[[dialogue]]
speaker = "コハルコ（覚醒）"
# 「トレーニングに付き合ってくれてありがとう。さすが会長さん、強かったね」
line = "「トレーニングに付き合ってくれてありがとう。さすが会長さん、強かったね」"

[[dialogue]]
speaker = "レイラ"
# 「ありがとうございました。はぁ……星術の制御に神経使ってくたくた……汗だくになっちゃいました。シャワー浴びてこようっと」
line = "「ありがとうございました。はぁ……星術の制御に神経使ってくたくた……汗だくになっちゃいました。シャワー浴びてこようっと」"

[[dialogue]]
speaker = "コハルコ（覚醒）"
# 「あ、私もシャワー浴びたいな。一緒に行こ、レイラ」
line = "「あ、私もシャワー浴びたいな。一緒に行こ、レイラ」"

[[dialogue]]
speaker = "コハルコ（覚醒）"
# 「そういえば、この前言ってたマザボ買ったの？　組んだら見せてよ」
line = "「そういえば、この前言ってたマザボ買ったの？　組んだら見せてよ」"

[[dialogue]]
speaker = "レイラ"
# 「それがですね、結局買ったんですけど、直後に値下がりしてモヤっちゃって、組むモチベまで下がってしまいました」
line = "「それがですね、結局買ったんですけど、直後に値下がりしてモヤっちゃって、組むモチベまで下がってしまいました」"

[[dialogue]]
speaker = "コハルコ（覚醒）"
# 「あー、あるある。実家がＰＣショップなのに言うのもなんだけど、ＰＣパーツって買い時難しいよね」
line = "「あー、あるある。実家がＰＣショップなのに言うのもなんだけど、ＰＣパーツって買い時難しいよね」"

[[dialogue]]
speaker = "レイラ"
# 「ですよねー。ＰＣ自作とは後悔することと見つけたり……」
line = "「ですよねー。ＰＣ自作とは後悔することと見つけたり……」"

[[dialogue]]
speaker = "コハルコ（覚醒）"
# 「ん？　どうしたの、会長さん？　……レイラと仲がいいって？」
line = "「ん？　どうしたの、会長さん？　……レイラと仲がいいって？」"

[[dialogue]]
speaker = "コハルコ（覚醒）"
# 「ハッカーでＰＣ自作が趣味って、ドンピシャだからね。そりゃあ仲良くなるよ」
line = "「ハッカーでＰＣ自作が趣味って、ドンピシャだからね。そりゃあ仲良くなるよ」"

[[dialogue]]
speaker = "コハルコ（覚醒）"
# 「命を狙われたっていっても、ハッカー活動でもっとドス黒い悪党を見てきたから、それくらいかわいいものだし」
line = "「命を狙われたっていっても、ハッカー活動でもっとドス黒い悪党を見てきたから、それくらいかわいいものだし」"

[[dialogue]]
speaker = "レイラ"
# 「その節は大変ご迷惑おかけしました……」
line = "「その節は大変ご迷惑おかけしました……」"

[[dialogue]]
speaker = "レイラ"
# 「でもその悪党はことごとくジャスティスウィザードに沈められているわけですよね。恐ろしや……」
line = "「でもその悪党はことごとくジャスティスウィザードに沈められているわけですよね。恐ろしや……」"

[[dialogue]]
speaker = "コハルコ（覚醒）"
# 「ただし！　ネットでジャスティスウィザードって名前付けたのは許してないから！」
line = "「ただし！　ネットでジャスティスウィザードって名前付けたのは許してないから！」"

[[dialogue]]
speaker = "レイラ"
# 「え～、ジャスティスウィザードかっこいいのに……」
line = "「え～、ジャスティスウィザードかっこいいのに……」"

[[dialogue]]
speaker = "unk"
# あんな事件があったというのに、長年の友人のように気安く話すコハルコさんとレイラ。
line = "あんな事件があったというのに、長年の友人のように気安く話すコハルコさんとレイラ。"

[[dialogue]]
speaker = "unk"
# ２人のやりとりを見ていると、つい先日のコラプサーとの激闘が、遠い昔のように感じられるのだった。
line = "２人のやりとりを見ていると、つい先日のコラプサーとの激闘が、遠い昔のように感じられるのだった。"
