[[dialogue]]
speaker = "unk"
# 第２話,環は有名人,P
line = "第２話,環は有名人,P"

[[dialogue]]
speaker = "unk"
# 今日は星徒会の活動がないので、真っ直ぐ帰ろうと思ったのだが──
line = "今日は星徒会の活動がないので、真っ直ぐ帰ろうと思ったのだが──"

[[dialogue]]
speaker = "環"
# 「会長～！　今ヒマ？　なら付き合ってよ」
line = "「会長～！　今ヒマ？　なら付き合ってよ」"

[[dialogue]]
speaker = "環"
# 「別に用事とかはないんだけど、なんとなく学園をブラブラしようと思ってさ。帰りたくなったら先帰っていいよ」
line = "「別に用事とかはないんだけど、なんとなく学園をブラブラしようと思ってさ。帰りたくなったら先帰っていいよ」"

[[dialogue]]
speaker = "環"
# 「だけど星徒会長たる者、先頭に立って戦うだけじゃなくて、生徒を見守るのも仕事でしょ？　たまには自分で見て回るのもいいんじゃない」
line = "「だけど星徒会長たる者、先頭に立って戦うだけじゃなくて、生徒を見守るのも仕事でしょ？　たまには自分で見て回るのもいいんじゃない」"

[[dialogue]]
speaker = "環"
# 「決まりだね。それじゃレッツゴー！」
line = "「決まりだね。それじゃレッツゴー！」"

[[dialogue]]
speaker = "環"
# 「モネ～、何か面白そうな本入ってる？」
line = "「モネ～、何か面白そうな本入ってる？」"

[[dialogue]]
speaker = "モネ"
# 「こんにちは、市倉さん。それなら歴史のコミックなんかはいかがですか？　歴史上重要な出来事を流れで理解することができるので、読むだけで勉強になりますよ」
line = "「こんにちは、市倉さん。それなら歴史のコミックなんかはいかがですか？　歴史上重要な出来事を流れで理解することができるので、読むだけで勉強になりますよ」"

[[dialogue]]
speaker = "環"
# 「いいね～、借りちゃおっかな。……でも見た目で漫画しか読まなさそうって思ってない？」
line = "「いいね～、借りちゃおっかな。……でも見た目で漫画しか読まなさそうって思ってない？」"

[[dialogue]]
speaker = "モネ"
# 「ギクッ」
line = "「ギクッ」"

[[dialogue]]
speaker = "環"
# 「はははっ、実際当たりだけどね。ボクでも読めそうな小説とかあったらまた教えてよ」
line = "「はははっ、実際当たりだけどね。ボクでも読めそうな小説とかあったらまた教えてよ」"

[[dialogue]]
speaker = "モネ"
# 「はい、オススメの一冊を用意しておきますね。ところで会長も何かご用件が？」
line = "「はい、オススメの一冊を用意しておきますね。ところで会長も何かご用件が？」"

[[dialogue]]
speaker = "環"
# 「会長はボクのおまけ！　ちょっと学園の見回りしてるだけだから、会長のことは気にしなくていいよ。ね？」
line = "「会長はボクのおまけ！　ちょっと学園の見回りしてるだけだから、会長のことは気にしなくていいよ。ね？」"

[[dialogue]]
speaker = "unk"
# そうそう
line = "そうそう"

[[dialogue]]
speaker = "モネ"
# 「はぁ……なるほど？」
line = "「はぁ……なるほど？」"

[[dialogue]]
speaker = "モネ"
# （なんだか会長と市倉さんがとても親しく見えるような……ハッ、もしかしてそういう関係なんでしょうか……？）
line = "（なんだか会長と市倉さんがとても親しく見えるような……ハッ、もしかしてそういう関係なんでしょうか……？）"

[[dialogue]]
speaker = "シャロン"
# 「おや、会長さまに環さま。大聖堂に何かご用事ですか？」
line = "「おや、会長さまに環さま。大聖堂に何かご用事ですか？」"

[[dialogue]]
speaker = "環"
# 「ううん、ちょっとシャロンに会いに来ただけ。いつも掃除とかありがとうね。おかげでいつ来ても綺麗だよ」
line = "「ううん、ちょっとシャロンに会いに来ただけ。いつも掃除とかありがとうね。おかげでいつ来ても綺麗だよ」"

[[dialogue]]
speaker = "シャロン"
# 「いいえ、女神様に仕える者として当然のことをしているまでです。むしろこの大聖堂をお掃除できるのはシスターとして栄誉ですから」
line = "「いいえ、女神様に仕える者として当然のことをしているまでです。むしろこの大聖堂をお掃除できるのはシスターとして栄誉ですから」"

[[dialogue]]
speaker = "環"
# 「きっと女神様も喜んでるよ。ね、会長？」
line = "「きっと女神様も喜んでるよ。ね、会長？」"

[[dialogue]]
speaker = "シャロン"
# 「いえいえそんな……畏れ多いです。ちなみに環さまと会長さまはどういったご関係なのでしょう？」
line = "「いえいえそんな……畏れ多いです。ちなみに環さまと会長さまはどういったご関係なのでしょう？」"

[[dialogue]]
speaker = "環"
# 「一緒にバイトしてたことがあるんだ。会長が新星学園に転入する前の話だね」
line = "「一緒にバイトしてたことがあるんだ。会長が新星学園に転入する前の話だね」"

[[dialogue]]
speaker = "シャロン"
# 「ふむふむ、そういうことでしたか」
line = "「ふむふむ、そういうことでしたか」"

[[dialogue]]
speaker = "シャロン"
# （親しいご様子でしたがどうりで……しかしそれ以上のご関係である可能性も？）
line = "（親しいご様子でしたがどうりで……しかしそれ以上のご関係である可能性も？）"

[[dialogue]]
speaker = "環"
# 「あ、セイファート学園長～！　こんにちはー！」
line = "「あ、セイファート学園長～！　こんにちはー！」"

[[dialogue]]
speaker = "セイファート"
# 「む……君か。それに星徒会長も一緒か。何か用件かね？」
line = "「む……君か。それに星徒会長も一緒か。何か用件かね？」"

[[dialogue]]
speaker = "環"
# 「いえ、会長と一緒に見回りしてたらお見かけしたので挨拶しただけです。執務がんばってくださ～い」
line = "「いえ、会長と一緒に見回りしてたらお見かけしたので挨拶しただけです。執務がんばってくださ～い」"

[[dialogue]]
speaker = "セイファート"
# 「ふむ、自発的に見回りをしていたのか。良い心掛けだ。ではな」
line = "「ふむ、自発的に見回りをしていたのか。良い心掛けだ。ではな」"

[[dialogue]]
speaker = "unk"
# 学園長とは仲いいのか？
line = "学園長とは仲いいのか？"

[[dialogue]]
speaker = "環"
# 「いや、全然。学園長がプリマステラでもない一般生徒と仲良くなるわけないじゃん。ボクは何度か挨拶してるから覚えてるみたいだけどね」
line = "「いや、全然。学園長がプリマステラでもない一般生徒と仲良くなるわけないじゃん。ボクは何度か挨拶してるから覚えてるみたいだけどね」"

[[dialogue]]
speaker = "環"
# 「でもまぁ……見た目の雰囲気ほど堅苦しい人じゃないんじゃないかな。そんな気はする」
line = "「でもまぁ……見た目の雰囲気ほど堅苦しい人じゃないんじゃないかな。そんな気はする」"

[[dialogue]]
speaker = "環"
# 「いや～、学園をブラブラするだけでもいろいろあったね。コハルコさんのシミュレーター調整を手伝ったり、紅明にエナジードリンクもらったり」
line = "「いや～、学園をブラブラするだけでもいろいろあったね。コハルコさんのシミュレーター調整を手伝ったり、紅明にエナジードリンクもらったり」"

[[dialogue]]
speaker = "環"
# 「フロレンシアがぶっ倒れたり、アニマさんの実験に巻き込まれたのはちょっとびっくりしたけど」
line = "「フロレンシアがぶっ倒れたり、アニマさんの実験に巻き込まれたのはちょっとびっくりしたけど」"

[[dialogue]]
speaker = "unk"
# 本当に知り合いが多いんだな
line = "本当に知り合いが多いんだな"

[[dialogue]]
speaker = "環"
# 「まだまだこんなもんじゃないよ。いろんな部活に助っ人で顔出してるから、もっともっと友達いるんだ」
line = "「まだまだこんなもんじゃないよ。いろんな部活に助っ人で顔出してるから、もっともっと友達いるんだ」"

[[dialogue]]
speaker = "環"
# 「──あ、寮長もお茶しに来たの？」
line = "「──あ、寮長もお茶しに来たの？」"

[[dialogue]]
speaker = "マハムート"
# 「マムとお呼びなさい。しかし、環さんはそもそも『ラルーナ』の寮生ではないでしょう。流星市国の生まれと聞いているのだけど？」
line = "「マムとお呼びなさい。しかし、環さんはそもそも『ラルーナ』の寮生ではないでしょう。流星市国の生まれと聞いているのだけど？」"

[[dialogue]]
speaker = "環"
# 「まぁそうなんだけどさ。うちは両親とも天使だけど、父さんも母さんも天界に帰省してて実質一人暮らしなんだよね」
line = "「まぁそうなんだけどさ。うちは両親とも天使だけど、父さんも母さんも天界に帰省してて実質一人暮らしなんだよね」"

[[dialogue]]
speaker = "環"
# 「だからお小遣い欲しさにバイトしてるんだけど、１人はさみしいし寮に入れてもらえないかな～」
line = "「だからお小遣い欲しさにバイトしてるんだけど、１人はさみしいし寮に入れてもらえないかな～」"

[[dialogue]]
speaker = "環"
# 「あーでも寮だと門限とかあるし、バイトしにくくなるから悩みどころだなぁ～……あ、そうだ」
line = "「あーでも寮だと門限とかあるし、バイトしにくくなるから悩みどころだなぁ～……あ、そうだ」"

[[dialogue]]
speaker = "環"
# 「ねぇねぇ、会長んちお邪魔していい？　居候しちゃおうっと」
line = "「ねぇねぇ、会長んちお邪魔していい？　居候しちゃおうっと」"

[[dialogue]]
speaker = "unk"
# 母さんがよければ大丈夫
line = "母さんがよければ大丈夫"

[[dialogue]]
speaker = "環"
# 「えっ、マジで！？　じゃあ本気で考えとこうかな～。会長のお母さんによろしくね！」
line = "「えっ、マジで！？　じゃあ本気で考えとこうかな～。会長のお母さんによろしくね！」"

[[dialogue]]
speaker = "マハムート"
# （この２人、妙に仲がいいわね……。そういう関係なのかしら？）
line = "（この２人、妙に仲がいいわね……。そういう関係なのかしら？）"

[[dialogue]]
speaker = "unk"
# しばらくの間、環と一緒にいると、みんなの視線がいつもと少し違う気がするのだった──
line = "しばらくの間、環と一緒にいると、みんなの視線がいつもと少し違う気がするのだった──"
