[[dialogue]]
speaker = "unk"
# 第１話,保健委員フロレンシア,P
line = "第１話,保健委員フロレンシア,P"

[[dialogue]]
speaker = "フロレンシア"
# 「ふぅ……大丈夫そうで良かった」
line = "「ふぅ……大丈夫そうで良かった」"

[[dialogue]]
speaker = "unk"
# 何かあったのか？
line = "何かあったのか？"

[[dialogue]]
speaker = "フロレンシア"
# 「あ、こんにちは、会長さん」
line = "「あ、こんにちは、会長さん」"

[[dialogue]]
speaker = "フロレンシア"
# 「シャロンさんを保健室に連れて行ったところでして。戦闘の後に貧血で倒れてしまったんです」
line = "「シャロンさんを保健室に連れて行ったところでして。戦闘の後に貧血で倒れてしまったんです」"

[[dialogue]]
speaker = "シャロン"
# 「きゅぅ～……」
line = "「きゅぅ～……」"

[[dialogue]]
speaker = "フロレンシア"
# 「少し休んでもらったら良くなりました。シャロンさんは慣れっこだって言ってましたけど、安心しました」
line = "「少し休んでもらったら良くなりました。シャロンさんは慣れっこだって言ってましたけど、安心しました」"

[[dialogue]]
speaker = "フロレンシア"
# 「星徒会のお仕事でお忙しいと思いますが、会長さんはお元気ですか？」
line = "「星徒会のお仕事でお忙しいと思いますが、会長さんはお元気ですか？」"

[[dialogue]]
speaker = "フロレンシア"
# 「……ええ、それなら良かったです。でも無理はしないでくださいね」
line = "「……ええ、それなら良かったです。でも無理はしないでくださいね」"

[[dialogue]]
speaker = "フロレンシア"
# 「それではまた。会長さんも、気分が優れない時は気兼ねなく保健委員を頼ってください」
line = "「それではまた。会長さんも、気分が優れない時は気兼ねなく保健委員を頼ってください」"

[[dialogue]]
speaker = "パワゴン"
# 「イイイイーーッッ！」
line = "「イイイイーーッッ！」"

[[dialogue]]
speaker = "unk"
# ぐっ……！
line = "ぐっ……！"

[[dialogue]]
speaker = "フロレンシア"
# 「モンスターは倒せましたけど、怪我が……今治療しますね！　傷を見せてください！」
line = "「モンスターは倒せましたけど、怪我が……今治療しますね！　傷を見せてください！」"

[[dialogue]]
speaker = "unk"
# 新星学園と流星学園では、保健委員は戦闘で負傷した星騎士や一般人を治療する役目も担っている。
line = "新星学園と流星学園では、保健委員は戦闘で負傷した星騎士や一般人を治療する役目も担っている。"

[[dialogue]]
speaker = "unk"
# のだが──
line = "のだが──"

[[dialogue]]
speaker = "フロレンシア"
# 「ひぁああああああっ！？　血が……血がこんなに……」
line = "「ひぁああああああっ！？　血が……血がこんなに……」"

[[dialogue]]
speaker = "フロレンシア"
# 「ガクッ」
line = "「ガクッ」"

[[dialogue]]
speaker = "unk"
# フロレンシアこそ大丈夫……？
line = "フロレンシアこそ大丈夫……？"

[[dialogue]]
speaker = "？？？"
# 「キヒヒ、キヒヒヒヒッ……」
line = "「キヒヒ、キヒヒヒヒッ……」"

[[dialogue]]
speaker = "フロレンシア？"
# 「ヒハハハハハハハハッ！！」
line = "「ヒハハハハハハハハッ！！」"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "フロレンシア？"
# 「あ～、最近ご無沙汰だったからシャバの空気がうまいぜ。ありがとよ、会長サン」
line = "「あ～、最近ご無沙汰だったからシャバの空気がうまいぜ。ありがとよ、会長サン」"

[[dialogue]]
speaker = "フロレンシア？"
# 「って、そういや怪我してるとこだったな」
line = "「って、そういや怪我してるとこだったな」"

[[dialogue]]
speaker = "フロレンシア？"
# 「どれどれ……なんだこんなもんか。死なねえ程度にもっとハデに怪我してくれりゃよかったんだが、普通のモンスターじゃこんなもんか」
line = "「どれどれ……なんだこんなもんか。死なねえ程度にもっとハデに怪我してくれりゃよかったんだが、普通のモンスターじゃこんなもんか」"

[[dialogue]]
speaker = "フロレンシア？"
# 「まあいいや、アタシが治してやる。ほれ、いた～いいた～いお注射だ」
line = "「まあいいや、アタシが治してやる。ほれ、いた～いいた～いお注射だ」"

[[dialogue]]
speaker = "unk"
# ぎゃ～～～～～～ッ！？
line = "ぎゃ～～～～～～ッ！？"

[[dialogue]]
speaker = "フロレンシア？"
# 「ヒハハッ、それが見たかったんだよ！　トゲだらけの蛇が全身の血管を這い回ってるような痛みだろ？　生きてるって感じがするだろ～？」
line = "「ヒハハッ、それが見たかったんだよ！　トゲだらけの蛇が全身の血管を這い回ってるような痛みだろ？　生きてるって感じがするだろ～？」"

[[dialogue]]
speaker = "フロレンシア？"
# 「いいザマだぜ……地面にのたうち回って、顔を苦痛に歪ませてよぉ。アタシはそういうのが好きなんだ」
line = "「いいザマだぜ……地面にのたうち回って、顔を苦痛に歪ませてよぉ。アタシはそういうのが好きなんだ」"

[[dialogue]]
speaker = "フロレンシア？"
# 「もっと悶えろ、もっと痛がれ……キヒヒッ、ヒャハハハハッ！」
line = "「もっと悶えろ、もっと痛がれ……キヒヒッ、ヒャハハハハッ！」"

[[dialogue]]
speaker = "フロレンシア？"
# 「……っと。もう痛みがおさまったか。どうだ、傷は塞がってるだろ」
line = "「……っと。もう痛みがおさまったか。どうだ、傷は塞がってるだろ」"

[[dialogue]]
speaker = "フロレンシア？"
# 「何驚いてやがる、保健委員なんだからそりゃ治すだろ。アタシの星術は痛みがある分、治りもはえーんだ」
line = "「何驚いてやがる、保健委員なんだからそりゃ治すだろ。アタシの星術は痛みがある分、治りもはえーんだ」"

[[dialogue]]
speaker = "フロレンシア？"
# 「チッ……まだモンスターがいやがったか。ヤツらの悲鳴は耳障りなんだよ。見かけばっか生き物らしくしてんじゃねぇ」
line = "「チッ……まだモンスターがいやがったか。ヤツらの悲鳴は耳障りなんだよ。見かけばっか生き物らしくしてんじゃねぇ」"

[[dialogue]]
speaker = "フロレンシア？"
# 「じゃあな。次はもっといい声聞かせてくれよ、会長サン」
line = "「じゃあな。次はもっといい声聞かせてくれよ、会長サン」"

[[dialogue]]
speaker = "フロレンシア"
# 「んん……会長、さん……？」
line = "「んん……会長、さん……？」"

[[dialogue]]
speaker = "フロレンシア"
# 「そうだ、私、会長さんの怪我を治療しようとして……あれ、もう治ってる……？　どうして……？」
line = "「そうだ、私、会長さんの怪我を治療しようとして……あれ、もう治ってる……？　どうして……？」"

[[dialogue]]
speaker = "フロレンシア"
# 「モンスター！？　あわわっ、私も戦わないと……でも私、支援とかの方が得意でして……」
line = "「モンスター！？　あわわっ、私も戦わないと……でも私、支援とかの方が得意でして……」"

[[dialogue]]
speaker = "フロレンシア"
# 「え～い、どうにでもなれ～！　ホーネットニードル！」
line = "「え～い、どうにでもなれ～！　ホーネットニードル！」"

[[dialogue]]
speaker = "フロレンシア"
# 「あ、倒せた……なんというかこう、いい感じのところに刺さったみたいです！」
line = "「あ、倒せた……なんというかこう、いい感じのところに刺さったみたいです！」"

[[dialogue]]
speaker = "フロレンシア"
# 「もう一度……プスッといきます！」
line = "「もう一度……プスッといきます！」"

[[dialogue]]
speaker = "フロレンシア"
# 「やった！　また倒せました！」
line = "「やった！　また倒せました！」"

[[dialogue]]
speaker = "フロレンシア"
# 「きゃっ！？　またモンスターが！？　うぅ～っ、こうなったらお注射打ちまくりですっ！」
line = "「きゃっ！？　またモンスターが！？　うぅ～っ、こうなったらお注射打ちまくりですっ！」"
