[[dialogue]]
speaker = "unk"
# 第１話,カフェテリアの新メニュー,P
line = "第１話,カフェテリアの新メニュー,P"

[[dialogue]]
speaker = "unk"
# カフェテリアの一角に人だかりが出来ていた。
line = "カフェテリアの一角に人だかりが出来ていた。"

[[dialogue]]
speaker = "unk"
# 気になって覗いてみると──
line = "気になって覗いてみると──"

[[dialogue]]
speaker = "サラン"
# 「んっ、はむ、はむ……んんん～……美味しい～♪」
line = "「んっ、はむ、はむ……んんん～……美味しい～♪」"

[[dialogue]]
speaker = "サラン"
# 「はむ……はむ……ん～♪　こっちも美味しい～♪」
line = "「はむ……はむ……ん～♪　こっちも美味しい～♪」"

[[dialogue]]
speaker = "unk"
# サランがデザートを食べていた。
line = "サランがデザートを食べていた。"

[[dialogue]]
speaker = "unk"
# それ自体は珍しい光景ではないが、テーブルの上には異常な数の皿やグラス、カップなどが並んでいる。
line = "それ自体は珍しい光景ではないが、テーブルの上には異常な数の皿やグラス、カップなどが並んでいる。"

[[dialogue]]
speaker = "サラン"
# 「ぽよ？　会長ちゃん、こんにちは～♪」
line = "「ぽよ？　会長ちゃん、こんにちは～♪」"

[[dialogue]]
speaker = "サラン"
# 「今ね、蛍火ちゃんに頼まれて、カフェテリアのデザートの試食をしてるんだよ～♪」
line = "「今ね、蛍火ちゃんに頼まれて、カフェテリアのデザートの試食をしてるんだよ～♪」"

[[dialogue]]
speaker = "蛍火"
# 「どうですか、サランさん？」
line = "「どうですか、サランさん？」"

[[dialogue]]
speaker = "サラン"
# 「ん～、味的には全然問題ないと思うけどな～」
line = "「ん～、味的には全然問題ないと思うけどな～」"

[[dialogue]]
speaker = "サラン"
# 「でも何だろう、あとちょっとで何か分かりそうな気がするんだよね～」
line = "「でも何だろう、あとちょっとで何か分かりそうな気がするんだよね～」"

[[dialogue]]
speaker = "蛍火"
# 「追加でもっと作ってもらいますか？」
line = "「追加でもっと作ってもらいますか？」"

[[dialogue]]
speaker = "サラン"
# 「うん、お願いだよ～」
line = "「うん、お願いだよ～」"

[[dialogue]]
speaker = "unk"
# この量はもう、試食とは言えないのでは
line = "この量はもう、試食とは言えないのでは"

[[dialogue]]
speaker = "unk"
# まだ頼むの！？
line = "まだ頼むの！？"

[[dialogue]]
speaker = "サラン"
# 「ぽよ……こんなに食べちゃってたんだ～。えへへ、気が付かなかったよ～♪」
line = "「ぽよ……こんなに食べちゃってたんだ～。えへへ、気が付かなかったよ～♪」"

[[dialogue]]
speaker = "蛍火"
# 「実はカフェテリアのデザートの売れ行きが芳しくないのです」
line = "「実はカフェテリアのデザートの売れ行きが芳しくないのです」"

[[dialogue]]
speaker = "蛍火"
# 「自分たちでもいろいろ考えてみたのですが原因が分からなくて……それでサランさんにお願いしました」
line = "「自分たちでもいろいろ考えてみたのですが原因が分からなくて……それでサランさんにお願いしました」"

[[dialogue]]
speaker = "蛍火"
# 「あ、そうだ……よければ師匠にも、試食をお願いしていいですか？」
line = "「あ、そうだ……よければ師匠にも、試食をお願いしていいですか？」"

[[dialogue]]
speaker = "サラン"
# 「そうしよそうしよ～♪　えへへ、それじゃ会長ちゃん、あ～ん……♪」
line = "「そうしよそうしよ～♪　えへへ、それじゃ会長ちゃん、あ～ん……♪」"

[[dialogue]]
speaker = "unk"
# 嬉しいけど視線が……
line = "嬉しいけど視線が……"

[[dialogue]]
speaker = "unk"
# た、食べさせてくれる系！？
line = "た、食べさせてくれる系！？"

[[dialogue]]
speaker = "サラン"
# 「ぽよ？　ん～、そっかぁ……みんなの前じゃ恥ずかしいよね～……」
line = "「ぽよ？　ん～、そっかぁ……みんなの前じゃ恥ずかしいよね～……」"

[[dialogue]]
speaker = "蛍火"
# 「大丈夫ですよ。師匠の分も作ってくださいとお願いしてきますから」
line = "「大丈夫ですよ。師匠の分も作ってくださいとお願いしてきますから」"

[[dialogue]]
speaker = "サラン"
# 「ありがとう～」
line = "「ありがとう～」"

[[dialogue]]
speaker = "サラン"
# 「会長ちゃん、ご馳走になるぶんは、ちゃんとメニュー作りに協力しないとね～」
line = "「会長ちゃん、ご馳走になるぶんは、ちゃんとメニュー作りに協力しないとね～」"

[[dialogue]]
speaker = "蛍火"
# 「それでは、２人分を持ってきます」
line = "「それでは、２人分を持ってきます」"

[[dialogue]]
speaker = "unk"
# しばらくして、蛍火の持ってきてくれたデザートを俺も試食してみる。
line = "しばらくして、蛍火の持ってきてくれたデザートを俺も試食してみる。"

[[dialogue]]
speaker = "unk"
# すごく美味しいと思うけど？
line = "すごく美味しいと思うけど？"

[[dialogue]]
speaker = "unk"
# ……わからない
line = "……わからない"

[[dialogue]]
speaker = "サラン"
# 「サランもとっても美味しいと思うんだけどね～」
line = "「サランもとっても美味しいと思うんだけどね～」"

[[dialogue]]
speaker = "蛍火"
# 「ですが……サランさんが『美食酔い』になっていません」
line = "「ですが……サランさんが『美食酔い』になっていません」"

[[dialogue]]
speaker = "unk"
# サランの美食酔い。
line = "サランの美食酔い。"

[[dialogue]]
speaker = "unk"
# 美味しい料理を食べると、サランはまるでお酒によったようになってしまう現象だ。
line = "美味しい料理を食べると、サランはまるでお酒によったようになってしまう現象だ。"

[[dialogue]]
speaker = "unk"
# それが発動する気配がないことを考えると、やはりこの料理には何か問題があるのかもしれない。
line = "それが発動する気配がないことを考えると、やはりこの料理には何か問題があるのかもしれない。"

[[dialogue]]
speaker = "サラン"
# 「あ……もしかしたら、季節感が足りないのかも……」
line = "「あ……もしかしたら、季節感が足りないのかも……」"

[[dialogue]]
speaker = "蛍火"
# 「一応、夏用のメニューにはしているのですが……」
line = "「一応、夏用のメニューにはしているのですが……」"

[[dialogue]]
speaker = "サラン"
# 「かき氷にスムージー、フローズンヨーグルトに水ようかん……確かに夏メニューなんだけど……」
line = "「かき氷にスムージー、フローズンヨーグルトに水ようかん……確かに夏メニューなんだけど……」"

[[dialogue]]
speaker = "サラン"
# 「これをもっともっーと、夏っぽくするの。そうしたらもっと美味しく食べられると思うよ～♪」
line = "「これをもっともっーと、夏っぽくするの。そうしたらもっと美味しく食べられると思うよ～♪」"

[[dialogue]]
speaker = "蛍火"
# 「なるほど……夏っぽく、ですか……何かいいアイデアはありますか？」
line = "「なるほど……夏っぽく、ですか……何かいいアイデアはありますか？」"

[[dialogue]]
speaker = "サラン"
# 「うーん……」
line = "「うーん……」"

[[dialogue]]
speaker = "unk"
# サランがしばらく考え込む。
line = "サランがしばらく考え込む。"

[[dialogue]]
speaker = "unk"
# やがてパッと表情を明るくして、ポンと手を打った。
line = "やがてパッと表情を明るくして、ポンと手を打った。"

[[dialogue]]
speaker = "サラン"
# 「そうだ、いいことを思いついた♪　会長ちゃん、今からプールに行こ～♪」
line = "「そうだ、いいことを思いついた♪　会長ちゃん、今からプールに行こ～♪」"

[[dialogue]]
speaker = "蛍火"
# 「えっ、どうして急に！？」
line = "「えっ、どうして急に！？」"

[[dialogue]]
speaker = "サラン"
# 「夏っぽい格好で夏っぽいことをしていたら、いいアイデアが浮かぶかもって思ったの～」
line = "「夏っぽい格好で夏っぽいことをしていたら、いいアイデアが浮かぶかもって思ったの～」"

[[dialogue]]
speaker = "unk"
# いいアイデアかもしれない！
line = "いいアイデアかもしれない！"

[[dialogue]]
speaker = "サラン"
# 「でしょう？　それじゃ蛍火ちゃん、ちょっと出かけてくるね～」
line = "「でしょう？　それじゃ蛍火ちゃん、ちょっと出かけてくるね～」"

[[dialogue]]
speaker = "蛍火"
# 「お、お願いします」
line = "「お、お願いします」"

[[dialogue]]
speaker = "サラン"
# 「ぽよっ♪　やっぱり水着になった方が、夏っぽいデザートのイメージが浮かびやすいかも～♪」
line = "「ぽよっ♪　やっぱり水着になった方が、夏っぽいデザートのイメージが浮かびやすいかも～♪」"

[[dialogue]]
speaker = "unk"
# サランが無邪気にはしゃぐたびに、サランのたわわなものがぷるんぷるんと揺れる。
line = "サランが無邪気にはしゃぐたびに、サランのたわわなものがぷるんぷるんと揺れる。"

[[dialogue]]
speaker = "サラン"
# 「ぽよ？　会長ちゃん、どうしたのかな～？」
line = "「ぽよ？　会長ちゃん、どうしたのかな～？」"

[[dialogue]]
speaker = "unk"
# な、なんでもないよ
line = "な、なんでもないよ"

[[dialogue]]
speaker = "サラン"
# 「えへへ、おかしな会長ちゃんだね～」
line = "「えへへ、おかしな会長ちゃんだね～」"

[[dialogue]]
speaker = "unk"
# とっさに視線をそらしたおかげでサランには気付かれなかったみたいだ。
line = "とっさに視線をそらしたおかげでサランには気付かれなかったみたいだ。"

[[dialogue]]
speaker = "サラン"
# 「水着になって気分は出たけど、まだまだインスピレーションが足りないよ～」
line = "「水着になって気分は出たけど、まだまだインスピレーションが足りないよ～」"

[[dialogue]]
speaker = "サラン"
# 「やっぱり水に入って泳いだ方が、いいアイデア浮かぶのかな？　でもサラン、泳げないし……」
line = "「やっぱり水に入って泳いだ方が、いいアイデア浮かぶのかな？　でもサラン、泳げないし……」"

[[dialogue]]
speaker = "サラン"
# 「そうだ会長ちゃん♪　サランが上手く泳げるように教えて欲しいの～♪」
line = "「そうだ会長ちゃん♪　サランが上手く泳げるように教えて欲しいの～♪」"

[[dialogue]]
speaker = "unk"
# そういって腕に抱きついてくるサラン。
line = "そういって腕に抱きついてくるサラン。"

[[dialogue]]
speaker = "unk"
# 弾力が腕に押し付けられて、いやでも煩悩をかきたてられてしまう。
line = "弾力が腕に押し付けられて、いやでも煩悩をかきたてられてしまう。"

[[dialogue]]
speaker = "unk"
# サランは無自覚にやってるんだろうけど──俺は理性を保つために全力を傾けなければならなかった。
line = "サランは無自覚にやってるんだろうけど──俺は理性を保つために全力を傾けなければならなかった。"
