[[dialogue]]
speaker = "unk"
# 第３話,炎の天使ＶＳ炎の料理人,P
line = "第３話,炎の天使ＶＳ炎の料理人,P"

[[dialogue]]
speaker = "unk"
# アルモと街へ観光に行ってからしばらく経ったある日。食欲に目覚めた彼女を、学園のカフェテリアへ案内することになった。
line = "アルモと街へ観光に行ってからしばらく経ったある日。食欲に目覚めた彼女を、学園のカフェテリアへ案内することになった。"

[[dialogue]]
speaker = "アルモタヘル"
# 「ふむ、ここが生徒達が利用する食事処か。良き雰囲気の場所だ」
line = "「ふむ、ここが生徒達が利用する食事処か。良き雰囲気の場所だ」"

[[dialogue]]
speaker = "アルモタヘル"
# 「然れど、ここの料理が美味だというのは本当か？」
line = "「然れど、ここの料理が美味だというのは本当か？」"

[[dialogue]]
speaker = "アルモタヘル"
# 「あれから我は、いくつもの名店を食べ歩いている。ここの料理が美味だといっても、それはあくまで生徒たちに合わせた値段設定の範囲内であろう？」
line = "「あれから我は、いくつもの名店を食べ歩いている。ここの料理が美味だといっても、それはあくまで生徒たちに合わせた値段設定の範囲内であろう？」"

[[dialogue]]
speaker = "unk"
# 蛍火の作る料理は高級店にも負けないよ
line = "蛍火の作る料理は高級店にも負けないよ"

[[dialogue]]
speaker = "unk"
# そんなことはない。
line = "そんなことはない。"

[[dialogue]]
speaker = "アルモタヘル"
# 「東雲蛍火、といったか。その者も学園の生徒なのだろう？　プロの料理人に匹敵する腕前とは、にわかには信じ難いが……」
line = "「東雲蛍火、といったか。その者も学園の生徒なのだろう？　プロの料理人に匹敵する腕前とは、にわかには信じ難いが……」"

[[dialogue]]
speaker = "アルモタヘル"
# 「……む？　この、背中に感じる鋭い視線は？　何奴！　隠れてなどおらず、堂々と姿を現すがよい！」
line = "「……む？　この、背中に感じる鋭い視線は？　何奴！　隠れてなどおらず、堂々と姿を現すがよい！」"

[[dialogue]]
speaker = "蛍火"
# 「……はい」
line = "「……はい」"

[[dialogue]]
speaker = "アルモタヘル"
# 「さては、お前が件の料理人か。……我は守護天使《命脈》のアルモタヘル。親しみを込めて、アルモたんと呼ぶがよい」
line = "「さては、お前が件の料理人か。……我は守護天使《命脈》のアルモタヘル。親しみを込めて、アルモたんと呼ぶがよい」"

[[dialogue]]
speaker = "蛍火"
# 「新星学園２年生、東雲蛍火……。本日、アルモタヘル様が私の料理を食べに来ることは、師匠から事前に連絡を頂いていました」
line = "「新星学園２年生、東雲蛍火……。本日、アルモタヘル様が私の料理を食べに来ることは、師匠から事前に連絡を頂いていました」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ほう、それ故に闘志溢れた鋭い視線を我に向けていたというわけか。料理人と審査人、その両名が出会えば戦いは必定だからな」
line = "「ほう、それ故に闘志溢れた鋭い視線を我に向けていたというわけか。料理人と審査人、その両名が出会えば戦いは必定だからな」"

[[dialogue]]
speaker = "unk"
# 戦い？　いや待って、何の話？
line = "戦い？　いや待って、何の話？"

[[dialogue]]
speaker = "蛍火"
# 「……なるほど、アルモタヘル様は既に審査人の領域へ達しておりましたか。準備しておいて正解でした」
line = "「……なるほど、アルモタヘル様は既に審査人の領域へ達しておりましたか。準備しておいて正解でした」"

[[dialogue]]
speaker = "蛍火"
# 「私も真の料理人である父の背中を見て育った身。その挑戦、受けて立ちましょう」
line = "「私も真の料理人である父の背中を見て育った身。その挑戦、受けて立ちましょう」"

[[dialogue]]
speaker = "unk"
# 俺だけ流れに付いて行けてないんだけど！？
line = "俺だけ流れに付いて行けてないんだけど！？"

[[dialogue]]
speaker = "unk"
# 待って待って！！
line = "待って待って！！"

[[dialogue]]
speaker = "アルモタヘル"
# 「ふっ、その意気や良し。鬼の子よ、せいぜい我の舌を楽しませるがよい！」
line = "「ふっ、その意気や良し。鬼の子よ、せいぜい我の舌を楽しませるがよい！」"

[[dialogue]]
speaker = "蛍火"
# 「それでは、こちらをどうぞ。カフェテリアで扱っている牛肩ロース肉を使ったステーキです」
line = "「それでは、こちらをどうぞ。カフェテリアで扱っている牛肩ロース肉を使ったステーキです」"

[[dialogue]]
speaker = "unk"
# ──実食！！！
line = "──実食！！！"

[[dialogue]]
speaker = "アルモタヘル"
# 「……ふむ、悪いが今の我なら見るだけで肉の品質がわかる。これは安い肉だな」
line = "「……ふむ、悪いが今の我なら見るだけで肉の品質がわかる。これは安い肉だな」"

[[dialogue]]
speaker = "アルモタヘル"
# 「鬼の子よ。我を舐めているな？　既にいくつもの有名な高級店を渡り歩いた身。学園の食堂レベルでは、我の舌を唸らせるのは困難と心得よ。……もぐもぐ」
line = "「鬼の子よ。我を舐めているな？　既にいくつもの有名な高級店を渡り歩いた身。学園の食堂レベルでは、我の舌を唸らせるのは困難と心得よ。……もぐもぐ」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ふっ……やはりな。肉の品質は普通と言わざるを得な──」
line = "「ふっ……やはりな。肉の品質は普通と言わざるを得な──」"

[[dialogue]]
speaker = "unk"
# アルモたぁぁぁ────んッ！！？
line = "アルモたぁぁぁ────んッ！！？"

[[dialogue]]
speaker = "蛍火"
# 「な、何かのドッキリですか、これ？」
line = "「な、何かのドッキリですか、これ？」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ドッキリではない」
line = "「ドッキリではない」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ビックリだ、もぐもぐ」
line = "「ビックリだ、もぐもぐ」"

[[dialogue]]
speaker = "unk"
# いや、こっちがビックリなんだが！？
line = "いや、こっちがビックリなんだが！？"

[[dialogue]]
speaker = "蛍火"
# 「お皿を持ったまま、肉もソースすらもこぼさずに、着地した……！？」
line = "「お皿を持ったまま、肉もソースすらもこぼさずに、着地した……！？」"

[[dialogue]]
speaker = "アルモタヘル"
# 「もぐもぐ……ごっくん。我が浅はかであった……高級な肉をいくつも口にしたというだけで、さも食を知り尽くしたかのような言動……」
line = "「もぐもぐ……ごっくん。我が浅はかであった……高級な肉をいくつも口にしたというだけで、さも食を知り尽くしたかのような言動……」"

[[dialogue]]
speaker = "アルモタヘル"
# 「食材の品質が美食のすべてを支配するわけではないのだと、このステーキで思い知らされた。高級な肉ではないからこそ、調理の工夫により生まれる美味……」
line = "「食材の品質が美食のすべてを支配するわけではないのだと、このステーキで思い知らされた。高級な肉ではないからこそ、調理の工夫により生まれる美味……」"

[[dialogue]]
speaker = "アルモタヘル"
# 「そう、実に美味であった……む？　なんだこれは？」
line = "「そう、実に美味であった……む？　なんだこれは？」"

[[dialogue]]
speaker = "unk"
# アルモ、涙が……！
line = "アルモ、涙が……！"

[[dialogue]]
speaker = "アルモタヘル"
# 「涙……？　我は泣いているのか？　これは一体どういうことだ……？」
line = "「涙……？　我は泣いているのか？　これは一体どういうことだ……？」"

[[dialogue]]
speaker = "アルモタヘル"
# 「そうか。美味であることに、我は『感動』したのか……」
line = "「そうか。美味であることに、我は『感動』したのか……」"

[[dialogue]]
speaker = "アルモタヘル"
# 「……認めよう、東雲蛍火よ。我の完敗だ。お前は、間違いなく……我の知るプロの者たちに匹敵──いや、それを上回る実力の料理人だ」
line = "「……認めよう、東雲蛍火よ。我の完敗だ。お前は、間違いなく……我の知るプロの者たちに匹敵──いや、それを上回る実力の料理人だ」"

[[dialogue]]
speaker = "蛍火"
# 「……ありがとうございます、アルモタヘル様」
line = "「……ありがとうございます、アルモタヘル様」"

[[dialogue]]
speaker = "unk"
# なら、勝者の願いを聞いてあげてくれないかな
line = "なら、勝者の願いを聞いてあげてくれないかな"

[[dialogue]]
speaker = "アルモタヘル"
# 「願いを？　よかろう。我に出来ることならば、申してみるがよい」
line = "「願いを？　よかろう。我に出来ることならば、申してみるがよい」"

[[dialogue]]
speaker = "unk"
# ──蛍火が極度の緊張しいであること、それ故に友達が少なくて増やしたいと思っていることを、アルモに話して聞かせた。
line = "──蛍火が極度の緊張しいであること、それ故に友達が少なくて増やしたいと思っていることを、アルモに話して聞かせた。"

[[dialogue]]
speaker = "アルモタヘル"
# 「それで、我とも友達になりたい、と……？」
line = "「それで、我とも友達になりたい、と……？」"

[[dialogue]]
speaker = "蛍火"
# 「嫌でしたら、別に無理にとは……」
line = "「嫌でしたら、別に無理にとは……」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ふっ……そんな簡単なことか。優れた料理人と友になれるなど、むしろ光栄だ」
line = "「ふっ……そんな簡単なことか。優れた料理人と友になれるなど、むしろ光栄だ」"

[[dialogue]]
speaker = "蛍火"
# 「……！　それでは……」
line = "「……！　それでは……」"

[[dialogue]]
speaker = "アルモタヘル"
# 「然り。我が友、蛍火よ。我にもっと、お前の作る美味な肉料理を食べさせてくれまいか」
line = "「然り。我が友、蛍火よ。我にもっと、お前の作る美味な肉料理を食べさせてくれまいか」"

[[dialogue]]
speaker = "蛍火"
# 「は、はい！　喜んで……！　アルモ様」
line = "「は、はい！　喜んで……！　アルモ様」"

[[dialogue]]
speaker = "unk"
# 蛍火は緊張が解けて、アルモと握手を交わすと、リラックスモードの笑顔を見せる。
line = "蛍火は緊張が解けて、アルモと握手を交わすと、リラックスモードの笑顔を見せる。"

[[dialogue]]
speaker = "unk"
# これで、めでたしめでたしかと思われたが──
line = "これで、めでたしめでたしかと思われたが──"

[[dialogue]]
speaker = "アルモタヘル"
# 「蛍火よ、次はこの肉料理を注文する」
line = "「蛍火よ、次はこの肉料理を注文する」"

[[dialogue]]
speaker = "蛍火"
# 「ふふっ。はい、アルモ様！　喜んで」
line = "「ふふっ。はい、アルモ様！　喜んで」"

[[dialogue]]
speaker = "unk"
# 延々と食べ続けるアルモと、幸せそうに料理を提供し続ける蛍火を、慌てて止めることになるのだった。
line = "延々と食べ続けるアルモと、幸せそうに料理を提供し続ける蛍火を、慌てて止めることになるのだった。"
