[[dialogue]]
speaker = "unk"
# 第２話,汐ルカルカの『お姉ちゃん』,P
line = "第２話,汐ルカルカの『お姉ちゃん』,P"

[[dialogue]]
speaker = "unk"
# 『汐ルカルカ』の水着衣装の発表。そして新曲の動画が公開されて、しばらく経ったある日の放課後のこと──
line = "『汐ルカルカ』の水着衣装の発表。そして新曲の動画が公開されて、しばらく経ったある日の放課後のこと──"

[[dialogue]]
speaker = "ルルカ"
# 「よーっし！　モンスター撃破～♪　アナちゃん、記録はどうだった？」
line = "「よーっし！　モンスター撃破～♪　アナちゃん、記録はどうだった？」"

[[dialogue]]
speaker = "アナ"
# 「イエス。先ほどよりもタイムが縮まりました。ルルカさんも水着フォームに慣れてきたようですね」
line = "「イエス。先ほどよりもタイムが縮まりました。ルルカさんも水着フォームに慣れてきたようですね」"

[[dialogue]]
speaker = "リーリア"
# 「だねー。即席のクラスメイトチームでこれだけの成績が出せるなら、もうばっちりだよね。お疲れマジカル！」
line = "「だねー。即席のクラスメイトチームでこれだけの成績が出せるなら、もうばっちりだよね。お疲れマジカル！」"

[[dialogue]]
speaker = "アナ"
# 「お疲れマジカルです」
line = "「お疲れマジカルです」"

[[dialogue]]
speaker = "ルルカ"
# 「２人とも模擬戦闘に付き合ってくれてありがとう！　お疲れマジカル～♪」
line = "「２人とも模擬戦闘に付き合ってくれてありがとう！　お疲れマジカル～♪」"

[[dialogue]]
speaker = "unk"
# その挨拶、流行ってるの？
line = "その挨拶、流行ってるの？"

[[dialogue]]
speaker = "ルルカ"
# 「あっ、お兄ちゃん！　あたしたちの訓練、見てくれてたの？」
line = "「あっ、お兄ちゃん！　あたしたちの訓練、見てくれてたの？」"

[[dialogue]]
speaker = "アナ"
# 「会長、朗報です。ルルカさんが覚醒した水着フォームの数値計測をした結果、十分に実戦が可能との結論に至りました」
line = "「会長、朗報です。ルルカさんが覚醒した水着フォームの数値計測をした結果、十分に実戦が可能との結論に至りました」"

[[dialogue]]
speaker = "リーリア"
# 「これは今後、センパイの指揮が試されちゃうことになりそうですね～？　頑張ってください！」
line = "「これは今後、センパイの指揮が試されちゃうことになりそうですね～？　頑張ってください！」"

[[dialogue]]
speaker = "unk"
# ああ、任せてくれ
line = "ああ、任せてくれ"

[[dialogue]]
speaker = "ルルカ"
# 「お兄ちゃんを助けられるように、あたしも頑張るからね！」
line = "「お兄ちゃんを助けられるように、あたしも頑張るからね！」"

[[dialogue]]
speaker = "リーリア"
# 「あ、そういえば話は変わるんだけど……ルルカちゃんってＶチューバーの汐ルカルカって知ってる？」
line = "「あ、そういえば話は変わるんだけど……ルルカちゃんってＶチューバーの汐ルカルカって知ってる？」"

[[dialogue]]
speaker = "ルルカ"
# 「うぇっ！？　な、何で？　そんなことをいきなりっ……」
line = "「うぇっ！？　な、何で？　そんなことをいきなりっ……」"

[[dialogue]]
speaker = "リーリア"
# 「え。だってその水着、ルカルカの新アバターとそっくりだから気になっちゃって」
line = "「え。だってその水着、ルカルカの新アバターとそっくりだから気になっちゃって」"

[[dialogue]]
speaker = "ルルカ"
# 「え゛っ──！？」
line = "「え゛っ──！？」"

[[dialogue]]
speaker = "unk"
# リ、リーリアもＶチューバーを見るの？
line = "リ、リーリアもＶチューバーを見るの？"

[[dialogue]]
speaker = "リーリア"
# 「えー、そりゃあ見ますよ。今どきの乙女ですから～」
line = "「えー、そりゃあ見ますよ。今どきの乙女ですから～」"

[[dialogue]]
speaker = "アナ"
# 「私も汐ルカルカは知っていますよ。人間界の文化研究も、留学の目的。流行とされるものは当然調査をしていますから」
line = "「私も汐ルカルカは知っていますよ。人間界の文化研究も、留学の目的。流行とされるものは当然調査をしていますから」"

[[dialogue]]
speaker = "ルルカ"
# 「な、ななな、なるほどっ……２人とも、ルカルカの視聴者さん、なんだ……？」
line = "「な、ななな、なるほどっ……２人とも、ルカルカの視聴者さん、なんだ……？」"

[[dialogue]]
speaker = "リーリア"
# 「うん！　特にショート動画で切り抜かれる、激辛ラーメンチャレンジ。あれ大好き～♪」
line = "「うん！　特にショート動画で切り抜かれる、激辛ラーメンチャレンジ。あれ大好き～♪」"

[[dialogue]]
speaker = "アナ"
# 「私も好きです。女性が出してはいけないような汚い声が癖になります」
line = "「私も好きです。女性が出してはいけないような汚い声が癖になります」"

[[dialogue]]
speaker = "ルルカ"
# （そこは歌動画を見てよぉ……！）
line = "（そこは歌動画を見てよぉ……！）"

[[dialogue]]
speaker = "リーリア"
# 「ルルカちゃんって、いつもの戦闘服もルカルカの衣装とそっくりでしょ？　で、今回の水着フォームも瓜二つ」
line = "「ルルカちゃんって、いつもの戦闘服もルカルカの衣装とそっくりでしょ？　で、今回の水着フォームも瓜二つ」"

[[dialogue]]
speaker = "アナ"
# 「なるほど。言われてみればそうですね」
line = "「なるほど。言われてみればそうですね」"

[[dialogue]]
speaker = "ルルカ"
# （どどどどどっ、どうしよう！？　お兄ちゃん、身バレ！？　もしかして身バレしちゃった！？）
line = "（どどどどどっ、どうしよう！？　お兄ちゃん、身バレ！？　もしかして身バレしちゃった！？）"

[[dialogue]]
speaker = "unk"
# （落ち着こう、まだバレたわけじゃない）
line = "（落ち着こう、まだバレたわけじゃない）"

[[dialogue]]
speaker = "リーリア"
# 「私、思ったんですよねえ。ルルカちゃんはきっと──」
line = "「私、思ったんですよねえ。ルルカちゃんはきっと──」"

[[dialogue]]
speaker = "ルルカ"
# 「ひぃ～っ！？」
line = "「ひぃ～っ！？」"

[[dialogue]]
speaker = "リーリア"
# 「汐ルカルカの『お姉ちゃん』なんでしょ！　ねっ♪」
line = "「汐ルカルカの『お姉ちゃん』なんでしょ！　ねっ♪」"

[[dialogue]]
speaker = "ルルカ"
# 「はっ……？」
line = "「はっ……？」"

[[dialogue]]
speaker = "unk"
# お、お姉ちゃん？
line = "お、お姉ちゃん？"

[[dialogue]]
speaker = "アナ"
# 「会長。ご存じないのですか？　汐ルカルカは、自身の男性ファンを『お兄ちゃん』、女性ファンを『お姉ちゃん』と呼称します」
line = "「会長。ご存じないのですか？　汐ルカルカは、自身の男性ファンを『お兄ちゃん』、女性ファンを『お姉ちゃん』と呼称します」"

[[dialogue]]
speaker = "リーリア"
# 「ねー。ルルカちゃん、きっとメンバーシップにも入ってるよ。相当熱狂的なルカルカファンなんだよ、きっと」
line = "「ねー。ルルカちゃん、きっとメンバーシップにも入ってるよ。相当熱狂的なルカルカファンなんだよ、きっと」"

[[dialogue]]
speaker = "アナ"
# 「はい。私の水着フォームが覚醒した時も、その時着ていた水着がそのまま戦闘服となりました」
line = "「はい。私の水着フォームが覚醒した時も、その時着ていた水着がそのまま戦闘服となりました」"

[[dialogue]]
speaker = "アナ"
# 「おそらくリゾート結界の疑似守護星は、本人の強いイメージに影響を受ける傾向があるのだと思います。あくまで憶測ですが」
line = "「おそらくリゾート結界の疑似守護星は、本人の強いイメージに影響を受ける傾向があるのだと思います。あくまで憶測ですが」"

[[dialogue]]
speaker = "リーリア"
# 「うんうん！　ルルカちゃんってルカルカのことがすっごく好きなんだな～って。……あ、もしかして違った？」
line = "「うんうん！　ルルカちゃんってルカルカのことがすっごく好きなんだな～って。……あ、もしかして違った？」"

[[dialogue]]
speaker = "ルルカ"
# 「え、え、えっと──」
line = "「え、え、えっと──」"

[[dialogue]]
speaker = "ルルカ"
# 「そ、そうっ！　あたし、実は汐ルカルカの大ファンなの！！　デビューした時からずーっと追ってるんだぁ！！」
line = "「そ、そうっ！　あたし、実は汐ルカルカの大ファンなの！！　デビューした時からずーっと追ってるんだぁ！！」"

[[dialogue]]
speaker = "ルルカ"
# 「もぉ可愛いからね、とにかく可愛いからね！　歌もうまいしダンスもできるし、トークだってテンポが良くて、えっと、えっとえっと──」
line = "「もぉ可愛いからね、とにかく可愛いからね！　歌もうまいしダンスもできるし、トークだってテンポが良くて、えっと、えっとえっと──」"

[[dialogue]]
speaker = "リーリア"
# 「あ、やっぱりそうなんだ～♪」
line = "「あ、やっぱりそうなんだ～♪」"

[[dialogue]]
speaker = "アナ"
# 「意外です。ルルカさんが、そこまでルカルカフリークだったとは」
line = "「意外です。ルルカさんが、そこまでルカルカフリークだったとは」"

[[dialogue]]
speaker = "ルルカ"
# 「もぉ大好きだよぉ！　耳かき動画も癒されるしラーメン食べてむせてるところは笑えるし！」
line = "「もぉ大好きだよぉ！　耳かき動画も癒されるしラーメン食べてむせてるところは笑えるし！」"

[[dialogue]]
speaker = "ルルカ"
# 「通知アラートも設定してるしメンバーシップアイコンも金冠だよ！　最古参！　ルカルカのことなら何でも聞いて！」
line = "「通知アラートも設定してるしメンバーシップアイコンも金冠だよ！　最古参！　ルカルカのことなら何でも聞いて！」"

[[dialogue]]
speaker = "ルルカ"
# 「で、でもでも！　でもね！？　ルカルカの一番の魅力は歌だから！　歌動画を聴いて！　ねっ！！　お願いだからぁ～っ！！」
line = "「で、でもでも！　でもね！？　ルカルカの一番の魅力は歌だから！　歌動画を聴いて！　ねっ！！　お願いだからぁ～っ！！」"

[[dialogue]]
speaker = "アナ"
# 「あ、はい……わ、わかりました……歌ですね……？」
line = "「あ、はい……わ、わかりました……歌ですね……？」"

[[dialogue]]
speaker = "リーリア"
# 「お、おぉ～……流石は戦闘服がアバターそっくりになっちゃうレベルの『お姉ちゃん』……パッションすごーい……」
line = "「お、おぉ～……流石は戦闘服がアバターそっくりになっちゃうレベルの『お姉ちゃん』……パッションすごーい……」"

[[dialogue]]
speaker = "unk"
# （でもここはこれで乗り切るしか……！）
line = "（でもここはこれで乗り切るしか……！）"

[[dialogue]]
speaker = "unk"
# （２人が若干引いている……！）
line = "（２人が若干引いている……！）"

[[dialogue]]
speaker = "ルルカ"
# 「ルカルカちゃんのことなら何でも聞いてよー！　わっはっはっは～！」
line = "「ルカルカちゃんのことなら何でも聞いてよー！　わっはっはっは～！」"

[[dialogue]]
speaker = "unk"
# その後、ルルカと２人きりになって──
line = "その後、ルルカと２人きりになって──"

[[dialogue]]
speaker = "ルルカ"
# 「う、ぅぅうぅうー……」
line = "「う、ぅぅうぅうー……」"

[[dialogue]]
speaker = "ルルカ"
# 「だ、ダメージが大きいよ、お兄ちゃん……自分で自分を褒めちぎるとか……ほんと何様って感じだよぉ……」
line = "「だ、ダメージが大きいよ、お兄ちゃん……自分で自分を褒めちぎるとか……ほんと何様って感じだよぉ……」"

[[dialogue]]
speaker = "ルルカ"
# 「今日はお兄ちゃんのお家、行ってもいい……？　一人だと羞恥心でおかしくなっちゃいそう……慰めてぇ……」
line = "「今日はお兄ちゃんのお家、行ってもいい……？　一人だと羞恥心でおかしくなっちゃいそう……慰めてぇ……」"

[[dialogue]]
speaker = "unk"
# しおしおになったルルカに、俺は「もちろん」と返すしかないのだった……
line = "しおしおになったルルカに、俺は「もちろん」と返すしかないのだった……"
