[[dialogue]]
speaker = "unk"
# 第４話,親しき仲にも禁欲あり？,P
line = "第４話,親しき仲にも禁欲あり？,P"

[[dialogue]]
speaker = "イクシリオン"
# 「よ、夜のビーチも静かでいいですね……？　お散歩するには打ってつけと言いますか……」
line = "「よ、夜のビーチも静かでいいですね……？　お散歩するには打ってつけと言いますか……」"

[[dialogue]]
speaker = "イクシリオン"
# 「波打ち際を歩くと少し肌寒いくらいです。制服で来て正解だったかもしれません」
line = "「波打ち際を歩くと少し肌寒いくらいです。制服で来て正解だったかもしれません」"

[[dialogue]]
speaker = "イクシリオン"
# 「でも驚きました……。まさか会長がこんな時間に連絡をくれるなんて……。い、一体どうされたんですか……？」
line = "「でも驚きました……。まさか会長がこんな時間に連絡をくれるなんて……。い、一体どうされたんですか……？」"

[[dialogue]]
speaker = "イクシリオン"
# 「いえいえっ、決して迷惑なことは……！　特に何をしていたわけでもありませんので。誘っていただいて嬉しかったですよ？」
line = "「いえいえっ、決して迷惑なことは……！　特に何をしていたわけでもありませんので。誘っていただいて嬉しかったですよ？」"

[[dialogue]]
speaker = "イクシリオン"
# （ですが緊張してしまいます……。夜のビーチで２人きり……。て、手まで繋いでくださって……）
line = "（ですが緊張してしまいます……。夜のビーチで２人きり……。て、手まで繋いでくださって……）"

[[dialogue]]
speaker = "イクシリオン"
# （これは音に聞く、夜デートというやつなのでは……？　キ、キスとかハグとか色々されちゃったりするやつなのではっ……？）
line = "（これは音に聞く、夜デートというやつなのでは……？　キ、キスとかハグとか色々されちゃったりするやつなのではっ……？）"

[[dialogue]]
speaker = "イクシリオン"
# （いえいえ会長に限ってそんなこと……！　私から誘うならともかく、会長はそんな即物的な感情で夜中に呼び出すような人じゃありませんよねっ……）
line = "（いえいえ会長に限ってそんなこと……！　私から誘うならともかく、会長はそんな即物的な感情で夜中に呼び出すような人じゃありませんよねっ……）"

[[dialogue]]
speaker = "イクシリオン"
# （……そう思うと、私ってやっぱりいやらしい女の子です。深夜に呼び出されただけでドキドキして……。キスやハグを期待してしまって……）
line = "（……そう思うと、私ってやっぱりいやらしい女の子です。深夜に呼び出されただけでドキドキして……。キスやハグを期待してしまって……）"

[[dialogue]]
speaker = "イクシリオン"
# （エッチなことしか考えられない自分が恥ずかしい……。連絡が来た時も、会長のことを考えて……）
line = "（エッチなことしか考えられない自分が恥ずかしい……。連絡が来た時も、会長のことを考えて……）"

[[dialogue]]
speaker = "unk"
# イクシー？
line = "イクシー？"

[[dialogue]]
speaker = "イクシリオン"
# 「へっ！？　あっ、えと……！　す、すみません、ボーッとしていて……」
line = "「へっ！？　あっ、えと……！　す、すみません、ボーッとしていて……」"

[[dialogue]]
speaker = "イクシリオン"
# 「水着戦闘服の使い心地、ですよね……？　お陰様で普段の戦闘服と変わらない程度には扱えるようになりましたよ……？」
line = "「水着戦闘服の使い心地、ですよね……？　お陰様で普段の戦闘服と変わらない程度には扱えるようになりましたよ……？」"

[[dialogue]]
speaker = "イクシリオン"
# （失敗しました失敗しました失敗しました……！　せっかく会長が話しかけてくださってるのに、私ったらてんで上の空で……！）
line = "（失敗しました失敗しました失敗しました……！　せっかく会長が話しかけてくださってるのに、私ったらてんで上の空で……！）"

[[dialogue]]
speaker = "イクシリオン"
# （とにかく気持ちを鎮めなければ……。エッチなことばかり考えていると幻滅されてしまうかもしれません……）
line = "（とにかく気持ちを鎮めなければ……。エッチなことばかり考えていると幻滅されてしまうかもしれません……）"

[[dialogue]]
speaker = "イクシリオン"
# （はぁ……でも会長の横顔、格好いい……唇美味しそう……。この適度に蒸し暑い夜が情欲を掻き立ててきて……）
line = "（はぁ……でも会長の横顔、格好いい……唇美味しそう……。この適度に蒸し暑い夜が情欲を掻き立ててきて……）"

[[dialogue]]
speaker = "イクシリオン"
# （って──ダメですダメっ。気を抜いたらすぐにそういうことばかり考えてしまうんですから……！）
line = "（って──ダメですダメっ。気を抜いたらすぐにそういうことばかり考えてしまうんですから……！）"

[[dialogue]]
speaker = "イクシリオン"
# （うぅ、不思議なものです……。恋人になる前はもっと赤裸々にエッチな自分を曝け出していましたのに、恋人になってからは曝け出すのが恥ずかしくなってしまって……）
line = "（うぅ、不思議なものです……。恋人になる前はもっと赤裸々にエッチな自分を曝け出していましたのに、恋人になってからは曝け出すのが恥ずかしくなってしまって……）"

[[dialogue]]
speaker = "イクシリオン"
# （でも我慢しないと……。とにかく今は、会長の声と、繋いだ手のぬくもりと、ふわりと香ってくる匂いと、この夜の雰囲気を脳の海馬に刻みつけて帰って──）
line = "（でも我慢しないと……。とにかく今は、会長の声と、繋いだ手のぬくもりと、ふわりと香ってくる匂いと、この夜の雰囲気を脳の海馬に刻みつけて帰って──）"

[[dialogue]]
speaker = "unk"
# そういえば……最近エッチなおねだりしてこないね？
line = "そういえば……最近エッチなおねだりしてこないね？"

[[dialogue]]
speaker = "イクシリオン"
# 「えっ！？　そ、そうですね。私も会長の彼女になって多少の慎みを覚えましたといいますか」
line = "「えっ！？　そ、そうですね。私も会長の彼女になって多少の慎みを覚えましたといいますか」"

[[dialogue]]
speaker = "イクシリオン"
# 「こうして手を繋いで夜のビーチをお散歩しているだけでも幸せです。そういうことをしなくても、とっても満たされちゃってます」
line = "「こうして手を繋いで夜のビーチをお散歩しているだけでも幸せです。そういうことをしなくても、とっても満たされちゃってます」"

[[dialogue]]
speaker = "unk"
# ……ならこれは俺のワガママだな
line = "……ならこれは俺のワガママだな"

[[dialogue]]
speaker = "イクシリオン"
# 「へ…………？　──ひゃっ！？」
line = "「へ…………？　──ひゃっ！？」"

[[dialogue]]
speaker = "イクシリオン"
# 「かかか、会長っ……！？　急にどうし──あっ、んふっ……！　ん゛んんんんっっ～～……！！？」
line = "「かかか、会長っ……！？　急にどうし──あっ、んふっ……！　ん゛んんんんっっ～～……！！？」"

[[dialogue]]
speaker = "イクシリオン"
# 「ぷ、ぷはぁ……！　はぁはぁ……こ、こんな強引なキス……」
line = "「ぷ、ぷはぁ……！　はぁはぁ……こ、こんな強引なキス……」"

[[dialogue]]
speaker = "イクシリオン"
# 「も、もしかして私とイチャイチャしたくて呼び出してくれたんですか……？　こんな夜更けに、あ、明日も会う約束をしていましたのに……」
line = "「も、もしかして私とイチャイチャしたくて呼び出してくれたんですか……？　こんな夜更けに、あ、明日も会う約束をしていましたのに……」"

[[dialogue]]
speaker = "イクシリオン"
# 「私とキスしたり、抱き締めたりしたくて……？　か、会長が……？」
line = "「私とキスしたり、抱き締めたりしたくて……？　か、会長が……？」"

[[dialogue]]
speaker = "unk"
# 幻滅されちゃったかな……
line = "幻滅されちゃったかな……"

[[dialogue]]
speaker = "イクシリオン"
# 「い、いえっ、いえいえいえっ！　すごくっ、すごく嬉しいですっ……！」
line = "「い、いえっ、いえいえいえっ！　すごくっ、すごく嬉しいですっ……！」"

[[dialogue]]
speaker = "イクシリオン"
# 「本当はその、私も、えと、会長とイチャイチャしたくて……。濃厚なキスとか、密着してハグとか、いっぱいして欲しくて……」
line = "「本当はその、私も、えと、会長とイチャイチャしたくて……。濃厚なキスとか、密着してハグとか、いっぱいして欲しくて……」"

[[dialogue]]
speaker = "イクシリオン"
# 「ふぁ──……んっ<emoji=heart04>　んちゅぁ、れ……れるぅん<emoji=heart04>　んふぅん、んっ……ちゅっ……んんっっ……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「ふぁ──……んっ<emoji=heart04>　んちゅぁ、れ……れるぅん<emoji=heart04>　んふぅん、んっ……ちゅっ……んんっっ……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「ぷはぁ……はぁはぁ<emoji=heart04>　し、幸せです……<emoji=heart04>　のぼせてしまいます……<emoji=heart04>」
line = "「ぷはぁ……はぁはぁ<emoji=heart04>　し、幸せです……<emoji=heart04>　のぼせてしまいます……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 水着になればいいんじゃない？
line = "水着になればいいんじゃない？"

[[dialogue]]
speaker = "イクシリオン"
# 「っっ<emoji=heart04><emoji=heart04><emoji=heart04>　さっきのお話もそういうことだったんですね……？　私の水着姿が見たくて、唐突に水着戦闘服の使い心地を尋ねてきて……<emoji=heart04>」
line = "「っっ<emoji=heart04><emoji=heart04><emoji=heart04>　さっきのお話もそういうことだったんですね……？　私の水着姿が見たくて、唐突に水着戦闘服の使い心地を尋ねてきて……<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「そんな遠回しなことしなくても──んっ<emoji=heart04>」
line = "「そんな遠回しなことしなくても──んっ<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「ひと言命令してくだされば従いますのに……<emoji=heart04>」
line = "「ひと言命令してくだされば従いますのに……<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「えへへ、会長も私に負けないくらいエッチだったんですね。水着になった途端、体温がぐんぐん上がってます」
line = "「えへへ、会長も私に負けないくらいエッチだったんですね。水着になった途端、体温がぐんぐん上がってます」"

[[dialogue]]
speaker = "イクシリオン"
# 「でも嬉しい……。んっ、ちゅ……<emoji=heart04>　会長が私をエッチな目で見てくださるの、何よりも嬉しいです……<emoji=heart04>」
line = "「でも嬉しい……。んっ、ちゅ……<emoji=heart04>　会長が私をエッチな目で見てくださるの、何よりも嬉しいです……<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「遠慮なんてしないでください。したいことがあれば、どんなことでもしてくださって構いませんから……」
line = "「遠慮なんてしないでください。したいことがあれば、どんなことでもしてくださって構いませんから……」"

[[dialogue]]
speaker = "イクシリオン"
# 「彼氏彼女なんですし……気遣いは無用ですよ？」
line = "「彼氏彼女なんですし……気遣いは無用ですよ？」"

[[dialogue]]
speaker = "イクシリオン"
# 「って、あはは……。かくいう私も幻滅されるのが怖くて控えちゃってたんですけど……」
line = "「って、あはは……。かくいう私も幻滅されるのが怖くて控えちゃってたんですけど……」"

[[dialogue]]
speaker = "イクシリオン"
# 「でも、今はっきりとわかりました。何も我慢する必要なんてなかったんですね……？」
line = "「でも、今はっきりとわかりました。何も我慢する必要なんてなかったんですね……？」"

[[dialogue]]
speaker = "イクシリオン"
# 「だって、こんなにも幸せなのですから。大好きな恋人に……求められることが」
line = "「だって、こんなにも幸せなのですから。大好きな恋人に……求められることが」"

[[dialogue]]
speaker = "イクシリオン"
# 「好き……好きですよ、大好きです<emoji=heart04>　もう私、何も遠慮しません。今まで以上に、えへへ、エッチな自分を曝け出していっちゃいます<emoji=heart04>」
line = "「好き……好きですよ、大好きです<emoji=heart04>　もう私、何も遠慮しません。今まで以上に、えへへ、エッチな自分を曝け出していっちゃいます<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「ですから会長もどんどん曝け出しちゃってください。ご存じの通り、私、とってもエッチでいやらしい女の子ですから……」
line = "「ですから会長もどんどん曝け出しちゃってください。ご存じの通り、私、とってもエッチでいやらしい女の子ですから……」"

[[dialogue]]
speaker = "イクシリオン"
# 「他の女の子じゃ引いちゃうようなプレイも……えへへ。喜んで引き受けちゃいますよ<emoji=heart04>」
line = "「他の女の子じゃ引いちゃうようなプレイも……えへへ。喜んで引き受けちゃいますよ<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「では、参りましょうか……<emoji=heart04>　実は、その、ビーチのパトロールをしている時に、人目に付かない一角を見つけたんです……<emoji=heart04>」
line = "「では、参りましょうか……<emoji=heart04>　実は、その、ビーチのパトロールをしている時に、人目に付かない一角を見つけたんです……<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「そこでならゆっくりイチャイチャできますから……<emoji=heart04>　溜まっていたもの、お互いにぶちまけちゃいましょう……？」
line = "「そこでならゆっくりイチャイチャできますから……<emoji=heart04>　溜まっていたもの、お互いにぶちまけちゃいましょう……？」"

[[dialogue]]
speaker = "イクシリオン"
# 「時間は、ん……ちゅっ……<emoji=heart04>　たっぷりありますし、ね？」
line = "「時間は、ん……ちゅっ……<emoji=heart04>　たっぷりありますし、ね？」"
