[[dialogue]]
speaker = "unk"
# 第３話,英雄ウィステリア？,P
line = "第３話,英雄ウィステリア？,P"

[[dialogue]]
speaker = "フィオナ"
# 「グロリアスサマー！」
line = "「グロリアスサマー！」"

[[dialogue]]
speaker = "ウィステリア"
# 「ウンディーネラメント」
line = "「ウンディーネラメント」"

[[dialogue]]
speaker = "unk"
# フィオナとウィステリアさん、２人が星術を放つと、激流がぶつかって水飛沫が弾けた。
line = "フィオナとウィステリアさん、２人が星術を放つと、激流がぶつかって水飛沫が弾けた。"

[[dialogue]]
speaker = "フィオナ"
# 「お久しぶりです、ウィステリアさん」
line = "「お久しぶりです、ウィステリアさん」"

[[dialogue]]
speaker = "ウィステリア"
# 「ええ、久しぶりね、フィオナさん。それとも、フィオナお嬢様と呼ぶべきかしら？」
line = "「ええ、久しぶりね、フィオナさん。それとも、フィオナお嬢様と呼ぶべきかしら？」"

[[dialogue]]
speaker = "フィオナ"
# 「やめてください。今のウィステリアさんはメイドじゃないんですから」
line = "「やめてください。今のウィステリアさんはメイドじゃないんですから」"

[[dialogue]]
speaker = "unk"
# なるほど、２人は知り合いなんだ
line = "なるほど、２人は知り合いなんだ"

[[dialogue]]
speaker = "ウィステリア"
# 「ええ、昔、星見家メイド隊でバイトしてたから。といっても割とすぐ辞めちゃったから、フィオナさんは覚えてないかと思ってたけど」
line = "「ええ、昔、星見家メイド隊でバイトしてたから。といっても割とすぐ辞めちゃったから、フィオナさんは覚えてないかと思ってたけど」"

[[dialogue]]
speaker = "フィオナ"
# 「いいえ、よく覚えていますよ。キリカととても仲が良かったですから」
line = "「いいえ、よく覚えていますよ。キリカととても仲が良かったですから」"

[[dialogue]]
speaker = "ウィステリア"
# 「う……フィオナさんまで……。全然仲良くないって言ってるのに、どうしてみんなそう言うのかしら……」
line = "「う……フィオナさんまで……。全然仲良くないって言ってるのに、どうしてみんなそう言うのかしら……」"

[[dialogue]]
speaker = "ウィステリア"
# 「でも、２人して私に手合わせしてほしいってどういう風の吹き回し？　キリカばっかり師匠呼びされるのは気に食わないから、相手するのはいいんだけど」
line = "「でも、２人して私に手合わせしてほしいってどういう風の吹き回し？　キリカばっかり師匠呼びされるのは気に食わないから、相手するのはいいんだけど」"

[[dialogue]]
speaker = "フィオナ"
# 「ウィステリアさんは在学中、“千年に一度の英雄”と呼ばれていたと、セーラさんに聞きましたから」
line = "「ウィステリアさんは在学中、“千年に一度の英雄”と呼ばれていたと、セーラさんに聞きましたから」"

[[dialogue]]
speaker = "ウィステリア"
# 「あー、そこから聞いたんだ……彼女、２つ下だから在学期間がギリギリ被ってるのよね……」
line = "「あー、そこから聞いたんだ……彼女、２つ下だから在学期間がギリギリ被ってるのよね……」"

[[dialogue]]
speaker = "ウィステリア"
# 「でも私、星騎士としては邪道よ？　私の戦闘力は、この魔導書の魔力があってのものだし」
line = "「でも私、星騎士としては邪道よ？　私の戦闘力は、この魔導書の魔力があってのものだし」"

[[dialogue]]
speaker = "フィオナ"
# 「と言いつつ、星力だけでもかなりの力をお持ちのようですけど。胸を借りるつもりでいきます」
line = "「と言いつつ、星力だけでもかなりの力をお持ちのようですけど。胸を借りるつもりでいきます」"

[[dialogue]]
speaker = "フィオナ"
# 「でもどうして海で、しかも水着で戦う必要があるんでしょう？　ビーチの持ち主であるヘレナさんの許可は取りましたが……」
line = "「でもどうして海で、しかも水着で戦う必要があるんでしょう？　ビーチの持ち主であるヘレナさんの許可は取りましたが……」"

[[dialogue]]
speaker = "ウィステリア"
# 「せっかくみんな水着があるんだし、着ないと損でしょ。お互い水着戦闘服を使いこなす練習も兼ねてってことで」
line = "「せっかくみんな水着があるんだし、着ないと損でしょ。お互い水着戦闘服を使いこなす練習も兼ねてってことで」"

[[dialogue]]
speaker = "unk"
# 魔導書は大丈夫ですか？
line = "魔導書は大丈夫ですか？"

[[dialogue]]
speaker = "ウィステリア"
# 「海水ぐらい平気よ。なんてったって、呪いの書なんだもの。多分マグマに投げ入れても焦げ跡ひとつ付かないわ」
line = "「海水ぐらい平気よ。なんてったって、呪いの書なんだもの。多分マグマに投げ入れても焦げ跡ひとつ付かないわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「それじゃ……ビーチが消し飛ばない程度に頑張りましょうっ」
line = "「それじゃ……ビーチが消し飛ばない程度に頑張りましょうっ」"

[[dialogue]]
speaker = "ウィステリア"
# 「ふぅ……こんなものかしら」
line = "「ふぅ……こんなものかしら」"

[[dialogue]]
speaker = "フィオナ"
# 「はぁ、はぁ……さすがウィステリアさん、本当にお強かったです……」
line = "「はぁ、はぁ……さすがウィステリアさん、本当にお強かったです……」"

[[dialogue]]
speaker = "unk"
# もう限界です……
line = "もう限界です……"

[[dialogue]]
speaker = "ウィステリア"
# 「ふふ、さすが星徒会長の２人だわ。私は魔導書あり、会長くんとフィオナさんは星力だけのハンデ戦だったけどね」
line = "「ふふ、さすが星徒会長の２人だわ。私は魔導書あり、会長くんとフィオナさんは星力だけのハンデ戦だったけどね」"

[[dialogue]]
speaker = "フィオナ"
# 「その条件でも、星徒会長２人を相手にできるのは異常な強さだと思います……」
line = "「その条件でも、星徒会長２人を相手にできるのは異常な強さだと思います……」"

[[dialogue]]
speaker = "ウィステリア"
# 「でも、魔王の力を使われたら私に勝ち目ないでしょ？」
line = "「でも、魔王の力を使われたら私に勝ち目ないでしょ？」"

[[dialogue]]
speaker = "ウィステリア"
# 「聞くところによると、会長くんとフィオナさんが持つ魔王の力は、星力・魔力・霊力を融合させ、さらに高次元のエネルギーを操ることができるとか」
line = "「聞くところによると、会長くんとフィオナさんが持つ魔王の力は、星力・魔力・霊力を融合させ、さらに高次元のエネルギーを操ることができるとか」"

[[dialogue]]
speaker = "ウィステリア"
# 「それに対し、私は星力と魔力をそれぞれ使えるだけ。魔王が核融合だとすれば、私はハイブリッドカーってところかしらね」
line = "「それに対し、私は星力と魔力をそれぞれ使えるだけ。魔王が核融合だとすれば、私はハイブリッドカーってところかしらね」"

[[dialogue]]
speaker = "ウィステリア"
# 「ちなみに私の『フォビドゥンリアクター』は星力と魔力をぶつけることで爆発を起こしてるの。魔王でない者にはこれが限界ね」
line = "「ちなみに私の『フォビドゥンリアクター』は星力と魔力をぶつけることで爆発を起こしてるの。魔王でない者にはこれが限界ね」"

[[dialogue]]
speaker = "フィオナ"
# 「逆に言えば、魔王の血筋でないのにそこに近づいている……それがウィステリアさんの強さの秘密だったんですね」
line = "「逆に言えば、魔王の血筋でないのにそこに近づいている……それがウィステリアさんの強さの秘密だったんですね」"

[[dialogue]]
speaker = "ウィステリア"
# 「まぁそういうことになるわね。魔王の力を知ったのは最近のことだし、真似したわけじゃないけど」
line = "「まぁそういうことになるわね。魔王の力を知ったのは最近のことだし、真似したわけじゃないけど」"

[[dialogue]]
speaker = "unk"
# さすが“千年に一度の英雄”です
line = "さすが“千年に一度の英雄”です"

[[dialogue]]
speaker = "ウィステリア"
# 「うぅ、それはやめてってば……」
line = "「うぅ、それはやめてってば……」"

[[dialogue]]
speaker = "フィオナ"
# 「確かに、どうして“千年に一度の英雄”なんて言われたんでしょう？　ウィステリアさんはお強いですが、いささか表現が大仰な気が……」
line = "「確かに、どうして“千年に一度の英雄”なんて言われたんでしょう？　ウィステリアさんはお強いですが、いささか表現が大仰な気が……」"

[[dialogue]]
speaker = "ウィステリア"
# 「うーん、それは私もイマイチわかってないのよね。そう言われたのはアレと戦った後なんだけど……」
line = "「うーん、それは私もイマイチわかってないのよね。そう言われたのはアレと戦った後なんだけど……」"

[[dialogue]]
speaker = "フィオナ"
# 「アレ？」
line = "「アレ？」"

[[dialogue]]
speaker = "ウィステリア"
# 「大きなトカゲ──あ、ドラゴンのことトカゲって言ったらマハムートさんに失礼ね。ドラゴンよ、ドラゴン」
line = "「大きなトカゲ──あ、ドラゴンのことトカゲって言ったらマハムートさんに失礼ね。ドラゴンよ、ドラゴン」"

[[dialogue]]
speaker = "ウィステリア"
# 「なんかこう……次元のねじれ的なのに迷い込んだ先に、とっても強いドラゴンがいたのよ」
line = "「なんかこう……次元のねじれ的なのに迷い込んだ先に、とっても強いドラゴンがいたのよ」"

[[dialogue]]
speaker = "ウィステリア"
# 「もし世に放たれたら世界が大変なことになる。一目でそう確信したわ」
line = "「もし世に放たれたら世界が大変なことになる。一目でそう確信したわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「だけど倒そうとしたら強いのなんのって。何度も死にかけたわ」
line = "「だけど倒そうとしたら強いのなんのって。何度も死にかけたわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「いいところまではいったけど、結局仕留め切れなくて、呪いまくって鎖で<ruby=がんじがら>雁字搦</ruby>めにしてやったのよ」
line = "「いいところまではいったけど、結局仕留め切れなくて、呪いまくって鎖で<ruby>雁字搦<rt>がんじがら</rt></ruby>めにしてやったのよ」"

[[dialogue]]
speaker = "ウィステリア"
# 「それを学園に報告したら、当時いた誰かが“千年に一度の英雄”だって言い出してね」
line = "「それを学園に報告したら、当時いた誰かが“千年に一度の英雄”だって言い出してね」"

[[dialogue]]
speaker = "ウィステリア"
# 「あのドラゴン、今どうなってるのかしらね？　今まで見てないってことは、まだあそこにいると思うんだけど」
line = "「あのドラゴン、今どうなってるのかしらね？　今まで見てないってことは、まだあそこにいると思うんだけど」"

[[dialogue]]
speaker = "フィオナ"
# 「ドラゴン……鎖……もしかして」
line = "「ドラゴン……鎖……もしかして」"

[[dialogue]]
speaker = "unk"
# そのドラゴン、こんなのじゃありませんでした……？
line = "そのドラゴン、こんなのじゃありませんでした……？"

[[dialogue]]
speaker = "unk"
# ＤＩＳＣで記録したデータを見せると──
line = "ＤＩＳＣで記録したデータを見せると──"

[[dialogue]]
speaker = "ウィステリア"
# 「そう、これこれ！　私が戦ったのは鎖がない時だけど……確かにこのドラゴンだったわ。これどうしたの？」
line = "「そう、これこれ！　私が戦ったのは鎖がない時だけど……確かにこのドラゴンだったわ。これどうしたの？」"

[[dialogue]]
speaker = "フィオナ"
# 「私たちがフィーニスの塔で遭遇した煌竜ヴィライアです。両星徒会のメンバーが総力をかけて倒したのですが……」
line = "「私たちがフィーニスの塔で遭遇した煌竜ヴィライアです。両星徒会のメンバーが総力をかけて倒したのですが……」"

[[dialogue]]
speaker = "ウィステリア"
# 「あれを倒したの！？　さすが会長くんたち、魔王の名に偽りなしね！」
line = "「あれを倒したの！？　さすが会長くんたち、魔王の名に偽りなしね！」"

[[dialogue]]
speaker = "フィオナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ウィステリア"
# 「フィオナさん？　どうしたの？」
line = "「フィオナさん？　どうしたの？」"

[[dialogue]]
speaker = "フィオナ"
# 「いえ……確かに“千年に一度の英雄”と呼ばれるにふさわしいお力ですね……」
line = "「いえ……確かに“千年に一度の英雄”と呼ばれるにふさわしいお力ですね……」"

[[dialogue]]
speaker = "unk"
# さすが英雄ですね……
line = "さすが英雄ですね……"

[[dialogue]]
speaker = "ウィステリア"
# 「ええ～っ、なんで会長くんたちもそれ言うのよ～っ！？」
line = "「ええ～っ、なんで会長くんたちもそれ言うのよ～っ！？」"

[[dialogue]]
speaker = "unk"
# 煌竜ヴィライアは、森羅暦以前の世界で魔界を滅ぼした、災厄の化身とも言うべき魔物。
line = "煌竜ヴィライアは、森羅暦以前の世界で魔界を滅ぼした、災厄の化身とも言うべき魔物。"

[[dialogue]]
speaker = "unk"
# 詳しい経緯は不明だが、ヴィライアと渡り合ったウィステリアさんは、間違いなく“英雄”と呼ばれるに足る存在だった。
line = "詳しい経緯は不明だが、ヴィライアと渡り合ったウィステリアさんは、間違いなく“英雄”と呼ばれるに足る存在だった。"
