[[dialogue]]
speaker = "unk"
# 第１話,番長襲来！？,P
line = "第１話,番長襲来！？,P"

[[dialogue]]
speaker = "マトイ"
# 「ふぅ……今日は仕事も少ないし、モンスターも発生してないし、平和だね」
line = "「ふぅ……今日は仕事も少ないし、モンスターも発生してないし、平和だね」"

[[dialogue]]
speaker = "unk"
# 確かに
line = "確かに"

[[dialogue]]
speaker = "マトイ"
# 「こんな日が続けばいいんだけど……」
line = "「こんな日が続けばいいんだけど……」"

[[dialogue]]
speaker = "モネ"
# 「た、大変ですっ！　隣の学園の番長が殴り込みに来ました～っ！」
line = "「た、大変ですっ！　隣の学園の番長が殴り込みに来ました～っ！」"

[[dialogue]]
speaker = "マトイ"
# 「番長！？」
line = "「番長！？」"

[[dialogue]]
speaker = "ユウリ"
# 「よぅ、新星の会長さん。あたしは流星の――」
line = "「よぅ、新星の会長さん。あたしは流星の――」"

[[dialogue]]
speaker = "unk"
# 番長さんですか？
line = "番長さんですか？"

[[dialogue]]
speaker = "ユウリ"
# 「誰が番長だ！　星徒会役員だっての！」
line = "「誰が番長だ！　星徒会役員だっての！」"

[[dialogue]]
speaker = "マトイ"
# 「だよね……良かった、番長じゃなくて……」
line = "「だよね……良かった、番長じゃなくて……」"

[[dialogue]]
speaker = "ユウリ"
# 「知ってると思うが一応。あたしは流星星徒会の楠葉ユウリ。役職は庶務だ」
line = "「知ってると思うが一応。あたしは流星星徒会の楠葉ユウリ。役職は庶務だ」"

[[dialogue]]
speaker = "ユウリ"
# 「ったく、なんであたしが番長ってことになってるんだよ。どこからどう見ても品行方正な星徒会役員だろ」
line = "「ったく、なんであたしが番長ってことになってるんだよ。どこからどう見ても品行方正な星徒会役員だろ」"

[[dialogue]]
speaker = "マトイ"
# （それはどうかな……？）
line = "（それはどうかな……？）"

[[dialogue]]
speaker = "モネ"
# 「なんというか、こう……やんちゃというか、不良っぽい感じのオーラが……」
line = "「なんというか、こう……やんちゃというか、不良っぽい感じのオーラが……」"

[[dialogue]]
speaker = "ユウリ"
# 「なんだと？」
line = "「なんだと？」"

[[dialogue]]
speaker = "モネ"
# 「ひいっ、ごめんなさい～っ！」
line = "「ひいっ、ごめんなさい～っ！」"

[[dialogue]]
speaker = "マトイ"
# （紙屋敷さん、正直すぎる……あと普通に失礼）
line = "（紙屋敷さん、正直すぎる……あと普通に失礼）"

[[dialogue]]
speaker = "unk"
# 何か用事？
line = "何か用事？"

[[dialogue]]
speaker = "ユウリ"
# 「ああ、そうそう。ほい、企画書。うちの星徒会で作ったからそっちでも読んでおいてくれ」
line = "「ああ、そうそう。ほい、企画書。うちの星徒会で作ったからそっちでも読んでおいてくれ」"

[[dialogue]]
speaker = "モネ"
# 「企画書？」
line = "「企画書？」"

[[dialogue]]
speaker = "ユウリ"
# 「ほら、ヤバそうな事件がいろいろ起きてるだろ。今までは星徒会だけでも十分だったが、これから何が起こるかわからない」
line = "「ほら、ヤバそうな事件がいろいろ起きてるだろ。今までは星徒会だけでも十分だったが、これから何が起こるかわからない」"

[[dialogue]]
speaker = "ユウリ"
# 「だから戦力の底上げだ。星騎士全員が戦えるように、両星徒会が相手の学園に行って稽古をつけるのはどうかってな」
line = "「だから戦力の底上げだ。星騎士全員が戦えるように、両星徒会が相手の学園に行って稽古をつけるのはどうかってな」"

[[dialogue]]
speaker = "ユウリ"
# 「普段は向こうの星徒会役員なんて接点がないし、刺激になるんじゃないか……って<ruby=うち>流星</ruby>の副会長が言ってた」
line = "「普段は向こうの星徒会役員なんて接点がないし、刺激になるんじゃないか……って<ruby>流星<rt>うち</rt></ruby>の副会長が言ってた」"

[[dialogue]]
speaker = "モネ"
# 「へぇ、そんなことが……戦うの得意じゃないのになぁ……」
line = "「へぇ、そんなことが……戦うの得意じゃないのになぁ……」"

[[dialogue]]
speaker = "ユウリ"
# 「そういう生徒がいるからこそだ。今度のリクリエは星騎士全員の力が必要になるかもしれない」
line = "「そういう生徒がいるからこそだ。今度のリクリエは星騎士全員の力が必要になるかもしれない」"

[[dialogue]]
speaker = "ユウリ"
# 「今までは戦闘が苦手でも何とかなってたが、これからは自分の身を守るためにも強くなってもらわないとな」
line = "「今までは戦闘が苦手でも何とかなってたが、これからは自分の身を守るためにも強くなってもらわないとな」"

[[dialogue]]
speaker = "モネ"
# 「そ、それはそうなんですけど……うぅ、ちょっと憂鬱……」
line = "「そ、それはそうなんですけど……うぅ、ちょっと憂鬱……」"

[[dialogue]]
speaker = "マトイ"
# 「ところで、どうして手にサンドイッチを？」
line = "「ところで、どうして手にサンドイッチを？」"

[[dialogue]]
speaker = "ユウリ"
# 「ああ、星徒会室に来る途中で料理研究会に出くわしてよ。ちょっと審査員してくれって言われて付き合ったら、お礼にもらった」
line = "「ああ、星徒会室に来る途中で料理研究会に出くわしてよ。ちょっと審査員してくれって言われて付き合ったら、お礼にもらった」"

[[dialogue]]
speaker = "ユウリ"
# 「はむはむ……ごちそうさま。けっこううまかったぜ」
line = "「はむはむ……ごちそうさま。けっこううまかったぜ」"

[[dialogue]]
speaker = "ユウリ"
# 「で、あたしを番長呼ばわりしたお前は何してたとこなんだ？　てか何持ってんだ？」
line = "「で、あたしを番長呼ばわりしたお前は何してたとこなんだ？　てか何持ってんだ？」"

[[dialogue]]
speaker = "モネ"
# 「あ、これ、本を修理する道具なんです。図書館に持っていくところだったんでした……」
line = "「あ、これ、本を修理する道具なんです。図書館に持っていくところだったんでした……」"

[[dialogue]]
speaker = "ユウリ"
# 「ああ、お前図書委員だったのか。それ貸せよ」
line = "「ああ、お前図書委員だったのか。それ貸せよ」"

[[dialogue]]
speaker = "モネ"
# 「カツアゲ！？」
line = "「カツアゲ！？」"

[[dialogue]]
speaker = "ユウリ"
# 「ちげーよ。けっこう重そうだから持ってやる。新星の図書館まででいいんだよな？」
line = "「ちげーよ。けっこう重そうだから持ってやる。新星の図書館まででいいんだよな？」"

[[dialogue]]
speaker = "モネ"
# 「いいんですか？　わたし失礼なこと言ったのに……」
line = "「いいんですか？　わたし失礼なこと言ったのに……」"

[[dialogue]]
speaker = "ユウリ"
# 「別にそのくらい気にしやしねーよ。どっかのアホ猫の方が十倍失礼なこと言ってきやがるし」
line = "「別にそのくらい気にしやしねーよ。どっかのアホ猫の方が十倍失礼なこと言ってきやがるし」"

[[dialogue]]
speaker = "ニャリオン"
# 『誰がアホ猫ニャン！』
line = "『誰がアホ猫ニャン！』"

[[dialogue]]
speaker = "モネ"
# 「じゃあ、半分お願いします……」
line = "「じゃあ、半分お願いします……」"

[[dialogue]]
speaker = "ユウリ"
# 「おう、任せろ。それじゃあな、新星の会長さん」
line = "「おう、任せろ。それじゃあな、新星の会長さん」"

[[dialogue]]
speaker = "unk"
# 優しい人だ
line = "優しい人だ"

[[dialogue]]
speaker = "マトイ"
# 「そうだね。意外とって言うと失礼だけど」
line = "「そうだね。意外とって言うと失礼だけど」"

[[dialogue]]
speaker = "モネ"
# 「ひゃあっ！？」
line = "「ひゃあっ！？」"

[[dialogue]]
speaker = "ユウリ"
# 「おおっと。自分で言うのもなんだがナイスキャッチ」
line = "「おおっと。自分で言うのもなんだがナイスキャッチ」"

[[dialogue]]
speaker = "モネ"
# 「ありがとうございます……」
line = "「ありがとうございます……」"

[[dialogue]]
speaker = "ユウリ"
# 「道具持ったままこけるなっての。危なっかしいから全部貸せ」
line = "「道具持ったままこけるなっての。危なっかしいから全部貸せ」"

[[dialogue]]
speaker = "モネ"
# 「すみません……」
line = "「すみません……」"

[[dialogue]]
speaker = "マトイ"
# 「ほんとにいい人だな……あはは」
line = "「ほんとにいい人だな……あはは」"
