[[dialogue]]
speaker = "unk"
# 第２話,アイ・キャント・ミス・ユー,P
line = "第２話,アイ・キャント・ミス・ユー,P"

[[dialogue]]
speaker = "ユーリス"
# 「ではショーダウンです。皆さん、役の公開を」
line = "「ではショーダウンです。皆さん、役の公開を」"

[[dialogue]]
speaker = "マトイ"
# 「ふっふー！　私はフルハウス！」
line = "「ふっふー！　私はフルハウス！」"

[[dialogue]]
speaker = "サーシャ"
# 「あら強ーい。降りて正解だったわ～」
line = "「あら強ーい。降りて正解だったわ～」"

[[dialogue]]
speaker = "マトイ"
# 「会長はフラッシュ？　えへへ、惜しかったね～。勝ったと思った？　思っちゃった～？　コノコノ～♪」
line = "「会長はフラッシュ？　えへへ、惜しかったね～。勝ったと思った？　思っちゃった～？　コノコノ～♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「勝ち誇るにはまだ早いわよマトイ。私の手は──これよ！」
line = "「勝ち誇るにはまだ早いわよマトイ。私の手は──これよ！」"

[[dialogue]]
speaker = "マトイ"
# 「フォ、フォーカード……！？　ガクっ……！」
line = "「フォ、フォーカード……！？　ガクっ……！」"

[[dialogue]]
speaker = "アナ"
# 「やはりマトイ先輩は引き立て役が似合いますね」
line = "「やはりマトイ先輩は引き立て役が似合いますね」"

[[dialogue]]
speaker = "マトイ"
# 「そんなー！？」
line = "「そんなー！？」"

[[dialogue]]
speaker = "ユーリス"
# 「ふふ、相変わらず星徒会の方々は賑やかですね」
line = "「ふふ、相変わらず星徒会の方々は賑やかですね」"

[[dialogue]]
speaker = "マトイ"
# 「ごめんね、ユーリスくん。いきなり呼びつけちゃって。カジノで出た新種のモンスターの話をしてたら、いつの間にかポーカー大会が始まっちゃってさー」
line = "「ごめんね、ユーリスくん。いきなり呼びつけちゃって。カジノで出た新種のモンスターの話をしてたら、いつの間にかポーカー大会が始まっちゃってさー」"

[[dialogue]]
speaker = "ユーリス"
# 「構いませんよ。実はまたカジノディーラーのバイトを頼まれていて。肩慣らしをしたいと思っていたところだったんです」
line = "「構いませんよ。実はまたカジノディーラーのバイトを頼まれていて。肩慣らしをしたいと思っていたところだったんです」"

[[dialogue]]
speaker = "サーシャ"
# 「本当に華麗なカード捌きね～。思わず見とれちゃったわ～」
line = "「本当に華麗なカード捌きね～。思わず見とれちゃったわ～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロトとは大違いね。ユーリスが来るまでディーラーをしてもらってたけれど、カードが明後日の方向に飛んで行っちゃってゲームどころじゃなかったもの」
line = "「クロトとは大違いね。ユーリスが来るまでディーラーをしてもらってたけれど、カードが明後日の方向に飛んで行っちゃってゲームどころじゃなかったもの」"

[[dialogue]]
speaker = "サーシャ"
# 「でも可愛いじゃない。ユーリスくんがまたカジノのバイトに入るって聞いて手伝いに行こうとしてるんでしょ？　そのために最近はずっとカードを弄って特訓もして」
line = "「でも可愛いじゃない。ユーリスくんがまたカジノのバイトに入るって聞いて手伝いに行こうとしてるんでしょ？　そのために最近はずっとカードを弄って特訓もして」"

[[dialogue]]
speaker = "ユーリス"
# 「えっ？　そ、そうなのかい、会長？」
line = "「えっ？　そ、そうなのかい、会長？」"

[[dialogue]]
speaker = "unk"
# サーシャさん、その話は……！
line = "サーシャさん、その話は……！"

[[dialogue]]
speaker = "サーシャ"
# 「あらごめんなさい、内緒だったかしら？」
line = "「あらごめんなさい、内緒だったかしら？」"

[[dialogue]]
speaker = "ユーリス"
# 「私のために影でそんなことを……。それならそうと一声かけてくれたら良かったのに……」
line = "「私のために影でそんなことを……。それならそうと一声かけてくれたら良かったのに……」"

[[dialogue]]
speaker = "ユーリス"
# 「特訓なら私も手伝うから……。手取り足取り教えてあげるよ……？　ううん、教えさせて？」
line = "「特訓なら私も手伝うから……。手取り足取り教えてあげるよ……？　ううん、教えさせて？」"

[[dialogue]]
speaker = "unk"
# ユーリス……
line = "ユーリス……"

[[dialogue]]
speaker = "ヴィーナス"
# 「ああ２人して見つめ合っちゃって……。特定の女生徒たちが見たら狂喜乱舞しちゃいそうな絵面ね……」
line = "「ああ２人して見つめ合っちゃって……。特定の女生徒たちが見たら狂喜乱舞しちゃいそうな絵面ね……」"

[[dialogue]]
speaker = "ユーリス"
# 「っっ。べ、別に見つめ合っているわけでは。それでは次のゲームを──……わわっ、カードが！？」
line = "「っっ。べ、別に見つめ合っているわけでは。それでは次のゲームを──……わわっ、カードが！？」"

[[dialogue]]
speaker = "アナ"
# 「今度はユーリス先輩もプレイヤーに入ってください。お疲れのようですし、私がディーラーをやりますよ」
line = "「今度はユーリス先輩もプレイヤーに入ってください。お疲れのようですし、私がディーラーをやりますよ」"

[[dialogue]]
speaker = "ユーリス"
# 「あ、あはは。それじゃお言葉に甘えさせてもらいます。私も一度会長と勝負してみたいと思っていたし……ね？」
line = "「あ、あはは。それじゃお言葉に甘えさせてもらいます。私も一度会長と勝負してみたいと思っていたし……ね？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「くっ……！　フォールドよ……！」
line = "「くっ……！　フォールドよ……！」"

[[dialogue]]
speaker = "マトイ"
# 「ついにヴィーナスも降りちゃったか～。これで事実上ユーリスくんと会長の一騎打ちだね～？　持ち点も並んでるんだっけ？」
line = "「ついにヴィーナスも降りちゃったか～。これで事実上ユーリスくんと会長の一騎打ちだね～？　持ち点も並んでるんだっけ？」"

[[dialogue]]
speaker = "アナ"
# 「ええ。さっきの３回戦で現会長が盛り返しましたから。全５回戦ということを考えると、ここでお互いリードを広げたいところでしょうね」
line = "「ええ。さっきの３回戦で現会長が盛り返しましたから。全５回戦ということを考えると、ここでお互いリードを広げたいところでしょうね」"

[[dialogue]]
speaker = "ユーリス"
# 「ここで上限までベットだ、会長」
line = "「ここで上限までベットだ、会長」"

[[dialogue]]
speaker = "マトイ"
# 「お、ユーリスくん、強気～♪」
line = "「お、ユーリスくん、強気～♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「降りた方がいいんじゃない？　私の見立てだと、彼の手、かなり強いわよ？　この私が降ろされたんだもの」
line = "「降りた方がいいんじゃない？　私の見立てだと、彼の手、かなり強いわよ？　この私が降ろされたんだもの」"

[[dialogue]]
speaker = "unk"
# それはどうかな
line = "それはどうかな"

[[dialogue]]
speaker = "ユーリス"
# 「なんだい会長？　ヴィーナスさんの言うとおり、大人しく降りた方がいい」
line = "「なんだい会長？　ヴィーナスさんの言うとおり、大人しく降りた方がいい」"

[[dialogue]]
speaker = "ユーリス"
# 「言っておくけど……私の手は相当強いよ？」
line = "「言っておくけど……私の手は相当強いよ？」"

[[dialogue]]
speaker = "unk"
# やっぱりな。ここはレイズだ！
line = "やっぱりな。ここはレイズだ！"

[[dialogue]]
speaker = "サーシャ"
# 「あら男の子ね～？　ユーリスくん、こんなに堂々としてるのに」
line = "「あら男の子ね～？　ユーリスくん、こんなに堂々としてるのに」"

[[dialogue]]
speaker = "ヴィーナス"
# 「誰がどう見ても勝負手じゃない。アホじゃないの？」
line = "「誰がどう見ても勝負手じゃない。アホじゃないの？」"

[[dialogue]]
speaker = "マトイ"
# 「私も流石に無茶だと思うなー。フルハウス以上は絶対あるって」
line = "「私も流石に無茶だと思うなー。フルハウス以上は絶対あるって」"

[[dialogue]]
speaker = "アナ"
# 「私もフォールドしますね。負けが見えてます」
line = "「私もフォールドしますね。負けが見えてます」"

[[dialogue]]
speaker = "ユーリス"
# 「……ふふ、会長には敵わないな。本当に私のことを良く見てくれてる。他の人にはわからない私の些細な感情の揺らぎに気付いたんだね……？」
line = "「……ふふ、会長には敵わないな。本当に私のことを良く見てくれてる。他の人にはわからない私の些細な感情の揺らぎに気付いたんだね……？」"

[[dialogue]]
speaker = "unk"
# 誰よりもユーリスを見ているからな
line = "誰よりもユーリスを見ているからな"

[[dialogue]]
speaker = "ユーリス"
# 「っっ。そ、そうみたいだね……。ハッキリ言われちゃうと恥ずかしいけど……」
line = "「っっ。そ、そうみたいだね……。ハッキリ言われちゃうと恥ずかしいけど……」"

[[dialogue]]
speaker = "ユーリス"
# 「でも、ふふ。だからこそ、この勝負は私の勝ちかな？」
line = "「でも、ふふ。だからこそ、この勝負は私の勝ちかな？」"

[[dialogue]]
speaker = "マトイ"
# 「ロ、ロイヤルストレートフラッシュだー！」
line = "「ロ、ロイヤルストレートフラッシュだー！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そら見なさい。だから言ったのよ」
line = "「そら見なさい。だから言ったのよ」"

[[dialogue]]
speaker = "アナ"
# 「何を意外そうな顔をしているんですか現会長。もう少し観察力を養った方がいいんじゃないですか？」
line = "「何を意外そうな顔をしているんですか現会長。もう少し観察力を養った方がいいんじゃないですか？」"

[[dialogue]]
speaker = "サーシャ"
# 「ワンペアかツーペア止まりのつもりだった顔してるわね～？　とてもそんな風には見えなかったと思うけど……」
line = "「ワンペアかツーペア止まりのつもりだった顔してるわね～？　とてもそんな風には見えなかったと思うけど……」"

[[dialogue]]
speaker = "ユーリス"
# 「ふふ、騙しちゃってごめんね？　だけど嬉しかったよ。ほんの一瞬だけ見せた不安げな表情に気付いてくれて」
line = "「ふふ、騙しちゃってごめんね？　だけど嬉しかったよ。ほんの一瞬だけ見せた不安げな表情に気付いてくれて」"

[[dialogue]]
speaker = "ユーリス"
# 「本当に、誰よりも私のことを見てくれてるんだね……？　勝負には勝ったけど、試合には負けちゃった気分だな」
line = "「本当に、誰よりも私のことを見てくれてるんだね……？　勝負には勝ったけど、試合には負けちゃった気分だな」"

[[dialogue]]
speaker = "ユーリス"
# 「さぁもう一勝負しよう、会長。私も会長に同じことをしてあげるから。どんな些細な変化も絶対に見逃さないよ♪」
line = "「さぁもう一勝負しよう、会長。私も会長に同じことをしてあげるから。どんな些細な変化も絶対に見逃さないよ♪」"
