[[dialogue]]
speaker = "unk"
# 第１話,トワちゃんの年齢の秘密,P
line = "第１話,トワちゃんの年齢の秘密,P"

[[dialogue]]
speaker = "unk"
# ある日のこと。俺はヴィーナスと、プリマステラから提出された戦闘報告書に目を通していた。
line = "ある日のこと。俺はヴィーナスと、プリマステラから提出された戦闘報告書に目を通していた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「──それでね、アナが言うには最近のモンスター発生場所には、何か法則性がありそうって話らしいのよ」
line = "「──それでね、アナが言うには最近のモンスター発生場所には、何か法則性がありそうって話らしいのよ」"

[[dialogue]]
speaker = "トワ先生"
# 「会長くん、この前頼まれてた会計資料のチェックが終わったから、持って来たよ」
line = "「会長くん、この前頼まれてた会計資料のチェックが終わったから、持って来たよ」"

[[dialogue]]
speaker = "トワ先生"
# 「あと、廊下でフィオナちゃんと会ったから、一緒に連れて来たんだ～」
line = "「あと、廊下でフィオナちゃんと会ったから、一緒に連れて来たんだ～」"

[[dialogue]]
speaker = "フィオナ"
# 「こんにちは、緋宮会長、ヴィーナスさん。先日のアステラ掃討の報告書を作成したので、見て頂きたくお持ちしました」
line = "「こんにちは、緋宮会長、ヴィーナスさん。先日のアステラ掃討の報告書を作成したので、見て頂きたくお持ちしました」"

[[dialogue]]
speaker = "ヴィーナス"
# 「こんにちは、フィオナ。珍しい組み合わせじゃない」
line = "「こんにちは、フィオナ。珍しい組み合わせじゃない」"

[[dialogue]]
speaker = "ヴィーナス"
# 「トワちゃんがフィオナを下の名前で呼んでるってことは、ふたりは知り合いだったの？」
line = "「トワちゃんがフィオナを下の名前で呼んでるってことは、ふたりは知り合いだったの？」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ、先生は流星学園星徒会のＯＧなんです。以前、星徒会の仕事で困った時に手伝って頂いたことがありまして」
line = "「ええ、先生は流星学園星徒会のＯＧなんです。以前、星徒会の仕事で困った時に手伝って頂いたことがありまして」"

[[dialogue]]
speaker = "unk"
# 先生、星徒会の元メンバーだったんだ……！
line = "先生、星徒会の元メンバーだったんだ……！"

[[dialogue]]
speaker = "トワ先生"
# 「えっへん！　そうなのです。流星学園で３年間、会計の役職に就いてたんだよ。こう見えて先生、優秀だったんだから！」
line = "「えっへん！　そうなのです。流星学園で３年間、会計の役職に就いてたんだよ。こう見えて先生、優秀だったんだから！」"

[[dialogue]]
speaker = "トワ先生"
# 「ところで、会長くんとヴィーナスちゃん、さっきモンスターの発生場所がどうとかって話してなかった？」
line = "「ところで、会長くんとヴィーナスちゃん、さっきモンスターの発生場所がどうとかって話してなかった？」"

[[dialogue]]
speaker = "フィオナ"
# 「私も気になっていたので、是非聞かせていただけませんか？」
line = "「私も気になっていたので、是非聞かせていただけませんか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうね。といっても、そこまで深刻な話じゃないんだけど。実は──」
line = "「そうね。といっても、そこまで深刻な話じゃないんだけど。実は──」"

[[dialogue]]
speaker = "unk"
# 最初はモンスターについて話していたのだが、途中から話が逸れて女子３人のガールズトークみたいな流れになっていた。
line = "最初はモンスターについて話していたのだが、途中から話が逸れて女子３人のガールズトークみたいな流れになっていた。"

[[dialogue]]
speaker = "トワ先生"
# 「へぇ～、最近２人は会う機会があったんだ？」
line = "「へぇ～、最近２人は会う機会があったんだ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうなの。フィオナと親戚の結婚式で偶然会って、会場でも一緒に過ごしたのよね～」
line = "「そうなの。フィオナと親戚の結婚式で偶然会って、会場でも一緒に過ごしたのよね～」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ、花嫁さんが九浄家の方で、花婿さんが星見家の分家筋の方だったんです。なので私も招待されていて」
line = "「ええ、花嫁さんが九浄家の方で、花婿さんが星見家の分家筋の方だったんです。なので私も招待されていて」"

[[dialogue]]
speaker = "ヴィーナス"
# 「花嫁さん、とっても綺麗だったわよね！」
line = "「花嫁さん、とっても綺麗だったわよね！」"

[[dialogue]]
speaker = "フィオナ"
# 「はい、ウェディングドレスも憧れてしまいます……」
line = "「はい、ウェディングドレスも憧れてしまいます……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そういえば、トワちゃんは結婚したりしないの？」
line = "「そういえば、トワちゃんは結婚したりしないの？」"

[[dialogue]]
speaker = "トワ先生"
# 「何故そこでわたし！？」
line = "「何故そこでわたし！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だって、トワちゃんくらいの年齢になると、結婚しててもおかしくないでしょ？」
line = "「だって、トワちゃんくらいの年齢になると、結婚しててもおかしくないでしょ？」"

[[dialogue]]
speaker = "トワ先生"
# 「ヴィーナスちゃんは先生をいくつだと思ってるのかな！？」
line = "「ヴィーナスちゃんは先生をいくつだと思ってるのかな！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……大人の女性って、２０歳をこえたら結婚するものなんじゃないの？」
line = "「……大人の女性って、２０歳をこえたら結婚するものなんじゃないの？」"

[[dialogue]]
speaker = "トワ先生"
# 「純真１００パーセントの眼差し……！」
line = "「純真１００パーセントの眼差し……！」"

[[dialogue]]
speaker = "フィオナ"
# 「そ、そうなんですか！？　どうしましょう、もう何年もないのに、私はまだ男の人とお付き合いした経験もありませんが……」
line = "「そ、そうなんですか！？　どうしましょう、もう何年もないのに、私はまだ男の人とお付き合いした経験もありませんが……」"

[[dialogue]]
speaker = "トワ先生"
# 「そんなのわたしだって全然経験ないけど！　こんな歳なのに……！」
line = "「そんなのわたしだって全然経験ないけど！　こんな歳なのに……！」"

[[dialogue]]
speaker = "unk"
# （トワ先生って何歳なんだ……？）
line = "（トワ先生って何歳なんだ……？）"

[[dialogue]]
speaker = "unk"
# （そういえば、誰も突っ込まないけど）
line = "（そういえば、誰も突っ込まないけど）"

[[dialogue]]
speaker = "トワ先生"
# 「──いやもう、結婚の話題はいいから本題に戻ろうよ！」
line = "「──いやもう、結婚の話題はいいから本題に戻ろうよ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「確かに。すっかり話し込んで、脱線しちゃってたわ」
line = "「確かに。すっかり話し込んで、脱線しちゃってたわ」"

[[dialogue]]
speaker = "フィオナ"
# 「そういえば、元はモンスターの発生場所についてのお話だったでしょうか」
line = "「そういえば、元はモンスターの発生場所についてのお話だったでしょうか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうそう。たとえば、新星学園が開校した時から今までのアステラの発生場所とかって、図書委員の人に聞けばなにかわかるかしら？」
line = "「そうそう。たとえば、新星学園が開校した時から今までのアステラの発生場所とかって、図書委員の人に聞けばなにかわかるかしら？」"

[[dialogue]]
speaker = "トワ先生"
# 「ふふんっ。そういうことは、新星学園が開校した年から教員をやっている、わたしに聞きなさいっ」
line = "「ふふんっ。そういうことは、新星学園が開校した年から教員をやっている、わたしに聞きなさいっ」"

[[dialogue]]
speaker = "unk"
# 先生、それ逆算で年齢が……
line = "先生、それ逆算で年齢が……"

[[dialogue]]
speaker = "トワ先生"
# 「ふぇ……？」
line = "「ふぇ……？」"

[[dialogue]]
speaker = "トワ先生"
# 「はわわわわわわわ……！？」
line = "「はわわわわわわわ……！？」"

[[dialogue]]
speaker = "フィオナ"
# 「ま、まあ、トワ先生が何歳でも、可愛らしいことには変わりありませんし！」
line = "「ま、まあ、トワ先生が何歳でも、可愛らしいことには変わりありませんし！」"

[[dialogue]]
speaker = "トワ先生"
# 「それは果たしてフォローになってるのかな！？」
line = "「それは果たしてフォローになってるのかな！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「というか、トワちゃんがそんなに若くないのって、みんな知ってることなんじゃないの？」
line = "「というか、トワちゃんがそんなに若くないのって、みんな知ってることなんじゃないの？」"

[[dialogue]]
speaker = "トワ先生"
# 「ガーン……！」
line = "「ガーン……！」"

[[dialogue]]
speaker = "unk"
# あーあ……
line = "あーあ……"

[[dialogue]]
speaker = "ヴィーナス"
# 「あれ？　トワちゃんもわかっててやってるんだと思ってたけど」
line = "「あれ？　トワちゃんもわかっててやってるんだと思ってたけど」"

[[dialogue]]
speaker = "フィオナ"
# 「あはは……」
line = "「あはは……」"

[[dialogue]]
speaker = "トワ先生"
# 「……………………」
line = "「……………………」"

[[dialogue]]
speaker = "トワ先生"
# 「はっ……！　わたしはいったいなにを！？」
line = "「はっ……！　わたしはいったいなにを！？」"

[[dialogue]]
speaker = "トワ先生"
# 「えっと……そうそう！　モンスターに関する資料だっけ」
line = "「えっと……そうそう！　モンスターに関する資料だっけ」"

[[dialogue]]
speaker = "トワ先生"
# 「ヴィーナスちゃん、すぐに用意するから待っててね♪」
line = "「ヴィーナスちゃん、すぐに用意するから待っててね♪」"

[[dialogue]]
speaker = "unk"
# 余りの衝撃に耐えきれなかったトワ先生の脳は、意識を切断することで正気を保つことを選択したらしい。
line = "余りの衝撃に耐えきれなかったトワ先生の脳は、意識を切断することで正気を保つことを選択したらしい。"

[[dialogue]]
speaker = "トワ先生"
# 「ふんふん、ふふ～ん♪」
line = "「ふんふん、ふふ～ん♪」"

[[dialogue]]
speaker = "unk"
# なるほど──と。トワ先生の年齢の秘密が、生徒たちの間で暗黙の了解と化している理由を知る俺たちなのであった。
line = "なるほど──と。トワ先生の年齢の秘密が、生徒たちの間で暗黙の了解と化している理由を知る俺たちなのであった。"
