[[dialogue]]
speaker = "unk"
# 第１話,恋愛の勉強,P
line = "第１話,恋愛の勉強,P"

[[dialogue]]
speaker = "unk"
# 色々あって恋人同士になった俺とアナだったが、お互い恋愛について意識しない人生をおくっていたため、２人の時間では『恋愛についての勉強』をするようになった──
line = "色々あって恋人同士になった俺とアナだったが、お互い恋愛について意識しない人生をおくっていたため、２人の時間では『恋愛についての勉強』をするようになった──"

[[dialogue]]
speaker = "アナ"
# 「――というわけで、今日はお家デートの勉強をしましょう」
line = "「――というわけで、今日はお家デートの勉強をしましょう」"

[[dialogue]]
speaker = "アナ"
# 「会長とは既に何度かお家デートをしていますが……このところ、星徒会が忙しくてなかなか２人きりの時間が取れていませんでした」
line = "「会長とは既に何度かお家デートをしていますが……このところ、星徒会が忙しくてなかなか２人きりの時間が取れていませんでした」"

[[dialogue]]
speaker = "アナ"
# 「一応、遊べる道具は持って来ていますので、新たな発見は見込めるかと」
line = "「一応、遊べる道具は持って来ていますので、新たな発見は見込めるかと」"

[[dialogue]]
speaker = "unk"
# それは……ジグソーパズル？
line = "それは……ジグソーパズル？"

[[dialogue]]
speaker = "アナ"
# 「イエス。私の趣味の１つです」
line = "「イエス。私の趣味の１つです」"

[[dialogue]]
speaker = "アナ"
# 「ジグソーパズルは、人間界で出会った中でも非常に良いモノです。考えに行き詰った時に、脳をリラックスさせつつ回転を促すのにちょうどいい」
line = "「ジグソーパズルは、人間界で出会った中でも非常に良いモノです。考えに行き詰った時に、脳をリラックスさせつつ回転を促すのにちょうどいい」"

[[dialogue]]
speaker = "アナ"
# 「全体図を想像し、俯瞰しながら組み立てるので、問題解決力の向上に繋がる。更に完成したものを再度作り直す際は、記憶力のトレーニングにもなる」
line = "「全体図を想像し、俯瞰しながら組み立てるので、問題解決力の向上に繋がる。更に完成したものを再度作り直す際は、記憶力のトレーニングにもなる」"

[[dialogue]]
speaker = "アナ"
# 「なので、今日はその良さを伝えることも兼ねて、会長も一緒にジグソーパズルをやりましょう」
line = "「なので、今日はその良さを伝えることも兼ねて、会長も一緒にジグソーパズルをやりましょう」"

[[dialogue]]
speaker = "unk"
# ……俺の膝の上に座りながらやるのか？
line = "……俺の膝の上に座りながらやるのか？"

[[dialogue]]
speaker = "アナ"
# 「ノープロブレム。いつもの星徒会での仕事と同じ定位置です」
line = "「ノープロブレム。いつもの星徒会での仕事と同じ定位置です」"

[[dialogue]]
speaker = "アナ"
# 「むしろ、最近はこの体勢の方がしっくり来ます。会長が後ろにいるので、安心感があって落ち着く」
line = "「むしろ、最近はこの体勢の方がしっくり来ます。会長が後ろにいるので、安心感があって落ち着く」"

[[dialogue]]
speaker = "アナ"
# 「――ん？　星徒会室はいいけど、２人きりの時だと落ち着かない、ですか？」
line = "「――ん？　星徒会室はいいけど、２人きりの時だと落ち着かない、ですか？」"

[[dialogue]]
speaker = "アナ"
# 「――この体勢になると、どうしても密着するから変な気分になる？」
line = "「――この体勢になると、どうしても密着するから変な気分になる？」"

[[dialogue]]
speaker = "アナ"
# 「んっ……<emoji=heart04>　こら、ダメですよ、会長。……今はジグソーパズルの時間……<emoji=heart04>」
line = "「んっ……<emoji=heart04>　こら、ダメですよ、会長。……今はジグソーパズルの時間……<emoji=heart04>」"

[[dialogue]]
speaker = "アナ"
# 「まあ……恋人同士ですし。う、後ろから抱き締めるくらいは別に構いませんが……<emoji=heart04>」
line = "「まあ……恋人同士ですし。う、後ろから抱き締めるくらいは別に構いませんが……<emoji=heart04>」"

[[dialogue]]
speaker = "アナ"
# 「と、とにかく今は、ジグソーパズルの良さを知ってもらいたいので、そちらに集中して下さい」
line = "「と、とにかく今は、ジグソーパズルの良さを知ってもらいたいので、そちらに集中して下さい」"

[[dialogue]]
speaker = "アナ"
# 「え～、じゃないです。ほら、ここの絵の繋がりとか分かりやすそうですよ。会長も一緒にピースを探して下さい」
line = "「え～、じゃないです。ほら、ここの絵の繋がりとか分かりやすそうですよ。会長も一緒にピースを探して下さい」"

[[dialogue]]
speaker = "アナ"
# 「１０００ピースのうち、半分くらい出来ましたね。少し休憩しますか？」
line = "「１０００ピースのうち、半分くらい出来ましたね。少し休憩しますか？」"

[[dialogue]]
speaker = "unk"
# なら、俺も良いものを用意してるんだ
line = "なら、俺も良いものを用意してるんだ"

[[dialogue]]
speaker = "アナ"
# 「冷蔵庫から持ってきたそれは……プリンですか？　なるほど、和抹茶プリン。とても美味しそうです……！」
line = "「冷蔵庫から持ってきたそれは……プリンですか？　なるほど、和抹茶プリン。とても美味しそうです……！」"

[[dialogue]]
speaker = "アナ"
# 「早速食べてもいいですか？　――はい、いただきます」
line = "「早速食べてもいいですか？　――はい、いただきます」"

[[dialogue]]
speaker = "アナ"
# 「もぐもぐ……おっ……おぉぉぉ……！　す、凄く美味しいです。抹茶の上品な甘さが口の中でとろけるように広がります……！」
line = "「もぐもぐ……おっ……おぉぉぉ……！　す、凄く美味しいです。抹茶の上品な甘さが口の中でとろけるように広がります……！」"

[[dialogue]]
speaker = "アナ"
# 「こ、このプリンは一体どこのメーカーの？　和菓子好きとして、是非ともリピートしたい味です……！」
line = "「こ、このプリンは一体どこのメーカーの？　和菓子好きとして、是非ともリピートしたい味です……！」"

[[dialogue]]
speaker = "アナ"
# 「って、会長……？　どうして嬉しそうに笑っているんですか？」
line = "「って、会長……？　どうして嬉しそうに笑っているんですか？」"

[[dialogue]]
speaker = "unk"
# 手作りなんだ。アナの口に合って良かった
line = "手作りなんだ。アナの口に合って良かった"

[[dialogue]]
speaker = "アナ"
# 「なっ……えぇっ！？　会長がこれを作ったんですか……！？　いつの間にそんな技術を……」
line = "「なっ……えぇっ！？　会長がこれを作ったんですか……！？　いつの間にそんな技術を……」"

[[dialogue]]
speaker = "アナ"
# 「――付き合い始めた日のこと、ですか？　はい、もちろん覚えていますが……」
line = "「――付き合い始めた日のこと、ですか？　はい、もちろん覚えていますが……」"

[[dialogue]]
speaker = "アナ"
# 「か、会長が私のことを好き……！？　ま、まったく予想してなかったわけではありませんが……それでも、本当に私を選ぶなんて」
line = "「か、会長が私のことを好き……！？　ま、まったく予想してなかったわけではありませんが……それでも、本当に私を選ぶなんて」"

[[dialogue]]
speaker = "アナ"
# 「――い、嫌ではないです。会長は魅力的な男性だと……思います」
line = "「――い、嫌ではないです。会長は魅力的な男性だと……思います」"

[[dialogue]]
speaker = "アナ"
# 「優しいですし、器用で仕事もできる。前会長を打ち破る実力があり、それにも関わらず努力を常に怠らないで訓練し続けるのは、カッコいいと感じます……ですが」
line = "「優しいですし、器用で仕事もできる。前会長を打ち破る実力があり、それにも関わらず努力を常に怠らないで訓練し続けるのは、カッコいいと感じます……ですが」"

[[dialogue]]
speaker = "アナ"
# 「むしろ、会長は……私のどんなところが好き、なんですか？　私は自分がそこまで可愛いとは、正直思っていません。前会長や、サーシャ先輩、マトイ先輩の方がずっと――」
line = "「むしろ、会長は……私のどんなところが好き、なんですか？　私は自分がそこまで可愛いとは、正直思っていません。前会長や、サーシャ先輩、マトイ先輩の方がずっと――」"

[[dialogue]]
speaker = "アナ"
# 「え？　小動物みたいで可愛い？　眼鏡が似合う？　和菓子に目がなくてチョロい？　マイペースなようで真面目なところ？　クールなようで心優しい……ま、まだあるんですか？」
line = "「え？　小動物みたいで可愛い？　眼鏡が似合う？　和菓子に目がなくてチョロい？　マイペースなようで真面目なところ？　クールなようで心優しい……ま、まだあるんですか？」"

[[dialogue]]
speaker = "アナ"
# 「――い、一体いくつ出て来るんですか？　数え切れないくらい好きポイントがあるって……。あ、あうぅ」
line = "「――い、一体いくつ出て来るんですか？　数え切れないくらい好きポイントがあるって……。あ、あうぅ」"

[[dialogue]]
speaker = "アナ"
# 「も、もういいですっ！　分かりました。会長が私のことを好きなのは、よく分かりましたから……」
line = "「も、もういいですっ！　分かりました。会長が私のことを好きなのは、よく分かりましたから……」"

[[dialogue]]
speaker = "unk"
# 美味しい和菓子の作り方、勉強するから
line = "美味しい和菓子の作り方、勉強するから"

[[dialogue]]
speaker = "アナ"
# 「だから付き合って欲しいと？　和菓子を作ってくれる恋人は、確かに魅力的ですが……それよりも――」
line = "「だから付き合って欲しいと？　和菓子を作ってくれる恋人は、確かに魅力的ですが……それよりも――」"

[[dialogue]]
speaker = "アナ"
# 「私としては、男女の付き合い方を一緒に勉強してくれると……嬉しいです」
line = "「私としては、男女の付き合い方を一緒に勉強してくれると……嬉しいです」"

[[dialogue]]
speaker = "アナ"
# 「会長との恋人関係に興味はありますが……私は恋愛、初心者ですので」
line = "「会長との恋人関係に興味はありますが……私は恋愛、初心者ですので」"

[[dialogue]]
speaker = "アナ"
# 「……本当にあれから、和菓子の作り方を勉強していたんですね」
line = "「……本当にあれから、和菓子の作り方を勉強していたんですね」"

[[dialogue]]
speaker = "アナ"
# 「――ようやく最近、披露できるレベルになった？　私の為に、そこまでしなくても良かったのに……」
line = "「――ようやく最近、披露できるレベルになった？　私の為に、そこまでしなくても良かったのに……」"

[[dialogue]]
speaker = "unk"
# 好きな子には、やっぱり喜んでもらいたい
line = "好きな子には、やっぱり喜んでもらいたい"

[[dialogue]]
speaker = "アナ"
# 「会長はまた、そういうことを……」
line = "「会長はまた、そういうことを……」"

[[dialogue]]
speaker = "unk"
# アナは正面から俺の膝の上に座り、じっと見上げて来る――
line = "アナは正面から俺の膝の上に座り、じっと見上げて来る――"

[[dialogue]]
speaker = "アナ"
# 「――ジグソーパズルは再開しないのかって？　一応、会長から美味しい和菓子をもらいましたので……」
line = "「――ジグソーパズルは再開しないのかって？　一応、会長から美味しい和菓子をもらいましたので……」"

[[dialogue]]
speaker = "アナ"
# 「先に、そのお礼をするのが筋かなと思いまして」
line = "「先に、そのお礼をするのが筋かなと思いまして」"

[[dialogue]]
speaker = "unk"
# アナ、可愛い……好きだ
line = "アナ、可愛い……好きだ"

[[dialogue]]
speaker = "アナ"
# 「んっ……<emoji=heart04>　会長、頭を撫でながら、耳元で囁くのはズルいです……」
line = "「んっ……<emoji=heart04>　会長、頭を撫でながら、耳元で囁くのはズルいです……」"

[[dialogue]]
speaker = "アナ"
# 「――私が会長のことを好きか？　そんな野暮なこと、聞かないで下さい……<emoji=heart04>」
line = "「――私が会長のことを好きか？　そんな野暮なこと、聞かないで下さい……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その後、２人でじっくりイチャイチャの勉強に勤しむのだった――
line = "その後、２人でじっくりイチャイチャの勉強に勤しむのだった――"
