[[dialogue]]
speaker = "unk"
# 第２話,傲慢の先生,P
line = "第２話,傲慢の先生,P"

[[dialogue]]
speaker = "unk"
# モネが演劇部の部室にいる、と聞いてやってきたのだが──
line = "モネが演劇部の部室にいる、と聞いてやってきたのだが──"

[[dialogue]]
speaker = "ロクサーナ"
# 「かーくーすーなー！　立派なブツがあるんだから堂々としていろ！」
line = "「かーくーすーなー！　立派なブツがあるんだから堂々としていろ！」"

[[dialogue]]
speaker = "モネ"
# 「は、はい！？」
line = "「は、はい！？」"

[[dialogue]]
speaker = "ロクサーナ"
# 「まず両腕を上げて、手首を重ねろ。それから腰をひねって……」
line = "「まず両腕を上げて、手首を重ねろ。それから腰をひねって……」"

[[dialogue]]
speaker = "モネ"
# 「こ、こうでしょうか……？」
line = "「こ、こうでしょうか……？」"

[[dialogue]]
speaker = "ロクサーナ"
# 「そうだ、悪くないぞ。よし次は……」
line = "「そうだ、悪くないぞ。よし次は……」"

[[dialogue]]
speaker = "unk"
# 何をしているんですか？
line = "何をしているんですか？"

[[dialogue]]
speaker = "モネ"
# 「か、会長！？」
line = "「か、会長！？」"

[[dialogue]]
speaker = "ロクサーナ"
# 「見て分からんか？　なら教えてやろう。これはセクシーポーズの練習だ」
line = "「見て分からんか？　なら教えてやろう。これはセクシーポーズの練習だ」"

[[dialogue]]
speaker = "モネ"
# 「えぇっ！！　ロクサーナ先輩、傲慢さを体現したポーズだって言ったじゃないですかぁ！？」
line = "「えぇっ！！　ロクサーナ先輩、傲慢さを体現したポーズだって言ったじゃないですかぁ！？」"

[[dialogue]]
speaker = "ロクサーナ"
# 「己の肉体がいかに魅力的か、周囲に見せびらかすポーズだぞ。これが傲慢でなくて何なのだ」
line = "「己の肉体がいかに魅力的か、周囲に見せびらかすポーズだぞ。これが傲慢でなくて何なのだ」"

[[dialogue]]
speaker = "モネ"
# 「えええ～～～っ！？　騙されたーーーっ！？」
line = "「えええ～～～っ！？　騙されたーーーっ！？」"

[[dialogue]]
speaker = "ロクサーナ"
# 「くっくっく。お前の恋人は実に面白いな、会長」
line = "「くっくっく。お前の恋人は実に面白いな、会長」"

[[dialogue]]
speaker = "モネ"
# 「先輩、私たちがお付き合いしてるの知ってたんですか！？」
line = "「先輩、私たちがお付き合いしてるの知ってたんですか！？」"

[[dialogue]]
speaker = "ロクサーナ"
# 「寮の連中が噂していたぞ？」
line = "「寮の連中が噂していたぞ？」"

[[dialogue]]
speaker = "モネ"
# 「そんな～！？」
line = "「そんな～！？」"

[[dialogue]]
speaker = "unk"
# モネはなんで演劇部に？
line = "モネはなんで演劇部に？"

[[dialogue]]
speaker = "モネ"
# 「先日の事件で、私は『傲慢』の魔将に選ばれ、魔本の力でパワーアップしました」
line = "「先日の事件で、私は『傲慢』の魔将に選ばれ、魔本の力でパワーアップしました」"

[[dialogue]]
speaker = "モネ"
# 「その力は幾千幾万の時を超えて収集された、魔族の怨念。とても１人の星騎士では扱いきれないほどの大きな力です」
line = "「その力は幾千幾万の時を超えて収集された、魔族の怨念。とても１人の星騎士では扱いきれないほどの大きな力です」"

[[dialogue]]
speaker = "モネ"
# 「だから思うんです。私はまだ『傲慢』の力を使いこなせていないって」
line = "「だから思うんです。私はまだ『傲慢』の力を使いこなせていないって」"

[[dialogue]]
speaker = "モネ"
# 「そこで、傲慢の何たるかを会得するため、私の知る中で最も傲慢という言葉が似合うロクサーナ先輩に弟子入りしたんです！」
line = "「そこで、傲慢の何たるかを会得するため、私の知る中で最も傲慢という言葉が似合うロクサーナ先輩に弟子入りしたんです！」"

[[dialogue]]
speaker = "unk"
# （本人の前で傲慢とか言っちゃうんだ！？）
line = "（本人の前で傲慢とか言っちゃうんだ！？）"

[[dialogue]]
speaker = "ロクサーナ"
# 「わっはっは！　お前の恋人はほんっとうに面白いな！」
line = "「わっはっは！　お前の恋人はほんっとうに面白いな！」"

[[dialogue]]
speaker = "ロクサーナ"
# 「さて。こうしてお迎えが来たから言ってやるが、私がお前に教えることなど何もない」
line = "「さて。こうしてお迎えが来たから言ってやるが、私がお前に教えることなど何もない」"

[[dialogue]]
speaker = "モネ"
# 「えぇっ！？」
line = "「えぇっ！？」"

[[dialogue]]
speaker = "ロクサーナ"
# 「まぁ、聞け。お前も作家の端くれだろう？　脚本……ではないな。小説か？」
line = "「まぁ、聞け。お前も作家の端くれだろう？　脚本……ではないな。小説か？」"

[[dialogue]]
speaker = "モネ"
# 「私が小説を書いていること、わかるんですか？」
line = "「私が小説を書いていること、わかるんですか？」"

[[dialogue]]
speaker = "ロクサーナ"
# 「ああ。お前が私を見ている表情に書いてあった。『これは使える』とな。お前の眼は物書きの眼だ」
line = "「ああ。お前が私を見ている表情に書いてあった。『これは使える』とな。お前の眼は物書きの眼だ」"

[[dialogue]]
speaker = "モネ"
# 「えぇっ、そんな顔してましたか？　失礼しましたっ」
line = "「えぇっ、そんな顔してましたか？　失礼しましたっ」"

[[dialogue]]
speaker = "ロクサーナ"
# 「構わん。私たちにとって神羅万象は創造の糧。人、物、動物はもちろん、事象でさえも、だ」
line = "「構わん。私たちにとって神羅万象は創造の糧。人、物、動物はもちろん、事象でさえも、だ」"

[[dialogue]]
speaker = "ロクサーナ"
# 「ときには目を背けたくなるような凄惨な事件すら、物語に昇華される。例えば、戦争、災害、あるいは大事故。枚挙に暇はない」
line = "「ときには目を背けたくなるような凄惨な事件すら、物語に昇華される。例えば、戦争、災害、あるいは大事故。枚挙に暇はない」"

[[dialogue]]
speaker = "ロクサーナ"
# 「あるいは作家というものは、人の不幸にたかるウジ虫なのかもしれん。──どうだ、醜いだろう？」
line = "「あるいは作家というものは、人の不幸にたかるウジ虫なのかもしれん。──どうだ、醜いだろう？」"

[[dialogue]]
speaker = "モネ"
# 「それは…………」
line = "「それは…………」"

[[dialogue]]
speaker = "ロクサーナ"
# 「では、お前のしていることは不謹慎だ、不道徳だと言われたら、筆を折るか？」
line = "「では、お前のしていることは不謹慎だ、不道徳だと言われたら、筆を折るか？」"

[[dialogue]]
speaker = "モネ"
# 「……いいえ、あり得ません。私はそれでも書き続けます。だって、そうせずにはいられないから」
line = "「……いいえ、あり得ません。私はそれでも書き続けます。だって、そうせずにはいられないから」"

[[dialogue]]
speaker = "ロクサーナ"
# 「ああ、その通りだ。そも創造とは神の領分。それを侵しているのだ。これを傲慢と言わずして何が傲慢か。作家はみな、傲慢から生まれてくると言ってもいい」
line = "「ああ、その通りだ。そも創造とは神の領分。それを侵しているのだ。これを傲慢と言わずして何が傲慢か。作家はみな、傲慢から生まれてくると言ってもいい」"

[[dialogue]]
speaker = "ロクサーナ"
# 「安心しろ、紙屋敷モネ。お前はすでに傲慢だ。……ふ、喋りすぎたな、喉が渇いた。コーヒーを淹れてくれ」
line = "「安心しろ、紙屋敷モネ。お前はすでに傲慢だ。……ふ、喋りすぎたな、喉が渇いた。コーヒーを淹れてくれ」"

[[dialogue]]
speaker = "モネ"
# 「はい。……悪魔のように黒く、地獄のように熱いヤツ、ですね」
line = "「はい。……悪魔のように黒く、地獄のように熱いヤツ、ですね」"

[[dialogue]]
speaker = "ロクサーナ"
# 「ああ、よく分かってるじゃないか」
line = "「ああ、よく分かってるじゃないか」"

[[dialogue]]
speaker = "unk"
# ところで、なんでずっと水着なの？
line = "ところで、なんでずっと水着なの？"

[[dialogue]]
speaker = "モネ"
# 「ひゃっ！？　水着なの忘れてました！」
line = "「ひゃっ！？　水着なの忘れてました！」"

[[dialogue]]
speaker = "ロクサーナ"
# 「言うのが早いぞ、会長。いつまで水着のままでいるか試していたのに」
line = "「言うのが早いぞ、会長。いつまで水着のままでいるか試していたのに」"

[[dialogue]]
speaker = "モネ"
# 「試さないでください！」
line = "「試さないでください！」"

[[dialogue]]
speaker = "ロクサーナ"
# 「会長も想像してみろ。モネが水着で小説を執筆している姿を。ペンを走らせるたびに揺れる果実……どうだ、そそるだろう？」
line = "「会長も想像してみろ。モネが水着で小説を執筆している姿を。ペンを走らせるたびに揺れる果実……どうだ、そそるだろう？」"

[[dialogue]]
speaker = "unk"
# ……確かに
line = "……確かに"

[[dialogue]]
speaker = "モネ"
# 「もうっ！　会長もなに言ってるんですか！」
line = "「もうっ！　会長もなに言ってるんですか！」"

[[dialogue]]
speaker = "モネ"
# 「ぷっく～」
line = "「ぷっく～」"

[[dialogue]]
speaker = "unk"
# 頬を膨らませて拗ねるモネ。申し訳ないけれど、そんなところも可愛いのだった。
line = "頬を膨らませて拗ねるモネ。申し訳ないけれど、そんなところも可愛いのだった。"
