[[dialogue]]
speaker = "unk"
# 第４話,ふわふわどきどきモーメント,P
line = "第４話,ふわふわどきどきモーメント,P"

[[dialogue]]
speaker = "unk"
# サランとの付き合いも長くなり始めた、とある休日のこと――
line = "サランとの付き合いも長くなり始めた、とある休日のこと――"

[[dialogue]]
speaker = "サラン"
# 「サランと、１日兄妹ごっこして欲しいの～♪」
line = "「サランと、１日兄妹ごっこして欲しいの～♪」"

[[dialogue]]
speaker = "unk"
# いきなりどういうこと！？
line = "いきなりどういうこと！？"

[[dialogue]]
speaker = "unk"
# 家に遊びに来る否や彼女が言い出した内容に、俺は理解が追い付かない。
line = "家に遊びに来る否や彼女が言い出した内容に、俺は理解が追い付かない。"

[[dialogue]]
speaker = "サラン"
# 「ほら、この前、星騎士として活躍したご褒美に～、サランのお願いを１つ叶えてくれるって言ってたじゃない？」
line = "「ほら、この前、星騎士として活躍したご褒美に～、サランのお願いを１つ叶えてくれるって言ってたじゃない？」"

[[dialogue]]
speaker = "unk"
# だからって、何故に兄妹ごっこ！？
line = "だからって、何故に兄妹ごっこ！？"

[[dialogue]]
speaker = "サラン"
# 「えっと実はね～、サラン、童話の絵本が好きなんだ～。特に、お菓子の家が出て来る『ヘンゼルとグレーテル』が昔から好きで～」
line = "「えっと実はね～、サラン、童話の絵本が好きなんだ～。特に、お菓子の家が出て来る『ヘンゼルとグレーテル』が昔から好きで～」"

[[dialogue]]
speaker = "サラン"
# 「それでヘンゼルみたいな頼れるお兄ちゃんに、ちょっと憧れがあるんだぁ♪」
line = "「それでヘンゼルみたいな頼れるお兄ちゃんに、ちょっと憧れがあるんだぁ♪」"

[[dialogue]]
speaker = "サラン"
# 「ほら、会長ちゃん、最初に会った時もそうだし、それからもサランのこと、色々と助けてくれるでしょ～？」
line = "「ほら、会長ちゃん、最初に会った時もそうだし、それからもサランのこと、色々と助けてくれるでしょ～？」"

[[dialogue]]
speaker = "サラン"
# 「何だかヘンゼルお兄ちゃんみたいだな～って、ずっと思ってたの～」
line = "「何だかヘンゼルお兄ちゃんみたいだな～って、ずっと思ってたの～」"

[[dialogue]]
speaker = "unk"
# 同級生だから、ちょっと照れくさいけど……
line = "同級生だから、ちょっと照れくさいけど……"

[[dialogue]]
speaker = "サラン"
# 「わぁ～、呼んでもいいの～？　やった～♪　ありがとう、会長ちゃん～♪」
line = "「わぁ～、呼んでもいいの～？　やった～♪　ありがとう、会長ちゃん～♪」"

[[dialogue]]
speaker = "サラン"
# 「じゃあじゃあ、会長ちゃんとサランは今から１日兄妹ってことで～」
line = "「じゃあじゃあ、会長ちゃんとサランは今から１日兄妹ってことで～」"

[[dialogue]]
speaker = "サラン"
# 「よろしくね～、<b>お兄ちゃん</b>♪」
line = "「よろしくね～、<b>お兄ちゃん</b>♪」"

[[dialogue]]
speaker = "unk"
# （サーシャさんの気持ちがわかった気がする！）
line = "（サーシャさんの気持ちがわかった気がする！）"

[[dialogue]]
speaker = "サラン"
# 「ぽよ？　どうしたの、お兄ちゃん？」
line = "「ぽよ？　どうしたの、お兄ちゃん？」"

[[dialogue]]
speaker = "サラン"
# 「……兄からして欲しいこと、どんどん言って欲しい？　うん、色々あるんだ～♪」
line = "「……兄からして欲しいこと、どんどん言って欲しい？　うん、色々あるんだ～♪」"

[[dialogue]]
speaker = "サラン"
# 「えっとね～、まずは優しく頭撫でて欲しいなって……」
line = "「えっとね～、まずは優しく頭撫でて欲しいなって……」"

[[dialogue]]
speaker = "unk"
# 言われるがまま、サランの頭を撫でる。
line = "言われるがまま、サランの頭を撫でる。"

[[dialogue]]
speaker = "サラン"
# 「あ……ふわぁ～……♪　これ何か、気持ち良くてふわふわする～♪」
line = "「あ……ふわぁ～……♪　これ何か、気持ち良くてふわふわする～♪」"

[[dialogue]]
speaker = "サラン"
# 「えへへ～♪　お兄ちゃんの手、大きくて温かくて気持ちいい～♪」
line = "「えへへ～♪　お兄ちゃんの手、大きくて温かくて気持ちいい～♪」"

[[dialogue]]
speaker = "サラン"
# 「それからね～、お兄ちゃんにあ～んってお菓子を食べさせて欲しい～♪」
line = "「それからね～、お兄ちゃんにあ～んってお菓子を食べさせて欲しい～♪」"

[[dialogue]]
speaker = "unk"
# 来客用のクッキーを手に取った。
line = "来客用のクッキーを手に取った。"

[[dialogue]]
speaker = "サラン"
# 「えへへ～♪　食べさせて、お兄ちゃん♪」
line = "「えへへ～♪　食べさせて、お兄ちゃん♪」"

[[dialogue]]
speaker = "サラン"
# 「は～い、あ～ん♪　……もぐもぐ、ん～、美味しい～♪」
line = "「は～い、あ～ん♪　……もぐもぐ、ん～、美味しい～♪」"

[[dialogue]]
speaker = "サラン"
# 「普通のクッキーなのに、お兄ちゃんに食べさせて貰うだけで、何か甘くてふわふわする～♪　ふわぁ～、幸せ～♪」
line = "「普通のクッキーなのに、お兄ちゃんに食べさせて貰うだけで、何か甘くてふわふわする～♪　ふわぁ～、幸せ～♪」"

[[dialogue]]
speaker = "unk"
# 俺も何か今、凄く幸せな気分だ
line = "俺も何か今、凄く幸せな気分だ"

[[dialogue]]
speaker = "サラン"
# 「本当～？　そっか、サランと一緒なんだ～♪　なんかそれって嬉しいかも～♪」
line = "「本当～？　そっか、サランと一緒なんだ～♪　なんかそれって嬉しいかも～♪」"

[[dialogue]]
speaker = "サラン"
# 「ねぇ～、次は～、お兄ちゃんに膝枕をして欲しいな～♪」
line = "「ねぇ～、次は～、お兄ちゃんに膝枕をして欲しいな～♪」"

[[dialogue]]
speaker = "unk"
# ソファーに座って、自分の太ももをぽんぽんと叩いた。
line = "ソファーに座って、自分の太ももをぽんぽんと叩いた。"

[[dialogue]]
speaker = "サラン"
# 「わ～い、サラン、膝枕して貰うの好きなんだ～♪」
line = "「わ～い、サラン、膝枕して貰うの好きなんだ～♪」"

[[dialogue]]
speaker = "サラン"
# 「でも、よく考えたら、家族以外にして貰うのは初めてかも～♪」
line = "「でも、よく考えたら、家族以外にして貰うのは初めてかも～♪」"

[[dialogue]]
speaker = "サラン"
# 「それじゃあ、お膝借りるね～♪」
line = "「それじゃあ、お膝借りるね～♪」"

[[dialogue]]
speaker = "サラン"
# 「ふわぁ～、これ何か、凄くいいかも～♪　心ぽかぽかだけど、落ち着いて安心もする～♪」
line = "「ふわぁ～、これ何か、凄くいいかも～♪　心ぽかぽかだけど、落ち着いて安心もする～♪」"

[[dialogue]]
speaker = "サラン"
# 「んっ……頭も撫でてくれるの～？　ふわぁ～、サラン、ずっとこうしてたいかもぉ～……♪」
line = "「んっ……頭も撫でてくれるの～？　ふわぁ～、サラン、ずっとこうしてたいかもぉ～……♪」"

[[dialogue]]
speaker = "サラン"
# 「ねぇ～、<b>会長ちゃん</b>。いま気付いたことがあって～」
line = "「ねぇ～、<b>会長ちゃん</b>。いま気付いたことがあって～」"

[[dialogue]]
speaker = "サラン"
# 「サラン、会長ちゃんとこうして一緒に居ると、それだけで気持ちがふわふわするんだ～。何だかそれって――」
line = "「サラン、会長ちゃんとこうして一緒に居ると、それだけで気持ちがふわふわするんだ～。何だかそれって――」"

[[dialogue]]
speaker = "サラン"
# 「本当の家族みたいだよね～♪」
line = "「本当の家族みたいだよね～♪」"

[[dialogue]]
speaker = "unk"
# サランの何気ない言葉に、ドキッとしてしまう。
line = "サランの何気ない言葉に、ドキッとしてしまう。"

[[dialogue]]
speaker = "unk"
# （お兄ちゃんと呼ばれた時と違って……）
line = "（お兄ちゃんと呼ばれた時と違って……）"

[[dialogue]]
speaker = "unk"
# （何だこれ……）
line = "（何だこれ……）"

[[dialogue]]
speaker = "サラン"
# 「ぽよ？　会長ちゃん、どうしたの～？」
line = "「ぽよ？　会長ちゃん、どうしたの～？」"

[[dialogue]]
speaker = "サラン"
# 「手で目隠ししたら、何も見えないよ～？　これって何かの遊び～？」
line = "「手で目隠ししたら、何も見えないよ～？　これって何かの遊び～？」"

[[dialogue]]
speaker = "unk"
# い、いや、何でもない……
line = "い、いや、何でもない……"

[[dialogue]]
speaker = "unk"
# そう言って俺は、熱くなった顔を彼女から見られないように誤魔化すのだった。
line = "そう言って俺は、熱くなった顔を彼女から見られないように誤魔化すのだった。"
