[[dialogue]]
speaker = "unk"
# 第１話,ロロットさんってどんな人？,P
line = "第１話,ロロットさんってどんな人？,P"

[[dialogue]]
speaker = "unk"
# 星騎士が存在する俺たちの世界と、流星クルセイダースが存在するリアさんたちの世界。
line = "星騎士が存在する俺たちの世界と、流星クルセイダースが存在するリアさんたちの世界。"

[[dialogue]]
speaker = "unk"
# ２つの世界の境界の乱れが落ち着くまで今しばらくかかるため、その間、新星学園の星徒会室を開放することにした。
line = "２つの世界の境界の乱れが落ち着くまで今しばらくかかるため、その間、新星学園の星徒会室を開放することにした。"

[[dialogue]]
speaker = "unk"
# 連日、星騎士の面々が訪れては伝説のクルセイダースと交流を深めており、今日はルリエルがやってきたのだが──
line = "連日、星騎士の面々が訪れては伝説のクルセイダースと交流を深めており、今日はルリエルがやってきたのだが──"

[[dialogue]]
speaker = "リア"
# 「ロロットちゃんがどんな人なのかを知りたいの？」
line = "「ロロットちゃんがどんな人なのかを知りたいの？」"

[[dialogue]]
speaker = "ルリエル"
# 「はい！　向こうの世界にはなかなか行けませんから、少しでもロロットさんのことを知っておきたいな、と思いまして！」
line = "「はい！　向こうの世界にはなかなか行けませんから、少しでもロロットさんのことを知っておきたいな、と思いまして！」"

[[dialogue]]
speaker = "unk"
# ルリエルはお世話になったしね
line = "ルリエルはお世話になったしね"

[[dialogue]]
speaker = "ルリエル"
# 「はいです～♪　素敵なお屋敷、豪華な食べ物、どれをとっても最高だったのですっ」
line = "「はいです～♪　素敵なお屋敷、豪華な食べ物、どれをとっても最高だったのですっ」"

[[dialogue]]
speaker = "ルリエル"
# 「困ったときは執事のじいやさんがしゅばばっと駆けつけてくれましたし、登下校は毎日がリムジンで……！」
line = "「困ったときは執事のじいやさんがしゅばばっと駆けつけてくれましたし、登下校は毎日がリムジンで……！」"

[[dialogue]]
speaker = "聖沙"
# 「今さらだけどよく違和感を覚えなかったわね。もしかしてルリエルさんもお嬢様だったりするのかしら？」
line = "「今さらだけどよく違和感を覚えなかったわね。もしかしてルリエルさんもお嬢様だったりするのかしら？」"

[[dialogue]]
speaker = "ルリエル"
# 「いえ。ルリエルは天界のド田舎の出身なのです！　お金とは無縁なのですよっ」
line = "「いえ。ルリエルは天界のド田舎の出身なのです！　お金とは無縁なのですよっ」"

[[dialogue]]
speaker = "聖沙"
# 「自信満々に言うことじゃないわよ！？」
line = "「自信満々に言うことじゃないわよ！？」"

[[dialogue]]
speaker = "ルリエル"
# 「でもでも、きっと精神的に似通うところはあると思うのです。リクリエの影響とは言え、この上なく馴染んでいたので……」
line = "「でもでも、きっと精神的に似通うところはあると思うのです。リクリエの影響とは言え、この上なく馴染んでいたので……」"

[[dialogue]]
speaker = "ルリエル"
# 「ロロットさんはきっと素敵な大天使様なのです。だからルリエルもあやかりたいのですよ～♪」
line = "「ロロットさんはきっと素敵な大天使様なのです。だからルリエルもあやかりたいのですよ～♪」"

[[dialogue]]
speaker = "聖沙"
# 「素敵な大天使様、ね。そこはちょっぴり訂正したいけど、まあ確かにルリエルさんは、ロロットさんに似てるかも？」
line = "「素敵な大天使様、ね。そこはちょっぴり訂正したいけど、まあ確かにルリエルさんは、ロロットさんに似てるかも？」"

[[dialogue]]
speaker = "リア"
# 「ふふ、そうだね。好奇心いっぱいに動き回るところなんて、ロロットちゃんにそっくりかも♪」
line = "「ふふ、そうだね。好奇心いっぱいに動き回るところなんて、ロロットちゃんにそっくりかも♪」"

[[dialogue]]
speaker = "リア"
# 「そのかわいい貯金箱を持ってると本当に似てる。姉妹かなって思っちゃうくらい」
line = "「そのかわいい貯金箱を持ってると本当に似てる。姉妹かなって思っちゃうくらい」"

[[dialogue]]
speaker = "ルリエル"
# 「トントロのことですか？　ロロットさんもいつも持っていたのです？」
line = "「トントロのことですか？　ロロットさんもいつも持っていたのです？」"

[[dialogue]]
speaker = "リア"
# 「うん。読書する時でもお昼寝する時でも、とっても大事そうにね♪」
line = "「うん。読書する時でもお昼寝する時でも、とっても大事そうにね♪」"

[[dialogue]]
speaker = "聖沙"
# 「大切にしてる割にはよく壊してた気もしますけど……」
line = "「大切にしてる割にはよく壊してた気もしますけど……」"

[[dialogue]]
speaker = "ルリエル"
# 「おお……！　じゃあルリエルも、この服の時は必ず持ち歩くことにするのです～♪」
line = "「おお……！　じゃあルリエルも、この服の時は必ず持ち歩くことにするのです～♪」"

[[dialogue]]
speaker = "聖沙"
# 「と、ところで……ごくり。その可愛い貯金箱、後で私にも抱っこさせてもらってもいいかしら？」
line = "「と、ところで……ごくり。その可愛い貯金箱、後で私にも抱っこさせてもらってもいいかしら？」"

[[dialogue]]
speaker = "ルリエル"
# 「もちろんです～。えへへ、一緒にトントロを愛でちゃいましょう～」
line = "「もちろんです～。えへへ、一緒にトントロを愛でちゃいましょう～」"

[[dialogue]]
speaker = "リア"
# 「あ。そこはちょっと違うかも」
line = "「あ。そこはちょっと違うかも」"

[[dialogue]]
speaker = "ルリエル"
# 「ふぇえ？」
line = "「ふぇえ？」"

[[dialogue]]
speaker = "リア"
# 「ロロットちゃんなら『トントロは渡しませんよっ』て言うかな～って」
line = "「ロロットちゃんなら『トントロは渡しませんよっ』て言うかな～って」"

[[dialogue]]
speaker = "ルリエル"
# 「そうだったのですかっ。だったら、ルリエルもトントロは渡さないのですっ！」
line = "「そうだったのですかっ。だったら、ルリエルもトントロは渡さないのですっ！」"

[[dialogue]]
speaker = "聖沙"
# 「そそ、そんなぁ～っ！　がっくし……！」
line = "「そそ、そんなぁ～っ！　がっくし……！」"

[[dialogue]]
speaker = "リア"
# 「よ、余計なことを言っちゃったかな……？」
line = "「よ、余計なことを言っちゃったかな……？」"

[[dialogue]]
speaker = "unk"
# 貯金箱もだけど、その本は？
line = "貯金箱もだけど、その本は？"

[[dialogue]]
speaker = "ルリエル"
# 「あ、これはガイドブックなのです。『実話・人間界』。トントロと一緒で、これも常に携行していたのです」
line = "「あ、これはガイドブックなのです。『実話・人間界』。トントロと一緒で、これも常に携行していたのです」"

[[dialogue]]
speaker = "ルリエル"
# 「このガイドブック、とっても便利なのですよ～。タメになる言葉がたっくさん載っているのです！」
line = "「このガイドブック、とっても便利なのですよ～。タメになる言葉がたっくさん載っているのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「『天使も危うきに近寄らず』『天使は二物を与える』などなど……」
line = "「『天使も危うきに近寄らず』『天使は二物を与える』などなど……」"

[[dialogue]]
speaker = "ルリエル"
# 「ルリエル、天使なのに知らないことわざがいっぱいでした！　これを見て勉強して、もっと立派な大天使様になるのですよ～♪」
line = "「ルリエル、天使なのに知らないことわざがいっぱいでした！　これを見て勉強して、もっと立派な大天使様になるのですよ～♪」"

[[dialogue]]
speaker = "unk"
# 色々と間違ってるような……？
line = "色々と間違ってるような……？"

[[dialogue]]
speaker = "聖沙"
# 「間違いなく間違っているのだけど……」
line = "「間違いなく間違っているのだけど……」"

[[dialogue]]
speaker = "リア"
# 「うん。ロロットちゃんに近づくって意味では、この上なく正解～って感じだね♪」
line = "「うん。ロロットちゃんに近づくって意味では、この上なく正解～って感じだね♪」"

[[dialogue]]
speaker = "unk"
# 近づいてるんですか！？
line = "近づいてるんですか！？"

[[dialogue]]
speaker = "ルリエル"
# 「わーい！　嬉しいのですっ。この調子でロロットさんのような素敵な大天使様に──」
line = "「わーい！　嬉しいのですっ。この調子でロロットさんのような素敵な大天使様に──」"

[[dialogue]]
speaker = "リア"
# 「あ、そんな両手を上げてバンザイなんてしちゃったら──」
line = "「あ、そんな両手を上げてバンザイなんてしちゃったら──」"

[[dialogue]]
speaker = "聖沙"
# 「貯金箱が──！」
line = "「貯金箱が──！」"

[[dialogue]]
speaker = "ルリエル"
# 「ひ、ひぇぇえ～っ！　トントロが爆発四散しちゃったのです～っ！」
line = "「ひ、ひぇぇえ～っ！　トントロが爆発四散しちゃったのです～っ！」"

[[dialogue]]
speaker = "ルリエル"
# 「あ、あわわ～。とりあえず絆創膏で仮止めを……」
line = "「あ、あわわ～。とりあえず絆創膏で仮止めを……」"

[[dialogue]]
speaker = "リア"
# 「あ。修理の仕方もおんなじなんだ？」
line = "「あ。修理の仕方もおんなじなんだ？」"

[[dialogue]]
speaker = "聖沙"
# 「よく持ってたわね、絆創膏」
line = "「よく持ってたわね、絆創膏」"

[[dialogue]]
speaker = "ルリエル"
# 「備えあれば嬉しいな、なのです……うぅ……」
line = "「備えあれば嬉しいな、なのです……うぅ……」"

[[dialogue]]
speaker = "ルリエル"
# 「ぐすん。応急手当で何とかなりました……トントロ、ごめんなさいなのです」
line = "「ぐすん。応急手当で何とかなりました……トントロ、ごめんなさいなのです」"

[[dialogue]]
speaker = "ルリエル"
# 「ロロットさんにも怒られちゃうかもしれません。はぅう、ルリエル、いつもドジばっかり」
line = "「ロロットさんにも怒られちゃうかもしれません。はぅう、ルリエル、いつもドジばっかり」"

[[dialogue]]
speaker = "聖沙"
# 「大丈夫じゃないかしら。ルリエルさんよりもっと壊してた気がするし」
line = "「大丈夫じゃないかしら。ルリエルさんよりもっと壊してた気がするし」"

[[dialogue]]
speaker = "ルリエル"
# 「そ、そうなのですか！？」
line = "「そ、そうなのですか！？」"

[[dialogue]]
speaker = "リア"
# 「うん。トントロは何度も壊れちゃう運命にある子だからね」
line = "「うん。トントロは何度も壊れちゃう運命にある子だからね」"

[[dialogue]]
speaker = "unk"
# いいんですか、それで！？
line = "いいんですか、それで！？"

[[dialogue]]
speaker = "ルリエル"
# 「そう言っていただけると、安心なのです。あ、そうです。お客様に何かお出しするのですよ」
line = "「そう言っていただけると、安心なのです。あ、そうです。お客様に何かお出しするのですよ」"

[[dialogue]]
speaker = "ルリエル"
# 「ルリエルが腕まくりしてお紅茶を淹れるのです～」
line = "「ルリエルが腕まくりしてお紅茶を淹れるのです～」"

[[dialogue]]
speaker = "unk"
# まだ見ぬロロットさんに似ている、と言われることがルリエルはとても嬉しかったらしく、張り切ってお茶の用意を始めて──
line = "まだ見ぬロロットさんに似ている、と言われることがルリエルはとても嬉しかったらしく、張り切ってお茶の用意を始めて──"

[[dialogue]]
speaker = "ルリエル"
# 「あっ。あちちっ……お湯がはねてっ……！」
line = "「あっ。あちちっ……お湯がはねてっ……！」"

[[dialogue]]
speaker = "ルリエル"
# 「うぁ～！　二度あることは三度笠。また割っちゃったのです～っ……！」
line = "「うぁ～！　二度あることは三度笠。また割っちゃったのです～っ……！」"

[[dialogue]]
speaker = "unk"
# 結局トントロはその日だけで３度も天に召されたのだけど、クルセイダースのお２人は懐かしいものを見るような目でくすくす笑うばかり。
line = "結局トントロはその日だけで３度も天に召されたのだけど、クルセイダースのお２人は懐かしいものを見るような目でくすくす笑うばかり。"

[[dialogue]]
speaker = "unk"
# ロロット・ローゼンクロイツさんって、面白いけどドジな人っていう認識でいいのかな……？
line = "ロロット・ローゼンクロイツさんって、面白いけどドジな人っていう認識でいいのかな……？"
