[[dialogue]]
speaker = "unk"
# 第４話,ウィステリアと一緒,P
line = "第４話,ウィステリアと一緒,P"

[[dialogue]]
speaker = "unk"
# 俺はウィステリアさんの新居探しの手伝いで、物件の下見に同行していた。
line = "俺はウィステリアさんの新居探しの手伝いで、物件の下見に同行していた。"

[[dialogue]]
speaker = "ウィステリア"
# 「新居探し、手伝ってくれてありがとう、会長くん。私じゃ気付かないところを指摘してくれて助かるわ」
line = "「新居探し、手伝ってくれてありがとう、会長くん。私じゃ気付かないところを指摘してくれて助かるわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「だけど、なかなかいい物件が見つからないわね……」
line = "「だけど、なかなかいい物件が見つからないわね……」"

[[dialogue]]
speaker = "ウィステリア"
# 「空きがあってもすぐ埋まったり、目星をつけてた物件で水漏れが見つかったり……」
line = "「空きがあってもすぐ埋まったり、目星をつけてた物件で水漏れが見つかったり……」"

[[dialogue]]
speaker = "ウィステリア"
# 「それどころか不動産屋さんにトラブルが起きて内見できなかったり……やっぱり呪われてるわ」
line = "「それどころか不動産屋さんにトラブルが起きて内見できなかったり……やっぱり呪われてるわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「このままだとリノさんが帰ってきても、居候をすることになりそう……迷惑かけたくないのに……」
line = "「このままだとリノさんが帰ってきても、居候をすることになりそう……迷惑かけたくないのに……」"

[[dialogue]]
speaker = "ウィステリア"
# 「俺としては、ウィステリアさんと長く一緒にいられて幸運……？」
line = "「俺としては、ウィステリアさんと長く一緒にいられて幸運……？」"

[[dialogue]]
speaker = "ウィステリア"
# 「もう、会長くんってば……そんなこと言われたら、嬉しくなっちゃうじゃない」
line = "「もう、会長くんってば……そんなこと言われたら、嬉しくなっちゃうじゃない」"

[[dialogue]]
speaker = "unk"
# このまま一緒に住みませんか？
line = "このまま一緒に住みませんか？"

[[dialogue]]
speaker = "ウィステリア"
# 「えええっ！？」
line = "「えええっ！？」"

[[dialogue]]
speaker = "ウィステリア"
# 「魅力的な申し出だけど、さすがにずっとお邪魔になるわけにはいかないし、学園にも一時的なことだって説明してるし……」
line = "「魅力的な申し出だけど、さすがにずっとお邪魔になるわけにはいかないし、学園にも一時的なことだって説明してるし……」"

[[dialogue]]
speaker = "ウィステリア"
# 「そりゃ、君とずっと一緒にいられるのは嬉しいし、至れり尽くせりなんだけど……」
line = "「そりゃ、君とずっと一緒にいられるのは嬉しいし、至れり尽くせりなんだけど……」"

[[dialogue]]
speaker = "ウィステリア"
# 「だいたい、私が彼女でいいの？　年上だし、運が悪いし……魔将になったせいでさらに不運になっちゃったし」
line = "「だいたい、私が彼女でいいの？　年上だし、運が悪いし……魔将になったせいでさらに不運になっちゃったし」"

[[dialogue]]
speaker = "unk"
# それでも俺はウィステリアさんが好きです
line = "それでも俺はウィステリアさんが好きです"

[[dialogue]]
speaker = "ウィステリア"
# 「ぁ……」
line = "「ぁ……」"

[[dialogue]]
speaker = "ウィステリア"
# 「……ふふ、会長くんには敵わないわね。ありがとう、私も君が好きよ」
line = "「……ふふ、会長くんには敵わないわね。ありがとう、私も君が好きよ」"

[[dialogue]]
speaker = "ウィステリア"
# 「でもこのまま一緒に住むのはやめておくわ。２人で住むなら──」
line = "「でもこのまま一緒に住むのはやめておくわ。２人で住むなら──」"

[[dialogue]]
speaker = "エスメラルダ"
# 「あら、ウィステリアじゃない」
line = "「あら、ウィステリアじゃない」"

[[dialogue]]
speaker = "ウィステリア"
# 「あ、エスメラルダ先輩。こんなところで奇遇──」
line = "「あ、エスメラルダ先輩。こんなところで奇遇──」"

[[dialogue]]
speaker = "キリカ"
# 「……ウィステリア」
line = "「……ウィステリア」"

[[dialogue]]
speaker = "ウィステリア"
# 「げ、キリカ」
line = "「げ、キリカ」"

[[dialogue]]
speaker = "キリカ"
# 「露骨に嫌な顔をしないでください。私はあなたに何もしていません」
line = "「露骨に嫌な顔をしないでください。私はあなたに何もしていません」"

[[dialogue]]
speaker = "ウィステリア"
# 「そういうあなたこそ嫌そうな顔してるでしょうが。私だって何もしてないわよ」
line = "「そういうあなたこそ嫌そうな顔してるでしょうが。私だって何もしてないわよ」"

[[dialogue]]
speaker = "エスメラルダ"
# 「２人は相変わらず仲良しね～」
line = "「２人は相変わらず仲良しね～」"

[[dialogue]]
speaker = "ウィステリア"
# 「仲良くないですってば！　どうしてエスメラルダ先輩とキリカが一緒にいるんですか？」
line = "「仲良くないですってば！　どうしてエスメラルダ先輩とキリカが一緒にいるんですか？」"

[[dialogue]]
speaker = "エスメラルダ"
# 「買い出しに出てて、今そこで会ったのよ。本当に偶然ね～」
line = "「買い出しに出てて、今そこで会ったのよ。本当に偶然ね～」"

[[dialogue]]
speaker = "キリカ"
# 「そういうウィステリアこそ、緋宮会長と何をしていたのです？」
line = "「そういうウィステリアこそ、緋宮会長と何をしていたのです？」"

[[dialogue]]
speaker = "ウィステリア"
# 「えっ！？　それは……その……キリカには関係ないでしょ」
line = "「えっ！？　それは……その……キリカには関係ないでしょ」"

[[dialogue]]
speaker = "ウィステリア"
# （今一緒に住んでるとは言えないし……）
line = "（今一緒に住んでるとは言えないし……）"

[[dialogue]]
speaker = "エスメラルダ"
# 「リノさんから聞いてるわ。ウィステリアのマンションが住めなくなって、今は会長さんのおうちにお世話になってるのよね」
line = "「リノさんから聞いてるわ。ウィステリアのマンションが住めなくなって、今は会長さんのおうちにお世話になってるのよね」"

[[dialogue]]
speaker = "ウィステリア"
# 「言っちゃった！？」
line = "「言っちゃった！？」"

[[dialogue]]
speaker = "キリカ"
# 「つまり一緒に住んでいると……？　ウィステリア。非常時とはいえ、異性の生徒のところに上がり込むのは不健全ではないですか？」
line = "「つまり一緒に住んでいると……？　ウィステリア。非常時とはいえ、異性の生徒のところに上がり込むのは不健全ではないですか？」"

[[dialogue]]
speaker = "ウィステリア"
# 「花嫁騒動やってたあなたには言われたくないわよ！」
line = "「花嫁騒動やってたあなたには言われたくないわよ！」"

[[dialogue]]
speaker = "キリカ"
# 「んな……っ！？　それとこれとは関係ないでしょう」
line = "「んな……っ！？　それとこれとは関係ないでしょう」"

[[dialogue]]
speaker = "キリカ"
# 「緋宮会長。ウィステリアが無理やりお邪魔して、迷惑をおかけしていませんか？」
line = "「緋宮会長。ウィステリアが無理やりお邪魔して、迷惑をおかけしていませんか？」"

[[dialogue]]
speaker = "unk"
# ウィステリアさんは俺の大事な人ですから
line = "ウィステリアさんは俺の大事な人ですから"

[[dialogue]]
speaker = "ウィステリア"
# 「会長くん……」
line = "「会長くん……」"

[[dialogue]]
speaker = "キリカ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "キリカ"
# 「そうですか。それは差し出がましいことを申し上げました。申し訳ありません」
line = "「そうですか。それは差し出がましいことを申し上げました。申し訳ありません」"

[[dialogue]]
speaker = "エスメラルダ"
# 「ふふふ。ウィステリアと会長さんも本当に仲良しね♪」
line = "「ふふふ。ウィステリアと会長さんも本当に仲良しね♪」"

[[dialogue]]
speaker = "キリカ"
# 「ウィステリア。特別な関係だからと調子に乗って羽目を外さないように。節度を持った行動を心がけなさい」
line = "「ウィステリア。特別な関係だからと調子に乗って羽目を外さないように。節度を持った行動を心がけなさい」"

[[dialogue]]
speaker = "ウィステリア"
# 「わかってるわ！　あなたに言われるまでもないわよ！」
line = "「わかってるわ！　あなたに言われるまでもないわよ！」"

[[dialogue]]
speaker = "エスメラルダ"
# 「そうそう。さっきの話で思い出したんだけど──」
line = "「そうそう。さっきの話で思い出したんだけど──」"

[[dialogue]]
speaker = "エスメラルダ"
# 「キリカのウェディングフォームも、ウィステリアの魔将フォームも、まだデータを取ってなかったわよね。ぜひデータを取らせて♪」
line = "「キリカのウェディングフォームも、ウィステリアの魔将フォームも、まだデータを取ってなかったわよね。ぜひデータを取らせて♪」"

[[dialogue]]
speaker = "キリカ"
# 「私は買い出しがありますので失礼します」
line = "「私は買い出しがありますので失礼します」"

[[dialogue]]
speaker = "ウィステリア"
# 「あ、逃げた！　私たちも行きましょ、会長くんっ！」
line = "「あ、逃げた！　私たちも行きましょ、会長くんっ！」"

[[dialogue]]
speaker = "エスメラルダ"
# 「あ、ちょっと～」
line = "「あ、ちょっと～」"

[[dialogue]]
speaker = "ウィステリア"
# 「ふぅ、なんとか逃げられたわね……。探求心に火がついたエスメラルダ先輩は怖いのよ……」
line = "「ふぅ、なんとか逃げられたわね……。探求心に火がついたエスメラルダ先輩は怖いのよ……」"

[[dialogue]]
speaker = "ウィステリア"
# 「それにしてもキリカってば、あんな言い方しなくてもいいじゃない。相変わらずうるさいわね」
line = "「それにしてもキリカってば、あんな言い方しなくてもいいじゃない。相変わらずうるさいわね」"

[[dialogue]]
speaker = "unk"
# キリカ師匠なりに認めてくれたのかと
line = "キリカ師匠なりに認めてくれたのかと"

[[dialogue]]
speaker = "ウィステリア"
# 「そうだとしても、素直じゃないったらありゃしないわ」
line = "「そうだとしても、素直じゃないったらありゃしないわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「まぁ、キリカらしいけど」
line = "「まぁ、キリカらしいけど」"

[[dialogue]]
speaker = "ウィステリア"
# 「でも嬉しかったわ。私のこと、大事な人って言ってくれて」
line = "「でも嬉しかったわ。私のこと、大事な人って言ってくれて」"

[[dialogue]]
speaker = "ウィステリア"
# 「さっき言いかけたけど、もし２人で暮らすなら、２人で場所を決めて、２人でそこに住みたいわ」
line = "「さっき言いかけたけど、もし２人で暮らすなら、２人で場所を決めて、２人でそこに住みたいわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「どこに住むとしても、その方が素敵に暮らせそうじゃない？」
line = "「どこに住むとしても、その方が素敵に暮らせそうじゃない？」"

[[dialogue]]
speaker = "unk"
# 俺もその方がいいです！
line = "俺もその方がいいです！"

[[dialogue]]
speaker = "ウィステリア"
# 「ふふっ、それじゃ将来暮らす場所を考えながら、物件を探しましょうか」
line = "「ふふっ、それじゃ将来暮らす場所を考えながら、物件を探しましょうか」"

[[dialogue]]
speaker = "ウィステリア"
# 「せっかく会長くんと一緒にいられるんだから、時間をかけていろいろ巡ってみたいわ」
line = "「せっかく会長くんと一緒にいられるんだから、時間をかけていろいろ巡ってみたいわ」"

[[dialogue]]
speaker = "unk"
# しかし翌日──
line = "しかし翌日──"

[[dialogue]]
speaker = "ウィステリア"
# 「え、ここ空いてるの！？　今すぐ決めないと埋まっちゃう？　決めます！　ここに入居します！」
line = "「え、ここ空いてるの！？　今すぐ決めないと埋まっちゃう？　決めます！　ここに入居します！」"

[[dialogue]]
speaker = "unk"
# ちょうどいい物件がすぐに見つかり、ウィステリアさんとの同居生活はあっさり終わりを告げた。
line = "ちょうどいい物件がすぐに見つかり、ウィステリアさんとの同居生活はあっさり終わりを告げた。"

[[dialogue]]
speaker = "ウィステリア"
# 「もっと会長くんと一緒にいられると思ったのに……やっぱり私って運がないわ～～っ！！」
line = "「もっと会長くんと一緒にいられると思ったのに……やっぱり私って運がないわ～～っ！！」"
