[[dialogue]]
speaker = "unk"
# 第４話,親友と恋人,P
line = "第４話,親友と恋人,P"

[[dialogue]]
speaker = "unk"
# ある日の放課後――俺が星徒会の仕事を終えて帰り支度をしていたところで、ヒトリが何やら神妙な顔つきで訪ねてきた。
line = "ある日の放課後――俺が星徒会の仕事を終えて帰り支度をしていたところで、ヒトリが何やら神妙な顔つきで訪ねてきた。"

[[dialogue]]
speaker = "ヒトリ"
# 「あ、あの……会長さん。今日は大事なお話がありまして……」
line = "「あ、あの……会長さん。今日は大事なお話がありまして……」"

[[dialogue]]
speaker = "unk"
# ヒトリ、何かあったのか？
line = "ヒトリ、何かあったのか？"

[[dialogue]]
speaker = "ヒトリ"
# 「その……今日はわたしが、というよりも…」
line = "「その……今日はわたしが、というよりも…」"

[[dialogue]]
speaker = "ヒトリ"
# 「ゆーちゃんが、会長さんと話したいと言っていて……」
line = "「ゆーちゃんが、会長さんと話したいと言っていて……」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「ゆー……」
line = "「ゆー……」"

[[dialogue]]
speaker = "unk"
# ヒトリの友達である、ゆーちゃん。俺はその姿を、たまにしか見ることができない。
line = "ヒトリの友達である、ゆーちゃん。俺はその姿を、たまにしか見ることができない。"

[[dialogue]]
speaker = "unk"
# 基本的には、時々気配を感じたり、声が聞こえたり聞こえなかったりするぐらい。今日は、小さいながらも声を聴きとることができる。
line = "基本的には、時々気配を感じたり、声が聞こえたり聞こえなかったりするぐらい。今日は、小さいながらも声を聴きとることができる。"

[[dialogue]]
speaker = "ヒトリ"
# 「実はゆーちゃん……最近、成仏を考え始めているらしくて……」
line = "「実はゆーちゃん……最近、成仏を考え始めているらしくて……」"

[[dialogue]]
speaker = "unk"
# えっ！？　そんな、どうして……
line = "えっ！？　そんな、どうして……"

[[dialogue]]
speaker = "ヒトリ"
# 「わたしと会長さんがお付き合いをするようになってからも、ゆーちゃんはいつもそばで、わたしたちのことを見守ってくれていました……」
line = "「わたしと会長さんがお付き合いをするようになってからも、ゆーちゃんはいつもそばで、わたしたちのことを見守ってくれていました……」"

[[dialogue]]
speaker = "ヒトリ"
# 「その……デートしている時や……キスとか、している時も……」
line = "「その……デートしている時や……キスとか、している時も……」"

[[dialogue]]
speaker = "ヒトリ"
# 「わたしは昔から、幽霊に<b>憑かれる</b>とはそういうものだとわかっているので……全然、気にしていなかったんですけど……」
line = "「わたしは昔から、幽霊に<b>憑かれる</b>とはそういうものだとわかっているので……全然、気にしていなかったんですけど……」"

[[dialogue]]
speaker = "ヒトリ"
# 「でも、ゆーちゃんの方が気にしていたみたいです」
line = "「でも、ゆーちゃんの方が気にしていたみたいです」"

[[dialogue]]
speaker = "ヒトリ"
# 「わたしや会長さんが、いつも見られて気恥ずかしい思いをしているんじゃないか、って……」
line = "「わたしや会長さんが、いつも見られて気恥ずかしい思いをしているんじゃないか、って……」"

[[dialogue]]
speaker = "ヒトリ"
# 「それで、『わたしのことは会長さんに任せられるから、自分はそろそろ成仏してもいいんじゃないか』って言いだしてて……」
line = "「それで、『わたしのことは会長さんに任せられるから、自分はそろそろ成仏してもいいんじゃないか』って言いだしてて……」"

[[dialogue]]
speaker = "unk"
# ……ヒトリは納得してるのか？
line = "……ヒトリは納得してるのか？"

[[dialogue]]
speaker = "ヒトリ"
# 「……いいえ。わたしは、ゆーちゃんとまだ、一緒に居たいです」
line = "「……いいえ。わたしは、ゆーちゃんとまだ、一緒に居たいです」"

[[dialogue]]
speaker = "ヒトリ"
# 「わたしにとって……ゆーちゃんは大切な、友達だから」
line = "「わたしにとって……ゆーちゃんは大切な、友達だから」"

[[dialogue]]
speaker = "ヒトリ"
# 「でも、だからこそちゃんと、会長さんに聞いておかなくちゃって、思ったんです……」
line = "「でも、だからこそちゃんと、会長さんに聞いておかなくちゃって、思ったんです……」"

[[dialogue]]
speaker = "ヒトリ"
# 「会長さんがゆーちゃんの存在を、どう思っているのかについては……実はずっと、気になっていました……」
line = "「会長さんがゆーちゃんの存在を、どう思っているのかについては……実はずっと、気になっていました……」"

[[dialogue]]
speaker = "ヒトリ"
# 「会長さんも、すべては見えなくても気配や声を感じることがあるって、言っていましたよね……？」
line = "「会長さんも、すべては見えなくても気配や声を感じることがあるって、言っていましたよね……？」"

[[dialogue]]
speaker = "ヒトリ"
# 「わたしには、霊感があります。それに、わたしを救ってくれたみんな――幽霊たちの居場所を作りたいって想いもあります」
line = "「わたしには、霊感があります。それに、わたしを救ってくれたみんな――幽霊たちの居場所を作りたいって想いもあります」"

[[dialogue]]
speaker = "ヒトリ"
# 「なので、不知火ヒトリは……これからも、死ぬまでずっと、幽霊と一緒の人生です」
line = "「なので、不知火ヒトリは……これからも、死ぬまでずっと、幽霊と一緒の人生です」"

[[dialogue]]
speaker = "ヒトリ"
# 「だからこそ……会長さんにちゃんと聞いておかなきゃいけないことが、あります……」
line = "「だからこそ……会長さんにちゃんと聞いておかなきゃいけないことが、あります……」"

[[dialogue]]
speaker = "ヒトリ"
# 「会長さんは、わたしにだけ見えて、自分には見えない幽霊という存在が、嫌だったり、怖かったりは、しませんか……？」
line = "「会長さんは、わたしにだけ見えて、自分には見えない幽霊という存在が、嫌だったり、怖かったりは、しませんか……？」"

[[dialogue]]
speaker = "ヒトリ"
# 「もし本当は嫌なのなら……わたしは……会長さんとは……」
line = "「もし本当は嫌なのなら……わたしは……会長さんとは……」"

[[dialogue]]
speaker = "unk"
# だけど幽霊を含めてヒトリだと思ってる
line = "だけど幽霊を含めてヒトリだと思ってる"

[[dialogue]]
speaker = "unk"
# 幽霊のことは俺にはよくわからない。
line = "幽霊のことは俺にはよくわからない。"

[[dialogue]]
speaker = "unk"
# ──彼女自身が言う通り、ヒトリという人間と幽霊の存在は不可分だ。
line = "──彼女自身が言う通り、ヒトリという人間と幽霊の存在は不可分だ。"

[[dialogue]]
speaker = "unk"
# そして俺は、『成仏を望まない幽霊の居場所を作りたい』と言ったヒトリを尊敬している。その夢を叶えて欲しいと思っている。
line = "そして俺は、『成仏を望まない幽霊の居場所を作りたい』と言ったヒトリを尊敬している。その夢を叶えて欲しいと思っている。"

[[dialogue]]
speaker = "unk"
# だから、ゆーちゃんが成仏しようと思っている理由が、俺たちを気遣ってのことなら、成仏なんてしなくていい。
line = "だから、ゆーちゃんが成仏しようと思っている理由が、俺たちを気遣ってのことなら、成仏なんてしなくていい。"

[[dialogue]]
speaker = "unk"
# だって、俺はゆーちゃんの存在もひっくるめて、ヒトリという女の子のことを好きになったのだから。
line = "だって、俺はゆーちゃんの存在もひっくるめて、ヒトリという女の子のことを好きになったのだから。"

[[dialogue]]
speaker = "ゆーちゃん"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "unk"
# 俺が自分の想いを伝えると――
line = "俺が自分の想いを伝えると――"

[[dialogue]]
speaker = "ヒトリ"
# 「会長さん……ありがとうございます」
line = "「会長さん……ありがとうございます」"

[[dialogue]]
speaker = "ヒトリ"
# 「わたし……ゆーちゃんのことも、会長さんのことも、どっちも大切だから……怖くて、なかなか言い出せなかったんです……」
line = "「わたし……ゆーちゃんのことも、会長さんのことも、どっちも大切だから……怖くて、なかなか言い出せなかったんです……」"

[[dialogue]]
speaker = "ヒトリ"
# 「普通の人は、見えない存在である幽霊が怖いって、わかっていたから……」
line = "「普通の人は、見えない存在である幽霊が怖いって、わかっていたから……」"

[[dialogue]]
speaker = "ヒトリ"
# 「でも、会長さんがそう言ってくれるなら……勇気を出して、自分の気持ちを伝えられます」
line = "「でも、会長さんがそう言ってくれるなら……勇気を出して、自分の気持ちを伝えられます」"

[[dialogue]]
speaker = "unk"
# そう言うと、ヒトリは向き直った。俺には見えないけど、小さく気配を感じる、彼女の親友の方へと。
line = "そう言うと、ヒトリは向き直った。俺には見えないけど、小さく気配を感じる、彼女の親友の方へと。"

[[dialogue]]
speaker = "ヒトリ"
# 「ねぇ、ゆーちゃん？」
line = "「ねぇ、ゆーちゃん？」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「ゆー……？」
line = "「ゆー……？」"

[[dialogue]]
speaker = "ヒトリ"
# 「わたしね……ゆーちゃんには成仏して欲しくない。これからもずっと、そばにいて欲しいって思ってる」
line = "「わたしね……ゆーちゃんには成仏して欲しくない。これからもずっと、そばにいて欲しいって思ってる」"

[[dialogue]]
speaker = "ヒトリ"
# 「ゆーちゃんはわたしとずっと一緒に居てくれた、大切な――『親友』だから」
line = "「ゆーちゃんはわたしとずっと一緒に居てくれた、大切な――『親友』だから」"

[[dialogue]]
speaker = "ヒトリ"
# 「一緒に居すぎるから、なんか気恥ずかしくて……ずっと言えなかったけど――」
line = "「一緒に居すぎるから、なんか気恥ずかしくて……ずっと言えなかったけど――」"

[[dialogue]]
speaker = "ヒトリ"
# 「大好きだよ、ゆーちゃん」
line = "「大好きだよ、ゆーちゃん」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「……！　ゆー♪」
line = "「……！　ゆー♪」"

[[dialogue]]
speaker = "ヒトリ"
# 「え？　わっ……！？　あっ……ふふふっ♪　ゆーちゃん、そんな抱き着いて来て――これからもずっと一緒に居てくれるの？」
line = "「え？　わっ……！？　あっ……ふふふっ♪　ゆーちゃん、そんな抱き着いて来て――これからもずっと一緒に居てくれるの？」"

[[dialogue]]
speaker = "ヒトリ"
# 「えへへ……ありがとう♪」
line = "「えへへ……ありがとう♪」"

[[dialogue]]
speaker = "unk"
# 見えないけど、『てぇてぇ』だな
line = "見えないけど、『てぇてぇ』だな"

[[dialogue]]
speaker = "unk"
# 嬉しそうなヒトリの様子に、俺も嬉しくなって頷いていると――
line = "嬉しそうなヒトリの様子に、俺も嬉しくなって頷いていると――"

[[dialogue]]
speaker = "ヒトリ"
# 「って、ゆーちゃん、会長さんの方に行って、どうしたの……？」
line = "「って、ゆーちゃん、会長さんの方に行って、どうしたの……？」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「ゆー<emoji=heart04>　――ちゅっ<emoji=heart04>」
line = "「ゆー<emoji=heart04>　――ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 不意に、俺の頬に柔らかな感覚があった。
line = "不意に、俺の頬に柔らかな感覚があった。"

[[dialogue]]
speaker = "ヒトリ"
# 「ちょっ、ゆーちゃん！？　会長さんに何してるの！？」
line = "「ちょっ、ゆーちゃん！？　会長さんに何してるの！？」"

[[dialogue]]
speaker = "unk"
# えっ？　俺、今なんかされた……？
line = "えっ？　俺、今なんかされた……？"

[[dialogue]]
speaker = "ヒトリ"
# 「ど、どうしてそんな……いきなり頬っぺたに、き、きき――キスなんてっ！！！」
line = "「ど、どうしてそんな……いきなり頬っぺたに、き、きき――キスなんてっ！！！」"

[[dialogue]]
speaker = "unk"
# えぇっ！？
line = "えぇっ！？"

[[dialogue]]
speaker = "ゆーちゃん"
# 「ゆ～～<emoji=heart04>」
line = "「ゆ～～<emoji=heart04>」"

[[dialogue]]
speaker = "ヒトリ"
# 「――こ、これまで遠慮してたけど、これからもずっとわたしと一緒にいるってことは……実質、ゆーちゃんも会長さんと恋人！？」
line = "「――こ、これまで遠慮してたけど、これからもずっとわたしと一緒にいるってことは……実質、ゆーちゃんも会長さんと恋人！？」"

[[dialogue]]
speaker = "ヒトリ"
# 「そ、それは……うぅ～～～！　――だ、ダメっ！」
line = "「そ、それは……うぅ～～～！　――だ、ダメっ！」"

[[dialogue]]
speaker = "ヒトリ"
# 「か、会長さんは――わたしの恋人なのっ！　たとえゆーちゃんでも、簡単には譲れないんだからぁ～～～っ！」
line = "「か、会長さんは――わたしの恋人なのっ！　たとえゆーちゃんでも、簡単には譲れないんだからぁ～～～っ！」"

[[dialogue]]
speaker = "unk"
# そんな今まで見たことのないような嫉妬心を見せる彼女が可愛くて、俺は思わず笑ってしまう。
line = "そんな今まで見たことのないような嫉妬心を見せる彼女が可愛くて、俺は思わず笑ってしまう。"

[[dialogue]]
speaker = "unk"
# ヒトリ、こっち向いて
line = "ヒトリ、こっち向いて"

[[dialogue]]
speaker = "ヒトリ"
# 「えっ？　は、はい……！」
line = "「えっ？　は、はい……！」"

[[dialogue]]
speaker = "unk"
# 俺は彼女を振り向かせると――
line = "俺は彼女を振り向かせると――"

[[dialogue]]
speaker = "ヒトリ"
# 「って、会長さん……！？　あっ……！　んんっ<emoji=heart04>」
line = "「って、会長さん……！？　あっ……！　んんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヒトリ"
# 「ちゅっ<emoji=heart04>　んんぅ……か、会長さん……<emoji=heart04>」
line = "「ちゅっ<emoji=heart04>　んんぅ……か、会長さん……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ヒトリ。ゆーちゃんに負けないくらい愛してる
line = "ヒトリ。ゆーちゃんに負けないくらい愛してる"

[[dialogue]]
speaker = "ヒトリ"
# 「……！　わ、わたしも……」
line = "「……！　わ、わたしも……」"

[[dialogue]]
speaker = "ヒトリ"
# 「ゆーちゃんに負けないくらい、会長さんのこと、愛してます……<emoji=heart04>」
line = "「ゆーちゃんに負けないくらい、会長さんのこと、愛してます……<emoji=heart04>」"

[[dialogue]]
speaker = "ヒトリ"
# 「ちゅっ……<emoji=heart04>」
line = "「ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「てーてー♪」
line = "「てーてー♪」"

[[dialogue]]
speaker = "unk"
# いつもよりも嬉しそうな、ゆーちゃんの声がそばから聞こえたのだった。
line = "いつもよりも嬉しそうな、ゆーちゃんの声がそばから聞こえたのだった。"
