[[dialogue]]
speaker = "ユーリス"
# 「んっ……はぁ……ふぁ……んっ……」
line = "「んっ……はぁ……ふぁ……んっ……」"

[[dialogue]]
speaker = "ユーリス"
# 「も、もう……。どうして閉店後の店内で、はぁ、んっ、こんなこと……」
line = "「も、もう……。どうして閉店後の店内で、はぁ、んっ、こんなこと……」"

[[dialogue]]
speaker = "ユーリス"
# 「後でバレたら、んんっ……。大目玉どころの騒ぎじゃないんだからね……？」
line = "「後でバレたら、んんっ……。大目玉どころの騒ぎじゃないんだからね……？」"

[[dialogue]]
speaker = "unk"
# 不服そうに唇を尖らせたまま、ユーリスが大きな乳房で肉棒を<ruby=しご>扱</ruby>いてくれる。
line = "不服そうに唇を尖らせたまま、ユーリスが大きな乳房で肉棒を<ruby>扱<rt>しご</rt></ruby>いてくれる。"

[[dialogue]]
speaker = "unk"
# だけど元はと言えばユーリスのせいだ。
line = "だけど元はと言えばユーリスのせいだ。"

[[dialogue]]
speaker = "unk"
# 閉店作業中にいきなり胸元を緩めたりするものだから。
line = "閉店作業中にいきなり胸元を緩めたりするものだから。"

[[dialogue]]
speaker = "ユーリス"
# 「だってこの服、学園の制服やいつもの戦闘服に比べて胸が苦しいんだもん……」
line = "「だってこの服、学園の制服やいつもの戦闘服に比べて胸が苦しいんだもん……」"

[[dialogue]]
speaker = "ユーリス"
# 「薄手な分、いつも以上に胸を潰さなくちゃいけないし……。２人きりの時くらい、楽になりたいと思って……」
line = "「薄手な分、いつも以上に胸を潰さなくちゃいけないし……。２人きりの時くらい、楽になりたいと思って……」"

[[dialogue]]
speaker = "ユーリス"
# 「そしたら会長、胸の谷間をやらしく覗き込んでくるし……。お、おち○ちんまで大きくして……」
line = "「そしたら会長、胸の谷間をやらしく覗き込んでくるし……。お、おち○ちんまで大きくして……」"

[[dialogue]]
speaker = "ユーリス"
# 「あまつさえ、私を店の隅に引っ張っていって……こんなこと頼んできて……」
line = "「あまつさえ、私を店の隅に引っ張っていって……こんなこと頼んできて……」"

[[dialogue]]
speaker = "unk"
# 「パイズリして欲しい」とお願いした時の、彼女の姿を思い出す。
line = "「パイズリして欲しい」とお願いした時の、彼女の姿を思い出す。"

[[dialogue]]
speaker = "unk"
# 耳まで顔を真っ赤にして一通り慌てたあと、結局はボタンをプツプツと外して俺の前にしゃがみ込んでくれた。
line = "耳まで顔を真っ赤にして一通り慌てたあと、結局はボタンをプツプツと外して俺の前にしゃがみ込んでくれた。"

[[dialogue]]
speaker = "unk"
# 目の前に広がる乳房の海が美しい。俺のペニスを潜り込ませてあまりある豊満な大海に魅入ってしまう。
line = "目の前に広がる乳房の海が美しい。俺のペニスを潜り込ませてあまりある豊満な大海に魅入ってしまう。"

[[dialogue]]
speaker = "ユーリス"
# 「あまり見つめないでくれよ……。胸を見られるのが一番恥ずかしいんだ……」
line = "「あまり見つめないでくれよ……。胸を見られるのが一番恥ずかしいんだ……」"

[[dialogue]]
speaker = "ユーリス"
# 「男の振りをしているのに全然男らしく見えないし……。毎朝この胸を潰す度に自分は女だと意識させられてしまうし……」
line = "「男の振りをしているのに全然男らしく見えないし……。毎朝この胸を潰す度に自分は女だと意識させられてしまうし……」"

[[dialogue]]
speaker = "ユーリス"
# 「こんな無駄な贅肉、ちっとも要らなかったのに……。頼んでもいないのに、こんなに大きくなってしまって……」
line = "「こんな無駄な贅肉、ちっとも要らなかったのに……。頼んでもいないのに、こんなに大きくなってしまって……」"

[[dialogue]]
speaker = "ユーリス"
# 「……とはいっても……」
line = "「……とはいっても……」"

[[dialogue]]
speaker = "unk"
# 不意に尖っていたユーリスの唇が綻ぶ。
line = "不意に尖っていたユーリスの唇が綻ぶ。"

[[dialogue]]
speaker = "ユーリス"
# 「好きな人に興奮してもらえるのは、ん、はぁ……嬉しいけど、ね……<emoji=heart04>」
line = "「好きな人に興奮してもらえるのは、ん、はぁ……嬉しいけど、ね……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「おっぱいでおち○ちんを扱くなんて、ふぁ、ん、死んでしまいそうなくらい恥ずかしいけど……<emoji=heart04>」
line = "「おっぱいでおち○ちんを扱くなんて、ふぁ、ん、死んでしまいそうなくらい恥ずかしいけど……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「でも、はぁ、んぁ、君が私のおっぱいで悦んでくれてる姿を見ると、羞恥心よりも悦ばせたい気持ちが強くなってしまう……<emoji=heart04>」
line = "「でも、はぁ、んぁ、君が私のおっぱいで悦んでくれてる姿を見ると、羞恥心よりも悦ばせたい気持ちが強くなってしまう……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 上目遣いで見つめながら、ユーリスが色気たっぷりに乳房を動かしてくれる。
line = "上目遣いで見つめながら、ユーリスが色気たっぷりに乳房を動かしてくれる。"

[[dialogue]]
speaker = "unk"
# 一日中キツく潰して蒸れてしまっているんだろう。谷間の中は蜜のように甘く温かい汗で濡れていた。
line = "一日中キツく潰して蒸れてしまっているんだろう。谷間の中は蜜のように甘く温かい汗で濡れていた。"

[[dialogue]]
speaker = "unk"
# 乳房を揺らしてもらう度にその蜜が肉棒にトロトロに絡みついてきて気持ちいい。豊満なおっぱいがより肉竿に密着してくる。
line = "乳房を揺らしてもらう度にその蜜が肉棒にトロトロに絡みついてきて気持ちいい。豊満なおっぱいがより肉竿に密着してくる。"

[[dialogue]]
speaker = "ユーリス"
# 「はぁ、んはぁ、おち○ちん気持ち良さそうに震えてくれて……<emoji=heart04>　やっぱり嬉しい……<emoji=heart04>」
line = "「はぁ、んはぁ、おち○ちん気持ち良さそうに震えてくれて……<emoji=heart04>　やっぱり嬉しい……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「君と出会うまで、んっ、はぁ、おっぱいなんて本当に邪魔なものでしかないと思っていたんだ……<emoji=heart04>」
line = "「君と出会うまで、んっ、はぁ、おっぱいなんて本当に邪魔なものでしかないと思っていたんだ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「重いし、潰してるとすぐ蒸れるし、何より、はぁ、んん、女の象徴みたいなものだから……<emoji=heart04>」
line = "「重いし、潰してるとすぐ蒸れるし、何より、はぁ、んん、女の象徴みたいなものだから……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「いくら大きくなったところで誰にも見せられないのにって……<emoji=heart04>　本当の私を見てもらえる日なんて来ないのにって……<emoji=heart04>」
line = "「いくら大きくなったところで誰にも見せられないのにって……<emoji=heart04>　本当の私を見てもらえる日なんて来ないのにって……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「だけど、んっ、はぁ、だから……<emoji=heart04>　私の大きなおっぱいを、君に見てもらえることが嬉しい……<emoji=heart04>」
line = "「だけど、んっ、はぁ、だから……<emoji=heart04>　私の大きなおっぱいを、君に見てもらえることが嬉しい……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「本当の私で興奮してもらえることが嬉しい……<emoji=heart04>　あんなに嫌いだったおっぱいで悦んでくれることが嬉しい……<emoji=heart04>」
line = "「本当の私で興奮してもらえることが嬉しい……<emoji=heart04>　あんなに嫌いだったおっぱいで悦んでくれることが嬉しい……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺の興奮を確かめるようにユーリスがぎゅうぎゅうと乳圧を強めてくれる。
line = "俺の興奮を確かめるようにユーリスがぎゅうぎゅうと乳圧を強めてくれる。"

[[dialogue]]
speaker = "unk"
# 羞恥心で頬を赤らめながらも、谷間の奥の奥まで肉棒を挟み込んで、そのグラマラスな感触を味わわせてくれる。
line = "羞恥心で頬を赤らめながらも、谷間の奥の奥まで肉棒を挟み込んで、そのグラマラスな感触を味わわせてくれる。"

[[dialogue]]
speaker = "ユーリス"
# 「私のおっぱいで気持ち良くなって……<emoji=heart04>　たくさんたくさん……<emoji=heart04>」
line = "「私のおっぱいで気持ち良くなって……<emoji=heart04>　たくさんたくさん……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「私のおっぱいは、まさに君だけのために存在してるから……<emoji=heart04>」
line = "「私のおっぱいは、まさに君だけのために存在してるから……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「君だけにしか見せない……<emoji=heart04>　君だけしか知らない……<emoji=heart04>　私自身のためですらない……<emoji=heart04>　君に悦んでもらうためだけのものだから……<emoji=heart04>」
line = "「君だけにしか見せない……<emoji=heart04>　君だけしか知らない……<emoji=heart04>　私自身のためですらない……<emoji=heart04>　君に悦んでもらうためだけのものだから……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# こんなに可愛い女の子の存在を俺だけが知っているという事実に改めて幸せを感じる。
line = "こんなに可愛い女の子の存在を俺だけが知っているという事実に改めて幸せを感じる。"

[[dialogue]]
speaker = "unk"
# そんな彼女から、こんなにも愛されていることに快感以上に幸福を覚える。
line = "そんな彼女から、こんなにも愛されていることに快感以上に幸福を覚える。"

[[dialogue]]
speaker = "ユーリス"
# 「あぁ、おち○ちんからエッチなおつゆが溢れて……<emoji=heart04>　この匂い好き……<emoji=heart04>　大好きな人が気持ち良くなってくれてる匂い……<emoji=heart04>」
line = "「あぁ、おち○ちんからエッチなおつゆが溢れて……<emoji=heart04>　この匂い好き……<emoji=heart04>　大好きな人が気持ち良くなってくれてる匂い……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「もっと、んふっ……<emoji=heart04>　ぎゅっとしてみるね……<emoji=heart04>　私のおっぱいの感触、ふぁ、堪能して欲しい……<emoji=heart04>」
line = "「もっと、んふっ……<emoji=heart04>　ぎゅっとしてみるね……<emoji=heart04>　私のおっぱいの感触、ふぁ、堪能して欲しい……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「私も君のおち○ちんの感触、たっぷり味わいたいんだ……<emoji=heart04>　私の女の部分で、んっ、はぁ、おっぱいで……<emoji=heart04>」
line = "「私も君のおち○ちんの感触、たっぷり味わいたいんだ……<emoji=heart04>　私の女の部分で、んっ、はぁ、おっぱいで……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 溢れ出した我慢汁をユーリスが胸全体に塗り込んでいく。にゅるんにゅるんと擦れる柔肌が気持ちいい。
line = "溢れ出した我慢汁をユーリスが胸全体に塗り込んでいく。にゅるんにゅるんと擦れる柔肌が気持ちいい。"

[[dialogue]]
speaker = "unk"
# まるで乳房の海を両手を広げて泳ぎ回っているような気分だ。フワとろなおっぱいの感触にペニスが蕩けていく。
line = "まるで乳房の海を両手を広げて泳ぎ回っているような気分だ。フワとろなおっぱいの感触にペニスが蕩けていく。"

[[dialogue]]
speaker = "ユーリス"
# 「ふぁぁ……<emoji=heart04>　おっぱいの中でおち○ちんが跳ね回ってくれて……<emoji=heart04>」
line = "「ふぁぁ……<emoji=heart04>　おっぱいの中でおち○ちんが跳ね回ってくれて……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「私まで感じてしまう……<emoji=heart04>　ううん、私の方が、はぁ、あぁん、感じてしまってるかもしれない……<emoji=heart04>」
line = "「私まで感じてしまう……<emoji=heart04>　ううん、私の方が、はぁ、あぁん、感じてしまってるかもしれない……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「おっぱいもエッチな汗でビショビショだけど、おま○こもグチョグチョに濡れてしまっているんだ……<emoji=heart04>」
line = "「おっぱいもエッチな汗でビショビショだけど、おま○こもグチョグチョに濡れてしまっているんだ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「おっぱいでおち○ちん扱いてるだけなのに、あぁん、はぁ……<emoji=heart04> ものすごく気持ち良くて、ふぁぁ、幸せで……<emoji=heart04>」
line = "「おっぱいでおち○ちん扱いてるだけなのに、あぁん、はぁ……<emoji=heart04> ものすごく気持ち良くて、ふぁぁ、幸せで……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ずりんずりんと乳房を擦り付ける度にユーリスがお尻を震わせる。
line = "ずりんずりんと乳房を擦り付ける度にユーリスがお尻を震わせる。"

[[dialogue]]
speaker = "unk"
# どんどんお尻に食い込んでいくショーツがエロい。
line = "どんどんお尻に食い込んでいくショーツがエロい。"

[[dialogue]]
speaker = "unk"
# クネクネと悶える度に、ただでさえセクシーなショーツがＴバックに変わっていく。
line = "クネクネと悶える度に、ただでさえセクシーなショーツがＴバックに変わっていく。"

[[dialogue]]
speaker = "ユーリス"
# 「えへへ……<emoji=heart04>　ショーツも、はぁ、んふぁ、気に入ってくれた……？」
line = "「えへへ……<emoji=heart04>　ショーツも、はぁ、んふぁ、気に入ってくれた……？」"

[[dialogue]]
speaker = "ユーリス"
# 「いいよ……？　好きなだけ見て……？　君に見せるために穿いてきたんだ……<emoji=heart04>」
line = "「いいよ……？　好きなだけ見て……？　君に見せるために穿いてきたんだ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「万が一こういうことになった時に興奮してもらえるようにって……<emoji=heart04>　君と会う時はいつも色っぽい下着付けるようにしてて……<emoji=heart04>」
line = "「万が一こういうことになった時に興奮してもらえるようにって……<emoji=heart04>　君と会う時はいつも色っぽい下着付けるようにしてて……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「エッチな気分になって欲しいから……<emoji=heart04>　私も、はぁ、ふぁ、できることならいつでも君とエッチしたいから……<emoji=heart04>」
line = "「エッチな気分になって欲しいから……<emoji=heart04>　私も、はぁ、ふぁ、できることならいつでも君とエッチしたいから……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# もっと発情してとばかりに、恥じらいながらもユーリスがお尻をフリフリと振ってくれる。
line = "もっと発情してとばかりに、恥じらいながらもユーリスがお尻をフリフリと振ってくれる。"

[[dialogue]]
speaker = "unk"
# その健気な姿がどうしようもなく可愛い。彼女の胸の中でペニスがはち切れそうなくらい腫れ上がってしまう。
line = "その健気な姿がどうしようもなく可愛い。彼女の胸の中でペニスがはち切れそうなくらい腫れ上がってしまう。"

[[dialogue]]
speaker = "ユーリス"
# 「あぁ、幸せ……<emoji=heart04>　おち○ちん、ガッチガチに硬くなって……<emoji=heart04>」
line = "「あぁ、幸せ……<emoji=heart04>　おち○ちん、ガッチガチに硬くなって……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「このままもっと気持ち良くしてあげるね……<emoji=heart04>　おち○ちんに溜め込んだ精液、ビュービューさせてあげたい……<emoji=heart04>」
line = "「このままもっと気持ち良くしてあげるね……<emoji=heart04>　おち○ちんに溜め込んだ精液、ビュービューさせてあげたい……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「私も今だけは、ふぁ、んふぅん……<emoji=heart04>　一匹のメスになりたいから……<emoji=heart04>」
line = "「私も今だけは、ふぁ、んふぅん……<emoji=heart04>　一匹のメスになりたいから……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 発情した吐息を漏らしながら、火照った乳房でペニスをぎゅっと抱き締めてくれる。
line = "発情した吐息を漏らしながら、火照った乳房でペニスをぎゅっと抱き締めてくれる。"

[[dialogue]]
speaker = "unk"
# そして、じゅぶじゃぶ水音が立つほど乳房の海を激しく波打たせてくれて──
line = "そして、じゅぶじゃぶ水音が立つほど乳房の海を激しく波打たせてくれて──"

[[dialogue]]
speaker = "ユーリス"
# 「ふぁんっ、あぁっ、あっ、はぁっ、あぁあんっ……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「ふぁんっ、あぁっ、あっ、はぁっ、あぁあんっ……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「おち○ちんゴシゴシ扱くの気持ちいいっ……<emoji=heart04>　おっぱいの中がおま○こみたいに敏感になっちゃってっ……<emoji=heart04>」
line = "「おち○ちんゴシゴシ扱くの気持ちいいっ……<emoji=heart04>　おっぱいの中がおま○こみたいに敏感になっちゃってっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「恥ずかしい声っ、あっ、あっ、あぁっ、出ちゃ……<emoji=heart04>　こんな女の子な声っ、ふぁ、あっ、はぁ、絶対出しちゃいけないのにっ……<emoji=heart04>」
line = "「恥ずかしい声っ、あっ、あっ、あぁっ、出ちゃ……<emoji=heart04>　こんな女の子な声っ、ふぁ、あっ、はぁ、絶対出しちゃいけないのにっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 口ではそう言いながらも、甘い嬌声が響く。
line = "口ではそう言いながらも、甘い嬌声が響く。"

[[dialogue]]
speaker = "unk"
# 恥じらいながらも女の自分を俺に見せつけてくれる。
line = "恥じらいながらも女の自分を俺に見せつけてくれる。"

[[dialogue]]
speaker = "ユーリス"
# 「先っぽをズリズリ擦られるのが気持ちいいんだよねっ……<emoji=heart04>　私のおっぱいでたっぷりシコシコしてあげるねっ……<emoji=heart04>」
line = "「先っぽをズリズリ擦られるのが気持ちいいんだよねっ……<emoji=heart04>　私のおっぱいでたっぷりシコシコしてあげるねっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「私のふわふわおっぱいの感触、あぁあんっ、いっぱい味わって欲しいっ……<emoji=heart04>　柔らかさは自信があるんだっ……<emoji=heart04>」
line = "「私のふわふわおっぱいの感触、あぁあんっ、いっぱい味わって欲しいっ……<emoji=heart04>　柔らかさは自信があるんだっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「自分でも大きくてふにふにのおっぱいだなって思っててっ……<emoji=heart04>　ぬるぬる咥え込むのだけは得意なんだっ……<emoji=heart04>」
line = "「自分でも大きくてふにふにのおっぱいだなって思っててっ……<emoji=heart04>　ぬるぬる咥え込むのだけは得意なんだっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 自分の胸の長所をアピールするように、ユーリスが極上の柔肌でペニスを頬張ってくれる。
line = "自分の胸の長所をアピールするように、ユーリスが極上の柔肌でペニスを頬張ってくれる。"

[[dialogue]]
speaker = "unk"
# おっぱいでフェラしてもらってるような気分だ。汗と我慢汁で蒸れ蒸れの乳穴で扱かれるのが最高に気持ちいい。
line = "おっぱいでフェラしてもらってるような気分だ。汗と我慢汁で蒸れ蒸れの乳穴で扱かれるのが最高に気持ちいい。"

[[dialogue]]
speaker = "ユーリス"
# 「もっと、んっ<emoji=heart04>　もっと激しく擦るねっ……<emoji=heart04>」
line = "「もっと、んっ<emoji=heart04>　もっと激しく擦るねっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「弾力ない分、はぁっ、あぁんっ、いっぱいぎゅってするっ……<emoji=heart04>　おっぱいキツキツに締めるっ……<emoji=heart04>」
line = "「弾力ない分、はぁっ、あぁんっ、いっぱいぎゅってするっ……<emoji=heart04>　おっぱいキツキツに締めるっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「出したくなったら出してくれていいからっ……<emoji=heart04>　ふぁっ、あっ、あぁんっ……<emoji=heart04>　好きなだけ気持ち良くなって……<emoji=heart04>」
line = "「出したくなったら出してくれていいからっ……<emoji=heart04>　ふぁっ、あっ、あぁんっ……<emoji=heart04>　好きなだけ気持ち良くなって……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# めいっぱい乳房を寄せ上げてペニスを扱いてくれるユーリス。
line = "めいっぱい乳房を寄せ上げてペニスを扱いてくれるユーリス。"

[[dialogue]]
speaker = "unk"
# そのあまりの激しさに、真白い肌が赤みがかっていくのがわかる。気持ちいいけど、このまま続けたら──
line = "そのあまりの激しさに、真白い肌が赤みがかっていくのがわかる。気持ちいいけど、このまま続けたら──"

[[dialogue]]
speaker = "ユーリス"
# 「いいんだっ……<emoji=heart04>　おち○ちんでおっぱい火傷しちゃってもっ……<emoji=heart04>」
line = "「いいんだっ……<emoji=heart04>　おち○ちんでおっぱい火傷しちゃってもっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「むしろ火傷したいっ……<emoji=heart04>　大好きな人のおち○ちんの痕、はぁっ、あぁっ、おっぱいに焼き付けたいっ……<emoji=heart04>」
line = "「むしろ火傷したいっ……<emoji=heart04>　大好きな人のおち○ちんの痕、はぁっ、あぁっ、おっぱいに焼き付けたいっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「そうすれば毎朝おっぱい潰す時も、えへへっ……<emoji=heart04>　幸せな気持ちになれるからっ……<emoji=heart04>」
line = "「そうすれば毎朝おっぱい潰す時も、えへへっ……<emoji=heart04>　幸せな気持ちになれるからっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「私のおっぱいで悦んでくれる人がいるんだってっ……<emoji=heart04>　私も大好きな人のためにおっぱい使えるんだってわかるからっ……<emoji=heart04>」
line = "「私のおっぱいで悦んでくれる人がいるんだってっ……<emoji=heart04>　私も大好きな人のためにおっぱい使えるんだってわかるからっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そう言ってさらにユーリスが愛撫のスピードを速めてくる。
line = "そう言ってさらにユーリスが愛撫のスピードを速めてくる。"

[[dialogue]]
speaker = "unk"
# 乳房を擦り剥かせるくらい、強く激しく扱いてくれる。
line = "乳房を擦り剥かせるくらい、強く激しく扱いてくれる。"

[[dialogue]]
speaker = "ユーリス"
# 「ふぁっ、あふぁっ、おっぱい熱いっ<emoji=heart04>　おち○ちんで擦り剥けちゃいそうっ<emoji=heart04>」
line = "「ふぁっ、あふぁっ、おっぱい熱いっ<emoji=heart04>　おち○ちんで擦り剥けちゃいそうっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「気持ちいいっ……<emoji=heart04>　初めておま○こに挿れてもらった時と同じだっ……<emoji=heart04>　私の女の場所に、君を刻み込んでもらってっ……<emoji=heart04>」
line = "「気持ちいいっ……<emoji=heart04>　初めておま○こに挿れてもらった時と同じだっ……<emoji=heart04>　私の女の場所に、君を刻み込んでもらってっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「あふぁっ、ダメっ、あっ、あっ<emoji=heart04>　やっぱり私の方がイっちゃっ、あぁああんっ<emoji=heart04>　パイズリでイっちゃっっ<emoji=heart04>」
line = "「あふぁっ、ダメっ、あっ、あっ<emoji=heart04>　やっぱり私の方がイっちゃっ、あぁああんっ<emoji=heart04>　パイズリでイっちゃっっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺以上に体をブルブル痙攣させて感じてくれるユーリスがエロい。
line = "俺以上に体をブルブル痙攣させて感じてくれるユーリスがエロい。"

[[dialogue]]
speaker = "unk"
# 蜜のような汗を谷間に溢れさせながら、まるで騎乗位でもするかのように一心不乱に乳房を上下させてくれて──
line = "蜜のような汗を谷間に溢れさせながら、まるで騎乗位でもするかのように一心不乱に乳房を上下させてくれて──"

[[dialogue]]
speaker = "ユーリス"
# 「エッチな彼女でごめんっ……<emoji=heart04>　でも、あっ、はぁっ、あぁっ、おっぱいとめられないっ……<emoji=heart04>」
line = "「エッチな彼女でごめんっ……<emoji=heart04>　でも、あっ、はぁっ、あぁっ、おっぱいとめられないっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「本当はずっとこうしたかったんだっ……<emoji=heart04>　私のおっぱいで大好きな恋人を気持ち良くしたかったっ……<emoji=heart04>」
line = "「本当はずっとこうしたかったんだっ……<emoji=heart04>　私のおっぱいで大好きな恋人を気持ち良くしたかったっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「乱暴に揉んだりしてもらいたいっ……<emoji=heart04>　サラシで潰すんじゃなくてっ、あっ、はぁっ、君の手の平で潰されたいっ……<emoji=heart04>」
line = "「乱暴に揉んだりしてもらいたいっ……<emoji=heart04>　サラシで潰すんじゃなくてっ、あっ、はぁっ、君の手の平で潰されたいっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「常にずっと、あっ、あっ、こうして君のおち○ちんを挟み込んでおきたいっ……<emoji=heart04>」
line = "「常にずっと、あっ、あっ、こうして君のおち○ちんを挟み込んでおきたいっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 発情した女の子の顔でユーリスが見上げる。
line = "発情した女の子の顔でユーリスが見上げる。"

[[dialogue]]
speaker = "unk"
# 目が合うだけでぶるりとお尻を震わせて、淫らに悶えてくれて……
line = "目が合うだけでぶるりとお尻を震わせて、淫らに悶えてくれて……"

[[dialogue]]
speaker = "ユーリス"
# 「好きだよっ<emoji=heart04>　好きだっ<emoji=heart04>　大好きだっ……<emoji=heart04>」
line = "「好きだよっ<emoji=heart04>　好きだっ<emoji=heart04>　大好きだっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「パイズリして欲しいって言ってくれて、ほんとは嬉しかったっ……<emoji=heart04>　お部屋で２人きりなわけでもないのに、カジノの店内なのにっ<emoji=heart04>」
line = "「パイズリして欲しいって言ってくれて、ほんとは嬉しかったっ……<emoji=heart04>　お部屋で２人きりなわけでもないのに、カジノの店内なのにっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「私のこと、いつも女として見てくれてるのがわかってっ<emoji=heart04>　それが本当に嬉しいっ、それだけでイっちゃうっ……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「私のこと、いつも女として見てくれてるのがわかってっ<emoji=heart04>　それが本当に嬉しいっ、それだけでイっちゃうっ……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 湯気が出そうなくらいユーリスの全身が火照る。
line = "湯気が出そうなくらいユーリスの全身が火照る。"

[[dialogue]]
speaker = "unk"
# 激しいパイズリが彼女の愛の大きさを示していて、俺も性欲と愛しさが今にも爆発しそうになる。
line = "激しいパイズリが彼女の愛の大きさを示していて、俺も性欲と愛しさが今にも爆発しそうになる。"

[[dialogue]]
speaker = "ユーリス"
# 「もっと頼んでっ<emoji=heart04>　私にエッチなこと頼んでいいからねっ<emoji=heart04>」
line = "「もっと頼んでっ<emoji=heart04>　私にエッチなこと頼んでいいからねっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「おっぱいもいつでも揉んでっ……<emoji=heart04>　他の人にバレなければ、どこでどれだけ揉まれても構わないからっ……<emoji=heart04>」
line = "「おっぱいもいつでも揉んでっ……<emoji=heart04>　他の人にバレなければ、どこでどれだけ揉まれても構わないからっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「むしろ触って欲しいっ<emoji=heart04>　おっぱいもお尻もっ、あっ、はぁっ、おま○こだってっ……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「むしろ触って欲しいっ<emoji=heart04>　おっぱいもお尻もっ、あっ、はぁっ、おま○こだってっ……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「私のこの体はっ、女の体はっ、君だけのためにあるものだからっっ……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「私のこの体はっ、女の体はっ、君だけのためにあるものだからっっ……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ユーリスの赤裸々な想いを聞いてペニスが猛る。
line = "ユーリスの赤裸々な想いを聞いてペニスが猛る。"

[[dialogue]]
speaker = "unk"
# 彼女のおっぱいの中で張り裂けんほどに脈動し、ドクドクと跳ねた。
line = "彼女のおっぱいの中で張り裂けんほどに脈動し、ドクドクと跳ねた。"

[[dialogue]]
speaker = "ユーリス"
# 「ああっ、出してっ<emoji=heart04>　どぴゅどぴゅびゅーびゅーしてっ<emoji=heart04>」
line = "「ああっ、出してっ<emoji=heart04>　どぴゅどぴゅびゅーびゅーしてっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「私もイクっ<emoji=heart04>　パイズリでイクっ<emoji=heart04>　大好きな人のおち○ちんゴシゴシしてるだけでイクぅっ<emoji=heart04>」
line = "「私もイクっ<emoji=heart04>　パイズリでイクっ<emoji=heart04>　大好きな人のおち○ちんゴシゴシしてるだけでイクぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「あっ、あっ、あっ、あっ<emoji=heart04><emoji=heart04><emoji=heart04>　イクイクイクぅぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あっ、あっ、あっ、あっ<emoji=heart04><emoji=heart04><emoji=heart04>　イクイクイクぅぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「ふぁあああああああああっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>　あっ──あはぁああああああっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「ふぁあああああああああっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>　あっ──あはぁああああああっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 溜まりに溜まった劣情をユーリスのおっぱいに、顔に、ありったけぶちまける。
line = "溜まりに溜まった劣情をユーリスのおっぱいに、顔に、ありったけぶちまける。"

[[dialogue]]
speaker = "ユーリス"
# 「あったかいっっ……<emoji=heart04>　顔もおっぱいもドロドロになってっ……<emoji=heart04>」
line = "「あったかいっっ……<emoji=heart04>　顔もおっぱいもドロドロになってっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「えへへっ、幸せぇ……<emoji=heart04>　イクっ、イクイクっっ……<emoji=heart04>　君の精子まみれにされるの、あふぁ、この世で一番大好きっ……<emoji=heart04>」
line = "「えへへっ、幸せぇ……<emoji=heart04>　イクっ、イクイクっっ……<emoji=heart04>　君の精子まみれにされるの、あふぁ、この世で一番大好きっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 体を汚されているというのに、ユーリスが幸せいっぱいのトロ顔で喘いでくれる。
line = "体を汚されているというのに、ユーリスが幸せいっぱいのトロ顔で喘いでくれる。"

[[dialogue]]
speaker = "unk"
# そんな彼女が愛しくて、おっぱいの谷間に白濁の水溜まりができるほど俺も射精し続けた。
line = "そんな彼女が愛しくて、おっぱいの谷間に白濁の水溜まりができるほど俺も射精し続けた。"

[[dialogue]]
speaker = "ユーリス"
# 「はぁ、はぁ、はぁ……<emoji=heart04>　君のエッチな匂いがおっぱいから上ってきて……<emoji=heart04>」
line = "「はぁ、はぁ、はぁ……<emoji=heart04>　君のエッチな匂いがおっぱいから上ってきて……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「私、ちゃんと君を気持ち良くしてあげられたんだね……<emoji=heart04>　私のおっぱいで……<emoji=heart04>　ふふ、本当に幸せだ……<emoji=heart04>」
line = "「私、ちゃんと君を気持ち良くしてあげられたんだね……<emoji=heart04>　私のおっぱいで……<emoji=heart04>　ふふ、本当に幸せだ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 谷間に溜まった精子を乳房に塗り込みながら、ユーリスが上目遣いで見つめてくる。
line = "谷間に溜まった精子を乳房に塗り込みながら、ユーリスが上目遣いで見つめてくる。"

[[dialogue]]
speaker = "ユーリス"
# 「またいつでも頼んでね……<emoji=heart04>　こんなおっぱいでいいなら、いつでも使ってくれていいから……<emoji=heart04>」
line = "「またいつでも頼んでね……<emoji=heart04>　こんなおっぱいでいいなら、いつでも使ってくれていいから……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「私も、んっ……はぁ……<emoji=heart04>　もっと君に尽くしたい……<emoji=heart04>　エッチなことしてあげたい……<emoji=heart04>」
line = "「私も、んっ……はぁ……<emoji=heart04>　もっと君に尽くしたい……<emoji=heart04>　エッチなことしてあげたい……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「君の親友ではなく、彼女として……<emoji=heart04>　ユーリスとしてじゃなく、ユリアーナとして……<emoji=heart04>」
line = "「君の親友ではなく、彼女として……<emoji=heart04>　ユーリスとしてじゃなく、ユリアーナとして……<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「もっとたくさんエッチなことして……ふふ。愛情を深め合いたいから……<emoji=heart04>」
line = "「もっとたくさんエッチなことして……ふふ。愛情を深め合いたいから……<emoji=heart04>」"
