[[dialogue]]
speaker = "unk"
# 第４話,コハルコの家族,P
line = "第４話,コハルコの家族,P"

[[dialogue]]
speaker = "ナツコ"
# 「あ、シンセーの会長さんだ！」
line = "「あ、シンセーの会長さんだ！」"

[[dialogue]]
speaker = "トウコ"
# 「こんにちは。コハルコお姉ちゃんがお世話になってます」
line = "「こんにちは。コハルコお姉ちゃんがお世話になってます」"

[[dialogue]]
speaker = "unk"
# こんにちは
line = "こんにちは"

[[dialogue]]
speaker = "コハルコ"
# 「ふふ、妹たちともすっかり仲良くなっちゃって。もうお兄ちゃんみたいだね」
line = "「ふふ、妹たちともすっかり仲良くなっちゃって。もうお兄ちゃんみたいだね」"

[[dialogue]]
speaker = "トウコ"
# 「デート行ってらっしゃい」
line = "「デート行ってらっしゃい」"

[[dialogue]]
speaker = "コハルコ"
# 「で、デート！？」
line = "「で、デート！？」"

[[dialogue]]
speaker = "ナツコ"
# 「また後でねー！」
line = "「また後でねー！」"

[[dialogue]]
speaker = "コハルコ"
# 「あ……２人とも行っちゃった……普通の買い物なのに」
line = "「あ……２人とも行っちゃった……普通の買い物なのに」"

[[dialogue]]
speaker = "コハルコ"
# 「妹たちの言ったことは気にしないで……ね？　とりあえず行こっか」
line = "「妹たちの言ったことは気にしないで……ね？　とりあえず行こっか」"

[[dialogue]]
speaker = "unk"
# 俺はデートでもいいですよ
line = "俺はデートでもいいですよ"

[[dialogue]]
speaker = "コハルコ"
# 「ひゃっ！？　もう、年上をからかわないで……え、本気？　それはそれでどうなんだか……」
line = "「ひゃっ！？　もう、年上をからかわないで……え、本気？　それはそれでどうなんだか……」"

[[dialogue]]
speaker = "コハルコ"
# 「えーい、こうなったらデートでいいよ！　秋葉原を楽しもう！」
line = "「えーい、こうなったらデートでいいよ！　秋葉原を楽しもう！」"

[[dialogue]]
speaker = "コハルコ"
# 「秋葉原は私の庭みたいなものだから、行きたいところがあったら言ってね。偽ジャスティスのおかげで臨時収入があったから奮発しちゃうよ」
line = "「秋葉原は私の庭みたいなものだから、行きたいところがあったら言ってね。偽ジャスティスのおかげで臨時収入があったから奮発しちゃうよ」"

[[dialogue]]
speaker = "コハルコ"
# 「穴場の電器屋さんに、割安なメイド喫茶、アニメショップ、アイドルの劇場、いろいろあるから」
line = "「穴場の電器屋さんに、割安なメイド喫茶、アニメショップ、アイドルの劇場、いろいろあるから」"

[[dialogue]]
speaker = "コハルコ"
# 「そうだ、お腹空いてない？　秋葉原はグルメの町でもあってね。ラーメンとか牛カツとか──あ、エッチなゲームの広告がまた変わってる……」
line = "「そうだ、お腹空いてない？　秋葉原はグルメの町でもあってね。ラーメンとか牛カツとか──あ、エッチなゲームの広告がまた変わってる……」"

[[dialogue]]
speaker = "コハルコ"
# 「まぁ、私となればエッチなゲームの広告も見慣れたもの……一時期うちの店にも置いてたから私もやったことあるし」
line = "「まぁ、私となればエッチなゲームの広告も見慣れたもの……一時期うちの店にも置いてたから私もやったことあるし」"

[[dialogue]]
speaker = "コハルコ"
# 「コホン。今のは忘れて」
line = "「コホン。今のは忘れて」"

[[dialogue]]
speaker = "コハルコ"
# 「それとも会長さんはそういうの興味ある？」
line = "「それとも会長さんはそういうの興味ある？」"

[[dialogue]]
speaker = "コハルコ"
# 「……興味ありそうな顔してる。会長さんのスケベ」
line = "「……興味ありそうな顔してる。会長さんのスケベ」"

[[dialogue]]
speaker = "コハルコ"
# 「なーんて、年頃の男の子なんだから、エッチなことが気になるのは当然だよね」
line = "「なーんて、年頃の男の子なんだから、エッチなことが気になるのは当然だよね」"

[[dialogue]]
speaker = "コハルコ"
# 「あ、顔が赤くなってる。恥ずかしがらなくても大丈夫。私、お姉さんだから理解はあるよ」
line = "「あ、顔が赤くなってる。恥ずかしがらなくても大丈夫。私、お姉さんだから理解はあるよ」"

[[dialogue]]
speaker = "コハルコ"
# 「ハッ──これって誘ってるみたい？　ゲームで似たようなシチュエーションがあった気が……」
line = "「ハッ──これって誘ってるみたい？　ゲームで似たようなシチュエーションがあった気が……」"

[[dialogue]]
speaker = "コハルコ"
# 「ま、まぁ私はお姉さんだから大丈夫だけど、会長さんには早いかな？　あはは、あはははー……」
line = "「ま、まぁ私はお姉さんだから大丈夫だけど、会長さんには早いかな？　あはは、あはははー……」"

[[dialogue]]
speaker = "コハルコ"
# 「気を取り直して遊びに行こっか。同人誌ショップに最新ＶＲゲーム体験、バッティングセンターにサバゲーもあるんだ。さ、アキバを楽しみ尽くすよ！」
line = "「気を取り直して遊びに行こっか。同人誌ショップに最新ＶＲゲーム体験、バッティングセンターにサバゲーもあるんだ。さ、アキバを楽しみ尽くすよ！」"

[[dialogue]]
speaker = "コハルコ"
# 「はぁ、はぁ……星騎士とはいえ、基本インドア派の私にはキツかったかな……。でも久々にいっぱい遊んでスッキリした」
line = "「はぁ、はぁ……星騎士とはいえ、基本インドア派の私にはキツかったかな……。でも久々にいっぱい遊んでスッキリした」"

[[dialogue]]
speaker = "コハルコ"
# 「だけど本命の買い物を忘れちゃダメだよね。もうすぐナツコの誕生日だから、ジャスティスガールのポーチを買ってあげないと」
line = "「だけど本命の買い物を忘れちゃダメだよね。もうすぐナツコの誕生日だから、ジャスティスガールのポーチを買ってあげないと」"

[[dialogue]]
speaker = "コハルコ"
# 「あとトウコのプレゼントも考えないとだ。トウコは興味ないふりしてるけど、ジャスティスガールのアニメちゃんと見てるから、ほんとは欲しいと思うんだよね」
line = "「あとトウコのプレゼントも考えないとだ。トウコは興味ないふりしてるけど、ジャスティスガールのアニメちゃんと見てるから、ほんとは欲しいと思うんだよね」"

[[dialogue]]
speaker = "コハルコ"
# 「でも誕生日のナツコと同じものはまずいし……うーん……悩むなぁ」
line = "「でも誕生日のナツコと同じものはまずいし……うーん……悩むなぁ」"

[[dialogue]]
speaker = "コハルコ"
# 「さーて、妹たちの学費を稼ぐためにも、またバグを見つけて賞金とってこないとね」
line = "「さーて、妹たちの学費を稼ぐためにも、またバグを見つけて賞金とってこないとね」"

[[dialogue]]
speaker = "unk"
# 家族を大事にしてるんですね
line = "家族を大事にしてるんですね"

[[dialogue]]
speaker = "コハルコ"
# 「うん。私はやっぱり家族が一番大事。新星学園でセキュリティや星騎士やってるのも、結局は家族のためだから」
line = "「うん。私はやっぱり家族が一番大事。新星学園でセキュリティや星騎士やってるのも、結局は家族のためだから」"

[[dialogue]]
speaker = "コハルコ"
# 「モンスターに店が壊されたり、お父さんが借金の保証人になってたり、お母さんの病気が再発したり、いろいろあったけど……私は家族が幸せになってくれるのが一番嬉しい」
line = "「モンスターに店が壊されたり、お父さんが借金の保証人になってたり、お母さんの病気が再発したり、いろいろあったけど……私は家族が幸せになってくれるのが一番嬉しい」"

[[dialogue]]
speaker = "unk"
# （苦労人だ……！）
line = "（苦労人だ……！）"

[[dialogue]]
speaker = "コハルコ"
# 「……会長さんだから言うけど、実は私、家族と血が繋がってないんだよね」
line = "「……会長さんだから言うけど、実は私、家族と血が繋がってないんだよね」"

[[dialogue]]
speaker = "unk"
# ！
line = "！"

[[dialogue]]
speaker = "コハルコ"
# 「驚かせてしまうかもしれないけど、騙したくはないから、妹たちが大きくなったらいつか教えるつもり」
line = "「驚かせてしまうかもしれないけど、騙したくはないから、妹たちが大きくなったらいつか教えるつもり」"

[[dialogue]]
speaker = "コハルコ"
# 「家が本当に大変だった時、お父さんとお母さんが教えてくれたんだ。血が繋がった子どもじゃないから、もう私たちのために頑張らなくていいよ、好きに生きてって」
line = "「家が本当に大変だった時、お父さんとお母さんが教えてくれたんだ。血が繋がった子どもじゃないから、もう私たちのために頑張らなくていいよ、好きに生きてって」"

[[dialogue]]
speaker = "コハルコ"
# 「でも血が繋がってなくても、私は家族を愛してる。本当の家族なんだって信じてる。だから頑張れるんだ」
line = "「でも血が繋がってなくても、私は家族を愛してる。本当の家族なんだって信じてる。だから頑張れるんだ」"

[[dialogue]]
speaker = "unk"
# 俺もそう思います
line = "俺もそう思います"

[[dialogue]]
speaker = "コハルコ"
# 「ありがとう。会長さんならそう言ってくれる気がしてた」
line = "「ありがとう。会長さんならそう言ってくれる気がしてた」"

[[dialogue]]
speaker = "コハルコ"
# 「妹とも仲良しだし、会長さんはもう私の家族みたいなもの……かな。ふふふ」
line = "「妹とも仲良しだし、会長さんはもう私の家族みたいなもの……かな。ふふふ」"

[[dialogue]]
speaker = "コハルコ"
# 「ナツコの誕生日、ささやかだけどパーティーをするから会長さんも来て。正義の魔法使いが特製クリームシチューをご馳走するよ♪」
line = "「ナツコの誕生日、ささやかだけどパーティーをするから会長さんも来て。正義の魔法使いが特製クリームシチューをご馳走するよ♪」"
