[[dialogue]]
speaker = "unk"
# 第３話,ファンシー・メルトダウン・前編,P
line = "第３話,ファンシー・メルトダウン・前編,P"

[[dialogue]]
speaker = "unk"
# メルエルと再会してから、３か月程経ったある日──
line = "メルエルと再会してから、３か月程経ったある日──"

[[dialogue]]
speaker = "メルエル"
# 「こうやって、何事もない平和な放課後も久しぶりだね～」
line = "「こうやって、何事もない平和な放課後も久しぶりだね～」"

[[dialogue]]
speaker = "メルエル"
# 「このところずっと、目まぐるしい忙しさだったよね。星徒会で急ぎの案件が発生したり、出動要請が立て続いたり」
line = "「このところずっと、目まぐるしい忙しさだったよね。星徒会で急ぎの案件が発生したり、出動要請が立て続いたり」"

[[dialogue]]
speaker = "unk"
# メルエルが色々と手伝ってくれて、助かったよ
line = "メルエルが色々と手伝ってくれて、助かったよ"

[[dialogue]]
speaker = "メルエル"
# 「えへへっ。キミに褒められると、嬉しいな♪」
line = "「えへへっ。キミに褒められると、嬉しいな♪」"

[[dialogue]]
speaker = "メルエル"
# 「こうして一緒に帰るのも久しぶりで嬉しいし、思わず鼻歌も歌いたくなっちゃうよ♪」
line = "「こうして一緒に帰るのも久しぶりで嬉しいし、思わず鼻歌も歌いたくなっちゃうよ♪」"

[[dialogue]]
speaker = "unk"
# お礼に何か出来ることはないかな？
line = "お礼に何か出来ることはないかな？"

[[dialogue]]
speaker = "メルエル"
# 「え？　そ、それってつまり……ご褒美ってこと！？」
line = "「え？　そ、それってつまり……ご褒美ってこと！？」"

[[dialogue]]
speaker = "メルエル"
# 「だ、だったら私……えっと──」
line = "「だ、だったら私……えっと──」"

[[dialogue]]
speaker = "メルエル"
# 「会長くんと、『放課後デート』がしてみたい……！」
line = "「会長くんと、『放課後デート』がしてみたい……！」"

[[dialogue]]
speaker = "メルエル"
# 「その……ダ、ダメ、かな？」
line = "「その……ダ、ダメ、かな？」"

[[dialogue]]
speaker = "unk"
# 今までにもメルエルと出掛けることはあった。……しかし、『デート』とはっきり言われたのはこれが初めてで、俺の方もドギマギしてしまう。
line = "今までにもメルエルと出掛けることはあった。……しかし、『デート』とはっきり言われたのはこれが初めてで、俺の方もドギマギしてしまう。"

[[dialogue]]
speaker = "unk"
# っ……メルエルが、それでいいのなら……
line = "っ……メルエルが、それでいいのなら……"

[[dialogue]]
speaker = "メルエル"
# 「本当！？　ありがとう、会長くんっ♪」
line = "「本当！？　ありがとう、会長くんっ♪」"

[[dialogue]]
speaker = "メルエル"
# （えへへ。会長くんとのデート、凄く嬉しい……♪）
line = "（えへへ。会長くんとのデート、凄く嬉しい……♪）"

[[dialogue]]
speaker = "unk"
# 俺とメルエルはそのまま『デート』へ出かけることになった。しかし何故か、彼女は口数が少なくて──
line = "俺とメルエルはそのまま『デート』へ出かけることになった。しかし何故か、彼女は口数が少なくて──"

[[dialogue]]
speaker = "メルエル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "メルエル"
# （うぅ～、せっかくのデートなのに、何故か緊張しちゃって、全然言葉が出てこないよぉ～）
line = "（うぅ～、せっかくのデートなのに、何故か緊張しちゃって、全然言葉が出てこないよぉ～）"

[[dialogue]]
speaker = "unk"
# もしかして、緊張……してる？
line = "もしかして、緊張……してる？"

[[dialogue]]
speaker = "メルエル"
# 「あ……！　う、うん……実は……少し」
line = "「あ……！　う、うん……実は……少し」"

[[dialogue]]
speaker = "メルエル"
# 「一緒に出かけたのは、これが初めてじゃないのに、変だよね……あはは」
line = "「一緒に出かけたのは、これが初めてじゃないのに、変だよね……あはは」"

[[dialogue]]
speaker = "unk"
# 実は……俺も『デート』って言われて、ちょっと緊張してた
line = "実は……俺も『デート』って言われて、ちょっと緊張してた"

[[dialogue]]
speaker = "メルエル"
# 「そ、そうなの……？　えへっ、えへへ♪」
line = "「そ、そうなの……？　えへっ、えへへ♪」"

[[dialogue]]
speaker = "メルエル"
# （それって会長くんも私のこと……意識、してくれてたってことだよね？）
line = "（それって会長くんも私のこと……意識、してくれてたってことだよね？）"

[[dialogue]]
speaker = "unk"
# そんな感じで並んで歩いていたら、ふとした瞬間、メルエルと手が触れてしまう。
line = "そんな感じで並んで歩いていたら、ふとした瞬間、メルエルと手が触れてしまう。"

[[dialogue]]
speaker = "メルエル"
# 「あっ……ご、ごめんね！　距離、近すぎたかも……」
line = "「あっ……ご、ごめんね！　距離、近すぎたかも……」"

[[dialogue]]
speaker = "unk"
# い、いや、こちらこそゴメン
line = "い、いや、こちらこそゴメン"

[[dialogue]]
speaker = "メルエル"
# 「って、幼なじみなのにね……手が触れたくらいで、大げさかな……あはは」
line = "「って、幼なじみなのにね……手が触れたくらいで、大げさかな……あはは」"

[[dialogue]]
speaker = "メルエル"
# 「そういえば、昔は遊びに行く時はいつも手を繋いでたりしてたな～。キミは覚えてたりする？」
line = "「そういえば、昔は遊びに行く時はいつも手を繋いでたりしてたな～。キミは覚えてたりする？」"

[[dialogue]]
speaker = "unk"
# 朧気だけど、手を繋いでた記憶、思い出したかも……
line = "朧気だけど、手を繋いでた記憶、思い出したかも……"

[[dialogue]]
speaker = "メルエル"
# 「あっ、思い出してくれた？　あの頃は普通のことだったのにね～……」
line = "「あっ、思い出してくれた？　あの頃は普通のことだったのにね～……」"

[[dialogue]]
speaker = "メルエル"
# （あの頃よりも、もっともっと、キミを好きになっちゃったから仕方ないことなんだけど……。気兼ねなく手を繋げないのは少し寂しいかも）
line = "（あの頃よりも、もっともっと、キミを好きになっちゃったから仕方ないことなんだけど……。気兼ねなく手を繋げないのは少し寂しいかも）"

[[dialogue]]
speaker = "unk"
# （何も言わず、メルエルと手を繋ぐ）
line = "（何も言わず、メルエルと手を繋ぐ）"

[[dialogue]]
speaker = "メルエル"
# 「か、会長くん？　ど、どうしたの？」
line = "「か、会長くん？　ど、どうしたの？」"

[[dialogue]]
speaker = "メルエル"
# （うぅぅ～～……っ。嬉しい、けどぉ！　会長くんの手、大きくて、男の人って感じで、ドキドキしちゃうよぉ！）
line = "（うぅぅ～～……っ。嬉しい、けどぉ！　会長くんの手、大きくて、男の人って感じで、ドキドキしちゃうよぉ！）"

[[dialogue]]
speaker = "unk"
# で、デートだし、普通かなぁって……
line = "で、デートだし、普通かなぁって……"

[[dialogue]]
speaker = "メルエル"
# 「そ、そっか……デート。……デート、だもんねっ」
line = "「そ、そっか……デート。……デート、だもんねっ」"

[[dialogue]]
speaker = "メルエル"
# （この感じ……懐かしくて胸がいっぱいになる）
line = "（この感じ……懐かしくて胸がいっぱいになる）"

[[dialogue]]
speaker = "メルエル"
# （手は大きくなったけど、昔と変わらず温かくて、安心する……）
line = "（手は大きくなったけど、昔と変わらず温かくて、安心する……）"

[[dialogue]]
speaker = "メルエル"
# （何より、キミは優しくて……やっぱり好き。大好き♪）
line = "（何より、キミは優しくて……やっぱり好き。大好き♪）"

[[dialogue]]
speaker = "メルエル"
# 「えへへっ♪　……メルトしちゃいそう<emoji=heart04>」
line = "「えへへっ♪　……メルトしちゃいそう<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# メルエルは照れたようにはにかみながら、俺の手をそっと握り返すのだった。
line = "メルエルは照れたようにはにかみながら、俺の手をそっと握り返すのだった。"
