[[dialogue]]
speaker = "unk"
# 第４話,シャルレーヌの夢,P
line = "第４話,シャルレーヌの夢,P"

[[dialogue]]
speaker = "unk"
# 福引でポケットティッシュ以外を当てたのはいつ以来だろう。
line = "福引でポケットティッシュ以外を当てたのはいつ以来だろう。"

[[dialogue]]
speaker = "unk"
# しかも驚くことに大当たりだ。流星市国から少し遠出したところにある遊園地の１日フリーパス。
line = "しかも驚くことに大当たりだ。流星市国から少し遠出したところにある遊園地の１日フリーパス。"

[[dialogue]]
speaker = "unk"
# 男１人で行くのはあまりに悲しいし、誰かを誘いたいけれど……
line = "男１人で行くのはあまりに悲しいし、誰かを誘いたいけれど……"

[[dialogue]]
speaker = "シャルレーヌ"
# 「あれ、会長さんじゃないですかぁ」
line = "「あれ、会長さんじゃないですかぁ」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「街中で鐘を鳴らされているから、通報でもされてるのかと思っちゃいました♪」
line = "「街中で鐘を鳴らされているから、通報でもされてるのかと思っちゃいました♪」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「──って、ああ、福引で当たったんですね。それは……遊園地のチケット？」
line = "「──って、ああ、福引で当たったんですね。それは……遊園地のチケット？」"

[[dialogue]]
speaker = "unk"
# 一緒に行く？
line = "一緒に行く？"

[[dialogue]]
speaker = "シャルレーヌ"
# 「いいですね。行きます、行きます」
line = "「いいですね。行きます、行きます」"

[[dialogue]]
speaker = "unk"
# 貴族令嬢が遊園地なんて──って、ＯＫ！？
line = "貴族令嬢が遊園地なんて──って、ＯＫ！？"

[[dialogue]]
speaker = "シャルレーヌ"
# 「会長さん、何ですかー。そのひとりノリツッコミ」
line = "「会長さん、何ですかー。そのひとりノリツッコミ」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ともかくお誘い自体はＯＫ。でも明日からしばらく忙しくなっちゃうのよね……」
line = "「ともかくお誘い自体はＯＫ。でも明日からしばらく忙しくなっちゃうのよね……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「会長さんさえ良かったら、今すぐ行っちゃいます？　制服のまま遊園地で遊ぶ、っていうのも面白そう♪」
line = "「会長さんさえ良かったら、今すぐ行っちゃいます？　制服のまま遊園地で遊ぶ、っていうのも面白そう♪」"

[[dialogue]]
speaker = "unk"
# こうしていきなり始まった、シャルレーヌとの遊園地デート。
line = "こうしていきなり始まった、シャルレーヌとの遊園地デート。"

[[dialogue]]
speaker = "unk"
# ディアーブルという名門貴族出身の彼女が、庶民の遊び場とも呼べる遊園地を楽しめるのかという杞憂は、すぐになくなった。
line = "ディアーブルという名門貴族出身の彼女が、庶民の遊び場とも呼べる遊園地を楽しめるのかという杞憂は、すぐになくなった。"

[[dialogue]]
speaker = "unk"
# 驚くべきことに、シャルレーヌは遊園地というものにとても慣れていたのだ。
line = "驚くべきことに、シャルレーヌは遊園地というものにとても慣れていたのだ。"

[[dialogue]]
speaker = "unk"
# 閉園ぎりぎりまで遊ぶ彼女の姿は、遊園地という『非日常』を楽しむ歳相応の少女そのものだった──
line = "閉園ぎりぎりまで遊ぶ彼女の姿は、遊園地という『非日常』を楽しむ歳相応の少女そのものだった──"

[[dialogue]]
speaker = "シャルレーヌ"
# 「すっかり遅くなっちゃったかも……でも楽しかったぁ」
line = "「すっかり遅くなっちゃったかも……でも楽しかったぁ」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「料理もおいしかったし、パレードの演出も素敵だったし」
line = "「料理もおいしかったし、パレードの演出も素敵だったし」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「惜しむらくは全部のアトラクション、回れなかったことかしら。ん～、気になる……」
line = "「惜しむらくは全部のアトラクション、回れなかったことかしら。ん～、気になる……」"

[[dialogue]]
speaker = "unk"
# 遊園地、もしかしてすごく好きだったり？
line = "遊園地、もしかしてすごく好きだったり？"

[[dialogue]]
speaker = "シャルレーヌ"
# 「……そんなわけないでしょー。子供じゃないんだから」
line = "「……そんなわけないでしょー。子供じゃないんだから」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「って。流石に無理があるか。うん、遊園地はね、かなり好き」
line = "「って。流石に無理があるか。うん、遊園地はね、かなり好き」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「人間界に来てすぐの頃だったかしら……学園のクラスメイトと一緒に遊びに行って。とても驚いたの」
line = "「人間界に来てすぐの頃だったかしら……学園のクラスメイトと一緒に遊びに行って。とても驚いたの」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「特別な日にだけ許されるお祭りが、毎日開催している感じ。素敵な場所だなって思ったわ」
line = "「特別な日にだけ許されるお祭りが、毎日開催している感じ。素敵な場所だなって思ったわ」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「魔界──少なくとも私の出身のシャリオン地方には、こんな素敵なものはない」
line = "「魔界──少なくとも私の出身のシャリオン地方には、こんな素敵なものはない」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「だからいずれ造ってやろうと思っているの。シャリオンで初めての遊園地を」
line = "「だからいずれ造ってやろうと思っているの。シャリオンで初めての遊園地を」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「私のための遊園地を思う存分楽しんで……ついでに領民たちにも、この素敵な体験をさせてあげるつもり」
line = "「私のための遊園地を思う存分楽しんで……ついでに領民たちにも、この素敵な体験をさせてあげるつもり」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「何驚いた顔してるんですか、会長さん？　私が領民のことを気にするのがそんなにおかしいんです？」
line = "「何驚いた顔してるんですか、会長さん？　私が領民のことを気にするのがそんなにおかしいんです？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「私は貴族。支配層なのよ？　付き従う者には相応の生活をさせてあげないといけないわ」
line = "「私は貴族。支配層なのよ？　付き従う者には相応の生活をさせてあげないといけないわ」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ただ力で押さえつけるなんて三流のやること。ムチとアメを使い分けて、自分から服従したがるようにさせるのが貴族の在り方」
line = "「ただ力で押さえつけるなんて三流のやること。ムチとアメを使い分けて、自分から服従したがるようにさせるのが貴族の在り方」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「シャルレーヌ様にかしずいて幸せだった……そう思わせるのよ。それが支配するってことなんだから」
line = "「シャルレーヌ様にかしずいて幸せだった……そう思わせるのよ。それが支配するってことなんだから」"

[[dialogue]]
speaker = "unk"
# ……シャルレーヌらしいな
line = "……シャルレーヌらしいな"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ふふ、他人事みたいに言ってる場合？」
line = "「ふふ、他人事みたいに言ってる場合？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「遊園地なんて造れるようになる頃には、ディアーブルの香水の名はもっと三界に知れ渡っているはずよ」
line = "「遊園地なんて造れるようになる頃には、ディアーブルの香水の名はもっと三界に知れ渡っているはずよ」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「当然、私の権力も、今以上に凄いことになってる」
line = "「当然、私の権力も、今以上に凄いことになってる」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「つまり──その時にはきっと、会長さんも私のペットになってるってことですけど～？」
line = "「つまり──その時にはきっと、会長さんも私のペットになってるってことですけど～？」"

[[dialogue]]
speaker = "unk"
# 簡単には負けないからな！
line = "簡単には負けないからな！"

[[dialogue]]
speaker = "シャルレーヌ"
# 「くすくすっ♪　私に負けてば～っかりなのに強がりばっかり♪」
line = "「くすくすっ♪　私に負けてば～っかりなのに強がりばっかり♪」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「でも会長さんのそういう所、嫌いじゃないですよ<emoji=heart04>」
line = "「でも会長さんのそういう所、嫌いじゃないですよ<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「どうせ最後は、私にわからされちゃうんだから……」
line = "「どうせ最後は、私にわからされちゃうんだから……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「どうかそれまで、精一杯に抵抗して、シャルレーヌを楽しませてくださいね♪」
line = "「どうかそれまで、精一杯に抵抗して、シャルレーヌを楽しませてくださいね♪」"
