[[dialogue]]
speaker = "unk"
# ヴィーナスと恋人になってから、初めての休日。
line = "ヴィーナスと恋人になってから、初めての休日。"

[[dialogue]]
speaker = "unk"
# 恋人になってからのヴィーナスは、俺に対して少しだけ甘えん坊で──
line = "恋人になってからのヴィーナスは、俺に対して少しだけ甘えん坊で──"

[[dialogue]]
speaker = "ヴィーナス"
# 「……好き。私、こんなに誰かに夢中になったのは初めてよ。……どうしちゃったのかしら」
line = "「……好き。私、こんなに誰かに夢中になったのは初めてよ。……どうしちゃったのかしら」"

[[dialogue]]
speaker = "ヴィーナス"
# 「こうやって隣に座って、腕を組んでるだけでも幸せになれるのよね……恋をするって不思議だわ」
line = "「こうやって隣に座って、腕を組んでるだけでも幸せになれるのよね……恋をするって不思議だわ」"

[[dialogue]]
speaker = "unk"
# 俺の肩に頭を乗せて、甘えてくるヴィーナス。その小さくて可愛らしい頭を、髪の毛を梳くようにして撫でた。
line = "俺の肩に頭を乗せて、甘えてくるヴィーナス。その小さくて可愛らしい頭を、髪の毛を梳くようにして撫でた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「んふ……私、あなたに頭撫でられるの好き。すっごく安心できるのよ、なんでかしらね」
line = "「んふ……私、あなたに頭撫でられるの好き。すっごく安心できるのよ、なんでかしらね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ねえ、今日、星徒会室には誰も来ないようにお願いしてるの……」
line = "「ねえ、今日、星徒会室には誰も来ないようにお願いしてるの……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だから──」
line = "「だから──」"

[[dialogue]]
speaker = "unk"
# しかし、<ruby=ディスク>ＤＩＳＣ</ruby>からは無情にもモンスター発見のアラートが鳴り響く……。
line = "しかし、<ruby>ＤＩＳＣ<rt>ディスク</rt></ruby>からは無情にもモンスター発見のアラートが鳴り響く……。"

[[dialogue]]
speaker = "ヴィーナス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ああもう！！！　わかったわよ！　この雰囲気どーするのよ！？　モンスターども、全員吹っ飛ばしてやるわ！！！」
line = "「ああもう！！！　わかったわよ！　この雰囲気どーするのよ！？　モンスターども、全員吹っ飛ばしてやるわ！！！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ほら行くわよ！　それでそれでそれでっ！」
line = "「ほら行くわよ！　それでそれでそれでっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「帰ったら私と、えっちしてもらうんだから！！！」
line = "「帰ったら私と、えっちしてもらうんだから！！！」"

[[dialogue]]
speaker = "unk"
# ──そうして、かつてないスピードでモンスターを蹴散らした俺たちは、再び星徒会室に舞い戻ってきた。
line = "──そうして、かつてないスピードでモンスターを蹴散らした俺たちは、再び星徒会室に舞い戻ってきた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「んっ……もう我慢出来ないわ。……はぁ、んくちゅ、ちゅ、ちゅる、ちゅぷぅ……」
line = "「んっ……もう我慢出来ないわ。……はぁ、んくちゅ、ちゅ、ちゅる、ちゅぷぅ……」"

[[dialogue]]
speaker = "unk"
# 貪るようにディープキスを交わしながら、ソファーの上になだれ込む。
line = "貪るようにディープキスを交わしながら、ソファーの上になだれ込む。"

[[dialogue]]
speaker = "ヴィーナス"
# 「んちゅっ<emoji=heart04>　ちゅっ、ちゅぷるっ<emoji=heart04>　舌きもちひ……ちゅれろっ<emoji=heart04>　ちゅっ、んちゅっ<emoji=heart04>　……んむっ、むちゅっ、ちゅるっ……<emoji=heart04>」
line = "「んちゅっ<emoji=heart04>　ちゅっ、ちゅぷるっ<emoji=heart04>　舌きもちひ……ちゅれろっ<emoji=heart04>　ちゅっ、んちゅっ<emoji=heart04>　……んむっ、むちゅっ、ちゅるっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んっ<emoji=heart04>　ぷはぁっ<emoji=heart04>　……はぁ、はぁ、はぁぁん<emoji=heart04>　んっ、なぁに<emoji=heart04>？　はぁ……んふふ、また頭撫でてくれるの<emoji=heart04>？」
line = "「んっ<emoji=heart04>　ぷはぁっ<emoji=heart04>　……はぁ、はぁ、はぁぁん<emoji=heart04>　んっ、なぁに<emoji=heart04>？　はぁ……んふふ、また頭撫でてくれるの<emoji=heart04>？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んふぅ<emoji=heart04>　……気持ちいい<emoji=heart04>　身体から力抜けちゃう……はぁぁ<emoji=heart04>　なんでこんなに心地いいのかしら……んんっ<emoji=heart04>」
line = "「んふぅ<emoji=heart04>　……気持ちいい<emoji=heart04>　身体から力抜けちゃう……はぁぁ<emoji=heart04>　なんでこんなに心地いいのかしら……んんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ん……あんっ<emoji=heart04>　おっぱい、触りたいの……？　んふっ、やんっ<emoji=heart04>　ちょっとくすぐったいわよぉ……。あっ<emoji=heart04>　あんっ、揉むのダメぇ……んんっ、感じちゃう……ふあぁんっ<emoji=heart04>」
line = "「ん……あんっ<emoji=heart04>　おっぱい、触りたいの……？　んふっ、やんっ<emoji=heart04>　ちょっとくすぐったいわよぉ……。あっ<emoji=heart04>　あんっ、揉むのダメぇ……んんっ、感じちゃう……ふあぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、乳首ダメぇ……<emoji=heart04>　あぁんっ、いま敏感になっててぇっ……んああっ、きもちぃ<emoji=heart04>　ふあぁっ、んんっ、あんっ……はあぁっ、んくっ、んんっふぅぅ……<emoji=heart04>！」
line = "「あっ、乳首ダメぇ……<emoji=heart04>　あぁんっ、いま敏感になっててぇっ……んああっ、きもちぃ<emoji=heart04>　ふあぁっ、んんっ、あんっ……はあぁっ、んくっ、んんっふぅぅ……<emoji=heart04>！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、おっぱい吸っちゃ<emoji=heart04>　……んああっ、んんっ、あぁんっ<emoji=heart04>　……舌きもちいいっ、ふあぁっ、んっ、んあぁっ……<emoji=heart04>！」
line = "「あっ、おっぱい吸っちゃ<emoji=heart04>　……んああっ、んんっ、あぁんっ<emoji=heart04>　……舌きもちいいっ、ふあぁっ、んっ、んあぁっ……<emoji=heart04>！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、あっ、ダメぇっ<emoji=heart04>！　乳首コリコリと吸うの同時、すごい、よぉっ……<emoji=heart04>　んあぁあっ、イっちゃうっ、おっぱいでイっちゃうからぁっ！」
line = "「あっ、あっ、ダメぇっ<emoji=heart04>！　乳首コリコリと吸うの同時、すごい、よぉっ……<emoji=heart04>　んあぁあっ、イっちゃうっ、おっぱいでイっちゃうからぁっ！」"

[[dialogue]]
speaker = "クロト"
# 「っ……ヴィーナス、俺もう！」
line = "「っ……ヴィーナス、俺もう！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「はあぁっ……んはぁ、お腹に固いの当たってるぅ……んんっ、あなたの大きいの……わ、私ももう、おま○こ、凄いことになってるから……<emoji=heart04>　んふぅっ」
line = "「はあぁっ……んはぁ、お腹に固いの当たってるぅ……んんっ、あなたの大きいの……わ、私ももう、おま○こ、凄いことになってるから……<emoji=heart04>　んふぅっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「はぁぁ。ふぇ……？　『おま○こ』って言い方、えっちだった<emoji=heart04>？　ふふっ、こう言ったら……はぁ、あなたが喜ぶかなって思って、恥ずかしいけど、言ってみたの<emoji=heart04>　はふぅぅ」
line = "「はぁぁ。ふぇ……？　『おま○こ』って言い方、えっちだった<emoji=heart04>？　ふふっ、こう言ったら……はぁ、あなたが喜ぶかなって思って、恥ずかしいけど、言ってみたの<emoji=heart04>　はふぅぅ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「う、うん<emoji=heart04>　はぁぁぁん……そ、そんなに喜んでくれると、頑張ってよかったって、思うわ<emoji=heart04>　はぁっ。これからも、えっちの時は言うねっ。あなたのために、おま○こって言う<emoji=heart04>」
line = "「う、うん<emoji=heart04>　はぁぁぁん……そ、そんなに喜んでくれると、頑張ってよかったって、思うわ<emoji=heart04>　はぁっ。これからも、えっちの時は言うねっ。あなたのために、おま○こって言う<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「はぁ、んっ、ふぅ……で、でも、あんまりじっと見ないでぇ<emoji=heart04>　はぁぁ、期待して愛液でぬちょぬちょになっちゃってるおま○こぉ<emoji=heart04>　恥ずかしいからぁ……んあぁっ！？」
line = "「はぁ、んっ、ふぅ……で、でも、あんまりじっと見ないでぇ<emoji=heart04>　はぁぁ、期待して愛液でぬちょぬちょになっちゃってるおま○こぉ<emoji=heart04>　恥ずかしいからぁ……んあぁっ！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、待って、触られちゃうと感じちゃうっ<emoji=heart04>　おま○こ、凄く敏感になってるのっ。あっ、あっ、んあぁぁっ<emoji=heart04>！」
line = "「あっ、待って、触られちゃうと感じちゃうっ<emoji=heart04>　おま○こ、凄く敏感になってるのっ。あっ、あっ、んあぁぁっ<emoji=heart04>！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、あっ、あぁっ。触り方ぁ、優しくて……ふぁぁぁ<emoji=heart04>　く、クリもきもちいっ、んんっ、あっ、感じるのぉっ……！　ふあぁぁんっ！」
line = "「あっ、あっ、あぁっ。触り方ぁ、優しくて……ふぁぁぁ<emoji=heart04>　く、クリもきもちいっ、んんっ、あっ、感じるのぉっ……！　ふあぁぁんっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んあぁっ、も、もうダメ、私も我慢できないぃ……<emoji=heart04>！　ねぇ、おち○ちん、おち○ちんもう挿れてぇ……！　はぁ、はぁっ、おま○こ期待で熱くて、変になっちゃってるよぉ<emoji=heart04>」
line = "「んあぁっ、も、もうダメ、私も我慢できないぃ……<emoji=heart04>！　ねぇ、おち○ちん、おち○ちんもう挿れてぇ……！　はぁ、はぁっ、おま○こ期待で熱くて、変になっちゃってるよぉ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「はあぁ……っ、あなたのおち○ちん<emoji=heart04>！　太くて逞しくて……<emoji=heart04>　んあぁっ、おま○こキュンとしちゃうっ……そんなの挿れられちゃうって、想像しちゃったら、ふぅぅ……」
line = "「はあぁ……っ、あなたのおち○ちん<emoji=heart04>！　太くて逞しくて……<emoji=heart04>　んあぁっ、おま○こキュンとしちゃうっ……そんなの挿れられちゃうって、想像しちゃったら、ふぅぅ……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、あっ、先っぽ、おま○こに当たってるっ<emoji=heart04>　ふあぁっ……きて、おち○ちん来て……私の初めて、奪って欲しいのっ<emoji=heart04>　……はあぁぁっ」
line = "「あっ、あっ、先っぽ、おま○こに当たってるっ<emoji=heart04>　ふあぁっ……きて、おち○ちん来て……私の初めて、奪って欲しいのっ<emoji=heart04>　……はあぁぁっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んあっ……ふあぁっ<emoji=heart04>！　抱き締めながら<emoji=heart04>　挿れちゃうのっ<emoji=heart04>？　あっ、あんっ、おち○ちん見えないから、感触意識しちゃっ……あっ、くるっ──」
line = "「んあっ……ふあぁっ<emoji=heart04>！　抱き締めながら<emoji=heart04>　挿れちゃうのっ<emoji=heart04>？　あっ、あんっ、おち○ちん見えないから、感触意識しちゃっ……あっ、くるっ──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んくっ、んああぁぁぁぁああああ──っ！」
line = "「んくっ、んああぁぁぁぁああああ──っ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んっ、はぁっ、はぁっ、ふぅぅっ……！　んんっ、ふあぁ……<emoji=heart04>！　おち○ちん<emoji=heart04>　入ったぁ……<emoji=heart04>！　ふぅぅ……はぁぁ……っ」
line = "「んっ、はぁっ、はぁっ、ふぅぅっ……！　んんっ、ふあぁ……<emoji=heart04>！　おち○ちん<emoji=heart04>　入ったぁ……<emoji=heart04>！　ふぅぅ……はぁぁ……っ」"

[[dialogue]]
speaker = "unk"
# ペニスと秘部の繋がったところから、ヴィーナスの初めての証が伝う。
line = "ペニスと秘部の繋がったところから、ヴィーナスの初めての証が伝う。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あ、あっ<emoji=heart04>　嘘っ<emoji=heart04>　初めてなのに……<emoji=heart04>　ふぅぅ、はぁぁ……こんなの<emoji=heart04>　聞いてな……んんっ<emoji=heart04>　はぁっ、はあぁっ……！」
line = "「あ、あっ<emoji=heart04>　嘘っ<emoji=heart04>　初めてなのに……<emoji=heart04>　ふぅぅ、はぁぁ……こんなの<emoji=heart04>　聞いてな……んんっ<emoji=heart04>　はぁっ、はあぁっ……！」"

[[dialogue]]
speaker = "クロト"
# 「ごめんっ、そんなに痛かったか……？」
line = "「ごめんっ、そんなに痛かったか……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ち、違うの……<emoji=heart04>　逆っ<emoji=heart04>　お、おま○こ<emoji=heart04>　怖いくらい気持ちいいのっ……<emoji=heart04>！　んはぁぁっ<emoji=heart04>　確かに処女膜破れたけど、それよりずっと……ふあぁっ<emoji=heart04>」
line = "「ち、違うの……<emoji=heart04>　逆っ<emoji=heart04>　お、おま○こ<emoji=heart04>　怖いくらい気持ちいいのっ……<emoji=heart04>！　んはぁぁっ<emoji=heart04>　確かに処女膜破れたけど、それよりずっと……ふあぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「き、気持ちよくてぇっ<emoji=heart04>　ふわっ<emoji=heart04>　っていうか……ま、まだ動いてないのにこんなっ……<emoji=heart04>　ふぅぅっ！　これ、動いたらっ……絶対<emoji=heart04>　もっと気持ちよくっ……はぁぁっ<emoji=heart04>」
line = "「き、気持ちよくてぇっ<emoji=heart04>　ふわっ<emoji=heart04>　っていうか……ま、まだ動いてないのにこんなっ……<emoji=heart04>　ふぅぅっ！　これ、動いたらっ……絶対<emoji=heart04>　もっと気持ちよくっ……はぁぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「っ……ヴィーナス、そんなこと言われたら！」
line = "「っ……ヴィーナス、そんなこと言われたら！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、待ってっ<emoji=heart04>　ま、まだ心の準備が……あっ、んあっ<emoji=heart04>　ふあぁぁぁあああ──っ<emoji=heart04>！？」
line = "「あっ、待ってっ<emoji=heart04>　ま、まだ心の準備が……あっ、んあっ<emoji=heart04>　ふあぁぁぁあああ──っ<emoji=heart04>！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、んあぁっ<emoji=heart04>　ダメぇ！　気持ちいい<emoji=heart04>　おま○こ気持ちいいのっ<emoji=heart04>！　ふあぁぁっ、おち○ちん凄いぃっ！」
line = "「あっ、んあぁっ<emoji=heart04>　ダメぇ！　気持ちいい<emoji=heart04>　おま○こ気持ちいいのっ<emoji=heart04>！　ふあぁぁっ、おち○ちん凄いぃっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「出たり入ったり、ぬぽぬぽ気持ちいいよぉっ<emoji=heart04>　んあぁぁぁっ、んうっ、ふあぁぁんっ<emoji=heart04>！」
line = "「出たり入ったり、ぬぽぬぽ気持ちいいよぉっ<emoji=heart04>　んあぁぁぁっ、んうっ、ふあぁぁんっ<emoji=heart04>！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あぁんっ<emoji=heart04>　頭撫でながら<emoji=heart04>　ピストンずるいぃっ、ふあぁっ<emoji=heart04>！　心と体、同時に気持ちよくなっちゃうっ<emoji=heart04>　はぁんっ……あっ、撫でるの止めちゃダメっ<emoji=heart04>　もっとぉ……！」
line = "「あぁんっ<emoji=heart04>　頭撫でながら<emoji=heart04>　ピストンずるいぃっ、ふあぁっ<emoji=heart04>！　心と体、同時に気持ちよくなっちゃうっ<emoji=heart04>　はぁんっ……あっ、撫でるの止めちゃダメっ<emoji=heart04>　もっとぉ……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ<emoji=heart04>　んあっ<emoji=heart04>　あぁぁんっ<emoji=heart04>！　頭撫でるの好きっ<emoji=heart04>　ふあぁっ、おち○ちんで内側撫でられるのも好きぃっ<emoji=heart04>　ふあぁぁっ、あっ、いいっ、そこ気持ちいいのぉ<emoji=heart04>」
line = "「あっ<emoji=heart04>　んあっ<emoji=heart04>　あぁぁんっ<emoji=heart04>！　頭撫でるの好きっ<emoji=heart04>　ふあぁっ、おち○ちんで内側撫でられるのも好きぃっ<emoji=heart04>　ふあぁぁっ、あっ、いいっ、そこ気持ちいいのぉ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふあぁんっ、おま○こ幸せで絡み付いちゃうっ<emoji=heart04>　あふぅんっ……おち○ちんのこと、もう好きになっちゃってるっ<emoji=heart04>　んあぁぁぁっ、これっ、絶対相性良いのぉ……<emoji=heart04>！」
line = "「ふあぁんっ、おま○こ幸せで絡み付いちゃうっ<emoji=heart04>　あふぅんっ……おち○ちんのこと、もう好きになっちゃってるっ<emoji=heart04>　んあぁぁぁっ、これっ、絶対相性良いのぉ……<emoji=heart04>！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「キス、キスもしてぇっ<emoji=heart04>　……お口の方も愛して欲しいのぉっ<emoji=heart04>　んあっ、んちゅっ<emoji=heart04>　くちゅるっ、んぷっ、ちゅるっ……<emoji=heart04>」
line = "「キス、キスもしてぇっ<emoji=heart04>　……お口の方も愛して欲しいのぉっ<emoji=heart04>　んあっ、んちゅっ<emoji=heart04>　くちゅるっ、んぷっ、ちゅるっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「はぁむ<emoji=heart04>　んくっ、ちゅ、ちゅ<emoji=heart04>　ちゅるるっ<emoji=heart04>　んくちゅ、ちゅぶぶっ……<emoji=heart04>　んはっ、はあっ、んっ、んんっ<emoji=heart04>　……んちゅる、んはっ、んちゅう……っ<emoji=heart04>」
line = "「はぁむ<emoji=heart04>　んくっ、ちゅ、ちゅ<emoji=heart04>　ちゅるるっ<emoji=heart04>　んくちゅ、ちゅぶぶっ……<emoji=heart04>　んはっ、はあっ、んっ、んんっ<emoji=heart04>　……んちゅる、んはっ、んちゅう……っ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「もっ、もっと、あんっ<emoji=heart04>　もっとっ……んくちゅ<emoji=heart04>　ちゅぷ、ちゅるるっ……んはぁっ、もっと、んちゅっ<emoji=heart04>　こっち来て……っ<emoji=heart04>　もっと、ちゅぷるっ、激しく、してっ……<emoji=heart04>」
line = "「もっ、もっと、あんっ<emoji=heart04>　もっとっ……んくちゅ<emoji=heart04>　ちゅぷ、ちゅるるっ……んはぁっ、もっと、んちゅっ<emoji=heart04>　こっち来て……っ<emoji=heart04>　もっと、ちゅぷるっ、激しく、してっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「っ……ヴィーナスッ！」
line = "「っ……ヴィーナスッ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んああぁぁぁっ<emoji=heart04>　おち○ちん奥まで来たあぁぁぁ～～っ<emoji=heart04>！　あんっ<emoji=heart04>　あんっ<emoji=heart04>　もっと私を、んあぁっ、求めていいからっ……私は、あなたのものなんだからぁっ<emoji=heart04>」
line = "「んああぁぁぁっ<emoji=heart04>　おち○ちん奥まで来たあぁぁぁ～～っ<emoji=heart04>！　あんっ<emoji=heart04>　あんっ<emoji=heart04>　もっと私を、んあぁっ、求めていいからっ……私は、あなたのものなんだからぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ<emoji=heart04>　あっ<emoji=heart04>　おま○こ奥しゅごいっ<emoji=heart04>　子宮の入り口トントンされるの気持ち良いっ<emoji=heart04>　あんっ！　ふあぁっ、はぁっ、んああっ<emoji=heart04>　あっ、はぁんっ、ふあぁぁぁんっ<emoji=heart04>」
line = "「あっ<emoji=heart04>　あっ<emoji=heart04>　おま○こ奥しゅごいっ<emoji=heart04>　子宮の入り口トントンされるの気持ち良いっ<emoji=heart04>　あんっ！　ふあぁっ、はぁっ、んああっ<emoji=heart04>　あっ、はぁんっ、ふあぁぁぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「こっ、これしゅきっ<emoji=heart04>　子宮口とおち○ちんキスするのしゅきっ<emoji=heart04>　気持ちいいのっ、あぁぁんっ！　ふあぁぁぁっ、あっ、あっ、んあぁぁぁっ！」
line = "「こっ、これしゅきっ<emoji=heart04>　子宮口とおち○ちんキスするのしゅきっ<emoji=heart04>　気持ちいいのっ、あぁぁんっ！　ふあぁぁぁっ、あっ、あっ、んあぁぁぁっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「降りてきちゃうっ<emoji=heart04>　んあぁっ、子宮がおち○ちん好きになって<emoji=heart04>　はぅんっ！　自分からキスしたくて、降りてきちゃってるのぉっ<emoji=heart04>　んあぁぁんっ！」
line = "「降りてきちゃうっ<emoji=heart04>　んあぁっ、子宮がおち○ちん好きになって<emoji=heart04>　はぅんっ！　自分からキスしたくて、降りてきちゃってるのぉっ<emoji=heart04>　んあぁぁんっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あああ<emoji=heart04>　気持ちいいっ<emoji=heart04>　全部気持ちいいのっ、ふあぁぁっ<emoji=heart04>　あなたに触れられた部分、どこも気持ちよくて幸せになのぉ<emoji=heart04>　あっ、んあぁ、はあぁぁんっ！」
line = "「あああ<emoji=heart04>　気持ちいいっ<emoji=heart04>　全部気持ちいいのっ、ふあぁぁっ<emoji=heart04>　あなたに触れられた部分、どこも気持ちよくて幸せになのぉ<emoji=heart04>　あっ、んあぁ、はあぁぁんっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ねえっ、あなたも気持ちいいっ<emoji=heart04>？　ふあぁんっ<emoji=heart04>　私の中っ、気持ちいいっ？　んはっ、あっ<emoji=heart04>　んっ、ふあぁっ、んあぁぁっ！」
line = "「ねえっ、あなたも気持ちいいっ<emoji=heart04>？　ふあぁんっ<emoji=heart04>　私の中っ、気持ちいいっ？　んはっ、あっ<emoji=heart04>　んっ、ふあぁっ、んあぁぁっ！」"

[[dialogue]]
speaker = "クロト"
# 「気持ちよすぎてっ……！　ヴィーナスの心だけじゃなくっ、体も俺のものにしたいっ！」
line = "「気持ちよすぎてっ……！　ヴィーナスの心だけじゃなくっ、体も俺のものにしたいっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んああっ<emoji=heart04>　してぇっ<emoji=heart04>！　好きにしていいからっ<emoji=heart04>　あぁんっ<emoji=heart04>　私をもっと、はあぁんっ、あなた専用にしてっ<emoji=heart04>！　ふあぁぁぁっ！」
line = "「んああっ<emoji=heart04>　してぇっ<emoji=heart04>！　好きにしていいからっ<emoji=heart04>　あぁんっ<emoji=heart04>　私をもっと、はあぁんっ、あなた専用にしてっ<emoji=heart04>！　ふあぁぁぁっ！」"

[[dialogue]]
speaker = "unk"
# 目の前にいる最高の女の子が『自分専用』になる。
line = "目の前にいる最高の女の子が『自分専用』になる。"

[[dialogue]]
speaker = "unk"
# その響きが俺の興奮を最高潮にし、射精欲を掻き立てる。
line = "その響きが俺の興奮を最高潮にし、射精欲を掻き立てる。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふああぁぁぁっ<emoji=heart04>！　本気ピストンきたあぁぁぁ──っ<emoji=heart04><emoji=heart04><emoji=heart04>　あっ、あっ、んあぁっ！　気持ちよしゅぎるっ<emoji=heart04>　んあぁっ、もっと、もっと奥突きあげてぇっ<emoji=heart04>」
line = "「ふああぁぁぁっ<emoji=heart04>！　本気ピストンきたあぁぁぁ──っ<emoji=heart04><emoji=heart04><emoji=heart04>　あっ、あっ、んあぁっ！　気持ちよしゅぎるっ<emoji=heart04>　んあぁっ、もっと、もっと奥突きあげてぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んあぁぁんっ、しゅきっ<emoji=heart04>　おち○ちん、しゅきなのぉっ<emoji=heart04>！　こんな気持ちいの知ったら、戻れないぃっ！　ふあぁぁんっ<emoji=heart04>　あなたのおち○ちん最高なのぉ<emoji=heart04>」
line = "「んあぁぁんっ、しゅきっ<emoji=heart04>　おち○ちん、しゅきなのぉっ<emoji=heart04>！　こんな気持ちいの知ったら、戻れないぃっ！　ふあぁぁんっ<emoji=heart04>　あなたのおち○ちん最高なのぉ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んはぁっ<emoji=heart04>　はっ、ああぁんっ！　んっ、あっ、んああぁぁぁっ<emoji=heart04>！　もっと、もっとぉっ<emoji=heart04>　そこっ、奥っ、奥いいのぉっ、おち○ちんキス気持ちいい～～っ<emoji=heart04>」
line = "「んはぁっ<emoji=heart04>　はっ、ああぁんっ！　んっ、あっ、んああぁぁぁっ<emoji=heart04>！　もっと、もっとぉっ<emoji=heart04>　そこっ、奥っ、奥いいのぉっ、おち○ちんキス気持ちいい～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふあぁっ<emoji=heart04>　はぁっ、んはぁっ、ふあぁぁぁんっ<emoji=heart04>！　おち○ちん<emoji=heart04>　んあぁっ、大きくなってきたっ<emoji=heart04>　先っぽ、膨らんでるのがわかるっ<emoji=heart04>　……ふあぁっ！」
line = "「ふあぁっ<emoji=heart04>　はぁっ、んはぁっ、ふあぁぁぁんっ<emoji=heart04>！　おち○ちん<emoji=heart04>　んあぁっ、大きくなってきたっ<emoji=heart04>　先っぽ、膨らんでるのがわかるっ<emoji=heart04>　……ふあぁっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んっ、射精っ<emoji=heart04>　んああっ、射精するのねっ？　きてっ<emoji=heart04>　私も凄く気持ちいいの登って来てるっ<emoji=heart04>　ふあぁぁっ、お腹の中いっぱい来てぇっ<emoji=heart04>　んあぁぁんっ！」
line = "「んっ、射精っ<emoji=heart04>　んああっ、射精するのねっ？　きてっ<emoji=heart04>　私も凄く気持ちいいの登って来てるっ<emoji=heart04>　ふあぁぁっ、お腹の中いっぱい来てぇっ<emoji=heart04>　んあぁぁんっ！」"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナス、奥に射精すぞ！　絶対に俺専用にするっ！」
line = "「ヴィーナス、奥に射精すぞ！　絶対に俺専用にするっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あぁんっ<emoji=heart04>　なってるっ、もうなってるからぁっ<emoji=heart04>　んあぁぁっ、子宮にいっぱい子種注いで、トドメさしてぇっ<emoji=heart04>　ふあぁぁぁんっ！」
line = "「あぁんっ<emoji=heart04>　なってるっ、もうなってるからぁっ<emoji=heart04>　んあぁぁっ、子宮にいっぱい子種注いで、トドメさしてぇっ<emoji=heart04>　ふあぁぁぁんっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、くるっ<emoji=heart04>　しゅごいアクメくりゅっ！　んああぁぁぁっ<emoji=heart04>　気持ち良いの一番上まで登ってくりゅうぅぅぅ～～っ<emoji=heart04><emoji=heart04>！」
line = "「あっ、くるっ<emoji=heart04>　しゅごいアクメくりゅっ！　んああぁぁぁっ<emoji=heart04>　気持ち良いの一番上まで登ってくりゅうぅぅぅ～～っ<emoji=heart04><emoji=heart04>！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふあぁぁぁっ<emoji=heart04>　イクっ、もうイッちゃうっ<emoji=heart04>！　おち○ちんも来てっ<emoji=heart04>！　私と一緒に射精してぇぇぇっ！」
line = "「ふあぁぁぁっ<emoji=heart04>　イクっ、もうイッちゃうっ<emoji=heart04>！　おち○ちんも来てっ<emoji=heart04>！　私と一緒に射精してぇぇぇっ！」"

[[dialogue]]
speaker = "unk"
# クロト「好きだ、ヴィーナスッ！！！」
line = "クロト「好きだ、ヴィーナスッ！！！」"

[[dialogue]]
speaker = "unk"
# 俺はペニスを一番奥まで突き入れ、溜まりに溜まった欲望を思いっきり吐き出した。
line = "俺はペニスを一番奥まで突き入れ、溜まりに溜まった欲望を思いっきり吐き出した。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あああああっ<emoji=heart04>　すきっ<emoji=heart04>　私もっ<emoji=heart04>　すきっ<emoji=heart04>　すきっ<emoji=heart04>　すきっ<emoji=heart04>　好きっ<emoji=heart04>　好きっ<emoji=heart04>　しゅきぃぃ<emoji=heart04>　ふぁぁぁぁっ<emoji=heart04><emoji=heart04>」
line = "「あああああっ<emoji=heart04>　すきっ<emoji=heart04>　私もっ<emoji=heart04>　すきっ<emoji=heart04>　すきっ<emoji=heart04>　すきっ<emoji=heart04>　好きっ<emoji=heart04>　好きっ<emoji=heart04>　しゅきぃぃ<emoji=heart04>　ふぁぁぁぁっ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「イクイクイクぅぅぅっ<emoji=heart04>！　中に出されて、イックうぅぅぅ──────っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「イクイクイクぅぅぅっ<emoji=heart04>！　中に出されて、イックうぅぅぅ──────っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「っ…………ふあぁぁぁぁあああぁぁぁぁあああああああっっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「っ…………ふあぁぁぁぁあああぁぁぁぁあああああああっっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 魂が抜けてしまいそうな快楽に、俺は射精中も堪らずヴィーナスへ腰を振った。
line = "魂が抜けてしまいそうな快楽に、俺は射精中も堪らずヴィーナスへ腰を振った。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、はぁっ……<emoji=heart04>　んんっ……ふあぁっ<emoji=heart04>　一緒に、イケたぁ……えへへぇ<emoji=heart04>」
line = "「あっ、はぁっ……<emoji=heart04>　んんっ……ふあぁっ<emoji=heart04>　一緒に、イケたぁ……えへへぇ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んっ、はぁ……<emoji=heart04>　まだ出てる……すごいぃ<emoji=heart04>　んふっ、そんなに私の中、気持ち良かったぁ……？」
line = "「んっ、はぁ……<emoji=heart04>　まだ出てる……すごいぃ<emoji=heart04>　んふっ、そんなに私の中、気持ち良かったぁ……？」"

[[dialogue]]
speaker = "クロト"
# 「人生で一番射精した……」
line = "「人生で一番射精した……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうなんだぁ……えへへっ、嬉しい<emoji=heart04>　私も、すっごく気持ちよかったわ……魂が飛んでっちゃいそうなくらい<emoji=heart04>」
line = "「そうなんだぁ……えへへっ、嬉しい<emoji=heart04>　私も、すっごく気持ちよかったわ……魂が飛んでっちゃいそうなくらい<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「セックスって、こんなに凄かったのね……。私、本当にあなた専用の体にされちゃったかも<emoji=heart04>」
line = "「セックスって、こんなに凄かったのね……。私、本当にあなた専用の体にされちゃったかも<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふふっ。……もちろん、あなたも私専用よ？　こんな幸せな時間、私が独り占めするべきなんだから♪」
line = "「ふふっ。……もちろん、あなたも私専用よ？　こんな幸せな時間、私が独り占めするべきなんだから♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ん……ねえ、また頭撫でて？　私、初めてのセックス頑張ったんだから……<emoji=heart04>」
line = "「ん……ねえ、また頭撫でて？　私、初めてのセックス頑張ったんだから……<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んふぅ<emoji=heart04>　んっ、んんっ……んふふっ<emoji=heart04>　やっぱり、こうやってあなたに甘えてる時間が１番好き……♪」
line = "「んふぅ<emoji=heart04>　んっ、んんっ……んふふっ<emoji=heart04>　やっぱり、こうやってあなたに甘えてる時間が１番好き……♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ね……まだ時間あるわよ？　今日の星徒会室は貸し切りなんだから、この時間は有効活用するべきだと思わない<emoji=heart04>？」
line = "「ね……まだ時間あるわよ？　今日の星徒会室は貸し切りなんだから、この時間は有効活用するべきだと思わない<emoji=heart04>？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なにより、あなたのおち○ちん、また大きくなってるの、気付いてるんだから<emoji=heart04>」
line = "「なにより、あなたのおち○ちん、また大きくなってるの、気付いてるんだから<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そう言って、ヴィーナスに唇を奪われる。
line = "そう言って、ヴィーナスに唇を奪われる。"

[[dialogue]]
speaker = "ヴィーナス"
# 「んっ、んちゅっ、んんっ……ぷはぁ<emoji=heart04>　ほら、あなたの専用おま○こ、いっぱい可愛がって<emoji=heart04>」
line = "「んっ、んちゅっ、んんっ……ぷはぁ<emoji=heart04>　ほら、あなたの専用おま○こ、いっぱい可愛がって<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 耳元でそんな風に囁かれては、セックス覚えたての若い男子が我慢できるはずもなく。
line = "耳元でそんな風に囁かれては、セックス覚えたての若い男子が我慢できるはずもなく。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あんっ<emoji=heart04>　おち○ちん、また奥にきたぁっ<emoji=heart04>」
line = "「あんっ<emoji=heart04>　おち○ちん、また奥にきたぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 性欲の赴くまま、日が暮れるまでヴィーナスと交わり続けるのだった。
line = "性欲の赴くまま、日が暮れるまでヴィーナスと交わり続けるのだった。"
