[[dialogue]]
speaker = "unk"
# 第３話,謎の声,P
line = "第３話,謎の声,P"

[[dialogue]]
speaker = "環"
# 「会長、勝負だー！」
line = "「会長、勝負だー！」"

[[dialogue]]
speaker = "環"
# 「……って、全然驚いてないじゃん。そこはもっと驚いてよ～」
line = "「……って、全然驚いてないじゃん。そこはもっと驚いてよ～」"

[[dialogue]]
speaker = "環"
# 「星術なら俺が勝つけど？　って顔してる会長に説明しよう！」
line = "「星術なら俺が勝つけど？　って顔してる会長に説明しよう！」"

[[dialogue]]
speaker = "環"
# 「ほら、ボクまだプリマステラにもなってないじゃない？　だから星騎士の頂点に立つ星徒会長様に、ご指導ご鞭撻を賜って強くなろうと思ってさ」
line = "「ほら、ボクまだプリマステラにもなってないじゃない？　だから星騎士の頂点に立つ星徒会長様に、ご指導ご鞭撻を賜って強くなろうと思ってさ」"

[[dialogue]]
speaker = "環"
# 「……ＯＫ？　ありがとー！　今日はバイトもないし、いっぱい付き合ってもらうよ！」
line = "「……ＯＫ？　ありがとー！　今日はバイトもないし、いっぱい付き合ってもらうよ！」"

[[dialogue]]
speaker = "環"
# 「はぁ、はぁ……もう動けない……ちょっと休憩……」
line = "「はぁ、はぁ……もう動けない……ちょっと休憩……」"

[[dialogue]]
speaker = "環"
# 「も～っ、いつの間にかこんなに強くなったのさ～！　転入生なのに、一緒にバイトしてたのに……ずるーいっ」
line = "「も～っ、いつの間にかこんなに強くなったのさ～！　転入生なのに、一緒にバイトしてたのに……ずるーいっ」"

[[dialogue]]
speaker = "環"
# 「あはははっ！　でも叫んだらスッキリしたや。特訓付き合ってくれてありがとね」
line = "「あはははっ！　でも叫んだらスッキリしたや。特訓付き合ってくれてありがとね」"

[[dialogue]]
speaker = "環"
# 「そういえばさ、御前試合でヴィーナスに勝ったあの力ってなんだったの？　ヴィーナスは魔王がどうとか言ってた気がするけど」
line = "「そういえばさ、御前試合でヴィーナスに勝ったあの力ってなんだったの？　ヴィーナスは魔王がどうとか言ってた気がするけど」"

[[dialogue]]
speaker = "環"
# 「……ふーん。本人でもわからないんだ。しかもあれは自由には使えないと」
line = "「……ふーん。本人でもわからないんだ。しかもあれは自由には使えないと」"

[[dialogue]]
speaker = "環"
# 「それじゃあヴィーナスにちゃんと勝ったとは言えないかもね。あの力を自力で出せるようになったら会長として一人前かな」
line = "「それじゃあヴィーナスにちゃんと勝ったとは言えないかもね。あの力を自力で出せるようになったら会長として一人前かな」"

[[dialogue]]
speaker = "環"
# 「ボクはプリマステラに。会長は自分の力を使いこなせるように。お互い頑張って強くなっていこうね」
line = "「ボクはプリマステラに。会長は自分の力を使いこなせるように。お互い頑張って強くなっていこうね」"

[[dialogue]]
speaker = "環"
# 「でも新星学園でまた会えて良かったな。あんなにバイト頑張ってたのに、ぱったりやめちゃったからどうしたのか気になってたんだ」
line = "「でも新星学園でまた会えて良かったな。あんなにバイト頑張ってたのに、ぱったりやめちゃったからどうしたのか気になってたんだ」"

[[dialogue]]
speaker = "環"
# 「そもそも、新星学園に転入するためにバイトしてたんだよね。そんな話聞いてなかったから驚いちゃった。もしかしたら忘れてるだけかもしれないけど」
line = "「そもそも、新星学園に転入するためにバイトしてたんだよね。そんな話聞いてなかったから驚いちゃった。もしかしたら忘れてるだけかもしれないけど」"

[[dialogue]]
speaker = "環"
# 「いや～、大変だったけど楽しかったな。コンビニはけっこうやること多いし、喫茶店ではコーヒーひっくり返してめちゃくちゃ謝ったね」
line = "「いや～、大変だったけど楽しかったな。コンビニはけっこうやること多いし、喫茶店ではコーヒーひっくり返してめちゃくちゃ謝ったね」"

[[dialogue]]
speaker = "環"
# 「そうだ、着ぐるみもヤバかったよね。あれに比べたらモンスターの攻撃なんて大したことないくらい。でも休憩時間に食べるお弁当はおいしかったなぁ……」
line = "「そうだ、着ぐるみもヤバかったよね。あれに比べたらモンスターの攻撃なんて大したことないくらい。でも休憩時間に食べるお弁当はおいしかったなぁ……」"

[[dialogue]]
speaker = "環"
# 「ねぇ……知ってる？」
line = "「ねぇ……知ってる？」"

[[dialogue]]
speaker = "環"
# 「ボク……キミのことずっと見てたんだよ？」
line = "「ボク……キミのことずっと見てたんだよ？」"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "環"
# 「どしたの？　顔が赤いよ？」
line = "「どしたの？　顔が赤いよ？」"

[[dialogue]]
speaker = "環"
# 「おや？　おやおや？　もしかしてボクにときめいちゃった？　しょうがないよね～、ボク美少女だから♪」
line = "「おや？　おやおや？　もしかしてボクにときめいちゃった？　しょうがないよね～、ボク美少女だから♪」"

[[dialogue]]
speaker = "環"
# 「……あれ？　今のはツッコむところだよ？　その反応だとマジみたいじゃん。恥ずかしいから何とか言ってよ──」
line = "「……あれ？　今のはツッコむところだよ？　その反応だとマジみたいじゃん。恥ずかしいから何とか言ってよ──」"

[[dialogue]]
speaker = "環"
# 「──！　モンスター……アステラも出てるっぽいね」
line = "「──！　モンスター……アステラも出てるっぽいね」"

[[dialogue]]
speaker = "環"
# 「ごめん。ボクも行きたかったんだけど、もう戦える星力がないや」
line = "「ごめん。ボクも行きたかったんだけど、もう戦える星力がないや」"

[[dialogue]]
speaker = "unk"
# 任せてくれ
line = "任せてくれ"

[[dialogue]]
speaker = "環"
# 「うん、お願い。モンスターなんて会長パワーでぶっ飛ばしちゃって！」
line = "「うん、お願い。モンスターなんて会長パワーでぶっ飛ばしちゃって！」"

[[dialogue]]
speaker = "unk"
# だが──
line = "だが──"

[[dialogue]]
speaker = "unk"
# 強い……！
line = "強い……！"

[[dialogue]]
speaker = "unk"
# やられ──
line = "やられ──"

[[dialogue]]
speaker = "？？？"
# 『うーん……キミも力を付けてきたと思ったんだけど、このレベルはまだ早かったかな。ごめんごめん』
line = "『うーん……キミも力を付けてきたと思ったんだけど、このレベルはまだ早かったかな。ごめんごめん』"

[[dialogue]]
speaker = "？？？"
# 『でも強くならないと大切なものは守れないよ。忘れないでね、魔王』
line = "『でも強くならないと大切なものは守れないよ。忘れないでね、魔王』"

[[dialogue]]
speaker = "サーシャ"
# 「あ～、目が覚めたかしら～？　私たちが駆け付けたら、モンスターもアステラも消えてて会長が倒れてたの～」
line = "「あ～、目が覚めたかしら～？　私たちが駆け付けたら、モンスターもアステラも消えてて会長が倒れてたの～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうよ、他にはな～にもなくてびっくりしたんだから！」
line = "「そうよ、他にはな～にもなくてびっくりしたんだから！」"

[[dialogue]]
speaker = "環"
# 「ごめん、会長……」
line = "「ごめん、会長……」"

[[dialogue]]
speaker = "環"
# 「ボクがもっと強かったらキミを１人にさせなかったのに……本当にごめんね」
line = "「ボクがもっと強かったらキミを１人にさせなかったのに……本当にごめんね」"

[[dialogue]]
speaker = "環"
# 「ううん……会長が無事でよかった」
line = "「ううん……会長が無事でよかった」"

[[dialogue]]
speaker = "unk"
# あのモンスターは普通より数段強力だった。
line = "あのモンスターは普通より数段強力だった。"

[[dialogue]]
speaker = "unk"
# だが俺が本当に魔王であるなら、倒せて当然の敵だったんだろう。
line = "だが俺が本当に魔王であるなら、倒せて当然の敵だったんだろう。"

[[dialogue]]
speaker = "unk"
# しかし薄れゆく意識の中で聞こえてきたのは、いったい誰の声だったんだ……？
line = "しかし薄れゆく意識の中で聞こえてきたのは、いったい誰の声だったんだ……？"
