[[dialogue]]
speaker = "unk"
# 第２話,寒がりソフィア,P
line = "第２話,寒がりソフィア,P"

[[dialogue]]
speaker = "ソフィア"
# 「またパトロールにお付き合いいただいて、ありがとうございま──」
line = "「またパトロールにお付き合いいただいて、ありがとうございま──」"

[[dialogue]]
speaker = "ソフィア"
# 「くちゅんっ」
line = "「くちゅんっ」"

[[dialogue]]
speaker = "ソフィア"
# 「ああいえ、風邪ではないのでご心配なく。少し鼻がムズムズしただけですから」
line = "「ああいえ、風邪ではないのでご心配なく。少し鼻がムズムズしただけですから」"

[[dialogue]]
speaker = "ソフィア"
# 「ブルブル、ガクガク……寒くない、寒くない……」
line = "「ブルブル、ガクガク……寒くない、寒くない……」"

[[dialogue]]
speaker = "unk"
# 本当に寒くない？
line = "本当に寒くない？"

[[dialogue]]
speaker = "ソフィア"
# 「だって寒いって言ったら余計に寒くなるじゃないですか！」
line = "「だって寒いって言ったら余計に寒くなるじゃないですか！」"

[[dialogue]]
speaker = "unk"
# （やっぱり寒いんだ）
line = "（やっぱり寒いんだ）"

[[dialogue]]
speaker = "ソフィア"
# 「私が生まれたのは、魔界のレゾフという町でした。レゾフはこの流星市国よりずっと寒さが厳しくて……極寒と言っても過言ではありません。ソーコールドです」
line = "「私が生まれたのは、魔界のレゾフという町でした。レゾフはこの流星市国よりずっと寒さが厳しくて……極寒と言っても過言ではありません。ソーコールドです」"

[[dialogue]]
speaker = "ソフィア"
# 「あのままレゾフに住んでいたら、今頃凍え死にしていてもおかしくありませんでした」
line = "「あのままレゾフに住んでいたら、今頃凍え死にしていてもおかしくありませんでした」"

[[dialogue]]
speaker = "ソフィア"
# 「たとえ故郷であっても、こんなに寒いところにずっと住むなんて耐えられない。そう思って人間界に来ました」
line = "「たとえ故郷であっても、こんなに寒いところにずっと住むなんて耐えられない。そう思って人間界に来ました」"

[[dialogue]]
speaker = "ソフィア"
# 「しかしレゾフよりはず～っと、ず～っとマシですが、人間界も万全とは言えません」
line = "「しかしレゾフよりはず～っと、ず～っとマシですが、人間界も万全とは言えません」"

[[dialogue]]
speaker = "ソフィア"
# 「皆さんが平気そうにしているのが不思議で不思議で……私に安住の地はないのですか？」
line = "「皆さんが平気そうにしているのが不思議で不思議で……私に安住の地はないのですか？」"

[[dialogue]]
speaker = "unk"
# だからずっと厚着してるんだ
line = "だからずっと厚着してるんだ"

[[dialogue]]
speaker = "ソフィア"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "ソフィア"
# 「……まぁ、そうですね。この外套がなければ、人間界でももっとつらかったしれません」
line = "「……まぁ、そうですね。この外套がなければ、人間界でももっとつらかったしれません」"

[[dialogue]]
speaker = "フィオナ"
# 「ソフィア？　緋宮会長も？」
line = "「ソフィア？　緋宮会長も？」"

[[dialogue]]
speaker = "ソフィア"
# 「フィオナ会長！？　どうしてここに……あ、そういえば教皇様の公務があるんでしたね」
line = "「フィオナ会長！？　どうしてここに……あ、そういえば教皇様の公務があるんでしたね」"

[[dialogue]]
speaker = "フィオナ"
# 「うん、その付き添いで私も出席してたの。ソフィアはこの前言ってたパトロール？」
line = "「うん、その付き添いで私も出席してたの。ソフィアはこの前言ってたパトロール？」"

[[dialogue]]
speaker = "ソフィア"
# 「はい、新星学園の会長さんと一緒に街を巡回していました」
line = "「はい、新星学園の会長さんと一緒に街を巡回していました」"

[[dialogue]]
speaker = "フィオナ"
# 「さすがソフィア。星徒会役員の鑑だね」
line = "「さすがソフィア。星徒会役員の鑑だね」"

[[dialogue]]
speaker = "ソフィア"
# 「いえ、そんな……言い過ぎです」
line = "「いえ、そんな……言い過ぎです」"

[[dialogue]]
speaker = "unk"
# （すごく嬉しそう）
line = "（すごく嬉しそう）"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長もソフィアに同行してくださってありがとうございます」
line = "「緋宮会長もソフィアに同行してくださってありがとうございます」"

[[dialogue]]
speaker = "フィオナ"
# 「私も一緒にパトロールしたいのはやまやまだけど、予定があるからもう行かないと。頑張るのはいいけど、無理はしないでね」
line = "「私も一緒にパトロールしたいのはやまやまだけど、予定があるからもう行かないと。頑張るのはいいけど、無理はしないでね」"

[[dialogue]]
speaker = "ソフィア"
# 「はいっ」
line = "「はいっ」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長もよろしくお願いします。それでは」
line = "「緋宮会長もよろしくお願いします。それでは」"

[[dialogue]]
speaker = "ソフィア"
# 「えへへ……。やはりフィオナ会長は最高の星徒会長です。流星学園に来て良かった……」
line = "「えへへ……。やはりフィオナ会長は最高の星徒会長です。流星学園に来て良かった……」"

[[dialogue]]
speaker = "ソフィア"
# 「ああいえ、決してあなたを貶しているわけではありません。ただフィオナ会長が素晴らしいのは厳然たる事実ですから」
line = "「ああいえ、決してあなたを貶しているわけではありません。ただフィオナ会長が素晴らしいのは厳然たる事実ですから」"

[[dialogue]]
speaker = "サーシャ"
# 「あら？　そこにいるのは……」
line = "「あら？　そこにいるのは……」"

[[dialogue]]
speaker = "ソフィア"
# 「姉さん！？」
line = "「姉さん！？」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふっ、奇遇ね～。もしかして２人でデート？」
line = "「ふふっ、奇遇ね～。もしかして２人でデート？」"

[[dialogue]]
speaker = "ソフィア"
# 「違いますっ！　時間に余裕があったのでパトロールしてたんですっ」
line = "「違いますっ！　時間に余裕があったのでパトロールしてたんですっ」"

[[dialogue]]
speaker = "サーシャ"
# 「そうなんだ、偉いわね～。会長くん頭撫でてあげる～。ナデナデ」
line = "「そうなんだ、偉いわね～。会長くん頭撫でてあげる～。ナデナデ」"

[[dialogue]]
speaker = "ソフィア"
# 「はぁ……姉さんの相手をするのも大変ですね。いつもそんな感じなんですか？」
line = "「はぁ……姉さんの相手をするのも大変ですね。いつもそんな感じなんですか？」"

[[dialogue]]
speaker = "サーシャ"
# 「そうねぇ、かわいいから、けっこうナデナデしてるかも～」
line = "「そうねぇ、かわいいから、けっこうナデナデしてるかも～」"

[[dialogue]]
speaker = "ソフィア"
# 「うー……」
line = "「うー……」"

[[dialogue]]
speaker = "サーシャ"
# 「ソフィも撫でてあげるわね～」
line = "「ソフィも撫でてあげるわね～」"

[[dialogue]]
speaker = "ソフィア"
# 「結構です。もう子どもじゃありませんから」
line = "「結構です。もう子どもじゃありませんから」"

[[dialogue]]
speaker = "サーシャ"
# 「あらそう……お姉ちゃん残念。じゃあソフィのことよろしくね」
line = "「あらそう……お姉ちゃん残念。じゃあソフィのことよろしくね」"

[[dialogue]]
speaker = "ソフィア"
# 「だから子どもじゃありませんってば。むー」
line = "「だから子どもじゃありませんってば。むー」"

[[dialogue]]
speaker = "ソフィア"
# 「ほら行きましょうっ。パトロールなんですから、姉さんにデレデレしていてはいけませんよ」
line = "「ほら行きましょうっ。パトロールなんですから、姉さんにデレデレしていてはいけませんよ」"
