[[dialogue]]
speaker = "unk"
# 第３話,お姉ちゃんとオイル塗り,P
line = "第３話,お姉ちゃんとオイル塗り,P"

[[dialogue]]
speaker = "unk"
# とある休日。俺はサーシャさんとデートで、リゾート結界にやって来ていた――
line = "とある休日。俺はサーシャさんとデートで、リゾート結界にやって来ていた――"

[[dialogue]]
speaker = "サーシャ"
# 「それじゃあ、海で水遊びする前に～」
line = "「それじゃあ、海で水遊びする前に～」"

[[dialogue]]
speaker = "サーシャ"
# 「お姉ちゃんに……日焼け止めオイル、塗って欲しいわ<emoji=heart04>」
line = "「お姉ちゃんに……日焼け止めオイル、塗って欲しいわ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ちょっ！？　いきなり脱ぐなんて……！？
line = "ちょっ！？　いきなり脱ぐなんて……！？"

[[dialogue]]
speaker = "サーシャ"
# 「うふふっ、水着の紐をちょっと緩めるだけだから、大丈夫よ～」
line = "「うふふっ、水着の紐をちょっと緩めるだけだから、大丈夫よ～」"

[[dialogue]]
speaker = "サーシャ"
# 「それに、脱がないとオイル、ちゃんと塗れないでしょう……？」
line = "「それに、脱がないとオイル、ちゃんと塗れないでしょう……？」"

[[dialogue]]
speaker = "サーシャ"
# 「リップルちゃんの海の家が繁盛しているって聞いたから、人で賑わっている方のビーチに来たけど――」
line = "「リップルちゃんの海の家が繁盛しているって聞いたから、人で賑わっている方のビーチに来たけど――」"

[[dialogue]]
speaker = "サーシャ"
# 「この辺りは、探検してて見つけた人気のない場所で、周りに人も居ないし……恋人なんだから、別に恥ずかしくないでしょう？」
line = "「この辺りは、探検してて見つけた人気のない場所で、周りに人も居ないし……恋人なんだから、別に恥ずかしくないでしょう？」"

[[dialogue]]
speaker = "サーシャ"
# 「それに……初めて見るわけじゃないんだし……<emoji=heart04>　ふふっ<emoji=heart04>」
line = "「それに……初めて見るわけじゃないんだし……<emoji=heart04>　ふふっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# わざとからかってません！？
line = "わざとからかってません！？"

[[dialogue]]
speaker = "サーシャ"
# 「だって～、会長くんってば、恋人になってから結構経つのに、未だに顔を赤くしちゃって可愛いんだもの♪」
line = "「だって～、会長くんってば、恋人になってから結構経つのに、未だに顔を赤くしちゃって可愛いんだもの♪」"

[[dialogue]]
speaker = "サーシャ"
# 「――私のスタイルが良いから、いつもドキドキしちゃう？　うふふっ、褒めてくれてありがと～♪」
line = "「――私のスタイルが良いから、いつもドキドキしちゃう？　うふふっ、褒めてくれてありがと～♪」"

[[dialogue]]
speaker = "サーシャ"
# 「会長くんはいつも変わらず、そういう反応をしてくれるから、お姉ちゃん嬉しくなっちゃうわ♪」
line = "「会長くんはいつも変わらず、そういう反応をしてくれるから、お姉ちゃん嬉しくなっちゃうわ♪」"

[[dialogue]]
speaker = "unk"
# 慣れ過ぎないよう、戒めているというか……
line = "慣れ過ぎないよう、戒めているというか……"

[[dialogue]]
speaker = "サーシャ"
# 「あら、そうなの？　どうして？」
line = "「あら、そうなの？　どうして？」"

[[dialogue]]
speaker = "サーシャ"
# 「――会長として、節度を持つように？　ふふっ、真面目な会長くんらしいわね～♪」
line = "「――会長として、節度を持つように？　ふふっ、真面目な会長くんらしいわね～♪」"

[[dialogue]]
speaker = "サーシャ"
# 「そういう健気なところも、お姉ちゃんは好きなんだけど……<emoji=heart04>」
line = "「そういう健気なところも、お姉ちゃんは好きなんだけど……<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「でも、恋人の会長くん以外に頼めないし、オイルは塗ってくれるでしょう？　お姉ちゃんからの、お願い<emoji=heart04>」
line = "「でも、恋人の会長くん以外に頼めないし、オイルは塗ってくれるでしょう？　お姉ちゃんからの、お願い<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「――ふふっ、ありがと～。じゃあ、よろしくね♪」
line = "「――ふふっ、ありがと～。じゃあ、よろしくね♪」"

[[dialogue]]
speaker = "unk"
# そうして、サーシャさんはビーチマットの上で、うつ伏せになった――
line = "そうして、サーシャさんはビーチマットの上で、うつ伏せになった――"

[[dialogue]]
speaker = "サーシャ"
# 「あんっ<emoji=heart04>　会長くんにヌルヌルのをいっぱい、かけられちゃってるぅ……<emoji=heart04>」
line = "「あんっ<emoji=heart04>　会長くんにヌルヌルのをいっぱい、かけられちゃってるぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「――出し過ぎちゃった……？　ふふっ、謝らなくて大丈夫よ」
line = "「――出し過ぎちゃった……？　ふふっ、謝らなくて大丈夫よ」"

[[dialogue]]
speaker = "サーシャ"
# 「お姉ちゃんがちゃんと、受け止めてあげるから<emoji=heart04>　焦らずに……ゆっくり、ね？」
line = "「お姉ちゃんがちゃんと、受け止めてあげるから<emoji=heart04>　焦らずに……ゆっくり、ね？」"

[[dialogue]]
speaker = "サーシャ"
# 「んっ<emoji=heart04>　そう、イイ感じ……はぁんっ<emoji=heart04>　ヌルヌルで敏感になって……会長くんの、いつもより感じちゃう……ふあぁっ……<emoji=heart04>」
line = "「んっ<emoji=heart04>　そう、イイ感じ……はぁんっ<emoji=heart04>　ヌルヌルで敏感になって……会長くんの、いつもより感じちゃう……ふあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そ、そんな色っぽい声を出されると……
line = "そ、そんな色っぽい声を出されると……"

[[dialogue]]
speaker = "サーシャ"
# 「だって……好きな男の子に触れられてるんだもの……<emoji=heart04>」
line = "「だって……好きな男の子に触れられてるんだもの……<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「お姉ちゃんだって、女の子だから意識しちゃうわ……あんっ<emoji=heart04>　それに今は、２人きりだし……んっ……<emoji=heart04>」
line = "「お姉ちゃんだって、女の子だから意識しちゃうわ……あんっ<emoji=heart04>　それに今は、２人きりだし……んっ……<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「だから会長くん、続き……して？」
line = "「だから会長くん、続き……して？」"

[[dialogue]]
speaker = "サーシャ"
# 「あっ<emoji=heart04>　そこ、撫でられたら、背筋ゾクゾクしちゃう……<emoji=heart04>　はあぁ……<emoji=heart04>」
line = "「あっ<emoji=heart04>　そこ、撫でられたら、背筋ゾクゾクしちゃう……<emoji=heart04>　はあぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「会長くん、可愛い顔して、ちゃんと男の子の逞しい手をしてるから……んっ<emoji=heart04>　お姉ちゃん、ドキッてしちゃう……<emoji=heart04>」
line = "「会長くん、可愛い顔して、ちゃんと男の子の逞しい手をしてるから……んっ<emoji=heart04>　お姉ちゃん、ドキッてしちゃう……<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「はぁ……ふぅ……<emoji=heart04>　背中終わったの？　じゃあ次は、他の場所も塗って欲しいわ<emoji=heart04>」
line = "「はぁ……ふぅ……<emoji=heart04>　背中終わったの？　じゃあ次は、他の場所も塗って欲しいわ<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「――背中以外は自分でも塗れる場所？　そうだけど、せっかくだし……」
line = "「――背中以外は自分でも塗れる場所？　そうだけど、せっかくだし……」"

[[dialogue]]
speaker = "サーシャ"
# 「会長くんは……するの嫌？」
line = "「会長くんは……するの嫌？」"

[[dialogue]]
speaker = "サーシャ"
# 「――嫌じゃないけど、抑えが利かなくなるかも？　ふふっ<emoji=heart04>」
line = "「――嫌じゃないけど、抑えが利かなくなるかも？　ふふっ<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「その時は、お姉ちゃんが責任もって受け止めてあげるから、大丈夫<emoji=heart04>」
line = "「その時は、お姉ちゃんが責任もって受け止めてあげるから、大丈夫<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「ほら、周りに誰も居ないし……来て<emoji=heart04>」
line = "「ほら、周りに誰も居ないし……来て<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「――あっ<emoji=heart04>　やんっ……脇はくすぐったいわ<emoji=heart04>　もっと優しく……<emoji=heart04>」
line = "「――あっ<emoji=heart04>　やんっ……脇はくすぐったいわ<emoji=heart04>　もっと優しく……<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「もっと下の、お腹の方も……大丈夫だから……そう、そこ……っ<emoji=heart04>」
line = "「もっと下の、お腹の方も……大丈夫だから……そう、そこ……っ<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「ふあぁっ<emoji=heart04>　会長くぅん……<emoji=heart04>」
line = "「ふあぁっ<emoji=heart04>　会長くぅん……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# な、何とか終わった……
line = "な、何とか終わった……"

[[dialogue]]
speaker = "サーシャ"
# 「ふふっ、ありがと～♪　全身ちゃんと塗ってくれて<emoji=heart04>」
line = "「ふふっ、ありがと～♪　全身ちゃんと塗ってくれて<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ"
# 「それじゃあ今度は――」
line = "「それじゃあ今度は――」"

[[dialogue]]
speaker = "サーシャ"
# 「私が会長くんにオイルを塗る番ね<emoji=heart04>」
line = "「私が会長くんにオイルを塗る番ね<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# えっ！？
line = "えっ！？"

[[dialogue]]
speaker = "サーシャ"
# 「だって、会長くんもちゃんとオイル塗っておかないと、後で日焼けして痛くなっちゃうわよ？」
line = "「だって、会長くんもちゃんとオイル塗っておかないと、後で日焼けして痛くなっちゃうわよ？」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふっ♪　遠慮なんてしなくていいのよ？」
line = "「ふふっ♪　遠慮なんてしなくていいのよ？」"

[[dialogue]]
speaker = "サーシャ"
# 「お姉ちゃんが全部、してあげるから……<emoji=heart04>」
line = "「お姉ちゃんが全部、してあげるから……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# や、優しく、お願いします……
line = "や、優しく、お願いします……"

[[dialogue]]
speaker = "unk"
# その後、俺はサーシャさんの手で、全身余すとこなくお世話されてしまうのだった――
line = "その後、俺はサーシャさんの手で、全身余すとこなくお世話されてしまうのだった――"
