[[dialogue]]
speaker = "unk"
# 第３話,激辛珍道中,P
line = "第３話,激辛珍道中,P"

[[dialogue]]
speaker = "セドナ"
# 「ん──貴様か。よく会うな。奇遇だと？　馬鹿を言え、こういうのは悪縁というのだ」
line = "「ん──貴様か。よく会うな。奇遇だと？　馬鹿を言え、こういうのは悪縁というのだ」"

[[dialogue]]
speaker = "unk"
# 外で会うのは珍しい
line = "外で会うのは珍しい"

[[dialogue]]
speaker = "unk"
# どうしてここに？
line = "どうしてここに？"

[[dialogue]]
speaker = "セドナ"
# 「何、ただの昼時だ。この近くに馴染みの店があってな──たまに余裕のある際は寄るようにしている」
line = "「何、ただの昼時だ。この近くに馴染みの店があってな──たまに余裕のある際は寄るようにしている」"

[[dialogue]]
speaker = "セドナ"
# 「最近は滅多に赴くこともなかったのだが……以前、誰かさんに少しは休めと説教されてしまったのでな」
line = "「最近は滅多に赴くこともなかったのだが……以前、誰かさんに少しは休めと説教されてしまったのでな」"

[[dialogue]]
speaker = "セドナ"
# 「そうだ。せっかくの機だ、貴様も来るか？　いつか学園内を巡らせてもらった礼もある」
line = "「そうだ。せっかくの機だ、貴様も来るか？　いつか学園内を巡らせてもらった礼もある」"

[[dialogue]]
speaker = "unk"
# お言葉に甘えて……
line = "お言葉に甘えて……"

[[dialogue]]
speaker = "unk"
# いいんですか？
line = "いいんですか？"

[[dialogue]]
speaker = "セドナ"
# 「ああ。穴場ゆえ混むこともないだろう──遠慮せずにたんと喰らえ」
line = "「ああ。穴場ゆえ混むこともないだろう──遠慮せずにたんと喰らえ」"

[[dialogue]]
speaker = "セドナ"
# 「ふむ──久方ぶりの訪問だったが、やはりここの火鍋は良い。全身に魔力が染み渡るかのようだ」
line = "「ふむ──久方ぶりの訪問だったが、やはりここの火鍋は良い。全身に魔力が染み渡るかのようだ」"

[[dialogue]]
speaker = "セドナ"
# 「……ん？　なんだ貴様、がぶがぶ水など飲んで」
line = "「……ん？　なんだ貴様、がぶがぶ水など飲んで」"

[[dialogue]]
speaker = "unk"
# 口から火が！
line = "口から火が！"

[[dialogue]]
speaker = "unk"
# 辛すぎる！
line = "辛すぎる！"

[[dialogue]]
speaker = "セドナ"
# 「はっはっはっ。どうした、顔を真っ赤にして──そんなに刺激が強すぎたか？　とんだお子ちゃまだな」
line = "「はっはっはっ。どうした、顔を真っ赤にして──そんなに刺激が強すぎたか？　とんだお子ちゃまだな」"

[[dialogue]]
speaker = "セドナ"
# 「くっくっ。いや何。貴様が必死に汗をかいている姿がおかしくてな。ふふっ、あまり笑わせるな！」
line = "「くっくっ。いや何。貴様が必死に汗をかいている姿がおかしくてな。ふふっ、あまり笑わせるな！」"

[[dialogue]]
speaker = "セドナ"
# 「これしきの辛さで音を上げるとはしようのない奴だ。ほら、私の水もやる」
line = "「これしきの辛さで音を上げるとはしようのない奴だ。ほら、私の水もやる」"

[[dialogue]]
speaker = "unk"
# 辛いものが好きなの？
line = "辛いものが好きなの？"

[[dialogue]]
speaker = "セドナ"
# 「まあ、それなりにな。森にはもっと刺激的な香草もあった──体が慣れているのかもしれんな」
line = "「まあ、それなりにな。森にはもっと刺激的な香草もあった──体が慣れているのかもしれんな」"

[[dialogue]]
speaker = "セドナ"
# 「……意外か？」
line = "「……意外か？」"

[[dialogue]]
speaker = "unk"
# 割とイメージ通り
line = "割とイメージ通り"

[[dialogue]]
speaker = "セドナ"
# 「……ぐ。いや……別にイメージ通りだったからと言って何が悪いわけでもないのだが。若干、負けた気にはなるな」
line = "「……ぐ。いや……別にイメージ通りだったからと言って何が悪いわけでもないのだが。若干、負けた気にはなるな」"

[[dialogue]]
speaker = "セドナ"
# 「しかし、まだダメージが残っているとはな。軟弱なものだ」
line = "「しかし、まだダメージが残っているとはな。軟弱なものだ」"

[[dialogue]]
speaker = "セドナ"
# 「仕方ない──向こうでジェラートでも食すか？　一軒だけだが、顔なじみの場所がある」
line = "「仕方ない──向こうでジェラートでも食すか？　一軒だけだが、顔なじみの場所がある」"

[[dialogue]]
speaker = "unk"
# そこは意外でした
line = "そこは意外でした"

[[dialogue]]
speaker = "unk"
# 面倒見がいいんですね
line = "面倒見がいいんですね"

[[dialogue]]
speaker = "セドナ"
# 「……貴様、私をからかっているんじゃあるまいな？　あまりふざけるようならこの場に置いていくぞ」
line = "「……貴様、私をからかっているんじゃあるまいな？　あまりふざけるようならこの場に置いていくぞ」"

[[dialogue]]
speaker = "セドナ"
# 「上官として──部下の面倒を見ることには慣れている。もっとも、貴様は別に部下ではないが……」
line = "「上官として──部下の面倒を見ることには慣れている。もっとも、貴様は別に部下ではないが……」"

[[dialogue]]
speaker = "セドナ"
# 「ともかく。そんなに恨みがましい目で私を見るくらいなら、氷菓子を奢ってやるというだけだ。どうだ？」
line = "「ともかく。そんなに恨みがましい目で私を見るくらいなら、氷菓子を奢ってやるというだけだ。どうだ？」"

[[dialogue]]
speaker = "セドナ"
# 「うむ、それでいい。こちらだ──ついてこい」
line = "「うむ、それでいい。こちらだ──ついてこい」"

[[dialogue]]
speaker = "セドナ"
# 「落ち着いたか。やれやれ……予想外の出費と相成ってしまったではないか」
line = "「落ち着いたか。やれやれ……予想外の出費と相成ってしまったではないか」"

[[dialogue]]
speaker = "セドナ"
# 「ふふ。どうやらこちらは口に合うようだな」
line = "「ふふ。どうやらこちらは口に合うようだな」"

[[dialogue]]
speaker = "セドナ"
# 「ん？　甘いものは苦手なんじゃ──って、よく覚えているな。基本はそうなのだが……ここのジェラートは例外なんだ」
line = "「ん？　甘いものは苦手なんじゃ──って、よく覚えているな。基本はそうなのだが……ここのジェラートは例外なんだ」"

[[dialogue]]
speaker = "セドナ"
# 「昔──古い付き合いの友人がよくここに誘ってくれていてな。もっとも、それとて数年前の話だが……」
line = "「昔──古い付き合いの友人がよくここに誘ってくれていてな。もっとも、それとて数年前の話だが……」"

[[dialogue]]
speaker = "セドナ"
# 「…………そんなことはいい。私もあまり長く油を売っているわけにはいかない、食い終わったら基地へ戻るぞ」
line = "「…………そんなことはいい。私もあまり長く油を売っているわけにはいかない、食い終わったら基地へ戻るぞ」"

[[dialogue]]
speaker = "セドナ"
# 「って……ん？　なんだ、こちらを見て。言いたいことがあるなら言ってみろ」
line = "「って……ん？　なんだ、こちらを見て。言いたいことがあるなら言ってみろ」"

[[dialogue]]
speaker = "unk"
# デートみたいですね
line = "デートみたいですね"

[[dialogue]]
speaker = "unk"
# こうやって歩いてると……
line = "こうやって歩いてると……"

[[dialogue]]
speaker = "セドナ"
# 「……デ？」
line = "「……デ？」"

[[dialogue]]
speaker = "セドナ"
# 「………………」
line = "「………………」"

[[dialogue]]
speaker = "セドナ"
# 「……………………貴様。よく上官に向かってそんな舐めた口が利けたものだな」
line = "「……………………貴様。よく上官に向かってそんな舐めた口が利けたものだな」"

[[dialogue]]
speaker = "unk"
# 上官ってわけじゃ
line = "上官ってわけじゃ"

[[dialogue]]
speaker = "unk"
# 部下ではないです
line = "部下ではないです"

[[dialogue]]
speaker = "セドナ"
# 「だ、黙れ！　口ごたえするな！　さっきから甘やかしていれば調子に乗りおって！」
line = "「だ、黙れ！　口ごたえするな！　さっきから甘やかしていれば調子に乗りおって！」"

[[dialogue]]
speaker = "セドナ"
# 「やはり貴様にはネビュラ式のきつい訓練が必要なようだ。その甘ったれた肉体も根性も、一からまとめて鍛え直してやる！」
line = "「やはり貴様にはネビュラ式のきつい訓練が必要なようだ。その甘ったれた肉体も根性も、一からまとめて鍛え直してやる！」"

[[dialogue]]
speaker = "セドナ"
# 「待つがいい魔王──貴様の魂、このセドナが燃え上がらせてくれる──！」
line = "「待つがいい魔王──貴様の魂、このセドナが燃え上がらせてくれる──！」"
