[[dialogue]]
speaker = "unk"
# 第３話,一人前の法螺吹きに,P
line = "第３話,一人前の法螺吹きに,P"

[[dialogue]]
speaker = "ルリエル"
# 「突然ですがルリエル、一人前の法螺吹きを目指します！」
line = "「突然ですがルリエル、一人前の法螺吹きを目指します！」"

[[dialogue]]
speaker = "ルリエル"
# 「演奏のことじゃないですよ？　ウソをつく方の法螺のことなのです！」
line = "「演奏のことじゃないですよ？　ウソをつく方の法螺のことなのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「この間ソフィアに言われちゃったんです。『ルリってウソが下手過ぎるよね』って」
line = "「この間ソフィアに言われちゃったんです。『ルリってウソが下手過ぎるよね』って」"

[[dialogue]]
speaker = "ルリエル"
# 「先日、星徒会のみんなで納涼人狼大会をしている時でした。わたし、ずーっと楽しみにしていて、個人的に何度も練習していたんです……！」
line = "「先日、星徒会のみんなで納涼人狼大会をしている時でした。わたし、ずーっと楽しみにしていて、個人的に何度も練習していたんです……！」"

[[dialogue]]
speaker = "ルリエル"
# 「なのにソフィアってば、わたしが人狼になるとバレバレすぎて面白くないって言ってきて……！　他の皆さんも苦笑するばかりで何も反論してくれなくて……！」
line = "「なのにソフィアってば、わたしが人狼になるとバレバレすぎて面白くないって言ってきて……！　他の皆さんも苦笑するばかりで何も反論してくれなくて……！」"

[[dialogue]]
speaker = "ルリエル"
# 「あの可哀想な子を見るような皆さんの顔が忘れられません……！　だからルリエル、決めたのです！　一人前の法螺吹きになって、見返してやろうって！」
line = "「あの可哀想な子を見るような皆さんの顔が忘れられません……！　だからルリエル、決めたのです！　一人前の法螺吹きになって、見返してやろうって！」"

[[dialogue]]
speaker = "ルリエル"
# 「だから特訓に付き合ってくださいっ。ルリエル、今からウソつきさんになりますから、自然にウソをつけてるか確かめて欲しいんですよっ」
line = "「だから特訓に付き合ってくださいっ。ルリエル、今からウソつきさんになりますから、自然にウソをつけてるか確かめて欲しいんですよっ」"

[[dialogue]]
speaker = "ルリエル"
# 「まぁ、そー簡単には見抜けないと思いますけどね？　人狼大会のあと、自然にウソをつけるようにいっぱい練習したので」
line = "「まぁ、そー簡単には見抜けないと思いますけどね？　人狼大会のあと、自然にウソをつけるようにいっぱい練習したので」"

[[dialogue]]
speaker = "ルリエル"
# 「今のわたしは言葉巧みに異性を弄ぶ小悪魔天使と言っても過言じゃありません！　覚悟してくださいよぉ～？」
line = "「今のわたしは言葉巧みに異性を弄ぶ小悪魔天使と言っても過言じゃありません！　覚悟してくださいよぉ～？」"

[[dialogue]]
speaker = "unk"
# …………
line = "…………"

[[dialogue]]
speaker = "ルリエル"
# 「あの時のみんなと同じ顔してますぅ！？　まだ何一つウソはついていませんよっ！？」
line = "「あの時のみんなと同じ顔してますぅ！？　まだ何一つウソはついていませんよっ！？」"

[[dialogue]]
speaker = "ルリエル"
# 「でもでも、そんな風に呆れていられるのも今のうちです！　わたしを守護する１万人のＳＰが黙っちゃいません！」
line = "「でもでも、そんな風に呆れていられるのも今のうちです！　わたしを守護する１万人のＳＰが黙っちゃいません！」"

[[dialogue]]
speaker = "ルリエル"
# 「今まで隠してましたけど、実はわたし、とある王家の生まれなんです。つまりお姫様なんですよぉ～！　わたしをからかったが最期──」
line = "「今まで隠してましたけど、実はわたし、とある王家の生まれなんです。つまりお姫様なんですよぉ～！　わたしをからかったが最期──」"

[[dialogue]]
speaker = "unk"
# はいダウトー
line = "はいダウトー"

[[dialogue]]
speaker = "ルリエル"
# 「ふぇっ！？　どどど、どうしてわかったんですかぁ～！？　この日のために寝る間も惜しんで練りに練ったウソでしたのに！？」
line = "「ふぇっ！？　どどど、どうしてわかったんですかぁ～！？　この日のために寝る間も惜しんで練りに練ったウソでしたのに！？」"

[[dialogue]]
speaker = "ルリエル"
# 「うぅ、どうしましょう……。まずこのウソに騙されちゃう想定でプランを組んでいたので、特訓のしようがなくなっちゃいました……」
line = "「うぅ、どうしましょう……。まずこのウソに騙されちゃう想定でプランを組んでいたので、特訓のしようがなくなっちゃいました……」"

[[dialogue]]
speaker = "ルリエル"
# 「そうだ！　何かわたしに質問してくれませんかっ？　それにさらっとウソをついて返しますのでっ。ウソって、すらすら言ってなんぼですし！」
line = "「そうだ！　何かわたしに質問してくれませんかっ？　それにさらっとウソをついて返しますのでっ。ウソって、すらすら言ってなんぼですし！」"

[[dialogue]]
speaker = "ルリエル"
# 「……え？　最近ハマってることは、ですか？　えへへ、そんなの決まってますよぉ～。水泳と法螺貝の演奏ですぅ」
line = "「……え？　最近ハマってることは、ですか？　えへへ、そんなの決まってますよぉ～。水泳と法螺貝の演奏ですぅ」"

[[dialogue]]
speaker = "ルリエル"
# 「海の家でたこ焼きを食べてからは、たこ焼き作りにもハマってます。今日も手作りのたこ焼きを──」
line = "「海の家でたこ焼きを食べてからは、たこ焼き作りにもハマってます。今日も手作りのたこ焼きを──」"

[[dialogue]]
speaker = "ルリエル"
# 「──って、ハっ！　思わず本当のことを話してしまいました！　え、ええと、最近はですね、絵画の鑑賞などをしょーしょー……」
line = "「──って、ハっ！　思わず本当のことを話してしまいました！　え、ええと、最近はですね、絵画の鑑賞などをしょーしょー……」"

[[dialogue]]
speaker = "ルリエル"
# 「あうぅ、そんな顔で見ないでくださいよぉ～！　わたしに絵画鑑賞の趣味があってもいいじゃないですかぁ～……！」
line = "「あうぅ、そんな顔で見ないでくださいよぉ～！　わたしに絵画鑑賞の趣味があってもいいじゃないですかぁ～……！」"

[[dialogue]]
speaker = "ルリエル"
# 「というか質問が悪いです！　最近ハマっていることなんてウソをつきづらいですもん！　もっとウソをつきやすそうな、イエスかノーで答えられる質問にしてください！」
line = "「というか質問が悪いです！　最近ハマっていることなんてウソをつきづらいですもん！　もっとウソをつきやすそうな、イエスかノーで答えられる質問にしてください！」"

[[dialogue]]
speaker = "ルリエル"
# 「え？　学園の宿題は終わらせたか、ですか？　ふふん、もちろんイエスですよぉ～！　わたし、遊びに行く前にぜーんぶ終わらせておくタイプですから！」
line = "「え？　学園の宿題は終わらせたか、ですか？　ふふん、もちろんイエスですよぉ～！　わたし、遊びに行く前にぜーんぶ終わらせておくタイプですから！」"

[[dialogue]]
speaker = "unk"
# じゃあ教えなくても大丈夫だな
line = "じゃあ教えなくても大丈夫だな"

[[dialogue]]
speaker = "ルリエル"
# 「へ……？　ちょっ、待ってくださいっ、ウソです、法螺です！　まだ手も付けてませ～んっ！」
line = "「へ……？　ちょっ、待ってくださいっ、ウソです、法螺です！　まだ手も付けてませ～んっ！」"

[[dialogue]]
speaker = "ルリエル"
# 「む～！　質問が意地悪です！　わたしが不利になる質問はしないでください！　もっと気分良くウソをつかせてくださいってばぁ～！」
line = "「む～！　質問が意地悪です！　わたしが不利になる質問はしないでください！　もっと気分良くウソをつかせてくださいってばぁ～！」"

[[dialogue]]
speaker = "ルリエル"
# 「たとえば……そうですね。じゃあ左右限定のあっち向いてほいをしましょう！　わたしの巧みなウソで会長さんを騙してみせます！」
line = "「たとえば……そうですね。じゃあ左右限定のあっち向いてほいをしましょう！　わたしの巧みなウソで会長さんを騙してみせます！」"

[[dialogue]]
speaker = "ルリエル"
# 「ふっふ～、絶対に右だけは向いちゃダメですよ～？　わたし、右を指しますから。ホ、ホントですってば。ここまで言って左なんか指しませんっ！」
line = "「ふっふ～、絶対に右だけは向いちゃダメですよ～？　わたし、右を指しますから。ホ、ホントですってば。ここまで言って左なんか指しませんっ！」"

[[dialogue]]
speaker = "ルリエル"
# 「くれぐれも右だけは向いちゃダメですからねっ？　それじゃ行きますよ～？　あっち向いて～、ほいっ！」
line = "「くれぐれも右だけは向いちゃダメですからねっ？　それじゃ行きますよ～？　あっち向いて～、ほいっ！」"

[[dialogue]]
speaker = "ルリエル"
# 「あははっ、やりました！　見事に騙されちゃいましたねっ！　左でドボンですっ！」
line = "「あははっ、やりました！　見事に騙されちゃいましたねっ！　左でドボンですっ！」"

[[dialogue]]
speaker = "unk"
# うわー、すっかり騙されちゃったよー
line = "うわー、すっかり騙されちゃったよー"

[[dialogue]]
speaker = "ルリエル"
# 「えへへ、でしょうでしょう！　やっぱりわたし、ウソつきの才能があります！　もはや会長さんはわたしの手の平の上です！」
line = "「えへへ、でしょうでしょう！　やっぱりわたし、ウソつきの才能があります！　もはや会長さんはわたしの手の平の上です！」"

[[dialogue]]
speaker = "ルリエル"
# 「そうだ、何かわたしに相談事とかありませんかっ？　さらっと自然にウソをついて、会長さんをもーっと弄んであげちゃいますから！」
line = "「そうだ、何かわたしに相談事とかありませんかっ？　さらっと自然にウソをついて、会長さんをもーっと弄んであげちゃいますから！」"

[[dialogue]]
speaker = "ルリエル"
# 「ふむふむ。新しい服を買おうと思っている、ですか。これとこれ、どっちが会長さんに似合うか選んで欲しいわけですねっ？」
line = "「ふむふむ。新しい服を買おうと思っている、ですか。これとこれ、どっちが会長さんに似合うか選んで欲しいわけですねっ？」"

[[dialogue]]
speaker = "ルリエル"
# 「でしたら、むふふ、断然こっちですよこっち！　このすごーくおダサな服の方です！」
line = "「でしたら、むふふ、断然こっちですよこっち！　このすごーくおダサな服の方です！」"

[[dialogue]]
speaker = "ルリエル"
# 「えへへ、ウソですっ、こっちですっ！　んもー危ないですよぉ？　店員さんとかに勧められるがまま、似合わない服とか買わないでくださいね～？」
line = "「えへへ、ウソですっ、こっちですっ！　んもー危ないですよぉ？　店員さんとかに勧められるがまま、似合わない服とか買わないでくださいね～？」"

[[dialogue]]
speaker = "ルリエル"
# 「でもでも、ウソつくのって楽しいですね？　特にネタばらしの瞬間が快感ですぅ！」
line = "「でもでも、ウソつくのって楽しいですね？　特にネタばらしの瞬間が快感ですぅ！」"

[[dialogue]]
speaker = "ルリエル"
# 「他に何かありませんかっ？　この機に何かルリエルに尋ねたいこととかっ？」
line = "「他に何かありませんかっ？　この機に何かルリエルに尋ねたいこととかっ？」"

[[dialogue]]
speaker = "unk"
# じゃあ……俺のこと好き？
line = "じゃあ……俺のこと好き？"

[[dialogue]]
speaker = "ルリエル"
# 「ふぇっ！？　え、ええと、それはその……き、嫌いですぅ……」
line = "「ふぇっ！？　え、ええと、それはその……き、嫌いですぅ……」"

[[dialogue]]
speaker = "ルリエル"
# 「ああっ！？　ウソですよ、ウソっ！　そんなに悲しそうな顔しないでくださいっ！」
line = "「ああっ！？　ウソですよ、ウソっ！　そんなに悲しそうな顔しないでくださいっ！」"

[[dialogue]]
speaker = "ルリエル"
# 「えっ……？　会長さんを格好良いと思うか、ですか？　ぜ、全然格好良くないですっ」
line = "「えっ……？　会長さんを格好良いと思うか、ですか？　ぜ、全然格好良くないですっ」"

[[dialogue]]
speaker = "ルリエル"
# 「ああっ！？　ですからウソですよ、ウソぉ！　世界で一番格好良いと思ってますっ！　自慢の彼氏さんなんですからぁ……！」
line = "「ああっ！？　ですからウソですよ、ウソぉ！　世界で一番格好良いと思ってますっ！　自慢の彼氏さんなんですからぁ……！」"

[[dialogue]]
speaker = "ルリエル"
# 「前言撤回、ウソって気分悪いですぅ……。そもそも天使がウソなんか付いちゃダメですよね。一人前の法螺吹きを目指すの、やっぱりやめます」
line = "「前言撤回、ウソって気分悪いですぅ……。そもそも天使がウソなんか付いちゃダメですよね。一人前の法螺吹きを目指すの、やっぱりやめます」"

[[dialogue]]
speaker = "ルリエル"
# 「ウソを言い合うより、本音を言い合って過ごしたいですもん。大好きって言った時に信じてもらえなかったら嫌ですから」
line = "「ウソを言い合うより、本音を言い合って過ごしたいですもん。大好きって言った時に信じてもらえなかったら嫌ですから」"

[[dialogue]]
speaker = "ルリエル"
# 「ね、会長さん。わたしのこと……好きですか？」
line = "「ね、会長さん。わたしのこと……好きですか？」"

[[dialogue]]
speaker = "unk"
# もちろん大好きだよ
line = "もちろん大好きだよ"

[[dialogue]]
speaker = "ルリエル"
# 「えへへっ、ルリエルもだいだいだーい好きですっ～！　世界で一番、いいえっ、宇宙で一番だーい好きなのですぅっ～」
line = "「えへへっ、ルリエルもだいだいだーい好きですっ～！　世界で一番、いいえっ、宇宙で一番だーい好きなのですぅっ～」"

[[dialogue]]
speaker = "ルリエル"
# 「これはぜったいぜ～ったい、ウソじゃない、ですよ？」
line = "「これはぜったいぜ～ったい、ウソじゃない、ですよ？」"
