[[dialogue]]
speaker = "unk"
# 第１話,可愛い後輩と羽根突きゲーム,P
line = "第１話,可愛い後輩と羽根突きゲーム,P"

[[dialogue]]
speaker = "unk"
# 恋人であるリーリアと迎えたお正月。その日は安倍野神社の境内を借り、羽根突きの練習をする約束をしていた。
line = "恋人であるリーリアと迎えたお正月。その日は安倍野神社の境内を借り、羽根突きの練習をする約束をしていた。"

[[dialogue]]
speaker = "リーリア"
# 「セ～ンパイ♪　マジカルおはようございま～す☆」
line = "「セ～ンパイ♪　マジカルおはようございま～す☆」"

[[dialogue]]
speaker = "unk"
# 晴れ着、似合ってて可愛い
line = "晴れ着、似合ってて可愛い"

[[dialogue]]
speaker = "リーリア"
# 「えへへへへへぇ<emoji=heart04>　さっすがセンパイ、わかってますね～☆」
line = "「えへへへへへぇ<emoji=heart04>　さっすがセンパイ、わかってますね～☆」"

[[dialogue]]
speaker = "リーリア"
# 「女の子は好きな人が相手なら、おめかしを褒められるのは、何度だって嬉しいんですから♪」
line = "「女の子は好きな人が相手なら、おめかしを褒められるのは、何度だって嬉しいんですから♪」"

[[dialogue]]
speaker = "リーリア"
# 「お礼に、可愛い後輩カノジョが腕に抱き着いちゃいますよ～♪　えいっ<emoji=heart04>」
line = "「お礼に、可愛い後輩カノジョが腕に抱き着いちゃいますよ～♪　えいっ<emoji=heart04>」"

[[dialogue]]
speaker = "リーリア"
# 「ふっふっふっ☆　どうです～？　さらにアップデートされた、最新の<b>幻影魔法</b>は？」
line = "「ふっふっふっ☆　どうです～？　さらにアップデートされた、最新の<b>幻影魔法</b>は？」"

[[dialogue]]
speaker = "リーリア"
# 「おかげで、ここまで胸元が開いちゃってる晴れ着フォームも、可愛く着こなせるようになったんですよ～♪」
line = "「おかげで、ここまで胸元が開いちゃってる晴れ着フォームも、可愛く着こなせるようになったんですよ～♪」"

[[dialogue]]
speaker = "unk"
# リーリアの胸は<b>パッド</b>でだいぶサイズが盛られている（本人曰く、これはお洒落の一環なので、バレてるかどうかは問題ではないらしい）。
line = "リーリアの胸は<b>パッド</b>でだいぶサイズが盛られている（本人曰く、これはお洒落の一環なので、バレてるかどうかは問題ではないらしい）。"

[[dialogue]]
speaker = "unk"
# そのパッドをテクスチャーのように幻影魔法で覆うことで、胸元を大胆に開いても本物にしか見えない巨乳美少女が完成する、という仕組みである。
line = "そのパッドをテクスチャーのように幻影魔法で覆うことで、胸元を大胆に開いても本物にしか見えない巨乳美少女が完成する、という仕組みである。"

[[dialogue]]
speaker = "unk"
# よし、それじゃあ訓練を始めようか！
line = "よし、それじゃあ訓練を始めようか！"

[[dialogue]]
speaker = "リーリア"
# 「って、ノーコメント！？　もう、センパイってば、そこは気になるポイントなんですから、ちゃんと褒めて下さいよ～！」
line = "「って、ノーコメント！？　もう、センパイってば、そこは気になるポイントなんですから、ちゃんと褒めて下さいよ～！」"

[[dialogue]]
speaker = "unk"
# 被害者風を装っているが、リーリアはパッド付きとはいえ、恋人に頻繁に胸を押し付けられて、俺が照れているのをわかっててやっている。これは巧妙な罠なのだ。
line = "被害者風を装っているが、リーリアはパッド付きとはいえ、恋人に頻繁に胸を押し付けられて、俺が照れているのをわかっててやっている。これは巧妙な罠なのだ。"

[[dialogue]]
speaker = "unk"
# そんなこんなで恋人同士のじゃれ合いをしつつ、俺たちは晴れ着の力の訓練でもある『星術羽根突き』を始めることになった。
line = "そんなこんなで恋人同士のじゃれ合いをしつつ、俺たちは晴れ着の力の訓練でもある『星術羽根突き』を始めることになった。"

[[dialogue]]
speaker = "リーリア"
# 「センパイ、今日の羽根突きなんですけど～、訓練とはいえ、せっかくですから<b>罰ゲーム</b>付きでやりませんか？」
line = "「センパイ、今日の羽根突きなんですけど～、訓練とはいえ、せっかくですから<b>罰ゲーム</b>付きでやりませんか？」"

[[dialogue]]
speaker = "リーリア"
# 「内容は、羽根を落とすたびに『負けた方が相手の耳元で愛の言葉を囁く』っていうのはどうでしょう♪」
line = "「内容は、羽根を落とすたびに『負けた方が相手の耳元で愛の言葉を囁く』っていうのはどうでしょう♪」"

[[dialogue]]
speaker = "リーリア"
# 「――ふふっ♪　では、センパイからの了承ももらったところで、始めちゃいますよ～☆　私から行きますね～、えいっ☆」
line = "「――ふふっ♪　では、センパイからの了承ももらったところで、始めちゃいますよ～☆　私から行きますね～、えいっ☆」"

[[dialogue]]
speaker = "unk"
# そうして始まった星術羽根突き。リーリアは魔法を技に込めて打ってくるのだが――これがまた、とても上手かった。
line = "そうして始まった星術羽根突き。リーリアは魔法を技に込めて打ってくるのだが――これがまた、とても上手かった。"

[[dialogue]]
speaker = "リーリア"
# 「よっし☆　センパイ、私の勝ちですよ～♪」
line = "「よっし☆　センパイ、私の勝ちですよ～♪」"

[[dialogue]]
speaker = "リーリア"
# 「えへへっ、褒めてくれてありがとうございま～す☆　元旦の後、サーシャさんと一緒に私も訓練を続けてるんですよ～」
line = "「えへへっ、褒めてくれてありがとうございま～す☆　元旦の後、サーシャさんと一緒に私も訓練を続けてるんですよ～」"

[[dialogue]]
speaker = "リーリア"
# 「ふふっ、可愛いだけじゃない後輩に、惚れ直しちゃってもいいんですよ～？」
line = "「ふふっ、可愛いだけじゃない後輩に、惚れ直しちゃってもいいんですよ～？」"

[[dialogue]]
speaker = "リーリア"
# 「で、センパイ？　罰ゲームは忘れてませんよね～？」
line = "「で、センパイ？　罰ゲームは忘れてませんよね～？」"

[[dialogue]]
speaker = "unk"
# やるからには男として、ちょっと恥ずかしくてもちゃんとやらねばと思い、俺はリーリアに近づいて、耳元で囁く。
line = "やるからには男として、ちょっと恥ずかしくてもちゃんとやらねばと思い、俺はリーリアに近づいて、耳元で囁く。"

[[dialogue]]
speaker = "unk"
# リーリア、好きだぞ。今年もよろしくな
line = "リーリア、好きだぞ。今年もよろしくな"

[[dialogue]]
speaker = "リーリア"
# 「っ<emoji=heart04>　えへへへへへぇ<emoji=heart04>　はいっ、センパイ、今年も後輩カノジョとして、よろしくお願いしますね<emoji=heart04>」
line = "「っ<emoji=heart04>　えへへへへへぇ<emoji=heart04>　はいっ、センパイ、今年も後輩カノジョとして、よろしくお願いしますね<emoji=heart04>」"

[[dialogue]]
speaker = "リーリア"
# 「さあ、この調子でどんどん続けて行きますよ～♪　勝って勝って勝ちまくって、センパイにもっと愛を囁かせちゃいます☆」
line = "「さあ、この調子でどんどん続けて行きますよ～♪　勝って勝って勝ちまくって、センパイにもっと愛を囁かせちゃいます☆」"

[[dialogue]]
speaker = "unk"
# 実際、リーリアの実力は俺より一枚上手で、その後も連敗続き。
line = "実際、リーリアの実力は俺より一枚上手で、その後も連敗続き。"

[[dialogue]]
speaker = "unk"
# 恥ずかしい愛の言葉を繰り返すことになり、なんとか勝ち筋を探っていた――のだが。
line = "恥ずかしい愛の言葉を繰り返すことになり、なんとか勝ち筋を探っていた――のだが。"

[[dialogue]]
speaker = "リーリア"
# 「あ～ん♪　ミスしてセンパイに負けてしまいました～☆」
line = "「あ～ん♪　ミスしてセンパイに負けてしまいました～☆」"

[[dialogue]]
speaker = "unk"
# なんか今……わざと羽根を落とさなかった？
line = "なんか今……わざと羽根を落とさなかった？"

[[dialogue]]
speaker = "リーリア"
# 「いやいや、何言ってるんですか～。いくら上手な後輩でも、ずっと続けていたらミスくらいしますよ～☆」
line = "「いやいや、何言ってるんですか～。いくら上手な後輩でも、ずっと続けていたらミスくらいしますよ～☆」"

[[dialogue]]
speaker = "リーリア"
# 「それじゃあ今度は、私からセンパイに、愛の言葉を囁いちゃいますね～<emoji=heart04>」
line = "「それじゃあ今度は、私からセンパイに、愛の言葉を囁いちゃいますね～<emoji=heart04>」"

[[dialogue]]
speaker = "リーリア"
# 「――大好きです<emoji=heart04>　世界一格好いいって、本気で思ってますよ、センパイ<emoji=heart04>」
line = "「――大好きです<emoji=heart04>　世界一格好いいって、本気で思ってますよ、センパイ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺は思わずドキッとして、顔が熱くなってしまう。
line = "俺は思わずドキッとして、顔が熱くなってしまう。"

[[dialogue]]
speaker = "リーリア"
# 「あっ、ふふふっ♪　センパイ、顔が赤くなってますよ～？　どうやらマジカルヒットしちゃったみたいですね☆」
line = "「あっ、ふふふっ♪　センパイ、顔が赤くなってますよ～？　どうやらマジカルヒットしちゃったみたいですね☆」"

[[dialogue]]
speaker = "unk"
# くっ……悪戯な後輩に、手玉に取られてしまっている。どうにか逆転の一手を探らなくては……！
line = "くっ……悪戯な後輩に、手玉に取られてしまっている。どうにか逆転の一手を探らなくては……！"

[[dialogue]]
speaker = "リーリア"
# 「――いぇいっ♪　マジカルウィン☆　また私の勝ちですね～」
line = "「――いぇいっ♪　マジカルウィン☆　また私の勝ちですね～」"

[[dialogue]]
speaker = "リーリア"
# 「それじゃあセンパイ、自己肯定感爆上がりの愛の言葉、お願いしま～す☆」
line = "「それじゃあセンパイ、自己肯定感爆上がりの愛の言葉、お願いしま～す☆」"

[[dialogue]]
speaker = "unk"
# 俺はリーリアに一矢報いる為、あれから考えておいた台詞を口にする。
line = "俺はリーリアに一矢報いる為、あれから考えておいた台詞を口にする。"

[[dialogue]]
speaker = "unk"
# スルーした晴れ着の幻影魔法の話だけど――
line = "スルーした晴れ着の幻影魔法の話だけど――"

[[dialogue]]
speaker = "リーリア"
# 「えっ？」
line = "「えっ？」"

[[dialogue]]
speaker = "unk"
# ――リーリアが俺のために一生懸命お洒落してくれてると思うと、実はめちゃくちゃ嬉しい。
line = "――リーリアが俺のために一生懸命お洒落してくれてると思うと、実はめちゃくちゃ嬉しい。"

[[dialogue]]
speaker = "unk"
# ――付き合い始めて結構経つのに、未だにおっぱい押し付けてまで好きアピールしてくれるところ、めちゃくちゃ可愛いと思ってる。
line = "――付き合い始めて結構経つのに、未だにおっぱい押し付けてまで好きアピールしてくれるところ、めちゃくちゃ可愛いと思ってる。"

[[dialogue]]
speaker = "リーリア"
# 「～～～っ<emoji=heart04><emoji=heart04>」
line = "「～～～っ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 顔を真っ赤に染め上げ、後ずさるリーリア。一方の俺も、ちょっと自意識過剰な内容だったため自傷ダメージを受けていた！
line = "顔を真っ赤に染め上げ、後ずさるリーリア。一方の俺も、ちょっと自意識過剰な内容だったため自傷ダメージを受けていた！"

[[dialogue]]
speaker = "リーリア"
# （別に隠してるつもりもなかったけど！　なかったけどぉ！！）
line = "（別に隠してるつもりもなかったけど！　なかったけどぉ！！）"

[[dialogue]]
speaker = "リーリア"
# （おっぱい押し付けてるのが、『好きアピール』だってバレてるの、超恥ずかしいんですけど！？　いやもちろん、特に誤解はないんですけどね！！？）
line = "（おっぱい押し付けてるのが、『好きアピール』だってバレてるの、超恥ずかしいんですけど！？　いやもちろん、特に誤解はないんですけどね！！？）"

[[dialogue]]
speaker = "リーリア"
# 「や、やりますね、センパイっ。今のは結構効きましたよ……！」
line = "「や、やりますね、センパイっ。今のは結構効きましたよ……！」"

[[dialogue]]
speaker = "リーリア"
# 「やられっぱなしというのもしゃくなんで……そうですね、次の罰ゲームは……」
line = "「やられっぱなしというのもしゃくなんで……そうですね、次の罰ゲームは……」"

[[dialogue]]
speaker = "リーリア"
# 「もし私が勝ったら、<b>キス</b>をお願いするっていうのは……アリですか？」
line = "「もし私が勝ったら、<b>キス</b>をお願いするっていうのは……アリですか？」"

[[dialogue]]
speaker = "unk"
# う～ん、ナシだな
line = "う～ん、ナシだな"

[[dialogue]]
speaker = "リーリア"
# 「えぇえぇえぇっ！？　ここでまさかのナシ！？」
line = "「えぇえぇえぇっ！？　ここでまさかのナシ！？」"

[[dialogue]]
speaker = "unk"
# 俺はリーリアの反応が可愛くて、思わず笑ってしまう。彼女の頭に手を置いて、優しく撫でながら言う。
line = "俺はリーリアの反応が可愛くて、思わず笑ってしまう。彼女の頭に手を置いて、優しく撫でながら言う。"

[[dialogue]]
speaker = "リーリア"
# 「――罰ゲームとかじゃなくて、恋人なんだから普通にしたい……？」
line = "「――罰ゲームとかじゃなくて、恋人なんだから普通にしたい……？」"

[[dialogue]]
speaker = "リーリア"
# 「は、はい……<emoji=heart04>　じゃあ、センパイ……んっ<emoji=heart04>」
line = "「は、はい……<emoji=heart04>　じゃあ、センパイ……んっ<emoji=heart04>」"

[[dialogue]]
speaker = "リーリア"
# 「ちゅっ……<emoji=heart04>」
line = "「ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その後は羽根突きよりも、キスにばかり夢中になってしまう俺たちなのであった。
line = "その後は羽根突きよりも、キスにばかり夢中になってしまう俺たちなのであった。"
