[[dialogue]]
speaker = "unk"
# 第１話,初めての海,P
line = "第１話,初めての海,P"

[[dialogue]]
speaker = "トリシャ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "トリシャ"
# 「あ……すみません。つい、圧倒されてしまっておりました。海というのは……こんなにも広大なものなのですね」
line = "「あ……すみません。つい、圧倒されてしまっておりました。海というのは……こんなにも広大なものなのですね」"

[[dialogue]]
speaker = "unk"
# 海は初めて？
line = "海は初めて？"

[[dialogue]]
speaker = "トリシャ"
# 「はい……今までも、絵や写真を見たりすることはあったのですが……」
line = "「はい……今までも、絵や写真を見たりすることはあったのですが……」"

[[dialogue]]
speaker = "トリシャ"
# 「自分の目で見るのは、今回が初めてでした。海というものが、こんなに綺麗なものだったなんて……」
line = "「自分の目で見るのは、今回が初めてでした。海というものが、こんなに綺麗なものだったなんて……」"

[[dialogue]]
speaker = "トリシャ"
# 「魔界では色々な場所を巡り歩いてきました……ですが私が歩いてきた中には、これほどの絶景はありませんでした」
line = "「魔界では色々な場所を巡り歩いてきました……ですが私が歩いてきた中には、これほどの絶景はありませんでした」"

[[dialogue]]
speaker = "トリシャ"
# 「この温暖な気候……爽やかな風……すべてが新鮮です……」
line = "「この温暖な気候……爽やかな風……すべてが新鮮です……」"

[[dialogue]]
speaker = "トリシャ"
# 「連れてきてくれたヘレナさんには感謝ですね……これで私の世界が、またひとつ広がったような気がします……」
line = "「連れてきてくれたヘレナさんには感謝ですね……これで私の世界が、またひとつ広がったような気がします……」"

[[dialogue]]
speaker = "unk"
# トリシャさんは魔界と大きく異なるリゾート結界の光景にカルチャーショックを受けていた。
line = "トリシャさんは魔界と大きく異なるリゾート結界の光景にカルチャーショックを受けていた。"

[[dialogue]]
speaker = "トリシャ"
# 「素足で歩くというのも……最初は、慣れないものでしたが……」
line = "「素足で歩くというのも……最初は、慣れないものでしたが……」"

[[dialogue]]
speaker = "トリシャ"
# 「慣れてみると……ふふ。開放感があって、悪くありません。熱いけど……サラサラしていて……変な感覚……」
line = "「慣れてみると……ふふ。開放感があって、悪くありません。熱いけど……サラサラしていて……変な感覚……」"

[[dialogue]]
speaker = "トリシャ"
# 「……にへへ……」
line = "「……にへへ……」"

[[dialogue]]
speaker = "トリシャ"
# 「砂浜を歩く……楽しいものですね……レゾフでこんなことをしていては、すぐに凍ってしまいそうですが」
line = "「砂浜を歩く……楽しいものですね……レゾフでこんなことをしていては、すぐに凍ってしまいそうですが」"

[[dialogue]]
speaker = "unk"
# 格好は平気？
line = "格好は平気？"

[[dialogue]]
speaker = "unk"
# 水着は慣れた？
line = "水着は慣れた？"

[[dialogue]]
speaker = "トリシャ"
# 「はい。このような姿は初めてでしたが、着てみると、とてもすんなりフィットしました」
line = "「はい。このような姿は初めてでしたが、着てみると、とてもすんなりフィットしました」"

[[dialogue]]
speaker = "トリシャ"
# 「さすがはヘレナさん……ですね……」
line = "「さすがはヘレナさん……ですね……」"

[[dialogue]]
speaker = "トリシャ"
# 「あと……普段の私の格好からして、抵抗なく馴染むだろうと言われました……その通りだったかもしれません……」
line = "「あと……普段の私の格好からして、抵抗なく馴染むだろうと言われました……その通りだったかもしれません……」"

[[dialogue]]
speaker = "unk"
# よくよく考えると、トリシャさんの格好はレゾフの頃からかなり露出多めだった。
line = "よくよく考えると、トリシャさんの格好はレゾフの頃からかなり露出多めだった。"

[[dialogue]]
speaker = "unk"
# むしろ、あちらの格好の方がビーチに適応しているというか……。
line = "むしろ、あちらの格好の方がビーチに適応しているというか……。"

[[dialogue]]
speaker = "トリシャ"
# 「……そういえば、あちらにある施設は……？」
line = "「……そういえば、あちらにある施設は……？」"

[[dialogue]]
speaker = "unk"
# 海の家ですよ
line = "海の家ですよ"

[[dialogue]]
speaker = "unk"
# あれは──
line = "あれは──"

[[dialogue]]
speaker = "トリシャ"
# 「海の家……そのままのネーミングですね。リップルさんがいらっしゃるところ……」
line = "「海の家……そのままのネーミングですね。リップルさんがいらっしゃるところ……」"

[[dialogue]]
speaker = "トリシャ"
# 「あちらに置かれているのは……スイカ、でしょうか？　なぜ野ざらしにされているのか、わかりませんが……」
line = "「あちらに置かれているのは……スイカ、でしょうか？　なぜ野ざらしにされているのか、わかりませんが……」"

[[dialogue]]
speaker = "unk"
# スイカ割りに使う
line = "スイカ割りに使う"

[[dialogue]]
speaker = "トリシャ"
# 「スイカ割り……とは？」
line = "「スイカ割り……とは？」"

[[dialogue]]
speaker = "トリシャ"
# 「なんと……その棒きれを使って、スイカを真っ二つに？　なるほど……なかなかワイルドな催しがあるのですね……」
line = "「なんと……その棒きれを使って、スイカを真っ二つに？　なるほど……なかなかワイルドな催しがあるのですね……」"

[[dialogue]]
speaker = "トリシャ"
# 「なぜそんなことを──あ」
line = "「なぜそんなことを──あ」"

[[dialogue]]
speaker = "トリシャ"
# 「お待ちください……わかりました。みなまで言う必要はありません」
line = "「お待ちください……わかりました。みなまで言う必要はありません」"

[[dialogue]]
speaker = "トリシャ"
# 「ずばり、スイカを叩き割り、その断面で運勢を占うというものですね……わかります。似たような占術を聞いたことがありますので」
line = "「ずばり、スイカを叩き割り、その断面で運勢を占うというものですね……わかります。似たような占術を聞いたことがありますので」"

[[dialogue]]
speaker = "トリシャ"
# 「え？　違う……？」
line = "「え？　違う……？」"

[[dialogue]]
speaker = "unk"
# 食べるため
line = "食べるため"

[[dialogue]]
speaker = "unk"
# 割るだけだ
line = "割るだけだ"

[[dialogue]]
speaker = "トリシャ"
# 「なるほど……ですが、それなら刃物で切ればよいような気もします。食べづらいだけだと思われますが……」
line = "「なるほど……ですが、それなら刃物で切ればよいような気もします。食べづらいだけだと思われますが……」"

[[dialogue]]
speaker = "トリシャ"
# 「そういうものだから……と。ふむ、魔界にも独特な風習は多くあります。それもまた文化なのでしょう……」
line = "「そういうものだから……と。ふむ、魔界にも独特な風習は多くあります。それもまた文化なのでしょう……」"

[[dialogue]]
speaker = "トリシャ"
# 「む？　ちょうどいいからスイカ割りをしないか、と……？」
line = "「む？　ちょうどいいからスイカ割りをしないか、と……？」"

[[dialogue]]
speaker = "トリシャ"
# 「私は剣の心得がないものですから……綺麗に割ろうにも、ご期待に添えないかと存じますが……」
line = "「私は剣の心得がないものですから……綺麗に割ろうにも、ご期待に添えないかと存じますが……」"

[[dialogue]]
speaker = "トリシャ"
# 「ふむ……割れればなんでもよい、と。それくらいなら……私にもできるかもしれません」
line = "「ふむ……割れればなんでもよい、と。それくらいなら……私にもできるかもしれません」"

[[dialogue]]
speaker = "トリシャ"
# 「フフ、少し興味が湧いてきましたね……挑戦してみましょうか」
line = "「フフ、少し興味が湧いてきましたね……挑戦してみましょうか」"

[[dialogue]]
speaker = "トリシャ"
# 「フフフ……ごめんなさい。結局、あなたに割ってもらうことになるなんて」
line = "「フフフ……ごめんなさい。結局、あなたに割ってもらうことになるなんて」"

[[dialogue]]
speaker = "トリシャ"
# 「非力も考えものですね……あんなに力を込めましたのに、スイカがびくともしませんでした……」
line = "「非力も考えものですね……あんなに力を込めましたのに、スイカがびくともしませんでした……」"

[[dialogue]]
speaker = "unk"
# トリシャさんはスイカに棒きれを振り下ろしたものの、力がなくてうまいこと割れなかった。
line = "トリシャさんはスイカに棒きれを振り下ろしたものの、力がなくてうまいこと割れなかった。"

[[dialogue]]
speaker = "トリシャ"
# 「えいっ。えいっ」
line = "「えいっ。えいっ」"

[[dialogue]]
speaker = "unk"
# 本人はその失敗を反省してか、なぜかスイカ割りの素振りをしていた。
line = "本人はその失敗を反省してか、なぜかスイカ割りの素振りをしていた。"

[[dialogue]]
speaker = "トリシャ"
# 「ふう……ですが、あなたに割ってもらったスイカの味は、格段に甘い気がします。不思議なものですね」
line = "「ふう……ですが、あなたに割ってもらったスイカの味は、格段に甘い気がします。不思議なものですね」"

[[dialogue]]
speaker = "トリシャ"
# 「ラムネ、というのも初めて飲みましたが……ひんやりしゅわしゅわで、火照った体に染みました」
line = "「ラムネ、というのも初めて飲みましたが……ひんやりしゅわしゅわで、火照った体に染みました」"

[[dialogue]]
speaker = "トリシャ"
# 「海の家が皆さんに愛される理由が……なんとなくわかった気がします」
line = "「海の家が皆さんに愛される理由が……なんとなくわかった気がします」"

[[dialogue]]
speaker = "トリシャ"
# 「ありがとうございます。あなたのおかげで……海と夏を満喫することができました……大変満足です」
line = "「ありがとうございます。あなたのおかげで……海と夏を満喫することができました……大変満足です」"

[[dialogue]]
speaker = "トリシャ"
# 「この感動を、これからの人生にも活かしたいものです──」
line = "「この感動を、これからの人生にも活かしたいものです──」"

[[dialogue]]
speaker = "unk"
# そうして、満足げに締めようとするトリシャさんだったが──
line = "そうして、満足げに締めようとするトリシャさんだったが──"

[[dialogue]]
speaker = "unk"
# 泳いでみません？
line = "泳いでみません？"

[[dialogue]]
speaker = "unk"
# 海に入ってみません？
line = "海に入ってみません？"

[[dialogue]]
speaker = "トリシャ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "トリシャ"
# 「えぇぇっ……？」
line = "「えぇぇっ……？」"
