[[dialogue]]
speaker = "ソフィア"
# 「寒い寒い寒い！　冷気を出すモンスターとか反則ですよ！？　早くお風呂に……！」
line = "「寒い寒い寒い！　冷気を出すモンスターとか反則ですよ！？　早くお風呂に……！」"

[[dialogue]]
speaker = "ソフィア"
# 「お先にどうぞ……って、何言ってるんですか、あなたも寒そうにしてるんだから一緒に入りましょう！」
line = "「お先にどうぞ……って、何言ってるんですか、あなたも寒そうにしてるんだから一緒に入りましょう！」"

[[dialogue]]
speaker = "ソフィア"
# 「というかそんなこと言ってる時間が惜しいです！　いいから入る！」
line = "「というかそんなこと言ってる時間が惜しいです！　いいから入る！」"

[[dialogue]]
speaker = "ソフィア"
# 「はぁ……温かい……生き返る……」
line = "「はぁ……温かい……生き返る……」"

[[dialogue]]
speaker = "unk"
# 一糸まとわぬ姿で湯船に浸かると、お湯の熱さが冷えた体に染み渡り、まさに極楽の心地だ。
line = "一糸まとわぬ姿で湯船に浸かると、お湯の熱さが冷えた体に染み渡り、まさに極楽の心地だ。"

[[dialogue]]
speaker = "ソフィア"
# 「あ……」
line = "「あ……」"

[[dialogue]]
speaker = "unk"
# けれど全身が温まってくると、凍っていた思考が解けてくる。
line = "けれど全身が温まってくると、凍っていた思考が解けてくる。"

[[dialogue]]
speaker = "unk"
# すると目の前にあるのは……
line = "すると目の前にあるのは……"

[[dialogue]]
speaker = "ソフィア"
# 「えと、その……裸、ですね……お風呂だから当然ですけど」
line = "「えと、その……裸、ですね……お風呂だから当然ですけど」"

[[dialogue]]
speaker = "unk"
# しかし俺に見られるとわかっているのに、ソフィは大事なところを隠そうとはしなかった。
line = "しかし俺に見られるとわかっているのに、ソフィは大事なところを隠そうとはしなかった。"

[[dialogue]]
speaker = "unk"
# まるで芸術品のような白い肌。控えめな膨らみにピンク色の乳首。お尻に向かって緩やかにカーブを描く腰つき。
line = "まるで芸術品のような白い肌。控えめな膨らみにピンク色の乳首。お尻に向かって緩やかにカーブを描く腰つき。"

[[dialogue]]
speaker = "unk"
# そして縦に走るスリットまでもが大胆に晒され、初めて見るソフィの裸体に目を奪われる。
line = "そして縦に走るスリットまでもが大胆に晒され、初めて見るソフィの裸体に目を奪われる。"

[[dialogue]]
speaker = "ソフィア"
# 「会長さんのが……男の人のってこうなってるんですね……」
line = "「会長さんのが……男の人のってこうなってるんですね……」"

[[dialogue]]
speaker = "unk"
# 一度意識すると抑えようもなく、本能がむくむくと膨らむ。
line = "一度意識すると抑えようもなく、本能がむくむくと膨らむ。"

[[dialogue]]
speaker = "unk"
# だけどソフィは、緊張と興奮が入り混じったような、何とも言い難い表情で俺の股間を見つめていた。
line = "だけどソフィは、緊張と興奮が入り混じったような、何とも言い難い表情で俺の股間を見つめていた。"

[[dialogue]]
speaker = "ソフィア"
# 「興奮すると大きくなるって聞きましたけど、今がそうなんですか……？　あっ、言わなくていいです……」
line = "「興奮すると大きくなるって聞きましたけど、今がそうなんですか……？　あっ、言わなくていいです……」"

[[dialogue]]
speaker = "unk"
# 早く上がった方がいいかもしれない。せめて目は逸らした方がいいかもしれない。
line = "早く上がった方がいいかもしれない。せめて目は逸らした方がいいかもしれない。"

[[dialogue]]
speaker = "unk"
# けれど思考はまともに働かなくて、ソフィの裸体に見とれていた。
line = "けれど思考はまともに働かなくて、ソフィの裸体に見とれていた。"

[[dialogue]]
speaker = "ソフィア"
# 「ご、ごめんなさい……」
line = "「ご、ごめんなさい……」"

[[dialogue]]
speaker = "unk"
# ソフィが身を離そうとすると、不意にお互いの股間が当たって──
line = "ソフィが身を離そうとすると、不意にお互いの股間が当たって──"

[[dialogue]]
speaker = "ソフィア"
# 「ひゃっ……！？」
line = "「ひゃっ……！？」"

[[dialogue]]
speaker = "unk"
# 性器と性器が触れ合い、肉の柔らかさと、痺れるような快感が脳天へと走り抜け、無意識に体が跳ねた。
line = "性器と性器が触れ合い、肉の柔らかさと、痺れるような快感が脳天へと走り抜け、無意識に体が跳ねた。"

[[dialogue]]
speaker = "ソフィア"
# 「今の、なに……？」
line = "「今の、なに……？」"

[[dialogue]]
speaker = "unk"
# 未知の刺激に驚きの声を漏らすソフィ。
line = "未知の刺激に驚きの声を漏らすソフィ。"

[[dialogue]]
speaker = "unk"
# 戸惑いながらも、さっきの感触を確かめるようにおずおずと股間を近づけていって……
line = "戸惑いながらも、さっきの感触を確かめるようにおずおずと股間を近づけていって……"

[[dialogue]]
speaker = "ソフィア"
# 「ふああっ……<emoji=heart04>」
line = "「ふああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その瞬間、確かな快感の声がこぼれる。
line = "その瞬間、確かな快感の声がこぼれる。"

[[dialogue]]
speaker = "ソフィア"
# 「もうちょっと……」
line = "「もうちょっと……」"

[[dialogue]]
speaker = "unk"
# 今のソフィは初めて性の芽生えを経験した子どものようで、熱に浮かされたように、また自分の股間をペニスに押し付けていく。
line = "今のソフィは初めて性の芽生えを経験した子どものようで、熱に浮かされたように、また自分の股間をペニスに押し付けていく。"

[[dialogue]]
speaker = "ソフィア"
# 「んんんっ……<emoji=heart04>」
line = "「んんんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# より確かに感じる肉の弾力。
line = "より確かに感じる肉の弾力。"

[[dialogue]]
speaker = "unk"
# 温かくてぷにぷにした感触がいきり立ったペニスに密着し、さらなる快感を求めて腰が勝手に動き出す。
line = "温かくてぷにぷにした感触がいきり立ったペニスに密着し、さらなる快感を求めて腰が勝手に動き出す。"

[[dialogue]]
speaker = "ソフィア"
# 「ふ……あっ……はぁ……はんっ……<emoji=heart04>　会長さんの、熱い……はぁはぁ……はっ、はぁ、んん～……<emoji=heart04>」
line = "「ふ……あっ……はぁ……はんっ……<emoji=heart04>　会長さんの、熱い……はぁはぁ……はっ、はぁ、んん～……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「会長さんの、おち○ちんが、擦れて……はぁ、はっ、ん……変になりそう……ん、はぁん……<emoji=heart04>」
line = "「会長さんの、おち○ちんが、擦れて……はぁ、はっ、ん……変になりそう……ん、はぁん……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# お湯の中で性器が摩擦する度、いつもは冷静なソフィの口からくぐもった吐息がこぼれる。
line = "お湯の中で性器が摩擦する度、いつもは冷静なソフィの口からくぐもった吐息がこぼれる。"

[[dialogue]]
speaker = "unk"
# 理性もお湯の熱さに溶けてしまって、水の抵抗を感じながらお互いに腰を使う。
line = "理性もお湯の熱さに溶けてしまって、水の抵抗を感じながらお互いに腰を使う。"

[[dialogue]]
speaker = "ソフィア"
# 「んん……ふ……あっ……はあぁ……あっ、はぁ……会長さんのおち○ちん、硬くて大きいです……」
line = "「んん……ふ……あっ……はあぁ……あっ、はぁ……会長さんのおち○ちん、硬くて大きいです……」"

[[dialogue]]
speaker = "ソフィア"
# 「これ、止まらない……ふっ……あ、はっ……頭、ふわふわする……<emoji=heart04>」
line = "「これ、止まらない……ふっ……あ、はっ……頭、ふわふわする……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そんなつもりじゃなかったのに、淫らなことだとわかっているはずなのに……体が勝手に動く。
line = "そんなつもりじゃなかったのに、淫らなことだとわかっているはずなのに……体が勝手に動く。"

[[dialogue]]
speaker = "ソフィア"
# 「ダメ、なのに……ふあっ、あ……んん～……おまた、ジンジンして……あ、ぬるぬるしてきた……」
line = "「ダメ、なのに……ふあっ、あ……んん～……おまた、ジンジンして……あ、ぬるぬるしてきた……」"

[[dialogue]]
speaker = "unk"
# 蜜は風呂の湯に混ざって流れてしまうが、ソフィと密着している部分だけ愛液で濡れてさらなる快感を生む。
line = "蜜は風呂の湯に混ざって流れてしまうが、ソフィと密着している部分だけ愛液で濡れてさらなる快感を生む。"

[[dialogue]]
speaker = "ソフィア"
# 「は……ふぁっ、あんっ……おち○ちん、ぬるぬるするの、いい……はぁはっ、あ、ん……もっとぉ……<emoji=heart04>」
line = "「は……ふぁっ、あんっ……おち○ちん、ぬるぬるするの、いい……はぁはっ、あ、ん……もっとぉ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「はぁ、はっ、んん……気持ち、いい……ふっ、あ……おち○ちん、気持ち、いいよぉ……<emoji=heart04>」
line = "「はぁ、はっ、んん……気持ち、いい……ふっ、あ……おち○ちん、気持ち、いいよぉ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 湯の温度は変わっていないはずなのに、まるで鍋釜で茹でられているみたいにどんどん体が熱くなってくる。
line = "湯の温度は変わっていないはずなのに、まるで鍋釜で茹でられているみたいにどんどん体が熱くなってくる。"

[[dialogue]]
speaker = "unk"
# 性器を擦り合わせるごとに、もっとソフィを感じたくなって、押し付ける力が少しずつ強くなる。
line = "性器を擦り合わせるごとに、もっとソフィを感じたくなって、押し付ける力が少しずつ強くなる。"

[[dialogue]]
speaker = "ソフィア"
# 「ふあぁ……おま○こ、熱いぃ……おち○ちん、おまたでゴシゴシするの好きぃ……ふっ……んっ、はぁ、はぁ……<emoji=heart04>」
line = "「ふあぁ……おま○こ、熱いぃ……おち○ちん、おまたでゴシゴシするの好きぃ……ふっ……んっ、はぁ、はぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「おち○ちん……おち○ちん……もっとぉ……ふ……あっ、は、はんっ……おま○こ、いい……<emoji=heart04>」
line = "「おち○ちん……おち○ちん……もっとぉ……ふ……あっ、は、はんっ……おま○こ、いい……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 白い肌を火照らせ、小さな体を揺らして、性器を擦り付けるのに夢中になるソフィ。
line = "白い肌を火照らせ、小さな体を揺らして、性器を擦り付けるのに夢中になるソフィ。"

[[dialogue]]
speaker = "unk"
# もう羞恥心も溶けてしまったのか、うわごとのように卑猥な言葉を何度も口にしていた。
line = "もう羞恥心も溶けてしまったのか、うわごとのように卑猥な言葉を何度も口にしていた。"

[[dialogue]]
speaker = "ソフィア"
# 「おち○ちん、もっと欲しい……です……はぁ、はぁ、あんっ……ふ、んん～っ<emoji=heart04>」
line = "「おち○ちん、もっと欲しい……です……はぁ、はぁ、あんっ……ふ、んん～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「はっ、はっ……ふぁ、んん……もっと、もっとぉ……もっといっぱい、おち○ちん、してくださいっ……」
line = "「はっ、はっ……ふぁ、んん……もっと、もっとぉ……もっといっぱい、おち○ちん、してくださいっ……」"

[[dialogue]]
speaker = "unk"
# ソフィは腰を大きく引くと、スリットをためらいなくペニスの先端へと押し付けて──
line = "ソフィは腰を大きく引くと、スリットをためらいなくペニスの先端へと押し付けて──"

[[dialogue]]
speaker = "ソフィア"
# 「ふあぁあ～～～～っ！　会長さんのおち○ちん、入ってきた、ぁっ……<emoji=heart04>」
line = "「ふあぁあ～～～～っ！　会長さんのおち○ちん、入ってきた、ぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 怒張したペニスを呑み込み、華奢な体を震わせながら声を上げた。
line = "怒張したペニスを呑み込み、華奢な体を震わせながら声を上げた。"

[[dialogue]]
speaker = "unk"
# ソフィの中は風呂の湯よりずっと熱く、寒がりの彼女とは思えない体温で、火傷してしまうかと思うほど。
line = "ソフィの中は風呂の湯よりずっと熱く、寒がりの彼女とは思えない体温で、火傷してしまうかと思うほど。"

[[dialogue]]
speaker = "ソフィア"
# 「おち○ちんで、私の中、広がってますぅ……んんんっ、はぁっ、はっ……」
line = "「おち○ちんで、私の中、広がってますぅ……んんんっ、はぁっ、はっ……」"

[[dialogue]]
speaker = "unk"
# 体の小さなソフィらしく、中は狭く、愛液で濡れた粘膜が痛いぐらいにぎゅっと締め付けてくる。
line = "体の小さなソフィらしく、中は狭く、愛液で濡れた粘膜が痛いぐらいにぎゅっと締め付けてくる。"

[[dialogue]]
speaker = "unk"
# けれどソフィはその小さな体で、そのまま腰を動かし始めた。
line = "けれどソフィはその小さな体で、そのまま腰を動かし始めた。"

[[dialogue]]
speaker = "ソフィア"
# 「ふぅ……あっ……はっ、はんっ……おち○ちん、大きくて、硬い……はあぁっ、ふぁっ……あっ、んん～～っ<emoji=heart04>」
line = "「ふぅ……あっ……はっ、はんっ……おち○ちん、大きくて、硬い……はあぁっ、ふぁっ……あっ、んん～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「中で擦れてっ……あっ、あんっ……！　ふっ、はあぁっ、はっ……熱いおち○ちんで、お腹の中、ごしごしされてるっ……<emoji=heart04>」
line = "「中で擦れてっ……あっ、あんっ……！　ふっ、はあぁっ、はっ……熱いおち○ちんで、お腹の中、ごしごしされてるっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 普段は表情の控えめなソフィが、うっとりと恍惚とした顔で喘ぐ。
line = "普段は表情の控えめなソフィが、うっとりと恍惚とした顔で喘ぐ。"

[[dialogue]]
speaker = "unk"
# 破瓜の痛みも快感に押し流されたようで、自分から腰を揺らして何度も性器を擦り合わせていた。
line = "破瓜の痛みも快感に押し流されたようで、自分から腰を揺らして何度も性器を擦り合わせていた。"

[[dialogue]]
speaker = "ソフィア"
# 「これ、気持ちいい、ですっ……ふわあっ、あぁっ……おち○ちん、ズボズボって……はぁっ、あぁんっ……<emoji=heart04>」
line = "「これ、気持ちいい、ですっ……ふわあっ、あぁっ……おち○ちん、ズボズボって……はぁっ、あぁんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ２人で腰を前後に動かし、ペニスがソフィの中を出たり入ったりを繰り返す。
line = "２人で腰を前後に動かし、ペニスがソフィの中を出たり入ったりを繰り返す。"

[[dialogue]]
speaker = "ソフィア"
# 「はっ……あっ……あんっ<emoji=heart04>　会長さんっ……会長さんっ<emoji=heart04>」
line = "「はっ……あっ……あんっ<emoji=heart04>　会長さんっ……会長さんっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# よりつながりを求めて、唇を重ね合わせる。
line = "よりつながりを求めて、唇を重ね合わせる。"

[[dialogue]]
speaker = "ソフィア"
# 「んんっ……んちゅっ……んぅ<emoji=heart04>　はぁ……んっ……<emoji=heart04>」
line = "「んんっ……んちゅっ……んぅ<emoji=heart04>　はぁ……んっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「ふわぁっ、はぁんっ……んんっ……会長さんのおち○ちんで、中から広げられてますぅ……んん～っ<emoji=heart04>」
line = "「ふわぁっ、はぁんっ……んんっ……会長さんのおち○ちんで、中から広げられてますぅ……んん～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ソフィの中はたっぷりの愛液で満ちていて、ペニスを突き入れる度にとろとろの蜜が絡みつく。
line = "ソフィの中はたっぷりの愛液で満ちていて、ペニスを突き入れる度にとろとろの蜜が絡みつく。"

[[dialogue]]
speaker = "unk"
# 膣内の肉のひだでペニスの表面を撫でられ、ぞわぞわと悪寒めいた快感が駆け抜けた。
line = "膣内の肉のひだでペニスの表面を撫でられ、ぞわぞわと悪寒めいた快感が駆け抜けた。"

[[dialogue]]
speaker = "ソフィア"
# 「ひぁああっ、はっ、んんっ……こんなの、知らない……これ、好き……ふあっ、あぁ～っ……<emoji=heart04>」
line = "「ひぁああっ、はっ、んんっ……こんなの、知らない……これ、好き……ふあっ、あぁ～っ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「おち○ちん熱くてっ、お腹の中、あったかいですっ……ふああっ、あっ、ああんっ……ああぁ～っ<emoji=heart04>」
line = "「おち○ちん熱くてっ、お腹の中、あったかいですっ……ふああっ、あっ、ああんっ……ああぁ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# いつもの真面目さはとろけてしまって、互いの性器でただつながることに集中する。
line = "いつもの真面目さはとろけてしまって、互いの性器でただつながることに集中する。"

[[dialogue]]
speaker = "unk"
# そのだらしない顔はまるで酔っているようで、初めてなのにすっかり快楽の虜になっていた。
line = "そのだらしない顔はまるで酔っているようで、初めてなのにすっかり快楽の虜になっていた。"

[[dialogue]]
speaker = "ソフィア"
# 「ひぁあ～～っ<emoji=heart04>　おち○ちんで、おま○こされるの気持ちいいっ……<emoji=heart04>　はぁああっ、はっ、はっ……んん～っ<emoji=heart04>」
line = "「ひぁあ～～っ<emoji=heart04>　おち○ちんで、おま○こされるの気持ちいいっ……<emoji=heart04>　はぁああっ、はっ、はっ……んん～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ひたすら腰を押して、引いて、快楽を堪能する。
line = "ひたすら腰を押して、引いて、快楽を堪能する。"

[[dialogue]]
speaker = "unk"
# 理性をとろとろに溶かされながら、俺もソフィも夢中になって腰を振っていた。
line = "理性をとろとろに溶かされながら、俺もソフィも夢中になって腰を振っていた。"

[[dialogue]]
speaker = "ソフィア"
# 「あっ、んんんっ……<emoji=heart04>　お腹の中、おち○ちんでゴリゴリされてぇっ……んはっ、はっ、ああんっ……<emoji=heart04>」
line = "「あっ、んんんっ……<emoji=heart04>　お腹の中、おち○ちんでゴリゴリされてぇっ……んはっ、はっ、ああんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「はあぁ、はぁ……んっ、んぅっ……はあぁっ、はっ、はんっ……おち○ちん太いぃ……んんはっ、んんっ……<emoji=heart04>」
line = "「はあぁ、はぁ……んっ、んぅっ……はあぁっ、はっ、はんっ……おち○ちん太いぃ……んんはっ、んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 普段の寒がりな彼女と対照的に、火傷しそうに熱いソフィの中。
line = "普段の寒がりな彼女と対照的に、火傷しそうに熱いソフィの中。"

[[dialogue]]
speaker = "unk"
# 熱々のお湯に浸かるみたいに、パンパンに膨張した敏感なペニスでソフィを感じながら、ピストンを続ける。
line = "熱々のお湯に浸かるみたいに、パンパンに膨張した敏感なペニスでソフィを感じながら、ピストンを続ける。"

[[dialogue]]
speaker = "ソフィア"
# 「もっと……ゴリゴリしてぇ……はぁっ、ふぁっ、んんっ……ひぁああ～っ<emoji=heart04>」
line = "「もっと……ゴリゴリしてぇ……はぁっ、ふぁっ、んんっ……ひぁああ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「おま○こ、もっと擦ってください……あっ、はっ、はっ……おち○ちん、もっと、もっとぉ……<emoji=heart04>」
line = "「おま○こ、もっと擦ってください……あっ、はっ、はっ……おち○ちん、もっと、もっとぉ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「んんん～～っ<emoji=heart04>　はぁっ、はっ、深いぃっ……<emoji=heart04>　ふあっ、はっ、はっ……おち○ちん、激し、いっ……<emoji=heart04>」
line = "「んんん～～っ<emoji=heart04>　はぁっ、はっ、深いぃっ……<emoji=heart04>　ふあっ、はっ、はっ……おち○ちん、激し、いっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「はあぁっ、はっ、はんっ……<emoji=heart04>　おち○ちん、いっぱい、ズンズン来てますぅっ……<emoji=heart04>　ふわぁっ、はっ、ああぁ～っ<emoji=heart04>」
line = "「はあぁっ、はっ、はんっ……<emoji=heart04>　おち○ちん、いっぱい、ズンズン来てますぅっ……<emoji=heart04>　ふわぁっ、はっ、ああぁ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# もうソフィを感じることしか考えられない。
line = "もうソフィを感じることしか考えられない。"

[[dialogue]]
speaker = "unk"
# お風呂の中でめいっぱい体を揺らし、大きく速く動こうとするソフィ。
line = "お風呂の中でめいっぱい体を揺らし、大きく速く動こうとするソフィ。"

[[dialogue]]
speaker = "unk"
# 俺も奥めがけて叩きつけるように、しゃにむにペニスを突き入れる。
line = "俺も奥めがけて叩きつけるように、しゃにむにペニスを突き入れる。"

[[dialogue]]
speaker = "ソフィア"
# 「んはっ……あっ、あっ、ああんっ<emoji=heart04>　はぁっ、はっ、あぁっ……おま○こ、溶けちゃいそうですっ……気持ちいいっ、んんっ……<emoji=heart04>」
line = "「んはっ……あっ、あっ、ああんっ<emoji=heart04>　はぁっ、はっ、あぁっ……おま○こ、溶けちゃいそうですっ……気持ちいいっ、んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「ひぁああっ、ああぁ～っ<emoji=heart04>　会長さんのおち○ちん、奥当たって……んんーーっ<emoji=heart04>　コツコツ当たってますぅっ……<emoji=heart04>」
line = "「ひぁああっ、ああぁ～っ<emoji=heart04>　会長さんのおち○ちん、奥当たって……んんーーっ<emoji=heart04>　コツコツ当たってますぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「おち○ちんで、お腹いっぱいになってますっ……はぁはっ、はんっ、んんっ……<emoji=heart04>　あっ、はっ、はっ、ああぁ～っ<emoji=heart04>」
line = "「おち○ちんで、お腹いっぱいになってますっ……はぁはっ、はんっ、んんっ……<emoji=heart04>　あっ、はっ、はっ、ああぁ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 爆発しそうに膨らんだ亀頭が一番奥に届く度、ソフィの体が震える。
line = "爆発しそうに膨らんだ亀頭が一番奥に届く度、ソフィの体が震える。"

[[dialogue]]
speaker = "unk"
# ソフィの小さな体を俺のペニスで満たすのが心地いい。
line = "ソフィの小さな体を俺のペニスで満たすのが心地いい。"

[[dialogue]]
speaker = "ソフィア"
# 「ふわぁっ、あっ、はんっ……<emoji=heart04>　おま○こ熱いぃっ……お腹、熱くて、奥キュンキュンしますっ……<emoji=heart04>」
line = "「ふわぁっ、あっ、はんっ……<emoji=heart04>　おま○こ熱いぃっ……お腹、熱くて、奥キュンキュンしますっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 膣が痙攣し、ペニスをきゅうきゅうと締め付けてくるのがたまらない。
line = "膣が痙攣し、ペニスをきゅうきゅうと締め付けてくるのがたまらない。"

[[dialogue]]
speaker = "unk"
# さらにもう一度唇を重ね、舌を絡めてソフィを味わう。
line = "さらにもう一度唇を重ね、舌を絡めてソフィを味わう。"

[[dialogue]]
speaker = "ソフィア"
# 「んちゅっ……ちゅるっ、ちゅるるるっ<emoji=heart04>　ふぁ、あんっ……れろ、れろ、ちゅぱっ……じゅるるっ──んん～っ<emoji=heart04>」
line = "「んちゅっ……ちゅるっ、ちゅるるるっ<emoji=heart04>　ふぁ、あんっ……れろ、れろ、ちゅぱっ……じゅるるっ──んん～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「ぷはぁ……気持ち良くて、溶けちゃうっ……はっ、はあぁ、はぁ……気持ち良すぎて、おかしくなっちゃいますぅっ……<emoji=heart04>」
line = "「ぷはぁ……気持ち良くて、溶けちゃうっ……はっ、はあぁ、はぁ……気持ち良すぎて、おかしくなっちゃいますぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「んんっ……！？　おち○ちんビクビクしてっ……はっ、あっ……私の中で、おち○ちん暴れてっ……はっ、はぁんっ……<emoji=heart04>」
line = "「んんっ……！？　おち○ちんビクビクしてっ……はっ、あっ……私の中で、おち○ちん暴れてっ……はっ、はぁんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 限界を知らせるように、ソフィの中でペニスが脈打つ。
line = "限界を知らせるように、ソフィの中でペニスが脈打つ。"

[[dialogue]]
speaker = "unk"
# 腰の奥で圧力が高まって爆発する寸前で、ペニスを締め付ける膣もひくひくと震えて前兆を伝えてきた。
line = "腰の奥で圧力が高まって爆発する寸前で、ペニスを締め付ける膣もひくひくと震えて前兆を伝えてきた。"

[[dialogue]]
speaker = "ソフィア"
# 「ふぁっ、はっ、はっ、ああっ……<emoji=heart04>　すごいっ……はっ、はぁ……おち○ちんすごいですぅっ……<emoji=heart04>」
line = "「ふぁっ、はっ、はっ、ああっ……<emoji=heart04>　すごいっ……はっ、はぁ……おち○ちんすごいですぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「はぁはぁ、はっ、あんっ……あっ、あっ、あっ、あぁ～っ<emoji=heart04>　熱いおち○ちん好き、大好きぃっ……<emoji=heart04>」
line = "「はぁはぁ、はっ、あんっ……あっ、あっ、あっ、あぁ～っ<emoji=heart04>　熱いおち○ちん好き、大好きぃっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「はっ、はっ、は、はんっ……<emoji=heart04>　も、もうダメ……な、何か来ちゃうっ……ふぁっ、ああっ……頭、真っ白に……」
line = "「はっ、はっ、は、はんっ……<emoji=heart04>　も、もうダメ……な、何か来ちゃうっ……ふぁっ、ああっ……頭、真っ白に……」"

[[dialogue]]
speaker = "ソフィア"
# 「来るっ、来ちゃうぅっ……<emoji=heart04>　あっ、あっ、あっ、あ、あんっ……<emoji=heart04>　はぁはっ、は、あぁ──」
line = "「来るっ、来ちゃうぅっ……<emoji=heart04>　あっ、あっ、あっ、あ、あんっ……<emoji=heart04>　はぁはっ、は、あぁ──」"

[[dialogue]]
speaker = "ソフィア"
# 「んんぁああ～～～～～～～～～～っ！！」
line = "「んんぁああ～～～～～～～～～～っ！！」"

[[dialogue]]
speaker = "unk"
# ソフィアの奥で情欲が爆ぜ、さらにその奥へと熱が迸っていく。
line = "ソフィアの奥で情欲が爆ぜ、さらにその奥へと熱が迸っていく。"

[[dialogue]]
speaker = "ソフィア"
# 「ふあぁあっ、はぁっ、あ──熱いっ、熱いですぅっ……<emoji=heart04>　熱いの、びゅーって、奥に……んんんっ<emoji=heart04>」
line = "「ふあぁあっ、はぁっ、あ──熱いっ、熱いですぅっ……<emoji=heart04>　熱いの、びゅーって、奥に……んんんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「おち○ちん、お腹の中でドクドクして……はあぁんっ……<emoji=heart04>　はぁ、はぁ、……はぁ～っ<emoji=heart04>」
line = "「おち○ちん、お腹の中でドクドクして……はあぁんっ……<emoji=heart04>　はぁ、はぁ、……はぁ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 絶頂と同時に膣壁が収縮し、ペニスにぴったりとまとわりつく。
line = "絶頂と同時に膣壁が収縮し、ペニスにぴったりとまとわりつく。"

[[dialogue]]
speaker = "unk"
# 隙間なく密着する粘膜に絞られながら、ソフィの中に精を注ぎ続けた。
line = "隙間なく密着する粘膜に絞られながら、ソフィの中に精を注ぎ続けた。"

[[dialogue]]
speaker = "ソフィア"
# 「はあぁ、はっ……熱いのいっぱい出てっ……はあぁ、あっ……んんん～～～～っ<emoji=heart04><emoji=heart04>」
line = "「はあぁ、はっ……熱いのいっぱい出てっ……はあぁ、あっ……んんん～～～～っ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「はあぁ、はぁ、はぁ……は、あぁ……会長さんので、お腹いっぱい、です……」
line = "「はあぁ、はぁ、はぁ……は、あぁ……会長さんので、お腹いっぱい、です……」"

[[dialogue]]
speaker = "ソフィア"
# 「まだ、熱い……はあぁ、はっ、はぁ……はぁ～……」
line = "「まだ、熱い……はあぁ、はっ、はぁ……はぁ～……」"

[[dialogue]]
speaker = "unk"
# 目はとろんとさせてお湯に揺蕩い、まだ夢見心地のようだ。
line = "目はとろんとさせてお湯に揺蕩い、まだ夢見心地のようだ。"

[[dialogue]]
speaker = "unk"
# いや、俺もまだふわふわしていて、夢見心地なのは俺も変わらない。
line = "いや、俺もまだふわふわしていて、夢見心地なのは俺も変わらない。"

[[dialogue]]
speaker = "ソフィア"
# 「はぁはぁ……暑い……さすがに温まり過ぎたかも、です……」
line = "「はぁはぁ……暑い……さすがに温まり過ぎたかも、です……」"

[[dialogue]]
speaker = "unk"
# ペニスを抜くこともできないまま湯船に浸かり、思考と疲労が回復するのを待つ。
line = "ペニスを抜くこともできないまま湯船に浸かり、思考と疲労が回復するのを待つ。"

[[dialogue]]
speaker = "unk"
# つながったところからソフィの温もりを感じ、快感とは違う、不思議な充足感が胸に満ちていく。
line = "つながったところからソフィの温もりを感じ、快感とは違う、不思議な充足感が胸に満ちていく。"

[[dialogue]]
speaker = "ソフィア"
# 「好きです、会長さん……」
line = "「好きです、会長さん……」"

[[dialogue]]
speaker = "unk"
# 薄い胸を上下させながら、ソフィがぽつりと呟く。
line = "薄い胸を上下させながら、ソフィがぽつりと呟く。"

[[dialogue]]
speaker = "unk"
# 落ち着いたらソフィの顔をまともに見れないかもしれないけど……これはこれで良かったと密かに思うのだった。
line = "落ち着いたらソフィの顔をまともに見れないかもしれないけど……これはこれで良かったと密かに思うのだった。"

[[dialogue]]
speaker = "unk"
# テンプレートシナリオ
line = "テンプレートシナリオ"
