[[dialogue]]
speaker = "unk"
# 第２話,初めてのチャレンジ,P
line = "第２話,初めてのチャレンジ,P"

[[dialogue]]
speaker = "トリシャ"
# 「えぇぇ……」
line = "「えぇぇ……」"

[[dialogue]]
speaker = "unk"
# 海で泳いでみませんか──
line = "海で泳いでみませんか──"

[[dialogue]]
speaker = "unk"
# そう告げられたトリシャさんは、まったく乗り気ではない様子だった。
line = "そう告げられたトリシャさんは、まったく乗り気ではない様子だった。"

[[dialogue]]
speaker = "トリシャ"
# 「海は……綺麗……それはそう……私にもよくわかりました。かつてない絶景に、心洗われるようでもありました」
line = "「海は……綺麗……それはそう……私にもよくわかりました。かつてない絶景に、心洗われるようでもありました」"

[[dialogue]]
speaker = "トリシャ"
# 「ですが……これだけ広いのなら……見てるだけでも十分ではありませんか？」
line = "「ですが……これだけ広いのなら……見てるだけでも十分ではありませんか？」"

[[dialogue]]
speaker = "トリシャ"
# 「私はそのように──このちっぽけな体で海に足を踏み入れようとは、思いません……」
line = "「私はそのように──このちっぽけな体で海に足を踏み入れようとは、思いません……」"

[[dialogue]]
speaker = "unk"
# 泳ぎたくない？
line = "泳ぎたくない？"

[[dialogue]]
speaker = "unk"
# 怖い？
line = "怖い？"

[[dialogue]]
speaker = "トリシャ"
# 「…………（こく）」
line = "「…………（こく）」"

[[dialogue]]
speaker = "トリシャ"
# 「だって……こんなに大きいんですよ。それにとても深いと聞きます。眺めているだけでも圧倒されたのに……入るだなんて……」
line = "「だって……こんなに大きいんですよ。それにとても深いと聞きます。眺めているだけでも圧倒されたのに……入るだなんて……」"

[[dialogue]]
speaker = "unk"
# 楽しいですよ
line = "楽しいですよ"

[[dialogue]]
speaker = "unk"
# 無理強いはしない
line = "無理強いはしない"

[[dialogue]]
speaker = "トリシャ"
# 「確かに……皆さん、楽しそうに海辺ではしゃいでおられます……」
line = "「確かに……皆さん、楽しそうに海辺ではしゃいでおられます……」"

[[dialogue]]
speaker = "トリシャ"
# 「なるほど……深いところまで踏み込む必要はないのですね。波打ち際で<ruby=たわむ>戯</ruby>れるくらいなら、私にもできるかもしれません」
line = "「なるほど……深いところまで踏み込む必要はないのですね。波打ち際で<ruby>戯<rt>たわむ</rt></ruby>れるくらいなら、私にもできるかもしれません」"

[[dialogue]]
speaker = "トリシャ"
# 「と思いましたが──うっかり波にさらわれてしまう恐れもあります。これは困りました……」
line = "「と思いましたが──うっかり波にさらわれてしまう恐れもあります。これは困りました……」"

[[dialogue]]
speaker = "トリシャ"
# 「まずは占いを。これで最高の運勢が出たら、足先くらい入ってみるということで……」
line = "「まずは占いを。これで最高の運勢が出たら、足先くらい入ってみるということで……」"

[[dialogue]]
speaker = "unk"
# と、その時──
line = "と、その時──"

[[dialogue]]
speaker = "リップル"
# 「オウ！　どんな悪い運勢でも、吹き飛ばしてくれるのが海の魅力デース！」
line = "「オウ！　どんな悪い運勢でも、吹き飛ばしてくれるのが海の魅力デース！」"

[[dialogue]]
speaker = "トリシャ"
# 「あ……リップルさん」
line = "「あ……リップルさん」"

[[dialogue]]
speaker = "リップル"
# 「ハーイ、トリシャ！　海で泳ぎたいならお手伝いシマース！」
line = "「ハーイ、トリシャ！　海で泳ぎたいならお手伝いシマース！」"

[[dialogue]]
speaker = "トリシャ"
# 「あ、いえ……そこまでは。泳ぐのはまだ……怖いので……」
line = "「あ、いえ……そこまでは。泳ぐのはまだ……怖いので……」"

[[dialogue]]
speaker = "リップル"
# 「なんともったいないデース！　海は広くて綺麗なだけではありまセン──すべてを包み込んでくれる母のような存在なのデース！」
line = "「なんともったいないデース！　海は広くて綺麗なだけではありまセン──すべてを包み込んでくれる母のような存在なのデース！」"

[[dialogue]]
speaker = "トリシャ"
# 「な、なるほど……？」
line = "「な、なるほど……？」"

[[dialogue]]
speaker = "リップル"
# 「それに、海で一緒に遊んだあとはみんな仲良く友達デース！　疲れた体で食べるかき氷はサイコーですヨ～！」
line = "「それに、海で一緒に遊んだあとはみんな仲良く友達デース！　疲れた体で食べるかき氷はサイコーですヨ～！」"

[[dialogue]]
speaker = "トリシャ"
# 「……！　なんと……」
line = "「……！　なんと……」"

[[dialogue]]
speaker = "トリシャ"
# 「せっかくビーチにはこれだけ人がいるのに……誰ともお友達になれないのは……もったいないです」
line = "「せっかくビーチにはこれだけ人がいるのに……誰ともお友達になれないのは……もったいないです」"

[[dialogue]]
speaker = "リップル"
# 「トリシャは泳げないデースか？」
line = "「トリシャは泳げないデースか？」"

[[dialogue]]
speaker = "unk"
# 泳いだ経験がないから
line = "泳いだ経験がないから"

[[dialogue]]
speaker = "unk"
# トリシャさんは海が初めて
line = "トリシャさんは海が初めて"

[[dialogue]]
speaker = "リップル"
# 「オウ、了解デース！　それならばいいものがありマース！」
line = "「オウ、了解デース！　それならばいいものがありマース！」"

[[dialogue]]
speaker = "リップル"
# 「ＢＩＧ浮き輪デース！　これに掴まっていれば、泳げなくてもへっちゃらデース！」
line = "「ＢＩＧ浮き輪デース！　これに掴まっていれば、泳げなくてもへっちゃらデース！」"

[[dialogue]]
speaker = "トリシャ"
# 「ほほう……こんなよいものが」
line = "「ほほう……こんなよいものが」"

[[dialogue]]
speaker = "リップル"
# 「それに、ここはワタシのリゾート結界デース。どんなに流されても、遭難することはないので安心してくだサーイ♪」
line = "「それに、ここはワタシのリゾート結界デース。どんなに流されても、遭難することはないので安心してくだサーイ♪」"

[[dialogue]]
speaker = "トリシャ"
# 「ふむふむ……ありがとうございます。なんだかいける気がしてきました」
line = "「ふむふむ……ありがとうございます。なんだかいける気がしてきました」"

[[dialogue]]
speaker = "トリシャ"
# 「行きましょう、会長さん……このビッグウェーブ、逃がすわけにはいきません」
line = "「行きましょう、会長さん……このビッグウェーブ、逃がすわけにはいきません」"

[[dialogue]]
speaker = "トリシャ"
# 「よ、よし……まずは足から入っていきますよ」
line = "「よ、よし……まずは足から入っていきますよ」"

[[dialogue]]
speaker = "トリシャ"
# 「ひゃっ……！　お、思ったより冷たいのですね。いえ、大丈夫です。私は寒さには強いので……」
line = "「ひゃっ……！　お、思ったより冷たいのですね。いえ、大丈夫です。私は寒さには強いので……」"

[[dialogue]]
speaker = "トリシャ"
# 「か、会長さんも隣にいてくださいね」
line = "「か、会長さんも隣にいてくださいね」"

[[dialogue]]
speaker = "unk"
# そばにいる
line = "そばにいる"

[[dialogue]]
speaker = "unk"
# わかった
line = "わかった"

[[dialogue]]
speaker = "トリシャ"
# 「フフ……あなたがいてくれると、安心感が湧き上がってきますね」
line = "「フフ……あなたがいてくれると、安心感が湧き上がってきますね」"

[[dialogue]]
speaker = "トリシャ"
# 「こうして腕も組めば……フフ、さらに安心です」
line = "「こうして腕も組めば……フフ、さらに安心です」"

[[dialogue]]
speaker = "unk"
# トリシャさんの柔らかな感触が、こちらの二の腕を包んだ。
line = "トリシャさんの柔らかな感触が、こちらの二の腕を包んだ。"

[[dialogue]]
speaker = "トリシャ"
# 「もうちょっと……もうちょっと行けそうです。一緒に来てくれますか……？」
line = "「もうちょっと……もうちょっと行けそうです。一緒に来てくれますか……？」"

[[dialogue]]
speaker = "トリシャ"
# 「きゃっ、波が……ふぅ。驚いてしまいますね──んぁっ……。な、慣れませんと……んっ」
line = "「きゃっ、波が……ふぅ。驚いてしまいますね──んぁっ……。な、慣れませんと……んっ」"

[[dialogue]]
speaker = "トリシャ"
# 「んっ──きゃぁっ……ご、ごめんなさい……」
line = "「んっ──きゃぁっ……ご、ごめんなさい……」"

[[dialogue]]
speaker = "unk"
# 大きめの波が来るたびにトリシャさんはびくっと震え、こちらに抱きついてきた。
line = "大きめの波が来るたびにトリシャさんはびくっと震え、こちらに抱きついてきた。"

[[dialogue]]
speaker = "トリシャ"
# 「会長さん……どうかしましたか？　先ほどから、なんだか前かがみの様子ですが……」
line = "「会長さん……どうかしましたか？　先ほどから、なんだか前かがみの様子ですが……」"

[[dialogue]]
speaker = "トリシャ"
# 「波で倒れそうになっているのでしょうか。でしたら、私がもっと密着して支えてあげなくては──」
line = "「波で倒れそうになっているのでしょうか。でしたら、私がもっと密着して支えてあげなくては──」"

[[dialogue]]
speaker = "トリシャ"
# 「……あれ。さらに前かがみになってしまいました。これは摩訶不思議です……」
line = "「……あれ。さらに前かがみになってしまいました。これは摩訶不思議です……」"

[[dialogue]]
speaker = "トリシャ"
# 「ですが……ふふ。気づいたら、太ももまで浸かってしまいました」
line = "「ですが……ふふ。気づいたら、太ももまで浸かってしまいました」"

[[dialogue]]
speaker = "トリシャ"
# 「慣れてみると……この波に揺られる感じも、楽しいものですね……ふふ」
line = "「慣れてみると……この波に揺られる感じも、楽しいものですね……ふふ」"

[[dialogue]]
speaker = "トリシャ"
# 「それとも……こんなに楽しいのは、隣にあなたがいるからでしょうか？」
line = "「それとも……こんなに楽しいのは、隣にあなたがいるからでしょうか？」"

[[dialogue]]
speaker = "unk"
# 至近距離で拝むトリシャさんの無邪気な笑顔は、ぎらつく太陽よりも眩しく感じた……。
line = "至近距離で拝むトリシャさんの無邪気な笑顔は、ぎらつく太陽よりも眩しく感じた……。"
