[[dialogue]]
speaker = "unk"
# 第４話,イニシュの記憶,P
line = "第４話,イニシュの記憶,P"

[[dialogue]]
speaker = "イニシュ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "イニシュ"
# 「……え？　近くに有名なラーメンのお店がある？　ああ、そうなのですか。それは気になりますね」
line = "「……え？　近くに有名なラーメンのお店がある？　ああ、そうなのですか。それは気になりますね」"

[[dialogue]]
speaker = "unk"
# フィオナやユウリと出会って以来、イニシュの様子がおかしい。
line = "フィオナやユウリと出会って以来、イニシュの様子がおかしい。"

[[dialogue]]
speaker = "unk"
# 好きなはずのラーメンに興味を示さないし、（元々あまり変わらないとはいえ）表情も暗い。
line = "好きなはずのラーメンに興味を示さないし、（元々あまり変わらないとはいえ）表情も暗い。"

[[dialogue]]
speaker = "unk"
# 何か思い出した？
line = "何か思い出した？"

[[dialogue]]
speaker = "イニシュ"
# 「……はい」
line = "「……はい」"

[[dialogue]]
speaker = "イニシュ"
# 「私には友達がいました。魔女ではない、人間の友人。たった１人の、かけがえのない親友」
line = "「私には友達がいました。魔女ではない、人間の友人。たった１人の、かけがえのない親友」"

[[dialogue]]
speaker = "イニシュ"
# 「彼女はリクリエで消滅しました。塵ひとつ残さず。跡形もなく」
line = "「彼女はリクリエで消滅しました。塵ひとつ残さず。跡形もなく」"

[[dialogue]]
speaker = "イニシュ"
# 「悲しい。悔しい。恨めしい」
line = "「悲しい。悔しい。恨めしい」"

[[dialogue]]
speaker = "イニシュ"
# 「彼女を失った。彼女を守れなかった」
line = "「彼女を失った。彼女を守れなかった」"

[[dialogue]]
speaker = "イニシュ"
# 「だから私は……リクリエと戦います」
line = "「だから私は……リクリエと戦います」"

[[dialogue]]
speaker = "イニシュ"
# 「きっと私は、リクリエと戦うためだけに眠り続けてきました。数千、数万年の時を超えて」
line = "「きっと私は、リクリエと戦うためだけに眠り続けてきました。数千、数万年の時を超えて」"

[[dialogue]]
speaker = "イニシュ"
# 「なのに──」
line = "「なのに──」"

[[dialogue]]
speaker = "イニシュ"
# 「私は彼女の名前も顔も思い出せない……」
line = "「私は彼女の名前も顔も思い出せない……」"

[[dialogue]]
speaker = "イニシュ"
# 「いつも明るく笑っていた……私とは正反対の女の子」
line = "「いつも明るく笑っていた……私とは正反対の女の子」"

[[dialogue]]
speaker = "イニシュ"
# 「引っ込み思案だった私を引っ張り回していたあの子」
line = "「引っ込み思案だった私を引っ張り回していたあの子」"

[[dialogue]]
speaker = "イニシュ"
# 「彼女がいたことは覚えているのに……彼女の声も言葉も思い出せません」
line = "「彼女がいたことは覚えているのに……彼女の声も言葉も思い出せません」"

[[dialogue]]
speaker = "イニシュ"
# 「彼女の存在さえ、最近まで忘却していました」
line = "「彼女の存在さえ、最近まで忘却していました」"

[[dialogue]]
speaker = "イニシュ"
# 「そんな私が……彼女を親友と呼んでいいのでしょうか」
line = "「そんな私が……彼女を親友と呼んでいいのでしょうか」"

[[dialogue]]
speaker = "unk"
# これから思い出せばいい
line = "これから思い出せばいい"

[[dialogue]]
speaker = "イニシュ"
# 「そうでしょうか。私が眠りから目覚めてから長い時が経つのに、彼女の存在を思い出したのはここ数日のことです」
line = "「そうでしょうか。私が眠りから目覚めてから長い時が経つのに、彼女の存在を思い出したのはここ数日のことです」"

[[dialogue]]
speaker = "イニシュ"
# 「それなのに、本当に彼女を思い出せるでしょうか。それどころかまた忘れてしまうかもしれません」
line = "「それなのに、本当に彼女を思い出せるでしょうか。それどころかまた忘れてしまうかもしれません」"

[[dialogue]]
speaker = "イニシュ"
# 「──！　アステラの出現を感知。行きましょう」
line = "「──！　アステラの出現を感知。行きましょう」"

[[dialogue]]
speaker = "イニシュ"
# 「アンブラル……ヴァナルガンド！」
line = "「アンブラル……ヴァナルガンド！」"

[[dialogue]]
speaker = "イニシュ"
# 「殲滅完了」
line = "「殲滅完了」"

[[dialogue]]
speaker = "unk"
# リクリエが憎い？
line = "リクリエが憎い？"

[[dialogue]]
speaker = "イニシュ"
# 「当然です」
line = "「当然です」"

[[dialogue]]
speaker = "イニシュ"
# 「リクリエが彼女を……あの子を消滅させた。憎くないはずがありません」
line = "「リクリエが彼女を……あの子を消滅させた。憎くないはずがありません」"

[[dialogue]]
speaker = "イニシュ"
# 「でも私に、リクリエを憎む資格があるのでしょうか」
line = "「でも私に、リクリエを憎む資格があるのでしょうか」"

[[dialogue]]
speaker = "イニシュ"
# 「のうのうと生き残っておきながら、あの子を忘れていた私に……」
line = "「のうのうと生き残っておきながら、あの子を忘れていた私に……」"

[[dialogue]]
speaker = "unk"
# イニシュは考えすぎだ
line = "イニシュは考えすぎだ"

[[dialogue]]
speaker = "イニシュ"
# 「あ──」
line = "「あ──」"

[[dialogue]]
speaker = "unk"
# その気持ちは親友のあかしだよ
line = "その気持ちは親友のあかしだよ"

[[dialogue]]
speaker = "イニシュ"
# 「そう……かもしれませんね」
line = "「そう……かもしれませんね」"

[[dialogue]]
speaker = "イニシュ"
# 「また思い出しました」
line = "「また思い出しました」"

[[dialogue]]
speaker = "イニシュ"
# 「魔女の寿命は人間より遥かに長い。避けられない別れが来る」
line = "「魔女の寿命は人間より遥かに長い。避けられない別れが来る」"

[[dialogue]]
speaker = "イニシュ"
# 「だから友達になれないと伝えたら──あの子に言われました」
line = "「だから友達になれないと伝えたら──あの子に言われました」"

[[dialogue]]
speaker = "イニシュ"
# 「“イニシュは考えすぎよ。友達は何年経っても友達なんだから”──って」
line = "「“イニシュは考えすぎよ。友達は何年経っても友達なんだから”──って」"

[[dialogue]]
speaker = "イニシュ"
# 「だから私たちは約束しました」
line = "「だから私たちは約束しました」"

[[dialogue]]
speaker = "イニシュ"
# 「私は若いまま、あの子だけ先に老いて死んでいく」
line = "「私は若いまま、あの子だけ先に老いて死んでいく」"

[[dialogue]]
speaker = "イニシュ"
# 「それでも……いつまでも……私たちは友達でいようと」
line = "「それでも……いつまでも……私たちは友達でいようと」"

[[dialogue]]
speaker = "イニシュ"
# 「私はあの子のことを思い出したいです」
line = "「私はあの子のことを思い出したいです」"

[[dialogue]]
speaker = "イニシュ"
# 「しかし記憶を取り戻すことで、またあの子を失う悲しみを味わうかもしれません。私はそれが怖いです」
line = "「しかし記憶を取り戻すことで、またあの子を失う悲しみを味わうかもしれません。私はそれが怖いです」"

[[dialogue]]
speaker = "イニシュ"
# 「だから──」
line = "「だから──」"

[[dialogue]]
speaker = "イニシュ"
# 「私がすべてを思い出した時、あなたがそばにいてくれることを願います」
line = "「私がすべてを思い出した時、あなたがそばにいてくれることを願います」"

[[dialogue]]
speaker = "イニシュ"
# 「あと、戦ったのでお腹が空きました。エネルギー補給が必要です」
line = "「あと、戦ったのでお腹が空きました。エネルギー補給が必要です」"

[[dialogue]]
speaker = "unk"
# ラーメン食べて帰ろう
line = "ラーメン食べて帰ろう"

[[dialogue]]
speaker = "イニシュ"
# 「はい」
line = "「はい」"
