[[dialogue]]
speaker = "unk"
# 第１話,びっくり留学生？,P
line = "第１話,びっくり留学生？,P"

[[dialogue]]
speaker = "マトイ"
# 「今日は星徒会のお仕事早く終わってよかったね。こうして帰りに寄り道できるし」
line = "「今日は星徒会のお仕事早く終わってよかったね。こうして帰りに寄り道できるし」"

[[dialogue]]
speaker = "アナ"
# 「話によれば、新しいお団子のお店はこの近くのはず。……おや？」
line = "「話によれば、新しいお団子のお店はこの近くのはず。……おや？」"

[[dialogue]]
speaker = "アイリーン"
# 「こんにちは、新星星徒会のみなさん」
line = "「こんにちは、新星星徒会のみなさん」"

[[dialogue]]
speaker = "マトイ"
# 「あなた、ネビュラの……なんでここに！？」
line = "「あなた、ネビュラの……なんでここに！？」"

[[dialogue]]
speaker = "アイリーン"
# 「──な～んてね！　せっかく会ったんだし仲良くしよーよ！」
line = "「──な～んてね！　せっかく会ったんだし仲良くしよーよ！」"

[[dialogue]]
speaker = "マトイ"
# 「えぇっ！？」
line = "「えぇっ！？」"

[[dialogue]]
speaker = "ミネルバ"
# 「ホー！」
line = "「ホー！」"

[[dialogue]]
speaker = "マトイ"
# 「なんというか、前会った時と全然雰囲気が違うような……」
line = "「なんというか、前会った時と全然雰囲気が違うような……」"

[[dialogue]]
speaker = "アイリーン"
# 「この前は、セドナさんが任務中はネビュラの構成員らしくしろって言うからお澄まししてたの。ほんとはみんなとお話したくてうずうずしてたんだから！」
line = "「この前は、セドナさんが任務中はネビュラの構成員らしくしろって言うからお澄まししてたの。ほんとはみんなとお話したくてうずうずしてたんだから！」"

[[dialogue]]
speaker = "アイリーン"
# 「というわけで……改めまして、魔女のアイリーンです！　人間界のこといろいろ教えてくれると嬉しいな」
line = "「というわけで……改めまして、魔女のアイリーンです！　人間界のこといろいろ教えてくれると嬉しいな」"

[[dialogue]]
speaker = "アイリーン"
# 「こっちは使い魔のミーちゃん！　ほんとはミネルバっていうんだけど、かわいいからいつもミーちゃんって呼んでるんだ」
line = "「こっちは使い魔のミーちゃん！　ほんとはミネルバっていうんだけど、かわいいからいつもミーちゃんって呼んでるんだ」"

[[dialogue]]
speaker = "ミネルバ"
# 「ホー」
line = "「ホー」"

[[dialogue]]
speaker = "アナ"
# 「アナです」
line = "「アナです」"

[[dialogue]]
speaker = "マトイ"
# 「私は詠野マトイ。こちらこそ……よろしく？」
line = "「私は詠野マトイ。こちらこそ……よろしく？」"

[[dialogue]]
speaker = "unk"
# よろしく
line = "よろしく"

[[dialogue]]
speaker = "マトイ"
# 「ていうか、どうして流星市国にいるの？　普通にこっち来て平気なの？」
line = "「ていうか、どうして流星市国にいるの？　普通にこっち来て平気なの？」"

[[dialogue]]
speaker = "アイリーン"
# 「うん。新星学園じゃないけど、今は流星市国の学校に短期留学中ってことになってるから」
line = "「うん。新星学園じゃないけど、今は流星市国の学校に短期留学中ってことになってるから」"

[[dialogue]]
speaker = "マトイ"
# 「留学！？　書類とかどうなってるの……？」
line = "「留学！？　書類とかどうなってるの……？」"

[[dialogue]]
speaker = "アイリーン"
# 「うーん、そこはネビュラの人がやってくれたからわかんない。会長さんたちは何してたところ？　今から遊びに行くの？」
line = "「うーん、そこはネビュラの人がやってくれたからわかんない。会長さんたちは何してたところ？　今から遊びに行くの？」"

[[dialogue]]
speaker = "アナ"
# 「はい、これから新しいお団子のお店に行くところでした」
line = "「はい、これから新しいお団子のお店に行くところでした」"

[[dialogue]]
speaker = "アイリーン"
# 「お団子！　お母さんに聞いたことある！」
line = "「お団子！　お母さんに聞いたことある！」"

[[dialogue]]
speaker = "unk"
# アイリーンも来る？
line = "アイリーンも来る？"

[[dialogue]]
speaker = "アイリーン"
# 「うん、行く！」
line = "「うん、行く！」"

[[dialogue]]
speaker = "マトイ"
# 「うちの星徒会長、もう馴染んでおられる……！」
line = "「うちの星徒会長、もう馴染んでおられる……！」"

[[dialogue]]
speaker = "アナ"
# 「ふむ、ここが噂のお店ですか。店内での飲食だけでなく持ち帰りもできるようです」
line = "「ふむ、ここが噂のお店ですか。店内での飲食だけでなく持ち帰りもできるようです」"

[[dialogue]]
speaker = "アナ"
# 「オーソドックスなあんこやみたらしもいいですが、くるみ味噌も捨てがたい……チョコソースもありますね。合うのでしょうか？」
line = "「オーソドックスなあんこやみたらしもいいですが、くるみ味噌も捨てがたい……チョコソースもありますね。合うのでしょうか？」"

[[dialogue]]
speaker = "アイリーン"
# 「どんな味がするのかな～？　ねぇねぇ、オススメとかある？」
line = "「どんな味がするのかな～？　ねぇねぇ、オススメとかある？」"

[[dialogue]]
speaker = "unk"
# ここはあえて……チョコ！
line = "ここはあえて……チョコ！"

[[dialogue]]
speaker = "アイリーン"
# 「じゃあそれにしよっと！　チョコ団子くださーい！」
line = "「じゃあそれにしよっと！　チョコ団子くださーい！」"

[[dialogue]]
speaker = "アイリーン"
# 「いただきまーす！　あむっ」
line = "「いただきまーす！　あむっ」"

[[dialogue]]
speaker = "マトイ"
# 「ど、どう？　お団子にチョコってあり……？　というか、魔女の味覚ってどうなんだろ……？」
line = "「ど、どう？　お団子にチョコってあり……？　というか、魔女の味覚ってどうなんだろ……？」"

[[dialogue]]
speaker = "アイリーン"
# 「ん～っ、おいしーっ！！」
line = "「ん～っ、おいしーっ！！」"

[[dialogue]]
speaker = "アナ"
# 「これは……アリ寄りのアリですね」
line = "「これは……アリ寄りのアリですね」"

[[dialogue]]
speaker = "マトイ"
# 「それは完璧にアリなんじゃ……。じゃあ私も食べてみよっと。あ、ほんとにおいしい」
line = "「それは完璧にアリなんじゃ……。じゃあ私も食べてみよっと。あ、ほんとにおいしい」"

[[dialogue]]
speaker = "unk"
# 俺も好きかも
line = "俺も好きかも"

[[dialogue]]
speaker = "アイリーン"
# 「甘くてもちもちしてる～♪　魔女の森でこんなの食べたことない！　ほらミーちゃんも！」
line = "「甘くてもちもちしてる～♪　魔女の森でこんなの食べたことない！　ほらミーちゃんも！」"

[[dialogue]]
speaker = "マトイ"
# 「フクロウってお団子食べられるの！？」
line = "「フクロウってお団子食べられるの！？」"

[[dialogue]]
speaker = "ミネルバ"
# 「ホホー！」
line = "「ホホー！」"

[[dialogue]]
speaker = "マトイ"
# 「ほんとに食べた！？　しかもけっこう喜んでる……？」
line = "「ほんとに食べた！？　しかもけっこう喜んでる……？」"

[[dialogue]]
speaker = "アイリーン"
# 「ミーちゃんも気に入ったみたい。はむはむ、はむはむ……ん～っ、おいひいっ」
line = "「ミーちゃんも気に入ったみたい。はむはむ、はむはむ……ん～っ、おいひいっ」"

[[dialogue]]
speaker = "マトイ"
# 「うーん……ネビュラの人だから身構えちゃったけど、今のところは大丈夫そうかな……？」
line = "「うーん……ネビュラの人だから身構えちゃったけど、今のところは大丈夫そうかな……？」"

[[dialogue]]
speaker = "アイリーン"
# 「ネビュラの人たちにも持って帰ってあげよっかな？　でもセドナさん甘いもの好きじゃないしなー」
line = "「ネビュラの人たちにも持って帰ってあげよっかな？　でもセドナさん甘いもの好きじゃないしなー」"

[[dialogue]]
speaker = "アイリーン"
# 「まぁいいや、全部食べちゃえっ♪　はむはむ……ごちそうさま！」
line = "「まぁいいや、全部食べちゃえっ♪　はむはむ……ごちそうさま！」"

[[dialogue]]
speaker = "アイリーン"
# 「会長さんのオススメにして良かった！　ありがとね、会長さん！」
line = "「会長さんのオススメにして良かった！　ありがとね、会長さん！」"
