[[dialogue]]
speaker = "unk"
# 第３話,昔日のかけら,P
line = "第３話,昔日のかけら,P"

[[dialogue]]
speaker = "unk"
# 週末、母さんが夜までいないということで、コハルコがごはんを作りに来てくれた。
line = "週末、母さんが夜までいないということで、コハルコがごはんを作りに来てくれた。"

[[dialogue]]
speaker = "unk"
# 俺だって料理はひと通りできるけど、恋人の手料理は特別だ。
line = "俺だって料理はひと通りできるけど、恋人の手料理は特別だ。"

[[dialogue]]
speaker = "コハルコ"
# 「はい、ミートソーススパゲッティ出来上がり～。付け合わせにサラダもあるよ」
line = "「はい、ミートソーススパゲッティ出来上がり～。付け合わせにサラダもあるよ」"

[[dialogue]]
speaker = "コハルコ"
# 「ふふっ、お口に合うといいんだけど」
line = "「ふふっ、お口に合うといいんだけど」"

[[dialogue]]
speaker = "unk"
# 美味しいっ！
line = "美味しいっ！"

[[dialogue]]
speaker = "コハルコ"
# 「ならよかった」
line = "「ならよかった」"

[[dialogue]]
speaker = "コハルコ"
# 「時間がない時は市販のソースを使うこともあるけど、うちは基本的に手作りなんだ。ひき肉と、玉ねぎと、缶詰のホールトマト。お母さんのレシピなの」
line = "「時間がない時は市販のソースを使うこともあるけど、うちは基本的に手作りなんだ。ひき肉と、玉ねぎと、缶詰のホールトマト。お母さんのレシピなの」"

[[dialogue]]
speaker = "コハルコ"
# 「といっても、普通のミートソースだけどね。でもうちの家族は大好きだから、会長さんも気に入ってくれると嬉しいな」
line = "「といっても、普通のミートソースだけどね。でもうちの家族は大好きだから、会長さんも気に入ってくれると嬉しいな」"

[[dialogue]]
speaker = "unk"
# 何の変哲もないミートソーススパゲティだけど、だからこそ、フォークが止まらない。
line = "何の変哲もないミートソーススパゲティだけど、だからこそ、フォークが止まらない。"

[[dialogue]]
speaker = "コハルコ"
# 「あははっ、そんなにがっつかなくてもいいのに。いつでも作ってあげるからね」
line = "「あははっ、そんなにがっつかなくてもいいのに。いつでも作ってあげるからね」"

[[dialogue]]
speaker = "コハルコ"
# 「パソコンの調子はどう？　異常とかない？」
line = "「パソコンの調子はどう？　異常とかない？」"

[[dialogue]]
speaker = "コハルコ"
# 「……いつも元気にピカピカ光ってる？　それはよかった…………のかな？　あのときは楽しく組んでたけど、派手すぎない？」
line = "「……いつも元気にピカピカ光ってる？　それはよかった…………のかな？　あのときは楽しく組んでたけど、派手すぎない？」"

[[dialogue]]
speaker = "unk"
# 賑やかで楽しいよ
line = "賑やかで楽しいよ"

[[dialogue]]
speaker = "unk"
# 俺が使っているパソコンは、以前にコハルコと２人で組んだもの。当然、ゲームもネットも快適だ。
line = "俺が使っているパソコンは、以前にコハルコと２人で組んだもの。当然、ゲームもネットも快適だ。"

[[dialogue]]
speaker = "コハルコ"
# 「そっか。ならいいや」
line = "「そっか。ならいいや」"

[[dialogue]]
speaker = "コハルコ"
# 「秋葉原にまた新しいお店ができてね。時間あるときに２人で行ってみようよ」
line = "「秋葉原にまた新しいお店ができてね。時間あるときに２人で行ってみようよ」"

[[dialogue]]
speaker = "コハルコ"
# 「うちの家族？　うん、みんな元気だよ。秋葉原に来たら顔出してあげて。ナツコもトウコも喜ぶよ」
line = "「うちの家族？　うん、みんな元気だよ。秋葉原に来たら顔出してあげて。ナツコもトウコも喜ぶよ」"

[[dialogue]]
speaker = "コハルコ"
# 「お母さんも体調すごくよくなってきてね。そのうち家族で旅行も行きたいなぁ。あ、でも、お父さんはさらにお腹出てきた。夜食はやめてっていつも言ってるんだけど」
line = "「お母さんも体調すごくよくなってきてね。そのうち家族で旅行も行きたいなぁ。あ、でも、お父さんはさらにお腹出てきた。夜食はやめてっていつも言ってるんだけど」"

[[dialogue]]
speaker = "コハルコ"
# 「会長さんのお母さんは元気？　ちゃんと会ったことないけど、いつかは挨拶しないとね」
line = "「会長さんのお母さんは元気？　ちゃんと会ったことないけど、いつかは挨拶しないとね」"

[[dialogue]]
speaker = "unk"
# とりとめのない話、なんでもない時間。
line = "とりとめのない話、なんでもない時間。"

[[dialogue]]
speaker = "unk"
# コハルコと一緒だと、それが心地いい。あれこれ話しているうちに皿も空になった。
line = "コハルコと一緒だと、それが心地いい。あれこれ話しているうちに皿も空になった。"

[[dialogue]]
speaker = "unk"
# ごちそうさまでした
line = "ごちそうさまでした"

[[dialogue]]
speaker = "コハルコ"
# 「はい、お粗末様でした。食後のコーヒー、飲むよね？」
line = "「はい、お粗末様でした。食後のコーヒー、飲むよね？」"

[[dialogue]]
speaker = "コハルコ"
# 「はい、どうぞ。隣、座るね」
line = "「はい、どうぞ。隣、座るね」"

[[dialogue]]
speaker = "コハルコ"
# 「今日はこれからどうする？　どこか出かける？」
line = "「今日はこれからどうする？　どこか出かける？」"

[[dialogue]]
speaker = "unk"
# 今日はこのまままったりかな
line = "今日はこのまままったりかな"

[[dialogue]]
speaker = "コハルコ"
# 「そうだね、ずっとこうしてよっか」
line = "「そうだね、ずっとこうしてよっか」"

[[dialogue]]
speaker = "unk"
# コハルコが肩を預けてくる。彼女の体温、匂い、全てが愛おしい。
line = "コハルコが肩を預けてくる。彼女の体温、匂い、全てが愛おしい。"

[[dialogue]]
speaker = "コハルコ"
# 「ふふっ、ふふふっ」
line = "「ふふっ、ふふふっ」"

[[dialogue]]
speaker = "unk"
# コハルコ
line = "コハルコ"

[[dialogue]]
speaker = "コハルコ"
# 「なーに、会長さん？」
line = "「なーに、会長さん？」"

[[dialogue]]
speaker = "unk"
# 愛してる
line = "愛してる"

[[dialogue]]
speaker = "unk"
# 好きだ
line = "好きだ"

[[dialogue]]
speaker = "コハルコ"
# 「うん。私もだよ……」
line = "「うん。私もだよ……」"

[[dialogue]]
speaker = "コハルコ"
# 「……………………あ」
line = "「……………………あ」"

[[dialogue]]
speaker = "コハルコ"
# 「どわああああぁぁぁぁぁ～～～～～～っ！？」
line = "「どわああああぁぁぁぁぁ～～～～～～っ！？」"

[[dialogue]]
speaker = "コハルコ"
# 「リ、リノさん、いつからそこに！？」
line = "「リ、リノさん、いつからそこに！？」"

[[dialogue]]
speaker = "リノ"
# 「ごめんなさいね。用事が片付いたから、ついさっき帰ってきたんだけど、どう入っていいのか分からなくて、様子を窺っちゃったわ」
line = "「ごめんなさいね。用事が片付いたから、ついさっき帰ってきたんだけど、どう入っていいのか分からなくて、様子を窺っちゃったわ」"

[[dialogue]]
speaker = "リノ"
# 「私のことは気にしなくていいから、続けて続けて」
line = "「私のことは気にしなくていいから、続けて続けて」"

[[dialogue]]
speaker = "コハルコ"
# 「そんなの無理ですぅ～！」
line = "「そんなの無理ですぅ～！」"

[[dialogue]]
speaker = "リノ"
# 「２人きりだとこんな感じなのねぇ。母さんまでドキドキしちゃいそう。あ、ちなみに呼び捨てなのは……」
line = "「２人きりだとこんな感じなのねぇ。母さんまでドキドキしちゃいそう。あ、ちなみに呼び捨てなのは……」"

[[dialogue]]
speaker = "コハルコ"
# 「私から言い出したことです……」
line = "「私から言い出したことです……」"

[[dialogue]]
speaker = "リノ"
# 「きゃ～～～！」
line = "「きゃ～～～！」"

[[dialogue]]
speaker = "unk"
# コハルコからのお願いで、２人きりやプライベートのときは呼び捨てで、敬語も使わないようにしている。
line = "コハルコからのお願いで、２人きりやプライベートのときは呼び捨てで、敬語も使わないようにしている。"

[[dialogue]]
speaker = "リノ"
# 「コハルコちゃんが来てるなら、クロトも教えてくれればいいのに～。じゃあ私、また出かけるわね。コハルコちゃんはゆっくりしていって」
line = "「コハルコちゃんが来てるなら、クロトも教えてくれればいいのに～。じゃあ私、また出かけるわね。コハルコちゃんはゆっくりしていって」"

[[dialogue]]
speaker = "unk"
# 母さん、ストップ
line = "母さん、ストップ"

[[dialogue]]
speaker = "リノ"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "unk"
# さっき話にも出た通り、コハルコと母さんはちゃんと会ったことがない。
line = "さっき話にも出た通り、コハルコと母さんはちゃんと会ったことがない。"

[[dialogue]]
speaker = "unk"
# 母さん不在の時にコハルコが来るか、コハルコが来ると知って母さんが出かけてるかだ。会っても今日みたいに少しだけ。
line = "母さん不在の時にコハルコが来るか、コハルコが来ると知って母さんが出かけてるかだ。会っても今日みたいに少しだけ。"

[[dialogue]]
speaker = "unk"
# 気を遣ってくれているといえばそれまでだが──
line = "気を遣ってくれているといえばそれまでだが──"

[[dialogue]]
speaker = "リノ"
# 「……私が、コハルコちゃんを避けている気がする？」
line = "「……私が、コハルコちゃんを避けている気がする？」"

[[dialogue]]
speaker = "コハルコ"
# 「っ！」
line = "「っ！」"

[[dialogue]]
speaker = "リノ"
# 「それはちが……わないかもしれないわね。私も気付かないうちにそうしていたのかも」
line = "「それはちが……わないかもしれないわね。私も気付かないうちにそうしていたのかも」"

[[dialogue]]
speaker = "リノ"
# 「いい機会だから、ちゃんと話しましょうか。コハルコちゃん、クロト、時間もらっていいかしら？」
line = "「いい機会だから、ちゃんと話しましょうか。コハルコちゃん、クロト、時間もらっていいかしら？」"

[[dialogue]]
speaker = "リノ"
# 「まず誤解しないで欲しいんだけど、私はあなたたちの交際を歓迎しているし、応援しているの。それだけは分かっていて」
line = "「まず誤解しないで欲しいんだけど、私はあなたたちの交際を歓迎しているし、応援しているの。それだけは分かっていて」"

[[dialogue]]
speaker = "コハルコ"
# 「はい、それはもちろん」
line = "「はい、それはもちろん」"

[[dialogue]]
speaker = "リノ"
# 「ありがと～」
line = "「ありがと～」"

[[dialogue]]
speaker = "リノ"
# 「でも、コハルコちゃんがクロトと仲良くしているのを見ると、心がざわざわするというか、まだ慣れないのよ。あなたはあの人にそっくりだから」
line = "「でも、コハルコちゃんがクロトと仲良くしているのを見ると、心がざわざわするというか、まだ慣れないのよ。あなたはあの人にそっくりだから」"

[[dialogue]]
speaker = "コハルコ"
# 「あの人…………イザベラさんですね」
line = "「あの人…………イザベラさんですね」"

[[dialogue]]
speaker = "unk"
# イザベラとは、コハルコの生みの親の魔女だ。
line = "イザベラとは、コハルコの生みの親の魔女だ。"

[[dialogue]]
speaker = "unk"
# 彼女をベースに、光の魔女の力を付与して生み出されたコハルコは、イザベラのクローンともいえるだろう。
line = "彼女をベースに、光の魔女の力を付与して生み出されたコハルコは、イザベラのクローンともいえるだろう。"

[[dialogue]]
speaker = "リノ"
# 「そう。私、若い頃はイザベラさんにボコボコにされたことがあるから、どうしても脳裏をよぎっちゃうの」
line = "「そう。私、若い頃はイザベラさんにボコボコにされたことがあるから、どうしても脳裏をよぎっちゃうの」"

[[dialogue]]
speaker = "コハルコ"
# 「ボコボコ！？　リノさんが、イザベラさんに！？」
line = "「ボコボコ！？　リノさんが、イザベラさんに！？」"

[[dialogue]]
speaker = "リノ"
# 「あ、物理的にじゃないわよ。なんというか、学術的に？　昔、ネビュラの若い魔女たちの研究発表の場があって、講評がイザベラさんだったのよ」
line = "「あ、物理的にじゃないわよ。なんというか、学術的に？　昔、ネビュラの若い魔女たちの研究発表の場があって、講評がイザベラさんだったのよ」"

[[dialogue]]
speaker = "リノ"
# 「それはもう、ボッコボコだったわぁ……」
line = "「それはもう、ボッコボコだったわぁ……」"

[[dialogue]]
speaker = "イザベラ"
# 「素人質問だけどいいかしら？」
line = "「素人質問だけどいいかしら？」"

[[dialogue]]
speaker = "イザベラ"
# 「先行研究は確認した？」
line = "「先行研究は確認した？」"

[[dialogue]]
speaker = "イザベラ"
# 「その論文は知ってるわ。書いたの私だから」
line = "「その論文は知ってるわ。書いたの私だから」"

[[dialogue]]
speaker = "イザベラ"
# 「資料はどうやって集めたの？　まさか資料室にあるものだけで完結してないわよね？　ちゃんと自分の足で集めなさい」
line = "「資料はどうやって集めたの？　まさか資料室にあるものだけで完結してないわよね？　ちゃんと自分の足で集めなさい」"

[[dialogue]]
speaker = "コハルコ"
# （何でだろう、ありありとイメージできる……）
line = "（何でだろう、ありありとイメージできる……）"

[[dialogue]]
speaker = "リノ"
# 「あのときは自分のことを優秀な研究員だと思ってたから、ふてくされてセドナとやけ酒したわ」
line = "「あのときは自分のことを優秀な研究員だと思ってたから、ふてくされてセドナとやけ酒したわ」"

[[dialogue]]
speaker = "コハルコ"
# （セドナさん、また巻き込まれてる）
line = "（セドナさん、また巻き込まれてる）"

[[dialogue]]
speaker = "リノ"
# 「でもね、あの経験があったから今の私がある。イザベラさんは道を踏み外してしまったけど、尊敬する先達なのは変わらないわ」
line = "「でもね、あの経験があったから今の私がある。イザベラさんは道を踏み外してしまったけど、尊敬する先達なのは変わらないわ」"

[[dialogue]]
speaker = "リノ"
# 「イザベラさんがいなかったら、見付けられなかったものもあるかもしれない。昔のことって意外なとこで今と繋がっているものよ」
line = "「イザベラさんがいなかったら、見付けられなかったものもあるかもしれない。昔のことって意外なとこで今と繋がっているものよ」"

[[dialogue]]
speaker = "コハルコ"
# 「……リノさん。今のお話、聞けてよかったです」
line = "「……リノさん。今のお話、聞けてよかったです」"

[[dialogue]]
speaker = "リノ"
# 「うん。ならよかった」
line = "「うん。ならよかった」"

[[dialogue]]
speaker = "コハルコ"
# 「ところで、イザベラさんも体を動かすの苦手だったり……？」
line = "「ところで、イザベラさんも体を動かすの苦手だったり……？」"

[[dialogue]]
speaker = "unk"
# コハルコの運動音痴は遺伝なのだろうか。俺もちょっと気になっていた。
line = "コハルコの運動音痴は遺伝なのだろうか。俺もちょっと気になっていた。"

[[dialogue]]
speaker = "リノ"
# 「それはないわね。遺跡調査の毎日で体力は人一倍あったし、思考を最適、高速化する魔法と魔力による身体強化で戦う肉体派の魔女だったから」
line = "「それはないわね。遺跡調査の毎日で体力は人一倍あったし、思考を最適、高速化する魔法と魔力による身体強化で戦う肉体派の魔女だったから」"

[[dialogue]]
speaker = "コハルコ"
# 「えぇ～～～～～～～～～～！？」
line = "「えぇ～～～～～～～～～～！？」"

[[dialogue]]
speaker = "イザベラ"
# 「動きが遅いわ。ハエが止まるわね」
line = "「動きが遅いわ。ハエが止まるわね」"

[[dialogue]]
speaker = "イザベラ"
# 「シッ！　シッシッ！」
line = "「シッ！　シッシッ！」"

[[dialogue]]
speaker = "unk"
# コハルコと同じ顔で、高速の肉弾戦で戦うイザベラ。あまりにも意外な絵面だった。
line = "コハルコと同じ顔で、高速の肉弾戦で戦うイザベラ。あまりにも意外な絵面だった。"
