[[dialogue]]
speaker = "unk"
# 第３話,梨緒とチーム戦,P
line = "第３話,梨緒とチーム戦,P"

[[dialogue]]
speaker = "unk"
# リップルがリゾート結界に実装して、現在試験中のサバイバルモード。
line = "リップルがリゾート結界に実装して、現在試験中のサバイバルモード。"

[[dialogue]]
speaker = "unk"
# 新星星徒会は以前攻略に失敗したものの、そのリベンジに訪れていた。
line = "新星星徒会は以前攻略に失敗したものの、そのリベンジに訪れていた。"

[[dialogue]]
speaker = "梨緒"
# 「私は当然、魔王の監視だ」
line = "「私は当然、魔王の監視だ」"

[[dialogue]]
speaker = "梨緒"
# 「もちろん新星星徒会に協力する気はない。私たち選挙管理委員会は、すでにサバイバルモードをクリアしているからな」
line = "「もちろん新星星徒会に協力する気はない。私たち選挙管理委員会は、すでにサバイバルモードをクリアしているからな」"

[[dialogue]]
speaker = "マトイ"
# 「梨緒さんの水着姿、クールでいいなぁ。金髪も綺麗で羨ましい……」
line = "「梨緒さんの水着姿、クールでいいなぁ。金髪も綺麗で羨ましい……」"

[[dialogue]]
speaker = "アナ"
# 「均整の取れたスタイルです」
line = "「均整の取れたスタイルです」"

[[dialogue]]
speaker = "サーシャ"
# 「お肌もすべすべね～」
line = "「お肌もすべすべね～」"

[[dialogue]]
speaker = "梨緒"
# 「えっ！？　いや、あの……私なんか浜辺に転がる名前もわからない貝のような存在で……そんなに見ないでくれ……」
line = "「えっ！？　いや、あの……私なんか浜辺に転がる名前もわからない貝のような存在で……そんなに見ないでくれ……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「つい触りたくなるお腹ね。つんつん」
line = "「つい触りたくなるお腹ね。つんつん」"

[[dialogue]]
speaker = "梨緒"
# 「ひゃぁっ！？　ちょっ、やめ……お腹をつつくなぁっ！」
line = "「ひゃぁっ！？　ちょっ、やめ……お腹をつつくなぁっ！」"

[[dialogue]]
speaker = "unk"
# つんつん
line = "つんつん"

[[dialogue]]
speaker = "梨緒"
# 「ひんっ！？　魔王までお腹を……ひぁあっ！？　あっ……魔王の指がつつ～っと、お腹をなぞって……ひゃああっ！？」
line = "「ひんっ！？　魔王までお腹を……ひぁあっ！？　あっ……魔王の指がつつ～っと、お腹をなぞって……ひゃああっ！？」"

[[dialogue]]
speaker = "梨緒"
# 「こらーっ！！　お腹を触るな～～っ！！」
line = "「こらーっ！！　お腹を触るな～～っ！！」"

[[dialogue]]
speaker = "梨緒"
# 「君たちはリゾート結界のサバイバルモードの攻略に来たんだろう。本題から逸れているぞ」
line = "「君たちはリゾート結界のサバイバルモードの攻略に来たんだろう。本題から逸れているぞ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ハッ──そうだったわ！」
line = "「ハッ──そうだったわ！」"

[[dialogue]]
speaker = "リップル"
# 「チョットまってくださーい！　さっきサバイバルモードの新しい遊び方を思いつきマシた！」
line = "「チョットまってくださーい！　さっきサバイバルモードの新しい遊び方を思いつきマシた！」"

[[dialogue]]
speaker = "梨緒"
# 「リップル？　新しい遊び方とは……？」
line = "「リップル？　新しい遊び方とは……？」"

[[dialogue]]
speaker = "リップル"
# 「チーム対抗で競うチーム戦です！　きっとオモシロいでーす！」
line = "「チーム対抗で競うチーム戦です！　きっとオモシロいでーす！」"

[[dialogue]]
speaker = "梨緒"
# 「なるほど、どのチームがボスを倒せるか競うわけだな」
line = "「なるほど、どのチームがボスを倒せるか競うわけだな」"

[[dialogue]]
speaker = "unk"
# この場にいるのはリップルを覗いて６人。２人のチームが３つ作ることになり、砂浜に線を引いてあみだくじでチームを決める。
line = "この場にいるのはリップルを覗いて６人。２人のチームが３つ作ることになり、砂浜に線を引いてあみだくじでチームを決める。"

[[dialogue]]
speaker = "unk"
# マトイとヴィーナス、アナとサーシャさんのチームに分かれ、そして──
line = "マトイとヴィーナス、アナとサーシャさんのチームに分かれ、そして──"

[[dialogue]]
speaker = "梨緒"
# 「私と組むのは──魔王だな」
line = "「私と組むのは──魔王だな」"

[[dialogue]]
speaker = "unk"
# よろしく、梨緒
line = "よろしく、梨緒"

[[dialogue]]
speaker = "梨緒"
# 「魔王とは何度も勝負をしたし、モンスター相手に共に戦ったことはあるが……勝負事で魔王と組んだことはなかったか」
line = "「魔王とは何度も勝負をしたし、モンスター相手に共に戦ったことはあるが……勝負事で魔王と組んだことはなかったか」"

[[dialogue]]
speaker = "梨緒"
# 「選挙管理委員会として、魔王の監視をするにはちょうどいいかもしれないな。君の一挙手一投足を見ているから、そのつもりでいてくれ」
line = "「選挙管理委員会として、魔王の監視をするにはちょうどいいかもしれないな。君の一挙手一投足を見ているから、そのつもりでいてくれ」"

[[dialogue]]
speaker = "梨緒"
# 「ではこの勝負……勝つぞ！」
line = "「ではこの勝負……勝つぞ！」"

[[dialogue]]
speaker = "モンスター"
# 「イーーーッ！」
line = "「イーーーッ！」"

[[dialogue]]
speaker = "unk"
# 結界内の疑似モンスターを倒しながら、食料や寝床を確保する。
line = "結界内の疑似モンスターを倒しながら、食料や寝床を確保する。"

[[dialogue]]
speaker = "unk"
# そうしている間にあっという間に日が落ちていって……
line = "そうしている間にあっという間に日が落ちていって……"

[[dialogue]]
speaker = "梨緒"
# 「ふぅ……なんとか食料や薪を集めることができたな。これだけあれば一晩は持つだろう」
line = "「ふぅ……なんとか食料や薪を集めることができたな。これだけあれば一晩は持つだろう」"

[[dialogue]]
speaker = "梨緒"
# 「魚が焼けたぞ。ほら、一緒に食べよう」
line = "「魚が焼けたぞ。ほら、一緒に食べよう」"

[[dialogue]]
speaker = "unk"
# 美味しい！
line = "美味しい！"

[[dialogue]]
speaker = "梨緒"
# 「……うん、悪くないな。サバイバルでこれなら上出来だろう」
line = "「……うん、悪くないな。サバイバルでこれなら上出来だろう」"

[[dialogue]]
speaker = "梨緒"
# 「魚を獲る勝負では魔王に負けてしまったが……くっ……」
line = "「魚を獲る勝負では魔王に負けてしまったが……くっ……」"

[[dialogue]]
speaker = "unk"
# 選挙管理委員会のみんなとはどう？
line = "選挙管理委員会のみんなとはどう？"

[[dialogue]]
speaker = "梨緒"
# 「なんだかんだうまくやれている……と思う」
line = "「なんだかんだうまくやれている……と思う」"

[[dialogue]]
speaker = "梨緒"
# 「ベアトが極星星徒会だと知った時は驚いたし、彼女を信じられなくなったこともあった。でもベアトの優しさはずっと変わらなかった」
line = "「ベアトが極星星徒会だと知った時は驚いたし、彼女を信じられなくなったこともあった。でもベアトの優しさはずっと変わらなかった」"

[[dialogue]]
speaker = "梨緒"
# 「ナターシャは何を考えているかわからないし、暗殺者という役割から非情なところはあるが、意外と仲間想いなところもある」
line = "「ナターシャは何を考えているかわからないし、暗殺者という役割から非情なところはあるが、意外と仲間想いなところもある」"

[[dialogue]]
speaker = "梨緒"
# 「アポロとは……ベガやデネブの彼女を知っているせいで、混乱することもあったが……年下とは思えないほど頼りになる。助けられてばかりだ」
line = "「アポロとは……ベガやデネブの彼女を知っているせいで、混乱することもあったが……年下とは思えないほど頼りになる。助けられてばかりだ」"

[[dialogue]]
speaker = "梨緒"
# 「彼女たちのことを思うと、自分が選挙管理委員会の委員長として相応しい存在なのか、不安になることもある」
line = "「彼女たちのことを思うと、自分が選挙管理委員会の委員長として相応しい存在なのか、不安になることもある」"

[[dialogue]]
speaker = "梨緒"
# 「だが……それでもいい。私は弱い人間だが、それだけじゃなかった。私は私なりに戦い続けてきた」
line = "「だが……それでもいい。私は弱い人間だが、それだけじゃなかった。私は私なりに戦い続けてきた」"

[[dialogue]]
speaker = "梨緒"
# 「私を信じるみんなと、ずっと戦ってきた自分を信じることにしたよ」
line = "「私を信じるみんなと、ずっと戦ってきた自分を信じることにしたよ」"

[[dialogue]]
speaker = "unk"
# 俺は梨緒に助けてもらったよ
line = "俺は梨緒に助けてもらったよ"

[[dialogue]]
speaker = "梨緒"
# 「……ああ、そういうこともあったな。あの時は魔王の暴走を防ぐという、選管の本分を全うすることができた」
line = "「……ああ、そういうこともあったな。あの時は魔王の暴走を防ぐという、選管の本分を全うすることができた」"

[[dialogue]]
speaker = "unk"
# ちなみにジグは？
line = "ちなみにジグは？"

[[dialogue]]
speaker = "梨緒"
# 「……あいつのことはいいだろう。選挙管理委員会としては新参だし、特に言うことはない」
line = "「……あいつのことはいいだろう。選挙管理委員会としては新参だし、特に言うことはない」"

[[dialogue]]
speaker = "梨緒"
# 「さて、食事は取ったし、明日に備えてそろそろ眠ろうか」
line = "「さて、食事は取ったし、明日に備えてそろそろ眠ろうか」"

[[dialogue]]
speaker = "梨緒"
# 「初めて出会った時は、こうして並んで寝るなんて想像できなかったな」
line = "「初めて出会った時は、こうして並んで寝るなんて想像できなかったな」"

[[dialogue]]
speaker = "梨緒"
# 「しかし、２人きりで寝るのはその、落ち着かないというか、ドキドキするというか……」
line = "「しかし、２人きりで寝るのはその、落ち着かないというか、ドキドキするというか……」"

[[dialogue]]
speaker = "梨緒"
# 「あ、いや、不愉快なわけじゃないんだぞ！　むしろ逆というか──って何を言ってるんだ私は！？」
line = "「あ、いや、不愉快なわけじゃないんだぞ！　むしろ逆というか──って何を言ってるんだ私は！？」"

[[dialogue]]
speaker = "梨緒"
# 「とにかく、私は君と２人で寝るのも悪くないと感じている。君もそう思ってくれていたら嬉しい」
line = "「とにかく、私は君と２人で寝るのも悪くないと感じている。君もそう思ってくれていたら嬉しい」"

[[dialogue]]
speaker = "梨緒"
# 「……お休み。明日は必ず勝とう」
line = "「……お休み。明日は必ず勝とう」"
