[[dialogue]]
speaker = "unk"
# 第１話,スーパー司書さん（不運もマシマシ）,P
line = "第１話,スーパー司書さん（不運もマシマシ）,P"

[[dialogue]]
speaker = "モンスター"
# 「ビビビビ！」
line = "「ビビビビ！」"

[[dialogue]]
speaker = "unk"
# モンスター出現の知らせを受け、近くにいた俺が迎撃にあたる。
line = "モンスター出現の知らせを受け、近くにいた俺が迎撃にあたる。"

[[dialogue]]
speaker = "unk"
# そこに──
line = "そこに──"

[[dialogue]]
speaker = "ウィステリア"
# 「あら、会長くんじゃない。機械型モンスターが出たって聞いて来たけど、私が出る幕はないかしら」
line = "「あら、会長くんじゃない。機械型モンスターが出たって聞いて来たけど、私が出る幕はないかしら」"

[[dialogue]]
speaker = "unk"
# ウィステリアさんが一緒だと心強いです！
line = "ウィステリアさんが一緒だと心強いです！"

[[dialogue]]
speaker = "ウィステリア"
# 「ふふ。そう言われたら、私も戦わないわけにはいかないわね。さっさと終わらせちゃいましょう」
line = "「ふふ。そう言われたら、私も戦わないわけにはいかないわね。さっさと終わらせちゃいましょう」"

[[dialogue]]
speaker = "ウィステリア"
# 「消し飛びなさい──フォビドゥンリアクター！」
line = "「消し飛びなさい──フォビドゥンリアクター！」"

[[dialogue]]
speaker = "モンスター"
# 「ビビビッ！？」
line = "「ビビビッ！？」"

[[dialogue]]
speaker = "モンスター"
# 「グルルッ！」
line = "「グルルッ！」"

[[dialogue]]
speaker = "ウィステリア"
# 「あら、大型のも出てきたわね。なら──」
line = "「あら、大型のも出てきたわね。なら──」"

[[dialogue]]
speaker = "ウィステリア"
# 「え、他にも機械型のモンスターが出た？　数は……大型の機械型モンスターが１０体！？」
line = "「え、他にも機械型のモンスターが出た？　数は……大型の機械型モンスターが１０体！？」"

[[dialogue]]
speaker = "モンスター"
# 「グラァアアッ！！」
line = "「グラァアアッ！！」"

[[dialogue]]
speaker = "ウィステリア"
# 「さすがに私でもこの数はきついわね。それじゃ──」
line = "「さすがに私でもこの数はきついわね。それじゃ──」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「新しい力を見せてあげましょう！」
line = "「新しい力を見せてあげましょう！」"

[[dialogue]]
speaker = "unk"
# その姿が例の……！
line = "その姿が例の……！"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「ええ。これが新たに会得した魔将フォームよ」
line = "「ええ。これが新たに会得した魔将フォームよ」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「新星学園の地下深くに存在する『地下図書館』……その正体は、リクリエに滅ぼされた魔族たちの怨念が呪いとなって集まったものだった」
line = "「新星学園の地下深くに存在する『地下図書館』……その正体は、リクリエに滅ぼされた魔族たちの怨念が呪いとなって集まったものだった」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「私はその呪いを分割し、制御して力にする『魔将システム』を構築した」
line = "「私はその呪いを分割し、制御して力にする『魔将システム』を構築した」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「『魔将システム』に選ばれた者は、地下図書館の魔本の力を使うことができる。そして私もその１人、『怠惰』の魔将」
line = "「『魔将システム』に選ばれた者は、地下図書館の魔本の力を使うことができる。そして私もその１人、『怠惰』の魔将」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「魔導書を通して感じるわ……リクリエへの憎しみを……全てを奪われた嘆きを」
line = "「魔導書を通して感じるわ……リクリエへの憎しみを……全てを奪われた嘆きを」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「ええ、そうよ。私たち魔将は魔族たちの無念とともに戦う者。その怨嗟を以て破滅を打ち砕く者」
line = "「ええ、そうよ。私たち魔将は魔族たちの無念とともに戦う者。その怨嗟を以て破滅を打ち砕く者」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「さぁ、思う存分恨みを晴らしなさい！　ただし私が許す範囲でね！」
line = "「さぁ、思う存分恨みを晴らしなさい！　ただし私が許す範囲でね！」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「アポカリプスリアクター！」
line = "「アポカリプスリアクター！」"

[[dialogue]]
speaker = "モンスター"
# 「グルルァアア……ッ！！」
line = "「グルルァアア……ッ！！」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「全てのモンスターの消滅を確認……これでおしまいね」
line = "「全てのモンスターの消滅を確認……これでおしまいね」"

[[dialogue]]
speaker = "unk"
# むしろ俺の出る幕がなかったんですが……
line = "むしろ俺の出る幕がなかったんですが……"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「あ……ごめんなさい、出しゃばっちゃったわね」
line = "「あ……ごめんなさい、出しゃばっちゃったわね」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「まぁ、街も人も無事なんだから誰が倒したかなんて別にいいでしょ。あはは」
line = "「まぁ、街も人も無事なんだから誰が倒したかなんて別にいいでしょ。あはは」"

[[dialogue]]
speaker = "unk"
# 魔将フォーム、強くてかっこいいです！
line = "魔将フォーム、強くてかっこいいです！"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「そう？　会長くんがそう言ってくれると、このフォームになった甲斐があるわね」
line = "「そう？　会長くんがそう言ってくれると、このフォームになった甲斐があるわね」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「今までは自分の魔導書だけを使っていたけど、この魔将フォームでは地下図書館の魔本の魔力を使うことができる」
line = "「今までは自分の魔導書だけを使っていたけど、この魔将フォームでは地下図書館の魔本の魔力を使うことができる」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「制御はより難しくなったけど、その分戦闘力も格段に向上したの。前はヴィライアと引き分けだったけど、今ならきっと倒せるわ」
line = "「制御はより難しくなったけど、その分戦闘力も格段に向上したの。前はヴィライアと引き分けだったけど、今ならきっと倒せるわ」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「まぁ、強くなっても嬉しくはないんだけど。私、現役の星騎士じゃないし」
line = "「まぁ、強くなっても嬉しくはないんだけど。私、現役の星騎士じゃないし」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「ただこの魔将フォーム、ちょっとどころじゃない問題があってね──」
line = "「ただこの魔将フォーム、ちょっとどころじゃない問題があってね──」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「きゃあぁあああっ！！？」
line = "「きゃあぁあああっ！！？」"

[[dialogue]]
speaker = "unk"
# 爆発した！？　攻撃！？
line = "爆発した！？　攻撃！？"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「はぁ、はぁ……死ぬかと思ったわ。星騎士だから平気だけど……」
line = "「はぁ、はぁ……死ぬかと思ったわ。星騎士だから平気だけど……」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「今のは攻撃じゃないわ。かすかに匂いがするし、地面に穴が空いているから、きっと地下のガス管が爆発したのね……」
line = "「今のは攻撃じゃないわ。かすかに匂いがするし、地面に穴が空いているから、きっと地下のガス管が爆発したのね……」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「ひぎぃっ！！？」
line = "「ひぎぃっ！！？」"

[[dialogue]]
speaker = "unk"
# 上から何か落ちてきた！？
line = "上から何か落ちてきた！？"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「あいたた……今、硬いものが頭に当たって……え、看板！？　ビルの上にあった看板が地面に転がってるんですけど！？」
line = "「あいたた……今、硬いものが頭に当たって……え、看板！？　ビルの上にあった看板が地面に転がってるんですけど！？」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「モンスターのせいか、固定が緩んでたのか知らないけど、看板が頭に直撃したのは初めてよ！？」
line = "「モンスターのせいか、固定が緩んでたのか知らないけど、看板が頭に直撃したのは初めてよ！？」"

[[dialogue]]
speaker = "unk"
# 問題ってまさか……
line = "問題ってまさか……"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「ええ、そうよ。ただでさえ運が悪かったのに──」
line = "「ええ、そうよ。ただでさえ運が悪かったのに──」"

[[dialogue]]
speaker = "ウィステリア（覚醒）"
# 「魔導書の呪いが強くなったせいで、余計に不運になっちゃったのよ！！」
line = "「魔導書の呪いが強くなったせいで、余計に不運になっちゃったのよ！！」"

[[dialogue]]
speaker = "unk"
# 魔将という強大な力を得た代わりに、大きな代償を支払ったウィステリアさん。
line = "魔将という強大な力を得た代わりに、大きな代償を支払ったウィステリアさん。"

[[dialogue]]
speaker = "unk"
# その不運さと不憫さに同情を禁じ得ないのであった……
line = "その不運さと不憫さに同情を禁じ得ないのであった……"
