[[dialogue]]
speaker = "unk"
# 第２話,ユウリとバニーレッスン,P
line = "第２話,ユウリとバニーレッスン,P"

[[dialogue]]
speaker = "ユウリ"
# 「ど……どうぞお客様。こちらメニューっす……」
line = "「ど……どうぞお客様。こちらメニューっす……」"

[[dialogue]]
speaker = "ユウリ"
# 「ご注文はお決まりですか？　……え？　ス、スマイルひとつ？」
line = "「ご注文はお決まりですか？　……え？　ス、スマイルひとつ？」"

[[dialogue]]
speaker = "ユウリ"
# 「は、はは……」
line = "「は、はは……」"

[[dialogue]]
speaker = "ユウリ"
# 「ははは…………」
line = "「ははは…………」"

[[dialogue]]
speaker = "ユウリ"
# 「～～っっ！　やっぱ無理だ、もうやめる、恥ずかしすぎて死ぬっ、つかこれじゃいかがわしいところの店員じゃねえか！？」
line = "「～～っっ！　やっぱ無理だ、もうやめる、恥ずかしすぎて死ぬっ、つかこれじゃいかがわしいところの店員じゃねえか！？」"

[[dialogue]]
speaker = "unk"
# 変身解いたら特訓にならないだろ
line = "変身解いたら特訓にならないだろ"

[[dialogue]]
speaker = "ユウリ"
# 「う、うるせえなっ、わかってるっつの……！　でもハズいもんはハズいんだってば……！」
line = "「う、うるせえなっ、わかってるっつの……！　でもハズいもんはハズいんだってば……！」"

[[dialogue]]
speaker = "ユウリ"
# 「そりゃあたしも前みたいなことになりたくはないけど……。バニー着るたびにオロオロしてたら話になんねえし……」
line = "「そりゃあたしも前みたいなことになりたくはないけど……。バニー着るたびにオロオロしてたら話になんねえし……」"

[[dialogue]]
speaker = "ユウリ"
# 「それに変身もまだ不安定で……。この前もいつもの戦闘服に変身したつもりだったのに、バニーガールになっちまったし……」
line = "「それに変身もまだ不安定で……。この前もいつもの戦闘服に変身したつもりだったのに、バニーガールになっちまったし……」"

[[dialogue]]
speaker = "ユウリ"
# 「だからこそちゃんと訓練して、バニーフォームを使いこなせるようになるべきだって自分でもわかってるけどよ……」
line = "「だからこそちゃんと訓練して、バニーフォームを使いこなせるようになるべきだって自分でもわかってるけどよ……」"

[[dialogue]]
speaker = "unk"
# ならやろう！！
line = "ならやろう！！"

[[dialogue]]
speaker = "ユウリ"
# 「だーっ！　そのノリノリっぷりがあたしの羞恥心を加速させんだよ！　前のめりで促すな！」
line = "「だーっ！　そのノリノリっぷりがあたしの羞恥心を加速させんだよ！　前のめりで促すな！」"

[[dialogue]]
speaker = "ユウリ"
# 「つ、つか、本当にリノさんは帰ってこないんだろうなっ？　息子の彼女が部屋でバニースーツなんか着てるの見られたら……！」
line = "「つ、つか、本当にリノさんは帰ってこないんだろうなっ？　息子の彼女が部屋でバニースーツなんか着てるの見られたら……！」"

[[dialogue]]
speaker = "ユウリ"
# 「って──～～っっ！　自分で彼女とか言っちまった……！　ハズい、死ぬっ、もう帰るっ……！！」
line = "「って──～～っっ！　自分で彼女とか言っちまった……！　ハズい、死ぬっ、もう帰るっ……！！」"

[[dialogue]]
speaker = "ユウリ"
# 「ひゃっ！？　いいい、いきなり手ぇ掴むなっ……！」
line = "「ひゃっ！？　いいい、いきなり手ぇ掴むなっ……！」"

[[dialogue]]
speaker = "ユウリ"
# 「あ、あうっ。わ、わかったからっ、帰らねえから……！　あたしも、その、せっかく来たのに帰りたくない、し……」
line = "「あ、あうっ。わ、わかったからっ、帰らねえから……！　あたしも、その、せっかく来たのに帰りたくない、し……」"

[[dialogue]]
speaker = "ユウリ"
# 「っっ。特訓の続きをしなきゃって意味だからなっ？　変な勘違いすんなよっ？」
line = "「っっ。特訓の続きをしなきゃって意味だからなっ？　変な勘違いすんなよっ？」"

[[dialogue]]
speaker = "ユウリ"
# 「それより、その。手ぇ離してくれよ。このままだと変身できねえし……」
line = "「それより、その。手ぇ離してくれよ。このままだと変身できねえし……」"

[[dialogue]]
speaker = "ユウリ"
# 「あ……でも待って。やっぱり、えと、バニースーツ着るの恥ずかしいから……」
line = "「あ……でも待って。やっぱり、えと、バニースーツ着るの恥ずかしいから……」"

[[dialogue]]
speaker = "ユウリ"
# 「変身する前に、おまじない……かけて欲しい……」
line = "「変身する前に、おまじない……かけて欲しい……」"

[[dialogue]]
speaker = "ユウリ"
# 「う……うん。女の子らしくてもいいってあたしに教えてくれるおまじない……。勇気出っから……」
line = "「う……うん。女の子らしくてもいいってあたしに教えてくれるおまじない……。勇気出っから……」"

[[dialogue]]
speaker = "ユウリ"
# 「ふぁ……んっ<emoji=heart04>　ちゅぁ……ん、んふ……<emoji=heart04>」
line = "「ふぁ……んっ<emoji=heart04>　ちゅぁ……ん、んふ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「はぁ、はぁ……こ、こんな姿、誰かに見られたらマジで死んじまうかも……」
line = "「はぁ、はぁ……こ、こんな姿、誰かに見られたらマジで死んじまうかも……」"

[[dialogue]]
speaker = "unk"
# 特訓続けられそう？
line = "特訓続けられそう？"

[[dialogue]]
speaker = "ユウリ"
# 「そ、そうだな。勇気もらったし……。もっかい変身してみる」
line = "「そ、そうだな。勇気もらったし……。もっかい変身してみる」"

[[dialogue]]
speaker = "ユウリ"
# 「ど……どうかな？」
line = "「ど……どうかな？」"

[[dialogue]]
speaker = "unk"
# 可愛いよ
line = "可愛いよ"

[[dialogue]]
speaker = "ユウリ"
# 「そ、そういうこと聞いてんじゃねえよ！　頭真っ白になるからやめろって……！」
line = "「そ、そういうこと聞いてんじゃねえよ！　頭真っ白になるからやめろって……！」"

[[dialogue]]
speaker = "ユウリ"
# 「えっ？　その場でくるくる回ってくれって。し、仕方ねえな、特別だぞ？」
line = "「えっ？　その場でくるくる回ってくれって。し、仕方ねえな、特別だぞ？」"

[[dialogue]]
speaker = "ユウリ"
# 「こう、かな……。っっ、だから可愛くなんかねえって……！　似合ってもねえから……！」
line = "「こう、かな……。っっ、だから可愛くなんかねえって……！　似合ってもねえから……！」"

[[dialogue]]
speaker = "ユウリ"
# 「もうちょっと前屈みに……？　こ……こう？　お尻ももっと突き出せって……？　んんっ……」
line = "「もうちょっと前屈みに……？　こ……こう？　お尻ももっと突き出せって……？　んんっ……」"

[[dialogue]]
speaker = "ユウリ"
# 「ひゃっ、バ、バカ、撮んなっ。恥ずかしいだろっ……！」
line = "「ひゃっ、バ、バカ、撮んなっ。恥ずかしいだろっ……！」"

[[dialogue]]
speaker = "ユウリ"
# 「あたしの可愛い姿、記録に残したいからって……？　しょ、しょうがねえヤツだな……」
line = "「あたしの可愛い姿、記録に残したいからって……？　しょ、しょうがねえヤツだな……」"

[[dialogue]]
speaker = "ユウリ"
# 「絶対他のヤツらには見せんなよ……？　見せびらかしたりしないってなら撮ってもいいけど……」
line = "「絶対他のヤツらには見せんなよ……？　見せびらかしたりしないってなら撮ってもいいけど……」"

[[dialogue]]
speaker = "ユウリ"
# 「きゃっ。ちょ、調子に乗って撮りすぎだっ。写真集の撮影じゃねえんだから……！」
line = "「きゃっ。ちょ、調子に乗って撮りすぎだっ。写真集の撮影じゃねえんだから……！」"

[[dialogue]]
speaker = "ユウリ"
# 「へ？　バナナを谷間に……？　ん、ふっ……<emoji=heart04>　こう、か……？」
line = "「へ？　バナナを谷間に……？　ん、ふっ……<emoji=heart04>　こう、か……？」"

[[dialogue]]
speaker = "ユウリ"
# 「そのまま舐め回せって……れろぉ、ぺろろぉ……<emoji=heart04>　ぢゅぷ……ぢゅぷぅ……<emoji=heart04>」
line = "「そのまま舐め回せって……れろぉ、ぺろろぉ……<emoji=heart04>　ぢゅぷ……ぢゅぷぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「っっ<emoji=heart04>　バ、バカ……<emoji=heart04>　ピントぶれぶれじゃねえか……<emoji=heart04>　息荒くしすぎだって……<emoji=heart04>」
line = "「っっ<emoji=heart04>　バ、バカ……<emoji=heart04>　ピントぶれぶれじゃねえか……<emoji=heart04>　息荒くしすぎだって……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「何やらせんだーっ！？」
line = "「何やらせんだーっ！？」"

[[dialogue]]
speaker = "ユウリ"
# 「さっきからあたしに何をやらせてんだ！？」
line = "「さっきからあたしに何をやらせてんだ！？」"

[[dialogue]]
speaker = "unk"
# つい出来心で……
line = "つい出来心で……"

[[dialogue]]
speaker = "ユウリ"
# 「特訓にかこつけておかしなことさせてんじゃねえぞ……！　た、ただでさえ死ぬほど恥ずかしい格好してるってのに……！」
line = "「特訓にかこつけておかしなことさせてんじゃねえぞ……！　た、ただでさえ死ぬほど恥ずかしい格好してるってのに……！」"

[[dialogue]]
speaker = "ユウリ"
# 「つかそもそもこれはバニーフォームを使いこなすための特訓なんだよなぁ……？　つーことは星術も特訓しねえと話になんねえよなぁ……？」
line = "「つかそもそもこれはバニーフォームを使いこなすための特訓なんだよなぁ……？　つーことは星術も特訓しねえと話になんねえよなぁ……？」"

[[dialogue]]
speaker = "ユウリ"
# 「ふふ、どこに行こうとしてんだ？　あたしの特訓に付き合ってくれんだろ？」
line = "「ふふ、どこに行こうとしてんだ？　あたしの特訓に付き合ってくれんだろ？」"

[[dialogue]]
speaker = "ユウリ"
# 「なら、たっぷりと協力してもらうぜ。お望み通り──」
line = "「なら、たっぷりと協力してもらうぜ。お望み通り──」"

[[dialogue]]
speaker = "ユウリ"
# 「あんたの体でなーーーーっ！！」
line = "「あんたの体でなーーーーっ！！」"

[[dialogue]]
speaker = "unk"
# それからユウリの星術を受け続け、ユウリのダイス捌きは見事なキレになったのだった……
line = "それからユウリの星術を受け続け、ユウリのダイス捌きは見事なキレになったのだった……"
