[[dialogue]]
speaker = "unk"
# 第３話,フィオナの素顔？,P
line = "第３話,フィオナの素顔？,P"

[[dialogue]]
speaker = "フィオナ"
# 「ふぅ……雨が弱くなったうちになんとか帰ってこられた……」
line = "「ふぅ……雨が弱くなったうちになんとか帰ってこられた……」"

[[dialogue]]
speaker = "ニャリオン"
# 「お帰りニャ～。どこ行ってたニャン？」
line = "「お帰りニャ～。どこ行ってたニャン？」"

[[dialogue]]
speaker = "フィオナ"
# 「フッフッフ……最近運動不足のニャリオンのために……」
line = "「フッフッフ……最近運動不足のニャリオンのために……」"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャニ！？　ワガハイ運動不足じゃないニャン！　ぷりちーボディは健在ニャ！」
line = "「ニャニ！？　ワガハイ運動不足じゃないニャン！　ぷりちーボディは健在ニャ！」"

[[dialogue]]
speaker = "フィオナ"
# 「じゃ～ん、ネズミのおもちゃにゃー♪」
line = "「じゃ～ん、ネズミのおもちゃにゃー♪」"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャン！？」
line = "「ニャン！？」"

[[dialogue]]
speaker = "フィオナ"
# 「ほら、気になるでしょ？　ふりふり、ふりふり」
line = "「ほら、気になるでしょ？　ふりふり、ふりふり」"

[[dialogue]]
speaker = "ニャリオン"
# 「ほ、誇り高き使い魔のワガハイがネズミのおもちゃに心動かされるわけないニャ」
line = "「ほ、誇り高き使い魔のワガハイがネズミのおもちゃに心動かされるわけないニャ」"

[[dialogue]]
speaker = "フィオナ"
# 「ほんとに？」
line = "「ほんとに？」"

[[dialogue]]
speaker = "ニャリオン"
# 「ほんとニャンッ」
line = "「ほんとニャンッ」"

[[dialogue]]
speaker = "フィオナ"
# 「ふ～ん……ふりふり、ふりふり……ふ～りふ～り」
line = "「ふ～ん……ふりふり、ふりふり……ふ～りふ～り」"

[[dialogue]]
speaker = "ニャリオン"
# 「ンニャニャ……」
line = "「ンニャニャ……」"

[[dialogue]]
speaker = "フィオナ"
# 「ふりふりふりふりふり～♪」
line = "「ふりふりふりふりふり～♪」"

[[dialogue]]
speaker = "ニャリオン"
# 「フシャーッ！」
line = "「フシャーッ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ほーら、まるまる太ったネズミだよ～、おいしそうなネズミだよ～♪」
line = "「ほーら、まるまる太ったネズミだよ～、おいしそうなネズミだよ～♪」"

[[dialogue]]
speaker = "ニャリオン"
# 「ネズミッ、ネズミッ、フーッ、フーッ！　フシャーッ！」
line = "「ネズミッ、ネズミッ、フーッ、フーッ！　フシャーッ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふっ、すっごく楽しそうにゃ。ふりふり～」
line = "「ふふっ、すっごく楽しそうにゃ。ふりふり～」"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャッ、ンニャニャニャッ、ンニャッ、ニャン♪」
line = "「ニャッ、ンニャニャニャッ、ンニャッ、ニャン♪」"

[[dialogue]]
speaker = "フィオナ"
# 「ふりふりふりふり～♪　最高速ふりふり～♪」
line = "「ふりふりふりふり～♪　最高速ふりふり～♪」"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャニャニャニャニャニャニャッ！！」
line = "「ニャニャニャニャニャニャニャッ！！」"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャッ」
line = "「ニャッ」"

[[dialogue]]
speaker = "フィオナ"
# 「ふりふり～、ふりふり～♪」
line = "「ふりふり～、ふりふり～♪」"

[[dialogue]]
speaker = "ニャリオン"
# 「あの～……フィオナ嬢？」
line = "「あの～……フィオナ嬢？」"

[[dialogue]]
speaker = "フィオナ"
# 「急に止まってどうしたにゃ～？」
line = "「急に止まってどうしたにゃ～？」"

[[dialogue]]
speaker = "ニャリオン"
# 「後ろ、後ろ」
line = "「後ろ、後ろ」"

[[dialogue]]
speaker = "フィオナ"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "unk"
# ……こんばんは
line = "……こんばんは"

[[dialogue]]
speaker = "フィオナ"
# 「きゃああぁ～～～～っ！？　どど、どうして緋宮会長が！？　いつからそこに！？」
line = "「きゃああぁ～～～～っ！？　どど、どうして緋宮会長が！？　いつからそこに！？」"

[[dialogue]]
speaker = "キリカ"
# 「先刻、緋宮さまが屋敷のお近くにおられたのですが、ずぶ濡れでしたのでお風呂に入っていただきました」
line = "「先刻、緋宮さまが屋敷のお近くにおられたのですが、ずぶ濡れでしたのでお風呂に入っていただきました」"

[[dialogue]]
speaker = "フィオナ"
# 「あ……そうなの……」
line = "「あ……そうなの……」"

[[dialogue]]
speaker = "キリカ"
# 「申し訳ありません、お嬢様。緋宮さまを屋敷に上げた私の責任です」
line = "「申し訳ありません、お嬢様。緋宮さまを屋敷に上げた私の責任です」"

[[dialogue]]
speaker = "キリカ"
# 「ですので責任を持って、この拳で記憶を消し飛ばします」
line = "「ですので責任を持って、この拳で記憶を消し飛ばします」"

[[dialogue]]
speaker = "フィオナ"
# 「それはダメ！？」
line = "「それはダメ！？」"

[[dialogue]]
speaker = "unk"
# さっきのフィオナ、すごくかわいかった
line = "さっきのフィオナ、すごくかわいかった"

[[dialogue]]
speaker = "フィオナ"
# 「かわっ！？」
line = "「かわっ！？」"

[[dialogue]]
speaker = "フィオナ"
# 「私はにゃ～とか言ってませんから！　気のせいですから！　忘れてくださ～いっ！」
line = "「私はにゃ～とか言ってませんから！　気のせいですから！　忘れてくださ～いっ！」"

[[dialogue]]
speaker = "ニャリオン"
# 「フィオナ嬢があんなにムキになって……なんだか恥ずかしい空気になってきた気がするニャン」
line = "「フィオナ嬢があんなにムキになって……なんだか恥ずかしい空気になってきた気がするニャン」"

[[dialogue]]
speaker = "キリカ"
# 「ですね。しかしフィオナ様に狼藉をはたらくなら容赦は致しません」
line = "「ですね。しかしフィオナ様に狼藉をはたらくなら容赦は致しません」"

[[dialogue]]
speaker = "ニャリオン"
# 「とっと帰るニャ！　この魔王モドキ！」
line = "「とっと帰るニャ！　この魔王モドキ！」"

[[dialogue]]
speaker = "unk"
# その前に渡したいものが……
line = "その前に渡したいものが……"

[[dialogue]]
speaker = "フィオナ"
# 「！　そのぬいぐるみはどこで……？」
line = "「！　そのぬいぐるみはどこで……？」"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャニャ！？　ゲテモ……コホン、フィオナ嬢好みの代物ニャン……」
line = "「ニャニャ！？　ゲテモ……コホン、フィオナ嬢好みの代物ニャン……」"

[[dialogue]]
speaker = "フィオナ"
# 「これをわざわざ私のために……？　ありがとうございます。ニャリオンと一緒でかわいいです」
line = "「これをわざわざ私のために……？　ありがとうございます。ニャリオンと一緒でかわいいです」"

[[dialogue]]
speaker = "ニャリオン"
# 「ワガハイ、自分のぷりちーさに自信がなくなってきたニャン……」
line = "「ワガハイ、自分のぷりちーさに自信がなくなってきたニャン……」"

[[dialogue]]
speaker = "フィオナ"
# 「ニャリオンはとってもかわいいよ？　大丈夫、自信持って」
line = "「ニャリオンはとってもかわいいよ？　大丈夫、自信持って」"

[[dialogue]]
speaker = "ニャリオン"
# 「うぅ、フィオナ嬢にそう言われると余計に不安ニャ……」
line = "「うぅ、フィオナ嬢にそう言われると余計に不安ニャ……」"

[[dialogue]]
speaker = "フィオナ"
# 「あ、でも、私がこういうものが好きということも、みんなには秘密でお願いします」
line = "「あ、でも、私がこういうものが好きということも、みんなには秘密でお願いします」"

[[dialogue]]
speaker = "unk"
# もちろん
line = "もちろん"

[[dialogue]]
speaker = "フィオナ"
# 「ありがとうございます。じゃあ……またお会いしましょう」
line = "「ありがとうございます。じゃあ……またお会いしましょう」"
