[[dialogue]]
speaker = "unk"
# 第３話,パワー系転入生,P
line = "第３話,パワー系転入生,P"

[[dialogue]]
speaker = "unk"
# 流星寮でお茶会が開かれるとのことで招待を受け、迎えに来たフニと共に向かうと、何やらロビーが騒がしい様子だった――
line = "流星寮でお茶会が開かれるとのことで招待を受け、迎えに来たフニと共に向かうと、何やらロビーが騒がしい様子だった――"

[[dialogue]]
speaker = "フェニエル"
# 「ヒルディお姉様、会長さんを呼んで参りました……って、何かあったんですか？」
line = "「ヒルディお姉様、会長さんを呼んで参りました……って、何かあったんですか？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ああ、フニ。ご苦労様ですわ」
line = "「ああ、フニ。ご苦労様ですわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「緋宮会長、ごきげんよう。お茶会の招待に応じて下さり、感謝致しますわ」
line = "「緋宮会長、ごきげんよう。お茶会の招待に応じて下さり、感謝致しますわ」"

[[dialogue]]
speaker = "unk"
# で、そこにある巨大なダビデ像は一体……？
line = "で、そこにある巨大なダビデ像は一体……？"

[[dialogue]]
speaker = "unk"
# 先輩、ごきげんよう
line = "先輩、ごきげんよう"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「やはりこの場だと邪魔ですわよね……３メートルくらいありますもの」
line = "「やはりこの場だと邪魔ですわよね……３メートルくらいありますもの」"

[[dialogue]]
speaker = "フェニエル"
# 「これって確か、卒業生の方からの寄付で届くって言っていた美術品ですよね？　本来は中庭に搬入される予定だったはず……」
line = "「これって確か、卒業生の方からの寄付で届くって言っていた美術品ですよね？　本来は中庭に搬入される予定だったはず……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ええ。ですが、どうやら業者に手違いがあったようですの」
line = "「ええ。ですが、どうやら業者に手違いがあったようですの」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「まあ、私たちは星騎士ですから、本気でやろうと思えば中庭に運べなくはないのでしょうけれど……」
line = "「まあ、私たちは星騎士ですから、本気でやろうと思えば中庭に運べなくはないのでしょうけれど……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「出入口もギリギリ通る大きさですし、ぶつけて傷付けたりしたら大変でしょう？」
line = "「出入口もギリギリ通る大きさですし、ぶつけて傷付けたりしたら大変でしょう？」"

[[dialogue]]
speaker = "フェニエル"
# 「なるほどですっ。卒業生の方が下さった物ですから、丁重に扱わないといけませんよね」
line = "「なるほどですっ。卒業生の方が下さった物ですから、丁重に扱わないといけませんよね」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「それで、どうしたものかと寮生の皆で相談していて……フニ？」
line = "「それで、どうしたものかと寮生の皆で相談していて……フニ？」"

[[dialogue]]
speaker = "フェニエル"
# 「中庭ですねっ。それでは私がお持ちします！」
line = "「中庭ですねっ。それでは私がお持ちします！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「お待ちなさい。貴方、私の話を聞いておりましたの？　それは私が変身して運ぼうと思っても、苦労する大きさと重さがありますのよ？　４トンですわ、４トン！」
line = "「お待ちなさい。貴方、私の話を聞いておりましたの？　それは私が変身して運ぼうと思っても、苦労する大きさと重さがありますのよ？　４トンですわ、４トン！」"

[[dialogue]]
speaker = "フェニエル"
# 「よいしょっと……」
line = "「よいしょっと……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「いやいやいや、変身もしないで、ましてや貴方の体格で持ち上がるわけが……」
line = "「いやいやいや、変身もしないで、ましてや貴方の体格で持ち上がるわけが……」"

[[dialogue]]
speaker = "フェニエル"
# 「ほっ！」
line = "「ほっ！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「軽々と持ち上がりましたわぁぁぁ―――――――っ！！？」
line = "「軽々と持ち上がりましたわぁぁぁ―――――――っ！！？」"

[[dialogue]]
speaker = "unk"
# そんなことある！？
line = "そんなことある！？"

[[dialogue]]
speaker = "流星寮の１年生"
# 「きゃあぁぁぁ――――――っ！？　フニちゃん、腰を壊してしまいますわ！」
line = "「きゃあぁぁぁ――――――っ！？　フニちゃん、腰を壊してしまいますわ！」"

[[dialogue]]
speaker = "流星寮の２年生"
# 「待って待って待って！　フニさん、潰れちゃう！　そのままだと潰れちゃいます！」
line = "「待って待って待って！　フニさん、潰れちゃう！　そのままだと潰れちゃいます！」"

[[dialogue]]
speaker = "フェニエル"
# 「大丈夫です！　私、こう見えて力持ちなので！」
line = "「大丈夫です！　私、こう見えて力持ちなので！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「えっ、素の力ですの！？　それ本当に、筋肉だけで持ち上げてますの！？　種も仕掛けもある手品とかじゃないんですの！？」
line = "「えっ、素の力ですの！？　それ本当に、筋肉だけで持ち上げてますの！？　種も仕掛けもある手品とかじゃないんですの！？」"

[[dialogue]]
speaker = "フェニエル"
# 「じゃあ、運びますね～」
line = "「じゃあ、運びますね～」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「あっ、お止めなさい、フニ！　出入口は像を横に倒さないと通りませんわ！　そんなの１人では――」
line = "「あっ、お止めなさい、フニ！　出入口は像を横に倒さないと通りませんわ！　そんなの１人では――」"

[[dialogue]]
speaker = "フェニエル"
# 「はい、大丈夫です、把握してますっ。……片手で一旦持って、倒して持ち替えて、っと……」
line = "「はい、大丈夫です、把握してますっ。……片手で一旦持って、倒して持ち替えて、っと……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「片手でって言いましたか今！？　えっ、貴方片手でそれを持てますの！？　発砲スチロール製じゃないんですのよそれ！？」
line = "「片手でって言いましたか今！？　えっ、貴方片手でそれを持てますの！？　発砲スチロール製じゃないんですのよそれ！？」"

[[dialogue]]
speaker = "フェニエル"
# 「これで通れますね！　中庭の設置予定場所に置いて来ます！」
line = "「これで通れますね！　中庭の設置予定場所に置いて来ます！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「フニ、中庭に像を運んでくれたことには、感謝いたしますわ」
line = "「フニ、中庭に像を運んでくれたことには、感謝いたしますわ」"

[[dialogue]]
speaker = "フェニエル"
# 「はいっ、力仕事でしたら、今後もお任せ下さい！」
line = "「はいっ、力仕事でしたら、今後もお任せ下さい！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「で・す・が、先程の行動は、あまり褒められたものではありませんわよ？」
line = "「で・す・が、先程の行動は、あまり褒められたものではありませんわよ？」"

[[dialogue]]
speaker = "フェニエル"
# 「え……お姉様、申し訳ありません。何か私、ミスをしてしまいましたか？」
line = "「え……お姉様、申し訳ありません。何か私、ミスをしてしまいましたか？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「別に怒っているわけではありませんわ。貴方がミスをしたわけでもありません。ただ……」
line = "「別に怒っているわけではありませんわ。貴方がミスをしたわけでもありません。ただ……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「幾ら力持ちでも、巨大な像を１人で運ぼうとしたことは危険な行為ですわ。手が滑れば潰されてしまうかもしれないし、前が見えなくて誰かにぶつけてしまうかもしれない」
line = "「幾ら力持ちでも、巨大な像を１人で運ぼうとしたことは危険な行為ですわ。手が滑れば潰されてしまうかもしれないし、前が見えなくて誰かにぶつけてしまうかもしれない」"

[[dialogue]]
speaker = "フェニエル"
# 「あ……」
line = "「あ……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「だから、こういう時は慎重になって、プロである業者に頼んだり、仲間で協力し合って、安全に運ぶのがエレガントというものですわ」
line = "「だから、こういう時は慎重になって、プロである業者に頼んだり、仲間で協力し合って、安全に運ぶのがエレガントというものですわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「私の言いたいこと、分かるかしら、フニ？」
line = "「私の言いたいこと、分かるかしら、フニ？」"

[[dialogue]]
speaker = "フェニエル"
# 「はい、お姉様。申し訳ありませんでした。次はまず、皆さんに相談するようにします」
line = "「はい、お姉様。申し訳ありませんでした。次はまず、皆さんに相談するようにします」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ええ、そうなさい。さて、お小言はこれでおしまいですわ。楽しいお茶会を始めましょう……と言いたいところですが――」
line = "「ええ、そうなさい。さて、お小言はこれでおしまいですわ。楽しいお茶会を始めましょう……と言いたいところですが――」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「その前に！　私、腕相撲がしたいですわ！」
line = "「その前に！　私、腕相撲がしたいですわ！」"

[[dialogue]]
speaker = "フェニエル"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "unk"
# 何て……？
line = "何て……？"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「腕相撲ですわ！　フニのあの圧倒的パワーを見せられて、最強の星騎士を目指す者として見過ごすなど出来ません！」
line = "「腕相撲ですわ！　フニのあの圧倒的パワーを見せられて、最強の星騎士を目指す者として見過ごすなど出来ません！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「それに、寮生たちの中にも、フニと戦いたい者が居るはず！　なにせここには、学園対抗杯で勝利を目指す星騎士が集っているんですもの！」
line = "「それに、寮生たちの中にも、フニと戦いたい者が居るはず！　なにせここには、学園対抗杯で勝利を目指す星騎士が集っているんですもの！」"

[[dialogue]]
speaker = "フェニエル"
# 「えええぇぇぇっ！？　いや、でも私、腕相撲とか全然したことがなくて……！」
line = "「えええぇぇぇっ！？　いや、でも私、腕相撲とか全然したことがなくて……！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「おーっほっほっほ！　さあ、変身して勝負ですわよ、フニ！」
line = "「おーっほっほっほ！　さあ、変身して勝負ですわよ、フニ！」"

[[dialogue]]
speaker = "unk"
# 俺もちょっと勝負してみたいかも
line = "俺もちょっと勝負してみたいかも"

[[dialogue]]
speaker = "フェニエル"
# 「会長さんまで！？」
line = "「会長さんまで！？」"

[[dialogue]]
speaker = "unk"
# その後、流星寮ではお茶会も忘れる程に、熱い腕相撲大会が開かれることとなるのだった。
line = "その後、流星寮ではお茶会も忘れる程に、熱い腕相撲大会が開かれることとなるのだった。"
