[[dialogue]]
speaker = "unk"
# 第４話,ブルーハワイのかき氷,P
line = "第４話,ブルーハワイのかき氷,P"

[[dialogue]]
speaker = "unk"
# 今日はいつもと違って、プライベートビーチでアムとデートをすることにした。というのも──
line = "今日はいつもと違って、プライベートビーチでアムとデートをすることにした。というのも──"

[[dialogue]]
speaker = "アム"
# 「ん、ちゅっ……ちゅぅ、ちゅっ……<emoji=heart04>」
line = "「ん、ちゅっ……ちゅぅ、ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アム"
# 「えへへ<emoji=heart04>　誰もいないってわかってはいるけど、普段賑わってる浜辺でキスするのってドキドキするね……♪」
line = "「えへへ<emoji=heart04>　誰もいないってわかってはいるけど、普段賑わってる浜辺でキスするのってドキドキするね……♪」"

[[dialogue]]
speaker = "アム"
# 「でも驚いちゃった。会長が、リップル先輩にプライベートビーチをお願いした～って聞いた時から、ちょっぴり予想はしてたけど……」
line = "「でも驚いちゃった。会長が、リップル先輩にプライベートビーチをお願いした～って聞いた時から、ちょっぴり予想はしてたけど……」"

[[dialogue]]
speaker = "アム"
# 「まさかビーチに来て、いきなりキスされると思ってなかったよ」
line = "「まさかビーチに来て、いきなりキスされると思ってなかったよ」"

[[dialogue]]
speaker = "unk"
# あんまりいちゃいちゃしてくれないから
line = "あんまりいちゃいちゃしてくれないから"

[[dialogue]]
speaker = "unk"
# アムは周りに人がいると
line = "アムは周りに人がいると"

[[dialogue]]
speaker = "アム"
# 「そ、そりゃそうでしょ？　人前で腕を組んでべたべたしたり、キスとかしてたらバカップルじゃん……そういうのってカッコよくないもん」
line = "「そ、そりゃそうでしょ？　人前で腕を組んでべたべたしたり、キスとかしてたらバカップルじゃん……そういうのってカッコよくないもん」"

[[dialogue]]
speaker = "アム"
# 「でもわざわざビーチを貸し切ってまで、あたしといちゃいちゃしたいって思ってくれたのは素直に嬉しいし……」
line = "「でもわざわざビーチを貸し切ってまで、あたしといちゃいちゃしたいって思ってくれたのは素直に嬉しいし……」"

[[dialogue]]
speaker = "アム"
# 「うん、今日この場所では、会長のリクエストは断らないよ？」
line = "「うん、今日この場所では、会長のリクエストは断らないよ？」"

[[dialogue]]
speaker = "アム"
# 「ん、ちゅぅー……ちゅ、ちゅぅ、んちゅっ……へへ～っ<emoji=heart04>」
line = "「ん、ちゅぅー……ちゅ、ちゅぅ、んちゅっ……へへ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "アム"
# 「リゾート結界の外でデートする時は、けっこーガマンしてるからかなぁ……反動来ちゃってるかも……あ、会長も？」
line = "「リゾート結界の外でデートする時は、けっこーガマンしてるからかなぁ……反動来ちゃってるかも……あ、会長も？」"

[[dialogue]]
speaker = "アム"
# 「気が合うね、会長♪　じゃあもっとしよー……ん、ちゅー<emoji=heart04>」
line = "「気が合うね、会長♪　じゃあもっとしよー……ん、ちゅー<emoji=heart04>」"

[[dialogue]]
speaker = "アム"
# 「にひひ<emoji=heart04>　今日はいっぱいキスして、いっぱい遊ぼうね<emoji=heart04>」
line = "「にひひ<emoji=heart04>　今日はいっぱいキスして、いっぱい遊ぼうね<emoji=heart04>」"

[[dialogue]]
speaker = "アム"
# 「プライベートビーチって人の目がないのはいいけど、海の家でご飯を買えないのが難点だよね～」
line = "「プライベートビーチって人の目がないのはいいけど、海の家でご飯を買えないのが難点だよね～」"

[[dialogue]]
speaker = "アム"
# 「でも会長に、飲食店のアルバイト経験があって助かったかも。あたし、家庭科はあんまりだからさー」
line = "「でも会長に、飲食店のアルバイト経験があって助かったかも。あたし、家庭科はあんまりだからさー」"

[[dialogue]]
speaker = "アム"
# 「んー、ソースの美味しそうな匂い！　リップル先輩とどっちが焼きそば作るのが上手か、あたしが判定してあげる！」
line = "「んー、ソースの美味しそうな匂い！　リップル先輩とどっちが焼きそば作るのが上手か、あたしが判定してあげる！」"

[[dialogue]]
speaker = "unk"
# アムもやってみる？
line = "アムもやってみる？"

[[dialogue]]
speaker = "アム"
# 「んー……ちょっと興味はあるんだけど、やめとく。持ってきてる食材で失敗したら悲惨だし……」
line = "「んー……ちょっと興味はあるんだけど、やめとく。持ってきてる食材で失敗したら悲惨だし……」"

[[dialogue]]
speaker = "アム"
# 「その代わり、あたしはデザート作るよ！　氷と、かき氷機は持ってきたから！　ふっふーん、これなら失敗しないもんね！」
line = "「その代わり、あたしはデザート作るよ！　氷と、かき氷機は持ってきたから！　ふっふーん、これなら失敗しないもんね！」"

[[dialogue]]
speaker = "アム"
# 「会長は何味にする？　ブルーハワイ……うん、定番だね。あたしはイチゴにしよっと！」
line = "「会長は何味にする？　ブルーハワイ……うん、定番だね。あたしはイチゴにしよっと！」"

[[dialogue]]
speaker = "アム"
# 「ご飯食べ終わったらどうしよっかなあ。泳ぐのもいいし、パラソルの下でまったりするのもいいけど……」
line = "「ご飯食べ終わったらどうしよっかなあ。泳ぐのもいいし、パラソルの下でまったりするのもいいけど……」"

[[dialogue]]
speaker = "unk"
# アムとまたいちゃいちゃしたいな
line = "アムとまたいちゃいちゃしたいな"

[[dialogue]]
speaker = "アム"
# 「も、も～……<emoji=heart04>　朝からそればっかりじゃん、会長……」
line = "「も、も～……<emoji=heart04>　朝からそればっかりじゃん、会長……」"

[[dialogue]]
speaker = "アム"
# 「でも、あたしも賛成！　せっかくビーチを貸し切ってくれたんだもんね……」
line = "「でも、あたしも賛成！　せっかくビーチを貸し切ってくれたんだもんね……」"

[[dialogue]]
speaker = "アム"
# 「うん、好きだよ、会長っ<emoji=heart04>」
line = "「うん、好きだよ、会長っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そうして俺とアムは、日が暮れるまで海水浴デートを楽しんだ──
line = "そうして俺とアムは、日が暮れるまで海水浴デートを楽しんだ──"

[[dialogue]]
speaker = "アム"
# 「じゃーね、会長！　また明日～っ！」
line = "「じゃーね、会長！　また明日～っ！」"

[[dialogue]]
speaker = "アム"
# 「あー、今日は楽しかったな～♪　……ん、あそこにいるのは……エルゼ？」
line = "「あー、今日は楽しかったな～♪　……ん、あそこにいるのは……エルゼ？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「もぐもぐ……もぐもぐ……♪」
line = "「もぐもぐ……もぐもぐ……♪」"

[[dialogue]]
speaker = "アム"
# 「寮を抜け出して買い食いする不良生徒、はっけ～ん♪」
line = "「寮を抜け出して買い食いする不良生徒、はっけ～ん♪」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「──アムっ！？　まま、まさかこんなところで会うだなんて……！」
line = "「──アムっ！？　まま、まさかこんなところで会うだなんて……！」"

[[dialogue]]
speaker = "アム"
# 「相変わらずだねー。あんまり門限破ってたら、寮長にバレちゃうんじゃないの？」
line = "「相変わらずだねー。あんまり門限破ってたら、寮長にバレちゃうんじゃないの？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「え、ええっ……それはわかっているのですが。あの、アム。このことは……」
line = "「え、ええっ……それはわかっているのですが。あの、アム。このことは……」"

[[dialogue]]
speaker = "アム"
# 「わかってるよー、内緒にするって。ふふ、両手で抱えてるたい焼き、１つくれればね♪」
line = "「わかってるよー、内緒にするって。ふふ、両手で抱えてるたい焼き、１つくれればね♪」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ちゃっかりしてますわね、アムは……出来立てのアツアツですから気を付けてくださいませ？」
line = "「ちゃっかりしてますわね、アムは……出来立てのアツアツですから気を付けてくださいませ？」"

[[dialogue]]
speaker = "アム"
# 「やったー♪　交渉、成立～っ」
line = "「やったー♪　交渉、成立～っ」"

[[dialogue]]
speaker = "アム"
# 「んー、おいし～っ♪」
line = "「んー、おいし～っ♪」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ところでアムの方こそ、こんな時間まで何をしていたのですか？」
line = "「ところでアムの方こそ、こんな時間まで何をしていたのですか？」"

[[dialogue]]
speaker = "アム"
# 「んー？　会長と海でデートしてたんだ。リップル先輩のリゾート結界でね」
line = "「んー？　会長と海でデートしてたんだ。リップル先輩のリゾート結界でね」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「まぁ！　それは素敵なお休みだったのですね。どんなことをしたのです？　サーフィン？　それともビーチバレーとか？」
line = "「まぁ！　それは素敵なお休みだったのですね。どんなことをしたのです？　サーフィン？　それともビーチバレーとか？」"

[[dialogue]]
speaker = "アム"
# 「あー、うん。まあそんなところ……かな？　遊んでお腹が空いたら、かき氷作ったりしてさ──」
line = "「あー、うん。まあそんなところ……かな？　遊んでお腹が空いたら、かき氷作ったりしてさ──」"

[[dialogue]]
speaker = "アム"
# （本当はあんまり遊んでなくて、ずっとチューしたりくっついたりしてたんだけど……）
line = "（本当はあんまり遊んでなくて、ずっとチューしたりくっついたりしてたんだけど……）"

[[dialogue]]
speaker = "アム"
# （な、なんか今になって恥ずかしくなってきたかも……いや、言わなきゃバレないんだけど……！）
line = "（な、なんか今になって恥ずかしくなってきたかも……いや、言わなきゃバレないんだけど……！）"

[[dialogue]]
speaker = "エルデリーゼ"
# 「アム、急に黙ってどうしたのです？　かき氷を作って、それで……？」
line = "「アム、急に黙ってどうしたのです？　かき氷を作って、それで……？」"

[[dialogue]]
speaker = "アム"
# 「あ、ああ、うん！　あたしがイチゴで、会長がブルーハワイだったんだけど。エルゼ、知ってた？　かき氷の味って、実はどれもおんなじだって会長が──」
line = "「あ、ああ、うん！　あたしがイチゴで、会長がブルーハワイだったんだけど。エルゼ、知ってた？　かき氷の味って、実はどれもおんなじだって会長が──」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「イチゴ？　アムが召し上がったのは、ブルーハワイの方では？」
line = "「イチゴ？　アムが召し上がったのは、ブルーハワイの方では？」"

[[dialogue]]
speaker = "アム"
# 「えー、違うよ。あたしはイチゴを食べたよ？　やっぱりかき氷の王道はイチゴだよ！」
line = "「えー、違うよ。あたしはイチゴを食べたよ？　やっぱりかき氷の王道はイチゴだよ！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「変ですね……？　だってアム、舌がとっても青いですわよ？　いえ、どちらかと言うと、紫……？」
line = "「変ですね……？　だってアム、舌がとっても青いですわよ？　いえ、どちらかと言うと、紫……？」"

[[dialogue]]
speaker = "アム"
# 「うぇっ──！？」
line = "「うぇっ──！？」"

[[dialogue]]
speaker = "アム"
# （も、もしかして……会長とたくさんキスしてるうちに……色が移っちゃった……！？）
line = "（も、もしかして……会長とたくさんキスしてるうちに……色が移っちゃった……！？）"

[[dialogue]]
speaker = "アム"
# （き、キスマーク見られてるみたいで恥ずかしいんだけど～っ！？）
line = "（き、キスマーク見られてるみたいで恥ずかしいんだけど～っ！？）"

[[dialogue]]
speaker = "アム"
# （ていうか、これ絶対にバレるやつ！　かき氷食べた後、いっぱいキスしてたのバレちゃうやつだ……！！）
line = "（ていうか、これ絶対にバレるやつ！　かき氷食べた後、いっぱいキスしてたのバレちゃうやつだ……！！）"

[[dialogue]]
speaker = "アム"
# 「あ、あーっ……ごめん！　あたし、急用を思い出しちゃった！　そ、それじゃあね、エルゼーっ！」
line = "「あ、あーっ……ごめん！　あたし、急用を思い出しちゃった！　そ、それじゃあね、エルゼーっ！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「……？　行ってしまいました……アムってば、どうしたのでしょうか。あんなに真っ赤になって、恥ずかしがって……」
line = "「……？　行ってしまいました……アムってば、どうしたのでしょうか。あんなに真っ赤になって、恥ずかしがって……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「──あ、もしかして！？」
line = "「──あ、もしかして！？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ふふ♪　かき氷をお代わりして、食いしん坊だと思われるのが嫌だったのですね。お可愛いところもあるではないですか、アムも」
line = "「ふふ♪　かき氷をお代わりして、食いしん坊だと思われるのが嫌だったのですね。お可愛いところもあるではないですか、アムも」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「もぐもぐ……たい焼き、おいしいですわね♪」
line = "「もぐもぐ……たい焼き、おいしいですわね♪」"
