[[dialogue]]
speaker = "unk"
# 第１話,選挙管理委員会誕生！,P
line = "第１話,選挙管理委員会誕生！,P"

[[dialogue]]
speaker = "unk"
# 謎の転校生、梨緒・<ruby=アガサ>Ａ</ruby>・クリステレス。
line = "謎の転校生、梨緒・<ruby>Ａ<rt>アガサ</rt></ruby>・クリステレス。"

[[dialogue]]
speaker = "unk"
# 彼女との御前試合に勝利し、新星学園の星徒会長の座を守ったのが数日前のこと。
line = "彼女との御前試合に勝利し、新星学園の星徒会長の座を守ったのが数日前のこと。"

[[dialogue]]
speaker = "unk"
# だが──
line = "だが──"

[[dialogue]]
speaker = "梨緒"
# 「緋宮会長。確かに私は御前試合で敗れた。君が星徒会長にふさわしいと認めよう」
line = "「緋宮会長。確かに私は御前試合で敗れた。君が星徒会長にふさわしいと認めよう」"

[[dialogue]]
speaker = "梨緒"
# 「だが魔王である君から目を離すことはできない。よって選挙管理委員会を設立し、君を監視させてもらう！」
line = "「だが魔王である君から目を離すことはできない。よって選挙管理委員会を設立し、君を監視させてもらう！」"

[[dialogue]]
speaker = "unk"
# とある日の放課後。マトイと一緒に星徒会室に向かう途中、唐突に宣戦布告（？）された。
line = "とある日の放課後。マトイと一緒に星徒会室に向かう途中、唐突に宣戦布告（？）された。"

[[dialogue]]
speaker = "マトイ"
# 「選挙管理委員会……？　そもそも<ruby=うち>新星学園</ruby>に選挙ってないんじゃ？」
line = "「選挙管理委員会……？　そもそも<ruby>新星学園<rt>うち</rt></ruby>に選挙ってないんじゃ？」"

[[dialogue]]
speaker = "梨緒"
# 「ああ。選挙管理委員会とは本来、生徒会選挙を公正に行うためのものだ。だから選挙のない新星学園では、選挙管理委員会が今まで存在しなかった」
line = "「ああ。選挙管理委員会とは本来、生徒会選挙を公正に行うためのものだ。だから選挙のない新星学園では、選挙管理委員会が今まで存在しなかった」"

[[dialogue]]
speaker = "マトイ"
# 「だよね……。星徒会長は先代の会長が指名するものだし」
line = "「だよね……。星徒会長は先代の会長が指名するものだし」"

[[dialogue]]
speaker = "梨緒"
# 「だが選挙が全く行われないわけではない」
line = "「だが選挙が全く行われないわけではない」"

[[dialogue]]
speaker = "梨緒"
# 「強権を持つ星徒会長とはいえ、校則によれば、全校生徒の３分の２の賛成があればリコールすることができる」
line = "「強権を持つ星徒会長とはいえ、校則によれば、全校生徒の３分の２の賛成があればリコールすることができる」"

[[dialogue]]
speaker = "梨緒"
# 「そしてリコールによって星徒会長が不在になった場合、選挙によって新たな星徒会長が選ばれることになっている」
line = "「そしてリコールによって星徒会長が不在になった場合、選挙によって新たな星徒会長が選ばれることになっている」"

[[dialogue]]
speaker = "梨緒"
# 「私の設立した選挙管理委員会──選管は、常日頃から星徒会を監視し、不適切な運営が行われた場合、全校生徒に対してリコールを発議する組織だ」
line = "「私の設立した選挙管理委員会──選管は、常日頃から星徒会を監視し、不適切な運営が行われた場合、全校生徒に対してリコールを発議する組織だ」"

[[dialogue]]
speaker = "梨緒"
# 「学園側にも正式に設立が認められた。……今はまだ私１人だけだが」
line = "「学園側にも正式に設立が認められた。……今はまだ私１人だけだが」"

[[dialogue]]
speaker = "マトイ"
# 「な、なるほど……思ったよりちゃんとした委員会なんだ……」
line = "「な、なるほど……思ったよりちゃんとした委員会なんだ……」"

[[dialogue]]
speaker = "梨緒"
# 「つまり君が星徒会長にふさわしくないと判断した場合、私はリコールを発議する。心してくれ」
line = "「つまり君が星徒会長にふさわしくないと判断した場合、私はリコールを発議する。心してくれ」"

[[dialogue]]
speaker = "unk"
# ああ、わかった
line = "ああ、わかった"

[[dialogue]]
speaker = "梨緒"
# 「では──」
line = "「では──」"

[[dialogue]]
speaker = "梨緒"
# 「勝負だ！」
line = "「勝負だ！」"

[[dialogue]]
speaker = "unk"
# なんで！？
line = "なんで！？"

[[dialogue]]
speaker = "梨緒"
# 「星徒会長は新星学園全校生徒の頂点に立つ者。相応の実力や振る舞いが求められる」
line = "「星徒会長は新星学園全校生徒の頂点に立つ者。相応の実力や振る舞いが求められる」"

[[dialogue]]
speaker = "梨緒"
# 「よって君が星徒会長に相応しいか、勝負を通して確認させてもらう。選管の正当な業務だ」
line = "「よって君が星徒会長に相応しいか、勝負を通して確認させてもらう。選管の正当な業務だ」"

[[dialogue]]
speaker = "マトイ"
# 「なる……ほど……？」
line = "「なる……ほど……？」"

[[dialogue]]
speaker = "unk"
# で、何の勝負にする？
line = "で、何の勝負にする？"

[[dialogue]]
speaker = "梨緒"
# 「驚いた割に勝負はすんなり受けるんだな。御前試合の時は時間がかかったのに」
line = "「驚いた割に勝負はすんなり受けるんだな。御前試合の時は時間がかかったのに」"

[[dialogue]]
speaker = "unk"
# 梨緒が真剣なのはわかってるから
line = "梨緒が真剣なのはわかってるから"

[[dialogue]]
speaker = "梨緒"
# 「む……そうか」
line = "「む……そうか」"

[[dialogue]]
speaker = "梨緒"
# 「こんな時にモンスターか……いや。モンスターを駆逐するのは星騎士の本分。どちらが先にモンスターを倒すか勝負だ！」
line = "「こんな時にモンスターか……いや。モンスターを駆逐するのは星騎士の本分。どちらが先にモンスターを倒すか勝負だ！」"

[[dialogue]]
speaker = "unk"
# 鋭い牙を突き立てようとするモンスターに、俺と梨緒が攻撃を叩き込む。
line = "鋭い牙を突き立てようとするモンスターに、俺と梨緒が攻撃を叩き込む。"

[[dialogue]]
speaker = "梨緒"
# 「モンスターの殲滅完了。マトイ、どちらが早かった？」
line = "「モンスターの殲滅完了。マトイ、どちらが早かった？」"

[[dialogue]]
speaker = "マトイ"
# 「うーん、僅差だったと思うけど……しいて言うなら会長かな」
line = "「うーん、僅差だったと思うけど……しいて言うなら会長かな」"

[[dialogue]]
speaker = "梨緒"
# 「くっ、負けた……」
line = "「くっ、負けた……」"

[[dialogue]]
speaker = "梨緒"
# 「速さには自信があったのに……やはり私はダメな星騎士だ……。私なんて、サメ映画で最初に食われる役がお似合いなんだ……」
line = "「速さには自信があったのに……やはり私はダメな星騎士だ……。私なんて、サメ映画で最初に食われる役がお似合いなんだ……」"

[[dialogue]]
speaker = "マトイ"
# 「すっごく落ち込んでる！？　なんでサメ映画！？」
line = "「すっごく落ち込んでる！？　なんでサメ映画！？」"

[[dialogue]]
speaker = "マトイ"
# 「ところで……梨緒さん？　転入生なのにどうして私のこと知ってるの？」
line = "「ところで……梨緒さん？　転入生なのにどうして私のこと知ってるの？」"

[[dialogue]]
speaker = "梨緒"
# 「マトイだけじゃなくて、新星学園の星騎士のことは概ね知っている。私は以前、新星星徒会の副会長だったからな」
line = "「マトイだけじゃなくて、新星学園の星騎士のことは概ね知っている。私は以前、新星星徒会の副会長だったからな」"

[[dialogue]]
speaker = "マトイ"
# 「梨緒さんが副会長？　アナじゃなくて……？」
line = "「梨緒さんが副会長？　アナじゃなくて……？」"

[[dialogue]]
speaker = "梨緒"
# 「私の知っている君は星徒会役員ではなかったが、変わらず努力家で、優秀な星騎士だった。あの時も……」
line = "「私の知っている君は星徒会役員ではなかったが、変わらず努力家で、優秀な星騎士だった。あの時も……」"

[[dialogue]]
speaker = "梨緒"
# 「うう……あの時、私がもっと強ければ、マトイは……マトイは……」
line = "「うう……あの時、私がもっと強ければ、マトイは……マトイは……」"

[[dialogue]]
speaker = "マトイ"
# 「悪化した！？　ごめん、私何か悪いことした！？」
line = "「悪化した！？　ごめん、私何か悪いことした！？」"

[[dialogue]]
speaker = "梨緒"
# 「ぐすっ……マトイは何も悪くない……ただ惰弱で非力な私が悪いんだ……」
line = "「ぐすっ……マトイは何も悪くない……ただ惰弱で非力な私が悪いんだ……」"

[[dialogue]]
speaker = "unk"
# 心に深い傷があるらしくて……
line = "心に深い傷があるらしくて……"

[[dialogue]]
speaker = "マトイ"
# 「そ、そうなんだ……大変だね……」
line = "「そ、そうなんだ……大変だね……」"

[[dialogue]]
speaker = "マトイ"
# 「でも梨緒さんも落ち込むことあるんだ。意外かも」
line = "「でも梨緒さんも落ち込むことあるんだ。意外かも」"

[[dialogue]]
speaker = "梨緒"
# 「意外？」
line = "「意外？」"

[[dialogue]]
speaker = "マトイ"
# 「うん。梨緒さんって会長と御前試合で戦えるくらい強いし、凛々しくてかっこいいから、落ち込まないと思ってた」
line = "「うん。梨緒さんって会長と御前試合で戦えるくらい強いし、凛々しくてかっこいいから、落ち込まないと思ってた」"

[[dialogue]]
speaker = "梨緒"
# 「強い！？　凛々しい！？　かっこいい！？」
line = "「強い！？　凛々しい！？　かっこいい！？」"

[[dialogue]]
speaker = "梨緒"
# 「そそ、そんなことはないっ、私なんて火を点ける前に折れたマッチのような、何の役にも立たない存在なんだ！！」
line = "「そそ、そんなことはないっ、私なんて火を点ける前に折れたマッチのような、何の役にも立たない存在なんだ！！」"

[[dialogue]]
speaker = "マトイ"
# 「そこまで自分を卑下しなくても……」
line = "「そこまで自分を卑下しなくても……」"

[[dialogue]]
speaker = "梨緒"
# 「……すまない、取り乱した」
line = "「……すまない、取り乱した」"

[[dialogue]]
speaker = "梨緒"
# 「今日は負けを認めよう、緋宮会長。だが私は何度敗れようと諦めない。世界を守るために君に勝つ！」
line = "「今日は負けを認めよう、緋宮会長。だが私は何度敗れようと諦めない。世界を守るために君に勝つ！」"

[[dialogue]]
speaker = "マトイ"
# 「あ、行っちゃった……。梨緒さんって、キリッとしててかっこいいけど、よくわからないところも多いよね……」
line = "「あ、行っちゃった……。梨緒さんって、キリッとしててかっこいいけど、よくわからないところも多いよね……」"

[[dialogue]]
speaker = "unk"
# 翌日の登校中──
line = "翌日の登校中──"

[[dialogue]]
speaker = "梨緒"
# 「勝負だ、緋宮会長！」
line = "「勝負だ、緋宮会長！」"

[[dialogue]]
speaker = "unk"
# またいきなり！？
line = "またいきなり！？"

[[dialogue]]
speaker = "梨緒"
# 「星徒会長たる者、規則正しい生活を送り、品行方正であらねばならない。今日から無遅刻無欠席をどちらが長く続けられるか、勝負だ！」
line = "「星徒会長たる者、規則正しい生活を送り、品行方正であらねばならない。今日から無遅刻無欠席をどちらが長く続けられるか、勝負だ！」"

[[dialogue]]
speaker = "unk"
# しかし途中でアステラが発生してしまい、俺と梨緒は仲良く遅刻したのであった──
line = "しかし途中でアステラが発生してしまい、俺と梨緒は仲良く遅刻したのであった──"
