[[dialogue]]
speaker = "unk"
# 蘭美と恋人として付き合い始めてからしばらく経った、ある日の放課後。
line = "蘭美と恋人として付き合い始めてからしばらく経った、ある日の放課後。"

[[dialogue]]
speaker = "unk"
# 新星学園の屋外を歩いていると、蘭美から声をかけられた。
line = "新星学園の屋外を歩いていると、蘭美から声をかけられた。"

[[dialogue]]
speaker = "蘭美"
# 「会長、ちょっといいかしら？　こっちこっち」
line = "「会長、ちょっといいかしら？　こっちこっち」"

[[dialogue]]
speaker = "unk"
# 手招きされて、人通りの少ない校舎裏へと移動する。
line = "手招きされて、人通りの少ない校舎裏へと移動する。"

[[dialogue]]
speaker = "蘭美"
# 「よし、この辺りでいいわね。じゃあ――」
line = "「よし、この辺りでいいわね。じゃあ――」"

[[dialogue]]
speaker = "unk"
# そう言うと、彼女はいきなりスカートの下に履いているショーツを脱ぎ出した。
line = "そう言うと、彼女はいきなりスカートの下に履いているショーツを脱ぎ出した。"

[[dialogue]]
speaker = "蘭美"
# 「よいしょっと……<emoji=heart04>」
line = "「よいしょっと……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「――ごめんなさい、会長。悪いんだけど……いつものアレが我慢できなくなっちゃったの<emoji=heart04>」
line = "「――ごめんなさい、会長。悪いんだけど……いつものアレが我慢できなくなっちゃったの<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「そう、発情期<emoji=heart04>　ふうぅ……<emoji=heart04>」
line = "「そう、発情期<emoji=heart04>　ふうぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 蘭美の種族は繁殖能力が高く、『万年発情期』体質だという。
line = "蘭美の種族は繁殖能力が高く、『万年発情期』体質だという。"

[[dialogue]]
speaker = "unk"
# 薬である程度、症状を抑えることは可能だが、好きな相手ができると時折、発情を抑え切れなくなってしまうらしい。
line = "薬である程度、症状を抑えることは可能だが、好きな相手ができると時折、発情を抑え切れなくなってしまうらしい。"

[[dialogue]]
speaker = "unk"
# なので、彼女がそうなってしまった際は、俺が恋人として性欲処理を手伝ってあげていた。
line = "なので、彼女がそうなってしまった際は、俺が恋人として性欲処理を手伝ってあげていた。"

[[dialogue]]
speaker = "蘭美"
# 「――でも、青姦はマズいって？　ふふっ♪　そんなに慌てなくても大丈夫よ、会長」
line = "「――でも、青姦はマズいって？　ふふっ♪　そんなに慌てなくても大丈夫よ、会長」"

[[dialogue]]
speaker = "蘭美"
# 「羽宮一族には代々、発情期対策で、こういう時の為の『隠蔽星術』が受け継がれているの」
line = "「羽宮一族には代々、発情期対策で、こういう時の為の『隠蔽星術』が受け継がれているの」"

[[dialogue]]
speaker = "蘭美"
# 「それを既に発動しているから、私たちの姿は周囲に見えないようになっているわ♪」
line = "「それを既に発動しているから、私たちの姿は周囲に見えないようになっているわ♪」"

[[dialogue]]
speaker = "蘭美"
# 「だから、安心して。それに……ふふっ<emoji=heart04>　貴方だって<b>期待してる</b>みたいだけど？」
line = "「だから、安心して。それに……ふふっ<emoji=heart04>　貴方だって<b>期待してる</b>みたいだけど？」"

[[dialogue]]
speaker = "unk"
# 彼女は俺の股間を擦りながら、囁く。
line = "彼女は俺の股間を擦りながら、囁く。"

[[dialogue]]
speaker = "蘭美"
# 「ほら、ここ。固くなってる……<emoji=heart04>」
line = "「ほら、ここ。固くなってる……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「――このところ、お互い忙しくてできてなかったからって？」
line = "「――このところ、お互い忙しくてできてなかったからって？」"

[[dialogue]]
speaker = "蘭美"
# 「なら、ちゃんとしないとダメじゃない♪」
line = "「なら、ちゃんとしないとダメじゃない♪」"

[[dialogue]]
speaker = "蘭美"
# 「自分の体調管理も仕事のうちよ？　ほら、早く<emoji=heart04>」
line = "「自分の体調管理も仕事のうちよ？　ほら、早く<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 甘い誘いに、俺は抗うことができず――
line = "甘い誘いに、俺は抗うことができず――"

[[dialogue]]
speaker = "蘭美"
# 「んっ……会長……<emoji=heart04>　ちゅっ……<emoji=heart04>」
line = "「んっ……会長……<emoji=heart04>　ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 彼女は恍惚とした表情で、キスをねだってくる。
line = "彼女は恍惚とした表情で、キスをねだってくる。"

[[dialogue]]
speaker = "蘭美"
# 「ちゅっ……ちゅぱっ<emoji=heart04>　んっ……ちゅぷっ……<emoji=heart04>　れろちゅっ……<emoji=heart04>」
line = "「ちゅっ……ちゅぱっ<emoji=heart04>　んっ……ちゅぷっ……<emoji=heart04>　れろちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「はあぁっ……<emoji=heart04>　舌を絡めるエッチなキス、好き……<emoji=heart04>　んむっ……<emoji=heart04>　ちゅぷぷっ……れろちゅっ<emoji=heart04>　れるれるっ……ちゅぱっ……ちゅるるっ<emoji=heart04>」
line = "「はあぁっ……<emoji=heart04>　舌を絡めるエッチなキス、好き……<emoji=heart04>　んむっ……<emoji=heart04>　ちゅぷぷっ……れろちゅっ<emoji=heart04>　れるれるっ……ちゅぱっ……ちゅるるっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「んっ……れろちゅっ……<emoji=heart04>　もっと……<emoji=heart04>　ちゅっ……ちゅぱっ……<emoji=heart04>　ちゅぷぷっ……ちゅれるっ……ちゅるるっ……<emoji=heart04>　ちゅっちゅっ……れろちゅっ……<emoji=heart04>」
line = "「んっ……れろちゅっ……<emoji=heart04>　もっと……<emoji=heart04>　ちゅっ……ちゅぱっ……<emoji=heart04>　ちゅぷぷっ……ちゅれるっ……ちゅるるっ……<emoji=heart04>　ちゅっちゅっ……れろちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「んむっ……ちゅぱっ……ぷはぁっ……<emoji=heart04>　んっ……<emoji=heart04>　――ふふっ、濃厚なキスで唾液がエッチな糸引いちゃってる……<emoji=heart04>」
line = "「んむっ……ちゅぱっ……ぷはぁっ……<emoji=heart04>　んっ……<emoji=heart04>　――ふふっ、濃厚なキスで唾液がエッチな糸引いちゃってる……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「おま○この方も濡れてきちゃった……<emoji=heart04>」
line = "「おま○この方も濡れてきちゃった……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「ね、触って……？」
line = "「ね、触って……？」"

[[dialogue]]
speaker = "unk"
# 彼女が俺の右手に触れて、そっと下の方に誘導する。指で彼女の小さな割れ目に触れると――
line = "彼女が俺の右手に触れて、そっと下の方に誘導する。指で彼女の小さな割れ目に触れると――"

[[dialogue]]
speaker = "蘭美"
# 「あっ<emoji=heart04>　あんっ……<emoji=heart04>」
line = "「あっ<emoji=heart04>　あんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「はあぁっ……ふうぅっ……<emoji=heart04>　んっ……<emoji=heart04>　貴方の指、おま○こに入ってくるわ<emoji=heart04>」
line = "「はあぁっ……ふうぅっ……<emoji=heart04>　んっ……<emoji=heart04>　貴方の指、おま○こに入ってくるわ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あっ、あんっ<emoji=heart04>　はあぁっ……ふあぁっ……<emoji=heart04>　んっ……あっ<emoji=heart04>　はあぁっ……ふうぅっ……<emoji=heart04>　んっ……んうぅっ……<emoji=heart04>」
line = "「あっ、あんっ<emoji=heart04>　はあぁっ……ふあぁっ……<emoji=heart04>　んっ……あっ<emoji=heart04>　はあぁっ……ふうぅっ……<emoji=heart04>　んっ……んうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「はあぁっ……<emoji=heart04>　くちゅくちゅってエッチな音が聞こえてきてる<emoji=heart04>　あっ、あんっ<emoji=heart04>　ふうぅっ……んんっ……<emoji=heart04>」
line = "「はあぁっ……<emoji=heart04>　くちゅくちゅってエッチな音が聞こえてきてる<emoji=heart04>　あっ、あんっ<emoji=heart04>　ふうぅっ……んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あっ<emoji=heart04>　そこ弱いの<emoji=heart04>　あっ、あっ<emoji=heart04>　ダメ<emoji=heart04>　感じて、愛液いっぱい出てきちゃうっ……<emoji=heart04>　あっ、はあぁっ……<emoji=heart04>　んあぁっ……<emoji=heart04>」
line = "「あっ<emoji=heart04>　そこ弱いの<emoji=heart04>　あっ、あっ<emoji=heart04>　ダメ<emoji=heart04>　感じて、愛液いっぱい出てきちゃうっ……<emoji=heart04>　あっ、はあぁっ……<emoji=heart04>　んあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「んっ<emoji=heart04>　あっ<emoji=heart04>　もうおま○この方もぐちょぐちょで、エッチな糸引いちゃってるぅ……<emoji=heart04>　はあぁっ……<emoji=heart04>　ふあぁっ……<emoji=heart04>」
line = "「んっ<emoji=heart04>　あっ<emoji=heart04>　もうおま○この方もぐちょぐちょで、エッチな糸引いちゃってるぅ……<emoji=heart04>　はあぁっ……<emoji=heart04>　ふあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あっ、あんっ<emoji=heart04>　会長の勃起おち○ぽ、当たってる<emoji=heart04>　んっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　んあぁっ……<emoji=heart04>」
line = "「あっ、あんっ<emoji=heart04>　会長の勃起おち○ぽ、当たってる<emoji=heart04>　んっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　んあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「熱くて大きいので、おま○この穴に、ちゅっちゅって<emoji=heart04>　あっ<emoji=heart04>　キスされちゃってるっ<emoji=heart04>　んっ<emoji=heart04>　はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」
line = "「熱くて大きいので、おま○この穴に、ちゅっちゅって<emoji=heart04>　あっ<emoji=heart04>　キスされちゃってるっ<emoji=heart04>　んっ<emoji=heart04>　はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「ふあぁっ<emoji=heart04>　ダメ<emoji=heart04>　クリ擦るの感じちゃう<emoji=heart04>　あっ、あっ<emoji=heart04>　はぁっ……ふああぁんっ……<emoji=heart04>」
line = "「ふあぁっ<emoji=heart04>　ダメ<emoji=heart04>　クリ擦るの感じちゃう<emoji=heart04>　あっ、あっ<emoji=heart04>　はぁっ……ふああぁんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「んっ……<emoji=heart04>　ね、ねぇ<emoji=heart04>　もう会長のも愛液でぬちょぬちょになってるから……もういいでしょ？」
line = "「んっ……<emoji=heart04>　ね、ねぇ<emoji=heart04>　もう会長のも愛液でぬちょぬちょになってるから……もういいでしょ？」"

[[dialogue]]
speaker = "蘭美"
# 「おま○こ……入れてぇ<emoji=heart04>」
line = "「おま○こ……入れてぇ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あんっ<emoji=heart04>　焦らさないで、おち○ぽ早くぅ～<emoji=heart04>」
line = "「あんっ<emoji=heart04>　焦らさないで、おち○ぽ早くぅ～<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「ふあぁっ……<emoji=heart04>　おち○ぽ、私の穴にグリグリされてるぅ……<emoji=heart04>　あっ<emoji=heart04>　はあぁっ……んんっ……<emoji=heart04>」
line = "「ふあぁっ……<emoji=heart04>　おち○ぽ、私の穴にグリグリされてるぅ……<emoji=heart04>　あっ<emoji=heart04>　はあぁっ……んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「はあぁっ<emoji=heart04>　先っぽで押し広げられてぇ……<emoji=heart04>　んっ、んんっ<emoji=heart04>」
line = "「はあぁっ<emoji=heart04>　先っぽで押し広げられてぇ……<emoji=heart04>　んっ、んんっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あっ――<emoji=heart04><emoji=heart04>」
line = "「あっ――<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「ふああぁ～～～っ<emoji=heart04><emoji=heart04>　おち○ぽ、中にきたぁ～～～っ<emoji=heart04><emoji=heart04>」
line = "「ふああぁ～～～っ<emoji=heart04><emoji=heart04>　おち○ぽ、中にきたぁ～～～っ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あっ、あっ、あんっ<emoji=heart04>　はあぁっ、んんっ……<emoji=heart04>　あっ、はぁっ、ふあぁっ<emoji=heart04>　んっ、あっ……はあぁっ、んあぁんっ……<emoji=heart04>　あっ、あっ、ふあぁっ<emoji=heart04>　はあぁんっ……<emoji=heart04>」
line = "「あっ、あっ、あんっ<emoji=heart04>　はあぁっ、んんっ……<emoji=heart04>　あっ、はぁっ、ふあぁっ<emoji=heart04>　んっ、あっ……はあぁっ、んあぁんっ……<emoji=heart04>　あっ、あっ、ふあぁっ<emoji=heart04>　はあぁんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「待ち侘びてた発情期おま○こが絡みついちゃう<emoji=heart04>　あっ、あっ、あんっ……<emoji=heart04>　はぁっ、はぁっ、ふぅっ<emoji=heart04>　んっ、あっ、あっ……ふあぁんっ<emoji=heart04>」
line = "「待ち侘びてた発情期おま○こが絡みついちゃう<emoji=heart04>　あっ、あっ、あんっ……<emoji=heart04>　はぁっ、はぁっ、ふぅっ<emoji=heart04>　んっ、あっ、あっ……ふあぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あっ、あっ、んあぁっ<emoji=heart04>　効くぅ<emoji=heart04>　んっ、んっ、ふああぁっ……<emoji=heart04>　おま○こ気持ちいぃ<emoji=heart04>　あっ、あっ、はあぁっ<emoji=heart04>　んあぁんっ……<emoji=heart04>」
line = "「あっ、あっ、んあぁっ<emoji=heart04>　効くぅ<emoji=heart04>　んっ、んっ、ふああぁっ……<emoji=heart04>　おま○こ気持ちいぃ<emoji=heart04>　あっ、あっ、はあぁっ<emoji=heart04>　んあぁんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 快楽のままに甘い嬌声をあげる蘭美。
line = "快楽のままに甘い嬌声をあげる蘭美。"

[[dialogue]]
speaker = "unk"
# 声が大きいから抑えてと、俺が慌てていると――
line = "声が大きいから抑えてと、俺が慌てていると――"

[[dialogue]]
speaker = "蘭美"
# 「大丈夫よっ<emoji=heart04>　あっ、あっ、あんっ<emoji=heart04>　さっき言った隠蔽星術で、声も周りに聞こえないようになってるからぁっ<emoji=heart04>　あっ、あっ、はあぁんっ<emoji=heart04>」
line = "「大丈夫よっ<emoji=heart04>　あっ、あっ、あんっ<emoji=heart04>　さっき言った隠蔽星術で、声も周りに聞こえないようになってるからぁっ<emoji=heart04>　あっ、あっ、はあぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「貴方も興奮したら、遠慮せずに声出していいのよっ<emoji=heart04>　んっ、あっ、あっ<emoji=heart04>　はぁっ、ふぅっ……ふあぁっ<emoji=heart04>」
line = "「貴方も興奮したら、遠慮せずに声出していいのよっ<emoji=heart04>　んっ、あっ、あっ<emoji=heart04>　はぁっ、ふぅっ……ふあぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「はあぁっ<emoji=heart04>　んっ、ふぅっ、んうぅっ……<emoji=heart04>　はぁっ、あっ、ふうぅっ……<emoji=heart04>　はぁっ、はぁっ、んあぁっ……<emoji=heart04>　ふぅっ、ふぅっ、んうぅっ<emoji=heart04>　あっ、あっ、ふあぁんっ……<emoji=heart04>」
line = "「はあぁっ<emoji=heart04>　んっ、ふぅっ、んうぅっ……<emoji=heart04>　はぁっ、あっ、ふうぅっ……<emoji=heart04>　はぁっ、はぁっ、んあぁっ……<emoji=heart04>　ふぅっ、ふぅっ、んうぅっ<emoji=heart04>　あっ、あっ、ふあぁんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「……もしかして、初めての青姦で興奮してる？」
line = "「……もしかして、初めての青姦で興奮してる？」"

[[dialogue]]
speaker = "蘭美"
# 「んっ<emoji=heart04>　そんなわけないじゃないっ<emoji=heart04>　はぁっ、はぁっ、ふうぅっ……<emoji=heart04>」
line = "「んっ<emoji=heart04>　そんなわけないじゃないっ<emoji=heart04>　はぁっ、はぁっ、ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「これは発情期で感度が上がっちゃってるせいよっ<emoji=heart04>　あっ、あっ、あんっ<emoji=heart04>　はぁっ、はぁっ、んあぁんっ……<emoji=heart04>」
line = "「これは発情期で感度が上がっちゃってるせいよっ<emoji=heart04>　あっ、あっ、あんっ<emoji=heart04>　はぁっ、はぁっ、んあぁんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# と、その時だった。
line = "と、その時だった。"

[[dialogue]]
speaker = "女子生徒Ａ"
# 「――ねぇ、教室まで行くなら、ここ通った方が早くない？」
line = "「――ねぇ、教室まで行くなら、ここ通った方が早くない？」"

[[dialogue]]
speaker = "女子生徒Ｂ"
# 「確かに、近道かも！　そうしよっか」
line = "「確かに、近道かも！　そうしよっか」"

[[dialogue]]
speaker = "蘭美"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "unk"
# なんと、女子生徒２人が近くを通りかかる。
line = "なんと、女子生徒２人が近くを通りかかる。"

[[dialogue]]
speaker = "unk"
# 俺は思わずドキッとするが、
line = "俺は思わずドキッとするが、"

[[dialogue]]
speaker = "蘭美"
# 「っ……<emoji=heart04>　んっ……！　ふうぅっ……<emoji=heart04>」
line = "「っ……<emoji=heart04>　んっ……！　ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 蘭美のおま○こが、きゅうきゅう反応してペニスを締め付けてくる。
line = "蘭美のおま○こが、きゅうきゅう反応してペニスを締め付けてくる。"

[[dialogue]]
speaker = "女子生徒Ａ"
# 「部活終わったし、この後どこかに寄ってく？」
line = "「部活終わったし、この後どこかに寄ってく？」"

[[dialogue]]
speaker = "蘭美"
# 「あっ、あっ、あんっ<emoji=heart04>」
line = "「あっ、あっ、あんっ<emoji=heart04>」"

[[dialogue]]
speaker = "女子生徒Ｂ"
# 「お腹減ったし、カフェテリアで何か食べたいかも～」
line = "「お腹減ったし、カフェテリアで何か食べたいかも～」"

[[dialogue]]
speaker = "蘭美"
# 「はあぁっ、ふあぁっ……<emoji=heart04>　んっ、あっ、あっ、はあぁんっ……<emoji=heart04>」
line = "「はあぁっ、ふあぁっ……<emoji=heart04>　んっ、あっ、あっ、はあぁんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 女子生徒たちは蘭美の大きな喘ぎ声に気づくことなく、通り過ぎて行った。
line = "女子生徒たちは蘭美の大きな喘ぎ声に気づくことなく、通り過ぎて行った。"

[[dialogue]]
speaker = "蘭美"
# 「はぁっ、はぁっ<emoji=heart04>　んっ……ふうぅっ……<emoji=heart04>」
line = "「はぁっ、はぁっ<emoji=heart04>　んっ……ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「――ね？　大丈夫だったでしょっ……<emoji=heart04>」
line = "「――ね？　大丈夫だったでしょっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「蘭美、意外とＭっ気があるよね」
line = "「蘭美、意外とＭっ気があるよね」"

[[dialogue]]
speaker = "蘭美"
# 「んっ<emoji=heart04>　なにを言ってるのっ……<emoji=heart04>　あっ、あっ<emoji=heart04>　違うからっ……<emoji=heart04>　はぁっ、はぁっ、ふうぅっ……<emoji=heart04>　あっ、あっ、んあぁっ……<emoji=heart04>」
line = "「んっ<emoji=heart04>　なにを言ってるのっ……<emoji=heart04>　あっ、あっ<emoji=heart04>　違うからっ……<emoji=heart04>　はぁっ、はぁっ、ふうぅっ……<emoji=heart04>　あっ、あっ、んあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「――生徒が近くを通ったのに興奮してたって？　んっ、あっ、あっ<emoji=heart04>　ふあぁっ……<emoji=heart04>」
line = "「――生徒が近くを通ったのに興奮してたって？　んっ、あっ、あっ<emoji=heart04>　ふあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「違うわよっ……<emoji=heart04>　私は自分の星術でバレないってわかってたものっ。あっ、あっ、あんっ<emoji=heart04>　はぁっ、はぁっ、ふうぅっ……<emoji=heart04>」
line = "「違うわよっ……<emoji=heart04>　私は自分の星術でバレないってわかってたものっ。あっ、あっ、あんっ<emoji=heart04>　はぁっ、はぁっ、ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「そういう会長こそ、腰を振るの止めなかったじゃないっ<emoji=heart04>　あっ、あっ、あんっ……<emoji=heart04>　興奮してたんじゃないの？　んっ、あっ、あっ……<emoji=heart04>」
line = "「そういう会長こそ、腰を振るの止めなかったじゃないっ<emoji=heart04>　あっ、あっ、あんっ……<emoji=heart04>　興奮してたんじゃないの？　んっ、あっ、あっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「んっ<emoji=heart04>　なに？　――素直じゃないメイドにはお仕置きだって？　あっ、あっ、ふあぁっ……<emoji=heart04>」
line = "「んっ<emoji=heart04>　なに？　――素直じゃないメイドにはお仕置きだって？　あっ、あっ、ふあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「それでっ、一体どうする気なのかしらっ<emoji=heart04>　はぁっ、はぁっ、ふうぅっ……<emoji=heart04>」
line = "「それでっ、一体どうする気なのかしらっ<emoji=heart04>　はぁっ、はぁっ、ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「――激しくしちゃうの？　んっ……<emoji=heart04>　ふふっ、別にいいわよ<emoji=heart04>」
line = "「――激しくしちゃうの？　んっ……<emoji=heart04>　ふふっ、別にいいわよ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「この私をわからせてみなさいっ<emoji=heart04>」
line = "「この私をわからせてみなさいっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あっ―――<emoji=heart04><emoji=heart04>　ふあああぁぁ～～～っ<emoji=heart04><emoji=heart04>　激しいピストンきたぁっ<emoji=heart04>」
line = "「あっ―――<emoji=heart04><emoji=heart04>　ふあああぁぁ～～～っ<emoji=heart04><emoji=heart04>　激しいピストンきたぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あっ、あっ、あっ、あんっ<emoji=heart04>　あっ、あっ、あっ、ふああぁっ<emoji=heart04>　んっ、んっ、んっ、はあぁっ<emoji=heart04>　はぁっ、はぁっ、はぁ、んああぁっ<emoji=heart04>　あっ、あっ、あっ、ふああぁんっ<emoji=heart04>」
line = "「あっ、あっ、あっ、あんっ<emoji=heart04>　あっ、あっ、あっ、ふああぁっ<emoji=heart04>　んっ、んっ、んっ、はあぁっ<emoji=heart04>　はぁっ、はぁっ、はぁ、んああぁっ<emoji=heart04>　あっ、あっ、あっ、ふああぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「ふぅっ、ふぅっ、んあぁっ<emoji=heart04>　おま○この奥に当たってるぅっ<emoji=heart04>　んっ、あっ、あっ、すごっ<emoji=heart04>　あっ、あっ、あっ、ふああぁっ<emoji=heart04>」
line = "「ふぅっ、ふぅっ、んあぁっ<emoji=heart04>　おま○この奥に当たってるぅっ<emoji=heart04>　んっ、あっ、あっ、すごっ<emoji=heart04>　あっ、あっ、あっ、ふああぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「おち○ぽ気持ちいい<emoji=heart04>　んっ、あっ、あっ、んああぁっ<emoji=heart04>　あっ、あっ、あっ、奥、いいのぉっ<emoji=heart04>　はあぁっ<emoji=heart04>　はぁっ、はぁっ、あっ、ふああぁんっ<emoji=heart04>」
line = "「おち○ぽ気持ちいい<emoji=heart04>　んっ、あっ、あっ、んああぁっ<emoji=heart04>　あっ、あっ、あっ、奥、いいのぉっ<emoji=heart04>　はあぁっ<emoji=heart04>　はぁっ、はぁっ、あっ、ふああぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「激しいセックス好きぃ<emoji=heart04>　あっ、あっ、あっ、んああぁっ<emoji=heart04>　んっ、んっ、んうぅっ<emoji=heart04>　あっ、あっ、あっ、ふああぁんっ<emoji=heart04>」
line = "「激しいセックス好きぃ<emoji=heart04>　あっ、あっ、あっ、んああぁっ<emoji=heart04>　んっ、んっ、んうぅっ<emoji=heart04>　あっ、あっ、あっ、ふああぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「んっ、もっとぉ<emoji=heart04>　あっ、そこそこ、んっ<emoji=heart04>　あっ、あっ、はあぁっ、いいっ<emoji=heart04>　あっ、あっ、あっ、んああぁっ<emoji=heart04>」
line = "「んっ、もっとぉ<emoji=heart04>　あっ、そこそこ、んっ<emoji=heart04>　あっ、あっ、はあぁっ、いいっ<emoji=heart04>　あっ、あっ、あっ、んああぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「奥っ<emoji=heart04>　もっとおち○ぽで突いてぇ<emoji=heart04>　あっ、あっ、あんっ<emoji=heart04>　はあぁっ、あっ、あっ、気持ちいいっ<emoji=heart04>　んっ、あっ、あっ、ふあぁっ<emoji=heart04>　あっ、あっ、あっ、はああぁんっ<emoji=heart04>」
line = "「奥っ<emoji=heart04>　もっとおち○ぽで突いてぇ<emoji=heart04>　あっ、あっ、あんっ<emoji=heart04>　はあぁっ、あっ、あっ、気持ちいいっ<emoji=heart04>　んっ、あっ、あっ、ふあぁっ<emoji=heart04>　あっ、あっ、あっ、はああぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺がもうイキそうだ、と口にすると――
line = "俺がもうイキそうだ、と口にすると――"

[[dialogue]]
speaker = "蘭美"
# 「んっ、私も気持ちいいの登ってきてるから、一緒にぃ<emoji=heart04>　あっ、あっ、あっ、ふああぁっ<emoji=heart04>」
line = "「んっ、私も気持ちいいの登ってきてるから、一緒にぃ<emoji=heart04>　あっ、あっ、あっ、ふああぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「射精前の種付けピストン、すごいぃ<emoji=heart04>　あっ、あっ、あっ、んああぁっ<emoji=heart04>　あっ、あっ、あっ、ふああぁっ<emoji=heart04>」
line = "「射精前の種付けピストン、すごいぃ<emoji=heart04>　あっ、あっ、あっ、んああぁっ<emoji=heart04>　あっ、あっ、あっ、ふああぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あっ、あっ、あっ、私ももうイク<emoji=heart04>　イっちゃう<emoji=heart04>」
line = "「あっ、あっ、あっ、私ももうイク<emoji=heart04>　イっちゃう<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あっ、あっ、あっ、はああぁっ<emoji=heart04>　おち○ぽ膨らんできた<emoji=heart04>　きて、きてきてっ<emoji=heart04>」
line = "「あっ、あっ、あっ、はああぁっ<emoji=heart04>　おち○ぽ膨らんできた<emoji=heart04>　きて、きてきてっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あっあっあっあっ<emoji=heart04><emoji=heart04>　私もイク、イクイクイク――」
line = "「あっあっあっあっ<emoji=heart04><emoji=heart04>　私もイク、イクイクイク――」"

[[dialogue]]
speaker = "蘭美"
# 「イックぅぅぅーーーーーーーーーっ<emoji=heart04><emoji=heart04><emoji=heart04>　ふあああぁぁぁ～～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「イックぅぅぅーーーーーーーーーっ<emoji=heart04><emoji=heart04><emoji=heart04>　ふあああぁぁぁ～～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「精液、中にいっぱいきてるぅっ………<emoji=heart04>　はあぁっ……<emoji=heart04>　熱いぃ……<emoji=heart04>」
line = "「精液、中にいっぱいきてるぅっ………<emoji=heart04>　はあぁっ……<emoji=heart04>　熱いぃ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「腰がガクガク震えちゃうっ……<emoji=heart04>　んっ……ふうぅっ……<emoji=heart04>」
line = "「腰がガクガク震えちゃうっ……<emoji=heart04>　んっ……ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あんっ……<emoji=heart04>　おち○ぽ抜けちゃう……<emoji=heart04>」
line = "「あんっ……<emoji=heart04>　おち○ぽ抜けちゃう……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」
line = "「はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「ん……ふふっ……いつもよりいっぱい出したわね<emoji=heart04>　青姦エッチ、そんなに興奮したの……？」
line = "「ん……ふふっ……いつもよりいっぱい出したわね<emoji=heart04>　青姦エッチ、そんなに興奮したの……？」"

[[dialogue]]
speaker = "蘭美"
# 「私……？　私は別に普通よ。発情期の症状が出ちゃっただけだもの……」
line = "「私……？　私は別に普通よ。発情期の症状が出ちゃっただけだもの……」"

[[dialogue]]
speaker = "蘭美"
# 「でも――」
line = "「でも――」"

[[dialogue]]
speaker = "蘭美"
# 「また外で症状が出ちゃうことは、あるかもしれないし……」
line = "「また外で症状が出ちゃうことは、あるかもしれないし……」"

[[dialogue]]
speaker = "蘭美"
# 「その時は仕方ないわよね……？」
line = "「その時は仕方ないわよね……？」"

[[dialogue]]
speaker = "蘭美"
# 「体調を整えるのも、仕事のうちだもの<emoji=heart04>」
line = "「体調を整えるのも、仕事のうちだもの<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「――さて、スッキリしたことだし、後片付けしたら、お互い仕事に戻りましょうか」
line = "「――さて、スッキリしたことだし、後片付けしたら、お互い仕事に戻りましょうか」"

[[dialogue]]
speaker = "蘭美"
# 「だけど、その前に……」
line = "「だけど、その前に……」"

[[dialogue]]
speaker = "蘭美"
# 「会長。いつも付き合ってくれて、ありがとう」
line = "「会長。いつも付き合ってくれて、ありがとう」"

[[dialogue]]
speaker = "蘭美"
# 「好きよ……ちゅっ<emoji=heart04>」
line = "「好きよ……ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そう言って、キスしてくる彼女に、俺もキスで返して応えるのだった――
line = "そう言って、キスしてくる彼女に、俺もキスで返して応えるのだった――"
