[[dialogue]]
speaker = "unk"
# 第４話,リーナだけを見て,P
line = "第４話,リーナだけを見て,P"

[[dialogue]]
speaker = "unk"
# リーナが話があるというので、サーシャさんたちと離れて席に着く。
line = "リーナが話があるというので、サーシャさんたちと離れて席に着く。"

[[dialogue]]
speaker = "リーナ"
# 「あのね、あのね……リーナはお兄ちゃんが大好き」
line = "「あのね、あのね……リーナはお兄ちゃんが大好き」"

[[dialogue]]
speaker = "リーナ"
# 「でもね、それだけじゃないの……お兄ちゃんのこと考えてると苦しいの」
line = "「でもね、それだけじゃないの……お兄ちゃんのこと考えてると苦しいの」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃんが知らない人と話してるとモヤモヤして、リーナのいないところで楽しそうにしてるの考えたら、すっごく胸が苦しくなる」
line = "「お兄ちゃんが知らない人と話してるとモヤモヤして、リーナのいないところで楽しそうにしてるの考えたら、すっごく胸が苦しくなる」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃん……リーナ、おかしくなっちゃったのかな……？」
line = "「お兄ちゃん……リーナ、おかしくなっちゃったのかな……？」"

[[dialogue]]
speaker = "リーナ"
# 「……お兄ちゃん？　難しい顔してどうしたの？」
line = "「……お兄ちゃん？　難しい顔してどうしたの？」"

[[dialogue]]
speaker = "unk"
# ……おかしくなんかない
line = "……おかしくなんかない"

[[dialogue]]
speaker = "unk"
# 絞り出した言葉は、当たり障りのないものだったけど、本心でもあった。
line = "絞り出した言葉は、当たり障りのないものだったけど、本心でもあった。"

[[dialogue]]
speaker = "unk"
# 俺だって考えたことはある。もしリーナが大きくなって、俺と違う人と幸せになったら、祝福できるだろうか、と。
line = "俺だって考えたことはある。もしリーナが大きくなって、俺と違う人と幸せになったら、祝福できるだろうか、と。"

[[dialogue]]
speaker = "unk"
# 俺も同じ気持ちだよ
line = "俺も同じ気持ちだよ"

[[dialogue]]
speaker = "リーナ"
# 「……そうなの？」
line = "「……そうなの？」"

[[dialogue]]
speaker = "unk"
# リーナには笑っていて欲しいし、リーナを守りたいと思っている。でもそこには俺も一緒にいないとイヤだ。
line = "リーナには笑っていて欲しいし、リーナを守りたいと思っている。でもそこには俺も一緒にいないとイヤだ。"

[[dialogue]]
speaker = "unk"
# それは、俺がお兄ちゃんだからじゃなくて──
line = "それは、俺がお兄ちゃんだからじゃなくて──"

[[dialogue]]
speaker = "unk"
# 俺もリーナが大好きだから
line = "俺もリーナが大好きだから"

[[dialogue]]
speaker = "リーナ"
# 「ほんと？　じゃあ、もうリーナの知らない人とお話したりしない？　リーナのいないところで女の人に会ったりしない？」
line = "「ほんと？　じゃあ、もうリーナの知らない人とお話したりしない？　リーナのいないところで女の人に会ったりしない？」"

[[dialogue]]
speaker = "リーナ"
# 「……それはムリ？　なんでぇ……？」
line = "「……それはムリ？　なんでぇ……？」"

[[dialogue]]
speaker = "リーナ"
# 「……リーナだってコラプサーのみんなと仲良くしちゃダメって言われたら困る？　それは……う～～～ん」
line = "「……リーナだってコラプサーのみんなと仲良くしちゃダメって言われたら困る？　それは……う～～～ん」"

[[dialogue]]
speaker = "リーナ"
# 「困るかな……困らないような……いや困るかも……？」
line = "「困るかな……困らないような……いや困るかも……？」"

[[dialogue]]
speaker = "リーナ"
# 「じゃあ、カヤちゃんやアイリーンちゃんだったら？　それはヤダ！」
line = "「じゃあ、カヤちゃんやアイリーンちゃんだったら？　それはヤダ！」"

[[dialogue]]
speaker = "リーナ"
# 「リーナ、お兄ちゃんを困らせるようなこと言ってたんだね……ごめんね、お兄ちゃん。リーナ、悪い子になっちゃった……」
line = "「リーナ、お兄ちゃんを困らせるようなこと言ってたんだね……ごめんね、お兄ちゃん。リーナ、悪い子になっちゃった……」"

[[dialogue]]
speaker = "unk"
# リーナが俺を慕ってくれるのは嬉しいけど、だからといって束縛し合うのはよくない。
line = "リーナが俺を慕ってくれるのは嬉しいけど、だからといって束縛し合うのはよくない。"

[[dialogue]]
speaker = "リーナ"
# 「でも、リーナの苦しいのはどうすればいいの？　どうすれば苦しくなくなるの？」
line = "「でも、リーナの苦しいのはどうすればいいの？　どうすれば苦しくなくなるの？」"

[[dialogue]]
speaker = "unk"
# それは……
line = "それは……"

[[dialogue]]
speaker = "サーシャ"
# 「それはお姉ちゃんが答えましょう～」
line = "「それはお姉ちゃんが答えましょう～」"

[[dialogue]]
speaker = "ソフィア"
# 「姉さん、何やってるんですか！？」
line = "「姉さん、何やってるんですか！？」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふっ。ちょっと心配だったから、お話聞かせてもらったわ～」
line = "「ふふっ。ちょっと心配だったから、お話聞かせてもらったわ～」"

[[dialogue]]
speaker = "サーシャ"
# 「リーナちゃん？　リーナちゃんは大好きなお兄ちゃんが誰かにとられないか不安なのよね？」
line = "「リーナちゃん？　リーナちゃんは大好きなお兄ちゃんが誰かにとられないか不安なのよね？」"

[[dialogue]]
speaker = "リーナ"
# 「…………うん」
line = "「…………うん」"

[[dialogue]]
speaker = "サーシャ"
# 「そうね、すごく分かるわ。素敵なお兄ちゃんだものね」
line = "「そうね、すごく分かるわ。素敵なお兄ちゃんだものね」"

[[dialogue]]
speaker = "サーシャ"
# 「そういうときはね、たくさんお話するの。お兄ちゃんがリーナちゃんのお兄ちゃんだって、安心できるまで」
line = "「そういうときはね、たくさんお話するの。お兄ちゃんがリーナちゃんのお兄ちゃんだって、安心できるまで」"

[[dialogue]]
speaker = "サーシャ"
# 「これは私が反省しなきゃなんだけど、私も言葉が足りなくて、ソフィを心配させてしまったから」
line = "「これは私が反省しなきゃなんだけど、私も言葉が足りなくて、ソフィを心配させてしまったから」"

[[dialogue]]
speaker = "サーシャ"
# 「でも、お兄ちゃんなら大丈夫。ちゃんとリーナちゃんと向き合ってくれるもの」
line = "「でも、お兄ちゃんなら大丈夫。ちゃんとリーナちゃんと向き合ってくれるもの」"

[[dialogue]]
speaker = "サーシャ"
# 「だから、リーナちゃんはお兄ちゃんといっぱい遊んで、いっぱいお話しましょう。そうすれば、会えないときも寂しくないわ」
line = "「だから、リーナちゃんはお兄ちゃんといっぱい遊んで、いっぱいお話しましょう。そうすれば、会えないときも寂しくないわ」"

[[dialogue]]
speaker = "リーナ"
# 「ほんと？」
line = "「ほんと？」"

[[dialogue]]
speaker = "サーシャ"
# 「本当よ。ね、お兄ちゃん？」
line = "「本当よ。ね、お兄ちゃん？」"

[[dialogue]]
speaker = "unk"
# はい！
line = "はい！"

[[dialogue]]
speaker = "リーナ"
# 「じゃあ、今日はいっぱい遊ぼうね、お兄ちゃん！」
line = "「じゃあ、今日はいっぱい遊ぼうね、お兄ちゃん！」"

[[dialogue]]
speaker = "リーナ"
# 「あ、そうだ、パフェ！」
line = "「あ、そうだ、パフェ！」"

[[dialogue]]
speaker = "unk"
# リーナと話していたら、パフェがテーブルの上に置いたままになっていたのをすっかり忘れていた。
line = "リーナと話していたら、パフェがテーブルの上に置いたままになっていたのをすっかり忘れていた。"

[[dialogue]]
speaker = "リーナ"
# 「ん～～！　おいしい！　クリームたっぷりで幸せ～！」
line = "「ん～～！　おいしい！　クリームたっぷりで幸せ～！」"

[[dialogue]]
speaker = "unk"
# この暑さでもアイスが溶けないまま冷たさを保っていた。おかしいなと思っていると……
line = "この暑さでもアイスが溶けないまま冷たさを保っていた。おかしいなと思っていると……"

[[dialogue]]
speaker = "unk"
# サーシャさんが微笑みながら去っていくのが見えた。先輩の氷の星術のおかげだったようだ。
line = "サーシャさんが微笑みながら去っていくのが見えた。先輩の氷の星術のおかげだったようだ。"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃん、あ～～ん……ほら、お口あけて。リーナ言ったでしょ。ふたりで食べようって」
line = "「お兄ちゃん、あ～～ん……ほら、お口あけて。リーナ言ったでしょ。ふたりで食べようって」"

[[dialogue]]
speaker = "リーナ"
# 「はい、あ～～ん」
line = "「はい、あ～～ん」"

[[dialogue]]
speaker = "リーナ"
# 「ふふっ、おいしい？　ならよかった。お兄ちゃんが嬉しいとリーナも嬉しいっ」
line = "「ふふっ、おいしい？　ならよかった。お兄ちゃんが嬉しいとリーナも嬉しいっ」"

[[dialogue]]
speaker = "unk"
# リーナもあーん
line = "リーナもあーん"

[[dialogue]]
speaker = "リーナ"
# 「え、リーナも！？　あ～～ん……うん、おいしい……」
line = "「え、リーナも！？　あ～～ん……うん、おいしい……」"

[[dialogue]]
speaker = "リーナ"
# 「おいしいけど、恥ずかしいよぉ～！　ドキドキするよぉ～！」
line = "「おいしいけど、恥ずかしいよぉ～！　ドキドキするよぉ～！」"

[[dialogue]]
speaker = "リーナ"
# 「もう、次はリーナの番だからね！」
line = "「もう、次はリーナの番だからね！」"

[[dialogue]]
speaker = "unk"
# それから、２人で巨大なパフェをたっぷり食べさせあいっこしたのだった。
line = "それから、２人で巨大なパフェをたっぷり食べさせあいっこしたのだった。"

[[dialogue]]
speaker = "リーナ"
# 「今日は楽しかったっ！」
line = "「今日は楽しかったっ！」"

[[dialogue]]
speaker = "リーナ"
# 「パフェもおいしかったし、プールも可愛かったね」
line = "「パフェもおいしかったし、プールも可愛かったね」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃん、泳ぐの得意でびっくりしちゃった。リーナはあんまり泳ぐの得意じゃないから、今度教えてね」
line = "「お兄ちゃん、泳ぐの得意でびっくりしちゃった。リーナはあんまり泳ぐの得意じゃないから、今度教えてね」"

[[dialogue]]
speaker = "リーナ"
# 「……ねぇ、お兄ちゃん」
line = "「……ねぇ、お兄ちゃん」"

[[dialogue]]
speaker = "リーナ"
# 「またリーナがモヤモヤしたり、苦しくなったら、一緒に遊んでくれる？　お話、聞いてくれる？」
line = "「またリーナがモヤモヤしたり、苦しくなったら、一緒に遊んでくれる？　お話、聞いてくれる？」"

[[dialogue]]
speaker = "unk"
# もちろん！
line = "もちろん！"

[[dialogue]]
speaker = "リーナ"
# 「ふふっ、ありがとう」
line = "「ふふっ、ありがとう」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃん、大好きっ！」
line = "「お兄ちゃん、大好きっ！」"

[[dialogue]]
speaker = "unk"
# 俺がお兄ちゃんであろうとそうでなくとも、ずっとリーナの傍にいたいと思うのだった。
line = "俺がお兄ちゃんであろうとそうでなくとも、ずっとリーナの傍にいたいと思うのだった。"
