[[dialogue]]
speaker = "unk"
# 第３話,舞亜の特製手料理,P
line = "第３話,舞亜の特製手料理,P"

[[dialogue]]
speaker = "舞亜"
# 「ふ～んふふ～んふふ～ん♪」
line = "「ふ～んふふ～んふふ～ん♪」"

[[dialogue]]
speaker = "unk"
# 鼻歌を歌いながら、俺のために料理を作ってくれる舞亜。
line = "鼻歌を歌いながら、俺のために料理を作ってくれる舞亜。"

[[dialogue]]
speaker = "unk"
# いったいどんな料理を作ってくれるんだろう……？
line = "いったいどんな料理を作ってくれるんだろう……？"

[[dialogue]]
speaker = "舞亜"
# 「は～い、お待たせ。野菜たっぷりミネストローネと、卵たっぷりのオムライスだよ」
line = "「は～い、お待たせ。野菜たっぷりミネストローネと、卵たっぷりのオムライスだよ」"

[[dialogue]]
speaker = "unk"
# （思ってたより普通だ……！）
line = "（思ってたより普通だ……！）"

[[dialogue]]
speaker = "舞亜"
# 「あ～、思ったより普通だって顔してる。会長さんってば失礼なんだから」
line = "「あ～、思ったより普通だって顔してる。会長さんってば失礼なんだから」"

[[dialogue]]
speaker = "舞亜"
# 「はい、おまちどうさま。そうそう、オムライスにはケチャップでハートとメッセージ書かなきゃ。『Ｉ　Ｌｏｖｅ　Ｙｏｕ』……っと」
line = "「はい、おまちどうさま。そうそう、オムライスにはケチャップでハートとメッセージ書かなきゃ。『Ｉ　Ｌｏｖｅ　Ｙｏｕ』……っと」"

[[dialogue]]
speaker = "舞亜"
# 「あ、失敗しちゃった。なんか血塗れみたいだけど、食べたら同じだしいいよね。さ、召し上がれ」
line = "「あ、失敗しちゃった。なんか血塗れみたいだけど、食べたら同じだしいいよね。さ、召し上がれ」"

[[dialogue]]
speaker = "舞亜"
# 「……どう？　美味しい？」
line = "「……どう？　美味しい？」"

[[dialogue]]
speaker = "舞亜"
# 「……素材の味が活きてて美味しい？　そっか、会長さんの口に合って良かった」
line = "「……素材の味が活きてて美味しい？　そっか、会長さんの口に合って良かった」"

[[dialogue]]
speaker = "舞亜"
# 「料理できるって言った手前、微妙って言われたらどうしようって、内心緊張してたんだから。私の好みだと薄味になりがちだしね」
line = "「料理できるって言った手前、微妙って言われたらどうしようって、内心緊張してたんだから。私の好みだと薄味になりがちだしね」"

[[dialogue]]
speaker = "舞亜"
# 「でもオムライスはご飯が少ない……？　あ、バレたか。糖質抑えるために、ご飯が少ないんだよね」
line = "「でもオムライスはご飯が少ない……？　あ、バレたか。糖質抑えるために、ご飯が少ないんだよね」"

[[dialogue]]
speaker = "舞亜"
# 「卵たっぷりなんじゃなくて、ご飯２割、卵８割の詐欺オムライス。ま、でも味はいけるでしょ？　オムライス失敗するとかっこ悪いから練習したもん」
line = "「卵たっぷりなんじゃなくて、ご飯２割、卵８割の詐欺オムライス。ま、でも味はいけるでしょ？　オムライス失敗するとかっこ悪いから練習したもん」"

[[dialogue]]
speaker = "unk"
# 俺のためにありがとう、舞亜
line = "俺のためにありがとう、舞亜"

[[dialogue]]
speaker = "舞亜"
# 「そうそう、そういう言葉が欲しかったの。トップスケーターとか世界一とか言われたって、私も女の子なんだから」
line = "「そうそう、そういう言葉が欲しかったの。トップスケーターとか世界一とか言われたって、私も女の子なんだから」"

[[dialogue]]
speaker = "舞亜"
# 「じゃ、あれやろうよ、あれ」
line = "「じゃ、あれやろうよ、あれ」"

[[dialogue]]
speaker = "舞亜"
# 「何かわからないって顔してるね。恋人同士で、食事中にやることと言えば決まってるでしょ？　あ～んだよ、あ～ん」
line = "「何かわからないって顔してるね。恋人同士で、食事中にやることと言えば決まってるでしょ？　あ～んだよ、あ～ん」"

[[dialogue]]
speaker = "舞亜"
# 「あ～んするために会長さんのおうちに来たまであるからね。それじゃいくよ」
line = "「あ～んするために会長さんのおうちに来たまであるからね。それじゃいくよ」"

[[dialogue]]
speaker = "舞亜"
# 「はい、あ～ん<emoji=heart04>」
line = "「はい、あ～ん<emoji=heart04>」"

[[dialogue]]
speaker = "舞亜"
# 「……美味しい？」
line = "「……美味しい？」"

[[dialogue]]
speaker = "unk"
# とっても美味しい
line = "とっても美味しい"

[[dialogue]]
speaker = "舞亜"
# 「ありがと。彼氏さんがそう言ってくれると、作った甲斐があるね」
line = "「ありがと。彼氏さんがそう言ってくれると、作った甲斐があるね」"

[[dialogue]]
speaker = "舞亜"
# 「じゃあ、会長さんからあーんってして？　あ～～んっ……うん、美味しい。作ったの私だけど♪」
line = "「じゃあ、会長さんからあーんってして？　あ～～んっ……うん、美味しい。作ったの私だけど♪」"

[[dialogue]]
speaker = "舞亜"
# 「それにしても……フィギュアの大会で優勝する自分は想像できても、好きな人のためにご飯を作ってあげる自分なんて、少し前じゃ想像できなかったなぁ……」
line = "「それにしても……フィギュアの大会で優勝する自分は想像できても、好きな人のためにご飯を作ってあげる自分なんて、少し前じゃ想像できなかったなぁ……」"

[[dialogue]]
speaker = "舞亜"
# 「ちゃんと料理ができる子で良かった。ふふふ」
line = "「ちゃんと料理ができる子で良かった。ふふふ」"

[[dialogue]]
speaker = "舞亜"
# 「ところで会長さんにプレゼントがあるんだ。はい」
line = "「ところで会長さんにプレゼントがあるんだ。はい」"

[[dialogue]]
speaker = "unk"
# これは……『阿』と『吽』のＴシャツ……？
line = "これは……『阿』と『吽』のＴシャツ……？"

[[dialogue]]
speaker = "舞亜"
# 「うん、白地のシャツに『<ruby=あ>阿</ruby>』と『<ruby=うん>吽</ruby>』の文字がどーんって書いてあって、かっこいいよね」
line = "「うん、白地のシャツに『<ruby>阿<rt>あ</rt></ruby>』と『<ruby>吽<rt>うん</rt></ruby>』の文字がどーんって書いてあって、かっこいいよね」"

[[dialogue]]
speaker = "舞亜"
# 「会長さんが『阿』を着て、私が『吽』を着たら、これ以上ないペアルックだよ」
line = "「会長さんが『阿』を着て、私が『吽』を着たら、これ以上ないペアルックだよ」"

[[dialogue]]
speaker = "unk"
# （独特なセンスだ……！）
line = "（独特なセンスだ……！）"

[[dialogue]]
speaker = "舞亜"
# 「でも……ごめんね？　恋人がいるって言っちゃったから、会長さんに迷惑かけちゃうかも」
line = "「でも……ごめんね？　恋人がいるって言っちゃったから、会長さんに迷惑かけちゃうかも」"

[[dialogue]]
speaker = "舞亜"
# 「私は慣れっこだけど、会長さんに取材やマスコミが来ちゃうかも。変なおっかけも付くかもしれない」
line = "「私は慣れっこだけど、会長さんに取材やマスコミが来ちゃうかも。変なおっかけも付くかもしれない」"

[[dialogue]]
speaker = "舞亜"
# 「もし会長さんの邪魔になるなら、その時は──」
line = "「もし会長さんの邪魔になるなら、その時は──」"

[[dialogue]]
speaker = "unk"
# それくらいどんと来いだよ
line = "それくらいどんと来いだよ"

[[dialogue]]
speaker = "舞亜"
# 「……モンスターに比べれば大したことない？　さすが会長さん、頼もしいね」
line = "「……モンスターに比べれば大したことない？　さすが会長さん、頼もしいね」"

[[dialogue]]
speaker = "舞亜"
# 「そうだね、星徒会長っていえば世界最強の星騎士なんだから、それくらいどうってことないよね」
line = "「そうだね、星徒会長っていえば世界最強の星騎士なんだから、それくらいどうってことないよね」"

[[dialogue]]
speaker = "舞亜"
# 「そう言えるのかっこいいな。もっと早く恋人がいるって言えばよかったかも」
line = "「そう言えるのかっこいいな。もっと早く恋人がいるって言えばよかったかも」"

[[dialogue]]
speaker = "舞亜"
# 「さっき言いかけたことは忘れて。会長さんには余計な話だったから」
line = "「さっき言いかけたことは忘れて。会長さんには余計な話だったから」"

[[dialogue]]
speaker = "舞亜"
# 「あ、そうだ。最後に食後のデザート、いる？」
line = "「あ、そうだ。最後に食後のデザート、いる？」"

[[dialogue]]
speaker = "unk"
# カロリーは控えてるんじゃ？
line = "カロリーは控えてるんじゃ？"

[[dialogue]]
speaker = "舞亜"
# 「大丈夫、ゼロカロリーだから。いくら食べても太らない、とびっきり甘いデザートだよ」
line = "「大丈夫、ゼロカロリーだから。いくら食べても太らない、とびっきり甘いデザートだよ」"

[[dialogue]]
speaker = "舞亜"
# 「そんな魔法みたいなデザートあるのかって？　あるんだな、これが。じゃあいくよ──」
line = "「そんな魔法みたいなデザートあるのかって？　あるんだな、これが。じゃあいくよ──」"

[[dialogue]]
speaker = "舞亜"
# 「ちゅっ<emoji=heart04>」
line = "「ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "舞亜"
# 「んちゅっ<emoji=heart04>　ちゅ……ちゅ……ちゅ、ちゅっ<emoji=heart04>」
line = "「んちゅっ<emoji=heart04>　ちゅ……ちゅ……ちゅ、ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 何度もキスを重ね、舞亜のふわふわの唇を味わう。
line = "何度もキスを重ね、舞亜のふわふわの唇を味わう。"

[[dialogue]]
speaker = "unk"
# 食後のキスは、甘酸っぱいケチャップの味がした。
line = "食後のキスは、甘酸っぱいケチャップの味がした。"
