[[dialogue]]
speaker = "unk"
# 第３話,いつか新魔法を叶える為に,P
line = "第３話,いつか新魔法を叶える為に,P"

[[dialogue]]
speaker = "unk"
# その日はアステラが発生し、俺はシズハの力を借りて、共に出撃していた。
line = "その日はアステラが発生し、俺はシズハの力を借りて、共に出撃していた。"

[[dialogue]]
speaker = "unk"
# モンスターはＳＳ級と強敵だったが、ヴィクトリアフォームの力によって、無事撃破に成功した。
line = "モンスターはＳＳ級と強敵だったが、ヴィクトリアフォームの力によって、無事撃破に成功した。"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「――よし♪　ディーちゃん、やったね♪」
line = "「――よし♪　ディーちゃん、やったね♪」"

[[dialogue]]
speaker = "ディーラック"
# 「はぁ～、終わった終わった。今日はもう働かないからね～、ボク」
line = "「はぁ～、終わった終わった。今日はもう働かないからね～、ボク」"

[[dialogue]]
speaker = "イニシュ"
# 「シズハ。原理はわかりませんが、あなたは星力ではなく、『魔力』を使って戦っているのですね」
line = "「シズハ。原理はわかりませんが、あなたは星力ではなく、『魔力』を使って戦っているのですね」"

[[dialogue]]
speaker = "ミネコ"
# 「いや～、面白い子だとは思ってたけどさ。シズハは星騎士としても面白い能力を持ってるんだね～」
line = "「いや～、面白い子だとは思ってたけどさ。シズハは星騎士としても面白い能力を持ってるんだね～」"

[[dialogue]]
speaker = "unk"
# たまたまマッドスタンパーで一緒に遊んでいた為、共に出撃したミネコとイニシュの２人が言う。
line = "たまたまマッドスタンパーで一緒に遊んでいた為、共に出撃したミネコとイニシュの２人が言う。"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「はい。あの……詳しくは話せないんですけど……『魔法』を使えるのには事情があって……」
line = "「はい。あの……詳しくは話せないんですけど……『魔法』を使えるのには事情があって……」"

[[dialogue]]
speaker = "ミネコ"
# 「ああ、いいよいいよ。特殊って言うなら、私だって似たようなもんだし♪」
line = "「ああ、いいよいいよ。特殊って言うなら、私だって似たようなもんだし♪」"

[[dialogue]]
speaker = "イニシュ"
# 「……私も深くは聞きません。シズハが話したいと思った時に、話してくれれば構いません」
line = "「……私も深くは聞きません。シズハが話したいと思った時に、話してくれれば構いません」"

[[dialogue]]
speaker = "イニシュ"
# 「私は長い時を生きる魔女ですから。友達として、何年でも待てます」
line = "「私は長い時を生きる魔女ですから。友達として、何年でも待てます」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「ミネコ先輩、イニシュさん……ありがとうございます♪」
line = "「ミネコ先輩、イニシュさん……ありがとうございます♪」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「――って、会長！　よく見たら、手を怪我してない？」
line = "「――って、会長！　よく見たら、手を怪我してない？」"

[[dialogue]]
speaker = "unk"
# あっ、本当だ
line = "あっ、本当だ"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「ちょっと待ってて！　救急箱を持ってくるから――」
line = "「ちょっと待ってて！　救急箱を持ってくるから――」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「これでよし、っと……」
line = "「これでよし、っと……」"

[[dialogue]]
speaker = "unk"
# シズハ、いつからこんな処置できるように？
line = "シズハ、いつからこんな処置できるように？"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「えへへっ、実はね、トマルくんや、学園の先生に教えてもらったんだ♪」
line = "「えへへっ、実はね、トマルくんや、学園の先生に教えてもらったんだ♪」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「前に会長にも話したでしょ？　私がいつか『新魔法』を作りたいって話」
line = "「前に会長にも話したでしょ？　私がいつか『新魔法』を作りたいって話」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「それで、人の病気を治す新魔法を目指すなら、ちゃんと医学の知識も学んでおかなきゃって思って」
line = "「それで、人の病気を治す新魔法を目指すなら、ちゃんと医学の知識も学んでおかなきゃって思って」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「だから最近は、図書館で医学の本を借りて勉強してるんだ」
line = "「だから最近は、図書館で医学の本を借りて勉強してるんだ」"

[[dialogue]]
speaker = "イニシュ"
# 「シズハが『新魔法』を……？」
line = "「シズハが『新魔法』を……？」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「あっ、はい。実は私……今の医学ではまだ治せないような、そんな病気でも治療できる魔法を使えるようになりたいんです」
line = "「あっ、はい。実は私……今の医学ではまだ治せないような、そんな病気でも治療できる魔法を使えるようになりたいんです」"

[[dialogue]]
speaker = "イニシュ"
# 「どうしてそのような考えに至ったのですか？」
line = "「どうしてそのような考えに至ったのですか？」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「私、少し前までは病気で、小さい頃からずっと入院生活を送っていて……」
line = "「私、少し前までは病気で、小さい頃からずっと入院生活を送っていて……」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「今は運よく治って、こうして学園に通えてますけど……その頃は、自分の明るい未来なんて、全然見えなくて」
line = "「今は運よく治って、こうして学園に通えてますけど……その頃は、自分の明るい未来なんて、全然見えなくて」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「それでも、両親や病院の先生、看護師さん、ディーちゃん、それにお姉ちゃん――」
line = "「それでも、両親や病院の先生、看護師さん、ディーちゃん、それにお姉ちゃん――」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「周りのみんなが、私に『生きる力』をくれたんです」
line = "「周りのみんなが、私に『生きる力』をくれたんです」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「だから今度は私が……同じように未来が見えなくなっている人たちに、生きる力をあげたいんです」
line = "「だから今度は私が……同じように未来が見えなくなっている人たちに、生きる力をあげたいんです」"

[[dialogue]]
speaker = "ミネコ"
# 「なるほど。それがキミの心に輝く『宝石』ってわけだね」
line = "「なるほど。それがキミの心に輝く『宝石』ってわけだね」"

[[dialogue]]
speaker = "イニシュ"
# 「でしたら、魔法のことで何か知りたいことがあれば、いつでも相談して下さい」
line = "「でしたら、魔法のことで何か知りたいことがあれば、いつでも相談して下さい」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「え？　イニシュさん、いいんですか？」
line = "「え？　イニシュさん、いいんですか？」"

[[dialogue]]
speaker = "イニシュ"
# 「私もまだ、失った記憶をすべて取り戻したわけではありません。なので、どこまで教えられるかはわかりませんが……」
line = "「私もまだ、失った記憶をすべて取り戻したわけではありません。なので、どこまで教えられるかはわかりませんが……」"

[[dialogue]]
speaker = "イニシュ"
# 「友達として、力になります」
line = "「友達として、力になります」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「ありがとう、イニシュさん♪」
line = "「ありがとう、イニシュさん♪」"

[[dialogue]]
speaker = "unk"
# 医学の勉強なら、俺も協力するぞ
line = "医学の勉強なら、俺も協力するぞ"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「会長も、ありがとう♪」
line = "「会長も、ありがとう♪」"

[[dialogue]]
speaker = "ディーラック"
# （ネビュラの魔女に、シズハちゃんの『聖杯』やボクのことを知られるのは、あまりよくないとは思うけど……）
line = "（ネビュラの魔女に、シズハちゃんの『聖杯』やボクのことを知られるのは、あまりよくないとは思うけど……）"

[[dialogue]]
speaker = "ディーラック"
# （まぁ、このイニシュとかいうのは……一旦見て見ぬフリで保留にしといてやろうかな……）
line = "（まぁ、このイニシュとかいうのは……一旦見て見ぬフリで保留にしといてやろうかな……）"

[[dialogue]]
speaker = "ミネコ"
# 「あっ、魔法を使えることについては詳しく聞かないって言ったけど、代わりに教えて欲しいことがあってさ～」
line = "「あっ、魔法を使えることについては詳しく聞かないって言ったけど、代わりに教えて欲しいことがあってさ～」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「はい、なんでしょう？」
line = "「はい、なんでしょう？」"

[[dialogue]]
speaker = "ミネコ"
# 「シズハと会長って、付き合ってるんでしょ？　だったら、２人の関係がどこまで進んでるのかって情報が、私としては知りたいな～♪」
line = "「シズハと会長って、付き合ってるんでしょ？　だったら、２人の関係がどこまで進んでるのかって情報が、私としては知りたいな～♪」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「へ！？　な、なに言ってるんですか！？　先輩のバカバカ！」
line = "「へ！？　な、なに言ってるんですか！？　先輩のバカバカ！」"

[[dialogue]]
speaker = "ミネコ"
# 「ありゃ？　シズハってば、めっちゃ恥ずかしがってる～♪」
line = "「ありゃ？　シズハってば、めっちゃ恥ずかしがってる～♪」"

[[dialogue]]
speaker = "unk"
# 可愛いだろ？
line = "可愛いだろ？"

[[dialogue]]
speaker = "イニシュ"
# 「友達関係のことについては私もわかりますが、恋人関係については、私もよくわかりません」
line = "「友達関係のことについては私もわかりますが、恋人関係については、私もよくわかりません」"

[[dialogue]]
speaker = "イニシュ"
# 「シズハ。『男性とキスをする』というのは、どのような感覚なのでしょうか？」
line = "「シズハ。『男性とキスをする』というのは、どのような感覚なのでしょうか？」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「イニシュさんまで！？　ば、バカバカ！　そんな恥ずかしいこと、言えるわけないじゃないっ！」
line = "「イニシュさんまで！？　ば、バカバカ！　そんな恥ずかしいこと、言えるわけないじゃないっ！」"

[[dialogue]]
speaker = "ミネコ"
# 「ぷっ……あはははっ♪　じゃあさ、このあとみんなでラーメンでも食べに行かない？　そこでゆっくりと聞かせてよ～♪」
line = "「ぷっ……あはははっ♪　じゃあさ、このあとみんなでラーメンでも食べに行かない？　そこでゆっくりと聞かせてよ～♪」"

[[dialogue]]
speaker = "イニシュ"
# 「いいですね。この近くには、美味しい<ruby=とりぱいたん>鶏白湯</ruby>ラーメンの店、『<ruby=ラーメン>ＲＡＭＥＮ</ruby>　<ruby=トリスケ>ＴＯＲＩＳＵＫＥ</ruby>』があります」
line = "「いいですね。この近くには、美味しい<ruby>鶏白湯<rt>とりぱいたん</rt></ruby>ラーメンの店、『<ruby>ＲＡＭＥＮ<rt>ラーメン</rt></ruby>　<ruby>ＴＯＲＩＳＵＫＥ<rt>トリスケ</rt></ruby>』があります」"

[[dialogue]]
speaker = "ミネコ"
# 「おっ、さすがラーメン好きのイニシュ、詳しい～♪　ほらシズハ、元気にいけいけゴーゴーだよ♪」
line = "「おっ、さすがラーメン好きのイニシュ、詳しい～♪　ほらシズハ、元気にいけいけゴーゴーだよ♪」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「ちょっ、私の言葉を盗らないでください！　恋愛関係の話は、いけいけゴーゴーしませんから～～っ！」
line = "「ちょっ、私の言葉を盗らないでください！　恋愛関係の話は、いけいけゴーゴーしませんから～～っ！」"

[[dialogue]]
speaker = "unk"
# そうしてミネコに肩を組まれ、イニシュと共に半ば連行されるシズハ。
line = "そうしてミネコに肩を組まれ、イニシュと共に半ば連行されるシズハ。"

[[dialogue]]
speaker = "unk"
# その後――俺たちはラーメンを食べながら、たっぷりと恋愛話を聞かれることになるのだった。
line = "その後――俺たちはラーメンを食べながら、たっぷりと恋愛話を聞かれることになるのだった。"
