[[dialogue]]
speaker = "unk"
# 第１話,癒しのお散歩タイム,P
line = "第１話,癒しのお散歩タイム,P"

[[dialogue]]
speaker = "シアン"
# 「もごっ」
line = "「もごっ」"

[[dialogue]]
speaker = "unk"
# 学園に向かう道中、ホットドッグを頬張るシアン先輩とバッタリ出会った。
line = "学園に向かう道中、ホットドッグを頬張るシアン先輩とバッタリ出会った。"

[[dialogue]]
speaker = "unk"
# 目が合うと、バツが悪そうに咀嚼し、一気に飲み込む。
line = "目が合うと、バツが悪そうに咀嚼し、一気に飲み込む。"

[[dialogue]]
speaker = "シアン"
# 「もぐもぐ……よっ、会長さん」
line = "「もぐもぐ……よっ、会長さん」"

[[dialogue]]
speaker = "シアン"
# 「ちょっと時間が空いたから飯食いながら散歩してたとこだ。お行儀が悪くて、すまねえな」
line = "「ちょっと時間が空いたから飯食いながら散歩してたとこだ。お行儀が悪くて、すまねえな」"

[[dialogue]]
speaker = "シアン"
# 「あー……もしかして会長さんも腹減ってるか？」
line = "「あー……もしかして会長さんも腹減ってるか？」"

[[dialogue]]
speaker = "シアン"
# 「遠慮すんなよ。腹減ってたから、うっかり買いすぎちまったけど、こんなには食えねえからな」
line = "「遠慮すんなよ。腹減ってたから、うっかり買いすぎちまったけど、こんなには食えねえからな」"

[[dialogue]]
speaker = "シアン"
# 「アメリカンドッグだろ、タコスだろ、ケバブだろ……いろいろあるぜ。どれがいい？」
line = "「アメリカンドッグだろ、タコスだろ、ケバブだろ……いろいろあるぜ。どれがいい？」"

[[dialogue]]
speaker = "unk"
# ジャンクフードばかりですね
line = "ジャンクフードばかりですね"

[[dialogue]]
speaker = "シアン"
# 「ああ、こういう手っ取り早く食えるのが、あたしの主食でな」
line = "「ああ、こういう手っ取り早く食えるのが、あたしの主食でな」"

[[dialogue]]
speaker = "シアン"
# 「慌ただしい仕事だからよ。仕事柄、片手で手早く食べられるのを口にする機会が多くてさ」
line = "「慌ただしい仕事だからよ。仕事柄、片手で手早く食べられるのを口にする機会が多くてさ」"

[[dialogue]]
speaker = "シアン"
# 「刑事ドラマで張り込みの<ruby=デカ>刑事</ruby>があんパン食ってるシーンあるだろ。アレみたいな感じだ。手早く、効率的に栄養補給できるのがベストなんだ」
line = "「刑事ドラマで張り込みの<ruby>刑事<rt>デカ</rt></ruby>があんパン食ってるシーンあるだろ。アレみたいな感じだ。手早く、効率的に栄養補給できるのがベストなんだ」"

[[dialogue]]
speaker = "シアン"
# 「久しぶりに流星市国に戻ってきたら、新しい店が増えてて驚いたぜ。これならバリエーションにも困らねえ。大助かりだ」
line = "「久しぶりに流星市国に戻ってきたら、新しい店が増えてて驚いたぜ。これならバリエーションにも困らねえ。大助かりだ」"

[[dialogue]]
speaker = "シアン"
# 「ジャンクフードばかりも体には良かねえんだろうけど……職業病みたいなもんかな。別に不便に感じちゃいねえしさ」
line = "「ジャンクフードばかりも体には良かねえんだろうけど……職業病みたいなもんかな。別に不便に感じちゃいねえしさ」"

[[dialogue]]
speaker = "シアン"
# 「ま、会長さんが素敵なディナーにでも誘ってくれるんなら、話は別だけどな、はは」
line = "「ま、会長さんが素敵なディナーにでも誘ってくれるんなら、話は別だけどな、はは」"

[[dialogue]]
speaker = "unk"
# 今度、ゆっくりご飯食べに行きましょう
line = "今度、ゆっくりご飯食べに行きましょう"

[[dialogue]]
speaker = "シアン"
# 「……は？　マジで言ってんのか」
line = "「……は？　マジで言ってんのか」"

[[dialogue]]
speaker = "シアン"
# 「まあ……言っちまった手前、断りゃしねえけどよ。いつ予定が空くかもわからねえからな」
line = "「まあ……言っちまった手前、断りゃしねえけどよ。いつ予定が空くかもわからねえからな」"

[[dialogue]]
speaker = "シアン"
# 「任務は突然入るし、休暇申請なんて通った試しはねえし……公安に入ってから休みらしい休みも取っちゃいねえ」
line = "「任務は突然入るし、休暇申請なんて通った試しはねえし……公安に入ってから休みらしい休みも取っちゃいねえ」"

[[dialogue]]
speaker = "unk"
# ちゃんと休んでる人に心当たりが……
line = "ちゃんと休んでる人に心当たりが……"

[[dialogue]]
speaker = "unk"
# ブラック企業かな……？
line = "ブラック企業かな……？"

[[dialogue]]
speaker = "ネーゼマイン"
# 「てへぺろ☆」
line = "「てへぺろ☆」"

[[dialogue]]
speaker = "シアン"
# 「なんか言いたそうな顔してんな……言いたいことはなんとなくわかるけどよ」
line = "「なんか言いたそうな顔してんな……言いたいことはなんとなくわかるけどよ」"

[[dialogue]]
speaker = "シアン"
# 「いや、言わなくていい。言葉にされると、あたしの心が折れちまうかもしんねえし」
line = "「いや、言わなくていい。言葉にされると、あたしの心が折れちまうかもしんねえし」"

[[dialogue]]
speaker = "シアン"
# 「ま、世界が平和になって、あたしも仕事を辞めて、落ち着いたらな。飯でもなんでも誘ってくれよ……もぐもぐ」
line = "「ま、世界が平和になって、あたしも仕事を辞めて、落ち着いたらな。飯でもなんでも誘ってくれよ……もぐもぐ」"

[[dialogue]]
speaker = "シアン"
# 「あー、美味かった。やっぱ、ここのホットドッグは絶品だな」
line = "「あー、美味かった。やっぱ、ここのホットドッグは絶品だな」"

[[dialogue]]
speaker = "unk"
# シアン先輩はホットドッグをたいらげると、唇の端についていたケチャップをぺろりと舐め取る。
line = "シアン先輩はホットドッグをたいらげると、唇の端についていたケチャップをぺろりと舐め取る。"

[[dialogue]]
speaker = "unk"
# せっかくの休憩なのにお邪魔じゃなかったです？
line = "せっかくの休憩なのにお邪魔じゃなかったです？"

[[dialogue]]
speaker = "シアン"
# 「はっ、邪魔だったら、端っから隠れてやり過ごしてるよ。そういうのは得意だからさ」
line = "「はっ、邪魔だったら、端っから隠れてやり過ごしてるよ。そういうのは得意だからさ」"

[[dialogue]]
speaker = "シアン"
# 「任務中は張り詰めっぱなしなんでな。こうやって、余計なこと考えずに、駄弁ってられる時間ってのは嫌いじゃねえんだ」
line = "「任務中は張り詰めっぱなしなんでな。こうやって、余計なこと考えずに、駄弁ってられる時間ってのは嫌いじゃねえんだ」"

[[dialogue]]
speaker = "シアン"
# 「束の間の平和を享受してる、って感じでさ。こういう時間を少しでも長く味わえるよう、あたしらは陰ながら頑張ってんだ……」
line = "「束の間の平和を享受してる、って感じでさ。こういう時間を少しでも長く味わえるよう、あたしらは陰ながら頑張ってんだ……」"

[[dialogue]]
speaker = "unk"
# 懐からケースを取り出すと、手慣れた仕草で白くて細長いスティックを咥えた。
line = "懐からケースを取り出すと、手慣れた仕草で白くて細長いスティックを咥えた。"

[[dialogue]]
speaker = "シアン"
# 「そういや、会長さんは、会ってすぐにあたしの素性に勘づいてたみたいだけど……どの辺で分かった？」
line = "「そういや、会長さんは、会ってすぐにあたしの素性に勘づいてたみたいだけど……どの辺で分かった？」"

[[dialogue]]
speaker = "unk"
# どの辺っていうか……雰囲気全般？
line = "どの辺っていうか……雰囲気全般？"

[[dialogue]]
speaker = "シアン"
# 「雰囲気、ねえ？　年上オーラが出ちまってんのかな……これでも上手いこと擬態してるつもりなんだけどよ」
line = "「雰囲気、ねえ？　年上オーラが出ちまってんのかな……これでも上手いこと擬態してるつもりなんだけどよ」"

[[dialogue]]
speaker = "シアン"
# 「……ちなみにだけど、あたしのコレはタバコじゃねえからな？　シガレットチョコだぞ」
line = "「……ちなみにだけど、あたしのコレはタバコじゃねえからな？　シガレットチョコだぞ」"

[[dialogue]]
speaker = "unk"
# チョコだったの！？
line = "チョコだったの！？"

[[dialogue]]
speaker = "シアン"
# 「当たり前だろ。あたしをなんだと思ってんだ」
line = "「当たり前だろ。あたしをなんだと思ってんだ」"

[[dialogue]]
speaker = "シアン"
# 「タバコなんて吸ってたら、臭いが体に染みついちまうだろ。任務に差し障りしかねえよ」
line = "「タバコなんて吸ってたら、臭いが体に染みついちまうだろ。任務に差し障りしかねえよ」"

[[dialogue]]
speaker = "シアン"
# 「口寂しいから咥えてるだけだ。食後のスイーツだよ」
line = "「口寂しいから咥えてるだけだ。食後のスイーツだよ」"

[[dialogue]]
speaker = "シアン"
# 「疑ってんのか？　嘘じゃねえから。食ってみろよ」
line = "「疑ってんのか？　嘘じゃねえから。食ってみろよ」"

[[dialogue]]
speaker = "シアン"
# 「……っと、案の定、呼び出しだ。悪ぃな、会長さん。いつかは豪華なディナーに行けるの、楽しみにしてるぜ」
line = "「……っと、案の定、呼び出しだ。悪ぃな、会長さん。いつかは豪華なディナーに行けるの、楽しみにしてるぜ」"

[[dialogue]]
speaker = "unk"
# 押し付けられ、無理やり口にねじこまれたシガレットは、確かに甘くて、ほろ苦いビターチョコだった。
line = "押し付けられ、無理やり口にねじこまれたシガレットは、確かに甘くて、ほろ苦いビターチョコだった。"
