[[dialogue]]
speaker = "unk"
# 第３話,２人の寮長,P
line = "第３話,２人の寮長,P"

[[dialogue]]
speaker = "unk"
# １ヶ月に１度開かれているという、新星寮と流星寮の寮長同士による定例会。俺は何故かその場に呼ばれていた――
line = "１ヶ月に１度開かれているという、新星寮と流星寮の寮長同士による定例会。俺は何故かその場に呼ばれていた――"

[[dialogue]]
speaker = "unk"
# お邪魔します、千園寺先輩
line = "お邪魔します、千園寺先輩"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「まあ、緋宮会長。我が流星寮へようこそですわ♪」
line = "「まあ、緋宮会長。我が流星寮へようこそですわ♪」"

[[dialogue]]
speaker = "マハムート"
# 「あら、会長。わざわざ流星寮まで何しに来たのかしら？」
line = "「あら、会長。わざわざ流星寮まで何しに来たのかしら？」"

[[dialogue]]
speaker = "unk"
# いや、マムが来いって言ったんですよね！？
line = "いや、マムが来いって言ったんですよね！？"

[[dialogue]]
speaker = "マハムート"
# 「ふっ……冗談よ。貴方も星徒会長になったのだから、定例会の内容くらいは知っておくべきだと思ってね」
line = "「ふっ……冗談よ。貴方も星徒会長になったのだから、定例会の内容くらいは知っておくべきだと思ってね」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「おーっほっほっほ！　そういうことでしたら、この私が教えて差し上げますわ！　この『定例寮議会』は学園の規則によって、月一の開催が義務付けられておりますの」
line = "「おーっほっほっほ！　そういうことでしたら、この私が教えて差し上げますわ！　この『定例寮議会』は学園の規則によって、月一の開催が義務付けられておりますの」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「議題は主に、互いの寮内で起こったトラブル事例や、有益なアイデアの情報交換、学園対抗杯の経過報告等ですわね」
line = "「議題は主に、互いの寮内で起こったトラブル事例や、有益なアイデアの情報交換、学園対抗杯の経過報告等ですわね」"

[[dialogue]]
speaker = "マハムート"
# 「はいこれ、あなたの分の資料。会長としての意見も聞きたいから、見ているだけじゃなく、ちゃんと話し合いに参加なさい」
line = "「はいこれ、あなたの分の資料。会長としての意見も聞きたいから、見ているだけじゃなく、ちゃんと話し合いに参加なさい」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「今回の話し合いはこんなところかしら。緋宮会長のご意見、参考になりましたわ。流石は私の同志ですわね」
line = "「今回の話し合いはこんなところかしら。緋宮会長のご意見、参考になりましたわ。流石は私の同志ですわね」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「流星学園に思わずスカウトしたくなってしまいますわ。緋宮会長がその気なら、千園寺家の力で本当に移籍させることも可能でしてよ？」
line = "「流星学園に思わずスカウトしたくなってしまいますわ。緋宮会長がその気なら、千園寺家の力で本当に移籍させることも可能でしてよ？」"

[[dialogue]]
speaker = "マハムート"
# 「私の前で堂々と引き抜きしてんじゃないわよ、ツインドリル」
line = "「私の前で堂々と引き抜きしてんじゃないわよ、ツインドリル」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「あら、嫉妬ですの、リトルマム？　ごめんあそばせ、いつの間にか貴方よりも私の方が緋宮会長と仲良くなってしまって……おほほほ！」
line = "「あら、嫉妬ですの、リトルマム？　ごめんあそばせ、いつの間にか貴方よりも私の方が緋宮会長と仲良くなってしまって……おほほほ！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「せめてものお詫びに、この自慢の流星寮ロビーで、常備している高級なお紅茶とお菓子を食べて、好きなだけくつろいで行って下さいましね、マム♪」
line = "「せめてものお詫びに、この自慢の流星寮ロビーで、常備している高級なお紅茶とお菓子を食べて、好きなだけくつろいで行って下さいましね、マム♪」"

[[dialogue]]
speaker = "マハムート"
# 「ふ、ふふっ……設備格差に物を言わせて煽るとは、いい度胸してるじゃないヒルディオーネ……！　最近、少し調子に乗ってるんじゃないかしら？」
line = "「ふ、ふふっ……設備格差に物を言わせて煽るとは、いい度胸してるじゃないヒルディオーネ……！　最近、少し調子に乗ってるんじゃないかしら？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ええ、そうですの！　このところ私、絶好調ですのよ♪　やはりトレーニング……いえ、趣味仲間が出来るのは、良いものですわね～。ねぇ、そうでしょう、緋宮会長？」
line = "「ええ、そうですの！　このところ私、絶好調ですのよ♪　やはりトレーニング……いえ、趣味仲間が出来るのは、良いものですわね～。ねぇ、そうでしょう、緋宮会長？」"

[[dialogue]]
speaker = "マハムート"
# 「趣味仲間ぁ……？　どういうことかしら、会長？　私、そんな話聞いてないんだけど？」
line = "「趣味仲間ぁ……？　どういうことかしら、会長？　私、そんな話聞いてないんだけど？」"

[[dialogue]]
speaker = "unk"
# いや、それには話せない事情があって……
line = "いや、それには話せない事情があって……"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「し～、ですわよ？　約束ですものね♪」
line = "「し～、ですわよ？　約束ですものね♪」"

[[dialogue]]
speaker = "マハムート"
# 「これは会長……後でじっくり聞き出す必要がありそうね」
line = "「これは会長……後でじっくり聞き出す必要がありそうね」"

[[dialogue]]
speaker = "unk"
# （状況が詰んでる……！）
line = "（状況が詰んでる……！）"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ふふん、設備が悔しかったら、今年こそ学園対抗杯で勝ってみせることですわね、マム」
line = "「ふふん、設備が悔しかったら、今年こそ学園対抗杯で勝ってみせることですわね、マム」"

[[dialogue]]
speaker = "マハムート"
# 「個人戦で私に１度でも勝ったことがない癖に、よくそこまで意気揚々と吠えられるものだわ」
line = "「個人戦で私に１度でも勝ったことがない癖に、よくそこまで意気揚々と吠えられるものだわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「はぁ？　それは貴方がなかなか私との対戦に応じないからで、今やれば勝てますけれど？」
line = "「はぁ？　それは貴方がなかなか私との対戦に応じないからで、今やれば勝てますけれど？」"

[[dialogue]]
speaker = "マハムート"
# 「あら、いいのかしら？　仲のよろしい会長の前で、負け姿を晒すことになっても」
line = "「あら、いいのかしら？　仲のよろしい会長の前で、負け姿を晒すことになっても」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「おーっほっほっほ！　別に、一向に構いませんわよ！」
line = "「おーっほっほっほ！　別に、一向に構いませんわよ！」"

[[dialogue]]
speaker = "マハムート"
# 「なんですって……？」
line = "「なんですって……？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「あいにく、その程度のことを遠慮するような仲ではございませんの♪」
line = "「あいにく、その程度のことを遠慮するような仲ではございませんの♪」"

[[dialogue]]
speaker = "マハムート"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "マハムート"
# 「……そういえば、さっきから気になっていたんだけど、仲が良いと言ってる割に貴方――」
line = "「……そういえば、さっきから気になっていたんだけど、仲が良いと言ってる割に貴方――」"

[[dialogue]]
speaker = "マハムート"
# 「会長から、愛称で呼ばれてないわね？」
line = "「会長から、愛称で呼ばれてないわね？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「え」
line = "「え」"

[[dialogue]]
speaker = "マハムート"
# 「仲がいいならそれくらいは普通でしょう？　例えば私は『マム』と呼ばれているわ」
line = "「仲がいいならそれくらいは普通でしょう？　例えば私は『マム』と呼ばれているわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「そ、それは別に、こだわるところでは……」
line = "「そ、それは別に、こだわるところでは……」"

[[dialogue]]
speaker = "マハムート"
# 「ヒルディオーネはひょっとして、知らないのかしら？　上流階級と違って、庶民の学生間では――」
line = "「ヒルディオーネはひょっとして、知らないのかしら？　上流階級と違って、庶民の学生間では――」"

[[dialogue]]
speaker = "マハムート"
# 「親愛を示す証として、愛称で呼び合う暗黙のルールが存在するのよ？」
line = "「親愛を示す証として、愛称で呼び合う暗黙のルールが存在するのよ？」"

[[dialogue]]
speaker = "unk"
# （それは大げさというより嘘の類では！？）
line = "（それは大げさというより嘘の類では！？）"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ですわっ！？　そんな……ああいえ、もちろん知ってましたわよ！？」
line = "「ですわっ！？　そんな……ああいえ、もちろん知ってましたわよ！？」"

[[dialogue]]
speaker = "unk"
# 先輩！？　あっけなく騙されないで……！
line = "先輩！？　あっけなく騙されないで……！"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「さあ、緋宮会長……じゃなくて貴方！　親愛の証として、私をヒルディーという愛称で呼ぶことを許しますわ！」
line = "「さあ、緋宮会長……じゃなくて貴方！　親愛の証として、私をヒルディーという愛称で呼ぶことを許しますわ！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「そ、それとも、私と仲良くすることが嫌だとでも？」
line = "「そ、それとも、私と仲良くすることが嫌だとでも？」"

[[dialogue]]
speaker = "unk"
# ええと、じゃあ……ヒルディー先輩
line = "ええと、じゃあ……ヒルディー先輩"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「あ……ふ、ふふ……下の名前呼び、良いですわね……！　貴方との絆を確かに感じますわ！」
line = "「あ……ふ、ふふ……下の名前呼び、良いですわね……！　貴方との絆を確かに感じますわ！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「どうですの、マム。これで私も――」
line = "「どうですの、マム。これで私も――」"

[[dialogue]]
speaker = "マハムート"
# 「まあ、嘘なんだけど」
line = "「まあ、嘘なんだけど」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「は？」
line = "「は？」"

[[dialogue]]
speaker = "マハムート"
# 「面白いものが見れたから、今日のところは許してあげるわヒルディー」
line = "「面白いものが見れたから、今日のところは許してあげるわヒルディー」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「あ……貴方って人は……！」
line = "「あ……貴方って人は……！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「また私を騙しましたわね、マムぅぅぅ――――――っ！！！」
line = "「また私を騙しましたわね、マムぅぅぅ――――――っ！！！」"

[[dialogue]]
speaker = "unk"
# つい吹き出してしまいながら、この２人は何だかんだ仲がいいよな、と改めて思うのだった。
line = "つい吹き出してしまいながら、この２人は何だかんだ仲がいいよな、と改めて思うのだった。"
