[[dialogue]]
speaker = "unk"
# 紅明と恋人になり、しばらく経ったある日のこと。
line = "紅明と恋人になり、しばらく経ったある日のこと。"

[[dialogue]]
speaker = "unk"
# 星徒会の残業が終わり、帰路に着こうとしていると──
line = "星徒会の残業が終わり、帰路に着こうとしていると──"

[[dialogue]]
speaker = "紅明"
# 「ダーリン、一緒に帰ろうぜ！！！」
line = "「ダーリン、一緒に帰ろうぜ！！！」"

[[dialogue]]
speaker = "クロト"
# 「うおっ！？　ビックリした！　学園に残ってたのか？」
line = "「うおっ！？　ビックリした！　学園に残ってたのか？」"

[[dialogue]]
speaker = "紅明"
# 「うしし♪　家に帰ってたんだけど、ダーリンの仕事終わったってチャット見て、迎えに来ちゃった☆」
line = "「うしし♪　家に帰ってたんだけど、ダーリンの仕事終わったってチャット見て、迎えに来ちゃった☆」"

[[dialogue]]
speaker = "紅明"
# 「……何でって、そりゃあ愛ですよ、愛♪　出来る恋人っしょ？」
line = "「……何でって、そりゃあ愛ですよ、愛♪　出来る恋人っしょ？」"

[[dialogue]]
speaker = "紅明"
# 「それに、ダーリンひょっとしたらお疲れかな～って思ってさ」
line = "「それに、ダーリンひょっとしたらお疲れかな～って思ってさ」"

[[dialogue]]
speaker = "紅明"
# 「……で、どうする？」
line = "「……で、どうする？」"

[[dialogue]]
speaker = "紅明"
# 「おっぱい、飲む？」
line = "「おっぱい、飲む？」"

[[dialogue]]
speaker = "unk"
# ──そうして、俺は紅明の部屋に招かれると、彼女のベッドに腰掛けた。
line = "──そうして、俺は紅明の部屋に招かれると、彼女のベッドに腰掛けた。"

[[dialogue]]
speaker = "紅明"
# 「あんっ……ダーリン、キスしたいの？<emoji=heart04>　ちゅっ、んちゅっ……んっ、ダーリンの舌、エッチぃ……ちゅむっ、ちゅれろっ、ちゅうっ……ちゅれるっ、ちゅぷぷっ、ちゅぱっ<emoji=heart04>」
line = "「あんっ……ダーリン、キスしたいの？<emoji=heart04>　ちゅっ、んちゅっ……んっ、ダーリンの舌、エッチぃ……ちゅむっ、ちゅれろっ、ちゅうっ……ちゅれるっ、ちゅぷぷっ、ちゅぱっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んちゅっ、ちゅぱっ<emoji=heart04>　ぷはぁ……はぁ……それじゃあダーリン、横になって？　アタシのおっぱいで癒して、元気にしたげる♪」
line = "「んちゅっ、ちゅぱっ<emoji=heart04>　ぷはぁ……はぁ……それじゃあダーリン、横になって？　アタシのおっぱいで癒して、元気にしたげる♪」"

[[dialogue]]
speaker = "紅明"
# 「んモー<emoji=heart04>　ダーリンってば、こっちの服でしたいだなんて、エッチなんだから♪」
line = "「んモー<emoji=heart04>　ダーリンってば、こっちの服でしたいだなんて、エッチなんだから♪」"

[[dialogue]]
speaker = "クロト"
# 「相変わらず紅明のおっぱい、凄いボリュームだ……」
line = "「相変わらず紅明のおっぱい、凄いボリュームだ……」"

[[dialogue]]
speaker = "紅明"
# 「バスト１００センチのＩカップだぜ☆　でも、そう言うダーリンのおち○ぽだって、凄いから……！」
line = "「バスト１００センチのＩカップだぜ☆　でも、そう言うダーリンのおち○ぽだって、凄いから……！」"

[[dialogue]]
speaker = "紅明"
# 「大きくて逞しくて、手に収まりきらないおち○ぽ……はあぁ……イケメン過ぎるでしょ<emoji=heart04>　こんなの女の子に見せたら、誰だってメロメロになっちゃうやつだし<emoji=heart04>」
line = "「大きくて逞しくて、手に収まりきらないおち○ぽ……はあぁ……イケメン過ぎるでしょ<emoji=heart04>　こんなの女の子に見せたら、誰だってメロメロになっちゃうやつだし<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あんっ<emoji=heart04>　ふふっ、我慢できなくなっちゃった……？　いいよ、ダーリン、おっぱい好きなだけ吸って♪」
line = "「あんっ<emoji=heart04>　ふふっ、我慢できなくなっちゃった……？　いいよ、ダーリン、おっぱい好きなだけ吸って♪」"

[[dialogue]]
speaker = "紅明"
# 「んっ……アタシのおっぱいは、ダーリン専用だから<emoji=heart04>　あぁんっ、乳首、舌で転がされてぇ……はあぁっ、乳首勃起しちゃう……<emoji=heart04>」
line = "「んっ……アタシのおっぱいは、ダーリン専用だから<emoji=heart04>　あぁんっ、乳首、舌で転がされてぇ……はあぁっ、乳首勃起しちゃう……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あっ、あっ<emoji=heart04>　勃起乳首、吸われてるぅ……はぁんっ<emoji=heart04>　ちゅぱちゅぱされるの、気持ちいいっ。んあぁっ、ダーリンのこと愛おしいって気持ちが溢れてきちゃう<emoji=heart04>」
line = "「あっ、あっ<emoji=heart04>　勃起乳首、吸われてるぅ……はぁんっ<emoji=heart04>　ちゅぱちゅぱされるの、気持ちいいっ。んあぁっ、ダーリンのこと愛おしいって気持ちが溢れてきちゃう<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「っ……紅明にいつも癒して貰ってるお礼がしたくて、おっぱいを気持ちよくする方法、勉強してきたんだ」
line = "「っ……紅明にいつも癒して貰ってるお礼がしたくて、おっぱいを気持ちよくする方法、勉強してきたんだ」"

[[dialogue]]
speaker = "紅明"
# 「あぁんっ……勉強って、ふふっ<emoji=heart04>　なにそれ～？　ダーリンを癒してるのは、アタシが好きでやってることだから……んっ、あんっ<emoji=heart04>　全然気にしなくてもいいのに<emoji=heart04>」
line = "「あぁんっ……勉強って、ふふっ<emoji=heart04>　なにそれ～？　ダーリンを癒してるのは、アタシが好きでやってることだから……んっ、あんっ<emoji=heart04>　全然気にしなくてもいいのに<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んっ……でも嬉しくって、乳首敏感になっちゃう<emoji=heart04>　はぁんっ……ダーリンに乳首吸われて、感じちゃう……あんっ、ふあぁっ<emoji=heart04>」
line = "「んっ……でも嬉しくって、乳首敏感になっちゃう<emoji=heart04>　はぁんっ……ダーリンに乳首吸われて、感じちゃう……あんっ、ふあぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んっ<emoji=heart04>　ダーリンのおち○ぽ、興奮でガッチガチぃ<emoji=heart04>　我慢汁が出てて、凄いオスの匂い……あぁんっ<emoji=heart04>　フェロモンむんむんで、アタシも興奮してきちゃう<emoji=heart04>」
line = "「んっ<emoji=heart04>　ダーリンのおち○ぽ、興奮でガッチガチぃ<emoji=heart04>　我慢汁が出てて、凄いオスの匂い……あぁんっ<emoji=heart04>　フェロモンむんむんで、アタシも興奮してきちゃう<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「はあぁ……ダーリンのおち○ぽも、アタシの手で癒してあげるね？<emoji=heart04>　愛情込めてご奉仕するから、いっぱい気持ち良くなって♪」
line = "「はあぁ……ダーリンのおち○ぽも、アタシの手で癒してあげるね？<emoji=heart04>　愛情込めてご奉仕するから、いっぱい気持ち良くなって♪」"

[[dialogue]]
speaker = "紅明"
# 「んっ……ゆっくり行くね<emoji=heart04>　シコシコ……シコシコ♪　すりすり……すりすり♪」
line = "「んっ……ゆっくり行くね<emoji=heart04>　シコシコ……シコシコ♪　すりすり……すりすり♪」"

[[dialogue]]
speaker = "紅明"
# 「カリ首のところ、気持ちいい？<emoji=heart04>　カリカリ、シコシコ……あっ……ふふっ……おち○ぽ、ビクビクって喜んでる♪」
line = "「カリ首のところ、気持ちいい？<emoji=heart04>　カリカリ、シコシコ……あっ……ふふっ……おち○ぽ、ビクビクって喜んでる♪」"

[[dialogue]]
speaker = "紅明"
# 「亀頭も、撫で撫でしちゃう……<emoji=heart04>　あんっ、エッチなお汁いっぱい出て……アタシで気持ち良くなってくれてるの、嬉しい♪」
line = "「亀頭も、撫で撫でしちゃう……<emoji=heart04>　あんっ、エッチなお汁いっぱい出て……アタシで気持ち良くなってくれてるの、嬉しい♪」"

[[dialogue]]
speaker = "クロト"
# 「じゃあ、今度は俺からも……」
line = "「じゃあ、今度は俺からも……」"

[[dialogue]]
speaker = "紅明"
# 「えっ、ダーリン、何して……ふああっ！？」
line = "「えっ、ダーリン、何して……ふああっ！？」"

[[dialogue]]
speaker = "紅明"
# 「んうぅっ、んあぁぁぁっ<emoji=heart04><emoji=heart04>！？　乳首舐められただけで、クリ触られたみたいに、感じちゃうっ……<emoji=heart04>！」
line = "「んうぅっ、んあぁぁぁっ<emoji=heart04><emoji=heart04>！？　乳首舐められただけで、クリ触られたみたいに、感じちゃうっ……<emoji=heart04>！」"

[[dialogue]]
speaker = "紅明"
# 「はあぁんっ、おっぱいが３倍気持ちよくなる愛撫って、なにそれ……っ<emoji=heart04>　ふあぁっ、乳首気持ちいいっ<emoji=heart04>！　んくっ、はあぁっ……あんっ、んあぁっ……ふあぁぁんっ」
line = "「はあぁんっ、おっぱいが３倍気持ちよくなる愛撫って、なにそれ……っ<emoji=heart04>　ふあぁっ、乳首気持ちいいっ<emoji=heart04>！　んくっ、はあぁっ……あんっ、んあぁっ……ふあぁぁんっ」"

[[dialogue]]
speaker = "紅明"
# 「興奮して、はあぁっ、ダーリン<emoji=heart04>　出ちゃうっ、アタシ出ちゃうよぉ……！　ふあああ──<emoji=heart04><emoji=heart04>」
line = "「興奮して、はあぁっ、ダーリン<emoji=heart04>　出ちゃうっ、アタシ出ちゃうよぉ……！　ふあああ──<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「はああぁぁんっ<emoji=heart04>　母乳出ちゃうぅ<emoji=heart04>」
line = "「はああぁぁんっ<emoji=heart04>　母乳出ちゃうぅ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ふあああぁぁぁ……<emoji=heart04>　ダーリンのエッチな舌使いっ、凄く気持ち良くて……んっ、はぁぁ<emoji=heart04>　いつもよりいっぱい、母乳溢れてきちゃう<emoji=heart04>」
line = "「ふあああぁぁぁ……<emoji=heart04>　ダーリンのエッチな舌使いっ、凄く気持ち良くて……んっ、はぁぁ<emoji=heart04>　いつもよりいっぱい、母乳溢れてきちゃう<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あんっ、ダーリン、夢中になっておっぱい吸ってる<emoji=heart04>　んっ、はぁんっ<emoji=heart04><emoji=heart04>　アタシのミルク、美味しい……<emoji=heart04>？」
line = "「あんっ、ダーリン、夢中になっておっぱい吸ってる<emoji=heart04>　んっ、はぁんっ<emoji=heart04><emoji=heart04>　アタシのミルク、美味しい……<emoji=heart04>？」"

[[dialogue]]
speaker = "紅明"
# 「んああっ、そんないやらしく舌で弄っちゃダメぇっ……<emoji=heart04>！　はぁんっ、ふあぁっ……アタシの方がダーリンより、気持ち良くなっちゃうぅ……<emoji=heart04>！」
line = "「んああっ、そんないやらしく舌で弄っちゃダメぇっ……<emoji=heart04>！　はぁんっ、ふあぁっ……アタシの方がダーリンより、気持ち良くなっちゃうぅ……<emoji=heart04>！」"

[[dialogue]]
speaker = "クロト"
# 「妊娠してないのに、種族の体質で母乳が出ちゃうなんて……エッチだ」
line = "「妊娠してないのに、種族の体質で母乳が出ちゃうなんて……エッチだ」"

[[dialogue]]
speaker = "紅明"
# 「んモー<emoji=heart04>　ダーリンがエッチなお口で興奮させるからでしょ<emoji=heart04>？　あぁんっ、ダーリンがカウパーで、おち○ぽヌルヌルになってるのと、一緒だしぃ。ふあぁぁっ<emoji=heart04>」
line = "「んモー<emoji=heart04>　ダーリンがエッチなお口で興奮させるからでしょ<emoji=heart04>？　あぁんっ、ダーリンがカウパーで、おち○ぽヌルヌルになってるのと、一緒だしぃ。ふあぁぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「はぁんっ<emoji=heart04>　ダーリンのおち○ぽ、更に大きくなっちゃってるぅ……<emoji=heart04>　はあぁ……母乳の媚薬効果、効いてきたってことかな<emoji=heart04>？」
line = "「はぁんっ<emoji=heart04>　ダーリンのおち○ぽ、更に大きくなっちゃってるぅ……<emoji=heart04>　はあぁ……母乳の媚薬効果、効いてきたってことかな<emoji=heart04>？」"

[[dialogue]]
speaker = "紅明"
# 「ダーリンはアタシの手コキ、どう？　んっ……気持ちーい<emoji=heart04>？」
line = "「ダーリンはアタシの手コキ、どう？　んっ……気持ちーい<emoji=heart04>？」"

[[dialogue]]
speaker = "紅明"
# 「あんっ<emoji=heart04>　ダーリンが気持ち良くなってくれてると、アタシも嬉しい……♪　ダーリンが幸せだと……んっ、ふあぁっ……アタシも幸せだから♪」
line = "「あんっ<emoji=heart04>　ダーリンが気持ち良くなってくれてると、アタシも嬉しい……♪　ダーリンが幸せだと……んっ、ふあぁっ……アタシも幸せだから♪」"

[[dialogue]]
speaker = "紅明"
# 「体も心も楽にして、甘えちゃって、いいからね♪　ふうぅ……<emoji=heart04>　アタシがダーリンのこと、もっともっと、気持ち良くしたげるっ<emoji=heart04>」
line = "「体も心も楽にして、甘えちゃって、いいからね♪　ふうぅ……<emoji=heart04>　アタシがダーリンのこと、もっともっと、気持ち良くしたげるっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「──あっ、ふあああっ<emoji=heart04><emoji=heart04>！？　ダーリンの手がもう片方のおっぱいにぃ<emoji=heart04>！　んっ、触られただけなのに、気持ち良くて……頭の中、バチバチってしちゃうぅ<emoji=heart04><emoji=heart04>！」
line = "「──あっ、ふあああっ<emoji=heart04><emoji=heart04>！？　ダーリンの手がもう片方のおっぱいにぃ<emoji=heart04>！　んっ、触られただけなのに、気持ち良くて……頭の中、バチバチってしちゃうぅ<emoji=heart04><emoji=heart04>！」"

[[dialogue]]
speaker = "紅明"
# 「あぁんっ<emoji=heart04>　ダーリンの舌で、乳首優しくコリコリされるの……気持ちいいっ<emoji=heart04>　両方の乳首同時にするの、気持ちいいのぉっ<emoji=heart04>」
line = "「あぁんっ<emoji=heart04>　ダーリンの舌で、乳首優しくコリコリされるの……気持ちいいっ<emoji=heart04>　両方の乳首同時にするの、気持ちいいのぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んっ……なんだか、おっぱいマッサージ、されてるみたい<emoji=heart04>　はあぁんっ、ダーリン、もっとしてぇ……<emoji=heart04>！」
line = "「んっ……なんだか、おっぱいマッサージ、されてるみたい<emoji=heart04>　はあぁんっ、ダーリン、もっとしてぇ……<emoji=heart04>！」"

[[dialogue]]
speaker = "紅明"
# 「あんっ<emoji=heart04>　アタシもダーリンのこと、もっと気持ち良くするからっ<emoji=heart04>　ふあぁっ、はぁ<emoji=heart04>　ほらぁ、もっと気持ち良くなってぇ<emoji=heart04>！」
line = "「あんっ<emoji=heart04>　アタシもダーリンのこと、もっと気持ち良くするからっ<emoji=heart04>　ふあぁっ、はぁ<emoji=heart04>　ほらぁ、もっと気持ち良くなってぇ<emoji=heart04>！」"

[[dialogue]]
speaker = "紅明"
# 「はあっ、はあっ、んんっ……はぁん<emoji=heart04>　先走りでおち○ぽヌルヌルだから、大きく強めにシコシコするね……？　んんっ<emoji=heart04>」
line = "「はあっ、はあっ、んんっ……はぁん<emoji=heart04>　先走りでおち○ぽヌルヌルだから、大きく強めにシコシコするね……？　んんっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「これくらいの強さが、好き？　うん、分かるよっ<emoji=heart04>　はあぁっ……ダーリンのおち○ぽ、ドクドクってカウパー出して……反応してくれるからっ<emoji=heart04>」
line = "「これくらいの強さが、好き？　うん、分かるよっ<emoji=heart04>　はあぁっ……ダーリンのおち○ぽ、ドクドクってカウパー出して……反応してくれるからっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「カリ首こうやって……裏から刺激するのが、好きなんだよねっ？　シコシコ、シュッシュって……♪　シコシコ、シュッシュ♪　シコシコ、シュッシュ……♪」
line = "「カリ首こうやって……裏から刺激するのが、好きなんだよねっ？　シコシコ、シュッシュって……♪　シコシコ、シュッシュ♪　シコシコ、シュッシュ……♪」"

[[dialogue]]
speaker = "紅明"
# 「裏筋も撫でてあげるね<emoji=heart04>　すりすり、シュッシュ……♪　んっ<emoji=heart04>　腰が跳ねてる……っ。気持ちいいんだ♪　もっとこれ、してあげるね……♪」
line = "「裏筋も撫でてあげるね<emoji=heart04>　すりすり、シュッシュ……♪　んっ<emoji=heart04>　腰が跳ねてる……っ。気持ちいいんだ♪　もっとこれ、してあげるね……♪」"

[[dialogue]]
speaker = "紅明"
# 「亀頭もシュッシュしちゃう……<emoji=heart04>　カウパーでヌルヌルだから、痛くないっしょ？<emoji=heart04>　シコシコ、シュッシュ……♪　シコシコ、シュッシュ♪」
line = "「亀頭もシュッシュしちゃう……<emoji=heart04>　カウパーでヌルヌルだから、痛くないっしょ？<emoji=heart04>　シコシコ、シュッシュ……♪　シコシコ、シュッシュ♪」"

[[dialogue]]
speaker = "紅明"
# 「はあぁっ<emoji=heart04>　擦る度、カウパーが溢れて来て、凄いエッチ……♪」
line = "「はあぁっ<emoji=heart04>　擦る度、カウパーが溢れて来て、凄いエッチ……♪」"

[[dialogue]]
speaker = "クロト"
# 「っ……紅明の手、凄く気持ちいい……！」
line = "「っ……紅明の手、凄く気持ちいい……！」"

[[dialogue]]
speaker = "紅明"
# 「うん、気持ちいいのに身を委ねちゃっていいからね、ダーリン♪　アタシはダーリンが気持ちよくなってくれれば、幸せだから<emoji=heart04>」
line = "「うん、気持ちいいのに身を委ねちゃっていいからね、ダーリン♪　アタシはダーリンが気持ちよくなってくれれば、幸せだから<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「っ……いや、俺も紅明を気持ち良くする……！　男として、紅明にも気持ち良くなってもらいたいんだっ」
line = "「っ……いや、俺も紅明を気持ち良くする……！　男として、紅明にも気持ち良くなってもらいたいんだっ」"

[[dialogue]]
speaker = "紅明"
# 「えっ、えぇ～～……<emoji=heart04><emoji=heart04>　そ、そんなこと言われちゃったら……アタシ……んんっ……<emoji=heart04><emoji=heart04>」
line = "「えっ、えぇ～～……<emoji=heart04><emoji=heart04>　そ、そんなこと言われちゃったら……アタシ……んんっ……<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「体が喜んで、反応しちゃう<emoji=heart04>　んあぁんっ<emoji=heart04>　おっぱい張ってきて……乳首も、もっと勃起しちゃうっ<emoji=heart04>　はぁんっ<emoji=heart04>　母乳もっと溢れて来ちゃうよぉ<emoji=heart04>！」
line = "「体が喜んで、反応しちゃう<emoji=heart04>　んあぁんっ<emoji=heart04>　おっぱい張ってきて……乳首も、もっと勃起しちゃうっ<emoji=heart04>　はぁんっ<emoji=heart04>　母乳もっと溢れて来ちゃうよぉ<emoji=heart04>！」"

[[dialogue]]
speaker = "クロト"
# 「紅明、このまま乳首でイカせちゃうからな……」
line = "「紅明、このまま乳首でイカせちゃうからな……」"

[[dialogue]]
speaker = "紅明"
# 「ふあぁっ<emoji=heart04>　うん、ダーリン、してぇ<emoji=heart04>！　アタシの乳首、もっと気持ち良く、してぇ<emoji=heart04><emoji=heart04>！」
line = "「ふあぁっ<emoji=heart04>　うん、ダーリン、してぇ<emoji=heart04>！　アタシの乳首、もっと気持ち良く、してぇ<emoji=heart04><emoji=heart04>！」"

[[dialogue]]
speaker = "紅明"
# 「アタシもダーリンのおち○ぽ<emoji=heart04>　頑張ってシコシコするから……一緒に<emoji=heart04>　一緒にぃ<emoji=heart04>！」
line = "「アタシもダーリンのおち○ぽ<emoji=heart04>　頑張ってシコシコするから……一緒に<emoji=heart04>　一緒にぃ<emoji=heart04>！」"

[[dialogue]]
speaker = "クロト"
# 「紅明、好きだっ……！」
line = "「紅明、好きだっ……！」"

[[dialogue]]
speaker = "紅明"
# 「ふあああっ、ダーリンッ<emoji=heart04>！　アタシも好きぃ<emoji=heart04>　大好きぃっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「ふあああっ、ダーリンッ<emoji=heart04>！　アタシも好きぃ<emoji=heart04>　大好きぃっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「はあぁぁっ、んあぁぁぁ～～っ！<emoji=heart04>　ダーリン、乳首しゃぶるの激しいっ……はあぁぁんっ<emoji=heart04>」
line = "「はあぁぁっ、んあぁぁぁ～～っ！<emoji=heart04>　ダーリン、乳首しゃぶるの激しいっ……はあぁぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　もう片方のおっぱい、乳絞りみたいにシコシコされるの、気持ちいいっ<emoji=heart04>！　あぁぁんっ<emoji=heart04>　出ちゃう、いっぱい出ちゃうぅっ<emoji=heart04>！　ふあぁぁんっ<emoji=heart04>」
line = "「あっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　もう片方のおっぱい、乳絞りみたいにシコシコされるの、気持ちいいっ<emoji=heart04>！　あぁぁんっ<emoji=heart04>　出ちゃう、いっぱい出ちゃうぅっ<emoji=heart04>！　ふあぁぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「敏感乳首っ<emoji=heart04>　エッチに弄られるの、凄いのぉっ！　あぁぁんっ<emoji=heart04>　癖になっちゃうっ<emoji=heart04>！」
line = "「敏感乳首っ<emoji=heart04>　エッチに弄られるの、凄いのぉっ！　あぁぁんっ<emoji=heart04>　癖になっちゃうっ<emoji=heart04>！」"

[[dialogue]]
speaker = "紅明"
# 「これ味わっちゃったら<emoji=heart04>　もう１人で乳首オナニーしても、イケなくなっちゃうよぉっ<emoji=heart04>！　あっ、あっ、はあぁぁんっ<emoji=heart04>」
line = "「これ味わっちゃったら<emoji=heart04>　もう１人で乳首オナニーしても、イケなくなっちゃうよぉっ<emoji=heart04>！　あっ、あっ、はあぁぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ふああぁぁぁっ<emoji=heart04>　乳首、クリトリスになっちゃうっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　乳首弄られると、おま○こ反応して、愛液どぷどぷ出てくりゅうっ<emoji=heart04>　ひぃぃんっ<emoji=heart04>」
line = "「ふああぁぁぁっ<emoji=heart04>　乳首、クリトリスになっちゃうっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　乳首弄られると、おま○こ反応して、愛液どぷどぷ出てくりゅうっ<emoji=heart04>　ひぃぃんっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「だ、ダーリンも一緒にぃ<emoji=heart04>　おち○ぽ、ぎゅ～って握って、ゴシゴシするからぁ<emoji=heart04>　ズリズリシュッシュ<emoji=heart04>　ズリズリシュッシュ<emoji=heart04>」
line = "「だ、ダーリンも一緒にぃ<emoji=heart04>　おち○ぽ、ぎゅ～って握って、ゴシゴシするからぁ<emoji=heart04>　ズリズリシュッシュ<emoji=heart04>　ズリズリシュッシュ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ダーリン、気持ちいいっ？　うんっ、アタシもぉっ<emoji=heart04>　あっ、あっ、おっぱい強く吸われるの、頭とろけちゃうっ、はぁ、んはぁ、はあぁぁぁんっ<emoji=heart04>」
line = "「ダーリン、気持ちいいっ？　うんっ、アタシもぉっ<emoji=heart04>　あっ、あっ、おっぱい強く吸われるの、頭とろけちゃうっ、はぁ、んはぁ、はあぁぁぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「アタシも、ダーリンのミルク絞って、気持ち良くするぅ<emoji=heart04>　カリ首のところから亀頭に掛けて、ゴシゴシするのぉ<emoji=heart04>　ズリズリシュッシュ<emoji=heart04>　ズリズリシュッシュぅ<emoji=heart04>」
line = "「アタシも、ダーリンのミルク絞って、気持ち良くするぅ<emoji=heart04>　カリ首のところから亀頭に掛けて、ゴシゴシするのぉ<emoji=heart04>　ズリズリシュッシュ<emoji=heart04>　ズリズリシュッシュぅ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んんんぅっ<emoji=heart04>　カウパー凄い量っ<emoji=heart04>　おち○ぽの先っぽから、どくどく出てるぅ<emoji=heart04>　ズリズリシュッシュ<emoji=heart04>　ズリズリシュッシュぅ<emoji=heart04>」
line = "「んんんぅっ<emoji=heart04>　カウパー凄い量っ<emoji=heart04>　おち○ぽの先っぽから、どくどく出てるぅ<emoji=heart04>　ズリズリシュッシュ<emoji=heart04>　ズリズリシュッシュぅ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あぁんっ<emoji=heart04>　ダーリンのたまたまキュッ、キュッって<emoji=heart04>　根元に引き寄せられてる……！　おち○ぽも膨らんできて……！　射精の準備始めてるぅっ<emoji=heart04>」
line = "「あぁんっ<emoji=heart04>　ダーリンのたまたまキュッ、キュッって<emoji=heart04>　根元に引き寄せられてる……！　おち○ぽも膨らんできて……！　射精の準備始めてるぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「はあぁぁっ<emoji=heart04>　アタシも乳首刺激される度、お腹の奥、ゾクゾクッて<emoji=heart04>　気持ちいいの、のぼってきてるの……！　今までにないくらい、大きなやつぅ<emoji=heart04>　ふあぁぁんっ<emoji=heart04>！」
line = "「はあぁぁっ<emoji=heart04>　アタシも乳首刺激される度、お腹の奥、ゾクゾクッて<emoji=heart04>　気持ちいいの、のぼってきてるの……！　今までにないくらい、大きなやつぅ<emoji=heart04>　ふあぁぁんっ<emoji=heart04>！」"

[[dialogue]]
speaker = "紅明"
# 「はあっ、はあああんっ<emoji=heart04><emoji=heart04>　イクならダーリンと一緒っ<emoji=heart04>　一緒がいいぃ<emoji=heart04>　だからほら、おち○ぽイって<emoji=heart04>　精液いっぱい出してぇ<emoji=heart04>」
line = "「はあっ、はあああんっ<emoji=heart04><emoji=heart04>　イクならダーリンと一緒っ<emoji=heart04>　一緒がいいぃ<emoji=heart04>　だからほら、おち○ぽイって<emoji=heart04>　精液いっぱい出してぇ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あっ、きた<emoji=heart04>　凄いの、のぼってきたぁっ<emoji=heart04>　はあぁぁぁっ、イクイク、もうイク──<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あっ、きた<emoji=heart04>　凄いの、のぼってきたぁっ<emoji=heart04>　はあぁぁぁっ、イクイク、もうイク──<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あっ、あっ、おち○ぽきてっ<emoji=heart04>！　きてきてっ<emoji=heart04>　一緒に気持ち良いミルク出してぇっ<emoji=heart04>」
line = "「あっ、あっ、おち○ぽきてっ<emoji=heart04>！　きてきてっ<emoji=heart04>　一緒に気持ち良いミルク出してぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んあああぁぁぁっ、イク、乳首でイっちゃうっ<emoji=heart04>　おっぱいミルクいっぱい出ちゃうぅっ<emoji=heart04>！」
line = "「んあああぁぁぁっ、イク、乳首でイっちゃうっ<emoji=heart04>　おっぱいミルクいっぱい出ちゃうぅっ<emoji=heart04>！」"

[[dialogue]]
speaker = "紅明"
# 「イクイクイクイク、イっ──くぅぅぅぅ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「イクイクイクイク、イっ──くぅぅぅぅ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「っ……おっぱいでイ、クぅぅぅ──────―っ<emoji=heart04><emoji=heart04><emoji=heart04>　ふあああぁぁぁああああああ～～～っっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「っ……おっぱいでイ、クぅぅぅ──────―っ<emoji=heart04><emoji=heart04><emoji=heart04>　ふあああぁぁぁああああああ～～～っっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あぁぁぁぁっ<emoji=heart04>　ふわぁぁぁ<emoji=heart04>　……はふぅぅ<emoji=heart04>　おっぱいミルク、射精みたいにいっぱい、出てるぅ～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あぁぁぁぁっ<emoji=heart04>　ふわぁぁぁ<emoji=heart04>　……はふぅぅ<emoji=heart04>　おっぱいミルク、射精みたいにいっぱい、出てるぅ～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あはぁ～<emoji=heart04>　ダーリンのおち○ぽミルクも、いっぱい出てるぅ<emoji=heart04>　はぁんっ……凄く濃いオスの匂いで、おま○こキュンキュンしちゃう……<emoji=heart04>」
line = "「あはぁ～<emoji=heart04>　ダーリンのおち○ぽミルクも、いっぱい出てるぅ<emoji=heart04>　はぁんっ……凄く濃いオスの匂いで、おま○こキュンキュンしちゃう……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「はぁ……はぁ……んうぅ……<emoji=heart04>　今までで１番凄い、乳首イキしちゃったぁ……<emoji=heart04>」
line = "「はぁ……はぁ……んうぅ……<emoji=heart04>　今までで１番凄い、乳首イキしちゃったぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ダーリンも気持ちよく、なってくれた……？　えへへ、それなら良かった♪　ダーリンが喜んでくれて、アタシも幸せ……♪」
line = "「ダーリンも気持ちよく、なってくれた……？　えへへ、それなら良かった♪　ダーリンが喜んでくれて、アタシも幸せ……♪」"

[[dialogue]]
speaker = "紅明"
# 「んちゅっ<emoji=heart04>　……ダーリンもアタシのこと、気持ち良くしてくれてありがと♪　感謝のキスだよ<emoji=heart04>」
line = "「んちゅっ<emoji=heart04>　……ダーリンもアタシのこと、気持ち良くしてくれてありがと♪　感謝のキスだよ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「男らしくて、ダーリンのこと、また好きになっちゃった……<emoji=heart04>」
line = "「男らしくて、ダーリンのこと、また好きになっちゃった……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「……こっちこそ、紅明のおかげで癒されて、凄く元気になった」
line = "「……こっちこそ、紅明のおかげで癒されて、凄く元気になった」"

[[dialogue]]
speaker = "紅明"
# 「あっ<emoji=heart04>　……ダーリンのおち○ぽ、あんなに出したのに、ガッチガチのままじゃんっ<emoji=heart04>」
line = "「あっ<emoji=heart04>　……ダーリンのおち○ぽ、あんなに出したのに、ガッチガチのままじゃんっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「今度は俺が、紅明に飲ませてあげる番かな？」
line = "「今度は俺が、紅明に飲ませてあげる番かな？」"

[[dialogue]]
speaker = "紅明"
# 「うんっ<emoji=heart04>」
line = "「うんっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「アタシのおま○こに、ダーリンのおち○ぽミルク、いっぱい飲ませて欲しい……<emoji=heart04>」
line = "「アタシのおま○こに、ダーリンのおち○ぽミルク、いっぱい飲ませて欲しい……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あっ、あんっ<emoji=heart04>　ダーリン……ふあぁっ<emoji=heart04>」
line = "「あっ、あんっ<emoji=heart04>　ダーリン……ふあぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その後、俺は彼女が満足するまで、沢山マッサージを施すのだった。
line = "その後、俺は彼女が満足するまで、沢山マッサージを施すのだった。"
