[[dialogue]]
speaker = "unk"
# 第２話,アニュラスと完全栄養食,P
line = "第２話,アニュラスと完全栄養食,P"

[[dialogue]]
speaker = "unk"
# クリスマスパーティーの準備で、俺たち実行委員はカフェテリアに集まっていた。
line = "クリスマスパーティーの準備で、俺たち実行委員はカフェテリアに集まっていた。"

[[dialogue]]
speaker = "unk"
# ああでもないこうでもないと激論を交わしていたが、疲れたので小休止ということになった。
line = "ああでもないこうでもないと激論を交わしていたが、疲れたので小休止ということになった。"

[[dialogue]]
speaker = "アニュラス"
# 「もぐもぐもぐ……」
line = "「もぐもぐもぐ……」"

[[dialogue]]
speaker = "アニュラス"
# 「ずずずずずーっ……ごくんっ、ふぅ～～」
line = "「ずずずずずーっ……ごくんっ、ふぅ～～」"

[[dialogue]]
speaker = "舞亜"
# 「無理矢理流し込んでるように見えるんだけど、大丈夫？」
line = "「無理矢理流し込んでるように見えるんだけど、大丈夫？」"

[[dialogue]]
speaker = "アニュラス"
# 「へ、平気だ」
line = "「へ、平気だ」"

[[dialogue]]
speaker = "アポロ"
# 「全然平気そうじゃないぞ。苦行に耐えてるって顔だ！」
line = "「全然平気そうじゃないぞ。苦行に耐えてるって顔だ！」"

[[dialogue]]
speaker = "舞亜"
# 「……まずいの？」
line = "「……まずいの？」"

[[dialogue]]
speaker = "アニュラス"
# 「そそ、そんなことはないぞ！　ただちょっと飲み込みづらいだけだ。貴重な食糧を作ってくれた人に、私は心から感謝している」
line = "「そそ、そんなことはないぞ！　ただちょっと飲み込みづらいだけだ。貴重な食糧を作ってくれた人に、私は心から感謝している」"

[[dialogue]]
speaker = "舞亜"
# 「まずいならまずいって言えばいいのに」
line = "「まずいならまずいって言えばいいのに」"

[[dialogue]]
speaker = "unk"
# ちょっと気になるかも
line = "ちょっと気になるかも"

[[dialogue]]
speaker = "unk"
# 何食べてるの？
line = "何食べてるの？"

[[dialogue]]
speaker = "アニュラス"
# 「これは完全栄養食だな。新星の新学園長の要望で、最近売るようになったと聞いている」
line = "「これは完全栄養食だな。新星の新学園長の要望で、最近売るようになったと聞いている」"

[[dialogue]]
speaker = "アポロ"
# 「完全栄養食！？　なんかすごそうな名前だなっ」
line = "「完全栄養食！？　なんかすごそうな名前だなっ」"

[[dialogue]]
speaker = "舞亜"
# 「いくら凄くても、まずいんでしょ？」
line = "「いくら凄くても、まずいんでしょ？」"

[[dialogue]]
speaker = "アニュラス"
# 「ちち、違うぞ！　まずいとは一言も言ってない。強い精神の持ち主でなければ、飲み込むことすら困難なのは事実だが……」
line = "「ちち、違うぞ！　まずいとは一言も言ってない。強い精神の持ち主でなければ、飲み込むことすら困難なのは事実だが……」"

[[dialogue]]
speaker = "アポロ"
# 「精神が試されるのか！　なら挑戦してみたいぞ！」
line = "「精神が試されるのか！　なら挑戦してみたいぞ！」"

[[dialogue]]
speaker = "アニュラス"
# 「いい覚悟だ。アポロも流星ライダーを志すなら、強い精神でなければならないからな。それ、１口やろう」
line = "「いい覚悟だ。アポロも流星ライダーを志すなら、強い精神でなければならないからな。それ、１口やろう」"

[[dialogue]]
speaker = "アポロ"
# 「わぁーい！　んじゃ、いただきまーすっ！　あむっ、むぐむぐむぐ……」
line = "「わぁーい！　んじゃ、いただきまーすっ！　あむっ、むぐむぐむぐ……」"

[[dialogue]]
speaker = "アポロ"
# 「なんだこれぇ、ぼそぼそするぞぉ」
line = "「なんだこれぇ、ぼそぼそするぞぉ」"

[[dialogue]]
speaker = "舞亜"
# 「はい、飲み物。慌てて飲むとむせるからゆっくりね」
line = "「はい、飲み物。慌てて飲むとむせるからゆっくりね」"

[[dialogue]]
speaker = "アポロ"
# 「んぐっ、んぐっ、んぐっ……ふぅ～～～っ、助かった。ありがとなっ、舞亜」
line = "「んぐっ、んぐっ、んぐっ……ふぅ～～～っ、助かった。ありがとなっ、舞亜」"

[[dialogue]]
speaker = "舞亜"
# 「どういたしまして。食べにくそうなのは伝わったけど、結局味はまずいの？」
line = "「どういたしまして。食べにくそうなのは伝わったけど、結局味はまずいの？」"

[[dialogue]]
speaker = "アポロ"
# 「正直ぼそぼそしててよくわかんなかった。でも食べた感想は、もう２度と食べなくていいと思ったぞ！」
line = "「正直ぼそぼそしててよくわかんなかった。でも食べた感想は、もう２度と食べなくていいと思ったぞ！」"

[[dialogue]]
speaker = "アニュラス"
# 「我慢して飲み込んだアポロは偉いぞ。これで強い精神の持ち主だと証明出来たな」
line = "「我慢して飲み込んだアポロは偉いぞ。これで強い精神の持ち主だと証明出来たな」"

[[dialogue]]
speaker = "アポロ"
# 「やった！　まずかったけど、あたしの勝利だな！」
line = "「やった！　まずかったけど、あたしの勝利だな！」"

[[dialogue]]
speaker = "舞亜"
# 「そこまでまずいんだ？　ちょっと気になるかも」
line = "「そこまでまずいんだ？　ちょっと気になるかも」"

[[dialogue]]
speaker = "アニュラス"
# 「ならば舞亜もチャレンジしてくれ」
line = "「ならば舞亜もチャレンジしてくれ」"

[[dialogue]]
speaker = "舞亜"
# 「え～～？　まあ、いいけどさ……」
line = "「え～～？　まあ、いいけどさ……」"

[[dialogue]]
speaker = "アポロ"
# 「頑張れ、舞亜！　強い心で戦うんだ！」
line = "「頑張れ、舞亜！　強い心で戦うんだ！」"

[[dialogue]]
speaker = "舞亜"
# 「はーい、それじゃミルクティーにどっぷり浸けて……うん、これでぼそぼそ解消♪」
line = "「はーい、それじゃミルクティーにどっぷり浸けて……うん、これでぼそぼそ解消♪」"

[[dialogue]]
speaker = "舞亜"
# 「はむっ、ふむふむふむ……うん、確かにおいしくないね。でも、ぼそぼそじゃなくなったら素朴な味で案外いける？」
line = "「はむっ、ふむふむふむ……うん、確かにおいしくないね。でも、ぼそぼそじゃなくなったら素朴な味で案外いける？」"

[[dialogue]]
speaker = "アニュラス"
# 「ひ、卑怯な……そんな加工法があったなんて……」
line = "「ひ、卑怯な……そんな加工法があったなんて……」"

[[dialogue]]
speaker = "舞亜"
# 「元々こうやって食べるよう想定されてるものなのかもね。買うとき説明してくれたらいいのに」
line = "「元々こうやって食べるよう想定されてるものなのかもね。買うとき説明してくれたらいいのに」"

[[dialogue]]
speaker = "アニュラス"
# 「いや、説明はしてもらったが……」
line = "「いや、説明はしてもらったが……」"

[[dialogue]]
speaker = "舞亜"
# 「は？　じゃあなんでそのまま食べてるの？」
line = "「は？　じゃあなんでそのまま食べてるの？」"

[[dialogue]]
speaker = "アニュラス"
# 「いや、その……なんだ、このまま食べた方が修行になるかと思って」
line = "「いや、その……なんだ、このまま食べた方が修行になるかと思って」"

[[dialogue]]
speaker = "舞亜"
# 「おいしく食べる方法がわかってるのに、まずいまま食べなくてもいいでしょ。前から思ってたんだけど、もしかしてアニュラスって……Ｍ？」
line = "「おいしく食べる方法がわかってるのに、まずいまま食べなくてもいいでしょ。前から思ってたんだけど、もしかしてアニュラスって……Ｍ？」"

[[dialogue]]
speaker = "アニュラス"
# 「Ｍじゃない！　断じてＭじゃないぞ！」
line = "「Ｍじゃない！　断じてＭじゃないぞ！」"

[[dialogue]]
speaker = "アポロ"
# 「えむってなんだ？」
line = "「えむってなんだ？」"

[[dialogue]]
speaker = "舞亜"
# 「あっ、アポロちゃんは知らなくていいからね～。大人になったら教えてあげるから」
line = "「あっ、アポロちゃんは知らなくていいからね～。大人になったら教えてあげるから」"

[[dialogue]]
speaker = "アポロ"
# 「そっか！　うん、わかった！」
line = "「そっか！　うん、わかった！」"

[[dialogue]]
speaker = "舞亜"
# 「意外と素直だ……」
line = "「意外と素直だ……」"

[[dialogue]]
speaker = "アポロ"
# 「大人になったら教えるって言われてること、いっぱいあるからな。多すぎて、あたしも諦めた！」
line = "「大人になったら教えるって言われてること、いっぱいあるからな。多すぎて、あたしも諦めた！」"

[[dialogue]]
speaker = "アニュラス"
# 「アポロはそれでいい。知識は知るべき時に自然と入ってくるものだからな」
line = "「アポロはそれでいい。知識は知るべき時に自然と入ってくるものだからな」"

[[dialogue]]
speaker = "アニュラス"
# 「それより、この完全栄養食でパーティーのアイデアを１つ閃いたぞ！」
line = "「それより、この完全栄養食でパーティーのアイデアを１つ閃いたぞ！」"

[[dialogue]]
speaker = "舞亜"
# 「え？　なんだか嫌な予感がするんだけど……」
line = "「え？　なんだか嫌な予感がするんだけど……」"

[[dialogue]]
speaker = "アニュラス"
# 「パーティーの食事に、完全栄養食を出すんだ！　ふふっ、きっといい思い出になるはず……」
line = "「パーティーの食事に、完全栄養食を出すんだ！　ふふっ、きっといい思い出になるはず……」"

[[dialogue]]
speaker = "舞亜"
# 「いや、それはただの罰ゲームでしょ」
line = "「いや、それはただの罰ゲームでしょ」"

[[dialogue]]
speaker = "アポロ"
# 「あたしは反対だ！　クリスマスのご馳走はおいしい方が絶対いいぞ！」
line = "「あたしは反対だ！　クリスマスのご馳走はおいしい方が絶対いいぞ！」"

[[dialogue]]
speaker = "アニュラス"
# 「そうだろうか？　みんなで耐えながら食すのも一興だと思ったんだが」
line = "「そうだろうか？　みんなで耐えながら食すのも一興だと思ったんだが」"

[[dialogue]]
speaker = "舞亜"
# 「却下。どうして苦行めいたことばかり求めるの？」
line = "「却下。どうして苦行めいたことばかり求めるの？」"

[[dialogue]]
speaker = "アポロ"
# 「アニュラスが頑張ってることは伝わったけどな！」
line = "「アニュラスが頑張ってることは伝わったけどな！」"

[[dialogue]]
speaker = "アニュラス"
# 「では更に頑張ってアポロが満足する出し物を考えよう。そうだな、例えば……」
line = "「では更に頑張ってアポロが満足する出し物を考えよう。そうだな、例えば……」"

[[dialogue]]
speaker = "舞亜"
# 「ちょっと待った。アニュラスの気持ちはわかるけど、いったん落ち着こ？」
line = "「ちょっと待った。アニュラスの気持ちはわかるけど、いったん落ち着こ？」"

[[dialogue]]
speaker = "アニュラス"
# 「どうしてだ？　パーティー当日まで、時間はあまりないのだろう？」
line = "「どうしてだ？　パーティー当日まで、時間はあまりないのだろう？」"

[[dialogue]]
speaker = "舞亜"
# 「まだ焦るほどじゃないよ。もっとじっくり腰を据えて考えようよ。ちゃんとしなきゃって思いが空回りしてるよ？」
line = "「まだ焦るほどじゃないよ。もっとじっくり腰を据えて考えようよ。ちゃんとしなきゃって思いが空回りしてるよ？」"

[[dialogue]]
speaker = "舞亜"
# 「なんのためにパーティーをするのか。それって<ruby=イルソーレ>流星寮</ruby>のみんなに楽しんでもらいたいからでしょ？　相手の顔を見て、どうしたら喜んでくれるかを考えて」
line = "「なんのためにパーティーをするのか。それって<ruby>流星寮<rt>イルソーレ</rt></ruby>のみんなに楽しんでもらいたいからでしょ？　相手の顔を見て、どうしたら喜んでくれるかを考えて」"

[[dialogue]]
speaker = "アニュラス"
# 「なるほどな。ではアポロ、失礼するぞ」
line = "「なるほどな。ではアポロ、失礼するぞ」"

[[dialogue]]
speaker = "アポロ"
# 「うわっ、近い！　近いってば～！」
line = "「うわっ、近い！　近いってば～！」"

[[dialogue]]
speaker = "アニュラス"
# 「アポロは可愛いな？　笑顔もきれいだ」
line = "「アポロは可愛いな？　笑顔もきれいだ」"

[[dialogue]]
speaker = "アポロ"
# 「至近距離で褒めるなってばぁ！　アニュラスだってかわいいぞ！　いい顔だ！」
line = "「至近距離で褒めるなってばぁ！　アニュラスだってかわいいぞ！　いい顔だ！」"

[[dialogue]]
speaker = "アニュラス"
# 「当然だ、私は美人だからな」
line = "「当然だ、私は美人だからな」"

[[dialogue]]
speaker = "舞亜"
# 「うわ、すごい自信だ……」
line = "「うわ、すごい自信だ……」"

[[dialogue]]
speaker = "アニュラス"
# 「舞亜も可愛いぞ。私とは違う方向の美人だな」
line = "「舞亜も可愛いぞ。私とは違う方向の美人だな」"

[[dialogue]]
speaker = "舞亜"
# 「ちょお！　こっちにも来るの！？　いい顔で褒めないでっ、照れるっ、照れるから～～っ！！」
line = "「ちょお！　こっちにも来るの！？　いい顔で褒めないでっ、照れるっ、照れるから～～っ！！」"

[[dialogue]]
speaker = "アニュラス"
# 「お世辞じゃないぞ。みんな可愛い。その可愛い顔がもっと可愛くなるようにするのが、私の仕事だ！」
line = "「お世辞じゃないぞ。みんな可愛い。その可愛い顔がもっと可愛くなるようにするのが、私の仕事だ！」"

[[dialogue]]
speaker = "unk"
# こうして、アニュラスの無自覚な褒め殺しが、全方位に向けて炸裂するのであった。
line = "こうして、アニュラスの無自覚な褒め殺しが、全方位に向けて炸裂するのであった。"
