[[dialogue]]
speaker = "unk"
# ヘレナちゃんとデートに出かけていた、ある日のこと。
line = "ヘレナちゃんとデートに出かけていた、ある日のこと。"

[[dialogue]]
speaker = "unk"
# 帰り際に彼女から提案を受けた。
line = "帰り際に彼女から提案を受けた。"

[[dialogue]]
speaker = "ヘレナ"
# 「魔王よ。このあと――」
line = "「魔王よ。このあと――」"

[[dialogue]]
speaker = "ヘレナ"
# 「私の家へ泊まりにこないか？」
line = "「私の家へ泊まりにこないか？」"

[[dialogue]]
speaker = "ヘレナ"
# 「なに、こうして夜遅くなってしまったであろう？　それに明日は祝日だ」
line = "「なに、こうして夜遅くなってしまったであろう？　それに明日は祝日だ」"

[[dialogue]]
speaker = "ヘレナ"
# 「――ふふっ、確かに、別に帰ろうと思えば帰れるであろう……しかし、そこは魔王よ、あれだ」
line = "「――ふふっ、確かに、別に帰ろうと思えば帰れるであろう……しかし、そこは魔王よ、あれだ」"

[[dialogue]]
speaker = "ヘレナ"
# 「私のワガママ、といえば察してくれるか？」
line = "「私のワガママ、といえば察してくれるか？」"

[[dialogue]]
speaker = "ヘレナ"
# 「ちなみに、そのことは事前に、リノにも伝えてあるのだ。だから、気兼ねなくデートの続きをすることができる」
line = "「ちなみに、そのことは事前に、リノにも伝えてあるのだ。だから、気兼ねなくデートの続きをすることができる」"

[[dialogue]]
speaker = "ヘレナ"
# 「――続きとはなにか？　ふふっ、それは……」
line = "「――続きとはなにか？　ふふっ、それは……」"

[[dialogue]]
speaker = "unk"
# お香の甘い匂いを漂わせて、彼女は耳元でそっと囁く。
line = "お香の甘い匂いを漂わせて、彼女は耳元でそっと囁く。"

[[dialogue]]
speaker = "ヘレナ"
# 「<ruby=よとぎ>夜伽</ruby><emoji=heart04>　……といえば、伝わるか？」
line = "「<ruby>夜伽<rt>よとぎ</rt></ruby><emoji=heart04>　……といえば、伝わるか？」"

[[dialogue]]
speaker = "ヘレナ"
# 「……どうだ？　私と、してみないか？」
line = "「……どうだ？　私と、してみないか？」"

[[dialogue]]
speaker = "unk"
# そうして、俺は九浄家に行き、ヘレナちゃんの寝室へ招かれることとなった――
line = "そうして、俺は九浄家に行き、ヘレナちゃんの寝室へ招かれることとなった――"

[[dialogue]]
speaker = "ヘレナ"
# 「ふふっ……<emoji=heart04>　ようこそ、私の部屋へ」
line = "「ふふっ……<emoji=heart04>　ようこそ、私の部屋へ」"

[[dialogue]]
speaker = "ヘレナ"
# 「……どうだ？　これが、ヘレナちゃんのおっぱいであるぞ<emoji=heart04>」
line = "「……どうだ？　これが、ヘレナちゃんのおっぱいであるぞ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「――綺麗とな？　ふふふっ<emoji=heart04>　貴殿にそう言われると、嬉しくなってしまうな<emoji=heart04>」
line = "「――綺麗とな？　ふふふっ<emoji=heart04>　貴殿にそう言われると、嬉しくなってしまうな<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「触ってみるか？　――なに、ダメな相手なら、わざわざ素肌を晒したりせぬ。ほら、貴殿の好きにしてよいのだぞ<emoji=heart04>」
line = "「触ってみるか？　――なに、ダメな相手なら、わざわざ素肌を晒したりせぬ。ほら、貴殿の好きにしてよいのだぞ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺はヘレナちゃんに誘われるまま、その大きな胸に触れた。
line = "俺はヘレナちゃんに誘われるまま、その大きな胸に触れた。"

[[dialogue]]
speaker = "ヘレナ"
# 「んっ……<emoji=heart04>　そうだ、そのまま揉んでみるがよい<emoji=heart04>」
line = "「んっ……<emoji=heart04>　そうだ、そのまま揉んでみるがよい<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「んふっ……<emoji=heart04>　可愛い揉み方であるな<emoji=heart04>　もっと強くてもよいのだぞ？　んっ……<emoji=heart04>」
line = "「んふっ……<emoji=heart04>　可愛い揉み方であるな<emoji=heart04>　もっと強くてもよいのだぞ？　んっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「よいぞ、それでこそ男というものだ……<emoji=heart04>　ふぅ……<emoji=heart04>」
line = "「よいぞ、それでこそ男というものだ……<emoji=heart04>　ふぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふふっ、おっぱいで興奮したのか？　おち○ぽがもう、ガチガチになっているぞ<emoji=heart04>」
line = "「ふふっ、おっぱいで興奮したのか？　おち○ぽがもう、ガチガチになっているぞ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「――私の乳首も固くなってきている？　んっ……<emoji=heart04>　ふふっ、余裕ぶろうとしたが、バレてしまったか……」
line = "「――私の乳首も固くなってきている？　んっ……<emoji=heart04>　ふふっ、余裕ぶろうとしたが、バレてしまったか……」"

[[dialogue]]
speaker = "ヘレナ"
# 「それにしても、顔は可愛いのに、おち○ぽはまさに魔王というべき大きさをしているな……<emoji=heart04>」
line = "「それにしても、顔は可愛いのに、おち○ぽはまさに魔王というべき大きさをしているな……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「男とはこんな風になるのだな。実に面白い……<emoji=heart04>」
line = "「男とはこんな風になるのだな。実に面白い……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「さて、準備をしていかねばな……<emoji=heart04>　んっ……<emoji=heart04>」
line = "「さて、準備をしていかねばな……<emoji=heart04>　んっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「はぁ……<emoji=heart04>　熱くて固いぞ……<emoji=heart04>　擦れるだけで、おま○こが濡れてきてしまう……<emoji=heart04>　人体とは不思議なものであるな……」
line = "「はぁ……<emoji=heart04>　熱くて固いぞ……<emoji=heart04>　擦れるだけで、おま○こが濡れてきてしまう……<emoji=heart04>　人体とは不思議なものであるな……」"

[[dialogue]]
speaker = "ヘレナ"
# 「貴殿も同じか。おち○ぽの先っぽから、先走りが溢れてきているぞ<emoji=heart04>　スマタで感じているのか？」
line = "「貴殿も同じか。おち○ぽの先っぽから、先走りが溢れてきているぞ<emoji=heart04>　スマタで感じているのか？」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふぅ……<emoji=heart04>　お互いのアソコ、すっかりヌルヌルになってしまったな……<emoji=heart04>　んっ……<emoji=heart04>」
line = "「ふぅ……<emoji=heart04>　お互いのアソコ、すっかりヌルヌルになってしまったな……<emoji=heart04>　んっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふふっ、これは果たして、どちらが多く溢れさせてしまっているのか……<emoji=heart04>　はあぁ……<emoji=heart04>」
line = "「ふふっ、これは果たして、どちらが多く溢れさせてしまっているのか……<emoji=heart04>　はあぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「そろそろ、頃合いか？　潤滑液はもう十分であろうし……」
line = "「そろそろ、頃合いか？　潤滑液はもう十分であろうし……」"

[[dialogue]]
speaker = "ヘレナ"
# 「おま○こ、挿れてみるか？」
line = "「おま○こ、挿れてみるか？」"

[[dialogue]]
speaker = "ヘレナ"
# 「――ふふっ、ならば、ここは私に任せるがよい<emoji=heart04>　大人として、少しはリードしてみせねばな」
line = "「――ふふっ、ならば、ここは私に任せるがよい<emoji=heart04>　大人として、少しはリードしてみせねばな」"

[[dialogue]]
speaker = "ヘレナ"
# 「では、ゆくぞ……貴殿の先っぽに、おま○こを当てて……」
line = "「では、ゆくぞ……貴殿の先っぽに、おま○こを当てて……」"

[[dialogue]]
speaker = "ヘレナ"
# 「んんっ……<emoji=heart04>　はあぁっ――<emoji=heart04>」
line = "「んんっ……<emoji=heart04>　はあぁっ――<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「んああぁっ……<emoji=heart04><emoji=heart04>　入った……<emoji=heart04>」
line = "「んああぁっ……<emoji=heart04><emoji=heart04>　入った……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「はあぁっ……<emoji=heart04>　ふうぅ……<emoji=heart04>」
line = "「はあぁっ……<emoji=heart04>　ふうぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「んっ……<emoji=heart04>　童貞卒業おめでとうだ、魔王よ……<emoji=heart04>」
line = "「んっ……<emoji=heart04>　童貞卒業おめでとうだ、魔王よ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「これが九浄ヘレナの、念願のおま○こであるぞ<emoji=heart04>」
line = "「これが九浄ヘレナの、念願のおま○こであるぞ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ん？　――ああ、そうだとも。私も、これが初めてだ」
line = "「ん？　――ああ、そうだとも。私も、これが初めてだ」"

[[dialogue]]
speaker = "ヘレナ"
# 「前にも言ったであろう？　これまでなかなか、よいと思える男と出会えなかったのだ」
line = "「前にも言ったであろう？　これまでなかなか、よいと思える男と出会えなかったのだ」"

[[dialogue]]
speaker = "ヘレナ"
# 「故に、ヘレナちゃんの初めてのおま○こを味わえること、光栄に思うがよいぞ<emoji=heart04>　ふふっ<emoji=heart04>」
line = "「故に、ヘレナちゃんの初めてのおま○こを味わえること、光栄に思うがよいぞ<emoji=heart04>　ふふっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「それでは、動くぞ。んんっ――<emoji=heart04>」
line = "「それでは、動くぞ。んんっ――<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　あっ……<emoji=heart04>　はぁっ……んっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　んんっ……<emoji=heart04>」
line = "「はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　あっ……<emoji=heart04>　はぁっ……んっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「これが男女のまぐわい、というものか……<emoji=heart04>　なるほど、これはすごいな……<emoji=heart04>　んっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」
line = "「これが男女のまぐわい、というものか……<emoji=heart04>　なるほど、これはすごいな……<emoji=heart04>　んっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「貴殿の、大きいものが……<emoji=heart04>　はあぁっ<emoji=heart04>　自分では触ったことのない、おま○この奥に、届いているぞ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」
line = "「貴殿の、大きいものが……<emoji=heart04>　はあぁっ<emoji=heart04>　自分では触ったことのない、おま○この奥に、届いているぞ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「んっ<emoji=heart04>　ふふっ……<emoji=heart04>　可愛い喘ぎ声がこぼれているぞ。私のおま○こが、そんなに気持ちよいのか？」
line = "「んっ<emoji=heart04>　ふふっ……<emoji=heart04>　可愛い喘ぎ声がこぼれているぞ。私のおま○こが、そんなに気持ちよいのか？」"

[[dialogue]]
speaker = "ヘレナ"
# 「私も、んっ……<emoji=heart04>　おち○ぽ、よい感じだぞ……<emoji=heart04>　んっ……ふぅっ……<emoji=heart04>　はあぁっ……<emoji=heart04>」
line = "「私も、んっ……<emoji=heart04>　おち○ぽ、よい感じだぞ……<emoji=heart04>　んっ……ふぅっ……<emoji=heart04>　はあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「だんだん馴染んできて、貴殿にもっとよくしてやれそうだ……<emoji=heart04>　ふうぅ……<emoji=heart04>」
line = "「だんだん馴染んできて、貴殿にもっとよくしてやれそうだ……<emoji=heart04>　ふうぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「こんなのは、どうだ……？　おま○この中を抱き締めるように、ぎゅ～っと――<emoji=heart04>」
line = "「こんなのは、どうだ……？　おま○この中を抱き締めるように、ぎゅ～っと――<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ヘレナちゃんの膣内が、きゅっと締まって、俺のペニスに絡みついてくる。
line = "ヘレナちゃんの膣内が、きゅっと締まって、俺のペニスに絡みついてくる。"

[[dialogue]]
speaker = "ヘレナ"
# 「――すごく気持ちいい、とな？　ふふっ、そんなとろけたような可愛い顔をしおって<emoji=heart04>　もっとしてあげたくなってしまうではないか<emoji=heart04>」
line = "「――すごく気持ちいい、とな？　ふふっ、そんなとろけたような可愛い顔をしおって<emoji=heart04>　もっとしてあげたくなってしまうではないか<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ほら、腰を振るのと合わせて――にゅっぽにゅっぽ<emoji=heart04>　きゅっきゅ<emoji=heart04>　……ちゅっぷちゅっぷ　きゅっきゅ<emoji=heart04>」
line = "「ほら、腰を振るのと合わせて――にゅっぽにゅっぽ<emoji=heart04>　きゅっきゅ<emoji=heart04>　……ちゅっぷちゅっぷ　きゅっきゅ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「はあぁっ……<emoji=heart04>　貴殿の可愛く感じる姿を見ていると、私も興奮してくるぞ……<emoji=heart04>　んっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」
line = "「はあぁっ……<emoji=heart04>　貴殿の可愛く感じる姿を見ていると、私も興奮してくるぞ……<emoji=heart04>　んっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「もっといっぱい、見せるがよい<emoji=heart04>　ほら、おま○こ、ぎゅ～っ<emoji=heart04>　にゅっぷにゅっぷ<emoji=heart04>　しっこしっこ<emoji=heart04>　ぎゅっぷぎゅっぷ<emoji=heart04>　にゅっぽにゅっぽ<emoji=heart04>」
line = "「もっといっぱい、見せるがよい<emoji=heart04>　ほら、おま○こ、ぎゅ～っ<emoji=heart04>　にゅっぷにゅっぷ<emoji=heart04>　しっこしっこ<emoji=heart04>　ぎゅっぷぎゅっぷ<emoji=heart04>　にゅっぽにゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふふっ、この角度で、腰を振るのがよいのか？　ならば集中的にっ<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>　パンパンッ<emoji=heart04>　じゅっぷじゅっぷ　パンパンッ<emoji=heart04>」
line = "「ふふっ、この角度で、腰を振るのがよいのか？　ならば集中的にっ<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>　パンパンッ<emoji=heart04>　じゅっぷじゅっぷ　パンパンッ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「んふぅぅっ<emoji=heart04>　おち○ぽ、私の中でビクビクと、喜んでいるのがわかるぞ<emoji=heart04>　じゅっぷじゅっぷ<emoji=heart04>　パンパンッ<emoji=heart04>　ぎゅっぷぎゅっぷ<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>」
line = "「んふぅぅっ<emoji=heart04>　おち○ぽ、私の中でビクビクと、喜んでいるのがわかるぞ<emoji=heart04>　じゅっぷじゅっぷ<emoji=heart04>　パンパンッ<emoji=heart04>　ぎゅっぷぎゅっぷ<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「あとは、男はこういうのもいいと聞いたぞ。片手を後ろに回して――」
line = "「あとは、男はこういうのもいいと聞いたぞ。片手を後ろに回して――」"

[[dialogue]]
speaker = "unk"
# そう言ってヘレナちゃんが触れた先は、俺の睾丸だった。
line = "そう言ってヘレナちゃんが触れた先は、俺の睾丸だった。"

[[dialogue]]
speaker = "ヘレナ"
# 「ふふっ<emoji=heart04>　貴殿はここも大きくて、立派であるな<emoji=heart04>　しかし、無防備で柔らかい<emoji=heart04>　はぁぁ<emoji=heart04>　ほら、ふにふに<emoji=heart04>　さわさわ<emoji=heart04>」
line = "「ふふっ<emoji=heart04>　貴殿はここも大きくて、立派であるな<emoji=heart04>　しかし、無防備で柔らかい<emoji=heart04>　はぁぁ<emoji=heart04>　ほら、ふにふに<emoji=heart04>　さわさわ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「んふっ<emoji=heart04>　漏れる喘ぎ声が、一段と可愛くなったな<emoji=heart04>　おち○ぽとタマタマの同時責め、はぁぁ<emoji=heart04>　興奮するのか？　もみもみ<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>」
line = "「んふっ<emoji=heart04>　漏れる喘ぎ声が、一段と可愛くなったな<emoji=heart04>　おち○ぽとタマタマの同時責め、はぁぁ<emoji=heart04>　興奮するのか？　もみもみ<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「なら、あぁぁん<emoji=heart04>　おま○こでぎゅっとするのも、一緒にしてやろう<emoji=heart04>　ふぅっ――<emoji=heart04>」
line = "「なら、あぁぁん<emoji=heart04>　おま○こでぎゅっとするのも、一緒にしてやろう<emoji=heart04>　ふぅっ――<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ぎゅっぷぎゅっぷ<emoji=heart04>　ふにふに<emoji=heart04>　パンパンッ<emoji=heart04>　さわさわ<emoji=heart04>　……はぁぁぁん<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>　もみもみ<emoji=heart04>　パンパンッ<emoji=heart04>　パンパンッ<emoji=heart04>」
line = "「ぎゅっぷぎゅっぷ<emoji=heart04>　ふにふに<emoji=heart04>　パンパンッ<emoji=heart04>　さわさわ<emoji=heart04>　……はぁぁぁん<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>　もみもみ<emoji=heart04>　パンパンッ<emoji=heart04>　パンパンッ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 気持ちよくて興奮が高まるあまり、俺は思わず、ヘレナちゃんの名前を呼んでしまう。
line = "気持ちよくて興奮が高まるあまり、俺は思わず、ヘレナちゃんの名前を呼んでしまう。"

[[dialogue]]
speaker = "ヘレナ"
# 「――んっ<emoji=heart04>　どうした？　魔王よ、はぁぁん<emoji=heart04>　なにか他に、して欲しいことがあるのか？」
line = "「――んっ<emoji=heart04>　どうした？　魔王よ、はぁぁん<emoji=heart04>　なにか他に、して欲しいことがあるのか？」"

[[dialogue]]
speaker = "ヘレナ"
# 「可愛い貴殿の為なら、このヘレナちゃん、なんでもしてやるぞ<emoji=heart04>　んっ……<emoji=heart04>　なんでもおねだり、するがよい<emoji=heart04>　ふうぅっ……<emoji=heart04>」
line = "「可愛い貴殿の為なら、このヘレナちゃん、なんでもしてやるぞ<emoji=heart04>　んっ……<emoji=heart04>　なんでもおねだり、するがよい<emoji=heart04>　ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# なんでもしてくれる、と言われて、俺は気づけば……
line = "なんでもしてくれる、と言われて、俺は気づけば……"

[[dialogue]]
speaker = "クロト"
# 「――ヘレナちゃん、好きだ。俺と付き合って欲しい」
line = "「――ヘレナちゃん、好きだ。俺と付き合って欲しい」"

[[dialogue]]
speaker = "ヘレナ"
# 「…………！」
line = "「…………！」"

[[dialogue]]
speaker = "ヘレナ"
# 「んっ……<emoji=heart04>　まったく、なんでもしてやると言ったが、はぁぁ<emoji=heart04>　まさか、そんなお願いとは……。はあぁぁっ<emoji=heart04>」
line = "「んっ……<emoji=heart04>　まったく、なんでもしてやると言ったが、はぁぁ<emoji=heart04>　まさか、そんなお願いとは……。はあぁぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「しかし、それならば……ふうぅ<emoji=heart04>　可愛いだけじゃなくて、男らしいところを見せて、もらわねばな……<emoji=heart04>」
line = "「しかし、それならば……ふうぅ<emoji=heart04>　可愛いだけじゃなくて、男らしいところを見せて、もらわねばな……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「故に、私のことが好きだというのなら――」
line = "「故に、私のことが好きだというのなら――」"

[[dialogue]]
speaker = "ヘレナ"
# 「んんっ<emoji=heart04>　その思いの丈、たっぷりと子宮の奥まで吐き出して、証明してみせよ<emoji=heart04>」
line = "「んんっ<emoji=heart04>　その思いの丈、たっぷりと子宮の奥まで吐き出して、証明してみせよ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ゆくぞ……<emoji=heart04>　んんっ――<emoji=heart04><emoji=heart04>」
line = "「ゆくぞ……<emoji=heart04>　んんっ――<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「じゅぽじゅぽ、パンパンッ<emoji=heart04>　どちゅどちゅ、パンパンッ<emoji=heart04>　……はぁぁん<emoji=heart04>　ふんっふんっ<emoji=heart04>　ぬちゅぬちゅ、ずっぽずっぽ<emoji=heart04>　どちゅどちゅ、じゅっぽじゅっぽ<emoji=heart04>」
line = "「じゅぽじゅぽ、パンパンッ<emoji=heart04>　どちゅどちゅ、パンパンッ<emoji=heart04>　……はぁぁん<emoji=heart04>　ふんっふんっ<emoji=heart04>　ぬちゅぬちゅ、ずっぽずっぽ<emoji=heart04>　どちゅどちゅ、じゅっぽじゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「あぁぁん<emoji=heart04>　おま○こで、ぎゅっとするのも、全力でゆくぞっ？　それっ<emoji=heart04>　ふんんっ――<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あぁぁん<emoji=heart04>　おま○こで、ぎゅっとするのも、全力でゆくぞっ？　それっ<emoji=heart04>　ふんんっ――<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ぎゅぷぎゅぷ、ふんっふんっ<emoji=heart04>　じゅぶじゅぶ、ふんっふんっ<emoji=heart04>　どちゅどちゅ、ずっぽずっぽ<emoji=heart04>　じゅぶじゅぶ、ぎゅっぽぎゅっぽ<emoji=heart04>」
line = "「ぎゅぷぎゅぷ、ふんっふんっ<emoji=heart04>　じゅぶじゅぶ、ふんっふんっ<emoji=heart04>　どちゅどちゅ、ずっぽずっぽ<emoji=heart04>　じゅぶじゅぶ、ぎゅっぽぎゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「はあぁっ<emoji=heart04>　よいぞ、魔王よ<emoji=heart04>　その快楽に乱れた顔、実にプリティーで興奮するっ<emoji=heart04>　ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>　ふあぁぁぁん<emoji=heart04>」
line = "「はあぁっ<emoji=heart04>　よいぞ、魔王よ<emoji=heart04>　その快楽に乱れた顔、実にプリティーで興奮するっ<emoji=heart04>　ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>　ふあぁぁぁん<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「激しい喘ぎ声も、ラブリーだ<emoji=heart04>　もっと私に聞かせてくれ<emoji=heart04>　ほら、ほらっ<emoji=heart04>　ぎゅぷぎゅぷ、パンパンッ<emoji=heart04>　じゅぽじゅぽ、パンパンッ<emoji=heart04>」
line = "「激しい喘ぎ声も、ラブリーだ<emoji=heart04>　もっと私に聞かせてくれ<emoji=heart04>　ほら、ほらっ<emoji=heart04>　ぎゅぷぎゅぷ、パンパンッ<emoji=heart04>　じゅぽじゅぽ、パンパンッ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「はぁぁぁん<emoji=heart04>　そら、がんばれ、がんばれ<emoji=heart04>　ぬちゅぬちゅ、ずっぽずっぽ<emoji=heart04>　どちゅどちゅ、じゅっぽじゅっぽ<emoji=heart04>　ぎゅぷぎゅぷ、パンパンッ<emoji=heart04>」
line = "「はぁぁぁん<emoji=heart04>　そら、がんばれ、がんばれ<emoji=heart04>　ぬちゅぬちゅ、ずっぽずっぽ<emoji=heart04>　どちゅどちゅ、じゅっぽじゅっぽ<emoji=heart04>　ぎゅぷぎゅぷ、パンパンッ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「激しくされて、もう出ちゃいそう？　あぁんっ<emoji=heart04>　もう少し我慢するのだ。私も、もうそろそろ……<emoji=heart04>　ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>」
line = "「激しくされて、もう出ちゃいそう？　あぁんっ<emoji=heart04>　もう少し我慢するのだ。私も、もうそろそろ……<emoji=heart04>　ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「あぁぁぁんっ<emoji=heart04>　んんんっ<emoji=heart04>　よいぞ<emoji=heart04>　きた、きたきたきたっ<emoji=heart04>」
line = "「あぁぁぁんっ<emoji=heart04>　んんんっ<emoji=heart04>　よいぞ<emoji=heart04>　きた、きたきたきたっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ラストスパートだ、ゆくぞっ<emoji=heart04>」
line = "「ラストスパートだ、ゆくぞっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ぎゅぷぎゅぷ、パンパンッ<emoji=heart04>　じゅぽじゅぽ、パンパンッ<emoji=heart04>　ああっ、ふあぁぁぁん<emoji=heart04>　……どちゅどちゅ、ずっぽずっぽ<emoji=heart04>　じゅぶじゅぶ、ぎゅっぽぎゅっぽ<emoji=heart04>」
line = "「ぎゅぷぎゅぷ、パンパンッ<emoji=heart04>　じゅぽじゅぽ、パンパンッ<emoji=heart04>　ああっ、ふあぁぁぁん<emoji=heart04>　……どちゅどちゅ、ずっぽずっぽ<emoji=heart04>　じゅぶじゅぶ、ぎゅっぽぎゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「んんんっ<emoji=heart04>　おち○ぽ膨らんでる<emoji=heart04>　まだだ、ギリギリまで我慢するのだ<emoji=heart04>　ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>」
line = "「んんんっ<emoji=heart04>　おち○ぽ膨らんでる<emoji=heart04>　まだだ、ギリギリまで我慢するのだ<emoji=heart04>　ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「はああぁっ<emoji=heart04>　くるっ<emoji=heart04>　私も昇ってきたっ<emoji=heart04>　パンパンッ<emoji=heart04>　パンパンッ<emoji=heart04>」
line = "「はああぁっ<emoji=heart04>　くるっ<emoji=heart04>　私も昇ってきたっ<emoji=heart04>　パンパンッ<emoji=heart04>　パンパンッ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「よいぞっ<emoji=heart04>　出せ、出せ出せ出せ<emoji=heart04>」
line = "「よいぞっ<emoji=heart04>　出せ、出せ出せ出せ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふあああぁぁぁっ<emoji=heart04>　イク、イクイクイクっ<emoji=heart04><emoji=heart04>　イっ――――」
line = "「ふあああぁぁぁっ<emoji=heart04>　イク、イクイクイクっ<emoji=heart04><emoji=heart04>　イっ――――」"

[[dialogue]]
speaker = "ヘレナ"
# 「イックぅぅぅーーーーーーーーーっ<emoji=heart04><emoji=heart04><emoji=heart04>　んあああぁぁぁ～～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「イックぅぅぅーーーーーーーーーっ<emoji=heart04><emoji=heart04><emoji=heart04>　んあああぁぁぁ～～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「はああぁっ……<emoji=heart04>　私の子宮に、貴殿の熱い精液が入ってくるぅ……<emoji=heart04>」
line = "「はああぁっ……<emoji=heart04>　私の子宮に、貴殿の熱い精液が入ってくるぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「んっ……<emoji=heart04>　すごいっ<emoji=heart04>　まだ出るのか……<emoji=heart04>　あぁぁ、ふうぅ……<emoji=heart04>」
line = "「んっ……<emoji=heart04>　すごいっ<emoji=heart04>　まだ出るのか……<emoji=heart04>　あぁぁ、ふうぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「１回の射精で、子宮をいっぱいにしてしまう気か？　ふふっ<emoji=heart04>」
line = "「１回の射精で、子宮をいっぱいにしてしまう気か？　ふふっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「――んっ<emoji=heart04>　ようやく出し切ったみたいだな……<emoji=heart04>」
line = "「――んっ<emoji=heart04>　ようやく出し切ったみたいだな……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「それじゃあ、抜くぞ……<emoji=heart04>」
line = "「それじゃあ、抜くぞ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「はあぁ……<emoji=heart04>　ふふっ<emoji=heart04>　見てみよ、貴殿のが溢れてきてしまっているぞ<emoji=heart04>」
line = "「はあぁ……<emoji=heart04>　ふふっ<emoji=heart04>　見てみよ、貴殿のが溢れてきてしまっているぞ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「……それで、どうであったか？　初めてのセックスは」
line = "「……それで、どうであったか？　初めてのセックスは」"

[[dialogue]]
speaker = "ヘレナ"
# 「正直、私も興奮して、やり過ぎてしまったかもしれぬが……」
line = "「正直、私も興奮して、やり過ぎてしまったかもしれぬが……」"

[[dialogue]]
speaker = "unk"
# 俺は、最高の筆おろしだったとヘレナちゃんに伝える。
line = "俺は、最高の筆おろしだったとヘレナちゃんに伝える。"

[[dialogue]]
speaker = "ヘレナ"
# 「そうか……ふふっ、気持ちよくなってくれたのなら、それでよい」
line = "「そうか……ふふっ、気持ちよくなってくれたのなら、それでよい」"

[[dialogue]]
speaker = "ヘレナ"
# 「――私はどうだったのか？　そんなこと、皆まで言うでない」
line = "「――私はどうだったのか？　そんなこと、皆まで言うでない」"

[[dialogue]]
speaker = "unk"
# 彼女は俺に顔を寄せてきて、耳元で囁く。
line = "彼女は俺に顔を寄せてきて、耳元で囁く。"

[[dialogue]]
speaker = "ヘレナ"
# 「気持ちよかったに決まっているであろう？」
line = "「気持ちよかったに決まっているであろう？」"

[[dialogue]]
speaker = "unk"
# そして、唇同士が触れて――
line = "そして、唇同士が触れて――"

[[dialogue]]
speaker = "ヘレナ"
# 「んっ……<emoji=heart04>　ちゅっ<emoji=heart04>」
line = "「んっ……<emoji=heart04>　ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「いま気づいたが……貴殿とキスをするのは、これが初めてだな」
line = "「いま気づいたが……貴殿とキスをするのは、これが初めてだな」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふふっ、順番が逆転してしまったな。私も緊張していたということか……」
line = "「ふふっ、順番が逆転してしまったな。私も緊張していたということか……」"

[[dialogue]]
speaker = "ヘレナ"
# 「魔王よ――」
line = "「魔王よ――」"

[[dialogue]]
speaker = "ヘレナ"
# 「愛しているぞ……<emoji=heart04>」
line = "「愛しているぞ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ちゅっ……<emoji=heart04>　んむっ<emoji=heart04>　ちゅぱっ<emoji=heart04>　れろちゅっ……<emoji=heart04>」
line = "「ちゅっ……<emoji=heart04>　んむっ<emoji=heart04>　ちゅぱっ<emoji=heart04>　れろちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# それからヘレナちゃんにディープキスをされて、俺の思考は彼女一色で染まってしまうほど、甘く溶かされてしまうのだった――
line = "それからヘレナちゃんにディープキスをされて、俺の思考は彼女一色で染まってしまうほど、甘く溶かされてしまうのだった――"
