[[dialogue]]
speaker = "unk"
# これは、ルルカが水着フォームを手に入れるよりも、ハメ撮り風疑似配信エッチをするよりも、ずっと前の出来事。
line = "これは、ルルカが水着フォームを手に入れるよりも、ハメ撮り風疑似配信エッチをするよりも、ずっと前の出来事。"

[[dialogue]]
speaker = "unk"
# 彼女とまだ初体験を済ませる前の、初々しかった頃の俺たちの思い出だ。
line = "彼女とまだ初体験を済ませる前の、初々しかった頃の俺たちの思い出だ。"

[[dialogue]]
speaker = "unk"
# ルルカと付き合い始めてしばらく経ったある日──俺は決意を固めて、彼女を自宅に呼んだ。
line = "ルルカと付き合い始めてしばらく経ったある日──俺は決意を固めて、彼女を自宅に呼んだ。"

[[dialogue]]
speaker = "ルルカ"
# 「んぅっ……ちゅ、んちゅるっ……ちゅぅ、んちゅっ……はぁっ……<emoji=heart04>」
line = "「んぅっ……ちゅ、んちゅるっ……ちゅぅ、んちゅっ……はぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「え、えへへ……キス、何回もしてきたけど……今までで一番ドキドキしてるかも……」
line = "「え、えへへ……キス、何回もしてきたけど……今までで一番ドキドキしてるかも……」"

[[dialogue]]
speaker = "ルルカ"
# 「その、今日はお兄ちゃんのお家、誰も帰ってこないんだよね……？」
line = "「その、今日はお兄ちゃんのお家、誰も帰ってこないんだよね……？」"

[[dialogue]]
speaker = "ルルカ"
# 「う、うん。お家に来てって言われた時から、わかってたよ。心の準備もしてきたし……」
line = "「う、うん。お家に来てって言われた時から、わかってたよ。心の準備もしてきたし……」"

[[dialogue]]
speaker = "ルルカ"
# 「お家でシャワーも浴びてきたの。そ、そういうこと、するんだなってわかってたから……だから……」
line = "「お家でシャワーも浴びてきたの。そ、そういうこと、するんだなってわかってたから……だから……」"

[[dialogue]]
speaker = "ルルカ"
# 「お兄ちゃん。あたしの初めて、もらってくれる……？」
line = "「お兄ちゃん。あたしの初めて、もらってくれる……？」"

[[dialogue]]
speaker = "ルルカ"
# 「こ、こんな体勢でいいのかな……お兄ちゃん、重くない……？」
line = "「こ、こんな体勢でいいのかな……お兄ちゃん、重くない……？」"

[[dialogue]]
speaker = "unk"
# 学園の制服を脱いで、一糸まとわぬ姿になったルルカが不安そうにこぼしてくる。
line = "学園の制服を脱いで、一糸まとわぬ姿になったルルカが不安そうにこぼしてくる。"

[[dialogue]]
speaker = "クロト"
# 「ぜんぜん。むしろ軽すぎるくらい」
line = "「ぜんぜん。むしろ軽すぎるくらい」"

[[dialogue]]
speaker = "ルルカ"
# 「そ、そっか。それなら良かったかも……」
line = "「そ、そっか。それなら良かったかも……」"

[[dialogue]]
speaker = "unk"
# 一年生の中でも小柄なルルカは見た目どおり、いや、見た目以上の軽さだった。
line = "一年生の中でも小柄なルルカは見た目どおり、いや、見た目以上の軽さだった。"

[[dialogue]]
speaker = "unk"
# こんなに華奢な女の子とこれから繋がって本当に良いのか──そんな背徳感を覚えてしまうほどだ。
line = "こんなに華奢な女の子とこれから繋がって本当に良いのか──そんな背徳感を覚えてしまうほどだ。"

[[dialogue]]
speaker = "ルルカ"
# 「うう～……夢みたい。まさかお兄ちゃんと、こういうエッチなことができるだなんて……」
line = "「うう～……夢みたい。まさかお兄ちゃんと、こういうエッチなことができるだなんて……」"

[[dialogue]]
speaker = "ルルカ"
# 「恋人同士になってから、こーゆうこと。期待はしてたけど……実はちょっぴり不安だったんだ～……」
line = "「恋人同士になってから、こーゆうこと。期待はしてたけど……実はちょっぴり不安だったんだ～……」"

[[dialogue]]
speaker = "クロト"
# 「不安って？」
line = "「不安って？」"

[[dialogue]]
speaker = "ルルカ"
# 「ほ、ほら。あたしっておっぱい小さいし、あんまりエッチな体つきもしてないでしょ？」
line = "「ほ、ほら。あたしっておっぱい小さいし、あんまりエッチな体つきもしてないでしょ？」"

[[dialogue]]
speaker = "ルルカ"
# 「それにお兄ちゃんは、星徒会ですごい美人さんに囲まれてるし……見劣りしちゃうかなぁ～……なんて……」
line = "「それにお兄ちゃんは、星徒会ですごい美人さんに囲まれてるし……見劣りしちゃうかなぁ～……なんて……」"

[[dialogue]]
speaker = "クロト"
# 「そんなことないよ。絶対にない。ルルカの裸にドキドキしていないと、俺だってこんな風にならないから」
line = "「そんなことないよ。絶対にない。ルルカの裸にドキドキしていないと、俺だってこんな風にならないから」"

[[dialogue]]
speaker = "unk"
# ルルカのお尻に、痛いほどに勃起したペニスを擦り付けると、膝上に乗った彼女がぶるりと震えた。
line = "ルルカのお尻に、痛いほどに勃起したペニスを擦り付けると、膝上に乗った彼女がぶるりと震えた。"

[[dialogue]]
speaker = "ルルカ"
# 「ぁ──ほんとだ……<emoji=heart04>　お兄ちゃんの、お、おち○ぽ……すっごく大きくなってる……」
line = "「ぁ──ほんとだ……<emoji=heart04>　お兄ちゃんの、お、おち○ぽ……すっごく大きくなってる……」"

[[dialogue]]
speaker = "ルルカ"
# 「男の人ってこんな風になっちゃうと、射精？　しないと小さくならないんだよね……？」
line = "「男の人ってこんな風になっちゃうと、射精？　しないと小さくならないんだよね……？」"

[[dialogue]]
speaker = "ルルカ"
# 「あ、えへへぇ<emoji=heart04>　『おち○ぽ』って言い方、すっごくえっちだよね？　こういう風に言うと、男の人が喜ぶって雑誌に書いてあったんだぁ<emoji=heart04>」
line = "「あ、えへへぇ<emoji=heart04>　『おち○ぽ』って言い方、すっごくえっちだよね？　こういう風に言うと、男の人が喜ぶって雑誌に書いてあったんだぁ<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「う、うん。いいよ、お兄ちゃん。ルルカのおま○こに……入れて？」
line = "「う、うん。いいよ、お兄ちゃん。ルルカのおま○こに……入れて？」"

[[dialogue]]
speaker = "ルルカ"
# 「お兄ちゃんとキスしてた時から──ううん。お家に来る前から、ドキドキして、あたし、濡れちゃってるから……」
line = "「お兄ちゃんとキスしてた時から──ううん。お家に来る前から、ドキドキして、あたし、濡れちゃってるから……」"

[[dialogue]]
speaker = "クロト"
# 「──っ！」
line = "「──っ！」"

[[dialogue]]
speaker = "ルルカ"
# 「ルルカのおま○こで、おち○ぽいっぱい、気持ちよくなっていいんだよ。お兄ちゃん？」
line = "「ルルカのおま○こで、おち○ぽいっぱい、気持ちよくなっていいんだよ。お兄ちゃん？」"

[[dialogue]]
speaker = "unk"
# 繋いだ手に力がこもる。可愛い恋人がもう覚悟を決めているみたいだった。
line = "繋いだ手に力がこもる。可愛い恋人がもう覚悟を決めているみたいだった。"

[[dialogue]]
speaker = "unk"
# 俺はうなずいて、ペニスをルルカの女性器にあてがって──
line = "俺はうなずいて、ペニスをルルカの女性器にあてがって──"

[[dialogue]]
speaker = "ルルカ"
# 「ふう、ぅっ──ぁ、はっ……あぁあ、あぁあっ……<emoji=heart04>」
line = "「ふう、ぅっ──ぁ、はっ……あぁあ、あぁあっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 狭くて熱いルルカの膣内に、俺のペニスが根元まで埋まった。
line = "狭くて熱いルルカの膣内に、俺のペニスが根元まで埋まった。"

[[dialogue]]
speaker = "ルルカ"
# 「ふぅっ……んんぅっ……はぁ、んんっ……んはぁー……す、すごぃ……お兄ちゃんのおち○ぽ、全部、入っちゃったぁ……<emoji=heart04>」
line = "「ふぅっ……んんぅっ……はぁ、んんっ……んはぁー……す、すごぃ……お兄ちゃんのおち○ぽ、全部、入っちゃったぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「苦しくないか？」
line = "「苦しくないか？」"

[[dialogue]]
speaker = "ルルカ"
# 「う、うん。ありがと……思ってたよりぜんぜん平気。んんっ……ふぅっ……ぅ、ぁっ……<emoji=heart04>」
line = "「う、うん。ありがと……思ってたよりぜんぜん平気。んんっ……ふぅっ……ぅ、ぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「お兄ちゃんのおち○ぽで、お腹がいっぱいになってて……はぁ、うぅんんっ……苦しいけど、痛くは、ないよぉ……？<emoji=heart04>」
line = "「お兄ちゃんのおち○ぽで、お腹がいっぱいになってて……はぁ、うぅんんっ……苦しいけど、痛くは、ないよぉ……？<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「んんぅ、はぁ、はああーっ……おち○ぽ大きい……おへその辺りまで、入っちゃってる感じ……す、すごぉ～……<emoji=heart04>」
line = "「んんぅ、はぁ、はああーっ……おち○ぽ大きい……おへその辺りまで、入っちゃってる感じ……す、すごぉ～……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ルルカが喋ったり息継ぎをするたびに、キュッキュッと膣内が締まってくる。
line = "ルルカが喋ったり息継ぎをするたびに、キュッキュッと膣内が締まってくる。"

[[dialogue]]
speaker = "クロト"
# 「ぅ、くぅっ……！」
line = "「ぅ、くぅっ……！」"

[[dialogue]]
speaker = "ルルカ"
# 「あ、ぁっ……お兄ちゃん、あたしの中でびくびく、してる……<emoji=heart04>　もしかして、気持ちよくなってくれてる……？」
line = "「あ、ぁっ……お兄ちゃん、あたしの中でびくびく、してる……<emoji=heart04>　もしかして、気持ちよくなってくれてる……？」"

[[dialogue]]
speaker = "クロト"
# 「正直、入れてるだけで出そうなくらい、気持ちいい……」
line = "「正直、入れてるだけで出そうなくらい、気持ちいい……」"

[[dialogue]]
speaker = "ルルカ"
# 「あ、あはー……<emoji=heart04>　嬉しい……あたしたち、もしかして体の相性、いいのかな<emoji=heart04>」
line = "「あ、あはー……<emoji=heart04>　嬉しい……あたしたち、もしかして体の相性、いいのかな<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「でも、男の人ってじっとしてるの辛いんだよね？　お兄ちゃん、動いていいよ……？」
line = "「でも、男の人ってじっとしてるの辛いんだよね？　お兄ちゃん、動いていいよ……？」"

[[dialogue]]
speaker = "クロト"
# 「──いいのか？」
line = "「──いいのか？」"

[[dialogue]]
speaker = "ルルカ"
# 「うん、ルルカのお尻つかんで、いっぱいおち○ぽ、出し入れして……？<emoji=heart04>　気持ち良ーく、なって欲しいな<emoji=heart04>」
line = "「うん、ルルカのお尻つかんで、いっぱいおち○ぽ、出し入れして……？<emoji=heart04>　気持ち良ーく、なって欲しいな<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 耳元でルルカのおねだりを聞いて、俺も我慢ができなくなった。
line = "耳元でルルカのおねだりを聞いて、俺も我慢ができなくなった。"

[[dialogue]]
speaker = "ルルカ"
# 「っふぅうっ<emoji=heart04>　んんんぅっ<emoji=heart04>　は、ぁっ……はぅ、ぅうっ……んんぅっ……んぁっ……<emoji=heart04>」
line = "「っふぅうっ<emoji=heart04>　んんんぅっ<emoji=heart04>　は、ぁっ……はぅ、ぅうっ……んんぅっ……んぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「す、すごぉいっ……おち○ぽ、本当に、出たり、入ったり、して、るぅっ……<emoji=heart04>」
line = "「す、すごぉいっ……おち○ぽ、本当に、出たり、入ったり、して、るぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# たっぷりの愛液で濡れそぼっていて、狭くて熱い膣内。ゆっくりピストンをするだけで、俺にとっても未体験の快感が押し寄せてくる。
line = "たっぷりの愛液で濡れそぼっていて、狭くて熱い膣内。ゆっくりピストンをするだけで、俺にとっても未体験の快感が押し寄せてくる。"

[[dialogue]]
speaker = "ルルカ"
# 「んんっ……ふぅ、んんんっ<emoji=heart04>　あ、ぁっ……下から、ずぷ、ずぷって……突かれてっ……んんぅ、ふぁ、あぁっ……<emoji=heart04>」
line = "「んんっ……ふぅ、んんんっ<emoji=heart04>　あ、ぁっ……下から、ずぷ、ずぷって……突かれてっ……んんぅ、ふぁ、あぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「お、お兄ちゃん、気持ちいい？　ルルカのおま○こ、ちゃんと気持ちいいかなっ……？」
line = "「お、お兄ちゃん、気持ちいい？　ルルカのおま○こ、ちゃんと気持ちいいかなっ……？」"

[[dialogue]]
speaker = "unk"
# とろんとした眼差しが俺を見つめてくる。上目遣いが可愛くて、そんな些細なことでもペニスへの刺激となってたまらない。
line = "とろんとした眼差しが俺を見つめてくる。上目遣いが可愛くて、そんな些細なことでもペニスへの刺激となってたまらない。"

[[dialogue]]
speaker = "ルルカ"
# 「ぁ、あ、ぁっ<emoji=heart04>　お腹の、んぅ、中で、おち○ぽビクビクって……はぁ、んんっ……喜んでくれてる、の……？<emoji=heart04>」
line = "「ぁ、あ、ぁっ<emoji=heart04>　お腹の、んぅ、中で、おち○ぽビクビクって……はぁ、んんっ……喜んでくれてる、の……？<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「嬉しいよ、ぉっ……お兄ちゃんが気持ちよくなってくれるの、嬉しいっ……んんっ、はぁ、あ、ああぁっ……んんっ……んぅ、ふぅ<emoji=heart04>」
line = "「嬉しいよ、ぉっ……お兄ちゃんが気持ちよくなってくれるの、嬉しいっ……んんっ、はぁ、あ、ああぁっ……んんっ……んぅ、ふぅ<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「おち○ぽ、いっぱい感じてね……？<emoji=heart04>　んんっ……あ、あっ<emoji=heart04>　先っぽから、根元まで、ぜんぶっ……ルルカの中でごしごし、して？」
line = "「おち○ぽ、いっぱい感じてね……？<emoji=heart04>　んんっ……あ、あっ<emoji=heart04>　先っぽから、根元まで、ぜんぶっ……ルルカの中でごしごし、して？」"

[[dialogue]]
speaker = "ルルカ"
# 「は、あぁ、ぁ、ぅっ……お兄ちゃんのお顔、気持ちよさそうっ……嬉しい、幸せぇっ……はぁ、んんぅ、んぁ、ぁ、あああっ……<emoji=heart04>」
line = "「は、あぁ、ぁ、ぅっ……お兄ちゃんのお顔、気持ちよさそうっ……嬉しい、幸せぇっ……はぁ、んんぅ、んぁ、ぁ、あああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ルルカも初めてで余裕はないはずなのに、彼女は俺の表情やペニスの反応にすごく気を配ってくれている。
line = "ルルカも初めてで余裕はないはずなのに、彼女は俺の表情やペニスの反応にすごく気を配ってくれている。"

[[dialogue]]
speaker = "unk"
# 常に周りを気遣うその姿勢は、動画配信者としての活動の癖なのか。それともルルカ自身の性格なのか。きっと両方だ。
line = "常に周りを気遣うその姿勢は、動画配信者としての活動の癖なのか。それともルルカ自身の性格なのか。きっと両方だ。"

[[dialogue]]
speaker = "ルルカ"
# 「んんっ……は、ぅあ、んんっ、んぅっ<emoji=heart04>　お兄ちゃん、もっと感じてるお顔、見せてっ……そのお顔、好きっ……好きぃっ<emoji=heart04>」
line = "「んんっ……は、ぅあ、んんっ、んぅっ<emoji=heart04>　お兄ちゃん、もっと感じてるお顔、見せてっ……そのお顔、好きっ……好きぃっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺が快感を得ることが、自分の喜びだとでも言いたげなルルカの言動。それがすごくすごく、いじらしくて──
line = "俺が快感を得ることが、自分の喜びだとでも言いたげなルルカの言動。それがすごくすごく、いじらしくて──"

[[dialogue]]
speaker = "unk"
# ピストンに合わせて揺れているおっぱいに思わず手を伸ばしてしまう。
line = "ピストンに合わせて揺れているおっぱいに思わず手を伸ばしてしまう。"

[[dialogue]]
speaker = "ルルカ"
# 「ひぁんっ<emoji=heart04>　んんっ……あっ……は、ぁうっんぅ<emoji=heart04>　あ、あっ……おっぱい、おっぱいも触ってくれてる、ぅ<emoji=heart04>」
line = "「ひぁんっ<emoji=heart04>　んんっ……あっ……は、ぁうっんぅ<emoji=heart04>　あ、あっ……おっぱい、おっぱいも触ってくれてる、ぅ<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「お兄ちゃんの手、あったかくて、大きくて──あんっ<emoji=heart04>　触り方も、優しいよぉっ……ぁぁぁあっ、お兄ちゃん好き、好きっ……<emoji=heart04>」
line = "「お兄ちゃんの手、あったかくて、大きくて──あんっ<emoji=heart04>　触り方も、優しいよぉっ……ぁぁぁあっ、お兄ちゃん好き、好きっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「お兄ちゃんに、んぁ、はぅっ……おっぱい、むにむにって、揉まれるの、ドキドキ、するよぅっ……んんぁ、ぅっ<emoji=heart04>」
line = "「お兄ちゃんに、んぁ、はぅっ……おっぱい、むにむにって、揉まれるの、ドキドキ、するよぅっ……んんぁ、ぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ルルカは小さいだなんて卑下していたけれど、そんなことはない。大好きな恋人のおっぱいを揉んで、興奮しない男がこの世にいるか。
line = "ルルカは小さいだなんて卑下していたけれど、そんなことはない。大好きな恋人のおっぱいを揉んで、興奮しない男がこの世にいるか。"

[[dialogue]]
speaker = "ルルカ"
# 「や、ぁ──んんんっ<emoji=heart04>　あ、ふうぅあっ……おち○ぽ、また太く、なった、ぁっ……？　な、なんでっ……？」
line = "「や、ぁ──んんんっ<emoji=heart04>　あ、ふうぅあっ……おち○ぽ、また太く、なった、ぁっ……？　な、なんでっ……？」"

[[dialogue]]
speaker = "クロト"
# 「ルルカのおっぱいで、興奮したんだ」
line = "「ルルカのおっぱいで、興奮したんだ」"

[[dialogue]]
speaker = "ルルカ"
# 「んんぅ～～っ<emoji=heart04>　あ、ああ、あっ<emoji=heart04>　ほんと？　やったぁ<emoji=heart04>　んんっ<emoji=heart04>　あたしのおっぱいで、おち○ぽ喜んでくれたんだぁっ……<emoji=heart04>」
line = "「んんぅ～～っ<emoji=heart04>　あ、ああ、あっ<emoji=heart04>　ほんと？　やったぁ<emoji=heart04>　んんっ<emoji=heart04>　あたしのおっぱいで、おち○ぽ喜んでくれたんだぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「嬉しいよぉっ……ありがとっ、あ、んぁ、お兄ちゃんっ……ふぅ、んんっ<emoji=heart04>」
line = "「嬉しいよぉっ……ありがとっ、あ、んぁ、お兄ちゃんっ……ふぅ、んんっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「俺ばっかり楽しんじゃってる気がするけど……ルルカも嬉しいのか？」
line = "「俺ばっかり楽しんじゃってる気がするけど……ルルカも嬉しいのか？」"

[[dialogue]]
speaker = "ルルカ"
# 「嬉しい、よぉっ……<emoji=heart04>　恋人の、お兄ちゃんがっ……ん、あっ<emoji=heart04>　あたしの体で、興奮してくれるの、う、嬉しいっ……は、ぁ、んぅ<emoji=heart04>」
line = "「嬉しい、よぉっ……<emoji=heart04>　恋人の、お兄ちゃんがっ……ん、あっ<emoji=heart04>　あたしの体で、興奮してくれるの、う、嬉しいっ……は、ぁ、んぅ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「──っ」
line = "「──っ」"

[[dialogue]]
speaker = "unk"
# 背筋にぞぞぞっと電流が走る。性の快感だけじゃない。ルルカが向けてくれる愛情が、気持ちいいんだ。
line = "背筋にぞぞぞっと電流が走る。性の快感だけじゃない。ルルカが向けてくれる愛情が、気持ちいいんだ。"

[[dialogue]]
speaker = "クロト"
# 「──ルルカっ」
line = "「──ルルカっ」"

[[dialogue]]
speaker = "unk"
# 興奮が一気にせりあがった俺は、ルルカの唇を奪った。
line = "興奮が一気にせりあがった俺は、ルルカの唇を奪った。"

[[dialogue]]
speaker = "ルルカ"
# 「んぅちゅぅっ<emoji=heart04>　んむぅっ<emoji=heart04>　ちゅるう、れぇ、んちゅるっ、ちゅぅんちゅ、ちゅぱ、んぢゅるぅっ<emoji=heart04>」
line = "「んぅちゅぅっ<emoji=heart04>　んむぅっ<emoji=heart04>　ちゅるう、れぇ、んちゅるっ、ちゅぅんちゅ、ちゅぱ、んぢゅるぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ピストンを強めながら、ルルカとめちゃくちゃに舌を絡める。
line = "ピストンを強めながら、ルルカとめちゃくちゃに舌を絡める。"

[[dialogue]]
speaker = "ルルカ"
# 「んちゅっ……ぷぁあ<emoji=heart04>　お兄ちゃんと繋がりながらキス、んんぅっ……ぢゅ、んちゅる、れぇ、ちゅる、んんちゅるっ、んちゅるぅ<emoji=heart04>」
line = "「んちゅっ……ぷぁあ<emoji=heart04>　お兄ちゃんと繋がりながらキス、んんぅっ……ぢゅ、んちゅる、れぇ、ちゅる、んんちゅるっ、んちゅるぅ<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「これしゅきぃっ……んんちゅるっ<emoji=heart04>　気持ちいぃ、んんっ、お兄ちゃあんっ……ちゅるぅ、んるちゅる、れるれる、んちゅうぅ～っ<emoji=heart04>」
line = "「これしゅきぃっ……んんちゅるっ<emoji=heart04>　気持ちいぃ、んんっ、お兄ちゃあんっ……ちゅるぅ、んるちゅる、れるれる、んちゅうぅ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 深いキスをするたびに、ルルカの女性器が小刻みに締まり、ペニスに快感を送ってくる。
line = "深いキスをするたびに、ルルカの女性器が小刻みに締まり、ペニスに快感を送ってくる。"

[[dialogue]]
speaker = "unk"
# ピストンしづらいほどにきつく締まる蜜穴を何度も穿ち、舌を絡めていく。
line = "ピストンしづらいほどにきつく締まる蜜穴を何度も穿ち、舌を絡めていく。"

[[dialogue]]
speaker = "ルルカ"
# 「れぇれる、んちゅるっ<emoji=heart04>　しゅき、しゅきぃっ……んんぅ、ちゅるうる、お兄ちゃん、好きぃ、んちゅるっ……<emoji=heart04>」
line = "「れぇれる、んちゅるっ<emoji=heart04>　しゅき、しゅきぃっ……んんぅ、ちゅるうる、お兄ちゃん、好きぃ、んちゅるっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 舌を差し入れれば、夢中で絡め返してくれる、年下の可愛い彼女が愛おしくて仕方がない。
line = "舌を差し入れれば、夢中で絡め返してくれる、年下の可愛い彼女が愛おしくて仕方がない。"

[[dialogue]]
speaker = "クロト"
# 「俺も好きだ、好きだぞ、ルルカっ……！」
line = "「俺も好きだ、好きだぞ、ルルカっ……！」"

[[dialogue]]
speaker = "ルルカ"
# 「んんううっ<emoji=heart04>　ちゅぱ、んちゅるぅ<emoji=heart04>　うんっ……あたしもしゅき、キスしゅきっ<emoji=heart04>　んん、ぱんぱんも、好きぃ<emoji=heart04>　幸せっ……<emoji=heart04>」
line = "「んんううっ<emoji=heart04>　ちゅぱ、んちゅるぅ<emoji=heart04>　うんっ……あたしもしゅき、キスしゅきっ<emoji=heart04>　んん、ぱんぱんも、好きぃ<emoji=heart04>　幸せっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「ちゅぱ、れろっ、んちゅるう、んじゅるっ、ちゅるちゅぱっ、れぇ、れるれる、んちゅるぅっ……<emoji=heart04>」
line = "「ちゅぱ、れろっ、んちゅるう、んじゅるっ、ちゅるちゅぱっ、れぇ、れるれる、んちゅるぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ルルカの体はどこもかしこも、温かくて柔らかい。汗と一緒にたちのぼるルルカの香りは、くらくらするほどに魅力的だった。
line = "ルルカの体はどこもかしこも、温かくて柔らかい。汗と一緒にたちのぼるルルカの香りは、くらくらするほどに魅力的だった。"

[[dialogue]]
speaker = "ルルカ"
# 「んんぅ、ふぅっ……んちゅるうー、れろっ……お兄ちゃん、おち○ぽ、すっごく震えて、きてる、よっ……？　んちゅるっ<emoji=heart04>」
line = "「んんぅ、ふぅっ……んちゅるうー、れろっ……お兄ちゃん、おち○ぽ、すっごく震えて、きてる、よっ……？　んちゅるっ<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「イ、イキたくなったら、好きな時にっ……ちゅぱ、んちゅるっ、好きなところに出していいから──ね？<emoji=heart04>」
line = "「イ、イキたくなったら、好きな時にっ……ちゅぱ、んちゅるっ、好きなところに出していいから──ね？<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ぞくぞくと昂ってきていたところへ、そんなことを言われたら──
line = "ぞくぞくと昂ってきていたところへ、そんなことを言われたら──"

[[dialogue]]
speaker = "ルルカ"
# 「ひっ、あ、あ、あ、あぁっ！<emoji=heart04>　激しっ<emoji=heart04>　んんんっ<emoji=heart04>　お兄ちゃんっ、激しいっ、おち○ぽ激しいよぉおっ<emoji=heart04>」
line = "「ひっ、あ、あ、あ、あぁっ！<emoji=heart04>　激しっ<emoji=heart04>　んんんっ<emoji=heart04>　お兄ちゃんっ、激しいっ、おち○ぽ激しいよぉおっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 繋いだ手にぎゅううっと力を込めたまま、腰を突き上げてルルカの体を弾ませる。
line = "繋いだ手にぎゅううっと力を込めたまま、腰を突き上げてルルカの体を弾ませる。"

[[dialogue]]
speaker = "unk"
# お尻を抱きかかえるようにして突き上げるピストンだ。
line = "お尻を抱きかかえるようにして突き上げるピストンだ。"

[[dialogue]]
speaker = "ルルカ"
# 「あんっ<emoji=heart04>　あっあっ、ふあんっ<emoji=heart04>　んんぅっ<emoji=heart04>　んぁっ、あぅ、んっ、んんっんっんぅ！<emoji=heart04>」
line = "「あんっ<emoji=heart04>　あっあっ、ふあんっ<emoji=heart04>　んんぅっ<emoji=heart04>　んぁっ、あぅ、んっ、んんっんっんぅ！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# とろとろに濡れそぼった女性器にピストンを続け、ピンク色にとがったルルカの乳首を指でこね回す。
line = "とろとろに濡れそぼった女性器にピストンを続け、ピンク色にとがったルルカの乳首を指でこね回す。"

[[dialogue]]
speaker = "ルルカ"
# 「ひぅううっ<emoji=heart04>　んっ、んんぅーっ<emoji=heart04>　あっあっあっ<emoji=heart04>　おっぱい、そこ、ひやぁぁ、ぁあ～っ<emoji=heart04>　んんぅっ、はぁああっ<emoji=heart04>」
line = "「ひぅううっ<emoji=heart04>　んっ、んんぅーっ<emoji=heart04>　あっあっあっ<emoji=heart04>　おっぱい、そこ、ひやぁぁ、ぁあ～っ<emoji=heart04>　んんぅっ、はぁああっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「う、くぅっ……中が、すごく締まって……！」
line = "「う、くぅっ……中が、すごく締まって……！」"

[[dialogue]]
speaker = "ルルカ"
# 「乳首、だ、ダメだよぉ、お兄ちゃん、ひぁ、あぁあっ<emoji=heart04>　それ気持ちいいっ、ふう、んんぅんぁ、あぁあっ<emoji=heart04>」
line = "「乳首、だ、ダメだよぉ、お兄ちゃん、ひぁ、あぁあっ<emoji=heart04>　それ気持ちいいっ、ふう、んんぅんぁ、あぁあっ<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「感じすぎちゃうからっ、感じすぎちゃうからぁっ、んぁあ！<emoji=heart04>　ぴんぴんダメぇっ<emoji=heart04>　あっあっあっ、んんっ、んんぅ～っ<emoji=heart04>」
line = "「感じすぎちゃうからっ、感じすぎちゃうからぁっ、んぁあ！<emoji=heart04>　ぴんぴんダメぇっ<emoji=heart04>　あっあっあっ、んんっ、んんぅ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ルルカが感じてくれると、俺も幸せなんだ。いっぱい気持ちよくなって」
line = "「ルルカが感じてくれると、俺も幸せなんだ。いっぱい気持ちよくなって」"

[[dialogue]]
speaker = "unk"
# 指でつまんでくりくりと刺激しながら、真下からペニスで可愛いルルカを串刺しにする。
line = "指でつまんでくりくりと刺激しながら、真下からペニスで可愛いルルカを串刺しにする。"

[[dialogue]]
speaker = "ルルカ"
# 「ふぅう～っ、んん、んくぅうぅ～っ……！<emoji=heart04>　あっ、はぁあっ、ふぅうっ、んぁ、はぁあ、んぁ、ぁう、んんぅっ！<emoji=heart04>」
line = "「ふぅう～っ、んん、んくぅうぅ～っ……！<emoji=heart04>　あっ、はぁあっ、ふぅうっ、んぁ、はぁあ、んぁ、ぁう、んんぅっ！<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「お、お兄ちゃんも、同じ気持ち、なんだっ……<emoji=heart04>　大好きな人が気持ちよくなってくれたら、し、幸せっ、なるの……？」
line = "「お、お兄ちゃんも、同じ気持ち、なんだっ……<emoji=heart04>　大好きな人が気持ちよくなってくれたら、し、幸せっ、なるの……？」"

[[dialogue]]
speaker = "unk"
# 頷いて、はち切れそうなペニスをルルカの中で擦り上げ、シゴきたてる。
line = "頷いて、はち切れそうなペニスをルルカの中で擦り上げ、シゴきたてる。"

[[dialogue]]
speaker = "ルルカ"
# 「あ、ぁ、あ、あ、ぁ、あっ<emoji=heart04>　じゃ、じゃあっ、なろ<emoji=heart04>　一緒に幸せになろっ<emoji=heart04>　んん、ふぅ、んんんっ<emoji=heart04>」
line = "「あ、ぁ、あ、あ、ぁ、あっ<emoji=heart04>　じゃ、じゃあっ、なろ<emoji=heart04>　一緒に幸せになろっ<emoji=heart04>　んん、ふぅ、んんんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「気持ちよくなって<emoji=heart04>　いっぱいイって<emoji=heart04>　びゅうびゅうって、してっ、して、してっ──あ、ぁ、ぁ、ぁ、ぁ、ぁ、ぁ──<emoji=heart04>」
line = "「気持ちよくなって<emoji=heart04>　いっぱいイって<emoji=heart04>　びゅうびゅうって、してっ、して、してっ──あ、ぁ、ぁ、ぁ、ぁ、ぁ、ぁ──<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 射精の準備が整う。ペニスをぞくぞくと登ってきて、もう歯を食いしばっても押しとどめられない。出る、出る、出る──
line = "射精の準備が整う。ペニスをぞくぞくと登ってきて、もう歯を食いしばっても押しとどめられない。出る、出る、出る──"

[[dialogue]]
speaker = "ルルカ"
# 「出してっ<emoji=heart04>　お兄ちゃん、出してっ<emoji=heart04>　あたしの中に射精してっ<emoji=heart04>　好きっ<emoji=heart04>　好き好きっ、好きぃっ……！<emoji=heart04>」
line = "「出してっ<emoji=heart04>　お兄ちゃん、出してっ<emoji=heart04>　あたしの中に射精してっ<emoji=heart04>　好きっ<emoji=heart04>　好き好きっ、好きぃっ……！<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「ふあぁぁっ……ひゃぁあぁああぁあああぁああぁああ～～～～～～っ……！！<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「ふあぁぁっ……ひゃぁあぁああぁあああぁああぁああ～～～～～～っ……！！<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「んんぅっ、ふぁあ、ぁ、あぁああ～っ……出てるぅっ……いっぱい、ぁ、は──んんぅっ……<emoji=heart04>」
line = "「んんぅっ、ふぁあ、ぁ、あぁああ～っ……出てるぅっ……いっぱい、ぁ、は──んんぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 魂まで一緒に飛び出ていきそうなほどの射精が止まらない。
line = "魂まで一緒に飛び出ていきそうなほどの射精が止まらない。"

[[dialogue]]
speaker = "ルルカ"
# 「ひ、ひぅうっ<emoji=heart04>　んうぁあっ<emoji=heart04>　勢い、すごっ……んんぅっ……すごいよぉおっ……あ、ぁあ、まだ出てっ……ふぅう～っ……<emoji=heart04>」
line = "「ひ、ひぅうっ<emoji=heart04>　んうぁあっ<emoji=heart04>　勢い、すごっ……んんぅっ……すごいよぉおっ……あ、ぁあ、まだ出てっ……ふぅう～っ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# いつも動画配信で聴いている大好きな声が、俺の射精を受けて艶っぽくなっている。
line = "いつも動画配信で聴いている大好きな声が、俺の射精を受けて艶っぽくなっている。"

[[dialogue]]
speaker = "ルルカ"
# 「はぁっ、ぁ、あぁあ──好き、好きぃっ……お兄ちゃんっ……<emoji=heart04>　んんぅっ……<emoji=heart04>」
line = "「はぁっ、ぁ、あぁあ──好き、好きぃっ……お兄ちゃんっ……<emoji=heart04>　んんぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# とろけるような喘ぎ声を耳元で聴きながらの長い長い射精が──ようやく終わった。
line = "とろけるような喘ぎ声を耳元で聴きながらの長い長い射精が──ようやく終わった。"

[[dialogue]]
speaker = "ルルカ"
# 「んんっ……はぁあっ……はぁあぁあーっ……ふぅううーっ……<emoji=heart04>」
line = "「んんっ……はぁあっ……はぁあぁあーっ……ふぅううーっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「お、男の人って……こ、こんなに……すごいん、だね……？　お兄ちゃんのおち○ぽ、ずぅっとビクビクしてたぁ……<emoji=heart04>」
line = "「お、男の人って……こ、こんなに……すごいん、だね……？　お兄ちゃんのおち○ぽ、ずぅっとビクビクしてたぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「こんなに出たの、初めてだ……」
line = "「こんなに出たの、初めてだ……」"

[[dialogue]]
speaker = "ルルカ"
# 「そ、それって……？」
line = "「そ、それって……？」"

[[dialogue]]
speaker = "クロト"
# 「俺の恋人が可愛すぎて、止まらなかった」
line = "「俺の恋人が可愛すぎて、止まらなかった」"

[[dialogue]]
speaker = "ルルカ"
# 「えへ、へへへぇっ……良かったぁ……お兄ちゃん、あたしとのエッチで、そんなに喜んでくれたんだ……<emoji=heart04>」
line = "「えへ、へへへぇっ……良かったぁ……お兄ちゃん、あたしとのエッチで、そんなに喜んでくれたんだ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 射精を一区切りに、いったんセックスは終わり……なんだろうけど。
line = "射精を一区切りに、いったんセックスは終わり……なんだろうけど。"

[[dialogue]]
speaker = "unk"
# 俺もルルカも、ぎゅっと抱き合って余韻に浸っていた。
line = "俺もルルカも、ぎゅっと抱き合って余韻に浸っていた。"

[[dialogue]]
speaker = "ルルカ"
# 「ねぇ、お兄ちゃん……これからも、ずっと一緒にいてね……？」
line = "「ねぇ、お兄ちゃん……これからも、ずっと一緒にいてね……？」"

[[dialogue]]
speaker = "クロト"
# 「もちろん。ずっと支えるよ。恋人としても、Ｖチューバーのサポーターとしても」
line = "「もちろん。ずっと支えるよ。恋人としても、Ｖチューバーのサポーターとしても」"

[[dialogue]]
speaker = "ルルカ"
# 「うん……<emoji=heart04>　あたしもお兄ちゃんのこと、ず～っと支えるね。約束……<emoji=heart04>」
line = "「うん……<emoji=heart04>　あたしもお兄ちゃんのこと、ず～っと支えるね。約束……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# お互いの気持ちを確かめ合うように、繋いだ手に力を込める。
line = "お互いの気持ちを確かめ合うように、繋いだ手に力を込める。"

[[dialogue]]
speaker = "unk"
# 汗だくになったまま、手を固く握りあったまま、俺たちはピロートークを続けるのだった──
line = "汗だくになったまま、手を固く握りあったまま、俺たちはピロートークを続けるのだった──"
