[[dialogue]]
speaker = "unk"
# 第４話,貴方にチョコを,P
line = "第４話,貴方にチョコを,P"

[[dialogue]]
speaker = "unk"
# 蘭美とデートに出かける仲になってから、しばらく経ったある日のこと。彼女が俺の家へ遊びに来ることになった――
line = "蘭美とデートに出かける仲になってから、しばらく経ったある日のこと。彼女が俺の家へ遊びに来ることになった――"

[[dialogue]]
speaker = "蘭美"
# 「お邪魔しま～す。ここが会長の家ね♪」
line = "「お邪魔しま～す。ここが会長の家ね♪」"

[[dialogue]]
speaker = "蘭美"
# 「今日は会長のお母様、仕事でいらっしゃらないのよね？　会ってみたかったけど、残念だわ。挨拶はまた次の機会ね」
line = "「今日は会長のお母様、仕事でいらっしゃらないのよね？　会ってみたかったけど、残念だわ。挨拶はまた次の機会ね」"

[[dialogue]]
speaker = "蘭美"
# 「それで、言っていた通り、今日は前にオススメしてたボードゲームを沢山持ってきたわ」
line = "「それで、言っていた通り、今日は前にオススメしてたボードゲームを沢山持ってきたわ」"

[[dialogue]]
speaker = "蘭美"
# 「ルールは教えるから、対戦しましょ♪」
line = "「ルールは教えるから、対戦しましょ♪」"

[[dialogue]]
speaker = "蘭美"
# 「おっ、そうきたわね。私は次の手番、どうしようかしら？」
line = "「おっ、そうきたわね。私は次の手番、どうしようかしら？」"

[[dialogue]]
speaker = "蘭美"
# 「って、会長、どうしたの？　なにか気になることでもあるの？」
line = "「って、会長、どうしたの？　なにか気になることでもあるの？」"

[[dialogue]]
speaker = "蘭美"
# 「――隣に座って、手を繋いでボードゲームしてるのが、変な感じ？」
line = "「――隣に座って、手を繋いでボードゲームしてるのが、変な感じ？」"

[[dialogue]]
speaker = "蘭美"
# 「一応、今日は家デートという名目で来ているんだもの。外のデートでも手は繋いで歩いたりするんだし、別におかしくはないでしょう？」
line = "「一応、今日は家デートという名目で来ているんだもの。外のデートでも手は繋いで歩いたりするんだし、別におかしくはないでしょう？」"

[[dialogue]]
speaker = "蘭美"
# 「――ふふっ♪　そうよ。だから、この天才飛び級美少女と手を繋げること、光栄に思いなさい？」
line = "「――ふふっ♪　そうよ。だから、この天才飛び級美少女と手を繋げること、光栄に思いなさい？」"

[[dialogue]]
speaker = "unk"
# （距離感が近すぎる気もするけど……）
line = "（距離感が近すぎる気もするけど……）"

[[dialogue]]
speaker = "unk"
# 蘭美が楽しそうならそれでもいいか、と思う俺なのだった。
line = "蘭美が楽しそうならそれでもいいか、と思う俺なのだった。"

[[dialogue]]
speaker = "蘭美"
# 「ん～！　結構長い時間続けてボードゲームやってたし、一旦休憩しましょうか」
line = "「ん～！　結構長い時間続けてボードゲームやってたし、一旦休憩しましょうか」"

[[dialogue]]
speaker = "蘭美"
# 「そうだわ、会長。実は今日、私、サプライズを用意してきたの」
line = "「そうだわ、会長。実は今日、私、サプライズを用意してきたの」"

[[dialogue]]
speaker = "蘭美"
# 「はい、これ♪」
line = "「はい、これ♪」"

[[dialogue]]
speaker = "unk"
# これは……もしかしてチョコレート？
line = "これは……もしかしてチョコレート？"

[[dialogue]]
speaker = "蘭美"
# 「そう、バレンタインチョコよ♪　――時期はもう過ぎてるのに、どうしてかって？」
line = "「そう、バレンタインチョコよ♪　――時期はもう過ぎてるのに、どうしてかって？」"

[[dialogue]]
speaker = "蘭美"
# 「ほら、この前のバレンタインの時は、まだ知り合ったばかりだったし、せつなのチョコ作りを手伝ったりで、渡しそびれちゃったでしょ？」
line = "「ほら、この前のバレンタインの時は、まだ知り合ったばかりだったし、せつなのチョコ作りを手伝ったりで、渡しそびれちゃったでしょ？」"

[[dialogue]]
speaker = "蘭美"
# 「それで、最近はデートに行くようにもなって……結構親しくなってきたじゃない？　だから――」
line = "「それで、最近はデートに行くようにもなって……結構親しくなってきたじゃない？　だから――」"

[[dialogue]]
speaker = "蘭美"
# 「大分遅れてではあるけど、作ってみたのよ。というわけで、あげるわ♪」
line = "「大分遅れてではあるけど、作ってみたのよ。というわけで、あげるわ♪」"

[[dialogue]]
speaker = "unk"
# ありがとう。すごく嬉しい
line = "ありがとう。すごく嬉しい"

[[dialogue]]
speaker = "蘭美"
# 「ん……♪　光栄に思って、受け取りなさい」
line = "「ん……♪　光栄に思って、受け取りなさい」"

[[dialogue]]
speaker = "蘭美"
# 「って、なに？　もう食べるの？」
line = "「って、なに？　もう食べるの？」"

[[dialogue]]
speaker = "蘭美"
# 「――せっかくだから？　まぁ……私も作った手前、反応は気になるしね」
line = "「――せっかくだから？　まぁ……私も作った手前、反応は気になるしね」"

[[dialogue]]
speaker = "蘭美"
# 「一応、この私が気合いを入れて、メイドとしての料理スキルを駆使して作ったものだから、味は保証するわよ」
line = "「一応、この私が気合いを入れて、メイドとしての料理スキルを駆使して作ったものだから、味は保証するわよ」"

[[dialogue]]
speaker = "unk"
# 俺はバレンタインチョコの封を開けて、食べてみる。
line = "俺はバレンタインチョコの封を開けて、食べてみる。"

[[dialogue]]
speaker = "蘭美"
# 「……どう？」
line = "「……どう？」"

[[dialogue]]
speaker = "unk"
# うまい！　さすが蘭美の作ったチョコだ
line = "うまい！　さすが蘭美の作ったチョコだ"

[[dialogue]]
speaker = "蘭美"
# 「そう。よかったわ。ふふっ……♪」
line = "「そう。よかったわ。ふふっ……♪」"

[[dialogue]]
speaker = "蘭美"
# 「って、んっ……<emoji=heart04>　い、いきなり頭を撫でたりして、なに？」
line = "「って、んっ……<emoji=heart04>　い、いきなり頭を撫でたりして、なに？」"

[[dialogue]]
speaker = "蘭美"
# 「これも男女のデートのスキンシップ？　私のこと、褒めてくれてるわけ？」
line = "「これも男女のデートのスキンシップ？　私のこと、褒めてくれてるわけ？」"

[[dialogue]]
speaker = "蘭美"
# 「ま、まぁ、別に悪い気分はしないけど……♪」
line = "「ま、まぁ、別に悪い気分はしないけど……♪」"

[[dialogue]]
speaker = "unk"
# 蘭美は長い耳はぴょこんと持ち上がらせ、機嫌よさそうに呟くのだった。
line = "蘭美は長い耳はぴょこんと持ち上がらせ、機嫌よさそうに呟くのだった。"

[[dialogue]]
speaker = "unk"
# ２人でいる時間はあっという間に過ぎ、気づけばもう日が暮れて、遅い時間になっていた。
line = "２人でいる時間はあっという間に過ぎ、気づけばもう日が暮れて、遅い時間になっていた。"

[[dialogue]]
speaker = "蘭美"
# 「そろそろ帰らないといけないわね。今日はなかなか楽しかったわ」
line = "「そろそろ帰らないといけないわね。今日はなかなか楽しかったわ」"

[[dialogue]]
speaker = "蘭美"
# 「――ん？　なに、会長？　バレンタインチョコがどうかしたの？」
line = "「――ん？　なに、会長？　バレンタインチョコがどうかしたの？」"

[[dialogue]]
speaker = "unk"
# 今度、お返しにクッキーを作るよ
line = "今度、お返しにクッキーを作るよ"

[[dialogue]]
speaker = "蘭美"
# 「……！　それって、ホワイトデーの……？」
line = "「……！　それって、ホワイトデーの……？」"

[[dialogue]]
speaker = "蘭美"
# 「――ふふっ……♪　なら、期待しているわね♪」
line = "「――ふふっ……♪　なら、期待しているわね♪」"

[[dialogue]]
speaker = "蘭美"
# 「あっ、会長。ちょっと屈んでみなさい。頭に埃が付いてるわよ。取ってあげるわ」
line = "「あっ、会長。ちょっと屈んでみなさい。頭に埃が付いてるわよ。取ってあげるわ」"

[[dialogue]]
speaker = "蘭美"
# 「ちゅっ……<emoji=heart04>」
line = "「ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# えっ！？　い、いま頬っぺたに……！？
line = "えっ！？　い、いま頬っぺたに……！？"

[[dialogue]]
speaker = "蘭美"
# 「――ふふっ……♪　これもまた、男女のスキンシップよ」
line = "「――ふふっ……♪　これもまた、男女のスキンシップよ」"

[[dialogue]]
speaker = "蘭美"
# 「また明日、学園でね。会長♪」
line = "「また明日、学園でね。会長♪」"

[[dialogue]]
speaker = "unk"
# 少し照れた笑顔を浮かべて、蘭美は帰っていく。
line = "少し照れた笑顔を浮かべて、蘭美は帰っていく。"

[[dialogue]]
speaker = "unk"
# 残された俺は、頬に残った熱に手で触れながら、しばらくドキドキしてしまうのだった――
line = "残された俺は、頬に残った熱に手で触れながら、しばらくドキドキしてしまうのだった――"
