[[dialogue]]
speaker = "unk"
# 第３話,カジノに舞い降りた王子様,P
line = "第３話,カジノに舞い降りた王子様,P"

[[dialogue]]
speaker = "ユーリス"
# 「まさかまた会長と一緒にカジノのアルバイトをすることができるなんてね。すごく嬉しいよ」
line = "「まさかまた会長と一緒にカジノのアルバイトをすることができるなんてね。すごく嬉しいよ」"

[[dialogue]]
speaker = "ユーリス"
# 「ヘレナさんも褒めてたよ？　会長のカード捌きが見違えるほど上手になっていたって。今日はテーブル１つ丸々任せられたんだってね？」
line = "「ヘレナさんも褒めてたよ？　会長のカード捌きが見違えるほど上手になっていたって。今日はテーブル１つ丸々任せられたんだってね？」"

[[dialogue]]
speaker = "unk"
# ユーリスが特訓に付き合ってくれたおかげさ
line = "ユーリスが特訓に付き合ってくれたおかげさ"

[[dialogue]]
speaker = "ユーリス"
# 「会長の筋が良かったからだよ。私が教えなくてもすぐに上達していたさ」
line = "「会長の筋が良かったからだよ。私が教えなくてもすぐに上達していたさ」"

[[dialogue]]
speaker = "ユーリス"
# 「でも……なんだかヤキモチ焼いちゃうな。これから会長がたくさんの女性を相手に華麗なカード捌きを披露すると思うと」
line = "「でも……なんだかヤキモチ焼いちゃうな。これから会長がたくさんの女性を相手に華麗なカード捌きを披露すると思うと」"

[[dialogue]]
speaker = "ユーリス"
# 「きっと黄色い声援で店が溢れちゃうだろうね。モテてモテて仕方なくなっちゃうと思う……」
line = "「きっと黄色い声援で店が溢れちゃうだろうね。モテてモテて仕方なくなっちゃうと思う……」"

[[dialogue]]
speaker = "ユーリス"
# 「って、あはは。ダメだね、こんなヤキモチ焼きじゃ。会長と一緒にいるとついつい女の子に戻ってしまうよ」
line = "「って、あはは。ダメだね、こんなヤキモチ焼きじゃ。会長と一緒にいるとついつい女の子に戻ってしまうよ」"

[[dialogue]]
speaker = "ユーリス"
# 「よし、切り替えて仕事仕事。あ……でも私がつくテーブルは会長よりも前にしておいてくれないかな？　女の子に囲まれる会長を見てしまったら集中できそうになくて」
line = "「よし、切り替えて仕事仕事。あ……でも私がつくテーブルは会長よりも前にしておいてくれないかな？　女の子に囲まれる会長を見てしまったら集中できそうになくて」"

[[dialogue]]
speaker = "ユーリス"
# 「ありがとう。それじゃお互いに頑張ろっか。バイトが終わったら、また２人で何か美味しいものでも食べに行こう」
line = "「ありがとう。それじゃお互いに頑張ろっか。バイトが終わったら、また２人で何か美味しいものでも食べに行こう」"

[[dialogue]]
speaker = "ユーリス"
# 「ふぅ、お疲れ様。まさかこんなに忙しいとは思わなかったね。以前の数倍はテーブルにお客さんが来てたよ」
line = "「ふぅ、お疲れ様。まさかこんなに忙しいとは思わなかったね。以前の数倍はテーブルにお客さんが来てたよ」"

[[dialogue]]
speaker = "ユーリス"
# 「でも今日のお客さんたちは実に楽しそうだったね。私がカードを配るだけで大歓声をあげて」
line = "「でも今日のお客さんたちは実に楽しそうだったね。私がカードを配るだけで大歓声をあげて」"

[[dialogue]]
speaker = "ユーリス"
# 「そんなに名勝負が多かったのかな──って会長？　何をむくれているんだい？」
line = "「そんなに名勝負が多かったのかな──って会長？　何をむくれているんだい？」"

[[dialogue]]
speaker = "unk"
# 大層モテモテだったご様子で
line = "大層モテモテだったご様子で"

[[dialogue]]
speaker = "ユーリス"
# 「え……そうかな？　確かに繁盛していたとは思うけど。会長のテーブルもそうだったんじゃないの？」
line = "「え……そうかな？　確かに繁盛していたとは思うけど。会長のテーブルもそうだったんじゃないの？」"

[[dialogue]]
speaker = "ユーリス"
# 「へ、私のテーブルだけ？　言われてみれば妙に女性客が多かったような……。普通に進行していただけのつもりだけど」
line = "「へ、私のテーブルだけ？　言われてみれば妙に女性客が多かったような……。普通に進行していただけのつもりだけど」"

[[dialogue]]
speaker = "ユーリス"
# 「ヘレナさんが言ってたことも本当だったのかな。元々は私目当ての女性客が多いからバイトに入って欲しいって話だったんだよ」
line = "「ヘレナさんが言ってたことも本当だったのかな。元々は私目当ての女性客が多いからバイトに入って欲しいって話だったんだよ」"

[[dialogue]]
speaker = "ユーリス"
# 「でもそれだけ男に見えてるのなら良かった。最近、女の自分が顔を出し過ぎている気がしてたからね」
line = "「でもそれだけ男に見えてるのなら良かった。最近、女の自分が顔を出し過ぎている気がしてたからね」"

[[dialogue]]
speaker = "ユーリス"
# 「それに、ふふ。私のことで妬いてくれる会長の姿も見られたし」
line = "「それに、ふふ。私のことで妬いてくれる会長の姿も見られたし」"

[[dialogue]]
speaker = "unk"
# 一体どんな風に接客してたんだ？
line = "一体どんな風に接客してたんだ？"

[[dialogue]]
speaker = "ユーリス"
# 「何も変わったことはしていないよ？　普通に進行していただけだってば」
line = "「何も変わったことはしていないよ？　普通に進行していただけだってば」"

[[dialogue]]
speaker = "ユーリス"
# 「もちろんお客さんが緊張していたら始める前にフォローを入れたりはするけれど。ゲームを楽しんでもらいたいからね」
line = "「もちろんお客さんが緊張していたら始める前にフォローを入れたりはするけれど。ゲームを楽しんでもらいたいからね」"

[[dialogue]]
speaker = "ユーリス"
# 「試しにやってみようか？　会長、テーブルに着いてくれる？」
line = "「試しにやってみようか？　会長、テーブルに着いてくれる？」"

[[dialogue]]
speaker = "ユーリス"
# 「ハロー。ふふ、カジノは初めて？　ちょっぴり顔が強ばっていたものだから。あまり緊張しないで楽しんでもらえると嬉しいよ」
line = "「ハロー。ふふ、カジノは初めて？　ちょっぴり顔が強ばっていたものだから。あまり緊張しないで楽しんでもらえると嬉しいよ」"

[[dialogue]]
speaker = "ユーリス"
# 「あはは、それでも震えがとまらないみたいだね。なら私が魔法をかけてあげよう」
line = "「あはは、それでも震えがとまらないみたいだね。なら私が魔法をかけてあげよう」"

[[dialogue]]
speaker = "ユーリス"
# 「さ、そのカードをめくって？　大丈夫。まだ賭けは始まってないから。それは君に安心してもらうための私からの贈り物さ」
line = "「さ、そのカードをめくって？　大丈夫。まだ賭けは始まってないから。それは君に安心してもらうための私からの贈り物さ」"

[[dialogue]]
speaker = "ユーリス"
# 「ハートのキング──……それを私だと思って懐に忍ばせておいて？　君がまた震えそうになった時にぎゅっと体を抱き締めてあげるから」
line = "「ハートのキング──……それを私だと思って懐に忍ばせておいて？　君がまた震えそうになった時にぎゅっと体を抱き締めてあげるから」"

[[dialogue]]
speaker = "ユーリス"
# 「ああカードは絶対にポケットから出しちゃダメだよ？　イカサマと勘違いされたら大変だ。それに……」
line = "「ああカードは絶対にポケットから出しちゃダメだよ？　イカサマと勘違いされたら大変だ。それに……」"

[[dialogue]]
speaker = "ユーリス"
# 「それに、君の体から離されてしまったら、君のことを抱き締めてあげられなくなっちゃう。魔法をかけてあげられなくなってしまうからね」
line = "「それに、君の体から離されてしまったら、君のことを抱き締めてあげられなくなっちゃう。魔法をかけてあげられなくなってしまうからね」"

[[dialogue]]
speaker = "ユーリス"
# 「さて。もう震えはとまったかな？　ふふ、それじゃあ私と一緒に楽しくゲームに興じよう」
line = "「さて。もう震えはとまったかな？　ふふ、それじゃあ私と一緒に楽しくゲームに興じよう」"

[[dialogue]]
speaker = "ユーリス"
# 「Ｐｌａｃｅ　ｙｏｕｒ　ｂｅｔｓ　ｐｌｅａｓｅ──おっとその前に。本日は当カジノへようこそ。歓迎させてもらうよ」
line = "「Ｐｌａｃｅ　ｙｏｕｒ　ｂｅｔｓ　ｐｌｅａｓｅ──おっとその前に。本日は当カジノへようこそ。歓迎させてもらうよ」"

[[dialogue]]
speaker = "unk"
# 惚れてまうやろ～！？
line = "惚れてまうやろ～！？"

[[dialogue]]
speaker = "ユーリス"
# 「わわっ！？　な、なんだい、その口調……！　別に私はカジノディーラーとして当然の振る舞いをしただけのつもりだけど……！」
line = "「わわっ！？　な、なんだい、その口調……！　別に私はカジノディーラーとして当然の振る舞いをしただけのつもりだけど……！」"

[[dialogue]]
speaker = "ユーリス"
# 「今日の担当はバカラだったし、ヘレナさんにも許可は取ったよ？　万が一でもイカサマに使われないようにカードの裏にサインも書いて──」
line = "「今日の担当はバカラだったし、ヘレナさんにも許可は取ったよ？　万が一でもイカサマに使われないようにカードの裏にサインも書いて──」"

[[dialogue]]
speaker = "ユーリス"
# 「え、そこじゃない？　難しいな、会長の言うことは……」
line = "「え、そこじゃない？　難しいな、会長の言うことは……」"

[[dialogue]]
speaker = "unk"
# 俺もユーリスのサイン入りカードが欲しいよ
line = "俺もユーリスのサイン入りカードが欲しいよ"

[[dialogue]]
speaker = "ユーリス"
# 「欲しいのならもちろんあげるけど……──えいっ！」
line = "「欲しいのならもちろんあげるけど……──えいっ！」"

[[dialogue]]
speaker = "ユーリス"
# 「私のサインカードなんて懐に忍ばせなくても……私はいつでも会長を抱き締めてあげるつもりだよ？」
line = "「私のサインカードなんて懐に忍ばせなくても……私はいつでも会長を抱き締めてあげるつもりだよ？」"

[[dialogue]]
speaker = "ユーリス"
# 「こうやって直接……ね？　離れてって言われても絶対に離れないから」
line = "「こうやって直接……ね？　離れてって言われても絶対に離れないから」"

[[dialogue]]
speaker = "ユーリス"
# 「だから、もしも何か緊張するようなことがあったり、震えてしまうようなことがあったりしたらいつでも言って？」
line = "「だから、もしも何か緊張するようなことがあったり、震えてしまうようなことがあったりしたらいつでも言って？」"

[[dialogue]]
speaker = "ユーリス"
# 「安心できるまでずーっとくっついてるから。君だけの……その。ハートのクイーンとして……」
line = "「安心できるまでずーっとくっついてるから。君だけの……その。ハートのクイーンとして……」"

[[dialogue]]
speaker = "ユーリス"
# 「って……えへへ。調子に乗りすぎかな？　いくら恋人だからってハートのクイーンを名乗っちゃうなんて」
line = "「って……えへへ。調子に乗りすぎかな？　いくら恋人だからってハートのクイーンを名乗っちゃうなんて」"

[[dialogue]]
speaker = "ユーリス"
# 「……全然ＯＫ？　なら良かった。じゃあ遠慮なく抱きつかせてもらうね？　いつでもどこでも、なんでもない時もぎゅ～っと」
line = "「……全然ＯＫ？　なら良かった。じゃあ遠慮なく抱きつかせてもらうね？　いつでもどこでも、なんでもない時もぎゅ～っと」"

[[dialogue]]
speaker = "ユーリス"
# 「それと……その。私のことも同じように抱き締めてもらえると嬉しいな。私が緊張しちゃってる時はもちろん、なんでもない時もこうやって……」
line = "「それと……その。私のことも同じように抱き締めてもらえると嬉しいな。私が緊張しちゃってる時はもちろん、なんでもない時もこうやって……」"

[[dialogue]]
speaker = "ユーリス"
# 「私にとって君は、唯一無二のハートのキングだから」
line = "「私にとって君は、唯一無二のハートのキングだから」"

[[dialogue]]
speaker = "ユーリス"
# 「大好き……だよ？」
line = "「大好き……だよ？」"
