[[dialogue]]
speaker = "unk"
# 第１話,インラインスケートの練習,P
line = "第１話,インラインスケートの練習,P"

[[dialogue]]
speaker = "舞亜"
# 「――というわけで、貰ったばかりの戦闘服を使いこなせるようにみんな特訓中だよ。特にアニュラスが張り切ってて」
line = "「――というわけで、貰ったばかりの戦闘服を使いこなせるようにみんな特訓中だよ。特にアニュラスが張り切ってて」"

[[dialogue]]
speaker = "舞亜"
# 「アポロちゃんは星見家のメイドさん達から逃げ回ってる最中かも。可哀想だな～って思うけど、可愛がりたくなる気持ちはわかるから、何とも言えないね」
line = "「アポロちゃんは星見家のメイドさん達から逃げ回ってる最中かも。可哀想だな～って思うけど、可愛がりたくなる気持ちはわかるから、何とも言えないね」"

[[dialogue]]
speaker = "舞亜"
# 「私？　うーん、特訓ってほどじゃないけど、ちょっと慣れが必要かなって。ほら、今回のクリスマスフォームはこうなってるから」
line = "「私？　うーん、特訓ってほどじゃないけど、ちょっと慣れが必要かなって。ほら、今回のクリスマスフォームはこうなってるから」"

[[dialogue]]
speaker = "unk"
# インラインスケート！
line = "インラインスケート！"

[[dialogue]]
speaker = "舞亜"
# 「そう、フィギュアスケートの靴じゃないから、いつもとちょっと勝手が違うんだよね」
line = "「そう、フィギュアスケートの靴じゃないから、いつもとちょっと勝手が違うんだよね」"

[[dialogue]]
speaker = "舞亜"
# 「というわけで、大丈夫な時には極力クリスマスフォームになってるよ。集中してなくても普通に滑れるようになりたいんだよね」
line = "「というわけで、大丈夫な時には極力クリスマスフォームになってるよ。集中してなくても普通に滑れるようになりたいんだよね」"

[[dialogue]]
speaker = "舞亜"
# 「クリスマスフォームを普段使いにしてみたら、って提案はソフィがしてくれたんだけど、これが結構気付くことがあって」
line = "「クリスマスフォームを普段使いにしてみたら、って提案はソフィがしてくれたんだけど、これが結構気付くことがあって」"

[[dialogue]]
speaker = "舞亜"
# 「人と人との間を縫って滑るのって、かなりランダム性があるから、パーティー会場で滑る時の練習になりそうなんだよね」
line = "「人と人との間を縫って滑るのって、かなりランダム性があるから、パーティー会場で滑る時の練習になりそうなんだよね」"

[[dialogue]]
speaker = "unk"
# 可愛い舞亜が見れて嬉しい
line = "可愛い舞亜が見れて嬉しい"

[[dialogue]]
speaker = "unk"
# 普段使いしてくれると
line = "普段使いしてくれると"

[[dialogue]]
speaker = "舞亜"
# 「ふふ、ありがと♪」
line = "「ふふ、ありがと♪」"

[[dialogue]]
speaker = "舞亜"
# 「でもこの衣装、本当にカワイイよね。さすがヘレナさんって感じ」
line = "「でもこの衣装、本当にカワイイよね。さすがヘレナさんって感じ」"

[[dialogue]]
speaker = "舞亜"
# 「フィギュアスケートの衣装もカワイイのが多いけど、このフォームも同じくらい可愛いと思わない？」
line = "「フィギュアスケートの衣装もカワイイのが多いけど、このフォームも同じくらい可愛いと思わない？」"

[[dialogue]]
speaker = "unk"
# でも中身の方も可愛い
line = "でも中身の方も可愛い"

[[dialogue]]
speaker = "unk"
# 確かに可愛い
line = "確かに可愛い"

[[dialogue]]
speaker = "舞亜"
# 「わ、私のことは、今はいいでしょ。今は衣装の話をしてるのっ」
line = "「わ、私のことは、今はいいでしょ。今は衣装の話をしてるのっ」"

[[dialogue]]
speaker = "舞亜"
# 「でも、そうだね。クリスマスフォームでいると注目を集めやすいから、いい意味で気が抜けないっていうか、プレッシャーを感じるんだよね」
line = "「でも、そうだね。クリスマスフォームでいると注目を集めやすいから、いい意味で気が抜けないっていうか、プレッシャーを感じるんだよね」"

[[dialogue]]
speaker = "舞亜"
# 「それはいい刺激になるかも。見られることを常に意識するのは、すごく大事だから」
line = "「それはいい刺激になるかも。見られることを常に意識するのは、すごく大事だから」"

[[dialogue]]
speaker = "舞亜"
# 「ちょっと見てて。滑ってくるから」
line = "「ちょっと見てて。滑ってくるから」"

[[dialogue]]
speaker = "舞亜"
# 「行きますっ！」
line = "「行きますっ！」"

[[dialogue]]
speaker = "舞亜"
# 「ふふふっ、すいすいすいーーーっと」
line = "「ふふふっ、すいすいすいーーーっと」"

[[dialogue]]
speaker = "舞亜"
# 「ぶつからないようにターン！」
line = "「ぶつからないようにターン！」"

[[dialogue]]
speaker = "舞亜"
# 「驚かせてごめんね～！　はいっ、お詫びのスピン！」
line = "「驚かせてごめんね～！　はいっ、お詫びのスピン！」"

[[dialogue]]
speaker = "舞亜"
# 「ありがと～！　応援よろしくね～」
line = "「ありがと～！　応援よろしくね～」"

[[dialogue]]
speaker = "舞亜"
# 「ふぅ……ただいま。どうだった？」
line = "「ふぅ……ただいま。どうだった？」"

[[dialogue]]
speaker = "unk"
# 惚れ直した
line = "惚れ直した"

[[dialogue]]
speaker = "unk"
# こんなの好きになっちゃう
line = "こんなの好きになっちゃう"

[[dialogue]]
speaker = "舞亜"
# 「ちょっ、褒めすぎ褒めすぎっ。もう、油断するとすぐ恋人モードに入るんだから……」
line = "「ちょっ、褒めすぎ褒めすぎっ。もう、油断するとすぐ恋人モードに入るんだから……」"

[[dialogue]]
speaker = "舞亜"
# 「必死になって隠すつもりはもう無いけど、あんまり見せつけるのはね？　見られてない時だったら、その……していいから<emoji=heart04>」
line = "「必死になって隠すつもりはもう無いけど、あんまり見せつけるのはね？　見られてない時だったら、その……していいから<emoji=heart04>」"

[[dialogue]]
speaker = "舞亜"
# 「あっ、していいってキスのことだからね？　会長さん、今もっとエッチなこと想像したでしょ？　もぉー」
line = "「あっ、していいってキスのことだからね？　会長さん、今もっとエッチなこと想像したでしょ？　もぉー」"

[[dialogue]]
speaker = "舞亜"
# 「あんまりエッチなのはよくないんだから。……今はこれで我慢してっ」
line = "「あんまりエッチなのはよくないんだから。……今はこれで我慢してっ」"

[[dialogue]]
speaker = "舞亜"
# 「ちゅ<emoji=heart04>」
line = "「ちゅ<emoji=heart04>」"

[[dialogue]]
speaker = "舞亜"
# 「えへへ～、キスしちゃった。ほっぺだし、一瞬だったからセーフだよね？」
line = "「えへへ～、キスしちゃった。ほっぺだし、一瞬だったからセーフだよね？」"

[[dialogue]]
speaker = "舞亜"
# 「一瞬じゃ物足りないって……それはまあ、そうなんだけどっ。こんな人が大勢いるところでがっつりキスはダメだってば<emoji=heart04>」
line = "「一瞬じゃ物足りないって……それはまあ、そうなんだけどっ。こんな人が大勢いるところでがっつりキスはダメだってば<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# もっと練習しないと
line = "もっと練習しないと"

[[dialogue]]
speaker = "unk"
# がっつりじゃなきゃいいよね？
line = "がっつりじゃなきゃいいよね？"

[[dialogue]]
speaker = "舞亜"
# 「ううっ、練習って自分で言ったばっかりだしなぁ……もー、わかったよ」
line = "「ううっ、練習って自分で言ったばっかりだしなぁ……もー、わかったよ」"

[[dialogue]]
speaker = "舞亜"
# 「でも……せっかくキスするなら、せめて雰囲気を盛り上げて欲しいな<emoji=heart04>」
line = "「でも……せっかくキスするなら、せめて雰囲気を盛り上げて欲しいな<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 大好きだ
line = "大好きだ"

[[dialogue]]
speaker = "unk"
# 可愛いよ、舞亜
line = "可愛いよ、舞亜"

[[dialogue]]
speaker = "舞亜"
# 「っっ～～～～！！？　もっ、もぉ！　もぉ！　もぉ！　ドキッとすること言って……」
line = "「っっ～～～～！！？　もっ、もぉ！　もぉ！　もぉ！　ドキッとすること言って……」"

[[dialogue]]
speaker = "舞亜"
# 「ううう～、めちゃくちゃ恥ずかしい。私赤くなってない？　ほっぺだけじゃなく、耳とか首まで真っ赤になってそうな気がする」
line = "「ううう～、めちゃくちゃ恥ずかしい。私赤くなってない？　ほっぺだけじゃなく、耳とか首まで真っ赤になってそうな気がする」"

[[dialogue]]
speaker = "舞亜"
# 「でも……うん、ありがと。ちゃんと言葉にしてくれて、嬉しかった。だから、私もちゃんとお礼するねっ」
line = "「でも……うん、ありがと。ちゃんと言葉にしてくれて、嬉しかった。だから、私もちゃんとお礼するねっ」"

[[dialogue]]
speaker = "舞亜"
# 「………………ちゅっ<emoji=heart04>」
line = "「………………ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "舞亜"
# 「えへへへ……今度はほっぺじゃなくて唇だぞ<emoji=heart04>」
line = "「えへへへ……今度はほっぺじゃなくて唇だぞ<emoji=heart04>」"

[[dialogue]]
speaker = "舞亜"
# 「唇にキスしちゃうくらい、好きなんだからね<emoji=heart04>　大事なことだから会長さんも覚えておくよーに」
line = "「唇にキスしちゃうくらい、好きなんだからね<emoji=heart04>　大事なことだから会長さんも覚えておくよーに」"
