[[dialogue]]
speaker = "unk"
# 第３話,スイートポテト祭,P
line = "第３話,スイートポテト祭,P"

[[dialogue]]
speaker = "unk"
# 部屋の端に置かれている段ボールの中を覗き込んで、ウズメが絶句していた。
line = "部屋の端に置かれている段ボールの中を覗き込んで、ウズメが絶句していた。"

[[dialogue]]
speaker = "ウズメイア"
# 「うわぁ、サツマイモでいっぱいだし……どうしちゃったの、これ？」
line = "「うわぁ、サツマイモでいっぱいだし……どうしちゃったの、これ？」"

[[dialogue]]
speaker = "unk"
# 母さんが貰ってきたんだ
line = "母さんが貰ってきたんだ"

[[dialogue]]
speaker = "ウズメイア"
# 「こんなにあるといくら美味しくても処理に困っちゃうよね……」
line = "「こんなにあるといくら美味しくても処理に困っちゃうよね……」"

[[dialogue]]
speaker = "ウズメイア"
# 「それで今日はあたしを家に誘って、ちょっとでも消費しようって感じなの？」
line = "「それで今日はあたしを家に誘って、ちょっとでも消費しようって感じなの？」"

[[dialogue]]
speaker = "unk"
# ウズメにお菓子を作ってあげたくて
line = "ウズメにお菓子を作ってあげたくて"

[[dialogue]]
speaker = "ウズメイア"
# 「物は言いようだし～。ま、会長くんの作る美味しいお菓子が食べられるならなんでもいいけど」
line = "「物は言いようだし～。ま、会長くんの作る美味しいお菓子が食べられるならなんでもいいけど」"

[[dialogue]]
speaker = "ウズメイア"
# 「あ、そだ♪　せっかくだから２人で作ろーよ」
line = "「あ、そだ♪　せっかくだから２人で作ろーよ」"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くんに作らせてあたしはただ待ってるだけっていうのも変な話じゃん？　だったら一緒に作った方が絶対楽しいでしょ♪」
line = "「会長くんに作らせてあたしはただ待ってるだけっていうのも変な話じゃん？　だったら一緒に作った方が絶対楽しいでしょ♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「それにさー、あたしってこういう感じだから、あんまり料理とかできる風に見られないんだよね」
line = "「それにさー、あたしってこういう感じだから、あんまり料理とかできる風に見られないんだよね」"

[[dialogue]]
speaker = "unk"
# ウズメが料理出来るのは知ってるよ？
line = "ウズメが料理出来るのは知ってるよ？"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くんにはたまに作ったものを食べてもらってるもんね。でも実際に作ってるところを見せたことはないっしょ？」
line = "「会長くんにはたまに作ったものを食べてもらってるもんね。でも実際に作ってるところを見せたことはないっしょ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「だから、これを機会に料理が出来るところをアピールしとくのも悪くないなって……ま、腕前的にはフツーでサラン先輩とかと比ぶべくもないんだけど」
line = "「だから、これを機会に料理が出来るところをアピールしとくのも悪くないなって……ま、腕前的にはフツーでサラン先輩とかと比ぶべくもないんだけど」"

[[dialogue]]
speaker = "ウズメイア"
# 「さーて、なに作る？　サツマイモ料理ってどんなのあったっけ」
line = "「さーて、なに作る？　サツマイモ料理ってどんなのあったっけ」"

[[dialogue]]
speaker = "unk"
# スイートポテトとかどう？
line = "スイートポテトとかどう？"

[[dialogue]]
speaker = "ウズメイア"
# 「いーじゃん！　お手軽だし、作ってて楽しいし！　決まり、それにしよっ♪」
line = "「いーじゃん！　お手軽だし、作ってて楽しいし！　決まり、それにしよっ♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「かんせーいっ♪」
line = "「かんせーいっ♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「それじゃ作ったスイートポテトを見せあいっこするし♪　会長くんのは……」
line = "「それじゃ作ったスイートポテトを見せあいっこするし♪　会長くんのは……」"

[[dialogue]]
speaker = "ウズメイア"
# 「わっ、カボチャの形になってるし！　ハロウィンにちなんでってことね、なるほどなるほど……」
line = "「わっ、カボチャの形になってるし！　ハロウィンにちなんでってことね、なるほどなるほど……」"

[[dialogue]]
speaker = "ウズメイア"
# 「あたしのはこれっ！　カヌレ型にしたお化け風のスイートポテトだよ。えへへ、発想は全くおんなじだったみたいだね」
line = "「あたしのはこれっ！　カヌレ型にしたお化け風のスイートポテトだよ。えへへ、発想は全くおんなじだったみたいだね」"

[[dialogue]]
speaker = "unk"
# お化けに個性があって可愛い
line = "お化けに個性があって可愛い"

[[dialogue]]
speaker = "ウズメイア"
# 「さっすが会長くん、気付いてくれたし♪　そーなんです、このお化けちゃんたちは１人１人、ちゃーんとモデルがいるお化けちゃんなんです♪」
line = "「さっすが会長くん、気付いてくれたし♪　そーなんです、このお化けちゃんたちは１人１人、ちゃーんとモデルがいるお化けちゃんなんです♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「さてここで問題、この子たちは誰をモデルにしてるでしょーか？」
line = "「さてここで問題、この子たちは誰をモデルにしてるでしょーか？」"

[[dialogue]]
speaker = "ウズメイア"
# 「ちっちっちっちっ……ピンポーン、正解。その子は舞亜でした～」
line = "「ちっちっちっちっ……ピンポーン、正解。その子は舞亜でした～」"

[[dialogue]]
speaker = "ウズメイア"
# 「こっちがソフィで、こっちのがシャルレーヌちゃん。これがゆゆ姫ちゃんで……これは難しいけど、誰だか分かるかな～？」
line = "「こっちがソフィで、こっちのがシャルレーヌちゃん。これがゆゆ姫ちゃんで……これは難しいけど、誰だか分かるかな～？」"

[[dialogue]]
speaker = "ウズメイア"
# 「わ、よく分かったね！　セーラ先輩、大正解だし♪」
line = "「わ、よく分かったね！　セーラ先輩、大正解だし♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「それで残りのこれがあたしで、こっちが会長くんでした～」
line = "「それで残りのこれがあたしで、こっちが会長くんでした～」"

[[dialogue]]
speaker = "unk"
# 俺のもあるんだ
line = "俺のもあるんだ"

[[dialogue]]
speaker = "ウズメイア"
# 「もっちろんだし♪　なんなら一番心を込めて作ったまであるし♪」
line = "「もっちろんだし♪　なんなら一番心を込めて作ったまであるし♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「あっ、ダメダメ！　これはあたしんだし！　会長くんは他のにしてよ～！」
line = "「あっ、ダメダメ！　これはあたしんだし！　会長くんは他のにしてよ～！」"

[[dialogue]]
speaker = "ウズメイア"
# 「えへへ、あなたはあたしが美味しく食べてあげるからね～、ちゅっ<emoji=heart04>」
line = "「えへへ、あなたはあたしが美味しく食べてあげるからね～、ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「あれ？　なんでそんな複雑そうな顔してるんですか？」
line = "「あれ？　なんでそんな複雑そうな顔してるんですか？」"

[[dialogue]]
speaker = "ウズメイア"
# 「あ～、確かに自分がモデルのお菓子が食べられちゃうって考えると、ちょっと変な気分になっちゃうかも？」
line = "「あ～、確かに自分がモデルのお菓子が食べられちゃうって考えると、ちょっと変な気分になっちゃうかも？」"

[[dialogue]]
speaker = "ウズメイア"
# 「でもまあ、お菓子はあくまでお菓子だし！　気にしない気にしない♪」
line = "「でもまあ、お菓子はあくまでお菓子だし！　気にしない気にしない♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「ふぁっ！？　会長くん、それはあたしがモデルの……！」
line = "「ふぁっ！？　会長くん、それはあたしがモデルの……！」"

[[dialogue]]
speaker = "unk"
# お菓子になっても可愛い
line = "お菓子になっても可愛い"

[[dialogue]]
speaker = "unk"
# ちゅっ
line = "ちゅっ"

[[dialogue]]
speaker = "ウズメイア"
# 「なななっ……！　た、確かにいざ自分がやられてみると恥ずかしい、かも……」
line = "「なななっ……！　た、確かにいざ自分がやられてみると恥ずかしい、かも……」"

[[dialogue]]
speaker = "ウズメイア"
# 「でもでもっ！　そんなこと言ってたら一生食べられないしっ！　どうしたらいいのーーーーっ！！」
line = "「でもでもっ！　そんなこと言ってたら一生食べられないしっ！　どうしたらいいのーーーーっ！！」"

[[dialogue]]
speaker = "unk"
# まさかの問題に、頭を抱えるウズメ。
line = "まさかの問題に、頭を抱えるウズメ。"

[[dialogue]]
speaker = "unk"
# でも、そんなやり取りをひとしきり終えた後、２人で作ったスイートポテトは結局全部美味しく頂いたのだった。
line = "でも、そんなやり取りをひとしきり終えた後、２人で作ったスイートポテトは結局全部美味しく頂いたのだった。"
