[[dialogue]]
speaker = "unk"
# 第１話,朝比奈コハルコは泳げない,P
line = "第１話,朝比奈コハルコは泳げない,P"

[[dialogue]]
speaker = "unk"
# コハルコは泳げない……というより、運動全般が苦手だ。
line = "コハルコは泳げない……というより、運動全般が苦手だ。"

[[dialogue]]
speaker = "unk"
# それでも泳げないのだけでもなんとかしようと、今日はリゾート結界のプライベートビーチを借りて練習中だ。
line = "それでも泳げないのだけでもなんとかしようと、今日はリゾート結界のプライベートビーチを借りて練習中だ。"

[[dialogue]]
speaker = "コハルコ"
# 「会長さん、手を放さないでね。絶対だよ！」
line = "「会長さん、手を放さないでね。絶対だよ！」"

[[dialogue]]
speaker = "unk"
# コハルコが足を力いっぱい動かすと、水しぶきが派手に上がる。
line = "コハルコが足を力いっぱい動かすと、水しぶきが派手に上がる。"

[[dialogue]]
speaker = "コハルコ"
# 「んぷっ……もっと手を引いて……体、沈んじゃ……」
line = "「んぷっ……もっと手を引いて……体、沈んじゃ……」"

[[dialogue]]
speaker = "unk"
# だけどコハルコのバタ足は全く推進力を生んでおらず、俺が手を引いているから進んでいるだけだ。
line = "だけどコハルコのバタ足は全く推進力を生んでおらず、俺が手を引いているから進んでいるだけだ。"

[[dialogue]]
speaker = "unk"
# そうこうしているうちにコハルコの体は沈んでいく──といっても、足がつく浅瀬だから問題ないのだが。
line = "そうこうしているうちにコハルコの体は沈んでいく──といっても、足がつく浅瀬だから問題ないのだが。"

[[dialogue]]
speaker = "レイラ"
# 「じー……」
line = "「じー……」"

[[dialogue]]
speaker = "コハルコ"
# 「なんでレイラがいるの？　会長さんと２人で練習のつもりだったんだけど」
line = "「なんでレイラがいるの？　会長さんと２人で練習のつもりだったんだけど」"

[[dialogue]]
speaker = "コハルコ"
# 「……え、会長さんがここに来る途中で出くわしちゃった？　だからってついてこなくていいのに……」
line = "「……え、会長さんがここに来る途中で出くわしちゃった？　だからってついてこなくていいのに……」"

[[dialogue]]
speaker = "レイラ"
# 「２人っきりだとイチャイチャして練習にならないでしょう？」
line = "「２人っきりだとイチャイチャして練習にならないでしょう？」"

[[dialogue]]
speaker = "レイラ"
# 「泳ぐ練習を名目にイチャつくなんて、コハルコさんがやってるゲームでも定番のシチュエーションじゃないですか」
line = "「泳ぐ練習を名目にイチャつくなんて、コハルコさんがやってるゲームでも定番のシチュエーションじゃないですか」"

[[dialogue]]
speaker = "コハルコ"
# 「ぐぬぬ……いろんなシーンが脳内を駆け巡って反論できない……」
line = "「ぐぬぬ……いろんなシーンが脳内を駆け巡って反論できない……」"

[[dialogue]]
speaker = "unk"
# 水着のコハルコとイチャイチャしたかったのは確かだ。コハルコも同じ気持ちだったようで、２人そろって図星を突かれてしまった。
line = "水着のコハルコとイチャイチャしたかったのは確かだ。コハルコも同じ気持ちだったようで、２人そろって図星を突かれてしまった。"

[[dialogue]]
speaker = "コハルコ"
# 「そういうレイラは泳げるの？　あんまり体を動かしてるイメージないけど」
line = "「そういうレイラは泳げるの？　あんまり体を動かしてるイメージないけど」"

[[dialogue]]
speaker = "レイラ"
# 「あのー、自分が運動不足ハッカーだからって、他のハッカーもそうだと思わない方がいいですよ？」
line = "「あのー、自分が運動不足ハッカーだからって、他のハッカーもそうだと思わない方がいいですよ？」"

[[dialogue]]
speaker = "コハルコ"
# 「運動不足は余計だよ！」
line = "「運動不足は余計だよ！」"

[[dialogue]]
speaker = "レイラ"
# 「……コハルコさん、少しムチりました？　心なしか肉感的に見える気が……」
line = "「……コハルコさん、少しムチりました？　心なしか肉感的に見える気が……」"

[[dialogue]]
speaker = "コハルコ"
# 「っ！　この！」
line = "「っ！　この！」"

[[dialogue]]
speaker = "レイラ"
# 「ふんっ」
line = "「ふんっ」"

[[dialogue]]
speaker = "コハルコ"
# 「サーシャ直伝のアームロックが効かないなんて！？」
line = "「サーシャ直伝のアームロックが効かないなんて！？」"

[[dialogue]]
speaker = "レイラ"
# 「関節の極めがなってないんですよ。ナマクラもいいところです」
line = "「関節の極めがなってないんですよ。ナマクラもいいところです」"

[[dialogue]]
speaker = "レイラ"
# 「コハルコさん、万年運動不足のもやしっ子なんですから。肉体言語はコンパイルエラーです」
line = "「コハルコさん、万年運動不足のもやしっ子なんですから。肉体言語はコンパイルエラーです」"

[[dialogue]]
speaker = "レイラ"
# 「あ、もやしはもやしでも太い方のもやしですが」
line = "「あ、もやしはもやしでも太い方のもやしですが」"

[[dialogue]]
speaker = "コハルコ"
# 「誰が大豆もやしだ、誰が！　ていうか太くないって！」
line = "「誰が大豆もやしだ、誰が！　ていうか太くないって！」"

[[dialogue]]
speaker = "コハルコ"
# 「水着で露出が多いからちょっとそう見えるだけ！」
line = "「水着で露出が多いからちょっとそう見えるだけ！」"

[[dialogue]]
speaker = "レイラ"
# 「魔王さんはどう思います？」
line = "「魔王さんはどう思います？」"

[[dialogue]]
speaker = "unk"
# ノーコメントで……
line = "ノーコメントで……"

[[dialogue]]
speaker = "コハルコ"
# 「ちょっと！　そこはしっかり否定してよ！」
line = "「ちょっと！　そこはしっかり否定してよ！」"

[[dialogue]]
speaker = "unk"
# 元からコハルコは脱いだらすごい……かはともかく、水着のコハルコの姿が肉感的なのは否定できない。むしろ全力で肯定したい。
line = "元からコハルコは脱いだらすごい……かはともかく、水着のコハルコの姿が肉感的なのは否定できない。むしろ全力で肯定したい。"

[[dialogue]]
speaker = "コハルコ"
# 「え？　ムチムチした女の子も魅力的……？　会長さん、上手いこと言って誤魔化そうとしてない？」
line = "「え？　ムチムチした女の子も魅力的……？　会長さん、上手いこと言って誤魔化そうとしてない？」"

[[dialogue]]
speaker = "unk"
# 俺は今のコハルコが好きだから
line = "俺は今のコハルコが好きだから"

[[dialogue]]
speaker = "コハルコ"
# 「ふ、ふぅん。ならいいんだけど……」
line = "「ふ、ふぅん。ならいいんだけど……」"

[[dialogue]]
speaker = "レイラ"
# 「ヒューヒュー、お熱いですね！」
line = "「ヒューヒュー、お熱いですね！」"

[[dialogue]]
speaker = "コハルコ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "コハルコ"
# 「ドルフィンドローン、ハイドロジェット逆噴射！」
line = "「ドルフィンドローン、ハイドロジェット逆噴射！」"

[[dialogue]]
speaker = "レイラ"
# 「あばばばばばば！！」
line = "「あばばばばばば！！」"

[[dialogue]]
speaker = "unk"
# 水を吸い込んで加速するドルフィンドローンは、逆噴射すれば水の大砲になる。
line = "水を吸い込んで加速するドルフィンドローンは、逆噴射すれば水の大砲になる。"

[[dialogue]]
speaker = "unk"
# 星力のこもっていないただの水なのでダメージはないはずだが、それでも勢いは凄まじい。
line = "星力のこもっていないただの水なのでダメージはないはずだが、それでも勢いは凄まじい。"

[[dialogue]]
speaker = "レイラ"
# 「ぷひゃー、びっくりした。私の顔、ちゃんついてます？」
line = "「ぷひゃー、びっくりした。私の顔、ちゃんついてます？」"

[[dialogue]]
speaker = "コハルコ"
# 「可愛いお目めもお鼻もちゃんとついてるよ。ブラックホールの星力で守られてるレイラにただの水流なんか効かないでしょ」
line = "「可愛いお目めもお鼻もちゃんとついてるよ。ブラックホールの星力で守られてるレイラにただの水流なんか効かないでしょ」"

[[dialogue]]
speaker = "レイラ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "コハルコ"
# 「どうしたの、私のドルフィンドローンじっと見て」
line = "「どうしたの、私のドルフィンドローンじっと見て」"

[[dialogue]]
speaker = "レイラ"
# 「イルカ　消す方法　検索」
line = "「イルカ　消す方法　検索」"

[[dialogue]]
speaker = "コハルコ"
# 「こらー！　私のイルカちゃん消そうとすなー！」
line = "「こらー！　私のイルカちゃん消そうとすなー！」"

[[dialogue]]
speaker = "レイラ"
# 「いや、だって……宙に浮くイルカを消そうとするのは人類のサガじゃないですか。イルカを消そうとしなかった人だけが私に石を投げてください」
line = "「いや、だって……宙に浮くイルカを消そうとするのは人類のサガじゃないですか。イルカを消そうとしなかった人だけが私に石を投げてください」"

[[dialogue]]
speaker = "コハルコ"
# 「じゃあ遠慮なく。ドルフィンドローン、採集サンプル発射！」
line = "「じゃあ遠慮なく。ドルフィンドローン、採集サンプル発射！」"

[[dialogue]]
speaker = "レイラ"
# 「本当に石が飛んできたー！？　ぐはっ！」
line = "「本当に石が飛んできたー！？　ぐはっ！」"

[[dialogue]]
speaker = "コハルコ"
# 「ドルフィンドローンは水中で拾ったものをサンプルとして保管できるからね。逆噴射と合わせればこれくらいできるよ」
line = "「ドルフィンドローンは水中で拾ったものをサンプルとして保管できるからね。逆噴射と合わせればこれくらいできるよ」"

[[dialogue]]
speaker = "レイラ"
# 「うぅ……前が見えない…………」
line = "「うぅ……前が見えない…………」"

[[dialogue]]
speaker = "コハルコ"
# 「さて、と。レイラはほっといて練習しよ」
line = "「さて、と。レイラはほっといて練習しよ」"

[[dialogue]]
speaker = "unk"
# 砂浜にめり込むレイラを横目に、俺たちは練習を再開した──
line = "砂浜にめり込むレイラを横目に、俺たちは練習を再開した──"

[[dialogue]]
speaker = "コハルコ"
# 「ヤダ～！　水に顔つけたくない！　知ってる？　水の中って息できないんだよ！　息できないなんて怖い！」
line = "「ヤダ～！　水に顔つけたくない！　知ってる？　水の中って息できないんだよ！　息できないなんて怖い！」"

[[dialogue]]
speaker = "コハルコ"
# 「息ができないと溺れちゃうよ～！！」
line = "「息ができないと溺れちゃうよ～！！」"

[[dialogue]]
speaker = "unk"
# いくら時間をかけても、頑なに水を拒否するコハルコであった。
line = "いくら時間をかけても、頑なに水を拒否するコハルコであった。"

[[dialogue]]
speaker = "unk"
# おかげで顔を出す泳ぎ方しか練習できない。それすら１ミリも上達していないけど。
line = "おかげで顔を出す泳ぎ方しか練習できない。それすら１ミリも上達していないけど。"

[[dialogue]]
speaker = "レイラ"
# 「ＺＺＺ…………」
line = "「ＺＺＺ…………」"

[[dialogue]]
speaker = "unk"
# ちなみにレイラは飽きて寝ている。
line = "ちなみにレイラは飽きて寝ている。"

[[dialogue]]
speaker = "unk"
# コハルコ、一緒に潜ってみない？
line = "コハルコ、一緒に潜ってみない？"

[[dialogue]]
speaker = "コハルコ"
# 「でも水の中、怖いし……」
line = "「でも水の中、怖いし……」"

[[dialogue]]
speaker = "コハルコ"
# 「……一緒なら大丈夫？　絶対に手を離したりしない？」
line = "「……一緒なら大丈夫？　絶対に手を離したりしない？」"

[[dialogue]]
speaker = "unk"
# 強くうなずく。コハルコは絶対に俺が守る。
line = "強くうなずく。コハルコは絶対に俺が守る。"

[[dialogue]]
speaker = "コハルコ"
# 「うん、じゃあ…………少しだけ、少しだけだよ？」
line = "「うん、じゃあ…………少しだけ、少しだけだよ？」"

[[dialogue]]
speaker = "unk"
# コハルコがぎゅっと強く手を握る。幼い子どもみたいで可愛い。
line = "コハルコがぎゅっと強く手を握る。幼い子どもみたいで可愛い。"

[[dialogue]]
speaker = "unk"
# せぇの！
line = "せぇの！"

[[dialogue]]
speaker = "コハルコ"
# 「きゃっ──」
line = "「きゃっ──」"

[[dialogue]]
speaker = "unk"
# 数秒だけその場に潜って──
line = "数秒だけその場に潜って──"

[[dialogue]]
speaker = "unk"
# すぐに立ち上がる。その間もコハルコの手は握ったままだ。
line = "すぐに立ち上がる。その間もコハルコの手は握ったままだ。"

[[dialogue]]
speaker = "unk"
# 海の中、どうだった？
line = "海の中、どうだった？"

[[dialogue]]
speaker = "コハルコ"
# 「目をつむってたから、何も見えなかったけど……私、海に潜れたんだね……」
line = "「目をつむってたから、何も見えなかったけど……私、海に潜れたんだね……」"

[[dialogue]]
speaker = "コハルコ"
# 「君の言ったとおりだったよ。一緒だから怖くなかった！」
line = "「君の言ったとおりだったよ。一緒だから怖くなかった！」"

[[dialogue]]
speaker = "コハルコ"
# 「ふふ、ふふふ……海、潜っちゃった……ふふふ」
line = "「ふふ、ふふふ……海、潜っちゃった……ふふふ」"

[[dialogue]]
speaker = "unk"
# 嬉しそうに微笑むコハルコ。どんなに小さい一歩でも、確かな前進には違いなかった。
line = "嬉しそうに微笑むコハルコ。どんなに小さい一歩でも、確かな前進には違いなかった。"
