[[dialogue]]
speaker = "unk"
# 第２話,水着星騎士杯開幕！？,P
line = "第２話,水着星騎士杯開幕！？,P"

[[dialogue]]
speaker = "unk"
# イングリットとヴィーナスの邂逅から数日後。
line = "イングリットとヴィーナスの邂逅から数日後。"

[[dialogue]]
speaker = "unk"
# リゾート結界は水着を着た星騎士で溢れかえっていた。
line = "リゾート結界は水着を着た星騎士で溢れかえっていた。"

[[dialogue]]
speaker = "unk"
# どうやら、俺と同じくヘレナちゃんからの呼び出しのようだ。何かのイベントだろうか。
line = "どうやら、俺と同じくヘレナちゃんからの呼び出しのようだ。何かのイベントだろうか。"

[[dialogue]]
speaker = "イングリット"
# 「フッ、水着戦闘服を着た星騎士がこんなにいたとはな。私を愉しませる強者がいるといいが」
line = "「フッ、水着戦闘服を着た星騎士がこんなにいたとはな。私を愉しませる強者がいるといいが」"

[[dialogue]]
speaker = "unk"
# イングリットも来たのか！？
line = "イングリットも来たのか！？"

[[dialogue]]
speaker = "イングリット"
# 「なんだ、その呆けた顔は。これから始まるのは夏の最強をかけた戦い。そんなことで生き残れるのか？」
line = "「なんだ、その呆けた顔は。これから始まるのは夏の最強をかけた戦い。そんなことで生き残れるのか？」"

[[dialogue]]
speaker = "unk"
# イングリットがイベントに来るなんて珍しい、などと思っているうちに、ヘレナちゃんがみんなの前に現れた。
line = "イングリットがイベントに来るなんて珍しい、などと思っているうちに、ヘレナちゃんがみんなの前に現れた。"

[[dialogue]]
speaker = "ヘレナ"
# 「星騎士諸君、急な呼び出しに応じていただき感謝する。立てばプリティー、座ればゴージャス、ヘレナちゃんである」
line = "「星騎士諸君、急な呼び出しに応じていただき感謝する。立てばプリティー、座ればゴージャス、ヘレナちゃんである」"

[[dialogue]]
speaker = "ヘレナ"
# 「夏の最強──つまり、最強の水着星騎士は誰かを決めようというのが今回の趣旨だ。諸君は己の力をぶつけあい、研鑚の機会としてほしい」
line = "「夏の最強──つまり、最強の水着星騎士は誰かを決めようというのが今回の趣旨だ。諸君は己の力をぶつけあい、研鑚の機会としてほしい」"

[[dialogue]]
speaker = "ヘレナ"
# 「形式はバトルロワイヤル。最後まで立っていた者の勝利だ。優勝者には賞品としてカフェテリアの食事券１年分を贈呈しよう」
line = "「形式はバトルロワイヤル。最後まで立っていた者の勝利だ。優勝者には賞品としてカフェテリアの食事券１年分を贈呈しよう」"

[[dialogue]]
speaker = "レイラ"
# 「食事券１年分！？　さすが理事長閣下！　ヘレナちゃん様サイコー！」
line = "「食事券１年分！？　さすが理事長閣下！　ヘレナちゃん様サイコー！」"

[[dialogue]]
speaker = "イングリット"
# 「ククッ、レイラも来ていたか。戦うのが楽しみだ」
line = "「ククッ、レイラも来ていたか。戦うのが楽しみだ」"

[[dialogue]]
speaker = "ヘレナ"
# 「名付けて──『ドキッ！　水着だらけの星騎士バトルロワイヤル』だ。では、リップル」
line = "「名付けて──『ドキッ！　水着だらけの星騎士バトルロワイヤル』だ。では、リップル」"

[[dialogue]]
speaker = "リップル"
# 「ハイ！　準備デキてまーす！　開催の合図とともにみなさんを結界内にランダムにハイチします。これで公平ですね！」
line = "「ハイ！　準備デキてまーす！　開催の合図とともにみなさんを結界内にランダムにハイチします。これで公平ですね！」"

[[dialogue]]
speaker = "ヘレナ"
# 「うむ、よろしく頼むぞ。では、『ドキッ！　水着だらけの星騎士バトルロワイヤル』の開催をここに宣言する！」
line = "「うむ、よろしく頼むぞ。では、『ドキッ！　水着だらけの星騎士バトルロワイヤル』の開催をここに宣言する！」"

[[dialogue]]
speaker = "リップル"
# 「いってラッシャーセー！」
line = "「いってラッシャーセー！」"

[[dialogue]]
speaker = "unk"
# 視界が暗転したかと思うと、次の瞬間には海岸に飛ばされていた。
line = "視界が暗転したかと思うと、次の瞬間には海岸に飛ばされていた。"

[[dialogue]]
speaker = "イングリット"
# 「最初に出くわすのが貴様とはな。これも運命だ。私と戦え」
line = "「最初に出くわすのが貴様とはな。これも運命だ。私と戦え」"

[[dialogue]]
speaker = "イングリット"
# 「……大会の開催を知っていたのか、だと？　無論だ。この大会はヴィーナスの仕込みだからな。やつもなかなか面白いことを考える」
line = "「……大会の開催を知っていたのか、だと？　無論だ。この大会はヴィーナスの仕込みだからな。やつもなかなか面白いことを考える」"

[[dialogue]]
speaker = "unk"
# 数日前、２人で笑いあっていたのはこういうことか。
line = "数日前、２人で笑いあっていたのはこういうことか。"

[[dialogue]]
speaker = "イングリット"
# 「よし、では構えろ」
line = "「よし、では構えろ」"

[[dialogue]]
speaker = "？？？"
# 「でーでんでーでんでーでんでーでん……」
line = "「でーでんでーでんでーでんでーでん……」"

[[dialogue]]
speaker = "パテル"
# 「しゃーっ！　おまえの相手はあたしだー！」
line = "「しゃーっ！　おまえの相手はあたしだー！」"

[[dialogue]]
speaker = "イングリット"
# 「誰かと思えば、守護天使パテルか。守護天使が相手とは<ruby=ぎょうこう>僥倖</ruby>だ。その力、見せてもらうぞ！」
line = "「誰かと思えば、守護天使パテルか。守護天使が相手とは<ruby>僥倖<rt>ぎょうこう</rt></ruby>だ。その力、見せてもらうぞ！」"

[[dialogue]]
speaker = "パテル"
# 「盛り上がってるとこ悪いけど、今日はお仕置きに来たんだからね。パテルちゃんはおこなのだ。ぷんぷん！」
line = "「盛り上がってるとこ悪いけど、今日はお仕置きに来たんだからね。パテルちゃんはおこなのだ。ぷんぷん！」"

[[dialogue]]
speaker = "イングリット"
# 「なに？　仕置きを受けるようなことをした覚えはないぞ」
line = "「なに？　仕置きを受けるようなことをした覚えはないぞ」"

[[dialogue]]
speaker = "パテル"
# 「分からないならはっきり言ってあげるね。すーっ……」
line = "「分からないならはっきり言ってあげるね。すーっ……」"

[[dialogue]]
speaker = "パテル"
# 「神殿掃除しに来いやー！！　イングリット、氏子なのに一度も掃除に来たことないじゃん！」
line = "「神殿掃除しに来いやー！！　イングリット、氏子なのに一度も掃除に来たことないじゃん！」"

[[dialogue]]
speaker = "unk"
# 氏子？
line = "氏子？"

[[dialogue]]
speaker = "イングリット"
# 「魔王には言っていなかったか。私の生まれた天界の武闘都市ウリルの近くには、守護天使パテルの神殿があり、その管理を我が家が代々担っている」
line = "「魔王には言っていなかったか。私の生まれた天界の武闘都市ウリルの近くには、守護天使パテルの神殿があり、その管理を我が家が代々担っている」"

[[dialogue]]
speaker = "イングリット"
# 「つまり、私はパテルを祀る家系の末裔というわけだ」
line = "「つまり、私はパテルを祀る家系の末裔というわけだ」"

[[dialogue]]
speaker = "イングリット"
# 「天界襲撃の際にはちゃんと守りに行ってやったはずだがな。それではご不満らしい」
line = "「天界襲撃の際にはちゃんと守りに行ってやったはずだがな。それではご不満らしい」"

[[dialogue]]
speaker = "パテル"
# 「イングリットは極星従騎と戦いたかっただけでしょ。しかも、帰りも掃除していかないし！」
line = "「イングリットは極星従騎と戦いたかっただけでしょ。しかも、帰りも掃除していかないし！」"

[[dialogue]]
speaker = "イングリット"
# 「当たり前だ。私は戦士だ。掃除なぞするヒマがあれば鍛錬に充てる。掃除など年寄りに任せておけ」
line = "「当たり前だ。私は戦士だ。掃除なぞするヒマがあれば鍛錬に充てる。掃除など年寄りに任せておけ」"

[[dialogue]]
speaker = "パテル"
# 「他のとこはしっかりしてるのに、うちはこれだからなー。性根を叩き直してやるから覚悟しろ！」
line = "「他のとこはしっかりしてるのに、うちはこれだからなー。性根を叩き直してやるから覚悟しろ！」"

[[dialogue]]
speaker = "unk"
# （無理だと思う）
line = "（無理だと思う）"

[[dialogue]]
speaker = "イングリット"
# 「御託はいい。かかってこい守護天使！」
line = "「御託はいい。かかってこい守護天使！」"

[[dialogue]]
speaker = "パテル"
# 「こいつなんでこんなに偉そうなんだろうね。じゃあ──」
line = "「こいつなんでこんなに偉そうなんだろうね。じゃあ──」"

[[dialogue]]
speaker = "パテル"
# 「でーでんでーでんでーでんでーでん」
line = "「でーでんでーでんでーでんでーでん」"

[[dialogue]]
speaker = "イングリット"
# 「海に潜ったか。これではどこにいるか分からん」
line = "「海に潜ったか。これではどこにいるか分からん」"

[[dialogue]]
speaker = "イングリット"
# 「死とは突然、忍び寄るもの……だったか。子どもの頃から聞かされていたとも」
line = "「死とは突然、忍び寄るもの……だったか。子どもの頃から聞かされていたとも」"

[[dialogue]]
speaker = "イングリット"
# 「だが、そんなものを恐れる私ではない！　海ごと叩き斬ってみせよう！　ザンブレイクセイバー！！」
line = "「だが、そんなものを恐れる私ではない！　海ごと叩き斬ってみせよう！　ザンブレイクセイバー！！」"

[[dialogue]]
speaker = "unk"
# 特大の斬撃が海を切り裂き、大波を生み出した。波の間からパテルが顔を出す。
line = "特大の斬撃が海を切り裂き、大波を生み出した。波の間からパテルが顔を出す。"

[[dialogue]]
speaker = "パテル"
# 「おっと、見付かっちゃった？　やるね～。そりゃっ！」
line = "「おっと、見付かっちゃった？　やるね～。そりゃっ！」"

[[dialogue]]
speaker = "unk"
# 波間から出てきたパテルがサメごと体当たりを仕掛ける。
line = "波間から出てきたパテルがサメごと体当たりを仕掛ける。"

[[dialogue]]
speaker = "イングリット"
# 「ぐぅっ！　これが守護天使の力か！　ククク、やはり戦いは愉しいな！」
line = "「ぐぅっ！　これが守護天使の力か！　ククク、やはり戦いは愉しいな！」"

[[dialogue]]
speaker = "unk"
# ……これじゃむしろご褒美では？
line = "……これじゃむしろご褒美では？"

[[dialogue]]
speaker = "パテル"
# 「え、どういうこと？」
line = "「え、どういうこと？」"

[[dialogue]]
speaker = "パテル"
# 「……掃除しないお仕置きに来たのに、戦ったらご褒美になっちゃう？　それはそうかも。う～ん」
line = "「……掃除しないお仕置きに来たのに、戦ったらご褒美になっちゃう？　それはそうかも。う～ん」"

[[dialogue]]
speaker = "パテル"
# 「じゃ、こうしよっか。イングリット～、神殿の掃除したら続きしたげる。それまでお預けってことで！」
line = "「じゃ、こうしよっか。イングリット～、神殿の掃除したら続きしたげる。それまでお預けってことで！」"

[[dialogue]]
speaker = "イングリット"
# 「なんだと！？　ここからがいいところだろうが！」
line = "「なんだと！？　ここからがいいところだろうが！」"

[[dialogue]]
speaker = "パテル"
# 「じゃあね。しーゆーあげいん♪」
line = "「じゃあね。しーゆーあげいん♪」"

[[dialogue]]
speaker = "イングリット"
# 「に、逃げるな～～～～～！？」
line = "「に、逃げるな～～～～～！？」"

[[dialogue]]
speaker = "イングリット"
# 「どうしてくれる、魔王！　貴様のせいでパテルが帰ってしまったではないか！」
line = "「どうしてくれる、魔王！　貴様のせいでパテルが帰ってしまったではないか！」"

[[dialogue]]
speaker = "unk"
# 神殿の掃除しようね
line = "神殿の掃除しようね"

[[dialogue]]
speaker = "イングリット"
# 「他人事みたいな顔をするな！　貴様のせいなのだから、責任を取って手伝え。今度ウリルに戻るときは貴様も来てもらうぞ！」
line = "「他人事みたいな顔をするな！　貴様のせいなのだから、責任を取って手伝え。今度ウリルに戻るときは貴様も来てもらうぞ！」"

[[dialogue]]
speaker = "unk"
# それって、イングリットの実家に俺も一緒に行くってことになるんだろうか。
line = "それって、イングリットの実家に俺も一緒に行くってことになるんだろうか。"

[[dialogue]]
speaker = "イングリット"
# 「そうだ、ついでに父と母にも貴様を紹介してやろう。私と釣り合う男は少ないからな」
line = "「そうだ、ついでに父と母にも貴様を紹介してやろう。私と釣り合う男は少ないからな」"

[[dialogue]]
speaker = "unk"
# やっぱり一緒に実家に行く流れになっていた。何故だ。
line = "やっぱり一緒に実家に行く流れになっていた。何故だ。"
