[[dialogue]]
speaker = "unk"
# 第４話,ユーリスとのこれから,P
line = "第４話,ユーリスとのこれから,P"

[[dialogue]]
speaker = "アナ"
# 「書類の整理お疲れ様でした、会長。今日の仕事はこれで終わり──」
line = "「書類の整理お疲れ様でした、会長。今日の仕事はこれで終わり──」"

[[dialogue]]
speaker = "ユーリス"
# 「やぁ、そろそろ星徒会が終わるころかと思って迎えに来たよ」
line = "「やぁ、そろそろ星徒会が終わるころかと思って迎えに来たよ」"

[[dialogue]]
speaker = "アナ"
# 「ジャストのお迎えです。最近、会長とユーリスさんはとても仲良しですね」
line = "「ジャストのお迎えです。最近、会長とユーリスさんはとても仲良しですね」"

[[dialogue]]
speaker = "ユーリス"
# 「男同士ですから。自然と結束ができるものです」
line = "「男同士ですから。自然と結束ができるものです」"

[[dialogue]]
speaker = "ユーリス"
# 「それに今日はたこ焼きとお好み焼きの作り方を教えてもらう約束なので。とても楽しみにしていました」
line = "「それに今日はたこ焼きとお好み焼きの作り方を教えてもらう約束なので。とても楽しみにしていました」"

[[dialogue]]
speaker = "アナ"
# 「なるほど。納得」
line = "「なるほど。納得」"

[[dialogue]]
speaker = "ユーリス"
# 「では会長をもらいますね」
line = "「では会長をもらいますね」"

[[dialogue]]
speaker = "アナ"
# 「どうぞ～」
line = "「どうぞ～」"

[[dialogue]]
speaker = "ユーリス"
# 「男同士……か」
line = "「男同士……か」"

[[dialogue]]
speaker = "ユーリス"
# 「あのことは……誰にも言ってないんだね」
line = "「あのことは……誰にも言ってないんだね」"

[[dialogue]]
speaker = "unk"
# もちろん
line = "もちろん"

[[dialogue]]
speaker = "ユーリス"
# 「ありがとう」
line = "「ありがとう」"

[[dialogue]]
speaker = "ユーリス"
# 「…………見た？」
line = "「…………見た？」"

[[dialogue]]
speaker = "unk"
# ごめん！　そんなつもりじゃなくて……
line = "ごめん！　そんなつもりじゃなくて……"

[[dialogue]]
speaker = "ユーリス"
# 「うん、わかってるよ。鍵をかけ忘れた私がうっかりしていた……」
line = "「うん、わかってるよ。鍵をかけ忘れた私がうっかりしていた……」"

[[dialogue]]
speaker = "ユーリス"
# 「君がトイレで見た通り、私は女だ」
line = "「君がトイレで見た通り、私は女だ」"

[[dialogue]]
speaker = "ユーリス"
# 「本当の名前は、ユリアーナ・フォン・ジルラント。ジルラント王国の王女だ」
line = "「本当の名前は、ユリアーナ・フォン・ジルラント。ジルラント王国の王女だ」"

[[dialogue]]
speaker = "unk"
# どうして性別を隠していたんだ？
line = "どうして性別を隠していたんだ？"

[[dialogue]]
speaker = "ユーリス"
# 「言ったよね、聖剣と王位は代々男が受け継ぐものだって。それなのに女の私が聖剣に選ばれてしまったんだ……」
line = "「言ったよね、聖剣と王位は代々男が受け継ぐものだって。それなのに女の私が聖剣に選ばれてしまったんだ……」"

[[dialogue]]
speaker = "ユーリス"
# 「当時のジルラント王国は、相次ぐアステラの出現で大きな被害を受けていてね」
line = "「当時のジルラント王国は、相次ぐアステラの出現で大きな被害を受けていてね」"

[[dialogue]]
speaker = "ユーリス"
# 「戦う力のない国民たちの不安は、想像すらできないものだったろう。せめて彼らに安心を与えることが私たち王族の役目だった」
line = "「戦う力のない国民たちの不安は、想像すらできないものだったろう。せめて彼らに安心を与えることが私たち王族の役目だった」"

[[dialogue]]
speaker = "ユーリス"
# 「歴史上、例のない女性の聖剣使い──だなんて。あんなナーバスな時期に発表できるものじゃなかった」
line = "「歴史上、例のない女性の聖剣使い──だなんて。あんなナーバスな時期に発表できるものじゃなかった」"

[[dialogue]]
speaker = "ユーリス"
# 「だから名前も『ユーリス』に改めた。男装をして聖剣を担いで国民の前に立った時……」
line = "「だから名前も『ユーリス』に改めた。男装をして聖剣を担いで国民の前に立った時……」"

[[dialogue]]
speaker = "ユーリス"
# 「みんな救われた顔をしていた。安心していた。私は正しいことをしたんだって思った」
line = "「みんな救われた顔をしていた。安心していた。私は正しいことをしたんだって思った」"

[[dialogue]]
speaker = "ユーリス"
# 「新星学園に入学する時も、王子ユーリスとして華々しく送ってもらったからね。こっちで女に戻るわけにもいかないよ」
line = "「新星学園に入学する時も、王子ユーリスとして華々しく送ってもらったからね。こっちで女に戻るわけにもいかないよ」"

[[dialogue]]
speaker = "ユーリス"
# 「今まで騙していてごめん。君を傷つけるつもりはなかったんだけど……」
line = "「今まで騙していてごめん。君を傷つけるつもりはなかったんだけど……」"

[[dialogue]]
speaker = "unk"
# 怒ってないから大丈夫
line = "怒ってないから大丈夫"

[[dialogue]]
speaker = "ユーリス"
# 「ありがとう。やはり会長はかけがえのない友達だ」
line = "「ありがとう。やはり会長はかけがえのない友達だ」"

[[dialogue]]
speaker = "unk"
# いや、親友だ
line = "いや、親友だ"

[[dialogue]]
speaker = "ユーリス"
# 「──！」
line = "「──！」"

[[dialogue]]
speaker = "ユーリス"
# 「そう言ってくれると本当に嬉しい。この国に来て良かったと、心からそう思うよ」
line = "「そう言ってくれると本当に嬉しい。この国に来て良かったと、心からそう思うよ」"

[[dialogue]]
speaker = "ユーリス"
# 「ごめんね。会長もみんなに隠し事をすることになってしまって」
line = "「ごめんね。会長もみんなに隠し事をすることになってしまって」"

[[dialogue]]
speaker = "ユーリス"
# 「でも、私の勇者スキル習得に無理に付き合ってくれなくていいんだよ？　会長も年頃の男子なんだから、女の子とデートに行きたいだろうし」
line = "「でも、私の勇者スキル習得に無理に付き合ってくれなくていいんだよ？　会長も年頃の男子なんだから、女の子とデートに行きたいだろうし」"

[[dialogue]]
speaker = "unk"
# おうちデートっていうのもあるぞ
line = "おうちデートっていうのもあるぞ"

[[dialogue]]
speaker = "ユーリス"
# 「えっ、じゃあ私と会長がデート……！？　いやいや、そもそも今の私は女の子に含まれるの……？」
line = "「えっ、じゃあ私と会長がデート……！？　いやいや、そもそも今の私は女の子に含まれるの……？」"

[[dialogue]]
speaker = "ユーリス"
# 「男として生きていくと誓ったはずなのに、嬉しく思ってる自分がいる。はは……我ながら現金だな」
line = "「男として生きていくと誓ったはずなのに、嬉しく思ってる自分がいる。はは……我ながら現金だな」"

[[dialogue]]
speaker = "unk"
# ユーリスが女の子で正直ほっとした
line = "ユーリスが女の子で正直ほっとした"

[[dialogue]]
speaker = "ユーリス"
# 「……え？　どうして？」
line = "「……え？　どうして？」"

[[dialogue]]
speaker = "ユーリス"
# 「時々ユーリスが女の子に見えてたから……？　ええっ！？」
line = "「時々ユーリスが女の子に見えてたから……？　ええっ！？」"

[[dialogue]]
speaker = "ユーリス"
# 「……な、なるほど。ユーリスは男のはずなのに、一瞬女の子に見えて、男にドキッとしたのかもって思ってた時期もあったと」
line = "「……な、なるほど。ユーリスは男のはずなのに、一瞬女の子に見えて、男にドキッとしたのかもって思ってた時期もあったと」"

[[dialogue]]
speaker = "ユーリス"
# 「はは……まさかお見通しとは。いや、まさかでもないか。思い返すと心当たりがいくつか……」
line = "「はは……まさかお見通しとは。いや、まさかでもないか。思い返すと心当たりがいくつか……」"

[[dialogue]]
speaker = "ユーリス"
# 「ありがとう、会長。こんな私でも受け入れてくれて」
line = "「ありがとう、会長。こんな私でも受け入れてくれて」"

[[dialogue]]
speaker = "ユーリス"
# 「こんなこと言うのもなんだけど……バレたのが会長で良かった。ずっとひとりで秘密を抱えるのはしんどかったから」
line = "「こんなこと言うのもなんだけど……バレたのが会長で良かった。ずっとひとりで秘密を抱えるのはしんどかったから」"

[[dialogue]]
speaker = "ユーリス"
# 「こんなに助けてもらって、仲良くしてもらって、何もしないのはジルラント家の名折れだ」
line = "「こんなに助けてもらって、仲良くしてもらって、何もしないのはジルラント家の名折れだ」"

[[dialogue]]
speaker = "ユーリス"
# 「これから先、君が窮地に陥った時は誰よりも早く駆け付ける。聖剣にかけて誓うよ」
line = "「これから先、君が窮地に陥った時は誰よりも早く駆け付ける。聖剣にかけて誓うよ」"

[[dialogue]]
speaker = "ユーリス"
# 「ユーリス・フォン・ジルラントとして」
line = "「ユーリス・フォン・ジルラントとして」"

[[dialogue]]
speaker = "ユーリス"
# 「そして……ユリアーナ・フォン・ジルラントとしてもね」
line = "「そして……ユリアーナ・フォン・ジルラントとしてもね」"

[[dialogue]]
speaker = "ユーリス"
# 「これからもよろしくね、会長」
line = "「これからもよろしくね、会長」"
