[[dialogue]]
speaker = "unk"
# 第１話,天使なシスターさん,P
line = "第１話,天使なシスターさん,P"

[[dialogue]]
speaker = "unk"
# リクリエの時に暴虐を働いた『魔王』を倒した様子を描いたのが、ここにある『太陽の壁画』と言われている。
line = "リクリエの時に暴虐を働いた『魔王』を倒した様子を描いたのが、ここにある『太陽の壁画』と言われている。"

[[dialogue]]
speaker = "unk"
# しかしヴィーナスは、魔王はリクリエから世界を救った英雄だと言っていた。いったいどちらが正しいのだろう？
line = "しかしヴィーナスは、魔王はリクリエから世界を救った英雄だと言っていた。いったいどちらが正しいのだろう？"

[[dialogue]]
speaker = "シャロン"
# 「難しそうな顔をしてどうされましたか、会長さま？」
line = "「難しそうな顔をしてどうされましたか、会長さま？」"

[[dialogue]]
speaker = "シャロン"
# 「おや、申し遅れましたね。私は教皇庁所属のシスター、シャロン・ミストリアと申します。会長さまと同じく新星学園の２年生です」
line = "「おや、申し遅れましたね。私は教皇庁所属のシスター、シャロン・ミストリアと申します。会長さまと同じく新星学園の２年生です」"

[[dialogue]]
speaker = "シャロン"
# 「住まいは流星市国内の修道院ですが、学園に通いながら、この大聖堂の管理をお手伝いさせていただいております」
line = "「住まいは流星市国内の修道院ですが、学園に通いながら、この大聖堂の管理をお手伝いさせていただいております」"

[[dialogue]]
speaker = "unk"
# お疲れ様です
line = "お疲れ様です"

[[dialogue]]
speaker = "シャロン"
# 「いいえ、シスターは神に仕えるものですから。それにこの大聖殿は世界の信仰の中心。お掃除させていただけるのは光栄なことです」
line = "「いいえ、シスターは神に仕えるものですから。それにこの大聖殿は世界の信仰の中心。お掃除させていただけるのは光栄なことです」"

[[dialogue]]
speaker = "シャロン"
# 「それより会長さま、あまりお元気がないようですが……やはり星徒会のお仕事がお忙しいのでしょうか」
line = "「それより会長さま、あまりお元気がないようですが……やはり星徒会のお仕事がお忙しいのでしょうか」"

[[dialogue]]
speaker = "シャロン"
# 「会長さまは新星学園に転入されてきたばかり。それにここは普通の学び舎とは違う、星騎士の学園です」
line = "「会長さまは新星学園に転入されてきたばかり。それにここは普通の学び舎とは違う、星騎士の学園です」"

[[dialogue]]
speaker = "シャロン"
# 「ただでさえ慣れない環境で、星徒会長のお仕事も求められるのですから、きっと苦労なさることもあるでしょう。心中お察しいたします」
line = "「ただでさえ慣れない環境で、星徒会長のお仕事も求められるのですから、きっと苦労なさることもあるでしょう。心中お察しいたします」"

[[dialogue]]
speaker = "シャロン"
# 「何か私にお手伝いできることはありませんか？」
line = "「何か私にお手伝いできることはありませんか？」"

[[dialogue]]
speaker = "unk"
# 今のところ大丈夫
line = "今のところ大丈夫"

[[dialogue]]
speaker = "シャロン"
# 「そうですか、会長さまはお強いのですね。ですが、どうか無理はされないように」
line = "「そうですか、会長さまはお強いのですね。ですが、どうか無理はされないように」"

[[dialogue]]
speaker = "シャロン"
# 「では私は聖堂のお掃除がありますので、失礼いたします。お力になれることがあればいつでもお声がけください」
line = "「では私は聖堂のお掃除がありますので、失礼いたします。お力になれることがあればいつでもお声がけください」"

[[dialogue]]
speaker = "ヴィーナス"
# 「今日も星徒会お疲れ様～」
line = "「今日も星徒会お疲れ様～」"

[[dialogue]]
speaker = "マトイ"
# 「まさかベリーダンス部があんな過激な衣装を作ってるなんて……セクシーっていってもさすがにあれはアウトでしょ……」
line = "「まさかベリーダンス部があんな過激な衣装を作ってるなんて……セクシーっていってもさすがにあれはアウトでしょ……」"

[[dialogue]]
speaker = "サーシャ"
# 「川釣り部が餌用に育てたミミズが大量に逃げ出すなんて思わなかったわ～」
line = "「川釣り部が餌用に育てたミミズが大量に逃げ出すなんて思わなかったわ～」"

[[dialogue]]
speaker = "アナ"
# 「現代美術部がグラウンドにピラミッド建てようとしてた。もちろん止めたけど」
line = "「現代美術部がグラウンドにピラミッド建てようとしてた。もちろん止めたけど」"

[[dialogue]]
speaker = "サーシャ"
# 「あ、部活のフリーダムさにクロトくんが困惑気味ね～」
line = "「あ、部活のフリーダムさにクロトくんが困惑気味ね～」"

[[dialogue]]
speaker = "マトイ"
# 「私が着たら恥ずかしい以前にすごく貧相なんだろうな……あんなのスタイルがいい人しか着られないでしょ……私もヴィーナスやサーシャさんみたいなら……」
line = "「私が着たら恥ずかしい以前にすごく貧相なんだろうな……あんなのスタイルがいい人しか着られないでしょ……私もヴィーナスやサーシャさんみたいなら……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「マトイ～、何ぶつぶつ言ってるの？」
line = "「マトイ～、何ぶつぶつ言ってるの？」"

[[dialogue]]
speaker = "シャロン"
# 「お疲れ様です！」
line = "「お疲れ様です！」"

[[dialogue]]
speaker = "マトイ"
# 「シャロンさん！？」
line = "「シャロンさん！？」"

[[dialogue]]
speaker = "シャロン"
# 「ご多忙な星徒会役員の皆さまのため、栄養ドリンクをお作りしましたっ」
line = "「ご多忙な星徒会役員の皆さまのため、栄養ドリンクをお作りしましたっ」"

[[dialogue]]
speaker = "unk"
# 昨日となんか違う！？
line = "昨日となんか違う！？"

[[dialogue]]
speaker = "シャロン"
# 「女神様のご慈悲をあまねく届かせるのが私の務め。いてもたってもいられず星徒会室を訪ねてしまいましたっ」
line = "「女神様のご慈悲をあまねく届かせるのが私の務め。いてもたってもいられず星徒会室を訪ねてしまいましたっ」"

[[dialogue]]
speaker = "マトイ"
# 「あ～……シャロンさんはいつもは清楚なシスターさんなんだけど、スイッチ入るとこうなるからね……」
line = "「あ～……シャロンさんはいつもは清楚なシスターさんなんだけど、スイッチ入るとこうなるからね……」"

[[dialogue]]
speaker = "サーシャ"
# 「どちらかというと、こっちが地の性格っぽいわね～」
line = "「どちらかというと、こっちが地の性格っぽいわね～」"

[[dialogue]]
speaker = "シャロン"
# 「さぁ、どうぞどうぞ。今お世話になっている修道院に伝わる疲労回復ドリンクですっ」
line = "「さぁ、どうぞどうぞ。今お世話になっている修道院に伝わる疲労回復ドリンクですっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「じゃあ遠慮なくいただくわ。味は……うん、まずまずってところかしら」
line = "「じゃあ遠慮なくいただくわ。味は……うん、まずまずってところかしら」"

[[dialogue]]
speaker = "サーシャ"
# 「お酢が入っているみたい。体に良さそうね～」
line = "「お酢が入っているみたい。体に良さそうね～」"

[[dialogue]]
speaker = "マトイ"
# 「あ、私は飲みやすくて好きかも。トレーニングの後とかに良さそう」
line = "「あ、私は飲みやすくて好きかも。トレーニングの後とかに良さそう」"

[[dialogue]]
speaker = "アナ"
# 「酢に含まれるクエン酸は疲労回復に有用な成分です」
line = "「酢に含まれるクエン酸は疲労回復に有用な成分です」"

[[dialogue]]
speaker = "シャロン"
# 「ささ、会長さまもどうぞ。グイっと一気に！」
line = "「ささ、会長さまもどうぞ。グイっと一気に！」"

[[dialogue]]
speaker = "unk"
# すっぱい！　……けど確かに効きそう
line = "すっぱい！　……けど確かに効きそう"

[[dialogue]]
speaker = "シャロン"
# 「そうでしょうそうでしょう。他にお力になれることはありませんかっ？　お腹は空いていませんかっ？　勉強でご不便はありませんかっ？」
line = "「そうでしょうそうでしょう。他にお力になれることはありませんかっ？　お腹は空いていませんかっ？　勉強でご不便はありませんかっ？」"

[[dialogue]]
speaker = "シャロン"
# 「宿題はお済みですかっ？　マッサージしましょうかっ？　　膝枕でお休みされますかっ？」
line = "「宿題はお済みですかっ？　マッサージしましょうかっ？　　膝枕でお休みされますかっ？」"

[[dialogue]]
speaker = "マトイ"
# 「圧がすごい……」
line = "「圧がすごい……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ちょっとちょっと、膝枕はやりすぎなんじゃない？　クロトには私たちがいるんだから。マッサージくらいにしときなさい」
line = "「ちょっとちょっと、膝枕はやりすぎなんじゃない？　クロトには私たちがいるんだから。マッサージくらいにしときなさい」"

[[dialogue]]
speaker = "シャロン"
# 「マッサージですね、わかりましたっ。では失礼して……」
line = "「マッサージですね、わかりましたっ。では失礼して……」"

[[dialogue]]
speaker = "unk"
# ああああああぁっ！？
line = "ああああああぁっ！？"

[[dialogue]]
speaker = "サーシャ"
# 「とっても痛そうなマッサージね～」
line = "「とっても痛そうなマッサージね～」"

[[dialogue]]
speaker = "マトイ"
# 「ごめんなさい。やっぱりシャロンさんは止められないわ……」
line = "「ごめんなさい。やっぱりシャロンさんは止められないわ……」"
