[[dialogue]]
speaker = "unk"
# 第３話,花よりお団子ルリエル,P
line = "第３話,花よりお団子ルリエル,P"

[[dialogue]]
speaker = "unk"
# ステラとラファエロが元の世界に戻り、フィオナたちも流星市国に帰ってきた。ここ最近はドタバタしていたが、ようやくのんびりできる放課後だ。
line = "ステラとラファエロが元の世界に戻り、フィオナたちも流星市国に帰ってきた。ここ最近はドタバタしていたが、ようやくのんびりできる放課後だ。"

[[dialogue]]
speaker = "unk"
# そこで俺は、恋人であるルリエルをデートに誘うことにした──
line = "そこで俺は、恋人であるルリエルをデートに誘うことにした──"

[[dialogue]]
speaker = "ルリエル"
# 「えへへへへへへぇ～<emoji=heart04>　会長さんとお出かけするの、久しぶりなのです♪」
line = "「えへへへへへへぇ～<emoji=heart04>　会長さんとお出かけするの、久しぶりなのです♪」"

[[dialogue]]
speaker = "unk"
# 今日もステラの衣装なんだ？
line = "今日もステラの衣装なんだ？"

[[dialogue]]
speaker = "ルリエル"
# 「はいなのです！　ステラさんの衣装、とっても可愛いですし、動きやすいから気に入っちゃいました～♪」
line = "「はいなのです！　ステラさんの衣装、とっても可愛いですし、動きやすいから気に入っちゃいました～♪」"

[[dialogue]]
speaker = "ルリエル"
# 「そういえば恋人の会長さんから、この格好のルリエルの感想、聞いてませんでした。どうですかー？」
line = "「そういえば恋人の会長さんから、この格好のルリエルの感想、聞いてませんでした。どうですかー？」"

[[dialogue]]
speaker = "unk"
# 似合ってるよ。すごく可愛い
line = "似合ってるよ。すごく可愛い"

[[dialogue]]
speaker = "ルリエル"
# 「むふふ～<emoji=heart04>　もっともーっと、褒めてくれていいのですよ～？　ルリエルは褒められて伸びるタイプですから！」
line = "「むふふ～<emoji=heart04>　もっともーっと、褒めてくれていいのですよ～？　ルリエルは褒められて伸びるタイプですから！」"

[[dialogue]]
speaker = "ルリエル"
# 「あっ、そうです！　お出かけ前に、花壇の様子を見てもいいですか？」
line = "「あっ、そうです！　お出かけ前に、花壇の様子を見てもいいですか？」"

[[dialogue]]
speaker = "ルリエル"
# 「じゃーん♪　このあたりのお花は、ルリエルもお世話を手伝っているのです！」
line = "「じゃーん♪　このあたりのお花は、ルリエルもお世話を手伝っているのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「カティアさんと最近、とっても仲良しになりまして～……この白くて小さいお花、名前わかりますか？」
line = "「カティアさんと最近、とっても仲良しになりまして～……この白くて小さいお花、名前わかりますか？」"

[[dialogue]]
speaker = "unk"
# 星の形をした花──『ステラ』だね
line = "星の形をした花──『ステラ』だね"

[[dialogue]]
speaker = "ルリエル"
# 「わっ、正解なのです！　そうなんです、カティアさんが好きなお花を植えていいって言ってくれたので──ステラを選びました！」
line = "「わっ、正解なのです！　そうなんです、カティアさんが好きなお花を植えていいって言ってくれたので──ステラを選びました！」"

[[dialogue]]
speaker = "ルリエル"
# 「会長さん、それにしてもよくご存知ですね！　ルリエル、図鑑で調べるまで知らなかったのです」
line = "「会長さん、それにしてもよくご存知ですね！　ルリエル、図鑑で調べるまで知らなかったのです」"

[[dialogue]]
speaker = "unk"
# 昔、花屋でアルバイトしてたから
line = "昔、花屋でアルバイトしてたから"

[[dialogue]]
speaker = "ルリエル"
# 「はぇ～、会長さんって本当にいろいろなところで働いてますね～。じゃあ、カティアさんだけがお世話してる、あっちの花の名前もわかったり？」
line = "「はぇ～、会長さんって本当にいろいろなところで働いてますね～。じゃあ、カティアさんだけがお世話してる、あっちの花の名前もわかったり？」"

[[dialogue]]
speaker = "unk"
# 全部わかるよ。右から順に──
line = "全部わかるよ。右から順に──"

[[dialogue]]
speaker = "ルリエル"
# 「ふわ～、本当に物知りさんなのです♪　会長さんとお付き合いしてると、ルリエルもどんどん賢くなっちゃうのです！」
line = "「ふわ～、本当に物知りさんなのです♪　会長さんとお付き合いしてると、ルリエルもどんどん賢くなっちゃうのです！」"

[[dialogue]]
speaker = "unk"
# ステラやラファエロと交流をした影響か、ルリエルは自然や藝術といったものにも好奇心のアンテナが向き始めているみたいだ。
line = "ステラやラファエロと交流をした影響か、ルリエルは自然や藝術といったものにも好奇心のアンテナが向き始めているみたいだ。"

[[dialogue]]
speaker = "unk"
# だったら今日のデートの行き先も、ちょっと変更してみようか──
line = "だったら今日のデートの行き先も、ちょっと変更してみようか──"

[[dialogue]]
speaker = "ルリエル"
# 「屋上庭園、驚きました……！　繁華街のビルの上に、あんなに自然豊かなスポットがあるだなんて！」
line = "「屋上庭園、驚きました……！　繁華街のビルの上に、あんなに自然豊かなスポットがあるだなんて！」"

[[dialogue]]
speaker = "unk"
# たまにはこういうデートもいいね
line = "たまにはこういうデートもいいね"

[[dialogue]]
speaker = "ルリエル"
# 「はい！　それに会長さんが一緒だと、お花についていろんな解説をしてもらえるから、とっても楽しいのです～♪」
line = "「はい！　それに会長さんが一緒だと、お花についていろんな解説をしてもらえるから、とっても楽しいのです～♪」"

[[dialogue]]
speaker = "ルリエル"
# 「せっかくなので、お花だけでなく藝術にも触れたいのです！　確かこの近くに、おっきな美術館が──」
line = "「せっかくなので、お花だけでなく藝術にも触れたいのです！　確かこの近くに、おっきな美術館が──」"

[[dialogue]]
speaker = "unk"
# 案内は任せて
line = "案内は任せて"

[[dialogue]]
speaker = "unk"
# 昔、アルバイトしてた美術館だな
line = "昔、アルバイトしてた美術館だな"

[[dialogue]]
speaker = "ルリエル"
# 「……たまに思うのですが。会長さんってどこなら働いたことがないのでしょう？」
line = "「……たまに思うのですが。会長さんってどこなら働いたことがないのでしょう？」"

[[dialogue]]
speaker = "unk"
# 翌日──昼休みの流星星徒会室にて、ルリエルは恋人であるクロトとのデートを、他の役員たちに語っていた。
line = "翌日──昼休みの流星星徒会室にて、ルリエルは恋人であるクロトとのデートを、他の役員たちに語っていた。"

[[dialogue]]
speaker = "ソフィア"
# 「屋上庭園に美術館……？　ルリにしては、ずいぶんと似つかわしくないところに……」
line = "「屋上庭園に美術館……？　ルリにしては、ずいぶんと似つかわしくないところに……」"

[[dialogue]]
speaker = "ルリエル"
# 「似つかわしくないってなんですか～！？　最近のルリエルは、自然や藝術にも興味が出てきたんです！　オトナの女性なのですよ～！」
line = "「似つかわしくないってなんですか～！？　最近のルリエルは、自然や藝術にも興味が出てきたんです！　オトナの女性なのですよ～！」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふっ、緋宮会長と仲良しみたいで何よりです。どんな花や絵画を見てきたんですか？」
line = "「ふふっ、緋宮会長と仲良しみたいで何よりです。どんな花や絵画を見てきたんですか？」"

[[dialogue]]
speaker = "ソフィア"
# 「確かに。私もあんまり行く場所じゃないので、感想が気になります」
line = "「確かに。私もあんまり行く場所じゃないので、感想が気になります」"

[[dialogue]]
speaker = "ルリエル"
# 「はいです、とっても楽しかったんですよー！　えっと、屋上庭園ではお花を見ながら、ベンチでゆっくりできるんです！」
line = "「はいです、とっても楽しかったんですよー！　えっと、屋上庭園ではお花を見ながら、ベンチでゆっくりできるんです！」"

[[dialogue]]
speaker = "ルリエル"
# 「近くの売店で売ってる、季節のお花のジュースが格別で！　フルーツとはまた違った甘さがありまして～♪」
line = "「近くの売店で売ってる、季節のお花のジュースが格別で！　フルーツとはまた違った甘さがありまして～♪」"

[[dialogue]]
speaker = "ソフィア"
# 「…………ん？」
line = "「…………ん？」"

[[dialogue]]
speaker = "ルリエル"
# 「それでそれで、美術館の中にはカフェスペースがあるんです！　藝術家さんが愛した紅茶とケーキのセットが楽しめて、これまた絶品で～！」
line = "「それでそれで、美術館の中にはカフェスペースがあるんです！　藝術家さんが愛した紅茶とケーキのセットが楽しめて、これまた絶品で～！」"

[[dialogue]]
speaker = "フィオナ"
# 「…………なるほど」
line = "「…………なるほど」"

[[dialogue]]
speaker = "ルリエル"
# 「えへへ～。会長さんとこっそり、あーんって食べさせあいっこをしたりですね～……<emoji=heart04>」
line = "「えへへ～。会長さんとこっそり、あーんって食べさせあいっこをしたりですね～……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「…………思ってたのと違う感想が来ましたね。流石はルリ」
line = "「…………思ってたのと違う感想が来ましたね。流石はルリ」"

[[dialogue]]
speaker = "ルリエル"
# 「えっ？　何がですか？」
line = "「えっ？　何がですか？」"

[[dialogue]]
speaker = "フィオナ"
# 「まあ、花より団子のルリエルらしいですけれど。ふふふっ」
line = "「まあ、花より団子のルリエルらしいですけれど。ふふふっ」"

[[dialogue]]
speaker = "ソフィア"
# 「オトナの女性にはまだまだ遠いみたいですね……」
line = "「オトナの女性にはまだまだ遠いみたいですね……」"

[[dialogue]]
speaker = "ルリエル"
# 「な、なんなんですか～っ！？」
line = "「な、なんなんですか～っ！？」"

[[dialogue]]
speaker = "unk"
# 自然や藝術への興味が出てきたとはいえ、ルリエルはやっぱりルリエルなのだった──
line = "自然や藝術への興味が出てきたとはいえ、ルリエルはやっぱりルリエルなのだった──"
