[[dialogue]]
speaker = "unk"
# 第１話,応援タッグバトル（前編）,P
line = "第１話,応援タッグバトル（前編）,P"

[[dialogue]]
speaker = "ミルフィー"
# 「２人とも頑張れーっ！」
line = "「２人とも頑張れーっ！」"

[[dialogue]]
speaker = "カティア"
# 「たぁああぁぁぁぁぁっ！」
line = "「たぁああぁぁぁぁぁっ！」"

[[dialogue]]
speaker = "ヒヨ"
# 「うぉおおりゃあぁああっ！」
line = "「うぉおおりゃあぁああっ！」"

[[dialogue]]
speaker = "unk"
# ミルフィーの声援を受けながら、カティアとヒヨは抜きつ抜かれつトラックを疾走する。
line = "ミルフィーの声援を受けながら、カティアとヒヨは抜きつ抜かれつトラックを疾走する。"

[[dialogue]]
speaker = "ヒヨ"
# 「くぅぅ、追いつけねえかっ！」
line = "「くぅぅ、追いつけねえかっ！」"

[[dialogue]]
speaker = "カティア"
# 「ゴールっ！　勝った勝ったー！　魔王様、見ててくれましたかー！」
line = "「ゴールっ！　勝った勝ったー！　魔王様、見ててくれましたかー！」"

[[dialogue]]
speaker = "unk"
# ナイスラン！
line = "ナイスラン！"

[[dialogue]]
speaker = "ヒヨ"
# 「かー、負けちまったい！　姐さんの前で記念の勝利を飾れると思ったのによぉ！」
line = "「かー、負けちまったい！　姐さんの前で記念の勝利を飾れると思ったのによぉ！」"

[[dialogue]]
speaker = "カティア"
# 「ふふーん、魔王様の前でいいカッコさせるわけにはいかないワン！」
line = "「ふふーん、魔王様の前でいいカッコさせるわけにはいかないワン！」"

[[dialogue]]
speaker = "ミルフィー"
# 「記念の勝利？」
line = "「記念の勝利？」"

[[dialogue]]
speaker = "カティア"
# 「今、私が勝って、ヒヨとの戦歴が１９８戦９９勝になったんです！」
line = "「今、私が勝って、ヒヨとの戦歴が１９８戦９９勝になったんです！」"

[[dialogue]]
speaker = "unk"
# ９９勝！？
line = "９９勝！？"

[[dialogue]]
speaker = "unk"
# １９８戦！？
line = "１９８戦！？"

[[dialogue]]
speaker = "ヒヨ"
# 「今の勝負に、あたしの１００勝目がかかってたってわけさあ」
line = "「今の勝負に、あたしの１００勝目がかかってたってわけさあ」"

[[dialogue]]
speaker = "ミルフィー"
# 「それだけの回数競い合ってるってことにも、五分五分の引き分けっていうのも驚きだよ……」
line = "「それだけの回数競い合ってるってことにも、五分五分の引き分けっていうのも驚きだよ……」"

[[dialogue]]
speaker = "ヒヨ"
# 「ワン公とはレース以外でも大なり小なり競い合ってっからなあ……簡易戦闘服で速く走れるようになってから、更に手強くなったぜえ」
line = "「ワン公とはレース以外でも大なり小なり競い合ってっからなあ……簡易戦闘服で速く走れるようになってから、更に手強くなったぜえ」"

[[dialogue]]
speaker = "カティア"
# 「次の勝負は、どっちかが１００勝目になるメモリアルレースですガオ！」
line = "「次の勝負は、どっちかが１００勝目になるメモリアルレースですガオ！」"

[[dialogue]]
speaker = "ヒヨ"
# 「絶対にワン公に負けたくねえ！　姐さん、あたしのために一肌脱いじゃくれねえか！」
line = "「絶対にワン公に負けたくねえ！　姐さん、あたしのために一肌脱いじゃくれねえか！」"

[[dialogue]]
speaker = "ミルフィー"
# 「ええっ！？　一肌脱ぐって──」
line = "「ええっ！？　一肌脱ぐって──」"

[[dialogue]]
speaker = "カティア"
# 「魔王様！　第一のしもべとして、絶対にヒヨより先に１００回勝ちたいですガオ！」
line = "「魔王様！　第一のしもべとして、絶対にヒヨより先に１００回勝ちたいですガオ！」"

[[dialogue]]
speaker = "カティア"
# 「だから、星霊祭の時みたいな本気の応援をお願いします！」
line = "「だから、星霊祭の時みたいな本気の応援をお願いします！」"

[[dialogue]]
speaker = "ヒヨ"
# 「姐さんにも頼みます！」
line = "「姐さんにも頼みます！」"

[[dialogue]]
speaker = "ミルフィー"
# 「あ、一肌脱ぐってそういうこと？」
line = "「あ、一肌脱ぐってそういうこと？」"

[[dialogue]]
speaker = "カティア"
# 「わふ？　なんだと思ったんです？」
line = "「わふ？　なんだと思ったんです？」"

[[dialogue]]
speaker = "ミルフィー"
# 「な、なんとも思ってないよ？」
line = "「な、なんとも思ってないよ？」"

[[dialogue]]
speaker = "unk"
# 本気の応援、任された！
line = "本気の応援、任された！"

[[dialogue]]
speaker = "ミルフィー"
# 「会長くんがやるなら、私もやらないわけにはいかないね。任せて、ヒヨちゃん」
line = "「会長くんがやるなら、私もやらないわけにはいかないね。任せて、ヒヨちゃん」"

[[dialogue]]
speaker = "ヒヨ"
# 「つまり、これはあたしと姐さんタッグＶＳ──」
line = "「つまり、これはあたしと姐さんタッグＶＳ──」"

[[dialogue]]
speaker = "カティア"
# 「私と魔王様チームのタッグバトルってことだワン！」
line = "「私と魔王様チームのタッグバトルってことだワン！」"

[[dialogue]]
speaker = "ヒヨ"
# 「せっかくの記念レースなんだ。ただ勝った負けただけじゃ面白くねえなあ？」
line = "「せっかくの記念レースなんだ。ただ勝った負けただけじゃ面白くねえなあ？」"

[[dialogue]]
speaker = "カティア"
# 「ふっふっふ、私もそう思ってたところだワン」
line = "「ふっふっふ、私もそう思ってたところだワン」"

[[dialogue]]
speaker = "カティア"
# 「負けた方は、勝った方の命令をひとつ、聞かなきゃいけないってのはどうですガオ？」
line = "「負けた方は、勝った方の命令をひとつ、聞かなきゃいけないってのはどうですガオ？」"

[[dialogue]]
speaker = "ミルフィー"
# 「望むところだよ！」
line = "「望むところだよ！」"

[[dialogue]]
speaker = "unk"
# 望んじゃった……
line = "望んじゃった……"

[[dialogue]]
speaker = "ヒヨ"
# 「勝負は明日の放課後、このグラウンドで！」
line = "「勝負は明日の放課後、このグラウンドで！」"

[[dialogue]]
speaker = "カティア"
# 「しっかりシャンプーして待っていろガオ！」
line = "「しっかりシャンプーして待っていろガオ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「……首を洗って待っていろ、って言いたかったのかな？」
line = "「……首を洗って待っていろ、って言いたかったのかな？」"

[[dialogue]]
speaker = "ミルフィー"
# 「本気で競い合えるライバルがいるのって良いよね」
line = "「本気で競い合えるライバルがいるのって良いよね」"

[[dialogue]]
speaker = "ミルフィー"
# 「だけど１００勝目がかかってるんだよね……ヒヨちゃんに勝たせてあげたいなぁ」
line = "「だけど１００勝目がかかってるんだよね……ヒヨちゃんに勝たせてあげたいなぁ」"

[[dialogue]]
speaker = "unk"
# 俺もカティアを勝たせたい
line = "俺もカティアを勝たせたい"

[[dialogue]]
speaker = "ミルフィー"
# 「ヒヨちゃんとカティアちゃんの実力がほぼ互角ってことは──勝敗は私たちの応援にかかっているといっても過言じゃないね」
line = "「ヒヨちゃんとカティアちゃんの実力がほぼ互角ってことは──勝敗は私たちの応援にかかっているといっても過言じゃないね」"

[[dialogue]]
speaker = "ミルフィー"
# 「私と会長くんも明日は競い合うライバル同士だ、ふふ」
line = "「私と会長くんも明日は競い合うライバル同士だ、ふふ」"

[[dialogue]]
speaker = "ミルフィー"
# 「あー、そういえば……負けた方は勝った方の命令を聞かなきゃいけないのって、やっぱり私たちも……かな？」
line = "「あー、そういえば……負けた方は勝った方の命令を聞かなきゃいけないのって、やっぱり私たちも……かな？」"

[[dialogue]]
speaker = "unk"
# 連帯責任で
line = "連帯責任で"

[[dialogue]]
speaker = "unk"
# タッグだからね
line = "タッグだからね"

[[dialogue]]
speaker = "ミルフィー"
# 「そ、そうだよね。タッグだもんね！」
line = "「そ、そうだよね。タッグだもんね！」"

[[dialogue]]
speaker = "ミルフィー"
# （つまりヒヨちゃんが勝ったら、会長くんに命令できちゃうってこと……！？）
line = "（つまりヒヨちゃんが勝ったら、会長くんに命令できちゃうってこと……！？）"

[[dialogue]]
speaker = "ミルフィー"
# （えっ、えっ、どうしよ……！　どんなお願いしようかな……）
line = "（えっ、えっ、どうしよ……！　どんなお願いしようかな……）"

[[dialogue]]
speaker = "ミルフィー"
# （あんなこととかこんなことでもいいのかな……えへ、えへへ……<emoji=heart04>）
line = "（あんなこととかこんなことでもいいのかな……えへ、えへへ……<emoji=heart04>）"

[[dialogue]]
speaker = "ミルフィー"
# 「明日の応援、絶対に負けないからねっ！　帰ったら、少し練習しておこうっと！」
line = "「明日の応援、絶対に負けないからねっ！　帰ったら、少し練習しておこうっと！」"

[[dialogue]]
speaker = "unk"
# カティアやヒヨ以上に、ミルフィーは闘志を燃やしているようにも見えた。
line = "カティアやヒヨ以上に、ミルフィーは闘志を燃やしているようにも見えた。"

[[dialogue]]
speaker = "unk"
# 明日の応援勝負、負けられない！
line = "明日の応援勝負、負けられない！"
