[[dialogue]]
speaker = "unk"
# 第２話,退かない、媚びない、省みない！,P
line = "第２話,退かない、媚びない、省みない！,P"

[[dialogue]]
speaker = "アナ"
# 「なるほど。この方が前会長が話していたクルセイダースの……」
line = "「なるほど。この方が前会長が話していたクルセイダースの……」"

[[dialogue]]
speaker = "マトイ"
# 「大昔の英雄って言うから、もっと怖そうな人を想像してたけど、私たちとそう見た目も変わらないね？　同年代くらいかも……」
line = "「大昔の英雄って言うから、もっと怖そうな人を想像してたけど、私たちとそう見た目も変わらないね？　同年代くらいかも……」"

[[dialogue]]
speaker = "サーシャ"
# 「確かにイメージとは違うわね～。肖像画なんかだとビシっと描かれてるから～」
line = "「確かにイメージとは違うわね～。肖像画なんかだとビシっと描かれてるから～」"

[[dialogue]]
speaker = "聖沙"
# 「デジャブを感じるわ……。クルセイダースって、この世界じゃそんなに物珍しい存在なのかしら……。これじゃパンダどころか珍獣扱いよ……」
line = "「デジャブを感じるわ……。クルセイダースって、この世界じゃそんなに物珍しい存在なのかしら……。これじゃパンダどころか珍獣扱いよ……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ほらほら、みんな！　あんまりジロジロみたら失礼でしょ。せっかく聖沙が我ら新星学園星徒会を訪ねてきてくれたんだから、まずは自己紹介よ！」
line = "「ほらほら、みんな！　あんまりジロジロみたら失礼でしょ。せっかく聖沙が我ら新星学園星徒会を訪ねてきてくれたんだから、まずは自己紹介よ！」"

[[dialogue]]
speaker = "サーシャ"
# 「そうね～。私は奏サーシャ。前に少しだけお話したかしら～？」
line = "「そうね～。私は奏サーシャ。前に少しだけお話したかしら～？」"

[[dialogue]]
speaker = "聖沙"
# 「あ、その節はパッキーさんがご迷惑を……。本人にはきつーいお仕置きをしておきましたから！」
line = "「あ、その節はパッキーさんがご迷惑を……。本人にはきつーいお仕置きをしておきましたから！」"

[[dialogue]]
speaker = "アナ"
# 「私はアナです。聖沙・<ruby=ブリリアント>Ｂ</ruby>・アリストテレスさんですよね？　とても頼りになる方だと会長たちから伺っています」
line = "「私はアナです。聖沙・<ruby>Ｂ<rt>ブリリアント</rt></ruby>・アリストテレスさんですよね？　とても頼りになる方だと会長たちから伺っています」"

[[dialogue]]
speaker = "マトイ"
# 「詠野マトイです！　星徒会では書記を担当しています！　クルセイダースさまにお会いできるなんて光栄です！」
line = "「詠野マトイです！　星徒会では書記を担当しています！　クルセイダースさまにお会いできるなんて光栄です！」"

[[dialogue]]
speaker = "聖沙"
# 「サーシャさんに、アナさん、それにマトイさんね？　それと──」
line = "「サーシャさんに、アナさん、それにマトイさんね？　それと──」"

[[dialogue]]
speaker = "unk"
# 何を隠そう新星学園の星徒会長です
line = "何を隠そう新星学園の星徒会長です"

[[dialogue]]
speaker = "聖沙"
# 「え、ええ。改めてよろしくね。そう無駄に胸を張ってもらわなくてもいいけれど……」
line = "「え、ええ。改めてよろしくね。そう無駄に胸を張ってもらわなくてもいいけれど……」"

[[dialogue]]
speaker = "聖沙"
# 「それで今日は何用かしら？　何か私に頼み事がある、という話だったけれど」
line = "「それで今日は何用かしら？　何か私に頼み事がある、という話だったけれど」"

[[dialogue]]
speaker = "ヴィーナス"
# 「聖沙には私たちの稽古を付けてもらおうと思って。平行世界の、とはいえ伝説の英雄とお手合わせできる機会なんて滅多にないもの！」
line = "「聖沙には私たちの稽古を付けてもらおうと思って。平行世界の、とはいえ伝説の英雄とお手合わせできる機会なんて滅多にないもの！」"

[[dialogue]]
speaker = "聖沙"
# 「つまり──勝負ということね！　望むところだわ！」
line = "「つまり──勝負ということね！　望むところだわ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「流石は聖沙！　それじゃ各自変身して、トレーニングルームへ集合よ！　特にマトイ！　同じ雷属性の使い手として、みっちり揉んでもらいなさい！」
line = "「流石は聖沙！　それじゃ各自変身して、トレーニングルームへ集合よ！　特にマトイ！　同じ雷属性の使い手として、みっちり揉んでもらいなさい！」"

[[dialogue]]
speaker = "マトイ"
# 「う、うん！　英雄さまの胸をお借りするつもりで頑張るね！」
line = "「う、うん！　英雄さまの胸をお借りするつもりで頑張るね！」"

[[dialogue]]
speaker = "マトイ"
# 「むぎゅぅ～……（バタリ）」
line = "「むぎゅぅ～……（バタリ）」"

[[dialogue]]
speaker = "聖沙"
# 「あ、大丈夫……！？　マトイさん……！？」
line = "「あ、大丈夫……！？　マトイさん……！？」"

[[dialogue]]
speaker = "unk"
# 瞬殺……！
line = "瞬殺……！"

[[dialogue]]
speaker = "マトイ"
# 「あはは……。やっぱり英雄さまはお強いんですね……。普通な私が太刀打ちできるわけありませんでした……」
line = "「あはは……。やっぱり英雄さまはお強いんですね……。普通な私が太刀打ちできるわけありませんでした……」"

[[dialogue]]
speaker = "聖沙"
# 「そんなことないわよ。私だってなんの変哲もない普通の女の子よ。あなたと一緒だわ」
line = "「そんなことないわよ。私だってなんの変哲もない普通の女の子よ。あなたと一緒だわ」"

[[dialogue]]
speaker = "聖沙"
# 「ヴィーナスさんに聞いたわよ。マトイさんは普通な自分をコンプレックスに思っているって。だからこそ誰よりも努力して、才能ある人についていこうとしてるって」
line = "「ヴィーナスさんに聞いたわよ。マトイさんは普通な自分をコンプレックスに思っているって。だからこそ誰よりも努力して、才能ある人についていこうとしてるって」"

[[dialogue]]
speaker = "聖沙"
# 「私は、好きよ。あなたみたいな人。私も何度勝負してもちっとも勝てない人がいるからよくわかるわ」
line = "「私は、好きよ。あなたみたいな人。私も何度勝負してもちっとも勝てない人がいるからよくわかるわ」"

[[dialogue]]
speaker = "マトイ"
# 「え、英雄さまにそう言ってもらえると励みになります」
line = "「え、英雄さまにそう言ってもらえると励みになります」"

[[dialogue]]
speaker = "聖沙"
# 「その英雄さまっていうのやめなさい。私とあなたは一緒って言ったでしょ？　マトイさん、いえ、マトイ。あなたに足りないのは負けん気だわ」
line = "「その英雄さまっていうのやめなさい。私とあなたは一緒って言ったでしょ？　マトイさん、いえ、マトイ。あなたに足りないのは負けん気だわ」"

[[dialogue]]
speaker = "聖沙"
# 「私に負けて悔しくないの？　いいえ、悔しいはずよ！　なら立ち上がって何度でも挑んできなさい！　それともたった一度の敗北であなたは諦めるのかしら？」
line = "「私に負けて悔しくないの？　いいえ、悔しいはずよ！　なら立ち上がって何度でも挑んできなさい！　それともたった一度の敗北であなたは諦めるのかしら？」"

[[dialogue]]
speaker = "マトイ"
# 「！！　あ、諦めません！　もう一度お願いします！！」
line = "「！！　あ、諦めません！　もう一度お願いします！！」"

[[dialogue]]
speaker = "聖沙"
# 「ふふ、その意気よ！　それじゃあ改めて──勝負よ！」
line = "「ふふ、その意気よ！　それじゃあ改めて──勝負よ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「どうやら上手くいったみたいね。聖沙とマトイは気が合うと思ってたの。私の目に狂いはなかったわ♪」
line = "「どうやら上手くいったみたいね。聖沙とマトイは気が合うと思ってたの。私の目に狂いはなかったわ♪」"

[[dialogue]]
speaker = "アナ"
# 「確かに聖沙さんも努力の人に見えます。凛々しく誇り高いオーラを身に纏いながらも、心のうちに稲妻のような闘争心を秘めておられて……」
line = "「確かに聖沙さんも努力の人に見えます。凛々しく誇り高いオーラを身に纏いながらも、心のうちに稲妻のような闘争心を秘めておられて……」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふ、マトイちゃんは常に一歩引いちゃうクセがあるものね～。聖沙ちゃんとの訓練で変われるといいけれど～」
line = "「ふふ、マトイちゃんは常に一歩引いちゃうクセがあるものね～。聖沙ちゃんとの訓練で変われるといいけれど～」"

[[dialogue]]
speaker = "聖沙"
# 「ダメよ、マトイ！　誰が相手でも媚びたり退いたりしちゃダメ！　たとえ敗北を喫しても、心から敗北を認めることだけはしちゃいけないわ！」
line = "「ダメよ、マトイ！　誰が相手でも媚びたり退いたりしちゃダメ！　たとえ敗北を喫しても、心から敗北を認めることだけはしちゃいけないわ！」"

[[dialogue]]
speaker = "マトイ"
# 「は、はい聖沙さん！　いえ、お姉様と呼ばせてください……！」
line = "「は、はい聖沙さん！　いえ、お姉様と呼ばせてください……！」"

[[dialogue]]
speaker = "聖沙"
# 「お姉様、か。紫央のことを思い出すわね……。いいわ、そこまで私を頼りにしてくれるのなら、トコトン付き合ってあげる！」
line = "「お姉様、か。紫央のことを思い出すわね……。いいわ、そこまで私を頼りにしてくれるのなら、トコトン付き合ってあげる！」"

[[dialogue]]
speaker = "unk"
# そして２人の訓練は夜遅くまで続き──
line = "そして２人の訓練は夜遅くまで続き──"

[[dialogue]]
speaker = "聖沙"
# 「よしよし。お疲れ様、マトイ。喉渇いたでしょ？　ドリンクをあげるわ」
line = "「よしよし。お疲れ様、マトイ。喉渇いたでしょ？　ドリンクをあげるわ」"

[[dialogue]]
speaker = "マトイ"
# 「ありがとうございま──じゃなくて！　ほ、施しは受けません！　ドリンクくらい自分で持ってきていますから！」
line = "「ありがとうございま──じゃなくて！　ほ、施しは受けません！　ドリンクくらい自分で持ってきていますから！」"

[[dialogue]]
speaker = "聖沙"
# 「ふふ！　いいじゃない！　そうよ、素直に受け取っちゃダメ！　相手に弱みを見せた時点で勝負は負けなんだから！」
line = "「ふふ！　いいじゃない！　そうよ、素直に受け取っちゃダメ！　相手に弱みを見せた時点で勝負は負けなんだから！」"

[[dialogue]]
speaker = "マトイ"
# 「はい、お姉様！」
line = "「はい、お姉様！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……ええと。これはどういうことかしら。聖沙の影響を受けてるのは間違いなさそうだけど……」
line = "「……ええと。これはどういうことかしら。聖沙の影響を受けてるのは間違いなさそうだけど……」"

[[dialogue]]
speaker = "マトイ"
# 「ふんだ、ヴィーナスってばちょっと強いからってあんまり調子に乗らないでよね！　今に見てなさい、すぐに追い越してあげるんだから！」
line = "「ふんだ、ヴィーナスってばちょっと強いからってあんまり調子に乗らないでよね！　今に見てなさい、すぐに追い越してあげるんだから！」"

[[dialogue]]
speaker = "unk"
# 見事なまでのツンデレ台詞だ
line = "見事なまでのツンデレ台詞だ"

[[dialogue]]
speaker = "ヴィーナス"
# 「いやデレられてはいないわよ、デレられては……。一体どの方向で影響を受けてるのよ……」
line = "「いやデレられてはいないわよ、デレられては……。一体どの方向で影響を受けてるのよ……」"

[[dialogue]]
speaker = "聖沙"
# 「そうよ、マトイ！　相手が実力者だからって臆しちゃいけないわ！　常に自分に自信を持つの！　あなたなら必ずヴィーナスさんを追い越せるわ！」
line = "「そうよ、マトイ！　相手が実力者だからって臆しちゃいけないわ！　常に自分に自信を持つの！　あなたなら必ずヴィーナスさんを追い越せるわ！」"

[[dialogue]]
speaker = "マトイ"
# 「ああ、お姉様……！　私、もっと頑張ります！　ヴィーナスなんてすぐにケチョンケチョンにしてみせますね！」
line = "「ああ、お姉様……！　私、もっと頑張ります！　ヴィーナスなんてすぐにケチョンケチョンにしてみせますね！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ま──ふふ、そこまで言うならやってみなさいよ♪　返り討ちにしてあげるわ♪」
line = "「ま──ふふ、そこまで言うならやってみなさいよ♪　返り討ちにしてあげるわ♪」"

[[dialogue]]
speaker = "聖沙"
# 「むむ！　挑発されたわよ、マトイ！　生まれ変わったあなたの姿を見せてあげなさい！」
line = "「むむ！　挑発されたわよ、マトイ！　生まれ変わったあなたの姿を見せてあげなさい！」"

[[dialogue]]
speaker = "マトイ"
# 「いざ尋常に勝負だよ、ヴィーナス！　お姉様との訓練の成果、見せてあげるから！」
line = "「いざ尋常に勝負だよ、ヴィーナス！　お姉様との訓練の成果、見せてあげるから！」"
