[[dialogue]]
speaker = "unk"
# 第１話,セシアの明るい家族計画,P
line = "第１話,セシアの明るい家族計画,P"

[[dialogue]]
speaker = "unk"
# 以前、セシアと初めてのデートに出かけた日から、しばらくして――
line = "以前、セシアと初めてのデートに出かけた日から、しばらくして――"

[[dialogue]]
speaker = "セシア"
# 「会長、お待ちどおさま」
line = "「会長、お待ちどおさま」"

[[dialogue]]
speaker = "unk"
# とある週末、俺はセシアに招かれて、新星寮へとやって来ていた。
line = "とある週末、俺はセシアに招かれて、新星寮へとやって来ていた。"

[[dialogue]]
speaker = "unk"
# 何やら、今日はセシアが手作り料理を披露してくれるとのことで――
line = "何やら、今日はセシアが手作り料理を披露してくれるとのことで――"

[[dialogue]]
speaker = "セシア"
# 「じゃ～ん♪　旗付きチキンライスよ♪」
line = "「じゃ～ん♪　旗付きチキンライスよ♪」"

[[dialogue]]
speaker = "unk"
# おおっ、すごい！　これをセシアが！？
line = "おおっ、すごい！　これをセシアが！？"

[[dialogue]]
speaker = "セシア"
# 「ええ。紅明ママに料理を教わって、作ったの♪」
line = "「ええ。紅明ママに料理を教わって、作ったの♪」"

[[dialogue]]
speaker = "紅明"
# 「おうよ☆　ふっふっふ、アタシはこう見えてちゃんと、料理ができるんだぜ、ダーリン♪　『昔取った<ruby=きねづか>杵柄</ruby>』ってやつで♪」
line = "「おうよ☆　ふっふっふ、アタシはこう見えてちゃんと、料理ができるんだぜ、ダーリン♪　『昔取った<ruby>杵柄<rt>きねづか</rt></ruby>』ってやつで♪」"

[[dialogue]]
speaker = "紅明"
# 「セッシーもさすが『蓄積』を司る『守護天使』なだけあるよ。アタシが教えたこと、１回ですんなり覚えちゃうんだから♪　いいこいいこ♪」
line = "「セッシーもさすが『蓄積』を司る『守護天使』なだけあるよ。アタシが教えたこと、１回ですんなり覚えちゃうんだから♪　いいこいいこ♪」"

[[dialogue]]
speaker = "セシア"
# 「えへへ～♪　紅明ママに褒められちゃった<emoji=heart04>」
line = "「えへへ～♪　紅明ママに褒められちゃった<emoji=heart04>」"

[[dialogue]]
speaker = "セシア"
# 「そういうわけで、会長。冷めない内に、どうぞ召し上がれ♪」
line = "「そういうわけで、会長。冷めない内に、どうぞ召し上がれ♪」"

[[dialogue]]
speaker = "unk"
# 俺は「いただきます」と手を合わせて、チキンライスを食べる。
line = "俺は「いただきます」と手を合わせて、チキンライスを食べる。"

[[dialogue]]
speaker = "セシア"
# 「――お味は……どうかしら？」
line = "「――お味は……どうかしら？」"

[[dialogue]]
speaker = "unk"
# うまい！
line = "うまい！"

[[dialogue]]
speaker = "セシア"
# 「……！　えへへ♪　よかった♪　わたくし、とっても嬉しいわ♪」
line = "「……！　えへへ♪　よかった♪　わたくし、とっても嬉しいわ♪」"

[[dialogue]]
speaker = "紅明"
# 「やったな、セッシー！　ダーリンの胃袋をハートキャッチだぜ☆　イェーイ！」
line = "「やったな、セッシー！　ダーリンの胃袋をハートキャッチだぜ☆　イェーイ！」"

[[dialogue]]
speaker = "セシア"
# 「いぇーいっ♪」
line = "「いぇーいっ♪」"

[[dialogue]]
speaker = "unk"
# セシアは可愛くぴょんと跳ねて、紅明をハイタッチをする。
line = "セシアは可愛くぴょんと跳ねて、紅明をハイタッチをする。"

[[dialogue]]
speaker = "セシア"
# 「それで、会長――わたくしと恋人として、お付き合いしてくれる気になったかしら？」
line = "「それで、会長――わたくしと恋人として、お付き合いしてくれる気になったかしら？」"

[[dialogue]]
speaker = "unk"
# ！？　ゴホッ……ゴホッ……！
line = "！？　ゴホッ……ゴホッ……！"

[[dialogue]]
speaker = "unk"
# チキンライスを食べている途中で、思わずむせてしまう。
line = "チキンライスを食べている途中で、思わずむせてしまう。"

[[dialogue]]
speaker = "セシア"
# 「？　どうしてそんなに、驚いた顔をするの？」
line = "「？　どうしてそんなに、驚いた顔をするの？」"

[[dialogue]]
speaker = "セシア"
# 「この前、わたくしと初めてデートをした時にも、伝えたじゃない？」
line = "「この前、わたくしと初めてデートをした時にも、伝えたじゃない？」"

[[dialogue]]
speaker = "セシア"
# 「会長と、これから恋人として恋愛を体験していきたい、って」
line = "「会長と、これから恋人として恋愛を体験していきたい、って」"

[[dialogue]]
speaker = "unk"
# た、確かに言われたけども……
line = "た、確かに言われたけども……"

[[dialogue]]
speaker = "セシア"
# 「どうやら、その様子を見るに、心の準備はまだできていないみたいね」
line = "「どうやら、その様子を見るに、心の準備はまだできていないみたいね」"

[[dialogue]]
speaker = "セシア"
# 「わたくし、この前のデートで気づいたの」
line = "「わたくし、この前のデートで気づいたの」"

[[dialogue]]
speaker = "セシア"
# 「わたくしは会長と恋人になる準備ができているのに、あなたがまだそのつもりじゃないのは、なんだか『とても寂しい』って」
line = "「わたくしは会長と恋人になる準備ができているのに、あなたがまだそのつもりじゃないのは、なんだか『とても寂しい』って」"

[[dialogue]]
speaker = "セシア"
# 「だから、早く心の準備をしてもらえるように、会長からのプラスポイントを『蓄積』することにしたのよ」
line = "「だから、早く心の準備をしてもらえるように、会長からのプラスポイントを『蓄積』することにしたのよ」"

[[dialogue]]
speaker = "紅明"
# 「要するに、セッシーが実はダーリンに対して片想いだったことが判明したんで――」
line = "「要するに、セッシーが実はダーリンに対して片想いだったことが判明したんで――」"

[[dialogue]]
speaker = "紅明"
# 「自分のことを好きになってもらおうと、『好感度』を上げる為に猛烈アプローチ中、ってわけだな☆」
line = "「自分のことを好きになってもらおうと、『好感度』を上げる為に猛烈アプローチ中、ってわけだな☆」"

[[dialogue]]
speaker = "セシア"
# 「ただ……」
line = "「ただ……」"

[[dialogue]]
speaker = "セシア"
# 「わたくしがもし、勝手に勘違いしているだけだったらと、不安なことが１つあって……」
line = "「わたくしがもし、勝手に勘違いしているだけだったらと、不安なことが１つあって……」"

[[dialogue]]
speaker = "unk"
# 不安なこととは何だろうかと俺が首を傾げていると、セシアは両手の指を突き合わせて、もじもじさせながら――
line = "不安なこととは何だろうかと俺が首を傾げていると、セシアは両手の指を突き合わせて、もじもじさせながら――"

[[dialogue]]
speaker = "セシア"
# 「会長がわたくしのこと、そもそも女の子として全く好きじゃなかったりしたら、どうしようって……」
line = "「会長がわたくしのこと、そもそも女の子として全く好きじゃなかったりしたら、どうしようって……」"

[[dialogue]]
speaker = "unk"
# それは絶対にない！
line = "それは絶対にない！"

[[dialogue]]
speaker = "unk"
# 俺がセシアを嫌いなわけがない。それだけは、迷わず即答することができた。
line = "俺がセシアを嫌いなわけがない。それだけは、迷わず即答することができた。"

[[dialogue]]
speaker = "セシア"
# 「よかった……♪　ならわたくし、会長の迷惑にはなっていないのね」
line = "「よかった……♪　ならわたくし、会長の迷惑にはなっていないのね」"

[[dialogue]]
speaker = "unk"
# もちろんだ、と頷く。
line = "もちろんだ、と頷く。"

[[dialogue]]
speaker = "紅明"
# 「ふふっ、ダーリンならそう言うと思ってたぜ♪　これでみんな仲良し『ハッピーハーレム』に１歩前進だな、セッシー！」
line = "「ふふっ、ダーリンならそう言うと思ってたぜ♪　これでみんな仲良し『ハッピーハーレム』に１歩前進だな、セッシー！」"

[[dialogue]]
speaker = "セシア"
# 「うん♪　紅明ママ♪」
line = "「うん♪　紅明ママ♪」"

[[dialogue]]
speaker = "unk"
# とんでもない言葉が聞こえたんだけど！？
line = "とんでもない言葉が聞こえたんだけど！？"

[[dialogue]]
speaker = "unk"
# ちょっと待って！　なんか今、
line = "ちょっと待って！　なんか今、"

[[dialogue]]
speaker = "紅明"
# 「え？　『ハッピーハーレム』のこと？」
line = "「え？　『ハッピーハーレム』のこと？」"

[[dialogue]]
speaker = "紅明"
# 「ふっふっふ、説明しよう。ぶっちゃけ、ダーリンはこれまで出会った女の子たちから全員、好意を向けられてもおかしくないくらいモテるじゃろ？」
line = "「ふっふっふ、説明しよう。ぶっちゃけ、ダーリンはこれまで出会った女の子たちから全員、好意を向けられてもおかしくないくらいモテるじゃろ？」"

[[dialogue]]
speaker = "unk"
# そ、それはどうかわからないけど……
line = "そ、それはどうかわからないけど……"

[[dialogue]]
speaker = "紅明"
# 「んモー、またまた～♪　まぁ、そういう謙虚なところがまた好きなんだけどね<emoji=heart04>」
line = "「んモー、またまた～♪　まぁ、そういう謙虚なところがまた好きなんだけどね<emoji=heart04>」"

[[dialogue]]
speaker = "セシア"
# 「会長は素敵な男性だと思うわ。初めての恋人を作るなら会長がいいって、わたくしも思ったもの」
line = "「会長は素敵な男性だと思うわ。初めての恋人を作るなら会長がいいって、わたくしも思ったもの」"

[[dialogue]]
speaker = "紅明"
# 「うんうん♪　それで少なくとも、このままだとアタシとセッシーがダーリンを取り合って、ドロドロの昼ドラ展開を繰り広げることになってしまう」
line = "「うんうん♪　それで少なくとも、このままだとアタシとセッシーがダーリンを取り合って、ドロドロの昼ドラ展開を繰り広げることになってしまう」"

[[dialogue]]
speaker = "紅明"
# 「仲良い子とそんな風になるのは、やっぱ嫌じゃん？　それでアタシは考えた。みんな笑顔でハッピーな将来を目指すなら――」
line = "「仲良い子とそんな風になるのは、やっぱ嫌じゃん？　それでアタシは考えた。みんな笑顔でハッピーな将来を目指すなら――」"

[[dialogue]]
speaker = "紅明"
# 「ズバリ、ハーレムしかないっしょ☆　ってね！　な？　セッシー♪」
line = "「ズバリ、ハーレムしかないっしょ☆　ってね！　な？　セッシー♪」"

[[dialogue]]
speaker = "セシア"
# 「うん♪」
line = "「うん♪」"

[[dialogue]]
speaker = "セシア"
# 「わたくしも、紅明ママの考えを聞いて大賛成だったわ。だって――」
line = "「わたくしも、紅明ママの考えを聞いて大賛成だったわ。だって――」"

[[dialogue]]
speaker = "セシア"
# 「ハーレムなら、会長との家庭を築きつつ、沢山のママと一緒に暮らせるわけでしょう？　それって、これ以上ないくらい、とっても素敵なことだもの♪」
line = "「ハーレムなら、会長との家庭を築きつつ、沢山のママと一緒に暮らせるわけでしょう？　それって、これ以上ないくらい、とっても素敵なことだもの♪」"

[[dialogue]]
speaker = "紅明"
# 「というわけで、ダーリンとセッシーの仲はアタシも全力で応援して行くから、よろしくな！　ダーリン☆」
line = "「というわけで、ダーリンとセッシーの仲はアタシも全力で応援して行くから、よろしくな！　ダーリン☆」"

[[dialogue]]
speaker = "紅明"
# 「あっ、もちろんアタシとの仲もね♪　んふっ<emoji=heart04>」
line = "「あっ、もちろんアタシとの仲もね♪　んふっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そう言って、俺の腕に抱き着き豊かな胸を押し付けて来る紅明。
line = "そう言って、俺の腕に抱き着き豊かな胸を押し付けて来る紅明。"

[[dialogue]]
speaker = "セシア"
# 「素敵な<ruby=ハーレム>未来</ruby>を目指して、一緒に過程を蓄積して行きましょう♪」
line = "「素敵な<ruby>未来<rt>ハーレム</rt></ruby>を目指して、一緒に過程を蓄積して行きましょう♪」"

[[dialogue]]
speaker = "unk"
# 反対側の腕にもセシアが抱き着いて、ぴとっと顔をくっ付けて来る。
line = "反対側の腕にもセシアが抱き着いて、ぴとっと顔をくっ付けて来る。"

[[dialogue]]
speaker = "unk"
# それに関して俺の意思は！？
line = "それに関して俺の意思は！？"

[[dialogue]]
speaker = "紅明"
# 「大丈夫！　ダーリンがそれで幸せになれるって確信を持って貰えるよう、アタシたち頑張ってアプローチして行くから！」
line = "「大丈夫！　ダーリンがそれで幸せになれるって確信を持って貰えるよう、アタシたち頑張ってアプローチして行くから！」"

[[dialogue]]
speaker = "セシア"
# 「だから、わたくしたちのこと、ちゃんと見ていてね。会長♪」
line = "「だから、わたくしたちのこと、ちゃんと見ていてね。会長♪」"

[[dialogue]]
speaker = "紅明"
# 「うしし<emoji=heart04>」
line = "「うしし<emoji=heart04>」"

[[dialogue]]
speaker = "セシア"
# 「ふふっ♪」
line = "「ふふっ♪」"

[[dialogue]]
speaker = "unk"
# ２人にそんな風に挟まれて、内心ドキドキしてしまう俺なのだった――
line = "２人にそんな風に挟まれて、内心ドキドキしてしまう俺なのだった――"
