[[dialogue]]
speaker = "unk"
# 第２話,死神いじめ？,P
line = "第２話,死神いじめ？,P"

[[dialogue]]
speaker = "unk"
# 今日は新しい漫画の発売日なので、放課後に秋葉原に寄っていた。
line = "今日は新しい漫画の発売日なので、放課後に秋葉原に寄っていた。"

[[dialogue]]
speaker = "？？？"
# 「ふぅ～」
line = "「ふぅ～」"

[[dialogue]]
speaker = "unk"
# うわっ！？
line = "うわっ！？"

[[dialogue]]
speaker = "パテル"
# 「ヤッホー♪　あなたの死神、パテルちゃんだよ♪」
line = "「ヤッホー♪　あなたの死神、パテルちゃんだよ♪」"

[[dialogue]]
speaker = "unk"
# どうしてパテルがここに？
line = "どうしてパテルがここに？"

[[dialogue]]
speaker = "パテル"
# 「ちょっとこの辺で人に会っててね。魔王も知ってる人だよ」
line = "「ちょっとこの辺で人に会っててね。魔王も知ってる人だよ」"

[[dialogue]]
speaker = "レイラ"
# 「うぅ、やっぱり秋葉原でもパーツが暴騰してる……」
line = "「うぅ、やっぱり秋葉原でもパーツが暴騰してる……」"

[[dialogue]]
speaker = "レイラ"
# 「メモリもＣＰＵもグラボも値上げの魔の手に……まだ電源しか新しいの買えてないのに、血も涙もない……」
line = "「メモリもＣＰＵもグラボも値上げの魔の手に……まだ電源しか新しいの買えてないのに、血も涙もない……」"

[[dialogue]]
speaker = "レイラ"
# 「救いは……<ruby=ジサカー>自作ｅｒ</ruby>に救いはないんですか！？　このままだと一生パソコンが組めなくて、<ruby=ジサカー>自作ｅｒ</ruby>は死に絶えてしまいますっ……！」
line = "「救いは……<ruby>自作ｅｒ<rt>ジサカー</rt></ruby>に救いはないんですか！？　このままだと一生パソコンが組めなくて、<ruby>自作ｅｒ<rt>ジサカー</rt></ruby>は死に絶えてしまいますっ……！」"

[[dialogue]]
speaker = "パテル"
# 「やぁ、あなたがコラプサーのレイラだよね？」
line = "「やぁ、あなたがコラプサーのレイラだよね？」"

[[dialogue]]
speaker = "レイラ"
# 「ひゃあっ！？　し、死神！？　とうとう自作ｅｒに終焉の時が！？」
line = "「ひゃあっ！？　し、死神！？　とうとう自作ｅｒに終焉の時が！？」"

[[dialogue]]
speaker = "パテル"
# 「あたしは『淘汰』の摂理を司る守護天使、《試練》のパテル。ジサなんとかは知らないけど、死神なのはほんとだよ」
line = "「あたしは『淘汰』の摂理を司る守護天使、《試練》のパテル。ジサなんとかは知らないけど、死神なのはほんとだよ」"

[[dialogue]]
speaker = "レイラ"
# 「は、はぁ……？　その死神さんが私に何のご用でしょうか？」
line = "「は、はぁ……？　その死神さんが私に何のご用でしょうか？」"

[[dialogue]]
speaker = "パテル"
# 「あなたたちコラプサーは一度死に、ブラックホールの星力によって蘇った。だけどそれは不完全な蘇生だった」
line = "「あなたたちコラプサーは一度死に、ブラックホールの星力によって蘇った。だけどそれは不完全な蘇生だった」"

[[dialogue]]
speaker = "パテル"
# 「再び死の窮地に立たされたあなたたちは、朝比奈コハルコの魔法によって、今度こそ生を取り戻した。……そうだよね？」
line = "「再び死の窮地に立たされたあなたたちは、朝比奈コハルコの魔法によって、今度こそ生を取り戻した。……そうだよね？」"

[[dialogue]]
speaker = "レイラ"
# 「……はい、そうです。間違いありません」
line = "「……はい、そうです。間違いありません」"

[[dialogue]]
speaker = "パテル"
# 「一度死んだはずのコラプサーは、本来あたしが連れていかなくちゃいけない存在だったんだけど──」
line = "「一度死んだはずのコラプサーは、本来あたしが連れていかなくちゃいけない存在だったんだけど──」"

[[dialogue]]
speaker = "レイラ"
# 「私、死神に連れていかれちゃうんですか！？」
line = "「私、死神に連れていかれちゃうんですか！？」"

[[dialogue]]
speaker = "レイラ"
# 「せ、せめてその前に、持ってるパーツでパソコンを組ませてくださいっ。買ったまま使ってないパーツがたくさんあるんです！」
line = "「せ、せめてその前に、持ってるパーツでパソコンを組ませてくださいっ。買ったまま使ってないパーツがたくさんあるんです！」"

[[dialogue]]
speaker = "レイラ"
# 「あと期間限定タツタバーガーも食べたいし、てり玉も食べなきゃだし、冬のグラタンバーガーも食べる予定だし──ああっ、月見もあるんだった！」
line = "「あと期間限定タツタバーガーも食べたいし、てり玉も食べなきゃだし、冬のグラタンバーガーも食べる予定だし──ああっ、月見もあるんだった！」"

[[dialogue]]
speaker = "パテル"
# 「せめてになってない気がするんだけど……。全然死ぬ気ないじゃん」
line = "「せめてになってない気がするんだけど……。全然死ぬ気ないじゃん」"

[[dialogue]]
speaker = "パテル"
# 「大丈夫。あなたも、あなたの仲間も、連れていくつもりはないよ」
line = "「大丈夫。あなたも、あなたの仲間も、連れていくつもりはないよ」"

[[dialogue]]
speaker = "パテル"
# 「あなたたちは生者に戻り、試練を乗り越えた。かなり反則スレスレだったけど」
line = "「あなたたちは生者に戻り、試練を乗り越えた。かなり反則スレスレだったけど」"

[[dialogue]]
speaker = "パテル"
# 「今は不完全な蘇生を受けた時の影響がないか観察してるから、一応伝えておこうと思っただけ」
line = "「今は不完全な蘇生を受けた時の影響がないか観察してるから、一応伝えておこうと思っただけ」"

[[dialogue]]
speaker = "レイラ"
# 「ほっ……」
line = "「ほっ……」"

[[dialogue]]
speaker = "パテル"
# 「コハルコに蘇生される前だったら、連れていってたけどね」
line = "「コハルコに蘇生される前だったら、連れていってたけどね」"

[[dialogue]]
speaker = "レイラ"
# 「ひぃぃぃっ！？」
line = "「ひぃぃぃっ！？」"

[[dialogue]]
speaker = "パテル"
# 「コラプサーの黒幕であるイザベラも、本当はあたしが連れていかなきゃいけない存在だった。秋葉原に張ったあの結界は、あたしを寄せ付けないためでもあったんだろうね」
line = "「コラプサーの黒幕であるイザベラも、本当はあたしが連れていかなきゃいけない存在だった。秋葉原に張ったあの結界は、あたしを寄せ付けないためでもあったんだろうね」"

[[dialogue]]
speaker = "パテル"
# 「あと、<ruby=レナトゥス>封理再誕</ruby>の魔法で生まれ変わったあなたも観察対象だから、一応忘れないでね」
line = "「あと、<ruby>封理再誕<rt>レナトゥス</rt></ruby>の魔法で生まれ変わったあなたも観察対象だから、一応忘れないでね」"

[[dialogue]]
speaker = "パテル"
# 「で、魔王は何してたの──って、漫画買ってたんだ」
line = "「で、魔王は何してたの──って、漫画買ってたんだ」"

[[dialogue]]
speaker = "パテル"
# 「ちょっと気になるなぁ～。じゃ、魔王のおうちにお邪魔させてもらうね♪」
line = "「ちょっと気になるなぁ～。じゃ、魔王のおうちにお邪魔させてもらうね♪」"

[[dialogue]]
speaker = "パテル"
# 「どんな漫画買ったの？　見せて見せて～」
line = "「どんな漫画買ったの？　見せて見せて～」"

[[dialogue]]
speaker = "パテル"
# 「けっこうグロくて刺激が強い？　へーきへーき、あたし死神だよ？」
line = "「けっこうグロくて刺激が強い？　へーきへーき、あたし死神だよ？」"

[[dialogue]]
speaker = "パテル"
# 「どれどれ……ふーん、へー、ほーん」
line = "「どれどれ……ふーん、へー、ほーん」"

[[dialogue]]
speaker = "unk"
# めちゃくちゃ冷めてる！？
line = "めちゃくちゃ冷めてる！？"

[[dialogue]]
speaker = "パテル"
# 「動物なんて、文字通り一皮剥けば血と肉と骨の塊だ。言われなくても知ってるし、そんなの見せつけられたって、何の感情も浮かばないよ」
line = "「動物なんて、文字通り一皮剥けば血と肉と骨の塊だ。言われなくても知ってるし、そんなの見せつけられたって、何の感情も浮かばないよ」"

[[dialogue]]
speaker = "unk"
# じゃあこっちはどう？
line = "じゃあこっちはどう？"

[[dialogue]]
speaker = "パテル"
# 「派遣社員の女性が、仕事の疲れをご飯で癒すグルメ漫画？　全然刺激的じゃなさそうだけど……」
line = "「派遣社員の女性が、仕事の疲れをご飯で癒すグルメ漫画？　全然刺激的じゃなさそうだけど……」"

[[dialogue]]
speaker = "パテル"
# 「ん？　あれ？　いきなりおっきなお弁当食べだしたけど……２０００キロカロリー……？」
line = "「ん？　あれ？　いきなりおっきなお弁当食べだしたけど……２０００キロカロリー……？」"

[[dialogue]]
speaker = "パテル"
# 「一日の摂取量じゃなくて？　一食で？　女性の一日の摂取カロリーの目安は１８００キロカロリーだよ？」
line = "「一日の摂取量じゃなくて？　一食で？　女性の一日の摂取カロリーの目安は１８００キロカロリーだよ？」"

[[dialogue]]
speaker = "パテル"
# 「そんなの一気に食べたら……うわぁあっ！？　意識が飛んでるっ！？　こんなの死んじゃうよぉっ！？」
line = "「そんなの一気に食べたら……うわぁあっ！？　意識が飛んでるっ！？　こんなの死んじゃうよぉっ！？」"

[[dialogue]]
speaker = "パテル"
# 「はぁ、はぁ……あたし、どうしてこんなの読んでるんだ……？」
line = "「はぁ、はぁ……あたし、どうしてこんなの読んでるんだ……？」"

[[dialogue]]
speaker = "パテル"
# 「え、仕事から帰ってきてまだ食べるの？　お米そんなにいらないって！　１合炊けば十分だってば！」
line = "「え、仕事から帰ってきてまだ食べるの？　お米そんなにいらないって！　１合炊けば十分だってば！」"

[[dialogue]]
speaker = "パテル"
# 「一日の摂取カロリーは……５０００キロカロリー！？　いや、だから成人女性のカロリーは１８００だって！　倍以上いってるってば！」
line = "「一日の摂取カロリーは……５０００キロカロリー！？　いや、だから成人女性のカロリーは１８００だって！　倍以上いってるってば！」"

[[dialogue]]
speaker = "パテル"
# 「ていうかこれ、塩分もものすごいことになってるんじゃ……わぁっ！？　さらに塩振り出した！？　もう塩そのまま食べてるようなものだよ！？」
line = "「ていうかこれ、塩分もものすごいことになってるんじゃ……わぁっ！？　さらに塩振り出した！？　もう塩そのまま食べてるようなものだよ！？」"

[[dialogue]]
speaker = "パテル"
# 「一日の塩分の摂取目安量は７グラムくらい……でもこれ倍とかそういうレベルじゃないよ……」
line = "「一日の塩分の摂取目安量は７グラムくらい……でもこれ倍とかそういうレベルじゃないよ……」"

[[dialogue]]
speaker = "パテル"
# 「ひやぁああっ！？　ベーコンの塊にマヨネーズぶっかけちゃダメダメダメぇっ！？　血糖値も血圧もぶっ壊れちゃうっ！？」
line = "「ひやぁああっ！？　ベーコンの塊にマヨネーズぶっかけちゃダメダメダメぇっ！？　血糖値も血圧もぶっ壊れちゃうっ！？」"

[[dialogue]]
speaker = "パテル"
# 「なんだこれ！？　これもうグルメ漫画じゃないよ！　死神いじめだよ！？」
line = "「なんだこれ！？　これもうグルメ漫画じゃないよ！　死神いじめだよ！？」"

[[dialogue]]
speaker = "パテル"
# 「生きるために食べてるはずなのに、どうして食べながら傷ついていくの……？　こんなの……こんなの……」
line = "「生きるために食べてるはずなのに、どうして食べながら傷ついていくの……？　こんなの……こんなの……」"

[[dialogue]]
speaker = "パテル"
# 「命をなんだと思ってるんだ！！！」
line = "「命をなんだと思ってるんだ！！！」"

[[dialogue]]
speaker = "パテル"
# 「はぁ……はぁ……なんてものを作るんだ、人類は……！」
line = "「はぁ……はぁ……なんてものを作るんだ、人類は……！」"

[[dialogue]]
speaker = "パテル"
# 「ねぇ、魔王……」
line = "「ねぇ、魔王……」"

[[dialogue]]
speaker = "パテル"
# 「魔王はこんな生活しないで、少しは健康に気を遣ってね。あたし心配だよ……」
line = "「魔王はこんな生活しないで、少しは健康に気を遣ってね。あたし心配だよ……」"

[[dialogue]]
speaker = "unk"
# もちろんこの漫画みたいな生活をするつもりはないけど、パテルを泣かせないように、健康的な生活を送ろうと思ったのだった。
line = "もちろんこの漫画みたいな生活をするつもりはないけど、パテルを泣かせないように、健康的な生活を送ろうと思ったのだった。"
