[[dialogue]]
speaker = "unk"
# 第２話,各国のバレンタイン事情,P
line = "第２話,各国のバレンタイン事情,P"

[[dialogue]]
speaker = "unk"
# バレンタインの時期になると、カフェテリアもバレンタイン仕様になっていて、限定メニューなんかも出ている。
line = "バレンタインの時期になると、カフェテリアもバレンタイン仕様になっていて、限定メニューなんかも出ている。"

[[dialogue]]
speaker = "イレーナ"
# 「本当にバレンタイン一色ですね……」
line = "「本当にバレンタイン一色ですね……」"

[[dialogue]]
speaker = "エリス"
# 「そうですね、恋人が想い合う日は、どの国でも大切なものなのでしょう」
line = "「そうですね、恋人が想い合う日は、どの国でも大切なものなのでしょう」"

[[dialogue]]
speaker = "unk"
# 珍しい組み合わせだ
line = "珍しい組み合わせだ"

[[dialogue]]
speaker = "イレーナ"
# 「あ、会長さん、こんにちは」
line = "「あ、会長さん、こんにちは」"

[[dialogue]]
speaker = "イレーナ"
# 「私たち、海外の出身で、流星学園では同学年なので、しばしば情報交換をしているんです」
line = "「私たち、海外の出身で、流星学園では同学年なので、しばしば情報交換をしているんです」"

[[dialogue]]
speaker = "イレーナ"
# 「エリスさんは私よりも流星市国での暮らしが長いので、いろいろと教えていただきました」
line = "「エリスさんは私よりも流星市国での暮らしが長いので、いろいろと教えていただきました」"

[[dialogue]]
speaker = "エリス"
# 「私など微力だと思いますが、お役に立てたのなら何よりです」
line = "「私など微力だと思いますが、お役に立てたのなら何よりです」"

[[dialogue]]
speaker = "イレーナ"
# 「実はさっき、エリスさんとバレンタインの風習について話していまして」
line = "「実はさっき、エリスさんとバレンタインの風習について話していまして」"

[[dialogue]]
speaker = "エリス"
# 「私はフランス、イレーナさんがイタリアの出身なので、国ごとにどんな違いがあるのかと気になったんです」
line = "「私はフランス、イレーナさんがイタリアの出身なので、国ごとにどんな違いがあるのかと気になったんです」"

[[dialogue]]
speaker = "unk"
# 具体的にはどう違うの？
line = "具体的にはどう違うの？"

[[dialogue]]
speaker = "イレーナ"
# 「そうですね……例えばイタリアと日本の違いですが、バレンタインに女性から男性にチョコレートを渡すのは日本独自の風習です」
line = "「そうですね……例えばイタリアと日本の違いですが、バレンタインに女性から男性にチョコレートを渡すのは日本独自の風習です」"

[[dialogue]]
speaker = "イレーナ"
# 「イタリアでは男性から女性にプレゼントを渡す方が多いです。赤いバラの花束が定番ですね」
line = "「イタリアでは男性から女性にプレゼントを渡す方が多いです。赤いバラの花束が定番ですね」"

[[dialogue]]
speaker = "イレーナ"
# 「夜はお洒落なレストランでディナーをしたりします。レストランの予約がもっとも難しい日、なんて言われることもありますね」
line = "「夜はお洒落なレストランでディナーをしたりします。レストランの予約がもっとも難しい日、なんて言われることもありますね」"

[[dialogue]]
speaker = "エリス"
# 「その点はフランスも近いですね」
line = "「その点はフランスも近いですね」"

[[dialogue]]
speaker = "エリス"
# 「『恋人の日』というのは変わりませんが、すでにカップルになっている２人が愛を確かめ合ったり、愛を深めたりする日……といった感じでしょうか」
line = "「『恋人の日』というのは変わりませんが、すでにカップルになっている２人が愛を確かめ合ったり、愛を深めたりする日……といった感じでしょうか」"

[[dialogue]]
speaker = "エリス"
# 「映画を見に行ったり、普段行かない高級なお店でディナーを楽しんだり、小旅行に出かけたりと、恋人と特別な時間を過ごすことが多いです」
line = "「映画を見に行ったり、普段行かない高級なお店でディナーを楽しんだり、小旅行に出かけたりと、恋人と特別な時間を過ごすことが多いです」"

[[dialogue]]
speaker = "エリス"
# 「プレゼントとしては、花束やメッセージカード、アクセサリーや香水などが一般的でしょうか」
line = "「プレゼントとしては、花束やメッセージカード、アクセサリーや香水などが一般的でしょうか」"

[[dialogue]]
speaker = "エリス"
# 「こちらのように『告白の日』ではないので、ホワイトデーはありませんね」
line = "「こちらのように『告白の日』ではないので、ホワイトデーはありませんね」"

[[dialogue]]
speaker = "unk"
# チョコレートは渡さないの？
line = "チョコレートは渡さないの？"

[[dialogue]]
speaker = "イレーナ"
# 「いいえ、チョコレート<b>も</b>贈ります」
line = "「いいえ、チョコレート<b>も</b>贈ります」"

[[dialogue]]
speaker = "イレーナ"
# 「チョコレートはバレンタインの贈り物の有力な選択肢の１つですが、バレンタイン＝チョコレート、というわけではありません」
line = "「チョコレートはバレンタインの贈り物の有力な選択肢の１つですが、バレンタイン＝チョコレート、というわけではありません」"

[[dialogue]]
speaker = "エリス"
# 「ヨーロッパはだいたい似たような感じだと思います。でも他の国の話も聞きたいところですね」
line = "「ヨーロッパはだいたい似たような感じだと思います。でも他の国の話も聞きたいところですね」"

[[dialogue]]
speaker = "unk"
# あ、ちょうどいいところに
line = "あ、ちょうどいいところに"

[[dialogue]]
speaker = "ジグ"
# 「おや、君たちもお茶しに来たのかい？」
line = "「おや、君たちもお茶しに来たのかい？」"

[[dialogue]]
speaker = "梨緒"
# 「私たちに何か用か？　今なら別に構わないが」
line = "「私たちに何か用か？　今なら別に構わないが」"

[[dialogue]]
speaker = "unk"
# ２人はイギリスとドイツの出身だよね？
line = "２人はイギリスとドイツの出身だよね？"

[[dialogue]]
speaker = "イレーナ"
# 「今、各国のバレンタインについてお話していたところなんです。それで、おふたりからもご自分の国のバレンタインについてお聞きしたいなと」
line = "「今、各国のバレンタインについてお話していたところなんです。それで、おふたりからもご自分の国のバレンタインについてお聞きしたいなと」"

[[dialogue]]
speaker = "梨緒"
# 「なるほど、そういうことか。もちろん構わない。私たちは平行世界ベガの出身だが、さすがにバレンタインの風習は変わらないからな」
line = "「なるほど、そういうことか。もちろん構わない。私たちは平行世界ベガの出身だが、さすがにバレンタインの風習は変わらないからな」"

[[dialogue]]
speaker = "梨緒"
# 「とはいえ、イギリスも他のヨーロッパの国とそう違わないと思うが」
line = "「とはいえ、イギリスも他のヨーロッパの国とそう違わないと思うが」"

[[dialogue]]
speaker = "梨緒"
# 「しいて言うなら、バレンタインにチョコレートを贈るようになったのは、イギリスの会社がバレンタイン向けにチョコを売り出したのがきっかけだ……と聞いたことがあるな」
line = "「しいて言うなら、バレンタインにチョコレートを贈るようになったのは、イギリスの会社がバレンタイン向けにチョコを売り出したのがきっかけだ……と聞いたことがあるな」"

[[dialogue]]
speaker = "ジグ"
# 「ドイツも男性から女性にプレゼントをするね。だけど他の国ほどは盛り上がらないかな」
line = "「ドイツも男性から女性にプレゼントをするね。だけど他の国ほどは盛り上がらないかな」"

[[dialogue]]
speaker = "ジグ"
# 「あと、ドイツのバレンタインでは、豚のお守りやスタチューを贈る人もいるんだ」
line = "「あと、ドイツのバレンタインでは、豚のお守りやスタチューを贈る人もいるんだ」"

[[dialogue]]
speaker = "梨緒"
# 「豚の？　何か意味があるのか？」
line = "「豚の？　何か意味があるのか？」"

[[dialogue]]
speaker = "イレーナ"
# （お前はメスブタだ、ってこと！？）
line = "（お前はメスブタだ、ってこと！？）"

[[dialogue]]
speaker = "ジグ"
# 「ドイツでは豚は幸運の象徴でね。縁起物なんだよ。まぁ、どちらかというと年末年始の方が豚を見ることは多いかな」
line = "「ドイツでは豚は幸運の象徴でね。縁起物なんだよ。まぁ、どちらかというと年末年始の方が豚を見ることは多いかな」"

[[dialogue]]
speaker = "イレーナ"
# （違った！？　そりゃそうだけど、とんでもない想像しちゃったわ……）
line = "（違った！？　そりゃそうだけど、とんでもない想像しちゃったわ……）"

[[dialogue]]
speaker = "エリス"
# 「イレーナさん？　少し顔が赤いようですが、大丈夫ですか？」
line = "「イレーナさん？　少し顔が赤いようですが、大丈夫ですか？」"

[[dialogue]]
speaker = "イレーナ"
# 「ああいえ、少し空調が利きすぎているのかもしれません。大丈夫ですよ」
line = "「ああいえ、少し空調が利きすぎているのかもしれません。大丈夫ですよ」"

[[dialogue]]
speaker = "イレーナ"
# 「ちなみにイタリアでは、バレンタインの翌日に、恋人がいない人たちが集まってパーティーをするんです」
line = "「ちなみにイタリアでは、バレンタインの翌日に、恋人がいない人たちが集まってパーティーをするんです」"

[[dialogue]]
speaker = "イレーナ"
# 「出会いを求めてだったり、パートナーがいないことを慰め合ったり、これはこれで楽しいものだそうですよ」
line = "「出会いを求めてだったり、パートナーがいないことを慰め合ったり、これはこれで楽しいものだそうですよ」"

[[dialogue]]
speaker = "梨緒"
# 「それは初耳だ。ヨーロッパでもバレンタインに違いがあるものなんだな」
line = "「それは初耳だ。ヨーロッパでもバレンタインに違いがあるものなんだな」"

[[dialogue]]
speaker = "エリス"
# 「ふふ、面白い風習ですね。寂しさも紛れそうです」
line = "「ふふ、面白い風習ですね。寂しさも紛れそうです」"

[[dialogue]]
speaker = "unk"
# 外国のバレンタインか……
line = "外国のバレンタインか……"

[[dialogue]]
speaker = "イレーナ"
# 「どうしました、会長さん？　何かお考えの様子ですが」
line = "「どうしました、会長さん？　何かお考えの様子ですが」"

[[dialogue]]
speaker = "unk"
# いや、何でもないよ
line = "いや、何でもないよ"

[[dialogue]]
speaker = "イレーナ"
# 「そうですか。ならよいのですが……」
line = "「そうですか。ならよいのですが……」"

[[dialogue]]
speaker = "ジグ"
# （おや、可能性が見えてしまった。行動を起こすようだね）
line = "（おや、可能性が見えてしまった。行動を起こすようだね）"

[[dialogue]]
speaker = "ジグ"
# （うまくいくといいね……魔王）
line = "（うまくいくといいね……魔王）"
