[[dialogue]]
speaker = "unk"
# 第３話,裏オークションの目玉商品,P
line = "第３話,裏オークションの目玉商品,P"

[[dialogue]]
speaker = "unk"
# 深夜の繁華街──俺はセナリィが運営する秘密結社『ゴールデングース』から依頼を受け、違法オークション会場の摘発を手伝うことになった。
line = "深夜の繁華街──俺はセナリィが運営する秘密結社『ゴールデングース』から依頼を受け、違法オークション会場の摘発を手伝うことになった。"

[[dialogue]]
speaker = "セナリィ"
# 「会長様、今夜はサポート感謝いたしますわ。腕利きの星騎士がどうしても必要でしたの」
line = "「会長様、今夜はサポート感謝いたしますわ。腕利きの星騎士がどうしても必要でしたの」"

[[dialogue]]
speaker = "セナリィ"
# 「なんでも今回のオークション、相当珍しいブツが出品されるらしく。裏世界のコレクターたちが勢ぞろいしているようですわ」
line = "「なんでも今回のオークション、相当珍しいブツが出品されるらしく。裏世界のコレクターたちが勢ぞろいしているようですわ」"

[[dialogue]]
speaker = "セナリィ"
# 「隠密でのミッションですから、少数精鋭が基本──腕の立つ星騎士をもう１人お願いしていたのですが……」
line = "「隠密でのミッションですから、少数精鋭が基本──腕の立つ星騎士をもう１人お願いしていたのですが……」"

[[dialogue]]
speaker = "メルエル"
# 「はいっ！　姫咲メルエル、準備ＯＫだよ！」
line = "「はいっ！　姫咲メルエル、準備ＯＫだよ！」"

[[dialogue]]
speaker = "セナリィ"
# 「まさかボランティア部の姫咲さんを連れてくるとは思いませんでしたわ！？　ハイキングと勘違いしていまして！？」
line = "「まさかボランティア部の姫咲さんを連れてくるとは思いませんでしたわ！？　ハイキングと勘違いしていまして！？」"

[[dialogue]]
speaker = "unk"
# でもメルエルは優秀なプリマステラだよ
line = "でもメルエルは優秀なプリマステラだよ"

[[dialogue]]
speaker = "unk"
# どうしても他の人の都合がつかなくて……
line = "どうしても他の人の都合がつかなくて……"

[[dialogue]]
speaker = "セナリィ"
# 「確かに姫咲さんの戦闘力は、<ruby=わたくし>私</ruby>も認めるところではありますが……ゴールデングースの人員補充、真剣に考えなくてはなりませんわね……」
line = "「確かに姫咲さんの戦闘力は、<ruby>私<rt>わたくし</rt></ruby>も認めるところではありますが……ゴールデングースの人員補充、真剣に考えなくてはなりませんわね……」"

[[dialogue]]
speaker = "セナリィ"
# 「──こほん。それではそこの小窓から、オークション会場をのぞき見しますわよ。覚悟はよろしくて？」
line = "「──こほん。それではそこの小窓から、オークション会場をのぞき見しますわよ。覚悟はよろしくて？」"

[[dialogue]]
speaker = "メルエル"
# 「う、うんっ……大丈夫……！」
line = "「う、うんっ……大丈夫……！」"

[[dialogue]]
speaker = "セナリィ"
# 「ふふ。あなたのような表の世界で過ごすお方には、ショッキングな光景かもしれませんが……」
line = "「ふふ。あなたのような表の世界で過ごすお方には、ショッキングな光景かもしれませんが……」"

[[dialogue]]
speaker = "セナリィ"
# 「魔王である会長様のフィアンセを名乗るならば、アンダーグラウンドな世界を経験することも重要でしょう。気を引き締めてくださいまし？」
line = "「魔王である会長様のフィアンセを名乗るならば、アンダーグラウンドな世界を経験することも重要でしょう。気を引き締めてくださいまし？」"

[[dialogue]]
speaker = "メルエル"
# 「はいっ！　会長くんのお手伝いだもん、全力で取り組むよ……！」
line = "「はいっ！　会長くんのお手伝いだもん、全力で取り組むよ……！」"

[[dialogue]]
speaker = "unk"
# こうして俺たち３人は違法オークション会場を観察し、隙を探すことになった。
line = "こうして俺たち３人は違法オークション会場を観察し、隙を探すことになった。"

[[dialogue]]
speaker = "unk"
# 異様な熱気の中、魔界からの盗品や天界の貴重な書物など、そうそうたる物品が競り落とされていく。
line = "異様な熱気の中、魔界からの盗品や天界の貴重な書物など、そうそうたる物品が競り落とされていく。"

[[dialogue]]
speaker = "メルエル"
# 「セナリィさん、いつ取り押さえに行くの？」
line = "「セナリィさん、いつ取り押さえに行くの？」"

[[dialogue]]
speaker = "セナリィ"
# 「お待ちなさいな。まだ警備の数と装備を把握しきれていませんの。万全を期すのがプロフェッショナルでしてよ？」
line = "「お待ちなさいな。まだ警備の数と装備を把握しきれていませんの。万全を期すのがプロフェッショナルでしてよ？」"

[[dialogue]]
speaker = "メルエル"
# 「でも、明らかにどこかから盗んだ美術品なんかもあるし。見すごしてるみたいで落ち着かなくって……」
line = "「でも、明らかにどこかから盗んだ美術品なんかもあるし。見すごしてるみたいで落ち着かなくって……」"

[[dialogue]]
speaker = "セナリィ"
# 「競り落とした人物の顔は確認しています。万が一取り逃しても、後で捕まえれば問題ありませんわ」
line = "「競り落とした人物の顔は確認しています。万が一取り逃しても、後で捕まえれば問題ありませんわ」"

[[dialogue]]
speaker = "セナリィ"
# 「あ──会場の熱気が高まっていますわ。今夜の目玉が登場のようですわね」
line = "「あ──会場の熱気が高まっていますわ。今夜の目玉が登場のようですわね」"

[[dialogue]]
speaker = "司会"
# 「さぁお待ちかね。次なる品物は、１枚の写真にございます」
line = "「さぁお待ちかね。次なる品物は、１枚の写真にございます」"

[[dialogue]]
speaker = "司会"
# 「複製はなし。競り落とされた方にはデータも進呈いたしますので、紛うことなく世界でたった１枚のブロマイド」
line = "「複製はなし。競り落とされた方にはデータも進呈いたしますので、紛うことなく世界でたった１枚のブロマイド」"

[[dialogue]]
speaker = "司会"
# 「電撃のように登場し、即日に引退した伝説のユニットアイドル──アーネスト、姫咲メルエル嬢の写真です！」
line = "「電撃のように登場し、即日に引退した伝説のユニットアイドル──アーネスト、姫咲メルエル嬢の写真です！」"

[[dialogue]]
speaker = "unk"
# なんだって！？
line = "なんだって！？"

[[dialogue]]
speaker = "メルエル"
# 「えぇええぇっ！？　なななっ、なんで私の写真が！？」
line = "「えぇええぇっ！？　なななっ、なんで私の写真が！？」"

[[dialogue]]
speaker = "セナリィ"
# 「新星学園内でのライブでしたし、開催も突発でしたから。所属事務所も映像データは持っておりません」
line = "「新星学園内でのライブでしたし、開催も突発でしたから。所属事務所も映像データは持っておりません」"

[[dialogue]]
speaker = "セナリィ"
# 「それに今をときめくトップアイドル、愛戸レミカが見出した逸材──そんな理由から注目されているのでしょう」
line = "「それに今をときめくトップアイドル、愛戸レミカが見出した逸材──そんな理由から注目されているのでしょう」"

[[dialogue]]
speaker = "セナリィ"
# 「しかし警戒の厳重な学園内でこっそりと撮影したものが出回るとは……やはり裏オークション。後ろ暗いツテを持っているようですわね！」
line = "「しかし警戒の厳重な学園内でこっそりと撮影したものが出回るとは……やはり裏オークション。後ろ暗いツテを持っているようですわね！」"

[[dialogue]]
speaker = "司会"
# 「さぁさぁ、ご入札を──！」
line = "「さぁさぁ、ご入札を──！」"

[[dialogue]]
speaker = "参加者１"
# 「１千万テルス！」
line = "「１千万テルス！」"

[[dialogue]]
speaker = "参加者２"
# 「１千５百万テルスだ！」
line = "「１千５百万テルスだ！」"

[[dialogue]]
speaker = "メルエル"
# 「どどど、どうなってるの！？　理解が追い付かないよっ……どうして私なんかの写真にそんな値段を！？　お金は粗末にしちゃダメなんだよ……！」
line = "「どどど、どうなってるの！？　理解が追い付かないよっ……どうして私なんかの写真にそんな値段を！？　お金は粗末にしちゃダメなんだよ……！」"

[[dialogue]]
speaker = "セナリィ"
# 「即決価格は１億テルス……確かに入手難易度の高いものではありますが、そんな金額を払うなど正気の沙汰では──」
line = "「即決価格は１億テルス……確かに入手難易度の高いものではありますが、そんな金額を払うなど正気の沙汰では──」"

[[dialogue]]
speaker = "unk"
# １億テルス──即決だ！！
line = "１億テルス──即決だ！！"

[[dialogue]]
speaker = "unk"
# メルエルは誰にも渡さない！！
line = "メルエルは誰にも渡さない！！"

[[dialogue]]
speaker = "セナリィ"
# 「どうして参加していますのーーー！？」
line = "「どうして参加していますのーーー！？」"

[[dialogue]]
speaker = "参加者１"
# 「な、なんだっ！？　男が窓から飛び込んできたぞ！！」
line = "「な、なんだっ！？　男が窓から飛び込んできたぞ！！」"

[[dialogue]]
speaker = "参加者２"
# 「１億だと！？　いくら貴重だからって写真１枚にめちゃくちゃやりやがる……！」
line = "「１億だと！？　いくら貴重だからって写真１枚にめちゃくちゃやりやがる……！」"

[[dialogue]]
speaker = "参加者１"
# 「アイドルオタクか！？　クレイジーな野郎だぜ！！」
line = "「アイドルオタクか！？　クレイジーな野郎だぜ！！」"

[[dialogue]]
speaker = "参加者２"
# 「──って、あいつ見たことあるぞ！？　たしか新星学園の会長──くそっ、ガサ入れか！！」
line = "「──って、あいつ見たことあるぞ！？　たしか新星学園の会長──くそっ、ガサ入れか！！」"

[[dialogue]]
speaker = "unk"
# しまった、体が勝手に……！
line = "しまった、体が勝手に……！"

[[dialogue]]
speaker = "セナリィ"
# 「ばれちまってはしょうがありませんわね！　作戦変更、制圧しますわよ！　姫咲さん、サポートを──」
line = "「ばれちまってはしょうがありませんわね！　作戦変更、制圧しますわよ！　姫咲さん、サポートを──」"

[[dialogue]]
speaker = "メルエル"
# 「会長くんが……だ、誰にも渡さないって……え、えへへへぇ～っ<emoji=heart04>」
line = "「会長くんが……だ、誰にも渡さないって……え、えへへへぇ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "セナリィ"
# 「ぼけっとしないでくださいましーっ！！」
line = "「ぼけっとしないでくださいましーっ！！」"

[[dialogue]]
speaker = "unk"
# なんとか裏オークションを摘発した翌日──
line = "なんとか裏オークションを摘発した翌日──"

[[dialogue]]
speaker = "メルエル"
# 「──でねでね！　会長くんがね！　『メルエルは誰にも渡さない！』って飛び出して行ってね……！」
line = "「──でねでね！　会長くんがね！　『メルエルは誰にも渡さない！』って飛び出して行ってね……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ねぇレミカ。今朝からこの話、何度目かしら……？」
line = "「ねぇレミカ。今朝からこの話、何度目かしら……？」"

[[dialogue]]
speaker = "レミカ"
# 「よっぽど嬉しかったんでしょ。浸らせてあげなよ」
line = "「よっぽど嬉しかったんでしょ。浸らせてあげなよ」"

[[dialogue]]
speaker = "メルエル"
# 「もうあの時のこと思い出すだけでっ……はうぅうっ<emoji=heart04>　メルトしちゃうよぉ～っ……！」
line = "「もうあの時のこと思い出すだけでっ……はうぅうっ<emoji=heart04>　メルトしちゃうよぉ～っ……！」"

[[dialogue]]
speaker = "unk"
# 俺がセナリィにこってりと絞られた今回の件は、のちに『新星星徒会長１億テルス事件』として有名になってしまうのだが……
line = "俺がセナリィにこってりと絞られた今回の件は、のちに『新星星徒会長１億テルス事件』として有名になってしまうのだが……"

[[dialogue]]
speaker = "unk"
# メルエルのアイドル写真とデータを無事に押収できたため、彼氏としては胸をなでおろすことができたのだった──
line = "メルエルのアイドル写真とデータを無事に押収できたため、彼氏としては胸をなでおろすことができたのだった──"
