[[dialogue]]
speaker = "unk"
# 第１話,新たな誓い,P
line = "第１話,新たな誓い,P"

[[dialogue]]
speaker = "unk"
# 紫桜の里で起きた事件を解決し視察を終えた俺たちは、空間転移装置を使って九浄の屋敷へと戻ってきた。
line = "紫桜の里で起きた事件を解決し視察を終えた俺たちは、空間転移装置を使って九浄の屋敷へと戻ってきた。"

[[dialogue]]
speaker = "ウズメイア"
# 「うぷっ……やっぱあたし、この空間転移っていうのは苦手かも……」
line = "「うぷっ……やっぱあたし、この空間転移っていうのは苦手かも……」"

[[dialogue]]
speaker = "せつな"
# 「また酔ったでござるか？　そんな時には師匠特製の秘薬でござる！」
line = "「また酔ったでござるか？　そんな時には師匠特製の秘薬でござる！」"

[[dialogue]]
speaker = "ウズメイア"
# 「おししょー様の薬の効果は分かってるけど、今回はちょっちパス……ふつーに休んでれば治るっしょ」
line = "「おししょー様の薬の効果は分かってるけど、今回はちょっちパス……ふつーに休んでれば治るっしょ」"

[[dialogue]]
speaker = "ヨミ"
# 「飲み薬ですからね……転移酔いとは相性が悪いかもしれません」
line = "「飲み薬ですからね……転移酔いとは相性が悪いかもしれません」"

[[dialogue]]
speaker = "せつな"
# 「それもそうでござるな……ではウズメ殿は少し休んでいるでござる。当主様への報告はせつなたちに任せるでござるよ」
line = "「それもそうでござるな……ではウズメ殿は少し休んでいるでござる。当主様への報告はせつなたちに任せるでござるよ」"

[[dialogue]]
speaker = "unk"
# ウズメをお願い
line = "ウズメをお願い"

[[dialogue]]
speaker = "unk"
# ヨミヨミ、任せてもいい？
line = "ヨミヨミ、任せてもいい？"

[[dialogue]]
speaker = "ヨミ"
# 「わかりました。さあウズメさん、こちらへ」
line = "「わかりました。さあウズメさん、こちらへ」"

[[dialogue]]
speaker = "ウズメイア"
# 「うん、ありがとー、ヨミヨミ」
line = "「うん、ありがとー、ヨミヨミ」"

[[dialogue]]
speaker = "せつな"
# 「ヨミ殿がついていれば安心でござるな。さて主様、我らは当主様へ帰還の報告に参るでござるよ」
line = "「ヨミ殿がついていれば安心でござるな。さて主様、我らは当主様へ帰還の報告に参るでござるよ」"

[[dialogue]]
speaker = "ヘレナ"
# 「よく戻った。両名とも無事でなによりだ」
line = "「よく戻った。両名とも無事でなによりだ」"

[[dialogue]]
speaker = "せつな"
# 「ヨミ殿は転移酔いのウズメ殿に付き添ってもらっているでござる」
line = "「ヨミ殿は転移酔いのウズメ殿に付き添ってもらっているでござる」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふむ。報告は受けているが、転移酔いを起こす者もいるようだな。アニマに伝えておくとしよう」
line = "「ふむ。報告は受けているが、転移酔いを起こす者もいるようだな。アニマに伝えておくとしよう」"

[[dialogue]]
speaker = "ヘレナ"
# 「それよりもアステラの件だ。偶然だろうが、シズル殿の依頼が功を奏したようだな」
line = "「それよりもアステラの件だ。偶然だろうが、シズル殿の依頼が功を奏したようだな」"

[[dialogue]]
speaker = "せつな"
# 「師匠の依頼？　いったい何のことでござるか？」
line = "「師匠の依頼？　いったい何のことでござるか？」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふむ、聞いていないか。今回の転移先を紫桜の里に選定した理由は、彼の者より依頼があったからなのだ」
line = "「ふむ、聞いていないか。今回の転移先を紫桜の里に選定した理由は、彼の者より依頼があったからなのだ」"

[[dialogue]]
speaker = "せつな"
# 「なんと、そういうことでござったか……」
line = "「なんと、そういうことでござったか……」"

[[dialogue]]
speaker = "ヘレナ"
# 「新たな人工戦闘服も、全て彼女の意向によるものだ。里の未来を託す忍に相応しき装束を、とな」
line = "「新たな人工戦闘服も、全て彼女の意向によるものだ。里の未来を託す忍に相応しき装束を、とな」"

[[dialogue]]
speaker = "せつな"
# 「まさか、師匠がそんなことをしてくれてただなんて……」
line = "「まさか、師匠がそんなことをしてくれてただなんて……」"

[[dialogue]]
speaker = "unk"
# いいお師匠様だね
line = "いいお師匠様だね"

[[dialogue]]
speaker = "unk"
# 優しい人だね
line = "優しい人だね"

[[dialogue]]
speaker = "せつな"
# 「ううっ、ししょおぉ～～。今のせつながあるのは、師匠のおかげにござるよぉ～～」
line = "「ううっ、ししょおぉ～～。今のせつながあるのは、師匠のおかげにござるよぉ～～」"

[[dialogue]]
speaker = "せつな"
# 「アステラの発生は偶然でも、あれがなければせつなは過去を振り切れなかったやも知れませぬ」
line = "「アステラの発生は偶然でも、あれがなければせつなは過去を振り切れなかったやも知れませぬ」"

[[dialogue]]
speaker = "せつな"
# 「主様。今ここで改めて、せつなの成長した姿を見て欲しいでござる！」
line = "「主様。今ここで改めて、せつなの成長した姿を見て欲しいでござる！」"

[[dialogue]]
speaker = "せつな"
# 「勇気と慈愛を胸に――目覚めよっ！　《開花》フォォォーーーームっっ！！」
line = "「勇気と慈愛を胸に――目覚めよっ！　《開花》フォォォーーーームっっ！！」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「これが……成長したせつなの姿にござる……」
line = "「これが……成長したせつなの姿にござる……」"

[[dialogue]]
speaker = "unk"
# 立派だね
line = "立派だね"

[[dialogue]]
speaker = "unk"
# すごいよ
line = "すごいよ"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「有難きお言葉にござる。ですが、せつな１人では到底ここに至れなかったでござる」
line = "「有難きお言葉にござる。ですが、せつな１人では到底ここに至れなかったでござる」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「師匠と里のみんな、ヨミ殿にウズメ殿……そして主様がいてくれたから……」
line = "「師匠と里のみんな、ヨミ殿にウズメ殿……そして主様がいてくれたから……」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「みんなの力でせつなは成長できたでござる。そのことを、しかと胸に刻みつけるでござる」
line = "「みんなの力でせつなは成長できたでござる。そのことを、しかと胸に刻みつけるでござる」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「あのような悲劇を、二度と起こさぬために、この《開花》フォームに誓って！」
line = "「あのような悲劇を、二度と起こさぬために、この《開花》フォームに誓って！」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「そして、忍として、主様に更なる忠誠を……！」
line = "「そして、忍として、主様に更なる忠誠を……！」"

[[dialogue]]
speaker = "unk"
# 今まで通りでいいよ
line = "今まで通りでいいよ"

[[dialogue]]
speaker = "unk"
# そこまで堅苦しく考えなくても
line = "そこまで堅苦しく考えなくても"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「そうは参りませぬ！」
line = "「そうは参りませぬ！」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「忍は護る相手がいて、初めて強くなれる。せつなは今回の件で、それを学んだでござる」
line = "「忍は護る相手がいて、初めて強くなれる。せつなは今回の件で、それを学んだでござる」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「そして、その相手が自分にとって大切な御仁であれば、より力を発揮できる、と」
line = "「そして、その相手が自分にとって大切な御仁であれば、より力を発揮できる、と」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「…………にゃっ？　い、今のは少々ハレンチな台詞でござったか？」
line = "「…………にゃっ？　い、今のは少々ハレンチな台詞でござったか？」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「け、けど、否定はしないでござる。主様の忍として、更なる忠心を以て、お仕えする所存！」
line = "「け、けど、否定はしないでござる。主様の忍として、更なる忠心を以て、お仕えする所存！」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「ということで主様。今回はこれにて任務終了にござるが、今後ともせつなをよろしく、でござるよ♪」
line = "「ということで主様。今回はこれにて任務終了にござるが、今後ともせつなをよろしく、でござるよ♪」"

[[dialogue]]
speaker = "unk"
# こうして、気持ちも新たにせつなは忠誠を誓ってくれるのだった。
line = "こうして、気持ちも新たにせつなは忠誠を誓ってくれるのだった。"
