[[dialogue]]
speaker = "unk"
# 第３話,潜入調査・星徒会！,P
line = "第３話,潜入調査・星徒会！,P"

[[dialogue]]
speaker = "ヒヨ"
# 「ここが新星学園の星徒会室か……」
line = "「ここが新星学園の星徒会室か……」"

[[dialogue]]
speaker = "unk"
# ゆっくりしていってね
line = "ゆっくりしていってね"

[[dialogue]]
speaker = "ヒヨ"
# 「別にくつろぎに来たわけじゃねえ！　あたしは会長サンを監視するために──」
line = "「別にくつろぎに来たわけじゃねえ！　あたしは会長サンを監視するために──」"

[[dialogue]]
speaker = "unk"
# お菓子あるけど、いる？
line = "お菓子あるけど、いる？"

[[dialogue]]
speaker = "ヒヨ"
# 「いただくぜい！」
line = "「いただくぜい！」"

[[dialogue]]
speaker = "マトイ"
# 「ねぇねぇ会長。この子は？」
line = "「ねぇねぇ会長。この子は？」"

[[dialogue]]
speaker = "ヒヨ"
# 「はぐはぐはぐっ……あたしは天桐ヒヨ！　新星１年のプリマステラでさぁ！　今日は会長サンを監視するために来たのさ！」
line = "「はぐはぐはぐっ……あたしは天桐ヒヨ！　新星１年のプリマステラでさぁ！　今日は会長サンを監視するために来たのさ！」"

[[dialogue]]
speaker = "マトイ"
# 「監視！？　会長ってば何か悪いことしたの？」
line = "「監視！？　会長ってば何か悪いことしたの？」"

[[dialogue]]
speaker = "アナ"
# 「……ふむ、それとも何か疑惑でもかけられているのでしょうか？」
line = "「……ふむ、それとも何か疑惑でもかけられているのでしょうか？」"

[[dialogue]]
speaker = "ヒヨ"
# 「会長サンは星徒会でハーレムを作ってるって話だ。それを確かめに来たんでい」
line = "「会長サンは星徒会でハーレムを作ってるって話だ。それを確かめに来たんでい」"

[[dialogue]]
speaker = "サーシャ"
# 「あら～♪　知らない間にみんなをハーレムの一員にしちゃうなんて、スミにおけないわね～♪」
line = "「あら～♪　知らない間にみんなをハーレムの一員にしちゃうなんて、スミにおけないわね～♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そんな事実はないわよ！　もしクロトがそんな気を起こすなら、真っ先に私に声をかけるはずだもの！！」
line = "「そんな事実はないわよ！　もしクロトがそんな気を起こすなら、真っ先に私に声をかけるはずだもの！！」"

[[dialogue]]
speaker = "マトイ"
# 「あはは……相変わらずすごい自信……」
line = "「あはは……相変わらずすごい自信……」"

[[dialogue]]
speaker = "ヒヨ"
# 「おっと、続々と集まってきたな……。それで、誰が会長サンの本命なんでい？」
line = "「おっと、続々と集まってきたな……。それで、誰が会長サンの本命なんでい？」"

[[dialogue]]
speaker = "unk"
# みんな大切な仲間だから
line = "みんな大切な仲間だから"

[[dialogue]]
speaker = "ヒヨ"
# 「そんなヒヨった返事は聞いてないやいっ」
line = "「そんなヒヨった返事は聞いてないやいっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうよ！　男の子なんだから、シャキッとしなさい！」
line = "「そうよ！　男の子なんだから、シャキッとしなさい！」"

[[dialogue]]
speaker = "マトイ"
# 「ヴィーナスまで加勢してるし」
line = "「ヴィーナスまで加勢してるし」"

[[dialogue]]
speaker = "アナ"
# 「ですが、会長の本命が誰なのかは、少し気になりますね」
line = "「ですが、会長の本命が誰なのかは、少し気になりますね」"

[[dialogue]]
speaker = "ヒヨ"
# 「会長サンは助兵衛そうだから……やっぱり、色っぽい年上の先輩が一番かい？」
line = "「会長サンは助兵衛そうだから……やっぱり、色っぽい年上の先輩が一番かい？」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら、私のことかしら♪」
line = "「あらあら、私のことかしら♪」"

[[dialogue]]
speaker = "ヒヨ"
# 「一目で分かる大きな乳房に、溢れる母性……普通の男なら、イチコロで堕ちちまうぜ」
line = "「一目で分かる大きな乳房に、溢れる母性……普通の男なら、イチコロで堕ちちまうぜ」"

[[dialogue]]
speaker = "サーシャ"
# 「照れるわね～♪」
line = "「照れるわね～♪」"

[[dialogue]]
speaker = "ヒヨ"
# 「……ほう、それでも本命じゃないときたか。だったら逆に年下好きなのかい？」
line = "「……ほう、それでも本命じゃないときたか。だったら逆に年下好きなのかい？」"

[[dialogue]]
speaker = "アナ"
# 「ということは私ですかね」
line = "「ということは私ですかね」"

[[dialogue]]
speaker = "ヒヨ"
# 「身体は未成熟……だけど、精神年齢は高めのギャップがいい！　こいつは罪な香りがするぜい……」
line = "「身体は未成熟……だけど、精神年齢は高めのギャップがいい！　こいつは罪な香りがするぜい……」"

[[dialogue]]
speaker = "アナ"
# 「まだまだ成長途中ですが、会長はそういうのがお好みですか？」
line = "「まだまだ成長途中ですが、会長はそういうのがお好みですか？」"

[[dialogue]]
speaker = "ヒヨ"
# 「ふむ違うのか……年上でも年下でもないとすると……」
line = "「ふむ違うのか……年上でも年下でもないとすると……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「もちろん、私が一番よね！」
line = "「もちろん、私が一番よね！」"

[[dialogue]]
speaker = "ヒヨ"
# 「そこの大人しそうな同級生が好みかい？」
line = "「そこの大人しそうな同級生が好みかい？」"

[[dialogue]]
speaker = "マトイ"
# 「え！？　私……！」
line = "「え！？　私……！」"

[[dialogue]]
speaker = "ヒヨ"
# 「一見地味に見えるが、自分だけが分かってあげられる魅力に溢れてやがる……守ってあげたくなるような女の子らしさが抜群だぜい！」
line = "「一見地味に見えるが、自分だけが分かってあげられる魅力に溢れてやがる……守ってあげたくなるような女の子らしさが抜群だぜい！」"

[[dialogue]]
speaker = "マトイ"
# 「そ、そんな私なんて、なんの取り柄もないのにっ」
line = "「そ、そんな私なんて、なんの取り柄もないのにっ」"

[[dialogue]]
speaker = "ヒヨ"
# 「ううむ……それでも違うって感じだな……。じゃあ残るは……」
line = "「ううむ……それでも違うって感じだな……。じゃあ残るは……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そう、私よ！」
line = "「そう、私よ！」"

[[dialogue]]
speaker = "ヒヨ"
# 「いや、ないな……」
line = "「いや、ないな……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なんでよ！」
line = "「なんでよ！」"

[[dialogue]]
speaker = "ヒヨ"
# 「いやぁ、前会長さんは乙女力が足りねぇぜ」
line = "「いやぁ、前会長さんは乙女力が足りねぇぜ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「何を言ってるの？　星徒会随一の乙女と言えばこの私よ。ほら、マトイも言ってやりなさい」
line = "「何を言ってるの？　星徒会随一の乙女と言えばこの私よ。ほら、マトイも言ってやりなさい」"

[[dialogue]]
speaker = "マトイ"
# 「うーん……乙女、だと思うよ？」
line = "「うーん……乙女、だと思うよ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なんで疑問形なのよ！　アナからも何か言ってやってちょうだい！」
line = "「なんで疑問形なのよ！　アナからも何か言ってやってちょうだい！」"

[[dialogue]]
speaker = "アナ"
# 「ノーコメントでお願いします」
line = "「ノーコメントでお願いします」"

[[dialogue]]
speaker = "ヒヨ"
# 「ダメじゃねぇか」
line = "「ダメじゃねぇか」"

[[dialogue]]
speaker = "ヒヨ"
# 「しかし、結局会長サンの本命は分からず仕舞いだな」
line = "「しかし、結局会長サンの本命は分からず仕舞いだな」"

[[dialogue]]
speaker = "unk"
# 仲間に順位付けなんて出来ないよ
line = "仲間に順位付けなんて出来ないよ"

[[dialogue]]
speaker = "ヒヨ"
# 「そうやって、あやふやにするのがハーレムのコツってわけかい」
line = "「そうやって、あやふやにするのがハーレムのコツってわけかい」"

[[dialogue]]
speaker = "unk"
# ヒヨだって、大切な後輩だよ
line = "ヒヨだって、大切な後輩だよ"

[[dialogue]]
speaker = "ヒヨ"
# 「なっ！？　あたしまで会長サンの守備範囲なのかい！？　あたしなんて、全然良かねぇだろ……」
line = "「なっ！？　あたしまで会長サンの守備範囲なのかい！？　あたしなんて、全然良かねぇだろ……」"

[[dialogue]]
speaker = "unk"
# ううん、可愛い後輩だよ
line = "ううん、可愛い後輩だよ"

[[dialogue]]
speaker = "ヒヨ"
# 「そ、そうやって籠絡しようたって、無駄だからなっ」
line = "「そ、そうやって籠絡しようたって、無駄だからなっ」"

[[dialogue]]
speaker = "ヒヨ"
# 「あたしは姐さん一筋なんでいっ、会長サンなんか興味ないやい」
line = "「あたしは姐さん一筋なんでいっ、会長サンなんか興味ないやい」"

[[dialogue]]
speaker = "ヒヨ"
# 「だがまあ……姐さんの安全を守るためにも、会長サンの監視は続けさせてもらうぜい！」
line = "「だがまあ……姐さんの安全を守るためにも、会長サンの監視は続けさせてもらうぜい！」"
