[[dialogue]]
speaker = "unk"
# 第３話,貴族の恋バナ？,P
line = "第３話,貴族の恋バナ？,P"

[[dialogue]]
speaker = "シャルレーヌ"
# 「それでジュリエッテ様、会長さんとその後はどんな感じなんです？」
line = "「それでジュリエッテ様、会長さんとその後はどんな感じなんです？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ふふ、もちろん順調でございますわ。たとえ魔王様といえども、わたくしの手にかかればちょちょいのちょいでございますわ」
line = "「ふふ、もちろん順調でございますわ。たとえ魔王様といえども、わたくしの手にかかればちょちょいのちょいでございますわ」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ふ～ん、なら会長さんとどんなことをしたんですか？」
line = "「ふ～ん、なら会長さんとどんなことをしたんですか？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ええっ！？　そ、それはでございますね……とてもアダルトなことですわ！」
line = "「ええっ！？　そ、それはでございますね……とてもアダルトなことですわ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「まぁ大胆♪　具体的にどんなことをされたんですか～？　気になりますね～」
line = "「まぁ大胆♪　具体的にどんなことをされたんですか～？　気になりますね～」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「それは……その、でございますね……とても公共の場では言えませんわ……！」
line = "「それは……その、でございますね……とても公共の場では言えませんわ……！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「おやおや～？　もしかして全然進展してないんじゃないですか～？　ジュリエッテ様ってばヘタレなんですから♪」
line = "「おやおや～？　もしかして全然進展してないんじゃないですか～？　ジュリエッテ様ってばヘタレなんですから♪」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「んなっ！？　ヘタレではございませんわ！　淑女でございますの！　お付き合いしていないのに、ふしだらなことはできませんわ！」
line = "「んなっ！？　ヘタレではございませんわ！　淑女でございますの！　お付き合いしていないのに、ふしだらなことはできませんわ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ほら～、やっぱり嘘だったんですね～♪　くふふ♪」
line = "「ほら～、やっぱり嘘だったんですね～♪　くふふ♪」"

[[dialogue]]
speaker = "ジュリエッテ"
# （くぅ～～～～！！　やっぱり腹立ちますわ～～！　わたくしっ、この方嫌い！！）
line = "（くぅ～～～～！！　やっぱり腹立ちますわ～～！　わたくしっ、この方嫌い！！）"

[[dialogue]]
speaker = "シャルレーヌ"
# 「やっぱりジュリエッテ様に会長さんの攻略はムリってことですね♪」
line = "「やっぱりジュリエッテ様に会長さんの攻略はムリってことですね♪」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「そんなことございませんわ……！　なんて言ったってわたくし、魔王様のお家にお呼ばれされたのでございますもの！」
line = "「そんなことございませんわ……！　なんて言ったってわたくし、魔王様のお家にお呼ばれされたのでございますもの！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「お呼ばれ……！？　……でもどうせ、ジュリエッテ様が押しかけたんでしょう？」
line = "「お呼ばれ……！？　……でもどうせ、ジュリエッテ様が押しかけたんでしょう？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ぐぬぬっ、そうやって何でもかんでも疑うのは品性に欠けましてよ！」
line = "「ぐぬぬっ、そうやって何でもかんでも疑うのは品性に欠けましてよ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「おや？　否定しないということは、図星なんですかね～」
line = "「おや？　否定しないということは、図星なんですかね～」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「で、ですが、魔王様のお家に伺ったのは本当のことでございますわっ」
line = "「で、ですが、魔王様のお家に伺ったのは本当のことでございますわっ」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「あっそう……で、会長さんのお家で何をしたんです？」
line = "「あっそう……で、会長さんのお家で何をしたんです？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ふふ、魔王様に手料理を振る舞いましたわ～！」
line = "「ふふ、魔王様に手料理を振る舞いましたわ～！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「魔王様ったら、わたくしの手料理をそれはそれは美味しそうに平らげてくださいましたわ！」
line = "「魔王様ったら、わたくしの手料理をそれはそれは美味しそうに平らげてくださいましたわ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ふーん……それだけですか？」
line = "「ふーん……それだけですか？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「……それだけとはどういうことでございます？」
line = "「……それだけとはどういうことでございます？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「だから～、会長さんのお家に行って、料理して帰っただけなんです～？」
line = "「だから～、会長さんのお家に行って、料理して帰っただけなんです～？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「そ、そそそんなことはございませんわっ……！　このわたくしが、その程度のことで終わるはずがありませんもの！」
line = "「そ、そそそんなことはございませんわっ……！　このわたくしが、その程度のことで終わるはずがありませんもの！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「じゃあ他には何をしたんですか～？　もっと教えてくださいよー」
line = "「じゃあ他には何をしたんですか～？　もっと教えてくださいよー」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「それは……え～と……こ、婚約っ、婚約も済ませましたわ！　魔王様と婚約！」
line = "「それは……え～と……こ、婚約っ、婚約も済ませましたわ！　魔王様と婚約！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「は？」
line = "「は？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「魔王様とはもう将来を誓い合った仲になったでございますの～！」
line = "「魔王様とはもう将来を誓い合った仲になったでございますの～！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「でもさっき、魔王様とお付き合いしてないって言っていましたよね？」
line = "「でもさっき、魔王様とお付き合いしてないって言っていましたよね？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「そ、それは……！！」
line = "「そ、それは……！！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「どうしてそんなしょうもない嘘を吐くんです？　昔からそうですが、無駄に見栄っ張りなんですから」
line = "「どうしてそんなしょうもない嘘を吐くんです？　昔からそうですが、無駄に見栄っ張りなんですから」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「うぐぐっ！！　そんな冷たい目を向けないでくださいまし！」
line = "「うぐぐっ！！　そんな冷たい目を向けないでくださいまし！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「はぁ……ジュリエッテ様って、本当に残念な人ですね～」
line = "「はぁ……ジュリエッテ様って、本当に残念な人ですね～」"

[[dialogue]]
speaker = "ジュリエッテ"
# （本っ当に腹が立つでございますわ～！　くぅ～～～～！！）
line = "（本っ当に腹が立つでございますわ～！　くぅ～～～～！！）"

[[dialogue]]
speaker = "シャルレーヌ"
# 「普通男の子のお家に行ったら、もっと他にやることとかありませ～ん？」
line = "「普通男の子のお家に行ったら、もっと他にやることとかありませ～ん？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ハレンチですわ！　不健全ですわ！　風紀が乱れますわ～！」
line = "「ハレンチですわ！　不健全ですわ！　風紀が乱れますわ～！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「何を想像したのかは分かりませんけど、ジュリエッテ様がそんな調子なら、私が会長さんを手に入れるのも時間の問題ですね～♪」
line = "「何を想像したのかは分かりませんけど、ジュリエッテ様がそんな調子なら、私が会長さんを手に入れるのも時間の問題ですね～♪」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「なっ！？　そんなことはさせませんわ！」
line = "「なっ！？　そんなことはさせませんわ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「でも～、ヘタレなジュリエッテ様には無理なんじゃないです～？　会長さんを虜にするのは♪」
line = "「でも～、ヘタレなジュリエッテ様には無理なんじゃないです～？　会長さんを虜にするのは♪」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「むっか～～～～！！　できますわやってやるでございますわ～～！！」
line = "「むっか～～～～！！　できますわやってやるでございますわ～～！！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「魔王様なんかわたくしの美貌でイチコロでございますからっ！」
line = "「魔王様なんかわたくしの美貌でイチコロでございますからっ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「プッ……美貌ねぇ♪」
line = "「プッ……美貌ねぇ♪」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「何か異論でもあるのでございます！？」
line = "「何か異論でもあるのでございます！？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「い～え？　ジュリエッテ様はと～っても、おかわいいですよ♪」
line = "「い～え？　ジュリエッテ様はと～っても、おかわいいですよ♪」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「絶っっ対にバカにしてやがるでございますね！！　覚えてらっしゃいませ！　今すぐ魔王様をわたくしのものにしてやりますわ！」
line = "「絶っっ対にバカにしてやがるでございますね！！　覚えてらっしゃいませ！　今すぐ魔王様をわたくしのものにしてやりますわ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「はいはい、がんばってくださいね～♪」
line = "「はいはい、がんばってくださいね～♪」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ぎぃぃぃぃ！！　ぜーったいに吠え面をかかせてやりますわ～！」
line = "「ぎぃぃぃぃ！！　ぜーったいに吠え面をかかせてやりますわ～！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「はぁはぁ、はぁはぁはぁっ……はぁ、はぁ……」
line = "「はぁはぁ、はぁはぁはぁっ……はぁ、はぁ……」"

[[dialogue]]
speaker = "unk"
# ジュリエッテ？
line = "ジュリエッテ？"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ま、魔王様……ここで会ったが百年目ですわ……！」
line = "「ま、魔王様……ここで会ったが百年目ですわ……！」"

[[dialogue]]
speaker = "unk"
# え、何？　果し合い？
line = "え、何？　果し合い？"

[[dialogue]]
speaker = "ジュリエッテ"
# 「おデートですわ～～～！！」
line = "「おデートですわ～～～！！」"

[[dialogue]]
speaker = "unk"
# ！！？？
line = "！！？？"

[[dialogue]]
speaker = "ジュリエッテ"
# 「魔王様、おデートしますわよ！　わたくしと！」
line = "「魔王様、おデートしますわよ！　わたくしと！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「わたくしの美貌で魔王様をメロメロにしてあげますわ！　イチコロでございますわ！」
line = "「わたくしの美貌で魔王様をメロメロにしてあげますわ！　イチコロでございますわ！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「言っておきますが、魔王様に拒否権はないでございますわよ！　おデートするったらしますわよ！」
line = "「言っておきますが、魔王様に拒否権はないでございますわよ！　おデートするったらしますわよ！」"

[[dialogue]]
speaker = "unk"
# 分かった
line = "分かった"

[[dialogue]]
speaker = "ジュリエッテ"
# 「即答でございますの！？　わたくし達敵同士でございますよ！？」
line = "「即答でございますの！？　わたくし達敵同士でございますよ！？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ま、まあいいでございますわ……決戦の時は日曜日！　それまで首を洗って待っていてくださいな！」
line = "「ま、まあいいでございますわ……決戦の時は日曜日！　それまで首を洗って待っていてくださいな！」"

[[dialogue]]
speaker = "unk"
# 楽しみにしてる
line = "楽しみにしてる"

[[dialogue]]
speaker = "ジュリエッテ"
# 「そ、そんな目を輝かせないでくださいまし！　顔が赤くなるでございますわ～！」
line = "「そ、そんな目を輝かせないでくださいまし！　顔が赤くなるでございますわ～！」"

[[dialogue]]
speaker = "unk"
# そう言い放ってジュリエッテは逃げるように去っていってしまった。
line = "そう言い放ってジュリエッテは逃げるように去っていってしまった。"
