[[dialogue]]
speaker = "unk"
# 第１話,新星の寮長,P
line = "第１話,新星の寮長,P"

[[dialogue]]
speaker = "unk"
# それは、星徒会長に就任してまだ間もない時のこと。とある女子生徒から、星徒会長に挨拶したいというアポがあった。
line = "それは、星徒会長に就任してまだ間もない時のこと。とある女子生徒から、星徒会長に挨拶したいというアポがあった。"

[[dialogue]]
speaker = "unk"
# 放課後、星徒会室で待っていると──
line = "放課後、星徒会室で待っていると──"

[[dialogue]]
speaker = "マハムート"
# 「失礼するわよ」
line = "「失礼するわよ」"

[[dialogue]]
speaker = "マハムート"
# 「はじめまして、星徒会長。この前の御前試合、見させてもらったわ」
line = "「はじめまして、星徒会長。この前の御前試合、見させてもらったわ」"

[[dialogue]]
speaker = "マハムート"
# 「私は新星学園３年生、<ruby=きりゅういん>妃竜院</ruby>マハムートよ」
line = "「私は新星学園３年生、<ruby>妃竜院<rt>きりゅういん</rt></ruby>マハムートよ」"

[[dialogue]]
speaker = "unk"
# よろしくお願いします、先輩
line = "よろしくお願いします、先輩"

[[dialogue]]
speaker = "マハムート"
# 「礼儀正しくて良いことね。けれど、私は周りから畏怖を込めて『マム』と呼ばれているの」
line = "「礼儀正しくて良いことね。けれど、私は周りから畏怖を込めて『マム』と呼ばれているの」"

[[dialogue]]
speaker = "マハムート"
# 「したがって──」
line = "「したがって──」"

[[dialogue]]
speaker = "マハムート"
# 「アナタも今この瞬間から、私のことをマムと呼びなさい！　ちなみに返事は、イエス・マムよ！」
line = "「アナタも今この瞬間から、私のことをマムと呼びなさい！　ちなみに返事は、イエス・マムよ！」"

[[dialogue]]
speaker = "unk"
# い、イエス・マム
line = "い、イエス・マム"

[[dialogue]]
speaker = "マハムート"
# 「声が小さいわね。まあ、言えただけ良しとしてあげるわ」
line = "「声が小さいわね。まあ、言えただけ良しとしてあげるわ」"

[[dialogue]]
speaker = "マハムート"
# 「それで本題だけど、今回会いに来たのは、私が『新星寮ラルーナ』の寮長だからよ」
line = "「それで本題だけど、今回会いに来たのは、私が『新星寮ラルーナ』の寮長だからよ」"

[[dialogue]]
speaker = "マハムート"
# 「アナタは新星寮について、どのくらい知っているのかしら？」
line = "「アナタは新星寮について、どのくらい知っているのかしら？」"

[[dialogue]]
speaker = "unk"
# 実はまだ、よく知らなくて……
line = "実はまだ、よく知らなくて……"

[[dialogue]]
speaker = "マハムート"
# 「やれやれ勉強不足ね。会いに来て正解だったわ」
line = "「やれやれ勉強不足ね。会いに来て正解だったわ」"

[[dialogue]]
speaker = "マハムート"
# 「なら、今のうちに頭に叩き込んでおきなさい。星徒会長の仕事にも関わることよ」
line = "「なら、今のうちに頭に叩き込んでおきなさい。星徒会長の仕事にも関わることよ」"

[[dialogue]]
speaker = "マハムート"
# 「新星学園と流星学園では、三界から強い星力を持つ生徒達を集めているわ」
line = "「新星学園と流星学園では、三界から強い星力を持つ生徒達を集めているわ」"

[[dialogue]]
speaker = "マハムート"
# 「種族を問わず、私のような魔族や、天使の生徒もね。それで生徒の多くは、学園の寮暮らしをしているの」
line = "「種族を問わず、私のような魔族や、天使の生徒もね。それで生徒の多くは、学園の寮暮らしをしているの」"

[[dialogue]]
speaker = "マハムート"
# 「その寮が『新星寮ラルーナ』と『流星寮イルソーレ』というわけ」
line = "「その寮が『新星寮ラルーナ』と『流星寮イルソーレ』というわけ」"

[[dialogue]]
speaker = "マハムート"
# 「そして私は、１年に１度行われる寮内投票で選ばれた、新星寮の寮長<ruby=エトワール・ラルーナ>『宵闇の極星』</ruby>なのよ」
line = "「そして私は、１年に１度行われる寮内投票で選ばれた、新星寮の寮長<ruby>『宵闇の極星』<rt>エトワール・ラルーナ</rt></ruby>なのよ」"

[[dialogue]]
speaker = "unk"
# 宵闇の極星？
line = "宵闇の極星？"

[[dialogue]]
speaker = "マハムート"
# 「新星寮の寮長に与えられる称号のようなものね。ラルーナは夜って意味があるのよ。だから、『夜の闇で最も輝く星』ってことね」
line = "「新星寮の寮長に与えられる称号のようなものね。ラルーナは夜って意味があるのよ。だから、『夜の闇で最も輝く星』ってことね」"

[[dialogue]]
speaker = "マハムート"
# 「言っておくけど、寮長の称号は伊達じゃないわよ？　星徒会長は学園内で最も大きな権限が与えられているけれど、寮に関しては寮長の権限の方が優先されるわ」
line = "「言っておくけど、寮長の称号は伊達じゃないわよ？　星徒会長は学園内で最も大きな権限が与えられているけれど、寮に関しては寮長の権限の方が優先されるわ」"

[[dialogue]]
speaker = "マハムート"
# 「つまり、アナタが寮に関わる際には、まず私に話を通す必要があるということよ。星徒会長といえども、寮の運営で勝手なことは許さないから、しっかり覚えておきなさい」
line = "「つまり、アナタが寮に関わる際には、まず私に話を通す必要があるということよ。星徒会長といえども、寮の運営で勝手なことは許さないから、しっかり覚えておきなさい」"

[[dialogue]]
speaker = "unk"
# イエス・マム！
line = "イエス・マム！"

[[dialogue]]
speaker = "マハムート"
# 「ふっ、今度は良い返事ね。その調子で私を畏怖なさい」
line = "「ふっ、今度は良い返事ね。その調子で私を畏怖なさい」"

[[dialogue]]
speaker = "マハムート"
# 「それから、他にも言っておくことがあるわ」
line = "「それから、他にも言っておくことがあるわ」"

[[dialogue]]
speaker = "マハムート"
# 「アナタ、流星学園の星徒会長である、星見フィオナと仲が良いみたいね？　サーシャから聞いたわ」
line = "「アナタ、流星学園の星徒会長である、星見フィオナと仲が良いみたいね？　サーシャから聞いたわ」"

[[dialogue]]
speaker = "マハムート"
# 「何も知らないままでは困るから忠告しておくけれど、流星学園はライバル校でもあると、わかっているのかしら？」
line = "「何も知らないままでは困るから忠告しておくけれど、流星学園はライバル校でもあると、わかっているのかしら？」"

[[dialogue]]
speaker = "マハムート"
# 「新星と流星は毎年、『学園対抗杯』というものを行っていて、実力を競い合っているの」
line = "「新星と流星は毎年、『学園対抗杯』というものを行っていて、実力を競い合っているの」"

[[dialogue]]
speaker = "マハムート"
# 「そして遺憾なことに、新星はここ２年、流星に連敗を喫してしまっているわ」
line = "「そして遺憾なことに、新星はここ２年、流星に連敗を喫してしまっているわ」"

[[dialogue]]
speaker = "マハムート"
# 「だから今年こそは、流星を完膚なきまでに叩きのめし、勝利するのよ！」
line = "「だから今年こそは、流星を完膚なきまでに叩きのめし、勝利するのよ！」"

[[dialogue]]
speaker = "unk"
# そこまで対抗心を抱かなくても……
line = "そこまで対抗心を抱かなくても……"

[[dialogue]]
speaker = "unk"
# 同じ星騎士の仲間なんですし、
line = "同じ星騎士の仲間なんですし、"

[[dialogue]]
speaker = "マハムート"
# 「甘いわよ！　アナタ、新星寮と流星寮を見比べたことあるのかしら？」
line = "「甘いわよ！　アナタ、新星寮と流星寮を見比べたことあるのかしら？」"

[[dialogue]]
speaker = "マハムート"
# 「自宅から通っているから、気にしたことないでしょう？　付いて来なさい」
line = "「自宅から通っているから、気にしたことないでしょう？　付いて来なさい」"

[[dialogue]]
speaker = "マハムート"
# 「寮は校門の向かいにあって、まずこれが<ruby=ラルーナ>新星寮</ruby>──」
line = "「寮は校門の向かいにあって、まずこれが<ruby>新星寮<rt>ラルーナ</rt></ruby>──」"

[[dialogue]]
speaker = "unk"
# うん、普通
line = "うん、普通"

[[dialogue]]
speaker = "マハムート"
# 「そして、これがライバルの<ruby=イルソーレ>流星寮</ruby>よ！」
line = "「そして、これがライバルの<ruby>流星寮<rt>イルソーレ</rt></ruby>よ！」"

[[dialogue]]
speaker = "unk"
# って、どこ？
line = "って、どこ？"

[[dialogue]]
speaker = "マハムート"
# 「目を背けてはダメよ。校門の対面にある、そのリゾート高級ホテルのような建物こそが、流星寮なの」
line = "「目を背けてはダメよ。校門の対面にある、そのリゾート高級ホテルのような建物こそが、流星寮なの」"

[[dialogue]]
speaker = "unk"
# ……は？
line = "……は？"

[[dialogue]]
speaker = "マハムート"
# 「流星の元寮長に凄い資産家が居て資金援助しているとかで、新星寮と流星寮の間には、とんでもない設備格差があるのよ！」
line = "「流星の元寮長に凄い資産家が居て資金援助しているとかで、新星寮と流星寮の間には、とんでもない設備格差があるのよ！」"

[[dialogue]]
speaker = "マハムート"
# 「これで対抗心を抱かないとか、あり得ないわ……！」
line = "「これで対抗心を抱かないとか、あり得ないわ……！」"
