[[dialogue]]
speaker = "unk"
# 第３話,恋愛の副作用,P
line = "第３話,恋愛の副作用,P"

[[dialogue]]
speaker = "unk"
# ある日、俺が他の星徒会メンバーと共に書類仕事をしていると、アニマ先輩が訪ねて来て――
line = "ある日、俺が他の星徒会メンバーと共に書類仕事をしていると、アニマ先輩が訪ねて来て――"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「仕事中のところ、失礼するヨ」
line = "「仕事中のところ、失礼するヨ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あら、アニマ先輩、こんにちは！　ひょっとしてまた、新しい薬が完成したの？」
line = "「あら、アニマ先輩、こんにちは！　ひょっとしてまた、新しい薬が完成したの？」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「ああ。ヴィーナス、その通りダ♪」
line = "「ああ。ヴィーナス、その通りダ♪」"

[[dialogue]]
speaker = "マトイ"
# 「えっ、この間完成したって言ってたけど、また！？　アニマ先輩、このところ発明頻度がすごくないですか！？」
line = "「えっ、この間完成したって言ってたけど、また！？　アニマ先輩、このところ発明頻度がすごくないですか！？」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「ノヴァフォームに覚醒したおかげで、新たな能力『思考加速』を手に入れたからネ。研究スピードが上がって大助かりだヨ♪」
line = "「ノヴァフォームに覚醒したおかげで、新たな能力『思考加速』を手に入れたからネ。研究スピードが上がって大助かりだヨ♪」"

[[dialogue]]
speaker = "サーシャ"
# 「アニマちゃん、最近ノヴァフォームをよく着ているわよね～。通常フォームよりも星力の消耗が激しいはずなのに、すごいわ～」
line = "「アニマちゃん、最近ノヴァフォームをよく着ているわよね～。通常フォームよりも星力の消耗が激しいはずなのに、すごいわ～」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「フヒ♪　これは会長との絆――愛の証だからナ♪　色々と試しているんダ」
line = "「フヒ♪　これは会長との絆――愛の証だからナ♪　色々と試しているんダ」"

[[dialogue]]
speaker = "アナ"
# 「アニマ先輩が自ら率先してノヴァフォームを長時間維持する実験を行っているおかげで、わかったことも多い」
line = "「アニマ先輩が自ら率先してノヴァフォームを長時間維持する実験を行っているおかげで、わかったことも多い」"

[[dialogue]]
speaker = "アナ"
# 「どうやら戦闘用の星術さえ使わなければ、それなりにノヴァフォームの状態を維持することはできるようです」
line = "「どうやら戦闘用の星術さえ使わなければ、それなりにノヴァフォームの状態を維持することはできるようです」"

[[dialogue]]
speaker = "アナ"
# 「また、使い込んでいけばいずれ、通常戦闘服の出力がノヴァフォーム時のものへ近づいて行くみたいです。まあ、これは本当に長期的な話になりそうですが」
line = "「また、使い込んでいけばいずれ、通常戦闘服の出力がノヴァフォーム時のものへ近づいて行くみたいです。まあ、これは本当に長期的な話になりそうですが」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「メイプル曰く、絆のアルケインコードは潜在能力を覚醒させる力、らしいからネ」
line = "「メイプル曰く、絆のアルケインコードは潜在能力を覚醒させる力、らしいからネ」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「フヒ、アニマは星騎士としては天才ではないという自覚があったガ、まさかまだ先の可能性があったとは――」
line = "「フヒ、アニマは星騎士としては天才ではないという自覚があったガ、まさかまだ先の可能性があったとは――」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「これもまた、実験してみなければ結果はわからナイ、という例だナ。気づけたのは会長のおかげダ。感謝するヨ♪」
line = "「これもまた、実験してみなければ結果はわからナイ、という例だナ。気づけたのは会長のおかげダ。感謝するヨ♪」"

[[dialogue]]
speaker = "unk"
# いえいえ、俺はアニマ先輩の彼氏ですから
line = "いえいえ、俺はアニマ先輩の彼氏ですから"

[[dialogue]]
speaker = "サーシャ"
# 「あら～♪」
line = "「あら～♪」"

[[dialogue]]
speaker = "アナ"
# 「お熱いですね」
line = "「お熱いですね」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「おっと……コホン。さて、ノヴァフォームの話題になったところで、新薬の効果を発表しよう。名付けて――」
line = "「おっと……コホン。さて、ノヴァフォームの話題になったところで、新薬の効果を発表しよう。名付けて――」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「『ノヴァシンクロン』！　研究の結果、アニマ達がノヴァフォームに変身した際、会長の中にある魔王の力と共鳴して、より強力な力を発揮できているコトが判明してイルが――」
line = "「『ノヴァシンクロン』！　研究の結果、アニマ達がノヴァフォームに変身した際、会長の中にある魔王の力と共鳴して、より強力な力を発揮できているコトが判明してイルが――」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「ならば逆に、会長もノヴァフォームと共鳴するコトで、アニマ達の能力や技を使うことが可能なんじゃないか？　とアニマは閃いてネ」
line = "「ならば逆に、会長もノヴァフォームと共鳴するコトで、アニマ達の能力や技を使うことが可能なんじゃないか？　とアニマは閃いてネ」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「つまり、今この薬を会長が飲めば、アニマのノヴァフォームと同等の力を発揮できるはず、というわけダ♪」
line = "「つまり、今この薬を会長が飲めば、アニマのノヴァフォームと同等の力を発揮できるはず、というわけダ♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なにそれ面白そう～！」
line = "「なにそれ面白そう～！」"

[[dialogue]]
speaker = "マトイ"
# 「相変わらずのトンデモ強力効果で、にわかには信じがたいけど――」
line = "「相変わらずのトンデモ強力効果で、にわかには信じがたいけど――」"

[[dialogue]]
speaker = "unk"
# もちろん試しますよ
line = "もちろん試しますよ"

[[dialogue]]
speaker = "unk"
# 俺はアニマ先輩に向けて、グッと親指を立ててみせる。
line = "俺はアニマ先輩に向けて、グッと親指を立ててみせる。"

[[dialogue]]
speaker = "アナ"
# 「おお～」
line = "「おお～」"

[[dialogue]]
speaker = "マトイ"
# 「判断が早い！」
line = "「判断が早い！」"

[[dialogue]]
speaker = "サーシャ"
# 「愛の力ね～♪」
line = "「愛の力ね～♪」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「フヒ♪　なら、お願いするヨ、会長」
line = "「フヒ♪　なら、お願いするヨ、会長」"

[[dialogue]]
speaker = "unk"
# 今更迷うこともなく、アニマ先輩を信じている俺は薬を一気飲みする。相変わらず、飲みやすさまで考えてくれていて、色の割に意外と美味しい。
line = "今更迷うこともなく、アニマ先輩を信じている俺は薬を一気飲みする。相変わらず、飲みやすさまで考えてくれていて、色の割に意外と美味しい。"

[[dialogue]]
speaker = "unk"
# そして、飲み終わるや否や、効果はすぐに表れて――
line = "そして、飲み終わるや否や、効果はすぐに表れて――"

[[dialogue]]
speaker = "マトイ"
# 「か、会長が、アニマ先輩とまったく同じ形状のノヴァフォーム衣装に変身した！？」
line = "「か、会長が、アニマ先輩とまったく同じ形状のノヴァフォーム衣装に変身した！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「しかもいつもの副作用で、女の子の体に変身してるから似合っているわ！　可愛いじゃない♪」
line = "「しかもいつもの副作用で、女の子の体に変身してるから似合っているわ！　可愛いじゃない♪」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「おお～！　なるほど、アニマと共鳴した結果、戦闘服もアニマとペアルックに変化したというわけカ。面白イ♪」
line = "「おお～！　なるほど、アニマと共鳴した結果、戦闘服もアニマとペアルックに変化したというわけカ。面白イ♪」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「能力の方はどうカナ？」
line = "「能力の方はどうカナ？」"

[[dialogue]]
speaker = "unk"
# 俺は会長席に戻って、途中だった書類仕事を始めると――
line = "俺は会長席に戻って、途中だった書類仕事を始めると――"

[[dialogue]]
speaker = "unk"
# はっ！！！
line = "はっ！！！"

[[dialogue]]
speaker = "unk"
# 思考加速を発動して、高速で書類を処理して行く。
line = "思考加速を発動して、高速で書類を処理して行く。"

[[dialogue]]
speaker = "unk"
# そして、数分もかからない内に――
line = "そして、数分もかからない内に――"

[[dialogue]]
speaker = "マトイ"
# 「早っ！？　まだ結構な量があったはずなのに、もう終わったの！？」
line = "「早っ！？　まだ結構な量があったはずなのに、もう終わったの！？」"

[[dialogue]]
speaker = "サーシャ"
# 「どれどれ～？　あら！　すごいわ～♪　字も綺麗だし、内容も完璧よ～♪」
line = "「どれどれ～？　あら！　すごいわ～♪　字も綺麗だし、内容も完璧よ～♪」"

[[dialogue]]
speaker = "アナ"
# 「思考の高速化は、やはり汎用性が高くて、すごい能力です」
line = "「思考の高速化は、やはり汎用性が高くて、すごい能力です」"

[[dialogue]]
speaker = "ヴィーナス"
# 「頭脳チートね！」
line = "「頭脳チートね！」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「フヒ♪　どうやら実験は成功のようだナ♪」
line = "「フヒ♪　どうやら実験は成功のようだナ♪」"

[[dialogue]]
speaker = "unk"
# ハッ！？　アニマ先輩、気づいたんですけど
line = "ハッ！？　アニマ先輩、気づいたんですけど"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「ん？　どうしたんダ、会長？」
line = "「ん？　どうしたんダ、会長？」"

[[dialogue]]
speaker = "unk"
# ――先輩のノヴァフォームの胸ベルトって、ぴったりくっ付いて、ズレないようになってるんですね！
line = "――先輩のノヴァフォームの胸ベルトって、ぴったりくっ付いて、ズレないようになってるんですね！"

[[dialogue]]
speaker = "アナ"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「ああ、なるほど。会長は男だから、その辺りの仕組みを知らナイのか」
line = "「ああ、なるほど。会長は男だから、その辺りの仕組みを知らナイのか」"

[[dialogue]]
speaker = "サーシャ"
# 「私たちも戦闘服の時は、ズレないようになってるのよ～」
line = "「私たちも戦闘服の時は、ズレないようになってるのよ～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なんかよく分からないけど、不思議な力が働いてるのよ！　便利よね！」
line = "「なんかよく分からないけど、不思議な力が働いてるのよ！　便利よね！」"

[[dialogue]]
speaker = "マトイ"
# 「戦闘ですっかり着慣れちゃってるけど、水着フォームとか、際どい戦闘服もあるしね」
line = "「戦闘ですっかり着慣れちゃってるけど、水着フォームとか、際どい戦闘服もあるしね」"

[[dialogue]]
speaker = "アナ"
# 「そうですね」
line = "「そうですね」"

[[dialogue]]
speaker = "unk"
# 知らなかった！
line = "知らなかった！"

[[dialogue]]
speaker = "アナ"
# （水着フォームを持ってるのに、知らなかった……）
line = "（水着フォームを持ってるのに、知らなかった……）"

[[dialogue]]
speaker = "ヴィーナス"
# 「ねぇ、思ったんだけど！」
line = "「ねぇ、思ったんだけど！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「他のノヴァフォームとシンクロした場合、やっぱりクロトの戦闘服ってそれと同じ衣装に変わるのよね？　だったらせっかくだし、見てみたいわ！」
line = "「他のノヴァフォームとシンクロした場合、やっぱりクロトの戦闘服ってそれと同じ衣装に変わるのよね？　だったらせっかくだし、見てみたいわ！」"

[[dialogue]]
speaker = "マトイ"
# 「言われてみれば、確かに……！」
line = "「言われてみれば、確かに……！」"

[[dialogue]]
speaker = "サーシャ"
# 「なら、それぞれ変身して、試してみましょうか♪」
line = "「なら、それぞれ変身して、試してみましょうか♪」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「……むぅ」
line = "「……むぅ」"

[[dialogue]]
speaker = "unk"
# あれ、アニマ先輩……？
line = "あれ、アニマ先輩……？"

[[dialogue]]
speaker = "unk"
# ふと先輩を見ると、なにやら頬をぷく～っと膨らませていた。
line = "ふと先輩を見ると、なにやら頬をぷく～っと膨らませていた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「アニマ先輩、どうしたの、その顔？　なんかすごく可愛いわよ？」
line = "「アニマ先輩、どうしたの、その顔？　なんかすごく可愛いわよ？」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「ウム、理由はよくわからないのだガ……なんだか、会長が他の子とペアルックに変身するのを想像したら、思考がモヤモヤしてだナ？」
line = "「ウム、理由はよくわからないのだガ……なんだか、会長が他の子とペアルックに変身するのを想像したら、思考がモヤモヤしてだナ？」"

[[dialogue]]
speaker = "マトイ"
# 「えっ！？　それってもしかして……！？」
line = "「えっ！？　それってもしかして……！？」"

[[dialogue]]
speaker = "サーシャ"
# 「あら～<emoji=heart04>　アニマちゃんが可愛くて、お姉ちゃん同級生なのに、キュンキュンしてきちゃったわ～<emoji=heart04>」
line = "「あら～<emoji=heart04>　アニマちゃんが可愛くて、お姉ちゃん同級生なのに、キュンキュンしてきちゃったわ～<emoji=heart04>」"

[[dialogue]]
speaker = "アナ"
# 「アニマ先輩、なんだか最近、すごく女の子らしくなりましたね」
line = "「アニマ先輩、なんだか最近、すごく女の子らしくなりましたね」"

[[dialogue]]
speaker = "アナ"
# 「まさか会長と付き合い始めて、そんなデレデレの姿を見せるとは……」
line = "「まさか会長と付き合い始めて、そんなデレデレの姿を見せるとは……」"

[[dialogue]]
speaker = "unk"
# 俺はアニマ先輩の手を取ると、正面から目を見て言う。
line = "俺はアニマ先輩の手を取ると、正面から目を見て言う。"

[[dialogue]]
speaker = "unk"
# 俺の心はいつも、アニマ先輩と一緒ですから
line = "俺の心はいつも、アニマ先輩と一緒ですから"

[[dialogue]]
speaker = "unk"
# 大丈夫です。どれだけ衣装が変わっても
line = "大丈夫です。どれだけ衣装が変わっても"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「か、会長……<emoji=heart04>」
line = "「か、会長……<emoji=heart04>」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「ありがとう……アニマは嬉しイ♪　フヒ<emoji=heart04>」
line = "「ありがとう……アニマは嬉しイ♪　フヒ<emoji=heart04>」"

[[dialogue]]
speaker = "アナ"
# 「これは……バカップルですね」
line = "「これは……バカップルですね」"

[[dialogue]]
speaker = "サーシャ"
# 「恋愛の副作用といったところかしら♪　ふふっ♪」
line = "「恋愛の副作用といったところかしら♪　ふふっ♪」"

[[dialogue]]
speaker = "unk"
# 周りからそんな風に言われてしまうが、アニマ先輩を笑顔にする為なら、これくらいのことは恥ずかしくないと思える俺なのだった。
line = "周りからそんな風に言われてしまうが、アニマ先輩を笑顔にする為なら、これくらいのことは恥ずかしくないと思える俺なのだった。"
