[[dialogue]]
speaker = "unk"
# 第２話,ふわふわスイートスマイル,P
line = "第２話,ふわふわスイートスマイル,P"

[[dialogue]]
speaker = "unk"
# ある日の放課後、俺は蛍火と他愛のない雑談をしていた。
line = "ある日の放課後、俺は蛍火と他愛のない雑談をしていた。"

[[dialogue]]
speaker = "蛍火"
# 「師匠、そういえば最近、サランさんとお知り合いになったんですか？」
line = "「師匠、そういえば最近、サランさんとお知り合いになったんですか？」"

[[dialogue]]
speaker = "unk"
# 蛍火は学園生でありながら、カフェテリアの料理長とも言える立場にある、凄腕の料理人だ。
line = "蛍火は学園生でありながら、カフェテリアの料理長とも言える立場にある、凄腕の料理人だ。"

[[dialogue]]
speaker = "unk"
# サラン？　うん、この前カフェテリアで――
line = "サラン？　うん、この前カフェテリアで――"

[[dialogue]]
speaker = "蛍火"
# 「やはり友達になられたのですね。初対面でもすぐ仲良くなってしまうとは、さすが師匠です」
line = "「やはり友達になられたのですね。初対面でもすぐ仲良くなってしまうとは、さすが師匠です」"

[[dialogue]]
speaker = "サラン"
# 「あっ、見つけた～。会長ちゃ～ん♪」
line = "「あっ、見つけた～。会長ちゃ～ん♪」"

[[dialogue]]
speaker = "サラン"
# 「それに、蛍火ちゃんも～。そういえば、２人は友達だって言ってたね～」
line = "「それに、蛍火ちゃんも～。そういえば、２人は友達だって言ってたね～」"

[[dialogue]]
speaker = "蛍火"
# 「ええ。まぁ……」
line = "「ええ。まぁ……」"

[[dialogue]]
speaker = "unk"
# ちなみに、蛍火は緊張すると二重人格ばりに対応が素っ気なくなるが、あくまで緊張しているだけ。彼女と付き合いのある人間にとっては見慣れた反応である。
line = "ちなみに、蛍火は緊張すると二重人格ばりに対応が素っ気なくなるが、あくまで緊張しているだけ。彼女と付き合いのある人間にとっては見慣れた反応である。"

[[dialogue]]
speaker = "unk"
# 蛍火とサランも友達なのか？
line = "蛍火とサランも友達なのか？"

[[dialogue]]
speaker = "蛍火"
# 「いえ、サランさんはクラスメイトです。友達ではありません」
line = "「いえ、サランさんはクラスメイトです。友達ではありません」"

[[dialogue]]
speaker = "サラン"
# 「そうだよ～、蛍火ちゃんは友達じゃないよ～」
line = "「そうだよ～、蛍火ちゃんは友達じゃないよ～」"

[[dialogue]]
speaker = "蛍火"
# 「ええ、そうですよね……」
line = "「ええ、そうですよね……」"

[[dialogue]]
speaker = "サラン"
# 「蛍火ちゃんは、サランの親友だよ～♪」
line = "「蛍火ちゃんは、サランの親友だよ～♪」"

[[dialogue]]
speaker = "蛍火"
# 「え……」
line = "「え……」"

[[dialogue]]
speaker = "サラン"
# 「ね～♪　そうだよね～、蛍火ちゃん♪」
line = "「ね～♪　そうだよね～、蛍火ちゃん♪」"

[[dialogue]]
speaker = "蛍火"
# 「は……はいぃ～<emoji=heart04>　親友ですぅ～<emoji=heart04>」
line = "「は……はいぃ～<emoji=heart04>　親友ですぅ～<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 緊張モードの蛍火が一瞬でメロメロに！？
line = "緊張モードの蛍火が一瞬でメロメロに！？"

[[dialogue]]
speaker = "蛍火"
# 「その……サランさんのふわふわな笑顔を見てると、癒されてリラックスしてしまうんです……」
line = "「その……サランさんのふわふわな笑顔を見てると、癒されてリラックスしてしまうんです……」"

[[dialogue]]
speaker = "サラン"
# 「えへへ～、そうなんだ～。そういうの初めて聞けて、嬉しいかも～♪」
line = "「えへへ～、そうなんだ～。そういうの初めて聞けて、嬉しいかも～♪」"

[[dialogue]]
speaker = "蛍火"
# 「あ……す、すみません……面と向かってだと、恥ずかしくて……」
line = "「あ……す、すみません……面と向かってだと、恥ずかしくて……」"

[[dialogue]]
speaker = "サラン"
# 「そうだ、せっかくだから蛍火ちゃんも、お菓子食べる～？　ちょっといっぱい作り過ぎちゃったんだ～」
line = "「そうだ、せっかくだから蛍火ちゃんも、お菓子食べる～？　ちょっといっぱい作り過ぎちゃったんだ～」"

[[dialogue]]
speaker = "unk"
# お菓子？
line = "お菓子？"

[[dialogue]]
speaker = "サラン"
# 「サランね、お菓子作りが趣味なんだ～。それでね、この間助けてくれたお礼も兼ねて、会長ちゃんにお菓子渡そうと思って～」
line = "「サランね、お菓子作りが趣味なんだ～。それでね、この間助けてくれたお礼も兼ねて、会長ちゃんにお菓子渡そうと思って～」"

[[dialogue]]
speaker = "サラン"
# 「マシュマロチーズケーキ作ってみたの～。テーブルの上に置いて～……はい、どうぞ～♪」
line = "「マシュマロチーズケーキ作ってみたの～。テーブルの上に置いて～……はい、どうぞ～♪」"

[[dialogue]]
speaker = "unk"
# 凄い本格的なケーキだ……！
line = "凄い本格的なケーキだ……！"

[[dialogue]]
speaker = "蛍火"
# 「本格的なんてものじゃありませんよ、師匠。サランさんは……いえ、百聞は一見に如かずですね。いただきましょう」
line = "「本格的なんてものじゃありませんよ、師匠。サランさんは……いえ、百聞は一見に如かずですね。いただきましょう」"

[[dialogue]]
speaker = "サラン"
# 「は～い、召し上がれ～♪」
line = "「は～い、召し上がれ～♪」"

[[dialogue]]
speaker = "unk"
# 気付けば、大きなマシュマロチーズケーキは、消えるように全て食べ終わっていた。
line = "気付けば、大きなマシュマロチーズケーキは、消えるように全て食べ終わっていた。"

[[dialogue]]
speaker = "unk"
# 滅茶苦茶美味しかった……！
line = "滅茶苦茶美味しかった……！"

[[dialogue]]
speaker = "サラン"
# 「わ～い、会長ちゃんが笑顔になってくれて嬉しい～♪　サランも幸せでふわふわ～♪」
line = "「わ～い、会長ちゃんが笑顔になってくれて嬉しい～♪　サランも幸せでふわふわ～♪」"

[[dialogue]]
speaker = "蛍火"
# 「サランさん、ごちそうさまでした。また腕を上げましたね。これはきっと……師匠の為に作ったからでしょうか。今までで一番美味しかったです。思わず嫉妬する程に……」
line = "「サランさん、ごちそうさまでした。また腕を上げましたね。これはきっと……師匠の為に作ったからでしょうか。今までで一番美味しかったです。思わず嫉妬する程に……」"

[[dialogue]]
speaker = "サラン"
# 「ありがと～♪　サランも今回はよく出来たかもって思ってたんだ～」
line = "「ありがと～♪　サランも今回はよく出来たかもって思ってたんだ～」"

[[dialogue]]
speaker = "蛍火"
# 「師匠、実は料理人界隈では、サランさんはお菓子作りの天才と呼ばれているんです。その腕前は、名だたるパティシエや、美食家達が唸る程で……」
line = "「師匠、実は料理人界隈では、サランさんはお菓子作りの天才と呼ばれているんです。その腕前は、名だたるパティシエや、美食家達が唸る程で……」"

[[dialogue]]
speaker = "蛍火"
# 「私もお菓子は作りますが、未だサランさんに勝てたことはありません。将来はきっと、名を残すパティシエになるでしょうね」
line = "「私もお菓子は作りますが、未だサランさんに勝てたことはありません。将来はきっと、名を残すパティシエになるでしょうね」"

[[dialogue]]
speaker = "unk"
# 料理人の蛍火が、そこまで言うなんて……！
line = "料理人の蛍火が、そこまで言うなんて……！"

[[dialogue]]
speaker = "サラン"
# 「パティシエか～、何となくなれたらいいな～って思ってるけど……」
line = "「パティシエか～、何となくなれたらいいな～って思ってるけど……」"

[[dialogue]]
speaker = "サラン"
# 「将来のことはともかく、サラン、皆が美味しいって言って笑ってくれるの好きなんだ～♪」
line = "「将来のことはともかく、サラン、皆が美味しいって言って笑ってくれるの好きなんだ～♪」"

[[dialogue]]
speaker = "サラン"
# 「サラン、昔からドジだから、皆に迷惑かけてて～」
line = "「サラン、昔からドジだから、皆に迷惑かけてて～」"

[[dialogue]]
speaker = "サラン"
# 「でも、得意な食のことなら役に立てて、皆が喜んでくれるんだ～」
line = "「でも、得意な食のことなら役に立てて、皆が喜んでくれるんだ～」"

[[dialogue]]
speaker = "サラン"
# 「サランもそれを見てると、ふわふわ～って幸せな気持ちになれるの～♪」
line = "「サランもそれを見てると、ふわふわ～って幸せな気持ちになれるの～♪」"

[[dialogue]]
speaker = "unk"
# サランなら、良いパティシエになれそうだな
line = "サランなら、良いパティシエになれそうだな"

[[dialogue]]
speaker = "蛍火"
# 「ええ、私もそう思います」
line = "「ええ、私もそう思います」"

[[dialogue]]
speaker = "サラン"
# 「そうかな～？　えへへ……♪」
line = "「そうかな～？　えへへ……♪」"

[[dialogue]]
speaker = "unk"
# そう言ってふわふわな笑顔を浮かべる彼女を見ていると、こちらも自然と笑顔になってしまうのだった。
line = "そう言ってふわふわな笑顔を浮かべる彼女を見ていると、こちらも自然と笑顔になってしまうのだった。"
