[[dialogue]]
speaker = "unk"
# 第４話,手作りカーネーション,P
line = "第４話,手作りカーネーション,P"

[[dialogue]]
speaker = "シャロン"
# 「みなさん、フラワーペーパーの準備はできましたか？　作り方がわからなかったら、近くのお姉さんたちに聞いてくださいね！」
line = "「みなさん、フラワーペーパーの準備はできましたか？　作り方がわからなかったら、近くのお姉さんたちに聞いてくださいね！」"

[[dialogue]]
speaker = "シャロン"
# 「あと、はさみやホッチキスを使いますから、怪我にだけは気を付けてくださーい！」
line = "「あと、はさみやホッチキスを使いますから、怪我にだけは気を付けてくださーい！」"

[[dialogue]]
speaker = "女の子"
# 「はーい！」
line = "「はーい！」"

[[dialogue]]
speaker = "シャロン"
# 「ふぅっ。会長さま、本日はありがとうございます。カフェテリアのスペースを貸していただき、助かりました」
line = "「ふぅっ。会長さま、本日はありがとうございます。カフェテリアのスペースを貸していただき、助かりました」"

[[dialogue]]
speaker = "シャロン"
# 「おかげさまでつつがなく、こども会のボランティア活動を行えそうです！」
line = "「おかげさまでつつがなく、こども会のボランティア活動を行えそうです！」"

[[dialogue]]
speaker = "シャロン"
# 「今年は例年以上にこども会の参加者が増えまして……開催場所に困っていたんですよ」
line = "「今年は例年以上にこども会の参加者が増えまして……開催場所に困っていたんですよ」"

[[dialogue]]
speaker = "シャロン"
# 「特に今日みたいに工作をする日は、広いお部屋とテーブルがたくさん必要ですからね」
line = "「特に今日みたいに工作をする日は、広いお部屋とテーブルがたくさん必要ですからね」"

[[dialogue]]
speaker = "シャロン"
# 「ん……どうかしましたか、会長さま？」
line = "「ん……どうかしましたか、会長さま？」"

[[dialogue]]
speaker = "unk"
# 俺にも作り方を教えてくれる？
line = "俺にも作り方を教えてくれる？"

[[dialogue]]
speaker = "シャロン"
# 「あ、そうですよね。こどもたちに作り方を聞かれた時に困りますものね」
line = "「あ、そうですよね。こどもたちに作り方を聞かれた時に困りますものね」"

[[dialogue]]
speaker = "シャロン"
# 「意外と簡単なんですよ。まずはフラワーペーパーを用意して、折り目を付けます」
line = "「意外と簡単なんですよ。まずはフラワーペーパーを用意して、折り目を付けます」"

[[dialogue]]
speaker = "シャロン"
# 「そのまま数枚重ね合わせて、じゃばら折りにした後に切れ目を入れて──」
line = "「そのまま数枚重ね合わせて、じゃばら折りにした後に切れ目を入れて──」"

[[dialogue]]
speaker = "シャロン"
# 「……と、こんな感じです！　いかがでしょう、手作りですが本物のように見えませんか？」
line = "「……と、こんな感じです！　いかがでしょう、手作りですが本物のように見えませんか？」"

[[dialogue]]
speaker = "unk"
# これなら俺にもできそうだ
line = "これなら俺にもできそうだ"

[[dialogue]]
speaker = "シャロン"
# 「はい！　折り目をつけるところから難しいと思う子もおりますので、ぜひフォローお願いします！」
line = "「はい！　折り目をつけるところから難しいと思う子もおりますので、ぜひフォローお願いします！」"

[[dialogue]]
speaker = "シャロン"
# 「私、毎年のこの時期が大好きなんです。こどもたちが大好きなお母さまのためにお花を作る姿は微笑ましいですし……」
line = "「私、毎年のこの時期が大好きなんです。こどもたちが大好きなお母さまのためにお花を作る姿は微笑ましいですし……」"

[[dialogue]]
speaker = "シャロン"
# 「受け取ったお母さまもとても喜んでくださいますから」
line = "「受け取ったお母さまもとても喜んでくださいますから」"

[[dialogue]]
speaker = "unk"
# 材料って余ったりするのかな？
line = "材料って余ったりするのかな？"

[[dialogue]]
speaker = "シャロン"
# 「そうですね。失敗しちゃう子も多いので、フラワーペーパーは多めに用意してあります」
line = "「そうですね。失敗しちゃう子も多いので、フラワーペーパーは多めに用意してあります」"

[[dialogue]]
speaker = "シャロン"
# 「ですから……はい。会長さまが何枚か持っていかれても大丈夫ですよ？」
line = "「ですから……はい。会長さまが何枚か持っていかれても大丈夫ですよ？」"

[[dialogue]]
speaker = "シャロン"
# 「ふふ♪　しっかり心を込めて作って差し上げてくださいね」
line = "「ふふ♪　しっかり心を込めて作って差し上げてくださいね」"

[[dialogue]]
speaker = "シャロン"
# 「──なにせ今日は『母の日』ですから」
line = "「──なにせ今日は『母の日』ですから」"

[[dialogue]]
speaker = "リノ"
# 「あっ、お帰りなさいクロト～。今日はちょっと遅かったのね？」
line = "「あっ、お帰りなさいクロト～。今日はちょっと遅かったのね？」"

[[dialogue]]
speaker = "リノ"
# 「大聖堂のボランティアをお手伝いしてたんだっけ？　こども会の子たちとは仲良くできた？」
line = "「大聖堂のボランティアをお手伝いしてたんだっけ？　こども会の子たちとは仲良くできた？」"

[[dialogue]]
speaker = "リノ"
# 「そう、なら良かった♪　晩御飯作ってあるから一緒に食べましょ。手洗いうがい、してきなさいね」
line = "「そう、なら良かった♪　晩御飯作ってあるから一緒に食べましょ。手洗いうがい、してきなさいね」"

[[dialogue]]
speaker = "unk"
# 母さん、これプレゼント
line = "母さん、これプレゼント"

[[dialogue]]
speaker = "リノ"
# 「んー？　どうしたの、藪から棒に──」
line = "「んー？　どうしたの、藪から棒に──」"

[[dialogue]]
speaker = "リノ"
# 「あっ……そっかぁ。今日は母の日だったっけ。すっかり忘れてたわ」
line = "「あっ……そっかぁ。今日は母の日だったっけ。すっかり忘れてたわ」"

[[dialogue]]
speaker = "リノ"
# 「星徒会で忙しいでしょうに……わざわざありがとうね、クロト！」
line = "「星徒会で忙しいでしょうに……わざわざありがとうね、クロト！」"

[[dialogue]]
speaker = "リノ"
# 「ラッピングされてる贈り物なんていつぶりかしら。それに箱に付いてるカーネーションの造花、素敵ね！」
line = "「ラッピングされてる贈り物なんていつぶりかしら。それに箱に付いてるカーネーションの造花、素敵ね！」"

[[dialogue]]
speaker = "リノ"
# 「……えっ？　このカーネーション、クロトの手作りなの！？」
line = "「……えっ？　このカーネーション、クロトの手作りなの！？」"

[[dialogue]]
speaker = "リノ"
# 「も～っ……！　あ～～～っ♪　うちの息子が可愛すぎる！　箱のプレゼントも、開けて見てもいい？」
line = "「も～っ……！　あ～～～っ♪　うちの息子が可愛すぎる！　箱のプレゼントも、開けて見てもいい？」"

[[dialogue]]
speaker = "リノ"
# 「わぁ……素敵な髪留めね。派手すぎないから、お仕事にも付けていけそう～♪」
line = "「わぁ……素敵な髪留めね。派手すぎないから、お仕事にも付けていけそう～♪」"

[[dialogue]]
speaker = "リノ"
# 「そうね。お仕事する時は髪をまとめる時も多いから。ふふ、ありがとうね、クロト♪」
line = "「そうね。お仕事する時は髪をまとめる時も多いから。ふふ、ありがとうね、クロト♪」"

[[dialogue]]
speaker = "リノ"
# 「でもこれ、結構いいところのブランドじゃない？　あんまり無理しなくていいのよ」
line = "「でもこれ、結構いいところのブランドじゃない？　あんまり無理しなくていいのよ」"

[[dialogue]]
speaker = "リノ"
# 「アルバイトで貯めたお金は、クロトの使いたいことに使えばいいんだから」
line = "「アルバイトで貯めたお金は、クロトの使いたいことに使えばいいんだから」"

[[dialogue]]
speaker = "unk"
# これが俺の使いたいことだから
line = "これが俺の使いたいことだから"

[[dialogue]]
speaker = "リノ"
# 「……そっか。うん、ありがとう。ずーっと大事にするわね！」
line = "「……そっか。うん、ありがとう。ずーっと大事にするわね！」"

[[dialogue]]
speaker = "リノ"
# 「お母さんもクロトには感謝してるわ。あなたと一緒に暮らしてると、いつも楽しいから」
line = "「お母さんもクロトには感謝してるわ。あなたと一緒に暮らしてると、いつも楽しいから」"

[[dialogue]]
speaker = "リノ"
# 「お母さんの息子でいてくれて、ありがとうね」
line = "「お母さんの息子でいてくれて、ありがとうね」"

[[dialogue]]
speaker = "リノ"
# 「……って、ご飯の前にしんみりしちゃったわね。ほら、手洗いうがい、ちゃーんとしてきなさい」
line = "「……って、ご飯の前にしんみりしちゃったわね。ほら、手洗いうがい、ちゃーんとしてきなさい」"

[[dialogue]]
speaker = "リノ"
# 「今日はクロトの好きなものばかり作ってあるからね。お腹い～っぱい食べなきゃだめよ？」
line = "「今日はクロトの好きなものばかり作ってあるからね。お腹い～っぱい食べなきゃだめよ？」"

[[dialogue]]
speaker = "unk"
# 母親への感謝を伝えるタイミングって、いっぱいあるようであまりないものだ。
line = "母親への感謝を伝えるタイミングって、いっぱいあるようであまりないものだ。"

[[dialogue]]
speaker = "unk"
# 俺を育てて、支えて、愛してくれる母さんに少しでも感謝の気持ちを伝えられたのなら嬉しい。
line = "俺を育てて、支えて、愛してくれる母さんに少しでも感謝の気持ちを伝えられたのなら嬉しい。"

[[dialogue]]
speaker = "unk"
# ……俺と母さんの血が繋がっていないだろうこととか、最近薄っすらとわかりはじめてきた、母さんが昔に所属していた『組織』のこととか。
line = "……俺と母さんの血が繋がっていないだろうこととか、最近薄っすらとわかりはじめてきた、母さんが昔に所属していた『組織』のこととか。"

[[dialogue]]
speaker = "unk"
# 本当はこの機会に腹を割って話してみようかとも思っていたのだけれど──
line = "本当はこの機会に腹を割って話してみようかとも思っていたのだけれど──"

[[dialogue]]
speaker = "リノ"
# 「クロトー？　髪留め、さっそく付けてみたけど～。どうかしら♪　似合う？」
line = "「クロトー？　髪留め、さっそく付けてみたけど～。どうかしら♪　似合う？」"

[[dialogue]]
speaker = "unk"
# もうちょっとだけ、「普通の幸せな親子」で居続けたくて……
line = "もうちょっとだけ、「普通の幸せな親子」で居続けたくて……"

[[dialogue]]
speaker = "unk"
# （自分から打ち明けるタイミング伺ってる）
line = "（自分から打ち明けるタイミング伺ってる）"

[[dialogue]]
speaker = "unk"
# （母さんもきっと……）
line = "（母さんもきっと……）"

[[dialogue]]
speaker = "unk"
# 用意周到な母さんのこと。自分から切り出さないということは、今はまだ『その時』ではないのかもしれない。
line = "用意周到な母さんのこと。自分から切り出さないということは、今はまだ『その時』ではないのかもしれない。"

[[dialogue]]
speaker = "unk"
# 俺は胸の中でそう言い訳をして、そっと親子の真実に触れる日の予定を後ろに倒すのだった。
line = "俺は胸の中でそう言い訳をして、そっと親子の真実に触れる日の予定を後ろに倒すのだった。"
