[[dialogue]]
speaker = "unk"
# 第３話,探偵と書記,P
line = "第３話,探偵と書記,P"

[[dialogue]]
speaker = "unk"
# ジュエリーとの関わりが増える内に、彼女は新星の星徒会メンバーとも仲良くなっていた。
line = "ジュエリーとの関わりが増える内に、彼女は新星の星徒会メンバーとも仲良くなっていた。"

[[dialogue]]
speaker = "マトイ"
# 「――そうなんだ。面白かったならよかった♪　探偵のジュエリーが観たらどう思うのか、気になってたんだよね」
line = "「――そうなんだ。面白かったならよかった♪　探偵のジュエリーが観たらどう思うのか、気になってたんだよね」"

[[dialogue]]
speaker = "ジュエリー"
# 「ああ、実によく考えられたトリックだったよ。人間ドラマも面白かった。ほかにもオススメの映画があれば、ぜひ教えてもらえるとありがたい」
line = "「ああ、実によく考えられたトリックだったよ。人間ドラマも面白かった。ほかにもオススメの映画があれば、ぜひ教えてもらえるとありがたい」"

[[dialogue]]
speaker = "ジュエリー"
# 「――さて、話もひと段落したところで……マトイさん。ズバリ批評しよう」
line = "「――さて、話もひと段落したところで……マトイさん。ズバリ批評しよう」"

[[dialogue]]
speaker = "マトイ"
# 「えっ、何？　どうしたの？　映画の話？」
line = "「えっ、何？　どうしたの？　映画の話？」"

[[dialogue]]
speaker = "ジュエリー"
# 「キミ、少し太ったかい？」
line = "「キミ、少し太ったかい？」"

[[dialogue]]
speaker = "マトイ"
# 「ファッ！？」
line = "「ファッ！？」"

[[dialogue]]
speaker = "ジュエリー"
# 「いやなに、キミの外見に、些細な違和感を覚えてね。それが何なのかとマトイさんの思考をトレースしていったところ、１つの話題を思い出したのさ」
line = "「いやなに、キミの外見に、些細な違和感を覚えてね。それが何なのかとマトイさんの思考をトレースしていったところ、１つの話題を思い出したのさ」"

[[dialogue]]
speaker = "ジュエリー"
# 「キミが先日、学園の近くに新しいケーキ屋ができて、そこのケーキがすごく美味しいと話していただろう？　おそらくキミはそこに頻繁に通った結果――」
line = "「キミが先日、学園の近くに新しいケーキ屋ができて、そこのケーキがすごく美味しいと話していただろう？　おそらくキミはそこに頻繁に通った結果――」"

[[dialogue]]
speaker = "マトイ"
# 「ちょっ、ちょっと待って！　合ってるけど、ストォーーーップ！」
line = "「ちょっ、ちょっと待って！　合ってるけど、ストォーーーップ！」"

[[dialogue]]
speaker = "マトイ"
# 「ふ、太ったか、太ってないかで言えば、確かに太ったけども！　男子である会長がいる前で、それを言うかな普通！？」
line = "「ふ、太ったか、太ってないかで言えば、確かに太ったけども！　男子である会長がいる前で、それを言うかな普通！？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふむ……良かれと思っての指摘だったのだが……」
line = "「ふむ……良かれと思っての指摘だったのだが……」"

[[dialogue]]
speaker = "マトイ"
# 「よくないよ！？　普通に恥ずかしいから！」
line = "「よくないよ！？　普通に恥ずかしいから！」"

[[dialogue]]
speaker = "ジュエリー"
# 「それは失礼した。今のキミの外見なら、むしろ男性にモテる範疇だと思っていたのでね」
line = "「それは失礼した。今のキミの外見なら、むしろ男性にモテる範疇だと思っていたのでね」"

[[dialogue]]
speaker = "ジュエリー"
# 「しかしこのままだと、体重が増え続ける可能性もある。ならば今の内にアドバイスをして、解決すべきだろうと考えたんだ」
line = "「しかしこのままだと、体重が増え続ける可能性もある。ならば今の内にアドバイスをして、解決すべきだろうと考えたんだ」"

[[dialogue]]
speaker = "マトイ"
# 「へ？　も、モテる？　そうなの？　会長も……今くらいの体型が好みだったり？」
line = "「へ？　も、モテる？　そうなの？　会長も……今くらいの体型が好みだったり？」"

[[dialogue]]
speaker = "unk"
# 俺は全然違いに気づかなかった。それに――
line = "俺は全然違いに気づかなかった。それに――"

[[dialogue]]
speaker = "マトイ"
# 「……少しふっくらしているくらいの方が、男にはモテる？　そ、そうなんだ……！」
line = "「……少しふっくらしているくらいの方が、男にはモテる？　そ、そうなんだ……！」"

[[dialogue]]
speaker = "マトイ"
# 「５キロくらい体重増えても、普通だったんだ……！　よかった！」
line = "「５キロくらい体重増えても、普通だったんだ……！　よかった！」"

[[dialogue]]
speaker = "ジュエリー"
# 「すまない、訂正しよう。思ったより増えていたね」
line = "「すまない、訂正しよう。思ったより増えていたね」"

[[dialogue]]
speaker = "マトイ"
# 「なんで急に２人とも目をそらしたのかな！？」
line = "「なんで急に２人とも目をそらしたのかな！？」"

[[dialogue]]
speaker = "マトイ"
# 「うわあぁぁぁん！　調子に乗って、会長に太り具合を暴露しちゃったよぉぉ！　恥ずかしい……っ！」
line = "「うわあぁぁぁん！　調子に乗って、会長に太り具合を暴露しちゃったよぉぉ！　恥ずかしい……っ！」"

[[dialogue]]
speaker = "ジュエリー"
# 「安心したまえ、マトイさん。まだちょっと頬の輪郭が丸くなったくらいだ。気にする程じゃない」
line = "「安心したまえ、マトイさん。まだちょっと頬の輪郭が丸くなったくらいだ。気にする程じゃない」"

[[dialogue]]
speaker = "マトイ"
# 「いや気になるんだけど！？　もう鏡怖くて見れないよ！？」
line = "「いや気になるんだけど！？　もう鏡怖くて見れないよ！？」"

[[dialogue]]
speaker = "ジュエリー"
# 「まあ、落ち着きたまえ。私は友人であるキミに、アドバイスをするつもりだったんだ。今から言うことを実践すれば、必ず元の体重に戻れるはずさ」
line = "「まあ、落ち着きたまえ。私は友人であるキミに、アドバイスをするつもりだったんだ。今から言うことを実践すれば、必ず元の体重に戻れるはずさ」"

[[dialogue]]
speaker = "マトイ"
# 「ほ、本当……！？」
line = "「ほ、本当……！？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ああ、本当だとも。キミももしかしたら、私の外見に変化を感じたことがあるかもしれないが……」
line = "「ああ、本当だとも。キミももしかしたら、私の外見に変化を感じたことがあるかもしれないが……」"

[[dialogue]]
speaker = "ジュエリー"
# 「普段ズボラな私も、最近は女として身だしなみを意識するようになったんだ。友人からも、可愛くなったと褒められる程だ」
line = "「普段ズボラな私も、最近は女として身だしなみを意識するようになったんだ。友人からも、可愛くなったと褒められる程だ」"

[[dialogue]]
speaker = "ジュエリー"
# 「その理由を明解に換言するならば――ズバリ、我が助手の存在だ」
line = "「その理由を明解に換言するならば――ズバリ、我が助手の存在だ」"

[[dialogue]]
speaker = "マトイ"
# 「会長のおかげってこと……？」
line = "「会長のおかげってこと……？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ああ、その通り。助手がズボラな私を見かねて、たびたび部屋の掃除にきてくれたり、食事を作ってくれたりしてね――」
line = "「ああ、その通り。助手がズボラな私を見かねて、たびたび部屋の掃除にきてくれたり、食事を作ってくれたりしてね――」"

[[dialogue]]
speaker = "ジュエリー"
# 「それだけじゃなく、私の寝起きが弱いと知ると、毎朝起こしにきてくれるようになったんだ」
line = "「それだけじゃなく、私の寝起きが弱いと知ると、毎朝起こしにきてくれるようになったんだ」"

[[dialogue]]
speaker = "ジュエリー"
# 「寝ぼけている私の髪を綺麗に梳いたり、服装の乱れを直してくれたりと、身だしなみの細かなチェックを行ってくれてね」
line = "「寝ぼけている私の髪を綺麗に梳いたり、服装の乱れを直してくれたりと、身だしなみの細かなチェックを行ってくれてね」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふふっ、おかげで私は、今も自信を持って可愛いと自負することができるわけだ」
line = "「ふふっ、おかげで私は、今も自信を持って可愛いと自負することができるわけだ」"

[[dialogue]]
speaker = "マトイ"
# 「ノロケかな！？　というか、会長！　そこまでやってあげてるの！？」
line = "「ノロケかな！？　というか、会長！　そこまでやってあげてるの！？」"

[[dialogue]]
speaker = "unk"
# なんか放っておけなくて、つい……
line = "なんか放っておけなくて、つい……"

[[dialogue]]
speaker = "ジュエリー"
# 「ちなみに私はマトイさんとは逆に、思考の世界へ旅立っていると食事をおろそかにしがちでね。体型が細すぎるくらいだったんだが……」
line = "「ちなみに私はマトイさんとは逆に、思考の世界へ旅立っていると食事をおろそかにしがちでね。体型が細すぎるくらいだったんだが……」"

[[dialogue]]
speaker = "ジュエリー"
# 「最近は、助手の作ってくれる料理が美味しくて、少し太ってしまった。ふふっ……幸せ太りとはこのことを言うのかな？」
line = "「最近は、助手の作ってくれる料理が美味しくて、少し太ってしまった。ふふっ……幸せ太りとはこのことを言うのかな？」"

[[dialogue]]
speaker = "マトイ"
# 「いや太ってんじゃん！　……痩せられるって話じゃなかったの？　ここまで完全に、ただのノロケ話なんだけど」
line = "「いや太ってんじゃん！　……痩せられるって話じゃなかったの？　ここまで完全に、ただのノロケ話なんだけど」"

[[dialogue]]
speaker = "ジュエリー"
# 「おっとすまない。助手の自慢したさに、余計なことまで口走ってしまったが――」
line = "「おっとすまない。助手の自慢したさに、余計なことまで口走ってしまったが――」"

[[dialogue]]
speaker = "ジュエリー"
# 「伝えたかった大事なポイントとしては、『異性の目があると意識が変わる』ということだ」
line = "「伝えたかった大事なポイントとしては、『異性の目があると意識が変わる』ということだ」"

[[dialogue]]
speaker = "ジュエリー"
# 「つまりマトイさんも、私が助手に私生活を管理してもらっているように、体重管理を手伝ってもらえばいい」
line = "「つまりマトイさんも、私が助手に私生活を管理してもらっているように、体重管理を手伝ってもらえばいい」"

[[dialogue]]
speaker = "マトイ"
# 「えぇっ！？　ど、どういうこと……！？」
line = "「えぇっ！？　ど、どういうこと……！？」"

[[dialogue]]
speaker = "ジュエリー"
# 「簡単なことだ。星徒会室に体重計を置いて、毎日助手に体重を記録してもらえばいい」
line = "「簡単なことだ。星徒会室に体重計を置いて、毎日助手に体重を記録してもらえばいい」"

[[dialogue]]
speaker = "ジュエリー"
# 「なに、特別なダイエットをする必要はない。毎日ただ、体重を見せるだけだ。ヒトと言う生き物はそれだけで、普段のちょっとした行いに変化があるものさ」
line = "「なに、特別なダイエットをする必要はない。毎日ただ、体重を見せるだけだ。ヒトと言う生き物はそれだけで、普段のちょっとした行いに変化があるものさ」"

[[dialogue]]
speaker = "マトイ"
# 「それ、私がめちゃくちゃ恥ずかしいだけなんだけど！？」
line = "「それ、私がめちゃくちゃ恥ずかしいだけなんだけど！？」"

[[dialogue]]
speaker = "unk"
# と言いつつも、後日、ジュエリーのアドバイスを普通に実行したマトイは、何だかんだでダイエットに成功していた。
line = "と言いつつも、後日、ジュエリーのアドバイスを普通に実行したマトイは、何だかんだでダイエットに成功していた。"
