[[dialogue]]
speaker = "unk"
# 第３話,アポロの様子が……？,P
line = "第３話,アポロの様子が……？,P"

[[dialogue]]
speaker = "unk"
# とある日の放課後──フィオナが新星星徒会室を訪ねてきた。
line = "とある日の放課後──フィオナが新星星徒会室を訪ねてきた。"

[[dialogue]]
speaker = "unk"
# アポロの様子がおかしい？
line = "アポロの様子がおかしい？"

[[dialogue]]
speaker = "フィオナ"
# 「はい、そうなんです。数日前から私に何かを隠しているみたいで……」
line = "「はい、そうなんです。数日前から私に何かを隠しているみたいで……」"

[[dialogue]]
speaker = "フィオナ"
# 「つい昨日もこんなことが──」
line = "「つい昨日もこんなことが──」"

[[dialogue]]
speaker = "フィオナ"
# 「姉さん。今日のおやつの時間はとっておきのものが用意できていますよ」
line = "「姉さん。今日のおやつの時間はとっておきのものが用意できていますよ」"

[[dialogue]]
speaker = "アポロ"
# 「……うん」
line = "「……うん」"

[[dialogue]]
speaker = "フィオナ"
# 「見てください。あの桜十路家の運営するパティスリーから購入したケーキです！　大人気でなかなか手に入らないものなんですよ！」
line = "「見てください。あの桜十路家の運営するパティスリーから購入したケーキです！　大人気でなかなか手に入らないものなんですよ！」"

[[dialogue]]
speaker = "フィオナ"
# 「もうすぐキリカがお茶を持ってきますから、３人で一緒に食べましょう！」
line = "「もうすぐキリカがお茶を持ってきますから、３人で一緒に食べましょう！」"

[[dialogue]]
speaker = "アポロ"
# 「あ……あたしはいい。キリカと２人で食べてくれ……」
line = "「あ……あたしはいい。キリカと２人で食べてくれ……」"

[[dialogue]]
speaker = "フィオナ"
# 「え──ええっ？　ね、姉さん……！？」
line = "「え──ええっ？　ね、姉さん……！？」"

[[dialogue]]
speaker = "フィオナ"
# 「どう考えても妙なんです。姉さん、甘い物が大好きなのに……ここのところおやつの時間に渋い顔をすることが多くて」
line = "「どう考えても妙なんです。姉さん、甘い物が大好きなのに……ここのところおやつの時間に渋い顔をすることが多くて」"

[[dialogue]]
speaker = "unk"
# お腹がいっぱい、とかじゃ？
line = "お腹がいっぱい、とかじゃ？"

[[dialogue]]
speaker = "unk"
# お菓子の盗み食いでもして
line = "お菓子の盗み食いでもして"

[[dialogue]]
speaker = "フィオナ"
# 「いいえ！　私もそれを疑って、備蓄してある流星ライダーグミを確認したのですが、数は減っていませんでした……！」
line = "「いいえ！　私もそれを疑って、備蓄してある流星ライダーグミを確認したのですが、数は減っていませんでした……！」"

[[dialogue]]
speaker = "フィオナ"
# 「姉さん、どこか具合でも悪いんでしょうか？　目が覚めてから、グミは最低１日に３袋は消えていたのに……！」
line = "「姉さん、どこか具合でも悪いんでしょうか？　目が覚めてから、グミは最低１日に３袋は消えていたのに……！」"

[[dialogue]]
speaker = "フィオナ"
# 「どうかしたんですかと聞いても『なんでもない』の一点張りで……私、心配で心配で……！」
line = "「どうかしたんですかと聞いても『なんでもない』の一点張りで……私、心配で心配で……！」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長、一緒に姉さんに会っていただけませんか？　妹の私ではダメでも、緋宮会長なら話してくれるかもしれません……！」
line = "「緋宮会長、一緒に姉さんに会っていただけませんか？　妹の私ではダメでも、緋宮会長なら話してくれるかもしれません……！」"

[[dialogue]]
speaker = "unk"
# じゃあ今から一緒に行こうか
line = "じゃあ今から一緒に行こうか"

[[dialogue]]
speaker = "unk"
# わかった
line = "わかった"

[[dialogue]]
speaker = "フィオナ"
# 「ありがとうございます！　では早速──」
line = "「ありがとうございます！　では早速──」"

[[dialogue]]
speaker = "アポロ"
# 「──で、魔王を連れてきたと……」
line = "「──で、魔王を連れてきたと……」"

[[dialogue]]
speaker = "フィオナ"
# 「姉さん。何か困っていることがあるのでしたら、相談してください」
line = "「姉さん。何か困っていることがあるのでしたら、相談してください」"

[[dialogue]]
speaker = "アポロ"
# 「…………魔王になら、言ってもいいかもしれない。フィオナ、お前はダメだ。お前にはあまり心配をかけたくない……」
line = "「…………魔王になら、言ってもいいかもしれない。フィオナ、お前はダメだ。お前にはあまり心配をかけたくない……」"

[[dialogue]]
speaker = "フィオナ"
# 「……っ！　わ、わかりました。では、私は席を外します……緋宮会長、よろしくお願いします……！」
line = "「……っ！　わ、わかりました。では、私は席を外します……緋宮会長、よろしくお願いします……！」"

[[dialogue]]
speaker = "アポロ"
# 「なあ魔王。あたしはどうすればいいんだろう……？」
line = "「なあ魔王。あたしはどうすればいいんだろう……？」"

[[dialogue]]
speaker = "unk"
# 俺はいつでもきみの味方だよ
line = "俺はいつでもきみの味方だよ"

[[dialogue]]
speaker = "unk"
# アポロが困ってるなら
line = "アポロが困ってるなら"

[[dialogue]]
speaker = "アポロ"
# 「うん……わかった。お前はあたしの味方だよな。味方でいてくれるよな……？」
line = "「うん……わかった。お前はあたしの味方だよな。味方でいてくれるよな……？」"

[[dialogue]]
speaker = "アポロ"
# 「なら──言おう。実はな……」
line = "「なら──言おう。実はな……」"

[[dialogue]]
speaker = "アポロ"
# 「奥歯が痛いんだ……！　触ると、こう……ぐらぐら揺れるし……き、きっと虫歯だ……！」
line = "「奥歯が痛いんだ……！　触ると、こう……ぐらぐら揺れるし……き、きっと虫歯だ……！」"

[[dialogue]]
speaker = "アポロ"
# 「やっぱり原因はお菓子の食べすぎか？　こっそりグミを盗み食いした罰が当たったのか！？」
line = "「やっぱり原因はお菓子の食べすぎか？　こっそりグミを盗み食いした罰が当たったのか！？」"

[[dialogue]]
speaker = "アポロ"
# 「頼む。キリカやフィオナにバレたら……絶対に歯医者に引きずって行かれてしまう……」
line = "「頼む。キリカやフィオナにバレたら……絶対に歯医者に引きずって行かれてしまう……」"

[[dialogue]]
speaker = "アポロ"
# 「魔王……助けてくれ……！！」
line = "「魔王……助けてくれ……！！」"

[[dialogue]]
speaker = "unk"
# アポロの必死の懇願に、俺は──
line = "アポロの必死の懇願に、俺は──"

[[dialogue]]
speaker = "アポロ"
# 「裏切者ーーー！！　なぜこの２人を呼んだーーー！！　離せ、離せーっ！！」
line = "「裏切者ーーー！！　なぜこの２人を呼んだーーー！！　離せ、離せーっ！！」"

[[dialogue]]
speaker = "フィオナ"
# 「姉さん！　まったくもう……私がどれだけ心配したと……！」
line = "「姉さん！　まったくもう……私がどれだけ心配したと……！」"

[[dialogue]]
speaker = "キリカ"
# 「申し訳ございません、フィオナお嬢様。私が付いていながら、虫歯を作らせてしまうだなんて……！」
line = "「申し訳ございません、フィオナお嬢様。私が付いていながら、虫歯を作らせてしまうだなんて……！」"

[[dialogue]]
speaker = "フィオナ"
# 「キリカは悪くないよ。悪いのはぜんぶ姉さん……あなたの自己管理が甘いからです！　ほら、ジタバタしないでください！」
line = "「キリカは悪くないよ。悪いのはぜんぶ姉さん……あなたの自己管理が甘いからです！　ほら、ジタバタしないでください！」"

[[dialogue]]
speaker = "アポロ"
# 「いやだいやだいやだっ！　歯医者だけは嫌だ～！！　ドリルがきゅいーんって！　あの音、大嫌いなんだーー！！」
line = "「いやだいやだいやだっ！　歯医者だけは嫌だ～！！　ドリルがきゅいーんって！　あの音、大嫌いなんだーー！！」"

[[dialogue]]
speaker = "アポロ"
# 「魔王、何を突っ立ってるんだ！　あたしの味方と言ったじゃないか！　嘘をつくだなんて卑怯だぞ！！」
line = "「魔王、何を突っ立ってるんだ！　あたしの味方と言ったじゃないか！　嘘をつくだなんて卑怯だぞ！！」"

[[dialogue]]
speaker = "unk"
# 女の子１名、予約したいんですが
line = "女の子１名、予約したいんですが"

[[dialogue]]
speaker = "unk"
# もしもし、歯医者さんですか？
line = "もしもし、歯医者さんですか？"

[[dialogue]]
speaker = "アポロ"
# 「やめろーーーーーー！！！」
line = "「やめろーーーーーー！！！」"

[[dialogue]]
speaker = "unk"
# そうしてその日のうちに、アポロは星見家御用達の歯科医へ連行されて──翌日。
line = "そうしてその日のうちに、アポロは星見家御用達の歯科医へ連行されて──翌日。"

[[dialogue]]
speaker = "フィオナ"
# 「お医者様に行ったのですが、虫歯じゃありませんでした」
line = "「お医者様に行ったのですが、虫歯じゃありませんでした」"

[[dialogue]]
speaker = "フィオナ"
# 「その、乳歯が永久歯に生え変わろうとしていただけだったみたいで……はい。この度はお騒がせしてすみませんでした、緋宮会長……！」
line = "「その、乳歯が永久歯に生え変わろうとしていただけだったみたいで……はい。この度はお騒がせしてすみませんでした、緋宮会長……！」"

[[dialogue]]
speaker = "フィオナ"
# 「その、お詫びに桜十路のケーキ、新星星徒会のみなさんでどうぞ……！」
line = "「その、お詫びに桜十路のケーキ、新星星徒会のみなさんでどうぞ……！」"

[[dialogue]]
speaker = "unk"
# 眠っていた５年の間、アポロの体は成長が止まっていたんだものな……
line = "眠っていた５年の間、アポロの体は成長が止まっていたんだものな……"

[[dialogue]]
speaker = "unk"
# 予想外の結末に驚く俺なのだった。
line = "予想外の結末に驚く俺なのだった。"
