[[dialogue]]
speaker = "unk"
# 第１話,江戸っ子巫女との出会い,P
line = "第１話,江戸っ子巫女との出会い,P"

[[dialogue]]
speaker = "ミルフィー"
# 「会長くん、今日も星徒会活動お疲れさま。よかったら、ジュースでもどう？」
line = "「会長くん、今日も星徒会活動お疲れさま。よかったら、ジュースでもどう？」"

[[dialogue]]
speaker = "unk"
# せっかくだし、いただこうかな
line = "せっかくだし、いただこうかな"

[[dialogue]]
speaker = "ミルフィー"
# 「うん、一本どうぞ」
line = "「うん、一本どうぞ」"

[[dialogue]]
speaker = "ヒヨ"
# 「おーっと！　姐さんに近づこうとは、いい度胸だぜい！」
line = "「おーっと！　姐さんに近づこうとは、いい度胸だぜい！」"

[[dialogue]]
speaker = "ミルフィー"
# 「ヒヨちゃん！？」
line = "「ヒヨちゃん！？」"

[[dialogue]]
speaker = "ヒヨ"
# 「そこの怪しい男！　姐さんに手を出そうたってそうはいかないぜ！」
line = "「そこの怪しい男！　姐さんに手を出そうたってそうはいかないぜ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「ヒヨちゃん、この人は新星学園の星徒会長だよ」
line = "「ヒヨちゃん、この人は新星学園の星徒会長だよ」"

[[dialogue]]
speaker = "ヒヨ"
# 「星徒会長……？　ってことは、あの有名な会長サンか！」
line = "「星徒会長……？　ってことは、あの有名な会長サンか！」"

[[dialogue]]
speaker = "unk"
# こんにちは、星徒会長の緋宮クロトだ
line = "こんにちは、星徒会長の緋宮クロトだ"

[[dialogue]]
speaker = "ヒヨ"
# 「てやんでい！　ここであったが百年目！　このあたしが直々に成敗してやる！」
line = "「てやんでい！　ここであったが百年目！　このあたしが直々に成敗してやる！」"

[[dialogue]]
speaker = "ミルフィー"
# 「なんで！？」
line = "「なんで！？」"

[[dialogue]]
speaker = "ヒヨ"
# 「だって、新星学園の星徒会長と言えば、星徒会でハーレムを作るわ、見目麗しい女生徒を片っ端からナンパするわで有名だろ？」
line = "「だって、新星学園の星徒会長と言えば、星徒会でハーレムを作るわ、見目麗しい女生徒を片っ端からナンパするわで有名だろ？」"

[[dialogue]]
speaker = "unk"
# そんな認識されてるの！？
line = "そんな認識されてるの！？"

[[dialogue]]
speaker = "ミルフィー"
# 「いやいや、会長くんはそんな人じゃないからっ」
line = "「いやいや、会長くんはそんな人じゃないからっ」"

[[dialogue]]
speaker = "ヒヨ"
# 「嘘でえ！　だって、現に姐さんにも言い寄ろうとしてたじゃねぇか……！」
line = "「嘘でえ！　だって、現に姐さんにも言い寄ろうとしてたじゃねぇか……！」"

[[dialogue]]
speaker = "ミルフィー"
# 「ただ、ジュースを渡そうとしてただけなんだけどなぁ～」
line = "「ただ、ジュースを渡そうとしてただけなんだけどなぁ～」"

[[dialogue]]
speaker = "unk"
# ええと、それでこの子は？
line = "ええと、それでこの子は？"

[[dialogue]]
speaker = "ヒヨ"
# 「軟派者に名乗る名はねぇぜ」
line = "「軟派者に名乗る名はねぇぜ」"

[[dialogue]]
speaker = "ミルフィー"
# 「もうヒヨちゃんってば、流石に失礼だよ」
line = "「もうヒヨちゃんってば、流石に失礼だよ」"

[[dialogue]]
speaker = "ヒヨ"
# 「ふんだっ」
line = "「ふんだっ」"

[[dialogue]]
speaker = "ミルフィー"
# 「ごめんね、根はいい子なんだけど……」
line = "「ごめんね、根はいい子なんだけど……」"

[[dialogue]]
speaker = "ミルフィー"
# 「それでね、この子は<ruby=あまぎり>天桐</ruby>ヒヨちゃん。陸上部の後輩でプリマステラなんだ。あとヒヨちゃんは神社の巫女さんでね、舞を踊るのがすごく上手なんだよ」
line = "「それでね、この子は<ruby>天桐<rt>あまぎり</rt></ruby>ヒヨちゃん。陸上部の後輩でプリマステラなんだ。あとヒヨちゃんは神社の巫女さんでね、舞を踊るのがすごく上手なんだよ」"

[[dialogue]]
speaker = "ヒヨ"
# 「天桐神社のご利益は恋愛・仕事・学業・健康なんでもござれだ！　なんか困ったことがあったらうちの神社に来な！」
line = "「天桐神社のご利益は恋愛・仕事・学業・健康なんでもござれだ！　なんか困ったことがあったらうちの神社に来な！」"

[[dialogue]]
speaker = "ミルフィー"
# 「ヒヨちゃんの神社は本当に万能だよね～」
line = "「ヒヨちゃんの神社は本当に万能だよね～」"

[[dialogue]]
speaker = "ヒヨ"
# 「たりめぇよ！　うちの神社の神様は、いつもあたしたちを見守ってくれてるからな！」
line = "「たりめぇよ！　うちの神社の神様は、いつもあたしたちを見守ってくれてるからな！」"

[[dialogue]]
speaker = "ミルフィー"
# 「ふふ、ヒヨちゃんのポジティブさには、いつも勇気づけられてるよ」
line = "「ふふ、ヒヨちゃんのポジティブさには、いつも勇気づけられてるよ」"

[[dialogue]]
speaker = "ヒヨ"
# 「照れるぜ姐さん。あたしも姐さんにはいつも助けてもらってるからな。少しは恩返しをしたいぜ！」
line = "「照れるぜ姐さん。あたしも姐さんにはいつも助けてもらってるからな。少しは恩返しをしたいぜ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「ヒヨちゃんがそばにいてくれるだけで充分だよ」
line = "「ヒヨちゃんがそばにいてくれるだけで充分だよ」"

[[dialogue]]
speaker = "unk"
# ２人は本当に仲がいいんだな
line = "２人は本当に仲がいいんだな"

[[dialogue]]
speaker = "ヒヨ"
# 「おうよ！　あたしと姐さんとの間には、切っても切れない縁があるからな！」
line = "「おうよ！　あたしと姐さんとの間には、切っても切れない縁があるからな！」"

[[dialogue]]
speaker = "ヒヨ"
# 「本当に姐さんには頭が上がらないぜ……今のあたしがあるのも、全部姐さんのおかげだ！」
line = "「本当に姐さんには頭が上がらないぜ……今のあたしがあるのも、全部姐さんのおかげだ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「そんな大げさだよ。私なんて大したことしてないから」
line = "「そんな大げさだよ。私なんて大したことしてないから」"

[[dialogue]]
speaker = "ヒヨ"
# 「いいや、そんなことはないぜ……あれは、あたしがプリマステラになる前の話でい……」
line = "「いいや、そんなことはないぜ……あれは、あたしがプリマステラになる前の話でい……」"

[[dialogue]]
speaker = "ヒヨ"
# 「星力に伸び悩んで弱気になっていた時、姐さんはずっとあたしを励ましてくれた。自分の時間を削って、ずっとずっと、あたしの訓練に付きっきりで……」
line = "「星力に伸び悩んで弱気になっていた時、姐さんはずっとあたしを励ましてくれた。自分の時間を削って、ずっとずっと、あたしの訓練に付きっきりで……」"

[[dialogue]]
speaker = "ミルフィー"
# 「あの頃のヒヨちゃんは、なんだか放っておけなくてね……でもそう言ってくれて嬉しいな」
line = "「あの頃のヒヨちゃんは、なんだか放っておけなくてね……でもそう言ってくれて嬉しいな」"

[[dialogue]]
speaker = "ヒヨ"
# 「そんな姐さんのおかげで、あたしは遂にプリマステラになれたってわけでい。それから尊敬と感謝の念を込めて、姐さんって呼ばせてもらってるんだぜい！」
line = "「そんな姐さんのおかげで、あたしは遂にプリマステラになれたってわけでい。それから尊敬と感謝の念を込めて、姐さんって呼ばせてもらってるんだぜい！」"

[[dialogue]]
speaker = "ミルフィー"
# 「姐さんって呼ばれると、なんだか勇ましい気がするけど……まあ、ヒヨちゃんがそう呼びたいならね」
line = "「姐さんって呼ばれると、なんだか勇ましい気がするけど……まあ、ヒヨちゃんがそう呼びたいならね」"

[[dialogue]]
speaker = "unk"
# ２人はそんな関係だったんだな
line = "２人はそんな関係だったんだな"

[[dialogue]]
speaker = "ヒヨ"
# 「おう！　だから姐さんに近づく不埒な輩は、あたしが許さねぇぜ！」
line = "「おう！　だから姐さんに近づく不埒な輩は、あたしが許さねぇぜ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「だから会長くんは違うって言ってるのにぃ～」
line = "「だから会長くんは違うって言ってるのにぃ～」"

[[dialogue]]
speaker = "ヒヨ"
# 「いいや、会長サンは星徒会でのハーレムに飽き足らず、姐さんにも手を出そうとしてるに違いねぇ！」
line = "「いいや、会長サンは星徒会でのハーレムに飽き足らず、姐さんにも手を出そうとしてるに違いねぇ！」"

[[dialogue]]
speaker = "ヒヨ"
# 「てわけで、今日から会長サンのことを監視させてもらうぜい」
line = "「てわけで、今日から会長サンのことを監視させてもらうぜい」"

[[dialogue]]
speaker = "ミルフィー"
# 「監視！？」
line = "「監視！？」"

[[dialogue]]
speaker = "ヒヨ"
# 「姐さん安心してくだせぇ……ちゃんとあたしが監視して、会長サンの悪事の証拠を掴んでくるでい！」
line = "「姐さん安心してくだせぇ……ちゃんとあたしが監視して、会長サンの悪事の証拠を掴んでくるでい！」"

[[dialogue]]
speaker = "ミルフィー"
# 「私の話をちゃんと聞いてぇ～」
line = "「私の話をちゃんと聞いてぇ～」"

[[dialogue]]
speaker = "ヒヨ"
# 「会長サン、そういうことだから覚悟しといてくれよな！」
line = "「会長サン、そういうことだから覚悟しといてくれよな！」"
