[[dialogue]]
speaker = "unk"
# 第１話,魔王様のしもべです！,P
line = "第１話,魔王様のしもべです！,P"

[[dialogue]]
speaker = "unk"
# ヴィーナスに御前試合で勝利し、星徒会長になって数日──
line = "ヴィーナスに御前試合で勝利し、星徒会長になって数日──"

[[dialogue]]
speaker = "カティア"
# 「魔王様～～～～～～っ！！」
line = "「魔王様～～～～～～っ！！」"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "カティア"
# 「初めまして、魔王様！　私は１年のカティア・セルベラスです！」
line = "「初めまして、魔王様！　私は１年のカティア・セルベラスです！」"

[[dialogue]]
speaker = "カティア"
# 「御前試合の逆転勝利お見事でした！　ヴィーナス前会長に勝つなんて絶対ムリだと思ったのに、さすが魔王様です！」
line = "「御前試合の逆転勝利お見事でした！　ヴィーナス前会長に勝つなんて絶対ムリだと思ったのに、さすが魔王様です！」"

[[dialogue]]
speaker = "unk"
# 魔王様って……？
line = "魔王様って……？"

[[dialogue]]
speaker = "カティア"
# 「ほら、前会長が魔王だって言ってましたよね？」
line = "「ほら、前会長が魔王だって言ってましたよね？」"

[[dialogue]]
speaker = "カティア"
# 「実は私のご先祖は魔王の配下として大暴れしたという言い伝えがあってですね。私もご先祖様のように魔王様のお役に立ちたいと思ったんです」
line = "「実は私のご先祖は魔王の配下として大暴れしたという言い伝えがあってですね。私もご先祖様のように魔王様のお役に立ちたいと思ったんです」"

[[dialogue]]
speaker = "カティア"
# 「私を魔王様のしもべにしてください！　一緒に世界征服しましょう！」
line = "「私を魔王様のしもべにしてください！　一緒に世界征服しましょう！」"

[[dialogue]]
speaker = "unk"
# 世界征服！？
line = "世界征服！？"

[[dialogue]]
speaker = "カティア"
# 「またまた～、魔王といえば世界征服に決まってるじゃないですかー。計画はすでに練っているんでしょう？」
line = "「またまた～、魔王といえば世界征服に決まってるじゃないですかー。計画はすでに練っているんでしょう？」"

[[dialogue]]
speaker = "カティア"
# 「……計画なんてない？　おお、なるほど！　魔王様が泰然自若に振る舞っていれば世界の方が勝手にかしずくということですね。さすが魔王様です！」
line = "「……計画なんてない？　おお、なるほど！　魔王様が泰然自若に振る舞っていれば世界の方が勝手にかしずくということですね。さすが魔王様です！」"

[[dialogue]]
speaker = "カティア"
# 「しかし必ず障害は現れるもの。万難を排するために、ぜひとも私を部下にしてください」
line = "「しかし必ず障害は現れるもの。万難を排するために、ぜひとも私を部下にしてください」"

[[dialogue]]
speaker = "カティア"
# 「私の忠誠を疑うのなら命令してみてください。魔王様のご命令とあらば、購買のパンの買い占めでも何でもやってみせます！」
line = "「私の忠誠を疑うのなら命令してみてください。魔王様のご命令とあらば、購買のパンの買い占めでも何でもやってみせます！」"

[[dialogue]]
speaker = "マトイ"
# 「会長、何してるの……って、その子は？」
line = "「会長、何してるの……って、その子は？」"

[[dialogue]]
speaker = "unk"
# 俺の配下……らしい
line = "俺の配下……らしい"

[[dialogue]]
speaker = "カティア"
# 「おお、魔王様のしもべと認めてくださったのですね！　嬉しいです！　このカティア、誠心誠意魔王様にお仕えします！」
line = "「おお、魔王様のしもべと認めてくださったのですね！　嬉しいです！　このカティア、誠心誠意魔王様にお仕えします！」"

[[dialogue]]
speaker = "マトイ"
# 「配下？　しもべ？　どうなってるの……？」
line = "「配下？　しもべ？　どうなってるの……？」"

[[dialogue]]
speaker = "アナ"
# 「カティア・セルベラス。新星学園一年生。成績・素行ともに特筆すべき点はないはず。会長との接点はないと思いますが……」
line = "「カティア・セルベラス。新星学園一年生。成績・素行ともに特筆すべき点はないはず。会長との接点はないと思いますが……」"

[[dialogue]]
speaker = "アナ"
# 「会長の配下なら、すでに星徒会役員の我々がいます」
line = "「会長の配下なら、すでに星徒会役員の我々がいます」"

[[dialogue]]
speaker = "カティア"
# 「ウ～……ガルルル！　私こそが魔王様の一番のしもべガオ！　星徒会には負けないガオ～！」
line = "「ウ～……ガルルル！　私こそが魔王様の一番のしもべガオ！　星徒会には負けないガオ～！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふぅん、あなたもクロトの真価を理解できるのね。やるじゃない」
line = "「ふぅん、あなたもクロトの真価を理解できるのね。やるじゃない」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でもあなたがクロトの一番というのは認められないわ。クロトを一番近くで支えるのは私、そして新星星徒会よ！」
line = "「でもあなたがクロトの一番というのは認められないわ。クロトを一番近くで支えるのは私、そして新星星徒会よ！」"

[[dialogue]]
speaker = "カティア"
# 「なら勝負だワン！　勝った方が魔王様の一番のしもべワン！」
line = "「なら勝負だワン！　勝った方が魔王様の一番のしもべワン！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「せめてワンかガオかどっちかにしなさいよ」
line = "「せめてワンかガオかどっちかにしなさいよ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でも勝負するのはいいわね。実力で白黒付けてあげる！」
line = "「でも勝負するのはいいわね。実力で白黒付けてあげる！」"

[[dialogue]]
speaker = "カティア"
# 「きゅぅ」
line = "「きゅぅ」"

[[dialogue]]
speaker = "アナ"
# 「犬キャラだけにワンパンでしたね」
line = "「犬キャラだけにワンパンでしたね」"

[[dialogue]]
speaker = "アナ"
# 「前会長と、プリマステラでもない一生徒ではこうなるのも必然です。無常」
line = "「前会長と、プリマステラでもない一生徒ではこうなるのも必然です。無常」"

[[dialogue]]
speaker = "カティア"
# 「前星徒会とガチンコバトルで勝てるわけありませんよぉ！　もし勝ったら私が星徒会長ですよ！」
line = "「前星徒会とガチンコバトルで勝てるわけありませんよぉ！　もし勝ったら私が星徒会長ですよ！」"

[[dialogue]]
speaker = "カティア"
# 「気づいたら目の前が真っ白になって、ビームで蒸発するかと思いました……。ちょっとぐらい手加減してくれたっていいじゃないですかぁ～」
line = "「気づいたら目の前が真っ白になって、ビームで蒸発するかと思いました……。ちょっとぐらい手加減してくれたっていいじゃないですかぁ～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あれでも一応威力は抑えたわよ。本気でぶっ飛ばすのも大人げないし」
line = "「あれでも一応威力は抑えたわよ。本気でぶっ飛ばすのも大人げないし」"

[[dialogue]]
speaker = "カティア"
# 「うぐっ……あれでも手加減してたんだ……前会長怖い……」
line = "「うぐっ……あれでも手加減してたんだ……前会長怖い……」"

[[dialogue]]
speaker = "カティア"
# 「魔王様～！」
line = "「魔王様～！」"

[[dialogue]]
speaker = "unk"
# おー……ヨシヨシ
line = "おー……ヨシヨシ"

[[dialogue]]
speaker = "カティア"
# 「うぅ……お気遣いありがとうございます……」
line = "「うぅ……お気遣いありがとうございます……」"

[[dialogue]]
speaker = "カティア"
# 「さすが魔王様はお優しいガオ。一生ついていきます……ワン」
line = "「さすが魔王様はお優しいガオ。一生ついていきます……ワン」"

[[dialogue]]
speaker = "マトイ"
# （うーん、キャラが立つなら私も語尾に何かつけようかな……？）
line = "（うーん、キャラが立つなら私も語尾に何かつけようかな……？）"

[[dialogue]]
speaker = "ヴィーナス"
# 「まぁ、クロトの配下が増えるのはいいことだわ。星徒会より下っぱで良ければ認めてあげなくもないわよ」
line = "「まぁ、クロトの配下が増えるのはいいことだわ。星徒会より下っぱで良ければ認めてあげなくもないわよ」"

[[dialogue]]
speaker = "カティア"
# 「な、情けなんていらないぞ！　いつか必ず魔王様の一番のしもべの座を勝ち取ってやるからな！」
line = "「な、情けなんていらないぞ！　いつか必ず魔王様の一番のしもべの座を勝ち取ってやるからな！」"

[[dialogue]]
speaker = "カティア"
# 「覚えてろよ～っ！」
line = "「覚えてろよ～っ！」"

[[dialogue]]
speaker = "マトイ"
# 「あ……行っちゃった……」
line = "「あ……行っちゃった……」"

[[dialogue]]
speaker = "マトイ"
# 「会長を慕ってくれる子ができて良かった……ね？」
line = "「会長を慕ってくれる子ができて良かった……ね？」"
