[[dialogue]]
speaker = "unk"
# 第１話,モネのモテ期！？,P
line = "第１話,モネのモテ期！？,P"

[[dialogue]]
speaker = "unk"
# 先日の事件で深淵書庫を出たリィベルは、新星学園に籍を置くこととなり、それに伴って<ruby=ラルーナ>新星学園寮</ruby>に入寮した。
line = "先日の事件で深淵書庫を出たリィベルは、新星学園に籍を置くこととなり、それに伴って<ruby>新星学園寮<rt>ラルーナ</rt></ruby>に入寮した。"

[[dialogue]]
speaker = "リィベル"
# 「モネ、髪の毛かわかして」
line = "「モネ、髪の毛かわかして」"

[[dialogue]]
speaker = "モネ"
# 「リィベルさん、お風呂上がりですか？　いいですよ。……ふふ、リィベルさんの髪、長くてサラサラですごく綺麗」
line = "「リィベルさん、お風呂上がりですか？　いいですよ。……ふふ、リィベルさんの髪、長くてサラサラですごく綺麗」"

[[dialogue]]
speaker = "リィベル"
# 「髪ならあなたも伸ばせばいいじゃない」
line = "「髪ならあなたも伸ばせばいいじゃない」"

[[dialogue]]
speaker = "モネ"
# 「私はちょっとくせっ毛なので、伸ばすと収拾がつかなくて……」
line = "「私はちょっとくせっ毛なので、伸ばすと収拾がつかなくて……」"

[[dialogue]]
speaker = "リィベル"
# 「ふぅん」
line = "「ふぅん」"

[[dialogue]]
speaker = "リップル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "リィベル"
# 「モネ、課題やって」
line = "「モネ、課題やって」"

[[dialogue]]
speaker = "モネ"
# 「学園の課題は自分でやらないとダメですよ。お手伝いしますから、頑張りましょう？」
line = "「学園の課題は自分でやらないとダメですよ。お手伝いしますから、頑張りましょう？」"

[[dialogue]]
speaker = "リィベル"
# 「うぅ、めんどくさい……数学なんてリクリエを滅ぼすのに要らないでしょうに」
line = "「うぅ、めんどくさい……数学なんてリクリエを滅ぼすのに要らないでしょうに」"

[[dialogue]]
speaker = "モネ"
# 「リクリエはともかく、数学の参考書もいいものです。一度じっくり読んでみてください」
line = "「リクリエはともかく、数学の参考書もいいものです。一度じっくり読んでみてください」"

[[dialogue]]
speaker = "モネ"
# 「ちなみに参考書ならオススメは<ruby=くまさんしゃ>隈参社</ruby>ですね。図解がとてもわかりやすくて、夏休みの推薦図書にしたいくらいですよ」
line = "「ちなみに参考書ならオススメは<ruby>隈参社<rt>くまさんしゃ</rt></ruby>ですね。図解がとてもわかりやすくて、夏休みの推薦図書にしたいくらいですよ」"

[[dialogue]]
speaker = "リィベル"
# 「す、推薦図書！？　参考書なのに！？」
line = "「す、推薦図書！？　参考書なのに！？」"

[[dialogue]]
speaker = "リップル"
# 「じー……」
line = "「じー……」"

[[dialogue]]
speaker = "モネ"
# 「あれ？　今誰かいたような……？」
line = "「あれ？　今誰かいたような……？」"

[[dialogue]]
speaker = "リィベル"
# 「モネ。今度の週末、買い物に付き合って」
line = "「モネ。今度の週末、買い物に付き合って」"

[[dialogue]]
speaker = "モネ"
# 「えっと、今週末の予定は……はい、大丈夫ですよ。何を買いに行くんですか？」
line = "「えっと、今週末の予定は……はい、大丈夫ですよ。何を買いに行くんですか？」"

[[dialogue]]
speaker = "リィベル"
# 「下着よ」
line = "「下着よ」"

[[dialogue]]
speaker = "モネ"
# 「え、下着ですか！？」
line = "「え、下着ですか！？」"

[[dialogue]]
speaker = "リィベル"
# 「そう。種類もサイズも多すぎて、何を買えばいいか分からないのよ」
line = "「そう。種類もサイズも多すぎて、何を買えばいいか分からないのよ」"

[[dialogue]]
speaker = "モネ"
# 「なるほど……でも、私には荷が重いというか……」
line = "「なるほど……でも、私には荷が重いというか……」"

[[dialogue]]
speaker = "リィベル"
# 「そうなの？」
line = "「そうなの？」"

[[dialogue]]
speaker = "モネ"
# 「リィベルさんは私でいいんですか？　私、センスには自信がなくて……」
line = "「リィベルさんは私でいいんですか？　私、センスには自信がなくて……」"

[[dialogue]]
speaker = "リィベル"
# 「そうは言っても、ファッション雑誌だって読み込んでいるんでしょう？　大丈夫よ、私はモネを信じているわ」
line = "「そうは言っても、ファッション雑誌だって読み込んでいるんでしょう？　大丈夫よ、私はモネを信じているわ」"

[[dialogue]]
speaker = "モネ"
# 「わ、わかりました！　不肖、紙屋敷モネ、リィベルさんの下着選びを成功させてみせます！」
line = "「わ、わかりました！　不肖、紙屋敷モネ、リィベルさんの下着選びを成功させてみせます！」"

[[dialogue]]
speaker = "モネ"
# 「じゃあ、週末はお買い物して、そのあと何か甘いものでも……」
line = "「じゃあ、週末はお買い物して、そのあと何か甘いものでも……」"

[[dialogue]]
speaker = "？？？"
# 「チョット待つで～す！！」
line = "「チョット待つで～す！！」"

[[dialogue]]
speaker = "モネ"
# 「わっ、リップルさん！？」
line = "「わっ、リップルさん！？」"

[[dialogue]]
speaker = "リップル"
# 「ワタシもモネと遊びに行きタイで～す！　リィベルはモネをひとりジメしすぎでーす！」
line = "「ワタシもモネと遊びに行きタイで～す！　リィベルはモネをひとりジメしすぎでーす！」"

[[dialogue]]
speaker = "リィベル"
# 「何なの、この天使……寮で見かけたことはあるけど、なんでいつも水着なのよ」
line = "「何なの、この天使……寮で見かけたことはあるけど、なんでいつも水着なのよ」"

[[dialogue]]
speaker = "リップル"
# 「それはいつも夏のココロを忘れないタメでーす！　水着は夏のショーチョーです！」
line = "「それはいつも夏のココロを忘れないタメでーす！　水着は夏のショーチョーです！」"

[[dialogue]]
speaker = "リィベル"
# 「そう……」
line = "「そう……」"

[[dialogue]]
speaker = "リィベル"
# （勢いで頷いてしまったけど意味がわからないわ。そんなに水着姿を人に見せたいのかしら）
line = "（勢いで頷いてしまったけど意味がわからないわ。そんなに水着姿を人に見せたいのかしら）"

[[dialogue]]
speaker = "リップル"
# 「それより、リィベルはモネをドクセンしてます！　断固コーギーします！」
line = "「それより、リィベルはモネをドクセンしてます！　断固コーギーします！」"

[[dialogue]]
speaker = "モネ"
# 「それを言うなら断固抗議では……え、独占、ですか？」
line = "「それを言うなら断固抗議では……え、独占、ですか？」"

[[dialogue]]
speaker = "リップル"
# 「ソウです！　モネは最近リィベルばっかりカマってます！　ワタシはＢＩＧサビシイです！」
line = "「ソウです！　モネは最近リィベルばっかりカマってます！　ワタシはＢＩＧサビシイです！」"

[[dialogue]]
speaker = "リィベル"
# 「そんなのモネの勝手でしょうに。子どもじゃないんだから我慢しなさい」
line = "「そんなのモネの勝手でしょうに。子どもじゃないんだから我慢しなさい」"

[[dialogue]]
speaker = "モネ"
# 「リィベルさん、そんな言い方は……」
line = "「リィベルさん、そんな言い方は……」"

[[dialogue]]
speaker = "リップル"
# 「リィベルこそお子様でーす！　いつもモネに甘えてバカリです！」
line = "「リィベルこそお子様でーす！　いつもモネに甘えてバカリです！」"

[[dialogue]]
speaker = "モネ"
# 「リップルさんも！」
line = "「リップルさんも！」"

[[dialogue]]
speaker = "リィベル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "リップル"
# 「ムー……」
line = "「ムー……」"

[[dialogue]]
speaker = "モネ"
# 「え、えっとえっと……」
line = "「え、えっとえっと……」"

[[dialogue]]
speaker = "モネ"
# 「ふたりとも、私のために争わないでください！！」
line = "「ふたりとも、私のために争わないでください！！」"

[[dialogue]]
speaker = "モネ"
# （言っちゃった～！ よりにもよって変なこと言っちゃったよ～！！）
line = "（言っちゃった～！ よりにもよって変なこと言っちゃったよ～！！）"

[[dialogue]]
speaker = "イクシリオン"
# 「あ、モネさんこんにちは。図書館にあるか探していただきたい本がありまして──」
line = "「あ、モネさんこんにちは。図書館にあるか探していただきたい本がありまして──」"

[[dialogue]]
speaker = "イクシリオン"
# 「おや、お取込み中でしたか？」
line = "「おや、お取込み中でしたか？」"

[[dialogue]]
speaker = "モネ"
# 「イクシーさんまで！？」
line = "「イクシーさんまで！？」"

[[dialogue]]
speaker = "unk"
# 俺の彼女にモテ期が来た！？
line = "俺の彼女にモテ期が来た！？"

[[dialogue]]
speaker = "モネ"
# 「ってなんで会長が！？　いつからそこに！？」
line = "「ってなんで会長が！？　いつからそこに！？」"

[[dialogue]]
speaker = "unk"
# リップルより前くらい
line = "リップルより前くらい"

[[dialogue]]
speaker = "モネ"
# 「じゃ、じゃあ……さっきのも見てました、よね？」
line = "「じゃ、じゃあ……さっきのも見てました、よね？」"

[[dialogue]]
speaker = "unk"
# 俺の彼女がモテモテで鼻が高い
line = "俺の彼女がモテモテで鼻が高い"

[[dialogue]]
speaker = "モネ"
# 「も～、からかわないでくださーい！」
line = "「も～、からかわないでくださーい！」"

[[dialogue]]
speaker = "リィベル"
# 「あなたたち、付き合ってたのね。それならそうと言えばいいのに。私は今度でいいから、デートでも行ってきなさい」
line = "「あなたたち、付き合ってたのね。それならそうと言えばいいのに。私は今度でいいから、デートでも行ってきなさい」"

[[dialogue]]
speaker = "リップル"
# 「行ってラッシャイで～す！　ゴユックリ～！」
line = "「行ってラッシャイで～す！　ゴユックリ～！」"

[[dialogue]]
speaker = "イクシリオン"
# 「デート楽しんできてくださいね、モネさん。……その後はしっぽりと……」
line = "「デート楽しんできてくださいね、モネさん。……その後はしっぽりと……」"

[[dialogue]]
speaker = "モネ"
# 「うぅ、みんなの視線が生温かい……」
line = "「うぅ、みんなの視線が生温かい……」"

[[dialogue]]
speaker = "unk"
# みんなの快諾も得て、無事（？）デートの約束を取り付けたのだった。
line = "みんなの快諾も得て、無事（？）デートの約束を取り付けたのだった。"
