[[dialogue]]
speaker = "unk"
# 第１話,スーパーパタンナーあらわる,P
line = "第１話,スーパーパタンナーあらわる,P"

[[dialogue]]
speaker = "ヴィーナス"
# 「ん～～～～っ……今日も疲れたわ～～」
line = "「ん～～～～っ……今日も疲れたわ～～」"

[[dialogue]]
speaker = "unk"
# 背伸びをしたヴィーナスが、大きく胸を反らしたその時だった。
line = "背伸びをしたヴィーナスが、大きく胸を反らしたその時だった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「きゃっ！？」
line = "「きゃっ！？」"

[[dialogue]]
speaker = "マトイ"
# 「え──痛ぁっ！？　何かおでこに当たった！？」
line = "「え──痛ぁっ！？　何かおでこに当たった！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ごめんね、マトイ。ボタンが弾け飛んじゃったみたい」
line = "「ごめんね、マトイ。ボタンが弾け飛んじゃったみたい」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なんとなーく胸周りがキツいとは思ってたのよね。また胸がおっきくなったのかしら」
line = "「なんとなーく胸周りがキツいとは思ってたのよね。また胸がおっきくなったのかしら」"

[[dialogue]]
speaker = "マトイ"
# 「ヴィーナスのお胸、恐るべし……！」
line = "「ヴィーナスのお胸、恐るべし……！」"

[[dialogue]]
speaker = "マトイ"
# 「でも、制服のサイズが合わなくなったら買い換えるのも大変だよね」
line = "「でも、制服のサイズが合わなくなったら買い換えるのも大変だよね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「その点は大丈夫よ、九浄家には優秀なメイドがいるもの。服飾のスペシャリストがね」
line = "「その点は大丈夫よ、九浄家には優秀なメイドがいるもの。服飾のスペシャリストがね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「胸周りだけなら買い換えるほどじゃないし、今晩にでも美鶴に制服のサイズを調整してもらった方が良さそうね」
line = "「胸周りだけなら買い換えるほどじゃないし、今晩にでも美鶴に制服のサイズを調整してもらった方が良さそうね」"

[[dialogue]]
speaker = "美鶴"
# 「お呼びですか、お嬢様」
line = "「お呼びですか、お嬢様」"

[[dialogue]]
speaker = "ヴィーナス"
# 「美鶴！？　いつからそこにいたの！？」
line = "「美鶴！？　いつからそこにいたの！？」"

[[dialogue]]
speaker = "美鶴"
# 「いえ、閃じゃないんですから。たまたま、通りがかったところでうちの名前を呼ばれたので何事かと……おや、ここに落ちてるボタンは？」
line = "「いえ、閃じゃないんですから。たまたま、通りがかったところでうちの名前を呼ばれたので何事かと……おや、ここに落ちてるボタンは？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それ、私のよ。ほら、ここの」
line = "「それ、私のよ。ほら、ここの」"

[[dialogue]]
speaker = "美鶴"
# 「なるほど。お嬢様の制服のボタンがはじけ飛んだんですか」
line = "「なるほど。お嬢様の制服のボタンがはじけ飛んだんですか」"

[[dialogue]]
speaker = "unk"
# はじめまして、美鶴
line = "はじめまして、美鶴"

[[dialogue]]
speaker = "美鶴"
# 「星徒会の皆さんとは初対面ですね、はじめまして。新星学園１年、<ruby=ながしの>長篠</ruby><ruby=みつる>美鶴</ruby>です」
line = "「星徒会の皆さんとは初対面ですね、はじめまして。新星学園１年、<ruby>長篠<rt>ながしの</rt></ruby><ruby>美鶴<rt>みつる</rt></ruby>です」"

[[dialogue]]
speaker = "マトイ"
# 「えっ、１年生なんだ！　落ち着いてて大人っぽいから年上かと思っちゃった。九浄家のメイドさんなんだよね？」
line = "「えっ、１年生なんだ！　落ち着いてて大人っぽいから年上かと思っちゃった。九浄家のメイドさんなんだよね？」"

[[dialogue]]
speaker = "美鶴"
# 「元々はメイドとして雇われたんじゃないんですけどね。九浄家でパタンナーをしてます」
line = "「元々はメイドとして雇われたんじゃないんですけどね。九浄家でパタンナーをしてます」"

[[dialogue]]
speaker = "unk"
# パタンナーって？
line = "パタンナーって？"

[[dialogue]]
speaker = "美鶴"
# 「あまりメジャーな職種じゃないんで、知らなくても無理ないですね。デザイナーが制作したデザインを基に型紙を作る仕事です」
line = "「あまりメジャーな職種じゃないんで、知らなくても無理ないですね。デザイナーが制作したデザインを基に型紙を作る仕事です」"

[[dialogue]]
speaker = "美鶴"
# 「当主様が考えた無茶振りなデザインを、うちが型紙に起こし、縫製まで手掛けてます」
line = "「当主様が考えた無茶振りなデザインを、うちが型紙に起こし、縫製まで手掛けてます」"

[[dialogue]]
speaker = "マトイ"
# 「縫製って……服を作ってるの？」
line = "「縫製って……服を作ってるの？」"

[[dialogue]]
speaker = "美鶴"
# 「ええ。パタンナーとはいってますが、服飾全般です」
line = "「ええ。パタンナーとはいってますが、服飾全般です」"

[[dialogue]]
speaker = "ヴィーナス"
# 「メイド隊のみんながバレンタインとかクリスマスに着てた特別な衣装、あるじゃない？」
line = "「メイド隊のみんながバレンタインとかクリスマスに着てた特別な衣装、あるじゃない？」"

[[dialogue]]
speaker = "マトイ"
# 「せつなちゃんとかヨミちゃんが着てた服かな？　すっごく可愛かったね」
line = "「せつなちゃんとかヨミちゃんが着てた服かな？　すっごく可愛かったね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でしょう！？　あれは全部、美鶴のお手製なのよ！」
line = "「でしょう！？　あれは全部、美鶴のお手製なのよ！」"

[[dialogue]]
speaker = "マトイ"
# 「全部、ひとりで！？　スゴいね！」
line = "「全部、ひとりで！？　スゴいね！」"

[[dialogue]]
speaker = "美鶴"
# 「ええ、まあ。とはいえデザイン元は当主様ですし、もらってるお賃金通りの仕事をしてるだけですけど」
line = "「ええ、まあ。とはいえデザイン元は当主様ですし、もらってるお賃金通りの仕事をしてるだけですけど」"

[[dialogue]]
speaker = "ヴィーナス"
# 「見た目だけでなく、着心地も抜群なの！　美鶴はスゴいのよ、ふふーん♪」
line = "「見た目だけでなく、着心地も抜群なの！　美鶴はスゴいのよ、ふふーん♪」"

[[dialogue]]
speaker = "美鶴"
# 「褒めてくれるのは嬉しいですが、ヴィーナスお嬢様、服の前がはだけたままなのは、だらしないです。替えのボタンがありますんで、つけ替えますね」
line = "「褒めてくれるのは嬉しいですが、ヴィーナスお嬢様、服の前がはだけたままなのは、だらしないです。替えのボタンがありますんで、つけ替えますね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「助かるわ。帰ったら、制服の調整もお願いできる？」
line = "「助かるわ。帰ったら、制服の調整もお願いできる？」"

[[dialogue]]
speaker = "美鶴"
# 「それがうちの仕事なんで、任せてください。あ、壊れたこっちのボタンは、うちが預かります」
line = "「それがうちの仕事なんで、任せてください。あ、壊れたこっちのボタンは、うちが預かります」"

[[dialogue]]
speaker = "マトイ"
# 「壊れたボタンなんてどうするの？」
line = "「壊れたボタンなんてどうするの？」"

[[dialogue]]
speaker = "美鶴"
# 「閃にあげたら、尻尾振って喜びそうなんで」
line = "「閃にあげたら、尻尾振って喜びそうなんで」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んー？　ただのボタンじゃない。センちゃん、ボタンのコレクションなんてしてたかしら」
line = "「んー？　ただのボタンじゃない。センちゃん、ボタンのコレクションなんてしてたかしら」"

[[dialogue]]
speaker = "美鶴"
# 「いえ、ヴィーナスお嬢様の胸を支えていたボタンというところに付加価値が」
line = "「いえ、ヴィーナスお嬢様の胸を支えていたボタンというところに付加価値が」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……私の胸？　よくわからないけど、もうダメになってしまったボタンなんだし、好きにしていいわよ」
line = "「……私の胸？　よくわからないけど、もうダメになってしまったボタンなんだし、好きにしていいわよ」"

[[dialogue]]
speaker = "美鶴"
# 「では、遠慮なく。……お嬢様、完成しました」
line = "「では、遠慮なく。……お嬢様、完成しました」"

[[dialogue]]
speaker = "マトイ"
# 「わっ、やっぱり美鶴ちゃん、手際いいね！　話してる内につけ終わっちゃった」
line = "「わっ、やっぱり美鶴ちゃん、手際いいね！　話してる内につけ終わっちゃった」"

[[dialogue]]
speaker = "美鶴"
# 「このくらいなら朝飯前ですよ。他にも何かあれば承りますが、うちへの依頼には作業料が発生します。タダ働きはしませんので、あしからず」
line = "「このくらいなら朝飯前ですよ。他にも何かあれば承りますが、うちへの依頼には作業料が発生します。タダ働きはしませんので、あしからず」"

[[dialogue]]
speaker = "unk"
# しっかりしてるね
line = "しっかりしてるね"

[[dialogue]]
speaker = "ヴィーナス"
# 「だって、プロだもの。彼女の仕事にはそれだけの価値があるわ！　美鶴、これからも期待してるわね！」
line = "「だって、プロだもの。彼女の仕事にはそれだけの価値があるわ！　美鶴、これからも期待してるわね！」"

[[dialogue]]
speaker = "美鶴"
# 「どうも。では、失礼」
line = "「どうも。では、失礼」"

[[dialogue]]
speaker = "マトイ"
# 「……美鶴ちゃん、ちょっととっつきにくそうな空気出してたね」
line = "「……美鶴ちゃん、ちょっととっつきにくそうな空気出してたね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうなのよ。必要以上に人と接したがらないの。ウチのメイド隊でもちょっと浮いちゃってるわ」
line = "「そうなのよ。必要以上に人と接したがらないの。ウチのメイド隊でもちょっと浮いちゃってるわ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「いい子だと思うんだけど、誤解されっぱなしなのは可哀想だわ……そうね、クロトにお願いしようかしら」
line = "「いい子だと思うんだけど、誤解されっぱなしなのは可哀想だわ……そうね、クロトにお願いしようかしら」"

[[dialogue]]
speaker = "unk"
# 俺に！？
line = "俺に！？"

[[dialogue]]
speaker = "ヴィーナス"
# 「名付けて『美鶴の心を開け大作戦』！」
line = "「名付けて『美鶴の心を開け大作戦』！」"

[[dialogue]]
speaker = "unk"
# 作戦名からだいたいの内容は想像はできるし、俺も美鶴のことが気になってはいるけれど。
line = "作戦名からだいたいの内容は想像はできるし、俺も美鶴のことが気になってはいるけれど。"

[[dialogue]]
speaker = "unk"
# ヘレナさんもヴィーナスも無茶振りが過ぎるのは、親子の縁が成せる業なんだろうかと思わずにはいられなかった。
line = "ヘレナさんもヴィーナスも無茶振りが過ぎるのは、親子の縁が成せる業なんだろうかと思わずにはいられなかった。"
