[[dialogue]]
speaker = "unk"
# とある日の深夜。どうも寝付けなくて公園に散歩へ出ていると──
line = "とある日の深夜。どうも寝付けなくて公園に散歩へ出ていると──"

[[dialogue]]
speaker = "キサナ"
# 「は～ぁ。さっぱりするぜ。こーしていつでも水浴びできんのはこの街のいいとこだな」
line = "「は～ぁ。さっぱりするぜ。こーしていつでも水浴びできんのはこの街のいいとこだな」"

[[dialogue]]
speaker = "クロト"
# 「公園の噴水で何して……！？」
line = "「公園の噴水で何して……！？」"

[[dialogue]]
speaker = "キサナ"
# 「ん？　魔王じゃねえか。見りゃわかんだろ。水浴びだ、水浴び」
line = "「ん？　魔王じゃねえか。見りゃわかんだろ。水浴びだ、水浴び」"

[[dialogue]]
speaker = "キサナ"
# 「別にいいだろ？　昼間は街のガキどもだって水浴びして遊んでるじゃねえか。それともなんだ？　悪人は水浴びしちゃいけませんってか？」
line = "「別にいいだろ？　昼間は街のガキどもだって水浴びして遊んでるじゃねえか。それともなんだ？　悪人は水浴びしちゃいけませんってか？」"

[[dialogue]]
speaker = "unk"
# 一糸まとわぬキサナの姿につい目が釘付けになってしまう。
line = "一糸まとわぬキサナの姿につい目が釘付けになってしまう。"

[[dialogue]]
speaker = "unk"
# 荒々しい言動をそのまま表したかのような、グラマラスで暴力的な肉体。
line = "荒々しい言動をそのまま表したかのような、グラマラスで暴力的な肉体。"

[[dialogue]]
speaker = "unk"
# 公園の灯りを反射する、艶めかしく濡れた柔肌。
line = "公園の灯りを反射する、艶めかしく濡れた柔肌。"

[[dialogue]]
speaker = "unk"
# 目を逸らそうとしても視線が吸い込まれてしまって──
line = "目を逸らそうとしても視線が吸い込まれてしまって──"

[[dialogue]]
speaker = "キサナ"
# 「なんだ……オマエ、アタシの裸に欲情してんのか？」
line = "「なんだ……オマエ、アタシの裸に欲情してんのか？」"

[[dialogue]]
speaker = "クロト"
# 「──！？　いや……」
line = "「──！？　いや……」"

[[dialogue]]
speaker = "キサナ"
# 「人の体ガン見しといて誤魔化せると思ってんのかよ。魔王っつってもオスだな。性欲には勝てませんってかぁ？」
line = "「人の体ガン見しといて誤魔化せると思ってんのかよ。魔王っつってもオスだな。性欲には勝てませんってかぁ？」"

[[dialogue]]
speaker = "キサナ"
# 「まぁ落ち着けよ童貞野郎。オマエに見つかっちまった以上、悠長に水浴びしてたら捕まっちまうだろ？　けどアタシもまだ水浴びしてえんだ」
line = "「まぁ落ち着けよ童貞野郎。オマエに見つかっちまった以上、悠長に水浴びしてたら捕まっちまうだろ？　けどアタシもまだ水浴びしてえんだ」"

[[dialogue]]
speaker = "キサナ"
# 「だからギブアンドテイクといこうぜ？　アタシの体、好きに触らせてやるよ。その代わり、今夜はアタシんこと見逃せ……な？」
line = "「だからギブアンドテイクといこうぜ？　アタシの体、好きに触らせてやるよ。その代わり、今夜はアタシんこと見逃せ……な？」"

[[dialogue]]
speaker = "クロト"
# 「うわっ！？」
line = "「うわっ！？」"

[[dialogue]]
speaker = "キサナ"
# 「ハッ、やっぱここがパンパンになってるじゃねえか。敵の裸にここまで興奮してたのか？　正義の味方さまよぉ」
line = "「ハッ、やっぱここがパンパンになってるじゃねえか。敵の裸にここまで興奮してたのか？　正義の味方さまよぉ」"

[[dialogue]]
speaker = "クロト"
# 「離れ──んぷっ！？」
line = "「離れ──んぷっ！？」"

[[dialogue]]
speaker = "キサナ"
# 「うるせぇな。乳でも吸ってろ。アタシのおっぱい吸いたかったんだろ？　お望み通り吸わせてやるぜ」
line = "「うるせぇな。乳でも吸ってろ。アタシのおっぱい吸いたかったんだろ？　お望み通り吸わせてやるぜ」"

[[dialogue]]
speaker = "unk"
# 馬乗りになったキサナが、その豊満な乳房を俺の顔にぎゅっと押しつけてくる。
line = "馬乗りになったキサナが、その豊満な乳房を俺の顔にぎゅっと押しつけてくる。"

[[dialogue]]
speaker = "unk"
# ぷっくりとした硬い乳首が口の中に入ってきて、その官能的な感触につい──
line = "ぷっくりとした硬い乳首が口の中に入ってきて、その官能的な感触につい──"

[[dialogue]]
speaker = "キサナ"
# 「んっはぁ……<emoji=heart04>　なんだよ、おい。吸い付いてきてんじゃねえか。魔王っつってもオスの本能には勝てねえみてえだな？」
line = "「んっはぁ……<emoji=heart04>　なんだよ、おい。吸い付いてきてんじゃねえか。魔王っつってもオスの本能には勝てねえみてえだな？」"

[[dialogue]]
speaker = "クロト"
# 「～～っ！！　ち、違っ……！！」
line = "「～～っ！！　ち、違っ……！！」"

[[dialogue]]
speaker = "キサナ"
# 「ふふ、照れんな照れんな。ギブアンドテイクっつったろ？　好きに揉んだり吸ったりしていいんだぜ？」
line = "「ふふ、照れんな照れんな。ギブアンドテイクっつったろ？　好きに揉んだり吸ったりしていいんだぜ？」"

[[dialogue]]
speaker = "キサナ"
# 「アタシもダリい逃亡生活のせーでムカムカしてたトコだったしなぁ。オマエも欲求不満みたいだしちょうどいいだろ」
line = "「アタシもダリい逃亡生活のせーでムカムカしてたトコだったしなぁ。オマエも欲求不満みたいだしちょうどいいだろ」"

[[dialogue]]
speaker = "unk"
# キサナが腰を揺らして割れ目を押しつけてくる。
line = "キサナが腰を揺らして割れ目を押しつけてくる。"

[[dialogue]]
speaker = "unk"
# 水を浴びて冷えた体とは反対に、その場所だけは煮えたぎるように熱くて、否応なしに体が反応してしまう。
line = "水を浴びて冷えた体とは反対に、その場所だけは煮えたぎるように熱くて、否応なしに体が反応してしまう。"

[[dialogue]]
speaker = "キサナ"
# 「それじゃ──食わせてもらうぜ」
line = "「それじゃ──食わせてもらうぜ」"

[[dialogue]]
speaker = "キサナ"
# 「んん～～～っ！」
line = "「んん～～～っ！」"

[[dialogue]]
speaker = "キサナ"
# 「はぁ、はぁ……やべぇ……<emoji=heart04>　挿れた瞬間、チ○ポがビクビク暴れやがった……<emoji=heart04>」
line = "「はぁ、はぁ……やべぇ……<emoji=heart04>　挿れた瞬間、チ○ポがビクビク暴れやがった……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「んっ……はっ……<emoji=heart04>　熱くて、硬くて……チ○ポってこんな感触なのかよ……んぁっ、はぁぁっ、腰動かすのも一苦労じゃねーか」
line = "「んっ……はっ……<emoji=heart04>　熱くて、硬くて……チ○ポってこんな感触なのかよ……んぁっ、はぁぁっ、腰動かすのも一苦労じゃねーか」"

[[dialogue]]
speaker = "キサナ"
# 「チ○ポギンギンにしやがって……ハハッ、敵に犯されてどんだけ興奮してんだよっ……<emoji=heart04>　魔王さまは特殊性癖の持ち主ってかぁ……お仲間が見たら幻滅しちまうぜっ……<emoji=heart04>」
line = "「チ○ポギンギンにしやがって……ハハッ、敵に犯されてどんだけ興奮してんだよっ……<emoji=heart04>　魔王さまは特殊性癖の持ち主ってかぁ……お仲間が見たら幻滅しちまうぜっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 煽られているのにゾクゾクと走る快感のせいで何も言い返せない。
line = "煽られているのにゾクゾクと走る快感のせいで何も言い返せない。"

[[dialogue]]
speaker = "unk"
# 反応するまいとしているのに、キサナの熱く柔らかい肉の中でペニスが勝手に跳ねる。
line = "反応するまいとしているのに、キサナの熱く柔らかい肉の中でペニスが勝手に跳ねる。"

[[dialogue]]
speaker = "キサナ"
# 「はっ、あっ……こりゃ契約成立ってことでいいよなぁ……<emoji=heart04>　軽く腰を振ってるだけで、チ○ポがどんどん滾ってきてやがるぜ<emoji=heart04>」
line = "「はっ、あっ……こりゃ契約成立ってことでいいよなぁ……<emoji=heart04>　軽く腰を振ってるだけで、チ○ポがどんどん滾ってきてやがるぜ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「アタシも、んっ、はぁっ、興奮してきたっ……<emoji=heart04>　んだよ、セックスってめちゃくちゃ気持ちいいじゃねえかっ……<emoji=heart04>」
line = "「アタシも、んっ、はぁっ、興奮してきたっ……<emoji=heart04>　んだよ、セックスってめちゃくちゃ気持ちいいじゃねえかっ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「娼婦みてえに犯されんのは嫌だがよっ<emoji=heart04>　こーして男を犯してやる分には、あぁんっ、はぁあんっ、悪く、ねえ……<emoji=heart04>」
line = "「娼婦みてえに犯されんのは嫌だがよっ<emoji=heart04>　こーして男を犯してやる分には、あぁんっ、はぁあんっ、悪く、ねえ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 荒々しく腰を振り、肉棒をこれでもかと刺激してくるキサナ。
line = "荒々しく腰を振り、肉棒をこれでもかと刺激してくるキサナ。"

[[dialogue]]
speaker = "キサナ"
# 「おらっ、んっ、はぁっ<emoji=heart04>　オマエも腰振れよっ……<emoji=heart04>　つかもっとおっぱい吸えっ……<emoji=heart04>」
line = "「おらっ、んっ、はぁっ<emoji=heart04>　オマエも腰振れよっ……<emoji=heart04>　つかもっとおっぱい吸えっ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「どーせもう挿れちまってんだっ……<emoji=heart04>　一緒に楽しんじまおうぜっ<emoji=heart04>　オマエもアタシのま○こ、んはぁぁ、もっと味わいてえんだろっ？」
line = "「どーせもう挿れちまってんだっ……<emoji=heart04>　一緒に楽しんじまおうぜっ<emoji=heart04>　オマエもアタシのま○こ、んはぁぁ、もっと味わいてえんだろっ？」"

[[dialogue]]
speaker = "unk"
# 窒息してしまいそうなほど胸を顔に押しつけられ、否応なしに乳首を吸わされる。
line = "窒息してしまいそうなほど胸を顔に押しつけられ、否応なしに乳首を吸わされる。"

[[dialogue]]
speaker = "unk"
# 火照ったおっぱいの感触が顔いっぱいに密着して頭がクラクラしてきた。
line = "火照ったおっぱいの感触が顔いっぱいに密着して頭がクラクラしてきた。"

[[dialogue]]
speaker = "キサナ"
# 「んんっ……<emoji=heart04>　そうだぁ……<emoji=heart04>　ママのおっぱいみたいに、ちゅうちゅう吸っていいぞ……<emoji=heart04>　んぁっ、あっ、はぁぁっ……<emoji=heart04>　気持ち、いいじゃねえかっ……<emoji=heart04>」
line = "「んんっ……<emoji=heart04>　そうだぁ……<emoji=heart04>　ママのおっぱいみたいに、ちゅうちゅう吸っていいぞ……<emoji=heart04>　んぁっ、あっ、はぁぁっ……<emoji=heart04>　気持ち、いいじゃねえかっ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「よほど女の乳に飢えてたのか？　チ○ポがさらにバッキバキになってきてるぜっ……<emoji=heart04>　それともセックスもずっとお預けにされてたってか？」
line = "「よほど女の乳に飢えてたのか？　チ○ポがさらにバッキバキになってきてるぜっ……<emoji=heart04>　それともセックスもずっとお預けにされてたってか？」"

[[dialogue]]
speaker = "キサナ"
# 「あんだけ女がいんのに、んっ、はぁっ、オマエも可哀想なヤツだなっ……<emoji=heart04>　アタシの裸くれえでこんなに発情しちまうってのによぉ……<emoji=heart04>」
line = "「あんだけ女がいんのに、んっ、はぁっ、オマエも可哀想なヤツだなっ……<emoji=heart04>　アタシの裸くれえでこんなに発情しちまうってのによぉ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「おらっ、もっと気持ち良くしてやんよっ……<emoji=heart04>　どーやら先っぽをグリグリギュウギュウされんのが好きらしいしなぁ……<emoji=heart04>」
line = "「おらっ、もっと気持ち良くしてやんよっ……<emoji=heart04>　どーやら先っぽをグリグリギュウギュウされんのが好きらしいしなぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 敏感な先端を肉厚な膣で挟み込まれて、甘く痺れるような快楽が駆け上る。
line = "敏感な先端を肉厚な膣で挟み込まれて、甘く痺れるような快楽が駆け上る。"

[[dialogue]]
speaker = "unk"
# 乳首もさっきより硬くなっていて、そのコリコリとした舌触りが情欲をくすぐって──
line = "乳首もさっきより硬くなっていて、そのコリコリとした舌触りが情欲をくすぐって──"

[[dialogue]]
speaker = "キサナ"
# 「あっ、あっ、あっ……<emoji=heart04>　調子出てきたじゃねえかっ……<emoji=heart04>　気付いてるかぁ、オマエ、自分で腰揺らしてるぜっ……<emoji=heart04>」
line = "「あっ、あっ、あっ……<emoji=heart04>　調子出てきたじゃねえかっ……<emoji=heart04>　気付いてるかぁ、オマエ、自分で腰揺らしてるぜっ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「悪く、ねえっ……<emoji=heart04>　セックスって気持ちいいなぁ、魔王っ……<emoji=heart04>　ま○こがトロトロになってきやがるっ……<emoji=heart04>」
line = "「悪く、ねえっ……<emoji=heart04>　セックスって気持ちいいなぁ、魔王っ……<emoji=heart04>　ま○こがトロトロになってきやがるっ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「なぁ魔王……<emoji=heart04>　ギブアンドテイクと行こうぜ……<emoji=heart04>　たまにこうしてヤらしてやるからよ<emoji=heart04>　これからもアタシを見逃せよ<emoji=heart04>」
line = "「なぁ魔王……<emoji=heart04>　ギブアンドテイクと行こうぜ……<emoji=heart04>　たまにこうしてヤらしてやるからよ<emoji=heart04>　これからもアタシを見逃せよ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 誘惑するようにキサナが肉棒を丸ごと咥え込み、柔らかくて大きなおっぱいをむぎゅっと胸板に押し付けてくる。
line = "誘惑するようにキサナが肉棒を丸ごと咥え込み、柔らかくて大きなおっぱいをむぎゅっと胸板に押し付けてくる。"

[[dialogue]]
speaker = "unk"
# ともすれば性欲と快楽に溺れてしまいそうになって──
line = "ともすれば性欲と快楽に溺れてしまいそうになって──"

[[dialogue]]
speaker = "キサナ"
# 「我慢すんなよっ……<emoji=heart04>　こっそり会って、ヤって、別れるだけじゃねえかっ……<emoji=heart04>」
line = "「我慢すんなよっ……<emoji=heart04>　こっそり会って、ヤって、別れるだけじゃねえかっ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「お仲間はヤらしてくんねえんだろっ<emoji=heart04>　けどアタシなら、いくらでもヤらしてやるぜっ……<emoji=heart04>」
line = "「お仲間はヤらしてくんねえんだろっ<emoji=heart04>　けどアタシなら、いくらでもヤらしてやるぜっ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「こーしてアツアツま○こでチ○ポ扱いてやったりよぉ……<emoji=heart04>　オマエの大好きなおっぱい吸わせてやったりさぁ……<emoji=heart04>」
line = "「こーしてアツアツま○こでチ○ポ扱いてやったりよぉ……<emoji=heart04>　オマエの大好きなおっぱい吸わせてやったりさぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 敵の誘いに乗るわけにはいかない──そう思っているはずなのに、キサナの声が蠱惑的に響く。
line = "敵の誘いに乗るわけにはいかない──そう思っているはずなのに、キサナの声が蠱惑的に響く。"

[[dialogue]]
speaker = "キサナ"
# 「まぁオマエが乗るか乗らねえかはどーでもいいがっ……<emoji=heart04>　アタシは、オマエのチ○ポ、たっぷり楽しませてもらうぜっ……<emoji=heart04>」
line = "「まぁオマエが乗るか乗らねえかはどーでもいいがっ……<emoji=heart04>　アタシは、オマエのチ○ポ、たっぷり楽しませてもらうぜっ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「あぁああんっ<emoji=heart04>　あっ<emoji=heart04>　はぁっ<emoji=heart04>　あっ、あっ、あっ、ああぁあああんんっっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あぁああんっ<emoji=heart04>　あっ<emoji=heart04>　はぁっ<emoji=heart04>　あっ、あっ、あっ、ああぁあああんんっっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「やっぱ、あっ、あっ<emoji=heart04>　いっぱい腰振ったほうが、気持ちいいなっ<emoji=heart04>」
line = "「やっぱ、あっ、あっ<emoji=heart04>　いっぱい腰振ったほうが、気持ちいいなっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「チ○ポ、めちゃくちゃ擦れるっ<emoji=heart04>　先っぽ大きくて、硬くて、ゾクゾクするっ……<emoji=heart04>　腰とまんねぇっ……<emoji=heart04>」
line = "「チ○ポ、めちゃくちゃ擦れるっ<emoji=heart04>　先っぽ大きくて、硬くて、ゾクゾクするっ……<emoji=heart04>　腰とまんねぇっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# まるで発情期の獣のようにキサナが腰を振ってくる。
line = "まるで発情期の獣のようにキサナが腰を振ってくる。"

[[dialogue]]
speaker = "unk"
# キサナの腰が動く度に理性が削られていくようで……
line = "キサナの腰が動く度に理性が削られていくようで……"

[[dialogue]]
speaker = "キサナ"
# 「はぁっ、あっ<emoji=heart04>　オマエも気持ち良さそうじゃねえか、魔王っ……<emoji=heart04>　実はアタシら、あっ、あっ、体の相性いいんじゃねえかっ……<emoji=heart04>」
line = "「はぁっ、あっ<emoji=heart04>　オマエも気持ち良さそうじゃねえか、魔王っ……<emoji=heart04>　実はアタシら、あっ、あっ、体の相性いいんじゃねえかっ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「そっちからもガンガン突き上げてきていいんだぜっ<emoji=heart04>　ふぁっ、あっ、はぁんっ<emoji=heart04>　難しいコト考えずに溺れちまえよっ<emoji=heart04>」
line = "「そっちからもガンガン突き上げてきていいんだぜっ<emoji=heart04>　ふぁっ、あっ、はぁんっ<emoji=heart04>　難しいコト考えずに溺れちまえよっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「アタシのま○こ、気持ちいいんだろっ<emoji=heart04>　おっぱい揉みくちゃにして、舐め回してえんだろっ<emoji=heart04>」
line = "「アタシのま○こ、気持ちいいんだろっ<emoji=heart04>　おっぱい揉みくちゃにして、舐め回してえんだろっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「欲望に素直になっちまえっ<emoji=heart04>　おらっ、ゴシゴシしてやんよっ<emoji=heart04>　んっ、んっ、んっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「欲望に素直になっちまえっ<emoji=heart04>　おらっ、ゴシゴシしてやんよっ<emoji=heart04>　んっ、んっ、んっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「はぁっ、はっ……<emoji=heart04>　まだ素直にならねえか……強情だな……それじゃ──んちゅるっ<emoji=heart04>」
line = "「はぁっ、はっ……<emoji=heart04>　まだ素直にならねえか……強情だな……それじゃ──んちゅるっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「──！？」
line = "「──！？」"

[[dialogue]]
speaker = "unk"
# キサナが俺の唇を奪い、そのまま力ずくで舌を差し入れてくる。
line = "キサナが俺の唇を奪い、そのまま力ずくで舌を差し入れてくる。"

[[dialogue]]
speaker = "キサナ"
# 「んんっ……んちゅるっ、ちゅるちゅる……れぇる、へるへるっ、へろんっ<emoji=heart04>」
line = "「んんっ……んちゅるっ、ちゅるちゅる……れぇる、へるへるっ、へろんっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# キサナの柔らかくて熱い舌が俺の口内を蹂躙し、めちゃくちゃに舐め回す。
line = "キサナの柔らかくて熱い舌が俺の口内を蹂躙し、めちゃくちゃに舐め回す。"

[[dialogue]]
speaker = "キサナ"
# 「んんちゅ、ちゅるっ、ちゅぱっ……じゅるっ……じゅるじゅる<emoji=heart04>　れぇろ、へろへろ……んちゅるるっ<emoji=heart04>」
line = "「んんちゅ、ちゅるっ、ちゅぱっ……じゅるっ……じゅるじゅる<emoji=heart04>　れぇろ、へろへろ……んちゅるるっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 舌を、歯を、頬の裏までを舐められ、思考がドロドロに溶けていく。
line = "舌を、歯を、頬の裏までを舐められ、思考がドロドロに溶けていく。"

[[dialogue]]
speaker = "unk"
# もう快楽に抗うことはできなくて、半ば無意識にキスに応える。
line = "もう快楽に抗うことはできなくて、半ば無意識にキスに応える。"

[[dialogue]]
speaker = "キサナ"
# 「んんっ……！？　そうだ、オマエも舐め返してこい……んちゅっ、ちゅるっ<emoji=heart04>　ちゅるれろ、へぇろ、れろ<emoji=heart04>」
line = "「んんっ……！？　そうだ、オマエも舐め返してこい……んちゅっ、ちゅるっ<emoji=heart04>　ちゅるれろ、へぇろ、れろ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「ちゅるっ、ちゅりゅれろ、じゅるるるっ<emoji=heart04>　んふっ、はぁ……れろちゅぱっ、ちゅぅっ、じゅる、じゅるるんっ<emoji=heart04>」
line = "「ちゅるっ、ちゅりゅれろ、じゅるるるっ<emoji=heart04>　んふっ、はぁ……れろちゅぱっ、ちゅぅっ、じゅる、じゅるるんっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 互いに舌を絡め合い、唾液が混ざり合う、さながら恋人同士のような激しいキス。
line = "互いに舌を絡め合い、唾液が混ざり合う、さながら恋人同士のような激しいキス。"

[[dialogue]]
speaker = "unk"
# 理性の崩壊になおも歯止めはかからず、力任せに突き上げた。
line = "理性の崩壊になおも歯止めはかからず、力任せに突き上げた。"

[[dialogue]]
speaker = "キサナ"
# 「ふやあああぁっ<emoji=heart04><emoji=heart04>　くぁっ、あっ、はぁっ、あぁっ<emoji=heart04>　そーだぁっ<emoji=heart04>　もっと振れぇっ<emoji=heart04>　本能のまま腰振りゃあいいんだっ<emoji=heart04>」
line = "「ふやあああぁっ<emoji=heart04><emoji=heart04>　くぁっ、あっ、はぁっ、あぁっ<emoji=heart04>　そーだぁっ<emoji=heart04>　もっと振れぇっ<emoji=heart04>　本能のまま腰振りゃあいいんだっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「アタシもその方が、あぁんっ、気持ちいいっ<emoji=heart04>　オマエがガンガン、突いてくる方がっ、あっ、あっ、濡れてくるっ<emoji=heart04>」
line = "「アタシもその方が、あぁんっ、気持ちいいっ<emoji=heart04>　オマエがガンガン、突いてくる方がっ、あっ、あっ、濡れてくるっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「どーせ誰も見てねえんだっ<emoji=heart04>　楽しんじまおうぜっ<emoji=heart04>　アタシと、ふぁっ、あっ、はぁっ、一緒によぉっ<emoji=heart04>」
line = "「どーせ誰も見てねえんだっ<emoji=heart04>　楽しんじまおうぜっ<emoji=heart04>　アタシと、ふぁっ、あっ、はぁっ、一緒によぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 敵味方も場所も忘れて、男と女の行為に没頭する。
line = "敵味方も場所も忘れて、男と女の行為に没頭する。"

[[dialogue]]
speaker = "unk"
# もう止まらない。キサナの肉感的なお尻を掴みながら、しゃにむに欲望を打ち付けた。
line = "もう止まらない。キサナの肉感的なお尻を掴みながら、しゃにむに欲望を打ち付けた。"

[[dialogue]]
speaker = "キサナ"
# 「んはぁっ、あぁあんっ、あっ、はぁっ、ふぁあああんっっ<emoji=heart04>」
line = "「んはぁっ、あぁあんっ、あっ、はぁっ、ふぁあああんっっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「奥までズンズン来てぇっ……<emoji=heart04>　もうケダモノじゃねえかっ<emoji=heart04>　だけど気持ち、いいっ<emoji=heart04>　　あっ、あっ、あっ、あぁあんっ<emoji=heart04>　最高に気持ちいいぜっ<emoji=heart04>」
line = "「奥までズンズン来てぇっ……<emoji=heart04>　もうケダモノじゃねえかっ<emoji=heart04>　だけど気持ち、いいっ<emoji=heart04>　　あっ、あっ、あっ、あぁあんっ<emoji=heart04>　最高に気持ちいいぜっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「チ○ポ、ビクビクって、激しくなってきやがったっ<emoji=heart04>　腹ん中、アチいっ<emoji=heart04>　んぁっ、はぁあんっ<emoji=heart04>　ドクンドクン脈打ってやがるっ<emoji=heart04>」
line = "「チ○ポ、ビクビクって、激しくなってきやがったっ<emoji=heart04>　腹ん中、アチいっ<emoji=heart04>　んぁっ、はぁあんっ<emoji=heart04>　ドクンドクン脈打ってやがるっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「おらっ、我慢せずに出しちまえよっ<emoji=heart04>　しゃせーしてえんだろっ<emoji=heart04>　アタシの体で気持ち良くイっちまえっ<emoji=heart04>」
line = "「おらっ、我慢せずに出しちまえよっ<emoji=heart04>　しゃせーしてえんだろっ<emoji=heart04>　アタシの体で気持ち良くイっちまえっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「アタシもイクっ、はぁはぁっ、イっちまっ、あぁああんっっ<emoji=heart04><emoji=heart04><emoji=heart04>　やべぇっ、ああっ、あぁあああっっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「アタシもイクっ、はぁはぁっ、イっちまっ、あぁああんっっ<emoji=heart04><emoji=heart04><emoji=heart04>　やべぇっ、ああっ、あぁあああっっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 今にも絶頂しそうなほど大声で喘ぐキサナ。
line = "今にも絶頂しそうなほど大声で喘ぐキサナ。"

[[dialogue]]
speaker = "unk"
# その蕩けた顔がとてつもなく女の子っぽくて、そのかわいさにペニスが滾ってしまう。
line = "その蕩けた顔がとてつもなく女の子っぽくて、そのかわいさにペニスが滾ってしまう。"

[[dialogue]]
speaker = "キサナ"
# 「くあぁっ、あんっ<emoji=heart04>　なんだ、その顔っ……ちょっ、見んなっ<emoji=heart04>　あぁんっ<emoji=heart04>　今アタシの顔見んなぁっ<emoji=heart04>」
line = "「くあぁっ、あんっ<emoji=heart04>　なんだ、その顔っ……ちょっ、見んなっ<emoji=heart04>　あぁんっ<emoji=heart04>　今アタシの顔見んなぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「見るならオマエも見せろっ<emoji=heart04>　アタシのま○こで感じてる情けねえ顔っ、しっかり見せろっ<emoji=heart04>」
line = "「見るならオマエも見せろっ<emoji=heart04>　アタシのま○こで感じてる情けねえ顔っ、しっかり見せろっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 互いに顔を見つたまま、吐息が交わるような距離で腰を振り、２人してセックスの快感に溺れ続ける。
line = "互いに顔を見つたまま、吐息が交わるような距離で腰を振り、２人してセックスの快感に溺れ続ける。"

[[dialogue]]
speaker = "キサナ"
# 「んはぁぁっ<emoji=heart04>　熱いっ<emoji=heart04>　オマエのチ○ポも、吐息もっ、顔もっ、アタシのま○こもっ<emoji=heart04>」
line = "「んはぁぁっ<emoji=heart04>　熱いっ<emoji=heart04>　オマエのチ○ポも、吐息もっ、顔もっ、アタシのま○こもっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「なんだこれっ、ああああっ<emoji=heart04>　イっちまうっ、くぁぁっ、イクっ、イクイクイクっっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「なんだこれっ、ああああっ<emoji=heart04>　イっちまうっ、くぁぁっ、イクっ、イクイクイクっっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ぎゅうぅっとキサナの膣が一気に締まり、発情しきった顔で俺のペニスを貪る。
line = "ぎゅうぅっとキサナの膣が一気に締まり、発情しきった顔で俺のペニスを貪る。"

[[dialogue]]
speaker = "unk"
# 凶暴は彼女の、今まで見たことないエッチな顔を見て俺は──
line = "凶暴は彼女の、今まで見たことないエッチな顔を見て俺は──"

[[dialogue]]
speaker = "キサナ"
# 「頭ん中、ぐちゃぐちゃになってっ<emoji=heart04>　はあぁっ<emoji=heart04>　あっ<emoji=heart04>　チ○ポ、ビクビクしてっ……ふあっ──あっ──あっ<emoji=heart04>」
line = "「頭ん中、ぐちゃぐちゃになってっ<emoji=heart04>　はあぁっ<emoji=heart04>　あっ<emoji=heart04>　チ○ポ、ビクビクしてっ……ふあっ──あっ──あっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「ま○こが、ぁっ、ぁっ<emoji=heart04>　お腹の奥、キュンキュンしてっ<emoji=heart04>　イクっ、イクっ、イクっ──イッくぅ～～～っ<emoji=heart04><emoji=heart04>」
line = "「ま○こが、ぁっ、ぁっ<emoji=heart04>　お腹の奥、キュンキュンしてっ<emoji=heart04>　イクっ、イクっ、イクっ──イッくぅ～～～っ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「んあっ、あっ──ふあぁぁあああああああんんんんんっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「んあっ、あっ──ふあぁぁあああああああんんんんんっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 何も考えられなくなって、キサナの膣内にたまらず精をぶちまけた。
line = "何も考えられなくなって、キサナの膣内にたまらず精をぶちまけた。"

[[dialogue]]
speaker = "キサナ"
# 「んぁぁあっ、熱っ<emoji=heart04>　イクっ<emoji=heart04>　んあああっっ<emoji=heart04>　腹ん中、あついぃぃっ<emoji=heart04>」
line = "「んぁぁあっ、熱っ<emoji=heart04>　イクっ<emoji=heart04>　んあああっっ<emoji=heart04>　腹ん中、あついぃぃっ<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「めちゃくちゃ、あぁあんっ、気持ちいいっ<emoji=heart04>　やべぇっ、んんんんっ<emoji=heart04>　めちゃくちゃ、ま○こ締まっちまうっ……<emoji=heart04>」
line = "「めちゃくちゃ、あぁあんっ、気持ちいいっ<emoji=heart04>　やべぇっ、んんんんっ<emoji=heart04>　めちゃくちゃ、ま○こ締まっちまうっ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「出せっ<emoji=heart04>　もっと出せっっ<emoji=heart04><emoji=heart04>　オマエのせーしっ、あぁああんっ、もっとアタシにくれよっっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「出せっ<emoji=heart04>　もっと出せっっ<emoji=heart04><emoji=heart04>　オマエのせーしっ、あぁああんっ、もっとアタシにくれよっっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# キサナが射精中の亀頭に子宮口を密着させ、敏感になっている先端を貪欲に吸ってくる。
line = "キサナが射精中の亀頭に子宮口を密着させ、敏感になっている先端を貪欲に吸ってくる。"

[[dialogue]]
speaker = "unk"
# その蕩けるような快楽に、また──
line = "その蕩けるような快楽に、また──"

[[dialogue]]
speaker = "キサナ"
# 「うああぁ～～～っ<emoji=heart04><emoji=heart04>　またビューッて、奥にっ……んんっ──ん～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「うああぁ～～～っ<emoji=heart04><emoji=heart04>　またビューッて、奥にっ……んんっ──ん～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「んぁぁぁ……<emoji=heart04>　はぁーっ、はぁーっ、んはぁぁーっ……<emoji=heart04>」
line = "「んぁぁぁ……<emoji=heart04>　はぁーっ、はぁーっ、んはぁぁーっ……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「こりゃあ水浴びし直しだな……<emoji=heart04>　ま○こから溢れちまうほど出しやがって……<emoji=heart04>」
line = "「こりゃあ水浴びし直しだな……<emoji=heart04>　ま○こから溢れちまうほど出しやがって……<emoji=heart04>」"

[[dialogue]]
speaker = "キサナ"
# 「でも、はぁはぁ、セックスも悪くねえじゃねえか……<emoji=heart04>　マジで秘密の関係っての続けてみっかぁ……？」
line = "「でも、はぁはぁ、セックスも悪くねえじゃねえか……<emoji=heart04>　マジで秘密の関係っての続けてみっかぁ……？」"

[[dialogue]]
speaker = "unk"
# 先程のかわいらしいキサナの姿を思い出して一瞬考えてしまう。
line = "先程のかわいらしいキサナの姿を思い出して一瞬考えてしまう。"

[[dialogue]]
speaker = "キサナ"
# 「って、冗談に決まってんだろ。真に受けんなよ、敵同士だぞアタシらは。……なんだその顔。本気で残念そうにすんなよ」
line = "「って、冗談に決まってんだろ。真に受けんなよ、敵同士だぞアタシらは。……なんだその顔。本気で残念そうにすんなよ」"

[[dialogue]]
speaker = "unk"
# 呆れたような、照れたような顔が俺の胸をさらに疼かせる。
line = "呆れたような、照れたような顔が俺の胸をさらに疼かせる。"

[[dialogue]]
speaker = "キサナ"
# 「アタシ、コラプサーの前はマフィアにいた……ってのは言ったっけか」
line = "「アタシ、コラプサーの前はマフィアにいた……ってのは言ったっけか」"

[[dialogue]]
speaker = "キサナ"
# 「アタシは抗争ばっかりだったが、場合によっちゃ娼婦か愛人にでもさせられてたんだろうなぁ……」
line = "「アタシは抗争ばっかりだったが、場合によっちゃ娼婦か愛人にでもさせられてたんだろうなぁ……」"

[[dialogue]]
speaker = "キサナ"
# 「セックスなんかバカかケダモノのやることだと思ってたけどよ、オマエとヤったのは……まぁ後悔はしてねえよ」
line = "「セックスなんかバカかケダモノのやることだと思ってたけどよ、オマエとヤったのは……まぁ後悔はしてねえよ」"

[[dialogue]]
speaker = "キサナ"
# 「次いつ出くわすかわかんねえし、このままもう１回ヤろうぜ。オマエもまだまだ溜まってんだろ？」
line = "「次いつ出くわすかわかんねえし、このままもう１回ヤろうぜ。オマエもまだまだ溜まってんだろ？」"

[[dialogue]]
speaker = "キサナ"
# 「とっととおっ勃てろよ。まさか一度で枯れ果てたとか言わねえよな？」
line = "「とっととおっ勃てろよ。まさか一度で枯れ果てたとか言わねえよな？」"

[[dialogue]]
speaker = "unk"
# そうして俺とキサナは獣になって、夜更けまで交わり続けたのだった──
line = "そうして俺とキサナは獣になって、夜更けまで交わり続けたのだった──"
