[[dialogue]]
speaker = "unk"
# 第２話,フランスから来た麗人,P
line = "第２話,フランスから来た麗人,P"

[[dialogue]]
speaker = "エリス"
# 「こんにちは。先日お会いして以来ですね。星徒会の業務には慣れましたか？」
line = "「こんにちは。先日お会いして以来ですね。星徒会の業務には慣れましたか？」"

[[dialogue]]
speaker = "unk"
# けっこう大変かも……
line = "けっこう大変かも……"

[[dialogue]]
speaker = "エリス"
# 「あはは……ご心労お察しします」
line = "「あはは……ご心労お察しします」"

[[dialogue]]
speaker = "エリス"
# 「せっかくですからご一緒しても？　……ありがとうございます」
line = "「せっかくですからご一緒しても？　……ありがとうございます」"

[[dialogue]]
speaker = "エリス"
# 「飲み物は……カフェオレにします。好きなのでよく飲んでいるんですよ」
line = "「飲み物は……カフェオレにします。好きなのでよく飲んでいるんですよ」"

[[dialogue]]
speaker = "エリス"
# 「あ、会長さんもカフェオレにしますか。じゃあお揃いですね、ふふっ」
line = "「あ、会長さんもカフェオレにしますか。じゃあお揃いですね、ふふっ」"

[[dialogue]]
speaker = "unk"
# エリスはどうして風紀委員に？
line = "エリスはどうして風紀委員に？"

[[dialogue]]
speaker = "エリス"
# 「そうですね……もちろんリヨンでの経験もありますが、きっと父の影響だと思います」
line = "「そうですね……もちろんリヨンでの経験もありますが、きっと父の影響だと思います」"

[[dialogue]]
speaker = "エリス"
# 「父はフランスの貴族の末裔で、代々受け継いできた事業と資産を持っています。ですから私も裕福な家庭で育ちました」
line = "「父はフランスの貴族の末裔で、代々受け継いできた事業と資産を持っています。ですから私も裕福な家庭で育ちました」"

[[dialogue]]
speaker = "エリス"
# 「しかし父は恵まれた環境をただ享受することを良しとせず、よく幼い私に言い聞かせました。富や地位、力には責務が伴うと」
line = "「しかし父は恵まれた環境をただ享受することを良しとせず、よく幼い私に言い聞かせました。富や地位、力には責務が伴うと」"

[[dialogue]]
speaker = "エリス"
# 「いわゆるノブレス・オブリージュです。星騎士になることを選んだのもそのためです」
line = "「いわゆるノブレス・オブリージュです。星騎士になることを選んだのもそのためです」"

[[dialogue]]
speaker = "エリス"
# 「そして父はこうも言っていました。力ある者が責務と責任を忘れて横暴に走れば、力なき者を蹂躙し、いずれ己の身も滅ぼす……と」
line = "「そして父はこうも言っていました。力ある者が責務と責任を忘れて横暴に走れば、力なき者を蹂躙し、いずれ己の身も滅ぼす……と」"

[[dialogue]]
speaker = "エリス"
# 「例えば、もし星騎士が星術で人々に危害を加えるとどうなるか」
line = "「例えば、もし星騎士が星術で人々に危害を加えるとどうなるか」"

[[dialogue]]
speaker = "エリス"
# 「そんな暴虐が跋扈すれば、星騎士と人々との間に溝が生まれ、私たちは今のような支援を受けられず戦うこともままならなくなるでしょう」
line = "「そんな暴虐が跋扈すれば、星騎士と人々との間に溝が生まれ、私たちは今のような支援を受けられず戦うこともままならなくなるでしょう」"

[[dialogue]]
speaker = "エリス"
# 「だからたとえ煙たがられても、風紀委員として規律を守ることには意義があると思うんです」
line = "「だからたとえ煙たがられても、風紀委員として規律を守ることには意義があると思うんです」"

[[dialogue]]
speaker = "エリス"
# 「……なんて、また堅苦しい話をしてしまいましたね。お恥ずかしい」
line = "「……なんて、また堅苦しい話をしてしまいましたね。お恥ずかしい」"

[[dialogue]]
speaker = "unk"
# 素晴らしい志だと思う
line = "素晴らしい志だと思う"

[[dialogue]]
speaker = "エリス"
# 「そ、そうでしょうか……？　そう言われるとその、少々こそばゆいですね……」
line = "「そ、そうでしょうか……？　そう言われるとその、少々こそばゆいですね……」"

[[dialogue]]
speaker = "エリス"
# 「そうです、せっかくですからケーキも頼みましょう！」
line = "「そうです、せっかくですからケーキも頼みましょう！」"

[[dialogue]]
speaker = "unk"
# （あ、ごまかした）
line = "（あ、ごまかした）"

[[dialogue]]
speaker = "エリス"
# 「私はミルクレープにします」
line = "「私はミルクレープにします」"

[[dialogue]]
speaker = "エリス"
# 「ミルクレープはこちらに来て初めて食べたのですが、お気に入りなんです。クレープはフランスが発祥なのに不思議なものですね」
line = "「ミルクレープはこちらに来て初めて食べたのですが、お気に入りなんです。クレープはフランスが発祥なのに不思議なものですね」"

[[dialogue]]
speaker = "エリス"
# 「……おや」
line = "「……おや」"

[[dialogue]]
speaker = "アニュラス"
# 「普通のコーヒーとエスプレッソはどう違うのだ？　いや、砂糖とミルクはいらない。そのままでいい」
line = "「普通のコーヒーとエスプレッソはどう違うのだ？　いや、砂糖とミルクはいらない。そのままでいい」"

[[dialogue]]
speaker = "ヨミ"
# 「か、かしこまりました……」
line = "「か、かしこまりました……」"

[[dialogue]]
speaker = "アニュラス"
# 「なんだ、お前か。あと新星の会長もいるな」
line = "「なんだ、お前か。あと新星の会長もいるな」"

[[dialogue]]
speaker = "エリス"
# 「私たち、流星学園入学以前からの知り合いでして」
line = "「私たち、流星学園入学以前からの知り合いでして」"

[[dialogue]]
speaker = "エリス"
# 「リヨンでモンスターにやられそうになった時、私を助けてくれたのがアニュラスなんです」
line = "「リヨンでモンスターにやられそうになった時、私を助けてくれたのがアニュラスなんです」"

[[dialogue]]
speaker = "エリス"
# 「あの時、現九浄家当主の九浄ヘレナさんがヨーロッパを巡遊していて、武者修行と護衛を兼ねてアニュラスが同行していたんです」
line = "「あの時、現九浄家当主の九浄ヘレナさんがヨーロッパを巡遊していて、武者修行と護衛を兼ねてアニュラスが同行していたんです」"

[[dialogue]]
speaker = "アニュラス"
# 「そんなこともあったか」
line = "「そんなこともあったか」"

[[dialogue]]
speaker = "エリス"
# 「あの時は仮面は付けていませんでしたけど。素顔を見せてくれないのは少し寂しいです」
line = "「あの時は仮面は付けていませんでしたけど。素顔を見せてくれないのは少し寂しいです」"

[[dialogue]]
speaker = "エリス"
# 「そのノート……アニュラスは勉強ですか？　私の方が上級生ですし、わからないところがあれば教えましょうか」
line = "「そのノート……アニュラスは勉強ですか？　私の方が上級生ですし、わからないところがあれば教えましょうか」"

[[dialogue]]
speaker = "アニュラス"
# 「必要ない。自分でできる」
line = "「必要ない。自分でできる」"

[[dialogue]]
speaker = "エリス"
# 「この後、模擬戦でお手合わせお願いしたくて。だから早く終わらせてほしいんですよ」
line = "「この後、模擬戦でお手合わせお願いしたくて。だから早く終わらせてほしいんですよ」"

[[dialogue]]
speaker = "アニュラス"
# 「……そういうことならいいだろう。手伝わせてやる」
line = "「……そういうことならいいだろう。手伝わせてやる」"

[[dialogue]]
speaker = "ヨミ"
# 「お待たせしました。カフェオレと……エスプレッソです」
line = "「お待たせしました。カフェオレと……エスプレッソです」"

[[dialogue]]
speaker = "アニュラス"
# 「ああ。ズズ──ッ！？」
line = "「ああ。ズズ──ッ！？」"

[[dialogue]]
speaker = "エリス"
# （とても苦そうな顔をしていますね……仮面越しでもわかります……）
line = "（とても苦そうな顔をしていますね……仮面越しでもわかります……）"

[[dialogue]]
speaker = "エリス"
# 「私のカフェオレと交換しませんか？」
line = "「私のカフェオレと交換しませんか？」"

[[dialogue]]
speaker = "アニュラス"
# 「問題ない。想定通りだ」
line = "「問題ない。想定通りだ」"

[[dialogue]]
speaker = "エリス"
# 「いえ、なんとなくエスプレッソが飲みたい気分なんです。いけませんか？」
line = "「いえ、なんとなくエスプレッソが飲みたい気分なんです。いけませんか？」"

[[dialogue]]
speaker = "アニュラス"
# 「仕方ない……ほら」
line = "「仕方ない……ほら」"

[[dialogue]]
speaker = "エリス"
# 「ふふっ、ありがとうございます」
line = "「ふふっ、ありがとうございます」"

[[dialogue]]
speaker = "unk"
# （うまく操っている……）
line = "（うまく操っている……）"

[[dialogue]]
speaker = "エリス"
# 「この問題は両辺を１０倍すると計算しやすくなりますよ」
line = "「この問題は両辺を１０倍すると計算しやすくなりますよ」"

[[dialogue]]
speaker = "アニュラス"
# 「わ、わかっている。今やろうとしていたところだ。……両辺？　りょうへん？？？」
line = "「わ、わかっている。今やろうとしていたところだ。……両辺？　りょうへん？？？」"

[[dialogue]]
speaker = "エリス"
# 「ちょっとペンを貸してください。ここをこうして……こちらも……」
line = "「ちょっとペンを貸してください。ここをこうして……こちらも……」"

[[dialogue]]
speaker = "アニュラス"
# 「むむ、むむむ？　…………そういうことか！」
line = "「むむ、むむむ？　…………そういうことか！」"

[[dialogue]]
speaker = "アニュラス"
# 「ハッ──いや言われなくとも理解していたぞ。理解していたからな！」
line = "「ハッ──いや言われなくとも理解していたぞ。理解していたからな！」"

[[dialogue]]
speaker = "エリス"
# 「ええ、承知していますよ。その調子で解いていきましょう」
line = "「ええ、承知していますよ。その調子で解いていきましょう」"
