[[dialogue]]
speaker = "unk"
# 第２話,正義の在処,P
line = "第２話,正義の在処,P"

[[dialogue]]
speaker = "unk"
# 放課後、コハルコはトレーニング施設にいることが多く、星徒会の仕事がない日は俺も自然と足が向く。今日は何故かレイラも一緒にいた。
line = "放課後、コハルコはトレーニング施設にいることが多く、星徒会の仕事がない日は俺も自然と足が向く。今日は何故かレイラも一緒にいた。"

[[dialogue]]
speaker = "コハルコ"
# 「会長さん、シミュレーターの調整に付き合ってもらっていいかな？　この前のフライドチキンモンスターも一応登録しておきたくて」
line = "「会長さん、シミュレーターの調整に付き合ってもらっていいかな？　この前のフライドチキンモンスターも一応登録しておきたくて」"

[[dialogue]]
speaker = "unk"
# もちろん
line = "もちろん"

[[dialogue]]
speaker = "unk"
# 何かの拍子で再び現れないとも限らない。対策できるならしておくべきだろう。
line = "何かの拍子で再び現れないとも限らない。対策できるならしておくべきだろう。"

[[dialogue]]
speaker = "unk"
# ……ただコハルコと一緒にいたいだけってのもあるけど。
line = "……ただコハルコと一緒にいたいだけってのもあるけど。"

[[dialogue]]
speaker = "コハルコ"
# 「うん、ありがとう」
line = "「うん、ありがとう」"

[[dialogue]]
speaker = "コハルコ"
# 「で、レイラは何しに来たの？」
line = "「で、レイラは何しに来たの？」"

[[dialogue]]
speaker = "レイラ"
# 「今日はイングリットがイニシュさんと訓練なので、羽を伸ばしに来ました」
line = "「今日はイングリットがイニシュさんと訓練なので、羽を伸ばしに来ました」"

[[dialogue]]
speaker = "コハルコ"
# 「羽を伸ばしに他所ん家に来るんじゃないの。私は仕事中だから、いてもいいけど邪魔はしないでよね」
line = "「羽を伸ばしに他所ん家に来るんじゃないの。私は仕事中だから、いてもいいけど邪魔はしないでよね」"

[[dialogue]]
speaker = "レイラ"
# 「はーい、コハタン先輩」
line = "「はーい、コハタン先輩」"

[[dialogue]]
speaker = "コハルコ"
# 「コハタンて誰。というかレイラが私の後輩だったことないでしょ」
line = "「コハタンて誰。というかレイラが私の後輩だったことないでしょ」"

[[dialogue]]
speaker = "unk"
# かつては敵だったコラプサーも今では味方だ。特にレイラはコハルコと話が合うらしく、用もないのに訪ねてくる。
line = "かつては敵だったコラプサーも今では味方だ。特にレイラはコハルコと話が合うらしく、用もないのに訪ねてくる。"

[[dialogue]]
speaker = "コハルコ"
# 「じゃあそろそろ始めようか」
line = "「じゃあそろそろ始めようか」"

[[dialogue]]
speaker = "コハルコ"
# 「フライドチキンモンスターを出してみるから、挙動におかしなところがあったら教えてね」
line = "「フライドチキンモンスターを出してみるから、挙動におかしなところがあったら教えてね」"

[[dialogue]]
speaker = "モンスター"
# 「チキチキチー！」
line = "「チキチキチー！」"

[[dialogue]]
speaker = "コハルコ"
# 「うーん……見た目や動きは問題なさそうかな。今度は戦ってみてレビューお願いね」
line = "「うーん……見た目や動きは問題なさそうかな。今度は戦ってみてレビューお願いね」"

[[dialogue]]
speaker = "コハルコ"
# 「お疲れ様。モンスターの戦い方はどうだった？」
line = "「お疲れ様。モンスターの戦い方はどうだった？」"

[[dialogue]]
speaker = "コハルコ"
# 「……戦い方も本物と同じ？　じゃあこのまま登録しちゃうね。……よし、これでいつでも戦えるよ」
line = "「……戦い方も本物と同じ？　じゃあこのまま登録しちゃうね。……よし、これでいつでも戦えるよ」"

[[dialogue]]
speaker = "シノ"
# 「お疲れ様です、コハルコさん。ここにいらしたんですね」
line = "「お疲れ様です、コハルコさん。ここにいらしたんですね」"

[[dialogue]]
speaker = "コハルコ"
# 「シノさん、お疲れ様です」
line = "「シノさん、お疲れ様です」"

[[dialogue]]
speaker = "シノ"
# 「会長さんと百目騎さんも、シミュレーターの調整ですか？　お疲れ様です」
line = "「会長さんと百目騎さんも、シミュレーターの調整ですか？　お疲れ様です」"

[[dialogue]]
speaker = "unk"
# お疲れ様です
line = "お疲れ様です"

[[dialogue]]
speaker = "レイラ"
# 「十六夜学園長、ご無沙汰しております」
line = "「十六夜学園長、ご無沙汰しております」"

[[dialogue]]
speaker = "コハルコ"
# 「あー、レイラは遊びに来てるだけなので無視していいですよ……。ところで、私に御用でしたか？」
line = "「あー、レイラは遊びに来てるだけなので無視していいですよ……。ところで、私に御用でしたか？」"

[[dialogue]]
speaker = "シノ"
# 「はい、職員の勤怠管理システムの改修の件について、確認したいことがあって」
line = "「はい、職員の勤怠管理システムの改修の件について、確認したいことがあって」"

[[dialogue]]
speaker = "コハルコ"
# 「ああ、あの件ですね。シノさんの職員ヒアリングが完璧だったので、改修プランはできてますよ。今月中にはベータ版を出す予定です」
line = "「ああ、あの件ですね。シノさんの職員ヒアリングが完璧だったので、改修プランはできてますよ。今月中にはベータ版を出す予定です」"

[[dialogue]]
speaker = "シノ"
# 「いえ、完璧だなんて……コハルコさんが優秀なんですよ」
line = "「いえ、完璧だなんて……コハルコさんが優秀なんですよ」"

[[dialogue]]
speaker = "レイラ"
# 「あのジャスティスウィザードが勤怠管理システムの改修だなんて、平和な世の中ですね～」
line = "「あのジャスティスウィザードが勤怠管理システムの改修だなんて、平和な世の中ですね～」"

[[dialogue]]
speaker = "シノ"
# 「ジャスティスウィザード……？」
line = "「ジャスティスウィザード……？」"

[[dialogue]]
speaker = "コハルコ"
# 「レイラ～！　シノさんは私のクソダサネームのことは知らないの！　せっかくヘレナさんにも秘密にしてもらったのに、台無しにしないで！」
line = "「レイラ～！　シノさんは私のクソダサネームのことは知らないの！　せっかくヘレナさんにも秘密にしてもらったのに、台無しにしないで！」"

[[dialogue]]
speaker = "レイラ"
# 「え、そうだったんですか！？　失礼しました～！」
line = "「え、そうだったんですか！？　失礼しました～！」"

[[dialogue]]
speaker = "シノ"
# 「え、あの……さっきからコハルコさんがジャスティスウィザードである前提でお話されているみたいなんですが」
line = "「え、あの……さっきからコハルコさんがジャスティスウィザードである前提でお話されているみたいなんですが」"

[[dialogue]]
speaker = "コハルコ"
# 「ぴゅ、ぴゅーーーー」
line = "「ぴゅ、ぴゅーーーー」"

[[dialogue]]
speaker = "レイラ"
# 「ほーほけきょ」
line = "「ほーほけきょ」"

[[dialogue]]
speaker = "シノ"
# 「人知れず巨悪を倒す正義のスーパーハッカ―『ジャスティスウィザード』……」
line = "「人知れず巨悪を倒す正義のスーパーハッカ―『ジャスティスウィザード』……」"

[[dialogue]]
speaker = "シノ"
# 「都市伝説だとばかり思っていましたけど、実在していて……しかも正体がコハルコさんなんですか！？」
line = "「都市伝説だとばかり思っていましたけど、実在していて……しかも正体がコハルコさんなんですか！？」"

[[dialogue]]
speaker = "unk"
# 実はそうなんです
line = "実はそうなんです"

[[dialogue]]
speaker = "unk"
# コハルコさんはかつてジャスティスウィザードと呼ばれた凄腕のハッカーだ。政治家の汚職や大企業の不正を暴いたりしていた過去がある。
line = "コハルコさんはかつてジャスティスウィザードと呼ばれた凄腕のハッカーだ。政治家の汚職や大企業の不正を暴いたりしていた過去がある。"

[[dialogue]]
speaker = "コハルコ"
# 「なんで会長さんが肯定するの！？」
line = "「なんで会長さんが肯定するの！？」"

[[dialogue]]
speaker = "コハルコ"
# 「……バレてしまったのは仕方ないし、このまま隠し事する方がよくない？　うぅ、それはそうだけど…………」
line = "「……バレてしまったのは仕方ないし、このまま隠し事する方がよくない？　うぅ、それはそうだけど…………」"

[[dialogue]]
speaker = "シノ"
# 「コハルコさん。あなたがジャスティスウィザードで間違いないんですね？　チームではなく単独なんですか？」
line = "「コハルコさん。あなたがジャスティスウィザードで間違いないんですね？　チームではなく単独なんですか？」"

[[dialogue]]
speaker = "コハルコ"
# 「……はい、そうです。仲間はいなくて私ひとりでやってました」
line = "「……はい、そうです。仲間はいなくて私ひとりでやってました」"

[[dialogue]]
speaker = "シノ"
# 「ちなみに動機は……？」
line = "「ちなみに動機は……？」"

[[dialogue]]
speaker = "コハルコ"
# 「弱い人を食い物にする悪い人が許せなくて、つい……」
line = "「弱い人を食い物にする悪い人が許せなくて、つい……」"

[[dialogue]]
speaker = "シノ"
# 「ついって……そんな、つまみ食いじゃないんですから…………」
line = "「ついって……そんな、つまみ食いじゃないんですから…………」"

[[dialogue]]
speaker = "コハルコ"
# 「学園に入学する前、ハッキングを身に着けた私は……悪い人に苦しめられている人が世の中にいることを知ったんです」
line = "「学園に入学する前、ハッキングを身に着けた私は……悪い人に苦しめられている人が世の中にいることを知ったんです」"

[[dialogue]]
speaker = "コハルコ"
# 「なんとか助けられないか、いろいろやってるうちに、変なあだ名がついちゃったんです」
line = "「なんとか助けられないか、いろいろやってるうちに、変なあだ名がついちゃったんです」"

[[dialogue]]
speaker = "レイラ"
# 「あ、それ私がつけました」
line = "「あ、それ私がつけました」"

[[dialogue]]
speaker = "コハルコ"
# 「コラプサーとしてやったことはともかく、あだ名のことは未だに許してないし、そして今後も許すつもりないからね！」
line = "「コラプサーとしてやったことはともかく、あだ名のことは未だに許してないし、そして今後も許すつもりないからね！」"

[[dialogue]]
speaker = "レイラ"
# 「うーん、コハルコさんの正義感って独特なんですよね。社会の正義とズレているというか……」
line = "「うーん、コハルコさんの正義感って独特なんですよね。社会の正義とズレているというか……」"

[[dialogue]]
speaker = "コハルコ"
# 「いや、私は自分が正しいと思ったことしかしてないから！」
line = "「いや、私は自分が正しいと思ったことしかしてないから！」"

[[dialogue]]
speaker = "レイラ"
# 「この人、自分の正義＞＞＞＞越えられない壁＞＞＞＞世間の正義なんです。世が世ならレジスタンスとかやってますよ、きっと」
line = "「この人、自分の正義＞＞＞＞越えられない壁＞＞＞＞世間の正義なんです。世が世ならレジスタンスとかやってますよ、きっと」"

[[dialogue]]
speaker = "コハルコ"
# 「やらないよレジスタンスなんて！」
line = "「やらないよレジスタンスなんて！」"

[[dialogue]]
speaker = "unk"
# 実は並行世界のコハルコはレジスタンスに参加してるんだけど、ここは黙っておこう。
line = "実は並行世界のコハルコはレジスタンスに参加してるんだけど、ここは黙っておこう。"

[[dialogue]]
speaker = "シノ"
# 「な、なるほど……コハルコさんの過去については分かりました。でも、ハッカー活動は今はしていないんですよね？」
line = "「な、なるほど……コハルコさんの過去については分かりました。でも、ハッカー活動は今はしていないんですよね？」"

[[dialogue]]
speaker = "コハルコ"
# 「……はい、今はしてない、です……基本的に……」
line = "「……はい、今はしてない、です……基本的に……」"

[[dialogue]]
speaker = "コハルコ"
# 「ほんの少し、たま～に……ちょっと、ちょこっとだけ……先っぽだけ……」
line = "「ほんの少し、たま～に……ちょっと、ちょこっとだけ……先っぽだけ……」"

[[dialogue]]
speaker = "シノ"
# 「してるじゃないですかー！　<ruby=コンプライアンス>遵法精神</ruby>、<ruby=コンプライアンス>遵法精神</ruby>はないんですか！？」
line = "「してるじゃないですかー！　<ruby>遵法精神<rt>コンプライアンス</rt></ruby>、<ruby>遵法精神<rt>コンプライアンス</rt></ruby>はないんですか！？」"

[[dialogue]]
speaker = "レイラ"
# 「そこになかったらないですね～」
line = "「そこになかったらないですね～」"

[[dialogue]]
speaker = "コハルコ"
# 「あるよ！　人並みには！」
line = "「あるよ！　人並みには！」"

[[dialogue]]
speaker = "シノ"
# 「そこは人並み以上でお願いします～～！！」
line = "「そこは人並み以上でお願いします～～！！」"

[[dialogue]]
speaker = "unk"
# 学園長には悪いけど、コハルコのジャスティスは止まらないと思う。この人は根っからだから。
line = "学園長には悪いけど、コハルコのジャスティスは止まらないと思う。この人は根っからだから。"
