[[dialogue]]
speaker = "unk"
# 第２話,マリンスポーツ,P
line = "第２話,マリンスポーツ,P"

[[dialogue]]
speaker = "セーラ"
# 「よーし……よっ……いい感じいい感じ……このまま前に歩いて……空のお散歩を──って、あっ！」
line = "「よーし……よっ……いい感じいい感じ……このまま前に歩いて……空のお散歩を──って、あっ！」"

[[dialogue]]
speaker = "セーラ"
# 「──きゃあっ！？」
line = "「──きゃあっ！？」"

[[dialogue]]
speaker = "unk"
# いま助けます！
line = "いま助けます！"

[[dialogue]]
speaker = "unk"
# 大丈夫ですか
line = "大丈夫ですか"

[[dialogue]]
speaker = "セーラ"
# 「──あはは、大失敗！　でもちょー面白い！」
line = "「──あはは、大失敗！　でもちょー面白い！」"

[[dialogue]]
speaker = "セーラ"
# 「これがフライボードってやつなんだねー！　雑誌だと簡単そうに見えたけど、やってみたら激ムズじゃん！」
line = "「これがフライボードってやつなんだねー！　雑誌だと簡単そうに見えたけど、やってみたら激ムズじゃん！」"

[[dialogue]]
speaker = "unk"
# 楽しかった
line = "楽しかった"

[[dialogue]]
speaker = "unk"
# 難しかったけど……
line = "難しかったけど……"

[[dialogue]]
speaker = "セーラ"
# 「ね！　わかる！　落っこちちゃっても逆に楽しい？　みたいな！」
line = "「ね！　わかる！　落っこちちゃっても逆に楽しい？　みたいな！」"

[[dialogue]]
speaker = "セーラ"
# 「下手な落ち方しなくてよかったぁ……打ちつけられたら超痛そうだもんね……」
line = "「下手な落ち方しなくてよかったぁ……打ちつけられたら超痛そうだもんね……」"

[[dialogue]]
speaker = "セーラ"
# 「それじゃ、この後はパラセーリングね！　リップルちゃんのお師匠さんがボート運転してくれるんだって！」
line = "「それじゃ、この後はパラセーリングね！　リップルちゃんのお師匠さんがボート運転してくれるんだって！」"

[[dialogue]]
speaker = "unk"
# パラセーリングをして、穏やかな空の遊覧を楽しんだ……。
line = "パラセーリングをして、穏やかな空の遊覧を楽しんだ……。"

[[dialogue]]
speaker = "セーラ"
# 「いや～楽しかった、っと。一旦休憩～♪」
line = "「いや～楽しかった、っと。一旦休憩～♪」"

[[dialogue]]
speaker = "セーラ"
# 「大人っぽい遊び方だった？　あはは、そんなことないっしょ。うちだってどっちも初めてだったんだから」
line = "「大人っぽい遊び方だった？　あはは、そんなことないっしょ。うちだってどっちも初めてだったんだから」"

[[dialogue]]
speaker = "セーラ"
# 「あと雑誌にはどんなアクティビティが載ってたかなー……カヤックとかラフティング──は海でやるものじゃないし……」
line = "「あと雑誌にはどんなアクティビティが載ってたかなー……カヤックとかラフティング──は海でやるものじゃないし……」"

[[dialogue]]
speaker = "アポロ"
# 「──よう、セーラ！　今ヒマか？」
line = "「──よう、セーラ！　今ヒマか？」"

[[dialogue]]
speaker = "ルリエル"
# 「新星会長さんもいます！　真夏の太陽に負けないラブラブっぷりです！」
line = "「新星会長さんもいます！　真夏の太陽に負けないラブラブっぷりです！」"

[[dialogue]]
speaker = "セーラ"
# 「アポロちゃんにルリちー。どしたん？」
line = "「アポロちゃんにルリちー。どしたん？」"

[[dialogue]]
speaker = "unk"
# //キュピーン！　ひらめき
line = "//キュピーン！　ひらめき"

[[dialogue]]
speaker = "アポロ"
# 「へっ……セーラはいい銃をお持ちだと思ってな！」
line = "「へっ……セーラはいい銃をお持ちだと思ってな！」"

[[dialogue]]
speaker = "セーラ"
# 「銃って……これのこと～？」
line = "「銃って……これのこと～？」"

[[dialogue]]
speaker = "アポロ"
# 「ああ！　これから流星星徒会にあたしを加えたメンバーでウォーターサバイバルゲームをやろうって話になったんだ」
line = "「ああ！　これから流星星徒会にあたしを加えたメンバーでウォーターサバイバルゲームをやろうって話になったんだ」"

[[dialogue]]
speaker = "ルリエル"
# 「流星イチのスナイパー、セーラ先輩もぜひ参加を！　と思いまして！」
line = "「流星イチのスナイパー、セーラ先輩もぜひ参加を！　と思いまして！」"

[[dialogue]]
speaker = "ソフィア"
# 「私やフィオナ会長も連れてこられました」
line = "「私やフィオナ会長も連れてこられました」"

[[dialogue]]
speaker = "セーラ"
# 「へー……面白そう！　会長さんもやるよね？」
line = "「へー……面白そう！　会長さんもやるよね？」"

[[dialogue]]
speaker = "unk"
# 流星じゃないけどいいの？
line = "流星じゃないけどいいの？"

[[dialogue]]
speaker = "アポロ"
# 「いいぜ！　たまには魔王とチームってのも悪くないな！」
line = "「いいぜ！　たまには魔王とチームってのも悪くないな！」"

[[dialogue]]
speaker = "ルリエル"
# 「セーラ先輩は日頃から銃を得物としていますからね！　強敵です」
line = "「セーラ先輩は日頃から銃を得物としていますからね！　強敵です」"

[[dialogue]]
speaker = "ソフィア"
# 「えふぴーえす……でしたっけ？　撃ち合うゲームにも慣れていますし、手ごわそうです」
line = "「えふぴーえす……でしたっけ？　撃ち合うゲームにも慣れていますし、手ごわそうです」"

[[dialogue]]
speaker = "セーラ"
# 「ふふふ～バレちゃった？　セーラ先輩は手強いよ～」
line = "「ふふふ～バレちゃった？　セーラ先輩は手強いよ～」"

[[dialogue]]
speaker = "アポロ"
# 「んじゃ、そういうことで参加決定な。向こうで待ってるからな～！」
line = "「んじゃ、そういうことで参加決定な。向こうで待ってるからな～！」"

[[dialogue]]
speaker = "セーラ"
# 「よいしょっ……と。じゃ、うちらも行こっか」
line = "「よいしょっ……と。じゃ、うちらも行こっか」"

[[dialogue]]
speaker = "セーラ"
# 「水鉄砲の撃ち合いなんて腕がなるよ～！　めっちゃわくわくする！」
line = "「水鉄砲の撃ち合いなんて腕がなるよ～！　めっちゃわくわくする！」"

[[dialogue]]
speaker = "unk"
# どっちのほうが好き？
line = "どっちのほうが好き？"

[[dialogue]]
speaker = "unk"
# セーラさんは……
line = "セーラさんは……"

[[dialogue]]
speaker = "セーラ"
# 「……へ？　何その質問」
line = "「……へ？　何その質問」"

[[dialogue]]
speaker = "セーラ"
# 「どっちって──ああ。２人の時と、みんなでいる時ってこと？」
line = "「どっちって──ああ。２人の時と、みんなでいる時ってこと？」"

[[dialogue]]
speaker = "セーラ"
# 「そんなの──どっちも好きだよ。会長さんと２人でいるのも、みんなでワイワイやってるのも」
line = "「そんなの──どっちも好きだよ。会長さんと２人でいるのも、みんなでワイワイやってるのも」"

[[dialogue]]
speaker = "セーラ"
# 「会長さんに色んな顔があるように……うちにも色んな側面があるってだけ」
line = "「会長さんに色んな顔があるように……うちにも色んな側面があるってだけ」"

[[dialogue]]
speaker = "セーラ"
# 「恋人として会長さんと接してるうち、先輩として流星のみんなと遊んでるうち、上の先輩に可愛がられてた頃の後輩としてのうち……」
line = "「恋人として会長さんと接してるうち、先輩として流星のみんなと遊んでるうち、上の先輩に可愛がられてた頃の後輩としてのうち……」"

[[dialogue]]
speaker = "セーラ"
# 「ま、会長さんには全部のうちを知ってほしいって思うけどね♪」
line = "「ま、会長さんには全部のうちを知ってほしいって思うけどね♪」"

[[dialogue]]
speaker = "unk"
# 俺も知りたい
line = "俺も知りたい"

[[dialogue]]
speaker = "unk"
# 俺も教えたい
line = "俺も教えたい"

[[dialogue]]
speaker = "セーラ"
# 「ふふっ、可愛いこと言うよね会長さんは。うちもだよ」
line = "「ふふっ、可愛いこと言うよね会長さんは。うちもだよ」"

[[dialogue]]
speaker = "セーラ"
# 「これからもずっと一緒にいるんだから──お互いのこと、もっと知ってこ♪」
line = "「これからもずっと一緒にいるんだから──お互いのこと、もっと知ってこ♪」"

[[dialogue]]
speaker = "セーラ"
# 「──ってことで、会長さんは敵チームね。日頃味わえないうちの射撃スキル──存分に体感してもらうから！」
line = "「──ってことで、会長さんは敵チームね。日頃味わえないうちの射撃スキル──存分に体感してもらうから！」"

[[dialogue]]
speaker = "unk"
# それからは流星星徒会のメンバーに囲まれて、ビーチでのひと時を過ごすのだった。
line = "それからは流星星徒会のメンバーに囲まれて、ビーチでのひと時を過ごすのだった。"
