[[dialogue]]
speaker = "unk"
# 第２話,セシアのママ宣言,P
line = "第２話,セシアのママ宣言,P"

[[dialogue]]
speaker = "unk"
# セシアのアプローチ宣言があってから、少し経ったある日のこと。
line = "セシアのアプローチ宣言があってから、少し経ったある日のこと。"

[[dialogue]]
speaker = "セシア"
# 「会長、人間界では、恋人を持った女性は最終的に『ママ』になるでしょう？」
line = "「会長、人間界では、恋人を持った女性は最終的に『ママ』になるでしょう？」"

[[dialogue]]
speaker = "セシア"
# 「なら、わたくしは――」
line = "「なら、わたくしは――」"

[[dialogue]]
speaker = "セシア"
# 「ズバリ、あなたの『ママ』になりたいわ！」
line = "「ズバリ、あなたの『ママ』になりたいわ！」"

[[dialogue]]
speaker = "unk"
# どういうこと！？
line = "どういうこと！？"

[[dialogue]]
speaker = "unk"
# 翌日の朝――
line = "翌日の朝――"

[[dialogue]]
speaker = "？？？"
# 「もう、疲れていたからって、こんなところで寝ちゃうなんて……」
line = "「もう、疲れていたからって、こんなところで寝ちゃうなんて……」"

[[dialogue]]
speaker = "？？？"
# 「起きて、会長。朝よ」
line = "「起きて、会長。朝よ」"

[[dialogue]]
speaker = "unk"
# ん……母さん？
line = "ん……母さん？"

[[dialogue]]
speaker = "セシア"
# 「そう、わたくしがあなたのママよ♪」
line = "「そう、わたくしがあなたのママよ♪」"

[[dialogue]]
speaker = "unk"
# セシア！？　なんでここに！？
line = "セシア！？　なんでここに！？"

[[dialogue]]
speaker = "セシア"
# 「ふふっ、昨日言ったでしょう？　会長のママになるって」
line = "「ふふっ、昨日言ったでしょう？　会長のママになるって」"

[[dialogue]]
speaker = "セシア"
# 「わたくしが将来、本当のママになる為の予行練習――つまりは、将来を見据えた蓄積ということね♪」
line = "「わたくしが将来、本当のママになる為の予行練習――つまりは、将来を見据えた蓄積ということね♪」"

[[dialogue]]
speaker = "リノ"
# 「セシアちゃん、クロトは起きたかしら～？」
line = "「セシアちゃん、クロトは起きたかしら～？」"

[[dialogue]]
speaker = "セシア"
# 「あっ、リノママ～♪　セシア、ちゃんと会長を起こせたわ♪」
line = "「あっ、リノママ～♪　セシア、ちゃんと会長を起こせたわ♪」"

[[dialogue]]
speaker = "リノ"
# 「あら～、セシアちゃん、よくできました♪　よしよし～♪」
line = "「あら～、セシアちゃん、よくできました♪　よしよし～♪」"

[[dialogue]]
speaker = "セシア"
# 「えへへ～<emoji=heart04>　ママに褒められて、セシアとっても嬉しいわ<emoji=heart04>」
line = "「えへへ～<emoji=heart04>　ママに褒められて、セシアとっても嬉しいわ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 子供みたいに甘えているというカオス！
line = "子供みたいに甘えているというカオス！"

[[dialogue]]
speaker = "unk"
# ママがママに
line = "ママがママに"

[[dialogue]]
speaker = "unk"
# ――というか、セシアが母さんと会うのは、初めてのはずでは！？　それがいつの間にか仲良くなってる！？
line = "――というか、セシアが母さんと会うのは、初めてのはずでは！？　それがいつの間にか仲良くなってる！？"

[[dialogue]]
speaker = "セシア"
# 「会長、リノママ、とっても素敵なママね♪　わたくし、観察する間もなく出会ってひと目でこの人はママだと直感したわ」
line = "「会長、リノママ、とっても素敵なママね♪　わたくし、観察する間もなく出会ってひと目でこの人はママだと直感したわ」"

[[dialogue]]
speaker = "リノ"
# 「ふふっ、クロトったら、こういう小さな子がタイプだったのね。大丈夫よ、お母さん――」
line = "「ふふっ、クロトったら、こういう小さな子がタイプだったのね。大丈夫よ、お母さん――」"

[[dialogue]]
speaker = "unk"
# 母さんはぐっと親指を立てて……
line = "母さんはぐっと親指を立てて……"

[[dialogue]]
speaker = "リノ"
# 「息子がどんな性癖でもちゃんと受け止めるから☆」
line = "「息子がどんな性癖でもちゃんと受け止めるから☆」"

[[dialogue]]
speaker = "セシア"
# 「それじゃあリノママ、行ってきま～す♪」
line = "「それじゃあリノママ、行ってきま～す♪」"

[[dialogue]]
speaker = "リノ"
# 「いってらっしゃ～い♪　また夕食の時にね、セシアちゃん♪」
line = "「いってらっしゃ～い♪　また夕食の時にね、セシアちゃん♪」"

[[dialogue]]
speaker = "セシア"
# 「は～い♪　セシア、学園でお勉強頑張ってくるわ♪」
line = "「は～い♪　セシア、学園でお勉強頑張ってくるわ♪」"

[[dialogue]]
speaker = "unk"
# 夕食も一緒にする流れになってるし！
line = "夕食も一緒にする流れになってるし！"

[[dialogue]]
speaker = "unk"
# なんか既に
line = "なんか既に"

[[dialogue]]
speaker = "unk"
# 母さんとセシアの馴染む速度が異常で、完全に置いてけぼりにされていた。
line = "母さんとセシアの馴染む速度が異常で、完全に置いてけぼりにされていた。"

[[dialogue]]
speaker = "unk"
# そうして、俺たちは家を出て、一緒に登校することになり――
line = "そうして、俺たちは家を出て、一緒に登校することになり――"

[[dialogue]]
speaker = "セシア"
# 「会長、手を繋いでもいいかしら？」
line = "「会長、手を繋いでもいいかしら？」"

[[dialogue]]
speaker = "セシア"
# 「――ありがとう♪　じゃあ、繋ぐわね」
line = "「――ありがとう♪　じゃあ、繋ぐわね」"

[[dialogue]]
speaker = "セシア"
# 「ん……♪　ふふっ、こうして繋ぐのはデートの時以来ね」
line = "「ん……♪　ふふっ、こうして繋ぐのはデートの時以来ね」"

[[dialogue]]
speaker = "セシア"
# 「やっぱり、リノママの手とは違う感じがするわ。それと……この前ともちょっと違う感じがする」
line = "「やっぱり、リノママの手とは違う感じがするわ。それと……この前ともちょっと違う感じがする」"

[[dialogue]]
speaker = "セシア"
# 「――今日はわたくしがママになっているからかしら？　なんだか……」
line = "「――今日はわたくしがママになっているからかしら？　なんだか……」"

[[dialogue]]
speaker = "セシア"
# 「嬉しいのと同時に、ドキドキするの♪」
line = "「嬉しいのと同時に、ドキドキするの♪」"

[[dialogue]]
speaker = "unk"
# その言葉に、俺はまたドキッとしてしまう。
line = "その言葉に、俺はまたドキッとしてしまう。"

[[dialogue]]
speaker = "unk"
# それから学園が近づいてくると、周りの視線が増えてきて、気恥ずかしく感じたりしたのだが――
line = "それから学園が近づいてくると、周りの視線が増えてきて、気恥ずかしく感じたりしたのだが――"

[[dialogue]]
speaker = "セシア"
# 「～～♪　～～～♪」
line = "「～～♪　～～～♪」"

[[dialogue]]
speaker = "unk"
# （まぁ、セシアが楽しそうだし、いっか）
line = "（まぁ、セシアが楽しそうだし、いっか）"

[[dialogue]]
speaker = "unk"
# 上機嫌に鼻唄を歌うセシアを見ていると、そんな気になって、結局学園に着くまでそのまま手を繋いで歩き続けたのだった――
line = "上機嫌に鼻唄を歌うセシアを見ていると、そんな気になって、結局学園に着くまでそのまま手を繋いで歩き続けたのだった――"

[[dialogue]]
speaker = "unk"
# その日の放課後。
line = "その日の放課後。"

[[dialogue]]
speaker = "unk"
# 俺はセシアと２人で夕食の買い物をして帰ることになった。
line = "俺はセシアと２人で夕食の買い物をして帰ることになった。"

[[dialogue]]
speaker = "unk"
# 母さんからＤＩＳＣの通知が届いて、頼まれたのだ。
line = "母さんからＤＩＳＣの通知が届いて、頼まれたのだ。"

[[dialogue]]
speaker = "セシア"
# 「会長、買い物袋を持ってくれてありがとう♪」
line = "「会長、買い物袋を持ってくれてありがとう♪」"

[[dialogue]]
speaker = "unk"
# どういたしまして
line = "どういたしまして"

[[dialogue]]
speaker = "セシア"
# 「ふふっ♪　こうして一緒に買い物をして歩いていると、ママになったって感じがするわ♪」
line = "「ふふっ♪　こうして一緒に買い物をして歩いていると、ママになったって感じがするわ♪」"

[[dialogue]]
speaker = "セシア"
# 「夫婦ってもしかして、こんな感じなのかしら？　……って、あら？」
line = "「夫婦ってもしかして、こんな感じなのかしら？　……って、あら？」"

[[dialogue]]
speaker = "unk"
# ふと、セシアの視線がある方向に向く。
line = "ふと、セシアの視線がある方向に向く。"

[[dialogue]]
speaker = "unk"
# そこにはセシアよりも小さな女の子が、１人で辺りをキョロキョロしながら歩いていた。
line = "そこにはセシアよりも小さな女の子が、１人で辺りをキョロキョロしながら歩いていた。"

[[dialogue]]
speaker = "unk"
# セシアはその子の近くへ歩いて行き――
line = "セシアはその子の近くへ歩いて行き――"

[[dialogue]]
speaker = "セシア"
# 「ねぇ、ちょっといいかしら？」
line = "「ねぇ、ちょっといいかしら？」"

[[dialogue]]
speaker = "女の子"
# 「え……？　お、お姉ちゃん、誰……？」
line = "「え……？　お、お姉ちゃん、誰……？」"

[[dialogue]]
speaker = "セシア"
# 「わたくしは――」
line = "「わたくしは――」"

[[dialogue]]
speaker = "セシア"
# 「通りすがりのママよ」
line = "「通りすがりのママよ」"

[[dialogue]]
speaker = "女の子"
# 「ママを名乗る怪しいヒト……！？」
line = "「ママを名乗る怪しいヒト……！？」"

[[dialogue]]
speaker = "セシア"
# 「それで……もしかしてあなた、迷子だったりするかしら？」
line = "「それで……もしかしてあなた、迷子だったりするかしら？」"

[[dialogue]]
speaker = "unk"
# その後、女の子から話を聞くと、セシアの予想通り、女の子は買い物中にお母さんとはぐれてしまった迷子だった。
line = "その後、女の子から話を聞くと、セシアの予想通り、女の子は買い物中にお母さんとはぐれてしまった迷子だった。"

[[dialogue]]
speaker = "unk"
# セシアはそっと彼女の頭に手を置いて、撫でると――
line = "セシアはそっと彼女の頭に手を置いて、撫でると――"

[[dialogue]]
speaker = "セシア"
# 「よく１人で泣かずに頑張ったわね。もう大丈夫よ」
line = "「よく１人で泣かずに頑張ったわね。もう大丈夫よ」"

[[dialogue]]
speaker = "セシア"
# 「わたくしたちが必ず、あなたのママを見つけてあげるわ」
line = "「わたくしたちが必ず、あなたのママを見つけてあげるわ」"

[[dialogue]]
speaker = "unk"
# それから俺たちは、女の子の話を聞きながら、その辺りを歩いて回った。
line = "それから俺たちは、女の子の話を聞きながら、その辺りを歩いて回った。"

[[dialogue]]
speaker = "unk"
# 幸い、すぐに彼女のお母さんは見つかって、事無きを得た。
line = "幸い、すぐに彼女のお母さんは見つかって、事無きを得た。"

[[dialogue]]
speaker = "unk"
# 女の子と別れた直後、セシアは彼女に手を振りながら……
line = "女の子と別れた直後、セシアは彼女に手を振りながら……"

[[dialogue]]
speaker = "セシア"
# 「あの子、すぐにママが見つかってよかったわ」
line = "「あの子、すぐにママが見つかってよかったわ」"

[[dialogue]]
speaker = "unk"
# そう言って優しく微笑むセシアの横顔は、何だか見惚れてしまうくらい慈愛に満ちていて――
line = "そう言って優しく微笑むセシアの横顔は、何だか見惚れてしまうくらい慈愛に満ちていて――"

[[dialogue]]
speaker = "unk"
# ……セシア、突然なんだけどさ
line = "……セシア、突然なんだけどさ"

[[dialogue]]
speaker = "セシア"
# 「？　どうしたの、会長？　真剣な顔をして――」
line = "「？　どうしたの、会長？　真剣な顔をして――」"

[[dialogue]]
speaker = "unk"
# 改めて俺と、恋人として付き合って欲しい
line = "改めて俺と、恋人として付き合って欲しい"

[[dialogue]]
speaker = "セシア"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "unk"
# 彼女は驚いた顔で目をぱちくりさせて……
line = "彼女は驚いた顔で目をぱちくりさせて……"

[[dialogue]]
speaker = "セシア"
# 「それはわたくしも望んでいたことだけれど……でも、いきなりどうして？　何かあったの？」
line = "「それはわたくしも望んでいたことだけれど……でも、いきなりどうして？　何かあったの？」"

[[dialogue]]
speaker = "unk"
# 正直、上手く言葉にできないんだ。でも――
line = "正直、上手く言葉にできないんだ。でも――"

[[dialogue]]
speaker = "unk"
# 今日、俺はセシアと一緒にいて、セシアのことをもっと知りたいと感じた、と素直な気持ちを話す。
line = "今日、俺はセシアと一緒にいて、セシアのことをもっと知りたいと感じた、と素直な気持ちを話す。"

[[dialogue]]
speaker = "unk"
# ……ダメかな？
line = "……ダメかな？"

[[dialogue]]
speaker = "セシア"
# 「――いいえ。そんなことない。わたくし、とっても嬉しいわ」
line = "「――いいえ。そんなことない。わたくし、とっても嬉しいわ」"

[[dialogue]]
speaker = "セシア"
# 「今……本当に、心から嬉しい。思わず、踊り出してしまいそうなくらい♪」
line = "「今……本当に、心から嬉しい。思わず、踊り出してしまいそうなくらい♪」"

[[dialogue]]
speaker = "セシア"
# 「これからもよろしくね、会長」
line = "「これからもよろしくね、会長」"

[[dialogue]]
speaker = "セシア"
# 「恋人としても、素敵な経験を蓄積して行きましょう♪」
line = "「恋人としても、素敵な経験を蓄積して行きましょう♪」"

[[dialogue]]
speaker = "unk"
# そうして彼女が浮かべた笑顔に、やっぱり俺は、心惹かれる感じがしていて。
line = "そうして彼女が浮かべた笑顔に、やっぱり俺は、心惹かれる感じがしていて。"

[[dialogue]]
speaker = "unk"
# ああ、よろしく、セシア
line = "ああ、よろしく、セシア"

[[dialogue]]
speaker = "セシア"
# 「ふふっ♪　今日からわたくしが会長のママね」
line = "「ふふっ♪　今日からわたくしが会長のママね」"

[[dialogue]]
speaker = "unk"
# いや、それはちょっと……
line = "いや、それはちょっと……"

[[dialogue]]
speaker = "セシア"
# 「ええっ！？　恋人になったのに！？」
line = "「ええっ！？　恋人になったのに！？」"

[[dialogue]]
speaker = "unk"
# 本気で意外そうな顔をする彼女が面白くて、俺は思わず笑ってしまうのだった――
line = "本気で意外そうな顔をする彼女が面白くて、俺は思わず笑ってしまうのだった――"
