[[dialogue]]
speaker = "unk"
# 第４話,ホワイトデーのお返しデート,P
line = "第４話,ホワイトデーのお返しデート,P"

[[dialogue]]
speaker = "unk"
# 今日はホワイトデー。俺はバレンタインチョコのお返しも兼ねて、ウズメを浅草デートに誘うことにした。
line = "今日はホワイトデー。俺はバレンタインチョコのお返しも兼ねて、ウズメを浅草デートに誘うことにした。"

[[dialogue]]
speaker = "ウズメイア"
# 「いい天気だね～、会長くん！　絶好の浅草デート日和だし！」
line = "「いい天気だね～、会長くん！　絶好の浅草デート日和だし！」"

[[dialogue]]
speaker = "unk"
# 晴れてよかったね
line = "晴れてよかったね"

[[dialogue]]
speaker = "unk"
# 天気予報は雨だったけど
line = "天気予報は雨だったけど"

[[dialogue]]
speaker = "ウズメイア"
# 「むふふ～♪　実はあたし、昔っから晴れ女だし！　こーゆーイベント系のお出かけだと、だいたい天気予報を覆せるの！」
line = "「むふふ～♪　実はあたし、昔っから晴れ女だし！　こーゆーイベント系のお出かけだと、だいたい天気予報を覆せるの！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ところでさー、会長くん。その恰好どうしたの！？　浴衣で来るとか聞いてないし……！」
line = "「ところでさー、会長くん。その恰好どうしたの！？　浴衣で来るとか聞いてないし……！」"

[[dialogue]]
speaker = "unk"
# ２人で和装デートしたら楽しいかなって
line = "２人で和装デートしたら楽しいかなって"

[[dialogue]]
speaker = "unk"
# 浅草では浴衣のレンタルがあるんだ
line = "浅草では浴衣のレンタルがあるんだ"

[[dialogue]]
speaker = "ウズメイア"
# 「そんなのもあるんだね！　さっすが会長くん、彼女の好みをよくわかってるし～♪」
line = "「そんなのもあるんだね！　さっすが会長くん、彼女の好みをよくわかってるし～♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くんの浴衣姿、バチバチに似合ってて動悸ヤバいかも～<emoji=heart04>　ね、ねっ。一緒に記念写真撮ろ！？」
line = "「会長くんの浴衣姿、バチバチに似合ってて動悸ヤバいかも～<emoji=heart04>　ね、ねっ。一緒に記念写真撮ろ！？」"

[[dialogue]]
speaker = "ウズメイア"
# 「は～い、ＤＩＳＣに向かってピースだしっ♪　いぇ～いっ！」
line = "「は～い、ＤＩＳＣに向かってピースだしっ♪　いぇ～いっ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「やっばぁ……<emoji=heart04>　お付き合いしてる彼ピの和装姿……めっちゃアガるっ……待ち受け不可避だし<emoji=heart04>」
line = "「やっばぁ……<emoji=heart04>　お付き合いしてる彼ピの和装姿……めっちゃアガるっ……待ち受け不可避だし<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「バレンタインのお返し、何がもらえるかな～って楽しみだったけど、まさか会長くんの浴衣を見せてもらえるなんて～。幸せだし！」
line = "「バレンタインのお返し、何がもらえるかな～って楽しみだったけど、まさか会長くんの浴衣を見せてもらえるなんて～。幸せだし！」"

[[dialogue]]
speaker = "unk"
# いや、これはまだ序の口だよ
line = "いや、これはまだ序の口だよ"

[[dialogue]]
speaker = "ウズメイア"
# 「なぬ！？　まだあるの！？」
line = "「なぬ！？　まだあるの！？」"

[[dialogue]]
speaker = "人力車の兄貴"
# 「──どうもっ、お迎えにあがりました！」
line = "「──どうもっ、お迎えにあがりました！」"

[[dialogue]]
speaker = "ウズメイア"
# 「なんか人力車のお兄さんまで来たし！？　えっ、これも予約したの？　これに乗って浅草をぐるっと一周デートプラン……！？」
line = "「なんか人力車のお兄さんまで来たし！？　えっ、これも予約したの？　これに乗って浅草をぐるっと一周デートプラン……！？」"

[[dialogue]]
speaker = "ウズメイア"
# 「ぅ～っ<emoji=heart04><emoji=heart04>　会長くん、大好きだし～っ<emoji=heart04>」
line = "「ぅ～っ<emoji=heart04><emoji=heart04>　会長くん、大好きだし～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その後、ウズメと一緒に人力車に乗り、引き手のお兄さんもまじえて談笑しながら浅草を一周した。
line = "その後、ウズメと一緒に人力車に乗り、引き手のお兄さんもまじえて談笑しながら浅草を一周した。"

[[dialogue]]
speaker = "unk"
# ウズメは俺の想像をはるかに超えるはしゃぎっぷりを見せてくれて──かなり前からプランを練った甲斐があったなと思うのだった。
line = "ウズメは俺の想像をはるかに超えるはしゃぎっぷりを見せてくれて──かなり前からプランを練った甲斐があったなと思うのだった。"

[[dialogue]]
speaker = "ウズメイア"
# 「人力車に乗るのも楽しいけど、こうやって２人でのんびり食べ歩きするのもまたオツだし！ ん～、あんみつ美味しい！」
line = "「人力車に乗るのも楽しいけど、こうやって２人でのんびり食べ歩きするのもまたオツだし！ ん～、あんみつ美味しい！」"

[[dialogue]]
speaker = "ウズメイア"
# 「はい、会長くん。あたしのあんみつ、１口どーぞ<emoji=heart04>　あ～ん……<emoji=heart04>」
line = "「はい、会長くん。あたしのあんみつ、１口どーぞ<emoji=heart04>　あ～ん……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「……甘さ控えめでおいしーでしょ！　むふふ～、また推しの笑顔を間近でゲットだし♪」
line = "「……甘さ控えめでおいしーでしょ！　むふふ～、また推しの笑顔を間近でゲットだし♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「あたしね、会長くんの笑顔が好きなんだ～<emoji=heart04>　ず～っと間近で見てたいし<emoji=heart04>」
line = "「あたしね、会長くんの笑顔が好きなんだ～<emoji=heart04>　ず～っと間近で見てたいし<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「……会長くんも同じ気持ち？　えへっ、めっちゃ幸せだし～<emoji=heart04>」
line = "「……会長くんも同じ気持ち？　えへっ、めっちゃ幸せだし～<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 大好きな恋人と手を繋いで街を歩く──しかし、ここで小さなトラブルが起こった。
line = "大好きな恋人と手を繋いで街を歩く──しかし、ここで小さなトラブルが起こった。"

[[dialogue]]
speaker = "ウズメイア"
# 「ありゃ？　晴れてるのに雨、降ってきちゃったし……！　うわ～、晴れ女だって言ったばっかなのに！？」
line = "「ありゃ？　晴れてるのに雨、降ってきちゃったし……！　うわ～、晴れ女だって言ったばっかなのに！？」"

[[dialogue]]
speaker = "ウズメイア"
# 「でも大丈夫だし！　あたしの新衣装なら……え～いっ♪」
line = "「でも大丈夫だし！　あたしの新衣装なら……え～いっ♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「傘があるから問題なし～<emoji=heart04>　会長くん、肩が濡れないように、ちゃーんとくっついてね？」
line = "「傘があるから問題なし～<emoji=heart04>　会長くん、肩が濡れないように、ちゃーんとくっついてね？」"

[[dialogue]]
speaker = "ウズメイア"
# 「にひ♪　オンボロ傘シリーズのマネする以外で、よーやく正しいことに使えた気がするし♪」
line = "「にひ♪　オンボロ傘シリーズのマネする以外で、よーやく正しいことに使えた気がするし♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「１人だったら、うわ～雨か～って思っちゃうけど、２人ならこういうトラブルも楽しくない？」
line = "「１人だったら、うわ～雨か～って思っちゃうけど、２人ならこういうトラブルも楽しくない？」"

[[dialogue]]
speaker = "ウズメイア"
# 「そういえばさ、晴れてる時に降る雨って、なんか名前があった気がする！　確か……たぬきの嫁入り！」
line = "「そういえばさ、晴れてる時に降る雨って、なんか名前があった気がする！　確か……たぬきの嫁入り！」"

[[dialogue]]
speaker = "unk"
# きつね、だね
line = "きつね、だね"

[[dialogue]]
speaker = "ウズメイア"
# 「あは、そだった♪　たぬきときつね、セットになることが多いからさ～。留学生は覚えるのも一苦労だし」
line = "「あは、そだった♪　たぬきときつね、セットになることが多いからさ～。留学生は覚えるのも一苦労だし」"

[[dialogue]]
speaker = "ウズメイア"
# 「今ごろどこかでお化粧したお狐様が、大好きな人と結婚式を挙げてるのかな～？」
line = "「今ごろどこかでお化粧したお狐様が、大好きな人と結婚式を挙げてるのかな～？」"

[[dialogue]]
speaker = "ウズメイア"
# 「もしそうだったら、この雨も悪くないってゆーか、もうちょっと続いてあげて欲しいな～って思うよね！」
line = "「もしそうだったら、この雨も悪くないってゆーか、もうちょっと続いてあげて欲しいな～って思うよね！」"

[[dialogue]]
speaker = "unk"
# ウズメのそういう優しいところが好きだ
line = "ウズメのそういう優しいところが好きだ"

[[dialogue]]
speaker = "ウズメイア"
# 「……っ<emoji=heart04>　て、照れるしー<emoji=heart04>　あたしもね、会長くんの優しいところ、大好きだよ？」
line = "「……っ<emoji=heart04>　て、照れるしー<emoji=heart04>　あたしもね、会長くんの優しいところ、大好きだよ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「こうやって相合傘するのって初めてだし、こうしてるだけで……実はめっちゃ、ドキドキしてるし<emoji=heart04>」
line = "「こうやって相合傘するのって初めてだし、こうしてるだけで……実はめっちゃ、ドキドキしてるし<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「──ちゅー、したいの？　んー……歩いてる人いっぱいだから、ちょっぴりハズいけど……傘で隠れてるからだいじょぶかな？」
line = "「──ちゅー、したいの？　んー……歩いてる人いっぱいだから、ちょっぴりハズいけど……傘で隠れてるからだいじょぶかな？」"

[[dialogue]]
speaker = "ウズメイア"
# 「ん～っ……ちゅっ<emoji=heart04>」
line = "「ん～っ……ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「にひひひ～<emoji=heart04>　ずーっと一緒にいようね、会長くん<emoji=heart04>　め～っちゃ大好きだしっ<emoji=heart04>」
line = "「にひひひ～<emoji=heart04>　ずーっと一緒にいようね、会長くん<emoji=heart04>　め～っちゃ大好きだしっ<emoji=heart04>」"
