[[dialogue]]
speaker = "unk"
# 第１話,何でもできるコハルコさん,P
line = "第１話,何でもできるコハルコさん,P"

[[dialogue]]
speaker = "サーシャ"
# 「あら、シミュレーターが止まっちゃったわね～。せっかく会長くんとトレーニングしようと思ったのに～」
line = "「あら、シミュレーターが止まっちゃったわね～。せっかく会長くんとトレーニングしようと思ったのに～」"

[[dialogue]]
speaker = "サーシャ"
# 「う～ん……よくわからないし、こういう時は専門家を呼びましょう」
line = "「う～ん……よくわからないし、こういう時は専門家を呼びましょう」"

[[dialogue]]
speaker = "サーシャ"
# 「もしもし～、コハルコちゃん？　シミュレーターが急に動かなくなっちゃって……うん、うん……お願いね～」
line = "「もしもし～、コハルコちゃん？　シミュレーターが急に動かなくなっちゃって……うん、うん……お願いね～」"

[[dialogue]]
speaker = "コハルコ"
# 「お待たせ、サーシャ」
line = "「お待たせ、サーシャ」"

[[dialogue]]
speaker = "サーシャ"
# 「いらっしゃ～い」
line = "「いらっしゃ～い」"

[[dialogue]]
speaker = "コハルコ"
# 「別にサーシャの家でも星徒会室でもないんだけど……相変わらずマイペースだね」
line = "「別にサーシャの家でも星徒会室でもないんだけど……相変わらずマイペースだね」"

[[dialogue]]
speaker = "コハルコ"
# 「君は……この間ヴィーナスさんに勝った会長さんだね。私は３年の朝比奈コハルコ。よろしく」
line = "「君は……この間ヴィーナスさんに勝った会長さんだね。私は３年の朝比奈コハルコ。よろしく」"

[[dialogue]]
speaker = "unk"
# よろしくお願いします
line = "よろしくお願いします"

[[dialogue]]
speaker = "コハルコ"
# 「うん。で、シミュレーターの調子が悪くなっちゃったんだっけ？　もっと具体的に教えてくれる？」
line = "「うん。で、シミュレーターの調子が悪くなっちゃったんだっけ？　もっと具体的に教えてくれる？」"

[[dialogue]]
speaker = "サーシャ"
# 「う～んと……会長くんと一緒だから、できるだけ強いモンスターをたくさん出したんだけど、戦ってる途中で真っ暗になっちゃったのよね」
line = "「う～んと……会長くんと一緒だから、できるだけ強いモンスターをたくさん出したんだけど、戦ってる途中で真っ暗になっちゃったのよね」"

[[dialogue]]
speaker = "コハルコ"
# 「ふむふむ、ちょっとログを見てみるね。……やっぱりそうか」
line = "「ふむふむ、ちょっとログを見てみるね。……やっぱりそうか」"

[[dialogue]]
speaker = "コハルコ"
# 「このシミュレーターは元々デリケートな上、安全のためにリミッターがかかってるの」
line = "「このシミュレーターは元々デリケートな上、安全のためにリミッターがかかってるの」"

[[dialogue]]
speaker = "コハルコ"
# 「どうやらモンスターの設定が強すぎてリミッターが誤作動してるみたい。ちょっと待ってて」
line = "「どうやらモンスターの設定が強すぎてリミッターが誤作動してるみたい。ちょっと待ってて」"

[[dialogue]]
speaker = "コハルコ"
# 「……はい、ＯＫ」
line = "「……はい、ＯＫ」"

[[dialogue]]
speaker = "サーシャ"
# 「あ、シミュレーターが動いたわ～」
line = "「あ、シミュレーターが動いたわ～」"

[[dialogue]]
speaker = "unk"
# ありがとうございます
line = "ありがとうございます"

[[dialogue]]
speaker = "コハルコ"
# 「どうしたしまして」
line = "「どうしたしまして」"

[[dialogue]]
speaker = "サーシャ"
# 「コハルコちゃんは機械のこと何でもできてすごいわ～」
line = "「コハルコちゃんは機械のこと何でもできてすごいわ～」"

[[dialogue]]
speaker = "コハルコ"
# 「何でもってわけじゃないよ。ハードウェアよりも、プログラムとかのソフトウェアが専門かな。それでも趣味でパソコンくらいは作るけど」
line = "「何でもってわけじゃないよ。ハードウェアよりも、プログラムとかのソフトウェアが専門かな。それでも趣味でパソコンくらいは作るけど」"

[[dialogue]]
speaker = "サーシャ"
# 「十分すごいわ～。それにコハルコちゃんはハッカーなのよ～」
line = "「十分すごいわ～。それにコハルコちゃんはハッカーなのよ～」"

[[dialogue]]
speaker = "unk"
# ハッカー！？
line = "ハッカー！？"

[[dialogue]]
speaker = "サーシャ"
# 「とっても大きな会社の厳重なセキュリティを突破したり、国の存亡に関わる大事なデータを盗んだりする人なのよね～」
line = "「とっても大きな会社の厳重なセキュリティを突破したり、国の存亡に関わる大事なデータを盗んだりする人なのよね～」"

[[dialogue]]
speaker = "コハルコ"
# 「そんな大それたことしてないよ。私の仕事はもっと地味だから」
line = "「そんな大それたことしてないよ。私の仕事はもっと地味だから」"

[[dialogue]]
speaker = "コハルコ"
# 「ハッカーというと悪いことをしている人をイメージするかもしれないけど、私はいわゆるホワイトハッカー」
line = "「ハッカーというと悪いことをしている人をイメージするかもしれないけど、私はいわゆるホワイトハッカー」"

[[dialogue]]
speaker = "コハルコ"
# 「攻撃される前にセキュリティの脆弱性を発見したり、新しいセキュリティシステムを構築したり、あと情報の漏洩をチェックしたりするのが仕事かな」
line = "「攻撃される前にセキュリティの脆弱性を発見したり、新しいセキュリティシステムを構築したり、あと情報の漏洩をチェックしたりするのが仕事かな」"

[[dialogue]]
speaker = "サーシャ"
# 「ハッカーと言えば、最近噂になってるわよね。え～っと……ジャスミンリザードだっけ～？」
line = "「ハッカーと言えば、最近噂になってるわよね。え～っと……ジャスミンリザードだっけ～？」"

[[dialogue]]
speaker = "コハルコ"
# 「正義の魔法使い──ジャスティスウィザード」
line = "「正義の魔法使い──ジャスティスウィザード」"

[[dialogue]]
speaker = "サーシャ"
# 「そう、それ～。確か大手の製薬会社の不正を暴いたのよ。あと政治家の汚職の証拠を出したりとか」
line = "「そう、それ～。確か大手の製薬会社の不正を暴いたのよ。あと政治家の汚職の証拠を出したりとか」"

[[dialogue]]
speaker = "unk"
# じゃあいいハッカー？
line = "じゃあいいハッカー？"

[[dialogue]]
speaker = "サーシャ"
# 「そうとは限らないかも。動物を開放するって言って動物園を攻撃したり、義賊を名乗って何も悪いことしてない資産家からお金を盗んだり……過激なこともやってるみたい」
line = "「そうとは限らないかも。動物を開放するって言って動物園を攻撃したり、義賊を名乗って何も悪いことしてない資産家からお金を盗んだり……過激なこともやってるみたい」"

[[dialogue]]
speaker = "サーシャ"
# 「コハルコちゃんはどう思う？」
line = "「コハルコちゃんはどう思う？」"

[[dialogue]]
speaker = "コハルコ"
# 「うーん、特に興味ないから聞かれても答えづらいなぁ。とりあえずハッカーのイメージを損なうことはやめてほしいけど」
line = "「うーん、特に興味ないから聞かれても答えづらいなぁ。とりあえずハッカーのイメージを損なうことはやめてほしいけど」"

[[dialogue]]
speaker = "コハルコ"
# 「それに最近の彼は手当たり次第というか、自分のスキルを誇示するためにやってるように見える」
line = "「それに最近の彼は手当たり次第というか、自分のスキルを誇示するためにやってるように見える」"

[[dialogue]]
speaker = "コハルコ"
# 「あと名前も好きじゃないし。元々優れたハッカーをウィザードと呼ぶけど、そのまますぎというか……」
line = "「あと名前も好きじゃないし。元々優れたハッカーをウィザードと呼ぶけど、そのまますぎというか……」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふ、コハルコちゃんきびし～」
line = "「ふふ、コハルコちゃんきびし～」"

[[dialogue]]
speaker = "コハルコ"
# 「――って、なんか愚痴っぽくなっちゃった。ごめんごめん」
line = "「――って、なんか愚痴っぽくなっちゃった。ごめんごめん」"

[[dialogue]]
speaker = "コハルコ"
# 「ちなみに、セキュリティ以外にもシステムやプログラム関係の仕事もしてるんだ。今のＤＩＳＣの星騎士用アプリを作ったりとか」
line = "「ちなみに、セキュリティ以外にもシステムやプログラム関係の仕事もしてるんだ。今のＤＩＳＣの星騎士用アプリを作ったりとか」"

[[dialogue]]
speaker = "unk"
# これもコハルコさんが？
line = "これもコハルコさんが？"

[[dialogue]]
speaker = "コハルコ"
# 「うん。会長さんは知らないだろうけど、前のは使いにくかったから新しいの作っちゃった」
line = "「うん。会長さんは知らないだろうけど、前のは使いにくかったから新しいの作っちゃった」"

[[dialogue]]
speaker = "サーシャ"
# 「戦闘中もお話しできて便利よね～。モンスターやアステラを感知するシステムを改良したのもコハルコちゃんだし、ほんと助かってるわ～」
line = "「戦闘中もお話しできて便利よね～。モンスターやアステラを感知するシステムを改良したのもコハルコちゃんだし、ほんと助かってるわ～」"

[[dialogue]]
speaker = "unk"
# あれもこれもコハルコさんなんだ……
line = "あれもこれもコハルコさんなんだ……"

[[dialogue]]
speaker = "コハルコ"
# 「世界を守るためだから。それに新星学園には恩もあるし」
line = "「世界を守るためだから。それに新星学園には恩もあるし」"

[[dialogue]]
speaker = "コハルコ"
# 「あ、そろそろ帰って晩ご飯のお買い物しないと」
line = "「あ、そろそろ帰って晩ご飯のお買い物しないと」"

[[dialogue]]
speaker = "コハルコ"
# 「またね、サーシャ、会長さん」
line = "「またね、サーシャ、会長さん」"
