[[dialogue]]
speaker = "unk"
# 第４話,戦士イングリット,P
line = "第４話,戦士イングリット,P"

[[dialogue]]
speaker = "unk"
# とある休日。久しぶりに羽根を伸ばして買い物しようかと思ったのだが──
line = "とある休日。久しぶりに羽根を伸ばして買い物しようかと思ったのだが──"

[[dialogue]]
speaker = "イングリット"
# 「見つけたぞ、魔王」
line = "「見つけたぞ、魔王」"

[[dialogue]]
speaker = "unk"
# またイングリットに見つかってしまった。
line = "またイングリットに見つかってしまった。"

[[dialogue]]
speaker = "イングリット"
# 「ここで会ったが千年目。いい加減観念して私と戦え、魔王」
line = "「ここで会ったが千年目。いい加減観念して私と戦え、魔王」"

[[dialogue]]
speaker = "unk"
# どうしてそんなに戦いたいんだ？
line = "どうしてそんなに戦いたいんだ？"

[[dialogue]]
speaker = "イングリット"
# 「知れたこと。私は戦士。戦士ならばより強い相手と戦い、最強を目指すのは当然だろう」
line = "「知れたこと。私は戦士。戦士ならばより強い相手と戦い、最強を目指すのは当然だろう」"

[[dialogue]]
speaker = "unk"
# 同郷のフランも似たようなことをよく言っている。
line = "同郷のフランも似たようなことをよく言っている。"

[[dialogue]]
speaker = "unk"
# それに──
line = "それに──"

[[dialogue]]
speaker = "イングリット"
# 『私もコラプサーになりたくてなったわけではない。元は星騎士になるべく鍛錬をしていたのだからな』
line = "『私もコラプサーになりたくてなったわけではない。元は星騎士になるべく鍛錬をしていたのだからな』"

[[dialogue]]
speaker = "unk"
# かつて星騎士を志していた、とも言っていた。
line = "かつて星騎士を志していた、とも言っていた。"

[[dialogue]]
speaker = "unk"
# そんな彼女がなぜコラプサーになったのか気になった。
line = "そんな彼女がなぜコラプサーになったのか気になった。"

[[dialogue]]
speaker = "イングリット"
# 「神妙な顔になったな。フ、いい加減戦う気に──」
line = "「神妙な顔になったな。フ、いい加減戦う気に──」"

[[dialogue]]
speaker = "unk"
# イングリットのことを教えてくれたら戦うかも
line = "イングリットのことを教えてくれたら戦うかも"

[[dialogue]]
speaker = "イングリット"
# 「私のことを……？　貴様はこれから倒す相手のことが気になるのか？　変なやつだな」
line = "「私のことを……？　貴様はこれから倒す相手のことが気になるのか？　変なやつだな」"

[[dialogue]]
speaker = "イングリット"
# 「だがそれで戦う気になるのなら、私のことなどいくらでも教えてやろう」
line = "「だがそれで戦う気になるのなら、私のことなどいくらでも教えてやろう」"

[[dialogue]]
speaker = "イングリット"
# 「私の名はイングリット・ハンゲイト！　コラプサー！　以上！」
line = "「私の名はイングリット・ハンゲイト！　コラプサー！　以上！」"

[[dialogue]]
speaker = "unk"
# 早っ！？
line = "早っ！？"

[[dialogue]]
speaker = "イングリット"
# 「どうだ、私はちゃんと自分のことを話したぞ。約束通り戦ってもらおうか」
line = "「どうだ、私はちゃんと自分のことを話したぞ。約束通り戦ってもらおうか」"

[[dialogue]]
speaker = "イングリット"
# 「……足りない？　もっと昔から話せ？　我がままなやつだな」
line = "「……足りない？　もっと昔から話せ？　我がままなやつだな」"

[[dialogue]]
speaker = "イングリット"
# 「昔というと……天界にいた頃からか」
line = "「昔というと……天界にいた頃からか」"

[[dialogue]]
speaker = "イングリット"
# 「私が生まれた武闘都市ウリルは、戦士の街だ。天界を守るために戦士が集められ、鍛錬を積んでいる」
line = "「私が生まれた武闘都市ウリルは、戦士の街だ。天界を守るために戦士が集められ、鍛錬を積んでいる」"

[[dialogue]]
speaker = "イングリット"
# 「フランのように代々戦士の家系の者もいる。星騎士として流星市国に渡る者も少なくないな」
line = "「フランのように代々戦士の家系の者もいる。星騎士として流星市国に渡る者も少なくないな」"

[[dialogue]]
speaker = "イングリット"
# 「私もその１人で、いずれ星騎士になると信じて疑わなかった」
line = "「私もその１人で、いずれ星騎士になると信じて疑わなかった」"

[[dialogue]]
speaker = "イングリット"
# 「……だが守護星は私を選ばなかった」
line = "「……だが守護星は私を選ばなかった」"

[[dialogue]]
speaker = "イングリット"
# 「新星学園に入るために旅立つフランを見送った。落胆がなかったと言えば嘘になる」
line = "「新星学園に入るために旅立つフランを見送った。落胆がなかったと言えば嘘になる」"

[[dialogue]]
speaker = "イングリット"
# 「いや、嘘だな。別に落ち込んだ記憶はない」
line = "「いや、嘘だな。別に落ち込んだ記憶はない」"

[[dialogue]]
speaker = "unk"
# （嘘なんだ……）
line = "（嘘なんだ……）"

[[dialogue]]
speaker = "イングリット"
# 「私は星騎士になれなかったが、戦士として鍛錬を続けた。より強くなるために」
line = "「私は星騎士になれなかったが、戦士として鍛錬を続けた。より強くなるために」"

[[dialogue]]
speaker = "イングリット"
# 「星騎士など所詮肩書きに過ぎん。武の極致に至れば、星騎士すら超える力を手に入れられる──そう信じて研鑽し続けた」
line = "「星騎士など所詮肩書きに過ぎん。武の極致に至れば、星騎士すら超える力を手に入れられる──そう信じて研鑽し続けた」"

[[dialogue]]
speaker = "イングリット"
# 「そしてウリルにモンスターが現れ……私は戦った。星力はなかったが、当然勝つつもりだった」
line = "「そしてウリルにモンスターが現れ……私は戦った。星力はなかったが、当然勝つつもりだった」"

[[dialogue]]
speaker = "イングリット"
# 「だがモンスターに爪で引き裂かれ、殺されかけて……命尽きる前にコラプサーの力に目覚めた」
line = "「だがモンスターに爪で引き裂かれ、殺されかけて……命尽きる前にコラプサーの力に目覚めた」"

[[dialogue]]
speaker = "イングリット"
# 「私はモンスターを斬って斬って斬りまくった。当初思い描いたものとは違ったが、それでも力は力だ。あの時は昂ったものだ」
line = "「私はモンスターを斬って斬って斬りまくった。当初思い描いたものとは違ったが、それでも力は力だ。あの時は昂ったものだ」"

[[dialogue]]
speaker = "イングリット"
# 「それからウリルの戦士連中を片っ端から倒し、星騎士と戦おうと大交流に紛れようとしたが、上手くいかなくてな」
line = "「それからウリルの戦士連中を片っ端から倒し、星騎士と戦おうと大交流に紛れようとしたが、上手くいかなくてな」"

[[dialogue]]
speaker = "イングリット"
# 「コラプサーの連中に声をかけられたのはその時だ」
line = "「コラプサーの連中に声をかけられたのはその時だ」"

[[dialogue]]
speaker = "unk"
# 何のために強さを求める？
line = "何のために強さを求める？"

[[dialogue]]
speaker = "イングリット"
# 「クッ──」
line = "「クッ──」"

[[dialogue]]
speaker = "イングリット"
# 「ククク、ハハハハハッ！　愚かだな魔王！　そんなことも分からないのか！」
line = "「ククク、ハハハハハッ！　愚かだな魔王！　そんなことも分からないのか！」"

[[dialogue]]
speaker = "イングリット"
# 「そんなの<b>楽しい</b>からに決まっているだろう！」
line = "「そんなの<b>楽しい</b>からに決まっているだろう！」"

[[dialogue]]
speaker = "イングリット"
# 「研鑽の末に感じる力の高まり……強敵と対峙した時のヒリつく緊張と高揚……そしてその強敵を打ち破る達成感」
line = "「研鑽の末に感じる力の高まり……強敵と対峙した時のヒリつく緊張と高揚……そしてその強敵を打ち破る達成感」"

[[dialogue]]
speaker = "イングリット"
# 「戦士イングリットはその快感を喰らって生きている！　戦いより楽しいことなんてないじゃないか！」
line = "「戦士イングリットはその快感を喰らって生きている！　戦いより楽しいことなんてないじゃないか！」"

[[dialogue]]
speaker = "イングリット"
# 「だから魔王……私は貴様を求めている」
line = "「だから魔王……私は貴様を求めている」"

[[dialogue]]
speaker = "イングリット"
# 「今一番興味があるのは貴様だ。私は貴様ともっともっと戦いたい！」
line = "「今一番興味があるのは貴様だ。私は貴様ともっともっと戦いたい！」"

[[dialogue]]
speaker = "イングリット"
# 「それにな。戦士というものは、力あっての戦士だ」
line = "「それにな。戦士というものは、力あっての戦士だ」"

[[dialogue]]
speaker = "イングリット"
# 「貴様がこの刀だったとして、<ruby=なまく>鈍</ruby>らのままでありたいか？　より鋭い刃でありたいと思わないのか？」
line = "「貴様がこの刀だったとして、<ruby>鈍<rt>なまく</rt></ruby>らのままでありたいか？　より鋭い刃でありたいと思わないのか？」"

[[dialogue]]
speaker = "イングリット"
# 「戦士も同じこと。強ければ強いほどいい」
line = "「戦士も同じこと。強ければ強いほどいい」"

[[dialogue]]
speaker = "イングリット"
# 「……ふぅ。随分と話したな。これで戦わないと言い出したら、ここで暴れるぞ？」
line = "「……ふぅ。随分と話したな。これで戦わないと言い出したら、ここで暴れるぞ？」"

[[dialogue]]
speaker = "イングリット"
# 「ん？　なんだこの音は」
line = "「ん？　なんだこの音は」"

[[dialogue]]
speaker = "イングリット"
# 「……近くでモンスターが出現した？　知るか。魔王は私と戦え」
line = "「……近くでモンスターが出現した？　知るか。魔王は私と戦え」"

[[dialogue]]
speaker = "unk"
# モンスターを倒してくれたら戦うよ
line = "モンスターを倒してくれたら戦うよ"

[[dialogue]]
speaker = "イングリット"
# 「何？　また注文だと？　魔王は人遣いが荒いな……」
line = "「何？　また注文だと？　魔王は人遣いが荒いな……」"

[[dialogue]]
speaker = "unk"
# （イングリットに言われたくない）
line = "（イングリットに言われたくない）"

[[dialogue]]
speaker = "イングリット"
# 「まぁいい。魔王と戦う前の肩慣らしといくか」
line = "「まぁいい。魔王と戦う前の肩慣らしといくか」"

[[dialogue]]
speaker = "イングリット"
# 「ダーク・オブリビオン！」
line = "「ダーク・オブリビオン！」"

[[dialogue]]
speaker = "unk"
# イングリットの行いが正しいとは思わないが、それでも彼女を少し理解できた気がする。
line = "イングリットの行いが正しいとは思わないが、それでも彼女を少し理解できた気がする。"

[[dialogue]]
speaker = "unk"
# だから彼女と戦う時は、学園とかコラプサーとか関係なく、ただ１人の戦士として清々しく戦いたいと思うのだった。
line = "だから彼女と戦う時は、学園とかコラプサーとか関係なく、ただ１人の戦士として清々しく戦いたいと思うのだった。"
