[[dialogue]]
speaker = "unk"
# 第４話,探偵の恋愛事情,P
line = "第４話,探偵の恋愛事情,P"

[[dialogue]]
speaker = "unk"
# ジュエリーの助手として、付き合いも長くなって来た頃――
line = "ジュエリーの助手として、付き合いも長くなって来た頃――"

[[dialogue]]
speaker = "依頼人の女生徒"
# 「先日の事件、ありがとうございました。犯人が捕まって、これで安心して元の生活に戻れます」
line = "「先日の事件、ありがとうございました。犯人が捕まって、これで安心して元の生活に戻れます」"

[[dialogue]]
speaker = "ジュエリー"
# 「なに、私は探偵としての使命を果たしたまでさ。困った時はまた気軽に相談してくれたまえ」
line = "「なに、私は探偵としての使命を果たしたまでさ。困った時はまた気軽に相談してくれたまえ」"

[[dialogue]]
speaker = "依頼人の女生徒"
# 「はい。本当にありがとうございます、日傘探偵さん！　それではまた！」
line = "「はい。本当にありがとうございます、日傘探偵さん！　それではまた！」"

[[dialogue]]
speaker = "unk"
# 無事に事件解決して、良かったね
line = "無事に事件解決して、良かったね"

[[dialogue]]
speaker = "ジュエリー"
# 「ああ。キミが助手としてサポートしてくれたおかげさ。ありがとう」
line = "「ああ。キミが助手としてサポートしてくれたおかげさ。ありがとう」"

[[dialogue]]
speaker = "ジュエリー"
# 「愛しているよ、我が助手」
line = "「愛しているよ、我が助手」"

[[dialogue]]
speaker = "unk"
# （親愛か恋愛か、正直わからないよな……）
line = "（親愛か恋愛か、正直わからないよな……）"

[[dialogue]]
speaker = "unk"
# （ジュエリーはいつもそう言うけど……）
line = "（ジュエリーはいつもそう言うけど……）"

[[dialogue]]
speaker = "unk"
# 俺は意を決して、ジュエリーに提案をした。
line = "俺は意を決して、ジュエリーに提案をした。"

[[dialogue]]
speaker = "ジュエリー"
# 「……ん？　明日の休日？　ああ、予定は特に無いが……え？」
line = "「……ん？　明日の休日？　ああ、予定は特に無いが……え？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふふっ、まさかキミからデートに誘われるとはね。一体、どういう風の吹き回しだい？」
line = "「ふふっ、まさかキミからデートに誘われるとはね。一体、どういう風の吹き回しだい？」"

[[dialogue]]
speaker = "ジュエリー"
# 「何かそういう気分だった？　ふむ、日頃私がキミに愛をささやき続けたことが、功を奏したといったところか♪」
line = "「何かそういう気分だった？　ふむ、日頃私がキミに愛をささやき続けたことが、功を奏したといったところか♪」"

[[dialogue]]
speaker = "ジュエリー"
# 「デートくらいは男がリードするもの？　ほう、つまり今日はキミが、私を楽しませてくれるということだね」
line = "「デートくらいは男がリードするもの？　ほう、つまり今日はキミが、私を楽しませてくれるということだね」"

[[dialogue]]
speaker = "ジュエリー"
# 「そう思うと、何だか好奇心でワクワクして来てしまうじゃないか。キミに限らず、男性とのデートは生まれて初めてなのでね」
line = "「そう思うと、何だか好奇心でワクワクして来てしまうじゃないか。キミに限らず、男性とのデートは生まれて初めてなのでね」"

[[dialogue]]
speaker = "ジュエリー"
# 「それにしても、誰かから遊びに誘われるなんて、一体いつ以来だろうか？」
line = "「それにしても、誰かから遊びに誘われるなんて、一体いつ以来だろうか？」"

[[dialogue]]
speaker = "unk"
# （やっぱり、親しい友達のノリなんだよな）
line = "（やっぱり、親しい友達のノリなんだよな）"

[[dialogue]]
speaker = "ジュエリー"
# 「おや？　どうしたんだい？　おもむろに近付いて来て……デートだから手を繋ぐ？」
line = "「おや？　どうしたんだい？　おもむろに近付いて来て……デートだから手を繋ぐ？」"

[[dialogue]]
speaker = "ジュエリー"
# 「そういえば、あまり考えたことがなかったが、私たちは手を繋ぐのも初めてだったね。いいだろう、試してみようじゃないか」
line = "「そういえば、あまり考えたことがなかったが、私たちは手を繋ぐのも初めてだったね。いいだろう、試してみようじゃないか」"

[[dialogue]]
speaker = "ジュエリー"
# 「おっ、おぉぉっ……！？　これが異性の手を繋ぐ感覚、というものか……」
line = "「おっ、おぉぉっ……！？　これが異性の手を繋ぐ感覚、というものか……」"

[[dialogue]]
speaker = "ジュエリー"
# 「手の感触も、意識すると情報量が多いな。肌と肌を触れ合わせるというのは、意外と心地良いものなのだな」
line = "「手の感触も、意識すると情報量が多いな。肌と肌を触れ合わせるというのは、意外と心地良いものなのだな」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふふっ、これまで自分からしようとは思わなかったが、やってみると面白い。……なに、手の繋ぎ方を変える？」
line = "「ふふっ、これまで自分からしようとは思わなかったが、やってみると面白い。……なに、手の繋ぎ方を変える？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ほう、恋人繋ぎ？　指と指を絡めるやつか。どれ、試してみようじゃないか――」
line = "「ほう、恋人繋ぎ？　指と指を絡めるやつか。どれ、試してみようじゃないか――」"

[[dialogue]]
speaker = "ジュエリー"
# 「んっ……！　これはまた、触れ合う面積が広がって、強く繋がっている感じがするな。見た目も明らかに、友人ではなく恋人だと分かる感じが……はっ！」
line = "「んっ……！　これはまた、触れ合う面積が広がって、強く繋がっている感じがするな。見た目も明らかに、友人ではなく恋人だと分かる感じが……はっ！」"

[[dialogue]]
speaker = "ジュエリー"
# 「なるほど、そういうことか！　キミの考えが分かったぞ、助手！」
line = "「なるほど、そういうことか！　キミの考えが分かったぞ、助手！」"

[[dialogue]]
speaker = "unk"
# （俺の好意が、ちゃんと伝わった……！？）
line = "（俺の好意が、ちゃんと伝わった……！？）"

[[dialogue]]
speaker = "ジュエリー"
# 「明解に換言するならば……ズバリ、これは恋人になった時の練習ということだな！」
line = "「明解に換言するならば……ズバリ、これは恋人になった時の練習ということだな！」"

[[dialogue]]
speaker = "ジュエリー"
# 「私たちは運命の相手であるが故、いずれ恋人になるのは必然。すなわち今日のデートは、その為の予行練習！　そうだろう、助手？」
line = "「私たちは運命の相手であるが故、いずれ恋人になるのは必然。すなわち今日のデートは、その為の予行練習！　そうだろう、助手？」"

[[dialogue]]
speaker = "unk"
# （そうじゃない……！）
line = "（そうじゃない……！）"

[[dialogue]]
speaker = "ジュエリー"
# 「いやはや、キミのそういうさり気ない心遣いは嬉しいね。時間は短くなるが、昼間ではなく夜にデートすることにしたのも、私の体質を気遣ってのことだろう？」
line = "「いやはや、キミのそういうさり気ない心遣いは嬉しいね。時間は短くなるが、昼間ではなく夜にデートすることにしたのも、私の体質を気遣ってのことだろう？」"

[[dialogue]]
speaker = "ジュエリー"
# 「そういう優しいところが好みだ。心から愛しているよ、我が助手」
line = "「そういう優しいところが好みだ。心から愛しているよ、我が助手」"

[[dialogue]]
speaker = "ジュエリー"
# 「って、どうしたんだい？　何か考え込んでいるような様子だが……」
line = "「って、どうしたんだい？　何か考え込んでいるような様子だが……」"

[[dialogue]]
speaker = "unk"
# （もう直接、好きと言うしかないのでは？）
line = "（もう直接、好きと言うしかないのでは？）"

[[dialogue]]
speaker = "unk"
# そうして口に出して伝えるタイミングを見計らいながら、しばらくデートを続け――
line = "そうして口に出して伝えるタイミングを見計らいながら、しばらくデートを続け――"

[[dialogue]]
speaker = "ジュエリー"
# 「良い中古ゲームショップを見つけてしまったな！　まさか念願のレア物をあんなにも安く手に入れられてしまうとは♪」
line = "「良い中古ゲームショップを見つけてしまったな！　まさか念願のレア物をあんなにも安く手に入れられてしまうとは♪」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふふっ、はしゃぎもするさ。これは世にも珍しい、２人共同プレイが可能なシミュレーションＲＰＧなんだ」
line = "「ふふっ、はしゃぎもするさ。これは世にも珍しい、２人共同プレイが可能なシミュレーションＲＰＧなんだ」"

[[dialogue]]
speaker = "ジュエリー"
# 「手に入れたら友人と一緒にやってみたいと、前から思っていたんだよ。今度、私の家で攻略しようじゃないか」
line = "「手に入れたら友人と一緒にやってみたいと、前から思っていたんだよ。今度、私の家で攻略しようじゃないか」"

[[dialogue]]
speaker = "ジュエリー"
# 「部屋がまた散らかっているんじゃないかって？　だが、いつもみたいに助手が手伝ってくれるだろう？」
line = "「部屋がまた散らかっているんじゃないかって？　だが、いつもみたいに助手が手伝ってくれるだろう？」"

[[dialogue]]
speaker = "unk"
# だって俺は、ジュエリーのことが好きだから
line = "だって俺は、ジュエリーのことが好きだから"

[[dialogue]]
speaker = "unk"
# いつだって手伝うよ
line = "いつだって手伝うよ"

[[dialogue]]
speaker = "ジュエリー"
# 「ははっ、そうだろう。何せ助手は私のことが……ん？」
line = "「ははっ、そうだろう。何せ助手は私のことが……ん？」"

[[dialogue]]
speaker = "ジュエリー"
# 「待ちたまえ、助手。今、キミは私のことが<b>好き</b>と言ったのかい？」
line = "「待ちたまえ、助手。今、キミは私のことが<b>好き</b>と言ったのかい？」"

[[dialogue]]
speaker = "ジュエリー"
# 「……気付いたんだが、キミに好きと言われるのは、これが初めてではないか？」
line = "「……気付いたんだが、キミに好きと言われるのは、これが初めてではないか？」"

[[dialogue]]
speaker = "unk"
# どうして言ったと思う？
line = "どうして言ったと思う？"

[[dialogue]]
speaker = "unk"
# うん、合ってる
line = "うん、合ってる"

[[dialogue]]
speaker = "ジュエリー"
# 「む？　それは当然……キミも私のことが、好きだからじゃないか？」
line = "「む？　それは当然……キミも私のことが、好きだからじゃないか？」"

[[dialogue]]
speaker = "ジュエリー"
# 「なに、問題……？」
line = "「なに、問題……？」"

[[dialogue]]
speaker = "unk"
# 今初めて、好きと言ったのは何故でしょう？
line = "今初めて、好きと言ったのは何故でしょう？"

[[dialogue]]
speaker = "unk"
# 前からずっと仲良くしてるのに……
line = "前からずっと仲良くしてるのに……"

[[dialogue]]
speaker = "ジュエリー"
# 「え……？　ええと……それはおそらく、今日デートに誘われたことに意味が――あっ……！」
line = "「え……？　ええと……それはおそらく、今日デートに誘われたことに意味が――あっ……！」"

[[dialogue]]
speaker = "ジュエリー"
# 「ま、待つんだ助手。そういうことなのか……！？　いやしかし、私の想像が合っているとは限らないし……！」
line = "「ま、待つんだ助手。そういうことなのか……！？　いやしかし、私の想像が合っているとは限らないし……！」"

[[dialogue]]
speaker = "unk"
# 名探偵なのに？
line = "名探偵なのに？"

[[dialogue]]
speaker = "ジュエリー"
# 「わ、私にだって、分からないことはあるんだっ！」
line = "「わ、私にだって、分からないことはあるんだっ！」"

[[dialogue]]
speaker = "ジュエリー"
# 「って、何を嬉しそうにニヤニヤしているんだ助手っ。それも想像しろって？　い、意地悪だぞっ」
line = "「って、何を嬉しそうにニヤニヤしているんだ助手っ。それも想像しろって？　い、意地悪だぞっ」"

[[dialogue]]
speaker = "unk"
# ジュエリーはそう言って、日傘で赤くなった顔を隠そうとする。俺はちゃんと彼女が自分を意識してくれたことに、嬉しくなってしまうのだった――
line = "ジュエリーはそう言って、日傘で赤くなった顔を隠そうとする。俺はちゃんと彼女が自分を意識してくれたことに、嬉しくなってしまうのだった――"
