[[dialogue]]
speaker = "unk"
# 第１話,甘々な守護天使,P
line = "第１話,甘々な守護天使,P"

[[dialogue]]
speaker = "unk"
# ある日の夜、俺は星徒会で残業を終えたところだったのだが――
line = "ある日の夜、俺は星徒会で残業を終えたところだったのだが――"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「会長、今日も１日、お仕事お疲れ様でした♪」
line = "「会長、今日も１日、お仕事お疲れ様でした♪」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「というわけで～、ママダレナが膝枕で癒しちゃいますね～♪　よしよし♪」
line = "「というわけで～、ママダレナが膝枕で癒しちゃいますね～♪　よしよし♪」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「って、会長、どうしました？　恥ずかしそうに顔を背けたりして」
line = "「って、会長、どうしました？　恥ずかしそうに顔を背けたりして」"

[[dialogue]]
speaker = "unk"
# 膝枕は嬉しいんだけど、その……
line = "膝枕は嬉しいんだけど、その……"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「――私の体が小さいから、仰向けになると顔にお胸が当たっちゃう？」
line = "「――私の体が小さいから、仰向けになると顔にお胸が当たっちゃう？」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「あ～、そういうことですか。うふふ♪　会長ったら耳まで赤くしちゃって、可愛い<emoji=heart04>」
line = "「あ～、そういうことですか。うふふ♪　会長ったら耳まで赤くしちゃって、可愛い<emoji=heart04>」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「恋人なんですから、そんなこと気にせず、ママダレナに甘えてもいいんですよ？　柔らかいクッションだと思って♪」
line = "「恋人なんですから、そんなこと気にせず、ママダレナに甘えてもいいんですよ？　柔らかいクッションだと思って♪」"

[[dialogue]]
speaker = "unk"
# しばらく前、俺はマグダレナに好意を伝えて、恋人関係になっていた。
line = "しばらく前、俺はマグダレナに好意を伝えて、恋人関係になっていた。"

[[dialogue]]
speaker = "unk"
# ただその後、本体アバターが一時使用不能になる事件があって、彼女はその時に代わりのスペアボディ『幼アバター』を使うようになった。
line = "ただその後、本体アバターが一時使用不能になる事件があって、彼女はその時に代わりのスペアボディ『幼アバター』を使うようになった。"

[[dialogue]]
speaker = "unk"
# 本体アバターに戻れるようになった今も、附属校に通う学生生活を気に入っているようで、最近はこちらの姿でいることが多い。ただ――
line = "本体アバターに戻れるようになった今も、附属校に通う学生生活を気に入っているようで、最近はこちらの姿でいることが多い。ただ――"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「む～っ、会長は、なかなか私のことをママダレナって呼んでくれませんね～。えいっ、頬っぺたつんつん」
line = "「む～っ、会長は、なかなか私のことをママダレナって呼んでくれませんね～。えいっ、頬っぺたつんつん」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「もっと子供みたいに甘えて欲しいのに～」
line = "「もっと子供みたいに甘えて欲しいのに～」"

[[dialogue]]
speaker = "unk"
# マグダレナが小さな体でいる時は、どうやら『みんなのママになりたい』という欲求が強くなっているらしく、周りに『ママダレナ』と呼んで欲しいと、よく口にする。
line = "マグダレナが小さな体でいる時は、どうやら『みんなのママになりたい』という欲求が強くなっているらしく、周りに『ママダレナ』と呼んで欲しいと、よく口にする。"

[[dialogue]]
speaker = "unk"
# 恋人としては、なるべく彼女のお願いに応えてあげたいとも思うが、その一方で――
line = "恋人としては、なるべく彼女のお願いに応えてあげたいとも思うが、その一方で――"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「……え？　――恋人だからこそ、普通に下の名前で呼びたい、ですか？」
line = "「……え？　――恋人だからこそ、普通に下の名前で呼びたい、ですか？」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「なるほど。甘えるなら、ママとしての私ではなく、恋人としての方がいいということですね……」
line = "「なるほど。甘えるなら、ママとしての私ではなく、恋人としての方がいいということですね……」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ごめんなさい、会長。私、そこまで気が回らなくて」
line = "「ごめんなさい、会長。私、そこまで気が回らなくて」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「守護天使として生まれてから、長いこと存在してきましたが、男女のお付き合いをするのは会長が初めてなので……私もまだまだ、恋愛初心者ですね」
line = "「守護天使として生まれてから、長いこと存在してきましたが、男女のお付き合いをするのは会長が初めてなので……私もまだまだ、恋愛初心者ですね」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「でも、それはそれとして、２人きりの時はママダレナになって、会長に甘えて欲しいな～とも思ってしまいます」
line = "「でも、それはそれとして、２人きりの時はママダレナになって、会長に甘えて欲しいな～とも思ってしまいます」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「恋人だからこそ、甘々な関係を楽しみたいと言いますか……」
line = "「恋人だからこそ、甘々な関係を楽しみたいと言いますか……」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「お互いに甘やかして、甘やかされる関係って、なんだかよくないですか？」
line = "「お互いに甘やかして、甘やかされる関係って、なんだかよくないですか？」"

[[dialogue]]
speaker = "unk"
# マグダレナも甘えたいんだ？
line = "マグダレナも甘えたいんだ？"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ダメ……ですか？」
line = "「ダメ……ですか？」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「――ママというより、むしろ子供っぽい？」
line = "「――ママというより、むしろ子供っぽい？」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「え～、そんな～！」
line = "「え～、そんな～！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「――って、笑わないで下さいよ、会長～」
line = "「――って、笑わないで下さいよ、会長～」"

[[dialogue]]
speaker = "unk"
# このまま少し休んでもいい？
line = "このまま少し休んでもいい？"

[[dialogue]]
speaker = "unk"
# じゃあ、ママダレナ
line = "じゃあ、ママダレナ"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「……あ！　えへへ♪　もちろんですよ～」
line = "「……あ！　えへへ♪　もちろんですよ～」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ママダレナの膝枕で、ゆっくり休んで下さいね♪」
line = "「ママダレナの膝枕で、ゆっくり休んで下さいね♪」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「今日１日、よく頑張りました。えらいえらい♪」
line = "「今日１日、よく頑張りました。えらいえらい♪」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ふふっ……♪」
line = "「ふふっ……♪」"

[[dialogue]]
speaker = "unk"
# ――恋人っぽいかはわからないけど、彼女が幸せそうなら、今はそれでいいか。
line = "――恋人っぽいかはわからないけど、彼女が幸せそうなら、今はそれでいいか。"

[[dialogue]]
speaker = "unk"
# そう思って、心地良い微睡みに身を委ねる俺なのだった。
line = "そう思って、心地良い微睡みに身を委ねる俺なのだった。"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# （会長、寝ちゃったみたいですね）
line = "（会長、寝ちゃったみたいですね）"

[[dialogue]]
speaker = "unk"
# マグダレナは、目を瞑る恋人の頭を優しく撫でる。
line = "マグダレナは、目を瞑る恋人の頭を優しく撫でる。"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# （本当は面と向かって、素直に伝えられたらいいのですが……）
line = "（本当は面と向かって、素直に伝えられたらいいのですが……）"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# （恋人同士でも、いざ面と向かってだと、恥ずかしくなってしまって、なかなか言えないんですよね）
line = "（恋人同士でも、いざ面と向かってだと、恥ずかしくなってしまって、なかなか言えないんですよね）"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「――いつも私を甘えさせてくれて、ありがとうございます。会長……」
line = "「――いつも私を甘えさせてくれて、ありがとうございます。会長……」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「愛しています……<emoji=heart04>」
line = "「愛しています……<emoji=heart04>」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ちゅっ……<emoji=heart04>」
line = "「ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# マグダレナは恋人の頬っぺたに、そっとキスを落とす――
line = "マグダレナは恋人の頬っぺたに、そっとキスを落とす――"

[[dialogue]]
speaker = "unk"
# ……俺も、愛してる
line = "……俺も、愛してる"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ひゃっ！？　か、会長、まさか起きて……！？」
line = "「ひゃっ！？　か、会長、まさか起きて……！？」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「あ、あわわわ……」
line = "「あ、あわわわ……」"

[[dialogue]]
speaker = "unk"
# わざとじゃないんだけど、ごめん
line = "わざとじゃないんだけど、ごめん"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「は、恥ずかしいです……」
line = "「は、恥ずかしいです……」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「はうぅ……」
line = "「はうぅ……」"

[[dialogue]]
speaker = "unk"
# 顔を赤くして照れるマグダレナ。俺は起き上がると、今度は彼女の頭を優しく撫でるのだった――
line = "顔を赤くして照れるマグダレナ。俺は起き上がると、今度は彼女の頭を優しく撫でるのだった――"
