[[dialogue]]
speaker = "unk"
# 第４話,転生したら２０００年後だった件,P
line = "第４話,転生したら２０００年後だった件,P"

[[dialogue]]
speaker = "unk"
# ある日の放課後、俺は紅明に呼び出され、何故かアリーナで向かい合っていた──
line = "ある日の放課後、俺は紅明に呼び出され、何故かアリーナで向かい合っていた──"

[[dialogue]]
speaker = "紅明"
# 「ダーリン、よくぞここまで来た！！！　アタシと戦って勝ったなら、重大な秘密を教えてしんぜよう！」
line = "「ダーリン、よくぞここまで来た！！！　アタシと戦って勝ったなら、重大な秘密を教えてしんぜよう！」"

[[dialogue]]
speaker = "unk"
# どうした急に
line = "どうした急に"

[[dialogue]]
speaker = "紅明"
# 「気付けば、ダーリンとの付き合いも幾星霜。アタシに対する好感度も、いい感じに上がって来た頃合いっしょ？」
line = "「気付けば、ダーリンとの付き合いも幾星霜。アタシに対する好感度も、いい感じに上がって来た頃合いっしょ？」"

[[dialogue]]
speaker = "紅明"
# 「そろそろアタシの真実を話してもいいんじゃないかと思ってね☆」
line = "「そろそろアタシの真実を話してもいいんじゃないかと思ってね☆」"

[[dialogue]]
speaker = "unk"
# それ戦う意味ある？
line = "それ戦う意味ある？"

[[dialogue]]
speaker = "紅明"
# 「ラブ・イズ・ウォー！　愛とは戦いなのだよ、ダーリン♪」
line = "「ラブ・イズ・ウォー！　愛とは戦いなのだよ、ダーリン♪」"

[[dialogue]]
speaker = "紅明"
# 「そう、アタシの秘密……それは今から遡ること２０００年前──」
line = "「そう、アタシの秘密……それは今から遡ること２０００年前──」"

[[dialogue]]
speaker = "unk"
# 結局、先に語るんかーーい！
line = "結局、先に語るんかーーい！"

[[dialogue]]
speaker = "紅明"
# 「アタシの<b>前世</b>は、かの西遊記に登場する魔族──」
line = "「アタシの<b>前世</b>は、かの西遊記に登場する魔族──」"

[[dialogue]]
speaker = "紅明"
# 「牛魔王の娘『<ruby=こうがいじ>紅孩児</ruby>』であった……」
line = "「牛魔王の娘『<ruby>紅孩児<rt>こうがいじ</rt></ruby>』であった……」"

[[dialogue]]
speaker = "unk"
# あー、はいはい。前世っていうか祖先の話ね
line = "あー、はいはい。前世っていうか祖先の話ね"

[[dialogue]]
speaker = "紅明"
# 「そう、ダーリンには以前話したことがあったね！　アタシのこの体は、確かに紅孩児の子孫のもの」
line = "「そう、ダーリンには以前話したことがあったね！　アタシのこの体は、確かに紅孩児の子孫のもの」"

[[dialogue]]
speaker = "紅明"
# 「そして、びっくりすることに当時のアタシと外見が瓜二つ！」
line = "「そして、びっくりすることに当時のアタシと外見が瓜二つ！」"

[[dialogue]]
speaker = "紅明"
# 「つまり、アタシの正体は──」
line = "「つまり、アタシの正体は──」"

[[dialogue]]
speaker = "紅明"
# 「実は２０００年後の現代に転生した、紅孩児本人だったんだよ！！！」
line = "「実は２０００年後の現代に転生した、紅孩児本人だったんだよ！！！」"

[[dialogue]]
speaker = "unk"
# な、なんだってー（棒）
line = "な、なんだってー（棒）"

[[dialogue]]
speaker = "紅明"
# 「ダーリンの信じられない気持ち、分かるぜ！　アタシもどうして転生したのかよくわかってないから、生まれてこの方、今の両親にだって打ち明けたことがなかったしね」
line = "「ダーリンの信じられない気持ち、分かるぜ！　アタシもどうして転生したのかよくわかってないから、生まれてこの方、今の両親にだって打ち明けたことがなかったしね」"

[[dialogue]]
speaker = "紅明"
# 「それに２０００年前、事故死したとかそういうことでもなく、アタシは娘や孫達に囲まれながら天寿を全うした記憶もある」
line = "「それに２０００年前、事故死したとかそういうことでもなく、アタシは娘や孫達に囲まれながら天寿を全うした記憶もある」"

[[dialogue]]
speaker = "紅明"
# 「ただ、リクリエが間近に迫りつつある今だからこそ、お釈迦様の導きで現代に呼ばれたのかなって気はしてるよ」
line = "「ただ、リクリエが間近に迫りつつある今だからこそ、お釈迦様の導きで現代に呼ばれたのかなって気はしてるよ」"

[[dialogue]]
speaker = "unk"
# じゃあ、三蔵法師一行も転生してるってこと？
line = "じゃあ、三蔵法師一行も転生してるってこと？"

[[dialogue]]
speaker = "紅明"
# 「ダーリン、いいところに気付いた！」
line = "「ダーリン、いいところに気付いた！」"

[[dialogue]]
speaker = "紅明"
# 「それについては、アタシも可能性は高いんじゃないかと思ってる。残念ながら、まだ見つけられてはいないんだけど」
line = "「それについては、アタシも可能性は高いんじゃないかと思ってる。残念ながら、まだ見つけられてはいないんだけど」"

[[dialogue]]
speaker = "紅明"
# 「アタシが転生したのに、悟空やお師匠様が呼ばれないって手落ち感あるしね！」
line = "「アタシが転生したのに、悟空やお師匠様が呼ばれないって手落ち感あるしね！」"

[[dialogue]]
speaker = "紅明"
# 「豚や河童の魔族も分かりやすいし、学園では見かけ次第声を掛けたりしてんだけど……うーん、何だろう？　何か反応的に違うっぽいんだよね～」
line = "「豚や河童の魔族も分かりやすいし、学園では見かけ次第声を掛けたりしてんだけど……うーん、何だろう？　何か反応的に違うっぽいんだよね～」"

[[dialogue]]
speaker = "unk"
# ……本当に紅孩児なの？
line = "……本当に紅孩児なの？"

[[dialogue]]
speaker = "紅明"
# 「マジも大マジなんだな～、これが！」
line = "「マジも大マジなんだな～、これが！」"

[[dialogue]]
speaker = "紅明"
# 「アタシが前世で紅孩児だった証拠が何か示せればいいんだけどね～。当時は写真なんてものは無いから、アタシの見た目が今と瓜二つなんだってのも、見せられないしな～」
line = "「アタシが前世で紅孩児だった証拠が何か示せればいいんだけどね～。当時は写真なんてものは無いから、アタシの見た目が今と瓜二つなんだってのも、見せられないしな～」"

[[dialogue]]
speaker = "紅明"
# 「あ、でも１つだけあるわ！　証拠になるかわからんけど……」
line = "「あ、でも１つだけあるわ！　証拠になるかわからんけど……」"

[[dialogue]]
speaker = "紅明"
# 「ダーリンは『<ruby=べにひさご>紅瓢</ruby>』って知ってる？　西遊記に登場する<ruby=ひょうたん>瓢箪</ruby>なんだけど」
line = "「ダーリンは『<ruby>紅瓢<rt>べにひさご</rt></ruby>』って知ってる？　西遊記に登場する<ruby>瓢箪<rt>ひょうたん</rt></ruby>なんだけど」"

[[dialogue]]
speaker = "unk"
# 金角と銀角が使っていたっていう……？
line = "金角と銀角が使っていたっていう……？"

[[dialogue]]
speaker = "紅明"
# 「物語だとそうなってるね！　それって実は、当時敵だったアタシがお師匠様一行を倒す為に、金銀姉妹に貸したやつだったんだよ！」
line = "「物語だとそうなってるね！　それって実は、当時敵だったアタシがお師匠様一行を倒す為に、金銀姉妹に貸したやつだったんだよ！」"

[[dialogue]]
speaker = "紅明"
# 「それから、呼び掛けて返事をすると、中に吸い込まれてしまうって瓢箪の話は、正確には返事した相手から元気を吸い込む能力のこと」
line = "「それから、呼び掛けて返事をすると、中に吸い込まれてしまうって瓢箪の話は、正確には返事した相手から元気を吸い込む能力のこと」"

[[dialogue]]
speaker = "紅明"
# 「うむ！！！　アタシが戦闘中に使ってる、この背中の紅い瓢箪。これが２０００年前から使っているアタシの相棒、紅瓢なんだよね！」
line = "「うむ！！！　アタシが戦闘中に使ってる、この背中の紅い瓢箪。これが２０００年前から使っているアタシの相棒、紅瓢なんだよね！」"

[[dialogue]]
speaker = "紅明"
# 「でもまあ、これも口では何とでも言えるから、信じてもらえるかわからんけども……」
line = "「でもまあ、これも口では何とでも言えるから、信じてもらえるかわからんけども……」"

[[dialogue]]
speaker = "unk"
# どうして転生の話を、俺に打ち明けたんだ……？
line = "どうして転生の話を、俺に打ち明けたんだ……？"

[[dialogue]]
speaker = "紅明"
# 「親にも話してないのに、ダーリンに打ち明けた理由？」
line = "「親にも話してないのに、ダーリンに打ち明けた理由？」"

[[dialogue]]
speaker = "紅明"
# 「それは、ダーリンだからこそ、かな」
line = "「それは、ダーリンだからこそ、かな」"

[[dialogue]]
speaker = "紅明"
# 「ほら、最近はすっかり慣れて言わなくなったけど、何でダーリンって呼ぶのか、最初の頃にツッコんでたじゃん？」
line = "「ほら、最近はすっかり慣れて言わなくなったけど、何でダーリンって呼ぶのか、最初の頃にツッコんでたじゃん？」"

[[dialogue]]
speaker = "紅明"
# 「それってさ……実はダーリンが、アタシの当時のダーリンと瓜二つだからなんだよね♪」
line = "「それってさ……実はダーリンが、アタシの当時のダーリンと瓜二つだからなんだよね♪」"

[[dialogue]]
speaker = "unk"
# な……！
line = "な……！"

[[dialogue]]
speaker = "紅明"
# 「ダーリンはそんな記憶持ってないみたいだし、世の中には激似の人が３人は居るっていうしね！」
line = "「ダーリンはそんな記憶持ってないみたいだし、世の中には激似の人が３人は居るっていうしね！」"

[[dialogue]]
speaker = "紅明"
# 「実際はただの偶然、他人の空似なんだろうなって思うけど、でも……」
line = "「実際はただの偶然、他人の空似なんだろうなって思うけど、でも……」"

[[dialogue]]
speaker = "紅明"
# 「仲良くなってもやっぱり、ダーリンはダーリンに似てるから、アタシのこと、知ってて欲しかったんだよね♪」
line = "「仲良くなってもやっぱり、ダーリンはダーリンに似てるから、アタシのこと、知ってて欲しかったんだよね♪」"

[[dialogue]]
speaker = "紅明"
# 「ってダーリン、ひょっとして照れてる？　顔赤いよ？」
line = "「ってダーリン、ひょっとして照れてる？　顔赤いよ？」"

[[dialogue]]
speaker = "unk"
# 紅明が変なこと言うから……！
line = "紅明が変なこと言うから……！"

[[dialogue]]
speaker = "紅明"
# 「うしし、そんなこと言いつつ満更でもない感じ？　いや～、やっぱ相性いいんだよね、アタシとダーリン♪」
line = "「うしし、そんなこと言いつつ満更でもない感じ？　いや～、やっぱ相性いいんだよね、アタシとダーリン♪」"

[[dialogue]]
speaker = "紅明"
# 「えいっ、このこの～。ぶっちゃけアタシのことどう思ってんのさ～。教えてよ、ダーリン☆」
line = "「えいっ、このこの～。ぶっちゃけアタシのことどう思ってんのさ～。教えてよ、ダーリン☆」"

[[dialogue]]
speaker = "紅明"
# 「ほれほれ～？　正直に言わないと、おっぱい揉ますぞ～？　というか、せっかくだから一発揉んどき？　うっしっし♪」
line = "「ほれほれ～？　正直に言わないと、おっぱい揉ますぞ～？　というか、せっかくだから一発揉んどき？　うっしっし♪」"

[[dialogue]]
speaker = "unk"
# その後、俺が正直な気持ちを告白するまで、紅明にイジられ続けることになるのだった。
line = "その後、俺が正直な気持ちを告白するまで、紅明にイジられ続けることになるのだった。"
