[[dialogue]]
speaker = "unk"
# 第３話,１００年目の変化,P
line = "第３話,１００年目の変化,P"

[[dialogue]]
speaker = "ソフレ"
# 「スヤスヤ……♪」
line = "「スヤスヤ……♪」"

[[dialogue]]
speaker = "unk"
# 最近、ソフレはよく星徒会室をお昼寝スポットにしている。静かに眠っているだけなので、仕事に支障はなく別にいいのだが――
line = "最近、ソフレはよく星徒会室をお昼寝スポットにしている。静かに眠っているだけなので、仕事に支障はなく別にいいのだが――"

[[dialogue]]
speaker = "ソフレ"
# 「ん……ふわぁ～。よく寝たのだわ」
line = "「ん……ふわぁ～。よく寝たのだわ」"

[[dialogue]]
speaker = "ソフレ"
# 「会長、仕事はどんな感じなのだわ？」
line = "「会長、仕事はどんな感じなのだわ？」"

[[dialogue]]
speaker = "ソフレ"
# 「――もうすぐ終わりそう？　ふ～ん、なら、ＤＩＳＣを弄って待っているのだわ」
line = "「――もうすぐ終わりそう？　ふ～ん、なら、ＤＩＳＣを弄って待っているのだわ」"

[[dialogue]]
speaker = "unk"
# 最近、よく星徒会室で寝てるよね
line = "最近、よく星徒会室で寝てるよね"

[[dialogue]]
speaker = "ソフレ"
# 「ふふ……ここはなかなか良いお昼寝スポットなのだわ♪　日当たりもいいし、エアコンもあるしね」
line = "「ふふ……ここはなかなか良いお昼寝スポットなのだわ♪　日当たりもいいし、エアコンもあるしね」"

[[dialogue]]
speaker = "ソフレ"
# 「あと会長はフェリシーと違って、意外とソフレに甘いのだわ。ソフレがお昼寝してても、怒ったりしないし」
line = "「あと会長はフェリシーと違って、意外とソフレに甘いのだわ。ソフレがお昼寝してても、怒ったりしないし」"

[[dialogue]]
speaker = "unk"
# ぐうたらしてたら怒るかもだけど……
line = "ぐうたらしてたら怒るかもだけど……"

[[dialogue]]
speaker = "ソフレ"
# 「ん？　――授業はちゃんと出てるし、星騎士としても出撃しているから、別に怒ったりしない？」
line = "「ん？　――授業はちゃんと出てるし、星騎士としても出撃しているから、別に怒ったりしない？」"

[[dialogue]]
speaker = "ソフレ"
# 「それは……授業をサボるとフェリシーがうるさいし……」
line = "「それは……授業をサボるとフェリシーがうるさいし……」"

[[dialogue]]
speaker = "ソフレ"
# 「戦うようになったのは……安眠の為よ。会長が出撃しているのに、ソフレだけ留守番して寝ていたら、寝覚めがよくないのだわ」
line = "「戦うようになったのは……安眠の為よ。会長が出撃しているのに、ソフレだけ留守番して寝ていたら、寝覚めがよくないのだわ」"

[[dialogue]]
speaker = "ソフレ"
# 「会長が近くにいると、なんだか不思議と安心して、よく眠れるのよね」
line = "「会長が近くにいると、なんだか不思議と安心して、よく眠れるのよね」"

[[dialogue]]
speaker = "ソフレ"
# 「会長はそういう、癒しオーラを持っているのかもしれないわ。一種の安眠グッズみたいなものね♪」
line = "「会長はそういう、癒しオーラを持っているのかもしれないわ。一種の安眠グッズみたいなものね♪」"

[[dialogue]]
speaker = "ソフレ"
# 「ついでに戦えば、封印の刑期も短くなるしね。一石二鳥なのだわ」
line = "「ついでに戦えば、封印の刑期も短くなるしね。一石二鳥なのだわ」"

[[dialogue]]
speaker = "ソフレ"
# 「――って、ソフレが話している間に、書類仕事が終わったみたいね」
line = "「――って、ソフレが話している間に、書類仕事が終わったみたいね」"

[[dialogue]]
speaker = "ソフレ"
# 「なら、ソフレがこうしてせっかく起きているのだし、放課後の雑談に付き合ってあげるのだわ♪」
line = "「なら、ソフレがこうしてせっかく起きているのだし、放課後の雑談に付き合ってあげるのだわ♪」"

[[dialogue]]
speaker = "ソフレ"
# 「会長も『ネムリスト』の仲間入りをしたわけだしね」
line = "「会長も『ネムリスト』の仲間入りをしたわけだしね」"

[[dialogue]]
speaker = "unk"
# 『ネムリスト』とは、ソフレの造語で、快適な睡眠を目指す者のこと――らしい。
line = "『ネムリスト』とは、ソフレの造語で、快適な睡眠を目指す者のこと――らしい。"

[[dialogue]]
speaker = "unk"
# ソフレとよく話すようになって、安眠グッズに興味を持つうちに、いつの間にか俺も仲間入りを認められていたのだった。
line = "ソフレとよく話すようになって、安眠グッズに興味を持つうちに、いつの間にか俺も仲間入りを認められていたのだった。"

[[dialogue]]
speaker = "ソフレ"
# 「――この前、ソフレがあげた枕は使ってみた？　それで、どうだったのかしら？」
line = "「――この前、ソフレがあげた枕は使ってみた？　それで、どうだったのかしら？」"

[[dialogue]]
speaker = "ソフレ"
# 「ぐっすり寝られるようになった？　ふふっ、そうでしょう♪　ソフレが１番よく使っているのと同じものなのよ」
line = "「ぐっすり寝られるようになった？　ふふっ、そうでしょう♪　ソフレが１番よく使っているのと同じものなのよ」"

[[dialogue]]
speaker = "ソフレ"
# 「また別の安眠グッズも教えてあげるのだわ。といっても、いちいち持ってくるのも面倒だし――」
line = "「また別の安眠グッズも教えてあげるのだわ。といっても、いちいち持ってくるのも面倒だし――」"

[[dialogue]]
speaker = "ソフレ"
# 「今度、ソフレの部屋に招待してあげる。今週末とか予定は空いているのかしら？」
line = "「今度、ソフレの部屋に招待してあげる。今週末とか予定は空いているのかしら？」"

[[dialogue]]
speaker = "ソフレ"
# 「――ふふっ、じゃあ決まりね。休日なら、まったりできるし……」
line = "「――ふふっ、じゃあ決まりね。休日なら、まったりできるし……」"

[[dialogue]]
speaker = "ソフレ"
# 「一緒にお昼寝会をするのも悪くないのだわ♪」
line = "「一緒にお昼寝会をするのも悪くないのだわ♪」"

[[dialogue]]
speaker = "ソフレ"
# 「――ということが昨日あって、会長が部屋に遊びに来ることになったのだわ」
line = "「――ということが昨日あって、会長が部屋に遊びに来ることになったのだわ」"

[[dialogue]]
speaker = "unk"
# ソフレがフェリシーと２人で昼食をしながら、そんなことを話すと……
line = "ソフレがフェリシーと２人で昼食をしながら、そんなことを話すと……"

[[dialogue]]
speaker = "フェリシー"
# 「……あのさ、ソフレ」
line = "「……あのさ、ソフレ」"

[[dialogue]]
speaker = "フェリシー"
# 「最近思ってたんだけど、ソフレって実は……」
line = "「最近思ってたんだけど、ソフレって実は……」"

[[dialogue]]
speaker = "フェリシー"
# 「会長くんのこと、好きだったりする？」
line = "「会長くんのこと、好きだったりする？」"

[[dialogue]]
speaker = "ソフレ"
# 「は……はあぁっ！？　なんでそうなるのだわ！」
line = "「は……はあぁっ！？　なんでそうなるのだわ！」"

[[dialogue]]
speaker = "フェリシー"
# 「だって、聞いている限り、２人ですごいイチャイチャしてるし」
line = "「だって、聞いている限り、２人ですごいイチャイチャしてるし」"

[[dialogue]]
speaker = "ソフレ"
# 「イチャイチャ！？」
line = "「イチャイチャ！？」"

[[dialogue]]
speaker = "フェリシー"
# 「というか、私より会長くんの方がソフレと親密になってる気がするし！」
line = "「というか、私より会長くんの方がソフレと親密になってる気がするし！」"

[[dialogue]]
speaker = "フェリシー"
# 「ずるい！　私だってまだソフレから遊びに誘われたことないのに！」
line = "「ずるい！　私だってまだソフレから遊びに誘われたことないのに！」"

[[dialogue]]
speaker = "ソフレ"
# 「い、いや、ソフレは別にそんな……」
line = "「い、いや、ソフレは別にそんな……」"

[[dialogue]]
speaker = "フェリシー"
# 「でも、ソフレが会長くんのことを話す時って、睡眠について語っている時みたいに楽しそうだよ？」
line = "「でも、ソフレが会長くんのことを話す時って、睡眠について語っている時みたいに楽しそうだよ？」"

[[dialogue]]
speaker = "ソフレ"
# 「えっ……！？」
line = "「えっ……！？」"

[[dialogue]]
speaker = "ソフレ"
# （そ、ソフレが会長を好きとか、あり得ないのだわ……！）
line = "（そ、ソフレが会長を好きとか、あり得ないのだわ……！）"

[[dialogue]]
speaker = "ソフレ"
# （だって、生まれてこの方、恋愛のことなんか興味を持ってこなかったのに……今更そんな……！）
line = "（だって、生まれてこの方、恋愛のことなんか興味を持ってこなかったのに……今更そんな……！）"

[[dialogue]]
speaker = "フェリシー"
# 「……で、実際のところは、どうなの？」
line = "「……で、実際のところは、どうなの？」"

[[dialogue]]
speaker = "ソフレ"
# 「そ、そんなわけないのだわ！　絶対に違うのよ！」
line = "「そ、そんなわけないのだわ！　絶対に違うのよ！」"

[[dialogue]]
speaker = "ソフレ"
# 「ソフレは恋愛よりも、睡眠の方が好きなのだわ～～～っ！」
line = "「ソフレは恋愛よりも、睡眠の方が好きなのだわ～～～っ！」"

[[dialogue]]
speaker = "フェリシー"
# 「って、ソフレったら逃げちゃった。でも、そっかぁ――」
line = "「って、ソフレったら逃げちゃった。でも、そっかぁ――」"

[[dialogue]]
speaker = "フェリシー"
# 「伝説の吸血鬼にも、ついに恋がやってきたか～。ふふっ♪」
line = "「伝説の吸血鬼にも、ついに恋がやってきたか～。ふふっ♪」"

[[dialogue]]
speaker = "unk"
# １００年目にして迎えた友達の変化を、嬉しく思うフェリシーなのだった。
line = "１００年目にして迎えた友達の変化を、嬉しく思うフェリシーなのだった。"
