[[dialogue]]
speaker = "unk"
# 第３話,どっちが好き？（後編）,P
line = "第３話,どっちが好き？（後編）,P"

[[dialogue]]
speaker = "unk"
# 俺は、分裂した大きな方のアルモによって、校舎隅の人気のない空き教室へ連れてこられていた――
line = "俺は、分裂した大きな方のアルモによって、校舎隅の人気のない空き教室へ連れてこられていた――"

[[dialogue]]
speaker = "アルモタヘル"
# 「よし、小さい我を撒いたようだな。これでしばらくは２人きりだ」
line = "「よし、小さい我を撒いたようだな。これでしばらくは２人きりだ」"

[[dialogue]]
speaker = "アルモタヘル"
# 「――ここで何をするのかだと？　決まっているであろう。あれだけ小さい我に煽られたのだ。然れば――」
line = "「――ここで何をするのかだと？　決まっているであろう。あれだけ小さい我に煽られたのだ。然れば――」"

[[dialogue]]
speaker = "アルモタヘル"
# 「我の方がファーストキスの相手なのだと、お前に思い出してもらわなけば、気が済まぬというもの……」
line = "「我の方がファーストキスの相手なのだと、お前に思い出してもらわなけば、気が済まぬというもの……」"

[[dialogue]]
speaker = "アルモタヘル"
# 「んっ……<emoji=heart04>　ちゅっ……<emoji=heart04>」
line = "「んっ……<emoji=heart04>　ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アルモタヘル"
# 「はぁ……<emoji=heart04>　我にも、小さい体でキスした記憶はあるが、それでも何だか久しぶりの感じがするな」
line = "「はぁ……<emoji=heart04>　我にも、小さい体でキスした記憶はあるが、それでも何だか久しぶりの感じがするな」"

[[dialogue]]
speaker = "アルモタヘル"
# 「胸がドキドキして、体が燃えるように熱くなってしまう……ふふっ<emoji=heart04>　守護天使なのに、今ではすっかり１人の女だ」
line = "「胸がドキドキして、体が燃えるように熱くなってしまう……ふふっ<emoji=heart04>　守護天使なのに、今ではすっかり１人の女だ」"

[[dialogue]]
speaker = "アルモタヘル"
# 「人の子よ……お前はどうであろうか？　こっちの我でも、ドキドキしてくれているか……？」
line = "「人の子よ……お前はどうであろうか？　こっちの我でも、ドキドキしてくれているか……？」"

[[dialogue]]
speaker = "unk"
# ちょっと不安そうな顔をするアルモ。そんな彼女が愛おしくて――
line = "ちょっと不安そうな顔をするアルモ。そんな彼女が愛おしくて――"

[[dialogue]]
speaker = "アルモタヘル"
# 「あっ……<emoji=heart04>　んっ……ちゅっ<emoji=heart04>　はあぁ……<emoji=heart04>　そんなに優しく頭を撫でられたら、小さい体の我みたいに甘えたくなってしまうではないか……<emoji=heart04>」
line = "「あっ……<emoji=heart04>　んっ……ちゅっ<emoji=heart04>　はあぁ……<emoji=heart04>　そんなに優しく頭を撫でられたら、小さい体の我みたいに甘えたくなってしまうではないか……<emoji=heart04>」"

[[dialogue]]
speaker = "アルモタヘル"
# 「――恋人だから、甘えてもいいと？　じゃあ……もっといっぱい、キスのおかわりを所望するぞ……<emoji=heart04>」
line = "「――恋人だから、甘えてもいいと？　じゃあ……もっといっぱい、キスのおかわりを所望するぞ……<emoji=heart04>」"

[[dialogue]]
speaker = "アルモタヘル"
# 「んっ……ちゅっ……<emoji=heart04>　好きだ、人の子よ……<emoji=heart04>　ちゅっ……<emoji=heart04>」
line = "「んっ……ちゅっ……<emoji=heart04>　好きだ、人の子よ……<emoji=heart04>　ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アルモたん"
# 「そこまでなのだーーーっ！！！」
line = "「そこまでなのだーーーっ！！！」"

[[dialogue]]
speaker = "unk"
# うわっ！？　アルモ、ごめん！
line = "うわっ！？　アルモ、ごめん！"

[[dialogue]]
speaker = "アルモタヘル"
# 「むぅ……存外早かったな……」
line = "「むぅ……存外早かったな……」"

[[dialogue]]
speaker = "アルモたん"
# 「自分の考えることだから、逃げる場所くらい想像つくに決まってるのだ！」
line = "「自分の考えることだから、逃げる場所くらい想像つくに決まってるのだ！」"

[[dialogue]]
speaker = "アルモたん"
# 「強引に２人きりになってキスをするなんて、ずるいのだ！　しかも、なんかものすごくいい雰囲気だったのだ！」
line = "「強引に２人きりになってキスをするなんて、ずるいのだ！　しかも、なんかものすごくいい雰囲気だったのだ！」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ふふっ、そうだな。久しぶりだったから、つい燃え上がってしまったようだ<emoji=heart04>」
line = "「ふふっ、そうだな。久しぶりだったから、つい燃え上がってしまったようだ<emoji=heart04>」"

[[dialogue]]
speaker = "アルモたん"
# 「ぐぬぬ……！　どんな感じだったか、ものすごく気になるのだ……！」
line = "「ぐぬぬ……！　どんな感じだったか、ものすごく気になるのだ……！」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ふふふ、残念だったな。分裂している間は、記憶は別々だからな。薬の効果が切れて共有されるまでは、おあずけだ」
line = "「ふふふ、残念だったな。分裂している間は、記憶は別々だからな。薬の効果が切れて共有されるまでは、おあずけだ」"

[[dialogue]]
speaker = "アルモたん"
# 「む～っ！　こうなったら……アルモたんだってしちゃうのだ！」
line = "「む～っ！　こうなったら……アルモたんだってしちゃうのだ！」"

[[dialogue]]
speaker = "アルモたん"
# 「ん～っ<emoji=heart04>　ちゅっ<emoji=heart04>」
line = "「ん～っ<emoji=heart04>　ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "アルモタヘル"
# 「あっ！　こらっ、無理矢理割って入ってくるとは……！」
line = "「あっ！　こらっ、無理矢理割って入ってくるとは……！」"

[[dialogue]]
speaker = "アルモたん"
# 「お肉を分け合わないなんて、大人はケチなのだ！　同じくらいアルモたんだってキスしないと、不公平なのだ！」
line = "「お肉を分け合わないなんて、大人はケチなのだ！　同じくらいアルモたんだってキスしないと、不公平なのだ！」"

[[dialogue]]
speaker = "アルモタヘル"
# 「今更それを言うか！？　騙されぬぞ！　ええい、人の子から、は～な～れ～ろ～！」
line = "「今更それを言うか！？　騙されぬぞ！　ええい、人の子から、は～な～れ～ろ～！」"

[[dialogue]]
speaker = "アルモたん"
# 「い～や～な～の～だ～！」
line = "「い～や～な～の～だ～！」"

[[dialogue]]
speaker = "unk"
# ふ、２人共、落ち着いて！
line = "ふ、２人共、落ち着いて！"

[[dialogue]]
speaker = "アルモタヘル"
# 「ええい！　こうなったら……人の子よ！」
line = "「ええい！　こうなったら……人の子よ！」"

[[dialogue]]
speaker = "アルモたん"
# 「手段は１つしかないのだ！　会長！」
line = "「手段は１つしかないのだ！　会長！」"

[[dialogue]]
speaker = "アルモ×２"
# 「どっちの我が好きなのだ！？」
line = "「どっちの我が好きなのだ！？」"

[[dialogue]]
speaker = "unk"
# こういう時だけユニゾン！？
line = "こういう時だけユニゾン！？"

[[dialogue]]
speaker = "アルモタヘル"
# 「当然、先に好きだと告白してくれたのは我の方なのだから、色々と大きい方が好きであろう？」
line = "「当然、先に好きだと告白してくれたのは我の方なのだから、色々と大きい方が好きであろう？」"

[[dialogue]]
speaker = "アルモたん"
# 「それは仕方なくなのだ。今の会長は、可愛さがパワーアップした小さいアルモたんにメロメロなのだ！」
line = "「それは仕方なくなのだ。今の会長は、可愛さがパワーアップした小さいアルモたんにメロメロなのだ！」"

[[dialogue]]
speaker = "unk"
# 俺は、どっちのアルモも本気で好きだ！
line = "俺は、どっちのアルモも本気で好きだ！"

[[dialogue]]
speaker = "unk"
# 目の前にいるのは、どちらも本物なのだ。だったら、俺は男として、アルモの両面をまとめて愛してみせる――覚悟を決めて、２人にそう告げた。
line = "目の前にいるのは、どちらも本物なのだ。だったら、俺は男として、アルモの両面をまとめて愛してみせる――覚悟を決めて、２人にそう告げた。"

[[dialogue]]
speaker = "アルモタヘル"
# 「……！　つ、つい勢いで言ってしまったので、そこまで深く考えていなかったが……」
line = "「……！　つ、つい勢いで言ってしまったので、そこまで深く考えていなかったが……」"

[[dialogue]]
speaker = "アルモたん"
# 「そんな真面目な顔で言われたら、どっちか選べなんて、これ以上言えなくなっちゃうのだ……」
line = "「そんな真面目な顔で言われたら、どっちか選べなんて、これ以上言えなくなっちゃうのだ……」"

[[dialogue]]
speaker = "アルモタヘル"
# 「……というか、最初はもう１人の我に嫉妬するはずがないと思っていたのだが、気づけば感情を抑えられなくなってしまっていたな」
line = "「……というか、最初はもう１人の我に嫉妬するはずがないと思っていたのだが、気づけば感情を抑えられなくなってしまっていたな」"

[[dialogue]]
speaker = "アルモタヘル"
# 「もしかしたら、『もう１人の自分に嫉妬してしまう』というのが、分裂薬の副作用だったのかもしれぬ」
line = "「もしかしたら、『もう１人の自分に嫉妬してしまう』というのが、分裂薬の副作用だったのかもしれぬ」"

[[dialogue]]
speaker = "アルモたん"
# 「そもそも分裂薬を飲んだのは、会長に喜んでもらうことが目的だったのだ。なのに、むしろ困らせてしまったのだ……」
line = "「そもそも分裂薬を飲んだのは、会長に喜んでもらうことが目的だったのだ。なのに、むしろ困らせてしまったのだ……」"

[[dialogue]]
speaker = "アルモタヘル"
# 「そうだな。ならば、その反省とお詫びを兼ねて、ちゃんとせねばなるまい」
line = "「そうだな。ならば、その反省とお詫びを兼ねて、ちゃんとせねばなるまい」"

[[dialogue]]
speaker = "アルモたん"
# 「嫉妬はしても、気持ちは１つなのだ！」
line = "「嫉妬はしても、気持ちは１つなのだ！」"

[[dialogue]]
speaker = "アルモタヘル"
# 「うむ。ということで、人の子よ。待たせたな。ここからはお待ちかねのハーレムだぞ<emoji=heart04>」
line = "「うむ。ということで、人の子よ。待たせたな。ここからはお待ちかねのハーレムだぞ<emoji=heart04>」"

[[dialogue]]
speaker = "アルモたん"
# 「いっぱい喜ばせちゃうのだ<emoji=heart04>　ん～っ……ちゅっ……<emoji=heart04>」
line = "「いっぱい喜ばせちゃうのだ<emoji=heart04>　ん～っ……ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ちゅっ……ちゅっ……<emoji=heart04>　――ん？　どうした、人の子よ？」
line = "「ちゅっ……ちゅっ……<emoji=heart04>　――ん？　どうした、人の子よ？」"

[[dialogue]]
speaker = "unk"
# ふ、２人同時は刺激は強過ぎる……！
line = "ふ、２人同時は刺激は強過ぎる……！"

[[dialogue]]
speaker = "アルモタヘル"
# 「んっ……<emoji=heart04>　ふふっ、嫉妬心よりも、なんだか人の子の反応の方が面白くなってきてしまったぞ<emoji=heart04>」
line = "「んっ……<emoji=heart04>　ふふっ、嫉妬心よりも、なんだか人の子の反応の方が面白くなってきてしまったぞ<emoji=heart04>」"

[[dialogue]]
speaker = "アルモたん"
# 「２人でいっぱい好き好き攻撃して、会長をもっと可愛い顔にしちゃうのだ<emoji=heart04>」
line = "「２人でいっぱい好き好き攻撃して、会長をもっと可愛い顔にしちゃうのだ<emoji=heart04>」"

[[dialogue]]
speaker = "アルモたん"
# 「ちゅっ……<emoji=heart04>」
line = "「ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その後、俺は２人に挟まれた熱で、甘々に理性を溶かされてしまうのだった――
line = "その後、俺は２人に挟まれた熱で、甘々に理性を溶かされてしまうのだった――"
