[[dialogue]]
speaker = "unk"
# 第４話,姉妹とクロト,P
line = "第４話,姉妹とクロト,P"

[[dialogue]]
speaker = "ソフィア"
# 「……会長さんもなかなか諦めが悪いですね。これだけ空振り続きなのに私のパトロールに付き合ってくれるなんて」
line = "「……会長さんもなかなか諦めが悪いですね。これだけ空振り続きなのに私のパトロールに付き合ってくれるなんて」"

[[dialogue]]
speaker = "ソフィア"
# 「まぁ、何も起きないなら起きないでいいことなのですが……」
line = "「まぁ、何も起きないなら起きないでいいことなのですが……」"

[[dialogue]]
speaker = "ソフィア"
# 「モンスター！　言ったそばから出てくるなんて、まるで聞こえていたみたいです」
line = "「モンスター！　言ったそばから出てくるなんて、まるで聞こえていたみたいです」"

[[dialogue]]
speaker = "ソフィア"
# 「！　アステラの反応があったと連絡が来ました。近いです」
line = "「！　アステラの反応があったと連絡が来ました。近いです」"

[[dialogue]]
speaker = "ソフィア"
# 「近くにいる星騎士が応援に来ます。合流してからアステラに突入しましょう」
line = "「近くにいる星騎士が応援に来ます。合流してからアステラに突入しましょう」"

[[dialogue]]
speaker = "ソフィア"
# 「──ふっ！」
line = "「──ふっ！」"

[[dialogue]]
speaker = "unk"
# 綺麗な戦い方だ
line = "綺麗な戦い方だ"

[[dialogue]]
speaker = "ソフィア"
# 「スケートの動きを取り入れてますので。このぐらいこなせなくてはフィギュアスケート部の名折れです」
line = "「スケートの動きを取り入れてますので。このぐらいこなせなくてはフィギュアスケート部の名折れです」"

[[dialogue]]
speaker = "サーシャ"
# 「お待たせ～。あら、先行していた２人ってソフィと会長くんだったのね～」
line = "「お待たせ～。あら、先行していた２人ってソフィと会長くんだったのね～」"

[[dialogue]]
speaker = "ソフィア"
# 「姉さん！？」
line = "「姉さん！？」"

[[dialogue]]
speaker = "サーシャ"
# 「はぁい、お姉ちゃんです～♪」
line = "「はぁい、お姉ちゃんです～♪」"

[[dialogue]]
speaker = "ソフィア"
# 「……まぁ、心強いことには変わりないです。アステラ内へ突入しましょう」
line = "「……まぁ、心強いことには変わりないです。アステラ内へ突入しましょう」"

[[dialogue]]
speaker = "ソフィア"
# 「やぁっ！」
line = "「やぁっ！」"

[[dialogue]]
speaker = "サーシャ"
# 「スケート、ずいぶん上手になったわね」
line = "「スケート、ずいぶん上手になったわね」"

[[dialogue]]
speaker = "ソフィア"
# 「姉さんが新星学園に行ってからも練習してましたから。──！」
line = "「姉さんが新星学園に行ってからも練習してましたから。──！」"

[[dialogue]]
speaker = "ソフィア"
# 「後ろからモンスター来てましたよ」
line = "「後ろからモンスター来てましたよ」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふっ、ありがとう～。さすがソフィね～」
line = "「ふふっ、ありがとう～。さすがソフィね～」"

[[dialogue]]
speaker = "ソフィア"
# 「……本当にそう思ってます？　まぁいいですけど」
line = "「……本当にそう思ってます？　まぁいいですけど」"

[[dialogue]]
speaker = "ソフィア"
# 「攻撃対象を補足。あのモンスターを倒せばアステラが消滅すると推測します」
line = "「攻撃対象を補足。あのモンスターを倒せばアステラが消滅すると推測します」"

[[dialogue]]
speaker = "サーシャ"
# 「確かにちょっと強そうね。それじゃ同時に攻撃しましょうか。私とソフィ、会長くんならやれるわ」
line = "「確かにちょっと強そうね。それじゃ同時に攻撃しましょうか。私とソフィ、会長くんならやれるわ」"

[[dialogue]]
speaker = "ソフィア"
# 「いきますよ。――コキュートススピナー！」
line = "「いきますよ。――コキュートススピナー！」"

[[dialogue]]
speaker = "ソフィア"
# 「アステラの消滅を確認。学園に連絡してきます」
line = "「アステラの消滅を確認。学園に連絡してきます」"

[[dialogue]]
speaker = "サーシャ"
# 「お疲れ様～、会長くん」
line = "「お疲れ様～、会長くん」"

[[dialogue]]
speaker = "unk"
# ソフィアは頼りになる
line = "ソフィアは頼りになる"

[[dialogue]]
speaker = "サーシャ"
# 「そうね、昔と違うからちょっと驚いちゃった。……でも昔と変わらないところもあるわ」
line = "「そうね、昔と違うからちょっと驚いちゃった。……でも昔と変わらないところもあるわ」"

[[dialogue]]
speaker = "サーシャ"
# 「人間界でソフィと再会した時、少しビックリしたの。だって私が作った外套をまだ着てくれてるもの」
line = "「人間界でソフィと再会した時、少しビックリしたの。だって私が作った外套をまだ着てくれてるもの」"

[[dialogue]]
speaker = "サーシャ"
# 「それにスケートもね。ソフィが小さかった頃、一緒にスケートに行ったんだけど、ソフィったら少し教えただけですぐに私より上手になってね」
line = "「それにスケートもね。ソフィが小さかった頃、一緒にスケートに行ったんだけど、ソフィったら少し教えただけですぐに私より上手になってね」"

[[dialogue]]
speaker = "サーシャ"
# 「それから本格的にスケートを習い始めて、三界一のスケート選手になるんだってすごく頑張ってたのよ」
line = "「それから本格的にスケートを習い始めて、三界一のスケート選手になるんだってすごく頑張ってたのよ」"

[[dialogue]]
speaker = "ソフィア"
# 「報告終わりました。……何の話をしてたんですか？」
line = "「報告終わりました。……何の話をしてたんですか？」"

[[dialogue]]
speaker = "サーシャ"
# 「会長くんは頑張ってるね～、って話」
line = "「会長くんは頑張ってるね～、って話」"

[[dialogue]]
speaker = "ソフィア"
# 「むー……」
line = "「むー……」"

[[dialogue]]
speaker = "サーシャ"
# 「ウソウソ。本当はソフィの話をしてたの。すごく成長したなって」
line = "「ウソウソ。本当はソフィの話をしてたの。すごく成長したなって」"

[[dialogue]]
speaker = "ソフィア"
# 「当然です。世界を守るために、フィオナ会長に近づくためにも、モンスターとの戦いで後れを取るわけにはいきません。もう子どもじゃないんです」
line = "「当然です。世界を守るために、フィオナ会長に近づくためにも、モンスターとの戦いで後れを取るわけにはいきません。もう子どもじゃないんです」"

[[dialogue]]
speaker = "サーシャ"
# 「それはどうかしら～？　大人は大変よ～？」
line = "「それはどうかしら～？　大人は大変よ～？」"

[[dialogue]]
speaker = "ソフィア"
# 「うー……」
line = "「うー……」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふふっ」
line = "「ふふふっ」"

[[dialogue]]
speaker = "ソフィア"
# 「うかうかしてると、あっという間に姉さんより強くなっちゃいますからね」
line = "「うかうかしてると、あっという間に姉さんより強くなっちゃいますからね」"

[[dialogue]]
speaker = "サーシャ"
# 「それは楽しみね～。ねぇねぇ、頑張ったご褒美にぎゅ～ってしていい？」
line = "「それは楽しみね～。ねぇねぇ、頑張ったご褒美にぎゅ～ってしていい？」"

[[dialogue]]
speaker = "ソフィア"
# 「ダメです。そんなご褒美いりません」
line = "「ダメです。そんなご褒美いりません」"

[[dialogue]]
speaker = "サーシャ"
# 「ソフィじゃなくて、お姉ちゃんへのご褒美～♪　ホントにダメ？」
line = "「ソフィじゃなくて、お姉ちゃんへのご褒美～♪　ホントにダメ？」"

[[dialogue]]
speaker = "ソフィア"
# 「……姉さんがしたいのならさせてあげます。私は大人ですから。今日だけ特別ですよ」
line = "「……姉さんがしたいのならさせてあげます。私は大人ですから。今日だけ特別ですよ」"

[[dialogue]]
speaker = "サーシャ"
# 「ぎゅ～っ♪」
line = "「ぎゅ～っ♪」"

[[dialogue]]
speaker = "ソフィア"
# 「むぅ……」
line = "「むぅ……」"

[[dialogue]]
speaker = "サーシャ"
# 「ついでにナデナデ♪」
line = "「ついでにナデナデ♪」"

[[dialogue]]
speaker = "ソフィア"
# 「そこまでしていいとは言ってません。むー」
line = "「そこまでしていいとは言ってません。むー」"

[[dialogue]]
speaker = "unk"
# （仲良し姉妹だ）
line = "（仲良し姉妹だ）"

[[dialogue]]
speaker = "ソフィア"
# 「何笑ってるんですか。変な笑い方しないでください」
line = "「何笑ってるんですか。変な笑い方しないでください」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら、仲良くしなくちゃダメよ～？」
line = "「あらあら、仲良くしなくちゃダメよ～？」"

[[dialogue]]
speaker = "ソフィア"
# 「見ないでくださいってば、もうっ」
line = "「見ないでくださいってば、もうっ」"
