[[dialogue]]
speaker = "unk"
# 第３話,アイリーンの力,P
line = "第３話,アイリーンの力,P"

[[dialogue]]
speaker = "アイリーン"
# 「ねぇねぇ、いいでしょ？　会長さん、お願いっ」
line = "「ねぇねぇ、いいでしょ？　会長さん、お願いっ」"

[[dialogue]]
speaker = "マトイ"
# 「ん？　何悩んでるの？　お高いケーキでもねだられた？」
line = "「ん？　何悩んでるの？　お高いケーキでもねだられた？」"

[[dialogue]]
speaker = "アイリーン"
# 「カップル限定のお店に行ってみたいの！　カップルって男の人と女の人のことでしょ？　だから会長さんにお願いっ」
line = "「カップル限定のお店に行ってみたいの！　カップルって男の人と女の人のことでしょ？　だから会長さんにお願いっ」"

[[dialogue]]
speaker = "マトイ"
# 「あ～……なるほど。まぁいいんじゃない、妹みたいなものだと思えば」
line = "「あ～……なるほど。まぁいいんじゃない、妹みたいなものだと思えば」"

[[dialogue]]
speaker = "アイリーン"
# 「むっ、私はれっきとしたレディだよ？　魔女は長生きなんだから」
line = "「むっ、私はれっきとしたレディだよ？　魔女は長生きなんだから」"

[[dialogue]]
speaker = "マトイ"
# 「えっ、もしかして私たちよりずっと年上！？」
line = "「えっ、もしかして私たちよりずっと年上！？」"

[[dialogue]]
speaker = "アイリーン"
# 「ううん、私はまだ成長止まってないし、お姉さんたちより年下だよ」
line = "「ううん、私はまだ成長止まってないし、お姉さんたちより年下だよ」"

[[dialogue]]
speaker = "マトイ"
# 「なんだ、結局年下なんじゃない……」
line = "「なんだ、結局年下なんじゃない……」"

[[dialogue]]
speaker = "アイリーン"
# 「私ね、行きたいところたくさんあるんだ～。カラオケに、映画館に、遊園地に～……あっ、動物園も行ってみたいな」
line = "「私ね、行きたいところたくさんあるんだ～。カラオケに、映画館に、遊園地に～……あっ、動物園も行ってみたいな」"

[[dialogue]]
speaker = "アイリーン"
# 「ネビュラの人はこっちの世界のこと調べてるのに、全然教えてくれなくてね」
line = "「ネビュラの人はこっちの世界のこと調べてるのに、全然教えてくれなくてね」"

[[dialogue]]
speaker = "アイリーン"
# 「こっちの世界に来たくて、頑張ってセドナさんを説得してネビュラに入ったんだから」
line = "「こっちの世界に来たくて、頑張ってセドナさんを説得してネビュラに入ったんだから」"

[[dialogue]]
speaker = "アイリーン"
# 「だからお願い！　カップル限定のお店に連れてって！」
line = "「だからお願い！　カップル限定のお店に連れてって！」"

[[dialogue]]
speaker = "unk"
# じゃあこれから行く？
line = "じゃあこれから行く？"

[[dialogue]]
speaker = "アイリーン"
# 「やった、ありがと～！　会長さん好き！」
line = "「やった、ありがと～！　会長さん好き！」"

[[dialogue]]
speaker = "マトイ"
# 「もう、そんな軽く好きって言っちゃダメなんだから」
line = "「もう、そんな軽く好きって言っちゃダメなんだから」"

[[dialogue]]
speaker = "アイリーン"
# 「なんで～？　気持ちはちゃんと言った方がいいってお母さん言ってたよ？」
line = "「なんで～？　気持ちはちゃんと言った方がいいってお母さん言ってたよ？」"

[[dialogue]]
speaker = "マトイ"
# 「うーん……やっぱり無邪気妹キャラでは……？」
line = "「うーん……やっぱり無邪気妹キャラでは……？」"

[[dialogue]]
speaker = "アイリーン"
# 「えへへ～っ♪　早くお店行こ、会長さん！」
line = "「えへへ～っ♪　早くお店行こ、会長さん！」"

[[dialogue]]
speaker = "アイリーン"
# 「！　も～、邪魔しないでよね」
line = "「！　も～、邪魔しないでよね」"

[[dialogue]]
speaker = "アイリーン"
# 「ミーちゃん、偵察よろしく！」
line = "「ミーちゃん、偵察よろしく！」"

[[dialogue]]
speaker = "ミネルバ"
# 「ホーホー！」
line = "「ホーホー！」"

[[dialogue]]
speaker = "アイリーン"
# 「モンスターの配置は……ふむふむ……そういう感じかー」
line = "「モンスターの配置は……ふむふむ……そういう感じかー」"

[[dialogue]]
speaker = "unk"
# 何してるんだ？
line = "何してるんだ？"

[[dialogue]]
speaker = "アイリーン"
# 「私とミーちゃんは感覚を共有できるの。ミーちゃんに周りを飛んでもらって、モンスターの数と位置を把握してるんだ」
line = "「私とミーちゃんは感覚を共有できるの。ミーちゃんに周りを飛んでもらって、モンスターの数と位置を把握してるんだ」"

[[dialogue]]
speaker = "アイリーン"
# 「オッケー、作戦できた！　会長さんはモンスターにちょっかいかけて、注意を引いたら大通りまで戻ってきて」
line = "「オッケー、作戦できた！　会長さんはモンスターにちょっかいかけて、注意を引いたら大通りまで戻ってきて」"

[[dialogue]]
speaker = "少女"
# 「きゃあああっ！？」
line = "「きゃあああっ！？」"

[[dialogue]]
speaker = "アイリーン"
# 「ミーちゃん！」
line = "「ミーちゃん！」"

[[dialogue]]
speaker = "少女"
# 「あれ、私飛んでる……？　えっ、フクロウ！？　フクロウに助けられた！？」
line = "「あれ、私飛んでる……？　えっ、フクロウ！？　フクロウに助けられた！？」"

[[dialogue]]
speaker = "アイリーン"
# 「ミーちゃんに感謝してね、そこのお姉さんっ」
line = "「ミーちゃんに感謝してね、そこのお姉さんっ」"

[[dialogue]]
speaker = "少女"
# 「あっ、はいっ、ありがとうございますっ。……あの子、星騎士なの……？」
line = "「あっ、はいっ、ありがとうございますっ。……あの子、星騎士なの……？」"

[[dialogue]]
speaker = "アイリーン"
# 「うんうん、会長さんのおかげでいい感じに集まってきたかな。それじゃ私とミーちゃんで挟み撃ち！」
line = "「うんうん、会長さんのおかげでいい感じに集まってきたかな。それじゃ私とミーちゃんで挟み撃ち！」"

[[dialogue]]
speaker = "ミネルバ"
# 「ホホー！」
line = "「ホホー！」"

[[dialogue]]
speaker = "アイリーン"
# 「お母さん直伝！　――スマートボルテックス！」
line = "「お母さん直伝！　――スマートボルテックス！」"

[[dialogue]]
speaker = "アイリーン"
# 「はい、一網打尽。あんまり戦うなって言われてるから、会長さんがやったってことにしといてね」
line = "「はい、一網打尽。あんまり戦うなって言われてるから、会長さんがやったってことにしといてね」"

[[dialogue]]
speaker = "アイリーン"
# 「お疲れさま、ミーちゃん。会長さんもありがと」
line = "「お疲れさま、ミーちゃん。会長さんもありがと」"

[[dialogue]]
speaker = "unk"
# お母さんは今どうしてるんだ？
line = "お母さんは今どうしてるんだ？"

[[dialogue]]
speaker = "アイリーン"
# 「死んじゃった」
line = "「死んじゃった」"

[[dialogue]]
speaker = "unk"
# ──！
line = "──！"

[[dialogue]]
speaker = "アイリーン"
# 「流星市国から離れた場所でモンスターが現れてね、星騎士が間に合わなかったから、たまたま居合わせたお母さんが戦ったの」
line = "「流星市国から離れた場所でモンスターが現れてね、星騎士が間に合わなかったから、たまたま居合わせたお母さんが戦ったの」"

[[dialogue]]
speaker = "アイリーン"
# 「ミーちゃんのお母さんもその時にやられちゃった」
line = "「ミーちゃんのお母さんもその時にやられちゃった」"

[[dialogue]]
speaker = "アイリーン"
# 「？　なんで会長さんが悲しそうな顔してるの？　聞かれたから答えただけだよ」
line = "「？　なんで会長さんが悲しそうな顔してるの？　聞かれたから答えただけだよ」"

[[dialogue]]
speaker = "アイリーン"
# 「さ、早くお店いこっ。カップル限定パフェ食べるんだ～。ちゃんとあーんして食べさせてくれないとダメなんだからね、会長さんっ」
line = "「さ、早くお店いこっ。カップル限定パフェ食べるんだ～。ちゃんとあーんして食べさせてくれないとダメなんだからね、会長さんっ」"

[[dialogue]]
speaker = "unk"
# あーん！？
line = "あーん！？"

[[dialogue]]
speaker = "アイリーン"
# 「あれ、なんで驚いてるの？　言ってなかったけ？　でも私もあーんしてあげるビョードーだねっ♪」
line = "「あれ、なんで驚いてるの？　言ってなかったけ？　でも私もあーんしてあげるビョードーだねっ♪」"
