[[dialogue]]
speaker = "unk"
# 第４話,魔王と光の魔女,P
line = "第４話,魔王と光の魔女,P"

[[dialogue]]
speaker = "unk"
# ある冬の日──
line = "ある冬の日──"

[[dialogue]]
speaker = "クラウディア"
# 「うー寒い寒い……しかし、この環境にもなんとか慣れてきたぞ」
line = "「うー寒い寒い……しかし、この環境にもなんとか慣れてきたぞ」"

[[dialogue]]
speaker = "クラウディア"
# 「魔王のくれたカイロもぽっかぽかだ！　うぅ、余はもうこれが手放せん体になってしまった……」
line = "「魔王のくれたカイロもぽっかぽかだ！　うぅ、余はもうこれが手放せん体になってしまった……」"

[[dialogue]]
speaker = "ウェンディ"
# 「──ああっ、困りました困りました！　急がないと……！」
line = "「──ああっ、困りました困りました！　急がないと……！」"

[[dialogue]]
speaker = "クラウディア"
# 「む……ウェンディ？　どうしたのだ」
line = "「む……ウェンディ？　どうしたのだ」"

[[dialogue]]
speaker = "ウェンディ"
# 「──あ、クラウディア様！　実は完成したばかりの資料が、輸送中、モンスターに襲われちゃったらしくって」
line = "「──あ、クラウディア様！　実は完成したばかりの資料が、輸送中、モンスターに襲われちゃったらしくって」"

[[dialogue]]
speaker = "ウェンディ"
# 「急いでこの新しい資料を学園に届けなくちゃならないんです！　では、失礼します～！」
line = "「急いでこの新しい資料を学園に届けなくちゃならないんです！　では、失礼します～！」"

[[dialogue]]
speaker = "クラウディア"
# 「とらぶるか。それにしても、まったくウェンディときたらいつも慌てておるのう」
line = "「とらぶるか。それにしても、まったくウェンディときたらいつも慌てておるのう」"

[[dialogue]]
speaker = "クラウディア"
# 「少しは余を見習って堂々と落ち着いておればよいのだ！　なあ？」
line = "「少しは余を見習って堂々と落ち着いておればよいのだ！　なあ？」"

[[dialogue]]
speaker = "unk"
# ネビュラが立ち行かない
line = "ネビュラが立ち行かない"

[[dialogue]]
speaker = "unk"
# みんながその調子だと
line = "みんながその調子だと"

[[dialogue]]
speaker = "クラウディア"
# 「はっはっは、それを言うでない。ドンと構えていればなんとかなるというものだ」
line = "「はっはっは、それを言うでない。ドンと構えていればなんとかなるというものだ」"

[[dialogue]]
speaker = "クラウディア"
# 「しかし、魔女がこうも堂々と外界を出歩く日がくるとは……ふふ、すっかり馴染んでおるな」
line = "「しかし、魔女がこうも堂々と外界を出歩く日がくるとは……ふふ、すっかり馴染んでおるな」"

[[dialogue]]
speaker = "unk"
# クラウディアのおかげ
line = "クラウディアのおかげ"

[[dialogue]]
speaker = "unk"
# 今までじゃ考えられなかった
line = "今までじゃ考えられなかった"

[[dialogue]]
speaker = "クラウディア"
# 「ん？　ああ、知っていたのか」
line = "「ん？　ああ、知っていたのか」"

[[dialogue]]
speaker = "クラウディア"
# 「そうだ。ネビュラに開国を──と求めたのはもとより余でな」
line = "「そうだ。ネビュラに開国を──と求めたのはもとより余でな」"

[[dialogue]]
speaker = "クラウディア"
# 「これでせっかく好きに出歩けると思っていたのに、その当人がまだ監視されるはめになるというのは計算外だったが……」
line = "「これでせっかく好きに出歩けると思っていたのに、その当人がまだ監視されるはめになるというのは計算外だったが……」"

[[dialogue]]
speaker = "クラウディア"
# 「ともかくネビュラは今、新しい道を切り拓こうとしておる」
line = "「ともかくネビュラは今、新しい道を切り拓こうとしておる」"

[[dialogue]]
speaker = "クラウディア"
# 「余もそうだ。余の役目はずっと……グレートウォール計画を成功させるためのものであった」
line = "「余もそうだ。余の役目はずっと……グレートウォール計画を成功させるためのものであった」"

[[dialogue]]
speaker = "クラウディア"
# 「だが、今はもうその役目はなくなってしまった。そして、役目の無くなった世界はこれから先も続いていく」
line = "「だが、今はもうその役目はなくなってしまった。そして、役目の無くなった世界はこれから先も続いていく」"

[[dialogue]]
speaker = "クラウディア"
# 「余が当代唯一の光の魔女というのには変わりない。だが、これからはそれに加えてネビュラ総帥としての在り方を模索しなくてはならん」
line = "「余が当代唯一の光の魔女というのには変わりない。だが、これからはそれに加えてネビュラ総帥としての在り方を模索しなくてはならん」"

[[dialogue]]
speaker = "クラウディア"
# 「開国は、その一歩だ。魔女の常識を打ち破らねば、先には進めんと思ってな」
line = "「開国は、その一歩だ。魔女の常識を打ち破らねば、先には進めんと思ってな」"

[[dialogue]]
speaker = "unk"
# 色々考えてたんだな
line = "色々考えてたんだな"

[[dialogue]]
speaker = "unk"
# クラウディアなりに……
line = "クラウディアなりに……"

[[dialogue]]
speaker = "クラウディア"
# 「ふふん。余とて捨てたものではなかろう？」
line = "「ふふん。余とて捨てたものではなかろう？」"

[[dialogue]]
speaker = "クラウディア"
# 「とはいえ……いざ道を切り拓いても、この先をどう進むべきかは未だ悩ましい」
line = "「とはいえ……いざ道を切り拓いても、この先をどう進むべきかは未だ悩ましい」"

[[dialogue]]
speaker = "クラウディア"
# 「セドナも忙しなさそうに動いておるし、余だけで何もかも決められるわけではない」
line = "「セドナも忙しなさそうに動いておるし、余だけで何もかも決められるわけではない」"

[[dialogue]]
speaker = "クラウディア"
# 「となれば、いつも余の隣にいて、共に導いてくれる存在が欲しいものだ」
line = "「となれば、いつも余の隣にいて、共に導いてくれる存在が欲しいものだ」"

[[dialogue]]
speaker = "unk"
# 俺のこと？
line = "俺のこと？"

[[dialogue]]
speaker = "クラウディア"
# 「──無論だ！　余と相思相愛、唯一無二のぱーとなー！」
line = "「──無論だ！　余と相思相愛、唯一無二のぱーとなー！」"

[[dialogue]]
speaker = "クラウディア"
# 「光の魔女と魔王だぞ？　まさに最強無敵のカップリングではないか！　余らが揃えば、何が起きても平気だと思えるのだ」
line = "「光の魔女と魔王だぞ？　まさに最強無敵のカップリングではないか！　余らが揃えば、何が起きても平気だと思えるのだ」"

[[dialogue]]
speaker = "クラウディア"
# 「これからの未来も共に歩んでいこうぞ、魔王！」
line = "「これからの未来も共に歩んでいこうぞ、魔王！」"

[[dialogue]]
speaker = "unk"
# これから待ち受ける冒険に向けて、いつまでも共にと誓い合う俺たちだった……。
line = "これから待ち受ける冒険に向けて、いつまでも共にと誓い合う俺たちだった……。"
