[[dialogue]]
speaker = "unk"
# 第２話,うれしはずかし撮影会,P
line = "第２話,うれしはずかし撮影会,P"

[[dialogue]]
speaker = "unk"
# 蘭美に呼ばれて九浄家のお屋敷にやってきた。
line = "蘭美に呼ばれて九浄家のお屋敷にやってきた。"

[[dialogue]]
speaker = "unk"
# そのはずなんだけど、蘭美はなかなか姿を見せなかった。
line = "そのはずなんだけど、蘭美はなかなか姿を見せなかった。"

[[dialogue]]
speaker = "ヨミ"
# 「すみません、メイド長はもうすぐ来ると思いますから」
line = "「すみません、メイド長はもうすぐ来ると思いますから」"

[[dialogue]]
speaker = "ヨミ"
# 「そうそう、会長の方も準備してもらっていいですか？　大丈夫です、ええ、お手間は取らせません」
line = "「そうそう、会長の方も準備してもらっていいですか？　大丈夫です、ええ、お手間は取らせません」"

[[dialogue]]
speaker = "ヨミ"
# 「あ、少しじっとしてて下さいね～。大丈夫、悪いようにはしませんから」
line = "「あ、少しじっとしてて下さいね～。大丈夫、悪いようにはしませんから」"

[[dialogue]]
speaker = "ヨミ"
# 「さぁ、メイド隊の皆さん、やっちゃって下さい♪」
line = "「さぁ、メイド隊の皆さん、やっちゃって下さい♪」"

[[dialogue]]
speaker = "unk"
# あ～～れ～～！
line = "あ～～れ～～！"

[[dialogue]]
speaker = "蘭美"
# 「会って早々、ひどい顔をしているわね！」
line = "「会って早々、ひどい顔をしているわね！」"

[[dialogue]]
speaker = "蘭美"
# 「着付けがそんなに大変だったのかしら？　うちのメイドに任せていれば、すぐ終わると思ったけど」
line = "「着付けがそんなに大変だったのかしら？　うちのメイドに任せていれば、すぐ終わると思ったけど」"

[[dialogue]]
speaker = "unk"
# なんで俺が着物を着てるの？
line = "なんで俺が着物を着てるの？"

[[dialogue]]
speaker = "unk"
# えっと、この格好は？
line = "えっと、この格好は？"

[[dialogue]]
speaker = "蘭美"
# 「スピーディかつ順を追って説明するわ！」
line = "「スピーディかつ順を追って説明するわ！」"

[[dialogue]]
speaker = "蘭美"
# 「実は魔界にいる両親に、貴方のことを報告させてもらったの。婚約者を見つけました、ってね」
line = "「実は魔界にいる両親に、貴方のことを報告させてもらったの。婚約者を見つけました、ってね」"

[[dialogue]]
speaker = "蘭美"
# 「そうしたら、どんな相手か教えなさいって言われて。貴方の写真を送るよう求められたのよ」
line = "「そうしたら、どんな相手か教えなさいって言われて。貴方の写真を送るよう求められたのよ」"

[[dialogue]]
speaker = "蘭美"
# 「せっかくならいい印象を持ってもらいたいでしょう？　だから、きちんとした写真を撮って送ろうと思ったのよ！」
line = "「せっかくならいい印象を持ってもらいたいでしょう？　だから、きちんとした写真を撮って送ろうと思ったのよ！」"

[[dialogue]]
speaker = "ヨミ"
# 「カメラマンは私が担当しますね。ばっちり撮りますので、期待して下さいっ」
line = "「カメラマンは私が担当しますね。ばっちり撮りますので、期待して下さいっ」"

[[dialogue]]
speaker = "蘭美"
# 「頼んだわよ、ヨミヨミ。私と会長の運命を左右する重要な１枚になるから、責任重大よ」
line = "「頼んだわよ、ヨミヨミ。私と会長の運命を左右する重要な１枚になるから、責任重大よ」"

[[dialogue]]
speaker = "ヨミ"
# 「こやぁっ！？　そんなプレッシャーかけないで下さ～いっ」
line = "「こやぁっ！？　そんなプレッシャーかけないで下さ～いっ」"

[[dialogue]]
speaker = "蘭美"
# 「貴方なら絶対に大丈夫よ！　いつも通りにやれば問題ないわ」
line = "「貴方なら絶対に大丈夫よ！　いつも通りにやれば問題ないわ」"

[[dialogue]]
speaker = "ヨミ"
# 「わ、わかりました！　それでは私、天ヶ崎ヨミがお２人の写真を担当しますね」
line = "「わ、わかりました！　それでは私、天ヶ崎ヨミがお２人の写真を担当しますね」"

[[dialogue]]
speaker = "ヨミ"
# 「では、軽く数枚撮ってみましょうか。はい、並んで並んで～、そうです、もっと笑顔でお願いしますっ」
line = "「では、軽く数枚撮ってみましょうか。はい、並んで並んで～、そうです、もっと笑顔でお願いしますっ」"

[[dialogue]]
speaker = "蘭美"
# 「わかったわ、こうかしら？」
line = "「わかったわ、こうかしら？」"

[[dialogue]]
speaker = "unk"
# もっと近づいた方がいいんじゃない？
line = "もっと近づいた方がいいんじゃない？"

[[dialogue]]
speaker = "蘭美"
# 「それもそうね！　婚約した２人の仲睦まじい姿を収めるのが目的なわけだし」
line = "「それもそうね！　婚約した２人の仲睦まじい姿を収めるのが目的なわけだし」"

[[dialogue]]
speaker = "蘭美"
# 「なら……ぎゅっ、と……抱き着いていた方がいいかしら？」
line = "「なら……ぎゅっ、と……抱き着いていた方がいいかしら？」"

[[dialogue]]
speaker = "蘭美"
# 「ヨミヨミ？　こんな感じでどうかしら！」
line = "「ヨミヨミ？　こんな感じでどうかしら！」"

[[dialogue]]
speaker = "ヨミ"
# 「ばっちりです！　じゃあ、撮っていきまーす！」
line = "「ばっちりです！　じゃあ、撮っていきまーす！」"

[[dialogue]]
speaker = "ヨミ"
# 「いいですよ～、いちゃいちゃ感が伝わってきます！」
line = "「いいですよ～、いちゃいちゃ感が伝わってきます！」"

[[dialogue]]
speaker = "蘭美"
# 「いちゃいちゃ……ということなら、こういうのもありかしら？」
line = "「いちゃいちゃ……ということなら、こういうのもありかしら？」"

[[dialogue]]
speaker = "ヨミ"
# 「あっ、とってもいいです！　このバージョンも頂いちゃいますね♪」
line = "「あっ、とってもいいです！　このバージョンも頂いちゃいますね♪」"

[[dialogue]]
speaker = "ヨミ"
# 「メイド長の可愛さが伝わってきます！　はい、次はもっと微笑んで～……にこっ♪」
line = "「メイド長の可愛さが伝わってきます！　はい、次はもっと微笑んで～……にこっ♪」"

[[dialogue]]
speaker = "蘭美"
# 「にこっ<emoji=heart04>」
line = "「にこっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺のお嫁さん、可愛すぎでは……？
line = "俺のお嫁さん、可愛すぎでは……？"

[[dialogue]]
speaker = "蘭美"
# 「あら、私が可愛いのは当然でしょう？　しかも、隣に貴方がいるんだもの、可愛さも倍増よ！」
line = "「あら、私が可愛いのは当然でしょう？　しかも、隣に貴方がいるんだもの、可愛さも倍増よ！」"

[[dialogue]]
speaker = "ヨミ"
# 「はい、会長もメイド長にあわせて笑顔を下さ～い」
line = "「はい、会長もメイド長にあわせて笑顔を下さ～い」"

[[dialogue]]
speaker = "蘭美"
# 「ほら、カメラマンのリクエストよ。貴方もアピールしなさい」
line = "「ほら、カメラマンのリクエストよ。貴方もアピールしなさい」"

[[dialogue]]
speaker = "蘭美"
# 「戸惑っているの？　別に可愛さを求めてはいないのよ。私の婚約者として、いつものように格好よくしていなさい！」
line = "「戸惑っているの？　別に可愛さを求めてはいないのよ。私の婚約者として、いつものように格好よくしていなさい！」"

[[dialogue]]
speaker = "unk"
# 蘭美は俺が守る！
line = "蘭美は俺が守る！"

[[dialogue]]
speaker = "蘭美"
# 「ぴゃあっ！？　なんでいきなり抱き締めてるのっ！」
line = "「ぴゃあっ！？　なんでいきなり抱き締めてるのっ！」"

[[dialogue]]
speaker = "ヨミ"
# 「そういうのもいいですね！　婚約者同士、ラブラブなところを見せつけちゃって下さ～い！」
line = "「そういうのもいいですね！　婚約者同士、ラブラブなところを見せつけちゃって下さ～い！」"

[[dialogue]]
speaker = "蘭美"
# 「待ちなさい、ヨミヨミっ、これは撮らなくていいわっ」
line = "「待ちなさい、ヨミヨミっ、これは撮らなくていいわっ」"

[[dialogue]]
speaker = "ヨミ"
# 「ご実家に送るかどうかは後で考えるとして、これは撮るべきだと思います！　なので撮りますっ！」
line = "「ご実家に送るかどうかは後で考えるとして、これは撮るべきだと思います！　なので撮りますっ！」"

[[dialogue]]
speaker = "ヨミ"
# 「はい、バッチリ頂きました～♪」
line = "「はい、バッチリ頂きました～♪」"

[[dialogue]]
speaker = "蘭美"
# 「はぁ……はぁ……もう、ヨミヨミも会長も調子に乗りすぎよ」
line = "「はぁ……はぁ……もう、ヨミヨミも会長も調子に乗りすぎよ」"

[[dialogue]]
speaker = "蘭美"
# 「撮影の目的を忘れたのかしら！？　両親に貴方を紹介するための写真なんだから」
line = "「撮影の目的を忘れたのかしら！？　両親に貴方を紹介するための写真なんだから」"

[[dialogue]]
speaker = "蘭美"
# 「その……私が選んだ婚約者が、破廉恥だと思われたら困るでしょ」
line = "「その……私が選んだ婚約者が、破廉恥だと思われたら困るでしょ」"

[[dialogue]]
speaker = "unk"
# もっとアピールした方がいいと思って
line = "もっとアピールした方がいいと思って"

[[dialogue]]
speaker = "unk"
# 好きあってることを
line = "好きあってることを"

[[dialogue]]
speaker = "蘭美"
# 「今までの写真で、十分伝わるんじゃないかしら……」
line = "「今までの写真で、十分伝わるんじゃないかしら……」"

[[dialogue]]
speaker = "蘭美"
# 「自分では、かなり仲睦まじいところを見せたつもりだったのだけど」
line = "「自分では、かなり仲睦まじいところを見せたつもりだったのだけど」"

[[dialogue]]
speaker = "ヨミ"
# 「では、もう一歩踏み込んだ、恋人らしい一面を見せちゃうのはどうでしょう？」
line = "「では、もう一歩踏み込んだ、恋人らしい一面を見せちゃうのはどうでしょう？」"

[[dialogue]]
speaker = "ヨミ"
# 「具体的には……キスしてるところ、とか？」
line = "「具体的には……キスしてるところ、とか？」"

[[dialogue]]
speaker = "蘭美"
# 「っっ！？　無理に決まってるぴょんっ！！」
line = "「っっ！？　無理に決まってるぴょんっ！！」"

[[dialogue]]
speaker = "ヨミ"
# 「えへへ、ですよね～」
line = "「えへへ、ですよね～」"

[[dialogue]]
speaker = "蘭美"
# 「人前でするのもどうかと思うのに、両親に見せるだなんて、できるわけないでしょう……」
line = "「人前でするのもどうかと思うのに、両親に見せるだなんて、できるわけないでしょう……」"

[[dialogue]]
speaker = "蘭美"
# 「まったく！　ヨミヨミにも困ったものね……」
line = "「まったく！　ヨミヨミにも困ったものね……」"

[[dialogue]]
speaker = "蘭美"
# 「え……ちょっと、会長？　なにこっちをじぃーっと見つめて……も、もしかして唇を見ているの？」
line = "「え……ちょっと、会長？　なにこっちをじぃーっと見つめて……も、もしかして唇を見ているの？」"

[[dialogue]]
speaker = "蘭美"
# 「まさか本気でキスの写真を……あ、こら、ちょっと、近づかないで。そんな、強引に……抱き締めないのっ！」
line = "「まさか本気でキスの写真を……あ、こら、ちょっと、近づかないで。そんな、強引に……抱き締めないのっ！」"

[[dialogue]]
speaker = "ヨミ"
# 「こ、これはシャッターチャンスですか！？」
line = "「こ、これはシャッターチャンスですか！？」"

[[dialogue]]
speaker = "蘭美"
# 「んちゅ<emoji=heart04>　ちゅ<emoji=heart04>　こらぁ、何度もキスしないで……んふっ、ちゅ<emoji=heart04>」
line = "「んちゅ<emoji=heart04>　ちゅ<emoji=heart04>　こらぁ、何度もキスしないで……んふっ、ちゅ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「あぁ……いっぱいキスしてるとこ、撮られちゃってるぴょん……<emoji=heart04>」
line = "「あぁ……いっぱいキスしてるとこ、撮られちゃってるぴょん……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# こうして蘭美とのうれしはずかしい写真が大量に撮影されたのだった。
line = "こうして蘭美とのうれしはずかしい写真が大量に撮影されたのだった。"
