[[dialogue]]
speaker = "unk"
# 第３話,お姉ちゃんの日,P
line = "第３話,お姉ちゃんの日,P"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「ねえ会長くん。父の日、母の日ってあるじゃない？」
line = "「ねえ会長くん。父の日、母の日ってあるじゃない？」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「育ててくれたご両親に感謝を伝える日。カーネーションを贈ったり、ささやかな食事をしたり～」
line = "「育ててくれたご両親に感謝を伝える日。カーネーションを贈ったり、ささやかな食事をしたり～」"

[[dialogue]]
speaker = "unk"
# 魔界にもあるんですか？
line = "魔界にもあるんですか？"

[[dialogue]]
speaker = "unk"
# ありますね
line = "ありますね"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「もちろん♪　たぶん、どの世界でも似たような風習はあると思うわ～」
line = "「もちろん♪　たぶん、どの世界でも似たような風習はあると思うわ～」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「だけど私、前々から疑問に思っていたことがあって……」
line = "「だけど私、前々から疑問に思っていたことがあって……」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「どうしてお姉ちゃんの日はないのかしら～！？」
line = "「どうしてお姉ちゃんの日はないのかしら～！？」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「お父さんもお母さんもお祝いされるのに、お姉ちゃんの日がないのは不公平だな～って毎年思ってるの！」
line = "「お父さんもお母さんもお祝いされるのに、お姉ちゃんの日がないのは不公平だな～って毎年思ってるの！」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「ね。会長くんもそうは思わない？」
line = "「ね。会長くんもそうは思わない？」"

[[dialogue]]
speaker = "unk"
# なんで俺に振るんですか！？
line = "なんで俺に振るんですか！？"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「え～。だって会長くん、妹ちゃんがたくさんいるでしょう？　お兄ちゃんの日があったら、妹みんなからお祝いしてもらえるのよ～？」
line = "「え～。だって会長くん、妹ちゃんがたくさんいるでしょう？　お兄ちゃんの日があったら、妹みんなからお祝いしてもらえるのよ～？」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「実質、誕生日が１日増えるようなものじゃない？　それなのに、あるのは父の日と母の日だけ……とっても悲しいわ～」
line = "「実質、誕生日が１日増えるようなものじゃない？　それなのに、あるのは父の日と母の日だけ……とっても悲しいわ～」"

[[dialogue]]
speaker = "unk"
# 仕方ないですよ、ないものはないので
line = "仕方ないですよ、ないものはないので"

[[dialogue]]
speaker = "unk"
# まあそうかもしれませんが……
line = "まあそうかもしれませんが……"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「くすん。お父さんとお母さんばかりずるいわ。お姉ちゃんだっていっぱいお祝いされたいのに～」
line = "「くすん。お父さんとお母さんばかりずるいわ。お姉ちゃんだっていっぱいお祝いされたいのに～」"

[[dialogue]]
speaker = "アナ"
# 「──お疲れ様です。何だか盛り上がってるみたいですね」
line = "「──お疲れ様です。何だか盛り上がってるみたいですね」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「あら～アナちゃん、お疲れ様～。今ね、世界の不平等について会長くんとディスカッションをしていたの～♪」
line = "「あら～アナちゃん、お疲れ様～。今ね、世界の不平等について会長くんとディスカッションをしていたの～♪」"

[[dialogue]]
speaker = "アナ"
# 「そんな大それた話ではないと思いますが……というか、ありますよ。姉の日も、兄の日も」
line = "「そんな大それた話ではないと思いますが……というか、ありますよ。姉の日も、兄の日も」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「えっ……！？」
line = "「えっ……！？」"

[[dialogue]]
speaker = "unk"
# あるの！？
line = "あるの！？"

[[dialogue]]
speaker = "アナ"
# 「はい。姉の日は１２月６日。兄の日は６月６日です」
line = "「はい。姉の日は１２月６日。兄の日は６月６日です」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「嘘……魔界にはそんなものはなかったのだけれど。もしかして、天界の風習かしら？」
line = "「嘘……魔界にはそんなものはなかったのだけれど。もしかして、天界の風習かしら？」"

[[dialogue]]
speaker = "アナ"
# 「いえ、天界にもありません。姉の日、兄の日は、人間界のとある研究者が提唱をした記念日になります」
line = "「いえ、天界にもありません。姉の日、兄の日は、人間界のとある研究者が提唱をした記念日になります」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「──本当だわ！　ＤＩＳＣで検索したら出てくるわよ、会長くん！」
line = "「──本当だわ！　ＤＩＳＣで検索したら出てくるわよ、会長くん！」"

[[dialogue]]
speaker = "unk"
# というかアナ、よく知ってたね
line = "というかアナ、よく知ってたね"

[[dialogue]]
speaker = "unk"
# 本当だ……！？
line = "本当だ……！？"

[[dialogue]]
speaker = "アナ"
# 「留学生である以上、流星市国を含む、この国の風習を知ることは大切なので。暦にまつわる記念日など、当然調べています」
line = "「留学生である以上、流星市国を含む、この国の風習を知ることは大切なので。暦にまつわる記念日など、当然調べています」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「すご～い！　すごいわ！　これでソフィにお祝いしてもらえる日が増えるのね！」
line = "「すご～い！　すごいわ！　これでソフィにお祝いしてもらえる日が増えるのね！」"

[[dialogue]]
speaker = "アナ"
# 「会長もおめでとうございます。これでルルカさんを筆頭に、増えすぎた妹方からお祝いされ放題ですね」
line = "「会長もおめでとうございます。これでルルカさんを筆頭に、増えすぎた妹方からお祝いされ放題ですね」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「──はっ！？　姉の日は１２月よね！？　ソフィのフィギュアスケートが忙しいタイミングだわ……今のうちからアポを取っておかなくっちゃ！」
line = "「──はっ！？　姉の日は１２月よね！？　ソフィのフィギュアスケートが忙しいタイミングだわ……今のうちからアポを取っておかなくっちゃ！」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「うんっ……ちょうどソフィ、カフェにいるみたい！　ごめんね、ちょっとお出かけするわ～！」
line = "「うんっ……ちょうどソフィ、カフェにいるみたい！　ごめんね、ちょっとお出かけするわ～！」"

[[dialogue]]
speaker = "アナ"
# 「……サーシャ先輩、随分と変わりましたね。以前まではこういう対人関係のイベントは、比較的ドライな傾向があったように思います」
line = "「……サーシャ先輩、随分と変わりましたね。以前まではこういう対人関係のイベントは、比較的ドライな傾向があったように思います」"

[[dialogue]]
speaker = "アナ"
# 「──はい。お祝いされる分にはありがたくいただくけれど、自分から何かをアプローチすることはあまりなかった気がしませんか？」
line = "「──はい。お祝いされる分にはありがたくいただくけれど、自分から何かをアプローチすることはあまりなかった気がしませんか？」"

[[dialogue]]
speaker = "アナ"
# 「自分は自分、他人は他人。離れていく人は引き止めたりしない……みたいな感じでしたよね」
line = "「自分は自分、他人は他人。離れていく人は引き止めたりしない……みたいな感じでしたよね」"

[[dialogue]]
speaker = "アナ"
# 「もともと嫌われるような人ではなかったですけれど、会長とお付き合いを始めてから、もっと温かい人になった気がします」
line = "「もともと嫌われるような人ではなかったですけれど、会長とお付き合いを始めてから、もっと温かい人になった気がします」"

[[dialogue]]
speaker = "アナ"
# 「……せっかくですから会長もカフェに行ってきては？　今日は急ぎの仕事もありませんし、恋人の妹さんと仲良くすることも大事でしょう」
line = "「……せっかくですから会長もカフェに行ってきては？　今日は急ぎの仕事もありませんし、恋人の妹さんと仲良くすることも大事でしょう」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「あ～ん、どうして信じてくれないの～……！？」
line = "「あ～ん、どうして信じてくれないの～……！？」"

[[dialogue]]
speaker = "ソフィア"
# 「当たり前です。いくらお祝いされたいからって、おかしな風習をでっちあげないでください！」
line = "「当たり前です。いくらお祝いされたいからって、おかしな風習をでっちあげないでください！」"

[[dialogue]]
speaker = "ソフィア"
# 「──あ、兄さん、助けてください。姉さんがまたおかしくなってしまいました」
line = "「──あ、兄さん、助けてください。姉さんがまたおかしくなってしまいました」"

[[dialogue]]
speaker = "ソフィア"
# 「人間界には、姉を祝う記念日があると言って聞かないんです。どうすれば……」
line = "「人間界には、姉を祝う記念日があると言って聞かないんです。どうすれば……」"

[[dialogue]]
speaker = "unk"
# （ＤＩＳＣの画面を見せる）
line = "（ＤＩＳＣの画面を見せる）"

[[dialogue]]
speaker = "unk"
# 本当だよ
line = "本当だよ"

[[dialogue]]
speaker = "ソフィア"
# 「……本当、ですね。え、人間界ってわざわざこんなのを記念日に設定されているんですか……？　人間ってみなさんシスコンなんですか？」
line = "「……本当、ですね。え、人間界ってわざわざこんなのを記念日に設定されているんですか……？　人間ってみなさんシスコンなんですか？」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「こんなのって何～？　とっても大事な日よ！　お姉ちゃんとしてお祝いされる日なんだから～！」
line = "「こんなのって何～？　とっても大事な日よ！　お姉ちゃんとしてお祝いされる日なんだから～！」"

[[dialogue]]
speaker = "ソフィア"
# 「はあ……わかりました。妹離れできない姉さんのために、その日は１日空けておきます」
line = "「はあ……わかりました。妹離れできない姉さんのために、その日は１日空けておきます」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「ありがと～♪　あ、ちゃんと<ruby=イルソーレ>流星学園寮</ruby>の寮長さんに外泊許可を取っておいてね～<emoji=heart04>」
line = "「ありがと～♪　あ、ちゃんと<ruby>流星学園寮<rt>イルソーレ</rt></ruby>の寮長さんに外泊許可を取っておいてね～<emoji=heart04>」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「その日はお姉ちゃんのお部屋にお泊まりしましょ、ソフィ～♪」
line = "「その日はお姉ちゃんのお部屋にお泊まりしましょ、ソフィ～♪」"

[[dialogue]]
speaker = "ソフィア"
# 「ええ～っ！？　嫌ですよ、姉の日だからって理由で外泊許可なんて取りたくありません！　私がシスコンみたいじゃないですか！？」
line = "「ええ～っ！？　嫌ですよ、姉の日だからって理由で外泊許可なんて取りたくありません！　私がシスコンみたいじゃないですか！？」"

[[dialogue]]
speaker = "unk"
# （と思ったけど黙っておこう）
line = "（と思ったけど黙っておこう）"

[[dialogue]]
speaker = "unk"
# （……結構シスコンでは？）
line = "（……結構シスコンでは？）"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「じゃあお姉ちゃんの方が<ruby=ラルーナ>新星学園寮</ruby>から外泊許可を取っておくわね。急いで準備しておかないと～」
line = "「じゃあお姉ちゃんの方が<ruby>新星学園寮<rt>ラルーナ</rt></ruby>から外泊許可を取っておくわね。急いで準備しておかないと～」"

[[dialogue]]
speaker = "ソフィア"
# 「何ヶ月先のことを言っているんですか……まったくもう」
line = "「何ヶ月先のことを言っているんですか……まったくもう」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「うふふ。何をして遊ぼうかしら。まずはソフィをぎゅ～っとして、頭をなでなでもして～♪」
line = "「うふふ。何をして遊ぼうかしら。まずはソフィをぎゅ～っとして、頭をなでなでもして～♪」"

[[dialogue]]
speaker = "ソフィア"
# 「……姉さんはお祝いされる側ですよね？」
line = "「……姉さんはお祝いされる側ですよね？」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「お姉ちゃんにとってのご褒美は、妹を甘やかすことなの～<emoji=heart04>」
line = "「お姉ちゃんにとってのご褒美は、妹を甘やかすことなの～<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「ま、まあ、そういうことでしたら……仕方ありません。受け入れます」
line = "「ま、まあ、そういうことでしたら……仕方ありません。受け入れます」"

[[dialogue]]
speaker = "ソフィア"
# 「あ──そうです。姉の日があるなら、きっと兄の日もありますよね」
line = "「あ──そうです。姉の日があるなら、きっと兄の日もありますよね」"

[[dialogue]]
speaker = "ソフィア"
# 「姉さんだけお祝いしたら不平等ですから。え～っと……兄の日は、１１月２３日のようですね」
line = "「姉さんだけお祝いしたら不平等ですから。え～っと……兄の日は、１１月２３日のようですね」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「あら～？　アナちゃんは６月６日って言っていたけれど」
line = "「あら～？　アナちゃんは６月６日って言っていたけれど」"

[[dialogue]]
speaker = "ソフィア"
# 「……ああ、１１月の方は『いい兄さんの日』みたいです。こっちは語呂合わせで作られたんですね」
line = "「……ああ、１１月の方は『いい兄さんの日』みたいです。こっちは語呂合わせで作られたんですね」"

[[dialogue]]
speaker = "ソフィア"
# 「６月６日も兄の日で……へえ、兄の日は１年に２回あるんですね」
line = "「６月６日も兄の日で……へえ、兄の日は１年に２回あるんですね」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「ええ～っ！？　そんなぁ、ずるいわよ会長くん！　せっかく世界の不平等が正されたと思ったのに～！！」
line = "「ええ～っ！？　そんなぁ、ずるいわよ会長くん！　せっかく世界の不平等が正されたと思ったのに～！！」"

[[dialogue]]
speaker = "unk"
# 俺のせいじゃない気がしますよ！？
line = "俺のせいじゃない気がしますよ！？"

[[dialogue]]
speaker = "ソフィア"
# 「残念ですが『いいお姉ちゃんの日』はないみたいです。なのでお祝いは１年に１回だけですね、姉さん」
line = "「残念ですが『いいお姉ちゃんの日』はないみたいです。なのでお祝いは１年に１回だけですね、姉さん」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「ひど～いっ！　お姉ちゃん、断固抗議するんだから～っ！」
line = "「ひど～いっ！　お姉ちゃん、断固抗議するんだから～っ！」"

[[dialogue]]
speaker = "unk"
# 父の日、母の日に代わる記念日をせっかく見つけたはいいものの、新たな格差が見つかってしまうとは。
line = "父の日、母の日に代わる記念日をせっかく見つけたはいいものの、新たな格差が見つかってしまうとは。"

[[dialogue]]
speaker = "unk"
# 世界から不平等が消えることはないのだと分かった１日なのだった──
line = "世界から不平等が消えることはないのだと分かった１日なのだった──"
