[[dialogue]]
speaker = "unk"
# 第１話,メスガキへの道は１日にして成らず,P
line = "第１話,メスガキへの道は１日にして成らず,P"

[[dialogue]]
speaker = "unk"
# ハロウィン当日、俺はウズメと一緒にハロウィンパーティーを楽しんでいた。
line = "ハロウィン当日、俺はウズメと一緒にハロウィンパーティーを楽しんでいた。"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くんっ、今度はあのお店に行ってみるし！」
line = "「会長くんっ、今度はあのお店に行ってみるし！」"

[[dialogue]]
speaker = "ウズメイア"
# 「見て見て！　侍パンプキン人形とかウケる！　着物姿で刀を下げてるとかマジでカッコイイ～っ♪」
line = "「見て見て！　侍パンプキン人形とかウケる！　着物姿で刀を下げてるとかマジでカッコイイ～っ♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「わっ！　ぱっと見、普通の提灯かと思ったらジャックオーランタンのデザインだし！」
line = "「わっ！　ぱっと見、普通の提灯かと思ったらジャックオーランタンのデザインだし！」"

[[dialogue]]
speaker = "ウズメイア"
# 「なるほど、このお店はそういうテーマなんだね～。まさに和洋折衷、西洋文化と日本文化の見事な融合っしょ！」
line = "「なるほど、このお店はそういうテーマなんだね～。まさに和洋折衷、西洋文化と日本文化の見事な融合っしょ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「あら、誰かと思えばウズメイア先輩と会長さんじゃありませんか」
line = "「あら、誰かと思えばウズメイア先輩と会長さんじゃありませんか」"

[[dialogue]]
speaker = "ウズメイア"
# 「あ、シャルレーヌちゃん。ガオガオ、トリックオアトリート♪」
line = "「あ、シャルレーヌちゃん。ガオガオ、トリックオアトリート♪」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ハッピーハロウィンです。イタズラされるのは勘弁して欲しいのでお菓子の方をどうぞ」
line = "「ハッピーハロウィンです。イタズラされるのは勘弁して欲しいのでお菓子の方をどうぞ」"

[[dialogue]]
speaker = "ウズメイア"
# 「あんがとー！　あたしからもお菓子をどうぞ～。ハロウィンデザインのお饅頭だし」
line = "「あんがとー！　あたしからもお菓子をどうぞ～。ハロウィンデザインのお饅頭だし」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「こんなの売ってたんですか。ウズメイア先輩はハロウィンでもやっぱり和テイストを求めちゃうんですね」
line = "「こんなの売ってたんですか。ウズメイア先輩はハロウィンでもやっぱり和テイストを求めちゃうんですね」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ところで会長さんと一緒ということは、仲良くハロウィンデートですか？」
line = "「ところで会長さんと一緒ということは、仲良くハロウィンデートですか？」"

[[dialogue]]
speaker = "ウズメイア"
# 「えへへ、そーだよ。会長くんが誘ってくれたんだよね」
line = "「えへへ、そーだよ。会長くんが誘ってくれたんだよね」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「それはそれは良かったですね、なんともお熱いことで……」
line = "「それはそれは良かったですね、なんともお熱いことで……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「普段から真面目ぶってる癖に、しっかりウズメイア先輩に手をだしちゃってるんですから……会長さんって本当に油断のならないワンちゃんですね♪」
line = "「普段から真面目ぶってる癖に、しっかりウズメイア先輩に手をだしちゃってるんですから……会長さんって本当に油断のならないワンちゃんですね♪」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「むっつりな会長さんのことですから、紳士づらしながらウズメイア先輩のことを下心いっぱいの目で見ているんでしょう？」
line = "「むっつりな会長さんのことですから、紳士づらしながらウズメイア先輩のことを下心いっぱいの目で見ているんでしょう？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「そんな年中発情状態の会長さんは、優しいウズメイア先輩に代わって私が躾けてあげましょうか？」
line = "「そんな年中発情状態の会長さんは、優しいウズメイア先輩に代わって私が躾けてあげましょうか？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「あら？　何をまんざらでもないような反応してるんです？　もしかしてウズメイア先輩という彼女がいながら私にも躾けられたいと？」
line = "「あら？　何をまんざらでもないような反応してるんです？　もしかしてウズメイア先輩という彼女がいながら私にも躾けられたいと？」"

[[dialogue]]
speaker = "unk"
# そ、そんなことは断じて！
line = "そ、そんなことは断じて！"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ムキになって否定するところが怪しくありませんか？」
line = "「ムキになって否定するところが怪しくありませんか？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ほらほら、自分が簡単に性欲に負けちゃうざこざこ会長さんじゃないって言うなら、もっとちゃんと言い返してみればいいじゃないですか」
line = "「ほらほら、自分が簡単に性欲に負けちゃうざこざこ会長さんじゃないって言うなら、もっとちゃんと言い返してみればいいじゃないですか」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「キャハハ、いい反応♪　やっぱりストレス解消には会長さんをいじめるのが一番です。いい音で鳴いてくれますからね～♪」
line = "「キャハハ、いい反応♪　やっぱりストレス解消には会長さんをいじめるのが一番です。いい音で鳴いてくれますからね～♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「んっと、えっと……」
line = "「んっと、えっと……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ん？　ウズメイア先輩、どうかしましたか？」
line = "「ん？　ウズメイア先輩、どうかしましたか？」"

[[dialogue]]
speaker = "ウズメイア"
# 「え、えへへ……会長くんのざーこ！」
line = "「え、えへへ……会長くんのざーこ！」"

[[dialogue]]
speaker = "unk"
# ウズメイア！？
line = "ウズメイア！？"

[[dialogue]]
speaker = "ウズメイア"
# 「いっつもエッチなことばっかり考えてる会長くんはざこざこだし……ええと、つまり──」
line = "「いっつもエッチなことばっかり考えてる会長くんはざこざこだし……ええと、つまり──」"

[[dialogue]]
speaker = "ウズメイア"
# 「つまりっ、据え膳食わぬは男の恥ってこと？　ざこざこな会長くんには天網恢恢疎にして漏らさずって言葉がお似合いだし！」
line = "「つまりっ、据え膳食わぬは男の恥ってこと？　ざこざこな会長くんには天網恢恢疎にして漏らさずって言葉がお似合いだし！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「突然どうしちゃったんですか、ウズメイア先輩？」
line = "「突然どうしちゃったんですか、ウズメイア先輩？」"

[[dialogue]]
speaker = "ウズメイア"
# 「えっ？　えっと、えへへ……」
line = "「えっ？　えっと、えへへ……」"

[[dialogue]]
speaker = "ウズメイア"
# 「シャルレーヌちゃんとお話してる会長くんが楽しそうに見えたから。それにシャルレーヌちゃんも楽しそうで……」
line = "「シャルレーヌちゃんとお話してる会長くんが楽しそうに見えたから。それにシャルレーヌちゃんも楽しそうで……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「会長さんはどうか分かりませんが、私は別に楽しんではいませんでしたよ？」
line = "「会長さんはどうか分かりませんが、私は別に楽しんではいませんでしたよ？」"

[[dialogue]]
speaker = "unk"
# 俺だってそうだよ！
line = "俺だってそうだよ！"

[[dialogue]]
speaker = "シャルレーヌ"
# 「……なるほど、それで急に意味のわからないことを言い始めたんですね？」
line = "「……なるほど、それで急に意味のわからないことを言い始めたんですね？」"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くん、シャルレーヌちゃんみたいに接するのが嬉しいのかなって……だからあたしもやってみたの」
line = "「会長くん、シャルレーヌちゃんみたいに接するのが嬉しいのかなって……だからあたしもやってみたの」"

[[dialogue]]
speaker = "ウズメイア"
# 「でもあたしには『メスガキ』は無理っぽいかも。なんか全然上手くいかなかったし……」
line = "「でもあたしには『メスガキ』は無理っぽいかも。なんか全然上手くいかなかったし……」"

[[dialogue]]
speaker = "unk"
# 今のウズメで大丈夫！
line = "今のウズメで大丈夫！"

[[dialogue]]
speaker = "unk"
# それは大いに誤解がある！
line = "それは大いに誤解がある！"

[[dialogue]]
speaker = "ウズメイア"
# 「ほ、本当？　いつものあたしでいいの？」
line = "「ほ、本当？　いつものあたしでいいの？」"

[[dialogue]]
speaker = "unk"
# 不安にさせちゃってごめん
line = "不安にさせちゃってごめん"

[[dialogue]]
speaker = "ウズメイア"
# 「あ……えへへ、ギュッてしてくれて……会長くん、ありがと……」
line = "「あ……えへへ、ギュッてしてくれて……会長くん、ありがと……」"

[[dialogue]]
speaker = "ウズメイア"
# 「もひとつ聞いてもいい？　会長くんはシャルレーヌちゃんに躾けられて、その……興奮しちゃった……？」
line = "「もひとつ聞いてもいい？　会長くんはシャルレーヌちゃんに躾けられて、その……興奮しちゃった……？」"

[[dialogue]]
speaker = "ウズメイア"
# 「あたしと付き合ってても、シャルレーヌちゃんに躾けられたい……？」
line = "「あたしと付き合ってても、シャルレーヌちゃんに躾けられたい……？」"

[[dialogue]]
speaker = "unk"
# 断じてそんなことはないよ
line = "断じてそんなことはないよ"

[[dialogue]]
speaker = "ウズメイア"
# 「えへへ、よかった……うん、これで全部安心できたし……もう大丈夫……」
line = "「えへへ、よかった……うん、これで全部安心できたし……もう大丈夫……」"

[[dialogue]]
speaker = "ウズメイア"
# 「ありがとう、会長くん……<emoji=heart04>」
line = "「ありがとう、会長くん……<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「コホン……あの、私は何を見せられているんでしょうね？　惚気るなら目につかないところでやってもらえます？」
line = "「コホン……あの、私は何を見せられているんでしょうね？　惚気るなら目につかないところでやってもらえます？」"

[[dialogue]]
speaker = "ウズメイア"
# 「はっ！？　ご、ごめんなさいだし！」
line = "「はっ！？　ご、ごめんなさいだし！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ま、今回はやきもちをやくウズメイア先輩というレアなものが見られたので良しとしますか……」
line = "「ま、今回はやきもちをやくウズメイア先輩というレアなものが見られたので良しとしますか……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「とにかくウズメイア先輩のことを大事にしてあげてください。先輩を泣かせるようなことをしたら、本気で躾に行きますからね」
line = "「とにかくウズメイア先輩のことを大事にしてあげてください。先輩を泣かせるようなことをしたら、本気で躾に行きますからね」"

[[dialogue]]
speaker = "unk"
# 張本人がそれを言うか、と口から出かかったが何とかそれを抑え込んだ。
line = "張本人がそれを言うか、と口から出かかったが何とかそれを抑え込んだ。"

[[dialogue]]
speaker = "unk"
# シャルレーヌのメスガキ煽りに付き合っていると、ウズメがまた不安がってしまうかもしれないから。
line = "シャルレーヌのメスガキ煽りに付き合っていると、ウズメがまた不安がってしまうかもしれないから。"

[[dialogue]]
speaker = "unk"
# ぐっと我慢して何も言い返さず、シャルレーヌと別れて、引き続きウズメとハロウィンデートを楽しんだのだった。
line = "ぐっと我慢して何も言い返さず、シャルレーヌと別れて、引き続きウズメとハロウィンデートを楽しんだのだった。"
