[[dialogue]]
speaker = "unk"
# 第３話,水着でキャンプ！,P
line = "第３話,水着でキャンプ！,P"

[[dialogue]]
speaker = "フィオナ"
# 「こんにちは、緋宮会長。ご足労いただきありがとうございます」
line = "「こんにちは、緋宮会長。ご足労いただきありがとうございます」"

[[dialogue]]
speaker = "unk"
# 先日の合宿はリップルのおかげで楽しく過ごせたものの、あまり合宿らしくはなかったので、改めて海辺でキャンプをしようということになったのだった。
line = "先日の合宿はリップルのおかげで楽しく過ごせたものの、あまり合宿らしくはなかったので、改めて海辺でキャンプをしようということになったのだった。"

[[dialogue]]
speaker = "ナミエル"
# 「ここは星見家メイド隊の教導施設の一部、つまり私たちの修行の場です。部外者は立ち入りませんのでご安心ください」
line = "「ここは星見家メイド隊の教導施設の一部、つまり私たちの修行の場です。部外者は立ち入りませんのでご安心ください」"

[[dialogue]]
speaker = "ナミエル"
# 「食材はメイド長が用意しましたが、釣りや素潜りで魚を獲ることも可能です」
line = "「食材はメイド長が用意しましたが、釣りや素潜りで魚を獲ることも可能です」"

[[dialogue]]
speaker = "ナミエル"
# 「シャワーとトイレはあちらに。着替えも用意しております。他にもご要望があればお申し付けください」
line = "「シャワーとトイレはあちらに。着替えも用意しております。他にもご要望があればお申し付けください」"

[[dialogue]]
speaker = "フィオナ"
# 「何から何までありがとう、ナミエル」
line = "「何から何までありがとう、ナミエル」"

[[dialogue]]
speaker = "ナミエル"
# 「いいえ。フィオナお嬢様にご不便を強いたとあれば、このナミエル、星見家に合わせる顔がございませんから」
line = "「いいえ。フィオナお嬢様にご不便を強いたとあれば、このナミエル、星見家に合わせる顔がございませんから」"

[[dialogue]]
speaker = "ナミエル"
# 「緋宮会長。私は近くに待機しておりますので、くれぐれも間違いなど起こさぬようご注意ください。もし何かあれば私とメイド長が地の果てまで追いかけます」
line = "「緋宮会長。私は近くに待機しておりますので、くれぐれも間違いなど起こさぬようご注意ください。もし何かあれば私とメイド長が地の果てまで追いかけます」"

[[dialogue]]
speaker = "ナミエル"
# 「では１泊２日の海キャンプ、お楽しみください」
line = "「では１泊２日の海キャンプ、お楽しみください」"

[[dialogue]]
speaker = "フィオナ"
# 「まずは何をしましょうか？　私はあまりキャンプの経験がないので、緋宮会長を頼らせてください」
line = "「まずは何をしましょうか？　私はあまりキャンプの経験がないので、緋宮会長を頼らせてください」"

[[dialogue]]
speaker = "unk"
# とりあえずテント！
line = "とりあえずテント！"

[[dialogue]]
speaker = "フィオナ"
# 「そうでした、キャンプといえばテント！　これがないと寝るところがありませんからね」
line = "「そうでした、キャンプといえばテント！　これがないと寝るところがありませんからね」"

[[dialogue]]
speaker = "フィオナ"
# 「ふむふむ……テントを広げて……フレームを通して……テントらしくなってきました」
line = "「ふむふむ……テントを広げて……フレームを通して……テントらしくなってきました」"

[[dialogue]]
speaker = "フィオナ"
# 「フレームを繋げて……あ、ちゃんとテントになりました！　もっと複雑かと思っていたんですけど、けっこう手軽にできるんですね」
line = "「フレームを繋げて……あ、ちゃんとテントになりました！　もっと複雑かと思っていたんですけど、けっこう手軽にできるんですね」"

[[dialogue]]
speaker = "フィオナ"
# 「上にフライシートをかけて、ペグで地面に固定して……テントの完成です！　テントがあるだけでもずいぶんキャンプらしくなった気がします」
line = "「上にフライシートをかけて、ペグで地面に固定して……テントの完成です！　テントがあるだけでもずいぶんキャンプらしくなった気がします」"

[[dialogue]]
speaker = "unk"
# 次はバーベキュー！
line = "次はバーベキュー！"

[[dialogue]]
speaker = "フィオナ"
# 「！　いいですね、私もバーベキューしてみたかったんです」
line = "「！　いいですね、私もバーベキューしてみたかったんです」"

[[dialogue]]
speaker = "フィオナ"
# 「確か炭と道具はナミエルが用意してくれたはず……あ、ありました。お肉と野菜も串に刺してありますね」
line = "「確か炭と道具はナミエルが用意してくれたはず……あ、ありました。お肉と野菜も串に刺してありますね」"

[[dialogue]]
speaker = "フィオナ"
# 「火はどうすれば……はい、空気が入るように炭をバーベキューコンロに並べて……これでいいですか？」
line = "「火はどうすれば……はい、空気が入るように炭をバーベキューコンロに並べて……これでいいですか？」"

[[dialogue]]
speaker = "フィオナ"
# 「すぐに炭に火がつかないから、着火剤も必要……？　なるほど、着火剤が燃えている間に炭に火がつくんですね」
line = "「すぐに炭に火がつかないから、着火剤も必要……？　なるほど、着火剤が燃えている間に炭に火がつくんですね」"

[[dialogue]]
speaker = "フィオナ"
# 「うちわで扇いで……あ、炭が赤くなってきました。では焼いていきましょう」
line = "「うちわで扇いで……あ、炭が赤くなってきました。では焼いていきましょう」"

[[dialogue]]
speaker = "フィオナ"
# 「おお……炭の火力で肉がじゅ～っと焼けて……いい匂いです♪」
line = "「おお……炭の火力で肉がじゅ～っと焼けて……いい匂いです♪」"

[[dialogue]]
speaker = "フィオナ"
# 「そろそろいけそうでしょうか？　……もうちょっと焼いた方がいい？　そうですね、ちゃんと中まで火を通さないと」
line = "「そろそろいけそうでしょうか？　……もうちょっと焼いた方がいい？　そうですね、ちゃんと中まで火を通さないと」"

[[dialogue]]
speaker = "フィオナ"
# 「普段は食事の用意もメイドたちがしてくれますから、こうして自分で調理するのも新鮮です」
line = "「普段は食事の用意もメイドたちがしてくれますから、こうして自分で調理するのも新鮮です」"

[[dialogue]]
speaker = "フィオナ"
# 「もう食べられそうですね……わっ、熱い。とてもおいしそう……。串から外した方が食べやすいですかね？」
line = "「もう食べられそうですね……わっ、熱い。とてもおいしそう……。串から外した方が食べやすいですかね？」"

[[dialogue]]
speaker = "unk"
# ここはワイルドにがぶっと！
line = "ここはワイルドにがぶっと！"

[[dialogue]]
speaker = "フィオナ"
# 「そうですね、せっかくのバーベキューですから豪快にいただきます。あ～ん」
line = "「そうですね、せっかくのバーベキューですから豪快にいただきます。あ～ん」"

[[dialogue]]
speaker = "フィオナ"
# 「ん～♪　おいし～♪」
line = "「ん～♪　おいし～♪」"

[[dialogue]]
speaker = "フィオナ"
# 「ほら、お肉はまだまだありますから、緋宮会長も食べてください」
line = "「ほら、お肉はまだまだありますから、緋宮会長も食べてください」"

[[dialogue]]
speaker = "unk"
# おいしい！
line = "おいしい！"

[[dialogue]]
speaker = "フィオナ"
# 「ですよね。海辺で食べると、普段と違う味わいがあります」
line = "「ですよね。海辺で食べると、普段と違う味わいがあります」"

[[dialogue]]
speaker = "フィオナ"
# 「……デザートにはスモア？　それはいったい？　焼いたマシュマロとチョコをビスケットに挟んで……確かにバーベキューにピッタリですね。とってもおいしそうです♪」
line = "「……デザートにはスモア？　それはいったい？　焼いたマシュマロとチョコをビスケットに挟んで……確かにバーベキューにピッタリですね。とってもおいしそうです♪」"

[[dialogue]]
speaker = "フィオナ"
# 「そうだ、食べたらカヤックに乗りませんか？　２人で乗ってもいいですし、競走してもいいですし」
line = "「そうだ、食べたらカヤックに乗りませんか？　２人で乗ってもいいですし、競走してもいいですし」"

[[dialogue]]
speaker = "フィオナ"
# 「もちろん釣りだってしたいです。さ、海を楽しみましょう！」
line = "「もちろん釣りだってしたいです。さ、海を楽しみましょう！」"

[[dialogue]]
speaker = "フィオナ"
# 「すっかり日が暮れてしまいましたね」
line = "「すっかり日が暮れてしまいましたね」"

[[dialogue]]
speaker = "フィオナ"
# 「う……夜になると、夏でもさすがに肌寒いですね……」
line = "「う……夜になると、夏でもさすがに肌寒いですね……」"

[[dialogue]]
speaker = "unk"
# こっち来て
line = "こっち来て"

[[dialogue]]
speaker = "フィオナ"
# 「あ……」
line = "「あ……」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ、こうしてくっついていると温かいですね」
line = "「ふふ、こうしてくっついていると温かいですね」"

[[dialogue]]
speaker = "フィオナ"
# 「見てください。夜空が綺麗ですよ。流星市国でも星は見えますけど、海で見る星はまた違った趣があります」
line = "「見てください。夜空が綺麗ですよ。流星市国でも星は見えますけど、海で見る星はまた違った趣があります」"

[[dialogue]]
speaker = "フィオナ"
# 「空に輝くあの星たちが、私たちに力を貸してくれてるんですね。昼間はあんなに眩しかったのに、今はこんなに落ち着いていて……不思議な気分です」
line = "「空に輝くあの星たちが、私たちに力を貸してくれてるんですね。昼間はあんなに眩しかったのに、今はこんなに落ち着いていて……不思議な気分です」"

[[dialogue]]
speaker = "フィオナ"
# 「もう少し……このままでいいですか？　今夜は一緒に星を見ていたい気分なんです」
line = "「もう少し……このままでいいですか？　今夜は一緒に星を見ていたい気分なんです」"
