[[dialogue]]
speaker = "unk"
# クリスマス当日。紅明とまた一緒にデートに出かけて、その帰り道でのこと――
line = "クリスマス当日。紅明とまた一緒にデートに出かけて、その帰り道でのこと――"

[[dialogue]]
speaker = "紅明"
# 「――いや～、今日は楽しかったな～♪　まさかこの前とは打って変わって、誰にもタレントだって気付かれずにデートできちゃうなんてね～」
line = "「――いや～、今日は楽しかったな～♪　まさかこの前とは打って変わって、誰にもタレントだって気付かれずにデートできちゃうなんてね～」"

[[dialogue]]
speaker = "紅明"
# 「開き直って、クリスマスプレゼント配りまくってやるぜ！　ってつもりで、サンタの格好してきてたんだけど、こういうこともあるんだね～」
line = "「開き直って、クリスマスプレゼント配りまくってやるぜ！　ってつもりで、サンタの格好してきてたんだけど、こういうこともあるんだね～」"

[[dialogue]]
speaker = "紅明"
# 「女神様がくれた、クリスマスの奇跡のやつなのかな？　――なんつってね♪」
line = "「女神様がくれた、クリスマスの奇跡のやつなのかな？　――なんつってね♪」"

[[dialogue]]
speaker = "紅明"
# 「そういえばさ、さっき、目立つくらいイチャイチャしてるカップルが近くを通ったじゃない？」
line = "「そういえばさ、さっき、目立つくらいイチャイチャしてるカップルが近くを通ったじゃない？」"

[[dialogue]]
speaker = "紅明"
# 「――そうそう。ダーリンとアタシみたいに熱々な感じの。すれ違う時に、会話がちょこっと聞こえちゃったんだけど……」
line = "「――そうそう。ダーリンとアタシみたいに熱々な感じの。すれ違う時に、会話がちょこっと聞こえちゃったんだけど……」"

[[dialogue]]
speaker = "紅明"
# 「あの２人、この後は家に帰って、朝までエッチしちゃうみたい<emoji=heart04>」
line = "「あの２人、この後は家に帰って、朝までエッチしちゃうみたい<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「うしし♪　クリスマスの夜だもんね～。当然、そういうテンションにもなっちゃうよね～<emoji=heart04>」
line = "「うしし♪　クリスマスの夜だもんね～。当然、そういうテンションにもなっちゃうよね～<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「というわけで、ダーリン――」
line = "「というわけで、ダーリン――」"

[[dialogue]]
speaker = "紅明"
# 「アタシたちもこの後、家でエッチしちゃう？」
line = "「アタシたちもこの後、家でエッチしちゃう？」"

[[dialogue]]
speaker = "unk"
# 耳元で囁かれて、期待でドキッとするが――
line = "耳元で囁かれて、期待でドキッとするが――"

[[dialogue]]
speaker = "紅明"
# 「と言いたいところなんだけど……ダーリン、ごめん！　実はこの後、外せない用事があるんだよね～」
line = "「と言いたいところなんだけど……ダーリン、ごめん！　実はこの後、外せない用事があるんだよね～」"

[[dialogue]]
speaker = "紅明"
# 「そういうわけで、今日はありがと♪　デート、楽しかったよ！」
line = "「そういうわけで、今日はありがと♪　デート、楽しかったよ！」"

[[dialogue]]
speaker = "紅明"
# 「イチャイチャの続きは、また今度ね<emoji=heart04>」
line = "「イチャイチャの続きは、また今度ね<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その後、俺はちょっと寂しい気持ちを抱えながら帰宅する。風呂に入って、自室のベッドで就寝した。
line = "その後、俺はちょっと寂しい気持ちを抱えながら帰宅する。風呂に入って、自室のベッドで就寝した。"

[[dialogue]]
speaker = "unk"
# そうして、眠っていたのだが――
line = "そうして、眠っていたのだが――"

[[dialogue]]
speaker = "？？？"
# 「んっ……<emoji=heart04>　ダーリンの……はぁ……<emoji=heart04>　寝てても大きくて……ふぅ……<emoji=heart04>　すごいっしょ……あんっ……<emoji=heart04>」
line = "「んっ……<emoji=heart04>　ダーリンの……はぁ……<emoji=heart04>　寝てても大きくて……ふぅ……<emoji=heart04>　すごいっしょ……あんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ……なんだか、ペニスが気持ちいい。そう思って、目を覚ますと――
line = "……なんだか、ペニスが気持ちいい。そう思って、目を覚ますと――"

[[dialogue]]
speaker = "紅明"
# 「あっ……♪　ダーリン、起きた？　うしし<emoji=heart04>　メリークリスマス☆」
line = "「あっ……♪　ダーリン、起きた？　うしし<emoji=heart04>　メリークリスマス☆」"

[[dialogue]]
speaker = "紅明"
# 「――なんでここにいるのかって？　実はアタシから、ダーリンにサプライズをしたいな～って思って」
line = "「――なんでここにいるのかって？　実はアタシから、ダーリンにサプライズをしたいな～って思って」"

[[dialogue]]
speaker = "紅明"
# 「見ての通り、クリスマスプレゼント的な感じで、エッチな夜這いをね<emoji=heart04>　んふふっ<emoji=heart04>」
line = "「見ての通り、クリスマスプレゼント的な感じで、エッチな夜這いをね<emoji=heart04>　んふふっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「――どうやって家に入ったのか？　リノさんに相談したら、ノリノリで協力してくれたんだよね～。スペアキーを借りちゃいました☆」
line = "「――どうやって家に入ったのか？　リノさんに相談したら、ノリノリで協力してくれたんだよね～。スペアキーを借りちゃいました☆」"

[[dialogue]]
speaker = "紅明"
# 「あ、ちなみに、リノさんからダーリンに伝言があって……」
line = "「あ、ちなみに、リノさんからダーリンに伝言があって……」"

[[dialogue]]
speaker = "紅明"
# 「今日は朝まで家に帰らないから、男として頑張りなさい――だってさ<emoji=heart04>」
line = "「今日は朝まで家に帰らないから、男として頑張りなさい――だってさ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「でも、んっ……<emoji=heart04>　サプライズとはいえ、ダーリンにはエッチお預けの残念な気分にさせちゃってたわけだし」
line = "「でも、んっ……<emoji=heart04>　サプライズとはいえ、ダーリンにはエッチお預けの残念な気分にさせちゃってたわけだし」"

[[dialogue]]
speaker = "紅明"
# 「その分、アタシがおま○こでいっぱい気持ちよくしちゃうから、ダーリンはそのまま寝転がってていいからね<emoji=heart04>」
line = "「その分、アタシがおま○こでいっぱい気持ちよくしちゃうから、ダーリンはそのまま寝転がってていいからね<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そう言うと、紅明はゆっくりと腰をグラインドさせ始めた――
line = "そう言うと、紅明はゆっくりと腰をグラインドさせ始めた――"

[[dialogue]]
speaker = "紅明"
# 「んっ<emoji=heart04>　はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　んんっ……<emoji=heart04>　はあぁっ……<emoji=heart04>」
line = "「んっ<emoji=heart04>　はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　んんっ……<emoji=heart04>　はあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あっ<emoji=heart04>　あんっ……<emoji=heart04>　ダーリンの太いおち○ぽに中押し広げられちゃって、声が出ちゃう<emoji=heart04>　はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　んうぅっ……<emoji=heart04>　ふあぁっ……<emoji=heart04>」
line = "「あっ<emoji=heart04>　あんっ……<emoji=heart04>　ダーリンの太いおち○ぽに中押し広げられちゃって、声が出ちゃう<emoji=heart04>　はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　んうぅっ……<emoji=heart04>　ふあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「――んっ<emoji=heart04>　いつもよりおま○こがすごい濡れてる？　隠してたのに……あんっ<emoji=heart04>　ダーリンに気づかれちゃった……ふうぅっ……<emoji=heart04>」
line = "「――んっ<emoji=heart04>　いつもよりおま○こがすごい濡れてる？　隠してたのに……あんっ<emoji=heart04>　ダーリンに気づかれちゃった……ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「本当はアタシも、んんっ……<emoji=heart04>　あのイチャイチャカップルの会話を聞いた時から、早く夜這いして、ダーリンとエッチしたいって期待しちゃってて……あんっ<emoji=heart04>」
line = "「本当はアタシも、んんっ……<emoji=heart04>　あのイチャイチャカップルの会話を聞いた時から、早く夜這いして、ダーリンとエッチしたいって期待しちゃってて……あんっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「時間が真夜中になるまで我慢している間も、まだかまだかとおま○こ待ちわびて、ぐちゅちゅになっちゃってたのぉ……<emoji=heart04>　はぁんっ……<emoji=heart04>」
line = "「時間が真夜中になるまで我慢している間も、まだかまだかとおま○こ待ちわびて、ぐちゅちゅになっちゃってたのぉ……<emoji=heart04>　はぁんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「だから、ごめん。んっ……<emoji=heart04>　本当はパイズリとか、フェラとかで起こそうかなって考えてたりもしたんだけど……ふあぁっ……<emoji=heart04>」
line = "「だから、ごめん。んっ……<emoji=heart04>　本当はパイズリとか、フェラとかで起こそうかなって考えてたりもしたんだけど……ふあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ダーリンのおち○ぽ見たら我慢できなくて……入れちゃったぁ……<emoji=heart04>　あんっ<emoji=heart04>　はあぁっ……<emoji=heart04>　んうぅっ……<emoji=heart04>　あっ……<emoji=heart04>　んあぁっ……<emoji=heart04>」
line = "「ダーリンのおち○ぽ見たら我慢できなくて……入れちゃったぁ……<emoji=heart04>　あんっ<emoji=heart04>　はあぁっ……<emoji=heart04>　んうぅっ……<emoji=heart04>　あっ……<emoji=heart04>　んあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あっ<emoji=heart04>　すごい<emoji=heart04>　ダーリンのもっと大きくなって、固くなってるぅ<emoji=heart04>　はあぁっ……<emoji=heart04>　んっ<emoji=heart04>　あっ……ふあぁっ……<emoji=heart04>」
line = "「あっ<emoji=heart04>　すごい<emoji=heart04>　ダーリンのもっと大きくなって、固くなってるぅ<emoji=heart04>　はあぁっ……<emoji=heart04>　んっ<emoji=heart04>　あっ……ふあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「――アタシがエッチなこと言うから？　んモー、ダーリンが言わせたんでしょぉ<emoji=heart04>　あっ<emoji=heart04>　あんっ<emoji=heart04>　ふうぅっ……<emoji=heart04>　んあぁっ……<emoji=heart04>」
line = "「――アタシがエッチなこと言うから？　んモー、ダーリンが言わせたんでしょぉ<emoji=heart04>　あっ<emoji=heart04>　あんっ<emoji=heart04>　ふうぅっ……<emoji=heart04>　んあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んっ……<emoji=heart04>　おま○こ、すっかりトロトロで堪らなくなっちゃってるから、もうそろそろ、いつもの<b>アレ</b>しちゃうね？」
line = "「んっ……<emoji=heart04>　おま○こ、すっかりトロトロで堪らなくなっちゃってるから、もうそろそろ、いつもの<b>アレ</b>しちゃうね？」"

[[dialogue]]
speaker = "紅明"
# 「――うん<emoji=heart04>　ダーリンの好きな……『おま○こハグ』<emoji=heart04>」
line = "「――うん<emoji=heart04>　ダーリンの好きな……『おま○こハグ』<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「それじゃあ、いくよ～？　はい、ぎゅうぅ～～～っ<emoji=heart04><emoji=heart04>」
line = "「それじゃあ、いくよ～？　はい、ぎゅうぅ～～～っ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# おま○こが俺のペニスを抱き締めるように、ぎゅっと柔らかい肉壁を絡みつかせてくる。
line = "おま○こが俺のペニスを抱き締めるように、ぎゅっと柔らかい肉壁を絡みつかせてくる。"

[[dialogue]]
speaker = "unk"
# 紅明曰く、人生２周目の経験によるエッチスキルらしい。その天国のような感触に包まれて、思わず気持ちよさで身じろぎしてしまう。
line = "紅明曰く、人生２周目の経験によるエッチスキルらしい。その天国のような感触に包まれて、思わず気持ちよさで身じろぎしてしまう。"

[[dialogue]]
speaker = "紅明"
# 「んっ……<emoji=heart04>　このまま、ピストン始めちゃうね？　はあぁっ……<emoji=heart04>　んんっ――<emoji=heart04><emoji=heart04>」
line = "「んっ……<emoji=heart04>　このまま、ピストン始めちゃうね？　はあぁっ……<emoji=heart04>　んんっ――<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ふあぁっ<emoji=heart04>　あっ……あんっ<emoji=heart04>　はあぁっ……<emoji=heart04>　んあぁっ……<emoji=heart04>　あっ……<emoji=heart04>　ふあぁっ<emoji=heart04>　んっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　あんっ<emoji=heart04>　んあぁっ……<emoji=heart04>」
line = "「ふあぁっ<emoji=heart04>　あっ……あんっ<emoji=heart04>　はあぁっ……<emoji=heart04>　んあぁっ……<emoji=heart04>　あっ……<emoji=heart04>　ふあぁっ<emoji=heart04>　んっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　あんっ<emoji=heart04>　んあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「おま○こハグで、密着して感じるぅ……<emoji=heart04>　はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　すごいぃ<emoji=heart04>　あっ<emoji=heart04>　んっ……ふあぁっ<emoji=heart04>　はあぁっ……<emoji=heart04>」
line = "「おま○こハグで、密着して感じるぅ……<emoji=heart04>　はあぁっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　すごいぃ<emoji=heart04>　あっ<emoji=heart04>　んっ……ふあぁっ<emoji=heart04>　はあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ダーリンのでっかいおち○ぽ、いちばん奥にグリグリって当たって、んあぁっ<emoji=heart04>　気持ちいい……<emoji=heart04>　んうぅっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　ふあぁっ……<emoji=heart04>」
line = "「ダーリンのでっかいおち○ぽ、いちばん奥にグリグリって当たって、んあぁっ<emoji=heart04>　気持ちいい……<emoji=heart04>　んうぅっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　ふあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あっ<emoji=heart04>　あんっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　んっ……<emoji=heart04>　はあぁんっ……<emoji=heart04>　ダーリンってば、喘ぎ声が出ちゃってる<emoji=heart04>」
line = "「あっ<emoji=heart04>　あんっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>　んっ……<emoji=heart04>　はあぁんっ……<emoji=heart04>　ダーリンってば、喘ぎ声が出ちゃってる<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んっ……<emoji=heart04>　感じてる顔もかわいい<emoji=heart04>　あっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　んふぅっ……<emoji=heart04>　そんなに気持ちいいんだ……？」
line = "「んっ……<emoji=heart04>　感じてる顔もかわいい<emoji=heart04>　あっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　んふぅっ……<emoji=heart04>　そんなに気持ちいいんだ……？」"

[[dialogue]]
speaker = "紅明"
# 「聞いてると、アタシも興奮してきちゃう……あんっ<emoji=heart04>　はあぁっ……<emoji=heart04>　んっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」
line = "「聞いてると、アタシも興奮してきちゃう……あんっ<emoji=heart04>　はあぁっ……<emoji=heart04>　んっ……<emoji=heart04>　ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「かわいい反応、もっと見せて<emoji=heart04>　ほら、おま○こハグの中動かすやつ、しちゃうから<emoji=heart04>　ふうぅっ……<emoji=heart04>　んんっ……！」
line = "「かわいい反応、もっと見せて<emoji=heart04>　ほら、おま○こハグの中動かすやつ、しちゃうから<emoji=heart04>　ふうぅっ……<emoji=heart04>　んんっ……！」"

[[dialogue]]
speaker = "unk"
# 紅明の膣内が、ペニスに絡みついてくるだけでなく、飲み込むようにうねうね動く。俺はまた、快感で喘ぎ声が出てしまう。
line = "紅明の膣内が、ペニスに絡みついてくるだけでなく、飲み込むようにうねうね動く。俺はまた、快感で喘ぎ声が出てしまう。"

[[dialogue]]
speaker = "紅明"
# 「んふっ<emoji=heart04>　ダーリンのおち○ぽ、ビクビクしてる<emoji=heart04>　いっぱい気持ちよくなって<emoji=heart04>　ほら、奥までパンッパン<emoji=heart04>　ずっぷずっぷ<emoji=heart04>　にゅっぽにゅっぽ<emoji=heart04>」
line = "「んふっ<emoji=heart04>　ダーリンのおち○ぽ、ビクビクしてる<emoji=heart04>　いっぱい気持ちよくなって<emoji=heart04>　ほら、奥までパンッパン<emoji=heart04>　ずっぷずっぷ<emoji=heart04>　にゅっぽにゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「おま○こパンッパン<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>　にゅっぷにゅっぷ<emoji=heart04>　中でぎゅっとしながら<emoji=heart04>　ずっぽずっぽ<emoji=heart04>　じゅっぷじゅっぷ<emoji=heart04>」
line = "「おま○こパンッパン<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>　にゅっぷにゅっぷ<emoji=heart04>　中でぎゅっとしながら<emoji=heart04>　ずっぽずっぽ<emoji=heart04>　じゅっぷじゅっぷ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ふんっ<emoji=heart04>　ふんっ<emoji=heart04>　ダーリン、どう？　気持ちいい？　パンッパン<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>」
line = "「ふんっ<emoji=heart04>　ふんっ<emoji=heart04>　ダーリン、どう？　気持ちいい？　パンッパン<emoji=heart04>　じゅっぽじゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「じゅっぷじゅっぷ<emoji=heart04>　にゅっぽにゅっぽ<emoji=heart04>　あはっ☆　ダーリンってば、おっぱい見てる目がやらしいっしょ<emoji=heart04>」
line = "「じゅっぷじゅっぷ<emoji=heart04>　にゅっぽにゅっぽ<emoji=heart04>　あはっ☆　ダーリンってば、おっぱい見てる目がやらしいっしょ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「揉んでもらって大きくなった１０１センチのおっぱいの揺れ、迫力ある？　　ふんっ<emoji=heart04>　ふんっ<emoji=heart04>」
line = "「揉んでもらって大きくなった１０１センチのおっぱいの揺れ、迫力ある？　　ふんっ<emoji=heart04>　ふんっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んモー、ダーリンのエッチ～<emoji=heart04>　喘ぎ声も女の子みたいにいっぱい出ちゃってるし<emoji=heart04>　ずっぽずっぽ<emoji=heart04>　にゅっぷにゅっぷ<emoji=heart04>」
line = "「んモー、ダーリンのエッチ～<emoji=heart04>　喘ぎ声も女の子みたいにいっぱい出ちゃってるし<emoji=heart04>　ずっぽずっぽ<emoji=heart04>　にゅっぷにゅっぷ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「感じてる顔もすごくエッチなことになってるよ？　かわいくて背筋がゾクゾクしちゃう<emoji=heart04>　ふんっ<emoji=heart04>　ふんっ<emoji=heart04>」
line = "「感じてる顔もすごくエッチなことになってるよ？　かわいくて背筋がゾクゾクしちゃう<emoji=heart04>　ふんっ<emoji=heart04>　ふんっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「って、あんっ<emoji=heart04>　手で顔を隠さなくてもいいのに～。んふぅっ……<emoji=heart04>」
line = "「って、あんっ<emoji=heart04>　手で顔を隠さなくてもいいのに～。んふぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ん～？　――見られるのが恥ずかしいって？　喘ぎ声も？　はあぁっ……<emoji=heart04>」
line = "「ん～？　――見られるのが恥ずかしいって？　喘ぎ声も？　はあぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ふ～ん<emoji=heart04>　じゃあもう、腰動かすの止めちゃおうかな～？」
line = "「ふ～ん<emoji=heart04>　じゃあもう、腰動かすの止めちゃおうかな～？」"

[[dialogue]]
speaker = "紅明"
# 「ふうぅ……<emoji=heart04>　ほら、おま○こハグもおしまい～☆　せっかく気持ちいいところだったのにな～♪　残念<emoji=heart04>」
line = "「ふうぅ……<emoji=heart04>　ほら、おま○こハグもおしまい～☆　せっかく気持ちいいところだったのにな～♪　残念<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「――ん？　なにかな、ダーリン♪　恥ずかしがらずに、言って<emoji=heart04>」
line = "「――ん？　なにかな、ダーリン♪　恥ずかしがらずに、言って<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺は手で顔を隠すのを止めて、彼女に、動いてイカせて欲しいとおねだりする――
line = "俺は手で顔を隠すのを止めて、彼女に、動いてイカせて欲しいとおねだりする――"

[[dialogue]]
speaker = "紅明"
# 「はああぁっ……<emoji=heart04><emoji=heart04>　ダーリンのおねだり、かわいくて、エッチすぎて、おま○こキュンキュンしちゃう……！　ふうぅっ……<emoji=heart04>」
line = "「はああぁっ……<emoji=heart04><emoji=heart04>　ダーリンのおねだり、かわいくて、エッチすぎて、おま○こキュンキュンしちゃう……！　ふうぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「意地悪してごめんね、ダーリン。でも正直、めっちゃ興奮するっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　だから――」
line = "「意地悪してごめんね、ダーリン。でも正直、めっちゃ興奮するっ……<emoji=heart04>　はあぁっ……<emoji=heart04>　だから――」"

[[dialogue]]
speaker = "紅明"
# 「今から激しく全力ピストンしちゃうけど、許してね？　いくよっ<emoji=heart04>」
line = "「今から激しく全力ピストンしちゃうけど、許してね？　いくよっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「せ～のっ<emoji=heart04>　ふんっ――<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「せ～のっ<emoji=heart04>　ふんっ――<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>　どちゅどちゅ、じゅっぷじゅっぷ<emoji=heart04>　ぬちゅぬちゅ、ずっぽずっぽ<emoji=heart04>」
line = "「ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>　どちゅどちゅ、じゅっぷじゅっぷ<emoji=heart04>　ぬちゅぬちゅ、ずっぽずっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「おま○こパンッパン<emoji=heart04>　パンッパン<emoji=heart04>　ずぽずぽ、ぬっぷぬっぷ<emoji=heart04>　どちゅどちゅ、じゅっぽじゅっぽ<emoji=heart04>」
line = "「おま○こパンッパン<emoji=heart04>　パンッパン<emoji=heart04>　ずぽずぽ、ぬっぷぬっぷ<emoji=heart04>　どちゅどちゅ、じゅっぽじゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「はああぁっ<emoji=heart04>　ダーリンの気持ちよくて泣きそうな顔、かわいい<emoji=heart04>　好きっ<emoji=heart04>　もっと、もっと気持ちよくなって<emoji=heart04>　ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>」
line = "「はああぁっ<emoji=heart04>　ダーリンの気持ちよくて泣きそうな顔、かわいい<emoji=heart04>　好きっ<emoji=heart04>　もっと、もっと気持ちよくなって<emoji=heart04>　ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「全力おま○こハグもしちゃうよ～<emoji=heart04>　いくよ？　せ～のっ――ぎゅうぅぅ～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「全力おま○こハグもしちゃうよ～<emoji=heart04>　いくよ？　せ～のっ――ぎゅうぅぅ～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 次の瞬間、ペニスが、まさに搾精というべきバキュームの快感に襲われる……！
line = "次の瞬間、ペニスが、まさに搾精というべきバキュームの快感に襲われる……！"

[[dialogue]]
speaker = "紅明"
# 「ふんっふんっふんっ<emoji=heart04>　おま○こパンッパンッパンッ<emoji=heart04>　ぎゅっぷぎゅっぷ、じゅっぽじゅっぽ<emoji=heart04>　どちゅどちゅ、ぎゅっぽぎゅっぽ<emoji=heart04>」
line = "「ふんっふんっふんっ<emoji=heart04>　おま○こパンッパンッパンッ<emoji=heart04>　ぎゅっぷぎゅっぷ、じゅっぽじゅっぽ<emoji=heart04>　どちゅどちゅ、ぎゅっぽぎゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んん゛っ<emoji=heart04>　アタシもおち○ぽ気持ちいいっ<emoji=heart04>　ハグでめっちゃ擦れるぅっ<emoji=heart04>　ふんっふんっ<emoji=heart04>　ぬちゅぬちゅ、ずっぽずっぽ<emoji=heart04>　ぎゅぷぎゅぷ、じゅっぽじゅっぽ<emoji=heart04>」
line = "「んん゛っ<emoji=heart04>　アタシもおち○ぽ気持ちいいっ<emoji=heart04>　ハグでめっちゃ擦れるぅっ<emoji=heart04>　ふんっふんっ<emoji=heart04>　ぬちゅぬちゅ、ずっぽずっぽ<emoji=heart04>　ぎゅぷぎゅぷ、じゅっぽじゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あ゛～っ<emoji=heart04>　ダーリンおち○ぽ効くぅっ<emoji=heart04>　大きくて逞しくて、気持ちいいのぉ<emoji=heart04>　あっ<emoji=heart04>　あんっ<emoji=heart04>　はあぁっ<emoji=heart04>　ふああぁっ<emoji=heart04>」
line = "「あ゛～っ<emoji=heart04>　ダーリンおち○ぽ効くぅっ<emoji=heart04>　大きくて逞しくて、気持ちいいのぉ<emoji=heart04>　あっ<emoji=heart04>　あんっ<emoji=heart04>　はあぁっ<emoji=heart04>　ふああぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んっ<emoji=heart04>　きてる<emoji=heart04>　アタシ、もうイキそうっ……！」
line = "「んっ<emoji=heart04>　きてる<emoji=heart04>　アタシ、もうイキそうっ……！」"

[[dialogue]]
speaker = "紅明"
# 「――ダーリンもイキそうなの？　うん、一緒にいこっ<emoji=heart04>　はあぁっ<emoji=heart04>　ダーリンのおち○ぽミルク、いっぱい飲ませてっ<emoji=heart04>」
line = "「――ダーリンもイキそうなの？　うん、一緒にいこっ<emoji=heart04>　はあぁっ<emoji=heart04>　ダーリンのおち○ぽミルク、いっぱい飲ませてっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>　ぬちゅぬちゅ、ずっぽずっぽ<emoji=heart04>」
line = "「ふんっふんっ<emoji=heart04>　ふんっふんっ<emoji=heart04>　ぬちゅぬちゅ、ずっぽずっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「おま○こパンッパンッ<emoji=heart04>　パンッパンッ<emoji=heart04>　ぎゅぷぎゅぷ、じゅっぽじゅっぽ<emoji=heart04>」
line = "「おま○こパンッパンッ<emoji=heart04>　パンッパンッ<emoji=heart04>　ぎゅぷぎゅぷ、じゅっぽじゅっぽ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ふうぅっ<emoji=heart04>　きた、きたきた<emoji=heart04>　アクメ昇ってきたっ<emoji=heart04>」
line = "「ふうぅっ<emoji=heart04>　きた、きたきた<emoji=heart04>　アクメ昇ってきたっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ダーリンもきてっ<emoji=heart04>　おち○ぽミルク、アタシの中にいっぱい出してぇっ<emoji=heart04>」
line = "「ダーリンもきてっ<emoji=heart04>　おち○ぽミルク、アタシの中にいっぱい出してぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「あ～っ<emoji=heart04>　イクっ<emoji=heart04><emoji=heart04>　イクイクイクイグ――っ<emoji=heart04><emoji=heart04>」
line = "「あ～っ<emoji=heart04>　イクっ<emoji=heart04><emoji=heart04>　イクイクイクイグ――っ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「おま○こイックぅぅぅーーーーーーーーーっ<emoji=heart04><emoji=heart04><emoji=heart04>　ふあああぁぁぁ～～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「おま○こイックぅぅぅーーーーーーーーーっ<emoji=heart04><emoji=heart04><emoji=heart04>　ふあああぁぁぁ～～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んああぁぁ～～っ<emoji=heart04><emoji=heart04>　ダーリンの熱いおち○ぽミルク、子宮にいっぱいきてるっしょぉ～<emoji=heart04>」
line = "「んああぁぁ～～っ<emoji=heart04><emoji=heart04>　ダーリンの熱いおち○ぽミルク、子宮にいっぱいきてるっしょぉ～<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「はああぁっ……<emoji=heart04>　すごっ……<emoji=heart04>　射精、まだどぴゅどぴゅって止まらないぃ……<emoji=heart04>」
line = "「はああぁっ……<emoji=heart04>　すごっ……<emoji=heart04>　射精、まだどぴゅどぴゅって止まらないぃ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ふうぅ……<emoji=heart04>　ダーリンの射精、いつも長くて、種付けって感じで素敵ぃ……<emoji=heart04>」
line = "「ふうぅ……<emoji=heart04>　ダーリンの射精、いつも長くて、種付けって感じで素敵ぃ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「んっ……<emoji=heart04>　止まった……<emoji=heart04>　はあぁ……<emoji=heart04>」
line = "「んっ……<emoji=heart04>　止まった……<emoji=heart04>　はあぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ふぅ……<emoji=heart04>　はぁ……<emoji=heart04>　すっごく気持ちよかったぁ……<emoji=heart04>」
line = "「ふぅ……<emoji=heart04>　はぁ……<emoji=heart04>　すっごく気持ちよかったぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「アタシ、ダーリンを甘やかしちゃうエッチも好きだけど、Ｓっぽく責めちゃうのも、ちょっと好きかも……♪」
line = "「アタシ、ダーリンを甘やかしちゃうエッチも好きだけど、Ｓっぽく責めちゃうのも、ちょっと好きかも……♪」"

[[dialogue]]
speaker = "紅明"
# 「おっぱいも興奮して、いっぱい母乳出ちゃったし……<emoji=heart04>」
line = "「おっぱいも興奮して、いっぱい母乳出ちゃったし……<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「――ダーリンもすごく気持ちよかった？　えへへ<emoji=heart04>　なら嬉しい……♪」
line = "「――ダーリンもすごく気持ちよかった？　えへへ<emoji=heart04>　なら嬉しい……♪」"

[[dialogue]]
speaker = "紅明"
# 「それで、ダーリン……んっ<emoji=heart04>」
line = "「それで、ダーリン……んっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ふと、紅明はわざとらしく、抜けたペニスにスマタをし始める。
line = "ふと、紅明はわざとらしく、抜けたペニスにスマタをし始める。"

[[dialogue]]
speaker = "紅明"
# 「この後はどうしよっか……？　もう寝ちゃう？　それとも――」
line = "「この後はどうしよっか……？　もう寝ちゃう？　それとも――」"

[[dialogue]]
speaker = "紅明"
# 「朝までエッチコース、しちゃう？」
line = "「朝までエッチコース、しちゃう？」"

[[dialogue]]
speaker = "unk"
# 期待している笑顔を前に、男として応えないわけにはいかない。俺はガバッと起き上がると――
line = "期待している笑顔を前に、男として応えないわけにはいかない。俺はガバッと起き上がると――"

[[dialogue]]
speaker = "紅明"
# 「あっ♪　あんっ……<emoji=heart04>　ダーリン、そんな強くおっぱい飲んじゃ、乳首感じちゃう……<emoji=heart04>　ふああぁっ――<emoji=heart04>」
line = "「あっ♪　あんっ……<emoji=heart04>　ダーリン、そんな強くおっぱい飲んじゃ、乳首感じちゃう……<emoji=heart04>　ふああぁっ――<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 言いつつも嬉しそうな彼女の母乳を飲んで回復した後、再びそのおっぱいを淫らに揺らすことになるのだった――
line = "言いつつも嬉しそうな彼女の母乳を飲んで回復した後、再びそのおっぱいを淫らに揺らすことになるのだった――"
