[[dialogue]]
speaker = "unk"
# 第３話,戸惑うキサナ,P
line = "第３話,戸惑うキサナ,P"

[[dialogue]]
speaker = "キサナ"
# 「もしあの家を追い出されたらここで寝りゃいい。ここの芝生は柔らかくてかなり寝心地が──……って」
line = "「もしあの家を追い出されたらここで寝りゃいい。ここの芝生は柔らかくてかなり寝心地が──……って」"

[[dialogue]]
speaker = "キサナ"
# 「魔王じゃねえか。ガキども引き連れて何やってんだ？　まさかコイツみてえなヤツらを集め回ってんじゃねえだろうな？」
line = "「魔王じゃねえか。ガキども引き連れて何やってんだ？　まさかコイツみてえなヤツらを集め回ってんじゃねえだろうな？」"

[[dialogue]]
speaker = "unk"
# みんな施設の子たちだよ
line = "みんな施設の子たちだよ"

[[dialogue]]
speaker = "キサナ"
# 「施設って例の？　まさかオマエ……アタシを説得するために施設を見に行ったってのか？」
line = "「施設って例の？　まさかオマエ……アタシを説得するために施設を見に行ったってのか？」"

[[dialogue]]
speaker = "キサナ"
# 「チッ、んなことしてもアタシの意志は変わんねえよ。そーいうとこはな。外面だけはいつもよくしてんだ」
line = "「チッ、んなことしてもアタシの意志は変わんねえよ。そーいうとこはな。外面だけはいつもよくしてんだ」"

[[dialogue]]
speaker = "キサナ"
# 「どうせコイツらも裏で施設のオトナに殴られたりして──ひぃあんっ！？　ちょっ、ガキども人の尻尾触んな……！！」
line = "「どうせコイツらも裏で施設のオトナに殴られたりして──ひぃあんっ！？　ちょっ、ガキども人の尻尾触んな……！！」"

[[dialogue]]
speaker = "キサナ"
# 「あっ、コラ、ひぃあっ、引っ張んなっ……！　耳は、くははっ、やめっ、くすぐったっ……！」
line = "「あっ、コラ、ひぃあっ、引っ張んなっ……！　耳は、くははっ、やめっ、くすぐったっ……！」"

[[dialogue]]
speaker = "キサナ"
# 「やめ、いい加減にしねえと、んにゃあああっっ、ぶっ殺すぞっ……！」
line = "「やめ、いい加減にしねえと、んにゃあああっっ、ぶっ殺すぞっ……！」"

[[dialogue]]
speaker = "unk"
# 元気いっぱいで楽しそうだろ？
line = "元気いっぱいで楽しそうだろ？"

[[dialogue]]
speaker = "キサナ"
# 「はぁーっ、はぁーっ、あぁ？　確かに……まぁ。殴られたりしてるようには見えねえがよ……」
line = "「はぁーっ、はぁーっ、あぁ？　確かに……まぁ。殴られたりしてるようには見えねえがよ……」"

[[dialogue]]
speaker = "キサナ"
# 「ん？　なんだガキ？　コイツらと一緒に遊びたいってか？　チッ、勝手にすりゃいいじゃねえか。いちいちアタシに聞くなよ」
line = "「ん？　なんだガキ？　コイツらと一緒に遊びたいってか？　チッ、勝手にすりゃいいじゃねえか。いちいちアタシに聞くなよ」"

[[dialogue]]
speaker = "キサナ"
# 「アタシも一緒に？　んなもん嫌に決まって──ふにゃっ！？　だからことあるごとに尻尾を引っ張んなっ！　遊べばいいんだろ、遊べばっ……！」
line = "「アタシも一緒に？　んなもん嫌に決まって──ふにゃっ！？　だからことあるごとに尻尾を引っ張んなっ！　遊べばいいんだろ、遊べばっ……！」"

[[dialogue]]
speaker = "キサナ"
# 「そっちのお兄ちゃんもって……おいおい。バカ言ってんじゃねえよ。アイツとアタシは敵同士っつったろ？」
line = "「そっちのお兄ちゃんもって……おいおい。バカ言ってんじゃねえよ。アイツとアタシは敵同士っつったろ？」"

[[dialogue]]
speaker = "キサナ"
# 「敵同士で仲良くお遊びなんかするわきゃねえだろ。アタシもアイツもそこまで頭ん中お花畑じゃねーっつの」
line = "「敵同士で仲良くお遊びなんかするわきゃねえだろ。アタシもアイツもそこまで頭ん中お花畑じゃねーっつの」"

[[dialogue]]
speaker = "unk"
# まずはかくれんぼからだ！
line = "まずはかくれんぼからだ！"

[[dialogue]]
speaker = "キサナ"
# 「遊ぶ気満々かよ！？　少しは緊張感ってもんを持てやテメエ！？」
line = "「遊ぶ気満々かよ！？　少しは緊張感ってもんを持てやテメエ！？」"

[[dialogue]]
speaker = "キサナ"
# 「つか、かくれんぼだぁ？　上等だよ。いい加減、オマエらから逃げ隠れするのにも飽き飽きしてきた頃だ」
line = "「つか、かくれんぼだぁ？　上等だよ。いい加減、オマエらから逃げ隠れするのにも飽き飽きしてきた頃だ」"

[[dialogue]]
speaker = "キサナ"
# 「今度はアタシが徹底的にテメエを追い回してやるよ！　隠れられるもんなら隠れてみやがれ！」
line = "「今度はアタシが徹底的にテメエを追い回してやるよ！　隠れられるもんなら隠れてみやがれ！」"

[[dialogue]]
speaker = "キサナ"
# 「はっ、口ほどにもねえな。魔王もガキどももまとめて捕まえてやったぜ」
line = "「はっ、口ほどにもねえな。魔王もガキどももまとめて捕まえてやったぜ」"

[[dialogue]]
speaker = "キサナ"
# 「大体アタシから逃げ隠れしよーってんのが間違いなんだ。足音でわかんだ、足音で」
line = "「大体アタシから逃げ隠れしよーってんのが間違いなんだ。足音でわかんだ、足音で」"

[[dialogue]]
speaker = "キサナ"
# 「この耳は飾りじゃねえ。テメエら星騎士の足音を聞きゃあピンとくるからな。逃げるのも追うのも自由自在だ。目や鼻も利くしよ」
line = "「この耳は飾りじゃねえ。テメエら星騎士の足音を聞きゃあピンとくるからな。逃げるのも追うのも自由自在だ。目や鼻も利くしよ」"

[[dialogue]]
speaker = "キサナ"
# 「ガキといる時は油断しちまってたが、気を張ってりゃ足音と匂いでわかるから、テメエらに見つからないで済む──」
line = "「ガキといる時は油断しちまってたが、気を張ってりゃ足音と匂いでわかるから、テメエらに見つからないで済む──」"

[[dialogue]]
speaker = "キサナ"
# 「って、ヤベっ。うっかりばらしちまった！？」
line = "「って、ヤベっ。うっかりばらしちまった！？」"

[[dialogue]]
speaker = "キサナ"
# 「今のはなしだ、なし！　忘れねえとぶっ殺すぞ！」
line = "「今のはなしだ、なし！　忘れねえとぶっ殺すぞ！」"

[[dialogue]]
speaker = "unk"
# わかった忘れる
line = "わかった忘れる"

[[dialogue]]
speaker = "キサナ"
# 「いや、アホか！？　貴重なアタシの情報だろ！？　そこは忘れんなよ！？」
line = "「いや、アホか！？　貴重なアタシの情報だろ！？　そこは忘れんなよ！？」"

[[dialogue]]
speaker = "キサナ"
# 「いったいどんだけ頭沸いてんだよ……。お尋ね者が目の前にいるってのにお仲間に連絡取ってる様子もねえしよ」
line = "「いったいどんだけ頭沸いてんだよ……。お尋ね者が目の前にいるってのにお仲間に連絡取ってる様子もねえしよ」"

[[dialogue]]
speaker = "キサナ"
# 「ガキどもと遊んでるからって一時休戦のつもりか？　ま……別にそっちがその気ならいいけどよ。アタシも上からの指示がなきゃケンカふっかけるつもりもねえし」
line = "「ガキどもと遊んでるからって一時休戦のつもりか？　ま……別にそっちがその気ならいいけどよ。アタシも上からの指示がなきゃケンカふっかけるつもりもねえし」"

[[dialogue]]
speaker = "キサナ"
# 「だけど何が悲しくて魔王と肩を並べてガキどもと遊ばなきゃなんねーんだ……。アタシもどーかしてたぜ……」
line = "「だけど何が悲しくて魔王と肩を並べてガキどもと遊ばなきゃなんねーんだ……。アタシもどーかしてたぜ……」"

[[dialogue]]
speaker = "キサナ"
# 「おいガキ。そろそろ帰るぞ。……あぁ？　まだ遊びたいだぁ？　チッ……んだよ楽しそうにしやがって」
line = "「おいガキ。そろそろ帰るぞ。……あぁ？　まだ遊びたいだぁ？　チッ……んだよ楽しそうにしやがって」"

[[dialogue]]
speaker = "キサナ"
# 「んな顔、今までしてなかったじゃねえか……。んな能天気な顔してたら生き残れねえっつーの……」
line = "「んな顔、今までしてなかったじゃねえか……。んな能天気な顔してたら生き残れねえっつーの……」"

[[dialogue]]
speaker = "キサナ"
# 「施設のガキどももアホ面晒して駆け回ってやがるし……。んな良いトコなのかよ、その保護施設ってのは……」
line = "「施設のガキどももアホ面晒して駆け回ってやがるし……。んな良いトコなのかよ、その保護施設ってのは……」"

[[dialogue]]
speaker = "unk"
# 少しは印象が変わった？
line = "少しは印象が変わった？"

[[dialogue]]
speaker = "キサナ"
# 「っ！　うるせえなっ。テメエは黙ってろ。どー思うかはアタシの勝手だろっ！」
line = "「っ！　うるせえなっ。テメエは黙ってろ。どー思うかはアタシの勝手だろっ！」"

[[dialogue]]
speaker = "キサナ"
# 「テメエのことはテメエで決める。他人の言うことなんざ信用ならねえ」
line = "「テメエのことはテメエで決める。他人の言うことなんざ信用ならねえ」"

[[dialogue]]
speaker = "キサナ"
# 「アタシはそういう世界で生きてきたんだ。誰かに守ってもらおうなんて甘い考えしてたらあっという間にやられちまう世界でな」
line = "「アタシはそういう世界で生きてきたんだ。誰かに守ってもらおうなんて甘い考えしてたらあっという間にやられちまう世界でな」"

[[dialogue]]
speaker = "キサナ"
# 「だからオマエがどれだけ理屈並べても──……」
line = "「だからオマエがどれだけ理屈並べても──……」"

[[dialogue]]
speaker = "キサナ"
# 「いや……ここはアタシの住んでた場所じゃねえんだよな。あのガキを縛り付けてんのはアタシの方……か……」
line = "「いや……ここはアタシの住んでた場所じゃねえんだよな。あのガキを縛り付けてんのはアタシの方……か……」"

[[dialogue]]
speaker = "キサナ"
# 「……なんでもねえよ。なんでもねえっつってんだろ！」
line = "「……なんでもねえよ。なんでもねえっつってんだろ！」"

[[dialogue]]
speaker = "キサナ"
# 「おい、ガキ。やっぱ今日は帰るぞ。そろそろ行かねえと弁当にもありつけねえ」
line = "「おい、ガキ。やっぱ今日は帰るぞ。そろそろ行かねえと弁当にもありつけねえ」"

[[dialogue]]
speaker = "キサナ"
# 「……あ？　今度は妙に素直じゃねえか。おい、テメエ……まさかアタシの顔色窺ってんじゃねえだろうな？」
line = "「……あ？　今度は妙に素直じゃねえか。おい、テメエ……まさかアタシの顔色窺ってんじゃねえだろうな？」"

[[dialogue]]
speaker = "キサナ"
# 「アタシはな、そういう誰かに媚びた顔は嫌いなんだよ」
line = "「アタシはな、そういう誰かに媚びた顔は嫌いなんだよ」"

[[dialogue]]
speaker = "キサナ"
# 「テメエのことはテメエで決めろっていつも言ってんだろ。遊びてえなら遊びてえって言え」
line = "「テメエのことはテメエで決めろっていつも言ってんだろ。遊びてえなら遊びてえって言え」"

[[dialogue]]
speaker = "キサナ"
# 「そうだ。それでいいんだ、バカ野郎が。はいはい、アタシも一緒にな。わーったから引っ張んなって」
line = "「そうだ。それでいいんだ、バカ野郎が。はいはい、アタシも一緒にな。わーったから引っ張んなって」"

[[dialogue]]
speaker = "キサナ"
# 「……んだよ魔王？　ニヤニヤ気持ち悪い笑顔浮かべやがってムカつくぜ」
line = "「……んだよ魔王？　ニヤニヤ気持ち悪い笑顔浮かべやがってムカつくぜ」"

[[dialogue]]
speaker = "キサナ"
# 「っしゃあガキども。今度はボール遊びだ。あの上から目線の星騎士さまにボールぶつけて、あの顔思い切り歪ませてやっぞ！」
line = "「っしゃあガキども。今度はボール遊びだ。あの上から目線の星騎士さまにボールぶつけて、あの顔思い切り歪ませてやっぞ！」"
