[[dialogue]]
speaker = "unk"
# 第３話,トントロをいっぱいにするのです！,P
line = "第３話,トントロをいっぱいにするのです！,P"

[[dialogue]]
speaker = "ルリエル"
# 「会長さんっ。ルリエル、貯金をしようと思います！」
line = "「会長さんっ。ルリエル、貯金をしようと思います！」"

[[dialogue]]
speaker = "unk"
# 何か欲しいものが？
line = "何か欲しいものが？"

[[dialogue]]
speaker = "ルリエル"
# 「いえ！　ルリエル、今までお小遣いはもらったそばからどんどん使っちゃっていました」
line = "「いえ！　ルリエル、今までお小遣いはもらったそばからどんどん使っちゃっていました」"

[[dialogue]]
speaker = "ルリエル"
# 「でも、無駄遣いはいけないことです。故郷のじっちゃんばっちゃんにも怒られちゃいます。そこで……！」
line = "「でも、無駄遣いはいけないことです。故郷のじっちゃんばっちゃんにも怒られちゃいます。そこで……！」"

[[dialogue]]
speaker = "ルリエル"
# 「トントロにしまっちゃえばいいことに気づいたのです～♪　これならどんどんお金が貯まっていくはずなのですよ！」
line = "「トントロにしまっちゃえばいいことに気づいたのです～♪　これならどんどんお金が貯まっていくはずなのですよ！」"

[[dialogue]]
speaker = "ルリエル"
# 「それで、トントロがいっぱいになったら。じっちゃんたちに何かお礼の贈り物でも……なんて思ってるのです♪」
line = "「それで、トントロがいっぱいになったら。じっちゃんたちに何かお礼の贈り物でも……なんて思ってるのです♪」"

[[dialogue]]
speaker = "unk"
# 名案だね、がんばれ！
line = "名案だね、がんばれ！"

[[dialogue]]
speaker = "ルリエル"
# 「はいです！　ではさっそく、お財布のお金をいくらか、貯金して──」
line = "「はいです！　ではさっそく、お財布のお金をいくらか、貯金して──」"

[[dialogue]]
speaker = "セーラ"
# 「あ。ルリちーに会長さんじゃん。やっほー」
line = "「あ。ルリちーに会長さんじゃん。やっほー」"

[[dialogue]]
speaker = "ルリエル"
# 「あっ、セーラ先輩。奇遇なのです～。お買い物ですか？」
line = "「あっ、セーラ先輩。奇遇なのです～。お買い物ですか？」"

[[dialogue]]
speaker = "セーラ"
# 「そだよん。てゆーか良いタイミングで会えたね！　ルリちーにぜひとも教えたいスイーツショップがあるんだ～」
line = "「そだよん。てゆーか良いタイミングで会えたね！　ルリちーにぜひとも教えたいスイーツショップがあるんだ～」"

[[dialogue]]
speaker = "ルリエル"
# 「スウィーツっ……！？」
line = "「スウィーツっ……！？」"

[[dialogue]]
speaker = "セーラ"
# 「そそ。つい最近オープンしたばっかりの店でね。限定のいちごショートがちょー最高なんだよね！」
line = "「そそ。つい最近オープンしたばっかりの店でね。限定のいちごショートがちょー最高なんだよね！」"

[[dialogue]]
speaker = "ルリエル"
# 「新しいお店！　限定！　いちご！　は、はうう♪　気になります、ルリエルも食べたいのですっ！」
line = "「新しいお店！　限定！　いちご！　は、はうう♪　気になります、ルリエルも食べたいのですっ！」"

[[dialogue]]
speaker = "unk"
# あ、あれ、貯金は……？
line = "あ、あれ、貯金は……？"

[[dialogue]]
speaker = "ルリエル"
# 「行きましょう、セーラ先輩っ！」
line = "「行きましょう、セーラ先輩っ！」"

[[dialogue]]
speaker = "セーラ"
# 「よっしゃー、レッツゴーだね～♪　会長さんもおいでよ！」
line = "「よっしゃー、レッツゴーだね～♪　会長さんもおいでよ！」"

[[dialogue]]
speaker = "ルリエル"
# 「お腹ぺこぺこなのです～♪　いっぱい買っちゃうのですよー♪」
line = "「お腹ぺこぺこなのです～♪　いっぱい買っちゃうのですよー♪」"

[[dialogue]]
speaker = "ルリエル"
# 「や、やってしまいました……くすん……貯金しようとした矢先に無駄遣いを……もぐもぐ……でもケーキはとってもおいしいのです……」
line = "「や、やってしまいました……くすん……貯金しようとした矢先に無駄遣いを……もぐもぐ……でもケーキはとってもおいしいのです……」"

[[dialogue]]
speaker = "ルリエル"
# 「で、でも！　ここから挽回なのですよ！　今度こそお財布のお金を、無駄遣いする前にトントロへ……！」
line = "「で、でも！　ここから挽回なのですよ！　今度こそお財布のお金を、無駄遣いする前にトントロへ……！」"

[[dialogue]]
speaker = "ソフィア"
# 「……あ。会長さんに、ルリ。こんにちは」
line = "「……あ。会長さんに、ルリ。こんにちは」"

[[dialogue]]
speaker = "ルリエル"
# 「ソフィアもお散歩ですか……って、くんくん。何だか甘い匂いがするのですっ」
line = "「ソフィアもお散歩ですか……って、くんくん。何だか甘い匂いがするのですっ」"

[[dialogue]]
speaker = "ソフィア"
# 「い、いきなり嗅がないでください！　えっと、今ちょうどパンケーキの食べ歩きをしてたんです……ルリも一緒に行きますか？」
line = "「い、いきなり嗅がないでください！　えっと、今ちょうどパンケーキの食べ歩きをしてたんです……ルリも一緒に行きますか？」"

[[dialogue]]
speaker = "ルリエル"
# 「パンケーキ……！　ルリエル、パンケーキには目がないのです～♪」
line = "「パンケーキ……！　ルリエル、パンケーキには目がないのです～♪」"

[[dialogue]]
speaker = "unk"
# ちょっとルリエル！？
line = "ちょっとルリエル！？"

[[dialogue]]
speaker = "ルリエル"
# 「ソフィアのおすすめはいつもとっても美味しいですから楽しみなのですっ♪」
line = "「ソフィアのおすすめはいつもとっても美味しいですから楽しみなのですっ♪」"

[[dialogue]]
speaker = "ソフィア"
# 「期待していいよ。あそこはひと味違うから。あ、会長さんも一緒にどうですか？」
line = "「期待していいよ。あそこはひと味違うから。あ、会長さんも一緒にどうですか？」"

[[dialogue]]
speaker = "ルリエル"
# 「ルリエルはダメダメ天使なのです……誘惑に抗うことができません……もぐもぐ……でもパンケーキもたまらなくおいしいのです……」
line = "「ルリエルはダメダメ天使なのです……誘惑に抗うことができません……もぐもぐ……でもパンケーキもたまらなくおいしいのです……」"

[[dialogue]]
speaker = "ルリエル"
# 「貯金というのは、こうも難しいものなのですね……ロロットさんはきっと鋼の意思を持った天使様なのですよ……」
line = "「貯金というのは、こうも難しいものなのですね……ロロットさんはきっと鋼の意思を持った天使様なのですよ……」"

[[dialogue]]
speaker = "フィオナ"
# 「ルリエル、ここにいたの。ちょうど良かった、良かったら一緒にお茶でも──」
line = "「ルリエル、ここにいたの。ちょうど良かった、良かったら一緒にお茶でも──」"

[[dialogue]]
speaker = "ルリエル"
# 「ふ、ふぇえええんっ！　フィオナ会長、ごめんなさい～っ！　欲に弱いルリエルを許してくださいなのです～っ！」
line = "「ふ、ふぇえええんっ！　フィオナ会長、ごめんなさい～っ！　欲に弱いルリエルを許してくださいなのです～っ！」"

[[dialogue]]
speaker = "フィオナ"
# 「え……え～っと。いったい何が……？」
line = "「え……え～っと。いったい何が……？」"

[[dialogue]]
speaker = "フィオナ"
# 「ルリエルが喜びそうなカフェを見つけたから、一緒にどうかと思っただけなんだけど……」
line = "「ルリエルが喜びそうなカフェを見つけたから、一緒にどうかと思っただけなんだけど……」"

[[dialogue]]
speaker = "unk"
# そっとしておいてあげて
line = "そっとしておいてあげて"

[[dialogue]]
speaker = "フィオナ"
# 「は、はい。緋宮会長がそうおっしゃるのでしたら……」
line = "「は、はい。緋宮会長がそうおっしゃるのでしたら……」"

[[dialogue]]
speaker = "unk"
# 友達がとても多く、また欲に弱いルリエルが貯金箱の中身をいっぱいにできるのは、まだまだ先のことになりそうなのだった。
line = "友達がとても多く、また欲に弱いルリエルが貯金箱の中身をいっぱいにできるのは、まだまだ先のことになりそうなのだった。"

[[dialogue]]
speaker = "ルリエル"
# 「うわーんっ……！　人間界は、誘惑が多すぎますよう～っ！」
line = "「うわーんっ……！　人間界は、誘惑が多すぎますよう～っ！」"
