[[dialogue]]
speaker = "unk"
# 第２話,カレーライスとカツ丼,P
line = "第２話,カレーライスとカツ丼,P"

[[dialogue]]
speaker = "unk"
# たまにはカフェでランチを──と訪れたそこには見知った先客がいた。
line = "たまにはカフェでランチを──と訪れたそこには見知った先客がいた。"

[[dialogue]]
speaker = "フラン"
# 「おっ、会長じゃねえか。今日はひとり飯か？」
line = "「おっ、会長じゃねえか。今日はひとり飯か？」"

[[dialogue]]
speaker = "グロリア"
# 「あの、よろしければ、ご一緒にいかがです？」
line = "「あの、よろしければ、ご一緒にいかがです？」"

[[dialogue]]
speaker = "unk"
# じゃあお言葉に甘えて
line = "じゃあお言葉に甘えて"

[[dialogue]]
speaker = "グロリア"
# 「女神様に感謝して……いただきます」
line = "「女神様に感謝して……いただきます」"

[[dialogue]]
speaker = "フラン"
# 「いただきまーす！　おっ、会長さんのはなんだ？」
line = "「いただきまーす！　おっ、会長さんのはなんだ？」"

[[dialogue]]
speaker = "unk"
# たっぷりキノコの和風パスタ
line = "たっぷりキノコの和風パスタ"

[[dialogue]]
speaker = "フラン"
# 「おしゃれなもん食ってんなあ。そんなんでパワーがみなぎるのかよ」
line = "「おしゃれなもん食ってんなあ。そんなんでパワーがみなぎるのかよ」"

[[dialogue]]
speaker = "グロリア"
# 「フランさんは今日もカツ丼なんですね」
line = "「フランさんは今日もカツ丼なんですね」"

[[dialogue]]
speaker = "フラン"
# 「おうよ！　しかも、今日はカツ２倍の特盛だぜ！　放課後に部活の応援が３件入ってるからな！」
line = "「おうよ！　しかも、今日はカツ２倍の特盛だぜ！　放課後に部活の応援が３件入ってるからな！」"

[[dialogue]]
speaker = "フラン"
# 「……で、グロリアもいつものなのな」
line = "「……で、グロリアもいつものなのな」"

[[dialogue]]
speaker = "グロリア"
# 「はい、お子様ハンバーグオムカレーです」
line = "「はい、お子様ハンバーグオムカレーです」"

[[dialogue]]
speaker = "フラン"
# 「電車の形をしたプレートに……ハンバーグとオムレツとカレーが乗ってて、ライスにはご丁寧に国旗まで刺さってらぁ……」
line = "「電車の形をしたプレートに……ハンバーグとオムレツとカレーが乗ってて、ライスにはご丁寧に国旗まで刺さってらぁ……」"

[[dialogue]]
speaker = "フラン"
# 「なんで学生用のカフェテリアにお子様ランチがあるんだ……？」
line = "「なんで学生用のカフェテリアにお子様ランチがあるんだ……？」"

[[dialogue]]
speaker = "グロリア"
# 「私はフランさんみたいにたくさんは食べられませんから、お子様サイズで十分なんです」
line = "「私はフランさんみたいにたくさんは食べられませんから、お子様サイズで十分なんです」"

[[dialogue]]
speaker = "グロリア"
# 「でも、すごく美味しいんですよ。こんなに美味しい食べ物は他にありません。あ～……ん～～っ<emoji=heart04>　美味しいです……<emoji=heart04>」
line = "「でも、すごく美味しいんですよ。こんなに美味しい食べ物は他にありません。あ～……ん～～っ<emoji=heart04>　美味しいです……<emoji=heart04>」"

[[dialogue]]
speaker = "フラン"
# 「いや、ここの飯は美味えよ？　美味えし、悪く言うつもりはねえけどよ……」
line = "「いや、ここの飯は美味えよ？　美味えし、悪く言うつもりはねえけどよ……」"

[[dialogue]]
speaker = "フラン"
# 「グロリアの食いものの好み、いくらなんでも子どもっぽすぎねえか？」
line = "「グロリアの食いものの好み、いくらなんでも子どもっぽすぎねえか？」"

[[dialogue]]
speaker = "グロリア"
# 「そうでしょうか？」
line = "「そうでしょうか？」"

[[dialogue]]
speaker = "unk"
# スパゲティといったら？
line = "スパゲティといったら？"

[[dialogue]]
speaker = "グロリア"
# 「ミートソースか、ナポリタンですね」
line = "「ミートソースか、ナポリタンですね」"

[[dialogue]]
speaker = "フラン"
# 「な？　いつもこんな調子で、子どもが食うものばっかりなんだよ。会長、なんか言ってやってくれ」
line = "「な？　いつもこんな調子で、子どもが食うものばっかりなんだよ。会長、なんか言ってやってくれ」"

[[dialogue]]
speaker = "グロリア"
# 「まあ！　フランさんだってカツ丼ばかり食べてるじゃないですか」
line = "「まあ！　フランさんだってカツ丼ばかり食べてるじゃないですか」"

[[dialogue]]
speaker = "フラン"
# 「カツ丼は美味えだろ！　ゲン担ぎだしな！」
line = "「カツ丼は美味えだろ！　ゲン担ぎだしな！」"

[[dialogue]]
speaker = "グロリア"
# 「カレーだって美味しいです！」
line = "「カレーだって美味しいです！」"

[[dialogue]]
speaker = "フラン"
# 「超甘口のカレーなんてカレーじゃねえし！」
line = "「超甘口のカレーなんてカレーじゃねえし！」"

[[dialogue]]
speaker = "グロリア"
# 「そんなことありません～～！」
line = "「そんなことありません～～！」"

[[dialogue]]
speaker = "グロリア"
# 「そもそも、私の舌がお子様だとしても、フランさんには特に迷惑もかからないのでは？」
line = "「そもそも、私の舌がお子様だとしても、フランさんには特に迷惑もかからないのでは？」"

[[dialogue]]
speaker = "フラン"
# 「迷惑はかかんねえけどさ……一生、お子様カレー以外の食べ物を知らなくてもよさそうな顔してんのが、ちょっと不安なんだよ」
line = "「迷惑はかかんねえけどさ……一生、お子様カレー以外の食べ物を知らなくてもよさそうな顔してんのが、ちょっと不安なんだよ」"

[[dialogue]]
speaker = "グロリア"
# 「不安、ですか？」
line = "「不安、ですか？」"

[[dialogue]]
speaker = "フラン"
# 「親御さんのしがらみも、ちっとは晴れたんだからよ。グロリアにはもっと広い世界を知ってほしいんだ」
line = "「親御さんのしがらみも、ちっとは晴れたんだからよ。グロリアにはもっと広い世界を知ってほしいんだ」"

[[dialogue]]
speaker = "フラン"
# 「世の中にはお子様カレー以外にも、美味いもんがたくさんあるってさ」
line = "「世の中にはお子様カレー以外にも、美味いもんがたくさんあるってさ」"

[[dialogue]]
speaker = "フラン"
# 「せっかくなら同じ美味い物を一緒に食べて、同じように笑いたいじゃねえか」
line = "「せっかくなら同じ美味い物を一緒に食べて、同じように笑いたいじゃねえか」"

[[dialogue]]
speaker = "フラン"
# 「友達ならさ、そういうの、分かち合いたくなるもんなんだよ」
line = "「友達ならさ、そういうの、分かち合いたくなるもんなんだよ」"

[[dialogue]]
speaker = "グロリア"
# 「友達……フランさん、ありがとうございます。あの……フランさんのカツ丼、一口いただいてもよろしいですか？」
line = "「友達……フランさん、ありがとうございます。あの……フランさんのカツ丼、一口いただいてもよろしいですか？」"

[[dialogue]]
speaker = "フラン"
# 「おお、食え食え！　一口と言わずに全部──いや半分までは食っていいぞ！」
line = "「おお、食え食え！　一口と言わずに全部──いや半分までは食っていいぞ！」"

[[dialogue]]
speaker = "グロリア"
# 「そこまで頂くつもりはありませんが……。では、いただきます……ぁむ」
line = "「そこまで頂くつもりはありませんが……。では、いただきます……ぁむ」"

[[dialogue]]
speaker = "フラン"
# 「……どうだ？」
line = "「……どうだ？」"

[[dialogue]]
speaker = "グロリア"
# 「っ！　美味しいです！　カツがサクサクで、卵もトロトロで、出汁の風味もふわぁって……！」
line = "「っ！　美味しいです！　カツがサクサクで、卵もトロトロで、出汁の風味もふわぁって……！」"

[[dialogue]]
speaker = "フラン"
# 「だろ？　オレもそのカレー、一口もらっていいか？」
line = "「だろ？　オレもそのカレー、一口もらっていいか？」"

[[dialogue]]
speaker = "グロリア"
# 「……はいっ！　もちろんです！」
line = "「……はいっ！　もちろんです！」"

[[dialogue]]
speaker = "フラン"
# 「んじゃ、いただきます……ぱく――んんっ！？」
line = "「んじゃ、いただきます……ぱく――んんっ！？」"

[[dialogue]]
speaker = "グロリア"
# 「ど、どうですか……？」
line = "「ど、どうですか……？」"

[[dialogue]]
speaker = "フラン"
# 「お子様味かと思ってたけど、このカレー、すげえ本格派じゃねえか……！　甘口なのにスパイスが効いてて、コクと旨味がすっげえ……！」
line = "「お子様味かと思ってたけど、このカレー、すげえ本格派じゃねえか……！　甘口なのにスパイスが効いてて、コクと旨味がすっげえ……！」"

[[dialogue]]
speaker = "グロリア"
# 「そうでしょう？　ここのカレーは絶品なんです！」
line = "「そうでしょう？　ここのカレーは絶品なんです！」"

[[dialogue]]
speaker = "フラン"
# 「味がわからねえみたいな言い方して悪かった！　このカレーとカツを合わせて、カツカレーにしても美味いかもな」
line = "「味がわからねえみたいな言い方して悪かった！　このカレーとカツを合わせて、カツカレーにしても美味いかもな」"

[[dialogue]]
speaker = "グロリア"
# 「私とフランさんの大好きな物の良いとこ取りですね、ふふ」
line = "「私とフランさんの大好きな物の良いとこ取りですね、ふふ」"

[[dialogue]]
speaker = "グロリア"
# 「会長さんのスパゲティも、一口いただいても？」
line = "「会長さんのスパゲティも、一口いただいても？」"

[[dialogue]]
speaker = "unk"
# ぜひ、どうぞ！
line = "ぜひ、どうぞ！"

[[dialogue]]
speaker = "unk"
# こうして今日、グロリアさんの好物が新たに２つ増えたのであった。
line = "こうして今日、グロリアさんの好物が新たに２つ増えたのであった。"
