[[dialogue]]
speaker = "unk"
# 第３話,本は友達,P
line = "第３話,本は友達,P"

[[dialogue]]
speaker = "モネ"
# 「ふぅ～……何とかなりました」
line = "「ふぅ～……何とかなりました」"

[[dialogue]]
speaker = "unk"
# お疲れ様
line = "お疲れ様"

[[dialogue]]
speaker = "モネ"
# 「いえいえ、モンスターを倒したのはほとんどは星徒会長ですから……私なんてまだまだですよぉ……」
line = "「いえいえ、モンスターを倒したのはほとんどは星徒会長ですから……私なんてまだまだですよぉ……」"

[[dialogue]]
speaker = "モネ"
# 「そんなことない？　モネもがんばってた？　えへへ……会長にそう言ってもらえると嬉しいです……」
line = "「そんなことない？　モネもがんばってた？　えへへ……会長にそう言ってもらえると嬉しいです……」"

[[dialogue]]
speaker = "モネ"
# 「会長に褒められちゃった。みんなのおかげだよ」
line = "「会長に褒められちゃった。みんなのおかげだよ」"

[[dialogue]]
speaker = "モネ"
# 「あ……みんなっていうのはこの子たちのことで。私、本の気持ちがわかるんです」
line = "「あ……みんなっていうのはこの子たちのことで。私、本の気持ちがわかるんです」"

[[dialogue]]
speaker = "モネ"
# 「あれ？　会長、意外と驚いてない？　むしろ私らしい……？」
line = "「あれ？　会長、意外と驚いてない？　むしろ私らしい……？」"

[[dialogue]]
speaker = "モネ"
# 「おお、さすが個性豊かな星徒会を束ねる星徒会長……懐が深いです」
line = "「おお、さすが個性豊かな星徒会を束ねる星徒会長……懐が深いです」"

[[dialogue]]
speaker = "モネ"
# 「もちろん理由もなく本好きになったわけじゃないんですけど……昔は祖父と一緒に暮らしていて」
line = "「もちろん理由もなく本好きになったわけじゃないんですけど……昔は祖父と一緒に暮らしていて」"

[[dialogue]]
speaker = "モネ"
# 「祖父の書斎にはたくさん本があって、物心ついた時には本に囲まれていました。祖父は私に負けない本好きで、よく書斎で一緒に読書してました」
line = "「祖父の書斎にはたくさん本があって、物心ついた時には本に囲まれていました。祖父は私に負けない本好きで、よく書斎で一緒に読書してました」"

[[dialogue]]
speaker = "モネ"
# 「あ……はい、そうですね、いわゆるおじいちゃん子です。何年も前に天国に行っちゃいましたけど、今もおじいちゃんのことは大好きです」
line = "「あ……はい、そうですね、いわゆるおじいちゃん子です。何年も前に天国に行っちゃいましたけど、今もおじいちゃんのことは大好きです」"

[[dialogue]]
speaker = "モネ"
# 「おじいちゃんがいなくなってからも書斎に入り浸って、本ばかり読んでいました」
line = "「おじいちゃんがいなくなってからも書斎に入り浸って、本ばかり読んでいました」"

[[dialogue]]
speaker = "モネ"
# 「それでいつの間にか、読んでほしいとか、手入れしてほしいとか、今は触られたくないとか……本の気持ちがなんとなくわかるようになったんです」
line = "「それでいつの間にか、読んでほしいとか、手入れしてほしいとか、今は触られたくないとか……本の気持ちがなんとなくわかるようになったんです」"

[[dialogue]]
speaker = "モネ"
# 「そのことをお母さんに話すと、新星学園の寮に入れられちゃいましたが……。私がおじいちゃんが好きすぎて妄想してると思われたみたいで」
line = "「そのことをお母さんに話すと、新星学園の寮に入れられちゃいましたが……。私がおじいちゃんが好きすぎて妄想してると思われたみたいで」"

[[dialogue]]
speaker = "モネ"
# 「でも今は新星の図書委員になれたので結果オーライです！　新星の図書館の蔵書は、量が豊富なだけでなく貴重な書物もたくさんありますからね！」
line = "「でも今は新星の図書委員になれたので結果オーライです！　新星の図書館の蔵書は、量が豊富なだけでなく貴重な書物もたくさんありますからね！」"

[[dialogue]]
speaker = "モネ"
# 「本は私の友達なんです。だから、本は本であるというだけで私にとっては宝なのです」
line = "「本は私の友達なんです。だから、本は本であるというだけで私にとっては宝なのです」"

[[dialogue]]
speaker = "モネ"
# 「まぁ……本の友達はたくさんなんですけど、人の友達が少ないんですけどね……あははは」
line = "「まぁ……本の友達はたくさんなんですけど、人の友達が少ないんですけどね……あははは」"

[[dialogue]]
speaker = "unk"
# 俺は友達じゃない？
line = "俺は友達じゃない？"

[[dialogue]]
speaker = "モネ"
# 「えええっ！？　そんな、新星学園全生徒の頂点に立つ星徒会長が友達なんて恐れ多いですよっ」
line = "「えええっ！？　そんな、新星学園全生徒の頂点に立つ星徒会長が友達なんて恐れ多いですよっ」"

[[dialogue]]
speaker = "モネ"
# 「あっ、会長がショックを受けてる……！？」
line = "「あっ、会長がショックを受けてる……！？」"

[[dialogue]]
speaker = "モネ"
# 「で、でも私なんかが会長の友達なんて釣り合いませんし……関係ない？　本の感想を語り合ったんだから友達……？」
line = "「で、でも私なんかが会長の友達なんて釣り合いませんし……関係ない？　本の感想を語り合ったんだから友達……？」"

[[dialogue]]
speaker = "モネ"
# 「そ、そうですねっ。友達……って言っていいですよね」
line = "「そ、そうですねっ。友達……って言っていいですよね」"

[[dialogue]]
speaker = "モネ"
# 「御前試合でヴィーナス前会長を倒して、転入したばかりなのに先頭に立って戦って……会長のこと、すごい人だと思っていました」
line = "「御前試合でヴィーナス前会長を倒して、転入したばかりなのに先頭に立って戦って……会長のこと、すごい人だと思っていました」"

[[dialogue]]
speaker = "モネ"
# 「そんな会長と友達になるなんて、なんだか夢みたいです」
line = "「そんな会長と友達になるなんて、なんだか夢みたいです」"

[[dialogue]]
speaker = "モネ"
# 「ん……？」
line = "「ん……？」"

[[dialogue]]
speaker = "unk"
# どうしたんだ？
line = "どうしたんだ？"

[[dialogue]]
speaker = "モネ"
# 「ふふっ、私の本が会長に嫉妬しちゃったみたいです」
line = "「ふふっ、私の本が会長に嫉妬しちゃったみたいです」"

[[dialogue]]
speaker = "モネ"
# 「大丈夫。みんなは何があってもずっと大事な友達だよ。帰ったらお手入れしてあげるからね」
line = "「大丈夫。みんなは何があってもずっと大事な友達だよ。帰ったらお手入れしてあげるからね」"

[[dialogue]]
speaker = "モネ"
# 「あっ、そうだ、忘れないうちにさっきの戦いをレポートにまとめないと……」
line = "「あっ、そうだ、忘れないうちにさっきの戦いをレポートにまとめないと……」"

[[dialogue]]
speaker = "モネ"
# 「この前みたいなのって……うっ、忘れてくださいよぅ……。あれはただの手癖というか、そもそも小説みたいなのはレポートに適しませんってば」
line = "「この前みたいなのって……うっ、忘れてくださいよぅ……。あれはただの手癖というか、そもそも小説みたいなのはレポートに適しませんってば」"

[[dialogue]]
speaker = "モネ"
# 「はい、これでどうですか？　……問題ない？　ありがとうございます」
line = "「はい、これでどうですか？　……問題ない？　ありがとうございます」"

[[dialogue]]
speaker = "モネ"
# 「戦ってお腹が空きましたし、何か帰りに食べませんか？　この近くにおいしいお店があるんですよ」
line = "「戦ってお腹が空きましたし、何か帰りに食べませんか？　この近くにおいしいお店があるんですよ」"

[[dialogue]]
speaker = "unk"
# 行きたい！
line = "行きたい！"

[[dialogue]]
speaker = "モネ"
# 「決まりですね。唐辛子たっぷりのスープが特徴のつけ麺屋さんで、激烈麻辣麺がおすすめです」
line = "「決まりですね。唐辛子たっぷりのスープが特徴のつけ麺屋さんで、激烈麻辣麺がおすすめです」"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "モネ"
# 「まさしく辛さと旨味のマリアージュ。<ruby=ホアジャオ>花椒</ruby>の風味が抜群で、辛さの中に強い旨味を感じられるんですよ」
line = "「まさしく辛さと旨味のマリアージュ。<ruby>花椒<rt>ホアジャオ</rt></ruby>の風味が抜群で、辛さの中に強い旨味を感じられるんですよ」"

[[dialogue]]
speaker = "モネ"
# 「スープが真っ赤なので、確かに最初見た人は驚くんですけど、大丈夫です！　見た目ほど辛くはないですから」
line = "「スープが真っ赤なので、確かに最初見た人は驚くんですけど、大丈夫です！　見た目ほど辛くはないですから」"

[[dialogue]]
speaker = "モネ"
# 「まぁ、私は最近慣れてきちゃったので一番上の辛さにしてますが……あれ？　会長、どうしたんですか？　顔が青いですよ？　会長～？」
line = "「まぁ、私は最近慣れてきちゃったので一番上の辛さにしてますが……あれ？　会長、どうしたんですか？　顔が青いですよ？　会長～？」"
