[[dialogue]]
speaker = "unk"
# 第４話,未来の白地図,P
line = "第４話,未来の白地図,P"

[[dialogue]]
speaker = "unk"
# トマルとの付き合いも長くなってきた、ある日のこと。彼がなにやら嬉しそうな様子で星徒会室へとやってきた――
line = "トマルとの付き合いも長くなってきた、ある日のこと。彼がなにやら嬉しそうな様子で星徒会室へとやってきた――"

[[dialogue]]
speaker = "トマル"
# 「会長さま、ただいまお時間はよろしいでしょうか？」
line = "「会長さま、ただいまお時間はよろしいでしょうか？」"

[[dialogue]]
speaker = "トマル"
# 「――ありがとうございます。実はちょっと、あなた様の意見をお聞きしたいことがございまして！」
line = "「――ありがとうございます。実はちょっと、あなた様の意見をお聞きしたいことがございまして！」"

[[dialogue]]
speaker = "トマル"
# 「私、イメチェンをしてみたのですが……わかりますか？」
line = "「私、イメチェンをしてみたのですが……わかりますか？」"

[[dialogue]]
speaker = "トマル"
# 「ドキドキ……そわそわ……♪」
line = "「ドキドキ……そわそわ……♪」"

[[dialogue]]
speaker = "unk"
# ごめん、難しいかも……
line = "ごめん、難しいかも……"

[[dialogue]]
speaker = "トマル"
# 「そんな！？」
line = "「そんな！？」"

[[dialogue]]
speaker = "トマル"
# 「うぅ……我ながら、雰囲気が女の子らしくなったのではと、自信があったのですが……」
line = "「うぅ……我ながら、雰囲気が女の子らしくなったのではと、自信があったのですが……」"

[[dialogue]]
speaker = "トマル"
# 「――イメチェンをした部分、ですか……？　それは……」
line = "「――イメチェンをした部分、ですか……？　それは……」"

[[dialogue]]
speaker = "トマル"
# 「性別そのものです」
line = "「性別そのものです」"

[[dialogue]]
speaker = "unk"
# は？
line = "は？"

[[dialogue]]
speaker = "トマル"
# 「私、今は本当に、女の子の体になっているんですよ」
line = "「私、今は本当に、女の子の体になっているんですよ」"

[[dialogue]]
speaker = "トマル"
# 「購買部のアニマさまから、実験で女体化薬を頂きまして……」
line = "「購買部のアニマさまから、実験で女体化薬を頂きまして……」"

[[dialogue]]
speaker = "unk"
# えっ……えぇぇぇ～～～っ！？
line = "えっ……えぇぇぇ～～～っ！？"

[[dialogue]]
speaker = "トマル"
# 「アニマさま、すごいお方です。まだ効果は一時的だそうですが、まさかこうして、本当に女の子になれるだなんて……」
line = "「アニマさま、すごいお方です。まだ効果は一時的だそうですが、まさかこうして、本当に女の子になれるだなんて……」"

[[dialogue]]
speaker = "トマル"
# 「私にとっては、まるで夢のようです……♪」
line = "「私にとっては、まるで夢のようです……♪」"

[[dialogue]]
speaker = "トマル"
# 「ほら、あなた様も、どうぞ私の体に触ってみてください♪　男の子の時とは、全然体つきが違うんですよ？」
line = "「ほら、あなた様も、どうぞ私の体に触ってみてください♪　男の子の時とは、全然体つきが違うんですよ？」"

[[dialogue]]
speaker = "トマル"
# 「そんな、女性の体だからと遠慮なさらずに。私としても、間違いなく女の子になっているのだと、あなた様にわかって頂きたいのでっ」
line = "「そんな、女性の体だからと遠慮なさらずに。私としても、間違いなく女の子になっているのだと、あなた様にわかって頂きたいのでっ」"

[[dialogue]]
speaker = "トマル"
# 「二の腕とか、どうぞ直接触れてみてください。会長さま、さあ！」
line = "「二の腕とか、どうぞ直接触れてみてください。会長さま、さあ！」"

[[dialogue]]
speaker = "トマル"
# 「――いかがでしょう？　男の体の時に比べて、柔らかさが増しているとは思いませんか？」
line = "「――いかがでしょう？　男の体の時に比べて、柔らかさが増しているとは思いませんか？」"

[[dialogue]]
speaker = "トマル"
# 「え？　そもそも普段の私をこんな風に触ったことがないから、わからない……？」
line = "「え？　そもそも普段の私をこんな風に触ったことがないから、わからない……？」"

[[dialogue]]
speaker = "トマル"
# 「い、言われてみれば確かに……。会長さまは紳士的な方ですし……あっ！」
line = "「い、言われてみれば確かに……。会長さまは紳士的な方ですし……あっ！」"

[[dialogue]]
speaker = "トマル"
# 「実は私、女の子になって胸が少し膨らんだのです！　そちらを触って頂ければ、体の変化がよりわかりやすいかと！」
line = "「実は私、女の子になって胸が少し膨らんだのです！　そちらを触って頂ければ、体の変化がよりわかりやすいかと！」"

[[dialogue]]
speaker = "unk"
# それはもっとダメでしょ！？
line = "それはもっとダメでしょ！？"

[[dialogue]]
speaker = "トマル"
# 「はぅぅ……私、女の子になれたら、胸はもっと大きくなるんじゃないかと期待していたのですが――」
line = "「はぅぅ……私、女の子になれたら、胸はもっと大きくなるんじゃないかと期待していたのですが――」"

[[dialogue]]
speaker = "トマル"
# 「私にはどうやら、胸に関して姉さまほどのポテンシャルはなかったみたいで……」
line = "「私にはどうやら、胸に関して姉さまほどのポテンシャルはなかったみたいで……」"

[[dialogue]]
speaker = "トマル"
# 「かくなる上は、下を脱いで、例のものが付いていないことを証明するしか……！」
line = "「かくなる上は、下を脱いで、例のものが付いていないことを証明するしか……！」"

[[dialogue]]
speaker = "unk"
# それは完全にアウトォォォッ！
line = "それは完全にアウトォォォッ！"

[[dialogue]]
speaker = "トマル"
# 「そんな……！　これもダメなら、私にはもう、女の子になっていると証明する術が……」
line = "「そんな……！　これもダメなら、私にはもう、女の子になっていると証明する術が……」"

[[dialogue]]
speaker = "トマル"
# 「うぅ……ごめんなさい。調子に乗っていました……女の子になったというのに私、普段とあまり変わらないなんて……」
line = "「うぅ……ごめんなさい。調子に乗っていました……女の子になったというのに私、普段とあまり変わらないなんて……」"

[[dialogue]]
speaker = "unk"
# トマル、そうじゃないよ
line = "トマル、そうじゃないよ"

[[dialogue]]
speaker = "トマル"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "unk"
# パッと見て気づかなかったのは、それだけ普段からトマルが女の子らしいからだと、目を見て伝える。
line = "パッと見て気づかなかったのは、それだけ普段からトマルが女の子らしいからだと、目を見て伝える。"

[[dialogue]]
speaker = "トマル"
# 「そ、それって……あなた様は私のことを、普段から女の子らしいと……思ってくれている、ということでしょうか？」
line = "「そ、それって……あなた様は私のことを、普段から女の子らしいと……思ってくれている、ということでしょうか？」"

[[dialogue]]
speaker = "unk"
# トマルは普段から可愛い
line = "トマルは普段から可愛い"

[[dialogue]]
speaker = "トマル"
# 「ああ、会長さま……」
line = "「ああ、会長さま……」"

[[dialogue]]
speaker = "トマル"
# （そんな風に、恥ずかしそうに顔を赤くしながら言われてしまったら……私、胸がときめいてしまいます……）
line = "（そんな風に、恥ずかしそうに顔を赤くしながら言われてしまったら……私、胸がときめいてしまいます……）"

[[dialogue]]
speaker = "トマル"
# （で、でも……そう言って下さるということは、私のことを、少しは女の子として意識してくださっているということ、でしょうか？）
line = "（で、でも……そう言って下さるということは、私のことを、少しは女の子として意識してくださっているということ、でしょうか？）"

[[dialogue]]
speaker = "トマル"
# （意識して貰えているなら、私、あなた様への想いを、諦めなくてもいいのでしょうか……？）
line = "（意識して貰えているなら、私、あなた様への想いを、諦めなくてもいいのでしょうか……？）"

[[dialogue]]
speaker = "トマル"
# （それに、いざとなれば女の子になれる薬があるのなら、性別の問題だって――）
line = "（それに、いざとなれば女の子になれる薬があるのなら、性別の問題だって――）"

[[dialogue]]
speaker = "トマル"
# 「あの、会長さま。私……もっともっと素敵な女性になれるよう、頑張ります」
line = "「あの、会長さま。私……もっともっと素敵な女性になれるよう、頑張ります」"

[[dialogue]]
speaker = "トマル"
# 「だからどうか……私のことをこれからも、あなた様のお側に置かせてください」
line = "「だからどうか……私のことをこれからも、あなた様のお側に置かせてください」"

[[dialogue]]
speaker = "unk"
# そう言って笑顔を見せたトマルは、今までで一番女の子らしく見えて。
line = "そう言って笑顔を見せたトマルは、今までで一番女の子らしく見えて。"

[[dialogue]]
speaker = "unk"
# 俺は思わずドキッとしてしまうのだった――
line = "俺は思わずドキッとしてしまうのだった――"
