[[dialogue]]
speaker = "unk"
# 第３話,ハロウィン百合デート,P
line = "第３話,ハロウィン百合デート,P"

[[dialogue]]
speaker = "ヒトリ"
# 「う、うぅ……ハロウィンはもう過ぎたのに、この格好で街を歩くのは、やっぱりちょっと恥ずかしい、です……」
line = "「う、うぅ……ハロウィンはもう過ぎたのに、この格好で街を歩くのは、やっぱりちょっと恥ずかしい、です……」"

[[dialogue]]
speaker = "ヒトリ"
# 「でも、取材の為に、頑張らないと……！」
line = "「でも、取材の為に、頑張らないと……！」"

[[dialogue]]
speaker = "unk"
# ハロウィンからしばらく経ったある休日。俺はハロウィンフォームのヒトリと共に、秋葉原へとやって来ていた。
line = "ハロウィンからしばらく経ったある休日。俺はハロウィンフォームのヒトリと共に、秋葉原へとやって来ていた。"

[[dialogue]]
speaker = "unk"
# というのも――
line = "というのも――"

[[dialogue]]
speaker = "unk"
# ――百合漫画を描く為の、取材？
line = "――百合漫画を描く為の、取材？"

[[dialogue]]
speaker = "ヒトリ"
# 「は、はい。年末に同人誌の大きな即売会があるというのは、会長さんもご存知ですよね……？」
line = "「は、はい。年末に同人誌の大きな即売会があるというのは、会長さんもご存知ですよね……？」"

[[dialogue]]
speaker = "ヒトリ"
# 「わたし、そこに向けて百合漫画を描いてる途中なんですけど……ちょっと、行き詰まってしまっていて……」
line = "「わたし、そこに向けて百合漫画を描いてる途中なんですけど……ちょっと、行き詰まってしまっていて……」"

[[dialogue]]
speaker = "unk"
# 美術部に所属しているヒトリは、自身でも趣味で絵や百合漫画を描いていた。前に見せてもらったことがあるが、その絵は驚くほど上手かった。
line = "美術部に所属しているヒトリは、自身でも趣味で絵や百合漫画を描いていた。前に見せてもらったことがあるが、その絵は驚くほど上手かった。"

[[dialogue]]
speaker = "ヒトリ"
# 「女の子同士がハロウィンデートをするシーンなんですけど、いいイメージがなかなか浮かんで来なくて……」
line = "「女の子同士がハロウィンデートをするシーンなんですけど、いいイメージがなかなか浮かんで来なくて……」"

[[dialogue]]
speaker = "ヒトリ"
# 「なので、会長さん、お願いします――」
line = "「なので、会長さん、お願いします――」"

[[dialogue]]
speaker = "ヒトリ"
# 「わたしと、女の子同士のデートをしてもらえないでしょうか……！？」
line = "「わたしと、女の子同士のデートをしてもらえないでしょうか……！？」"

[[dialogue]]
speaker = "unk"
# いや、俺は男なんだけど！？
line = "いや、俺は男なんだけど！？"

[[dialogue]]
speaker = "unk"
# そんな事情があって、２人でデートすることになったのだが――
line = "そんな事情があって、２人でデートすることになったのだが――"

[[dialogue]]
speaker = "ヒトリ"
# 「そ、それにしても、会長さんのハロウィンフォーム……すごく似合ってます……！」
line = "「そ、それにしても、会長さんのハロウィンフォーム……すごく似合ってます……！」"

[[dialogue]]
speaker = "unk"
# う、うん……ありがとう……
line = "う、うん……ありがとう……"

[[dialogue]]
speaker = "ヒトリ"
# 「どこからどう見ても、百合の花がバックに咲いているような美少女で、感嘆のため息が漏れてしまいます……！」
line = "「どこからどう見ても、百合の花がバックに咲いているような美少女で、感嘆のため息が漏れてしまいます……！」"

[[dialogue]]
speaker = "ヒトリ"
# 「さすがアニマ先輩ですね……！　会長さんが女の子に変身した状態を維持しつつ、新たにハロウィンフォームまで作り上げてしまうだなんて……！」
line = "「さすがアニマ先輩ですね……！　会長さんが女の子に変身した状態を維持しつつ、新たにハロウィンフォームまで作り上げてしまうだなんて……！」"

[[dialogue]]
speaker = "unk"
# 最初はいつもの『星力倍増薬』の副作用で、性別転換するだけのつもりだったのだ――しかし。
line = "最初はいつもの『星力倍増薬』の副作用で、性別転換するだけのつもりだったのだ――しかし。"

[[dialogue]]
speaker = "アニマ"
# 「フヒ♪　ならばちょうどイイ。会長のハロウィンフォームも、作ってしまおうじゃないカ♪」
line = "「フヒ♪　ならばちょうどイイ。会長のハロウィンフォームも、作ってしまおうじゃないカ♪」"

[[dialogue]]
speaker = "unk"
# ハロウィンデートの取材という話をアニマ先輩にしたら、ノリノリであっという間に俺のハロウィンフォームを完成させてしまったのである。
line = "ハロウィンデートの取材という話をアニマ先輩にしたら、ノリノリであっという間に俺のハロウィンフォームを完成させてしまったのである。"

[[dialogue]]
speaker = "unk"
# とはいえ、セレスティアを使って『変身』できるというだけで、ヒトリのように特殊な能力や新しい力に目覚めたりはしなかった。
line = "とはいえ、セレスティアを使って『変身』できるというだけで、ヒトリのように特殊な能力や新しい力に目覚めたりはしなかった。"

[[dialogue]]
speaker = "アニマ"
# 「フヒ？　これではただの、早着替えできるコスプレ衣装でしかない……ダト？　だが、それがいい！　違うカ、会長？」
line = "「フヒ？　これではただの、早着替えできるコスプレ衣装でしかない……ダト？　だが、それがいい！　違うカ、会長？」"

[[dialogue]]
speaker = "unk"
# 何もよくないのだが……？？？
line = "何もよくないのだが……？？？"

[[dialogue]]
speaker = "unk"
# そんなこんながあって始まった、俺とヒトリの百合デート。
line = "そんなこんながあって始まった、俺とヒトリの百合デート。"

[[dialogue]]
speaker = "unk"
# 経緯はぶっ飛んでいるが、何はともあれ彼女とのデートである。彼氏としてはそれなりに楽しみにしていたのだが──
line = "経緯はぶっ飛んでいるが、何はともあれ彼女とのデートである。彼氏としてはそれなりに楽しみにしていたのだが──"

[[dialogue]]
speaker = "unk"
# あの……ヒトリさん？
line = "あの……ヒトリさん？"

[[dialogue]]
speaker = "ヒトリ"
# 「ひゃ、ひゃい……！　なんでしょう……！？」
line = "「ひゃ、ひゃい……！　なんでしょう……！？」"

[[dialogue]]
speaker = "ヒトリ"
# 「――な、なんでそんなに緊張しているのか、ですか？」
line = "「――な、なんでそんなに緊張しているのか、ですか？」"

[[dialogue]]
speaker = "unk"
# 俺とヒトリのデートは初めてというわけではない。にも関わらず、手を繋ごうとしても、何やら恥ずかしがって距離を取られてしまっている。それどころか……
line = "俺とヒトリのデートは初めてというわけではない。にも関わらず、手を繋ごうとしても、何やら恥ずかしがって距離を取られてしまっている。それどころか……"

[[dialogue]]
speaker = "ヒトリ"
# 「――め、目も合わせようとしない？　そ、それは……えっと……その……」
line = "「――め、目も合わせようとしない？　そ、それは……えっと……その……」"

[[dialogue]]
speaker = "ヒトリ"
# 「じ、実は……会長さんが美人すぎて……お顔を直視できなくて……！」
line = "「じ、実は……会長さんが美人すぎて……お顔を直視できなくて……！」"

[[dialogue]]
speaker = "unk"
# 彼氏としては複雑なんだけど……
line = "彼氏としては複雑なんだけど……"

[[dialogue]]
speaker = "unk"
# 男の姿でそんなこと言われたことないから
line = "男の姿でそんなこと言われたことないから"

[[dialogue]]
speaker = "ヒトリ"
# 「あっ、い、いえっ。わたしは男の会長さんのお顔も好きですよ……！？」
line = "「あっ、い、いえっ。わたしは男の会長さんのお顔も好きですよ……！？」"

[[dialogue]]
speaker = "ヒトリ"
# 「ただ……」
line = "「ただ……」"

[[dialogue]]
speaker = "ヒトリ"
# 「会長さんって、女の子になると真の姿になったみたいに、色々パワーアップするといいますか……」
line = "「会長さんって、女の子になると真の姿になったみたいに、色々パワーアップするといいますか……」"

[[dialogue]]
speaker = "unk"
# 俺の真の姿は男の方だよ！？
line = "俺の真の姿は男の方だよ！？"

[[dialogue]]
speaker = "unk"
# と、その時だった。
line = "と、その時だった。"

[[dialogue]]
speaker = "男"
# 「ねぇ、そこのお２人さん。ちょっといいかな～？」
line = "「ねぇ、そこのお２人さん。ちょっといいかな～？」"

[[dialogue]]
speaker = "unk"
# 背後から、俺とヒトリの間に挟まるように、見知らぬ男が割って入って来た。金髪で軽そうな感じの――年齢は２０代前半くらいだろうか。
line = "背後から、俺とヒトリの間に挟まるように、見知らぬ男が割って入って来た。金髪で軽そうな感じの――年齢は２０代前半くらいだろうか。"

[[dialogue]]
speaker = "男"
# 「おっ、どっちの子も可愛いねぇ～。暇なら俺と遊ばない？」
line = "「おっ、どっちの子も可愛いねぇ～。暇なら俺と遊ばない？」"

[[dialogue]]
speaker = "unk"
# そう言って男は、俺とヒトリの肩に手を置く。
line = "そう言って男は、俺とヒトリの肩に手を置く。"

[[dialogue]]
speaker = "ヒトリ"
# 「ひっ……お、男の人……！？」
line = "「ひっ……お、男の人……！？」"

[[dialogue]]
speaker = "unk"
# 俺は、ヒトリの肩に置かれた方の手首を掴むと、男の目を真っ直ぐに見る。
line = "俺は、ヒトリの肩に置かれた方の手首を掴むと、男の目を真っ直ぐに見る。"

[[dialogue]]
speaker = "男"
# 「え……？　な、何？　手がビクとも動かな――」
line = "「え……？　な、何？　手がビクとも動かな――」"

[[dialogue]]
speaker = "unk"
# 百合に挟まる男は……罪が重いよ？
line = "百合に挟まる男は……罪が重いよ？"

[[dialogue]]
speaker = "unk"
# お兄さん――
line = "お兄さん――"

[[dialogue]]
speaker = "unk"
# それからニコッと笑って、手を離すと……
line = "それからニコッと笑って、手を離すと……"

[[dialogue]]
speaker = "男"
# 「……な、なんかよく分からないけど、すんません！！！　失礼しましたぁぁぁ～～～っ！！！」
line = "「……な、なんかよく分からないけど、すんません！！！　失礼しましたぁぁぁ～～～っ！！！」"

[[dialogue]]
speaker = "unk"
# 男は逃げるように去って行った。
line = "男は逃げるように去って行った。"

[[dialogue]]
speaker = "ヒトリ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# ふぅ……ヒトリ、大丈夫だった？
line = "ふぅ……ヒトリ、大丈夫だった？"

[[dialogue]]
speaker = "unk"
# ぼーっとしている様子のヒトリに声を掛けると――
line = "ぼーっとしている様子のヒトリに声を掛けると――"

[[dialogue]]
speaker = "ヒトリ"
# 「……お姉様……！」
line = "「……お姉様……！」"

[[dialogue]]
speaker = "unk"
# え？
line = "え？"

[[dialogue]]
speaker = "ヒトリ"
# 「ああ、そうです……！　今回は同い年の女の子じゃなくて、年上の女の子とのてぇてぇを描けばよかったんです！」
line = "「ああ、そうです……！　今回は同い年の女の子じゃなくて、年上の女の子とのてぇてぇを描けばよかったんです！」"

[[dialogue]]
speaker = "ヒトリ"
# 「この憧れるような想い……！　会長さん……今日から女の子の姿になった時は、『お姉様』と呼んでもいいでしょうか！？」
line = "「この憧れるような想い……！　会長さん……今日から女の子の姿になった時は、『お姉様』と呼んでもいいでしょうか！？」"

[[dialogue]]
speaker = "unk"
# いや、どういうこと！？
line = "いや、どういうこと！？"

[[dialogue]]
speaker = "unk"
# いつもとは違う、キラキラとした瞳を俺に向けて来るヒトリ。
line = "いつもとは違う、キラキラとした瞳を俺に向けて来るヒトリ。"

[[dialogue]]
speaker = "ゆーちゃん"
# 「てーてー！　てーてー！」
line = "「てーてー！　てーてー！」"

[[dialogue]]
speaker = "unk"
# 姿は見えないが、近くで興奮しているらしいゆーちゃんの声が沢山聞こえてくるのだった。
line = "姿は見えないが、近くで興奮しているらしいゆーちゃんの声が沢山聞こえてくるのだった。"

[[dialogue]]
speaker = "unk"
# その後――街のカフェにて。
line = "その後――街のカフェにて。"

[[dialogue]]
speaker = "ヒトリ"
# 「お、お姉様……よろしくお願いします……！」
line = "「お、お姉様……よろしくお願いします……！」"

[[dialogue]]
speaker = "ヒトリ"
# 「あ、あ～ん……♪」
line = "「あ、あ～ん……♪」"

[[dialogue]]
speaker = "unk"
# 頼んだストロベリーパフェを、スプーンで食べさせてあげると……
line = "頼んだストロベリーパフェを、スプーンで食べさせてあげると……"

[[dialogue]]
speaker = "ヒトリ"
# 「――あむっ♪　もぐもぐ……ん～～～っ<emoji=heart04>」
line = "「――あむっ♪　もぐもぐ……ん～～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ヒトリ"
# 「お姉様のご尊顔は眩しくて直視できませんが、てぇてぇ味がします……♪　はあぁぁ♪」
line = "「お姉様のご尊顔は眩しくて直視できませんが、てぇてぇ味がします……♪　はあぁぁ♪」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「てーてー♪」
line = "「てーてー♪」"

[[dialogue]]
speaker = "unk"
# 俺の顔を見ないように伏し目がちで照れつつも、嬉しそうにネコミミをピコピコさせるヒトリの姿がそこにはあった――
line = "俺の顔を見ないように伏し目がちで照れつつも、嬉しそうにネコミミをピコピコさせるヒトリの姿がそこにはあった――"
