[[dialogue]]
speaker = "unk"
# 第３話,クリスマスフォーム,P
line = "第３話,クリスマスフォーム,P"

[[dialogue]]
speaker = "unk"
# 九浄家の屋敷に呼ばれて行ってみると、中庭で蘭美と紅明が何やら真剣な表情で話をしている。
line = "九浄家の屋敷に呼ばれて行ってみると、中庭で蘭美と紅明が何やら真剣な表情で話をしている。"

[[dialogue]]
speaker = "unk"
# 紅明の格好には見覚えがあったが、蘭美は見慣れない衣装を身に着けていた。
line = "紅明の格好には見覚えがあったが、蘭美は見慣れない衣装を身に着けていた。"

[[dialogue]]
speaker = "unk"
# あの格好は一体……？
line = "あの格好は一体……？"

[[dialogue]]
speaker = "ヘレナ"
# 「よく来た魔王よ。蘭美の着ているアレは、新たに開発した人工戦闘服、蘭美専用の『クリスマスフォーム』だ」
line = "「よく来た魔王よ。蘭美の着ているアレは、新たに開発した人工戦闘服、蘭美専用の『クリスマスフォーム』だ」"

[[dialogue]]
speaker = "ヘレナ"
# 「つい先日に完成し蘭美にプレゼントしたばかりなのだが、まだその力を引き出すに至っていない状態なのだ」
line = "「つい先日に完成し蘭美にプレゼントしたばかりなのだが、まだその力を引き出すに至っていない状態なのだ」"

[[dialogue]]
speaker = "ヘレナ"
# 「それでクリスマスフォームの元になった戦闘服を持つ紅明を招いて、その力を引き出すべく試行錯誤しているというわけだ」
line = "「それでクリスマスフォームの元になった戦闘服を持つ紅明を招いて、その力を引き出すべく試行錯誤しているというわけだ」"

[[dialogue]]
speaker = "unk"
# 目のやり場に困るんですけど
line = "目のやり場に困るんですけど"

[[dialogue]]
speaker = "unk"
# 大胆なデザインですね
line = "大胆なデザインですね"

[[dialogue]]
speaker = "ヘレナ"
# 「そうだろう？　蘭美の色気を最大限引き出せるように、全身全霊を注ぎ込んだのだ」
line = "「そうだろう？　蘭美の色気を最大限引き出せるように、全身全霊を注ぎ込んだのだ」"

[[dialogue]]
speaker = "ヘレナ"
# 「蘭美は胸がぺったんこで色気なしに思われがちだが、実は脇と腰のくびれが絶品だからな」
line = "「蘭美は胸がぺったんこで色気なしに思われがちだが、実は脇と腰のくびれが絶品だからな」"

[[dialogue]]
speaker = "ヘレナ"
# 「まあ彼氏である魔王には、語るまでもないことかもしれないが。ふふふ……」
line = "「まあ彼氏である魔王には、語るまでもないことかもしれないが。ふふふ……」"

[[dialogue]]
speaker = "ヘレナ"
# 「ん？　何かな、その顔は。貴殿と交際を始めたことは、蘭美からしっかりと報告を受けているぞ？」
line = "「ん？　何かな、その顔は。貴殿と交際を始めたことは、蘭美からしっかりと報告を受けているぞ？」"

[[dialogue]]
speaker = "ヘレナ"
# 「仲睦まじいようで大いに結構。蘭美のこと、私からも頼むぞ。大切にしてやってくれ」
line = "「仲睦まじいようで大いに結構。蘭美のこと、私からも頼むぞ。大切にしてやってくれ」"

[[dialogue]]
speaker = "ヘレナ"
# 「おっと……そんな話をしていたら２人が戻ってきたようだ」
line = "「おっと……そんな話をしていたら２人が戻ってきたようだ」"

[[dialogue]]
speaker = "蘭美"
# 「当主様……会長と何をお話しされていたのですか？」
line = "「当主様……会長と何をお話しされていたのですか？」"

[[dialogue]]
speaker = "ヘレナ"
# 「うむ、お前のクリスマスフォームのデザインコンセプトについて熱く語っていたのだ」
line = "「うむ、お前のクリスマスフォームのデザインコンセプトについて熱く語っていたのだ」"

[[dialogue]]
speaker = "紅明"
# 「ヘレナちゃんが作ったラビラビのクリスマスフォーム、去年のヨミヨミのやつよりだいぶ刺激的っしょ～！」
line = "「ヘレナちゃんが作ったラビラビのクリスマスフォーム、去年のヨミヨミのやつよりだいぶ刺激的っしょ～！」"

[[dialogue]]
speaker = "unk"
# 紅明が九浄家の面子と顔見知りなのは知らなかったが、すでにだいぶ打ち解けているらしい。
line = "紅明が九浄家の面子と顔見知りなのは知らなかったが、すでにだいぶ打ち解けているらしい。"

[[dialogue]]
speaker = "unk"
# ちなみにヘレナちゃんは初対面の相手に「私のことはヘレナちゃんと呼ぶがいい！」と言って回る癖がある。……かなり偉い人なので、その通りに呼ぶヒトは割と少ない。
line = "ちなみにヘレナちゃんは初対面の相手に「私のことはヘレナちゃんと呼ぶがいい！」と言って回る癖がある。……かなり偉い人なので、その通りに呼ぶヒトは割と少ない。"

[[dialogue]]
speaker = "ヘレナ"
# 「うむ！　紅明にもわかるか！　今回はまさに、まさに蘭美の隠れた色気を引き出すことが狙いだったからな」
line = "「うむ！　紅明にもわかるか！　今回はまさに、まさに蘭美の隠れた色気を引き出すことが狙いだったからな」"

[[dialogue]]
speaker = "紅明"
# 「狙い通りという意味では大成功だけど……ラビラビ的には露出の多い服装はＯＫなん？」
line = "「狙い通りという意味では大成功だけど……ラビラビ的には露出の多い服装はＯＫなん？」"

[[dialogue]]
speaker = "蘭美"
# 「平気よ。私は自分のプロポーションに自信を持ってるから」
line = "「平気よ。私は自分のプロポーションに自信を持ってるから」"

[[dialogue]]
speaker = "蘭美"
# 「むしろこんな可愛い服を着ているんだから、もっとしっかり見て欲しいくらいね！」
line = "「むしろこんな可愛い服を着ているんだから、もっとしっかり見て欲しいくらいね！」"

[[dialogue]]
speaker = "紅明"
# 「おぉ～！　タレント向きのメンタル☆　それじゃあお言葉に甘えて、たっぷり見させてもらうっしょ！」
line = "「おぉ～！　タレント向きのメンタル☆　それじゃあお言葉に甘えて、たっぷり見させてもらうっしょ！」"

[[dialogue]]
speaker = "蘭美"
# 「今日は大サービスよ。しっかり目に焼き付けていきなさい！」
line = "「今日は大サービスよ。しっかり目に焼き付けていきなさい！」"

[[dialogue]]
speaker = "紅明"
# 「ほらほら～、ダーリンもしっかり見なくちゃダメだぜ！？　彼女がここまで奮発してくれてるんだから！」
line = "「ほらほら～、ダーリンもしっかり見なくちゃダメだぜ！？　彼女がここまで奮発してくれてるんだから！」"

[[dialogue]]
speaker = "unk"
# 男の俺がジロジロ見るわけには……
line = "男の俺がジロジロ見るわけには……"

[[dialogue]]
speaker = "紅明"
# 「もぅ～♪　ダーリンってば、シャイボーイ☆」
line = "「もぅ～♪　ダーリンってば、シャイボーイ☆」"

[[dialogue]]
speaker = "ヘレナ"
# 「いやいや、そんな事はないぞ……むしろさっきは食い入るように見ていたが？」
line = "「いやいや、そんな事はないぞ……むしろさっきは食い入るように見ていたが？」"

[[dialogue]]
speaker = "蘭美"
# 「ぴゃっ……！！！」
line = "「ぴゃっ……！！！」"

[[dialogue]]
speaker = "紅明"
# 「あ、固まっちった」
line = "「あ、固まっちった」"

[[dialogue]]
speaker = "unk"
# そ、そんなに見てないよ！
line = "そ、そんなに見てないよ！"

[[dialogue]]
speaker = "ヘレナ"
# 「私の目を誤魔化せると思うな？　主にむっちりとした肉付きのいい太ももの辺りを、舐めるように……」
line = "「私の目を誤魔化せると思うな？　主にむっちりとした肉付きのいい太ももの辺りを、舐めるように……」"

[[dialogue]]
speaker = "蘭美"
# 「ぅぅぅぅぅ～～～～！！！！」
line = "「ぅぅぅぅぅ～～～～！！！！」"

[[dialogue]]
speaker = "紅明"
# 「アタシたちの視線は平気だったけど、ダーリンの視線はダメだったってこと？」
line = "「アタシたちの視線は平気だったけど、ダーリンの視線はダメだったってこと？」"

[[dialogue]]
speaker = "ヘレナ"
# 「好きな相手に見られていたことに動揺して動けなくなる……うむ♪　意外に可愛いところがあるではないか」
line = "「好きな相手に見られていたことに動揺して動けなくなる……うむ♪　意外に可愛いところがあるではないか」"

[[dialogue]]
speaker = "蘭美"
# 「へ──」
line = "「へ──」"

[[dialogue]]
speaker = "蘭美"
# 「平気だぴょん！　恥ずかしいとか無いぴょん！　相手が会長だって平気だぴょん！」
line = "「平気だぴょん！　恥ずかしいとか無いぴょん！　相手が会長だって平気だぴょん！」"

[[dialogue]]
speaker = "蘭美"
# 「むしろ会長こそしっかり見るべきだぴょん！　恋人のエロ可愛い格好を見て、興奮しない方がおかしいぴょん！」
line = "「むしろ会長こそしっかり見るべきだぴょん！　恋人のエロ可愛い格好を見て、興奮しない方がおかしいぴょん！」"

[[dialogue]]
speaker = "蘭美"
# 「それとも会長は私の身体が、夢中になるほど大したものではないと言いたいぴょん！！？」
line = "「それとも会長は私の身体が、夢中になるほど大したものではないと言いたいぴょん！！？」"

[[dialogue]]
speaker = "unk"
# ずっと見てたいくらい可愛いよ！
line = "ずっと見てたいくらい可愛いよ！"

[[dialogue]]
speaker = "unk"
# そ、そんなことない！
line = "そ、そんなことない！"

[[dialogue]]
speaker = "蘭美"
# 「ぴゃっ！？　ず、ずっと……ずっと見るぴょん？　会長に、見られちゃうぴょん……？」
line = "「ぴゃっ！？　ず、ずっと……ずっと見るぴょん？　会長に、見られちゃうぴょん……？」"

[[dialogue]]
speaker = "蘭美"
# 「だったら見るぴょん！　思う存分、好きなだけ見ればいいぴょん！　もうどうにでもなればいいぴょん！！！！」
line = "「だったら見るぴょん！　思う存分、好きなだけ見ればいいぴょん！　もうどうにでもなればいいぴょん！！！！」"

[[dialogue]]
speaker = "紅明"
# 「ラビラビ、ほら深呼吸、深呼吸。混乱しすぎで方言出まくっちゃってるから！」
line = "「ラビラビ、ほら深呼吸、深呼吸。混乱しすぎで方言出まくっちゃってるから！」"

[[dialogue]]
speaker = "ヘレナ"
# 「うむ。大変なことになってしまったな！」
line = "「うむ。大変なことになってしまったな！」"

[[dialogue]]
speaker = "unk"
# 落ち着いてないで助けてください！
line = "落ち着いてないで助けてください！"

[[dialogue]]
speaker = "ヘレナ"
# 「好きな人に可愛い衣装を見てもらいたいが、どこか気恥ずかしさも覚える──実によき青春のひとコマである」
line = "「好きな人に可愛い衣装を見てもらいたいが、どこか気恥ずかしさも覚える──実によき青春のひとコマである」"

[[dialogue]]
speaker = "ヘレナ"
# 「それを私が止めると言うのも、野暮な話だ。というわけで魔王よ、後は若い者に任せるぞ」
line = "「それを私が止めると言うのも、野暮な話だ。というわけで魔王よ、後は若い者に任せるぞ」"

[[dialogue]]
speaker = "unk"
# ぶん投げた……！？
line = "ぶん投げた……！？"

[[dialogue]]
speaker = "蘭美"
# 「ぴゃぁ～～～～～～～っ！！！」
line = "「ぴゃぁ～～～～～～～っ！！！」"

[[dialogue]]
speaker = "unk"
# その後パニックになった蘭美を落ち着かせ、なんとか立ち直らせるために１時間以上の時間を要するのだった。
line = "その後パニックになった蘭美を落ち着かせ、なんとか立ち直らせるために１時間以上の時間を要するのだった。"
