[[dialogue]]
speaker = "unk"
# 第２話,ショッピングフレンズ,P
line = "第２話,ショッピングフレンズ,P"

[[dialogue]]
speaker = "unk"
# ハロウィンの後、仲良くなった３人は街に買い物へ出かけていた。
line = "ハロウィンの後、仲良くなった３人は街に買い物へ出かけていた。"

[[dialogue]]
speaker = "ウズメイア"
# 「ハロウィンで仲良くなったから、これを機会にもっと親交を深めるし♪」
line = "「ハロウィンで仲良くなったから、これを機会にもっと親交を深めるし♪」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ヒトリと出かけるときは、いつもお菓子屋さんだゆ！　ここには初めて来たゆ！」
line = "「ヒトリと出かけるときは、いつもお菓子屋さんだゆ！　ここには初めて来たゆ！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「人がいっぱいだし、にぎやかだし、なんだか不思議と楽しい気持ちになってくる街ゆ！」
line = "「人がいっぱいだし、にぎやかだし、なんだか不思議と楽しい気持ちになってくる街ゆ！」"

[[dialogue]]
speaker = "ソフィア"
# 「土地柄的にハロウィンとも相性がいいですからね」
line = "「土地柄的にハロウィンとも相性がいいですからね」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「何かあるのかゆ？」
line = "「何かあるのかゆ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「ハロウィンの時はここも派手なお祭り騒ぎになるし、通りは歩行者天国になって仮装する人でいっぱいになるし♪」
line = "「ハロウィンの時はここも派手なお祭り騒ぎになるし、通りは歩行者天国になって仮装する人でいっぱいになるし♪」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆっゆっゆ～♪　次はそれにも参加してみたいゆ！」
line = "「ゆっゆっゆ～♪　次はそれにも参加してみたいゆ！」"

[[dialogue]]
speaker = "ソフィア"
# 「私はあまり騒がしいのは得意ではないのですが……」
line = "「私はあまり騒がしいのは得意ではないのですが……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「そうなのかゆ？　それじゃソフィアはお留守番ゆ？」
line = "「そうなのかゆ？　それじゃソフィアはお留守番ゆ？」"

[[dialogue]]
speaker = "ソフィア"
# 「そうは言ってません。みんなが行くなら私も行きます」
line = "「そうは言ってません。みんなが行くなら私も行きます」"

[[dialogue]]
speaker = "ウズメイア"
# 「ソフィは寂しがりやだし♪」
line = "「ソフィは寂しがりやだし♪」"

[[dialogue]]
speaker = "ソフィア"
# 「仲間外れにされるのが許せないだけです」
line = "「仲間外れにされるのが許せないだけです」"

[[dialogue]]
speaker = "ソフィア"
# 「できれば舞亜も一緒に来て、ジャクリーヌさんと仲良くなって欲しいのですが」
line = "「できれば舞亜も一緒に来て、ジャクリーヌさんと仲良くなって欲しいのですが」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「舞亜は何をしてるゆ？」
line = "「舞亜は何をしてるゆ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「フィギュアスケートの遠征から帰ってきてないの」
line = "「フィギュアスケートの遠征から帰ってきてないの」"

[[dialogue]]
speaker = "ウズメイア"
# 「ハロウィンの時も一緒に遊べなかったし……あ～あ、早く帰ってこないかなぁ」
line = "「ハロウィンの時も一緒に遊べなかったし……あ～あ、早く帰ってこないかなぁ」"

[[dialogue]]
speaker = "ソフィア"
# 「もうすぐですよ。そしたら舞亜も加えて４人でショッピングに行きましょう」
line = "「もうすぐですよ。そしたら舞亜も加えて４人でショッピングに行きましょう」"

[[dialogue]]
speaker = "ウズメイア"
# 「うんうん、そうするし！　それじゃ２人ともお店にレッツゴー♪」
line = "「うんうん、そうするし！　それじゃ２人ともお店にレッツゴー♪」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆっ！？　すごいゆ！　お洋服がいっぱいだゆ！！」
line = "「ゆっ！？　すごいゆ！　お洋服がいっぱいだゆ！！」"

[[dialogue]]
speaker = "ウズメイア"
# 「でしょ～♪　このお店はあたしのお気に入りなの♪」
line = "「でしょ～♪　このお店はあたしのお気に入りなの♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「あっ、今日は和装フェアなんだ。ちょっと行ってみるし♪」
line = "「あっ、今日は和装フェアなんだ。ちょっと行ってみるし♪」"

[[dialogue]]
speaker = "ソフィア"
# 「待ってください。今日はジャクリーヌさんのお洋服を選ぶのが目的でしょう？　あなたが買い物に夢中になってどうするんです！」
line = "「待ってください。今日はジャクリーヌさんのお洋服を選ぶのが目的でしょう？　あなたが買い物に夢中になってどうするんです！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「そうゆ！　さっさと余の好きそうなお洋服の売り場に案内するゆ！」
line = "「そうゆ！　さっさと余の好きそうなお洋服の売り場に案内するゆ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ゆゆ姫ちゃん、和装はいいよ～。一度騙されたと思って着てみて欲しいかも」
line = "「ゆゆ姫ちゃん、和装はいいよ～。一度騙されたと思って着てみて欲しいかも」"

[[dialogue]]
speaker = "ウズメイア"
# 「そしたらきっとゆゆ姫ちゃんも和装の虜になるはずだし♪」
line = "「そしたらきっとゆゆ姫ちゃんも和装の虜になるはずだし♪」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「着物も嫌いじゃないゆ！　でも余の好みはもっと派手なお洋服ゆ！」
line = "「着物も嫌いじゃないゆ！　でも余の好みはもっと派手なお洋服ゆ！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆっ、例えばあれ！　こんな感じの、着ているだけで楽しくなっちゃうようなお洋服がいいゆ！」
line = "「ゆっ、例えばあれ！　こんな感じの、着ているだけで楽しくなっちゃうようなお洋服がいいゆ！」"

[[dialogue]]
speaker = "ソフィア"
# 「うっ！　可愛いには可愛いですが、ギンギンのオレンジが鮮やか過ぎて目が痛いです……」
line = "「うっ！　可愛いには可愛いですが、ギンギンのオレンジが鮮やか過ぎて目が痛いです……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「オレンジの何が悪いゆ！　オレンジ色はこの世で最も高貴な色なんだゆ！」
line = "「オレンジの何が悪いゆ！　オレンジ色はこの世で最も高貴な色なんだゆ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「えーっ！？　高貴って言ったら紫色っしょ！　ゆゆ姫ちゃんはカボチャ王国の姫なんだから紫いってみよ、紫」
line = "「えーっ！？　高貴って言ったら紫色っしょ！　ゆゆ姫ちゃんはカボチャ王国の姫なんだから紫いってみよ、紫」"

[[dialogue]]
speaker = "ソフィア"
# 「紫……ジャクリーヌさんはもっと明るいイメージのような……」
line = "「紫……ジャクリーヌさんはもっと明るいイメージのような……」"

[[dialogue]]
speaker = "ソフィア"
# 「そうですね……こういう感じのはどうでしょう？　きっとジャクリーヌさんに似合うと思いますよ」
line = "「そうですね……こういう感じのはどうでしょう？　きっとジャクリーヌさんに似合うと思いますよ」"

[[dialogue]]
speaker = "ウズメイア"
# 「うーん……」
line = "「うーん……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆ～……」
line = "「ゆ～……」"

[[dialogue]]
speaker = "ソフィア"
# 「あれ？　そんな微妙な反応が返ってきますか？」
line = "「あれ？　そんな微妙な反応が返ってきますか？」"

[[dialogue]]
speaker = "ウズメイア"
# 「ちょっと地味過ぎじゃない？　もっと露出があった方がいいし」
line = "「ちょっと地味過ぎじゃない？　もっと露出があった方がいいし」"

[[dialogue]]
speaker = "ソフィア"
# 「着物がいいとか言ってた人の発言とは思えないです！」
line = "「着物がいいとか言ってた人の発言とは思えないです！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「胸のあたりが窮屈そうゆ。もっとパカッと開いてる感じがいいゆ！」
line = "「胸のあたりが窮屈そうゆ。もっとパカッと開いてる感じがいいゆ！」"

[[dialogue]]
speaker = "ソフィア"
# 「む、胸なんて主張する必要はありません！　わざわざ寒い格好をするなんて愚か者のすることです！」
line = "「む、胸なんて主張する必要はありません！　わざわざ寒い格好をするなんて愚か者のすることです！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆ？　ソフィアはどうして怒ってるゆ？」
line = "「ゆ？　ソフィアはどうして怒ってるゆ？」"

[[dialogue]]
speaker = "ソフィア"
# 「怒ってませんから！　ほら、２人とも自分の趣味に走ってないで、ちゃんと選びなさい！！」
line = "「怒ってませんから！　ほら、２人とも自分の趣味に走ってないで、ちゃんと選びなさい！！」"

[[dialogue]]
speaker = "ウズメイア"
# 「あははっ♪」
line = "「あははっ♪」"

[[dialogue]]
speaker = "ソフィア"
# 「あなたも何を笑っているんですか、ウズメ」
line = "「あなたも何を笑っているんですか、ウズメ」"

[[dialogue]]
speaker = "ウズメイア"
# 「なんかソフィもゆゆ姫ちゃんとふつーに言い合いできるくらいに打ち解けたなーって思って」
line = "「なんかソフィもゆゆ姫ちゃんとふつーに言い合いできるくらいに打ち解けたなーって思って」"

[[dialogue]]
speaker = "ソフィア"
# 「ん、それは……そうかもしれませんね……」
line = "「ん、それは……そうかもしれませんね……」"

[[dialogue]]
speaker = "ウズメイア"
# 「それだけでも今日、一緒に買い物に来た甲斐はあったし♪」
line = "「それだけでも今日、一緒に買い物に来た甲斐はあったし♪」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「何を言ってるゆ？　余は最初からソフィアと仲良しゆ」
line = "「何を言ってるゆ？　余は最初からソフィアと仲良しゆ」"

[[dialogue]]
speaker = "ウズメイア"
# 「ゆゆ姫ちゃんはそのままでオッケーだし♪　ほらほら、それじゃ服選びの続きしよ！」
line = "「ゆゆ姫ちゃんはそのままでオッケーだし♪　ほらほら、それじゃ服選びの続きしよ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「──ってね、この間のお休みはそんな感じだったんだ～」
line = "「──ってね、この間のお休みはそんな感じだったんだ～」"

[[dialogue]]
speaker = "unk"
# ハロウィンの時よりもっと仲良くなれた？
line = "ハロウィンの時よりもっと仲良くなれた？"

[[dialogue]]
speaker = "ウズメイア"
# 「そうそう。そっからもうずっとソフィのツッコミがキレキレだったんだ～」
line = "「そうそう。そっからもうずっとソフィのツッコミがキレキレだったんだ～」"

[[dialogue]]
speaker = "ウズメイア"
# 「最後はソフィがお姉ちゃんみたいな感じになってたよ。ゆゆ姫ちゃんは絶対ソフィをお姉ちゃんと思ってないだろうけど」
line = "「最後はソフィがお姉ちゃんみたいな感じになってたよ。ゆゆ姫ちゃんは絶対ソフィをお姉ちゃんと思ってないだろうけど」"

[[dialogue]]
speaker = "ウズメイア"
# 「でも、２人ともすっごい楽しそうだったし。また一緒に行こうって計画も立ててるし……」
line = "「でも、２人ともすっごい楽しそうだったし。また一緒に行こうって計画も立ててるし……」"

[[dialogue]]
speaker = "ウズメイア"
# 「そだ、次は会長くんも一緒に来る？」
line = "「そだ、次は会長くんも一緒に来る？」"

[[dialogue]]
speaker = "unk"
# 俺が混じって邪魔にならないかな？
line = "俺が混じって邪魔にならないかな？"

[[dialogue]]
speaker = "ウズメイア"
# 「全然だし♪　会長くんが来るって聞いたら２人も喜ぶし♪」
line = "「全然だし♪　会長くんが来るって聞いたら２人も喜ぶし♪」"

[[dialogue]]
speaker = "unk"
# だったら次は俺も参加で──
line = "だったら次は俺も参加で──"

[[dialogue]]
speaker = "ウズメイア"
# 「はい、決定♪　ちなみに次はみんなで下着を買いに行くことになってるから」
line = "「はい、決定♪　ちなみに次はみんなで下着を買いに行くことになってるから」"

[[dialogue]]
speaker = "ウズメイア"
# 「あたしのは会長くんに選んでもらうからお願いだし♪」
line = "「あたしのは会長くんに選んでもらうからお願いだし♪」"

[[dialogue]]
speaker = "unk"
# それは女の子だけで行ってきて！
line = "それは女の子だけで行ってきて！"

[[dialogue]]
speaker = "unk"
# 前言撤回！
line = "前言撤回！"

[[dialogue]]
speaker = "ウズメイア"
# 「あはは、もう言質を取ったから遅いし～♪」
line = "「あはは、もう言質を取ったから遅いし～♪」"

[[dialogue]]
speaker = "unk"
# と、そんなわけで次は俺も３人に付き合って買い物に出かけることになった。
line = "と、そんなわけで次は俺も３人に付き合って買い物に出かけることになった。"

[[dialogue]]
speaker = "unk"
# 何とか下着売り場に引っ張り込まれるという事態だけは回避して──
line = "何とか下着売り場に引っ張り込まれるという事態だけは回避して──"

[[dialogue]]
speaker = "unk"
# そして俺はウズメから聞いた話だけでなく、３人の打ち解けた様子を実際に目の当たりにすることが出来たのだった。
line = "そして俺はウズメから聞いた話だけでなく、３人の打ち解けた様子を実際に目の当たりにすることが出来たのだった。"
