[[dialogue]]
speaker = "unk"
# トワちゃんと恋人になってから、自宅に招くことが増えた。
line = "トワちゃんと恋人になってから、自宅に招くことが増えた。"

[[dialogue]]
speaker = "トワ先生"
# 「ごめんねー、うちにはメイプルちゃんがいるから」
line = "「ごめんねー、うちにはメイプルちゃんがいるから」"

[[dialogue]]
speaker = "トワ先生"
# 「いちゃいちゃしてもいいよって言ってくれたけど、やっぱり落ち着かないよね」
line = "「いちゃいちゃしてもいいよって言ってくれたけど、やっぱり落ち着かないよね」"

[[dialogue]]
speaker = "トワ先生"
# 「それに、メイプルちゃんの教育上よくないことも……多いし……」
line = "「それに、メイプルちゃんの教育上よくないことも……多いし……」"

[[dialogue]]
speaker = "クロト"
# 「そうだね。夫婦がすることもしてる訳だから」
line = "「そうだね。夫婦がすることもしてる訳だから」"

[[dialogue]]
speaker = "トワ先生"
# 「う、うん……キスしてるとことか、絶対見せちゃダメだよね……」
line = "「う、うん……キスしてるとことか、絶対見せちゃダメだよね……」"

[[dialogue]]
speaker = "トワ先生"
# 「…………ちゅっ<emoji=heart04>」
line = "「…………ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「えへへ、そうそう、こういうの。メイプルちゃんにはまだ早いもん」
line = "「えへへ、そうそう、こういうの。メイプルちゃんにはまだ早いもん」"

[[dialogue]]
speaker = "クロト"
# 「なら、その先はもっと教育上よくないか」
line = "「なら、その先はもっと教育上よくないか」"

[[dialogue]]
speaker = "トワ先生"
# 「うん、だからこうして、またキミの家にお邪魔しちゃうんだよね」
line = "「うん、だからこうして、またキミの家にお邪魔しちゃうんだよね」"

[[dialogue]]
speaker = "トワ先生"
# 「へ、変身っ♪」
line = "「へ、変身っ♪」"

[[dialogue]]
speaker = "トワ先生"
# 「じゃーん、キミが大好きな、ウェディングフォームだよ♪」
line = "「じゃーん、キミが大好きな、ウェディングフォームだよ♪」"

[[dialogue]]
speaker = "トワ先生"
# 「この前言ってたよね、次はドレス姿でえっちしようねって」
line = "「この前言ってたよね、次はドレス姿でえっちしようねって」"

[[dialogue]]
speaker = "クロト"
# 「そうだけど、いいの？」
line = "「そうだけど、いいの？」"

[[dialogue]]
speaker = "トワ先生"
# 「いいに決まってるよ。だって、今のわたしはキミのお嫁さんなんだから」
line = "「いいに決まってるよ。だって、今のわたしはキミのお嫁さんなんだから」"

[[dialogue]]
speaker = "トワ先生"
# 「ベッドに行こ？　今日は時間が許す限り、いちゃいちゃハメハメしようね<emoji=heart04>」
line = "「ベッドに行こ？　今日は時間が許す限り、いちゃいちゃハメハメしようね<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んんっ……はぁぁっ……見て、まだ触ってもないのに、こんなに濡れちゃってる……」
line = "「んんっ……はぁぁっ……見て、まだ触ってもないのに、こんなに濡れちゃってる……」"

[[dialogue]]
speaker = "トワ先生"
# 「キミとセックス出来るって思っただけで、もうこんなになっちゃった。何度もして、すっかりチ○ポの気持ちよさ、覚えちゃったみたい」
line = "「キミとセックス出来るって思っただけで、もうこんなになっちゃった。何度もして、すっかりチ○ポの気持ちよさ、覚えちゃったみたい」"

[[dialogue]]
speaker = "トワ先生"
# 「ふふっ、キミもわたしのおま○この感触、思い出しちゃったの？　もう、チ○ポをこんなにパンパンに膨らませちゃって……先っぽからえっちなぬるぬるも出ちゃってるね」
line = "「ふふっ、キミもわたしのおま○この感触、思い出しちゃったの？　もう、チ○ポをこんなにパンパンに膨らませちゃって……先っぽからえっちなぬるぬるも出ちゃってるね」"

[[dialogue]]
speaker = "トワ先生"
# 「最初にフェラチオしたいなって思ってたけど、もう待ちきれない感じだね。あっ、心配しないで、どうせ何度もすることになるんだから、後のお楽しみだよ<emoji=heart04>」
line = "「最初にフェラチオしたいなって思ってたけど、もう待ちきれない感じだね。あっ、心配しないで、どうせ何度もすることになるんだから、後のお楽しみだよ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「もー、わたしにお口でしてもらうの想像しちゃったの？　毎回キミがして欲しがるから、わたしも自主練したんだよ。おもちゃのチ○ポをじゅぽじゅぽして」
line = "「もー、わたしにお口でしてもらうの想像しちゃったの？　毎回キミがして欲しがるから、わたしも自主練したんだよ。おもちゃのチ○ポをじゅぽじゅぽして」"

[[dialogue]]
speaker = "トワ先生"
# 「わわっ、すごいビクンってしたぁ<emoji=heart04>　そんなに興奮しちゃったの？」
line = "「わわっ、すごいビクンってしたぁ<emoji=heart04>　そんなに興奮しちゃったの？」"

[[dialogue]]
speaker = "トワ先生"
# 「お口よりも……ここの方が気持ちいいんだけどな～」
line = "「お口よりも……ここの方が気持ちいいんだけどな～」"

[[dialogue]]
speaker = "トワ先生"
# 「ほら見て～、キミ専用のお嫁さんま○こだよ<emoji=heart04>　ちっちゃい穴だけど、何度もセックスしてもらったおかげで、キミのおっきなチ○ポだって根元まで全部入るんだから」
line = "「ほら見て～、キミ専用のお嫁さんま○こだよ<emoji=heart04>　ちっちゃい穴だけど、何度もセックスしてもらったおかげで、キミのおっきなチ○ポだって根元まで全部入るんだから」"

[[dialogue]]
speaker = "トワ先生"
# 「ぬるぬるのヒダヒダがとっても気持ちいいよ～。ほら、チ○ポをハメて好きなだけにゅるにゅるにゅぽにゅぽしちゃおう？」
line = "「ぬるぬるのヒダヒダがとっても気持ちいいよ～。ほら、チ○ポをハメて好きなだけにゅるにゅるにゅぽにゅぽしちゃおう？」"

[[dialogue]]
speaker = "トワ先生"
# 「ていうか、もうわたしのほうが待ちきれないよ。もうハメハメしちゃうね～<emoji=heart04>」
line = "「ていうか、もうわたしのほうが待ちきれないよ。もうハメハメしちゃうね～<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んおおおっ<emoji=heart04>　おおんっ<emoji=heart04>　はぁっはぁっ、キミのおっきすぎるチ○ポ……ぬぷぷぷ～～って簡単に入っちゃった<emoji=heart04>」
line = "「んおおおっ<emoji=heart04>　おおんっ<emoji=heart04>　はぁっはぁっ、キミのおっきすぎるチ○ポ……ぬぷぷぷ～～って簡単に入っちゃった<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「えへへ、入る時ちょっと変な声出ちゃったね。サイズが違いすぎて、おま○こに刺激が強すぎるせいなんだから」
line = "「えへへ、入る時ちょっと変な声出ちゃったね。サイズが違いすぎて、おま○こに刺激が強すぎるせいなんだから」"

[[dialogue]]
speaker = "トワ先生"
# 「セックスの最後の方とか、はしたなくおんおん言っちゃってるかもしれないけど、ああいうの恥ずかしいんだから」
line = "「セックスの最後の方とか、はしたなくおんおん言っちゃってるかもしれないけど、ああいうの恥ずかしいんだから」"

[[dialogue]]
speaker = "トワ先生"
# 「キミがそういうので興奮するのはわかってるけどねー。可愛いお嫁さんとしては、あんまり聞かせたくない声かなって」
line = "「キミがそういうので興奮するのはわかってるけどねー。可愛いお嫁さんとしては、あんまり聞かせたくない声かなって」"

[[dialogue]]
speaker = "クロト"
# 「でも、そんなトワちゃんの声にめちゃくちゃ興奮するんだよね」
line = "「でも、そんなトワちゃんの声にめちゃくちゃ興奮するんだよね」"

[[dialogue]]
speaker = "トワ先生"
# 「んんんっ！？　ちょっ、チ○ポぐうぅ～～っておっきくなったんだけど」
line = "「んんんっ！？　ちょっ、チ○ポぐうぅ～～っておっきくなったんだけど」"

[[dialogue]]
speaker = "トワ先生"
# 「もー、絶対ダメとは言わないけど……お嫁さんの気持ちも考えて、お手柔らかにね<emoji=heart04>」
line = "「もー、絶対ダメとは言わないけど……お嫁さんの気持ちも考えて、お手柔らかにね<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「それはこっちのセリフだよ。トワちゃんこそ、すっかり腰振りが上達して、めちゃくちゃ激しくチ○ポしごきしてくるんだから」
line = "「それはこっちのセリフだよ。トワちゃんこそ、すっかり腰振りが上達して、めちゃくちゃ激しくチ○ポしごきしてくるんだから」"

[[dialogue]]
speaker = "トワ先生"
# 「だ、だってセックス気持ちいいんだもん。あんな気持ちいいことずっと知らなかったなんて勿体ないよね」
line = "「だ、だってセックス気持ちいいんだもん。あんな気持ちいいことずっと知らなかったなんて勿体ないよね」"

[[dialogue]]
speaker = "トワ先生"
# 「もちろんわたしだってわかってるよ。あんまり激しくすると、すぐドピュってしちゃうもんね。いっぱい出し入れを楽しみたいなら、手加減する必要があるから」
line = "「もちろんわたしだってわかってるよ。あんまり激しくすると、すぐドピュってしちゃうもんね。いっぱい出し入れを楽しみたいなら、手加減する必要があるから」"

[[dialogue]]
speaker = "クロト"
# 「じゃあ……そろそろお願いしていい？　最初は手加減モードで、トワちゃんのスケベま○こを愉しませてよ」
line = "「じゃあ……そろそろお願いしていい？　最初は手加減モードで、トワちゃんのスケベま○こを愉しませてよ」"

[[dialogue]]
speaker = "トワ先生"
# 「うん、わかった。わたしも我慢できなくなってたから……動くね？」
line = "「うん、わかった。わたしも我慢できなくなってたから……動くね？」"

[[dialogue]]
speaker = "トワ先生"
# 「んあっ<emoji=heart04>　あぁんっ、はぁっ<emoji=heart04>　やっぱりチ○ポ気持ちいい……自分でするのとは全然違うよぉ<emoji=heart04>」
line = "「んあっ<emoji=heart04>　あぁんっ、はぁっ<emoji=heart04>　やっぱりチ○ポ気持ちいい……自分でするのとは全然違うよぉ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「あぁんっ、あっ、あっ、だめっ、腰が勝手に動いちゃうっ<emoji=heart04>　最初だからゆっくりぬぽぬぽしたかったのにぃ～」
line = "「あぁんっ、あっ、あっ、だめっ、腰が勝手に動いちゃうっ<emoji=heart04>　最初だからゆっくりぬぽぬぽしたかったのにぃ～」"

[[dialogue]]
speaker = "トワ先生"
# 「ご、ごめんねっ、すぐに激しくしちゃうかも、だけど。はぁっ、はぁっ、その分いっぱいおま○こで気持ちよくするね？　お嫁さんのえっちな肉穴満喫していいよ<emoji=heart04>」
line = "「ご、ごめんねっ、すぐに激しくしちゃうかも、だけど。はぁっ、はぁっ、その分いっぱいおま○こで気持ちよくするね？　お嫁さんのえっちな肉穴満喫していいよ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んふぅ～～～っ<emoji=heart04>　はぁんっ、あぁっ！　この体勢つらいけど、でも、キミのチ○ポが奥までぐう～～って刺さるから……気持ちいいよぉ<emoji=heart04>」
line = "「んふぅ～～～っ<emoji=heart04>　はぁんっ、あぁっ！　この体勢つらいけど、でも、キミのチ○ポが奥までぐう～～って刺さるから……気持ちいいよぉ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「おま○ことチ○ポ、長さが違うのに……無理矢理全部押し込んじゃう……んぅっ<emoji=heart04>　ううっ、奥のとこ、ずるい～<emoji=heart04>」
line = "「おま○ことチ○ポ、長さが違うのに……無理矢理全部押し込んじゃう……んぅっ<emoji=heart04>　ううっ、奥のとこ、ずるい～<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「ね、ねえキミも……動いていいんだよ？　下からわたしのおま○こいじめて<emoji=heart04>」
line = "「ね、ねえキミも……動いていいんだよ？　下からわたしのおま○こいじめて<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「俺のお嫁さんはえっちだなぁ。いいよ、トワちゃんの大好きなとこ、いっぱいズボズボしてあげる」
line = "「俺のお嫁さんはえっちだなぁ。いいよ、トワちゃんの大好きなとこ、いっぱいズボズボしてあげる」"

[[dialogue]]
speaker = "トワ先生"
# 「うんっ……来てぇ……わたしをセックス大好きにさせちゃったこのチ○ポでいっぱい突いてぇ<emoji=heart04>」
line = "「うんっ……来てぇ……わたしをセックス大好きにさせちゃったこのチ○ポでいっぱい突いてぇ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んおっ<emoji=heart04>　は、激しいっ<emoji=heart04>　そこっ<emoji=heart04>　もっと突いてぇ<emoji=heart04>　あぁっ、あんっ、あんっ、はぁぁっ、んあっ<emoji=heart04>　セックス気持ちいい～<emoji=heart04>　キミのチ○ポ好きぃ<emoji=heart04>」
line = "「んおっ<emoji=heart04>　は、激しいっ<emoji=heart04>　そこっ<emoji=heart04>　もっと突いてぇ<emoji=heart04>　あぁっ、あんっ、あんっ、はぁぁっ、んあっ<emoji=heart04>　セックス気持ちいい～<emoji=heart04>　キミのチ○ポ好きぃ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「ご、ごめんね、えっちなお嫁さんで。でもでもっ、気持ちいいこと我慢できなくって。んうっ！　ふぅぅ～～っ、はぁっ、あぁん<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　あぁん<emoji=heart04>」
line = "「ご、ごめんね、えっちなお嫁さんで。でもでもっ、気持ちいいこと我慢できなくって。んうっ！　ふぅぅ～～っ、はぁっ、あぁん<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　あぁん<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「お嫁さんはみんな、こんなえっちなことしてるのかなぁ？　一番恥ずかしくてえっちなとこを夢中でこすりっこして<emoji=heart04>」
line = "「お嫁さんはみんな、こんなえっちなことしてるのかなぁ？　一番恥ずかしくてえっちなとこを夢中でこすりっこして<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「でもっ、こんな気持ちよかったら、毎日だってセックスしちゃうよね<emoji=heart04>」
line = "「でもっ、こんな気持ちよかったら、毎日だってセックスしちゃうよね<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「夫婦の秘密の夜の営みっ<emoji=heart04>　恥ずかしいとこと気持ちいいとこ全部っ、絶対見せられない全部をさらけ出し合って……<emoji=heart04>」
line = "「夫婦の秘密の夜の営みっ<emoji=heart04>　恥ずかしいとこと気持ちいいとこ全部っ、絶対見せられない全部をさらけ出し合って……<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「こんなのっ……すればするほど好きになっちゃうよぉ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「こんなのっ……すればするほど好きになっちゃうよぉ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「もっと俺のこと好きになってよ。俺も今よりずっとトワちゃんを好きになるから」
line = "「もっと俺のこと好きになってよ。俺も今よりずっとトワちゃんを好きになるから」"

[[dialogue]]
speaker = "トワ先生"
# 「うんっ、好きになる<emoji=heart04>　現在進行形で好きになってるからぁ<emoji=heart04>　わたしを好きって言ってくれるならっ、いっぱい愛して<emoji=heart04>　チ○ポでわたしを夢中にさせてっ<emoji=heart04>」
line = "「うんっ、好きになる<emoji=heart04>　現在進行形で好きになってるからぁ<emoji=heart04>　わたしを好きって言ってくれるならっ、いっぱい愛して<emoji=heart04>　チ○ポでわたしを夢中にさせてっ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んほぉぉぉっ<emoji=heart04>　おおっ<emoji=heart04>　おんっ<emoji=heart04>　すごいっ<emoji=heart04>　それダメっ<emoji=heart04>　やぁんっ、声出ちゃうっ<emoji=heart04>　恥ずかしいから聞かないでぇぇっ<emoji=heart04>」
line = "「んほぉぉぉっ<emoji=heart04>　おおっ<emoji=heart04>　おんっ<emoji=heart04>　すごいっ<emoji=heart04>　それダメっ<emoji=heart04>　やぁんっ、声出ちゃうっ<emoji=heart04>　恥ずかしいから聞かないでぇぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んぐうっ、気持ちよすぎるよぉ<emoji=heart04>　キミのチ○ポがずりゅっ、ずりゅっ、てわたしの敏感な内側をえぐって……これ好きだからダメなのにぃぃ<emoji=heart04>」
line = "「んぐうっ、気持ちよすぎるよぉ<emoji=heart04>　キミのチ○ポがずりゅっ、ずりゅっ、てわたしの敏感な内側をえぐって……これ好きだからダメなのにぃぃ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「ね、ねえ、煽ったのはわたしだけど、やっぱりゆっくりセックスしよ？　こんなのすぐ終わっちゃうから」
line = "「ね、ねえ、煽ったのはわたしだけど、やっぱりゆっくりセックスしよ？　こんなのすぐ終わっちゃうから」"

[[dialogue]]
speaker = "クロト"
# 「すぐ終わっても、何度もすればいいから。いつもそうでしょ？」
line = "「すぐ終わっても、何度もすればいいから。いつもそうでしょ？」"

[[dialogue]]
speaker = "トワ先生"
# 「う、うんっ……じゃあ……いいよ？　激しくしていいから、その代わり、その、キミのザーメンいっぱい出してね<emoji=heart04>」
line = "「う、うんっ……じゃあ……いいよ？　激しくしていいから、その代わり、その、キミのザーメンいっぱい出してね<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「わたしのおなかがぽっこりするくらいっ、出してくれなきゃダメなんだからっ<emoji=heart04>」
line = "「わたしのおなかがぽっこりするくらいっ、出してくれなきゃダメなんだからっ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「はぁんっ<emoji=heart04>　あぁっ<emoji=heart04>　あんっ<emoji=heart04>　やっぱりすごいぃ<emoji=heart04>　キミの本気を感じちゃうっ、わたしのおま○こ全部、ごしごしされちゃって……これ好きぃ<emoji=heart04>　大好きぃ<emoji=heart04>」
line = "「はぁんっ<emoji=heart04>　あぁっ<emoji=heart04>　あんっ<emoji=heart04>　やっぱりすごいぃ<emoji=heart04>　キミの本気を感じちゃうっ、わたしのおま○こ全部、ごしごしされちゃって……これ好きぃ<emoji=heart04>　大好きぃ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「もっと突いて<emoji=heart04>　激しくしていいよ<emoji=heart04>　お嫁さんま○こが壊れちゃうくらいいっぱい愛して<emoji=heart04>　んあぁぁっ<emoji=heart04>　はぁんっ<emoji=heart04>　あっ、嬉しい<emoji=heart04>　嬉しいよぉ<emoji=heart04>」
line = "「もっと突いて<emoji=heart04>　激しくしていいよ<emoji=heart04>　お嫁さんま○こが壊れちゃうくらいいっぱい愛して<emoji=heart04>　んあぁぁっ<emoji=heart04>　はぁんっ<emoji=heart04>　あっ、嬉しい<emoji=heart04>　嬉しいよぉ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「こんなのもぉ、気持ちよすぎておかしくなっちゃう<emoji=heart04>　キミとはじめてえっちするまで、こんなの知らなかったのに<emoji=heart04>　もう戻れないんだからぁ<emoji=heart04>」
line = "「こんなのもぉ、気持ちよすぎておかしくなっちゃう<emoji=heart04>　キミとはじめてえっちするまで、こんなの知らなかったのに<emoji=heart04>　もう戻れないんだからぁ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んおおおおおっ<emoji=heart04>　おほぉっ<emoji=heart04>　おおんっ<emoji=heart04>　おっ<emoji=heart04>　おっ<emoji=heart04>　おおおおっ<emoji=heart04>　そこえぐっちゃダメぇ<emoji=heart04>　すぐイク<emoji=heart04>　イっちゃうからああぁぁぁんっ<emoji=heart04>」
line = "「んおおおおおっ<emoji=heart04>　おほぉっ<emoji=heart04>　おおんっ<emoji=heart04>　おっ<emoji=heart04>　おっ<emoji=heart04>　おおおおっ<emoji=heart04>　そこえぐっちゃダメぇ<emoji=heart04>　すぐイク<emoji=heart04>　イっちゃうからああぁぁぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「わたし先生なのにっ<emoji=heart04>　スケベなお嫁さんだけどっ、みんなの先生なのにっ<emoji=heart04>　こんなっ、品の無い声出してるとこ、絶対知られちゃダメっっ<emoji=heart04>」
line = "「わたし先生なのにっ<emoji=heart04>　スケベなお嫁さんだけどっ、みんなの先生なのにっ<emoji=heart04>　こんなっ、品の無い声出してるとこ、絶対知られちゃダメっっ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んおっ<emoji=heart04>　ちょっ、声出させようとしないでぇ<emoji=heart04>　ほんとに恥ずかしいんだからぁ<emoji=heart04>」
line = "「んおっ<emoji=heart04>　ちょっ、声出させようとしないでぇ<emoji=heart04>　ほんとに恥ずかしいんだからぁ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「あっ、あっ、あぁぁぁんっっ<emoji=heart04>　あ、ありがとう……さっきのとこが弱点だから……って、もう何度もセックスしてるから全部知ってるよね？」
line = "「あっ、あっ、あぁぁぁんっっ<emoji=heart04>　あ、ありがとう……さっきのとこが弱点だから……って、もう何度もセックスしてるから全部知ってるよね？」"

[[dialogue]]
speaker = "トワ先生"
# 「とにかくっ、射精しそうになるまで今のとこはダメだから。他の、えっちなヒダヒダでチ○ポごしごしこすって気持ちよくなってね<emoji=heart04>」
line = "「とにかくっ、射精しそうになるまで今のとこはダメだから。他の、えっちなヒダヒダでチ○ポごしごしこすって気持ちよくなってね<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「はぁんっ<emoji=heart04>　あぁっ<emoji=heart04>　あんっ<emoji=heart04>　気持ちいい、よぉ<emoji=heart04>　やっぱりキミとするセックス好きぃ<emoji=heart04>　オナニーなんかじゃもう満足できないよぉ<emoji=heart04>」
line = "「はぁんっ<emoji=heart04>　あぁっ<emoji=heart04>　あんっ<emoji=heart04>　気持ちいい、よぉ<emoji=heart04>　やっぱりキミとするセックス好きぃ<emoji=heart04>　オナニーなんかじゃもう満足できないよぉ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「早く……毎日セックス出来るようになったらいいのにっ<emoji=heart04>　そしたら……朝も夜もずっと愛し合えるのに<emoji=heart04>　昼間は、キミの精液おなかに入れたまんまで……<emoji=heart04>」
line = "「早く……毎日セックス出来るようになったらいいのにっ<emoji=heart04>　そしたら……朝も夜もずっと愛し合えるのに<emoji=heart04>　昼間は、キミの精液おなかに入れたまんまで……<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「あぁん、もうっ、えっちなことばっかり考えちゃう<emoji=heart04>　んふっ、ふううぅっ<emoji=heart04>　チ○ポ入れてもらってると、思考が全部ピンク色になって……ダメになっちゃうよぉ<emoji=heart04>」
line = "「あぁん、もうっ、えっちなことばっかり考えちゃう<emoji=heart04>　んふっ、ふううぅっ<emoji=heart04>　チ○ポ入れてもらってると、思考が全部ピンク色になって……ダメになっちゃうよぉ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「ねえ、もっと突いて。わたしがおかしくなるくらい、奥いじめていいから<emoji=heart04>　お嫁さんま○こでじゅぽじゅぽして……いつもみたいにたっぷりザーメン出してぇっ<emoji=heart04>」
line = "「ねえ、もっと突いて。わたしがおかしくなるくらい、奥いじめていいから<emoji=heart04>　お嫁さんま○こでじゅぽじゅぽして……いつもみたいにたっぷりザーメン出してぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んおおっ<emoji=heart04>　おおっ<emoji=heart04>　おんっ<emoji=heart04>　ぎもぢいいいぃ<emoji=heart04>　イグッ<emoji=heart04>　こんなのすぐイグ<emoji=heart04>　イっぢゃううう～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「んおおっ<emoji=heart04>　おおっ<emoji=heart04>　おんっ<emoji=heart04>　ぎもぢいいいぃ<emoji=heart04>　イグッ<emoji=heart04>　こんなのすぐイグ<emoji=heart04>　イっぢゃううう～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「早くっ<emoji=heart04>　キミも早く出してぇぇっっ<emoji=heart04>　わたしっ、もうそんなに我慢できないからぁ<emoji=heart04>　んうっ<emoji=heart04>　もうダメっ<emoji=heart04>　んあぁぁぁぁっ<emoji=heart04>　はぁんっ<emoji=heart04>」
line = "「早くっ<emoji=heart04>　キミも早く出してぇぇっっ<emoji=heart04>　わたしっ、もうそんなに我慢できないからぁ<emoji=heart04>　んうっ<emoji=heart04>　もうダメっ<emoji=heart04>　んあぁぁぁぁっ<emoji=heart04>　はぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んほおおおおぉぉっ<emoji=heart04>　おおんっ<emoji=heart04>　おっ<emoji=heart04>　おっ<emoji=heart04>　しゅごいっぃぃ～～<emoji=heart04>　そこらめぇっ<emoji=heart04>　らめなのおおぉぉっっ<emoji=heart04>」
line = "「んほおおおおぉぉっ<emoji=heart04>　おおんっ<emoji=heart04>　おっ<emoji=heart04>　おっ<emoji=heart04>　しゅごいっぃぃ～～<emoji=heart04>　そこらめぇっ<emoji=heart04>　らめなのおおぉぉっっ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「イグぅ<emoji=heart04>　イっぢゃうぅぅ～～～っ<emoji=heart04>　まだ？　ザーメンまだなのぉ？　出してっ<emoji=heart04>　ザーメン出してっ<emoji=heart04>　早く射精しでぇぇぇ～～～～っ<emoji=heart04>」
line = "「イグぅ<emoji=heart04>　イっぢゃうぅぅ～～～っ<emoji=heart04>　まだ？　ザーメンまだなのぉ？　出してっ<emoji=heart04>　ザーメン出してっ<emoji=heart04>　早く射精しでぇぇぇ～～～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「もう無理ぃぃ～～～っ<emoji=heart04>　イグっ<emoji=heart04>　イギ過ぎちゃうぅぅぅ<emoji=heart04>　気持ちよくて馬鹿になっちゃうぅ～～っ<emoji=heart04>」
line = "「もう無理ぃぃ～～～っ<emoji=heart04>　イグっ<emoji=heart04>　イギ過ぎちゃうぅぅぅ<emoji=heart04>　気持ちよくて馬鹿になっちゃうぅ～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んおぉんっ<emoji=heart04>　おほっ<emoji=heart04>　ほおおっ<emoji=heart04>　おっ<emoji=heart04>　おっ<emoji=heart04>　んおおおおおお～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「んおぉんっ<emoji=heart04>　おほっ<emoji=heart04>　ほおおっ<emoji=heart04>　おっ<emoji=heart04>　おっ<emoji=heart04>　んおおおおおお～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「おっきいの来ちゃう<emoji=heart04>　イグっ<emoji=heart04>　イグイグイグぅっ<emoji=heart04>　イっグぅぅ～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「おっきいの来ちゃう<emoji=heart04>　イグっ<emoji=heart04>　イグイグイグぅっ<emoji=heart04>　イっグぅぅ～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「ふやぁぁっ<emoji=heart04>　はぁっ<emoji=heart04>　はぁっ<emoji=heart04>　すっごい……ザーメンびゅるびゅる出てるぅ……<emoji=heart04>」
line = "「ふやぁぁっ<emoji=heart04>　はぁっ<emoji=heart04>　はぁっ<emoji=heart04>　すっごい……ザーメンびゅるびゅる出てるぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「今日最初の射精だから……んぅっ<emoji=heart04>　量がすごいよぉ<emoji=heart04>　こんなに出されたら、お嫁さんのおなかすぐいっぱいになっちゃうよぉ<emoji=heart04>」
line = "「今日最初の射精だから……んぅっ<emoji=heart04>　量がすごいよぉ<emoji=heart04>　こんなに出されたら、お嫁さんのおなかすぐいっぱいになっちゃうよぉ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「ううっ……ふぁぁぁっ<emoji=heart04>　はぁんっ<emoji=heart04>　びちゃびちゃ出てるね……んっ、チ○ポも嬉しそうに射精してるよ……んっ、お嫁さんま○こ、気持ちよかった？」
line = "「ううっ……ふぁぁぁっ<emoji=heart04>　はぁんっ<emoji=heart04>　びちゃびちゃ出てるね……んっ、チ○ポも嬉しそうに射精してるよ……んっ、お嫁さんま○こ、気持ちよかった？」"

[[dialogue]]
speaker = "クロト"
# 「めっっちゃくちゃ……気持ちよかった……やっぱりトワちゃんのおま○こは最高だよ……」
line = "「めっっちゃくちゃ……気持ちよかった……やっぱりトワちゃんのおま○こは最高だよ……」"

[[dialogue]]
speaker = "トワ先生"
# 「えへへ～、最初にしてからずっと、夢中だもんね<emoji=heart04>　わたしも……同じくらいキミのチ○ポに夢中なんだけど<emoji=heart04>」
line = "「えへへ～、最初にしてからずっと、夢中だもんね<emoji=heart04>　わたしも……同じくらいキミのチ○ポに夢中なんだけど<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「んんっ……まだ出てるね……もう、そんなに気持ちよかったの？　こんなに貯め込んじゃうなら、心配だから毎日ヌいてあげないとダメかもね<emoji=heart04>」
line = "「んんっ……まだ出てるね……もう、そんなに気持ちよかったの？　こんなに貯め込んじゃうなら、心配だから毎日ヌいてあげないとダメかもね<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「はぁ……はぁ……ふぁぁぁっっ……んっ、そろそろ……射精終わりそうだね……ふふっ、わかるよ、もう何度もおなかに出してもらったもん<emoji=heart04>」
line = "「はぁ……はぁ……ふぁぁぁっっ……んっ、そろそろ……射精終わりそうだね……ふふっ、わかるよ、もう何度もおなかに出してもらったもん<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「やんっ、抜けちゃうっ……んんっ、やっぱり多すぎてどろぉって漏らしちゃった……もー、全部受け止めてあげたかったのにぃ<emoji=heart04>」
line = "「やんっ、抜けちゃうっ……んんっ、やっぱり多すぎてどろぉって漏らしちゃった……もー、全部受け止めてあげたかったのにぃ<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「はぁ……はぁ……でも……漏らしちゃった分はまた注いでもらえばいいし……」
line = "「はぁ……はぁ……でも……漏らしちゃった分はまた注いでもらえばいいし……」"

[[dialogue]]
speaker = "トワ先生"
# 「ねぇ……今日もまだ大丈夫だよね？　もっとキミとセックスしたくて……ダメ？」
line = "「ねぇ……今日もまだ大丈夫だよね？　もっとキミとセックスしたくて……ダメ？」"

[[dialogue]]
speaker = "クロト"
# 「ダメじゃないよ。もちろん、もっとトワちゃんのお嫁さんま○こに射精するから覚悟してね」
line = "「ダメじゃないよ。もちろん、もっとトワちゃんのお嫁さんま○こに射精するから覚悟してね」"

[[dialogue]]
speaker = "トワ先生"
# 「う、うん……改めてそう言われるとちょっと不安になっちゃうけど、でも激しいの、期待しちゃうんだから<emoji=heart04>」
line = "「う、うん……改めてそう言われるとちょっと不安になっちゃうけど、でも激しいの、期待しちゃうんだから<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「今日は何回セックス出来るのかな～？」
line = "「今日は何回セックス出来るのかな～？」"

[[dialogue]]
speaker = "トワ先生"
# 「まあ、それはそれとして……またキミにいっぱい変な声出させられちゃったね<emoji=heart04>　気持ちよかったからいいけど、ちょっぴり怒ってるんだから<emoji=heart04>」
line = "「まあ、それはそれとして……またキミにいっぱい変な声出させられちゃったね<emoji=heart04>　気持ちよかったからいいけど、ちょっぴり怒ってるんだから<emoji=heart04>」"

[[dialogue]]
speaker = "トワ先生"
# 「だから次は先生が、キミが大好きなフェラチオで、とことんチ○ポいじめしちゃうんだからねっ<emoji=heart04>　覚悟するよーに<emoji=heart04>」
line = "「だから次は先生が、キミが大好きなフェラチオで、とことんチ○ポいじめしちゃうんだからねっ<emoji=heart04>　覚悟するよーに<emoji=heart04>」"
