[[dialogue]]
speaker = "unk"
# 第２話,世間知らずの占い師,P
line = "第２話,世間知らずの占い師,P"

[[dialogue]]
speaker = "unk"
# レゾフは極寒の土地であるがゆえに、夜空が人間界よりも澄んで見えるのが特徴だ。
line = "レゾフは極寒の土地であるがゆえに、夜空が人間界よりも澄んで見えるのが特徴だ。"

[[dialogue]]
speaker = "unk"
# 俺とトリシャさんとフィオナの３人で、夜の天体観測をすることになった。
line = "俺とトリシャさんとフィオナの３人で、夜の天体観測をすることになった。"

[[dialogue]]
speaker = "フィオナ"
# 「お待たせしました、緋宮会長。温かいお芋のスープです」
line = "「お待たせしました、緋宮会長。温かいお芋のスープです」"

[[dialogue]]
speaker = "unk"
# お帰り、フィオナ
line = "お帰り、フィオナ"

[[dialogue]]
speaker = "トリシャ"
# 「そろそろお使いから戻ってくる頃だと思っていました……あの、私の分は……」
line = "「そろそろお使いから戻ってくる頃だと思っていました……あの、私の分は……」"

[[dialogue]]
speaker = "フィオナ"
# 「氷結ヨーグルトですよね。ちゃんと買ってきましたけれど、本当にこんな冷たいものでよろしかったのですか？」
line = "「氷結ヨーグルトですよね。ちゃんと買ってきましたけれど、本当にこんな冷たいものでよろしかったのですか？」"

[[dialogue]]
speaker = "フィオナ"
# 「ソフィアなんて『こんな寒い夜に正気ですか！？』と怯えていましたから……」
line = "「ソフィアなんて『こんな寒い夜に正気ですか！？』と怯えていましたから……」"

[[dialogue]]
speaker = "トリシャ"
# 「フフ……問題ない。私はどんなに寒い日でも、これを食べられる星の下に生まれているので……」
line = "「フフ……問題ない。私はどんなに寒い日でも、これを食べられる星の下に生まれているので……」"

[[dialogue]]
speaker = "トリシャ"
# 「良かったらフィオナさんも、どう……？　ヨーグルトを一口……」
line = "「良かったらフィオナさんも、どう……？　ヨーグルトを一口……」"

[[dialogue]]
speaker = "フィオナ"
# 「暖炉の前でならありがたくいただくのですが……」
line = "「暖炉の前でならありがたくいただくのですが……」"

[[dialogue]]
speaker = "トリシャ"
# 「それは残念……あむ。もぐ……フフ……体の芯から凍える感じがたまりませんね……」
line = "「それは残念……あむ。もぐ……フフ……体の芯から凍える感じがたまりませんね……」"

[[dialogue]]
speaker = "フィオナ"
# 「ど、独特な感性ですね、トリシャさん」
line = "「ど、独特な感性ですね、トリシャさん」"

[[dialogue]]
speaker = "トリシャ"
# 「フフフ。さてさて、それでは天体観測の時間です……」
line = "「フフフ。さてさて、それでは天体観測の時間です……」"

[[dialogue]]
speaker = "トリシャ"
# 「今はベテルギウス、シリウス、プロキオン……この３つが特に輝く時期であり……」
line = "「今はベテルギウス、シリウス、プロキオン……この３つが特に輝く時期であり……」"

[[dialogue]]
speaker = "トリシャ"
# 「──っと。星騎士のお２人には、わざわざ紹介する必要はなかったでしょうか……？」
line = "「──っと。星騎士のお２人には、わざわざ紹介する必要はなかったでしょうか……？」"

[[dialogue]]
speaker = "フィオナ"
# 「いえ。魔界の夜空で見ると、親しんだはずの星も輝きがまるで違いますから。説明、感謝いたします」
line = "「いえ。魔界の夜空で見ると、親しんだはずの星も輝きがまるで違いますから。説明、感謝いたします」"

[[dialogue]]
speaker = "トリシャ"
# 「フフ……それは重畳、です……お２人は戦いの日々で疲れているでしょうし……今夜は心行くまで星を眺めようではありませんか……」
line = "「フフ……それは重畳、です……お２人は戦いの日々で疲れているでしょうし……今夜は心行くまで星を眺めようではありませんか……」"

[[dialogue]]
speaker = "フィオナ"
# 「はい。楽しませていただきますね……っと、緋宮会長？　おくちのところ、スープが跳ねてますよ？」
line = "「はい。楽しませていただきますね……っと、緋宮会長？　おくちのところ、スープが跳ねてますよ？」"

[[dialogue]]
speaker = "unk"
# あれ、本当に？
line = "あれ、本当に？"

[[dialogue]]
speaker = "フィオナ"
# 「動かないでくださいね。ふき、ふき、ふき──はい。綺麗になりました」
line = "「動かないでくださいね。ふき、ふき、ふき──はい。綺麗になりました」"

[[dialogue]]
speaker = "トリシャ"
# 「な、な、なんと……！？」
line = "「な、な、なんと……！？」"

[[dialogue]]
speaker = "トリシャ"
# 「まさか……そんな……星のお告げでも、視えなかった事実が……目の前に……！？」
line = "「まさか……そんな……星のお告げでも、視えなかった事実が……目の前に……！？」"

[[dialogue]]
speaker = "フィオナ"
# 「トリシャさん？」
line = "「トリシャさん？」"

[[dialogue]]
speaker = "トリシャ"
# 「気づきませんでした……お２人の今の自然な動き、態度……これはまさに恋縁……前世から定められし、運命の番……」
line = "「気づきませんでした……お２人の今の自然な動き、態度……これはまさに恋縁……前世から定められし、運命の番……」"

[[dialogue]]
speaker = "フィオナ"
# 「つ、つがいっ！？　いったい何でそんな……私と緋宮会長は、そういう関係ではありませんよ！？」
line = "「つ、つがいっ！？　いったい何でそんな……私と緋宮会長は、そういう関係ではありませんよ！？」"

[[dialogue]]
speaker = "トリシャ"
# 「しかし実に自然に、ハンカチで口元を拭いて……」
line = "「しかし実に自然に、ハンカチで口元を拭いて……」"

[[dialogue]]
speaker = "トリシャ"
# 「これはもう婚約をしていてもおかしくないと……判断、したのですが……」
line = "「これはもう婚約をしていてもおかしくないと……判断、したのですが……」"

[[dialogue]]
speaker = "フィオナ"
# 「大げさです！　確かに、その、距離は少し近かったかもしれませんがっ……」
line = "「大げさです！　確かに、その、距離は少し近かったかもしれませんがっ……」"

[[dialogue]]
speaker = "トリシャ"
# 「そうだったの、ですか……私、師匠以外の方とお喋りしたことがほとんどなく……」
line = "「そうだったの、ですか……私、師匠以外の方とお喋りしたことがほとんどなく……」"

[[dialogue]]
speaker = "unk"
# トリシャさんの生い立ちって？
line = "トリシャさんの生い立ちって？"

[[dialogue]]
speaker = "トリシャ"
# 「出身は魔界のシャリオン地方、らしいのですが……不安定な情勢の時に産まれたので、親の顔も知らず……」
line = "「出身は魔界のシャリオン地方、らしいのですが……不安定な情勢の時に産まれたので、親の顔も知らず……」"

[[dialogue]]
speaker = "トリシャ"
# 「占星術師だったメラム……師匠に拾われ、各地を転々としながら占い師としての薫陶を授かり……」
line = "「占星術師だったメラム……師匠に拾われ、各地を転々としながら占い師としての薫陶を授かり……」"

[[dialogue]]
speaker = "トリシャ"
# 「１５の頃に独立して……フフ……それ以来、お２人が初めてできた友達です……」
line = "「１５の頃に独立して……フフ……それ以来、お２人が初めてできた友達です……」"

[[dialogue]]
speaker = "フィオナ"
# 「なるほど……大変な暮らしだったのですね」
line = "「なるほど……大変な暮らしだったのですね」"

[[dialogue]]
speaker = "unk"
# 対人関係に疎いのも仕方ない
line = "対人関係に疎いのも仕方ない"

[[dialogue]]
speaker = "トリシャ"
# 「占星術は、星の声を届けるだけ……なので。食べていく分には困らないのですが……」
line = "「占星術は、星の声を届けるだけ……なので。食べていく分には困らないのですが……」"

[[dialogue]]
speaker = "トリシャ"
# 「しかし数年来の謎が解けました……私の目から見て明らかに恋仲であるのに、星に訊ねると『友人』と出たりするので……」
line = "「しかし数年来の謎が解けました……私の目から見て明らかに恋仲であるのに、星に訊ねると『友人』と出たりするので……」"

[[dialogue]]
speaker = "トリシャ"
# 「師からもよく言われました。星以外のことにも興味を持ち、たくさんの友人を作り、レディとしての作法を身に付けろと……」
line = "「師からもよく言われました。星以外のことにも興味を持ち、たくさんの友人を作り、レディとしての作法を身に付けろと……」"

[[dialogue]]
speaker = "フィオナ"
# 「それで私たちの頼みに、友人になって欲しいとの返事をしたのですね」
line = "「それで私たちの頼みに、友人になって欲しいとの返事をしたのですね」"

[[dialogue]]
speaker = "トリシャ"
# 「頼むときは死ぬほど緊張しました……私とリンクしている<ruby=アルコル>おおぐま座８０番星</ruby>も、一際輝いていましたとも……」
line = "「頼むときは死ぬほど緊張しました……私とリンクしている<ruby>おおぐま座８０番星<rt>アルコル</rt></ruby>も、一際輝いていましたとも……」"

[[dialogue]]
speaker = "トリシャ"
# 「立派な占星術師になって……いつか、行方不明の師匠の居場所を、占いで突き止めたいから……が、頑張った……フ、フフ……」
line = "「立派な占星術師になって……いつか、行方不明の師匠の居場所を、占いで突き止めたいから……が、頑張った……フ、フフ……」"

[[dialogue]]
speaker = "フィオナ"
# 「いつの日か、きっとお師匠様に会えますよ。トリシャさん」
line = "「いつの日か、きっとお師匠様に会えますよ。トリシャさん」"

[[dialogue]]
speaker = "unk"
# うん、きっと会える
line = "うん、きっと会える"

[[dialogue]]
speaker = "トリシャ"
# 「ほんと……？　に、にへ……。お２人は、守護星の輝きに負けない優しさの持ち主……」
line = "「ほんと……？　に、にへ……。お２人は、守護星の輝きに負けない優しさの持ち主……」"

[[dialogue]]
speaker = "トリシャ"
# 「ホロスコープを通じなくてもわかる……視えますよ、お２人の輝かしい運命の道が……」
line = "「ホロスコープを通じなくてもわかる……視えますよ、お２人の輝かしい運命の道が……」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長。私、トリシャさんに協力したいです」
line = "「緋宮会長。私、トリシャさんに協力したいです」"

[[dialogue]]
speaker = "フィオナ"
# 「今でも優秀な占星術師なのですから、多くの人と触れ合い、絆を深めれば、さらなる精度の占いもできるようになるはずですよね」
line = "「今でも優秀な占星術師なのですから、多くの人と触れ合い、絆を深めれば、さらなる精度の占いもできるようになるはずですよね」"

[[dialogue]]
speaker = "トリシャ"
# 「にへ……ほ、ほめ過ぎ……」
line = "「にへ……ほ、ほめ過ぎ……」"

[[dialogue]]
speaker = "フィオナ"
# 「ですから、いつの日かトリシャさんを人間界へ招待しましょう。星見家、総出でお出迎えさせていただきます！」
line = "「ですから、いつの日かトリシャさんを人間界へ招待しましょう。星見家、総出でお出迎えさせていただきます！」"

[[dialogue]]
speaker = "トリシャ"
# 「……えっ？」
line = "「……えっ？」"

[[dialogue]]
speaker = "unk"
# 魔族であるトリシャさんを人間界へ連れて行くのは大変だろうけれど、俺にとっても恩人だ。協力するのはもちろん大賛成。
line = "魔族であるトリシャさんを人間界へ連れて行くのは大変だろうけれど、俺にとっても恩人だ。協力するのはもちろん大賛成。"

[[dialogue]]
speaker = "トリシャ"
# 「え、え、えっ……？　私が、人間界の……フィオナさんのお家、に……？」
line = "「え、え、えっ……？　私が、人間界の……フィオナさんのお家、に……？」"

[[dialogue]]
speaker = "unk"
# ただフィオナの家は、流星市国でも屈指の名家だ。トリシャさんは果たして、耐えられるのだろうか……？
line = "ただフィオナの家は、流星市国でも屈指の名家だ。トリシャさんは果たして、耐えられるのだろうか……？"
