[[dialogue]]
speaker = "unk"
# 第１話,特別な権利,P
line = "第１話,特別な権利,P"

[[dialogue]]
speaker = "ヘレナ"
# 「２人ともよく来てくれた。用件は他でもない、我々のウェディングフォームについて所感を聞こうと思ってな」
line = "「２人ともよく来てくれた。用件は他でもない、我々のウェディングフォームについて所感を聞こうと思ってな」"

[[dialogue]]
speaker = "ヘレナ"
# 「まずはヨミ、ウェディングフォームに」
line = "「まずはヨミ、ウェディングフォームに」"

[[dialogue]]
speaker = "ヨミ"
# 「は、はいっ！」
line = "「は、はいっ！」"

[[dialogue]]
speaker = "ヘレナ"
# 「……ふむ」
line = "「……ふむ」"

[[dialogue]]
speaker = "ヨミ"
# 「な、何か気になるところが……？」
line = "「な、何か気になるところが……？」"

[[dialogue]]
speaker = "ヘレナ"
# 「変身速度も申し分ない。星力の循環も順調のように見える。が……」
line = "「変身速度も申し分ない。星力の循環も順調のように見える。が……」"

[[dialogue]]
speaker = "ヘレナ"
# 「すこぶる可愛いな♪」
line = "「すこぶる可愛いな♪」"

[[dialogue]]
speaker = "ヨミ"
# 「こやぁんっ！？　勿体つけて出した感想がそれですか？」
line = "「こやぁんっ！？　勿体つけて出した感想がそれですか？」"

[[dialogue]]
speaker = "ヘレナ"
# 「何を言うか、可愛さは何より重要だぞ、ヨミヨミ」
line = "「何を言うか、可愛さは何より重要だぞ、ヨミヨミ」"

[[dialogue]]
speaker = "unk"
# 同感です！
line = "同感です！"

[[dialogue]]
speaker = "ヘレナ"
# 「ほら、恋人もこう申しているではないか」
line = "「ほら、恋人もこう申しているではないか」"

[[dialogue]]
speaker = "ヨミ"
# 「そ、そういうものなんでしょうか？　もしかして、私の認識が間違ってる？」
line = "「そ、そういうものなんでしょうか？　もしかして、私の認識が間違ってる？」"

[[dialogue]]
speaker = "ヘレナ"
# 「ただ戦闘力を求めるなら、花嫁装束でなくともよい。では何故、私がウェディングフォームを欲したのか。それ即ち」
line = "「ただ戦闘力を求めるなら、花嫁装束でなくともよい。では何故、私がウェディングフォームを欲したのか。それ即ち」"

[[dialogue]]
speaker = "ヘレナ"
# 「可愛いお嫁さんが見たかったからだ！！」
line = "「可愛いお嫁さんが見たかったからだ！！」"

[[dialogue]]
speaker = "ヨミ"
# 「そんなどうでもいい理由だったんですか……」
line = "「そんなどうでもいい理由だったんですか……」"

[[dialogue]]
speaker = "ヘレナ"
# 「だって悔しいじゃないか、星見家ばっかり可愛い花嫁さんを取り揃えて。これは不公平というものだ」
line = "「だって悔しいじゃないか、星見家ばっかり可愛い花嫁さんを取り揃えて。これは不公平というものだ」"

[[dialogue]]
speaker = "ヘレナ"
# 「であるから、九浄家としては星見家に対抗してウェディングフォームを研究、開発したというわけだ。理解したか？」
line = "「であるから、九浄家としては星見家に対抗してウェディングフォームを研究、開発したというわけだ。理解したか？」"

[[dialogue]]
speaker = "ヨミ"
# 「はい、このウェディングフォームにはそんな理由が……」
line = "「はい、このウェディングフォームにはそんな理由が……」"

[[dialogue]]
speaker = "ヨミ"
# 「って、割としょうもない理由なんですね。まあ、いつものことですけど」
line = "「って、割としょうもない理由なんですね。まあ、いつものことですけど」"

[[dialogue]]
speaker = "ヘレナ"
# 「そうぼやくな、ヨミヨミ。なんだかんだでよい思いができたのではないか？」
line = "「そうぼやくな、ヨミヨミ。なんだかんだでよい思いができたのではないか？」"

[[dialogue]]
speaker = "ヨミ"
# 「それは……確かに……はい、仰る通りですね。会長がもっと私のこと、見てくれるようになりましたし<emoji=heart04>」
line = "「それは……確かに……はい、仰る通りですね。会長がもっと私のこと、見てくれるようになりましたし<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 気付いてたの！？
line = "気付いてたの！？"

[[dialogue]]
speaker = "ヨミ"
# 「もちろん気付きますよ～！　もう、チラチラ視線を向けて……恋人同士なんだから、もっと堂々と見てもいいのに」
line = "「もちろん気付きますよ～！　もう、チラチラ視線を向けて……恋人同士なんだから、もっと堂々と見てもいいのに」"

[[dialogue]]
speaker = "ヘレナ"
# 「そう責めてやるな。ヨミヨミがかわゆすぎて、直視できなかったのであろうよ。それもまた男心、魔王の伴侶ならそのくらい酌んでこそ、よき女というものだぞ」
line = "「そう責めてやるな。ヨミヨミがかわゆすぎて、直視できなかったのであろうよ。それもまた男心、魔王の伴侶ならそのくらい酌んでこそ、よき女というものだぞ」"

[[dialogue]]
speaker = "ヨミ"
# 「そ、そうですね。別に見られてても嫌じゃなかったですし」
line = "「そ、そうですね。別に見られてても嫌じゃなかったですし」"

[[dialogue]]
speaker = "ヨミ"
# 「こそこそ見られるのも悪くないんですけど、やっぱり見たいって直接言われたかったですね。彼女として求められてるな～って感じたいなって思います」
line = "「こそこそ見られるのも悪くないんですけど、やっぱり見たいって直接言われたかったですね。彼女として求められてるな～って感じたいなって思います」"

[[dialogue]]
speaker = "ヘレナ"
# 「こう申しているが、どうだ？」
line = "「こう申しているが、どうだ？」"

[[dialogue]]
speaker = "unk"
# ヨミヨミの花嫁姿、じっくり見ていい？
line = "ヨミヨミの花嫁姿、じっくり見ていい？"

[[dialogue]]
speaker = "ヨミ"
# 「こやぁん！？　自分から言ったことですけど、それにしたってストレートに言いますね」
line = "「こやぁん！？　自分から言ったことですけど、それにしたってストレートに言いますね」"

[[dialogue]]
speaker = "ヨミ"
# 「まあ……会長が見たいって言ってくれたから……いいですよ、見ても。せっかくの機会です、しっかり観察して、思う存分好奇心を満たして下さい」
line = "「まあ……会長が見たいって言ってくれたから……いいですよ、見ても。せっかくの機会です、しっかり観察して、思う存分好奇心を満たして下さい」"

[[dialogue]]
speaker = "unk"
# じぃーーーーーーっ
line = "じぃーーーーーーっ"

[[dialogue]]
speaker = "unk"
# ではさっそく
line = "ではさっそく"

[[dialogue]]
speaker = "ヨミ"
# 「ち、近いですよ、近すぎますって」
line = "「ち、近いですよ、近すぎますって」"

[[dialogue]]
speaker = "ヨミ"
# 「はわわわわっ、会長がこんなに近くに……２人きりの時はよくあるけど、当主様の前で恋人距離なんて……」
line = "「はわわわわっ、会長がこんなに近くに……２人きりの時はよくあるけど、当主様の前で恋人距離なんて……」"

[[dialogue]]
speaker = "ヘレナ"
# 「照れているな、ヨミヨミ。可愛いぞ♪」
line = "「照れているな、ヨミヨミ。可愛いぞ♪」"

[[dialogue]]
speaker = "ヨミ"
# 「こやん！　からかわないでくださいよぉ～～～っ！」
line = "「こやん！　からかわないでくださいよぉ～～～っ！」"

[[dialogue]]
speaker = "ヘレナ"
# 「どうだ、白無垢を纏ったヨミヨミは？　九浄家自慢のメイドだぞ」
line = "「どうだ、白無垢を纏ったヨミヨミは？　九浄家自慢のメイドだぞ」"

[[dialogue]]
speaker = "unk"
# 最高に可愛いです
line = "最高に可愛いです"

[[dialogue]]
speaker = "ヨミ"
# 「こやぁっ……」
line = "「こやぁっ……」"

[[dialogue]]
speaker = "ヘレナ"
# 「最高に可愛い……確かにその通りだ。しかし！　もっと他にも褒める要素があるだろう？」
line = "「最高に可愛い……確かにその通りだ。しかし！　もっと他にも褒める要素があるだろう？」"

[[dialogue]]
speaker = "ヘレナ"
# 「ヨミヨミの実家は神社だからな。巫女装束も着慣れている。だからこそ、この白無垢の着こなしよ！　一朝一夕で身につくものではないぞ」
line = "「ヨミヨミの実家は神社だからな。巫女装束も着慣れている。だからこそ、この白無垢の着こなしよ！　一朝一夕で身につくものではないぞ」"

[[dialogue]]
speaker = "ヘレナ"
# 「つまり、このウェディングフォームはただの萌え衣装ではない。ヨミヨミのために最適化された特別な装いなのだっ！」
line = "「つまり、このウェディングフォームはただの萌え衣装ではない。ヨミヨミのために最適化された特別な装いなのだっ！」"

[[dialogue]]
speaker = "ヨミ"
# 「そ、そこまで考えてくれていたんですね……私、感動です！」
line = "「そ、そこまで考えてくれていたんですね……私、感動です！」"

[[dialogue]]
speaker = "ヘレナ"
# 「さあ、魔王よ。ヨミヨミの花婿となるつもりなら、その魅力を余すところなく語ってみよ！」
line = "「さあ、魔王よ。ヨミヨミの花婿となるつもりなら、その魅力を余すところなく語ってみよ！」"

[[dialogue]]
speaker = "unk"
# 清楚で可憐でふわふわしてていい匂いがして
line = "清楚で可憐でふわふわしてていい匂いがして"

[[dialogue]]
speaker = "ヨミ"
# 「ストーーップ！　そのくらいでもう十分です！　しっかり伝わりましたからぁ！」
line = "「ストーーップ！　そのくらいでもう十分です！　しっかり伝わりましたからぁ！」"

[[dialogue]]
speaker = "ヨミ"
# 「もう、すごい勢いでまくし立てるんですから……」
line = "「もう、すごい勢いでまくし立てるんですから……」"

[[dialogue]]
speaker = "ヘレナ"
# 「それほどヨミヨミには魅力が詰まっている、と言いたいのだろう？　愛されているではないか」
line = "「それほどヨミヨミには魅力が詰まっている、と言いたいのだろう？　愛されているではないか」"

[[dialogue]]
speaker = "ヨミ"
# 「そそ、そうですね……すごく、愛を感じました。えへへ、嬉しくなっちゃいますね<emoji=heart04>」
line = "「そそ、そうですね……すごく、愛を感じました。えへへ、嬉しくなっちゃいますね<emoji=heart04>」"

[[dialogue]]
speaker = "ヘレナ"
# 「ウェディングフォームになるだけでは、ここまでのぷりてぃーなヨミヨミは引き出せなかった」
line = "「ウェディングフォームになるだけでは、ここまでのぷりてぃーなヨミヨミは引き出せなかった」"

[[dialogue]]
speaker = "ヘレナ"
# 「さすがは魔王、ヨミヨミの可愛さを増幅させる天才だな！」
line = "「さすがは魔王、ヨミヨミの可愛さを増幅させる天才だな！」"

[[dialogue]]
speaker = "unk"
# いや、それほどでも……あるかな
line = "いや、それほどでも……あるかな"

[[dialogue]]
speaker = "unk"
# えっへん！
line = "えっへん！"

[[dialogue]]
speaker = "ヘレナ"
# 「気に入ったぞ！　ヨミヨミと子を作る権利をやろう！」
line = "「気に入ったぞ！　ヨミヨミと子を作る権利をやろう！」"

[[dialogue]]
speaker = "ヨミ"
# 「こやぁっ！！？　と、当主様！？　いきなり何とんでもないこと言ってるんですかぁぁっ！！」
line = "「こやぁっ！！？　と、当主様！？　いきなり何とんでもないこと言ってるんですかぁぁっ！！」"

[[dialogue]]
speaker = "ヘレナ"
# 「まあ、そう声を荒らげるな。私も九浄家の当主、配下のメイド達の将来を考えねばならぬ」
line = "「まあ、そう声を荒らげるな。私も九浄家の当主、配下のメイド達の将来を考えねばならぬ」"

[[dialogue]]
speaker = "ヘレナ"
# 「メイド達には最高の伴侶を宛がってやりたい。そして幸せな結婚をして、子を成す……」
line = "「メイド達には最高の伴侶を宛がってやりたい。そして幸せな結婚をして、子を成す……」"

[[dialogue]]
speaker = "ヘレナ"
# 「皆には女としての幸せを全て手に入れて、九浄家のメイド隊の一員でよかったと心の底から思ってもらいたいのだ」
line = "「皆には女としての幸せを全て手に入れて、九浄家のメイド隊の一員でよかったと心の底から思ってもらいたいのだ」"

[[dialogue]]
speaker = "ヨミ"
# 「当主様……そのようなお考えが……」
line = "「当主様……そのようなお考えが……」"

[[dialogue]]
speaker = "ヘレナ"
# 「そうすれば、最高に可愛いメイドが見られるからな！　はっはっは！」
line = "「そうすれば、最高に可愛いメイドが見られるからな！　はっはっは！」"

[[dialogue]]
speaker = "ヨミ"
# 「どうせそんなことだろうと思ってましたよ……」
line = "「どうせそんなことだろうと思ってましたよ……」"

[[dialogue]]
speaker = "ヘレナ"
# 「そうぼやくな。可愛い花嫁衣装が台無しだぞ」
line = "「そうぼやくな。可愛い花嫁衣装が台無しだぞ」"

[[dialogue]]
speaker = "ヘレナ"
# 「それより話を戻そう。どうなんだ、魔王のことは？　好いているなら子を作りたくなるものではないのか？」
line = "「それより話を戻そう。どうなんだ、魔王のことは？　好いているなら子を作りたくなるものではないのか？」"

[[dialogue]]
speaker = "ヨミ"
# 「そそそ、それは……そのぉ……否定はしませんけど……」
line = "「そそそ、それは……そのぉ……否定はしませんけど……」"

[[dialogue]]
speaker = "ヨミ"
# 「こやぁぁんっ！！　この話はなし！　今は保留にさせて下さいぃ～～～～っ！！」
line = "「こやぁぁんっ！！　この話はなし！　今は保留にさせて下さいぃ～～～～っ！！」"

[[dialogue]]
speaker = "unk"
# こうして、ヨミと子作りする権利は、残念ながら有耶無耶になってしまうのだった。
line = "こうして、ヨミと子作りする権利は、残念ながら有耶無耶になってしまうのだった。"
