[[dialogue]]
speaker = "unk"
# 第２話,流星ライダー鑑賞会,P
line = "第２話,流星ライダー鑑賞会,P"

[[dialogue]]
speaker = "unk"
# アポロが目覚め、そしてこの世界で生きていくことを決めて数週間が経った。
line = "アポロが目覚め、そしてこの世界で生きていくことを決めて数週間が経った。"

[[dialogue]]
speaker = "unk"
# 衰弱していた体もすっかり回復し、もう少し時間が経てば流星学園の附属校への転入手続きも取られるらしい。
line = "衰弱していた体もすっかり回復し、もう少し時間が経てば流星学園の附属校への転入手続きも取られるらしい。"

[[dialogue]]
speaker = "unk"
# これからアポロは、５年間のブランクを埋めていく。彼女がどのように成長していくのか……俺も近くで見守っていきたい。
line = "これからアポロは、５年間のブランクを埋めていく。彼女がどのように成長していくのか……俺も近くで見守っていきたい。"

[[dialogue]]
speaker = "アポロ"
# 「魔王。一大事だ！　今度の連休は空いてるか？　暇ならあたしの部屋に来てくれ！」
line = "「魔王。一大事だ！　今度の連休は空いてるか？　暇ならあたしの部屋に来てくれ！」"

[[dialogue]]
speaker = "unk"
# だからこそアポロから呼び出されれば駆けつけないわけにはいかない。ずいぶんと真面目な口調だったし、何かの相談かな……？
line = "だからこそアポロから呼び出されれば駆けつけないわけにはいかない。ずいぶんと真面目な口調だったし、何かの相談かな……？"

[[dialogue]]
speaker = "フィオナ"
# 「これから流星ライダーシリーズの一気鑑賞会を行います！」
line = "「これから流星ライダーシリーズの一気鑑賞会を行います！」"

[[dialogue]]
speaker = "アポロ"
# 「ひゃっほーい！　この時を待ってたぜー！！」
line = "「ひゃっほーい！　この時を待ってたぜー！！」"

[[dialogue]]
speaker = "unk"
# どういうこと！？
line = "どういうこと！？"

[[dialogue]]
speaker = "アポロ"
# 「あたしが頼んだんだ！　５年も眠ってたからな、知らない流星ライダーがたっぷりリリースされているだろ？」
line = "「あたしが頼んだんだ！　５年も眠ってたからな、知らない流星ライダーがたっぷりリリースされているだろ？」"

[[dialogue]]
speaker = "アポロ"
# 「体調もばっちり回復したからな。今日は見たことのないライダーを一気見するんだ！」
line = "「体調もばっちり回復したからな。今日は見たことのないライダーを一気見するんだ！」"

[[dialogue]]
speaker = "フィオナ"
# 「──私もこの時を待っていました。いつか姉さんと鑑賞できることを信じ、全作品、完全版コンプリートパックを揃えています……！」
line = "「──私もこの時を待っていました。いつか姉さんと鑑賞できることを信じ、全作品、完全版コンプリートパックを揃えています……！」"

[[dialogue]]
speaker = "アポロ"
# 「魔王も流星ライダーを全部はチェックしていないだろ？　一緒に見て盛り上がろうぜ！」
line = "「魔王も流星ライダーを全部はチェックしていないだろ？　一緒に見て盛り上がろうぜ！」"

[[dialogue]]
speaker = "unk"
# いいね、面白そうだ！
line = "いいね、面白そうだ！"

[[dialogue]]
speaker = "アポロ"
# 「いい返事だ！　それじゃあフィオナ、再生を頼む！」
line = "「いい返事だ！　それじゃあフィオナ、再生を頼む！」"

[[dialogue]]
speaker = "フィオナ"
# 「任されました！　では──スタートです！」
line = "「任されました！　では──スタートです！」"

[[dialogue]]
speaker = "unk"
# こうして３人で並び、星見家のホームシアターで流星ライダーシリーズを一気見することになり──
line = "こうして３人で並び、星見家のホームシアターで流星ライダーシリーズを一気見することになり──"

[[dialogue]]
speaker = "アポロ"
# 「な、なにぃっ……！？　２人同時にベルトを起動して……１人のライダーに変身するだと！？」
line = "「な、なにぃっ……！？　２人同時にベルトを起動して……１人のライダーに変身するだと！？」"

[[dialogue]]
speaker = "フィオナ"
# 「はい！　本作品の流星ライダーは双子で力を合わせて、１人のライダーになるんです！　姉さんとこの神作を見る機会が来るだなんて……！」
line = "「はい！　本作品の流星ライダーは双子で力を合わせて、１人のライダーになるんです！　姉さんとこの神作を見る機会が来るだなんて……！」"

[[dialogue]]
speaker = "アポロ"
# 「おぉっ！　それぞれ異なる属性攻撃を……！？　なんだこれは……カッコ良すぎるぞっ……！！」
line = "「おぉっ！　それぞれ異なる属性攻撃を……！？　なんだこれは……カッコ良すぎるぞっ……！！」"

[[dialogue]]
speaker = "フィオナ"
# 「まだまだ！　盛り上がるのはここからですよ、姉さん！　刮目してください！」
line = "「まだまだ！　盛り上がるのはここからですよ、姉さん！　刮目してください！」"

[[dialogue]]
speaker = "アポロ"
# 「いけー、ライダー！　トルネードフォームで悪党をぶっ倒すんだー！」
line = "「いけー、ライダー！　トルネードフォームで悪党をぶっ倒すんだー！」"

[[dialogue]]
speaker = "アポロ"
# 「このシリーズは……科学者が流星ライダーになるのか！？　てっきりあの若いやつが主人公かと思ってたぞ！」
line = "「このシリーズは……科学者が流星ライダーになるのか！？　てっきりあの若いやつが主人公かと思ってたぞ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ！　権威と学識のある壮年の男性が主人公なんです！　クレバーな戦い方とシリアスな展開がたまらないんですよ！」
line = "「ええ！　権威と学識のある壮年の男性が主人公なんです！　クレバーな戦い方とシリアスな展開がたまらないんですよ！」"

[[dialogue]]
speaker = "アポロ"
# 「何の力もない若者が巻き込まれて──という展開は王道ゆえにオツだが。これもいいな！　続きが気になる……早く次の話を頼む！」
line = "「何の力もない若者が巻き込まれて──という展開は王道ゆえにオツだが。これもいいな！　続きが気になる……早く次の話を頼む！」"

[[dialogue]]
speaker = "フィオナ"
# 「はいっ、姉さん！」
line = "「はいっ、姉さん！」"

[[dialogue]]
speaker = "アポロ"
# 「この新シリーズも熱いな！　バトルが手に汗握るぜ！　やっぱり１話からドンパチやってくれないとな！」
line = "「この新シリーズも熱いな！　バトルが手に汗握るぜ！　やっぱり１話からドンパチやってくれないとな！」"

[[dialogue]]
speaker = "フィオナ"
# 「バトルシーンが多めの流星ライダーはやはり見ごたえがありますね！」
line = "「バトルシーンが多めの流星ライダーはやはり見ごたえがありますね！」"

[[dialogue]]
speaker = "アポロ"
# 「しかし１話の最後……あいつは仲間なんだろう？　なぜ主人公の助太刀をせず、見てるだけだったんだ？」
line = "「しかし１話の最後……あいつは仲間なんだろう？　なぜ主人公の助太刀をせず、見てるだけだったんだ？」"

[[dialogue]]
speaker = "unk"
# なぜ見てたんだろう……？
line = "なぜ見てたんだろう……？"

[[dialogue]]
speaker = "フィオナ"
# 「そ、それはのちのち明かされますから……いま語ってはネタバレになってしまいます。さあ、続きを──！」
line = "「そ、それはのちのち明かされますから……いま語ってはネタバレになってしまいます。さあ、続きを──！」"

[[dialogue]]
speaker = "unk"
# 正義と悪のぶつかり合い。笑いあり涙ありのエンターテインメントを、俺たちはたっぷりと楽しんだ。
line = "正義と悪のぶつかり合い。笑いあり涙ありのエンターテインメントを、俺たちはたっぷりと楽しんだ。"

[[dialogue]]
speaker = "unk"
# 連休を利用しての夜更かしお泊まり鑑賞は続き──
line = "連休を利用しての夜更かしお泊まり鑑賞は続き──"

[[dialogue]]
speaker = "unk"
# アポロの見たことのない流星ライダーシリーズ、その最終話を見終わったのは、連休最終日の夕方を過ぎた頃だった──
line = "アポロの見たことのない流星ライダーシリーズ、その最終話を見終わったのは、連休最終日の夕方を過ぎた頃だった──"

[[dialogue]]
speaker = "アポロ"
# 「終わった……太陽がいやにまぶしいぜ……！」
line = "「終わった……太陽がいやにまぶしいぜ……！」"

[[dialogue]]
speaker = "unk"
# ほとんど睡眠ゼロで駆け抜けたからね……
line = "ほとんど睡眠ゼロで駆け抜けたからね……"

[[dialogue]]
speaker = "フィオナ"
# 「ですが素晴らしかったです……やはり流星ライダーは不滅の作品ですね……！」
line = "「ですが素晴らしかったです……やはり流星ライダーは不滅の作品ですね……！」"

[[dialogue]]
speaker = "アポロ"
# 「毎週楽しみに待つのもいいが、こうやって一気見するのも楽しいな！　くぅっ……どのライダーも最高だった……！」
line = "「毎週楽しみに待つのもいいが、こうやって一気見するのも楽しいな！　くぅっ……どのライダーも最高だった……！」"

[[dialogue]]
speaker = "アポロ"
# 「魔王、お前はどのシリーズがよかった？」
line = "「魔王、お前はどのシリーズがよかった？」"

[[dialogue]]
speaker = "unk"
# アポロシリーズかなぁ
line = "アポロシリーズかなぁ"

[[dialogue]]
speaker = "unk"
# どれも捨てがたいけど
line = "どれも捨てがたいけど"

[[dialogue]]
speaker = "アポロ"
# 「わかる！　『流星ライダー・アポロ』はやっぱり傑作だからな！　今回唯一見なかったシリーズだが……」
line = "「わかる！　『流星ライダー・アポロ』はやっぱり傑作だからな！　今回唯一見なかったシリーズだが……」"

[[dialogue]]
speaker = "アポロ"
# 「……む。話をしたらアポロシリーズも見たくなってきたぞ」
line = "「……む。話をしたらアポロシリーズも見たくなってきたぞ」"

[[dialogue]]
speaker = "フィオナ"
# 「それじゃあまた次のお休みの日にしましょうか」
line = "「それじゃあまた次のお休みの日にしましょうか」"

[[dialogue]]
speaker = "アポロ"
# 「何を言ってるんだ！　まだ連休は終わっていない！」
line = "「何を言ってるんだ！　まだ連休は終わっていない！」"

[[dialogue]]
speaker = "unk"
# じゃ、じゃあ俺はそろそろお暇して──
line = "じゃ、じゃあ俺はそろそろお暇して──"

[[dialogue]]
speaker = "アポロ"
# 「魔王、お前も一緒だ！　逃がさんぞ！」
line = "「魔王、お前も一緒だ！　逃がさんぞ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ね、姉さん。緋宮会長には今まで付き合っていただいたじゃないですか。今日はこのくらいで──」
line = "「ね、姉さん。緋宮会長には今まで付き合っていただいたじゃないですか。今日はこのくらいで──」"

[[dialogue]]
speaker = "アポロ"
# 「い～や～だ～っ！　アポロシリーズを今から見たいし、魔王も一緒がいい！　なぁ、いいだろー？」
line = "「い～や～だ～っ！　アポロシリーズを今から見たいし、魔王も一緒がいい！　なぁ、いいだろー？」"

[[dialogue]]
speaker = "アポロ"
# 「それともなんだ。あたしと一緒に見たくないってゆーのか、お前は？」
line = "「それともなんだ。あたしと一緒に見たくないってゆーのか、お前は？」"

[[dialogue]]
speaker = "フィオナ"
# 「姉さん、そんな言い方をしたら困らせてしまいますよ……！」
line = "「姉さん、そんな言い方をしたら困らせてしまいますよ……！」"

[[dialogue]]
speaker = "unk"
# 最後まで付き合うよ！
line = "最後まで付き合うよ！"

[[dialogue]]
speaker = "unk"
# ──わかった！
line = "──わかった！"

[[dialogue]]
speaker = "アポロ"
# 「ひゃっほーう！　それじゃあ流星ライダーの原点！　アポロシリーズ再生だぜ～！」
line = "「ひゃっほーう！　それじゃあ流星ライダーの原点！　アポロシリーズ再生だぜ～！」"

[[dialogue]]
speaker = "フィオナ"
# 「うちの姉さんがすみません、緋宮会長……」
line = "「うちの姉さんがすみません、緋宮会長……」"

[[dialogue]]
speaker = "unk"
# そうしてアポロのわがままを聞く形で、流星ライダー・アポロのシリーズを鑑賞することになり。
line = "そうしてアポロのわがままを聞く形で、流星ライダー・アポロのシリーズを鑑賞することになり。"

[[dialogue]]
speaker = "unk"
# 日付けが変わったところで物語が盛り上がり、止めどころがなくなって──
line = "日付けが変わったところで物語が盛り上がり、止めどころがなくなって──"

[[dialogue]]
speaker = "unk"
# 明け方近くに最終話を見終わって……俺たち３人の意識はそこで途絶えた。
line = "明け方近くに最終話を見終わって……俺たち３人の意識はそこで途絶えた。"

[[dialogue]]
speaker = "キリカ"
# 「失礼します。お嬢様方、そろそろ学園のご支度を……」
line = "「失礼します。お嬢様方、そろそろ学園のご支度を……」"

[[dialogue]]
speaker = "キリカ"
# 「って、これは一体何が……！　全員、床で寝るだなんてお行儀の悪い……！」
line = "「って、これは一体何が……！　全員、床で寝るだなんてお行儀の悪い……！」"

[[dialogue]]
speaker = "キリカ"
# 「はぁ。起きたら全員お説教ですね……。ですが──」
line = "「はぁ。起きたら全員お説教ですね……。ですが──」"

[[dialogue]]
speaker = "アポロ"
# 「すー……すー……」
line = "「すー……すー……」"

[[dialogue]]
speaker = "フィオナ"
# 「すー……すー……」
line = "「すー……すー……」"

[[dialogue]]
speaker = "キリカ"
# 「……ようやく一緒にいられるのですものね。羽目を外すのも、仕方がないのかもしれません」
line = "「……ようやく一緒にいられるのですものね。羽目を外すのも、仕方がないのかもしれません」"

[[dialogue]]
speaker = "キリカ"
# 「お説教は軽いお小言に留めておくことにしましょう。それと……」
line = "「お説教は軽いお小言に留めておくことにしましょう。それと……」"

[[dialogue]]
speaker = "キリカ"
# 「緋宮会長も、お付き合いいただきありがとうございました──」
line = "「緋宮会長も、お付き合いいただきありがとうございました──」"
