[[dialogue]]
speaker = "unk"
# 第１話,噂の新人バニーガール,P
line = "第１話,噂の新人バニーガール,P"

[[dialogue]]
speaker = "ユウリ"
# 「だーかーらー！　何度頼まれても嫌だっつの！」
line = "「だーかーらー！　何度頼まれても嫌だっつの！」"

[[dialogue]]
speaker = "フィオナ"
# 「いいじゃない。セーラさんから聞いたよ？　とーっても可愛かったって」
line = "「いいじゃない。セーラさんから聞いたよ？　とーっても可愛かったって」"

[[dialogue]]
speaker = "ユウリ"
# 「おだてても無駄だ。似合ってねえのはあたしが一番わかってる」
line = "「おだてても無駄だ。似合ってねえのはあたしが一番わかってる」"

[[dialogue]]
speaker = "unk"
# どうしたんだ？
line = "どうしたんだ？"

[[dialogue]]
speaker = "フィオナ"
# 「あ、緋宮会長、丁度良いところに。ユウリったら恥ずかしがって例のバニーガール姿を見せてくれないんです」
line = "「あ、緋宮会長、丁度良いところに。ユウリったら恥ずかしがって例のバニーガール姿を見せてくれないんです」"

[[dialogue]]
speaker = "ユウリ"
# 「ほいほい見せるようなもんでもねえだろうが。それにあたしは自分から笑い物にされに行くほど酔狂でもねえ」
line = "「ほいほい見せるようなもんでもねえだろうが。それにあたしは自分から笑い物にされに行くほど酔狂でもねえ」"

[[dialogue]]
speaker = "フィオナ"
# 「笑ったりなんかしないって。ちょっと変身してくれるだけでいいから。みんなユウリの可愛さに釘付けになるよ？」
line = "「笑ったりなんかしないって。ちょっと変身してくれるだけでいいから。みんなユウリの可愛さに釘付けになるよ？」"

[[dialogue]]
speaker = "ユウリ"
# 「こんな衆人環視の中で誰が変身するか。完全に見世物じゃねえか」
line = "「こんな衆人環視の中で誰が変身するか。完全に見世物じゃねえか」"

[[dialogue]]
speaker = "フィオナ"
# 「そんなこと言わずに～。緋宮会長も見たいんじゃないですか？　ユウリの可愛いバニーガール姿、もう一度見たいですよね？」
line = "「そんなこと言わずに～。緋宮会長も見たいんじゃないですか？　ユウリの可愛いバニーガール姿、もう一度見たいですよね？」"

[[dialogue]]
speaker = "unk"
# 実は２人きりの時は見せてくれるんだ
line = "実は２人きりの時は見せてくれるんだ"

[[dialogue]]
speaker = "フィオナ"
# 「え……？　ユウリ、意外と大胆なんだ……」
line = "「え……？　ユウリ、意外と大胆なんだ……」"

[[dialogue]]
speaker = "ユウリ"
# 「わかりづらい嘘をつくな、このアホ！　フィオナが信じるだろうが！？」
line = "「わかりづらい嘘をつくな、このアホ！　フィオナが信じるだろうが！？」"

[[dialogue]]
speaker = "ユウリ"
# 「つか登校時間なのになんでここにいんだよ！？　あんたの学園あっちだろ！？」
line = "「つか登校時間なのになんでここにいんだよ！？　あんたの学園あっちだろ！？」"

[[dialogue]]
speaker = "unk"
# ユウリが待ち合わせ場所に来ないから
line = "ユウリが待ち合わせ場所に来ないから"

[[dialogue]]
speaker = "ユウリ"
# 「っっ。そ、それはっ。待ち合わせして登校するなんて、カ、カップルみてえだし……」
line = "「っっ。そ、それはっ。待ち合わせして登校するなんて、カ、カップルみてえだし……」"

[[dialogue]]
speaker = "フィオナ"
# 「みたい、じゃなくて実際カップルなんだし。みんなもう知ってるよ？」
line = "「みたい、じゃなくて実際カップルなんだし。みんなもう知ってるよ？」"

[[dialogue]]
speaker = "ユウリ"
# 「～～っっ。ちげえし、カップルじゃねえし、仮にそうでも仲良く登校なんて恥ずかしい真似あたしはしねえっ！」
line = "「～～っっ。ちげえし、カップルじゃねえし、仮にそうでも仲良く登校なんて恥ずかしい真似あたしはしねえっ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ、こんな照れ屋で天邪鬼な子ですけど、これからもよろしくお願いしますね？」
line = "「ふふ、こんな照れ屋で天邪鬼な子ですけど、これからもよろしくお願いしますね？」"

[[dialogue]]
speaker = "ユウリ"
# 「菓子折を渡すな！　会長さんも深々頷くな！　つかあたしと手ぇ繋いでこようとすんな！！」
line = "「菓子折を渡すな！　会長さんも深々頷くな！　つかあたしと手ぇ繋いでこようとすんな！！」"

[[dialogue]]
speaker = "フィオナ"
# 「遠慮しなくていいのに。２人きりの時は仲良く手を繋いでイチャイチャしてるんでしょ？」
line = "「遠慮しなくていいのに。２人きりの時は仲良く手を繋いでイチャイチャしてるんでしょ？」"

[[dialogue]]
speaker = "ユウリ"
# 「し、してねえってのっ」
line = "「し、してねえってのっ」"

[[dialogue]]
speaker = "フィオナ"
# 「星徒会宛てに何件も目撃情報が届いてるけど。ペンネーム『ウサギギャル』さんからのお手紙によると──」
line = "「星徒会宛てに何件も目撃情報が届いてるけど。ペンネーム『ウサギギャル』さんからのお手紙によると──」"

[[dialogue]]
speaker = "ユウリ"
# 「読むな読むな読むな！　つかラジオのお便りコーナー感覚で人のプライベート星徒会に届けてんじゃねえよ！？」
line = "「読むな読むな読むな！　つかラジオのお便りコーナー感覚で人のプライベート星徒会に届けてんじゃねえよ！？」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ、ユウリ、真っ赤になってる。恋人の前だとそんな顔するんだ？」
line = "「ふふ、ユウリ、真っ赤になってる。恋人の前だとそんな顔するんだ？」"

[[dialogue]]
speaker = "ユウリ"
# 「単なるツッコミ疲れだから……」
line = "「単なるツッコミ疲れだから……」"

[[dialogue]]
speaker = "フィオナ"
# 「それじゃユウリの決意も固まったところで変身タイムですね。みんな、ユウリのバニーガール姿を見るの楽しみにしてるよ♪」
line = "「それじゃユウリの決意も固まったところで変身タイムですね。みんな、ユウリのバニーガール姿を見るの楽しみにしてるよ♪」"

[[dialogue]]
speaker = "ユウリ"
# 「どこにあった？　決意固まる要素どこにあった？　むしろ真逆の意志が断固として固まったわ」
line = "「どこにあった？　決意固まる要素どこにあった？　むしろ真逆の意志が断固として固まったわ」"

[[dialogue]]
speaker = "ユウリ"
# 「つかもう変身できねえし。とっくの昔にいつもの戦闘服に調整し直したっての」
line = "「つかもう変身できねえし。とっくの昔にいつもの戦闘服に調整し直したっての」"

[[dialogue]]
speaker = "フィオナ"
# 「なんだ残念……。てっきり緋宮会長のためにもうしばらくバニーガールのまま過ごすと思ってたのに」
line = "「なんだ残念……。てっきり緋宮会長のためにもうしばらくバニーガールのまま過ごすと思ってたのに」"

[[dialogue]]
speaker = "ユウリ"
# 「っっ。ん、んなバカップルみたいなこと、あたしがすっかよ」
line = "「っっ。ん、んなバカップルみたいなこと、あたしがすっかよ」"

[[dialogue]]
speaker = "フィオナ"
# 「せっかくの機会だったのに勿体ない。緋宮会長もしょんぼりしちゃってるよ？」
line = "「せっかくの機会だったのに勿体ない。緋宮会長もしょんぼりしちゃってるよ？」"

[[dialogue]]
speaker = "ユウリ"
# 「う、うるせえな。会長さんも困るだろ、似合ってもない服あたしに着られても……」
line = "「う、うるせえな。会長さんも困るだろ、似合ってもない服あたしに着られても……」"

[[dialogue]]
speaker = "ユウリ"
# 「いや、えと、あんたは似合ってるって言ってくれるけど……。それはそれで気を遣わせちゃってるみたいで悪いというか……」
line = "「いや、えと、あんたは似合ってるって言ってくれるけど……。それはそれで気を遣わせちゃってるみたいで悪いというか……」"

[[dialogue]]
speaker = "ユウリ"
# 「ほ、本心なのはわかってるけどよ。逆にまたそれが恥ずかしいというか、逆に照れて着づらくなるというか……」
line = "「ほ、本心なのはわかってるけどよ。逆にまたそれが恥ずかしいというか、逆に照れて着づらくなるというか……」"

[[dialogue]]
speaker = "ユウリ"
# 「あうっ……。だから残念がるなってっ……！　勝手に戦闘服調整したのは悪かったけど……！　というかホントはまだ──……」
line = "「あうっ……。だから残念がるなってっ……！　勝手に戦闘服調整したのは悪かったけど……！　というかホントはまだ──……」"

[[dialogue]]
speaker = "フィオナ"
# 「！　街中に複数のモンスターが出現したようです。お喋りは後にして、手分けして片付けにいきましょうっ」
line = "「！　街中に複数のモンスターが出現したようです。お喋りは後にして、手分けして片付けにいきましょうっ」"

[[dialogue]]
speaker = "ユウリ"
# 「えっ！？　いやあたしは今日はちょっと──」
line = "「えっ！？　いやあたしは今日はちょっと──」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長とユウリは西側をお願いします！」
line = "「緋宮会長とユウリは西側をお願いします！」"

[[dialogue]]
speaker = "ユウリ"
# 「うっ……！　くそ、割と大量にいやがる……！」
line = "「うっ……！　くそ、割と大量にいやがる……！」"

[[dialogue]]
speaker = "ユウリ"
# 「か、会長さん、悪いけどここは一人で片付けてもらって……いや、無茶言ってんのはわかってるけど……！」
line = "「か、会長さん、悪いけどここは一人で片付けてもらって……いや、無茶言ってんのはわかってるけど……！」"

[[dialogue]]
speaker = "unk"
# ユウリ、危ないっ！
line = "ユウリ、危ないっ！"

[[dialogue]]
speaker = "ユウリ"
# 「きゃっ、会長さん……！？　ああっ、あたしを庇って……！　悪い、あたしがおたおたしてたばっかりに……！」
line = "「きゃっ、会長さん……！？　ああっ、あたしを庇って……！　悪い、あたしがおたおたしてたばっかりに……！」"

[[dialogue]]
speaker = "ユウリ"
# 「くそ、バカかあたしは……！　あたしのしょうもない羞恥心なんかより、会長さんのことの方が何倍もっ……！！」
line = "「くそ、バカかあたしは……！　あたしのしょうもない羞恥心なんかより、会長さんのことの方が何倍もっ……！！」"

[[dialogue]]
speaker = "ユウリ"
# 「何倍もっ、大事だろうがよぉっ！」
line = "「何倍もっ、大事だろうがよぉっ！」"

[[dialogue]]
speaker = "unk"
# その姿……
line = "その姿……"

[[dialogue]]
speaker = "ユウリ"
# 「～～っっ！　やっぱハズいっ！！　見んなっ、まじまじ見んなっ！」
line = "「～～っっ！　やっぱハズいっ！！　見んなっ、まじまじ見んなっ！」"

[[dialogue]]
speaker = "ユウリ"
# 「んだよ、悪いかよ、フィオナの言うとおりだよっ！　一応またバニーに変身できるようにこっちの服も残しといたんだよっ！」
line = "「んだよ、悪いかよ、フィオナの言うとおりだよっ！　一応またバニーに変身できるようにこっちの服も残しといたんだよっ！」"

[[dialogue]]
speaker = "ユウリ"
# 「それでもいつもの戦闘服に変身するつもりだったのに……！　戦闘服が増えると変身が不安定になって……！」
line = "「それでもいつもの戦闘服に変身するつもりだったのに……！　戦闘服が増えると変身が不安定になって……！」"

[[dialogue]]
speaker = "ユウリ"
# 「ニ、ニヤニヤしてんじゃねえっ……！　これはあんたが可愛い可愛いうるさいから仕方なくっ──そう、仕方なく残しておいただけで……！」
line = "「ニ、ニヤニヤしてんじゃねえっ……！　これはあんたが可愛い可愛いうるさいから仕方なくっ──そう、仕方なく残しておいただけで……！」"

[[dialogue]]
speaker = "ユウリ"
# 「てめぇらも──さっきから邪魔なんだよぉ～！！」
line = "「てめぇらも──さっきから邪魔なんだよぉ～！！」"

[[dialogue]]
speaker = "unk"
# そしてユウリがモンスターを蹴散らし、後日その活躍ぶりが話題になったのだった。
line = "そしてユウリがモンスターを蹴散らし、後日その活躍ぶりが話題になったのだった。"
