[[dialogue]]
speaker = "unk"
# 第４話,祈りと歌と激励と,P
line = "第４話,祈りと歌と激励と,P"

[[dialogue]]
speaker = "聖沙"
# 「ラ～……ラ～……ラ～……♪」
line = "「ラ～……ラ～……ラ～……♪」"

[[dialogue]]
speaker = "聖沙"
# 「あら……会長さんじゃない。こんばんは。こんな夜更けに珍しいわね。もしかしてお祈りに来たの？」
line = "「あら……会長さんじゃない。こんばんは。こんな夜更けに珍しいわね。もしかしてお祈りに来たの？」"

[[dialogue]]
speaker = "unk"
# 綺麗な歌声が聞こえてきたので
line = "綺麗な歌声が聞こえてきたので"

[[dialogue]]
speaker = "聖沙"
# 「ああ、外まで漏れちゃってたのね。ごめんなさい、うるさかったかしら」
line = "「ああ、外まで漏れちゃってたのね。ごめんなさい、うるさかったかしら」"

[[dialogue]]
speaker = "unk"
# こんな夜遅くに練習？
line = "こんな夜遅くに練習？"

[[dialogue]]
speaker = "聖沙"
# 「日課のようなものよ。これでも元の世界では聖歌隊の隊長を務めているから。平行世界に来ているからって練習を怠るわけにはいかないわ」
line = "「日課のようなものよ。これでも元の世界では聖歌隊の隊長を務めているから。平行世界に来ているからって練習を怠るわけにはいかないわ」"

[[dialogue]]
speaker = "聖沙"
# 「それに……真夜中の聖堂ってとても静かで落ち着くのよね。こうして夜中に歌の練習をしたり、お祈りをしたりするだけで心が透き通っていく気がするの」
line = "「それに……真夜中の聖堂ってとても静かで落ち着くのよね。こうして夜中に歌の練習をしたり、お祈りをしたりするだけで心が透き通っていく気がするの」"

[[dialogue]]
speaker = "聖沙"
# 「そうだ。せっかくだし、会長さんもお祈りしていったら？　大方この時間まで会長の仕事やら戦闘訓練やらしてたんでしょ？」
line = "「そうだ。せっかくだし、会長さんもお祈りしていったら？　大方この時間まで会長の仕事やら戦闘訓練やらしてたんでしょ？」"

[[dialogue]]
speaker = "聖沙"
# 「ふふ、わかるわよ。短い付き合いとはいえ、あなたのことをずっと傍で見ていたんだもん」
line = "「ふふ、わかるわよ。短い付き合いとはいえ、あなたのことをずっと傍で見ていたんだもん」"

[[dialogue]]
speaker = "聖沙"
# 「会長さんはとても真面目で一生懸命な人よ。うちの会長にもあなたの爪の垢を煎じて飲ませてあげたいくらい」
line = "「会長さんはとても真面目で一生懸命な人よ。うちの会長にもあなたの爪の垢を煎じて飲ませてあげたいくらい」"

[[dialogue]]
speaker = "聖沙"
# 「でも、だからこそちょっと心配ね。ちゃんと休息は取ってる？　あんまり無茶をしすぎてはダメよ？」
line = "「でも、だからこそちょっと心配ね。ちゃんと休息は取ってる？　あんまり無茶をしすぎてはダメよ？」"

[[dialogue]]
speaker = "聖沙"
# 「急いては事をし損じるんだから。時には何も考えずに心を空っぽにすることも大切よ」
line = "「急いては事をし損じるんだから。時には何も考えずに心を空っぽにすることも大切よ」"

[[dialogue]]
speaker = "聖沙"
# 「こうしてお祈りを捧げたりして、ね？　ほら手を合わせて目を閉じなさい？　何も考えなくていいから」
line = "「こうしてお祈りを捧げたりして、ね？　ほら手を合わせて目を閉じなさい？　何も考えなくていいから」"

[[dialogue]]
speaker = "聖沙"
# 「……ふふ、どう？　心の中がスッキリするでしょ？」
line = "「……ふふ、どう？　心の中がスッキリするでしょ？」"

[[dialogue]]
speaker = "聖沙"
# 「せっかくこんなに立派な大聖堂が学園の敷地にあるんだもの。毎日お祈りの時間を取るといいわ」
line = "「せっかくこんなに立派な大聖堂が学園の敷地にあるんだもの。毎日お祈りの時間を取るといいわ」"

[[dialogue]]
speaker = "聖沙"
# 「深呼吸の時間にもなるし、願うことで自分の目的や目標を再確認できるし、良いことずくめよ」
line = "「深呼吸の時間にもなるし、願うことで自分の目的や目標を再確認できるし、良いことずくめよ」"

[[dialogue]]
speaker = "unk"
# 聖沙って意外と面倒見がいいんだな
line = "聖沙って意外と面倒見がいいんだな"

[[dialogue]]
speaker = "聖沙"
# 「意外とって何よ、意外とって！　私は最初から面倒見がいい方よ！」
line = "「意外とって何よ、意外とって！　私は最初から面倒見がいい方よ！」"

[[dialogue]]
speaker = "聖沙"
# 「まったくもう。気を遣ってあげたのに失礼しちゃうわ。……まぁでも、そんな減らず口を叩けるのなら大丈夫そうね」
line = "「まったくもう。気を遣ってあげたのに失礼しちゃうわ。……まぁでも、そんな減らず口を叩けるのなら大丈夫そうね」"

[[dialogue]]
speaker = "聖沙"
# 「って、だからもう。どうしてまた不思議そうな顔をしているのよ。私があなたの心配をするのが、そんなにおかしいかしら？」
line = "「って、だからもう。どうしてまた不思議そうな顔をしているのよ。私があなたの心配をするのが、そんなにおかしいかしら？」"

[[dialogue]]
speaker = "聖沙"
# 「そりゃ心配にもなるわよ。こちらの世界の星騎士は危険なモンスターと毎日のように命がけで戦っているんだもん」
line = "「そりゃ心配にもなるわよ。こちらの世界の星騎士は危険なモンスターと毎日のように命がけで戦っているんだもん」"

[[dialogue]]
speaker = "聖沙"
# 「私のいる世界よりよっぽど大変だわ。みんなは私を英雄と持ち上げてくれるけど、私から見れば、こちらの世界のみんなの方が断然英雄に見えるくらいよ」
line = "「私のいる世界よりよっぽど大変だわ。みんなは私を英雄と持ち上げてくれるけど、私から見れば、こちらの世界のみんなの方が断然英雄に見えるくらいよ」"

[[dialogue]]
speaker = "聖沙"
# 「まぁだからといって実力で負けているつもりはないけれどね♪　呼んでくれれば、いつでも英雄らしいところを見せてあげるわ♪」
line = "「まぁだからといって実力で負けているつもりはないけれどね♪　呼んでくれれば、いつでも英雄らしいところを見せてあげるわ♪」"

[[dialogue]]
speaker = "聖沙"
# 「って……どうして黙ってるのよ！　呼んでくれればいつでも英雄らしいところを見せてあげるって言ってるじゃない！」
line = "「って……どうして黙ってるのよ！　呼んでくれればいつでも英雄らしいところを見せてあげるって言ってるじゃない！」"

[[dialogue]]
speaker = "聖沙"
# 「つまり、その……。助けが欲しくなったら、いつでも私を頼りなさいってことよ！」
line = "「つまり、その……。助けが欲しくなったら、いつでも私を頼りなさいってことよ！」"

[[dialogue]]
speaker = "聖沙"
# 「別に戦闘以外のことでも構わないわ。身内には打ち明けづらい悩みだとかも私には話しやすいかもしれないし」
line = "「別に戦闘以外のことでも構わないわ。身内には打ち明けづらい悩みだとかも私には話しやすいかもしれないし」"

[[dialogue]]
speaker = "聖沙"
# 「たとえ元の世界に戻っても、あなたが私に助けを求めるのなら、すぐに飛んでいってあげるわ。何があっても必ず、ね？」
line = "「たとえ元の世界に戻っても、あなたが私に助けを求めるのなら、すぐに飛んでいってあげるわ。何があっても必ず、ね？」"

[[dialogue]]
speaker = "unk"
# やっぱり良い人だ……！
line = "やっぱり良い人だ……！"

[[dialogue]]
speaker = "聖沙"
# 「だからもう……！　あなたは今まで私をどんな風に思ってたのよ！　私は最初からずーっと頼れる良い先輩だってば！」
line = "「だからもう……！　あなたは今まで私をどんな風に思ってたのよ！　私は最初からずーっと頼れる良い先輩だってば！」"

[[dialogue]]
speaker = "聖沙"
# 「なんだかバカにされている気分になってきたわ……。せっかく夜遅くまで頑張るあなたを労ってあげようと思っていたのに」
line = "「なんだかバカにされている気分になってきたわ……。せっかく夜遅くまで頑張るあなたを労ってあげようと思っていたのに」"

[[dialogue]]
speaker = "聖沙"
# 「よし──構えなさい。勝負よ！　あなたに生徒会長の器があるかどうか改めて確かめてあげる！」
line = "「よし──構えなさい。勝負よ！　あなたに生徒会長の器があるかどうか改めて確かめてあげる！」"

[[dialogue]]
speaker = "unk"
# さっき無茶しすぎるのはダメって……
line = "さっき無茶しすぎるのはダメって……"

[[dialogue]]
speaker = "聖沙"
# 「さ、さっきはさっき、今は今よ！　いいから構えなさいってば！」
line = "「さ、さっきはさっき、今は今よ！　いいから構えなさいってば！」"

[[dialogue]]
speaker = "聖沙"
# 「それとも自信がないの？　それなら、ふふん。私の不戦勝でも構わないけれど」
line = "「それとも自信がないの？　それなら、ふふん。私の不戦勝でも構わないけれど」"

[[dialogue]]
speaker = "unk"
# ああ──負けない
line = "ああ──負けない"

[[dialogue]]
speaker = "聖沙"
# 「……ふふ。良い気迫じゃない。それでこそ生徒会長よ」
line = "「……ふふ。良い気迫じゃない。それでこそ生徒会長よ」"

[[dialogue]]
speaker = "聖沙"
# 「これから先、きっとあなたには色々な勝負や試練が待ち受けているわ。時には敗北を味わうこともあるかもしれない」
line = "「これから先、きっとあなたには色々な勝負や試練が待ち受けているわ。時には敗北を味わうこともあるかもしれない」"

[[dialogue]]
speaker = "聖沙"
# 「だけど決して折れちゃダメよ。たとえ負けても心だけは折れちゃダメ。何度でも何度でも泥臭く立ち上がりなさい」
line = "「だけど決して折れちゃダメよ。たとえ負けても心だけは折れちゃダメ。何度でも何度でも泥臭く立ち上がりなさい」"

[[dialogue]]
speaker = "聖沙"
# 「そうすれば周りのみんなも必ず応えてくれる。あなたの背中に付いてきてくれる」
line = "「そうすれば周りのみんなも必ず応えてくれる。あなたの背中に付いてきてくれる」"

[[dialogue]]
speaker = "聖沙"
# 「時にはそれを重荷に感じる時もあるかもしれないけれど……そういう時は、私を頼ってくれたらいいから」
line = "「時にはそれを重荷に感じる時もあるかもしれないけれど……そういう時は、私を頼ってくれたらいいから」"

[[dialogue]]
speaker = "聖沙"
# 「って──だからニヤニヤしないで～っ！　やっぱりバカにしてるわね！　ちょっと先輩ぶったらすぐそれなんだから……！」
line = "「って──だからニヤニヤしないで～っ！　やっぱりバカにしてるわね！　ちょっと先輩ぶったらすぐそれなんだから……！」"

[[dialogue]]
speaker = "聖沙"
# 「いいわ、今夜は徹底的に敗北ってヤツをあなたに味わわせてあげる。バッキンバッキンに心をへし折ってやるんだから！」
line = "「いいわ、今夜は徹底的に敗北ってヤツをあなたに味わわせてあげる。バッキンバッキンに心をへし折ってやるんだから！」"

[[dialogue]]
speaker = "聖沙"
# 「さぁ──勝負よ！　元の世界に戻るまでに、生徒会長のなんたるかをみっちり叩き込んであげるわ！」
line = "「さぁ──勝負よ！　元の世界に戻るまでに、生徒会長のなんたるかをみっちり叩き込んであげるわ！」"
