[[dialogue]]
speaker = "unk"
# 第２話,幸せな未来を想像して,P
line = "第２話,幸せな未来を想像して,P"

[[dialogue]]
speaker = "キリカ"
# 「歯ブラシ、お召し物、その他日用品……ふむ、これで大体の物は買い揃えましたか。他に何かご入り用な物はありますか？」
line = "「歯ブラシ、お召し物、その他日用品……ふむ、これで大体の物は買い揃えましたか。他に何かご入り用な物はありますか？」"

[[dialogue]]
speaker = "キリカ"
# 「将来のための予行演習……という体裁とはいえ、あなたがしばらく星見家のお屋敷で暮らしていくことには変わりませんからね」
line = "「将来のための予行演習……という体裁とはいえ、あなたがしばらく星見家のお屋敷で暮らしていくことには変わりませんからね」"

[[dialogue]]
speaker = "キリカ"
# 「消耗品含め必要物は、好みのものがある場合は、各々で揃えていただきます。それが星見家メイド隊の規則です」
line = "「消耗品含め必要物は、好みのものがある場合は、各々で揃えていただきます。それが星見家メイド隊の規則です」"

[[dialogue]]
speaker = "キリカ"
# 「特に私の部屋は物がありませんからね。何か必要な家具や雑貨などありましたら、今の内に──」
line = "「特に私の部屋は物がありませんからね。何か必要な家具や雑貨などありましたら、今の内に──」"

[[dialogue]]
speaker = "キリカ"
# 「……もし？　聞いていますか？　何故、頬を緩ませておられるのです？」
line = "「……もし？　聞いていますか？　何故、頬を緩ませておられるのです？」"

[[dialogue]]
speaker = "unk"
# まるで新婚夫婦のお買い物みたいだなと思って
line = "まるで新婚夫婦のお買い物みたいだなと思って"

[[dialogue]]
speaker = "キリカ"
# 「なっ……！　おかしなことを言わないでください。買い出しついでに必要物を買い揃えていただけではありませんか」
line = "「なっ……！　おかしなことを言わないでください。買い出しついでに必要物を買い揃えていただけではありませんか」"

[[dialogue]]
speaker = "unk"
# せっかくだから手を繋いで歩きましょう
line = "せっかくだから手を繋いで歩きましょう"

[[dialogue]]
speaker = "キリカ"
# 「……職務中だと理解しておられますか？　まだ買い出しも終わっておりませんし、口を動かすより足を動かしてください」
line = "「……職務中だと理解しておられますか？　まだ買い出しも終わっておりませんし、口を動かすより足を動かしてください」"

[[dialogue]]
speaker = "キリカ"
# 「………………」
line = "「………………」"

[[dialogue]]
speaker = "キリカ"
# 「コ……コホン。何をしているのです？　手を繋ぐのではないのですか？　あなたが言い出したのでしょう？　手を繋いで歩こう、と」
line = "「コ……コホン。何をしているのです？　手を繋ぐのではないのですか？　あなたが言い出したのでしょう？　手を繋いで歩こう、と」"

[[dialogue]]
speaker = "キリカ"
# 「結婚生活の予行演習もお嬢様から仰せつかった大事な仕事のひとつです。ならば夫婦らしい行動も進んで行うべきだと思います」
line = "「結婚生活の予行演習もお嬢様から仰せつかった大事な仕事のひとつです。ならば夫婦らしい行動も進んで行うべきだと思います」"

[[dialogue]]
speaker = "キリカ"
# 「私はたとえ夫婦になっても、職務中に手を繋ぐような真似はしたくありませんが……。あなたがどうしてもと言うのであれば致し方ありません」
line = "「私はたとえ夫婦になっても、職務中に手を繋ぐような真似はしたくありませんが……。あなたがどうしてもと言うのであれば致し方ありません」"

[[dialogue]]
speaker = "キリカ"
# 「ここは私が譲りましょう。譲り合いの精神もまた良い夫婦になる秘訣と聞きますからね」
line = "「ここは私が譲りましょう。譲り合いの精神もまた良い夫婦になる秘訣と聞きますからね」"

[[dialogue]]
speaker = "キリカ"
# 「ですから……繋ぐなら早く繋いでください。ずっと手を差し出している私があまりに間抜けではありませんか……」
line = "「ですから……繋ぐなら早く繋いでください。ずっと手を差し出している私があまりに間抜けではありませんか……」"

[[dialogue]]
speaker = "キリカ"
# 「あ……ふふ。もっとしっかり握ってください。それと握り方が違います。夫婦で手を繋ぐのなら、こう指を絡めて……」
line = "「あ……ふふ。もっとしっかり握ってください。それと握り方が違います。夫婦で手を繋ぐのなら、こう指を絡めて……」"

[[dialogue]]
speaker = "キリカ"
# 「ふふふ、これでバッチリですね。指の一本一本から、あなたのぬくもりが伝わってきます」
line = "「ふふふ、これでバッチリですね。指の一本一本から、あなたのぬくもりが伝わってきます」"

[[dialogue]]
speaker = "キリカ"
# 「さあ参りましょうか。残りの必要物は──……あ」
line = "「さあ参りましょうか。残りの必要物は──……あ」"

[[dialogue]]
speaker = "キリカ"
# 「い、いえ。ベビー用品店が目に入ったもので」
line = "「い、いえ。ベビー用品店が目に入ったもので」"

[[dialogue]]
speaker = "キリカ"
# 「……いつか我々もこのお店を利用する日が来るのでしょうか。私とあなたの間に、子どもができたり……して……」
line = "「……いつか我々もこのお店を利用する日が来るのでしょうか。私とあなたの間に、子どもができたり……して……」"

[[dialogue]]
speaker = "キリカ"
# 「っっ。申し訳ありません。職務中につまらない私語をこぼしてしまいました。買い出しに戻りましょう」
line = "「っっ。申し訳ありません。職務中につまらない私語をこぼしてしまいました。買い出しに戻りましょう」"

[[dialogue]]
speaker = "unk"
# 今以上に幸せで楽しい生活になるだろうね
line = "今以上に幸せで楽しい生活になるだろうね"

[[dialogue]]
speaker = "キリカ"
# 「～～っっ。話を膨らませないでください。意見には……その、同意いたしますけど」
line = "「～～っっ。話を膨らませないでください。意見には……その、同意いたしますけど」"

[[dialogue]]
speaker = "キリカ"
# 「けれど少しだけ不安ですね。何せあなたのお子です」
line = "「けれど少しだけ不安ですね。何せあなたのお子です」"

[[dialogue]]
speaker = "キリカ"
# 「ふふ。目を離すとすぐにどこかへ走り出してしまうような、好奇心旺盛でわんぱくな子どもになりそうです」
line = "「ふふ。目を離すとすぐにどこかへ走り出してしまうような、好奇心旺盛でわんぱくな子どもになりそうです」"

[[dialogue]]
speaker = "unk"
# よく笑う子になってくれるといいけどね
line = "よく笑う子になってくれるといいけどね"

[[dialogue]]
speaker = "キリカ"
# 「む、意趣返しですか？　申し訳ありませんね、表情の乏しい人間で」
line = "「む、意趣返しですか？　申し訳ありませんね、表情の乏しい人間で」"

[[dialogue]]
speaker = "キリカ"
# 「でも、その時は私も自然と笑顔を浮かべていますよ。できることなら笑顔で溢れる家庭を築きたいですから」
line = "「でも、その時は私も自然と笑顔を浮かべていますよ。できることなら笑顔で溢れる家庭を築きたいですから」"

[[dialogue]]
speaker = "キリカ"
# 「もちろん躾はきっちりいたしますが。礼儀作法はもちろん上月流の継承まで。学ばせることはたくさんあります」
line = "「もちろん躾はきっちりいたしますが。礼儀作法はもちろん上月流の継承まで。学ばせることはたくさんあります」"

[[dialogue]]
speaker = "キリカ"
# 「いえ……こういうところが私の欠点ですね。どうも厳しく教育を施そうとしてしまいます」
line = "「いえ……こういうところが私の欠点ですね。どうも厳しく教育を施そうとしてしまいます」"

[[dialogue]]
speaker = "キリカ"
# 「でも、そういう時はきっとあなたが優しく制してくださるのでしょうね。もっと自由に育ててあげようと言ってくれたりして」
line = "「でも、そういう時はきっとあなたが優しく制してくださるのでしょうね。もっと自由に育ててあげようと言ってくれたりして」"

[[dialogue]]
speaker = "キリカ"
# 「少し喧嘩になりそうな気配もありますが……ふふ。それもまた楽しそうです。厳しい母と自由な父に挟まれるくらいが子どもも健やかに成長してくれそうですし」
line = "「少し喧嘩になりそうな気配もありますが……ふふ。それもまた楽しそうです。厳しい母と自由な父に挟まれるくらいが子どもも健やかに成長してくれそうですし」"

[[dialogue]]
speaker = "キリカ"
# 「もっとも、厳しく躾けすぎるつもりはありません。あなただけ子どもに好かれて、私は嫌われてしまうなんて耐えがたいことですからね」
line = "「もっとも、厳しく躾けすぎるつもりはありません。あなただけ子どもに好かれて、私は嫌われてしまうなんて耐えがたいことですからね」"

[[dialogue]]
speaker = "キリカ"
# 「親子３人で……いえ、もっと多いかもしれませんが、いつでも笑顔で楽しく過ごしていきたいものですね」
line = "「親子３人で……いえ、もっと多いかもしれませんが、いつでも笑顔で楽しく過ごしていきたいものですね」"

[[dialogue]]
speaker = "キリカ"
# 「想像するだけでとても幸せで……本当に幸せな……」
line = "「想像するだけでとても幸せで……本当に幸せな……」"

[[dialogue]]
speaker = "unk"
# ……産着も買って帰る？
line = "……産着も買って帰る？"

[[dialogue]]
speaker = "キリカ"
# 「～～っっ。気が早すぎます。あくまで想像を膨らませていただけで。気持ちは……嬉しいですが」
line = "「～～っっ。気が早すぎます。あくまで想像を膨らませていただけで。気持ちは……嬉しいですが」"

[[dialogue]]
speaker = "キリカ"
# 「そもそも、もし子宝を授かっても産着は買いません。私が手ずから繕いますよ」
line = "「そもそも、もし子宝を授かっても産着は買いません。私が手ずから繕いますよ」"

[[dialogue]]
speaker = "キリカ"
# 「愛しい我が子が初めて袖を通す服ですからね……。生まれてくるまでの間に一針一針愛情を込めて縫ってあげたいんです……」
line = "「愛しい我が子が初めて袖を通す服ですからね……。生まれてくるまでの間に一針一針愛情を込めて縫ってあげたいんです……」"

[[dialogue]]
speaker = "キリカ"
# 「その時は……あなたも手伝ってくださいね？　私の愛情だけ込めても意味はありませんから……」
line = "「その時は……あなたも手伝ってくださいね？　私の愛情だけ込めても意味はありませんから……」"

[[dialogue]]
speaker = "キリカ"
# 「コホン……公衆の面前で何を話しているのでしょうか。さすがに恥ずかしくなってきました」
line = "「コホン……公衆の面前で何を話しているのでしょうか。さすがに恥ずかしくなってきました」"

[[dialogue]]
speaker = "キリカ"
# 「早くお買い物を済ませて帰りましょう。お屋敷で使う物品の調達が残っておりますので」
line = "「早くお買い物を済ませて帰りましょう。お屋敷で使う物品の調達が残っておりますので」"

[[dialogue]]
speaker = "キリカ"
# 「急ぎますよ。これ以上、帰りが遅くなっては他のメイドに示しがつきません」
line = "「急ぎますよ。これ以上、帰りが遅くなっては他のメイドに示しがつきません」"

[[dialogue]]
speaker = "キリカ"
# 「ひゃっ……！　へ、返事代わりに手を握り締めないでください。頷いていただくだけで構いませんから。手よりも足を動かしていただきたいです」
line = "「ひゃっ……！　へ、返事代わりに手を握り締めないでください。頷いていただくだけで構いませんから。手よりも足を動かしていただきたいです」"

[[dialogue]]
speaker = "キリカ"
# 「……ちなみに、ですが。どういたしましょう……？」
line = "「……ちなみに、ですが。どういたしましょう……？」"

[[dialogue]]
speaker = "キリカ"
# 「ですから、その。もしもあなたが望まれるのであれば、ええと……」
line = "「ですから、その。もしもあなたが望まれるのであれば、ええと……」"

[[dialogue]]
speaker = "キリカ"
# 「産着の製作も……始めて参ろうかと思うのですが……」
line = "「産着の製作も……始めて参ろうかと思うのですが……」"

[[dialogue]]
speaker = "キリカ"
# 「い、いえ、なんでもございません。早く行きましょう。買い出しひとつに日暮れまでかかったとなればメイド長の名折れですので……！」
line = "「い、いえ、なんでもございません。早く行きましょう。買い出しひとつに日暮れまでかかったとなればメイド長の名折れですので……！」"
