[[dialogue]]
speaker = "unk"
# 第４話,友達以上,P
line = "第４話,友達以上,P"

[[dialogue]]
speaker = "unk"
# ビルのアステラの件からしばらく経ったある日、ウズメが俺の家へ遊びにくることになった――
line = "ビルのアステラの件からしばらく経ったある日、ウズメが俺の家へ遊びにくることになった――"

[[dialogue]]
speaker = "ウズメイア"
# 「お、お邪魔しま～す……」
line = "「お、お邪魔しま～す……」"

[[dialogue]]
speaker = "ウズメイア"
# 「（うわあぁぁ、会長くんの家に初めて来ちゃったんだけど……！　今日１日、室内で２人きりで過ごすとか、ドキドキしちゃうし……！）」
line = "「（うわあぁぁ、会長くんの家に初めて来ちゃったんだけど……！　今日１日、室内で２人きりで過ごすとか、ドキドキしちゃうし……！）」"

[[dialogue]]
speaker = "unk"
# 俺は時代劇の映画のブルーレイを持ってきて、ウズメに見せる。
line = "俺は時代劇の映画のブルーレイを持ってきて、ウズメに見せる。"

[[dialogue]]
speaker = "ウズメイア"
# 「へ、へぇ～、それが前に面白いって言ってた作品なんだ。楽しみ～！」
line = "「へ、へぇ～、それが前に面白いって言ってた作品なんだ。楽しみ～！」"

[[dialogue]]
speaker = "ウズメイア"
# 「（初めて家へあがるってことに頭一杯で、すっかり忘れてたし！　というか今更なんだけど、会長くんが時代劇好きとか、趣味合うの、これもはや運命じゃない！？）」
line = "「（初めて家へあがるってことに頭一杯で、すっかり忘れてたし！　というか今更なんだけど、会長くんが時代劇好きとか、趣味合うの、これもはや運命じゃない！？）」"

[[dialogue]]
speaker = "unk"
# 続いて俺は、気に入っている煎茶と和菓子――苺大福を持ってくる。ソファーに案内して、前のテーブルに置いた。
line = "続いて俺は、気に入っている煎茶と和菓子――苺大福を持ってくる。ソファーに案内して、前のテーブルに置いた。"

[[dialogue]]
speaker = "ウズメイア"
# 「これが会長くんの好きな味なんだ。いただきます――」
line = "「これが会長くんの好きな味なんだ。いただきます――」"

[[dialogue]]
speaker = "ウズメイア"
# 「ん～～～っ♪　ヤバッ、めっちゃ美味しいんだけど！　あたしもこれ、好きな味だし！」
line = "「ん～～～っ♪　ヤバッ、めっちゃ美味しいんだけど！　あたしもこれ、好きな味だし！」"

[[dialogue]]
speaker = "unk"
# そっか、好みが合ってよかった
line = "そっか、好みが合ってよかった"

[[dialogue]]
speaker = "ウズメイア"
# 「っ……！」
line = "「っ……！」"

[[dialogue]]
speaker = "ウズメイア"
# 「（はああぁぁっ、そこで嬉しそうに微笑むのは反則じゃん！？　なんなの、あたしをキュン死させる気なの！？）」
line = "「（はああぁぁっ、そこで嬉しそうに微笑むのは反則じゃん！？　なんなの、あたしをキュン死させる気なの！？）」"

[[dialogue]]
speaker = "ウズメイア"
# 「（そんなのもう無理なんだけど！？　好きピになっちゃうんだけど！？）」
line = "「（そんなのもう無理なんだけど！？　好きピになっちゃうんだけど！？）」"

[[dialogue]]
speaker = "unk"
# それから俺は、映画のブルーレイを流す準備をして、ウズメの横に腰かける。
line = "それから俺は、映画のブルーレイを流す準備をして、ウズメの横に腰かける。"

[[dialogue]]
speaker = "ウズメイア"
# 「か、かかか、会長くん、あたしの隣に座るの！？」
line = "「か、かかか、会長くん、あたしの隣に座るの！？」"

[[dialogue]]
speaker = "ウズメイア"
# 「――いやいやいや！　全然嫌じゃないし、おかしくはないんだけど！　確かに今までもお昼食べる時とか、よく隣に座ってたし……」
line = "「――いやいやいや！　全然嫌じゃないし、おかしくはないんだけど！　確かに今までもお昼食べる時とか、よく隣に座ってたし……」"

[[dialogue]]
speaker = "ウズメイア"
# 「でも今は、前とちょっと違うというか、うぅ～～～！」
line = "「でも今は、前とちょっと違うというか、うぅ～～～！」"

[[dialogue]]
speaker = "ウズメイア"
# 「（友達じゃなくて男の子として意識するようになっちゃったからとか、言えるわけないし！）」
line = "「（友達じゃなくて男の子として意識するようになっちゃったからとか、言えるわけないし！）」"

[[dialogue]]
speaker = "unk"
# ウズメ、最近やっぱり変じゃないか？
line = "ウズメ、最近やっぱり変じゃないか？"

[[dialogue]]
speaker = "ウズメイア"
# 「え！？　へ、変って何が！？」
line = "「え！？　へ、変って何が！？」"

[[dialogue]]
speaker = "ウズメイア"
# 「――ここ最近、お正月前のソフィとサーシャ先輩が同じだったように、距離を置かれているような気がする？　そ、それは……！」
line = "「――ここ最近、お正月前のソフィとサーシャ先輩が同じだったように、距離を置かれているような気がする？　そ、それは……！」"

[[dialogue]]
speaker = "unk"
# 心配なんだ。何かあるなら教えて欲しい
line = "心配なんだ。何かあるなら教えて欲しい"

[[dialogue]]
speaker = "ウズメイア"
# 「うっ……！　そ、そんな真面目な顔で見つめられたら……！　あたし――」
line = "「うっ……！　そ、そんな真面目な顔で見つめられたら……！　あたし――」"

[[dialogue]]
speaker = "ウズメイア"
# 「ますます友達じゃいられなくなっちゃうし……！」
line = "「ますます友達じゃいられなくなっちゃうし……！」"

[[dialogue]]
speaker = "unk"
# 友達でいられないの！？
line = "友達でいられないの！？"

[[dialogue]]
speaker = "ウズメイア"
# 「あっ！？　いや、違うし！　悪い意味じゃなくて！　その逆！　逆だから！　その、ええと！」
line = "「あっ！？　いや、違うし！　悪い意味じゃなくて！　その逆！　逆だから！　その、ええと！」"

[[dialogue]]
speaker = "ウズメイア"
# 「友達以上に意識しちゃうってことであって、会長くんを嫌いになったとかそういうことじゃないから！」
line = "「友達以上に意識しちゃうってことであって、会長くんを嫌いになったとかそういうことじゃないから！」"

[[dialogue]]
speaker = "ウズメイア"
# 「って、あ、あれ……？　あたし、なに言って……！　いや、えっと、今のはその……！」
line = "「って、あ、あれ……？　あたし、なに言って……！　いや、えっと、今のはその……！」"

[[dialogue]]
speaker = "ウズメイア"
# 「（て、テンパって口が滑ったんだけどぉぉぉっ！？　いや、もうこれ半分告白しちゃってるようなもんじゃん！？　なにやってんのあたし！？）」
line = "「（て、テンパって口が滑ったんだけどぉぉぉっ！？　いや、もうこれ半分告白しちゃってるようなもんじゃん！？　なにやってんのあたし！？）」"

[[dialogue]]
speaker = "ウズメイア"
# 「（誤魔化す言葉が出てこないし……！　こうなったら、もう……！）」
line = "「（誤魔化す言葉が出てこないし……！　こうなったら、もう……！）」"

[[dialogue]]
speaker = "ウズメイア"
# 「――も、もし……あたしが、会長くんと友達以上の……そういう関係に、なったら……」
line = "「――も、もし……あたしが、会長くんと友達以上の……そういう関係に、なったら……」"

[[dialogue]]
speaker = "ウズメイア"
# 「寮暮らししてるから、こう見えてお弁当作ったりとかできるし……！　和食も得意だしっ。ほ、ほかには――」
line = "「寮暮らししてるから、こう見えてお弁当作ったりとかできるし……！　和食も得意だしっ。ほ、ほかには――」"

[[dialogue]]
speaker = "ウズメイア"
# 「す、スキンシップするのは！　結構好きな方だと思うんで……イチャイチャ大歓迎～……！」
line = "「す、スキンシップするのは！　結構好きな方だと思うんで……イチャイチャ大歓迎～……！」"

[[dialogue]]
speaker = "ウズメイア"
# 「とか、言ってみたりして……あはは……」
line = "「とか、言ってみたりして……あはは……」"

[[dialogue]]
speaker = "unk"
# ウズメ、俺は――
line = "ウズメ、俺は――"

[[dialogue]]
speaker = "ウズメイア"
# 「う、うん……」
line = "「う、うん……」"

[[dialogue]]
speaker = "unk"
# 不安そうな顔をするウズメ。そんな彼女に俺は――
line = "不安そうな顔をするウズメ。そんな彼女に俺は――"

[[dialogue]]
speaker = "ウズメイア"
# 「えっ！？　――本当は会長くんも、あたしのこと、女の子として、意識してくれてたの……？」
line = "「えっ！？　――本当は会長くんも、あたしのこと、女の子として、意識してくれてたの……？」"

[[dialogue]]
speaker = "ウズメイア"
# 「そ、そなんだ……じゃ、じゃあさ」
line = "「そ、そなんだ……じゃ、じゃあさ」"

[[dialogue]]
speaker = "ウズメイア"
# 「あたしたち、つ、付き合、っちゃう……？　とか、言ってみたりして……」
line = "「あたしたち、つ、付き合、っちゃう……？　とか、言ってみたりして……」"

[[dialogue]]
speaker = "unk"
# よろしくお願いします
line = "よろしくお願いします"

[[dialogue]]
speaker = "ウズメイア"
# 「あ……！　うんっ♪」
line = "「あ……！　うんっ♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「彼氏彼女として、これからはよろしくね♪　えへへへへぇ♪」
line = "「彼氏彼女として、これからはよろしくね♪　えへへへへぇ♪」"

[[dialogue]]
speaker = "unk"
# 嬉しさと照れが入り混じった笑顔を浮かべるウズメ。そんな彼女に、男としてちゃんと言っておかなければと向き直る。
line = "嬉しさと照れが入り混じった笑顔を浮かべるウズメ。そんな彼女に、男としてちゃんと言っておかなければと向き直る。"

[[dialogue]]
speaker = "ウズメイア"
# 「――え？　会長くん、言っておきたいことって……？」
line = "「――え？　会長くん、言っておきたいことって……？」"

[[dialogue]]
speaker = "unk"
# ウズメ、好きだ
line = "ウズメ、好きだ"

[[dialogue]]
speaker = "ウズメイア"
# 「～～～っ！」
line = "「～～～っ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「う、うん……私も……」
line = "「う、うん……私も……」"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くんのことが、好き……<emoji=heart04>　えへへっ<emoji=heart04>」
line = "「会長くんのことが、好き……<emoji=heart04>　えへへっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そうして俺とウズメは、どちらともなく触れた手を絡めると、そっと握り合うのだった――
line = "そうして俺とウズメは、どちらともなく触れた手を絡めると、そっと握り合うのだった――"
