[[dialogue]]
speaker = "unk"
# 第２話,ミルフィーの乙女力？,P
line = "第２話,ミルフィーの乙女力？,P"

[[dialogue]]
speaker = "unk"
# ──とある休日。
line = "──とある休日。"

[[dialogue]]
speaker = "ヒヨ"
# 「いやぁ～、今日は散歩にぴったりなお天気日和でさぁ」
line = "「いやぁ～、今日は散歩にぴったりなお天気日和でさぁ」"

[[dialogue]]
speaker = "ミルフィー"
# 「うん、こんなに晴れてると気持ちいいよね～」
line = "「うん、こんなに晴れてると気持ちいいよね～」"

[[dialogue]]
speaker = "ヒヨ"
# 「全くでさぁ……これで２人きりだったら最高だったんだが……」
line = "「全くでさぁ……これで２人きりだったら最高だったんだが……」"

[[dialogue]]
speaker = "unk"
# やっぱりお邪魔だった？
line = "やっぱりお邪魔だった？"

[[dialogue]]
speaker = "ミルフィー"
# 「そんなことないよ！　会長くんがいてくれた方が楽しいし！」
line = "「そんなことないよ！　会長くんがいてくれた方が楽しいし！」"

[[dialogue]]
speaker = "ヒヨ"
# 「あたしは姐さんと２人きりの方が楽しいぜっ」
line = "「あたしは姐さんと２人きりの方が楽しいぜっ」"

[[dialogue]]
speaker = "ミルフィー"
# 「ヒヨちゃん、そんないじわる言っちゃダメ」
line = "「ヒヨちゃん、そんないじわる言っちゃダメ」"

[[dialogue]]
speaker = "ヒヨ"
# 「だってなぁ～、会長サンがいたら、姐さんとの濃密な時間を過ごせないじゃないか」
line = "「だってなぁ～、会長サンがいたら、姐さんとの濃密な時間を過ごせないじゃないか」"

[[dialogue]]
speaker = "ミルフィー"
# 「濃密な時間って……いつも普通に遊んでるだけでしょ？」
line = "「濃密な時間って……いつも普通に遊んでるだけでしょ？」"

[[dialogue]]
speaker = "ヒヨ"
# 「あたしにとっては、かけがえのない時間なんでいっ」
line = "「あたしにとっては、かけがえのない時間なんでいっ」"

[[dialogue]]
speaker = "ミルフィー"
# 「もう～、そんなに不貞腐れないでよ」
line = "「もう～、そんなに不貞腐れないでよ」"

[[dialogue]]
speaker = "ヒヨ"
# 「別に不貞腐れてなんてないやい」
line = "「別に不貞腐れてなんてないやい」"

[[dialogue]]
speaker = "ミルフィー"
# 「ほら、たい焼き買ってあげるから機嫌直して？」
line = "「ほら、たい焼き買ってあげるから機嫌直して？」"

[[dialogue]]
speaker = "ヒヨ"
# 「たい焼き……！　そいつはたまんねぇなぁ！　姐さん、会長サン、そうと決まれば早く行こうぜぇ！」
line = "「たい焼き……！　そいつはたまんねぇなぁ！　姐さん、会長サン、そうと決まれば早く行こうぜぇ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「もうヒヨちゃん、そんなに慌てないで」
line = "「もうヒヨちゃん、そんなに慌てないで」"

[[dialogue]]
speaker = "ヒヨ"
# 「いやぁ～、やっぱり姐さんと食べるたい焼きは極上だぜぇ」
line = "「いやぁ～、やっぱり姐さんと食べるたい焼きは極上だぜぇ」"

[[dialogue]]
speaker = "ミルフィー"
# 「ヒヨちゃんってば、すっかりたい焼きに夢中になって……」
line = "「ヒヨちゃんってば、すっかりたい焼きに夢中になって……」"

[[dialogue]]
speaker = "ミルフィー"
# 「会長くんもたい焼き美味しい？　ふふ、よかった。実は私、たい焼きが大好物なんだ」
line = "「会長くんもたい焼き美味しい？　ふふ、よかった。実は私、たい焼きが大好物なんだ」"

[[dialogue]]
speaker = "ミルフィー"
# 「特にね、カスタードクリームのたい焼きが好きで、陸上部の帰りによく買い食いしちゃってるんだ」
line = "「特にね、カスタードクリームのたい焼きが好きで、陸上部の帰りによく買い食いしちゃってるんだ」"

[[dialogue]]
speaker = "ミルフィー"
# 「おかげで、ちょっとダイエットとか──……って、会長くんどうしたの？　さっきから私の顔を見つめて」
line = "「おかげで、ちょっとダイエットとか──……って、会長くんどうしたの？　さっきから私の顔を見つめて」"

[[dialogue]]
speaker = "unk"
# いや、ほっぺにクリームが付いてるから
line = "いや、ほっぺにクリームが付いてるから"

[[dialogue]]
speaker = "ミルフィー"
# 「え、嘘……！？」
line = "「え、嘘……！？」"

[[dialogue]]
speaker = "unk"
# ほら、取ったよ
line = "ほら、取ったよ"

[[dialogue]]
speaker = "ミルフィー"
# 「あ、あわわわわわわっ！」
line = "「あ、あわわわわわわっ！」"

[[dialogue]]
speaker = "unk"
# ミルフィーも意外と抜けてるところあるんだ
line = "ミルフィーも意外と抜けてるところあるんだ"

[[dialogue]]
speaker = "ミルフィー"
# 「～～～～～～～～～っっ！！」
line = "「～～～～～～～～～っっ！！」"

[[dialogue]]
speaker = "ヒヨ"
# 「なんでい！　完璧な姐さんがそんなミスをするわけねえ！　きっと姐さんはわざとクリームを付けたんだぜい！」
line = "「なんでい！　完璧な姐さんがそんなミスをするわけねえ！　きっと姐さんはわざとクリームを付けたんだぜい！」"

[[dialogue]]
speaker = "ミルフィー"
# 「わ、わざとじゃないから！　ホントだからね！」
line = "「わ、わざとじゃないから！　ホントだからね！」"

[[dialogue]]
speaker = "ヒヨ"
# 「いやぁ、姐さんの乙女アピールは流石でい！　あたしが男だったら、完全に惚れてるな！」
line = "「いやぁ、姐さんの乙女アピールは流石でい！　あたしが男だったら、完全に惚れてるな！」"

[[dialogue]]
speaker = "ミルフィー"
# 「乙女アピールとかじゃないからぁ～！」
line = "「乙女アピールとかじゃないからぁ～！」"

[[dialogue]]
speaker = "ヒヨ"
# 「会長サンも、姐さんの乙女力にドキっとしただろ？」
line = "「会長サンも、姐さんの乙女力にドキっとしただろ？」"

[[dialogue]]
speaker = "ミルフィー"
# 「えっ！？　会長くんドキドキしたの！？」
line = "「えっ！？　会長くんドキドキしたの！？」"

[[dialogue]]
speaker = "ヒヨ"
# 「って、なぁに姐さんにいやらしい目を向けてんでい！　姐さんに近づこうたってそうはいかないぞ！　姐さんの貞操はあたしが守る！」
line = "「って、なぁに姐さんにいやらしい目を向けてんでい！　姐さんに近づこうたってそうはいかないぞ！　姐さんの貞操はあたしが守る！」"

[[dialogue]]
speaker = "ミルフィー"
# 「か、会長くんはそんな人じゃないから……！」
line = "「か、会長くんはそんな人じゃないから……！」"

[[dialogue]]
speaker = "ミルフィー"
# 「会長くんは優しくて頼りになって……みんなの憧れの星徒会長なんだからっ」
line = "「会長くんは優しくて頼りになって……みんなの憧れの星徒会長なんだからっ」"

[[dialogue]]
speaker = "ヒヨ"
# 「いいや、こういう大人しそうな男ほど、頭の中はドスケベなんでい」
line = "「いいや、こういう大人しそうな男ほど、頭の中はドスケベなんでい」"

[[dialogue]]
speaker = "ヒヨ"
# 「姐さんのことも脳内では、あーんなことや、こーんなことをしてるに決まってらぁ！」
line = "「姐さんのことも脳内では、あーんなことや、こーんなことをしてるに決まってらぁ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「そ、そんなことないよね？　会長くん……」
line = "「そ、そんなことないよね？　会長くん……」"

[[dialogue]]
speaker = "ヒヨ"
# 「なんでい、姐さんでいやらしい妄想すらしないなんて、それでも男かい！　男なら一発くらいかましてやれい！」
line = "「なんでい、姐さんでいやらしい妄想すらしないなんて、それでも男かい！　男なら一発くらいかましてやれい！」"

[[dialogue]]
speaker = "unk"
# ……いいの？
line = "……いいの？"

[[dialogue]]
speaker = "ミルフィー"
# 「い、いいいわけないでしょ！」
line = "「い、いいいわけないでしょ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「もう！　ヒヨちゃんもエッチな話は禁止！」
line = "「もう！　ヒヨちゃんもエッチな話は禁止！」"

[[dialogue]]
speaker = "ヒヨ"
# 「へぇーい」
line = "「へぇーい」"

[[dialogue]]
speaker = "ミルフィー"
# （でも、会長くんにエッチな目で見られてるって想像しても……イヤじゃなかった……）
line = "（でも、会長くんにエッチな目で見られてるって想像しても……イヤじゃなかった……）"

[[dialogue]]
speaker = "ミルフィー"
# （それどころか、むしろ嬉しいって──）
line = "（それどころか、むしろ嬉しいって──）"

[[dialogue]]
speaker = "ミルフィー"
# （って、何考えちゃってるの私！　私はクラス委員なんだから、エッチなこと考えちゃダメなのにっ！！）
line = "（って、何考えちゃってるの私！　私はクラス委員なんだから、エッチなこと考えちゃダメなのにっ！！）"

[[dialogue]]
speaker = "ミルフィー"
# 「な、なんでもない！　なんでもないから、会長くんは私のこと見ないでっっ」
line = "「な、なんでもない！　なんでもないから、会長くんは私のこと見ないでっっ」"

[[dialogue]]
speaker = "ヒヨ"
# 「……変態」
line = "「……変態」"

[[dialogue]]
speaker = "unk"
# なんで！？
line = "なんで！？"

[[dialogue]]
speaker = "unk"
# その日はずっとヒヨにジト目で見られ続け、ミルフィーは顔を赤くしていたのだった。
line = "その日はずっとヒヨにジト目で見られ続け、ミルフィーは顔を赤くしていたのだった。"
