[[dialogue]]
speaker = "unk"
# 第２話,心を釣られて,P
line = "第２話,心を釣られて,P"

[[dialogue]]
speaker = "unk"
# 夏のサバイバル合宿でアナが釣り好きだということを知り、俺達は改めて２人で釣りデートをしに、リゾート結界へやって来ていた――
line = "夏のサバイバル合宿でアナが釣り好きだということを知り、俺達は改めて２人で釣りデートをしに、リゾート結界へやって来ていた――"

[[dialogue]]
speaker = "アナ"
# 「～～～♪　～～、～～～♪」
line = "「～～～♪　～～、～～～♪」"

[[dialogue]]
speaker = "アナ"
# 「おや？　会長、どうしました？　何か言いたげな表情ですが……」
line = "「おや？　会長、どうしました？　何か言いたげな表情ですが……」"

[[dialogue]]
speaker = "unk"
# この体勢で釣りをすることになるとは……
line = "この体勢で釣りをすることになるとは……"

[[dialogue]]
speaker = "アナ"
# 「会長の膝の上は、今や私の定位置ですので」
line = "「会長の膝の上は、今や私の定位置ですので」"

[[dialogue]]
speaker = "アナ"
# 「いつもの場所に腰掛け、２人で釣り竿を持っている状態……これで１度、釣りをしてみたかった。想像通り、リラックス出来て快適な釣り環境」
line = "「いつもの場所に腰掛け、２人で釣り竿を持っている状態……これで１度、釣りをしてみたかった。想像通り、リラックス出来て快適な釣り環境」"

[[dialogue]]
speaker = "アナ"
# 「それに、サバイバル合宿ではサーシャ先輩に釣りのやり方を教えたりで、会長とまったり出来ていませんでしたから」
line = "「それに、サバイバル合宿ではサーシャ先輩に釣りのやり方を教えたりで、会長とまったり出来ていませんでしたから」"

[[dialogue]]
speaker = "アナ"
# 「――大物がかかった時、危なくないのかって……？　ノープロブレム」
line = "「――大物がかかった時、危なくないのかって……？　ノープロブレム」"

[[dialogue]]
speaker = "アナ"
# 「私がこのまま釣り竿を持って立ち上がれば問題ありませんし、会長に釣りのテクニックを教えるという意味でも、私の手元が見やすいこの体勢は合理的」
line = "「私がこのまま釣り竿を持って立ち上がれば問題ありませんし、会長に釣りのテクニックを教えるという意味でも、私の手元が見やすいこの体勢は合理的」"

[[dialogue]]
speaker = "アナ"
# 「お、早速、魚のアタリがきてますよ。会長、まずはロッドをあおって釣り針がしっかりと刺さるようにアワセ――フッキングを行いましょう。それから――」
line = "「お、早速、魚のアタリがきてますよ。会長、まずはロッドをあおって釣り針がしっかりと刺さるようにアワセ――フッキングを行いましょう。それから――」"

[[dialogue]]
speaker = "unk"
# そうしてアナにテクニックを解説して貰いながら、見事に魚を釣り上げることができた――
line = "そうしてアナにテクニックを解説して貰いながら、見事に魚を釣り上げることができた――"

[[dialogue]]
speaker = "アナ"
# 「やりましたね。初回から、なかなかの大物です」
line = "「やりましたね。初回から、なかなかの大物です」"

[[dialogue]]
speaker = "アナ"
# 「――釣りの細かなテクニックに感心した？　ほうほう……ふふふっ。そこまで会長にベタ褒めされると、良い気分……むふ～♪」
line = "「――釣りの細かなテクニックに感心した？　ほうほう……ふふふっ。そこまで会長にベタ褒めされると、良い気分……むふ～♪」"

[[dialogue]]
speaker = "unk"
# アナはどうして釣りが好きなんだ？
line = "アナはどうして釣りが好きなんだ？"

[[dialogue]]
speaker = "アナ"
# 「この前は、そこまで話していませんでしたね」
line = "「この前は、そこまで話していませんでしたね」"

[[dialogue]]
speaker = "アナ"
# 「最初は人間界の、生態系への興味。実際に色んな生き物を観察したくて、海や山に出向き、魚を近くで見る為の手段として釣りを学びました」
line = "「最初は人間界の、生態系への興味。実際に色んな生き物を観察したくて、海や山に出向き、魚を近くで見る為の手段として釣りを学びました」"

[[dialogue]]
speaker = "アナ"
# 「ところが実際やってみると……簡単ではなくて、最初の１匹を釣り上げるのに悪戦苦闘した。同時に魚の生命力に触れて、驚きました」
line = "「ところが実際やってみると……簡単ではなくて、最初の１匹を釣り上げるのに悪戦苦闘した。同時に魚の生命力に触れて、驚きました」"

[[dialogue]]
speaker = "アナ"
# 「そして、やっとの想いで初めて釣り上げた瞬間は……今も鮮明に覚えています」
line = "「そして、やっとの想いで初めて釣り上げた瞬間は……今も鮮明に覚えています」"

[[dialogue]]
speaker = "アナ"
# 「その１匹目は、予想外のとんでもない大物で……思わず放心状態になって、足がガクガク震えたんです。とても……感動しました」
line = "「その１匹目は、予想外のとんでもない大物で……思わず放心状態になって、足がガクガク震えたんです。とても……感動しました」"

[[dialogue]]
speaker = "アナ"
# 「そんなことがあって、今では釣り自体が凄く好きになったんです。ただ――」
line = "「そんなことがあって、今では釣り自体が凄く好きになったんです。ただ――」"

[[dialogue]]
speaker = "アナ"
# 「周りには釣りが好きという人は見かけませんでした。だから、合宿の時まで自分から言い出さずに黙っていたんです」
line = "「周りには釣りが好きという人は見かけませんでした。だから、合宿の時まで自分から言い出さずに黙っていたんです」"

[[dialogue]]
speaker = "アナ"
# 「でもこうして、趣味を一緒にやれる人が出来ると嬉しいものですね」
line = "「でもこうして、趣味を一緒にやれる人が出来ると嬉しいものですね」"

[[dialogue]]
speaker = "unk"
# アナの趣味を知らなかったのはちょっと悔しい
line = "アナの趣味を知らなかったのはちょっと悔しい"

[[dialogue]]
speaker = "アナ"
# 「それは……すみません」
line = "「それは……すみません」"

[[dialogue]]
speaker = "アナ"
# 「……釣りって決して、女の子らしい趣味とは言えないじゃないですか」
line = "「……釣りって決して、女の子らしい趣味とは言えないじゃないですか」"

[[dialogue]]
speaker = "アナ"
# 「会長にはなるべく、彼女として良く思われたくって……」
line = "「会長にはなるべく、彼女として良く思われたくって……」"

[[dialogue]]
speaker = "アナ"
# 「んっ……<emoji=heart04>　か、会長……いきなり抱き締められると、驚く……<emoji=heart04>」
line = "「んっ……<emoji=heart04>　か、会長……いきなり抱き締められると、驚く……<emoji=heart04>」"

[[dialogue]]
speaker = "アナ"
# 「い、今は釣りをしている最中……そういうのは、魚がかかった時の反応に遅れが生じます……」
line = "「い、今は釣りをしている最中……そういうのは、魚がかかった時の反応に遅れが生じます……」"

[[dialogue]]
speaker = "アナ"
# 「――心臓のドキドキが聞こえてくる？　こ、好意対象の男性から抱き締められたら、そうなるのは普通……」
line = "「――心臓のドキドキが聞こえてくる？　こ、好意対象の男性から抱き締められたら、そうなるのは普通……」"

[[dialogue]]
speaker = "unk"
# アナが俺を釣り上げるようなことを言うのが悪い
line = "アナが俺を釣り上げるようなことを言うのが悪い"

[[dialogue]]
speaker = "アナ"
# 「別にそんなことを狙ったわけでは……」
line = "「別にそんなことを狙ったわけでは……」"

[[dialogue]]
speaker = "アナ"
# 「で、ですが――」
line = "「で、ですが――」"

[[dialogue]]
speaker = "unk"
# アナは釣り竿のリールを巻いて、釣り針を海から引き上げさせると――
line = "アナは釣り竿のリールを巻いて、釣り針を海から引き上げさせると――"

[[dialogue]]
speaker = "アナ"
# 「人間界のことわざで、二兎追う者は一兎をも得ず、とも言います……」
line = "「人間界のことわざで、二兎追う者は一兎をも得ず、とも言います……」"

[[dialogue]]
speaker = "アナ"
# 「今は一旦……会長を釣る方に集中しましょう」
line = "「今は一旦……会長を釣る方に集中しましょう」"

[[dialogue]]
speaker = "unk"
# アナ、そんなこと言われたら――
line = "アナ、そんなこと言われたら――"

[[dialogue]]
speaker = "アナ"
# 「会長……んっ……<emoji=heart04>」
line = "「会長……んっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アナ"
# 「ちゅっ……ちゅ<emoji=heart04>　すぐにキスするだなんて……会長は、スケベ<emoji=heart04>」
line = "「ちゅっ……ちゅ<emoji=heart04>　すぐにキスするだなんて……会長は、スケベ<emoji=heart04>」"

[[dialogue]]
speaker = "アナ"
# 「でも、ここ数日、キスの勉強を出来てませんでしたし……んっ<emoji=heart04>　……いい機会、かもしれません」
line = "「でも、ここ数日、キスの勉強を出来てませんでしたし……んっ<emoji=heart04>　……いい機会、かもしれません」"

[[dialogue]]
speaker = "アナ"
# 「ちゅ<emoji=heart04>　――はいっ。会長……私も好き、です……<emoji=heart04>」
line = "「ちゅ<emoji=heart04>　――はいっ。会長……私も好き、です……<emoji=heart04>」"

[[dialogue]]
speaker = "アナ"
# 「浅いキス……ぽかぽかして、幸せな気持ちに……なります<emoji=heart04>　……ちゅっ」
line = "「浅いキス……ぽかぽかして、幸せな気持ちに……なります<emoji=heart04>　……ちゅっ」"

[[dialogue]]
speaker = "アナ"
# 「はぁ。会長、好き……っ<emoji=heart04>　ちゅっ……ちゅ<emoji=heart04>　ちゅっ<emoji=heart04>」
line = "「はぁ。会長、好き……っ<emoji=heart04>　ちゅっ……ちゅ<emoji=heart04>　ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そうして見事に釣られた俺は、アナと心行くまで甘いキスを楽しむのだった――
line = "そうして見事に釣られた俺は、アナと心行くまで甘いキスを楽しむのだった――"
