[[dialogue]]
speaker = "unk"
# 第１話,元気の出る応援,P
line = "第１話,元気の出る応援,P"

[[dialogue]]
speaker = "unk"
# 星霊祭が終わり、その後処理に明け暮れていたある日──
line = "星霊祭が終わり、その後処理に明け暮れていたある日──"

[[dialogue]]
speaker = "マトイ"
# 「ふー、これで星霊祭関係の仕事は全部終わりかな。アナとサーシャさんがいなくても、ちゃんと片付いたね」
line = "「ふー、これで星霊祭関係の仕事は全部終わりかな。アナとサーシャさんがいなくても、ちゃんと片付いたね」"

[[dialogue]]
speaker = "マトイ"
# 「でも何か大事なものを忘れてるような……」
line = "「でも何か大事なものを忘れてるような……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、クロト、マトイ、ごっめーん」
line = "「あっ、クロト、マトイ、ごっめーん」"

[[dialogue]]
speaker = "マトイ"
# 「どうしたの？　……なんか嫌～な予感がするんだけど」
line = "「どうしたの？　……なんか嫌～な予感がするんだけど」"

[[dialogue]]
speaker = "ヴィーナス"
# 「星霊祭の会計報告書を、学園長に出さないといけないんだったわ！」
line = "「星霊祭の会計報告書を、学園長に出さないといけないんだったわ！」"

[[dialogue]]
speaker = "unk"
# 星霊祭の会計報告！？
line = "星霊祭の会計報告！？"

[[dialogue]]
speaker = "マトイ"
# 「ヴィーナス！？　なんでそんな大事な書類、隠してたのー！？」
line = "「ヴィーナス！？　なんでそんな大事な書類、隠してたのー！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「隠してたんじゃないわ、隠れちゃってたのよ！」
line = "「隠してたんじゃないわ、隠れちゃってたのよ！」"

[[dialogue]]
speaker = "マトイ"
# 「それっていつまでに提出しないといけないやつ？」
line = "「それっていつまでに提出しないといけないやつ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それが今日中なのよ！」
line = "「それが今日中なのよ！」"

[[dialogue]]
speaker = "マトイ"
# 「今日中！？　完全下校まで、あと２時間だよ！？」
line = "「今日中！？　完全下校まで、あと２時間だよ！？」"

[[dialogue]]
speaker = "マトイ"
# 「猫の手も借りたいのに、今日に限ってアナもサーシャさんもいないけど……それでも、やらなきゃだよね」
line = "「猫の手も借りたいのに、今日に限ってアナもサーシャさんもいないけど……それでも、やらなきゃだよね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「大丈夫！　私がいるわ！」
line = "「大丈夫！　私がいるわ！」"

[[dialogue]]
speaker = "マトイ"
# 「ヴィーナスが手を出すと、余計に混乱するからダメ！　隅っこでジッとしてて！」
line = "「ヴィーナスが手を出すと、余計に混乱するからダメ！　隅っこでジッとしてて！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「猫の手以下！？　ひどいわ！？」
line = "「猫の手以下！？　ひどいわ！？」"

[[dialogue]]
speaker = "美鶴"
# 「何の騒ぎですか、お三方。廊下まで聞こえてますよ」
line = "「何の騒ぎですか、お三方。廊下まで聞こえてますよ」"

[[dialogue]]
speaker = "unk"
# 騒がしい星徒会室に顔を覗かせたのは、九浄家メイド隊の長篠美鶴だ。
line = "騒がしい星徒会室に顔を覗かせたのは、九浄家メイド隊の長篠美鶴だ。"

[[dialogue]]
speaker = "美鶴"
# 「あー、お嬢様がまた余計なことをやらかしたんで？」
line = "「あー、お嬢様がまた余計なことをやらかしたんで？」"

[[dialogue]]
speaker = "マトイ"
# 「ご主人様のトラブルメーカーっぷりをよくご存じで……」
line = "「ご主人様のトラブルメーカーっぷりをよくご存じで……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「今回は違うわ！　やらなきゃいけないことをすっかり忘れていたのよ！」
line = "「今回は違うわ！　やらなきゃいけないことをすっかり忘れていたのよ！」"

[[dialogue]]
speaker = "美鶴"
# 「もっとタチが悪いすね。すみません、皆様。うちのお嬢様が」
line = "「もっとタチが悪いすね。すみません、皆様。うちのお嬢様が」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そんなことより良いところに来たわ、美鶴！」
line = "「そんなことより良いところに来たわ、美鶴！」"

[[dialogue]]
speaker = "マトイ"
# 「あっ、美鶴ちゃんに手伝ってもらうの？　猫の手も借りたいって言ったけど、それはちょっと悪い──」
line = "「あっ、美鶴ちゃんに手伝ってもらうの？　猫の手も借りたいって言ったけど、それはちょっと悪い──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「星霊祭で着てたチアガールの戦闘服があったでしょ。アレを着て、私たちを応援しなさい！」
line = "「星霊祭で着てたチアガールの戦闘服があったでしょ。アレを着て、私たちを応援しなさい！」"

[[dialogue]]
speaker = "マトイ"
# 「なんで着替えさせるのー！？　普通に手伝ってもらえばいいじゃない！」
line = "「なんで着替えさせるのー！？　普通に手伝ってもらえばいいじゃない！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「予算報告書は一応、星徒会内で片づけなきゃいけない案件でしょ？」
line = "「予算報告書は一応、星徒会内で片づけなきゃいけない案件でしょ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「部外者の美鶴に助力は頼めないわ。一般の学生には見せられない情報もあるし」
line = "「部外者の美鶴に助力は頼めないわ。一般の学生には見せられない情報もあるし」"

[[dialogue]]
speaker = "unk"
# ちゃんとした理由があった……
line = "ちゃんとした理由があった……"

[[dialogue]]
speaker = "ヴィーナス"
# 「だから、美鶴には応援だけしてもらおうと思って。美鶴のチアガール姿なんてスーパーウルトラゴッデスレアよ」
line = "「だから、美鶴には応援だけしてもらおうと思って。美鶴のチアガール姿なんてスーパーウルトラゴッデスレアよ」"

[[dialogue]]
speaker = "美鶴"
# 「え、普通にイヤですけど」
line = "「え、普通にイヤですけど」"

[[dialogue]]
speaker = "マトイ"
# 「秒で拒否られたんですけど！？」
line = "「秒で拒否られたんですけど！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そんなこと言わないで！　あんなに可愛い美鶴を星霊祭の１回こっきりで終わらせちゃうには惜しすぎるわ！　世界の損失よ！」
line = "「そんなこと言わないで！　あんなに可愛い美鶴を星霊祭の１回こっきりで終わらせちゃうには惜しすぎるわ！　世界の損失よ！」"

[[dialogue]]
speaker = "マトイ"
# 「それはまぁ、確かに……美鶴ちゃんのチアガール、すっごく可愛かったし……」
line = "「それはまぁ、確かに……美鶴ちゃんのチアガール、すっごく可愛かったし……」"

[[dialogue]]
speaker = "美鶴"
# 「おだてても着ませんて。恥ずいし」
line = "「おだてても着ませんて。恥ずいし」"

[[dialogue]]
speaker = "unk"
# チアガールの美鶴、可愛かったな……
line = "チアガールの美鶴、可愛かったな……"

[[dialogue]]
speaker = "美鶴"
# 「……うちが着替えれば、満足するんです？」
line = "「……うちが着替えれば、満足するんです？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「大・満・足よ！　クロトも大喜びよね？」
line = "「大・満・足よ！　クロトも大喜びよね？」"

[[dialogue]]
speaker = "マトイ"
# （あれ？　美鶴ちゃん、かなりチョロめ？）
line = "（あれ？　美鶴ちゃん、かなりチョロめ？）"

[[dialogue]]
speaker = "美鶴"
# 「はいはい、わかりました、わかりました。お嬢様の命令には逆らえません」
line = "「はいはい、わかりました、わかりました。お嬢様の命令には逆らえません」"

[[dialogue]]
speaker = "マトイ"
# （ヴィーナスというか、会長のためな気がする……）
line = "（ヴィーナスというか、会長のためな気がする……）"

[[dialogue]]
speaker = "美鶴"
# 「んじゃ早速──」
line = "「んじゃ早速──」"

[[dialogue]]
speaker = "美鶴"
# 「これでいいんですよね、お嬢様」
line = "「これでいいんですよね、お嬢様」"

[[dialogue]]
speaker = "マトイ"
# 「やっぱかわいいっ！　いつもとギャップがあるよね！」
line = "「やっぱかわいいっ！　いつもとギャップがあるよね！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でしょー？　いつものメイド服もいいけど、たまにはこれで仕事してくれたらいいのにって思うわ」
line = "「でしょー？　いつものメイド服もいいけど、たまにはこれで仕事してくれたらいいのにって思うわ」"

[[dialogue]]
speaker = "美鶴"
# 「愛でていただくのは悪い気はしませんが、勘弁してください。それよりも今は急がなくてはいけない緊急事態なのでは？」
line = "「愛でていただくのは悪い気はしませんが、勘弁してください。それよりも今は急がなくてはいけない緊急事態なのでは？」"

[[dialogue]]
speaker = "マトイ"
# 「そうだった！　提出期限まであと１時間半しかないよー！」
line = "「そうだった！　提出期限まであと１時間半しかないよー！」"

[[dialogue]]
speaker = "美鶴"
# 「わざわざ着替えたうちは、何をすればよろしいので？」
line = "「わざわざ着替えたうちは、何をすればよろしいので？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「応援よ！　切羽詰まっている２人を励ましてあげて！」
line = "「応援よ！　切羽詰まっている２人を励ましてあげて！」"

[[dialogue]]
speaker = "マトイ"
# 「誰のせいで切羽詰まったと思ってるのかなぁ？」
line = "「誰のせいで切羽詰まったと思ってるのかなぁ？」"

[[dialogue]]
speaker = "美鶴"
# 「はぁ……そんなんでいいんでしたら……がーんばれ、がーんばれ」
line = "「はぁ……そんなんでいいんでしたら……がーんばれ、がーんばれ」"

[[dialogue]]
speaker = "美鶴"
# 「何やってるかよくわかんないんで、ちっとも気持ちは入ってないんすけど……こんなのでよろしいんすかね」
line = "「何やってるかよくわかんないんで、ちっとも気持ちは入ってないんすけど……こんなのでよろしいんすかね」"

[[dialogue]]
speaker = "マトイ"
# 「なんだろう……美鶴ちゃんの応援……気持ちが籠ってる感じはしないのに……」
line = "「なんだろう……美鶴ちゃんの応援……気持ちが籠ってる感じはしないのに……」"

[[dialogue]]
speaker = "unk"
# み・な・ぎっ・て・き・た・ぜ！
line = "み・な・ぎっ・て・き・た・ぜ！"

[[dialogue]]
speaker = "unk"
# 妙にやる気が湧いてくる……！
line = "妙にやる気が湧いてくる……！"

[[dialogue]]
speaker = "美鶴"
# 「そんならいいんすけど……ふぁーいと、ふぁーいと」
line = "「そんならいいんすけど……ふぁーいと、ふぁーいと」"

[[dialogue]]
speaker = "マトイ"
# 「一気にやっちゃうよっ！　私はこっちの領収書の数字を読み上げてくから、入力お願いできるかなっ！？」
line = "「一気にやっちゃうよっ！　私はこっちの領収書の数字を読み上げてくから、入力お願いできるかなっ！？」"

[[dialogue]]
speaker = "unk"
# 秒で終わらせてやる！
line = "秒で終わらせてやる！"

[[dialogue]]
speaker = "unk"
# 任せろ！
line = "任せろ！"

[[dialogue]]
speaker = "美鶴"
# 「やーればでっきるー、なーせばっなるー」
line = "「やーればでっきるー、なーせばっなるー」"

[[dialogue]]
speaker = "美鶴"
# 「いけいけマトイー、いけいけかいちょー」
line = "「いけいけマトイー、いけいけかいちょー」"

[[dialogue]]
speaker = "美鶴"
# 「……我ながら何やってんだかって感じなんすけど」
line = "「……我ながら何やってんだかって感じなんすけど」"

[[dialogue]]
speaker = "ヴィーナス"
# 「冷静になっちゃダメ！　応援を止めちゃダメよ、美鶴！」
line = "「冷静になっちゃダメ！　応援を止めちゃダメよ、美鶴！」"

[[dialogue]]
speaker = "美鶴"
# 「はぁ……まだ勤務時間内なんでやりますけど……で、ヴィーナスお嬢様は何やってんすか」
line = "「はぁ……まだ勤務時間内なんでやりますけど……で、ヴィーナスお嬢様は何やってんすか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「美鶴の勇姿を目に焼き付けつつ、画像と動画も残してるわ！」
line = "「美鶴の勇姿を目に焼き付けつつ、画像と動画も残してるわ！」"

[[dialogue]]
speaker = "美鶴"
# 「ちょ、撮影許可出してないんすけど。追加のお給金請求してもいいヤツすよね、これ」
line = "「ちょ、撮影許可出してないんすけど。追加のお給金請求してもいいヤツすよね、これ」"

[[dialogue]]
speaker = "マトイ"
# 「収支トータルプラマイゼロ！　誤差なし！　完璧だよ！」
line = "「収支トータルプラマイゼロ！　誤差なし！　完璧だよ！」"

[[dialogue]]
speaker = "美鶴"
# 「お疲れさまです。てか、１時間しか経ってませんけど」
line = "「お疲れさまです。てか、１時間しか経ってませんけど」"

[[dialogue]]
speaker = "マトイ"
# 「なんかあっという間だったよ。集中力が研ぎ澄まされて、ゾーンに入ったみたいになって……嘘みたいなスピードで片付いちゃった……」
line = "「なんかあっという間だったよ。集中力が研ぎ澄まされて、ゾーンに入ったみたいになって……嘘みたいなスピードで片付いちゃった……」"

[[dialogue]]
speaker = "unk"
# 美鶴の応援のおかげだ
line = "美鶴の応援のおかげだ"

[[dialogue]]
speaker = "美鶴"
# 「えっへん」
line = "「えっへん」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それはつまり、美鶴を着替えさせた私の功績でもあるわね！　えっへん！」
line = "「それはつまり、美鶴を着替えさせた私の功績でもあるわね！　えっへん！」"

[[dialogue]]
speaker = "マトイ"
# 「それはない」
line = "「それはない」"

[[dialogue]]
speaker = "美鶴"
# 「ないです」
line = "「ないです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なんでよー！？」
line = "「なんでよー！？」"

[[dialogue]]
speaker = "マトイ"
# 「そもそも、ヴィーナスが忘れてなければ、こんな大変なことにはならなかったんだからね！」
line = "「そもそも、ヴィーナスが忘れてなければ、こんな大変なことにはならなかったんだからね！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「てへぺろ☆」
line = "「てへぺろ☆」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そういえば、美鶴って本気出して集中するとゾーンに入って、すっごく強くなるのよね？　前にヘレナちゃんから聞いたわ」
line = "「そういえば、美鶴って本気出して集中するとゾーンに入って、すっごく強くなるのよね？　前にヘレナちゃんから聞いたわ」"

[[dialogue]]
speaker = "美鶴"
# 「そうらしいすね。うちが本気出すのなんて、多くて年イチくらいすけど」
line = "「そうらしいすね。うちが本気出すのなんて、多くて年イチくらいすけど」"

[[dialogue]]
speaker = "ヴィーナス"
# 「美鶴の超集中ゾーンが、応援した人にエンチャントされる──って感じなのかしら。すごく便利ね！　ピンチになったら、またお願いするわ！」
line = "「美鶴の超集中ゾーンが、応援した人にエンチャントされる──って感じなのかしら。すごく便利ね！　ピンチになったら、またお願いするわ！」"

[[dialogue]]
speaker = "美鶴"
# 「もうヤです。そもそもピンチにならないようにしてください」
line = "「もうヤです。そもそもピンチにならないようにしてください」"

[[dialogue]]
speaker = "マトイ"
# 「ごもっともだよ。ヴィーナスは反省して！」
line = "「ごもっともだよ。ヴィーナスは反省して！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「はーい」
line = "「はーい」"

[[dialogue]]
speaker = "unk"
# 兎にも角にも、美鶴の応援のおかげで重要書類は爆速で完成し、星徒会は窮地を免れたのであった。
line = "兎にも角にも、美鶴の応援のおかげで重要書類は爆速で完成し、星徒会は窮地を免れたのであった。"
