[[dialogue]]
speaker = "unk"
# 第４話,個人の境界,P
line = "第４話,個人の境界,P"

[[dialogue]]
speaker = "マグダレナ"
# 「あれが噂に聞きし萌え萌えジャンケン……不思議な楽しさがありましたね」
line = "「あれが噂に聞きし萌え萌えジャンケン……不思議な楽しさがありましたね」"

[[dialogue]]
speaker = "シャロン"
# 「私は女神様に仕える身なので、そういったサービスとはいえ、奉仕される側になるのはむずがゆかったですねー」
line = "「私は女神様に仕える身なので、そういったサービスとはいえ、奉仕される側になるのはむずがゆかったですねー」"

[[dialogue]]
speaker = "マグダレナ"
# 「次のお店に参りましょうか。さすがメイドの総本山。メイド喫茶がたくさんあってどれも興味深いです」
line = "「次のお店に参りましょうか。さすがメイドの総本山。メイド喫茶がたくさんあってどれも興味深いです」"

[[dialogue]]
speaker = "unk"
# 合ってるような、間違ってるような……
line = "合ってるような、間違ってるような……"

[[dialogue]]
speaker = "マグダレナ"
# 「違うのですか？　こちらにメイド喫茶がたくさん所在しているとテレビで見たのですが」
line = "「違うのですか？　こちらにメイド喫茶がたくさん所在しているとテレビで見たのですが」"

[[dialogue]]
speaker = "マグダレナ"
# 「……ふむふむ、本来のメイドは喫茶店ではなく家に仕えるもの。星見家にいらっしゃるキリカさまなどがそうなのですね」
line = "「……ふむふむ、本来のメイドは喫茶店ではなく家に仕えるもの。星見家にいらっしゃるキリカさまなどがそうなのですね」"

[[dialogue]]
speaker = "マグダレナ"
# 「なるほど、それならすでにお会いしていましたね。勘違いしていたようでした。お恥ずかしい」
line = "「なるほど、それならすでにお会いしていましたね。勘違いしていたようでした。お恥ずかしい」"

[[dialogue]]
speaker = "unk"
# なぜこのメンツでメイド喫茶巡り……？
line = "なぜこのメンツでメイド喫茶巡り……？"

[[dialogue]]
speaker = "マグダレナ"
# 「せっかく肉体を得たのですから、どのようなものでも体験してみたいのです。リクリエに際して不謹慎かもしれませんが……」
line = "「せっかく肉体を得たのですから、どのようなものでも体験してみたいのです。リクリエに際して不謹慎かもしれませんが……」"

[[dialogue]]
speaker = "シャロン"
# 「いえいえ、素晴らしいことだと思います。守護天使様の目で直に我々の世界を見ていただけるなんて、滅多にありませんからね」
line = "「いえいえ、素晴らしいことだと思います。守護天使様の目で直に我々の世界を見ていただけるなんて、滅多にありませんからね」"

[[dialogue]]
speaker = "シャロン"
# 「そして私はマグダレナさまの介添えです。守護天使様は女神様とともに世界を支える偉大なる存在。教皇庁のシスターたる私がお世話しなくてどうするというものですから！」
line = "「そして私はマグダレナさまの介添えです。守護天使様は女神様とともに世界を支える偉大なる存在。教皇庁のシスターたる私がお世話しなくてどうするというものですから！」"

[[dialogue]]
speaker = "マグダレナ"
# 「ありがとうございます、シャロンさま。教皇庁の方々には住まいを提供していただいて本当に感謝しています」
line = "「ありがとうございます、シャロンさま。教皇庁の方々には住まいを提供していただいて本当に感謝しています」"

[[dialogue]]
speaker = "シャロン"
# 「いえいえそんな、守護天使様からお言葉を頂くなんて畏れ多い……！　むしろ光栄です！」
line = "「いえいえそんな、守護天使様からお言葉を頂くなんて畏れ多い……！　むしろ光栄です！」"

[[dialogue]]
speaker = "シャロン"
# 「遠慮なさらず何でも申し付けてください。このシャロン、マグダレナさまのためなら火の中水の中、アステラの中まで飛び込みます……！」
line = "「遠慮なさらず何でも申し付けてください。このシャロン、マグダレナさまのためなら火の中水の中、アステラの中まで飛び込みます……！」"

[[dialogue]]
speaker = "マグダレナ"
# 「ふふふ……頼りにさせていただきます。シャロンさまも悩みなどありましたらお聞かせくださいね」
line = "「ふふふ……頼りにさせていただきます。シャロンさまも悩みなどありましたらお聞かせくださいね」"

[[dialogue]]
speaker = "マグダレナ"
# 「それにテレビで紹介されていたメイドの衣装がかわいらしくて……メイド体験ができるお店もあるそうです。ご主人様、とお呼びしてみましょうか？」
line = "「それにテレビで紹介されていたメイドの衣装がかわいらしくて……メイド体験ができるお店もあるそうです。ご主人様、とお呼びしてみましょうか？」"

[[dialogue]]
speaker = "マグダレナ"
# 「……畏れ多すぎる？　ふふ、よろしいではないですか。滅多にできない経験ですよ」
line = "「……畏れ多すぎる？　ふふ、よろしいではないですか。滅多にできない経験ですよ」"

[[dialogue]]
speaker = "シャロン"
# 「──モンスター！」
line = "「──モンスター！」"

[[dialogue]]
speaker = "マグダレナ"
# 「行きましょう。世界を――この街を守るために」
line = "「行きましょう。世界を――この街を守るために」"

[[dialogue]]
speaker = "シャロン"
# 「きゅぅ～～……」
line = "「きゅぅ～～……」"

[[dialogue]]
speaker = "マグダレナ"
# 「おっと……モンスターの討伐お疲れ様でした。さすがシャロンさま、見事な戦いぶりでありました」
line = "「おっと……モンスターの討伐お疲れ様でした。さすがシャロンさま、見事な戦いぶりでありました」"

[[dialogue]]
speaker = "マグダレナ"
# 「会長さまもお疲れ様です。どこかでお休みを……そうだ、この近くにもメイド喫茶がありましたね」
line = "「会長さまもお疲れ様です。どこかでお休みを……そうだ、この近くにもメイド喫茶がありましたね」"

[[dialogue]]
speaker = "unk"
# メイド喫茶気に入りました？
line = "メイド喫茶気に入りました？"

[[dialogue]]
speaker = "マグダレナ"
# 「はい、とても新鮮な体験でした。オムライスにハートを描くのもかわいらしいです」
line = "「はい、とても新鮮な体験でした。オムライスにハートを描くのもかわいらしいです」"

[[dialogue]]
speaker = "マグダレナ"
# 「……でももしかすると、行先はどこでも良かったのかもしれません」
line = "「……でももしかすると、行先はどこでも良かったのかもしれません」"

[[dialogue]]
speaker = "マグダレナ"
# 「以前私は、三界とは異なる領域の話をいたしましたね。個人が持つ複数の領域の話です」
line = "「以前私は、三界とは異なる領域の話をいたしましたね。個人が持つ複数の領域の話です」"

[[dialogue]]
speaker = "マグダレナ"
# 「フィーニスの塔を除いて、三界という領域は混じり合うことはなく、この世界がある限り不変です」
line = "「フィーニスの塔を除いて、三界という領域は混じり合うことはなく、この世界がある限り不変です」"

[[dialogue]]
speaker = "マグダレナ"
# 「ですが人の持つ領域は違うと思うのです。人と繋がっていくことで広がり、重なっていくもの」
line = "「ですが人の持つ領域は違うと思うのです。人と繋がっていくことで広がり、重なっていくもの」"

[[dialogue]]
speaker = "マグダレナ"
# 「いろんな方の領域にもっと入っていきたい。私の領域に入ってきてほしい。……もちろんあなたもその一人です」
line = "「いろんな方の領域にもっと入っていきたい。私の領域に入ってきてほしい。……もちろんあなたもその一人です」"

[[dialogue]]
speaker = "マグダレナ"
# 「ですから今日もその一環で……メイド喫茶という経験を通してあなたと領域を重ねたかったのです」
line = "「ですから今日もその一環で……メイド喫茶という経験を通してあなたと領域を重ねたかったのです」"

[[dialogue]]
speaker = "マグダレナ"
# 「この身は仮初めのもの。リクリエを阻止できたとて、今の私がいつまで地上にいられるかはわかりません」
line = "「この身は仮初めのもの。リクリエを阻止できたとて、今の私がいつまで地上にいられるかはわかりません」"

[[dialogue]]
speaker = "マグダレナ"
# 「戦いの中で壊れてしまうかもしれません。間もなく寿命を迎えて朽ちてしまうかもしれません」
line = "「戦いの中で壊れてしまうかもしれません。間もなく寿命を迎えて朽ちてしまうかもしれません」"

[[dialogue]]
speaker = "マグダレナ"
# 「今の私がいなくなった時、その記憶は本体に受け継がれるのか、無となって消えてしまうのかもわかりません」
line = "「今の私がいなくなった時、その記憶は本体に受け継がれるのか、無となって消えてしまうのかもわかりません」"

[[dialogue]]
speaker = "マグダレナ"
# 「このマグダレナはそのように不安定な、泡沫のような存在なのです」
line = "「このマグダレナはそのように不安定な、泡沫のような存在なのです」"

[[dialogue]]
speaker = "マグダレナ"
# 「短い間になってしまうかもしれませんが……それでも末永長くよろしくお願いしますね」
line = "「短い間になってしまうかもしれませんが……それでも末永長くよろしくお願いしますね」"

[[dialogue]]
speaker = "unk"
# よろしくお願いします
line = "よろしくお願いします"

[[dialogue]]
speaker = "マグダレナ"
# 「ちなみに先ほど言ったメイド体験できるお店、メイド服がなかなか大胆なデザインらしいですよ？」
line = "「ちなみに先ほど言ったメイド体験できるお店、メイド服がなかなか大胆なデザインらしいですよ？」"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "シャロン"
# 「むっ！　何か不埒な気配がしたような！」
line = "「むっ！　何か不埒な気配がしたような！」"

[[dialogue]]
speaker = "マグダレナ"
# 「おや、元気になられたのですね、シャロンさま。安心いたしました」
line = "「おや、元気になられたのですね、シャロンさま。安心いたしました」"

[[dialogue]]
speaker = "シャロン"
# 「いえいえ、お気遣いありがとうございますっ。しかし会長さま、守護天使さまに邪な気持ちを抱いてはなりませんよっ」
line = "「いえいえ、お気遣いありがとうございますっ。しかし会長さま、守護天使さまに邪な気持ちを抱いてはなりませんよっ」"

[[dialogue]]
speaker = "マグダレナ"
# 「あらあら、シャロンさまはお厳しい。うふふふふっ」
line = "「あらあら、シャロンさまはお厳しい。うふふふふっ」"
