[[dialogue]]
speaker = "ユウリ"
# 「ほ、本当にこれっきりだからな……？　こんなこと一回こっきりだぞ……？」
line = "「ほ、本当にこれっきりだからな……？　こんなこと一回こっきりだぞ……？」"

[[dialogue]]
speaker = "unk"
# 恥ずかしそうに尋ねてくるユウリに深く頷く。
line = "恥ずかしそうに尋ねてくるユウリに深く頷く。"

[[dialogue]]
speaker = "unk"
# その悩ましげに視線を泳がせる姿を見ているだけでも、ズボンの膨らみが一段と大きくなった。
line = "その悩ましげに視線を泳がせる姿を見ているだけでも、ズボンの膨らみが一段と大きくなった。"

[[dialogue]]
speaker = "ユウリ"
# 「～～っっ。や、やっぱしやめるっ……！　大体閉店作業中にこんなことしちゃいけねえし……！」
line = "「～～っっ。や、やっぱしやめるっ……！　大体閉店作業中にこんなことしちゃいけねえし……！」"

[[dialogue]]
speaker = "ユウリ"
# 「イチャイチャするなら部屋に帰ってからいくらでも……！　ここでする必要なんてどこにもねえじゃんか……！」
line = "「イチャイチャするなら部屋に帰ってからいくらでも……！　ここでする必要なんてどこにもねえじゃんか……！」"

[[dialogue]]
speaker = "unk"
# いいや、部屋に帰ってからではダメだ。ユウリがバニースーツから着替えてしまう。
line = "いいや、部屋に帰ってからではダメだ。ユウリがバニースーツから着替えてしまう。"

[[dialogue]]
speaker = "unk"
# 俺はバニー姿のユウリとエッチがしたかった。
line = "俺はバニー姿のユウリとエッチがしたかった。"

[[dialogue]]
speaker = "ユウリ"
# 「ちゃ、ちゃんと着てやるから。特訓の時だって着てたろ？　いやまぁ明らかにそういう目をしてきてからは避けてたけど……」
line = "「ちゃ、ちゃんと着てやるから。特訓の時だって着てたろ？　いやまぁ明らかにそういう目をしてきてからは避けてたけど……」"

[[dialogue]]
speaker = "ユウリ"
# 「でも着るって約束するから……！　ホントマジで絶対……！　今度こそ必ず着てやっからさ……！」
line = "「でも着るって約束するから……！　ホントマジで絶対……！　今度こそ必ず着てやっからさ……！」"

[[dialogue]]
speaker = "ユウリ"
# 「だから、なっ？　今回はやめとこうぜっ？」
line = "「だから、なっ？　今回はやめとこうぜっ？」"

[[dialogue]]
speaker = "ユウリ"
# 「バニー姿でエッチするなんて恥ずか──ひゃっ！？」
line = "「バニー姿でエッチするなんて恥ずか──ひゃっ！？」"

[[dialogue]]
speaker = "unk"
# 流石にもう先送りにされたくない。半ば強引にユウリをテーブルへ押し倒す。
line = "流石にもう先送りにされたくない。半ば強引にユウリをテーブルへ押し倒す。"

[[dialogue]]
speaker = "unk"
# そして簡単には逃げられないようにぎゅっと手首を掴んで──
line = "そして簡単には逃げられないようにぎゅっと手首を掴んで──"

[[dialogue]]
speaker = "ユウリ"
# 「バ、バカヤロっ、離せっ……！　せめて部屋に帰ってからっ……！」
line = "「バ、バカヤロっ、離せっ……！　せめて部屋に帰ってからっ……！」"

[[dialogue]]
speaker = "ユウリ"
# 「ひぃあっ！？　ズリズリ擦り付けんなぁ……！　人のこと眺めながら、なに腰揺らしてんだよぉ……！」
line = "「ひぃあっ！？　ズリズリ擦り付けんなぁ……！　人のこと眺めながら、なに腰揺らしてんだよぉ……！」"

[[dialogue]]
speaker = "unk"
# テーブルの上で照れ悶えるユウリを目の当たりにした途端、無意識のうちに肉棒を扱いていた。
line = "テーブルの上で照れ悶えるユウリを目の当たりにした途端、無意識のうちに肉棒を扱いていた。"

[[dialogue]]
speaker = "unk"
# 初体験の時よりも初々しい。ユウリが照れれば照れるほど興奮してしまう。
line = "初体験の時よりも初々しい。ユウリが照れれば照れるほど興奮してしまう。"

[[dialogue]]
speaker = "ユウリ"
# 「うぅ、なんでこんなに発情してっ……。フリフリの服着てやった時も、めちゃくちゃはぁはぁ言ってたしっ……」
line = "「うぅ、なんでこんなに発情してっ……。フリフリの服着てやった時も、めちゃくちゃはぁはぁ言ってたしっ……」"

[[dialogue]]
speaker = "ユウリ"
# 「そういう反応されると困るんだよぉ……。似合ってるって、可愛いって、口で言うよりも言ってもらってる気分になって……」
line = "「そういう反応されると困るんだよぉ……。似合ってるって、可愛いって、口で言うよりも言ってもらってる気分になって……」"

[[dialogue]]
speaker = "ユウリ"
# 「恥ずかしいのに嬉しくなって、興奮してくれてるの見てドキドキしちゃって……」
line = "「恥ずかしいのに嬉しくなって、興奮してくれてるの見てドキドキしちゃって……」"

[[dialogue]]
speaker = "ユウリ"
# 「あたしらしくなくなっちまうっ……。こ、こんなモジモジ照れるようなキャラじゃねえのにっ……」
line = "「あたしらしくなくなっちまうっ……。こ、こんなモジモジ照れるようなキャラじゃねえのにっ……」"

[[dialogue]]
speaker = "unk"
# まるで初心な乙女のように恥じらうユウリが可愛い。
line = "まるで初心な乙女のように恥じらうユウリが可愛い。"

[[dialogue]]
speaker = "unk"
# その『らしくない反応』を俺は見たかったんだ。
line = "その『らしくない反応』を俺は見たかったんだ。"

[[dialogue]]
speaker = "unk"
# 他の誰にも見せない女の子らしい姿を。俺だけが知っているユウリの一番可愛い姿を。
line = "他の誰にも見せない女の子らしい姿を。俺だけが知っているユウリの一番可愛い姿を。"

[[dialogue]]
speaker = "ユウリ"
# 「ふぁぁぁっ……<emoji=heart04>　入って、んぁぁ、先っぽ入ってきてるってばっ……<emoji=heart04>」
line = "「ふぁぁぁっ……<emoji=heart04>　入って、んぁぁ、先っぽ入ってきてるってばっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「ダメだからっ……<emoji=heart04>　店の中でこんなことっ……<emoji=heart04>　ヘレナさんに、あぁぁ、叱られちまうっ……<emoji=heart04>」
line = "「ダメだからっ……<emoji=heart04>　店の中でこんなことっ……<emoji=heart04>　ヘレナさんに、あぁぁ、叱られちまうっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「イチャつくなら部屋でっ……<emoji=heart04>　エッチするのは嫌じゃないからっ、あたしだってしたいからっ……<emoji=heart04>」
line = "「イチャつくなら部屋でっ……<emoji=heart04>　エッチするのは嫌じゃないからっ、あたしだってしたいからっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「こんな場所でするのっ、めちゃくちゃ恥ずかし──」
line = "「こんな場所でするのっ、めちゃくちゃ恥ずかし──」"

[[dialogue]]
speaker = "ユウリ"
# 「あはぁぁああああああんんんんっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あはぁぁああああああんんんんっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 股を閉じようとするユウリを阻止してペニスを突き入れる。
line = "股を閉じようとするユウリを阻止してペニスを突き入れる。"

[[dialogue]]
speaker = "ユウリ"
# 「あっ、はぁっ、んぁぁぁっ……<emoji=heart04>　挿れるなって言ってんのにっ……<emoji=heart04>　やめっ、あぁっ、動くなっ……<emoji=heart04>」
line = "「あっ、はぁっ、んぁぁぁっ……<emoji=heart04>　挿れるなって言ってんのにっ……<emoji=heart04>　やめっ、あぁっ、動くなっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「バレちゃっ、あっ、あっ、あぁっ……<emoji=heart04>　興奮しちゃってるのバレちゃうっ……<emoji=heart04>」
line = "「バレちゃっ、あっ、あっ、あぁっ……<emoji=heart04>　興奮しちゃってるのバレちゃうっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「絶対あたしのおま○こ今っ、ふぁぁぁぁっ……<emoji=heart04>　いつも以上にギュウギュウしてっ、蕩けちゃってっっ……<emoji=heart04>」
line = "「絶対あたしのおま○こ今っ、ふぁぁぁぁっ……<emoji=heart04>　いつも以上にギュウギュウしてっ、蕩けちゃってっっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ユウリの言う通り、締まりも濡れ具合も凄まじくて、火照り滾った膣内にペニスが溶かされてしまいそうだ。
line = "ユウリの言う通り、締まりも濡れ具合も凄まじくて、火照り滾った膣内にペニスが溶かされてしまいそうだ。"

[[dialogue]]
speaker = "unk"
# ひと突きごとに恥ずかしそうによがるユウリの姿が情欲を掻き立ててくる。
line = "ひと突きごとに恥ずかしそうによがるユウリの姿が情欲を掻き立ててくる。"

[[dialogue]]
speaker = "ユウリ"
# 「ふぁっ、あはぁんっ、ち○ちん熱いっ……<emoji=heart04>　普段よりおっきいっ……<emoji=heart04>　膣内でどんどん膨らんでっ……<emoji=heart04>」
line = "「ふぁっ、あはぁんっ、ち○ちん熱いっ……<emoji=heart04>　普段よりおっきいっ……<emoji=heart04>　膣内でどんどん膨らんでっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「それダメぇ……<emoji=heart04>　はぁあんっ……<emoji=heart04>　嬉しくなっちゃうからぁ……<emoji=heart04>　もっと恥ずかしくなっちゃうからぁ……<emoji=heart04>」
line = "「それダメぇ……<emoji=heart04>　はぁあんっ……<emoji=heart04>　嬉しくなっちゃうからぁ……<emoji=heart04>　もっと恥ずかしくなっちゃうからぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「こんな女の子な姿、あふぁ、見ないでっ、見るなぁっ、見られたくないっ……<emoji=heart04>」
line = "「こんな女の子な姿、あふぁ、見ないでっ、見るなぁっ、見られたくないっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 真っ赤な顔を手で覆おうとしているのか、ユウリが必死に俺の腕をほどこうとする。
line = "真っ赤な顔を手で覆おうとしているのか、ユウリが必死に俺の腕をほどこうとする。"

[[dialogue]]
speaker = "unk"
# だけどさせない。乙女な姿に興奮して、可愛すぎて今にも射精しそうになってしまう。
line = "だけどさせない。乙女な姿に興奮して、可愛すぎて今にも射精しそうになってしまう。"

[[dialogue]]
speaker = "ユウリ"
# 「あはぁあんっ、あっ、はぁっ、あぁぁぁっっ……<emoji=heart04>　可愛いって言うのもダメっ、今は好きって言うの禁止ぃ……<emoji=heart04>」
line = "「あはぁあんっ、あっ、はぁっ、あぁぁぁっっ……<emoji=heart04>　可愛いって言うのもダメっ、今は好きって言うの禁止ぃ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「イっちゃうっ、あぁっ、イっちゃうからっ……<emoji=heart04>　知ってるクセにっ、可愛いって言われたらすぐイっちゃうの知ってるクセにっ……<emoji=heart04>」
line = "「イっちゃうっ、あぁっ、イっちゃうからっ……<emoji=heart04>　知ってるクセにっ、可愛いって言われたらすぐイっちゃうの知ってるクセにっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺がつい口に出した言葉に反応して、ユウリがビクビクと体を悶えさせる。
line = "俺がつい口に出した言葉に反応して、ユウリがビクビクと体を悶えさせる。"

[[dialogue]]
speaker = "unk"
# ただでさえトロトロな膣内が一気に愛液で満たされて、テーブルの上に大きな染みを作っていく。
line = "ただでさえトロトロな膣内が一気に愛液で満たされて、テーブルの上に大きな染みを作っていく。"

[[dialogue]]
speaker = "ユウリ"
# 「はふぁぁぁああっっ<emoji=heart04>　あっ、はぁああんっ<emoji=heart04>　ゆっくり動くのもズルいぃ……<emoji=heart04>　わざとち○ちんの感触味わわせてきてっ……<emoji=heart04>」
line = "「はふぁぁぁああっっ<emoji=heart04>　あっ、はぁああんっ<emoji=heart04>　ゆっくり動くのもズルいぃ……<emoji=heart04>　わざとち○ちんの感触味わわせてきてっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「おま○こ吸い付いていっちゃうじゃんかぁ……<emoji=heart04>　ち○ちん抱き締めにいっちゃうっ……<emoji=heart04>」
line = "「おま○こ吸い付いていっちゃうじゃんかぁ……<emoji=heart04>　ち○ちん抱き締めにいっちゃうっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「はぁぁあっ、ぶっといっ……<emoji=heart04>　やっぱりいつもよりおっきいっ……<emoji=heart04>　発情しまくってくれてるの、丸わかりでっ……<emoji=heart04>」
line = "「はぁぁあっ、ぶっといっ……<emoji=heart04>　やっぱりいつもよりおっきいっ……<emoji=heart04>　発情しまくってくれてるの、丸わかりでっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「ふぁぁぁっ<emoji=heart04>　ち○ちんパンパンで、おま○こ張り裂けそっ……<emoji=heart04>　バニー着てるだけで、こんなにたくさん精子作ってくれてっ……<emoji=heart04>」
line = "「ふぁぁぁっ<emoji=heart04>　ち○ちんパンパンで、おま○こ張り裂けそっ……<emoji=heart04>　バニー着てるだけで、こんなにたくさん精子作ってくれてっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「ホントに、あふぁっ、ホントに可愛いと思ってくれてるんだっ……<emoji=heart04>　らしくない格好してるのにっ、らしくない反応してるのにっ……<emoji=heart04>」
line = "「ホントに、あふぁっ、ホントに可愛いと思ってくれてるんだっ……<emoji=heart04>　らしくない格好してるのにっ、らしくない反応してるのにっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「えへへっ、えへっ、あはぁあんっ……<emoji=heart04>　照れてイっちゃうっ……<emoji=heart04>　嬉しくてっ、イックぅぅぅっ～～<emoji=heart04>」
line = "「えへへっ、えへっ、あはぁあんっ……<emoji=heart04>　照れてイっちゃうっ……<emoji=heart04>　嬉しくてっ、イックぅぅぅっ～～<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「やっぱり幸せっ……<emoji=heart04>　幸せすぎてっ……<emoji=heart04>　こんなあたしを本気で可愛いと思ってくれてるのがイクほど嬉しくてっ……<emoji=heart04>」
line = "「やっぱり幸せっ……<emoji=heart04>　幸せすぎてっ……<emoji=heart04>　こんなあたしを本気で可愛いと思ってくれてるのがイクほど嬉しくてっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ユウリの腕から力が抜ける。照れた顔をしながらも俺を上目遣いに見つめてきてくれる。
line = "ユウリの腕から力が抜ける。照れた顔をしながらも俺を上目遣いに見つめてきてくれる。"

[[dialogue]]
speaker = "unk"
# それどころか、ユウリからも甘えるように腰を振ってきてくれて──
line = "それどころか、ユウリからも甘えるように腰を振ってきてくれて──"

[[dialogue]]
speaker = "ユウリ"
# 「はぁっ、あっ、あっ、はぁあんっ……<emoji=heart04>　もういいっ……<emoji=heart04>　もう焦らさなくてもいいから、もっと動いてっ……<emoji=heart04>」
line = "「はぁっ、あっ、あっ、はぁあんっ……<emoji=heart04>　もういいっ……<emoji=heart04>　もう焦らさなくてもいいから、もっと動いてっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「もっとち○ちんで好きって言ってっ……<emoji=heart04>　あたしのこと可愛いって言ってっ……<emoji=heart04>」
line = "「もっとち○ちんで好きって言ってっ……<emoji=heart04>　あたしのこと可愛いって言ってっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「興奮してくれてるの、はぁっ、はぁっ、本当はすげぇ嬉しいからっ……<emoji=heart04>　やらしい目で見てくれるの幸せだからぁ……<emoji=heart04>」
line = "「興奮してくれてるの、はぁっ、はぁっ、本当はすげぇ嬉しいからっ……<emoji=heart04>　やらしい目で見てくれるの幸せだからぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「あたしの照れ屋なモジモジおま○こっ、彼氏ち○ちんでいっぱいズボズボしてぇぇっっ……<emoji=heart04>」
line = "「あたしの照れ屋なモジモジおま○こっ、彼氏ち○ちんでいっぱいズボズボしてぇぇっっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ユウリの声に応えて、その手を思いっきり引き寄せる。
line = "ユウリの声に応えて、その手を思いっきり引き寄せる。"

[[dialogue]]
speaker = "ユウリ"
# 「んぁっ、あっ、あっ、あっ、あっ、あはぁああっ、くふぁぁあああんんっっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「んぁっ、あっ、あっ、あっ、あっ、あはぁああっ、くふぁぁあああんんっっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「これっ、これこれっ、イクっ<emoji=heart04>　イクイクっ<emoji=heart04>　イクぅぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「これっ、これこれっ、イクっ<emoji=heart04>　イクイクっ<emoji=heart04>　イクぅぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「この瞬間が一番幸せっ<emoji=heart04>　大好きなヤツが、ふぁっ、あぁあっ、夢中であたしのこと愛してくれてっ<emoji=heart04>」
line = "「この瞬間が一番幸せっ<emoji=heart04>　大好きなヤツが、ふぁっ、あぁあっ、夢中であたしのこと愛してくれてっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「女の子になっちまうっ<emoji=heart04>　らしくない声出して甘えちまうっ<emoji=heart04>」
line = "「女の子になっちまうっ<emoji=heart04>　らしくない声出して甘えちまうっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「だけどっ、あっ、ふぁっ、くはぁああんっっ<emoji=heart04><emoji=heart04><emoji=heart04>　めちゃくちゃ幸せぇ……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「だけどっ、あっ、ふぁっ、くはぁああんっっ<emoji=heart04><emoji=heart04><emoji=heart04>　めちゃくちゃ幸せぇ……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 顔をフニャフニャにしてユウリが快感に喘ぐ。
line = "顔をフニャフニャにしてユウリが快感に喘ぐ。"

[[dialogue]]
speaker = "unk"
# 普段の強気な彼女からは想像も付かないほど、目尻を垂らして、だらしなく口を半開きにして。
line = "普段の強気な彼女からは想像も付かないほど、目尻を垂らして、だらしなく口を半開きにして。"

[[dialogue]]
speaker = "unk"
# そんなユウリの姿が一番好きだ。恋人の俺にしか見せない顔。イチャイチャしてる時だけ見せてくれる女の子の顔──
line = "そんなユウリの姿が一番好きだ。恋人の俺にしか見せない顔。イチャイチャしてる時だけ見せてくれる女の子の顔──"

[[dialogue]]
speaker = "ユウリ"
# 「ふぁああんっっ<emoji=heart04>　あはぁあんっっ<emoji=heart04>　気持ちいいっ<emoji=heart04>　もっと、あっ、あっ、もっと激しくしていいからっ……<emoji=heart04>」
line = "「ふぁああんっっ<emoji=heart04>　あはぁあんっっ<emoji=heart04>　気持ちいいっ<emoji=heart04>　もっと、あっ、あっ、もっと激しくしていいからっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「あたしも気持ち良くするっ<emoji=heart04>　んふぅぅんんっっ<emoji=heart04>　おま○こいっぱい締めてっ、ち○ちん気持ち良くしてあげたいっ<emoji=heart04>」
line = "「あたしも気持ち良くするっ<emoji=heart04>　んふぅぅんんっっ<emoji=heart04>　おま○こいっぱい締めてっ、ち○ちん気持ち良くしてあげたいっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「一緒に気持ち良くなろっ<emoji=heart04>　たくさんエッチしよっ<emoji=heart04>　大好きな彼氏と、あはぁあんっ、いっぱいイチャイチャしたいっ<emoji=heart04>」
line = "「一緒に気持ち良くなろっ<emoji=heart04>　たくさんエッチしよっ<emoji=heart04>　大好きな彼氏と、あはぁあんっ、いっぱいイチャイチャしたいっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「あっ、あっ、あんっ、おま○こキュンキュンするっ<emoji=heart04>　彼氏のち○ちん、抱き締めちゃうっ<emoji=heart04>」
line = "「あっ、あっ、あんっ、おま○こキュンキュンするっ<emoji=heart04>　彼氏のち○ちん、抱き締めちゃうっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「おっきなち○ちんで、奥までズンズンされて、んぁっ、ああっ<emoji=heart04>　深いところ、入って、あっ、あっ、んん～～～っ<emoji=heart04>」
line = "「おっきなち○ちんで、奥までズンズンされて、んぁっ、ああっ<emoji=heart04>　深いところ、入って、あっ、あっ、んん～～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「あっ、あっ、あっ、あっ<emoji=heart04>　そうっ、もっと腕引っ張ってっ<emoji=heart04>　奥気持ちいいっ<emoji=heart04>　イクっ、イクイクイクぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あっ、あっ、あっ、あっ<emoji=heart04>　そうっ、もっと腕引っ張ってっ<emoji=heart04>　奥気持ちいいっ<emoji=heart04>　イクっ、イクイクイクぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「あふぁっ、嬉しいっ<emoji=heart04>　ち○ちんすげぇブルブルしてくれてっ<emoji=heart04>　ビュービュー我慢汁噴き出してくれてっ<emoji=heart04>」
line = "「あふぁっ、嬉しいっ<emoji=heart04>　ち○ちんすげぇブルブルしてくれてっ<emoji=heart04>　ビュービュー我慢汁噴き出してくれてっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「いつでも出していいからなっ<emoji=heart04>　好きなだけ出してくれていいからっ<emoji=heart04>」
line = "「いつでも出していいからなっ<emoji=heart04>　好きなだけ出してくれていいからっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「だけど絶対、膣内に出してっ<emoji=heart04>　腕引っ張りながら、奥の奥にドピュドピュしてっ<emoji=heart04>」
line = "「だけど絶対、膣内に出してっ<emoji=heart04>　腕引っ張りながら、奥の奥にドピュドピュしてっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「膣内に出してもらうの一番好きだからっ<emoji=heart04>　出した後もっ、あっ、あっ、ち○ちん絶対すぐ抜かないでっ……<emoji=heart04>」
line = "「膣内に出してもらうの一番好きだからっ<emoji=heart04>　出した後もっ、あっ、あっ、ち○ちん絶対すぐ抜かないでっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 腕を引っ張る動きに合わせてユウリが器用に腰を揺らす。
line = "腕を引っ張る動きに合わせてユウリが器用に腰を揺らす。"

[[dialogue]]
speaker = "unk"
# キスの雨を降らせるように子宮口を亀頭にチュッチュと当てて、ジュクジュクのおま○こで肉竿にねぶってくる。
line = "キスの雨を降らせるように子宮口を亀頭にチュッチュと当てて、ジュクジュクのおま○こで肉竿にねぶってくる。"

[[dialogue]]
speaker = "unk"
# それがたまらなく気持ちよくてペニスが蕩けそうだ。デレデレのユウリに溶かされていく心地がピストンをさらに加速させていく。
line = "それがたまらなく気持ちよくてペニスが蕩けそうだ。デレデレのユウリに溶かされていく心地がピストンをさらに加速させていく。"

[[dialogue]]
speaker = "ユウリ"
# 「ふぁっ、あふぁっ<emoji=heart04>　きてるっ、えへへっ、ち○ちんすっげぇビクついてるぅっ<emoji=heart04>」
line = "「ふぁっ、あふぁっ<emoji=heart04>　きてるっ、えへへっ、ち○ちんすっげぇビクついてるぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「でももっとぉっ<emoji=heart04>　もっとち○ちんアツアツに火照らせてっ<emoji=heart04>　もっとあたしのおま○こ夢中で犯してっ<emoji=heart04>」
line = "「でももっとぉっ<emoji=heart04>　もっとち○ちんアツアツに火照らせてっ<emoji=heart04>　もっとあたしのおま○こ夢中で犯してっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「バニー姿、いくらでもオカズにしていいからっ<emoji=heart04>　ハメてっ<emoji=heart04>　もっとハメてっ<emoji=heart04>　いっぱい興奮してぇっ<emoji=heart04>」
line = "「バニー姿、いくらでもオカズにしていいからっ<emoji=heart04>　ハメてっ<emoji=heart04>　もっとハメてっ<emoji=heart04>　いっぱい興奮してぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 言われるまでもなくユウリのおま○こをハメまくる。
line = "言われるまでもなくユウリのおま○こをハメまくる。"

[[dialogue]]
speaker = "unk"
# セクシーなバニー姿を見下ろしながら、ピストンに喘ぎ悶える彼女の姿をオカズにしながら──
line = "セクシーなバニー姿を見下ろしながら、ピストンに喘ぎ悶える彼女の姿をオカズにしながら──"

[[dialogue]]
speaker = "ユウリ"
# 「はふあぁああっっ<emoji=heart04>　イクっ、イクイクっ<emoji=heart04>　あああああっっ<emoji=heart04>　はげしっ、気持ちっ、イくっ、イックぅぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「はふあぁああっっ<emoji=heart04>　イクっ、イクイクっ<emoji=heart04>　あああああっっ<emoji=heart04>　はげしっ、気持ちっ、イくっ、イックぅぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「しゅきっ、だいしゅきっ<emoji=heart04>　あふぁぁあっっ、ち○ちん熱いっ<emoji=heart04>　おま○こ焼けちゃっ、イクぅぅぅっっ～～<emoji=heart04>」
line = "「しゅきっ、だいしゅきっ<emoji=heart04>　あふぁぁあっっ、ち○ちん熱いっ<emoji=heart04>　おま○こ焼けちゃっ、イクぅぅぅっっ～～<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「んぁっ、あっ、イクイクっ<emoji=heart04>　爆発しそうなち○ちんで、あたしのおま○こ、イク、イっちゃうぅっっ<emoji=heart04><emoji=heart04>」
line = "「んぁっ、あっ、イクイクっ<emoji=heart04>　爆発しそうなち○ちんで、あたしのおま○こ、イク、イっちゃうぅっっ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「あふぁぁっっ<emoji=heart04>　くるっ<emoji=heart04>　くるくるっ<emoji=heart04>　くるくるくるぅぅっっ<emoji=heart04>」
line = "「あふぁぁっっ<emoji=heart04>　くるっ<emoji=heart04>　くるくるっ<emoji=heart04>　くるくるくるぅぅっっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「出してっ<emoji=heart04>　一滴残らず膣内に出してっ<emoji=heart04>　あたしのおま○こっ、彼氏精子で、ラブラブ精子でっっ<emoji=heart04>」
line = "「出してっ<emoji=heart04>　一滴残らず膣内に出してっ<emoji=heart04>　あたしのおま○こっ、彼氏精子で、ラブラブ精子でっっ<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「満タンにしてええぇぇぇっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「満タンにしてええぇぇぇっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「くふぁあああっっ<emoji=heart04>　あああああっっ<emoji=heart04>　あっ、あっ、んはぁああああっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「くふぁあああっっ<emoji=heart04>　あああああっっ<emoji=heart04>　あっ、あっ、んはぁああああっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「しゅごっ、あふぁあああっっ、いつもより熱いっ<emoji=heart04>　多いっ<emoji=heart04>　イくイくイくぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「しゅごっ、あふぁあああっっ、いつもより熱いっ<emoji=heart04>　多いっ<emoji=heart04>　イくイくイくぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「きもひいいっっ、しあわせぇっ、しゅきぃっ、んふぁぁぁっ、しゅきぃぃっっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「きもひいいっっ、しあわせぇっ、しゅきぃっ、んふぁぁぁっ、しゅきぃぃっっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「このままぜんぶだしへっ<emoji=heart04>　ぜったいぬかないでっ<emoji=heart04>　ずっとつながってたいっ、ぜんぶうけとめたいっ、しゃせーでもっとイキたいっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「このままぜんぶだしへっ<emoji=heart04>　ぜったいぬかないでっ<emoji=heart04>　ずっとつながってたいっ、ぜんぶうけとめたいっ、しゃせーでもっとイキたいっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 全身を激しく痙攣させながら、ユウリが震えるおま○こでペニスを咥え込んでくる。
line = "全身を激しく痙攣させながら、ユウリが震えるおま○こでペニスを咥え込んでくる。"

[[dialogue]]
speaker = "unk"
# ぎゅっと絞られる快感を貪りながら、俺も無我夢中で中出しし続ける。
line = "ぎゅっと絞られる快感を貪りながら、俺も無我夢中で中出しし続ける。"

[[dialogue]]
speaker = "unk"
# そして──
line = "そして──"

[[dialogue]]
speaker = "ユウリ"
# 「くはぁぁーっ、はぁーっ、はぁーっ、あふぁぁ……<emoji=heart04>　こんなに溢れるくらい、えへへ、注いでくれて……<emoji=heart04>」
line = "「くはぁぁーっ、はぁーっ、はぁーっ、あふぁぁ……<emoji=heart04>　こんなに溢れるくらい、えへへ、注いでくれて……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「バニー着るだけで、こんなに興奮してくれるんだ……<emoji=heart04>　あたしのバニー姿でこんなに発情してくれるんだ……<emoji=heart04>」
line = "「バニー着るだけで、こんなに興奮してくれるんだ……<emoji=heart04>　あたしのバニー姿でこんなに発情してくれるんだ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「えへへ、嬉しい……<emoji=heart04>　たまには、んふぁ……<emoji=heart04>　女の子らしい服着るの、ありかも……<emoji=heart04>」
line = "「えへへ、嬉しい……<emoji=heart04>　たまには、んふぁ……<emoji=heart04>　女の子らしい服着るの、ありかも……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 照れて拒んでいた姿はどこへやら、ユウリが幸せいっぱいの笑みを浮かべてくれる。
line = "照れて拒んでいた姿はどこへやら、ユウリが幸せいっぱいの笑みを浮かべてくれる。"

[[dialogue]]
speaker = "unk"
# でもきっと我に返ったらまた照れて取り乱してしまうんだろう。エッチを終えた後のユウリは照れ屋に拍車がかかるから。
line = "でもきっと我に返ったらまた照れて取り乱してしまうんだろう。エッチを終えた後のユウリは照れ屋に拍車がかかるから。"

[[dialogue]]
speaker = "unk"
# だけど──
line = "だけど──"

[[dialogue]]
speaker = "ユウリ"
# 「あっ……<emoji=heart04>　まだ抜いちゃヤダ……<emoji=heart04>　しばらくこのままでいて……<emoji=heart04>」
line = "「あっ……<emoji=heart04>　まだ抜いちゃヤダ……<emoji=heart04>　しばらくこのままでいて……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「もっとイチャイチャしてたい……<emoji=heart04>　大好きな人と繋がってたい……<emoji=heart04>」
line = "「もっとイチャイチャしてたい……<emoji=heart04>　大好きな人と繋がってたい……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「それとできたら、はぁはぁ、もっかいしたい……<emoji=heart04>　ううん、もっかいじゃなくて、もっともっとしたい……<emoji=heart04>」
line = "「それとできたら、はぁはぁ、もっかいしたい……<emoji=heart04>　ううん、もっかいじゃなくて、もっともっとしたい……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# だけど──だからこそデレデレなユウリが可愛くて仕方がない。
line = "だけど──だからこそデレデレなユウリが可愛くて仕方がない。"

[[dialogue]]
speaker = "unk"
# この後、我に返って焦る姿を想像するとさらに愛しさが膨れあがってくる。
line = "この後、我に返って焦る姿を想像するとさらに愛しさが膨れあがってくる。"

[[dialogue]]
speaker = "ユウリ"
# 「今度はあたしが上がいい……<emoji=heart04>　繋がったままあたしのこと抱き上げて……？」
line = "「今度はあたしが上がいい……<emoji=heart04>　繋がったままあたしのこと抱き上げて……？」"

[[dialogue]]
speaker = "ユウリ"
# 「そんで二回戦……しよ<emoji=heart04>　してくれなきゃ、許さないから……<emoji=heart04>」
line = "「そんで二回戦……しよ<emoji=heart04>　してくれなきゃ、許さないから……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 閉店作業が遅れた理由を何か考えておこう。
line = "閉店作業が遅れた理由を何か考えておこう。"

[[dialogue]]
speaker = "unk"
# そうして唇を尖らせて甘えてくるユウリに唇を重ねながら、俺は可愛い彼女を抱き起こした。
line = "そうして唇を尖らせて甘えてくるユウリに唇を重ねながら、俺は可愛い彼女を抱き起こした。"
