[[dialogue]]
speaker = "unk"
# 第４話,海デート！,P
line = "第４話,海デート！,P"

[[dialogue]]
speaker = "フィオナ"
# 「星徒会活動お疲れ様です。緋宮会長もティータイムですか？」
line = "「星徒会活動お疲れ様です。緋宮会長もティータイムですか？」"

[[dialogue]]
speaker = "フィオナ"
# 「私は今日は紅茶とビスケットを。スコーンもおすすめですよ」
line = "「私は今日は紅茶とビスケットを。スコーンもおすすめですよ」"

[[dialogue]]
speaker = "フィオナ"
# 「そういえば、サーフィン勝負で緋宮会長が勝ったのに、私に何をしてほしいかまだ聞いていませんね」
line = "「そういえば、サーフィン勝負で緋宮会長が勝ったのに、私に何をしてほしいかまだ聞いていませんね」"

[[dialogue]]
speaker = "フィオナ"
# 「あれは恨みっこなしの真剣勝負。私が言い出したことでもありますし、遠慮はいりませんよ」
line = "「あれは恨みっこなしの真剣勝負。私が言い出したことでもありますし、遠慮はいりませんよ」"

[[dialogue]]
speaker = "unk"
# 俺とデートしてほしい
line = "俺とデートしてほしい"

[[dialogue]]
speaker = "フィオナ"
# 「はい、デートですね。もちろん大丈夫ですよ。今週末に──」
line = "「はい、デートですね。もちろん大丈夫ですよ。今週末に──」"

[[dialogue]]
speaker = "フィオナ"
# 「デ、デート！？」
line = "「デ、デート！？」"

[[dialogue]]
speaker = "フィオナ"
# 「こ、こんにちは……」
line = "「こ、こんにちは……」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長と２人きりになったことは今までもありますけど、改めてデートだと思うと照れますね……」
line = "「緋宮会長と２人きりになったことは今までもありますけど、改めてデートだと思うと照れますね……」"

[[dialogue]]
speaker = "unk"
# ここはリップルが新たに作った、２人きりになれるデート用の結界。
line = "ここはリップルが新たに作った、２人きりになれるデート用の結界。"

[[dialogue]]
speaker = "unk"
# 名付けて“ラブラブシーサイド結界”。
line = "名付けて“ラブラブシーサイド結界”。"

[[dialogue]]
speaker = "unk"
# なんでも「街でカップルを見て思イツキました！」とのことで、ロマンチックな雰囲気になるよう時間を夕方に固定してあるのだとか。
line = "なんでも「街でカップルを見て思イツキました！」とのことで、ロマンチックな雰囲気になるよう時間を夕方に固定してあるのだとか。"

[[dialogue]]
speaker = "フィオナ"
# 「せっかくの海ですし、水遊びしましょうか！」
line = "「せっかくの海ですし、水遊びしましょうか！」"

[[dialogue]]
speaker = "フィオナ"
# 「……って、そんな雰囲気でもないですか。あはは……」
line = "「……って、そんな雰囲気でもないですか。あはは……」"

[[dialogue]]
speaker = "フィオナ"
# 「デートって何をすればいいんでしょうか。私、昔から使命を果たすことばかり考えていたので、そういうのには疎くて……」
line = "「デートって何をすればいいんでしょうか。私、昔から使命を果たすことばかり考えていたので、そういうのには疎くて……」"

[[dialogue]]
speaker = "フィオナ"
# 「デートに誘ったのは緋宮会長ですし……緋宮会長ならわかりますか？」
line = "「デートに誘ったのは緋宮会長ですし……緋宮会長ならわかりますか？」"

[[dialogue]]
speaker = "unk"
# 俺もよくわからない
line = "俺もよくわからない"

[[dialogue]]
speaker = "フィオナ"
# 「わからないんですかっ」
line = "「わからないんですかっ」"

[[dialogue]]
speaker = "unk"
# それでもフィオナとデートしたかったから
line = "それでもフィオナとデートしたかったから"

[[dialogue]]
speaker = "フィオナ"
# 「！？　そんなこと言われたら……うぅ、ずるいです……」
line = "「！？　そんなこと言われたら……うぅ、ずるいです……」"

[[dialogue]]
speaker = "unk"
# 一緒にデートらしいことを考えていこう
line = "一緒にデートらしいことを考えていこう"

[[dialogue]]
speaker = "フィオナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ、そうですね。わからないなら模索していけばいいんですから」
line = "「ふふ、そうですね。わからないなら模索していけばいいんですから」"

[[dialogue]]
speaker = "フィオナ"
# 「じゃあ……手をつなぎませんか？　これは間違いなくデートっぽいですよ。では失礼して……」
line = "「じゃあ……手をつなぎませんか？　これは間違いなくデートっぽいですよ。では失礼して……」"

[[dialogue]]
speaker = "フィオナ"
# 「にぎにぎ」
line = "「にぎにぎ」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長の手、大きくてたくましいですね。男性の手です」
line = "「緋宮会長の手、大きくてたくましいですね。男性の手です」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長は拳で戦いますから、この手が世界を守ってるんですよね。ふふふ、この手にはいつも助けられてます。ありがとうございます」
line = "「緋宮会長は拳で戦いますから、この手が世界を守ってるんですよね。ふふふ、この手にはいつも助けられてます。ありがとうございます」"

[[dialogue]]
speaker = "フィオナ"
# 「ふむふむ、思ったより硬い手触りなんですね。不思議と安心できて……この感触、私好きです」
line = "「ふむふむ、思ったより硬い手触りなんですね。不思議と安心できて……この感触、私好きです」"

[[dialogue]]
speaker = "フィオナ"
# 「──って、いつまで握ってるんだって感じですよね……」
line = "「──って、いつまで握ってるんだって感じですよね……」"

[[dialogue]]
speaker = "フィオナ"
# 「え？　デートなんだからずっと握っていてもいい……？　それなら遠慮なく……」
line = "「え？　デートなんだからずっと握っていてもいい……？　それなら遠慮なく……」"

[[dialogue]]
speaker = "フィオナ"
# 「にぎにぎ……にぎにぎ……えへへ。いいですね、デート」
line = "「にぎにぎ……にぎにぎ……えへへ。いいですね、デート」"

[[dialogue]]
speaker = "フィオナ"
# 「次は……ビーチを散歩？　確かにデートらしいです。せっかくですから、手をつないだまま、ゆっくり歩きましょうか」
line = "「次は……ビーチを散歩？　確かにデートらしいです。せっかくですから、手をつないだまま、ゆっくり歩きましょうか」"

[[dialogue]]
speaker = "フィオナ"
# 「ビーチをぐるりと一周しましたけど、小さな島になっていて、本当に私たちしかいないんですね。結界の主であるリップルさんはどこかにいるのかもしれませんが」
line = "「ビーチをぐるりと一周しましたけど、小さな島になっていて、本当に私たちしかいないんですね。結界の主であるリップルさんはどこかにいるのかもしれませんが」"

[[dialogue]]
speaker = "フィオナ"
# 「夕暮れの海で２人きり……この広い世界で私とあなただけになってしまったみたいです」
line = "「夕暮れの海で２人きり……この広い世界で私とあなただけになってしまったみたいです」"

[[dialogue]]
speaker = "フィオナ"
# 「こんなシチュエーションだとつい大胆になってしまうかもしれません。たとえば……」
line = "「こんなシチュエーションだとつい大胆になってしまうかもしれません。たとえば……」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長を閉じ込めて独り占めしてしまうとか」
line = "「緋宮会長を閉じ込めて独り占めしてしまうとか」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ♪　そんなに驚かないでください、冗談ですよ。そういうのじゃなくて──」
line = "「ふふ♪　そんなに驚かないでください、冗談ですよ。そういうのじゃなくて──」"

[[dialogue]]
speaker = "フィオナ"
# 「ちゅっ」
line = "「ちゅっ」"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長の希望でデートしたんですから、ちゃんとドキッとしてもらわないといけません」
line = "「緋宮会長の希望でデートしたんですから、ちゃんとドキッとしてもらわないといけません」"

[[dialogue]]
speaker = "フィオナ"
# 「今日のデート、満足していただけましたか？」
line = "「今日のデート、満足していただけましたか？」"

[[dialogue]]
speaker = "unk"
# ……もちろん
line = "……もちろん"

[[dialogue]]
speaker = "フィオナ"
# 「さすがの緋宮会長も照れていますね。そうでなくては女の子として自信をなくしてしまいます。私だって恥ずかしかったんですから」
line = "「さすがの緋宮会長も照れていますね。そうでなくては女の子として自信をなくしてしまいます。私だって恥ずかしかったんですから」"

[[dialogue]]
speaker = "フィオナ"
# 「……私も緋宮会長とのデート、とても楽しかったです」
line = "「……私も緋宮会長とのデート、とても楽しかったです」"

[[dialogue]]
speaker = "フィオナ"
# 「勝負とは関係なく、海でも他の場所でも……またデートに行きましょうね」
line = "「勝負とは関係なく、海でも他の場所でも……またデートに行きましょうね」"
