[[dialogue]]
speaker = "unk"
# 第３話,お嫁さんＶＳ師匠,P
line = "第３話,お嫁さんＶＳ師匠,P"

[[dialogue]]
speaker = "unk"
# とある昼休み。最近は蘭美と一緒にランチを食べるのが定番になっていた。
line = "とある昼休み。最近は蘭美と一緒にランチを食べるのが定番になっていた。"

[[dialogue]]
speaker = "蘭美"
# 「はい、あーんして<emoji=heart04>」
line = "「はい、あーんして<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# あーん<emoji=heart04>
line = "あーん<emoji=heart04>"

[[dialogue]]
speaker = "蘭美"
# 「ふふっ、よく噛んで食べるのよ。好き嫌いもよくないわ。バランスよく食べることが大事なんだから」
line = "「ふふっ、よく噛んで食べるのよ。好き嫌いもよくないわ。バランスよく食べることが大事なんだから」"

[[dialogue]]
speaker = "蘭美"
# 「……待ちなさい、ニンジンが残ってるわよ。もしかしてニンジンが食べられない、なんてことは……」
line = "「……待ちなさい、ニンジンが残ってるわよ。もしかしてニンジンが食べられない、なんてことは……」"

[[dialogue]]
speaker = "unk"
# でも、蘭美の好物だから
line = "でも、蘭美の好物だから"

[[dialogue]]
speaker = "unk"
# むしろニンジンは好きだよ
line = "むしろニンジンは好きだよ"

[[dialogue]]
speaker = "蘭美"
# 「あら、私のために取っておいてくれたのね。それなら喜んで頂くわ」
line = "「あら、私のために取っておいてくれたのね。それなら喜んで頂くわ」"

[[dialogue]]
speaker = "蘭美"
# 「もちろん……私に食べさせてくれるのよね？　じゃあ、はい、あーん……<emoji=heart04>」
line = "「もちろん……私に食べさせてくれるのよね？　じゃあ、はい、あーん……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# って、あれ、キリカさん？
line = "って、あれ、キリカさん？"

[[dialogue]]
speaker = "unk"
# あーん──
line = "あーん──"

[[dialogue]]
speaker = "キリカ"
# 「ごきげんよう、緋宮会長。それと……羽宮様も」
line = "「ごきげんよう、緋宮会長。それと……羽宮様も」"

[[dialogue]]
speaker = "蘭美"
# 「なかなかいいタイミングで現れるわね、上月キリカ……」
line = "「なかなかいいタイミングで現れるわね、上月キリカ……」"

[[dialogue]]
speaker = "蘭美"
# 「星見家のメイド長が学園に顔を出すなんて珍しい、何か急用でもあったのかしら？」
line = "「星見家のメイド長が学園に顔を出すなんて珍しい、何か急用でもあったのかしら？」"

[[dialogue]]
speaker = "キリカ"
# 「フィオナお嬢様の遣いで、新星の学園長代理に少々。用件も済みましたので、こちらで昼食を摂ろうと思ったのです」
line = "「フィオナお嬢様の遣いで、新星の学園長代理に少々。用件も済みましたので、こちらで昼食を摂ろうと思ったのです」"

[[dialogue]]
speaker = "蘭美"
# 「あら、そうなのね。だったら一緒にどうかしら？」
line = "「あら、そうなのね。だったら一緒にどうかしら？」"

[[dialogue]]
speaker = "キリカ"
# 「羽宮様のお邪魔になりませんか？」
line = "「羽宮様のお邪魔になりませんか？」"

[[dialogue]]
speaker = "蘭美"
# 「今は会長との２人きりの時間を楽しんでいたところだけど、別に邪魔だなんて思ってはいないわ」
line = "「今は会長との２人きりの時間を楽しんでいたところだけど、別に邪魔だなんて思ってはいないわ」"

[[dialogue]]
speaker = "キリカ"
# 「本心を隠しきれていないように思うのですが……。やはり私は遠慮いたしましょう」
line = "「本心を隠しきれていないように思うのですが……。やはり私は遠慮いたしましょう」"

[[dialogue]]
speaker = "蘭美"
# 「いいから座りなさい。そうね、これは貴方に、私と会長の仲の良さを見せつける絶好のチャンスかもしれないわ！」
line = "「いいから座りなさい。そうね、これは貴方に、私と会長の仲の良さを見せつける絶好のチャンスかもしれないわ！」"

[[dialogue]]
speaker = "キリカ"
# 「羽宮様と会長との交際は順調のようですね。仲睦まじいと、流星学園でも噂になっていますよ」
line = "「羽宮様と会長との交際は順調のようですね。仲睦まじいと、流星学園でも噂になっていますよ」"

[[dialogue]]
speaker = "蘭美"
# 「あら、流星学園にまでそんな噂が流れているの？」
line = "「あら、流星学園にまでそんな噂が流れているの？」"

[[dialogue]]
speaker = "キリカ"
# 「お困りであれば、噂を消しましょうか？」
line = "「お困りであれば、噂を消しましょうか？」"

[[dialogue]]
speaker = "蘭美"
# 「結構よ！　会長と仲良しなのは事実なんだし、わざわざ火消しをする必要はないわ！」
line = "「結構よ！　会長と仲良しなのは事実なんだし、わざわざ火消しをする必要はないわ！」"

[[dialogue]]
speaker = "蘭美"
# 「それよりも……１つ気になっていたことがあるの。いい機会だから言わせてもらうわ」
line = "「それよりも……１つ気になっていたことがあるの。いい機会だから言わせてもらうわ」"

[[dialogue]]
speaker = "蘭美"
# 「上月キリカ、貴方もウェディングフォームを所有しているのよね？」
line = "「上月キリカ、貴方もウェディングフォームを所有しているのよね？」"

[[dialogue]]
speaker = "蘭美"
# 「貴方の戦闘技術とウェディングフォームが組み合わさったら、とんでもないことになるはず……興味があるわ、ぜひ手合わせを願いたいものね」
line = "「貴方の戦闘技術とウェディングフォームが組み合わさったら、とんでもないことになるはず……興味があるわ、ぜひ手合わせを願いたいものね」"

[[dialogue]]
speaker = "キリカ"
# 「……九浄家が人工戦闘服のウェディングフォームを開発したという話は耳に届いています」
line = "「……九浄家が人工戦闘服のウェディングフォームを開発したという話は耳に届いています」"

[[dialogue]]
speaker = "キリカ"
# 「お望みであれば、いつでもどうぞ」
line = "「お望みであれば、いつでもどうぞ」"

[[dialogue]]
speaker = "蘭美"
# 「ふっ……自信たっぷりのようね、でも私のウェディングフォームの方が上なのは明白なんだからっ！」
line = "「ふっ……自信たっぷりのようね、でも私のウェディングフォームの方が上なのは明白なんだからっ！」"

[[dialogue]]
speaker = "キリカ"
# 「断言する理由を伺っても？」
line = "「断言する理由を伺っても？」"

[[dialogue]]
speaker = "蘭美"
# 「それはもちろん！　彼の存在よ！」
line = "「それはもちろん！　彼の存在よ！」"

[[dialogue]]
speaker = "unk"
# お、俺ぇ！？
line = "お、俺ぇ！？"

[[dialogue]]
speaker = "蘭美"
# 「ウェディングフォームはその名の通り、花嫁衣装がモチーフになっているわ。だからこそ、伴侶の存在が力になる！」
line = "「ウェディングフォームはその名の通り、花嫁衣装がモチーフになっているわ。だからこそ、伴侶の存在が力になる！」"

[[dialogue]]
speaker = "蘭美"
# 「『<ruby=エム　オー　エム>Ｍ・Ｏ・Ｍ</ruby>』では惜敗を喫したけれど、ウェディングフォーム対決なら私に分があるわ！」
line = "「『<ruby>Ｍ・Ｏ・Ｍ<rt>エム　オー　エム</rt></ruby>』では惜敗を喫したけれど、ウェディングフォーム対決なら私に分があるわ！」"

[[dialogue]]
speaker = "蘭美"
# 「ふふっ、どうかしら？　私には彼がついているのよ。恋人であり、婚約者であり、未来の旦那様……」
line = "「ふふっ、どうかしら？　私には彼がついているのよ。恋人であり、婚約者であり、未来の旦那様……」"

[[dialogue]]
speaker = "蘭美"
# 「こうして触れているだけで、力が漲ってくるわ。これぞ愛のパワー！」
line = "「こうして触れているだけで、力が漲ってくるわ。これぞ愛のパワー！」"

[[dialogue]]
speaker = "蘭美"
# 「お嫁さんになった私には、たとえ『マスターメイド』の称号を持つ貴方であろうと絶対勝てないんだから！」
line = "「お嫁さんになった私には、たとえ『マスターメイド』の称号を持つ貴方であろうと絶対勝てないんだから！」"

[[dialogue]]
speaker = "キリカ"
# 「なるほど、理解しました」
line = "「なるほど、理解しました」"

[[dialogue]]
speaker = "キリカ"
# 「しかし……婚約者の立場なら、まだお嫁さんとは名乗れないのでは？」
line = "「しかし……婚約者の立場なら、まだお嫁さんとは名乗れないのでは？」"

[[dialogue]]
speaker = "蘭美"
# 「四捨五入すればラブラブ夫婦よ！」
line = "「四捨五入すればラブラブ夫婦よ！」"

[[dialogue]]
speaker = "蘭美"
# 「ほら、こんなことだってしちゃうのよ？　むぎゅ～～～っ<emoji=heart04>」
line = "「ほら、こんなことだってしちゃうのよ？　むぎゅ～～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "キリカ"
# 「……ふむ、ラブラブですね」
line = "「……ふむ、ラブラブですね」"

[[dialogue]]
speaker = "蘭美"
# 「こんなの私と会長には日常茶飯事なのよ。くっつくのだって、抱き締め合うのだって、特別じゃなく日常なんだから！」
line = "「こんなの私と会長には日常茶飯事なのよ。くっつくのだって、抱き締め合うのだって、特別じゃなく日常なんだから！」"

[[dialogue]]
speaker = "蘭美"
# 「さあ、どうかしら？　降参するなんて興ざめなことは言わないわよね！」
line = "「さあ、どうかしら？　降参するなんて興ざめなことは言わないわよね！」"

[[dialogue]]
speaker = "キリカ"
# 「私としては降参しても構わないのですが、一方的に敗北することは、主であるフィオナお嬢様の名誉を汚すことになります……なので、１つだけ」
line = "「私としては降参しても構わないのですが、一方的に敗北することは、主であるフィオナお嬢様の名誉を汚すことになります……なので、１つだけ」"

[[dialogue]]
speaker = "キリカ"
# 「私は会長の、武の師匠ですよ？」
line = "「私は会長の、武の師匠ですよ？」"

[[dialogue]]
speaker = "蘭美"
# 「し、師匠！？　そのカードはズルだぴょん！？」
line = "「し、師匠！？　そのカードはズルだぴょん！？」"

[[dialogue]]
speaker = "キリカ"
# 「その言葉、そっくりお返しします」
line = "「その言葉、そっくりお返しします」"

[[dialogue]]
speaker = "蘭美"
# 「師弟というのも特別な関係……恋人とはまた別の強い絆があるなんて、やはり侮れない強敵だわ」
line = "「師弟というのも特別な関係……恋人とはまた別の強い絆があるなんて、やはり侮れない強敵だわ」"

[[dialogue]]
speaker = "unk"
# 俺にとっては蘭美が一番だから
line = "俺にとっては蘭美が一番だから"

[[dialogue]]
speaker = "蘭美"
# 「ありがとう、会長！　とっても嬉しいわ」
line = "「ありがとう、会長！　とっても嬉しいわ」"

[[dialogue]]
speaker = "蘭美"
# 「私も会長のことが、世界で一番大好きよ！」
line = "「私も会長のことが、世界で一番大好きよ！」"

[[dialogue]]
speaker = "キリカ"
# 「……そろそろお暇してもいいでしょうか？」
line = "「……そろそろお暇してもいいでしょうか？」"

[[dialogue]]
speaker = "蘭美"
# 「だけど残念ながら、その『一番』という評価は会長の主観でしかない。客観的に私の方が上であることを証明する必要があるわ！」
line = "「だけど残念ながら、その『一番』という評価は会長の主観でしかない。客観的に私の方が上であることを証明する必要があるわ！」"

[[dialogue]]
speaker = "キリカ"
# 「それは本当に証明しなければならないことでしょうか？」
line = "「それは本当に証明しなければならないことでしょうか？」"

[[dialogue]]
speaker = "蘭美"
# 「これはプライドの問題よ！　お嫁さんと師匠、どちらがすごいか見せてあげる！」
line = "「これはプライドの問題よ！　お嫁さんと師匠、どちらがすごいか見せてあげる！」"

[[dialogue]]
speaker = "蘭美"
# 「師匠には無理で、お嫁さんにしかできないこと……何があるかしら……」
line = "「師匠には無理で、お嫁さんにしかできないこと……何があるかしら……」"

[[dialogue]]
speaker = "unk"
# 土俵がそもそも違うんじゃ……
line = "土俵がそもそも違うんじゃ……"

[[dialogue]]
speaker = "unk"
# お嫁さんＶＳ師匠って
line = "お嫁さんＶＳ師匠って"

[[dialogue]]
speaker = "蘭美"
# 「抱擁、はどうかしら。ギュッと抱きしめ合うのは恋人同士の特権でしょう？」
line = "「抱擁、はどうかしら。ギュッと抱きしめ合うのは恋人同士の特権でしょう？」"

[[dialogue]]
speaker = "キリカ"
# 「場合によっては師匠と弟子も抱き合うことはあるのでは？」
line = "「場合によっては師匠と弟子も抱き合うことはあるのでは？」"

[[dialogue]]
speaker = "蘭美"
# 「えぇっ！？　したのぉ！？」
line = "「えぇっ！？　したのぉ！？」"

[[dialogue]]
speaker = "unk"
# し、してないっ！
line = "し、してないっ！"

[[dialogue]]
speaker = "蘭美"
# 「そ、そうよね！　でも確かにシチュエーションによっては、師匠と弟子の抱擁はあるわね」
line = "「そ、そうよね！　でも確かにシチュエーションによっては、師匠と弟子の抱擁はあるわね」"

[[dialogue]]
speaker = "蘭美"
# 「ではデートはどうかしら？　肩を並べて仲良くショッピングなんて師匠と弟子ではありえないでしょう！」
line = "「ではデートはどうかしら？　肩を並べて仲良くショッピングなんて師匠と弟子ではありえないでしょう！」"

[[dialogue]]
speaker = "キリカ"
# 「普通にあると思います。一緒に竹刀を選んだり、トレーニングに適したシューズを探したり……」
line = "「普通にあると思います。一緒に竹刀を選んだり、トレーニングに適したシューズを探したり……」"

[[dialogue]]
speaker = "蘭美"
# 「えぇっ！？　したのぉ！？」
line = "「えぇっ！？　したのぉ！？」"

[[dialogue]]
speaker = "unk"
# し、してないって！
line = "し、してないって！"

[[dialogue]]
speaker = "蘭美"
# 「だったら、だったら……そうね……キス！　キスはどうかしら！」
line = "「だったら、だったら……そうね……キス！　キスはどうかしら！」"

[[dialogue]]
speaker = "キリカ"
# 「……………………」
line = "「……………………」"

[[dialogue]]
speaker = "蘭美"
# 「軽くチュッっていうのじゃないわよ、ちゃんと恋人同士で愛を確かめ合うキス！　これならどうかしら！」
line = "「軽くチュッっていうのじゃないわよ、ちゃんと恋人同士で愛を確かめ合うキス！　これならどうかしら！」"

[[dialogue]]
speaker = "キリカ"
# 「それは、ありませんね。恋人という関係だけのものです」
line = "「それは、ありませんね。恋人という関係だけのものです」"

[[dialogue]]
speaker = "蘭美"
# 「そうよね！　ふふんっ、師弟ＶＳ恋人、どうやら軍配が上がったのは恋人の方だったようね！」
line = "「そうよね！　ふふんっ、師弟ＶＳ恋人、どうやら軍配が上がったのは恋人の方だったようね！」"

[[dialogue]]
speaker = "キリカ"
# 「では、今からお２人の恋人ぶりを見せて頂ける、と……そういうことでしょうか？」
line = "「では、今からお２人の恋人ぶりを見せて頂ける、と……そういうことでしょうか？」"

[[dialogue]]
speaker = "蘭美"
# 「えぇっ！？　するのぉ！？」
line = "「えぇっ！？　するのぉ！？」"

[[dialogue]]
speaker = "unk"
# …………どうする？
line = "…………どうする？"

[[dialogue]]
speaker = "蘭美"
# 「も、もちろんいいわ！」
line = "「も、もちろんいいわ！」"

[[dialogue]]
speaker = "unk"
# いいのっ！？
line = "いいのっ！？"

[[dialogue]]
speaker = "蘭美"
# 「ここまで来たら後には引けないわ！　勝利のために腹を括りなさいっ」
line = "「ここまで来たら後には引けないわ！　勝利のために腹を括りなさいっ」"

[[dialogue]]
speaker = "蘭美"
# 「んーーーっ………………………ちゅっ<emoji=heart04>」
line = "「んーーーっ………………………ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「んっ……………………ちゅ<emoji=heart04>　も、もっと……ちゅ<emoji=heart04>　ちゅっ<emoji=heart04>　ちゅ～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「んっ……………………ちゅ<emoji=heart04>　も、もっと……ちゅ<emoji=heart04>　ちゅっ<emoji=heart04>　ちゅ～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "蘭美"
# 「はぁ……はぁ……目に焼き付けたかしら？　これが私たちの愛の絆よ！」
line = "「はぁ……はぁ……目に焼き付けたかしら？　これが私たちの愛の絆よ！」"

[[dialogue]]
speaker = "キリカ"
# 「はい……まさか本当にするとは……羽宮様の執念に感服しました」
line = "「はい……まさか本当にするとは……羽宮様の執念に感服しました」"

[[dialogue]]
speaker = "蘭美"
# 「そ、そう？」
line = "「そ、そう？」"

[[dialogue]]
speaker = "キリカ"
# 「ここまでされてしまったら素直に敗北を認めましょう。きっとフィオナお嬢様もお許しくださるはずです」
line = "「ここまでされてしまったら素直に敗北を認めましょう。きっとフィオナお嬢様もお許しくださるはずです」"

[[dialogue]]
speaker = "キリカ"
# 「ですが、こういった行為は人前では控えた方がよろしいかと思いますよ」
line = "「ですが、こういった行為は人前では控えた方がよろしいかと思いますよ」"

[[dialogue]]
speaker = "蘭美"
# 「うっ……」
line = "「うっ……」"

[[dialogue]]
speaker = "unk"
# 冷静な忠告を受けて我に返る。
line = "冷静な忠告を受けて我に返る。"

[[dialogue]]
speaker = "unk"
# 大胆過ぎる公開キスに周囲の注目を集めまくりだった。
line = "大胆過ぎる公開キスに周囲の注目を集めまくりだった。"

[[dialogue]]
speaker = "unk"
# 結局その後はいたたまれなくなって、逃げるようにカフェテリアを後にしたのだった。
line = "結局その後はいたたまれなくなって、逃げるようにカフェテリアを後にしたのだった。"
