[[dialogue]]
speaker = "unk"
# 晴れ着姿でおめかしをしたヴィーナスとの、新年デートの帰り道──
line = "晴れ着姿でおめかしをしたヴィーナスとの、新年デートの帰り道──"

[[dialogue]]
speaker = "ヴィーナス"
# 「今夜は私の家に泊まっていきなさい！」
line = "「今夜は私の家に泊まっていきなさい！」"

[[dialogue]]
speaker = "クロト"
# 「また急だな……！？　でも俺、泊まりの準備なんてしてないぞ」
line = "「また急だな……！？　でも俺、泊まりの準備なんてしてないぞ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「大丈夫！　九浄の家は客間もいっぱいあるし。ヘレナちゃんにも連絡はすんでるわ！」
line = "「大丈夫！　九浄の家は客間もいっぱいあるし。ヘレナちゃんにも連絡はすんでるわ！」"

[[dialogue]]
speaker = "unk"
# そうしてヴィーナスに連れられ九浄家の門をくぐり、離れのふすまを開けると──
line = "そうしてヴィーナスに連れられ九浄家の門をくぐり、離れのふすまを開けると──"

[[dialogue]]
speaker = "クロト"
# 「って、何だこれ……！？」
line = "「って、何だこれ……！？」"

[[dialogue]]
speaker = "unk"
# 布団が２つ並べて敷いてあった。俺たちをからかうヘレナさんのイタズラだろうか。あの人にも困ったものだな、なんて思った矢先……
line = "布団が２つ並べて敷いてあった。俺たちをからかうヘレナさんのイタズラだろうか。あの人にも困ったものだな、なんて思った矢先……"

[[dialogue]]
speaker = "unk"
# 部屋の隅で、何か妙なものが焚かれていることに気が付いた。
line = "部屋の隅で、何か妙なものが焚かれていることに気が付いた。"

[[dialogue]]
speaker = "unk"
# 甘ったるく、肌に貼りつくような感触のする……お香？
line = "甘ったるく、肌に貼りつくような感触のする……お香？"

[[dialogue]]
speaker = "ヴィーナス"
# 「あ、あれ……この匂い、思ってたより凄すぎ……は、あぁぁっ<emoji=heart04>　ムラムラ、して……ど、ドキドキ、してきちゃった……？<emoji=heart04>」
line = "「あ、あれ……この匂い、思ってたより凄すぎ……は、あぁぁっ<emoji=heart04>　ムラムラ、して……ど、ドキドキ、してきちゃった……？<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# お香の匂いを吸い込むたびに、何だかソワソワと妙な気分になってきた俺たちは、お互い目が合った途端、抱き合って、服を無言で脱がせあって──
line = "お香の匂いを吸い込むたびに、何だかソワソワと妙な気分になってきた俺たちは、お互い目が合った途端、抱き合って、服を無言で脱がせあって──"

[[dialogue]]
speaker = "ヴィーナス"
# 「はぁあぁーっ……はぁぁあーっ……お、お願いぃっ……おち○ちん……おち○ちん欲しいのぉっ……<emoji=heart04>」
line = "「はぁあぁーっ……はぁぁあーっ……お、お願いぃっ……おち○ちん……おち○ちん欲しいのぉっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# とろとろに濡れそぼった女性器を見せつけながら、ヴィーナスがまるいお尻をフリフリと揺すっている。
line = "とろとろに濡れそぼった女性器を見せつけながら、ヴィーナスがまるいお尻をフリフリと揺すっている。"

[[dialogue]]
speaker = "unk"
# あのお香のせいなのは間違いない──嗅いだだけで性欲を昂らせるだなんてとんでもない代物だ。
line = "あのお香のせいなのは間違いない──嗅いだだけで性欲を昂らせるだなんてとんでもない代物だ。"

[[dialogue]]
speaker = "unk"
# でも──もうここまで興奮してしまったら、途中でやめるだなんて不可能だった。
line = "でも──もうここまで興奮してしまったら、途中でやめるだなんて不可能だった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふあぁあっ……おち○ちん、すごい。硬ぁい……ふぅう、ふぅうっ……お、お尻でスリスリするだけで、気持ち、いぃっ……<emoji=heart04>」
line = "「ふあぁあっ……おち○ちん、すごい。硬ぁい……ふぅう、ふぅうっ……お、お尻でスリスリするだけで、気持ち、いぃっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ちょ、ちょっと……う、うぁッ──！？」
line = "「ちょ、ちょっと……う、うぁッ──！？」"

[[dialogue]]
speaker = "unk"
# ヴィーナスのお尻が、俺のペニスの裏筋を撫でてくる──油断したらそれだけで射精してしまいそう。
line = "ヴィーナスのお尻が、俺のペニスの裏筋を撫でてくる──油断したらそれだけで射精してしまいそう。"

[[dialogue]]
speaker = "ヴィーナス"
# 「こ、これ、欲しいのっ……あなたのおち○ちん、ずぷぅぅってして……はぁぁ、いっぱいぱんぱん、して欲しいのぉ……<emoji=heart04>」
line = "「こ、これ、欲しいのっ……あなたのおち○ちん、ずぷぅぅってして……はぁぁ、いっぱいぱんぱん、して欲しいのぉ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 酔っぱらったような声でお尻を振って、ピストンをねだってくるヴィーナスを見て──火が点いた。
line = "酔っぱらったような声でお尻を振って、ピストンをねだってくるヴィーナスを見て──火が点いた。"

[[dialogue]]
speaker = "unk"
# まるで吸い寄せられるみたいに、今まで幾度となく愛してきた彼女の秘部へペニスを挿入する──
line = "まるで吸い寄せられるみたいに、今まで幾度となく愛してきた彼女の秘部へペニスを挿入する──"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふぅううッ──あ、あ、ぁ、あ、あぁあ～～～～っ！？<emoji=heart04>」
line = "「ふぅううッ──あ、あ、ぁ、あ、あぁあ～～～～っ！？<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「う、ぁあぁっ……な、なんだ、これっ……濡れ、すぎっ……！？」
line = "「う、ぁあぁっ……な、なんだ、これっ……濡れ、すぎっ……！？」"

[[dialogue]]
speaker = "unk"
# 挿入しただけで絶頂してしまうヴィーナス。背中を弓なりに反らせてビクビクと震えて、その振動がペニスに走っただけで俺までイキそうになる。
line = "挿入しただけで絶頂してしまうヴィーナス。背中を弓なりに反らせてビクビクと震えて、その振動がペニスに走っただけで俺までイキそうになる。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ぁあぁああっ……はぁあぁあ～っ……<emoji=heart04>　な、何これ、何これぇっ……いつもより、おち○ちん、感じる、ぅっ<emoji=heart04>」
line = "「ぁあぁああっ……はぁあぁあ～っ……<emoji=heart04>　な、何これ、何これぇっ……いつもより、おち○ちん、感じる、ぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナス、ちょっと……力、抜いてくれっ……！」
line = "「ヴィーナス、ちょっと……力、抜いてくれっ……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「む、無理ぃっ……あ、ぁぁぁ、ぁっ<emoji=heart04>　あなたのおち○ちん、好きだものぉっ……は、離したくない、からぁっ……！」
line = "「む、無理ぃっ……あ、ぁぁぁ、ぁっ<emoji=heart04>　あなたのおち○ちん、好きだものぉっ……は、離したくない、からぁっ……！」"

[[dialogue]]
speaker = "unk"
# また男心をくすぐるようなことを……！　ヴィーナスを感じさせたい。俺の、可愛くて仕方のない、エッチな彼女を愛したい。
line = "また男心をくすぐるようなことを……！　ヴィーナスを感じさせたい。俺の、可愛くて仕方のない、エッチな彼女を愛したい。"

[[dialogue]]
speaker = "unk"
# 強い気持ちに背中を押されて──動く。
line = "強い気持ちに背中を押されて──動く。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あ、ぁあ、あぁ、あぁ～っ<emoji=heart04>　おち○ちん、ふあ、あぁあっ<emoji=heart04>　気持ちいいところ、す、すっごく、当たる、ふぁ、あぁあ、ぁっ<emoji=heart04>」
line = "「あ、ぁあ、あぁ、あぁ～っ<emoji=heart04>　おち○ちん、ふあ、あぁあっ<emoji=heart04>　気持ちいいところ、す、すっごく、当たる、ふぁ、あぁあ、ぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「も、もっと深いところ、してっ<emoji=heart04>　お尻掴んで、ぐい、ぐいぐいって、奥、してぇっ<emoji=heart04>」
line = "「も、もっと深いところ、してっ<emoji=heart04>　お尻掴んで、ぐい、ぐいぐいって、奥、してぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 汗ばんだヴィーナスのお尻をぎゅうっと掴みながら、彼女の好きなところをペニスで集中的に突き込む。
line = "汗ばんだヴィーナスのお尻をぎゅうっと掴みながら、彼女の好きなところをペニスで集中的に突き込む。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ひぁあああっ！？<emoji=heart04>　あ、ぁーっ<emoji=heart04>　あーっ！<emoji=heart04>　あぁーっ<emoji=heart04>　そこ好きっ、おち○ちん気持ちぃ、いぃっ<emoji=heart04>　んんぁ、あ、ぁあ、ぁああっ<emoji=heart04>」
line = "「ひぁあああっ！？<emoji=heart04>　あ、ぁーっ<emoji=heart04>　あーっ！<emoji=heart04>　あぁーっ<emoji=heart04>　そこ好きっ、おち○ちん気持ちぃ、いぃっ<emoji=heart04>　んんぁ、あ、ぁあ、ぁああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「も、もっとお尻、ぎゅうってして<emoji=heart04>　指の痕、ついちゃうくらい、ぎゅうっって──ぁ、ぁ、あぁ、あぁああっ<emoji=heart04>」
line = "「も、もっとお尻、ぎゅうってして<emoji=heart04>　指の痕、ついちゃうくらい、ぎゅうっって──ぁ、ぁ、あぁ、あぁああっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 普段なら躊躇していたと思う。ヴィーナスと交わる時は、優しく抱きしめたり、頭を撫でたりしてゆっくり愛し合うことが多かった。
line = "普段なら躊躇していたと思う。ヴィーナスと交わる時は、優しく抱きしめたり、頭を撫でたりしてゆっくり愛し合うことが多かった。"

[[dialogue]]
speaker = "unk"
# 大切な恋人だから、丁重に油断せず、間違っても傷つけないように。そう思っていた──だけど、今は無理だった。
line = "大切な恋人だから、丁重に油断せず、間違っても傷つけないように。そう思っていた──だけど、今は無理だった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ひゃわぁぁああっ<emoji=heart04>　あ、あぁあっ<emoji=heart04>　お尻っ<emoji=heart04>　お尻ぎゅーって<emoji=heart04>　そ、それぇっ<emoji=heart04>　気持ちぃ、ぃいっ<emoji=heart04>　あぁんっ、好き、それ好きぃいいっ<emoji=heart04>」
line = "「ひゃわぁぁああっ<emoji=heart04>　あ、あぁあっ<emoji=heart04>　お尻っ<emoji=heart04>　お尻ぎゅーって<emoji=heart04>　そ、それぇっ<emoji=heart04>　気持ちぃ、ぃいっ<emoji=heart04>　あぁんっ、好き、それ好きぃいいっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 部屋中に漂うお香の香りのせいでブレーキが利かない。もっちり指に吸い付くお尻に痕がつくくらい、指に力を込めてしまう。
line = "部屋中に漂うお香の香りのせいでブレーキが利かない。もっちり指に吸い付くお尻に痕がつくくらい、指に力を込めてしまう。"

[[dialogue]]
speaker = "ヴィーナス"
# 「いつもより太いっ……おち○ちん、太いのぉっ……ふああぁあ、あっ<emoji=heart04>」
line = "「いつもより太いっ……おち○ちん、太いのぉっ……ふああぁあ、あっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナスのも、いつもより……狭いっ……！」
line = "「ヴィーナスのも、いつもより……狭いっ……！」"

[[dialogue]]
speaker = "unk"
# ピストンで引き抜こうとするたび、名残惜しそうにちゅうちゅう吸い付いてくる膣穴。
line = "ピストンで引き抜こうとするたび、名残惜しそうにちゅうちゅう吸い付いてくる膣穴。"

[[dialogue]]
speaker = "unk"
# ペニスを押し込む時だって、俺が腰を振っているのか、彼女の女性器に引っ張られているのか──よくわからないくらいだ。
line = "ペニスを押し込む時だって、俺が腰を振っているのか、彼女の女性器に引っ張られているのか──よくわからないくらいだ。"

[[dialogue]]
speaker = "ヴィーナス"
# 「んんぅっ<emoji=heart04>　あ、ぁぁあんっ<emoji=heart04>　んんぅっ<emoji=heart04>　ふぁあ、あぁあっ<emoji=heart04>　あぁっ、あっあっあっ<emoji=heart04>　ずぷずぷ、それもっと、もっとぉ<emoji=heart04>」
line = "「んんぅっ<emoji=heart04>　あ、ぁぁあんっ<emoji=heart04>　んんぅっ<emoji=heart04>　ふぁあ、あぁあっ<emoji=heart04>　あぁっ、あっあっあっ<emoji=heart04>　ずぷずぷ、それもっと、もっとぉ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んっふぅ、うぅっ<emoji=heart04>　あぁ、ぁあ～っ<emoji=heart04>　あっあっ、ぁぁあ～っ！<emoji=heart04>　はぁ、ふぅっ……喉、か、渇いちゃう、ぅうっ……<emoji=heart04>」
line = "「んっふぅ、うぅっ<emoji=heart04>　あぁ、ぁあ～っ<emoji=heart04>　あっあっ、ぁぁあ～っ！<emoji=heart04>　はぁ、ふぅっ……喉、か、渇いちゃう、ぅうっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ２人とも汗みどろになっているけれど、荒い呼吸が止まらず口の中はカラカラだ。どちらからともなく、唇を寄せ合った。
line = "２人とも汗みどろになっているけれど、荒い呼吸が止まらず口の中はカラカラだ。どちらからともなく、唇を寄せ合った。"

[[dialogue]]
speaker = "ヴィーナス"
# 「んんぅちゅるぅっ<emoji=heart04>　れぇええ～っ<emoji=heart04>　ちゅぅ、んちゅるぅ、ちゅぱ、れぇろぉ、んちゅるぅ、れちゅるうぅ<emoji=heart04>」
line = "「んんぅちゅるぅっ<emoji=heart04>　れぇええ～っ<emoji=heart04>　ちゅぅ、んちゅるぅ、ちゅぱ、れぇろぉ、んちゅるぅ、れちゅるうぅ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ぷはあっ──<emoji=heart04>　はふぅ、んんぅっ……バックでも、ちゃんとチューしてくれるのっ……うれ、し、ぃっ……<emoji=heart04>」
line = "「ぷはあっ──<emoji=heart04>　はふぅ、んんぅっ……バックでも、ちゃんとチューしてくれるのっ……うれ、し、ぃっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは頭を撫でられるだけでなく、キスをするのも大好きだった。体勢的にちょっと苦しくても、キスの時間は必ず取らなければ拗ねてしまう。
line = "ヴィーナスは頭を撫でられるだけでなく、キスをするのも大好きだった。体勢的にちょっと苦しくても、キスの時間は必ず取らなければ拗ねてしまう。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ちゅぅうる、んれぇええ、ちゅぱっ、んちゅるぅ、れちゅれちゅ、んちゅうぅ、れぇ～っ<emoji=heart04>　ぷはぁ<emoji=heart04>」
line = "「ちゅぅうる、んれぇええ、ちゅぱっ、んちゅるぅ、れちゅれちゅ、んちゅうぅ、れぇ～っ<emoji=heart04>　ぷはぁ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「キスしながら、あなたのおち○ちんで突かれるの、し、幸せ、ぇっ……<emoji=heart04>」
line = "「キスしながら、あなたのおち○ちんで突かれるの、し、幸せ、ぇっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「俺もヴィーナスと繋がりながら、キスするの、幸せだ……っ」
line = "「俺もヴィーナスと繋がりながら、キスするの、幸せだ……っ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「嬉しいっ……ん、んんぅっ<emoji=heart04>　いっぱい、おま○こキュッキュッてするから、もっとぉっ……んちゅるぅう<emoji=heart04>」
line = "「嬉しいっ……ん、んんぅっ<emoji=heart04>　いっぱい、おま○こキュッキュッてするから、もっとぉっ……んちゅるぅう<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んぅじゅるるっ<emoji=heart04>　ぢゅるちゅぱっ<emoji=heart04>　れぇれろぉっ<emoji=heart04>　んぅちゅぱっ、ちゅぅぱっ、ちゅぱ、れりゅれりゅ、んちゅるぅう<emoji=heart04>」
line = "「んぅじゅるるっ<emoji=heart04>　ぢゅるちゅぱっ<emoji=heart04>　れぇれろぉっ<emoji=heart04>　んぅちゅぱっ、ちゅぅぱっ、ちゅぱ、れりゅれりゅ、んちゅるぅう<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ヴィーナスが目を細めてキスを受け入れてくれるのが嬉しい。夢中でストロークして、彼女のお尻を波打たせるのも楽しい。
line = "ヴィーナスが目を細めてキスを受け入れてくれるのが嬉しい。夢中でストロークして、彼女のお尻を波打たせるのも楽しい。"

[[dialogue]]
speaker = "ヴィーナス"
# 「もっと<emoji=heart04>　もっとキスっ……ベロ、吸ってっ<emoji=heart04>　吸わせてっ<emoji=heart04>　あなたのお口、好き、キス好き、あなたが好きぃ……んちゅるぅ<emoji=heart04>」
line = "「もっと<emoji=heart04>　もっとキスっ……ベロ、吸ってっ<emoji=heart04>　吸わせてっ<emoji=heart04>　あなたのお口、好き、キス好き、あなたが好きぃ……んちゅるぅ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 舌を絡めるたびに膣穴の締まりが良くなる。よだれを注ぐと、本当に嬉しそうに喉を鳴らしてこくこく飲んでくれる。甘えん坊のひな鳥みたいだ。
line = "舌を絡めるたびに膣穴の締まりが良くなる。よだれを注ぐと、本当に嬉しそうに喉を鳴らしてこくこく飲んでくれる。甘えん坊のひな鳥みたいだ。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ぷっはぁっ<emoji=heart04>　はーっ<emoji=heart04>　はぁ～っ<emoji=heart04>　えへぇっ……よだれ、つぅ～って繋がって……え、えっちぃ……<emoji=heart04>」
line = "「ぷっはぁっ<emoji=heart04>　はーっ<emoji=heart04>　はぁ～っ<emoji=heart04>　えへぇっ……よだれ、つぅ～って繋がって……え、えっちぃ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「今日のあなた、乱暴にぱんぱんって、してくれてるけどっ……も、もっと激しく、して？<emoji=heart04>　大好きなあなたに、もっともっと、乱暴にされたいのっ<emoji=heart04>」
line = "「今日のあなた、乱暴にぱんぱんって、してくれてるけどっ……も、もっと激しく、して？<emoji=heart04>　大好きなあなたに、もっともっと、乱暴にされたいのっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「で、でも……その、本当にまずいんだ、今。このお香……む、ムラムラ、凄くて……」
line = "「で、でも……その、本当にまずいんだ、今。このお香……む、ムラムラ、凄くて……」"

[[dialogue]]
speaker = "unk"
# ヘレナさんのイタズラに乗っかって、ヴィーナスをこれ以上乱暴に犯すのは……
line = "ヘレナさんのイタズラに乗っかって、ヴィーナスをこれ以上乱暴に犯すのは……"

[[dialogue]]
speaker = "ヴィーナス"
# 「いいのっ……こ、このお香、私がヘレナちゃんに頼んで、あぁん<emoji=heart04>　置いてもらったやつ、だからあっ……<emoji=heart04>」
line = "「いいのっ……こ、このお香、私がヘレナちゃんに頼んで、あぁん<emoji=heart04>　置いてもらったやつ、だからあっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「………………へ？」
line = "「………………へ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あぁぁっ<emoji=heart04>　い、言っちゃったぁ……<emoji=heart04>　え、えへへぇっ……あなた、いっつも優しいえっち、ばっかりしてくれる、からぁ……<emoji=heart04>」
line = "「あぁぁっ<emoji=heart04>　い、言っちゃったぁ……<emoji=heart04>　え、えへへぇっ……あなた、いっつも優しいえっち、ばっかりしてくれる、からぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「はぁぁんっ<emoji=heart04>　た、たまには乱暴に犯してもらいたいんだけど……はふぅ<emoji=heart04>　どうしたらいいかって聞いたら、ヘレナちゃんがね～っ……<emoji=heart04>」
line = "「はぁぁんっ<emoji=heart04>　た、たまには乱暴に犯してもらいたいんだけど……はふぅ<emoji=heart04>　どうしたらいいかって聞いたら、ヘレナちゃんがね～っ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 発情するお香を準備してくれた、というわけらしい。
line = "発情するお香を準備してくれた、というわけらしい。"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナスは俺に……乱暴に犯して欲しかったから、こんなものまで用意したのか」
line = "「ヴィーナスは俺に……乱暴に犯して欲しかったから、こんなものまで用意したのか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「う、うんっ……<emoji=heart04>　そうなのっ、頭撫でられるのも、優しいキスも、好きだけどぉ……<emoji=heart04>」
line = "「う、うんっ……<emoji=heart04>　そうなのっ、頭撫でられるのも、優しいキスも、好きだけどぉ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「はぁぁぁっ<emoji=heart04>　大好きなあなたに、乱暴に求められたかったの……<emoji=heart04>　き、嫌いに、なった？」
line = "「はぁぁぁっ<emoji=heart04>　大好きなあなたに、乱暴に求められたかったの……<emoji=heart04>　き、嫌いに、なった？」"

[[dialogue]]
speaker = "unk"
# 布団を２組敷いたのも、性欲が昂るお香を置いたのも……全てはヴィーナスが望んだこと。
line = "布団を２組敷いたのも、性欲が昂るお香を置いたのも……全てはヴィーナスが望んだこと。"

[[dialogue]]
speaker = "unk"
# そんな事実を知らされて──我慢できる彼氏がいるわけがない。
line = "そんな事実を知らされて──我慢できる彼氏がいるわけがない。"

[[dialogue]]
speaker = "クロト"
# 「──もう出すまで止まらないからな」
line = "「──もう出すまで止まらないからな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「うんっ<emoji=heart04>　──ふぁぁ、あぁあぁああっ！？<emoji=heart04>　す、すごっ、すごい強い、ぱんぱん、来たぁっ……！<emoji=heart04>」
line = "「うんっ<emoji=heart04>　──ふぁぁ、あぁあぁああっ！？<emoji=heart04>　す、すごっ、すごい強い、ぱんぱん、来たぁっ……！<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あ、あぁーっ<emoji=heart04>　あっあっあっあっあっ<emoji=heart04>　奥、そんなところ知らないっ──ひぁあ、ぁ！<emoji=heart04>　あ、あーっ<emoji=heart04>　あーーーっ！<emoji=heart04>」
line = "「あ、あぁーっ<emoji=heart04>　あっあっあっあっあっ<emoji=heart04>　奥、そんなところ知らないっ──ひぁあ、ぁ！<emoji=heart04>　あ、あーっ<emoji=heart04>　あーーーっ！<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そこいぃいっ<emoji=heart04>　気持ちよすぎて、ひぁあっ<emoji=heart04>　あぁあ、ぁあぁ～っ！<emoji=heart04>」
line = "「そこいぃいっ<emoji=heart04>　気持ちよすぎて、ひぁあっ<emoji=heart04>　あぁあ、ぁあぁ～っ！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 思いきり犯して欲しいと言ったのに、ヴィーナスのお尻が俺から逃げようとする。
line = "思いきり犯して欲しいと言ったのに、ヴィーナスのお尻が俺から逃げようとする。"

[[dialogue]]
speaker = "unk"
# 強すぎる快感に、意思とは無関係に体が動いているのかも──俺はしっかりと彼女のお尻を掴み直して、手加減一切なしのピストンをお見舞いしていく。
line = "強すぎる快感に、意思とは無関係に体が動いているのかも──俺はしっかりと彼女のお尻を掴み直して、手加減一切なしのピストンをお見舞いしていく。"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナスのお尻、めちゃくちゃエロいっ。ヴィーナスの全部、俺のものにしていいんだなっ！」
line = "「ヴィーナスのお尻、めちゃくちゃエロいっ。ヴィーナスの全部、俺のものにしていいんだなっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「う、うんっ<emoji=heart04>　うんっ<emoji=heart04>　私のこと、あなたのものにしてぇっ<emoji=heart04>　──ぁ、ぁぁあぁ！？<emoji=heart04>　うぁ、ぁああっ<emoji=heart04>　奥だめぇ、ぅあっ<emoji=heart04>　あーっ！<emoji=heart04>」
line = "「う、うんっ<emoji=heart04>　うんっ<emoji=heart04>　私のこと、あなたのものにしてぇっ<emoji=heart04>　──ぁ、ぁぁあぁ！？<emoji=heart04>　うぁ、ぁああっ<emoji=heart04>　奥だめぇ、ぅあっ<emoji=heart04>　あーっ！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ポルチオ周りをぐりぐりと突くと、長い髪を振り乱して喘ぐヴィーナス。
line = "ポルチオ周りをぐりぐりと突くと、長い髪を振り乱して喘ぐヴィーナス。"

[[dialogue]]
speaker = "unk"
# 汗だくのほっぺに髪の毛が貼りついて、普段の元気溌溂な印象と大違いの──いやらしい、とろけ顔。
line = "汗だくのほっぺに髪の毛が貼りついて、普段の元気溌溂な印象と大違いの──いやらしい、とろけ顔。"

[[dialogue]]
speaker = "クロト"
# 「乱暴に犯されるの、実際にやられて、どうだっ？」
line = "「乱暴に犯されるの、実際にやられて、どうだっ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「しゅ、しゅきぃっ<emoji=heart04>　はぁぁぁん<emoji=heart04>　だいしゅきぃっ<emoji=heart04>　あぁん<emoji=heart04>　優しいあなたの、乱暴なえっちっ……あ、あ、あぁぁああ～<emoji=heart04>　しゅきぃい～っ<emoji=heart04>」
line = "「しゅ、しゅきぃっ<emoji=heart04>　はぁぁぁん<emoji=heart04>　だいしゅきぃっ<emoji=heart04>　あぁん<emoji=heart04>　優しいあなたの、乱暴なえっちっ……あ、あ、あぁぁああ～<emoji=heart04>　しゅきぃい～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 全身からくたりと力が抜けているのに、お尻だけは俺がピストンしやすいように高く掲げるヴィーナス。
line = "全身からくたりと力が抜けているのに、お尻だけは俺がピストンしやすいように高く掲げるヴィーナス。"

[[dialogue]]
speaker = "unk"
# あまりにいじらしくて、ヴィーナスのむき出しの首筋に全力で吸い付いていた。
line = "あまりにいじらしくて、ヴィーナスのむき出しの首筋に全力で吸い付いていた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「んんぁあっ！？<emoji=heart04>　あっ<emoji=heart04>　んやぁあ、だめぇえ<emoji=heart04>　くびすじっ<emoji=heart04>　キスマーク残る、残っちゃうぅっ<emoji=heart04>」
line = "「んんぁあっ！？<emoji=heart04>　あっ<emoji=heart04>　んやぁあ、だめぇえ<emoji=heart04>　くびすじっ<emoji=heart04>　キスマーク残る、残っちゃうぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「痕、残してほしかったんだろ？」
line = "「痕、残してほしかったんだろ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「で、でもぉっ、恥ずかしっ<emoji=heart04>　明日、お家のみんなに見られ、ちゃう、ぅ──あぁぁぁん<emoji=heart04>　はぁぁっ、だめ、だめ、だめぇええっ<emoji=heart04>」
line = "「で、でもぉっ、恥ずかしっ<emoji=heart04>　明日、お家のみんなに見られ、ちゃう、ぅ──あぁぁぁん<emoji=heart04>　はぁぁっ、だめ、だめ、だめぇええっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「駄目じゃないだろ。もっとして、だろ？　ほら──」
line = "「駄目じゃないだろ。もっとして、だろ？　ほら──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「～～～～～っ<emoji=heart04>　も、もっとしてぇっ<emoji=heart04>　いっぱいキスマーク、付けてほしいのぉっ！<emoji=heart04>　あぁぁぁん<emoji=heart04>　好きぃっ<emoji=heart04>　うぁっ<emoji=heart04>　ぁ、あ、あぁ、あ、あぁっ<emoji=heart04>」
line = "「～～～～～っ<emoji=heart04>　も、もっとしてぇっ<emoji=heart04>　いっぱいキスマーク、付けてほしいのぉっ！<emoji=heart04>　あぁぁぁん<emoji=heart04>　好きぃっ<emoji=heart04>　うぁっ<emoji=heart04>　ぁ、あ、あぁ、あ、あぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# キスマークを付けるたびにヴィーナスの体が震え、ペニスへの締め付けも強まっていく。
line = "キスマークを付けるたびにヴィーナスの体が震え、ペニスへの締め付けも強まっていく。"

[[dialogue]]
speaker = "unk"
# 名残惜しいけれど……もう、俺も限界だ。
line = "名残惜しいけれど……もう、俺も限界だ。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ぁ、ぁぁああっ！<emoji=heart04>　イく？　もう、イくのっ？<emoji=heart04>　いいよ、出してっ<emoji=heart04>　精液、いっぱい、出して、出して、出してっ<emoji=heart04>」
line = "「ぁ、ぁぁああっ！<emoji=heart04>　イく？　もう、イくのっ？<emoji=heart04>　いいよ、出してっ<emoji=heart04>　精液、いっぱい、出して、出して、出してっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「どこにっ？」
line = "「どこにっ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「中っ！<emoji=heart04>　中に出してぇっ<emoji=heart04>　あぁぁん<emoji=heart04>　好きだから<emoji=heart04>　中出し<emoji=heart04>　ふあぁぁん<emoji=heart04>　してっ<emoji=heart04>　してしてしてっ<emoji=heart04>　してぇええっ！<emoji=heart04>」
line = "「中っ！<emoji=heart04>　中に出してぇっ<emoji=heart04>　あぁぁん<emoji=heart04>　好きだから<emoji=heart04>　中出し<emoji=heart04>　ふあぁぁん<emoji=heart04>　してっ<emoji=heart04>　してしてしてっ<emoji=heart04>　してぇええっ！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 恋人のおねだりに応えて、根元までしっかりとペニスを差し込み──ヴィーナスの弱いところに亀頭を押し当てながら、放った。
line = "恋人のおねだりに応えて、根元までしっかりとペニスを差し込み──ヴィーナスの弱いところに亀頭を押し当てながら、放った。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あぁぁっ、あぁぁぁっ<emoji=heart04><emoji=heart04>　んんぁぁぁああぁあああぁあああぁあ～～～～～っ！<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あぁぁっ、あぁぁぁっ<emoji=heart04><emoji=heart04>　んんぁぁぁああぁあああぁあああぁあ～～～～～っ！<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ<emoji=heart04>　あっ<emoji=heart04>　あぁぁぁん<emoji=heart04>　ふあぁぁあっ、あ、ぁぁあ、ぁぁああ～っ……！<emoji=heart04>」
line = "「あっ<emoji=heart04>　あっ<emoji=heart04>　あぁぁぁん<emoji=heart04>　ふあぁぁあっ、あ、ぁぁあ、ぁぁああ～っ……！<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「す、すごぃっ……んぁ、ぁ、ああぁぁ～～っ……はぁあっ……うぁっ……あぁあ～っ……<emoji=heart04>」
line = "「す、すごぃっ……んぁ、ぁ、ああぁぁ～～っ……はぁあっ……うぁっ……あぁあ～っ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 最後の一滴まで、引き絞るように出して、出して、出し尽くして──ようやく射精が終わった。
line = "最後の一滴まで、引き絞るように出して、出して、出し尽くして──ようやく射精が終わった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「はぁああっ……ふぅううっ……す、すっごい、量……精液、おま○こから、どんどん、溢れてくる、ぅ……<emoji=heart04>」
line = "「はぁああっ……ふぅううっ……す、すっごい、量……精液、おま○こから、どんどん、溢れてくる、ぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「はぁぁ……乱暴なエッチ……気持ち、良かったあ……<emoji=heart04>　あなたに、求めてもらえるの、ふふっ<emoji=heart04>　幸せぇ<emoji=heart04>」
line = "「はぁぁ……乱暴なエッチ……気持ち、良かったあ……<emoji=heart04>　あなたに、求めてもらえるの、ふふっ<emoji=heart04>　幸せぇ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 射精が終わった後は、ゆったりピロートークをすることも多い、俺とヴィーナスだけど……
line = "射精が終わった後は、ゆったりピロートークをすることも多い、俺とヴィーナスだけど……"

[[dialogue]]
speaker = "クロト"
# 「もう一回、いいか……？」
line = "「もう一回、いいか……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「──うんっ<emoji=heart04>　私も……し、したいって、思ってた、から……<emoji=heart04>」
line = "「──うんっ<emoji=heart04>　私も……し、したいって、思ってた、から……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# お香のせいか。新年明けての激しい姫始めでテンションが上がっているのか──もうどっちでもいい。
line = "お香のせいか。新年明けての激しい姫始めでテンションが上がっているのか──もうどっちでもいい。"

[[dialogue]]
speaker = "unk"
# 九浄家の敷地は膨大で、ここは人の寄り付かない離れ。
line = "九浄家の敷地は膨大で、ここは人の寄り付かない離れ。"

[[dialogue]]
speaker = "unk"
# ヴィーナスを思いきり喘がせても聞こえることはないだろう。遠慮はいらない。
line = "ヴィーナスを思いきり喘がせても聞こえることはないだろう。遠慮はいらない。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あなたが満足するまで……いっぱい愛して？<emoji=heart04>」
line = "「あなたが満足するまで……いっぱい愛して？<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# とろけた眼差しのヴィーナスに誘われて、２回戦、３回戦──俺たちは汗だくになりながら夜通し、夢中で交わるのだった──
line = "とろけた眼差しのヴィーナスに誘われて、２回戦、３回戦──俺たちは汗だくになりながら夜通し、夢中で交わるのだった──"
