[[dialogue]]
speaker = "unk"
# 第２話,会長のお買い物,P
line = "第２話,会長のお買い物,P"

[[dialogue]]
speaker = "フィオナ"
# 「はぁはぁ……ふぅ、思ったより遅くなっちゃった。まだ残ってるかな……ちゃんと買えるといいけど」
line = "「はぁはぁ……ふぅ、思ったより遅くなっちゃった。まだ残ってるかな……ちゃんと買えるといいけど」"

[[dialogue]]
speaker = "フィオナ"
# 「あら、こんなところで奇遇ですね。緋宮会長もお買い物ですか？」
line = "「あら、こんなところで奇遇ですね。緋宮会長もお買い物ですか？」"

[[dialogue]]
speaker = "フィオナ"
# 「そんな意外そうな顔をしないでください。星徒会長で教皇の娘といっても、私とて学生ですから、放課後に立ち寄ることくらいあります」
line = "「そんな意外そうな顔をしないでください。星徒会長で教皇の娘といっても、私とて学生ですから、放課後に立ち寄ることくらいあります」"

[[dialogue]]
speaker = "フィオナ"
# 「一般生徒に比べれば、多少頻度は低いかもしれませんが。緋宮会長は何を買いに──」
line = "「一般生徒に比べれば、多少頻度は低いかもしれませんが。緋宮会長は何を買いに──」"

[[dialogue]]
speaker = "フィオナ"
# 「！　モンスター！　ここから近そうですね。力を貸していただけますか？」
line = "「！　モンスター！　ここから近そうですね。力を貸していただけますか？」"

[[dialogue]]
speaker = "unk"
# もちろん！
line = "もちろん！"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長ならそう言うと思っていました」
line = "「緋宮会長ならそう言うと思っていました」"

[[dialogue]]
speaker = "フィオナ"
# 「行きましょう！」
line = "「行きましょう！」"

[[dialogue]]
speaker = "フィオナ"
# 「迅速な対応、さすがでした。緋宮会長も星騎士として様になってきていると思います」
line = "「迅速な対応、さすがでした。緋宮会長も星騎士として様になってきていると思います」"

[[dialogue]]
speaker = "フィオナ"
# 「もちろんお世辞ではないですよ。さっきの緋宮会長、かっこよかったです。……あ、顔がにやけてますよ」
line = "「もちろんお世辞ではないですよ。さっきの緋宮会長、かっこよかったです。……あ、顔がにやけてますよ」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふふっ、冗談です。大丈夫です、だらしない顔なんてしていませんから。ちゃんとキリッとしたお顔ですよ」
line = "「ふふふっ、冗談です。大丈夫です、だらしない顔なんてしていませんから。ちゃんとキリッとしたお顔ですよ」"

[[dialogue]]
speaker = "フィオナ"
# 「では私はこれで──」
line = "「では私はこれで──」"

[[dialogue]]
speaker = "フィオナ"
# 「あっ！？」
line = "「あっ！？」"

[[dialogue]]
speaker = "フィオナ"
# 「モンスターのせいで、買い物のことを失念していました。今からだときっと間に合わない……」
line = "「モンスターのせいで、買い物のことを失念していました。今からだときっと間に合わない……」"

[[dialogue]]
speaker = "フィオナ"
# 「キリカにお願いすれば……ううん、趣味の買い物を任せるのも悪いし……キリカは、そのためのメイドだと言ってくれているけど」
line = "「キリカにお願いすれば……ううん、趣味の買い物を任せるのも悪いし……キリカは、そのためのメイドだと言ってくれているけど」"

[[dialogue]]
speaker = "フィオナ"
# 「それに自分で手に取りたかったし……人にお願いするのは恥ずかしいものだし」
line = "「それに自分で手に取りたかったし……人にお願いするのは恥ずかしいものだし」"

[[dialogue]]
speaker = "フィオナ"
# 「あっ、いえ……恥ずかしいと言っても、ハレンチなものではないんですけど……」
line = "「あっ、いえ……恥ずかしいと言っても、ハレンチなものではないんですけど……」"

[[dialogue]]
speaker = "フィオナ"
# 「ええと、実は私、主に少年向けの……特にヒーローものと言われるジャンルの漫画を嗜んでいまして」
line = "「ええと、実は私、主に少年向けの……特にヒーローものと言われるジャンルの漫画を嗜んでいまして」"

[[dialogue]]
speaker = "フィオナ"
# 「今日は最新刊の発売日だったんです。ヒーローを目指す少年が主人公の、今全世界で大人気の作品なんですが」
line = "「今日は最新刊の発売日だったんです。ヒーローを目指す少年が主人公の、今全世界で大人気の作品なんですが」"

[[dialogue]]
speaker = "フィオナ"
# 「ヒーローらしくなくておどろおどろしい雰囲気があるんですけど、でもテーマは真っ直ぐで普遍的で、とても心を打つんです」
line = "「ヒーローらしくなくておどろおどろしい雰囲気があるんですけど、でもテーマは真っ直ぐで普遍的で、とても心を打つんです」"

[[dialogue]]
speaker = "フィオナ"
# 「登場人物はそれぞれ重い境遇なんですけど、決して屈することなく、前を向いて命を懸けて……」
line = "「登場人物はそれぞれ重い境遇なんですけど、決して屈することなく、前を向いて命を懸けて……」"

[[dialogue]]
speaker = "フィオナ"
# 「あっ！　熱くなって語りすぎてしまいました。すみません……」
line = "「あっ！　熱くなって語りすぎてしまいました。すみません……」"

[[dialogue]]
speaker = "フィオナ"
# 「歴史ある流星学園の星徒会長としてはお恥ずかしい話ですし、男の子でもないのに、少年漫画を読むのは変かもしれませんが……」
line = "「歴史ある流星学園の星徒会長としてはお恥ずかしい話ですし、男の子でもないのに、少年漫画を読むのは変かもしれませんが……」"

[[dialogue]]
speaker = "unk"
# 変でも恥ずかしくもないよ
line = "変でも恥ずかしくもないよ"

[[dialogue]]
speaker = "フィオナ"
# 「……そう言っていただけるとありがたいです」
line = "「……そう言っていただけるとありがたいです」"

[[dialogue]]
speaker = "フィオナ"
# 「ちなみに私、漫画は紙で読む派なんです。戦闘で魔導書を使うからでしょうか」
line = "「ちなみに私、漫画は紙で読む派なんです。戦闘で魔導書を使うからでしょうか」"

[[dialogue]]
speaker = "フィオナ"
# 「コミックの厚さ、ざらついた紙の手ざわり、めくれる時の小さな音……それらも含めて漫画だと思うんです」
line = "「コミックの厚さ、ざらついた紙の手ざわり、めくれる時の小さな音……それらも含めて漫画だと思うんです」"

[[dialogue]]
speaker = "フィオナ"
# 「だから自分でお店で手に取りたくて……結果、まだ買えていないのですが」
line = "「だから自分でお店で手に取りたくて……結果、まだ買えていないのですが」"

[[dialogue]]
speaker = "フィオナ"
# 「私は連載で読んでいないから今日を楽しみにしていたのに、売り切れているかもしれません。ああ、こんなことなら予約しておけば良かった……」
line = "「私は連載で読んでいないから今日を楽しみにしていたのに、売り切れているかもしれません。ああ、こんなことなら予約しておけば良かった……」"

[[dialogue]]
speaker = "フィオナ"
# 「気が付いたら発売日だったんですよね……最近こんなことばかりで、しっかりしないといけませんね」
line = "「気が付いたら発売日だったんですよね……最近こんなことばかりで、しっかりしないといけませんね」"

[[dialogue]]
speaker = "unk"
# 実は俺も同じのを買いに来た
line = "実は俺も同じのを買いに来た"

[[dialogue]]
speaker = "フィオナ"
# 「！　そうだったんですか。ますます奇遇ですね」
line = "「！　そうだったんですか。ますます奇遇ですね」"

[[dialogue]]
speaker = "フィオナ"
# 「もしかしたらまだ書店に残っているかもしれません。急ぎましょうっ」
line = "「もしかしたらまだ書店に残っているかもしれません。急ぎましょうっ」"

[[dialogue]]
speaker = "フィオナ"
# 「の、残り１冊……買えるのは私か緋宮会長どちらかだけ……まさかこんなことになるとは……」
line = "「の、残り１冊……買えるのは私か緋宮会長どちらかだけ……まさかこんなことになるとは……」"

[[dialogue]]
speaker = "フィオナ"
# 「どうぞ、緋宮会長。私は増版された時に購入しますので……」
line = "「どうぞ、緋宮会長。私は増版された時に購入しますので……」"

[[dialogue]]
speaker = "フィオナ"
# 「え？　最後の１冊を私に……？　いけません、それでは緋宮会長が読めないじゃないですか」
line = "「え？　最後の１冊を私に……？　いけません、それでは緋宮会長が読めないじゃないですか」"

[[dialogue]]
speaker = "unk"
# フィオナはすごく楽しみにしてたから
line = "フィオナはすごく楽しみにしてたから"

[[dialogue]]
speaker = "フィオナ"
# 「……そこまで言うなら、買わせていただきます。本当にありがとうございます」
line = "「……そこまで言うなら、買わせていただきます。本当にありがとうございます」"

[[dialogue]]
speaker = "フィオナ"
# 「ところで緋宮会長はどのキャラクターがお好きですか？　良ければお聞きしたいです」
line = "「ところで緋宮会長はどのキャラクターがお好きですか？　良ければお聞きしたいです」"

[[dialogue]]
speaker = "フィオナ"
# 「私は主人公の幼馴染の女の子が好きで……妹を守ろうとしてヒーローを志して、でも本当は戦いは好きじゃなくて……共感してしまいます」
line = "「私は主人公の幼馴染の女の子が好きで……妹を守ろうとしてヒーローを志して、でも本当は戦いは好きじゃなくて……共感してしまいます」"

[[dialogue]]
speaker = "フィオナ"
# 「でもやっぱり……みんな好きです。戦える人も、戦えない人も、大切なものを失っても立ち上がって、すごくかっこいいです」
line = "「でもやっぱり……みんな好きです。戦える人も、戦えない人も、大切なものを失っても立ち上がって、すごくかっこいいです」"

[[dialogue]]
speaker = "フィオナ"
# 「……？　神妙な顔をされて、どうしたんですか？」
line = "「……？　神妙な顔をされて、どうしたんですか？」"

[[dialogue]]
speaker = "unk"
# でも俺たちなら大切なものを守れる
line = "でも俺たちなら大切なものを守れる"

[[dialogue]]
speaker = "フィオナ"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "フィオナ"
# 「……そうです、その通りです。失いながらも立ち上がるのは、確かに素晴らしいことです」
line = "「……そうです、その通りです。失いながらも立ち上がるのは、確かに素晴らしいことです」"

[[dialogue]]
speaker = "フィオナ"
# 「でも私たちは、星騎士は、誰かが大切なものを失う前に守ることができる」
line = "「でも私たちは、星騎士は、誰かが大切なものを失う前に守ることができる」"

[[dialogue]]
speaker = "フィオナ"
# 「会長として先輩なのに１つ教わった気分です。さすが緋宮会長です」
line = "「会長として先輩なのに１つ教わった気分です。さすが緋宮会長です」"

[[dialogue]]
speaker = "フィオナ"
# 「……ふふっ、そんなに照れなくてもいいじゃないですか。私は本当にそう思ったんですから」
line = "「……ふふっ、そんなに照れなくてもいいじゃないですか。私は本当にそう思ったんですから」"

[[dialogue]]
speaker = "フィオナ"
# 「あ、すみません。思ったより遅くなったのでそろそろ帰らないと。今度、この作品について語り合いましょう」
line = "「あ、すみません。思ったより遅くなったのでそろそろ帰らないと。今度、この作品について語り合いましょう」"

[[dialogue]]
speaker = "フィオナ"
# 「その時が楽しみです。それではっ」
line = "「その時が楽しみです。それではっ」"
