[[dialogue]]
speaker = "unk"
# 事の始まりは、ソフィとのお正月デートを済ませた帰り道で起こった。
line = "事の始まりは、ソフィとのお正月デートを済ませた帰り道で起こった。"

[[dialogue]]
speaker = "unk"
# アステラの出現──新年が始まったばかりだというのにモンスターの活動は空気を読まないったらない。
line = "アステラの出現──新年が始まったばかりだというのにモンスターの活動は空気を読まないったらない。"

[[dialogue]]
speaker = "unk"
# 現場近くにいた俺とソフィ、そしてサーシャさんが駆けつけて無事にモンスターを駆逐。
line = "現場近くにいた俺とソフィ、そしてサーシャさんが駆けつけて無事にモンスターを駆逐。"

[[dialogue]]
speaker = "unk"
# さぁ帰るぞ──という段階で、俺はつまずいて。
line = "さぁ帰るぞ──という段階で、俺はつまずいて。"

[[dialogue]]
speaker = "unk"
# サーシャさんの大きなお胸へダイブ。
line = "サーシャさんの大きなお胸へダイブ。"

[[dialogue]]
speaker = "unk"
# それを見たソフィはぷんすかと怒ってしまい……
line = "それを見たソフィはぷんすかと怒ってしまい……"

[[dialogue]]
speaker = "ソフィア"
# 「むっすぅ～……」
line = "「むっすぅ～……」"

[[dialogue]]
speaker = "unk"
# ──今ここ、というわけだ。
line = "──今ここ、というわけだ。"

[[dialogue]]
speaker = "unk"
# 晴れ着をベッドの上ではだけて、綺麗なおっぱいを露出してくれているソフィ。けれどもそのほっぺたは、誰が見ても分かるくらいにむくれていた。
line = "晴れ着をベッドの上ではだけて、綺麗なおっぱいを露出してくれているソフィ。けれどもそのほっぺたは、誰が見ても分かるくらいにむくれていた。"

[[dialogue]]
speaker = "ソフィア"
# 「私みたいなちっちゃな体では、会長さんは満足できないかもしれませんが。それでもいいのでしたら、どうぞっ？」
line = "「私みたいなちっちゃな体では、会長さんは満足できないかもしれませんが。それでもいいのでしたら、どうぞっ？」"

[[dialogue]]
speaker = "unk"
# ソフィは自分のスタイルのことを気にしており、男性にとって面白くない体だと思い込んでいる節がある。
line = "ソフィは自分のスタイルのことを気にしており、男性にとって面白くない体だと思い込んでいる節がある。"

[[dialogue]]
speaker = "unk"
# そんな彼女が、別の大きなおっぱいの女性（しかも姉）に顔を埋めている彼氏を見てしまったら──不機嫌になってしまうのは無理はない。
line = "そんな彼女が、別の大きなおっぱいの女性（しかも姉）に顔を埋めている彼氏を見てしまったら──不機嫌になってしまうのは無理はない。"

[[dialogue]]
speaker = "クロト"
# 「……俺はソフィ一筋だぞ？」
line = "「……俺はソフィ一筋だぞ？」"

[[dialogue]]
speaker = "ソフィア"
# 「そうですか。私も会長さん一筋ですよ。つーん」
line = "「そうですか。私も会長さん一筋ですよ。つーん」"

[[dialogue]]
speaker = "ソフィア"
# 「会長さん。姉さんのおっぱいに飛び込んだ時、すっっっごくだらしない顔、してました。つーん、ってなってもしょうがないです」
line = "「会長さん。姉さんのおっぱいに飛び込んだ時、すっっっごくだらしない顔、してました。つーん、ってなってもしょうがないです」"

[[dialogue]]
speaker = "クロト"
# 「そんな顔してないって……俺がエッチしたいって思うのはソフィだけだよ。魅力的だって思ってなかったらこんな風にはならないだろ？」
line = "「そんな顔してないって……俺がエッチしたいって思うのはソフィだけだよ。魅力的だって思ってなかったらこんな風にはならないだろ？」"

[[dialogue]]
speaker = "unk"
# 恋人との姫始めということで期待しているペニス──そこへ視線を向けたソフィは頬を赤く染めながらもそっぽを向く。
line = "恋人との姫始めということで期待しているペニス──そこへ視線を向けたソフィは頬を赤く染めながらもそっぽを向く。"

[[dialogue]]
speaker = "ソフィア"
# 「ね、姉さんのおっぱいを思い出して、おっきくなってるのかもしれません。つーんっ！」
line = "「ね、姉さんのおっぱいを思い出して、おっきくなってるのかもしれません。つーんっ！」"

[[dialogue]]
speaker = "unk"
# 困った……今回は相当にお冠みたいだ。
line = "困った……今回は相当にお冠みたいだ。"

[[dialogue]]
speaker = "unk"
# どうすれば機嫌を直してもらえるんだろう……
line = "どうすれば機嫌を直してもらえるんだろう……"

[[dialogue]]
speaker = "クロト"
# 「じゃあ、ソフィ。俺、一生懸命ソフィを求めるから、それで判断してもらえるか？」
line = "「じゃあ、ソフィ。俺、一生懸命ソフィを求めるから、それで判断してもらえるか？」"

[[dialogue]]
speaker = "ソフィア"
# 「──えっ？」
line = "「──えっ？」"

[[dialogue]]
speaker = "unk"
# 宣言と同時に、すでにしっとりと濡れていたソフィのあそこへペニスを挿入した──
line = "宣言と同時に、すでにしっとりと濡れていたソフィのあそこへペニスを挿入した──"

[[dialogue]]
speaker = "ソフィア"
# 「んんぅ、あぁあっ……！<emoji=heart04>　そんな、いきなり、ぃっ……ぁ、はぁ……！<emoji=heart04>」
line = "「んんぅ、あぁあっ……！<emoji=heart04>　そんな、いきなり、ぃっ……ぁ、はぁ……！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# いきなりの挿入には違いなかったけれど、ペニスは根元までぬるんと一息に入ってしまった。
line = "いきなりの挿入には違いなかったけれど、ペニスは根元までぬるんと一息に入ってしまった。"

[[dialogue]]
speaker = "unk"
# 今日まで、数えきれないくらいにエッチをしてきた証拠だった。
line = "今日まで、数えきれないくらいにエッチをしてきた証拠だった。"

[[dialogue]]
speaker = "ソフィア"
# 「か、会長さんの、んんぅっ……はぁっ……すっごく熱い……は、あ、ぁあっ……それに、いつもより、硬いかも……」
line = "「か、会長さんの、んんぅっ……はぁっ……すっごく熱い……は、あ、ぁあっ……それに、いつもより、硬いかも……」"

[[dialogue]]
speaker = "unk"
# たくさん感じて欲しい。俺がこんなにも興奮するのはソフィだけだ──それを証明するために動く。
line = "たくさん感じて欲しい。俺がこんなにも興奮するのはソフィだけだ──それを証明するために動く。"

[[dialogue]]
speaker = "ソフィア"
# 「ふぅうっ、あ、あ、ぁっ……<emoji=heart04>　んんぅっ……あ、ぅぁ、あ、ぁあっ<emoji=heart04>」
line = "「ふぅうっ、あ、あ、ぁっ……<emoji=heart04>　んんぅっ……あ、ぅぁ、あ、ぁあっ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「んん、ぅうっ……はあぁっ……んんっ……おへその裏、ぐりぐりって、いっぱい、こすれて──んんぅっ<emoji=heart04>」
line = "「んん、ぅうっ……はあぁっ……んんっ……おへその裏、ぐりぐりって、いっぱい、こすれて──んんぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 新年が明けてから、ソフィとの初めてのエッチ。年末年始と禁欲を続けていたこともあって、勃起の角度がすごいことになっている。
line = "新年が明けてから、ソフィとの初めてのエッチ。年末年始と禁欲を続けていたこともあって、勃起の角度がすごいことになっている。"

[[dialogue]]
speaker = "ソフィア"
# 「あ、ぁ、あっ<emoji=heart04>　そ、そんな、腰を掴んで、お尻持ち上げちゃ駄目ですっ……体、反りかえっちゃいま──んんぅう～～っ<emoji=heart04>」
line = "「あ、ぁ、あっ<emoji=heart04>　そ、そんな、腰を掴んで、お尻持ち上げちゃ駄目ですっ……体、反りかえっちゃいま──んんぅう～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「おち○ちんで、ぐいぐいって、ナナメに突き上げるの、だ──めぇ、あっ、んんぅっ<emoji=heart04>　おま○こ、感じちゃいまっ、あ、あっあっ！<emoji=heart04>」
line = "「おち○ちんで、ぐいぐいって、ナナメに突き上げるの、だ──めぇ、あっ、んんぅっ<emoji=heart04>　おま○こ、感じちゃいまっ、あ、あっあっ！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ソフィと交わる時は、手を繋いだり、両手を背中に回して抱きあったりすることが多い。
line = "ソフィと交わる時は、手を繋いだり、両手を背中に回して抱きあったりすることが多い。"

[[dialogue]]
speaker = "unk"
# 今日みたいに腰を持って、華奢な背中を反らせながら、ペニスで突きこむエッチは初めてだ。
line = "今日みたいに腰を持って、華奢な背中を反らせながら、ペニスで突きこむエッチは初めてだ。"

[[dialogue]]
speaker = "ソフィア"
# 「そんな、奥までぱんぱん、されたらっ……んああっ<emoji=heart04>　ふぅ、んんっ、や、あぁあっ……ぐいぐい、来るぅっ<emoji=heart04>」
line = "「そんな、奥までぱんぱん、されたらっ……んああっ<emoji=heart04>　ふぅ、んんっ、や、あぁあっ……ぐいぐい、来るぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 星騎士として鍛えているのに、華奢な体のソフィ。
line = "星騎士として鍛えているのに、華奢な体のソフィ。"

[[dialogue]]
speaker = "unk"
# ペニスをぐいっと上へ向けると、それだけでお尻がくくっと持ち上がるのがたまらなくいやらしい。
line = "ペニスをぐいっと上へ向けると、それだけでお尻がくくっと持ち上がるのがたまらなくいやらしい。"

[[dialogue]]
speaker = "ソフィア"
# 「あ、ぁ、ぁっ、あ～っ……！<emoji=heart04>　きょ、今日の会長さん、ふうぁ、あ、あっ……絶対にいつもより硬いです、んんぁ、なんでっ……！？<emoji=heart04>」
line = "「あ、ぁ、ぁっ、あ～っ……！<emoji=heart04>　きょ、今日の会長さん、ふうぁ、あ、あっ……絶対にいつもより硬いです、んんぁ、なんでっ……！？<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そんなの、大好きな恋人のソフィと繋がっているから以外にない──ピストンの合間にそう率直に伝える。
line = "そんなの、大好きな恋人のソフィと繋がっているから以外にない──ピストンの合間にそう率直に伝える。"

[[dialogue]]
speaker = "ソフィア"
# 「んんぁ、あ、あっ<emoji=heart04>　はぁ、ぁ、ぅっ<emoji=heart04>　ほ、本当、ですかっ？　私、んんぁっ、可愛いっ……ですかっ……？<emoji=heart04>　姉さん、より……？」
line = "「んんぁ、あ、あっ<emoji=heart04>　はぁ、ぁ、ぅっ<emoji=heart04>　ほ、本当、ですかっ？　私、んんぁっ、可愛いっ……ですかっ……？<emoji=heart04>　姉さん、より……？」"

[[dialogue]]
speaker = "クロト"
# 「当たり前だっ……！」
line = "「当たり前だっ……！」"

[[dialogue]]
speaker = "unk"
# ソフィの腰を引きよせて、ぱんぱんに膨らんだ亀頭で、おへその裏側をぐりぐりと擦り上げる。
line = "ソフィの腰を引きよせて、ぱんぱんに膨らんだ亀頭で、おへその裏側をぐりぐりと擦り上げる。"

[[dialogue]]
speaker = "ソフィア"
# 「ふぅ、んんんぅ～っ<emoji=heart04>　あっ──は、ぁ、あ、あぁあっ！<emoji=heart04>　んんぅっ、くっふぅ、ぅう～っ……！<emoji=heart04>」
line = "「ふぅ、んんんぅ～っ<emoji=heart04>　あっ──は、ぁ、あ、あぁあっ！<emoji=heart04>　んんぅっ、くっふぅ、ぅう～っ……！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ソフィが深く感じてくれたのか、俺の手のひらにビクビクビクっと振動が広がる。恋人の可愛い反応を受け止めながら、俺はどんどん言葉を伝えていく。
line = "ソフィが深く感じてくれたのか、俺の手のひらにビクビクビクっと振動が広がる。恋人の可愛い反応を受け止めながら、俺はどんどん言葉を伝えていく。"

[[dialogue]]
speaker = "クロト"
# 「普段からとびきり可愛いけど、今日は輪をかけて素敵だ」
line = "「普段からとびきり可愛いけど、今日は輪をかけて素敵だ」"

[[dialogue]]
speaker = "ソフィア"
# 「あ、あっあっあっ<emoji=heart04>　ダメっ<emoji=heart04>　嬉しいこと言いながら、ぱんぱん、ふああぁ、ああっ！<emoji=heart04>」
line = "「あ、あっあっあっ<emoji=heart04>　ダメっ<emoji=heart04>　嬉しいこと言いながら、ぱんぱん、ふああぁ、ああっ！<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「晴れ着もよく似合っている。髪飾りもおしゃれで、デートしている時からずっとドキドキしてた」
line = "「晴れ着もよく似合っている。髪飾りもおしゃれで、デートしている時からずっとドキドキしてた」"

[[dialogue]]
speaker = "ソフィア"
# 「んっ、ふぅ、んんっ<emoji=heart04>　あ、あっあっ<emoji=heart04>　おち○ちんで、そこ、ぐりぐり、ゃああぁ<emoji=heart04>　くぅ、気持ち、いぃい、ですぅっ……<emoji=heart04>」
line = "「んっ、ふぅ、んんっ<emoji=heart04>　あ、あっあっ<emoji=heart04>　おち○ちんで、そこ、ぐりぐり、ゃああぁ<emoji=heart04>　くぅ、気持ち、いぃい、ですぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「それに今日は、うっすら化粧もしてる？」
line = "「それに今日は、うっすら化粧もしてる？」"

[[dialogue]]
speaker = "ソフィア"
# 「ぁっ……ふぁあ、あ、あっ……はいっ……<emoji=heart04>　会長さんに、可愛いって、思ってもらいたくって──ひぁああぁっ<emoji=heart04>」
line = "「ぁっ……ふぁあ、あ、あっ……はいっ……<emoji=heart04>　会長さんに、可愛いって、思ってもらいたくって──ひぁああぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「んぁ、あ、あっ……ウズメにお化粧、やり方、聞いて──あぁぁあっ！<emoji=heart04>」
line = "「んぁ、あ、あっ……ウズメにお化粧、やり方、聞いて──あぁぁあっ！<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「んんぅ、ふぅ、うぅうっ<emoji=heart04>　す、すみませ、んっ……会長さん、さっき……んんっ、可愛くない態度、取っちゃって……！」
line = "「んんぅ、ふぅ、うぅうっ<emoji=heart04>　す、すみませ、んっ……会長さん、さっき……んんっ、可愛くない態度、取っちゃって……！」"

[[dialogue]]
speaker = "ソフィア"
# 「会長さんの周り、綺麗で、スタイルのいい女性、ばかりで……ね、姉さんと比べられたら、私、勝てるところないって、思ってて……！」
line = "「会長さんの周り、綺麗で、スタイルのいい女性、ばかりで……ね、姉さんと比べられたら、私、勝てるところないって、思ってて……！」"

[[dialogue]]
speaker = "unk"
# 気にしてない。ソフィにヤキモチを焼かれるのだって悪い気分じゃないんだ。──そう伝えながら唇を奪う。
line = "気にしてない。ソフィにヤキモチを焼かれるのだって悪い気分じゃないんだ。──そう伝えながら唇を奪う。"

[[dialogue]]
speaker = "ソフィア"
# 「ぁっ……会長さんっ……んんぅ<emoji=heart04>　はぷっ、んちゅぅ、れぇ、ちゅぅっ……<emoji=heart04>」
line = "「ぁっ……会長さんっ……んんぅ<emoji=heart04>　はぷっ、んちゅぅ、れぇ、ちゅぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「んぅちゅるっ、れぇえ、んちゅる、れえ、れろっ、んちゅう……<emoji=heart04>　ぷあっ……はぁ、ふぅっ、んんぅっ、あぁ、好き、好きです、んぅ<emoji=heart04>」
line = "「んぅちゅるっ、れぇえ、んちゅる、れえ、れろっ、んちゅう……<emoji=heart04>　ぷあっ……はぁ、ふぅっ、んんぅっ、あぁ、好き、好きです、んぅ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ソフィのヤキモチは嬉しい。だけど……もう少し俺のことも信じてもらいたい。こんなに好きなんだってこと。
line = "ソフィのヤキモチは嬉しい。だけど……もう少し俺のことも信じてもらいたい。こんなに好きなんだってこと。"

[[dialogue]]
speaker = "クロト"
# 「俺がソフィのこと、どれくらい好きなのか。今日はしっかり体で覚えてもらうからな」
line = "「俺がソフィのこと、どれくらい好きなのか。今日はしっかり体で覚えてもらうからな」"

[[dialogue]]
speaker = "ソフィア"
# 「……え？」
line = "「……え？」"

[[dialogue]]
speaker = "unk"
# ソフィの腰を逃がさないようにホールドして、彼女の弱いところ──女性器の最奥を強くピストンする。
line = "ソフィの腰を逃がさないようにホールドして、彼女の弱いところ──女性器の最奥を強くピストンする。"

[[dialogue]]
speaker = "ソフィア"
# 「ひっ──ぁっ──ぁぁあぁ～っ<emoji=heart04>　そ、そこぉっ、ら、らめぇ、らめれすっ……あ、ぁ、あ、あ、あぁ、あっ！<emoji=heart04>」
line = "「ひっ──ぁっ──ぁぁあぁ～っ<emoji=heart04>　そ、そこぉっ、ら、らめぇ、らめれすっ……あ、ぁ、あ、あ、あぁ、あっ！<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「ふううぁ、あ、あぁっ<emoji=heart04>　会長、さんっ、ぁ、あ、あっ<emoji=heart04>　おま○こ、奥のところ、トントン、だめ、ぇっ……あ、はぁ、あぁあっ<emoji=heart04>」
line = "「ふううぁ、あ、あぁっ<emoji=heart04>　会長、さんっ、ぁ、あ、あっ<emoji=heart04>　おま○こ、奥のところ、トントン、だめ、ぇっ……あ、はぁ、あぁあっ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「おち○ちん、んんぅ、ふぅう、あぁっ<emoji=heart04>　が、ガチガチ、すぎますっ、あ、ぁあ、ああっ<emoji=heart04>　熱い、熱い、んんぅ、ぅうっ！<emoji=heart04>」
line = "「おち○ちん、んんぅ、ふぅう、あぁっ<emoji=heart04>　が、ガチガチ、すぎますっ、あ、ぁあ、ああっ<emoji=heart04>　熱い、熱い、んんぅ、ぅうっ！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 熱くて硬いのは、ソフィのことが好きだからだ。色っぽくて、エッチな彼女だからこんなに硬くなっているんだと、何度もピストンで伝える。
line = "熱くて硬いのは、ソフィのことが好きだからだ。色っぽくて、エッチな彼女だからこんなに硬くなっているんだと、何度もピストンで伝える。"

[[dialogue]]
speaker = "ソフィア"
# 「んんぅっ、あ、あ、あぁ、ああっ<emoji=heart04>　ふぅっ、んんんっ！<emoji=heart04>　ちょ、ちょっと、ゆるめて、あ、ぁ、あぁ、あっ<emoji=heart04>　ゆるめてくださいっ<emoji=heart04>」
line = "「んんぅっ、あ、あ、あぁ、ああっ<emoji=heart04>　ふぅっ、んんんっ！<emoji=heart04>　ちょ、ちょっと、ゆるめて、あ、ぁ、あぁ、あっ<emoji=heart04>　ゆるめてくださいっ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「おち○ちん、よ、弱くしてっ<emoji=heart04>　て、手加減して、ください、ぃ──っ<emoji=heart04>」
line = "「おち○ちん、よ、弱くしてっ<emoji=heart04>　て、手加減して、ください、ぃ──っ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ソフィのこと、大好きだから無理」
line = "「ソフィのこと、大好きだから無理」"

[[dialogue]]
speaker = "ソフィア"
# 「そ、そっ──そんなぁっ<emoji=heart04>　あ、あ、ああっ<emoji=heart04>　ふうぁっ<emoji=heart04>　んんぅ<emoji=heart04>　あっあっあっあっあっ<emoji=heart04>」
line = "「そ、そっ──そんなぁっ<emoji=heart04>　あ、あ、ああっ<emoji=heart04>　ふうぁっ<emoji=heart04>　んんぅ<emoji=heart04>　あっあっあっあっあっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ピストンのたびに、ぷるんぷるんと揺れるおっぱいも揉みしだく。乳房をこねて、乳首をぴんぴん弾いていく。
line = "ピストンのたびに、ぷるんぷるんと揺れるおっぱいも揉みしだく。乳房をこねて、乳首をぴんぴん弾いていく。"

[[dialogue]]
speaker = "ソフィア"
# 「んんんぅーっ<emoji=heart04>　ふぅっ<emoji=heart04>　ふうううっ<emoji=heart04>　おっぱい、あ、あっ<emoji=heart04>　今、気持ちいいの、いっぱい来てて、だから触るの、ま、待って──」
line = "「んんんぅーっ<emoji=heart04>　ふぅっ<emoji=heart04>　ふうううっ<emoji=heart04>　おっぱい、あ、あっ<emoji=heart04>　今、気持ちいいの、いっぱい来てて、だから触るの、ま、待って──」"

[[dialogue]]
speaker = "クロト"
# 「ソフィのおっぱいも、大好きだから無理」
line = "「ソフィのおっぱいも、大好きだから無理」"

[[dialogue]]
speaker = "ソフィア"
# 「きゅっふ、ぅ、ぅ──ぁあ、あ、あぁあっ<emoji=heart04>　や、やぁっ──気持ちいいの、く、来る、来ちゃい、ま──す、ぅっ──<emoji=heart04>」
line = "「きゅっふ、ぅ、ぅ──ぁあ、あ、あぁあっ<emoji=heart04>　や、やぁっ──気持ちいいの、く、来る、来ちゃい、ま──す、ぅっ──<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「ぁっ──んんぅぅ、ぅうぅぅ～っ……！<emoji=heart04>」
line = "「ぁっ──んんぅぅ、ぅうぅぅ～っ……！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ソフィが軽く絶頂して、ぎゅぎゅうぅっ──！！　とペニスに苛烈な締め付けが走る。
line = "ソフィが軽く絶頂して、ぎゅぎゅうぅっ──！！　とペニスに苛烈な締め付けが走る。"

[[dialogue]]
speaker = "unk"
# 何度も経験していたから、快感に耐えながらピストンを続けられる。
line = "何度も経験していたから、快感に耐えながらピストンを続けられる。"

[[dialogue]]
speaker = "unk"
# フィギュアスケートで鍛えているからか、小柄ゆえに膣内が狭いからか──ソフィの絶頂の締め付けは本当にすさまじい。
line = "フィギュアスケートで鍛えているからか、小柄ゆえに膣内が狭いからか──ソフィの絶頂の締め付けは本当にすさまじい。"

[[dialogue]]
speaker = "ソフィア"
# 「ぁ、ふぁ、あぁ、あああっ！？<emoji=heart04>　会長さん、わ、私っ、イってます、イってますからっ……！　おち○ちん、止め、止めてっ……！<emoji=heart04>」
line = "「ぁ、ふぁ、あぁ、あああっ！？<emoji=heart04>　会長さん、わ、私っ、イってます、イってますからっ……！　おち○ちん、止め、止めてっ……！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ソフィのことをどれだけ愛しているかを伝えるエッチだから止まるわけがない。むしろ、さっきの締め付けで射精欲を刺激されてしまった。
line = "ソフィのことをどれだけ愛しているかを伝えるエッチだから止まるわけがない。むしろ、さっきの締め付けで射精欲を刺激されてしまった。"

[[dialogue]]
speaker = "ソフィア"
# 「あ、だ、だめっ……これ以上、速くするの、だ──めっ<emoji=heart04>」
line = "「あ、だ、だめっ……これ以上、速くするの、だ──めっ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「ひぅぅううっ<emoji=heart04>　んんぅうっ<emoji=heart04>　ぁあんっ<emoji=heart04>　あっあっあ、ひあ、あぁあ～っ<emoji=heart04>　や、やぁあ、やぁぁぁんんっ……<emoji=heart04>」
line = "「ひぅぅううっ<emoji=heart04>　んんぅうっ<emoji=heart04>　ぁあんっ<emoji=heart04>　あっあっあ、ひあ、あぁあ～っ<emoji=heart04>　や、やぁあ、やぁぁぁんんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「おち○ちん──ふっきゅ、ぅう！<emoji=heart04>　そんな乱暴に、ずぷずぷ、ひ、ひぁあぁあっ！<emoji=heart04>　あっ、あぁああ、ぁあ～っ！<emoji=heart04>」
line = "「おち○ちん──ふっきゅ、ぅう！<emoji=heart04>　そんな乱暴に、ずぷずぷ、ひ、ひぁあぁあっ！<emoji=heart04>　あっ、あぁああ、ぁあ～っ！<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「わ、私の体、持ち上げられちゃってますっ、ぁ、あぁああ！？<emoji=heart04>　反らせながら、ぱんぱん<emoji=heart04>　んぅ～っ、ふぅうっ、あぁああっ<emoji=heart04>」
line = "「わ、私の体、持ち上げられちゃってますっ、ぁ、あぁああ！？<emoji=heart04>　反らせながら、ぱんぱん<emoji=heart04>　んぅ～っ、ふぅうっ、あぁああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「串刺しに、されてる、みた──いっ……あ、あぁああ、んっ、ぅ、ふぅう～っ！<emoji=heart04>」
line = "「串刺しに、されてる、みた──いっ……あ、あぁああ、んっ、ぅ、ふぅう～っ！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ソフィが喘ぐたび、ぎゅうぅ、ぎゅぅぅう──とペニスが絞られて、ぞくぞくと精液が登ってきている。
line = "ソフィが喘ぐたび、ぎゅうぅ、ぎゅぅぅう──とペニスが絞られて、ぞくぞくと精液が登ってきている。"

[[dialogue]]
speaker = "unk"
# でもピストンは止めない。限界ぎりぎりまで全力で叩きつける。
line = "でもピストンは止めない。限界ぎりぎりまで全力で叩きつける。"

[[dialogue]]
speaker = "クロト"
# 「ソフィ……好きだ……！　大好きだっ……！」
line = "「ソフィ……好きだ……！　大好きだっ……！」"

[[dialogue]]
speaker = "ソフィア"
# 「わ、私も好きっ<emoji=heart04>　会長さんのこと好きっ<emoji=heart04>　あ、ぁあ、はぁあ<emoji=heart04>　もっと、もっと愛してくださいっ<emoji=heart04>　ぱんぱん、ぱんぱんしてっ<emoji=heart04>」
line = "「わ、私も好きっ<emoji=heart04>　会長さんのこと好きっ<emoji=heart04>　あ、ぁあ、はぁあ<emoji=heart04>　もっと、もっと愛してくださいっ<emoji=heart04>　ぱんぱん、ぱんぱんしてっ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「会長さんの気持ち、いっぱい、伝えてくださいっ<emoji=heart04>　私のこと、いっぱい求めてくださいっ──あ、ぁあ、ぁ、そこだめぇ、あぁあ～っ<emoji=heart04>」
line = "「会長さんの気持ち、いっぱい、伝えてくださいっ<emoji=heart04>　私のこと、いっぱい求めてくださいっ──あ、ぁあ、ぁ、そこだめぇ、あぁあ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ソフィの可愛くてエッチなお尻が波打つくらいにバチュバチュと腰を振る。おっぱいをもみくちゃにしながら、腰をぐいっと引き寄せて──
line = "ソフィの可愛くてエッチなお尻が波打つくらいにバチュバチュと腰を振る。おっぱいをもみくちゃにしながら、腰をぐいっと引き寄せて──"

[[dialogue]]
speaker = "ソフィア"
# 「キスっ……キスしてください、会長さんっ<emoji=heart04>　チューしながら出して、あ、ぁ、あぁ、あぁっ！<emoji=heart04>」
line = "「キスっ……キスしてください、会長さんっ<emoji=heart04>　チューしながら出して、あ、ぁ、あぁ、あぁっ！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 快感でふやけたソフィの唇を奪い、むさぼるようにかきまぜながらラストスパート。
line = "快感でふやけたソフィの唇を奪い、むさぼるようにかきまぜながらラストスパート。"

[[dialogue]]
speaker = "ソフィア"
# 「んぅじゅぅるる、れぇ、じゅるれる、ちゅるちゅぱっ<emoji=heart04>　れぇえ～っ<emoji=heart04>　んちゅぅう、じゅるぅ、ちゅるるう、んちゅぅ、ちゅぅ～っ<emoji=heart04>」
line = "「んぅじゅぅるる、れぇ、じゅるれる、ちゅるちゅぱっ<emoji=heart04>　れぇえ～っ<emoji=heart04>　んちゅぅう、じゅるぅ、ちゅるるう、んちゅぅ、ちゅぅ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「会長さっ、会長さんっ<emoji=heart04>　んぅぢゅるぅ<emoji=heart04>　れちょれちょれちょ<emoji=heart04>　んぅぢゅるるっ<emoji=heart04>　じゅるれる、じゅるぅう、れぇ～、じゅるぅっ<emoji=heart04>」
line = "「会長さっ、会長さんっ<emoji=heart04>　んぅぢゅるぅ<emoji=heart04>　れちょれちょれちょ<emoji=heart04>　んぅぢゅるるっ<emoji=heart04>　じゅるれる、じゅるぅう、れぇ～、じゅるぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「んぅじゅるるっ、しゅき<emoji=heart04>　んぅりゅ<emoji=heart04>　会長しゃん、しゅき<emoji=heart04>　だいしゅきっ、んぅっ<emoji=heart04>」
line = "「んぅじゅるるっ、しゅき<emoji=heart04>　んぅりゅ<emoji=heart04>　会長しゃん、しゅき<emoji=heart04>　だいしゅきっ、んぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「んっんっんっんっんっ──ぷぁあっ<emoji=heart04>　はあっ、おち○ちん、ふ、膨らんで来てますっ、で、出ますかっ？<emoji=heart04>　出ちゃうん、ですかっ？<emoji=heart04>」
line = "「んっんっんっんっんっ──ぷぁあっ<emoji=heart04>　はあっ、おち○ちん、ふ、膨らんで来てますっ、で、出ますかっ？<emoji=heart04>　出ちゃうん、ですかっ？<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# もう限界だ──精液が登ってきていて、あと数秒で我慢も利かなくなるのが分かった。
line = "もう限界だ──精液が登ってきていて、あと数秒で我慢も利かなくなるのが分かった。"

[[dialogue]]
speaker = "unk"
# ソフィと深いキスをしながら、イキたい──
line = "ソフィと深いキスをしながら、イキたい──"

[[dialogue]]
speaker = "ソフィア"
# 「んぅじゅぅるるうっ！<emoji=heart04>　んぢゅるるうっ！<emoji=heart04>　出してっ、会長さっ、出してっ、出して出して出してっ──ん──うぅぅう～っ！<emoji=heart04>」
line = "「んぅじゅぅるるうっ！<emoji=heart04>　んぢゅるるうっ！<emoji=heart04>　出してっ、会長さっ、出してっ、出して出して出してっ──ん──うぅぅう～っ！<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「んんぅっ！<emoji=heart04>　はぁ、あぁああ、ぁあぁああ～っ！？<emoji=heart04>」
line = "「んんぅっ！<emoji=heart04>　はぁ、あぁああ、ぁあぁああ～っ！？<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 放っている俺が驚くほどの勢いと量──熱い精液がドプドプとソフィの膣内に注がれていく。
line = "放っている俺が驚くほどの勢いと量──熱い精液がドプドプとソフィの膣内に注がれていく。"

[[dialogue]]
speaker = "ソフィア"
# 「熱いっ……ふぁ、あぁ、ああっ<emoji=heart04>　おま○こ、熱い、です、ぅうっ……<emoji=heart04>　頭の中、ばちばちって、して、へ、ぇえ、えぇっ……<emoji=heart04>」
line = "「熱いっ……ふぁ、あぁ、ああっ<emoji=heart04>　おま○こ、熱い、です、ぅうっ……<emoji=heart04>　頭の中、ばちばちって、して、へ、ぇえ、えぇっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 一滴も漏らさないために、彼女の腰を引きよせながら、最後の一滴まで、射精──
line = "一滴も漏らさないために、彼女の腰を引きよせながら、最後の一滴まで、射精──"

[[dialogue]]
speaker = "ソフィア"
# 「くっふぅ、ううぅ～！<emoji=heart04>　あ、あぁ、あぁあーっ……<emoji=heart04>　そんなぁっ……奥に押し付けながら、ぴゅっぴゅしちゃ──ひぁあぁあっっ<emoji=heart04>」
line = "「くっふぅ、ううぅ～！<emoji=heart04>　あ、あぁ、あぁあーっ……<emoji=heart04>　そんなぁっ……奥に押し付けながら、ぴゅっぴゅしちゃ──ひぁあぁあっっ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「あったかぁいっ……は、あぁあ、ぁああ～っ……<emoji=heart04>　会長さんの、精液っ……あ、ぁんっ……<emoji=heart04>　気持ちいぃっ……しゅ、しゅきぃ……<emoji=heart04>」
line = "「あったかぁいっ……は、あぁあ、ぁああ～っ……<emoji=heart04>　会長さんの、精液っ……あ、ぁんっ……<emoji=heart04>　気持ちいぃっ……しゅ、しゅきぃ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 体の内側からぽかぽかに温もっているからか、ソフィの声は本当に気持ちよさそうで……
line = "体の内側からぽかぽかに温もっているからか、ソフィの声は本当に気持ちよさそうで……"

[[dialogue]]
speaker = "unk"
# どぴゅ、どぴゅっ──と精液を放つたびに、可愛い声が出る。
line = "どぴゅ、どぴゅっ──と精液を放つたびに、可愛い声が出る。"

[[dialogue]]
speaker = "ソフィア"
# 「ひゃぅっ<emoji=heart04>　ぁっ<emoji=heart04>　ふぇあっ<emoji=heart04>　んんぅっ……ふぅうう～っ……あっ……はぁぁ、あぁぁあぁああぁーっ………………<emoji=heart04>」
line = "「ひゃぅっ<emoji=heart04>　ぁっ<emoji=heart04>　ふぇあっ<emoji=heart04>　んんぅっ……ふぅうう～っ……あっ……はぁぁ、あぁぁあぁああぁーっ………………<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 射精が収まったのを確認してから、ずるり──とペニスを引き抜く。
line = "射精が収まったのを確認してから、ずるり──とペニスを引き抜く。"

[[dialogue]]
speaker = "ソフィア"
# 「んはあぁっ……ふうぅうっ……はーっ……ふぅうう～っ……はぁあ～っ……<emoji=heart04>」
line = "「んはあぁっ……ふうぅうっ……はーっ……ふぅうう～っ……はぁあ～っ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ソフィのちっちゃな女性器から、とろとろと精液が溢れ出てくるのが見える……
line = "ソフィのちっちゃな女性器から、とろとろと精液が溢れ出てくるのが見える……"

[[dialogue]]
speaker = "ソフィア"
# 「会長さんのっ……ふぅうっ……気持ち、しっかり、伝わりました……<emoji=heart04>」
line = "「会長さんのっ……ふぅうっ……気持ち、しっかり、伝わりました……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「いっぱい、想ってもらえて……素敵な、エッチ……でした……<emoji=heart04>　んんぅっ……はぁあっ……<emoji=heart04>」
line = "「いっぱい、想ってもらえて……素敵な、エッチ……でした……<emoji=heart04>　んんぅっ……はぁあっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「愛してるよ、ソフィ。誰よりも」
line = "「愛してるよ、ソフィ。誰よりも」"

[[dialogue]]
speaker = "ソフィア"
# 「はい……私もです……会長さんのこと、愛してます……<emoji=heart04>」
line = "「はい……私もです……会長さんのこと、愛してます……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「あ……会長さんのおち○ちん……ピクって動きました……<emoji=heart04>」
line = "「あ……会長さんのおち○ちん……ピクって動きました……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# もちろん、たった１回で終わらせるつもりは毛頭ない。
line = "もちろん、たった１回で終わらせるつもりは毛頭ない。"

[[dialogue]]
speaker = "unk"
# 夜通し、全力でソフィを抱く。俺が彼女のことをどれくらい愛しているのか、知って欲しいから。
line = "夜通し、全力でソフィを抱く。俺が彼女のことをどれくらい愛しているのか、知って欲しいから。"

[[dialogue]]
speaker = "ソフィア"
# 「はい……<emoji=heart04>　会長さんが満足するまで、抱いてください……抱き潰して欲しいです……<emoji=heart04>」
line = "「はい……<emoji=heart04>　会長さんが満足するまで、抱いてください……抱き潰して欲しいです……<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「キス、い～っぱいしながら……お腹の奥……何回も……びゅーっ……<emoji=heart04>　て、して欲しいです……<emoji=heart04>」
line = "「キス、い～っぱいしながら……お腹の奥……何回も……びゅーっ……<emoji=heart04>　て、して欲しいです……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その後──夜が更けて、朝が来るまで。俺とソフィは全身汗だくになりながら、交わり続けるのだった。
line = "その後──夜が更けて、朝が来るまで。俺とソフィは全身汗だくになりながら、交わり続けるのだった。"
