[[dialogue]]
speaker = "unk"
# 第２話,ポンポンパンチ！,P
line = "第２話,ポンポンパンチ！,P"

[[dialogue]]
speaker = "カティア"
# 「応援ありがとう、美鶴！　おかげで入賞できたワン！」
line = "「応援ありがとう、美鶴！　おかげで入賞できたワン！」"

[[dialogue]]
speaker = "美鶴"
# 「どういたしまして。お役に立てたなら何よりっす」
line = "「どういたしまして。お役に立てたなら何よりっす」"

[[dialogue]]
speaker = "unk"
# 星霊祭でフランに気に入られた美鶴は、チア服の研究の一環で、時々応援団のヘルプに入っていた。
line = "星霊祭でフランに気に入られた美鶴は、チア服の研究の一環で、時々応援団のヘルプに入っていた。"

[[dialogue]]
speaker = "カティア"
# 「美鶴に応援されると、集中力がギュンってなって自分だけの世界に入れるんだ。あれがいわゆるゾーンっていうの？」
line = "「美鶴に応援されると、集中力がギュンってなって自分だけの世界に入れるんだ。あれがいわゆるゾーンっていうの？」"

[[dialogue]]
speaker = "カティア"
# 「元気が出る魔王様のと違って面白いや！　またお願いね！」
line = "「元気が出る魔王様のと違って面白いや！　またお願いね！」"

[[dialogue]]
speaker = "美鶴"
# 「げ、モンスターすか」
line = "「げ、モンスターすか」"

[[dialogue]]
speaker = "カティア"
# 「魔王様、私たちで対処しましょう！　ここから近いみたいですガオ！」
line = "「魔王様、私たちで対処しましょう！　ここから近いみたいですガオ！」"

[[dialogue]]
speaker = "美鶴"
# 「しゃーないっすね。こんなカッコだし、うちは２人を徹底サポートしますよ」
line = "「しゃーないっすね。こんなカッコだし、うちは２人を徹底サポートしますよ」"

[[dialogue]]
speaker = "モンスター"
# 「イーーーッ！」
line = "「イーーーッ！」"

[[dialogue]]
speaker = "カティア"
# 「あ、モンスターがこっちに来ました！」
line = "「あ、モンスターがこっちに来ました！」"

[[dialogue]]
speaker = "美鶴"
# 「がんばれがんばれ、２人とも～。悪～いモンスターやっつけろ～」
line = "「がんばれがんばれ、２人とも～。悪～いモンスターやっつけろ～」"

[[dialogue]]
speaker = "カティア"
# 「フルスピーーードッ！　今です、魔王様っ！」
line = "「フルスピーーードッ！　今です、魔王様っ！」"

[[dialogue]]
speaker = "unk"
# 俺がトドメを刺す！
line = "俺がトドメを刺す！"

[[dialogue]]
speaker = "unk"
# カティアのスピードでかく乱し……
line = "カティアのスピードでかく乱し……"

[[dialogue]]
speaker = "モンスター"
# 「イィィ……」
line = "「イィィ……」"

[[dialogue]]
speaker = "カティア"
# 「さすが魔王様～♪　お見事ですワン！」
line = "「さすが魔王様～♪　お見事ですワン！」"

[[dialogue]]
speaker = "美鶴"
# 「む……」
line = "「む……」"

[[dialogue]]
speaker = "美鶴"
# （カティアにはそーゆーつもりはなさそうなんだけど……会長さんとイチャってるとこ見ると、なーんかモヤる）
line = "（カティアにはそーゆーつもりはなさそうなんだけど……会長さんとイチャってるとこ見ると、なーんかモヤる）"

[[dialogue]]
speaker = "カティア"
# 「美鶴もナイス応援ガオ！　爆速で動けたワン！」
line = "「美鶴もナイス応援ガオ！　爆速で動けたワン！」"

[[dialogue]]
speaker = "美鶴"
# 「ん、ども」
line = "「ん、ども」"

[[dialogue]]
speaker = "カティア"
# 「今のでモンスターは全部やっつけたガオ？　大したことなかったですね！　私たちの連携、完璧すぎです！」
line = "「今のでモンスターは全部やっつけたガオ？　大したことなかったですね！　私たちの連携、完璧すぎです！」"

[[dialogue]]
speaker = "unk"
# まだ反応が残っている
line = "まだ反応が残っている"

[[dialogue]]
speaker = "unk"
# 油断は禁物だぞ
line = "油断は禁物だぞ"

[[dialogue]]
speaker = "カティア"
# 「ふふーん、どっからでもかかってきやがれだワン！　シュッ、シュッ！」
line = "「ふふーん、どっからでもかかってきやがれだワン！　シュッ、シュッ！」"

[[dialogue]]
speaker = "モンスター"
# 「クルルーッ！」
line = "「クルルーッ！」"

[[dialogue]]
speaker = "美鶴"
# 「！？　カティア、後ろっ！」
line = "「！？　カティア、後ろっ！」"

[[dialogue]]
speaker = "カティア"
# 「わふっ！？　不意打ちっ！？」
line = "「わふっ！？　不意打ちっ！？」"

[[dialogue]]
speaker = "美鶴"
# （会長さんも間に合わないかっ！　だったら、うちが──）
line = "（会長さんも間に合わないかっ！　だったら、うちが──）"

[[dialogue]]
speaker = "美鶴"
# 「ぶん殴った方が早いっ！」
line = "「ぶん殴った方が早いっ！」"

[[dialogue]]
speaker = "美鶴"
# 「閃拳・輝禍祓掌っ！」
line = "「閃拳・輝禍祓掌っ！」"

[[dialogue]]
speaker = "モンスター"
# 「クルルッ！？」
line = "「クルルッ！？」"

[[dialogue]]
speaker = "unk"
# ナイスパンチ！
line = "ナイスパンチ！"

[[dialogue]]
speaker = "unk"
# ポンポンでぶん殴った！？
line = "ポンポンでぶん殴った！？"

[[dialogue]]
speaker = "美鶴"
# 「あー、スッキリー。やっぱ、うちは応援でサポるより戦闘に参加する方が性に合ってるみたいすね」
line = "「あー、スッキリー。やっぱ、うちは応援でサポるより戦闘に参加する方が性に合ってるみたいすね」"

[[dialogue]]
speaker = "美鶴"
# 「カティア、お手本みたいな油断だったよ。気ぃつけて」
line = "「カティア、お手本みたいな油断だったよ。気ぃつけて」"

[[dialogue]]
speaker = "カティア"
# 「うぅ、面目ないワン。守ってくれてありがとう！」
line = "「うぅ、面目ないワン。守ってくれてありがとう！」"

[[dialogue]]
speaker = "カティア"
# 「くんくん……んん！？　モンスターの新手、全方向から来ます！」
line = "「くんくん……んん！？　モンスターの新手、全方向から来ます！」"

[[dialogue]]
speaker = "モンスター"
# 「イ～～～ッ！」
line = "「イ～～～ッ！」"

[[dialogue]]
speaker = "モンスター"
# 「イーーーーッ！」
line = "「イーーーーッ！」"

[[dialogue]]
speaker = "美鶴"
# 「うっわ、めちゃおかわり来た」
line = "「うっわ、めちゃおかわり来た」"

[[dialogue]]
speaker = "美鶴"
# 「ここからはうちの応援なしでいいすか？　うちも殴るんで」
line = "「ここからはうちの応援なしでいいすか？　うちも殴るんで」"

[[dialogue]]
speaker = "unk"
# 背中は任せた！
line = "背中は任せた！"

[[dialogue]]
speaker = "カティア"
# 「美鶴が後ろにいてくれると心強いワン！」
line = "「美鶴が後ろにいてくれると心強いワン！」"

[[dialogue]]
speaker = "美鶴"
# 「ま、応援するよか背中を任される方が、うちらしいかもすね」
line = "「ま、応援するよか背中を任される方が、うちらしいかもすね」"

[[dialogue]]
speaker = "美鶴"
# 「さ、うちのポンポンに殴られたい奴からかかって来な」
line = "「さ、うちのポンポンに殴られたい奴からかかって来な」"

[[dialogue]]
speaker = "unk"
# 美鶴がモンスターを片っ端から殴り倒し、街の平和を取り戻したのだった。
line = "美鶴がモンスターを片っ端から殴り倒し、街の平和を取り戻したのだった。"
