[[dialogue]]
speaker = "unk"
# 第４話,クリスマスデート,P
line = "第４話,クリスマスデート,P"

[[dialogue]]
speaker = "unk"
# そしてクリスマス当日──
line = "そしてクリスマス当日──"

[[dialogue]]
speaker = "モネ"
# 「お、おはようございます……待ちましたか？」
line = "「お、おはようございます……待ちましたか？」"

[[dialogue]]
speaker = "unk"
# 全然。今来たところ
line = "全然。今来たところ"

[[dialogue]]
speaker = "モネ"
# 「そ、そうですか……ベタベタなやり取りですね……はは」
line = "「そ、そうですか……ベタベタなやり取りですね……はは」"

[[dialogue]]
speaker = "モネ"
# 「……チラ」
line = "「……チラ」"

[[dialogue]]
speaker = "モネ"
# （デートなんだから、手を繋ぐくらいは……ああいや、いきなりそんなことしたら、はしたないって思われるかな……？　ていうか恥ずかしい……！）
line = "（デートなんだから、手を繋ぐくらいは……ああいや、いきなりそんなことしたら、はしたないって思われるかな……？　ていうか恥ずかしい……！）"

[[dialogue]]
speaker = "モネ"
# 「ひゃわ！？　い、いきなり手を！？　どど、どうしたんですか？」
line = "「ひゃわ！？　い、いきなり手を！？　どど、どうしたんですか？」"

[[dialogue]]
speaker = "モネ"
# 「デートなんだから手を繋ぎたい……？　そ、そうですねっ、小説のネタのためにデートするんですもんねっ」
line = "「デートなんだから手を繋ぎたい……？　そ、そうですねっ、小説のネタのためにデートするんですもんねっ」"

[[dialogue]]
speaker = "モネ"
# （でも手汗とか大丈夫かなぁ……ううぅ、慌てるな私、落ち着け私……）
line = "（でも手汗とか大丈夫かなぁ……ううぅ、慌てるな私、落ち着け私……）"

[[dialogue]]
speaker = "モネ"
# （だけど会長は、どうして私なんかと恋人になってくれたんだろう……？　会長は優しくて頼りになるけど、私なんて本を読んでばっかりなのに……）
line = "（だけど会長は、どうして私なんかと恋人になってくれたんだろう……？　会長は優しくて頼りになるけど、私なんて本を読んでばっかりなのに……）"

[[dialogue]]
speaker = "モネ"
# 「あっ、すみません。一瞬考え事していて……」
line = "「あっ、すみません。一瞬考え事していて……」"

[[dialogue]]
speaker = "モネ"
# 「えっと、今日のデートは小説の取材も兼ねてなので、いつも私がやらないことにも挑戦してみようと思いますっ」
line = "「えっと、今日のデートは小説の取材も兼ねてなので、いつも私がやらないことにも挑戦してみようと思いますっ」"

[[dialogue]]
speaker = "unk"
# そうして俺たちは、手を繋ぎながら繁華街へ。
line = "そうして俺たちは、手を繋ぎながら繁華街へ。"

[[dialogue]]
speaker = "モネ"
# 「あ、ありました、ゲームセンター。今まで来たことはありませんが、本で読んだところによると、いかがわしい雰囲気もあるとか……」
line = "「あ、ありました、ゲームセンター。今まで来たことはありませんが、本で読んだところによると、いかがわしい雰囲気もあるとか……」"

[[dialogue]]
speaker = "unk"
# 大丈夫、怖いところじゃないよ
line = "大丈夫、怖いところじゃないよ"

[[dialogue]]
speaker = "モネ"
# 「は、はいっ。では入ってみましょう……！」
line = "「は、はいっ。では入ってみましょう……！」"

[[dialogue]]
speaker = "モネ"
# 「初めてのゲームセンターでしたが、想像より音と光がすごくて、ちょっとしたカルチャーショックでした……」
line = "「初めてのゲームセンターでしたが、想像より音と光がすごくて、ちょっとしたカルチャーショックでした……」"

[[dialogue]]
speaker = "モネ"
# 「アーケードゲームを取り扱った本は読んだことあるんですけど、実際にやるのは違いますね。全然上手くできなかったけど、楽しかったです」
line = "「アーケードゲームを取り扱った本は読んだことあるんですけど、実際にやるのは違いますね。全然上手くできなかったけど、楽しかったです」"

[[dialogue]]
speaker = "モネ"
# 「それにクレーンゲームで、キーホルダーを取ってもらって……これ、前から読んでて好きなマンガのマスコットなんですよ。大事にします」
line = "「それにクレーンゲームで、キーホルダーを取ってもらって……これ、前から読んでて好きなマンガのマスコットなんですよ。大事にします」"

[[dialogue]]
speaker = "モネ"
# 「次は映画ですね。とっても感動した小説が原作なんですけど、ちゃんと再現されているかどうか……期待半分、不安半分でドキドキです」
line = "「次は映画ですね。とっても感動した小説が原作なんですけど、ちゃんと再現されているかどうか……期待半分、不安半分でドキドキです」"

[[dialogue]]
speaker = "unk"
# どういうところが魅力なの？
line = "どういうところが魅力なの？"

[[dialogue]]
speaker = "モネ"
# 「そうですね、見どころはたくさんあるのですが、命懸けで恋人を助け──ああ～っ！？　これ以上はネタバレですっ！？」
line = "「そうですね、見どころはたくさんあるのですが、命懸けで恋人を助け──ああ～っ！？　これ以上はネタバレですっ！？」"

[[dialogue]]
speaker = "モネ"
# 「ちょっと言葉では説明できないというか、今のでもけっこうヤバいというか、とにかく見てみましょうっ！」
line = "「ちょっと言葉では説明できないというか、今のでもけっこうヤバいというか、とにかく見てみましょうっ！」"

[[dialogue]]
speaker = "モネ"
# 「……あれ、どうして笑ってるんですか、会長？」
line = "「……あれ、どうして笑ってるんですか、会長？」"

[[dialogue]]
speaker = "モネ"
# 「……モネらしいから？　どういう意味ですか～～っ！？」
line = "「……モネらしいから？　どういう意味ですか～～っ！？」"

[[dialogue]]
speaker = "モネ"
# 「会長、映画はどうでした？　ネタバレしないでよかったですよね？」
line = "「会長、映画はどうでした？　ネタバレしないでよかったですよね？」"

[[dialogue]]
speaker = "モネ"
# 「……ふふ、ですよね。私も涙が出るほど感動しちゃいました」
line = "「……ふふ、ですよね。私も涙が出るほど感動しちゃいました」"

[[dialogue]]
speaker = "モネ"
# 「夜の海もいいですよね。街の夜景もいいんですけど、どうせならと思ってリップルさんにお願いして、リゾート結界を用意してもらいました」
line = "「夜の海もいいですよね。街の夜景もいいんですけど、どうせならと思ってリップルさんにお願いして、リゾート結界を用意してもらいました」"

[[dialogue]]
speaker = "モネ"
# 「じゃあ海らしく……」
line = "「じゃあ海らしく……」"

[[dialogue]]
speaker = "モネ"
# 「えへへ……恥ずかしいですけど、水着はかわいいですから。私なんかにはもったいないかもしれないですけど……」
line = "「えへへ……恥ずかしいですけど、水着はかわいいですから。私なんかにはもったいないかもしれないですけど……」"

[[dialogue]]
speaker = "unk"
# 水着のモネ、すごくかわいい
line = "水着のモネ、すごくかわいい"

[[dialogue]]
speaker = "モネ"
# 「ひゃっ！？　そ、そんな、無理してほめなくても……」
line = "「ひゃっ！？　そ、そんな、無理してほめなくても……」"

[[dialogue]]
speaker = "モネ"
# 「ひあああっ！？　きゅっ、急に抱きしめてどうしたんですか～っ！？」
line = "「ひあああっ！？　きゅっ、急に抱きしめてどうしたんですか～っ！？」"

[[dialogue]]
speaker = "unk"
# 好きだよ、モネ
line = "好きだよ、モネ"

[[dialogue]]
speaker = "モネ"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "モネ"
# 「どうして……なんでしょうか」
line = "「どうして……なんでしょうか」"

[[dialogue]]
speaker = "モネ"
# 「もっと素敵な人、会長にふさわしい人は他にたくさんいます。それこそリップルさんみたいに、明るくて笑顔が似合う人が」
line = "「もっと素敵な人、会長にふさわしい人は他にたくさんいます。それこそリップルさんみたいに、明るくて笑顔が似合う人が」"

[[dialogue]]
speaker = "モネ"
# 「でも私は、人より本の友達が多いような人間で……性格も明るくなくて、星騎士として強くもなくて……いいところなんてないです」
line = "「でも私は、人より本の友達が多いような人間で……性格も明るくなくて、星騎士として強くもなくて……いいところなんてないです」"

[[dialogue]]
speaker = "モネ"
# 「強くてみんなから慕われている会長とは、とても釣り合わないです……」
line = "「強くてみんなから慕われている会長とは、とても釣り合わないです……」"

[[dialogue]]
speaker = "unk"
# 本に夢中になってるモネはとっても素敵だ
line = "本に夢中になってるモネはとっても素敵だ"

[[dialogue]]
speaker = "モネ"
# 「そ、そうなんですか……？」
line = "「そ、そうなんですか……？」"

[[dialogue]]
speaker = "unk"
# そんなモネが大好きだ！
line = "そんなモネが大好きだ！"

[[dialogue]]
speaker = "モネ"
# 「大好き……！？　そ、そこまでですか……！？」
line = "「大好き……！？　そ、そこまでですか……！？」"

[[dialogue]]
speaker = "モネ"
# 「あはは……そこまで言われると、うじうじしてる自分がバカらしくなってきました……」
line = "「あはは……そこまで言われると、うじうじしてる自分がバカらしくなってきました……」"

[[dialogue]]
speaker = "モネ"
# 「自分がダメだと思っているところも、人から見ると魅力になりうる……それも学びかもしれませんね。小説の参考にします」
line = "「自分がダメだと思っているところも、人から見ると魅力になりうる……それも学びかもしれませんね。小説の参考にします」"

[[dialogue]]
speaker = "モネ"
# 「もう自分を人と比べて、ふさわしくないとか言うのはやめにします。好きって言ってくれる会長にも失礼ですから」
line = "「もう自分を人と比べて、ふさわしくないとか言うのはやめにします。好きって言ってくれる会長にも失礼ですから」"

[[dialogue]]
speaker = "モネ"
# 「だから……ちゅっ<emoji=heart04>」
line = "「だから……ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "モネ"
# 「私も好きです。会長のこと大好きです」
line = "「私も好きです。会長のこと大好きです」"

[[dialogue]]
speaker = "モネ"
# 「だから一緒にいましょうね。ずっと、ずっと……末永くよろしくお願いします」
line = "「だから一緒にいましょうね。ずっと、ずっと……末永くよろしくお願いします」"

[[dialogue]]
speaker = "モネ"
# 「来年のクリスマスも、また一緒に過ごしましょうね<emoji=heart04>」
line = "「来年のクリスマスも、また一緒に過ごしましょうね<emoji=heart04>」"
