[[dialogue]]
speaker = "unk"
# 第２話,ソフィア流サーフィン,P
line = "第２話,ソフィア流サーフィン,P"

[[dialogue]]
speaker = "ソフィア"
# 「──サーフィン、ですか？」
line = "「──サーフィン、ですか？」"

[[dialogue]]
speaker = "ソフィア"
# 「なるほど……私もやってみてはどうか、と。確かにフィオナ会長もさっそうと波に乗っていましたね」
line = "「なるほど……私もやってみてはどうか、と。確かにフィオナ会長もさっそうと波に乗っていましたね」"

[[dialogue]]
speaker = "ソフィア"
# 「それに、サーフィンといえば大人らしい趣味のイメージがあります」
line = "「それに、サーフィンといえば大人らしい趣味のイメージがあります」"

[[dialogue]]
speaker = "ソフィア"
# 「いずれ私もフィオナ会長と同じビッグウェーブに乗れれば、きっと違った目で見てくれるはずです」
line = "「いずれ私もフィオナ会長と同じビッグウェーブに乗れれば、きっと違った目で見てくれるはずです」"

[[dialogue]]
speaker = "unk"
# かもしれない
line = "かもしれない"

[[dialogue]]
speaker = "unk"
# 冬だけどね
line = "冬だけどね"

[[dialogue]]
speaker = "ソフィア"
# 「はい！　ふふ、会長さんはサーフィンもお手のものなんですよね？　そうお聞きしましたよ」
line = "「はい！　ふふ、会長さんはサーフィンもお手のものなんですよね？　そうお聞きしましたよ」"

[[dialogue]]
speaker = "ソフィア"
# 「ぜひ私にも教えてください。これもひと夏の体験というものです！」
line = "「ぜひ私にも教えてください。これもひと夏の体験というものです！」"

[[dialogue]]
speaker = "ソフィア"
# 「──むぅ…………」
line = "「──むぅ…………」"

[[dialogue]]
speaker = "ソフィア"
# 「なんなんですか、これは。まるで安定しません……！　波に乗るどころか、ボードの上に立つことすらままならないじゃないですか」
line = "「なんなんですか、これは。まるで安定しません……！　波に乗るどころか、ボードの上に立つことすらままならないじゃないですか」"

[[dialogue]]
speaker = "ソフィア"
# 「んっ、しょ……よっ……ほっ……このまま……重心を崩さずに………………あっ！？」
line = "「んっ、しょ……よっ……ほっ……このまま……重心を崩さずに………………あっ！？」"

[[dialogue]]
speaker = "ソフィア"
# 「ごぼごぼごぼごぼ……！！！」
line = "「ごぼごぼごぼごぼ……！！！」"

[[dialogue]]
speaker = "ソフィア"
# 「ぷはぁあああっ！！」
line = "「ぷはぁあああっ！！」"

[[dialogue]]
speaker = "ソフィア"
# 「むむむぅ……楽しくありません……人のを見ていたら、簡単そうに見えたのに……」
line = "「むむむぅ……楽しくありません……人のを見ていたら、簡単そうに見えたのに……」"

[[dialogue]]
speaker = "unk"
# 最初は皆そう
line = "最初は皆そう"

[[dialogue]]
speaker = "unk"
# 何事も練習だ
line = "何事も練習だ"

[[dialogue]]
speaker = "ソフィア"
# 「確かに……一朝一夕でどうこうなるものではありませんか……」
line = "「確かに……一朝一夕でどうこうなるものではありませんか……」"

[[dialogue]]
speaker = "ソフィア"
# 「私のスケートもそうですが、ただ見ているのと、実際にやってみるのとでは、大きな違いがありますからね」
line = "「私のスケートもそうですが、ただ見ているのと、実際にやってみるのとでは、大きな違いがありますからね」"

[[dialogue]]
speaker = "ソフィア"
# 「それに、ちょうどいい波を待つのも大変です。ただでさえ難儀なのに、タイミングまで要求されるとは──」
line = "「それに、ちょうどいい波を待つのも大変です。ただでさえ難儀なのに、タイミングまで要求されるとは──」"

[[dialogue]]
speaker = "ソフィア"
# 「……って……いつまで私のことを抱きかかえてるんです？」
line = "「……って……いつまで私のことを抱きかかえてるんです？」"

[[dialogue]]
speaker = "ソフィア"
# 「全くもう、会長さんまで私のことを子ども扱いして。まぁ……お姫様抱っこの心地は、悪くありませんでしたけど」
line = "「全くもう、会長さんまで私のことを子ども扱いして。まぁ……お姫様抱っこの心地は、悪くありませんでしたけど」"

[[dialogue]]
speaker = "ソフィア"
# 「しかし、どうしましょう。このままでは格好よくサーフィンなんて夢のまた夢……」
line = "「しかし、どうしましょう。このままでは格好よくサーフィンなんて夢のまた夢……」"

[[dialogue]]
speaker = "unk"
# フィギュアの要領で
line = "フィギュアの要領で"

[[dialogue]]
speaker = "unk"
# 海をリンクだと思って
line = "海をリンクだと思って"

[[dialogue]]
speaker = "ソフィア"
# 「ん？　確かに──そうだ、思いついたことがあったんです」
line = "「ん？　確かに──そうだ、思いついたことがあったんです」"

[[dialogue]]
speaker = "ソフィア"
# 「……………………よし」
line = "「……………………よし」"

[[dialogue]]
speaker = "unk"
# 何をする気だ？
line = "何をする気だ？"

[[dialogue]]
speaker = "unk"
# よし、って？
line = "よし、って？"

[[dialogue]]
speaker = "ソフィア"
# 「まあまあ。お気になさらずです、会長さん」
line = "「まあまあ。お気になさらずです、会長さん」"

[[dialogue]]
speaker = "ソフィア"
# 「波？　いえ、波は待っていません。むしろ──波のない瞬間を待っているんです」
line = "「波？　いえ、波は待っていません。むしろ──波のない瞬間を待っているんです」"

[[dialogue]]
speaker = "ソフィア"
# 「この一瞬の凪……今ですっ！　コキュートスダイブ！」
line = "「この一瞬の凪……今ですっ！　コキュートスダイブ！」"

[[dialogue]]
speaker = "ソフィア"
# 「──よし！　凍結完了です」
line = "「──よし！　凍結完了です」"

[[dialogue]]
speaker = "unk"
# 海が凍って……
line = "海が凍って……"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "ソフィア"
# 「はい！　これで天然のスケートリンク完成です！」
line = "「はい！　これで天然のスケートリンク完成です！」"

[[dialogue]]
speaker = "ソフィア"
# 「まさか？　ええ、もちろん。そのまさかです。この上を直接滑れば──海に乗るという意味では同じ！　実質サーフィンみたいなものです！」
line = "「まさか？　ええ、もちろん。そのまさかです。この上を直接滑れば──海に乗るという意味では同じ！　実質サーフィンみたいなものです！」"

[[dialogue]]
speaker = "unk"
# でこぼこだらけだ
line = "でこぼこだらけだ"

[[dialogue]]
speaker = "unk"
# 危ないよ
line = "危ないよ"

[[dialogue]]
speaker = "ソフィア"
# 「確かに、凪の一瞬を狙ったとはいえさざなみは立っていました。整氷の必要がありますね」
line = "「確かに、凪の一瞬を狙ったとはいえさざなみは立っていました。整氷の必要がありますね」"

[[dialogue]]
speaker = "ソフィア"
# 「フィギュアにおいてリンク上の穴は大敵です。下手にハマってしまうと大怪我の危険もありますからね。丁寧に、こう、<ruby=なら>均</ruby>してっと……」
line = "「フィギュアにおいてリンク上の穴は大敵です。下手にハマってしまうと大怪我の危険もありますからね。丁寧に、こう、<ruby>均<rt>なら</rt></ruby>してっと……」"

[[dialogue]]
speaker = "ソフィア"
# 「──ふふふん♪　どうですか、私の華麗なるサーフィンは♪　２回転だってお手の物です♪」
line = "「──ふふふん♪　どうですか、私の華麗なるサーフィンは♪　２回転だってお手の物です♪」"

[[dialogue]]
speaker = "unk"
# サーフィンじゃない
line = "サーフィンじゃない"

[[dialogue]]
speaker = "unk"
# そっちのほうが難しい
line = "そっちのほうが難しい"

[[dialogue]]
speaker = "ソフィア"
# 「むぅ……細かいことはいいじゃないですか。一応、波には乗ったんですから──って。あ」
line = "「むぅ……細かいことはいいじゃないですか。一応、波には乗ったんですから──って。あ」"

[[dialogue]]
speaker = "ソフィア"
# 「しまった。このやり方だと、フィオナ会長と一緒に波に乗ることができません……！」
line = "「しまった。このやり方だと、フィオナ会長と一緒に波に乗ることができません……！」"

[[dialogue]]
speaker = "ソフィア"
# 「やはり地道な積み重ねしかありませんか。やれやれ……何事も楽はできませんね」
line = "「やはり地道な積み重ねしかありませんか。やれやれ……何事も楽はできませんね」"

[[dialogue]]
speaker = "ソフィア"
# 「きっと、何度も落ちてしまうでしょうから……その度に私を助けてくださいね？　会長さん<emoji=heart04>」
line = "「きっと、何度も落ちてしまうでしょうから……その度に私を助けてくださいね？　会長さん<emoji=heart04>」"
