[[dialogue]]
speaker = "unk"
# 第４話,ナミエルとアフタークリスマス②,P
line = "第４話,ナミエルとアフタークリスマス②,P"

[[dialogue]]
speaker = "ナミエル"
# 「まさか、クリスマスフォームの不思議な力がまた発動してしまうだなんて……」
line = "「まさか、クリスマスフォームの不思議な力がまた発動してしまうだなんて……」"

[[dialogue]]
speaker = "unk"
# デートの最後、何故かクリスマスフォームに変身してしまったナミエルは、磁石で引き寄せられるように、俺と１メートル以上離れられない状態となってしまった。
line = "デートの最後、何故かクリスマスフォームに変身してしまったナミエルは、磁石で引き寄せられるように、俺と１メートル以上離れられない状態となってしまった。"

[[dialogue]]
speaker = "ナミエル"
# 「それで会長の家に泊まることになって……。し、しかも、リノさままで気遣って、わざわざ家を空けるだなんて……」
line = "「それで会長の家に泊まることになって……。し、しかも、リノさままで気遣って、わざわざ家を空けるだなんて……」"

[[dialogue]]
speaker = "unk"
# イチャイチャするように言われてるみたい？
line = "イチャイチャするように言われてるみたい？"

[[dialogue]]
speaker = "ナミエル"
# 「っ……わざわざ言わなくてもいいですから！　うぅ……なんか恥ずかしいです……」
line = "「っ……わざわざ言わなくてもいいですから！　うぅ……なんか恥ずかしいです……」"

[[dialogue]]
speaker = "ナミエル"
# 「え？　離れられなくなる力が発動してしまった原因ですか……？」
line = "「え？　離れられなくなる力が発動してしまった原因ですか……？」"

[[dialogue]]
speaker = "ナミエル"
# 「――このところ、スキンシップできていなかったから？　ち、違いますっ……！」
line = "「――このところ、スキンシップできていなかったから？　ち、違いますっ……！」"

[[dialogue]]
speaker = "ナミエル"
# 「確かに、クリスマス以前から今日まで、アム先輩と離れられない状態だったので、会長と全然スキンシップはできてませんでしたけど……！」
line = "「確かに、クリスマス以前から今日まで、アム先輩と離れられない状態だったので、会長と全然スキンシップはできてませんでしたけど……！」"

[[dialogue]]
speaker = "unk"
# でも、試してみる価値はあるかも？
line = "でも、試してみる価値はあるかも？"

[[dialogue]]
speaker = "ナミエル"
# 「も、もうっ……会長がスキンシップしたいだけなんじゃないですか……？　いやらしいですよ……！」
line = "「も、もうっ……会長がスキンシップしたいだけなんじゃないですか……？　いやらしいですよ……！」"

[[dialogue]]
speaker = "ナミエル"
# 「――じゃあ、しないのかって……べ、別にそんな風には言ってないじゃないですか……」
line = "「――じゃあ、しないのかって……べ、別にそんな風には言ってないじゃないですか……」"

[[dialogue]]
speaker = "unk"
# そんなこんなで、俺たちは久しぶりに２人で恋人同士のスキンシップをすることになった。
line = "そんなこんなで、俺たちは久しぶりに２人で恋人同士のスキンシップをすることになった。"

[[dialogue]]
speaker = "ナミエル"
# 「ん……<emoji=heart04>　はあぁ……ふうぅ……<emoji=heart04>」
line = "「ん……<emoji=heart04>　はあぁ……ふうぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ソファーに腰かけて、膝の上にナミエルを座らせる。後ろから少し体重をかけるように覆い被さると、彼女は吐息を漏らす。
line = "ソファーに腰かけて、膝の上にナミエルを座らせる。後ろから少し体重をかけるように覆い被さると、彼女は吐息を漏らす。"

[[dialogue]]
speaker = "ナミエル"
# （あ……<emoji=heart04>　会長の手が頬を撫でてきて……んっ<emoji=heart04>　ふうぅ……<emoji=heart04>）
line = "（あ……<emoji=heart04>　会長の手が頬を撫でてきて……んっ<emoji=heart04>　ふうぅ……<emoji=heart04>）"

[[dialogue]]
speaker = "unk"
# ナミエルと付き合う中で、彼女がどんな風にスキンシップされるのが好きなのか、俺も少しずつ分かるようになってきていた。
line = "ナミエルと付き合う中で、彼女がどんな風にスキンシップされるのが好きなのか、俺も少しずつ分かるようになってきていた。"

[[dialogue]]
speaker = "ナミエル"
# 「んんっ……<emoji=heart04>　会長、頬ずりまでしてきて……いやらしいですよ……<emoji=heart04>」
line = "「んんっ……<emoji=heart04>　会長、頬ずりまでしてきて……いやらしいですよ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# たまには甘えて欲しいな
line = "たまには甘えて欲しいな"

[[dialogue]]
speaker = "unk"
# ウェディングフォームの時みたいに
line = "ウェディングフォームの時みたいに"

[[dialogue]]
speaker = "ナミエル"
# 「う、ウェディングフォームについては、恥ずかしいからあんまり言わないで下さい……！」
line = "「う、ウェディングフォームについては、恥ずかしいからあんまり言わないで下さい……！」"

[[dialogue]]
speaker = "ナミエル"
# 「あ、あれはちょっと、フォームの特性で、変身すると精神が影響を受けるというか……<emoji=heart04>」
line = "「あ、あれはちょっと、フォームの特性で、変身すると精神が影響を受けるというか……<emoji=heart04>」"

[[dialogue]]
speaker = "ナミエル"
# 「――え？　い、言ってることが全部ウソってわけじゃないですけど……も、もうっ。そこは恋人として察して下さい……！」
line = "「――え？　い、言ってることが全部ウソってわけじゃないですけど……も、もうっ。そこは恋人として察して下さい……！」"

[[dialogue]]
speaker = "unk"
# 恥ずかしがっているナミエルに、俺はもう１度耳元で、甘えて欲しいとお願いする。
line = "恥ずかしがっているナミエルに、俺はもう１度耳元で、甘えて欲しいとお願いする。"

[[dialogue]]
speaker = "ナミエル"
# 「ん……<emoji=heart04>　仕方ないですね……<emoji=heart04>　わかりました。その代わり、変にからかったりしちゃダメですからね……？」
line = "「ん……<emoji=heart04>　仕方ないですね……<emoji=heart04>　わかりました。その代わり、変にからかったりしちゃダメですからね……？」"

[[dialogue]]
speaker = "unk"
# ナミエルは体をくるりと俺の方に向けて座り直し、正面から目を合わせながら、じ～っと見つめてくる。
line = "ナミエルは体をくるりと俺の方に向けて座り直し、正面から目を合わせながら、じ～っと見つめてくる。"

[[dialogue]]
speaker = "ナミエル"
# 「じゃあ――<b>旦那様</b>……<emoji=heart04>　久しぶりに、キスをして欲しいです……<emoji=heart04>」
line = "「じゃあ――<b>旦那様</b>……<emoji=heart04>　久しぶりに、キスをして欲しいです……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# お願いを聞いてくれたナミエルを抱き締めて、俺は彼女と唇をそっと重ねる。
line = "お願いを聞いてくれたナミエルを抱き締めて、俺は彼女と唇をそっと重ねる。"

[[dialogue]]
speaker = "ナミエル"
# 「あっ……旦那様<emoji=heart04>　んっ……ちゅっ……<emoji=heart04>」
line = "「あっ……旦那様<emoji=heart04>　んっ……ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ナミエル"
# 「ちゅっ……<emoji=heart04>　んむっ……ちゅっ……<emoji=heart04>　はあぁ……<emoji=heart04>」
line = "「ちゅっ……<emoji=heart04>　んむっ……ちゅっ……<emoji=heart04>　はあぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 能動的にスキンシップする日を作らないか？
line = "能動的にスキンシップする日を作らないか？"

[[dialogue]]
speaker = "unk"
# 俺、考えたんだけど……今度から
line = "俺、考えたんだけど……今度から"

[[dialogue]]
speaker = "ナミエル"
# 「能動的に、ですか……？　それはどうして……？」
line = "「能動的に、ですか……？　それはどうして……？」"

[[dialogue]]
speaker = "ナミエル"
# 「――スキンシップが不足すると、今回みたいに欲求不満になっちゃうから……？」
line = "「――スキンシップが不足すると、今回みたいに欲求不満になっちゃうから……？」"

[[dialogue]]
speaker = "ナミエル"
# 「もう……旦那様ったら、仕方ないですね……<emoji=heart04>　でしたら、未来の奥さんとして、スキンシップ不足にならないように、ちゃんと管理してあげます<emoji=heart04>」
line = "「もう……旦那様ったら、仕方ないですね……<emoji=heart04>　でしたら、未来の奥さんとして、スキンシップ不足にならないように、ちゃんと管理してあげます<emoji=heart04>」"

[[dialogue]]
speaker = "ナミエル"
# 「――頻度はどのくらいなら許してくれるか？　そうですね……週３日、とかでしょうか……？」
line = "「――頻度はどのくらいなら許してくれるか？　そうですね……週３日、とかでしょうか……？」"

[[dialogue]]
speaker = "unk"
# 思ってたより多くて嬉しい
line = "思ってたより多くて嬉しい"

[[dialogue]]
speaker = "ナミエル"
# 「あっ、でも、その時だけすればいいってわけじゃなくて……私が『したい』と考えてる時は、ちゃんと察してくれないとダメですよ？」
line = "「あっ、でも、その時だけすればいいってわけじゃなくて……私が『したい』と考えてる時は、ちゃんと察してくれないとダメですよ？」"

[[dialogue]]
speaker = "ナミエル"
# 「――大変そう？　ふふっ……ダメです。それが、旦那様としての甲斐性というものですよ……<emoji=heart04>」
line = "「――大変そう？　ふふっ……ダメです。それが、旦那様としての甲斐性というものですよ……<emoji=heart04>」"

[[dialogue]]
speaker = "ナミエル"
# 「んっ……<emoji=heart04>　ちゅっ……<emoji=heart04>」
line = "「んっ……<emoji=heart04>　ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# それからも、俺たちは久しぶりのスキンシップを繰り返し堪能し続けるのだった。
line = "それからも、俺たちは久しぶりのスキンシップを繰り返し堪能し続けるのだった。"

[[dialogue]]
speaker = "unk"
# ――翌朝。
line = "――翌朝。"

[[dialogue]]
speaker = "ナミエル"
# 「……どうやら、クリスマスフォームの力は収まったみたいですね」
line = "「……どうやら、クリスマスフォームの力は収まったみたいですね」"

[[dialogue]]
speaker = "unk"
# 目覚めた時には、ナミエルの変身は解除され、制服姿に戻っていた。
line = "目覚めた時には、ナミエルの変身は解除され、制服姿に戻っていた。"

[[dialogue]]
speaker = "unk"
# 本当だったんだな
line = "本当だったんだな"

[[dialogue]]
speaker = "unk"
# ナミエルが、抱き枕がないと寝られないって
line = "ナミエルが、抱き枕がないと寝られないって"

[[dialogue]]
speaker = "ナミエル"
# 「～～～っ……！　それは、仕方がないじゃないですかっ。そういう人も中にはいるんです……！」
line = "「～～～っ……！　それは、仕方がないじゃないですかっ。そういう人も中にはいるんです……！」"

[[dialogue]]
speaker = "ナミエル"
# 「寝る時に抱き着かれて、幸せな気分だった……？　も、もうっ、思い出してニヤニヤしないで下さいっ。いやらしいですよ……！」
line = "「寝る時に抱き着かれて、幸せな気分だった……？　も、もうっ、思い出してニヤニヤしないで下さいっ。いやらしいですよ……！」"

[[dialogue]]
speaker = "ナミエル"
# 「こ、このことは、他の人に言いふらしたりしちゃ、ダメですからね……？」
line = "「こ、このことは、他の人に言いふらしたりしちゃ、ダメですからね……？」"

[[dialogue]]
speaker = "unk"
# 俺はナミエルの可愛い一面をまた知れて、嬉しい気持ちになりつつ、彼女の頭を優しく撫でるのだった。
line = "俺はナミエルの可愛い一面をまた知れて、嬉しい気持ちになりつつ、彼女の頭を優しく撫でるのだった。"
