[[dialogue]]
speaker = "unk"
# 第２話,リップルの師匠,P
line = "第２話,リップルの師匠,P"

[[dialogue]]
speaker = "unk"
# 学園でリゾート結界の運営が開始されると、たちまち人気スポットとなって、リップルの海の家は今日も大忙しだった――
line = "学園でリゾート結界の運営が開始されると、たちまち人気スポットとなって、リップルの海の家は今日も大忙しだった――"

[[dialogue]]
speaker = "マトイ"
# 「ふぅ……お昼のピークが終わって、やっと一息つけるね～」
line = "「ふぅ……お昼のピークが終わって、やっと一息つけるね～」"

[[dialogue]]
speaker = "リップル"
# 「マトイ、カイチョー。海の家の接客、手伝ってくれてアリガトございます♪　手が足りなくてピンチだったので、助かりま～す！」
line = "「マトイ、カイチョー。海の家の接客、手伝ってくれてアリガトございます♪　手が足りなくてピンチだったので、助かりま～す！」"

[[dialogue]]
speaker = "unk"
# 接客のバイトは慣れてるから、お安い御用だ
line = "接客のバイトは慣れてるから、お安い御用だ"

[[dialogue]]
speaker = "リップル"
# 「おかげさまで大繁盛で～す♪　カイチョーの接客する姿、まるでシショーみたいでカッコイイです！」
line = "「おかげさまで大繁盛で～す♪　カイチョーの接客する姿、まるでシショーみたいでカッコイイです！」"

[[dialogue]]
speaker = "リップル"
# 「――と、また新しいお客さんがキタみたいです！　ラッシャーセー♪　海の家へヨウコソで～す！　……って」
line = "「――と、また新しいお客さんがキタみたいです！　ラッシャーセー♪　海の家へヨウコソで～す！　……って」"

[[dialogue]]
speaker = "シショー"
# 「やあ、こんにちは、渚の天使さん。素敵な笑顔でのお出迎え、ありがとう。大人２人でお願いできるかな？」
line = "「やあ、こんにちは、渚の天使さん。素敵な笑顔でのお出迎え、ありがとう。大人２人でお願いできるかな？」"

[[dialogue]]
speaker = "オクサン"
# 「ふふっ、笑顔を見ているだけで、こっちも元気になっちゃうわね。お礼にハグしてもいいかしら？」
line = "「ふふっ、笑顔を見ているだけで、こっちも元気になっちゃうわね。お礼にハグしてもいいかしら？」"

[[dialogue]]
speaker = "リップル"
# 「ワオ！！　シショー！　オクサン！　来てくれたんデスね！」
line = "「ワオ！！　シショー！　オクサン！　来てくれたんデスね！」"

[[dialogue]]
speaker = "シショー"
# 「久しぶりだね、リップル。元気そうで安心したよ」
line = "「久しぶりだね、リップル。元気そうで安心したよ」"

[[dialogue]]
speaker = "オクサン"
# 「ずっと会いたかったわ。私達の可愛い天使さん」
line = "「ずっと会いたかったわ。私達の可愛い天使さん」"

[[dialogue]]
speaker = "リップル"
# 「ワタシも会いたかったです、シショー、オクサン！　久しぶりのハグで～す♪」
line = "「ワタシも会いたかったです、シショー、オクサン！　久しぶりのハグで～す♪」"

[[dialogue]]
speaker = "リップル"
# 「カイチョーとマトイにもショーカイしますね！　合宿の時も話しましたが、ワタシの恩人であるシショーと、そのオクサンです！」
line = "「カイチョーとマトイにもショーカイしますね！　合宿の時も話しましたが、ワタシの恩人であるシショーと、そのオクサンです！」"

[[dialogue]]
speaker = "マトイ"
# 「き、金髪碧眼の凄い美男美女……！　確か、お２人で海の家を経営されてるって話だったよね？」
line = "「き、金髪碧眼の凄い美男美女……！　確か、お２人で海の家を経営されてるって話だったよね？」"

[[dialogue]]
speaker = "リップル"
# 「ハイ！　ワタシは合宿でカイチョー達と出会うまで、シショー達のトコロでお世話になってたんです」
line = "「ハイ！　ワタシは合宿でカイチョー達と出会うまで、シショー達のトコロでお世話になってたんです」"

[[dialogue]]
speaker = "リップル"
# 「シショーとオクサンからはいっぱい優しくして貰って、夏の海について色々なことを学びました」
line = "「シショーとオクサンからはいっぱい優しくして貰って、夏の海について色々なことを学びました」"

[[dialogue]]
speaker = "リップル"
# 「おかげでワタシは、ハッピーな気持ちを知って、笑顔を取り戻すことがデキたんです。感謝してもシキれません！」
line = "「おかげでワタシは、ハッピーな気持ちを知って、笑顔を取り戻すことがデキたんです。感謝してもシキれません！」"

[[dialogue]]
speaker = "シショー"
# 「初めまして。新星学園の会長さんと、書記のマトイさん。お２人や星徒会の皆さんのことは、リップルからよく聞いているよ」
line = "「初めまして。新星学園の会長さんと、書記のマトイさん。お２人や星徒会の皆さんのことは、リップルからよく聞いているよ」"

[[dialogue]]
speaker = "オクサン"
# 「ふふっ、リップルちゃんとはＤＩＳＣで連絡を取り合っていてね。夏合宿でのことや、学園のことをそれはもう楽しそうに話してくれるのよ」
line = "「ふふっ、リップルちゃんとはＤＩＳＣで連絡を取り合っていてね。夏合宿でのことや、学園のことをそれはもう楽しそうに話してくれるのよ」"

[[dialogue]]
speaker = "unk"
# こちらこそ、リップルには助けられています
line = "こちらこそ、リップルには助けられています"

[[dialogue]]
speaker = "マトイ"
# 「戦闘でも強くて頼りになりますし、明るい性格で、転入したばかりなのに人気者なんですよ。それに、見ての通りリゾート結界も生徒達から凄く人気があるんです」
line = "「戦闘でも強くて頼りになりますし、明るい性格で、転入したばかりなのに人気者なんですよ。それに、見ての通りリゾート結界も生徒達から凄く人気があるんです」"

[[dialogue]]
speaker = "リップル"
# 「エヘヘ♪　何だか照れちゃいま～す」
line = "「エヘヘ♪　何だか照れちゃいま～す」"

[[dialogue]]
speaker = "シショー"
# 「このリゾート結界は本当に良い場所だと思うよ。少し見ただけでも分かる。リップルが皆にハッピーになって貰いたくて、ここを作ったんだってことが」
line = "「このリゾート結界は本当に良い場所だと思うよ。少し見ただけでも分かる。リップルが皆にハッピーになって貰いたくて、ここを作ったんだってことが」"

[[dialogue]]
speaker = "リップル"
# 「シショー、アリガトございます！　ワタシだけの力じゃなくて、皆からアイデアを貰ったから、作り上げることがデキたんです！」
line = "「シショー、アリガトございます！　ワタシだけの力じゃなくて、皆からアイデアを貰ったから、作り上げることがデキたんです！」"

[[dialogue]]
speaker = "オクサン"
# 「リップルちゃんは、良いお友達と出会えたのね」
line = "「リップルちゃんは、良いお友達と出会えたのね」"

[[dialogue]]
speaker = "シショー"
# 「ああ。前よりいい顔になったな、リップル」
line = "「ああ。前よりいい顔になったな、リップル」"

[[dialogue]]
speaker = "リップル"
# 「ハイ♪　ワタシ、カイチョー達と出会って、この学園に来て、今とてもハッピーです！」
line = "「ハイ♪　ワタシ、カイチョー達と出会って、この学園に来て、今とてもハッピーです！」"

[[dialogue]]
speaker = "リップル"
# 「――あっ、また別のお客さんがキタみたいです。ワタシ、ちょっと接客に行ってきますね！　ラッシャーセー♪」
line = "「――あっ、また別のお客さんがキタみたいです。ワタシ、ちょっと接客に行ってきますね！　ラッシャーセー♪」"

[[dialogue]]
speaker = "マトイ"
# 「いや、せっかくお世話になった方が会いに来てくれたんだから、ここはヘルプの私達が！　……って、止める間もなく行っちゃった」
line = "「いや、せっかくお世話になった方が会いに来てくれたんだから、ここはヘルプの私達が！　……って、止める間もなく行っちゃった」"

[[dialogue]]
speaker = "シショー"
# 「ははっ、あの子は海の家でお客さんの笑顔を見るのが大好きなんだよ。私達と暮らしている時もそうだった。――さて、会長さん、マトイさん」
line = "「ははっ、あの子は海の家でお客さんの笑顔を見るのが大好きなんだよ。私達と暮らしている時もそうだった。――さて、会長さん、マトイさん」"

[[dialogue]]
speaker = "シショー"
# 「リップルに良くしてくれて、本当にありがとう。改めて、お礼を言わせて貰うよ」
line = "「リップルに良くしてくれて、本当にありがとう。改めて、お礼を言わせて貰うよ」"

[[dialogue]]
speaker = "unk"
# いやいや！　大したことはしてないです
line = "いやいや！　大したことはしてないです"

[[dialogue]]
speaker = "オクサン"
# 「いいえ、リップルちゃんを仲間として、この学園に迎えてくれたでしょう？　それが凄く嬉しかったって、あの子言ってたの」
line = "「いいえ、リップルちゃんを仲間として、この学園に迎えてくれたでしょう？　それが凄く嬉しかったって、あの子言ってたの」"

[[dialogue]]
speaker = "シショー"
# 「……私達夫婦には残念ながら子供がいなくてね。母親を亡くしてそう経っていないあの子には言えないが、実の娘のように思っているんだ」
line = "「……私達夫婦には残念ながら子供がいなくてね。母親を亡くしてそう経っていないあの子には言えないが、実の娘のように思っているんだ」"

[[dialogue]]
speaker = "オクサン"
# 「だから、あの子が今日、心から楽しそうな笑顔を浮かべているのを見て、凄く安心したし、私達も嬉しかったの」
line = "「だから、あの子が今日、心から楽しそうな笑顔を浮かべているのを見て、凄く安心したし、私達も嬉しかったの」"

[[dialogue]]
speaker = "シショー"
# 「どうか、これからも仲良くしてあげて欲しい。私達の代わりに」
line = "「どうか、これからも仲良くしてあげて欲しい。私達の代わりに」"

[[dialogue]]
speaker = "マトイ"
# 「……師匠さん、奥さん。自分達の代わりにだなんて、寂しいこと言わないで下さい。リップルはお２人のこと、家族みたいに思ってるって前に言ってましたよ」
line = "「……師匠さん、奥さん。自分達の代わりにだなんて、寂しいこと言わないで下さい。リップルはお２人のこと、家族みたいに思ってるって前に言ってましたよ」"

[[dialogue]]
speaker = "unk"
# 今だってそうですよ。ほら、後ろ――
line = "今だってそうですよ。ほら、後ろ――"

[[dialogue]]
speaker = "リップル"
# 「シショー……オクサン……」
line = "「シショー……オクサン……」"

[[dialogue]]
speaker = "シショー"
# 「！　リップル、いつの間に……接客を終えて、戻って来てたのか……！」
line = "「！　リップル、いつの間に……接客を終えて、戻って来てたのか……！」"

[[dialogue]]
speaker = "リップル"
# 「わ、ワタシ……衣食住を不自由ナク面倒みて貰って……それ以上は迷惑カナと思って、ずっと言えませんでしたが――」
line = "「わ、ワタシ……衣食住を不自由ナク面倒みて貰って……それ以上は迷惑カナと思って、ずっと言えませんでしたが――」"

[[dialogue]]
speaker = "リップル"
# 「本当は……シショー達のこと、もう１人のお父さんや、お母さんみたいに、オモってます……！」
line = "「本当は……シショー達のこと、もう１人のお父さんや、お母さんみたいに、オモってます……！」"

[[dialogue]]
speaker = "リップル"
# 「だから、これからも……家族みたいにオモっててイイですか……？」
line = "「だから、これからも……家族みたいにオモっててイイですか……？」"

[[dialogue]]
speaker = "オクサン"
# 「リップルちゃん……！　ええ、ええ……もちろんよ！　あなたは私達のところに来てくれた、可愛くて愛おしい天使だもの……！」
line = "「リップルちゃん……！　ええ、ええ……もちろんよ！　あなたは私達のところに来てくれた、可愛くて愛おしい天使だもの……！」"

[[dialogue]]
speaker = "シショー"
# 「ああ……リップル……！　すまない……私達も、ずっと言えなくて……いつでも家に帰って来い……遠慮なんてしなくていいから……！」
line = "「ああ……リップル……！　すまない……私達も、ずっと言えなくて……いつでも家に帰って来い……遠慮なんてしなくていいから……！」"

[[dialogue]]
speaker = "リップル"
# 「ハイ、今度近いうちに帰ります。必ず、２人に会いに行きます……！」
line = "「ハイ、今度近いうちに帰ります。必ず、２人に会いに行きます……！」"

[[dialogue]]
speaker = "マトイ"
# 「どうしよう……もらい泣きしそう。凄く、いい家族だね……」
line = "「どうしよう……もらい泣きしそう。凄く、いい家族だね……」"

[[dialogue]]
speaker = "unk"
# よかったな、リップル
line = "よかったな、リップル"

[[dialogue]]
speaker = "リップル"
# 「エヘヘ♪　ワタシもＢＩＧハッピーで、ちょっと泣いてしまいソウです……♪」
line = "「エヘヘ♪　ワタシもＢＩＧハッピーで、ちょっと泣いてしまいソウです……♪」"

[[dialogue]]
speaker = "unk"
# リップルはそう言って、心から嬉しそうな笑顔を浮かべるのだった――
line = "リップルはそう言って、心から嬉しそうな笑顔を浮かべるのだった――"
