[[dialogue]]
speaker = "unk"
# 第２話,突撃マムハート,P
line = "第２話,突撃マムハート,P"

[[dialogue]]
speaker = "unk"
# バトルフェスタ・ペンタグラムで実装された仮想結界システム――それを使って仮想空間に再現された魔界。
line = "バトルフェスタ・ペンタグラムで実装された仮想結界システム――それを使って仮想空間に再現された魔界。"

[[dialogue]]
speaker = "unk"
# 俺はそこで大出力のノヴァフォームに変身したマムと、全力の戦闘訓練を行っていた。
line = "俺はそこで大出力のノヴァフォームに変身したマムと、全力の戦闘訓練を行っていた。"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「会長、魔王の力が上手く引き出せないからって甘えは許さないわよ。星騎士として、星力だけで戦い抜く気概を見せなさい！」
line = "「会長、魔王の力が上手く引き出せないからって甘えは許さないわよ。星騎士として、星力だけで戦い抜く気概を見せなさい！」"

[[dialogue]]
speaker = "unk"
# イエス・マム！
line = "イエス・マム！"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「行くわよ――引力球！」
line = "「行くわよ――引力球！」"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （ノヴァフォームになって更に進化した私の『引力操作』は、星術や相手の能力すらも引き寄せる。そして――）
line = "（ノヴァフォームになって更に進化した私の『引力操作』は、星術や相手の能力すらも引き寄せる。そして――）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「反転！　ブラックホールリフレクション！」
line = "「反転！　ブラックホールリフレクション！」"

[[dialogue]]
speaker = "unk"
# 俺の全力で放った攻撃がそのまま跳ね返され、吹き飛ばされる。
line = "俺の全力で放った攻撃がそのまま跳ね返され、吹き飛ばされる。"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「竜の<ruby=りょりょく>膂力</ruby>、<ruby=さば>捌</ruby>いてみせなさい！」
line = "「竜の<ruby>膂力<rt>りょりょく</rt></ruby>、<ruby>捌<rt>さば</rt></ruby>いてみせなさい！」"

[[dialogue]]
speaker = "unk"
# そのまま追撃してきたマムの拳を避けるが、拳圧で地面が大きく陥没し、そこに大きなクレーターを作り上げる。
line = "そのまま追撃してきたマムの拳を避けるが、拳圧で地面が大きく陥没し、そこに大きなクレーターを作り上げる。"

[[dialogue]]
speaker = "unk"
# 普段は愛らしい小さな体躯だが、ノヴァフォームに変身した際の膂力は竜化した時と変わらぬものになるという。
line = "普段は愛らしい小さな体躯だが、ノヴァフォームに変身した際の膂力は竜化した時と変わらぬものになるという。"

[[dialogue]]
speaker = "unk"
# まさに、今のマムは小さく凝縮された竜そのもの。
line = "まさに、今のマムは小さく凝縮された竜そのもの。"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （そう、私は竜の全力を出して戦っている。だけど――）
line = "（そう、私は竜の全力を出して戦っている。だけど――）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （会長は何度攻撃を受けても、必ず立ち上がって来る）
line = "（会長は何度攻撃を受けても、必ず立ち上がって来る）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （幼い頃から何度もリクリエと対峙してきた経験による『死や痛みに対する精神耐性』。それと『危機的状況から立ち上がる度に星力が上昇する』という固有の能力）
line = "（幼い頃から何度もリクリエと対峙してきた経験による『死や痛みに対する精神耐性』。それと『危機的状況から立ち上がる度に星力が上昇する』という固有の能力）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （その２つから生み出される『不死身のごとき<ruby=タフさ>耐久性</ruby>』こそが、会長の星騎士として抜きん出た才能）
line = "（その２つから生み出される『不死身のごとき<ruby>耐久性<rt>タフさ</rt></ruby>』こそが、会長の星騎士として抜きん出た才能）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （学園に来てからリクリエの最前線で戦い続けて来たことで、今や魔王の力を抜きにしても、竜の全力でも簡単には倒し切れない）
line = "（学園に来てからリクリエの最前線で戦い続けて来たことで、今や魔王の力を抜きにしても、竜の全力でも簡単には倒し切れない）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （おまけに、どこぞのツインドリルに似た不屈の努力家で、恋人になってからも腑抜けることなく、会長として日々勤勉に己を高め続けている）
line = "（おまけに、どこぞのツインドリルに似た不屈の努力家で、恋人になってからも腑抜けることなく、会長として日々勤勉に己を高め続けている）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （全く……おかげで、たまにはご褒美のスキンシップくらい許してあげないと、私の方が恋人としてダメみたいになるじゃない）
line = "（全く……おかげで、たまにはご褒美のスキンシップくらい許してあげないと、私の方が恋人としてダメみたいになるじゃない）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （それで、いざスキンシップが始まると、生意気に強いオスの一面を出して来たりするし……）
line = "（それで、いざスキンシップが始まると、生意気に強いオスの一面を出して来たりするし……）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （私が力の強さを認めちゃってる異性だから、触れ合うと竜の本能で、仕方なくドキドキしちゃって……）
line = "（私が力の強さを認めちゃってる異性だから、触れ合うと竜の本能で、仕方なくドキドキしちゃって……）"

[[dialogue]]
speaker = "unk"
# マム、ちょっと失礼します
line = "マム、ちょっと失礼します"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「えっ！？」
line = "「えっ！？」"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （余計なことを考えている隙を突かれたとはいえ、この私が反応できない程の速さで肉薄された！？）
line = "（余計なことを考えている隙を突かれたとはいえ、この私が反応できない程の速さで肉薄された！？）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （完全に１本取られた……！　竜たるこの私が！？）
line = "（完全に１本取られた……！　竜たるこの私が！？）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「って、会長？　おでこに手を当てて、一体何を……！？」
line = "「って、会長？　おでこに手を当てて、一体何を……！？」"

[[dialogue]]
speaker = "unk"
# どこか様子が変だなと思って……
line = "どこか様子が変だなと思って……"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「は！？　――この私が、集中できてなくて、顔が赤くなっているように見えた！？」
line = "「は！？　――この私が、集中できてなくて、顔が赤くなっているように見えた！？」"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「～～～っ！」
line = "「～～～っ！」"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「何を言っているのかしら！？　竜たるこの私が、体調が悪くなるなんてこと早々あるわけないでしょう！？」
line = "「何を言っているのかしら！？　竜たるこの私が、体調が悪くなるなんてこと早々あるわけないでしょう！？」"

[[dialogue]]
speaker = "unk"
# 問題ないなら、別にいいんだけど――
line = "問題ないなら、別にいいんだけど――"

[[dialogue]]
speaker = "unk"
# 本当に何かある時は、素直に言って欲しい。俺はマムの恋人なのだから、と伝えた。
line = "本当に何かある時は、素直に言って欲しい。俺はマムの恋人なのだから、と伝えた。"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「っ……恋人だからこそ、素直に言えないこともあるのよ」
line = "「っ……恋人だからこそ、素直に言えないこともあるのよ」"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「ばか……」
line = "「ばか……」"

[[dialogue]]
speaker = "unk"
# 顔を赤くして呟くマムに、俺は思わずドキッとしてしまう。
line = "顔を赤くして呟くマムに、俺は思わずドキッとしてしまう。"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （言えるわけないじゃない……！）
line = "（言えるわけないじゃない……！）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# （この私が、訓練中に貴方を異性として意識して、ドキドキしてるなんて……）
line = "（この私が、訓練中に貴方を異性として意識して、ドキドキしてるなんて……）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「っ……生意気よ！　どれだけ貴方が強くなったとしても、畏怖をもって跪かせてあげるんだから！」
line = "「っ……生意気よ！　どれだけ貴方が強くなったとしても、畏怖をもって跪かせてあげるんだから！」"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「引力球で百叩きにしてあげるから、そこに直りなさい！」
line = "「引力球で百叩きにしてあげるから、そこに直りなさい！」"

[[dialogue]]
speaker = "unk"
# あれ！？　なんか怒ってます！？
line = "あれ！？　なんか怒ってます！？"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「貴方のせいよっ！　ノヴァメテオインパクトォーーーッ！！！」
line = "「貴方のせいよっ！　ノヴァメテオインパクトォーーーッ！！！」"

[[dialogue]]
speaker = "unk"
# ちょっ、待っ……アッーーーーーー！！？
line = "ちょっ、待っ……アッーーーーーー！！？"

[[dialogue]]
speaker = "unk"
# 突然始まったアルマゲドンのごとき指導を、俺はそこから受ける羽目になるのだった――
line = "突然始まったアルマゲドンのごとき指導を、俺はそこから受ける羽目になるのだった――"
