[[dialogue]]
speaker = "unk"
# 第１話,アニマの告白,P
line = "第１話,アニマの告白,P"

[[dialogue]]
speaker = "unk"
# 先日、アニマ先輩が分裂薬で２人に増える出来事があった。
line = "先日、アニマ先輩が分裂薬で２人に増える出来事があった。"

[[dialogue]]
speaker = "unk"
# そして、そのことがきっかけで、アニマ先輩が俺を異性としてどう思っているのかについて、本心を聞かされることとなった。
line = "そして、そのことがきっかけで、アニマ先輩が俺を異性としてどう思っているのかについて、本心を聞かされることとなった。"

[[dialogue]]
speaker = "アニマ"
# 「アニマも、好きダ。キミのことが――大好きダ……！」
line = "「アニマも、好きダ。キミのことが――大好きダ……！」"

[[dialogue]]
speaker = "unk"
# 俺も、アニマ先輩のことが好きだと伝え、晴れて恋人関係になった――
line = "俺も、アニマ先輩のことが好きだと伝え、晴れて恋人関係になった――"

[[dialogue]]
speaker = "unk"
# はずだったのだが……。
line = "はずだったのだが……。"

[[dialogue]]
speaker = "アニマ"
# 「……会長、わざわざ呼び出してすまナイ。先日言ったことについてなのだが……」
line = "「……会長、わざわざ呼び出してすまナイ。先日言ったことについてなのだが……」"

[[dialogue]]
speaker = "アニマ"
# 「その……忘れて欲しイ」
line = "「その……忘れて欲しイ」"

[[dialogue]]
speaker = "unk"
# そんな……どうしてですか？
line = "そんな……どうしてですか？"

[[dialogue]]
speaker = "アニマ"
# 「キミのことが好きと言ったのは嘘ではナイ。だが……アニマは、その気持ちを口にするつもりはなかったんダ」
line = "「キミのことが好きと言ったのは嘘ではナイ。だが……アニマは、その気持ちを口にするつもりはなかったんダ」"

[[dialogue]]
speaker = "アニマ"
# 「何故なら……アニマは恋人を作る資格がナイからダ」
line = "「何故なら……アニマは恋人を作る資格がナイからダ」"

[[dialogue]]
speaker = "アニマ"
# 「――アニマは、錬金術師としての夢がアル。それは……」
line = "「――アニマは、錬金術師としての夢がアル。それは……」"

[[dialogue]]
speaker = "アニマ"
# 「『魂の根源』を明らかにすることダ」
line = "「『魂の根源』を明らかにすることダ」"

[[dialogue]]
speaker = "アニマ"
# 「――簡単に言うと、魂とはどのように作られているのか、その成分を明らかにし、錬金術師として作り出せるようになるコト」
line = "「――簡単に言うと、魂とはどのように作られているのか、その成分を明らかにし、錬金術師として作り出せるようになるコト」"

[[dialogue]]
speaker = "アニマ"
# 「それはつまり、物理的な創造から、概念的な創造へとシフトする、錬金術の新たな扉を開くことでもアル」
line = "「それはつまり、物理的な創造から、概念的な創造へとシフトする、錬金術の新たな扉を開くことでもアル」"

[[dialogue]]
speaker = "アニマ"
# 「そこへ辿り着くのは、決して簡単なことではナイ。最大の近道は、百聞は一見に如かずという言葉があるように、自身が『魂の感覚』を体験するコト」
line = "「そこへ辿り着くのは、決して簡単なことではナイ。最大の近道は、百聞は一見に如かずという言葉があるように、自身が『魂の感覚』を体験するコト」"

[[dialogue]]
speaker = "アニマ"
# 「故にアニマは、最終的には肉体を捨て、魂だけの存在へとなろうと考えているんダ」
line = "「故にアニマは、最終的には肉体を捨て、魂だけの存在へとなろうと考えているんダ」"

[[dialogue]]
speaker = "アニマ"
# 「つまりは、アニマはキミと恋人になったとしても、いずれ物理的に触れ合えなくナル。それは……キミにとって、決して望ましいことではないダロウ？」
line = "「つまりは、アニマはキミと恋人になったとしても、いずれ物理的に触れ合えなくナル。それは……キミにとって、決して望ましいことではないダロウ？」"

[[dialogue]]
speaker = "アニマ"
# 「だから、人生のパートナーとして、アニマは不適合なんダ。アニマはキミを……幸せにすることはできナイ」
line = "「だから、人生のパートナーとして、アニマは不適合なんダ。アニマはキミを……幸せにすることはできナイ」"

[[dialogue]]
speaker = "アニマ"
# 「好意があっても、アニマはキミの恋人になるべきではないんダ」
line = "「好意があっても、アニマはキミの恋人になるべきではないんダ」"

[[dialogue]]
speaker = "アニマ"
# 「アニマは、夢を捨てることはできナイ。その上で、キミのことが好きだと思うからこそ――」
line = "「アニマは、夢を捨てることはできナイ。その上で、キミのことが好きだと思うからこそ――」"

[[dialogue]]
speaker = "アニマ"
# 「キミには、ちゃんと幸せになって欲しいんダ」
line = "「キミには、ちゃんと幸せになって欲しいんダ」"

[[dialogue]]
speaker = "アニマ"
# 「ほら、キミの周りには、アニマよりも女の子らしい女の子が沢山いるダロウ？　だから……」
line = "「ほら、キミの周りには、アニマよりも女の子らしい女の子が沢山いるダロウ？　だから……」"

[[dialogue]]
speaker = "unk"
# ……先輩の言いたいことはわかりました
line = "……先輩の言いたいことはわかりました"

[[dialogue]]
speaker = "アニマ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# だけど――俺は。
line = "だけど――俺は。"

[[dialogue]]
speaker = "unk"
# 俺が好きなのは、アニマ先輩です！
line = "俺が好きなのは、アニマ先輩です！"

[[dialogue]]
speaker = "アニマ"
# 「っ……！」
line = "「っ……！」"

[[dialogue]]
speaker = "アニマ"
# 「キミがそう言ってくれるのは嬉しイ。だが、アニマは――」
line = "「キミがそう言ってくれるのは嬉しイ。だが、アニマは――」"

[[dialogue]]
speaker = "unk"
# ――たとえ将来……アニマ先輩が夢を叶える為に肉体を捨てることになるのだとしても。
line = "――たとえ将来……アニマ先輩が夢を叶える為に肉体を捨てることになるのだとしても。"

[[dialogue]]
speaker = "unk"
# 俺は、本気で研究に打ち込むアニマ先輩を尊敬しているし、応援したいと思っている。
line = "俺は、本気で研究に打ち込むアニマ先輩を尊敬しているし、応援したいと思っている。"

[[dialogue]]
speaker = "unk"
# だって――俺も本気でアニマ先輩のことが好きだから。
line = "だって――俺も本気でアニマ先輩のことが好きだから。"

[[dialogue]]
speaker = "unk"
# だから、アニマ先輩が嫌じゃなければ、どうか夢を叶えるその瞬間まで、そばに居させて下さい。
line = "だから、アニマ先輩が嫌じゃなければ、どうか夢を叶えるその瞬間まで、そばに居させて下さい。"

[[dialogue]]
speaker = "unk"
# 俺はそう伝えた。
line = "俺はそう伝えた。"

[[dialogue]]
speaker = "アニマ"
# 「か、会長……」
line = "「か、会長……」"

[[dialogue]]
speaker = "アニマ"
# 「せっかく断る覚悟を決めて、アニマは言いにキタというのに……」
line = "「せっかく断る覚悟を決めて、アニマは言いにキタというのに……」"

[[dialogue]]
speaker = "アニマ"
# 「そんな真剣に言われたら……また迷ってしまうじゃナイか。将来のことを考えたら、よくないとわかってイルのに……」
line = "「そんな真剣に言われたら……また迷ってしまうじゃナイか。将来のことを考えたら、よくないとわかってイルのに……」"

[[dialogue]]
speaker = "unk"
# 実験してみませんか？
line = "実験してみませんか？"

[[dialogue]]
speaker = "アニマ"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "unk"
# 恋愛の実験です
line = "恋愛の実験です"

[[dialogue]]
speaker = "アニマ"
# 「実験……？」
line = "「実験……？」"

[[dialogue]]
speaker = "unk"
# 俺は頷く。
line = "俺は頷く。"

[[dialogue]]
speaker = "unk"
# いつもアニマ先輩が作った薬を俺が飲んで試しているように、その効果の度合いや副作用は、実験してみないと分からない。
line = "いつもアニマ先輩が作った薬を俺が飲んで試しているように、その効果の度合いや副作用は、実験してみないと分からない。"

[[dialogue]]
speaker = "unk"
# だから、俺たちの関係がどうなるかも、実際に付き合ってみないとわからないはずだと説明する。
line = "だから、俺たちの関係がどうなるかも、実際に付き合ってみないとわからないはずだと説明する。"

[[dialogue]]
speaker = "アニマ"
# 「……ああ、ソウか。アニマは……どうやら臆病になってしまっていたみたいダ……」
line = "「……ああ、ソウか。アニマは……どうやら臆病になってしまっていたみたいダ……」"

[[dialogue]]
speaker = "アニマ"
# 「キミの言う通りだナ。どれだけ予測を立てても、実際にやってみなければ、結果がどうなるかはわからない。実験とはそういうものダ」
line = "「キミの言う通りだナ。どれだけ予測を立てても、実際にやってみなければ、結果がどうなるかはわからない。実験とはそういうものダ」"

[[dialogue]]
speaker = "アニマ"
# 「にも関わらず、アニマは恋愛を試してみることすら、及び腰になってしまってイタ」
line = "「にも関わらず、アニマは恋愛を試してみることすら、及び腰になってしまってイタ」"

[[dialogue]]
speaker = "アニマ"
# 「アニマは……キミとの恋愛に失敗して、嫌われてしまうことが怖かったんダ……」
line = "「アニマは……キミとの恋愛に失敗して、嫌われてしまうことが怖かったんダ……」"

[[dialogue]]
speaker = "unk"
# 俺は簡単に先輩を手離したりしませんよ
line = "俺は簡単に先輩を手離したりしませんよ"

[[dialogue]]
speaker = "unk"
# 失敗したとしても、
line = "失敗したとしても、"

[[dialogue]]
speaker = "アニマ"
# 「――それくらい、本気で好きだから……？」
line = "「――それくらい、本気で好きだから……？」"

[[dialogue]]
speaker = "アニマ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "アニマ"
# 「……キミは、アニマの実験にいつも本気で付き合ってくれタ」
line = "「……キミは、アニマの実験にいつも本気で付き合ってくれタ」"

[[dialogue]]
speaker = "アニマ"
# 「なのに、アニマが今更キミの気持ちを疑うのは、失礼というものだナ……」
line = "「なのに、アニマが今更キミの気持ちを疑うのは、失礼というものだナ……」"

[[dialogue]]
speaker = "アニマ"
# 「――アニマは、本当は……キミと恋人になってみたいと思ってイル」
line = "「――アニマは、本当は……キミと恋人になってみたいと思ってイル」"

[[dialogue]]
speaker = "アニマ"
# 「恋愛に興味がアル。アニマが体験したことのない関係性を、試してみたイ」
line = "「恋愛に興味がアル。アニマが体験したことのない関係性を、試してみたイ」"

[[dialogue]]
speaker = "アニマ"
# 「……さっきも言った通り、キミとの将来がどうなるかは分からなイ。それでも、実験に付き合ってくれるというなら――」
line = "「……さっきも言った通り、キミとの将来がどうなるかは分からなイ。それでも、実験に付き合ってくれるというなら――」"

[[dialogue]]
speaker = "アニマ"
# 「コホン……」
line = "「コホン……」"

[[dialogue]]
speaker = "unk"
# 先輩は１度咳ばらいをすると──
line = "先輩は１度咳ばらいをすると──"

[[dialogue]]
speaker = "アニマ"
# 「改めて、アニマと……恋人になってくれるダロウか、会長……？」
line = "「改めて、アニマと……恋人になってくれるダロウか、会長……？」"

[[dialogue]]
speaker = "unk"
# もちろん。喜んでお付き合いします
line = "もちろん。喜んでお付き合いします"

[[dialogue]]
speaker = "アニマ"
# 「そ、そうか……じゃあ、これで……契約は成立というわけダナ」
line = "「そ、そうか……じゃあ、これで……契約は成立というわけダナ」"

[[dialogue]]
speaker = "アニマ"
# 「な、なんだか、照れるナ……」
line = "「な、なんだか、照れるナ……」"

[[dialogue]]
speaker = "アニマ"
# 「フヒ……♪」
line = "「フヒ……♪」"

[[dialogue]]
speaker = "unk"
# アニマ先輩の照れた顔、可愛いです
line = "アニマ先輩の照れた顔、可愛いです"

[[dialogue]]
speaker = "アニマ"
# 「な……！？　き、急にそんなこと言うなんて、ずるいゾ……！」
line = "「な……！？　き、急にそんなこと言うなんて、ずるいゾ……！」"

[[dialogue]]
speaker = "アニマ"
# 「――恋人になったら、実験してみたかった？　……って、ひゃんっ！？」
line = "「――恋人になったら、実験してみたかった？　……って、ひゃんっ！？」"

[[dialogue]]
speaker = "アニマ"
# 「か、会長……い、いきなりアニマを抱き締めるなんて……実験には準備段階というものがあってダナ……あ、アニマ的には、スキンシップはまだ早いと……」
line = "「か、会長……い、いきなりアニマを抱き締めるなんて……実験には準備段階というものがあってダナ……あ、アニマ的には、スキンシップはまだ早いと……」"

[[dialogue]]
speaker = "unk"
# ごめんなさい。でも――
line = "ごめんなさい。でも――"

[[dialogue]]
speaker = "unk"
# 俺は彼女へそっと、顔を近づけてキスをする。
line = "俺は彼女へそっと、顔を近づけてキスをする。"

[[dialogue]]
speaker = "アニマ"
# 「あっ……会長……<emoji=heart04>」
line = "「あっ……会長……<emoji=heart04>」"

[[dialogue]]
speaker = "アニマ"
# 「んっ……<emoji=heart04>」
line = "「んっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アニマ"
# 「ちゅっ……<emoji=heart04>　んむっ……ちゅっ……<emoji=heart04>」
line = "「ちゅっ……<emoji=heart04>　んむっ……ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アニマ"
# 「……はあぁ<emoji=heart04>　付き合い始めたばかりなのに、すぐにキスをしてしまうナンて……<emoji=heart04>」
line = "「……はあぁ<emoji=heart04>　付き合い始めたばかりなのに、すぐにキスをしてしまうナンて……<emoji=heart04>」"

[[dialogue]]
speaker = "アニマ"
# 「――恋人になった副作用で、好きという気持ちが抑えられナイ……？」
line = "「――恋人になった副作用で、好きという気持ちが抑えられナイ……？」"

[[dialogue]]
speaker = "アニマ"
# 「そ、そうか……なら、仕方ない、ナ……」
line = "「そ、そうか……なら、仕方ない、ナ……」"

[[dialogue]]
speaker = "アニマ"
# 「恋人として、アニマが責任を持って、鎮めないと……ナ？」
line = "「恋人として、アニマが責任を持って、鎮めないと……ナ？」"

[[dialogue]]
speaker = "unk"
# 照れながら、じっと上目遣いで俺の目を見つめて来るアニマ先輩。
line = "照れながら、じっと上目遣いで俺の目を見つめて来るアニマ先輩。"

[[dialogue]]
speaker = "unk"
# そんな風に可愛く同意されてしまっては、我慢できるはずもなく。
line = "そんな風に可愛く同意されてしまっては、我慢できるはずもなく。"

[[dialogue]]
speaker = "アニマ"
# 「んっ……<emoji=heart04>　ちゅっ……<emoji=heart04>」
line = "「んっ……<emoji=heart04>　ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺はそれからまた、先輩と甘い実験を続けてしまうのだった――
line = "俺はそれからまた、先輩と甘い実験を続けてしまうのだった――"
