[[dialogue]]
speaker = "unk"
# 第３話,パルミエと見回りデート,P
line = "第３話,パルミエと見回りデート,P"

[[dialogue]]
speaker = "パルミエ"
# 「水精ちゃ～ん！　決めちゃいなさ～い！」
line = "「水精ちゃ～ん！　決めちゃいなさ～い！」"

[[dialogue]]
speaker = "パルミエ"
# 「ふ～、やっと片付いたわ～。プリマステラってやっぱり大変ね～」
line = "「ふ～、やっと片付いたわ～。プリマステラってやっぱり大変ね～」"

[[dialogue]]
speaker = "パルミエ"
# 「ダーリーン、部室まで負ぶって帰って～？　もうヘトヘトよ～」
line = "「ダーリーン、部室まで負ぶって帰って～？　もうヘトヘトよ～」"

[[dialogue]]
speaker = "パルミエ"
# 「それとも……このままデートにでも行っちゃう？　遊ぶ元気ならまだまだあるし♪」
line = "「それとも……このままデートにでも行っちゃう？　遊ぶ元気ならまだまだあるし♪」"

[[dialogue]]
speaker = "unk"
# いや、俺はもう少し見回りして帰るよ
line = "いや、俺はもう少し見回りして帰るよ"

[[dialogue]]
speaker = "パルミエ"
# 「うっそやだ、信じられない。可愛い私のお誘いを断るなんて」
line = "「うっそやだ、信じられない。可愛い私のお誘いを断るなんて」"

[[dialogue]]
speaker = "パルミエ"
# 「見回りなんて他の人に任せたらいいじゃなーい。デート行きましょうよ、つまんないわよ～」
line = "「見回りなんて他の人に任せたらいいじゃなーい。デート行きましょうよ、つまんないわよ～」"

[[dialogue]]
speaker = "パルミエ"
# 「そもそもここ数日ずっと見回りに出てるんじゃないの？　どれだけ見回りが好きなのよ～」
line = "「そもそもここ数日ずっと見回りに出てるんじゃないの？　どれだけ見回りが好きなのよ～」"

[[dialogue]]
speaker = "unk"
# やらなきゃいけないことだからな
line = "やらなきゃいけないことだからな"

[[dialogue]]
speaker = "パルミエ"
# 「……はぁ。ダーリンはダメね、全然わかってないわ」
line = "「……はぁ。ダーリンはダメね、全然わかってないわ」"

[[dialogue]]
speaker = "パルミエ"
# 「わかったわ。そういうことなら私も一緒に見回りしてあげる」
line = "「わかったわ。そういうことなら私も一緒に見回りしてあげる」"

[[dialogue]]
speaker = "パルミエ"
# 「いいからいいから。愛するダーリンのためだもの♪　私がとびっきり楽しい見回りにしてあげるから♪」
line = "「いいからいいから。愛するダーリンのためだもの♪　私がとびっきり楽しい見回りにしてあげるから♪」"

[[dialogue]]
speaker = "パルミエ"
# 「え～いっ！」
line = "「え～いっ！」"

[[dialogue]]
speaker = "パルミエ"
# 「むむ、ピッチングマシーンとやらも中々やるわね。次こそきっちり捕らえてやるわっ！」
line = "「むむ、ピッチングマシーンとやらも中々やるわね。次こそきっちり捕らえてやるわっ！」"

[[dialogue]]
speaker = "パルミエ"
# 「ええーいっ！」
line = "「ええーいっ！」"

[[dialogue]]
speaker = "パルミエ"
# 「やった！　ヒットよ、ヒット！　ちゃんと見ててくれたっ？」
line = "「やった！　ヒットよ、ヒット！　ちゃんと見ててくれたっ？」"

[[dialogue]]
speaker = "unk"
# パルミエ、これは……？
line = "パルミエ、これは……？"

[[dialogue]]
speaker = "パルミエ"
# 「見回りデートよ、見回りデート♪」
line = "「見回りデートよ、見回りデート♪」"

[[dialogue]]
speaker = "パルミエ"
# 「出るかもわからないモンスターをただ探し回るなんて面白くないじゃない？　それなら見回りついでにデートした方が絶対楽しいわ」
line = "「出るかもわからないモンスターをただ探し回るなんて面白くないじゃない？　それなら見回りついでにデートした方が絶対楽しいわ」"

[[dialogue]]
speaker = "パルミエ"
# 「デートしながら見回りしちゃダメだっていう規則もないでしょ？　モンスターが出たらすぐに駆けつければいいだけだし」
line = "「デートしながら見回りしちゃダメだっていう規則もないでしょ？　モンスターが出たらすぐに駆けつければいいだけだし」"

[[dialogue]]
speaker = "パルミエ"
# 「それともダーリンは、しかめっ面でモンスターを探し回る方がお好みなのかしら？　それが楽しくて仕方ないって言うならそうするけど」
line = "「それともダーリンは、しかめっ面でモンスターを探し回る方がお好みなのかしら？　それが楽しくて仕方ないって言うならそうするけど」"

[[dialogue]]
speaker = "パルミエ"
# 「ふふ、もちろん違うわよね？　私とデートしながらの方が楽しいでしょ？」
line = "「ふふ、もちろん違うわよね？　私とデートしながらの方が楽しいでしょ？」"

[[dialogue]]
speaker = "パルミエ"
# 「それじゃダーリンも打席に立って立って。未来の妻に格好いいところを見せてちょうだい♪」
line = "「それじゃダーリンも打席に立って立って。未来の妻に格好いいところを見せてちょうだい♪」"

[[dialogue]]
speaker = "パルミエ"
# 「きゃ～！　やるじゃないダーリン！　ホームランよ、ホームラン！」
line = "「きゃ～！　やるじゃないダーリン！　ホームランよ、ホームラン！」"

[[dialogue]]
speaker = "パルミエ"
# 「よーし、この調子で次はボーリングにでもいきましょ♪　その後はお買い物ね♪　休憩がてらカラオケに行くのもいいかしら～」
line = "「よーし、この調子で次はボーリングにでもいきましょ♪　その後はお買い物ね♪　休憩がてらカラオケに行くのもいいかしら～」"

[[dialogue]]
speaker = "パルミエ"
# 「ふぅ～。遊んだ、遊んだ。結局モンスターも出なかったわね～」
line = "「ふぅ～。遊んだ、遊んだ。結局モンスターも出なかったわね～」"

[[dialogue]]
speaker = "パルミエ"
# 「見回りデートの感想はどう？　ダーリンは楽しかった？」
line = "「見回りデートの感想はどう？　ダーリンは楽しかった？」"

[[dialogue]]
speaker = "unk"
# こんなに楽しい見回りは初めてだったよ
line = "こんなに楽しい見回りは初めてだったよ"

[[dialogue]]
speaker = "パルミエ"
# 「ふふ、なら良かったわ。ダーリンったら使命感ひとつで見回りしてるみたいだったから気になっちゃって」
line = "「ふふ、なら良かったわ。ダーリンったら使命感ひとつで見回りしてるみたいだったから気になっちゃって」"

[[dialogue]]
speaker = "パルミエ"
# 「やらなきゃいけない。とか言ってたでしょ？　そんな身を削るような考え方じゃ、そのうち疲れちゃうわよ～？　ブラック企業戦士じゃあるまいし」
line = "「やらなきゃいけない。とか言ってたでしょ？　そんな身を削るような考え方じゃ、そのうち疲れちゃうわよ～？　ブラック企業戦士じゃあるまいし」"

[[dialogue]]
speaker = "パルミエ"
# 「何もダーリン１人で頑張る必要はないんだから。もうちょっと気楽に構えたら？」
line = "「何もダーリン１人で頑張る必要はないんだから。もうちょっと気楽に構えたら？」"

[[dialogue]]
speaker = "パルミエ"
# 「こうしてデートしながら見回りしたっていいわけだしね。やるなら楽しくやらなくちゃ勿体ないわ」
line = "「こうしてデートしながら見回りしたっていいわけだしね。やるなら楽しくやらなくちゃ勿体ないわ」"

[[dialogue]]
speaker = "パルミエ"
# 「私も子どもの頃は毎日のようにお屋敷を抜け出して、シフォンやモナカと遊んだものよ。やっぱり人間、好きなことして過ごさなくちゃね♪」
line = "「私も子どもの頃は毎日のようにお屋敷を抜け出して、シフォンやモナカと遊んだものよ。やっぱり人間、好きなことして過ごさなくちゃね♪」"

[[dialogue]]
speaker = "unk"
# 小さい頃からお転婆だったのか
line = "小さい頃からお転婆だったのか"

[[dialogue]]
speaker = "パルミエ"
# 「ダーリンもあんなところにいたらお転婆になっちゃうわよ～。毎日毎日やりたくないお勉強やお稽古ばっかりさせられるのよ～？」
line = "「ダーリンもあんなところにいたらお転婆になっちゃうわよ～。毎日毎日やりたくないお勉強やお稽古ばっかりさせられるのよ～？」"

[[dialogue]]
speaker = "パルミエ"
# 「政治家の娘も大変よ？　外に出した時に恥ずかしくないようにって必要以上になんでも仕込もうとしてくるんだもの」
line = "「政治家の娘も大変よ？　外に出した時に恥ずかしくないようにって必要以上になんでも仕込もうとしてくるんだもの」"

[[dialogue]]
speaker = "パルミエ"
# 「ま、自慢じゃないけど私、小さい頃から可愛い上に大抵のことは器用にできちゃう天才児だったから。色々やらせたくなるのもわかるけどね♪」
line = "「ま、自慢じゃないけど私、小さい頃から可愛い上に大抵のことは器用にできちゃう天才児だったから。色々やらせたくなるのもわかるけどね♪」"

[[dialogue]]
speaker = "パルミエ"
# 「でもでも興味のないことなんかやりたくないじゃない？　実際につまらなかったし」
line = "「でもでも興味のないことなんかやりたくないじゃない？　実際につまらなかったし」"

[[dialogue]]
speaker = "パルミエ"
# 「けど、私みたいに考えられる人って意外といないみたいなのよね～。みんなホントよくやるわ。どうしてそんなに頑張れるのかしら」
line = "「けど、私みたいに考えられる人って意外といないみたいなのよね～。みんなホントよくやるわ。どうしてそんなに頑張れるのかしら」"

[[dialogue]]
speaker = "パルミエ"
# 「私はね、ダーリン。人生は楽しく自由であるべきだと思ってるの」
line = "「私はね、ダーリン。人生は楽しく自由であるべきだと思ってるの」"

[[dialogue]]
speaker = "パルミエ"
# 「本当はやらなくちゃいけないことなんか１つもないのよ。やりたくて仕方のないことがあるだけでね？」
line = "「本当はやらなくちゃいけないことなんか１つもないのよ。やりたくて仕方のないことがあるだけでね？」"

[[dialogue]]
speaker = "パルミエ"
# 「もしもどうしてもやらなきゃいけないことがあったとしても、まずはそれをやりたくて仕方のないことに変えることから始めなきゃ」
line = "「もしもどうしてもやらなきゃいけないことがあったとしても、まずはそれをやりたくて仕方のないことに変えることから始めなきゃ」"

[[dialogue]]
speaker = "パルミエ"
# 「こうして見回りをするのだって、ただ見回りするのは面倒でも、ダーリンとの見回りデートに変えちゃえば私はやる気が出てくるし♪」
line = "「こうして見回りをするのだって、ただ見回りするのは面倒でも、ダーリンとの見回りデートに変えちゃえば私はやる気が出てくるし♪」"

[[dialogue]]
speaker = "パルミエ"
# 「だから、あんまり気負い過ぎちゃだーめ♪　ワガママなくらいが丁度いいんだから♪」
line = "「だから、あんまり気負い過ぎちゃだーめ♪　ワガママなくらいが丁度いいんだから♪」"

[[dialogue]]
speaker = "パルミエ"
# 「ということでダーリン。残りの見回りは他の人に任せて、私たちはデートの続きをしちゃいましょ♪」
line = "「ということでダーリン。残りの見回りは他の人に任せて、私たちはデートの続きをしちゃいましょ♪」"

[[dialogue]]
speaker = "パルミエ"
# 「まずは腹ごしらえからね。美味しいディナーを食べたいわ～。その後は部室に戻って２人でだらだらしながらゲームしてもいいかも♪」
line = "「まずは腹ごしらえからね。美味しいディナーを食べたいわ～。その後は部室に戻って２人でだらだらしながらゲームしてもいいかも♪」"

[[dialogue]]
speaker = "パルミエ"
# 「ダーリンは何がしたい？　せっかくの機会だし、思いっきり遊んでストレス解消しちゃいましょ？」
line = "「ダーリンは何がしたい？　せっかくの機会だし、思いっきり遊んでストレス解消しちゃいましょ？」"

[[dialogue]]
speaker = "パルミエ"
# 「なんなら、ふふふ。その辺のホテルにでも入って、可愛い私とイチャイチャしちゃう？　そういう大人なデートもダーリンとなら……大歓迎よ？」
line = "「なんなら、ふふふ。その辺のホテルにでも入って、可愛い私とイチャイチャしちゃう？　そういう大人なデートもダーリンとなら……大歓迎よ？」"

[[dialogue]]
speaker = "パルミエ"
# 「あらあら、照れちゃって。我慢は体に毒よ～？」
line = "「あらあら、照れちゃって。我慢は体に毒よ～？」"

[[dialogue]]
speaker = "パルミエ"
# 「まぁそういう奥手なところも、ふふ、可愛いんだけど♪」
line = "「まぁそういう奥手なところも、ふふ、可愛いんだけど♪」"
