[[dialogue]]
speaker = "unk"
# 第３話,ナミエルのお料理修行,P
line = "第３話,ナミエルのお料理修行,P"

[[dialogue]]
speaker = "unk"
# 美化委員の清掃活動を手伝ってから、ナミエルの俺に対する態度はだいぶ柔らかくなったように思う。
line = "美化委員の清掃活動を手伝ってから、ナミエルの俺に対する態度はだいぶ柔らかくなったように思う。"

[[dialogue]]
speaker = "unk"
# もちろん『男性はえっちな生き物です』という認識はそのままだが、それでも一応信頼できる異性＆先輩として評価されているようで……
line = "もちろん『男性はえっちな生き物です』という認識はそのままだが、それでも一応信頼できる異性＆先輩として評価されているようで……"

[[dialogue]]
speaker = "unk"
# 今日は珍しく、ナミエルの方から頼み事をされた。どういうわけか、俺の家のキッチンを貸して欲しいと言わて──
line = "今日は珍しく、ナミエルの方から頼み事をされた。どういうわけか、俺の家のキッチンを貸して欲しいと言わて──"

[[dialogue]]
speaker = "ナミエル"
# 「緋宮会長。ケーキが焼き上がりました。ご試食いただけますか？」
line = "「緋宮会長。ケーキが焼き上がりました。ご試食いただけますか？」"

[[dialogue]]
speaker = "unk"
# 真っ黒のケーキ……ガトーショコラかな？
line = "真っ黒のケーキ……ガトーショコラかな？"

[[dialogue]]
speaker = "ナミエル"
# 「いえ。チーズケーキですが」
line = "「いえ。チーズケーキですが」"

[[dialogue]]
speaker = "ナミエル"
# 「──お待ちください。言いたいことはわかります」
line = "「──お待ちください。言いたいことはわかります」"

[[dialogue]]
speaker = "ナミエル"
# 「確かに見た目は悪いです。そこは認めましょう」
line = "「確かに見た目は悪いです。そこは認めましょう」"

[[dialogue]]
speaker = "ナミエル"
# 「ですが、味はなかなかのものでした。これでも試食をしましたからね」
line = "「ですが、味はなかなかのものでした。これでも試食をしましたからね」"

[[dialogue]]
speaker = "ナミエル"
# 「さぁ、緋宮会長もぜひ一口。召し上がってみてください」
line = "「さぁ、緋宮会長もぜひ一口。召し上がってみてください」"

[[dialogue]]
speaker = "unk"
# むぐっ！？
line = "むぐっ！？"

[[dialogue]]
speaker = "ナミエル"
# 「──うっ。とても心苦しそうなお顔ですね」
line = "「──うっ。とても心苦しそうなお顔ですね」"

[[dialogue]]
speaker = "ナミエル"
# 「やはり私が味オンチなのですね……むぅ。このままではまずいです」
line = "「やはり私が味オンチなのですね……むぅ。このままではまずいです」"

[[dialogue]]
speaker = "ナミエル"
# 「実は今度の日曜日に、お嬢様と２人きりでお茶をすることになったのです」
line = "「実は今度の日曜日に、お嬢様と２人きりでお茶をすることになったのです」"

[[dialogue]]
speaker = "ナミエル"
# 「お嬢様はお忙しい身ですが、お屋敷で働く者たちの声を直接聞くため、語らいの場を設けてくださったのです」
line = "「お嬢様はお忙しい身ですが、お屋敷で働く者たちの声を直接聞くため、語らいの場を設けてくださったのです」"

[[dialogue]]
speaker = "ナミエル"
# 「もちろんメイド隊だけでなく、コックや庭師なども対象です。お嬢様は本当にお優しく、素敵なお方です……」
line = "「もちろんメイド隊だけでなく、コックや庭師なども対象です。お嬢様は本当にお優しく、素敵なお方です……」"

[[dialogue]]
speaker = "ナミエル"
# 「敬愛しているお嬢様との大切なひと時ですから、このナミエル、万全の準備で臨みたいと思いました」
line = "「敬愛しているお嬢様との大切なひと時ですから、このナミエル、万全の準備で臨みたいと思いました」"

[[dialogue]]
speaker = "ナミエル"
# 「そこで、紅茶に合うお菓子を手作りしてはどうかと思ったのです。私はその……料理が苦手なので、良いサプライズになるかなと」
line = "「そこで、紅茶に合うお菓子を手作りしてはどうかと思ったのです。私はその……料理が苦手なので、良いサプライズになるかなと」"

[[dialogue]]
speaker = "ナミエル"
# 「緋宮会長には感謝しています。お屋敷で練習していては私の目論見がお嬢様にバレてしまいかねませんからね」
line = "「緋宮会長には感謝しています。お屋敷で練習していては私の目論見がお嬢様にバレてしまいかねませんからね」"

[[dialogue]]
speaker = "ナミエル"
# 「……しかしこのケーキ、何がいけなかったのでしょう？」
line = "「……しかしこのケーキ、何がいけなかったのでしょう？」"

[[dialogue]]
speaker = "ナミエル"
# 「多少、材料や手順にアレンジは加えましたが、基本はレシピ通りのはずなのに……」
line = "「多少、材料や手順にアレンジは加えましたが、基本はレシピ通りのはずなのに……」"

[[dialogue]]
speaker = "unk"
# そのアレンジのせいじゃないか……！？
line = "そのアレンジのせいじゃないか……！？"

[[dialogue]]
speaker = "ナミエル"
# 「ですがお嬢様に渡すスペシャルなケーキなのです。レシピに沿っただけのものでは、私の忠誠心が込められません……！」
line = "「ですがお嬢様に渡すスペシャルなケーキなのです。レシピに沿っただけのものでは、私の忠誠心が込められません……！」"

[[dialogue]]
speaker = "unk"
# 良ければ俺にも手伝わせてくれないか
line = "良ければ俺にも手伝わせてくれないか"

[[dialogue]]
speaker = "ナミエル"
# 「……そういえば、学園に入る前はアルバイトをたくさんしていたそうですね」
line = "「……そういえば、学園に入る前はアルバイトをたくさんしていたそうですね」"

[[dialogue]]
speaker = "ナミエル"
# 「飲食店の経験もおありなのですか。頼もしいです。サポートをお願いできますか？」
line = "「飲食店の経験もおありなのですか。頼もしいです。サポートをお願いできますか？」"

[[dialogue]]
speaker = "ナミエル"
# 「ケーキは甘ければ甘いほど良いはずです。お砂糖をレシピの３倍程度、入れてみました」
line = "「ケーキは甘ければ甘いほど良いはずです。お砂糖をレシピの３倍程度、入れてみました」"

[[dialogue]]
speaker = "ナミエル"
# 「もぐもぐ……うん。濃厚な甘みがあります──ぇ？　甘すぎて胃もたれする？　そうですか……」
line = "「もぐもぐ……うん。濃厚な甘みがあります──ぇ？　甘すぎて胃もたれする？　そうですか……」"

[[dialogue]]
speaker = "ナミエル"
# 「表面を軽く焦がすのがトレンドだそうです。倍の時間をかけて焼き上げてみました」
line = "「表面を軽く焦がすのがトレンドだそうです。倍の時間をかけて焼き上げてみました」"

[[dialogue]]
speaker = "ナミエル"
# 「もぐもぐ……うん。ほんのり苦くて良いアクセントです──え？　焦げ焦げだからダメ？　むむぅ……」
line = "「もぐもぐ……うん。ほんのり苦くて良いアクセントです──え？　焦げ焦げだからダメ？　むむぅ……」"

[[dialogue]]
speaker = "ナミエル"
# 「ダマが一切残らぬよう、生地を徹底的に混ぜ混ぜしてみました。きっと良い出来になるはずです」
line = "「ダマが一切残らぬよう、生地を徹底的に混ぜ混ぜしてみました。きっと良い出来になるはずです」"

[[dialogue]]
speaker = "ナミエル"
# 「う……スポンジがぼそぼそのぐしゃぐしゃに……これではとてもお出しできません……もう一度！」
line = "「う……スポンジがぼそぼそのぐしゃぐしゃに……これではとてもお出しできません……もう一度！」"

[[dialogue]]
speaker = "unk"
# こうして連日、ナミエルのケーキ作りに付き合い続け、アレンジしたがるのを必死で止めて──数日後。
line = "こうして連日、ナミエルのケーキ作りに付き合い続け、アレンジしたがるのを必死で止めて──数日後。"

[[dialogue]]
speaker = "ナミエル"
# 「できました……！　写真の通りのチーズケーキが！」
line = "「できました……！　写真の通りのチーズケーキが！」"

[[dialogue]]
speaker = "ナミエル"
# 「緋宮会長、本当にありがとうございます。これでお嬢様にサプライズができます！」
line = "「緋宮会長、本当にありがとうございます。これでお嬢様にサプライズができます！」"

[[dialogue]]
speaker = "ナミエル"
# 「感無量です……これは撮影し、記録に残さねば！」
line = "「感無量です……これは撮影し、記録に残さねば！」"

[[dialogue]]
speaker = "ナミエル"
# 「むむ。この角度よりも……」
line = "「むむ。この角度よりも……」"

[[dialogue]]
speaker = "ナミエル"
# 「こっちの方が映える気がいたしますね。連写しましょう」
line = "「こっちの方が映える気がいたしますね。連写しましょう」"

[[dialogue]]
speaker = "unk"
# ナミエルってＳＮＳをやってるのか？
line = "ナミエルってＳＮＳをやってるのか？"

[[dialogue]]
speaker = "ナミエル"
# 「ええ。メイド長に、掃除以外の趣味を持てと言われて始めたのです」
line = "「ええ。メイド長に、掃除以外の趣味を持てと言われて始めたのです」"

[[dialogue]]
speaker = "ナミエル"
# 「最初は性に合いませんでしたが、意外と反響をもらえるのが楽しくて」
line = "「最初は性に合いませんでしたが、意外と反響をもらえるのが楽しくて」"

[[dialogue]]
speaker = "ナミエル"
# 「──どうでしょう、緋宮会長。さっそくアップロードしてみました。いい感じではないですか？」
line = "「──どうでしょう、緋宮会長。さっそくアップロードしてみました。いい感じではないですか？」"

[[dialogue]]
speaker = "unk"
# あ、さっそくいいねが付いた
line = "あ、さっそくいいねが付いた"

[[dialogue]]
speaker = "ナミエル"
# 「ふふ。そうでしょうとも──って、あぁあっ！？　お嬢様からの『いいね』が！」
line = "「ふふ。そうでしょうとも──って、あぁあっ！？　お嬢様からの『いいね』が！」"

[[dialogue]]
speaker = "ナミエル"
# 「しまった。迂闊でした……！　お嬢様は私のアカウントの一番のフォロワーなのです……！」
line = "「しまった。迂闊でした……！　お嬢様は私のアカウントの一番のフォロワーなのです……！」"

[[dialogue]]
speaker = "ナミエル"
# 「見つかってしまいました。これではサプライズになりません……！　ど、どうすればっ……！？」
line = "「見つかってしまいました。これではサプライズになりません……！　ど、どうすればっ……！？」"

[[dialogue]]
speaker = "unk"
# その後ナミエルにお願いされて、バレてしまったケーキを超える、新しいケーキの習得に付き合ったのだった。
line = "その後ナミエルにお願いされて、バレてしまったケーキを超える、新しいケーキの習得に付き合ったのだった。"
