[[dialogue]]
speaker = "unk"
# 第１話,サマー・マイ・ハニー,P
line = "第１話,サマー・マイ・ハニー,P"

[[dialogue]]
speaker = "セーラ"
# 「ん～っ！　海～っ！」
line = "「ん～っ！　海～っ！」"

[[dialogue]]
speaker = "セーラ"
# 「冬に海これるとかまじ最高！　季節感バグっちゃいそーだけど、それもまたヨシ！」
line = "「冬に海これるとかまじ最高！　季節感バグっちゃいそーだけど、それもまたヨシ！」"

[[dialogue]]
speaker = "セーラ"
# 「って……どしたん？　会長さん、そんなもじもじして」
line = "「って……どしたん？　会長さん、そんなもじもじして」"

[[dialogue]]
speaker = "セーラ"
# 「会長さん……もしかして、未だにうちの水着に照れてたりする？」
line = "「会長さん……もしかして、未だにうちの水着に照れてたりする？」"

[[dialogue]]
speaker = "unk"
# 少しだけだ
line = "少しだけだ"

[[dialogue]]
speaker = "unk"
# そんなことは……
line = "そんなことは……"

[[dialogue]]
speaker = "セーラ"
# 「あはは、うける。今さらそんなこと言う？」
line = "「あはは、うける。今さらそんなこと言う？」"

[[dialogue]]
speaker = "セーラ"
# （もうあんなところまで見せちゃった仲なのに……さ）
line = "（もうあんなところまで見せちゃった仲なのに……さ）"

[[dialogue]]
speaker = "セーラ"
# 「なーんてね。えっちい話にはちょっとまだ早いか♪」
line = "「なーんてね。えっちい話にはちょっとまだ早いか♪」"

[[dialogue]]
speaker = "セーラ"
# 「ビーチに来たんだから、ここじゃないとできない遊びがしたいよね～」
line = "「ビーチに来たんだから、ここじゃないとできない遊びがしたいよね～」"

[[dialogue]]
speaker = "unk"
# ビーチバレー？
line = "ビーチバレー？"

[[dialogue]]
speaker = "unk"
# スイカ割り？
line = "スイカ割り？"

[[dialogue]]
speaker = "セーラ"
# 「ん～……それもいいんだけど……そーゆーのはみんなとやった方が楽しそうな気がする」
line = "「ん～……それもいいんだけど……そーゆーのはみんなとやった方が楽しそうな気がする」"

[[dialogue]]
speaker = "セーラ"
# 「今日はせっかく２人だけなんだからー……あ、そうだ！」
line = "「今日はせっかく２人だけなんだからー……あ、そうだ！」"

[[dialogue]]
speaker = "セーラ"
# 「リップルちゃーん！　リクエストいーいー？」
line = "「リップルちゃーん！　リクエストいーいー？」"

[[dialogue]]
speaker = "リップル"
# 「ハーイ、セーラ♪　どんなゴヨウケンですか～？」
line = "「ハーイ、セーラ♪　どんなゴヨウケンですか～？」"

[[dialogue]]
speaker = "セーラ"
# 「雑誌で読んだアクティビティ──フライボードとかパラセーリングとかってのやってみたいんだけど、そういうのある？」
line = "「雑誌で読んだアクティビティ──フライボードとかパラセーリングとかってのやってみたいんだけど、そういうのある？」"

[[dialogue]]
speaker = "リップル"
# 「ワオ！　マリンスポーツですネー！」
line = "「ワオ！　マリンスポーツですネー！」"

[[dialogue]]
speaker = "リップル"
# 「ノープロブレムデース！　リゾート結界にはあらゆる夏のレジャーが揃っておりマースから──お任せアレ～！」
line = "「ノープロブレムデース！　リゾート結界にはあらゆる夏のレジャーが揃っておりマースから──お任せアレ～！」"

[[dialogue]]
speaker = "リップル"
# 「デスが道具の準備にお時間かかりマース。少々お待ちくださいデース～♪」
line = "「デスが道具の準備にお時間かかりマース。少々お待ちくださいデース～♪」"

[[dialogue]]
speaker = "unk"
# パラセーリングって？
line = "パラセーリングって？"

[[dialogue]]
speaker = "unk"
# フライボードって？
line = "フライボードって？"

[[dialogue]]
speaker = "セーラ"
# 「フライボードはほら、足元から水流ブシャーッて噴射して歩くやつ！　動画とかで見たことない？」
line = "「フライボードはほら、足元から水流ブシャーッて噴射して歩くやつ！　動画とかで見たことない？」"

[[dialogue]]
speaker = "セーラ"
# 「んでパラセーリングは、海の上をでっかいパラシュートで飛ぶやつ！　ボートに引っ張ってもらうのかな？」
line = "「んでパラセーリングは、海の上をでっかいパラシュートで飛ぶやつ！　ボートに引っ張ってもらうのかな？」"

[[dialogue]]
speaker = "セーラ"
# 「実はさー、夏のトキに気になってたやつあったんだよね」
line = "「実はさー、夏のトキに気になってたやつあったんだよね」"

[[dialogue]]
speaker = "セーラ"
# 「雑誌でちょろっと見ただけなんだけど……『海のアクティビティ大特集』ってのに色々載ってたんだ！」
line = "「雑誌でちょろっと見ただけなんだけど……『海のアクティビティ大特集』ってのに色々載ってたんだ！」"

[[dialogue]]
speaker = "セーラ"
# 「どっちも体験したことなくてさ～。ちゃんと設備のあるビーチに行かなきゃなって思ってたんだけど……」
line = "「どっちも体験したことなくてさ～。ちゃんと設備のあるビーチに行かなきゃなって思ってたんだけど……」"

[[dialogue]]
speaker = "セーラ"
# 「ここならリップルちゃんに頼めばできそうかなって♪　さすがって感じ♪」
line = "「ここならリップルちゃんに頼めばできそうかなって♪　さすがって感じ♪」"

[[dialogue]]
speaker = "unk"
# 自分も初めて
line = "自分も初めて"

[[dialogue]]
speaker = "unk"
# 楽しみだ
line = "楽しみだ"

[[dialogue]]
speaker = "セーラ"
# 「会長さんも初めて？　ふふ、なら一緒だね」
line = "「会長さんも初めて？　ふふ、なら一緒だね」"

[[dialogue]]
speaker = "セーラ"
# 「でも、リップルちゃんちょっと時間かかるって言ってたね。んー……」
line = "「でも、リップルちゃんちょっと時間かかるって言ってたね。んー……」"

[[dialogue]]
speaker = "セーラ"
# 「……ねえ、会長さん」
line = "「……ねえ、会長さん」"

[[dialogue]]
speaker = "セーラ"
# 「うちにオイル、塗ってくんない？」
line = "「うちにオイル、塗ってくんない？」"

[[dialogue]]
speaker = "セーラ"
# 「ふふっ……うんうん。大丈夫大丈夫。そのまま塗って伸ばしてもらえればいいから」
line = "「ふふっ……うんうん。大丈夫大丈夫。そのまま塗って伸ばしてもらえればいいから」"

[[dialogue]]
speaker = "unk"
# 水着のトップを外して寝そべるセーラさんの背中に、じっくりとサンオイルを塗り込んでいく。
line = "水着のトップを外して寝そべるセーラさんの背中に、じっくりとサンオイルを塗り込んでいく。"

[[dialogue]]
speaker = "unk"
# しばらくして作業が完了すると、彼女はトップを着用して立ち上がった。
line = "しばらくして作業が完了すると、彼女はトップを着用して立ち上がった。"

[[dialogue]]
speaker = "セーラ"
# 「──はーい、あんがと」
line = "「──はーい、あんがと」"

[[dialogue]]
speaker = "セーラ"
# 「にしても……まだそんな照れる？　うちまで恥ずかしくなってきちゃうじゃん」
line = "「にしても……まだそんな照れる？　うちまで恥ずかしくなってきちゃうじゃん」"

[[dialogue]]
speaker = "セーラ"
# 「さっきも言ったけど──あーんなこととかこーんなこともしちゃった仲なのにさ……？」
line = "「さっきも言ったけど──あーんなこととかこーんなこともしちゃった仲なのにさ……？」"

[[dialogue]]
speaker = "unk"
# 色っぽくて……
line = "色っぽくて……"

[[dialogue]]
speaker = "unk"
# それとこれとは
line = "それとこれとは"

[[dialogue]]
speaker = "セーラ"
# 「……そっか」
line = "「……そっか」"

[[dialogue]]
speaker = "セーラ"
# 「ふふっ──でも……うれしーよ。いつまでもうちのこと、新鮮なまま見てくれてるってことだもんね」
line = "「ふふっ──でも……うれしーよ。いつまでもうちのこと、新鮮なまま見てくれてるってことだもんね」"

[[dialogue]]
speaker = "セーラ"
# 「会長さんの彼女として──いつまでもドキドキさせたげるね？」
line = "「会長さんの彼女として──いつまでもドキドキさせたげるね？」"

[[dialogue]]
speaker = "unk"
# 小悪魔チックに微笑むセーラさん。
line = "小悪魔チックに微笑むセーラさん。"

[[dialogue]]
speaker = "unk"
# 惚れた時の気持ちが、色褪せぬままよみがえってくるようだった……。
line = "惚れた時の気持ちが、色褪せぬままよみがえってくるようだった……。"
