[[dialogue]]
speaker = "unk"
# 第２話,マトイのお父さん,P
line = "第２話,マトイのお父さん,P"

[[dialogue]]
speaker = "unk"
# とある週末の休日。俺はマトイと、学園近くでデートをする約束をしていたのだが――
line = "とある週末の休日。俺はマトイと、学園近くでデートをする約束をしていたのだが――"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「それが、どうして家族とファミレスに入ることに……」
line = "「それが、どうして家族とファミレスに入ることに……」"

[[dialogue]]
speaker = "マトイ母"
# 「あら、いいじゃない♪　せっかくお昼時に会ったんだし～」
line = "「あら、いいじゃない♪　せっかくお昼時に会ったんだし～」"

[[dialogue]]
speaker = "unk"
# そこはファミリーレストランの中。
line = "そこはファミリーレストランの中。"

[[dialogue]]
speaker = "unk"
# 俺とマトイが隣り合って席に座り、テーブルを挟んで、向かいに座っているのはマトイのお母さん――マモリさんと、それから……
line = "俺とマトイが隣り合って席に座り、テーブルを挟んで、向かいに座っているのはマトイのお母さん――マモリさんと、それから……"

[[dialogue]]
speaker = "マトイ父"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# マモリさん達は、どうやら夫婦で買い物に来ていたらしい。街中でばったり顔を合わせて、せっかくだから挨拶がてら食事でもどうかという話になったのだった。
line = "マモリさん達は、どうやら夫婦で買い物に来ていたらしい。街中でばったり顔を合わせて、せっかくだから挨拶がてら食事でもどうかという話になったのだった。"

[[dialogue]]
speaker = "unk"
# は、初めまして……
line = "は、初めまして……"

[[dialogue]]
speaker = "unk"
# 俺は名前と、新星学園の星徒会長を務めていること、それと……マトイの彼氏として、男女のお付き合いをさせてもらっていることを自己紹介する。
line = "俺は名前と、新星学園の星徒会長を務めていること、それと……マトイの彼氏として、男女のお付き合いをさせてもらっていることを自己紹介する。"

[[dialogue]]
speaker = "マトイ父"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「ちょっと、お父さん！　黙ってないで、自己紹介してよ」
line = "「ちょっと、お父さん！　黙ってないで、自己紹介してよ」"

[[dialogue]]
speaker = "マトイ父"
# 「……ああ。えっと……」
line = "「……ああ。えっと……」"

[[dialogue]]
speaker = "マトイ父"
# 「娘がお世話になっております。マトイの父――<ruby=よみの>詠野</ruby>ススムです。その……よろしくお願いします」
line = "「娘がお世話になっております。マトイの父――<ruby>詠野<rt>よみの</rt></ruby>ススムです。その……よろしくお願いします」"

[[dialogue]]
speaker = "マトイ母"
# 「ごめんね、会長くん。お父さん、ちょっと不愛想に見えるかもしれないけど、別に怒ってたりとかそんなんじゃないから」
line = "「ごめんね、会長くん。お父さん、ちょっと不愛想に見えるかもしれないけど、別に怒ってたりとかそんなんじゃないから」"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「普段はもっと、普通のサラリーマンをやってるおじさんって感じなんだけど……」
line = "「普段はもっと、普通のサラリーマンをやってるおじさんって感じなんだけど……」"

[[dialogue]]
speaker = "マトイ父"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "マトイ母"
# 「あっ、私、ちょっとお手洗いに行ってくるわね。マトイもこっち……！」
line = "「あっ、私、ちょっとお手洗いに行ってくるわね。マトイもこっち……！」"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「えっ、私も？　なんで？」
line = "「えっ、私も？　なんで？」"

[[dialogue]]
speaker = "マトイ母"
# 「いいからいいから。ほら、一緒に行きましょ♪　ついでにドリンクバーで飲み物取って来るわね～。会長くんとお父さんは何がいいかしら？」
line = "「いいからいいから。ほら、一緒に行きましょ♪　ついでにドリンクバーで飲み物取って来るわね～。会長くんとお父さんは何がいいかしら？」"

[[dialogue]]
speaker = "unk"
# えっと……そしたら緑茶で
line = "えっと……そしたら緑茶で"

[[dialogue]]
speaker = "マトイ父"
# 「…………私も同じのを」
line = "「…………私も同じのを」"

[[dialogue]]
speaker = "マトイ母"
# 「は～い♪　それじゃあ、親子仲良く行って来ま～す♪」
line = "「は～い♪　それじゃあ、親子仲良く行って来ま～す♪」"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「ちょっと、お母さん！　私、別にお手洗いに行かなくても――わ～っ！？」
line = "「ちょっと、お母さん！　私、別にお手洗いに行かなくても――わ～っ！？」"

[[dialogue]]
speaker = "クロト"
# 参った……どうしよう。マトイのお父さんと２人きりになってしまった……。一体、何を話したら……
line = "参った……どうしよう。マトイのお父さんと２人きりになってしまった……。一体、何を話したら……"

[[dialogue]]
speaker = "unk"
# 気まずさを感じながら、悩んでいると――
line = "気まずさを感じながら、悩んでいると――"

[[dialogue]]
speaker = "マトイ父"
# 「……その、気分を悪くさせてしまっていたら、すまない」
line = "「……その、気分を悪くさせてしまっていたら、すまない」"

[[dialogue]]
speaker = "unk"
# え……？
line = "え……？"

[[dialogue]]
speaker = "unk"
# 俺はススムさんの顔を見る。緊張していて気づかなかったが、よく見るとそれは俺と同じ――
line = "俺はススムさんの顔を見る。緊張していて気づかなかったが、よく見るとそれは俺と同じ――"

[[dialogue]]
speaker = "マトイ父"
# 「キミには……本当はもっと感謝しなくてはならないとわかっているんだ。娘から聞いている。キミが星騎士として、どんな厳しい戦いを乗り越えて、リクリエを退けたのか」
line = "「キミには……本当はもっと感謝しなくてはならないとわかっているんだ。娘から聞いている。キミが星騎士として、どんな厳しい戦いを乗り越えて、リクリエを退けたのか」"

[[dialogue]]
speaker = "マトイ父"
# 「だが、同時にマトイの彼氏と聞くと、やっぱり複雑な感情も抱いてしまって……こうして面と向かうと、どのように接したらいいのかわからないんだ……」
line = "「だが、同時にマトイの彼氏と聞くと、やっぱり複雑な感情も抱いてしまって……こうして面と向かうと、どのように接したらいいのかわからないんだ……」"

[[dialogue]]
speaker = "マトイ父"
# 「ただ、誤解はしないで欲しい！　これは私という一個人の問題であって、娘には――マトイには関係がない」
line = "「ただ、誤解はしないで欲しい！　これは私という一個人の問題であって、娘には――マトイには関係がない」"

[[dialogue]]
speaker = "マトイ父"
# 「あの子はいい子なんだ。だから――」
line = "「あの子はいい子なんだ。だから――」"

[[dialogue]]
speaker = "unk"
# ススムさんは深く頭を下げて、言った。
line = "ススムさんは深く頭を下げて、言った。"

[[dialogue]]
speaker = "マトイ父"
# 「どうか、これからもあの子のことをよろしくお願いします」
line = "「どうか、これからもあの子のことをよろしくお願いします」"

[[dialogue]]
speaker = "unk"
# す、ススムさん！　頭を上げて下さい！
line = "す、ススムさん！　頭を上げて下さい！"

[[dialogue]]
speaker = "クロト"
# ああ、そうだ。この人は確かにマトイのお父さんだ。
line = "ああ、そうだ。この人は確かにマトイのお父さんだ。"

[[dialogue]]
speaker = "クロト"
# 普通に優しくて、いい人なのだ。だから――
line = "普通に優しくて、いい人なのだ。だから――"

[[dialogue]]
speaker = "unk"
# 俺、ススムさんとも仲良くなりたいです
line = "俺、ススムさんとも仲良くなりたいです"

[[dialogue]]
speaker = "マトイ父"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "unk"
# 少しして、マトイ達が帰って来ると――
line = "少しして、マトイ達が帰って来ると――"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「こ、これは……」
line = "「こ、これは……」"

[[dialogue]]
speaker = "マトイ父"
# 「そうか、そうか、ははは！　マトイから話は聞いていたけど、まさかそこまで時代劇が好きだとは！」
line = "「そうか、そうか、ははは！　マトイから話は聞いていたけど、まさかそこまで時代劇が好きだとは！」"

[[dialogue]]
speaker = "unk"
# まさか、ここまで趣味が一緒だなんて！
line = "まさか、ここまで趣味が一緒だなんて！"

[[dialogue]]
speaker = "マトイ父"
# 「いや～、これならもっと早く顔を合わせておけばよかったな！　はははは！」
line = "「いや～、これならもっと早く顔を合わせておけばよかったな！　はははは！」"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「離れていた数分の間に、一体何が！？」
line = "「離れていた数分の間に、一体何が！？」"

[[dialogue]]
speaker = "マトイ母"
# 「ふふっ、お父さんと会長くん、絶対に気が合うと思ってたのよね～」
line = "「ふふっ、お父さんと会長くん、絶対に気が合うと思ってたのよね～」"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「いや、確かに趣味は一緒だな～って前から思ってたけども！」
line = "「いや、確かに趣味は一緒だな～って前から思ってたけども！」"

[[dialogue]]
speaker = "マトイ父"
# 「あっ、そうだ、会長くん！　少年漫画が好きだとも言っていたが、今流行りのアレは読んでいるかい？」
line = "「あっ、そうだ、会長くん！　少年漫画が好きだとも言っていたが、今流行りのアレは読んでいるかい？」"

[[dialogue]]
speaker = "マトイ父"
# 「――そう、時代劇の！　来週アレの映画、『鉄道編』が上映開始するじゃないか！」
line = "「――そう、時代劇の！　来週アレの映画、『鉄道編』が上映開始するじゃないか！」"

[[dialogue]]
speaker = "マトイ父"
# 「せっかくこうして知り合えたんだし、おじさんと一緒に観に行くかい！？」
line = "「せっかくこうして知り合えたんだし、おじさんと一緒に観に行くかい！？」"

[[dialogue]]
speaker = "unk"
# 是非！　行きましょう！
line = "是非！　行きましょう！"

[[dialogue]]
speaker = "マトイ父"
# 「よし！　じゃあ今度、おじさんとデートをしようじゃないか♪　はっはっはっは！」
line = "「よし！　じゃあ今度、おじさんとデートをしようじゃないか♪　はっはっはっは！」"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「ちょっ！？　それ、私が会長を誘って行こうと思ってたのに！？」
line = "「ちょっ！？　それ、私が会長を誘って行こうと思ってたのに！？」"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「彼女より先に、お父さんと彼氏がデートの約束してるってどういうことーーーーーーっ！？！？」
line = "「彼女より先に、お父さんと彼氏がデートの約束してるってどういうことーーーーーーっ！？！？」"

[[dialogue]]
speaker = "マトイ母"
# 「ぷっ……あはははっ♪　これから色々と、楽しくなりそうね～♪」
line = "「ぷっ……あはははっ♪　これから色々と、楽しくなりそうね～♪」"

[[dialogue]]
speaker = "unk"
# ちなみにその後、折衷案で俺とマトイ一家のみんなで映画を観に行こうという話になり――いずれにしてもマトイのお父さんと仲良くなれそうで、嬉しく思う俺なのだった。
line = "ちなみにその後、折衷案で俺とマトイ一家のみんなで映画を観に行こうという話になり――いずれにしてもマトイのお父さんと仲良くなれそうで、嬉しく思う俺なのだった。"
