[[dialogue]]
speaker = "unk"
# 第４話,いつか変わる呼び方,P
line = "第４話,いつか変わる呼び方,P"

[[dialogue]]
speaker = "unk"
# とある休日──アナがいつものように俺の家へ遊びに来た。
line = "とある休日──アナがいつものように俺の家へ遊びに来た。"

[[dialogue]]
speaker = "unk"
# 一緒に食事をとったり、最近読んだ本の内容を語ったりと、まったりとした午後を過ごしていたのだけれど……
line = "一緒に食事をとったり、最近読んだ本の内容を語ったりと、まったりとした午後を過ごしていたのだけれど……"

[[dialogue]]
speaker = "アナ"
# 「すぅ……すぅ……」
line = "「すぅ……すぅ……」"

[[dialogue]]
speaker = "unk"
# 膝の上で寝ちゃったな
line = "膝の上で寝ちゃったな"

[[dialogue]]
speaker = "アナ"
# 「んん……お父さん、ダメ、ですよー……甘やかしたら……」
line = "「んん……お父さん、ダメ、ですよー……甘やかしたら……」"

[[dialogue]]
speaker = "unk"
# アナが寝言をこぼすなんて珍しい。
line = "アナが寝言をこぼすなんて珍しい。"

[[dialogue]]
speaker = "unk"
# 『お父さん』と言うからには、天界にいるご両親のことを夢に見ているのだろうか？
line = "『お父さん』と言うからには、天界にいるご両親のことを夢に見ているのだろうか？"

[[dialogue]]
speaker = "アナ"
# 「むにゃ……まったく……あなたは……いつも、そうなんですから……すぅ……すぅう……」
line = "「むにゃ……まったく……あなたは……いつも、そうなんですから……すぅ……すぅう……」"

[[dialogue]]
speaker = "unk"
# ……どんな夢を見てるんだろう？
line = "……どんな夢を見てるんだろう？"

[[dialogue]]
speaker = "unk"
# ──あなた？
line = "──あなた？"

[[dialogue]]
speaker = "アナ"
# 「……ぁっ。ン、ンン……あれ、夢……？」
line = "「……ぁっ。ン、ンン……あれ、夢……？」"

[[dialogue]]
speaker = "unk"
# おはよう、アナ
line = "おはよう、アナ"

[[dialogue]]
speaker = "アナ"
# 「んー……ふぁあっ……。すみません、うたた寝しちゃってたみたいです……」
line = "「んー……ふぁあっ……。すみません、うたた寝しちゃってたみたいです……」"

[[dialogue]]
speaker = "アナ"
# 「会長のお膝、ベストプレイス賞だけでなく、寝具としてもグッドデザイン賞、受賞ですね。ついついリラックスしてしまって……」
line = "「会長のお膝、ベストプレイス賞だけでなく、寝具としてもグッドデザイン賞、受賞ですね。ついついリラックスしてしまって……」"

[[dialogue]]
speaker = "アナ"
# 「ん……？　どうかしましたか、会長。じっと私の顔を見て……何か付いてます？」
line = "「ん……？　どうかしましたか、会長。じっと私の顔を見て……何か付いてます？」"

[[dialogue]]
speaker = "unk"
# 夢でも見てた？
line = "夢でも見てた？"

[[dialogue]]
speaker = "アナ"
# 「夢……？　見ていたような、いなかったような……」
line = "「夢……？　見ていたような、いなかったような……」"

[[dialogue]]
speaker = "アナ"
# 「私が『お父さん』って呟いていたんですか？　はて……天界の両親の夢なんて、見ていたでしょうか……」
line = "「私が『お父さん』って呟いていたんですか？　はて……天界の両親の夢なんて、見ていたでしょうか……」"

[[dialogue]]
speaker = "アナ"
# 「『あなた』という呼び名もあった？　んー……？　あなた、なんて呼ぶ相手は、天界にいないのですが」
line = "「『あなた』という呼び名もあった？　んー……？　あなた、なんて呼ぶ相手は、天界にいないのですが」"

[[dialogue]]
speaker = "アナ"
# 「待ってください、気になるので思い出します……えっと……んー……？」
line = "「待ってください、気になるので思い出します……えっと……んー……？」"

[[dialogue]]
speaker = "アナ"
# 「──そうです。人間界でしたね、桜の花がたくさんありましたから……あれは……公園？　そう、公園ですね」
line = "「──そうです。人間界でしたね、桜の花がたくさんありましたから……あれは……公園？　そう、公園ですね」"

[[dialogue]]
speaker = "アナ"
# 「私は学園を卒業していたと思います。制服を着ていませんでした。それで隣に、お父さんが──ぁぁあっ！？」
line = "「私は学園を卒業していたと思います。制服を着ていませんでした。それで隣に、お父さんが──ぁぁあっ！？」"

[[dialogue]]
speaker = "アナ"
# 「お、思い出し、ました……あ、あわわ……私、なんという夢を……！？」
line = "「お、思い出し、ました……あ、あわわ……私、なんという夢を……！？」"

[[dialogue]]
speaker = "アナ"
# 「か、会長。えっと、その……夢の内容、本当に、聞きたいですか……？」
line = "「か、会長。えっと、その……夢の内容、本当に、聞きたいですか……？」"

[[dialogue]]
speaker = "unk"
# 気になるなぁ
line = "気になるなぁ"

[[dialogue]]
speaker = "unk"
# アナのお父さんの夢なんでしょ？
line = "アナのお父さんの夢なんでしょ？"

[[dialogue]]
speaker = "アナ"
# 「いえ、違うんです。その……お父さんって言うのは……私の父のことじゃありません」
line = "「いえ、違うんです。その……お父さんって言うのは……私の父のことじゃありません」"

[[dialogue]]
speaker = "アナ"
# 「えっと……お父さんイコール……会長です」
line = "「えっと……お父さんイコール……会長です」"

[[dialogue]]
speaker = "unk"
# ……俺っ！？
line = "……俺っ！？"

[[dialogue]]
speaker = "アナ"
# 「その……会長が『お父さん』になっていたので……。子供の前だから、お父さん、と……」
line = "「その……会長が『お父さん』になっていたので……。子供の前だから、お父さん、と……」"

[[dialogue]]
speaker = "アナ"
# 「『あなた』というのは……子供が私たちの傍から離れたので。２人きりの時は、そうやって呼んでいるみたい……でした」
line = "「『あなた』というのは……子供が私たちの傍から離れたので。２人きりの時は、そうやって呼んでいるみたい……でした」"

[[dialogue]]
speaker = "アナ"
# 「な、何だか尋常じゃないくらい恥ずかしいのですが……！？　夢を見るにしたって、ああまでリアルに見なくても……！！」
line = "「な、何だか尋常じゃないくらい恥ずかしいのですが……！？　夢を見るにしたって、ああまでリアルに見なくても……！！」"

[[dialogue]]
speaker = "アナ"
# 「──っ！？　も、もうっ、何ですか、その顔は……！　に、にやにやと笑って。あんまり私の顔、見ないでください……！」
line = "「──っ！？　も、もうっ、何ですか、その顔は……！　に、にやにやと笑って。あんまり私の顔、見ないでください……！」"

[[dialogue]]
speaker = "unk"
# 将来、本当にそうなったらいいな
line = "将来、本当にそうなったらいいな"

[[dialogue]]
speaker = "アナ"
# 「ま、また会長は、そうやってストレートに……」
line = "「ま、また会長は、そうやってストレートに……」"

[[dialogue]]
speaker = "アナ"
# 「でも……はい。私も、そうなったら……素敵だなって、思います」
line = "「でも……はい。私も、そうなったら……素敵だなって、思います」"

[[dialogue]]
speaker = "アナ"
# 「夢の世界は、１０年後くらい、だったと思います。モンスターが出ない平和になった世界で……会長と結婚していました」
line = "「夢の世界は、１０年後くらい、だったと思います。モンスターが出ない平和になった世界で……会長と結婚していました」"

[[dialogue]]
speaker = "アナ"
# 「公園の近くに家があって。以前に、子供がたくさん欲しいって話したこと、ありましたよね」
line = "「公園の近くに家があって。以前に、子供がたくさん欲しいって話したこと、ありましたよね」"

[[dialogue]]
speaker = "アナ"
# 「大家族が住めるような、大きな家でした。あの日、砂浜で一緒に作った大きな家みたいな……」
line = "「大家族が住めるような、大きな家でした。あの日、砂浜で一緒に作った大きな家みたいな……」"

[[dialogue]]
speaker = "unk"
# 世界を平和にして、実現させたい
line = "世界を平和にして、実現させたい"

[[dialogue]]
speaker = "unk"
# 頑張ろう
line = "頑張ろう"

[[dialogue]]
speaker = "アナ"
# 「そうですね。今はまだ学生ですし、リクリエのことも決着がついていませんが……」
line = "「そうですね。今はまだ学生ですし、リクリエのことも決着がついていませんが……」"

[[dialogue]]
speaker = "アナ"
# 「さっきの夢を、本当のことにできたら私も嬉しいです」
line = "「さっきの夢を、本当のことにできたら私も嬉しいです」"

[[dialogue]]
speaker = "unk"
# アナが見た夢を現実にできるよう、俺はこれからも懸命に戦い抜こう。そう誓うのだった──
line = "アナが見た夢を現実にできるよう、俺はこれからも懸命に戦い抜こう。そう誓うのだった──"

[[dialogue]]
speaker = "unk"
# と、ここで終わればいい話。どんな話にもオチはあるのだ。
line = "と、ここで終わればいい話。どんな話にもオチはあるのだ。"

[[dialogue]]
speaker = "アナ"
# 「ちなみに会長。確かに私、子供が大勢欲しいとは言いましたが……まさかサッカーチームができるくらい産ませるとは驚きでした」
line = "「ちなみに会長。確かに私、子供が大勢欲しいとは言いましたが……まさかサッカーチームができるくらい産ませるとは驚きでした」"

[[dialogue]]
speaker = "unk"
# えぇえ！？
line = "えぇえ！？"

[[dialogue]]
speaker = "アナ"
# 「軽く両手を超えていましたよ。でも大丈夫。私は子供が大好きです。愛する人との子なら、いくらでもバッチコイ」
line = "「軽く両手を超えていましたよ。でも大丈夫。私は子供が大好きです。愛する人との子なら、いくらでもバッチコイ」"

[[dialogue]]
speaker = "アナ"
# 「ふふっ♪　どこまでを正夢にしていただけるのでしょうか？　楽しみですね……『あなた』<emoji=heart04>」
line = "「ふふっ♪　どこまでを正夢にしていただけるのでしょうか？　楽しみですね……『あなた』<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ──リクリエだけじゃなく、俺は本当に色々と頑張らなければいけないらしかった。
line = "──リクリエだけじゃなく、俺は本当に色々と頑張らなければいけないらしかった。"

[[dialogue]]
speaker = "unk"
# うん……頑張るぞ……頑張ろう……！
line = "うん……頑張るぞ……頑張ろう……！"
