[[dialogue]]
speaker = "unk"
# 第２話,必殺のふともも,P
line = "第２話,必殺のふともも,P"

[[dialogue]]
speaker = "unk"
# ただのクラスメイトから、放課後デートをする関係へと発展し、今では俺とミルフィーは恋人同士になっていた。
line = "ただのクラスメイトから、放課後デートをする関係へと発展し、今では俺とミルフィーは恋人同士になっていた。"

[[dialogue]]
speaker = "unk"
# そんな恋人のミルフィーを伴い、アリーナを訪れている。
line = "そんな恋人のミルフィーを伴い、アリーナを訪れている。"

[[dialogue]]
speaker = "ミルフィー"
# 「じゃあ、行くよっ。変身！」
line = "「じゃあ、行くよっ。変身！」"

[[dialogue]]
speaker = "ミルフィー"
# 「はい、これがチーパオフォームだよっ」
line = "「はい、これがチーパオフォームだよっ」"

[[dialogue]]
speaker = "unk"
# すごくかわいい！
line = "すごくかわいい！"

[[dialogue]]
speaker = "unk"
# おおおおおーーーっ！
line = "おおおおおーーーっ！"

[[dialogue]]
speaker = "ミルフィー"
# 「もう、大袈裟だよぉ」
line = "「もう、大袈裟だよぉ」"

[[dialogue]]
speaker = "ミルフィー"
# 「でも、今回はかなりのスピード解決だったし、会長くんもゆっくり見る暇なかったよね」
line = "「でも、今回はかなりのスピード解決だったし、会長くんもゆっくり見る暇なかったよね」"

[[dialogue]]
speaker = "ミルフィー"
# 「だから、改めてじっくり見たいって気持ちはわかるんだけど……」
line = "「だから、改めてじっくり見たいって気持ちはわかるんだけど……」"

[[dialogue]]
speaker = "ミルフィー"
# 「でも、どうしてここなの？　会長くんの部屋とか、２人きりになれる場所でよかったのに」
line = "「でも、どうしてここなの？　会長くんの部屋とか、２人きりになれる場所でよかったのに」"

[[dialogue]]
speaker = "unk"
# 他のみんなにも見てもらいたくて
line = "他のみんなにも見てもらいたくて"

[[dialogue]]
speaker = "ミルフィー"
# 「そ、そうなんだ。私は会長くんに見てもらえたら、十分満足なんだけど」
line = "「そ、そうなんだ。私は会長くんに見てもらえたら、十分満足なんだけど」"

[[dialogue]]
speaker = "ヒヨ"
# 「おうおう、いくら恋人同士だからってちぃーっとばかし姐さんにくっつきすぎじゃねえか？」
line = "「おうおう、いくら恋人同士だからってちぃーっとばかし姐さんにくっつきすぎじゃねえか？」"

[[dialogue]]
speaker = "unk"
# 俺を押しのけるようにして割り込んできたのは新星１年の天桐ヒヨだ。
line = "俺を押しのけるようにして割り込んできたのは新星１年の天桐ヒヨだ。"

[[dialogue]]
speaker = "unk"
# ミルフィーとは同じ陸上部の先輩後輩で、ミルフィーを慕いすぎるあまり、俺が彼女の恋人になったと聞いた時には、かなり不満そうにしていた。
line = "ミルフィーとは同じ陸上部の先輩後輩で、ミルフィーを慕いすぎるあまり、俺が彼女の恋人になったと聞いた時には、かなり不満そうにしていた。"

[[dialogue]]
speaker = "ミルフィー"
# 「ヒヨちゃん、落ち着いて……」
line = "「ヒヨちゃん、落ち着いて……」"

[[dialogue]]
speaker = "ヒヨ"
# 「おっと姐さん、それ以上は駄目だぜ。いくら惚れたもん同士とはいえ、ちょいと刺激が強すぎだ」
line = "「おっと姐さん、それ以上は駄目だぜ。いくら惚れたもん同士とはいえ、ちょいと刺激が強すぎだ」"

[[dialogue]]
speaker = "ヒヨ"
# 「会長サンも男だからよ、姐さんみてぇな別嬪さんにそこまで迫られたら、いやらしい目で見ちまうだろ」
line = "「会長サンも男だからよ、姐さんみてぇな別嬪さんにそこまで迫られたら、いやらしい目で見ちまうだろ」"

[[dialogue]]
speaker = "ミルフィー"
# 「そ、そうかな？　会長くんを誘惑するつもりなんてなかったけど……ゆーわく……しちゃってたんだ<emoji=heart04>」
line = "「そ、そうかな？　会長くんを誘惑するつもりなんてなかったけど……ゆーわく……しちゃってたんだ<emoji=heart04>」"

[[dialogue]]
speaker = "ヒヨ"
# 「かーっ！　姐さん姐さん、その目はいけねぇなぁ。もっと会長サンが興奮しちまうぜ」
line = "「かーっ！　姐さん姐さん、その目はいけねぇなぁ。もっと会長サンが興奮しちまうぜ」"

[[dialogue]]
speaker = "カティア"
# 「ちょっと待つです！　魔王様はそんな人じゃないです！　ミルフィー先輩のエッチな格好を見ても絶対興奮なんてしないワン！」
line = "「ちょっと待つです！　魔王様はそんな人じゃないです！　ミルフィー先輩のエッチな格好を見ても絶対興奮なんてしないワン！」"

[[dialogue]]
speaker = "unk"
# どこからともなく現れたのは、ミルフィーの後輩で陸上部１年のカティアだ。
line = "どこからともなく現れたのは、ミルフィーの後輩で陸上部１年のカティアだ。"

[[dialogue]]
speaker = "unk"
# 俺を魔王様と慕う彼女は、事あるごとにヒヨとぶつかっているが、今回も俺を擁護しに来たらしい。
line = "俺を魔王様と慕う彼女は、事あるごとにヒヨとぶつかっているが、今回も俺を擁護しに来たらしい。"

[[dialogue]]
speaker = "ヒヨ"
# 「おいおいワン公、急に出てきたと思えば、おかしなこと言いやがって」
line = "「おいおいワン公、急に出てきたと思えば、おかしなこと言いやがって」"

[[dialogue]]
speaker = "カティア"
# 「魔王様はエッチじゃないワン！」
line = "「魔王様はエッチじゃないワン！」"

[[dialogue]]
speaker = "ヒヨ"
# 「いやいや、会長サンはどこからどう見てもエッチだろ！　こんなドスケベ他に見たことないぜ」
line = "「いやいや、会長サンはどこからどう見てもエッチだろ！　こんなドスケベ他に見たことないぜ」"

[[dialogue]]
speaker = "カティア"
# 「それはっ……ミルフィー先輩のせいだワン！　先輩がエッチだから、魔王様が見ちゃっても仕方ないのです」
line = "「それはっ……ミルフィー先輩のせいだワン！　先輩がエッチだから、魔王様が見ちゃっても仕方ないのです」"

[[dialogue]]
speaker = "ミルフィー"
# 「ええっ、私のせいなの？」
line = "「ええっ、私のせいなの？」"

[[dialogue]]
speaker = "ヒヨ"
# 「言うに事欠いて姐さんを悪者にしようとはとんでもねぇワン公だな」
line = "「言うに事欠いて姐さんを悪者にしようとはとんでもねぇワン公だな」"

[[dialogue]]
speaker = "カティア"
# 「悪者じゃないワン！」
line = "「悪者じゃないワン！」"

[[dialogue]]
speaker = "カティア"
# 「ミルフィー先輩がエッチで……だから魔王様もエッチになっちゃって……でも恋人同士ならそれはいいことなのです！」
line = "「ミルフィー先輩がエッチで……だから魔王様もエッチになっちゃって……でも恋人同士ならそれはいいことなのです！」"

[[dialogue]]
speaker = "ヒヨ"
# 「ダメだダメだ！　いくら恋人同士ってぇ言っても、姐さんと会長サンが……エッチで……そういう風になって……ごにょごにょ……なことしたら……」
line = "「ダメだダメだ！　いくら恋人同士ってぇ言っても、姐さんと会長サンが……エッチで……そういう風になって……ごにょごにょ……なことしたら……」"

[[dialogue]]
speaker = "ヒヨ"
# 「っっ～～～～～～っ！！」
line = "「っっ～～～～～～っ！！」"

[[dialogue]]
speaker = "カティア"
# 「やったぁ、私の勝利だワン！　魔王様～、褒めて褒めて～」
line = "「やったぁ、私の勝利だワン！　魔王様～、褒めて褒めて～」"

[[dialogue]]
speaker = "ヒヨ"
# 「ちょっと待ったぁ！　誰も負けてねぇだろ！　姐さんも何とか言ってくれよ」
line = "「ちょっと待ったぁ！　誰も負けてねぇだろ！　姐さんも何とか言ってくれよ」"

[[dialogue]]
speaker = "ミルフィー"
# 「ええっ、でも何を言ってもエッチだって言われて終わりそうだし……」
line = "「ええっ、でも何を言ってもエッチだって言われて終わりそうだし……」"

[[dialogue]]
speaker = "ミルフィー"
# 「ねえねえ、チアの時は確かにちょっぴりエッチだなぁって思ってたけど、今回のチーパオフォームはそこまでエッチじゃないよね？」
line = "「ねえねえ、チアの時は確かにちょっぴりエッチだなぁって思ってたけど、今回のチーパオフォームはそこまでエッチじゃないよね？」"

[[dialogue]]
speaker = "カティア"
# 「エッチなのです」
line = "「エッチなのです」"

[[dialogue]]
speaker = "ヒヨ"
# 「すまねぇ、姐さん。いくらフォローしたくても、自分に嘘はつけねぇ」
line = "「すまねぇ、姐さん。いくらフォローしたくても、自分に嘘はつけねぇ」"

[[dialogue]]
speaker = "ヒヨ"
# 「姐さんのチーパオフォームは……めちゃくちゃエッチだぜ」
line = "「姐さんのチーパオフォームは……めちゃくちゃエッチだぜ」"

[[dialogue]]
speaker = "ミルフィー"
# 「ええ～～っ！？　だってだって、チアほど露出度も高くないよ？」
line = "「ええ～～っ！？　だってだって、チアほど露出度も高くないよ？」"

[[dialogue]]
speaker = "ヒヨ"
# 「世の中にはチラリズムってぇもんがあるんだ。そんで会長サンはそういうのが大好物と来てる」
line = "「世の中にはチラリズムってぇもんがあるんだ。そんで会長サンはそういうのが大好物と来てる」"

[[dialogue]]
speaker = "カティア"
# 「ちらちら見えるふとももが、とてもエッチなのです」
line = "「ちらちら見えるふとももが、とてもエッチなのです」"

[[dialogue]]
speaker = "ミルフィー"
# 「そうだったんだ……確かに会長くんも、太股のあたりを見てた気がするけど……」
line = "「そうだったんだ……確かに会長くんも、太股のあたりを見てた気がするけど……」"

[[dialogue]]
speaker = "unk"
# スリットからチラ見えするふとももは正義
line = "スリットからチラ見えするふとももは正義"

[[dialogue]]
speaker = "unk"
# ミルフィーのむちむちなふとももが好き
line = "ミルフィーのむちむちなふとももが好き"

[[dialogue]]
speaker = "ミルフィー"
# 「そっかぁ……会長くんから見てもエッチだったんだ……」
line = "「そっかぁ……会長くんから見てもエッチだったんだ……」"

[[dialogue]]
speaker = "ヒヨ"
# 「だからあんま会長サンの前で激しい動きはしない方がいいぜ。ライオンの檻に餌を投げ入れるようなもんだ」
line = "「だからあんま会長サンの前で激しい動きはしない方がいいぜ。ライオンの檻に餌を投げ入れるようなもんだ」"

[[dialogue]]
speaker = "カティア"
# 「そんなことないワン！　確かにミルフィー先輩はエッチだけど、魔王様はその程度じゃ動じないのです！」
line = "「そんなことないワン！　確かにミルフィー先輩はエッチだけど、魔王様はその程度じゃ動じないのです！」"

[[dialogue]]
speaker = "ヒヨ"
# 「ほほう、言うじゃねぇか。よーし、わかった。姐さん、ちょいと試してくれよ。その最高のふとももをちらりとするだけでいいから」
line = "「ほほう、言うじゃねぇか。よーし、わかった。姐さん、ちょいと試してくれよ。その最高のふとももをちらりとするだけでいいから」"

[[dialogue]]
speaker = "ミルフィー"
# 「そ、そんなこと言われても……困ったなぁ……」
line = "「そ、そんなこと言われても……困ったなぁ……」"

[[dialogue]]
speaker = "ミルフィー"
# （でもでもっ、会長くんがドキドキしてくれるなら……いいかも<emoji=heart04>）
line = "（でもでもっ、会長くんがドキドキしてくれるなら……いいかも<emoji=heart04>）"

[[dialogue]]
speaker = "ミルフィー"
# 「じゃあ、行くよ……」
line = "「じゃあ、行くよ……」"

[[dialogue]]
speaker = "ミルフィー"
# 「……………………ちらっ<emoji=heart04>」
line = "「……………………ちらっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ありがとうございます！！！
line = "ありがとうございます！！！"

[[dialogue]]
speaker = "unk"
# うおおおおおおおーーーーーーっ！！！
line = "うおおおおおおおーーーーーーっ！！！"

[[dialogue]]
speaker = "ミルフィー"
# 「……あれ？　もしかしてやり過ぎちゃった？」
line = "「……あれ？　もしかしてやり過ぎちゃった？」"

[[dialogue]]
speaker = "ヒヨ"
# 「姐さん……だから言わんこっちゃない……」
line = "「姐さん……だから言わんこっちゃない……」"

[[dialogue]]
speaker = "カティア"
# 「いくら魔王様でも無理なのです。エッチすぎるのです」
line = "「いくら魔王様でも無理なのです。エッチすぎるのです」"

[[dialogue]]
speaker = "ミルフィー"
# 「さすがにそこまでは……って、会長くん？　ねえちょっと！　もしかして気絶しちゃってる！？」
line = "「さすがにそこまでは……って、会長くん？　ねえちょっと！　もしかして気絶しちゃってる！？」"

[[dialogue]]
speaker = "ヒヨ"
# 「さすがは姐さん……必殺のふとももだぜ……」
line = "「さすがは姐さん……必殺のふとももだぜ……」"

[[dialogue]]
speaker = "カティア"
# 「こればっかりは私も同意見なのです……」
line = "「こればっかりは私も同意見なのです……」"

[[dialogue]]
speaker = "unk"
# こうして、ミルフィーの必殺のふとももにより、俺はしばらく気を失い続けるのだった。
line = "こうして、ミルフィーの必殺のふとももにより、俺はしばらく気を失い続けるのだった。"
