[[dialogue]]
speaker = "unk"
# 第３話,パスタは折るな！,P
line = "第３話,パスタは折るな！,P"

[[dialogue]]
speaker = "イレーナ"
# 「あくまで仮定の話。もしもの話なんだけど……」
line = "「あくまで仮定の話。もしもの話なんだけど……」"

[[dialogue]]
speaker = "イレーナ"
# 「もしあたしとあんたがけ、けけけけ、け……」
line = "「もしあたしとあんたがけ、けけけけ、け……」"

[[dialogue]]
speaker = "unk"
# 結婚
line = "結婚"

[[dialogue]]
speaker = "イレーナ"
# 「さらっと言うなぁ～～～っ！！」
line = "「さらっと言うなぁ～～～っ！！」"

[[dialogue]]
speaker = "イレーナ"
# 「ま、まぁ、恥ずかしがってても仕方ないわね……」
line = "「ま、まぁ、恥ずかしがってても仕方ないわね……」"

[[dialogue]]
speaker = "イレーナ"
# 「も、もしあたしとあんたが本当に結婚して、一緒に暮らすなら、約束してほしいことがいくつかあるの。特に食事に関してね」
line = "「も、もしあたしとあんたが本当に結婚して、一緒に暮らすなら、約束してほしいことがいくつかあるの。特に食事に関してね」"

[[dialogue]]
speaker = "イレーナ"
# 「まず──」
line = "「まず──」"

[[dialogue]]
speaker = "イレーナ"
# 「パスタは折るな！！」
line = "「パスタは折るな！！」"

[[dialogue]]
speaker = "unk"
# イタリア人のこだわり！
line = "イタリア人のこだわり！"

[[dialogue]]
speaker = "イレーナ"
# 「当然よ。あんただって、フライにされた寿司が出てきたら思うところあるでしょ」
line = "「当然よ。あんただって、フライにされた寿司が出てきたら思うところあるでしょ」"

[[dialogue]]
speaker = "イレーナ"
# 「この国の食事のレベルは高いと思うし、美味しいイタリア料理だってあるわ。それでも気になることはあるのよ」
line = "「この国の食事のレベルは高いと思うし、美味しいイタリア料理だってあるわ。それでも気になることはあるのよ」"

[[dialogue]]
speaker = "イレーナ"
# 「さっきも言った通り、パスタは折らない！」
line = "「さっきも言った通り、パスタは折らない！」"

[[dialogue]]
speaker = "イレーナ"
# 「というかパスタじゃなくてスパゲッティでしょ。フェットチーネとかリガトーニとかいろいろなパスタの種類があるのに、スパゲッティのことをパスタって呼ぶのどうかと思うわ」
line = "「というかパスタじゃなくてスパゲッティでしょ。フェットチーネとかリガトーニとかいろいろなパスタの種類があるのに、スパゲッティのことをパスタって呼ぶのどうかと思うわ」"

[[dialogue]]
speaker = "イレーナ"
# 「カルボナーラにはベーコンじゃなくてグアンチャーレ！　グアンチャーレってのは、豚の頬肉の塩漬けのことよ」
line = "「カルボナーラにはベーコンじゃなくてグアンチャーレ！　グアンチャーレってのは、豚の頬肉の塩漬けのことよ」"

[[dialogue]]
speaker = "イレーナ"
# 「それに生クリームも使わない！　チーズと卵！　そして本物はペコリーノロマーノを使うの。羊の乳で作ったチーズね」
line = "「それに生クリームも使わない！　チーズと卵！　そして本物はペコリーノロマーノを使うの。羊の乳で作ったチーズね」"

[[dialogue]]
speaker = "イレーナ"
# 「あとピザとピッツァは別物！」
line = "「あとピザとピッツァは別物！」"

[[dialogue]]
speaker = "イレーナ"
# 「そしてケチャップは邪道！　ナポリタンは邪教！」
line = "「そしてケチャップは邪道！　ナポリタンは邪教！」"

[[dialogue]]
speaker = "イレーナ"
# 「あたしはあれをスパゲッティとは認めない！！　たとえ美味しくても別物！！　いいわね？」
line = "「あたしはあれをスパゲッティとは認めない！！　たとえ美味しくても別物！！　いいわね？」"

[[dialogue]]
speaker = "unk"
# わかった
line = "わかった"

[[dialogue]]
speaker = "イレーナ"
# 「わかればいいのよ」
line = "「わかればいいのよ」"

[[dialogue]]
speaker = "unk"
# じゃあ本場のイタリア料理を教えて
line = "じゃあ本場のイタリア料理を教えて"

[[dialogue]]
speaker = "イレーナ"
# 「え──？」
line = "「え──？」"

[[dialogue]]
speaker = "イレーナ"
# 「ええっと……それは無理かも……」
line = "「ええっと……それは無理かも……」"

[[dialogue]]
speaker = "イレーナ"
# 「偉そうに言っちゃったけど、特別料理が得意なわけじゃないし、自分で作れるわけじゃないのよね……あと手に入りにくい材料もあるし」
line = "「偉そうに言っちゃったけど、特別料理が得意なわけじゃないし、自分で作れるわけじゃないのよね……あと手に入りにくい材料もあるし」"

[[dialogue]]
speaker = "イレーナ"
# 「え？　一緒に作ってみる……？　それならできるかもしれないわね……」
line = "「え？　一緒に作ってみる……？　それならできるかもしれないわね……」"

[[dialogue]]
speaker = "unk"
# それから数日後。
line = "それから数日後。"

[[dialogue]]
speaker = "unk"
# サランにも協力してもらって本場イタリアの食材を揃え、２人で料理を作ることになった。
line = "サランにも協力してもらって本場イタリアの食材を揃え、２人で料理を作ることになった。"

[[dialogue]]
speaker = "イレーナ"
# 「さすがにピッツァは釜がないと作れないし、カルボナーラにしましょ」
line = "「さすがにピッツァは釜がないと作れないし、カルボナーラにしましょ」"

[[dialogue]]
speaker = "イレーナ"
# 「なんでウェディングフォームで料理するのかって？　別にいいじゃない、減るものじゃなし」
line = "「なんでウェディングフォームで料理するのかって？　別にいいじゃない、減るものじゃなし」"

[[dialogue]]
speaker = "イレーナ"
# 「それに……ちょっとは気分を味わいたいのよ。それくらい察しなさいっ」
line = "「それに……ちょっとは気分を味わいたいのよ。それくらい察しなさいっ」"

[[dialogue]]
speaker = "イレーナ"
# 「あ～もうこの話終わり！　さっさと始めるわよ！」
line = "「あ～もうこの話終わり！　さっさと始めるわよ！」"

[[dialogue]]
speaker = "イレーナ"
# 「材料はグアンチャーレ、卵、ペコリーノロマーノ、ブラックペッパー……以上！　余計なものは入れないわよ」
line = "「材料はグアンチャーレ、卵、ペコリーノロマーノ、ブラックペッパー……以上！　余計なものは入れないわよ」"

[[dialogue]]
speaker = "イレーナ"
# 「カルボナーラはショートパスタで作る時もあるけど、今日はスパゲッティにするわ」
line = "「カルボナーラはショートパスタで作る時もあるけど、今日はスパゲッティにするわ」"

[[dialogue]]
speaker = "イレーナ"
# 「まずはスパゲッティを茹でましょう。もちろん折らずに茹でられる鍋を使ってね」
line = "「まずはスパゲッティを茹でましょう。もちろん折らずに茹でられる鍋を使ってね」"

[[dialogue]]
speaker = "イレーナ"
# 「その間にグアンチャーレをフライパンで焼いてカリカリにして……あ、ソースはあんたがお願い。ペコリーノと卵黄を混ぜるの」
line = "「その間にグアンチャーレをフライパンで焼いてカリカリにして……あ、ソースはあんたがお願い。ペコリーノと卵黄を混ぜるの」"

[[dialogue]]
speaker = "unk"
# スパゲッティが茹で上がってきたら、少量の茹で汁をフライパンに入れて、グアンチャーレから出てきた脂と乳化させる。
line = "スパゲッティが茹で上がってきたら、少量の茹で汁をフライパンに入れて、グアンチャーレから出てきた脂と乳化させる。"

[[dialogue]]
speaker = "unk"
# そしてスパゲッティを入れて、最後にソースを投入する。
line = "そしてスパゲッティを入れて、最後にソースを投入する。"

[[dialogue]]
speaker = "イレーナ"
# 「ここで加熱しすぎると卵が固まっちゃうのよね……スパゲッティ全体に絡むように手早く混ぜて……」
line = "「ここで加熱しすぎると卵が固まっちゃうのよね……スパゲッティ全体に絡むように手早く混ぜて……」"

[[dialogue]]
speaker = "イレーナ"
# 「盛り付けて、ブラックペッパーをかけたら完成ね！」
line = "「盛り付けて、ブラックペッパーをかけたら完成ね！」"

[[dialogue]]
speaker = "unk"
# すごく美味しそうだ
line = "すごく美味しそうだ"

[[dialogue]]
speaker = "イレーナ"
# 「そうね……見た目はイタリアで食べたカルボナーラと同じだわ」
line = "「そうね……見た目はイタリアで食べたカルボナーラと同じだわ」"

[[dialogue]]
speaker = "イレーナ"
# 「それじゃ……あ、あ～ん」
line = "「それじゃ……あ、あ～ん」"

[[dialogue]]
speaker = "イレーナ"
# 「……何驚いてんのよ。恋人なんだからこれくらいするでしょ。せっかくこんなかっこしてるんだし」
line = "「……何驚いてんのよ。恋人なんだからこれくらいするでしょ。せっかくこんなかっこしてるんだし」"

[[dialogue]]
speaker = "イレーナ"
# 「それより味の方はどうなの？　食べて聞かせてよ。……はい、あ～ん」
line = "「それより味の方はどうなの？　食べて聞かせてよ。……はい、あ～ん」"

[[dialogue]]
speaker = "unk"
# すごく濃厚で美味しい！
line = "すごく濃厚で美味しい！"

[[dialogue]]
speaker = "イレーナ"
# 「ふふ、それなら良かった。わざわざイタリアの食材を揃えた甲斐があったわね」
line = "「ふふ、それなら良かった。わざわざイタリアの食材を揃えた甲斐があったわね」"

[[dialogue]]
speaker = "unk"
# それじゃ俺からも……あ～ん
line = "それじゃ俺からも……あ～ん"

[[dialogue]]
speaker = "イレーナ"
# 「あ、あ～ん」
line = "「あ、あ～ん」"

[[dialogue]]
speaker = "イレーナ"
# 「ん～っ♪　これよこれ！　これぞ本場のカルボナーラよ！」
line = "「ん～っ♪　これよこれ！　これぞ本場のカルボナーラよ！」"

[[dialogue]]
speaker = "イレーナ"
# 「それじゃもう一度……あ～ん。あたしが食べさせてあげてるんだから、味わって食べなさい」
line = "「それじゃもう一度……あ～ん。あたしが食べさせてあげてるんだから、味わって食べなさい」"

[[dialogue]]
speaker = "イレーナ"
# 「あたし１人でちゃんと作れるようになったら、また作ってあげる」
line = "「あたし１人でちゃんと作れるようになったら、また作ってあげる」"

[[dialogue]]
speaker = "イレーナ"
# 「パスタも、ピッツァも、ドルチェも、あたしの故郷の味をたくさん教えてあげるんだから♪」
line = "「パスタも、ピッツァも、ドルチェも、あたしの故郷の味をたくさん教えてあげるんだから♪」"
