[[dialogue]]
speaker = "unk"
# 第３話,セーラの夢？,P
line = "第３話,セーラの夢？,P"

[[dialogue]]
speaker = "セーラ"
# 「ミーティングおっつー。今日もいろいろ案出たけど、もうちょっと詰めていきたいね」
line = "「ミーティングおっつー。今日もいろいろ案出たけど、もうちょっと詰めていきたいね」"

[[dialogue]]
speaker = "ルリエル"
# 「お疲れ様でした～」
line = "「お疲れ様でした～」"

[[dialogue]]
speaker = "セーラ"
# 「ところでさ……うち、将来社長になりたいんだよね」
line = "「ところでさ……うち、将来社長になりたいんだよね」"

[[dialogue]]
speaker = "unk"
# どうしたんですか突然
line = "どうしたんですか突然"

[[dialogue]]
speaker = "セーラ"
# 「うち、かっこいい女になりたいなって前から思ってて。そのイメージが社長なの」
line = "「うち、かっこいい女になりたいなって前から思ってて。そのイメージが社長なの」"

[[dialogue]]
speaker = "セーラ"
# 「自分がトップに立って、自分で決めて。誰にも命令されず、成功も失敗も自分の責任。そういうのかっこいいなって」
line = "「自分がトップに立って、自分で決めて。誰にも命令されず、成功も失敗も自分の責任。そういうのかっこいいなって」"

[[dialogue]]
speaker = "セーラ"
# 「もちろん星騎士としての役目を無事終えて卒業したらの話だけど。うち、星騎士やめたら社長になるんだ……ってやつ？」
line = "「もちろん星騎士としての役目を無事終えて卒業したらの話だけど。うち、星騎士やめたら社長になるんだ……ってやつ？」"

[[dialogue]]
speaker = "unk"
# それはダメなやつです
line = "それはダメなやつです"

[[dialogue]]
speaker = "セーラ"
# 「あはははっ」
line = "「あはははっ」"

[[dialogue]]
speaker = "ルリエル"
# 「女社長・桐原セーラ……いいですねっ！　いしゅーなあぐりーをあじぇんだでこみっとするんですねっ！」
line = "「女社長・桐原セーラ……いいですねっ！　いしゅーなあぐりーをあじぇんだでこみっとするんですねっ！」"

[[dialogue]]
speaker = "ルリエル"
# 「ガッポガッポ稼いでギロッポンにオフィスを構えて、シャンパン片手に大都会の夜景を眺めちゃいましょお～！」
line = "「ガッポガッポ稼いでギロッポンにオフィスを構えて、シャンパン片手に大都会の夜景を眺めちゃいましょお～！」"

[[dialogue]]
speaker = "セーラ"
# 「そうそう、目指せ億万長者！　お札の風呂で泳いでやるぜ～！」
line = "「そうそう、目指せ億万長者！　お札の風呂で泳いでやるぜ～！」"

[[dialogue]]
speaker = "ルリエル"
# 「ロマンですぅ～！」
line = "「ロマンですぅ～！」"

[[dialogue]]
speaker = "セーラ"
# 「とまぁ、ギラついた野望はさておき、どんな事業がいいか一緒に考えてくんない？　冗談半分でいいからさ」
line = "「とまぁ、ギラついた野望はさておき、どんな事業がいいか一緒に考えてくんない？　冗談半分でいいからさ」"

[[dialogue]]
speaker = "unk"
# やっぱり好きなものとか？
line = "やっぱり好きなものとか？"

[[dialogue]]
speaker = "セーラ"
# 「うちの好きなものかー……ネイル、コスメ、アクセ……ま、イメージはできるね。特色のある商品を作れれば事業になりそう」
line = "「うちの好きなものかー……ネイル、コスメ、アクセ……ま、イメージはできるね。特色のある商品を作れれば事業になりそう」"

[[dialogue]]
speaker = "ルリエル"
# 「はいはーいっ。セーラ先輩なら水着になればいいと思いまーすっ！　うっふ、あっはーんで世の男性方にヒット間違いなしですっ！」
line = "「はいはーいっ。セーラ先輩なら水着になればいいと思いまーすっ！　うっふ、あっはーんで世の男性方にヒット間違いなしですっ！」"

[[dialogue]]
speaker = "セーラ"
# 「それ社長の仕事じゃないっしょ！」
line = "「それ社長の仕事じゃないっしょ！」"

[[dialogue]]
speaker = "ルリエル"
# 「あ、そうでしたっ」
line = "「あ、そうでしたっ」"

[[dialogue]]
speaker = "セーラ"
# 「もう、ルリちーってば～。でも需要は大事だよね。潜在的に必要とされているものを発見できれば──」
line = "「もう、ルリちーってば～。でも需要は大事だよね。潜在的に必要とされているものを発見できれば──」"

[[dialogue]]
speaker = "セーラ"
# 「あっ！　ゲームのイベント始まってたの忘れてた！　ごめんちょっと触っていい？」
line = "「あっ！　ゲームのイベント始まってたの忘れてた！　ごめんちょっと触っていい？」"

[[dialogue]]
speaker = "セーラ"
# 「あー、よかったー、スタミナ漏れてない。うち無課金プレイだから、できるだけムダなくやりたいんだよねー」
line = "「あー、よかったー、スタミナ漏れてない。うち無課金プレイだから、できるだけムダなくやりたいんだよねー」"

[[dialogue]]
speaker = "ルリエル"
# 「えーっと、何かの漫画とコラボ？　しててそこから始めたんでしたっけ。流星学園でもやってるのたまに見るのです」
line = "「えーっと、何かの漫画とコラボ？　しててそこから始めたんでしたっけ。流星学園でもやってるのたまに見るのです」"

[[dialogue]]
speaker = "セーラ"
# 「そうそう。今日のイベントのために石貯めといたから、今回の目玉キャラはこれで引けるはず……」
line = "「そうそう。今日のイベントのために石貯めといたから、今回の目玉キャラはこれで引けるはず……」"

[[dialogue]]
speaker = "セーラ"
# 「あ～っ！？　石が溶ける～！　らめ～っ！」
line = "「あ～っ！？　石が溶ける～！　らめ～っ！」"

[[dialogue]]
speaker = "セーラ"
# 「くぅ～っ……あー、ダメ……レア度高いのは当たるけど、欲しいのが引けない……。課金しちゃおっかなぁ……あと少し、あと少しだけ回せば出る気がする……」
line = "「くぅ～っ……あー、ダメ……レア度高いのは当たるけど、欲しいのが引けない……。課金しちゃおっかなぁ……あと少し、あと少しだけ回せば出る気がする……」"

[[dialogue]]
speaker = "unk"
# 気のせいだと思います
line = "気のせいだと思います"

[[dialogue]]
speaker = "セーラ"
# 「わかる」
line = "「わかる」"

[[dialogue]]
speaker = "セーラ"
# 「でも課金して引けたらめっちゃ気持ちいいと思うんだよねー」
line = "「でも課金して引けたらめっちゃ気持ちいいと思うんだよねー」"

[[dialogue]]
speaker = "unk"
# わかる
line = "わかる"

[[dialogue]]
speaker = "セーラ"
# 「どうするか人生初課金……でも欲しい本あるからお金使うのはなー……」
line = "「どうするか人生初課金……でも欲しい本あるからお金使うのはなー……」"

[[dialogue]]
speaker = "セーラ"
# 「待てよ～、まだ受け取ってないミッションの石をかき集めれば……よし！　あともうちょっと回せる！」
line = "「待てよ～、まだ受け取ってないミッションの石をかき集めれば……よし！　あともうちょっと回せる！」"

[[dialogue]]
speaker = "セーラ"
# 「会長さん、回してもらっていい？　あ、そんなビビんなくていいから。ゲン担ぎみたいなもんだし、ダメ元だからさ」
line = "「会長さん、回してもらっていい？　あ、そんなビビんなくていいから。ゲン担ぎみたいなもんだし、ダメ元だからさ」"

[[dialogue]]
speaker = "セーラ"
# 「会長さんの指を借りたいの。先っぽだけでいいから。ちょーっと触るだけだから。お願い！」
line = "「会長さんの指を借りたいの。先っぽだけでいいから。ちょーっと触るだけだから。お願い！」"

[[dialogue]]
speaker = "ルリエル"
# 「はいっ！　ここは天使ルリエルが華麗に引き当ててみせますぅ！」
line = "「はいっ！　ここは天使ルリエルが華麗に引き当ててみせますぅ！」"

[[dialogue]]
speaker = "セーラ"
# 「ルリちーはこの前大爆死だったからダメ」
line = "「ルリちーはこの前大爆死だったからダメ」"

[[dialogue]]
speaker = "ルリエル"
# 「あぅっ」
line = "「あぅっ」"

[[dialogue]]
speaker = "セーラ"
# 「会長さんお願いっ！　先っぽっでツンってするだけ！　ちょっとだけだから！　……いい？　じゃあここ押してみて」
line = "「会長さんお願いっ！　先っぽっでツンってするだけ！　ちょっとだけだから！　……いい？　じゃあここ押してみて」"

[[dialogue]]
speaker = "セーラ"
# 「来い……来い……」
line = "「来い……来い……」"

[[dialogue]]
speaker = "セーラ"
# 「やった～～！！」
line = "「やった～～！！」"

[[dialogue]]
speaker = "セーラ"
# 「ほんっとありがと！　神の指先だね！」
line = "「ほんっとありがと！　神の指先だね！」"

[[dialogue]]
speaker = "セーラ"
# 「あ……近かったね……ごめん。あはは、ちょっとはしゃぎすぎたかな……まぁ、今度何かお礼させて。ね？」
line = "「あ……近かったね……ごめん。あはは、ちょっとはしゃぎすぎたかな……まぁ、今度何かお礼させて。ね？」"

[[dialogue]]
speaker = "セーラ"
# 「って、何の話してたんだっけ？」
line = "「って、何の話してたんだっけ？」"

[[dialogue]]
speaker = "セーラ"
# 「そうだ、会社の話だった。じゃ、また今度意見聞かせてね～っ」
line = "「そうだ、会社の話だった。じゃ、また今度意見聞かせてね～っ」"
