[[dialogue]]
speaker = "unk"
# クラウディア・イルゼ・フォン・ゴットフリート。
line = "クラウディア・イルゼ・フォン・ゴットフリート。"

[[dialogue]]
speaker = "unk"
# ネビュラと名乗る謎多き組織の総帥だ。
line = "ネビュラと名乗る謎多き組織の総帥だ。"

[[dialogue]]
speaker = "unk"
# ネビュラは俺たち新星星徒会と、味方とも敵とも言えない微妙な関係にあったのだが……
line = "ネビュラは俺たち新星星徒会と、味方とも敵とも言えない微妙な関係にあったのだが……"

[[dialogue]]
speaker = "クラウディア"
# 「ふ、ふんっ。高貴な余を辱めるような格好をさせるとは……んんっ、今日はいったい、どういう趣向なのだ？　……はぁぁっ」
line = "「ふ、ふんっ。高貴な余を辱めるような格好をさせるとは……んんっ、今日はいったい、どういう趣向なのだ？　……はぁぁっ」"

[[dialogue]]
speaker = "クラウディア"
# 「そんな風に余を持ち上げて……はふぅっ。そそり立ったイチモツを見せつけたところで、余は決してち○ぽに屈したりせぬぞ！　……ふぅぅっ」
line = "「そんな風に余を持ち上げて……はふぅっ。そそり立ったイチモツを見せつけたところで、余は決してち○ぽに屈したりせぬぞ！　……ふぅぅっ」"

[[dialogue]]
speaker = "unk"
# いつの間にか、みんなに内緒でエッチなことをする関係になってしまっていた。
line = "いつの間にか、みんなに内緒でエッチなことをする関係になってしまっていた。"

[[dialogue]]
speaker = "unk"
# 『子作り』はどうするのかと熱心に聞いてきたクラウディア。あれに大真面目に答えてしまったのがよくなかった。
line = "『子作り』はどうするのかと熱心に聞いてきたクラウディア。あれに大真面目に答えてしまったのがよくなかった。"

[[dialogue]]
speaker = "クラウディア"
# 「む──何？　どこでそんな言葉を覚えたかと？　ふふ……乙女の教典に決まっておる」
line = "「む──何？　どこでそんな言葉を覚えたかと？　ふふ……乙女の教典に決まっておる」"

[[dialogue]]
speaker = "クラウディア"
# 「ふふん？　勢いづいて始めたはいいが……はぁぁっ。さすがの貴様も、余をこれ以上辱めるのは、躊躇いがあると見える……んんっ」
line = "「ふふん？　勢いづいて始めたはいいが……はぁぁっ。さすがの貴様も、余をこれ以上辱めるのは、躊躇いがあると見える……んんっ」"

[[dialogue]]
speaker = "クラウディア"
# 「よいぞ。今なら今日の無礼はすべて許そう。……余の体をベッドに下ろし、余の足に忠誠のキスをするなら、無様にそそり立った貴様のち○ぽを余のおま○こで慰めてやろうっ」
line = "「よいぞ。今なら今日の無礼はすべて許そう。……余の体をベッドに下ろし、余の足に忠誠のキスをするなら、無様にそそり立った貴様のち○ぽを余のおま○こで慰めてやろうっ」"

[[dialogue]]
speaker = "unk"
# 「慰めてやる」なんて上から目線で言うクラウディアだったが、その女性器は羞恥心と興奮ですっかり濡れそぼっていた。
line = "「慰めてやる」なんて上から目線で言うクラウディアだったが、その女性器は羞恥心と興奮ですっかり濡れそぼっていた。"

[[dialogue]]
speaker = "クラウディア"
# 「はぁぁ……ほれ、早くしろ。余の気が変わらんうちにな。……今日の余は機嫌がいい。今なららぶらぶな雰囲気で可愛がってやるぞ？」
line = "「はぁぁ……ほれ、早くしろ。余の気が変わらんうちにな。……今日の余は機嫌がいい。今なららぶらぶな雰囲気で可愛がってやるぞ？」"

[[dialogue]]
speaker = "unk"
# まるで俺がそれを望んでるかのような口調で、自分のしてほしいエッチをおねだりするクラウディア。
line = "まるで俺がそれを望んでるかのような口調で、自分のしてほしいエッチをおねだりするクラウディア。"

[[dialogue]]
speaker = "unk"
# だけど、未挿入のペニスに伝う愛液の量で、彼女の我慢の方が限界なのは丸わかりだった。
line = "だけど、未挿入のペニスに伝う愛液の量で、彼女の我慢の方が限界なのは丸わかりだった。"

[[dialogue]]
speaker = "unk"
# 俺は愛液で濡れ濡れの膣口をペニスで焦らすようにこすって、すっかり可愛い顔になってしまったクラウディアに意地悪を言う。
line = "俺は愛液で濡れ濡れの膣口をペニスで焦らすようにこすって、すっかり可愛い顔になってしまったクラウディアに意地悪を言う。"

[[dialogue]]
speaker = "クラウディア"
# 「我慢できなくなってるのは余のほう──だと？　んんっ……そんなわけがなかろうっ」
line = "「我慢できなくなってるのは余のほう──だと？　んんっ……そんなわけがなかろうっ」"

[[dialogue]]
speaker = "クラウディア"
# 「はぁ……貴様、最近余が目をかけてやっているから、調子に乗っているな？　……んんぅ」
line = "「はぁ……貴様、最近余が目をかけてやっているから、調子に乗っているな？　……んんぅ」"

[[dialogue]]
speaker = "クラウディア"
# 「はぁ、はぁっ……なんだ……？　貴様のそれを、そんな風にこすりつけてきて」
line = "「はぁ、はぁっ……なんだ……？　貴様のそれを、そんな風にこすりつけてきて」"

[[dialogue]]
speaker = "クラウディア"
# 「まさか、貴様のち○ぽ程度で、余を屈服させるつもりか？　ははっ、無理に決まっておろう。ザコめ<emoji=heart04>」
line = "「まさか、貴様のち○ぽ程度で、余を屈服させるつもりか？　ははっ、無理に決まっておろう。ザコめ<emoji=heart04>」"

[[dialogue]]
speaker = "クラウディア"
# 「んくぅぅ……！　はっ、あああああっ……！」
line = "「んくぅぅ……！　はっ、あああああっ……！」"

[[dialogue]]
speaker = "クラウディア"
# 「そ、そんなっ！　ば、馬鹿者──あんっ……きゅ、急に入れたり、しゅりゅなぁ……っ。んんんっ」
line = "「そ、そんなっ！　ば、馬鹿者──あんっ……きゅ、急に入れたり、しゅりゅなぁ……っ。んんんっ」"

[[dialogue]]
speaker = "クラウディア"
# 「あふぅ……ゆっくり、余の体を持ち上げて……んんっ。勃起したち○ぽに、串刺しにする、などぉ……くふぅっ」
line = "「あふぅ……ゆっくり、余の体を持ち上げて……んんっ。勃起したち○ぽに、串刺しにする、などぉ……くふぅっ」"

[[dialogue]]
speaker = "クラウディア"
# 「これではまるで……はぁぁっ。貴様が余の体を、おなほーるにしているようでは、んんっ……ないかぁっ。はふぅぅっ」
line = "「これではまるで……はぁぁっ。貴様が余の体を、おなほーるにしているようでは、んんっ……ないかぁっ。はふぅぅっ」"

[[dialogue]]
speaker = "unk"
# 本当に、どこでそんな言葉を覚えたのか──
line = "本当に、どこでそんな言葉を覚えたのか──"

[[dialogue]]
speaker = "unk"
# 彼女の体を上下に揺すって性器を擦り合わせるたび、じゅぷじゅぷと愛液があふれてくる。
line = "彼女の体を上下に揺すって性器を擦り合わせるたび、じゅぷじゅぷと愛液があふれてくる。"

[[dialogue]]
speaker = "unk"
# この一見気の強そうなお姫様は、羞恥心や屈辱感で気持ちよくなってしまう性癖の持ち主だった。
line = "この一見気の強そうなお姫様は、羞恥心や屈辱感で気持ちよくなってしまう性癖の持ち主だった。"

[[dialogue]]
speaker = "クラウディア"
# 「屈辱的、だぞ……んんっ。はぁんっ。か、感じてなどおらん！　ふぅっ、これは性感帯を弄られた……せ、生理現象だっ！」
line = "「屈辱的、だぞ……んんっ。はぁんっ。か、感じてなどおらん！　ふぅっ、これは性感帯を弄られた……せ、生理現象だっ！」"

[[dialogue]]
speaker = "クラウディア"
# 「はぁぁ……っ。余は自分の体を、おもちゃのように弄ばれて、んふぅ……悦ぶ、変態ではないっ」
line = "「はぁぁ……っ。余は自分の体を、おもちゃのように弄ばれて、んふぅ……悦ぶ、変態ではないっ」"

[[dialogue]]
speaker = "unk"
# 普段なら凛々しく感じるクラウディアの口調も、エッチの最中では嗜虐心をくすぐるスパイスでしかない。
line = "普段なら凛々しく感じるクラウディアの口調も、エッチの最中では嗜虐心をくすぐるスパイスでしかない。"

[[dialogue]]
speaker = "クラウディア"
# 「む……何？　こっ……このままの格好で、ネビュラの基地を歩く──だと……？」
line = "「む……何？　こっ……このままの格好で、ネビュラの基地を歩く──だと……？」"

[[dialogue]]
speaker = "unk"
# そんな意地悪な言葉も、ついつい口にしてしまう。
line = "そんな意地悪な言葉も、ついつい口にしてしまう。"

[[dialogue]]
speaker = "クラウディア"
# 「ひぅぅ……っ。はぁぁっ、んんんっ。余のおま○こが、ち○ぽに串刺しにされたまま……はふぅ……皆の前を歩く、なんてぇ……んふぅぅぅっ」
line = "「ひぅぅ……っ。はぁぁっ、んんんっ。余のおま○こが、ち○ぽに串刺しにされたまま……はふぅ……皆の前を歩く、なんてぇ……んふぅぅぅっ」"

[[dialogue]]
speaker = "unk"
# クラウディアの膣は廊下に飛び出す瞬間を妄想しているのか、キュンキュンとわなないていた。
line = "クラウディアの膣は廊下に飛び出す瞬間を妄想しているのか、キュンキュンとわなないていた。"

[[dialogue]]
speaker = "クラウディア"
# 「くくくっ……んんっ。はぁ……貴様は口ばかり、達者だの。そんなリスキーなこと……ふぅ、貴様にはできまい。……よわよわだのう<emoji=heart04>　ざぁ～こ<emoji=heart04>」
line = "「くくくっ……んんっ。はぁ……貴様は口ばかり、達者だの。そんなリスキーなこと……ふぅ、貴様にはできまい。……よわよわだのう<emoji=heart04>　ざぁ～こ<emoji=heart04>」"

[[dialogue]]
speaker = "クラウディア"
# 「はぁ、あぁんっ……ほれ、どうした？　んんっ……廊下に出ないのか？　はぁぁっ……情けないのぅ～<emoji=heart04>　根性なし<emoji=heart04>　かっこわるすぎ～<emoji=heart04>　……んくぅぅ」
line = "「はぁ、あぁんっ……ほれ、どうした？　んんっ……廊下に出ないのか？　はぁぁっ……情けないのぅ～<emoji=heart04>　根性なし<emoji=heart04>　かっこわるすぎ～<emoji=heart04>　……んくぅぅ」"

[[dialogue]]
speaker = "クラウディア"
# 「やはり貴様が余を屈服させるなど、１０００年早かったのぅ～。んふぅ……よいぞ、このまま余がざこち○ぽから、搾り取ってやる<emoji=heart04>　……はぁぁん」
line = "「やはり貴様が余を屈服させるなど、１０００年早かったのぅ～。んふぅ……よいぞ、このまま余がざこち○ぽから、搾り取ってやる<emoji=heart04>　……はぁぁん」"

[[dialogue]]
speaker = "クラウディア"
# 「んんぅっ……体を拘束して、マウント取ったつもりだったのだろうが……はぁぁ……所詮貴様は、その程度<emoji=heart04>」
line = "「んんぅっ……体を拘束して、マウント取ったつもりだったのだろうが……はぁぁ……所詮貴様は、その程度<emoji=heart04>」"

[[dialogue]]
speaker = "クラウディア"
# 「負けてしまえ<emoji=heart04>　余のおま○こに情けなく精液を出せばよいのだ<emoji=heart04>　あぁっんうっ、軟弱な魔王め……<emoji=heart04>」
line = "「負けてしまえ<emoji=heart04>　余のおま○こに情けなく精液を出せばよいのだ<emoji=heart04>　あぁっんうっ、軟弱な魔王め……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# クラウディアの煽りを聞くたびにペニスがイライラして大きくなる。
line = "クラウディアの煽りを聞くたびにペニスがイライラして大きくなる。"

[[dialogue]]
speaker = "unk"
# クラウディアのおま○こは、まるでそれを喜ぶように一層締め付けを強くしていた。
line = "クラウディアのおま○こは、まるでそれを喜ぶように一層締め付けを強くしていた。"

[[dialogue]]
speaker = "unk"
# だから、俺は彼女の期待に応えるように、じゅぷじゅぷと本気汁で泡立つおま○こ目がけて、ペニスを深くねじ込んだ。
line = "だから、俺は彼女の期待に応えるように、じゅぷじゅぷと本気汁で泡立つおま○こ目がけて、ペニスを深くねじ込んだ。"

[[dialogue]]
speaker = "クラウディア"
# 「んぐぅぅぅ……っ！　はっ、ああぁぁぁんっ。ち○ぽ、おま○こに深くっ……あぁんっ。刺さってりゅうぅぅ……っ」
line = "「んぐぅぅぅ……っ！　はっ、ああぁぁぁんっ。ち○ぽ、おま○こに深くっ……あぁんっ。刺さってりゅうぅぅ……っ」"

[[dialogue]]
speaker = "クラウディア"
# 「はっ、あぁぁんっ。んんっ……お、怒ったのか？　あぁんっ。図星だったのだろう<emoji=heart04>　あんっ……ざこち○ぽ<emoji=heart04>　雑魚め<emoji=heart04>　ば～か<emoji=heart04>　んふぅぅぅ」
line = "「はっ、あぁぁんっ。んんっ……お、怒ったのか？　あぁんっ。図星だったのだろう<emoji=heart04>　あんっ……ざこち○ぽ<emoji=heart04>　雑魚め<emoji=heart04>　ば～か<emoji=heart04>　んふぅぅぅ」"

[[dialogue]]
speaker = "クラウディア"
# 「所詮人間のオスなど……んふぅぅ……っ。余がおま○こで可愛がってやれば……はぁんっ。情けなく精液びゅるびゅるするしか……できないのだ<emoji=heart04>　んんんっ」
line = "「所詮人間のオスなど……んふぅぅ……っ。余がおま○こで可愛がってやれば……はぁんっ。情けなく精液びゅるびゅるするしか……できないのだ<emoji=heart04>　んんんっ」"

[[dialogue]]
speaker = "クラウディア"
# 「ちょろいのぉ<emoji=heart04>　あふぅ……っ。ほれ、出せ、出せ<emoji=heart04>　ざこち○ぽからざこ精子出せ<emoji=heart04>　出せ、出せ、出せっ<emoji=heart04>」
line = "「ちょろいのぉ<emoji=heart04>　あふぅ……っ。ほれ、出せ、出せ<emoji=heart04>　ざこち○ぽからざこ精子出せ<emoji=heart04>　出せ、出せ、出せっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# クラウディアももう余裕がないのか、射精をうながすように口でもおま○こでも激しくペニスを責め立てる。
line = "クラウディアももう余裕がないのか、射精をうながすように口でもおま○こでも激しくペニスを責め立てる。"

[[dialogue]]
speaker = "unk"
# だから俺は──
line = "だから俺は──"

[[dialogue]]
speaker = "クラウディア"
# 「は？　……え？　な、なんで？　なぜ止まるのだ。あと少しで……っ……」
line = "「は？　……え？　な、なんで？　なぜ止まるのだ。あと少しで……っ……」"

[[dialogue]]
speaker = "クラウディア"
# 「～～～～っ。くぅぅぅ、な、何も言っておらん！　とにかく、ち○ぽを止めるでない……っ」
line = "「～～～～っ。くぅぅぅ、な、何も言っておらん！　とにかく、ち○ぽを止めるでない……っ」"

[[dialogue]]
speaker = "unk"
# クラウディアは俺におしっこのポーズを取らされたまま、少しでもおま○こで快感を得ようと情けなく腰をヘコヘコさせる。
line = "クラウディアは俺におしっこのポーズを取らされたまま、少しでもおま○こで快感を得ようと情けなく腰をヘコヘコさせる。"

[[dialogue]]
speaker = "unk"
# しかし、がっちりとももを掴まれているため大して動くこともできず、おま○こは切なそうにひくひくと震えるばかりだった。
line = "しかし、がっちりとももを掴まれているため大して動くこともできず、おま○こは切なそうにひくひくと震えるばかりだった。"

[[dialogue]]
speaker = "クラウディア"
# 「な、何のつもりだ……んんんっ……貴様だって、射精が近かったはず……ふぅぅっ。余にはわかっているのだぞっ」
line = "「な、何のつもりだ……んんんっ……貴様だって、射精が近かったはず……ふぅぅっ。余にはわかっているのだぞっ」"

[[dialogue]]
speaker = "unk"
# そうかもしれないが、生意気ばかり言うメスガキおま○こに、このままご褒美をあげるわけにはいかない。
line = "そうかもしれないが、生意気ばかり言うメスガキおま○こに、このままご褒美をあげるわけにはいかない。"

[[dialogue]]
speaker = "クラウディア"
# 「ふーーっ、ふーーっ……うぅぅ。どうして動かないのだ。ほら、素直になれっ、ざこち○ぽに正直になるのだっ」
line = "「ふーーっ、ふーーっ……うぅぅ。どうして動かないのだ。ほら、素直になれっ、ざこち○ぽに正直になるのだっ」"

[[dialogue]]
speaker = "クラウディア"
# 「素直になるのは余のほう──だと？　うっ、くぅぅっ……ぁっ、はぁんっ<emoji=heart04>」
line = "「素直になるのは余のほう──だと？　うっ、くぅぅっ……ぁっ、はぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "クラウディア"
# 「くぅぅぅっ。……ふぅぅぅぅっ」
line = "「くぅぅぅっ。……ふぅぅぅぅっ」"

[[dialogue]]
speaker = "unk"
# クラウディアのおま○こが、きゅうきゅうとペニスを締めつけてくる。
line = "クラウディアのおま○こが、きゅうきゅうとペニスを締めつけてくる。"

[[dialogue]]
speaker = "unk"
# 俺はその気持ちよさに耐えながら、クラウディアの屈服の瞬間を待った――
line = "俺はその気持ちよさに耐えながら、クラウディアの屈服の瞬間を待った――"

[[dialogue]]
speaker = "クラウディア"
# 「わ、わかった……！　余の負けだ。負けでいい……っ！　本当に雑魚なのは、余のおま○この方だった……んぐぅ、ふぁぁあああぁぁぁっ<emoji=heart04>」
line = "「わ、わかった……！　余の負けだ。負けでいい……っ！　本当に雑魚なのは、余のおま○この方だった……んぐぅ、ふぁぁあああぁぁぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "クラウディア"
# 「んんんんんぅ！　はぁぁっ、あんっ、あんっ、あん……っ。はげしいっ。おち○ぽ<emoji=heart04>　おち○ぽ来てる<emoji=heart04>　余のざこま○こ、気持ちよくされてりゅ……<emoji=heart04>　あああぁぁっ」
line = "「んんんんんぅ！　はぁぁっ、あんっ、あんっ、あん……っ。はげしいっ。おち○ぽ<emoji=heart04>　おち○ぽ来てる<emoji=heart04>　余のざこま○こ、気持ちよくされてりゅ……<emoji=heart04>　あああぁぁっ」"

[[dialogue]]
speaker = "クラウディア"
# 「んああっ……深いっ、激しいぃ……っ。じゅぶじゅぶ、ざこま○こに逞しいおち○ぽっ……あああっ。ちゅきさされてりゅぅ……っ。ふあぁあぁぁっ」
line = "「んああっ……深いっ、激しいぃ……っ。じゅぶじゅぶ、ざこま○こに逞しいおち○ぽっ……あああっ。ちゅきさされてりゅぅ……っ。ふあぁあぁぁっ」"

[[dialogue]]
speaker = "クラウディア"
# 「きもちいい<emoji=heart04>　きもちいいっ<emoji=heart04>　きもちいい……っ<emoji=heart04>　ああああっ、おち○ぽに負けるのきもちいい<emoji=heart04>　ふぁぁぁっ」
line = "「きもちいい<emoji=heart04>　きもちいいっ<emoji=heart04>　きもちいい……っ<emoji=heart04>　ああああっ、おち○ぽに負けるのきもちいい<emoji=heart04>　ふぁぁぁっ」"

[[dialogue]]
speaker = "クラウディア"
# 「こんなことされたら、んんんっ……二度とっ、貴様のおち○ぽに、勝てなくなる<emoji=heart04>　はぁぁぁんっ、ざこメスになりゅぅぅぅ<emoji=heart04>」
line = "「こんなことされたら、んんんっ……二度とっ、貴様のおち○ぽに、勝てなくなる<emoji=heart04>　はぁぁぁんっ、ざこメスになりゅぅぅぅ<emoji=heart04>」"

[[dialogue]]
speaker = "クラウディア"
# 「あっ、あっ、あっ。おち○ぽふくらんできたっ……はぁぁ。わかる、わかる、ぞっ。でる、でるんだな<emoji=heart04>　あぁぁぁあっ」
line = "「あっ、あっ、あっ。おち○ぽふくらんできたっ……はぁぁ。わかる、わかる、ぞっ。でる、でるんだな<emoji=heart04>　あぁぁぁあっ」"

[[dialogue]]
speaker = "クラウディア"
# 「ふわぁぁっ。出して、ざこま○こにザーメン<emoji=heart04>　おち○ぽのつよつよザーメン、中出ししてぇ<emoji=heart04>　……んくぅぅぅっ」
line = "「ふわぁぁっ。出して、ざこま○こにザーメン<emoji=heart04>　おち○ぽのつよつよザーメン、中出ししてぇ<emoji=heart04>　……んくぅぅぅっ」"

[[dialogue]]
speaker = "unk"
# クラウディアの完全に蕩けてしまったエロ可愛い声に、ペニスはすぐに限界を迎えそうになる。
line = "クラウディアの完全に蕩けてしまったエロ可愛い声に、ペニスはすぐに限界を迎えそうになる。"

[[dialogue]]
speaker = "unk"
# 俺はこの快感を１秒でも長く共有したくて、ペニスの根元に力を込めてクラウディアの膣を擦り上げる。
line = "俺はこの快感を１秒でも長く共有したくて、ペニスの根元に力を込めてクラウディアの膣を擦り上げる。"

[[dialogue]]
speaker = "クラウディア"
# 「んっはぁぁぁ……！　子宮、子宮に当たってりゅっ。ああぁああぁっ！　おま○こ気持ちいいっ。もっと、もっとおま○こしてっ。あっ、あっ、あっ！　おま○こ来てりゅっ」
line = "「んっはぁぁぁ……！　子宮、子宮に当たってりゅっ。ああぁああぁっ！　おま○こ気持ちいいっ。もっと、もっとおま○こしてっ。あっ、あっ、あっ！　おま○こ来てりゅっ」"

[[dialogue]]
speaker = "クラウディア"
# 「おち○ぽ<emoji=heart04>　んんんっ、つよつよおち○ぽくる<emoji=heart04>　きて、きて、きてぇ<emoji=heart04>　はぁっ、はっ、はっ、はぁぁぁぁぁんっ。ふぁあぁぁぁ～～っ！」
line = "「おち○ぽ<emoji=heart04>　んんんっ、つよつよおち○ぽくる<emoji=heart04>　きて、きて、きてぇ<emoji=heart04>　はぁっ、はっ、はっ、はぁぁぁぁぁんっ。ふぁあぁぁぁ～～っ！」"

[[dialogue]]
speaker = "クラウディア"
# 「もうダメっ、げんかいっ、イクっ……イク、イク、イク！　イっちゃう！　あっ、あっ、あっ、あ──」
line = "「もうダメっ、げんかいっ、イクっ……イク、イク、イク！　イっちゃう！　あっ、あっ、あっ、あ──」"

[[dialogue]]
speaker = "クラウディア"
# 「イっ……クぅぅぅううぅぅぅううううぅぅぅぅ～～～～～っ！！」
line = "「イっ……クぅぅぅううぅぅぅううううぅぅぅぅ～～～～～っ！！」"

[[dialogue]]
speaker = "クラウディア"
# 「あああっ！　あぁんっ……しゅごぃ。おち○ちん……ふぁぁ、まだびくびくして……んんんぅ」
line = "「あああっ！　あぁんっ……しゅごぃ。おち○ちん……ふぁぁ、まだびくびくして……んんんぅ」"

[[dialogue]]
speaker = "クラウディア"
# 「はぁ……んんんっ、ふぅ。あああっ。……最後の一滴まで、余のおま○この中に、出し切るのだぞ<emoji=heart04>　……んふぅぅ」
line = "「はぁ……んんんっ、ふぅ。あああっ。……最後の一滴まで、余のおま○この中に、出し切るのだぞ<emoji=heart04>　……んふぅぅ」"

[[dialogue]]
speaker = "クラウディア"
# 「あぁんっ……はふぅ。もう、抜いてしまうのか？　余のおま○こは貴様に敗北したのだから……好きにしてよいのだぞ？」
line = "「あぁんっ……はふぅ。もう、抜いてしまうのか？　余のおま○こは貴様に敗北したのだから……好きにしてよいのだぞ？」"

[[dialogue]]
speaker = "クラウディア"
# 「くっくっ──こういった趣向も……なかなか面白いのう。ふう、ふう……危うく心まで屈服してしまいそうだ」
line = "「くっくっ──こういった趣向も……なかなか面白いのう。ふう、ふう……危うく心まで屈服してしまいそうだ」"

[[dialogue]]
speaker = "unk"
# 結局、最後までノリノリだったクラウディア──
line = "結局、最後までノリノリだったクラウディア──"

[[dialogue]]
speaker = "unk"
# 『わからせエッチ』は相当お気に召したみたいだ。
line = "『わからせエッチ』は相当お気に召したみたいだ。"

[[dialogue]]
speaker = "unk"
# いつになくトロンと蕩けた声でクラウディアは甘えてくる。
line = "いつになくトロンと蕩けた声でクラウディアは甘えてくる。"

[[dialogue]]
speaker = "unk"
# その様子を見て、またペニスが固さを取り戻してきた。
line = "その様子を見て、またペニスが固さを取り戻してきた。"

[[dialogue]]
speaker = "クラウディア"
# 「んっ、はぁぁ……。全然余裕そうじゃな<emoji=heart04>　ほれ、そのつよつよわからせおち○ぽで、もっと余のざこま○こをを犯すのだ<emoji=heart04>」
line = "「んっ、はぁぁ……。全然余裕そうじゃな<emoji=heart04>　ほれ、そのつよつよわからせおち○ぽで、もっと余のざこま○こをを犯すのだ<emoji=heart04>」"

[[dialogue]]
speaker = "クラウディア"
# 「貴様のち○ぽのイライラが収まるまで、思う存分『ざあめん』を吐き出すのだぞ<emoji=heart04>」
line = "「貴様のち○ぽのイライラが収まるまで、思う存分『ざあめん』を吐き出すのだぞ<emoji=heart04>」"
