[[dialogue]]
speaker = "unk"
# 第３話,エルゼとフィオナ,P
line = "第３話,エルゼとフィオナ,P"

[[dialogue]]
speaker = "unk"
# 遊園地を拡張して作られたプール施設、『チェリークルーズ』。
line = "遊園地を拡張して作られたプール施設、『チェリークルーズ』。"

[[dialogue]]
speaker = "unk"
# 開園後も好評で、連日、お客さんで賑わっていた。
line = "開園後も好評で、連日、お客さんで賑わっていた。"

[[dialogue]]
speaker = "unk"
# そんなチェリークルーズに招待されて遊びに来ていた。
line = "そんなチェリークルーズに招待されて遊びに来ていた。"

[[dialogue]]
speaker = "フィオナ"
# 「色んなプールがあるのね～。ありがとう、エルゼ。今日はたくさん楽しませてもらうわ」
line = "「色んなプールがあるのね～。ありがとう、エルゼ。今日はたくさん楽しませてもらうわ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「フィオナ会長はいつも頑張っていらっしゃいますから」
line = "「フィオナ会長はいつも頑張っていらっしゃいますから」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「私から何か出来ればと思いましたの。ゆっくり羽を伸ばしていってくださいませ」
line = "「私から何か出来ればと思いましたの。ゆっくり羽を伸ばしていってくださいませ」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ、そうさせて貰うわ」
line = "「ええ、そうさせて貰うわ」"

[[dialogue]]
speaker = "unk"
# エルゼから渡されたチケットは２枚。
line = "エルゼから渡されたチケットは２枚。"

[[dialogue]]
speaker = "unk"
# １枚は俺用で、もう１枚はフィオナを誘ってきて欲しいとのことだった。
line = "１枚は俺用で、もう１枚はフィオナを誘ってきて欲しいとのことだった。"

[[dialogue]]
speaker = "フィオナ"
# 「エルゼ、メインのプールは豪華客船のプールをモチーフにしているの？」
line = "「エルゼ、メインのプールは豪華客船のプールをモチーフにしているの？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「そうなんです。先日世界一周に向けて出港した『チェリークルーズ号』の甲板をイメージして作られていますわ」
line = "「そうなんです。先日世界一周に向けて出港した『チェリークルーズ号』の甲板をイメージして作られていますわ」"

[[dialogue]]
speaker = "フィオナ"
# 「名前もそこからもらったのね？」
line = "「名前もそこからもらったのね？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「はい、そうなんですの！」
line = "「はい、そうなんですの！」"

[[dialogue]]
speaker = "unk"
# 一生に一度は乗ってみたいな
line = "一生に一度は乗ってみたいな"

[[dialogue]]
speaker = "unk"
# 豪華客船か……
line = "豪華客船か……"

[[dialogue]]
speaker = "エルデリーゼ"
# 「興味がおありですの？　お父様にお願いして、乗せていただけないかしら……」
line = "「興味がおありですの？　お父様にお願いして、乗せていただけないかしら……」"

[[dialogue]]
speaker = "unk"
# え、遠慮します……！
line = "え、遠慮します……！"

[[dialogue]]
speaker = "フィオナ"
# 「ふふっ♪　緋宮会長、エルゼとお付き合いしているんですよね？」
line = "「ふふっ♪　緋宮会長、エルゼとお付き合いしているんですよね？」"

[[dialogue]]
speaker = "フィオナ"
# 「そんな程度で気後れしていたら、ご両親に挨拶に行くときに大変じゃありませんか？」
line = "「そんな程度で気後れしていたら、ご両親に挨拶に行くときに大変じゃありませんか？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「なっ……フィオナ会長っ！？」
line = "「なっ……フィオナ会長っ！？」"

[[dialogue]]
speaker = "unk"
# か、からかわないでくれよ
line = "か、からかわないでくれよ"

[[dialogue]]
speaker = "フィオナ"
# 「ごめんなさい。でもエルゼのお父様は厳格な方だから、覚悟を決めておいた方がいいと思いますよ」
line = "「ごめんなさい。でもエルゼのお父様は厳格な方だから、覚悟を決めておいた方がいいと思いますよ」"

[[dialogue]]
speaker = "unk"
# フィオナの言葉に、エルゼから聞いた屋敷での生活のことを思い出す。
line = "フィオナの言葉に、エルゼから聞いた屋敷での生活のことを思い出す。"

[[dialogue]]
speaker = "unk"
# その話からエルゼのご両親を想像すると、ご挨拶にいくのは確かにちょっと恐くなってくる。
line = "その話からエルゼのご両親を想像すると、ご挨拶にいくのは確かにちょっと恐くなってくる。"

[[dialogue]]
speaker = "エルデリーゼ"
# 「会長様。お父様は確かに厳格な方ですけど、決して恐い人ではありませんのよ？」
line = "「会長様。お父様は確かに厳格な方ですけど、決して恐い人ではありませんのよ？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ですからご安心ください」
line = "「ですからご安心ください」"

[[dialogue]]
speaker = "フィオナ"
# 「可愛いお店も多いわね。この外装は……サランさんのイメージかしら」
line = "「可愛いお店も多いわね。この外装は……サランさんのイメージかしら」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「はい。外装だけでなく、メニューにもお姉さまが協力していますわ」
line = "「はい。外装だけでなく、メニューにもお姉さまが協力していますわ」"

[[dialogue]]
speaker = "フィオナ"
# 「そうなんだ。じゃあもう絶対間違いないわね」
line = "「そうなんだ。じゃあもう絶対間違いないわね」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「何か食べたいものがあったら仰ってくださいませ。すぐに買って参りますわ」
line = "「何か食べたいものがあったら仰ってくださいませ。すぐに買って参りますわ」"

[[dialogue]]
speaker = "フィオナ"
# 「ありがとう。でもそんなに気を遣わなくて大丈夫よ」
line = "「ありがとう。でもそんなに気を遣わなくて大丈夫よ」"

[[dialogue]]
speaker = "unk"
# エルゼはフィオナの大ファンだから
line = "エルゼはフィオナの大ファンだから"

[[dialogue]]
speaker = "unk"
# 今日はいつも以上に上機嫌だな
line = "今日はいつも以上に上機嫌だな"

[[dialogue]]
speaker = "エルデリーゼ"
# 「えへへ……フィオナ会長のことは大好きですわ。でも、ファンとは少し違う気がしますの」
line = "「えへへ……フィオナ会長のことは大好きですわ。でも、ファンとは少し違う気がしますの」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「そうですわね～。これは言葉の捉え方なだけかもしれませんけれど……」
line = "「そうですわね～。これは言葉の捉え方なだけかもしれませんけれど……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「私は地下アイドルのファンをしておりますが、その気持ちとフィオナ会長に対する気持ちは種類が全く別物ですの」
line = "「私は地下アイドルのファンをしておりますが、その気持ちとフィオナ会長に対する気持ちは種類が全く別物ですの」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「何が違うかといいますと……そうですわね、アイドルの皆さんに対しては応援する気持ちが強いですわ」
line = "「何が違うかといいますと……そうですわね、アイドルの皆さんに対しては応援する気持ちが強いですわ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ですがフィオナ会長に対する気持ちは、どちらかと言えば尊敬と憧れ……それから感謝の気持ちが強いのですわ」
line = "「ですがフィオナ会長に対する気持ちは、どちらかと言えば尊敬と憧れ……それから感謝の気持ちが強いのですわ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「……２年生になったころ、私は星騎士としての力の伸び悩みを感じておりましたの」
line = "「……２年生になったころ、私は星騎士としての力の伸び悩みを感じておりましたの」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「私の星騎士としての強みはスピード。ですが、そのせいで突出してしまうことが多く、周囲との連携に失敗することが多かったのです」
line = "「私の星騎士としての強みはスピード。ですが、そのせいで突出してしまうことが多く、周囲との連携に失敗することが多かったのです」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ですが、当時の私は周りの方々に相談することも出来ませんでした」
line = "「ですが、当時の私は周りの方々に相談することも出来ませんでした」"

[[dialogue]]
speaker = "フィオナ"
# 「エルゼは箱入り娘だったから、同年代の子と接する機会が少なかったのよね……」
line = "「エルゼは箱入り娘だったから、同年代の子と接する機会が少なかったのよね……」"

[[dialogue]]
speaker = "フィオナ"
# 「それでなくても五名門のお嬢様ということで、周りの子たちから距離を置いて接せられることが多かったでしょうね」
line = "「それでなくても五名門のお嬢様ということで、周りの子たちから距離を置いて接せられることが多かったでしょうね」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ですが、そんな時に力になってくださったのがフィオナ会長でした！」
line = "「ですが、そんな時に力になってくださったのがフィオナ会長でした！」"

[[dialogue]]
speaker = "unk"
# どんな風に力になってもらったの？
line = "どんな風に力になってもらったの？"

[[dialogue]]
speaker = "エルデリーゼ"
# 「色々ですわ……本当にたくさん……」
line = "「色々ですわ……本当にたくさん……」"

[[dialogue]]
speaker = "フィオナ"
# 「とエルゼは言ってくれていますが、本当に大したことはしてないんですよ」
line = "「とエルゼは言ってくれていますが、本当に大したことはしてないんですよ」"

[[dialogue]]
speaker = "フィオナ"
# 「スピードを活かしたまま、他の子と連携を取るための立ち回りを一緒に考えたりした程度じゃなかったかしら？」
line = "「スピードを活かしたまま、他の子と連携を取るための立ち回りを一緒に考えたりした程度じゃなかったかしら？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「そんな、まだまだありますわ！」
line = "「そんな、まだまだありますわ！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「皆の話の輪の中に入るためにどうすればいいのか。それは自分の興味のある話──趣味の話を振ってみるとよい、とか」
line = "「皆の話の輪の中に入るためにどうすればいいのか。それは自分の興味のある話──趣味の話を振ってみるとよい、とか」"

[[dialogue]]
speaker = "フィオナ"
# 「あっ……！　ええと……確かにそれは言ったかもだけど……」
line = "「あっ……！　ええと……確かにそれは言ったかもだけど……」"

[[dialogue]]
speaker = "フィオナ"
# （私の場合は流星ライダーだし、それでコミュニケーションが上手く取れました、なんて経験は緋宮会長とくらいしかないのよね……）
line = "（私の場合は流星ライダーだし、それでコミュニケーションが上手く取れました、なんて経験は緋宮会長とくらいしかないのよね……）"

[[dialogue]]
speaker = "エルデリーゼ"
# 「後は同年代の子とより多く接するために、<ruby=イルソーレ>流星寮</ruby>に入ることを提案してくださいましたわ。そしてその口添えもしていただきました」
line = "「後は同年代の子とより多く接するために、<ruby>流星寮<rt>イルソーレ</rt></ruby>に入ることを提案してくださいましたわ。そしてその口添えもしていただきました」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「おかげで私は両親を説得して入寮することができたんですのよ」
line = "「おかげで私は両親を説得して入寮することができたんですのよ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「フィオナ会長は私にとってまさに恩人、ですからファンというのとは少し違うんですの！」
line = "「フィオナ会長は私にとってまさに恩人、ですからファンというのとは少し違うんですの！」"

[[dialogue]]
speaker = "フィオナ"
# 「ともあれ私で力になれていたのだったら良かったわ」
line = "「ともあれ私で力になれていたのだったら良かったわ」"

[[dialogue]]
speaker = "フィオナ"
# 「エルゼほどではないけれど、私も同じような境遇で、同じような悩みを抱えていたことがあったから」
line = "「エルゼほどではないけれど、私も同じような境遇で、同じような悩みを抱えていたことがあったから」"

[[dialogue]]
speaker = "フィオナ"
# 「だからエルゼを見ていたら、声をかけずにはいられなかったの」
line = "「だからエルゼを見ていたら、声をかけずにはいられなかったの」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「フィオナ会長……本当にありがとうございます……」
line = "「フィオナ会長……本当にありがとうございます……」"

[[dialogue]]
speaker = "unk"
# ２人の間にあった歴史を聞き、またひとつエルゼについて知ることが出来た。
line = "２人の間にあった歴史を聞き、またひとつエルゼについて知ることが出来た。"

[[dialogue]]
speaker = "unk"
# エルゼが苦しんでいる時、フィオナが居てくれて本当に良かったと思う。
line = "エルゼが苦しんでいる時、フィオナが居てくれて本当に良かったと思う。"

[[dialogue]]
speaker = "unk"
# そして、この先エルゼが何かに躓いてしまうことがあった時、今度は俺が彼女の力になりたいと強く思うのだった。
line = "そして、この先エルゼが何かに躓いてしまうことがあった時、今度は俺が彼女の力になりたいと強く思うのだった。"
