[[dialogue]]
speaker = "unk"
# 第４話,モネは作家志望？,P
line = "第４話,モネは作家志望？,P"

[[dialogue]]
speaker = "モネ"
# 「ウィステリアさん、こっちの作業終わりました～」
line = "「ウィステリアさん、こっちの作業終わりました～」"

[[dialogue]]
speaker = "ウィステリア"
# 「いつもありがとう、紙屋敷さん。本の修繕も本職の司書より上手だから助かってるわ」
line = "「いつもありがとう、紙屋敷さん。本の修繕も本職の司書より上手だから助かってるわ」"

[[dialogue]]
speaker = "モネ"
# 「いえ、私は本に囲まれて幸せですから。むしろもっとお役に立ちたいぐらいです。新星学園を卒業しても司書としてここで働けたらなぁ……」
line = "「いえ、私は本に囲まれて幸せですから。むしろもっとお役に立ちたいぐらいです。新星学園を卒業しても司書としてここで働けたらなぁ……」"

[[dialogue]]
speaker = "ウィステリア"
# 「ふふ、それは心強いわ。上の人にも言っておくわね」
line = "「ふふ、それは心強いわ。上の人にも言っておくわね」"

[[dialogue]]
speaker = "モネ"
# 「ありがとうございます！」
line = "「ありがとうございます！」"

[[dialogue]]
speaker = "モネ"
# 「あぁ、本がいっぱい……スンスン……本の匂い……もっとぉ……」
line = "「あぁ、本がいっぱい……スンスン……本の匂い……もっとぉ……」"

[[dialogue]]
speaker = "ウィステリア"
# （ちょっと本が好きすぎるのがなければ完璧なんだけどね……）
line = "（ちょっと本が好きすぎるのがなければ完璧なんだけどね……）"

[[dialogue]]
speaker = "unk"
# こんにちは
line = "こんにちは"

[[dialogue]]
speaker = "ウィステリア"
# 「あらいらっしゃい。最近よく来るわね」
line = "「あらいらっしゃい。最近よく来るわね」"

[[dialogue]]
speaker = "モネ"
# 「会長、こんにちは。この前借りた本、もう読んじゃったんですか？　読むのだんだん早くなってますね」
line = "「会長、こんにちは。この前借りた本、もう読んじゃったんですか？　読むのだんだん早くなってますね」"

[[dialogue]]
speaker = "unk"
# 考えられる作品だった
line = "考えられる作品だった"

[[dialogue]]
speaker = "モネ"
# 「ふふ、そうですね。小説の登場人物たちはみんな幸せになろうとしてるのに、それぞれ幸せが違って、自分の幸せって何だろうって考えちゃいます」
line = "「ふふ、そうですね。小説の登場人物たちはみんな幸せになろうとしてるのに、それぞれ幸せが違って、自分の幸せって何だろうって考えちゃいます」"

[[dialogue]]
speaker = "モネ"
# 「次はこの本なんていかがですか？　『地底人の秘儀』というタイトルなんですが、オカルトではなくて本格的なミステリーなんですよ」
line = "「次はこの本なんていかがですか？　『地底人の秘儀』というタイトルなんですが、オカルトではなくて本格的なミステリーなんですよ」"

[[dialogue]]
speaker = "モネ"
# 「本当に良くできていて、早く読んでもらわないとうっかりネタバレしてしまいそうなくらいです」
line = "「本当に良くできていて、早く読んでもらわないとうっかりネタバレしてしまいそうなくらいです」"

[[dialogue]]
speaker = "モネ"
# 「そうそう、小説だけじゃなくてルポルタージュ本もおすすめですよ。この『世界ワンコイン飯』は名前通り、各地でワンコインで食べられる食事を集めた本です」
line = "「そうそう、小説だけじゃなくてルポルタージュ本もおすすめですよ。この『世界ワンコイン飯』は名前通り、各地でワンコインで食べられる食事を集めた本です」"

[[dialogue]]
speaker = "モネ"
# 「物価だけでなく現地の通貨制の影響も受けますし、なんと魔界料理の話もあって非常に興味深い――」
line = "「物価だけでなく現地の通貨制の影響も受けますし、なんと魔界料理の話もあって非常に興味深い――」"

[[dialogue]]
speaker = "モネ"
# 「あ、今のは完全に趣味の話でしたね。すみません、図書委員のお仕事しないと……」
line = "「あ、今のは完全に趣味の話でしたね。すみません、図書委員のお仕事しないと……」"

[[dialogue]]
speaker = "ウィステリア"
# 「いつもよく働いてくれてるし、少しぐらいいいんじゃない。それに利用者への対応は図書委員の立派な仕事でしょ？」
line = "「いつもよく働いてくれてるし、少しぐらいいいんじゃない。それに利用者への対応は図書委員の立派な仕事でしょ？」"

[[dialogue]]
speaker = "ウィステリア"
# 「今日はそんなに仕事多くないし私の方でやっておくわ。じゃ、また後でねー」
line = "「今日はそんなに仕事多くないし私の方でやっておくわ。じゃ、また後でねー」"

[[dialogue]]
speaker = "モネ"
# 「ありがとうございますっ」
line = "「ありがとうございますっ」"

[[dialogue]]
speaker = "モネ"
# 「あれ、その本は……会長のおすすめ？　おお～、それは気になります。大切に読ませてもらいますね」
line = "「あれ、その本は……会長のおすすめ？　おお～、それは気になります。大切に読ませてもらいますね」"

[[dialogue]]
speaker = "モネ"
# 「私、会長とこうして本について語り合えて本当に楽しいです。やっぱり新星学園に来て良かったです」
line = "「私、会長とこうして本について語り合えて本当に楽しいです。やっぱり新星学園に来て良かったです」"

[[dialogue]]
speaker = "モネ"
# 「それで……実は私、会長にお願いしたいことがありまして……」
line = "「それで……実は私、会長にお願いしたいことがありまして……」"

[[dialogue]]
speaker = "モネ"
# 「私にとって全てと言っていいくらい、私は本が好きです。大好きです」
line = "「私にとって全てと言っていいくらい、私は本が好きです。大好きです」"

[[dialogue]]
speaker = "モネ"
# 「だから司書だけじゃなくて、他にもやってみたいことがあって……本を作る側になってみたいんです」
line = "「だから司書だけじゃなくて、他にもやってみたいことがあって……本を作る側になってみたいんです」"

[[dialogue]]
speaker = "モネ"
# 「私が書いた小説、読んでみてもらえませんかっ？」
line = "「私が書いた小説、読んでみてもらえませんかっ？」"

[[dialogue]]
speaker = "unk"
# もちろん
line = "もちろん"

[[dialogue]]
speaker = "モネ"
# 「あ、ありがとうございます。これ、印刷してきたんですけど……うぅ、恥ずかしいっ……」
line = "「あ、ありがとうございます。これ、印刷してきたんですけど……うぅ、恥ずかしいっ……」"

[[dialogue]]
speaker = "unk"
# ……
line = "……"

[[dialogue]]
speaker = "unk"
# …………
line = "…………"

[[dialogue]]
speaker = "モネ"
# 「旅行先で偶然出会った男女の恋愛小説なんですけど……ど、どうでしょうか？　」
line = "「旅行先で偶然出会った男女の恋愛小説なんですけど……ど、どうでしょうか？　」"

[[dialogue]]
speaker = "unk"
# こ、これは……
line = "こ、これは……"

[[dialogue]]
speaker = "モネ"
# 「や、やっぱりダメですかっ？」
line = "「や、やっぱりダメですかっ？」"

[[dialogue]]
speaker = "unk"
# すごくいい！
line = "すごくいい！"

[[dialogue]]
speaker = "モネ"
# 「へ？　ほ、本当ですか……？　もしかして気を遣ってほめてくれてるんじゃ……」
line = "「へ？　ほ、本当ですか……？　もしかして気を遣ってほめてくれてるんじゃ……」"

[[dialogue]]
speaker = "unk"
# 未来の大作家だ！
line = "未来の大作家だ！"

[[dialogue]]
speaker = "モネ"
# 「そこまで！？」
line = "「そこまで！？」"

[[dialogue]]
speaker = "モネ"
# 「あ……うぅ……酷評もあり得るかと覚悟していたんですが、そんなにほめられると逆に不安になってしまいます……」
line = "「あ……うぅ……酷評もあり得るかと覚悟していたんですが、そんなにほめられると逆に不安になってしまいます……」"

[[dialogue]]
speaker = "モネ"
# 「でも会長にほめられると嬉しいです……えへへ」
line = "「でも会長にほめられると嬉しいです……えへへ」"

[[dialogue]]
speaker = "モネ"
# 「嬉しいのと恥ずかしいのがぐちゃぐちゃになって、おかしくなっちゃいそうです……」
line = "「嬉しいのと恥ずかしいのがぐちゃぐちゃになって、おかしくなっちゃいそうです……」"

[[dialogue]]
speaker = "モネ"
# 「男女の鬱屈した感情や生々しい描写もあえて入れてみたんですけど、会長にいいって言ってもらえて良かったです」
line = "「男女の鬱屈した感情や生々しい描写もあえて入れてみたんですけど、会長にいいって言ってもらえて良かったです」"

[[dialogue]]
speaker = "モネ"
# 「それならもっと技巧的な表現も使って……ああいやいや、作家のひとりよがりになるのはいけないし……」
line = "「それならもっと技巧的な表現も使って……ああいやいや、作家のひとりよがりになるのはいけないし……」"

[[dialogue]]
speaker = "モネ"
# 「題材はもっと爽やかに……少年少女の部活動とか……いっそもっとドロドロとした愛憎を……でもファンタジーも書いてみたい……」
line = "「題材はもっと爽やかに……少年少女の部活動とか……いっそもっとドロドロとした愛憎を……でもファンタジーも書いてみたい……」"

[[dialogue]]
speaker = "モネ"
# 「ハッ──！？　ひとりの世界に入ってました、ごめんなさい！」
line = "「ハッ──！？　ひとりの世界に入ってました、ごめんなさい！」"

[[dialogue]]
speaker = "モネ"
# 「あ、原稿は返さなくて大丈夫ですよ。むしろ会長が持っていてください。私の最初の読者として」
line = "「あ、原稿は返さなくて大丈夫ですよ。むしろ会長が持っていてください。私の最初の読者として」"

[[dialogue]]
speaker = "モネ"
# 「私がデビューして有名になったらお宝原稿になりますから。いえ、してみせます」
line = "「私がデビューして有名になったらお宝原稿になりますから。いえ、してみせます」"

[[dialogue]]
speaker = "モネ"
# 「……なんて言うのはおこがましいし恥ずかしいですけど。でも本当の気持ちです」
line = "「……なんて言うのはおこがましいし恥ずかしいですけど。でも本当の気持ちです」"

[[dialogue]]
speaker = "モネ"
# 「また小説を書きますので……感想をお願いしますね」
line = "「また小説を書きますので……感想をお願いしますね」"
