[[dialogue]]
speaker = "unk"
# 第４話,ジュリエッテとデート,P
line = "第４話,ジュリエッテとデート,P"

[[dialogue]]
speaker = "unk"
# ──ジュリエッテとのデート当日。
line = "──ジュリエッテとのデート当日。"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ま、魔王様っ、お時間ピッタリでございますねっ！」
line = "「ま、魔王様っ、お時間ピッタリでございますねっ！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ええと、本日はお日柄もよく……じゃなくてそのっ！　いい天気でございますわね！」
line = "「ええと、本日はお日柄もよく……じゃなくてそのっ！　いい天気でございますわね！」"

[[dialogue]]
speaker = "ジュリエッテ"
# （ど、ど、どうしましょう！　この前は謎のテンションでおデートに誘ってしまいましたが、冷静に考えるとヤバいですわ激ヤバでございますわ！）
line = "（ど、ど、どうしましょう！　この前は謎のテンションでおデートに誘ってしまいましたが、冷静に考えるとヤバいですわ激ヤバでございますわ！）"

[[dialogue]]
speaker = "ジュリエッテ"
# （殿方とおデートなんて……わたくし人生初体験でございますわ！）
line = "（殿方とおデートなんて……わたくし人生初体験でございますわ！）"

[[dialogue]]
speaker = "ジュリエッテ"
# （そもそもおデートって、一体なんなんですの～！　何をすればいいか、まるで分からないでございますわ！）
line = "（そもそもおデートって、一体なんなんですの～！　何をすればいいか、まるで分からないでございますわ！）"

[[dialogue]]
speaker = "ジュリエッテ"
# （こういう時は少女漫画を思い出すでございますわ……！　確かおデートの時、ヒロインは……）
line = "（こういう時は少女漫画を思い出すでございますわ……！　確かおデートの時、ヒロインは……）"

[[dialogue]]
speaker = "unk"
# 顔色悪いけど大丈夫？
line = "顔色悪いけど大丈夫？"

[[dialogue]]
speaker = "ジュリエッテ"
# 「だ、大丈夫でございますわ！　パーフェクトジュリエッテでございますわ！」
line = "「だ、大丈夫でございますわ！　パーフェクトジュリエッテでございますわ！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「わたくし、全然緊張なんてしてませんでしてよ！　比較的フラットなジュリエッテをお送りいたしておりますわよ」
line = "「わたくし、全然緊張なんてしてませんでしてよ！　比較的フラットなジュリエッテをお送りいたしておりますわよ」"

[[dialogue]]
speaker = "unk"
# 緊張してるんだね
line = "緊張してるんだね"

[[dialogue]]
speaker = "ジュリエッテ"
# 「き、き緊張なんてしてないでございます！　わたくしレベルのレディならおデートくらい余裕でございますわ！」
line = "「き、き緊張なんてしてないでございます！　わたくしレベルのレディならおデートくらい余裕でございますわ！」"

[[dialogue]]
speaker = "ジュリエッテ"
# （嘘でございますわ～～！　ガチガチに震えてますわ～！　もうお家に帰りたいでございます！）
line = "（嘘でございますわ～～！　ガチガチに震えてますわ～！　もうお家に帰りたいでございます！）"

[[dialogue]]
speaker = "ジュリエッテ"
# （しかしここでめげてはいけませんわ。シャルレーヌ様にぎゃふんと言わせるためにも、魔王様をメロメロにしなければっ）
line = "（しかしここでめげてはいけませんわ。シャルレーヌ様にぎゃふんと言わせるためにも、魔王様をメロメロにしなければっ）"

[[dialogue]]
speaker = "ジュリエッテ"
# 「さて魔王様、本日のおデートですが…………まずはおててを繋ぎましょう！」
line = "「さて魔王様、本日のおデートですが…………まずはおててを繋ぎましょう！」"

[[dialogue]]
speaker = "unk"
# おてて？
line = "おてて？"

[[dialogue]]
speaker = "ジュリエッテ"
# 「そう、おててでございます。世のカップルはおててを繋ぐものだと認識してございますわ」
line = "「そう、おててでございます。世のカップルはおててを繋ぐものだと認識してございますわ」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「さあおててを繋ぎますわよ……！」
line = "「さあおててを繋ぎますわよ……！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「～～～～～～～～～～っ！！」
line = "「～～～～～～～～～～っ！！」"

[[dialogue]]
speaker = "ジュリエッテ"
# （きゃ～～～～！！　こ、これ……意外と恥ずかしいでございますわ～！）
line = "（きゃ～～～～！！　こ、これ……意外と恥ずかしいでございますわ～！）"

[[dialogue]]
speaker = "ジュリエッテ"
# （手のひらから直に魔王様の温もりが伝わってきて……めちゃ恥ずかしいでございます！）
line = "（手のひらから直に魔王様の温もりが伝わってきて……めちゃ恥ずかしいでございます！）"

[[dialogue]]
speaker = "ジュリエッテ"
# （ですが、この程度で動じてしまっては魔王様をメロメロにできないでございますわ……！）
line = "（ですが、この程度で動じてしまっては魔王様をメロメロにできないでございますわ……！）"

[[dialogue]]
speaker = "ジュリエッテ"
# 「どどどうでございましょう魔王様っ……！　これがわたくしのおデートでございますわ……！」
line = "「どどどうでございましょう魔王様っ……！　これがわたくしのおデートでございますわ……！」"

[[dialogue]]
speaker = "unk"
# ドキドキしてる
line = "ドキドキしてる"

[[dialogue]]
speaker = "ジュリエッテ"
# 「！？　そうでございますかっ、それは大変嬉しゅうございます！」
line = "「！？　そうでございますかっ、それは大変嬉しゅうございます！」"

[[dialogue]]
speaker = "ジュリエッテ"
# （やりましたわ……！　やってやりましたわ！　これで魔王様もメロメロでございますわ！）
line = "（やりましたわ……！　やってやりましたわ！　これで魔王様もメロメロでございますわ！）"

[[dialogue]]
speaker = "ジュリエッテ"
# 「うふふ♪　それでは本格的におデートを始めましょうでございますわ！」
line = "「うふふ♪　それでは本格的におデートを始めましょうでございますわ！」"

[[dialogue]]
speaker = "ジュリエッテ"
# （始めはドキドキして仕方なかったのでございますが、段々と慣れてきましたわ）
line = "（始めはドキドキして仕方なかったのでございますが、段々と慣れてきましたわ）"

[[dialogue]]
speaker = "ジュリエッテ"
# （魔王様……ちゃんと歩幅をわたくしに合わせてくださいますし、手もずっと優しく握ってくださりますわ）
line = "（魔王様……ちゃんと歩幅をわたくしに合わせてくださいますし、手もずっと優しく握ってくださりますわ）"

[[dialogue]]
speaker = "ジュリエッテ"
# （なんだか、思ったよりもずっと紳士な方でございますわね……）
line = "（なんだか、思ったよりもずっと紳士な方でございますわね……）"

[[dialogue]]
speaker = "ジュリエッテ"
# （わたくしなんて、ただの敵に過ぎないのに……惚れているなんて、嘘を吐いて騙しているのに……）
line = "（わたくしなんて、ただの敵に過ぎないのに……惚れているなんて、嘘を吐いて騙しているのに……）"

[[dialogue]]
speaker = "ジュリエッテ"
# 「魔王様、そろそろお昼にいたしませんこと？　実はわたくし、お弁当を作ってきたんでございますの♪」
line = "「魔王様、そろそろお昼にいたしませんこと？　実はわたくし、お弁当を作ってきたんでございますの♪」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ふふ、特別でしてよ♪　このわたくしが二度も人に手料理を振る舞うなんて、よっぽどのことなんでございますから♪」
line = "「ふふ、特別でしてよ♪　このわたくしが二度も人に手料理を振る舞うなんて、よっぽどのことなんでございますから♪」"

[[dialogue]]
speaker = "unk"
# 近場の公園のベンチに座り、ジュリエッテのお弁当を楽しんだ。
line = "近場の公園のベンチに座り、ジュリエッテのお弁当を楽しんだ。"

[[dialogue]]
speaker = "ジュリエッテ"
# 「お弁当はお気に召しましたでございましょうか？」
line = "「お弁当はお気に召しましたでございましょうか？」"

[[dialogue]]
speaker = "unk"
# とても美味しかった
line = "とても美味しかった"

[[dialogue]]
speaker = "ジュリエッテ"
# 「うふふ♪　それはよかったでございますわ♪　まあ、このわたくしが作って美味しくない料理などございませんけれど♪」
line = "「うふふ♪　それはよかったでございますわ♪　まあ、このわたくしが作って美味しくない料理などございませんけれど♪」"

[[dialogue]]
speaker = "ジュリエッテ"
# （やはり魔王様に褒めていただくのは悪い気はしませんわね）
line = "（やはり魔王様に褒めていただくのは悪い気はしませんわね）"

[[dialogue]]
speaker = "ジュリエッテ"
# （ですが、モヤモヤしますわ……魔王様をこのまま騙し続けるのは、わたくし……）
line = "（ですが、モヤモヤしますわ……魔王様をこのまま騙し続けるのは、わたくし……）"

[[dialogue]]
speaker = "ジュリエッテ"
# 「魔王様……実はわたくし、一つ隠し事をしていましてよ」
line = "「魔王様……実はわたくし、一つ隠し事をしていましてよ」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「わたくし、魔王様に一目惚れなんてしていませんでしたわ」
line = "「わたくし、魔王様に一目惚れなんてしていませんでしたわ」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「全て嘘でございましたの。ただわたくしは魔王様を利用──」
line = "「全て嘘でございましたの。ただわたくしは魔王様を利用──」"

[[dialogue]]
speaker = "unk"
# 知ってたよ。でも楽しかったから
line = "知ってたよ。でも楽しかったから"

[[dialogue]]
speaker = "ジュリエッテ"
# 「へ！？　知っててわたくしと一緒にいたのでございますか！？」
line = "「へ！？　知っててわたくしと一緒にいたのでございますか！？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「本当に魔王様は、変わり者といいますか……」
line = "「本当に魔王様は、変わり者といいますか……」"

[[dialogue]]
speaker = "ジュリエッテ"
# （はぁ……でもそんなお方だから、わたくしも──）
line = "（はぁ……でもそんなお方だから、わたくしも──）"

[[dialogue]]
speaker = "ジュリエッテ"
# 「……わたくしと魔王様はあくまでも敵同士でございますから、そのことをゆめゆめお忘れなく」
line = "「……わたくしと魔王様はあくまでも敵同士でございますから、そのことをゆめゆめお忘れなく」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「わたくし達は所詮相容れない存在……決して、魔王様を騙し続けて罪悪感が湧いたとか、魔王様のことをちょっぴり気に入りかけたとか」
line = "「わたくし達は所詮相容れない存在……決して、魔王様を騙し続けて罪悪感が湧いたとか、魔王様のことをちょっぴり気に入りかけたとか」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「そーんな甘いことは一切ござませんから！　本当でございますからね！」
line = "「そーんな甘いことは一切ござませんから！　本当でございますからね！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「……コホン。ということで、これからも敵同士仲良くしていきましょう……魔王様♪」
line = "「……コホン。ということで、これからも敵同士仲良くしていきましょう……魔王様♪」"
