[[dialogue]]
speaker = "unk"
# 俺たちは今、豪華客船『チェリークルーズ号』の甲板のプールに居た。
line = "俺たちは今、豪華客船『チェリークルーズ号』の甲板のプールに居た。"

[[dialogue]]
speaker = "unk"
# そこには、デッキチェアに寝そべって夜空を見上げている俺とサラン以外に誰もいない。
line = "そこには、デッキチェアに寝そべって夜空を見上げている俺とサラン以外に誰もいない。"

[[dialogue]]
speaker = "クロト"
# 「……静かだな…………」
line = "「……静かだな…………」"

[[dialogue]]
speaker = "サラン"
# 「静かだね～……」
line = "「静かだね～……」"

[[dialogue]]
speaker = "クロト"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "サラン"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# その静けさに俺は少し大胆になって……
line = "その静けさに俺は少し大胆になって……"

[[dialogue]]
speaker = "クロト"
# 「サラン……もしよかったら……」
line = "「サラン……もしよかったら……」"

[[dialogue]]
speaker = "unk"
# 隣にいるサランの手を握る。
line = "隣にいるサランの手を握る。"

[[dialogue]]
speaker = "サラン"
# 「…………うん、いいよ……会長ちゃん……しよ……」
line = "「…………うん、いいよ……会長ちゃん……しよ……」"

[[dialogue]]
speaker = "unk"
# 短い沈黙の後、サランの小さな手が握り返してくる。
line = "短い沈黙の後、サランの小さな手が握り返してくる。"

[[dialogue]]
speaker = "クロト"
# 「サラン……」
line = "「サラン……」"

[[dialogue]]
speaker = "unk"
# サランの上に覆いかぶさるようにして見つめ合う。
line = "サランの上に覆いかぶさるようにして見つめ合う。"

[[dialogue]]
speaker = "サラン"
# 「……ど、どうしたの～……黙って見つめられたら……恥ずかしいよ～……」
line = "「……ど、どうしたの～……黙って見つめられたら……恥ずかしいよ～……」"

[[dialogue]]
speaker = "クロト"
# 「可愛いなって、思って……」
line = "「可愛いなって、思って……」"

[[dialogue]]
speaker = "サラン"
# 「ありがと～。でも、水着はもういっぱい褒めてもらったから……」
line = "「ありがと～。でも、水着はもういっぱい褒めてもらったから……」"

[[dialogue]]
speaker = "クロト"
# 「いや、水着だけじゃなくて……サランの何もかもが可愛いなって……」
line = "「いや、水着だけじゃなくて……サランの何もかもが可愛いなって……」"

[[dialogue]]
speaker = "サラン"
# 「っっっうう～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「っっっうう～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「どうしたの、会長ちゃん……なんだかいつものえっちと、雰囲気がちがうよ～……」
line = "「どうしたの、会長ちゃん……なんだかいつものえっちと、雰囲気がちがうよ～……」"

[[dialogue]]
speaker = "クロト"
# 「……この雰囲気がそうさせるのかな？」
line = "「……この雰囲気がそうさせるのかな？」"

[[dialogue]]
speaker = "unk"
# プールはライトアップされ、ムーディーな明かりに照らされている。
line = "プールはライトアップされ、ムーディーな明かりに照らされている。"

[[dialogue]]
speaker = "unk"
# 静かな波の音が遠くに聞こえるだけで、人の声もない。物音もしない。世界に２人だけだと錯覚させるような……静かな世界……
line = "静かな波の音が遠くに聞こえるだけで、人の声もない。物音もしない。世界に２人だけだと錯覚させるような……静かな世界……"

[[dialogue]]
speaker = "サラン"
# 「いつもはお部屋でしてるから、お外でするなんてドキドキするけど……」
line = "「いつもはお部屋でしてるから、お外でするなんてドキドキするけど……」"

[[dialogue]]
speaker = "サラン"
# 「でも不思議なくらい、穏やかな気持ち……会長ちゃんも、そうなのかな……？」
line = "「でも不思議なくらい、穏やかな気持ち……会長ちゃんも、そうなのかな……？」"

[[dialogue]]
speaker = "クロト"
# 「ああ、まさにそんな気持ち……」
line = "「ああ、まさにそんな気持ち……」"

[[dialogue]]
speaker = "サラン"
# 「会長ちゃんとのえっちはいつだって、夢中で求めちゃうけど……こんな気持ちのままえっちしたら、どうなっちゃうのかな……」
line = "「会長ちゃんとのえっちはいつだって、夢中で求めちゃうけど……こんな気持ちのままえっちしたら、どうなっちゃうのかな……」"

[[dialogue]]
speaker = "クロト"
# 「してみようか……」
line = "「してみようか……」"

[[dialogue]]
speaker = "サラン"
# 「うん……」
line = "「うん……」"

[[dialogue]]
speaker = "unk"
# 俺は勃起したペニスの先端を、サランの秘部へと押し当てる。
line = "俺は勃起したペニスの先端を、サランの秘部へと押し当てる。"

[[dialogue]]
speaker = "unk"
# くちゅりという音がして、先端部分が花びらの中へもぐりこんだ。
line = "くちゅりという音がして、先端部分が花びらの中へもぐりこんだ。"

[[dialogue]]
speaker = "クロト"
# 「すごく濡れてる……興奮は、ちゃんとしてくれてるんだ……」
line = "「すごく濡れてる……興奮は、ちゃんとしてくれてるんだ……」"

[[dialogue]]
speaker = "サラン"
# 「もちろんだよ～。会長ちゃんだって落ち着いてるようにみえるのに、おち○ちん、カチカチになってるよ……」
line = "「もちろんだよ～。会長ちゃんだって落ち着いてるようにみえるのに、おち○ちん、カチカチになってるよ……」"

[[dialogue]]
speaker = "クロト"
# 「そうだな……」
line = "「そうだな……」"

[[dialogue]]
speaker = "unk"
# そのカチカチのペニスを上下に動かして、サランの入り口付近を丁寧にまさぐる。
line = "そのカチカチのペニスを上下に動かして、サランの入り口付近を丁寧にまさぐる。"

[[dialogue]]
speaker = "サラン"
# 「クチュクチュって、サランのおま○こ……えっちな音、してる……んんぅう……そんなに感じてたの……？」
line = "「クチュクチュって、サランのおま○こ……えっちな音、してる……んんぅう……そんなに感じてたの……？」"

[[dialogue]]
speaker = "サラン"
# 「ぁ、ぅ……んんっ……恥ずかしい……んっ、ん……あぅ……んんん……」
line = "「ぁ、ぅ……んんっ……恥ずかしい……んっ、ん……あぅ……んんん……」"

[[dialogue]]
speaker = "サラン"
# 「っ……んんんんっ……<emoji=heart04>」
line = "「っ……んんんんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 膣壁を押し分けて、サランの内側へペニスを押し進める。
line = "膣壁を押し分けて、サランの内側へペニスを押し進める。"

[[dialogue]]
speaker = "サラン"
# 「ぁああ、んんっ……おち○ちん、入ってきてる……ゆっくり……出たり入ったりしてるぅ……<emoji=heart04>」
line = "「ぁああ、んんっ……おち○ちん、入ってきてる……ゆっくり……出たり入ったりしてるぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 動きが緩やかな分、その動きを意識できるのかもしれない。
line = "動きが緩やかな分、その動きを意識できるのかもしれない。"

[[dialogue]]
speaker = "unk"
# 俺の微かな動きにも反応して、膣内のヒダが忙しなく蠢いた。
line = "俺の微かな動きにも反応して、膣内のヒダが忙しなく蠢いた。"

[[dialogue]]
speaker = "サラン"
# 「はぁ……ぁ……んんっ……んぅ……ぁ……熱い……んんっ……会長ちゃんの……おち○ちん……」
line = "「はぁ……ぁ……んんっ……んぅ……ぁ……熱い……んんっ……会長ちゃんの……おち○ちん……」"

[[dialogue]]
speaker = "サラン"
# 「んっ、ふ、んんん……はぁ、ぅ……んんんっ……ぁ……あああ……んんんっ……」
line = "「んっ、ふ、んんん……はぁ、ぅ……んんんっ……ぁ……あああ……んんんっ……」"

[[dialogue]]
speaker = "unk"
# サランの膣の具合を味わいながら、俺はゆっくりとしたピストンを続ける。
line = "サランの膣の具合を味わいながら、俺はゆっくりとしたピストンを続ける。"

[[dialogue]]
speaker = "unk"
# ペニスがサランの内に押し込まれるたび、その内側から愛液がこぼれる。
line = "ペニスがサランの内に押し込まれるたび、その内側から愛液がこぼれる。"

[[dialogue]]
speaker = "unk"
# その量がサランの身体にどれだけ火がついているかを教えていた。
line = "その量がサランの身体にどれだけ火がついているかを教えていた。"

[[dialogue]]
speaker = "クロト"
# 「サラン……感じてるところも可愛いよ……」
line = "「サラン……感じてるところも可愛いよ……」"

[[dialogue]]
speaker = "サラン"
# 「んぅうう……会長ちゃん……そんなこと言われたら……余計に感じちゃうよ～……んんっ、あぁあ……<emoji=heart04>」
line = "「んぅうう……会長ちゃん……そんなこと言われたら……余計に感じちゃうよ～……んんっ、あぁあ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「や、あぁあ……んんんっ……会長ちゃんに、見つめられてるだけで……イッちゃいそうだよ～……んんんっ、あ、ああっ……<emoji=heart04>」
line = "「や、あぁあ……んんんっ……会長ちゃんに、見つめられてるだけで……イッちゃいそうだよ～……んんんっ、あ、ああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 恥じらうサランに顔を近づける。
line = "恥じらうサランに顔を近づける。"

[[dialogue]]
speaker = "サラン"
# 「んっ……ん……ふ……んんっ……ちゅ……んんっ……」
line = "「んっ……ん……ふ……んんっ……ちゅ……んんっ……」"

[[dialogue]]
speaker = "サラン"
# 「んんっ……ふ……ふぁ……んんんっ……ん……ちゅ……んむ……ふ……んんんっ……ふぁ……」
line = "「んんっ……ふ……ふぁ……んんんっ……ん……ちゅ……んむ……ふ……んんんっ……ふぁ……」"

[[dialogue]]
speaker = "unk"
# 短くついばむようなキスを何度も繰り返す。
line = "短くついばむようなキスを何度も繰り返す。"

[[dialogue]]
speaker = "unk"
# そして、キスの合間には身体を寄せてサランを抱きしめる。
line = "そして、キスの合間には身体を寄せてサランを抱きしめる。"

[[dialogue]]
speaker = "サラン"
# 「はぁ、ぅうう……んん……そんな、優しく抱きしめられたら……もっと嬉しくなっちゃう……<emoji=heart04>」
line = "「はぁ、ぅうう……んん……そんな、優しく抱きしめられたら……もっと嬉しくなっちゃう……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「サランは柔らかくて抱き心地がいいからな……大好きなんだ……」
line = "「サランは柔らかくて抱き心地がいいからな……大好きなんだ……」"

[[dialogue]]
speaker = "サラン"
# 「嬉しい……会長ちゃん、いつでもいっぱい……サランのこと抱きしめて……会長ちゃん……」
line = "「嬉しい……会長ちゃん、いつでもいっぱい……サランのこと抱きしめて……会長ちゃん……」"

[[dialogue]]
speaker = "サラン"
# 「んっ、ん……は……んんんっ……んっ……ふぅ、ん……ふぁ……ん……ふ……ちゅ、む……んんんっ……」
line = "「んっ、ん……は……んんんっ……んっ……ふぅ、ん……ふぁ……ん……ふ……ちゅ、む……んんんっ……」"

[[dialogue]]
speaker = "サラン"
# 「ちゅ、は、んん……ちゅむ……んん、ふぁ……ん……んんっ……ちゅ、ん……ふ、ちゅぱ、ん……んん……ふ……ちゅむ……」
line = "「ちゅ、は、んん……ちゅむ……んん、ふぁ……ん……んんっ……ちゅ、ん……ふ、ちゅぱ、ん……んん……ふ……ちゅむ……」"

[[dialogue]]
speaker = "unk"
# サランの唇を割り舌を忍び込ませると、サランはすぐに絡めてくる。
line = "サランの唇を割り舌を忍び込ませると、サランはすぐに絡めてくる。"

[[dialogue]]
speaker = "unk"
# 俺とサランはしばらく、息をすることも忘れて長い長いキスに没頭する。
line = "俺とサランはしばらく、息をすることも忘れて長い長いキスに没頭する。"

[[dialogue]]
speaker = "サラン"
# 「んっ、ちゅっ、ふ……ちゅ、んむ……ぷはっ、は……ちゅ、んんっ……んっ、んふ……ちゅ、んんんっ……」
line = "「んっ、ちゅっ、ふ……ちゅ、んむ……ぷはっ、は……ちゅ、んんっ……んっ、んふ……ちゅ、んんんっ……」"

[[dialogue]]
speaker = "サラン"
# 「ふぁ、ん……はぁ……キス、気持ちいいよぉ……んんっ、ちゅ、んん、ん……ちゅは、ん……んふ……ちゅ、ちゅむ……んんっ……ふぁ……」
line = "「ふぁ、ん……はぁ……キス、気持ちいいよぉ……んんっ、ちゅ、んん、ん……ちゅは、ん……んふ……ちゅ、ちゅむ……んんっ……ふぁ……」"

[[dialogue]]
speaker = "サラン"
# 「えへへ……甘いキス……飴玉みたいに溶けてなくなっちゃいそう……<emoji=heart04>　んんっ……ちゅ、ふ……んんんっ……<emoji=heart04>」
line = "「えへへ……甘いキス……飴玉みたいに溶けてなくなっちゃいそう……<emoji=heart04>　んんっ……ちゅ、ふ……んんんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「んっ、ちゅ、はぁ……キスだけでも、気持ちいいのに……んんっ……は……ズポズポするのも……ずっと続けてるから……んんんっ……<emoji=heart04>」
line = "「んっ、ちゅ、はぁ……キスだけでも、気持ちいいのに……んんっ……は……ズポズポするのも……ずっと続けてるから……んんんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# キスをしながらも、緩やかなピストンは続けていた。
line = "キスをしながらも、緩やかなピストンは続けていた。"

[[dialogue]]
speaker = "unk"
# 舌を絡める興奮に合わせて襞がざわめき、包み込んだペニスを撫で上げていく。
line = "舌を絡める興奮に合わせて襞がざわめき、包み込んだペニスを撫で上げていく。"

[[dialogue]]
speaker = "サラン"
# 「あっ……！　あ……んんんっ……んぅ……そこ……サランの気持ちいいところだぁ～……んんんっ……<emoji=heart04>」
line = "「あっ……！　あ……んんんっ……んぅ……そこ……サランの気持ちいいところだぁ～……んんんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「はぁ、あっ……は、んんっ……会長ちゃんは、すぐに分かるんだね……サランの弱いところ……あ、あっ……あああ、ん、はぁああ……<emoji=heart04>」
line = "「はぁ、あっ……は、んんっ……会長ちゃんは、すぐに分かるんだね……サランの弱いところ……あ、あっ……あああ、ん、はぁああ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「分かるよ……だってもう、数えきれないくらいサランとはエッチしたから……」
line = "「分かるよ……だってもう、数えきれないくらいサランとはエッチしたから……」"

[[dialogue]]
speaker = "サラン"
# 「えへへ、嬉しいな……何も言わなくても分かってもらえるの……んんっ……<emoji=heart04>」
line = "「えへへ、嬉しいな……何も言わなくても分かってもらえるの……んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「それに……会長ちゃん……知ってる……サランがして欲しいこと……んんんっ……そこ、いっぱい攻めて欲しいって……んっ、あっ……ああっ……<emoji=heart04>」
line = "「それに……会長ちゃん……知ってる……サランがして欲しいこと……んんんっ……そこ、いっぱい攻めて欲しいって……んっ、あっ……ああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「はぁ、ぅ……んんっ……でも、変だよ……んんっ……どうして……？　こんなに、ゆっくりなのに……サラン、なんだか……あっ、感じて……ぁっ……ん……」
line = "「はぁ、ぅ……んんっ……でも、変だよ……んんっ……どうして……？　こんなに、ゆっくりなのに……サラン、なんだか……あっ、感じて……ぁっ……ん……」"

[[dialogue]]
speaker = "サラン"
# 「っ……ぁ……！！！　んんぅうううっ……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「っ……ぁ……！！！　んんぅうううっ……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# サランが軽くイッたのが分かった。
line = "サランが軽くイッたのが分かった。"

[[dialogue]]
speaker = "サラン"
# 「はぁ……はぁ……ん……ぁあ……ふ……んんっ……<emoji=heart04>　びっくり……しちゃった……んんんっ……<emoji=heart04>」
line = "「はぁ……はぁ……ん……ぁあ……ふ……んんっ……<emoji=heart04>　びっくり……しちゃった……んんんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「こんなにゆっくりでも……イけちゃうんだ……っ……はぁ……ん……」
line = "「こんなにゆっくりでも……イけちゃうんだ……っ……はぁ……ん……」"

[[dialogue]]
speaker = "サラン"
# 「えへへ……でも……何だかふわふわで……幸せなえっちだよ……こういうのも、好き……<emoji=heart04>」
line = "「えへへ……でも……何だかふわふわで……幸せなえっちだよ……こういうのも、好き……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「それじゃ会長ちゃん……次は会長ちゃんが気持ちよくなる番だよ……」
line = "「それじゃ会長ちゃん……次は会長ちゃんが気持ちよくなる番だよ……」"

[[dialogue]]
speaker = "クロト"
# 「ありがとう、サラン……。でも、俺は一緒がいいな……サランと一緒に気持ちよくなりたい……」
line = "「ありがとう、サラン……。でも、俺は一緒がいいな……サランと一緒に気持ちよくなりたい……」"

[[dialogue]]
speaker = "サラン"
# 「ふふっ……そうだね……それじゃ……一緒に気持ちよくなろ……会長ちゃん……<emoji=heart04>」
line = "「ふふっ……そうだね……それじゃ……一緒に気持ちよくなろ……会長ちゃん……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺は再び、抜いては差しのピストンを始める。
line = "俺は再び、抜いては差しのピストンを始める。"

[[dialogue]]
speaker = "unk"
# 先ほどの緩やかなものとは違い、自分も気持ちよくなることを求めたピストン。
line = "先ほどの緩やかなものとは違い、自分も気持ちよくなることを求めたピストン。"

[[dialogue]]
speaker = "サラン"
# 「んっ、んっ、んっ……！　んっ、はっ、あっ……あぁあ……んんっ、あっ、あっ、あ、ああっ……！」
line = "「んっ、んっ、んっ……！　んっ、はっ、あっ……あぁあ……んんっ、あっ、あっ、あ、ああっ……！」"

[[dialogue]]
speaker = "サラン"
# 「っ、んん……はっ、あぁあ、あっ……は……んんっ……<emoji=heart04>　えへへ……会長ちゃんも……気持ちよくなってる～……<emoji=heart04>」
line = "「っ、んん……はっ、あぁあ、あっ……は……んんっ……<emoji=heart04>　えへへ……会長ちゃんも……気持ちよくなってる～……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「あ、んっ、は、ああっ……んぅ……会長ちゃんの……えっちしてる時の顔……好きぃ……んんっ、あっ、あ、ああっ……<emoji=heart04>」
line = "「あ、んっ、は、ああっ……んぅ……会長ちゃんの……えっちしてる時の顔……好きぃ……んんっ、あっ、あ、ああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「切なそうで……汗がにじんでて……唇がちょっと震えてて……声には出ないけど……気持ち、伝わってくるよ……<emoji=heart04>」
line = "「切なそうで……汗がにじんでて……唇がちょっと震えてて……声には出ないけど……気持ち、伝わってくるよ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「気持ちいいよね……んんっ……えっち、気持ちいいよね……会長ちゃんっ……あああっ、ん、ふぁ、んん……あぁ、あっ、ああんっ……<emoji=heart04>」
line = "「気持ちいいよね……んんっ……えっち、気持ちいいよね……会長ちゃんっ……あああっ、ん、ふぁ、んん……あぁ、あっ、ああんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「会長ちゃんの息遣い、どんどん荒くなってる……んんんっ……おち○ちんもの動きも……乱暴になっていって……」
line = "「会長ちゃんの息遣い、どんどん荒くなってる……んんんっ……おち○ちんもの動きも……乱暴になっていって……」"

[[dialogue]]
speaker = "サラン"
# 「でも、愛してるんだ～……サランのことが大切で……好きで好きで仕方ないって……あぁあっ……伝わってくるから……<emoji=heart04>」
line = "「でも、愛してるんだ～……サランのことが大切で……好きで好きで仕方ないって……あぁあっ……伝わってくるから……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「ああっ、あっ、あっ……ん、あ、あああっ……嬉しい……愛してる……大好きだよ……会長ちゃんっ……あっ、あああっ……<emoji=heart04>」
line = "「ああっ、あっ、あっ……ん、あ、あああっ……嬉しい……愛してる……大好きだよ……会長ちゃんっ……あっ、あああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# サランの言葉に愛情と欲望がごちゃごちゃにかき混ぜられる。
line = "サランの言葉に愛情と欲望がごちゃごちゃにかき混ぜられる。"

[[dialogue]]
speaker = "unk"
# 荒れ狂う気持ちを収めるために、サランの唇を貪る。
line = "荒れ狂う気持ちを収めるために、サランの唇を貪る。"

[[dialogue]]
speaker = "サラン"
# 「んんっ……！　んっ、んんっ、ちゅ、んん……ふぁあ……！　んんんっ、んむ……ふ、ちゅ、ん……ちゅぷ、れろっ、んん、ふ、はぁああ……<emoji=heart04>」
line = "「んんっ……！　んっ、んんっ、ちゅ、んん……ふぁあ……！　んんんっ、んむ……ふ、ちゅ、ん……ちゅぷ、れろっ、んん、ふ、はぁああ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「キス、激し……んんっ、ちゅ、ふぁ……はぁ……キスでも、サランに夢中だって……んんっ……伝えてくれてるっ……んんんっ……<emoji=heart04>」
line = "「キス、激し……んんっ、ちゅ、ふぁ……はぁ……キスでも、サランに夢中だって……んんっ……伝えてくれてるっ……んんんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「ふぁ……はぁ……ぁ……んんんっ……<emoji=heart04>　はぁ、あ……どんどん……サランのおま○こ……熱くなってる……あ、あああんっ……<emoji=heart04>」
line = "「ふぁ……はぁ……ぁ……んんんっ……<emoji=heart04>　はぁ、あ……どんどん……サランのおま○こ……熱くなってる……あ、あああんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「あっ、あっ、あ、んんっ……はぁ、あ……さっき、イッたばかりなのに……また、どんどん気持ちよくなってくよ……あ、ああっ、っ、あ、あああっ……<emoji=heart04>」
line = "「あっ、あっ、あ、んんっ……はぁ、あ……さっき、イッたばかりなのに……また、どんどん気持ちよくなってくよ……あ、ああっ、っ、あ、あああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その兆候は俺も感じ取っていた。
line = "その兆候は俺も感じ取っていた。"

[[dialogue]]
speaker = "unk"
# ペニスを包み込んだ膣が再び収縮を始める。
line = "ペニスを包み込んだ膣が再び収縮を始める。"

[[dialogue]]
speaker = "unk"
# その全てを吸い上げるような動きは、俺の欲望の全部を呑み込もうとしているかのようだった。
line = "その全てを吸い上げるような動きは、俺の欲望の全部を呑み込もうとしているかのようだった。"

[[dialogue]]
speaker = "サラン"
# 「はぁ、う、んんんっ……会長、ちゃん……どうしよ……サラン、また……んんんっ……！」
line = "「はぁ、う、んんんっ……会長、ちゃん……どうしよ……サラン、また……んんんっ……！」"

[[dialogue]]
speaker = "クロト"
# 「いいよ……俺もイキそうだから……そのまま……」
line = "「いいよ……俺もイキそうだから……そのまま……」"

[[dialogue]]
speaker = "サラン"
# 「うん、うん、わかった……んんっ……サラン、イクね……会長ちゃんっ……あ、ああっ……イクっ、もう……サラン、イッちゃうっ……<emoji=heart04>」
line = "「うん、うん、わかった……んんっ……サラン、イクね……会長ちゃんっ……あ、ああっ……イクっ、もう……サラン、イッちゃうっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ペニスを痺れた様な感覚が包んでいる。
line = "ペニスを痺れた様な感覚が包んでいる。"

[[dialogue]]
speaker = "unk"
# 背筋が震え、目がくらみ、意識が霞がかったようにぼやけてくる。
line = "背筋が震え、目がくらみ、意識が霞がかったようにぼやけてくる。"

[[dialogue]]
speaker = "unk"
# だけど、ただ夢中で……サランと一緒に絶頂を迎えるために、無心に身体を揺さぶり続ける。
line = "だけど、ただ夢中で……サランと一緒に絶頂を迎えるために、無心に身体を揺さぶり続ける。"

[[dialogue]]
speaker = "サラン"
# 「あっ、あっ、あっ、あ、あ、ああっ、あ、んんっ<emoji=heart04>　ん、あっ、ああっ<emoji=heart04>　は、ふぁ、あ……あ、あ、あ……ああああっ<emoji=heart04>」
line = "「あっ、あっ、あっ、あ、あ、ああっ、あ、んんっ<emoji=heart04>　ん、あっ、ああっ<emoji=heart04>　は、ふぁ、あ……あ、あ、あ……ああああっ<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「会長ちゃんっ、んんっ、会長ちゃんっ！　んんっ、あっ、あ、ああっ、や、んんっ、く、あぁあ……らめっ、サラン、もう、らめぇっ……！！」
line = "「会長ちゃんっ、んんっ、会長ちゃんっ！　んんっ、あっ、あ、ああっ、や、んんっ、く、あぁあ……らめっ、サラン、もう、らめぇっ……！！」"

[[dialogue]]
speaker = "クロト"
# 「っ……ぁあ……俺も……サランの、中にっ……！！！」
line = "「っ……ぁあ……俺も……サランの、中にっ……！！！」"

[[dialogue]]
speaker = "サラン"
# 「んんっ、あ、らしてっ<emoji=heart04>　んんっ……サランのおま○こにっ……<emoji=heart04>　会長ちゃんのせーえきっれ満たしてっ……<emoji=heart04>」
line = "「んんっ、あ、らしてっ<emoji=heart04>　んんっ……サランのおま○こにっ……<emoji=heart04>　会長ちゃんのせーえきっれ満たしてっ……<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「びゅーびゅーって、あふれるくらい、いっぱいのせーしでイかせてっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　あああっ、あっ、あああっ、あ、ああっ<emoji=heart04>」
line = "「びゅーびゅーって、あふれるくらい、いっぱいのせーしでイかせてっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　あああっ、あっ、あああっ、あ、ああっ<emoji=heart04>」"

[[dialogue]]
speaker = "サラン"
# 「あああっ、あっ、あっ、あ、ああっ<emoji=heart04>　らめぇっ、らめ、らめ、もうっ……イク……イクイクイクっ！　イッちゃうううううっ！！！」
line = "「あああっ、あっ、あっ、あ、ああっ<emoji=heart04>　らめぇっ、らめ、らめ、もうっ……イク……イクイクイクっ！　イッちゃうううううっ！！！」"

[[dialogue]]
speaker = "unk"
# サランの身体がさっきよりも激しく、びくんびくんと跳ね上がる。
line = "サランの身体がさっきよりも激しく、びくんびくんと跳ね上がる。"

[[dialogue]]
speaker = "unk"
# 同時に膣全体がペニスをギュッと締め付けてきて──
line = "同時に膣全体がペニスをギュッと締め付けてきて──"

[[dialogue]]
speaker = "クロト"
# 「っ……！！！！！！！！」
line = "「っ……！！！！！！！！」"

[[dialogue]]
speaker = "サラン"
# 「ぁっ……あ、あああああああああああああーーーーーーっ！！！！！！！！！」
line = "「ぁっ……あ、あああああああああああああーーーーーーっ！！！！！！！！！」"

[[dialogue]]
speaker = "unk"
# 快感の頂点に達した叫びを上げながら、サランが全身を<ruby=わなな>戦慄</ruby>かせる。
line = "快感の頂点に達した叫びを上げながら、サランが全身を<ruby>戦慄<rt>わなな</rt></ruby>かせる。"

[[dialogue]]
speaker = "サラン"
# 「ああっ！！　んっ、は、ああっ！！　んぅうう……んんっ……！　あ、ああっ……！！」
line = "「ああっ！！　んっ、は、ああっ！！　んぅうう……んんっ……！　あ、ああっ……！！」"

[[dialogue]]
speaker = "サラン"
# 「しゅご、い……んんっ……イッて、るぅ……おま○こ……震えがとまらないぃ……んんっ……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「しゅご、い……んんっ……イッて、るぅ……おま○こ……震えがとまらないぃ……んんっ……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 達してからもなお、サランの膣は蠢き、ペニスを刺激し続けていた。
line = "達してからもなお、サランの膣は蠢き、ペニスを刺激し続けていた。"

[[dialogue]]
speaker = "unk"
# 俺は下半身に力を込めながら、全てを吐き出そうと限界まで脈打たせる。
line = "俺は下半身に力を込めながら、全てを吐き出そうと限界まで脈打たせる。"

[[dialogue]]
speaker = "サラン"
# 「あっ……ん……うう……んぅう……ん……<emoji=heart04>　んく、ぅ……はぁ……ん……はぁ……はぁ……<emoji=heart04>」
line = "「あっ……ん……うう……んぅう……ん……<emoji=heart04>　んく、ぅ……はぁ……ん……はぁ……はぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 途切れ途切れの喘ぎを漏らしながら、ようやく長い絶頂の余韻が収まりを見せ始めた。
line = "途切れ途切れの喘ぎを漏らしながら、ようやく長い絶頂の余韻が収まりを見せ始めた。"

[[dialogue]]
speaker = "unk"
# その波がゆっくり引いたのを感じ取ると、俺はサランの中からペニスを引き抜く。
line = "その波がゆっくり引いたのを感じ取ると、俺はサランの中からペニスを引き抜く。"

[[dialogue]]
speaker = "サラン"
# 「あっ……<emoji=heart04>　んんぅ……ん……」
line = "「あっ……<emoji=heart04>　んんぅ……ん……」"

[[dialogue]]
speaker = "unk"
# 膣口からあふれた精液は、お尻を伝って流れ、ビーチチェアに白い水たまりを作った。
line = "膣口からあふれた精液は、お尻を伝って流れ、ビーチチェアに白い水たまりを作った。"

[[dialogue]]
speaker = "サラン"
# 「はぁ……はぁ……ん……会長……ちゃん……」
line = "「はぁ……はぁ……ん……会長……ちゃん……」"

[[dialogue]]
speaker = "クロト"
# 「ん……？」
line = "「ん……？」"

[[dialogue]]
speaker = "サラン"
# 「好き……<emoji=heart04>」
line = "「好き……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# それだけ言って、サランは幸せそうな笑顔を浮かべる。
line = "それだけ言って、サランは幸せそうな笑顔を浮かべる。"

[[dialogue]]
speaker = "クロト"
# 「俺も……愛してる……」
line = "「俺も……愛してる……」"

[[dialogue]]
speaker = "unk"
# そっと唇にキスをして、それからもう一度サランをギュッと抱きしめる。
line = "そっと唇にキスをして、それからもう一度サランをギュッと抱きしめる。"

[[dialogue]]
speaker = "unk"
# そのぬくもりと柔らかさを感じながら、心地よい疲労感に身を任せるのだった。
line = "そのぬくもりと柔らかさを感じながら、心地よい疲労感に身を任せるのだった。"
