[[dialogue]]
speaker = "unk"
# 第１話,体は小さくなっても,P
line = "第１話,体は小さくなっても,P"

[[dialogue]]
speaker = "unk"
# アルモが附属校に通うようになってから、しばらく経ったある休日のこと。彼女から遊びに行こうと誘われて、俺は街へとやってきていた。
line = "アルモが附属校に通うようになってから、しばらく経ったある休日のこと。彼女から遊びに行こうと誘われて、俺は街へとやってきていた。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「会長～！　早く早くなのだ～！」
line = "「会長～！　早く早くなのだ～！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――今日はいつにも増して元気？　だって、会長と久しぶりのデートなのだ♪」
line = "「――今日はいつにも増して元気？　だって、会長と久しぶりのデートなのだ♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「あっ、でも、この体で一緒にデートするのは初めてだな！　そう考えると、なんだか新鮮な感じがするのだ！」
line = "「あっ、でも、この体で一緒にデートするのは初めてだな！　そう考えると、なんだか新鮮な感じがするのだ！」"

[[dialogue]]
speaker = "unk"
# なぜアルモの体が小さくなっているのかといえば、附属校に通う為にスペアボディ『幼アバター』を使用しているからである。
line = "なぜアルモの体が小さくなっているのかといえば、附属校に通う為にスペアボディ『幼アバター』を使用しているからである。"

[[dialogue]]
speaker = "unk"
# 元々は以前現れた新種モンスターから受けた攻撃の影響で、一時的に本体アバターが使用不能になり、その代わりとして使い始めたのがきっかけだ。
line = "元々は以前現れた新種モンスターから受けた攻撃の影響で、一時的に本体アバターが使用不能になり、その代わりとして使い始めたのがきっかけだ。"

[[dialogue]]
speaker = "unk"
# 最近は附属校生活が楽しいようで、こちらの姿でいることの方が多い。
line = "最近は附属校生活が楽しいようで、こちらの姿でいることの方が多い。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「さて、今日はまず、レジャー施設で思いっきり遊ぶのだ！」
line = "「さて、今日はまず、レジャー施設で思いっきり遊ぶのだ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ＤＩＳＣで調べたら、ボウリングとかスポーツとか、色々できる場所があるのを見つけたのだ！」
line = "「ＤＩＳＣで調べたら、ボウリングとかスポーツとか、色々できる場所があるのを見つけたのだ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――ん？　食べ歩きはしないのかって？」
line = "「――ん？　食べ歩きはしないのかって？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ふっふっふ……アルモたんはこの体になって、新たな学びを得たのだ。それは――」
line = "「ふっふっふ……アルモたんはこの体になって、新たな学びを得たのだ。それは――」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「いっぱい遊んで、お腹が空いてから食べるお肉は、すごく美味ということなのだ！」
line = "「いっぱい遊んで、お腹が空いてから食べるお肉は、すごく美味ということなのだ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「だから会長、午前中はアルモたんと思いっきり遊ぶのだ！」
line = "「だから会長、午前中はアルモたんと思いっきり遊ぶのだ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「それじゃあ、手を繋いで出発なのだ♪」
line = "「それじゃあ、手を繋いで出発なのだ♪」"

[[dialogue]]
speaker = "unk"
# それからレジャー施設に行って、ボウリングや卓球等で遊び倒した後、午後からは食べ歩きをすることになった。
line = "それからレジャー施設に行って、ボウリングや卓球等で遊び倒した後、午後からは食べ歩きをすることになった。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「もぐもぐ♪　ん～、やっぱりお腹が減るまで遊んだ後に食べるお肉は格別なのだ！」
line = "「もぐもぐ♪　ん～、やっぱりお腹が減るまで遊んだ後に食べるお肉は格別なのだ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ほら、会長も１本どうぞなのだ♪　ここのお店の牛串、すごく美味なのだぞ？」
line = "「ほら、会長も１本どうぞなのだ♪　ここのお店の牛串、すごく美味なのだぞ？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「どうなのだ？　少しは元気が出たか？」
line = "「どうなのだ？　少しは元気が出たか？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――それならよかったのだ！　最近の会長は、ちょっと変だったからな」
line = "「――それならよかったのだ！　最近の会長は、ちょっと変だったからな」"

[[dialogue]]
speaker = "unk"
# え？　変って？
line = "え？　変って？"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「なんだか……最近は、アルモたんとの間に、少し距離があるような感じがしたのだ。そう――」
line = "「なんだか……最近は、アルモたんとの間に、少し距離があるような感じがしたのだ。そう――」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「恋人として付き合う前の感じに、戻ってしまったみたいな」
line = "「恋人として付き合う前の感じに、戻ってしまったみたいな」"

[[dialogue]]
speaker = "unk"
# 実は、アルモが幼アバターを使い始める少し前、互いに好意を伝え合って、俺たちは恋人関係になっていた。ただ……
line = "実は、アルモが幼アバターを使い始める少し前、互いに好意を伝え合って、俺たちは恋人関係になっていた。ただ……"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――アルモたんが幼アバターを使うようになってから、雰囲気が変わったから、同じように接していいかわからなくなってた……？」
line = "「――アルモたんが幼アバターを使うようになってから、雰囲気が変わったから、同じように接していいかわからなくなってた……？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「う～ん、自分ではそこまで変わったつもりはないのだが……確かに周りからはよく、幼くなっているとツッコまれるのだ」
line = "「う～ん、自分ではそこまで変わったつもりはないのだが……確かに周りからはよく、幼くなっているとツッコまれるのだ」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「でも、そういう風に思われてるということは、アルモたんの気持ちが、会長にしっかり伝わっていなかったということなのだな」
line = "「でも、そういう風に思われてるということは、アルモたんの気持ちが、会長にしっかり伝わっていなかったということなのだな」"

[[dialogue]]
speaker = "unk"
# ごめん……
line = "ごめん……"

[[dialogue]]
speaker = "unk"
# 幼アバターになったことで、ひょっとしたらアルモの俺に対する好意も変化してしまっているかもしれないと、恋人としての距離感を測りかねてしまったのだ。
line = "幼アバターになったことで、ひょっとしたらアルモの俺に対する好意も変化してしまっているかもしれないと、恋人としての距離感を測りかねてしまったのだ。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「う～ん……そうだ！　なら、いいことを思い付いたのだ！」
line = "「う～ん……そうだ！　なら、いいことを思い付いたのだ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「天使の羽でふわっと浮いて～……えいっ♪」
line = "「天使の羽でふわっと浮いて～……えいっ♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ん～<emoji=heart04>　……ちゅっ<emoji=heart04>」
line = "「ん～<emoji=heart04>　……ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――えへへ♪　いきなり唇にキスをされて、驚いたのだ？」
line = "「――えへへ♪　いきなり唇にキスをされて、驚いたのだ？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「距離感がわからなくなってしまったのなら、『好き』をもう１度ここからやり直せばいいのだ♪」
line = "「距離感がわからなくなってしまったのなら、『好き』をもう１度ここからやり直せばいいのだ♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「会長、周りが言うように、アルモたんの精神は少し変化しているのかもしれないのだ。でも――」
line = "「会長、周りが言うように、アルモたんの精神は少し変化しているのかもしれないのだ。でも――」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「会長に対する『好き』という気持ちは、前から変わっていないのだ！　――ああいや、嘘を言ったのだ」
line = "「会長に対する『好き』という気持ちは、前から変わっていないのだ！　――ああいや、嘘を言ったのだ」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「アルモたんはこの体になって、会長への好きという気持ちは、前より大きくなったのだ！」
line = "「アルモたんはこの体になって、会長への好きという気持ちは、前より大きくなったのだ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「だから、会長。改めて、言うのだ」
line = "「だから、会長。改めて、言うのだ」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「アルモたんは会長のことが好きだぞ。だから――この体でも恋人として付き合って欲しいのだ」
line = "「アルモたんは会長のことが好きだぞ。だから――この体でも恋人として付き合って欲しいのだ」"

[[dialogue]]
speaker = "unk"
# 俺も、アルモのことが好きだ
line = "俺も、アルモのことが好きだ"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「えへへ……<emoji=heart04>　これで、２度目の両想いだな♪」
line = "「えへへ……<emoji=heart04>　これで、２度目の両想いだな♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――言わせちゃって、ごめんって？　謝らなくていいのだ！」
line = "「――言わせちゃって、ごめんって？　謝らなくていいのだ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「前は会長の方から告白してもらったし……これでおあいこなのだ♪」
line = "「前は会長の方から告白してもらったし……これでおあいこなのだ♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「あ……<emoji=heart04>　ふふっ、頭撫でるの、くすぐったいのだ……♪」
line = "「あ……<emoji=heart04>　ふふっ、頭撫でるの、くすぐったいのだ……♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――それじゃあ、ここから恋人同士のデート、再開だな♪」
line = "「――それじゃあ、ここから恋人同士のデート、再開だな♪」"

[[dialogue]]
speaker = "unk"
# 恋人らしく、今度は俺からアルモの手を取って、繋ぐ。すると――
line = "恋人らしく、今度は俺からアルモの手を取って、繋ぐ。すると――"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「あ……！　恋人繋ぎ……えへへぇ<emoji=heart04>」
line = "「あ……！　恋人繋ぎ……えへへぇ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 彼女は嬉しそうな笑顔を見せて、俺の手を握り返してくれるのだった。
line = "彼女は嬉しそうな笑顔を見せて、俺の手を握り返してくれるのだった。"
