[[dialogue]]
speaker = "リア"
# 「ぎゅ～……<emoji=heart04>　ふふ、落ち着いちゃうなぁ～」
line = "「ぎゅ～……<emoji=heart04>　ふふ、落ち着いちゃうなぁ～」"

[[dialogue]]
speaker = "シン"
# 「さ、流石に抱きつきすぎですって（汗）」
line = "「さ、流石に抱きつきすぎですって（汗）」"

[[dialogue]]
speaker = "リア"
# 「逃げちゃダーメ。充電中なんだから♪　もうしばらく抱きつかせて？」
line = "「逃げちゃダーメ。充電中なんだから♪　もうしばらく抱きつかせて？」"

[[dialogue]]
speaker = "シン"
# 「よ、よっぽど大変だったんですね？　平行世界に行ったとか話してましたけど……」
line = "「よ、よっぽど大変だったんですね？　平行世界に行ったとか話してましたけど……」"

[[dialogue]]
speaker = "リア"
# 「事件が大変だったのもあるけど、先輩として気を張りっぱなしだったからね。こうして気を抜く暇もなくて……」
line = "「事件が大変だったのもあるけど、先輩として気を張りっぱなしだったからね。こうして気を抜く暇もなくて……」"

[[dialogue]]
speaker = "リア"
# 「夜遅くに呼び出しちゃってごめんね？　こういう時に甘えられるのってシン君だけだから」
line = "「夜遅くに呼び出しちゃってごめんね？　こういう時に甘えられるのってシン君だけだから」"

[[dialogue]]
speaker = "シン"
# 「いえいえ。彼氏冥利に尽きますよ」
line = "「いえいえ。彼氏冥利に尽きますよ」"

[[dialogue]]
speaker = "リア"
# 「えへへ、さっすがシン君♪　なら遠慮なく甘えちゃおうかな<emoji=heart04>」
line = "「えへへ、さっすがシン君♪　なら遠慮なく甘えちゃおうかな<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そう言ってリア先輩が僕の顔に頬ずりしながら、体に回した手にぎゅっと力を込めて抱き締めてくる。
line = "そう言ってリア先輩が僕の顔に頬ずりしながら、体に回した手にぎゅっと力を込めて抱き締めてくる。"

[[dialogue]]
speaker = "unk"
# まるで抱き枕にでもなった気分だ。でもむしろ役得というか。
line = "まるで抱き枕にでもなった気分だ。でもむしろ役得というか。"

[[dialogue]]
speaker = "unk"
# リア先輩の体温に包まれて、おっぱいもむにゅんむにゅんと押しつけられて、体がどんどん火照っていってしまう。
line = "リア先輩の体温に包まれて、おっぱいもむにゅんむにゅんと押しつけられて、体がどんどん火照っていってしまう。"

[[dialogue]]
speaker = "リア"
# 「あ……ふふふ、エッチな顔になってるゾ♪」
line = "「あ……ふふふ、エッチな顔になってるゾ♪」"

[[dialogue]]
speaker = "シン"
# 「っっ。す、すみません」
line = "「っっ。す、すみません」"

[[dialogue]]
speaker = "リア"
# 「謝らなくてもいいよ。私もシン君とイチャイチャしたくてここに呼んだんだから」
line = "「謝らなくてもいいよ。私もシン君とイチャイチャしたくてここに呼んだんだから」"

[[dialogue]]
speaker = "リア"
# 「たくさん、んっ……ちゅっ……<emoji=heart04>　イチャイチャしよ<emoji=heart04>　めいっぱい甘えさせて欲しいな♪　ここなら誰かに見られる心配もないし♪」
line = "「たくさん、んっ……ちゅっ……<emoji=heart04>　イチャイチャしよ<emoji=heart04>　めいっぱい甘えさせて欲しいな♪　ここなら誰かに見られる心配もないし♪」"

[[dialogue]]
speaker = "unk"
# 恋人になってからというもの、リア先輩が日に日に甘えん坊になってきている気がする。
line = "恋人になってからというもの、リア先輩が日に日に甘えん坊になってきている気がする。"

[[dialogue]]
speaker = "unk"
# 普段は先輩としてみんなの面倒を見てくれているけど、二人きりになるとそれはもう子供みたいに甘えてくれるようになって──
line = "普段は先輩としてみんなの面倒を見てくれているけど、二人きりになるとそれはもう子供みたいに甘えてくれるようになって──"

[[dialogue]]
speaker = "リア"
# 「はぁはぁ、えへへ……<emoji=heart04>　くっついてるだけで、すごくエッチな気分になってきちゃった……<emoji=heart04>」
line = "「はぁはぁ、えへへ……<emoji=heart04>　くっついてるだけで、すごくエッチな気分になってきちゃった……<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「そういうコトも……おねだりしちゃっていい？」
line = "「そういうコトも……おねだりしちゃっていい？」"

[[dialogue]]
speaker = "unk"
# 頬を赤くして尋ねてきてくれるリア先輩がものすごく可愛い。
line = "頬を赤くして尋ねてきてくれるリア先輩がものすごく可愛い。"

[[dialogue]]
speaker = "unk"
# 口で返事するよりも先に体の方が反応してしまう。
line = "口で返事するよりも先に体の方が反応してしまう。"

[[dialogue]]
speaker = "リア"
# 「えへへ、決まり……だね<emoji=heart04>　じゃあ、こっち来て？」
line = "「えへへ、決まり……だね<emoji=heart04>　じゃあ、こっち来て？」"

[[dialogue]]
speaker = "unk"
# 膨れあがったズボンを見てリア先輩が頬を赤くして微笑む。そして、僕を窓際の方へ引っ張って行くと──
line = "膨れあがったズボンを見てリア先輩が頬を赤くして微笑む。そして、僕を窓際の方へ引っ張って行くと──"

[[dialogue]]
speaker = "リア"
# 「はぁ、はぁ……<emoji=heart04>　おっきいのがお尻に当たって……<emoji=heart04>」
line = "「はぁ、はぁ……<emoji=heart04>　おっきいのがお尻に当たって……<emoji=heart04>」"

[[dialogue]]
speaker = "シン"
# 「立ったままでいいんですか？　ソファーの上とか机の上に寝転がっても……」
line = "「立ったままでいいんですか？　ソファーの上とか机の上に寝転がっても……」"

[[dialogue]]
speaker = "リア"
# 「今夜はめいっぱいあなたを感じたいから……<emoji=heart04>　後ろから思いっきりズンズンして欲しくって……<emoji=heart04>」
line = "「今夜はめいっぱいあなたを感じたいから……<emoji=heart04>　後ろから思いっきりズンズンして欲しくって……<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「この体勢なら奥の奥まで入ってくるから……<emoji=heart04>　ものすごく気持ち良くなれるし……<emoji=heart04>」
line = "「この体勢なら奥の奥まで入ってくるから……<emoji=heart04>　ものすごく気持ち良くなれるし……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 熱っぽい吐息を漏らしながらリア先輩が可愛いお尻を突き出してきてくれる。
line = "熱っぽい吐息を漏らしながらリア先輩が可愛いお尻を突き出してきてくれる。"

[[dialogue]]
speaker = "unk"
# まるで尻尾を振っておねだりする子犬のようだ。そんな姿を恥ずかしがらずに僕へ見せてくれることが嬉しい。
line = "まるで尻尾を振っておねだりする子犬のようだ。そんな姿を恥ずかしがらずに僕へ見せてくれることが嬉しい。"

[[dialogue]]
speaker = "リア"
# 「めいっぱい甘えちゃっていいんだよね？　なら、はぁはぁ、うんと気持ち良くして欲しいな……<emoji=heart04>」
line = "「めいっぱい甘えちゃっていいんだよね？　なら、はぁはぁ、うんと気持ち良くして欲しいな……<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「それとも流石に甘えすぎ、かな？　お姉ちゃんらしくないよね？」
line = "「それとも流石に甘えすぎ、かな？　お姉ちゃんらしくないよね？」"

[[dialogue]]
speaker = "シン"
# 「甘えてもらえるの、すごく嬉しいです。先輩に信頼してもらってるんだなぁって実感できますから」
line = "「甘えてもらえるの、すごく嬉しいです。先輩に信頼してもらってるんだなぁって実感できますから」"

[[dialogue]]
speaker = "リア"
# 「ふふ、恋人になる前から信頼してるよ♪　今はそれ以上に、愛してるの（はぁと）」
line = "「ふふ、恋人になる前から信頼してるよ♪　今はそれ以上に、愛してるの（はぁと）」"

[[dialogue]]
speaker = "リア"
# 「だから、ね？　早く、ん……はぁ、挿れて？」
line = "「だから、ね？　早く、ん……はぁ、挿れて？」"

[[dialogue]]
speaker = "リア"
# 「あんまり焦らされると、はぁ……んぁ……。どんどん切なくなってきちゃうから……<emoji=heart04>」
line = "「あんまり焦らされると、はぁ……んぁ……。どんどん切なくなってきちゃうから……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# リア先輩が軽く腰を揺らして濡れそぼった秘部をペニスに擦り付けてくる。
line = "リア先輩が軽く腰を揺らして濡れそぼった秘部をペニスに擦り付けてくる。"

[[dialogue]]
speaker = "unk"
# こんなに可愛くおねだりされて、我慢できるわけがなかった。
line = "こんなに可愛くおねだりされて、我慢できるわけがなかった。"

[[dialogue]]
speaker = "リア"
# 「あぁあああんっ<emoji=heart04>　ふぁっ、あっ、くぁんっ、あはぁんっ<emoji=heart04>」
line = "「あぁあああんっ<emoji=heart04>　ふぁっ、あっ、くぁんっ、あはぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「気持ち、いいっ<emoji=heart04>　もっと、んぁぁっ、もっと深々と挿れてっ……<emoji=heart04>」
line = "「気持ち、いいっ<emoji=heart04>　もっと、んぁぁっ、もっと深々と挿れてっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 腰を振る度に繋がった場所からエッチな愛液が飛び散る。ものすごくグチョグチョだ。
line = "腰を振る度に繋がった場所からエッチな愛液が飛び散る。ものすごくグチョグチョだ。"

[[dialogue]]
speaker = "リア"
# 「やぁ<emoji=heart04>　水音、ふぁぁっ、恥ずかしっ……<emoji=heart04>　自分でもビックリしちゃうくらい、んぁっ、あっ、はぁっ、濡れちゃってるっ……<emoji=heart04>」
line = "「やぁ<emoji=heart04>　水音、ふぁぁっ、恥ずかしっ……<emoji=heart04>　自分でもビックリしちゃうくらい、んぁっ、あっ、はぁっ、濡れちゃってるっ……<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「想像以上に私、あっ、あっ、溜まっちゃってたのかもっ……<emoji=heart04>　数日会えなかっただけなのにっ<emoji=heart04>　数日エッチしなかっただけなのにっ<emoji=heart04>」
line = "「想像以上に私、あっ、あっ、溜まっちゃってたのかもっ……<emoji=heart04>　数日会えなかっただけなのにっ<emoji=heart04>　数日エッチしなかっただけなのにっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「エッチなおつゆ、はふあぁ、どんどん溢れてきちゃっ……<emoji=heart04>　ズンズンしてもらう度に、じゅわわって満ち満ちてきてっ……<emoji=heart04>」
line = "「エッチなおつゆ、はふあぁ、どんどん溢れてきちゃっ……<emoji=heart04>　ズンズンしてもらう度に、じゅわわって満ち満ちてきてっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 今までにないほどリア先輩が発情してくれているのがわかる。
line = "今までにないほどリア先輩が発情してくれているのがわかる。"

[[dialogue]]
speaker = "unk"
# 膣内がまるで生き物のようにうねって、いやらしく僕のペニスにしゃぶりついてきて。
line = "膣内がまるで生き物のようにうねって、いやらしく僕のペニスにしゃぶりついてきて。"

[[dialogue]]
speaker = "unk"
# そのトロトロでギュウギュウの感触がたまらない。僕も一心不乱にピストンを続けてしまう。
line = "そのトロトロでギュウギュウの感触がたまらない。僕も一心不乱にピストンを続けてしまう。"

[[dialogue]]
speaker = "リア"
# 「あっ、あっ、あっ、あっ<emoji=heart04>　体のビクビクとまらないよぉっ<emoji=heart04>　いつもより、はふぁぁ、そこら中敏感になっちゃってるっ<emoji=heart04>」
line = "「あっ、あっ、あっ、あっ<emoji=heart04>　体のビクビクとまらないよぉっ<emoji=heart04>　いつもより、はふぁぁ、そこら中敏感になっちゃってるっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「おち○ちんも、んぁっ、いつもよりおっきいっ<emoji=heart04>　もしかしなくても、会えない間も自分でしないでくれてたのかなっ？」
line = "「おち○ちんも、んぁっ、いつもよりおっきいっ<emoji=heart04>　もしかしなくても、会えない間も自分でしないでくれてたのかなっ？」"

[[dialogue]]
speaker = "リア"
# 「だったら、あっ、あっ、好きなだけズンズンしていいよっ<emoji=heart04>　ううんっ、いっぱいズンズンしてっ<emoji=heart04>」
line = "「だったら、あっ、あっ、好きなだけズンズンしていいよっ<emoji=heart04>　ううんっ、いっぱいズンズンしてっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「今夜は二人で数日分のエッチ、しよっ<emoji=heart04>　いっぱいいっぱい愛してもらいたいなっ<emoji=heart04>」
line = "「今夜は二人で数日分のエッチ、しよっ<emoji=heart04>　いっぱいいっぱい愛してもらいたいなっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 可愛く喘ぎながらもリア先輩が甘えてきてくれて、よりいっそうペニスが硬く膨らんでしまう。
line = "可愛く喘ぎながらもリア先輩が甘えてきてくれて、よりいっそうペニスが硬く膨らんでしまう。"

[[dialogue]]
speaker = "unk"
# 膣内の感触もたまらないほど気持ちいいけど、突き入れる度にブルンブルン弾む大きなおっぱいがこれまたエッチで──
line = "膣内の感触もたまらないほど気持ちいいけど、突き入れる度にブルンブルン弾む大きなおっぱいがこれまたエッチで──"

[[dialogue]]
speaker = "リア"
# 「えへへっ、おっぱいばっかり見つめちゃってっ……<emoji=heart04>　相変わらず、あっ、はぁっ、おっぱいが大好きなんだねっ<emoji=heart04>」
line = "「えへへっ、おっぱいばっかり見つめちゃってっ……<emoji=heart04>　相変わらず、あっ、はぁっ、おっぱいが大好きなんだねっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「いいよっ<emoji=heart04>　もっと、あっ、あっ、もっと私のおっぱい揺らしてっ？　激しくブルンブルンさせちゃってっ？」
line = "「いいよっ<emoji=heart04>　もっと、あっ、あっ、もっと私のおっぱい揺らしてっ？　激しくブルンブルンさせちゃってっ？」"

[[dialogue]]
speaker = "リア"
# 「私も、ふぁっ、あっ、はぁっ、もっともっとズンズンしてもらいたいなっ<emoji=heart04>　おま○この奥、んぁぁっ、思いっきりズドンズドンして欲しいっ<emoji=heart04>」
line = "「私も、ふぁっ、あっ、はぁっ、もっともっとズンズンしてもらいたいなっ<emoji=heart04>　おま○この奥、んぁぁっ、思いっきりズドンズドンして欲しいっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「そのくらいしてもらわないと、はぁっ、はぁっ、今夜はおさまりそうにないからっ<emoji=heart04>　アソコ疼いてたまらないからっ<emoji=heart04>」
line = "「そのくらいしてもらわないと、はぁっ、はぁっ、今夜はおさまりそうにないからっ<emoji=heart04>　アソコ疼いてたまらないからっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「向こうにいる間、私の中のエッチな風船がずーっと膨らみ続けてたのっ……<emoji=heart04>　イチャイチャできなくて切なくて、もどかしくて、もうパンパンになっちゃってるのっ<emoji=heart04>」
line = "「向こうにいる間、私の中のエッチな風船がずーっと膨らみ続けてたのっ……<emoji=heart04>　イチャイチャできなくて切なくて、もどかしくて、もうパンパンになっちゃってるのっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「だからっ、はぁはぁっ、だからぁっ……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「だからっ、はぁはぁっ、だからぁっ……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 生半可な抽挿じゃ足りないとばかりにリア先輩がお尻をぐっぐと突き出して、少しでもセックスの快感を貪ろうとしてくる。
line = "生半可な抽挿じゃ足りないとばかりにリア先輩がお尻をぐっぐと突き出して、少しでもセックスの快感を貪ろうとしてくる。"

[[dialogue]]
speaker = "unk"
# こんなに欲求不満になっちゃうくらい、向こうの世界にいる間も僕を想い続けてくれていて──
line = "こんなに欲求不満になっちゃうくらい、向こうの世界にいる間も僕を想い続けてくれていて──"

[[dialogue]]
speaker = "リア"
# 「はひぃんっっ<emoji=heart04>　あはっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　くぁっ<emoji=heart04>　あふぅんっっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「はひぃんっっ<emoji=heart04>　あはっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　くぁっ<emoji=heart04>　あふぅんっっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「しゅごひっ<emoji=heart04>　あああぁんっっ<emoji=heart04>　きもひいいっっ<emoji=heart04>　いつもより乱暴でっ、ああああっ、だけどそれがまひゃっっ<emoji=heart04>」
line = "「しゅごひっ<emoji=heart04>　あああぁんっっ<emoji=heart04>　きもひいいっっ<emoji=heart04>　いつもより乱暴でっ、ああああっ、だけどそれがまひゃっっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 自分でも突き込み過ぎかと思うくらい先輩の膣内にペニスをねじ込む。
line = "自分でも突き込み過ぎかと思うくらい先輩の膣内にペニスをねじ込む。"

[[dialogue]]
speaker = "unk"
# しかしリア先輩はそんな荒々しいばかりの抽挿を蕩けた顔で悦んでくれた。
line = "しかしリア先輩はそんな荒々しいばかりの抽挿を蕩けた顔で悦んでくれた。"

[[dialogue]]
speaker = "リア"
# 「イクイクっ<emoji=heart04>　イっちゃっ<emoji=heart04>　きもひいいっっ<emoji=heart04>　しゅごくきもひいいよぉっ<emoji=heart04>」
line = "「イクイクっ<emoji=heart04>　イっちゃっ<emoji=heart04>　きもひいいっっ<emoji=heart04>　しゅごくきもひいいよぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「私の中のエッチな風船、弾けちゃふっ<emoji=heart04>　これが、あふぁっ、ずっとこれが欲しかったのぉっ<emoji=heart04>」
line = "「私の中のエッチな風船、弾けちゃふっ<emoji=heart04>　これが、あふぁっ、ずっとこれが欲しかったのぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「大好きな人のおち○ちんがっ<emoji=heart04>　あっ、あっ、あっ<emoji=heart04>　こうやって、ふぁぁぁっっ、いっぱいズドズドして欲しかったのぉっ<emoji=heart04>」
line = "「大好きな人のおち○ちんがっ<emoji=heart04>　あっ、あっ、あっ<emoji=heart04>　こうやって、ふぁぁぁっっ、いっぱいズドズドして欲しかったのぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# すごい締め付けだ。ペニスが千切れそうなくらいギュウギュウ閉じてきてくれる。愛液の量も一気に増えて……！
line = "すごい締め付けだ。ペニスが千切れそうなくらいギュウギュウ閉じてきてくれる。愛液の量も一気に増えて……！"

[[dialogue]]
speaker = "unk"
# あまりの気持ちよさにピストンのスピードがどんどん上がっていく。ブルンブルンと淫らに弾むおっぱいをオカズにより突き上げてしまう。
line = "あまりの気持ちよさにピストンのスピードがどんどん上がっていく。ブルンブルンと淫らに弾むおっぱいをオカズにより突き上げてしまう。"

[[dialogue]]
speaker = "リア"
# 「あっ、はぁっ、あっ、あああっ<emoji=heart04>　おっぱい揺れるだけでも感じちゃっ<emoji=heart04>　おち○ちんでブルンブルン揺らされるのきもひいいっ<emoji=heart04>」
line = "「あっ、はぁっ、あっ、あああっ<emoji=heart04>　おっぱい揺れるだけでも感じちゃっ<emoji=heart04>　おち○ちんでブルンブルン揺らされるのきもひいいっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「おち○ちんもどんどん熱くなってきてるっ<emoji=heart04>　ああっ、これっ、これ好きっ<emoji=heart04>　大好きな人が我慢できなくなってくれてる感覚ぅっ<emoji=heart04>」
line = "「おち○ちんもどんどん熱くなってきてるっ<emoji=heart04>　ああっ、これっ、これ好きっ<emoji=heart04>　大好きな人が我慢できなくなってくれてる感覚ぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「ただでさえおっきいのにっ、ふぁああっっ、膣内でミチミチ膨らんでっ<emoji=heart04>　私のおま○こ、やらしく広げられちゃってっ<emoji=heart04>」
line = "「ただでさえおっきいのにっ、ふぁああっっ、膣内でミチミチ膨らんでっ<emoji=heart04>　私のおま○こ、やらしく広げられちゃってっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「もっとぉっ<emoji=heart04>　もっと膨らませてっ<emoji=heart04>　ガッチガチのバッキバキにしてっ<emoji=heart04>」
line = "「もっとぉっ<emoji=heart04>　もっと膨らませてっ<emoji=heart04>　ガッチガチのバッキバキにしてっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「あなたが興奮してくれてるのわかると、あはぁあんっっ<emoji=heart04>　私も興奮しちゃうからぁっ<emoji=heart04>　さらに気持ち良くなっちゃうからぁっ<emoji=heart04>」
line = "「あなたが興奮してくれてるのわかると、あはぁあんっっ<emoji=heart04>　私も興奮しちゃうからぁっ<emoji=heart04>　さらに気持ち良くなっちゃうからぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 僕の射精欲を察したリア先輩が膣内をビクビク痙攣させながら、中出しをねだるように子宮を下ろしてきてくれる。
line = "僕の射精欲を察したリア先輩が膣内をビクビク痙攣させながら、中出しをねだるように子宮を下ろしてきてくれる。"

[[dialogue]]
speaker = "unk"
# そのエッチな甘えっぷりがとんでもなく嬉しかった。僕とのセックスを、中出しを、心から期待してくれていて──
line = "そのエッチな甘えっぷりがとんでもなく嬉しかった。僕とのセックスを、中出しを、心から期待してくれていて──"

[[dialogue]]
speaker = "リア"
# 「くぁっ、あっ、あっ、あっ<emoji=heart04>　一段とはげひっっ<emoji=heart04>　あああああっ、らめっ、イっひゃっ<emoji=heart04>」
line = "「くぁっ、あっ、あっ、あっ<emoji=heart04>　一段とはげひっっ<emoji=heart04>　あああああっ、らめっ、イっひゃっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「きもひよすぎへ、口とじられにゃひっ<emoji=heart04>　あふぁあっっ<emoji=heart04>　あああああっっ<emoji=heart04>　イきゅイきゅイきゅぅぅぅっっ<emoji=heart04>」
line = "「きもひよすぎへ、口とじられにゃひっ<emoji=heart04>　あふぁあっっ<emoji=heart04>　あああああっっ<emoji=heart04>　イきゅイきゅイきゅぅぅぅっっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「割っへぇっ<emoji=heart04>　わたひの欲求不満っ、あなひゃのおひんひんで解消しへぇっ<emoji=heart04>　わたひの甘えんぼおま○こ慰めへぇっ<emoji=heart04>」
line = "「割っへぇっ<emoji=heart04>　わたひの欲求不満っ、あなひゃのおひんひんで解消しへぇっ<emoji=heart04>　わたひの甘えんぼおま○こ慰めへぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「本当にずっひょ寂しかっひゃのっ<emoji=heart04>　切なかっひゃのぉっ<emoji=heart04>　あなひゃとエッチれきにゃくへ、ずっひょ、ずっひょぉっ<emoji=heart04>」
line = "「本当にずっひょ寂しかっひゃのっ<emoji=heart04>　切なかっひゃのぉっ<emoji=heart04>　あなひゃとエッチれきにゃくへ、ずっひょ、ずっひょぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「あつひの欲ひいっ<emoji=heart04>　中にいっぱひ出しへ欲ひいっ<emoji=heart04>　あなひゃのしゃーせーでイキひゃいっ<emoji=heart04>　おもいっきりイキひゃいっっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あつひの欲ひいっ<emoji=heart04>　中にいっぱひ出しへ欲ひいっ<emoji=heart04>　あなひゃのしゃーせーでイキひゃいっ<emoji=heart04>　おもいっきりイキひゃいっっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 僕もイキたいっ。リア先輩の甘えんぼおま○こでっ。こんなにも僕を求めてくれるエッチなおま○こでっ……！！
line = "僕もイキたいっ。リア先輩の甘えんぼおま○こでっ。こんなにも僕を求めてくれるエッチなおま○こでっ……！！"

[[dialogue]]
speaker = "リア"
# 「あっ、あっ、あっ、あっ、あっ<emoji=heart04>　きへりゅっ<emoji=heart04>　のぼってきへりゅっ<emoji=heart04>」
line = "「あっ、あっ、あっ、あっ、あっ<emoji=heart04>　きへりゅっ<emoji=heart04>　のぼってきへりゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「わたひもしゅごいのくりゅっ<emoji=heart04>　エッチな風船が私のおっぱいみたいにパツンパツンに膨らんできちゃふぅっっ<emoji=heart04>」
line = "「わたひもしゅごいのくりゅっ<emoji=heart04>　エッチな風船が私のおっぱいみたいにパツンパツンに膨らんできちゃふぅっっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「弾けさせへっ<emoji=heart04>　あなひゃのおち○ちんミルクれ、んぁっ、あっ、あぁあんっ、弾けさせへぇっ<emoji=heart04>」
line = "「弾けさせへっ<emoji=heart04>　あなひゃのおち○ちんミルクれ、んぁっ、あっ、あぁあんっ、弾けさせへぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「数日分の溜まったせーしっ<emoji=heart04>　エッチできなくへウズウズしへたイチャラブせーしぃっ<emoji=heart04>」
line = "「数日分の溜まったせーしっ<emoji=heart04>　エッチできなくへウズウズしへたイチャラブせーしぃっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「わたひの甘えんぼおま○こにぃっ<emoji=heart04>　ああああっっ<emoji=heart04>　寂しがり屋の赤ちゃんの部屋にぃっっ<emoji=heart04>」
line = "「わたひの甘えんぼおま○こにぃっ<emoji=heart04>　ああああっっ<emoji=heart04>　寂しがり屋の赤ちゃんの部屋にぃっっ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「全部全部っ──ぶちまけてぇぇぇぇえっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「全部全部っ──ぶちまけてぇぇぇぇえっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「あっ──ああああああああああああっっ<emoji=heart04><emoji=heart04><emoji=heart04>　イきゅイきゅイきゅぅぅぅぅぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あっ──ああああああああああああっっ<emoji=heart04><emoji=heart04><emoji=heart04>　イきゅイきゅイきゅぅぅぅぅぅぅっっ～～<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ガクガクガクぅぅっとリア先輩が体中を震わせながら、腰を海老反らせる。
line = "ガクガクガクぅぅっとリア先輩が体中を震わせながら、腰を海老反らせる。"

[[dialogue]]
speaker = "unk"
# 僕もそんなリア先輩の体を抱えながら、溜まりに溜まった精子を膣内に注ぎ続ける。
line = "僕もそんなリア先輩の体を抱えながら、溜まりに溜まった精子を膣内に注ぎ続ける。"

[[dialogue]]
speaker = "リア"
# 「ふぁああああああああっ<emoji=heart04><emoji=heart04>　さいこうにきもひいいっっ……<emoji=heart04>　割れっ<emoji=heart04>　エッチな風船割れたぁぁぁっ……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「ふぁああああああああっ<emoji=heart04><emoji=heart04>　さいこうにきもひいいっっ……<emoji=heart04>　割れっ<emoji=heart04>　エッチな風船割れたぁぁぁっ……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「やっぱりしゅごひっ<emoji=heart04>　しゃーせーしゅごいっ<emoji=heart04>　きもひいいっ、しあわせぇっ<emoji=heart04>　あ゛ぁっ<emoji=heart04>　あ゛あぁぁぁっっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「やっぱりしゅごひっ<emoji=heart04>　しゃーせーしゅごいっ<emoji=heart04>　きもひいいっ、しあわせぇっ<emoji=heart04>　あ゛ぁっ<emoji=heart04>　あ゛あぁぁぁっっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 口を半開きにしたまま、リア先輩が激しく喘いで僕以上に絶頂し続けてくれる。
line = "口を半開きにしたまま、リア先輩が激しく喘いで僕以上に絶頂し続けてくれる。"

[[dialogue]]
speaker = "unk"
# 僕とのセックスを、中出しを、それだけ嬉しく思ってくれているのがわかって、ちっとも射精がとまらない。
line = "僕とのセックスを、中出しを、それだけ嬉しく思ってくれているのがわかって、ちっとも射精がとまらない。"

[[dialogue]]
speaker = "リア"
# 「ふぁぁぁぁっっ……<emoji=heart04>　きもひいいっ……<emoji=heart04>　イクっ、あふぁっ、イクイクぅぅっ……<emoji=heart04>」
line = "「ふぁぁぁぁっっ……<emoji=heart04>　きもひいいっ……<emoji=heart04>　イクっ、あふぁっ、イクイクぅぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「このまま一生、あふぁぁぁっ……<emoji=heart04>　あなひゃにビュービューしてもらいたいよぉ……<emoji=heart04>」
line = "「このまま一生、あふぁぁぁっ……<emoji=heart04>　あなひゃにビュービューしてもらいたいよぉ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そうして、どれくらい二人でイキ続けただろう。
line = "そうして、どれくらい二人でイキ続けただろう。"

[[dialogue]]
speaker = "リア"
# 「はぁー……<emoji=heart04>　はぁー……<emoji=heart04>　はぁー……<emoji=heart04>　まだ、あふぅ……<emoji=heart04>　ビュルビュルしてくれてる……<emoji=heart04>」
line = "「はぁー……<emoji=heart04>　はぁー……<emoji=heart04>　はぁー……<emoji=heart04>　まだ、あふぅ……<emoji=heart04>　ビュルビュルしてくれてる……<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「そっちも、えへへ……<emoji=heart04>　相当溜まってくれてたんだね……<emoji=heart04>　嬉しい……<emoji=heart04>　好きなだけ出してくれていいからね……<emoji=heart04>」
line = "「そっちも、えへへ……<emoji=heart04>　相当溜まってくれてたんだね……<emoji=heart04>　嬉しい……<emoji=heart04>　好きなだけ出してくれていいからね……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 荒くて甘い吐息を繰り返しながらも、リア先輩がだらしなく射精を続ける僕を甘えさせてくれる。
line = "荒くて甘い吐息を繰り返しながらも、リア先輩がだらしなく射精を続ける僕を甘えさせてくれる。"

[[dialogue]]
speaker = "リア"
# 「でも、たった数日会えなかっただけで、はぁはぁ、こんなにも寂しくなっちゃうんだね……<emoji=heart04>」
line = "「でも、たった数日会えなかっただけで、はぁはぁ、こんなにも寂しくなっちゃうんだね……<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「こんなにも、えへへ……<emoji=heart04>　イチャイチャしたくて、エッチしたくて、たまらなくなっちゃうんだ……<emoji=heart04>」
line = "「こんなにも、えへへ……<emoji=heart04>　イチャイチャしたくて、エッチしたくて、たまらなくなっちゃうんだ……<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「すごく気持ち良くしてもらったのに、はぁはぁ……<emoji=heart04>　もっともっと甘えさせてもらいたくなっちゃうよ……<emoji=heart04>」
line = "「すごく気持ち良くしてもらったのに、はぁはぁ……<emoji=heart04>　もっともっと甘えさせてもらいたくなっちゃうよ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# おねだりするようにギュムムとリア先輩がペニスを抱き締めてきてくれる。僕も先輩が甘えてきてくれるのが嬉しい。
line = "おねだりするようにギュムムとリア先輩がペニスを抱き締めてきてくれる。僕も先輩が甘えてきてくれるのが嬉しい。"

[[dialogue]]
speaker = "unk"
# もっと甘やかしたいし、僕も甘えたくなってしまう。
line = "もっと甘やかしたいし、僕も甘えたくなってしまう。"

[[dialogue]]
speaker = "リア"
# 「あ……<emoji=heart04>　またおっぱいに目が行ってるゾ……<emoji=heart04>　エッチなミルクも先っぽからビュビュって出ちゃってる……<emoji=heart04>」
line = "「あ……<emoji=heart04>　またおっぱいに目が行ってるゾ……<emoji=heart04>　エッチなミルクも先っぽからビュビュって出ちゃってる……<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「えへへ、なら今度は私がおっぱいで気持ち良くしてあげるね<emoji=heart04>　たくさん甘えさせてあげるから……<emoji=heart04>」
line = "「えへへ、なら今度は私がおっぱいで気持ち良くしてあげるね<emoji=heart04>　たくさん甘えさせてあげるから……<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「その代わり、ふふふ<emoji=heart04>　そのあとはまた交代してね<emoji=heart04>　まだまだ私、甘え足りないから……<emoji=heart04>」
line = "「その代わり、ふふふ<emoji=heart04>　そのあとはまた交代してね<emoji=heart04>　まだまだ私、甘え足りないから……<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「今夜は、はぁはぁ……<emoji=heart04>　一晩中、あなたとイチャイチャしたいな……<emoji=heart04>」
line = "「今夜は、はぁはぁ……<emoji=heart04>　一晩中、あなたとイチャイチャしたいな……<emoji=heart04>」"
