[[dialogue]]
speaker = "unk"
# 第１話,フレイムフォーム,P
line = "第１話,フレイムフォーム,P"

[[dialogue]]
speaker = "unk"
# 黒ベア子の出現から一夜明けて……
line = "黒ベア子の出現から一夜明けて……"

[[dialogue]]
speaker = "アポロ"
# 「──ででーん！　どうだ魔王、改めてこいつが……アポロちゃんフレイムフォームだぜ！」
line = "「──ででーん！　どうだ魔王、改めてこいつが……アポロちゃんフレイムフォームだぜ！」"

[[dialogue]]
speaker = "アポロ"
# 「おっと、あんまり近づくとヤケドするぞ。ま──あたしの愛の熱に溶かされたいなら、構わないけどな！」
line = "「おっと、あんまり近づくとヤケドするぞ。ま──あたしの愛の熱に溶かされたいなら、構わないけどな！」"

[[dialogue]]
speaker = "アポロ"
# 「あたしがノリノリだって？　そりゃそうだ、やっぱフォームチェンジっていったらヒーローの華だろ？　まさかこんな形で叶うなんて思わなかったぜ」
line = "「あたしがノリノリだって？　そりゃそうだ、やっぱフォームチェンジっていったらヒーローの華だろ？　まさかこんな形で叶うなんて思わなかったぜ」"

[[dialogue]]
speaker = "アポロ"
# 「フッフッフ──芸術は爆発だ、ってな！　こいつを着てると、全身から『いんすぴれーしょん』が湧いてくる気がするぜ！」
line = "「フッフッフ──芸術は爆発だ、ってな！　こいつを着てると、全身から『いんすぴれーしょん』が湧いてくる気がするぜ！」"

[[dialogue]]
speaker = "unk"
# 不便じゃないの？
line = "不便じゃないの？"

[[dialogue]]
speaker = "アポロ"
# 「ああ。黒ベア子のやつがなんであたしにこれを着せたのかはわかんねーけど……特に動きづらかったりはしないぞ。むしろ身軽なくらいだ」
line = "「ああ。黒ベア子のやつがなんであたしにこれを着せたのかはわかんねーけど……特に動きづらかったりはしないぞ。むしろ身軽なくらいだ」"

[[dialogue]]
speaker = "アポロ"
# 「ただ参ったことに、元のフォームに戻れなくなっちゃってんだよな」
line = "「ただ参ったことに、元のフォームに戻れなくなっちゃってんだよな」"

[[dialogue]]
speaker = "unk"
# ダメじゃん？
line = "ダメじゃん？"

[[dialogue]]
speaker = "アポロ"
# 「うむ……確かに、ずっとこのままってのは良くないかもしれん。パンツとはワケが違うからな」
line = "「うむ……確かに、ずっとこのままってのは良くないかもしれん。パンツとはワケが違うからな」"

[[dialogue]]
speaker = "アポロ"
# 「ん？　元に戻る方法を一緒に探してくれるって？　さすが魔王だな、助かるぞ！」
line = "「ん？　元に戻る方法を一緒に探してくれるって？　さすが魔王だな、助かるぞ！」"

[[dialogue]]
speaker = "アポロ"
# 「ただし！　その前にだ！　この新たに生まれ変わったあたしの姿を、皆の衆に見せびらかしてやるぜ～～！！」
line = "「ただし！　その前にだ！　この新たに生まれ変わったあたしの姿を、皆の衆に見せびらかしてやるぜ～～！！」"

[[dialogue]]
speaker = "マトイ"
# 「あ～も～どうしよどうしよ。アナがいなくちゃ事務仕事が回らないし、サーシャさんにも頼れないし……！」
line = "「あ～も～どうしよどうしよ。アナがいなくちゃ事務仕事が回らないし、サーシャさんにも頼れないし……！」"

[[dialogue]]
speaker = "アポロ"
# 「──邪魔するぜ！」
line = "「──邪魔するぜ！」"

[[dialogue]]
speaker = "マトイ"
# 「──ってわぁっ！？　会長──と、アポロちゃん？」
line = "「──ってわぁっ！？　会長──と、アポロちゃん？」"

[[dialogue]]
speaker = "アポロ"
# 「ふふっ、いかにもだ！　どうだマトイ、生まれ変わったあたしの姿は！」
line = "「ふふっ、いかにもだ！　どうだマトイ、生まれ変わったあたしの姿は！」"

[[dialogue]]
speaker = "マトイ"
# 「な、なんかいつもと違う感じだね……！　すごい情熱を感じるっていうか……！」
line = "「な、なんかいつもと違う感じだね……！　すごい情熱を感じるっていうか……！」"

[[dialogue]]
speaker = "アポロ"
# 「だろ～！？　マトイはよくわかってるな！　この新フォームの魅力を！」
line = "「だろ～！？　マトイはよくわかってるな！　この新フォームの魅力を！」"

[[dialogue]]
speaker = "マトイ"
# 「楽しそう──なのはいいんだけど、こっちは今それどころじゃなくて……星徒会の業務が山盛りなの～！」
line = "「楽しそう──なのはいいんだけど、こっちは今それどころじゃなくて……星徒会の業務が山盛りなの～！」"

[[dialogue]]
speaker = "unk"
# 大変そうだね、マトイ
line = "大変そうだね、マトイ"

[[dialogue]]
speaker = "マトイ"
# 「うんうん、実は……って他人事じゃないでしょ会長！　アナとサーシャさんがいなくなっちゃったんだよ～！？」
line = "「うんうん、実は……って他人事じゃないでしょ会長！　アナとサーシャさんがいなくなっちゃったんだよ～！？」"

[[dialogue]]
speaker = "アポロ"
# 「まあまあ、そう焦るなマトイ。アナとサーシャも今頃、あたしと同じく新フォームに心躍らせてるかもしれないぜ！」
line = "「まあまあ、そう焦るなマトイ。アナとサーシャも今頃、あたしと同じく新フォームに心躍らせてるかもしれないぜ！」"

[[dialogue]]
speaker = "マトイ"
# 「ええ……？　な、何がどうなってるの……？」
line = "「ええ……？　な、何がどうなってるの……？」"

[[dialogue]]
speaker = "アポロ"
# 「ま、その事件もあたしらが解決してやるさ。よおし魔王、次は流星のほうに向かうぞ！」
line = "「ま、その事件もあたしらが解決してやるさ。よおし魔王、次は流星のほうに向かうぞ！」"

[[dialogue]]
speaker = "アポロ"
# 「──はっはっは！　頼もう！」
line = "「──はっはっは！　頼もう！」"

[[dialogue]]
speaker = "セーラ"
# 「うわ、なんか知らん人きた！」
line = "「うわ、なんか知らん人きた！」"

[[dialogue]]
speaker = "ソフィア"
# 「星徒会室という拠点に襲撃を仕掛けてくるとは大した敵です。ただちに撃退の準備を──」
line = "「星徒会室という拠点に襲撃を仕掛けてくるとは大した敵です。ただちに撃退の準備を──」"

[[dialogue]]
speaker = "アポロ"
# 「──待て待て！　あたしだ、アポロだ！」
line = "「──待て待て！　あたしだ、アポロだ！」"

[[dialogue]]
speaker = "ユウリ"
# 「ん？　おお、ホントだ」
line = "「ん？　おお、ホントだ」"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャ！　新たな魅力に目覚めたアポロ嬢なのニャ！」
line = "「ニャ！　新たな魅力に目覚めたアポロ嬢なのニャ！」"

[[dialogue]]
speaker = "アポロ"
# 「ふふん。どうだ、このアポロ様の新衣装は。クールさとホットさが一緒になったナイスデザインだろ？」
line = "「ふふん。どうだ、このアポロ様の新衣装は。クールさとホットさが一緒になったナイスデザインだろ？」"

[[dialogue]]
speaker = "ユウリ"
# 「おおう、なんかイメチェンしてんな。しかもその戦闘服って──あたしと同じ『炎』か？」
line = "「おおう、なんかイメチェンしてんな。しかもその戦闘服って──あたしと同じ『炎』か？」"

[[dialogue]]
speaker = "アポロ"
# 「ふっふっふ……その通り！　それもあたしの炎はただの炎じゃないぞ、芸術の爆炎なんだ！」
line = "「ふっふっふ……その通り！　それもあたしの炎はただの炎じゃないぞ、芸術の爆炎なんだ！」"

[[dialogue]]
speaker = "ソフィア"
# 「芸術……？」
line = "「芸術……？」"

[[dialogue]]
speaker = "unk"
# 自慢したいみたい
line = "自慢したいみたい"

[[dialogue]]
speaker = "unk"
# 付き合ってあげて
line = "付き合ってあげて"

[[dialogue]]
speaker = "セーラ"
# 「うんうん、確かにこっちのアポロちゃんもイカしてる感じ♪」
line = "「うんうん、確かにこっちのアポロちゃんもイカしてる感じ♪」"

[[dialogue]]
speaker = "ソフィア"
# 「ええ……見るからに暖かそうなので、そばに置いておきたいです」
line = "「ええ……見るからに暖かそうなので、そばに置いておきたいです」"

[[dialogue]]
speaker = "アポロ"
# 「へへへ。そんなくっつくなって、ソフィア」
line = "「へへへ。そんなくっつくなって、ソフィア」"

[[dialogue]]
speaker = "ユウリ"
# 「んでもよ、どうしたんだ？　セレスティアが進化でもしたのか？」
line = "「んでもよ、どうしたんだ？　セレスティアが進化でもしたのか？」"

[[dialogue]]
speaker = "unk"
# 黒ベア子のせいで……
line = "黒ベア子のせいで……"

[[dialogue]]
speaker = "unk"
# かくかくしかじか
line = "かくかくしかじか"

[[dialogue]]
speaker = "ユウリ"
# 「黒ベア子……クマロボ……お祭り……？　また妙なことが起きてるみたいだな」
line = "「黒ベア子……クマロボ……お祭り……？　また妙なことが起きてるみたいだな」"

[[dialogue]]
speaker = "アポロ"
# 「ああ。消えたアナ達のためにも、あたし達はなんとかしなくちゃいけないんだ」
line = "「ああ。消えたアナ達のためにも、あたし達はなんとかしなくちゃいけないんだ」"

[[dialogue]]
speaker = "ソフィア"
# 「そう言えば、先ほど正門前で謎のクマ型ロボを見かけましたね」
line = "「そう言えば、先ほど正門前で謎のクマ型ロボを見かけましたね」"

[[dialogue]]
speaker = "アポロ"
# 「む！　そいつだ。他のやつに迷惑かけないとも限らないからな──普段とは違うけど、出動の必要ありだぜ！」
line = "「む！　そいつだ。他のやつに迷惑かけないとも限らないからな──普段とは違うけど、出動の必要ありだぜ！」"

[[dialogue]]
speaker = "アポロ"
# 「よーし出かけるぞ魔王、クマ狩りの時間だ！　あたしのハートが燃えたぎるぜ……ファイヤー！」
line = "「よーし出かけるぞ魔王、クマ狩りの時間だ！　あたしのハートが燃えたぎるぜ……ファイヤー！」"

[[dialogue]]
speaker = "セーラ"
# 「いつにも増してガッツマシマシだねー、アポロちゃん」
line = "「いつにも増してガッツマシマシだねー、アポロちゃん」"
