[[dialogue]]
speaker = "unk"
# 第４話,アヒルのぬいぐるみ,P
line = "第４話,アヒルのぬいぐるみ,P"

[[dialogue]]
speaker = "ナミエル"
# 「うぅ……困りました……」
line = "「うぅ……困りました……」"

[[dialogue]]
speaker = "unk"
# どうかした？
line = "どうかした？"

[[dialogue]]
speaker = "ナミエル"
# 「あ。緋宮会長……」
line = "「あ。緋宮会長……」"

[[dialogue]]
speaker = "ナミエル"
# 「つかぬ事を伺いますが、クレーンゲームは得意でしょうか？」
line = "「つかぬ事を伺いますが、クレーンゲームは得意でしょうか？」"

[[dialogue]]
speaker = "unk"
# ゲームセンターの？　欲しい物でもあるのか
line = "ゲームセンターの？　欲しい物でもあるのか"

[[dialogue]]
speaker = "ナミエル"
# 「はい、お恥ずかしながら……どうしても入手したいものがあるんです」
line = "「はい、お恥ずかしながら……どうしても入手したいものがあるんです」"

[[dialogue]]
speaker = "ナミエル"
# 「あいにくこの手の娯楽は経験がなく、ネットでコツなど調べてみたのですがうまくいかなくて……」
line = "「あいにくこの手の娯楽は経験がなく、ネットでコツなど調べてみたのですがうまくいかなくて……」"

[[dialogue]]
speaker = "ナミエル"
# 「プライズ限定商品なので定価で求めるという手も使えません」
line = "「プライズ限定商品なので定価で求めるという手も使えません」"

[[dialogue]]
speaker = "ナミエル"
# 「おまけに店員様の会話を傍受したところ、もうすぐ景品の入れ替えを行うと仰っていました……時間の猶予もないのです……」
line = "「おまけに店員様の会話を傍受したところ、もうすぐ景品の入れ替えを行うと仰っていました……時間の猶予もないのです……」"

[[dialogue]]
speaker = "ナミエル"
# 「果敢に挑みましたが、お小遣いもすっかりなくなってしまいました……」
line = "「果敢に挑みましたが、お小遣いもすっかりなくなってしまいました……」"

[[dialogue]]
speaker = "unk"
# じゃあ、俺が取ってあげよう
line = "じゃあ、俺が取ってあげよう"

[[dialogue]]
speaker = "ナミエル"
# 「いいのですか？　もしや緋宮会長は、クレームゲームの名手なのでしょうか」
line = "「いいのですか？　もしや緋宮会長は、クレームゲームの名手なのでしょうか」"

[[dialogue]]
speaker = "ナミエル"
# 「お手伝いいただけるのでしたら嬉しいです。よろしくお願いいたします……！」
line = "「お手伝いいただけるのでしたら嬉しいです。よろしくお願いいたします……！」"

[[dialogue]]
speaker = "unk"
# ナミエルに頼られるということはあまり経験がない。
line = "ナミエルに頼られるということはあまり経験がない。"

[[dialogue]]
speaker = "unk"
# ここはどんな手を使ってでも、景品を入手してみせよう！
line = "ここはどんな手を使ってでも、景品を入手してみせよう！"

[[dialogue]]
speaker = "ナミエル"
# 「……あんな手があるだなんて聞いていないです」
line = "「……あんな手があるだなんて聞いていないです」"

[[dialogue]]
speaker = "ナミエル"
# 「店員様を呼んで、取りやすい位置に置いてもらうよう要求できるだなんて……」
line = "「店員様を呼んで、取りやすい位置に置いてもらうよう要求できるだなんて……」"

[[dialogue]]
speaker = "ナミエル"
# 「知っていれば私のお小遣いも無駄には……いえ、過ぎたことです。経費と割り切りましょう」
line = "「知っていれば私のお小遣いも無駄には……いえ、過ぎたことです。経費と割り切りましょう」"

[[dialogue]]
speaker = "ナミエル"
# 「緋宮会長、ありがとうございます。どうしても欲しかったんです、このアヒルのぬいぐるみ」
line = "「緋宮会長、ありがとうございます。どうしても欲しかったんです、このアヒルのぬいぐるみ」"

[[dialogue]]
speaker = "unk"
# ぬいぐるみ、好きだったんだ？
line = "ぬいぐるみ、好きだったんだ？"

[[dialogue]]
speaker = "ナミエル"
# 「……ええ。子どもっぽい趣味ですが、私の数少ない趣味です。可愛い物には目がなくって」
line = "「……ええ。子どもっぽい趣味ですが、私の数少ない趣味です。可愛い物には目がなくって」"

[[dialogue]]
speaker = "ナミエル"
# 「中でもこのアヒルのぬいぐるみは特別です。……似たものを、ずっと探していたんです」
line = "「中でもこのアヒルのぬいぐるみは特別です。……似たものを、ずっと探していたんです」"

[[dialogue]]
speaker = "ナミエル"
# 「小さい頃、両親にもらったぬいぐるみ。もう失くしてしまったのですが……でも記憶には焼き付いていましたから」
line = "「小さい頃、両親にもらったぬいぐるみ。もう失くしてしまったのですが……でも記憶には焼き付いていましたから」"

[[dialogue]]
speaker = "ナミエル"
# 「いつかもう一度、手に取りたい。ずっとそう思っていたんですよ」
line = "「いつかもう一度、手に取りたい。ずっとそう思っていたんですよ」"

[[dialogue]]
speaker = "ナミエル"
# 「そういえば……緋宮会長には私の生い立ちを話したことはありませんでしたね」
line = "「そういえば……緋宮会長には私の生い立ちを話したことはありませんでしたね」"

[[dialogue]]
speaker = "ナミエル"
# 「実は私、メイド隊に所属する前は……とある犯罪組織に身を置いていたのです」
line = "「実は私、メイド隊に所属する前は……とある犯罪組織に身を置いていたのです」"

[[dialogue]]
speaker = "ナミエル"
# 「両親が事故で他界した後、幼かった私はそこが悪いところだと知らぬままに引き取られてしまい……」
line = "「両親が事故で他界した後、幼かった私はそこが悪いところだと知らぬままに引き取られてしまい……」"

[[dialogue]]
speaker = "ナミエル"
# 「そこで私は、ターゲットを殺して自分も自決する、いわば使い捨ての暗殺者としての訓練を受けました」
line = "「そこで私は、ターゲットを殺して自分も自決する、いわば使い捨ての暗殺者としての訓練を受けました」"

[[dialogue]]
speaker = "ナミエル"
# 「そして３年ほど前にこの流星市国にやってきました。星見フィオナ暗殺の命を受けて」
line = "「そして３年ほど前にこの流星市国にやってきました。星見フィオナ暗殺の命を受けて」"

[[dialogue]]
speaker = "ナミエル"
# 「──ですが、メイド長に阻止されました。これでも一応組織の中では凄腕の部類だったのですけれど」
line = "「──ですが、メイド長に阻止されました。これでも一応組織の中では凄腕の部類だったのですけれど」"

[[dialogue]]
speaker = "ナミエル"
# 「私がいた組織は、もうありません。幼い子どもを暗殺者に仕立て上げる……そんな行いがお嬢様の逆鱗に触れまして」
line = "「私がいた組織は、もうありません。幼い子どもを暗殺者に仕立て上げる……そんな行いがお嬢様の逆鱗に触れまして」"

[[dialogue]]
speaker = "ナミエル"
# 「星見家や九浄家の力で消された、と聞いております」
line = "「星見家や九浄家の力で消された、と聞いております」"

[[dialogue]]
speaker = "ナミエル"
# 「暗殺者だった私は星見家に引き取られ、メイドとして雇用されました。本当にお嬢様は人が良すぎますよね」
line = "「暗殺者だった私は星見家に引き取られ、メイドとして雇用されました。本当にお嬢様は人が良すぎますよね」"

[[dialogue]]
speaker = "ナミエル"
# 「おかしな組織にいた私は一般常識にも疎く……それからは色々なものを勉強するように言われました」
line = "「おかしな組織にいた私は一般常識にも疎く……それからは色々なものを勉強するように言われました」"

[[dialogue]]
speaker = "ナミエル"
# 「『普通』というものに、たくさん触れていきなさい、と」
line = "「『普通』というものに、たくさん触れていきなさい、と」"

[[dialogue]]
speaker = "ナミエル"
# 「このぬいぐるみは、私の『普通』の象徴なのです。幼い頃、とても幸せだった頃……両親からプレゼントされたアヒルのぬいぐるみ」
line = "「このぬいぐるみは、私の『普通』の象徴なのです。幼い頃、とても幸せだった頃……両親からプレゼントされたアヒルのぬいぐるみ」"

[[dialogue]]
speaker = "ナミエル"
# 「少しでも似たものを見つけたくていつも探し回っていました」
line = "「少しでも似たものを見つけたくていつも探し回っていました」"

[[dialogue]]
speaker = "ナミエル"
# 「……これ、本当にそっくりです。ありがとうございます。緋宮会長」
line = "「……これ、本当にそっくりです。ありがとうございます。緋宮会長」"

[[dialogue]]
speaker = "ナミエル"
# 「両親との思い出に触れられた気がしました」
line = "「両親との思い出に触れられた気がしました」"

[[dialogue]]
speaker = "unk"
# どういたしまして
line = "どういたしまして"

[[dialogue]]
speaker = "ナミエル"
# 「ふふっ……元暗殺者、と伝えても態度が変わらないんですね。やっぱりあなたは、お嬢様に似ています」
line = "「ふふっ……元暗殺者、と伝えても態度が変わらないんですね。やっぱりあなたは、お嬢様に似ています」"

[[dialogue]]
speaker = "ナミエル"
# 「とっても優しくて、とっても温かい」
line = "「とっても優しくて、とっても温かい」"

[[dialogue]]
speaker = "ナミエル"
# 「……たまにえっちな時もありますけれど」
line = "「……たまにえっちな時もありますけれど」"

[[dialogue]]
speaker = "ナミエル"
# 「あの、これからも私と一緒に過ごしていただけますか？　学べなかった色々なことを緋宮会長と共に触れていきたいんです」
line = "「あの、これからも私と一緒に過ごしていただけますか？　学べなかった色々なことを緋宮会長と共に触れていきたいんです」"

[[dialogue]]
speaker = "ナミエル"
# 「──はい。昔のことを自ら話したのは、あなたが初めてです。秘密を知られたからには、距離を取るわけにはいきません」
line = "「──はい。昔のことを自ら話したのは、あなたが初めてです。秘密を知られたからには、距離を取るわけにはいきません」"

[[dialogue]]
speaker = "ナミエル"
# 「これからもどうぞよろしくお願いいたしますね。緋宮会長」
line = "「これからもどうぞよろしくお願いいたしますね。緋宮会長」"
