[[dialogue]]
speaker = "unk"
# 第４話,百合カップル（偽）,P
line = "第４話,百合カップル（偽）,P"

[[dialogue]]
speaker = "unk"
# アニマ先輩の作った分裂薬により、並行して附属校にも通えることになり、俺は久しぶりに附属生女子のアバターで登校していた――
line = "アニマ先輩の作った分裂薬により、並行して附属校にも通えることになり、俺は久しぶりに附属生女子のアバターで登校していた――"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「会長とまたこうして昼食を一緒にできて、アルモたんは嬉しいのだ♪　もぐもぐ♪」
line = "「会長とまたこうして昼食を一緒にできて、アルモたんは嬉しいのだ♪　もぐもぐ♪」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ふふっ、何を言ってるんですか、アルモタヘルったら。恋人として、よく会長と一緒にいるじゃないですか」
line = "「ふふっ、何を言ってるんですか、アルモタヘルったら。恋人として、よく会長と一緒にいるじゃないですか」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「附属校女子になった会長と会うのは久しぶりなのだ！　アルモたん的には、男の会長と、女の子の会長は別腹なのだ！」
line = "「附属校女子になった会長と会うのは久しぶりなのだ！　アルモたん的には、男の会長と、女の子の会長は別腹なのだ！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「なるほど、一理あるかもしれません。女の子になった会長、本当に可愛いらしいですもんね。それはもう、ママダレナの娘になって欲しいくらいです♪」
line = "「なるほど、一理あるかもしれません。女の子になった会長、本当に可愛いらしいですもんね。それはもう、ママダレナの娘になって欲しいくらいです♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ダメなのだ！　会長はアルモたんのものなのだ！　たとえ今は同性であっても、くっ付いていいのは恋人のアルモたんだけなのだ！」
line = "「ダメなのだ！　会長はアルモたんのものなのだ！　たとえ今は同性であっても、くっ付いていいのは恋人のアルモたんだけなのだ！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「あらあら、残念です。お熱いですね、うふふ♪」
line = "「あらあら、残念です。お熱いですね、うふふ♪」"

[[dialogue]]
speaker = "ヒトリ"
# 「じ～っ……」
line = "「じ～っ……」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ん……？　なんだか視線を感じるような……？」
line = "「ん……？　なんだか視線を感じるような……？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「まあ、きっと、会長の姿が可愛いからだな♪　とりあえず会長、いつもみたいにアルモたんにアレをやって欲しいのだ♪」
line = "「まあ、きっと、会長の姿が可愛いからだな♪　とりあえず会長、いつもみたいにアルモたんにアレをやって欲しいのだ♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――周りに見られるから、恥ずかしい？　え～、やだやだ、お願いなのだ～」
line = "「――周りに見られるから、恥ずかしい？　え～、やだやだ、お願いなのだ～」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「えへへ～、してくれるのだ？　ありがとうなのだ♪　――あ～んなのだ♪」
line = "「えへへ～、してくれるのだ？　ありがとうなのだ♪　――あ～んなのだ♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「あむっ♪　もぐもぐ♪　……ん～♪　幸せスパイスで、お肉がとっても美味なのだ……♪」
line = "「あむっ♪　もぐもぐ♪　……ん～♪　幸せスパイスで、お肉がとっても美味なのだ……♪」"

[[dialogue]]
speaker = "ヒトリ"
# 「はあぁ……てぇてぇ……<emoji=heart04>」
line = "「はあぁ……てぇてぇ……<emoji=heart04>」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「むっ……！　やっぱり熱い視線を感じるのだ！　そこだな！」
line = "「むっ……！　やっぱり熱い視線を感じるのだ！　そこだな！」"

[[dialogue]]
speaker = "ヒトリ"
# 「ひゃっ！？　ご、ごめんなさい！」
line = "「ひゃっ！？　ご、ごめんなさい！」"

[[dialogue]]
speaker = "unk"
# ヒトリ、こんにちは
line = "ヒトリ、こんにちは"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「会長、この子と知り合いなのか？」
line = "「会長、この子と知り合いなのか？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「なるほど、幽霊を連れている星騎士が新星学園にいると聞いていたが、それがお前のことだったのだな」
line = "「なるほど、幽霊を連れている星騎士が新星学園にいると聞いていたが、それがお前のことだったのだな」"

[[dialogue]]
speaker = "ヒトリ"
# 「は、はい、不知火ヒトリと言います。それで……こちらが幽霊友達の、ゆーちゃんです」
line = "「は、はい、不知火ヒトリと言います。それで……こちらが幽霊友達の、ゆーちゃんです」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「ゆー♪」
line = "「ゆー♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「よろしくなのだ！　それで、ヒトリはアルモたん達に熱い視線を送っていたようだが、何か気になることでもあったのか？」
line = "「よろしくなのだ！　それで、ヒトリはアルモたん達に熱い視線を送っていたようだが、何か気になることでもあったのか？」"

[[dialogue]]
speaker = "ヒトリ"
# 「え！？　そ、それはその……私、現実に女の子同士の……『百合カップル』を見るのが初めてだったので、興奮を抑えられなくて……！」
line = "「え！？　そ、それはその……私、現実に女の子同士の……『百合カップル』を見るのが初めてだったので、興奮を抑えられなくて……！」"

[[dialogue]]
speaker = "unk"
# いや、中身の俺は男だけど！？
line = "いや、中身の俺は男だけど！？"

[[dialogue]]
speaker = "ヒトリ"
# 「わ、わかってます！　で、でも、何というか……」
line = "「わ、わかってます！　で、でも、何というか……」"

[[dialogue]]
speaker = "ヒトリ"
# 「私的には、今の会長さんは可愛いのでアリというか……」
line = "「私的には、今の会長さんは可愛いのでアリというか……」"

[[dialogue]]
speaker = "unk"
# どういうこと！？
line = "どういうこと！？"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ノリのいいクラスの男の子たちも、会長さんに話しかけられると異性と意識して、照れたりしてますしね～♪」
line = "「ノリのいいクラスの男の子たちも、会長さんに話しかけられると異性と意識して、照れたりしてますしね～♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「会長は性別問わず、人たらしなのだ。でも、ユリ……？　というのは一体、なんなのだ？」
line = "「会長は性別問わず、人たらしなのだ。でも、ユリ……？　というのは一体、なんなのだ？」"

[[dialogue]]
speaker = "unk"
# 俺は、ヒトリが実は女の子同士の絡みを見るのが好きな『百合好き』であるということを説明する。
line = "俺は、ヒトリが実は女の子同士の絡みを見るのが好きな『百合好き』であるということを説明する。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――ふむ。確かに周りでは、女の子同士のカップルは見かけたことがなかったのだ！」
line = "「――ふむ。確かに周りでは、女の子同士のカップルは見かけたことがなかったのだ！」"

[[dialogue]]
speaker = "ヒトリ"
# 「そ、それで……あの、実は１つ聞きたいことがあって……！」
line = "「そ、それで……あの、実は１つ聞きたいことがあって……！」"

[[dialogue]]
speaker = "ヒトリ"
# 「その……アルモタヘルさんは、女の子の会長さんに対してもドキドキしたりとか、好きって思ったりとか、するんでしょうか……？」
line = "「その……アルモタヘルさんは、女の子の会長さんに対してもドキドキしたりとか、好きって思ったりとか、するんでしょうか……？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「重要なのは、『女の子の会長』への気持ち？　……そこまで深く考えたことはなかったのだ。でも……」
line = "「重要なのは、『女の子の会長』への気持ち？　……そこまで深く考えたことはなかったのだ。でも……」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「たとえ会長の本来の性別が女だったとしても、きっと同じように好きになっていた気がするのだ」
line = "「たとえ会長の本来の性別が女だったとしても、きっと同じように好きになっていた気がするのだ」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「会長が小さい姿になったアルモたんに対しても、変わらず好きと言ってくれたように……守護天使の我が、人間に恋をしたようにな♪」
line = "「会長が小さい姿になったアルモたんに対しても、変わらず好きと言ってくれたように……守護天使の我が、人間に恋をしたようにな♪」"

[[dialogue]]
speaker = "unk"
# アルモから真っ直ぐに見つめられて、思わずドキッとしてしまう。
line = "アルモから真っ直ぐに見つめられて、思わずドキッとしてしまう。"

[[dialogue]]
speaker = "ヒトリ"
# 「て……てぇてぇ……！」
line = "「て……てぇてぇ……！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「でも、せっかくだし、試してみるのもいいかもしれないな……というわけで会長、ちょっとだけ拝借するのだ♪」
line = "「でも、せっかくだし、試してみるのもいいかもしれないな……というわけで会長、ちょっとだけ拝借するのだ♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――ん？　どこって……唇なのだ♪」
line = "「――ん？　どこって……唇なのだ♪」"

[[dialogue]]
speaker = "ヒトリ"
# 「！？」
line = "「！？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ん～っ……ちゅっ<emoji=heart04>　――えへへ<emoji=heart04>　試してみたけど、やっぱり女の子の姿でも、ドキドキしちゃうのだ<emoji=heart04>」
line = "「ん～っ……ちゅっ<emoji=heart04>　――えへへ<emoji=heart04>　試してみたけど、やっぱり女の子の姿でも、ドキドキしちゃうのだ<emoji=heart04>」"

[[dialogue]]
speaker = "ヒトリ"
# 「てっ゛！（気絶）」
line = "「てっ゛！（気絶）」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「ゆっ゛！（昇天）」
line = "「ゆっ゛！（昇天）」"

[[dialogue]]
speaker = "unk"
# カムバーック！！！
line = "カムバーック！！！"

[[dialogue]]
speaker = "unk"
# ちょっ、ゆーちゃんが成仏しかけてる！
line = "ちょっ、ゆーちゃんが成仏しかけてる！"

[[dialogue]]
speaker = "unk"
# 慌てて２人を起こそうとする俺。
line = "慌てて２人を起こそうとする俺。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「あははっ♪　ヒトリ、なかなか面白いやつなのだ♪」
line = "「あははっ♪　ヒトリ、なかなか面白いやつなのだ♪」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「アルモタヘル、さては面白そうだと思って、わざと見せつけましたね？」
line = "「アルモタヘル、さては面白そうだと思って、わざと見せつけましたね？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「てへぺろなのだ♪」
line = "「てへぺろなのだ♪」"

[[dialogue]]
speaker = "unk"
# 小さく舌を出して、可愛い悪戯スマイルをしてみせるアルモなのだった――
line = "小さく舌を出して、可愛い悪戯スマイルをしてみせるアルモなのだった――"
