[[dialogue]]
speaker = "unk"
# 第２話,ヨミとクリスマス,P
line = "第２話,ヨミとクリスマス,P"

[[dialogue]]
speaker = "unk"
# 今日はクリスマス当日。一緒に過ごそうと約束していたヨミが、家を訪ねてきた――
line = "今日はクリスマス当日。一緒に過ごそうと約束していたヨミが、家を訪ねてきた――"

[[dialogue]]
speaker = "ヨミ"
# 「め、メリークリスマスです、会長……♪」
line = "「め、メリークリスマスです、会長……♪」"

[[dialogue]]
speaker = "ヨミ"
# 「――あ、この衣装ですか？　せっかくのクリスマスなので、今日こそ出番かなって……」
line = "「――あ、この衣装ですか？　せっかくのクリスマスなので、今日こそ出番かなって……」"

[[dialogue]]
speaker = "unk"
# 似合ってて、とてもかわいいよ
line = "似合ってて、とてもかわいいよ"

[[dialogue]]
speaker = "ヨミ"
# 「えへへ……♪　会長に褒められると、照れちゃいます……<emoji=heart04>」
line = "「えへへ……♪　会長に褒められると、照れちゃいます……<emoji=heart04>」"

[[dialogue]]
speaker = "ヨミ"
# 「それで、今日は会長にクリスマスプレゼントを用意してきてまして――これ、どうぞ……！」
line = "「それで、今日は会長にクリスマスプレゼントを用意してきてまして――これ、どうぞ……！」"

[[dialogue]]
speaker = "ヨミ"
# 「もちろん、中身を開けて大丈夫ですよ。喜んでもらえるかどうかわからなくて、色々悩んだんですけど……」
line = "「もちろん、中身を開けて大丈夫ですよ。喜んでもらえるかどうかわからなくて、色々悩んだんですけど……」"

[[dialogue]]
speaker = "ヨミ"
# 「でも、私が会長に渡したいものを選ぶことにしました。ちょっと恥ずかしいんですけど……」
line = "「でも、私が会長に渡したいものを選ぶことにしました。ちょっと恥ずかしいんですけど……」"

[[dialogue]]
speaker = "unk"
# これは、お守り？
line = "これは、お守り？"

[[dialogue]]
speaker = "ヨミ"
# 「はい。実家の天ヶ崎神宮に伝わるやり方で作ったものでして……<b>縁結び</b>のお守りなんです……」
line = "「はい。実家の天ヶ崎神宮に伝わるやり方で作ったものでして……<b>縁結び</b>のお守りなんです……」"

[[dialogue]]
speaker = "ヨミ"
# 「その……これからもずっと、一緒にいられますようにって。えへへ……♪」
line = "「その……これからもずっと、一緒にいられますようにって。えへへ……♪」"

[[dialogue]]
speaker = "unk"
# 照れながら言うヨミに、愛おしい気持ちが込み上げてくる。俺も用意していたプレゼントを渡すことにした。
line = "照れながら言うヨミに、愛おしい気持ちが込み上げてくる。俺も用意していたプレゼントを渡すことにした。"

[[dialogue]]
speaker = "ヨミ"
# 「え、会長も私にクリスマスプレゼントを……？　あ、ありがとうございます……♪」
line = "「え、会長も私にクリスマスプレゼントを……？　あ、ありがとうございます……♪」"

[[dialogue]]
speaker = "ヨミ"
# 「わあぁ……綺麗な鈴のペンダント……！」
line = "「わあぁ……綺麗な鈴のペンダント……！」"

[[dialogue]]
speaker = "ヨミ"
# 「あれ？　これ、鈴に宝石が付いてませんか？　なんだかすごく高価そうな……」
line = "「あれ？　これ、鈴に宝石が付いてませんか？　なんだかすごく高価そうな……」"

[[dialogue]]
speaker = "ヨミ"
# 「――えっ、秘密でバイトして買ったんですか？　そんな高いものを私に……？」
line = "「――えっ、秘密でバイトして買ったんですか？　そんな高いものを私に……？」"

[[dialogue]]
speaker = "unk"
# 確かにちょっと高かったけど、鈴型で珍しいし、ヨミに似合いそうだからプレゼントしたかったのだ。そのことを伝えると――
line = "確かにちょっと高かったけど、鈴型で珍しいし、ヨミに似合いそうだからプレゼントしたかったのだ。そのことを伝えると――"

[[dialogue]]
speaker = "ヨミ"
# 「会長……爆裂嬉しいです<emoji=heart04>　大切にします……！」
line = "「会長……爆裂嬉しいです<emoji=heart04>　大切にします……！」"

[[dialogue]]
speaker = "ヨミ"
# 「お礼にってわけじゃないですけど、私、会長にもう１つプレゼントがあるんです。受け取ってくれますか？」
line = "「お礼にってわけじゃないですけど、私、会長にもう１つプレゼントがあるんです。受け取ってくれますか？」"

[[dialogue]]
speaker = "ヨミ"
# 「できました。会長、どうぞ召し上がってみて下さい」
line = "「できました。会長、どうぞ召し上がってみて下さい」"

[[dialogue]]
speaker = "ヨミ"
# 「――はい。会長に食べてもらう為に、実は前々から料理の練習をしていたんです」
line = "「――はい。会長に食べてもらう為に、実は前々から料理の練習をしていたんです」"

[[dialogue]]
speaker = "ヨミ"
# 「まだまだ未熟なので、簡単な親子丼と、お味噌汁ではあるんですけど……」
line = "「まだまだ未熟なので、簡単な親子丼と、お味噌汁ではあるんですけど……」"

[[dialogue]]
speaker = "ヨミ"
# 「ど、どうでしょうか……？」
line = "「ど、どうでしょうか……？」"

[[dialogue]]
speaker = "unk"
# うまい！
line = "うまい！"

[[dialogue]]
speaker = "ヨミ"
# 「本当ですか？　よかったです……♪」
line = "「本当ですか？　よかったです……♪」"

[[dialogue]]
speaker = "ヨミ"
# 「私、カフェテリアでも受付担当に回されてしまうくらい、料理が苦手だったんですけど……その――」
line = "「私、カフェテリアでも受付担当に回されてしまうくらい、料理が苦手だったんですけど……その――」"

[[dialogue]]
speaker = "ヨミ"
# 「将来の為に、料理は上手くなっておきたいなって、思ったので……」
line = "「将来の為に、料理は上手くなっておきたいなって、思ったので……」"

[[dialogue]]
speaker = "ヨミ"
# 「あっ……会長……<emoji=heart04>」
line = "「あっ……会長……<emoji=heart04>」"

[[dialogue]]
speaker = "ヨミ"
# 「そんないきなり抱き締められたら、ドキドキしちゃいます……<emoji=heart04>」
line = "「そんないきなり抱き締められたら、ドキドキしちゃいます……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ヨミが可愛いことを言うのが悪い
line = "ヨミが可愛いことを言うのが悪い"

[[dialogue]]
speaker = "ヨミ"
# 「そんなつもりは……くんくん……<emoji=heart04>」
line = "「そんなつもりは……くんくん……<emoji=heart04>」"

[[dialogue]]
speaker = "ヨミ"
# 「はあぁ……<emoji=heart04>　好きな会長の匂いで私、ウットリしてきちゃいます……<emoji=heart04>」
line = "「はあぁ……<emoji=heart04>　好きな会長の匂いで私、ウットリしてきちゃいます……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺もヨミの匂い、好きだよ
line = "俺もヨミの匂い、好きだよ"

[[dialogue]]
speaker = "ヨミ"
# 「こやん<emoji=heart04>　嗅がれるのはまだ、恥ずかしいです……<emoji=heart04>」
line = "「こやん<emoji=heart04>　嗅がれるのはまだ、恥ずかしいです……<emoji=heart04>」"

[[dialogue]]
speaker = "ヨミ"
# 「あっ、だ、ダメです会長<emoji=heart04>　これ以上スキンシップしてたら、止まらなくなっちゃいますから……！」
line = "「あっ、だ、ダメです会長<emoji=heart04>　これ以上スキンシップしてたら、止まらなくなっちゃいますから……！」"

[[dialogue]]
speaker = "ヨミ"
# 「せめて、食事が終わってから――んっ……<emoji=heart04>」
line = "「せめて、食事が終わってから――んっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヨミ"
# 「会長……<emoji=heart04>　ちゅっ……<emoji=heart04>」
line = "「会長……<emoji=heart04>　ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そんな風に甘いクリスマスを過ごしていると、あっという間に夜になってしまう。
line = "そんな風に甘いクリスマスを過ごしていると、あっという間に夜になってしまう。"

[[dialogue]]
speaker = "ヨミ"
# 「もうこんな時間……名残惜しいですが、そろそろお屋敷に帰らないといけませんね……」
line = "「もうこんな時間……名残惜しいですが、そろそろお屋敷に帰らないといけませんね……」"

[[dialogue]]
speaker = "ヨミ"
# 「――え？　そのことなら大丈夫？」
line = "「――え？　そのことなら大丈夫？」"

[[dialogue]]
speaker = "ヨミ"
# 「――ヴィーナスお嬢様に許可をもらっている……ですか？　今日はずっと、私と一緒にいたいからって？」
line = "「――ヴィーナスお嬢様に許可をもらっている……ですか？　今日はずっと、私と一緒にいたいからって？」"

[[dialogue]]
speaker = "ヨミ"
# 「こ、こやあぁぁ～～～っ。なんかそれ、周りに今日のことが伝わっちゃってるってことですよね……？　ば、爆裂恥ずかしいです……！」
line = "「こ、こやあぁぁ～～～っ。なんかそれ、周りに今日のことが伝わっちゃってるってことですよね……？　ば、爆裂恥ずかしいです……！」"

[[dialogue]]
speaker = "ヨミ"
# 「――い、いえ。嫌じゃないです……恥ずかしいですけど、正直……嬉しいです」
line = "「――い、いえ。嫌じゃないです……恥ずかしいですけど、正直……嬉しいです」"

[[dialogue]]
speaker = "ヨミ"
# 「私もまだ、会長と離れたくなかったですから……<emoji=heart04>」
line = "「私もまだ、会長と離れたくなかったですから……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ヨミ、好きだ
line = "ヨミ、好きだ"

[[dialogue]]
speaker = "ヨミ"
# 「はい……<emoji=heart04>　私も、好きです……<emoji=heart04>」
line = "「はい……<emoji=heart04>　私も、好きです……<emoji=heart04>」"

[[dialogue]]
speaker = "ヨミ"
# 「――ん……<emoji=heart04>　ちゅっ……<emoji=heart04>」
line = "「――ん……<emoji=heart04>　ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺とヨミはそれからもゆっくりと、お互いの好きを確かめ合うのだった――
line = "俺とヨミはそれからもゆっくりと、お互いの好きを確かめ合うのだった――"
