[[dialogue]]
speaker = "unk"
# 第３話,竜たるもの、畏怖を持たれよ,P
line = "第３話,竜たるもの、畏怖を持たれよ,P"

[[dialogue]]
speaker = "unk"
# 某日、アステラが２ヵ所同時に出現。新星星徒会はこれに対し、マハムート先輩に支援要請──
line = "某日、アステラが２ヵ所同時に出現。新星星徒会はこれに対し、マハムート先輩に支援要請──"

[[dialogue]]
speaker = "unk"
# 俺はマハムート先輩、アナとチームを組み、片方のアステラに突入していた。
line = "俺はマハムート先輩、アナとチームを組み、片方のアステラに突入していた。"

[[dialogue]]
speaker = "パワゴン"
# 「イイイイイ！」
line = "「イイイイイ！」"

[[dialogue]]
speaker = "アナ"
# 「なっ、このモンスター、大型なのに素早い！？」
line = "「なっ、このモンスター、大型なのに素早い！？」"

[[dialogue]]
speaker = "アナ"
# 「ぐっ……！　油断しましたっ」
line = "「ぐっ……！　油断しましたっ」"

[[dialogue]]
speaker = "unk"
# アナ！　大丈夫か！？
line = "アナ！　大丈夫か！？"

[[dialogue]]
speaker = "アナ"
# 「ノープロブレムです……。ですが、このデカブツの足をどうにかしないと──」
line = "「ノープロブレムです……。ですが、このデカブツの足をどうにかしないと──」"

[[dialogue]]
speaker = "マハムート"
# 「畏怖をもって跪きなさい。グラビトンプレッシャー」
line = "「畏怖をもって跪きなさい。グラビトンプレッシャー」"

[[dialogue]]
speaker = "アナ"
# 「デカブツが地面に倒れて止まった。マムの『引力操作』……！」
line = "「デカブツが地面に倒れて止まった。マムの『引力操作』……！」"

[[dialogue]]
speaker = "マハムート"
# 「……よくもうちの寮生に手を出してくれたわね。身の程を知りなさい」
line = "「……よくもうちの寮生に手を出してくれたわね。身の程を知りなさい」"

[[dialogue]]
speaker = "マハムート"
# 「メテオインパクト！」
line = "「メテオインパクト！」"

[[dialogue]]
speaker = "unk"
# その後、マハムート先輩の圧倒的な活躍によってアステラは無事消滅。
line = "その後、マハムート先輩の圧倒的な活躍によってアステラは無事消滅。"

[[dialogue]]
speaker = "unk"
# 別動隊のヴィーナスたちからも、もう１つのアステラの消滅確認したと連絡があった。
line = "別動隊のヴィーナスたちからも、もう１つのアステラの消滅確認したと連絡があった。"

[[dialogue]]
speaker = "unk"
# マム、とんでもない強さでした
line = "マム、とんでもない強さでした"

[[dialogue]]
speaker = "マハムート"
# 「ふっ……言ったでしょう？　ヴィーナスにもアナタにも、最強の座を譲るつもりはないって」
line = "「ふっ……言ったでしょう？　ヴィーナスにもアナタにも、最強の座を譲るつもりはないって」"

[[dialogue]]
speaker = "マハムート"
# 「これが寮長たる私、妃竜院家次期当主──妃竜院マハムートの実力よ」
line = "「これが寮長たる私、妃竜院家次期当主──妃竜院マハムートの実力よ」"

[[dialogue]]
speaker = "unk"
# 妃竜院家、次期当主？
line = "妃竜院家、次期当主？"

[[dialogue]]
speaker = "アナ"
# 「妃竜院家は魔界で３０００年以上続く名家。魔界でも希少な『竜』の血を引く魔族なんですよ」
line = "「妃竜院家は魔界で３０００年以上続く名家。魔界でも希少な『竜』の血を引く魔族なんですよ」"

[[dialogue]]
speaker = "アナ"
# 「その中でもマムは、生まれながらに膨大な星力と、固有の星術である『引力操作』を有していて、歴代最強の当主になると言われています」
line = "「その中でもマムは、生まれながらに膨大な星力と、固有の星術である『引力操作』を有していて、歴代最強の当主になると言われています」"

[[dialogue]]
speaker = "unk"
# そういえば、アナも新星寮の寮生なんだっけ
line = "そういえば、アナも新星寮の寮生なんだっけ"

[[dialogue]]
speaker = "アナ"
# 「はい、なのでマムのことはよく知っています」
line = "「はい、なのでマムのことはよく知っています」"

[[dialogue]]
speaker = "マハムート"
# 「『竜たるもの、畏怖を持たれよ』というのが、我が妃竜院家の家訓よ」
line = "「『竜たるもの、畏怖を持たれよ』というのが、我が妃竜院家の家訓よ」"

[[dialogue]]
speaker = "マハムート"
# 「故に会長、今回手伝ってあげたこと、畏怖をもって感謝なさい？」
line = "「故に会長、今回手伝ってあげたこと、畏怖をもって感謝なさい？」"

[[dialogue]]
speaker = "unk"
# ありがとうございます、本当に助かりました
line = "ありがとうございます、本当に助かりました"

[[dialogue]]
speaker = "unk"
# イエス・マム。
line = "イエス・マム。"

[[dialogue]]
speaker = "マハムート"
# 「ふん、アナタも返事が板について来たわね。悪くないわ」
line = "「ふん、アナタも返事が板について来たわね。悪くないわ」"

[[dialogue]]
speaker = "マハムート"
# 「さて、それはいいとして……アナ」
line = "「さて、それはいいとして……アナ」"

[[dialogue]]
speaker = "アナ"
# 「ぎくり」
line = "「ぎくり」"

[[dialogue]]
speaker = "マハムート"
# 「アナタは、さっさとするべきことがあるでしょ？」
line = "「アナタは、さっさとするべきことがあるでしょ？」"

[[dialogue]]
speaker = "アナ"
# 「……申し訳ありませんでした、マム。大型は動きが遅いはずと油断して、チームに迷惑を掛けてしまいました」
line = "「……申し訳ありませんでした、マム。大型は動きが遅いはずと油断して、チームに迷惑を掛けてしまいました」"

[[dialogue]]
speaker = "マハムート"
# 「何を言っているの、アナタは？　誰がミスを謝れなんて言ったかしら」
line = "「何を言っているの、アナタは？　誰がミスを謝れなんて言ったかしら」"

[[dialogue]]
speaker = "アナ"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "マハムート"
# 「アナタ、さっきの戦闘で１発食らってたでしょ」
line = "「アナタ、さっきの戦闘で１発食らってたでしょ」"

[[dialogue]]
speaker = "マハムート"
# 「こんなところで私の機嫌うかがっている暇があったら、さっさと学園の保健室に行って、体に異常がないか診てもらいなさい」
line = "「こんなところで私の機嫌うかがっている暇があったら、さっさと学園の保健室に行って、体に異常がないか診てもらいなさい」"

[[dialogue]]
speaker = "アナ"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "マハムート"
# 「返事は？」
line = "「返事は？」"

[[dialogue]]
speaker = "アナ"
# 「イエス・マム。後で必ず報告に上がります」
line = "「イエス・マム。後で必ず報告に上がります」"

[[dialogue]]
speaker = "マハムート"
# 「ええ、そうして頂戴」
line = "「ええ、そうして頂戴」"

[[dialogue]]
speaker = "アナ"
# 「あの……マム」
line = "「あの……マム」"

[[dialogue]]
speaker = "マハムート"
# 「まだ何かあるの？　いいから早く──」
line = "「まだ何かあるの？　いいから早く──」"

[[dialogue]]
speaker = "アナ"
# 「今日は助けていただき、ありがとうございました。行ってきます」
line = "「今日は助けていただき、ありがとうございました。行ってきます」"

[[dialogue]]
speaker = "マハムート"
# 「ふん……まったく、礼の言葉なんて何の足しにもならないわ……」
line = "「ふん……まったく、礼の言葉なんて何の足しにもならないわ……」"

[[dialogue]]
speaker = "unk"
# 寮生から慕われてるんですね
line = "寮生から慕われてるんですね"

[[dialogue]]
speaker = "マハムート"
# 「は？　何を言っているのかしら、アナタは」
line = "「は？　何を言っているのかしら、アナタは」"

[[dialogue]]
speaker = "マハムート"
# 「あれは私に対しての『畏怖』に決まっているでしょ」
line = "「あれは私に対しての『畏怖』に決まっているでしょ」"

[[dialogue]]
speaker = "unk"
# えっ
line = "えっ"

[[dialogue]]
speaker = "マハムート"
# 「何よ、その顔は？　何か私、変なこと言ったかしら？」
line = "「何よ、その顔は？　何か私、変なこと言ったかしら？」"

[[dialogue]]
speaker = "マハムート"
# 「……って、ちょっと！　なんで笑い出すわけ？　失礼ね、どういうことか説明なさい！」
line = "「……って、ちょっと！　なんで笑い出すわけ？　失礼ね、どういうことか説明なさい！」"

[[dialogue]]
speaker = "unk"
# つい笑ってしまう俺に、不服そうな様子でむくれるマハムート先輩なのだった。
line = "つい笑ってしまう俺に、不服そうな様子でむくれるマハムート先輩なのだった。"
