[[dialogue]]
speaker = "unk"
# 第３話,ルリエルと恋人カードゲーム,P
line = "第３話,ルリエルと恋人カードゲーム,P"

[[dialogue]]
speaker = "ルリエル"
# 「会長さん、今日の巫女修業はこれをやりましょう！」
line = "「会長さん、今日の巫女修業はこれをやりましょう！」"

[[dialogue]]
speaker = "unk"
# 休日、俺の家に遊びに来ていたルリエル。彼女が取り出して見せたのは――
line = "休日、俺の家に遊びに来ていたルリエル。彼女が取り出して見せたのは――"

[[dialogue]]
speaker = "ルリエル"
# 「ででん♪　『ブッチャケカード』というゲームなのです！」
line = "「ででん♪　『ブッチャケカード』というゲームなのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「この間、流星星徒会の皆さんと街に出かけた時に、見つけたんですよ～♪」
line = "「この間、流星星徒会の皆さんと街に出かけた時に、見つけたんですよ～♪」"

[[dialogue]]
speaker = "ルリエル"
# 「恋人同士でやるゲームらしくて、会長さんと楽しくイチャイチャできると思って、買ってきたのです♪」
line = "「恋人同士でやるゲームらしくて、会長さんと楽しくイチャイチャできると思って、買ってきたのです♪」"

[[dialogue]]
speaker = "ルリエル"
# 「えっとですね～、内容はすごく簡単で、シャッフルした山札を交互に引いて、そのカードに書いてある内容をぶっちゃけて話すというものなのです」
line = "「えっとですね～、内容はすごく簡単で、シャッフルした山札を交互に引いて、そのカードに書いてある内容をぶっちゃけて話すというものなのです」"

[[dialogue]]
speaker = "ルリエル"
# 「例えば１枚引いてみせると～、『相手について最近新しく知ったことは？』といった感じです」
line = "「例えば１枚引いてみせると～、『相手について最近新しく知ったことは？』といった感じです」"

[[dialogue]]
speaker = "unk"
# 勝ち負けとかはあるの？
line = "勝ち負けとかはあるの？"

[[dialogue]]
speaker = "ルリエル"
# 「本来は特にないのです。普段は言えないことを言ったりして、恋人としての仲を深めるのが目的らしいので」
line = "「本来は特にないのです。普段は言えないことを言ったりして、恋人としての仲を深めるのが目的らしいので」"

[[dialogue]]
speaker = "ルリエル"
# 「でも、ルリエル的にはもっと面白くしたいので、今回は先に３回照れた方が負けっていうルールを追加しようと思うのです！」
line = "「でも、ルリエル的にはもっと面白くしたいので、今回は先に３回照れた方が負けっていうルールを追加しようと思うのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「ちなみに、言いづらい内容もあると思うので、その時はパスしてもＯＫですよ。楽しく遊べないと意味がないですから」
line = "「ちなみに、言いづらい内容もあると思うので、その時はパスしてもＯＫですよ。楽しく遊べないと意味がないですから」"

[[dialogue]]
speaker = "ルリエル"
# 「それじゃあ、始めちゃいましょう！　ジャンケンで勝った方が先行ということで――じゃ～んけ～ん、ぽんっ☆　なのです♪」
line = "「それじゃあ、始めちゃいましょう！　ジャンケンで勝った方が先行ということで――じゃ～んけ～ん、ぽんっ☆　なのです♪」"

[[dialogue]]
speaker = "ルリエル"
# 「では、ルリエルから先行で行っちゃいますよ～！　――山札からドローなのです」
line = "「では、ルリエルから先行で行っちゃいますよ～！　――山札からドローなのです」"

[[dialogue]]
speaker = "ルリエル"
# 「書いてある内容は――『相手のどんな仕草が好きか？』だそうです」
line = "「書いてある内容は――『相手のどんな仕草が好きか？』だそうです」"

[[dialogue]]
speaker = "ルリエル"
# 「ルリエルが会長さんの仕草で好きなのは、そうですね～」
line = "「ルリエルが会長さんの仕草で好きなのは、そうですね～」"

[[dialogue]]
speaker = "ルリエル"
# 「すごく照れる時に、恥ずかしくなって顔を両手で覆って隠しちゃうところとか、可愛くてルリエルは好きなのです♪　見ていると思わず笑顔になっちゃいます<emoji=heart04>」
line = "「すごく照れる時に、恥ずかしくなって顔を両手で覆って隠しちゃうところとか、可愛くてルリエルは好きなのです♪　見ていると思わず笑顔になっちゃいます<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 指摘されると恥ずかしい……！
line = "指摘されると恥ずかしい……！"

[[dialogue]]
speaker = "unk"
# 意識してなかったけど
line = "意識してなかったけど"

[[dialogue]]
speaker = "ルリエル"
# 「あっ♪　会長さん、顔が赤くなってますよ？　照れてます？　照れてますよね♪」
line = "「あっ♪　会長さん、顔が赤くなってますよ？　照れてます？　照れてますよね♪」"

[[dialogue]]
speaker = "ルリエル"
# 「ルリエルの１点先取なのです♪　ふふふっ、次は会長さんの番ですよ～。どうぞ♪」
line = "「ルリエルの１点先取なのです♪　ふふふっ、次は会長さんの番ですよ～。どうぞ♪」"

[[dialogue]]
speaker = "unk"
# 俺が引いたカードに書かれていたお題は――『相手がどんな人と話していたら嫉妬するか？』というものだった。
line = "俺が引いたカードに書かれていたお題は――『相手がどんな人と話していたら嫉妬するか？』というものだった。"

[[dialogue]]
speaker = "ルリエル"
# 「嫉妬……？　会長さん、わたしのことで嫉妬してくれたりするのですか？　気になるのです！」
line = "「嫉妬……？　会長さん、わたしのことで嫉妬してくれたりするのですか？　気になるのです！」"

[[dialogue]]
speaker = "unk"
# あ～、実を言うと……
line = "あ～、実を言うと……"

[[dialogue]]
speaker = "ルリエル"
# 「――最近は、ルリエルが他の男子生徒と話しているのを見たら、内心嫉妬してしまう？　えっ、そうなのですか！？」
line = "「――最近は、ルリエルが他の男子生徒と話しているのを見たら、内心嫉妬してしまう？　えっ、そうなのですか！？」"

[[dialogue]]
speaker = "ルリエル"
# 「会長さん、そこまでルリエルのこと、独占したいと思ってくれてるなんて……」
line = "「会長さん、そこまでルリエルのこと、独占したいと思ってくれてるなんて……」"

[[dialogue]]
speaker = "ルリエル"
# 「ルリエル、なんだか嬉しくなっちゃうのですよ～♪　えへへへへへぇ～<emoji=heart04>」
line = "「ルリエル、なんだか嬉しくなっちゃうのですよ～♪　えへへへへへぇ～<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# う、嬉しいんだ……
line = "う、嬉しいんだ……"

[[dialogue]]
speaker = "ルリエル"
# 「はい♪　だって、わたしが会長さんの気持ちを、独占できてるってことですもんね♪」
line = "「はい♪　だって、わたしが会長さんの気持ちを、独占できてるってことですもんね♪」"

[[dialogue]]
speaker = "ルリエル"
# 「内心むくれてる会長さんを想像したら、すごく愛おしい気持ちが湧いて来て、思わずニヤニヤしちゃうのです<emoji=heart04>」
line = "「内心むくれてる会長さんを想像したら、すごく愛おしい気持ちが湧いて来て、思わずニヤニヤしちゃうのです<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# くぅっ……！
line = "くぅっ……！"

[[dialogue]]
speaker = "ルリエル"
# 「あっ！　会長さん、顔がさっきよりも赤くなってます♪　ということは、照れポイント２点目もゲットですね！　えへへ♪」
line = "「あっ！　会長さん、顔がさっきよりも赤くなってます♪　ということは、照れポイント２点目もゲットですね！　えへへ♪」"

[[dialogue]]
speaker = "ルリエル"
# 「じゃあ、またルリエルのターンですよ～。カードをドローなのです！」
line = "「じゃあ、またルリエルのターンですよ～。カードをドローなのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「内容は『今年中に２人でしてみたいことは？』ですか。そうですね～、ルリエルは会長さんと――」
line = "「内容は『今年中に２人でしてみたいことは？』ですか。そうですね～、ルリエルは会長さんと――」"

[[dialogue]]
speaker = "ルリエル"
# 「<b>婚約</b>がしたいのです！」
line = "「<b>婚約</b>がしたいのです！」"

[[dialogue]]
speaker = "unk"
# えっ！？
line = "えっ！？"

[[dialogue]]
speaker = "ルリエル"
# 「流星星徒会の皆さんに恋愛相談をしたら、さすがに結婚は学園を卒業してからの方がいいって言われたのです！」
line = "「流星星徒会の皆さんに恋愛相談をしたら、さすがに結婚は学園を卒業してからの方がいいって言われたのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「でもでも！　結婚はまだ早かったとしても、その準備は今からしておけますよね？　なので～」
line = "「でもでも！　結婚はまだ早かったとしても、その準備は今からしておけますよね？　なので～」"

[[dialogue]]
speaker = "ルリエル"
# 「ルリエル的には、今年中に婚約して、卒業したらすぐ結婚できるように、早めに準備しておきたいのです！」
line = "「ルリエル的には、今年中に婚約して、卒業したらすぐ結婚できるように、早めに準備しておきたいのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「会長さんとの大事な将来のことなので、準備は時間をかけて、ちゃんとしたいので……えへへ<emoji=heart04>」
line = "「会長さんとの大事な将来のことなので、準備は時間をかけて、ちゃんとしたいので……えへへ<emoji=heart04>」"

[[dialogue]]
speaker = "ルリエル"
# 「――って、ああっ！　会長さん、顔を両手で覆っちゃってます！　耳まで真っ赤になってますよ～？」
line = "「――って、ああっ！　会長さん、顔を両手で覆っちゃってます！　耳まで真っ赤になってますよ～？」"

[[dialogue]]
speaker = "ルリエル"
# 「えへへへ<emoji=heart04>　ルリエルの大好きな仕草なのです<emoji=heart04>　ということは、３ポイントゲットで勝ちってことですよね！？　イェ～イ♪」
line = "「えへへへ<emoji=heart04>　ルリエルの大好きな仕草なのです<emoji=heart04>　ということは、３ポイントゲットで勝ちってことですよね！？　イェ～イ♪」"

[[dialogue]]
speaker = "unk"
# どう考えても強すぎるよ！
line = "どう考えても強すぎるよ！"

[[dialogue]]
speaker = "unk"
# だって、今のは……
line = "だって、今のは……"

[[dialogue]]
speaker = "ルリエル"
# 「――え？　まるでプロポーズみたい、ですか？」
line = "「――え？　まるでプロポーズみたい、ですか？」"

[[dialogue]]
speaker = "ルリエル"
# 「あれ？　でもプロポーズって、指輪を渡しながら『結婚してください』って言うものじゃないんですか？」
line = "「あれ？　でもプロポーズって、指輪を渡しながら『結婚してください』って言うものじゃないんですか？」"

[[dialogue]]
speaker = "unk"
# ルリエルは相手が俺でいいの？
line = "ルリエルは相手が俺でいいの？"

[[dialogue]]
speaker = "ルリエル"
# 「？？？　もちろんなのです！」
line = "「？？？　もちろんなのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「ルリエルは会長さんのこと、大好きですから♪」
line = "「ルリエルは会長さんのこと、大好きですから♪」"

[[dialogue]]
speaker = "ルリエル"
# 「――って、いきなり抱き締めたりして、どうしたのですか？」
line = "「――って、いきなり抱き締めたりして、どうしたのですか？」"

[[dialogue]]
speaker = "ルリエル"
# 「あっ<emoji=heart04>　そんな優しく頭を撫でられたら、くすぐったいのですよ……えへへへへへぇ<emoji=heart04>」
line = "「あっ<emoji=heart04>　そんな優しく頭を撫でられたら、くすぐったいのですよ……えへへへへへぇ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ルリエルを抱き締めながら、今年中に改めてプロポーズしようと心に誓う俺なのであった――
line = "ルリエルを抱き締めながら、今年中に改めてプロポーズしようと心に誓う俺なのであった――"
