[[dialogue]]
speaker = "unk"
# 第１話,会長さんを分析させて？,P
line = "第１話,会長さんを分析させて？,P"

[[dialogue]]
speaker = "エスメラルダ"
# 「こんにちは、新星学園の会長さん。お邪魔するわね♪」
line = "「こんにちは、新星学園の会長さん。お邪魔するわね♪」"

[[dialogue]]
speaker = "unk"
# あなたは流星学園の……？
line = "あなたは流星学園の……？"

[[dialogue]]
speaker = "エスメラルダ"
# 「ええ。流星学園で数学教師と……リクリエの分析官も担当しています。エスメラルダ・シーメインよ」
line = "「ええ。流星学園で数学教師と……リクリエの分析官も担当しています。エスメラルダ・シーメインよ」"

[[dialogue]]
speaker = "エスメラルダ"
# 「気さくに『エスメラルダ先生』って呼んでね♪」
line = "「気さくに『エスメラルダ先生』って呼んでね♪」"

[[dialogue]]
speaker = "エスメラルダ"
# 「今日は会長さんに用事があって……って、あれれ？　何だかちょっぴり、緊張してる雰囲気ね」
line = "「今日は会長さんに用事があって……って、あれれ？　何だかちょっぴり、緊張してる雰囲気ね」"

[[dialogue]]
speaker = "エスメラルダ"
# 「あ──そっか。私が先生だからかな」
line = "「あ──そっか。私が先生だからかな」"

[[dialogue]]
speaker = "エスメラルダ"
# 「そうよね～。急に教師が『用事がある！』なんて言い出したら、何かやっちゃったかも～って思っちゃうわよね」
line = "「そうよね～。急に教師が『用事がある！』なんて言い出したら、何かやっちゃったかも～って思っちゃうわよね」"

[[dialogue]]
speaker = "エスメラルダ"
# 「大丈夫、悪いニュースじゃないから。今日は純粋に、会長さんとお話がしたくてやってきただけなの」
line = "「大丈夫、悪いニュースじゃないから。今日は純粋に、会長さんとお話がしたくてやってきただけなの」"

[[dialogue]]
speaker = "エスメラルダ"
# 「ちょ～っとあなたに興味が湧いてきちゃって」
line = "「ちょ～っとあなたに興味が湧いてきちゃって」"

[[dialogue]]
speaker = "エスメラルダ"
# 「ヴィーナスさんとの御前試合、私も映像で見せてもらったわ」
line = "「ヴィーナスさんとの御前試合、私も映像で見せてもらったわ」"

[[dialogue]]
speaker = "エスメラルダ"
# 「すごかったわね。編入して間もなかったのに勝っちゃうだなんて」
line = "「すごかったわね。編入して間もなかったのに勝っちゃうだなんて」"

[[dialogue]]
speaker = "エスメラルダ"
# 「私も昔は星騎士として活動していたことがあるからわかるの。あなたは普通の子たちとどこか違う。特別だってね」
line = "「私も昔は星騎士として活動していたことがあるからわかるの。あなたは普通の子たちとどこか違う。特別だってね」"

[[dialogue]]
speaker = "エスメラルダ"
# 「わずかな訓練期間でヴィーナスさんを破ったこともそうだし、モンスターを惹きつけるっていう体質のことも気になるわ」
line = "「わずかな訓練期間でヴィーナスさんを破ったこともそうだし、モンスターを惹きつけるっていう体質のことも気になるわ」"

[[dialogue]]
speaker = "エスメラルダ"
# 「元星騎士として。現役の分析官として。あなたのことを色々測定させてもらいたくてやってきた、というわけね♪」
line = "「元星騎士として。現役の分析官として。あなたのことを色々測定させてもらいたくてやってきた、というわけね♪」"

[[dialogue]]
speaker = "エスメラルダ"
# 「時間があるなら、ぜひ測定に協力して欲しいのだけど……大丈夫かしら？」
line = "「時間があるなら、ぜひ測定に協力して欲しいのだけど……大丈夫かしら？」"

[[dialogue]]
speaker = "unk"
# 分析官とは、その名の通りモンスターやリクリエに関するデータを収集し、その実態を詳らかにしていく役職の事を指す。
line = "分析官とは、その名の通りモンスターやリクリエに関するデータを収集し、その実態を詳らかにしていく役職の事を指す。"

[[dialogue]]
speaker = "unk"
# 流星学園のエスメラルダ先生と言えば、新星学園でも名の知れた分析官だ。
line = "流星学園のエスメラルダ先生と言えば、新星学園でも名の知れた分析官だ。"

[[dialogue]]
speaker = "unk"
# みんなが俺のことを魔王だと言う。だが俺は、そんな自分のことを何も知らない。先生に調べてもらえるのならば願ったりだ。
line = "みんなが俺のことを魔王だと言う。だが俺は、そんな自分のことを何も知らない。先生に調べてもらえるのならば願ったりだ。"

[[dialogue]]
speaker = "unk"
# そう思い、俺はエスメラルダ先生の測定に付き合うことになったのだが──
line = "そう思い、俺はエスメラルダ先生の測定に付き合うことになったのだが──"

[[dialogue]]
speaker = "エスメラルダ"
# 「あ。動かないでね。メジャーがずれちゃうから……ん、はーい。ありがとう♪」
line = "「あ。動かないでね。メジャーがずれちゃうから……ん、はーい。ありがとう♪」"

[[dialogue]]
speaker = "エスメラルダ"
# 「協力的でとっても嬉しいわ～。ふふ～、いっぱいデータが集まったわね」
line = "「協力的でとっても嬉しいわ～。ふふ～、いっぱいデータが集まったわね」"

[[dialogue]]
speaker = "エスメラルダ"
# 「えーっと、身長でしょ、体重でしょ、肩幅に、座高に、足のサイズに視力測定も終わり……っと」
line = "「えーっと、身長でしょ、体重でしょ、肩幅に、座高に、足のサイズに視力測定も終わり……っと」"

[[dialogue]]
speaker = "unk"
# これって、ただの身体測定なのでは……？
line = "これって、ただの身体測定なのでは……？"

[[dialogue]]
speaker = "エスメラルダ"
# 「そうよー。測定はいつだって地味なもの。だけど侮っちゃだめ。どんな些細なことでも記録することが大事なんだから」
line = "「そうよー。測定はいつだって地味なもの。だけど侮っちゃだめ。どんな些細なことでも記録することが大事なんだから」"

[[dialogue]]
speaker = "エスメラルダ"
# 「本当に些細な数字が、大きな発見の入口になってることなんてしょっちゅうなんだから」
line = "「本当に些細な数字が、大きな発見の入口になってることなんてしょっちゅうなんだから」"

[[dialogue]]
speaker = "エスメラルダ"
# 「うーん。魔王、魔王と言われるけれど……体は本当に普通の子たちと変わらないのね」
line = "「うーん。魔王、魔王と言われるけれど……体は本当に普通の子たちと変わらないのね」"

[[dialogue]]
speaker = "エスメラルダ"
# 「細身だけど、しっかり鍛えてる男の子～って感じ……」
line = "「細身だけど、しっかり鍛えてる男の子～って感じ……」"

[[dialogue]]
speaker = "エスメラルダ"
# 「──いえ。思い込みは危険よね。どこかで平均値と大きくかけ離れたデータが出てくるかもしれないんだから」
line = "「──いえ。思い込みは危険よね。どこかで平均値と大きくかけ離れたデータが出てくるかもしれないんだから」"

[[dialogue]]
speaker = "エスメラルダ"
# 「よし、それじゃあ第２ステップにいくわよ」
line = "「よし、それじゃあ第２ステップにいくわよ」"

[[dialogue]]
speaker = "エスメラルダ"
# 「服、全部脱いでくれるかしら♪」
line = "「服、全部脱いでくれるかしら♪」"

[[dialogue]]
speaker = "unk"
# えぇっ！？　服を！？
line = "えぇっ！？　服を！？"

[[dialogue]]
speaker = "エスメラルダ"
# 「ええ。次は体脂肪率とか筋肉の密度とか、その他色々な項目を測っていくから。制服を着たままじゃ数値がブレちゃうの」
line = "「ええ。次は体脂肪率とか筋肉の密度とか、その他色々な項目を測っていくから。制服を着たままじゃ数値がブレちゃうの」"

[[dialogue]]
speaker = "エスメラルダ"
# 「大丈夫よー。私は先生で、会長さんは生徒なんだから。好きな女の子の前じゃないんだし、恥ずかしくないでしょ～？」
line = "「大丈夫よー。私は先生で、会長さんは生徒なんだから。好きな女の子の前じゃないんだし、恥ずかしくないでしょ～？」"

[[dialogue]]
speaker = "unk"
# 恥ずかしいです！　服を引っ張らないで！
line = "恥ずかしいです！　服を引っ張らないで！"

[[dialogue]]
speaker = "ウィステリア"
# 「失礼するわね。何だか廊下まで悲鳴が聞こえたのだけど……」
line = "「失礼するわね。何だか廊下まで悲鳴が聞こえたのだけど……」"

[[dialogue]]
speaker = "エスメラルダ"
# 「あ。ウィステリア。久しぶり～♪」
line = "「あ。ウィステリア。久しぶり～♪」"

[[dialogue]]
speaker = "ウィステリア"
# 「エスメラルダ先輩！？　えっ、な、なななっ、何で会長くんの服を脱がしているんですかっ！？」
line = "「エスメラルダ先輩！？　えっ、な、なななっ、何で会長くんの服を脱がしているんですかっ！？」"

[[dialogue]]
speaker = "エスメラルダ"
# 「困ってるのよ～。私が『脱いで』ってお願いしてるのに、この子、脱いでくれないの」
line = "「困ってるのよ～。私が『脱いで』ってお願いしてるのに、この子、脱いでくれないの」"

[[dialogue]]
speaker = "ウィステリア"
# 「えっ？　えっえっ、えっ！？」
line = "「えっ？　えっえっ、えっ！？」"

[[dialogue]]
speaker = "エスメラルダ"
# 「あ、そうだ。良かったらウィステリアからもお願いしてくれない？　あなたの頼みなら彼も聞いてくれるかも♪」
line = "「あ、そうだ。良かったらウィステリアからもお願いしてくれない？　あなたの頼みなら彼も聞いてくれるかも♪」"

[[dialogue]]
speaker = "ウィステリア"
# 「さ、３人で！？　そういうのはみだりがましいと言いますかっ……し、し、失礼しましたー！」
line = "「さ、３人で！？　そういうのはみだりがましいと言いますかっ……し、し、失礼しましたー！」"

[[dialogue]]
speaker = "エスメラルダ"
# 「あん、待ってよー、先輩が困ってるのに～！」
line = "「あん、待ってよー、先輩が困ってるのに～！」"

[[dialogue]]
speaker = "エスメラルダ"
# 「っと、会長さんは逃げたら駄目よ？　ちゃ～んと最後まで付き合ってね♪」
line = "「っと、会長さんは逃げたら駄目よ？　ちゃ～んと最後まで付き合ってね♪」"

[[dialogue]]
speaker = "unk"
# その後、何とか服を剥かれるのは阻止したが、ウィステリアさんに事情を説明するのに苦労したのだった……
line = "その後、何とか服を剥かれるのは阻止したが、ウィステリアさんに事情を説明するのに苦労したのだった……"
