[[dialogue]]
speaker = "unk"
# 第１話,アニュラス・セイファート,P
line = "第１話,アニュラス・セイファート,P"

[[dialogue]]
speaker = "フィオナ"
# 「お疲れ様です、緋宮会長。今日はアステラの攻略について、良い意見交換ができたと思います」
line = "「お疲れ様です、緋宮会長。今日はアステラの攻略について、良い意見交換ができたと思います」"

[[dialogue]]
speaker = "フィオナ"
# 「後で今日の話し合いをまとめたデータを送りますので、新星星徒会のほうでも周知なさってください」
line = "「後で今日の話し合いをまとめたデータを送りますので、新星星徒会のほうでも周知なさってください」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふっ……苦労しているようですけど、あなたなら大丈夫だと思いますよ。ようは慣れの問題ですから」
line = "「ふふっ……苦労しているようですけど、あなたなら大丈夫だと思いますよ。ようは慣れの問題ですから」"

[[dialogue]]
speaker = "フィオナ"
# 「ではまた、別の機会に」
line = "「ではまた、別の機会に」"

[[dialogue]]
speaker = "アニュラス"
# 「……あの男が、新星の新しい星徒会長」
line = "「……あの男が、新星の新しい星徒会長」"

[[dialogue]]
speaker = "unk"
# 流星学園の星徒会室を後にし、敷地内を歩いていると――
line = "流星学園の星徒会室を後にし、敷地内を歩いていると――"

[[dialogue]]
speaker = "unk"
# （何か、視線を感じる……？）
line = "（何か、視線を感じる……？）"

[[dialogue]]
speaker = "アニュラス"
# 「……お父様が認めるほどの男なのだろうか。とてもじゃないが、強そうには見えないな」
line = "「……お父様が認めるほどの男なのだろうか。とてもじゃないが、強そうには見えないな」"

[[dialogue]]
speaker = "unk"
# 新星星徒会室へ戻る道中、尾行を確認するために寄り道をしてみると――
line = "新星星徒会室へ戻る道中、尾行を確認するために寄り道をしてみると――"

[[dialogue]]
speaker = "unk"
# （やっぱり、誰かがつけてきている……）
line = "（やっぱり、誰かがつけてきている……）"

[[dialogue]]
speaker = "アニュラス"
# 「買い食いだと？　たるんでいるんじゃないのか？　星徒会長という立場でありながら、なぜ模範的な行動を取ろうとしない」
line = "「買い食いだと？　たるんでいるんじゃないのか？　星徒会長という立場でありながら、なぜ模範的な行動を取ろうとしない」"

[[dialogue]]
speaker = "アニュラス"
# 「むぅ……もう少し観察を続けるか」
line = "「むぅ……もう少し観察を続けるか」"

[[dialogue]]
speaker = "unk"
# そうして、新星学園の校門前まで戻ってきたところで、俺は背後へ向けて告げた。
line = "そうして、新星学園の校門前まで戻ってきたところで、俺は背後へ向けて告げた。"

[[dialogue]]
speaker = "unk"
# ……誰だ？
line = "……誰だ？"

[[dialogue]]
speaker = "アニュラス"
# 「……ようやく気付いたか。周囲の警戒を怠っているな。そんな様子で新星の星徒会長など務まるのか？」
line = "「……ようやく気付いたか。周囲の警戒を怠っているな。そんな様子で新星の星徒会長など務まるのか？」"

[[dialogue]]
speaker = "アニュラス"
# 「私の名は、アニュラス・セイファート」
line = "「私の名は、アニュラス・セイファート」"

[[dialogue]]
speaker = "unk"
# セイファート！？　それって……！
line = "セイファート！？　それって……！"

[[dialogue]]
speaker = "アニュラス"
# 「そう。私は、新星の学園長である『ジェラルド・セイファート』の娘だ」
line = "「そう。私は、新星の学園長である『ジェラルド・セイファート』の娘だ」"

[[dialogue]]
speaker = "アニュラス"
# 「最近、お父様が興味を持っている生徒がいると聞いてな。新星最強の九浄ヴィーナスに勝った男というのは、お前で間違いないな？」
line = "「最近、お父様が興味を持っている生徒がいると聞いてな。新星最強の九浄ヴィーナスに勝った男というのは、お前で間違いないな？」"

[[dialogue]]
speaker = "アニュラス"
# 「……何？　もし間違っていたらどうするつもりなのか、だと？」
line = "「……何？　もし間違っていたらどうするつもりなのか、だと？」"

[[dialogue]]
speaker = "アニュラス"
# 「う、うるさいなっ。私は確信をもっていたのだ。フィオナ会長と仲良さげに話している男性など、新星の会長しかいないはずだからな！」
line = "「う、うるさいなっ。私は確信をもっていたのだ。フィオナ会長と仲良さげに話している男性など、新星の会長しかいないはずだからな！」"

[[dialogue]]
speaker = "unk"
# 尾行はよくないと思うぞ？
line = "尾行はよくないと思うぞ？"

[[dialogue]]
speaker = "アニュラス"
# 「び、尾行なんて卑怯な真似、していない。観察……そう！　観察していたんだ！」
line = "「び、尾行なんて卑怯な真似、していない。観察……そう！　観察していたんだ！」"

[[dialogue]]
speaker = "アニュラス"
# 「尾行などという騎士道精神に反するような行動を取ると思わないで欲しい！　失礼だぞ！？」
line = "「尾行などという騎士道精神に反するような行動を取ると思わないで欲しい！　失礼だぞ！？」"

[[dialogue]]
speaker = "アニュラス"
# 「む……ま、まあ、確かに声もかけずに見ていたことは事実だ。そこは謝罪しよう。すまなかった」
line = "「む……ま、まあ、確かに声もかけずに見ていたことは事実だ。そこは謝罪しよう。すまなかった」"

[[dialogue]]
speaker = "unk"
# （意外と素直だ……）
line = "（意外と素直だ……）"

[[dialogue]]
speaker = "アニュラス"
# 「しかしそれはそれ、これはこれだ。お前が本当にお父様の興味を引くほどの人物なのか、私にその実力を見せてもらいたい」
line = "「しかしそれはそれ、これはこれだ。お前が本当にお父様の興味を引くほどの人物なのか、私にその実力を見せてもらいたい」"

[[dialogue]]
speaker = "アニュラス"
# 「最近はどこに行ってもお前の話ばかりだ……私はこの目で確かめるまで、噂などには決して踊らされないからな」
line = "「最近はどこに行ってもお前の話ばかりだ……私はこの目で確かめるまで、噂などには決して踊らされないからな」"

[[dialogue]]
speaker = "アニュラス"
# 「魔剣の力を解き放つ……！　はああぁぁぁッ！」
line = "「魔剣の力を解き放つ……！　はああぁぁぁッ！」"

[[dialogue]]
speaker = "アニュラス"
# 「グラトニーデザイアッ！！！」
line = "「グラトニーデザイアッ！！！」"

[[dialogue]]
speaker = "unk"
# （星徒会メンバーに匹敵するレベルで強い！）
line = "（星徒会メンバーに匹敵するレベルで強い！）"

[[dialogue]]
speaker = "アニュラス"
# 「――どうやら、ここまでのようだな」
line = "「――どうやら、ここまでのようだな」"

[[dialogue]]
speaker = "アニュラス"
# 「なるほど。確かな実力はあるようだ。しかし、まだまだだ」
line = "「なるほど。確かな実力はあるようだ。しかし、まだまだだ」"

[[dialogue]]
speaker = "アニュラス"
# 「お父様にはまだ遠く及ばん。それに、その調子では私にも勝てるかどうか怪しい。本当にあの九浄ヴィーナスに勝ったのか？」
line = "「お父様にはまだ遠く及ばん。それに、その調子では私にも勝てるかどうか怪しい。本当にあの九浄ヴィーナスに勝ったのか？」"

[[dialogue]]
speaker = "アニュラス"
# 「……これでも私は、実技試験では流星学園１年の首席だ。お父様の恥とならないように、努力を続けてきたからな」
line = "「……これでも私は、実技試験では流星学園１年の首席だ。お父様の恥とならないように、努力を続けてきたからな」"

[[dialogue]]
speaker = "unk"
# 学園長も強かった？
line = "学園長も強かった？"

[[dialogue]]
speaker = "アニュラス"
# 「お父様のことを知らないのか？　現役時代には英雄的活躍をした人物だぞ。私じゃなくとも、憧れている生徒は多いはずだ」
line = "「お父様のことを知らないのか？　現役時代には英雄的活躍をした人物だぞ。私じゃなくとも、憧れている生徒は多いはずだ」"

[[dialogue]]
speaker = "アニュラス"
# 「星力が衰えた今でも、剣技のみで生半可な者には負けないはずだ。私の剣もお父様から習ったものだからな」
line = "「星力が衰えた今でも、剣技のみで生半可な者には負けないはずだ。私の剣もお父様から習ったものだからな」"

[[dialogue]]
speaker = "アニュラス"
# 「機会があれば稽古をつけてもらうといい……いや、最近のお父様は忙しそうにしているから無理か……」
line = "「機会があれば稽古をつけてもらうといい……いや、最近のお父様は忙しそうにしているから無理か……」"

[[dialogue]]
speaker = "アニュラス"
# 「なんにせよ、時間を取らせて悪かったな。私の期待するほどの人物ではなかった、ということはわかった」
line = "「なんにせよ、時間を取らせて悪かったな。私の期待するほどの人物ではなかった、ということはわかった」"

[[dialogue]]
speaker = "unk"
# ……待て
line = "……待て"

[[dialogue]]
speaker = "アニュラス"
# 「ん？　どうした」
line = "「ん？　どうした」"

[[dialogue]]
speaker = "アニュラス"
# 「実力の優劣ならば、ついたと思うが？」
line = "「実力の優劣ならば、ついたと思うが？」"

[[dialogue]]
speaker = "unk"
# 次会う時までに、納得させられるようになる
line = "次会う時までに、納得させられるようになる"

[[dialogue]]
speaker = "アニュラス"
# 「……ふむ、心意気は私の好みだな。私も悔しさをバネにしてきたから、お前の気持ちはわかる」
line = "「……ふむ、心意気は私の好みだな。私も悔しさをバネにしてきたから、お前の気持ちはわかる」"

[[dialogue]]
speaker = "アニュラス"
# 「いいだろう、本気ならば受けて立とう」
line = "「いいだろう、本気ならば受けて立とう」"

[[dialogue]]
speaker = "アニュラス"
# 「では、新星の会長、また会おう。私もその日まで、鍛錬に精を出すこととする」
line = "「では、新星の会長、また会おう。私もその日まで、鍛錬に精を出すこととする」"

[[dialogue]]
speaker = "アニュラス"
# 「その時、お父様から教わった剣技も披露してやろう。楽しみにしているといい」
line = "「その時、お父様から教わった剣技も披露してやろう。楽しみにしているといい」"

[[dialogue]]
speaker = "unk"
# 俺は燃え上がる決意を胸に、その日から特訓を開始するのだった。
line = "俺は燃え上がる決意を胸に、その日から特訓を開始するのだった。"
