[[dialogue]]
speaker = "unk"
# 第２話,ウィステリアさんの手作りケーキ,P
line = "第２話,ウィステリアさんの手作りケーキ,P"

[[dialogue]]
speaker = "ウィステリア"
# 「あ、会長くん、また図書館に来てくれたのね。ありがとう、君の顔見ただけで気分良くなっちゃった」
line = "「あ、会長くん、また図書館に来てくれたのね。ありがとう、君の顔見ただけで気分良くなっちゃった」"

[[dialogue]]
speaker = "ウィステリア"
# 「あら、視線が下向いてない？　胸、見てるでしょ？」
line = "「あら、視線が下向いてない？　胸、見てるでしょ？」"

[[dialogue]]
speaker = "unk"
# 服が大胆すぎてつい……
line = "服が大胆すぎてつい……"

[[dialogue]]
speaker = "ウィステリア"
# 「う……。いやこれはヘレナさんからもらったやつで……ほら、ヘレナさん、服のデザインもしてるでしょ」
line = "「う……。いやこれはヘレナさんからもらったやつで……ほら、ヘレナさん、服のデザインもしてるでしょ」"

[[dialogue]]
speaker = "ウィステリア"
# 「意外と着心地いいのよ、これ。慣れたら手放せなくて……」
line = "「意外と着心地いいのよ、これ。慣れたら手放せなくて……」"

[[dialogue]]
speaker = "ウィステリア"
# 「まぁ、そんなことはいいのよ。会長くんなら見られてもいいし」
line = "「まぁ、そんなことはいいのよ。会長くんなら見られてもいいし」"

[[dialogue]]
speaker = "ウィステリア"
# 「ああ、そうだ。会長くん、ちょっとだけ相談していい？」
line = "「ああ、そうだ。会長くん、ちょっとだけ相談していい？」"

[[dialogue]]
speaker = "unk"
# もちろんです
line = "もちろんです"

[[dialogue]]
speaker = "ウィステリア"
# 「ありがとう。やっぱり会長くんは頼りになるわね」
line = "「ありがとう。やっぱり会長くんは頼りになるわね」"

[[dialogue]]
speaker = "ウィステリア"
# 「いやー、本当に大したことじゃないんだけど、最近細々とした仕事のストレスが溜まっててね。どうにかして発散したいなーと思ってるのよ」
line = "「いやー、本当に大したことじゃないんだけど、最近細々とした仕事のストレスが溜まっててね。どうにかして発散したいなーと思ってるのよ」"

[[dialogue]]
speaker = "ウィステリア"
# 「だけど自分でも何していいかわからなくて。今は特別気になるスイーツもないし……」
line = "「だけど自分でも何していいかわからなくて。今は特別気になるスイーツもないし……」"

[[dialogue]]
speaker = "ウィステリア"
# 「……あ、そうだ」
line = "「……あ、そうだ」"

[[dialogue]]
speaker = "ウィステリア"
# 「会長くん、ケーキ食べる？」
line = "「会長くん、ケーキ食べる？」"

[[dialogue]]
speaker = "unk"
# その週末。ウィステリアさんが俺の自宅にやってきた。
line = "その週末。ウィステリアさんが俺の自宅にやってきた。"

[[dialogue]]
speaker = "ウィステリア"
# 「キッチン借りちゃうわね。ふふ、気合入っちゃうわ」
line = "「キッチン借りちゃうわね。ふふ、気合入っちゃうわ」"

[[dialogue]]
speaker = "unk"
# ウィステリアさんがケーキ作るんですか？
line = "ウィステリアさんがケーキ作るんですか？"

[[dialogue]]
speaker = "ウィステリア"
# 「そんなに意外そうな顔しないでよ。私、これでも自炊するし、お菓子だって作れるのよ」
line = "「そんなに意外そうな顔しないでよ。私、これでも自炊するし、お菓子だって作れるのよ」"

[[dialogue]]
speaker = "ウィステリア"
# 「昔、星見家メイド隊でバイトしてたってのは言ったっけ？」
line = "「昔、星見家メイド隊でバイトしてたってのは言ったっけ？」"

[[dialogue]]
speaker = "ウィステリア"
# 「あ、思い出した。キリカが勝手に喋ったんだったわね……もう、あの陰険メイド長ってば」
line = "「あ、思い出した。キリカが勝手に喋ったんだったわね……もう、あの陰険メイド長ってば」"

[[dialogue]]
speaker = "unk"
# キリカ師匠の影響でお菓子好きに？
line = "キリカ師匠の影響でお菓子好きに？"

[[dialogue]]
speaker = "ウィステリア"
# 「まぁ……そうね。キリカのおかげっていうのは癪だけど、人間界に来る前の私は、甘いものなんて全然食べたことなかったから」
line = "「まぁ……そうね。キリカのおかげっていうのは癪だけど、人間界に来る前の私は、甘いものなんて全然食べたことなかったから」"

[[dialogue]]
speaker = "ウィステリア"
# 「キリカが作ってくれたケーキはそれはもう美味しくて、ほんとに驚いちゃった」
line = "「キリカが作ってくれたケーキはそれはもう美味しくて、ほんとに驚いちゃった」"

[[dialogue]]
speaker = "ウィステリア"
# 「あの頃はキリカもまだメイド長じゃなかったから、ケーキを焼く練習に付き合ったりしてね」
line = "「あの頃はキリカもまだメイド長じゃなかったから、ケーキを焼く練習に付き合ったりしてね」"

[[dialogue]]
speaker = "ウィステリア"
# 「小言は多いけど、キリカのお菓子作りの腕は認めてるわ。もうちょっと素直なら可愛げもあるのにね」
line = "「小言は多いけど、キリカのお菓子作りの腕は認めてるわ。もうちょっと素直なら可愛げもあるのにね」"

[[dialogue]]
speaker = "ウィステリア"
# 「なに？　ニヤニヤしちゃって。……キリカと仲がいい？　そんなわけないでしょ、いくら会長くんでも怒るわよ」
line = "「なに？　ニヤニヤしちゃって。……キリカと仲がいい？　そんなわけないでしょ、いくら会長くんでも怒るわよ」"

[[dialogue]]
speaker = "ウィステリア"
# 「さて、それじゃそのキリカ直伝のケーキを作りましょうか」
line = "「さて、それじゃそのキリカ直伝のケーキを作りましょうか」"

[[dialogue]]
speaker = "ウィステリア"
# 「手出しは無用よ、会長くん。君がいろいろできるのは知ってるけど、ここは私に任せなさい♪」
line = "「手出しは無用よ、会長くん。君がいろいろできるのは知ってるけど、ここは私に任せなさい♪」"

[[dialogue]]
speaker = "ウィステリア"
# 「焼き上がったのを冷まして……粉砂糖をかけて……っと。はい、ガトーショコラの出来上がり♪」
line = "「焼き上がったのを冷まして……粉砂糖をかけて……っと。はい、ガトーショコラの出来上がり♪」"

[[dialogue]]
speaker = "ウィステリア"
# 「我ながら綺麗にできたわ。いつもは食べる側だけど、たまに作るとストレス発散になるわね♪」
line = "「我ながら綺麗にできたわ。いつもは食べる側だけど、たまに作るとストレス発散になるわね♪」"

[[dialogue]]
speaker = "ウィステリア"
# 「それじゃ……」
line = "「それじゃ……」"

[[dialogue]]
speaker = "ウィステリア"
# 「はい、あ～ん<emoji=heart04>」
line = "「はい、あ～ん<emoji=heart04>」"

[[dialogue]]
speaker = "ウィステリア"
# 「……どう？　美味しい？」
line = "「……どう？　美味しい？」"

[[dialogue]]
speaker = "unk"
# すごく美味しいです！
line = "すごく美味しいです！"

[[dialogue]]
speaker = "ウィステリア"
# 「ふふふ♪　口に合って良かったわ。マズイって言われたら呪ってたかも」
line = "「ふふふ♪　口に合って良かったわ。マズイって言われたら呪ってたかも」"

[[dialogue]]
speaker = "ウィステリア"
# 「ふふっ、冗談よ。怖がらないで。そんなことで呪ったりしないわ」
line = "「ふふっ、冗談よ。怖がらないで。そんなことで呪ったりしないわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「ほら、ケーキまだまだあるから食べて。あ～ん<emoji=heart04>」
line = "「ほら、ケーキまだまだあるから食べて。あ～ん<emoji=heart04>」"

[[dialogue]]
speaker = "ウィステリア"
# 「……ふふふ♪」
line = "「……ふふふ♪」"

[[dialogue]]
speaker = "ウィステリア"
# 「自分でスイーツを食べるのもいいけど、好きになった人に食べてもらうのもいいわね」
line = "「自分でスイーツを食べるのもいいけど、好きになった人に食べてもらうのもいいわね」"

[[dialogue]]
speaker = "ウィステリア"
# 「私ね。今すごく幸せなの」
line = "「私ね。今すごく幸せなの」"

[[dialogue]]
speaker = "ウィステリア"
# 「君と２人っきりで……私が作ったケーキで君が笑顔になってくれて……こんな時間がずっと続けばいいのにって思っちゃう」
line = "「君と２人っきりで……私が作ったケーキで君が笑顔になってくれて……こんな時間がずっと続けばいいのにって思っちゃう」"

[[dialogue]]
speaker = "ウィステリア"
# 「私って年下好きだったのかしら。少女漫画みたいなドラマチックな恋に憧れてた頃もあったけど、漫画の王子様より君がいいわ」
line = "「私って年下好きだったのかしら。少女漫画みたいなドラマチックな恋に憧れてた頃もあったけど、漫画の王子様より君がいいわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「君を見ているだけで、つい頬が緩んじゃって。こんな気持ちになれる日が来るなんて思わなかったなぁ……」
line = "「君を見ているだけで、つい頬が緩んじゃって。こんな気持ちになれる日が来るなんて思わなかったなぁ……」"

[[dialogue]]
speaker = "unk"
# 俺も幸せですよ
line = "俺も幸せですよ"

[[dialogue]]
speaker = "ウィステリア"
# 「言わせちゃってない？　私、年上だし、呪われてるのよ？」
line = "「言わせちゃってない？　私、年上だし、呪われてるのよ？」"

[[dialogue]]
speaker = "ウィステリア"
# 「って、会長くんが言ってくれてるんだから、不安になっちゃダメよね。年上って言っても３つだけだし」
line = "「って、会長くんが言ってくれてるんだから、不安になっちゃダメよね。年上って言っても３つだけだし」"

[[dialogue]]
speaker = "ウィステリア"
# 「だけど、今の言葉がウソじゃないって、行動で示してもらってもいい？」
line = "「だけど、今の言葉がウソじゃないって、行動で示してもらってもいい？」"

[[dialogue]]
speaker = "unk"
# そう言って頬を赤く染めるウィステリアさん。
line = "そう言って頬を赤く染めるウィステリアさん。"

[[dialogue]]
speaker = "unk"
# 俺もゆっくり顔を近づけていって──
line = "俺もゆっくり顔を近づけていって──"

[[dialogue]]
speaker = "ウィステリア"
# 「ひゃああっ！？　こんな時にモンスター！？」
line = "「ひゃああっ！？　こんな時にモンスター！？」"

[[dialogue]]
speaker = "ウィステリア"
# 「もう、仕方ないわね。さっさと片付けるわよ！」
line = "「もう、仕方ないわね。さっさと片付けるわよ！」"

[[dialogue]]
speaker = "ウィステリア"
# 「シャドウメイルストラム！」
line = "「シャドウメイルストラム！」"

[[dialogue]]
speaker = "unk"
# ウィステリアさんの星術が炸裂し、今日もモンスターを蹴散らすのだった……
line = "ウィステリアさんの星術が炸裂し、今日もモンスターを蹴散らすのだった……"
