[[dialogue]]
speaker = "unk"
# 第４話,今日はデート？,P
line = "第４話,今日はデート？,P"

[[dialogue]]
speaker = "セーラ"
# 「ふんふん……ふんふん……うんっ、それじゃまた」
line = "「ふんふん……ふんふん……うんっ、それじゃまた」"

[[dialogue]]
speaker = "セーラ"
# 「あ、ごめん。ちょっと電話してた。いやぁ～、この前はありがとねー」
line = "「あ、ごめん。ちょっと電話してた。いやぁ～、この前はありがとねー」"

[[dialogue]]
speaker = "セーラ"
# 「いやいやそんな謙遜しないでって。それにありがとうは、ガチャのことだけじゃないからね。ほら、こないだ一緒におばあちゃん案内したっしょ」
line = "「いやいやそんな謙遜しないでって。それにありがとうは、ガチャのことだけじゃないからね。ほら、こないだ一緒におばあちゃん案内したっしょ」"

[[dialogue]]
speaker = "セーラ"
# 「あの時オススメのとこがあるって言ってたの覚えてる？　あそこ行こーよ」
line = "「あの時オススメのとこがあるって言ってたの覚えてる？　あそこ行こーよ」"

[[dialogue]]
speaker = "セーラ"
# 「おっけー？　じゃあ……デートしよっか」
line = "「おっけー？　じゃあ……デートしよっか」"

[[dialogue]]
speaker = "セーラ"
# 「ぷっ、慌ててる慌ててる。……別にデートじゃないって？　え～、男子と女子が一緒に歩いてたらデートっしょ」
line = "「ぷっ、慌ててる慌ててる。……別にデートじゃないって？　え～、男子と女子が一緒に歩いてたらデートっしょ」"

[[dialogue]]
speaker = "セーラ"
# 「それともうちとデートするの……イヤ？」
line = "「それともうちとデートするの……イヤ？」"

[[dialogue]]
speaker = "unk"
# イヤじゃないです！
line = "イヤじゃないです！"

[[dialogue]]
speaker = "セーラ"
# 「ならよし。レッツゴ～」
line = "「ならよし。レッツゴ～」"

[[dialogue]]
speaker = "セーラ"
# 「あ、ここここ。すいませーん、たい焼き２つくださーい。こしあんで」
line = "「あ、ここここ。すいませーん、たい焼き２つくださーい。こしあんで」"

[[dialogue]]
speaker = "セーラ"
# 「ん？　クレープかタピオカだと思った？　ふっふん、ここのたい焼きめっちゃおいしいんだから」
line = "「ん？　クレープかタピオカだと思った？　ふっふん、ここのたい焼きめっちゃおいしいんだから」"

[[dialogue]]
speaker = "セーラ"
# 「ってあれ？　もしかして会長さんもここ知ってた？　さすがいろいろバイトしてただけはあるね、情報通なんだ」
line = "「ってあれ？　もしかして会長さんもここ知ってた？　さすがいろいろバイトしてただけはあるね、情報通なんだ」"

[[dialogue]]
speaker = "セーラ"
# 「あ、焼けたみたい。はい、会長さんの分」
line = "「あ、焼けたみたい。はい、会長さんの分」"

[[dialogue]]
speaker = "unk"
# おいしい！
line = "おいしい！"

[[dialogue]]
speaker = "セーラ"
# 「ん～、おいしー♪　ここのたい焼き、皮の厚さとあんこの甘さのバランスが絶妙なんだよね～」
line = "「ん～、おいしー♪　ここのたい焼き、皮の厚さとあんこの甘さのバランスが絶妙なんだよね～」"

[[dialogue]]
speaker = "セーラ"
# 「うち、流星市国に引っ越してくる前は割と田舎の方で暮らしててね。おばあちゃんがよくおまんじゅうとかくれたから、和菓子とかも好きなんだ」
line = "「うち、流星市国に引っ越してくる前は割と田舎の方で暮らしててね。おばあちゃんがよくおまんじゅうとかくれたから、和菓子とかも好きなんだ」"

[[dialogue]]
speaker = "セーラ"
# 「新しい味もいろいろ種類あるみたい。おじさん、アップルカスタードとキャラメルチョコくださーい」
line = "「新しい味もいろいろ種類あるみたい。おじさん、アップルカスタードとキャラメルチョコくださーい」"

[[dialogue]]
speaker = "セーラ"
# 「はむはむ……アップルカスタードのたい焼きもイケるね。ね、そっちのキャラメルチョコも一口ちょうだい？」
line = "「はむはむ……アップルカスタードのたい焼きもイケるね。ね、そっちのキャラメルチョコも一口ちょうだい？」"

[[dialogue]]
speaker = "セーラ"
# 「食べかけとか気にしない気にしない。うちのもあげるからさ。ほら、あーん」
line = "「食べかけとか気にしない気にしない。うちのもあげるからさ。ほら、あーん」"

[[dialogue]]
speaker = "セーラ"
# 「おいしい？　へへっ、だよねー。リンゴの甘酸っぱさとカスタードが相性良くていくらでも食べられそうな感じ」
line = "「おいしい？　へへっ、だよねー。リンゴの甘酸っぱさとカスタードが相性良くていくらでも食べられそうな感じ」"

[[dialogue]]
speaker = "セーラ"
# 「じゃあそっちのもらうよ。あ～んして、あ～ん。ほらほら、恥ずかしがらないでってば～」
line = "「じゃあそっちのもらうよ。あ～んして、あ～ん。ほらほら、恥ずかしがらないでってば～」"

[[dialogue]]
speaker = "セーラ"
# 「はぁむっ。おぉ～、これは濃厚。カロリーやばそうだけどめっちゃおいしい」
line = "「はぁむっ。おぉ～、これは濃厚。カロリーやばそうだけどめっちゃおいしい」"

[[dialogue]]
speaker = "セーラ"
# 「あ、お金のことは気にしなくていいよ。お礼だからうちのおごりだし」
line = "「あ、お金のことは気にしなくていいよ。お礼だからうちのおごりだし」"

[[dialogue]]
speaker = "unk"
# ありがとうございます
line = "ありがとうございます"

[[dialogue]]
speaker = "セーラ"
# 「ふふん、たーんと召し上がれ♪」
line = "「ふふん、たーんと召し上がれ♪」"

[[dialogue]]
speaker = "セーラ"
# 「ここのたい焼きもセンパイと一緒に食べたなぁ。いやぁ、懐かし～」
line = "「ここのたい焼きもセンパイと一緒に食べたなぁ。いやぁ、懐かし～」"

[[dialogue]]
speaker = "セーラ"
# 「ところでさ、前から気になってたんだけど、会長さんは新星の星徒会の誰と仲いいの？」
line = "「ところでさ、前から気になってたんだけど、会長さんは新星の星徒会の誰と仲いいの？」"

[[dialogue]]
speaker = "セーラ"
# 「やっぱりヴィーナスちゃん？　それとも真面目なマトイちゃん？　クールなアナちゃんや優しいサーシャさんもいいよねー」
line = "「やっぱりヴィーナスちゃん？　それとも真面目なマトイちゃん？　クールなアナちゃんや優しいサーシャさんもいいよねー」"

[[dialogue]]
speaker = "セーラ"
# 「特に誰とってことはないカンジ？　へ～、そうなんだー。ふーん……」
line = "「特に誰とってことはないカンジ？　へ～、そうなんだー。ふーん……」"

[[dialogue]]
speaker = "セーラ"
# 「はむ、はむ……ごちそうさま。ここのたい焼き、久々だけどやっぱりおいしかった～」
line = "「はむ、はむ……ごちそうさま。ここのたい焼き、久々だけどやっぱりおいしかった～」"

[[dialogue]]
speaker = "セーラ"
# 「えっ……うちがたい焼き屋さんの社長？　うーん……確かに好きだけど、新規参入できるかな……」
line = "「えっ……うちがたい焼き屋さんの社長？　うーん……確かに好きだけど、新規参入できるかな……」"

[[dialogue]]
speaker = "セーラ"
# 「いや待てよ。和菓子ってけっこう幅広くアレンジできるし、やりようによっては……うん、考えとく」
line = "「いや待てよ。和菓子ってけっこう幅広くアレンジできるし、やりようによっては……うん、考えとく」"

[[dialogue]]
speaker = "セーラ"
# 「ねえ会長さん。もしうちが社長になって、会長さんが新星学園卒業したら……パートナーにならない？」
line = "「ねえ会長さん。もしうちが社長になって、会長さんが新星学園卒業したら……パートナーにならない？」"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "セーラ"
# 「あ、パートナーって言っても仕事のだよ？　会長さんは何のパートナーだと思ったのかな～？」
line = "「あ、パートナーって言っても仕事のだよ？　会長さんは何のパートナーだと思ったのかな～？」"

[[dialogue]]
speaker = "セーラ"
# 「ふふっ、赤くなってる。かっわいい～♪」
line = "「ふふっ、赤くなってる。かっわいい～♪」"

[[dialogue]]
speaker = "セーラ"
# 「あはは、からかってごめんってば。でも冗談で言ってるんじゃないよ。うちんとこの社員にならない？」
line = "「あはは、からかってごめんってば。でも冗談で言ってるんじゃないよ。うちんとこの社員にならない？」"

[[dialogue]]
speaker = "セーラ"
# 「割と本気。会長さんが近くにいてくれるといいなって思ってる。どう？」
line = "「割と本気。会長さんが近くにいてくれるといいなって思ってる。どう？」"

[[dialogue]]
speaker = "セーラ"
# 「……って、急に言われても困るよね。ま、ちょっと卒業するまでに考えといてよ。うちは待ってるから」
line = "「……って、急に言われても困るよね。ま、ちょっと卒業するまでに考えといてよ。うちは待ってるから」"

[[dialogue]]
speaker = "セーラ"
# 「ちなみに、なんで社長になりたいかって言うと……うちが言ってたセンパイ、卒業してすぐに起業してんの」
line = "「ちなみに、なんで社長になりたいかって言うと……うちが言ってたセンパイ、卒業してすぐに起業してんの」"

[[dialogue]]
speaker = "セーラ"
# 「あの人から話聞いてたら、社長いいなーって思って。女社長目指して密かに勉強中ってワケ。この後も会う約束してるんだ」
line = "「あの人から話聞いてたら、社長いいなーって思って。女社長目指して密かに勉強中ってワケ。この後も会う約束してるんだ」"

[[dialogue]]
speaker = "セーラ"
# 「だから本読んだりして勉強してるし、授業も真面目に聞いてる。実はうち、成績いいんだよ。特に英語はしっかりやってるし」
line = "「だから本読んだりして勉強してるし、授業も真面目に聞いてる。実はうち、成績いいんだよ。特に英語はしっかりやってるし」"

[[dialogue]]
speaker = "セーラ"
# 「だけどその前に世界の平和！　うちが社長になるためにも、頑張って世界を守ろうねっ♪」
line = "「だけどその前に世界の平和！　うちが社長になるためにも、頑張って世界を守ろうねっ♪」"
