[[dialogue]]
speaker = "unk"
# 第４話,２人の距離でゆっくりと,P
line = "第４話,２人の距離でゆっくりと,P"

[[dialogue]]
speaker = "unk"
# 会長の家で２人きりのクリスマスパーティーを楽しんでから、週末が明けた翌日。
line = "会長の家で２人きりのクリスマスパーティーを楽しんでから、週末が明けた翌日。"

[[dialogue]]
speaker = "unk"
# アムは附属校３年の教室で、クラスメイトの女子から尋ねられた。
line = "アムは附属校３年の教室で、クラスメイトの女子から尋ねられた。"

[[dialogue]]
speaker = "アム"
# 「――週末に会長とどんなイチャイチャしたのかって？」
line = "「――週末に会長とどんなイチャイチャしたのかって？」"

[[dialogue]]
speaker = "附属生Ａ"
# 「ほら、改めて２人でクリスマス気分で過ごすっていう感じだったんでしょ？　ってことは、当然甘～い雰囲気になってスキンシップとかしちゃうわけじゃん？」
line = "「ほら、改めて２人でクリスマス気分で過ごすっていう感じだったんでしょ？　ってことは、当然甘～い雰囲気になってスキンシップとかしちゃうわけじゃん？」"

[[dialogue]]
speaker = "附属生Ａ"
# 「会長は、普段は紳士的で中性的な感じだけど、２人きりになると結構男らしくて、積極的になるってアムから聞いてたし、どうだったのか気になっちゃって～♪」
line = "「会長は、普段は紳士的で中性的な感じだけど、２人きりになると結構男らしくて、積極的になるってアムから聞いてたし、どうだったのか気になっちゃって～♪」"

[[dialogue]]
speaker = "アム"
# 「……そういえば、スキンシップしてないかも」
line = "「……そういえば、スキンシップしてないかも」"

[[dialogue]]
speaker = "附属生Ａ"
# 「え？　いやいや、まっさか～！　キスとか、もっとすごいこともしちゃったんじゃないの～？　誤魔化さないで教えてよ～」
line = "「え？　いやいや、まっさか～！　キスとか、もっとすごいこともしちゃったんじゃないの～？　誤魔化さないで教えてよ～」"

[[dialogue]]
speaker = "アム"
# 「い、いや……スキンシップは確かにしなかったけど、その日はすごく楽しかったよ？　食事して、いっぱい話して、それから対戦ゲームで夜遅くまで対戦したりして……！」
line = "「い、いや……スキンシップは確かにしなかったけど、その日はすごく楽しかったよ？　食事して、いっぱい話して、それから対戦ゲームで夜遅くまで対戦したりして……！」"

[[dialogue]]
speaker = "附属生Ａ"
# 「え……もしかして、マジなの……？」
line = "「え……もしかして、マジなの……？」"

[[dialogue]]
speaker = "アム"
# 「…………うん。そういうことするの、頭から完全に抜けてたっぽい……」
line = "「…………うん。そういうことするの、頭から完全に抜けてたっぽい……」"

[[dialogue]]
speaker = "unk"
# 週明けの放課後、俺は久しぶりにアムと２人で日課の戦闘訓練を再開することになった。
line = "週明けの放課後、俺は久しぶりにアムと２人で日課の戦闘訓練を再開することになった。"

[[dialogue]]
speaker = "アム"
# （う～ん……）
line = "（う～ん……）"

[[dialogue]]
speaker = "unk"
# だが――なにやらアムの様子がおかしい。いつもなら戦闘訓練の時は張り切って楽しそうにしているのに、今日は他のことに気を取られているような様子だった。
line = "だが――なにやらアムの様子がおかしい。いつもなら戦闘訓練の時は張り切って楽しそうにしているのに、今日は他のことに気を取られているような様子だった。"

[[dialogue]]
speaker = "アム"
# （自分から、最近スキンシップができてなかったよね～、って言うのは、『いい女』としてカッコよくない気がするし……）
line = "（自分から、最近スキンシップができてなかったよね～、って言うのは、『いい女』としてカッコよくない気がするし……）"

[[dialogue]]
speaker = "unk"
# アム、提案があるんだけど、いいか？
line = "アム、提案があるんだけど、いいか？"

[[dialogue]]
speaker = "アム"
# 「――え？　模擬戦で勝負して会長が勝ったら、久しぶりに触れあって、イチャイチャしたい……？」
line = "「――え？　模擬戦で勝負して会長が勝ったら、久しぶりに触れあって、イチャイチャしたい……？」"

[[dialogue]]
speaker = "unk"
# そうして、俺は模擬戦に挑んで、アムに勝利する。
line = "そうして、俺は模擬戦に挑んで、アムに勝利する。"

[[dialogue]]
speaker = "アム"
# 「な、なんかあっという間に負けちゃった……！」
line = "「な、なんかあっという間に負けちゃった……！」"

[[dialogue]]
speaker = "unk"
# じゃあ……触れてもいい？
line = "じゃあ……触れてもいい？"

[[dialogue]]
speaker = "アム"
# 「えっと……う、うん。負けちゃったし、約束だから……仕方ないよね？」
line = "「えっと……う、うん。負けちゃったし、約束だから……仕方ないよね？」"

[[dialogue]]
speaker = "unk"
# もじもじと照れながらこちらを見てくるアムに、俺はそっと近づき、耳元で囁く。
line = "もじもじと照れながらこちらを見てくるアムに、俺はそっと近づき、耳元で囁く。"

[[dialogue]]
speaker = "unk"
# アム、久しぶりに、抱き締めるよ
line = "アム、久しぶりに、抱き締めるよ"

[[dialogue]]
speaker = "アム"
# 「あっ……<emoji=heart04>」
line = "「あっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺がアムの小さな体を抱き寄せると、可愛い声が漏れる。
line = "俺がアムの小さな体を抱き寄せると、可愛い声が漏れる。"

[[dialogue]]
speaker = "アム"
# （会長、中性的な見た目で線が細い感じなのに、抱き締められると思ったより筋肉質でガッシリしてて……<emoji=heart04>　男の人って感じがして、ドキドキしちゃう……<emoji=heart04>）
line = "（会長、中性的な見た目で線が細い感じなのに、抱き締められると思ったより筋肉質でガッシリしてて……<emoji=heart04>　男の人って感じがして、ドキドキしちゃう……<emoji=heart04>）"

[[dialogue]]
speaker = "アム"
# 「その……さ、会長……？　週末にスキンシップできなくて……もしかして、我慢してたりした……？」
line = "「その……さ、会長……？　週末にスキンシップできなくて……もしかして、我慢してたりした……？」"

[[dialogue]]
speaker = "unk"
# やっぱりちょっとは期待してたかな
line = "やっぱりちょっとは期待してたかな"

[[dialogue]]
speaker = "unk"
# 俺はアムのことが好き過ぎるから
line = "俺はアムのことが好き過ぎるから"

[[dialogue]]
speaker = "アム"
# 「そう、だよね……ごめん。あたし、浮かれてて、そこまで考えられてなくて……気づこうともしてなかった……」
line = "「そう、だよね……ごめん。あたし、浮かれてて、そこまで考えられてなくて……気づこうともしてなかった……」"

[[dialogue]]
speaker = "unk"
# 俺は首を横に振って、彼女の頭を撫でながら言う。
line = "俺は首を横に振って、彼女の頭を撫でながら言う。"

[[dialogue]]
speaker = "アム"
# 「――あたしはどちらかというと、そこまで恋人とベタベタしないタイプなんじゃないかって……？」
line = "「――あたしはどちらかというと、そこまで恋人とベタベタしないタイプなんじゃないかって……？」"

[[dialogue]]
speaker = "アム"
# 「そう、なのかな……？　あたし、週末は久しぶりに２人で過ごせるだけで楽しくて……スキンシップとか意識せずに、忘れちゃってて……」
line = "「そう、なのかな……？　あたし、週末は久しぶりに２人で過ごせるだけで楽しくて……スキンシップとか意識せずに、忘れちゃってて……」"

[[dialogue]]
speaker = "unk"
# アムが楽しかったなら、それでいい
line = "アムが楽しかったなら、それでいい"

[[dialogue]]
speaker = "unk"
# それに、たまにこうしてアムと触れ合うと、その分すごく好きだなぁって再確認できるから問題ない――と、俺は話して伝える。
line = "それに、たまにこうしてアムと触れ合うと、その分すごく好きだなぁって再確認できるから問題ない――と、俺は話して伝える。"

[[dialogue]]
speaker = "アム"
# 「会長……<emoji=heart04>　ねぇ、じゃあ今日は……キスしてもいい？」
line = "「会長……<emoji=heart04>　ねぇ、じゃあ今日は……キスしてもいい？」"

[[dialogue]]
speaker = "unk"
# 俺はもちろんだと頷くと、そっとアムと唇を重ねる。
line = "俺はもちろんだと頷くと、そっとアムと唇を重ねる。"

[[dialogue]]
speaker = "アム"
# 「んっ……<emoji=heart04>　んむっ……ちゅっ……<emoji=heart04>」
line = "「んっ……<emoji=heart04>　んむっ……ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アム"
# 「――はあぁ<emoji=heart04>　……あたし、確かに四六時中ベタベタしていたいとは思わないタイプなのかも」
line = "「――はあぁ<emoji=heart04>　……あたし、確かに四六時中ベタベタしていたいとは思わないタイプなのかも」"

[[dialogue]]
speaker = "アム"
# 「あたしは、会長と一緒に戦闘訓練するのも好きだし……一緒に外に出かけたり、ゲームで勝負するのも好きだし……」
line = "「あたしは、会長と一緒に戦闘訓練するのも好きだし……一緒に外に出かけたり、ゲームで勝負するのも好きだし……」"

[[dialogue]]
speaker = "アム"
# 「で、でもね、勘違いしないで欲しいのは、こうしてスキンシップするのも、あたしは好きで、全然嫌じゃないよ？」
line = "「で、でもね、勘違いしないで欲しいのは、こうしてスキンシップするのも、あたしは好きで、全然嫌じゃないよ？」"

[[dialogue]]
speaker = "アム"
# 「ただ、普段はなんか恥ずかしくなっちゃうから、そういう雰囲気にならないと、自分からはなかなか言い出せなくて……」
line = "「ただ、普段はなんか恥ずかしくなっちゃうから、そういう雰囲気にならないと、自分からはなかなか言い出せなくて……」"

[[dialogue]]
speaker = "unk"
# なら、お互いに勝負だな
line = "なら、お互いに勝負だな"

[[dialogue]]
speaker = "アム"
# 「え？　――相手がスキンシップしたいって思っているタイミングを見極められるかの勝負……？」
line = "「え？　――相手がスキンシップしたいって思っているタイミングを見極められるかの勝負……？」"

[[dialogue]]
speaker = "unk"
# 俺は頷く。すぐにはアムの望むタイミングがわかるようにはならないだろう。だが、少しずつアムが『心地いいと思える距離感』を見つけていきたい。
line = "俺は頷く。すぐにはアムの望むタイミングがわかるようにはならないだろう。だが、少しずつアムが『心地いいと思える距離感』を見つけていきたい。"

[[dialogue]]
speaker = "アム"
# 「――あたし達は、これから長く付き合っていく恋人だから、時間をかけてゆっくりと……？」
line = "「――あたし達は、これから長く付き合っていく恋人だから、時間をかけてゆっくりと……？」"

[[dialogue]]
speaker = "アム"
# （ああ、会長……やっぱりカッコいいな。腕っぷしだけじゃなくて……あたしのことを想ってくれる、優しいところも……）
line = "（ああ、会長……やっぱりカッコいいな。腕っぷしだけじゃなくて……あたしのことを想ってくれる、優しいところも……）"

[[dialogue]]
speaker = "アム"
# （だからあたし、会長のことを『好き』になったんだ……<emoji=heart04>）
line = "（だからあたし、会長のことを『好き』になったんだ……<emoji=heart04>）"

[[dialogue]]
speaker = "アム"
# 「……勝負なら、あたしも負けないように頑張っていかないとね<emoji=heart04>」
line = "「……勝負なら、あたしも負けないように頑張っていかないとね<emoji=heart04>」"

[[dialogue]]
speaker = "アム"
# 「ねぇ、会長……もう１回、キスしてもいい……？」
line = "「ねぇ、会長……もう１回、キスしてもいい……？」"

[[dialogue]]
speaker = "アム"
# 「んっ……<emoji=heart04>　ちゅっ……<emoji=heart04>　んむっ……ちゅっ……<emoji=heart04>」
line = "「んっ……<emoji=heart04>　ちゅっ……<emoji=heart04>　んむっ……ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# それから俺は久しぶりに沢山、アムとの甘いスキンシップの時間を過ごすのだった。
line = "それから俺は久しぶりに沢山、アムとの甘いスキンシップの時間を過ごすのだった。"
