[[dialogue]]
speaker = "unk"
# 第４話,金欠の理由,P
line = "第４話,金欠の理由,P"

[[dialogue]]
speaker = "ユウリ"
# 「い、いらっしゃいませ～。本日は当カジノへようこそ～」
line = "「い、いらっしゃいませ～。本日は当カジノへようこそ～」"

[[dialogue]]
speaker = "ユウリ"
# 「……はぁ。やっぱ何度やっても慣れねえ。このカッコで笑顔浮かべるだけでも表情筋がヒクヒクしちまう……」
line = "「……はぁ。やっぱ何度やっても慣れねえ。このカッコで笑顔浮かべるだけでも表情筋がヒクヒクしちまう……」"

[[dialogue]]
speaker = "unk"
# ならどうしてまたカジノでバイトを
line = "ならどうしてまたカジノでバイトを"

[[dialogue]]
speaker = "ユウリ"
# 「う、うっせーな。金欠になっちまったんだから仕方ねえだろ。このバイト、割だけはいいし」
line = "「う、うっせーな。金欠になっちまったんだから仕方ねえだろ。このバイト、割だけはいいし」"

[[dialogue]]
speaker = "ユウリ"
# 「つかなんで会長さんまでバイトしてんだよ？　あんたは一緒じゃなくても良かったのに」
line = "「つかなんで会長さんまでバイトしてんだよ？　あんたは一緒じゃなくても良かったのに」"

[[dialogue]]
speaker = "ユウリ"
# 「大方あたしのこと心配してついてきたんだろ？　ガキ扱いするなっての。バイトくらい１人でできるって」
line = "「大方あたしのこと心配してついてきたんだろ？　ガキ扱いするなっての。バイトくらい１人でできるって」"

[[dialogue]]
speaker = "ユウリ"
# 「んまあ……気持ちは嬉しいけど。正直、１人でバイトするの心細かったし……」
line = "「んまあ……気持ちは嬉しいけど。正直、１人でバイトするの心細かったし……」"

[[dialogue]]
speaker = "ユウリ"
# 「でも突然バイトなんか入れちゃって悪かったな。今日も、その……せっかくデートに誘ってくれてたのに」
line = "「でも突然バイトなんか入れちゃって悪かったな。今日も、その……せっかくデートに誘ってくれてたのに」"

[[dialogue]]
speaker = "unk"
# ユウリと一緒ならなんだってデートだよ
line = "ユウリと一緒ならなんだってデートだよ"

[[dialogue]]
speaker = "ユウリ"
# 「～～っっ。毎度毎度恥ずかしいこと言うなよ。言っとくけどバイト中はこの前したようなこと禁止だからなっ？」
line = "「～～っっ。毎度毎度恥ずかしいこと言うなよ。言っとくけどバイト中はこの前したようなこと禁止だからなっ？」"

[[dialogue]]
speaker = "ユウリ"
# 「だ、だからキスだよ、キス……！　フロアの真ん中でした日にはぶっ飛ばすからなっ……！」
line = "「だ、だからキスだよ、キス……！　フロアの真ん中でした日にはぶっ飛ばすからなっ……！」"

[[dialogue]]
speaker = "ユウリ"
# 「バックヤードで……とかも絶対ダメだからっ。フリじゃねえぞっ？　やった瞬間、別れ話を切り出すからなっ……！」
line = "「バックヤードで……とかも絶対ダメだからっ。フリじゃねえぞっ？　やった瞬間、別れ話を切り出すからなっ……！」"

[[dialogue]]
speaker = "ユウリ"
# 「……わかってるならいいけど。その代わり、えと……。部屋に戻ったらいくらでもしてやるし……」
line = "「……わかってるならいいけど。その代わり、えと……。部屋に戻ったらいくらでもしてやるし……」"

[[dialogue]]
speaker = "ユウリ"
# 「それに今日は、サプライズも……」
line = "「それに今日は、サプライズも……」"

[[dialogue]]
speaker = "ユウリ"
# 「っっ。い、いや、なんでもねえっ。とにかく今はバイト中なんだから、あんま喋りかけてくんなってっ」
line = "「っっ。い、いや、なんでもねえっ。とにかく今はバイト中なんだから、あんま喋りかけてくんなってっ」"

[[dialogue]]
speaker = "ユウリ"
# 「会長さんも自分の仕事あんだろっ？　あたしは大丈夫だから自分の仕事に戻れってっ」
line = "「会長さんも自分の仕事あんだろっ？　あたしは大丈夫だから自分の仕事に戻れってっ」"

[[dialogue]]
speaker = "ユウリ"
# 「……はぁ？　ナンパなんかあたしがされるわけねえだろうが。アホな心配してんじゃねえ」
line = "「……はぁ？　ナンパなんかあたしがされるわけねえだろうが。アホな心配してんじゃねえ」"

[[dialogue]]
speaker = "ユウリ"
# 「万が一、変な客に絡まれても外までぶっ飛ばしてやるよ。だから会長さんも自分に集中しろって」
line = "「万が一、変な客に絡まれても外までぶっ飛ばしてやるよ。だから会長さんも自分に集中しろって」"

[[dialogue]]
speaker = "ユウリ"
# 「ようやく行ったか……。ったく過保護にも程があんぜ……」
line = "「ようやく行ったか……。ったく過保護にも程があんぜ……」"

[[dialogue]]
speaker = "ユウリ"
# 「あいつはあたしを女の子として見過ぎなんだよ。……それ自体は、まぁ嬉しいけど……」
line = "「あいつはあたしを女の子として見過ぎなんだよ。……それ自体は、まぁ嬉しいけど……」"

[[dialogue]]
speaker = "ユウリ"
# 「でもあたしに限ってナンパなんざ。心配する方向がズレにズレて──」
line = "「でもあたしに限ってナンパなんざ。心配する方向がズレにズレて──」"

[[dialogue]]
speaker = "ユウリ"
# 「あっ、いらっしゃいませお客様方。当カジノは初めてですか？　でしたら──……」
line = "「あっ、いらっしゃいませお客様方。当カジノは初めてですか？　でしたら──……」"

[[dialogue]]
speaker = "ユウリ"
# （な、なんだ、この男たち。全員酒臭え……。泥酔してカジノになんざ来るんじゃねえっての……！）
line = "（な、なんだ、この男たち。全員酒臭え……。泥酔してカジノになんざ来るんじゃねえっての……！）"

[[dialogue]]
speaker = "ユウリ"
# （つかやたら近えし、視線もギラギラしてるし……！　ひ、人のことジロジロ見やがって……！）
line = "（つかやたら近えし、視線もギラギラしてるし……！　ひ、人のことジロジロ見やがって……！）"

[[dialogue]]
speaker = "ユウリ"
# 「え？　可愛い？　色っぽい？　あ、あはは、ありがとうござい、ます……」
line = "「え？　可愛い？　色っぽい？　あ、あはは、ありがとうござい、ます……」"

[[dialogue]]
speaker = "ユウリ"
# （あんたらに可愛いっつわれても一つも嬉しくねえっての……！　鳥肌立つわ……！）
line = "（あんたらに可愛いっつわれても一つも嬉しくねえっての……！　鳥肌立つわ……！）"

[[dialogue]]
speaker = "ユウリ"
# （つ、つか地味にヤバくないか？　どんどん壁際に追いやられてってるような……）
line = "（つ、つか地味にヤバくないか？　どんどん壁際に追いやられてってるような……）"

[[dialogue]]
speaker = "ユウリ"
# （まさかあたし……変なナンパ野郎に絡まれてるっ？　あぶなっ、触ってこようとしやがったっ……！）
line = "（まさかあたし……変なナンパ野郎に絡まれてるっ？　あぶなっ、触ってこようとしやがったっ……！）"

[[dialogue]]
speaker = "ユウリ"
# 「あ、あの……やめ……」
line = "「あ、あの……やめ……」"

[[dialogue]]
speaker = "ユウリ"
# （あれっ？　声が、声が出ねえ……！？　男たちに囲まれて、か、体が震えちまって……！　う、動きも……！）
line = "（あれっ？　声が、声が出ねえ……！？　男たちに囲まれて、か、体が震えちまって……！　う、動きも……！）"

[[dialogue]]
speaker = "ユウリ"
# （ヤバい、怖い……！　大人の男に囲まれるのってこんなに……！　誰か助けを……！　でも声が──……！）
line = "（ヤバい、怖い……！　大人の男に囲まれるのってこんなに……！　誰か助けを……！　でも声が──……！）"

[[dialogue]]
speaker = "unk"
# お客様──用件なら私が伺いますよ
line = "お客様──用件なら私が伺いますよ"

[[dialogue]]
speaker = "ユウリ"
# 「か、会長さん……！　あっ、客たちが……」
line = "「か、会長さん……！　あっ、客たちが……」"

[[dialogue]]
speaker = "unk"
# 遅くなってごめんなユウリ
line = "遅くなってごめんなユウリ"

[[dialogue]]
speaker = "ユウリ"
# 「っっ、ううん……！　ありがと、助けてくれて……！　あんな啖呵切っておいてあたし、いざとなったらビビっちまって……！」
line = "「っっ、ううん……！　ありがと、助けてくれて……！　あんな啖呵切っておいてあたし、いざとなったらビビっちまって……！」"

[[dialogue]]
speaker = "ユウリ"
# 「会長さんが来てくれなかったらどうなってたか……。本当に、ありがと……」
line = "「会長さんが来てくれなかったらどうなってたか……。本当に、ありがと……」"

[[dialogue]]
speaker = "ユウリ"
# 「あたし、自分が思ってる以上に女の子だったんだな……。あ、あはは、安心したら腰抜けちまって……」
line = "「あたし、自分が思ってる以上に女の子だったんだな……。あ、あはは、安心したら腰抜けちまって……」"

[[dialogue]]
speaker = "ユウリ"
# 「もうしばらく抱き締めてもらってていいか……？　あたしの体、ぎゅっとしてて欲しい……」
line = "「もうしばらく抱き締めてもらってていいか……？　あたしの体、ぎゅっとしてて欲しい……」"

[[dialogue]]
speaker = "ユウリ"
# 「ありがと……ん、ちゅっ<emoji=heart04>　大好き……<emoji=heart04>　頼りになる彼氏がいてくれて、あたしは幸せだ……<emoji=heart04>」
line = "「ありがと……ん、ちゅっ<emoji=heart04>　大好き……<emoji=heart04>　頼りになる彼氏がいてくれて、あたしは幸せだ……<emoji=heart04>」"

[[dialogue]]
speaker = "ユウリ"
# 「失敗した失敗した失敗した！！　フロアのど真ん中でキスしちまうなんて……！！」
line = "「失敗した失敗した失敗した！！　フロアのど真ん中でキスしちまうなんて……！！」"

[[dialogue]]
speaker = "ユウリ"
# 「もう二度とあそこでバイトできねえ……！　客からもスタッフさんからも超<ruby=はや>囃</ruby>し立てられるようになっちまったし……！」
line = "「もう二度とあそこでバイトできねえ……！　客からもスタッフさんからも超<ruby>囃<rt>はや</rt></ruby>し立てられるようになっちまったし……！」"

[[dialogue]]
speaker = "unk"
# そもそもどうして金欠だったんだ？
line = "そもそもどうして金欠だったんだ？"

[[dialogue]]
speaker = "ユウリ"
# 「えっ！？　だ、だから、それは、その……」
line = "「えっ！？　だ、だから、それは、その……」"

[[dialogue]]
speaker = "ユウリ"
# 「ふ、服買ったからだよ……。この前見に行ったフリフリの女の子っぽい服、けっこう高くて。サプライズで着てやろうと思って……」
line = "「ふ、服買ったからだよ……。この前見に行ったフリフリの女の子っぽい服、けっこう高くて。サプライズで着てやろうと思って……」"

[[dialogue]]
speaker = "ユウリ"
# 「あれ着たらもっとあたしのこと好きになってくれるっつってたから……。あたしも着てみたいって思ってたし……」
line = "「あれ着たらもっとあたしのこと好きになってくれるっつってたから……。あたしも着てみたいって思ってたし……」"

[[dialogue]]
speaker = "ユウリ"
# 「ちゃ、ちゃんと感想聞かせてもらうからなっ？　似合ってないなら似合ってないってハッキリ言えよっ……！？」
line = "「ちゃ、ちゃんと感想聞かせてもらうからなっ？　似合ってないなら似合ってないってハッキリ言えよっ……！？」"

[[dialogue]]
speaker = "ユウリ"
# 「財布空っぽになるまで色々買っちまったんだ……。一晩中ファッションショーできるくらいたくさんあるからよ……」
line = "「財布空っぽになるまで色々買っちまったんだ……。一晩中ファッションショーできるくらいたくさんあるからよ……」"

[[dialogue]]
speaker = "ユウリ"
# 「あたしの女の子らしい姿……今夜はトコトン見てもらうからな？」
line = "「あたしの女の子らしい姿……今夜はトコトン見てもらうからな？」"
