[[dialogue]]
speaker = "unk"
# 第３話,ラティエの苦手なもの,P
line = "第３話,ラティエの苦手なもの,P"

[[dialogue]]
speaker = "unk"
# ヴィーナスと２人、新星学園の星徒会室で仕事をする──珍しいこともあるものだ。
line = "ヴィーナスと２人、新星学園の星徒会室で仕事をする──珍しいこともあるものだ。"

[[dialogue]]
speaker = "unk"
# そして珍しいことは、立て続けに起こるものであるらしい。
line = "そして珍しいことは、立て続けに起こるものであるらしい。"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロトー、ちょっといいかしら。ここの書類って──」
line = "「クロトー、ちょっといいかしら。ここの書類って──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「きゃーっ！？　なになに、なんなのっ！」
line = "「きゃーっ！？　なになに、なんなのっ！」"

[[dialogue]]
speaker = "ラティエ"
# 「夜分失礼、少し邪魔をするぞ──むっ、九浄の娘もいたのか。息災だったか？」
line = "「夜分失礼、少し邪魔をするぞ──むっ、九浄の娘もいたのか。息災だったか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そりゃ元気よ、元気だけど！　ノックもなしに隣の学園の学園長が飛び込んでくるって……！」
line = "「そりゃ元気よ、元気だけど！　ノックもなしに隣の学園の学園長が飛び込んでくるって……！」"

[[dialogue]]
speaker = "ラティエ"
# 「すまない。少々、困ったことになっている。説明する時間が惜しい」
line = "「すまない。少々、困ったことになっている。説明する時間が惜しい」"

[[dialogue]]
speaker = "ラティエ"
# 「きみ、すまんが私はここには来ていない。何も見なかったと言ってくれ。いいね？」
line = "「きみ、すまんが私はここには来ていない。何も見なかったと言ってくれ。いいね？」"

[[dialogue]]
speaker = "unk"
# え、ちょっと……ラティエさん！？
line = "え、ちょっと……ラティエさん！？"

[[dialogue]]
speaker = "ラティエ"
# 「隠れるのはここでいいか。よし……では後は頼んだぞ」
line = "「隠れるのはここでいいか。よし……では後は頼んだぞ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なっ、何なのよ、いったい……！？」
line = "「なっ、何なのよ、いったい……！？」"

[[dialogue]]
speaker = "エスメラルダ"
# 「失礼しま～す。夜遅くにごめんなさいね、会長さんにヴィーナスさん」
line = "「失礼しま～す。夜遅くにごめんなさいね、会長さんにヴィーナスさん」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あら。確か流星学園の……」
line = "「あら。確か流星学園の……」"

[[dialogue]]
speaker = "エスメラルダ"
# 「分析官のエスメラルダよ。ところでなんだけど、ラティエ学園長を見なかったかしら？」
line = "「分析官のエスメラルダよ。ところでなんだけど、ラティエ学園長を見なかったかしら？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「えっと……み、見ていないけれど。どうかしたの？」
line = "「えっと……み、見ていないけれど。どうかしたの？」"

[[dialogue]]
speaker = "エスメラルダ"
# 「困ってるのよ～。星力のデータ分析、まだ終わっていないのに逃げ出されちゃったの……！」
line = "「困ってるのよ～。星力のデータ分析、まだ終わっていないのに逃げ出されちゃったの……！」"

[[dialogue]]
speaker = "エスメラルダ"
# 「学園長って放浪癖があるでしょう？　前もこうやって実験の途中に逃げ出されちゃって……」
line = "「学園長って放浪癖があるでしょう？　前もこうやって実験の途中に逃げ出されちゃって……」"

[[dialogue]]
speaker = "エスメラルダ"
# 「今日は朝まで付き合ってもらおうと思ってたのに。どこ行っちゃったのかしら」
line = "「今日は朝まで付き合ってもらおうと思ってたのに。どこ行っちゃったのかしら」"

[[dialogue]]
speaker = "エスメラルダ"
# 「こっそり付けてた発信機も外されちゃうし。新星学園の廊下に落ちてたから、とりあえず色々見て回っているのだけど」
line = "「こっそり付けてた発信機も外されちゃうし。新星学園の廊下に落ちてたから、とりあえず色々見て回っているのだけど」"

[[dialogue]]
speaker = "ヴィーナス"
# （な、なるほど。この人から逃げていたのね。だったら……）
line = "（な、なるほど。この人から逃げていたのね。だったら……）"

[[dialogue]]
speaker = "ヴィーナス"
# 「あ──窓の外に、怪しい人影がー！」
line = "「あ──窓の外に、怪しい人影がー！」"

[[dialogue]]
speaker = "エスメラルダ"
# 「本当に！？　どのあたりかしら、ヴィーナスさんっ」
line = "「本当に！？　どのあたりかしら、ヴィーナスさんっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっちに向かっていったわ！　ついてきなさい！」
line = "「あっちに向かっていったわ！　ついてきなさい！」"

[[dialogue]]
speaker = "ラティエ"
# 「ふぅ……いや、きみ。世話をかけたね。九浄の娘にも借りを作ってしまった。礼を言っておかないといけないな、これは」
line = "「ふぅ……いや、きみ。世話をかけたね。九浄の娘にも借りを作ってしまった。礼を言っておかないといけないな、これは」"

[[dialogue]]
speaker = "unk"
# どうして追われていたんですか？
line = "どうして追われていたんですか？"

[[dialogue]]
speaker = "ラティエ"
# 「なに、簡単なことだよ。エスメラルダ女史はとても仕事熱心な分析官というだけの話さ」
line = "「なに、簡単なことだよ。エスメラルダ女史はとても仕事熱心な分析官というだけの話さ」"

[[dialogue]]
speaker = "ラティエ"
# 「きみも星騎士ならば知っているだろう？　星力は、きみたちのような若い年頃の者がピークだ」
line = "「きみも星騎士ならば知っているだろう？　星力は、きみたちのような若い年頃の者がピークだ」"

[[dialogue]]
speaker = "ラティエ"
# 「加齢と共に星力は次第に衰えていく。それがこの世の決まり事。どの教科書にだってそう書いてある──が」
line = "「加齢と共に星力は次第に衰えていく。それがこの世の決まり事。どの教科書にだってそう書いてある──が」"

[[dialogue]]
speaker = "ラティエ"
# 「私の星力はなぜかその決まりから外れていてね。この歳になっても未だ、出力は増大の傾向を保っている」
line = "「私の星力はなぜかその決まりから外れていてね。この歳になっても未だ、出力は増大の傾向を保っている」"

[[dialogue]]
speaker = "ラティエ"
# 「まぁ、修行の成果だという以外に私には説明できんのだが。エスメラルダ女史はそれを科学で証明しようとしているんだよ」
line = "「まぁ、修行の成果だという以外に私には説明できんのだが。エスメラルダ女史はそれを科学で証明しようとしているんだよ」"

[[dialogue]]
speaker = "ラティエ"
# 「もしも皆が私のように、星力を伸ばし続けることができれば。これ以上ないリクリエ対策と言えるじゃないか」
line = "「もしも皆が私のように、星力を伸ばし続けることができれば。これ以上ないリクリエ対策と言えるじゃないか」"

[[dialogue]]
speaker = "ラティエ"
# 「それに生徒たちを矢面に立たせる必要もなくなるからね。彼女の気持ちは痛いほどわかる」
line = "「それに生徒たちを矢面に立たせる必要もなくなるからね。彼女の気持ちは痛いほどわかる」"

[[dialogue]]
speaker = "unk"
# じゃあ、なんで逃げるんです？
line = "じゃあ、なんで逃げるんです？"

[[dialogue]]
speaker = "ラティエ"
# 「それもまた簡単な話……終わらないんだよ、女史の分析は」
line = "「それもまた簡単な話……終わらないんだよ、女史の分析は」"

[[dialogue]]
speaker = "ラティエ"
# 「きみ、想像してみるといい。１０時間も２０時間もトレーニングルームで星力測定を行うさまを」
line = "「きみ、想像してみるといい。１０時間も２０時間もトレーニングルームで星力測定を行うさまを」"

[[dialogue]]
speaker = "ラティエ"
# 「コードのつながったヘルメットを始終かぶせられ、ひたすら湧き出てくるモンスターを星力でなぎ倒すんだ……」
line = "「コードのつながったヘルメットを始終かぶせられ、ひたすら湧き出てくるモンスターを星力でなぎ倒すんだ……」"

[[dialogue]]
speaker = "ラティエ"
# 「トレーニング室のモンスターは私にとって雑魚に等しい。延々と虚空に向かって素振りしているようなものだ……あれは疲れる。とても」
line = "「トレーニング室のモンスターは私にとって雑魚に等しい。延々と虚空に向かって素振りしているようなものだ……あれは疲れる。とても」"

[[dialogue]]
speaker = "ラティエ"
# 「で、私の顔に疲れが見えたら女史は何を言うと思う？　休憩しよう、ではない。『眠くなってきました？　ぁ、コーヒーいります？』だ」
line = "「で、私の顔に疲れが見えたら女史は何を言うと思う？　休憩しよう、ではない。『眠くなってきました？　ぁ、コーヒーいります？』だ」"

[[dialogue]]
speaker = "ラティエ"
# 「一杯のコーヒーを飲んだのち、また１０時間の計測が始まる。あれは地獄だ。魔界の『魔獣大行進』に巻き込まれた方が気が楽だよ、私は」
line = "「一杯のコーヒーを飲んだのち、また１０時間の計測が始まる。あれは地獄だ。魔界の『魔獣大行進』に巻き込まれた方が気が楽だよ、私は」"

[[dialogue]]
speaker = "ラティエ"
# 「女史は優しく真面目な教師なのだがね、ちょっとこう、視野が狭くなる時があるんだ。興味深い実験対象がいる時などは特にね」
line = "「女史は優しく真面目な教師なのだがね、ちょっとこう、視野が狭くなる時があるんだ。興味深い実験対象がいる時などは特にね」"

[[dialogue]]
speaker = "ラティエ"
# 「そもそも私自身、己の体質をセルフチェックしたレポートは上げているんだぞ？　体質の特異さは理解しているからね」
line = "「そもそも私自身、己の体質をセルフチェックしたレポートは上げているんだぞ？　体質の特異さは理解しているからね」"

[[dialogue]]
speaker = "ラティエ"
# 「だが女史には関係ないんだ。彼女なりに取りたいデータがたくさんあるのだろう……」
line = "「だが女史には関係ないんだ。彼女なりに取りたいデータがたくさんあるのだろう……」"

[[dialogue]]
speaker = "ラティエ"
# 「はぁ……帰国していたことは内緒にしていたのだが。どこで漏れてしまった？　もはや流星市国は安寧の地ではなくなってしまった」
line = "「はぁ……帰国していたことは内緒にしていたのだが。どこで漏れてしまった？　もはや流星市国は安寧の地ではなくなってしまった」"

[[dialogue]]
speaker = "ラティエ"
# 「……仕方ない。ちょっとした旅に出るか」
line = "「……仕方ない。ちょっとした旅に出るか」"

[[dialogue]]
speaker = "unk"
# 唐突ですね！？
line = "唐突ですね！？"

[[dialogue]]
speaker = "ラティエ"
# 「エスメラルダ女史から逃げるには、彼女以上の奔放さを発揮するより他にない。現に、私の自宅も学園長室もすでに見張られている」
line = "「エスメラルダ女史から逃げるには、彼女以上の奔放さを発揮するより他にない。現に、私の自宅も学園長室もすでに見張られている」"

[[dialogue]]
speaker = "ラティエ"
# 「……うむ、どこに行くか。歯ごたえのない敵ばかりで退屈していたからな、思いきり体を動かせるところがいいな」
line = "「……うむ、どこに行くか。歯ごたえのない敵ばかりで退屈していたからな、思いきり体を動かせるところがいいな」"

[[dialogue]]
speaker = "ラティエ"
# 「そうだ。レゾフできみと会った時、修行をしようとしていたね。今日の礼と言っては何だが、私が稽古をつけてやろうか？」
line = "「そうだ。レゾフできみと会った時、修行をしようとしていたね。今日の礼と言っては何だが、私が稽古をつけてやろうか？」"

[[dialogue]]
speaker = "unk"
# ……と、そんなことがあり。
line = "……と、そんなことがあり。"

[[dialogue]]
speaker = "unk"
# 仕事終わりの俺は、そのままラティエさんに連れられ、流星市国から出かけることになるのだった。
line = "仕事終わりの俺は、そのままラティエさんに連れられ、流星市国から出かけることになるのだった。"
