[[dialogue]]
speaker = "unk"
# 第１話,妹（？）との再会,P
line = "第１話,妹（？）との再会,P"

[[dialogue]]
speaker = "シアン"
# 「休日だってのに、わざわざ捜査に付き合ってもらって悪いな、会長さん。コラプサー相手だと、あたしだけじゃ心許なくてな」
line = "「休日だってのに、わざわざ捜査に付き合ってもらって悪いな、会長さん。コラプサー相手だと、あたしだけじゃ心許なくてな」"

[[dialogue]]
speaker = "シアン"
# 「だけど会長さん、ヴァレリーは捕まえるとして、リーナはどうするつもりだ？　前の戦いじゃ助けられたが、所属としては敵だ」
line = "「だけど会長さん、ヴァレリーは捕まえるとして、リーナはどうするつもりだ？　前の戦いじゃ助けられたが、所属としては敵だ」"

[[dialogue]]
speaker = "シアン"
# 「……てか、あんたはお兄ちゃんのままでいいのかよ？」
line = "「……てか、あんたはお兄ちゃんのままでいいのかよ？」"

[[dialogue]]
speaker = "unk"
# どうすればいいんでしょうか……
line = "どうすればいいんでしょうか……"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃん……」
line = "「お兄ちゃん……」"

[[dialogue]]
speaker = "シアン"
# 「──！？」
line = "「──！？」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃん、久しぶり♪　会いたかったよっ♪」
line = "「お兄ちゃん、久しぶり♪　会いたかったよっ♪」"

[[dialogue]]
speaker = "シアン"
# 「噂をすれば、ってやつか……寒気で毛が逆立ったぜ」
line = "「噂をすれば、ってやつか……寒気で毛が逆立ったぜ」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃん、一緒に遊ぼう！　遊園地も水族館も行きたいし～……あ、この間は途中だったし、またお洋服見に行くのもいいな～」
line = "「お兄ちゃん、一緒に遊ぼう！　遊園地も水族館も行きたいし～……あ、この間は途中だったし、またお洋服見に行くのもいいな～」"

[[dialogue]]
speaker = "シアン"
# 「遊ぼうって、お前コラプサーだろ？　敵じゃねえか」
line = "「遊ぼうって、お前コラプサーだろ？　敵じゃねえか」"

[[dialogue]]
speaker = "リーナ"
# 「リーナはお兄ちゃんに聞いてるの。お姉ちゃんには聞いてないから」
line = "「リーナはお兄ちゃんに聞いてるの。お姉ちゃんには聞いてないから」"

[[dialogue]]
speaker = "unk"
# リーナ、そんな言い方したらダメだよ
line = "リーナ、そんな言い方したらダメだよ"

[[dialogue]]
speaker = "リーナ"
# 「は～い。ごめんなさい、お姉ちゃん」
line = "「は～い。ごめんなさい、お姉ちゃん」"

[[dialogue]]
speaker = "シアン"
# 「すっかり兄貴面じゃねえか！？」
line = "「すっかり兄貴面じゃねえか！？」"

[[dialogue]]
speaker = "シアン"
# （どうする？　戦うか）
line = "（どうする？　戦うか）"

[[dialogue]]
speaker = "シアン"
# （……いや、そうだな、やめとこう。リーナの力は未知数だし、場所も場所だしな）
line = "（……いや、そうだな、やめとこう。リーナの力は未知数だし、場所も場所だしな）"

[[dialogue]]
speaker = "リーナ"
# 「動物園も行きたいな～。お兄ちゃんはどこがいい？」
line = "「動物園も行きたいな～。お兄ちゃんはどこがいい？」"

[[dialogue]]
speaker = "unk"
# リーナの本当のお兄ちゃんはどこに──
line = "リーナの本当のお兄ちゃんはどこに──"

[[dialogue]]
speaker = "リーナ"
# 「どうしてそんなこと言うの？　リーナのお兄ちゃんは、ここにいるお兄ちゃんだけだよ？」
line = "「どうしてそんなこと言うの？　リーナのお兄ちゃんは、ここにいるお兄ちゃんだけだよ？」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃん、リーナのこと嫌いなの……？　リーナ、いらない子なの……？」
line = "「お兄ちゃん、リーナのこと嫌いなの……？　リーナ、いらない子なの……？」"

[[dialogue]]
speaker = "リーナ"
# 「そんなことない……？　よかった～！　お兄ちゃんに嫌いって言われたら、リーナ、悲しくて死んじゃうもんっ」
line = "「そんなことない……？　よかった～！　お兄ちゃんに嫌いって言われたら、リーナ、悲しくて死んじゃうもんっ」"

[[dialogue]]
speaker = "シアン"
# （やめとけ。話が通じる相手じゃねえ。適当に合わせとけ）
line = "（やめとけ。話が通じる相手じゃねえ。適当に合わせとけ）"

[[dialogue]]
speaker = "リーナ"
# 「リーナはお兄ちゃんのこと大好きだもん。だからお兄ちゃんもリーナのこと大好きだよね？」
line = "「リーナはお兄ちゃんのこと大好きだもん。だからお兄ちゃんもリーナのこと大好きだよね？」"

[[dialogue]]
speaker = "リーナ"
# 「……ね？」
line = "「……ね？」"

[[dialogue]]
speaker = "unk"
# う、うん……
line = "う、うん……"

[[dialogue]]
speaker = "リーナ"
# 「えへへ♪　大好きって言ってもらっちゃった～♪」
line = "「えへへ♪　大好きって言ってもらっちゃった～♪」"

[[dialogue]]
speaker = "リーナ"
# 「じゃあ行こっ。お兄ちゃんと一緒ならどこでもいいからっ」
line = "「じゃあ行こっ。お兄ちゃんと一緒ならどこでもいいからっ」"

[[dialogue]]
speaker = "リーナ"
# 「ふんふんふふ～ん♪　お兄ちゃんとお出かけ～♪　お兄ちゃんと一緒～♪」
line = "「ふんふんふふ～ん♪　お兄ちゃんとお出かけ～♪　お兄ちゃんと一緒～♪」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃん、これからどこ行くの？　……美味しいケーキ屋さん？　やったぁっ！」
line = "「お兄ちゃん、これからどこ行くの？　……美味しいケーキ屋さん？　やったぁっ！」"

[[dialogue]]
speaker = "リーナ"
# 「リーナね、生クリーム好きなの♪　甘くて、口の中でとろけて、幸せな気持ちになれちゃうんだぁ～♪」
line = "「リーナね、生クリーム好きなの♪　甘くて、口の中でとろけて、幸せな気持ちになれちゃうんだぁ～♪」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃんはどんなケーキが好き？　リーナは苺のショートケーキ♪」
line = "「お兄ちゃんはどんなケーキが好き？　リーナは苺のショートケーキ♪」"

[[dialogue]]
speaker = "リーナ"
# 「……え、和菓子が好き？　も～、ケーキって言ってるでしょっ。お兄ちゃんってば、お話聞いてないんだから～っ」
line = "「……え、和菓子が好き？　も～、ケーキって言ってるでしょっ。お兄ちゃんってば、お話聞いてないんだから～っ」"

[[dialogue]]
speaker = "リーナ"
# 「あ、でも向こうに和菓子屋さんがあるっ。ケーキ屋さんの後で行こうよ。お兄ちゃんが好きなもの、リーナも好きになりたいな」
line = "「あ、でも向こうに和菓子屋さんがあるっ。ケーキ屋さんの後で行こうよ。お兄ちゃんが好きなもの、リーナも好きになりたいな」"

[[dialogue]]
speaker = "シアン"
# （一応ついてきたが……特に何も起きねえな。それならそれでいいが）
line = "（一応ついてきたが……特に何も起きねえな。それならそれでいいが）"

[[dialogue]]
speaker = "リーナ"
# 「ねぇ、お兄ちゃん」
line = "「ねぇ、お兄ちゃん」"

[[dialogue]]
speaker = "リーナ"
# 「ぎゅ～っ<emoji=heart04>」
line = "「ぎゅ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "リーナ"
# 「何でもないっ。お兄ちゃんにぎゅ～ってしたかっただけ<emoji=heart04>　えへへ<emoji=heart04>」
line = "「何でもないっ。お兄ちゃんにぎゅ～ってしたかっただけ<emoji=heart04>　えへへ<emoji=heart04>」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃん大好き……ふふ……」
line = "「お兄ちゃん大好き……ふふ……」"

[[dialogue]]
speaker = "シアン"
# （大好きって言ってる割に殺気がヤバいんだが……本当に大丈夫か？）
line = "（大好きって言ってる割に殺気がヤバいんだが……本当に大丈夫か？）"

[[dialogue]]
speaker = "リーナ"
# 「ケーキも和菓子も美味しかった！　連れていってくれてありがとう、お兄ちゃん♪」
line = "「ケーキも和菓子も美味しかった！　連れていってくれてありがとう、お兄ちゃん♪」"

[[dialogue]]
speaker = "シアン"
# （リーナを利用してコラプサーの情報を聞き出すか？　……って、そんなに嫌そうな顔すんなよ。わかったわかった、そういうズルはやんないって）
line = "（リーナを利用してコラプサーの情報を聞き出すか？　……って、そんなに嫌そうな顔すんなよ。わかったわかった、そういうズルはやんないって）"

[[dialogue]]
speaker = "シアン"
# （ま、上からはリーナをどうこうしろって命令は受けてねえし、下手に刺激しても怖いからな）
line = "（ま、上からはリーナをどうこうしろって命令は受けてねえし、下手に刺激しても怖いからな）"

[[dialogue]]
speaker = "リーナ"
# 「次は～……あ、そろそろ帰らないとキサナお姉ちゃんに怒られちゃうかも」
line = "「次は～……あ、そろそろ帰らないとキサナお姉ちゃんに怒られちゃうかも」"

[[dialogue]]
speaker = "リーナ"
# 「でもお兄ちゃんとサヨナラするのは寂しいし……」
line = "「でもお兄ちゃんとサヨナラするのは寂しいし……」"

[[dialogue]]
speaker = "unk"
# また会えるから大丈夫
line = "また会えるから大丈夫"

[[dialogue]]
speaker = "リーナ"
# 「うん！　お兄ちゃんはリーナのお兄ちゃんだもんねっ！」
line = "「うん！　お兄ちゃんはリーナのお兄ちゃんだもんねっ！」"

[[dialogue]]
speaker = "リーナ"
# 「絶対に離さないからね……お兄ちゃん」
line = "「絶対に離さないからね……お兄ちゃん」"

[[dialogue]]
speaker = "unk"
# え──？
line = "え──？"

[[dialogue]]
speaker = "リーナ"
# 「またねー、お兄ちゃん！」
line = "「またねー、お兄ちゃん！」"

[[dialogue]]
speaker = "シアン"
# 「結局戦わずじまいか。ま、平和なのはいいことだが」
line = "「結局戦わずじまいか。ま、平和なのはいいことだが」"

[[dialogue]]
speaker = "シアン"
# 「リーナについてはわからないことだらけだ。あたしもあたしでリーナのことを探ってみるよ」
line = "「リーナについてはわからないことだらけだ。あたしもあたしでリーナのことを探ってみるよ」"

[[dialogue]]
speaker = "シアン"
# 「だけどありゃ、本当に懐いてるのかね……？　何せ相手はコラプサーだ。気を付けろよ、会長さん」
line = "「だけどありゃ、本当に懐いてるのかね……？　何せ相手はコラプサーだ。気を付けろよ、会長さん」"
