[[dialogue]]
speaker = "unk"
# 第３話,マトイの家族,P
line = "第３話,マトイの家族,P"

[[dialogue]]
speaker = "unk"
# マトイとの交際は順調に進んでいたが、ある日のこと──
line = "マトイとの交際は順調に進んでいたが、ある日のこと──"

[[dialogue]]
speaker = "マトイ"
# 「会長。あのさ、今週末、一緒に遊ぶ予定だったじゃない？　それでなんだけど――」
line = "「会長。あのさ、今週末、一緒に遊ぶ予定だったじゃない？　それでなんだけど――」"

[[dialogue]]
speaker = "マトイ"
# 「私……会長に家族を紹介したいの！」
line = "「私……会長に家族を紹介したいの！」"

[[dialogue]]
speaker = "unk"
# ファッ！？
line = "ファッ！？"

[[dialogue]]
speaker = "unk"
# そうして週末――
line = "そうして週末――"

[[dialogue]]
speaker = "マトイ"
# 「じゃあ、会長。約束通り、私の家族を紹介するね！」
line = "「じゃあ、会長。約束通り、私の家族を紹介するね！」"

[[dialogue]]
speaker = "マトイ"
# 「これが私の飼っている……ジャンガリアンハムスターの、ツツミで～す♪」
line = "「これが私の飼っている……ジャンガリアンハムスターの、ツツミで～す♪」"

[[dialogue]]
speaker = "ツツミ"
# 「キュ～♪」
line = "「キュ～♪」"

[[dialogue]]
speaker = "unk"
# ある意味、助かった……
line = "ある意味、助かった……"

[[dialogue]]
speaker = "マトイ"
# 「ん？　どうしたの会長？」
line = "「ん？　どうしたの会長？」"

[[dialogue]]
speaker = "マトイ"
# 「――私の両親や弟を紹介されるかもって、思ってた？」
line = "「――私の両親や弟を紹介されるかもって、思ってた？」"

[[dialogue]]
speaker = "マトイ"
# 「そ、それは……私も心の準備がまだ……あ、でも！」
line = "「そ、それは……私も心の準備がまだ……あ、でも！」"

[[dialogue]]
speaker = "マトイ"
# 「そのうち……必ず、ね？　会長とは長いお付き合いになるだろうし……」
line = "「そのうち……必ず、ね？　会長とは長いお付き合いになるだろうし……」"

[[dialogue]]
speaker = "unk"
# そうだな。ちゃんと挨拶したい
line = "そうだな。ちゃんと挨拶したい"

[[dialogue]]
speaker = "マトイ"
# 「えへへ……うん♪」
line = "「えへへ……うん♪」"

[[dialogue]]
speaker = "マトイ"
# 「あ、それで、会長もツツミを触ってみる？　うん、大丈夫だよ～。ジャンガリアンハムスターはおとなしい子が多いんだけど、ツツミは特別人懐っこいから」
line = "「あ、それで、会長もツツミを触ってみる？　うん、大丈夫だよ～。ジャンガリアンハムスターはおとなしい子が多いんだけど、ツツミは特別人懐っこいから」"

[[dialogue]]
speaker = "マトイ"
# 「はい、じゃあ手の平に乗せるね～。ツツミ～、会長に挨拶しましょ～」
line = "「はい、じゃあ手の平に乗せるね～。ツツミ～、会長に挨拶しましょ～」"

[[dialogue]]
speaker = "ツツミ"
# 「キュッキュッキュ～♪」
line = "「キュッキュッキュ～♪」"

[[dialogue]]
speaker = "unk"
# かわいい！
line = "かわいい！"

[[dialogue]]
speaker = "マトイ"
# 「かわいいでしょ～♪　ハムスターは昔から飼ってるんだけど、凄く癒されるんだよね～。ちなみに、ツツミは女の子なんだ～」
line = "「かわいいでしょ～♪　ハムスターは昔から飼ってるんだけど、凄く癒されるんだよね～。ちなみに、ツツミは女の子なんだ～」"

[[dialogue]]
speaker = "マトイ"
# 「……って、会長、何か凄く触り方慣れてない？　下からすくうような持ち方とか、正面からゆっくり撫でてあげる感じとか……」
line = "「……って、会長、何か凄く触り方慣れてない？　下からすくうような持ち方とか、正面からゆっくり撫でてあげる感じとか……」"

[[dialogue]]
speaker = "ツツミ"
# 「キュ～ン<emoji=heart02>」
line = "「キュ～ン<emoji=heart02>」"

[[dialogue]]
speaker = "マトイ"
# 「あぁっ！？　ツツミが機嫌いい時の鳴き声を出してる！？」
line = "「あぁっ！？　ツツミが機嫌いい時の鳴き声を出してる！？」"

[[dialogue]]
speaker = "マトイ"
# 「――えっ、ペットショップのバイト経験があるの？　会長、恐るべし……」
line = "「――えっ、ペットショップのバイト経験があるの？　会長、恐るべし……」"

[[dialogue]]
speaker = "マトイ"
# 「そ、それにしても……ツツミ、私が撫でている時より嬉しそうなんだけど……」
line = "「そ、それにしても……ツツミ、私が撫でている時より嬉しそうなんだけど……」"

[[dialogue]]
speaker = "unk"
# よしよし……ツツミ、かわいいね～♪
line = "よしよし……ツツミ、かわいいね～♪"

[[dialogue]]
speaker = "マトイ"
# 「む、むむむ……」
line = "「む、むむむ……」"

[[dialogue]]
speaker = "マトイ"
# 「ね、ねぇ、会長！　ちょっと！」
line = "「ね、ねぇ、会長！　ちょっと！」"

[[dialogue]]
speaker = "マトイ"
# 「――い、いや別に、触り方は間違って無いし、ツツミは喜んでるから、いいんだけど……」
line = "「――い、いや別に、触り方は間違って無いし、ツツミは喜んでるから、いいんだけど……」"

[[dialogue]]
speaker = "マトイ"
# 「こ、恋人の前で、他の女の子と、イチャイチャし過ぎじゃない……！？」
line = "「こ、恋人の前で、他の女の子と、イチャイチャし過ぎじゃない……！？」"

[[dialogue]]
speaker = "マトイ"
# 「――わ、笑わないでよ！　会長がツツミばっかり構ってるから……」
line = "「――わ、笑わないでよ！　会長がツツミばっかり構ってるから……」"

[[dialogue]]
speaker = "unk"
# ごめん。それじゃあ――
line = "ごめん。それじゃあ――"

[[dialogue]]
speaker = "マトイ"
# 「あっ……頭、撫でられて……ん……<emoji=heart04>」
line = "「あっ……頭、撫でられて……ん……<emoji=heart04>」"

[[dialogue]]
speaker = "マトイ"
# 「――か、かわいいって……そこまでツツミと同じように、しなくても……う、うぅん、ダメじゃないよ。照れるけど……嬉しい<emoji=heart04>」
line = "「――か、かわいいって……そこまでツツミと同じように、しなくても……う、うぅん、ダメじゃないよ。照れるけど……嬉しい<emoji=heart04>」"

[[dialogue]]
speaker = "リノ"
# 「あら～、想像以上にラブラブね～♪」
line = "「あら～、想像以上にラブラブね～♪」"

[[dialogue]]
speaker = "マトイ"
# 「きゃっ！？　りりり、リノさん！？」
line = "「きゃっ！？　りりり、リノさん！？」"

[[dialogue]]
speaker = "unk"
# 母さん、さっき出掛けたはずでは！？
line = "母さん、さっき出掛けたはずでは！？"

[[dialogue]]
speaker = "リノ"
# 「うふふっ、クロトが何やらそわそわしていたから、気になって出掛けたフリをしていたの♪」
line = "「うふふっ、クロトが何やらそわそわしていたから、気になって出掛けたフリをしていたの♪」"

[[dialogue]]
speaker = "マトイ"
# 「こ、こんにちは、リノさん。今のは……わ、私、実はその、会長とお付き合いすることになりまして……」
line = "「こ、こんにちは、リノさん。今のは……わ、私、実はその、会長とお付き合いすることになりまして……」"

[[dialogue]]
speaker = "リノ"
# 「やっぱりね～。この頃、この子の機嫌が良くて、ＤＩＳＣを見ながらニヤニヤしていたから、そんな気がしてたのよね～」
line = "「やっぱりね～。この頃、この子の機嫌が良くて、ＤＩＳＣを見ながらニヤニヤしていたから、そんな気がしてたのよね～」"

[[dialogue]]
speaker = "マトイ"
# 「ふ、ふ～ん……会長、そんなに浮かれてたんだ……♪」
line = "「ふ、ふ～ん……会長、そんなに浮かれてたんだ……♪」"

[[dialogue]]
speaker = "unk"
# ちょっ、母さん！　変なこと言わないで！
line = "ちょっ、母さん！　変なこと言わないで！"

[[dialogue]]
speaker = "リノ"
# 「ふふっ♪　マトイちゃん、息子のこと、よろしくね～。私とも仲良くしてくれると嬉しいわ♪」
line = "「ふふっ♪　マトイちゃん、息子のこと、よろしくね～。私とも仲良くしてくれると嬉しいわ♪」"

[[dialogue]]
speaker = "マトイ"
# 「は、はい！　こちらこそ、改めてよろしくお願いします、リノさん！」
line = "「は、はい！　こちらこそ、改めてよろしくお願いします、リノさん！」"

[[dialogue]]
speaker = "マトイ"
# 「会長、何か私の方が先に、家族紹介されちゃったね……えへへ♪」
line = "「会長、何か私の方が先に、家族紹介されちゃったね……えへへ♪」"

[[dialogue]]
speaker = "マトイ"
# 「これは近い内に、私も紹介しないとかも……♪」
line = "「これは近い内に、私も紹介しないとかも……♪」"

[[dialogue]]
speaker = "unk"
# こ、心の準備が……
line = "こ、心の準備が……"

[[dialogue]]
speaker = "マトイ"
# 「あはは♪　２人でどうするか、考えないとだね」
line = "「あはは♪　２人でどうするか、考えないとだね」"

[[dialogue]]
speaker = "リノ"
# 「そこは男の子として頑張らないと♪　ファイトよ！」
line = "「そこは男の子として頑張らないと♪　ファイトよ！」"

[[dialogue]]
speaker = "unk"
# マトイの家族に会う日は、そう遠くないかもしれない、と思いを馳せるのだった――
line = "マトイの家族に会う日は、そう遠くないかもしれない、と思いを馳せるのだった――"
