[[dialogue]]
speaker = "unk"
# 第３話,妄想天使とホワイトデー,P
line = "第３話,妄想天使とホワイトデー,P"

[[dialogue]]
speaker = "unk"
# その日、俺は日課の訓練へ向かう前に、イクシーと話がしたくて声をかけていた。
line = "その日、俺は日課の訓練へ向かう前に、イクシーと話がしたくて声をかけていた。"

[[dialogue]]
speaker = "イクシリオン"
# 「会長、お疲れ様です……<emoji=heart04>　それであの……話とは一体何でしょう？」
line = "「会長、お疲れ様です……<emoji=heart04>　それであの……話とは一体何でしょう？」"

[[dialogue]]
speaker = "unk"
# 校舎裏でちょっと話そう
line = "校舎裏でちょっと話そう"

[[dialogue]]
speaker = "イクシリオン"
# 「はい、わかりました――って、ええぇっ！？　こ、校舎裏ですか……？」
line = "「はい、わかりました――って、ええぇっ！？　こ、校舎裏ですか……？」"

[[dialogue]]
speaker = "イクシリオン"
# 「そ、そんな人目に付かない場所に呼び出すなんて……！　昼間でも薄暗く、声を出さなければバレない、絶好のシチュエーション……っ<emoji=heart04>」
line = "「そ、そんな人目に付かない場所に呼び出すなんて……！　昼間でも薄暗く、声を出さなければバレない、絶好のシチュエーション……っ<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「ああっ<emoji=heart04>　会長、いけませんっ<emoji=heart04>　そんないやらしいところ……！」
line = "「ああっ<emoji=heart04>　会長、いけませんっ<emoji=heart04>　そんないやらしいところ……！」"

[[dialogue]]
speaker = "イクシリオン"
# 「――ハッ！？　ちちち、違うんです会長！　今のは決して、実際にいやらしいことをしている場面を妄想したわけでは……！」
line = "「――ハッ！？　ちちち、違うんです会長！　今のは決して、実際にいやらしいことをしている場面を妄想したわけでは……！」"

[[dialogue]]
speaker = "イクシリオン"
# 「って、あうぅ……<emoji=heart04>　私、また会長の前でテンパって、はしたないことを口にしてしまいました……」
line = "「って、あうぅ……<emoji=heart04>　私、また会長の前でテンパって、はしたないことを口にしてしまいました……」"

[[dialogue]]
speaker = "unk"
# 恥ずかしそうに顔を赤く染めるイクシーに、俺は微笑みながら言う。
line = "恥ずかしそうに顔を赤く染めるイクシーに、俺は微笑みながら言う。"

[[dialogue]]
speaker = "イクシリオン"
# 「――え？　バレンタインのお返し……？　あっ、今日って……ホワイトデー……！」
line = "「――え？　バレンタインのお返し……？　あっ、今日って……ホワイトデー……！」"

[[dialogue]]
speaker = "unk"
# それから校舎裏へ移動し、俺はイクシーにお菓子を手渡した。
line = "それから校舎裏へ移動し、俺はイクシーにお菓子を手渡した。"

[[dialogue]]
speaker = "イクシリオン"
# 「あ、ありがとうございます……<emoji=heart04>　今日がホワイトデーだということ、すっかり忘れていました……」
line = "「あ、ありがとうございます……<emoji=heart04>　今日がホワイトデーだということ、すっかり忘れていました……」"

[[dialogue]]
speaker = "unk"
# 最近は一生懸命、訓練してたからな
line = "最近は一生懸命、訓練してたからな"

[[dialogue]]
speaker = "イクシリオン"
# 「はい。新しいバレンタインフォームをちゃんと使いこなせるようになりたくて……新星学園の星騎士として、誇れる自分になりたいと」
line = "「はい。新しいバレンタインフォームをちゃんと使いこなせるようになりたくて……新星学園の星騎士として、誇れる自分になりたいと」"

[[dialogue]]
speaker = "イクシリオン"
# 「あとはその……できれば会長に褒めてもらえるような、強い星騎士になれたらと……<emoji=heart04>」
line = "「あとはその……できれば会長に褒めてもらえるような、強い星騎士になれたらと……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 最近のイクシーを見て、俺、思い出したんだ
line = "最近のイクシーを見て、俺、思い出したんだ"

[[dialogue]]
speaker = "イクシリオン"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "unk"
# 俺はイクシーと初めて会った時、真面目で誰かを助けようとする優しさがあり、清楚で綺麗な子だという印象を持った。
line = "俺はイクシーと初めて会った時、真面目で誰かを助けようとする優しさがあり、清楚で綺麗な子だという印象を持った。"

[[dialogue]]
speaker = "イクシリオン"
# 「――それから何度も会って話すうちに、実は内心でよくエッチな妄想をしちゃうお茶目な一面もあるとわかって、親近感が湧いた……？」
line = "「――それから何度も会って話すうちに、実は内心でよくエッチな妄想をしちゃうお茶目な一面もあるとわかって、親近感が湧いた……？」"

[[dialogue]]
speaker = "イクシリオン"
# 「あぅ……お、お恥ずかしい限りです……」
line = "「あぅ……お、お恥ずかしい限りです……」"

[[dialogue]]
speaker = "unk"
# 反省するようにシュンとした顔をするイクシーに、俺は言った。
line = "反省するようにシュンとした顔をするイクシーに、俺は言った。"

[[dialogue]]
speaker = "unk"
# でも俺は、そんなイクシーを好きになったんだ
line = "でも俺は、そんなイクシーを好きになったんだ"

[[dialogue]]
speaker = "unk"
# ついエッチな妄想をしてしまい、それを恥ずかしがる真面目なイクシー。それが可愛くて、俺はいつしか目を離せなくなっていた。
line = "ついエッチな妄想をしてしまい、それを恥ずかしがる真面目なイクシー。それが可愛くて、俺はいつしか目を離せなくなっていた。"

[[dialogue]]
speaker = "unk"
# 俺はやっぱり、イクシーのことが好きだ
line = "俺はやっぱり、イクシーのことが好きだ"

[[dialogue]]
speaker = "イクシリオン"
# 「――真面目なところも、エッチなところも、恥ずかしがるところも、全部ひっくるめて……？」
line = "「――真面目なところも、エッチなところも、恥ずかしがるところも、全部ひっくるめて……？」"

[[dialogue]]
speaker = "unk"
# これからは俺も、イクシーからもっと好きになってもらえるよう頑張ると伝える。
line = "これからは俺も、イクシーからもっと好きになってもらえるよう頑張ると伝える。"

[[dialogue]]
speaker = "イクシリオン"
# 「――私に、何度も惚れ直してもらえるように……？」
line = "「――私に、何度も惚れ直してもらえるように……？」"

[[dialogue]]
speaker = "イクシリオン"
# 「か、会長……<emoji=heart04>」
line = "「か、会長……<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「今の会長、とてもカッコよくて……私、また惚れ直して好きになってしまいます……<emoji=heart04>」
line = "「今の会長、とてもカッコよくて……私、また惚れ直して好きになってしまいます……<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「え？　――もう１つ告白しなきゃいけないことがある……ですか？　それは一体……？」
line = "「え？　――もう１つ告白しなきゃいけないことがある……ですか？　それは一体……？」"

[[dialogue]]
speaker = "unk"
# 惚れ直してもらえるように頑張ると言っておきながら、ちょっとカッコ悪い話なんだけど……と、俺は前置きしてから告げた。
line = "惚れ直してもらえるように頑張ると言っておきながら、ちょっとカッコ悪い話なんだけど……と、俺は前置きしてから告げた。"

[[dialogue]]
speaker = "イクシリオン"
# 「――最近、私と触れ合えてないことが寂しい、ですか……？」
line = "「――最近、私と触れ合えてないことが寂しい、ですか……？」"

[[dialogue]]
speaker = "unk"
# 恋人であるイクシーとバレンタインの前辺りからずっとスキンシップできていないのは、少し……ではなく、俺も男なので、正直かなりモヤモヤしていた。
line = "恋人であるイクシーとバレンタインの前辺りからずっとスキンシップできていないのは、少し……ではなく、俺も男なので、正直かなりモヤモヤしていた。"

[[dialogue]]
speaker = "unk"
# だから俺はイクシーの目を見て、今度はちゃんと気持ちを伝える。
line = "だから俺はイクシーの目を見て、今度はちゃんと気持ちを伝える。"

[[dialogue]]
speaker = "unk"
# 俺は前みたいに、イクシーと触れ合いたい
line = "俺は前みたいに、イクシーと触れ合いたい"

[[dialogue]]
speaker = "イクシリオン"
# 「……！　そ、その……」
line = "「……！　そ、その……」"

[[dialogue]]
speaker = "イクシリオン"
# 「はい……<emoji=heart04>　すごくドキドキしちゃいますけど……私も、好きな会長には触れて欲しいです……<emoji=heart04>」
line = "「はい……<emoji=heart04>　すごくドキドキしちゃいますけど……私も、好きな会長には触れて欲しいです……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 恥ずかしそうに顔を赤く染めながら、こくりと頷くイクシーの手を、俺はそっと取って指を絡めた。
line = "恥ずかしそうに顔を赤く染めながら、こくりと頷くイクシーの手を、俺はそっと取って指を絡めた。"

[[dialogue]]
speaker = "イクシリオン"
# 「あっ……<emoji=heart04>　久しぶりの、恋人繋ぎ……<emoji=heart04>」
line = "「あっ……<emoji=heart04>　久しぶりの、恋人繋ぎ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺はゆっくりと腰に手を回し、抱き寄せる。そして――
line = "俺はゆっくりと腰に手を回し、抱き寄せる。そして――"

[[dialogue]]
speaker = "イクシリオン"
# 「会長……<emoji=heart04>　んっ……<emoji=heart04>」
line = "「会長……<emoji=heart04>　んっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 久しぶりに唇を重ね、キスをする。
line = "久しぶりに唇を重ね、キスをする。"

[[dialogue]]
speaker = "イクシリオン"
# 「んむっ……ちゅっ……<emoji=heart04>」
line = "「んむっ……ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 数秒が長く感じられるほど濃密な甘い時間。唇を離すと、彼女は熱い吐息を漏らす。
line = "数秒が長く感じられるほど濃密な甘い時間。唇を離すと、彼女は熱い吐息を漏らす。"

[[dialogue]]
speaker = "イクシリオン"
# 「んっ……はあぁっ<emoji=heart04>　久しぶりのキス、すごいです……<emoji=heart04>　甘く痺れるみたいな感覚が全身を駆け抜けて……<emoji=heart04>」
line = "「んっ……はあぁっ<emoji=heart04>　久しぶりのキス、すごいです……<emoji=heart04>　甘く痺れるみたいな感覚が全身を駆け抜けて……<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「すごく恥ずかしいのに、でも――もっとしたいです……<emoji=heart04>」
line = "「すごく恥ずかしいのに、でも――もっとしたいです……<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「んっ……ちゅっ……<emoji=heart04>　ちゅっ……<emoji=heart04>」
line = "「んっ……ちゅっ……<emoji=heart04>　ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# それから俺たちは、今日まで触れ合えなかった埋め合わせをするように、校舎裏で唇を重ね続けるのだった。
line = "それから俺たちは、今日まで触れ合えなかった埋め合わせをするように、校舎裏で唇を重ね続けるのだった。"
