[[dialogue]]
speaker = "unk"
# 第４話,膝の上のアナ,P
line = "第４話,膝の上のアナ,P"

[[dialogue]]
speaker = "アナ"
# 「行く。バーミリオンイータ……！」
line = "「行く。バーミリオンイータ……！」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら。今日のアナちゃんは絶好調ね～♪」
line = "「あらあら。今日のアナちゃんは絶好調ね～♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「さすがね、アナ！　私の記録が抜かされるかと思って冷や冷やしたわ！」
line = "「さすがね、アナ！　私の記録が抜かされるかと思って冷や冷やしたわ！」"

[[dialogue]]
speaker = "アナ"
# 「言い過ぎですし、まったく追い付いてません。それに、最近私たちが４人で作った９秒９８の記録を塗り替えたじゃないですか。８秒８６は異常です。無理」
line = "「言い過ぎですし、まったく追い付いてません。それに、最近私たちが４人で作った９秒９８の記録を塗り替えたじゃないですか。８秒８６は異常です。無理」"

[[dialogue]]
speaker = "マトイ"
# 「は、８秒台を出したの……？　同じ世界の話とは思えなくなってきた……」
line = "「は、８秒台を出したの……？　同じ世界の話とは思えなくなってきた……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だって悔しかったんだもん。いくら４人がかりだったとしても、Ｓランクの記録が塗り替えられたままは嫌だわ」
line = "「だって悔しかったんだもん。いくら４人がかりだったとしても、Ｓランクの記録が塗り替えられたままは嫌だわ」"

[[dialogue]]
speaker = "アナ"
# 「もう一生塗り替えられることはないかもしれません」
line = "「もう一生塗り替えられることはないかもしれません」"

[[dialogue]]
speaker = "unk"
# みんな、そろそろ終わりにして仕事に戻ろう
line = "みんな、そろそろ終わりにして仕事に戻ろう"

[[dialogue]]
speaker = "ヴィーナス"
# 「じゃあ私はこのままパトロールに行ってくるわ。今日は駅のほうまで出てみようかしら」
line = "「じゃあ私はこのままパトロールに行ってくるわ。今日は駅のほうまで出てみようかしら」"

[[dialogue]]
speaker = "アナ"
# 「待ってください前会長。今日は会長が買ってきてくれた和菓子があります。一緒にどうですか？」
line = "「待ってください前会長。今日は会長が買ってきてくれた和菓子があります。一緒にどうですか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それはぜひご相伴にあずかりたいわね！　わかったわ、パトロールはおやつを食べた後にしましょう！」
line = "「それはぜひご相伴にあずかりたいわね！　わかったわ、パトロールはおやつを食べた後にしましょう！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ついでだから、あの人からもらった和菓子もお屋敷から取ってくる！　みんなは先に戻ってて！」
line = "「ついでだから、あの人からもらった和菓子もお屋敷から取ってくる！　みんなは先に戻ってて！」"

[[dialogue]]
speaker = "アナ"
# 「……文字通り、棚から牡丹餅」
line = "「……文字通り、棚から牡丹餅」"

[[dialogue]]
speaker = "サーシャ"
# 「うまいわね～、座布団一枚♪」
line = "「うまいわね～、座布団一枚♪」"

[[dialogue]]
speaker = "アナ"
# 「はむっ……もぐもぐ……会長のお菓子、これは最近東京駅に移店してきたという和菓子屋さんのものですよね」
line = "「はむっ……もぐもぐ……会長のお菓子、これは最近東京駅に移店してきたという和菓子屋さんのものですよね」"

[[dialogue]]
speaker = "マトイ"
# 「よく買えたね。できたばっかりで凄い行列だって聞いたけど」
line = "「よく買えたね。できたばっかりで凄い行列だって聞いたけど」"

[[dialogue]]
speaker = "アナ"
# 「さすが、前会長の意思を継ぐ者……会長もなかなかやります」
line = "「さすが、前会長の意思を継ぐ者……会長もなかなかやります」"

[[dialogue]]
speaker = "マトイ"
# 「でも……アナはそんなにお菓子ばっかり食べて、その……太ったりしないの？」
line = "「でも……アナはそんなにお菓子ばっかり食べて、その……太ったりしないの？」"

[[dialogue]]
speaker = "アナ"
# 「しません。……しない、はずです」
line = "「しません。……しない、はずです」"

[[dialogue]]
speaker = "アナ"
# 「１日の摂取カロリー計算は完璧に行っています。そうですよね、会長？」
line = "「１日の摂取カロリー計算は完璧に行っています。そうですよね、会長？」"

[[dialogue]]
speaker = "unk"
# むしろ、もっと食べたほうがいい
line = "むしろ、もっと食べたほうがいい"

[[dialogue]]
speaker = "unk"
# アナは軽いよ。
line = "アナは軽いよ。"

[[dialogue]]
speaker = "アナ"
# 「そういうことです。和菓子を食べすぎて和菓子が食べられなくなるなんて、和菓子道を征くものとしてあるまじきこと」
line = "「そういうことです。和菓子を食べすぎて和菓子が食べられなくなるなんて、和菓子道を征くものとしてあるまじきこと」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……で、どうしてアナはクロトの膝の上に座ってるのかしら？」
line = "「……で、どうしてアナはクロトの膝の上に座ってるのかしら？」"

[[dialogue]]
speaker = "アナ"
# 「…………？」
line = "「…………？」"

[[dialogue]]
speaker = "サーシャ"
# 「随分と会長くんに心を許したのね～。お膝の上でお菓子食べちゃって。……アナちゃんを乗せるのは、お姉ちゃんである私の役目だったはずなのに～」
line = "「随分と会長くんに心を許したのね～。お膝の上でお菓子食べちゃって。……アナちゃんを乗せるのは、お姉ちゃんである私の役目だったはずなのに～」"

[[dialogue]]
speaker = "アナ"
# 「ん、んぐっ！　ご、ごほっごほっ……べ、別に心を許したとかではありません。効率的な休憩を突き詰めていった結果です」
line = "「ん、んぐっ！　ご、ごほっごほっ……べ、別に心を許したとかではありません。効率的な休憩を突き詰めていった結果です」"

[[dialogue]]
speaker = "マトイ"
# 「ごくり……もしかして、これが『ツンデレ』ってやつ……？」
line = "「ごくり……もしかして、これが『ツンデレ』ってやつ……？」"

[[dialogue]]
speaker = "アナ"
# 「いえ、クーデレというやつです」
line = "「いえ、クーデレというやつです」"

[[dialogue]]
speaker = "サーシャ"
# 「デレは否定しないのね～♪　かわいい～♪」
line = "「デレは否定しないのね～♪　かわいい～♪」"

[[dialogue]]
speaker = "アナ"
# 「……指摘されると少し恥ずかしくなってきました。降ります」
line = "「……指摘されると少し恥ずかしくなってきました。降ります」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なんだかちょっとモヤモヤするわね。私もクロトの膝に座らせてもらおうかしら……？」
line = "「なんだかちょっとモヤモヤするわね。私もクロトの膝に座らせてもらおうかしら……？」"

[[dialogue]]
speaker = "サーシャ"
# 「ヴィーナスちゃん。お姉ちゃんの膝の上が空いてるわよ～♪」
line = "「ヴィーナスちゃん。お姉ちゃんの膝の上が空いてるわよ～♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「サーシャさん……！」
line = "「サーシャさん……！」"

[[dialogue]]
speaker = "マトイ"
# 「え、えっと……この場合、私はどうすれば……？」
line = "「え、えっと……この場合、私はどうすれば……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「マトイは私の膝の上よ！　合体しましょう！」
line = "「マトイは私の膝の上よ！　合体しましょう！」"

[[dialogue]]
speaker = "マトイ"
# 「その発想はなかった！」
line = "「その発想はなかった！」"

[[dialogue]]
speaker = "アナ"
# 「しょうがない。私も合体します。しゅわっち」
line = "「しょうがない。私も合体します。しゅわっち」"

[[dialogue]]
speaker = "サーシャ"
# 「さ、さすがに重いわ～～～っ！」
line = "「さ、さすがに重いわ～～～っ！」"

[[dialogue]]
speaker = "unk"
# アナ、俺の膝の上も空いてるよ
line = "アナ、俺の膝の上も空いてるよ"

[[dialogue]]
speaker = "アナ"
# 「寂しいのなら座ってあげます。よいしょっと」
line = "「寂しいのなら座ってあげます。よいしょっと」"

[[dialogue]]
speaker = "アナ"
# 「会長の膝の上は、私のものです。今期のベストプレイス賞受賞」
line = "「会長の膝の上は、私のものです。今期のベストプレイス賞受賞」"

[[dialogue]]
speaker = "アナ"
# 「和菓子の食べ心地も、お昼寝の寝心地も最高。私がつい座ってしまうのもしょうがない」
line = "「和菓子の食べ心地も、お昼寝の寝心地も最高。私がつい座ってしまうのもしょうがない」"

[[dialogue]]
speaker = "アナ"
# 「……どうして笑ってるんですか、会長？」
line = "「……どうして笑ってるんですか、会長？」"

[[dialogue]]
speaker = "アナ"
# 「さては、私が戻ってきて嬉しくなったとか？　まあ、冗談ですが……」
line = "「さては、私が戻ってきて嬉しくなったとか？　まあ、冗談ですが……」"

[[dialogue]]
speaker = "アナ"
# 「え、本当に……？　ふ、ふーん……」
line = "「え、本当に……？　ふ、ふーん……」"

[[dialogue]]
speaker = "unk"
# 俺がからかうと、ぷいっと顔を背けてしまうアナだったが──
line = "俺がからかうと、ぷいっと顔を背けてしまうアナだったが──"

[[dialogue]]
speaker = "unk"
# その耳は赤くなっていて、そんなアナはやっぱり可愛いと思ってしまうのだった。
line = "その耳は赤くなっていて、そんなアナはやっぱり可愛いと思ってしまうのだった。"
