[[dialogue]]
speaker = "unk"
# 第２話,そうだ、海へ行こう！,P
line = "第２話,そうだ、海へ行こう！,P"

[[dialogue]]
speaker = "unk"
# 紅明からダーリン呼びされるようになり、しばらく経ったある日のこと──
line = "紅明からダーリン呼びされるようになり、しばらく経ったある日のこと──"

[[dialogue]]
speaker = "紅明"
# 「ダーリン、西に行こうぜ！！！」
line = "「ダーリン、西に行こうぜ！！！」"

[[dialogue]]
speaker = "unk"
# 唐突に何事！？
line = "唐突に何事！？"

[[dialogue]]
speaker = "紅明"
# 「ウェーイ！　かっとばすぜ～！」
line = "「ウェーイ！　かっとばすぜ～！」"

[[dialogue]]
speaker = "紅明"
# 「ダーリン、こっちこっち～！」
line = "「ダーリン、こっちこっち～！」"

[[dialogue]]
speaker = "紅明"
# 「ほら、見えた！　海だよ、海！！！　めっちゃ綺麗～！」
line = "「ほら、見えた！　海だよ、海！！！　めっちゃ綺麗～！」"

[[dialogue]]
speaker = "紅明"
# 「いや～、めっちゃ西に飛んだわ～！　海見えるくらい飛んだわ～！」
line = "「いや～、めっちゃ西に飛んだわ～！　海見えるくらい飛んだわ～！」"

[[dialogue]]
speaker = "unk"
# 何だったんだ、今の！？
line = "何だったんだ、今の！？"

[[dialogue]]
speaker = "紅明"
# 「ほら、このところ星徒会の仕事で忙しそうだったじゃん？」
line = "「ほら、このところ星徒会の仕事で忙しそうだったじゃん？」"

[[dialogue]]
speaker = "紅明"
# 「だから海でも見たら、ダーリンの溜まった疲れも吹っ飛ぶかなと思って☆」
line = "「だから海でも見たら、ダーリンの溜まった疲れも吹っ飛ぶかなと思って☆」"

[[dialogue]]
speaker = "unk"
# だからダーリンって何！？
line = "だからダーリンって何！？"

[[dialogue]]
speaker = "紅明"
# 「まあまあ、その話は置いておいて。めっちゃ飛んで、喉乾いたっしょ？」
line = "「まあまあ、その話は置いておいて。めっちゃ飛んで、喉乾いたっしょ？」"

[[dialogue]]
speaker = "紅明"
# 「はい、ホルスタミンあるから、２人で飲みましょうや」
line = "「はい、ホルスタミンあるから、２人で飲みましょうや」"

[[dialogue]]
speaker = "紅明"
# 「ちなみに飲む時は、腰に手を当てて、上を向きながらグイッと飲む、温泉上がりスタイルがオススメだぜ☆」
line = "「ちなみに飲む時は、腰に手を当てて、上を向きながらグイッと飲む、温泉上がりスタイルがオススメだぜ☆」"

[[dialogue]]
speaker = "unk"
# 紅明の実家が作ってるんだっけ……
line = "紅明の実家が作ってるんだっけ……"

[[dialogue]]
speaker = "unk"
# そういえばこれって、
line = "そういえばこれって、"

[[dialogue]]
speaker = "紅明"
# 「そうそう、牛一族で世の為人の為、『善哉乳業』って会社をやってるのよ！」
line = "「そうそう、牛一族で世の為人の為、『善哉乳業』って会社をやってるのよ！」"

[[dialogue]]
speaker = "紅明"
# 「牛一族の祖先は昔、魔界から人間界に移住して来てさ、それから乳業を営むようになったんだよね」
line = "「牛一族の祖先は昔、魔界から人間界に移住して来てさ、それから乳業を営むようになったんだよね」"

[[dialogue]]
speaker = "unk"
# 要するに紅明は人間界出身の魔族なのか
line = "要するに紅明は人間界出身の魔族なのか"

[[dialogue]]
speaker = "unk"
# 前もそんな話してたけど、
line = "前もそんな話してたけど、"

[[dialogue]]
speaker = "紅明"
# 「そういうこと！」
line = "「そういうこと！」"

[[dialogue]]
speaker = "紅明"
# 「ところで、ダーリンは『西遊記』って知ってるかな？」
line = "「ところで、ダーリンは『西遊記』って知ってるかな？」"

[[dialogue]]
speaker = "紅明"
# 「そうそう、孫悟空や三蔵法師で有名な話ね！」
line = "「そうそう、孫悟空や三蔵法師で有名な話ね！」"

[[dialogue]]
speaker = "紅明"
# 「じゃあ、『<ruby=こうがいじ>紅孩児</ruby>』っていうのは誰だか分かるかい？」
line = "「じゃあ、『<ruby>紅孩児<rt>こうがいじ</rt></ruby>』っていうのは誰だか分かるかい？」"

[[dialogue]]
speaker = "unk"
# 西遊記に登場する敵……だっけ？
line = "西遊記に登場する敵……だっけ？"

[[dialogue]]
speaker = "紅明"
# 「その通り！　西遊記のラスボス『牛魔王』の<b>娘</b>なんだけど、最初は三蔵法師一行と敵対してたんだよね」
line = "「その通り！　西遊記のラスボス『牛魔王』の<b>娘</b>なんだけど、最初は三蔵法師一行と敵対してたんだよね」"

[[dialogue]]
speaker = "紅明"
# 「でも、戦いを繰り返すうちに敗れて、改心し、それ以降は三蔵法師一行に加わったんだな！」
line = "「でも、戦いを繰り返すうちに敗れて、改心し、それ以降は三蔵法師一行に加わったんだな！」"

[[dialogue]]
speaker = "紅明"
# 「その後は父親の牛魔王を倒して、人間界に残ることを選択した。これまでやって来た悪事の贖罪の為にね」
line = "「その後は父親の牛魔王を倒して、人間界に残ることを選択した。これまでやって来た悪事の贖罪の為にね」"

[[dialogue]]
speaker = "紅明"
# 「そうして世の為人の為と始めたのが、善哉乳業の大本ってわけさ！！！」
line = "「そうして世の為人の為と始めたのが、善哉乳業の大本ってわけさ！！！」"

[[dialogue]]
speaker = "unk"
# え！？　ちょっと待って、じゃあまさか……！？
line = "え！？　ちょっと待って、じゃあまさか……！？"

[[dialogue]]
speaker = "紅明"
# 「そう、牛一族は紅孩児の血を引く子孫なのさ！　凄いっしょ？」
line = "「そう、牛一族は紅孩児の血を引く子孫なのさ！　凄いっしょ？」"

[[dialogue]]
speaker = "紅明"
# 「この話すると皆驚いてくれるから、アタシの鉄板ネタなんだぜ☆　うしし♪」
line = "「この話すると皆驚いてくれるから、アタシの鉄板ネタなんだぜ☆　うしし♪」"

[[dialogue]]
speaker = "紅明"
# 「ちなみに、２０００年前に紅孩児の掲げた『世の為人の為』ってモットーは今も一族に受け継がれてて、それはアタシ、誇らしく思ってるんだよね！」
line = "「ちなみに、２０００年前に紅孩児の掲げた『世の為人の為』ってモットーは今も一族に受け継がれてて、それはアタシ、誇らしく思ってるんだよね！」"

[[dialogue]]
speaker = "紅明"
# 「ホルスタミンを昔から変わらず作り続けて、皆に元気と笑顔を与え続けてる。それって凄いことじゃん？」
line = "「ホルスタミンを昔から変わらず作り続けて、皆に元気と笑顔を与え続けてる。それって凄いことじゃん？」"

[[dialogue]]
speaker = "unk"
# 善哉乳業、凄い会社だったんだな……
line = "善哉乳業、凄い会社だったんだな……"

[[dialogue]]
speaker = "紅明"
# 「でしょ～♪　アタシの自慢なんだぜ☆」
line = "「でしょ～♪　アタシの自慢なんだぜ☆」"

[[dialogue]]
speaker = "紅明"
# 「牛一族の秘伝で作られたこのエナジー牛乳、ホルスタミンもね！　さあさあ、ダーリン、グイッと飲んで、グイッと！」
line = "「牛一族の秘伝で作られたこのエナジー牛乳、ホルスタミンもね！　さあさあ、ダーリン、グイッと飲んで、グイッと！」"

[[dialogue]]
speaker = "unk"
# （腰に手を当てて、ホルスタミンを飲む）
line = "（腰に手を当てて、ホルスタミンを飲む）"

[[dialogue]]
speaker = "紅明"
# 「おっ、いい飲みっぷり！　どうよ、元気出て来たかい！？」
line = "「おっ、いい飲みっぷり！　どうよ、元気出て来たかい！？」"

[[dialogue]]
speaker = "紅明"
# 「──それなら良かった！　善哉善哉、これでまた仕事頑張れそうだね、うしし♪」
line = "「──それなら良かった！　善哉善哉、これでまた仕事頑張れそうだね、うしし♪」"

[[dialogue]]
speaker = "unk"
# 元気が出たのは紅明と一緒に居たからだと思う
line = "元気が出たのは紅明と一緒に居たからだと思う"

[[dialogue]]
speaker = "紅明"
# 「ん？　ホルスタミンだけじゃなくて、アタシも？」
line = "「ん？　ホルスタミンだけじゃなくて、アタシも？」"

[[dialogue]]
speaker = "紅明"
# 「んモー♪　ダーリンってば、嬉しいこと言ってくれるじゃん！」
line = "「んモー♪　ダーリンってば、嬉しいこと言ってくれるじゃん！」"

[[dialogue]]
speaker = "紅明"
# 「まあ、アタシは『見るエナジードリンク』とか『ホルスタミンの擬人化』とか言われている、スーパータレントだかんね！！！」
line = "「まあ、アタシは『見るエナジードリンク』とか『ホルスタミンの擬人化』とか言われている、スーパータレントだかんね！！！」"

[[dialogue]]
speaker = "紅明"
# 「これからもダーリンが疲れてたら、言われなくても元気にしちゃうんで、そこんところよろしく元気☆」
line = "「これからもダーリンが疲れてたら、言われなくても元気にしちゃうんで、そこんところよろしく元気☆」"

[[dialogue]]
speaker = "unk"
# 気分転換のお礼に、紅明と今度はゆっくり海へ遊びに行くのも良いかもしれない──そんな風に思うのだった。
line = "気分転換のお礼に、紅明と今度はゆっくり海へ遊びに行くのも良いかもしれない──そんな風に思うのだった。"
