[[dialogue]]
speaker = "ウズメイア"
# 「デート、すっごく楽しかった～♪　ありがとね、会長くん<emoji=heart04>」
line = "「デート、すっごく楽しかった～♪　ありがとね、会長くん<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「すっかり陽も暮れちゃったねー。この後はどうしよっか。このままバイバイしちゃう感じ？」
line = "「すっかり陽も暮れちゃったねー。この後はどうしよっか。このままバイバイしちゃう感じ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「……なーんちゃって。わかってるよん。あたし、ちゃーんと夜も予定空けてあるから♪」
line = "「……なーんちゃって。わかってるよん。あたし、ちゃーんと夜も予定空けてあるから♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「じゃあ、会長くん。いつものホテル、行っちゃおっか？<emoji=heart04>」
line = "「じゃあ、会長くん。いつものホテル、行っちゃおっか？<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「今日はちょ～っと試してみたいことがあるんだよね～。というわけで、ハイこれ、よろしく～♪」
line = "「今日はちょ～っと試してみたいことがあるんだよね～。というわけで、ハイこれ、よろしく～♪」"

[[dialogue]]
speaker = "クロト"
# 「え？　これ……本当にするのかっ？」
line = "「え？　これ……本当にするのかっ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「もっちろん！　ほら、ＤＩＳＣで調べて、縛り方もばっちりだから。この通りにぎゅぎゅ～ってやっちゃって♪」
line = "「もっちろん！　ほら、ＤＩＳＣで調べて、縛り方もばっちりだから。この通りにぎゅぎゅ～ってやっちゃって♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「じゃーんっ♪　どうかなぁ、会長くん。おち○ぽ興奮した？　興奮した～？」
line = "「じゃーんっ♪　どうかなぁ、会長くん。おち○ぽ興奮した？　興奮した～？」"

[[dialogue]]
speaker = "unk"
# ウズメの真っ白な肌に食い込む幾重もの縄。お尻の穴まで丸見えの後背位の体勢……ムラムラしないわけがないのだけど。
line = "ウズメの真っ白な肌に食い込む幾重もの縄。お尻の穴まで丸見えの後背位の体勢……ムラムラしないわけがないのだけど。"

[[dialogue]]
speaker = "クロト"
# 「言われた通りに縛ったけど、痛くないか？」
line = "「言われた通りに縛ったけど、痛くないか？」"

[[dialogue]]
speaker = "ウズメイア"
# 「ぜんぜんへーき！　あたし、体やわらかいし♪　それに会長くん、縛ってる時も優しかったじゃん？　問題ないって～<emoji=heart04>」
line = "「ぜんぜんへーき！　あたし、体やわらかいし♪　それに会長くん、縛ってる時も優しかったじゃん？　問題ないって～<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「んふふ～、これ１回やってみたかったんだよね。着物と言えば芸者。芸者と言えば緊縛エッチ！　だもんねっ♪」
line = "「んふふ～、これ１回やってみたかったんだよね。着物と言えば芸者。芸者と言えば緊縛エッチ！　だもんねっ♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「はぁあ<emoji=heart04>　……おち○ぽ、もう勃起しちゃってる。きゃぁ～♪　お代官様ぁ、お許しくださいませぇ～<emoji=heart04>」
line = "「はぁあ<emoji=heart04>　……おち○ぽ、もう勃起しちゃってる。きゃぁ～♪　お代官様ぁ、お許しくださいませぇ～<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 日本文化が好きで、また好奇心も強いウズメ。彼女は何かを見たり聞いたりするたびにすぐ体験したがる節がある。
line = "日本文化が好きで、また好奇心も強いウズメ。彼女は何かを見たり聞いたりするたびにすぐ体験したがる節がある。"

[[dialogue]]
speaker = "unk"
# 先日は４８手を試したいと言われて、月見茶臼だの絞り芙蓉だの、もはや文字だけではよくわからないプレイを散々こなしたものだった。
line = "先日は４８手を試したいと言われて、月見茶臼だの絞り芙蓉だの、もはや文字だけではよくわからないプレイを散々こなしたものだった。"

[[dialogue]]
speaker = "クロト"
# 「ウズメと付き合ってると、知らなくていい知識ばっかり増える気がするなぁ……」
line = "「ウズメと付き合ってると、知らなくていい知識ばっかり増える気がするなぁ……」"

[[dialogue]]
speaker = "ウズメイア"
# 「ふふふ、良いではないか、良いではないか～<emoji=heart04>」
line = "「ふふふ、良いではないか、良いではないか～<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「言う人が逆だろ……まったく」
line = "「言う人が逆だろ……まったく」"

[[dialogue]]
speaker = "unk"
# 目の前で揺れるウズメのお尻を掴んで、勃起したペニスをあてがって──
line = "目の前で揺れるウズメのお尻を掴んで、勃起したペニスをあてがって──"

[[dialogue]]
speaker = "ウズメイア"
# 「んっ──は、ぁぁ、あぁあ～っ<emoji=heart04>　おち○ぽ、奥まで来たぁっ……♪」
line = "「んっ──は、ぁぁ、あぁあ～っ<emoji=heart04>　おち○ぽ、奥まで来たぁっ……♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「あっ、はぁあー……すごぉ♪　いつもより太いかもー……んんっ<emoji=heart04>　ぐいぃ～って広げられて、るぅー……<emoji=heart04>」
line = "「あっ、はぁあー……すごぉ♪　いつもより太いかもー……んんっ<emoji=heart04>　ぐいぃ～って広げられて、るぅー……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「身動きできないまま……んっ<emoji=heart04>　おち○ぽ突っ込まれるの、こ、これヤバイかもっ……<emoji=heart04>」
line = "「身動きできないまま……んっ<emoji=heart04>　おち○ぽ突っ込まれるの、こ、これヤバイかもっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「ぁ、あ、ぁっ……<emoji=heart04>　動いてないのに、おち○ぽビクビクしてっ……会長くんも興奮しちゃってる？」
line = "「ぁ、あ、ぁっ……<emoji=heart04>　動いてないのに、おち○ぽビクビクしてっ……会長くんも興奮しちゃってる？」"

[[dialogue]]
speaker = "unk"
# さっきまで好きな女の子を縛ることに抵抗があったのに……何だろう、これ。ウズメを縛った縄を握りながらの挿入……
line = "さっきまで好きな女の子を縛ることに抵抗があったのに……何だろう、これ。ウズメを縛った縄を握りながらの挿入……"

[[dialogue]]
speaker = "unk"
# 男の本能に訴えかけてくるような、ふつふつとＳっ気が湧き上がってくるような──
line = "男の本能に訴えかけてくるような、ふつふつとＳっ気が湧き上がってくるような──"

[[dialogue]]
speaker = "ウズメイア"
# 「それじゃあ来てっ……おち○ぽいっぱい動かして、気持ちよくなってね<emoji=heart04>」
line = "「それじゃあ来てっ……おち○ぽいっぱい動かして、気持ちよくなってね<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「んんぁっ、あ、ぁああ、ふあぁ、あ、ぁあっ<emoji=heart04>　おち○ぽ、動いてるっ……ん、ふぅ、んんんっ<emoji=heart04>」
line = "「んんぁっ、あ、ぁああ、ふあぁ、あ、ぁあっ<emoji=heart04>　おち○ぽ、動いてるっ……ん、ふぅ、んんんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「あー、ヤバ、ヤバヤバっ<emoji=heart04>　身動きできないの、想像以上に──んっ、うぅぅっ<emoji=heart04>　すご、ぃ、かもぉっ<emoji=heart04>」
line = "「あー、ヤバ、ヤバヤバっ<emoji=heart04>　身動きできないの、想像以上に──んっ、うぅぅっ<emoji=heart04>　すご、ぃ、かもぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「おち○ぽの気持ちいいやつが、ぅあっ、逃がせないから、おま○こに響く、ぅっ──ぁ、あぁぁあ～っ<emoji=heart04>」
line = "「おち○ぽの気持ちいいやつが、ぅあっ、逃がせないから、おま○こに響く、ぅっ──ぁ、あぁぁあ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 快感にあえぐウズメの唇がつややかに濡れていて、俺はペニスを深く挿入しながら、覆いかぶさるようにしてキスをした。
line = "快感にあえぐウズメの唇がつややかに濡れていて、俺はペニスを深く挿入しながら、覆いかぶさるようにしてキスをした。"

[[dialogue]]
speaker = "ウズメイア"
# 「んぅちゅるっ、れええ、ちゅる、ちゅぅ、ちゅぱぁ<emoji=heart04>　んっふぅ、ふぅっ……会長くん、キス好きだねぇ……んふふっ<emoji=heart04>」
line = "「んぅちゅるっ、れええ、ちゅる、ちゅぅ、ちゅぱぁ<emoji=heart04>　んっふぅ、ふぅっ……会長くん、キス好きだねぇ……んふふっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ウズメだって好きなくせに、とこぼしながら夢中で舌を絡める。
line = "ウズメだって好きなくせに、とこぼしながら夢中で舌を絡める。"

[[dialogue]]
speaker = "ウズメイア"
# 「ちゅぅちゅるっ、んちゅるぅ、れぇえっ、ちゅぱ、んちゅるっ……んふぅっ<emoji=heart04>　縛られながらキスって、なんかトーサク的ぃ……♪」
line = "「ちゅぅちゅるっ、んちゅるぅ、れぇえっ、ちゅぱ、んちゅるっ……んふぅっ<emoji=heart04>　縛られながらキスって、なんかトーサク的ぃ……♪」"

[[dialogue]]
speaker = "unk"
# ＳＭプレイなのに愛情のあるキスを行う──確かにウズメの言うとおり倒錯的な気分になってくる。
line = "ＳＭプレイなのに愛情のあるキスを行う──確かにウズメの言うとおり倒錯的な気分になってくる。"

[[dialogue]]
speaker = "ウズメイア"
# 「ちゅぅちゅぱ、れろれる、んちゅる、へろれろぉ……んちゅる、ちゅぱぁっ……<emoji=heart04>」
line = "「ちゅぅちゅぱ、れろれる、んちゅる、へろれろぉ……んちゅる、ちゅぱぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「んれぇえろっ<emoji=heart04>　れろれろ、んちゅるぅ、れぇ～っ……んちゅぅ、ちゅるるっ、ちゅぱっ<emoji=heart04>　んぅ、会長くん<emoji=heart04>　ちゅぅっ<emoji=heart04>」
line = "「んれぇえろっ<emoji=heart04>　れろれろ、んちゅるぅ、れぇ～っ……んちゅぅ、ちゅるるっ、ちゅぱっ<emoji=heart04>　んぅ、会長くん<emoji=heart04>　ちゅぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「んー……会長くんとキスするの、好きだけどぉっ……せっかくの緊縛エッチだし、も～っと乱暴なの、して欲しいかも～？」
line = "「んー……会長くんとキスするの、好きだけどぉっ……せっかくの緊縛エッチだし、も～っと乱暴なの、して欲しいかも～？」"

[[dialogue]]
speaker = "クロト"
# 「……例えば？」
line = "「……例えば？」"

[[dialogue]]
speaker = "ウズメイア"
# 「そだね。縄をぐい～って、引っ張りながら突くとか？」
line = "「そだね。縄をぐい～って、引っ張りながら突くとか？」"

[[dialogue]]
speaker = "クロト"
# 「いや、でもなぁ……」
line = "「いや、でもなぁ……」"

[[dialogue]]
speaker = "ウズメイア"
# 「ぶーぶー。お代官様のくせにぃ、芸者さんのリクエストが聞けぬと申すかぁ～？」
line = "「ぶーぶー。お代官様のくせにぃ、芸者さんのリクエストが聞けぬと申すかぁ～？」"

[[dialogue]]
speaker = "unk"
# どっちの立場が上なんだよと苦笑しながら、言うとおりにすることにした。
line = "どっちの立場が上なんだよと苦笑しながら、言うとおりにすることにした。"

[[dialogue]]
speaker = "ウズメイア"
# 「んっ！？<emoji=heart04>　ぁーっあっ<emoji=heart04>　あぁぁあっ、はぁ、あぁっ<emoji=heart04>　おち○ぽ、さっきよりキくっ<emoji=heart04>　キいちゃう、ぅうぅ～っ……<emoji=heart04>」
line = "「んっ！？<emoji=heart04>　ぁーっあっ<emoji=heart04>　あぁぁあっ、はぁ、あぁっ<emoji=heart04>　おち○ぽ、さっきよりキくっ<emoji=heart04>　キいちゃう、ぅうぅ～っ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# もうこれ以上ないと思っていたのに、さらにウズメの女性器の締め付けがきつくなった……！？
line = "もうこれ以上ないと思っていたのに、さらにウズメの女性器の締め付けがきつくなった……！？"

[[dialogue]]
speaker = "ウズメイア"
# 「は、はぁああっ<emoji=heart04>　あ、あたし、これ好きかもぉっ<emoji=heart04>　会長くんの、わんちゃんになったみたい、あ、あぁ、あぁ<emoji=heart04>」
line = "「は、はぁああっ<emoji=heart04>　あ、あたし、これ好きかもぉっ<emoji=heart04>　会長くんの、わんちゃんになったみたい、あ、あぁ、あぁ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「おち○ぽすっご、また太くなったっ<emoji=heart04>　お、ぁっ<emoji=heart04>　んんぅ、ふぅうっ<emoji=heart04>　んっ、んっ、んっ、んっ、んんぅうっ<emoji=heart04>」
line = "「おち○ぽすっご、また太くなったっ<emoji=heart04>　お、ぁっ<emoji=heart04>　んんぅ、ふぅうっ<emoji=heart04>　んっ、んっ、んっ、んっ、んんぅうっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「はぁっ、はぁあっ<emoji=heart04>　会長くぅんっ<emoji=heart04>　も、もっとすごいのしてっ、普段しないようなの、して欲しいかもっ♪」
line = "「はぁっ、はぁあっ<emoji=heart04>　会長くぅんっ<emoji=heart04>　も、もっとすごいのしてっ、普段しないようなの、して欲しいかもっ♪」"

[[dialogue]]
speaker = "クロト"
# 「どんなこと、して欲しいんだっ……？」
line = "「どんなこと、して欲しいんだっ……？」"

[[dialogue]]
speaker = "ウズメイア"
# 「あ、んんっ……えっとぉ──お、お尻っ<emoji=heart04>　お尻、ぺちんって、ぶって<emoji=heart04>」
line = "「あ、んんっ……えっとぉ──お、お尻っ<emoji=heart04>　お尻、ぺちんって、ぶって<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「おち○ぽパンパンされながら、お尻ぶたれるのって、あ、あはっ<emoji=heart04>　そ、それっぽい感じ、しないっ？<emoji=heart04>」
line = "「おち○ぽパンパンされながら、お尻ぶたれるのって、あ、あはっ<emoji=heart04>　そ、それっぽい感じ、しないっ？<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ピストンするたびに波打つウズメの丸いお尻を叩く──その様を想像すると、背筋がゾクゾクと震えた。
line = "ピストンするたびに波打つウズメの丸いお尻を叩く──その様を想像すると、背筋がゾクゾクと震えた。"

[[dialogue]]
speaker = "ウズメイア"
# 「んっ──ぁ、あぁぁああっ<emoji=heart04>　んっ、ふぅうっ<emoji=heart04>」
line = "「んっ──ぁ、あぁぁああっ<emoji=heart04>　んっ、ふぅうっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「う──ぁっ！　くぅっ……叩いた瞬間、めっちゃくちゃ締まった……！」
line = "「う──ぁっ！　くぅっ……叩いた瞬間、めっちゃくちゃ締まった……！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ど、どうしよぉっ……このエッチ、まじヤバっ……ぁ、もっと、もっとしてぇっ……<emoji=heart04>」
line = "「ど、どうしよぉっ……このエッチ、まじヤバっ……ぁ、もっと、もっとしてぇっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ピストンされながらもじもじと動くウズメのお尻に、さっきよりも強く平手をする。
line = "ピストンされながらもじもじと動くウズメのお尻に、さっきよりも強く平手をする。"

[[dialogue]]
speaker = "ウズメイア"
# 「ぁぁぁぁんんっ！<emoji=heart04>　んっふぅう、んんぁっ<emoji=heart04>　会長くん、それいい、縄、ぐいってしながら、お尻いじめてぇっ<emoji=heart04>」
line = "「ぁぁぁぁんんっ！<emoji=heart04>　んっふぅう、んんぁっ<emoji=heart04>　会長くん、それいい、縄、ぐいってしながら、お尻いじめてぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「ひっ──うぅう！<emoji=heart04>　んっふぅ、んんぅ、ふぁ、ぁ、あぁっ<emoji=heart04>」
line = "「ひっ──うぅう！<emoji=heart04>　んっふぅ、んんぅ、ふぁ、ぁ、あぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ぶたれるの……好きなのかっ？　ウズメ！」
line = "「ぶたれるの……好きなのかっ？　ウズメ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ひぁぁあんん！<emoji=heart04>　う、うんっ<emoji=heart04>　これ好きっ<emoji=heart04>　好きな人にいじめられるのっ、ぁ、ぁ、あぁっ<emoji=heart04>　気持ちいいよ、ぉ、ぉっ<emoji=heart04>」
line = "「ひぁぁあんん！<emoji=heart04>　う、うんっ<emoji=heart04>　これ好きっ<emoji=heart04>　好きな人にいじめられるのっ、ぁ、ぁ、あぁっ<emoji=heart04>　気持ちいいよ、ぉ、ぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 膝から下をぱたぱた動かしながら喜びのあえぎを上げるウズメ。今までにも何度も交わってきたけれど、こんなにも反応が良いのは初めてだった。
line = "膝から下をぱたぱた動かしながら喜びのあえぎを上げるウズメ。今までにも何度も交わってきたけれど、こんなにも反応が良いのは初めてだった。"

[[dialogue]]
speaker = "unk"
# 何度もお尻を叩いているうちに、俺の中にも『ウズメをもっといじめたい』という気持ちが湧き上がってきて──
line = "何度もお尻を叩いているうちに、俺の中にも『ウズメをもっといじめたい』という気持ちが湧き上がってきて──"

[[dialogue]]
speaker = "クロト"
# 「縛られて、お尻叩かれてっ……濡らしすぎだぞ、ウズメ！」
line = "「縛られて、お尻叩かれてっ……濡らしすぎだぞ、ウズメ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「んっふあ、ぁあぁっ<emoji=heart04>　お尻叩きながら叱られるの、ダメだしっ<emoji=heart04>　頭の芯まで、びりびりって、来るぅ──ぁ、ぁああっ<emoji=heart04>」
line = "「んっふあ、ぁあぁっ<emoji=heart04>　お尻叩きながら叱られるの、ダメだしっ<emoji=heart04>　頭の芯まで、びりびりって、来るぅ──ぁ、ぁああっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「じゃあ、やめるか？　やめてもいいんだぞ！」
line = "「じゃあ、やめるか？　やめてもいいんだぞ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「あ──そ、それはぁっ……だ、だめぇー……<emoji=heart04>　もっとして、縄、ぎりぎりって引っ張って、お尻、ばちんばちん、してぇっ<emoji=heart04>」
line = "「あ──そ、それはぁっ……だ、だめぇー……<emoji=heart04>　もっとして、縄、ぎりぎりって引っ張って、お尻、ばちんばちん、してぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くんのおち○ぽでっ、も、もっと、あたしのこといじめて欲しい、よぉおっ……<emoji=heart04>」
line = "「会長くんのおち○ぽでっ、も、もっと、あたしのこといじめて欲しい、よぉおっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 瞳を潤ませて、切ない眼差しでそんなこと言われたら──
line = "瞳を潤ませて、切ない眼差しでそんなこと言われたら──"

[[dialogue]]
speaker = "クロト"
# 「──っ！！」
line = "「──っ！！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ううっぁ、ああ、ぁあぁあ～っ<emoji=heart04>　すごい、すごい速いおち○ぽ、あぁっ<emoji=heart04>　そこ好きっ、そこ好き、パンパン好きぃっ<emoji=heart04>」
line = "「ううっぁ、ああ、ぁあぁあ～っ<emoji=heart04>　すごい、すごい速いおち○ぽ、あぁっ<emoji=heart04>　そこ好きっ、そこ好き、パンパン好きぃっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ぎゅーっと縄を引っ張って、たたきつけるみたいな乱暴なピストンをしているのに、ウズメは嬉しそうな声を上げるばかりだ。
line = "ぎゅーっと縄を引っ張って、たたきつけるみたいな乱暴なピストンをしているのに、ウズメは嬉しそうな声を上げるばかりだ。"

[[dialogue]]
speaker = "クロト"
# 「知らなかったぞ！　ウズメが、こんなエッチが好きだったなんて！」
line = "「知らなかったぞ！　ウズメが、こんなエッチが好きだったなんて！」"

[[dialogue]]
speaker = "ウズメイア"
# 「あ、ぁああっ、あたしも知らなかったよぉっ<emoji=heart04>　んっ、ふぅあっ<emoji=heart04>　んんんうっ<emoji=heart04>　好きな人にいじめられるの、こんなイイだなんてっ<emoji=heart04>」
line = "「あ、ぁああっ、あたしも知らなかったよぉっ<emoji=heart04>　んっ、ふぅあっ<emoji=heart04>　んんんうっ<emoji=heart04>　好きな人にいじめられるの、こんなイイだなんてっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「乱暴されてるんだぞ！　それなのに気持ちいいのかっ？」
line = "「乱暴されてるんだぞ！　それなのに気持ちいいのかっ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「か、会長くんだからぁっ<emoji=heart04>　大好きな会長くんにいじめられてるから、気持ちいいのっ<emoji=heart04>　あ、あぁ、あああ、ぁあっ<emoji=heart04>」
line = "「か、会長くんだからぁっ<emoji=heart04>　大好きな会長くんにいじめられてるから、気持ちいいのっ<emoji=heart04>　あ、あぁ、あああ、ぁあっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# いじらしいことを言ってくれたお礼に、今日一番の強さの平手をお尻に見舞ってやる。
line = "いじらしいことを言ってくれたお礼に、今日一番の強さの平手をお尻に見舞ってやる。"

[[dialogue]]
speaker = "ウズメイア"
# 「ぁぁぁあ──ッ！？<emoji=heart04>　んっきゅ、うぅう、うっぅう～っ……そ、それぇっ、今の強さで、もっとしてぇっ<emoji=heart04>」
line = "「ぁぁぁあ──ッ！？<emoji=heart04>　んっきゅ、うぅう、うっぅう～っ……そ、それぇっ、今の強さで、もっとしてぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「さっきからおねだりばっかりだな……！　ぶってもらったお礼も言えないの？」
line = "「さっきからおねだりばっかりだな……！　ぶってもらったお礼も言えないの？」"

[[dialogue]]
speaker = "ウズメイア"
# 「っ！？<emoji=heart04>　あ、ぁぁっ……ご、ごめんっ<emoji=heart04>　あ、たしの、お尻、ぶってくれたのに、お礼言わないで、ごめぇんっ<emoji=heart04>」
line = "「っ！？<emoji=heart04>　あ、ぁぁっ……ご、ごめんっ<emoji=heart04>　あ、たしの、お尻、ぶってくれたのに、お礼言わないで、ごめぇんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くんに叩かれるの、すっごく気持ち良かったっ<emoji=heart04>　マジヤバい、最高、だったしぃっ……<emoji=heart04>」
line = "「会長くんに叩かれるの、すっごく気持ち良かったっ<emoji=heart04>　マジヤバい、最高、だったしぃっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# この子をもっといじめてやりたい──そんな感情が脳裏を埋め尽くす。
line = "この子をもっといじめてやりたい──そんな感情が脳裏を埋め尽くす。"

[[dialogue]]
speaker = "クロト"
# 「敬語っ！」
line = "「敬語っ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ふぅうう～っ！？　ご、ごめんなさいっ<emoji=heart04>　縛られて悦ぶ、マゾ天使のくせに、タメ口利いてごめんなさいっ<emoji=heart04>」
line = "「ふぅうう～っ！？　ご、ごめんなさいっ<emoji=heart04>　縛られて悦ぶ、マゾ天使のくせに、タメ口利いてごめんなさいっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「う、ウズメのお尻、ぶ、ぶってくださって、あ、ありがとう、ございます、ぅうぅっ……！<emoji=heart04>」
line = "「う、ウズメのお尻、ぶ、ぶってくださって、あ、ありがとう、ございます、ぅうぅっ……！<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「お礼を言えてえらいぞ！　ご褒美、だっ！」
line = "「お礼を言えてえらいぞ！　ご褒美、だっ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ひっ──ぅううぅぅ～っ<emoji=heart04>　あっあっ、嬉しっ<emoji=heart04>　会長くん、しゅ、しゅきっ<emoji=heart04>　しゅきぃぃいっ<emoji=heart04>」
line = "「ひっ──ぅううぅぅ～っ<emoji=heart04>　あっあっ、嬉しっ<emoji=heart04>　会長くん、しゅ、しゅきっ<emoji=heart04>　しゅきぃぃいっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「ひぅううっ<emoji=heart04>　お、ぉぉおおっ<emoji=heart04>　叩きながら奥うぅっ、そんな、ぐりぐり──ぉおぉっ<emoji=heart04>」
line = "「ひぅううっ<emoji=heart04>　お、ぉぉおおっ<emoji=heart04>　叩きながら奥うぅっ、そんな、ぐりぐり──ぉおぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「このまま最後まで行くからな！　どこに出して欲しいんだっ？」
line = "「このまま最後まで行くからな！　どこに出して欲しいんだっ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「あ、あぅっ……ど、どうしよっ……中に欲しいけど、ぶっかけも、して欲しい、かもぉおっ……<emoji=heart04>」
line = "「あ、あぅっ……ど、どうしよっ……中に欲しいけど、ぶっかけも、して欲しい、かもぉおっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「欲張りな天使だなっ！　もういい、俺が決める！」
line = "「欲張りな天使だなっ！　もういい、俺が決める！」"

[[dialogue]]
speaker = "ウズメイア"
# 「んっっきゅぅっ<emoji=heart04>　あ、ぁあああ<emoji=heart04>　しゅ、しゅみましぇっ、お任せしましゅっ──あ、ぁ、あぁ、あ、あぁ、ああ～っ！<emoji=heart04>」
line = "「んっっきゅぅっ<emoji=heart04>　あ、ぁあああ<emoji=heart04>　しゅ、しゅみましぇっ、お任せしましゅっ──あ、ぁ、あぁ、あ、あぁ、ああ～っ！<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「しっかり締めろっ！　俺がイくまでぎゅって締めろっ、わかったかっ！」
line = "「しっかり締めろっ！　俺がイくまでぎゅって締めろっ、わかったかっ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「は──はいっ<emoji=heart04><emoji=heart04><emoji=heart04>　おま○こ、ぎゅーってしゅる、しゅるぅうっ……お、ぉおぉ、おぉお、おっおっおおっ<emoji=heart04>」
line = "「は──はいっ<emoji=heart04><emoji=heart04><emoji=heart04>　おま○こ、ぎゅーってしゅる、しゅるぅうっ……お、ぉおぉ、おぉお、おっおっおおっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「おち○ぽ、は、速い、強い──ぅあ、あ、ぁああっ<emoji=heart04>　そこダメ、弱いから、ダメ、イ、イグっイグっ、イっちゃう、ぅっ……！<emoji=heart04>」
line = "「おち○ぽ、は、速い、強い──ぅあ、あ、ぁああっ<emoji=heart04>　そこダメ、弱いから、ダメ、イ、イグっイグっ、イっちゃう、ぅっ……！<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「あっあっあっあっあっ<emoji=heart04>　ヤバっ、大きいの来るっ、来る来る来る、来るぅうううっ──<emoji=heart04>」
line = "「あっあっあっあっあっ<emoji=heart04>　ヤバっ、大きいの来るっ、来る来る来る、来るぅうううっ──<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「出すぞっ……ウズメ！」
line = "「出すぞっ……ウズメ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ひぁぁあぁああっ！？<emoji=heart04><emoji=heart04>　あ、イグぅっ！？　イグイグイグっ、イッグうぅぅうぅ～っ！<emoji=heart04>」
line = "「ひぁぁあぁああっ！？<emoji=heart04><emoji=heart04>　あ、イグぅっ！？　イグイグイグっ、イッグうぅぅうぅ～っ！<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「あああぁぁっ～～<emoji=heart04>　……ふああぁぁあぁぁぁあああぁぁぁ～～～～～～っ！！<emoji=heart04><emoji=heart04>」
line = "「あああぁぁっ～～<emoji=heart04>　……ふああぁぁあぁぁぁあああぁぁぁ～～～～～～っ！！<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 馬の手綱を握るみたいにウズメの縄を引っ張って、俺の方へ引き寄せて──ゼロ距離で子宮口に精液をぶちまける。
line = "馬の手綱を握るみたいにウズメの縄を引っ張って、俺の方へ引き寄せて──ゼロ距離で子宮口に精液をぶちまける。"

[[dialogue]]
speaker = "ウズメイア"
# 「ふぇあぁぁぁああっ！<emoji=heart04>　会長くぅんっ、んぁああっ！<emoji=heart04>　あ、あぁあーっ<emoji=heart04>　あぁぁああーっ！！<emoji=heart04>」
line = "「ふぇあぁぁぁああっ！<emoji=heart04>　会長くぅんっ、んぁああっ！<emoji=heart04>　あ、あぁあーっ<emoji=heart04>　あぁぁああーっ！！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 精液を注ぎ込むたびにガクガク震えるウズメ。このまま最後の一滴まで出してやりたいけれど、ぶっかけもして欲しいと言っていたから──
line = "精液を注ぎ込むたびにガクガク震えるウズメ。このまま最後の一滴まで出してやりたいけれど、ぶっかけもして欲しいと言っていたから──"

[[dialogue]]
speaker = "クロト"
# 「う──くぅっ！」
line = "「う──くぅっ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「んぁあ、ぁああっ……！<emoji=heart04>」
line = "「んぁあ、ぁああっ……！<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 射精の途中でペニスを引き抜いて、ウズメの全身を汚した──
line = "射精の途中でペニスを引き抜いて、ウズメの全身を汚した──"

[[dialogue]]
speaker = "ウズメイア"
# 「はぁああっ……ふぅうっ……んんぅっ……<emoji=heart04>　な、中も、外もぉっ……精液、いっぱぁい……<emoji=heart04>」
line = "「はぁああっ……ふぅうっ……んんぅっ……<emoji=heart04>　な、中も、外もぉっ……精液、いっぱぁい……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 白濁にまみれてうっとりするウズメとは正反対に、俺は賢者タイムが訪れたためか、急速に冷静さを取り戻しつつあった。
line = "白濁にまみれてうっとりするウズメとは正反対に、俺は賢者タイムが訪れたためか、急速に冷静さを取り戻しつつあった。"

[[dialogue]]
speaker = "unk"
# つまり……その……ちょっと調子に乗りすぎたかも。
line = "つまり……その……ちょっと調子に乗りすぎたかも。"

[[dialogue]]
speaker = "ウズメイア"
# 「はぁああっ……やっばあぁ～……精液、やばぁー……どろどろじゃん……<emoji=heart04>」
line = "「はぁああっ……やっばあぁ～……精液、やばぁー……どろどろじゃん……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「あ、あの……ウズメ？　その……」
line = "「あ、あの……ウズメ？　その……」"

[[dialogue]]
speaker = "ウズメイア"
# 「あ、ご、ごめんなさぁいっ……<emoji=heart04>　精液、いっぱい出してもらったのに、お礼、言えてません、でしたぁ<emoji=heart04>」
line = "「あ、ご、ごめんなさぁいっ……<emoji=heart04>　精液、いっぱい出してもらったのに、お礼、言えてません、でしたぁ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「マゾ天使のウズメイアに、大切な精液、いっぱいぶっかけてくださって、とっても嬉しい、ですぅ……<emoji=heart04>」
line = "「マゾ天使のウズメイアに、大切な精液、いっぱいぶっかけてくださって、とっても嬉しい、ですぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「い、いじめてくださって……ありがとうございましたぁ～……<emoji=heart04>」
line = "「い、いじめてくださって……ありがとうございましたぁ～……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「男らしい会長くん、すっごくかっこ良かったよぉっ……はぁぁぁん<emoji=heart04>　これからもたくさん、いじめてくださぁいっ……<emoji=heart04>」
line = "「男らしい会長くん、すっごくかっこ良かったよぉっ……はぁぁぁん<emoji=heart04>　これからもたくさん、いじめてくださぁいっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# どうやら信じがたいことに、ウズメにはマゾの素養があったらしく……
line = "どうやら信じがたいことに、ウズメにはマゾの素養があったらしく……"

[[dialogue]]
speaker = "unk"
# その日はいつまでも俺にへりくだって、ＳＭエッチをおねだりしてくるのだった──
line = "その日はいつまでも俺にへりくだって、ＳＭエッチをおねだりしてくるのだった──"
