[[dialogue]]
speaker = "unk"
# 第４話,キリカとケーキ入刀,P
line = "第４話,キリカとケーキ入刀,P"

[[dialogue]]
speaker = "キリカ"
# 「全くもう……わざわざ式場を訪れる必要はないのでは？　ウェディングドレス姿程度、自室で見せて差し上げますよ？」
line = "「全くもう……わざわざ式場を訪れる必要はないのでは？　ウェディングドレス姿程度、自室で見せて差し上げますよ？」"

[[dialogue]]
speaker = "キリカ"
# 「休憩中とはいえ職務中ですし。あまりお屋敷から離れてしまうと、ゆったり２人で過ごせる時間がむしろ少なく──……」
line = "「休憩中とはいえ職務中ですし。あまりお屋敷から離れてしまうと、ゆったり２人で過ごせる時間がむしろ少なく──……」"

[[dialogue]]
speaker = "キリカ"
# 「っっ！　な、何事ですっ！？」
line = "「っっ！　な、何事ですっ！？」"

[[dialogue]]
speaker = "みんな"
# 「おめでとうございま～す！」
line = "「おめでとうございま～す！」"

[[dialogue]]
speaker = "キリカ"
# 「は……はい？　なぜフィオナお嬢様とメイド隊がお揃いに？　それに私は一体何を祝われて……？」
line = "「は……はい？　なぜフィオナお嬢様とメイド隊がお揃いに？　それに私は一体何を祝われて……？」"

[[dialogue]]
speaker = "ナミエル"
# 「これは……現れるタイミングが早かったのでは？」
line = "「これは……現れるタイミングが早かったのでは？」"

[[dialogue]]
speaker = "マリオン"
# 「段取り担当はフェニエルさんでしたよね？　今だと言うから物陰から飛び出してクラッカーを鳴らしたのですけど」
line = "「段取り担当はフェニエルさんでしたよね？　今だと言うから物陰から飛び出してクラッカーを鳴らしたのですけど」"

[[dialogue]]
speaker = "フェニエル"
# 「ぴぃっ！？　しゅしゅしゅ、しゅみませんっ！　てっきりもう色々と伝えられた後かと思いましてっ……！！」
line = "「ぴぃっ！？　しゅしゅしゅ、しゅみませんっ！　てっきりもう色々と伝えられた後かと思いましてっ……！！」"

[[dialogue]]
speaker = "フィオナ"
# 「まぁまぁ細かいことはいいじゃない。緋宮会長が恥ずかしい想いをするだけだから♪」
line = "「まぁまぁ細かいことはいいじゃない。緋宮会長が恥ずかしい想いをするだけだから♪」"

[[dialogue]]
speaker = "キリカ"
# 「状況が掴めないのですが……」
line = "「状況が掴めないのですが……」"

[[dialogue]]
speaker = "unk"
# ええとね……
line = "ええとね……"

[[dialogue]]
speaker = "フィオナ"
# 「プロポーズだよ、プロポーズ♪　緋宮会長が今からキリカにプロポーズするの♪」
line = "「プロポーズだよ、プロポーズ♪　緋宮会長が今からキリカにプロポーズするの♪」"

[[dialogue]]
speaker = "キリカ"
# 「プロポっ──！？」
line = "「プロポっ──！？」"

[[dialogue]]
speaker = "マリオン"
# 「既に三ヶ月分のお給金をお嬢様に前借りしたそうですよ？　そこでプロポーズするつもりだと発覚してしまっただとか」
line = "「既に三ヶ月分のお給金をお嬢様に前借りしたそうですよ？　そこでプロポーズするつもりだと発覚してしまっただとか」"

[[dialogue]]
speaker = "フェニエル"
# 「そこでメイド隊総出でおふたりをお祝いしようというお話になったんです！　ウェディングケーキも作ったんですよ！」
line = "「そこでメイド隊総出でおふたりをお祝いしようというお話になったんです！　ウェディングケーキも作ったんですよ！」"

[[dialogue]]
speaker = "ナミエル"
# 「私はプロポーズに失敗して玉砕なさる緋宮会長を見に来ただけですが。メイド長も同棲生活を経て、緋宮会長に嫌気が差してきた頃でしょうし」
line = "「私はプロポーズに失敗して玉砕なさる緋宮会長を見に来ただけですが。メイド長も同棲生活を経て、緋宮会長に嫌気が差してきた頃でしょうし」"

[[dialogue]]
speaker = "キリカ"
# 「それでわざわざ式場へ……？　皆さまの前で公開プロポーズをするために……？」
line = "「それでわざわざ式場へ……？　皆さまの前で公開プロポーズをするために……？」"

[[dialogue]]
speaker = "unk"
# プロポーズしてから出てきてもらうはずだったけど
line = "プロポーズしてから出てきてもらうはずだったけど"

[[dialogue]]
speaker = "フィオナ"
# 「裏でこっそり覗いているのか、目の前で見ているのかの違いですよ♪　さぁさぁ早くプロポーズしてください！　熱い愛の言葉を聞かせてください！」
line = "「裏でこっそり覗いているのか、目の前で見ているのかの違いですよ♪　さぁさぁ早くプロポーズしてください！　熱い愛の言葉を聞かせてください！」"

[[dialogue]]
speaker = "キリカ"
# 「～～っっ。ま、待ってください。まだ心の準備が……！」
line = "「～～っっ。ま、待ってください。まだ心の準備が……！」"

[[dialogue]]
speaker = "フェニエル"
# 「はわー、あんなにお顔を真っ赤にしたキリカさん初めて見ました……」
line = "「はわー、あんなにお顔を真っ赤にしたキリカさん初めて見ました……」"

[[dialogue]]
speaker = "ナミエル"
# 「お声まで上擦らせて……」
line = "「お声まで上擦らせて……」"

[[dialogue]]
speaker = "マリオン"
# 「うふふ、キリカさんの鉄面皮が剥がれるなんて。恋は人を変えるものですね」
line = "「うふふ、キリカさんの鉄面皮が剥がれるなんて。恋は人を変えるものですね」"

[[dialogue]]
speaker = "キリカ"
# 「コ、コホン。あなたたちは早く職務に戻りなさい。休憩時間はとっくの昔に終わっているはずです。先代も隠居先に戻られてくださいませ」
line = "「コ、コホン。あなたたちは早く職務に戻りなさい。休憩時間はとっくの昔に終わっているはずです。先代も隠居先に戻られてくださいませ」"

[[dialogue]]
speaker = "マリオン"
# 「おやおや。私は隠居したつもりはないのですが」
line = "「おやおや。私は隠居したつもりはないのですが」"

[[dialogue]]
speaker = "フィオナ"
# 「メイド隊のみんなには午後から休暇を出したから♪　それにみんな、キリカの幸せを一緒にお祝いしたいの」
line = "「メイド隊のみんなには午後から休暇を出したから♪　それにみんな、キリカの幸せを一緒にお祝いしたいの」"

[[dialogue]]
speaker = "フィオナ"
# 「……幸せになってね、キリカ？　星見家に仕える使用人としてじゃなく、家族の一員として、あなたの幸せを祈っている」
line = "「……幸せになってね、キリカ？　星見家に仕える使用人としてじゃなく、家族の一員として、あなたの幸せを祈っている」"

[[dialogue]]
speaker = "キリカ"
# 「お嬢様……」
line = "「お嬢様……」"

[[dialogue]]
speaker = "unk"
# キリカ
line = "キリカ"

[[dialogue]]
speaker = "キリカ"
# 「っっ。は、はいっ」
line = "「っっ。は、はいっ」"

[[dialogue]]
speaker = "unk"
# 俺と結婚してください
line = "俺と結婚してください"

[[dialogue]]
speaker = "キリカ"
# 「……本当にあなたは身勝手なお方ですね。心の準備もさせず、自分の想いばかり強引に伝えてこられて……」
line = "「……本当にあなたは身勝手なお方ですね。心の準備もさせず、自分の想いばかり強引に伝えてこられて……」"

[[dialogue]]
speaker = "キリカ"
# 「ですが──……ん、ちゅっ<emoji=heart04>」
line = "「ですが──……ん、ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "キリカ"
# 「この上なく嬉しいです。皆の前でプロポーズしてくれたこと、結婚して欲しいと告げてくれたこと」
line = "「この上なく嬉しいです。皆の前でプロポーズしてくれたこと、結婚して欲しいと告げてくれたこと」"

[[dialogue]]
speaker = "キリカ"
# 「こんな私で良ければ、是非もらってください。私もずっと、あなたと<ruby=めおと>夫婦</ruby>になりたいと願っておりましたから……ちゅっ」
line = "「こんな私で良ければ、是非もらってください。私もずっと、あなたと<ruby>夫婦<rt>めおと</rt></ruby>になりたいと願っておりましたから……ちゅっ」"

[[dialogue]]
speaker = "フェニエル"
# 「ふぁー……？　い、今、チューしました……？　してましたよねっ？」
line = "「ふぁー……？　い、今、チューしました……？　してましたよねっ？」"

[[dialogue]]
speaker = "ナミエル"
# 「誓いの口づけを花嫁にさせるなんて、だらしない男性です。……と、というかいつまでチュッチュし合ってるのですか」
line = "「誓いの口づけを花嫁にさせるなんて、だらしない男性です。……と、というかいつまでチュッチュし合ってるのですか」"

[[dialogue]]
speaker = "マリオン"
# 「ふふ、どれだけキスしても足りないくらい幸せということですよ。今の内にウェディングケーキを運んできましょうか」
line = "「ふふ、どれだけキスしても足りないくらい幸せということですよ。今の内にウェディングケーキを運んできましょうか」"

[[dialogue]]
speaker = "フィオナ"
# 「ほーら２人とも♪　イチャイチャするのは帰ってからにして、初めての共同作業しないと♪」
line = "「ほーら２人とも♪　イチャイチャするのは帰ってからにして、初めての共同作業しないと♪」"

[[dialogue]]
speaker = "キリカ"
# 「ちゅ、んっ……～～っっ。わ、私としたことが。皆さまがいらっしゃることを失念していて……！」
line = "「ちゅ、んっ……～～っっ。わ、私としたことが。皆さまがいらっしゃることを失念していて……！」"

[[dialogue]]
speaker = "フィオナ"
# 「さあ２人とも。仲良くナイフを握って？　ナミエル、フェニエル、とびきりの笑顔を撮影してあげてね？」
line = "「さあ２人とも。仲良くナイフを握って？　ナミエル、フェニエル、とびきりの笑顔を撮影してあげてね？」"

[[dialogue]]
speaker = "キリカ"
# 「せ、急かさないでください。ひゃっ……！　て、手が触れてっ……」
line = "「せ、急かさないでください。ひゃっ……！　て、手が触れてっ……」"

[[dialogue]]
speaker = "unk"
# こうして手を取り合いながら生きていこう
line = "こうして手を取り合いながら生きていこう"

[[dialogue]]
speaker = "キリカ"
# 「っっ。は……はい」
line = "「っっ。は……はい」"

[[dialogue]]
speaker = "キリカ"
# 「しかし寿退社はいたしませんよ？　これからも私はフィオナお嬢様を支え続ける所存ですから。メイド長として、お嬢様の家族の一員として、それだけは譲れません」
line = "「しかし寿退社はいたしませんよ？　これからも私はフィオナお嬢様を支え続ける所存ですから。メイド長として、お嬢様の家族の一員として、それだけは譲れません」"

[[dialogue]]
speaker = "キリカ"
# 「ですが……同じくらいあなたのことも支えたいと思っております。世界にただ１人、私が心に決めた……愛するあなたを」
line = "「ですが……同じくらいあなたのことも支えたいと思っております。世界にただ１人、私が心に決めた……愛するあなたを」"

[[dialogue]]
speaker = "キリカ"
# 「さあケーキを切り分けましょうか。お嬢様も今か今かと待ち侘びていらっしゃいます」
line = "「さあケーキを切り分けましょうか。お嬢様も今か今かと待ち侘びていらっしゃいます」"

[[dialogue]]
speaker = "キリカ"
# 「幸せいっぱいの笑顔を見せつけて、ふふ。お嬢様を安心させてあげましょう」
line = "「幸せいっぱいの笑顔を見せつけて、ふふ。お嬢様を安心させてあげましょう」"
