[[dialogue]]
speaker = "unk"
# 第２話,釣りをするぞ！,P
line = "第２話,釣りをするぞ！,P"

[[dialogue]]
speaker = "unk"
# また別の日──
line = "また別の日──"

[[dialogue]]
speaker = "アポロ"
# 「──釣りをするぞ、魔王！」
line = "「──釣りをするぞ、魔王！」"

[[dialogue]]
speaker = "アポロ"
# 「なんでかって？　へへ……リップルからいいスポットを教えてもらったんだ。魚がバンバン釣れるらしーぜ！」
line = "「なんでかって？　へへ……リップルからいいスポットを教えてもらったんだ。魚がバンバン釣れるらしーぜ！」"

[[dialogue]]
speaker = "アポロ"
# 「つっても、あたしは釣りなんかやったことないからよ。どうしたもんかと思ってたんだが……」
line = "「つっても、あたしは釣りなんかやったことないからよ。どうしたもんかと思ってたんだが……」"

[[dialogue]]
speaker = "アポロ"
# 「魔王は釣りの名人だって聞いたぞ！　昔やってたんだろ？　なあなあ、あたしにも教えてくれよ～！」
line = "「魔王は釣りの名人だって聞いたぞ！　昔やってたんだろ？　なあなあ、あたしにも教えてくれよ～！」"

[[dialogue]]
speaker = "unk"
# 釣りの道は厳しいぞ
line = "釣りの道は厳しいぞ"

[[dialogue]]
speaker = "unk"
# それほどでも
line = "それほどでも"

[[dialogue]]
speaker = "アポロ"
# 「よっしゃ、サンキューな！　さっそく教えてもらったアナバまでいこーぜ！」
line = "「よっしゃ、サンキューな！　さっそく教えてもらったアナバまでいこーぜ！」"

[[dialogue]]
speaker = "unk"
# アポロに連れられ向かった岩礁地帯で、ルアーフィッシングの簡単なやり方をレクチャーすることに……。
line = "アポロに連れられ向かった岩礁地帯で、ルアーフィッシングの簡単なやり方をレクチャーすることに……。"

[[dialogue]]
speaker = "アポロ"
# 「………………」
line = "「………………」"

[[dialogue]]
speaker = "アポロ"
# 「むむ……なあ……さっきから竿がピクリとも動かないぞ。やり方、間違ってないか？」
line = "「むむ……なあ……さっきから竿がピクリとも動かないぞ。やり方、間違ってないか？」"

[[dialogue]]
speaker = "アポロ"
# 「まだ５分しか経ってない？　いやいや、もう５分だろ！　この５分があったらなんでもできるぞ──ドッジとか、ビーチバレーとか！」
line = "「まだ５分しか経ってない？　いやいや、もう５分だろ！　この５分があったらなんでもできるぞ──ドッジとか、ビーチバレーとか！」"

[[dialogue]]
speaker = "unk"
# アポロは、どうせならばと海の家から一番大型のロッドを借りてきていた。初心者があれでは苦戦するだろう。
line = "アポロは、どうせならばと海の家から一番大型のロッドを借りてきていた。初心者があれでは苦戦するだろう。"

[[dialogue]]
speaker = "アポロ"
# 「え？　そうやって地道に待つことが釣りのコツ……？　むぅ──ならしょうがないな……」
line = "「え？　そうやって地道に待つことが釣りのコツ……？　むぅ──ならしょうがないな……」"

[[dialogue]]
speaker = "unk"
# しかし、その後──
line = "しかし、その後──"

[[dialogue]]
speaker = "アポロ"
# 「──おおっ！？　なんか引っかかったぞ！」
line = "「──おおっ！？　なんか引っかかったぞ！」"

[[dialogue]]
speaker = "アポロ"
# 「──釣れた！　見ろ見ろ魔王、こいつはどうだ！？」
line = "「──釣れた！　見ろ見ろ魔王、こいつはどうだ！？」"

[[dialogue]]
speaker = "unk"
# これは……
line = "これは……"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "アポロ"
# 「ん？　どーした、目ん玉ひん剥いて」
line = "「ん？　どーした、目ん玉ひん剥いて」"

[[dialogue]]
speaker = "アポロ"
# 「わーたた、ピチピチ跳ねるなって！　威勢がいいなこいつ」
line = "「わーたた、ピチピチ跳ねるなって！　威勢がいいなこいつ」"

[[dialogue]]
speaker = "unk"
# アポロが釣り上げたのは、彼女が両手で抱えるほど巨大なハタの一種だった。
line = "アポロが釣り上げたのは、彼女が両手で抱えるほど巨大なハタの一種だった。"

[[dialogue]]
speaker = "アポロ"
# 「ん？　びぎなーずらっく？　魚の名前か？」
line = "「ん？　びぎなーずらっく？　魚の名前か？」"

[[dialogue]]
speaker = "アポロ"
# 「それよりさ、なあ。どうなんだ、この魚？　ウマイのか？」
line = "「それよりさ、なあ。どうなんだ、この魚？　ウマイのか？」"

[[dialogue]]
speaker = "unk"
# 毒があるかも
line = "毒があるかも"

[[dialogue]]
speaker = "unk"
# 食用じゃない
line = "食用じゃない"

[[dialogue]]
speaker = "アポロ"
# 「へ──食べれる部位がない？　なんだよそれ～！　せっかく釣れたと思ったのによ」
line = "「へ──食べれる部位がない？　なんだよそれ～！　せっかく釣れたと思ったのによ」"

[[dialogue]]
speaker = "アポロ"
# 「ちぇっ、まあいいや。そんなら用はねーし、喉に引っかかった程度っぽいから海に返しとくか」
line = "「ちぇっ、まあいいや。そんなら用はねーし、喉に引っかかった程度っぽいから海に返しとくか」"

[[dialogue]]
speaker = "unk"
# リゾート結界の海には、南国の水温に適したカラフルな魚が多くいることがわかっていた。
line = "リゾート結界の海には、南国の水温に適したカラフルな魚が多くいることがわかっていた。"

[[dialogue]]
speaker = "アポロ"
# 「んで、魔王のほうは？」
line = "「んで、魔王のほうは？」"

[[dialogue]]
speaker = "unk"
# 達人は粘るもの
line = "達人は粘るもの"

[[dialogue]]
speaker = "unk"
# まだ……
line = "まだ……"

[[dialogue]]
speaker = "アポロ"
# 「なるほどな。さらなる大物にしか興味ねーってわけか……それでこそあたしのライバル！」
line = "「なるほどな。さらなる大物にしか興味ねーってわけか……それでこそあたしのライバル！」"

[[dialogue]]
speaker = "アポロ"
# 「俄然こっちも燃えてきたぜ。よし、この調子でどんどん釣り上げてやるぞ！」
line = "「俄然こっちも燃えてきたぜ。よし、この調子でどんどん釣り上げてやるぞ！」"

[[dialogue]]
speaker = "unk"
# そうして、数時間──
line = "そうして、数時間──"

[[dialogue]]
speaker = "アポロ"
# 「おっと──またかかったぞ！」
line = "「おっと──またかかったぞ！」"

[[dialogue]]
speaker = "アポロ"
# 「──って、あーあ。またさっきのデカコブ魚だ。食えないデカブツばっか釣れてもしょーがねーなあ」
line = "「──って、あーあ。またさっきのデカコブ魚だ。食えないデカブツばっか釣れてもしょーがねーなあ」"

[[dialogue]]
speaker = "unk"
# アポロはあれから、見たこともないような珍しい魚をバンバン釣り上げていた。
line = "アポロはあれから、見たこともないような珍しい魚をバンバン釣り上げていた。"

[[dialogue]]
speaker = "アポロ"
# 「ん？　暴れるのに重くないのかって？　んまあ、いつも担いでる大剣に比べたら大した重量じゃねーな」
line = "「ん？　暴れるのに重くないのかって？　んまあ、いつも担いでる大剣に比べたら大した重量じゃねーな」"

[[dialogue]]
speaker = "アポロ"
# 「んで、魔王はどうだ？　あれからだいぶ時間も経ったけど……」
line = "「んで、魔王はどうだ？　あれからだいぶ時間も経ったけど……」"

[[dialogue]]
speaker = "unk"
# 一匹だけ……
line = "一匹だけ……"

[[dialogue]]
speaker = "unk"
# アジが……
line = "アジが……"

[[dialogue]]
speaker = "アポロ"
# 「アジ？　へー、すげーな！　きっと焼いたらウマイんだろうな」
line = "「アジ？　へー、すげーな！　きっと焼いたらウマイんだろうな」"

[[dialogue]]
speaker = "アポロ"
# 「あたしも負けてらんないぜ。魔王に負けないくらいウマイ魚をきっと──」
line = "「あたしも負けてらんないぜ。魔王に負けないくらいウマイ魚をきっと──」"

[[dialogue]]
speaker = "リップル"
# 「ハーイ、アポロにカイチョー！　ワタシ秘蔵のスポットで、海釣りを楽しんでマスカ──って」
line = "「ハーイ、アポロにカイチョー！　ワタシ秘蔵のスポットで、海釣りを楽しんでマスカ──って」"

[[dialogue]]
speaker = "リップル"
# 「ワーオ！？　こ、これはリゾート結界にただ１匹だけ生息しているという伝説のヌシ──釣り上げたのは一体！？」
line = "「ワーオ！？　こ、これはリゾート結界にただ１匹だけ生息しているという伝説のヌシ──釣り上げたのは一体！？」"

[[dialogue]]
speaker = "アポロ"
# 「おうリップル！　サンキューな。オマエの教えてくれたスポット、それなりに魚が釣れるぞ」
line = "「おうリップル！　サンキューな。オマエの教えてくれたスポット、それなりに魚が釣れるぞ」"

[[dialogue]]
speaker = "リップル"
# 「た、確かに穴場は教えマシタけど……ここまで大漁に釣ってるアングラーは初めて見マシタ！」
line = "「た、確かに穴場は教えマシタけど……ここまで大漁に釣ってるアングラーは初めて見マシタ！」"

[[dialogue]]
speaker = "リップル"
# 「まさにタイコーボー！　天才釣り人の誕生デ～ス！」
line = "「まさにタイコーボー！　天才釣り人の誕生デ～ス！」"

[[dialogue]]
speaker = "アポロ"
# 「──お、また釣れた。ってまたデカブツじゃねーか。よし、しょーがねーから次はこいつを餌にして……っと……」
line = "「──お、また釣れた。ってまたデカブツじゃねーか。よし、しょーがねーから次はこいつを餌にして……っと……」"

[[dialogue]]
speaker = "unk"
# そうして、最終的に──
line = "そうして、最終的に──"

[[dialogue]]
speaker = "アポロ"
# 「──んまい！」
line = "「──んまい！」"

[[dialogue]]
speaker = "アポロ"
# 「むしゃむしゃ……！　アジの塩焼きって、こんなにウマかったんだな！　もぐもぐ……！」
line = "「むしゃむしゃ……！　アジの塩焼きって、こんなにウマかったんだな！　もぐもぐ……！」"

[[dialogue]]
speaker = "unk"
# アポロの胃袋に収まることとなったのは、こちらの釣り上げた平均サイズのアジやキスたちだった。
line = "アポロの胃袋に収まることとなったのは、こちらの釣り上げた平均サイズのアジやキスたちだった。"

[[dialogue]]
speaker = "アポロ"
# 「こんなにおいしい魚も釣れるなんて、さすがは魔王だな！　見直したぜ」
line = "「こんなにおいしい魚も釣れるなんて、さすがは魔王だな！　見直したぜ」"

[[dialogue]]
speaker = "アポロ"
# 「あたしときたら、デカくてカラフルなのばっかりで、どいつもてんで食べられやしなかったもんな。今回ばかりは完敗と認めざるをえないぜ」
line = "「あたしときたら、デカくてカラフルなのばっかりで、どいつもてんで食べられやしなかったもんな。今回ばかりは完敗と認めざるをえないぜ」"

[[dialogue]]
speaker = "アポロ"
# 「あの、カジキだっけ？　でけーし痛そうなヤツは、あんまり暴れるから可愛そうで逃がしちゃったしな」
line = "「あの、カジキだっけ？　でけーし痛そうなヤツは、あんまり暴れるから可愛そうで逃がしちゃったしな」"

[[dialogue]]
speaker = "アポロ"
# 「まったく魔王には敵わないぜ！　また、あたしに釣りを教えてくれよな！」
line = "「まったく魔王には敵わないぜ！　また、あたしに釣りを教えてくれよな！」"

[[dialogue]]
speaker = "unk"
# （静かな努力を誓う）
line = "（静かな努力を誓う）"

[[dialogue]]
speaker = "unk"
# はは……
line = "はは……"

[[dialogue]]
speaker = "unk"
# 釣り人として、去来する敗北感のなか……
line = "釣り人として、去来する敗北感のなか……"

[[dialogue]]
speaker = "unk"
# 次回までに必ずやフィッシングテクニックを磨いておこうと、静かな誓いを胸に秘めるのだった。
line = "次回までに必ずやフィッシングテクニックを磨いておこうと、静かな誓いを胸に秘めるのだった。"
