[[dialogue]]
speaker = "unk"
# 第１話,えっちな人は『お掃除』します,P
line = "第１話,えっちな人は『お掃除』します,P"

[[dialogue]]
speaker = "フィオナ"
# 「わざわざ来ていただいたのにすみません、緋宮会長。教皇庁の者と話をする必要がありまして……少しの間、ここでメイドと待っていていただけますか？」
line = "「わざわざ来ていただいたのにすみません、緋宮会長。教皇庁の者と話をする必要がありまして……少しの間、ここでメイドと待っていていただけますか？」"

[[dialogue]]
speaker = "unk"
# もちろん大丈夫
line = "もちろん大丈夫"

[[dialogue]]
speaker = "フィオナ"
# 「ありがとうございます。ナミエル～」
line = "「ありがとうございます。ナミエル～」"

[[dialogue]]
speaker = "ナミエル"
# 「お呼びでしょうか、フィオナお嬢様」
line = "「お呼びでしょうか、フィオナお嬢様」"

[[dialogue]]
speaker = "フィオナ"
# 「ナミエル。私が部屋を空ける間、緋宮会長の応対をお願いね」
line = "「ナミエル。私が部屋を空ける間、緋宮会長の応対をお願いね」"

[[dialogue]]
speaker = "ナミエル"
# 「承知いたしました」
line = "「承知いたしました」"

[[dialogue]]
speaker = "フィオナ"
# 「この間みたいに、お客さんに殺気を向けるのはダメだからね」
line = "「この間みたいに、お客さんに殺気を向けるのはダメだからね」"

[[dialogue]]
speaker = "ナミエル"
# 「お嬢様。お言葉を返すようですが、あのお客様は挙動が怪しかったのです。私を見るたび、ニヤニヤと笑って──」
line = "「お嬢様。お言葉を返すようですが、あのお客様は挙動が怪しかったのです。私を見るたび、ニヤニヤと笑って──」"

[[dialogue]]
speaker = "フィオナ"
# 「それはナミエルがあまりにも警戒して睨むから、愛想笑いをしてただけじゃ……。男の人だからといって理由もなく怪しんだり、威圧するのはいけないよ」
line = "「それはナミエルがあまりにも警戒して睨むから、愛想笑いをしてただけじゃ……。男の人だからといって理由もなく怪しんだり、威圧するのはいけないよ」"

[[dialogue]]
speaker = "ナミエル"
# 「でも男性はえっちな生き物です。隙を与えれば豹変すると本にも書いてありました」
line = "「でも男性はえっちな生き物です。隙を与えれば豹変すると本にも書いてありました」"

[[dialogue]]
speaker = "フィオナ"
# 「うーん、また今度、ちゃんと話したほうがいいのかなぁ……。とにかく、早とちりで『掃除』をしないようにしてね」
line = "「うーん、また今度、ちゃんと話したほうがいいのかなぁ……。とにかく、早とちりで『掃除』をしないようにしてね」"

[[dialogue]]
speaker = "ナミエル"
# 「かしこまりました」
line = "「かしこまりました」"

[[dialogue]]
speaker = "フィオナ"
# 「では緋宮会長。何かしてほしいことがあったらナミエルに言ってください。できるだけ早く戻ってきますので」
line = "「では緋宮会長。何かしてほしいことがあったらナミエルに言ってください。できるだけ早く戻ってきますので」"

[[dialogue]]
speaker = "ナミエル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# よろしく、ナミエル
line = "よろしく、ナミエル"

[[dialogue]]
speaker = "ナミエル"
# 「私はあまりよろしくしたくありませんが、致し方ありません」
line = "「私はあまりよろしくしたくありませんが、致し方ありません」"

[[dialogue]]
speaker = "ナミエル"
# 「ナミエル・クレシェンテと申します。流星学園附属の１年生。ご覧のとおり、星見家メイド隊の一員でもあります」
line = "「ナミエル・クレシェンテと申します。流星学園附属の１年生。ご覧のとおり、星見家メイド隊の一員でもあります」"

[[dialogue]]
speaker = "ナミエル"
# 「得意なことは掃除。嫌いなものは拭いてもなかなか落ちない汚れと、男性全般です」
line = "「得意なことは掃除。嫌いなものは拭いてもなかなか落ちない汚れと、男性全般です」"

[[dialogue]]
speaker = "unk"
# ひょっとしなくても俺……嫌われてる？
line = "ひょっとしなくても俺……嫌われてる？"

[[dialogue]]
speaker = "ナミエル"
# 「はい。わざわざ休日に、アステラ対策などと称してお嬢様のご自宅にまで来られる輩は初めてです」
line = "「はい。わざわざ休日に、アステラ対策などと称してお嬢様のご自宅にまで来られる輩は初めてです」"

[[dialogue]]
speaker = "ナミエル"
# 「お嬢様目当てに違いありません。警戒レベルを普段の３倍に引き上げて対応するのは当然でしょう」
line = "「お嬢様目当てに違いありません。警戒レベルを普段の３倍に引き上げて対応するのは当然でしょう」"

[[dialogue]]
speaker = "ナミエル"
# 「不埒な考えはすぐに見透かします。私に隙はございません。背中にも目を付けるよう、特殊な訓練を積んできましたから」
line = "「不埒な考えはすぐに見透かします。私に隙はございません。背中にも目を付けるよう、特殊な訓練を積んできましたから」"

[[dialogue]]
speaker = "ナミエル"
# 「……自己紹介は以上です。紅茶のお代わりなど、必要なものがあればお申し付けください。それでは」
line = "「……自己紹介は以上です。紅茶のお代わりなど、必要なものがあればお申し付けください。それでは」"

[[dialogue]]
speaker = "unk"
# 真面目な子なのだろう。俺への過度な警戒も、フィオナへの忠誠心の高さと取ればそれも長所だ。
line = "真面目な子なのだろう。俺への過度な警戒も、フィオナへの忠誠心の高さと取ればそれも長所だ。"

[[dialogue]]
speaker = "unk"
# それに『背中にも目がある』と言ったのは伊達ではなく、所作のひとつひとつに隙がない。
line = "それに『背中にも目がある』と言ったのは伊達ではなく、所作のひとつひとつに隙がない。"

[[dialogue]]
speaker = "unk"
# だけど一点だけ──
line = "だけど一点だけ──"

[[dialogue]]
speaker = "ナミエル"
# 「どうぞ、紅茶です。お茶菓子もお召し上がりください」
line = "「どうぞ、紅茶です。お茶菓子もお召し上がりください」"

[[dialogue]]
speaker = "unk"
# （ナミエルのスカートが引っかかって……）
line = "（ナミエルのスカートが引っかかって……）"

[[dialogue]]
speaker = "ナミエル"
# 「お嬢様はもうすぐお戻りになるそうです。しばしお待ちください」
line = "「お嬢様はもうすぐお戻りになるそうです。しばしお待ちください」"

[[dialogue]]
speaker = "unk"
# （タイツ越しにパンツが見えてる……！）
line = "（タイツ越しにパンツが見えてる……！）"

[[dialogue]]
speaker = "ナミエル"
# 「──あの。さっきから何ですか？　視線をすごく感じるのですが」
line = "「──あの。さっきから何ですか？　視線をすごく感じるのですが」"

[[dialogue]]
speaker = "ナミエル"
# 「メイド服の…………スカート？」
line = "「メイド服の…………スカート？」"

[[dialogue]]
speaker = "ナミエル"
# 「～～～～っ！？」
line = "「～～～～っ！？」"

[[dialogue]]
speaker = "ナミエル"
# 「ず、ずっと黙って見ていたんですかっ！？　信じられません！　ほ、ほほ、本性を現しましたねっ！？」
line = "「ず、ずっと黙って見ていたんですかっ！？　信じられません！　ほ、ほほ、本性を現しましたねっ！？」"

[[dialogue]]
speaker = "unk"
# ごめん、わざとじゃないんだ！
line = "ごめん、わざとじゃないんだ！"

[[dialogue]]
speaker = "ナミエル"
# 「エロ会長！　変態！　スケベ！　変質者！　ええ、えっちな人は洗い流します！」
line = "「エロ会長！　変態！　スケベ！　変質者！　ええ、えっちな人は洗い流します！」"

[[dialogue]]
speaker = "ナミエル"
# 「ぅぅ……うぅ～～～っ……」
line = "「ぅぅ……うぅ～～～っ……」"

[[dialogue]]
speaker = "フィオナ"
# 「ただいま戻りまし──た？」
line = "「ただいま戻りまし──た？」"

[[dialogue]]
speaker = "ナミエル"
# 「うわあぁああぁぁ～～～～～んっ！」
line = "「うわあぁああぁぁ～～～～～んっ！」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長……これはいったいどういうことでしょうか？」
line = "「緋宮会長……これはいったいどういうことでしょうか？」"

[[dialogue]]
speaker = "ナミエル"
# 「うぇええっ……ひくっ、ぐすっ……うわぁああんっ！！」
line = "「うぇええっ……ひくっ、ぐすっ……うわぁああんっ！！」"

[[dialogue]]
speaker = "unk"
# 号泣するナミエルの声が部屋に大きく響く。
line = "号泣するナミエルの声が部屋に大きく響く。"

[[dialogue]]
speaker = "unk"
# 殺気をみなぎらせるフィオナの誤解を解くのに、とても苦労したのだった──
line = "殺気をみなぎらせるフィオナの誤解を解くのに、とても苦労したのだった──"
