[[dialogue]]
speaker = "unk"
# 第１話,誰かがそばにいるような……？,P
line = "第１話,誰かがそばにいるような……？,P"

[[dialogue]]
speaker = "サーシャ"
# 「あら～？　会長くんってばもうそのお仕事に取りかかってるの。手際がいいのね～」
line = "「あら～？　会長くんってばもうそのお仕事に取りかかってるの。手際がいいのね～」"

[[dialogue]]
speaker = "アナ"
# 「驚異的なペース。会長、最近絶好調ですね。１週間分の仕事を渡したのは数日前なのに」
line = "「驚異的なペース。会長、最近絶好調ですね。１週間分の仕事を渡したのは数日前なのに」"

[[dialogue]]
speaker = "unk"
# なんだか最近、疲れ知らずなんだ
line = "なんだか最近、疲れ知らずなんだ"

[[dialogue]]
speaker = "？？？"
# 「ふふ。それも当然のこと。魔王様の傍らには常に私──」
line = "「ふふ。それも当然のこと。魔王様の傍らには常に私──」"

[[dialogue]]
speaker = "トリュファイナ"
# 「第７代、光の魔女のトリュファイナが控えておりますゆえ」
line = "「第７代、光の魔女のトリュファイナが控えておりますゆえ」"

[[dialogue]]
speaker = "トリュファイナ"
# 「寝不足の疲労も書類仕事に伴う身体のコリも、全て影から魔法にてお癒しさせていただいております」
line = "「寝不足の疲労も書類仕事に伴う身体のコリも、全て影から魔法にてお癒しさせていただいております」"

[[dialogue]]
speaker = "トリュファイナ"
# 「……なんて。霊体である私が喋っても誰にも気づいてはいただけないのですが……い、いえ。今日こそはしっかりとアピールを……」
line = "「……なんて。霊体である私が喋っても誰にも気づいてはいただけないのですが……い、いえ。今日こそはしっかりとアピールを……」"

[[dialogue]]
speaker = "サーシャ"
# 「えらい、えらい♪　お仕事ぜーんぶ終わったら、お姉ちゃんがナデナデしてあげるわね～」
line = "「えらい、えらい♪　お仕事ぜーんぶ終わったら、お姉ちゃんがナデナデしてあげるわね～」"

[[dialogue]]
speaker = "トリュファイナ"
# 「あぁサーシャ様。それはよい案です。どうかぜひ、魔王様の頭をナデナデするお役目、私にお任せください」
line = "「あぁサーシャ様。それはよい案です。どうかぜひ、魔王様の頭をナデナデするお役目、私にお任せください」"

[[dialogue]]
speaker = "トリュファイナ"
# 「<ruby=レナトゥス>封理再誕</ruby>より目覚めし英雄のお世話は、今後も私に一任いただければ幸いです。これも乗りかかった船ですので」
line = "「<ruby>封理再誕<rt>レナトゥス</rt></ruby>より目覚めし英雄のお世話は、今後も私に一任いただければ幸いです。これも乗りかかった船ですので」"

[[dialogue]]
speaker = "unk"
# あ──痛っ
line = "あ──痛っ"

[[dialogue]]
speaker = "サーシャ"
# 「あっ、会長くんったら。紙で指、切っちゃった？」
line = "「あっ、会長くんったら。紙で指、切っちゃった？」"

[[dialogue]]
speaker = "トリュファイナ"
# 「む……っ！　再生の魔女の奇蹟を今ここにっ……ルクス・リプロダクション！」
line = "「む……っ！　再生の魔女の奇蹟を今ここにっ……ルクス・リプロダクション！」"

[[dialogue]]
speaker = "アナ"
# 「絆創膏ならここに……あれ？　なんともないですね」
line = "「絆創膏ならここに……あれ？　なんともないですね」"

[[dialogue]]
speaker = "サーシャ"
# 「怪我しちゃったと思ったけど……見間違いだったのかしら？」
line = "「怪我しちゃったと思ったけど……見間違いだったのかしら？」"

[[dialogue]]
speaker = "トリュファイナ"
# 「見間違いではありませんよ。私。私がお癒やししたのですよ。気づいてくださいませ」
line = "「見間違いではありませんよ。私。私がお癒やししたのですよ。気づいてくださいませ」"

[[dialogue]]
speaker = "アナ"
# 「まぁでも怪我がないなら何よりです。仕事の進捗も目覚ましいですし、お茶を淹れて休憩しましょう」
line = "「まぁでも怪我がないなら何よりです。仕事の進捗も目覚ましいですし、お茶を淹れて休憩しましょう」"

[[dialogue]]
speaker = "サーシャ"
# 「あら……アナちゃん、カップを４つも出すの？」
line = "「あら……アナちゃん、カップを４つも出すの？」"

[[dialogue]]
speaker = "トリュファイナ"
# 「……っ！！　もしかしてアナ様、霊体である私が見えているのですか……！？」
line = "「……っ！！　もしかしてアナ様、霊体である私が見えているのですか……！？」"

[[dialogue]]
speaker = "アナ"
# 「ええ、４つです。人数分ですから」
line = "「ええ、４つです。人数分ですから」"

[[dialogue]]
speaker = "トリュファイナ"
# 「ああ、何ということでしょう！　とうとう奇蹟が起こったのですね！　私の姿が見える方が現れたのですね！」
line = "「ああ、何ということでしょう！　とうとう奇蹟が起こったのですね！　私の姿が見える方が現れたのですね！」"

[[dialogue]]
speaker = "トリュファイナ"
# 「でもでも、よろしいのですよ。今の私は霊体です。何かを食べたり飲んだりはできませんので、お気持ちだけでも──」
line = "「でもでも、よろしいのですよ。今の私は霊体です。何かを食べたり飲んだりはできませんので、お気持ちだけでも──」"

[[dialogue]]
speaker = "アナ"
# 「マトイ先輩がもうすぐやってくる頃合いです。先んじて淹れておこうかなと」
line = "「マトイ先輩がもうすぐやってくる頃合いです。先んじて淹れておこうかなと」"

[[dialogue]]
speaker = "トリュファイナ"
# 「……やっぱり。見えませんよね……そうですよね……」
line = "「……やっぱり。見えませんよね……そうですよね……」"

[[dialogue]]
speaker = "トリュファイナ"
# 「深く魂で繋がった魔王様にも、私の姿は見えないのですから……私はこの時代で、ずうっと１人ぼっちなのでしょうか……」
line = "「深く魂で繋がった魔王様にも、私の姿は見えないのですから……私はこの時代で、ずうっと１人ぼっちなのでしょうか……」"

[[dialogue]]
speaker = "サーシャ"
# 「ん～？　会長くん、どうしたの。首をかしげちゃって」
line = "「ん～？　会長くん、どうしたの。首をかしげちゃって」"

[[dialogue]]
speaker = "unk"
# 今、誰かが泣いていたような……
line = "今、誰かが泣いていたような……"

[[dialogue]]
speaker = "サーシャ"
# 「そうかしら～？　ふぅん、お部屋から出て行った気もするの？　……変ね、扉を閉める音なんて聞こえなかったけれど」
line = "「そうかしら～？　ふぅん、お部屋から出て行った気もするの？　……変ね、扉を閉める音なんて聞こえなかったけれど」"

[[dialogue]]
speaker = "アナ"
# 「右に同じです。会長、張り切りすぎて疲れているのでは？」
line = "「右に同じです。会長、張り切りすぎて疲れているのでは？」"

[[dialogue]]
speaker = "unk"
# （違和感の正体を探しに行く）
line = "（違和感の正体を探しに行く）"

[[dialogue]]
speaker = "サーシャ"
# 「あら、お出かけするの？　すぐに戻る……？　わかったわ～」
line = "「あら、お出かけするの？　すぐに戻る……？　わかったわ～」"

[[dialogue]]
speaker = "アナ"
# 「せっかくお茶を淹れたのですから、冷めないうちに戻って来てくださいね」
line = "「せっかくお茶を淹れたのですから、冷めないうちに戻って来てくださいね」"

[[dialogue]]
speaker = "unk"
# 探し出したいと強く意識すると、その『誰か』の存在が濃くなったり薄くなったりすることに気づいた。俺は『誰か』の気配がする方向へ走り……
line = "探し出したいと強く意識すると、その『誰か』の存在が濃くなったり薄くなったりすることに気づいた。俺は『誰か』の気配がする方向へ走り……"

[[dialogue]]
speaker = "unk"
# 侵入厳禁であるため誰も寄りつかないフィーニスの塔。そのすぐ下に、三角座りをして泣いている女の子がいた──
line = "侵入厳禁であるため誰も寄りつかないフィーニスの塔。そのすぐ下に、三角座りをして泣いている女の子がいた──"

[[dialogue]]
speaker = "トリュファイナ"
# 「くすん……くすん……私、寂しいです。ラクシス様……いえ、クロト様……」
line = "「くすん……くすん……私、寂しいです。ラクシス様……いえ、クロト様……」"

[[dialogue]]
speaker = "unk"
# あ、あのー……
line = "あ、あのー……"

[[dialogue]]
speaker = "トリュファイナ"
# 「いくら霊体とはいえ、ずうっと見つけてくださらない。あんまりです。あなた様の魂に引っ張られて現代に再誕したというのに……」
line = "「いくら霊体とはいえ、ずうっと見つけてくださらない。あんまりです。あなた様の魂に引っ張られて現代に再誕したというのに……」"

[[dialogue]]
speaker = "トリュファイナ"
# 「へっ……？　あ、あれ……今度こそ本当に、見えて……？」
line = "「へっ……？　あ、あれ……今度こそ本当に、見えて……？」"

[[dialogue]]
speaker = "unk"
# 先代、光の魔女のトリュファイナさん！？
line = "先代、光の魔女のトリュファイナさん！？"

[[dialogue]]
speaker = "unk"
# あなたはラクシスの記憶の中で見た……
line = "あなたはラクシスの記憶の中で見た……"

[[dialogue]]
speaker = "トリュファイナ"
# 「やっと……やっと気づいていただけました……！　うぅ、誰にも気づいてもらえない悲しみ！　苦しみ！　寂しさっ……！」
line = "「やっと……やっと気づいていただけました……！　うぅ、誰にも気づいてもらえない悲しみ！　苦しみ！　寂しさっ……！」"

[[dialogue]]
speaker = "トリュファイナ"
# 「ええ、そうです！　あなた様がラクシス様の過去を垣間見た際、私も霊体としてこの現代に呼び出されたのです！」
line = "「ええ、そうです！　あなた様がラクシス様の過去を垣間見た際、私も霊体としてこの現代に呼び出されたのです！」"

[[dialogue]]
speaker = "トリュファイナ"
# 「<ruby=レナトゥス>封理再誕</ruby>による副作用か、魔王の因子の影響かは存じませんがっ……ずっと、ずっとお傍におりました！」
line = "「<ruby>封理再誕<rt>レナトゥス</rt></ruby>による副作用か、魔王の因子の影響かは存じませんがっ……ずっと、ずっとお傍におりました！」"

[[dialogue]]
speaker = "トリュファイナ"
# 「フィーニスの塔・第零層の攻略の時も、その後もずっとですよ……！？」
line = "「フィーニスの塔・第零層の攻略の時も、その後もずっとですよ……！？」"

[[dialogue]]
speaker = "トリュファイナ"
# 「傷ついた時はお癒やしして……たまに耳元でわーって叫んだり……それでも気づいてもらえなくて……」
line = "「傷ついた時はお癒やしして……たまに耳元でわーって叫んだり……それでも気づいてもらえなくて……」"

[[dialogue]]
speaker = "トリュファイナ"
# 「あの、魔王様。手を握ってもよろしいでしょうか……」
line = "「あの、魔王様。手を握ってもよろしいでしょうか……」"

[[dialogue]]
speaker = "トリュファイナ"
# 「あぁ……魔王様の手、温かいです……もう少し、このままでいさせてください……」
line = "「あぁ……魔王様の手、温かいです……もう少し、このままでいさせてください……」"

[[dialogue]]
speaker = "unk"
# 俺の魔王としての力の覚醒に伴い、限定的に霊体として再誕したというトリュファイナさん。
line = "俺の魔王としての力の覚醒に伴い、限定的に霊体として再誕したというトリュファイナさん。"

[[dialogue]]
speaker = "unk"
# 繋いだ手は温かくて、少し震えていて……これから彼女が現代で生きていけるよう、支えていこうと思うのだった──
line = "繋いだ手は温かくて、少し震えていて……これから彼女が現代で生きていけるよう、支えていこうと思うのだった──"
