[[dialogue]]
speaker = "unk"
# 第４話,君から目を離さない,P
line = "第４話,君から目を離さない,P"

[[dialogue]]
speaker = "モンスター"
# 「シャーーーッ！！」
line = "「シャーーーッ！！」"

[[dialogue]]
speaker = "梨緒"
# 「あれが今回のボスモンスターだな。強敵だが、こちらも雑魚モンスターを狩って強化は十分だ。ここであれを倒す！」
line = "「あれが今回のボスモンスターだな。強敵だが、こちらも雑魚モンスターを狩って強化は十分だ。ここであれを倒す！」"

[[dialogue]]
speaker = "アナ"
# 「させませんよ」
line = "「させませんよ」"

[[dialogue]]
speaker = "サーシャ"
# 「抜け駆けはダメよ～」
line = "「抜け駆けはダメよ～」"

[[dialogue]]
speaker = "梨緒"
# 「くっ……後ろからサーシャさんのチームが……！」
line = "「くっ……後ろからサーシャさんのチームが……！」"

[[dialogue]]
speaker = "unk"
# 梨緒の背中は俺が守る！
line = "梨緒の背中は俺が守る！"

[[dialogue]]
speaker = "梨緒"
# 「ああ、任せた！」
line = "「ああ、任せた！」"

[[dialogue]]
speaker = "梨緒"
# （今回のルールでは、モンスターと戦闘するだけでなく、他チームを攻撃して妨害することも可能だ）
line = "（今回のルールでは、モンスターと戦闘するだけでなく、他チームを攻撃して妨害することも可能だ）"

[[dialogue]]
speaker = "梨緒"
# （このままではボスモンスターとサーシャさんのチームに挟み撃ちにされた上、私たちが消耗させたボスモンスターを横取りされてしまうだろう）
line = "（このままではボスモンスターとサーシャさんのチームに挟み撃ちにされた上、私たちが消耗させたボスモンスターを横取りされてしまうだろう）"

[[dialogue]]
speaker = "梨緒"
# （だが何も考えていない訳じゃない……！）
line = "（だが何も考えていない訳じゃない……！）"

[[dialogue]]
speaker = "マトイ"
# 「出遅れちゃった！　ほら、ヴィーナスがゆっくり朝ご飯食べてるから！」
line = "「出遅れちゃった！　ほら、ヴィーナスがゆっくり朝ご飯食べてるから！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「大丈夫よ！　ここから巻き返すわ！」
line = "「大丈夫よ！　ここから巻き返すわ！」"

[[dialogue]]
speaker = "サーシャ"
# 「あら、マトイちゃんとヴィーナスちゃんが後ろから来ちゃったわ～」
line = "「あら、マトイちゃんとヴィーナスちゃんが後ろから来ちゃったわ～」"

[[dialogue]]
speaker = "アナ"
# 「迂闊でした。逆に挟まれる展開になりましたね」
line = "「迂闊でした。逆に挟まれる展開になりましたね」"

[[dialogue]]
speaker = "梨緒"
# 「ここに来るまでに、ヴィーナスたちの野営地の周りに道標を残しておいた。そろそろ来る頃だと思っていたよ」
line = "「ここに来るまでに、ヴィーナスたちの野営地の周りに道標を残しておいた。そろそろ来る頃だと思っていたよ」"

[[dialogue]]
speaker = "unk"
# ボスモンスターと３チームの乱戦だが、アナとサーシャさん、マトイとヴィーナスのチームがぶつかる形だ。
line = "ボスモンスターと３チームの乱戦だが、アナとサーシャさん、マトイとヴィーナスのチームがぶつかる形だ。"

[[dialogue]]
speaker = "unk"
# そして俺と梨緒のチームがボスの一番近くにいる。
line = "そして俺と梨緒のチームがボスの一番近くにいる。"

[[dialogue]]
speaker = "モンスター"
# 「シャーーーッ！」
line = "「シャーーーッ！」"

[[dialogue]]
speaker = "梨緒"
# 「勝つのは──私たちだ！！」
line = "「勝つのは──私たちだ！！」"

[[dialogue]]
speaker = "梨緒"
# 「私たちの勝ちだ！」
line = "「私たちの勝ちだ！」"

[[dialogue]]
speaker = "アナ"
# 「他の２チームを争わせ、その間にボスモンスターを倒すとは……作戦勝ちですね」
line = "「他の２チームを争わせ、その間にボスモンスターを倒すとは……作戦勝ちですね」"

[[dialogue]]
speaker = "梨緒"
# 「アナもサーシャさんも、その実力はよく知っているからな」
line = "「アナもサーシャさんも、その実力はよく知っているからな」"

[[dialogue]]
speaker = "梨緒"
# 「ジグを星徒会長に指名したのは他でもないサーシャさんだし、アナの優秀さは、１つ上の学年の私たちの間でも噂になっていた」
line = "「ジグを星徒会長に指名したのは他でもないサーシャさんだし、アナの優秀さは、１つ上の学年の私たちの間でも噂になっていた」"

[[dialogue]]
speaker = "梨緒"
# 「クレバーな作戦をとってくると踏んでいたから、ヴィーナスを誘導して作戦を乱させてもらった」
line = "「クレバーな作戦をとってくると踏んでいたから、ヴィーナスを誘導して作戦を乱させてもらった」"

[[dialogue]]
speaker = "サーシャ"
# 「うまくしてやられたわね～」
line = "「うまくしてやられたわね～」"

[[dialogue]]
speaker = "マトイ"
# 「う～ん、ヴィーナスの猪突猛進さを利用されちゃった……」
line = "「う～ん、ヴィーナスの猪突猛進さを利用されちゃった……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私たちの負けだわ。やるじゃない、梨緒！」
line = "「私たちの負けだわ。やるじゃない、梨緒！」"

[[dialogue]]
speaker = "リップル"
# 「皆さーん、お疲れサマでしたー！　こっちでバーベキューしましょー！」
line = "「皆さーん、お疲れサマでしたー！　こっちでバーベキューしましょー！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「やったー！　ほらみんな行きましょ！」
line = "「やったー！　ほらみんな行きましょ！」"

[[dialogue]]
speaker = "unk"
# リップルに案内され、ヴィーナスたちが海の家の方に向かっていく。
line = "リップルに案内され、ヴィーナスたちが海の家の方に向かっていく。"

[[dialogue]]
speaker = "梨緒"
# 「ふぅ……何とか勝てた。さっきは得意顔で語ってしまったが、ギリギリの勝利だったな」
line = "「ふぅ……何とか勝てた。さっきは得意顔で語ってしまったが、ギリギリの勝利だったな」"

[[dialogue]]
speaker = "unk"
# お疲れ様、梨緒
line = "お疲れ様、梨緒"

[[dialogue]]
speaker = "梨緒"
# 「ああ、お疲れ様。ありがとう。君のおかげで勝つことができたよ」
line = "「ああ、お疲れ様。ありがとう。君のおかげで勝つことができたよ」"

[[dialogue]]
speaker = "梨緒"
# 「あ、思ったより疲労が──」
line = "「あ、思ったより疲労が──」"

[[dialogue]]
speaker = "梨緒"
# 「ひゃぁっ！？」
line = "「ひゃぁっ！？」"

[[dialogue]]
speaker = "梨緒"
# 「あ……すまない……押し倒すような形になってしまった……」
line = "「あ……すまない……押し倒すような形になってしまった……」"

[[dialogue]]
speaker = "梨緒"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "梨緒"
# 「その……君とはいろいろあったな……本当にいろいろ……迷惑をかけたこともあった」
line = "「その……君とはいろいろあったな……本当にいろいろ……迷惑をかけたこともあった」"

[[dialogue]]
speaker = "梨緒"
# 「うまく言えないが……君のことは、かけがえのない存在だと思っている」
line = "「うまく言えないが……君のことは、かけがえのない存在だと思っている」"

[[dialogue]]
speaker = "unk"
# 俺もそうだよ
line = "俺もそうだよ"

[[dialogue]]
speaker = "梨緒"
# 「──！　そ、そうか……それは素直に嬉しいな……」
line = "「──！　そ、そうか……それは素直に嬉しいな……」"

[[dialogue]]
speaker = "unk"
# 俺のこと、ずっと見ていてほしい
line = "俺のこと、ずっと見ていてほしい"

[[dialogue]]
speaker = "梨緒"
# 「ずっと……か」
line = "「ずっと……か」"

[[dialogue]]
speaker = "梨緒"
# 「仕方ない。魔王が悪に堕ちないよう、監視の目が必要だからな」
line = "「仕方ない。魔王が悪に堕ちないよう、監視の目が必要だからな」"

[[dialogue]]
speaker = "アポロ"
# 「おーい、梨緒ー！」
line = "「おーい、梨緒ー！」"

[[dialogue]]
speaker = "梨緒"
# 「ひゃっ！？」
line = "「ひゃっ！？」"

[[dialogue]]
speaker = "アポロ"
# 「ん？　魔王とくっついて何やってたんだ？」
line = "「ん？　魔王とくっついて何やってたんだ？」"

[[dialogue]]
speaker = "ベアトリス"
# 「なんだかすごく親しそうに見えたけど……」
line = "「なんだかすごく親しそうに見えたけど……」"

[[dialogue]]
speaker = "ナターシャ"
# 「もしかしてお邪魔だったかな？」
line = "「もしかしてお邪魔だったかな？」"

[[dialogue]]
speaker = "梨緒"
# 「ななな、何でもない！　ちょっとこけてしまっただけだ！　それよりどうして君たちがここに？」
line = "「ななな、何でもない！　ちょっとこけてしまっただけだ！　それよりどうして君たちがここに？」"

[[dialogue]]
speaker = "アポロ"
# 「リゾート結界で面白いことやってるって聞いてな。新星星徒会とチーム戦なら、選管が受けてたつぞ！」
line = "「リゾート結界で面白いことやってるって聞いてな。新星星徒会とチーム戦なら、選管が受けてたつぞ！」"

[[dialogue]]
speaker = "ベアトリス"
# 「クイズ大会のリベンジだよ！　選管があの時とは違うってとこ、見せてあげよう！」
line = "「クイズ大会のリベンジだよ！　選管があの時とは違うってとこ、見せてあげよう！」"

[[dialogue]]
speaker = "ナターシャ"
# 「お、ベアトがやる気だ。それなら私も一肌脱がなくちゃね」
line = "「お、ベアトがやる気だ。それなら私も一肌脱がなくちゃね」"

[[dialogue]]
speaker = "梨緒"
# 「みんな……」
line = "「みんな……」"

[[dialogue]]
speaker = "梨緒"
# 「ああ、そうだな。やはりリベンジマッチは直接対決でないとな」
line = "「ああ、そうだな。やはりリベンジマッチは直接対決でないとな」"

[[dialogue]]
speaker = "梨緒"
# 「というわけだ、魔王。バーベキューが終わったら、選管と新星星徒会でもう一度勝負だ」
line = "「というわけだ、魔王。バーベキューが終わったら、選管と新星星徒会でもう一度勝負だ」"

[[dialogue]]
speaker = "梨緒"
# 「君がいるところに私がいる。君から目を離さない」
line = "「君がいるところに私がいる。君から目を離さない」"

[[dialogue]]
speaker = "梨緒"
# 「嫌と言っても、地の果てまで──いや天界だろうが平行世界だろうが追いかけてやるから、覚悟するんだな」
line = "「嫌と言っても、地の果てまで──いや天界だろうが平行世界だろうが追いかけてやるから、覚悟するんだな」"
