[[dialogue]]
speaker = "unk"
# ラブホテルの部屋中に、甘い香水の香りが満ちている。
line = "ラブホテルの部屋中に、甘い香水の香りが満ちている。"

[[dialogue]]
speaker = "unk"
# 上品な芳香の中に漂う、理性を溶かして蕩けさせる、甘く甘く淫らな香り。
line = "上品な芳香の中に漂う、理性を溶かして蕩けさせる、甘く甘く淫らな香り。"

[[dialogue]]
speaker = "unk"
# そしてペニスに与えられる、柔らかな肉による刺激は、奥歯を噛み締めなければとても堪えきれない。
line = "そしてペニスに与えられる、柔らかな肉による刺激は、奥歯を噛み締めなければとても堪えきれない。"

[[dialogue]]
speaker = "シャルレーヌ"
# 「んんぅっ<emoji=heart04>　あ、ぁ、んんっ<emoji=heart04>　ふぁあ、あぁっ、や、やぁんっ<emoji=heart04>」
line = "「んんぅっ<emoji=heart04>　あ、ぁ、んんっ<emoji=heart04>　ふぁあ、あぁっ、や、やぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そしてこの声──ひどく幼く、ひどくいやらしい喘ぎ声が、俺の射精欲を否応なしに焚きつけてくる。
line = "そしてこの声──ひどく幼く、ひどくいやらしい喘ぎ声が、俺の射精欲を否応なしに焚きつけてくる。"

[[dialogue]]
speaker = "unk"
# ふとした瞬間に気が緩むと、我慢をやめてしまいそうになるほどの……
line = "ふとした瞬間に気が緩むと、我慢をやめてしまいそうになるほどの……"

[[dialogue]]
speaker = "シャルレーヌ"
# 「まだ許可は出してませんよ、魔王様～？」
line = "「まだ許可は出してませんよ、魔王様～？」"

[[dialogue]]
speaker = "クロト"
# 「ぐうぅっ……！」
line = "「ぐうぅっ……！」"

[[dialogue]]
speaker = "unk"
# 俺の胸中を見透かしたように、シャルレーヌがリードを引く。
line = "俺の胸中を見透かしたように、シャルレーヌがリードを引く。"

[[dialogue]]
speaker = "unk"
# 気道が詰まって全身がこわばった結果、精液の発射は阻害されてしまった。
line = "気道が詰まって全身がこわばった結果、精液の発射は阻害されてしまった。"

[[dialogue]]
speaker = "unk"
# また絶妙のタイミングで、イくことができなかった……いつまで続くんだ、この焦らしは……
line = "また絶妙のタイミングで、イくことができなかった……いつまで続くんだ、この焦らしは……"

[[dialogue]]
speaker = "シャルレーヌ"
# 「魔王様？　今、私に黙ってイこうとしましたね？　何度目ですかぁ、それ？　私が『射精していい』って言うまではダメなんですからね？」
line = "「魔王様？　今、私に黙ってイこうとしましたね？　何度目ですかぁ、それ？　私が『射精していい』って言うまではダメなんですからね？」"

[[dialogue]]
speaker = "クロト"
# 「た、頼む……！　お願いだ、いい加減セックスしたい、させてくれっ……！」
line = "「た、頼む……！　お願いだ、いい加減セックスしたい、させてくれっ……！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「あっは♪　何ですかぁ、その情けない声は？　まったくもう。堪え性がないざこおち○ちんは、これだから困ります」
line = "「あっは♪　何ですかぁ、その情けない声は？　まったくもう。堪え性がないざこおち○ちんは、これだから困ります」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「お互いの呼吸を合わせる前戯は、じっくり行わないと。いつも言ってることでしょう？　ほらぁ、もっと素股しますよ～♪」
line = "「お互いの呼吸を合わせる前戯は、じっくり行わないと。いつも言ってることでしょう？　ほらぁ、もっと素股しますよ～♪」"

[[dialogue]]
speaker = "クロト"
# 「くっ……うぁああっ！　前戯って、いつまで続けるんだっ……も、もう何十分もっ！　おかしくなりそうだっ……！」
line = "「くっ……うぁああっ！　前戯って、いつまで続けるんだっ……も、もう何十分もっ！　おかしくなりそうだっ……！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「だって～、いっぱい楽しまないと損じゃないですかぁ～♪　それに、長いか短いか、それを決めるのは私ですよ？　くすくす♪」
line = "「だって～、いっぱい楽しまないと損じゃないですかぁ～♪　それに、長いか短いか、それを決めるのは私ですよ？　くすくす♪」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「仕方ない魔王様。だけど、ひとつだけ褒めてあげます」
line = "「仕方ない魔王様。だけど、ひとつだけ褒めてあげます」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「こんなにおち○ちんパンパンにさせて……ちゃあんと言いつけ通り、ここ数日間オナニーはしなかったみたいですね？」
line = "「こんなにおち○ちんパンパンにさせて……ちゃあんと言いつけ通り、ここ数日間オナニーはしなかったみたいですね？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「くふ♪　学園のみんなが知ったらどう思うでしょうね？　あの頼りがいのある星徒会長様がぁ……♪」
line = "「くふ♪　学園のみんなが知ったらどう思うでしょうね？　あの頼りがいのある星徒会長様がぁ……♪」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「附属に通う歳下の女の子に、射精管理されてるだなんて♪ ちっちゃな女の子の命令に従うの、癖になっちゃいましたかぁ？」
line = "「附属に通う歳下の女の子に、射精管理されてるだなんて♪ ちっちゃな女の子の命令に従うの、癖になっちゃいましたかぁ？」"

[[dialogue]]
speaker = "unk"
# 自慰を我慢することは辛い。後輩女子の言いなりになることも羞恥心がすさまじい。
line = "自慰を我慢することは辛い。後輩女子の言いなりになることも羞恥心がすさまじい。"

[[dialogue]]
speaker = "unk"
# けれど俺は……俺は……
line = "けれど俺は……俺は……"

[[dialogue]]
speaker = "シャルレーヌ"
# 「くふ♪　泣きそうなっちゃって……いい顔ですよ、魔王様<emoji=heart04>」
line = "「くふ♪　泣きそうなっちゃって……いい顔ですよ、魔王様<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「さてと。オナニーをしなかったご褒美。いい加減おねだりもうるさいので、あげちゃいましょうか。繋がりましょう？」
line = "「さてと。オナニーをしなかったご褒美。いい加減おねだりもうるさいので、あげちゃいましょうか。繋がりましょう？」"

[[dialogue]]
speaker = "unk"
# 手に持ったゴムを渡そうとしたが、シャルレーヌはそれより先に──
line = "手に持ったゴムを渡そうとしたが、シャルレーヌはそれより先に──"

[[dialogue]]
speaker = "シャルレーヌ"
# 「んんぅう～っ<emoji=heart04>　ふぁ、ぁあっ<emoji=heart04>　全部っ、挿入っちゃったぁ<emoji=heart04>」
line = "「んんぅう～っ<emoji=heart04>　ふぁ、ぁあっ<emoji=heart04>　全部っ、挿入っちゃったぁ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ぐううぅっ――！？」
line = "「ぐううぅっ――！？」"

[[dialogue]]
speaker = "unk"
# 避妊具も装着せずに繋がってしまった。
line = "避妊具も装着せずに繋がってしまった。"

[[dialogue]]
speaker = "unk"
# 小さい膣穴にペニスが埋まる、ただそれだけで意識が飛ぶほどの快感が押し寄せる。
line = "小さい膣穴にペニスが埋まる、ただそれだけで意識が飛ぶほどの快感が押し寄せる。"

[[dialogue]]
speaker = "unk"
# そして竿の中をずりずりと精液が登ってきて──
line = "そして竿の中をずりずりと精液が登ってきて──"

[[dialogue]]
speaker = "シャルレーヌ"
# 「まさか挿入しただけでイっちゃうわけないですよねぇ？」
line = "「まさか挿入しただけでイっちゃうわけないですよねぇ？」"

[[dialogue]]
speaker = "クロト"
# 「──！」
line = "「──！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「もしイっちゃったらどうしましょうか。玩具にする価値もないですし……捨てちゃおっかな？」
line = "「もしイっちゃったらどうしましょうか。玩具にする価値もないですし……捨てちゃおっかな？」"

[[dialogue]]
speaker = "クロト"
# 「――――――――！？！？」
line = "「――――――――！？！？」"

[[dialogue]]
speaker = "unk"
# 気づいたときには、全力で歯を食いしばっていた。
line = "気づいたときには、全力で歯を食いしばっていた。"

[[dialogue]]
speaker = "unk"
# 竿の部分を通過しつつあった精液を必死に押しとどめる。
line = "竿の部分を通過しつつあった精液を必死に押しとどめる。"

[[dialogue]]
speaker = "シャルレーヌ"
# 「くふふふっ<emoji=heart04>　何だかおち○ちんがビクビクしてましたけどぉ……射精はしなかったみたいですね？」
line = "「くふふふっ<emoji=heart04>　何だかおち○ちんがビクビクしてましたけどぉ……射精はしなかったみたいですね？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「流石は会長さんです♪　かっこいい<emoji=heart04>　素敵<emoji=heart04>　私、感動しちゃいました♪」
line = "「流石は会長さんです♪　かっこいい<emoji=heart04>　素敵<emoji=heart04>　私、感動しちゃいました♪」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「私、我慢強い男の人って大好きなんです♪　ですからぁ～……」
line = "「私、我慢強い男の人って大好きなんです♪　ですからぁ～……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「もっともっと、我慢できるところぉ……見せて<emoji=heart04>　んっしょ、んんぅっ、しょっ<emoji=heart04>」
line = "「もっともっと、我慢できるところぉ……見せて<emoji=heart04>　んっしょ、んんぅっ、しょっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「あぅ、うあ、あぁあっ……！？」
line = "「あぅ、うあ、あぁあっ……！？」"

[[dialogue]]
speaker = "unk"
# シャルレーヌの膣内がリズミカルに上下を始め、あり得ないほどの締め付けと摩擦が襲いかかってくる。
line = "シャルレーヌの膣内がリズミカルに上下を始め、あり得ないほどの締め付けと摩擦が襲いかかってくる。"

[[dialogue]]
speaker = "シャルレーヌ"
# 「おち○ちんのぉ、つよつよなところ♪　見～せてっ、ほら、ほら、ほらっ♪」
line = "「おち○ちんのぉ、つよつよなところ♪　見～せてっ、ほら、ほら、ほらっ♪」"

[[dialogue]]
speaker = "unk"
# まるで我慢させる気のない、情け容赦なしのピストン──
line = "まるで我慢させる気のない、情け容赦なしのピストン──"

[[dialogue]]
speaker = "クロト"
# 「ま、待ってくれ、そんなにされたら、出る、出るから、ぁあぁあっ……！」
line = "「ま、待ってくれ、そんなにされたら、出る、出るから、ぁあぁあっ……！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「え～？　まだぁ、んんっ<emoji=heart04>　何回かぱんぱんしただけじゃないですかぁ<emoji=heart04>　会長さん、そーろーなんですかぁ？」
line = "「え～？　まだぁ、んんっ<emoji=heart04>　何回かぱんぱんしただけじゃないですかぁ<emoji=heart04>　会長さん、そーろーなんですかぁ？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「限界が来るの早すぎません？　ざぁこ<emoji=heart04>　ざこっ<emoji=heart04>　くそざこっ<emoji=heart04>　女の子に手加減を懇願してぇ、恥ずかしくないんですか？」
line = "「限界が来るの早すぎません？　ざぁこ<emoji=heart04>　ざこっ<emoji=heart04>　くそざこっ<emoji=heart04>　女の子に手加減を懇願してぇ、恥ずかしくないんですか？」"

[[dialogue]]
speaker = "クロト"
# 「でもっ、だって、ぁ──か、はっ……！」
line = "「でもっ、だって、ぁ──か、はっ……！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「シャルレーヌはぁ、まだ附属生になったばかりのー、ちっちゃい女の子なんですよ？」
line = "「シャルレーヌはぁ、まだ附属生になったばかりのー、ちっちゃい女の子なんですよ？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ほらぁ、体だってこんなに小さいのにぃ……<emoji=heart04>」
line = "「ほらぁ、体だってこんなに小さいのにぃ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# にやりと笑うシャルレーヌが、バストやヒップを強調するように体をくねらせてアピールしてくる。
line = "にやりと笑うシャルレーヌが、バストやヒップを強調するように体をくねらせてアピールしてくる。"

[[dialogue]]
speaker = "unk"
# だが小さいのは身長だけだ。
line = "だが小さいのは身長だけだ。"

[[dialogue]]
speaker = "unk"
# 形のいい乳房は同年代の子に比べてもずっと大きい。きゅっと括れた腰回りからのヒップラインはすでに女性のそれだ。
line = "形のいい乳房は同年代の子に比べてもずっと大きい。きゅっと括れた腰回りからのヒップラインはすでに女性のそれだ。"

[[dialogue]]
speaker = "unk"
# アンバランスな魅力に興奮を抑えきれない。
line = "アンバランスな魅力に興奮を抑えきれない。"

[[dialogue]]
speaker = "シャルレーヌ"
# 「会長さん？　すっごいいやらしい視線を感じるんですけどー？　舐め回すように見ないでくれますかぁ？」
line = "「会長さん？　すっごいいやらしい視線を感じるんですけどー？　舐め回すように見ないでくれますかぁ？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「エロすぎるから目が離せない～って顔してる♪　変態<emoji=heart04>　スケベ<emoji=heart04>　おち○ちん、どれだけもじもじさせれば気がすむんですかぁ？」
line = "「エロすぎるから目が離せない～って顔してる♪　変態<emoji=heart04>　スケベ<emoji=heart04>　おち○ちん、どれだけもじもじさせれば気がすむんですかぁ？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「勝手に射精したら許しませんよ？　そしたら会長さんのこと……おトイレにしちゃいますからね？」
line = "「勝手に射精したら許しませんよ？　そしたら会長さんのこと……おトイレにしちゃいますからね？」"

[[dialogue]]
speaker = "クロト"
# 「！？　それは、あ、あんまり、だっ……」
line = "「！？　それは、あ、あんまり、だっ……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「嫌だったら言うこと聞きましょうね？　くすくす<emoji=heart04>」
line = "「嫌だったら言うこと聞きましょうね？　くすくす<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「はあっ、はぁっ……！　ふう、ふぅうっ、ふーっ！」
line = "「はあっ、はぁっ……！　ふう、ふぅうっ、ふーっ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「呼吸荒すぎ～っ<emoji=heart04>　気持ち悪～い<emoji=heart04>　はぁはぁ言って……ちんぽ、ビクビクさせて～<emoji=heart04>　この変態<emoji=heart04>　スケベち○ぽ<emoji=heart04>」
line = "「呼吸荒すぎ～っ<emoji=heart04>　気持ち悪～い<emoji=heart04>　はぁはぁ言って……ちんぽ、ビクビクさせて～<emoji=heart04>　この変態<emoji=heart04>　スケベち○ぽ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# シャルレーヌのような小さな女の子に似つかわしくない淫語が耳に染み込むたび、ぞくぞくと背筋が震える。
line = "シャルレーヌのような小さな女の子に似つかわしくない淫語が耳に染み込むたび、ぞくぞくと背筋が震える。"

[[dialogue]]
speaker = "シャルレーヌ"
# 「あっ、あっ、あっ、あぁん<emoji=heart04>　おち○ちんおっきい<emoji=heart04>　シャルレーヌのおま○こいっぱいになってるぅ<emoji=heart04>」
line = "「あっ、あっ、あっ、あぁん<emoji=heart04>　おち○ちんおっきい<emoji=heart04>　シャルレーヌのおま○こいっぱいになってるぅ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# わざとらしい甘い喘ぎも俺の情欲を揺さぶる。
line = "わざとらしい甘い喘ぎも俺の情欲を揺さぶる。"

[[dialogue]]
speaker = "unk"
# 興奮と我慢の連続で、指先にも力が入らなくなってきた──
line = "興奮と我慢の連続で、指先にも力が入らなくなってきた──"

[[dialogue]]
speaker = "シャルレーヌ"
# 「こらぁ、コンドーム落としちゃ駄目ですよ？　必要な時が来たら使うんですから、ちゃあんと大切に持っててください？」
line = "「こらぁ、コンドーム落としちゃ駄目ですよ？　必要な時が来たら使うんですから、ちゃあんと大切に持っててください？」"

[[dialogue]]
speaker = "クロト"
# 「も、もう使ってくれっ……お願いだっ……」
line = "「も、もう使ってくれっ……お願いだっ……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「嫌で～す。ゴムが無い方が気持ちいいんですから。射精前に着ければ問題ないでしょ？」
line = "「嫌で～す。ゴムが無い方が気持ちいいんですから。射精前に着ければ問題ないでしょ？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「それとも会長さんのは、勝手に中出ししちゃう無責任ざこざこおち○ぽなんですぅ～？」
line = "「それとも会長さんのは、勝手に中出ししちゃう無責任ざこざこおち○ぽなんですぅ～？」"

[[dialogue]]
speaker = "クロト"
# 「ほ、本当に出そうなんだっ……！　早く抜いて、着けてくれっ！」
line = "「ほ、本当に出そうなんだっ……！　早く抜いて、着けてくれっ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「うるさい<emoji=heart04>　お前が出すな<emoji=heart04>　いい？　出・す・な<emoji=heart04>」
line = "「うるさい<emoji=heart04>　お前が出すな<emoji=heart04>　いい？　出・す・な<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ぁあ、ぁああああ…………！！」
line = "「ぁあ、ぁああああ…………！！」"

[[dialogue]]
speaker = "unk"
# 『出すな』と命令してくるのに、シャルレーヌは腰の動きを少しも弱めてくれない。
line = "『出すな』と命令してくるのに、シャルレーヌは腰の動きを少しも弱めてくれない。"

[[dialogue]]
speaker = "unk"
# ひねり、ねじり、膣内にもランダムに圧力をかけてペニスを悦ばせておきながら──
line = "ひねり、ねじり、膣内にもランダムに圧力をかけてペニスを悦ばせておきながら──"

[[dialogue]]
speaker = "シャルレーヌ"
# 「絶対に出すな<emoji=heart04>　出すな<emoji=heart04>　我慢しろ<emoji=heart04>　ざこち○ぽを甘やかすな<emoji=heart04>　出すな、出すな、出すな<emoji=heart04>」
line = "「絶対に出すな<emoji=heart04>　出すな<emoji=heart04>　我慢しろ<emoji=heart04>　ざこち○ぽを甘やかすな<emoji=heart04>　出すな、出すな、出すな<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「うぅううっ！？」
line = "「うぅううっ！？」"

[[dialogue]]
speaker = "unk"
# シャルレーヌがまたリードを引っ張った。
line = "シャルレーヌがまたリードを引っ張った。"

[[dialogue]]
speaker = "unk"
# 幾度、このひどい行為をされただろう。
line = "幾度、このひどい行為をされただろう。"

[[dialogue]]
speaker = "unk"
# 射精を必死で我慢している最中に、息苦しくなるこの感覚は、本当に、本当に――
line = "射精を必死で我慢している最中に、息苦しくなるこの感覚は、本当に、本当に――"

[[dialogue]]
speaker = "シャルレーヌ"
# 「あはぁっ……<emoji=heart04>　おち○ちん、ビキビキぃ～っ<emoji=heart04>　って硬くなった<emoji=heart04>」
line = "「あはぁっ……<emoji=heart04>　おち○ちん、ビキビキぃ～っ<emoji=heart04>　って硬くなった<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 気持ちがいい……！
line = "気持ちがいい……！"

[[dialogue]]
speaker = "シャルレーヌ"
# 「苦しいのが気持ちいいんだぁ<emoji=heart04>　手玉に取られるのが堪らないのねぇ、このド変態<emoji=heart04>　気持ち悪い<emoji=heart04>　マゾ魔王<emoji=heart04>」
line = "「苦しいのが気持ちいいんだぁ<emoji=heart04>　手玉に取られるのが堪らないのねぇ、このド変態<emoji=heart04>　気持ち悪い<emoji=heart04>　マゾ魔王<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「もっと見せろ<emoji=heart04>　必死に我慢する情けない顔、見せろっ<emoji=heart04>　ほら、ほら、ほらほらほらっ……！」
line = "「もっと見せろ<emoji=heart04>　必死に我慢する情けない顔、見せろっ<emoji=heart04>　ほら、ほら、ほらほらほらっ……！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「んんぁっ、はぁ、んんぅっ<emoji=heart04>　おち○ちん暴れすぎ～<emoji=heart04>　おま○この中でまた膨らんだぁ<emoji=heart04>　やぁん、種付けされちゃう～っ<emoji=heart04>」
line = "「んんぁっ、はぁ、んんぅっ<emoji=heart04>　おち○ちん暴れすぎ～<emoji=heart04>　おま○この中でまた膨らんだぁ<emoji=heart04>　やぁん、種付けされちゃう～っ<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「あぁん、種付けって言ったらまたおち○ちんビクッてしたぁ<emoji=heart04>　会長さんのおち○ちん、正直なんですからぁ～<emoji=heart04>」
line = "「あぁん、種付けって言ったらまたおち○ちんビクッてしたぁ<emoji=heart04>　会長さんのおち○ちん、正直なんですからぁ～<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「はぁあぅっ<emoji=heart04>　あ、んんぅ<emoji=heart04>　あ、ぁあん、んんぁ、はぁ、んぁあっ、あぁっ、はぁっ、あんっ、あんっ<emoji=heart04>」
line = "「はぁあぅっ<emoji=heart04>　あ、んんぅ<emoji=heart04>　あ、ぁあん、んんぁ、はぁ、んぁあっ、あぁっ、はぁっ、あんっ、あんっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「っ……ううぅっ……！」
line = "「っ……ううぅっ……！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ん～、ふふ<emoji=heart04>　会長さんってば涎まで垂らして呻いちゃって……気持ち悪ぅい<emoji=heart04>」
line = "「ん～、ふふ<emoji=heart04>　会長さんってば涎まで垂らして呻いちゃって……気持ち悪ぅい<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「このまま無責任ぴゅっぴゅでぇ、女の子を孕ませるつもりですかぁ？」
line = "「このまま無責任ぴゅっぴゅでぇ、女の子を孕ませるつもりですかぁ？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「シャルレーヌのとろとろおま○こにぃ、ぶびゅっ<emoji=heart04>　びゅるびゅるーっ<emoji=heart04>　するつもりなんですかぁ～？」
line = "「シャルレーヌのとろとろおま○こにぃ、ぶびゅっ<emoji=heart04>　びゅるびゅるーっ<emoji=heart04>　するつもりなんですかぁ～？」"

[[dialogue]]
speaker = "クロト"
# 「くっ……それは駄目だ、ゴム、着けよう……」
line = "「くっ……それは駄目だ、ゴム、着けよう……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「それが人にお願いする態度ですかぁ、魔王様？」
line = "「それが人にお願いする態度ですかぁ、魔王様？」"

[[dialogue]]
speaker = "クロト"
# 「しゃ、シャルレーヌ、様っ……どうかゴムを、着けさせてくださいっ……もう我慢、できないんです、出てしまいますっ……！」
line = "「しゃ、シャルレーヌ、様っ……どうかゴムを、着けさせてくださいっ……もう我慢、できないんです、出てしまいますっ……！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「──知るか<emoji=heart04>」
line = "「──知るか<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「そんなっ──本当に、出る、出る出る、出るっ……！？」
line = "「そんなっ──本当に、出る、出る出る、出るっ……！？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「うるさいですよ、マゾ魔王様？　私の言うこと、聞けないんですか？」
line = "「うるさいですよ、マゾ魔王様？　私の言うこと、聞けないんですか？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「我慢しろ、我慢しろ、我慢しろっ<emoji=heart04>　射精も我慢できないのっ<emoji=heart04>　できるでしょっ<emoji=heart04>　この変態魔王、マゾ騎士っ<emoji=heart04>」
line = "「我慢しろ、我慢しろ、我慢しろっ<emoji=heart04>　射精も我慢できないのっ<emoji=heart04>　できるでしょっ<emoji=heart04>　この変態魔王、マゾ騎士っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ペニスにどれだけ力を込めても、もう無理だ。精液を押し返せない。
line = "ペニスにどれだけ力を込めても、もう無理だ。精液を押し返せない。"

[[dialogue]]
speaker = "unk"
# 睾丸が引き攣り、肉棒の内側をずりずりと登ってくる精液の存在を、シャルレーヌも当然気づいていて──
line = "睾丸が引き攣り、肉棒の内側をずりずりと登ってくる精液の存在を、シャルレーヌも当然気づいていて──"

[[dialogue]]
speaker = "クロト"
# 「う、うあぁ、あっ、あーっ！　ああぁ、ぁあ、あぁああーっ！」
line = "「う、うあぁ、あっ、あーっ！　ああぁ、ぁあ、あぁああーっ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「あっははははっ<emoji=heart04>　すっごい声～♪　ばぁか<emoji=heart04>　そのまま情けない顔でイけっ<emoji=heart04>　びゅーしろっ<emoji=heart04>　しろしろっ、しろ～っ<emoji=heart04>」
line = "「あっははははっ<emoji=heart04>　すっごい声～♪　ばぁか<emoji=heart04>　そのまま情けない顔でイけっ<emoji=heart04>　びゅーしろっ<emoji=heart04>　しろしろっ、しろ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「んんんんんう～～～ッ<emoji=heart04><emoji=heart04>」
line = "「んんんんんう～～～ッ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 何十分と焦らされたペニスが、文字通り爆発した。
line = "何十分と焦らされたペニスが、文字通り爆発した。"

[[dialogue]]
speaker = "unk"
# のたうち回るみたいな、吹き散らすような、不様な射精……
line = "のたうち回るみたいな、吹き散らすような、不様な射精……"

[[dialogue]]
speaker = "シャルレーヌ"
# 「はぁあっ……あぁんっ<emoji=heart04>　出しちゃったぁ……<emoji=heart04>　我慢できなかったんだぁ……ひっどぉい、コンドーム着ける暇もなかったぁ……<emoji=heart04>」
line = "「はぁあっ……あぁんっ<emoji=heart04>　出しちゃったぁ……<emoji=heart04>　我慢できなかったんだぁ……ひっどぉい、コンドーム着ける暇もなかったぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「遠慮なさすぎ～……どびゅどびゅ、びゅるびゅるって<emoji=heart04>　おもらしするみたいにぶちまけちゃってぇっ……鬼畜ぅ<emoji=heart04>　さっすが魔王様<emoji=heart04>」
line = "「遠慮なさすぎ～……どびゅどびゅ、びゅるびゅるって<emoji=heart04>　おもらしするみたいにぶちまけちゃってぇっ……鬼畜ぅ<emoji=heart04>　さっすが魔王様<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「そ、そんな……うぅ……」
line = "「そ、そんな……うぅ……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「あぁん、お腹熱いぃ<emoji=heart04>　そんなにちっちゃな女の子を孕ませたいんだぁ～<emoji=heart04>　んんっ……ほんとに会長さんの赤ちゃんできちゃう～<emoji=heart04>」
line = "「あぁん、お腹熱いぃ<emoji=heart04>　そんなにちっちゃな女の子を孕ませたいんだぁ～<emoji=heart04>　んんっ……ほんとに会長さんの赤ちゃんできちゃう～<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「無責任ぴゅっぴゅするの、さぞかし気持ちいいでしょうねぇ～<emoji=heart04>　くすくすくす<emoji=heart04>」
line = "「無責任ぴゅっぴゅするの、さぞかし気持ちいいでしょうねぇ～<emoji=heart04>　くすくすくす<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ん……ふー……ふぅうー……ようやく収まった、ところでぇ……おしおきの時間ですよ、魔王様？」
line = "「ん……ふー……ふぅうー……ようやく収まった、ところでぇ……おしおきの時間ですよ、魔王様？」"

[[dialogue]]
speaker = "クロト"
# 「え……」
line = "「え……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「私は『射精していい』とは一言も言っていませんよ～？　聞いてませんでしたか、おバカさん♪」
line = "「私は『射精していい』とは一言も言っていませんよ～？　聞いてませんでしたか、おバカさん♪」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「無許可の中出しをした罰。シャルレーヌのっ……おトイレになりなさい<emoji=heart04>　ん、んんぅっ──<emoji=heart04>」
line = "「無許可の中出しをした罰。シャルレーヌのっ……おトイレになりなさい<emoji=heart04>　ん、んんぅっ──<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「う、ぅうう──っ！！」
line = "「う、ぅうう──っ！！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「はぁあぁっ、んん、んんぅ、ふぅうっ……<emoji=heart04>」
line = "「はぁあぁっ、んん、んんぅ、ふぅうっ……<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「き、気持ち、ぃいっ……<emoji=heart04>　んん<emoji=heart04>　会長さんにおしっこ、かけるのっ……最っ高っ<emoji=heart04>　はぁ、あぁああ～～～っ……<emoji=heart04>」
line = "「き、気持ち、ぃいっ……<emoji=heart04>　んん<emoji=heart04>　会長さんにおしっこ、かけるのっ……最っ高っ<emoji=heart04>　はぁ、あぁああ～～～っ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 精液をしとどにぶちまけて、火照り切った体に浴びせられる、シャルレーヌの温かいおしっこ。
line = "精液をしとどにぶちまけて、火照り切った体に浴びせられる、シャルレーヌの温かいおしっこ。"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ん……は……はぁ<emoji=heart04>　女の子のおトイレにされるの、どんな気持ちですかぁ～？」
line = "「ん……は……はぁ<emoji=heart04>　女の子のおトイレにされるの、どんな気持ちですかぁ～？」"

[[dialogue]]
speaker = "unk"
# 汗だくの体にシャワーを浴びるみたいな爽快感さえ覚えてしまう……なんでこんなに屈辱的で、気持ちがいいんだ……
line = "汗だくの体にシャワーを浴びるみたいな爽快感さえ覚えてしまう……なんでこんなに屈辱的で、気持ちがいいんだ……"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ん、んん……おしっこかけられて、おち○ちん硬くなってるしっ……ほんっと変態なんだから……<emoji=heart04>」
line = "「ん、んん……おしっこかけられて、おち○ちん硬くなってるしっ……ほんっと変態なんだから……<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「そんななっさけない目で見なくても大丈夫ですよ？　逃がしませんから。もっともっと滅茶苦茶にしてあげます」
line = "「そんななっさけない目で見なくても大丈夫ですよ？　逃がしませんから。もっともっと滅茶苦茶にしてあげます」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「私の、私だけの……魔王様<emoji=heart04>」
line = "「私の、私だけの……魔王様<emoji=heart04>」"
