[[dialogue]]
speaker = "unk"
# 第３話,行列のできるおみくじ屋さん,P
line = "第３話,行列のできるおみくじ屋さん,P"

[[dialogue]]
speaker = "unk"
# 通学路の一角にできた大勢の人だかり。何の騒ぎだろうと覗き込んだその輪の中心にいたのは──
line = "通学路の一角にできた大勢の人だかり。何の騒ぎだろうと覗き込んだその輪の中心にいたのは──"

[[dialogue]]
speaker = "unk"
# まさかの晴れ着姿のトリシャさんだった。
line = "まさかの晴れ着姿のトリシャさんだった。"

[[dialogue]]
speaker = "女の子"
# 「トリシャさん、私も占ってくださーい！」
line = "「トリシャさん、私も占ってくださーい！」"

[[dialogue]]
speaker = "トリシャ"
# 「あ、慌てないでください……並んでください……ちゃんと視ますので……全員……」
line = "「あ、慌てないでください……並んでください……ちゃんと視ますので……全員……」"

[[dialogue]]
speaker = "トリシャ"
# 「ひぇ……やっぱり、明るい内から出かけたのは失敗でした……あっ……！　た、助けてください……」
line = "「ひぇ……やっぱり、明るい内から出かけたのは失敗でした……あっ……！　た、助けてください……」"

[[dialogue]]
speaker = "unk"
# 何があったんです……？
line = "何があったんです……？"

[[dialogue]]
speaker = "トリシャ"
# 「私にもわかりません……急に、私の元に人が押し寄せてきまして……あ、あの……何故……？」
line = "「私にもわかりません……急に、私の元に人が押し寄せてきまして……あ、あの……何故……？」"

[[dialogue]]
speaker = "女の子"
# 「占星術師のトリシャさんですよね？　占いがよく当たるってみんなが言ってました！」
line = "「占星術師のトリシャさんですよね？　占いがよく当たるってみんなが言ってました！」"

[[dialogue]]
speaker = "トリシャ"
# 「口コミですか……なるほど……それは嬉しいのですが……」
line = "「口コミですか……なるほど……それは嬉しいのですが……」"

[[dialogue]]
speaker = "トリシャ"
# 「ここでおみくじをしていたら、通行の邪魔になってしまいます……どこかいいところはないでしょうか……？」
line = "「ここでおみくじをしていたら、通行の邪魔になってしまいます……どこかいいところはないでしょうか……？」"

[[dialogue]]
speaker = "unk"
# それなら──
line = "それなら──"

[[dialogue]]
speaker = "トリシャ"
# 「え……？　星徒会室……？」
line = "「え……？　星徒会室……？」"

[[dialogue]]
speaker = "トリシャ"
# 「まさか会長権限で、星徒会室をおみくじ小屋として解放するとは……驚きです」
line = "「まさか会長権限で、星徒会室をおみくじ小屋として解放するとは……驚きです」"

[[dialogue]]
speaker = "トリシャ"
# 「ですがここでしたら、心おきなく<ruby=みくじ>神籤</ruby>れます……場所の提供、感謝いたします……」
line = "「ですがここでしたら、心おきなく<ruby>神籤<rt>みくじ</rt></ruby>れます……場所の提供、感謝いたします……」"

[[dialogue]]
speaker = "トリシャ"
# 「では次の方……」
line = "「では次の方……」"

[[dialogue]]
speaker = "トリシャ"
# 「中吉ですね……失せ物は必ずや見つかることでしょう……ちなみに、床下の収納はお探しになりましたか……？」
line = "「中吉ですね……失せ物は必ずや見つかることでしょう……ちなみに、床下の収納はお探しになりましたか……？」"

[[dialogue]]
speaker = "トリシャ"
# 「次の方は……大吉、ですね……おめでとうございます……。特に金運が好調と出ています……ところで、年末に購入した宝くじをお忘れではありませんか……」
line = "「次の方は……大吉、ですね……おめでとうございます……。特に金運が好調と出ています……ところで、年末に購入した宝くじをお忘れではありませんか……」"

[[dialogue]]
speaker = "トリシャ"
# 「あなたの恋愛運は……吉……途切れた縁が再び繋がる……と出ています。元々、勘違いが原因ですので……お相手に妹さんがいないか、今一度、確認されてみては……？」
line = "「あなたの恋愛運は……吉……途切れた縁が再び繋がる……と出ています。元々、勘違いが原因ですので……お相手に妹さんがいないか、今一度、確認されてみては……？」"

[[dialogue]]
speaker = "unk"
# トリシャさん、そろそろ休憩しなくて大丈夫？
line = "トリシャさん、そろそろ休憩しなくて大丈夫？"

[[dialogue]]
speaker = "トリシャ"
# 「はい……いつもの占いよりは……幾分か工程と内容を簡略化していますので」
line = "「はい……いつもの占いよりは……幾分か工程と内容を簡略化していますので」"

[[dialogue]]
speaker = "トリシャ"
# 「しかし頼まれると、断るのが苦手なもので……そろそろ、少しは列が短くなったのではないでしょうか……」
line = "「しかし頼まれると、断るのが苦手なもので……そろそろ、少しは列が短くなったのではないでしょうか……」"

[[dialogue]]
speaker = "unk"
# いや、むしろ列が伸びてるかも……
line = "いや、むしろ列が伸びてるかも……"

[[dialogue]]
speaker = "トリシャ"
# 「なるほど、口コミがさらに広がっていると……レゾフでは、ここまで人気になることはなかったのですが……驚きです」
line = "「なるほど、口コミがさらに広がっていると……レゾフでは、ここまで人気になることはなかったのですが……驚きです」"

[[dialogue]]
speaker = "トリシャ"
# 「ですが、私のおみくじが人の役に立つのでしたら……少しくらい無理をしましょう……」
line = "「ですが、私のおみくじが人の役に立つのでしたら……少しくらい無理をしましょう……」"

[[dialogue]]
speaker = "unk"
# 夕方になり、おみくじを望む人の波はようやく引いた。
line = "夕方になり、おみくじを望む人の波はようやく引いた。"

[[dialogue]]
speaker = "トリシャ"
# 「ふう……新年早々、１年分の会話を交わしてしまいました……キャパシティオーバーです……」
line = "「ふう……新年早々、１年分の会話を交わしてしまいました……キャパシティオーバーです……」"

[[dialogue]]
speaker = "トリシャ"
# 「お気持ち程度の占い料でしたが……積もり積もって、それなりの額になってしまいました……」
line = "「お気持ち程度の占い料でしたが……積もり積もって、それなりの額になってしまいました……」"

[[dialogue]]
speaker = "unk"
# 初穂料ですね
line = "初穂料ですね"

[[dialogue]]
speaker = "トリシャ"
# 「初穂料という呼び名があるのですね……なんとなく響きがいい……雅です……」
line = "「初穂料という呼び名があるのですね……なんとなく響きがいい……雅です……」"

[[dialogue]]
speaker = "トリシャ"
# 「こんな時間になってしまいましたが、数多の人を導けました……占い師、冥利に尽きます……」
line = "「こんな時間になってしまいましたが、数多の人を導けました……占い師、冥利に尽きます……」"

[[dialogue]]
speaker = "トリシャ"
# 「それに、学園の方々と、少し、友達になりました……占いの後に、一緒に写真を撮ったりとか……にへへ」
line = "「それに、学園の方々と、少し、友達になりました……占いの後に、一緒に写真を撮ったりとか……にへへ」"

[[dialogue]]
speaker = "トリシャ"
# 「美味しい焼きたてパンのお店を、教えてもらえることになりました……楽しみです……」
line = "「美味しい焼きたてパンのお店を、教えてもらえることになりました……楽しみです……」"

[[dialogue]]
speaker = "トリシャ"
# 「……？　あなたも笑っていますね……？」
line = "「……？　あなたも笑っていますね……？」"

[[dialogue]]
speaker = "トリシャ"
# 「トリシャさんが嬉しそうにしてると、俺も嬉しい……？　そ、そうですか……」
line = "「トリシャさんが嬉しそうにしてると、俺も嬉しい……？　そ、そうですか……」"

[[dialogue]]
speaker = "トリシャ"
# 「そうです……よろしければ、あなたも占いましょうか……？」
line = "「そうです……よろしければ、あなたも占いましょうか……？」"

[[dialogue]]
speaker = "unk"
# お疲れのところ悪いけど、いいですか？
line = "お疲れのところ悪いけど、いいですか？"

[[dialogue]]
speaker = "トリシャ"
# 「もちろんです、喜んで……カシャカシャ」
line = "「もちろんです、喜んで……カシャカシャ」"

[[dialogue]]
speaker = "トリシャ"
# 「出ました……これはなんと……今日一番の眩い光……！　あなたの今年の運勢は……大吉では到底言い表せないほどの幸運……いうなれば、超吉……！」
line = "「出ました……これはなんと……今日一番の眩い光……！　あなたの今年の運勢は……大吉では到底言い表せないほどの幸運……いうなれば、超吉……！」"

[[dialogue]]
speaker = "トリシャ"
# 「異性と外出をすることで、更なる運が開ける……と出ています……」
line = "「異性と外出をすることで、更なる運が開ける……と出ています……」"

[[dialogue]]
speaker = "unk"
# 一緒に初詣に行きましょう、トリシャさん
line = "一緒に初詣に行きましょう、トリシャさん"

[[dialogue]]
speaker = "unk"
# それなら、ちょうど良かった
line = "それなら、ちょうど良かった"

[[dialogue]]
speaker = "トリシャ"
# 「は、はいっ……喜んで、参りましょう……！」
line = "「は、はいっ……喜んで、参りましょう……！」"

[[dialogue]]
speaker = "unk"
# そもそもトリシャさんに街中で遭遇したのも、彼女を初詣に誘おうと向かっていた道中だ。
line = "そもそもトリシャさんに街中で遭遇したのも、彼女を初詣に誘おうと向かっていた道中だ。"

[[dialogue]]
speaker = "unk"
# 即ＯＫしてもらえた俺の今年の運勢は、彼女が言う通りの超吉なのかもしれない。
line = "即ＯＫしてもらえた俺の今年の運勢は、彼女が言う通りの超吉なのかもしれない。"
