[[dialogue]]
speaker = "unk"
# 第１話,おなか部の小さな部長さん,P
line = "第１話,おなか部の小さな部長さん,P"

[[dialogue]]
speaker = "？？？"
# 「おーい……おーい……にゃ～お……にゃ～お……」
line = "「おーい……おーい……にゃ～お……にゃ～お……」"

[[dialogue]]
speaker = "？？？"
# 「あう、ここにもいないみたい……」
line = "「あう、ここにもいないみたい……」"

[[dialogue]]
speaker = "unk"
# そんな狭い路地に潜り込んで何をしてるんだ？
line = "そんな狭い路地に潜り込んで何をしてるんだ？"

[[dialogue]]
speaker = "モナカ"
# 「ふぇ！？　星徒会長さんっ……？　ご、ごめんなさい、これは、その、変なことをしてたわけじゃなくて……！」
line = "「ふぇ！？　星徒会長さんっ……？　ご、ごめんなさい、これは、その、変なことをしてたわけじゃなくて……！」"

[[dialogue]]
speaker = "モナカ"
# 「モナカね、おなか部の部長さんで、今はその、活動中で……」
line = "「モナカね、おなか部の部長さんで、今はその、活動中で……」"

[[dialogue]]
speaker = "モナカ"
# 「あっ、ご、ごめんなさい……。おなか部じゃわからないよね。正式には、お悩み解決倶楽部って名前で……。部に届いたお悩みを解決するっていう活動をしてて……」
line = "「あっ、ご、ごめんなさい……。おなか部じゃわからないよね。正式には、お悩み解決倶楽部って名前で……。部に届いたお悩みを解決するっていう活動をしてて……」"

[[dialogue]]
speaker = "モナカ"
# 「飼ってる子猫さんがお家から逃げだしちゃったって相談が届いたの……。猫さんって狭いところや暗いところが好きだから、路地にいるかなぁって思って、それで……」
line = "「飼ってる子猫さんがお家から逃げだしちゃったって相談が届いたの……。猫さんって狭いところや暗いところが好きだから、路地にいるかなぁって思って、それで……」"

[[dialogue]]
speaker = "モナカ"
# 「あう……口下手でごめんなさい。とにかく子猫さんを探してて……。だから、えと、その……」
line = "「あう……口下手でごめんなさい。とにかく子猫さんを探してて……。だから、えと、その……」"

[[dialogue]]
speaker = "モナカ"
# 「え……？　手伝ってくれるの……？　い、いいよ、これはおなか部に届いた依頼だから……」
line = "「え……？　手伝ってくれるの……？　い、いいよ、これはおなか部に届いた依頼だから……」"

[[dialogue]]
speaker = "モナカ"
# 「星徒会長さんはモンスター退治とかもっと大変な事件を解決しなくちゃいけないだろうし……。こういう相談はプリマステラじゃないモナカに任せてくれれば……」
line = "「星徒会長さんはモンスター退治とかもっと大変な事件を解決しなくちゃいけないだろうし……。こういう相談はプリマステラじゃないモナカに任せてくれれば……」"

[[dialogue]]
speaker = "モナカ"
# 「あ……！　ほ、本当にいいから、そんな狭い路地なんかに潜り込んだら制服汚れちゃうよっ……。モナカだけで十分だから……」
line = "「あ……！　ほ、本当にいいから、そんな狭い路地なんかに潜り込んだら制服汚れちゃうよっ……。モナカだけで十分だから……」"

[[dialogue]]
speaker = "モナカ"
# 「あう……。確かに１人より２人の方が早く見つかるかもしれないけど……」
line = "「あう……。確かに１人より２人の方が早く見つかるかもしれないけど……」"

[[dialogue]]
speaker = "モナカ"
# 「時間も、その……。すごく取らせちゃうかもしれないよ……？　こういうのってとっても地道に探すことになっちゃうから……」
line = "「時間も、その……。すごく取らせちゃうかもしれないよ……？　こういうのってとっても地道に探すことになっちゃうから……」"

[[dialogue]]
speaker = "モナカ"
# 「なら尚更２人でって……会長さん。優しいんだね……？」
line = "「なら尚更２人でって……会長さん。優しいんだね……？」"

[[dialogue]]
speaker = "モナカ"
# 「それじゃ、えと……。お願いしてもいい……？　赤い首輪を付けた黒猫さんなんだけど……」
line = "「それじゃ、えと……。お願いしてもいい……？　赤い首輪を付けた黒猫さんなんだけど……」"

[[dialogue]]
speaker = "モナカ"
# 「あう、どうしよう……。全然見つからない……。もう日も沈んできちゃった……」
line = "「あう、どうしよう……。全然見つからない……。もう日も沈んできちゃった……」"

[[dialogue]]
speaker = "モナカ"
# 「ごめんね、こんな時間まで付き合わせちゃって……」
line = "「ごめんね、こんな時間まで付き合わせちゃって……」"

[[dialogue]]
speaker = "モナカ"
# 「えと、その。今日はこの辺りで切り上げようと思うの……。続きは明日にするから……。今日はありがとう……」
line = "「えと、その。今日はこの辺りで切り上げようと思うの……。続きは明日にするから……。今日はありがとう……」"

[[dialogue]]
speaker = "モナカ"
# 「い、行ったよね……？」
line = "「い、行ったよね……？」"

[[dialogue]]
speaker = "モナカ"
# 「おーい……。おーい……。にゃ～お……。にゃ～お……」
line = "「おーい……。おーい……。にゃ～お……。にゃ～お……」"

[[dialogue]]
speaker = "モナカ"
# 「子猫さーん、いたらお返事してー……？　にゃ～お、にゃ～お……」
line = "「子猫さーん、いたらお返事してー……？　にゃ～お、にゃ～お……」"

[[dialogue]]
speaker = "unk"
# やっぱり１人で探し続けてたんだ？
line = "やっぱり１人で探し続けてたんだ？"

[[dialogue]]
speaker = "モナカ"
# 「ひゃっ！？　か、会長さん……！？　帰ったんじゃ……！？」
line = "「ひゃっ！？　か、会長さん……！？　帰ったんじゃ……！？」"

[[dialogue]]
speaker = "モナカ"
# 「え、このおにぎり……。モナカに……？　お腹空いてるだろうからって……？」
line = "「え、このおにぎり……。モナカに……？　お腹空いてるだろうからって……？」"

[[dialogue]]
speaker = "モナカ"
# 「あ……ありがとう。でもどうして戻ってきたの……？　え、モナカが１人で探し続けてると思った、から……？」
line = "「あ……ありがとう。でもどうして戻ってきたの……？　え、モナカが１人で探し続けてると思った、から……？」"

[[dialogue]]
speaker = "モナカ"
# 「それでもわざわざ戻ってくる必要はなかったのに……。本当に……すごく優しいんだね？　おにぎりまで持ってきてくれて……」
line = "「それでもわざわざ戻ってくる必要はなかったのに……。本当に……すごく優しいんだね？　おにぎりまで持ってきてくれて……」"

[[dialogue]]
speaker = "モナカ"
# 「子猫さんを見つけた後でいただくね……？　今は少しでも早く子猫さんを見つけてあげたいから……」
line = "「子猫さんを見つけた後でいただくね……？　今は少しでも早く子猫さんを見つけてあげたいから……」"

[[dialogue]]
speaker = "unk"
# モナカは頑張り屋だね
line = "モナカは頑張り屋だね"

[[dialogue]]
speaker = "モナカ"
# 「そ、そんなことないよ……。モナカにはこれくらいしかできないだけで……」
line = "「そ、そんなことないよ……。モナカにはこれくらいしかできないだけで……」"

[[dialogue]]
speaker = "モナカ"
# 「それにモナカよりも子猫さんの方がお腹を空かせてると思うから……。飼い主さんも心配で心配で食事も喉を通らないだろうし……」
line = "「それにモナカよりも子猫さんの方がお腹を空かせてると思うから……。飼い主さんも心配で心配で食事も喉を通らないだろうし……」"

[[dialogue]]
speaker = "モナカ"
# 「モナカね、プリマステラにもなれない落ちこぼれだけど……。人見知りで臆病でダメダメの星騎士だけど……」
line = "「モナカね、プリマステラにもなれない落ちこぼれだけど……。人見知りで臆病でダメダメの星騎士だけど……」"

[[dialogue]]
speaker = "モナカ"
# 「でも、それでも自分にできる範囲で困ってる人を助けてあげたいんだ……。そのために、みんなでおなか部を作ったから……」
line = "「でも、それでも自分にできる範囲で困ってる人を助けてあげたいんだ……。そのために、みんなでおなか部を作ったから……」"

[[dialogue]]
speaker = "モナカ"
# 「ふぇ？　今、子猫さんの鳴き声が聞こえたような……」
line = "「ふぇ？　今、子猫さんの鳴き声が聞こえたような……」"

[[dialogue]]
speaker = "unk"
# あの木の上だ！
line = "あの木の上だ！"

[[dialogue]]
speaker = "モナカ"
# 「あっ、ホントだ……！　あの赤い首輪、黒い毛並み……！　きっと相談にあった子猫さんだよ……！」
line = "「あっ、ホントだ……！　あの赤い首輪、黒い毛並み……！　きっと相談にあった子猫さんだよ……！」"

[[dialogue]]
speaker = "モナカ"
# 「か、会長さんっ。モナカを肩車してくれるっ？　モナカ１人じゃあそこまでのぼれないから……！」
line = "「か、会長さんっ。モナカを肩車してくれるっ？　モナカ１人じゃあそこまでのぼれないから……！」"

[[dialogue]]
speaker = "モナカ"
# 「にゃ～お……にゃ～お……。ほーら、子猫さん、こっちに来て……？　にゃ～お、にゃ～お、怖くないから、ほーら……」
line = "「にゃ～お……にゃ～お……。ほーら、子猫さん、こっちに来て……？　にゃ～お、にゃ～お、怖くないから、ほーら……」"

[[dialogue]]
speaker = "モナカ"
# 「えへへ、今日はありがとう、会長さん。おかげで無事に飼い主さんへ子猫さんを届けてあげられたよ」
line = "「えへへ、今日はありがとう、会長さん。おかげで無事に飼い主さんへ子猫さんを届けてあげられたよ」"

[[dialogue]]
speaker = "モナカ"
# 「あの子猫さん、会長さんが持ってきてくれたおにぎりを見て、欲しい欲しいって鳴いたみたい。きっとモナカ１人じゃ見つけられなかったや」
line = "「あの子猫さん、会長さんが持ってきてくれたおにぎりを見て、欲しい欲しいって鳴いたみたい。きっとモナカ１人じゃ見つけられなかったや」"

[[dialogue]]
speaker = "モナカ"
# 「飼い主さんに届ける時も、口下手なモナカに代わって色々と話してくれて……。モナカ、ああいう時いつも上手く喋れないから助かっちゃった」
line = "「飼い主さんに届ける時も、口下手なモナカに代わって色々と話してくれて……。モナカ、ああいう時いつも上手く喋れないから助かっちゃった」"

[[dialogue]]
speaker = "モナカ"
# 「それにしても……その。ちょっぴり恥ずかしかったね……？　飼い主さん、ずっとモナカと会長さんのこと兄妹だと勘違いしてたから……」
line = "「それにしても……その。ちょっぴり恥ずかしかったね……？　飼い主さん、ずっとモナカと会長さんのこと兄妹だと勘違いしてたから……」"

[[dialogue]]
speaker = "モナカ"
# 「でも、モナカも嬉しいかも……。会長さんみたいな優しいにぃ様がいたら……。モナカね、姉様はたくさんいるけどにぃ様は１人もいなくて……」
line = "「でも、モナカも嬉しいかも……。会長さんみたいな優しいにぃ様がいたら……。モナカね、姉様はたくさんいるけどにぃ様は１人もいなくて……」"

[[dialogue]]
speaker = "モナカ"
# 「少しだけ憧れてたの……。ダメダメなモナカの前を歩いてくれる優しいにぃ様に……。手を引いてくれるにぃ様に……」
line = "「少しだけ憧れてたの……。ダメダメなモナカの前を歩いてくれる優しいにぃ様に……。手を引いてくれるにぃ様に……」"

[[dialogue]]
speaker = "モナカ"
# 「って、ご、ごめんなさい。変なこと言って」
line = "「って、ご、ごめんなさい。変なこと言って」"

[[dialogue]]
speaker = "unk"
# モナカみたいな子が妹なら大歓迎だよ
line = "モナカみたいな子が妹なら大歓迎だよ"

[[dialogue]]
speaker = "モナカ"
# 「ホ、ホント……？　なら、その……これから会長さんのこと、にぃ様って呼んでもいい……？」
line = "「ホ、ホント……？　なら、その……これから会長さんのこと、にぃ様って呼んでもいい……？」"

[[dialogue]]
speaker = "モナカ"
# 「えへへ、嬉しいな……。にぃ様……にぃ様……にぃ様……えへへ」
line = "「えへへ、嬉しいな……。にぃ様……にぃ様……にぃ様……えへへ」"

[[dialogue]]
speaker = "モナカ"
# 「あ、あのね、にぃ様。もし何かお悩み事があったら、いつでもモナカに相談して？　なんだって相談に乗るから」
line = "「あ、あのね、にぃ様。もし何かお悩み事があったら、いつでもモナカに相談して？　なんだって相談に乗るから」"

[[dialogue]]
speaker = "モナカ"
# 「それに今日は本当にありがとう。にぃ様からもらったおにぎりも、大切にいただくね？」
line = "「それに今日は本当にありがとう。にぃ様からもらったおにぎりも、大切にいただくね？」"

[[dialogue]]
speaker = "モナカ"
# 「あ……ふふ、すごいお腹の音。にぃ様もお腹空いてたんだ？　ずっとモナカに付き合ってくれてたもんね……？」
line = "「あ……ふふ、すごいお腹の音。にぃ様もお腹空いてたんだ？　ずっとモナカに付き合ってくれてたもんね……？」"

[[dialogue]]
speaker = "モナカ"
# 「じゃあ、えと。半分こ……しよ？　こういうことにも、えへへ、ちょっぴり憧れてたから……」
line = "「じゃあ、えと。半分こ……しよ？　こういうことにも、えへへ、ちょっぴり憧れてたから……」"
