[[dialogue]]
speaker = "unk"
# 第４話,甘々スパイラル,P
line = "第４話,甘々スパイラル,P"

[[dialogue]]
speaker = "unk"
# 前回、ヒルディー先輩が『絆』について打ち明けて以来、俺たちの間には少し変化があった。
line = "前回、ヒルディー先輩が『絆』について打ち明けて以来、俺たちの間には少し変化があった。"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「せっかく２人きりで過ごせる休日なのですから、今日もミーティアフォームでお互いの絆を深める訓練を致しますわよ♪」
line = "「せっかく２人きりで過ごせる休日なのですから、今日もミーティアフォームでお互いの絆を深める訓練を致しますわよ♪」"

[[dialogue]]
speaker = "unk"
# 絆の訓練という体裁で、先輩が以前より積極的に、<b>イチャイチャ</b>を提案して来るようになったのだ。
line = "絆の訓練という体裁で、先輩が以前より積極的に、<b>イチャイチャ</b>を提案して来るようになったのだ。"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「会長<emoji=heart04>　私のこと……抱き締めて下さいまし<emoji=heart04>」
line = "「会長<emoji=heart04>　私のこと……抱き締めて下さいまし<emoji=heart04>」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「あっ<emoji=heart04>　んっ……<emoji=heart04>」
line = "「あっ<emoji=heart04>　んっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺は彼女の体をそっと抱き寄せる。
line = "俺は彼女の体をそっと抱き寄せる。"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「はあぁ……<emoji=heart04>　こうして会長に抱き締められると、どれだけ強くなっても自分が女であると自覚させられますわ……<emoji=heart04>」
line = "「はあぁ……<emoji=heart04>　こうして会長に抱き締められると、どれだけ強くなっても自分が女であると自覚させられますわ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 先輩、抱き締められるの、好きですよね
line = "先輩、抱き締められるの、好きですよね"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「ですわ<emoji=heart04>　会長の細マッチョな筋肉の力強さを感じて、男らしさにトキめいて、ウットリしてしまいますの……<emoji=heart04>」
line = "「ですわ<emoji=heart04>　会長の細マッチョな筋肉の力強さを感じて、男らしさにトキめいて、ウットリしてしまいますの……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# それからしばらく、抱き合ったままお互いの体の温もりを確かめ合った後、俺は彼女に言う。
line = "それからしばらく、抱き合ったままお互いの体の温もりを確かめ合った後、俺は彼女に言う。"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「え？　――私の『羽』を撫でてみたい……ですの？」
line = "「え？　――私の『羽』を撫でてみたい……ですの？」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「恋人なのですし、構いませんけれど……撫でるのは別に初めてはありませんわよね？」
line = "「恋人なのですし、構いませんけれど……撫でるのは別に初めてはありませんわよね？」"

[[dialogue]]
speaker = "unk"
# 実は、ネットで調べて知ったんですけど――
line = "実は、ネットで調べて知ったんですけど――"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「――天使の羽は、気持ちを込めながら触れると、その人の感情が流れ込むらしい……？」
line = "「――天使の羽は、気持ちを込めながら触れると、その人の感情が流れ込むらしい……？」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「えっ、そんなことができますの！？　初めて知りましたけれど……どんな感じか、ちょっと興味が湧いてきますわ」
line = "「えっ、そんなことができますの！？　初めて知りましたけれど……どんな感じか、ちょっと興味が湧いてきますわ」"

[[dialogue]]
speaker = "unk"
# 俺は彼女の羽に触れて、そっと撫でる。すると――
line = "俺は彼女の羽に触れて、そっと撫でる。すると――"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「ふあっ……！？　ほ、本当ですわ<emoji=heart04>　なんだか触れてる感覚だけじゃなくて……んんっ<emoji=heart04>」
line = "「ふあっ……！？　ほ、本当ですわ<emoji=heart04>　なんだか触れてる感覚だけじゃなくて……んんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「不思議と、会長が考えていることが伝わってくる感じがしますの<emoji=heart04>　耳元よりももっと近くで愛を囁かれているような……<emoji=heart04>」
line = "「不思議と、会長が考えていることが伝わってくる感じがしますの<emoji=heart04>　耳元よりももっと近くで愛を囁かれているような……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 伝わりますか？
line = "伝わりますか？"

[[dialogue]]
speaker = "unk"
# 俺がどれくらい先輩のことが好きなのか
line = "俺がどれくらい先輩のことが好きなのか"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「え、ええ<emoji=heart04>　まるで心が優しく抱き締められているみたいで……はあぁっ<emoji=heart04>　とっても幸せな気持ちになってしまいますの……<emoji=heart04>」
line = "「え、ええ<emoji=heart04>　まるで心が優しく抱き締められているみたいで……はあぁっ<emoji=heart04>　とっても幸せな気持ちになってしまいますの……<emoji=heart04>」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「――あっ<emoji=heart04>　会長、羽を撫でながら耳元で名前を呼ぶのは反則ですわ<emoji=heart04>　しゅ、淑女としての理性が甘くとろけてしまいそうですの……<emoji=heart04>」
line = "「――あっ<emoji=heart04>　会長、羽を撫でながら耳元で名前を呼ぶのは反則ですわ<emoji=heart04>　しゅ、淑女としての理性が甘くとろけてしまいそうですの……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ヒルディーも、『旦那様』って呼んで欲しいな
line = "ヒルディーも、『旦那様』って呼んで欲しいな"

[[dialogue]]
speaker = "unk"
# これまでも今のようにすごく甘いムードになった時は、そう呼び合ってイチャイチャすることがあった。
line = "これまでも今のようにすごく甘いムードになった時は、そう呼び合ってイチャイチャすることがあった。"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「ん……わかりましたわ<emoji=heart04>　――旦那様<emoji=heart04>」
line = "「ん……わかりましたわ<emoji=heart04>　――旦那様<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# それから俺はソファーに座り、彼女を後ろから抱き締めるような形で、イチャイチャしながら過ごす。
line = "それから俺はソファーに座り、彼女を後ろから抱き締めるような形で、イチャイチャしながら過ごす。"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「あっ、思いつきましたわ<emoji=heart04>　見て下さいまし、旦那様の親指と人差し指で、こうして輪っかを作って……」
line = "「あっ、思いつきましたわ<emoji=heart04>　見て下さいまし、旦那様の親指と人差し指で、こうして輪っかを作って……」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「そこに私の薬指を通すと……ほら♪　結婚指輪みたいですわ<emoji=heart04>　ふふっ……<emoji=heart04>」
line = "「そこに私の薬指を通すと……ほら♪　結婚指輪みたいですわ<emoji=heart04>　ふふっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ならばと、俺は彼女のよく手入れされた綺麗な縦ロールの髪先を、自分の左手薬指に軽く巻いてみせる。
line = "ならばと、俺は彼女のよく手入れされた綺麗な縦ロールの髪先を、自分の左手薬指に軽く巻いてみせる。"

[[dialogue]]
speaker = "unk"
# これでお揃いだね
line = "これでお揃いだね"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「……！　そんなお返しをされたら……私、愛おしい気持ちが溢れてきて、我慢できなくなってしまいますわ<emoji=heart04>」
line = "「……！　そんなお返しをされたら……私、愛おしい気持ちが溢れてきて、我慢できなくなってしまいますわ<emoji=heart04>」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「旦那様とキス……したくなってしまいますの<emoji=heart04>」
line = "「旦那様とキス……したくなってしまいますの<emoji=heart04>」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「ん……<emoji=heart04>」
line = "「ん……<emoji=heart04>」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「旦那様……<emoji=heart04>　ちゅっ……<emoji=heart04>」
line = "「旦那様……<emoji=heart04>　ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ヒルディー、好きだよ
line = "ヒルディー、好きだよ"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「私もですわ、旦那様<emoji=heart04>　んむっ……<emoji=heart04>　ちゅっ……<emoji=heart04>」
line = "「私もですわ、旦那様<emoji=heart04>　んむっ……<emoji=heart04>　ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「心からお慕いしておりますの<emoji=heart04>　誰よりも愛しておりますわ……<emoji=heart04>」
line = "「心からお慕いしておりますの<emoji=heart04>　誰よりも愛しておりますわ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「これからもどうか……私と一緒に居て下さいましね<emoji=heart04>」
line = "「これからもどうか……私と一緒に居て下さいましね<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ああ、ずっとそばにいるよ
line = "ああ、ずっとそばにいるよ"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「約束ですわよ？　んっ……<emoji=heart04>」
line = "「約束ですわよ？　んっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ヒルディオーネ（覚醒）"
# 「ちゅっ……<emoji=heart04>」
line = "「ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺たちはそれからも、天使の羽やキスを通して、繰り返し気持ちを伝え合うのだった――
line = "俺たちはそれからも、天使の羽やキスを通して、繰り返し気持ちを伝え合うのだった――"
