[[dialogue]]
speaker = "unk"
# ハロウィンに賑わう街で遊んで、そろそろ寮に戻る時間が近づいてくる。
line = "ハロウィンに賑わう街で遊んで、そろそろ寮に戻る時間が近づいてくる。"

[[dialogue]]
speaker = "クロト"
# 「ウズメ、今日はどうする？」
line = "「ウズメ、今日はどうする？」"

[[dialogue]]
speaker = "ウズメイア"
# 「まだ時間あるよ。も～、分かってて聞いてるし……」
line = "「まだ時間あるよ。も～、分かってて聞いてるし……」"

[[dialogue]]
speaker = "ウズメイア"
# 「ご休憩、していこっ<emoji=heart04>」
line = "「ご休憩、していこっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 袖を引っ張るウズメの視線の先には、暗がりに光るラブホテルの入り口があった。
line = "袖を引っ張るウズメの視線の先には、暗がりに光るラブホテルの入り口があった。"

[[dialogue]]
speaker = "ウズメイア"
# 「えへへ、今日のあたしは狼さんだから、会長くんを襲って食べちゃうし♪」
line = "「えへへ、今日のあたしは狼さんだから、会長くんを襲って食べちゃうし♪」"

[[dialogue]]
speaker = "クロト"
# 「あ、そういうノリなんだ」
line = "「あ、そういうノリなんだ」"

[[dialogue]]
speaker = "ウズメイア"
# 「せっかくのハロウィンだし、仮装してるし、楽しまない手はないっしょ？」
line = "「せっかくのハロウィンだし、仮装してるし、楽しまない手はないっしょ？」"

[[dialogue]]
speaker = "クロト"
# 「それは仮装じゃなくて戦闘服だろ？」
line = "「それは仮装じゃなくて戦闘服だろ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「まあまあ、細かいことは言わないし♪　今夜は逃がさないぞ～<emoji=heart04>」
line = "「まあまあ、細かいことは言わないし♪　今夜は逃がさないぞ～<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# と、攻める気満々のウズメだったのだが──
line = "と、攻める気満々のウズメだったのだが──"

[[dialogue]]
speaker = "クロト"
# 「──とか、調子に乗ったこと言ってたけど、何なんだ、この無様な様子は」
line = "「──とか、調子に乗ったこと言ってたけど、何なんだ、この無様な様子は」"

[[dialogue]]
speaker = "ウズメイア"
# 「だ、だって……会長くんの愛撫が気持ちよすぎるのがいけないし……」
line = "「だ、だって……会長くんの愛撫が気持ちよすぎるのがいけないし……」"

[[dialogue]]
speaker = "クロト"
# 「ウズメ、敬語」
line = "「ウズメ、敬語」"

[[dialogue]]
speaker = "ウズメイア"
# 「ご、ごめんなさいっ！　わかりましたぁっ！！」
line = "「ご、ごめんなさいっ！　わかりましたぁっ！！」"

[[dialogue]]
speaker = "unk"
# ウズメはホテルの壁にかかっている鏡に手を突いてお尻を突き出している。
line = "ウズメはホテルの壁にかかっている鏡に手を突いてお尻を突き出している。"

[[dialogue]]
speaker = "unk"
# お尻を叩かれておずおずと向けた視線の先には、赤面するほど恥ずかしい格好の自身が写っていた。
line = "お尻を叩かれておずおずと向けた視線の先には、赤面するほど恥ずかしい格好の自身が写っていた。"

[[dialogue]]
speaker = "クロト"
# 「鏡に映った自分を見てみろ。どんな姿が写ってる？」
line = "「鏡に映った自分を見てみろ。どんな姿が写ってる？」"

[[dialogue]]
speaker = "ウズメイア"
# 「お尻を突き出して、会長くんにおち○ぽ入れてもらえるのを待ってる、メスオオカミの姿が写ってます……」
line = "「お尻を突き出して、会長くんにおち○ぽ入れてもらえるのを待ってる、メスオオカミの姿が写ってます……」"

[[dialogue]]
speaker = "ウズメイア"
# 「そのメスオオカミは……待ちきれない様子で……おま○こから恥ずかしいおつゆをダラダラとだらしなく垂らしてます……」
line = "「そのメスオオカミは……待ちきれない様子で……おま○こから恥ずかしいおつゆをダラダラとだらしなく垂らしてます……」"

[[dialogue]]
speaker = "クロト"
# 「挿入もしていないのにそんな状態になるなんて、どういうことなんだろうな？」
line = "「挿入もしていないのにそんな状態になるなんて、どういうことなんだろうな？」"

[[dialogue]]
speaker = "ウズメイア"
# 「これからこの会長くんのたくましいおち○ぽでめちゃくちゃにされるんだって思うと……それだけで興奮が抑えられないんです<emoji=heart04>」
line = "「これからこの会長くんのたくましいおち○ぽでめちゃくちゃにされるんだって思うと……それだけで興奮が抑えられないんです<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「そんな自分の状態を口で言わされて……もっと興奮してしまっているはしたないメスオオカミです……<emoji=heart04>」
line = "「そんな自分の状態を口で言わされて……もっと興奮してしまっているはしたないメスオオカミです……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「我慢できないくらい、これが欲しいんだな？」
line = "「我慢できないくらい、これが欲しいんだな？」"

[[dialogue]]
speaker = "ウズメイア"
# 「欲しいです……<emoji=heart04>　焦らさないで、お願いですから会長くんのおち○ぽを、あたしのおま○こにぶち込んでください……<emoji=heart04>」
line = "「欲しいです……<emoji=heart04>　焦らさないで、お願いですから会長くんのおち○ぽを、あたしのおま○こにぶち込んでください……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「仕方ないな……それじゃ入れてやるから、しっかり受け止めろ」
line = "「仕方ないな……それじゃ入れてやるから、しっかり受け止めろ」"

[[dialogue]]
speaker = "ウズメイア"
# 「は、はいっ<emoji=heart04>」
line = "「は、はいっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「あぁあああああん……っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あぁあああああん……っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺はウズメの腰をしっかりつかむと、じりじりと焦らすようにペニスを挿入していく。
line = "俺はウズメの腰をしっかりつかむと、じりじりと焦らすようにペニスを挿入していく。"

[[dialogue]]
speaker = "unk"
# 鏡にはその様子が写り、ウズメの目にもそれはしっかり見えたことだろう。
line = "鏡にはその様子が写り、ウズメの目にもそれはしっかり見えたことだろう。"

[[dialogue]]
speaker = "クロト"
# 「欲しがってたものが入ってきた様子はどうだ？」
line = "「欲しがってたものが入ってきた様子はどうだ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「は、はい……おま○こにおち○ぽが突き刺さってます……その様子が、はっきり見えます……」
line = "「は、はい……おま○こにおち○ぽが突き刺さってます……その様子が、はっきり見えます……」"

[[dialogue]]
speaker = "ウズメイア"
# 「それに……あはっ……嬉しそうな顔……あたし、おち○ぽ入れてもらって、こんなに悦んでるんだぁ<emoji=heart04>」
line = "「それに……あはっ……嬉しそうな顔……あたし、おち○ぽ入れてもらって、こんなに悦んでるんだぁ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「おち○ぽ入れられただけで……おま○こから涎を垂らして……蕩け顔になっちゃってるぅ<emoji=heart04>」
line = "「おち○ぽ入れられただけで……おま○こから涎を垂らして……蕩け顔になっちゃってるぅ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「すごいな、ギュウギュウ締め付けてくる。自分の恥ずかしい様子を口にするのがそんなに興奮するんだな」
line = "「すごいな、ギュウギュウ締め付けてくる。自分の恥ずかしい様子を口にするのがそんなに興奮するんだな」"

[[dialogue]]
speaker = "ウズメイア"
# （興奮、してる……んんっ……自分で自分の恥ずかしいところ言わされて……興奮、してる……？）
line = "（興奮、してる……んんっ……自分で自分の恥ずかしいところ言わされて……興奮、してる……？）"

[[dialogue]]
speaker = "クロト"
# 「どうなんだ？」
line = "「どうなんだ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「ひゃうっ<emoji=heart04>　は、はいっ……興奮、してるしっ<emoji=heart04>」
line = "「ひゃうっ<emoji=heart04>　は、はいっ……興奮、してるしっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「あっ、あ……あああっ……んっ、あっ、あああっ……<emoji=heart04>」
line = "「あっ、あ……あああっ……んっ、あっ、あああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ゆっくりとしたピストンを開始する。
line = "ゆっくりとしたピストンを開始する。"

[[dialogue]]
speaker = "unk"
# 掴んでいる腰を揺さぶり動かすと、にゅるりとした快感がペニスに走り、思わず声が漏れてしまいそうになる。
line = "掴んでいる腰を揺さぶり動かすと、にゅるりとした快感がペニスに走り、思わず声が漏れてしまいそうになる。"

[[dialogue]]
speaker = "ウズメイア"
# 「はぁっ、はぁっ……会長くんの、おち○ぽ……動き出した……んんっ……出たり入ったりするのが見えるし……」
line = "「はぁっ、はぁっ……会長くんの、おち○ぽ……動き出した……んんっ……出たり入ったりするのが見えるし……」"

[[dialogue]]
speaker = "ウズメイア"
# 「充血した……おま○こ肉を押し広げて……んんっ……会長くんのぶっといの、ずぶっずぶって……ああんっ……<emoji=heart04>」
line = "「充血した……おま○こ肉を押し広げて……んんっ……会長くんのぶっといの、ずぶっずぶって……ああんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くんのおち○ぽ……んっ、あっ……気持ちいいとこ、こすってくるし……あ、ああ、ん、ああっ……<emoji=heart04>」
line = "「会長くんのおち○ぽ……んっ、あっ……気持ちいいとこ、こすってくるし……あ、ああ、ん、ああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# （あぁ……ん……会長くんのおち○ぽ……あたしの感じるところ、見逃さないんだぁ……嬉しいよぉ<emoji=heart04>）
line = "（あぁ……ん……会長くんのおち○ぽ……あたしの感じるところ、見逃さないんだぁ……嬉しいよぉ<emoji=heart04>）"

[[dialogue]]
speaker = "ウズメイア"
# （あたしのこと、絶対に気持ちよくするって決めてるみたい……あぁあ、気持ちよすぎだしぃっ<emoji=heart04>）
line = "（あたしのこと、絶対に気持ちよくするって決めてるみたい……あぁあ、気持ちよすぎだしぃっ<emoji=heart04>）"

[[dialogue]]
speaker = "unk"
# 俺はウズメの求めに応じるように、膣内の弱いところに先端を擦りあてる。
line = "俺はウズメの求めに応じるように、膣内の弱いところに先端を擦りあてる。"

[[dialogue]]
speaker = "unk"
# 的確な刺激に、ウズメはぶるぶるっと身を震わせながら快感を訴える。
line = "的確な刺激に、ウズメはぶるぶるっと身を震わせながら快感を訴える。"

[[dialogue]]
speaker = "ウズメイア"
# 「ああっ、あっ、んっ、あっ……あぁあ……あ、はぁ、あ、ああっ……<emoji=heart04>」
line = "「ああっ、あっ、んっ、あっ……あぁあ……あ、はぁ、あ、ああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「んっ、あっ、んんぅっ……ヤバい、よぉ……それ、感じすぎちゃうっ……んっ、あ、あああっ……<emoji=heart04>」
line = "「んっ、あっ、んんぅっ……ヤバい、よぉ……それ、感じすぎちゃうっ……んっ、あ、あああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「感じるより先に、やることがあるだろ？」
line = "「感じるより先に、やることがあるだろ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「んっ、う、んんんっ……会長くんを、気持ちよくするっ……んんっ、あっ、んぅううっ……」
line = "「んっ、う、んんんっ……会長くんを、気持ちよくするっ……んんっ、あっ、んぅううっ……」"

[[dialogue]]
speaker = "ウズメイア"
# 「ああんっ<emoji=heart04>　ダメだしぃっ、そんなにされたら、力が……入んなくなっちゃうっ……んんっ、ああっ……<emoji=heart04>」
line = "「ああんっ<emoji=heart04>　ダメだしぃっ、そんなにされたら、力が……入んなくなっちゃうっ……んんっ、ああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「おち○ぽ、ちゃんと締められないよぉ……あっ、あっ、ああ、ん、あああっ……<emoji=heart04>」
line = "「おち○ぽ、ちゃんと締められないよぉ……あっ、あっ、ああ、ん、あああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「だったらこうしてやったらどうだ？」
line = "「だったらこうしてやったらどうだ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「あああんっっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あああんっっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「そうそう、そうやってしっかり締めているんだぞ」
line = "「そうそう、そうやってしっかり締めているんだぞ」"

[[dialogue]]
speaker = "ウズメイア"
# 「はぁ、ん……んふぅ……会長くんのおち○ぽ、しっかり締めてますっ……<emoji=heart04>」
line = "「はぁ、ん……んふぅ……会長くんのおち○ぽ、しっかり締めてますっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「尻を叩かれて感じたのか？　それで締め付けが増すなんてドＭが過ぎるんじゃないか？」
line = "「尻を叩かれて感じたのか？　それで締め付けが増すなんてドＭが過ぎるんじゃないか？」"

[[dialogue]]
speaker = "ウズメイア"
# 「うぅぅ……はい……あたしは、お尻を叩かれてかんじちゃう、変態のドＭですっ……<emoji=heart04>」
line = "「うぅぅ……はい……あたしは、お尻を叩かれてかんじちゃう、変態のドＭですっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「あううっ！　んんっ……気持ちいい……<emoji=heart04>　んんっ、ぁ……んんぅ……<emoji=heart04>」
line = "「あううっ！　んんっ……気持ちいい……<emoji=heart04>　んんっ、ぁ……んんぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「こうやって会長くんにいじめられるの、大好きです……だから、もっと……お願いしますっ……<emoji=heart04>」
line = "「こうやって会長くんにいじめられるの、大好きです……だから、もっと……お願いしますっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「本当にエロくて変態だな……最高だよ、ウズメ……」
line = "「本当にエロくて変態だな……最高だよ、ウズメ……」"

[[dialogue]]
speaker = "ウズメイア"
# 「あぁあ、ありがとう、ございますっ……<emoji=heart04>　んっ、あ、んんぅ……んうう……はぁ、ん、ああぅ……んんっ……」
line = "「あぁあ、ありがとう、ございますっ……<emoji=heart04>　んっ、あ、んんぅ……んうう……はぁ、ん、ああぅ……んんっ……」"

[[dialogue]]
speaker = "unk"
# 被虐心の高まったウズメに火をつけるように、俺は彼女を貫くピストンを一気に速めた。
line = "被虐心の高まったウズメに火をつけるように、俺は彼女を貫くピストンを一気に速めた。"

[[dialogue]]
speaker = "ウズメイア"
# 「あああんっ<emoji=heart04>　あっ、あっ、あっ、あ、ああっ……んんっ、あ、あああっ<emoji=heart04>」
line = "「あああんっ<emoji=heart04>　あっ、あっ、あっ、あ、ああっ……んんっ、あ、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くんのが、奥の方を……ああっ、あっ……ガンガン、突いてるっ……ん、あ、あああっ<emoji=heart04>」
line = "「会長くんのが、奥の方を……ああっ、あっ……ガンガン、突いてるっ……ん、あ、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「容赦なく突いて、あたしのおま○こ……悦ばせてくれてるっ……んんっ、あっ、あ、あああっ、あ、やぁあっ……<emoji=heart04>」
line = "「容赦なく突いて、あたしのおま○こ……悦ばせてくれてるっ……んんっ、あっ、あ、あああっ、あ、やぁあっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# （すっごい音だし……パンパンって音が、隣の部屋にまで聞こえちゃいそう……）
line = "（すっごい音だし……パンパンって音が、隣の部屋にまで聞こえちゃいそう……）"

[[dialogue]]
speaker = "ウズメイア"
# （どんだけ激しく求めてくれてんだろ……あぁ……すごいよぉ……気持ちよすぎて変になっちゃうよぉ<emoji=heart04>）
line = "（どんだけ激しく求めてくれてんだろ……あぁ……すごいよぉ……気持ちよすぎて変になっちゃうよぉ<emoji=heart04>）"

[[dialogue]]
speaker = "ウズメイア"
# 「はぁっ、はぁっ、あっ、あっ、あ、ああっ<emoji=heart04>　んんっ、はぁ、あ、あああっ、んんっ、あ、ああっ<emoji=heart04>」
line = "「はぁっ、はぁっ、あっ、あっ、あ、ああっ<emoji=heart04>　んんっ、はぁ、あ、あああっ、んんっ、あ、ああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くんっ、あたし、激しいの好きっ<emoji=heart04>　むちゃくちゃにされるのが、好きっ<emoji=heart04>」
line = "「会長くんっ、あたし、激しいの好きっ<emoji=heart04>　むちゃくちゃにされるのが、好きっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「だからもっと、おねがいしますっ<emoji=heart04>　たくましいおち○ぽでっ……ああっ……壊れるくらい突きまくってっ<emoji=heart04>」
line = "「だからもっと、おねがいしますっ<emoji=heart04>　たくましいおち○ぽでっ……ああっ……壊れるくらい突きまくってっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ああ、お望み通り……むちゃくちゃにしてやるよ……！」
line = "「ああ、お望み通り……むちゃくちゃにしてやるよ……！」"

[[dialogue]]
speaker = "unk"
# 身体を叩きつける度に、ウズメの身体が跳ねる。
line = "身体を叩きつける度に、ウズメの身体が跳ねる。"

[[dialogue]]
speaker = "unk"
# その度にウズメの形のいい胸が歪んで跳ね上がり、その様子でますます興奮をかき立てられる。
line = "その度にウズメの形のいい胸が歪んで跳ね上がり、その様子でますます興奮をかき立てられる。"

[[dialogue]]
speaker = "クロト"
# 「おっぱいが揺れてるところも見えるか？」
line = "「おっぱいが揺れてるところも見えるか？」"

[[dialogue]]
speaker = "ウズメイア"
# 「はいっ、ん、んぅぅっ……<emoji=heart04>　見え、ますっ……おち○ぽが突き入れられるたびに、ブルンブルンって揺れてますっ……<emoji=heart04>」
line = "「はいっ、ん、んぅぅっ……<emoji=heart04>　見え、ますっ……おち○ぽが突き入れられるたびに、ブルンブルンって揺れてますっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「エロいよ、ウズメ。最高のエロ乳だ」
line = "「エロいよ、ウズメ。最高のエロ乳だ」"

[[dialogue]]
speaker = "ウズメイア"
# 「会長くん、んんっ、あたしのおっぱい好き？　乱暴にしたい？」
line = "「会長くん、んんっ、あたしのおっぱい好き？　乱暴にしたい？」"

[[dialogue]]
speaker = "ウズメイア"
# 「だったら、してくださいっ<emoji=heart04>　手のひらで握りつぶすくらい、強くつかんだり……乳首を抓ったりしてくださいっ……<emoji=heart04>」
line = "「だったら、してくださいっ<emoji=heart04>　手のひらで握りつぶすくらい、強くつかんだり……乳首を抓ったりしてくださいっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ああ、両方可愛がってやるよ」
line = "「ああ、両方可愛がってやるよ」"

[[dialogue]]
speaker = "ウズメイア"
# 「あああっ、んっ、あ、ああっ<emoji=heart04>　おっぱい揉まれながら、おま○こもずぽずぽされてるぅっ<emoji=heart04>　上も下も感じさせられちゃってるぅっ<emoji=heart04>」
line = "「あああっ、んっ、あ、ああっ<emoji=heart04>　おっぱい揉まれながら、おま○こもずぽずぽされてるぅっ<emoji=heart04>　上も下も感じさせられちゃってるぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「こんなのむりぃっ！　どこまでも気持ちよくなっちゃうしっ<emoji=heart04>」
line = "「こんなのむりぃっ！　どこまでも気持ちよくなっちゃうしっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 切迫した声が示すように、ウズメの絶頂も迫っているようだった。
line = "切迫した声が示すように、ウズメの絶頂も迫っているようだった。"

[[dialogue]]
speaker = "unk"
# 同時に俺も、痺れるような快感がペニスを通じて下半身を支配していく。
line = "同時に俺も、痺れるような快感がペニスを通じて下半身を支配していく。"

[[dialogue]]
speaker = "クロト"
# 「気持ちよくなってきたぞ……このまま中に出すからな……」
line = "「気持ちよくなってきたぞ……このまま中に出すからな……」"

[[dialogue]]
speaker = "ウズメイア"
# 「あっ、ああっ、ん、出してっ<emoji=heart04>　あたしの中に、たっぷり注ぎ込んでくださいっ！」
line = "「あっ、ああっ、ん、出してっ<emoji=heart04>　あたしの中に、たっぷり注ぎ込んでくださいっ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「特濃の精子欲しいっ<emoji=heart04>　一方的に孕ませられたいっ<emoji=heart04>　ああっ、あっ、あっ、あっ、あ、ああああっ<emoji=heart04>」
line = "「特濃の精子欲しいっ<emoji=heart04>　一方的に孕ませられたいっ<emoji=heart04>　ああっ、あっ、あっ、あっ、あ、ああああっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「孕ませて欲しかったら、おま○こを全力で締めて搾り取れ……！」
line = "「孕ませて欲しかったら、おま○こを全力で締めて搾り取れ……！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ん、うんっ<emoji=heart04>　ちゃんと、会長くんの赤ちゃん、妊娠できるようにっ、んっ、んんんっ、全力で、締めるしっ、ん、あああっ<emoji=heart04>」
line = "「ん、うんっ<emoji=heart04>　ちゃんと、会長くんの赤ちゃん、妊娠できるようにっ、んっ、んんんっ、全力で、締めるしっ、ん、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「どう？　会長くんっ、んんっ、はぁ、あ……これで、妊娠できる？　会長くんに、孕ませ汁、びゅーびゅーしてもらえるっ？」
line = "「どう？　会長くんっ、んんっ、はぁ、あ……これで、妊娠できる？　会長くんに、孕ませ汁、びゅーびゅーしてもらえるっ？」"

[[dialogue]]
speaker = "クロト"
# 「ああ、気持ちいい。絶対に妊娠するくらいいっぱい出そうだ」
line = "「ああ、気持ちいい。絶対に妊娠するくらいいっぱい出そうだ」"

[[dialogue]]
speaker = "ウズメイア"
# 「嬉しい、んんっ、あっ、あ、ああっ、あっ、あああ……あっ、ん、あ、ああっ、あ、あああっ……<emoji=heart04>」
line = "「嬉しい、んんっ、あっ、あ、ああっ、あっ、あああ……あっ、ん、あ、ああっ、あ、あああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「出してっ、くださいっ<emoji=heart04>　思いっきり、おま○こにっ！　あふれるくらいっ、あ、あ、あ、ああ、あ……ん、あぁ、あああっ<emoji=heart04>」
line = "「出してっ、くださいっ<emoji=heart04>　思いっきり、おま○こにっ！　あふれるくらいっ、あ、あ、あ、ああ、あ……ん、あぁ、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「ああ、あっ、あああっ、んんっ、はぁ、あ、あああっ<emoji=heart04>　あ、ん、ん、ふぁ、あ、あ、あああっ、や、んんっ、あっ、ああ、あ、ああ……」
line = "「ああ、あっ、あああっ、んんっ、はぁ、あ、あああっ<emoji=heart04>　あ、ん、ん、ふぁ、あ、あ、あああっ、や、んんっ、あっ、ああ、あ、ああ……」"

[[dialogue]]
speaker = "unk"
# 熱い何かがこみ上げてくる。
line = "熱い何かがこみ上げてくる。"

[[dialogue]]
speaker = "unk"
# それをせき止めながら熱い息を吐き出し、夢中になってピストンを速めていく。
line = "それをせき止めながら熱い息を吐き出し、夢中になってピストンを速めていく。"

[[dialogue]]
speaker = "ウズメイア"
# 「おち○ぽ、ビクビクしてるっ、んんっ、あっ、あ、ああっ……あたしの中で、爆発寸前ってこと……？　ああっ、あ、ん、あぁあんっ<emoji=heart04>」
line = "「おち○ぽ、ビクビクしてるっ、んんっ、あっ、あ、ああっ……あたしの中で、爆発寸前ってこと……？　ああっ、あ、ん、あぁあんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「ん、ああっ、あ……会長くん、あたしも、だしっ……イキそう、だしっ、あっ、ああ、んんっ、あ、ああっ……<emoji=heart04>」
line = "「ん、ああっ、あ……会長くん、あたしも、だしっ……イキそう、だしっ、あっ、ああ、んんっ、あ、ああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ああ、一緒にイこうか」
line = "「ああ、一緒にイこうか」"

[[dialogue]]
speaker = "ウズメイア"
# 「んっ、うんっ、いくっ、ああっ、あっ、んんっ、ああっ<emoji=heart04>　会長くんの、射精嬉しくて、一緒にイキ果てちゃうっ<emoji=heart04>」
line = "「んっ、うんっ、いくっ、ああっ、あっ、んんっ、ああっ<emoji=heart04>　会長くんの、射精嬉しくて、一緒にイキ果てちゃうっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「あっ、あ、あ、あ、ああっ<emoji=heart04>　はぁ、ん、んぅ、はぁ、あ、あ、ああ、あっ<emoji=heart04>　ああ、あ、ああっ、んっ、あっ、く……あ、あああっ<emoji=heart04>」
line = "「あっ、あ、あ、あ、ああっ<emoji=heart04>　はぁ、ん、んぅ、はぁ、あ、あ、ああ、あっ<emoji=heart04>　ああ、あ、ああっ、んっ、あっ、く……あ、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「や、あ、んんっ、ああっ、会長、くんっ<emoji=heart04>　んんっ、く……イク、んぅっ、ん、ぁ、ああっ……あ、イク、イクよぉっ<emoji=heart04>」
line = "「や、あ、んんっ、ああっ、会長、くんっ<emoji=heart04>　んんっ、く……イク、んぅっ、ん、ぁ、ああっ……あ、イク、イクよぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「あっ、や、あ、あああっ、は、あああぅ、あ、ああっ<emoji=heart04>　あっ、あっ、ああっ、あ、あ、ああ、あ、ん……ぁ、あああっ……あ、んんぅ、はぁ、あ──」
line = "「あっ、や、あ、あああっ、は、あああぅ、あ、ああっ<emoji=heart04>　あっ、あっ、ああっ、あ、あ、ああ、あ、ん……ぁ、あああっ……あ、んんぅ、はぁ、あ──」"

[[dialogue]]
speaker = "ウズメイア"
# 「ひぁぅ、あ、あああああっ、ぐ、イグイグイグっ<emoji=heart04>　あ、あああああああああああああああ～～～～っ！！！！」
line = "「ひぁぅ、あ、あああああっ、ぐ、イグイグイグっ<emoji=heart04>　あ、あああああああああああああああ～～～～っ！！！！」"

[[dialogue]]
speaker = "unk"
# ウズメの絶頂の叫びとともに、しなやかな身体が大きく反り上がった。
line = "ウズメの絶頂の叫びとともに、しなやかな身体が大きく反り上がった。"

[[dialogue]]
speaker = "unk"
# ビクンビクンと身体を震わせるウズメの膣内に、俺は欲望の限り白濁とした液体をぶちまける。
line = "ビクンビクンと身体を震わせるウズメの膣内に、俺は欲望の限り白濁とした液体をぶちまける。"

[[dialogue]]
speaker = "ウズメイア"
# 「あああぁぁぁあ～～～～っ！！！　あっ、ふぁ、ん……あぁああああ～～～～～～っ！！！<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あああぁぁぁあ～～～～っ！！！　あっ、ふぁ、ん……あぁああああ～～～～～～っ！！！<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「ああ、んんぅっ……出てるっ……<emoji=heart04>　会長くんの、せーえきっ……んんっ、注ぎ込まれてるっ……んんぅっ……<emoji=heart04>」
line = "「ああ、んんぅっ……出てるっ……<emoji=heart04>　会長くんの、せーえきっ……んんっ、注ぎ込まれてるっ……んんぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ウズメは無理やり孕まされるのを歓喜するように、声を震わせながら流し込まれる俺の子種を受け止める。
line = "ウズメは無理やり孕まされるのを歓喜するように、声を震わせながら流し込まれる俺の子種を受け止める。"

[[dialogue]]
speaker = "unk"
# 何度も脈動が繰り返され、その波が落ち着いてくると、ウズメの身体が少しずつ弛緩していくのがわかった。
line = "何度も脈動が繰り返され、その波が落ち着いてくると、ウズメの身体が少しずつ弛緩していくのがわかった。"

[[dialogue]]
speaker = "ウズメイア"
# 「はぁ、はぁ、んん……んぅぅ……ふぅ……はぁ……んぅ……<emoji=heart04>」
line = "「はぁ、はぁ、んん……んぅぅ……ふぅ……はぁ……んぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「なんか、いつも通り……メッチャ攻められちゃったし……んんぅ……」
line = "「なんか、いつも通り……メッチャ攻められちゃったし……んんぅ……」"

[[dialogue]]
speaker = "ウズメイア"
# 「もう……鏡に映った自分のこと、説明させられたの……ちょー恥ずかしかったよ……」
line = "「もう……鏡に映った自分のこと、説明させられたの……ちょー恥ずかしかったよ……」"

[[dialogue]]
speaker = "クロト"
# 「ごめんな、ウズメ」
line = "「ごめんな、ウズメ」"

[[dialogue]]
speaker = "ウズメイア"
# 「えへへ、いいし……<emoji=heart04>」
line = "「えへへ、いいし……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# 「ってか、その方があたしも喜ぶって分かっててやってもらってることだしね……<emoji=heart04>」
line = "「ってか、その方があたしも喜ぶって分かっててやってもらってることだしね……<emoji=heart04>」"

[[dialogue]]
speaker = "ウズメイア"
# （それに、乱暴にしたエッチの後に、ちょっと反省してる会長くんも可愛いし……<emoji=heart04>）
line = "（それに、乱暴にしたエッチの後に、ちょっと反省してる会長くんも可愛いし……<emoji=heart04>）"

[[dialogue]]
speaker = "ウズメイア"
# （何よりやっぱ激しくされるほうが気持ちいい……やっぱドＭなんだな～、あたしって……<emoji=heart04>）
line = "（何よりやっぱ激しくされるほうが気持ちいい……やっぱドＭなんだな～、あたしって……<emoji=heart04>）"

[[dialogue]]
speaker = "ウズメイア"
# 「ねね、会長くん。もう一回いける？」
line = "「ねね、会長くん。もう一回いける？」"

[[dialogue]]
speaker = "クロト"
# 「ウズメがいいならもちろんだよ」
line = "「ウズメがいいならもちろんだよ」"

[[dialogue]]
speaker = "ウズメイア"
# 「時間もあと少しなら大丈夫だし……えへへ、じゃもう１回っ<emoji=heart04>」
line = "「時間もあと少しなら大丈夫だし……えへへ、じゃもう１回っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# こうして俺とウズメは門限ギリギリになるまで、時間いっぱい愛し合ったのだった。
line = "こうして俺とウズメは門限ギリギリになるまで、時間いっぱい愛し合ったのだった。"
