[[dialogue]]
speaker = "unk"
# 第２話,マトイのメイド体験,P
line = "第２話,マトイのメイド体験,P"

[[dialogue]]
speaker = "unk"
# マトイは最近、九浄家メイド隊でのバイトを始めていた。ヴィーナスに頼み、メイド体験をさせて貰うことになったのだ。
line = "マトイは最近、九浄家メイド隊でのバイトを始めていた。ヴィーナスに頼み、メイド体験をさせて貰うことになったのだ。"

[[dialogue]]
speaker = "unk"
# その指導を受け持つことになったのが――
line = "その指導を受け持つことになったのが――"

[[dialogue]]
speaker = "蘭美"
# 「なるほど。色々なことに挑戦してみたい、ね」
line = "「なるほど。色々なことに挑戦してみたい、ね」"

[[dialogue]]
speaker = "unk"
# 新星学園の飛び級３年生にして、九浄家メイド隊を率いる最年少メイド長、<ruby=はねみや>羽宮</ruby><ruby=らび>蘭美</ruby>。
line = "新星学園の飛び級３年生にして、九浄家メイド隊を率いる最年少メイド長、<ruby>羽宮<rt>はねみや</rt></ruby><ruby>蘭美<rt>らび</rt></ruby>。"

[[dialogue]]
speaker = "マトイ"
# 「はい。以前マムに、私は全部に適正があるって言われて。何が新フォーム覚醒のきっかけになるか分からないし、メイドの仕事にも挑戦してみたいと思って」
line = "「はい。以前マムに、私は全部に適正があるって言われて。何が新フォーム覚醒のきっかけになるか分からないし、メイドの仕事にも挑戦してみたいと思って」"

[[dialogue]]
speaker = "蘭美"
# 「事情は分かったわ。だけど、私が指導する以上、手を抜いたりなんてしないわよ？　それでもちゃんと付いて来られるのかしら？」
line = "「事情は分かったわ。だけど、私が指導する以上、手を抜いたりなんてしないわよ？　それでもちゃんと付いて来られるのかしら？」"

[[dialogue]]
speaker = "マトイ"
# 「もちろんです！　蘭美先輩、ご指導よろしくお願いします！」
line = "「もちろんです！　蘭美先輩、ご指導よろしくお願いします！」"

[[dialogue]]
speaker = "unk"
# バイトの研修が始まり、まずはひと通り、基礎的なメイドの仕事を叩きこまれることになった。
line = "バイトの研修が始まり、まずはひと通り、基礎的なメイドの仕事を叩きこまれることになった。"

[[dialogue]]
speaker = "マトイ"
# 「――よし、ここは綺麗になったかな。次は、えっと……」
line = "「――よし、ここは綺麗になったかな。次は、えっと……」"

[[dialogue]]
speaker = "蘭美"
# （ふむ、掃除の手際もそれなりね）
line = "（ふむ、掃除の手際もそれなりね）"

[[dialogue]]
speaker = "蘭美"
# （まあ、メイドとしての才能があるかどうかいえば『普通』といったところかしら）
line = "（まあ、メイドとしての才能があるかどうかいえば『普通』といったところかしら）"

[[dialogue]]
speaker = "マトイ"
# 「蘭美先輩、指示された場所の掃除、終わりました！　チェックお願いします」
line = "「蘭美先輩、指示された場所の掃除、終わりました！　チェックお願いします」"

[[dialogue]]
speaker = "蘭美"
# 「――うん。見逃しはなさそうね。次の指導に移るわよ！」
line = "「――うん。見逃しはなさそうね。次の指導に移るわよ！」"

[[dialogue]]
speaker = "unk"
# それから、マトイがメイドのバイトを始めて１ヶ月が経過──
line = "それから、マトイがメイドのバイトを始めて１ヶ月が経過──"

[[dialogue]]
speaker = "蘭美"
# 「私の指導に、普通について来ている……」
line = "「私の指導に、普通について来ている……」"

[[dialogue]]
speaker = "マトイ"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "蘭美"
# 「マトイ。あなた、メイドの才能があるわよ！」
line = "「マトイ。あなた、メイドの才能があるわよ！」"

[[dialogue]]
speaker = "蘭美"
# 「地味だから気づきにくいけれど……得意不得意がなく、教えたことがどれだけ難しいことでも、全て着実に覚えて行く」
line = "「地味だから気づきにくいけれど……得意不得意がなく、教えたことがどれだけ難しいことでも、全て着実に覚えて行く」"

[[dialogue]]
speaker = "マトイ"
# 「蘭美先輩の教え方が上手いからですよ」
line = "「蘭美先輩の教え方が上手いからですよ」"

[[dialogue]]
speaker = "マトイ"
# 「やっぱり、小さい時から訓練を積んでる天才メイド長は普通じゃないですね！」
line = "「やっぱり、小さい時から訓練を積んでる天才メイド長は普通じゃないですね！」"

[[dialogue]]
speaker = "蘭美"
# 「ふふん♪　それはそうよ！　なんせ私は小さい時から、最速でナンバー１メイドになることを目指して――」
line = "「ふふん♪　それはそうよ！　なんせ私は小さい時から、最速でナンバー１メイドになることを目指して――」"

[[dialogue]]
speaker = "蘭美"
# 「って、誰の胸が今も小さいままですって！？」
line = "「って、誰の胸が今も小さいままですって！？」"

[[dialogue]]
speaker = "マトイ"
# 「いや、誰も言ってないですよ！？」
line = "「いや、誰も言ってないですよ！？」"

[[dialogue]]
speaker = "蘭美"
# 「そうよね♪　私は小さくても、世界一可愛くて天才な美少女メイド長だもの！！」
line = "「そうよね♪　私は小さくても、世界一可愛くて天才な美少女メイド長だもの！！」"

[[dialogue]]
speaker = "マトイ"
# 「す、すごい……！　個性付けっていうのは、コンプレックスすら武器になるんだ！」
line = "「す、すごい……！　個性付けっていうのは、コンプレックスすら武器になるんだ！」"

[[dialogue]]
speaker = "蘭美"
# 「って、どこに感心してるのよ！？　そうじゃなくて！」
line = "「って、どこに感心してるのよ！？　そうじゃなくて！」"

[[dialogue]]
speaker = "蘭美"
# 「この私が褒めてるんだから、ちゃんと光栄に思って聞きなさい！」
line = "「この私が褒めてるんだから、ちゃんと光栄に思って聞きなさい！」"

[[dialogue]]
speaker = "蘭美"
# 「あなたは確かに、一般に言われるような天才ではないわ。でも、努力を重ねることで『多方面に強い秀才』になれるの！」
line = "「あなたは確かに、一般に言われるような天才ではないわ。でも、努力を重ねることで『多方面に強い秀才』になれるの！」"

[[dialogue]]
speaker = "蘭美"
# 「マトイ、あなたバイトじゃなくて、このまま九浄家メイド隊に正式入隊する気はない？」
line = "「マトイ、あなたバイトじゃなくて、このまま九浄家メイド隊に正式入隊する気はない？」"

[[dialogue]]
speaker = "マトイ"
# 「え？　私がですか……？」
line = "「え？　私がですか……？」"

[[dialogue]]
speaker = "マトイ"
# 「う～ん……蘭美先輩に認めてもらえるのはすごく光栄なんですけど、今はまだ色々なことに挑戦してみたいっていうか……」
line = "「う～ん……蘭美先輩に認めてもらえるのはすごく光栄なんですけど、今はまだ色々なことに挑戦してみたいっていうか……」"

[[dialogue]]
speaker = "蘭美"
# 「なら、こうしましょう――時間がある時でいいから、これからもバイトしに来なさい！」
line = "「なら、こうしましょう――時間がある時でいいから、これからもバイトしに来なさい！」"

[[dialogue]]
speaker = "蘭美"
# 「私が引き続き、世界に通用するメイドスキルをあなたに叩き込んであげるわ！」
line = "「私が引き続き、世界に通用するメイドスキルをあなたに叩き込んであげるわ！」"

[[dialogue]]
speaker = "蘭美"
# 「メイドスキルは将来、あなたが会長と結婚することになった時、必ず役に立つわよ？　家事万能の奥さん、男なら喜ばないわけがないわ！」
line = "「メイドスキルは将来、あなたが会長と結婚することになった時、必ず役に立つわよ？　家事万能の奥さん、男なら喜ばないわけがないわ！」"

[[dialogue]]
speaker = "マトイ"
# 「そ、それは確かに……！」
line = "「そ、それは確かに……！」"

[[dialogue]]
speaker = "蘭美"
# 「それに……恋人としてもご奉仕をしてあげれば、会長のハートはイチコロよ♪」
line = "「それに……恋人としてもご奉仕をしてあげれば、会長のハートはイチコロよ♪」"

[[dialogue]]
speaker = "マトイ"
# 「えぇっ！？　ご、ご奉仕って……それはちょっと恥ずかしいっていうか……」
line = "「えぇっ！？　ご、ご奉仕って……それはちょっと恥ずかしいっていうか……」"

[[dialogue]]
speaker = "蘭美"
# 「恋人同士なら、それくらい普通よ！！」
line = "「恋人同士なら、それくらい普通よ！！」"

[[dialogue]]
speaker = "マトイ"
# 「お、お帰りなさいませ～、ご主人様♪」
line = "「お、お帰りなさいませ～、ご主人様♪」"

[[dialogue]]
speaker = "unk"
# ま、マトイ？　一体どうしたんだ？
line = "ま、マトイ？　一体どうしたんだ？"

[[dialogue]]
speaker = "unk"
# 俺が星徒会室に入ると、マトイがメイドのように出迎えてくれた。
line = "俺が星徒会室に入ると、マトイがメイドのように出迎えてくれた。"

[[dialogue]]
speaker = "マトイ"
# 「緑茶と和菓子を用意したので、どうぞ……♪」
line = "「緑茶と和菓子を用意したので、どうぞ……♪」"

[[dialogue]]
speaker = "unk"
# 会長席に座ると、マトイが和菓子を楊枝で持ち上げ、口に運んでくれて――
line = "会長席に座ると、マトイが和菓子を楊枝で持ち上げ、口に運んでくれて――"

[[dialogue]]
speaker = "マトイ"
# 「はい、あ……あ～ん<emoji=heart04>」
line = "「はい、あ……あ～ん<emoji=heart04>」"

[[dialogue]]
speaker = "マトイ"
# 「ど、どう？　手作りの和菓子なんだけど、美味しい？」
line = "「ど、どう？　手作りの和菓子なんだけど、美味しい？」"

[[dialogue]]
speaker = "unk"
# うまいっ！　あと、嬉しい！！
line = "うまいっ！　あと、嬉しい！！"

[[dialogue]]
speaker = "マトイ"
# 「よかった～……えへへ<emoji=heart04>　蘭美先輩から、こうしたら会長も喜ぶはずだって……」
line = "「よかった～……えへへ<emoji=heart04>　蘭美先輩から、こうしたら会長も喜ぶはずだって……」"

[[dialogue]]
speaker = "蘭美"
# 「ふふふ、ご奉仕作戦、大成功ね！　マトイ」
line = "「ふふふ、ご奉仕作戦、大成功ね！　マトイ」"

[[dialogue]]
speaker = "unk"
# 星徒会室の階段の影から、蘭美が姿を現す。
line = "星徒会室の階段の影から、蘭美が姿を現す。"

[[dialogue]]
speaker = "マトイ"
# 「はい♪　メイドに挑戦してみて、よかったです！」
line = "「はい♪　メイドに挑戦してみて、よかったです！」"

[[dialogue]]
speaker = "マトイ"
# 「あと会長。これから私……なんでも普通にこなせる彼女を目指すから！」
line = "「あと会長。これから私……なんでも普通にこなせる彼女を目指すから！」"

[[dialogue]]
speaker = "unk"
# ん？　どういうこと？
line = "ん？　どういうこと？"

[[dialogue]]
speaker = "マトイ"
# 「ほら、メイドってご主人様の為にご奉仕するものでしょ？　だから――」
line = "「ほら、メイドってご主人様の為にご奉仕するものでしょ？　だから――」"

[[dialogue]]
speaker = "マトイ"
# 「会長が攻めだとしても受けだとしても、私、どっちも普通にこなしてみせるから！」
line = "「会長が攻めだとしても受けだとしても、私、どっちも普通にこなしてみせるから！」"

[[dialogue]]
speaker = "unk"
# 突然何を言ってんの！？
line = "突然何を言ってんの！？"

[[dialogue]]
speaker = "蘭美"
# 「……そ、その考えはちょっと普通じゃないわね」
line = "「……そ、その考えはちょっと普通じゃないわね」"

[[dialogue]]
speaker = "マトイ"
# 「あれぇ！？　なんで！？」
line = "「あれぇ！？　なんで！？」"

[[dialogue]]
speaker = "unk"
# 世界ナンバー２のメイドも思わず何とも言えない顔を浮かべる、マトイの発言なのであった――
line = "世界ナンバー２のメイドも思わず何とも言えない顔を浮かべる、マトイの発言なのであった――"
