[[dialogue]]
speaker = "unk"
# 第３話,アムとスペシャルハンバーグ,P
line = "第３話,アムとスペシャルハンバーグ,P"

[[dialogue]]
speaker = "アム"
# 「会長とこうして２人きりで過ごすのは、久しぶりだね～」
line = "「会長とこうして２人きりで過ごすのは、久しぶりだね～」"

[[dialogue]]
speaker = "unk"
# 今回のクリスマスは、アムとナミエルが二人三脚生活を送ることになり、その間、恋人である俺とは、２人きりで過ごすことが不可能な状況だった。
line = "今回のクリスマスは、アムとナミエルが二人三脚生活を送ることになり、その間、恋人である俺とは、２人きりで過ごすことが不可能な状況だった。"

[[dialogue]]
speaker = "unk"
# なので、改めて『２人でクリスマスパーティーをしよう』という話になり、俺たちは休日に家で過ごすことになったのだ。
line = "なので、改めて『２人でクリスマスパーティーをしよう』という話になり、俺たちは休日に家で過ごすことになったのだ。"

[[dialogue]]
speaker = "アム"
# 「でも、楽しみだな～♪　まさか、会長がパーティーのご馳走を作ってくれるだなんて！」
line = "「でも、楽しみだな～♪　まさか、会長がパーティーのご馳走を作ってくれるだなんて！」"

[[dialogue]]
speaker = "unk"
# アムは何が食べたい？
line = "アムは何が食べたい？"

[[dialogue]]
speaker = "アム"
# 「え？　あたしの食べたい物を言っていいの？　それじゃあ、えっと……ハンバーグとか？」
line = "「え？　あたしの食べたい物を言っていいの？　それじゃあ、えっと……ハンバーグとか？」"

[[dialogue]]
speaker = "unk"
# 俺はそれから、キッチンで準備をし、調理し始めた。
line = "俺はそれから、キッチンで準備をし、調理し始めた。"

[[dialogue]]
speaker = "アム"
# 「会長、すごい……！　あたしが言った料理を、レシピを見ずに、すぐにするっと作っちゃうなんて……！」
line = "「会長、すごい……！　あたしが言った料理を、レシピを見ずに、すぐにするっと作っちゃうなんて……！」"

[[dialogue]]
speaker = "アム"
# （なんか、星騎士として強いだけじゃなくて、私生活でもできる男って感じがして、カッコいい……！）
line = "（なんか、星騎士として強いだけじゃなくて、私生活でもできる男って感じがして、カッコいい……！）"

[[dialogue]]
speaker = "アム"
# （これがあたしの彼氏なんだよね……なんかキュンとしちゃうかも……<emoji=heart04>　『惚れ直す』ってこういうことなのかな……？）
line = "（これがあたしの彼氏なんだよね……なんかキュンとしちゃうかも……<emoji=heart04>　『惚れ直す』ってこういうことなのかな……？）"

[[dialogue]]
speaker = "unk"
# ん？　アム、どうかした？
line = "ん？　アム、どうかした？"

[[dialogue]]
speaker = "アム"
# 「え！？　あっ、ううん、なんでもないよ！　あはははっ……！」
line = "「え！？　あっ、ううん、なんでもないよ！　あはははっ……！」"

[[dialogue]]
speaker = "アム"
# （って、なんか照れて思わず誤魔化しちゃったけど……好きな人をちゃんと褒められないのは、『いい女』としてカッコよくないよね……）
line = "（って、なんか照れて思わず誤魔化しちゃったけど……好きな人をちゃんと褒められないのは、『いい女』としてカッコよくないよね……）"

[[dialogue]]
speaker = "アム"
# 「――ごめん、会長。なんでもないっていうのはウソ……あたし今、照れて誤魔化そうとしちゃった」
line = "「――ごめん、会長。なんでもないっていうのはウソ……あたし今、照れて誤魔化そうとしちゃった」"

[[dialogue]]
speaker = "アム"
# 「あのね……本当は、その……」
line = "「あのね……本当は、その……」"

[[dialogue]]
speaker = "アム"
# 「カッコいいなぁって思ったんだ、会長のこと。あたしの食べたいって言った料理をさらっと手作りしてくれて……」
line = "「カッコいいなぁって思ったんだ、会長のこと。あたしの食べたいって言った料理をさらっと手作りしてくれて……」"

[[dialogue]]
speaker = "unk"
# 好きな子に褒めてもらえて、嬉しい
line = "好きな子に褒めてもらえて、嬉しい"

[[dialogue]]
speaker = "アム"
# 「……！　え、えへへっ……そっか<emoji=heart04>」
line = "「……！　え、えへへっ……そっか<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その後、でき上がったハンバーグをアムは口にする。
line = "その後、でき上がったハンバーグをアムは口にする。"

[[dialogue]]
speaker = "アム"
# 「――いただきま～す♪　あむっ……もぐもぐ……ん～～っ<emoji=heart04>　これ、すごく美味しい！　お世辞抜きにこれ、あたしの好きな味だよっ♪」
line = "「――いただきま～す♪　あむっ……もぐもぐ……ん～～っ<emoji=heart04>　これ、すごく美味しい！　お世辞抜きにこれ、あたしの好きな味だよっ♪」"

[[dialogue]]
speaker = "unk"
# アムはハンバーグ、好きだよな
line = "アムはハンバーグ、好きだよな"

[[dialogue]]
speaker = "unk"
# カフェテリアでも一緒に食事をして、よく注文しているから、俺は知っていた。
line = "カフェテリアでも一緒に食事をして、よく注文しているから、俺は知っていた。"

[[dialogue]]
speaker = "アム"
# 「うん、ちょっと子供っぽいかも～って思って、頼むときに気恥ずかしくなっちゃう時もあるけど……」
line = "「うん、ちょっと子供っぽいかも～って思って、頼むときに気恥ずかしくなっちゃう時もあるけど……」"

[[dialogue]]
speaker = "アム"
# 「でも、昔からあたしの好物でさ。お母さんの得意料理で、頑張った時とか、お祝いの時は『スペシャルハンバーグ』を作ってくれるんだ」
line = "「でも、昔からあたしの好物でさ。お母さんの得意料理で、頑張った時とか、お祝いの時は『スペシャルハンバーグ』を作ってくれるんだ」"

[[dialogue]]
speaker = "アム"
# 「あっ、スペシャルっていうのは、いつも作ってくれるのより、ちょっと豪華なハンバーグでね？　それがレストランとかで出るのよりも、すっごく美味しいんだ♪」
line = "「あっ、スペシャルっていうのは、いつも作ってくれるのより、ちょっと豪華なハンバーグでね？　それがレストランとかで出るのよりも、すっごく美味しいんだ♪」"

[[dialogue]]
speaker = "unk"
# なんだか楽しそうに言うアムに、俺は１つ思いついたことを口にしてみる。
line = "なんだか楽しそうに言うアムに、俺は１つ思いついたことを口にしてみる。"

[[dialogue]]
speaker = "アム"
# 「えっ？　――今度あたしのお母さんに、どんなレシピで作っているのか、聞いてみたいって？」
line = "「えっ？　――今度あたしのお母さんに、どんなレシピで作っているのか、聞いてみたいって？」"

[[dialogue]]
speaker = "アム"
# 「それって……もしかして会長がスペシャルハンバーグを作ってくれるの！？　わぁ～、食べてみたい！」
line = "「それって……もしかして会長がスペシャルハンバーグを作ってくれるの！？　わぁ～、食べてみたい！」"

[[dialogue]]
speaker = "アム"
# 「それじゃあまた今度、うちに遊びに来る？　お母さんも喜ぶと思うよ！」
line = "「それじゃあまた今度、うちに遊びに来る？　お母さんも喜ぶと思うよ！」"

[[dialogue]]
speaker = "アム"
# 「――よ～し！　そうと決まれば、家に帰ったらすぐにお母さんに相談しないと！　えへへっ、楽しみだな～♪」
line = "「――よ～し！　そうと決まれば、家に帰ったらすぐにお母さんに相談しないと！　えへへっ、楽しみだな～♪」"

[[dialogue]]
speaker = "アム"
# 「って、そうだ！　今は恋人同士の時間なんだから、久しぶりにアレをやらないとね♪」
line = "「って、そうだ！　今は恋人同士の時間なんだから、久しぶりにアレをやらないとね♪」"

[[dialogue]]
speaker = "unk"
# アムはひと口サイズに切り分けたハンバーグをフォークで刺すと、俺の前に差し出してくる。
line = "アムはひと口サイズに切り分けたハンバーグをフォークで刺すと、俺の前に差し出してくる。"

[[dialogue]]
speaker = "アム"
# 「はい、会長、口開けて♪　ほら――あ～ん<emoji=heart04>」
line = "「はい、会長、口開けて♪　ほら――あ～ん<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺はそれに応じて、アムからハンバーグを食べさせてもらう。
line = "俺はそれに応じて、アムからハンバーグを食べさせてもらう。"

[[dialogue]]
speaker = "アム"
# 「ふふふっ、どう？　美味しい？　まあ、会長自身が作ったものなんだけどね♪」
line = "「ふふふっ、どう？　美味しい？　まあ、会長自身が作ったものなんだけどね♪」"

[[dialogue]]
speaker = "アム"
# 「でも、あたしから食べさせてもらえて、嬉しいでしょ～？　なんてね！　えへへっ♪」
line = "「でも、あたしから食べさせてもらえて、嬉しいでしょ～？　なんてね！　えへへっ♪」"

[[dialogue]]
speaker = "アム"
# 「――うん？　次は会長があたしに？　あ、あたしが先にやったんだから、お返しを恥ずかしがっちゃダメだよね……よ～し、バッチコイ！」
line = "「――うん？　次は会長があたしに？　あ、あたしが先にやったんだから、お返しを恥ずかしがっちゃダメだよね……よ～し、バッチコイ！」"

[[dialogue]]
speaker = "アム"
# 「あ、あ～ん……っ！　んっ……<emoji=heart04>　あむっ……もぐもぐ……」
line = "「あ、あ～ん……っ！　んっ……<emoji=heart04>　あむっ……もぐもぐ……」"

[[dialogue]]
speaker = "アム"
# （な、なんか自分で食べるのより、美味しく感じちゃうかも……<emoji=heart04>）
line = "（な、なんか自分で食べるのより、美味しく感じちゃうかも……<emoji=heart04>）"

[[dialogue]]
speaker = "unk"
# このまま最後まで食べる？
line = "このまま最後まで食べる？"

[[dialogue]]
speaker = "アム"
# 「えっ！？　そ、それは……なんかカッコよくないし……」
line = "「えっ！？　そ、それは……なんかカッコよくないし……」"

[[dialogue]]
speaker = "アム"
# 「だけど……会長がそう言うなら……今日はクリスマス気分で過ごす特別な日だし……うん<emoji=heart04>」
line = "「だけど……会長がそう言うなら……今日はクリスマス気分で過ごす特別な日だし……うん<emoji=heart04>」"

[[dialogue]]
speaker = "アム"
# 「あ、あ～ん……<emoji=heart04>」
line = "「あ、あ～ん……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# こくりと頷いて、あ～んと口を開けるアムが可愛くて、俺は幸せな気持ちになりながら、再びハンバーグを食べさせてあげるのだった。
line = "こくりと頷いて、あ～んと口を開けるアムが可愛くて、俺は幸せな気持ちになりながら、再びハンバーグを食べさせてあげるのだった。"
