[[dialogue]]
speaker = "unk"
# 第１話,シズハと初詣デート,P
line = "第１話,シズハと初詣デート,P"

[[dialogue]]
speaker = "unk"
# シズハと出会ってから初めて迎えたお正月。俺は流星寮を訪れて、彼女に告げる。
line = "シズハと出会ってから初めて迎えたお正月。俺は流星寮を訪れて、彼女に告げる。"

[[dialogue]]
speaker = "シズハ"
# 「えっ、私と会長で初詣に？　そ、その……私たち２人きりで？」
line = "「えっ、私と会長で初詣に？　そ、その……私たち２人きりで？」"

[[dialogue]]
speaker = "unk"
# 俺が頷くと、シズハは顔を赤らめ、もじもじとしながらも、小さく頷き返してくれた。
line = "俺が頷くと、シズハは顔を赤らめ、もじもじとしながらも、小さく頷き返してくれた。"

[[dialogue]]
speaker = "シズハ"
# 「う、うん。わかった……じゃあ２日後にね？」
line = "「う、うん。わかった……じゃあ２日後にね？」"

[[dialogue]]
speaker = "unk"
# そうして２日後、俺とシズハは浅草で初詣をすることになった。
line = "そうして２日後、俺とシズハは浅草で初詣をすることになった。"

[[dialogue]]
speaker = "unk"
# 晴れ着姿、今日も可愛くてよく似合ってるよ
line = "晴れ着姿、今日も可愛くてよく似合ってるよ"

[[dialogue]]
speaker = "シズハ"
# 「も、もうっ。会長ったら、初めて見せたわけじゃないのに、毎回言わなくても大丈夫だから……！」
line = "「も、もうっ。会長ったら、初めて見せたわけじゃないのに、毎回言わなくても大丈夫だから……！」"

[[dialogue]]
speaker = "シズハ"
# 「べ、別に嬉しくないわけじゃないけど、毎回照れちゃうでしょ……！」
line = "「べ、別に嬉しくないわけじゃないけど、毎回照れちゃうでしょ……！」"

[[dialogue]]
speaker = "unk"
# それでも俺は、シズハのことを異性として『可愛い』と感じていて、毎回でも伝えたいと思ってしまうのだから、仕方がない。
line = "それでも俺は、シズハのことを異性として『可愛い』と感じていて、毎回でも伝えたいと思ってしまうのだから、仕方がない。"

[[dialogue]]
speaker = "シズハ"
# 「――き、今日も手を繋ぐの？　う、うん、わかったわ。それじゃあ……」
line = "「――き、今日も手を繋ぐの？　う、うん、わかったわ。それじゃあ……」"

[[dialogue]]
speaker = "unk"
# シズハが差し出した手を、俺はそっと受け取り優しく握る。２人で並んで大きな門をくぐり、境内の方へと歩き始めた。
line = "シズハが差し出した手を、俺はそっと受け取り優しく握る。２人で並んで大きな門をくぐり、境内の方へと歩き始めた。"

[[dialogue]]
speaker = "シズハ"
# （はうぅ～<emoji=heart04>　遊園地デートに行ってから、会長とよくお出かけするようになったけど、いつもデートみたいな感じになっちゃってる……<emoji=heart04>）
line = "（はうぅ～<emoji=heart04>　遊園地デートに行ってから、会長とよくお出かけするようになったけど、いつもデートみたいな感じになっちゃってる……<emoji=heart04>）"

[[dialogue]]
speaker = "シズハ"
# （まだお付き合いもしてないのに、２人で出かける時は手を繋ぐのが当たり前になっちゃってるし……<emoji=heart04>）
line = "（まだお付き合いもしてないのに、２人で出かける時は手を繋ぐのが当たり前になっちゃってるし……<emoji=heart04>）"

[[dialogue]]
speaker = "unk"
# それから俺たちがお寺の本堂へ進むと、参拝する人たちで列ができており、その最後尾に並ぶことになった。
line = "それから俺たちがお寺の本堂へ進むと、参拝する人たちで列ができており、その最後尾に並ぶことになった。"

[[dialogue]]
speaker = "シズハ"
# （デートばっかり意識しちゃってたけど、マイナスエネルギーの問題解決の為にも、しっかり女神様にお願いしとかないと）
line = "（デートばっかり意識しちゃってたけど、マイナスエネルギーの問題解決の為にも、しっかり女神様にお願いしとかないと）"

[[dialogue]]
speaker = "シズハ"
# （あ、あと、他には……会長とこれからどうなりたいか、とか……）
line = "（あ、あと、他には……会長とこれからどうなりたいか、とか……）"

[[dialogue]]
speaker = "シズハ"
# （今年は会長との関係、ちょっと進んじゃったりして……？　例えば、その……もしかしたら男女のお付き合いを始めたり、なんて……<emoji=heart04>）
line = "（今年は会長との関係、ちょっと進んじゃったりして……？　例えば、その……もしかしたら男女のお付き合いを始めたり、なんて……<emoji=heart04>）"

[[dialogue]]
speaker = "シズハ"
# （か、会長の方はどんなことお願いするんだろう……？　私とのこと……お願いしてくれてたりとか、するのかな？）
line = "（か、会長の方はどんなことお願いするんだろう……？　私とのこと……お願いしてくれてたりとか、するのかな？）"

[[dialogue]]
speaker = "unk"
# ん？　シズハ、俺の顔を見て、どうかした？
line = "ん？　シズハ、俺の顔を見て、どうかした？"

[[dialogue]]
speaker = "シズハ"
# 「えっ！？　あ、ううん、ごめんね！　会長が何をお願いするのかな～、なんて、ちょっと考えたりしてて……」
line = "「えっ！？　あ、ううん、ごめんね！　会長が何をお願いするのかな～、なんて、ちょっと考えたりしてて……」"

[[dialogue]]
speaker = "シズハ"
# 「――後で教えるから待ってて欲しい？　そ、それってどういう……？」
line = "「――後で教えるから待ってて欲しい？　そ、それってどういう……？」"

[[dialogue]]
speaker = "unk"
# 俺はシズハの耳元で、周りには聞かれないくらいの小さな声で囁く。
line = "俺はシズハの耳元で、周りには聞かれないくらいの小さな声で囁く。"

[[dialogue]]
speaker = "unk"
# まだ秘密
line = "まだ秘密"

[[dialogue]]
speaker = "シズハ"
# 「ひゃっ……！？」
line = "「ひゃっ……！？」"

[[dialogue]]
speaker = "シズハ"
# （み、耳元でそんな甘い声で囁かれたら、ドキッとしちゃうじゃない……！）
line = "（み、耳元でそんな甘い声で囁かれたら、ドキッとしちゃうじゃない……！）"

[[dialogue]]
speaker = "シズハ"
# （しかも会長、繋いだ手をさっきよりもぎゅって、しっかり握ってきて……な、なんか今日の会長、すごく甘口じゃない！？）
line = "（しかも会長、繋いだ手をさっきよりもぎゅって、しっかり握ってきて……な、なんか今日の会長、すごく甘口じゃない！？）"

[[dialogue]]
speaker = "unk"
# それから俺たちの参拝する番がきて、２人で並んで手を合わせる。
line = "それから俺たちの参拝する番がきて、２人で並んで手を合わせる。"

[[dialogue]]
speaker = "シズハ"
# （会長はどんなことをお祈りしてるんだろう……？　というか、変に意識しちゃってるせいか……）
line = "（会長はどんなことをお祈りしてるんだろう……？　というか、変に意識しちゃってるせいか……）"

[[dialogue]]
speaker = "シズハ"
# （横顔見てると、いつもよりカッコよく見えて、なんか胸がドキドキしちゃう……！）
line = "（横顔見てると、いつもよりカッコよく見えて、なんか胸がドキドキしちゃう……！）"

[[dialogue]]
speaker = "unk"
# 俺がお祈りを終えて顔を上げると、横からシズハの視線を感じて振り返る。
line = "俺がお祈りを終えて顔を上げると、横からシズハの視線を感じて振り返る。"

[[dialogue]]
speaker = "unk"
# シズハのお願いは、もう終わった？
line = "シズハのお願いは、もう終わった？"

[[dialogue]]
speaker = "シズハ"
# 「え？　う、うん……！」
line = "「え？　う、うん……！」"

[[dialogue]]
speaker = "シズハ"
# （ぜ、全然集中できなくて、お願いできなかった……！　というか、ここでさり気なく、にこっと微笑みかけてくるの、ずるい……！）
line = "（ぜ、全然集中できなくて、お願いできなかった……！　というか、ここでさり気なく、にこっと微笑みかけてくるの、ずるい……！）"

[[dialogue]]
speaker = "シズハ"
# 「か、会長……？　こんな隅っこに移動して、話したいことって……？」
line = "「か、会長……？　こんな隅っこに移動して、話したいことって……？」"

[[dialogue]]
speaker = "unk"
# 参拝でお願いを済ませ、覚悟は決めた。
line = "参拝でお願いを済ませ、覚悟は決めた。"

[[dialogue]]
speaker = "unk"
# 俺は静かに深呼吸をしてからシズハに目を向け、ゆっくりと口を開いた。
line = "俺は静かに深呼吸をしてからシズハに目を向け、ゆっくりと口を開いた。"

[[dialogue]]
speaker = "unk"
# もちろん、１人の女の子、異性として
line = "もちろん、１人の女の子、異性として"

[[dialogue]]
speaker = "unk"
# 俺はシズハのことが好きだ。
line = "俺はシズハのことが好きだ。"

[[dialogue]]
speaker = "シズハ"
# 「……！　そ、それってつまり……」
line = "「……！　そ、それってつまり……」"

[[dialogue]]
speaker = "unk"
# 俺はシズハと恋人として付き合いたい、と今日まで引っ張ってきた想いを告げる。
line = "俺はシズハと恋人として付き合いたい、と今日まで引っ張ってきた想いを告げる。"

[[dialogue]]
speaker = "シズハ"
# 「～～～っ！　ば、バカバカ！　いきなり何告白してるの、会長っ……！」
line = "「～～～っ！　ば、バカバカ！　いきなり何告白してるの、会長っ……！」"

[[dialogue]]
speaker = "シズハ"
# 「――いきなりじゃなくて、これまで何度もデートをして、アピールを重ねてきたつもり？」
line = "「――いきなりじゃなくて、これまで何度もデートをして、アピールを重ねてきたつもり？」"

[[dialogue]]
speaker = "シズハ"
# 「た、確かにそうかもしれないけど！　少し前まで病院暮らしだったから、告白されるのなんて生まれて初めてなんだからっ！　テンパっちゃうの！」
line = "「た、確かにそうかもしれないけど！　少し前まで病院暮らしだったから、告白されるのなんて生まれて初めてなんだからっ！　テンパっちゃうの！」"

[[dialogue]]
speaker = "unk"
# 顔を赤らめて動揺しているシズハに、俺はそっと歩み寄り、その手を取って繋ぐ。
line = "顔を赤らめて動揺しているシズハに、俺はそっと歩み寄り、その手を取って繋ぐ。"

[[dialogue]]
speaker = "シズハ"
# 「えっ……？　――返事は落ち着いてからでいい……？」
line = "「えっ……？　――返事は落ち着いてからでいい……？」"

[[dialogue]]
speaker = "unk"
# 俺は頷く。シズハが好きだから、恋人になりたい――まずはそう伝えることで、今までの関係から新しい１歩を踏み出したかった。
line = "俺は頷く。シズハが好きだから、恋人になりたい――まずはそう伝えることで、今までの関係から新しい１歩を踏み出したかった。"

[[dialogue]]
speaker = "シズハ"
# 「――だから落ち着いてから、私の気持ちを教えて欲しい、って……」
line = "「――だから落ち着いてから、私の気持ちを教えて欲しい、って……」"

[[dialogue]]
speaker = "シズハ"
# 「…………バカ、会長」
line = "「…………バカ、会長」"

[[dialogue]]
speaker = "unk"
# シズハは顔を真っ赤にし、恥ずかしそうに視線を合わせないまま、言葉をこぼした。
line = "シズハは顔を真っ赤にし、恥ずかしそうに視線を合わせないまま、言葉をこぼした。"

[[dialogue]]
speaker = "シズハ"
# 「そんなの……何度も一緒にデートに出かけてるんだから、嫌いなわけないじゃない……」
line = "「そんなの……何度も一緒にデートに出かけてるんだから、嫌いなわけないじゃない……」"

[[dialogue]]
speaker = "unk"
# じゃあ……
line = "じゃあ……"

[[dialogue]]
speaker = "シズハ"
# 「んっ♪　新年は、いけいけゴーゴーってこと……<emoji=heart04>」
line = "「んっ♪　新年は、いけいけゴーゴーってこと……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# こくんと頷いて、口元に照れた笑みを浮かべるシズハ。
line = "こくんと頷いて、口元に照れた笑みを浮かべるシズハ。"

[[dialogue]]
speaker = "unk"
# それからシズハは繋いだ手の指先を絡めると、そっと恋人繋ぎにするのだった。
line = "それからシズハは繋いだ手の指先を絡めると、そっと恋人繋ぎにするのだった。"
