[[dialogue]]
speaker = "unk"
# 第２話,ミウの放課後クラストーク,P
line = "第２話,ミウの放課後クラストーク,P"

[[dialogue]]
speaker = "女学生"
# 「ミウって会長さんとお付き合いしてるんでしょー？　どっちから告白したのー？」
line = "「ミウって会長さんとお付き合いしてるんでしょー？　どっちから告白したのー？」"

[[dialogue]]
speaker = "ミウ"
# 「会長さんからですよ。デートに誘ってくれた日の帰り際に告白してくれたんです」
line = "「会長さんからですよ。デートに誘ってくれた日の帰り際に告白してくれたんです」"

[[dialogue]]
speaker = "ミウ"
# 「映画を見終わった後で、夜の公園で抱きしめながら『好きだよ、付き合ってください』って言ってくれました」
line = "「映画を見終わった後で、夜の公園で抱きしめながら『好きだよ、付き合ってください』って言ってくれました」"

[[dialogue]]
speaker = "女学生"
# 「ロマンチックー！　さすがは会長さんだねー。憧れてる人いっぱいいるモテモテ会長さんを惚れさせちゃうなんて、ミウちゃんってやっぱスゴーい！」
line = "「ロマンチックー！　さすがは会長さんだねー。憧れてる人いっぱいいるモテモテ会長さんを惚れさせちゃうなんて、ミウちゃんってやっぱスゴーい！」"

[[dialogue]]
speaker = "ミウ"
# 「そ、そうかな？　えへへ、彼氏を褒められると悪い気はしないですね」
line = "「そ、そうかな？　えへへ、彼氏を褒められると悪い気はしないですね」"

[[dialogue]]
speaker = "ミウ"
# （事前に計画していたプランがちょっと崩れて、グダグダにはなっちゃったけどね……）
line = "（事前に計画していたプランがちょっと崩れて、グダグダにはなっちゃったけどね……）"

[[dialogue]]
speaker = "ミウ"
# （涙でべしょべしょだったし、会長さんにフォローしてもらったみたいな告白だったけど……嘘は言ってないよね？）
line = "（涙でべしょべしょだったし、会長さんにフォローしてもらったみたいな告白だったけど……嘘は言ってないよね？）"

[[dialogue]]
speaker = "ヒマワリ"
# 「ニヨニヨ<emoji=heart04>」
line = "「ニヨニヨ<emoji=heart04>」"

[[dialogue]]
speaker = "ミウ"
# 「……ヒマワリちゃん、何か言いたそうだね？」
line = "「……ヒマワリちゃん、何か言いたそうだね？」"

[[dialogue]]
speaker = "ヒマワリ"
# 「んーんー？　べっつにー、なーんにもー？」
line = "「んーんー？　べっつにー、なーんにもー？」"

[[dialogue]]
speaker = "女学生"
# 「ヒマワリちゃんはなんか知ってるの？　ミウちゃんと仲良いもんねー」
line = "「ヒマワリちゃんはなんか知ってるの？　ミウちゃんと仲良いもんねー」"

[[dialogue]]
speaker = "ヒマワリ"
# 「ミウとは大親友だもん。いろいろ聞いたからね♪」
line = "「ミウとは大親友だもん。いろいろ聞いたからね♪」"

[[dialogue]]
speaker = "ミウ"
# 「ヒマワリちゃん、絶対に言っちゃダメだからね！？」
line = "「ヒマワリちゃん、絶対に言っちゃダメだからね！？」"

[[dialogue]]
speaker = "ヒマワリ"
# 「言わないってばー。他の人には絶対秘密って約束したもんね」
line = "「言わないってばー。他の人には絶対秘密って約束したもんね」"

[[dialogue]]
speaker = "ミウ"
# （前々から私の気持ちを知っていて、恋愛相談にも乗ってくれていた親友のヒマワリちゃんには、告白の時の話をしちゃったんだよね……）
line = "（前々から私の気持ちを知っていて、恋愛相談にも乗ってくれていた親友のヒマワリちゃんには、告白の時の話をしちゃったんだよね……）"

[[dialogue]]
speaker = "ミウ"
# （だって、ヒマワリちゃんが激詰めしてくるし、話してくれないなら会長さんに直接聞きに行くなんて言うから渋々……）
line = "（だって、ヒマワリちゃんが激詰めしてくるし、話してくれないなら会長さんに直接聞きに行くなんて言うから渋々……）"

[[dialogue]]
speaker = "ミウ"
# 「──って感じになっちゃったの……」
line = "「──って感じになっちゃったの……」"

[[dialogue]]
speaker = "ヒマワリ"
# 「えー！？　ミウもパニクっちゃうことってあるんだ！？」
line = "「えー！？　ミウもパニクっちゃうことってあるんだ！？」"

[[dialogue]]
speaker = "ヒマワリ"
# 「でも、なんか可愛いー！　やっぱりミウも恋する女の子なんだねー！」
line = "「でも、なんか可愛いー！　やっぱりミウも恋する女の子なんだねー！」"

[[dialogue]]
speaker = "ミウ"
# 「もう、私のことなんだと思ってたの？　そうやって冷やかされるから言いたくなかったのに」
line = "「もう、私のことなんだと思ってたの？　そうやって冷やかされるから言いたくなかったのに」"

[[dialogue]]
speaker = "ヒマワリ"
# 「冷やかしてなんかないよー。ミウの可愛いとこを新しく見つけたってだけ！」
line = "「冷やかしてなんかないよー。ミウの可愛いとこを新しく見つけたってだけ！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「いろいろあったかもだけど、会長さんとお付き合いできて、良かったじゃん」
line = "「いろいろあったかもだけど、会長さんとお付き合いできて、良かったじゃん」"

[[dialogue]]
speaker = "ミウ"
# 「……うん、ありがと」
line = "「……うん、ありがと」"

[[dialogue]]
speaker = "ヒマワリ"
# 「会長さんとラブラブなのはいいけど、遊んでくれなくなっちゃうと困るなー。これからもあたしたちは親友だからね！」
line = "「会長さんとラブラブなのはいいけど、遊んでくれなくなっちゃうと困るなー。これからもあたしたちは親友だからね！」"

[[dialogue]]
speaker = "ミウ"
# 「もちろん、ヒマワリちゃんはずっと親友だよ！　あっ、告白の話は絶対誰にも言っちゃダメだからね！」
line = "「もちろん、ヒマワリちゃんはずっと親友だよ！　あっ、告白の話は絶対誰にも言っちゃダメだからね！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「わかってるってばー。ミウの恥ずかしい秘密は、あたしとミウだけのものー♪」
line = "「わかってるってばー。ミウの恥ずかしい秘密は、あたしとミウだけのものー♪」"

[[dialogue]]
speaker = "ミウ"
# 「もうっ、ヒマワリちゃんっ！」
line = "「もうっ、ヒマワリちゃんっ！」"

[[dialogue]]
speaker = "unk"
# ミウを迎えに附属教室に向かったのだが、何やら同級生たちと話が盛り上がっている様子だった。
line = "ミウを迎えに附属教室に向かったのだが、何やら同級生たちと話が盛り上がっている様子だった。"

[[dialogue]]
speaker = "ヒマワリ"
# 「あ！　噂をすればなんとやらの会長さんだー。どしたのー？」
line = "「あ！　噂をすればなんとやらの会長さんだー。どしたのー？」"

[[dialogue]]
speaker = "ミウ"
# 「あっ……！　校門の前で待っててくださいって言ってたのに……！」
line = "「あっ……！　校門の前で待っててくださいって言ってたのに……！」"

[[dialogue]]
speaker = "unk"
# ミウとの放課後デートの約束してたからさ
line = "ミウとの放課後デートの約束してたからさ"

[[dialogue]]
speaker = "unk"
# 星徒会の仕事が早く終わったからさ
line = "星徒会の仕事が早く終わったからさ"

[[dialogue]]
speaker = "ヒマワリ"
# 「ミウとデートなんだー！　待ちきれなくて迎えに来ちゃったんですね」
line = "「ミウとデートなんだー！　待ちきれなくて迎えに来ちゃったんですね」"

[[dialogue]]
speaker = "女学生"
# 「やっぱり会長さん、ミウちゃんにラブラブなんだー。いいなー、私も素敵な彼氏欲しいよー」
line = "「やっぱり会長さん、ミウちゃんにラブラブなんだー。いいなー、私も素敵な彼氏欲しいよー」"

[[dialogue]]
speaker = "ヒマワリ"
# 「会長さんは、ミウのどんなところが好きなんですー？」
line = "「会長さんは、ミウのどんなところが好きなんですー？」"

[[dialogue]]
speaker = "ミウ"
# 「し、失礼だよ、ヒマワリちゃん！　か、会長さん、別に答えなくても──」
line = "「し、失礼だよ、ヒマワリちゃん！　か、会長さん、別に答えなくても──」"

[[dialogue]]
speaker = "unk"
# 俺のことが大好きなとこ、かな
line = "俺のことが大好きなとこ、かな"

[[dialogue]]
speaker = "ミウ"
# 「んにゃっ……！？」
line = "「んにゃっ……！？」"

[[dialogue]]
speaker = "女学生"
# 「きゃー、両想いだーっ♪」
line = "「きゃー、両想いだーっ♪」"

[[dialogue]]
speaker = "ヒマワリ"
# 「たまに意地っ張りなとこもあるけど、可愛い所もあるから、会長さん、ミウと仲良くしてあげてね！」
line = "「たまに意地っ張りなとこもあるけど、可愛い所もあるから、会長さん、ミウと仲良くしてあげてね！」"

[[dialogue]]
speaker = "unk"
# ミウの可愛い所は俺が１番知ってるからね
line = "ミウの可愛い所は俺が１番知ってるからね"

[[dialogue]]
speaker = "unk"
# 言われなくても！
line = "言われなくても！"

[[dialogue]]
speaker = "ヒマワリ"
# 「なにをーっ！　ミウのことなら、あたしだっていっぱい知ってるしー！」
line = "「なにをーっ！　ミウのことなら、あたしだっていっぱい知ってるしー！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「んー、でも、女のあたしじゃ見られないところも、会長さんは見ちゃってるのかな……？」
line = "「んー、でも、女のあたしじゃ見られないところも、会長さんは見ちゃってるのかな……？」"

[[dialogue]]
speaker = "ミウ"
# 「もう、ヒマワリちゃんっ！　会長さん、早く行かないとお店閉まっちゃいますよ！　みんなまた明日ね！」
line = "「もう、ヒマワリちゃんっ！　会長さん、早く行かないとお店閉まっちゃいますよ！　みんなまた明日ね！」"

[[dialogue]]
speaker = "女学生"
# 「うん、また明日ねー」
line = "「うん、また明日ねー」"

[[dialogue]]
speaker = "ヒマワリ"
# 「末永くお幸せにー♪」
line = "「末永くお幸せにー♪」"

[[dialogue]]
speaker = "unk"
# ヒマワリに冷やかされながらも、ミウは俺の手を引いて教室を離れるのだった。
line = "ヒマワリに冷やかされながらも、ミウは俺の手を引いて教室を離れるのだった。"
