[[dialogue]]
speaker = "unk"
# 第１話,妄想天使の異変,P
line = "第１話,妄想天使の異変,P"

[[dialogue]]
speaker = "unk"
# 最近、恋人であるイクシーの様子がなんだかおかしい。
line = "最近、恋人であるイクシーの様子がなんだかおかしい。"

[[dialogue]]
speaker = "unk"
# バレンタインが過ぎてから少し経ち、俺とイクシーは日課の戦闘訓練を仮想結界内で行っていたのだが……。
line = "バレンタインが過ぎてから少し経ち、俺とイクシーは日課の戦闘訓練を仮想結界内で行っていたのだが……。"

[[dialogue]]
speaker = "イクシリオン"
# 「ひゃっ！？　か、会長、申し訳ありません……！」
line = "「ひゃっ！？　か、会長、申し訳ありません……！」"

[[dialogue]]
speaker = "unk"
# 隣で休憩していて、ちょっと手が触れただけで、顔を赤くしたり。
line = "隣で休憩していて、ちょっと手が触れただけで、顔を赤くしたり。"

[[dialogue]]
speaker = "イクシリオン"
# 「あ、あの……会長、そんなじっと見つめられると、恥ずかしいです……<emoji=heart04>」
line = "「あ、あの……会長、そんなじっと見つめられると、恥ずかしいです……<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「バレンタインフォーム、この前覚醒したばかりで、まだ着慣れていないので……」
line = "「バレンタインフォーム、この前覚醒したばかりで、まだ着慣れていないので……」"

[[dialogue]]
speaker = "unk"
# 俺がちょっと見つめただけで、もじもじと恥じらったり。
line = "俺がちょっと見つめただけで、もじもじと恥じらったり。"

[[dialogue]]
speaker = "unk"
# この前チョコを渡してくれたときもそうだ。バレンタインフォームにいつの間にか覚醒していたことにも驚いたけれど、やけに緊張している様子が印象に残っていた。
line = "この前チョコを渡してくれたときもそうだ。バレンタインフォームにいつの間にか覚醒していたことにも驚いたけれど、やけに緊張している様子が印象に残っていた。"

[[dialogue]]
speaker = "unk"
# イクシー、最近何かあったのか？
line = "イクシー、最近何かあったのか？"

[[dialogue]]
speaker = "イクシリオン"
# 「え？　何か……と言いますと？」
line = "「え？　何か……と言いますと？」"

[[dialogue]]
speaker = "イクシリオン"
# 「――最近、私が会長に対して、前より恥ずかしがっているような気がする……？　そ、それは……」
line = "「――最近、私が会長に対して、前より恥ずかしがっているような気がする……？　そ、それは……」"

[[dialogue]]
speaker = "イクシリオン"
# 「その……心配かけて申し訳ありません。実は、会長と付き合い続ける内に、私――」
line = "「その……心配かけて申し訳ありません。実は、会長と付き合い続ける内に、私――」"

[[dialogue]]
speaker = "イクシリオン"
# 「会長のことが……<b>前より好き</b>になってしまったみたいで……<emoji=heart04>」
line = "「会長のことが……<b>前より好き</b>になってしまったみたいで……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# え？　ど、どういうこと？
line = "え？　ど、どういうこと？"

[[dialogue]]
speaker = "イクシリオン"
# 「会長が男らしく頼りになるところを見せて下さったり……優しく気遣って下さったり。それを近くで見ている内に……」
line = "「会長が男らしく頼りになるところを見せて下さったり……優しく気遣って下さったり。それを近くで見ている内に……」"

[[dialogue]]
speaker = "イクシリオン"
# 「私、会長に改めて、こ、『恋をしている』ような気持ちになってしまって……<emoji=heart04>」
line = "「私、会長に改めて、こ、『恋をしている』ような気持ちになってしまって……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 『恋』というワードと熱のこもった視線に、俺は思わずドキッとしてしまう。
line = "『恋』というワードと熱のこもった視線に、俺は思わずドキッとしてしまう。"

[[dialogue]]
speaker = "イクシリオン"
# 「なので、自分のはしたない部分を見られるのが、恥ずかしくなってしまうというか……」
line = "「なので、自分のはしたない部分を見られるのが、恥ずかしくなってしまうというか……」"

[[dialogue]]
speaker = "イクシリオン"
# 「以前の水着フォームの時は、会長に自分を曝け出したいと思っていたんです。でも今は……女の子として、会長にもっと好きになってもらいたいと思っていて……」
line = "「以前の水着フォームの時は、会長に自分を曝け出したいと思っていたんです。でも今は……女の子として、会長にもっと好きになってもらいたいと思っていて……」"

[[dialogue]]
speaker = "イクシリオン"
# 「だから、私……会長にもう１度好きになってもらえるように、頑張ります<emoji=heart04>」
line = "「だから、私……会長にもう１度好きになってもらえるように、頑張ります<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺はイクシーのこと、ちゃんと好きだぞ？
line = "俺はイクシーのこと、ちゃんと好きだぞ？"

[[dialogue]]
speaker = "イクシリオン"
# 「あ、ありがとうございます。いつも優しくして頂いて……すごく伝わってきています<emoji=heart04>」
line = "「あ、ありがとうございます。いつも優しくして頂いて……すごく伝わってきています<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# 「なので、不束者ですが、これからもお付き合い頂けると嬉しいです……<emoji=heart04>」
line = "「なので、不束者ですが、これからもお付き合い頂けると嬉しいです……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 清楚な恥じらいを帯びた微笑みに、俺もなんだか顔が熱くなってしまって。
line = "清楚な恥じらいを帯びた微笑みに、俺もなんだか顔が熱くなってしまって。"

[[dialogue]]
speaker = "イクシリオン"
# 「それでは会長、引き続き、訓練のお相手をよろしくお願い致します<emoji=heart04>」
line = "「それでは会長、引き続き、訓練のお相手をよろしくお願い致します<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その日はイクシーと触れ合うどころか、目もちゃんと合わせられなくなってしまうくらい、ドキドキしてしまうのだった。
line = "その日はイクシーと触れ合うどころか、目もちゃんと合わせられなくなってしまうくらい、ドキドキしてしまうのだった。"

[[dialogue]]
speaker = "イクシリオン"
# 「ふぅ……なんとか今日も無事に訓練を終えることができました」
line = "「ふぅ……なんとか今日も無事に訓練を終えることができました」"

[[dialogue]]
speaker = "イクシリオン"
# （今日も会長がカッコよくて、危うく色々エッチな妄想を膨らませてしまうところでした……<emoji=heart04>）
line = "（今日も会長がカッコよくて、危うく色々エッチな妄想を膨らませてしまうところでした……<emoji=heart04>）"

[[dialogue]]
speaker = "イクシリオン"
# （普段は中性的なお顔なのに、戦闘訓練中は男らしい表情になって……はあぁ<emoji=heart04>）
line = "（普段は中性的なお顔なのに、戦闘訓練中は男らしい表情になって……はあぁ<emoji=heart04>）"

[[dialogue]]
speaker = "イクシリオン"
# （あの表情で見つめられると、ついベッドに押し倒される妄想をしてしまいそうになります……<emoji=heart04>）
line = "（あの表情で見つめられると、ついベッドに押し倒される妄想をしてしまいそうになります……<emoji=heart04>）"

[[dialogue]]
speaker = "イクシリオン"
# （それに訓練中に会長に近づくと、汗の匂いがして、つい激しく絡み合っている場面を妄想してしまい、興奮してしまって……<emoji=heart04>）
line = "（それに訓練中に会長に近づくと、汗の匂いがして、つい激しく絡み合っている場面を妄想してしまい、興奮してしまって……<emoji=heart04>）"

[[dialogue]]
speaker = "イクシリオン"
# （ああ……どうして会長は、あんなに汗だくになってもいい匂いがするのでしょう<emoji=heart04>）
line = "（ああ……どうして会長は、あんなに汗だくになってもいい匂いがするのでしょう<emoji=heart04>）"

[[dialogue]]
speaker = "イクシリオン"
# （ですが――それも会長に相応しい女性になろうというイメージに集中することで、なんとか抑え込むことができました）
line = "（ですが――それも会長に相応しい女性になろうというイメージに集中することで、なんとか抑え込むことができました）"

[[dialogue]]
speaker = "イクシリオン"
# （会長は、私の『妄想癖』という恥ずかしい部分も受け止めて下さる、優しくて包容力のある素敵な男性です……）
line = "（会長は、私の『妄想癖』という恥ずかしい部分も受け止めて下さる、優しくて包容力のある素敵な男性です……）"

[[dialogue]]
speaker = "イクシリオン"
# （でも、私はそれに甘えて努力しない自分でいたくない）
line = "（でも、私はそれに甘えて努力しない自分でいたくない）"

[[dialogue]]
speaker = "イクシリオン"
# （会長に惚れ直してもらえるような、『どこに出しても恥ずかしくない女性』を目指したいのです……！）
line = "（会長に惚れ直してもらえるような、『どこに出しても恥ずかしくない女性』を目指したいのです……！）"

[[dialogue]]
speaker = "イクシリオン"
# （ただ……会長を以前より好きになってしまったことで、最近はちょっと触れ合うだけでもドキドキしてしまって……）
line = "（ただ……会長を以前より好きになってしまったことで、最近はちょっと触れ合うだけでもドキドキしてしまって……）"

[[dialogue]]
speaker = "イクシリオン"
# （そのせいで、以前のように自然なスキンシップはできなくなってしまっていますが……）
line = "（そのせいで、以前のように自然なスキンシップはできなくなってしまっていますが……）"

[[dialogue]]
speaker = "イクシリオン"
# （本当は、会長にもっと触れてほしいです……<emoji=heart04>　抱き合って、キスして、もっと深く絡み合いたい……<emoji=heart04>）
line = "（本当は、会長にもっと触れてほしいです……<emoji=heart04>　抱き合って、キスして、もっと深く絡み合いたい……<emoji=heart04>）"

[[dialogue]]
speaker = "イクシリオン"
# 「はぁ……はぁ……<emoji=heart04>」
line = "「はぁ……はぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "イクシリオン"
# （はっ……！？　い、いけません。こんな外の暗い場所で妄想を膨らませて、息を荒くしては……！　不審な痴女だと思われてしまいます！）
line = "（はっ……！？　い、いけません。こんな外の暗い場所で妄想を膨らませて、息を荒くしては……！　不審な痴女だと思われてしまいます！）"

[[dialogue]]
speaker = "イクシリオン"
# （と、とりあえず、今日の訓練は終わったのですから、早く部屋に戻って休むとしましょう<emoji=heart04>）
line = "（と、とりあえず、今日の訓練は終わったのですから、早く部屋に戻って休むとしましょう<emoji=heart04>）"

[[dialogue]]
speaker = "unk"
# 顔を赤くしながらイクシリオンはそんなことを考え、いそいそと新星寮の自室へ戻っていくのだった。
line = "顔を赤くしながらイクシリオンはそんなことを考え、いそいそと新星寮の自室へ戻っていくのだった。"
