[[dialogue]]
speaker = "unk"
# 第２話,水着の監視者,P
line = "第２話,水着の監視者,P"

[[dialogue]]
speaker = "unk"
# 俺は息抜きにリゾート結界に来ていた……のだが──
line = "俺は息抜きにリゾート結界に来ていた……のだが──"

[[dialogue]]
speaker = "梨緒"
# 「じー……」
line = "「じー……」"

[[dialogue]]
speaker = "unk"
# どうして梨緒がここに？
line = "どうして梨緒がここに？"

[[dialogue]]
speaker = "梨緒"
# 「決まっている、君を監視するためだ」
line = "「決まっている、君を監視するためだ」"

[[dialogue]]
speaker = "梨緒"
# 「選挙管理委員会は、魔王にして星徒会長である君を監視するための組織。君が行くなら、たとえ火の中だろうが水の中だろうが駆けつける」
line = "「選挙管理委員会は、魔王にして星徒会長である君を監視するための組織。君が行くなら、たとえ火の中だろうが水の中だろうが駆けつける」"

[[dialogue]]
speaker = "梨緒"
# 「つまり、君がいるところ私ありだ」
line = "「つまり、君がいるところ私ありだ」"

[[dialogue]]
speaker = "梨緒"
# 「……まるで恋人みたいだって？」
line = "「……まるで恋人みたいだって？」"

[[dialogue]]
speaker = "梨緒"
# 「なななな、何を言ってるんだ君は！？　私はそんなつもりじゃないぞ！？」
line = "「なななな、何を言ってるんだ君は！？　私はそんなつもりじゃないぞ！？」"

[[dialogue]]
speaker = "梨緒"
# 「まったくもう……そんな浮ついたことを言ってナンパでもするんじゃないかと心配なんだ……」
line = "「まったくもう……そんな浮ついたことを言ってナンパでもするんじゃないかと心配なんだ……」"

[[dialogue]]
speaker = "梨緒"
# 「ただでさえ海で浮かれているだろうし、他の女性の水着姿に目を奪われたりしないか気になって……」
line = "「ただでさえ海で浮かれているだろうし、他の女性の水着姿に目を奪われたりしないか気になって……」"

[[dialogue]]
speaker = "unk"
# じー……
line = "じー……"

[[dialogue]]
speaker = "梨緒"
# 「な、何だ？　そんなに私をじっと見つめてどうした……？　監視しているのは私だぞ？」
line = "「な、何だ？　そんなに私をじっと見つめてどうした……？　監視しているのは私だぞ？」"

[[dialogue]]
speaker = "unk"
# 梨緒の水着、似合ってるよ
line = "梨緒の水着、似合ってるよ"

[[dialogue]]
speaker = "梨緒"
# 「何を言ってるんだ！？　私は遊びに来たんじゃないんだぞ！」
line = "「何を言ってるんだ！？　私は遊びに来たんじゃないんだぞ！」"

[[dialogue]]
speaker = "梨緒"
# 「水着がスタイリッシュで素敵……？　肌が綺麗？　ポニーテールが活動的でいい？　スタイルが良くて見惚れそう？」
line = "「水着がスタイリッシュで素敵……？　肌が綺麗？　ポニーテールが活動的でいい？　スタイルが良くて見惚れそう？」"

[[dialogue]]
speaker = "梨緒"
# 「そそそ、そんなことないぞっ！　私なんて水着に着られているだけだ！」
line = "「そそそ、そんなことないぞっ！　私なんて水着に着られているだけだ！」"

[[dialogue]]
speaker = "unk"
# 梨緒の水着が一番好きだよ
line = "梨緒の水着が一番好きだよ"

[[dialogue]]
speaker = "梨緒"
# 「～～～っ！？　君は本当に何を言ってるんだ！？」
line = "「～～～っ！？　君は本当に何を言ってるんだ！？」"

[[dialogue]]
speaker = "梨緒"
# 「私を懐柔しようとしたところで無駄だぞ！　選挙管理員会として、星徒会長の行いは厳正に見させてもらうからな！」
line = "「私を懐柔しようとしたところで無駄だぞ！　選挙管理員会として、星徒会長の行いは厳正に見させてもらうからな！」"

[[dialogue]]
speaker = "梨緒"
# 「君に水着を褒められても、別に私は嬉しくなんて──」
line = "「君に水着を褒められても、別に私は嬉しくなんて──」"

[[dialogue]]
speaker = "フィオナ"
# 「あら？」
line = "「あら？」"

[[dialogue]]
speaker = "梨緒"
# 「ひゃあっ！？」
line = "「ひゃあっ！？」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長に梨緒さん、こんなところで奇遇ですね」
line = "「緋宮会長に梨緒さん、こんなところで奇遇ですね」"

[[dialogue]]
speaker = "アポロ"
# 「よ、２人とも！」
line = "「よ、２人とも！」"

[[dialogue]]
speaker = "梨緒"
# 「アポロとフィオナ！？　君たちも来ていたのか？」
line = "「アポロとフィオナ！？　君たちも来ていたのか？」"

[[dialogue]]
speaker = "アポロ"
# 「ん？　もしかして２人はデートしてたのか？　だったら邪魔して悪かったな」
line = "「ん？　もしかして２人はデートしてたのか？　だったら邪魔して悪かったな」"

[[dialogue]]
speaker = "梨緒"
# 「デートじゃない！　選挙管理委員会として、魔王が星徒会長にふさわしくない行いをしないよう監視していただけだ！」
line = "「デートじゃない！　選挙管理委員会として、魔王が星徒会長にふさわしくない行いをしないよう監視していただけだ！」"

[[dialogue]]
speaker = "フィオナ"
# 「それにしてはお顔が赤いようですが……？」
line = "「それにしてはお顔が赤いようですが……？」"

[[dialogue]]
speaker = "梨緒"
# 「ちち、違うっ！　きっと日差しが強かったせいだ！」
line = "「ちち、違うっ！　きっと日差しが強かったせいだ！」"

[[dialogue]]
speaker = "梨緒"
# 「いいか、魔王。君が気の緩みを見せたら、私は選管として容赦なく君を摘発する」
line = "「いいか、魔王。君が気の緩みを見せたら、私は選管として容赦なく君を摘発する」"

[[dialogue]]
speaker = "梨緒"
# 「魔王がボロを出してくれるなら、それはそれで構わない。現会長である君を引きずり下ろし、私が星徒会長になるからな……！」
line = "「魔王がボロを出してくれるなら、それはそれで構わない。現会長である君を引きずり下ろし、私が星徒会長になるからな……！」"

[[dialogue]]
speaker = "unk"
# 梨緒はどうして星徒会長にこだわるんだ？
line = "梨緒はどうして星徒会長にこだわるんだ？"

[[dialogue]]
speaker = "梨緒"
# 「そういえば言っていなかったか？　すっかり話した気になっていたが……」
line = "「そういえば言っていなかったか？　すっかり話した気になっていたが……」"

[[dialogue]]
speaker = "梨緒"
# 「ベガのフィオナ──こちらではアポロと名乗っている、星見家の双子の姉の方だ。彼女と約束したんだ」
line = "「ベガのフィオナ──こちらではアポロと名乗っている、星見家の双子の姉の方だ。彼女と約束したんだ」"

[[dialogue]]
speaker = "梨緒"
# 「フィオナが流星学園の星徒会長に、私が新星学園の星徒会長になると」
line = "「フィオナが流星学園の星徒会長に、私が新星学園の星徒会長になると」"

[[dialogue]]
speaker = "フィオナ"
# 「ベガの私たちとはお知り合いだったんですか？」
line = "「ベガの私たちとはお知り合いだったんですか？」"

[[dialogue]]
speaker = "梨緒"
# 「ああ、私がイギリスから流星市国に来た頃に２人と出会って、友人になったんだ。一緒に星術の鍛錬をしたこともある」
line = "「ああ、私がイギリスから流星市国に来た頃に２人と出会って、友人になったんだ。一緒に星術の鍛錬をしたこともある」"

[[dialogue]]
speaker = "梨緒"
# 「だから星見家で目覚めた時は、エリシアがフィオナと名乗っているし、フィオナ──今のアポロが小さくなっているしで、本当に驚いた」
line = "「だから星見家で目覚めた時は、エリシアがフィオナと名乗っているし、フィオナ──今のアポロが小さくなっているしで、本当に驚いた」"

[[dialogue]]
speaker = "アポロ"
# 「なるほど。そりゃ梨緒が混乱するわけだ」
line = "「なるほど。そりゃ梨緒が混乱するわけだ」"

[[dialogue]]
speaker = "梨緒"
# 「だが結局、私が新星学園の星徒会長になることはなかった。ジグに阻まれたからだ」
line = "「だが結局、私が新星学園の星徒会長になることはなかった。ジグに阻まれたからだ」"

[[dialogue]]
speaker = "梨緒"
# 「今思い出しても憎たらしい……いや、よそう。負けた私が悪いんだ」
line = "「今思い出しても憎たらしい……いや、よそう。負けた私が悪いんだ」"

[[dialogue]]
speaker = "フィオナ"
# 「ベガではそんなことがあったんですね……」
line = "「ベガではそんなことがあったんですね……」"

[[dialogue]]
speaker = "アポロ"
# 「ベガのあたしか……デネブのあたしとも違うのか？」
line = "「ベガのあたしか……デネブのあたしとも違うのか？」"

[[dialogue]]
speaker = "梨緒"
# 「そうだな……ベガの君は星見家の後継者として育った分、行儀がいいというか、言葉遣いも丁寧で、令嬢然としていた」
line = "「そうだな……ベガの君は星見家の後継者として育った分、行儀がいいというか、言葉遣いも丁寧で、令嬢然としていた」"

[[dialogue]]
speaker = "梨緒"
# 「エリシア──フィオナはあまり変わらないが、こちらの君より少し甘えたがりだったな」
line = "「エリシア──フィオナはあまり変わらないが、こちらの君より少し甘えたがりだったな」"

[[dialogue]]
speaker = "フィオナ"
# 「私が……？　そう言われると少し恥ずかしいですね」
line = "「私が……？　そう言われると少し恥ずかしいですね」"

[[dialogue]]
speaker = "梨緒"
# 「ただ、流星ライダーが好きなことは２人とも変わらないな」
line = "「ただ、流星ライダーが好きなことは２人とも変わらないな」"

[[dialogue]]
speaker = "アポロ"
# 「お、そこは同じなんだな！　平行世界でもやっぱりあたしたちだ！」
line = "「お、そこは同じなんだな！　平行世界でもやっぱりあたしたちだ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ところで気になっていたのですが、梨緒さんが持っているその猫のキャラクターは？」
line = "「ところで気になっていたのですが、梨緒さんが持っているその猫のキャラクターは？」"

[[dialogue]]
speaker = "梨緒"
# 「これか？　これはぶちゃ猫というキャラクターなんだが、どうやらあまり人気がないみたいで……私は好きなんだが」
line = "「これか？　これはぶちゃ猫というキャラクターなんだが、どうやらあまり人気がないみたいで……私は好きなんだが」"

[[dialogue]]
speaker = "フィオナ"
# 「すごくかわいいと思います！　私は好きですよ！」
line = "「すごくかわいいと思います！　私は好きですよ！」"

[[dialogue]]
speaker = "unk"
# 俺も愛嬌があると思う
line = "俺も愛嬌があると思う"

[[dialogue]]
speaker = "梨緒"
# 「そ、そうか……？　そう思ってくれると嬉しいな……」
line = "「そ、そうか……？　そう思ってくれると嬉しいな……」"

[[dialogue]]
speaker = "アポロ"
# 「んじゃ、あたしたちはこれでな。流星星徒会のみんなが待ってるんだ」
line = "「んじゃ、あたしたちはこれでな。流星星徒会のみんなが待ってるんだ」"

[[dialogue]]
speaker = "フィオナ"
# 「デートのお邪魔してすみませんでした。おふたりで楽しんでくださいね」
line = "「デートのお邪魔してすみませんでした。おふたりで楽しんでくださいね」"

[[dialogue]]
speaker = "梨緒"
# 「だからデートじゃないと言っているだろう！」
line = "「だからデートじゃないと言っているだろう！」"

[[dialogue]]
speaker = "梨緒"
# 「……誤解したまま行ってしまった」
line = "「……誤解したまま行ってしまった」"

[[dialogue]]
speaker = "unk"
# 気を取り直して遊ぼう
line = "気を取り直して遊ぼう"

[[dialogue]]
speaker = "梨緒"
# 「……仕方ない。時間は有限だし、気持ちを切り替えよう」
line = "「……仕方ない。時間は有限だし、気持ちを切り替えよう」"

[[dialogue]]
speaker = "梨緒"
# 「海でまずやることは決まっている──水かけで勝負だ！」
line = "「海でまずやることは決まっている──水かけで勝負だ！」"

[[dialogue]]
speaker = "梨緒"
# 「やったな！　お返しだ……それ！」
line = "「やったな！　お返しだ……それ！」"

[[dialogue]]
speaker = "梨緒"
# 「あははっ、顔がビショビショだぞ魔王！」
line = "「あははっ、顔がビショビショだぞ魔王！」"

[[dialogue]]
speaker = "フィオナ"
# （緋宮会長と梨緒さんが楽しそうにしていますが……）
line = "（緋宮会長と梨緒さんが楽しそうにしていますが……）"

[[dialogue]]
speaker = "アポロ"
# （あいつら、やっぱりデートしてるんじゃないか……？）
line = "（あいつら、やっぱりデートしてるんじゃないか……？）"
