[[dialogue]]
speaker = "unk"
# 第１話,和菓子は神,P
line = "第１話,和菓子は神,P"

[[dialogue]]
speaker = "アナ"
# 「──ふう」
line = "「──ふう」"

[[dialogue]]
speaker = "アナ"
# 「会長、そろそろ休憩しましょう。仕事を始めてから２時間以上経過しています。ストレッチをして、少し身体をほぐすべき」
line = "「会長、そろそろ休憩しましょう。仕事を始めてから２時間以上経過しています。ストレッチをして、少し身体をほぐすべき」"

[[dialogue]]
speaker = "unk"
# それはアナの経験則？
line = "それはアナの経験則？"

[[dialogue]]
speaker = "アナ"
# 「長時間のデスクワークでは、適度な休憩が重要。要ブレイクタイムです」
line = "「長時間のデスクワークでは、適度な休憩が重要。要ブレイクタイムです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうよ！　そろそろ休憩するべきだわ！」
line = "「そうよ！　そろそろ休憩するべきだわ！」"

[[dialogue]]
speaker = "アナ"
# 「前会長。パトロールお疲れ様です。問題はありましたか？」
line = "「前会長。パトロールお疲れ様です。問題はありましたか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「街は平和そのものだったわ！　モンスターもなし、困ってる人もなし、天気もいいし最高の１日ね！」
line = "「街は平和そのものだったわ！　モンスターもなし、困ってる人もなし、天気もいいし最高の１日ね！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「新会長の仕事っぷりはどう？　ちゃんとやってるかしら」
line = "「新会長の仕事っぷりはどう？　ちゃんとやってるかしら」"

[[dialogue]]
speaker = "アナ"
# 「ノープロブレム。前会長の頃と比べると私の仕事量は１２０％くらいになりました」
line = "「ノープロブレム。前会長の頃と比べると私の仕事量は１２０％くらいになりました」"

[[dialogue]]
speaker = "ヴィーナス"
# 「増えたの？」
line = "「増えたの？」"

[[dialogue]]
speaker = "アナ"
# 「激減。前会長が実質ハンコ係だった頃は５００％を越えていた。それに比べて会長は予算のチェックまでしてくれるので、凄く楽」
line = "「激減。前会長が実質ハンコ係だった頃は５００％を越えていた。それに比べて会長は予算のチェックまでしてくれるので、凄く楽」"

[[dialogue]]
speaker = "ヴィーナス"
# 「さすがね、会長！　やっぱりあなたに星徒会長を任せて正解だったわ！」
line = "「さすがね、会長！　やっぱりあなたに星徒会長を任せて正解だったわ！」"

[[dialogue]]
speaker = "unk"
# ヴィーナス、皮肉って言葉を知ってるか？
line = "ヴィーナス、皮肉って言葉を知ってるか？"

[[dialogue]]
speaker = "ヴィーナス"
# 「なにそれ！　なんのお肉？」
line = "「なにそれ！　なんのお肉？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そんなことより！　あなたたちにご褒美を持ってきたのよ！」
line = "「そんなことより！　あなたたちにご褒美を持ってきたのよ！」"

[[dialogue]]
speaker = "アナ"
# 「……ご褒美、ですか？」
line = "「……ご褒美、ですか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「じゃーーーーんっ！」
line = "「じゃーーーーんっ！」"

[[dialogue]]
speaker = "unk"
# これは……モナカ？
line = "これは……モナカ？"

[[dialogue]]
speaker = "ヴィーナス"
# 「そう、モナカよ。私の親戚の人がよく持ってきてくれるの。私も甘いものは好きだけど、１人じゃ食べきれないからみんなに配ってるわけ」
line = "「そう、モナカよ。私の親戚の人がよく持ってきてくれるの。私も甘いものは好きだけど、１人じゃ食べきれないからみんなに配ってるわけ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「特にアナはこういう和菓子が大好きだから、たまにおすそわけしてるのよ」
line = "「特にアナはこういう和菓子が大好きだから、たまにおすそわけしてるのよ」"

[[dialogue]]
speaker = "アナ"
# 「じゅるり……」
line = "「じゅるり……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「好きなだけ持ってっていいわよ。お屋敷にも山のようにあるから、どんどん食べてちょうだい！」
line = "「好きなだけ持ってっていいわよ。お屋敷にも山のようにあるから、どんどん食べてちょうだい！」"

[[dialogue]]
speaker = "アナ"
# 「前会長は神、後光が差してる、まぶしい」
line = "「前会長は神、後光が差してる、まぶしい」"

[[dialogue]]
speaker = "アナ"
# 「このモナカは餡子？　栗？　……それとも、少し邪道だけど、カスタード？」
line = "「このモナカは餡子？　栗？　……それとも、少し邪道だけど、カスタード？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「餡子じゃないかしら？　いつも餡子だし」
line = "「餡子じゃないかしら？　いつも餡子だし」"

[[dialogue]]
speaker = "アナ"
# 「つぶあん？　こしあん？　まさか、抹茶餡？」
line = "「つぶあん？　こしあん？　まさか、抹茶餡？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「さ、さすがにそこまでわからないけど……。あの人が自分で作ってるものだから市販のものじゃないし……食べてみたらわかるんじゃないの？」
line = "「さ、さすがにそこまでわからないけど……。あの人が自分で作ってるものだから市販のものじゃないし……食べてみたらわかるんじゃないの？」"

[[dialogue]]
speaker = "アナ"
# 「モナカの中身によって、用意する飲み物が変わる。この選択を間違えると、せっかくのモナカが台無しになります。事前の準備が重要」
line = "「モナカの中身によって、用意する飲み物が変わる。この選択を間違えると、せっかくのモナカが台無しになります。事前の準備が重要」"

[[dialogue]]
speaker = "ヴィーナス"
# 「アナの言う通り、お菓子に合わせる飲み物は重要ね！　今からでも中身を聞いてこようかしら？」
line = "「アナの言う通り、お菓子に合わせる飲み物は重要ね！　今からでも中身を聞いてこようかしら？」"

[[dialogue]]
speaker = "アナ"
# 「……現会長。みんなのお茶は私が用意するので、１つ食べて中身を確かめて貰えませんか？」
line = "「……現会長。みんなのお茶は私が用意するので、１つ食べて中身を確かめて貰えませんか？」"

[[dialogue]]
speaker = "アナ"
# 「ちなみに、前会長は和菓子の神ですが、こしあんとつぶあんの違いがわかりません」
line = "「ちなみに、前会長は和菓子の神ですが、こしあんとつぶあんの違いがわかりません」"

[[dialogue]]
speaker = "ヴィーナス"
# 「美味しければどちらでもよくない？」
line = "「美味しければどちらでもよくない？」"

[[dialogue]]
speaker = "アナ"
# 「よくありません。由々しき問題です。会長、お願いします」
line = "「よくありません。由々しき問題です。会長、お願いします」"

[[dialogue]]
speaker = "unk"
# （モナカを取って食べてみる）
line = "（モナカを取って食べてみる）"

[[dialogue]]
speaker = "アナ"
# 「──なるほど。それはこしあんの顔ですね」
line = "「──なるほど。それはこしあんの顔ですね」"

[[dialogue]]
speaker = "unk"
# どんな顔！？　というか合ってる……だと！？
line = "どんな顔！？　というか合ってる……だと！？"

[[dialogue]]
speaker = "アナ"
# 「玄米茶を用意します。少しお待ちください」
line = "「玄米茶を用意します。少しお待ちください」"

[[dialogue]]
speaker = "アナ"
# 「お待たせしました、会長。前会長もどうぞ」
line = "「お待たせしました、会長。前会長もどうぞ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ありがとう！　和菓子にはアナが用意したお茶が１番合うのよね～」
line = "「ありがとう！　和菓子にはアナが用意したお茶が１番合うのよね～」"

[[dialogue]]
speaker = "アナ"
# 「ではいざ尋常に」
line = "「ではいざ尋常に」"

[[dialogue]]
speaker = "アナ"
# 「はむっ……もぐもぐ……」
line = "「はむっ……もぐもぐ……」"

[[dialogue]]
speaker = "アナ"
# 「────────♥♥♥」
line = "「────────♥♥♥」"

[[dialogue]]
speaker = "ヴィーナス"
# 「アナがバグった！？　お、落ち着いて！」
line = "「アナがバグった！？　お、落ち着いて！」"

[[dialogue]]
speaker = "アナ"
# 「すん」
line = "「すん」"

[[dialogue]]
speaker = "unk"
# うわぁ！？　急に落ち着くな！
line = "うわぁ！？　急に落ち着くな！"

[[dialogue]]
speaker = "アナ"
# 「……余りの美味しさに、感動でうち震えてしまった。これはモナカの革命。生地のほうにほのかな甘みを感じる反面、餡子には少しだけ塩味が足されて絶妙な味わいになってる」
line = "「……余りの美味しさに、感動でうち震えてしまった。これはモナカの革命。生地のほうにほのかな甘みを感じる反面、餡子には少しだけ塩味が足されて絶妙な味わいになってる」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そ、そう。そこまで喜んでくれたなら、あの人も嬉しいと思うわ……」
line = "「そ、そう。そこまで喜んでくれたなら、あの人も嬉しいと思うわ……」"

[[dialogue]]
speaker = "アナ"
# 「こんな美味しいものをこの世に生み出してくださった、女神テルル様に感謝。アーメン……」
line = "「こんな美味しいものをこの世に生み出してくださった、女神テルル様に感謝。アーメン……」"

[[dialogue]]
speaker = "unk"
# 幸せそうな顔で、ハムスターのようにモナカを頬張るアナなのだった。
line = "幸せそうな顔で、ハムスターのようにモナカを頬張るアナなのだった。"
