[[dialogue]]
speaker = "unk"
# 第１話,お主の欲しいもの,P
line = "第１話,お主の欲しいもの,P"

[[dialogue]]
speaker = "クラウディア"
# 「──どうだ、魔王よ！」
line = "「──どうだ、魔王よ！」"

[[dialogue]]
speaker = "unk"
# ぴったりだ
line = "ぴったりだ"

[[dialogue]]
speaker = "unk"
# 似合ってる
line = "似合ってる"

[[dialogue]]
speaker = "クラウディア"
# 「あっはっは、そうであろうそうであろう！　ただでさえぷりちーな余が、さらに可愛く大変身というわけだ」
line = "「あっはっは、そうであろうそうであろう！　ただでさえぷりちーな余が、さらに可愛く大変身というわけだ」"

[[dialogue]]
speaker = "クラウディア"
# 「うむ。実はちぇちゅーりえが、余のためにと開発してくれたらしくてな。余の専用フォームなのだ！」
line = "「うむ。実はちぇちゅーりえが、余のためにと開発してくれたらしくてな。余の専用フォームなのだ！」"

[[dialogue]]
speaker = "クラウディア"
# 「ふふふ。なにせ１２月２５日は余の誕生日だからな。特別な品こそふさわしいというものよ」
line = "「ふふふ。なにせ１２月２５日は余の誕生日だからな。特別な品こそふさわしいというものよ」"

[[dialogue]]
speaker = "クラウディア"
# 「このロッドか？　そうだ、実はここにも仕掛けが施されていてな」
line = "「このロッドか？　そうだ、実はここにも仕掛けが施されていてな」"

[[dialogue]]
speaker = "クラウディア"
# 「こうやって杖を振ると──えいっ！　どうだ、雪がもりもり降ってくるのだ」
line = "「こうやって杖を振ると──えいっ！　どうだ、雪がもりもり降ってくるのだ」"

[[dialogue]]
speaker = "unk"
# 何の意味が？
line = "何の意味が？"

[[dialogue]]
speaker = "unk"
# すごい
line = "すごい"

[[dialogue]]
speaker = "クラウディア"
# 「綺麗であろう！　意味などそれで十分！」
line = "「綺麗であろう！　意味などそれで十分！」"

[[dialogue]]
speaker = "クラウディア"
# 「他にもまだまだあるぞ。ジングルベルが鳴ったり、ツリー用の飾りが出てきたりだな……」
line = "「他にもまだまだあるぞ。ジングルベルが鳴ったり、ツリー用の飾りが出てきたりだな……」"

[[dialogue]]
speaker = "クラウディア"
# 「そして極めつけはプレゼント機能だ。このホーリー・ベルは、相手の望んだものを出すことが可能なのだ！」
line = "「そして極めつけはプレゼント機能だ。このホーリー・ベルは、相手の望んだものを出すことが可能なのだ！」"

[[dialogue]]
speaker = "unk"
# さすがクラウディア
line = "さすがクラウディア"

[[dialogue]]
speaker = "unk"
# そっちは本当にすごい
line = "そっちは本当にすごい"

[[dialogue]]
speaker = "クラウディア"
# 「あっはっは、恐れ入ったか！」
line = "「あっはっは、恐れ入ったか！」"

[[dialogue]]
speaker = "クラウディア"
# 「どれ。試しに魔王にもプレゼントをしてみせようではないか」
line = "「どれ。試しに魔王にもプレゼントをしてみせようではないか」"

[[dialogue]]
speaker = "クラウディア"
# 「ふっふっふっ……みなまで言うでない。余に伝えずとも、ホーリー・ベルはお主の希望を汲み取ってくれるであろう」
line = "「ふっふっふっ……みなまで言うでない。余に伝えずとも、ホーリー・ベルはお主の希望を汲み取ってくれるであろう」"

[[dialogue]]
speaker = "クラウディア"
# 「そ～れ……メリークラウディアバースデ～！」
line = "「そ～れ……メリークラウディアバースデ～！」"

[[dialogue]]
speaker = "unk"
# 人形だ
line = "人形だ"

[[dialogue]]
speaker = "unk"
# これは……
line = "これは……"

[[dialogue]]
speaker = "クラウディア"
# 「む？　これは小さいお人形──って……よく見れば、これは余そっくりではないか」
line = "「む？　これは小さいお人形──って……よく見れば、これは余そっくりではないか」"

[[dialogue]]
speaker = "クラウディア"
# 「お主はこんなものが欲しかったのか？　──いや待てよ。この機能は残念ながら、希望の品をそのまま出してくれるわけではないのだ」
line = "「お主はこんなものが欲しかったのか？　──いや待てよ。この機能は残念ながら、希望の品をそのまま出してくれるわけではないのだ」"

[[dialogue]]
speaker = "クラウディア"
# 「実際に出てくるプレゼントは、希望よりいくつかグレードの下がったアイテムになってしまう」
line = "「実際に出てくるプレゼントは、希望よりいくつかグレードの下がったアイテムになってしまう」"

[[dialogue]]
speaker = "クラウディア"
# 「それで小さいクラウディア人形が出てくるということは、お主が本当に欲しかったのは、余そのものということになるわけで……」
line = "「それで小さいクラウディア人形が出てくるということは、お主が本当に欲しかったのは、余そのものということになるわけで……」"

[[dialogue]]
speaker = "クラウディア"
# 「はあ……お主、そんなに余が好きなのか」
line = "「はあ……お主、そんなに余が好きなのか」"

[[dialogue]]
speaker = "unk"
# クラウディアが欲しい
line = "クラウディアが欲しい"

[[dialogue]]
speaker = "unk"
# 実はそう
line = "実はそう"

[[dialogue]]
speaker = "クラウディア"
# 「まったく……しようのないやつだ！　こっちへ来い」
line = "「まったく……しようのないやつだ！　こっちへ来い」"

[[dialogue]]
speaker = "クラウディア"
# 「すりすり～……ふふ、どうだ？　欲しがりな魔王のために、余がひたすら引っついてやるのだ」
line = "「すりすり～……ふふ、どうだ？　欲しがりな魔王のために、余がひたすら引っついてやるのだ」"

[[dialogue]]
speaker = "クラウディア"
# 「ふふっ、満足か？　余も気分がよい」
line = "「ふふっ、満足か？　余も気分がよい」"

[[dialogue]]
speaker = "クラウディア"
# 「そうだ。このままデートといきたいな……今日は外出の許可こそ降りておらぬが……」
line = "「そうだ。このままデートといきたいな……今日は外出の許可こそ降りておらぬが……」"

[[dialogue]]
speaker = "クラウディア"
# 「魔王がいれば大丈夫だ。というわけで──セドナの目を盗んでさっさとここから抜け出そうぞ。ふふ、お主も共犯というやつだ♪」
line = "「魔王がいれば大丈夫だ。というわけで──セドナの目を盗んでさっさとここから抜け出そうぞ。ふふ、お主も共犯というやつだ♪」"

[[dialogue]]
speaker = "unk"
# そうしてその日は、クラウディアと共にお忍びデートへ出かけるのだった……。
line = "そうしてその日は、クラウディアと共にお忍びデートへ出かけるのだった……。"
