[[dialogue]]
speaker = "unk"
# 第４話,王女に戻れる未来へ,P
line = "第４話,王女に戻れる未来へ,P"

[[dialogue]]
speaker = "ユーリス"
# 「会長。このお皿はここに片付けておけばいいかな？」
line = "「会長。このお皿はここに片付けておけばいいかな？」"

[[dialogue]]
speaker = "ユーリス"
# 「よし。これで晩ご飯のお片付けも終わり、と。会長は座ってて。今お茶でも淹れるから」
line = "「よし。これで晩ご飯のお片付けも終わり、と。会長は座ってて。今お茶でも淹れるから」"

[[dialogue]]
speaker = "ユーリス"
# 「ふふ、気にしないでいいよ。これは私の我が儘だから。少しでも会長とのデートを長引かせたくて、あれやこれやと理由を探しているだけさ」
line = "「ふふ、気にしないでいいよ。これは私の我が儘だから。少しでも会長とのデートを長引かせたくて、あれやこれやと理由を探しているだけさ」"

[[dialogue]]
speaker = "ユーリス"
# 「それよりどうだったかな……？　今日の晩ご飯。いつもより、その。美味しくなかったとか……」
line = "「それよりどうだったかな……？　今日の晩ご飯。いつもより、その。美味しくなかったとか……」"

[[dialogue]]
speaker = "unk"
# むしろいつもより美味しかったよ
line = "むしろいつもより美味しかったよ"

[[dialogue]]
speaker = "ユーリス"
# 「っっ。そ、そっか。なら良かったよ。実はちょっぴり不安だったんだ」
line = "「っっ。そ、そっか。なら良かったよ。実はちょっぴり不安だったんだ」"

[[dialogue]]
speaker = "ユーリス"
# 「今夜は勇者スキルを使わずに料理したから。それなりに練習はしたつもりだけど、先達のスキルにはまだまだ敵わないからね」
line = "「今夜は勇者スキルを使わずに料理したから。それなりに練習はしたつもりだけど、先達のスキルにはまだまだ敵わないからね」"

[[dialogue]]
speaker = "ユーリス"
# 「でも喜んでもらえたなら本当に良かった。君にはどうしても、その。自分の実力だけで作った料理を食べてもらいたくて」
line = "「でも喜んでもらえたなら本当に良かった。君にはどうしても、その。自分の実力だけで作った料理を食べてもらいたくて」"

[[dialogue]]
speaker = "ユーリス"
# 「聖剣のおかげで大概のことはできるけど……なんて言えばいいのかな。君のために何かする時は、勇者スキルを使いたくないんだ」
line = "「聖剣のおかげで大概のことはできるけど……なんて言えばいいのかな。君のために何かする時は、勇者スキルを使いたくないんだ」"

[[dialogue]]
speaker = "ユーリス"
# 「っと、そうだ。お茶を淹れてる途中だったんだ。すぐに持ってくるね」
line = "「っと、そうだ。お茶を淹れてる途中だったんだ。すぐに持ってくるね」"

[[dialogue]]
speaker = "ユーリス"
# 「こっちはどう？　……う、ちょっと渋い？　紅茶の入れ方はもう少し鍛錬が必要みたいだね。蜂蜜でも入れてみよっか」
line = "「こっちはどう？　……う、ちょっと渋い？　紅茶の入れ方はもう少し鍛錬が必要みたいだね。蜂蜜でも入れてみよっか」"

[[dialogue]]
speaker = "ユーリス"
# 「うん……甘い。私はこのくらい甘い方が好みかも。男の振りをしていると、あまり甘い物が好きだって言いづらいんだけどね」
line = "「うん……甘い。私はこのくらい甘い方が好みかも。男の振りをしていると、あまり甘い物が好きだって言いづらいんだけどね」"

[[dialogue]]
speaker = "ユーリス"
# 「ところで……その。もう少しだけ、くっついてもいいかな？」
line = "「ところで……その。もう少しだけ、くっついてもいいかな？」"

[[dialogue]]
speaker = "ユーリス"
# 「えへへ、ありがとう。それじゃあ……ん」
line = "「えへへ、ありがとう。それじゃあ……ん」"

[[dialogue]]
speaker = "ユーリス"
# 「温かい……落ち着く……。ふふ、もちろん紅茶の話じゃないよ？　この幸せな時間のことさ」
line = "「温かい……落ち着く……。ふふ、もちろん紅茶の話じゃないよ？　この幸せな時間のことさ」"

[[dialogue]]
speaker = "ユーリス"
# 「……不思議だよね。さっき２人で朝日が昇るところを見たと思っていたら、今は月が昇っていく姿を眺めている」
line = "「……不思議だよね。さっき２人で朝日が昇るところを見たと思っていたら、今は月が昇っていく姿を眺めている」"

[[dialogue]]
speaker = "ユーリス"
# 「楽しい時間は本当にあっという間だよ。別に何をしていたわけでもないのにね？　君と一緒にいるだけで……瞬く間に時間が過ぎていっちゃう」
line = "「楽しい時間は本当にあっという間だよ。別に何をしていたわけでもないのにね？　君と一緒にいるだけで……瞬く間に時間が過ぎていっちゃう」"

[[dialogue]]
speaker = "ユーリス"
# 「ん……ちゅっ。ん……」
line = "「ん……ちゅっ。ん……」"

[[dialogue]]
speaker = "ユーリス"
# 「ふぁ……またキスしちゃった。ダメだね、そろそろユーリスに戻らなくちゃいけないのに……」
line = "「ふぁ……またキスしちゃった。ダメだね、そろそろユーリスに戻らなくちゃいけないのに……」"

[[dialogue]]
speaker = "unk"
# ２人きりの時はずっとユリアーナで構わないよ
line = "２人きりの時はずっとユリアーナで構わないよ"

[[dialogue]]
speaker = "ユーリス"
# 「会長……。ちゅ……んっ……んふ……」
line = "「会長……。ちゅ……んっ……んふ……」"

[[dialogue]]
speaker = "ユーリス"
# 「えへへ……明日が怖いね。唇がものすごく荒れていそうだ。朝から数え切れないほどキスしちゃってる気がする……」
line = "「えへへ……明日が怖いね。唇がものすごく荒れていそうだ。朝から数え切れないほどキスしちゃってる気がする……」"

[[dialogue]]
speaker = "ユーリス"
# 「だけど……んっ、ちゅっ。全然足りない……はむぅん、んちゅ……。まだまだし足りないよ……」
line = "「だけど……んっ、ちゅっ。全然足りない……はむぅん、んちゅ……。まだまだし足りないよ……」"

[[dialogue]]
speaker = "ユーリス"
# 「甘えんぼの彼女でごめんね……？　２人きりだと思うと、どうしてもイチャイチャしたくなっちゃって……」
line = "「甘えんぼの彼女でごめんね……？　２人きりだと思うと、どうしてもイチャイチャしたくなっちゃって……」"

[[dialogue]]
speaker = "ユーリス"
# 「会長の恋人にしてもらってからというもの、つくづく自分の見立てが甘かったことを思い知らされるよ」
line = "「会長の恋人にしてもらってからというもの、つくづく自分の見立てが甘かったことを思い知らされるよ」"

[[dialogue]]
speaker = "ユーリス"
# 「こんなにも自分が女の子だなんて思ってなかった。聖剣に選ばれた時に、女の自分なんて捨て去ったつもりだったのに」
line = "「こんなにも自分が女の子だなんて思ってなかった。聖剣に選ばれた時に、女の自分なんて捨て去ったつもりだったのに」"

[[dialogue]]
speaker = "ユーリス"
# 「私は本当にダメなヤツだね。聖剣の勇者失格だ。この時間がいつまでも続けばいいと思ってしまってる」
line = "「私は本当にダメなヤツだね。聖剣の勇者失格だ。この時間がいつまでも続けばいいと思ってしまってる」"

[[dialogue]]
speaker = "ユーリス"
# 「このまま時間よ止まれと願ってしまっているんだ。ユーリスではなくユリアーナとしてずっと君の隣にいたいと望んでしまっている」
line = "「このまま時間よ止まれと願ってしまっているんだ。ユーリスではなくユリアーナとしてずっと君の隣にいたいと望んでしまっている」"

[[dialogue]]
speaker = "unk"
# 時間は止められないよ
line = "時間は止められないよ"

[[dialogue]]
speaker = "ユーリス"
# 「そう……だよね。わかってる。自分でもわかってるんだ。でも本当にユリアーナとして君と過ごす時間は心地よくて」
line = "「そう……だよね。わかってる。自分でもわかってるんだ。でも本当にユリアーナとして君と過ごす時間は心地よくて」"

[[dialogue]]
speaker = "ユーリス"
# 「常にユリアーナでいられないことが口惜しいんだ。ユーリスとして君と接する度に胸がズキズキしてしまう」
line = "「常にユリアーナでいられないことが口惜しいんだ。ユーリスとして君と接する度に胸がズキズキしてしまう」"

[[dialogue]]
speaker = "ユーリス"
# 「ごめん。困らせるようなことを言っちゃったね。今この瞬間、ユリアーナに戻っていられるだけでも贅沢な話なのに」
line = "「ごめん。困らせるようなことを言っちゃったね。今この瞬間、ユリアーナに戻っていられるだけでも贅沢な話なのに」"

[[dialogue]]
speaker = "ユーリス"
# 「今の話は忘れて？　そろそろ会長のお母様も帰ってくる頃だろうし、私も自分の部屋に──」
line = "「今の話は忘れて？　そろそろ会長のお母様も帰ってくる頃だろうし、私も自分の部屋に──」"

[[dialogue]]
speaker = "unk"
# だけど未来に進むことはできるよ
line = "だけど未来に進むことはできるよ"

[[dialogue]]
speaker = "ユーリス"
# 「え……？　未来に……？」
line = "「え……？　未来に……？」"

[[dialogue]]
speaker = "unk"
# リクリエを退けてユリアーナに戻れる未来にさ
line = "リクリエを退けてユリアーナに戻れる未来にさ"

[[dialogue]]
speaker = "ユーリス"
# 「ぷふっ、あははっ、ふふふっ。会長はたまに私なんかよりもよっぽど王子様らしいセリフを吐くよね？」
line = "「ぷふっ、あははっ、ふふふっ。会長はたまに私なんかよりもよっぽど王子様らしいセリフを吐くよね？」"

[[dialogue]]
speaker = "ユーリス"
# 「でも、うん。会長の言うとおりだ。現状維持を是とするなんてどうかしていたよ」
line = "「でも、うん。会長の言うとおりだ。現状維持を是とするなんてどうかしていたよ」"

[[dialogue]]
speaker = "ユーリス"
# 「リクリエさえ退ければ、ジルラント王国のみんなの不安も解消される。私が性別を偽る理由もなくなる」
line = "「リクリエさえ退ければ、ジルラント王国のみんなの不安も解消される。私が性別を偽る理由もなくなる」"

[[dialogue]]
speaker = "ユーリス"
# 「会長とならそんな未来、簡単に切り拓けるはずなのに。私は何を立ち止まろうとしていたんだろう」
line = "「会長とならそんな未来、簡単に切り拓けるはずなのに。私は何を立ち止まろうとしていたんだろう」"

[[dialogue]]
speaker = "ユーリス"
# 「おかげで目が覚めたよ。俄然やる気も出てきた」
line = "「おかげで目が覚めたよ。俄然やる気も出てきた」"

[[dialogue]]
speaker = "ユーリス"
# 「改めて、会長に、我が聖剣に誓うよ。必ずリクリエを打倒してみせるって」
line = "「改めて、会長に、我が聖剣に誓うよ。必ずリクリエを打倒してみせるって」"

[[dialogue]]
speaker = "ユーリス"
# 「そして、ふふ。私のフィアンセとして会長をジルラント王国に連れて帰るんだ。国を挙げて結婚式を開いて、祖国のみんなに祝ってもらっちゃおう」
line = "「そして、ふふ。私のフィアンセとして会長をジルラント王国に連れて帰るんだ。国を挙げて結婚式を開いて、祖国のみんなに祝ってもらっちゃおう」"

[[dialogue]]
speaker = "ユーリス"
# 「ああ……力が湧いてくる。会長との幸せな未来を思い描くだけで、こんなにも私は強くなれるんだ」
line = "「ああ……力が湧いてくる。会長との幸せな未来を思い描くだけで、こんなにも私は強くなれるんだ」"

[[dialogue]]
speaker = "ユーリス"
# 「大好きだよ、会長。心の底から愛してる」
line = "「大好きだよ、会長。心の底から愛してる」"

[[dialogue]]
speaker = "ユーリス"
# 「私は、絶対に君との幸せな未来を勝ち取ってみせるよ……！」
line = "「私は、絶対に君との幸せな未来を勝ち取ってみせるよ……！」"

[[dialogue]]
speaker = "ユーリス"
# 「わわっ、会長のＤＩＳＣが……！　こ、こんな時に誰からの連絡だい？　え、お母様？」
line = "「わわっ、会長のＤＩＳＣが……！　こ、こんな時に誰からの連絡だい？　え、お母様？」"

[[dialogue]]
speaker = "ユーリス"
# 「そ、そっか。今日は帰らないことになったんだね？　まあ夜も遅いもんね……？」
line = "「そ、そっか。今日は帰らないことになったんだね？　まあ夜も遅いもんね……？」"

[[dialogue]]
speaker = "ユーリス"
# 「それなら、えと……。物は相談なんだけど……」
line = "「それなら、えと……。物は相談なんだけど……」"

[[dialogue]]
speaker = "ユーリス"
# 「今日はこのまま……泊まっていってもいい、かな？」
line = "「今日はこのまま……泊まっていってもいい、かな？」"
