[[dialogue]]
speaker = "unk"
# 第１話,ノリノリな２人,P
line = "第１話,ノリノリな２人,P"

[[dialogue]]
speaker = "unk"
# 夏が終わり、新学期初日。俺は学園に転入したリップルの様子を見に向かったのだが――
line = "夏が終わり、新学期初日。俺は学園に転入したリップルの様子を見に向かったのだが――"

[[dialogue]]
speaker = "紅明"
# 「それじゃ撮るよ～。アタシの近くにもっと寄って寄って～♪　一緒にハイッ、チーズ☆」
line = "「それじゃ撮るよ～。アタシの近くにもっと寄って寄って～♪　一緒にハイッ、チーズ☆」"

[[dialogue]]
speaker = "リップル"
# 「イェ～イ♪　シリ合った記念の、ツーショットで～す！」
line = "「イェ～イ♪　シリ合った記念の、ツーショットで～す！」"

[[dialogue]]
speaker = "紅明"
# 「うん、可愛く撮れた♪　ほら、ＤＩＳＣの画面、見てみ？　良い感じっしょ～☆」
line = "「うん、可愛く撮れた♪　ほら、ＤＩＳＣの画面、見てみ？　良い感じっしょ～☆」"

[[dialogue]]
speaker = "リップル"
# 「ワオ♪　素敵な自撮り写真デスね～！　後でワタシのＤＩＳＣにも送ってホシイで～す♪」
line = "「ワオ♪　素敵な自撮り写真デスね～！　後でワタシのＤＩＳＣにも送ってホシイで～す♪」"

[[dialogue]]
speaker = "紅明"
# 「おっけー♪　すぐ送るね～……って、おっ？　ダーリンじゃ～ん！　今日も元気してる～？」
line = "「おっけー♪　すぐ送るね～……って、おっ？　ダーリンじゃ～ん！　今日も元気してる～？」"

[[dialogue]]
speaker = "リップル"
# 「あっ、カイチョー！　コンニチハで～す♪」
line = "「あっ、カイチョー！　コンニチハで～す♪」"

[[dialogue]]
speaker = "リップル"
# 「――ワタシの様子を見に来てくれたんデスか？　アリガトございます♪　学園の初授業、楽しかったデスよ！」
line = "「――ワタシの様子を見に来てくれたんデスか？　アリガトございます♪　学園の初授業、楽しかったデスよ！」"

[[dialogue]]
speaker = "unk"
# ２人はもしかして同じクラス？
line = "２人はもしかして同じクラス？"

[[dialogue]]
speaker = "リップル"
# 「いえ、別のクラスで～す！　今さっき、ここで出会って仲良くナリました♪」
line = "「いえ、別のクラスで～す！　今さっき、ここで出会って仲良くナリました♪」"

[[dialogue]]
speaker = "紅明"
# 「転入生が来るって聞いたから、友達になろうと思ってさ☆　で、会ってすぐにビビっと来ちゃったワケよ！　お互いノリノリな感じが合うっていうか！」
line = "「転入生が来るって聞いたから、友達になろうと思ってさ☆　で、会ってすぐにビビっと来ちゃったワケよ！　お互いノリノリな感じが合うっていうか！」"

[[dialogue]]
speaker = "リップル"
# 「また１人、気の合う友達がデキて、嬉しいで～す♪　……あ！　それで、今思い出したんデスが――」
line = "「また１人、気の合う友達がデキて、嬉しいで～す♪　……あ！　それで、今思い出したんデスが――」"

[[dialogue]]
speaker = "リップル"
# 「アナタのお名前、まだ聞いてマセンでした！」
line = "「アナタのお名前、まだ聞いてマセンでした！」"

[[dialogue]]
speaker = "紅明"
# 「おっ、確かに！　アタシも聞いてなかったわ！」
line = "「おっ、確かに！　アタシも聞いてなかったわ！」"

[[dialogue]]
speaker = "unk"
# 名前も知らずに、あんなに仲良くしてたの！？
line = "名前も知らずに、あんなに仲良くしてたの！？"

[[dialogue]]
speaker = "紅明"
# 「うししし♪　ノリが合い過ぎて、聞くのすっかり忘れてたわ！　ウケる～☆」
line = "「うししし♪　ノリが合い過ぎて、聞くのすっかり忘れてたわ！　ウケる～☆」"

[[dialogue]]
speaker = "リップル"
# 「ノリが良ければナントカなる。サーフィンと一緒デスね～♪」
line = "「ノリが良ければナントカなる。サーフィンと一緒デスね～♪」"

[[dialogue]]
speaker = "紅明"
# 「それじゃあ改めて名乗らないとだね。アタシは牛紅明！　元気が取り柄の２年生さ！　こう見えて、テレビタレントをやってるんだぜ♪　ヨロシクな☆」
line = "「それじゃあ改めて名乗らないとだね。アタシは牛紅明！　元気が取り柄の２年生さ！　こう見えて、テレビタレントをやってるんだぜ♪　ヨロシクな☆」"

[[dialogue]]
speaker = "リップル"
# 「ワタシはリップルとイイま～す！　夏にカイチョーと出会って、新星学園にやってキマした！　コウメイ、こちらこそヨロシクお願いしま～す♪」
line = "「ワタシはリップルとイイま～す！　夏にカイチョーと出会って、新星学園にやってキマした！　コウメイ、こちらこそヨロシクお願いしま～す♪」"

[[dialogue]]
speaker = "紅明"
# 「ほうほう……それじゃあ、あだ名はズバリ『リプるん』だね☆」
line = "「ほうほう……それじゃあ、あだ名はズバリ『リプるん』だね☆」"

[[dialogue]]
speaker = "リップル"
# 「オウ♪　リプるん……ＢＩＧ素敵な呼び方です！　ワタシ、あだ名付けて貰ったのハジメテなので、嬉しいで～す♪」
line = "「オウ♪　リプるん……ＢＩＧ素敵な呼び方です！　ワタシ、あだ名付けて貰ったのハジメテなので、嬉しいで～す♪」"

[[dialogue]]
speaker = "紅明"
# 「それで、アタシとしては、ダーリンとリプるんが既に親しい感じなのが気になるけど、夏に何があったんだい？」
line = "「それで、アタシとしては、ダーリンとリプるんが既に親しい感じなのが気になるけど、夏に何があったんだい？」"

[[dialogue]]
speaker = "unk"
# 星徒会の夏合宿で出会ったんだ
line = "星徒会の夏合宿で出会ったんだ"

[[dialogue]]
speaker = "リップル"
# 「ワタシは星術で結界を作ることが出来るのデスが、トラブルで自分の結界から脱出できなくナッテしまって……」
line = "「ワタシは星術で結界を作ることが出来るのデスが、トラブルで自分の結界から脱出できなくナッテしまって……」"

[[dialogue]]
speaker = "リップル"
# 「その結界がある無人島に、星徒会の皆が合宿でやってキタので～す！」
line = "「その結界がある無人島に、星徒会の皆が合宿でやってキタので～す！」"

[[dialogue]]
speaker = "リップル"
# 「カイチョー達は空間の歪みから、結界内に迷い込んでしまって……そこでワタシと出会ったんです！」
line = "「カイチョー達は空間の歪みから、結界内に迷い込んでしまって……そこでワタシと出会ったんです！」"

[[dialogue]]
speaker = "リップル"
# 「そうして一緒にトラブルを解決する中で、カイチョーから学園へ誘って貰ったというワケで～す♪」
line = "「そうして一緒にトラブルを解決する中で、カイチョーから学園へ誘って貰ったというワケで～す♪」"

[[dialogue]]
speaker = "紅明"
# 「なるほどね～、結界……あっ！　もしかして、いま噂の『リゾート結界』ってリプるんが作ったものだったりする？」
line = "「なるほどね～、結界……あっ！　もしかして、いま噂の『リゾート結界』ってリプるんが作ったものだったりする？」"

[[dialogue]]
speaker = "リップル"
# 「ハイ！　その通りです♪　常夏の海がいつでも楽しめる、カイチョー達と出会った無人島をベースにツクった空間で～す！」
line = "「ハイ！　その通りです♪　常夏の海がいつでも楽しめる、カイチョー達と出会った無人島をベースにツクった空間で～す！」"

[[dialogue]]
speaker = "紅明"
# 「マジか～！　１年中、近場で夏の海を楽しめるってことっしょ？　めっちゃいいじゃん！」
line = "「マジか～！　１年中、近場で夏の海を楽しめるってことっしょ？　めっちゃいいじゃん！」"

[[dialogue]]
speaker = "紅明"
# 「実はアタシ、この夏はタレント活動が忙しかったからさ。リプるんのリゾート結界には、まだ行ったことがないんだよね～」
line = "「実はアタシ、この夏はタレント活動が忙しかったからさ。リプるんのリゾート結界には、まだ行ったことがないんだよね～」"

[[dialogue]]
speaker = "リップル"
# 「だったら、今すぐ案内しマスよ～♪　ワタシ、結界を召喚することがデキますので！」
line = "「だったら、今すぐ案内しマスよ～♪　ワタシ、結界を召喚することがデキますので！」"

[[dialogue]]
speaker = "リップル"
# 「オイデマセ、夏の海～♪　ソォイッ！」
line = "「オイデマセ、夏の海～♪　ソォイッ！」"

[[dialogue]]
speaker = "紅明"
# 「うおっ！？　眩しっ……！」
line = "「うおっ！？　眩しっ……！」"

[[dialogue]]
speaker = "リップル"
# 「コウメイ、ラッシャーセー♪　ここがワタシのリゾート結界……名付けて『エンドレスサマー』で～す！」
line = "「コウメイ、ラッシャーセー♪　ここがワタシのリゾート結界……名付けて『エンドレスサマー』で～す！」"

[[dialogue]]
speaker = "紅明"
# 「うおぉぉぉっ、マジで日差しが夏！　そして海の匂い！　完全にモノホンじゃん！　これマジでリプるんが作ったの！？　パないんですけど！」
line = "「うおぉぉぉっ、マジで日差しが夏！　そして海の匂い！　完全にモノホンじゃん！　これマジでリプるんが作ったの！？　パないんですけど！」"

[[dialogue]]
speaker = "リップル"
# 「エヘヘ♪　ワタシの星術は、結界内に自分のイメージする空間を作り上げることがデキるんです！」
line = "「エヘヘ♪　ワタシの星術は、結界内に自分のイメージする空間を作り上げることがデキるんです！」"

[[dialogue]]
speaker = "リップル"
# 「ワタシは夏の海が大好きなんデスが、この国には季節がアリますから、夏が終わってしまうのをザンネンに思ってました……」
line = "「ワタシは夏の海が大好きなんデスが、この国には季節がアリますから、夏が終わってしまうのをザンネンに思ってました……」"

[[dialogue]]
speaker = "リップル"
# 「デスが、それなら常夏の空間を作ればいいと思って、完成したのがこのリゾート結界というワケで～す♪」
line = "「デスが、それなら常夏の空間を作ればいいと思って、完成したのがこのリゾート結界というワケで～す♪」"

[[dialogue]]
speaker = "リップル"
# 「ちなみに、今はまだ無人島を囲える範囲が限界デスが、いずれは世界全部を結界で包み込み、常夏の世界を作り上げるのが、ワタシのＢＩＧドリームです！」
line = "「ちなみに、今はまだ無人島を囲える範囲が限界デスが、いずれは世界全部を結界で包み込み、常夏の世界を作り上げるのが、ワタシのＢＩＧドリームです！」"

[[dialogue]]
speaker = "紅明"
# 「どゆこと……？」
line = "「どゆこと……？」"

[[dialogue]]
speaker = "リップル"
# 「夏の海は人のココロを解放して、ハッピーな気持ちにしま～す。デスので、世界中が常夏の空間になれば──」
line = "「夏の海は人のココロを解放して、ハッピーな気持ちにしま～す。デスので、世界中が常夏の空間になれば──」"

[[dialogue]]
speaker = "リップル"
# 「皆がいつもハッピーでいられる、理想の世界がデキあがるというワケで～す♪」
line = "「皆がいつもハッピーでいられる、理想の世界がデキあがるというワケで～す♪」"

[[dialogue]]
speaker = "unk"
# その夢については、後で要相談ね！
line = "その夢については、後で要相談ね！"

[[dialogue]]
speaker = "リップル"
# 「ハイ？　よくワカリませんが……ワカリました！」
line = "「ハイ？　よくワカリませんが……ワカリました！」"

[[dialogue]]
speaker = "紅明"
# 「うししし♪　リプるん、めっちゃ面白い子じゃん！」
line = "「うししし♪　リプるん、めっちゃ面白い子じゃん！」"

[[dialogue]]
speaker = "紅明"
# 「皆がハッピーになる常夏世界、意外とアリじゃね？」
line = "「皆がハッピーになる常夏世界、意外とアリじゃね？」"

[[dialogue]]
speaker = "unk"
# やめて！　ノリで乗っからないで！
line = "やめて！　ノリで乗っからないで！"

[[dialogue]]
speaker = "unk"
# 乗り気になる流星市国屈指のインフルエンサーを、俺は慌てて止めるのだった──
line = "乗り気になる流星市国屈指のインフルエンサーを、俺は慌てて止めるのだった──"
