[[dialogue]]
speaker = "unk"
# 第１話,幼なじみとの再会,P
line = "第１話,幼なじみとの再会,P"

[[dialogue]]
speaker = "unk"
# それはヴィーナスとの御前試合が終わった、数日後のこと──
line = "それはヴィーナスとの御前試合が終わった、数日後のこと──"

[[dialogue]]
speaker = "unk"
# はい、どうぞお入り下さい
line = "はい、どうぞお入り下さい"

[[dialogue]]
speaker = "メルエル"
# 「失礼します。……あっ、やっぱり！！　やっぱりキミだったんだぁ。久しぶりだねっ！」
line = "「失礼します。……あっ、やっぱり！！　やっぱりキミだったんだぁ。久しぶりだねっ！」"

[[dialogue]]
speaker = "メルエル"
# 「その……私のこと、覚えてないかな？　私だよ、姫咲メルエル！」
line = "「その……私のこと、覚えてないかな？　私だよ、姫咲メルエル！」"

[[dialogue]]
speaker = "unk"
# えっ！　『覚えてない』って……お、俺？
line = "えっ！　『覚えてない』って……お、俺？"

[[dialogue]]
speaker = "メルエル"
# 「うん！　私たち、１０年前くらいかな？　一緒に遊んだことがあるんだけど……」
line = "「うん！　私たち、１０年前くらいかな？　一緒に遊んだことがあるんだけど……」"

[[dialogue]]
speaker = "unk"
# えっと……ごめん、実は……
line = "えっと……ごめん、実は……"

[[dialogue]]
speaker = "メルエル"
# 「え？　幼少期の記憶があんまりない……？　そうなんだ……」
line = "「え？　幼少期の記憶があんまりない……？　そうなんだ……」"

[[dialogue]]
speaker = "メルエル"
# 「ということは……もしかしたら、私が出会ったキミは記憶を失って、目覚めた直後だったのかもしれないね」
line = "「ということは……もしかしたら、私が出会ったキミは記憶を失って、目覚めた直後だったのかもしれないね」"

[[dialogue]]
speaker = "メルエル"
# 「うん……だって１０年前のキミは、年齢のわりにはちょっとぼんやりしたところがあったから」
line = "「うん……だって１０年前のキミは、年齢のわりにはちょっとぼんやりしたところがあったから」"

[[dialogue]]
speaker = "メルエル"
# 「でもそれなら、改めて自己紹介しないとだね！」
line = "「でもそれなら、改めて自己紹介しないとだね！」"

[[dialogue]]
speaker = "メルエル"
# 「私は新星学園２年生の姫咲メルエル。生まれも育ちも天界で、<ruby=せいていえん>聖庭園</ruby>ってところ出身だよ。よろしくね♪」
line = "「私は新星学園２年生の姫咲メルエル。生まれも育ちも天界で、<ruby>聖庭園<rt>せいていえん</rt></ruby>ってところ出身だよ。よろしくね♪」"

[[dialogue]]
speaker = "メルエル"
# 「１０年くらい前、お父さんの仕事の都合で半年だけ流星市国にいたことがあって……キミとはその時に出会ったんだ」
line = "「１０年くらい前、お父さんの仕事の都合で半年だけ流星市国にいたことがあって……キミとはその時に出会ったんだ」"

[[dialogue]]
speaker = "メルエル"
# 「大聖堂の日曜ミサに参加した時に仲良くなってね？　半年間、毎週ミサの後に一緒に遊んでたんだよ！」
line = "「大聖堂の日曜ミサに参加した時に仲良くなってね？　半年間、毎週ミサの後に一緒に遊んでたんだよ！」"

[[dialogue]]
speaker = "メルエル"
# 「だから私たち、いわゆる幼なじみなの♪」
line = "「だから私たち、いわゆる幼なじみなの♪」"

[[dialogue]]
speaker = "unk"
# 大聖堂の……日曜ミサ……
line = "大聖堂の……日曜ミサ……"

[[dialogue]]
speaker = "メルエル"
# 「──こ、こんにちはっ。わたし、メルエル。キミのおなまえは？」
line = "「──こ、こんにちはっ。わたし、メルエル。キミのおなまえは？」"

[[dialogue]]
speaker = "メルエル"
# 「──もし、わたしたちがおおきくなって、それでも■■■■だったときは……」
line = "「──もし、わたしたちがおおきくなって、それでも■■■■だったときは……」"

[[dialogue]]
speaker = "メルエル"
# 「──うぅ……わたし、ぜったいにわすれないよ！　キミがわすれたとしても、わたしは……」
line = "「──うぅ……わたし、ぜったいにわすれないよ！　キミがわすれたとしても、わたしは……」"

[[dialogue]]
speaker = "unk"
# そうか……確かに、俺たち会ったことがある
line = "そうか……確かに、俺たち会ったことがある"

[[dialogue]]
speaker = "メルエル"
# 「本当！？　はっきりとじゃなくても思い出してくれて、嬉しい♪」
line = "「本当！？　はっきりとじゃなくても思い出してくれて、嬉しい♪」"

[[dialogue]]
speaker = "メルエル"
# 「ううん、そんな全然、謝らなくてもいいよ。……今こうして再会できて、私はそれだけで嬉しいから」
line = "「ううん、そんな全然、謝らなくてもいいよ。……今こうして再会できて、私はそれだけで嬉しいから」"

[[dialogue]]
speaker = "メルエル"
# 「……昔、天界へ帰る時に、星騎士になってこの学園でまた会おうって、キミと約束をしてたんだ」
line = "「……昔、天界へ帰る時に、星騎士になってこの学園でまた会おうって、キミと約束をしてたんだ」"

[[dialogue]]
speaker = "メルエル"
# 「でも、入学した時にキミを探しても見つからなくて、ちょっぴり落ち込んじゃったりすることもあったけど……」
line = "「でも、入学した時にキミを探しても見つからなくて、ちょっぴり落ち込んじゃったりすることもあったけど……」"

[[dialogue]]
speaker = "メルエル"
# 「御前試合で戦う姿を見て、間違いなくキミだって思って。私、居ても立ってもいられなくて、こうして会いに来ちゃったんだ。えへへ♪」
line = "「御前試合で戦う姿を見て、間違いなくキミだって思って。私、居ても立ってもいられなくて、こうして会いに来ちゃったんだ。えへへ♪」"

[[dialogue]]
speaker = "unk"
# もう星騎士を目指す約束してたんだな
line = "もう星騎士を目指す約束してたんだな"

[[dialogue]]
speaker = "unk"
# 俺、１０年前の時点で、
line = "俺、１０年前の時点で、"

[[dialogue]]
speaker = "メルエル"
# 「──５年前、セイファート学園長に助けられたことがきっかけで星騎士に？　そっか。だから私との約束を忘れてても、キミはこの学園にやって来たんだね」
line = "「──５年前、セイファート学園長に助けられたことがきっかけで星騎士に？　そっか。だから私との約束を忘れてても、キミはこの学園にやって来たんだね」"

[[dialogue]]
speaker = "メルエル"
# 「私はそれが凄く嬉しいな。何はともあれ──」
line = "「私はそれが凄く嬉しいな。何はともあれ──」"

[[dialogue]]
speaker = "メルエル"
# 「これからまた、幼なじみとしてよろしくね！　会長くん♪」
line = "「これからまた、幼なじみとしてよろしくね！　会長くん♪」"

[[dialogue]]
speaker = "unk"
# ああ、こちらこそよろしく、メルエル
line = "ああ、こちらこそよろしく、メルエル"

[[dialogue]]
speaker = "メルエル"
# 「うんっ！　せっかくだし、会長くんとは昔より仲良くなれたら嬉しいな～、なんて……えへへ♪」
line = "「うんっ！　せっかくだし、会長くんとは昔より仲良くなれたら嬉しいな～、なんて……えへへ♪」"

[[dialogue]]
speaker = "メルエル"
# 「……ん？　この『会長くん』って呼び方？」
line = "「……ん？　この『会長くん』って呼び方？」"

[[dialogue]]
speaker = "メルエル"
# 「ほら、キミはこれから、新星学園代表の星騎士になるわけでしょ？　だから会長くんって響き、なんだか格好よくて素敵だなぁって♪」
line = "「ほら、キミはこれから、新星学園代表の星騎士になるわけでしょ？　だから会長くんって響き、なんだか格好よくて素敵だなぁって♪」"

[[dialogue]]
speaker = "メルエル"
# 「御前試合の時も、凄く格好よかったし！　……あっ、会長くん、もしかして照れてる？」
line = "「御前試合の時も、凄く格好よかったし！　……あっ、会長くん、もしかして照れてる？」"

[[dialogue]]
speaker = "メルエル"
# 「ふふっ、その照れた顔、昔を思い出すなぁ……」
line = "「ふふっ、その照れた顔、昔を思い出すなぁ……」"

[[dialogue]]
speaker = "メルエル"
# （あの時交わした<b>もう１つの約束</b>も、いつかキミに思い出して欲しい）
line = "（あの時交わした<b>もう１つの約束</b>も、いつかキミに思い出して欲しい）"

[[dialogue]]
speaker = "メルエル"
# （だって１０年ぶりに再会して、わかっちゃったから）
line = "（だって１０年ぶりに再会して、わかっちゃったから）"

[[dialogue]]
speaker = "メルエル"
# （１０年経っても私はまだ、キミのことが『好き』なんだって）
line = "（１０年経っても私はまだ、キミのことが『好き』なんだって）"

[[dialogue]]
speaker = "メルエル"
# （私の初恋の男の子……思い出の中の淡い恋心だったかもしれない。だけど、再会した今はもう、そうじゃなくなってる）
line = "（私の初恋の男の子……思い出の中の淡い恋心だったかもしれない。だけど、再会した今はもう、そうじゃなくなってる）"

[[dialogue]]
speaker = "メルエル"
# （何気ない仕草や、言葉１つ１つに胸が高鳴っちゃうくらい、好き。……キミが好き）
line = "（何気ない仕草や、言葉１つ１つに胸が高鳴っちゃうくらい、好き。……キミが好き）"

[[dialogue]]
speaker = "メルエル"
# （だから今度こそ……一意専心、キミを振り向かせて見せるんだから！）
line = "（だから今度こそ……一意専心、キミを振り向かせて見せるんだから！）"
