[[dialogue]]
speaker = "unk"
# 第２話,恋人はサンタクロース,P
line = "第２話,恋人はサンタクロース,P"

[[dialogue]]
speaker = "unk"
# ある日の戦闘で、紅明はクリスマスフォームに変身して戦っていた。
line = "ある日の戦闘で、紅明はクリスマスフォームに変身して戦っていた。"

[[dialogue]]
speaker = "unk"
# 紅明、今だ！
line = "紅明、今だ！"

[[dialogue]]
speaker = "紅明"
# 「よっしゃ、サンタの力、見せてやるぜ！」
line = "「よっしゃ、サンタの力、見せてやるぜ！」"

[[dialogue]]
speaker = "紅明"
# 「必殺！　メリクリボンバーッ！」
line = "「必殺！　メリクリボンバーッ！」"

[[dialogue]]
speaker = "紅明"
# 「善哉善哉♪　ダーリンとのラブラブユニゾンで、今日も大勝利っしょ☆」
line = "「善哉善哉♪　ダーリンとのラブラブユニゾンで、今日も大勝利っしょ☆」"

[[dialogue]]
speaker = "unk"
# そういえば、紅明のサンタ衣装って、最初から戦闘服だったよな。気になって、いつから変身できるようになったのか、聞いてみることにした。
line = "そういえば、紅明のサンタ衣装って、最初から戦闘服だったよな。気になって、いつから変身できるようになったのか、聞いてみることにした。"

[[dialogue]]
speaker = "紅明"
# 「ん？　ああ、そこら辺詳しく話してなかったよね」
line = "「ん？　ああ、そこら辺詳しく話してなかったよね」"

[[dialogue]]
speaker = "紅明"
# 「ダーリンにはさ、前にアタシの前世について話したじゃん？」
line = "「ダーリンにはさ、前にアタシの前世について話したじゃん？」"

[[dialogue]]
speaker = "紅明"
# 「そう、アタシが西遊記で有名な牛魔王の子孫で、転生した紅孩児だって話。それを踏まえた上でになるんだけど……」
line = "「そう、アタシが西遊記で有名な牛魔王の子孫で、転生した紅孩児だって話。それを踏まえた上でになるんだけど……」"

[[dialogue]]
speaker = "紅明"
# 「アタシさ、前世でサンタクロースやってたんだよね」
line = "「アタシさ、前世でサンタクロースやってたんだよね」"

[[dialogue]]
speaker = "unk"
# は……？　どういうこと？
line = "は……？　どういうこと？"

[[dialogue]]
speaker = "紅明"
# 「アタシの通常の戦闘服って、２０００年前と同一のものなんだよね。それと同じように、このサンタ衣装も２０００年前から変身できたんだ」
line = "「アタシの通常の戦闘服って、２０００年前と同一のものなんだよね。それと同じように、このサンタ衣装も２０００年前から変身できたんだ」"

[[dialogue]]
speaker = "紅明"
# 「それはアタシが当時からサンタを知ってたからってわけじゃなくてさ。サンタって概念は、そもそもその時は存在してなかったんだ。つまり――」
line = "「それはアタシが当時からサンタを知ってたからってわけじゃなくてさ。サンタって概念は、そもそもその時は存在してなかったんだ。つまり――」"

[[dialogue]]
speaker = "紅明"
# 「多分なんだけど、アタシが<b>元祖サンタ</b>ってことなんだと思う」
line = "「多分なんだけど、アタシが<b>元祖サンタ</b>ってことなんだと思う」"

[[dialogue]]
speaker = "紅明"
# 「だから、現代のサンタコスチュームは紅色だし、アタシのこの戦闘服にそっくりなんだ」
line = "「だから、現代のサンタコスチュームは紅色だし、アタシのこの戦闘服にそっくりなんだ」"

[[dialogue]]
speaker = "unk"
# え……えええぇぇぇ～～～っ！？！？
line = "え……えええぇぇぇ～～～っ！？！？"

[[dialogue]]
speaker = "紅明"
# 「いやまぁ、驚くよね。アタシも現代に転生して、サンタの存在を初めて知った時はマジかよ、って思ったし」
line = "「いやまぁ、驚くよね。アタシも現代に転生して、サンタの存在を初めて知った時はマジかよ、って思ったし」"

[[dialogue]]
speaker = "紅明"
# 「元々はさ、アタシが村の子供たちに、１年頑張ったご褒美として贈り物をあげたいって思ったのがきっかけなんだよね」
line = "「元々はさ、アタシが村の子供たちに、１年頑張ったご褒美として贈り物をあげたいって思ったのがきっかけなんだよね」"

[[dialogue]]
speaker = "紅明"
# 「ただ、アタシも特別裕福ってわけじゃなかったから、プレゼントを配るにもお金がない。なら、星術でプレゼントを作れないかってことで、頑張って修行をしたんだ」
line = "「ただ、アタシも特別裕福ってわけじゃなかったから、プレゼントを配るにもお金がない。なら、星術でプレゼントを作れないかってことで、頑張って修行をしたんだ」"

[[dialogue]]
speaker = "紅明"
# 「そうして獲得したのが、この戦衣弐式――クリスマスフォームだったってわけ」
line = "「そうして獲得したのが、この戦衣弐式――クリスマスフォームだったってわけ」"

[[dialogue]]
speaker = "紅明"
# 「で、子供たちにサプライズしたかったから、付け髭で変装して、名前を<ruby=さんたくろう>三太九郎</ruby>って名乗ることに――」
line = "「で、子供たちにサプライズしたかったから、付け髭で変装して、名前を<ruby>三太九郎<rt>さんたくろう</rt></ruby>って名乗ることに――」"

[[dialogue]]
speaker = "unk"
# 待って待って、トナカイとソリは！？
line = "待って待って、トナカイとソリは！？"

[[dialogue]]
speaker = "紅明"
# 「多分なんだけど、ソリは悟空の筋斗雲じゃないかなって思うんだよね。三太九郎の噂が広がって、他の村にもプレゼント配ることになってさ」
line = "「多分なんだけど、ソリは悟空の筋斗雲じゃないかなって思うんだよね。三太九郎の噂が広がって、他の村にもプレゼント配ることになってさ」"

[[dialogue]]
speaker = "紅明"
# 「１人じゃ配り切れないから、悟空にもよく手伝って貰ってたんよ。で、プレゼントを筋斗雲に乗せて運んでたわけ」
line = "「１人じゃ配り切れないから、悟空にもよく手伝って貰ってたんよ。で、プレゼントを筋斗雲に乗せて運んでたわけ」"

[[dialogue]]
speaker = "紅明"
# 「トナカイは多分、アタシだと思う。ほら、角がそれっぽく変身してるっしょ？」
line = "「トナカイは多分、アタシだと思う。ほら、角がそれっぽく変身してるっしょ？」"

[[dialogue]]
speaker = "unk"
# マジか……！　サンタ、実在したんだ……！
line = "マジか……！　サンタ、実在したんだ……！"

[[dialogue]]
speaker = "紅明"
# 「２０００年も語り継がれるとは、夢にも思わなかったけどね～。だから、アタシはクリスマスって凄く思い入れがあるんよ」
line = "「２０００年も語り継がれるとは、夢にも思わなかったけどね～。だから、アタシはクリスマスって凄く思い入れがあるんよ」"

[[dialogue]]
speaker = "紅明"
# 「でも、ダーリンはちゃんと信じてくれるんだね。自分でも正直、妄想乙って言われそうなことを語ってると思うんだけど……」
line = "「でも、ダーリンはちゃんと信じてくれるんだね。自分でも正直、妄想乙って言われそうなことを語ってると思うんだけど……」"

[[dialogue]]
speaker = "unk"
# 好きな子のことだから、見てればわかるよ
line = "好きな子のことだから、見てればわかるよ"

[[dialogue]]
speaker = "紅明"
# 「――よくふざけるけど、真剣な時は違う顔をするから、それでわかる？」
line = "「――よくふざけるけど、真剣な時は違う顔をするから、それでわかる？」"

[[dialogue]]
speaker = "紅明"
# 「ダーリン……♪」
line = "「ダーリン……♪」"

[[dialogue]]
speaker = "紅明"
# 「本当に……大っ好きだぞ<emoji=heart04>」
line = "「本当に……大っ好きだぞ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「ん……<emoji=heart04>　ちゅっ<emoji=heart04>」
line = "「ん……<emoji=heart04>　ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "紅明"
# 「えへへ……今度はダーリンと一緒に２０００年くらい語り継がれちゃうような伝説、作っちゃおっか<emoji=heart04>」
line = "「えへへ……今度はダーリンと一緒に２０００年くらい語り継がれちゃうような伝説、作っちゃおっか<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# もちろん！
line = "もちろん！"

[[dialogue]]
speaker = "紅明"
# 「ダーリン、嬉しいっ<emoji=heart04>　じゃあもう一仕事、いっちゃいますか～<emoji=heart04>」
line = "「ダーリン、嬉しいっ<emoji=heart04>　じゃあもう一仕事、いっちゃいますか～<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そんなこんなで俺と紅明は、イチャイチャしながらモンスターをなぎ倒していくのであった――
line = "そんなこんなで俺と紅明は、イチャイチャしながらモンスターをなぎ倒していくのであった――"
