[[dialogue]]
speaker = "unk"
# 第３話,アイドルの可能性,P
line = "第３話,アイドルの可能性,P"

[[dialogue]]
speaker = "unk"
# とある放課後、ルルカが所属する聖歌隊の練習を見学しに、俺は大聖堂を訪れていた。
line = "とある放課後、ルルカが所属する聖歌隊の練習を見学しに、俺は大聖堂を訪れていた。"

[[dialogue]]
speaker = "ルルカ"
# 「あっ、お兄ちゃん！　見に来てくれたんだ～♪」
line = "「あっ、お兄ちゃん！　見に来てくれたんだ～♪」"

[[dialogue]]
speaker = "unk"
# 綺麗な歌声だったよ
line = "綺麗な歌声だったよ"

[[dialogue]]
speaker = "ルルカ"
# 「褒めてくれてありがとう♪　でも、コーラスだし、なかなか目立つのは難しいよね」
line = "「褒めてくれてありがとう♪　でも、コーラスだし、なかなか目立つのは難しいよね」"

[[dialogue]]
speaker = "ルルカ"
# 「単独で歌わせてもらえたら話は別なんだけど、先輩たちくらい上手にならなきゃ、逆に悪目立ちしちゃうし」
line = "「単独で歌わせてもらえたら話は別なんだけど、先輩たちくらい上手にならなきゃ、逆に悪目立ちしちゃうし」"

[[dialogue]]
speaker = "ルルカ"
# 「ほんっと、うちの聖歌隊って上手い人多すぎだよ。歌には自信があったあたしも、プライドをバキバキに折られちゃうレベルだもん」
line = "「ほんっと、うちの聖歌隊って上手い人多すぎだよ。歌には自信があったあたしも、プライドをバキバキに折られちゃうレベルだもん」"

[[dialogue]]
speaker = "ルルカ"
# 「お兄ちゃんはいつもあたしの歌を褒めてくれるし、Ｖチューバーとして人気が出てきた後は、歌が上手いって言われることも増えたんだけどね～」
line = "「お兄ちゃんはいつもあたしの歌を褒めてくれるし、Ｖチューバーとして人気が出てきた後は、歌が上手いって言われることも増えたんだけどね～」"

[[dialogue]]
speaker = "ルルカ"
# 「でも実際、突き抜けて歌が上手い人がすぐ近くにいると、圧倒されちゃう」
line = "「でも実際、突き抜けて歌が上手い人がすぐ近くにいると、圧倒されちゃう」"

[[dialogue]]
speaker = "unk"
# ルルカがちらっと視線を向ける。
line = "ルルカがちらっと視線を向ける。"

[[dialogue]]
speaker = "unk"
# その先には――
line = "その先には――"

[[dialogue]]
speaker = "ルルカ"
# 「世界的に有名な歌姫――レミカ先輩とかね」
line = "「世界的に有名な歌姫――レミカ先輩とかね」"

[[dialogue]]
speaker = "ルルカ"
# 「ほんっとにすごいんだよ、レミカ先輩。あたしのお母さん――<ruby=しおなぎ>汐凪</ruby>シャルルと同じくらい、天性の歌声を持ってる」
line = "「ほんっとにすごいんだよ、レミカ先輩。あたしのお母さん――<ruby>汐凪<rt>しおなぎ</rt></ruby>シャルルと同じくらい、天性の歌声を持ってる」"

[[dialogue]]
speaker = "unk"
# そういえば、ルルカはアイドルに興味ないのか？
line = "そういえば、ルルカはアイドルに興味ないのか？"

[[dialogue]]
speaker = "ルルカ"
# 「ん？　あ～、もちろんお母さんが昔活躍してた時の映像とか沢山見てきたから、興味がないわけじゃないよ」
line = "「ん？　あ～、もちろんお母さんが昔活躍してた時の映像とか沢山見てきたから、興味がないわけじゃないよ」"

[[dialogue]]
speaker = "ルルカ"
# 「その影響でＶチューバーを始めたって部分もあるし。でも、あたしの場合は『歌を唄うこと』への興味の方が、もっと強いって感じかな」
line = "「その影響でＶチューバーを始めたって部分もあるし。でも、あたしの場合は『歌を唄うこと』への興味の方が、もっと強いって感じかな」"

[[dialogue]]
speaker = "ルルカ"
# 「な～に、お兄ちゃん？　もしかしてあたしが、アイドルになる未来を想像しちゃった？」
line = "「な～に、お兄ちゃん？　もしかしてあたしが、アイドルになる未来を想像しちゃった？」"

[[dialogue]]
speaker = "unk"
# ちょっとだけ
line = "ちょっとだけ"

[[dialogue]]
speaker = "ルルカ"
# 「ふふっ。でも顔出しで『ルルカ』としてアイドルになっちゃったら、お兄ちゃんだけの『妹』じゃなくなっちゃうよ？」
line = "「ふふっ。でも顔出しで『ルルカ』としてアイドルになっちゃったら、お兄ちゃんだけの『妹』じゃなくなっちゃうよ？」"

[[dialogue]]
speaker = "ルルカ"
# 「大丈夫♪　あたしはず～っと、お兄ちゃんだけのアイドルで、妹カノジョだからね<emoji=heart04>」
line = "「大丈夫♪　あたしはず～っと、お兄ちゃんだけのアイドルで、妹カノジョだからね<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「ふふっ、でも妹で彼女か～。属性盛りすぎ<emoji=heart04>　ちょっと贅沢だよね♪」
line = "「ふふっ、でも妹で彼女か～。属性盛りすぎ<emoji=heart04>　ちょっと贅沢だよね♪」"

[[dialogue]]
speaker = "ルルカ"
# 「そうそう、アイドルと言えばこの前、芸能事務所の人が見学しに来たんだよ。レミカ先輩のいるポラリスプロダクションの人らしくて」
line = "「そうそう、アイドルと言えばこの前、芸能事務所の人が見学しに来たんだよ。レミカ先輩のいるポラリスプロダクションの人らしくて」"

[[dialogue]]
speaker = "ルルカ"
# 「聖歌隊の中にめぼしい子がいたら、スカウトするつもりだったみたい」
line = "「聖歌隊の中にめぼしい子がいたら、スカウトするつもりだったみたい」"

[[dialogue]]
speaker = "unk"
# まさかルルカもスカウトを？
line = "まさかルルカもスカウトを？"

[[dialogue]]
speaker = "ルルカ"
# 「あ、うん。一応、名刺はもらったけど……」
line = "「あ、うん。一応、名刺はもらったけど……」"

[[dialogue]]
speaker = "unk"
# ルルカがアイドルになったら困る！
line = "ルルカがアイドルになったら困る！"

[[dialogue]]
speaker = "ルルカ"
# 「えっ！？　そこまでなの？　お兄ちゃん的には、てっきりアイドル活動してるあたしも見てみたい～って感じだと思ってたんだけど……」
line = "「えっ！？　そこまでなの？　お兄ちゃん的には、てっきりアイドル活動してるあたしも見てみたい～って感じだと思ってたんだけど……」"

[[dialogue]]
speaker = "ルルカ"
# 「でも、安心して。スカウトされたけど、ちゃんと断っておいたから」
line = "「でも、安心して。スカウトされたけど、ちゃんと断っておいたから」"

[[dialogue]]
speaker = "ルルカ"
# 「――あたしにはもう『ルカルカ』の活動があるからね。いつも見に来てくれる『お兄ちゃん』『お姉ちゃん』を大事にしたいから」
line = "「――あたしにはもう『ルカルカ』の活動があるからね。いつも見に来てくれる『お兄ちゃん』『お姉ちゃん』を大事にしたいから」"

[[dialogue]]
speaker = "ルルカ"
# 「今のルカルカがあるのは、リスナーさん達のおかげだもん」
line = "「今のルカルカがあるのは、リスナーさん達のおかげだもん」"

[[dialogue]]
speaker = "ルルカ"
# 「あ、もちろんお兄ちゃんのおかげでもあるんだよ？　感謝してもしきれないほど、たくさん協力してもらってるしね」
line = "「あ、もちろんお兄ちゃんのおかげでもあるんだよ？　感謝してもしきれないほど、たくさん協力してもらってるしね」"

[[dialogue]]
speaker = "ルルカ"
# 「それに彼氏としても……いつもあたしに頑張る力をくれてありがとうね、お兄ちゃん<emoji=heart04>」
line = "「それに彼氏としても……いつもあたしに頑張る力をくれてありがとうね、お兄ちゃん<emoji=heart04>」"

[[dialogue]]
speaker = "ルルカ"
# 「って、そんな話してたら、なんだかちょっと……」
line = "「って、そんな話してたら、なんだかちょっと……」"

[[dialogue]]
speaker = "ルルカ"
# 「キス、したくなってきちゃった<emoji=heart04>　でも、ダメだよね……周りに聖歌隊のみんながいるし……」
line = "「キス、したくなってきちゃった<emoji=heart04>　でも、ダメだよね……周りに聖歌隊のみんながいるし……」"

[[dialogue]]
speaker = "ルルカ"
# 「ん～、だけどお兄ちゃん成分もちょっと充電したいし……ここでしても大丈夫そうなイチャイチャというと――」
line = "「ん～、だけどお兄ちゃん成分もちょっと充電したいし……ここでしても大丈夫そうなイチャイチャというと――」"

[[dialogue]]
speaker = "unk"
# ルルカは俺の手を取って、そっと繋いできた。
line = "ルルカは俺の手を取って、そっと繋いできた。"

[[dialogue]]
speaker = "ルルカ"
# 「えへへ<emoji=heart04>　これくらいならセーフ……だよね？」
line = "「えへへ<emoji=heart04>　これくらいならセーフ……だよね？」"

[[dialogue]]
speaker = "unk"
# どっちにしても注目されちゃうぞ？
line = "どっちにしても注目されちゃうぞ？"

[[dialogue]]
speaker = "ルルカ"
# 「え？　あ、あれ？　あたし達は恋人同士だって知られてるし、手を繋いでるだけなのに……」
line = "「え？　あ、あれ？　あたし達は恋人同士だって知られてるし、手を繋いでるだけなのに……」"

[[dialogue]]
speaker = "ルルカ"
# 「指を絡める『恋人繋ぎ』って、そ、そんなに恥ずかしいことだったかな……？」
line = "「指を絡める『恋人繋ぎ』って、そ、そんなに恥ずかしいことだったかな……？」"

[[dialogue]]
speaker = "ルルカ"
# 「うぅ～……な、なんか、急に顔が熱くなってきちゃった……」
line = "「うぅ～……な、なんか、急に顔が熱くなってきちゃった……」"

[[dialogue]]
speaker = "ルルカ"
# 「と、とりあえず、そろそろ休憩終わるから、あたし行くねっ」
line = "「と、とりあえず、そろそろ休憩終わるから、あたし行くねっ」"

[[dialogue]]
speaker = "ルルカ"
# 「あ、そうだ――」
line = "「あ、そうだ――」"

[[dialogue]]
speaker = "unk"
# ルルカは俺の耳元に顔を近づけて、囁く。
line = "ルルカは俺の耳元に顔を近づけて、囁く。"

[[dialogue]]
speaker = "ルルカ"
# 「練習が終わったら、一緒に帰ろ？　それで……」
line = "「練習が終わったら、一緒に帰ろ？　それで……」"

[[dialogue]]
speaker = "ルルカ"
# 「２人きりになったら、いっぱいキスしようね、お兄ちゃん<emoji=heart04>」
line = "「２人きりになったら、いっぱいキスしようね、お兄ちゃん<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そう言って、手を振りながら、ルルカは練習へと戻って行く。
line = "そう言って、手を振りながら、ルルカは練習へと戻って行く。"

[[dialogue]]
speaker = "unk"
# 俺は耳元に甘い囁きの余韻を残したまま、彼女の練習が終わるのが待ち遠しくなってしまうのだった――
line = "俺は耳元に甘い囁きの余韻を残したまま、彼女の練習が終わるのが待ち遠しくなってしまうのだった――"
