[[dialogue]]
speaker = "unk"
# 第４話,愛しの女神に捧ぐ,P
line = "第４話,愛しの女神に捧ぐ,P"

[[dialogue]]
speaker = "unk"
# 休日、俺はヴィーナスと遊園地デートへやって来ていた――
line = "休日、俺はヴィーナスと遊園地デートへやって来ていた――"

[[dialogue]]
speaker = "ヴィーナス"
# 「最近はクロト、ちょっと忙しそうにしてたから、久しぶりのデートね♪」
line = "「最近はクロト、ちょっと忙しそうにしてたから、久しぶりのデートね♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「その分、今日は目いっぱい遊んじゃうわよ～！」
line = "「その分、今日は目いっぱい遊んじゃうわよ～！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「まずは何と言ってもジェットコースターからね！　行きましょ、クロト♪」
line = "「まずは何と言ってもジェットコースターからね！　行きましょ、クロト♪」"

[[dialogue]]
speaker = "unk"
# そうして、ジェットコースターに乗ることになり――
line = "そうして、ジェットコースターに乗ることになり――"

[[dialogue]]
speaker = "ヴィーナス"
# 「わぁーーーいっ♪　空を全速力で飛び回るのもいいけど、ジェットコースターはやっぱり別腹ね♪」
line = "「わぁーーーいっ♪　空を全速力で飛び回るのもいいけど、ジェットコースターはやっぱり別腹ね♪」"

[[dialogue]]
speaker = "unk"
# ちなみに、ヴィーナスは絶叫マシーンを一切怖がったりしない。
line = "ちなみに、ヴィーナスは絶叫マシーンを一切怖がったりしない。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、もうすぐでっかい下り坂が来るわよ！　せ～のっ――」
line = "「あっ、もうすぐでっかい下り坂が来るわよ！　せ～のっ――」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ぎゅーーーんっ！　あははははははっ♪　楽しいぃ～～～っ♪」
line = "「ぎゅーーーんっ！　あははははははっ♪　楽しいぃ～～～っ♪」"

[[dialogue]]
speaker = "unk"
# 保護者のヘレナちゃん曰く、遊園地で初めてジェットコースターに乗った時の感想は「めちゃんこ楽しかった～！　でも、この安全バーっている？」だったとか。
line = "保護者のヘレナちゃん曰く、遊園地で初めてジェットコースターに乗った時の感想は「めちゃんこ楽しかった～！　でも、この安全バーっている？」だったとか。"

[[dialogue]]
speaker = "unk"
# それからも遊園地を満喫して、夕方になったところで、俺はヴィーナスを誘って観覧車に乗り込んだ。
line = "それからも遊園地を満喫して、夕方になったところで、俺はヴィーナスを誘って観覧車に乗り込んだ。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ねぇ、パパ、膝の上に座ってもいい？」
line = "「ねぇ、パパ、膝の上に座ってもいい？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「――えへへ<emoji=heart04>　やったぁ♪」
line = "「――えへへ<emoji=heart04>　やったぁ♪」"

[[dialogue]]
speaker = "unk"
# 観覧車の中で、俺の膝に乗るヴィーナス。
line = "観覧車の中で、俺の膝に乗るヴィーナス。"

[[dialogue]]
speaker = "ヴィーナス"
# 「～～♪　～～～♪」
line = "「～～♪　～～～♪」"

[[dialogue]]
speaker = "unk"
# そのまま機嫌良さそうに鼻歌を唄い始める。
line = "そのまま機嫌良さそうに鼻歌を唄い始める。"

[[dialogue]]
speaker = "unk"
# そんな娘兼恋人の姿を見ていると、愛おしい気持ちが溢れてしまい、思わず頭を撫でてしまう。
line = "そんな娘兼恋人の姿を見ていると、愛おしい気持ちが溢れてしまい、思わず頭を撫でてしまう。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ♪　えへへへ……<emoji=heart04>　パパの頭なでなで、好き～<emoji=heart04>」
line = "「あっ♪　えへへへ……<emoji=heart04>　パパの頭なでなで、好き～<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んふふふ<emoji=heart04>　私も頬っぺすりすりしちゃうんだから<emoji=heart04>」
line = "「んふふふ<emoji=heart04>　私も頬っぺすりすりしちゃうんだから<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ほら、パ～パ<emoji=heart04>　すりすり～……<emoji=heart04>」
line = "「ほら、パ～パ<emoji=heart04>　すりすり～……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そんな風にしばらく、恋人のスキンシップを楽しんだ後……
line = "そんな風にしばらく、恋人のスキンシップを楽しんだ後……"

[[dialogue]]
speaker = "ヴィーナス"
# 「――ん？　パパ、改まってどうしたの？」
line = "「――ん？　パパ、改まってどうしたの？」"

[[dialogue]]
speaker = "unk"
# ヴィーナスに渡したいものがあるんだ
line = "ヴィーナスに渡したいものがあるんだ"

[[dialogue]]
speaker = "ヴィーナス"
# 「渡したいもの？　なにかしら？」
line = "「渡したいもの？　なにかしら？」"

[[dialogue]]
speaker = "unk"
# 俺はポケットから小さな箱を取り出して、開いて中を見せる。
line = "俺はポケットから小さな箱を取り出して、開いて中を見せる。"

[[dialogue]]
speaker = "ヴィーナス"
# 「これって……指輪？」
line = "「これって……指輪？」"

[[dialogue]]
speaker = "unk"
# 実はここ最近忙しかったのは――
line = "実はここ最近忙しかったのは――"

[[dialogue]]
speaker = "unk"
# ヘレナちゃんに頼んで、公安委員会の仕事を紹介して貰い、それを夜や休日にこなしていたのだった。
line = "ヘレナちゃんに頼んで、公安委員会の仕事を紹介して貰い、それを夜や休日にこなしていたのだった。"

[[dialogue]]
speaker = "unk"
# その理由は、ヴィーナスにこの――婚約指輪を買って渡す為。
line = "その理由は、ヴィーナスにこの――婚約指輪を買って渡す為。"

[[dialogue]]
speaker = "ヴィーナス"
# 「前に結婚するって誓ったから、それの証として……？」
line = "「前に結婚するって誓ったから、それの証として……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロト！　私、すごく嬉しいわ♪」
line = "「クロト！　私、すごく嬉しいわ♪」"

[[dialogue]]
speaker = "unk"
# ただ、デートが出来てなかったのはごめん
line = "ただ、デートが出来てなかったのはごめん"

[[dialogue]]
speaker = "ヴィーナス"
# 「休日で会えない日も確かにあったけど、私、寂しいとは全然感じなかったわよ？」
line = "「休日で会えない日も確かにあったけど、私、寂しいとは全然感じなかったわよ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だってクロトって、会えない日でも連絡をくれるし、いつだって私を気にかけてくれるでしょう？」
line = "「だってクロトって、会えない日でも連絡をくれるし、いつだって私を気にかけてくれるでしょう？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「この指輪だって、私のことが１番好きだってことを形にしてくれてる……」
line = "「この指輪だって、私のことが１番好きだってことを形にしてくれてる……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だからとっても嬉しいわ！　クロトが私を想ってくれた時間と愛情の結晶だもの♪」
line = "「だからとっても嬉しいわ！　クロトが私を想ってくれた時間と愛情の結晶だもの♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ねぇ、指にはめてみてもいい？」
line = "「ねぇ、指にはめてみてもいい？」"

[[dialogue]]
speaker = "unk"
# 俺は頷き、指輪を手に取る。
line = "俺は頷き、指輪を手に取る。"

[[dialogue]]
speaker = "unk"
# それから、ヴィーナスの背中側から手を伸ばして、彼女の左手をそっと握る。
line = "それから、ヴィーナスの背中側から手を伸ばして、彼女の左手をそっと握る。"

[[dialogue]]
speaker = "ヴィーナス"
# 「えへへ……♪　クロトが付けてくれるの？」
line = "「えへへ……♪　クロトが付けてくれるの？」"

[[dialogue]]
speaker = "unk"
# 俺は改めて伝える。
line = "俺は改めて伝える。"

[[dialogue]]
speaker = "unk"
# ヴィーナス、俺と結婚して欲しい
line = "ヴィーナス、俺と結婚して欲しい"

[[dialogue]]
speaker = "ヴィーナス"
# 「うんっ♪　これからもずっと、学園を卒業しても一緒よ、クロト♪」
line = "「うんっ♪　これからもずっと、学園を卒業しても一緒よ、クロト♪」"

[[dialogue]]
speaker = "unk"
# ヴィーナスの左手の薬指に指輪を付ける。
line = "ヴィーナスの左手の薬指に指輪を付ける。"

[[dialogue]]
speaker = "unk"
# 彼女はそれを嬉しそうに見つめながら──
line = "彼女はそれを嬉しそうに見つめながら──"

[[dialogue]]
speaker = "ヴィーナス"
# 「えへへへへへぇ～<emoji=heart04>　ありがとう♪　それと……」
line = "「えへへへへへぇ～<emoji=heart04>　ありがとう♪　それと……」"

[[dialogue]]
speaker = "unk"
# 身体を反転させて、向き合う体勢に座り直してから、ぎゅっと抱き着いて来る。
line = "身体を反転させて、向き合う体勢に座り直してから、ぎゅっと抱き着いて来る。"

[[dialogue]]
speaker = "ヴィーナス"
# 「本当に結婚しちゃったら、旦那さんって意味でパパになっちゃうわね♪」
line = "「本当に結婚しちゃったら、旦那さんって意味でパパになっちゃうわね♪」"

[[dialogue]]
speaker = "unk"
# 夫婦でもあるって関係を、特別に思ってる
line = "夫婦でもあるって関係を、特別に思ってる"

[[dialogue]]
speaker = "unk"
# それも嬉しいけど、今では親子でありつつ
line = "それも嬉しいけど、今では親子でありつつ"

[[dialogue]]
speaker = "ヴィーナス"
# 「確かにそうね<emoji=heart04>」
line = "「確かにそうね<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私の最愛の人は、パパでありクロトだから、私の運命そのものなんだもの<emoji=heart04>」
line = "「私の最愛の人は、パパでありクロトだから、私の運命そのものなんだもの<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 彼女の柔らかさや温かさ、それと好きな女の子のいい匂いが伝わって来て、幸せを感じる。
line = "彼女の柔らかさや温かさ、それと好きな女の子のいい匂いが伝わって来て、幸せを感じる。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ねぇ、パパ？　私、指輪だけじゃなくて、誓いのキスもしたいわ<emoji=heart04>」
line = "「ねぇ、パパ？　私、指輪だけじゃなくて、誓いのキスもしたいわ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは１度見つめ合える距離まで顔を離してから、俺と両手を繋ぐ。
line = "ヴィーナスは１度見つめ合える距離まで顔を離してから、俺と両手を繋ぐ。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ん……<emoji=heart04>　ただ手を繋ぐんじゃなくて、指も絡めなくちゃイヤ……<emoji=heart04>」
line = "「ん……<emoji=heart04>　ただ手を繋ぐんじゃなくて、指も絡めなくちゃイヤ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ヴィーナスの要望に応えて、両手の指を絡め直して、恋人繋ぎにする。
line = "ヴィーナスの要望に応えて、両手の指を絡め直して、恋人繋ぎにする。"

[[dialogue]]
speaker = "unk"
# そして――
line = "そして――"

[[dialogue]]
speaker = "ヴィーナス"
# 「パパ<emoji=heart04>　ん～……<emoji=heart04>」
line = "「パパ<emoji=heart04>　ん～……<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ちゅっ<emoji=heart04>」
line = "「ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んっ……<emoji=heart04>　好き<emoji=heart04>　ちゅっ……<emoji=heart04>　世界で一番大好きっ<emoji=heart04>」
line = "「んっ……<emoji=heart04>　好き<emoji=heart04>　ちゅっ……<emoji=heart04>　世界で一番大好きっ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ちゅっ……<emoji=heart04>　ちゅっ<emoji=heart04>」
line = "「ちゅっ……<emoji=heart04>　ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 観覧車が地上に降りるギリギリまで、俺たちはこれまでで一番甘いキスを交わすのだった――
line = "観覧車が地上に降りるギリギリまで、俺たちはこれまでで一番甘いキスを交わすのだった――"
