[[dialogue]]
speaker = "unk"
# 第１話,夏の最強,P
line = "第１話,夏の最強,P"

[[dialogue]]
speaker = "unk"
# 夏のある日。星徒会の仕事が早く片付いたので、星徒会みんなでリゾート結界に遊びに来ていた。
line = "夏のある日。星徒会の仕事が早く片付いたので、星徒会みんなでリゾート結界に遊びに来ていた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「マトイ、もうちょっと右よ！　あー、行きすぎ！」
line = "「マトイ、もうちょっと右よ！　あー、行きすぎ！」"

[[dialogue]]
speaker = "マトイ"
# 「もうちょっとじゃ分かんないよ！　もっと具体的にお願い！」
line = "「もうちょっとじゃ分かんないよ！　もっと具体的にお願い！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「もうちょっとはもうちょっとよ！　あ、今度は左に行きすぎたわ！」
line = "「もうちょっとはもうちょっとよ！　あ、今度は左に行きすぎたわ！」"

[[dialogue]]
speaker = "マトイ"
# 「えー！？」
line = "「えー！？」"

[[dialogue]]
speaker = "unk"
# マトイとヴィーナスがスイカ割りをしているが、ヴィーナスの指示が大雑把すぎて苦戦しているようだ。
line = "マトイとヴィーナスがスイカ割りをしているが、ヴィーナスの指示が大雑把すぎて苦戦しているようだ。"

[[dialogue]]
speaker = "アナ"
# 「おお、宇治金時。なんと素晴らしい響きでしょうか。抹茶と小豆のハーモニーは氷の上でも完璧です」
line = "「おお、宇治金時。なんと素晴らしい響きでしょうか。抹茶と小豆のハーモニーは氷の上でも完璧です」"

[[dialogue]]
speaker = "サーシャ"
# 「私はどうしようかしら……アナちゃんの宇治金時も美味しそうだし、イチゴ練乳もブルーハワイも捨てがたいわ～」
line = "「私はどうしようかしら……アナちゃんの宇治金時も美味しそうだし、イチゴ練乳もブルーハワイも捨てがたいわ～」"

[[dialogue]]
speaker = "アナ"
# 「では両方頼んでシェアしませんか。実は私も気になっていたので」
line = "「では両方頼んでシェアしませんか。実は私も気になっていたので」"

[[dialogue]]
speaker = "サーシャ"
# 「それはナイスアイディアだわ～。ありがとう、アナちゃん」
line = "「それはナイスアイディアだわ～。ありがとう、アナちゃん」"

[[dialogue]]
speaker = "unk"
# 平和だ……
line = "平和だ……"

[[dialogue]]
speaker = "unk"
# こんなにゆったり時間が流れるのはいつ以来だろう。この平和がずっと続けばいいのに。
line = "こんなにゆったり時間が流れるのはいつ以来だろう。この平和がずっと続けばいいのに。"

[[dialogue]]
speaker = "イングリット"
# 「いいところで会ったな。私と戦え、魔王」
line = "「いいところで会ったな。私と戦え、魔王」"

[[dialogue]]
speaker = "unk"
# 平和は１秒で崩壊した。
line = "平和は１秒で崩壊した。"

[[dialogue]]
speaker = "unk"
# その恰好は？
line = "その恰好は？"

[[dialogue]]
speaker = "イングリット"
# 「これはネビュラに作らせた水着型の人工戦闘服だ。今日はこいつの試しで泳ぎに来ていたのだが、貴様に会えるとは運がいい」
line = "「これはネビュラに作らせた水着型の人工戦闘服だ。今日はこいつの試しで泳ぎに来ていたのだが、貴様に会えるとは運がいい」"

[[dialogue]]
speaker = "unk"
# 水着、似合ってる
line = "水着、似合ってる"

[[dialogue]]
speaker = "unk"
# 中身はともかく見た目は美人でスタイルもいい。思わず口に出ていた。
line = "中身はともかく見た目は美人でスタイルもいい。思わず口に出ていた。"

[[dialogue]]
speaker = "イングリット"
# 「そうだろうそうだろう。動きやすくて私も気に入っている」
line = "「そうだろうそうだろう。動きやすくて私も気に入っている」"

[[dialogue]]
speaker = "イングリット"
# 「ちなみに得物も新しくなっていてな。星力の使い方次第で打撃も斬撃もできる優れ物だ。ククク、気になるだろう？」
line = "「ちなみに得物も新しくなっていてな。星力の使い方次第で打撃も斬撃もできる優れ物だ。ククク、気になるだろう？」"

[[dialogue]]
speaker = "イングリット"
# 「というわけだ、私と戦え」
line = "「というわけだ、私と戦え」"

[[dialogue]]
speaker = "イングリット"
# 「……イヤだと？　なぜだ！？　この私の新しい力だぞ？　気になって仕方ないだろう。正直になれ、魔王」
line = "「……イヤだと？　なぜだ！？　この私の新しい力だぞ？　気になって仕方ないだろう。正直になれ、魔王」"

[[dialogue]]
speaker = "イングリット"
# 「……興味がない？　しらばっくれるな。なら、なぜ貴様は私をジロジロ見ているんだ？」
line = "「……興味がない？　しらばっくれるな。なら、なぜ貴様は私をジロジロ見ているんだ？」"

[[dialogue]]
speaker = "unk"
# イングリットの体に目がいっているだけなのだが、それを正直に言うこともできない。
line = "イングリットの体に目がいっているだけなのだが、それを正直に言うこともできない。"

[[dialogue]]
speaker = "イングリット"
# 「戦え、でないと大声で喚き散らすぞ」
line = "「戦え、でないと大声で喚き散らすぞ」"

[[dialogue]]
speaker = "unk"
# それはやめて
line = "それはやめて"

[[dialogue]]
speaker = "イングリット"
# 「ふむ。なら……」
line = "「ふむ。なら……」"

[[dialogue]]
speaker = "イングリット"
# 「たーたかえ……たーたかえ……そんなに戦うのが怖いかザーコ」
line = "「たーたかえ……たーたかえ……そんなに戦うのが怖いかザーコ」"

[[dialogue]]
speaker = "unk"
# 耳元でささやくのもやめて
line = "耳元でささやくのもやめて"

[[dialogue]]
speaker = "イングリット"
# 「大声はやめろと言うから小声で言ってやったのに、我儘な奴め。貴様が戦わないと、私が夏の最強になれないではないか」
line = "「大声はやめろと言うから小声で言ってやったのに、我儘な奴め。貴様が戦わないと、私が夏の最強になれないではないか」"

[[dialogue]]
speaker = "イングリット"
# 「……夏の最強とは、だと？　いいだろう、説明してやろう」
line = "「……夏の最強とは、だと？　いいだろう、説明してやろう」"

[[dialogue]]
speaker = "イングリット"
# 「聞けば、私のように水着の戦闘服を持つ星騎士も多いという。ならば、その中でもっとも強い者が夏の最強だ。私がさっき決めた」
line = "「聞けば、私のように水着の戦闘服を持つ星騎士も多いという。ならば、その中でもっとも強い者が夏の最強だ。私がさっき決めた」"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロト、誰その天使？　知ってる人？」
line = "「クロト、誰その天使？　知ってる人？」"

[[dialogue]]
speaker = "マトイ"
# 「ヴィーナス？　ヴィーナスどこいったの～！？」
line = "「ヴィーナス？　ヴィーナスどこいったの～！？」"

[[dialogue]]
speaker = "unk"
# いつの間にか、ヴィーナスがイングリットに気付いてやってきていた。向こうで放置されたマトイが右往左往している。
line = "いつの間にか、ヴィーナスがイングリットに気付いてやってきていた。向こうで放置されたマトイが右往左往している。"

[[dialogue]]
speaker = "イングリット"
# 「私はイングリット。コラプサーだ。貴様こそ何者だ」
line = "「私はイングリット。コラプサーだ。貴様こそ何者だ」"

[[dialogue]]
speaker = "unk"
# かつて星騎士と敵対していた組織・コラプサーの一員で、今は敵ではないが、それはそれとして戦うことしか頭にない生粋の戦闘狂だ。
line = "かつて星騎士と敵対していた組織・コラプサーの一員で、今は敵ではないが、それはそれとして戦うことしか頭にない生粋の戦闘狂だ。"

[[dialogue]]
speaker = "unk"
# コラプサー随一のトラブルメーカーとして学園内でも有名である。
line = "コラプサー随一のトラブルメーカーとして学園内でも有名である。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あなたが噂の不審者ね。私は九浄ヴィーナス！　星徒会のスーパーフィクサーとは私のことよ！」
line = "「あなたが噂の不審者ね。私は九浄ヴィーナス！　星徒会のスーパーフィクサーとは私のことよ！」"

[[dialogue]]
speaker = "イングリット"
# 「ボーナスだかピーナッツだか知らんが、邪魔をするなら容赦せんぞ。私は魔王と戦いたいのだ」
line = "「ボーナスだかピーナッツだか知らんが、邪魔をするなら容赦せんぞ。私は魔王と戦いたいのだ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ヴィーナスよ！　今日は星徒会で遊びに来たのよ。そっちこそ邪魔しないでちょうだい」
line = "「ヴィーナスよ！　今日は星徒会で遊びに来たのよ。そっちこそ邪魔しないでちょうだい」"

[[dialogue]]
speaker = "イングリット"
# 「どうやら退く気はないようだな」
line = "「どうやら退く気はないようだな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そっちもね。行くわよ！」
line = "「そっちもね。行くわよ！」"

[[dialogue]]
speaker = "イングリット"
# 「叩き斬る！　ツインリッパー！」
line = "「叩き斬る！　ツインリッパー！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「行っけー！　サマーレーヴァテイン！」
line = "「行っけー！　サマーレーヴァテイン！」"

[[dialogue]]
speaker = "イングリット"
# 「この星力の輝き、ただ者ではないな。強き水着星騎士として認めてやろう。私が夏の最強となるための糧となれ！」
line = "「この星力の輝き、ただ者ではないな。強き水着星騎士として認めてやろう。私が夏の最強となるための糧となれ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「夏の最強って何？」
line = "「夏の最強って何？」"

[[dialogue]]
speaker = "unk"
# 一番強い水着星騎士のことらしい
line = "一番強い水着星騎士のことらしい"

[[dialogue]]
speaker = "ヴィーナス"
# 「なんでクロトが答えるのよ。でもそう言われたら、私だって譲れな……はっ、そうだわ！」
line = "「なんでクロトが答えるのよ。でもそう言われたら、私だって譲れな……はっ、そうだわ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「もしもし、ヘレナちゃん？　ちょっと思いついたんだけど……」
line = "「もしもし、ヘレナちゃん？　ちょっと思いついたんだけど……」"

[[dialogue]]
speaker = "イングリット"
# 「何をしている？　来ないならこちらから行くぞ」
line = "「何をしている？　来ないならこちらから行くぞ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……うん、よろしくお願いね。じゃ、また後で」
line = "「……うん、よろしくお願いね。じゃ、また後で」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ねぇイングリット。私たちだけで夏の最強を決めるのはもったいないと思わない？」
line = "「ねぇイングリット。私たちだけで夏の最強を決めるのはもったいないと思わない？」"

[[dialogue]]
speaker = "イングリット"
# 「なんだと？　貴様、何を言って……」
line = "「なんだと？　貴様、何を言って……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ごにょごにょごにょ……」
line = "「ごにょごにょごにょ……」"

[[dialogue]]
speaker = "イングリット"
# 「……クク、クハハハハッ！！　面白いことを考えるではないか！　ヴィーナスといったな！　気に入ったぞ！」
line = "「……クク、クハハハハッ！！　面白いことを考えるではないか！　ヴィーナスといったな！　気に入ったぞ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「イングリットもね。私たち、仲良くなれそうね！」
line = "「イングリットもね。私たち、仲良くなれそうね！」"

[[dialogue]]
speaker = "unk"
# 熱い握手を交わす２人。
line = "熱い握手を交わす２人。"

[[dialogue]]
speaker = "unk"
# ヴィーナスもナチュラルにバトルマニアであったことを失念していた。この２人の同調に、嫌な予感しかない。
line = "ヴィーナスもナチュラルにバトルマニアであったことを失念していた。この２人の同調に、嫌な予感しかない。"

[[dialogue]]
speaker = "イングリット"
# 「星騎士どもよ、夏の最強はこのイングリットだ。首を洗って待っていろ。クハハハ！！」
line = "「星騎士どもよ、夏の最強はこのイングリットだ。首を洗って待っていろ。クハハハ！！」"
