[[dialogue]]
speaker = "unk"
# 第２話,何も起きないはずがなく……！,P
line = "第２話,何も起きないはずがなく……！,P"

[[dialogue]]
speaker = "イクシリオン"
# 「し、失礼します！　星徒会の皆様……！」
line = "「し、失礼します！　星徒会の皆様……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あら？　保健委員の子ね。確か……」
line = "「あら？　保健委員の子ね。確か……」"

[[dialogue]]
speaker = "イクシリオン"
# 「イ、イクシリオンと申します。以後、お見知りおきのほどを……！」
line = "「イ、イクシリオンと申します。以後、お見知りおきのほどを……！」"

[[dialogue]]
speaker = "イクシリオン"
# 「え、えと、保健委員から、星徒会長宛ての書類をいくつか、お持ちしまして……」
line = "「え、えと、保健委員から、星徒会長宛ての書類をいくつか、お持ちしまして……」"

[[dialogue]]
speaker = "unk"
# ありがとう、イクシー
line = "ありがとう、イクシー"

[[dialogue]]
speaker = "イクシリオン"
# 「どうぞっ！　ご査収くださいませ……！」
line = "「どうぞっ！　ご査収くださいませ……！」"

[[dialogue]]
speaker = "マトイ"
# 「あはは。緊張しちゃってるのかな。普通にリラックスしてくれて大丈夫だよ？」
line = "「あはは。緊張しちゃってるのかな。普通にリラックスしてくれて大丈夫だよ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうそう。新星星徒会はアットホームな職場なんだから」
line = "「そうそう。新星星徒会はアットホームな職場なんだから」"

[[dialogue]]
speaker = "サーシャ"
# 「うふふ、いらっしゃ～い。未経験者も大歓迎よ～」
line = "「うふふ、いらっしゃ～い。未経験者も大歓迎よ～」"

[[dialogue]]
speaker = "アナ"
# 「職場ではないですし今は募集もしてません」
line = "「職場ではないですし今は募集もしてません」"

[[dialogue]]
speaker = "イクシリオン"
# 「お、お気遣いありがとうございます……」
line = "「お、お気遣いありがとうございます……」"

[[dialogue]]
speaker = "イクシリオン"
# （と、とうとう……入ってしまいました。新星学園の星徒会室……！）
line = "（と、とうとう……入ってしまいました。新星学園の星徒会室……！）"

[[dialogue]]
speaker = "イクシリオン"
# （う、噂通りです、本当にお綺麗な方ばっかり……！　それに……）
line = "（う、噂通りです、本当にお綺麗な方ばっかり……！　それに……）"

[[dialogue]]
speaker = "イクシリオン"
# （おふたりのおっぱいが！　大きい！！）
line = "（おふたりのおっぱいが！　大きい！！）"

[[dialogue]]
speaker = "イクシリオン"
# （私もそれなりだとは思っていますが、ヴィーナスさんとサーシャさんもすごいですね……！）
line = "（私もそれなりだとは思っていますが、ヴィーナスさんとサーシャさんもすごいですね……！）"

[[dialogue]]
speaker = "サーシャ"
# 「あらら？　どこ見てるの～？」
line = "「あらら？　どこ見てるの～？」"

[[dialogue]]
speaker = "イクシリオン"
# 「いい、いえっ、やましいことなんて何もありませんよ？　イクシリオンは健全な天使でありまするのでっ」
line = "「いい、いえっ、やましいことなんて何もありませんよ？　イクシリオンは健全な天使でありまするのでっ」"

[[dialogue]]
speaker = "サーシャ"
# 「語尾がおかしくなってるけど、そうなのね～」
line = "「語尾がおかしくなってるけど、そうなのね～」"

[[dialogue]]
speaker = "イクシリオン"
# （男性は会長１人だけ……！）
line = "（男性は会長１人だけ……！）"

[[dialogue]]
speaker = "イクシリオン"
# （まるで漫画のようなシチュエーションです！　密室に若い男女がこんなにいて、何も起きないはずがなく……！）
line = "（まるで漫画のようなシチュエーションです！　密室に若い男女がこんなにいて、何も起きないはずがなく……！）"

[[dialogue]]
speaker = "イクシリオン"
# （会長は毎日女の子をとっかえひっかえ……いえ、同時に何人か相手をしたり……まさか全員一緒に！？）
line = "（会長は毎日女の子をとっかえひっかえ……いえ、同時に何人か相手をしたり……まさか全員一緒に！？）"

[[dialogue]]
speaker = "イクシリオン"
# 「あわわ……！？　めくるめく世界が広がっています……！」
line = "「あわわ……！？　めくるめく世界が広がっています……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふやけた顔しちゃってるけど、どうしちゃったのかしら、この子。お～い」
line = "「ふやけた顔しちゃってるけど、どうしちゃったのかしら、この子。お～い」"

[[dialogue]]
speaker = "イクシリオン"
# 「──ふあっ！？　すみません、私ったらまたはしたない……」
line = "「──ふあっ！？　すみません、私ったらまたはしたない……」"

[[dialogue]]
speaker = "unk"
# （はしたない……？）
line = "（はしたない……？）"

[[dialogue]]
speaker = "ヴィーナス"
# 「疲れちゃってるのかしら？　だったらちょうどいいわ、今からお楽しみタイムなの。あなたも混ざっていって！」
line = "「疲れちゃってるのかしら？　だったらちょうどいいわ、今からお楽しみタイムなの。あなたも混ざっていって！」"

[[dialogue]]
speaker = "イクシリオン"
# 「お楽しみタイム……！？　わ、私も……！？」
line = "「お楽しみタイム……！？　わ、私も……！？」"

[[dialogue]]
speaker = "マトイ"
# 「いいね！　たまには星徒会以外の人もいたら楽しそう♪」
line = "「いいね！　たまには星徒会以外の人もいたら楽しそう♪」"

[[dialogue]]
speaker = "イクシリオン"
# 「は、はわわわ！　いつもは星徒会役員のみなさんで！？　や、やはり星徒会は……会長の……！？」
line = "「は、はわわわ！　いつもは星徒会役員のみなさんで！？　や、やはり星徒会は……会長の……！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「え～っと、今日は誰が入れる？」
line = "「え～っと、今日は誰が入れる？」"

[[dialogue]]
speaker = "イクシリオン"
# （入れる！？　星徒会でそんなあけすけな言い方を……！？）
line = "（入れる！？　星徒会でそんなあけすけな言い方を……！？）"

[[dialogue]]
speaker = "サーシャ"
# 「この前は私だったわね～」
line = "「この前は私だったわね～」"

[[dialogue]]
speaker = "イクシリオン"
# （完全に常態化しています！？　ただれた星徒会室……そんな……漫画だけの世界じゃなかったのですね……ごくりっ……！）
line = "（完全に常態化しています！？　ただれた星徒会室……そんな……漫画だけの世界じゃなかったのですね……ごくりっ……！）"

[[dialogue]]
speaker = "サーシャ"
# 「そうねぇ～、イクシーちゃん、やってみる？」
line = "「そうねぇ～、イクシーちゃん、やってみる？」"

[[dialogue]]
speaker = "イクシリオン"
# 「わわ、私ですか！？」
line = "「わわ、私ですか！？」"

[[dialogue]]
speaker = "イクシリオン"
# 「私には早いといいますか、心の準備ができていないといいますか……」
line = "「私には早いといいますか、心の準備ができていないといいますか……」"

[[dialogue]]
speaker = "イクシリオン"
# 「きょ、今日のところは失礼いたします～～～～っ！」
line = "「きょ、今日のところは失礼いたします～～～～っ！」"

[[dialogue]]
speaker = "unk"
# 行っちゃった……
line = "行っちゃった……"

[[dialogue]]
speaker = "サーシャ"
# 「お茶を入れるのってそんなに難しくないのよ～……って、遅かったわね～」
line = "「お茶を入れるのってそんなに難しくないのよ～……って、遅かったわね～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あらら。紅茶嫌いだったのかしら？」
line = "「あらら。紅茶嫌いだったのかしら？」"

[[dialogue]]
speaker = "マトイ"
# 「おいしいお茶菓子があったのに……もったいない」
line = "「おいしいお茶菓子があったのに……もったいない」"

[[dialogue]]
speaker = "アナ"
# 「きっと何かご事情があったのでしょう。お菓子いただきます。はむ」
line = "「きっと何かご事情があったのでしょう。お菓子いただきます。はむ」"
