[[dialogue]]
speaker = "unk"
# 第４話,あなたのファンになりたい,P
line = "第４話,あなたのファンになりたい,P"

[[dialogue]]
speaker = "unk"
# 夜、いつものようにエルゼに付き合って地下アイドルのライブに参加した。
line = "夜、いつものようにエルゼに付き合って地下アイドルのライブに参加した。"

[[dialogue]]
speaker = "unk"
# ライブが終わって帰り道、エルゼは興奮冷めやらぬ様子で空を見上げながら熱く語っている。
line = "ライブが終わって帰り道、エルゼは興奮冷めやらぬ様子で空を見上げながら熱く語っている。"

[[dialogue]]
speaker = "エルデリーゼ"
# 「今日は本当に来てよかったですわ！　まさか新メンバーのお披露目があるなんて思いませんでしたわ！」
line = "「今日は本当に来てよかったですわ！　まさか新メンバーのお披露目があるなんて思いませんでしたわ！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「緊張していたのでしょうか、ダンスはまだまだ固い感じでしたけど、一生懸命踊っていて……」
line = "「緊張していたのでしょうか、ダンスはまだまだ固い感じでしたけど、一生懸命踊っていて……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「そんな彼女を先輩たちがフォローしていて、その優しさがもう<ruby=とうと>尊</ruby>過ぎて……」
line = "「そんな彼女を先輩たちがフォローしていて、その優しさがもう<ruby>尊<rt>とうと</rt></ruby>過ぎて……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「私、見ていて胸がキューッってなりましたの！　会長様はいかがでしたか？」
line = "「私、見ていて胸がキューッってなりましたの！　会長様はいかがでしたか？」"

[[dialogue]]
speaker = "unk"
# 頑張ってる子を見ると応援したくなるね
line = "頑張ってる子を見ると応援したくなるね"

[[dialogue]]
speaker = "エルデリーゼ"
# 「そうなんですの！」
line = "「そうなんですの！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「完成されたパフォーマンスはそれはそれでよいものですわ」
line = "「完成されたパフォーマンスはそれはそれでよいものですわ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ですが、新人様が頑張って成長していく様子を見られるのもアイドルの魅力なんですの！」
line = "「ですが、新人様が頑張って成長していく様子を見られるのもアイドルの魅力なんですの！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「特にデビューの瞬間を見守った身としては思い入れも<ruby=ひとしお>一入</ruby>なのですわ！」
line = "「特にデビューの瞬間を見守った身としては思い入れも<ruby>一入<rt>ひとしお</rt></ruby>なのですわ！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「会長様、私、決めましたわ！　あの子のファンになります！」
line = "「会長様、私、決めましたわ！　あの子のファンになります！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「あの子がもっともっと輝けるように、私も頑張ってたくさん応援いたしますわ！！」
line = "「あの子がもっともっと輝けるように、私も頑張ってたくさん応援いたしますわ！！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ん、どうされましたの？　何かに気が付いたようなお顔をして……」
line = "「ん、どうされましたの？　何かに気が付いたようなお顔をして……」"

[[dialogue]]
speaker = "unk"
# 俺はエルゼのファンなのかも
line = "俺はエルゼのファンなのかも"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ふえっ！？　ど、どういうことですの？」
line = "「ふえっ！？　ど、どういうことですの？」"

[[dialogue]]
speaker = "unk"
# エルゼを見ていると応援したくなる
line = "エルゼを見ていると応援したくなる"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ああ、そういうことですのね」
line = "「ああ、そういうことですのね」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「確かに星騎士として私は、まだまだ成長の途中ですわ。つまり新人アイドルのようなものですわ」
line = "「確かに星騎士として私は、まだまだ成長の途中ですわ。つまり新人アイドルのようなものですわ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「でしたら会長様、私のファンになって、私のことを推してくださいます？」
line = "「でしたら会長様、私のファンになって、私のことを推してくださいます？」"

[[dialogue]]
speaker = "unk"
# 星騎士として以外にも頑張ってる
line = "星騎士として以外にも頑張ってる"

[[dialogue]]
speaker = "unk"
# それだけじゃないよ
line = "それだけじゃないよ"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ぁ……そういうことですのね」
line = "「ぁ……そういうことですのね」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「会長様と初めてお会いした時は、今思うと恥ずかしくなるほど世間知らずでしたわ」
line = "「会長様と初めてお会いした時は、今思うと恥ずかしくなるほど世間知らずでしたわ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「けれど会長様にいろいろな経験をさせてもらって、いろいろなことを教えて頂いて、少しずつ成長しておりますの」
line = "「けれど会長様にいろいろな経験をさせてもらって、いろいろなことを教えて頂いて、少しずつ成長しておりますの」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「そんな私のことを全部、会長様は見守ってくださるということですのね？」
line = "「そんな私のことを全部、会長様は見守ってくださるということですのね？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「会長様、ありがとうございます……」
line = "「会長様、ありがとうございます……」"

[[dialogue]]
speaker = "unk"
# エルゼは俺の腕を取り、そっと頭を預けてくる。
line = "エルゼは俺の腕を取り、そっと頭を預けてくる。"

[[dialogue]]
speaker = "エルデリーゼ"
# 「会長様が見守ってくださっていると考えると、とても安心できますわ……」
line = "「会長様が見守ってくださっていると考えると、とても安心できますわ……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「これからも私のこと、宜しくお願いいたします」
line = "「これからも私のこと、宜しくお願いいたします」"

[[dialogue]]
speaker = "unk"
# 俺のこともよろしくね
line = "俺のこともよろしくね"

[[dialogue]]
speaker = "unk"
# 恋愛方面では俺も発展途上だから
line = "恋愛方面では俺も発展途上だから"

[[dialogue]]
speaker = "エルデリーゼ"
# 「まあ……分かりましたわ<emoji=heart04>　会長様のことは私がしっかり応援して、しっかり見守らせて頂きます」
line = "「まあ……分かりましたわ<emoji=heart04>　会長様のことは私がしっかり応援して、しっかり見守らせて頂きます」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ふふっ♪　実は私、恋人同士といってもどうすれば良いのか、よく分かっていなかったところがありましたの」
line = "「ふふっ♪　実は私、恋人同士といってもどうすれば良いのか、よく分かっていなかったところがありましたの」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ですが今、何だかひとつ、恋の仕方について学んだような気がしますわ……」
line = "「ですが今、何だかひとつ、恋の仕方について学んだような気がしますわ……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「送って頂いてありがとうございます。ここまでで大丈夫です」
line = "「送って頂いてありがとうございます。ここまでで大丈夫です」"

[[dialogue]]
speaker = "unk"
# ちゃんと外泊届を取って
line = "ちゃんと外泊届を取って"

[[dialogue]]
speaker = "unk"
# 今度は家に泊まりに来ない？
line = "今度は家に泊まりに来ない？"

[[dialogue]]
speaker = "エルデリーゼ"
# 「お泊り！？　素晴らしいですわ！！」
line = "「お泊り！？　素晴らしいですわ！！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「っ！　いけませんわ……静かに静かに……」
line = "「っ！　いけませんわ……静かに静かに……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「会長様の提案があまりに素晴らしくて、思わず声を上げてしまいましたわ」
line = "「会長様の提案があまりに素晴らしくて、思わず声を上げてしまいましたわ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「私、今までお友達の家にお泊りなどはしたことありませんの」
line = "「私、今までお友達の家にお泊りなどはしたことありませんの」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ですから是非、会長様のお家にご招待して頂きたいですわ」
line = "「ですから是非、会長様のお家にご招待して頂きたいですわ」"

[[dialogue]]
speaker = "unk"
# ぜひ遊びに来てよ
line = "ぜひ遊びに来てよ"

[[dialogue]]
speaker = "エルデリーゼ"
# 「そう致しますわ！」
line = "「そう致しますわ！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「そうと決まりましたら、さっそくお勉強致しませんと！」
line = "「そうと決まりましたら、さっそくお勉強致しませんと！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「お友達のお家にお泊りするときに、どういった準備をしなければならないのか……まったく分かりませんの」
line = "「お友達のお家にお泊りするときに、どういった準備をしなければならないのか……まったく分かりませんの」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「それに外泊のための口実ですわ！　何か自然な理由を考えなければ……うーん……」
line = "「それに外泊のための口実ですわ！　何か自然な理由を考えなければ……うーん……」"

[[dialogue]]
speaker = "unk"
# そんなに難しく考えることは無いのに、と思いつつ。
line = "そんなに難しく考えることは無いのに、と思いつつ。"

[[dialogue]]
speaker = "unk"
# 目を輝かせながらあれこれ考えているエルゼの姿が楽しそうで、しばらくは見守るだけにしようと考える俺だった。
line = "目を輝かせながらあれこれ考えているエルゼの姿が楽しそうで、しばらくは見守るだけにしようと考える俺だった。"
