[[dialogue]]
speaker = "unk"
# 第３話,友達として,P
line = "第３話,友達として,P"

[[dialogue]]
speaker = "unk"
# 流星寮のクリスマスパーティーの準備は順調に進んでいた。
line = "流星寮のクリスマスパーティーの準備は順調に進んでいた。"

[[dialogue]]
speaker = "unk"
# アイデアを出すターンも終わり、個別の作業が増えてきた、そんなある日。
line = "アイデアを出すターンも終わり、個別の作業が増えてきた、そんなある日。"

[[dialogue]]
speaker = "アニュラス"
# 「……ちょっと待て」
line = "「……ちょっと待て」"

[[dialogue]]
speaker = "アポロ"
# 「どうしたんだ？　急に真剣な声して……」
line = "「どうしたんだ？　急に真剣な声して……」"

[[dialogue]]
speaker = "アニュラス"
# 「アポロならわかるだろう？　この場所は流星ライダーが死闘を繰り広げた場所だ！」
line = "「アポロならわかるだろう？　この場所は流星ライダーが死闘を繰り広げた場所だ！」"

[[dialogue]]
speaker = "unk"
# それって第何話？
line = "それって第何話？"

[[dialogue]]
speaker = "unk"
# そうなの？
line = "そうなの？"

[[dialogue]]
speaker = "アポロ"
# 「いや、似てるってだけだぞ。ここじゃないはずだ」
line = "「いや、似てるってだけだぞ。ここじゃないはずだ」"

[[dialogue]]
speaker = "アポロ"
# 「あたしも前に勘違いしたけど、調べてもらったら違うってわかったんだ。アニュラスは流星ライダーを見始めたばっかだし、間違うのも仕方ないぞ」
line = "「あたしも前に勘違いしたけど、調べてもらったら違うってわかったんだ。アニュラスは流星ライダーを見始めたばっかだし、間違うのも仕方ないぞ」"

[[dialogue]]
speaker = "アニュラス"
# 「ぐぬぬ……まだまだ修行が足りないと言うことか……」
line = "「ぐぬぬ……まだまだ修行が足りないと言うことか……」"

[[dialogue]]
speaker = "アポロ"
# 「でもここ、いいよなぁ。戦いたくなっちゃう場所だ」
line = "「でもここ、いいよなぁ。戦いたくなっちゃう場所だ」"

[[dialogue]]
speaker = "アニュラス"
# 「同感だ。学習のために流星ライダーを見せてもらったが、正義のために悪と戦う姿は感動ものだったからな」
line = "「同感だ。学習のために流星ライダーを見せてもらったが、正義のために悪と戦う姿は感動ものだったからな」"

[[dialogue]]
speaker = "アニュラス"
# 「流星剣騎とはまた違った清々しい良さがある！　それは認めざるをえないだろう！」
line = "「流星剣騎とはまた違った清々しい良さがある！　それは認めざるをえないだろう！」"

[[dialogue]]
speaker = "アポロ"
# 「そうだ！　流星ライダーＶＳ流星剣騎ファイバー……ここで、やるか？」
line = "「そうだ！　流星ライダーＶＳ流星剣騎ファイバー……ここで、やるか？」"

[[dialogue]]
speaker = "アニュラス"
# 「いいだろう……私とアポロなら良い戦いが出来るはずだ」
line = "「いいだろう……私とアポロなら良い戦いが出来るはずだ」"

[[dialogue]]
speaker = "unk"
# ここで戦闘するつもりなの！？
line = "ここで戦闘するつもりなの！？"

[[dialogue]]
speaker = "unk"
# ちょっと待った！
line = "ちょっと待った！"

[[dialogue]]
speaker = "アニュラス"
# 「駄目だったか？」
line = "「駄目だったか？」"

[[dialogue]]
speaker = "アポロ"
# 「パーティーの出し物の練習だぞ？　ちょっとだけっ、ちょっとだけだから！」
line = "「パーティーの出し物の練習だぞ？　ちょっとだけっ、ちょっとだけだから！」"

[[dialogue]]
speaker = "アニュラス"
# 「安心してくれ、迷惑になるようなことは決してしない。あくまでデモンストレーションだ」
line = "「安心してくれ、迷惑になるようなことは決してしない。あくまでデモンストレーションだ」"

[[dialogue]]
speaker = "unk"
# ちょっとだけだよ？
line = "ちょっとだけだよ？"

[[dialogue]]
speaker = "unk"
# そこまで言うなら……
line = "そこまで言うなら……"

[[dialogue]]
speaker = "アニュラス"
# 「ありがとう！　では行くぞ、アポロ！」
line = "「ありがとう！　では行くぞ、アポロ！」"

[[dialogue]]
speaker = "アポロ"
# 「変身！」
line = "「変身！」"

[[dialogue]]
speaker = "アポロ"
# 「どうだっ！　これがあたしのクリスマスフォーーームッ！！」
line = "「どうだっ！　これがあたしのクリスマスフォーーームッ！！」"

[[dialogue]]
speaker = "アニュラス"
# 「かっこいいぞ、アポロ。可愛い中にも強さを感じるな」
line = "「かっこいいぞ、アポロ。可愛い中にも強さを感じるな」"

[[dialogue]]
speaker = "アポロ"
# 「えへへっ、ありがとな。アニュラスはちゃんとかっこいいって言ってくれるから好きだ」
line = "「えへへっ、ありがとな。アニュラスはちゃんとかっこいいって言ってくれるから好きだ」"

[[dialogue]]
speaker = "アニュラス"
# 「アポロに可愛さしか感じないなんて、その目は節穴かと言いたいくらいだ。燃える正義の心を強く感じるのに」
line = "「アポロに可愛さしか感じないなんて、その目は節穴かと言いたいくらいだ。燃える正義の心を強く感じるのに」"

[[dialogue]]
speaker = "アポロ"
# 「アニュラスはわかってるな。流星ライダーのことも、すぐ好きになってくれたし」
line = "「アニュラスはわかってるな。流星ライダーのことも、すぐ好きになってくれたし」"

[[dialogue]]
speaker = "アニュラス"
# 「歩む道は異なれど、目指すものは同じだからな」
line = "「歩む道は異なれど、目指すものは同じだからな」"

[[dialogue]]
speaker = "アポロ"
# 「おうっ！　アニュラスと仲良くなれて、ほんとよかったぜ！」
line = "「おうっ！　アニュラスと仲良くなれて、ほんとよかったぜ！」"

[[dialogue]]
speaker = "unk"
# 人が集まって来ちゃったみたいだ
line = "人が集まって来ちゃったみたいだ"

[[dialogue]]
speaker = "unk"
# 仲良くしてるとこ申し訳ないけど
line = "仲良くしてるとこ申し訳ないけど"

[[dialogue]]
speaker = "アポロ"
# 「うわ、ほんとだ！　どうしたらいいんだ？」
line = "「うわ、ほんとだ！　どうしたらいいんだ？」"

[[dialogue]]
speaker = "アニュラス"
# 「善良な市民に迷惑をかけるわけにはいかない。模擬戦闘は断念しよう」
line = "「善良な市民に迷惑をかけるわけにはいかない。模擬戦闘は断念しよう」"

[[dialogue]]
speaker = "アポロ"
# 「じゃあ次の機会だな！」
line = "「じゃあ次の機会だな！」"

[[dialogue]]
speaker = "アニュラス"
# 「クリスマスパーティーまでに、練習する機会は何度もあるだろう」
line = "「クリスマスパーティーまでに、練習する機会は何度もあるだろう」"

[[dialogue]]
speaker = "アポロ"
# 「おう！　でもアニュラスがすぐに諦めたのはちょっと意外だったぞ」
line = "「おう！　でもアニュラスがすぐに諦めたのはちょっと意外だったぞ」"

[[dialogue]]
speaker = "アニュラス"
# 「意外とはなんだ、失礼な。私だってちゃんと考えているんだ」
line = "「意外とはなんだ、失礼な。私だってちゃんと考えているんだ」"

[[dialogue]]
speaker = "アニュラス"
# 「まだまだ試行錯誤の途中だが、『流星の騎士』として私はもっと成長したい。上手くいかないこともあるが、しかし最終的には前に進んでいたいんだ」
line = "「まだまだ試行錯誤の途中だが、『流星の騎士』として私はもっと成長したい。上手くいかないこともあるが、しかし最終的には前に進んでいたいんだ」"

[[dialogue]]
speaker = "アポロ"
# 「悩むのはいいことだと思うぞ。流星ライダーだって、時には悩み、苦しみ、成長してきたんだ」
line = "「悩むのはいいことだと思うぞ。流星ライダーだって、時には悩み、苦しみ、成長してきたんだ」"

[[dialogue]]
speaker = "アポロ"
# 「ヒーローには必要なことだ。アニュラスも流星の騎士を目指すんなら、大いに悩んでいいぞ！」
line = "「ヒーローには必要なことだ。アニュラスも流星の騎士を目指すんなら、大いに悩んでいいぞ！」"

[[dialogue]]
speaker = "アニュラス"
# 「そうだな。迷惑をかけることもあるだろうが、よろしく頼む」
line = "「そうだな。迷惑をかけることもあるだろうが、よろしく頼む」"

[[dialogue]]
speaker = "アポロ"
# 「へへっ、ようやく調子が戻ってきたな。ちょっと堅苦しいけど、アニュラスらしくていいぞ」
line = "「へへっ、ようやく調子が戻ってきたな。ちょっと堅苦しいけど、アニュラスらしくていいぞ」"

[[dialogue]]
speaker = "unk"
# それもアニュラスの長所だから
line = "それもアニュラスの長所だから"

[[dialogue]]
speaker = "unk"
# 自分らしさは大事だよ
line = "自分らしさは大事だよ"

[[dialogue]]
speaker = "アニュラス"
# 「流星の騎士として、自分の正義を<ruby=ま>枉</ruby>げるつもりはない。私は私らしく、更なる成長を目指そう！」
line = "「流星の騎士として、自分の正義を<ruby>枉<rt>ま</rt></ruby>げるつもりはない。私は私らしく、更なる成長を目指そう！」"

[[dialogue]]
speaker = "アポロ"
# 「いいと思うぞ！　もし間違ってたら、あたしが教えてやるから」
line = "「いいと思うぞ！　もし間違ってたら、あたしが教えてやるから」"

[[dialogue]]
speaker = "アポロ"
# 「アニュラスの友達として、なっ！」
line = "「アニュラスの友達として、なっ！」"

[[dialogue]]
speaker = "アニュラス"
# 「ああ、頼むぞ！」
line = "「ああ、頼むぞ！」"

[[dialogue]]
speaker = "unk"
# がっちりと握手するアニュラスとアポロ。
line = "がっちりと握手するアニュラスとアポロ。"

[[dialogue]]
speaker = "unk"
# まるで少年漫画の１シーンのように、２人の笑顔は清々しいものだった。
line = "まるで少年漫画の１シーンのように、２人の笑顔は清々しいものだった。"
