[[dialogue]]
speaker = "unk"
# 第２話,付き合ってることは絶対ナイショ,P
line = "第２話,付き合ってることは絶対ナイショ,P"

[[dialogue]]
speaker = "unk"
# 晴れて恋人関係になった俺とレミカ。しかし彼女はワールドクラスのアイドルなので、当然恋愛沙汰は御法度だ。
line = "晴れて恋人関係になった俺とレミカ。しかし彼女はワールドクラスのアイドルなので、当然恋愛沙汰は御法度だ。"

[[dialogue]]
speaker = "レミカ"
# 「会長。言うまでもないけど、私と会長が付き合ってることは内緒だよ」
line = "「会長。言うまでもないけど、私と会長が付き合ってることは内緒だよ」"

[[dialogue]]
speaker = "unk"
# 仲のいい友達に教えるのもダメだよね
line = "仲のいい友達に教えるのもダメだよね"

[[dialogue]]
speaker = "レミカ"
# 「もちろん。そういう気の緩み、小さな穴がダムを決壊させるんだから。気を引き締めて行こう」
line = "「もちろん。そういう気の緩み、小さな穴がダムを決壊させるんだから。気を引き締めて行こう」"

[[dialogue]]
speaker = "レミカ"
# 「あ、もちろん偶然会った時にまで、よそよそしかったら逆に不自然だから。あんまり神経質になるのもよくないよ？」
line = "「あ、もちろん偶然会った時にまで、よそよそしかったら逆に不自然だから。あんまり神経質になるのもよくないよ？」"

[[dialogue]]
speaker = "レミカ"
# 「そう。人の目がある時は、同じ学園に通う生徒同士、違和感のない範囲で接するってことで。ＯＫかな？」
line = "「そう。人の目がある時は、同じ学園に通う生徒同士、違和感のない範囲で接するってことで。ＯＫかな？」"

[[dialogue]]
speaker = "unk"
# レミカの言うことは至極もっともなので、俺も気を付けようと肝に銘じた──のだが。
line = "レミカの言うことは至極もっともなので、俺も気を付けようと肝に銘じた──のだが。"

[[dialogue]]
speaker = "unk"
# それでは、ここ数日のレミカさんを見ていただこう。まずは朝の時間帯。
line = "それでは、ここ数日のレミカさんを見ていただこう。まずは朝の時間帯。"

[[dialogue]]
speaker = "マトイ"
# 「あっ、会長おはよう。偶然だね、一緒に登校しよっか」
line = "「あっ、会長おはよう。偶然だね、一緒に登校しよっか」"

[[dialogue]]
speaker = "マトイ"
# 「朝は大変だよねー。寮で暮らしてる子はぎりぎりまで寝てられるから羨ましいなー」
line = "「朝は大変だよねー。寮で暮らしてる子はぎりぎりまで寝てられるから羨ましいなー」"

[[dialogue]]
speaker = "マトイ"
# 「あれ、なんだか校門前が騒がしいね……？」
line = "「あれ、なんだか校門前が騒がしいね……？」"

[[dialogue]]
speaker = "マトイ"
# 「あ、愛戸さんが立ってる。そりゃあ騒がれるわけだね。流石はアイドル」
line = "「あ、愛戸さんが立ってる。そりゃあ騒がれるわけだね。流石はアイドル」"

[[dialogue]]
speaker = "unk"
# （俺を待ってる──！？）
line = "（俺を待ってる──！？）"

[[dialogue]]
speaker = "レミカ"
# 「──会長、おはよ。偶然だね」
line = "「──会長、おはよ。偶然だね」"

[[dialogue]]
speaker = "マトイ"
# 「偶然……！？」
line = "「偶然……！？」"

[[dialogue]]
speaker = "レミカ"
# 「<ruby=よみの>詠野</ruby>さんもおはよ。一緒に教室行こっか」
line = "「<ruby>詠野<rt>よみの</rt></ruby>さんもおはよ。一緒に教室行こっか」"

[[dialogue]]
speaker = "マトイ"
# 「う、うん……そうだね……？」
line = "「う、うん……そうだね……？」"

[[dialogue]]
speaker = "マトイ"
# （あ、あれ～？　愛戸さんって<ruby=ラルーナ>新星寮</ruby>に住んでるよね。なんでわざわざ校門のところで立って、会長を待ってたんだろ……？）
line = "（あ、あれ～？　愛戸さんって<ruby>新星寮<rt>ラルーナ</rt></ruby>に住んでるよね。なんでわざわざ校門のところで立って、会長を待ってたんだろ……？）"

[[dialogue]]
speaker = "unk"
# ──また、ある日の休み時間。
line = "──また、ある日の休み時間。"

[[dialogue]]
speaker = "マトイ"
# 「でね。その時にヴィーナスが……」
line = "「でね。その時にヴィーナスが……」"

[[dialogue]]
speaker = "レミカ"
# 「失礼します」
line = "「失礼します」"

[[dialogue]]
speaker = "マトイ"
# 「愛戸さん？　どうかしたの」
line = "「愛戸さん？　どうかしたの」"

[[dialogue]]
speaker = "レミカ"
# 「うん。会長に用事があってさ……ごめん、教科書を忘れちゃったんだけど貸してくれる？　……ありがと、助かるよ」
line = "「うん。会長に用事があってさ……ごめん、教科書を忘れちゃったんだけど貸してくれる？　……ありがと、助かるよ」"

[[dialogue]]
speaker = "レミカ"
# 「あ……寝癖ついてる。ふふ♪　教科書、借りるお返しに直してあげるよ。動かないでね」
line = "「あ……寝癖ついてる。ふふ♪　教科書、借りるお返しに直してあげるよ。動かないでね」"

[[dialogue]]
speaker = "unk"
# （レミカ……距離が近いよ……！）
line = "（レミカ……距離が近いよ……！）"

[[dialogue]]
speaker = "マトイ"
# （また愛戸さん……最近、教室によく来るなあ……？　ていうか教科書、どうして隣の席の子に見せてもらわないんだろ？）
line = "（また愛戸さん……最近、教室によく来るなあ……？　ていうか教科書、どうして隣の席の子に見せてもらわないんだろ？）"

[[dialogue]]
speaker = "unk"
# ──また、ある日の昼休み。
line = "──また、ある日の昼休み。"

[[dialogue]]
speaker = "マトイ"
# 「カフェのご飯って定期的に更新されるから飽きなくていいよね。ん～、おいしい。午後の授業も頑張れそう！」
line = "「カフェのご飯って定期的に更新されるから飽きなくていいよね。ん～、おいしい。午後の授業も頑張れそう！」"

[[dialogue]]
speaker = "レミカ"
# 「会長、それに詠野さんも。私もここで一緒に食べていい？」
line = "「会長、それに詠野さんも。私もここで一緒に食べていい？」"

[[dialogue]]
speaker = "マトイ"
# 「あっ、う、うん……！　もちろんいいよ。でも愛戸さん、まだ何も買ってないみたいだけど……？」
line = "「あっ、う、うん……！　もちろんいいよ。でも愛戸さん、まだ何も買ってないみたいだけど……？」"

[[dialogue]]
speaker = "レミカ"
# 「会長が何食べるのかなって気になって──うん、それだね。じゃあ私も同じやつにしよっと。それじゃ、すぐ戻ってくるから」
line = "「会長が何食べるのかなって気になって──うん、それだね。じゃあ私も同じやつにしよっと。それじゃ、すぐ戻ってくるから」"

[[dialogue]]
speaker = "マトイ"
# 「……あやしい。最近、会長と愛戸さん、距離がすご～く近いような……！　まさか……！？」
line = "「……あやしい。最近、会長と愛戸さん、距離がすご～く近いような……！　まさか……！？」"

[[dialogue]]
speaker = "unk"
# （バレるに決まってる……こんなの……！）
line = "（バレるに決まってる……こんなの……！）"

[[dialogue]]
speaker = "unk"
# ──と、こんなことがあり。とうとう放課後、俺とレミカはマトイに呼び出されて……
line = "──と、こんなことがあり。とうとう放課後、俺とレミカはマトイに呼び出されて……"

[[dialogue]]
speaker = "マトイ"
# 「２人に聞きたいことがあります！　単刀直入に聞くけど、お付き合いしてるよね！？　もうネタは上がってるんだよ！」
line = "「２人に聞きたいことがあります！　単刀直入に聞くけど、お付き合いしてるよね！？　もうネタは上がってるんだよ！」"

[[dialogue]]
speaker = "レミカ"
# 「え、そ、そんなことないよ。私と会長は、ただの友人で……」
line = "「え、そ、そんなことないよ。私と会長は、ただの友人で……」"

[[dialogue]]
speaker = "マトイ"
# 「普通の男女の友人は、毎朝校門で偶然出会ったり、休み時間のたびに会いに来たりしません！　寝癖も直したりしません！」
line = "「普通の男女の友人は、毎朝校門で偶然出会ったり、休み時間のたびに会いに来たりしません！　寝癖も直したりしません！」"

[[dialogue]]
speaker = "レミカ"
# 「──ぅ」
line = "「──ぅ」"

[[dialogue]]
speaker = "マトイ"
# 「お付き合いするのはいいと思うけど！　もうちょっと隠した方がいいよ！」
line = "「お付き合いするのはいいと思うけど！　もうちょっと隠した方がいいよ！」"

[[dialogue]]
speaker = "マトイ"
# 「ていうか、どうしてそんな攻めた行動を取っちゃうの？　クールな愛戸さんらしくもない……」
line = "「ていうか、どうしてそんな攻めた行動を取っちゃうの？　クールな愛戸さんらしくもない……」"

[[dialogue]]
speaker = "レミカ"
# 「……頭ではわかってるんだけど。自分で思った以上に舞い上がってるのかな……時間ができると、会長に会いたくなっちゃって……」
line = "「……頭ではわかってるんだけど。自分で思った以上に舞い上がってるのかな……時間ができると、会長に会いたくなっちゃって……」"

[[dialogue]]
speaker = "レミカ"
# 「クラス違うし、私は寮暮らしだから登下校も一緒にできないし。夜は仕事で連絡取れない時間も多いから、日中は反動が来ちゃって……」
line = "「クラス違うし、私は寮暮らしだから登下校も一緒にできないし。夜は仕事で連絡取れない時間も多いから、日中は反動が来ちゃって……」"

[[dialogue]]
speaker = "レミカ"
# 「で、でもほら。会長はよくプロデュース業で私と一緒にいるよね。だったら、あれぐらいの距離感でも違和感、そんなにないんじゃないかな……？」
line = "「で、でもほら。会長はよくプロデュース業で私と一緒にいるよね。だったら、あれぐらいの距離感でも違和感、そんなにないんじゃないかな……？」"

[[dialogue]]
speaker = "レミカ"
# 「今回の件だって、詠野さんの勘が鋭かっただけ、とか……」
line = "「今回の件だって、詠野さんの勘が鋭かっただけ、とか……」"

[[dialogue]]
speaker = "マトイ"
# 「バリバリに違和感があるよ！？　付き合いたてのカップルにしか見えないって！　今はまだそこまで目立ってないから、今のうちに矯正しなきゃ……！」
line = "「バリバリに違和感があるよ！？　付き合いたてのカップルにしか見えないって！　今はまだそこまで目立ってないから、今のうちに矯正しなきゃ……！」"

[[dialogue]]
speaker = "レミカ"
# 「お、ＯＫ。ここから巻き返す。会長──お互い頑張ろっか」
line = "「お、ＯＫ。ここから巻き返す。会長──お互い頑張ろっか」"

[[dialogue]]
speaker = "unk"
# 頑張るのはレミカだよ！？
line = "頑張るのはレミカだよ！？"

[[dialogue]]
speaker = "マトイ"
# 「ダメだよ会長！　今回のはほぼ１００％、愛戸さんの落ち度だけど！　恋人同士なんだから責任は<ruby=フィフティーフィフティー>５０％５０％</ruby>だよ！！」
line = "「ダメだよ会長！　今回のはほぼ１００％、愛戸さんの落ち度だけど！　恋人同士なんだから責任は<ruby>５０％５０％<rt>フィフティーフィフティー</rt></ruby>だよ！！」"

[[dialogue]]
speaker = "unk"
# は、はい……！
line = "は、はい……！"

[[dialogue]]
speaker = "マトイ"
# 「愛戸さんも！　会うにしてももう少し違和感のないように！　とりあえず毎時間、教室に来るのは我慢しようね！」
line = "「愛戸さんも！　会うにしてももう少し違和感のないように！　とりあえず毎時間、教室に来るのは我慢しようね！」"

[[dialogue]]
speaker = "レミカ"
# 「はい……」
line = "「はい……」"

[[dialogue]]
speaker = "マトイ"
# 「せっかくお付き合いしてるんだから、くだらないゴシップで台無しになったらいやでしょ？」
line = "「せっかくお付き合いしてるんだから、くだらないゴシップで台無しになったらいやでしょ？」"

[[dialogue]]
speaker = "レミカ"
# 「うん……」
line = "「うん……」"

[[dialogue]]
speaker = "マトイ"
# 「頑張って隠しながらお付き合いしようね！」
line = "「頑張って隠しながらお付き合いしようね！」"

[[dialogue]]
speaker = "レミカ"
# 「詠野さん、なんだかお母さんみたい……愛のあるお説教って感じ……」
line = "「詠野さん、なんだかお母さんみたい……愛のあるお説教って感じ……」"

[[dialogue]]
speaker = "unk"
# はい……マトイママ……！
line = "はい……マトイママ……！"

[[dialogue]]
speaker = "マトイ"
# 「茶化さないの！」
line = "「茶化さないの！」"

[[dialogue]]
speaker = "unk"
# 守護天使のセシアが、マトイをママ判定する気持ちが少しだけわかった俺たちなのだった。
line = "守護天使のセシアが、マトイをママ判定する気持ちが少しだけわかった俺たちなのだった。"

[[dialogue]]
speaker = "unk"
# なお、マトイのお説教が効いたのか。その後のレミカは実に自然に友人関係の距離を装えるようになるのだった……
line = "なお、マトイのお説教が効いたのか。その後のレミカは実に自然に友人関係の距離を装えるようになるのだった……"

[[dialogue]]
speaker = "unk"
# ──いや、できるなら最初からやってよ！？
line = "──いや、できるなら最初からやってよ！？"
