[[dialogue]]
speaker = "unk"
# 第４話,呪われた司書さん,P
line = "第４話,呪われた司書さん,P"

[[dialogue]]
speaker = "unk"
# ウィステリアさんとキリカさんという頼もしすぎる援軍を得て、俺たちはアステラの深部へと向かう――
line = "ウィステリアさんとキリカさんという頼もしすぎる援軍を得て、俺たちはアステラの深部へと向かう――"

[[dialogue]]
speaker = "ウィステリア"
# 「くっ……！」
line = "「くっ……！」"

[[dialogue]]
speaker = "ウィステリア"
# 「あ、大丈夫。モンスターにやられたわけじゃないわよ。この魔導書呪われててね、強い力を与える代わりに持ち主の精神を蝕むの」
line = "「あ、大丈夫。モンスターにやられたわけじゃないわよ。この魔導書呪われててね、強い力を与える代わりに持ち主の精神を蝕むの」"

[[dialogue]]
speaker = "unk"
# 大丈夫じゃない！？
line = "大丈夫じゃない！？"

[[dialogue]]
speaker = "ウィステリア"
# 「普通の人なら手にしただけで死ぬか発狂するらしいけど、気を抜かなければ大丈夫よ。普段はしっかり封印してるしね」
line = "「普通の人なら手にしただけで死ぬか発狂するらしいけど、気を抜かなければ大丈夫よ。普段はしっかり封印してるしね」"

[[dialogue]]
speaker = "キリカ"
# 「その危険物、まだ処理していなかったのですね」
line = "「その危険物、まだ処理していなかったのですね」"

[[dialogue]]
speaker = "ウィステリア"
# 「そんな簡単に手放せるなら苦労しないわよ。新星の図書館の本に解呪する方法とかないかしら？」
line = "「そんな簡単に手放せるなら苦労しないわよ。新星の図書館の本に解呪する方法とかないかしら？」"

[[dialogue]]
speaker = "ウィステリア"
# 「こんな危ないものどこで……って思ったでしょ。それが実家に最初からあったのよこれが」
line = "「こんな危ないものどこで……って思ったでしょ。それが実家に最初からあったのよこれが」"

[[dialogue]]
speaker = "ウィステリア"
# 「私の家は魔界でも特別古い一族でね。次期当主として生まれた私は小さい頃から呪術の教育を受けていた」
line = "「私の家は魔界でも特別古い一族でね。次期当主として生まれた私は小さい頃から呪術の教育を受けていた」"

[[dialogue]]
speaker = "ウィステリア"
# 「動物を呪い殺させたり、大量の呪術書を読まされたり、耐性を付けるために呪われたり……極めつけにこの魔導書を与えられた。最初は何度も死にかけたわ」
line = "「動物を呪い殺させたり、大量の呪術書を読まされたり、耐性を付けるために呪われたり……極めつけにこの魔導書を与えられた。最初は何度も死にかけたわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「で、そんなヤバいものを押し付けてくる家が嫌になって、こっそり抜け出して流星学園に入ったってわけ」
line = "「で、そんなヤバいものを押し付けてくる家が嫌になって、こっそり抜け出して流星学園に入ったってわけ」"

[[dialogue]]
speaker = "unk"
# だからメイドのバイトを……
line = "だからメイドのバイトを……"

[[dialogue]]
speaker = "ウィステリア"
# 「うぐっ……そうなのよ。人間界に頼れる人はいないし、お金欲しさに泣く泣くね……」
line = "「うぐっ……そうなのよ。人間界に頼れる人はいないし、お金欲しさに泣く泣くね……」"

[[dialogue]]
speaker = "キリカ"
# 「失礼ですね。ちょっとメイド服着てみたい、と言ったのはあなたでしょう」
line = "「失礼ですね。ちょっとメイド服着てみたい、と言ったのはあなたでしょう」"

[[dialogue]]
speaker = "ウィステリア"
# 「あいや、それは若気の至りっていうか、女の子なんだからフリフリしたのも一度着てみたいっていうか――」
line = "「あいや、それは若気の至りっていうか、女の子なんだからフリフリしたのも一度着てみたいっていうか――」"

[[dialogue]]
speaker = "キリカ"
# 「どうやらここがアステラの奥のようですね」
line = "「どうやらここがアステラの奥のようですね」"

[[dialogue]]
speaker = "ウィステリア"
# 「よしっ、モンスターのくせにファインプレーよ！　お礼に跡形もなく消し飛ばしてあげる！」
line = "「よしっ、モンスターのくせにファインプレーよ！　お礼に跡形もなく消し飛ばしてあげる！」"

[[dialogue]]
speaker = "ウィステリア"
# 「術式凍結解除――フォビドゥンリアクター！！」
line = "「術式凍結解除――フォビドゥンリアクター！！」"

[[dialogue]]
speaker = "ウィステリア"
# 「はい、お終い。じゃ、アステラが崩壊する前に脱出しましょ」
line = "「はい、お終い。じゃ、アステラが崩壊する前に脱出しましょ」"

[[dialogue]]
speaker = "unk"
# 一瞬でモンスターが全滅した……！
line = "一瞬でモンスターが全滅した……！"

[[dialogue]]
speaker = "キリカ"
# 「驚いておられるようですが、ウィステリアの全力はこの程度ではありませんよ。学生時代は――」
line = "「驚いておられるようですが、ウィステリアの全力はこの程度ではありませんよ。学生時代は――」"

[[dialogue]]
speaker = "ウィステリア"
# 「コラそこ、何いらないこと教えようとしてんの」
line = "「コラそこ、何いらないこと教えようとしてんの」"

[[dialogue]]
speaker = "ウィステリア"
# 「私のこと、ただの司書さんだと思ってたかしら？　でもあんまり他の子には言っちゃダメよ」
line = "「私のこと、ただの司書さんだと思ってたかしら？　でもあんまり他の子には言っちゃダメよ」"

[[dialogue]]
speaker = "ウィステリア"
# 「お姉さんとのヒミツ。いい？」
line = "「お姉さんとのヒミツ。いい？」"

[[dialogue]]
speaker = "ウィステリア"
# 「……うん、いい子ね。お姉さんとの約束よ」
line = "「……うん、いい子ね。お姉さんとの約束よ」"

[[dialogue]]
speaker = "ウィステリア"
# 「あっ」
line = "「あっ」"

[[dialogue]]
speaker = "ウィステリア"
# 「あたた、私たちだけ変なところに出ちゃったわね……また不運だわ……」
line = "「あたた、私たちだけ変なところに出ちゃったわね……また不運だわ……」"

[[dialogue]]
speaker = "ウィステリア"
# 「……私のこと、やたら運の悪いお姉さんだと思ってない？　あ、その顔は思ってるでしょ」
line = "「……私のこと、やたら運の悪いお姉さんだと思ってない？　あ、その顔は思ってるでしょ」"

[[dialogue]]
speaker = "ウィステリア"
# 「実はね、この魔本は持ち主の魂を喰らうだけじゃなくて幸運も奪うの」
line = "「実はね、この魔本は持ち主の魂を喰らうだけじゃなくて幸運も奪うの」"

[[dialogue]]
speaker = "ウィステリア"
# 「新品の家電が壊れたり、財布を落としたり、赤信号に全部引っかかったり……ほんとイヤになっちゃう」
line = "「新品の家電が壊れたり、財布を落としたり、赤信号に全部引っかかったり……ほんとイヤになっちゃう」"

[[dialogue]]
speaker = "ウィステリア"
# 「――だって就職した会社が一ヶ月経たずに潰れたんだから！」
line = "「――だって就職した会社が一ヶ月経たずに潰れたんだから！」"

[[dialogue]]
speaker = "unk"
# えええっ！？
line = "えええっ！？"

[[dialogue]]
speaker = "ウィステリア"
# 「普通の会社に就職して、普通の人として生きていくつもりだったのに、同僚の顔を覚える暇すらなく無職よ！」
line = "「普通の会社に就職して、普通の人として生きていくつもりだったのに、同僚の顔を覚える暇すらなく無職よ！」"

[[dialogue]]
speaker = "ウィステリア"
# 「再就職もうまくいかなくて……でもちょうど新星学園の司書さんが１人やめたそうで、行き場をなくしてる私に声をかけてくれたの。おかげで助かったわ」
line = "「再就職もうまくいかなくて……でもちょうど新星学園の司書さんが１人やめたそうで、行き場をなくしてる私に声をかけてくれたの。おかげで助かったわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「はぁ～……今日はモンスターとキリカのせいで余計なことたくさん知られちゃったわ。あの鬼メイド長め……ケーキを作る腕前だけは認めてあげるけど」
line = "「はぁ～……今日はモンスターとキリカのせいで余計なことたくさん知られちゃったわ。あの鬼メイド長め……ケーキを作る腕前だけは認めてあげるけど」"

[[dialogue]]
speaker = "ウィステリア"
# 「あ、言っとくけど私のせいで会社が潰れたわけじゃないから。後で聞いたら元から経営状態悪かったらしいし」
line = "「あ、言っとくけど私のせいで会社が潰れたわけじゃないから。後で聞いたら元から経営状態悪かったらしいし」"

[[dialogue]]
speaker = "ウィステリア"
# 「あ――」
line = "「あ――」"

[[dialogue]]
speaker = "ウィステリア"
# 「あんなに戦ったの久々だから、呪いの反動で力抜けちゃって……ありがとう、また受け止めてもらっちゃったわね」
line = "「あんなに戦ったの久々だから、呪いの反動で力抜けちゃって……ありがとう、また受け止めてもらっちゃったわね」"

[[dialogue]]
speaker = "ウィステリア"
# 「…………その、ね。呪いのせいで失ったもの、まだあるの」
line = "「…………その、ね。呪いのせいで失ったもの、まだあるの」"

[[dialogue]]
speaker = "ウィステリア"
# 「それは……恋」
line = "「それは……恋」"

[[dialogue]]
speaker = "ウィステリア"
# 「魔窟みたいな家を出て、学園で青春を楽しんで、そして恋をしたかった」
line = "「魔窟みたいな家を出て、学園で青春を楽しんで、そして恋をしたかった」"

[[dialogue]]
speaker = "ウィステリア"
# 「でも必ず邪魔が入ってうまいくかない」
line = "「でも必ず邪魔が入ってうまいくかない」"

[[dialogue]]
speaker = "ウィステリア"
# 「強くなりたくなんてなかった。普通の女の子になって、普通の恋ができればそれで幸せだったのに」
line = "「強くなりたくなんてなかった。普通の女の子になって、普通の恋ができればそれで幸せだったのに」"

[[dialogue]]
speaker = "ウィステリア"
# 「ふぅ……もう立ち上がれるわ。ごめんなさい、恥ずかしいところ見せたわね」
line = "「ふぅ……もう立ち上がれるわ。ごめんなさい、恥ずかしいところ見せたわね」"

[[dialogue]]
speaker = "ウィステリア"
# 「だけど会長くんは特別みたいで、不思議と近づける。私ね、男の子とこんなにお話できたのは初めてなの」
line = "「だけど会長くんは特別みたいで、不思議と近づける。私ね、男の子とこんなにお話できたのは初めてなの」"

[[dialogue]]
speaker = "ウィステリア"
# 「だから……」
line = "「だから……」"

[[dialogue]]
speaker = "ウィステリア"
# 「こんないわくつきの女だけど、恋の相手になってくれる？」
line = "「こんないわくつきの女だけど、恋の相手になってくれる？」"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "ウィステリア"
# 「ふふふっ、さすがにここまで言ったら動揺するのね。ちょっと勝った気分。でも会長くんにはお姉さんの相手はまだ早いかなぁ～？」
line = "「ふふふっ、さすがにここまで言ったら動揺するのね。ちょっと勝った気分。でも会長くんにはお姉さんの相手はまだ早いかなぁ～？」"

[[dialogue]]
speaker = "ウィステリア"
# 「あっ、冗談冗談！？　ごめんなさい調子乗りました！　謝るから今の許して！」
line = "「あっ、冗談冗談！？　ごめんなさい調子乗りました！　謝るから今の許して！」"

[[dialogue]]
speaker = "ウィステリア"
# 「まぁ、その……さっき言ったことは忘れていいから、また図書館に来てね。お姉さん、君が相手してくれるだけで嬉しいから」
line = "「まぁ、その……さっき言ったことは忘れていいから、また図書館に来てね。お姉さん、君が相手してくれるだけで嬉しいから」"

[[dialogue]]
speaker = "ウィステリア"
# 「それじゃ……おやすみなさい」
line = "「それじゃ……おやすみなさい」"
