[[dialogue]]
speaker = "unk"
# 第１話,ぐーたらユニゾン,P
line = "第１話,ぐーたらユニゾン,P"

[[dialogue]]
speaker = "unk"
# 赤ちゃんクマロボの騒動は無事に落ち着いた──しかし黒ベア子曰く、他の世界での事件はまだ解決していないらしい。
line = "赤ちゃんクマロボの騒動は無事に落ち着いた──しかし黒ベア子曰く、他の世界での事件はまだ解決していないらしい。"

[[dialogue]]
speaker = "unk"
# そのためフィオナたちが戻ってくるまでの間、ステラとラファエロには、俺たちの世界にいてもらうことになるのだが……
line = "そのためフィオナたちが戻ってくるまでの間、ステラとラファエロには、俺たちの世界にいてもらうことになるのだが……"

[[dialogue]]
speaker = "ルリエル"
# 「ステラさんやラファエロさんの生活の、フォローをお願いしたい……ですか？」
line = "「ステラさんやラファエロさんの生活の、フォローをお願いしたい……ですか？」"

[[dialogue]]
speaker = "unk"
# お別れの日まで、おもてなしをしてあげたい
line = "お別れの日まで、おもてなしをしてあげたい"

[[dialogue]]
speaker = "ルリエル"
# 「なるほどです！　ルリエルもお２人には、流星市国のことを大好きになってから帰ってもらいたいです～！」
line = "「なるほどです！　ルリエルもお２人には、流星市国のことを大好きになってから帰ってもらいたいです～！」"

[[dialogue]]
speaker = "ルリエル"
# 「今は留守のフィオナ会長も、ここにいたらきっと会長さんとおんなじことを言ってたと思います♪　──となれば！」
line = "「今は留守のフィオナ会長も、ここにいたらきっと会長さんとおんなじことを言ってたと思います♪　──となれば！」"

[[dialogue]]
speaker = "ルリエル"
# 「流星星徒会の役員として、ルリエルも一肌脱いじゃうのです！」
line = "「流星星徒会の役員として、ルリエルも一肌脱いじゃうのです！」"

[[dialogue]]
speaker = "セーラ"
# 「お～っと。ルリちーったらお着替えまでしちゃって。張り切ってるね～♪」
line = "「お～っと。ルリちーったらお着替えまでしちゃって。張り切ってるね～♪」"

[[dialogue]]
speaker = "ソフィア"
# 「それが噂の、異世界の騎士さんの戦闘服ですか。人工戦闘服とはまた違った雰囲気の、洗練された星力が感じられますね」
line = "「それが噂の、異世界の騎士さんの戦闘服ですか。人工戦闘服とはまた違った雰囲気の、洗練された星力が感じられますね」"

[[dialogue]]
speaker = "ルリエル"
# 「ふっふっふ～♪　そうでしょう、そうでしょう！」
line = "「ふっふっふ～♪　そうでしょう、そうでしょう！」"

[[dialogue]]
speaker = "ソフィア"
# 「……ルリってドジばかりしてるイメージですけど、やっぱり優秀なんですね。新しい戦闘服もすぐ操れるようになるだなんて」
line = "「……ルリってドジばかりしてるイメージですけど、やっぱり優秀なんですね。新しい戦闘服もすぐ操れるようになるだなんて」"

[[dialogue]]
speaker = "ルリエル"
# 「そうでしょう、そうでしょう──ってぇ！？　なんだか聞き捨てならない言葉がありましたぁ！？」
line = "「そうでしょう、そうでしょう──ってぇ！？　なんだか聞き捨てならない言葉がありましたぁ！？」"

[[dialogue]]
speaker = "ユウリ"
# 「ま、並の星騎士だったら星徒会役員には選ばれないからな。いいかルリ。異世界からのお客さんに、失礼のないようにしろよ？」
line = "「ま、並の星騎士だったら星徒会役員には選ばれないからな。いいかルリ。異世界からのお客さんに、失礼のないようにしろよ？」"

[[dialogue]]
speaker = "ルリエル"
# 「もちろんです！　ステラさんたちのキラキラな生活のために、ルリエル頑張っちゃうのです～！」
line = "「もちろんです！　ステラさんたちのキラキラな生活のために、ルリエル頑張っちゃうのです～！」"

[[dialogue]]
speaker = "unk"
# そうしてルリエルに、快く協力を了承してもらえた翌日──
line = "そうしてルリエルに、快く協力を了承してもらえた翌日──"

[[dialogue]]
speaker = "unk"
# どういうわけか……新星学園の星徒会室の隅っこに、アウトドアで使う立派なテントが鎮座していた。
line = "どういうわけか……新星学園の星徒会室の隅っこに、アウトドアで使う立派なテントが鎮座していた。"

[[dialogue]]
speaker = "unk"
# ……何事！？
line = "……何事！？"

[[dialogue]]
speaker = "ルリエル"
# 「あっ、会長さん！　おはようなのです～♪」
line = "「あっ、会長さん！　おはようなのです～♪」"

[[dialogue]]
speaker = "ルリエル"
# 「じゃーん！　見てください、さっそくステラさんをおもてなししてるんですよ～！」
line = "「じゃーん！　見てください、さっそくステラさんをおもてなししてるんですよ～！」"

[[dialogue]]
speaker = "unk"
# いったい何がどうしてこうなった！？
line = "いったい何がどうしてこうなった！？"

[[dialogue]]
speaker = "ステラ"
# 「んしょ……こ、こんにちは……会長さん。ありがとうございます、ボクのためにこんな素敵なテントを用意していただいて……」
line = "「んしょ……こ、こんにちは……会長さん。ありがとうございます、ボクのためにこんな素敵なテントを用意していただいて……」"

[[dialogue]]
speaker = "ルリエル"
# 「ステラさん、元々は<ruby=イルソーレ>流星寮</ruby>にお部屋が用意されてたじゃないですか？」
line = "「ステラさん、元々は<ruby>流星寮<rt>イルソーレ</rt></ruby>にお部屋が用意されてたじゃないですか？」"

[[dialogue]]
speaker = "ルリエル"
# 「でも人の出入りが多い場所は苦手とのこと。新星学園の星徒会室に、間借りする形で落ち着いてはいましたが……」
line = "「でも人の出入りが多い場所は苦手とのこと。新星学園の星徒会室に、間借りする形で落ち着いてはいましたが……」"

[[dialogue]]
speaker = "ルリエル"
# 「ここ最近は星徒会室に人の出入りも多くなってきて、見知らぬ人の視線に晒されることが増えてきてしまっていました！」
line = "「ここ最近は星徒会室に人の出入りも多くなってきて、見知らぬ人の視線に晒されることが増えてきてしまっていました！」"

[[dialogue]]
speaker = "ルリエル"
# 「そこでルリエル、考えました！　視線が気になるのなら、隠してしまえばいいのだと！！」
line = "「そこでルリエル、考えました！　視線が気になるのなら、隠してしまえばいいのだと！！」"

[[dialogue]]
speaker = "ルリエル"
# 「パーテーションではちょっとした角度で中が見えてしまうこともありますが、テントの中であれば、そんな心配は不要なのです」
line = "「パーテーションではちょっとした角度で中が見えてしまうこともありますが、テントの中であれば、そんな心配は不要なのです」"

[[dialogue]]
speaker = "ルリエル"
# 「どうですか、会長さん？　このルリエルの完璧なアイディアは……！　褒めてくれていいんですよ～、えへへ♪」
line = "「どうですか、会長さん？　このルリエルの完璧なアイディアは……！　褒めてくれていいんですよ～、えへへ♪」"

[[dialogue]]
speaker = "ステラ"
# 「あ、あれ……？　会長さん、なんだか複雑なお顔ですね……や、やっぱりご迷惑でしたか……？」
line = "「あ、あれ……？　会長さん、なんだか複雑なお顔ですね……や、やっぱりご迷惑でしたか……？」"

[[dialogue]]
speaker = "unk"
# 一応、こういったことは星徒会の許可を……
line = "一応、こういったことは星徒会の許可を……"

[[dialogue]]
speaker = "unk"
# 迷惑ではないんだけど……
line = "迷惑ではないんだけど……"

[[dialogue]]
speaker = "アナ"
# 「もぞもぞ……テントの中からしゅわっち」
line = "「もぞもぞ……テントの中からしゅわっち」"

[[dialogue]]
speaker = "unk"
# 流星市国に帰って来て早々、一体何を……
line = "流星市国に帰って来て早々、一体何を……"

[[dialogue]]
speaker = "unk"
# アナ！？
line = "アナ！？"

[[dialogue]]
speaker = "アナ"
# 「事後報告になりましたが、副会長権限で許可をしました。確かにスペースは取りますが、業務に大きな影響は出ないかと」
line = "「事後報告になりましたが、副会長権限で許可をしました。確かにスペースは取りますが、業務に大きな影響は出ないかと」"

[[dialogue]]
speaker = "ルリエル"
# 「会長さん、ステラさんがコーディネートしたテントは凄いんですよ！　中は一見散らかってる風ですが、全てが機能的に配置されているのです！」
line = "「会長さん、ステラさんがコーディネートしたテントは凄いんですよ！　中は一見散らかってる風ですが、全てが機能的に配置されているのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「あれれ。そんなバカな……ってお顔ですね？」
line = "「あれれ。そんなバカな……ってお顔ですね？」"

[[dialogue]]
speaker = "マトイ"
# 「ごそごそ……！　会長、一回このテントは体験しておいた方がいいよ！」
line = "「ごそごそ……！　会長、一回このテントは体験しておいた方がいいよ！」"

[[dialogue]]
speaker = "unk"
# マトイまで出てきた！？
line = "マトイまで出てきた！？"

[[dialogue]]
speaker = "ルリエル"
# 「それだけこの『ステラさんテント』の居心地がよいということなのです～♪」
line = "「それだけこの『ステラさんテント』の居心地がよいということなのです～♪」"

[[dialogue]]
speaker = "ステラ"
# 「ルリエルさんのおかげで、ボクの異世界生活がさらに快適になりました……本当に感謝してもしきれません……！」
line = "「ルリエルさんのおかげで、ボクの異世界生活がさらに快適になりました……本当に感謝してもしきれません……！」"

[[dialogue]]
speaker = "ルリエル"
# 「いえいえ、それほどでも～」
line = "「いえいえ、それほどでも～」"

[[dialogue]]
speaker = "ルリエル"
# 「そうだ！　会長さんも是非、ステラさんのテントの中を見ていって欲しいのです！」
line = "「そうだ！　会長さんも是非、ステラさんのテントの中を見ていって欲しいのです！」"

[[dialogue]]
speaker = "ステラ"
# 「えっ！？」
line = "「えっ！？」"

[[dialogue]]
speaker = "ステラ"
# （女の子が入るのはともかく、会長さんが中に入るのはちょっと恥ずかしいような！？）
line = "（女の子が入るのはともかく、会長さんが中に入るのはちょっと恥ずかしいような！？）"

[[dialogue]]
speaker = "ルリエル"
# 「ステラさんも引き籠りスタイルを、色んな人に布教したいと仰ってましたから！」
line = "「ステラさんも引き籠りスタイルを、色んな人に布教したいと仰ってましたから！」"

[[dialogue]]
speaker = "ルリエル"
# 「百聞は一見に如かずなのです！　ほらほら、会長さん！　早く入るのです！！」
line = "「百聞は一見に如かずなのです！　ほらほら、会長さん！　早く入るのです！！」"

[[dialogue]]
speaker = "ステラ"
# （あああっ……！！　ルリエルさんが会長さんを中に引っ張り込んじゃいました！？）
line = "（あああっ……！！　ルリエルさんが会長さんを中に引っ張り込んじゃいました！？）"

[[dialogue]]
speaker = "unk"
# なし崩し的にテントの中に引きずり込まれてしまったが……ともあれ、みんなが太鼓判を押すので体験してみることにした。
line = "なし崩し的にテントの中に引きずり込まれてしまったが……ともあれ、みんなが太鼓判を押すので体験してみることにした。"

[[dialogue]]
speaker = "unk"
# ものすごく落ち着く！！
line = "ものすごく落ち着く！！"

[[dialogue]]
speaker = "unk"
# これはすごい……！
line = "これはすごい……！"

[[dialogue]]
speaker = "ルリエル"
# 「でしょう！？　お菓子が食べたいな～って思ったら、右手を伸ばしたその先に！」
line = "「でしょう！？　お菓子が食べたいな～って思ったら、右手を伸ばしたその先に！」"

[[dialogue]]
speaker = "アナ"
# 「本を読みたいな～と思ったら、左手を伸ばしたその先に。<ruby=カオス>混沌</ruby>の中に存在する確かな秩序」
line = "「本を読みたいな～と思ったら、左手を伸ばしたその先に。<ruby>混沌<rt>カオス</rt></ruby>の中に存在する確かな秩序」"

[[dialogue]]
speaker = "マトイ"
# 「それにちょっぴり暗くて狭い所って落ち着くよね……こう、本能的に。私、今日からこのテントでお仕事しようかな……？」
line = "「それにちょっぴり暗くて狭い所って落ち着くよね……こう、本能的に。私、今日からこのテントでお仕事しようかな……？」"

[[dialogue]]
speaker = "ステラ"
# 「会長さんは、ぐーたらの才能があるみたいですね。ボクのテリトリーを評価してもらえて嬉しいです……！」
line = "「会長さんは、ぐーたらの才能があるみたいですね。ボクのテリトリーを評価してもらえて嬉しいです……！」"

[[dialogue]]
speaker = "unk"
# だらだらしてしまう……！
line = "だらだらしてしまう……！"

[[dialogue]]
speaker = "unk"
# だめだ……居心地がいい……！
line = "だめだ……居心地がいい……！"

[[dialogue]]
speaker = "ルリエル"
# 「一緒にぐーたら生活をユニゾンなのです～♪　は～……落ち着く～……<emoji=heart04>」
line = "「一緒にぐーたら生活をユニゾンなのです～♪　は～……落ち着く～……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 数時間後……
line = "数時間後……"

[[dialogue]]
speaker = "ソフィア"
# 「失礼します。流星星徒会からのご連絡を……って？」
line = "「失礼します。流星星徒会からのご連絡を……って？」"

[[dialogue]]
speaker = "ルリエル"
# 「だら～……<emoji=heart04>」
line = "「だら～……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「だら～……<emoji=heart04>」
line = "「だら～……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# だらだら～……
line = "だらだら～……"

[[dialogue]]
speaker = "ソフィア"
# 「……何してるんですか、あなたたちは」
line = "「……何してるんですか、あなたたちは」"
