[[dialogue]]
speaker = "unk"
# 第１話,ネビュラの姫,P
line = "第１話,ネビュラの姫,P"

[[dialogue]]
speaker = "クラウディア"
# 「──よく来た、魔王。余はお主を歓迎するぞ」
line = "「──よく来た、魔王。余はお主を歓迎するぞ」"

[[dialogue]]
speaker = "クラウディア"
# 「なんだ。しばらく会わぬうちに、もう余の顔を忘れたのか？」
line = "「なんだ。しばらく会わぬうちに、もう余の顔を忘れたのか？」"

[[dialogue]]
speaker = "クラウディア"
# 「クラウディア・イルゼ・フォン・ゴットフリート──『ネビュラ』の総帥たる偉くてすご～～～い魔女なのだ。どうだ、思い出したか？」
line = "「クラウディア・イルゼ・フォン・ゴットフリート──『ネビュラ』の総帥たる偉くてすご～～～い魔女なのだ。どうだ、思い出したか？」"

[[dialogue]]
speaker = "クラウディア"
# 「うむ。ならばよい。余はお主のことをよーく知っておるぞ」
line = "「うむ。ならばよい。余はお主のことをよーく知っておるぞ」"

[[dialogue]]
speaker = "クラウディア"
# 「なにせ人間界における『魔王』だからな。余ほどではないが、特別な相手だ。徹底的にまーくしておるのだ」
line = "「なにせ人間界における『魔王』だからな。余ほどではないが、特別な相手だ。徹底的にまーくしておるのだ」"

[[dialogue]]
speaker = "クラウディア"
# 「余の目は誤魔化せんぞ。お主は見かけからしてへんちくりんだ」
line = "「余の目は誤魔化せんぞ。お主は見かけからしてへんちくりんだ」"

[[dialogue]]
speaker = "クラウディア"
# 「肩幅は広いし、胸も飛び出ていないし、声も低い。これが魔王の特質というものか」
line = "「肩幅は広いし、胸も飛び出ていないし、声も低い。これが魔王の特質というものか」"

[[dialogue]]
speaker = "unk"
# それは男だから
line = "それは男だから"

[[dialogue]]
speaker = "クラウディア"
# 「む……男？　男だとそうなのか？」
line = "「む……男？　男だとそうなのか？」"

[[dialogue]]
speaker = "クラウディア"
# 「ふうむ……なるほど。知らなんだぞ。魔王の特徴というわけではないのだな」
line = "「ふうむ……なるほど。知らなんだぞ。魔王の特徴というわけではないのだな」"

[[dialogue]]
speaker = "クラウディア"
# 「何？　男が珍しいのか……と？」
line = "「何？　男が珍しいのか……と？」"

[[dialogue]]
speaker = "クラウディア"
# 「当たり前だ。余らは魔女の一族──森には女しかおらんからのう」
line = "「当たり前だ。余らは魔女の一族──森には女しかおらんからのう」"

[[dialogue]]
speaker = "クラウディア"
# 「と言っても……男の存在くらい知っているぞ。バカにするな。ただ、まじまじと見る機会がなかっただけだ！」
line = "「と言っても……男の存在くらい知っているぞ。バカにするな。ただ、まじまじと見る機会がなかっただけだ！」"

[[dialogue]]
speaker = "クラウディア"
# 「ふむ……この機に観察させてもらおう。腕も、腰も、脚のあたりも……なんだか全体的にがっちりしているな」
line = "「ふむ……この機に観察させてもらおう。腕も、腰も、脚のあたりも……なんだか全体的にがっちりしているな」"

[[dialogue]]
speaker = "unk"
# あんまりペタペタ触られると……
line = "あんまりペタペタ触られると……"

[[dialogue]]
speaker = "クラウディア"
# 「む？　これしきで応えるのか？　はっはっは、男というのは軟弱だのう」
line = "「む？　これしきで応えるのか？　はっはっは、男というのは軟弱だのう」"

[[dialogue]]
speaker = "クラウディア"
# 「まあよい。それより普段、お主はいかようにして過ごしておるのか？」
line = "「まあよい。それより普段、お主はいかようにして過ごしておるのか？」"

[[dialogue]]
speaker = "クラウディア"
# 「星徒かいちょー……ふむふむ。学園とやらの一員なのか」
line = "「星徒かいちょー……ふむふむ。学園とやらの一員なのか」"

[[dialogue]]
speaker = "クラウディア"
# 「して、その星徒かいちょーというのは、偉いのか？」
line = "「して、その星徒かいちょーというのは、偉いのか？」"

[[dialogue]]
speaker = "クラウディア"
# 「ほほう──余には及ばんまでも、なかなかの『けんりょくしゃ』のようだな」
line = "「ほほう──余には及ばんまでも、なかなかの『けんりょくしゃ』のようだな」"

[[dialogue]]
speaker = "クラウディア"
# 「よい機会だ。その学園とやらをひと目見たいぞ！　連れて行ってくれ」
line = "「よい機会だ。その学園とやらをひと目見たいぞ！　連れて行ってくれ」"

[[dialogue]]
speaker = "アイリーン"
# 「あ──ク、クラウディア様！？　こちらは指令室ですが──どういったご要件でしょうか？」
line = "「あ──ク、クラウディア様！？　こちらは指令室ですが──どういったご要件でしょうか？」"

[[dialogue]]
speaker = "クラウディア"
# 「なに。少々散歩がてら、外にでも出てみようかと思ってな」
line = "「なに。少々散歩がてら、外にでも出てみようかと思ってな」"

[[dialogue]]
speaker = "アイリーン"
# 「外に……ですか？　お言葉ですが、セドナ長官の許可なく出歩かれるのはまずいのではないかと」
line = "「外に……ですか？　お言葉ですが、セドナ長官の許可なく出歩かれるのはまずいのではないかと」"

[[dialogue]]
speaker = "クラウディア"
# 「お堅いやつよのう。余が一番エライのだから、誰にも止められる筋合いはないのだ。そーれ！」
line = "「お堅いやつよのう。余が一番エライのだから、誰にも止められる筋合いはないのだ。そーれ！」"

[[dialogue]]
speaker = "アイリーン"
# 「え──わああっ！？」
line = "「え──わああっ！？」"

[[dialogue]]
speaker = "アイリーン"
# 「……あ、あれ。私は誰と話していたのでしょうか。まだ仕事が残ってるのに──持ち場へ戻らないとっ」
line = "「……あ、あれ。私は誰と話していたのでしょうか。まだ仕事が残ってるのに──持ち場へ戻らないとっ」"

[[dialogue]]
speaker = "クラウディア"
# 「ん？　認識変異の魔法だ。アイリーンの意識をいじって、余を路傍の小石と区別のつかぬようにした」
line = "「ん？　認識変異の魔法だ。アイリーンの意識をいじって、余を路傍の小石と区別のつかぬようにした」"

[[dialogue]]
speaker = "クラウディア"
# 「もっとも、６０秒程度しか持続せぬ、まじないもどきだがな！」
line = "「もっとも、６０秒程度しか持続せぬ、まじないもどきだがな！」"

[[dialogue]]
speaker = "unk"
# 外には出ちゃいけないの？
line = "外には出ちゃいけないの？"

[[dialogue]]
speaker = "クラウディア"
# 「うむ。大人はどいつもこいつもケチンボゆえ、すぐお小言を言われるのだ。全くもって嘆かわしい」
line = "「うむ。大人はどいつもこいつもケチンボゆえ、すぐお小言を言われるのだ。全くもって嘆かわしい」"

[[dialogue]]
speaker = "クラウディア"
# 「どうもこの人間界において、魔女というのは表立ってはならぬそうでな……大体はこの基地で過ごしておる」
line = "「どうもこの人間界において、魔女というのは表立ってはならぬそうでな……大体はこの基地で過ごしておる」"

[[dialogue]]
speaker = "unk"
# でも、偉いんだよね
line = "でも、偉いんだよね"

[[dialogue]]
speaker = "クラウディア"
# 「当然だ！　ネビュラは今、世界を救う偉大な計画を抱えておる。余はそのために欠かせぬ存在なのだ！」
line = "「当然だ！　ネビュラは今、世界を救う偉大な計画を抱えておる。余はそのために欠かせぬ存在なのだ！」"

[[dialogue]]
speaker = "クラウディア"
# 「つまり余は偉大にして無敵！　よくよく考えれば、規則に縛られる道理などない！」
line = "「つまり余は偉大にして無敵！　よくよく考えれば、規則に縛られる道理などない！」"

[[dialogue]]
speaker = "クラウディア"
# 「わーっはっはっは！　よし、さっそく学園とやらに行くぞ！」
line = "「わーっはっはっは！　よし、さっそく学園とやらに行くぞ！」"

[[dialogue]]
speaker = "unk"
# 向こうから人影が……
line = "向こうから人影が……"

[[dialogue]]
speaker = "unk"
# あ……
line = "あ……"

[[dialogue]]
speaker = "セドナ"
# 「──姫」
line = "「──姫」"

[[dialogue]]
speaker = "クラウディア"
# 「──ぎく！？」
line = "「──ぎく！？」"

[[dialogue]]
speaker = "セドナ"
# 「無断で外出とはよいご身分ですね。宿題を課していたはずですが、こんなに早く済まされたのでしょうか」
line = "「無断で外出とはよいご身分ですね。宿題を課していたはずですが、こんなに早く済まされたのでしょうか」"

[[dialogue]]
speaker = "クラウディア"
# 「い、いや……まだというかだな。まずは気分転換も大事と思ってだな」
line = "「い、いや……まだというかだな。まずは気分転換も大事と思ってだな」"

[[dialogue]]
speaker = "セドナ"
# 「ネビュラとのおやくそく第五条『勝手にお外でちゃダメ』第二十二条『お外で魔法は使わない』」
line = "「ネビュラとのおやくそく第五条『勝手にお外でちゃダメ』第二十二条『お外で魔法は使わない』」"

[[dialogue]]
speaker = "セドナ"
# 「姫はどちらも理解不足のようですので、追加の課題が必要ですね。それから今夜は新鮮な野菜が届いておりますので、残さず召し上がっていただきます」
line = "「姫はどちらも理解不足のようですので、追加の課題が必要ですね。それから今夜は新鮮な野菜が届いておりますので、残さず召し上がっていただきます」"

[[dialogue]]
speaker = "クラウディア"
# 「い、嫌だ！　余は草っ葉など食いとうない！　ひぇっ……見てないで助けろおい！　まお～～！！」
line = "「い、嫌だ！　余は草っ葉など食いとうない！　ひぇっ……見てないで助けろおい！　まお～～！！」"
