[[dialogue]]
speaker = "unk"
# 第２話,ダブルアルモたんはデートがしたい,P
line = "第２話,ダブルアルモたんはデートがしたい,P"

[[dialogue]]
speaker = "unk"
# その日は、俺はアルモと街へ食べ歩きデートに出かけていた。
line = "その日は、俺はアルモと街へ食べ歩きデートに出かけていた。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「会長との『食べ歩きデート』、楽しみにしていたのだ～♪」
line = "「会長との『食べ歩きデート』、楽しみにしていたのだ～♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「でも……どうして<b>大きい</b>アルモたんも一緒なのだ！？」
line = "「でも……どうして<b>大きい</b>アルモたんも一緒なのだ！？」"

[[dialogue]]
speaker = "大人アルモ"
# 「当然だ。抜け駆けは許さんぞ、小さき我よ。デートをするなら『大人の食事』の方が、男女の雰囲気が出てよかろう？」
line = "「当然だ。抜け駆けは許さんぞ、小さき我よ。デートをするなら『大人の食事』の方が、男女の雰囲気が出てよかろう？」"

[[dialogue]]
speaker = "大人アルモ"
# 「――なぁ、我が愛しき人の子よ<emoji=heart04>」
line = "「――なぁ、我が愛しき人の子よ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そう言って、アルモが俺の腕に抱き着いてくる。大人ボディのボリュームある肉感が押し付けられ、思わずドキッとしてしまう。
line = "そう言って、アルモが俺の腕に抱き着いてくる。大人ボディのボリュームある肉感が押し付けられ、思わずドキッとしてしまう。"

[[dialogue]]
speaker = "unk"
# そ、そもそも２人は同一人物なのでは……？
line = "そ、そもそも２人は同一人物なのでは……？"

[[dialogue]]
speaker = "unk"
# アルモはアニマ先輩の作った『魂分裂薬』で魂を２つに分け、大小の義体を同時に運用している。その為、薬の効果時間が切れれば、元の１人に戻るわけで。
line = "アルモはアニマ先輩の作った『魂分裂薬』で魂を２つに分け、大小の義体を同時に運用している。その為、薬の効果時間が切れれば、元の１人に戻るわけで。"

[[dialogue]]
speaker = "大人アルモ"
# 「その通りではあるが……察せよ。女心というのは複雑なものなのだ」
line = "「その通りではあるが……察せよ。女心というのは複雑なものなのだ」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「そうだぞ、会長！　大きいアルモたんと小さいアルモたんは、牛肉と豚肉くらい別物なのだ！」
line = "「そうだぞ、会長！　大きいアルモたんと小さいアルモたんは、牛肉と豚肉くらい別物なのだ！」"

[[dialogue]]
speaker = "大人アルモ"
# 「うむ。マグダレナの方はどうか知らぬが、我にとっては目の前に双子の姉妹がいるような感覚だな」
line = "「うむ。マグダレナの方はどうか知らぬが、我にとっては目の前に双子の姉妹がいるような感覚だな」"

[[dialogue]]
speaker = "unk"
# よくわからないが……とりあえず今日は、ダブルアルモとデートということらしかった。
line = "よくわからないが……とりあえず今日は、ダブルアルモとデートということらしかった。"

[[dialogue]]
speaker = "unk"
# それからデートが始まると、さっそく２人は俺の腕を巡って言い合いを始めた。
line = "それからデートが始まると、さっそく２人は俺の腕を巡って言い合いを始めた。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「大きいアルモたん、会長にくっ付き過ぎなのだ！」
line = "「大きいアルモたん、会長にくっ付き過ぎなのだ！」"

[[dialogue]]
speaker = "大人アルモ"
# 「何を言う。肉感ある大人ボディを持つ我の方が、こうして腕に抱き着いて喜ばせるのは、必然の流れであろう」
line = "「何を言う。肉感ある大人ボディを持つ我の方が、こうして腕に抱き着いて喜ばせるのは、必然の流れであろう」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「会長はアルモたんの『ぴちぴちなお肉』も好きなのだ！　この小さい体でも、普段いっぱいイチャイチャしているのだからな♪」
line = "「会長はアルモたんの『ぴちぴちなお肉』も好きなのだ！　この小さい体でも、普段いっぱいイチャイチャしているのだからな♪」"

[[dialogue]]
speaker = "大人アルモ"
# 「だが『肉』というものは、ボリュームがある方がよかろう？」
line = "「だが『肉』というものは、ボリュームがある方がよかろう？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「量があっても、味が美味じゃなかったら意味ないのだ！」
line = "「量があっても、味が美味じゃなかったら意味ないのだ！」"

[[dialogue]]
speaker = "大人アルモ"
# 「誰が美味でないと！？　我の大人ボディは熟成肉のように味わい深いぞ！」
line = "「誰が美味でないと！？　我の大人ボディは熟成肉のように味わい深いぞ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「むぅ～っ！　会長はどっちのアルモたんが好きなのだ！？」
line = "「むぅ～っ！　会長はどっちのアルモたんが好きなのだ！？」"

[[dialogue]]
speaker = "大人アルモ"
# 「当然、大きい方の我であろう？　なにせ最初に恋人になったのは我の方なのだからな♪」
line = "「当然、大きい方の我であろう？　なにせ最初に恋人になったのは我の方なのだからな♪」"

[[dialogue]]
speaker = "unk"
# こ、答えづらい……！
line = "こ、答えづらい……！"

[[dialogue]]
speaker = "大人アルモ"
# 「なっ！？　即答できんとはどういうことだ！？」
line = "「なっ！？　即答できんとはどういうことだ！？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ふふ～ん♪　つまり今は『小さいアルモたん』の方にメロメロということだな♪」
line = "「ふふ～ん♪　つまり今は『小さいアルモたん』の方にメロメロということだな♪」"

[[dialogue]]
speaker = "大人アルモ"
# 「まさか……浮気か！？　そうなのか！」
line = "「まさか……浮気か！？　そうなのか！」"

[[dialogue]]
speaker = "unk"
# ――いや、俺はずっとアルモが一途に好きなんだけど！？
line = "――いや、俺はずっとアルモが一途に好きなんだけど！？"

[[dialogue]]
speaker = "unk"
# それからしばらく歩いて、アクセサリー店を見つけて立ち寄ると、２人はどれを買ってもらうかで再び言い合い始めた。
line = "それからしばらく歩いて、アクセサリー店を見つけて立ち寄ると、２人はどれを買ってもらうかで再び言い合い始めた。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「アルモたんは、この可愛いヘアピンの方がいいのだ！」
line = "「アルモたんは、この可愛いヘアピンの方がいいのだ！」"

[[dialogue]]
speaker = "大人アルモ"
# 「ならば大人の我に似合うこちらのデザインにすべきであろう」
line = "「ならば大人の我に似合うこちらのデザインにすべきであろう」"

[[dialogue]]
speaker = "unk"
# 見かねた俺は、２人の間に割って入る。
line = "見かねた俺は、２人の間に割って入る。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「えっ……？　会長、両方とも買ってくれるのか？」
line = "「えっ……？　会長、両方とも買ってくれるのか？」"

[[dialogue]]
speaker = "大人アルモ"
# 「それは嬉しいが……。すまない、気を遣わせてしまったな。つい熱くなってしまった……」
line = "「それは嬉しいが……。すまない、気を遣わせてしまったな。つい熱くなってしまった……」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「アルモたんも反省するのだ……ごめんなのだ……」
line = "「アルモたんも反省するのだ……ごめんなのだ……」"

[[dialogue]]
speaker = "unk"
# シュンとする２人に俺は笑ってみせて、双方の頭を撫でる。
line = "シュンとする２人に俺は笑ってみせて、双方の頭を撫でる。"

[[dialogue]]
speaker = "unk"
# 正直、２人に挟まれるのは嬉しい
line = "正直、２人に挟まれるのは嬉しい"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――好きな子が２人に増えるのは、男としては夢があるシチュエーション……？」
line = "「――好きな子が２人に増えるのは、男としては夢があるシチュエーション……？」"

[[dialogue]]
speaker = "大人アルモ"
# 「ふふっ、そうか。この状況は役得ということか」
line = "「ふふっ、そうか。この状況は役得ということか」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「なら、アルモたんたちは休戦して、会長を喜ばせてあげるのだ♪」
line = "「なら、アルモたんたちは休戦して、会長を喜ばせてあげるのだ♪」"

[[dialogue]]
speaker = "大人アルモ"
# 「うむ。迷惑をかけた詫びに、また『アルモたんハーレム』を堪能させてやろう<emoji=heart04>」
line = "「うむ。迷惑をかけた詫びに、また『アルモたんハーレム』を堪能させてやろう<emoji=heart04>」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「お肉も種類が多いけど、どれも美味しくて、１番が選べないのと同じなのだ♪」
line = "「お肉も種類が多いけど、どれも美味しくて、１番が選べないのと同じなのだ♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「あっ！　でも、アルモたんが男として好きなのは、会長だけだぞ<emoji=heart04>」
line = "「あっ！　でも、アルモたんが男として好きなのは、会長だけだぞ<emoji=heart04>」"

[[dialogue]]
speaker = "大人アルモ"
# 「然り。我がツガイになりたいと思う男は、お前だけだ」
line = "「然り。我がツガイになりたいと思う男は、お前だけだ」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「会長、大好きなのだ<emoji=heart04>　ん～っ、ちゅっ<emoji=heart04>」
line = "「会長、大好きなのだ<emoji=heart04>　ん～っ、ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "大人アルモ"
# 「我からも……ちゅっ<emoji=heart04>」
line = "「我からも……ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 左右の頬に同時キスされて、ドキッとしてしまう。
line = "左右の頬に同時キスされて、ドキッとしてしまう。"

[[dialogue]]
speaker = "unk"
# ふ、２人共、こんなところで……！
line = "ふ、２人共、こんなところで……！"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「えへへ～<emoji=heart04>　好きって気持ちが溢れて、ついキスしたくなっちゃったのだ<emoji=heart04>」
line = "「えへへ～<emoji=heart04>　好きって気持ちが溢れて、ついキスしたくなっちゃったのだ<emoji=heart04>」"

[[dialogue]]
speaker = "大人アルモ"
# 「ふふっ<emoji=heart04>　なに、堂々としていれば、意外と注目されぬものだ<emoji=heart04>」
line = "「ふふっ<emoji=heart04>　なに、堂々としていれば、意外と注目されぬものだ<emoji=heart04>」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「……そうだ！　大きいアルモたん、耳を貸すのだ！」
line = "「……そうだ！　大きいアルモたん、耳を貸すのだ！」"

[[dialogue]]
speaker = "大人アルモ"
# 「うん？　……ほう、それは良い案だ。さすが小さくても我だな」
line = "「うん？　……ほう、それは良い案だ。さすが小さくても我だな」"

[[dialogue]]
speaker = "unk"
# ２人はこそこそと相談した後、俺の両腕に抱き着いてくる。
line = "２人はこそこそと相談した後、俺の両腕に抱き着いてくる。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「会長、このあとは食べ歩きデートから、『食べ放題』に予定を変更なのだ♪」
line = "「会長、このあとは食べ歩きデートから、『食べ放題』に予定を変更なのだ♪」"

[[dialogue]]
speaker = "大人アルモ"
# 「我ら２人に挟まれるのは嬉しいのだろう？　ならば――」
line = "「我ら２人に挟まれるのは嬉しいのだろう？　ならば――」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「リゾート結界で、ダブルアルモたんが会長にお肉をいっぱい食べさせてあげるのだ♪」
line = "「リゾート結界で、ダブルアルモたんが会長にお肉をいっぱい食べさせてあげるのだ♪」"

[[dialogue]]
speaker = "大人アルモ"
# 「ふふっ、つまりはバーベキューをして、我ら２人であ～んをしてやるということだ。どうだ？」
line = "「ふふっ、つまりはバーベキューをして、我ら２人であ～んをしてやるということだ。どうだ？」"

[[dialogue]]
speaker = "unk"
# 俺は期待を膨らませながら、こくりと頷く。
line = "俺は期待を膨らませながら、こくりと頷く。"

[[dialogue]]
speaker = "大人アルモ"
# 「ふふっ、決まりだな<emoji=heart04>　もちろん、食後のデザートも予定しているぞ<emoji=heart04>」
line = "「ふふっ、決まりだな<emoji=heart04>　もちろん、食後のデザートも予定しているぞ<emoji=heart04>」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ダブルアルモたんとのイチャイチャを、お腹いっぱい味わうといいのだ<emoji=heart04>」
line = "「ダブルアルモたんとのイチャイチャを、お腹いっぱい味わうといいのだ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# こうして俺は、大好きな２人に挟まれながら、お腹も心も満たされる幸せな休日を過ごすのだった。
line = "こうして俺は、大好きな２人に挟まれながら、お腹も心も満たされる幸せな休日を過ごすのだった。"
