[[dialogue]]
speaker = "unk"
# 第３話,制圧天使,P
line = "第３話,制圧天使,P"

[[dialogue]]
speaker = "unk"
# 街中を歩いていると、ケイティさんの姿を見つけた。
line = "街中を歩いていると、ケイティさんの姿を見つけた。"

[[dialogue]]
speaker = "unk"
# 小さな雑貨屋の店先で、そこの店員らしき女性と話をしている。
line = "小さな雑貨屋の店先で、そこの店員らしき女性と話をしている。"

[[dialogue]]
speaker = "ケイティ"
# 「あらあら、こちらのティーセットもすごく可愛いですね～」
line = "「あらあら、こちらのティーセットもすごく可愛いですね～」"

[[dialogue]]
speaker = "女性店員"
# 「いいわよね～。今人気だから品薄なの。上品な雰囲気がケイティさんにピッタリだと思うし、オススメよ～」
line = "「いいわよね～。今人気だから品薄なの。上品な雰囲気がケイティさんにピッタリだと思うし、オススメよ～」"

[[dialogue]]
speaker = "ケイティ"
# 「うふふ、そうですか～？　ありがとうございます。それじゃこちらを頂いていいですか～？」
line = "「うふふ、そうですか～？　ありがとうございます。それじゃこちらを頂いていいですか～？」"

[[dialogue]]
speaker = "女性店員"
# 「ありがとう。それじゃすぐに包んでくるわね」
line = "「ありがとう。それじゃすぐに包んでくるわね」"

[[dialogue]]
speaker = "unk"
# 今日はお休みですか？
line = "今日はお休みですか？"

[[dialogue]]
speaker = "unk"
# こんにちは
line = "こんにちは"

[[dialogue]]
speaker = "ケイティ"
# 「あら、魔王さん。こんにちは」
line = "「あら、魔王さん。こんにちは」"

[[dialogue]]
speaker = "ケイティ"
# 「ええ、今日は非番の日なんです。だから、せっかく人間界に来ているのですし、以前からやってみたかった雑貨屋巡りを満喫しているんですよ～」
line = "「ええ、今日は非番の日なんです。だから、せっかく人間界に来ているのですし、以前からやってみたかった雑貨屋巡りを満喫しているんですよ～」"

[[dialogue]]
speaker = "ケイティ"
# 「人間界の雑貨は種類も豊富だし、可愛いものが多いからいいですね～。眺めているだけでも楽しい気分になれます」
line = "「人間界の雑貨は種類も豊富だし、可愛いものが多いからいいですね～。眺めているだけでも楽しい気分になれます」"

[[dialogue]]
speaker = "ケイティ"
# 「天界にもこういったお店はあるのですが、やはりこういったものは人間界が一番充実しているのだとはっきり分かりました～」
line = "「天界にもこういったお店はあるのですが、やはりこういったものは人間界が一番充実しているのだとはっきり分かりました～」"

[[dialogue]]
speaker = "unk"
# お茶会の道具狙いですか？
line = "お茶会の道具狙いですか？"

[[dialogue]]
speaker = "ケイティ"
# 「そうですね。でも私、それ以外でも可愛い小物なら何でも好きなので……」
line = "「そうですね。でも私、それ以外でも可愛い小物なら何でも好きなので……」"

[[dialogue]]
speaker = "ケイティ"
# 「あっ、このコースターも可愛いです♪　あっちの写真立ても……どれもこれも欲しくなっちゃいます～♪」
line = "「あっ、このコースターも可愛いです♪　あっちの写真立ても……どれもこれも欲しくなっちゃいます～♪」"

[[dialogue]]
speaker = "ケイティ"
# 「この音は？」
line = "「この音は？」"

[[dialogue]]
speaker = "unk"
# 近くにアステラが出現しました
line = "近くにアステラが出現しました"

[[dialogue]]
speaker = "ケイティ"
# 「まあ、それは大変です。はやく皆さんを安全なところへ避難させないと～」
line = "「まあ、それは大変です。はやく皆さんを安全なところへ避難させないと～」"

[[dialogue]]
speaker = "ケイティ"
# 「店員さん、ここは私に任せて逃げてください」
line = "「店員さん、ここは私に任せて逃げてください」"

[[dialogue]]
speaker = "女性店員"
# 「あ、ありがとうございます──あっ！」
line = "「あ、ありがとうございます──あっ！」"

[[dialogue]]
speaker = "モンスター"
# 「イーーーーーーーーッ！！！！」
line = "「イーーーーーーーーッ！！！！」"

[[dialogue]]
speaker = "ケイティ"
# 「モンスターさーん！　ここで暴れるのはやめてください、争いは何も生みませんよ～！」
line = "「モンスターさーん！　ここで暴れるのはやめてください、争いは何も生みませんよ～！」"

[[dialogue]]
speaker = "unk"
# モンスターを説得！？
line = "モンスターを説得！？"

[[dialogue]]
speaker = "モンスター"
# 「イーーーーーーーーッ！！！！」
line = "「イーーーーーーーーッ！！！！」"

[[dialogue]]
speaker = "ケイティ"
# 「危ない！」
line = "「危ない！」"

[[dialogue]]
speaker = "ケイティ"
# 「大丈夫ですか店員さん、お怪我はありませんか？」
line = "「大丈夫ですか店員さん、お怪我はありませんか？」"

[[dialogue]]
speaker = "女性店員"
# 「は、はい……おかげさまで。ですが……」
line = "「は、はい……おかげさまで。ですが……」"

[[dialogue]]
speaker = "ケイティ"
# 「あっ……」
line = "「あっ……」"

[[dialogue]]
speaker = "unk"
# モンスターの攻撃から店員さんをかばった時に、買ったばかりのティーセットが路面に落ちて粉々に砕けてしまっていた。
line = "モンスターの攻撃から店員さんをかばった時に、買ったばかりのティーセットが路面に落ちて粉々に砕けてしまっていた。"

[[dialogue]]
speaker = "ケイティ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# あの、ケイティさん、どうか冷静に
line = "あの、ケイティさん、どうか冷静に"

[[dialogue]]
speaker = "ケイティ"
# 「ええ、もちろんです。私は平和主義ですから」
line = "「ええ、もちろんです。私は平和主義ですから」"

[[dialogue]]
speaker = "ケイティ"
# 「けれど、モンスターさんは私の忠告にも関わらず暴れ続けています」
line = "「けれど、モンスターさんは私の忠告にも関わらず暴れ続けています」"

[[dialogue]]
speaker = "ケイティ"
# 「……で、あれば……平和のために戦うしかありませんね」
line = "「……で、あれば……平和のために戦うしかありませんね」"

[[dialogue]]
speaker = "ケイティ"
# 「では、参ります……平和の重みを思い知りなさーーいっ！！！」
line = "「では、参ります……平和の重みを思い知りなさーーいっ！！！」"

[[dialogue]]
speaker = "ケイティ"
# 「アステラも消滅しましたし、もう安心ですね。街の平和を取り戻せて何よりです～」
line = "「アステラも消滅しましたし、もう安心ですね。街の平和を取り戻せて何よりです～」"

[[dialogue]]
speaker = "ケイティ"
# 「店員さんもお怪我はありませんか？」
line = "「店員さんもお怪我はありませんか？」"

[[dialogue]]
speaker = "女性店員"
# 「は、はい……」
line = "「は、はい……」"

[[dialogue]]
speaker = "ケイティ"
# 「もう震えなくても大丈夫です、モンスターは私たちが倒しましたから～」
line = "「もう震えなくても大丈夫です、モンスターは私たちが倒しましたから～」"

[[dialogue]]
speaker = "女性店員"
# 「ありがとう……ございます……」
line = "「ありがとう……ございます……」"

[[dialogue]]
speaker = "ケイティ"
# 「ですが申し訳ないことになってしまいました～。せっかくお薦めしてもらったティーセットが……」
line = "「ですが申し訳ないことになってしまいました～。せっかくお薦めしてもらったティーセットが……」"

[[dialogue]]
speaker = "女性店員"
# 「それでしたら！　こちらをお持ちください！　お代は要りませんので！」
line = "「それでしたら！　こちらをお持ちください！　お代は要りませんので！」"

[[dialogue]]
speaker = "ケイティ"
# 「まあ、こちらも可愛いティーセット♪」
line = "「まあ、こちらも可愛いティーセット♪」"

[[dialogue]]
speaker = "ケイティ"
# 「ですがそれは申し訳ありません。お代はきちんとお支払いいたしますから……」
line = "「ですがそれは申し訳ありません。お代はきちんとお支払いいたしますから……」"

[[dialogue]]
speaker = "女性店員"
# 「いいえ、命を助けて頂いたのですから！　そんなことはおっしゃらず！　命だけはっ！」
line = "「いいえ、命を助けて頂いたのですから！　そんなことはおっしゃらず！　命だけはっ！」"

[[dialogue]]
speaker = "ケイティ"
# 「そう、ですか……ではありがたく頂いておきますね～♪」
line = "「そう、ですか……ではありがたく頂いておきますね～♪」"

[[dialogue]]
speaker = "unk"
# 嬉しそうに新しいティーセットを受け取るケイティさん。
line = "嬉しそうに新しいティーセットを受け取るケイティさん。"

[[dialogue]]
speaker = "unk"
# けど、おそらく……店員さんが怯えていたのはモンスターじゃなくてケイティさんではないかと思う。
line = "けど、おそらく……店員さんが怯えていたのはモンスターじゃなくてケイティさんではないかと思う。"

[[dialogue]]
speaker = "unk"
# 何しろあの大剣をぶん回して、モンスターたちを完膚なきまでに叩き潰して回る光景を目の当たりにしたのだから。
line = "何しろあの大剣をぶん回して、モンスターたちを完膚なきまでに叩き潰して回る光景を目の当たりにしたのだから。"
