[[dialogue]]
speaker = "unk"
# 第２話,何もしてないのに壊れた！,P
line = "第２話,何もしてないのに壊れた！,P"

[[dialogue]]
speaker = "unk"
# コハルコさんの依頼で、シミュレーターの調整を手伝っていた。
line = "コハルコさんの依頼で、シミュレーターの調整を手伝っていた。"

[[dialogue]]
speaker = "unk"
# 今回の作業は、リクリエの直前あたりから現れた新種のモンスターの登録も兼ねている。
line = "今回の作業は、リクリエの直前あたりから現れた新種のモンスターの登録も兼ねている。"

[[dialogue]]
speaker = "unk"
# いわゆる大型アップデートだ。
line = "いわゆる大型アップデートだ。"

[[dialogue]]
speaker = "コハルコ"
# 「お疲れ様。進捗は順調だし、ここらで少し休憩しようか。お茶でいいかな？」
line = "「お疲れ様。進捗は順調だし、ここらで少し休憩しようか。お茶でいいかな？」"

[[dialogue]]
speaker = "unk"
# ありがとうございます
line = "ありがとうございます"

[[dialogue]]
speaker = "コハルコ"
# 「それにしても、会長さんは強くなったね。初めて出会った頃と比べて、明らかに星力が伸びてる」
line = "「それにしても、会長さんは強くなったね。初めて出会った頃と比べて、明らかに星力が伸びてる」"

[[dialogue]]
speaker = "シルヴィ"
# 「コハルコ助けて～！　何もしてないのにＤＩＳＣが壊れた～！」
line = "「コハルコ助けて～！　何もしてないのにＤＩＳＣが壊れた～！」"

[[dialogue]]
speaker = "コハルコ"
# 「ＤＩＳＣは何もしてないのに壊れません！」
line = "「ＤＩＳＣは何もしてないのに壊れません！」"

[[dialogue]]
speaker = "シルヴィ"
# 「濡らしたり、落としたりはしてないよ！　心当たりないんだって！」
line = "「濡らしたり、落としたりはしてないよ！　心当たりないんだって！」"

[[dialogue]]
speaker = "コハルコ"
# 「シルヴィ、今日、変身したでしょ？」
line = "「シルヴィ、今日、変身したでしょ？」"

[[dialogue]]
speaker = "シルヴィ"
# 「うん」
line = "「うん」"

[[dialogue]]
speaker = "コハルコ"
# 「そのあとすぐＤＩＳＣ触った？」
line = "「そのあとすぐＤＩＳＣ触った？」"

[[dialogue]]
speaker = "シルヴィ"
# 「うん……あっ！」
line = "「うん……あっ！」"

[[dialogue]]
speaker = "コハルコ"
# 「シルヴィは雷の星術なんだから気を付けなさいって私、何度も言ったよね？　帯電したまま触ったら壊れるよって」
line = "「シルヴィは雷の星術なんだから気を付けなさいって私、何度も言ったよね？　帯電したまま触ったら壊れるよって」"

[[dialogue]]
speaker = "コハルコ"
# 「対策はしてあるとはいえ、シルヴィの雷は一際強力なんだから、注意しないとダメだよ」
line = "「対策はしてあるとはいえ、シルヴィの雷は一際強力なんだから、注意しないとダメだよ」"

[[dialogue]]
speaker = "シルヴィ"
# 「うぅ……ごめんなさい」
line = "「うぅ……ごめんなさい」"

[[dialogue]]
speaker = "コハルコ"
# 「ほら、見せて。……うーん、これなら修理するより、データをサルベージして新しい端末に引き継いだ方がいいかな。私から申請しとくね」
line = "「ほら、見せて。……うーん、これなら修理するより、データをサルベージして新しい端末に引き継いだ方がいいかな。私から申請しとくね」"

[[dialogue]]
speaker = "シルヴィ"
# 「ありがとっ！　今度チキンおごるね♪」
line = "「ありがとっ！　今度チキンおごるね♪」"

[[dialogue]]
speaker = "コハルコ"
# 「いや、チキンはいいかな……そうだ、お礼するならひとつお願いがあるんだけど」
line = "「いや、チキンはいいかな……そうだ、お礼するならひとつお願いがあるんだけど」"

[[dialogue]]
speaker = "シルヴィ"
# 「いいよ！」
line = "「いいよ！」"

[[dialogue]]
speaker = "コハルコ"
# 「用件は聞いてから返事しなさい。面倒なデバッグとかだったらどうするの」
line = "「用件は聞いてから返事しなさい。面倒なデバッグとかだったらどうするの」"

[[dialogue]]
speaker = "シルヴィ"
# 「でばっく……？　バックするの？　オーラーイって」
line = "「でばっく……？　バックするの？　オーラーイって」"

[[dialogue]]
speaker = "コハルコ"
# 「……私が悪かったから忘れて。で、そのお願いなんだけど、会長さんと一緒にシミュレーターで戦ってくれないかな？」
line = "「……私が悪かったから忘れて。で、そのお願いなんだけど、会長さんと一緒にシミュレーターで戦ってくれないかな？」"

[[dialogue]]
speaker = "コハルコ"
# 「今のバージョンでデータを取りたいんだけど、サンプルは多い方がいいからね」
line = "「今のバージョンでデータを取りたいんだけど、サンプルは多い方がいいからね」"

[[dialogue]]
speaker = "シルヴィ"
# 「おっけー！　会長くんの実力も気になってたからね！」
line = "「おっけー！　会長くんの実力も気になってたからね！」"

[[dialogue]]
speaker = "コハルコ"
# 「会長さんもいい？」
line = "「会長さんもいい？」"

[[dialogue]]
speaker = "unk"
# はい
line = "はい"

[[dialogue]]
speaker = "シルヴィ"
# 「決まりだね！」
line = "「決まりだね！」"

[[dialogue]]
speaker = "シルヴィ"
# 「じゃあどっちが多くモンスターを倒せるか競争しようよ！　勝ったら会長の座をいただいちゃおうかな！」
line = "「じゃあどっちが多くモンスターを倒せるか競争しようよ！　勝ったら会長の座をいただいちゃおうかな！」"

[[dialogue]]
speaker = "シルヴィ"
# 「ふふ、負ける気はないって顔だね」
line = "「ふふ、負ける気はないって顔だね」"

[[dialogue]]
speaker = "シルヴィ"
# 「いくよっ！　ワン、ツー、スリー、フォー！」
line = "「いくよっ！　ワン、ツー、スリー、フォー！」"

[[dialogue]]
speaker = "シルヴィ"
# 「負けたー！！」
line = "「負けたー！！」"

[[dialogue]]
speaker = "シルヴィ"
# 「ふぃー、疲れた。こんなに動いたの久々かも」
line = "「ふぃー、疲れた。こんなに動いたの久々かも」"

[[dialogue]]
speaker = "コハルコ"
# 「お疲れ様。おかげでいいデータが取れたよ。シルヴィはオレンジジュースだったよね？　会長さんは？」
line = "「お疲れ様。おかげでいいデータが取れたよ。シルヴィはオレンジジュースだったよね？　会長さんは？」"

[[dialogue]]
speaker = "unk"
# 同じのでお願いします
line = "同じのでお願いします"

[[dialogue]]
speaker = "コハルコ"
# 「分かった。はい、どうぞ」
line = "「分かった。はい、どうぞ」"

[[dialogue]]
speaker = "unk"
# コハルコ先輩のドローンが俺たちの前にドリンクを運んでくれる。オレンジの甘みと酸味が疲れた体に染み渡る。
line = "コハルコ先輩のドローンが俺たちの前にドリンクを運んでくれる。オレンジの甘みと酸味が疲れた体に染み渡る。"

[[dialogue]]
speaker = "シルヴィ"
# 「ぷは～！　１００％は効く～！」
line = "「ぷは～！　１００％は効く～！」"

[[dialogue]]
speaker = "コハルコ"
# 「おじさんみたいなこと言わないの。会長さんはシルヴィと戦ってみてどうだった？」
line = "「おじさんみたいなこと言わないの。会長さんはシルヴィと戦ってみてどうだった？」"

[[dialogue]]
speaker = "unk"
# 強くて派手でした
line = "強くて派手でした"

[[dialogue]]
speaker = "コハルコ"
# 「音とか光とかすごいからね。どこで戦っててもすぐ分かるんだよ。シルヴィは一緒に戦ってみてどうだった？」
line = "「音とか光とかすごいからね。どこで戦っててもすぐ分かるんだよ。シルヴィは一緒に戦ってみてどうだった？」"

[[dialogue]]
speaker = "シルヴィ"
# 「めーっちゃ強かった！　さすが星徒会長！　この学園で最強なだけあるね！」
line = "「めーっちゃ強かった！　さすが星徒会長！　この学園で最強なだけあるね！」"

[[dialogue]]
speaker = "シルヴィ"
# 「君がいたから、リクリエは止められたんだね。……ありがとう、サーシャやみんなを守ってくれて」
line = "「君がいたから、リクリエは止められたんだね。……ありがとう、サーシャやみんなを守ってくれて」"

[[dialogue]]
speaker = "unk"
# 俺もみんなに助けられてきました
line = "俺もみんなに助けられてきました"

[[dialogue]]
speaker = "シルヴィ"
# 「そっか」
line = "「そっか」"

[[dialogue]]
speaker = "シルヴィ"
# 「いい子だな～もう！　そういうとこ好きだよ！」
line = "「いい子だな～もう！　そういうとこ好きだよ！」"

[[dialogue]]
speaker = "unk"
# シルヴィ先輩に気に入られたのか、髪がボサボサになるまで撫でられてしまった。
line = "シルヴィ先輩に気に入られたのか、髪がボサボサになるまで撫でられてしまった。"
