[[dialogue]]
speaker = "unk"
# 第２話,ゲシュペンス島とモンスター娘,P
line = "第２話,ゲシュペンス島とモンスター娘,P"

[[dialogue]]
speaker = "unk"
# 明らかに学園生ではない女性が、花火を打ち上げていたという現場に到着した。
line = "明らかに学園生ではない女性が、花火を打ち上げていたという現場に到着した。"

[[dialogue]]
speaker = "unk"
# しかし、その女性は既に現場を去ってしまったとのことだった。
line = "しかし、その女性は既に現場を去ってしまったとのことだった。"

[[dialogue]]
speaker = "unk"
# 聞き込みから得た情報によると、女性は学園外に出て行ったらしく、急いでその後を追う。
line = "聞き込みから得た情報によると、女性は学園外に出て行ったらしく、急いでその後を追う。"

[[dialogue]]
speaker = "ルルゥ"
# 「マムさん、ずっと気になってたの！　この大きな道に列を作って走ってるアレ、何か教えて欲しいの！」
line = "「マムさん、ずっと気になってたの！　この大きな道に列を作って走ってるアレ、何か教えて欲しいの！」"

[[dialogue]]
speaker = "マハムート"
# 「あれは車よ。確かにゲシュペンス島では見かけなかったし、あそこでは必要ないものかもしれないわね」
line = "「あれは車よ。確かにゲシュペンス島では見かけなかったし、あそこでは必要ないものかもしれないわね」"

[[dialogue]]
speaker = "ルルゥ"
# 「クルマ娘……初めて見る『モンスター娘』なの……」
line = "「クルマ娘……初めて見る『モンスター娘』なの……」"

[[dialogue]]
speaker = "マハムート"
# 「あれはモンスター娘ではなくて、ただの乗り物よ。よく見てみなさい、中にヒトが乗っているでしょう？」
line = "「あれはモンスター娘ではなくて、ただの乗り物よ。よく見てみなさい、中にヒトが乗っているでしょう？」"

[[dialogue]]
speaker = "ルルゥ"
# 「わわ、本当なの！」
line = "「わわ、本当なの！」"

[[dialogue]]
speaker = "フィオナ"
# 「ゲシュペンス島ではルルゥさんのようなヒトたちのことを、モンスター娘、と呼ぶのですか？」
line = "「ゲシュペンス島ではルルゥさんのようなヒトたちのことを、モンスター娘、と呼ぶのですか？」"

[[dialogue]]
speaker = "ルルゥ"
# 「そうなの。ルルゥはカーバンクル娘だけど、島には他にもいろんなモンスター娘がいるの」
line = "「そうなの。ルルゥはカーバンクル娘だけど、島には他にもいろんなモンスター娘がいるの」"

[[dialogue]]
speaker = "マハムート"
# 「私たちにとって『モンスター』と言えば、リクリエの生み出す怪物の事だから、フィオナが引っ掛かるのも無理ないわね」
line = "「私たちにとって『モンスター』と言えば、リクリエの生み出す怪物の事だから、フィオナが引っ掛かるのも無理ないわね」"

[[dialogue]]
speaker = "マハムート"
# 「けれどゲシュペンス島のモンスター娘は、それとは全くの別物だから安心しなさい」
line = "「けれどゲシュペンス島のモンスター娘は、それとは全くの別物だから安心しなさい」"

[[dialogue]]
speaker = "unk"
# 他にはどんな娘がいるの？
line = "他にはどんな娘がいるの？"

[[dialogue]]
speaker = "ルルゥ"
# 「オーク娘やスライム娘。ペガサス娘にミノタウロス娘。いろんな子がいる、なの」
line = "「オーク娘やスライム娘。ペガサス娘にミノタウロス娘。いろんな子がいる、なの」"

[[dialogue]]
speaker = "マハムート"
# 「私と同じ竜族のモンスター娘もいたわね」
line = "「私と同じ竜族のモンスター娘もいたわね」"

[[dialogue]]
speaker = "ルルゥ"
# 「ふふふっ♪　実はルルゥもドラゴンに変身できるの！　カーバンクルドラゴンなの♪」
line = "「ふふふっ♪　実はルルゥもドラゴンに変身できるの！　カーバンクルドラゴンなの♪」"

[[dialogue]]
speaker = "マハムート"
# 「それは知らなかったわね。そんな力を持っているのなら、是非見せて欲しいわ」
line = "「それは知らなかったわね。そんな力を持っているのなら、是非見せて欲しいわ」"

[[dialogue]]
speaker = "ルルゥ"
# 「んん……残念だけど、ここではその力は使えないみたい、なの」
line = "「んん……残念だけど、ここではその力は使えないみたい、なの」"

[[dialogue]]
speaker = "unk"
# すごい島だな、ゲシュペンス島
line = "すごい島だな、ゲシュペンス島"

[[dialogue]]
speaker = "unk"
# 本当にいろんな種族の娘がいるんだね
line = "本当にいろんな種族の娘がいるんだね"

[[dialogue]]
speaker = "ルルゥ"
# 「会長さんたちの学園もすごい場所なの。色んなヒトたちがひとつの場所に集まってるの」
line = "「会長さんたちの学園もすごい場所なの。色んなヒトたちがひとつの場所に集まってるの」"

[[dialogue]]
speaker = "フィオナ"
# 「流星市国はこの世界においても特別な場所ではありますが……」
line = "「流星市国はこの世界においても特別な場所ではありますが……」"

[[dialogue]]
speaker = "フィオナ"
# 「魔族に天使に人間。集まっている種族の混沌具合で言えば、私たちの学園も負けてはいないかもしれませんね」
line = "「魔族に天使に人間。集まっている種族の混沌具合で言えば、私たちの学園も負けてはいないかもしれませんね」"

[[dialogue]]
speaker = "ルルゥ"
# 「そんなヒトたちのリーダーの会長さんは、やっぱりすごいヒトなの……！」
line = "「そんなヒトたちのリーダーの会長さんは、やっぱりすごいヒトなの……！」"

[[dialogue]]
speaker = "unk"
# 耐えろ、俺！
line = "耐えろ、俺！"

[[dialogue]]
speaker = "unk"
# ううっ、その目で見つめられると！
line = "ううっ、その目で見つめられると！"

[[dialogue]]
speaker = "マハムート"
# 「ルルゥ、また能力が暴走しているわ」
line = "「ルルゥ、また能力が暴走しているわ」"

[[dialogue]]
speaker = "ルルゥ"
# 「あっ！　ごめんなさい、またやっちゃったの……」
line = "「あっ！　ごめんなさい、またやっちゃったの……」"

[[dialogue]]
speaker = "フィオナ"
# 「ルルゥさんの魅了の力、本当に強力なんですね。密猟者にルルゥさんが狙われる理由も、分かる気がします」
line = "「ルルゥさんの魅了の力、本当に強力なんですね。密猟者にルルゥさんが狙われる理由も、分かる気がします」"

[[dialogue]]
speaker = "ルルゥ"
# 「そうなの。いつも狙われてて、気が休まる暇が無かった、なの」
line = "「そうなの。いつも狙われてて、気が休まる暇が無かった、なの」"

[[dialogue]]
speaker = "ルルゥ"
# 「でも、ご主人様が島にやってきて、ルルゥを守ってくれるようになったの。だから、今は昔よりも安心なの♪」
line = "「でも、ご主人様が島にやってきて、ルルゥを守ってくれるようになったの。だから、今は昔よりも安心なの♪」"

[[dialogue]]
speaker = "unk"
# ご主人様？
line = "ご主人様？"

[[dialogue]]
speaker = "マハムート"
# 「ゲシュペンス島に住んでいる唯一の人間のことよ。彼だけはモンスター娘から信頼と好意を寄せられているわ」
line = "「ゲシュペンス島に住んでいる唯一の人間のことよ。彼だけはモンスター娘から信頼と好意を寄せられているわ」"

[[dialogue]]
speaker = "ルルゥ"
# 「外から密猟者が襲ってきたり、おかしな事件が起きたりした時は、ご主人様がみんなを導いて解決してくれるの。島で楽しく暮らせるのはご主人様のおかげなの♪」
line = "「外から密猟者が襲ってきたり、おかしな事件が起きたりした時は、ご主人様がみんなを導いて解決してくれるの。島で楽しく暮らせるのはご主人様のおかげなの♪」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふっ。ルルゥさんはそのご主人様のことが大好きなんですね」
line = "「ふふっ。ルルゥさんはそのご主人様のことが大好きなんですね」"

[[dialogue]]
speaker = "ルルゥ"
# 「はいなの♪　とっても優しくて、ルルゥのことを大切に思ってくれてるの」
line = "「はいなの♪　とっても優しくて、ルルゥのことを大切に思ってくれてるの」"

[[dialogue]]
speaker = "ルルゥ"
# 「ニンゲンだけど、とってもいいニンゲンで……ルルゥはご主人様のことが大好きなの<emoji=heart04>」
line = "「ニンゲンだけど、とってもいいニンゲンで……ルルゥはご主人様のことが大好きなの<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 少し恥ずかしそうに、けれど隠す様子もなく、ご主人様への好意を口にするルルゥだった。
line = "少し恥ずかしそうに、けれど隠す様子もなく、ご主人様への好意を口にするルルゥだった。"

[[dialogue]]
speaker = "unk"
# その後も、ルルゥからゲシュペンス島のことや、モンスター娘たちのこと、日々起きている不思議な出来事などを聞きながら街を歩く。
line = "その後も、ルルゥからゲシュペンス島のことや、モンスター娘たちのこと、日々起きている不思議な出来事などを聞きながら街を歩く。"

[[dialogue]]
speaker = "unk"
# 話は尽きることなく盛り上がってはいたのだが、肝心の相手は見つけることが出来ずにいた。
line = "話は尽きることなく盛り上がってはいたのだが、肝心の相手は見つけることが出来ずにいた。"

[[dialogue]]
speaker = "unk"
# すると──
line = "すると──"

[[dialogue]]
speaker = "フィオナ"
# 「……新しい目撃情報が届いたみたいですね。カフェテリアでそれらしき人物を見た、と」
line = "「……新しい目撃情報が届いたみたいですね。カフェテリアでそれらしき人物を見た、と」"

[[dialogue]]
speaker = "マハムート"
# 「また学園に戻ったのかしら？　随分、あちらこちらをさまよっているようね」
line = "「また学園に戻ったのかしら？　随分、あちらこちらをさまよっているようね」"

[[dialogue]]
speaker = "フィオナ"
# 「ともかく行ってみましょう！」
line = "「ともかく行ってみましょう！」"
