[[dialogue]]
speaker = "unk"
# 第１話,天才藝術家の苦悩？,P
line = "第１話,天才藝術家の苦悩？,P"

[[dialogue]]
speaker = "unk"
# 黒ベア子が始めた『お祭り』によって、こちらの世界に迷い込んできた（自称）天才藝術家のアルテ。
line = "黒ベア子が始めた『お祭り』によって、こちらの世界に迷い込んできた（自称）天才藝術家のアルテ。"

[[dialogue]]
speaker = "unk"
# そんな彼女はこちらでの生活にもあっという間に慣れたようで、暇さえあれば星徒会室のソファに陣取ってくつろいでいるという余裕ぶりだった。
line = "そんな彼女はこちらでの生活にもあっという間に慣れたようで、暇さえあれば星徒会室のソファに陣取ってくつろいでいるという余裕ぶりだった。"

[[dialogue]]
speaker = "アルテ"
# 「なるほど……これは難しい問題です。これほどまでに私を悩ませた問題は初めてかもしれませんね」
line = "「なるほど……これは難しい問題です。これほどまでに私を悩ませた問題は初めてかもしれませんね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「初めても何も、あなた記憶喪失なんでしょ？　忘れてるだけかもしれないじゃない」
line = "「初めても何も、あなた記憶喪失なんでしょ？　忘れてるだけかもしれないじゃない」"

[[dialogue]]
speaker = "アルテ"
# 「ええまぁ。しかしこれほどの難問は、記憶を失うまでもおそらくなかったでしょう」
line = "「ええまぁ。しかしこれほどの難問は、記憶を失うまでもおそらくなかったでしょう」"

[[dialogue]]
speaker = "アルテ"
# 「私、記憶喪失なんですよね」
line = "「私、記憶喪失なんですよね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「もしかして、異世界に来たから……？」
line = "「もしかして、異世界に来たから……？」"

[[dialogue]]
speaker = "アルテ"
# 「いえ、元からです」
line = "「いえ、元からです」"

[[dialogue]]
speaker = "unk"
# アルテは夢幻美術館に所属するまでの記憶がなく、本当の名前もわからないのだという。
line = "アルテは夢幻美術館に所属するまでの記憶がなく、本当の名前もわからないのだという。"

[[dialogue]]
speaker = "unk"
# 普通、記憶喪失になったら少なからず不安を覚えそうなものだが、アルテはむしろ泰然としていた。
line = "普通、記憶喪失になったら少なからず不安を覚えそうなものだが、アルテはむしろ泰然としていた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あなた、本当に記憶喪失なんでしょうね……？　ま、いいわ。どんな問題なの？　この私がバシッと相談に乗ってあげる！」
line = "「あなた、本当に記憶喪失なんでしょうね……？　ま、いいわ。どんな問題なの？　この私がバシッと相談に乗ってあげる！」"

[[dialogue]]
speaker = "アルテ"
# 「自信満々ですが、ヴィーナスにこの問題が解決できるでしょうか？」
line = "「自信満々ですが、ヴィーナスにこの問題が解決できるでしょうか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「出来るわよ！　今までだって色んな問題にぶち当たってきたけど、ぜーんぶスパッと解決してきたんだから」
line = "「出来るわよ！　今までだって色んな問題にぶち当たってきたけど、ぜーんぶスパッと解決してきたんだから」"

[[dialogue]]
speaker = "アルテ"
# 「本当でしょうか？　疑わしいですね……」
line = "「本当でしょうか？　疑わしいですね……」"

[[dialogue]]
speaker = "マトイ"
# 「疑う気持ちも分かるけど、ヴィーナスがこれまでいろいろな問題を解決してきたのは本当だよ」
line = "「疑う気持ちも分かるけど、ヴィーナスがこれまでいろいろな問題を解決してきたのは本当だよ」"

[[dialogue]]
speaker = "マトイ"
# 「だから悩み事があるなら、気軽に相談していいと思う。私も及ばずながら協力するし」
line = "「だから悩み事があるなら、気軽に相談していいと思う。私も及ばずながら協力するし」"

[[dialogue]]
speaker = "unk"
# 俺たちも協力するから
line = "俺たちも協力するから"

[[dialogue]]
speaker = "unk"
# ヴィーナスの手に余るようだったら
line = "ヴィーナスの手に余るようだったら"

[[dialogue]]
speaker = "アルテ"
# 「ふむ、そこまで言うのなら相談してみましょう。『三大和牛』というものをご存知ですか？」
line = "「ふむ、そこまで言うのなら相談してみましょう。『三大和牛』というものをご存知ですか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ん？　まあ、詳しくは知らないけど……そういう呼び方があるってことくらいは」
line = "「ん？　まあ、詳しくは知らないけど……そういう呼び方があるってことくらいは」"

[[dialogue]]
speaker = "アルテ"
# 「その響きに興味を持って、私も調べてみました」
line = "「その響きに興味を持って、私も調べてみました」"

[[dialogue]]
speaker = "アルテ"
# 「柔らかく、きめ細やかな肉質で、甘く蕩けるような味わい……厳しい審査基準の元に選ばれた最高級のお肉たち」
line = "「柔らかく、きめ細やかな肉質で、甘く蕩けるような味わい……厳しい審査基準の元に選ばれた最高級のお肉たち」"

[[dialogue]]
speaker = "アルテ"
# 「その最高峰に位置づけられるのが三大和牛だそうです──」
line = "「その最高峰に位置づけられるのが三大和牛だそうです──」"

[[dialogue]]
speaker = "アルテ"
# 「しかし、こちらの文献によると、三大和牛として名乗りを上げるブランドは４つあるというではありませんか。これは一体どういうことなんでしょう？」
line = "「しかし、こちらの文献によると、三大和牛として名乗りを上げるブランドは４つあるというではありませんか。これは一体どういうことなんでしょう？」"

[[dialogue]]
speaker = "マトイ"
# 「文献って……ただのグルメ情報雑誌だよね、それ……。読んでるの、美術誌とかじゃなかったんだ……」
line = "「文献って……ただのグルメ情報雑誌だよね、それ……。読んでるの、美術誌とかじゃなかったんだ……」"

[[dialogue]]
speaker = "アルテ"
# 「それは問題の本質ではないでしょう。今大事なのは、<b>三大</b>なのに何故<b>４つ</b>もブランドがあるのか、ということです」
line = "「それは問題の本質ではないでしょう。今大事なのは、<b>三大</b>なのに何故<b>４つ</b>もブランドがあるのか、ということです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「稀によくある事よ。三大なんとかなのに４つあったり、四天王なのに５人いたりとかね」
line = "「稀によくある事よ。三大なんとかなのに４つあったり、四天王なのに５人いたりとかね」"

[[dialogue]]
speaker = "アルテ"
# 「意味が分かりません。やはりここは私がそれらのお肉を吟味して、真の三大和牛を決してあげなくては」
line = "「意味が分かりません。やはりここは私がそれらのお肉を吟味して、真の三大和牛を決してあげなくては」"

[[dialogue]]
speaker = "unk"
# 要するに食べてみたいってこと？
line = "要するに食べてみたいってこと？"

[[dialogue]]
speaker = "アルテ"
# 「そういうことです」
line = "「そういうことです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「悩みっていうから何かと思ったら……思ってた以上にどうでもいいことだったわ」
line = "「悩みっていうから何かと思ったら……思ってた以上にどうでもいいことだったわ」"

[[dialogue]]
speaker = "アルテ"
# 「相談してみろと言われたから相談したのに、酷い言いぐさですね。どんな問題でもスパッと解決してくれるのではなかったのですか？」
line = "「相談してみろと言われたから相談したのに、酷い言いぐさですね。どんな問題でもスパッと解決してくれるのではなかったのですか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あなたのそれは悩みでもなんでもなくて、ただの欲望っていうのよ」
line = "「あなたのそれは悩みでもなんでもなくて、ただの欲望っていうのよ」"

[[dialogue]]
speaker = "アルテ"
# 「ふむふむ、このご近所でも食べられるお店があるそうです。私の悩みを解決するためにも、このお店に連れて行ってもらうしかありませんね」
line = "「ふむふむ、このご近所でも食べられるお店があるそうです。私の悩みを解決するためにも、このお店に連れて行ってもらうしかありませんね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「はぁ……仕方がないわね。また今度連れて行ってあげるわ」
line = "「はぁ……仕方がないわね。また今度連れて行ってあげるわ」"

[[dialogue]]
speaker = "アルテ"
# 「また今度などという曖昧な言葉ではぐらかされる私じゃありません。今度とはいつのことか、はっきりさせてもらっていいでしょうか」
line = "「また今度などという曖昧な言葉ではぐらかされる私じゃありません。今度とはいつのことか、はっきりさせてもらっていいでしょうか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「今度は今度よ、大人しく待ってなさい。副会長と会計が別世界に転移しちゃったおかげで、いま星徒会の仕事が大変なことになってるんだから」
line = "「今度は今度よ、大人しく待ってなさい。副会長と会計が別世界に転移しちゃったおかげで、いま星徒会の仕事が大変なことになってるんだから」"

[[dialogue]]
speaker = "アルテ"
# 「会長さんとマトイが忙しそうに仕事をしているのは分かります。でもヴィーナスは先ほどから何をしているんですか？」
line = "「会長さんとマトイが忙しそうに仕事をしているのは分かります。でもヴィーナスは先ほどから何をしているんですか？」"

[[dialogue]]
speaker = "アルテ"
# 「お菓子を食べながら、お茶を飲んでくつろいでいるようにしか見えないのですが」
line = "「お菓子を食べながら、お茶を飲んでくつろいでいるようにしか見えないのですが」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私はいいのよ、なんたって元会長なんだから♪」
line = "「私はいいのよ、なんたって元会長なんだから♪」"

[[dialogue]]
speaker = "アルテ"
# 「元会長ならなおさら、業務には精通しているのでは？　ダラけていないで少しは手伝ったらどうです？」
line = "「元会長ならなおさら、業務には精通しているのでは？　ダラけていないで少しは手伝ったらどうです？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私が手伝うと却って仕事が増えるから、こういう時は何もしないのが仕事なのよ」
line = "「私が手伝うと却って仕事が増えるから、こういう時は何もしないのが仕事なのよ」"

[[dialogue]]
speaker = "アルテ"
# 「なるほど……ヴィーナスが肩書だけで、あまり役に立たない人なのだということがよく分かりました」
line = "「なるほど……ヴィーナスが肩書だけで、あまり役に立たない人なのだということがよく分かりました」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あなたこそ居候の身分なんだから、ぐうたらしてないで手伝おうとか思わないの？」
line = "「あなたこそ居候の身分なんだから、ぐうたらしてないで手伝おうとか思わないの？」"

[[dialogue]]
speaker = "アルテ"
# 「適材適所という言葉がありますからね。私はあくまで天才美少女藝術家、事務作業は他の方にお任せします」
line = "「適材適所という言葉がありますからね。私はあくまで天才美少女藝術家、事務作業は他の方にお任せします」"

[[dialogue]]
speaker = "アルテ"
# 「今はこうして英気を養いながら、やがて萌芽する芸術的衝動に備えているのです」
line = "「今はこうして英気を養いながら、やがて萌芽する芸術的衝動に備えているのです」"

[[dialogue]]
speaker = "マトイ"
# 「こ、これは大物藝術家の風格……！？」
line = "「こ、これは大物藝術家の風格……！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「マトイ、騙されてるわよ。そんなこと言って、だらけてばかりで筆をとる気配すらないじゃない」
line = "「マトイ、騙されてるわよ。そんなこと言って、だらけてばかりで筆をとる気配すらないじゃない」"

[[dialogue]]
speaker = "アルテ"
# 「天才美少女藝術家は、ここぞという時にこそ活躍するものなのです」
line = "「天才美少女藝術家は、ここぞという時にこそ活躍するものなのです」"

[[dialogue]]
speaker = "アルテ"
# 「ま、その気になったら半日で歴史に名を残すような作品を作れる──ような気がしますけどね」
line = "「ま、その気になったら半日で歴史に名を残すような作品を作れる──ような気がしますけどね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「どこからその自信が湧いてくるのよ」
line = "「どこからその自信が湧いてくるのよ」"

[[dialogue]]
speaker = "unk"
# アルテとヴィーナス、仲良くなったなぁ……
line = "アルテとヴィーナス、仲良くなったなぁ……"

[[dialogue]]
speaker = "マトイ"
# 「なんだかんだこっちの世界にも馴染んでくれて安心だね」
line = "「なんだかんだこっちの世界にも馴染んでくれて安心だね」"

[[dialogue]]
speaker = "アルテ"
# 「おかげさまで。私はとっても繊細な性格なので苦労はしましたが」
line = "「おかげさまで。私はとっても繊細な性格なので苦労はしましたが」"

[[dialogue]]
speaker = "ヴィーナス"
# 「繊細な性格の人間が、星徒会室のソファを占拠してぐうたらはしないのよね」
line = "「繊細な性格の人間が、星徒会室のソファを占拠してぐうたらはしないのよね」"

[[dialogue]]
speaker = "アルテ"
# 「居心地がいいもので。これは夢幻美術館の館長室のソファに匹敵するかもしれませんね……むにゃむにゃ……」
line = "「居心地がいいもので。これは夢幻美術館の館長室のソファに匹敵するかもしれませんね……むにゃむにゃ……」"

[[dialogue]]
speaker = "unk"
# ソファに寝転がってグルメ雑誌を広げるアルテは、繊細さとは正反対に位置する存在だった。
line = "ソファに寝転がってグルメ雑誌を広げるアルテは、繊細さとは正反対に位置する存在だった。"

[[dialogue]]
speaker = "unk"
# だけど１人異世界に飛ばされて、不安に泣くよりよほどいい。こちらの世界での生活に馴染んだ様子は安心感さえ与えてくれる。
line = "だけど１人異世界に飛ばされて、不安に泣くよりよほどいい。こちらの世界での生活に馴染んだ様子は安心感さえ与えてくれる。"

[[dialogue]]
speaker = "unk"
# ヴィーナスとのやり取りを見ながら同じことを考えたのか、俺とマトイは思わずクスリと笑いあったのだった。
line = "ヴィーナスとのやり取りを見ながら同じことを考えたのか、俺とマトイは思わずクスリと笑いあったのだった。"
