[[dialogue]]
speaker = "unk"
# 俺とレティシアがお互いに『好き』であることを伝えあってから、数日が経過した。
line = "俺とレティシアがお互いに『好き』であることを伝えあってから、数日が経過した。"

[[dialogue]]
speaker = "unk"
# レティシアとは正式に交際の約束を交わしたわけではない。一時的な協力関係を了承してもらっただけで、明日にも敵対する可能性は大いにある。
line = "レティシアとは正式に交際の約束を交わしたわけではない。一時的な協力関係を了承してもらっただけで、明日にも敵対する可能性は大いにある。"

[[dialogue]]
speaker = "unk"
# けれど普通の男女の友人よりは、お互いのことを意識している。敵のような味方のような、友人のような恋人のような……
line = "けれど普通の男女の友人よりは、お互いのことを意識している。敵のような味方のような、友人のような恋人のような……"

[[dialogue]]
speaker = "unk"
# そんな曖昧な距離感を保っていたのだが、ある夜、転機が訪れた──
line = "そんな曖昧な距離感を保っていたのだが、ある夜、転機が訪れた──"

[[dialogue]]
speaker = "レティシア"
# 「こんな夜遅くに、魔王の部屋を訪れるのは初めてね」
line = "「こんな夜遅くに、魔王の部屋を訪れるのは初めてね」"

[[dialogue]]
speaker = "unk"
# 極星学園生の外出は、ある程度緩和されたとはいえ制限されている。レティシアが『俺に用事がある』というから、こうして特別に許可をしたのだが……
line = "極星学園生の外出は、ある程度緩和されたとはいえ制限されている。レティシアが『俺に用事がある』というから、こうして特別に許可をしたのだが……"

[[dialogue]]
speaker = "レティシア"
# 「用事といっても、大したことじゃないのだけど……よかったら、私に教えてくれないかしら？」
line = "「用事といっても、大したことじゃないのだけど……よかったら、私に教えてくれないかしら？」"

[[dialogue]]
speaker = "クロト"
# 「……何を？」
line = "「……何を？」"

[[dialogue]]
speaker = "レティシア"
# 「決まってるわ。お互いを意識している異性が２人きりですること。経験しておきたいの」
line = "「決まってるわ。お互いを意識している異性が２人きりですること。経験しておきたいの」"

[[dialogue]]
speaker = "unk"
# レティシアの口から似合わない言葉が飛び出て、驚いた。
line = "レティシアの口から似合わない言葉が飛び出て、驚いた。"

[[dialogue]]
speaker = "レティシア"
# 「貴方は私を『好き』と言ってくれた。私も、貴方のことが──５番目くらいには『好き』」
line = "「貴方は私を『好き』と言ってくれた。私も、貴方のことが──５番目くらいには『好き』」"

[[dialogue]]
speaker = "unk"
# 極星学園の幼なじみの次くらい──そういう意味での５番目。嫌な気はしない。今のレティシアなりの、最大限の好意を伝えられている気がするから。
line = "極星学園の幼なじみの次くらい──そういう意味での５番目。嫌な気はしない。今のレティシアなりの、最大限の好意を伝えられている気がするから。"

[[dialogue]]
speaker = "レティシア"
# 「ルヴィの説得のために、私は変わらないといけないわ。必要がないと切り捨てていた、たくさんのことを経験しておきたい」
line = "「ルヴィの説得のために、私は変わらないといけないわ。必要がないと切り捨てていた、たくさんのことを経験しておきたい」"

[[dialogue]]
speaker = "レティシア"
# 「だから教えて？　お互いを憎からず想っている男女がする、エッチなこと」
line = "「だから教えて？　お互いを憎からず想っている男女がする、エッチなこと」"

[[dialogue]]
speaker = "クロト"
# 「……教えられるかどうか。俺だって初めてなんだ」
line = "「……教えられるかどうか。俺だって初めてなんだ」"

[[dialogue]]
speaker = "レティシア"
# 「あら。あんなにたくさん女の子がいるから、てっきりプレイボーイかと思ってたのに……でも別に構わないわ」
line = "「あら。あんなにたくさん女の子がいるから、てっきりプレイボーイかと思ってたのに……でも別に構わないわ」"

[[dialogue]]
speaker = "レティシア"
# 「教えてくれなくてもいい。私と一緒に、学んでくれる？」
line = "「教えてくれなくてもいい。私と一緒に、学んでくれる？」"

[[dialogue]]
speaker = "unk"
# レティシアのまっすぐな瞳に、俺は頷いた──
line = "レティシアのまっすぐな瞳に、俺は頷いた──"

[[dialogue]]
speaker = "unk"
# レティシアの希望で、俺が仰向けになる騎乗位をすることになった。それにしても……
line = "レティシアの希望で、俺が仰向けになる騎乗位をすることになった。それにしても……"

[[dialogue]]
speaker = "クロト"
# 「どうして戦闘服に……？」
line = "「どうして戦闘服に……？」"

[[dialogue]]
speaker = "レティシア"
# 「いざという時に、あなたの寝首をかけるかも──なんてね？」
line = "「いざという時に、あなたの寝首をかけるかも──なんてね？」"

[[dialogue]]
speaker = "レティシア"
# 「こっちの方が痛みに耐性があるの。初めては痛いって言うし……あなたも私が苦しい顔をしていない方が、気が楽でしょう？」
line = "「こっちの方が痛みに耐性があるの。初めては痛いって言うし……あなたも私が苦しい顔をしていない方が、気が楽でしょう？」"

[[dialogue]]
speaker = "unk"
# とても合理的な理由での変身だった──けれど、俺のことまで考えて気配りをしてくれたことは嬉しい。
line = "とても合理的な理由での変身だった──けれど、俺のことまで考えて気配りをしてくれたことは嬉しい。"

[[dialogue]]
speaker = "レティシア"
# 「……凄いのね。あなたのそれ……すごく大きくなってる」
line = "「……凄いのね。あなたのそれ……すごく大きくなってる」"

[[dialogue]]
speaker = "レティシア"
# 「私の身体で、興奮してくれているのね」
line = "「私の身体で、興奮してくれているのね」"

[[dialogue]]
speaker = "unk"
# 普段からスタイルのいい女の子だとは思っていたけれど……服をはだけると一段と凄い。
line = "普段からスタイルのいい女の子だとは思っていたけれど……服をはだけると一段と凄い。"

[[dialogue]]
speaker = "unk"
# 胸はたっぷりと大きく、腰はくびれて、俺の体にもっちりと乗ったお尻も柔らかくて──興奮するなという方が無理な話だ。
line = "胸はたっぷりと大きく、腰はくびれて、俺の体にもっちりと乗ったお尻も柔らかくて──興奮するなという方が無理な話だ。"

[[dialogue]]
speaker = "レティシア"
# 「性知識は、一応あるの。ルヴィが教えてくれたから」
line = "「性知識は、一応あるの。ルヴィが教えてくれたから」"

[[dialogue]]
speaker = "クロト"
# 「……ルヴィネが？　意外だ」
line = "「……ルヴィネが？　意外だ」"

[[dialogue]]
speaker = "レティシア"
# 「心配してくれてたんだと思う。極星学園に入学した頃から私、男の子に告白される機会が増えていたから」
line = "「心配してくれてたんだと思う。極星学園に入学した頃から私、男の子に告白される機会が増えていたから」"

[[dialogue]]
speaker = "レティシア"
# 「『いつか好きな男の子とする時のために』って……あの時は必要のない無駄な知識と思っていたけれど。今は感謝ね」
line = "「『いつか好きな男の子とする時のために』って……あの時は必要のない無駄な知識と思っていたけれど。今は感謝ね」"

[[dialogue]]
speaker = "レティシア"
# 「勃起した男性器を、女性器に入れて、出し入れして……男性が我慢できなくなったら、セックスはおわり。これで合ってるかしら？」
line = "「勃起した男性器を、女性器に入れて、出し入れして……男性が我慢できなくなったら、セックスはおわり。これで合ってるかしら？」"

[[dialogue]]
speaker = "unk"
# 合っているけれど、淡白すぎる……
line = "合っているけれど、淡白すぎる……"

[[dialogue]]
speaker = "レティシア"
# 「男性器じゃ、だめ？　じゃあどう言ったらいいかしら。教えて？」
line = "「男性器じゃ、だめ？　じゃあどう言ったらいいかしら。教えて？」"

[[dialogue]]
speaker = "unk"
# 俺より歳上で余裕はあるけれど、性のことをほとんど何も知らないレティシア。きっと教科書に載っているような事柄しか知らないはずだ。
line = "俺より歳上で余裕はあるけれど、性のことをほとんど何も知らないレティシア。きっと教科書に載っているような事柄しか知らないはずだ。"

[[dialogue]]
speaker = "unk"
# こんなまっさらな初心な女の子に、余計なことを教えていいのだろうかと思いつつ──
line = "こんなまっさらな初心な女の子に、余計なことを教えていいのだろうかと思いつつ──"

[[dialogue]]
speaker = "レティシア"
# 「……チ○ポ？　あなたのそれ、チ○ポって言ってほしいの？　それで女性器は──ええ。わかったわ。言う通りにしてあげる」
line = "「……チ○ポ？　あなたのそれ、チ○ポって言ってほしいの？　それで女性器は──ええ。わかったわ。言う通りにしてあげる」"

[[dialogue]]
speaker = "レティシア"
# 「あなたのチ○ポ……私のおま○こに入れるから。ジッとしてて……」
line = "「あなたのチ○ポ……私のおま○こに入れるから。ジッとしてて……」"

[[dialogue]]
speaker = "レティシア"
# 「はぁ、あぁっ……<emoji=heart04>　ん、んんんうっ……<emoji=heart04>」
line = "「はぁ、あぁっ……<emoji=heart04>　ん、んんんうっ……<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「全部入った……ん、ぅ<emoji=heart04>　すごい……内側から、ぐいぐい広げられて……ぞくぞくする……」
line = "「全部入った……ん、ぅ<emoji=heart04>　すごい……内側から、ぐいぐい広げられて……ぞくぞくする……」"

[[dialogue]]
speaker = "unk"
# レティシアの性器は、すでにしっとりと濡れていた。興奮していたのは、俺だけではなかったみたいだ。
line = "レティシアの性器は、すでにしっとりと濡れていた。興奮していたのは、俺だけではなかったみたいだ。"

[[dialogue]]
speaker = "レティシア"
# 「チ○ポ、硬い……<emoji=heart04>　あ、これ……嫌じゃない……<emoji=heart04>　あったかいのが、お腹の奥で、じんわり広がって……<emoji=heart04>」
line = "「チ○ポ、硬い……<emoji=heart04>　あ、これ……嫌じゃない……<emoji=heart04>　あったかいのが、お腹の奥で、じんわり広がって……<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「動いて、あげるっ……射精しやすいように、いっぱいこすって、あげるからっ……んんぅっ<emoji=heart04>」
line = "「動いて、あげるっ……射精しやすいように、いっぱいこすって、あげるからっ……んんぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「はぁっ……はぁあっ……<emoji=heart04>　あっ……はぁっ……ふぅっ……んんんっ……<emoji=heart04>　はぁ、あ、ぁああっ……<emoji=heart04>」
line = "「はぁっ……はぁあっ……<emoji=heart04>　あっ……はぁっ……ふぅっ……んんんっ……<emoji=heart04>　はぁ、あ、ぁああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 大きく股を開いたレティシアに、ゆっくりとストロークをされる。
line = "大きく股を開いたレティシアに、ゆっくりとストロークをされる。"

[[dialogue]]
speaker = "unk"
# 張り詰めたペニスを、柔らかい膣肉できつく締めあげられ、思わず腰が浮くほどの気持ちよさ。
line = "張り詰めたペニスを、柔らかい膣肉できつく締めあげられ、思わず腰が浮くほどの気持ちよさ。"

[[dialogue]]
speaker = "レティシア"
# 「あっ……んんっ……<emoji=heart04>　ふふっ♪　あなた、すごく余裕の、なさそうな顔してる……チ○ポ、気持ちいいの？」
line = "「あっ……んんっ……<emoji=heart04>　ふふっ♪　あなた、すごく余裕の、なさそうな顔してる……チ○ポ、気持ちいいの？」"

[[dialogue]]
speaker = "レティシア"
# 「おま○こにチ○ポの出し入れ……これで合ってる？　男の子って、自分でするん、でしょう……？　私、下手じゃない……？　……んぅっ<emoji=heart04>」
line = "「おま○こにチ○ポの出し入れ……これで合ってる？　男の子って、自分でするん、でしょう……？　私、下手じゃない……？　……んぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 自慰なんて比べ物にならない。レティシアに包まれて、しごかれる方が圧倒的に気持ちいいことを伝えた──
line = "自慰なんて比べ物にならない。レティシアに包まれて、しごかれる方が圧倒的に気持ちいいことを伝えた──"

[[dialogue]]
speaker = "レティシア"
# 「そうっ……<emoji=heart04>　なんだ、セックスって、案外簡単、なのね……よかった……はぁ、んんっ……<emoji=heart04>」
line = "「そうっ……<emoji=heart04>　なんだ、セックスって、案外簡単、なのね……よかった……はぁ、んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「チ○ポ、いっぱいシコシコしてあげるっ……んぅ<emoji=heart04>　はぁ、はぁあっ……<emoji=heart04>　私のおま○こでたくさんっ……んんぅ、ぁ、あぁあっ……<emoji=heart04>」
line = "「チ○ポ、いっぱいシコシコしてあげるっ……んぅ<emoji=heart04>　はぁ、はぁあっ……<emoji=heart04>　私のおま○こでたくさんっ……んんぅ、ぁ、あぁあっ……<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「男の子は……手でしごく、のよね……？　だったら、締めつけも、強い方が、いいのかしらっ……？　んんんっ……<emoji=heart04>」
line = "「男の子は……手でしごく、のよね……？　だったら、締めつけも、強い方が、いいのかしらっ……？　んんんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ぎゅっ、ぎゅっ──とレティシアの膣内の締まりが強くなる。ピストンをしながら、俺のペニスへ刺激を増やしてくれていた。
line = "ぎゅっ、ぎゅっ──とレティシアの膣内の締まりが強くなる。ピストンをしながら、俺のペニスへ刺激を増やしてくれていた。"

[[dialogue]]
speaker = "レティシア"
# 「あっ……ふふふっ♪　今の、いいのね？　チ○ポが震えてるの、よくわかる……んんぅっ……<emoji=heart04>」
line = "「あっ……ふふふっ♪　今の、いいのね？　チ○ポが震えてるの、よくわかる……んんぅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「おま○こに力を、込めてっ……<emoji=heart04>　ぎゅ、ぅっ<emoji=heart04>　ぎゅ、ぅっ<emoji=heart04>　んんっ……こんな、感じ……？　はぁ、んんっ……<emoji=heart04>」
line = "「おま○こに力を、込めてっ……<emoji=heart04>　ぎゅ、ぅっ<emoji=heart04>　ぎゅ、ぅっ<emoji=heart04>　んんっ……こんな、感じ……？　はぁ、んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「あ──ぁ、あっ<emoji=heart04>　チ○ポ硬いっ……<emoji=heart04>　奥のところ、好き、かもっ……<emoji=heart04>　奥に、当てるとっ……あ、あぁ<emoji=heart04>　んんっ……<emoji=heart04>」
line = "「あ──ぁ、あっ<emoji=heart04>　チ○ポ硬いっ……<emoji=heart04>　奥のところ、好き、かもっ……<emoji=heart04>　奥に、当てるとっ……あ、あぁ<emoji=heart04>　んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# きっとレティシアの性格からして、自慰も経験なんてないはずだ。自身の性器の、気持ちいい所に、俺のペニスを導いてポイントを探っている──
line = "きっとレティシアの性格からして、自慰も経験なんてないはずだ。自身の性器の、気持ちいい所に、俺のペニスを導いてポイントを探っている──"

[[dialogue]]
speaker = "unk"
# 夢中でお尻を上下する彼女のおっぱいもダイナミックに揺れて、俺もどんどん昂っていく。
line = "夢中でお尻を上下する彼女のおっぱいもダイナミックに揺れて、俺もどんどん昂っていく。"

[[dialogue]]
speaker = "レティシア"
# 「……おっぱい、好き？　んんっ……はぁっ……<emoji=heart04>　いいのよ、しっかり見て……<emoji=heart04>　あなたなら……見られるの、嫌いじゃないっ……から<emoji=heart04>」
line = "「……おっぱい、好き？　んんっ……はぁっ……<emoji=heart04>　いいのよ、しっかり見て……<emoji=heart04>　あなたなら……見られるの、嫌いじゃないっ……から<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「手、伸ばしてっ……触っていいから……はぁ、あぁっ<emoji=heart04>」
line = "「手、伸ばしてっ……触っていいから……はぁ、あぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# レティシアの大きな胸は、ずっしりと重たくて、手のひらに吸い付く。柔らかくてハリがあって、興奮せずにいられない。
line = "レティシアの大きな胸は、ずっしりと重たくて、手のひらに吸い付く。柔らかくてハリがあって、興奮せずにいられない。"

[[dialogue]]
speaker = "レティシア"
# 「あぁ、ああぁっ……はぁあ、んんぅ<emoji=heart04>　セックス、気持ちいい……<emoji=heart04>　んんっ……おっぱい、もっとぎゅって、して……？」
line = "「あぁ、ああぁっ……はぁあ、んんぅ<emoji=heart04>　セックス、気持ちいい……<emoji=heart04>　んんっ……おっぱい、もっとぎゅって、して……？」"

[[dialogue]]
speaker = "レティシア"
# 「んんぅっ<emoji=heart04>　は、あぁっ<emoji=heart04>　それ、いいっ……先っぽ、好きっ──ぁ、あっ<emoji=heart04>　んんんっ<emoji=heart04>」
line = "「んんぅっ<emoji=heart04>　は、あぁっ<emoji=heart04>　それ、いいっ……先っぽ、好きっ──ぁ、あっ<emoji=heart04>　んんんっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 乳首を指先で転がすと、心地よさそうに口角を上げるレティシア。
line = "乳首を指先で転がすと、心地よさそうに口角を上げるレティシア。"

[[dialogue]]
speaker = "unk"
# とろんと蕩けた瞳が、普段の彼女とのギャップになって、たまらない。
line = "とろんと蕩けた瞳が、普段の彼女とのギャップになって、たまらない。"

[[dialogue]]
speaker = "レティシア"
# 「ね、ねぇっ……<emoji=heart04>　もっとして欲しいこと、ない……？　んんぅ<emoji=heart04>　は、あぁっ<emoji=heart04>　んんっ……<emoji=heart04>　何でも、言って……<emoji=heart04>」
line = "「ね、ねぇっ……<emoji=heart04>　もっとして欲しいこと、ない……？　んんぅ<emoji=heart04>　は、あぁっ<emoji=heart04>　んんっ……<emoji=heart04>　何でも、言って……<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「教えてっ……チ○ポが喜ぶことっ、教えて……？　してあげるっ……あ、あぁっ<emoji=heart04>　はぁ、んぅっ<emoji=heart04>」
line = "「教えてっ……チ○ポが喜ぶことっ、教えて……？　してあげるっ……あ、あぁっ<emoji=heart04>　はぁ、んぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 『好き』とたくさん言ってほしい──俺は彼女のおっぱいを揉みしだきながら、そう伝えた。
line = "『好き』とたくさん言ってほしい──俺は彼女のおっぱいを揉みしだきながら、そう伝えた。"

[[dialogue]]
speaker = "レティシア"
# 「すっ……好きっ……<emoji=heart04>　セックス、好き……<emoji=heart04>　気持ちいいの、好き……<emoji=heart04>　あ、ぁっ！？　チ○ポ、ぐいぐいって、大きくっ……んんんぅ<emoji=heart04>」
line = "「すっ……好きっ……<emoji=heart04>　セックス、好き……<emoji=heart04>　気持ちいいの、好き……<emoji=heart04>　あ、ぁっ！？　チ○ポ、ぐいぐいって、大きくっ……んんんぅ<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「そういうこと……？　口でちゃんと伝えたら、嬉しい……ってこと……？　ええ、わかったわ……んんぅ<emoji=heart04>　はぁ、あぁあっ……<emoji=heart04>」
line = "「そういうこと……？　口でちゃんと伝えたら、嬉しい……ってこと……？　ええ、わかったわ……んんぅ<emoji=heart04>　はぁ、あぁあっ……<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「好き……好きよ……<emoji=heart04>　隙間なくくっついて、あったかいの……好き……<emoji=heart04>　安心する……ふわふわする……あ、あぁっ<emoji=heart04>　好き、好きっ……<emoji=heart04>」
line = "「好き……好きよ……<emoji=heart04>　隙間なくくっついて、あったかいの……好き……<emoji=heart04>　安心する……ふわふわする……あ、あぁっ<emoji=heart04>　好き、好きっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# レティシアと繋がっているところがどんどん熱くなっていく。彼女も、絶頂に向かっている──
line = "レティシアと繋がっているところがどんどん熱くなっていく。彼女も、絶頂に向かっている──"

[[dialogue]]
speaker = "レティシア"
# 「ご、ごめんなさいっ……ゆっくりじゃ、もうだめっ……速く、し、したいっ……だ、だめ……？」
line = "「ご、ごめんなさいっ……ゆっくりじゃ、もうだめっ……速く、し、したいっ……だ、だめ……？」"

[[dialogue]]
speaker = "unk"
# リードする側なのに、俺の許可を仰いでくる。
line = "リードする側なのに、俺の許可を仰いでくる。"

[[dialogue]]
speaker = "unk"
# 歳上で、妖艶で、ミステリアスなのに……甘えてくる。彼女は元々、そういう女の子なんだろう。
line = "歳上で、妖艶で、ミステリアスなのに……甘えてくる。彼女は元々、そういう女の子なんだろう。"

[[dialogue]]
speaker = "unk"
# そんなレティシアが愛おしくて──
line = "そんなレティシアが愛おしくて──"

[[dialogue]]
speaker = "クロト"
# 「速くしてくれると嬉しいな──レティシアっ……！」
line = "「速くしてくれると嬉しいな──レティシアっ……！」"

[[dialogue]]
speaker = "レティシア"
# 「…………うんっ<emoji=heart04>」
line = "「…………うんっ<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「あっあっ、あっあっあっ<emoji=heart04>　んんっ、んっんっんっんっ<emoji=heart04>　ふぅ、んんっ<emoji=heart04>　んんぁ、あ、あぁぁっ<emoji=heart04>　あぁぁあっ<emoji=heart04>」
line = "「あっあっ、あっあっあっ<emoji=heart04>　んんっ、んっんっんっんっ<emoji=heart04>　ふぅ、んんっ<emoji=heart04>　んんぁ、あ、あぁぁっ<emoji=heart04>　あぁぁあっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# お尻が波打つくらいの激しい騎乗位ピストンが、ペニスに襲い掛かった。
line = "お尻が波打つくらいの激しい騎乗位ピストンが、ペニスに襲い掛かった。"

[[dialogue]]
speaker = "レティシア"
# 「はぁ、あっあっあっ<emoji=heart04>　チ○ポ、すごいっ、あ、あっ<emoji=heart04>　ガチガチ、でっ<emoji=heart04>　あったかいっ……奥、ぐりぐりって──ぁ、ああぁっ<emoji=heart04>」
line = "「はぁ、あっあっあっ<emoji=heart04>　チ○ポ、すごいっ、あ、あっ<emoji=heart04>　ガチガチ、でっ<emoji=heart04>　あったかいっ……奥、ぐりぐりって──ぁ、ああぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「す、好きっ……<emoji=heart04>　これ、好きっ……<emoji=heart04>　あなたの、硬いチ○ポっ<emoji=heart04>　速い出し入れ、気持ち、いいっ<emoji=heart04>　あっあっあっ、あぁ、あぁっ<emoji=heart04>」
line = "「す、好きっ……<emoji=heart04>　これ、好きっ……<emoji=heart04>　あなたの、硬いチ○ポっ<emoji=heart04>　速い出し入れ、気持ち、いいっ<emoji=heart04>　あっあっあっ、あぁ、あぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 快感を貪るように、かつて得られなかった温もりを離さないとばかりに、強い杭打ちをするレティシアが、エロくて、可愛くて、仕方がない。
line = "快感を貪るように、かつて得られなかった温もりを離さないとばかりに、強い杭打ちをするレティシアが、エロくて、可愛くて、仕方がない。"

[[dialogue]]
speaker = "unk"
# 紅潮した表情。揺れるおっぱい。ペニスを飲み込む女性器──全てから目が離せなかった。
line = "紅潮した表情。揺れるおっぱい。ペニスを飲み込む女性器──全てから目が離せなかった。"

[[dialogue]]
speaker = "レティシア"
# 「はぁっふぅっんんんっ<emoji=heart04>　あっあっあっ<emoji=heart04>　んんぅ、はぁ、あっあっあっあっあっ<emoji=heart04>　と、止まら、ないのっ<emoji=heart04>　お尻、止まらないっ……<emoji=heart04>」
line = "「はぁっふぅっんんんっ<emoji=heart04>　あっあっあっ<emoji=heart04>　んんぅ、はぁ、あっあっあっあっあっ<emoji=heart04>　と、止まら、ないのっ<emoji=heart04>　お尻、止まらないっ……<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「気持ちいいっ<emoji=heart04>　チ○ポ気持ちいいっ<emoji=heart04>　セックス好きっ……おま○こで繋がるの、好きっ……ぁ、あぁあっ<emoji=heart04>　はあ、あ、あぁっ<emoji=heart04>」
line = "「気持ちいいっ<emoji=heart04>　チ○ポ気持ちいいっ<emoji=heart04>　セックス好きっ……おま○こで繋がるの、好きっ……ぁ、あぁあっ<emoji=heart04>　はあ、あ、あぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 初めてとは思えないほどに乱れるレティシアが可愛くて、もっと感じさせてあげたくなる。
line = "初めてとは思えないほどに乱れるレティシアが可愛くて、もっと感じさせてあげたくなる。"

[[dialogue]]
speaker = "unk"
# 俺は結合部の少し上にある、クリトリスをそっと撫でた。
line = "俺は結合部の少し上にある、クリトリスをそっと撫でた。"

[[dialogue]]
speaker = "レティシア"
# 「──んんんぅうっ！？　あ、あ、ぁあっ<emoji=heart04>　今の、すごっ──んんんっ<emoji=heart04>　そこ、何っ……それ、好きっ……あ、あぁあっ<emoji=heart04>」
line = "「──んんんぅうっ！？　あ、あ、ぁあっ<emoji=heart04>　今の、すごっ──んんんっ<emoji=heart04>　そこ、何っ……それ、好きっ……あ、あぁあっ<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「もっとしてっ……そこ、触って──あ、あぁあっ<emoji=heart04>　ん、んんぅっ<emoji=heart04>　ふぁ、あ、あぁ、あぁああっ<emoji=heart04>　んん～っ<emoji=heart04>」
line = "「もっとしてっ……そこ、触って──あ、あぁあっ<emoji=heart04>　ん、んんぅっ<emoji=heart04>　ふぁ、あ、あぁ、あぁああっ<emoji=heart04>　んん～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# レティシアは敏感な方なのかもしれない。優しく、けれど小刻みに速く。クリトリスへ刺激を続ける。
line = "レティシアは敏感な方なのかもしれない。優しく、けれど小刻みに速く。クリトリスへ刺激を続ける。"

[[dialogue]]
speaker = "レティシア"
# 「ひぁ、あ、あぁっ<emoji=heart04>　あ、あ、ぁ、ううぅっ<emoji=heart04>　あ、あ、あぁあ、あ、あ、ぁ、ああっ<emoji=heart04>　んんぅっ<emoji=heart04>　気持ちいい、気持ちいい、のっ<emoji=heart04>」
line = "「ひぁ、あ、あぁっ<emoji=heart04>　あ、あ、ぁ、ううぅっ<emoji=heart04>　あ、あ、あぁあ、あ、あ、ぁ、ああっ<emoji=heart04>　んんぅっ<emoji=heart04>　気持ちいい、気持ちいい、のっ<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「はぁ、あ、あぁああっ<emoji=heart04>　チ○ポ、びくびくっ<emoji=heart04>　ずっとしてるっ……こ、これっ<emoji=heart04>　もう、で、出そう、なのっ……？」
line = "「はぁ、あ、あぁああっ<emoji=heart04>　チ○ポ、びくびくっ<emoji=heart04>　ずっとしてるっ……こ、これっ<emoji=heart04>　もう、で、出そう、なのっ……？」"

[[dialogue]]
speaker = "unk"
# 愛液をしとどにまぶされて、狭い膣内でこすられ続けて、俺も限界が近い──
line = "愛液をしとどにまぶされて、狭い膣内でこすられ続けて、俺も限界が近い──"

[[dialogue]]
speaker = "レティシア"
# 「はぁ、はぁ、はあ、ぁああっ<emoji=heart04>　あ、あっ？　私も、な、何か、来るっ？　何か来るっ<emoji=heart04>　魔王、私、変なの、おま○こ、切なく、なって──んんんっ<emoji=heart04>」
line = "「はぁ、はぁ、はあ、ぁああっ<emoji=heart04>　あ、あっ？　私も、な、何か、来るっ？　何か来るっ<emoji=heart04>　魔王、私、変なの、おま○こ、切なく、なって──んんんっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 絶頂が近いんだ、と教えてあげた。教科書には載っていない性の知識を、レティシアはすぐに吸収した。
line = "絶頂が近いんだ、と教えてあげた。教科書には載っていない性の知識を、レティシアはすぐに吸収した。"

[[dialogue]]
speaker = "レティシア"
# 「イ、イクっ？　これがっ……う、んっ<emoji=heart04>　あ、あ、ああっ<emoji=heart04>　イク<emoji=heart04>　イクっ<emoji=heart04>　イクのっ<emoji=heart04>　あなたのチ○ポで、おま○こ、イク、ぅっ<emoji=heart04>」
line = "「イ、イクっ？　これがっ……う、んっ<emoji=heart04>　あ、あ、ああっ<emoji=heart04>　イク<emoji=heart04>　イクっ<emoji=heart04>　イクのっ<emoji=heart04>　あなたのチ○ポで、おま○こ、イク、ぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「ふあぁあっあっあっあっあっ──イク<emoji=heart04>　イクっ<emoji=heart04>　イクイクっ<emoji=heart04>　イクイクイクイクっ──あ、ぁ、あぁあっ！」
line = "「ふあぁあっあっあっあっあっ──イク<emoji=heart04>　イクっ<emoji=heart04>　イクイクっ<emoji=heart04>　イクイクイクイクっ──あ、ぁ、あぁあっ！」"

[[dialogue]]
speaker = "レティシア"
# 「んん、んんんぅぅぅうう～～～～っ──<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「んん、んんんぅぅぅうう～～～～っ──<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「あぁあぁあぁあぁあぁあぁああああ～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あぁあぁあぁあぁあぁあぁああああ～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「あ、あぁあっ──んんんぅっ！　んん、んんう～っ<emoji=heart04>　あったかいのが、たくさんっ……出て、る、ぅっ……あ、あぁああっ……<emoji=heart04>」
line = "「あ、あぁあっ──んんんぅっ！　んん、んんう～っ<emoji=heart04>　あったかいのが、たくさんっ……出て、る、ぅっ……あ、あぁああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ずっと堰き止めていた迸りが、レティシアのお腹で弾け続ける。
line = "ずっと堰き止めていた迸りが、レティシアのお腹で弾け続ける。"

[[dialogue]]
speaker = "レティシア"
# 「ふうぅっ<emoji=heart04>　ぁ、ああぁあっ……はぁ、あぁっ……<emoji=heart04>　んん、んぁ、ああぁっ……<emoji=heart04>」
line = "「ふうぅっ<emoji=heart04>　ぁ、ああぁあっ……はぁ、あぁっ……<emoji=heart04>　んん、んぁ、ああぁっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# どくん、どくんと撃ち放つたび、レティシアの身体が痙攣を繰り返す。
line = "どくん、どくんと撃ち放つたび、レティシアの身体が痙攣を繰り返す。"

[[dialogue]]
speaker = "unk"
# 一滴残らず射精しろと言われているみたいに、ペニスを何度も何度も女性器で揉みしだかれて──
line = "一滴残らず射精しろと言われているみたいに、ペニスを何度も何度も女性器で揉みしだかれて──"

[[dialogue]]
speaker = "レティシア"
# 「んんぁぁっ……はああぁっ……ふぅうー……<emoji=heart04>」
line = "「んんぁぁっ……はああぁっ……ふぅうー……<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「抜け、ちゃった……んんぅ……<emoji=heart04>　すごかった……チ○ポから、びゅうびゅうって……<emoji=heart04>」
line = "「抜け、ちゃった……んんぅ……<emoji=heart04>　すごかった……チ○ポから、びゅうびゅうって……<emoji=heart04>」"

[[dialogue]]
speaker = "レティシア"
# 「いつ止まるのか、わからないくらい……男の子って……１回で、こんなに出るのね……ふぅうっ……<emoji=heart04>」
line = "「いつ止まるのか、わからないくらい……男の子って……１回で、こんなに出るのね……ふぅうっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 射精した俺自身がびっくりするほどの量。溜めきれなかった精液がごぽごぽとレティシアの秘所からあふれ出し、俺の身体に垂れ落ちていく。
line = "射精した俺自身がびっくりするほどの量。溜めきれなかった精液がごぽごぽとレティシアの秘所からあふれ出し、俺の身体に垂れ落ちていく。"

[[dialogue]]
speaker = "レティシア"
# 「……普段はこんなに、出ないの？　私が相手だから、たくさん、出たの……？」
line = "「……普段はこんなに、出ないの？　私が相手だから、たくさん、出たの……？」"

[[dialogue]]
speaker = "レティシア"
# 「……不思議。そんなこと、あるのね……」
line = "「……不思議。そんなこと、あるのね……」"

[[dialogue]]
speaker = "クロト"
# 「……レティシア、どうだった？」
line = "「……レティシア、どうだった？」"

[[dialogue]]
speaker = "レティシア"
# 「気持ち、良かった……。あなたとぴったり繋がって、あったかい精液、注がれるの……これ……」
line = "「気持ち、良かった……。あなたとぴったり繋がって、あったかい精液、注がれるの……これ……」"

[[dialogue]]
speaker = "レティシア"
# 「…………すごく、好き……<emoji=heart04>」
line = "「…………すごく、好き……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 倒れこむようにして抱き着いてきたレティシアと──
line = "倒れこむようにして抱き着いてきたレティシアと──"

[[dialogue]]
speaker = "レティシア"
# 「んぅちゅ……んれぇ、んちゅる……<emoji=heart04>」
line = "「んぅちゅ……んれぇ、んちゅる……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 初めて、キスをした。
line = "初めて、キスをした。"

[[dialogue]]
speaker = "レティシア"
# 「……今さらだけど、順番があべこべね。先にキスからするべきだったかしら……？」
line = "「……今さらだけど、順番があべこべね。先にキスからするべきだったかしら……？」"

[[dialogue]]
speaker = "unk"
# 急に冷静なことを言うレティシアが面白くて、俺は苦笑しながらキスを返す。
line = "急に冷静なことを言うレティシアが面白くて、俺は苦笑しながらキスを返す。"

[[dialogue]]
speaker = "レティシア"
# 「ん……ちゅ<emoji=heart04>　んぅ、ちゅぱ……<emoji=heart04>」
line = "「ん……ちゅ<emoji=heart04>　んぅ、ちゅぱ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# デネブに住む平行世界人の彼女。
line = "デネブに住む平行世界人の彼女。"

[[dialogue]]
speaker = "unk"
# いずれ、離ればなれになるかもしれない相手──そう思うとなおさら、今この瞬間が愛おしくて。
line = "いずれ、離ればなれになるかもしれない相手──そう思うとなおさら、今この瞬間が愛おしくて。"

[[dialogue]]
speaker = "レティシア"
# 「れぇ、んちゅる、んぅ……ちゅぱ……<emoji=heart04>　好きよ……魔王……んちゅぅ……<emoji=heart04>」
line = "「れぇ、んちゅる、んぅ……ちゅぱ……<emoji=heart04>　好きよ……魔王……んちゅぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# その夜はずっと、レティシアと共に過ごすのだった。
line = "その夜はずっと、レティシアと共に過ごすのだった。"
