[[dialogue]]
speaker = "unk"
# 一連の事件が解決し、ステラが異世界から戻って来た。
line = "一連の事件が解決し、ステラが異世界から戻って来た。"

[[dialogue]]
speaker = "ステラ"
# 「やっぱり団長さんのそばが一番落ち着きますね～」
line = "「やっぱり団長さんのそばが一番落ち着きますね～」"

[[dialogue]]
speaker = "unk"
# さっそく部屋にやって来たステラは、そのままリラックスモードに入っている。
line = "さっそく部屋にやって来たステラは、そのままリラックスモードに入っている。"

[[dialogue]]
speaker = "unk"
# 知らない人だらけの異世界では、いろいろ苦労しただろうと思って訊ねてみると、予想外に自信たっぷりな様子だった。
line = "知らない人だらけの異世界では、いろいろ苦労しただろうと思って訊ねてみると、予想外に自信たっぷりな様子だった。"

[[dialogue]]
speaker = "ステラ"
# 「心配しなくても大丈夫でしたよ！　ちゃーんとしっかり交流もしてきましたから」
line = "「心配しなくても大丈夫でしたよ！　ちゃーんとしっかり交流もしてきましたから」"

[[dialogue]]
speaker = "ステラ"
# 「本当ですよ？　異世界でボクもいろんな経験を積んで、ひと回りもふた回りも成長したんです」
line = "「本当ですよ？　異世界でボクもいろんな経験を積んで、ひと回りもふた回りも成長したんです」"

[[dialogue]]
speaker = "unk"
# 立派なことを言いつつも、ステラは完全に気の抜けきった様子でゴロゴロしている。
line = "立派なことを言いつつも、ステラは完全に気の抜けきった様子でゴロゴロしている。"

[[dialogue]]
speaker = "unk"
# 果たしてどれだけステラが成長したのか、確かめてみたいという気持ちが芽生えてきた。
line = "果たしてどれだけステラが成長したのか、確かめてみたいという気持ちが芽生えてきた。"

[[dialogue]]
speaker = "ステラ"
# 「え？　いいですよ、そんなに疑うなら確かめてもらっても。どうやって確かめるのか知りませんけど……きゃっ！？」
line = "「え？　いいですよ、そんなに疑うなら確かめてもらっても。どうやって確かめるのか知りませんけど……きゃっ！？」"

[[dialogue]]
speaker = "ステラ"
# 「だ、団長さんっ！　か、鏡！　鏡に映っちゃってますっ！」
line = "「だ、団長さんっ！　か、鏡！　鏡に映っちゃってますっ！」"

[[dialogue]]
speaker = "ステラ"
# 「何がって……ぜ、全部ですよぉっ！　恥ずかしいところ、全部、映っちゃってますって……あっ、あぁあぁっ<emoji=heart04>」
line = "「何がって……ぜ、全部ですよぉっ！　恥ずかしいところ、全部、映っちゃってますって……あっ、あぁあぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 鏡面にはステラの可愛らしい局部と、こちらの熱くいきり立った肉棒が映っている。
line = "鏡面にはステラの可愛らしい局部と、こちらの熱くいきり立った肉棒が映っている。"

[[dialogue]]
speaker = "ステラ"
# 「こ、こんなことされたら……はぁあぁっ<emoji=heart04>　ボクじゃなくても、恥ずかしいに決まってますよっ！」
line = "「こ、こんなことされたら……はぁあぁっ<emoji=heart04>　ボクじゃなくても、恥ずかしいに決まってますよっ！」"

[[dialogue]]
speaker = "ステラ"
# 「あぁあっ、はぁぁ<emoji=heart04>　だいたいこんな方法で、ボクが向こうの世界でちゃんと交流できてたかなんて……んんぅ<emoji=heart04>　確かめられるはず、ないじゃないですかぁ！」
line = "「あぁあっ、はぁぁ<emoji=heart04>　だいたいこんな方法で、ボクが向こうの世界でちゃんと交流できてたかなんて……んんぅ<emoji=heart04>　確かめられるはず、ないじゃないですかぁ！」"

[[dialogue]]
speaker = "unk"
# ステラの抗議は至極もっともだ。
line = "ステラの抗議は至極もっともだ。"

[[dialogue]]
speaker = "unk"
# だがパンパンに張り詰めたこちらのモノは、もう収まりがつかないほど興奮状態になってしまっている。
line = "だがパンパンに張り詰めたこちらのモノは、もう収まりがつかないほど興奮状態になってしまっている。"

[[dialogue]]
speaker = "ステラ"
# 「えっ？　ま、まさか……<emoji=heart04>　はぁぁあっ<emoji=heart04>　鏡に映したまま、するつもりですかぁ……？」
line = "「えっ？　ま、まさか……<emoji=heart04>　はぁぁあっ<emoji=heart04>　鏡に映したまま、するつもりですかぁ……？」"

[[dialogue]]
speaker = "ステラ"
# 「はぁぁんっ<emoji=heart04>　だって……団長さんのこの、おっきなおち○ちん……<emoji=heart04>　ボクのに入るところ、目の当たりにするなんてぇ……はふぅぅん<emoji=heart04>」
line = "「はぁぁんっ<emoji=heart04>　だって……団長さんのこの、おっきなおち○ちん……<emoji=heart04>　ボクのに入るところ、目の当たりにするなんてぇ……はふぅぅん<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「ど、ドキドキなんてしてませんよっ！　あぁぁっ<emoji=heart04>　ただ、今までちゃんと、見たことなかったかもしれないと思ってぇ……<emoji=heart04>」
line = "「ど、ドキドキなんてしてませんよっ！　あぁぁっ<emoji=heart04>　ただ、今までちゃんと、見たことなかったかもしれないと思ってぇ……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「あっ……！　んんぅ、はふぅぅん<emoji=heart04>　おち○ちん……スリスリしないでくださいよぉ<emoji=heart04>」
line = "「あっ……！　んんぅ、はふぅぅん<emoji=heart04>　おち○ちん……スリスリしないでくださいよぉ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「や、んぅう……<emoji=heart04>　こんなにカチカチになった……団長さんのおち○ちん<emoji=heart04>　あぁあっ<emoji=heart04>　おま○こにスリスリ、されたらぁ……<emoji=heart04>　ボク……ボクぅ<emoji=heart04>」
line = "「や、んぅう……<emoji=heart04>　こんなにカチカチになった……団長さんのおち○ちん<emoji=heart04>　あぁあっ<emoji=heart04>　おま○こにスリスリ、されたらぁ……<emoji=heart04>　ボク……ボクぅ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「うぅぅ<emoji=heart04>　団長さんの、意地悪ぅ……<emoji=heart04>」
line = "「うぅぅ<emoji=heart04>　団長さんの、意地悪ぅ……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「は、恥ずかしい、ですけど……<emoji=heart04>　はぁぁあっ<emoji=heart04>　正直に言うと、見たいって気持ちも、あります……<emoji=heart04>」
line = "「は、恥ずかしい、ですけど……<emoji=heart04>　はぁぁあっ<emoji=heart04>　正直に言うと、見たいって気持ちも、あります……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「あはぁぁ<emoji=heart04>　団長さんのおち○ちんと、ボクのおま○こっ<emoji=heart04>　ひとつになってる、ところ……<emoji=heart04>　んんぅっ<emoji=heart04>」
line = "「あはぁぁ<emoji=heart04>　団長さんのおち○ちんと、ボクのおま○こっ<emoji=heart04>　ひとつになってる、ところ……<emoji=heart04>　んんぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「わかり、ましたぁ<emoji=heart04>　いい、ですよ……<emoji=heart04>　はぁぁっ<emoji=heart04>　このまま、団長さんのおち○ちんが入るとこ……見せてください<emoji=heart04>」
line = "「わかり、ましたぁ<emoji=heart04>　いい、ですよ……<emoji=heart04>　はぁぁっ<emoji=heart04>　このまま、団長さんのおち○ちんが入るとこ……見せてください<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「はぁっ……！　あぁううっ<emoji=heart04>　んんんぅ<emoji=heart04><emoji=heart04>」
line = "「はぁっ……！　あぁううっ<emoji=heart04>　んんんぅ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「ぁ、あぁあっ<emoji=heart04>　団長さんの……おっきなおち○ちんっ<emoji=heart04>　ボクのおま○こ、かき分けて……っ<emoji=heart04>」
line = "「ぁ、あぁあっ<emoji=heart04>　団長さんの……おっきなおち○ちんっ<emoji=heart04>　ボクのおま○こ、かき分けて……っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 熱く膨張しきった肉棒が、ステラの小さな割れ目を押し分けて入っていく。
line = "熱く膨張しきった肉棒が、ステラの小さな割れ目を押し分けて入っていく。"

[[dialogue]]
speaker = "unk"
# その様子がはっきり鏡に映って、詳細に見て取れた。
line = "その様子がはっきり鏡に映って、詳細に見て取れた。"

[[dialogue]]
speaker = "ステラ"
# 「はぁ、ぁ……ああぁ<emoji=heart04>　んんっ……んふぅうっ<emoji=heart04>　ぁ……はぁあ、あぁあっ……<emoji=heart04>」
line = "「はぁ、ぁ……ああぁ<emoji=heart04>　んんっ……んふぅうっ<emoji=heart04>　ぁ……はぁあ、あぁあっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「あぁんっ<emoji=heart04>　ボク……団長さんと、ひとつになってるところ<emoji=heart04>　はぁぁっ<emoji=heart04>　見せつけ、られてるぅ<emoji=heart04>　んんぅっ<emoji=heart04>」
line = "「あぁんっ<emoji=heart04>　ボク……団長さんと、ひとつになってるところ<emoji=heart04>　はぁぁっ<emoji=heart04>　見せつけ、られてるぅ<emoji=heart04>　んんぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「変な、感じですぅ<emoji=heart04>　んんうっ<emoji=heart04>　恥ずかし過ぎて、死んじゃいそうなのにぃ……<emoji=heart04>　あぁあっ<emoji=heart04>　でも……どうして、いつも以上に胸がドキドキしてぇ……<emoji=heart04>」
line = "「変な、感じですぅ<emoji=heart04>　んんうっ<emoji=heart04>　恥ずかし過ぎて、死んじゃいそうなのにぃ……<emoji=heart04>　あぁあっ<emoji=heart04>　でも……どうして、いつも以上に胸がドキドキしてぇ……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「あぁああっ<emoji=heart04>　おち○ちんが、おま○こを貫いてるところから……目が、離せませんっ<emoji=heart04>　んんっ、は、ぁううっ……<emoji=heart04>」
line = "「あぁああっ<emoji=heart04>　おち○ちんが、おま○こを貫いてるところから……目が、離せませんっ<emoji=heart04>　んんっ、は、ぁううっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 戸惑ったような声を漏らしながら、ステラもその光景に釘付けになっている。
line = "戸惑ったような声を漏らしながら、ステラもその光景に釘付けになっている。"

[[dialogue]]
speaker = "ステラ"
# 「団長さん……ボク、知りたい、です<emoji=heart04>　あぁぁっ<emoji=heart04>　団長さんのおち○ちんが……どうやって、ボクのおま○こに出たり、入ったり、するのかぁ……<emoji=heart04>」
line = "「団長さん……ボク、知りたい、です<emoji=heart04>　あぁぁっ<emoji=heart04>　団長さんのおち○ちんが……どうやって、ボクのおま○こに出たり、入ったり、するのかぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ステラから発せられたその言葉に動かされるように、ゆっくりとピストンを始めた。
line = "ステラから発せられたその言葉に動かされるように、ゆっくりとピストンを始めた。"

[[dialogue]]
speaker = "ステラ"
# 「あぁああっ<emoji=heart04>　あぁあんっ<emoji=heart04>　はぁ、あっ……あぁあっ<emoji=heart04>　あ、んんっ、あっ、ああっ<emoji=heart04>」
line = "「あぁああっ<emoji=heart04>　あぁあんっ<emoji=heart04>　はぁ、あっ……あぁあっ<emoji=heart04>　あ、んんっ、あっ、ああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「すごい、ですっ<emoji=heart04>　んんんっ……本当に、ボクのおま○こっ<emoji=heart04>　こんなに太くて硬いものが、ズボズボしてぇ……んんぅっ<emoji=heart04>」
line = "「すごい、ですっ<emoji=heart04>　んんんっ……本当に、ボクのおま○こっ<emoji=heart04>　こんなに太くて硬いものが、ズボズボしてぇ……んんぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「血管が浮き出るくらい、パンパンに張り詰めたおち○ちんっ<emoji=heart04>　あぁんっ<emoji=heart04>　ボクの<ruby=なか>膣</ruby>で、ヌルヌルになって……<emoji=heart04>　は、あぁあっ<emoji=heart04>」
line = "「血管が浮き出るくらい、パンパンに張り詰めたおち○ちんっ<emoji=heart04>　あぁんっ<emoji=heart04>　ボクの<ruby>膣<rt>なか</rt></ruby>で、ヌルヌルになって……<emoji=heart04>　は、あぁあっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「ボクのおま○こって、こんなに濡れてたんですね……<emoji=heart04>　はぁあん<emoji=heart04>　団長さんのおち○ちんが欲しくて、こんなにぃ……<emoji=heart04>　あ、ああんっ<emoji=heart04>」
line = "「ボクのおま○こって、こんなに濡れてたんですね……<emoji=heart04>　はぁあん<emoji=heart04>　団長さんのおち○ちんが欲しくて、こんなにぃ……<emoji=heart04>　あ、ああんっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ステラの膣は熱い蜜液に満たされており、スムーズなピストンと心地よい摩擦を与えてくれた。
line = "ステラの膣は熱い蜜液に満たされており、スムーズなピストンと心地よい摩擦を与えてくれた。"

[[dialogue]]
speaker = "unk"
# ジュプジュプといやらしい粘液の音を立てて、ステラの内側がかき回されていく。
line = "ジュプジュプといやらしい粘液の音を立てて、ステラの内側がかき回されていく。"

[[dialogue]]
speaker = "ステラ"
# 「あんっ<emoji=heart04>　ふわあっ、ふぅう、ああぁ、んんぅ<emoji=heart04>　はぁ、あ、ああ……エッチな、音……しちゃってますっ<emoji=heart04>　んんうっ<emoji=heart04>」
line = "「あんっ<emoji=heart04>　ふわあっ、ふぅう、ああぁ、んんぅ<emoji=heart04>　はぁ、あ、ああ……エッチな、音……しちゃってますっ<emoji=heart04>　んんうっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「こんなふうに、ボク……はぁあん<emoji=heart04>　団長さんに、エッチされてたんですねっ<emoji=heart04>　あぁあんっ<emoji=heart04>　知らな、かったです……<emoji=heart04>」
line = "「こんなふうに、ボク……はぁあん<emoji=heart04>　団長さんに、エッチされてたんですねっ<emoji=heart04>　あぁあんっ<emoji=heart04>　知らな、かったです……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「男の人の、おち○ちんが……女の子のおま○こ、ぬっちゅぬっちゅって、出入りする、ところっ<emoji=heart04>　あぁあっ<emoji=heart04>　なんだかすごく、エッチで、恥ずかしいっ<emoji=heart04><emoji=heart04>」
line = "「男の人の、おち○ちんが……女の子のおま○こ、ぬっちゅぬっちゅって、出入りする、ところっ<emoji=heart04>　あぁあっ<emoji=heart04>　なんだかすごく、エッチで、恥ずかしいっ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「あんっ<emoji=heart04>　恥ずかしいのに、目が離せないですっ<emoji=heart04>　んふぅんっ<emoji=heart04>　恥ずかしいとこ見てると、余計ドキドキしてっ<emoji=heart04>　ドキドキすると、気持ちよくなっちゃうっ<emoji=heart04>」
line = "「あんっ<emoji=heart04>　恥ずかしいのに、目が離せないですっ<emoji=heart04>　んふぅんっ<emoji=heart04>　恥ずかしいとこ見てると、余計ドキドキしてっ<emoji=heart04>　ドキドキすると、気持ちよくなっちゃうっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「あぁあぁっ<emoji=heart04>　もっと、動いてくださいっ<emoji=heart04>　ボクの恥ずかしいおま○こが、団長さんのおち○ちんを飲み込むところ、もっとよく見せてぇ……<emoji=heart04>」
line = "「あぁあぁっ<emoji=heart04>　もっと、動いてくださいっ<emoji=heart04>　ボクの恥ずかしいおま○こが、団長さんのおち○ちんを飲み込むところ、もっとよく見せてぇ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ステラの要望通り、少しずつ大胆に、ピストンの可動域を広げていく。
line = "ステラの要望通り、少しずつ大胆に、ピストンの可動域を広げていく。"

[[dialogue]]
speaker = "unk"
# もう今の段階で、頭が痺れるほどに気持ちがいい。
line = "もう今の段階で、頭が痺れるほどに気持ちがいい。"

[[dialogue]]
speaker = "ステラ"
# 「あぁんっ<emoji=heart04>　気持ちよくて……あぁあっ<emoji=heart04>　声、出ちゃいますっ<emoji=heart04>　んんっ、あっ、ああんっ<emoji=heart04>」
line = "「あぁんっ<emoji=heart04>　気持ちよくて……あぁあっ<emoji=heart04>　声、出ちゃいますっ<emoji=heart04>　んんっ、あっ、ああんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「ボク、赤ちゃんみたいに、抱っこされながら……んんぅ<emoji=heart04>　エッチな声、上げちゃってますっ<emoji=heart04>　あああっ、これすっごく、恥ずかしいですっ<emoji=heart04>」
line = "「ボク、赤ちゃんみたいに、抱っこされながら……んんぅ<emoji=heart04>　エッチな声、上げちゃってますっ<emoji=heart04>　あああっ、これすっごく、恥ずかしいですっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ステラの甘い喘ぎを聞きながら、もっと深い交わりを求めて突き込む。
line = "ステラの甘い喘ぎを聞きながら、もっと深い交わりを求めて突き込む。"

[[dialogue]]
speaker = "ステラ"
# 「んっ……！　はぁう、んんぅっ<emoji=heart04>　はぁ、あ、あああっ<emoji=heart04>　おち○ちん……もっと奥の方まで、届いて……<emoji=heart04>」
line = "「んっ……！　はぁう、んんぅっ<emoji=heart04>　はぁ、あ、あああっ<emoji=heart04>　おち○ちん……もっと奥の方まで、届いて……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「あっ<emoji=heart04>　あっ<emoji=heart04>　あぁあっ<emoji=heart04>　一番先っちょのところが、赤ちゃんのお部屋<emoji=heart04>　ズンズンって……んんっ、あっ、あああ<emoji=heart04>」
line = "「あっ<emoji=heart04>　あっ<emoji=heart04>　あぁあっ<emoji=heart04>　一番先っちょのところが、赤ちゃんのお部屋<emoji=heart04>　ズンズンって……んんっ、あっ、あああ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「そんなこと、されたらぁ……<emoji=heart04>　頭の中、真っ白に、なっちゃうじゃないですかぁ<emoji=heart04>　んっ、あっ、あっ、あ、あ、ああっ……<emoji=heart04>」
line = "「そんなこと、されたらぁ……<emoji=heart04>　頭の中、真っ白に、なっちゃうじゃないですかぁ<emoji=heart04>　んっ、あっ、あっ、あ、あ、ああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 言葉面とは裏腹にその声は「もっと<emoji=heart04>　もっと<emoji=heart04>」とせがむように甘ったるく、さらにステラの膣もさらなる刺激を求めて強く締め付けてくる。
line = "言葉面とは裏腹にその声は「もっと<emoji=heart04>　もっと<emoji=heart04>」とせがむように甘ったるく、さらにステラの膣もさらなる刺激を求めて強く締め付けてくる。"

[[dialogue]]
speaker = "unk"
# その期待に応えるように、今まで以上にピストンを激しくしていく。
line = "その期待に応えるように、今まで以上にピストンを激しくしていく。"

[[dialogue]]
speaker = "ステラ"
# 「あああっ！　あ、んんっ……あ、あああっ！」
line = "「あああっ！　あ、んんっ……あ、あああっ！」"

[[dialogue]]
speaker = "ステラ"
# 「はぁ、あぁあっ<emoji=heart04>　急にそんな、激しくっ<emoji=heart04>　んんっ、あっ、あああっ<emoji=heart04>」
line = "「はぁ、あぁあっ<emoji=heart04>　急にそんな、激しくっ<emoji=heart04>　んんっ、あっ、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 激しくなった動きにステラが声を上げる。
line = "激しくなった動きにステラが声を上げる。"

[[dialogue]]
speaker = "ステラ"
# 「あっ、あ、あぁあっ<emoji=heart04>　やんんっ、くんぅううっ<emoji=heart04>　む、無理、無理ぃっ<emoji=heart04>　んんっ、あっ、ああっ<emoji=heart04>」
line = "「あっ、あ、あぁあっ<emoji=heart04>　やんんっ、くんぅううっ<emoji=heart04>　む、無理、無理ぃっ<emoji=heart04>　んんっ、あっ、ああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「そんなに、されたらっ<emoji=heart04>　あっ、あ、あああっ<emoji=heart04>　おま○こ、壊れちゃいますっ<emoji=heart04>　あ、あっ、ああ、あ、あああっ<emoji=heart04>」
line = "「そんなに、されたらっ<emoji=heart04>　あっ、あ、あああっ<emoji=heart04>　おま○こ、壊れちゃいますっ<emoji=heart04>　あ、あっ、ああ、あ、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「ふわぁあぁっ<emoji=heart04>　じゅぼじゅぼっていやらしい音、すごいですぅ<emoji=heart04>　あんっ<emoji=heart04>　あんっ<emoji=heart04>　あぁあぁんっ<emoji=heart04>」
line = "「ふわぁあぁっ<emoji=heart04>　じゅぼじゅぼっていやらしい音、すごいですぅ<emoji=heart04>　あんっ<emoji=heart04>　あんっ<emoji=heart04>　あぁあぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「鏡に映ってるっ<emoji=heart04>　あぁんっ<emoji=heart04>　あんなに激しくっ、おち○ちん出し入れされてっ<emoji=heart04>　おま○こ、よだれ垂らしてっ、全部飲み込んじゃってますぅ<emoji=heart04>」
line = "「鏡に映ってるっ<emoji=heart04>　あぁんっ<emoji=heart04>　あんなに激しくっ、おち○ちん出し入れされてっ<emoji=heart04>　おま○こ、よだれ垂らしてっ、全部飲み込んじゃってますぅ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「はぁう、ううっ<emoji=heart04>　ボク、こんなエッチな顔してたんだぁ……<emoji=heart04>　はぁあんっ<emoji=heart04>」
line = "「はぁう、ううっ<emoji=heart04>　ボク、こんなエッチな顔してたんだぁ……<emoji=heart04>　はぁあんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「こんな、嬉しそうな顔して、おち○ちん飲み込んじゃってっ<emoji=heart04>　あぁああぁっ<emoji=heart04>　恥ずかしいっ、恥ずかしいですぅ<emoji=heart04>」
line = "「こんな、嬉しそうな顔して、おち○ちん飲み込んじゃってっ<emoji=heart04>　あぁああぁっ<emoji=heart04>　恥ずかしいっ、恥ずかしいですぅ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「あぁああぁあぁっ<emoji=heart04>　ボクのエッチなところ、全部見られてますっ<emoji=heart04>　ふわぁあんっ<emoji=heart04>　恥ずかしいの、気持ちいいですぅ<emoji=heart04>」
line = "「あぁああぁあぁっ<emoji=heart04>　ボクのエッチなところ、全部見られてますっ<emoji=heart04>　ふわぁあんっ<emoji=heart04>　恥ずかしいの、気持ちいいですぅ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「団長さんにっ、んんっ、あ、あ、ああ、あっ<emoji=heart04>　おち○ちんズボズボされて……もっともっと、気持ちよくなっちゃいますっ<emoji=heart04>」
line = "「団長さんにっ、んんっ、あ、あ、ああ、あっ<emoji=heart04>　おち○ちんズボズボされて……もっともっと、気持ちよくなっちゃいますっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「はぁ、あぁあ、あっ<emoji=heart04>　だって……仕方ないんですっ<emoji=heart04>　団長さんとのエッチ、気持ちいいんですからっ、あ、あああっ<emoji=heart04>」
line = "「はぁ、あぁあ、あっ<emoji=heart04>　だって……仕方ないんですっ<emoji=heart04>　団長さんとのエッチ、気持ちいいんですからっ、あ、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「優しく、されるのもっ、んうぅうっ、好き、ですけどぉっ<emoji=heart04>　こんなふうに、激しく、されるのも……好きだからっ、は、ぁ、あああぁあっ<emoji=heart04>」
line = "「優しく、されるのもっ、んうぅうっ、好き、ですけどぉっ<emoji=heart04>　こんなふうに、激しく、されるのも……好きだからっ、は、ぁ、あああぁあっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「だから、仕方ないですよねっ、団長さんっ<emoji=heart04>　あぁあっ<emoji=heart04>　こんな、恥ずかしい女の子に、なっちゃってもぉ<emoji=heart04>　あっ、あ、あ、あ、あ、ああっ！！」
line = "「だから、仕方ないですよねっ、団長さんっ<emoji=heart04>　あぁあっ<emoji=heart04>　こんな、恥ずかしい女の子に、なっちゃってもぉ<emoji=heart04>　あっ、あ、あ、あ、あ、ああっ！！」"

[[dialogue]]
speaker = "unk"
# 恥ずかしがってるステラも、恥ずかしいのが気持ちよくなっちゃうステラも、大好きだ。
line = "恥ずかしがってるステラも、恥ずかしいのが気持ちよくなっちゃうステラも、大好きだ。"

[[dialogue]]
speaker = "unk"
# ステラにそう伝えると、表情が緩んでステラはますます行為に没頭していく。
line = "ステラにそう伝えると、表情が緩んでステラはますます行為に没頭していく。"

[[dialogue]]
speaker = "ステラ"
# 「団長さん、大好きですぅ<emoji=heart04>　あぁあんっ<emoji=heart04>　大好きな団長さんのおち○ちんでっ、あぁあっ<emoji=heart04>　ボクの気持ちいいとこ、いっぱい攻めてくださいっ、あっ、ああっ<emoji=heart04>」
line = "「団長さん、大好きですぅ<emoji=heart04>　あぁあんっ<emoji=heart04>　大好きな団長さんのおち○ちんでっ、あぁあっ<emoji=heart04>　ボクの気持ちいいとこ、いっぱい攻めてくださいっ、あっ、ああっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 叫びながらステラの膣が痛いほどに締め付けてくる。
line = "叫びながらステラの膣が痛いほどに締め付けてくる。"

[[dialogue]]
speaker = "ステラ"
# 「だ、だって……大好きだからぁ<emoji=heart04>　あんっ、おま○こ、締まっちゃうんですっ<emoji=heart04>　団長さんのおち○ちん、ぎゅーってしちゃうんですっ<emoji=heart04>」
line = "「だ、だって……大好きだからぁ<emoji=heart04>　あんっ、おま○こ、締まっちゃうんですっ<emoji=heart04>　団長さんのおち○ちん、ぎゅーってしちゃうんですっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「ああっ、あっ、あ、ああっ<emoji=heart04>　気持ちいいの、止まらないっ<emoji=heart04>　んんぅ、あっ、あ、あ、ああ、あ、あ、あああっ<emoji=heart04>」
line = "「ああっ、あっ、あ、ああっ<emoji=heart04>　気持ちいいの、止まらないっ<emoji=heart04>　んんぅ、あっ、あ、あ、ああ、あ、あ、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「ボクの中でっ、団長さんも気持ちよくなってぇ<emoji=heart04>　あんっ<emoji=heart04>　あん<emoji=heart04>　あぁあんっ<emoji=heart04>」
line = "「ボクの中でっ、団長さんも気持ちよくなってぇ<emoji=heart04>　あんっ<emoji=heart04>　あん<emoji=heart04>　あぁあんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「んくぅううっ、はあぁあっ<emoji=heart04>　あっ、あ……おち○ちん、ビクビクしてるの、分かりますっ<emoji=heart04>　んんっ、あっ、あぁああっ！」
line = "「んくぅううっ、はあぁあっ<emoji=heart04>　あっ、あ……おち○ちん、ビクビクしてるの、分かりますっ<emoji=heart04>　んんっ、あっ、あぁああっ！」"

[[dialogue]]
speaker = "ステラ"
# 「ボクも、イッちゃう……んんぅっ、あっ、ああ、あ、ああっ<emoji=heart04>　もうイクっ、んぅうう、ん、んくぅ、んんんっ<emoji=heart04>　あっ、あ、あぁあ、あ、あ、ああんっ<emoji=heart04>」
line = "「ボクも、イッちゃう……んんぅっ、あっ、ああ、あ、ああっ<emoji=heart04>　もうイクっ、んぅうう、ん、んくぅ、んんんっ<emoji=heart04>　あっ、あ、あぁあ、あ、あ、ああんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「あぁあんっ<emoji=heart04>　もう限界、イッちゃいますっ<emoji=heart04>　団長さんっ、団長さぁんっ<emoji=heart04>　あっ、あっ、あああっ<emoji=heart04>」
line = "「あぁあんっ<emoji=heart04>　もう限界、イッちゃいますっ<emoji=heart04>　団長さんっ、団長さぁんっ<emoji=heart04>　あっ、あっ、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「ボクもうっ<emoji=heart04>　あっあっあっあっあっ<emoji=heart04>　イクイク、イっちゃうぅぅぅ<emoji=heart04>　ああ、あぁ、ああ、あぁ、あぁあっ<emoji=heart04>　ふあぁああぁ～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「ボクもうっ<emoji=heart04>　あっあっあっあっあっ<emoji=heart04>　イクイク、イっちゃうぅぅぅ<emoji=heart04>　ああ、あぁ、ああ、あぁ、あぁあっ<emoji=heart04>　ふあぁああぁ～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「あぁああぁあああぁああぁぁ～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>　イックうぅぅぅ～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「あぁああぁあああぁああぁぁ～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>　イックうぅぅぅ～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 最後にステラの膣奥深くまで先端を叩きつけ、同時に欲望の全てを解放する。
line = "最後にステラの膣奥深くまで先端を叩きつけ、同時に欲望の全てを解放する。"

[[dialogue]]
speaker = "ステラ"
# 「ああぁああぁぁっ<emoji=heart04><emoji=heart04>　んんっ、あっ、あ、ああああ～～～～っ<emoji=heart04><emoji=heart04>」
line = "「ああぁああぁぁっ<emoji=heart04><emoji=heart04>　んんっ、あっ、あ、ああああ～～～～っ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「はぁぅ……んんぅっ<emoji=heart04>　あぁあぁっ<emoji=heart04>　団長さんのが……ドクドクって、脈打ってぇ<emoji=heart04>　ぁあ、あ、ああっ……<emoji=heart04>」
line = "「はぁぅ……んんぅっ<emoji=heart04>　あぁあぁっ<emoji=heart04>　団長さんのが……ドクドクって、脈打ってぇ<emoji=heart04>　ぁあ、あ、ああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「ふわぁあぁっ<emoji=heart04>　ボクの中に……あったかいの、いっぱい……流れ込んできてますぅ<emoji=heart04>　んんっ……んぅ、あぁあ、ああっ<emoji=heart04>」
line = "「ふわぁあぁっ<emoji=heart04>　ボクの中に……あったかいの、いっぱい……流れ込んできてますぅ<emoji=heart04>　んんっ……んぅ、あぁあ、ああっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ステラは大きく身体を震わせながら、自身の内側を満たしていく温かい液体を感じていた。
line = "ステラは大きく身体を震わせながら、自身の内側を満たしていく温かい液体を感じていた。"

[[dialogue]]
speaker = "ステラ"
# 「はぁ……ぅ……<emoji=heart04>　はふぅぅん……<emoji=heart04>」
line = "「はぁ……ぅ……<emoji=heart04>　はふぅぅん……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 心地よい放出感に包まれながら、ステラの膣内からゆっくりと自身を引き抜く。
line = "心地よい放出感に包まれながら、ステラの膣内からゆっくりと自身を引き抜く。"

[[dialogue]]
speaker = "unk"
# すると内側を満たしていたものが、トロトロと流れ出した。
line = "すると内側を満たしていたものが、トロトロと流れ出した。"

[[dialogue]]
speaker = "unk"
# ステラは乱れた息を整えながら、鏡に映るその光景にうっとりと見入っている。
line = "ステラは乱れた息を整えながら、鏡に映るその光景にうっとりと見入っている。"

[[dialogue]]
speaker = "ステラ"
# 「あぁ……いっぱい、こぼれてます<emoji=heart04>　団長さん、こんなにボクで、気持ちよくなってくれたんですね……<emoji=heart04>」
line = "「あぁ……いっぱい、こぼれてます<emoji=heart04>　団長さん、こんなにボクで、気持ちよくなってくれたんですね……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「えへへへへへぇ<emoji=heart04>　なんだか、とっても嬉しいです……<emoji=heart04>」
line = "「えへへへへへぇ<emoji=heart04>　なんだか、とっても嬉しいです……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「はぁぁ……<emoji=heart04>　鏡に映った自分を見ながらエッチするの、恥ずかしかったけど……いつも以上に興奮しちゃったかもです<emoji=heart04>」
line = "「はぁぁ……<emoji=heart04>　鏡に映った自分を見ながらエッチするの、恥ずかしかったけど……いつも以上に興奮しちゃったかもです<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「団長さんは、どうでしたか……<emoji=heart04>」
line = "「団長さんは、どうでしたか……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ステラの痴態を目の当たりにしながらの行為、そんなもの興奮しないわけがない。
line = "ステラの痴態を目の当たりにしながらの行為、そんなもの興奮しないわけがない。"

[[dialogue]]
speaker = "unk"
# そう答えると、ステラはうんうんと頷く。
line = "そう答えると、ステラはうんうんと頷く。"

[[dialogue]]
speaker = "ステラ"
# 「今まで曖昧だった団長さんとのエッチ姿が、ちゃんと見たことで鮮明に頭の中に残っちゃってます……<emoji=heart04>」
line = "「今まで曖昧だった団長さんとのエッチ姿が、ちゃんと見たことで鮮明に頭の中に残っちゃってます……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「なんだか、しばらく忘れられそうにないかも……<emoji=heart04>」
line = "「なんだか、しばらく忘れられそうにないかも……<emoji=heart04>」"

[[dialogue]]
speaker = "ステラ"
# 「今夜は、それを思い出して……」
line = "「今夜は、それを思い出して……」"

[[dialogue]]
speaker = "ステラ"
# 「って、何を言わせるんですかぁ！」
line = "「って、何を言わせるんですかぁ！」"

[[dialogue]]
speaker = "ステラ"
# 「もーっ、団長さん！　このままエッチな光景が頭から離れなくなっちゃったら、責任を取ってもらいますからねっ<emoji=heart04>」
line = "「もーっ、団長さん！　このままエッチな光景が頭から離れなくなっちゃったら、責任を取ってもらいますからねっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ステラの可愛い抗議を聞きながら、その時はステラが満足するまでたっぷり可愛がってやろうと心に決めるのだった。
line = "ステラの可愛い抗議を聞きながら、その時はステラが満足するまでたっぷり可愛がってやろうと心に決めるのだった。"
