[[dialogue]]
speaker = "unk"
# 第２話,勉強は苦手,P
line = "第２話,勉強は苦手,P"

[[dialogue]]
speaker = "unk"
# 極星学園星徒会のみんなは、一時的に<ruby=とうりゅう>逗留</ruby>している平行世界人だ。
line = "極星学園星徒会のみんなは、一時的に<ruby>逗留<rt>とうりゅう</rt></ruby>している平行世界人だ。"

[[dialogue]]
speaker = "unk"
# しかし学生である以上、勉学をおろそかにしてはいけない──それが学園長であるシノさんからのお達しだ。
line = "しかし学生である以上、勉学をおろそかにしてはいけない──それが学園長であるシノさんからのお達しだ。"

[[dialogue]]
speaker = "グレイス"
# 「すごい量の本ですね～っ！　やっぱり復興した後の極星学園に比べて、蔵書が桁違いです！」
line = "「すごい量の本ですね～っ！　やっぱり復興した後の極星学園に比べて、蔵書が桁違いです！」"

[[dialogue]]
speaker = "チナ"
# 「うっ……活字まみれの本……頭が……」
line = "「うっ……活字まみれの本……頭が……」"

[[dialogue]]
speaker = "レティシア"
# 「困ったわね。どうにかして本を読まずに、課題を終わらせられないかしら」
line = "「困ったわね。どうにかして本を読まずに、課題を終わらせられないかしら」"

[[dialogue]]
speaker = "マトイ"
# 「レティシアさんって、読書はしないんですか？」
line = "「レティシアさんって、読書はしないんですか？」"

[[dialogue]]
speaker = "レティシア"
# 「まったくしないわね。ページをめくる暇があったら、戦闘訓練の方が有意義だもの」
line = "「まったくしないわね。ページをめくる暇があったら、戦闘訓練の方が有意義だもの」"

[[dialogue]]
speaker = "マトイ"
# 「意外かも……何だか本を読む姿が、すごく絵になる人に見えますけど」
line = "「意外かも……何だか本を読む姿が、すごく絵になる人に見えますけど」"

[[dialogue]]
speaker = "レティシア"
# 「それ、デネブでもよく言われるのよね……イメージと違うって。どうしてかしら？」
line = "「それ、デネブでもよく言われるのよね……イメージと違うって。どうしてかしら？」"

[[dialogue]]
speaker = "マトイ"
# 「落ち着いたお姉さんですから、何でもできちゃう感じが漂っているっていうか……」
line = "「落ち着いたお姉さんですから、何でもできちゃう感じが漂っているっていうか……」"

[[dialogue]]
speaker = "レティシア"
# 「偏見ね。自慢じゃないけれど──私は本を一切読まないわ」
line = "「偏見ね。自慢じゃないけれど──私は本を一切読まないわ」"

[[dialogue]]
speaker = "unk"
# 本当に自慢にならない……！
line = "本当に自慢にならない……！"

[[dialogue]]
speaker = "レティシア"
# 「私の役割は、ルヴィの命令を完遂することだもの。読書する暇があったら刀を振るうべきでしょう？」
line = "「私の役割は、ルヴィの命令を完遂することだもの。読書する暇があったら刀を振るうべきでしょう？」"

[[dialogue]]
speaker = "マトイ"
# 「す、すごい思いきり。一応、合理的ではあるのかな……？」
line = "「す、すごい思いきり。一応、合理的ではあるのかな……？」"

[[dialogue]]
speaker = "グレイス"
# 「よ～し！　ひとまずお勉強、始めちゃいましょう！　私、本を見繕ってきます！」
line = "「よ～し！　ひとまずお勉強、始めちゃいましょう！　私、本を見繕ってきます！」"

[[dialogue]]
speaker = "unk"
# せっかくなので極星のみんなと同じテーブルで、俺とマトイも学園の課題を進めることにした──
line = "せっかくなので極星のみんなと同じテーブルで、俺とマトイも学園の課題を進めることにした──"

[[dialogue]]
speaker = "マトイ"
# 「あれ……？　この数式、どうやって解けばいいんだっけ……会長、わかる？」
line = "「あれ……？　この数式、どうやって解けばいいんだっけ……会長、わかる？」"

[[dialogue]]
speaker = "unk"
# ……ごめん、俺もわからない
line = "……ごめん、俺もわからない"

[[dialogue]]
speaker = "マトイ"
# 「最近、出撃続きで復習ができてないんだよね……こんな時、サーシャさんがいてくれたらなぁ……」
line = "「最近、出撃続きで復習ができてないんだよね……こんな時、サーシャさんがいてくれたらなぁ……」"

[[dialogue]]
speaker = "マトイ"
# 「あ──そうだっ。レティシアさん、ちょっと聞いてもいいですか？」
line = "「あ──そうだっ。レティシアさん、ちょっと聞いてもいいですか？」"

[[dialogue]]
speaker = "レティシア"
# 「あら。何かしら」
line = "「あら。何かしら」"

[[dialogue]]
speaker = "マトイ"
# 「この設問なんですけど、ちょっと詰まってて……よかったら教えてくれませんか？」
line = "「この設問なんですけど、ちょっと詰まってて……よかったら教えてくれませんか？」"

[[dialogue]]
speaker = "レティシア"
# 「……どうしてみんな、私に勉強を教えてって言うのかしら？　デネブでもよく聞かれるのよね」
line = "「……どうしてみんな、私に勉強を教えてって言うのかしら？　デネブでもよく聞かれるのよね」"

[[dialogue]]
speaker = "チナ"
# 「レティシアはアタシより勉強できないぞ」
line = "「レティシアはアタシより勉強できないぞ」"

[[dialogue]]
speaker = "マトイ"
# 「ええっ！？」
line = "「ええっ！？」"

[[dialogue]]
speaker = "グレイス"
# 「極星星徒会の中で一番成績悪いですからね……」
line = "「極星星徒会の中で一番成績悪いですからね……」"

[[dialogue]]
speaker = "unk"
# い、意外だ……
line = "い、意外だ……"

[[dialogue]]
speaker = "マトイ"
# 「うん。すっごく勉強、できそうに見えるのに……！」
line = "「うん。すっごく勉強、できそうに見えるのに……！」"

[[dialogue]]
speaker = "レティシア"
# 「偏見ね。自慢じゃないけれど──私の成績は下から数えた方が早いの。覚えておいてね」
line = "「偏見ね。自慢じゃないけれど──私の成績は下から数えた方が早いの。覚えておいてね」"

[[dialogue]]
speaker = "unk"
# そ、そんなに悪いのか……！？
line = "そ、そんなに悪いのか……！？"

[[dialogue]]
speaker = "レティシア"
# 「あなたたち、星徒会の役員なのでしょう？　思い込みや偏見は捨てないとダメじゃないかしら？」
line = "「あなたたち、星徒会の役員なのでしょう？　思い込みや偏見は捨てないとダメじゃないかしら？」"

[[dialogue]]
speaker = "マトイ"
# 「あれ？　なんか逆にお説教されてる……！？」
line = "「あれ？　なんか逆にお説教されてる……！？」"

[[dialogue]]
speaker = "チナ"
# 「これでもマシになったんだぞ？　アタシらと出会った時は、読み書きだってできなかったし……」
line = "「これでもマシになったんだぞ？　アタシらと出会った時は、読み書きだってできなかったし……」"

[[dialogue]]
speaker = "チナ"
# 「ていうかちょっと聞きたいんだけどさ。アタシら５人の成績……どういう順番だとお前らは思ってるんだ？」
line = "「ていうかちょっと聞きたいんだけどさ。アタシら５人の成績……どういう順番だとお前らは思ってるんだ？」"

[[dialogue]]
speaker = "unk"
# 次は……ベアトリスあたり？
line = "次は……ベアトリスあたり？"

[[dialogue]]
speaker = "unk"
# ルヴィネが一番成績が良さそう
line = "ルヴィネが一番成績が良さそう"

[[dialogue]]
speaker = "レティシア"
# 「ルヴィについてはその通りね。入学した時からずっと首席。あの子が満点以外を取ってるところ、見たことがないわ。でも……」
line = "「ルヴィについてはその通りね。入学した時からずっと首席。あの子が満点以外を取ってるところ、見たことがないわ。でも……」"

[[dialogue]]
speaker = "グレイス"
# 「ええ、さっそく訂正しなくては！　２番目は私です！　ていうか学年次席です！　えっへん！！」
line = "「ええ、さっそく訂正しなくては！　２番目は私です！　ていうか学年次席です！　えっへん！！」"

[[dialogue]]
speaker = "マトイ"
# 「えええぇええっ！？　グレイスちゃんが！？」
line = "「えええぇええっ！？　グレイスちゃんが！？」"

[[dialogue]]
speaker = "チナ"
# 「驚きだろ？　こいつアホだけど、成績だけはいいんだ……」
line = "「驚きだろ？　こいつアホだけど、成績だけはいいんだ……」"

[[dialogue]]
speaker = "グレイス"
# 「アホは余計ですよチナ！　私はしっかり者です！！」
line = "「アホは余計ですよチナ！　私はしっかり者です！！」"

[[dialogue]]
speaker = "マトイ"
# 「ど、どうやってそんないい成績を！？　勉強法、知りたい……！」
line = "「ど、どうやってそんないい成績を！？　勉強法、知りたい……！」"

[[dialogue]]
speaker = "グレイス"
# 「授業をしっかり聞いていればＯＫです！　テストの点はそれでばっちりです！」
line = "「授業をしっかり聞いていればＯＫです！　テストの点はそれでばっちりです！」"

[[dialogue]]
speaker = "マトイ"
# 「身も蓋もない！！　じゃ、じゃあ３番目はベアトリスさん……？」
line = "「身も蓋もない！！　じゃ、じゃあ３番目はベアトリスさん……？」"

[[dialogue]]
speaker = "チナ"
# 「アタシだよ！　ベアトはアタシの下！！」
line = "「アタシだよ！　ベアトはアタシの下！！」"

[[dialogue]]
speaker = "unk"
# チナが──３番目に成績がいい！？
line = "チナが──３番目に成績がいい！？"

[[dialogue]]
speaker = "チナ"
# 「失礼すぎるリアクション……！　くそっ、どいつもこいつも！　デネブの奴らもみんな同じことを言いやがって……！！」
line = "「失礼すぎるリアクション……！　くそっ、どいつもこいつも！　デネブの奴らもみんな同じことを言いやがって……！！」"

[[dialogue]]
speaker = "レティシア"
# 「でもチナとベアトはほとんど並んでるわ。ぶっちぎりで私だけができないの。ふふふ」
line = "「でもチナとベアトはほとんど並んでるわ。ぶっちぎりで私だけができないの。ふふふ」"

[[dialogue]]
speaker = "マトイ"
# 「笑ってる場合じゃないですよレティシアさん！？」
line = "「笑ってる場合じゃないですよレティシアさん！？」"

[[dialogue]]
speaker = "チナ"
# 「戦闘中の判断スピードとか、頭の回転っていうのか？　そういうのはレティシア、めちゃくちゃ凄いんだけど……」
line = "「戦闘中の判断スピードとか、頭の回転っていうのか？　そういうのはレティシア、めちゃくちゃ凄いんだけど……」"

[[dialogue]]
speaker = "レティシア"
# 「文字に書かれた知識の蓄積は一切できないと思って頂戴？　自慢じゃないけれど、教科書だって読んだ試しがないもの」
line = "「文字に書かれた知識の蓄積は一切できないと思って頂戴？　自慢じゃないけれど、教科書だって読んだ試しがないもの」"

[[dialogue]]
speaker = "レティシア"
# 「授業中は、訓練に備えて眠っているくらい。<ruby=アクティブレスト>積極的休養</ruby>、というやつね」
line = "「授業中は、訓練に備えて眠っているくらい。<ruby>積極的休養<rt>アクティブレスト</rt></ruby>、というやつね」"

[[dialogue]]
speaker = "マトイ"
# 「もうやめましょう、それ！　本当に自慢じゃないです！　あとアクティブレストもぜんぜん意味が違うと思います！！」
line = "「もうやめましょう、それ！　本当に自慢じゃないです！　あとアクティブレストもぜんぜん意味が違うと思います！！」"

[[dialogue]]
speaker = "レティシア"
# 「でも私より成績の悪い子が、デネブには何人かいるのよね……少し心配になっちゃうわ。大丈夫かしら……？」
line = "「でも私より成績の悪い子が、デネブには何人かいるのよね……少し心配になっちゃうわ。大丈夫かしら……？」"

[[dialogue]]
speaker = "unk"
# 他人の心配してる場合じゃない！！
line = "他人の心配してる場合じゃない！！"

[[dialogue]]
speaker = "チナ"
# 「まあそんなわけだから……レティシアに聞いても何も進まないぞってことは教えとくよ……」
line = "「まあそんなわけだから……レティシアに聞いても何も進まないぞってことは教えとくよ……」"

[[dialogue]]
speaker = "unk"
# レティシアは勉強ができない──それだけでなく。
line = "レティシアは勉強ができない──それだけでなく。"

[[dialogue]]
speaker = "unk"
# 極星星徒会のメンバーの、意外な成績事情を知ってしまう俺とマトイなのだった……
line = "極星星徒会のメンバーの、意外な成績事情を知ってしまう俺とマトイなのだった……"
