[[dialogue]]
speaker = "unk"
# 第１話,衝撃の出会い,P
line = "第１話,衝撃の出会い,P"

[[dialogue]]
speaker = "unk"
# ぶぉーん、ぶぉーん、ぶぉーん、ぶぉーん……
line = "ぶぉーん、ぶぉーん、ぶぉーん、ぶぉーん……"

[[dialogue]]
speaker = "unk"
# ぶぉーん、ぶぉーん、ぶぉーん、ぶぉーん……
line = "ぶぉーん、ぶぉーん、ぶぉーん、ぶぉーん……"

[[dialogue]]
speaker = "unk"
# ぶぉーん、ぶぉーん、ぶぉーん、ぶぉーん……
line = "ぶぉーん、ぶぉーん、ぶぉーん、ぶぉーん……"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「おほぉおおっ！！！」
line = "「おほぉおおっ！！！」"

[[dialogue]]
speaker = "unk"
# ぶぉーん、ぶぉーん、ぶぉーん、ぶぉーん……
line = "ぶぉーん、ぶぉーん、ぶぉーん、ぶぉーん……"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「うひひひひ、すっごぉいいいっ♪」
line = "「うひひひひ、すっごぉいいいっ♪」"

[[dialogue]]
speaker = "unk"
# な、何してるの……かな？
line = "な、何してるの……かな？"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「アタシはね、今とっっっっっても感動してるんだよ！」
line = "「アタシはね、今とっっっっっても感動してるんだよ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「何にって？　決まってるじゃない、この運命の出会いにさっ！」
line = "「何にって？　決まってるじゃない、この運命の出会いにさっ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ふっふっふ……じゃーん♪　おにーさん、これ何だかわかる？」
line = "「ふっふっふ……じゃーん♪　おにーさん、これ何だかわかる？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「え……『でんま』？」
line = "「え……『でんま』？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「あ～、『電気マッサージ器』だから略して『でんま』なんだ。たはは、可愛くっていいね～♪」
line = "「あ～、『電気マッサージ器』だから略して『でんま』なんだ。たはは、可愛くっていいね～♪」"

[[dialogue]]
speaker = "unk"
# 運命の出会いって、それ？
line = "運命の出会いって、それ？"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「その通りだよん。何となーく立ち寄った電気屋さんで、こんな素晴らしいものに出会えるなんて」
line = "「その通りだよん。何となーく立ち寄った電気屋さんで、こんな素晴らしいものに出会えるなんて」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「スイッチひとつでモーターが回転して、先端部分を小刻みに震わせる」
line = "「スイッチひとつでモーターが回転して、先端部分を小刻みに震わせる」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「それを身体に押し当てることで、コリがほぐれて気持ちよくなれる……」
line = "「それを身体に押し当てることで、コリがほぐれて気持ちよくなれる……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「超シンプルな仕組みだけど目的のためにわき目も振らず、全てをこの１本に集約させてる！」
line = "「超シンプルな仕組みだけど目的のためにわき目も振らず、全てをこの１本に集約させてる！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「発想、技術、素材へのこだわり……全てが素晴らしいんだ！　神は細部に宿るというけれど、発明とはかく在るべきって理想を体現してるよ！」
line = "「発想、技術、素材へのこだわり……全てが素晴らしいんだ！　神は細部に宿るというけれど、発明とはかく在るべきって理想を体現してるよ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「人間界の発明品にはいつも驚かされるけど、今日ほど心が躍ったのは久しぶりだね！」
line = "「人間界の発明品にはいつも驚かされるけど、今日ほど心が躍ったのは久しぶりだね！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「魔女の森の老人たちも目を覚ますべきだよ。魔力にばかり頼って技術を育てない自らの愚かしさをさ！」
line = "「魔女の森の老人たちも目を覚ますべきだよ。魔力にばかり頼って技術を育てない自らの愚かしさをさ！」"

[[dialogue]]
speaker = "unk"
# 君は魔女なの？
line = "君は魔女なの？"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「うん、そうだよ。アタシはネビュラ所属の研究員、ツェツィーリエ。気軽にツェツィって呼んでよ」
line = "「うん、そうだよ。アタシはネビュラ所属の研究員、ツェツィーリエ。気軽にツェツィって呼んでよ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「そんなに軽々しく名乗っちゃって平気なのかって？」
line = "「そんなに軽々しく名乗っちゃって平気なのかって？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ま、ダイジョーブでしょ。リクリエを退けた今となっちゃ魔女の存在を隠さなきゃいけないってこともないだろうし」
line = "「ま、ダイジョーブでしょ。リクリエを退けた今となっちゃ魔女の存在を隠さなきゃいけないってこともないだろうし」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「そんなことよりさ、さっそく試してみようと思うんだよ」
line = "「そんなことよりさ、さっそく試してみようと思うんだよ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「アタシもデスクワークが多くてさ、肩もこっちゃってるってわけ」
line = "「アタシもデスクワークが多くてさ、肩もこっちゃってるってわけ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「……それじゃ早速……あ、あああっ……！　こ、これはっ……！」
line = "「……それじゃ早速……あ、あああっ……！　こ、これはっ……！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「んうううっ、あっ、き、きくぅっ！」
line = "「んうううっ、あっ、き、きくぅっ！」"

[[dialogue]]
speaker = "unk"
# もう少し声を抑えて！
line = "もう少し声を抑えて！"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ああ、ごめんごめん、こんなに気持ちいいとは思ってなくて、つい声が出ちゃったよ」
line = "「ああ、ごめんごめん、こんなに気持ちいいとは思ってなくて、つい声が出ちゃったよ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「でもそれだけこの『でんま』が素晴らしいものだって証明されたわけだ！」
line = "「でもそれだけこの『でんま』が素晴らしいものだって証明されたわけだ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「研究室に帰ったら早速分解してみなくっちゃ」
line = "「研究室に帰ったら早速分解してみなくっちゃ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「うひひ、この可愛い可愛い『でんま』ちゃんをひん剥いて丸裸にしてやるのが待ちきれないよぉ♪」
line = "「うひひ、この可愛い可愛い『でんま』ちゃんをひん剥いて丸裸にしてやるのが待ちきれないよぉ♪」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「おやおや、またしても失礼。興奮して大きな声が出ちゃってたよ」
line = "「おやおや、またしても失礼。興奮して大きな声が出ちゃってたよ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「おにーさんには恥ずかしいとこ見られっぱなしだね、参った参った──ん？」
line = "「おにーさんには恥ずかしいとこ見られっぱなしだね、参った参った──ん？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「もしかしてキミ……噂の魔王ちゃんだよねぇ？」
line = "「もしかしてキミ……噂の魔王ちゃんだよねぇ？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「うん、間違いない。やーやーお近づきになれて光栄だよ～」
line = "「うん、間違いない。やーやーお近づきになれて光栄だよ～」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「もちろんキミのことは知ってるよ。有名人だからね」
line = "「もちろんキミのことは知ってるよ。有名人だからね」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「アタシは戦闘員じゃないから参加してなかったけど、作戦会議とかだとよく名前が挙がってたみたいだよ」
line = "「アタシは戦闘員じゃないから参加してなかったけど、作戦会議とかだとよく名前が挙がってたみたいだよ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「世界樹を使わせて欲しいって基地に来た時も、研究室のメンバー総出で野次馬しにいったもんさ♪」
line = "「世界樹を使わせて欲しいって基地に来た時も、研究室のメンバー総出で野次馬しにいったもんさ♪」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「なにしろ研究対象としてとんでもなく魅力的な存在だからね、キミは」
line = "「なにしろ研究対象としてとんでもなく魅力的な存在だからね、キミは」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「アタシもキミへの関心は尽きないよ。いずれ研究室に持ち帰って隅々までじっくり調べさせてもらうつもりだからヨロシクね～」
line = "「アタシもキミへの関心は尽きないよ。いずれ研究室に持ち帰って隅々までじっくり調べさせてもらうつもりだからヨロシクね～」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「なーんて冗談冗談、そんなに怯えなくても大丈夫だよん♪」
line = "「なーんて冗談冗談、そんなに怯えなくても大丈夫だよん♪」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「まあ今日のところは『でんま』で忙しいからこれで。また近いうちに声をかけるから連絡先をぷりーず♪」
line = "「まあ今日のところは『でんま』で忙しいからこれで。また近いうちに声をかけるから連絡先をぷりーず♪」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「たはは、この感動を共に分かちあえて良かったよ、ありがと～♪」
line = "「たはは、この感動を共に分かちあえて良かったよ、ありがと～♪」"

[[dialogue]]
speaker = "unk"
# 勢いに押されるがまま、連絡先を交換してしまった。
line = "勢いに押されるがまま、連絡先を交換してしまった。"

[[dialogue]]
speaker = "unk"
# 何だか危なそうなヒトだったけど……大丈夫だったんだろうか？
line = "何だか危なそうなヒトだったけど……大丈夫だったんだろうか？"
