[[dialogue]]
speaker = "unk"
# 第２話,グレイスとエステル,P
line = "第２話,グレイスとエステル,P"

[[dialogue]]
speaker = "グレイス"
# 「魔王さん、わざわざありがとうございます」
line = "「魔王さん、わざわざありがとうございます」"

[[dialogue]]
speaker = "unk"
# 俺に用事があるって？
line = "俺に用事があるって？"

[[dialogue]]
speaker = "グレイス"
# 「はい。小耳に挟んだのですが、私たちに先んじて、アルタイルの世界にエステルが来ているんですよね？」
line = "「はい。小耳に挟んだのですが、私たちに先んじて、アルタイルの世界にエステルが来ているんですよね？」"

[[dialogue]]
speaker = "グレイス"
# 「あの子と会ってお話がしたいんですけれど、取次ぎをお願いできますか……？」
line = "「あの子と会ってお話がしたいんですけれど、取次ぎをお願いできますか……？」"

[[dialogue]]
speaker = "unk"
# 問題ないよ。エステルも喜ぶと思う
line = "問題ないよ。エステルも喜ぶと思う"

[[dialogue]]
speaker = "グレイス"
# 「……そう、でしょうか。あはは」
line = "「……そう、でしょうか。あはは」"

[[dialogue]]
speaker = "グレイス"
# 「私とあの子はそりが合わない──って言ったらお互いに問題があるように聞こえちゃいますね」
line = "「私とあの子はそりが合わない──って言ったらお互いに問題があるように聞こえちゃいますね」"

[[dialogue]]
speaker = "グレイス"
# 「あの子は何も悪くないんです。私が一方的に苦手意識を持って、デネブにいた頃はぎくしゃくしてたんです……」
line = "「あの子は何も悪くないんです。私が一方的に苦手意識を持って、デネブにいた頃はぎくしゃくしてたんです……」"

[[dialogue]]
speaker = "グレイス"
# 「──だから謝りたくて。エステルと一度、お話をさせてくれませんか？」
line = "「──だから謝りたくて。エステルと一度、お話をさせてくれませんか？」"

[[dialogue]]
speaker = "unk"
# 俺はフィオナに連絡を取り、星見家の邸宅の一室で、グレイスとエステルを引き合わせることにした。
line = "俺はフィオナに連絡を取り、星見家の邸宅の一室で、グレイスとエステルを引き合わせることにした。"

[[dialogue]]
speaker = "エステル"
# 「グレイス先輩、お久しぶりです！」
line = "「グレイス先輩、お久しぶりです！」"

[[dialogue]]
speaker = "グレイス"
# 「は、はい。エステルも、元気そうで……」
line = "「は、はい。エステルも、元気そうで……」"

[[dialogue]]
speaker = "エステル"
# 「わざわざ私の顔を見に来ていただけるだなんて嬉しいです。本日はどのような……？」
line = "「わざわざ私の顔を見に来ていただけるだなんて嬉しいです。本日はどのような……？」"

[[dialogue]]
speaker = "グレイス"
# 「そ、そのこと、なのですが……ええと……」
line = "「そ、そのこと、なのですが……ええと……」"

[[dialogue]]
speaker = "unk"
# エステルに謝りたいんだって
line = "エステルに謝りたいんだって"

[[dialogue]]
speaker = "エステル"
# 「謝る、ですか……？　あっ、もしかして──」
line = "「謝る、ですか……？　あっ、もしかして──」"

[[dialogue]]
speaker = "グレイス"
# 「はい。ちょっと前にデネブであった、あの一件のことで……」
line = "「はい。ちょっと前にデネブであった、あの一件のことで……」"

[[dialogue]]
speaker = "グレイス"
# 「あれっ？　エステル、手帳から何か落ちましたよ！　拾ってあげますね！」
line = "「あれっ？　エステル、手帳から何か落ちましたよ！　拾ってあげますね！」"

[[dialogue]]
speaker = "エステル"
# 「あっ──」
line = "「あっ──」"

[[dialogue]]
speaker = "グレイス"
# 「……こ、これはっ！？」
line = "「……こ、これはっ！？」"

[[dialogue]]
speaker = "unk"
# グレイスが拾ったのは、ぼろぼろに擦りきれた雑誌の１ページ──その切り抜きだった。
line = "グレイスが拾ったのは、ぼろぼろに擦りきれた雑誌の１ページ──その切り抜きだった。"

[[dialogue]]
speaker = "unk"
# 『流星市国を守る、新星学園の星徒会長に迫る』と銘打たれた記事と、１人の星騎士の写真──
line = "『流星市国を守る、新星学園の星徒会長に迫る』と銘打たれた記事と、１人の星騎士の写真──"

[[dialogue]]
speaker = "グレイス"
# 「緋宮、クロト……！」
line = "「緋宮、クロト……！」"

[[dialogue]]
speaker = "エステル"
# 「す、すみません、グレイス先輩……あの……」
line = "「す、すみません、グレイス先輩……あの……」"

[[dialogue]]
speaker = "グレイス"
# 「どうして……こんなものを？　エステル、この男は裏切り者ですよ！？」
line = "「どうして……こんなものを？　エステル、この男は裏切り者ですよ！？」"

[[dialogue]]
speaker = "エステル"
# 「……グレイス先輩。そんなこと、仰らないでください……魔王様は何も悪いことなど……」
line = "「……グレイス先輩。そんなこと、仰らないでください……魔王様は何も悪いことなど……」"

[[dialogue]]
speaker = "グレイス"
# 「目を覚ましてください！　こいつはデネブを……私たちを見捨てたんです！　自分だけが助かるために！！」
line = "「目を覚ましてください！　こいつはデネブを……私たちを見捨てたんです！　自分だけが助かるために！！」"

[[dialogue]]
speaker = "エステル"
# 「……違います。きっと何か、誤解があるはずなんです……」
line = "「……違います。きっと何か、誤解があるはずなんです……」"

[[dialogue]]
speaker = "エステル"
# 「私はかつて、魔王様に命を救われました。あの御方がいなかったら今、私は生きていません……命の、恩人なんです……」
line = "「私はかつて、魔王様に命を救われました。あの御方がいなかったら今、私は生きていません……命の、恩人なんです……」"

[[dialogue]]
speaker = "グレイス"
# 「…………！！」
line = "「…………！！」"

[[dialogue]]
speaker = "エステル"
# 「ルヴィネ会長のお言葉も、女神様のお話も、理解はしています。でも私は、信じているんです……」
line = "「ルヴィネ会長のお言葉も、女神様のお話も、理解はしています。でも私は、信じているんです……」"

[[dialogue]]
speaker = "グレイス"
# （…………この子は、まだ？）
line = "（…………この子は、まだ？）"

[[dialogue]]
speaker = "グレイス"
# （…………私はとっくに、諦めたのに）
line = "（…………私はとっくに、諦めたのに）"

[[dialogue]]
speaker = "グレイス"
# 「……返します。ですが、これはお家の引き出しにでも入れておいてください。持ち歩くのは感心しません」
line = "「……返します。ですが、これはお家の引き出しにでも入れておいてください。持ち歩くのは感心しません」"

[[dialogue]]
speaker = "エステル"
# 「い、いいんですか……？　ありがとうございます……！」
line = "「い、いいんですか……？　ありがとうございます……！」"

[[dialogue]]
speaker = "グレイス"
# 「……私は何も見ていません。だからお礼なんて、いりません」
line = "「……私は何も見ていません。だからお礼なんて、いりません」"

[[dialogue]]
speaker = "グレイス"
# 「アルタイルにやってきて……真実を知りました。デネブの魔王さんは裏切ってなんかいないって」
line = "「アルタイルにやってきて……真実を知りました。デネブの魔王さんは裏切ってなんかいないって」"

[[dialogue]]
speaker = "エステル"
# 「……はい」
line = "「……はい」"

[[dialogue]]
speaker = "グレイス"
# 「あの時から私、変にエステルのことを意識して……つっけんどんな態度、いっぱい取っちゃいました。だから……ごめんなさい」
line = "「あの時から私、変にエステルのことを意識して……つっけんどんな態度、いっぱい取っちゃいました。だから……ごめんなさい」"

[[dialogue]]
speaker = "エステル"
# 「そんな……謝らないでください。私、気にしていません。ベアトリス副会長から、色々お話も聞いていますし……」
line = "「そんな……謝らないでください。私、気にしていません。ベアトリス副会長から、色々お話も聞いていますし……」"

[[dialogue]]
speaker = "グレイス"
# 「──ベアトから？」
line = "「──ベアトから？」"

[[dialogue]]
speaker = "エステル"
# 「はい。グレイス先輩と私の様子を心配して、声をかけてくださって……」
line = "「はい。グレイス先輩と私の様子を心配して、声をかけてくださって……」"

[[dialogue]]
speaker = "エステル"
# 「その時に聞きました。グレイス先輩は昔、魔王様のことを信じていたと……」
line = "「その時に聞きました。グレイス先輩は昔、魔王様のことを信じていたと……」"

[[dialogue]]
speaker = "エステル"
# 「流星群の後の避難地で、魔王様の潔白を誰よりも強く訴えていたのが、グレイス先輩だと聞きました」
line = "「流星群の後の避難地で、魔王様の潔白を誰よりも強く訴えていたのが、グレイス先輩だと聞きました」"

[[dialogue]]
speaker = "グレイス"
# 「でも結局……私は信じるのをやめました。エステルは、強いですね……」
line = "「でも結局……私は信じるのをやめました。エステルは、強いですね……」"

[[dialogue]]
speaker = "エステル"
# 「やめざるを得なかっただけだと思います。１０年前のあの騒動を現地で経験すれば……無理もありません」
line = "「やめざるを得なかっただけだと思います。１０年前のあの騒動を現地で経験すれば……無理もありません」"

[[dialogue]]
speaker = "エステル"
# 「私はあの時、両親と一緒に市国の外に避難していました──家族が、いましたから……」
line = "「私はあの時、両親と一緒に市国の外に避難していました──家族が、いましたから……」"

[[dialogue]]
speaker = "エステル"
# 「でもご両親を亡くされた、幼い頃のグレイス先輩は……心を守るためにも魔王様を恨むしかなかった……」
line = "「でもご両親を亡くされた、幼い頃のグレイス先輩は……心を守るためにも魔王様を恨むしかなかった……」"

[[dialogue]]
speaker = "エステル"
# 「だから私、何も気にしていません。お気になさらないでください」
line = "「だから私、何も気にしていません。お気になさらないでください」"

[[dialogue]]
speaker = "グレイス"
# 「……ありがとうございます。エステル、その……これからは、仲良くしてもらえると嬉しいです」
line = "「……ありがとうございます。エステル、その……これからは、仲良くしてもらえると嬉しいです」"

[[dialogue]]
speaker = "エステル"
# 「こちらこそ、喜んで！」
line = "「こちらこそ、喜んで！」"

[[dialogue]]
speaker = "ナミエル"
# 「失礼します。お客さまがいらっしゃると聞いて……お茶をお持ちしました」
line = "「失礼します。お客さまがいらっしゃると聞いて……お茶をお持ちしました」"

[[dialogue]]
speaker = "エステル"
# 「ナミエルさん。ありがとうございます♪」
line = "「ナミエルさん。ありがとうございます♪」"

[[dialogue]]
speaker = "ナミエル"
# 「はい。そしてグレイスさま、初めまして。星見家メイド隊のナミエルと申します」
line = "「はい。そしてグレイスさま、初めまして。星見家メイド隊のナミエルと申します」"

[[dialogue]]
speaker = "グレイス"
# 「ど、どうもっ！　初めまして！」
line = "「ど、どうもっ！　初めまして！」"

[[dialogue]]
speaker = "ナミエル"
# 「エステルさまのご学友なのですよね？」
line = "「エステルさまのご学友なのですよね？」"

[[dialogue]]
speaker = "エステル"
# 「はい。頼りになるプリマステラの先輩で──」
line = "「はい。頼りになるプリマステラの先輩で──」"

[[dialogue]]
speaker = "エステル"
# 「私と同じく、魔王様を深く深く敬愛する方ですよ♪」
line = "「私と同じく、魔王様を深く深く敬愛する方ですよ♪」"

[[dialogue]]
speaker = "ナミエル"
# 「…………えっ？」
line = "「…………えっ？」"

[[dialogue]]
speaker = "ナミエル"
# 「ま、また強火魔王信者が増えた、ということですか……！？」
line = "「ま、また強火魔王信者が増えた、ということですか……！？」"

[[dialogue]]
speaker = "unk"
# 強火魔王信者──なんだそれ！？
line = "強火魔王信者──なんだそれ！？"

[[dialogue]]
speaker = "エステル"
# 「私は幼き頃、魔王様に命を救われた身です……この身も心も捧げるのは当然のことです♪」
line = "「私は幼き頃、魔王様に命を救われた身です……この身も心も捧げるのは当然のことです♪」"

[[dialogue]]
speaker = "グレイス"
# 「このグレイス・オベロニア！　魔王さんとの約束のために、命を懸けて戦いますとも！」
line = "「このグレイス・オベロニア！　魔王さんとの約束のために、命を懸けて戦いますとも！」"

[[dialogue]]
speaker = "ナミエル"
# 「どうして緋宮会長は、出会う女性をことごとく落としていくのです？　えっちなのは許しませんよ」
line = "「どうして緋宮会長は、出会う女性をことごとく落としていくのです？　えっちなのは許しませんよ」"

[[dialogue]]
speaker = "unk"
# 濡れ衣だ！？！？
line = "濡れ衣だ！？！？"

[[dialogue]]
speaker = "unk"
# グレイスとエステルのわだかまりが溶けたのは良いとして……
line = "グレイスとエステルのわだかまりが溶けたのは良いとして……"

[[dialogue]]
speaker = "ナミエル"
# 「お嬢様には改めて、プレイボーイな緋宮会長を警戒するよう進言しておきましょう」
line = "「お嬢様には改めて、プレイボーイな緋宮会長を警戒するよう進言しておきましょう」"

[[dialogue]]
speaker = "unk"
# 俺はナミエルから冷ややかな視線を貰うことになるのだった……
line = "俺はナミエルから冷ややかな視線を貰うことになるのだった……"

[[dialogue]]
speaker = "unk"
# ──なんで？？？？？
line = "──なんで？？？？？"
