[[dialogue]]
speaker = "unk"
# 第４話,指切りげんまん,P
line = "第４話,指切りげんまん,P"

[[dialogue]]
speaker = "unk"
# グレイスと同じ時間を過ごすうち、俺は彼女のことを１人の異性として意識するようになっていた。
line = "グレイスと同じ時間を過ごすうち、俺は彼女のことを１人の異性として意識するようになっていた。"

[[dialogue]]
speaker = "unk"
# だから意を決して、休日にグレイスを遊びに誘うことにした──
line = "だから意を決して、休日にグレイスを遊びに誘うことにした──"

[[dialogue]]
speaker = "グレイス"
# 「まさか魔王さんに、遊園地に誘っていただけるだなんて──驚きました！」
line = "「まさか魔王さんに、遊園地に誘っていただけるだなんて──驚きました！」"

[[dialogue]]
speaker = "グレイス"
# 「でもでも、私だけなんて他の皆に悪い気が……」
line = "「でもでも、私だけなんて他の皆に悪い気が……」"

[[dialogue]]
speaker = "unk"
# これ、２人用なんだ
line = "これ、２人用なんだ"

[[dialogue]]
speaker = "unk"
# バイトしてた時のチケットが余っててね
line = "バイトしてた時のチケットが余っててね"

[[dialogue]]
speaker = "グレイス"
# 「なるほどです！　じゃあ仕方がないですね！　チナたちには悪いですが、今日は楽しませてもらいます！」
line = "「なるほどです！　じゃあ仕方がないですね！　チナたちには悪いですが、今日は楽しませてもらいます！」"

[[dialogue]]
speaker = "グレイス"
# 「でも……あはは。ちょ、ちょっとドキドキしますね……魔王さんと２人きりでお出かけだなんて」
line = "「でも……あはは。ちょ、ちょっとドキドキしますね……魔王さんと２人きりでお出かけだなんて」"

[[dialogue]]
speaker = "グレイス"
# 「な、なんだかデートみたいじゃありませんか……！？」
line = "「な、なんだかデートみたいじゃありませんか……！？」"

[[dialogue]]
speaker = "グレイス"
# 「あ──い、いえいえ！　誤解はしてないですよ！？　あくまで余ってたチケットでお誘いしてもらっただけですし！」
line = "「あ──い、いえいえ！　誤解はしてないですよ！？　あくまで余ってたチケットでお誘いしてもらっただけですし！」"

[[dialogue]]
speaker = "グレイス"
# 「故郷を離れた、平行世界人の私をおもてなししてくれてるだけって、ええもうバッチリわかってますとも……！」
line = "「故郷を離れた、平行世界人の私をおもてなししてくれてるだけって、ええもうバッチリわかってますとも……！」"

[[dialogue]]
speaker = "グレイス"
# 「魔王さんの周りには可愛い女の子もたくさんいらっしゃいますし、ええもうこれっぽっちも乙女のトキメキ的な誤解なんて──」
line = "「魔王さんの周りには可愛い女の子もたくさんいらっしゃいますし、ええもうこれっぽっちも乙女のトキメキ的な誤解なんて──」"

[[dialogue]]
speaker = "unk"
# えっと……デートのお誘い、なんだけど
line = "えっと……デートのお誘い、なんだけど"

[[dialogue]]
speaker = "グレイス"
# 「はえぇええ──っ！？」
line = "「はえぇええ──っ！？」"

[[dialogue]]
speaker = "グレイス"
# 「あ、あれれっ……ま、マジのやつです？　これ、デートだったんです！？」
line = "「あ、あれれっ……ま、マジのやつです？　これ、デートだったんです！？」"

[[dialogue]]
speaker = "unk"
# ──あれは嘘だ
line = "──あれは嘘だ"

[[dialogue]]
speaker = "unk"
# このチケット、余っていたと伝えたな
line = "このチケット、余っていたと伝えたな"

[[dialogue]]
speaker = "グレイス"
# 「そんなっ！？　嘘だったのですか！？」
line = "「そんなっ！？　嘘だったのですか！？」"

[[dialogue]]
speaker = "グレイス"
# 「私とお出かけするために、わざわざ買った……ですか？」
line = "「私とお出かけするために、わざわざ買った……ですか？」"

[[dialogue]]
speaker = "グレイス"
# 「えっ、えっえっえっ──じゃ、じゃあ……本当の本当に……デート？」
line = "「えっ、えっえっえっ──じゃ、じゃあ……本当の本当に……デート？」"

[[dialogue]]
speaker = "グレイス"
# 「……………………ぷしゅー」
line = "「……………………ぷしゅー」"

[[dialogue]]
speaker = "unk"
# 顔を真っ赤にして、フリーズしてしまった……
line = "顔を真っ赤にして、フリーズしてしまった……"

[[dialogue]]
speaker = "unk"
# と、とりあえずアトラクションを楽しもう……！！
line = "と、とりあえずアトラクションを楽しもう……！！"

[[dialogue]]
speaker = "遊園地のスタッフ"
# 「お２人ですね。チケットを拝見いたします」
line = "「お２人ですね。チケットを拝見いたします」"

[[dialogue]]
speaker = "グレイス"
# 「…………う、うすっ」
line = "「…………う、うすっ」"

[[dialogue]]
speaker = "遊園地のスタッフ"
# 「はい、確認いたしました。どうぞお楽しみください♪」
line = "「はい、確認いたしました。どうぞお楽しみください♪」"

[[dialogue]]
speaker = "グレイス"
# 「…………お、おすっ」
line = "「…………お、おすっ」"

[[dialogue]]
speaker = "unk"
# 口調もなんか変だし……
line = "口調もなんか変だし……"

[[dialogue]]
speaker = "unk"
# 右手と右足が一緒に出てるし……
line = "右手と右足が一緒に出てるし……"

[[dialogue]]
speaker = "グレイス"
# 「い、意識しちゃって……あうあう……」
line = "「い、意識しちゃって……あうあう……」"

[[dialogue]]
speaker = "グレイス"
# 「──きゃっ！？　躓いて──」
line = "「──きゃっ！？　躓いて──」"

[[dialogue]]
speaker = "unk"
# おっと！
line = "おっと！"

[[dialogue]]
speaker = "グレイス"
# 「あ、あぁぁあ……私の肩を、ギュって……力、強い……」
line = "「あ、あぁぁあ……私の肩を、ギュって……力、強い……」"

[[dialogue]]
speaker = "グレイス"
# 「……………………ぷっしゅ～」
line = "「……………………ぷっしゅ～」"

[[dialogue]]
speaker = "unk"
# 手、繋いでいこうか
line = "手、繋いでいこうか"

[[dialogue]]
speaker = "グレイス"
# 「……あ、あい。よろしく、お願い、シマス……」
line = "「……あ、あい。よろしく、お願い、シマス……」"

[[dialogue]]
speaker = "unk"
# ここまで意識されてしまうだなんてびっくりだけど、悪い気はしない。
line = "ここまで意識されてしまうだなんてびっくりだけど、悪い気はしない。"

[[dialogue]]
speaker = "unk"
# 俺は彼女の緊張がほぐせるように、遊園地中を連れまわすのだった──
line = "俺は彼女の緊張がほぐせるように、遊園地中を連れまわすのだった──"

[[dialogue]]
speaker = "グレイス"
# 「いきなりのデートという展開に、受け入れるのに少し時間がかかりましたが……」
line = "「いきなりのデートという展開に、受け入れるのに少し時間がかかりましたが……」"

[[dialogue]]
speaker = "グレイス"
# 「──とっても楽しかったです！　お誘いいただきありがとうございましたっ！」
line = "「──とっても楽しかったです！　お誘いいただきありがとうございましたっ！」"

[[dialogue]]
speaker = "unk"
# いつものグレイスに戻ってくれてよかった
line = "いつものグレイスに戻ってくれてよかった"

[[dialogue]]
speaker = "グレイス"
# 「あはは……お恥ずかしい限りです。昔から、女の子の友達とばかり遊んでましたし……」
line = "「あはは……お恥ずかしい限りです。昔から、女の子の友達とばかり遊んでましたし……」"

[[dialogue]]
speaker = "グレイス"
# 「男の子と２人きりのお出かけも、デートも初めてだったので……」
line = "「男の子と２人きりのお出かけも、デートも初めてだったので……」"

[[dialogue]]
speaker = "unk"
# グレイス、モテそうだけど
line = "グレイス、モテそうだけど"

[[dialogue]]
speaker = "グレイス"
# 「そ、そう見えます？　んー……まあ、手紙とかは、ちょくちょく貰いますけれど」
line = "「そ、そう見えます？　んー……まあ、手紙とかは、ちょくちょく貰いますけれど」"

[[dialogue]]
speaker = "グレイス"
# 「全部断ってました。星徒会のお仕事で忙しいですし、それに──」
line = "「全部断ってました。星徒会のお仕事で忙しいですし、それに──」"

[[dialogue]]
speaker = "グレイス"
# 「私、好きな人がいるんです。ずっと昔から……」
line = "「私、好きな人がいるんです。ずっと昔から……」"

[[dialogue]]
speaker = "グレイス"
# 「えへへ、でもその人、彼女がいたので。告白する前から振られちゃったんですけどね！」
line = "「えへへ、でもその人、彼女がいたので。告白する前から振られちゃったんですけどね！」"

[[dialogue]]
speaker = "グレイス"
# 「……あれだけ意識してたら、ごまかしても無駄だから言っちゃいますけど。魔王さん、ですからね？」
line = "「……あれだけ意識してたら、ごまかしても無駄だから言っちゃいますけど。魔王さん、ですからね？」"

[[dialogue]]
speaker = "グレイス"
# 「１０年間、ずーっと蓋をしてきましたけど。本当は……ずっとずっと、大好きでした……」
line = "「１０年間、ずーっと蓋をしてきましたけど。本当は……ずっとずっと、大好きでした……」"

[[dialogue]]
speaker = "unk"
# 君の好きな人と俺は、正確には違う
line = "君の好きな人と俺は、正確には違う"

[[dialogue]]
speaker = "グレイス"
# 「……そうですね。あの人はもういません」
line = "「……そうですね。あの人はもういません」"

[[dialogue]]
speaker = "unk"
# グレイスのことが好きだよ
line = "グレイスのことが好きだよ"

[[dialogue]]
speaker = "unk"
# でも、アルタイルの俺は──
line = "でも、アルタイルの俺は──"

[[dialogue]]
speaker = "グレイス"
# 「…………っ！」
line = "「…………っ！」"

[[dialogue]]
speaker = "unk"
# だから……俺の恋人になってくれないか
line = "だから……俺の恋人になってくれないか"

[[dialogue]]
speaker = "unk"
# 君の憧れの人に近づけるよう努力をする
line = "君の憧れの人に近づけるよう努力をする"

[[dialogue]]
speaker = "グレイス"
# 「…………嬉しいです、魔王さん」
line = "「…………嬉しいです、魔王さん」"

[[dialogue]]
speaker = "グレイス"
# 「──はい。私を、あなたの彼女にしてください！」
line = "「──はい。私を、あなたの彼女にしてください！」"

[[dialogue]]
speaker = "グレイス"
# 「約束してくれますか。今度こそ……私の前からいなくならないって！」
line = "「約束してくれますか。今度こそ……私の前からいなくならないって！」"

[[dialogue]]
speaker = "unk"
# そうして俺は頷き──グレイスの差しだした小指に、自身の小指を絡めて。
line = "そうして俺は頷き──グレイスの差しだした小指に、自身の小指を絡めて。"

[[dialogue]]
speaker = "unk"
# １０年越しの、世界すらを飛び越えた指切りをもう一度交わすのだった──
line = "１０年越しの、世界すらを飛び越えた指切りをもう一度交わすのだった──"
