[[dialogue]]
speaker = "unk"
# 第１話,ルヴィネ（妹）,P
line = "第１話,ルヴィネ（妹）,P"

[[dialogue]]
speaker = "unk"
# 創造神『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』に勝利した記念に行われた、アルタイルでの祝勝会──その翌日。
line = "創造神『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』に勝利した記念に行われた、アルタイルでの祝勝会──その翌日。"

[[dialogue]]
speaker = "unk"
# ルヴィネが新星学園の星徒会室を訪ねてきた。
line = "ルヴィネが新星学園の星徒会室を訪ねてきた。"

[[dialogue]]
speaker = "アナ"
# 「ようこそいらっしゃいました。お茶をどうぞ、ルヴィネさん」
line = "「ようこそいらっしゃいました。お茶をどうぞ、ルヴィネさん」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ありがとう、アナ。ん……いい味だわ」
line = "「ありがとう、アナ。ん……いい味だわ」"

[[dialogue]]
speaker = "マトイ"
# 「ゆっくりしていってね、ルヴィネちゃん♪」
line = "「ゆっくりしていってね、ルヴィネちゃん♪」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ええ──今日は極星の皆、用事があるみたいなの。時間を持て余していたから助かるわ」
line = "「ええ──今日は極星の皆、用事があるみたいなの。時間を持て余していたから助かるわ」"

[[dialogue]]
speaker = "unk"
# デネブからやってきた極星学園のみんなは、今日から数日間、アルタイルに滞在する予定になっている。
line = "デネブからやってきた極星学園のみんなは、今日から数日間、アルタイルに滞在する予定になっている。"

[[dialogue]]
speaker = "unk"
# ベアトリスは選管メンバーと遊びに。チナやグレイスは家族水入らずで過ごすとのことだ。
line = "ベアトリスは選管メンバーと遊びに。チナやグレイスは家族水入らずで過ごすとのことだ。"

[[dialogue]]
speaker = "unk"
# 意外なことに、レティシアも祝勝会でナミエルと打ち解けたらしく、今日は星見家にお邪魔しているらしい──
line = "意外なことに、レティシアも祝勝会でナミエルと打ち解けたらしく、今日は星見家にお邪魔しているらしい──"

[[dialogue]]
speaker = "ヴィーナス"
# 「なるほど～。それでルヴィネおばちゃん、寂しくってうちの星徒会室に来たってわけね！」
line = "「なるほど～。それでルヴィネおばちゃん、寂しくってうちの星徒会室に来たってわけね！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「九浄ヴィーナス。別に私は寂しがってなんかいないわ」
line = "「九浄ヴィーナス。別に私は寂しがってなんかいないわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「──って、待ちなさい。貴女、今なんて？」
line = "「──って、待ちなさい。貴女、今なんて？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「？　ルヴィネおばちゃん──」
line = "「？　ルヴィネおばちゃん──」"

[[dialogue]]
speaker = "ルヴィネ"
# 「どういうこと……！？」
line = "「どういうこと……！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ルヴィネはママの妹なんでしょう？　ママとのお別れの時も、『姉さん』って呼んでたものね！」
line = "「ルヴィネはママの妹なんでしょう？　ママとのお別れの時も、『姉さん』って呼んでたものね！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「まあ……そうね。同じ父から創造された者同士、姉妹のようなものには違いないわ」
line = "「まあ……そうね。同じ父から創造された者同士、姉妹のようなものには違いないわ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ママの妹ってことは──つまり、私のおばさんじゃない！　だから『ルヴィネおばちゃん』♪」
line = "「ママの妹ってことは──つまり、私のおばさんじゃない！　だから『ルヴィネおばちゃん』♪」"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………不愉快だわ。やめなさい」
line = "「…………不愉快だわ。やめなさい」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なんでー！？　親しみを込めて呼んでるのに！！」
line = "「なんでー！？　親しみを込めて呼んでるのに！！」"

[[dialogue]]
speaker = "マトイ"
# 「ヴィーナス、女の子がいきなり『おばちゃん』呼ばわりされたら、そりゃ嫌だよ……」
line = "「ヴィーナス、女の子がいきなり『おばちゃん』呼ばわりされたら、そりゃ嫌だよ……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「デネブのリノさんは『おばあちゃん』って呼ぶと喜んでくれたのに！？　お小遣いだってくれそうな勢いだったわ！」
line = "「デネブのリノさんは『おばあちゃん』って呼ぶと喜んでくれたのに！？　お小遣いだってくれそうな勢いだったわ！」"

[[dialogue]]
speaker = "アナ"
# 「リノさんは数百年生きた魔女ですから、その辺りのことは気にならないと思いますが……」
line = "「リノさんは数百年生きた魔女ですから、その辺りのことは気にならないと思いますが……」"

[[dialogue]]
speaker = "サーシャ"
# 「そうね～。今回のことは流石に、ヴィーナスちゃんが悪いわよ～？」
line = "「そうね～。今回のことは流石に、ヴィーナスちゃんが悪いわよ～？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「え～！？　なんでなんでっ！？　呼び方を変えるのって、仲良くなるために大事じゃない！　ねぇマトイ？」
line = "「え～！？　なんでなんでっ！？　呼び方を変えるのって、仲良くなるために大事じゃない！　ねぇマトイ？」"

[[dialogue]]
speaker = "マトイ"
# 「なんで私に振るの！？」
line = "「なんで私に振るの！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「マトイだって昔は私のこと、『ヴィーナスさん』って呼んでたじゃない？」
line = "「マトイだって昔は私のこと、『ヴィーナスさん』って呼んでたじゃない？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でもそれを変えてから、もっと仲良しになれたでしょ♪」
line = "「でもそれを変えてから、もっと仲良しになれたでしょ♪」"

[[dialogue]]
speaker = "マトイ"
# 「あ～、そんな時期もあったね。あの頃の私は、ヴィーナスの何に気後れをしてたんだろう……懐かしいなぁ」
line = "「あ～、そんな時期もあったね。あの頃の私は、ヴィーナスの何に気後れをしてたんだろう……懐かしいなぁ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「デネブとはこれから手を取り合っていくんだから、よそよそしい関係はダメだって思ったの！」
line = "「デネブとはこれから手を取り合っていくんだから、よそよそしい関係はダメだって思ったの！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「必要以上に距離を取ろうとは思わないわ。けれど……おばさん呼びは嫌よ。やめて頂戴」
line = "「必要以上に距離を取ろうとは思わないわ。けれど……おばさん呼びは嫌よ。やめて頂戴」"

[[dialogue]]
speaker = "ルヴィネ"
# 「魔王……貴方ね、娘のしつけはちゃんとしなさい」
line = "「魔王……貴方ね、娘のしつけはちゃんとしなさい」"

[[dialogue]]
speaker = "unk"
# 本当に申し訳ない……
line = "本当に申し訳ない……"

[[dialogue]]
speaker = "サーシャ"
# 「う～ん。でもでも、ヴィーナスちゃんの言うことも一理あるかもしれないわね～」
line = "「う～ん。でもでも、ヴィーナスちゃんの言うことも一理あるかもしれないわね～」"

[[dialogue]]
speaker = "ルヴィネ"
# 「何を言っているの、奏サーシャ。貴女まで……」
line = "「何を言っているの、奏サーシャ。貴女まで……」"

[[dialogue]]
speaker = "サーシャ"
# 「相手が嫌がる呼び名はもちろんダメだけど。関係性を意識して変えていくのも、大切なことじゃないかしら～？」
line = "「相手が嫌がる呼び名はもちろんダメだけど。関係性を意識して変えていくのも、大切なことじゃないかしら～？」"

[[dialogue]]
speaker = "サーシャ"
# 「事実、ルヴィネちゃんってば私たちのこと、フルネームで呼ぶし……」
line = "「事実、ルヴィネちゃんってば私たちのこと、フルネームで呼ぶし……」"

[[dialogue]]
speaker = "アナ"
# 「確かに。先ほどから『九浄ヴィーナス』『奏サーシャ』と呼んでいます。少し距離を感じるかもしれません」
line = "「確かに。先ほどから『九浄ヴィーナス』『奏サーシャ』と呼んでいます。少し距離を感じるかもしれません」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ぅ……性分なのだけれど、確かによそよそしかったかしら。わかったわ、希望の呼び名があるなら教えて頂戴。改めるから」
line = "「ぅ……性分なのだけれど、確かによそよそしかったかしら。わかったわ、希望の呼び名があるなら教えて頂戴。改めるから」"

[[dialogue]]
speaker = "サーシャ"
# 「うふふ♪　じゃあ私のことは『サーシャお姉ちゃん』でお願いしようかしら～♪」
line = "「うふふ♪　じゃあ私のことは『サーシャお姉ちゃん』でお願いしようかしら～♪」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……真面目にやってもらえる？」
line = "「……真面目にやってもらえる？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「失礼ね！　私が集めた『最強のお姉ちゃん』に、なんてことを言うの！」
line = "「失礼ね！　私が集めた『最強のお姉ちゃん』に、なんてことを言うの！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……やっぱり貴女の感性、どうかしているわ」
line = "「……やっぱり貴女の感性、どうかしているわ」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふ。私、皆の『お姉ちゃん』だもの♪　それにルヴィネちゃんって、妹力が高いと思うのよね～<emoji=heart04>」
line = "「ふふ。私、皆の『お姉ちゃん』だもの♪　それにルヴィネちゃんって、妹力が高いと思うのよね～<emoji=heart04>」"

[[dialogue]]
speaker = "ルヴィネ"
# 「貴女の主観を否定する気はないけれど、何なの『妹力』って……理解不能だわ。そんなもの私にはないし、似合わないでしょう」
line = "「貴女の主観を否定する気はないけれど、何なの『妹力』って……理解不能だわ。そんなもの私にはないし、似合わないでしょう」"

[[dialogue]]
speaker = "アナ"
# 「そうでしょうか？　ルヴィネさんは、女神テルル様の妹さん──それに、私と同じく小さい見た目です」
line = "「そうでしょうか？　ルヴィネさんは、女神テルル様の妹さん──それに、私と同じく小さい見た目です」"

[[dialogue]]
speaker = "アナ"
# 「『妹』たるポテンシャルは、十分あるかと」
line = "「『妹』たるポテンシャルは、十分あるかと」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……アナ、貴女も実はそちら側だったの？」
line = "「……アナ、貴女も実はそちら側だったの？」"

[[dialogue]]
speaker = "サーシャ"
# 「次代の立派な女神様になるために、色々なことを学んでいくって決めたんでしょう？」
line = "「次代の立派な女神様になるために、色々なことを学んでいくって決めたんでしょう？」"

[[dialogue]]
speaker = "サーシャ"
# 「だったら、物は試しよ～♪　ほらほら、呼んでみて♪」
line = "「だったら、物は試しよ～♪　ほらほら、呼んでみて♪」"

[[dialogue]]
speaker = "ルヴィネ"
# 「………………」
line = "「………………」"

[[dialogue]]
speaker = "ルヴィネ"
# 「アルタイルには、おかしなヒトが多いわね……はぁ。一度だけよ？」
line = "「アルタイルには、おかしなヒトが多いわね……はぁ。一度だけよ？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………サーシャ、お姉ちゃん」
line = "「…………サーシャ、お姉ちゃん」"

[[dialogue]]
speaker = "サーシャ"
# 「あ～ん、可愛いわ～っ<emoji=heart04>　ぎゅ～ぅ～っ<emoji=heart04>」
line = "「あ～ん、可愛いわ～っ<emoji=heart04>　ぎゅ～ぅ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ルヴィネ"
# 「んぶぶっ！？　は、離しなさい、奏サーシャ……！！」
line = "「んぶぶっ！？　は、離しなさい、奏サーシャ……！！」"

[[dialogue]]
speaker = "サーシャ"
# 「だ～め<emoji=heart04>　お姉ちゃんって呼ばないと～……お仕置きのハグ、強ーくしちゃうんだから～♪　えい、え～いっ<emoji=heart04>」
line = "「だ～め<emoji=heart04>　お姉ちゃんって呼ばないと～……お仕置きのハグ、強ーくしちゃうんだから～♪　えい、え～いっ<emoji=heart04>」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ま、魔王っ！！　突っ立ってないで、助けて頂戴……！」
line = "「ま、魔王っ！！　突っ立ってないで、助けて頂戴……！」"

[[dialogue]]
speaker = "unk"
# 俺のことは『兄さん』って呼んでくれ
line = "俺のことは『兄さん』って呼んでくれ"

[[dialogue]]
speaker = "ルヴィネ"
# 「ひぃ！？」
line = "「ひぃ！？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「あ、貴方まで馬鹿なことを言ってないで……！　ふざけてないで早く……むぎゅぅ！？」
line = "「あ、貴方まで馬鹿なことを言ってないで……！　ふざけてないで早く……むぎゅぅ！？」"

[[dialogue]]
speaker = "ルヴィネ"
# （こ、このままだと本当にハグで落とされる……！　い、言うしかないの！？　次代の女神である私が！？）
line = "（こ、このままだと本当にハグで落とされる……！　い、言うしかないの！？　次代の女神である私が！？）"

[[dialogue]]
speaker = "ルヴィネ"
# 「に──兄さん！　助けてっ────！」
line = "「に──兄さん！　助けてっ────！」"

[[dialogue]]
speaker = "unk"
# ──任せろ！！！
line = "──任せろ！！！"

[[dialogue]]
speaker = "サーシャ"
# 「あ～ん<emoji=heart04>　会長くんに引き離されちゃったわ～♪」
line = "「あ～ん<emoji=heart04>　会長くんに引き離されちゃったわ～♪」"

[[dialogue]]
speaker = "ルヴィネ"
# 「けほっ……何なの、本当に……」
line = "「けほっ……何なの、本当に……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「魔王。貴方まで一緒になって……ふざけるのは程々にして頂戴」
line = "「魔王。貴方まで一緒になって……ふざけるのは程々にして頂戴」"

[[dialogue]]
speaker = "unk"
# もう『兄さん』呼びは終わり……？
line = "もう『兄さん』呼びは終わり……？"

[[dialogue]]
speaker = "ルヴィネ"
# 「当たり前でしょう！？　アルタイルには変人しかいないの……！？」
line = "「当たり前でしょう！？　アルタイルには変人しかいないの……！？」"

[[dialogue]]
speaker = "unk"
# ──それから、しばらく後。
line = "──それから、しばらく後。"

[[dialogue]]
speaker = "unk"
# 星徒会室から逃げ出したルヴィネは、カフェテリアで休息を取っていた。
line = "星徒会室から逃げ出したルヴィネは、カフェテリアで休息を取っていた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「創造神の傀儡ではなく、１人の天使として知見を深めていく……そのことの大切さは理解しているけれど、いきなり散々な目に遭ったわ」
line = "「創造神の傀儡ではなく、１人の天使として知見を深めていく……そのことの大切さは理解しているけれど、いきなり散々な目に遭ったわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「おばさん呼ばわりされるし、妹キャラが似合うだなんて言われるし……立派な女神になるための道のりは前途多難そうね……」
line = "「おばさん呼ばわりされるし、妹キャラが似合うだなんて言われるし……立派な女神になるための道のりは前途多難そうね……」"

[[dialogue]]
speaker = "ルルカ"
# 「あっ──いたいた！　こんにちは、ルヴィネさん！　今ちょっといいですか？」
line = "「あっ──いたいた！　こんにちは、ルヴィネさん！　今ちょっといいですか？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「貴女たちは……？」
line = "「貴女たちは……？」"

[[dialogue]]
speaker = "ルルカ"
# 「さっきアナちゃんから、新しい妹が増えたって聞いて──ご挨拶に来ました！　よろしくお願いしますっ！」
line = "「さっきアナちゃんから、新しい妹が増えたって聞いて──ご挨拶に来ました！　よろしくお願いしますっ！」"

[[dialogue]]
speaker = "メイプル"
# 「ふっふっふ……まさか平行世界から、新たな『妹ライバル』が現れるとは！　油断ならない相手のようだな！」
line = "「ふっふっふ……まさか平行世界から、新たな『妹ライバル』が現れるとは！　油断ならない相手のようだな！」"

[[dialogue]]
speaker = "クーシェン"
# 「誰が一番、にーにーの妹にふさわしいか勝負だよ！　ボク、負けないから！！」
line = "「誰が一番、にーにーの妹にふさわしいか勝負だよ！　ボク、負けないから！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「？？？？　……？？　？？？」
line = "「？？？？　……？？　？？？」"

[[dialogue]]
speaker = "unk"
# そうしてルヴィネは、学園内に存在する妹同盟の女の子たちに囲まれて、親交を深めることになるのだが。
line = "そうしてルヴィネは、学園内に存在する妹同盟の女の子たちに囲まれて、親交を深めることになるのだが。"

[[dialogue]]
speaker = "unk"
# それはまた、別のお話──
line = "それはまた、別のお話──"
