[[dialogue]]
speaker = "unk"
# すっかり油断していた俺は、あろうことかシズルさんに一服盛られてしまった！
line = "すっかり油断していた俺は、あろうことかシズルさんに一服盛られてしまった！"

[[dialogue]]
speaker = "unk"
# 股間はズキズキするほど膨らみ、脳内はピンクのヴェールがかかったみたいに霞がかる。
line = "股間はズキズキするほど膨らみ、脳内はピンクのヴェールがかかったみたいに霞がかる。"

[[dialogue]]
speaker = "シズル"
# 「ふふふっ、秘薬もしっかり効いてきたみたいですね<emoji=heart04>」
line = "「ふふふっ、秘薬もしっかり効いてきたみたいですね<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「シズルさん……こ、これは……どういうつもりですか？」
line = "「シズルさん……こ、これは……どういうつもりですか？」"

[[dialogue]]
speaker = "シズル"
# 「野暮なことを訊かないで下さい。ここにいるのは一対のオスとメス。することなんて１つしかありません」
line = "「野暮なことを訊かないで下さい。ここにいるのは一対のオスとメス。することなんて１つしかありません」"

[[dialogue]]
speaker = "シズル"
# 「さあ、参りましょう。恐がらないで……身も心も私に委ねて下さい」
line = "「さあ、参りましょう。恐がらないで……身も心も私に委ねて下さい」"

[[dialogue]]
speaker = "シズル"
# 「弟子のせつなに代わって、師の私が房中術を味わわせてあげますね<emoji=heart04>」
line = "「弟子のせつなに代わって、師の私が房中術を味わわせてあげますね<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「うふふ～、このままでもいいですが、も～っと気持ちよくするために、秘薬の香を焚きましょう」
line = "「うふふ～、このままでもいいですが、も～っと気持ちよくするために、秘薬の香を焚きましょう」"

[[dialogue]]
speaker = "シズル"
# 「これでよし。ささ、魔王さん……行きますよ～」
line = "「これでよし。ささ、魔王さん……行きますよ～」"

[[dialogue]]
speaker = "シズル"
# 「どぉーんっ<emoji=heart04>」
line = "「どぉーんっ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「大人しくして下さいね～、抵抗しちゃ嫌ですよ。じっとしていたら、す～ぐ気持ちよくなりますからね～♪」
line = "「大人しくして下さいね～、抵抗しちゃ嫌ですよ。じっとしていたら、す～ぐ気持ちよくなりますからね～♪」"

[[dialogue]]
speaker = "クロト"
# 「クッ、動けないっ……」
line = "「クッ、動けないっ……」"

[[dialogue]]
speaker = "シズル"
# 「忍の体術で押さえつけていますから、逃げられるとは思わないことです<emoji=heart04>」
line = "「忍の体術で押さえつけていますから、逃げられるとは思わないことです<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「ねえ、魔王さん、そんなに嫌ですか？　おち○ぽをこんなにギンギンにさせてるのに～」
line = "「ねえ、魔王さん、そんなに嫌ですか？　おち○ぽをこんなにギンギンにさせてるのに～」"

[[dialogue]]
speaker = "シズル"
# 「こっちはとっても素直なのに……ねぇ？」
line = "「こっちはとっても素直なのに……ねぇ？」"

[[dialogue]]
speaker = "シズル"
# 「房中術のお試しみたいなものですよ。ほら～、気持ちよくないですか？　ちっちゃくてぷにぷにの割れ目に押し当てられて……むにゅ～って……」
line = "「房中術のお試しみたいなものですよ。ほら～、気持ちよくないですか？　ちっちゃくてぷにぷにの割れ目に押し当てられて……むにゅ～って……」"

[[dialogue]]
speaker = "クロト"
# 「き、気持ちいいけどっ……」
line = "「き、気持ちいいけどっ……」"

[[dialogue]]
speaker = "シズル"
# 「なら、いいじゃないですか。もっと本能に従いましょ？　魔王さんも気持ちよくなって、私も気持ちよくなって……まさにうぃんうぃんです♪」
line = "「なら、いいじゃないですか。もっと本能に従いましょ？　魔王さんも気持ちよくなって、私も気持ちよくなって……まさにうぃんうぃんです♪」"

[[dialogue]]
speaker = "シズル"
# 「うふふ……おち○ぽビクンってしましたね。魔王さん、えろ～い<emoji=heart04>　こんなでっかいおち○ぽなんですから、使わないと勿体ないですよ～♪」
line = "「うふふ……おち○ぽビクンってしましたね。魔王さん、えろ～い<emoji=heart04>　こんなでっかいおち○ぽなんですから、使わないと勿体ないですよ～♪」"

[[dialogue]]
speaker = "シズル"
# 「というか、こっちが我慢できなくなってきました。自分で作った秘薬ですけど、ほんと効果抜群ですね」
line = "「というか、こっちが我慢できなくなってきました。自分で作った秘薬ですけど、ほんと効果抜群ですね」"

[[dialogue]]
speaker = "シズル"
# 「ほら、見て下さい。魔王さんのおち○ぽがくっついてるとこ……私のおま○こ、もうこんなに濡れちゃってますよ……」
line = "「ほら、見て下さい。魔王さんのおち○ぽがくっついてるとこ……私のおま○こ、もうこんなに濡れちゃってますよ……」"

[[dialogue]]
speaker = "シズル"
# 「魔王さんのかっこいいち○ちん食べたいよ～ってうずうずしてるんです。こ～んなえっちなよだれを垂らして……んんっ、ま○ずり気持ちいい……本気になっちゃう……」
line = "「魔王さんのかっこいいち○ちん食べたいよ～ってうずうずしてるんです。こ～んなえっちなよだれを垂らして……んんっ、ま○ずり気持ちいい……本気になっちゃう……」"

[[dialogue]]
speaker = "シズル"
# 「くちゅっ、くちゅって……やらしー音してるの聞こえますか？　魔王さんの竿もぬるぬるになってますよ～。ごめんなさい、スケベ汁なすりつけちゃって<emoji=heart04>」
line = "「くちゅっ、くちゅって……やらしー音してるの聞こえますか？　魔王さんの竿もぬるぬるになってますよ～。ごめんなさい、スケベ汁なすりつけちゃって<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「こんなになっちゃうくらい、魔王さんのおち○ぽが欲しいんです<emoji=heart04>　ねえ、魔王さん<emoji=heart04>　ねえってば<emoji=heart04>　してもいいよね？　ち○ちんハメてもいいよね？」
line = "「こんなになっちゃうくらい、魔王さんのおち○ぽが欲しいんです<emoji=heart04>　ねえ、魔王さん<emoji=heart04>　ねえってば<emoji=heart04>　してもいいよね？　ち○ちんハメてもいいよね？」"

[[dialogue]]
speaker = "シズル"
# 「やだって言っても、ハメちゃうんですからっ<emoji=heart04>　えへへへ～」
line = "「やだって言っても、ハメちゃうんですからっ<emoji=heart04>　えへへへ～」"

[[dialogue]]
speaker = "シズル"
# 「暴れたって逃がしませんよ～。魔王さんはここで私に無理矢理食べられちゃうんです<emoji=heart04>」
line = "「暴れたって逃がしませんよ～。魔王さんはここで私に無理矢理食べられちゃうんです<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「後はただ、気持ちよくなって、どぴゅ～ってすることだけ考えて……私の体を感じて下さい……<emoji=heart04>」
line = "「後はただ、気持ちよくなって、どぴゅ～ってすることだけ考えて……私の体を感じて下さい……<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「じゃあ、挿れますね<emoji=heart04>　ち○ちん食べちゃいます<emoji=heart04>　私のちびま○こに……むにゅう～～～って……頂きまぁす<emoji=heart04>」
line = "「じゃあ、挿れますね<emoji=heart04>　ち○ちん食べちゃいます<emoji=heart04>　私のちびま○こに……むにゅう～～～って……頂きまぁす<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んあぁぁっ！　はぁっ！　あっ……おっきい<emoji=heart04>　魔王さんのおち○ぽ、すごくいいですよ～<emoji=heart04>」
line = "「んあぁぁっ！　はぁっ！　あっ……おっきい<emoji=heart04>　魔王さんのおち○ぽ、すごくいいですよ～<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「ごめんなさい、全部は入りませんでしたぁ<emoji=heart04>　これほどのち○ぽ、きっとせつなでは持て余すでしょうね」
line = "「ごめんなさい、全部は入りませんでしたぁ<emoji=heart04>　これほどのち○ぽ、きっとせつなでは持て余すでしょうね」"

[[dialogue]]
speaker = "シズル"
# 「でも、私なら大丈夫ですよ。おま○こ小さすぎて無理だって思うかもしれませんけど、房中術を使えば……ちゃ～んと根元までぱっくん出来ますから<emoji=heart04>」
line = "「でも、私なら大丈夫ですよ。おま○こ小さすぎて無理だって思うかもしれませんけど、房中術を使えば……ちゃ～んと根元までぱっくん出来ますから<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んんぅっ……<emoji=heart04>　おっき<emoji=heart04>　子袋押し上げられちゃいます<emoji=heart04>　も～、全然興味なさそうなこと言ってて、えっぐいち○ちんですね～。こんなの女の子は一発で堕ちちゃいますよ<emoji=heart04>」
line = "「んんぅっ……<emoji=heart04>　おっき<emoji=heart04>　子袋押し上げられちゃいます<emoji=heart04>　も～、全然興味なさそうなこと言ってて、えっぐいち○ちんですね～。こんなの女の子は一発で堕ちちゃいますよ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「私は房中術の使い手ですから、いくら魔王さんのおち○ぽが女殺しでも、絶対負けませんよ～<emoji=heart04>」
line = "「私は房中術の使い手ですから、いくら魔王さんのおち○ぽが女殺しでも、絶対負けませんよ～<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「魔王さんのイケちんと……あんっ<emoji=heart04>　房中術の使い手のえっちま○こ<emoji=heart04>　どっちがつよいか、勝負しましょうね～<emoji=heart04>」
line = "「魔王さんのイケちんと……あんっ<emoji=heart04>　房中術の使い手のえっちま○こ<emoji=heart04>　どっちがつよいか、勝負しましょうね～<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「ふふふ、私の肉壺も、ようやく魔王さんのデカちんに馴染んできましたね～<emoji=heart04>　どうですか～、根元までずっぽり入ってますよ～<emoji=heart04>」
line = "「ふふふ、私の肉壺も、ようやく魔王さんのデカちんに馴染んできましたね～<emoji=heart04>　どうですか～、根元までずっぽり入ってますよ～<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「ぬるぬるでプリプリの膣襞で気持ちよ～く……しこ<emoji=heart04>　しこ<emoji=heart04>　してあげますからね～<emoji=heart04>」
line = "「ぬるぬるでプリプリの膣襞で気持ちよ～く……しこ<emoji=heart04>　しこ<emoji=heart04>　してあげますからね～<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んしょ<emoji=heart04>　んしょ<emoji=heart04>　えへへ～、気持ちいい上下運動ですね～<emoji=heart04>　こうしてゆ～っくり、出したり入れたりして～<emoji=heart04>　んふっ<emoji=heart04>　気持ちいい<emoji=heart04>　もっとぬぽぬぽしますね<emoji=heart04>」
line = "「んしょ<emoji=heart04>　んしょ<emoji=heart04>　えへへ～、気持ちいい上下運動ですね～<emoji=heart04>　こうしてゆ～っくり、出したり入れたりして～<emoji=heart04>　んふっ<emoji=heart04>　気持ちいい<emoji=heart04>　もっとぬぽぬぽしますね<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「魔王さんはどうですか～？　ち○ちん気持ちいいですか～？　私のおま○こ、気に入ってくれるといいんですが……」
line = "「魔王さんはどうですか～？　ち○ちん気持ちいいですか～？　私のおま○こ、気に入ってくれるといいんですが……」"

[[dialogue]]
speaker = "クロト"
# 「き、気持ちいい……よっ」
line = "「き、気持ちいい……よっ」"

[[dialogue]]
speaker = "シズル"
# 「ふふふっ、当然ですよね～。男の子のおち○ちんは、おま○こに挿れるのがいちば～ん気持ちいいんですから<emoji=heart04>」
line = "「ふふふっ、当然ですよね～。男の子のおち○ちんは、おま○こに挿れるのがいちば～ん気持ちいいんですから<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「おち○ちんはおま○こに勝てなくてぇ<emoji=heart04>　でもでもっ、おま○こも……おち○ちんには勝てないんですよ<emoji=heart04>　これ、大事なことですから覚えて下さいね<emoji=heart04>」
line = "「おち○ちんはおま○こに勝てなくてぇ<emoji=heart04>　でもでもっ、おま○こも……おち○ちんには勝てないんですよ<emoji=heart04>　これ、大事なことですから覚えて下さいね<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んふっ<emoji=heart04>　あぁんっ<emoji=heart04>　やだ<emoji=heart04>　気持ちよくてえっちな声出ちゃう<emoji=heart04>　魔王さん<emoji=heart04>　魔王さん～っ<emoji=heart04>」
line = "「んふっ<emoji=heart04>　あぁんっ<emoji=heart04>　やだ<emoji=heart04>　気持ちよくてえっちな声出ちゃう<emoji=heart04>　魔王さん<emoji=heart04>　魔王さん～っ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「はぁ<emoji=heart04>　はぁ<emoji=heart04>　こんな風に生殖器同士をぬぷ<emoji=heart04>　ぬぷ<emoji=heart04>　擦り合ってたら……好きになっちゃいそうですよね～<emoji=heart04>」
line = "「はぁ<emoji=heart04>　はぁ<emoji=heart04>　こんな風に生殖器同士をぬぷ<emoji=heart04>　ぬぷ<emoji=heart04>　擦り合ってたら……好きになっちゃいそうですよね～<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「ふふっ、恐がらないで下さい<emoji=heart04>　ぜ～んぶ本能のせいですから<emoji=heart04>　気持ちい～いえっちすると、遊びのハメっこでも好きになっちゃうんですよ～<emoji=heart04>」
line = "「ふふっ、恐がらないで下さい<emoji=heart04>　ぜ～んぶ本能のせいですから<emoji=heart04>　気持ちい～いえっちすると、遊びのハメっこでも好きになっちゃうんですよ～<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「さぁ、魔王さん……シズル<emoji=heart04>　って呼んで下さい<emoji=heart04>　シズル好き<emoji=heart04>　って言って<emoji=heart04>　好き好き言い合いながらするせっくすがどれだけ気持ちいいか教えてあげます<emoji=heart04>」
line = "「さぁ、魔王さん……シズル<emoji=heart04>　って呼んで下さい<emoji=heart04>　シズル好き<emoji=heart04>　って言って<emoji=heart04>　好き好き言い合いながらするせっくすがどれだけ気持ちいいか教えてあげます<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ううっ……シズルさん……」
line = "「ううっ……シズルさん……」"

[[dialogue]]
speaker = "シズル"
# 「はい、魔王さん<emoji=heart04>　えっちなシズルさんですよ<emoji=heart04>　魔王さんのち○ちん気持ちよくしてくれる、えっちえっちなシズルさんですよ～<emoji=heart04>」
line = "「はい、魔王さん<emoji=heart04>　えっちなシズルさんですよ<emoji=heart04>　魔王さんのち○ちん気持ちよくしてくれる、えっちえっちなシズルさんですよ～<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「魔王さん<emoji=heart04>　好き<emoji=heart04>　魔王さんっ<emoji=heart04>　好きぃ<emoji=heart04>　んんん～っ、すっご<emoji=heart04>　おち○ぽおっきくなりましたぁ<emoji=heart04>」
line = "「魔王さん<emoji=heart04>　好き<emoji=heart04>　魔王さんっ<emoji=heart04>　好きぃ<emoji=heart04>　んんん～っ、すっご<emoji=heart04>　おち○ぽおっきくなりましたぁ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「さぁ、魔王さんも<emoji=heart04>　好きって言って<emoji=heart04>　私がぬぷぬぷするのに合わせてっ<emoji=heart04>　好きって言って<emoji=heart04>」
line = "「さぁ、魔王さんも<emoji=heart04>　好きって言って<emoji=heart04>　私がぬぷぬぷするのに合わせてっ<emoji=heart04>　好きって言って<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「シズルさんっ、好き<emoji=heart04>　好きっ<emoji=heart04>　好きだっ<emoji=heart04>」
line = "「シズルさんっ、好き<emoji=heart04>　好きっ<emoji=heart04>　好きだっ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んん～っ<emoji=heart04>　ふあっ<emoji=heart04>　あんっ<emoji=heart04>　嬉しいっ<emoji=heart04>　んあっ<emoji=heart04>　あっ<emoji=heart04>　私もっ<emoji=heart04>　好き<emoji=heart04>　好きですよ<emoji=heart04>　魔王さんっ<emoji=heart04>　好き好き好きっ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「んん～っ<emoji=heart04>　ふあっ<emoji=heart04>　あんっ<emoji=heart04>　嬉しいっ<emoji=heart04>　んあっ<emoji=heart04>　あっ<emoji=heart04>　私もっ<emoji=heart04>　好き<emoji=heart04>　好きですよ<emoji=heart04>　魔王さんっ<emoji=heart04>　好き好き好きっ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「すっご<emoji=heart04>　おち○ぽおっきい<emoji=heart04>　こんなの気持ちよすぎてっ<emoji=heart04>　本気の腰振りしちゃいます<emoji=heart04>」
line = "「すっご<emoji=heart04>　おち○ぽおっきい<emoji=heart04>　こんなの気持ちよすぎてっ<emoji=heart04>　本気の腰振りしちゃいます<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「これするとすぐどぴゅってしちゃうのに<emoji=heart04>　もう無理<emoji=heart04>　これ以上我慢できませんっ<emoji=heart04>　魔王さんっ<emoji=heart04>　好き<emoji=heart04>　本気で動きますね<emoji=heart04>　ざーめん出すまで止めませんからっ<emoji=heart04>」
line = "「これするとすぐどぴゅってしちゃうのに<emoji=heart04>　もう無理<emoji=heart04>　これ以上我慢できませんっ<emoji=heart04>　魔王さんっ<emoji=heart04>　好き<emoji=heart04>　本気で動きますね<emoji=heart04>　ざーめん出すまで止めませんからっ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んおおっ<emoji=heart04>　ふおっ<emoji=heart04>　おっ<emoji=heart04>　おんっ<emoji=heart04>　ち○ぽしゅご<emoji=heart04>　魔王さん<emoji=heart04>　気持ちいいっ<emoji=heart04>　んあぁっっ<emoji=heart04>　はぁんっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　好き<emoji=heart04>　好きぃ<emoji=heart04>」
line = "「んおおっ<emoji=heart04>　ふおっ<emoji=heart04>　おっ<emoji=heart04>　おんっ<emoji=heart04>　ち○ぽしゅご<emoji=heart04>　魔王さん<emoji=heart04>　気持ちいいっ<emoji=heart04>　んあぁっっ<emoji=heart04>　はぁんっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　好き<emoji=heart04>　好きぃ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「ふぉぉ～～<emoji=heart04>　おおっ<emoji=heart04>　魔王さんのち○ぽ強すぎぃ<emoji=heart04>　ううっ<emoji=heart04>　んうっ<emoji=heart04>　わ、私のま○こと相性ばっちりです<emoji=heart04>　房中術のお試しのつもりなのにっ<emoji=heart04>」
line = "「ふぉぉ～～<emoji=heart04>　おおっ<emoji=heart04>　魔王さんのち○ぽ強すぎぃ<emoji=heart04>　ううっ<emoji=heart04>　んうっ<emoji=heart04>　わ、私のま○こと相性ばっちりです<emoji=heart04>　房中術のお試しのつもりなのにっ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「うあっ<emoji=heart04>　あんっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　はぁぁんっ<emoji=heart04>　はぁっ、はぁっ、はぁっ、こんなに気持ちいいと……お試しじゃなくなっちゃいそうです<emoji=heart04>」
line = "「うあっ<emoji=heart04>　あんっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　はぁぁんっ<emoji=heart04>　はぁっ、はぁっ、はぁっ、こんなに気持ちいいと……お試しじゃなくなっちゃいそうです<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「魔王さんっ<emoji=heart04>　好き<emoji=heart04>　好きぃ<emoji=heart04>　魔王ち○ぽしゅきぃ<emoji=heart04>　こんなっ、はしたなくてごめんなさいっ<emoji=heart04>　でもっ<emoji=heart04>　せっくす気持ちよすぎてっ<emoji=heart04>」
line = "「魔王さんっ<emoji=heart04>　好き<emoji=heart04>　好きぃ<emoji=heart04>　魔王ち○ぽしゅきぃ<emoji=heart04>　こんなっ、はしたなくてごめんなさいっ<emoji=heart04>　でもっ<emoji=heart04>　せっくす気持ちよすぎてっ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「ごめんなさいっ<emoji=heart04>　せつなの主様なのにっ<emoji=heart04>　本気になっちゃう<emoji=heart04>　本気交尾しちゃうぅ～～っ<emoji=heart04>」
line = "「ごめんなさいっ<emoji=heart04>　せつなの主様なのにっ<emoji=heart04>　本気になっちゃう<emoji=heart04>　本気交尾しちゃうぅ～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「魔王さんっ<emoji=heart04>　好き<emoji=heart04>　しゅきっ<emoji=heart04>　ざーめん出してっ<emoji=heart04>　魔王さんの子種欲しいっ<emoji=heart04>　子宮が求めてるんですっ<emoji=heart04>　魔王さんの子種で孕みたいって<emoji=heart04>」
line = "「魔王さんっ<emoji=heart04>　好き<emoji=heart04>　しゅきっ<emoji=heart04>　ざーめん出してっ<emoji=heart04>　魔王さんの子種欲しいっ<emoji=heart04>　子宮が求めてるんですっ<emoji=heart04>　魔王さんの子種で孕みたいって<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んあぁぁ～～っ<emoji=heart04>　はぁん<emoji=heart04>　あっ<emoji=heart04>　ふあぁぁっ<emoji=heart04>　もう無理っ<emoji=heart04>　けものみたいにはしたなく声出してっ、魔王さんのち○ぽに夢中になっちゃいますっ<emoji=heart04>」
line = "「んあぁぁ～～っ<emoji=heart04>　はぁん<emoji=heart04>　あっ<emoji=heart04>　ふあぁぁっ<emoji=heart04>　もう無理っ<emoji=heart04>　けものみたいにはしたなく声出してっ、魔王さんのち○ぽに夢中になっちゃいますっ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んおっ<emoji=heart04>　おっ<emoji=heart04>　おっ<emoji=heart04>　奥刺さるっ<emoji=heart04>　ち○ぽっ<emoji=heart04>　しゅごっ<emoji=heart04>　もっと気持ちよくなりたいっ<emoji=heart04>　魔王さんっ<emoji=heart04>　魔王さんっ<emoji=heart04>　好き<emoji=heart04>　好きぃ～～～っ<emoji=heart04>」
line = "「んおっ<emoji=heart04>　おっ<emoji=heart04>　おっ<emoji=heart04>　奥刺さるっ<emoji=heart04>　ち○ぽっ<emoji=heart04>　しゅごっ<emoji=heart04>　もっと気持ちよくなりたいっ<emoji=heart04>　魔王さんっ<emoji=heart04>　魔王さんっ<emoji=heart04>　好き<emoji=heart04>　好きぃ～～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「シズルさんっ<emoji=heart04>　シズルさんっ<emoji=heart04>　シズル～～っ<emoji=heart04>」
line = "「シズルさんっ<emoji=heart04>　シズルさんっ<emoji=heart04>　シズル～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んんぅ～～～～っ<emoji=heart04>　イぐっ<emoji=heart04>　イぐうっ<emoji=heart04>　名前呼ばれてイっちゃううぅ～～～っ<emoji=heart04>　魔王さんっ<emoji=heart04>　魔王さんっ<emoji=heart04>　好きですっ<emoji=heart04>　好き好き好きぃっ<emoji=heart04>」
line = "「んんぅ～～～～っ<emoji=heart04>　イぐっ<emoji=heart04>　イぐうっ<emoji=heart04>　名前呼ばれてイっちゃううぅ～～～っ<emoji=heart04>　魔王さんっ<emoji=heart04>　魔王さんっ<emoji=heart04>　好きですっ<emoji=heart04>　好き好き好きぃっ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「もうっ、私イくからっ<emoji=heart04>　魔王さんもっ<emoji=heart04>　ざーめん<emoji=heart04>　ざーめん出してぇっ<emoji=heart04>　私に出してっ<emoji=heart04>　私のおま○こにざーめん出してぇぇ～っ<emoji=heart04>」
line = "「もうっ、私イくからっ<emoji=heart04>　魔王さんもっ<emoji=heart04>　ざーめん<emoji=heart04>　ざーめん出してぇっ<emoji=heart04>　私に出してっ<emoji=heart04>　私のおま○こにざーめん出してぇぇ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んおっ<emoji=heart04>　おおっ<emoji=heart04>　んおっ<emoji=heart04>　おっ<emoji=heart04>　イぐ<emoji=heart04>　おっきいの来る<emoji=heart04>　イぐっ<emoji=heart04>　もう無理ぃぃ～っ<emoji=heart04>　魔王さんっ<emoji=heart04>　イきますっ<emoji=heart04>　イぐイぐイぐイぐぅっっ<emoji=heart04>」
line = "「んおっ<emoji=heart04>　おおっ<emoji=heart04>　んおっ<emoji=heart04>　おっ<emoji=heart04>　イぐ<emoji=heart04>　おっきいの来る<emoji=heart04>　イぐっ<emoji=heart04>　もう無理ぃぃ～っ<emoji=heart04>　魔王さんっ<emoji=heart04>　イきますっ<emoji=heart04>　イぐイぐイぐイぐぅっっ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んおおおおおぉ～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「んおおおおおぉ～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んぐっ<emoji=heart04>　すごっ<emoji=heart04>　ざーめん出てるっ<emoji=heart04>　とどめ刺すみたいにっ<emoji=heart04>　びゅるびゅる出てるっ<emoji=heart04>　私がせっくす教えるつもりだったのにっ<emoji=heart04>」
line = "「んぐっ<emoji=heart04>　すごっ<emoji=heart04>　ざーめん出てるっ<emoji=heart04>　とどめ刺すみたいにっ<emoji=heart04>　びゅるびゅる出てるっ<emoji=heart04>　私がせっくす教えるつもりだったのにっ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「魔王さんのざーめんでっ<emoji=heart04>　イかされてるっ<emoji=heart04>　んおおおおっ<emoji=heart04>　おほっ<emoji=heart04>　ほっ<emoji=heart04>　多すぎっ<emoji=heart04>　全部っ<emoji=heart04>　子宮にっっ<emoji=heart04>　こんなの入りきらないっ<emoji=heart04>」
line = "「魔王さんのざーめんでっ<emoji=heart04>　イかされてるっ<emoji=heart04>　んおおおおっ<emoji=heart04>　おほっ<emoji=heart04>　ほっ<emoji=heart04>　多すぎっ<emoji=heart04>　全部っ<emoji=heart04>　子宮にっっ<emoji=heart04>　こんなの入りきらないっ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「はぁぁ～～っ<emoji=heart04>　あはぁっ<emoji=heart04>　はぁ<emoji=heart04>　はぁ<emoji=heart04>　んんん～～～っ<emoji=heart04>　まだ出るの？　ううっ、こんなに出されたらおかしくなっちゃいますっ<emoji=heart04>」
line = "「はぁぁ～～っ<emoji=heart04>　あはぁっ<emoji=heart04>　はぁ<emoji=heart04>　はぁ<emoji=heart04>　んんん～～～っ<emoji=heart04>　まだ出るの？　ううっ、こんなに出されたらおかしくなっちゃいますっ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「魔王さんっ<emoji=heart04>　んんっ<emoji=heart04>　好き……です<emoji=heart04>　こんなせっくすしたら、好きになっちゃいます<emoji=heart04>　ダメなのにっ、ううう～っ、しゅきぃ<emoji=heart04>」
line = "「魔王さんっ<emoji=heart04>　んんっ<emoji=heart04>　好き……です<emoji=heart04>　こんなせっくすしたら、好きになっちゃいます<emoji=heart04>　ダメなのにっ、ううう～っ、しゅきぃ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「はぁっ<emoji=heart04>　はぁっ<emoji=heart04>　はぁっ<emoji=heart04>　犯してたはずなのに……ふふっ、犯されてしまった後みたいです……<emoji=heart04>」
line = "「はぁっ<emoji=heart04>　はぁっ<emoji=heart04>　はぁっ<emoji=heart04>　犯してたはずなのに……ふふっ、犯されてしまった後みたいです……<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「ううっ……ふぅぅ～～～っ<emoji=heart04>　ようやく……射精終わりましたか……んもう、長すぎですよ<emoji=heart04>　どれだけ出すんですか<emoji=heart04>　こんなに出したら、孕んでも知りませんよ<emoji=heart04>」
line = "「ううっ……ふぅぅ～～～っ<emoji=heart04>　ようやく……射精終わりましたか……んもう、長すぎですよ<emoji=heart04>　どれだけ出すんですか<emoji=heart04>　こんなに出したら、孕んでも知りませんよ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「んふぅぅ～～～～っ<emoji=heart04>　はぁ<emoji=heart04>　はぁっ<emoji=heart04>　おち○ぽ抜きましたよ……わぁ、どろっどろでスケベですね<emoji=heart04>」
line = "「んふぅぅ～～～～っ<emoji=heart04>　はぁ<emoji=heart04>　はぁっ<emoji=heart04>　おち○ぽ抜きましたよ……わぁ、どろっどろでスケベですね<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「ううっ、抜いたらぶりゅぶりゅ出てきます<emoji=heart04>　ほとんど固形じゃないですか<emoji=heart04>　もお、量も多いですが、濃すぎ<emoji=heart04>　魔王ともなると、繁殖力も桁違いなんですね<emoji=heart04>」
line = "「ううっ、抜いたらぶりゅぶりゅ出てきます<emoji=heart04>　ほとんど固形じゃないですか<emoji=heart04>　もお、量も多いですが、濃すぎ<emoji=heart04>　魔王ともなると、繁殖力も桁違いなんですね<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「こんなの……せつな１人では太刀打ち出来るはずありませんね……もう、スケベ<emoji=heart04>」
line = "「こんなの……せつな１人では太刀打ち出来るはずありませんね……もう、スケベ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「ごめん……自分でもここまでとは思わなくて……」
line = "「ごめん……自分でもここまでとは思わなくて……」"

[[dialogue]]
speaker = "シズル"
# 「魔王さんは、好き好き言いながらのせっくすがツボだったみたいですね<emoji=heart04>」
line = "「魔王さんは、好き好き言いながらのせっくすがツボだったみたいですね<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「否定しないよ。めちゃくちゃ興奮した」
line = "「否定しないよ。めちゃくちゃ興奮した」"

[[dialogue]]
speaker = "シズル"
# 「私も……途中から房中術を忘れて本気せっくすしちゃいましたから、おあいこですよ<emoji=heart04>」
line = "「私も……途中から房中術を忘れて本気せっくすしちゃいましたから、おあいこですよ<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「でも、少し悔しいですね。魔王さんのおち○ぽを、私のおま○この虜にさせたかったのに<emoji=heart04>」
line = "「でも、少し悔しいですね。魔王さんのおち○ぽを、私のおま○この虜にさせたかったのに<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「あっ、もう虜になってる、とか言わなくていいですからね<emoji=heart04>　私が言いたいのは、そういうことではなくて……」
line = "「あっ、もう虜になってる、とか言わなくていいですからね<emoji=heart04>　私が言いたいのは、そういうことではなくて……」"

[[dialogue]]
speaker = "シズル"
# 「魔王さんとのせっくす、とっても素敵だったから……もう１戦、お相手してくれませんか<emoji=heart04>」
line = "「魔王さんとのせっくす、とっても素敵だったから……もう１戦、お相手してくれませんか<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「こちらこそ、是非お願いしますっ！」
line = "「こちらこそ、是非お願いしますっ！」"

[[dialogue]]
speaker = "シズル"
# 「うふふっ、ではこれから房中術を駆使して、魔王さんをメロメロにさせちゃいますね<emoji=heart04>」
line = "「うふふっ、ではこれから房中術を駆使して、魔王さんをメロメロにさせちゃいますね<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「そして……何度も何度も、シズル<emoji=heart04>　好き<emoji=heart04>　って言わせるんですからっ」
line = "「そして……何度も何度も、シズル<emoji=heart04>　好き<emoji=heart04>　って言わせるんですからっ」"

[[dialogue]]
speaker = "クロト"
# 「シズル<emoji=heart04>　好き<emoji=heart04>」
line = "「シズル<emoji=heart04>　好き<emoji=heart04>」"

[[dialogue]]
speaker = "シズル"
# 「もうっ、今言わなくていいんですっ<emoji=heart04>　ハメっこしながら言うのが、一番気持ちいいんですからぁ～～～っ<emoji=heart04>」
line = "「もうっ、今言わなくていいんですっ<emoji=heart04>　ハメっこしながら言うのが、一番気持ちいいんですからぁ～～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# こうして俺とシズルさんは、好き好き言い合いながら、ひたすら肉欲を貪るのだった。
line = "こうして俺とシズルさんは、好き好き言い合いながら、ひたすら肉欲を貪るのだった。"
