[[dialogue]]
speaker = "unk"
# 第３話,ニンニク大好きベアトさん,P
line = "第３話,ニンニク大好きベアトさん,P"

[[dialogue]]
speaker = "ベアトリス"
# 「う～ん、やっぱりまだないのかな～……」
line = "「う～ん、やっぱりまだないのかな～……」"

[[dialogue]]
speaker = "unk"
# こんにちは、ベアトリス
line = "こんにちは、ベアトリス"

[[dialogue]]
speaker = "ベアトリス"
# 「かか、会長さん！？　ごめんなさい、この前は、お見苦しいところをお見せしました……」
line = "「かか、会長さん！？　ごめんなさい、この前は、お見苦しいところをお見せしました……」"

[[dialogue]]
speaker = "unk"
# 大丈夫、気にしてないよ
line = "大丈夫、気にしてないよ"

[[dialogue]]
speaker = "ベアトリス"
# 「そ、そうですか……ありがとうございます……」
line = "「そ、そうですか……ありがとうございます……」"

[[dialogue]]
speaker = "ベアトリス"
# 「あの、恥のかきついでに聞きたいんですけど、この辺りにニンニクを好きなだけ盛れるパスタ屋さんってありませんでしたか？」
line = "「あの、恥のかきついでに聞きたいんですけど、この辺りにニンニクを好きなだけ盛れるパスタ屋さんってありませんでしたか？」"

[[dialogue]]
speaker = "ベアトリス"
# 「……この辺にはない？　やっぱりそうですか……」
line = "「……この辺にはない？　やっぱりそうですか……」"

[[dialogue]]
speaker = "ベアトリス"
# 「え、心当たりがある？　ホントですか！？」
line = "「え、心当たりがある？　ホントですか！？」"

[[dialogue]]
speaker = "ベアトリス"
# 「アーリオ・ポモドーロ……そう、このお店です！　イタリア語でニンニクとトマトって意味らしいですよ」
line = "「アーリオ・ポモドーロ……そう、このお店です！　イタリア語でニンニクとトマトって意味らしいですよ」"

[[dialogue]]
speaker = "ベアトリス"
# 「は～、こんなところにお店があるなんて知らなかったなぁ～。もしかしてここから移転したのかな？」
line = "「は～、こんなところにお店があるなんて知らなかったなぁ～。もしかしてここから移転したのかな？」"

[[dialogue]]
speaker = "unk"
# ここから移転した……？
line = "ここから移転した……？"

[[dialogue]]
speaker = "ベアトリス"
# 「ああいえいえいえっ、何でもないですよ、何でもっ。あははは……」
line = "「ああいえいえいえっ、何でもないですよ、何でもっ。あははは……」"

[[dialogue]]
speaker = "ベアトリス"
# 「そうです会長さん、せっかくですしここで一緒にお食事しませんか？」
line = "「そうです会長さん、せっかくですしここで一緒にお食事しませんか？」"

[[dialogue]]
speaker = "ベアトリス"
# 「ここはニンニクたっぷりがデフォなので、匂いが気にならなければですけど……」
line = "「ここはニンニクたっぷりがデフォなので、匂いが気にならなければですけど……」"

[[dialogue]]
speaker = "unk"
# 喜んで！
line = "喜んで！"

[[dialogue]]
speaker = "ベアトリス"
# 「やった！　じゃあ行きましょう！」
line = "「やった！　じゃあ行きましょう！」"

[[dialogue]]
speaker = "unk"
# これから人に会う予定のない俺たちは、思う存分ニンニクたっぷりのパスタを味わった。
line = "これから人に会う予定のない俺たちは、思う存分ニンニクたっぷりのパスタを味わった。"

[[dialogue]]
speaker = "ベアトリス"
# 「は～、美味しかった～♪」
line = "「は～、美味しかった～♪」"

[[dialogue]]
speaker = "unk"
# 口の周りが真っ赤になってるよ
line = "口の周りが真っ赤になってるよ"

[[dialogue]]
speaker = "ベアトリス"
# 「ええっ、ウソ！？　ＤＩＳＣで確認を──ああ、ホントだ！？　トマトソースがべったり付いてる！！」
line = "「ええっ、ウソ！？　ＤＩＳＣで確認を──ああ、ホントだ！？　トマトソースがべったり付いてる！！」"

[[dialogue]]
speaker = "ベアトリス"
# 「ふきふき……ごめんなさい。はしたないところをお見せしました……」
line = "「ふきふき……ごめんなさい。はしたないところをお見せしました……」"

[[dialogue]]
speaker = "ベアトリス"
# 「でも会長さんのおかげで、最近足りなかったニンニク分を補充できました。ありがとうございますっ」
line = "「でも会長さんのおかげで、最近足りなかったニンニク分を補充できました。ありがとうございますっ」"

[[dialogue]]
speaker = "ベアトリス"
# 「会長さんは魔王で怖い人だって聞いてたんですけど、全然そんなことなかったです。むしろ優しくて驚いちゃいました」
line = "「会長さんは魔王で怖い人だって聞いてたんですけど、全然そんなことなかったです。むしろ優しくて驚いちゃいました」"

[[dialogue]]
speaker = "unk"
# 吸血鬼なのにニンニクは大丈夫なの？
line = "吸血鬼なのにニンニクは大丈夫なの？"

[[dialogue]]
speaker = "ベアトリス"
# 「あ～、吸血鬼はニンニクが苦手ってやつですね」
line = "「あ～、吸血鬼はニンニクが苦手ってやつですね」"

[[dialogue]]
speaker = "ベアトリス"
# 「吸血鬼は嗅覚が鋭いので、ニンニクの匂いが嫌いな人は多いんですけど、食べたら死ぬとかそんなことはないですよ」
line = "「吸血鬼は嗅覚が鋭いので、ニンニクの匂いが嫌いな人は多いんですけど、食べたら死ぬとかそんなことはないですよ」"

[[dialogue]]
speaker = "ベアトリス"
# 「むしろ私は大好きです！　故郷じゃ全然食べられなかったから、流星市国に来て良かったです！」
line = "「むしろ私は大好きです！　故郷じゃ全然食べられなかったから、流星市国に来て良かったです！」"

[[dialogue]]
speaker = "ベアトリス"
# 「おかげで息がニンニクの匂いになっちゃいましたけど」
line = "「おかげで息がニンニクの匂いになっちゃいましたけど」"

[[dialogue]]
speaker = "ベアトリス"
# 「でも時間は限られてますから。食事を楽しまなきゃ人生損ですっ」
line = "「でも時間は限られてますから。食事を楽しまなきゃ人生損ですっ」"

[[dialogue]]
speaker = "ベアトリス"
# 「──！　モンスター！」
line = "「──！　モンスター！」"

[[dialogue]]
speaker = "ベアトリス"
# 「ここから近いです！　行きましょう、会長さん！」
line = "「ここから近いです！　行きましょう、会長さん！」"

[[dialogue]]
speaker = "ダークキングフワッチ"
# 「イ～～～～～ッ！！」
line = "「イ～～～～～ッ！！」"

[[dialogue]]
speaker = "unk"
# 突如として街に現れる大型モンスター。力ない人々は逃げ惑うが──
line = "突如として街に現れる大型モンスター。力ない人々は逃げ惑うが──"

[[dialogue]]
speaker = "ベアトリス"
# 「させないよ！　ブラッディインベイション──！」
line = "「させないよ！　ブラッディインベイション──！」"

[[dialogue]]
speaker = "ダークキングフワッチ"
# 「イ～～～ッ……」
line = "「イ～～～ッ……」"

[[dialogue]]
speaker = "unk"
# いつもの少し頼りない様子はどこへやら、圧倒的な力でモンスターを駆逐していくベアトリス。
line = "いつもの少し頼りない様子はどこへやら、圧倒的な力でモンスターを駆逐していくベアトリス。"

[[dialogue]]
speaker = "unk"
# その実力は星徒会の役員に匹敵する──あるいはそれ以上かもしれない。
line = "その実力は星徒会の役員に匹敵する──あるいはそれ以上かもしれない。"

[[dialogue]]
speaker = "フワッチ"
# 「イ～～～！」
line = "「イ～～～！」"

[[dialogue]]
speaker = "unk"
# ！　モンスターが逃げる人の方に──！
line = "！　モンスターが逃げる人の方に──！"

[[dialogue]]
speaker = "ベアトリス"
# 「させないって言ってるでしょ！　誰も傷つけさせないから！」
line = "「させないって言ってるでしょ！　誰も傷つけさせないから！」"

[[dialogue]]
speaker = "ベアトリス"
# 「これで終わり──レッドスプラッシュ！」
line = "「これで終わり──レッドスプラッシュ！」"

[[dialogue]]
speaker = "フワッチ"
# 「イ～～……」
line = "「イ～～……」"

[[dialogue]]
speaker = "ベアトリス"
# 「はい、これでおしまいっと。みなさんお怪我はありませんか？」
line = "「はい、これでおしまいっと。みなさんお怪我はありませんか？」"

[[dialogue]]
speaker = "女性"
# 「はい、おかげさまで……んっ！？」
line = "「はい、おかげさまで……んっ！？」"

[[dialogue]]
speaker = "女性"
# 「あ、ありがとうございました……失礼します……」
line = "「あ、ありがとうございました……失礼します……」"

[[dialogue]]
speaker = "ベアトリス"
# 「あ、行っちゃった……。私たち、避けられてる……？　怖がられちゃったのかな？」
line = "「あ、行っちゃった……。私たち、避けられてる……？　怖がられちゃったのかな？」"

[[dialogue]]
speaker = "ナターシャ"
# 「はーい、とうちゃく～」
line = "「はーい、とうちゃく～」"

[[dialogue]]
speaker = "アポロ"
# 「なんだ、もう終わってるじゃんか。モンスターが綺麗さっぱりいなくなってるぞ」
line = "「なんだ、もう終わってるじゃんか。モンスターが綺麗さっぱりいなくなってるぞ」"

[[dialogue]]
speaker = "梨緒"
# 「魔王とベアトか……なら私たちの出る幕はなかったか」
line = "「魔王とベアトか……なら私たちの出る幕はなかったか」"

[[dialogue]]
speaker = "ベアトリス"
# 「そんなことないよ。来てくれてありがとう、みんな」
line = "「そんなことないよ。来てくれてありがとう、みんな」"

[[dialogue]]
speaker = "ナターシャ"
# 「ん？　すんすん……」
line = "「ん？　すんすん……」"

[[dialogue]]
speaker = "梨緒"
# 「これは……」
line = "「これは……」"

[[dialogue]]
speaker = "アポロ"
# 「どうした２人とも？　仲間外れは良くない──んっ！？」
line = "「どうした２人とも？　仲間外れは良くない──んっ！？」"

[[dialogue]]
speaker = "ベアトリス"
# 「どうしたの！？　何かあった！？」
line = "「どうしたの！？　何かあった！？」"

[[dialogue]]
speaker = "ナターシャ"
# 「ごめんベアト、ちょ～っと離れててくれる？」
line = "「ごめんベアト、ちょ～っと離れててくれる？」"

[[dialogue]]
speaker = "梨緒"
# 「ベアト、魔王、こういう言い方はなんだが……匂いがきついぞ」
line = "「ベアト、魔王、こういう言い方はなんだが……匂いがきついぞ」"

[[dialogue]]
speaker = "アポロ"
# 「ニンニク食べすぎだ！　こっち寄るな、ベアト、魔王！」
line = "「ニンニク食べすぎだ！　こっち寄るな、ベアト、魔王！」"

[[dialogue]]
speaker = "ベアトリス"
# 「え～～っ、ごめんなさ～～～いっ！？」
line = "「え～～っ、ごめんなさ～～～いっ！？」"

[[dialogue]]
speaker = "unk"
# 星騎士たる者、緊急の事態を想定し、匂いの強いものはほどほどにはすべき……なのかもしれない。
line = "星騎士たる者、緊急の事態を想定し、匂いの強いものはほどほどにはすべき……なのかもしれない。"
