[[dialogue]]
speaker = "unk"
# アルテが芸術都市『アテネス』に帰還してからのこと──
line = "アルテが芸術都市『アテネス』に帰還してからのこと──"

[[dialogue]]
speaker = "アルテ"
# 「……館長の部屋に来るのも、久しぶりに思えますね」
line = "「……館長の部屋に来るのも、久しぶりに思えますね」"

[[dialogue]]
speaker = "館長"
# 「実際、こんなに長い間、アルテと顔を合わせずにいたのは初めてじゃないか？」
line = "「実際、こんなに長い間、アルテと顔を合わせずにいたのは初めてじゃないか？」"

[[dialogue]]
speaker = "アルテ"
# 「そうですね。まぁ、私は向こうで楽しく過ごしていましたが。特にお肉は絶品で、館長にも食べさせてあげたいくらいでしたよ」
line = "「そうですね。まぁ、私は向こうで楽しく過ごしていましたが。特にお肉は絶品で、館長にも食べさせてあげたいくらいでしたよ」"

[[dialogue]]
speaker = "館長"
# 「異世界か……向こうの人たちにご迷惑をおかけしてないといいんだけど」
line = "「異世界か……向こうの人たちにご迷惑をおかけしてないといいんだけど」"

[[dialogue]]
speaker = "アルテ"
# 「なんですか、その言いぐさは。向こうじゃ敵をちぎっては投げの大活躍だったんですから」
line = "「なんですか、その言いぐさは。向こうじゃ敵をちぎっては投げの大活躍だったんですから」"

[[dialogue]]
speaker = "館長"
# 「そうなのか……？　ならいいんだけど……いや、それならこっちでもそれくらい頑張ってほしいんだが……」
line = "「そうなのか……？　ならいいんだけど……いや、それならこっちでもそれくらい頑張ってほしいんだが……」"

[[dialogue]]
speaker = "館長"
# 「ところでその格好は？　水着かそれ以上に露出がある気がするんだが」
line = "「ところでその格好は？　水着かそれ以上に露出がある気がするんだが」"

[[dialogue]]
speaker = "アルテ"
# 「向こうで変身したんですよ」
line = "「向こうで変身したんですよ」"

[[dialogue]]
speaker = "館長"
# 「変身？」
line = "「変身？」"

[[dialogue]]
speaker = "アルテ"
# 「ええ、念じることで服装が変わるんです。ちなみにこれくらいの露出は向こうでは普通でしたよ」
line = "「ええ、念じることで服装が変わるんです。ちなみにこれくらいの露出は向こうでは普通でしたよ」"

[[dialogue]]
speaker = "館長"
# 「異世界ではそんなことができるのか。……え、普通？」
line = "「異世界ではそんなことができるのか。……え、普通？」"

[[dialogue]]
speaker = "アルテ"
# 「む。何かふしだらなことを考えていませんか、館長？」
line = "「む。何かふしだらなことを考えていませんか、館長？」"

[[dialogue]]
speaker = "館長"
# 「いや、だってだな……」
line = "「いや、だってだな……」"

[[dialogue]]
speaker = "unk"
# 肩どころか胸元もお腹も太ももも露出した姿で、それが普通と言われたら驚かざるを得ない。
line = "肩どころか胸元もお腹も太ももも露出した姿で、それが普通と言われたら驚かざるを得ない。"

[[dialogue]]
speaker = "unk"
# 何より、目の前のアルテの姿が大胆過ぎて意識せずにはいられない。
line = "何より、目の前のアルテの姿が大胆過ぎて意識せずにはいられない。"

[[dialogue]]
speaker = "アルテ"
# 「私が居ない間、館長はどうでしたか？　まるで永遠のように長く感じられたのではありませんか？」
line = "「私が居ない間、館長はどうでしたか？　まるで永遠のように長く感じられたのではありませんか？」"

[[dialogue]]
speaker = "館長"
# 「至って普通だったな」
line = "「至って普通だったな」"

[[dialogue]]
speaker = "アルテ"
# 「強がらなくてもいいんですよ。寂しかったのでしょう？　この天才美少女藝術家が居なかったのですから」
line = "「強がらなくてもいいんですよ。寂しかったのでしょう？　この天才美少女藝術家が居なかったのですから」"

[[dialogue]]
speaker = "館長"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "アルテ"
# 「まったく、仕方がありませんね。その寂しさを埋めるためにも、今夜はここで一緒に寝てあげることにしましょう」
line = "「まったく、仕方がありませんね。その寂しさを埋めるためにも、今夜はここで一緒に寝てあげることにしましょう」"

[[dialogue]]
speaker = "館長"
# 「……それはどうも」
line = "「……それはどうも」"

[[dialogue]]
speaker = "unk"
# しょっちゅう勝手に昼寝してるだろ、とは言わなかった。
line = "しょっちゅう勝手に昼寝してるだろ、とは言わなかった。"

[[dialogue]]
speaker = "unk"
# それで機嫌を損ねてしまったら、絶対に後悔すると思ったから。
line = "それで機嫌を損ねてしまったら、絶対に後悔すると思ったから。"

[[dialogue]]
speaker = "アルテ"
# 「あっ……もう、強引ですね……」
line = "「あっ……もう、強引ですね……」"

[[dialogue]]
speaker = "アルテ"
# 「館長がこんな風に求めてくるなんて……これは私が居なくて相当寂しかったということですかね……」
line = "「館長がこんな風に求めてくるなんて……これは私が居なくて相当寂しかったということですかね……」"

[[dialogue]]
speaker = "アルテ"
# 「いいですよ……んんっ……今日は多少のことは大目に見てあげます……思う存分、この天才美少女成分を摂取してください」
line = "「いいですよ……んんっ……今日は多少のことは大目に見てあげます……思う存分、この天才美少女成分を摂取してください」"

[[dialogue]]
speaker = "館長"
# 「ああ……お言葉に甘えさせてもらうよ」
line = "「ああ……お言葉に甘えさせてもらうよ」"

[[dialogue]]
speaker = "unk"
# アルテを後ろから抱きしめた俺は、片方の手で胸を掴み、もう片方の手でアルテの太股を抱え上げる。
line = "アルテを後ろから抱きしめた俺は、片方の手で胸を掴み、もう片方の手でアルテの太股を抱え上げる。"

[[dialogue]]
speaker = "アルテ"
# 「いやらしい格好ですね……んんっ……は、んぅ……それに館長のこれ……」
line = "「いやらしい格好ですね……んんっ……は、んぅ……それに館長のこれ……」"

[[dialogue]]
speaker = "アルテ"
# 「私のあそこに当たってますよ……おち○ちん、こんなにいきり立たせて……鼻息が荒いにも程があります……んんっ……」
line = "「私のあそこに当たってますよ……おち○ちん、こんなにいきり立たせて……鼻息が荒いにも程があります……んんっ……」"

[[dialogue]]
speaker = "unk"
# アルテの言う通り、俺のペニスはパンパンに怒張していた。
line = "アルテの言う通り、俺のペニスはパンパンに怒張していた。"

[[dialogue]]
speaker = "unk"
# それを意識させるように、下半身を密着させアルテの局部へと擦りつける。
line = "それを意識させるように、下半身を密着させアルテの局部へと擦りつける。"

[[dialogue]]
speaker = "アルテ"
# 「はぁ、あ……んぅん……おち○ちん、こんなに硬くしてしまって……んんっ……そんなに私と交われることが、嬉しいんですか……？」
line = "「はぁ、あ……んぅん……おち○ちん、こんなに硬くしてしまって……んんっ……そんなに私と交われることが、嬉しいんですか……？」"

[[dialogue]]
speaker = "アルテ"
# 「ふふっ……こんなに興奮させてしまって……少し申し訳ない気持ちにもなってきますね……」
line = "「ふふっ……こんなに興奮させてしまって……少し申し訳ない気持ちにもなってきますね……」"

[[dialogue]]
speaker = "アルテ"
# 「仕方ないですね……太ももでもあそこでも、好きなだけ擦りつけるといいですよ」
line = "「仕方ないですね……太ももでもあそこでも、好きなだけ擦りつけるといいですよ」"

[[dialogue]]
speaker = "unk"
# 匂い付けでもするようにペニスをアルテの肌に押し付け、ゾクゾクするような快感を下半身に感じながら、胸だけでなく全身をまさぐっていく。
line = "匂い付けでもするようにペニスをアルテの肌に押し付け、ゾクゾクするような快感を下半身に感じながら、胸だけでなく全身をまさぐっていく。"

[[dialogue]]
speaker = "アルテ"
# 「あっ、んん……館長の手……私の身体のラインを、確かめるみたいに……んんんっ……そんな、いやらしい触り方……あ……はぁ、あ、んんっ……」
line = "「あっ、んん……館長の手……私の身体のラインを、確かめるみたいに……んんんっ……そんな、いやらしい触り方……あ……はぁ、あ、んんっ……」"

[[dialogue]]
speaker = "unk"
# 首元に顔をうずめて、汗ばんだ肌に舌を這わせる。
line = "首元に顔をうずめて、汗ばんだ肌に舌を這わせる。"

[[dialogue]]
speaker = "アルテ"
# 「あっ……！　んぅ、あ……や……首筋、弱いんです……んんんっ……そんなに、舐めないで……」
line = "「あっ……！　んぅ、あ……や……首筋、弱いんです……んんんっ……そんなに、舐めないで……」"

[[dialogue]]
speaker = "unk"
# 彼女の声から、次第に余裕の色が失われていくのが分かった。
line = "彼女の声から、次第に余裕の色が失われていくのが分かった。"

[[dialogue]]
speaker = "館長"
# 「アルテ……」
line = "「アルテ……」"

[[dialogue]]
speaker = "unk"
# 痛いほどに張り詰めたペニスの先端を、おもむろに彼女の入り口へと押し当てた。
line = "痛いほどに張り詰めたペニスの先端を、おもむろに彼女の入り口へと押し当てた。"

[[dialogue]]
speaker = "アルテ"
# 「っん……！　なんですか、もう……入れたいんですか……？」
line = "「っん……！　なんですか、もう……入れたいんですか……？」"

[[dialogue]]
speaker = "unk"
# 先端を少し潜らせただけで、花びらの内側からあふれ出した蜜液でベトベトに濡れるのが分かる。
line = "先端を少し潜らせただけで、花びらの内側からあふれ出した蜜液でベトベトに濡れるのが分かる。"

[[dialogue]]
speaker = "アルテ"
# 「仕方ありませんね。いいですよ……挿れて、ください……」
line = "「仕方ありませんね。いいですよ……挿れて、ください……」"

[[dialogue]]
speaker = "アルテ"
# 「あっ……！！　んんんんんぅうっ……！！！」
line = "「あっ……！！　んんんんんぅうっ……！！！」"

[[dialogue]]
speaker = "unk"
# 力強く、アルテの身体を引き寄せるようにして、ペニスを奥まで押し込む。
line = "力強く、アルテの身体を引き寄せるようにして、ペニスを奥まで押し込む。"

[[dialogue]]
speaker = "unk"
# 瞬く間に幹の部分から根元まで、すっぽりと温かい感触に包まれる。
line = "瞬く間に幹の部分から根元まで、すっぽりと温かい感触に包まれる。"

[[dialogue]]
speaker = "アルテ"
# 「ああっ……んっ、あっ……ああ……！　あ、んんっ……はぁっ、あ……ああっ……！」
line = "「ああっ……んっ、あっ……ああ……！　あ、んんっ……はぁっ、あ……ああっ……！」"

[[dialogue]]
speaker = "アルテ"
# 「館長のが……あっ……あん……っ！　はぁ、はっ、んっ……いつもより、大きい……んっ……！」
line = "「館長のが……あっ……あん……っ！　はぁ、はっ、んっ……いつもより、大きい……んっ……！」"

[[dialogue]]
speaker = "unk"
# そのままの勢いで、ゆるやかなピストンを始めると、彼女は驚いたように身体を跳ねさせる。
line = "そのままの勢いで、ゆるやかなピストンを始めると、彼女は驚いたように身体を跳ねさせる。"

[[dialogue]]
speaker = "アルテ"
# 「はあっ、あっ、あっ……ん、んんっ……んぅ……はぁ、んぅ……あ、あああ……あ、あ、んんんっ……！」
line = "「はあっ、あっ、あっ……ん、んんっ……んぅ……はぁ、んぅ……あ、あああ……あ、あ、んんんっ……！」"

[[dialogue]]
speaker = "アルテ"
# 「ん、ぁ……ちょっと、まって、ください……んんっ……いきなり、動くんですか……んんんっ……」
line = "「ん、ぁ……ちょっと、まって、ください……んんっ……いきなり、動くんですか……んんんっ……」"

[[dialogue]]
speaker = "アルテ"
# 「私と、久しぶりにできて……嬉しいのはわかりますが……あっ、ああ……！　ちょっと、激し過ぎでしょう……んんんっ……！」
line = "「私と、久しぶりにできて……嬉しいのはわかりますが……あっ、ああ……！　ちょっと、激し過ぎでしょう……んんんっ……！」"

[[dialogue]]
speaker = "館長"
# 「そんなに激しくは動いてないぞ。今日のアルテはいつもより感じやすいのか……？」
line = "「そんなに激しくは動いてないぞ。今日のアルテはいつもより感じやすいのか……？」"

[[dialogue]]
speaker = "アルテ"
# 「そんな……ことは……」
line = "「そんな……ことは……」"

[[dialogue]]
speaker = "館長"
# 「嬉しいよ。アルテも俺と同じ気持ちだってこと」
line = "「嬉しいよ。アルテも俺と同じ気持ちだってこと」"

[[dialogue]]
speaker = "アルテ"
# 「な、何を言っているんです……あっ、ん、ああぁあっ……！」
line = "「な、何を言っているんです……あっ、ん、ああぁあっ……！」"

[[dialogue]]
speaker = "unk"
# 余裕のある口ぶりで軽口を叩いてみせても、本心では久しぶりに会えたことが嬉しくて心を震わせている。
line = "余裕のある口ぶりで軽口を叩いてみせても、本心では久しぶりに会えたことが嬉しくて心を震わせている。"

[[dialogue]]
speaker = "unk"
# こうして抱きしめて、ひとつに交わり合うことにこの上ない喜びを感じてくれている。
line = "こうして抱きしめて、ひとつに交わり合うことにこの上ない喜びを感じてくれている。"

[[dialogue]]
speaker = "unk"
# そして、求めている。<b>求められる</b>ことを。
line = "そして、求めている。<b>求められる</b>ことを。"

[[dialogue]]
speaker = "館長"
# 「アルテが居ない間、俺はずっと寂しかったぞ……こうして抱きしめたいとずっと思ってた……」
line = "「アルテが居ない間、俺はずっと寂しかったぞ……こうして抱きしめたいとずっと思ってた……」"

[[dialogue]]
speaker = "アルテ"
# 「ぁ……う……そんなこと、言わなくていいですってば……」
line = "「ぁ……う……そんなこと、言わなくていいですってば……」"

[[dialogue]]
speaker = "アルテ"
# 「ふっ……んっ……ん……ひぁああっ……！　館長のおち○ちん、いつもより、熱いです……」
line = "「ふっ……んっ……ん……ひぁああっ……！　館長のおち○ちん、いつもより、熱いです……」"

[[dialogue]]
speaker = "アルテ"
# 「はぁっ、はっ、んんっ……あっ……！　ぞりぞりって、内側なぞるみたいに、すりつけてきて……はあぁ……」
line = "「はぁっ、はっ、んんっ……あっ……！　ぞりぞりって、内側なぞるみたいに、すりつけてきて……はあぁ……」"

[[dialogue]]
speaker = "アルテ"
# 「はぁはっ、あ……ん、んん……今日の館長、なんだかねちっこくて、ゾクゾクします……んんっ……！」
line = "「はぁはっ、あ……ん、んん……今日の館長、なんだかねちっこくて、ゾクゾクします……んんっ……！」"

[[dialogue]]
speaker = "アルテ"
# 「んっ、はぁ……私のこと、そんなに抱きたかったんですか……？　もう、いやらしい人です……んっ……はあぁ……ふぁああっ！」
line = "「んっ、はぁ……私のこと、そんなに抱きたかったんですか……？　もう、いやらしい人です……んっ……はあぁ……ふぁああっ！」"

[[dialogue]]
speaker = "アルテ"
# 「本当に、仕方ない人……はっ、あっ、あっ……私じゃないと、愛想尽かして、出ていっちゃうんですから……」
line = "「本当に、仕方ない人……はっ、あっ、あっ……私じゃないと、愛想尽かして、出ていっちゃうんですから……」"

[[dialogue]]
speaker = "館長"
# 「ああ、だからもうどこにも行くなよ……」
line = "「ああ、だからもうどこにも行くなよ……」"

[[dialogue]]
speaker = "アルテ"
# 「やぁ、ぅ……どうして……そんなこと、言うんですか……んんんっ……そんなこと、言われたらぁ……」
line = "「やぁ、ぅ……どうして……そんなこと、言うんですか……んんんっ……そんなこと、言われたらぁ……」"

[[dialogue]]
speaker = "unk"
# 内に秘めた喜びを示すように、俺を包み込んだ膣壁が切なそうに締め付けてくる。
line = "内に秘めた喜びを示すように、俺を包み込んだ膣壁が切なそうに締め付けてくる。"

[[dialogue]]
speaker = "unk"
# 俺はわずかに残ったアルテの虚勢をはぎ取るように、彼女の膣の奥深くを貫いた。
line = "俺はわずかに残ったアルテの虚勢をはぎ取るように、彼女の膣の奥深くを貫いた。"

[[dialogue]]
speaker = "アルテ"
# 「あああっ……！　んんっ、あっ、あっ、あああっ！　あ、あっ、んんっ、あ、あああっ、ん、ああああっ<emoji=heart04>」
line = "「あああっ……！　んんっ、あっ、あっ、あああっ！　あ、あっ、んんっ、あ、あああっ、ん、ああああっ<emoji=heart04>」"

[[dialogue]]
speaker = "アルテ"
# 「あぁ、あ、んんっ……嬉しい、です……んんっ、あ……ああっ……そんなの、嬉しくなっちゃうじゃ……ないですか……あ、あああっ<emoji=heart04>」
line = "「あぁ、あ、んんっ……嬉しい、です……んんっ、あ……ああっ……そんなの、嬉しくなっちゃうじゃ……ないですか……あ、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 激しさを増したピストンに、彼女の本心がこぼれ出る。
line = "激しさを増したピストンに、彼女の本心がこぼれ出る。"

[[dialogue]]
speaker = "unk"
# そして、一度こぼれ出てしまえば、もうそれをせき止める術はなかった。
line = "そして、一度こぼれ出てしまえば、もうそれをせき止める術はなかった。"

[[dialogue]]
speaker = "アルテ"
# 「あっ、あ、あ、ああっ……んんんぅっ……あぁ、あ……あ、ああっ……<emoji=heart04>」
line = "「あっ、あ、あ、ああっ……んんんぅっ……あぁ、あ……あ、ああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アルテ"
# 「あぁあ、んんっ……感じて、ますっ……館長にこんな風に、ズボズボしてもらえて……私っ、悦んじゃってますっ……<emoji=heart04>」
line = "「あぁあ、んんっ……感じて、ますっ……館長にこんな風に、ズボズボしてもらえて……私っ、悦んじゃってますっ……<emoji=heart04>」"

[[dialogue]]
speaker = "館長"
# 「ああ、分かるよ……アルテの中、洪水みたいになってるし、締め付けも凄くて……」
line = "「ああ、分かるよ……アルテの中、洪水みたいになってるし、締め付けも凄くて……」"

[[dialogue]]
speaker = "アルテ"
# 「っ、あ、んうううっ……だって、そうして欲しいと思ってたら……館長が抱きしめてくれて……」
line = "「っ、あ、んうううっ……だって、そうして欲しいと思ってたら……館長が抱きしめてくれて……」"

[[dialogue]]
speaker = "アルテ"
# 「私のこと……こんなに求めてくれて……あああっ……嬉しくないはず、ないですっ……んん、あああっ……！」
line = "「私のこと……こんなに求めてくれて……あああっ……嬉しくないはず、ないですっ……んん、あああっ……！」"

[[dialogue]]
speaker = "アルテ"
# 「はあっ、あっ、あああっ！　もっと、求めてくださいっ！　んんっ……！　もう、どこにも行くなって、身体に刻み付けてくださいっ！」
line = "「はあっ、あっ、あああっ！　もっと、求めてくださいっ！　んんっ……！　もう、どこにも行くなって、身体に刻み付けてくださいっ！」"

[[dialogue]]
speaker = "館長"
# 「ああ……思いっきり刻み付けてやるよ」
line = "「ああ……思いっきり刻み付けてやるよ」"

[[dialogue]]
speaker = "アルテ"
# 「あっ！　あっ！　あ、あぁあああっ<emoji=heart04>　あ、んんっ<emoji=heart04>　あ、んんっ、あ、あああ……感じ、る……んんぅううっ、あ、あああっ<emoji=heart04>」
line = "「あっ！　あっ！　あ、あぁあああっ<emoji=heart04>　あ、んんっ<emoji=heart04>　あ、んんっ、あ、あああ……感じ、る……んんぅううっ、あ、あああっ<emoji=heart04>」"

[[dialogue]]
speaker = "アルテ"
# 「ああ、あ、はあっ！　あ、ん、あ、んんんっ！　あ、あああっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　や、あ、んんぅううっ……<emoji=heart04>」
line = "「ああ、あ、はあっ！　あ、ん、あ、んんんっ！　あ、あああっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　や、あ、んんぅううっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 絶対にどこにも行けないくらいアルテの身体をしっかり抱きしめながら、何度も何度も身体を打ち付ける。
line = "絶対にどこにも行けないくらいアルテの身体をしっかり抱きしめながら、何度も何度も身体を打ち付ける。"

[[dialogue]]
speaker = "unk"
# 一心不乱に身体を揺さぶり動かしながら、下半身に湧き立つような激しい熱を感じる。
line = "一心不乱に身体を揺さぶり動かしながら、下半身に湧き立つような激しい熱を感じる。"

[[dialogue]]
speaker = "アルテ"
# 「ああっ<emoji=heart04>　んん、あ、あああっ<emoji=heart04>　んんぅ、あ、あ、あああっ、あ……んん、あ、ああぁああっ……<emoji=heart04>」
line = "「ああっ<emoji=heart04>　んん、あ、あああっ<emoji=heart04>　んんぅ、あ、あ、あああっ、あ……んん、あ、ああぁああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アルテ"
# 「館長の、んんっ、あぁああ、っ、あ<emoji=heart04>　私の中で……暴れて、ますっ……ああっ、ん、ぁ、ああっ……んんぅう、あ、あああっ……<emoji=heart04>」
line = "「館長の、んんっ、あぁああ、っ、あ<emoji=heart04>　私の中で……暴れて、ますっ……ああっ、ん、ぁ、ああっ……んんぅう、あ、あああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アルテ"
# 「はぁ、あ……んんっ……館長っ、んんっ……イキそう、なんですね……んんっ、あ、あああっ……！」
line = "「はぁ、あ……んんっ……館長っ、んんっ……イキそう、なんですね……んんっ、あ、あああっ……！」"

[[dialogue]]
speaker = "アルテ"
# 「あっ、あ、んんっ、あ、あ、んんっ<emoji=heart04>　おねがい……ですっ、んんっ……あ……そのまま、イッて……くださいっ……んんうっ<emoji=heart04>」
line = "「あっ、あ、んんっ、あ、あ、んんっ<emoji=heart04>　おねがい……ですっ、んんっ……あ……そのまま、イッて……くださいっ……んんうっ<emoji=heart04>」"

[[dialogue]]
speaker = "アルテ"
# 「一番、奥でっ<emoji=heart04>　射精、してっ<emoji=heart04>　熱いの、思いっきり、注ぎ込んで、くだ、さいっ<emoji=heart04>　んんんっ、んうっ……！」
line = "「一番、奥でっ<emoji=heart04>　射精、してっ<emoji=heart04>　熱いの、思いっきり、注ぎ込んで、くだ、さいっ<emoji=heart04>　んんんっ、んうっ……！」"

[[dialogue]]
speaker = "unk"
# ひと際乱れたアルテの嬌声に、押しとどめていた欲望が一気にせり上がってくる。
line = "ひと際乱れたアルテの嬌声に、押しとどめていた欲望が一気にせり上がってくる。"

[[dialogue]]
speaker = "アルテ"
# 「あっ！　あ、あああっ！　んんっ、く、イクっ、い、イキます、私も……あああっ、や、んんっ、あ、あ、あ、あああっ！」
line = "「あっ！　あ、あああっ！　んんっ、く、イクっ、い、イキます、私も……あああっ、や、んんっ、あ、あ、あ、あああっ！」"

[[dialogue]]
speaker = "アルテ"
# 「あああ、あっ、あ、あ、ああっ<emoji=heart04>　んんっ、あ、ああっ、館長っ、館長っ、あ、ああっ、あ、んんっ、あ、もう、私、あ、ああああっ……<emoji=heart04>」
line = "「あああ、あっ、あ、あ、ああっ<emoji=heart04>　んんっ、あ、ああっ、館長っ、館長っ、あ、ああっ、あ、んんっ、あ、もう、私、あ、ああああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "アルテ"
# 「イク、イク、イッくぅっ<emoji=heart04>　イクイクっ<emoji=heart04>　ふぁっ、あ、あ、あ、あ<emoji=heart04>　あっ──あっ──あっ──ああぁっ──」
line = "「イク、イク、イッくぅっ<emoji=heart04>　イクイクっ<emoji=heart04>　ふぁっ、あ、あ、あ、あ<emoji=heart04>　あっ──あっ──あっ──ああぁっ──」"

[[dialogue]]
speaker = "アルテ"
# 「や、んぅ……ぁ……あああああああああああああああああっ<emoji=heart04><emoji=heart04><emoji=heart04>！！！！！」
line = "「や、んぅ……ぁ……あああああああああああああああああっ<emoji=heart04><emoji=heart04><emoji=heart04>！！！！！」"

[[dialogue]]
speaker = "unk"
# アルテの絶頂の叫びと共に、弾けるような欲望のほとばしりを感じる。
line = "アルテの絶頂の叫びと共に、弾けるような欲望のほとばしりを感じる。"

[[dialogue]]
speaker = "unk"
# 下半身がドクドクと脈打ち、熱い液体がアルテの膣内を満たしていく。
line = "下半身がドクドクと脈打ち、熱い液体がアルテの膣内を満たしていく。"

[[dialogue]]
speaker = "アルテ"
# 「ああっ、あっ、んんっ！　せい、しっ、出てるっ……館長の、熱い精子、いっぱい注ぎ込まれてます……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「ああっ、あっ、んんっ！　せい、しっ、出てるっ……館長の、熱い精子、いっぱい注ぎ込まれてます……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "アルテ"
# 「身体、ビクビクして……止まらない、んんっ、ああっ……<emoji=heart04>　あ、は、あああ、んんっ、あ……んんぅ……あ、ああああっ……<emoji=heart04>」
line = "「身体、ビクビクして……止まらない、んんっ、ああっ……<emoji=heart04>　あ、は、あああ、んんっ、あ……んんぅ……あ、ああああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 搾り取るようにペニスを締め上げながら、激しい絶頂の波に呑まれるアルテ。
line = "搾り取るようにペニスを締め上げながら、激しい絶頂の波に呑まれるアルテ。"

[[dialogue]]
speaker = "unk"
# 硬直した身体から少しずつ力が抜け始めたのは、アルテの膣内を思う存分満たし尽くした後だった。
line = "硬直した身体から少しずつ力が抜け始めたのは、アルテの膣内を思う存分満たし尽くした後だった。"

[[dialogue]]
speaker = "アルテ"
# 「はぁ……ふぅ……んん……んぅ……」
line = "「はぁ……ふぅ……んん……んぅ……」"

[[dialogue]]
speaker = "アルテ"
# 「見なくても、分かります……どれだけ出したんですか……」
line = "「見なくても、分かります……どれだけ出したんですか……」"

[[dialogue]]
speaker = "館長"
# 「自分でもびっくりするほど、だな……」
line = "「自分でもびっくりするほど、だな……」"

[[dialogue]]
speaker = "アルテ"
# 「少し顔を見られなかったくらいでこんなになってしまうなんて……館長はどれだけ私のことが好きなんですか……？」
line = "「少し顔を見られなかったくらいでこんなになってしまうなんて……館長はどれだけ私のことが好きなんですか……？」"

[[dialogue]]
speaker = "館長"
# 「そんな事を言いながら、アルテの本音はちゃんと聞かせてもらったから」
line = "「そんな事を言いながら、アルテの本音はちゃんと聞かせてもらったから」"

[[dialogue]]
speaker = "アルテ"
# 「さ、さて……何のことだか……」
line = "「さ、さて……何のことだか……」"

[[dialogue]]
speaker = "アルテ"
# 「でもまあ、これからはあなたの傍からいなくならないようにしてあげますよ……」
line = "「でもまあ、これからはあなたの傍からいなくならないようにしてあげますよ……」"

[[dialogue]]
speaker = "unk"
# アルテは懸命にいつもの調子を取り戻そうとしているようだった。
line = "アルテは懸命にいつもの調子を取り戻そうとしているようだった。"

[[dialogue]]
speaker = "unk"
# きっとそうしないと、明日からどうやって顔を合わせていいかわからなくなるから。
line = "きっとそうしないと、明日からどうやって顔を合わせていいかわからなくなるから。"

[[dialogue]]
speaker = "unk"
# だから無理やり取り繕おうとしているのだと思うと、アルテのことが可愛くて可愛くてたまらなくなってしまうのだった。
line = "だから無理やり取り繕おうとしているのだと思うと、アルテのことが可愛くて可愛くてたまらなくなってしまうのだった。"
