[[dialogue]]
speaker = "unk"
# 第４話,キャラ崩壊デート,P
line = "第４話,キャラ崩壊デート,P"

[[dialogue]]
speaker = "unk"
# 週末──俺は遊園地の前でロクサーナの到着を待っていた
line = "週末──俺は遊園地の前でロクサーナの到着を待っていた"

[[dialogue]]
speaker = "ロクサーナ"
# 「待たせちゃった？　会長さん、ごめんね♪」
line = "「待たせちゃった？　会長さん、ごめんね♪」"

[[dialogue]]
speaker = "unk"
# 今来たばかりだよ
line = "今来たばかりだよ"

[[dialogue]]
speaker = "ロクサーナ"
# 「ええ～、ホントに～？　会長さんってば優しいんだから～」
line = "「ええ～、ホントに～？　会長さんってば優しいんだから～」"

[[dialogue]]
speaker = "ロクサーナ"
# 「遊園地なんて、久しぶり～。すっごく楽しみで昨日は眠れなかったんだから～♪」
line = "「遊園地なんて、久しぶり～。すっごく楽しみで昨日は眠れなかったんだから～♪」"

[[dialogue]]
speaker = "ロクサーナ"
# 「……ふぅぅ、ちょっと素に返るぞ、会長」
line = "「……ふぅぅ、ちょっと素に返るぞ、会長」"

[[dialogue]]
speaker = "ロクサーナ"
# 「ヴォエェ……甘ったるすぎて、唾液がガムシロップにでもなってしまいそうだ……！」
line = "「ヴォエェ……甘ったるすぎて、唾液がガムシロップにでもなってしまいそうだ……！」"

[[dialogue]]
speaker = "unk"
# ……あまり無理しなくても
line = "……あまり無理しなくても"

[[dialogue]]
speaker = "ロクサーナ"
# 「だが、これが世界のごく一般的なカップルの姿だというならば実体験を得ねばならない」
line = "「だが、これが世界のごく一般的なカップルの姿だというならば実体験を得ねばならない」"

[[dialogue]]
speaker = "ロクサーナ"
# 「どんなに辛かろうとも、吐き気をもよそうとも……脚本家のプライドには代えられん！」
line = "「どんなに辛かろうとも、吐き気をもよそうとも……脚本家のプライドには代えられん！」"

[[dialogue]]
speaker = "unk"
# 何故、ロクサーナのキャラが変わってしまう事態になったかというと──
line = "何故、ロクサーナのキャラが変わってしまう事態になったかというと──"

[[dialogue]]
speaker = "ロクサーナ"
# 「うぅ～む……！」
line = "「うぅ～む……！」"

[[dialogue]]
speaker = "ロクサーナ"
# 「先日のオリジナル劇の後の、観客の反応だ。概ね高評価なのだがな、しかし」
line = "「先日のオリジナル劇の後の、観客の反応だ。概ね高評価なのだがな、しかし」"

[[dialogue]]
speaker = "unk"
# 紙の束を渡された。そこには先日の演劇部の劇を見た感想が書かれていたのだが──
line = "紙の束を渡された。そこには先日の演劇部の劇を見た感想が書かれていたのだが──"

[[dialogue]]
speaker = "ロクサーナ"
# 「『カップルというよりライバル同士』『デートというより決闘』『スキンシップというより組手』」
line = "「『カップルというよりライバル同士』『デートというより決闘』『スキンシップというより組手』」"

[[dialogue]]
speaker = "ロクサーナ"
# 「恋人同士の甘いシーンを書いたはずなのに、絶望的なまでに違う解釈で受け取られている！」
line = "「恋人同士の甘いシーンを書いたはずなのに、絶望的なまでに違う解釈で受け取られている！」"

[[dialogue]]
speaker = "unk"
# 面白かったけどね
line = "面白かったけどね"

[[dialogue]]
speaker = "ロクサーナ"
# 「面白ければ良いというものではない！」
line = "「面白ければ良いというものではない！」"

[[dialogue]]
speaker = "ロクサーナ"
# 「やはり私には経験が足りていないのだな。恋人のみが生み出す空気感……」
line = "「やはり私には経験が足りていないのだな。恋人のみが生み出す空気感……」"

[[dialogue]]
speaker = "ロクサーナ"
# 「後学のためにも演出家たるもの、色事のひとつも学んでおかねばな……」
line = "「後学のためにも演出家たるもの、色事のひとつも学んでおかねばな……」"

[[dialogue]]
speaker = "ロクサーナ"
# 「しかし、私にはデートに行ってくれる男などおらん。はぁ……同年代の異性が都合よく目の前にいたりはしないものか──ん？」
line = "「しかし、私にはデートに行ってくれる男などおらん。はぁ……同年代の異性が都合よく目の前にいたりはしないものか──ん？」"

[[dialogue]]
speaker = "ロクサーナ"
# 「いるではないか！！！」
line = "「いるではないか！！！」"

[[dialogue]]
speaker = "ロクサーナ"
# 「会長！　私を助けると思って、デートをしろ！　今週末、遊園地に向かうぞ！」
line = "「会長！　私を助けると思って、デートをしろ！　今週末、遊園地に向かうぞ！」"

[[dialogue]]
speaker = "unk"
# そんなこんなで、ロクサーナとデートする流れとなり、現在に至る。『甘い空気の出し方』を少し勘違いしているような気もするが……。
line = "そんなこんなで、ロクサーナとデートする流れとなり、現在に至る。『甘い空気の出し方』を少し勘違いしているような気もするが……。"

[[dialogue]]
speaker = "ロクサーナ"
# 「わぁ、美味しそうなクレープ♪　はい、クロトきゅん、あーんして♪」
line = "「わぁ、美味しそうなクレープ♪　はい、クロトきゅん、あーんして♪」"

[[dialogue]]
speaker = "unk"
# あ、あーん……
line = "あ、あーん……"

[[dialogue]]
speaker = "ロクサーナ"
# 「どう？　美味し？　美味しいよね♪」
line = "「どう？　美味し？　美味しいよね♪」"

[[dialogue]]
speaker = "ロクサーナ"
# 「同じスプーン、ペットボトル、ストローを用いての飲食……わざわざ交換する手間は省けるな」
line = "「同じスプーン、ペットボトル、ストローを用いての飲食……わざわざ交換する手間は省けるな」"

[[dialogue]]
speaker = "ロクサーナ"
# 「だが、効率の問題ではないように思える。カップルは誰もがこのように分け合って楽しそうに食べるものだ……会長、私の口にもくれ。あーん」
line = "「だが、効率の問題ではないように思える。カップルは誰もがこのように分け合って楽しそうに食べるものだ……会長、私の口にもくれ。あーん」"

[[dialogue]]
speaker = "ロクサーナ"
# 「あむ。もぐもぐ……うむ、甘くて美味い。お高めのアイスクリームの味がする。もう一口だ。あーん」
line = "「あむ。もぐもぐ……うむ、甘くて美味い。お高めのアイスクリームの味がする。もう一口だ。あーん」"

[[dialogue]]
speaker = "unk"
# 思うところはいろいろあるみたいだけれど、嫌がっているわけではないらしかった。
line = "思うところはいろいろあるみたいだけれど、嫌がっているわけではないらしかった。"

[[dialogue]]
speaker = "ロクサーナ"
# 「先ほどのお化け屋敷、うっすらとギミックが透けて見えていたな。ホラー映画の文脈を辿れば、ここで脅かしに来るだろうというのが見え見えだ」
line = "「先ほどのお化け屋敷、うっすらとギミックが透けて見えていたな。ホラー映画の文脈を辿れば、ここで脅かしに来るだろうというのが見え見えだ」"

[[dialogue]]
speaker = "ロクサーナ"
# 「いわゆる吊り橋効果を狙ったものか。『いやーん♪　怖ーい♪』とか黄色い声をあげて、すり寄るのが正解か？　馬鹿馬鹿しいこと、この上ないな」
line = "「いわゆる吊り橋効果を狙ったものか。『いやーん♪　怖ーい♪』とか黄色い声をあげて、すり寄るのが正解か？　馬鹿馬鹿しいこと、この上ないな」"

[[dialogue]]
speaker = "ロクサーナ"
# 「まったく、世の恋人どもは凡骨の集まりなのか？　『恋とはまったく一種の狂気』とはよく言ったものだ」
line = "「まったく、世の恋人どもは凡骨の集まりなのか？　『恋とはまったく一種の狂気』とはよく言ったものだ」"

[[dialogue]]
speaker = "ロクサーナ"
# 「ジェットコースター、ゴーカート、コーヒーカップ、メリーゴーラウンド、観覧車……一通り乗ったら、もう閉園時間だな。そろそろ帰るとしようか」
line = "「ジェットコースター、ゴーカート、コーヒーカップ、メリーゴーラウンド、観覧車……一通り乗ったら、もう閉園時間だな。そろそろ帰るとしようか」"

[[dialogue]]
speaker = "unk"
# 楽しかった……？
line = "楽しかった……？"

[[dialogue]]
speaker = "ロクサーナ"
# 「ふうむ……そうだな。終わってみれば、悪い気はしなかった」
line = "「ふうむ……そうだな。終わってみれば、悪い気はしなかった」"

[[dialogue]]
speaker = "ロクサーナ"
# 「なるほど、定番のデートスポットだから遊園地を選択したが……遊園地である必要はなかったのかもしれん」
line = "「なるほど、定番のデートスポットだから遊園地を選択したが……遊園地である必要はなかったのかもしれん」"

[[dialogue]]
speaker = "ロクサーナ"
# 「デートとは何処に行ったかより、誰と行って、どれだけ同じ時間を過ごしたのかが重要に思えた」
line = "「デートとは何処に行ったかより、誰と行って、どれだけ同じ時間を過ごしたのかが重要に思えた」"

[[dialogue]]
speaker = "ロクサーナ"
# 「会長はどうだ……？　私とのデートは、その、なんだ……楽しめたか？」
line = "「会長はどうだ……？　私とのデートは、その、なんだ……楽しめたか？」"

[[dialogue]]
speaker = "unk"
# もちろん！
line = "もちろん！"

[[dialogue]]
speaker = "ロクサーナ"
# 「そうか！　それは何よりだ！　またいずれ、デートに付き合ってくれ。次回作の資料を集めるのに、水族館なども良いな」
line = "「そうか！　それは何よりだ！　またいずれ、デートに付き合ってくれ。次回作の資料を集めるのに、水族館なども良いな」"

[[dialogue]]
speaker = "ロクサーナ"
# 「多忙な中、丸１日付き合わせてしまって、すまなかったな。協力に感謝する。おかげで貴重な経験ができた」
line = "「多忙な中、丸１日付き合わせてしまって、すまなかったな。協力に感謝する。おかげで貴重な経験ができた」"

[[dialogue]]
speaker = "ロクサーナ"
# 「私の探求心をここまで引き付けた男は、お前が初めてだ。これからも密着取材は続けさせてもらう」
line = "「私の探求心をここまで引き付けた男は、お前が初めてだ。これからも密着取材は続けさせてもらう」"

[[dialogue]]
speaker = "ロクサーナ"
# 「いつかは『会長』ではなく『緋宮クロト』という男の辿る人生そのものを脚本にし、後世まで残したいものだ」
line = "「いつかは『会長』ではなく『緋宮クロト』という男の辿る人生そのものを脚本にし、後世まで残したいものだ」"

[[dialogue]]
speaker = "unk"
# ちょっと恥ずかしいな
line = "ちょっと恥ずかしいな"

[[dialogue]]
speaker = "ロクサーナ"
# 「何を恥ずかしがることがある！　私の生涯を賭す超大作にして傑作になるだろうよ、はっはっは！」
line = "「何を恥ずかしがることがある！　私の生涯を賭す超大作にして傑作になるだろうよ、はっはっは！」"

[[dialogue]]
speaker = "unk"
# これからもずっと、いつまでも末永く。
line = "これからもずっと、いつまでも末永く。"

[[dialogue]]
speaker = "unk"
# ロクサーナの密着取材は続くのであった。
line = "ロクサーナの密着取材は続くのであった。"
