[[dialogue]]
speaker = "unk"
# 第４話,事件解決？,P
line = "第４話,事件解決？,P"

[[dialogue]]
speaker = "unk"
# 食事を済ませた後、人探しを再開する俺たち。
line = "食事を済ませた後、人探しを再開する俺たち。"

[[dialogue]]
speaker = "unk"
# しかし、目撃情報はあれど空振りばかりで、時間ばかりが無駄に過ぎ去ってしまっていた。
line = "しかし、目撃情報はあれど空振りばかりで、時間ばかりが無駄に過ぎ去ってしまっていた。"

[[dialogue]]
speaker = "unk"
# 次第に有力な情報もなくなり、ついにその足取りは完全に途絶えてしまう。
line = "次第に有力な情報もなくなり、ついにその足取りは完全に途絶えてしまう。"

[[dialogue]]
speaker = "unk"
# と、困り果てていたところに、意外な相手からの連絡が入った。
line = "と、困り果てていたところに、意外な相手からの連絡が入った。"

[[dialogue]]
speaker = "リーリア"
# 『実はですね～、異世界から来たと思われる魔法使い？　をネビュラで保護してるんですよ！』
line = "『実はですね～、異世界から来たと思われる魔法使い？　をネビュラで保護してるんですよ！』"

[[dialogue]]
speaker = "リーリア"
# 『これって多分、センパイたちが掲示板で捜してる人じゃないかなーって思って連絡をしてみたわけです♪　どうです、助かっちゃいますか？』
line = "『これって多分、センパイたちが掲示板で捜してる人じゃないかなーって思って連絡をしてみたわけです♪　どうです、助かっちゃいますか？』"

[[dialogue]]
speaker = "unk"
# ネビュラの基地に向かうと、そこには捜していた女性──ノルトハウゼンさんが待っていた。
line = "ネビュラの基地に向かうと、そこには捜していた女性──ノルトハウゼンさんが待っていた。"

[[dialogue]]
speaker = "unk"
# 無事に彼女を保護できたことに安堵しつつも、星徒会室に戻ったころにはすっかり夕方になっていた。
line = "無事に彼女を保護できたことに安堵しつつも、星徒会室に戻ったころにはすっかり夕方になっていた。"

[[dialogue]]
speaker = "ベア子"
# 「無事に見つかったみたいですね。よかったくま……」
line = "「無事に見つかったみたいですね。よかったくま……」"

[[dialogue]]
speaker = "黒ベア子"
# 「まったく、待たせ過ぎくま！　急いで次の世界に向かうくま！」
line = "「まったく、待たせ過ぎくま！　急いで次の世界に向かうくま！」"

[[dialogue]]
speaker = "unk"
# ベア子と黒ベア子は早速、ノルトハウゼンさんを連れて次の世界へ向かおうとする。
line = "ベア子と黒ベア子は早速、ノルトハウゼンさんを連れて次の世界へ向かおうとする。"

[[dialogue]]
speaker = "unk"
# それにフィオナも望んで同行することになった。
line = "それにフィオナも望んで同行することになった。"

[[dialogue]]
speaker = "マハムート"
# 「まったくとんだ騒ぎに巻き込まれてしまったけれど、これでようやくお役御免といったところね」
line = "「まったくとんだ騒ぎに巻き込まれてしまったけれど、これでようやくお役御免といったところね」"

[[dialogue]]
speaker = "マハムート"
# 「後は、いつになるか分からないけれど、ルルゥがゲシュペンス島に無事に戻るのを見届けることくらいかしら」
line = "「後は、いつになるか分からないけれど、ルルゥがゲシュペンス島に無事に戻るのを見届けることくらいかしら」"

[[dialogue]]
speaker = "unk"
# 大丈夫かな？
line = "大丈夫かな？"

[[dialogue]]
speaker = "unk"
# 約束は破らないとは言ってたけど
line = "約束は破らないとは言ってたけど"

[[dialogue]]
speaker = "マハムート"
# 「黒い方はともかく、もう１人の方はそこそこ話の通じる相手だったし、大丈夫だとは思うわ」
line = "「黒い方はともかく、もう１人の方はそこそこ話の通じる相手だったし、大丈夫だとは思うわ」"

[[dialogue]]
speaker = "マハムート"
# 「それに、もしも約束を破るようなことがあれば、どういう目に遭うか……この鉄球で分からせに行くだけよ」
line = "「それに、もしも約束を破るようなことがあれば、どういう目に遭うか……この鉄球で分からせに行くだけよ」"

[[dialogue]]
speaker = "unk"
# 日々のトレーニングを思い出し、なぜか俺の背筋まで寒くなる。
line = "日々のトレーニングを思い出し、なぜか俺の背筋まで寒くなる。"

[[dialogue]]
speaker = "マハムート"
# 「とはいえ、すぐに帰れるという状況では無さそうね」
line = "「とはいえ、すぐに帰れるという状況では無さそうね」"

[[dialogue]]
speaker = "マハムート"
# 「それまでルルゥは私が面倒を見るわ。今日から新星寮の私の部屋で生活なさい」
line = "「それまでルルゥは私が面倒を見るわ。今日から新星寮の私の部屋で生活なさい」"

[[dialogue]]
speaker = "ルルゥ"
# 「マムさんのお部屋に泊めてもらえる、なの……？」
line = "「マムさんのお部屋に泊めてもらえる、なの……？」"

[[dialogue]]
speaker = "unk"
# ルルゥはそれでいい？
line = "ルルゥはそれでいい？"

[[dialogue]]
speaker = "ルルゥ"
# 「嬉しい、なの♪」
line = "「嬉しい、なの♪」"

[[dialogue]]
speaker = "ルルゥ"
# 「マムさんとお別れするのは寂しかった、なの！　ゲシュペンス島に戻るまでの間、ずっとマムさんと一緒にいるの♪」
line = "「マムさんとお別れするのは寂しかった、なの！　ゲシュペンス島に戻るまでの間、ずっとマムさんと一緒にいるの♪」"

[[dialogue]]
speaker = "マハムート"
# 「ふっ、仕方がないわね。少しだけなら甘えさせてあげてもいいわ」
line = "「ふっ、仕方がないわね。少しだけなら甘えさせてあげてもいいわ」"

[[dialogue]]
speaker = "unk"
# 実はルルゥに魅了されてる？
line = "実はルルゥに魅了されてる？"

[[dialogue]]
speaker = "unk"
# マム、もしかして……
line = "マム、もしかして……"

[[dialogue]]
speaker = "マハムート"
# 「私の強靭な精神力を侮ってもらっては困るわね。魅了の力は発動しているようだけど、影響などされていないわ」
line = "「私の強靭な精神力を侮ってもらっては困るわね。魅了の力は発動しているようだけど、影響などされていないわ」"

[[dialogue]]
speaker = "マハムート"
# 「ルルゥは私に畏怖するあまり流星市国まで付いて来てしまったわ。彼女の面倒を見るのは、私にその責任があるからよ。その辺り勘違いしないで頂戴」
line = "「ルルゥは私に畏怖するあまり流星市国まで付いて来てしまったわ。彼女の面倒を見るのは、私にその責任があるからよ。その辺り勘違いしないで頂戴」"

[[dialogue]]
speaker = "unk"
# イ、イエス・マム……
line = "イ、イエス・マム……"

[[dialogue]]
speaker = "マハムート"
# 「ところで──」
line = "「ところで──」"

[[dialogue]]
speaker = "unk"
# （あ……嫌な予感……）
line = "（あ……嫌な予感……）"

[[dialogue]]
speaker = "マハムート"
# 「簡単に魅了の力に惑わされてしまう会長の精神を鍛え直してあげる、そういう約束だったわね」
line = "「簡単に魅了の力に惑わされてしまう会長の精神を鍛え直してあげる、そういう約束だったわね」"

[[dialogue]]
speaker = "マハムート"
# 「寮の門限までまだ時間があるわ。みっちり鍛えてあげるから覚悟しなさい」
line = "「寮の門限までまだ時間があるわ。みっちり鍛えてあげるから覚悟しなさい」"

[[dialogue]]
speaker = "ルルゥ"
# 「これから会長さんの特訓が始まる、なの？」
line = "「これから会長さんの特訓が始まる、なの？」"

[[dialogue]]
speaker = "マハムート"
# 「ええ、あなたにも少し手伝ってもらうわ」
line = "「ええ、あなたにも少し手伝ってもらうわ」"

[[dialogue]]
speaker = "ルルゥ"
# 「わかったなの！　ルルゥ、頑張るの！」
line = "「わかったなの！　ルルゥ、頑張るの！」"

[[dialogue]]
speaker = "unk"
# マムにお願いされて、ルルゥもすっかりやる気になってしまっている。
line = "マムにお願いされて、ルルゥもすっかりやる気になってしまっている。"

[[dialogue]]
speaker = "unk"
# 赤ちゃんクマロボのパパ捜し事件は一旦の幕を引いたようだが、比較にならないほど大きな試練が俺の前に立ちはだかっていたのだった。
line = "赤ちゃんクマロボのパパ捜し事件は一旦の幕を引いたようだが、比較にならないほど大きな試練が俺の前に立ちはだかっていたのだった。"
