[[dialogue]]
speaker = "unk"
# 第１話,蝶の妖精族……？,P
line = "第１話,蝶の妖精族……？,P"

[[dialogue]]
speaker = "unk"
# グレイス・オベロニア──極星学園の星徒会メンバーであり、かつては俺たちアルタイルと敵対していた星騎士だ。
line = "グレイス・オベロニア──極星学園の星徒会メンバーであり、かつては俺たちアルタイルと敵対していた星騎士だ。"

[[dialogue]]
speaker = "unk"
# しかし『デネブの緋宮クロト』に対する誤解は無事に解け、今では協力を申し出てくれる関係にまでになっていた。
line = "しかし『デネブの緋宮クロト』に対する誤解は無事に解け、今では協力を申し出てくれる関係にまでになっていた。"

[[dialogue]]
speaker = "トリュファイナ"
# 「失礼いたします。グレイス様、ご注文のフライドチキンをお届けに参りました」
line = "「失礼いたします。グレイス様、ご注文のフライドチキンをお届けに参りました」"

[[dialogue]]
speaker = "グレイス"
# 「ありがとうございます、トリュファイナさん！」
line = "「ありがとうございます、トリュファイナさん！」"

[[dialogue]]
speaker = "チナ"
# 「グレイスお前、購買部にデリバリーまで頼んでたのか？　アルタイルに馴染みすぎだろ、たった数日で……」
line = "「グレイスお前、購買部にデリバリーまで頼んでたのか？　アルタイルに馴染みすぎだろ、たった数日で……」"

[[dialogue]]
speaker = "グレイス"
# 「共闘すると決めた以上、遠慮をしていては魔王さんたちも居心地が悪いですからね！　もぐもぐ──チナも食べます？」
line = "「共闘すると決めた以上、遠慮をしていては魔王さんたちも居心地が悪いですからね！　もぐもぐ──チナも食べます？」"

[[dialogue]]
speaker = "トリュファイナ"
# 「ふふ。おかわりはたくさんありますからね。ご遠慮なくどうぞ！」
line = "「ふふ。おかわりはたくさんありますからね。ご遠慮なくどうぞ！」"

[[dialogue]]
speaker = "アナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "サーシャ"
# 「あら、どうかしたのアナちゃん。難しい顔をしちゃって」
line = "「あら、どうかしたのアナちゃん。難しい顔をしちゃって」"

[[dialogue]]
speaker = "アナ"
# 「いえ。やはり文献だけで知った気になるのはダメだなと、自戒をしていました」
line = "「いえ。やはり文献だけで知った気になるのはダメだなと、自戒をしていました」"

[[dialogue]]
speaker = "unk"
# ……と言うと？
line = "……と言うと？"

[[dialogue]]
speaker = "アナ"
# 「天界から留学した際、私は図書館で多くの書籍にあたりました」
line = "「天界から留学した際、私は図書館で多くの書籍にあたりました」"

[[dialogue]]
speaker = "アナ"
# 「人間界は数多くの種族がごった返す場所です。特に魔界からの留学生は、広大な土地ゆえに様々な種族の方がいらっしゃいます」
line = "「人間界は数多くの種族がごった返す場所です。特に魔界からの留学生は、広大な土地ゆえに様々な種族の方がいらっしゃいます」"

[[dialogue]]
speaker = "アナ"
# 「知らぬ間に不作法をしないようにと調べている時に、蝶の妖精族についても知る機会がありました」
line = "「知らぬ間に不作法をしないようにと調べている時に、蝶の妖精族についても知る機会がありました」"

[[dialogue]]
speaker = "グレイス"
# 「おぉ！　私の一族のことですね！　そうです、魔界の片隅にある、妖精の森で暮らす一族です！」
line = "「おぉ！　私の一族のことですね！　そうです、魔界の片隅にある、妖精の森で暮らす一族です！」"

[[dialogue]]
speaker = "チナ"
# 「グレイスはかなり珍しい一族って聞いてるけど……よく残ってたな、そんな本」
line = "「グレイスはかなり珍しい一族って聞いてるけど……よく残ってたな、そんな本」"

[[dialogue]]
speaker = "アナ"
# 「アルタイルの図書館の蔵書は並ではありませんので──で、ここからが本題なのですが」
line = "「アルタイルの図書館の蔵書は並ではありませんので──で、ここからが本題なのですが」"

[[dialogue]]
speaker = "アナ"
# 「……私が本で得た妖精族の知識と、グレイスさんのイメージがまったく一致しないんです」
line = "「……私が本で得た妖精族の知識と、グレイスさんのイメージがまったく一致しないんです」"

[[dialogue]]
speaker = "グレイス"
# 「えぇっ？　そんな……その本、本当に信用できるものなんですか？」
line = "「えぇっ？　そんな……その本、本当に信用できるものなんですか？」"

[[dialogue]]
speaker = "アナ"
# 「魔界の人種研究の権威が記したものです。だから私も信頼していたのですが……」
line = "「魔界の人種研究の権威が記したものです。だから私も信頼していたのですが……」"

[[dialogue]]
speaker = "unk"
# 蝶の妖精族は、どんな一族なんだ？
line = "蝶の妖精族は、どんな一族なんだ？"

[[dialogue]]
speaker = "アナ"
# 「『彼らは特徴的な長い耳を持ち、人間に比べてはるかに長命な種族であり──』」
line = "「『彼らは特徴的な長い耳を持ち、人間に比べてはるかに長命な種族であり──』」"

[[dialogue]]
speaker = "グレイス"
# 「合ってますね！　私、お耳が長いです！　人間さんに比べて、長生きですよ！」
line = "「合ってますね！　私、お耳が長いです！　人間さんに比べて、長生きですよ！」"

[[dialogue]]
speaker = "アナ"
# 「『人里離れた静謐な森に住み、小鳥や花と語らい──』」
line = "「『人里離れた静謐な森に住み、小鳥や花と語らい──』」"

[[dialogue]]
speaker = "グレイス"
# 「またまた合ってますね！　故郷の妖精の森は、それはもう豊かな自然がありました！」
line = "「またまた合ってますね！　故郷の妖精の森は、それはもう豊かな自然がありました！」"

[[dialogue]]
speaker = "アナ"
# 「『生まれながらにして高度な知能を持ち、冷静で聡明。幼くして星力に目覚める者も多い。種族の絶対数が少ないためか、逸材ばかりである』」
line = "「『生まれながらにして高度な知能を持ち、冷静で聡明。幼くして星力に目覚める者も多い。種族の絶対数が少ないためか、逸材ばかりである』」"

[[dialogue]]
speaker = "グレイス"
# 「おやおや、ばっちり何もかも合ってるではないですか！　そうです、私はしっかり者です、えっへん！」
line = "「おやおや、ばっちり何もかも合ってるではないですか！　そうです、私はしっかり者です、えっへん！」"

[[dialogue]]
speaker = "チナ"
# 「……そうか？　グレイスって、地頭はいいけど普通にアホの子だぞ」
line = "「……そうか？　グレイスって、地頭はいいけど普通にアホの子だぞ」"

[[dialogue]]
speaker = "グレイス"
# 「そこ！　うるさいですよっ！」
line = "「そこ！　うるさいですよっ！」"

[[dialogue]]
speaker = "アナ"
# 「『人間と同じく雑食であるが、肉食を極端に嫌う。木の実や果実を主に食べ、そして食も細い。出会った際は食文化の違いに注意するべし』」
line = "「『人間と同じく雑食であるが、肉食を極端に嫌う。木の実や果実を主に食べ、そして食も細い。出会った際は食文化の違いに注意するべし』」"

[[dialogue]]
speaker = "unk"
# ……んっ？
line = "……んっ？"

[[dialogue]]
speaker = "チナ"
# 「全然違うじゃねーか。グレイスって野菜が嫌いだろ」
line = "「全然違うじゃねーか。グレイスって野菜が嫌いだろ」"

[[dialogue]]
speaker = "グレイス"
# 「好んで食べたくはないですね……もぐもぐ」
line = "「好んで食べたくはないですね……もぐもぐ」"

[[dialogue]]
speaker = "チナ"
# 「で、肉好きの大食いだ。焼肉はタレにどっぷりつけて、白飯に乗っけて食うし……シメに冷麺とジェラートまで食うんだぜこいつ」
line = "「で、肉好きの大食いだ。焼肉はタレにどっぷりつけて、白飯に乗っけて食うし……シメに冷麺とジェラートまで食うんだぜこいつ」"

[[dialogue]]
speaker = "グレイス"
# 「そ、そんなプライベートなことまで魔王さんの前で言わなくてもいいじゃないですか！？　──もぐもぐ！」
line = "「そ、そんなプライベートなことまで魔王さんの前で言わなくてもいいじゃないですか！？　──もぐもぐ！」"

[[dialogue]]
speaker = "チナ"
# 「さっきからチキン食いながらつっこむんじゃねーよ！？」
line = "「さっきからチキン食いながらつっこむんじゃねーよ！？」"

[[dialogue]]
speaker = "アナ"
# 「『長命ゆえに他種族との交流も積極的ではなく、排他的な傾向があり、気難しい者も多い』……そんな記述があったと記憶しています」
line = "「『長命ゆえに他種族との交流も積極的ではなく、排他的な傾向があり、気難しい者も多い』……そんな記述があったと記憶しています」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら、うふふ♪」
line = "「あらあら、うふふ♪」"

[[dialogue]]
speaker = "チナ"
# 「そんなまさか……グレイスは、もしかして蝶の妖精じゃなかったのかよ……！？」
line = "「そんなまさか……グレイスは、もしかして蝶の妖精じゃなかったのかよ……！？」"

[[dialogue]]
speaker = "グレイス"
# 「合ってますよ！？　蝶の<ruby=はね>翅</ruby>、見せましょうか！？　パタパタですよ私！？」
line = "「合ってますよ！？　蝶の<ruby>翅<rt>はね</rt></ruby>、見せましょうか！？　パタパタですよ私！？」"

[[dialogue]]
speaker = "トリュファイナ"
# 「……私もかつて、魔界を<ruby=たんぼう>探訪</ruby>したことがあります。蝶の妖精族の方とも出会ったことがありますが──」
line = "「……私もかつて、魔界を<ruby>探訪<rt>たんぼう</rt></ruby>したことがあります。蝶の妖精族の方とも出会ったことがありますが──」"

[[dialogue]]
speaker = "グレイス"
# 「おぉ、そうだったのですか！？　では訂正をお願いしますトリュファイナさんっ！」
line = "「おぉ、そうだったのですか！？　では訂正をお願いしますトリュファイナさんっ！」"

[[dialogue]]
speaker = "トリュファイナ"
# 「……アナ様の読んだ図書の記述が、た、正しいかと」
line = "「……アナ様の読んだ図書の記述が、た、正しいかと」"

[[dialogue]]
speaker = "グレイス"
# 「そんなぁあ～っ！？」
line = "「そんなぁあ～っ！？」"

[[dialogue]]
speaker = "グレイス"
# 「……た、確かに私はちょっぴり変わった妖精族かもしれませんが！　ほ、ほらチナ。フォローしてください、親友でしょう！？」
line = "「……た、確かに私はちょっぴり変わった妖精族かもしれませんが！　ほ、ほらチナ。フォローしてください、親友でしょう！？」"

[[dialogue]]
speaker = "チナ"
# 「フォローっつったって……」
line = "「フォローっつったって……」"

[[dialogue]]
speaker = "グレイス"
# 「私がいかに聡明で有能な星騎士であるかを語ってください！」
line = "「私がいかに聡明で有能な星騎士であるかを語ってください！」"

[[dialogue]]
speaker = "グレイス"
# 「そ、そうです、就任してから会計の仕事っ。計算間違いなんて一度もしたことないはずですよ！？」
line = "「そ、そうです、就任してから会計の仕事っ。計算間違いなんて一度もしたことないはずですよ！？」"

[[dialogue]]
speaker = "unk"
# グレイスって会計なんだ……？（戦慄）
line = "グレイスって会計なんだ……？（戦慄）"

[[dialogue]]
speaker = "グレイス"
# 「何ですかその反応は！？」
line = "「何ですかその反応は！？」"

[[dialogue]]
speaker = "チナ"
# 「確かに計算間違いはないな。でもよくレシート失くすし……」
line = "「確かに計算間違いはないな。でもよくレシート失くすし……」"

[[dialogue]]
speaker = "グレイス"
# 「しまった！？　今のは無しですっ！」
line = "「しまった！？　今のは無しですっ！」"

[[dialogue]]
speaker = "グレイス"
# 「じゃ、じゃあ……そうです、ちょっと前に！　デネブでモンスターに襲われていた子供を救出したことが……！」
line = "「じゃ、じゃあ……そうです、ちょっと前に！　デネブでモンスターに襲われていた子供を救出したことが……！」"

[[dialogue]]
speaker = "チナ"
# 「ああ、あれか──確かにお前が一番乗りで解決したよな」
line = "「ああ、あれか──確かにお前が一番乗りで解決したよな」"

[[dialogue]]
speaker = "チナ"
# 「でもあれ、授業中のモンスター出現だったろ。お前、休校日だと勘違いして街で遊んでて、だから現場に近くて──」
line = "「でもあれ、授業中のモンスター出現だったろ。お前、休校日だと勘違いして街で遊んでて、だから現場に近くて──」"

[[dialogue]]
speaker = "グレイス"
# 「ああぁぁっ！？　思い出しました！　今のも無し、無しですッ！！」
line = "「ああぁぁっ！？　思い出しました！　今のも無し、無しですッ！！」"

[[dialogue]]
speaker = "unk"
# その後も、チナの口から語られるのは、グレイスのうっかりエピソードばっかりで。
line = "その後も、チナの口から語られるのは、グレイスのうっかりエピソードばっかりで。"

[[dialogue]]
speaker = "グレイス"
# 「し、信じてください！　私はしっかり者の、蝶の妖精なんです～っ！！」
line = "「し、信じてください！　私はしっかり者の、蝶の妖精なんです～っ！！」"

[[dialogue]]
speaker = "unk"
# 本だけの知識で全てを知った気になるのはいけないなと、俺も思うのだった──
line = "本だけの知識で全てを知った気になるのはいけないなと、俺も思うのだった──"
