[[dialogue]]
speaker = "unk"
# 第３話,催眠ゴッデスビーム,P
line = "第３話,催眠ゴッデスビーム,P"

[[dialogue]]
speaker = "unk"
# この日、俺たち新星星徒会のメンバーで、仮想結界内での戦闘訓練を行っていた。
line = "この日、俺たち新星星徒会のメンバーで、仮想結界内での戦闘訓練を行っていた。"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「よ～し、それじゃあ行くわよ、パパ！」
line = "「よ～し、それじゃあ行くわよ、パパ！」"

[[dialogue]]
speaker = "unk"
# よし、バッチコイ！
line = "よし、バッチコイ！"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「１０連ゴッデスビーム！」
line = "「１０連ゴッデスビーム！」"

[[dialogue]]
speaker = "unk"
# リトルフォームのヴィーナスが放つ連射ビームを、俺は最小限の動きを心がけながら体を横に逸らし、受け流すように回避する。
line = "リトルフォームのヴィーナスが放つ連射ビームを、俺は最小限の動きを心がけながら体を横に逸らし、受け流すように回避する。"

[[dialogue]]
speaker = "マトイ"
# 「ひゃ～っ、すごい連射速度……！　しかも１発１発が直撃したら戦闘不能になりそうな威力！」
line = "「ひゃ～っ、すごい連射速度……！　しかも１発１発が直撃したら戦闘不能になりそうな威力！」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「えへへっ♪　リトルフォームで武器が『ビーム銃』になったから、前より色んな種類のビームが撃てるようになったのよ♪」
line = "「えへへっ♪　リトルフォームで武器が『ビーム銃』になったから、前より色んな種類のビームが撃てるようになったのよ♪」"

[[dialogue]]
speaker = "アナ"
# 「ふむ……それって、攻撃技ではないビームもあったりするのでしょうか？」
line = "「ふむ……それって、攻撃技ではないビームもあったりするのでしょうか？」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「あるわ！　ただ、私にも効果がよくわからない、変なビームもあったりするのよね」
line = "「あるわ！　ただ、私にも効果がよくわからない、変なビームもあったりするのよね」"

[[dialogue]]
speaker = "マトイ"
# 「変なビーム？」
line = "「変なビーム？」"

[[dialogue]]
speaker = "サーシャ"
# 「あら～、それは面白そうね～♪」
line = "「あら～、それは面白そうね～♪」"

[[dialogue]]
speaker = "アナ"
# 「戦闘訓練ですし、私も興味があります。せっかくですからこの場で試してみましょう」
line = "「戦闘訓練ですし、私も興味があります。せっかくですからこの場で試してみましょう」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「そうね！　アナに見てもらったら、どういう効果かわかるかも♪」
line = "「そうね！　アナに見てもらったら、どういう効果かわかるかも♪」"

[[dialogue]]
speaker = "unk"
# そうして、俺が相手になって、ヴィーナスの言う『変なビーム』を試してみることになったのだが……
line = "そうして、俺が相手になって、ヴィーナスの言う『変なビーム』を試してみることになったのだが……"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「あれ？　パパ、大丈夫？」
line = "「あれ？　パパ、大丈夫？」"

[[dialogue]]
speaker = "サーシャ"
# 「防御した会長くん、なんだか寝ぼけちゃってるような顔をしてるわね～？」
line = "「防御した会長くん、なんだか寝ぼけちゃってるような顔をしてるわね～？」"

[[dialogue]]
speaker = "アナ"
# 「ふむ、この状態は……」
line = "「ふむ、この状態は……」"

[[dialogue]]
speaker = "unk"
# お姉ちゃんたち、誰……？
line = "お姉ちゃんたち、誰……？"

[[dialogue]]
speaker = "マトイ"
# 「えぇええぇ……！？」
line = "「えぇええぇ……！？」"

[[dialogue]]
speaker = "unk"
# それから、星徒会メンバーがクロトの様子を調べた結果。
line = "それから、星徒会メンバーがクロトの様子を調べた結果。"

[[dialogue]]
speaker = "マトイ"
# 「もしかして会長、精神が幼くなっちゃってるーーーっ！？」
line = "「もしかして会長、精神が幼くなっちゃってるーーーっ！？」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「それって、前に私がなった時と同じような状態ってこと？」
line = "「それって、前に私がなった時と同じような状態ってこと？」"

[[dialogue]]
speaker = "アナ"
# 「会長は先程ビームを防御しましたが、その効果は防げなかった。……精神に作用するこれは、いわゆる相手を『催眠』状態にするビームだと考えられます」
line = "「会長は先程ビームを防御しましたが、その効果は防げなかった。……精神に作用するこれは、いわゆる相手を『催眠』状態にするビームだと考えられます」"

[[dialogue]]
speaker = "マトイ"
# 「それが本当なら、普通じゃないよ！？」
line = "「それが本当なら、普通じゃないよ！？」"

[[dialogue]]
speaker = "サーシャ"
# 「そ、そんな……会長くんが……！」
line = "「そ、そんな……会長くんが……！」"

[[dialogue]]
speaker = "サーシャ"
# 「精神状態が『弟くん』になっちゃってるなんて、お姉ちゃん、すごくキュンキュンしちゃうわ～～っ<emoji=heart04><emoji=heart04>」
line = "「精神状態が『弟くん』になっちゃってるなんて、お姉ちゃん、すごくキュンキュンしちゃうわ～～っ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "マトイ"
# 「いやサーシャさん、『弟』になってるわけじゃないですからね！？」
line = "「いやサーシャさん、『弟』になってるわけじゃないですからね！？」"

[[dialogue]]
speaker = "アナ"
# 「多分、興奮して聞こえてないと思われます……」
line = "「多分、興奮して聞こえてないと思われます……」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「とりあえずわかったわ！　ビームの効果が切れてパパが元に戻るまで、安心させてあげないといけないってことね！」
line = "「とりあえずわかったわ！　ビームの効果が切れてパパが元に戻るまで、安心させてあげないといけないってことね！」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「パパ、何も心配しなくて大丈夫よ！　私は九浄ヴィーナス！　パパの娘で、恋人よ♪」
line = "「パパ、何も心配しなくて大丈夫よ！　私は九浄ヴィーナス！　パパの娘で、恋人よ♪」"

[[dialogue]]
speaker = "unk"
# パパで？　娘で？　恋人？？？
line = "パパで？　娘で？　恋人？？？"

[[dialogue]]
speaker = "マトイ"
# 「うん、普通は意味わからなくて混乱するよね！」
line = "「うん、普通は意味わからなくて混乱するよね！」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「それなら、こうすればいいわ！　パパがいつもやってくれてるみたいに、こうして――」
line = "「それなら、こうすればいいわ！　パパがいつもやってくれてるみたいに、こうして――」"

[[dialogue]]
speaker = "unk"
# ヴィーナスはクロトの頭を優しく撫でる。
line = "ヴィーナスはクロトの頭を優しく撫でる。"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「なで、なで♪　……どう？　安心するかしら？」
line = "「なで、なで♪　……どう？　安心するかしら？」"

[[dialogue]]
speaker = "unk"
# クロトは頷いてから、微笑んで言う。
line = "クロトは頷いてから、微笑んで言う。"

[[dialogue]]
speaker = "unk"
# うん。ありがとう、ヴィーナスお姉ちゃん♪
line = "うん。ありがとう、ヴィーナスお姉ちゃん♪"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「っ！？　な、なんか今、胸がビームに撃ち抜かれたみたいに、すごくズキュ～ンってなったわ！」
line = "「っ！？　な、なんか今、胸がビームに撃ち抜かれたみたいに、すごくズキュ～ンってなったわ！」"

[[dialogue]]
speaker = "サーシャ"
# 「ヴィーナスちゃん……それが『弟萌え』よ！」
line = "「ヴィーナスちゃん……それが『弟萌え』よ！」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「弟萌え……！？」
line = "「弟萌え……！？」"

[[dialogue]]
speaker = "サーシャ"
# 「さあ、今の可愛すぎる会長くんを一緒に甘やかしてあげましょう♪　会長くん、サーシャお姉ちゃんよ～♪　ぎゅ～っ<emoji=heart04>」
line = "「さあ、今の可愛すぎる会長くんを一緒に甘やかしてあげましょう♪　会長くん、サーシャお姉ちゃんよ～♪　ぎゅ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「あっ、サーシャさん、ずるいわよ！　パパは私の彼氏なんだから！　ぎゅ～っ<emoji=heart04>」
line = "「あっ、サーシャさん、ずるいわよ！　パパは私の彼氏なんだから！　ぎゅ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# お、お姉ちゃんたち、恥ずかしいよ……
line = "お、お姉ちゃんたち、恥ずかしいよ……"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「～～っ<emoji=heart04>　パパ、可愛いわっ<emoji=heart04>　ん～っ、頭なでなで～<emoji=heart04>」
line = "「～～っ<emoji=heart04>　パパ、可愛いわっ<emoji=heart04>　ん～っ、頭なでなで～<emoji=heart04>」"

[[dialogue]]
speaker = "マトイ"
# 「ご、ごくり……わ、私もちょっと、試しに会長を撫でてみようかな……？　そ、その方が会長も安心すると思うし……<emoji=heart04>」
line = "「ご、ごくり……わ、私もちょっと、試しに会長を撫でてみようかな……？　そ、その方が会長も安心すると思うし……<emoji=heart04>」"

[[dialogue]]
speaker = "アナ"
# 「そ、そうですね……私たちが会長の味方であるということを伝えておくのは大事。なので、私も……<emoji=heart04>」
line = "「そ、そうですね……私たちが会長の味方であるということを伝えておくのは大事。なので、私も……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 星徒会の面々はそれからも、みんなでクロトのことを撫でて、可愛がり続けるのだった。
line = "星徒会の面々はそれからも、みんなでクロトのことを撫でて、可愛がり続けるのだった。"

[[dialogue]]
speaker = "unk"
# ――気づくと、俺は星徒会のみんなの腕の中にいた。
line = "――気づくと、俺は星徒会のみんなの腕の中にいた。"

[[dialogue]]
speaker = "unk"
# はっ！？　俺は一体……！？
line = "はっ！？　俺は一体……！？"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「あっ！　パパ、元に戻ったのね♪」
line = "「あっ！　パパ、元に戻ったのね♪」"

[[dialogue]]
speaker = "アナ"
# 「コホン……とりあえず、さっきのビームはむやみに使わないよう気を付けましょう……」
line = "「コホン……とりあえず、さっきのビームはむやみに使わないよう気を付けましょう……」"

[[dialogue]]
speaker = "マトイ"
# 「そ、そうだね……あははは……」
line = "「そ、そうだね……あははは……」"

[[dialogue]]
speaker = "サーシャ"
# 「あら～、私はまた会長くんの可愛い姿が見てみたいけど～<emoji=heart04>」
line = "「あら～、私はまた会長くんの可愛い姿が見てみたいけど～<emoji=heart04>」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「名づけて、『催眠ゴッデスビーム』ね！」
line = "「名づけて、『催眠ゴッデスビーム』ね！」"

[[dialogue]]
speaker = "unk"
# ん？　待って！　催眠ってどういうこと！？
line = "ん？　待って！　催眠ってどういうこと！？"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「これからはたまに、私のことを『お姉ちゃん』って呼んでくれてもいいわよ、パ～パ<emoji=heart04>　ふふふっ♪」
line = "「これからはたまに、私のことを『お姉ちゃん』って呼んでくれてもいいわよ、パ～パ<emoji=heart04>　ふふふっ♪」"

[[dialogue]]
speaker = "unk"
# ヴィーナスはそう言って、満足げに笑ってみせるのであった。
line = "ヴィーナスはそう言って、満足げに笑ってみせるのであった。"
