[[dialogue]]
speaker = "unk"
# 第１話,煌嶺陛下の懐刀,P
line = "第１話,煌嶺陛下の懐刀,P"

[[dialogue]]
speaker = "リーエン"
# 「どうした、怖じ気づいたか、魔王！」
line = "「どうした、怖じ気づいたか、魔王！」"

[[dialogue]]
speaker = "unk"
# 放課後のアリーナで、俺はリーエンと対峙していた。
line = "放課後のアリーナで、俺はリーエンと対峙していた。"

[[dialogue]]
speaker = "リーエン"
# 「おまえが来ないなら、こちらから往くぞ！」
line = "「おまえが来ないなら、こちらから往くぞ！」"

[[dialogue]]
speaker = "リーエン"
# 「破ァァーーーーーッ！」
line = "「破ァァーーーーーッ！」"

[[dialogue]]
speaker = "マトイ"
# 「ま、待ってください！　まだ開始の合図は出てませんよ！」
line = "「ま、待ってください！　まだ開始の合図は出てませんよ！」"

[[dialogue]]
speaker = "リーエン"
# 「フン、命拾いしたな」
line = "「フン、命拾いしたな」"

[[dialogue]]
speaker = "マトイ"
# 「よかったぁ……もう、なんでこんなに血の気が多いの……」
line = "「よかったぁ……もう、なんでこんなに血の気が多いの……」"

[[dialogue]]
speaker = "リーエン"
# 「おい！　聞こえているぞ！」
line = "「おい！　聞こえているぞ！」"

[[dialogue]]
speaker = "マトイ"
# 「ひゃあ！　すす、すみません。ごめんなさい」
line = "「ひゃあ！　すす、すみません。ごめんなさい」"

[[dialogue]]
speaker = "リーエン"
# 「謝る必要はない。戦士たるもの、血の気が多いのは誇るべきことだからな」
line = "「謝る必要はない。戦士たるもの、血の気が多いのは誇るべきことだからな」"

[[dialogue]]
speaker = "マトイ"
# 「そ、そういうものなんだ……」
line = "「そ、そういうものなんだ……」"

[[dialogue]]
speaker = "unk"
# 戦闘民族すぎる
line = "戦闘民族すぎる"

[[dialogue]]
speaker = "リーエン"
# 「そうだな、賞賛の言葉と受け取っておくぞ、魔王」
line = "「そうだな、賞賛の言葉と受け取っておくぞ、魔王」"

[[dialogue]]
speaker = "リーエン"
# 「それより早く合図を出せ！　あたしの刃は魔王の血に飢えてるからな！」
line = "「それより早く合図を出せ！　あたしの刃は魔王の血に飢えてるからな！」"

[[dialogue]]
speaker = "マトイ"
# 「ひえぇぇ～～」
line = "「ひえぇぇ～～」"

[[dialogue]]
speaker = "unk"
# いったいどうしてこうなった？
line = "いったいどうしてこうなった？"

[[dialogue]]
speaker = "unk"
# 事の発端は少し前に遡る。
line = "事の発端は少し前に遡る。"

[[dialogue]]
speaker = "リーエン"
# 「たのもう！」
line = "「たのもう！」"

[[dialogue]]
speaker = "リーエン"
# 「魔王はいるか！　魔界の皇妃・煌嶺陛下に仕えるリーエンだ！」
line = "「魔王はいるか！　魔界の皇妃・煌嶺陛下に仕えるリーエンだ！」"

[[dialogue]]
speaker = "リーエン"
# 「魔王がどれほどの武を誇るか、このあたしが直々に確かめさせてもらおう！」
line = "「魔王がどれほどの武を誇るか、このあたしが直々に確かめさせてもらおう！」"

[[dialogue]]
speaker = "リーエン"
# 「いざ尋常に、勝負！！」
line = "「いざ尋常に、勝負！！」"

[[dialogue]]
speaker = "unk"
# さすがに星徒会室で戦うわけにもいかず、アリーナを貸切にしてリーエンと模擬戦をすることになった、という流れだ。
line = "さすがに星徒会室で戦うわけにもいかず、アリーナを貸切にしてリーエンと模擬戦をすることになった、という流れだ。"

[[dialogue]]
speaker = "unk"
# ごめん、立ち会いをお願いしちゃって
line = "ごめん、立ち会いをお願いしちゃって"

[[dialogue]]
speaker = "マトイ"
# 「気にしないで。会長たちだけにしたら、何が起こるか心配だもんね」
line = "「気にしないで。会長たちだけにしたら、何が起こるか心配だもんね」"

[[dialogue]]
speaker = "リーエン"
# 「こそこそと作戦会議か？　どんな策を弄しようと、あたしが噛み破ってやる」
line = "「こそこそと作戦会議か？　どんな策を弄しようと、あたしが噛み破ってやる」"

[[dialogue]]
speaker = "リーエン"
# 「それとも２人がかりで来るか？　あたしはそれでも一向に構わんぞ！」
line = "「それとも２人がかりで来るか？　あたしはそれでも一向に構わんぞ！」"

[[dialogue]]
speaker = "マトイ"
# 「うわぁ、やる気満々だね。会長、ほんとに大丈夫？　私も参加した方がいいかな？」
line = "「うわぁ、やる気満々だね。会長、ほんとに大丈夫？　私も参加した方がいいかな？」"

[[dialogue]]
speaker = "unk"
# １人でやるよ、正々堂々とね
line = "１人でやるよ、正々堂々とね"

[[dialogue]]
speaker = "リーエン"
# 「ほぉ……殊勝なことを言う。その心意気だけは買ってやろう」
line = "「ほぉ……殊勝なことを言う。その心意気だけは買ってやろう」"

[[dialogue]]
speaker = "リーエン"
# 「より楽しみになって来たぞ。さあ来い、魔王！」
line = "「より楽しみになって来たぞ。さあ来い、魔王！」"

[[dialogue]]
speaker = "マトイ"
# 「そ、それでは、模擬戦開始！」
line = "「そ、それでは、模擬戦開始！」"

[[dialogue]]
speaker = "リーエン"
# 「破ッ！」
line = "「破ッ！」"

[[dialogue]]
speaker = "unk"
# は、速いっ！？
line = "は、速いっ！？"

[[dialogue]]
speaker = "リーエン"
# 「そらそらそらァッ！　あたしはまだまだこんなものじゃないぞ！」
line = "「そらそらそらァッ！　あたしはまだまだこんなものじゃないぞ！」"

[[dialogue]]
speaker = "マトイ"
# 「え？　もっと速度が上がるの？」
line = "「え？　もっと速度が上がるの？」"

[[dialogue]]
speaker = "リーエン"
# 「まずは一閃！　はぁぁぁぁっ！！」
line = "「まずは一閃！　はぁぁぁぁっ！！」"

[[dialogue]]
speaker = "マトイ"
# 「やった！　相殺した！」
line = "「やった！　相殺した！」"

[[dialogue]]
speaker = "リーエン"
# 「フッ、さすがは魔王。そう容易くは折れぬか」
line = "「フッ、さすがは魔王。そう容易くは折れぬか」"

[[dialogue]]
speaker = "マトイ"
# 「会長、頑張って！　相手の動きをよく見て！」
line = "「会長、頑張って！　相手の動きをよく見て！」"

[[dialogue]]
speaker = "リーエン"
# 「おまえには友がいるが、このあたしには陛下がいる！」
line = "「おまえには友がいるが、このあたしには陛下がいる！」"

[[dialogue]]
speaker = "リーエン"
# 「煌嶺陛下の懐刀として、魔王に後れを取るわけにはいかない！！」
line = "「煌嶺陛下の懐刀として、魔王に後れを取るわけにはいかない！！」"

[[dialogue]]
speaker = "リーエン"
# 「戦いは始まったばかりだ！　さあ、往くぞ！！」
line = "「戦いは始まったばかりだ！　さあ、往くぞ！！」"

[[dialogue]]
speaker = "リーエン"
# 「はぁ……はぁ……はぁ……しぶといやつめ、あたしの攻撃をここまで凌ぎきるとはな……」
line = "「はぁ……はぁ……はぁ……しぶといやつめ、あたしの攻撃をここまで凌ぎきるとはな……」"

[[dialogue]]
speaker = "unk"
# リーエンも、想像以上に強かった
line = "リーエンも、想像以上に強かった"

[[dialogue]]
speaker = "リーエン"
# 「フンッ、つまりこのあたしを舐めてかかっていたということか？」
line = "「フンッ、つまりこのあたしを舐めてかかっていたということか？」"

[[dialogue]]
speaker = "リーエン"
# 「いいだろう、あたしはまだ戦える。このまま死力を尽くして勝敗を決しようではないか！」
line = "「いいだろう、あたしはまだ戦える。このまま死力を尽くして勝敗を決しようではないか！」"

[[dialogue]]
speaker = "マトイ"
# 「待って待って！　アリーナの利用時間が終わっちゃうから、ここでおしまいにしよう？」
line = "「待って待って！　アリーナの利用時間が終わっちゃうから、ここでおしまいにしよう？」"

[[dialogue]]
speaker = "リーエン"
# 「時間切れか……」
line = "「時間切れか……」"

[[dialogue]]
speaker = "リーエン"
# 「このまま戦い続ければ、絶対にあたしが勝つのに……」
line = "「このまま戦い続ければ、絶対にあたしが勝つのに……」"

[[dialogue]]
speaker = "リーエン"
# 「まあいい、魔王の力量は確認できた。陛下にも良い報告ができる」
line = "「まあいい、魔王の力量は確認できた。陛下にも良い報告ができる」"

[[dialogue]]
speaker = "リーエン"
# 「今回は引き分けで勘弁してやろう。だが、次は絶対にあたしが勝つ！」
line = "「今回は引き分けで勘弁してやろう。だが、次は絶対にあたしが勝つ！」"

[[dialogue]]
speaker = "マトイ"
# 「え？　次があるの？」
line = "「え？　次があるの？」"

[[dialogue]]
speaker = "リーエン"
# 「当然だ。どうせ魔王も本気を見せていないのだろう？」
line = "「当然だ。どうせ魔王も本気を見せていないのだろう？」"

[[dialogue]]
speaker = "unk"
# それはどうかな？
line = "それはどうかな？"

[[dialogue]]
speaker = "リーエン"
# 「フンッ」
line = "「フンッ」"

[[dialogue]]
speaker = "マトイ"
# 「そうだ、リーエンさんもノヴァフォーム使わなかったよね？」
line = "「そうだ、リーエンさんもノヴァフォーム使わなかったよね？」"

[[dialogue]]
speaker = "リーエン"
# 「必要があれば使う。だが、今の魔王にはその必要もないと判断したまでのこと」
line = "「必要があれば使う。だが、今の魔王にはその必要もないと判断したまでのこと」"

[[dialogue]]
speaker = "リーエン"
# 「あたしは武人だからな。正々堂々、相手の全力を受け止め、叩き伏せるのみだ！」
line = "「あたしは武人だからな。正々堂々、相手の全力を受け止め、叩き伏せるのみだ！」"

[[dialogue]]
speaker = "リーエン"
# 「よき戦いだったぞ、魔王！　あたしも存分に楽しませてもらった！」
line = "「よき戦いだったぞ、魔王！　あたしも存分に楽しませてもらった！」"

[[dialogue]]
speaker = "リーエン"
# 「次は、あたしが勝つ！　ではさらばだ！」
line = "「次は、あたしが勝つ！　ではさらばだ！」"

[[dialogue]]
speaker = "unk"
# こうして、リーエンは事あるごとに模擬戦を挑んでくるようになった。
line = "こうして、リーエンは事あるごとに模擬戦を挑んでくるようになった。"
