[[dialogue]]
speaker = "unk"
# 第１話,あなたの傍で,P
line = "第１話,あなたの傍で,P"

[[dialogue]]
speaker = "unk"
# 『ＸＥＬＯＳ』との決戦から少し経ち、学園には日常が戻りつつあった。
line = "『ＸＥＬＯＳ』との決戦から少し経ち、学園には日常が戻りつつあった。"

[[dialogue]]
speaker = "unk"
# 放課後の星徒会室に、いつかのようにノックが響く。
line = "放課後の星徒会室に、いつかのようにノックが響く。"

[[dialogue]]
speaker = "レイラ"
# 「失礼します」
line = "「失礼します」"

[[dialogue]]
speaker = "レイラ"
# 「っ！　魔王さんっ！」
line = "「っ！　魔王さんっ！」"

[[dialogue]]
speaker = "unk"
# レイラにいきなり抱き締められた。柔らかい感触が、匂いが、俺を包む。
line = "レイラにいきなり抱き締められた。柔らかい感触が、匂いが、俺を包む。"

[[dialogue]]
speaker = "unk"
# ……レイラ？
line = "……レイラ？"

[[dialogue]]
speaker = "レイラ"
# 「ごめんなさい。こんなことするために来たんじゃないのに」
line = "「ごめんなさい。こんなことするために来たんじゃないのに」"

[[dialogue]]
speaker = "レイラ"
# 「でも魔王さんの顔を見たら、いてもたってもいられなくて……本当に、本当に無事でよかった」
line = "「でも魔王さんの顔を見たら、いてもたってもいられなくて……本当に、本当に無事でよかった」"

[[dialogue]]
speaker = "レイラ"
# 「ずっと、あなたの傍にいたかった。でも叶わなくて……だから、今だけは魔王さんを感じさせてください」
line = "「ずっと、あなたの傍にいたかった。でも叶わなくて……だから、今だけは魔王さんを感じさせてください」"

[[dialogue]]
speaker = "unk"
# 俺を抱き締める腕の力が強くなる。それに応えようと、俺もレイラを抱き締める。
line = "俺を抱き締める腕の力が強くなる。それに応えようと、俺もレイラを抱き締める。"

[[dialogue]]
speaker = "レイラ"
# 「魔王さん……」
line = "「魔王さん……」"

[[dialogue]]
speaker = "unk"
# レイラが目をつむる。そして、お互いの唇が近付いて──
line = "レイラが目をつむる。そして、お互いの唇が近付いて──"

[[dialogue]]
speaker = "コハルコ"
# 「あのー……」
line = "「あのー……」"

[[dialogue]]
speaker = "レイラ"
# 「アイエエエェェッ！？」
line = "「アイエエエェェッ！？」"

[[dialogue]]
speaker = "レイラ"
# 「コハルコさんナンデェ！？　いつからそこに！？」
line = "「コハルコさんナンデェ！？　いつからそこに！？」"

[[dialogue]]
speaker = "コハルコ"
# 「いや、最初からいたよ。書類の提出で来てたんだけど、会長さんも途中から忘れてたでしょ」
line = "「いや、最初からいたよ。書類の提出で来てたんだけど、会長さんも途中から忘れてたでしょ」"

[[dialogue]]
speaker = "レイラ"
# 「はぁはぁ……今世紀最大にビックリした……心臓ないなった……」
line = "「はぁはぁ……今世紀最大にビックリした……心臓ないなった……」"

[[dialogue]]
speaker = "コハルコ"
# 「目の前で当然のように２人の世界に突入するし、私もびっくりしたよ。会長さんとレイラってそういう関係だったんだ？」
line = "「目の前で当然のように２人の世界に突入するし、私もびっくりしたよ。会長さんとレイラってそういう関係だったんだ？」"

[[dialogue]]
speaker = "レイラ"
# 「えっと、それは、その……以前からこっそり、２人でお出かけとかしてます……」
line = "「えっと、それは、その……以前からこっそり、２人でお出かけとかしてます……」"

[[dialogue]]
speaker = "コハルコ"
# 「ふ～ん。そっかそっか。でも意外だな。レイラ、リアルの男の子とか興味あったんだなって」
line = "「ふ～ん。そっかそっか。でも意外だな。レイラ、リアルの男の子とか興味あったんだなって」"

[[dialogue]]
speaker = "レイラ"
# 「え～。それ、コハルコさんが言います？　コハルコさんこそ架空の触手やらにご執心なのでは……」
line = "「え～。それ、コハルコさんが言います？　コハルコさんこそ架空の触手やらにご執心なのでは……」"

[[dialogue]]
speaker = "コハルコ"
# 「レイラ。それ以上言ったら体育館裏に来てもらうからね？」
line = "「レイラ。それ以上言ったら体育館裏に来てもらうからね？」"

[[dialogue]]
speaker = "レイラ"
# 「ずみまぜん！　失礼しましたぁ！」
line = "「ずみまぜん！　失礼しましたぁ！」"

[[dialogue]]
speaker = "コハルコ"
# 「それにしても会長さんとレイラが付き合ってるなんてね。命のやり取りした相手なのに……まぁ私もレイラと仲良くしてるし、今更かな」
line = "「それにしても会長さんとレイラが付き合ってるなんてね。命のやり取りした相手なのに……まぁ私もレイラと仲良くしてるし、今更かな」"

[[dialogue]]
speaker = "レイラ"
# 「お付き合いしているわけでは……私が一方的にお慕いしてるというか……」
line = "「お付き合いしているわけでは……私が一方的にお慕いしてるというか……」"

[[dialogue]]
speaker = "コハルコ"
# 「キスする３秒前でそれは無理があるって。逆にこれで付き合ってなかったら会長さんがだらしなさすぎる」
line = "「キスする３秒前でそれは無理があるって。逆にこれで付き合ってなかったら会長さんがだらしなさすぎる」"

[[dialogue]]
speaker = "レイラ"
# 「でも私はコラプサーで、星騎士のみなさんを傷付けた身です。異性と交際なんて不謹慎ではないでしょうか」
line = "「でも私はコラプサーで、星騎士のみなさんを傷付けた身です。異性と交際なんて不謹慎ではないでしょうか」"

[[dialogue]]
speaker = "レイラ"
# 「ましてや、魔王さんは星騎士を束ねる星徒会長です。私とお付き合いなんてことになったら、魔王さんにも累が及ぶのではないかと心配なんです」
line = "「ましてや、魔王さんは星騎士を束ねる星徒会長です。私とお付き合いなんてことになったら、魔王さんにも累が及ぶのではないかと心配なんです」"

[[dialogue]]
speaker = "コハルコ"
# 「それこそ今更だと思うけどなぁ。でも、レイラは会長さんのこと好きなんでしょ？」
line = "「それこそ今更だと思うけどなぁ。でも、レイラは会長さんのこと好きなんでしょ？」"

[[dialogue]]
speaker = "レイラ"
# 「はい。この気持ちに偽りはありません」
line = "「はい。この気持ちに偽りはありません」"

[[dialogue]]
speaker = "コハルコ"
# 「会長さんは？」
line = "「会長さんは？」"

[[dialogue]]
speaker = "unk"
# 俺もレイラが好きです
line = "俺もレイラが好きです"

[[dialogue]]
speaker = "コハルコ"
# 「うん。じゃあ何も問題ないね。付き合っちゃえ付き合っちゃえ」
line = "「うん。じゃあ何も問題ないね。付き合っちゃえ付き合っちゃえ」"

[[dialogue]]
speaker = "レイラ"
# 「でも……」
line = "「でも……」"

[[dialogue]]
speaker = "コハルコ"
# 「レイラ、おいで」
line = "「レイラ、おいで」"

[[dialogue]]
speaker = "レイラ"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "unk"
# コハルコさんがレイラを抱き締め、頭をなでる。まるで姉が妹にそうするように。
line = "コハルコさんがレイラを抱き締め、頭をなでる。まるで姉が妹にそうするように。"

[[dialogue]]
speaker = "レイラ"
# 「コハルコさん？」
line = "「コハルコさん？」"

[[dialogue]]
speaker = "コハルコ"
# 「レイラやコラプサーのみんながいろんなところで戦ってきたの、私は知ってるよ。もうあなたたちは星騎士の敵じゃない。私が保証する」
line = "「レイラやコラプサーのみんながいろんなところで戦ってきたの、私は知ってるよ。もうあなたたちは星騎士の敵じゃない。私が保証する」"

[[dialogue]]
speaker = "コハルコ"
# 「レイラこそ、無事に帰ってきてくれてよかった。おかえり」
line = "「レイラこそ、無事に帰ってきてくれてよかった。おかえり」"

[[dialogue]]
speaker = "レイラ"
# 「……いつもご心配おかけしてます」
line = "「……いつもご心配おかけしてます」"

[[dialogue]]
speaker = "コハルコ"
# 「もう、本当だよ。……誰かに何か言われても大丈夫、私は味方だから。レイラは幸せになっていいんだよ」
line = "「もう、本当だよ。……誰かに何か言われても大丈夫、私は味方だから。レイラは幸せになっていいんだよ」"

[[dialogue]]
speaker = "レイラ"
# 「コハルコさん。……はい、ありがとうございます」
line = "「コハルコさん。……はい、ありがとうございます」"

[[dialogue]]
speaker = "コハルコ"
# 「会長さんも、付き合うんだったらちゃんと彼女を守ってあげないとダメだよ。私の友達、泣かせたら怒るからね」
line = "「会長さんも、付き合うんだったらちゃんと彼女を守ってあげないとダメだよ。私の友達、泣かせたら怒るからね」"

[[dialogue]]
speaker = "コハルコ"
# 「書類は机に置いとくから、後で読んでおいて。じゃ、お邪魔虫は退散するよ」
line = "「書類は机に置いとくから、後で読んでおいて。じゃ、お邪魔虫は退散するよ」"

[[dialogue]]
speaker = "レイラ"
# 「コハルコさん、行っちゃいましたね……」
line = "「コハルコさん、行っちゃいましたね……」"

[[dialogue]]
speaker = "レイラ"
# 「私、本当に魔王さんとお付き合いしてもいいんでしょうか……？」
line = "「私、本当に魔王さんとお付き合いしてもいいんでしょうか……？」"

[[dialogue]]
speaker = "unk"
# レイラの顔に戸惑いの色が浮かぶ。でも、この先は俺から言わなくちゃ。
line = "レイラの顔に戸惑いの色が浮かぶ。でも、この先は俺から言わなくちゃ。"

[[dialogue]]
speaker = "unk"
# レイラが好きだ。俺と付き合ってほしい
line = "レイラが好きだ。俺と付き合ってほしい"

[[dialogue]]
speaker = "レイラ"
# 「っ！」
line = "「っ！」"

[[dialogue]]
speaker = "レイラ"
# 「はい。……不束者ですけど、よろしくお願いします」
line = "「はい。……不束者ですけど、よろしくお願いします」"

[[dialogue]]
speaker = "unk"
# レイラが再び目を閉じる。俺も目を閉じ──
line = "レイラが再び目を閉じる。俺も目を閉じ──"

[[dialogue]]
speaker = "レイラ"
# 「ちゅっ」
line = "「ちゅっ」"
