[[dialogue]]
speaker = "unk"
# 第１話,市倉環の乙女なココロ,P
line = "第１話,市倉環の乙女なココロ,P"

[[dialogue]]
speaker = "unk"
# 平行世界デネブにおける防衛戦から数日が経った。
line = "平行世界デネブにおける防衛戦から数日が経った。"

[[dialogue]]
speaker = "unk"
# 『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』とは近いうちに最後の決着をつけることになるだろう──しかしすぐにヤツのところに乗り込むわけにはいかない。
line = "『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』とは近いうちに最後の決着をつけることになるだろう──しかしすぐにヤツのところに乗り込むわけにはいかない。"

[[dialogue]]
speaker = "unk"
# 負傷者の手当てに、アルタイルとデネブが連携を取るための打ち合わせ。やることはたくさんある──そして今、俺は。
line = "負傷者の手当てに、アルタイルとデネブが連携を取るための打ち合わせ。やることはたくさんある──そして今、俺は。"

[[dialogue]]
speaker = "unk"
# 世界の危機と同じくらいに大変な、個人的なトラブルにも直面していた──
line = "世界の危機と同じくらいに大変な、個人的なトラブルにも直面していた──"

[[dialogue]]
speaker = "チナ"
# 「ここがレジスタンスのアジト……すごいな。本当に秘密基地って感じだ」
line = "「ここがレジスタンスのアジト……すごいな。本当に秘密基地って感じだ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「『空間』の魔女が隠蔽していたのね。道理で見つからないわけだわ」
line = "「『空間』の魔女が隠蔽していたのね。道理で見つからないわけだわ」"

[[dialogue]]
speaker = "ベアトリス"
# 「お邪魔します、リノさん。すみません、大勢で押しかけちゃって……」
line = "「お邪魔します、リノさん。すみません、大勢で押しかけちゃって……」"

[[dialogue]]
speaker = "リノ"
# 「いいのよ、賑やかな方が楽しいもの！」
line = "「いいのよ、賑やかな方が楽しいもの！」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「色々と<ruby=いさかい>諍い</ruby>もあったけど、アタシたちはもう仲間だ。極星学園のみんな、我が家だと思ってくつろいでくれ！」
line = "「色々と<ruby>諍い<rt>いさかい</rt></ruby>もあったけど、アタシたちはもう仲間だ。極星学園のみんな、我が家だと思ってくつろいでくれ！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「感謝するわ。ところで──」
line = "「感謝するわ。ところで──」"

[[dialogue]]
speaker = "チナ"
# 「……あれ、何なんだ？」
line = "「……あれ、何なんだ？」"

[[dialogue]]
speaker = "ラクシャ"
# 「あ～……喉が渇いたなぁ～？　冷たいコーラが飲みたいなあ～？」
line = "「あ～……喉が渇いたなぁ～？　冷たいコーラが飲みたいなあ～？」"

[[dialogue]]
speaker = "unk"
# どうぞ……！
line = "どうぞ……！"

[[dialogue]]
speaker = "ラクシャ"
# 「ゴクゴク……ぷはー♪　あー、今度は肩が凝ってきたかも？　どこかにマッサージ上手な男の子はいないかなー？」
line = "「ゴクゴク……ぷはー♪　あー、今度は肩が凝ってきたかも？　どこかにマッサージ上手な男の子はいないかなー？」"

[[dialogue]]
speaker = "unk"
# モミモミ……！
line = "モミモミ……！"

[[dialogue]]
speaker = "グレイス"
# 「魔王さん、ずいぶんと慌ただしく動いてますね？」
line = "「魔王さん、ずいぶんと慌ただしく動いてますね？」"

[[dialogue]]
speaker = "レティシア"
# 「察するに──私たちがここに来る前から、ずっとあんな感じのようだけれど？」
line = "「察するに──私たちがここに来る前から、ずっとあんな感じのようだけれど？」"

[[dialogue]]
speaker = "アナ"
# 「イエス。現在、守護天使ラクシャ様──いいえ。市倉さんは、非常にご機嫌がナナメでして」
line = "「イエス。現在、守護天使ラクシャ様──いいえ。市倉さんは、非常にご機嫌がナナメでして」"

[[dialogue]]
speaker = "マトイ"
# 「会長が市倉さんを怒らせちゃったみたい……ついこの間知ったんだけど、あの２人、<b>実はお付き合いしてた</b>みたいで……」
line = "「会長が市倉さんを怒らせちゃったみたい……ついこの間知ったんだけど、あの２人、<b>実はお付き合いしてた</b>みたいで……」"

[[dialogue]]
speaker = "グレイス"
# 「がーん！？　お、お付き合い……そ、そうですかぁ」
line = "「がーん！？　お、お付き合い……そ、そうですかぁ」"

[[dialogue]]
speaker = "グレイス"
# 「……その。事情はわかりませんが、魔王さんを許してあげることはできないんですか？」
line = "「……その。事情はわかりませんが、魔王さんを許してあげることはできないんですか？」"

[[dialogue]]
speaker = "ラクシャ"
# 「うーん。もうしばらくは無理かなー？　ボクのピュアな乙女心を弄んだ罪は重いからね～」
line = "「うーん。もうしばらくは無理かなー？　ボクのピュアな乙女心を弄んだ罪は重いからね～」"

[[dialogue]]
speaker = "レティシア"
# 「そう言わずに。魔王が可哀想じゃない」
line = "「そう言わずに。魔王が可哀想じゃない」"

[[dialogue]]
speaker = "チナ"
# 「そーだぞ。あんなにしおらしく反省してるじゃないか。仲直りしてやれよ」
line = "「そーだぞ。あんなにしおらしく反省してるじゃないか。仲直りしてやれよ」"

[[dialogue]]
speaker = "unk"
# 極星の皆……味方になってくれるのか！？
line = "極星の皆……味方になってくれるのか！？"

[[dialogue]]
speaker = "ルヴィネ"
# 「当然でしょう。魔王には世話になったもの。私たち５人は、いつだってあなたの味方よ」
line = "「当然でしょう。魔王には世話になったもの。私たち５人は、いつだってあなたの味方よ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「守護天使ラクシャ。いったい何があったというの？」
line = "「守護天使ラクシャ。いったい何があったというの？」"

[[dialogue]]
speaker = "ラクシャ"
# 「知りたいなら教えてあげるよ。会長ったらひどいんだから……！」
line = "「知りたいなら教えてあげるよ。会長ったらひどいんだから……！」"

[[dialogue]]
speaker = "ラクシャ"
# 「会長たちの１回目のデネブ来訪の際──彼らを逃がすために、ボクはフィーニスの塔に残した半身と同化したでしょ？」
line = "「会長たちの１回目のデネブ来訪の際──彼らを逃がすために、ボクはフィーニスの塔に残した半身と同化したでしょ？」"

[[dialogue]]
speaker = "ラクシャ"
# 「その時、別れ際に約束してくれたんだよ……ねぇ会長。キミはボクに何て言ったっけ？」
line = "「その時、別れ際に約束してくれたんだよ……ねぇ会長。キミはボクに何て言ったっけ？」"

[[dialogue]]
speaker = "unk"
# 『いつか迎えに来るよ、環』って……
line = "『いつか迎えに来るよ、環』って……"

[[dialogue]]
speaker = "ラクシャ"
# 「そう。『ラクシャ』じゃなくて、わざわざボクのヒトとしての名前まで呼んでくれて……それはもう感動的なお別れだったよね？」
line = "「そう。『ラクシャ』じゃなくて、わざわざボクのヒトとしての名前まで呼んでくれて……それはもう感動的なお別れだったよね？」"

[[dialogue]]
speaker = "ラクシャ"
# 「その後すぐボクは、フィーニスの塔の第零層に封印された」
line = "「その後すぐボクは、フィーニスの塔の第零層に封印された」"

[[dialogue]]
speaker = "ラクシャ"
# 「暗い闇の中で……ボクは会長のことを待ち続けたんだ……」
line = "「暗い闇の中で……ボクは会長のことを待ち続けたんだ……」"

[[dialogue]]
speaker = "ラクシャ"
# （……次に会長に出会えたら、何て声をかけようかな？）
line = "（……次に会長に出会えたら、何て声をかけようかな？）"

[[dialogue]]
speaker = "ラクシャ"
# （『もう──遅いよ！』なんて言いながら、ハグとかしちゃったり……あはは、ボクのキャラじゃないっての）
line = "（『もう──遅いよ！』なんて言いながら、ハグとかしちゃったり……あはは、ボクのキャラじゃないっての）"

[[dialogue]]
speaker = "ラクシャ"
# （でも……）
line = "（でも……）"

[[dialogue]]
speaker = "ラクシャ"
# （早く、逢いたいな……）
line = "（早く、逢いたいな……）"

[[dialogue]]
speaker = "ラクシャ"
# 「あ──封印が、解かれる……！？」
line = "「あ──封印が、解かれる……！？」"

[[dialogue]]
speaker = "ラクシャ"
# 「待ってたよ会長！　逢いたかったよ、すっごく──！」
line = "「待ってたよ会長！　逢いたかったよ、すっごく──！」"

[[dialogue]]
speaker = "セイファート"
# 「──フ。待たせてしまったようだな」
line = "「──フ。待たせてしまったようだな」"

[[dialogue]]
speaker = "ラクシャ"
# 「……………………はぁ？」
line = "「……………………はぁ？」"

[[dialogue]]
speaker = "ラクシャ"
# 「──ってわけ！　怒るなって方が無理でしょ、これ！？」
line = "「──ってわけ！　怒るなって方が無理でしょ、これ！？」"

[[dialogue]]
speaker = "ラクシャ"
# 「ようやく彼氏と再会できると思ったら、ヒゲのおっさんに出迎えられたんだよ！？　あり得ないよ！！」
line = "「ようやく彼氏と再会できると思ったら、ヒゲのおっさんに出迎えられたんだよ！？　あり得ないよ！！」"

[[dialogue]]
speaker = "チナ"
# 「それは魔王が悪いな。誠心誠意謝れ」
line = "「それは魔王が悪いな。誠心誠意謝れ」"

[[dialogue]]
speaker = "レティシア"
# 「男としてダメね」
line = "「男としてダメね」"

[[dialogue]]
speaker = "グレイス"
# 「魔王さん、酷いです……！　鬼畜！　魔王！！」
line = "「魔王さん、酷いです……！　鬼畜！　魔王！！」"

[[dialogue]]
speaker = "unk"
# さっきまで味方してくれてたのに！？
line = "さっきまで味方してくれてたのに！？"

[[dialogue]]
speaker = "ベアトリス"
# 「お、おじさんの何が駄目なんですか！？　おじさんはかっこよくて素敵じゃないですか──！？」
line = "「お、おじさんの何が駄目なんですか！？　おじさんはかっこよくて素敵じゃないですか──！？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ベアト。ややこしくなるから、あなたは下がりなさい」
line = "「ベアト。ややこしくなるから、あなたは下がりなさい」"

[[dialogue]]
speaker = "unk"
# いい加減、機嫌を直してくれよ環……
line = "いい加減、機嫌を直してくれよ環……"

[[dialogue]]
speaker = "ラクシャ"
# 「むりむり。これはもーちょい引っ張るから」
line = "「むりむり。これはもーちょい引っ張るから」"

[[dialogue]]
speaker = "ラクシャ"
# 「あー、彼氏にエスコートしてもらってデートがしたいなー？　もちろん全部キミの奢りね？」
line = "「あー、彼氏にエスコートしてもらってデートがしたいなー？　もちろん全部キミの奢りね？」"

[[dialogue]]
speaker = "unk"
# お、仰せのままに……！！
line = "お、仰せのままに……！！"

[[dialogue]]
speaker = "unk"
# 環は基本的にさっぱりしていて、後に引きずるタイプではないのだけど……
line = "環は基本的にさっぱりしていて、後に引きずるタイプではないのだけど……"

[[dialogue]]
speaker = "unk"
# それからしばらくの間、俺は環のご機嫌取りに奔走することになるのだった──
line = "それからしばらくの間、俺は環のご機嫌取りに奔走することになるのだった──"
