[[dialogue]]
speaker = "unk"
# 第１話,極星星徒会のお姉さん,P
line = "第１話,極星星徒会のお姉さん,P"

[[dialogue]]
speaker = "unk"
# 極星学園生による天界襲撃からしばらくの月日が経った。
line = "極星学園生による天界襲撃からしばらくの月日が経った。"

[[dialogue]]
speaker = "unk"
# 当初こそアルタイルに敵意を隠さないレティシアだったが、俺たちの説得の甲斐もあり、一時的な協力関係を了承してくれるまでになっていた──
line = "当初こそアルタイルに敵意を隠さないレティシアだったが、俺たちの説得の甲斐もあり、一時的な協力関係を了承してくれるまでになっていた──"

[[dialogue]]
speaker = "グレイス"
# 「……レティシア。このカードはババじゃありませんよ。さぁ、私を信じて引いてください！」
line = "「……レティシア。このカードはババじゃありませんよ。さぁ、私を信じて引いてください！」"

[[dialogue]]
speaker = "レティシア"
# 「あら、そうなのね。助かるわ」
line = "「あら、そうなのね。助かるわ」"

[[dialogue]]
speaker = "チナ"
# 「いや、ぜってー嘘だぞ。ゲームなんだから真剣に──」
line = "「いや、ぜってー嘘だぞ。ゲームなんだから真剣に──」"

[[dialogue]]
speaker = "レティシア"
# 「あ……グレイスったら。これ、ババじゃないの」
line = "「あ……グレイスったら。これ、ババじゃないの」"

[[dialogue]]
speaker = "グレイス"
# 「ふっふっふ……引っ掛かりましたね！　これで私が優勢になりました！」
line = "「ふっふっふ……引っ掛かりましたね！　これで私が優勢になりました！」"

[[dialogue]]
speaker = "レティシア"
# 「困ったわ。このままじゃ負けちゃいそうね」
line = "「困ったわ。このままじゃ負けちゃいそうね」"

[[dialogue]]
speaker = "チナ"
# 「だから言ったじゃねーか。つーかレティシアはグレイスに甘すぎるぞ……引く前からわかってただろ、絶対」
line = "「だから言ったじゃねーか。つーかレティシアはグレイスに甘すぎるぞ……引く前からわかってただろ、絶対」"

[[dialogue]]
speaker = "レティシア"
# 「別にいいじゃない。たかがゲームなんだし」
line = "「別にいいじゃない。たかがゲームなんだし」"

[[dialogue]]
speaker = "チナ"
# 「ばっかやろー。たかがゲーム、されどゲームなんだよ！　真剣にやらないと面白くないだろ！？」
line = "「ばっかやろー。たかがゲーム、されどゲームなんだよ！　真剣にやらないと面白くないだろ！？」"

[[dialogue]]
speaker = "unk"
# いつもこんな感じなのか？
line = "いつもこんな感じなのか？"

[[dialogue]]
speaker = "unk"
# 昼食のデザートを賭けてババ抜き……
line = "昼食のデザートを賭けてババ抜き……"

[[dialogue]]
speaker = "ベアトリス"
# 「そう、ですね。チナちゃんは勝負事が好きで、グレイスちゃんは食いしんぼうなので……」
line = "「そう、ですね。チナちゃんは勝負事が好きで、グレイスちゃんは食いしんぼうなので……」"

[[dialogue]]
speaker = "ベアトリス"
# 「『勝者がデザートを独り占め』みたいなゲームはよくやってますね……あはは」
line = "「『勝者がデザートを独り占め』みたいなゲームはよくやってますね……あはは」"

[[dialogue]]
speaker = "ベアトリス"
# 「だいたい今みたいに、レティシアちゃんがグレイスちゃんを甘やかして泥仕合になるんですけれど……」
line = "「だいたい今みたいに、レティシアちゃんがグレイスちゃんを甘やかして泥仕合になるんですけれど……」"

[[dialogue]]
speaker = "レティシア"
# 「チナ。こっちがババよ。引いたら危ないから注意してね？」
line = "「チナ。こっちがババよ。引いたら危ないから注意してね？」"

[[dialogue]]
speaker = "チナ"
# 「ま～た余計なヒントが出ちまった。レティシアは嘘とか吐かないからなぁ……ほら、やっぱりだ」
line = "「ま～た余計なヒントが出ちまった。レティシアは嘘とか吐かないからなぁ……ほら、やっぱりだ」"

[[dialogue]]
speaker = "レティシア"
# 「ふふふ。ババじゃない方を引いてくれたわね。信じてくれてありがとう、チナ」
line = "「ふふふ。ババじゃない方を引いてくれたわね。信じてくれてありがとう、チナ」"

[[dialogue]]
speaker = "チナ"
# 「なんで追い詰められてるヤツに感謝されてるんだ、アタシは？」
line = "「なんで追い詰められてるヤツに感謝されてるんだ、アタシは？」"

[[dialogue]]
speaker = "グレイス"
# 「レティシアはこのまま最下位確定ですね。チナ、私と一騎打ちですよ！　プリンは譲りませんから！」
line = "「レティシアはこのまま最下位確定ですね。チナ、私と一騎打ちですよ！　プリンは譲りませんから！」"

[[dialogue]]
speaker = "チナ"
# 「アタシだって負けねーっての！　いくぞグレイス！」
line = "「アタシだって負けねーっての！　いくぞグレイス！」"

[[dialogue]]
speaker = "グレイス"
# 「ううぅぅぅ～……！　私のプリンが……サランさんお手製の極旨プリンがぁ……」
line = "「ううぅぅぅ～……！　私のプリンが……サランさんお手製の極旨プリンがぁ……」"

[[dialogue]]
speaker = "チナ"
# 「やった！　デザート３人分ゲットだ！　今日はついてるな！」
line = "「やった！　デザート３人分ゲットだ！　今日はついてるな！」"

[[dialogue]]
speaker = "グレイス"
# 「レ、レティシア～っ……！！」
line = "「レ、レティシア～っ……！！」"

[[dialogue]]
speaker = "レティシア"
# 「可哀想に。あとでカフェテリアに行きましょう？　パフェをごちそうしてあげるから、元気を出して」
line = "「可哀想に。あとでカフェテリアに行きましょう？　パフェをごちそうしてあげるから、元気を出して」"

[[dialogue]]
speaker = "グレイス"
# 「本当ですか！？　嬉しいです～！！」
line = "「本当ですか！？　嬉しいです～！！」"

[[dialogue]]
speaker = "チナ"
# 「いや、そんなことしたら賭けの意味ないだろ……」
line = "「いや、そんなことしたら賭けの意味ないだろ……」"

[[dialogue]]
speaker = "レティシア"
# 「チナも欲しいの？　いいわよ、ごちそうしてあげるわね」
line = "「チナも欲しいの？　いいわよ、ごちそうしてあげるわね」"

[[dialogue]]
speaker = "チナ"
# 「やめろ！　アタシのプリンの価値が下がることを言うな……！」
line = "「やめろ！　アタシのプリンの価値が下がることを言うな……！」"

[[dialogue]]
speaker = "unk"
# レティシアは、特殊な生い立ちのせいで、自我の欲求というものが希薄な天使だ。
line = "レティシアは、特殊な生い立ちのせいで、自我の欲求というものが希薄な天使だ。"

[[dialogue]]
speaker = "unk"
# 『何をすればいいかわからない時は、みんなのお世話をしなさい』──そうルヴィネから命じられており、それに従って動いているのだと聞いている。
line = "『何をすればいいかわからない時は、みんなのお世話をしなさい』──そうルヴィネから命じられており、それに従って動いているのだと聞いている。"

[[dialogue]]
speaker = "グレイス"
# 「──うぅっ！？　ピ、ピーマンがありますっ……！？」
line = "「──うぅっ！？　ピ、ピーマンがありますっ……！？」"

[[dialogue]]
speaker = "グレイス"
# 「その～……レティシア～……？」
line = "「その～……レティシア～……？」"

[[dialogue]]
speaker = "レティシア"
# 「ええ。ピーマン、食べてあげるわね。貰ってばかりだと悪いし……私のお肉と交換しましょうか」
line = "「ええ。ピーマン、食べてあげるわね。貰ってばかりだと悪いし……私のお肉と交換しましょうか」"

[[dialogue]]
speaker = "グレイス"
# 「いいんですか～っ！　レティシア大好きです！！」
line = "「いいんですか～っ！　レティシア大好きです！！」"

[[dialogue]]
speaker = "チナ"
# 「待て待て待て。交換レートがおかしい！」
line = "「待て待て待て。交換レートがおかしい！」"

[[dialogue]]
speaker = "レティシア"
# 「チナも茄子が苦手でしょう？　食べてあげましょうか」
line = "「チナも茄子が苦手でしょう？　食べてあげましょうか」"

[[dialogue]]
speaker = "チナ"
# 「子ども扱いすんなっての……！」
line = "「子ども扱いすんなっての……！」"

[[dialogue]]
speaker = "unk"
# 仲良しなんだな、みんな
line = "仲良しなんだな、みんな"

[[dialogue]]
speaker = "ベアトリス"
# 「はい！　もうずっと一緒の５人ですから！」
line = "「はい！　もうずっと一緒の５人ですから！」"

[[dialogue]]
speaker = "グレイス"
# 「人生の半分以上、一緒にいますしね」
line = "「人生の半分以上、一緒にいますしね」"

[[dialogue]]
speaker = "チナ"
# 「でもアタシはいい加減、グレイスを厳しくしつける必要があると思うんだ……」
line = "「でもアタシはいい加減、グレイスを厳しくしつける必要があると思うんだ……」"

[[dialogue]]
speaker = "レティシア"
# 「いいじゃない。グレイスにはのびのびしていて欲しいもの」
line = "「いいじゃない。グレイスにはのびのびしていて欲しいもの」"

[[dialogue]]
speaker = "グレイス"
# 「あっ……ピーマン、まだお皿に残ってました……！？　レティシア、これも──」
line = "「あっ……ピーマン、まだお皿に残ってました……！？　レティシア、これも──」"

[[dialogue]]
speaker = "レティシア"
# 「ごめんなさいね。今日はもう、だめなの」
line = "「ごめんなさいね。今日はもう、だめなの」"

[[dialogue]]
speaker = "グレイス"
# 「えっ？」
line = "「えっ？」"

[[dialogue]]
speaker = "レティシア"
# 「ルヴィから言われてるの。グレイスを甘やかすのは１日３回までって」
line = "「ルヴィから言われてるの。グレイスを甘やかすのは１日３回までって」"

[[dialogue]]
speaker = "レティシア"
# 「ババ抜きで１回。パフェの約束で１回。最初のピーマンで１回。使い切っちゃったから──ごめんなさいね？」
line = "「ババ抜きで１回。パフェの約束で１回。最初のピーマンで１回。使い切っちゃったから──ごめんなさいね？」"

[[dialogue]]
speaker = "グレイス"
# 「そんなぁ！？　あとちょっとです、ほら、ぱくってすればすぐ終わりますよ！？」
line = "「そんなぁ！？　あとちょっとです、ほら、ぱくってすればすぐ終わりますよ！？」"

[[dialogue]]
speaker = "レティシア"
# 「すぐ終わるのなら、なおのこと、がんばって自分で食べてね。ふふふ」
line = "「すぐ終わるのなら、なおのこと、がんばって自分で食べてね。ふふふ」"

[[dialogue]]
speaker = "unk"
# 愛情深いようで機械的──自身のことを『空っぽだ』と称したレティシアの日常は、自然なようでいて、少しだけ歪にも見える。
line = "愛情深いようで機械的──自身のことを『空っぽだ』と称したレティシアの日常は、自然なようでいて、少しだけ歪にも見える。"

[[dialogue]]
speaker = "unk"
# このアルタイルで過ごす日々が、彼女にいい影響を与えてくれればいいのだけれど……
line = "このアルタイルで過ごす日々が、彼女にいい影響を与えてくれればいいのだけれど……"

[[dialogue]]
speaker = "レティシア"
# 「…………はむ」
line = "「…………はむ」"

[[dialogue]]
speaker = "unk"
# （…………あれ？）
line = "（…………あれ？）"

[[dialogue]]
speaker = "unk"
# グレイスと交換したピーマンを食べる時、レティシアの顔が一瞬、曇ったような気がした。
line = "グレイスと交換したピーマンを食べる時、レティシアの顔が一瞬、曇ったような気がした。"

[[dialogue]]
speaker = "unk"
# …………俺はもう少し、彼女のことをしっかりと見る必要があるのかもしれない。
line = "…………俺はもう少し、彼女のことをしっかりと見る必要があるのかもしれない。"
