[[dialogue]]
speaker = "unk"
# 第２話,吸血鬼ＶＳ吸血鬼？,P
line = "第２話,吸血鬼ＶＳ吸血鬼？,P"

[[dialogue]]
speaker = "ソフレ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "ベアトリス"
# 「はわわ……」
line = "「はわわ……」"

[[dialogue]]
speaker = "unk"
# 放課後、一休みしようとカフェテリアに向かうと、ソフレとベアトリスの２人がいた。
line = "放課後、一休みしようとカフェテリアに向かうと、ソフレとベアトリスの２人がいた。"

[[dialogue]]
speaker = "unk"
# ソフレはいつも通りのローテンションだが、ベアトリスはヘビににらまれたカエルのようにすくみ上っていた。
line = "ソフレはいつも通りのローテンションだが、ベアトリスはヘビににらまれたカエルのようにすくみ上っていた。"

[[dialogue]]
speaker = "unk"
# ２人は知り合い？
line = "２人は知り合い？"

[[dialogue]]
speaker = "ソフレ"
# 「全く知らないのだわ」
line = "「全く知らないのだわ」"

[[dialogue]]
speaker = "ベアトリス"
# 「ああいえ、初対面です……」
line = "「ああいえ、初対面です……」"

[[dialogue]]
speaker = "unk"
# 初対面なんだ……
line = "初対面なんだ……"

[[dialogue]]
speaker = "ソフレ"
# 「でも無関係ではないわ。こいつ、ソフレと同族なのだわ」
line = "「でも無関係ではないわ。こいつ、ソフレと同族なのだわ」"

[[dialogue]]
speaker = "unk"
# 同族っていうと……吸血鬼？
line = "同族っていうと……吸血鬼？"

[[dialogue]]
speaker = "ベアトリス"
# 「はい、私も吸血鬼なんです。ほら、牙とか羽とか付いてますよね？　パタパタ」
line = "「はい、私も吸血鬼なんです。ほら、牙とか羽とか付いてますよね？　パタパタ」"

[[dialogue]]
speaker = "ベアトリス"
# 「ソフレ様とは違い、私たちの一族は暗い洞窟で暮らしているのですが……同じ吸血鬼なのでソフレ様のことは有名でした」
line = "「ソフレ様とは違い、私たちの一族は暗い洞窟で暮らしているのですが……同じ吸血鬼なのでソフレ様のことは有名でした」"

[[dialogue]]
speaker = "ベアトリス"
# 「『暴虐の吸血鬼』と恐れられる存在で、子どもが言うことを聞かないと『ソフレ様に食べられるぞ』って脅すんです」
line = "「『暴虐の吸血鬼』と恐れられる存在で、子どもが言うことを聞かないと『ソフレ様に食べられるぞ』って脅すんです」"

[[dialogue]]
speaker = "ソフレ"
# 「普通に失礼ね、それ」
line = "「普通に失礼ね、それ」"

[[dialogue]]
speaker = "ソフレ"
# 「でもその吸血鬼が、どうして昼日中にこんなところにいるのかしら」
line = "「でもその吸血鬼が、どうして昼日中にこんなところにいるのかしら」"

[[dialogue]]
speaker = "ソフレ"
# 「ソフレは日光を克服した吸血鬼『デイマスター』。だけど普通の吸血鬼は日の光を浴びると肌を焼かれるし、最悪死ぬのだわ」
line = "「ソフレは日光を克服した吸血鬼『デイマスター』。だけど普通の吸血鬼は日の光を浴びると肌を焼かれるし、最悪死ぬのだわ」"

[[dialogue]]
speaker = "ベアトリス"
# 「私はデイマスターじゃないけど、星力がある間は日光も大丈夫なんです。逆に言えば星力がないとダメなんですけど」
line = "「私はデイマスターじゃないけど、星力がある間は日光も大丈夫なんです。逆に言えば星力がないとダメなんですけど」"

[[dialogue]]
speaker = "ベアトリス"
# 「なので、星騎士じゃなくなったら故郷の洞窟に帰るつもりです」
line = "「なので、星騎士じゃなくなったら故郷の洞窟に帰るつもりです」"

[[dialogue]]
speaker = "ソフレ"
# 「なるほど、そういうのもありなのね」
line = "「なるほど、そういうのもありなのね」"

[[dialogue]]
speaker = "ソフレ"
# 「でもお前とソフレは故郷が近いだけの赤の他人。放っておいてほしいのだわ」
line = "「でもお前とソフレは故郷が近いだけの赤の他人。放っておいてほしいのだわ」"

[[dialogue]]
speaker = "ベアトリス"
# 「そんな～っ、同じ吸血鬼同士仲良くしましょうよ～っ！　流星市国には他に吸血鬼がいないから心細いんですよっ」
line = "「そんな～っ、同じ吸血鬼同士仲良くしましょうよ～っ！　流星市国には他に吸血鬼がいないから心細いんですよっ」"

[[dialogue]]
speaker = "ソフレ"
# 「ソフレをなまはげ呼ばわりしたお前には言われたくないのだわ」
line = "「ソフレをなまはげ呼ばわりしたお前には言われたくないのだわ」"

[[dialogue]]
speaker = "ベアトリス"
# 「ひぃっ……！？　ごめんなさ～いっ！？」
line = "「ひぃっ……！？　ごめんなさ～いっ！？」"

[[dialogue]]
speaker = "unk"
# ちなみになまはげは神の使いであり、子どもは食べない……らしい。
line = "ちなみになまはげは神の使いであり、子どもは食べない……らしい。"

[[dialogue]]
speaker = "ソフレ"
# 「ま、お前のことはどうでもいいけど、ソフレ様はやめなさい。一応同学年なんだから普通にソフレでいいのだわ」
line = "「ま、お前のことはどうでもいいけど、ソフレ様はやめなさい。一応同学年なんだから普通にソフレでいいのだわ」"

[[dialogue]]
speaker = "ベアトリス"
# 「は、はい……わかりました……」
line = "「は、はい……わかりました……」"

[[dialogue]]
speaker = "unk"
# ちなみに２人は何を食べてるの？
line = "ちなみに２人は何を食べてるの？"

[[dialogue]]
speaker = "ソフレ"
# 「ソフレはパンケーキよ。ここのパンケーキは雲みたいにふわふわで悪くないのだわ」
line = "「ソフレはパンケーキよ。ここのパンケーキは雲みたいにふわふわで悪くないのだわ」"

[[dialogue]]
speaker = "ベアトリス"
# 「私はラズベリーのケーキと紅茶にしました。これから食べるところなんですけど」
line = "「私はラズベリーのケーキと紅茶にしました。これから食べるところなんですけど」"

[[dialogue]]
speaker = "unk"
# ２人とも血じゃない！
line = "２人とも血じゃない！"

[[dialogue]]
speaker = "ソフレ"
# 「当然でしょ。カフェテリアで血が出るわけないし。吸血鬼といっても、血液で栄養を摂っているわけじゃないのだわ」
line = "「当然でしょ。カフェテリアで血が出るわけないし。吸血鬼といっても、血液で栄養を摂っているわけじゃないのだわ」"

[[dialogue]]
speaker = "ベアトリス"
# 「もし血だけで生きようとしたら、たっくさんの血液が要りますからね。そんなに血ばかり飲んでいたら、吸血鬼が討伐されちゃいますよ」
line = "「もし血だけで生きようとしたら、たっくさんの血液が要りますからね。そんなに血ばかり飲んでいたら、吸血鬼が討伐されちゃいますよ」"

[[dialogue]]
speaker = "ベアトリス"
# 「でもこのケーキ、血のように真っ赤で……美味しそうです……」
line = "「でもこのケーキ、血のように真っ赤で……美味しそうです……」"

[[dialogue]]
speaker = "ソフレ"
# 「はしたないのだわ……」
line = "「はしたないのだわ……」"

[[dialogue]]
speaker = "ベアトリス"
# 「いえ、普通に美味しそうだなって思ってるだけですよ！？」
line = "「いえ、普通に美味しそうだなって思ってるだけですよ！？」"

[[dialogue]]
speaker = "unk"
# どういう意味……？
line = "どういう意味……？"

[[dialogue]]
speaker = "ベアトリス"
# 「あ～いえいえいえ！　本当に他意なんてないですから！　ケーキ美味しそうですよね！　ね！？」
line = "「あ～いえいえいえ！　本当に他意なんてないですから！　ケーキ美味しそうですよね！　ね！？」"

[[dialogue]]
speaker = "ソフレ"
# 「吸血鬼は、吸血によって異性を自分の眷属にすることができる。眷属を作るということは、同族を増やすということ。つまり──」
line = "「吸血鬼は、吸血によって異性を自分の眷属にすることができる。眷属を作るということは、同族を増やすということ。つまり──」"

[[dialogue]]
speaker = "ソフレ"
# 「生殖よ」
line = "「生殖よ」"

[[dialogue]]
speaker = "ベアトリス"
# 「！？」
line = "「！？」"

[[dialogue]]
speaker = "ソフレ"
# 「こいつ、赤いケーキを見て欲情しているのだわ……」
line = "「こいつ、赤いケーキを見て欲情しているのだわ……」"

[[dialogue]]
speaker = "ベアトリス"
# 「ちち、違いますから！　私そんなむっつりじゃないですから！」
line = "「ちち、違いますから！　私そんなむっつりじゃないですから！」"

[[dialogue]]
speaker = "ソフレ"
# 「じゃあ会長の目を見て違うって言える？　年頃の異性の顔を見ながらでも言えるの？」
line = "「じゃあ会長の目を見て違うって言える？　年頃の異性の顔を見ながらでも言えるの？」"

[[dialogue]]
speaker = "ベアトリス"
# 「も、もちろん言えますよ！　会長さん、じっとしててくださいね！」
line = "「も、もちろん言えますよ！　会長さん、じっとしててくださいね！」"

[[dialogue]]
speaker = "ベアトリス"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "ベアトリス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ベアトリス"
# 「やっぱり無理です、ごめんなさ～いっ！！」
line = "「やっぱり無理です、ごめんなさ～いっ！！」"

[[dialogue]]
speaker = "unk"
# ……行っちゃった
line = "……行っちゃった"

[[dialogue]]
speaker = "ソフレ"
# 「まったく、卑しい吸血鬼なのだわ」
line = "「まったく、卑しい吸血鬼なのだわ」"

[[dialogue]]
speaker = "unk"
# それからしばらく、ベアトリスは俺を見ると逃げるようになってしまった。
line = "それからしばらく、ベアトリスは俺を見ると逃げるようになってしまった。"

[[dialogue]]
speaker = "unk"
# ……ちなみにベアトリスのケーキはソフレが美味しくいただきました。
line = "……ちなみにベアトリスのケーキはソフレが美味しくいただきました。"
