[[dialogue]]
speaker = "unk"
# 第４話,遠き日の思い出と,P
line = "第４話,遠き日の思い出と,P"

[[dialogue]]
speaker = "unk"
# エステルに会うために教皇庁へ向かおうとしていると。
line = "エステルに会うために教皇庁へ向かおうとしていると。"

[[dialogue]]
speaker = "エステル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# 車道を見つめながら、物思いにふけっているエステルの姿を見つけた。
line = "車道を見つめながら、物思いにふけっているエステルの姿を見つけた。"

[[dialogue]]
speaker = "unk"
# その場所、その表情から、彼女が今、何を思っているのか、俺にはすぐに想像することが出来た。
line = "その場所、その表情から、彼女が今、何を思っているのか、俺にはすぐに想像することが出来た。"

[[dialogue]]
speaker = "unk"
# 俺がエステルを助けた場所
line = "俺がエステルを助けた場所"

[[dialogue]]
speaker = "unk"
# ここだったよね
line = "ここだったよね"

[[dialogue]]
speaker = "エステル"
# 「はい……」
line = "「はい……」"

[[dialogue]]
speaker = "エステル"
# 「あれから１０年以上経ちました。けれど、私をモンスターから救うため、勇敢に戦ってくれた魔王様のお姿は忘れたことがありません」
line = "「あれから１０年以上経ちました。けれど、私をモンスターから救うため、勇敢に戦ってくれた魔王様のお姿は忘れたことがありません」"

[[dialogue]]
speaker = "エステル"
# 「突然現れたモンスターたちに、私の乗ったスクールバスが襲われて……」
line = "「突然現れたモンスターたちに、私の乗ったスクールバスが襲われて……」"

[[dialogue]]
speaker = "エステル"
# 「バスの中に取り残されてしまった私は、バスごとモンスターたちに齧られてしまうところでした」
line = "「バスの中に取り残されてしまった私は、バスごとモンスターたちに齧られてしまうところでした」"

[[dialogue]]
speaker = "エステル"
# 「そこに魔王様が現れて、モンスターたちの注意を自分に引き付け……その間に私は救い出されました」
line = "「そこに魔王様が現れて、モンスターたちの注意を自分に引き付け……その間に私は救い出されました」"

[[dialogue]]
speaker = "unk"
# セレスティアも持ってなかったな
line = "セレスティアも持ってなかったな"

[[dialogue]]
speaker = "unk"
# そんな感じだったね
line = "そんな感じだったね"

[[dialogue]]
speaker = "エステル"
# 「そんな状況なのに私を救おうと身体を張って戦って下さったのですね……」
line = "「そんな状況なのに私を救おうと身体を張って戦って下さったのですね……」"

[[dialogue]]
speaker = "エステル"
# 「魔王様、あらためてお礼を言わせてください……ありがとうございます」
line = "「魔王様、あらためてお礼を言わせてください……ありがとうございます」"

[[dialogue]]
speaker = "unk"
# お互いさまだ
line = "お互いさまだ"

[[dialogue]]
speaker = "unk"
# デネブではエステルに助けられた
line = "デネブではエステルに助けられた"

[[dialogue]]
speaker = "エステル"
# 「ふふっ、そうかもしれませんが……私は私の正しいと思う事を信じただけなんです」
line = "「ふふっ、そうかもしれませんが……私は私の正しいと思う事を信じただけなんです」"

[[dialogue]]
speaker = "エステル"
# 「デネブであなたの姿を見た時……普通ならありえないことなのに……あなたが魔王様なのだとすぐに気が付きました」
line = "「デネブであなたの姿を見た時……普通ならありえないことなのに……あなたが魔王様なのだとすぐに気が付きました」"

[[dialogue]]
speaker = "エステル"
# 「私の世界の魔王様は、デネブを裏切ったと聞いています」
line = "「私の世界の魔王様は、デネブを裏切ったと聞いています」"

[[dialogue]]
speaker = "エステル"
# 「けれど私はそんなこと信じられなくて。ずっとどこかで皆のために戦い続けているんだと信じていました」
line = "「けれど私はそんなこと信じられなくて。ずっとどこかで皆のために戦い続けているんだと信じていました」"

[[dialogue]]
speaker = "エステル"
# 「そうしたらあなたが現れて……私が思い続けていたことは間違いではなかったのだと証明してくれたんです」
line = "「そうしたらあなたが現れて……私が思い続けていたことは間違いではなかったのだと証明してくれたんです」"

[[dialogue]]
speaker = "エステル"
# 「それに……アルタイルに来て数日間ですが、一緒に過ごしていてもあなたは優しくて、思い出以上に素晴らしい人で……」
line = "「それに……アルタイルに来て数日間ですが、一緒に過ごしていてもあなたは優しくて、思い出以上に素晴らしい人で……」"

[[dialogue]]
speaker = "エステル"
# 「あなたが裏切者の悪なる存在だなんてありえない、という確信を持たせてくれました」
line = "「あなたが裏切者の悪なる存在だなんてありえない、という確信を持たせてくれました」"

[[dialogue]]
speaker = "エステル"
# 「それで私の心は救われたんです……本当に、本当にありがとうございました」
line = "「それで私の心は救われたんです……本当に、本当にありがとうございました」"

[[dialogue]]
speaker = "unk"
# 清らかな瞳でまっすぐに俺を見つめるエステル。
line = "清らかな瞳でまっすぐに俺を見つめるエステル。"

[[dialogue]]
speaker = "unk"
# 彼女が浮かべる笑顔に安心しつつも、同時に胸が締め付けられるような思いがした。
line = "彼女が浮かべる笑顔に安心しつつも、同時に胸が締め付けられるような思いがした。"

[[dialogue]]
speaker = "unk"
# それは俺が、心の中で感じていた負い目を、すっと溶かしてくれるような笑顔だった。
line = "それは俺が、心の中で感じていた負い目を、すっと溶かしてくれるような笑顔だった。"

[[dialogue]]
speaker = "unk"
# ありがとう、エステル
line = "ありがとう、エステル"

[[dialogue]]
speaker = "unk"
# そこで一度言葉を切り……
line = "そこで一度言葉を切り……"

[[dialogue]]
speaker = "unk"
# 大好きだ
line = "大好きだ"

[[dialogue]]
speaker = "エステル"
# 「っ……！！？」
line = "「っ……！！？」"

[[dialogue]]
speaker = "エステル"
# 「そ、そんなお言葉……私にはもったいないです……」
line = "「そ、そんなお言葉……私にはもったいないです……」"

[[dialogue]]
speaker = "エステル"
# 「すみません、勘違いしてはいけないと分かっているのですが、そんな事を言われてしまうとお顔が熱くなってしまいます」
line = "「すみません、勘違いしてはいけないと分かっているのですが、そんな事を言われてしまうとお顔が熱くなってしまいます」"

[[dialogue]]
speaker = "unk"
# 勘違いじゃないよ
line = "勘違いじゃないよ"

[[dialogue]]
speaker = "エステル"
# 「っ……本当ですか？」
line = "「っ……本当ですか？」"

[[dialogue]]
speaker = "エステル"
# 「そんなお気持ちを向けて頂けるなんて、恐れ多いです……」
line = "「そんなお気持ちを向けて頂けるなんて、恐れ多いです……」"

[[dialogue]]
speaker = "エステル"
# 「でも、きちんとお応えしないといけないですよね」
line = "「でも、きちんとお応えしないといけないですよね」"

[[dialogue]]
speaker = "エステル"
# 「正直に申し上げます……魔王様のことは私、命を救われたあの時から、ずっとお慕い申し上げていました」
line = "「正直に申し上げます……魔王様のことは私、命を救われたあの時から、ずっとお慕い申し上げていました」"

[[dialogue]]
speaker = "エステル"
# 「けれど、デネブにやってきた魔王様とお会いして、アルタイルに連れてきていただいて……」
line = "「けれど、デネブにやってきた魔王様とお会いして、アルタイルに連れてきていただいて……」"

[[dialogue]]
speaker = "エステル"
# 「そして同じ場所、同じ時間を過ごすようになって……魔王様のことを慕う気持ちに変化が生まれ始めました」
line = "「そして同じ場所、同じ時間を過ごすようになって……魔王様のことを慕う気持ちに変化が生まれ始めました」"

[[dialogue]]
speaker = "エステル"
# 「きっと……私の抱くあなたへの気持ちは……ただの敬意や恩義ではなく、人として、異性として慕う……思慕の情なのだと思います」
line = "「きっと……私の抱くあなたへの気持ちは……ただの敬意や恩義ではなく、人として、異性として慕う……思慕の情なのだと思います」"

[[dialogue]]
speaker = "unk"
# うれしい、ありがとう
line = "うれしい、ありがとう"

[[dialogue]]
speaker = "エステル"
# 「まさか、自分がこんな気持ちを抱くなんて思ってもいませんでした……」
line = "「まさか、自分がこんな気持ちを抱くなんて思ってもいませんでした……」"

[[dialogue]]
speaker = "エステル"
# 「私にとって魔王様は初恋の人です。そんな人と、こうして想いを通じ合わせることができるなんて……」
line = "「私にとって魔王様は初恋の人です。そんな人と、こうして想いを通じ合わせることができるなんて……」"

[[dialogue]]
speaker = "エステル"
# 「魔王様……ありがとうございます」
line = "「魔王様……ありがとうございます」"

[[dialogue]]
speaker = "unk"
# つつましくエステルが俺の胸に身を預けてくる。
line = "つつましくエステルが俺の胸に身を預けてくる。"

[[dialogue]]
speaker = "unk"
# そんなエステルを俺は愛情を込めて優しく抱きしめたのだった。
line = "そんなエステルを俺は愛情を込めて優しく抱きしめたのだった。"
