[[dialogue]]
speaker = "unk"
# 第２話,ナナカのおもてなし,P
line = "第２話,ナナカのおもてなし,P"

[[dialogue]]
speaker = "unk"
# スイーツ同好会の臨時メンバーになった翌日、俺はナナカに連れられてソバ屋に来ていた。
line = "スイーツ同好会の臨時メンバーになった翌日、俺はナナカに連れられてソバ屋に来ていた。"

[[dialogue]]
speaker = "フィオナ"
# 「このお蕎麦屋さん、ナナカさんのご実家だったのですか。趣のある良いお店ですね」
line = "「このお蕎麦屋さん、ナナカさんのご実家だったのですか。趣のある良いお店ですね」"

[[dialogue]]
speaker = "unk"
# どうしてフィオナも来たの？
line = "どうしてフィオナも来たの？"

[[dialogue]]
speaker = "フィオナ"
# 「えっ？　ええと、会長のことをかなり熱烈に勧誘されたと伺ったので……私もちょっと興味が湧いたんです」
line = "「えっ？　ええと、会長のことをかなり熱烈に勧誘されたと伺ったので……私もちょっと興味が湧いたんです」"

[[dialogue]]
speaker = "ナナカ"
# 「へいお待ち！　夕霧庵名物、天ざるソバでいっ！」
line = "「へいお待ち！　夕霧庵名物、天ざるソバでいっ！」"

[[dialogue]]
speaker = "ナナカ"
# 「前に来た時もうちで食べていってくれたって話だけどさ、今日のソバはひと味違うからね！」
line = "「前に来た時もうちで食べていってくれたって話だけどさ、今日のソバはひと味違うからね！」"

[[dialogue]]
speaker = "フィオナ"
# 「何が違うんですか？」
line = "「何が違うんですか？」"

[[dialogue]]
speaker = "ナナカ"
# 「ふっふっふ……前回は親父が打ったソバだったけど、こいつはアタシの手打ちだよ！」
line = "「ふっふっふ……前回は親父が打ったソバだったけど、こいつはアタシの手打ちだよ！」"

[[dialogue]]
speaker = "ナナカ"
# 「こいつは店じゃ出さない十割ソバなんでい！」
line = "「こいつは店じゃ出さない十割ソバなんでい！」"

[[dialogue]]
speaker = "unk"
# それは凄い！
line = "それは凄い！"

[[dialogue]]
speaker = "ナナカ"
# 「さあさあ、のんびりしてたらソバが伸びちまう！　ささっと食べてくんなっ！」
line = "「さあさあ、のんびりしてたらソバが伸びちまう！　ささっと食べてくんなっ！」"

[[dialogue]]
speaker = "フィオナ"
# 「では頂きましょう。……ちゅるっ」
line = "「では頂きましょう。……ちゅるっ」"

[[dialogue]]
speaker = "ナナカ"
# 「あー、ダメダメ！　ソバはもっと勢いよくすすらなきゃ！　ほら、こうやって……」
line = "「あー、ダメダメ！　ソバはもっと勢いよくすすらなきゃ！　ほら、こうやって……」"

[[dialogue]]
speaker = "ナナカ"
# 「ずるずるずるーーーーっ！！！」
line = "「ずるずるずるーーーーっ！！！」"

[[dialogue]]
speaker = "ナナカ"
# 「かぁーーっ、うんまい！」
line = "「かぁーーっ、うんまい！」"

[[dialogue]]
speaker = "フィオナ"
# 「な、なるほど、少々はしたない気もしますが、音を立てて食べるのが作法とも聞きますし……」
line = "「な、なるほど、少々はしたない気もしますが、音を立てて食べるのが作法とも聞きますし……」"

[[dialogue]]
speaker = "フィオナ"
# 「ずるずるずるっ」
line = "「ずるずるずるっ」"

[[dialogue]]
speaker = "フィオナ"
# 「あら、おいしい。香りがより立つように感じますね」
line = "「あら、おいしい。香りがより立つように感じますね」"

[[dialogue]]
speaker = "unk"
# ほんとにおいしいソバだ
line = "ほんとにおいしいソバだ"

[[dialogue]]
speaker = "ナナカ"
# 「でしょっ？　ささ、この調子でどんどん食べてっ」
line = "「でしょっ？　ささ、この調子でどんどん食べてっ」"

[[dialogue]]
speaker = "フィオナ"
# 「確かにおいしいお蕎麦なのは間違いないですけど……これはスイーツ研究会の活動ですよね？　スイーツなのに、ソバ？」
line = "「確かにおいしいお蕎麦なのは間違いないですけど……これはスイーツ研究会の活動ですよね？　スイーツなのに、ソバ？」"

[[dialogue]]
speaker = "ナナカ"
# 「あー、うん……確かに、いきなりソバを振る舞われたら、面食らっちゃうよね……」
line = "「あー、うん……確かに、いきなりソバを振る舞われたら、面食らっちゃうよね……」"

[[dialogue]]
speaker = "ナナカ"
# 「でもさ、アタシもちょっと無茶言いすぎたって反省してるんだ。時間が限られてるのに、こっちの都合に巻き込んじゃってさ」
line = "「でもさ、アタシもちょっと無茶言いすぎたって反省してるんだ。時間が限られてるのに、こっちの都合に巻き込んじゃってさ」"

[[dialogue]]
speaker = "ナナカ"
# 「だからせめて、アタシに出来る最大限のもてなしをしてあげたいってわけ」
line = "「だからせめて、アタシに出来る最大限のもてなしをしてあげたいってわけ」"

[[dialogue]]
speaker = "ナナカ"
# 「ソバ屋の娘だし、自分でも手打ちしてるし、みんなおいしいって言ってくれるから、これなら喜んでもらえるんじゃないかな、ってね」
line = "「ソバ屋の娘だし、自分でも手打ちしてるし、みんなおいしいって言ってくれるから、これなら喜んでもらえるんじゃないかな、ってね」"

[[dialogue]]
speaker = "フィオナ"
# 「つまり、スイーツ研究会の手伝いをするお礼が、このお蕎麦ということですね？」
line = "「つまり、スイーツ研究会の手伝いをするお礼が、このお蕎麦ということですね？」"

[[dialogue]]
speaker = "ナナカ"
# 「そーいうことっ。どうかな会長？　こいつで満足してもらえるか、わかんないけど……」
line = "「そーいうことっ。どうかな会長？　こいつで満足してもらえるか、わかんないけど……」"

[[dialogue]]
speaker = "unk"
# 天ぷらもメチャクチャうまい！
line = "天ぷらもメチャクチャうまい！"

[[dialogue]]
speaker = "ナナカ"
# 「たはは……ごめん、天ぷらは親父に揚げてもらったんだよね」
line = "「たはは……ごめん、天ぷらは親父に揚げてもらったんだよね」"

[[dialogue]]
speaker = "ナナカ"
# 「一応、アタシでも揚げられるんだけどさ、そこまではさすがに、親父には敵わないからね。よりおいしいものを提供したかったってわけ」
line = "「一応、アタシでも揚げられるんだけどさ、そこまではさすがに、親父には敵わないからね。よりおいしいものを提供したかったってわけ」"

[[dialogue]]
speaker = "ナナカ"
# 「ってことで、今のアタシに出せる札はこんだけだ！　さあ、ジャッジしてくんな！」
line = "「ってことで、今のアタシに出せる札はこんだけだ！　さあ、ジャッジしてくんな！」"

[[dialogue]]
speaker = "unk"
# 最高のおもてなしだったよ！
line = "最高のおもてなしだったよ！"

[[dialogue]]
speaker = "フィオナ"
# 「ふふっ、合格みたいですね」
line = "「ふふっ、合格みたいですね」"

[[dialogue]]
speaker = "ナナカ"
# 「よっしゃー！　なら、２人ともアタシに協力してくれるってことだよね！」
line = "「よっしゃー！　なら、２人ともアタシに協力してくれるってことだよね！」"

[[dialogue]]
speaker = "フィオナ"
# 「ええっ、私もですか？」
line = "「ええっ、私もですか？」"

[[dialogue]]
speaker = "ナナカ"
# 「フィオナはなんか食通っぽいから、頼りになりそう」
line = "「フィオナはなんか食通っぽいから、頼りになりそう」"

[[dialogue]]
speaker = "フィオナ"
# 「そ、そんなことは無いのですが……私で協力できることがあるなら」
line = "「そ、そんなことは無いのですが……私で協力できることがあるなら」"

[[dialogue]]
speaker = "unk"
# 俺も協力するよ
line = "俺も協力するよ"

[[dialogue]]
speaker = "ナナカ"
# 「あんがとっ！　じゃあ頼りにさせてもらうねっ」
line = "「あんがとっ！　じゃあ頼りにさせてもらうねっ」"

[[dialogue]]
speaker = "unk"
# それで１つ思いついたんだけど
line = "それで１つ思いついたんだけど"

[[dialogue]]
speaker = "ナナカ"
# 「おっ、なになに？」
line = "「おっ、なになに？」"

[[dialogue]]
speaker = "ナナカ"
# 「……夕霧庵でスウィーツ？　いやいや、うちはソバ屋なんだけど」
line = "「……夕霧庵でスウィーツ？　いやいや、うちはソバ屋なんだけど」"

[[dialogue]]
speaker = "フィオナ"
# 「お蕎麦屋さんでもスイーツを提供しているお店は多いと思いますよ」
line = "「お蕎麦屋さんでもスイーツを提供しているお店は多いと思いますよ」"

[[dialogue]]
speaker = "ナナカ"
# 「そうだけどっ、うちの職人はソバや丼ものを作るので手一杯だから、そんな余裕ないってば」
line = "「そうだけどっ、うちの職人はソバや丼ものを作るので手一杯だから、そんな余裕ないってば」"

[[dialogue]]
speaker = "unk"
# ナナカが作ればいいよ
line = "ナナカが作ればいいよ"

[[dialogue]]
speaker = "フィオナ"
# 「そうですね、ご自分でお蕎麦を打っているんですから、実家のお店で提供するスイーツを作ってもよさそうですが」
line = "「そうですね、ご自分でお蕎麦を打っているんですから、実家のお店で提供するスイーツを作ってもよさそうですが」"

[[dialogue]]
speaker = "ナナカ"
# 「うーん……でもアタシ、スウィーツは好きだけど、作るのは苦手なんだよね……」
line = "「うーん……でもアタシ、スウィーツは好きだけど、作るのは苦手なんだよね……」"

[[dialogue]]
speaker = "フィオナ"
# 「それこそ緋宮会長の腕の見せ所でしょう。ナナカさんにも簡単に作れて、お店の評判になるスイーツを考案すればいい話です」
line = "「それこそ緋宮会長の腕の見せ所でしょう。ナナカさんにも簡単に作れて、お店の評判になるスイーツを考案すればいい話です」"

[[dialogue]]
speaker = "ナナカ"
# 「なるほど！　そいつは名案だっ！」
line = "「なるほど！　そいつは名案だっ！」"

[[dialogue]]
speaker = "unk"
# こうして俺はナナカと協力して、夕霧庵の締めスイーツを考案することになった。
line = "こうして俺はナナカと協力して、夕霧庵の締めスイーツを考案することになった。"
