[[dialogue]]
speaker = "unk"
# 第１話,カーバンクル娘のルルゥ,P
line = "第１話,カーバンクル娘のルルゥ,P"

[[dialogue]]
speaker = "unk"
# カーバンクル娘のルルゥ──彼女がやってきたゲシュペンス島という名前には聞き覚えがあった。
line = "カーバンクル娘のルルゥ──彼女がやってきたゲシュペンス島という名前には聞き覚えがあった。"

[[dialogue]]
speaker = "unk"
# 以前、新星学園星徒会の副会長であるアナが、黒ベア子によって別世界に転移させられたことがあった。
line = "以前、新星学園星徒会の副会長であるアナが、黒ベア子によって別世界に転移させられたことがあった。"

[[dialogue]]
speaker = "unk"
# その時の島の名前がゲシュペンス島。
line = "その時の島の名前がゲシュペンス島。"

[[dialogue]]
speaker = "unk"
# 多種多様な種族の女の子がひとつの島に集まって生活している、実に興味深い場所だ、とアナは興奮気味に語っていた。
line = "多種多様な種族の女の子がひとつの島に集まって生活している、実に興味深い場所だ、とアナは興奮気味に語っていた。"

[[dialogue]]
speaker = "ルルゥ"
# 「おまたせ、なの♪」
line = "「おまたせ、なの♪」"

[[dialogue]]
speaker = "unk"
# 流星学園附属校の制服に着替えたルルゥが姿を現す。
line = "流星学園附属校の制服に着替えたルルゥが姿を現す。"

[[dialogue]]
speaker = "unk"
# これから学園内で一緒に行動する時、注目を浴びないようにと着替えてもらったのだが……
line = "これから学園内で一緒に行動する時、注目を浴びないようにと着替えてもらったのだが……"

[[dialogue]]
speaker = "unk"
# （附属校の制服も似合ってるし……）
line = "（附属校の制服も似合ってるし……）"

[[dialogue]]
speaker = "unk"
# （かわいい子だな……）
line = "（かわいい子だな……）"

[[dialogue]]
speaker = "ルルゥ"
# 「っ……！」
line = "「っ……！」"

[[dialogue]]
speaker = "マハムート"
# 「会長、レディをあまり無遠慮に見つめるものではないわ」
line = "「会長、レディをあまり無遠慮に見つめるものではないわ」"

[[dialogue]]
speaker = "unk"
# ルルゥの制服姿に見とれていると、マムこと<ruby=きりゅういん>妃竜院</ruby>マハムート先輩に注意されてしまう。
line = "ルルゥの制服姿に見とれていると、マムこと<ruby>妃竜院<rt>きりゅういん</rt></ruby>マハムート先輩に注意されてしまう。"

[[dialogue]]
speaker = "unk"
# ごめん、ルルゥ
line = "ごめん、ルルゥ"

[[dialogue]]
speaker = "unk"
# あ……
line = "あ……"

[[dialogue]]
speaker = "ルルゥ"
# 「お、思わず隠れちゃったなの……ルルゥもごめんなさいなの……」
line = "「お、思わず隠れちゃったなの……ルルゥもごめんなさいなの……」"

[[dialogue]]
speaker = "ルルゥ"
# 「会長さんは、いいニンゲンだから怖くないの！　マムさんに教わったから大丈夫なの！」
line = "「会長さんは、いいニンゲンだから怖くないの！　マムさんに教わったから大丈夫なの！」"

[[dialogue]]
speaker = "unk"
# と言いながらもマムの後ろに姿を隠していて、チラチラとこちらを覗くように見ている。
line = "と言いながらもマムの後ろに姿を隠していて、チラチラとこちらを覗くように見ている。"

[[dialogue]]
speaker = "unk"
# まだ警戒心は解けていない様子だ。
line = "まだ警戒心は解けていない様子だ。"

[[dialogue]]
speaker = "フィオナ"
# 「ルルゥさんは密猟者に狙われ続けてきたそうですね。そのせいでこんな風に人間を恐れるようになってしまったなんて……」
line = "「ルルゥさんは密猟者に狙われ続けてきたそうですね。そのせいでこんな風に人間を恐れるようになってしまったなんて……」"

[[dialogue]]
speaker = "フィオナ"
# 「学園には大勢の人がいます。黒ベア子さんの召喚した次の世界の案内人探しは私たちに任せて、ここで待っていてもらっても構わないんですよ？」
line = "「学園には大勢の人がいます。黒ベア子さんの召喚した次の世界の案内人探しは私たちに任せて、ここで待っていてもらっても構わないんですよ？」"

[[dialogue]]
speaker = "ルルゥ"
# 「大勢……そんなにたくさんのニンゲンがいる、なの……？　うぅぅ……」
line = "「大勢……そんなにたくさんのニンゲンがいる、なの……？　うぅぅ……」"

[[dialogue]]
speaker = "ルルゥ"
# 「で、でもルルゥも行く、なの！　どれだけニンゲンが居ても、マムさんの側なら平気なの！　ルルゥ頑張る、なの！」
line = "「で、でもルルゥも行く、なの！　どれだけニンゲンが居ても、マムさんの側なら平気なの！　ルルゥ頑張る、なの！」"

[[dialogue]]
speaker = "マハムート"
# 「なかなかいい意気込みね。あなたのことは私が守ってあげるから、しっかりついてくるのよ」
line = "「なかなかいい意気込みね。あなたのことは私が守ってあげるから、しっかりついてくるのよ」"

[[dialogue]]
speaker = "ルルゥ"
# 「はいなの！」
line = "「はいなの！」"

[[dialogue]]
speaker = "フィオナ"
# 「それでは掲示板で報告のあった女性が、黒ベア子さんが召喚したという人なのか確かめに行きましょう」
line = "「それでは掲示板で報告のあった女性が、黒ベア子さんが召喚したという人なのか確かめに行きましょう」"

[[dialogue]]
speaker = "ルルゥ"
# 「はわわわ……ほんとにいっぱいいる、なの……」
line = "「はわわわ……ほんとにいっぱいいる、なの……」"

[[dialogue]]
speaker = "unk"
# 校内を往来する学園生の数に、ルルゥの意気込みは早くも挫けていた。
line = "校内を往来する学園生の数に、ルルゥの意気込みは早くも挫けていた。"

[[dialogue]]
speaker = "unk"
# マムの後ろにしっかり隠れながら周囲のあちこちに不安げな視線を向けている。
line = "マムの後ろにしっかり隠れながら周囲のあちこちに不安げな視線を向けている。"

[[dialogue]]
speaker = "unk"
# ルルゥ、あれを見て
line = "ルルゥ、あれを見て"

[[dialogue]]
speaker = "ルルゥ"
# 「……？」
line = "「……？」"

[[dialogue]]
speaker = "魔族の星騎士"
# 「ねえねえ、これからみんなでどこか遊びに行かない？」
line = "「ねえねえ、これからみんなでどこか遊びに行かない？」"

[[dialogue]]
speaker = "人間の星騎士"
# 「いいね～、たまには自主練もお休みにして思いっきり羽をのばした～い♪」
line = "「いいね～、たまには自主練もお休みにして思いっきり羽をのばした～い♪」"

[[dialogue]]
speaker = "神族の星騎士"
# 「何がたまには、よ。あなたの場合、いっつも羽を伸ばしてばっかりじゃない」
line = "「何がたまには、よ。あなたの場合、いっつも羽を伸ばしてばっかりじゃない」"

[[dialogue]]
speaker = "人間の星騎士"
# 「も～、硬いこと言わないの！」
line = "「も～、硬いこと言わないの！」"

[[dialogue]]
speaker = "ルルゥ"
# 「……ニンゲンと……そうじゃないヒトとが、仲良くお話ししてます……」
line = "「……ニンゲンと……そうじゃないヒトとが、仲良くお話ししてます……」"

[[dialogue]]
speaker = "マハムート"
# 「ルルゥにとっては見慣れない光景かもしれないわね。けれど、ここではそれが当たり前なのよ」
line = "「ルルゥにとっては見慣れない光景かもしれないわね。けれど、ここではそれが当たり前なのよ」"

[[dialogue]]
speaker = "ルルゥ"
# 「不思議なの……」
line = "「不思議なの……」"

[[dialogue]]
speaker = "フィオナ"
# 「ルルゥさんの島ではどうして、人間とそれ以外の種族の方々が仲良くできていないのでしょうか？」
line = "「ルルゥさんの島ではどうして、人間とそれ以外の種族の方々が仲良くできていないのでしょうか？」"

[[dialogue]]
speaker = "ルルゥ"
# 「島にやってくるニンゲンの大半が、ルルゥたちのことを狙っている密猟者なの。密猟者はルルゥたちを見かけたら襲ってくる、なの」
line = "「島にやってくるニンゲンの大半が、ルルゥたちのことを狙っている密猟者なの。密猟者はルルゥたちを見かけたら襲ってくる、なの」"

[[dialogue]]
speaker = "ルルゥ"
# 「だから、ニンゲンには警戒しなくちゃいけないの。襲われる前にこっちから襲うって子もいる、なの」
line = "「だから、ニンゲンには警戒しなくちゃいけないの。襲われる前にこっちから襲うって子もいる、なの」"

[[dialogue]]
speaker = "ルルゥ"
# 「でも……こっちの世界には、悪いニンゲンはいないみたい、なの……とっても平和そうなの……」
line = "「でも……こっちの世界には、悪いニンゲンはいないみたい、なの……とっても平和そうなの……」"

[[dialogue]]
speaker = "マハムート"
# 「本当にそうなら良かったのだけれど……残念ながらこちらの世界にも、平和を乱す不埒者はいるわ。無論、私の目の黒いうちは学園に近寄らせたりしないけれど」
line = "「本当にそうなら良かったのだけれど……残念ながらこちらの世界にも、平和を乱す不埒者はいるわ。無論、私の目の黒いうちは学園に近寄らせたりしないけれど」"

[[dialogue]]
speaker = "フィオナ"
# 「この世界はこの世界で、外敵と呼べる存在が別にあります。それこそ世界の命運を揺るがすような脅威が」
line = "「この世界はこの世界で、外敵と呼べる存在が別にあります。それこそ世界の命運を揺るがすような脅威が」"

[[dialogue]]
speaker = "unk"
# そう──リクリエの脅威は一旦乗り越えたが、まだまだ不可解な事件は続いていて、気を抜くことはできない。
line = "そう──リクリエの脅威は一旦乗り越えたが、まだまだ不可解な事件は続いていて、気を抜くことはできない。"

[[dialogue]]
speaker = "unk"
# 世界の脅威はまだ取り去られてはいないのだ。
line = "世界の脅威はまだ取り去られてはいないのだ。"

[[dialogue]]
speaker = "unk"
# それらに立ち向かうのが星騎士であり、ここは星騎士を育成する学園なのだと、簡単にルルゥに説明する。
line = "それらに立ち向かうのが星騎士であり、ここは星騎士を育成する学園なのだと、簡単にルルゥに説明する。"

[[dialogue]]
speaker = "ルルゥ"
# 「それは、とっても大変そうなの……」
line = "「それは、とっても大変そうなの……」"

[[dialogue]]
speaker = "ルルゥ"
# 「でもマムさんがいるの！　マムさんはとっても強いから、マムさんがいれば大丈夫なの♪」
line = "「でもマムさんがいるの！　マムさんはとっても強いから、マムさんがいれば大丈夫なの♪」"

[[dialogue]]
speaker = "マハムート"
# 「ふふっ。私が強いのは当然として、私以外にもこの学園に集まった者は精鋭ぞろいよ」
line = "「ふふっ。私が強いのは当然として、私以外にもこの学園に集まった者は精鋭ぞろいよ」"

[[dialogue]]
speaker = "マハムート"
# 「特にそこの２人、まだまだ未熟なところはあるけれど、会長とフィオナはかなりの実力者よ」
line = "「特にそこの２人、まだまだ未熟なところはあるけれど、会長とフィオナはかなりの実力者よ」"

[[dialogue]]
speaker = "フィオナ"
# 「えっ？　嬉しいです……マムにそんな風に言っていただけるなんて」
line = "「えっ？　嬉しいです……マムにそんな風に言っていただけるなんて」"

[[dialogue]]
speaker = "unk"
# 光栄です
line = "光栄です"

[[dialogue]]
speaker = "ルルゥ"
# 「そうだった、なの！　会長さんはマムさんにも認められた、この学園のリーダーなの。つまりここで１番偉い人……」
line = "「そうだった、なの！　会長さんはマムさんにも認められた、この学園のリーダーなの。つまりここで１番偉い人……」"

[[dialogue]]
speaker = "ルルゥ"
# 「ルルゥ、尊敬なの……！」
line = "「ルルゥ、尊敬なの……！」"

[[dialogue]]
speaker = "unk"
# ちょっと恥ずかしいな……
line = "ちょっと恥ずかしいな……"

[[dialogue]]
speaker = "unk"
# そ、尊敬するとか言われると……
line = "そ、尊敬するとか言われると……"

[[dialogue]]
speaker = "マハムート"
# 「何を鼻の下を伸ばしているのかしら、会長？」
line = "「何を鼻の下を伸ばしているのかしら、会長？」"

[[dialogue]]
speaker = "unk"
# っ……！！
line = "っ……！！"

[[dialogue]]
speaker = "ルルゥ"
# 「あっ、ごめんなさい、なの！　ルルゥの『魅了』の力が働いてしまったみたい、なのっ」
line = "「あっ、ごめんなさい、なの！　ルルゥの『魅了』の力が働いてしまったみたい、なのっ」"

[[dialogue]]
speaker = "フィオナ"
# 「魅了ですか？」
line = "「魅了ですか？」"

[[dialogue]]
speaker = "マハムート"
# 「これは秘密にしておいてほしいのだけれど、ルルゥはその特性として、魅了の力を持っているわ」
line = "「これは秘密にしておいてほしいのだけれど、ルルゥはその特性として、魅了の力を持っているわ」"

[[dialogue]]
speaker = "フィオナ"
# 「もしかしてルルゥさんが密猟者に特に狙われている理由はそれですか？」
line = "「もしかしてルルゥさんが密猟者に特に狙われている理由はそれですか？」"

[[dialogue]]
speaker = "ルルゥ"
# 「……はい、なの」
line = "「……はい、なの」"

[[dialogue]]
speaker = "マハムート"
# 「ゲシュペンス島でもこの能力は希少なようね。手に入れて悪事を企む者はいくらでもいるでしょう」
line = "「ゲシュペンス島でもこの能力は希少なようね。手に入れて悪事を企む者はいくらでもいるでしょう」"

[[dialogue]]
speaker = "ルルゥ"
# 「ルルゥはこの力を上手く制御できないの……だから、そのつもりがなくても、今みたいに魅了してしまうことがある、なの……」
line = "「ルルゥはこの力を上手く制御できないの……だから、そのつもりがなくても、今みたいに魅了してしまうことがある、なの……」"

[[dialogue]]
speaker = "ルルゥ"
# 「会長さん、本当にごめんなさい、なの」
line = "「会長さん、本当にごめんなさい、なの」"

[[dialogue]]
speaker = "unk"
# 今はもう大丈夫だから
line = "今はもう大丈夫だから"

[[dialogue]]
speaker = "unk"
# 不可抗力なら仕方ない
line = "不可抗力なら仕方ない"

[[dialogue]]
speaker = "マハムート"
# 「何も大丈夫ではないわ。こんなに簡単に魅了されてしまうなんて、まだまだ精神修行が足りないようね」
line = "「何も大丈夫ではないわ。こんなに簡単に魅了されてしまうなんて、まだまだ精神修行が足りないようね」"

[[dialogue]]
speaker = "マハムート"
# 「後で１から鍛え直してあげるから、覚悟しておきなさい」
line = "「後で１から鍛え直してあげるから、覚悟しておきなさい」"

[[dialogue]]
speaker = "unk"
# マムに鍛えてもらうと成長も出来るのだけど、苛烈過ぎるその修行はまさに命がけのものだ。
line = "マムに鍛えてもらうと成長も出来るのだけど、苛烈過ぎるその修行はまさに命がけのものだ。"

[[dialogue]]
speaker = "unk"
# 特に今回は厳しい修行になる……なぜかそんな予感がして、心が曇ってしまうのだった。
line = "特に今回は厳しい修行になる……なぜかそんな予感がして、心が曇ってしまうのだった。"
