[[dialogue]]
speaker = "リィベル"
# 「服を脱ぎなさい、魔王」
line = "「服を脱ぎなさい、魔王」"

[[dialogue]]
speaker = "unk"
# 一度、勢いで体を重ねてからというもの、リィベルは発情する度にセックスをねだるようになってしまった。
line = "一度、勢いで体を重ねてからというもの、リィベルは発情する度にセックスをねだるようになってしまった。"

[[dialogue]]
speaker = "unk"
# タイミングはリィベル次第で、ムードも何もあったもんじゃない。
line = "タイミングはリィベル次第で、ムードも何もあったもんじゃない。"

[[dialogue]]
speaker = "クロト"
# 「また？」
line = "「また？」"

[[dialogue]]
speaker = "リィベル"
# 「また、じゃないわよ。あなたが私にセックスの快感を教えたんだから、責任を取りなさい。でないと暴れるわよ」
line = "「また、じゃないわよ。あなたが私にセックスの快感を教えたんだから、責任を取りなさい。でないと暴れるわよ」"

[[dialogue]]
speaker = "クロト"
# （めちゃくちゃな脅迫だ）
line = "（めちゃくちゃな脅迫だ）"

[[dialogue]]
speaker = "クロト"
# 「俺はいいけど、リィベルは大丈夫なのか？　妊娠とか……」
line = "「俺はいいけど、リィベルは大丈夫なのか？　妊娠とか……」"

[[dialogue]]
speaker = "リィベル"
# 「竜の魔族ってなかなか孕まないらしいから大丈夫よ。だから生でしてあげるわ。好きでしょ？　生中出しセックス」
line = "「竜の魔族ってなかなか孕まないらしいから大丈夫よ。だから生でしてあげるわ。好きでしょ？　生中出しセックス」"

[[dialogue]]
speaker = "クロト"
# 「っ……そりゃ好きだけどさ」
line = "「っ……そりゃ好きだけどさ」"

[[dialogue]]
speaker = "unk"
# リィベルはエロ漫画で覚えた言葉で俺を挑発してくる。だけど結果はいつも……
line = "リィベルはエロ漫画で覚えた言葉で俺を挑発してくる。だけど結果はいつも……"

[[dialogue]]
speaker = "リィベル"
# 「今日はこっちでしてあげる。好きなんでしょ、これ。ほら、早く寝っ転がりなさい」
line = "「今日はこっちでしてあげる。好きなんでしょ、これ。ほら、早く寝っ転がりなさい」"

[[dialogue]]
speaker = "unk"
# 言われるがまま、俺は服を脱いでベッドに横になった──
line = "言われるがまま、俺は服を脱いでベッドに横になった──"

[[dialogue]]
speaker = "リィベル"
# 「ふふっ、いい様ね」
line = "「ふふっ、いい様ね」"

[[dialogue]]
speaker = "unk"
# 服をはだけたリィベルが俺の上にまたがる。控えめなおっぱいと、これまた控えめな乳首が可愛らしい。
line = "服をはだけたリィベルが俺の上にまたがる。控えめなおっぱいと、これまた控えめな乳首が可愛らしい。"

[[dialogue]]
speaker = "リィベル"
# 「今日は私があなたを鳴かせてあげる。覚悟はいいかしら？」
line = "「今日は私があなたを鳴かせてあげる。覚悟はいいかしら？」"

[[dialogue]]
speaker = "クロト"
# 「覚悟、ね……」
line = "「覚悟、ね……」"

[[dialogue]]
speaker = "unk"
# その自信がどこから来るのだろうか。ちょっと俺には分からない。
line = "その自信がどこから来るのだろうか。ちょっと俺には分からない。"

[[dialogue]]
speaker = "リィベル"
# 「何よ。余裕こいていられるのも今のうちよ」
line = "「何よ。余裕こいていられるのも今のうちよ」"

[[dialogue]]
speaker = "リィベル"
# 「一滴残らず精液搾り取って、エロ漫画みたいに『もう出ない～』って言わせてやるわ。もうちん負け雑魚ま○ことは言わせないんだから」
line = "「一滴残らず精液搾り取って、エロ漫画みたいに『もう出ない～』って言わせてやるわ。もうちん負け雑魚ま○ことは言わせないんだから」"

[[dialogue]]
speaker = "クロト"
# 「いや、言った覚えないんだけど」
line = "「いや、言った覚えないんだけど」"

[[dialogue]]
speaker = "リィベル"
# 「ふん。上の口でなんと言おうと、下半身は正直ね。私の中に入りたくて、おち○ぽバキバキじゃない。でも、まだ挿れてあげない」
line = "「ふん。上の口でなんと言おうと、下半身は正直ね。私の中に入りたくて、おち○ぽバキバキじゃない。でも、まだ挿れてあげない」"

[[dialogue]]
speaker = "リィベル"
# 「ほら……すり、すり……<emoji=heart04>　おち○ぽ、待ちきれなくてビクビクしてるわ。このまま射精してもいいのよ？　早漏魔王って呼んであげる」
line = "「ほら……すり、すり……<emoji=heart04>　おち○ぽ、待ちきれなくてビクビクしてるわ。このまま射精してもいいのよ？　早漏魔王って呼んであげる」"

[[dialogue]]
speaker = "リィベル"
# 「あっ<emoji=heart04>　分かる？　今、先っぽがおま○この入り口に当たってるわ」
line = "「あっ<emoji=heart04>　分かる？　今、先っぽがおま○この入り口に当たってるわ」"

[[dialogue]]
speaker = "unk"
# リィベルから溢れた蜜が俺のペニスを濡らしていて、言われなくても発情具合が伝わってくる。
line = "リィベルから溢れた蜜が俺のペニスを濡らしていて、言われなくても発情具合が伝わってくる。"

[[dialogue]]
speaker = "リィベル"
# 「さぁ、挿れるわよ。いい声で喘ぎなさい」
line = "「さぁ、挿れるわよ。いい声で喘ぎなさい」"

[[dialogue]]
speaker = "リィベル"
# 「ん、んん～～～～～っ<emoji=heart04><emoji=heart04>」
line = "「ん、んん～～～～～っ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 声にならない叫びを上げ、小刻みに震えるリィベル。
line = "声にならない叫びを上げ、小刻みに震えるリィベル。"

[[dialogue]]
speaker = "unk"
# 愛液で潤っていても、膣はぎちぎちに締め付けてきて強い快感が走る。
line = "愛液で潤っていても、膣はぎちぎちに締め付けてきて強い快感が走る。"

[[dialogue]]
speaker = "リィベル"
# 「ど、どうかしら？　私の、おま○こに屈する気になった……？」
line = "「ど、どうかしら？　私の、おま○こに屈する気になった……？」"

[[dialogue]]
speaker = "unk"
# 屈するも何もまだ挿れたばかりだ。どう答えるか迷っていると……
line = "屈するも何もまだ挿れたばかりだ。どう答えるか迷っていると……"

[[dialogue]]
speaker = "リィベル"
# 「ふー……ふー……言葉も、出ないようね」
line = "「ふー……ふー……言葉も、出ないようね」"

[[dialogue]]
speaker = "クロト"
# 「……まだ動かないでくれ。リィベルの中、気持ちよすぎてすぐ射精しそうだ」
line = "「……まだ動かないでくれ。リィベルの中、気持ちよすぎてすぐ射精しそうだ」"

[[dialogue]]
speaker = "リィベル"
# 「んんっ……ずいぶん可愛いことを言うのね、魔王のくせに。救世の英雄とはいえ、おち○ぽは普通の人間ね」
line = "「んんっ……ずいぶん可愛いことを言うのね、魔王のくせに。救世の英雄とはいえ、おち○ぽは普通の人間ね」"

[[dialogue]]
speaker = "リィベル"
# 「でも……ダメよ。ん、今日は、あなたが……鳴く番だって言ったでしょ」
line = "「でも……ダメよ。ん、今日は、あなたが……鳴く番だって言ったでしょ」"

[[dialogue]]
speaker = "クロト"
# 「そんな……くっ」
line = "「そんな……くっ」"

[[dialogue]]
speaker = "unk"
# 強気なリィベルが可愛くて、つい乗ってしまう。
line = "強気なリィベルが可愛くて、つい乗ってしまう。"

[[dialogue]]
speaker = "リィベル"
# 「ふふっ……そんなに、ん、惨めな顔をしないで、ちょうだい。これからいっぱい気持ちよくして、あげ、る……ふー……」
line = "「ふふっ……そんなに、ん、惨めな顔をしないで、ちょうだい。これからいっぱい気持ちよくして、あげ、る……ふー……」"

[[dialogue]]
speaker = "unk"
# 俺の頬に触れながら微笑むリィベル。いつの間にか乳首もつんと尖っていて、余裕はすでになさそうだけど……
line = "俺の頬に触れながら微笑むリィベル。いつの間にか乳首もつんと尖っていて、余裕はすでになさそうだけど……"

[[dialogue]]
speaker = "リィベル"
# 「ふー……ふー……観念しなさい。動くわよ……」
line = "「ふー……ふー……観念しなさい。動くわよ……」"

[[dialogue]]
speaker = "リィベル"
# 「んん～～～～～～～～～～～っ<emoji=heart04>」
line = "「んん～～～～～～～～～～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「はぁ、あああ、んんっ<emoji=heart04>　魔王のおち○ぽ、おっきいっ<emoji=heart04>」
line = "「はぁ、あああ、んんっ<emoji=heart04>　魔王のおち○ぽ、おっきいっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ついに腰を動かし始め、熱い粘膜がペニスと摩擦して快感を生み出す。
line = "ついに腰を動かし始め、熱い粘膜がペニスと摩擦して快感を生み出す。"

[[dialogue]]
speaker = "リィベル"
# 「ふ、はぁ、あああっ<emoji=heart04>　ふっ……どう？　もう射精しちゃいそう？」
line = "「ふ、はぁ、あああっ<emoji=heart04>　ふっ……どう？　もう射精しちゃいそう？」"

[[dialogue]]
speaker = "クロト"
# 「まだだ。耐えて、みせる……」
line = "「まだだ。耐えて、みせる……」"

[[dialogue]]
speaker = "リィベル"
# 「そう、ね。んっ……少し動いたくらいで根を上げられたら、私も溜飲が下がらないわ」
line = "「そう、ね。んっ……少し動いたくらいで根を上げられたら、私も溜飲が下がらないわ」"

[[dialogue]]
speaker = "リィベル"
# 「今日のために、あなたの本棚から女性上位モノのエロ漫画を探して読み込んだんだもの」
line = "「今日のために、あなたの本棚から女性上位モノのエロ漫画を探して読み込んだんだもの」"

[[dialogue]]
speaker = "リィベル"
# 「ふふっ……英雄なのに、意外な趣味ね。こうやって、んっ、女にいいようにされるのが、好きだったの？」
line = "「ふふっ……英雄なのに、意外な趣味ね。こうやって、んっ、女にいいようにされるのが、好きだったの？」"

[[dialogue]]
speaker = "リィベル"
# 「ん、んんっ<emoji=heart04>　ああ、あ、はぁ……<emoji=heart04>　おち○ぽ、ビクビクして、るっ<emoji=heart04>」
line = "「ん、んんっ<emoji=heart04>　ああ、あ、はぁ……<emoji=heart04>　おち○ぽ、ビクビクして、るっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「いいわよ……いっぱい感じて、気持ちよくなりなさい。いくら我慢しても、最後にはみっともなく射精させてあげる」
line = "「いいわよ……いっぱい感じて、気持ちよくなりなさい。いくら我慢しても、最後にはみっともなく射精させてあげる」"

[[dialogue]]
speaker = "リィベル"
# 「白くてねばねばの精液、私の子宮に出したいんでしょう？　いくらでも出していいのよ<emoji=heart04>」
line = "「白くてねばねばの精液、私の子宮に出したいんでしょう？　いくらでも出していいのよ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「びゅ～～って出しなさいよっ<emoji=heart04>　ほらっ<emoji=heart04>」
line = "「びゅ～～って出しなさいよっ<emoji=heart04>　ほらっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「はぁ、んっ<emoji=heart04>　精液、出しちゃいなさいっ<emoji=heart04>　早漏魔王って呼んであげるっ<emoji=heart04>　よく射精できたわねって、頭なでて、褒めて、あげるっ<emoji=heart04>」
line = "「はぁ、んっ<emoji=heart04>　精液、出しちゃいなさいっ<emoji=heart04>　早漏魔王って呼んであげるっ<emoji=heart04>　よく射精できたわねって、頭なでて、褒めて、あげるっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 奥歯を食いしばって責めに耐える。下では物理的な快楽が、上では囁く声が俺の意地を溶かそうとしてくる。
line = "奥歯を食いしばって責めに耐える。下では物理的な快楽が、上では囁く声が俺の意地を溶かそうとしてくる。"

[[dialogue]]
speaker = "リィベル"
# 「あっ<emoji=heart04>　ん、んんっ<emoji=heart04>　まだ、耐えるの、ねっ<emoji=heart04>」
line = "「あっ<emoji=heart04>　ん、んんっ<emoji=heart04>　まだ、耐えるの、ねっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「いいわ……なら、私も本気を出すまでよ……<emoji=heart04>」
line = "「いいわ……なら、私も本気を出すまでよ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「本気だって……？」
line = "「本気だって……？」"

[[dialogue]]
speaker = "unk"
# これまでは本気じゃなかったっていうのか。リィベルを見くびりすぎていたかもしれない。
line = "これまでは本気じゃなかったっていうのか。リィベルを見くびりすぎていたかもしれない。"

[[dialogue]]
speaker = "リィベル"
# 「ほら、とくと味わいなさい……んん、んんん──ッ<emoji=heart04>」
line = "「ほら、とくと味わいなさい……んん、んんん──ッ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# リィベルの腰が深く沈み、同時に強く膣が締まる。痛いくらいの締め付けに、一瞬、漏らしそうになった。
line = "リィベルの腰が深く沈み、同時に強く膣が締まる。痛いくらいの締め付けに、一瞬、漏らしそうになった。"

[[dialogue]]
speaker = "リィベル"
# 「はっ、んっ……<emoji=heart04>　下半身に力を込めて、おま○こ締めてみたわ。これは、ん、効くでしょう？」
line = "「はっ、んっ……<emoji=heart04>　下半身に力を込めて、おま○こ締めてみたわ。これは、ん、効くでしょう？」"

[[dialogue]]
speaker = "リィベル"
# 「んん──ん、んん、んッ<emoji=heart04>　はぁはっ……んんッ<emoji=heart04>」
line = "「んん──ん、んん、んッ<emoji=heart04>　はぁはっ……んんッ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# リィベルが力を込める度、ぎゅっぎゅっと締まって、文字通り搾り取ろうとしてくる。
line = "リィベルが力を込める度、ぎゅっぎゅっと締まって、文字通り搾り取ろうとしてくる。"

[[dialogue]]
speaker = "リィベル"
# 「どう？　ちゃんと練習したんだから……早く精液出しな、さいっ……んっ<emoji=heart04>」
line = "「どう？　ちゃんと練習したんだから……早く精液出しな、さいっ……んっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「くっ、うぅっ……練習？　どうやって……？」
line = "「くっ、うぅっ……練習？　どうやって……？」"

[[dialogue]]
speaker = "unk"
# 無視するには大きすぎる疑問で、思わず口に出ていた。
line = "無視するには大きすぎる疑問で、思わず口に出ていた。"

[[dialogue]]
speaker = "リィベル"
# 「どうって…………しっぽの先をおま○こに挿れて、おへその下に力入れて……って、何を言わせるのよ」
line = "「どうって…………しっぽの先をおま○こに挿れて、おへその下に力入れて……って、何を言わせるのよ」"

[[dialogue]]
speaker = "クロト"
# 「しっぽ、硬そうだけど痛くなかった？」
line = "「しっぽ、硬そうだけど痛くなかった？」"

[[dialogue]]
speaker = "リィベル"
# 「え？　ちゃんと濡らせば大丈夫だったけど……だから言わせないでってばっ」
line = "「え？　ちゃんと濡らせば大丈夫だったけど……だから言わせないでってばっ」"

[[dialogue]]
speaker = "クロト"
# 「それはもうただのオナニーじゃ……」
line = "「それはもうただのオナニーじゃ……」"

[[dialogue]]
speaker = "リィベル"
# 「このっ、ばかっ……余計なこと考えないで、さっさと、射精、しなさい、よ……んん、んっ<emoji=heart04>」
line = "「このっ、ばかっ……余計なこと考えないで、さっさと、射精、しなさい、よ……んん、んっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 考えるななんて、そんなの無理だ。おま○こを締める練習と称してしっぽオナニーしてただなんて可愛すぎる。
line = "考えるななんて、そんなの無理だ。おま○こを締める練習と称してしっぽオナニーしてただなんて可愛すぎる。"

[[dialogue]]
speaker = "unk"
# リィベルの痴態を想像して、けど、想像するしかない悔しさがこみ上げてきて──
line = "リィベルの痴態を想像して、けど、想像するしかない悔しさがこみ上げてきて──"

[[dialogue]]
speaker = "リィベル"
# 「ひああぁ～～～～～～～～～～っ<emoji=heart04><emoji=heart04>」
line = "「ひああぁ～～～～～～～～～～っ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「うそっ！？　んぁっ<emoji=heart04>　あんっ<emoji=heart04>　下から、突き上げられて、からだ、浮いちゃうっ<emoji=heart04>」
line = "「うそっ！？　んぁっ<emoji=heart04>　あんっ<emoji=heart04>　下から、突き上げられて、からだ、浮いちゃうっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 気が付けば、がむしゃらに腰を振っていた。この感情の昂りをリィベルのおま○こに直接ぶつけてやる。
line = "気が付けば、がむしゃらに腰を振っていた。この感情の昂りをリィベルのおま○こに直接ぶつけてやる。"

[[dialogue]]
speaker = "リィベル"
# 「んあ、あっ<emoji=heart04>　ああぁっ<emoji=heart04>　あ、あ、あああっ──ふあぁ～～～～っ<emoji=heart04>」
line = "「んあ、あっ<emoji=heart04>　ああぁっ<emoji=heart04>　あ、あ、あああっ──ふあぁ～～～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「あなた、もう限界のはずじゃ……ああんっ<emoji=heart04>　ひやぁあっ<emoji=heart04>　あっ<emoji=heart04>　んん～っ<emoji=heart04>」
line = "「あなた、もう限界のはずじゃ……ああんっ<emoji=heart04>　ひやぁあっ<emoji=heart04>　あっ<emoji=heart04>　んん～っ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「それはリィベルも、だろ……！」
line = "「それはリィベルも、だろ……！」"

[[dialogue]]
speaker = "unk"
# 俺もほとんど理性が焼き切れそうだ。
line = "俺もほとんど理性が焼き切れそうだ。"

[[dialogue]]
speaker = "unk"
# だけどそれは向こうも一緒のはず。その証拠に愛液で互いの下半身がびしょびしょだ。
line = "だけどそれは向こうも一緒のはず。その証拠に愛液で互いの下半身がびしょびしょだ。"

[[dialogue]]
speaker = "unk"
# こうなったら、イかされる前にイかせてやる。
line = "こうなったら、イかされる前にイかせてやる。"

[[dialogue]]
speaker = "クロト"
# 「俺も本気を見せてやるっ！」
line = "「俺も本気を見せてやるっ！」"

[[dialogue]]
speaker = "リィベル"
# 「ふあ、あ、あぁっ<emoji=heart04>　おち○ぽ、ゴリゴリって、私の中で、暴れてるっ<emoji=heart04>　ひぃっ<emoji=heart04>」
line = "「ふあ、あ、あぁっ<emoji=heart04>　おち○ぽ、ゴリゴリって、私の中で、暴れてるっ<emoji=heart04>　ひぃっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「やぁっ<emoji=heart04>　そこ、だめっ<emoji=heart04>　私の、子宮、力任せに叩かないでぇっ<emoji=heart04>」
line = "「やぁっ<emoji=heart04>　そこ、だめっ<emoji=heart04>　私の、子宮、力任せに叩かないでぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「ひぃん<emoji=heart04>　待って、待ってってばっ<emoji=heart04>　あっ、あっ、ああぁっ<emoji=heart04>　はぁっ、ああぁんっ<emoji=heart04>」
line = "「ひぃん<emoji=heart04>　待って、待ってってばっ<emoji=heart04>　あっ、あっ、ああぁっ<emoji=heart04>　はぁっ、ああぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# リィベルの体は小さくて、簡単に奥まで届く。
line = "リィベルの体は小さくて、簡単に奥まで届く。"

[[dialogue]]
speaker = "unk"
# 子宮の入り口を亀頭でこじ開けるつもりで何度もノックする。
line = "子宮の入り口を亀頭でこじ開けるつもりで何度もノックする。"

[[dialogue]]
speaker = "リィベル"
# 「ふゃああ<emoji=heart04>　あっ<emoji=heart04>　私の、おま○こ、壊れて、ばかになっちゃったっ<emoji=heart04>　ふぁあっ<emoji=heart04>　あんっ<emoji=heart04>」
line = "「ふゃああ<emoji=heart04>　あっ<emoji=heart04>　私の、おま○こ、壊れて、ばかになっちゃったっ<emoji=heart04>　ふぁあっ<emoji=heart04>　あんっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「乱暴に<emoji=heart04>　あ<emoji=heart04>　おち○ぽで、ごしごし擦られただけで気持ちよくなるっ<emoji=heart04>　何も考えられなくなりゅっ<emoji=heart04>」
line = "「乱暴に<emoji=heart04>　あ<emoji=heart04>　おち○ぽで、ごしごし擦られただけで気持ちよくなるっ<emoji=heart04>　何も考えられなくなりゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「おち○ぽに屈する気になった？」
line = "「おち○ぽに屈する気になった？」"

[[dialogue]]
speaker = "リィベル"
# 「屈するっ<emoji=heart04>　屈しちゃうっ<emoji=heart04>　屈するからいっぱいおち○ぽ突いてぇっ<emoji=heart04>」
line = "「屈するっ<emoji=heart04>　屈しちゃうっ<emoji=heart04>　屈するからいっぱいおち○ぽ突いてぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「ごめんなさい、淫乱雑魚ま○こでごめんなさいぃ<emoji=heart04>」
line = "「ごめんなさい、淫乱雑魚ま○こでごめんなさいぃ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「おち○ぽ、おち○ぽ、おち○ぽ<emoji=heart04>　おち○ぽしゅきなのっ<emoji=heart04>　おま○こされるのしゅきなのぉっ<emoji=heart04>」
line = "「おち○ぽ、おち○ぽ、おち○ぽ<emoji=heart04>　おち○ぽしゅきなのっ<emoji=heart04>　おま○こされるのしゅきなのぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# すっかりスイッチの入ったリィベルをもっと刺激したくて、胸に手を伸ばした。
line = "すっかりスイッチの入ったリィベルをもっと刺激したくて、胸に手を伸ばした。"

[[dialogue]]
speaker = "リィベル"
# 「やぁっ<emoji=heart04>　ちくび、やぁっ<emoji=heart04>　ちくび、いぢめないでぇっ<emoji=heart04>」
line = "「やぁっ<emoji=heart04>　ちくび、やぁっ<emoji=heart04>　ちくび、いぢめないでぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 硬く尖った乳首を潰すように摘まんで、くりくりと弄ぶ。
line = "硬く尖った乳首を潰すように摘まんで、くりくりと弄ぶ。"

[[dialogue]]
speaker = "unk"
# その度にリィベルの脚ががくがくと揺れ、膣内がきゅっと嬉しそうに締まった。
line = "その度にリィベルの脚ががくがくと揺れ、膣内がきゅっと嬉しそうに締まった。"

[[dialogue]]
speaker = "リィベル"
# 「ふやぁっ<emoji=heart04>　ちくび、ひっぱらないでっ<emoji=heart04>　やっ、のびない、おっぱいのびないからぁっ<emoji=heart04>」
line = "「ふやぁっ<emoji=heart04>　ちくび、ひっぱらないでっ<emoji=heart04>　やっ、のびない、おっぱいのびないからぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# リィベルの可愛い顔を引き寄せ、唇を奪う。
line = "リィベルの可愛い顔を引き寄せ、唇を奪う。"

[[dialogue]]
speaker = "リィベル"
# 「んんんっ！？」
line = "「んんんっ！？」"

[[dialogue]]
speaker = "unk"
# 間髪入れず、小さな口に躊躇なく舌をねじ込む。
line = "間髪入れず、小さな口に躊躇なく舌をねじ込む。"

[[dialogue]]
speaker = "リィベル"
# 「んふぅっ<emoji=heart04>　んじゅるっ、ちゅぱっ<emoji=heart04>　じゅ、ちゅるるっちゅるっ……ちゅっ、んちゅぱっ<emoji=heart04>」
line = "「んふぅっ<emoji=heart04>　んじゅるっ、ちゅぱっ<emoji=heart04>　じゅ、ちゅるるっちゅるっ……ちゅっ、んちゅぱっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「んちゅっ<emoji=heart04>　ちゅるるっちゅっ……じゅるるっ<emoji=heart04>　ちゅるりろっ<emoji=heart04>　んぱっ<emoji=heart04>」
line = "「んちゅっ<emoji=heart04>　ちゅるるっちゅっ……じゅるるっ<emoji=heart04>　ちゅるりろっ<emoji=heart04>　んぱっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 付き合ってもいないのにセックスだけしているから、キスもセックスの間だけだ。なら、今のうちに好きにさせてもらう。
line = "付き合ってもいないのにセックスだけしているから、キスもセックスの間だけだ。なら、今のうちに好きにさせてもらう。"

[[dialogue]]
speaker = "リィベル"
# 「じゅるるるっ<emoji=heart04>　んじゅる、ちゅぱ<emoji=heart04>　んちゅぱちゅるるっ<emoji=heart04>　じゅるちゅっ<emoji=heart04>」
line = "「じゅるるるっ<emoji=heart04>　んじゅる、ちゅぱ<emoji=heart04>　んちゅぱちゅるるっ<emoji=heart04>　じゅるちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 快感にうっとりしたリィベルの顔が目の前にあって、それを歪ませたい。もっと快楽で染め上げたい。
line = "快感にうっとりしたリィベルの顔が目の前にあって、それを歪ませたい。もっと快楽で染め上げたい。"

[[dialogue]]
speaker = "リィベル"
# 「おち○ぽ、暴れてりゅ<emoji=heart04>　はぁ、あ、あっ<emoji=heart04>　ズンズンきてるっ<emoji=heart04>　子宮、ぶっ叩かれてりゅ<emoji=heart04>」
line = "「おち○ぽ、暴れてりゅ<emoji=heart04>　はぁ、あ、あっ<emoji=heart04>　ズンズンきてるっ<emoji=heart04>　子宮、ぶっ叩かれてりゅ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「ひぃああぁっ<emoji=heart04>　あっ<emoji=heart04>　ふぅ、あ、あぁっ<emoji=heart04>　あひ、ひぃんっ<emoji=heart04>　んやぁ～～～っ<emoji=heart04>」
line = "「ひぃああぁっ<emoji=heart04>　あっ<emoji=heart04>　ふぅ、あ、あぁっ<emoji=heart04>　あひ、ひぃんっ<emoji=heart04>　んやぁ～～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# リィベルの切羽詰まった鳴き声に射精欲がこみ上げてくる。細い腰を掴んで、ラストスパートをかける。
line = "リィベルの切羽詰まった鳴き声に射精欲がこみ上げてくる。細い腰を掴んで、ラストスパートをかける。"

[[dialogue]]
speaker = "リィベル"
# 「ふあああっ<emoji=heart04>　あっ、ひあ、ああっ<emoji=heart04>　ひぃ、ふあ、あ<emoji=heart04>　あ、あん、ひあっ<emoji=heart04>」
line = "「ふあああっ<emoji=heart04>　あっ、ひあ、ああっ<emoji=heart04>　ひぃ、ふあ、あ<emoji=heart04>　あ、あん、ひあっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「おち○ぽ、ビクビクしてりゅっ<emoji=heart04>　しゃせー<emoji=heart04>　しゃせーされちゃうのぉっ<emoji=heart04>」
line = "「おち○ぽ、ビクビクしてりゅっ<emoji=heart04>　しゃせー<emoji=heart04>　しゃせーされちゃうのぉっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「あついのくりゅ<emoji=heart04>　あっついせーえききちゃう<emoji=heart04>　きてきてぇ<emoji=heart04>　せーえききてぇっ<emoji=heart04>」
line = "「あついのくりゅ<emoji=heart04>　あっついせーえききちゃう<emoji=heart04>　きてきてぇ<emoji=heart04>　せーえききてぇっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「ひぁああっ<emoji=heart04>　あついの、きてっ<emoji=heart04>　イクっ<emoji=heart04>　イクっ<emoji=heart04>　わたしもおま○こイっちゃぅっ<emoji=heart04>」
line = "「ひぁああっ<emoji=heart04>　あついの、きてっ<emoji=heart04>　イクっ<emoji=heart04>　イクっ<emoji=heart04>　わたしもおま○こイっちゃぅっ<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「んぁ、あ、あ、あ、あぁ～っ<emoji=heart04>　あひぃっ<emoji=heart04>　イクぅっ<emoji=heart04>　おま○こイクっ<emoji=heart04>　イッっくぅ～～～～っ<emoji=heart04><emoji=heart04>」
line = "「んぁ、あ、あ、あ、あぁ～っ<emoji=heart04>　あひぃっ<emoji=heart04>　イクぅっ<emoji=heart04>　おま○こイクっ<emoji=heart04>　イッっくぅ～～～～っ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「んひゃあああああああ～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「んひゃあああああああ～～～～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「ん、んんっ<emoji=heart04>　ひあ、ああ～<emoji=heart04>　おち○ぽ、おなかのなかであばれてりゅりゅぅ<emoji=heart04>　あついぃ、せーえきあっついのぉ<emoji=heart04>」
line = "「ん、んんっ<emoji=heart04>　ひあ、ああ～<emoji=heart04>　おち○ぽ、おなかのなかであばれてりゅりゅぅ<emoji=heart04>　あついぃ、せーえきあっついのぉ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# リィベルの子宮口に亀頭を押し付けながら射精する。なかなか孕まないと言われても、本能はそれを目指していた。
line = "リィベルの子宮口に亀頭を押し付けながら射精する。なかなか孕まないと言われても、本能はそれを目指していた。"

[[dialogue]]
speaker = "リィベル"
# 「びゅ～って、びゅ～ってせーえききてりゅ<emoji=heart04>　は、あ、ふわぁ～<emoji=heart04>　おなかいっぱい、あったかいのぉ……きもちい<emoji=heart04>　おま○こしあわせぇ……<emoji=heart04>」
line = "「びゅ～って、びゅ～ってせーえききてりゅ<emoji=heart04>　は、あ、ふわぁ～<emoji=heart04>　おなかいっぱい、あったかいのぉ……きもちい<emoji=heart04>　おま○こしあわせぇ……<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「もっと、もっとせえーき出してぇ<emoji=heart04>　ぎゅってしてあげるからぁ<emoji=heart04>　ん、んんんっ<emoji=heart04>」
line = "「もっと、もっとせえーき出してぇ<emoji=heart04>　ぎゅってしてあげるからぁ<emoji=heart04>　ん、んんんっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 一滴残らず搾り取ろうと、リィベルが膣を絞める。俺もそれに応えて、痛いくらいに射精する。
line = "一滴残らず搾り取ろうと、リィベルが膣を絞める。俺もそれに応えて、痛いくらいに射精する。"

[[dialogue]]
speaker = "リィベル"
# 「はぁ、ん、ぬけちゃっ……<emoji=heart04>」
line = "「はぁ、ん、ぬけちゃっ……<emoji=heart04>」"

[[dialogue]]
speaker = "リィベル"
# 「ふー、はー……はぁ、はぁ………ふぅ、はぁ…………」
line = "「ふー、はー……はぁ、はぁ………ふぅ、はぁ…………」"

[[dialogue]]
speaker = "unk"
# ペニスが抜けると、どぼっと精液の塊が膣からこぼれてきた。
line = "ペニスが抜けると、どぼっと精液の塊が膣からこぼれてきた。"

[[dialogue]]
speaker = "unk"
# 自分でも驚くぐらいリィベルの中に射精していたようだ。
line = "自分でも驚くぐらいリィベルの中に射精していたようだ。"

[[dialogue]]
speaker = "リィベル"
# 「うぅ……またちん負けしたぁ……我を忘れてサカって、バカみたい……」
line = "「うぅ……またちん負けしたぁ……我を忘れてサカって、バカみたい……」"

[[dialogue]]
speaker = "クロト"
# 「そんなことないよ。いっぱい感じてくれて可愛かった」
line = "「そんなことないよ。いっぱい感じてくれて可愛かった」"

[[dialogue]]
speaker = "リィベル"
# 「ふんっ……どうせあなたも、雑魚まんドラゴンだと思ってるんでしょ」
line = "「ふんっ……どうせあなたも、雑魚まんドラゴンだと思ってるんでしょ」"

[[dialogue]]
speaker = "unk"
# 自分から誘ってきたのに、拗ねてしまった。自分勝手というか、マイペースというか。
line = "自分から誘ってきたのに、拗ねてしまった。自分勝手というか、マイペースというか。"

[[dialogue]]
speaker = "リィベル"
# 「次こそはあなたをひいひい言わせてやるんだから。覚悟しておくことね」
line = "「次こそはあなたをひいひい言わせてやるんだから。覚悟しておくことね」"

[[dialogue]]
speaker = "クロト"
# 「はいはい。……でも、そんなに俺だけイかせたいなら、手とか口でもいいんじゃないか？」
line = "「はいはい。……でも、そんなに俺だけイかせたいなら、手とか口でもいいんじゃないか？」"

[[dialogue]]
speaker = "リィベル"
# 「え、イヤよ。だって…………それじゃ私が気持ちよくならないじゃない」
line = "「え、イヤよ。だって…………それじゃ私が気持ちよくならないじゃない」"

[[dialogue]]
speaker = "クロト"
# 「…………そっか」
line = "「…………そっか」"

[[dialogue]]
speaker = "unk"
# 次も、その次もひいひい言わせてやろう。そう心の中で誓うのだった。
line = "次も、その次もひいひい言わせてやろう。そう心の中で誓うのだった。"
