[[dialogue]]
speaker = "unk"
# 第３話,実録、魔王秘話……！？,P
line = "第３話,実録、魔王秘話……！？,P"

[[dialogue]]
speaker = "ルネア"
# 「あらクロト、今日は一人なの？」
line = "「あらクロト、今日は一人なの？」"

[[dialogue]]
speaker = "unk"
# みんなちょうど出払ってて
line = "みんなちょうど出払ってて"

[[dialogue]]
speaker = "ルネア"
# 「ふ～ん、そうなのね。せっかくわたしが遊びに来てあげたというのに、寂しいじゃない」
line = "「ふ～ん、そうなのね。せっかくわたしが遊びに来てあげたというのに、寂しいじゃない」"

[[dialogue]]
speaker = "ルネア"
# 「まあいいわ。今日はね、あなたにシンのこと……いいえ。魔王のことを、布教してあげようと思って来たの」
line = "「まあいいわ。今日はね、あなたにシンのこと……いいえ。魔王のことを、布教してあげようと思って来たの」"

[[dialogue]]
speaker = "unk"
# 布教……？
line = "布教……？"

[[dialogue]]
speaker = "ルネア"
# 「そうよ。だからとにかく、つべこべ言わずに聞いておきなさい。何よりわたしが、シンのことを誰かに話したくて仕方がないのよ」
line = "「そうよ。だからとにかく、つべこべ言わずに聞いておきなさい。何よりわたしが、シンのことを誰かに話したくて仕方がないのよ」"

[[dialogue]]
speaker = "ルネア"
# 「ほら、無性に『推し』の話をしたくなる時ってあるでしょう？　そう、いわば魔王の推し活ね」
line = "「ほら、無性に『推し』の話をしたくなる時ってあるでしょう？　そう、いわば魔王の推し活ね」"

[[dialogue]]
speaker = "ルネア"
# 「そうなった時に、１番適任な話し相手は誰なのかと考えたら……あなたしかいないでしょ？」
line = "「そうなった時に、１番適任な話し相手は誰なのかと考えたら……あなたしかいないでしょ？」"

[[dialogue]]
speaker = "ルネア"
# 「なんといっても、あのシンが認めて、魔王の力を託したんだから」
line = "「なんといっても、あのシンが認めて、魔王の力を託したんだから」"

[[dialogue]]
speaker = "ルネア"
# 「まぁでも？　わたしはまだそこまであなたのことを認めたというわけでもないから、この機会に、あなたのことを見定めさせてもらうつもりでもあるわ」
line = "「まぁでも？　わたしはまだそこまであなたのことを認めたというわけでもないから、この機会に、あなたのことを見定めさせてもらうつもりでもあるわ」"

[[dialogue]]
speaker = "ルネア"
# 「だからしっかり、シンのこと、魔王のことについて、耳を傾けることね。せっかく、女神が直々に布教するわけだし」
line = "「だからしっかり、シンのこと、魔王のことについて、耳を傾けることね。せっかく、女神が直々に布教するわけだし」"

[[dialogue]]
speaker = "unk"
# お、お手柔らかに……
line = "お、お手柔らかに……"

[[dialogue]]
speaker = "ルネア"
# 「まずはそうね、手始めに、魔王の心構えから話していった方がいいかしら……」
line = "「まずはそうね、手始めに、魔王の心構えから話していった方がいいかしら……」"

[[dialogue]]
speaker = "メイプル"
# 「その話、ちょっと待ったーっ！」
line = "「その話、ちょっと待ったーっ！」"

[[dialogue]]
speaker = "ルネア"
# 「あら、あなたは……メイプル、だったかしら」
line = "「あら、あなたは……メイプル、だったかしら」"

[[dialogue]]
speaker = "メイプル"
# 「その通り！　我こそはクルセイダースの末裔、メイプル・モノクラウン！　魔王にまつわる話とあらば、ぜひ聞かせてもらおう！」
line = "「その通り！　我こそはクルセイダースの末裔、メイプル・モノクラウン！　魔王にまつわる話とあらば、ぜひ聞かせてもらおう！」"

[[dialogue]]
speaker = "ルネア"
# 「ふぅん……あなたも、魔王のことが気になるの？」
line = "「ふぅん……あなたも、魔王のことが気になるの？」"

[[dialogue]]
speaker = "メイプル"
# 「いかにも！　それに、お兄ちゃんの妹……すなわち魔王の妹として、魔王の秘密について知る権利はあるはずだよ！」
line = "「いかにも！　それに、お兄ちゃんの妹……すなわち魔王の妹として、魔王の秘密について知る権利はあるはずだよ！」"

[[dialogue]]
speaker = "ルネア"
# 「シンの秘密は、わたしだけのものだけど……魔王についての話なら、別にいいわよ」
line = "「シンの秘密は、わたしだけのものだけど……魔王についての話なら、別にいいわよ」"

[[dialogue]]
speaker = "ルネア"
# 「それに、より多くの人に魔王を布教し、シンの素敵な魅力を広めるというのも、女神たるわたしの宿命と言えるのだから」
line = "「それに、より多くの人に魔王を布教し、シンの素敵な魅力を広めるというのも、女神たるわたしの宿命と言えるのだから」"

[[dialogue]]
speaker = "メイプル"
# 「女神の宿命……！　なんかかっこいい！」
line = "「女神の宿命……！　なんかかっこいい！」"

[[dialogue]]
speaker = "ルネア"
# 「それと、あなたにも迷惑をかけてしまったし、お詫びに……はい、これをどうぞ。クロトの分もあるわよ」
line = "「それと、あなたにも迷惑をかけてしまったし、お詫びに……はい、これをどうぞ。クロトの分もあるわよ」"

[[dialogue]]
speaker = "メイプル"
# 「なにこれ、ストラップ？　ちっちゃいマスコットがついてて可愛いね！」
line = "「なにこれ、ストラップ？　ちっちゃいマスコットがついてて可愛いね！」"

[[dialogue]]
speaker = "ルネア"
# 「これぞ、魔王印のお守りストラップよ。魔王布教の一環として、特別にプレゼントしてあげるわ」
line = "「これぞ、魔王印のお守りストラップよ。魔王布教の一環として、特別にプレゼントしてあげるわ」"

[[dialogue]]
speaker = "メイプル"
# 「魔王関係ある？」
line = "「魔王関係ある？」"

[[dialogue]]
speaker = "ルネア"
# 「これを身につけていれば、魔王の加護を少しだけ得られるのよ」
line = "「これを身につけていれば、魔王の加護を少しだけ得られるのよ」"

[[dialogue]]
speaker = "メイプル"
# 「うわ、なんか急に胡散臭い宗教感が……」
line = "「うわ、なんか急に胡散臭い宗教感が……」"

[[dialogue]]
speaker = "ルネア"
# 「女神を信じれば、救われるわよ」
line = "「女神を信じれば、救われるわよ」"

[[dialogue]]
speaker = "メイプル"
# 「本人から言われると、御利益ありそうだけどぉ……」
line = "「本人から言われると、御利益ありそうだけどぉ……」"

[[dialogue]]
speaker = "ルネア"
# 「わたしお手製の魔王グッズというだけでも、とってもありがたいんだから」
line = "「わたしお手製の魔王グッズというだけでも、とってもありがたいんだから」"

[[dialogue]]
speaker = "メイプル"
# 「えっ、すごい！　手作りだったんだ」
line = "「えっ、すごい！　手作りだったんだ」"

[[dialogue]]
speaker = "ルネア"
# 「まぁ、時間だけはたくさんあるし、このぐらいは大したことないわ」
line = "「まぁ、時間だけはたくさんあるし、このぐらいは大したことないわ」"

[[dialogue]]
speaker = "ルネア"
# 「それにね、わたしなんかより、シンの方がずっとすごいのよ」
line = "「それにね、わたしなんかより、シンの方がずっとすごいのよ」"

[[dialogue]]
speaker = "ルネア"
# 「生活に必要なものは、なんでもＤＩＹで作ってしまうし、それで足りないものがあっても、町の人たちからの貢ぎ物で、大体賄えてしまうんだから」
line = "「生活に必要なものは、なんでもＤＩＹで作ってしまうし、それで足りないものがあっても、町の人たちからの貢ぎ物で、大体賄えてしまうんだから」"

[[dialogue]]
speaker = "メイプル"
# 「へ～、自分の実力もある上に、魔王としての信仰や人望が厚いんだね！」
line = "「へ～、自分の実力もある上に、魔王としての信仰や人望が厚いんだね！」"

[[dialogue]]
speaker = "ルネア"
# 「このストラップもね、実はシンに作り方を教えてもらったの」
line = "「このストラップもね、実はシンに作り方を教えてもらったの」"

[[dialogue]]
speaker = "ルネア"
# 「時々、シンが参加するフリーマーケットについていったりもするんだけど、そこでも評判がいいのよ」
line = "「時々、シンが参加するフリーマーケットについていったりもするんだけど、そこでも評判がいいのよ」"

[[dialogue]]
speaker = "メイプル"
# 「地域に寄り添って勢力拡大してるんだ……！」
line = "「地域に寄り添って勢力拡大してるんだ……！」"

[[dialogue]]
speaker = "ルネア"
# 「勿論それだけじゃなくて、シンは牛乳配達のアルバイトも頑張っていて、生徒会長として学園での人望もあって、しかも、クルセイダースとして平和のために戦い続けているのよ」
line = "「勿論それだけじゃなくて、シンは牛乳配達のアルバイトも頑張っていて、生徒会長として学園での人望もあって、しかも、クルセイダースとして平和のために戦い続けているのよ」"

[[dialogue]]
speaker = "メイプル"
# 「へぇ～……シンって人、ホントにすごいんだね！　あたしも見習わないと……！」
line = "「へぇ～……シンって人、ホントにすごいんだね！　あたしも見習わないと……！」"

[[dialogue]]
speaker = "ルネア"
# 「あら、いい心がけね」
line = "「あら、いい心がけね」"

[[dialogue]]
speaker = "ルネア"
# 「まぁ逆に、シンに人望がありすぎるあまり、たくさんの女の子に囲まれていたりして、少し不安になる時もあるのだけれど……」
line = "「まぁ逆に、シンに人望がありすぎるあまり、たくさんの女の子に囲まれていたりして、少し不安になる時もあるのだけれど……」"

[[dialogue]]
speaker = "ルネア"
# 「でも、ライバルが多いということは、わたしの恋人であるシンが、それだけ魅力的だということだものね！」
line = "「でも、ライバルが多いということは、わたしの恋人であるシンが、それだけ魅力的だということだものね！」"

[[dialogue]]
speaker = "メイプル"
# 「おお、ノロケだ……！」
line = "「おお、ノロケだ……！」"

[[dialogue]]
speaker = "ルネア"
# 「そんなシンを信頼しているからこそ、わたしも毎日早起きして、こっそりシンの後をつけながら、彼のバイト姿を見守っているのよ」
line = "「そんなシンを信頼しているからこそ、わたしも毎日早起きして、こっそりシンの後をつけながら、彼のバイト姿を見守っているのよ」"

[[dialogue]]
speaker = "メイプル"
# 「そ、そうなんだ……それでよく知ってるんだね」
line = "「そ、そうなんだ……それでよく知ってるんだね」"

[[dialogue]]
speaker = "ルネア"
# 「シンを手伝ってあげたい気持ちもあるのだけれど……ひたむきに努力するシンの姿が、何より素敵なの」
line = "「シンを手伝ってあげたい気持ちもあるのだけれど……ひたむきに努力するシンの姿が、何より素敵なの」"

[[dialogue]]
speaker = "ルネア"
# 「だから、こっそり尾行しているというわけ。一生懸命なシンを、邪魔するわけにはいかないものね」
line = "「だから、こっそり尾行しているというわけ。一生懸命なシンを、邪魔するわけにはいかないものね」"

[[dialogue]]
speaker = "メイプル"
# 「ふーん……だけど、頑張ってるっていうなら、お兄ちゃんだっていっぱい頑張ってるよ。仲間だってたくさんいるし！」
line = "「ふーん……だけど、頑張ってるっていうなら、お兄ちゃんだっていっぱい頑張ってるよ。仲間だってたくさんいるし！」"

[[dialogue]]
speaker = "ルネア"
# 「ん～、言われてみれば、確かにそうね……これまでの星徒会長としての仕事ぶりや、スターナイツとしての活躍は、見せてもらってきたわ」
line = "「ん～、言われてみれば、確かにそうね……これまでの星徒会長としての仕事ぶりや、スターナイツとしての活躍は、見せてもらってきたわ」"

[[dialogue]]
speaker = "ルネア"
# 「あちらの世界の子たちとも、ちゃんと協力し合って、仲良くやっていたみたいだし……」
line = "「あちらの世界の子たちとも、ちゃんと協力し合って、仲良くやっていたみたいだし……」"

[[dialogue]]
speaker = "メイプル"
# 「そうそう、そうなんだよっ」
line = "「そうそう、そうなんだよっ」"

[[dialogue]]
speaker = "ルネア"
# 「それにクロト、この前戦った時にも思ったけれど……あなたも、なかなかの実力を持っていたわね。もちろんシンには及ばないけれど」
line = "「それにクロト、この前戦った時にも思ったけれど……あなたも、なかなかの実力を持っていたわね。もちろんシンには及ばないけれど」"

[[dialogue]]
speaker = "メイプル"
# 「ふふん♪　あたしが見込んだお兄ちゃんなんだから、当然だよ！」
line = "「ふふん♪　あたしが見込んだお兄ちゃんなんだから、当然だよ！」"

[[dialogue]]
speaker = "ルネア"
# 「なるほどね……」
line = "「なるほどね……」"

[[dialogue]]
speaker = "ルネア"
# 「そう考えると、わたしがわざわざ魔王の心得を説くまでもなく、大切なことはしっかりわかっているようね」
line = "「そう考えると、わたしがわざわざ魔王の心得を説くまでもなく、大切なことはしっかりわかっているようね」"

[[dialogue]]
speaker = "ルネア"
# 「それに、よく見ると……シンとは違うのに、なんだか少し似ている雰囲気もあるような……」
line = "「それに、よく見ると……シンとは違うのに、なんだか少し似ている雰囲気もあるような……」"

[[dialogue]]
speaker = "ルネア"
# 「これも魔王としての、素質の為せる業ということかしら」
line = "「これも魔王としての、素質の為せる業ということかしら」"

[[dialogue]]
speaker = "メイプル"
# 「ふっふっふ、やっと分かってきたようだね！」
line = "「ふっふっふ、やっと分かってきたようだね！」"

[[dialogue]]
speaker = "ルネア"
# 「……そうね。なんだかんだで、結構見所がありそうだし……魔王として、少しくらいは認めてあげるわ」
line = "「……そうね。なんだかんだで、結構見所がありそうだし……魔王として、少しくらいは認めてあげるわ」"

[[dialogue]]
speaker = "ルネア"
# 「あくまで魔王としては、シンが信用したから、わたしも信用するというだけだけれど……」
line = "「あくまで魔王としては、シンが信用したから、わたしも信用するというだけだけれど……」"

[[dialogue]]
speaker = "ルネア"
# 「それでも、わたしにここまで言わせたんだから、これからもしっかり精進することね」
line = "「それでも、わたしにここまで言わせたんだから、これからもしっかり精進することね」"

[[dialogue]]
speaker = "unk"
# もちろん、そのつもりだよ
line = "もちろん、そのつもりだよ"

[[dialogue]]
speaker = "ルネア"
# 「ふふ……わたしったら、シンの人の良さがうつってしまったのかしら」
line = "「ふふ……わたしったら、シンの人の良さがうつってしまったのかしら」"

[[dialogue]]
speaker = "ルネア"
# 「それと、メイプル。あなたも、クロトのことを支えてあげる仲間の１人として、しっかり頑張るのよ」
line = "「それと、メイプル。あなたも、クロトのことを支えてあげる仲間の１人として、しっかり頑張るのよ」"

[[dialogue]]
speaker = "メイプル"
# 「そんなの当たり前だよっ！　あたしだってお兄ちゃんと一緒にいつか魔王になる者――妹魔王なんだからね♪」
line = "「そんなの当たり前だよっ！　あたしだってお兄ちゃんと一緒にいつか魔王になる者――妹魔王なんだからね♪」"

[[dialogue]]
speaker = "ルネア"
# 「それならよかったわ。それじゃあ、シンのことも話せてすっきりしたことだし……」
line = "「それならよかったわ。それじゃあ、シンのことも話せてすっきりしたことだし……」"

[[dialogue]]
speaker = "ルネア"
# 「次は、シンの活躍をまとめた武勇伝を聞かせてあげるわ」
line = "「次は、シンの活躍をまとめた武勇伝を聞かせてあげるわ」"

[[dialogue]]
speaker = "メイプル"
# 「えっ、まだ続くのっ！？」
line = "「えっ、まだ続くのっ！？」"

[[dialogue]]
speaker = "ルネア"
# 「ふふっ、心して聞くのよ、２人とも」
line = "「ふふっ、心して聞くのよ、２人とも」"
