[[dialogue]]
speaker = "unk"
# 第１話,天使の来訪,P
line = "第１話,天使の来訪,P"

[[dialogue]]
speaker = "unk"
# 時は過ぎ、再び大交流の時期がやってきた。
line = "時は過ぎ、再び大交流の時期がやってきた。"

[[dialogue]]
speaker = "unk"
# 今回は天界より人間界へ、大々的な使節団がやってくる。
line = "今回は天界より人間界へ、大々的な使節団がやってくる。"

[[dialogue]]
speaker = "unk"
# その使節団が学園の視察も行うとのことで、先んじて警備隊長であるケイティさんが流星星徒会室を訪れていた。
line = "その使節団が学園の視察も行うとのことで、先んじて警備隊長であるケイティさんが流星星徒会室を訪れていた。"

[[dialogue]]
speaker = "ケイティ"
# 「本日はお時間をいただき、ありがとうございました」
line = "「本日はお時間をいただき、ありがとうございました」"

[[dialogue]]
speaker = "ケイティ"
# 「視察の際、皆様にはまた色々とご協力いただくことになると思います。その際にはよろしくお願いしますね」
line = "「視察の際、皆様にはまた色々とご協力いただくことになると思います。その際にはよろしくお願いしますね」"

[[dialogue]]
speaker = "フィオナ"
# 「お任せください、ケイティさん。この度は、わざわざご足労いただいてありがとうございました」
line = "「お任せください、ケイティさん。この度は、わざわざご足労いただいてありがとうございました」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それにしても久しぶりね。天界で会って以来だけど、あの時は本当に助かったわ」
line = "「それにしても久しぶりね。天界で会って以来だけど、あの時は本当に助かったわ」"

[[dialogue]]
speaker = "ケイティ"
# 「こちらこそです～。皆様のおかげで天界の平和は保たれました。感謝してもしきれません」
line = "「こちらこそです～。皆様のおかげで天界の平和は保たれました。感謝してもしきれません」"

[[dialogue]]
speaker = "unk"
# あれから天界の様子はどうですか？
line = "あれから天界の様子はどうですか？"

[[dialogue]]
speaker = "ケイティ"
# 「極星従騎……でしたか？　あれに荒らされてしまった聖庭園もすっかり元通りになりました」
line = "「極星従騎……でしたか？　あれに荒らされてしまった聖庭園もすっかり元通りになりました」"

[[dialogue]]
speaker = "ケイティ"
# 「平和を脅かしていた諸悪の根源も、皆様の手によって退治されたようですし～……平和が取り戻されて何よりです」
line = "「平和を脅かしていた諸悪の根源も、皆様の手によって退治されたようですし～……平和が取り戻されて何よりです」"

[[dialogue]]
speaker = "ルリエル"
# 「ふわ～……すっごく優しそうなお姉さんなのです。あんまり警備隊長って感じじゃありませんね～」
line = "「ふわ～……すっごく優しそうなお姉さんなのです。あんまり警備隊長って感じじゃありませんね～」"

[[dialogue]]
speaker = "ソフィア"
# 「確かに話に聞いていた印象とは違います。ちっとも怖い方には見えません」
line = "「確かに話に聞いていた印象とは違います。ちっとも怖い方には見えません」"

[[dialogue]]
speaker = "ソフィア"
# 「ですが、会長さんたちが言うには凄腕の剣士だというお話ですし……」
line = "「ですが、会長さんたちが言うには凄腕の剣士だというお話ですし……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「疑うのも無理はないわね！　でも本っ当にすごいんだから！　こーんなでっかい剣をブンブン振り回して！」
line = "「疑うのも無理はないわね！　でも本っ当にすごいんだから！　こーんなでっかい剣をブンブン振り回して！」"

[[dialogue]]
speaker = "ケイティ"
# 「あの……そんなに言わないでください。お恥ずかしいです……」
line = "「あの……そんなに言わないでください。お恥ずかしいです……」"

[[dialogue]]
speaker = "unk"
# 獅子奮迅という感じで
line = "獅子奮迅という感じで"

[[dialogue]]
speaker = "unk"
# でも、本当にすごかったです
line = "でも、本当にすごかったです"

[[dialogue]]
speaker = "ケイティ"
# 「本当はみんなが争うことなく、平和的に物事を解決できれば一番良いのですけど……」
line = "「本当はみんなが争うことなく、平和的に物事を解決できれば一番良いのですけど……」"

[[dialogue]]
speaker = "ケイティ"
# 「ですが誰もが平和を愛する心を持っているわけではありませんからね～」
line = "「ですが誰もが平和を愛する心を持っているわけではありませんからね～」"

[[dialogue]]
speaker = "ケイティ"
# 「平和のためにはどうしても、力に訴えなければならないこともあります……とても辛いことですが」
line = "「平和のためにはどうしても、力に訴えなければならないこともあります……とても辛いことですが」"

[[dialogue]]
speaker = "セーラ"
# 「ま、どーしようもないことって世の中ままあるもんね～」
line = "「ま、どーしようもないことって世の中ままあるもんね～」"

[[dialogue]]
speaker = "ユウリ"
# 「でも、まずは出来るだけ平和的に解決しようってのはすごくいいと思うぜ！」
line = "「でも、まずは出来るだけ平和的に解決しようってのはすごくいいと思うぜ！」"

[[dialogue]]
speaker = "ケイティ"
# 「まあ……なんて素晴らしいのでしょう～。こんなにもたくさんの方が平和の大切さに共感してくださるなんて……」
line = "「まあ……なんて素晴らしいのでしょう～。こんなにもたくさんの方が平和の大切さに共感してくださるなんて……」"

[[dialogue]]
speaker = "ケイティ"
# 「この喜びを得たことだけでも、人間界にやってきた意味がありました～♪」
line = "「この喜びを得たことだけでも、人間界にやってきた意味がありました～♪」"

[[dialogue]]
speaker = "ケイティ"
# 「滞在期間は限られていますが、その間に少しでも皆さんとも友好を深め、平和の尊さについて分かち合いたいと思っています～」
line = "「滞在期間は限られていますが、その間に少しでも皆さんとも友好を深め、平和の尊さについて分かち合いたいと思っています～」"

[[dialogue]]
speaker = "フィオナ"
# 「はい、任務以外でも気軽に遊びに来てください」
line = "「はい、任務以外でも気軽に遊びに来てください」"

[[dialogue]]
speaker = "unk"
# 次は新星星徒会にも来てください
line = "次は新星星徒会にも来てください"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうよ、私たちだって流星星徒会に負けないくらい大歓迎するわ！」
line = "「そうよ、私たちだって流星星徒会に負けないくらい大歓迎するわ！」"

[[dialogue]]
speaker = "ケイティ"
# 「ありがとうございます……魔王さんとも平和について、もっともっとお話ししたいと思っていましたから、とっても嬉しいです～」
line = "「ありがとうございます……魔王さんとも平和について、もっともっとお話ししたいと思っていましたから、とっても嬉しいです～」"

[[dialogue]]
speaker = "ケイティ"
# 「ぜひ、新星学園にも遊びに行かせてくださいね♪」
line = "「ぜひ、新星学園にも遊びに行かせてくださいね♪」"

[[dialogue]]
speaker = "ルリエル"
# 「はぁぅ……なんという慈愛に満ちた微笑み……まさに天使……」
line = "「はぁぅ……なんという慈愛に満ちた微笑み……まさに天使……」"

[[dialogue]]
speaker = "セーラ"
# 「あはは、そういうルリちーだって天使でしょ」
line = "「あはは、そういうルリちーだって天使でしょ」"

[[dialogue]]
speaker = "ユウリ"
# 「ま、同じ天使でもオーラが違うけどな。ルリはケイティさんを見習って、もっと気品ってやつを身に着けたらどうだ？」
line = "「ま、同じ天使でもオーラが違うけどな。ルリはケイティさんを見習って、もっと気品ってやつを身に着けたらどうだ？」"

[[dialogue]]
speaker = "ルリエル"
# 「むうう～、酷い言われようですが何も言い返せません」
line = "「むうう～、酷い言われようですが何も言い返せません」"

[[dialogue]]
speaker = "ルリエル"
# 「分かりました！　ルリエルはケイティさんを目標に、天使の中の天使になることをここに誓いますっ！」
line = "「分かりました！　ルリエルはケイティさんを目標に、天使の中の天使になることをここに誓いますっ！」"

[[dialogue]]
speaker = "ケイティ"
# 「そんな……そこまで持ち上げられると、お恥ずかしいです……」
line = "「そんな……そこまで持ち上げられると、お恥ずかしいです……」"

[[dialogue]]
speaker = "unk"
# ルリエルの宣言に、ほんのりと頬を染めながら上品な恥じらいを見せるケイティさん。
line = "ルリエルの宣言に、ほんのりと頬を染めながら上品な恥じらいを見せるケイティさん。"

[[dialogue]]
speaker = "unk"
# その様子はルリエルの言う通り、まさに天使の中の天使という言葉がふさわしい……誰もがそう思うだろう。
line = "その様子はルリエルの言う通り、まさに天使の中の天使という言葉がふさわしい……誰もがそう思うだろう。"

[[dialogue]]
speaker = "unk"
# けれどこの人は、敵対する者を完全に制圧してしまうことから『制圧天使』という異名を持っている。
line = "けれどこの人は、敵対する者を完全に制圧してしまうことから『制圧天使』という異名を持っている。"

[[dialogue]]
speaker = "unk"
# この人の戦いぶりを目の当たりにした時、みんなの印象は１８０度変わってしまうんだろうな、と心の中で思うのだった。
line = "この人の戦いぶりを目の当たりにした時、みんなの印象は１８０度変わってしまうんだろうな、と心の中で思うのだった。"
