[[dialogue]]
speaker = "unk"
# 第２話,ブラックホール・ストマック,P
line = "第２話,ブラックホール・ストマック,P"

[[dialogue]]
speaker = "unk"
# 休日、昼食を摂ろうとバーガーショップに入った。
line = "休日、昼食を摂ろうとバーガーショップに入った。"

[[dialogue]]
speaker = "unk"
# せっかくの陽気なので、オープンテラスの席を取ろうとすると──
line = "せっかくの陽気なので、オープンテラスの席を取ろうとすると──"

[[dialogue]]
speaker = "レイラ"
# 「うぅ、ひもじい……」
line = "「うぅ、ひもじい……」"

[[dialogue]]
speaker = "レイラ"
# 「あ、魔王さん、こんにちは。混んでますし、魔王さんさえよければ相席しませんか？」
line = "「あ、魔王さん、こんにちは。混んでますし、魔王さんさえよければ相席しませんか？」"

[[dialogue]]
speaker = "unk"
# ありがとう。お邪魔するね
line = "ありがとう。お邪魔するね"

[[dialogue]]
speaker = "レイラ"
# 「はい、どうぞ。……え、悲しそう？　私が、ですか？」
line = "「はい、どうぞ。……え、悲しそう？　私が、ですか？」"

[[dialogue]]
speaker = "レイラ"
# 「えっと、とある事情でお金を使いこんでしまってですね、もっと食べたいんですけど一番安いハンバーガーひとつで我慢しています……」
line = "「えっと、とある事情でお金を使いこんでしまってですね、もっと食べたいんですけど一番安いハンバーガーひとつで我慢しています……」"

[[dialogue]]
speaker = "レイラ"
# 「え、ハンバーガーひとつあげる……？　そんな、申し訳ないですよ」
line = "「え、ハンバーガーひとつあげる……？　そんな、申し訳ないですよ」"

[[dialogue]]
speaker = "unk"
# ちょっと頼み過ぎちゃったから
line = "ちょっと頼み過ぎちゃったから"

[[dialogue]]
speaker = "レイラ"
# 「……ふふ、やっぱりあなたは優しい人ですね」
line = "「……ふふ、やっぱりあなたは優しい人ですね」"

[[dialogue]]
speaker = "レイラ"
# 「ご厚意を無下にするわけには参りません。では、いただきます」
line = "「ご厚意を無下にするわけには参りません。では、いただきます」"

[[dialogue]]
speaker = "レイラ"
# 「うめ、うめ……てりやきうめ……」
line = "「うめ、うめ……てりやきうめ……」"

[[dialogue]]
speaker = "unk"
# 一週間後。同じバーガーショップでまたレイラと出会った。
line = "一週間後。同じバーガーショップでまたレイラと出会った。"

[[dialogue]]
speaker = "レイラ"
# 「あ、魔王さん、こんにちは。相席いかがですか？」
line = "「あ、魔王さん、こんにちは。相席いかがですか？」"

[[dialogue]]
speaker = "unk"
# あ、ありがとう……
line = "あ、ありがとう……"

[[dialogue]]
speaker = "レイラ"
# 「どうしたんですか、火山でイエティでも見たような顔してますよ？」
line = "「どうしたんですか、火山でイエティでも見たような顔してますよ？」"

[[dialogue]]
speaker = "レイラ"
# 「……え、ハンバーガーが山積み？　ええ、ええ！　お金が入ったんです！　実は──」
line = "「……え、ハンバーガーが山積み？　ええ、ええ！　お金が入ったんです！　実は──」"

[[dialogue]]
speaker = "レイラ"
# 「お待たせしました。今日はコハルコさんもご一緒なんですね？」
line = "「お待たせしました。今日はコハルコさんもご一緒なんですね？」"

[[dialogue]]
speaker = "ウェンディ"
# 「ええ、彼女には実行犯というか……まぁ、専門家として助言をお願いしました」
line = "「ええ、彼女には実行犯というか……まぁ、専門家として助言をお願いしました」"

[[dialogue]]
speaker = "コハルコ"
# 「急いでいたとはいえ、先日は大変ご迷惑をお掛けしました……」
line = "「急いでいたとはいえ、先日は大変ご迷惑をお掛けしました……」"

[[dialogue]]
speaker = "ウェンディ"
# 「ええ、まさか基地のシステムがまるごと掌握されるとは思いませんでした。セドナ長官からもセキュリティ強化の指令を受けています。そのためのこの場です」
line = "「ええ、まさか基地のシステムがまるごと掌握されるとは思いませんでした。セドナ長官からもセキュリティ強化の指令を受けています。そのためのこの場です」"

[[dialogue]]
speaker = "ウェンディ"
# 「その前に２人は……その、わだかまりとかはないんですか？」
line = "「その前に２人は……その、わだかまりとかはないんですか？」"

[[dialogue]]
speaker = "コハルコ"
# 「確かに敵対はしましたけど、それは理由あってのことですし、命を狙われたことも一度や二度ではないので気にしてません」
line = "「確かに敵対はしましたけど、それは理由あってのことですし、命を狙われたことも一度や二度ではないので気にしてません」"

[[dialogue]]
speaker = "コハルコ"
# 「まぁ、家族を狙われてたら再起不能にしてましたけど」
line = "「まぁ、家族を狙われてたら再起不能にしてましたけど」"

[[dialogue]]
speaker = "レイラ"
# （こわっ……コハルコさん、目が笑ってない……）
line = "（こわっ……コハルコさん、目が笑ってない……）"

[[dialogue]]
speaker = "コハルコ"
# 「今は趣味が合う友達ですね。パソコン談議ができる人は貴重ですから」
line = "「今は趣味が合う友達ですね。パソコン談議ができる人は貴重ですから」"

[[dialogue]]
speaker = "レイラ"
# 「私も、コハルコさんには畏れ多くも親しくしていただいております……」
line = "「私も、コハルコさんには畏れ多くも親しくしていただいております……」"

[[dialogue]]
speaker = "ウェンディ"
# 「でしたら問題はありませんね。実はレイラに提案があるんです」
line = "「でしたら問題はありませんね。実はレイラに提案があるんです」"

[[dialogue]]
speaker = "ウェンディ"
# 「ネビュラのサイバー担当をお願いできませんか？」
line = "「ネビュラのサイバー担当をお願いできませんか？」"

[[dialogue]]
speaker = "レイラ"
# 「私に、ですか？」
line = "「私に、ですか？」"

[[dialogue]]
speaker = "コハルコ"
# 「私の推薦なんだ。私は忙しくて新規案件は受けられないし、レイラの実力なら私も太鼓判だよ」
line = "「私の推薦なんだ。私は忙しくて新規案件は受けられないし、レイラの実力なら私も太鼓判だよ」"

[[dialogue]]
speaker = "ウェンディ"
# 「聞くところによれば、レイラは食費で難儀しているそうですね」
line = "「聞くところによれば、レイラは食費で難儀しているそうですね」"

[[dialogue]]
speaker = "ウェンディ"
# 「現在も戦闘員として生活費を支給していますが、サイバー担当を引き受けていただければ、その分の報酬を上乗せしてお支払いします」
line = "「現在も戦闘員として生活費を支給していますが、サイバー担当を引き受けていただければ、その分の報酬を上乗せしてお支払いします」"

[[dialogue]]
speaker = "ウェンディ"
# 「ちなみにこれくらい……」
line = "「ちなみにこれくらい……」"

[[dialogue]]
speaker = "レイラ"
# 「そんなに頂けるんですか！？　牛丼に卵とみそ汁も付けられますね！」
line = "「そんなに頂けるんですか！？　牛丼に卵とみそ汁も付けられますね！」"

[[dialogue]]
speaker = "ウェンディ"
# 「……は？」
line = "「……は？」"

[[dialogue]]
speaker = "レイラ"
# 「いえ、ものの例えです。すみません」
line = "「いえ、ものの例えです。すみません」"

[[dialogue]]
speaker = "レイラ"
# 「百目騎レイラ、謹んでお引き受けいたします。誠心誠意、務めて参りますのでよろしくお願いいたします」
line = "「百目騎レイラ、謹んでお引き受けいたします。誠心誠意、務めて参りますのでよろしくお願いいたします」"

[[dialogue]]
speaker = "レイラ"
# 「──というわけなんですよ！」
line = "「──というわけなんですよ！」"

[[dialogue]]
speaker = "レイラ"
# 「これで思う存分ハンバーガーが食べられます。魔王さんにはこの前てりやきバーガーをいただきましたから、今日は私がお裾分けします」
line = "「これで思う存分ハンバーガーが食べられます。魔王さんにはこの前てりやきバーガーをいただきましたから、今日は私がお裾分けします」"

[[dialogue]]
speaker = "レイラ"
# 「どうぞ、デミグラスシチューバーガーです！　召し上がってください！」
line = "「どうぞ、デミグラスシチューバーガーです！　召し上がってください！」"

[[dialogue]]
speaker = "unk"
# あっつっ！！
line = "あっつっ！！"

[[dialogue]]
speaker = "レイラ"
# 「アツアツなので気を付けてください……って遅かったですね。すみません」
line = "「アツアツなので気を付けてください……って遅かったですね。すみません」"

[[dialogue]]
speaker = "レイラ"
# 「では、私はこのトンカツバーガーをいただきます……ひゅごっ」
line = "「では、私はこのトンカツバーガーをいただきます……ひゅごっ」"

[[dialogue]]
speaker = "unk"
# ひと口でいった！？
line = "ひと口でいった！？"

[[dialogue]]
speaker = "レイラ"
# 「……もぐもぐ……サクサク、ジューシーなトンカツとシャキシャキのキャベツ、硬めのバンズの相性が最高ですね」
line = "「……もぐもぐ……サクサク、ジューシーなトンカツとシャキシャキのキャベツ、硬めのバンズの相性が最高ですね」"

[[dialogue]]
speaker = "レイラ"
# 「ひゅごっ……このカプレーゼバーガー、トマトの酸味とモッツァレラの旨みが見事に融合しています。百億万点」
line = "「ひゅごっ……このカプレーゼバーガー、トマトの酸味とモッツァレラの旨みが見事に融合しています。百億万点」"

[[dialogue]]
speaker = "レイラ"
# 「ひゅごっ……ひゅごっ……ひゅごっ……」
line = "「ひゅごっ……ひゅごっ……ひゅごっ……」"

[[dialogue]]
speaker = "unk"
# 次々とハンバーガーがレイラに飲み込まれていく。
line = "次々とハンバーガーがレイラに飲み込まれていく。"

[[dialogue]]
speaker = "unk"
# レイラは操る星術だけでなく、胃袋もブラックホールのようだった……。
line = "レイラは操る星術だけでなく、胃袋もブラックホールのようだった……。"
