[[dialogue]]
speaker = "unk"
# 第１話,新たな監視者？,P
line = "第１話,新たな監視者？,P"

[[dialogue]]
speaker = "unk"
# 今日は星徒会長として、各部活の様子を見て回っていたのだが……
line = "今日は星徒会長として、各部活の様子を見て回っていたのだが……"

[[dialogue]]
speaker = "unk"
# （視線を感じる……）
line = "（視線を感じる……）"

[[dialogue]]
speaker = "梨緒"
# 「じー……」
line = "「じー……」"

[[dialogue]]
speaker = "ベアトリス"
# 「じー……」
line = "「じー……」"

[[dialogue]]
speaker = "ナターシャ"
# 「じー……」
line = "「じー……」"

[[dialogue]]
speaker = "アポロ"
# 「じー……」
line = "「じー……」"

[[dialogue]]
speaker = "unk"
# （すごく視線を感じる……！）
line = "（すごく視線を感じる……！）"

[[dialogue]]
speaker = "ベアトリス"
# （今のところ真面目に活動にしてる……よね？　いい会長さんに見えるけど……）
line = "（今のところ真面目に活動にしてる……よね？　いい会長さんに見えるけど……）"

[[dialogue]]
speaker = "ナターシャ"
# （そだねー）
line = "（そだねー）"

[[dialogue]]
speaker = "アポロ"
# （ああ、いつもの魔王だな）
line = "（ああ、いつもの魔王だな）"

[[dialogue]]
speaker = "梨緒"
# （だがいつ彼が悪に堕ちるかわからない。気を緩めないようにな）
line = "（だがいつ彼が悪に堕ちるかわからない。気を緩めないようにな）"

[[dialogue]]
speaker = "ベアトリス"
# （う、うん。会長さんから目を離さないように……）
line = "（う、うん。会長さんから目を離さないように……）"

[[dialogue]]
speaker = "ベアトリス"
# （きゃっ）
line = "（きゃっ）"

[[dialogue]]
speaker = "ベアトリス"
# 「あいたた……こけちゃった～……」
line = "「あいたた……こけちゃった～……」"

[[dialogue]]
speaker = "ベアトリス"
# 「あ、こんにちは、会長さん。──って」
line = "「あ、こんにちは、会長さん。──って」"

[[dialogue]]
speaker = "ベアトリス"
# 「見つかっちゃった～～～～～っ！！？」
line = "「見つかっちゃった～～～～～っ！！？」"

[[dialogue]]
speaker = "梨緒"
# 「気にするな。気付かれていようといまいと、私たちのやるべきことは変わらない」
line = "「気にするな。気付かれていようといまいと、私たちのやるべきことは変わらない」"

[[dialogue]]
speaker = "ナターシャ"
# 「ま、会長さんはその前から気付いてたと思うけどね」
line = "「ま、会長さんはその前から気付いてたと思うけどね」"

[[dialogue]]
speaker = "ナターシャ"
# 「はーい、こんにちは、会長さん。おなじみ選管だよ」
line = "「はーい、こんにちは、会長さん。おなじみ選管だよ」"

[[dialogue]]
speaker = "ベアトリス"
# 「そんなにおなじみだったかな……？」
line = "「そんなにおなじみだったかな……？」"

[[dialogue]]
speaker = "アポロ"
# 「あたしもいるぞ！　よ、元気か魔王！」
line = "「あたしもいるぞ！　よ、元気か魔王！」"

[[dialogue]]
speaker = "unk"
# 元気だけど……俺に何か用事？
line = "元気だけど……俺に何か用事？"

[[dialogue]]
speaker = "ベアトリス"
# 「あ、いえ、用というか……選管は会長さんを監視するものだって、梨緒ちゃんに言われまして」
line = "「あ、いえ、用というか……選管は会長さんを監視するものだって、梨緒ちゃんに言われまして」"

[[dialogue]]
speaker = "梨緒"
# 「選挙管理委員会は君を監視し、星徒会長に相応しくないと判断すればリコールを発議する」
line = "「選挙管理委員会は君を監視し、星徒会長に相応しくないと判断すればリコールを発議する」"

[[dialogue]]
speaker = "梨緒"
# 「用の有る無しの問題ではない。むしろ何もない時こそ、目を光らせておかなければいけないんだ」
line = "「用の有る無しの問題ではない。むしろ何もない時こそ、目を光らせておかなければいけないんだ」"

[[dialogue]]
speaker = "ベアトリス"
# 「……というわけで会長さんの監視に来ました。会長さんの一挙手一投足を見逃しませんからっ」
line = "「……というわけで会長さんの監視に来ました。会長さんの一挙手一投足を見逃しませんからっ」"

[[dialogue]]
speaker = "ベアトリス"
# 「会長さんから絶対に目を離しませんから。じぃ～～～～～～～っ」
line = "「会長さんから絶対に目を離しませんから。じぃ～～～～～～～っ」"

[[dialogue]]
speaker = "ベアトリス"
# 「へくちっ」
line = "「へくちっ」"

[[dialogue]]
speaker = "ベアトリス"
# 「あ、今のは違いますよっ！？　目を離してませんからっ、ホントですからねっ」
line = "「あ、今のは違いますよっ！？　目を離してませんからっ、ホントですからねっ」"

[[dialogue]]
speaker = "ベアトリス"
# 「会長さんのこと、じっと見てますからね。じーーーーーーーーっ」
line = "「会長さんのこと、じっと見てますからね。じーーーーーーーーっ」"

[[dialogue]]
speaker = "ベアトリス"
# 「いたっ！？　目にゴミが入った～っ！？」
line = "「いたっ！？　目にゴミが入った～っ！？」"

[[dialogue]]
speaker = "ナターシャ"
# 「ベアトはかわいいね」
line = "「ベアトはかわいいね」"

[[dialogue]]
speaker = "梨緒"
# 「……そうだな」
line = "「……そうだな」"

[[dialogue]]
speaker = "アポロ"
# 「監視するならちゃんと監視しろ。監査として心配になるぞ」
line = "「監視するならちゃんと監視しろ。監査として心配になるぞ」"

[[dialogue]]
speaker = "ベアトリス"
# 「ごめんなさ～～いっ！」
line = "「ごめんなさ～～いっ！」"

[[dialogue]]
speaker = "unk"
# ベアトリスはどうして選管に入ったんだ？
line = "ベアトリスはどうして選管に入ったんだ？"

[[dialogue]]
speaker = "ベアトリス"
# 「えっと……梨緒ちゃんが言ってたんです。『最も強い人が、正しい道を往くとは限らない』って」
line = "「えっと……梨緒ちゃんが言ってたんです。『最も強い人が、正しい道を往くとは限らない』って」"

[[dialogue]]
speaker = "ベアトリス"
# 「会長さんを疑ってるとか、信じてないとかじゃないんですけど、確かにそうだなって思って」
line = "「会長さんを疑ってるとか、信じてないとかじゃないんですけど、確かにそうだなって思って」"

[[dialogue]]
speaker = "ベアトリス"
# 「誰だって間違ったり、つい悪いことをしたり、自分を止められないことはありますから。その時は他の誰かが止めないといけません」
line = "「誰だって間違ったり、つい悪いことをしたり、自分を止められないことはありますから。その時は他の誰かが止めないといけません」"

[[dialogue]]
speaker = "ベアトリス"
# 「私なんかに止められるかはわからないですけど……」
line = "「私なんかに止められるかはわからないですけど……」"

[[dialogue]]
speaker = "unk"
# 俺にもし何かあったらよろしく
line = "俺にもし何かあったらよろしく"

[[dialogue]]
speaker = "ベアトリス"
# 「あ、はい、もし会長さんが悪い魔王になったら、頑張って止めますっ」
line = "「あ、はい、もし会長さんが悪い魔王になったら、頑張って止めますっ」"

[[dialogue]]
speaker = "ベアトリス"
# 「って、何かってなんですか！？　本当に悪の魔王になっちゃうかもなんですか！？」
line = "「って、何かってなんですか！？　本当に悪の魔王になっちゃうかもなんですか！？」"

[[dialogue]]
speaker = "ベアトリス"
# 「……万が一の場合？　そ、そうですよね……闇堕ちしちゃう予定なんてないですよね」
line = "「……万が一の場合？　そ、そうですよね……闇堕ちしちゃう予定なんてないですよね」"

[[dialogue]]
speaker = "unk"
# でもその前に……
line = "でもその前に……"

[[dialogue]]
speaker = "ベアトリス"
# 「……自己紹介？　はっ、そうでした！　最初びっくりして逃げちゃったから、ちゃんと挨拶できてませんでした！」
line = "「……自己紹介？　はっ、そうでした！　最初びっくりして逃げちゃったから、ちゃんと挨拶できてませんでした！」"

[[dialogue]]
speaker = "ベアトリス"
# 「私、２年生のベアトリス・シェイドですっ。星騎士になるために魔界から流星市国にやってきました」
line = "「私、２年生のベアトリス・シェイドですっ。星騎士になるために魔界から流星市国にやってきました」"

[[dialogue]]
speaker = "ベアトリス"
# 「私の目標はみんなを……世界すべてを救うこと。誰一人切り捨てることなく守りたいです」
line = "「私の目標はみんなを……世界すべてを救うこと。誰一人切り捨てることなく守りたいです」"

[[dialogue]]
speaker = "unk"
# 今度こそよろしく、ベアトリス
line = "今度こそよろしく、ベアトリス"

[[dialogue]]
speaker = "ベアトリス"
# 「はい！　よろしくお願いします！」
line = "「はい！　よろしくお願いします！」"

[[dialogue]]
speaker = "unk"
# 俺は星徒会長で、ベアトリスは監視する側だけど、きっと志は同じ。
line = "俺は星徒会長で、ベアトリスは監視する側だけど、きっと志は同じ。"

[[dialogue]]
speaker = "unk"
# 遠くから来た新たな仲間を得て、心強く思うのだった。
line = "遠くから来た新たな仲間を得て、心強く思うのだった。"
