[[dialogue]]
speaker = "unk"
# 第４話,もしも年下の幼なじみだったら,P
line = "第４話,もしも年下の幼なじみだったら,P"

[[dialogue]]
speaker = "unk"
# その日は休日で、メルエルが俺の家へ遊びにやってきていた。
line = "その日は休日で、メルエルが俺の家へ遊びにやってきていた。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「ふんふん、ふふふ～ん♪　今日は会長くんと２人っきりで、ゆっくり過ごせる日～♪　えへへへへへぇ<emoji=heart04>」
line = "「ふんふん、ふふふ～ん♪　今日は会長くんと２人っきりで、ゆっくり過ごせる日～♪　えへへへへへぇ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 今日はリトルフォームなんだな
line = "今日はリトルフォームなんだな"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「うん♪　今日は、『年下の幼なじみ』になったつもりで、会長くんとイチャイチャしたいな～と思って<emoji=heart04>」
line = "「うん♪　今日は、『年下の幼なじみ』になったつもりで、会長くんとイチャイチャしたいな～と思って<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「それにおっきい私のままだと、まだちょっと恥ずかしいけど……今日は１日中、ベタベタしちゃいたいから<emoji=heart04>」
line = "「それにおっきい私のままだと、まだちょっと恥ずかしいけど……今日は１日中、ベタベタしちゃいたいから<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺は全然、ウェルカムだけど
line = "俺は全然、ウェルカムだけど"

[[dialogue]]
speaker = "unk"
# １日中、キスしちゃう？
line = "１日中、キスしちゃう？"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「あぅぅ<emoji=heart04>　それもすっごく魅力的だけど、キスばっかりしてると、できないこともあるから……」
line = "「あぅぅ<emoji=heart04>　それもすっごく魅力的だけど、キスばっかりしてると、できないこともあるから……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「１日中キスしちゃうデートは、また今度にしよ<emoji=heart04>」
line = "「１日中キスしちゃうデートは、また今度にしよ<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「それでね、会長くんと同級生なのは、とっても運命を感じちゃって、嬉しいことなんだけど……」
line = "「それでね、会長くんと同級生なのは、とっても運命を感じちゃって、嬉しいことなんだけど……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「会長くんってとっても男らしいから、もし私が会長くんに甘えられる立場の、年下の幼なじみだったら、どんな風になってたんだろうって思ったの<emoji=heart04>」
line = "「会長くんってとっても男らしいから、もし私が会長くんに甘えられる立場の、年下の幼なじみだったら、どんな風になってたんだろうって思ったの<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「だから今日１日、『年下幼なじみごっこ』してみたいんだけど、どうかなぁ？」
line = "「だから今日１日、『年下幼なじみごっこ』してみたいんだけど、どうかなぁ？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「――ふふっ、ありがとう<emoji=heart04>　じゃあ今日は、年下として甘えちゃうね、会長くん<emoji=heart04>」
line = "「――ふふっ、ありがとう<emoji=heart04>　じゃあ今日は、年下として甘えちゃうね、会長くん<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# それから、俺たちはベッドのふちに腰掛けて、向き合って座る。
line = "それから、俺たちはベッドのふちに腰掛けて、向き合って座る。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「会長くん、あのね、私の頭……優しく撫でて欲しいの<emoji=heart04>」
line = "「会長くん、あのね、私の頭……優しく撫でて欲しいの<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「ヴィーナスちゃんが褒めてもらってる時に、会長くんによく撫でてもらってるでしょ？　実は私、あれがずっと羨ましいな～って思ってて……」
line = "「ヴィーナスちゃんが褒めてもらってる時に、会長くんによく撫でてもらってるでしょ？　実は私、あれがずっと羨ましいな～って思ってて……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「おっきい私だと、恥ずかしくてなかなか言い出せなかったから……今日は恋人として思いっきり甘えたいな～って<emoji=heart04>」
line = "「おっきい私だと、恥ずかしくてなかなか言い出せなかったから……今日は恋人として思いっきり甘えたいな～って<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺はメルエルのおねだりに応えて、頭に手を置いて、優しく撫でる。
line = "俺はメルエルのおねだりに応えて、頭に手を置いて、優しく撫でる。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「あっ<emoji=heart04>　えへへ<emoji=heart04>　会長くんの手、優しくて……大好き<emoji=heart04>」
line = "「あっ<emoji=heart04>　えへへ<emoji=heart04>　会長くんの手、優しくて……大好き<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「会長くんに撫でられてると、愛が伝わってくる感じがして、とっても安心するんだぁ<emoji=heart04>」
line = "「会長くんに撫でられてると、愛が伝わってくる感じがして、とっても安心するんだぁ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺も勇気を出して、言ってみていい？
line = "俺も勇気を出して、言ってみていい？"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「え？　会長くんも恥ずかしくて、なかなか言えなかったことがあるの？」
line = "「え？　会長くんも恥ずかしくて、なかなか言えなかったことがあるの？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「――本当は、自分も甘えたい時があるけど、カッコ悪いと思われたくなかったから言えなかった……？」
line = "「――本当は、自分も甘えたい時があるけど、カッコ悪いと思われたくなかったから言えなかった……？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「そう、だよね<emoji=heart04>　私だって、恥ずかしくて言えなかったことがいっぱいあるんだから、会長くんだって同じようにあるよね……<emoji=heart04>」
line = "「そう、だよね<emoji=heart04>　私だって、恥ずかしくて言えなかったことがいっぱいあるんだから、会長くんだって同じようにあるよね……<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「なんだか、嬉しいな<emoji=heart04>　会長くんとこうやって、お互いの恥ずかしいところを晒し合えるなんて……私たち、凄く深いところで繋がり合えてる気がする<emoji=heart04>」
line = "「なんだか、嬉しいな<emoji=heart04>　会長くんとこうやって、お互いの恥ずかしいところを晒し合えるなんて……私たち、凄く深いところで繋がり合えてる気がする<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺もメルエルに甘えていいんだって気づけた
line = "俺もメルエルに甘えていいんだって気づけた"

[[dialogue]]
speaker = "unk"
# メルエルが甘えてくれるようになったから
line = "メルエルが甘えてくれるようになったから"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「そっか<emoji=heart04>　本当に、どれもこれも、ちっちゃい私に感謝だね<emoji=heart04>」
line = "「そっか<emoji=heart04>　本当に、どれもこれも、ちっちゃい私に感謝だね<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「えへへ<emoji=heart04>　なら今日は、もっともっと会長くんがしてみたいこと……教えてほしいな♪」
line = "「えへへ<emoji=heart04>　なら今日は、もっともっと会長くんがしてみたいこと……教えてほしいな♪」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「私も、好きな人が望んでいることなら、すごく嬉しくて、どんなことでもドキドキしちゃうと思うから<emoji=heart04>」
line = "「私も、好きな人が望んでいることなら、すごく嬉しくて、どんなことでもドキドキしちゃうと思うから<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# なら、試してみたいことがあって……
line = "なら、試してみたいことがあって……"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「――『天使の羽』を触ってみたい？」
line = "「――『天使の羽』を触ってみたい？」"

[[dialogue]]
speaker = "unk"
# 俺は頷いて、言葉を続ける。
line = "俺は頷いて、言葉を続ける。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「――天使の羽に強い気持ちを込めながら触ると、その気持ちが流れ込んできて、伝わるらしい……？」
line = "「――天使の羽に強い気持ちを込めながら触ると、その気持ちが流れ込んできて、伝わるらしい……？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「あ……お父さんやお母さんが、大切な人以外に羽を触らせちゃダメだよって教育してくれてたのって、そういうことだったのかな？」
line = "「あ……お父さんやお母さんが、大切な人以外に羽を触らせちゃダメだよって教育してくれてたのって、そういうことだったのかな？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「うん<emoji=heart04>　会長くんなら、もちろんいいよ<emoji=heart04>　というか、私の羽に触っていいのは、世界でただ一人、会長くんだけなんだから<emoji=heart04>」
line = "「うん<emoji=heart04>　会長くんなら、もちろんいいよ<emoji=heart04>　というか、私の羽に触っていいのは、世界でただ一人、会長くんだけなんだから<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そうして、俺に身を委ねるように、背中の羽をこちらへ差し出してくるメルエル。
line = "そうして、俺に身を委ねるように、背中の羽をこちらへ差し出してくるメルエル。"

[[dialogue]]
speaker = "unk"
# 俺はドキドキしながら、彼女の羽に手で触れて、優しく撫でる。
line = "俺はドキドキしながら、彼女の羽に手で触れて、優しく撫でる。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「んっ<emoji=heart04>　はあぁっ……<emoji=heart04>　こ、これ……すごいかも……<emoji=heart04>」
line = "「んっ<emoji=heart04>　はあぁっ……<emoji=heart04>　こ、これ……すごいかも……<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「会長くんの『愛』が、直接流れ込んでくる感じがして、体がなんだか熱くなってきちゃう……<emoji=heart04>」
line = "「会長くんの『愛』が、直接流れ込んでくる感じがして、体がなんだか熱くなってきちゃう……<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「あっ……ふあぁっ<emoji=heart04>　会長くんが私のこと、どれだけ好きって思ってくれてるか、わかるよぉ<emoji=heart04>」
line = "「あっ……ふあぁっ<emoji=heart04>　会長くんが私のこと、どれだけ好きって思ってくれてるか、わかるよぉ<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「はあぁっ……<emoji=heart04>　これ続けてたら私、嬉しくなり過ぎて、頭がメルトしちゃうよぉ……<emoji=heart04>」
line = "「はあぁっ……<emoji=heart04>　これ続けてたら私、嬉しくなり過ぎて、頭がメルトしちゃうよぉ……<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「会長くんからの愛をいっぱい注がれて、私、もう……<emoji=heart04>」
line = "「会長くんからの愛をいっぱい注がれて、私、もう……<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「キス……して欲しくなってきちゃった<emoji=heart04>」
line = "「キス……して欲しくなってきちゃった<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# わかったと頷いて、俺はメルエルの唇を奪う。
line = "わかったと頷いて、俺はメルエルの唇を奪う。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「会長くん<emoji=heart04>　んっ……ちゅっ<emoji=heart04>」
line = "「会長くん<emoji=heart04>　んっ……ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺はキスをしながら、またメルエルの翼に触れて、優しく撫でる。
line = "俺はキスをしながら、またメルエルの翼に触れて、優しく撫でる。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「あぁっ<emoji=heart04>　会長くんの気持ち、羽からまた、流れ込んできちゃう……<emoji=heart04>」
line = "「あぁっ<emoji=heart04>　会長くんの気持ち、羽からまた、流れ込んできちゃう……<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「私の『好き』って気持ち、いっぱい教えて欲しいって、伝わってくる……<emoji=heart04>」
line = "「私の『好き』って気持ち、いっぱい教えて欲しいって、伝わってくる……<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「んんぅ……<emoji=heart04>　じゃあ、私は……キスと言葉で、いっぱい伝えるね<emoji=heart04>」
line = "「んんぅ……<emoji=heart04>　じゃあ、私は……キスと言葉で、いっぱい伝えるね<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「会長くん、好きぃ<emoji=heart04>　好き……大好きぃ<emoji=heart04>」
line = "「会長くん、好きぃ<emoji=heart04>　好き……大好きぃ<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「愛してるの……<emoji=heart04>　ちゅっ<emoji=heart04>　ちゅっ……<emoji=heart04>」
line = "「愛してるの……<emoji=heart04>　ちゅっ<emoji=heart04>　ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# メルエル、俺も大好きだ
line = "メルエル、俺も大好きだ"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「あっ<emoji=heart04>　ふあぁぁっ、会長くぅん<emoji=heart04>　そんな耳元で囁いたりしたら、またメルトしちゃうよぉ……<emoji=heart04>」
line = "「あっ<emoji=heart04>　ふあぁぁっ、会長くぅん<emoji=heart04>　そんな耳元で囁いたりしたら、またメルトしちゃうよぉ……<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「んんぅ……<emoji=heart04>　私も大好きぃ<emoji=heart04>　んっ……ちゅっ<emoji=heart04>」
line = "「んんぅ……<emoji=heart04>　私も大好きぃ<emoji=heart04>　んっ……ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺たちはこの日、数え切れない程に『好き』という気持ちを、お互いに伝え合うのだった。
line = "俺たちはこの日、数え切れない程に『好き』という気持ちを、お互いに伝え合うのだった。"
