[[dialogue]]
speaker = "unk"
# 第３話,環、新星学園へ,P
line = "第３話,環、新星学園へ,P"

[[dialogue]]
speaker = "unk"
# 『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』との決着は近い──だからこそ最後の瞬間まで、かけがえのない学園生活を謳歌しよう。
line = "『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』との決着は近い──だからこそ最後の瞬間まで、かけがえのない学園生活を謳歌しよう。"

[[dialogue]]
speaker = "unk"
# 俺たちの日常を守りたい。かけがえのない平和を続けていく──そう強く実感することが、創造神との戦いで何よりも大切なことだと思うから。
line = "俺たちの日常を守りたい。かけがえのない平和を続けていく──そう強く実感することが、創造神との戦いで何よりも大切なことだと思うから。"

[[dialogue]]
speaker = "ラクシャ"
# 「おっじゃましまーす！　多忙な会長を借りに来ました～♪」
line = "「おっじゃましまーす！　多忙な会長を借りに来ました～♪」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら、うふふ♪　元気いっぱいね、環ちゃん」
line = "「あらあら、うふふ♪　元気いっぱいね、環ちゃん」"

[[dialogue]]
speaker = "アナ"
# 「ようこそいらっしゃいました。会長の仕事はもうすぐ終わります。少々お待ちください」
line = "「ようこそいらっしゃいました。会長の仕事はもうすぐ終わります。少々お待ちください」"

[[dialogue]]
speaker = "マトイ"
# 「また新星学園の制服を着た市倉さんが見られるだなんて、何だか感動かも」
line = "「また新星学園の制服を着た市倉さんが見られるだなんて、何だか感動かも」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ていうかびっくりしたわ！　髪を下ろしたら、雰囲気ぜんぜん違うのね！」
line = "「ていうかびっくりしたわ！　髪を下ろしたら、雰囲気ぜんぜん違うのね！」"

[[dialogue]]
speaker = "ラクシャ"
# 「まあねー。ああして髪を結ぶのは、一種のスイッチみたいなものだったから」
line = "「まあねー。ああして髪を結ぶのは、一種のスイッチみたいなものだったから」"

[[dialogue]]
speaker = "ラクシャ"
# 「守護天使ラクシャから、ただのキュートな天使の学園生・市倉環になるために必要なルーティンってわけ」
line = "「守護天使ラクシャから、ただのキュートな天使の学園生・市倉環になるために必要なルーティンってわけ」"

[[dialogue]]
speaker = "unk"
# もう少しだけ待っててくれるか
line = "もう少しだけ待っててくれるか"

[[dialogue]]
speaker = "unk"
# キュートな天使、環ちゃん
line = "キュートな天使、環ちゃん"

[[dialogue]]
speaker = "ラクシャ"
# 「そこはツッコむところなんだけどなー……。ま、いいや。了解でーす、っと」
line = "「そこはツッコむところなんだけどなー……。ま、いいや。了解でーす、っと」"

[[dialogue]]
speaker = "アナ"
# 「どうぞ、お茶です」
line = "「どうぞ、お茶です」"

[[dialogue]]
speaker = "ラクシャ"
# 「サンキュー、アナ。うん……おいしいや！」
line = "「サンキュー、アナ。うん……おいしいや！」"

[[dialogue]]
speaker = "unk"
# 環とは過去に色々なことがあったが……彼女の行動は全てリクリエを防ぎ、デネブとアルタイルを存続させるためにこそあった。
line = "環とは過去に色々なことがあったが……彼女の行動は全てリクリエを防ぎ、デネブとアルタイルを存続させるためにこそあった。"

[[dialogue]]
speaker = "unk"
# そのことを皆承知しているから、以前と同じような距離感を取り戻すことができていた。雑談にも華が咲いている様子で──
line = "そのことを皆承知しているから、以前と同じような距離感を取り戻すことができていた。雑談にも華が咲いている様子で──"

[[dialogue]]
speaker = "マトイ"
# 「会長を監視して、守ることも女神様からの命令だったんだよね。やっぱり大変だった？」
line = "「会長を監視して、守ることも女神様からの命令だったんだよね。やっぱり大変だった？」"

[[dialogue]]
speaker = "ラクシャ"
# 「大変なんてものじゃないよ、マトイ！　キミたちも知ってるでしょ、彼のバイト遍歴のやばさ！」
line = "「大変なんてものじゃないよ、マトイ！　キミたちも知ってるでしょ、彼のバイト遍歴のやばさ！」"

[[dialogue]]
speaker = "ラクシャ"
# 「交通量調査、ゲームセンター、ペットショップ。回転寿司屋にチェーンのカレースタンド……まだこの辺りはいいんだけど」
line = "「交通量調査、ゲームセンター、ペットショップ。回転寿司屋にチェーンのカレースタンド……まだこの辺りはいいんだけど」"

[[dialogue]]
speaker = "ラクシャ"
# 「冷凍マグロの倉庫仕分けに、芸能事務所のアシスタント……土木作業員に、ヒーローショーの怪人役──」
line = "「冷凍マグロの倉庫仕分けに、芸能事務所のアシスタント……土木作業員に、ヒーローショーの怪人役──」"

[[dialogue]]
speaker = "ラクシャ"
# 「ライフセーバーを始めたと思ったら、今度は女装メイド喫茶に出勤して……ボクがただの天使だったら今ごろ過労で力尽きてるね」
line = "「ライフセーバーを始めたと思ったら、今度は女装メイド喫茶に出勤して……ボクがただの天使だったら今ごろ過労で力尽きてるね」"

[[dialogue]]
speaker = "ラクシャ"
# 「いつモンスターに襲われるかわかんないから、できる限り傍に居なきゃならなくて……はは。いったい何枚の履歴書を書いたことか……」
line = "「いつモンスターに襲われるかわかんないから、できる限り傍に居なきゃならなくて……はは。いったい何枚の履歴書を書いたことか……」"

[[dialogue]]
speaker = "ラクシャ"
# 「やることが……やることが多い！！　ってなったよね。ぶっちゃけボク、忙しすぎて何回か記憶が飛んでるし」
line = "「やることが……やることが多い！！　ってなったよね。ぶっちゃけボク、忙しすぎて何回か記憶が飛んでるし」"

[[dialogue]]
speaker = "アナ"
# 「改めて聞くに人を辞めていますね、うちの会長は」
line = "「改めて聞くに人を辞めていますね、うちの会長は」"

[[dialogue]]
speaker = "ヴィーナス"
# 「パパは魔王だもの！　当然よね♪」
line = "「パパは魔王だもの！　当然よね♪」"

[[dialogue]]
speaker = "マトイ"
# 「それ説明になってる……？」
line = "「それ説明になってる……？」"

[[dialogue]]
speaker = "ラクシャ"
# 「おかげでなんでも１人でできるようになっちゃったよ……みんなも自宅の水道管が詰まったら言いなよ。ボク、直せるから」
line = "「おかげでなんでも１人でできるようになっちゃったよ……みんなも自宅の水道管が詰まったら言いなよ。ボク、直せるから」"

[[dialogue]]
speaker = "unk"
# 俺も直せるぞ！
line = "俺も直せるぞ！"

[[dialogue]]
speaker = "ラクシャ"
# 「キミは早く仕事終わらせなよ……彼女が待ってるんですけどー？」
line = "「キミは早く仕事終わらせなよ……彼女が待ってるんですけどー？」"

[[dialogue]]
speaker = "unk"
# ごめんなさい……
line = "ごめんなさい……"

[[dialogue]]
speaker = "マトイ"
# 「今から思えば、よく会長にバレなかったね？　それだけ色んなバイト先で出会ってたら……」
line = "「今から思えば、よく会長にバレなかったね？　それだけ色んなバイト先で出会ってたら……」"

[[dialogue]]
speaker = "アナ"
# 「はい。市倉さんに何か目的があるのでは、と勘繰りそうなものですが」
line = "「はい。市倉さんに何か目的があるのでは、と勘繰りそうなものですが」"

[[dialogue]]
speaker = "ラクシャ"
# 「ああ、その心配はいらないよ。彼、超がつく鈍感野郎だから」
line = "「ああ、その心配はいらないよ。彼、超がつく鈍感野郎だから」"

[[dialogue]]
speaker = "ラクシャ"
# 「ボクが『将来のために貯金したくてさー』ってテキトー言ったのを、ず～っと信じてたからね」
line = "「ボクが『将来のために貯金したくてさー』ってテキトー言ったのを、ず～っと信じてたからね」"

[[dialogue]]
speaker = "ラクシャ"
# 「『そうなんだ、俺も学費を貯めてるんだ。お互い頑張ろう』とか言っちゃって……」
line = "「『そうなんだ、俺も学費を貯めてるんだ。お互い頑張ろう』とか言っちゃって……」"

[[dialogue]]
speaker = "ラクシャ"
# 「ストーカーだと誤解されたらどうしようとか、色々言い訳考えてたのにね。張り合いなかったなあ」
line = "「ストーカーだと誤解されたらどうしようとか、色々言い訳考えてたのにね。張り合いなかったなあ」"

[[dialogue]]
speaker = "マトイ"
# 「会長、その察しの悪さはちょっとまずいと思うよ！？」
line = "「会長、その察しの悪さはちょっとまずいと思うよ！？」"

[[dialogue]]
speaker = "unk"
# それに環も、労働が好きなのかと……
line = "それに環も、労働が好きなのかと……"

[[dialogue]]
speaker = "unk"
# 昔は、学費のことで頭がいっぱいで……
line = "昔は、学費のことで頭がいっぱいで……"

[[dialogue]]
speaker = "ラクシャ"
# 「華の女学生だよこっちは！？　誰が好き好んで、冷凍マグロの仕分けとか、土木工事をするのさ！？」
line = "「華の女学生だよこっちは！？　誰が好き好んで、冷凍マグロの仕分けとか、土木工事をするのさ！？」"

[[dialogue]]
speaker = "ラクシャ"
# 「オシャレなカフェとかで働くでしょ、普通！！」
line = "「オシャレなカフェとかで働くでしょ、普通！！」"

[[dialogue]]
speaker = "アナ"
# 「ごもっともすぎます。反論の余地がありません」
line = "「ごもっともすぎます。反論の余地がありません」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら、うふふ♪」
line = "「あらあら、うふふ♪」"

[[dialogue]]
speaker = "unk"
# 確かに言われてみれば、俺は鈍感だったのかも……反省だ。
line = "確かに言われてみれば、俺は鈍感だったのかも……反省だ。"

[[dialogue]]
speaker = "ラクシャ"
# 「よーやく終わったみたいだね。あー、お腹空いた。ね、久しぶりの新星学園だし、カフェテリアで何か食べようよ」
line = "「よーやく終わったみたいだね。あー、お腹空いた。ね、久しぶりの新星学園だし、カフェテリアで何か食べようよ」"

[[dialogue]]
speaker = "unk"
# 最近、味が変わったんだ
line = "最近、味が変わったんだ"

[[dialogue]]
speaker = "unk"
# 環のお気に入りだったカレーにするか
line = "環のお気に入りだったカレーにするか"

[[dialogue]]
speaker = "ラクシャ"
# 「そうなの！？　え、それは楽しみだね。よーし、行こ！　会長！」
line = "「そうなの！？　え、それは楽しみだね。よーし、行こ！　会長！」"

[[dialogue]]
speaker = "アナ"
# 「会長、腕を引っ張られて行きましたね。守護天使様と仲良しなようで何よりです」
line = "「会長、腕を引っ張られて行きましたね。守護天使様と仲良しなようで何よりです」"

[[dialogue]]
speaker = "サーシャ"
# 「平和ね～。この平和を守るためにも……」
line = "「平和ね～。この平和を守るためにも……」"

[[dialogue]]
speaker = "マトイ"
# 「はい。絶対に負けられません！」
line = "「はい。絶対に負けられません！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「よーしっ、私たちもご飯にしましょう！　それが終わったら特訓よ！」
line = "「よーしっ、私たちもご飯にしましょう！　それが終わったら特訓よ！」"

[[dialogue]]
speaker = "unk"
# ドタバタで、賑やかで──この平和を守るためにも負けられない。
line = "ドタバタで、賑やかで──この平和を守るためにも負けられない。"

[[dialogue]]
speaker = "unk"
# 俺は改めて、決意を固めるのだった──
line = "俺は改めて、決意を固めるのだった──"
