[[dialogue]]
speaker = "unk"
# 第１話,突然の変身,P
line = "第１話,突然の変身,P"

[[dialogue]]
speaker = "unk"
# 放課後、本を借りようと思って図書館を訪ねると──
line = "放課後、本を借りようと思って図書館を訪ねると──"

[[dialogue]]
speaker = "リィベル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# 華やかな衣装に身を包んだリィベルがカウンターに座っていた。
line = "華やかな衣装に身を包んだリィベルがカウンターに座っていた。"

[[dialogue]]
speaker = "unk"
# 俺の視線に気が付いたのか、リィベルがこちらを軽く睨む。
line = "俺の視線に気が付いたのか、リィベルがこちらを軽く睨む。"

[[dialogue]]
speaker = "リィベル"
# 「な、何よ。……何か言いたいことがあるんでしょう」
line = "「な、何よ。……何か言いたいことがあるんでしょう」"

[[dialogue]]
speaker = "unk"
# すっごく似合ってる！
line = "すっごく似合ってる！"

[[dialogue]]
speaker = "リィベル"
# 「はぁ！？」
line = "「はぁ！？」"

[[dialogue]]
speaker = "リィベル"
# 「……そうじゃなくて、他に言うことがあるでしょう？」
line = "「……そうじゃなくて、他に言うことがあるでしょう？」"

[[dialogue]]
speaker = "unk"
# ……はちゃめちゃに可愛い？
line = "……はちゃめちゃに可愛い？"

[[dialogue]]
speaker = "リィベル"
# 「っ！　そ、そういうことじゃないわよ！」
line = "「っ！　そ、そういうことじゃないわよ！」"

[[dialogue]]
speaker = "モネ"
# 「は～い、図書館ではお静かに……って会長じゃないですか。どうしたんですか？」
line = "「は～い、図書館ではお静かに……って会長じゃないですか。どうしたんですか？」"

[[dialogue]]
speaker = "リィベル"
# 「どうしたもこうしたもないわ。魔王が私のこの格好を可愛いとか似合ってるとか言って話にならないの」
line = "「どうしたもこうしたもないわ。魔王が私のこの格好を可愛いとか似合ってるとか言って話にならないの」"

[[dialogue]]
speaker = "モネ"
# 「それは会長の言うとおりだと思いますけど……ちょうどいい機会ですから、この姿について、会長に相談してみましょう」
line = "「それは会長の言うとおりだと思いますけど……ちょうどいい機会ですから、この姿について、会長に相談してみましょう」"

[[dialogue]]
speaker = "リィベル"
# 「この魔王、頼りになるのかしら……。はぁ、まぁいいわ」
line = "「この魔王、頼りになるのかしら……。はぁ、まぁいいわ」"

[[dialogue]]
speaker = "リィベル"
# 「信じられないかもしれないけれど、朝起きたらこの格好になっていて、元に戻れないの。おかげでみんな制服を着ている中、これで授業を受ける羽目になったわ……」
line = "「信じられないかもしれないけれど、朝起きたらこの格好になっていて、元に戻れないの。おかげでみんな制服を着ている中、これで授業を受ける羽目になったわ……」"

[[dialogue]]
speaker = "unk"
# 星騎士あるあるだから気にしないで
line = "星騎士あるあるだから気にしないで"

[[dialogue]]
speaker = "リィベル"
# 「そうなの！？」
line = "「そうなの！？」"

[[dialogue]]
speaker = "unk"
# ある日突然、星騎士の戦闘服が変わって元に戻らない──まれによくある話だ。
line = "ある日突然、星騎士の戦闘服が変わって元に戻らない──まれによくある話だ。"

[[dialogue]]
speaker = "モネ"
# 「はい。この図書館にもトワちゃん先生が書かれたレポートで記録が残っています」
line = "「はい。この図書館にもトワちゃん先生が書かれたレポートで記録が残っています」"

[[dialogue]]
speaker = "モネ"
# 「結婚したい気持ちが溢れて戦闘服がウェディングドレスになったとか、異空間に閉じ込められたと思ったらバニー服を着ていた、などですね」
line = "「結婚したい気持ちが溢れて戦闘服がウェディングドレスになったとか、異空間に閉じ込められたと思ったらバニー服を着ていた、などですね」"

[[dialogue]]
speaker = "unk"
# バニーは俺も当事者なのだが、黙っておこう。傷口を自分から広げる真似はしない。
line = "バニーは俺も当事者なのだが、黙っておこう。傷口を自分から広げる真似はしない。"

[[dialogue]]
speaker = "モネ"
# 「また、自力で戦闘服を変化させられる方もいらっしゃいますね。ただ、その場合は、細部の調整が難しいので大胆なデザインになることもあるようです」
line = "「また、自力で戦闘服を変化させられる方もいらっしゃいますね。ただ、その場合は、細部の調整が難しいので大胆なデザインになることもあるようです」"

[[dialogue]]
speaker = "リィベル"
# 「なるほど。モネがたまに着ている、サンタみたいな水着みたいな戦闘服は調整がうまくいかなかったのね」
line = "「なるほど。モネがたまに着ている、サンタみたいな水着みたいな戦闘服は調整がうまくいかなかったのね」"

[[dialogue]]
speaker = "モネ"
# 「いえ、あれは……ヘレナさんのデザインした人工戦闘服なのでまた別というか……その、あまり、話題にしないでもらえると助かります……」
line = "「いえ、あれは……ヘレナさんのデザインした人工戦闘服なのでまた別というか……その、あまり、話題にしないでもらえると助かります……」"

[[dialogue]]
speaker = "リィベル"
# 「そう……ひとまず星騎士の戦闘服が変化することは分かったわ。でも、私のこれについては原因からして不明のままよ」
line = "「そう……ひとまず星騎士の戦闘服が変化することは分かったわ。でも、私のこれについては原因からして不明のままよ」"

[[dialogue]]
speaker = "unk"
# 星騎士の場合、外的な要因で戦闘服が変化したケースが多い。
line = "星騎士の場合、外的な要因で戦闘服が変化したケースが多い。"

[[dialogue]]
speaker = "unk"
# リィベルは厳密には星騎士ではないので、単純に当てはめることはできないが……
line = "リィベルは厳密には星騎士ではないので、単純に当てはめることはできないが……"

[[dialogue]]
speaker = "リィベル"
# 「え？　……昨日、変わったことはなかったか？　別に何も。いつも通りに登校して授業を受けて、放課後は図書委員の仕事をしながら魔将の候補者を探していたわ」
line = "「え？　……昨日、変わったことはなかったか？　別に何も。いつも通りに登校して授業を受けて、放課後は図書委員の仕事をしながら魔将の候補者を探していたわ」"

[[dialogue]]
speaker = "リィベル"
# 「そのあとは……寮に帰って、晩ご飯を食べて、お風呂入って、寝たわ。いわゆる普通の生活ね」
line = "「そのあとは……寮に帰って、晩ご飯を食べて、お風呂入って、寝たわ。いわゆる普通の生活ね」"

[[dialogue]]
speaker = "リィベル"
# 「……あ、あと、寝る前に小説をいくらか読んだわ。でも、本当にそれくらいで、何も変わったことなんてなかったのよ」
line = "「……あ、あと、寝る前に小説をいくらか読んだわ。でも、本当にそれくらいで、何も変わったことなんてなかったのよ」"

[[dialogue]]
speaker = "モネ"
# 「ちなみに、小説は何を読みました？」
line = "「ちなみに、小説は何を読みました？」"

[[dialogue]]
speaker = "リィベル"
# 「主人公が死後、中華風の世界に生まれ変わって宮廷で成り上がるやつ。つい盛り上がって、シリーズ一気読みしてしまったわ。おかげで今も少し眠たいのよ」
line = "「主人公が死後、中華風の世界に生まれ変わって宮廷で成り上がるやつ。つい盛り上がって、シリーズ一気読みしてしまったわ。おかげで今も少し眠たいのよ」"

[[dialogue]]
speaker = "モネ"
# 「ああ、あの！　コミック化もしてる人気シリーズですね。じゃあ原因はそれです」
line = "「ああ、あの！　コミック化もしてる人気シリーズですね。じゃあ原因はそれです」"

[[dialogue]]
speaker = "unk"
# それだね
line = "それだね"

[[dialogue]]
speaker = "リィベル"
# 「はぁ！？　小説を読んだだけで戦闘服が変わるわけないでしょう！？」
line = "「はぁ！？　小説を読んだだけで戦闘服が変わるわけないでしょう！？」"

[[dialogue]]
speaker = "モネ"
# 「いいえ、リィベルさん。図書委員たる者が何を言っているんですか」
line = "「いいえ、リィベルさん。図書委員たる者が何を言っているんですか」"

[[dialogue]]
speaker = "モネ"
# 「一冊の本、いえ、たった一文でさえ人生を変えうるのです。シリーズ一気読みしたら戦闘服が変わるなんてむしろ当たり前じゃないですか」
line = "「一冊の本、いえ、たった一文でさえ人生を変えうるのです。シリーズ一気読みしたら戦闘服が変わるなんてむしろ当たり前じゃないですか」"

[[dialogue]]
speaker = "モネ"
# 「リィベルさんの衣装、どこかで見たと思ったんですけど、まさしく小説の挿絵にそっくりです」
line = "「リィベルさんの衣装、どこかで見たと思ったんですけど、まさしく小説の挿絵にそっくりです」"

[[dialogue]]
speaker = "リィベル"
# 「そうかしら……そうかも……」
line = "「そうかしら……そうかも……」"

[[dialogue]]
speaker = "unk"
# リィベルは特殊な存在だ。彼女の力の源は深淵書庫の魔本であり、他の本に影響されるというのはあり得る。
line = "リィベルは特殊な存在だ。彼女の力の源は深淵書庫の魔本であり、他の本に影響されるというのはあり得る。"

[[dialogue]]
speaker = "リィベル"
# 「でも待って。仮にそうだとして……仮に、仮によ。私がえっちな小説や露出度多めの漫画を読んだら、『そういう格好』になってしまう可能性があるということ？」
line = "「でも待って。仮にそうだとして……仮に、仮によ。私がえっちな小説や露出度多めの漫画を読んだら、『そういう格好』になってしまう可能性があるということ？」"

[[dialogue]]
speaker = "？？？"
# 「その質問には私から答えよう」
line = "「その質問には私から答えよう」"

[[dialogue]]
speaker = "リィベル"
# 「あなたは──」
line = "「あなたは──」"

[[dialogue]]
speaker = "ジグ"
# 「私はレナーテ・<ruby=ジグ>Ｚ</ruby>・サイフリート。ここではジグと呼ばれているよ。私の『<ruby=てんき>天機</ruby>の星眼』は視たものの可能性を見通すことができる」
line = "「私はレナーテ・<ruby>Ｚ<rt>ジグ</rt></ruby>・サイフリート。ここではジグと呼ばれているよ。私の『<ruby>天機<rt>てんき</rt></ruby>の星眼』は視たものの可能性を見通すことができる」"

[[dialogue]]
speaker = "リィベル"
# 「つまり……」
line = "「つまり……」"

[[dialogue]]
speaker = "ジグ"
# 「そう、私には視えているよ。君がえっちな本を読んで、えっちな姿になる可能性が」
line = "「そう、私には視えているよ。君がえっちな本を読んで、えっちな姿になる可能性が」"

[[dialogue]]
speaker = "リィベル"
# 「はぁ～～～～～！？」
line = "「はぁ～～～～～！？」"

[[dialogue]]
speaker = "ジグ"
# 「ふふっ。面白い話が聞こえたからつい悪ノリしてしまった。まぁ、信じるかどうかは君次第だけどね。じゃあ、これで失礼するよ」
line = "「ふふっ。面白い話が聞こえたからつい悪ノリしてしまった。まぁ、信じるかどうかは君次第だけどね。じゃあ、これで失礼するよ」"

[[dialogue]]
speaker = "リィベル"
# 「ちょっと、待ちなさ……行ってしまったわね」
line = "「ちょっと、待ちなさ……行ってしまったわね」"

[[dialogue]]
speaker = "リィベル"
# 「はぁ～……なんかどっと疲れたわ。モネ、本を選んでちょうだい。絶対いかがわしい気分にならない真面目なのを」
line = "「はぁ～……なんかどっと疲れたわ。モネ、本を選んでちょうだい。絶対いかがわしい気分にならない真面目なのを」"

[[dialogue]]
speaker = "モネ"
# 「そうですね……では、難解な哲学の本などいかがでしょう」
line = "「そうですね……では、難解な哲学の本などいかがでしょう」"

[[dialogue]]
speaker = "リィベル"
# 「いいわね。これでこの姿も解除されるし、変な恰好になることもないはず」
line = "「いいわね。これでこの姿も解除されるし、変な恰好になることもないはず」"

[[dialogue]]
speaker = "unk"
# ──翌日、リィベルは哲学の本をしっかり読み込み、哲学者っぽい服装で登校してきた。
line = "──翌日、リィベルは哲学の本をしっかり読み込み、哲学者っぽい服装で登校してきた。"

[[dialogue]]
speaker = "リィベル"
# 「どうしてこうなるのよ～～～～～っ！？」
line = "「どうしてこうなるのよ～～～～～っ！？」"

[[dialogue]]
speaker = "unk"
# ちなみに、戦闘服は深淵書庫に戻ると解除された。
line = "ちなみに、戦闘服は深淵書庫に戻ると解除された。"
