[[dialogue]]
speaker = "unk"
# 第４話,恋は先手必勝,P
line = "第４話,恋は先手必勝,P"

[[dialogue]]
speaker = "ウルスラ"
# （私が会長さんに抱くこの気持ちは……）
line = "（私が会長さんに抱くこの気持ちは……）"

[[dialogue]]
speaker = "ウルスラ"
# （いえ、そういうのではないんです。そういうのでは……あら？　あそこの子たち……）
line = "（いえ、そういうのではないんです。そういうのでは……あら？　あそこの子たち……）"

[[dialogue]]
speaker = "女学生Ａ"
# 「危なかったところに会長さんが颯爽と駆けつけてくれてさー、格好良かったー！　それからすっかりファンになっちゃってー！」
line = "「危なかったところに会長さんが颯爽と駆けつけてくれてさー、格好良かったー！　それからすっかりファンになっちゃってー！」"

[[dialogue]]
speaker = "女学生Ｂ"
# 「わたしバレンタインチョコもあげちゃった！　いっぱい抱えてたから迷惑になるかもだったけど、やっぱ我慢できなくって！」
line = "「わたしバレンタインチョコもあげちゃった！　いっぱい抱えてたから迷惑になるかもだったけど、やっぱ我慢できなくって！」"

[[dialogue]]
speaker = "女学生Ｃ"
# 「パッと見は優しそうなのに、いざという時は凛々しくて男らしくて……やっぱり星徒会長様推せる～っ！」
line = "「パッと見は優しそうなのに、いざという時は凛々しくて男らしくて……やっぱり星徒会長様推せる～っ！」"

[[dialogue]]
speaker = "ウルスラ"
# （会長さんの話を……やはり学園の多くの女子が会長さんに憧れの感情を抱いているみたいですね）
line = "（会長さんの話を……やはり学園の多くの女子が会長さんに憧れの感情を抱いているみたいですね）"

[[dialogue]]
speaker = "ウルスラ"
# （ここまでの一極集中は正直、不自然ですらあります。何故、会長さんの周りにはここまで愛が集まっているのか）
line = "（ここまでの一極集中は正直、不自然ですらあります。何故、会長さんの周りにはここまで愛が集まっているのか）"

[[dialogue]]
speaker = "ウルスラ"
# （バレンタインは過ぎ、シーズンオフではありますけど、愛の伝道師としてしっかり調査するべきですよね）
line = "（バレンタインは過ぎ、シーズンオフではありますけど、愛の伝道師としてしっかり調査するべきですよね）"

[[dialogue]]
speaker = "ウルスラ"
# （会長さんがこれほどまでにおモテになる根源がどこにあるのか……見極めなくては！）
line = "（会長さんがこれほどまでにおモテになる根源がどこにあるのか……見極めなくては！）"

[[dialogue]]
speaker = "ウルスラ"
# 「じーーーーーっ……！」
line = "「じーーーーーっ……！」"

[[dialogue]]
speaker = "unk"
# 最近、よく物陰から視線を感じる。
line = "最近、よく物陰から視線を感じる。"

[[dialogue]]
speaker = "unk"
# まるで矢のように鋭い、しかし甘さも感じさせる不思議な眼差し……
line = "まるで矢のように鋭い、しかし甘さも感じさせる不思議な眼差し……"

[[dialogue]]
speaker = "unk"
# （この視線はウルスラだな……）
line = "（この視線はウルスラだな……）"

[[dialogue]]
speaker = "ウルスラ"
# （確かに会長さんは可愛らしくも凛々しい顔立ちをされていますが……男性アイドルのように図抜けているわけではありません）
line = "（確かに会長さんは可愛らしくも凛々しい顔立ちをされていますが……男性アイドルのように図抜けているわけではありません）"

[[dialogue]]
speaker = "ウルスラ"
# （運動も人並み以上、成績も優秀みたいですね）
line = "（運動も人並み以上、成績も優秀みたいですね）"

[[dialogue]]
speaker = "ウルスラ"
# （手先も器用なんですね。これまでにいくつもバイトをされて、苦労もされている……）
line = "（手先も器用なんですね。これまでにいくつもバイトをされて、苦労もされている……）"

[[dialogue]]
speaker = "ウルスラ"
# （星徒会役員の皆さんや、シャロンさんやイレーナさんたちとも仲は良いみたいですが）
line = "（星徒会役員の皆さんや、シャロンさんやイレーナさんたちとも仲は良いみたいですが）"

[[dialogue]]
speaker = "ウルスラ"
# （特定の異性──いわゆる、恋人はいらっしゃらないようですね……ホッ）
line = "（特定の異性──いわゆる、恋人はいらっしゃらないようですね……ホッ）"

[[dialogue]]
speaker = "ウルスラ"
# （『ホッ』……？）
line = "（『ホッ』……？）"

[[dialogue]]
speaker = "ウルスラ"
# 「私、会長さんに恋人がいないことに安心してしまっている……！？」
line = "「私、会長さんに恋人がいないことに安心してしまっている……！？」"

[[dialogue]]
speaker = "ウルスラ"
# 「じーーーっ……メモメモ」
line = "「じーーーっ……メモメモ」"

[[dialogue]]
speaker = "unk"
# （何かメモしてる……）
line = "（何かメモしてる……）"

[[dialogue]]
speaker = "unk"
# ウルスラの視線を感じつつ、自分も彼女が気になってしまう。
line = "ウルスラの視線を感じつつ、自分も彼女が気になってしまう。"

[[dialogue]]
speaker = "unk"
# 俺が戦っている時も……
line = "俺が戦っている時も……"

[[dialogue]]
speaker = "ウルスラ"
# 「さすが会長さん、一般の方を庇いながら戦っていますね……」
line = "「さすが会長さん、一般の方を庇いながら戦っていますね……」"

[[dialogue]]
speaker = "ウルスラ"
# 「しかもただ守るだけでなく、優しく言葉をかけて……危機に立たされた時に『大丈夫だよ』と言われたら、ときめいてしまいます……」
line = "「しかもただ守るだけでなく、優しく言葉をかけて……危機に立たされた時に『大丈夫だよ』と言われたら、ときめいてしまいます……」"

[[dialogue]]
speaker = "ウルスラ"
# 「あ、私も見ているばかりではなく攻撃しなくては……」
line = "「あ、私も見ているばかりではなく攻撃しなくては……」"

[[dialogue]]
speaker = "モンスター"
# 「イーッ！」
line = "「イーッ！」"

[[dialogue]]
speaker = "モンスター"
# 「イ～～～ッ！？」
line = "「イ～～～ッ！？」"

[[dialogue]]
speaker = "unk"
# ウルスラの矢が正確にモンスターを射貫く。
line = "ウルスラの矢が正確にモンスターを射貫く。"

[[dialogue]]
speaker = "unk"
# 俺は気付かないふりをしつつ、周囲のモンスターを全滅させた。
line = "俺は気付かないふりをしつつ、周囲のモンスターを全滅させた。"

[[dialogue]]
speaker = "ウルスラ"
# 「ああ、いつの間にか会長さんのことばかり見ています……」
line = "「ああ、いつの間にか会長さんのことばかり見ています……」"

[[dialogue]]
speaker = "ウルスラ"
# 「でも、それがちっとも嫌ではなくて……むしろ、会長さんのことを想い浮かべるだけで切なさと多幸感で満たされて……」
line = "「でも、それがちっとも嫌ではなくて……むしろ、会長さんのことを想い浮かべるだけで切なさと多幸感で満たされて……」"

[[dialogue]]
speaker = "ウルスラ"
# 「私、会長さんを、本当に好きになってしまったのでしょうか……！？　そんなの……サランさんやヒルディオーネさんが言っていた通りではないですか……！」
line = "「私、会長さんを、本当に好きになってしまったのでしょうか……！？　そんなの……サランさんやヒルディオーネさんが言っていた通りではないですか……！」"

[[dialogue]]
speaker = "ウルスラ"
# 「これが人を好きになるということ……！？」
line = "「これが人を好きになるということ……！？」"

[[dialogue]]
speaker = "ウルスラ"
# 「一週間ほど会長さんを見てきましたが、特定の恋人はいらっしゃらないようですし……これはもしかして、チャンス、なのでは……！？」
line = "「一週間ほど会長さんを見てきましたが、特定の恋人はいらっしゃらないようですし……これはもしかして、チャンス、なのでは……！？」"

[[dialogue]]
speaker = "ウルスラ"
# 「ウルスラ……ウルスラ・バレンタイン……あなたのポリシーは何ですか？」
line = "「ウルスラ……ウルスラ・バレンタイン……あなたのポリシーは何ですか？」"

[[dialogue]]
speaker = "ウルスラ"
# 「そう、『命短し恋せよ乙女』！　私だって１人の等身大の乙女なのですから！」
line = "「そう、『命短し恋せよ乙女』！　私だって１人の等身大の乙女なのですから！」"

[[dialogue]]
speaker = "ウルスラ"
# 「もしこの恋に破れて、会長さんがダメだったとしても、次の恋に──」
line = "「もしこの恋に破れて、会長さんがダメだったとしても、次の恋に──」"

[[dialogue]]
speaker = "ウルスラ"
# 「──そんなのイヤっ！　絶対にイヤです……っ！」
line = "「──そんなのイヤっ！　絶対にイヤです……っ！」"

[[dialogue]]
speaker = "ウルスラ"
# 「会長さんしか、会長さんじゃなきゃダメなんです……ああ、そうですよね……！　それは私の決定的な過ちでした……！」
line = "「会長さんしか、会長さんじゃなきゃダメなんです……ああ、そうですよね……！　それは私の決定的な過ちでした……！」"

[[dialogue]]
speaker = "ウルスラ"
# 「恋は七転び八起きではありませんよね」
line = "「恋は七転び八起きではありませんよね」"

[[dialogue]]
speaker = "ウルスラ"
# 「この人しかいないと思うくらいでなくては、次なんて考えているようでは……その人を心から愛しているだなんて言えるはずないではないですか……！」
line = "「この人しかいないと思うくらいでなくては、次なんて考えているようでは……その人を心から愛しているだなんて言えるはずないではないですか……！」"

[[dialogue]]
speaker = "ウルスラ"
# 「本当の愛も知らないのに、伝道師だの恋愛相談だの、なんて<ruby=おこ>烏滸</ruby>がましい……でも！」
line = "「本当の愛も知らないのに、伝道師だの恋愛相談だの、なんて<ruby>烏滸<rt>おこ</rt></ruby>がましい……でも！」"

[[dialogue]]
speaker = "ウルスラ"
# 「皆さんを出し抜くのは心苦しいですけど、溢れ出る想いは止められません」
line = "「皆さんを出し抜くのは心苦しいですけど、溢れ出る想いは止められません」"

[[dialogue]]
speaker = "ウルスラ"
# 「恋は戦い。先手必勝なのですから」
line = "「恋は戦い。先手必勝なのですから」"

[[dialogue]]
speaker = "unk"
# ある日の放課後。ウルスラが星徒会室にやってきて──
line = "ある日の放課後。ウルスラが星徒会室にやってきて──"

[[dialogue]]
speaker = "ウルスラ"
# 「会長さん、あなたが好きです！」
line = "「会長さん、あなたが好きです！」"

[[dialogue]]
speaker = "ウルスラ"
# 「私と──付き合ってください！」
line = "「私と──付き合ってください！」"

[[dialogue]]
speaker = "unk"
# 俺も君のことが気になっていた
line = "俺も君のことが気になっていた"

[[dialogue]]
speaker = "ウルスラ"
# 「──っ！！」
line = "「──っ！！」"

[[dialogue]]
speaker = "unk"
# 恋に悩むウルスラが可愛かった
line = "恋に悩むウルスラが可愛かった"

[[dialogue]]
speaker = "ウルスラ"
# 「そんなところを見られていたのですか！？　お恥ずかしい……」
line = "「そんなところを見られていたのですか！？　お恥ずかしい……」"

[[dialogue]]
speaker = "ウルスラ"
# 「でもあなたを射止められたのなら結果オーライ、怪我の功名です」
line = "「でもあなたを射止められたのなら結果オーライ、怪我の功名です」"

[[dialogue]]
speaker = "ウルスラ"
# 「恥じらっている暇などありません。『命短し恋せよ乙女』──なのですから」
line = "「恥じらっている暇などありません。『命短し恋せよ乙女』──なのですから」"

[[dialogue]]
speaker = "ウルスラ"
# 「さぁ、存分に愛し合いましょう！」
line = "「さぁ、存分に愛し合いましょう！」"

[[dialogue]]
speaker = "unk"
# そして新たなカップル誕生の知らせは、新星・流星の両校に稲妻のように轟くのだった。
line = "そして新たなカップル誕生の知らせは、新星・流星の両校に稲妻のように轟くのだった。"
