[[dialogue]]
speaker = "unk"
# 第２話,購買部の名売り子,P
line = "第２話,購買部の名売り子,P"

[[dialogue]]
speaker = "unk"
# 昼休み──昼食を終え、お腹は満たされたが、なんとなく口寂しさを感じていた。
line = "昼休み──昼食を終え、お腹は満たされたが、なんとなく口寂しさを感じていた。"

[[dialogue]]
speaker = "unk"
# 午後の授業に挑むに辺り、満足感の得られる、食後のおやつが欲しい。
line = "午後の授業に挑むに辺り、満足感の得られる、食後のおやつが欲しい。"

[[dialogue]]
speaker = "unk"
# そう、例えば……アナも好きそうな饅頭とか大福といった和の甘味を──
line = "そう、例えば……アナも好きそうな饅頭とか大福といった和の甘味を──"

[[dialogue]]
speaker = "アニマ"
# 「おや、いらっしゃい、会長。何かご入用かナ？」
line = "「おや、いらっしゃい、会長。何かご入用かナ？」"

[[dialogue]]
speaker = "アニマ"
# 「甘いもの？　ならちょうど良かった。おーい、ウルスラ。会長さんが甘味をご所望ダ♪」
line = "「甘いもの？　ならちょうど良かった。おーい、ウルスラ。会長さんが甘味をご所望ダ♪」"

[[dialogue]]
speaker = "ウルスラ"
# 「まあ、いらっしゃいませ、会長さん。購買部にようこそ」
line = "「まあ、いらっしゃいませ、会長さん。購買部にようこそ」"

[[dialogue]]
speaker = "アニマ"
# 「おやおや、会長。ウルスラとも知り合いなのカ？　さすがは学園中の女の子に満遍なく粉かけているだけはあるネ」
line = "「おやおや、会長。ウルスラとも知り合いなのカ？　さすがは学園中の女の子に満遍なく粉かけているだけはあるネ」"

[[dialogue]]
speaker = "ウルスラ"
# 「はい、会長さんと過ごした熱い夜……私、一生忘れません……<emoji=heart04>」
line = "「はい、会長さんと過ごした熱い夜……私、一生忘れません……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 誤解される言い回し！
line = "誤解される言い回し！"

[[dialogue]]
speaker = "アニマ"
# 「別にナニがあってどんな関係だろうが、咎めやしないサ」
line = "「別にナニがあってどんな関係だろうが、咎めやしないサ」"

[[dialogue]]
speaker = "アニマ"
# 「だがこう見えて、ウルスラはかなりのヤリ手でネ」
line = "「だがこう見えて、ウルスラはかなりのヤリ手でネ」"

[[dialogue]]
speaker = "ウルスラ"
# 「はっ……！　会長さん、甘いもの……特にチョコレートに多く含まれるカカオポリフェノールとテオブロミンが不足している顔をしていらっしゃいます」
line = "「はっ……！　会長さん、甘いもの……特にチョコレートに多く含まれるカカオポリフェノールとテオブロミンが不足している顔をしていらっしゃいます」"

[[dialogue]]
speaker = "unk"
# どんな顔！？
line = "どんな顔！？"

[[dialogue]]
speaker = "ウルスラ"
# 「お疲れなのでしょう？　目の下にうっすらとクマもできていますし……満足な睡眠も取れていないようにお見受けしますけど」
line = "「お疲れなのでしょう？　目の下にうっすらとクマもできていますし……満足な睡眠も取れていないようにお見受けしますけど」"

[[dialogue]]
speaker = "ウルスラ"
# 「その表情、どうやら図星のようですね。ふふふ」
line = "「その表情、どうやら図星のようですね。ふふふ」"

[[dialogue]]
speaker = "ウルスラ"
# 「そんな会長さんにオススメなのが……こちらのチョコレートです」
line = "「そんな会長さんにオススメなのが……こちらのチョコレートです」"

[[dialogue]]
speaker = "unk"
# ウルスラが指し示したのは、ハートの箱にリボンがラッピングされたチョコレートだ。
line = "ウルスラが指し示したのは、ハートの箱にリボンがラッピングされたチョコレートだ。"

[[dialogue]]
speaker = "unk"
# これってバレンタインの売れ残りでは？
line = "これってバレンタインの売れ残りでは？"

[[dialogue]]
speaker = "ウルスラ"
# 「そうなんです。やっぱりこのパッケージだと売れ残ってしまうんですよね」
line = "「そうなんです。やっぱりこのパッケージだと売れ残ってしまうんですよね」"

[[dialogue]]
speaker = "ウルスラ"
# 「ですが賞味期限はまだまだ長いですし、有名チョコレートブランドと同じ産地のカカオ豆を使用しています。味も折り紙付き」
line = "「ですが賞味期限はまだまだ長いですし、有名チョコレートブランドと同じ産地のカカオ豆を使用しています。味も折り紙付き」"

[[dialogue]]
speaker = "ウルスラ"
# 「くちどけも極上で、一口頬張るだけで幸せな甘さに満たされるんです」
line = "「くちどけも極上で、一口頬張るだけで幸せな甘さに満たされるんです」"

[[dialogue]]
speaker = "ウルスラ"
# 「会長さん、チョコレートを食べ過ぎて鼻血が出ちゃった、なんて経験はおありではないですか？」
line = "「会長さん、チョコレートを食べ過ぎて鼻血が出ちゃった、なんて経験はおありではないですか？」"

[[dialogue]]
speaker = "ウルスラ"
# 「実は昔は、チョコレートは体が高揚する媚薬として扱われた歴史もありまして」
line = "「実は昔は、チョコレートは体が高揚する媚薬として扱われた歴史もありまして」"

[[dialogue]]
speaker = "ウルスラ"
# 「チョコレートは疲労回復に滋養強壮、成人病リスクを軽減するとまでいわれているんです。万能にして万病に効く栄養補給フードなんですよ」
line = "「チョコレートは疲労回復に滋養強壮、成人病リスクを軽減するとまでいわれているんです。万能にして万病に効く栄養補給フードなんですよ」"

[[dialogue]]
speaker = "ウルスラ"
# 「食後の口直しと、午後を頑張る栄養補給に最適ですよ」
line = "「食後の口直しと、午後を頑張る栄養補給に最適ですよ」"

[[dialogue]]
speaker = "unk"
# （チョコの気分になってきたかも……）
line = "（チョコの気分になってきたかも……）"

[[dialogue]]
speaker = "アニマ"
# 「フヒ、不思議ダロウ？　ウルスラのセールストークを聞いていると、何故か財布のヒモが緩んでしまうのサ」
line = "「フヒ、不思議ダロウ？　ウルスラのセールストークを聞いていると、何故か財布のヒモが緩んでしまうのサ」"

[[dialogue]]
speaker = "ウルスラ"
# 「極上３つ星チョコレートが、今ならなんと５０％ＯＦＦ！　３つ購入すると更にお安くなって、とってもお買い得なんです！　今だけ、ですよ」
line = "「極上３つ星チョコレートが、今ならなんと５０％ＯＦＦ！　３つ購入すると更にお安くなって、とってもお買い得なんです！　今だけ、ですよ」"

[[dialogue]]
speaker = "ウルスラ"
# 「お買い得でも、男がハートのパッケージの商品を買うのは恥ずかしい……？　なるほど、そうお考えの方もいらっしゃるでしょう」
line = "「お買い得でも、男がハートのパッケージの商品を買うのは恥ずかしい……？　なるほど、そうお考えの方もいらっしゃるでしょう」"

[[dialogue]]
speaker = "ウルスラ"
# 「でしたら……私からお渡しするという体でしたら、いかがでしょう？」
line = "「でしたら……私からお渡しするという体でしたら、いかがでしょう？」"

[[dialogue]]
speaker = "ウルスラ"
# 「会長さん、私からのチョコレート、受け取ってください<emoji=heart04>」
line = "「会長さん、私からのチョコレート、受け取ってください<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# あっ、はい
line = "あっ、はい"

[[dialogue]]
speaker = "ウルスラ"
# 「ありがとうございます<emoji=heart04>　５００テルスになりまーす<emoji=heart04>」
line = "「ありがとうございます<emoji=heart04>　５００テルスになりまーす<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# はっ！？　買わされてしまった！
line = "はっ！？　買わされてしまった！"

[[dialogue]]
speaker = "アニマ"
# 「どうダ、会長。ウルスラはなかなかやるだろう。これからも購買部をご贔屓にナ♪」
line = "「どうダ、会長。ウルスラはなかなかやるだろう。これからも購買部をご贔屓にナ♪」"

[[dialogue]]
speaker = "ウルスラ"
# 「またのご来店、お待ちしておりまーす<emoji=heart04>」
line = "「またのご来店、お待ちしておりまーす<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# アニマ先輩とウルスラに見送られつつ、購買を後にする。
line = "アニマ先輩とウルスラに見送られつつ、購買を後にする。"

[[dialogue]]
speaker = "unk"
# お金を払ったのに、なんだかちょっぴり幸せな気分だった。
line = "お金を払ったのに、なんだかちょっぴり幸せな気分だった。"

[[dialogue]]
speaker = "unk"
# そして、このチョコレートは戦闘や業務の疲れを吹き飛ばしてくれる最高の強壮剤となり、やがて在庫を買い占めるまでに至るのだった。
line = "そして、このチョコレートは戦闘や業務の疲れを吹き飛ばしてくれる最高の強壮剤となり、やがて在庫を買い占めるまでに至るのだった。"
