[[dialogue]]
speaker = "unk"
# 完全下校時刻が迫る黄昏時。俺が１人で執務をしているところにやってきたのは──
line = "完全下校時刻が迫る黄昏時。俺が１人で執務をしているところにやってきたのは──"

[[dialogue]]
speaker = "ジグ"
# 「やぁ、まだ星徒会の仕事をしているのかい？」
line = "「やぁ、まだ星徒会の仕事をしているのかい？」"

[[dialogue]]
speaker = "クロト"
# 「ああ、<b>レナーテ</b>か。今日の分はもう終わるところ。そっちは何してたんだ？」
line = "「ああ、<b>レナーテ</b>か。今日の分はもう終わるところ。そっちは何してたんだ？」"

[[dialogue]]
speaker = "ジグ"
# 「アガサと模擬戦をしてきたところさ。私の勝ちだったけどね」
line = "「アガサと模擬戦をしてきたところさ。私の勝ちだったけどね」"

[[dialogue]]
speaker = "unk"
# 今も梨緒に何度も勝負を挑まれているそうだけど、レナーテも少し楽しそうだ。
line = "今も梨緒に何度も勝負を挑まれているそうだけど、レナーテも少し楽しそうだ。"

[[dialogue]]
speaker = "ジグ"
# 「おや？　熱い視線を感じるね？」
line = "「おや？　熱い視線を感じるね？」"

[[dialogue]]
speaker = "クロト"
# 「う……」
line = "「う……」"

[[dialogue]]
speaker = "unk"
# 戦闘服の露出が大きい星騎士は他にもいるが、レナーテは一際肌が出ている。
line = "戦闘服の露出が大きい星騎士は他にもいるが、レナーテは一際肌が出ている。"

[[dialogue]]
speaker = "unk"
# 形のいい胸や、引き締まったお腹、際どい股間に、張りのある太もも……どこをとっても魅力的で、つい視線が吸い寄せられる。
line = "形のいい胸や、引き締まったお腹、際どい股間に、張りのある太もも……どこをとっても魅力的で、つい視線が吸い寄せられる。"

[[dialogue]]
speaker = "ジグ"
# 「別にごまかさなくていいよ。君なら近くでじっくり見てもいいからね」
line = "「別にごまかさなくていいよ。君なら近くでじっくり見てもいいからね」"

[[dialogue]]
speaker = "unk"
# そんなこと言われると、余計に目が離せなくなってしまう。
line = "そんなこと言われると、余計に目が離せなくなってしまう。"

[[dialogue]]
speaker = "ジグ"
# 「む。可能性が見えた。劣情を催した君が、私を無理やり押し倒してしまう可能性が──なんてね」
line = "「む。可能性が見えた。劣情を催した君が、私を無理やり押し倒してしまう可能性が──なんてね」"

[[dialogue]]
speaker = "クロト"
# 「俺はそんなことしないよ」
line = "「俺はそんなことしないよ」"

[[dialogue]]
speaker = "ジグ"
# 「本当にそうかな？　全くありえないとは言えない気がするけど」
line = "「本当にそうかな？　全くありえないとは言えない気がするけど」"

[[dialogue]]
speaker = "ジグ"
# 「だけど……たまにはそういうのもいいかもしれないね？」
line = "「だけど……たまにはそういうのもいいかもしれないね？」"

[[dialogue]]
speaker = "ジグ"
# 「あっ……私にこんな格好をさせるなんて、君は随分といい趣味を持っているようだ」
line = "「あっ……私にこんな格好をさせるなんて、君は随分といい趣味を持っているようだ」"

[[dialogue]]
speaker = "unk"
# 星徒会室の窓に手を突かせると、自然とお尻を突き出す体勢になった。
line = "星徒会室の窓に手を突かせると、自然とお尻を突き出す体勢になった。"

[[dialogue]]
speaker = "unk"
# 戦闘服から鎧だけを脱いだ姿は裸よりも煽情的で、細い腰から肉感的なお尻へのラインに男の本能を刺激される。
line = "戦闘服から鎧だけを脱いだ姿は裸よりも煽情的で、細い腰から肉感的なお尻へのラインに男の本能を刺激される。"

[[dialogue]]
speaker = "クロト"
# 「レナーテがこうしようって言ったくせに」
line = "「レナーテがこうしようって言ったくせに」"

[[dialogue]]
speaker = "ジグ"
# 「ふふ。それはそうだけどね」
line = "「ふふ。それはそうだけどね」"

[[dialogue]]
speaker = "unk"
# 俺たちは正式に恋人という関係になったわけではない。
line = "俺たちは正式に恋人という関係になったわけではない。"

[[dialogue]]
speaker = "unk"
# それでもある日レナーテに誘われて、それ以来、しばしば肌を重ねるようになっていた。
line = "それでもある日レナーテに誘われて、それ以来、しばしば肌を重ねるようになっていた。"

[[dialogue]]
speaker = "ジグ"
# 「今日は手籠めにするつもりで、思いっきり犯してくれていいからね？」
line = "「今日は手籠めにするつもりで、思いっきり犯してくれていいからね？」"

[[dialogue]]
speaker = "クロト"
# 「いいんだな？　途中でやめられないぞ」
line = "「いいんだな？　途中でやめられないぞ」"

[[dialogue]]
speaker = "ジグ"
# 「ああ、大丈夫。思い切り羽目を外したい気分なんだ」
line = "「ああ、大丈夫。思い切り羽目を外したい気分なんだ」"

[[dialogue]]
speaker = "unk"
# 期待しているのか、レナーテの秘部が淡く濡れてきた。
line = "期待しているのか、レナーテの秘部が淡く濡れてきた。"

[[dialogue]]
speaker = "unk"
# 愛液を塗り付けるようにペニスを摩擦させる。
line = "愛液を塗り付けるようにペニスを摩擦させる。"

[[dialogue]]
speaker = "ジグ"
# 「ぁんっ……<emoji=heart04>　君のここ、大きく、熱くなってる<emoji=heart04>」
line = "「ぁんっ……<emoji=heart04>　君のここ、大きく、熱くなってる<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「もっと元気になるように、媚びた方がいいかい？　君のおっきくて、硬いおち○ぽ、私のおま○こにちょうだい──って」
line = "「もっと元気になるように、媚びた方がいいかい？　君のおっきくて、硬いおち○ぽ、私のおま○こにちょうだい──って」"

[[dialogue]]
speaker = "unk"
# あえてはしたない言葉を使いながら、細い腰をくねらせ、ふりふりとお尻を振るレナーテ。
line = "あえてはしたない言葉を使いながら、細い腰をくねらせ、ふりふりとお尻を振るレナーテ。"

[[dialogue]]
speaker = "unk"
# その煽情的な姿に矢も楯もたまらず、怒張したペニスを突き立てた。
line = "その煽情的な姿に矢も楯もたまらず、怒張したペニスを突き立てた。"

[[dialogue]]
speaker = "ジグ"
# 「ふぁああああっ……<emoji=heart04>　私の中、広げられてっ……はああぁっ<emoji=heart04>」
line = "「ふぁああああっ……<emoji=heart04>　私の中、広げられてっ……はああぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ペニスが蜜で濡れた粘膜に呑み込まれ、心地良い圧迫感に包まれる。
line = "ペニスが蜜で濡れた粘膜に呑み込まれ、心地良い圧迫感に包まれる。"

[[dialogue]]
speaker = "ジグ"
# 「はぁ……はぁ……おち○ぽ、熱くて、大きくて、君が私の中にいるのを感じるよ……<emoji=heart04>」
line = "「はぁ……はぁ……おち○ぽ、熱くて、大きくて、君が私の中にいるのを感じるよ……<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「んんっ……<emoji=heart04>　君のおち○ぽ、私の中でビクビクしてる……<emoji=heart04>　嬉しそうに脈打ってるね……<emoji=heart04>」
line = "「んんっ……<emoji=heart04>　君のおち○ぽ、私の中でビクビクしてる……<emoji=heart04>　嬉しそうに脈打ってるね……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 愛液のトロトロの感触と、膣の肉の弾力、熱い体温が相まって極上の快感をもたらしてくれる。
line = "愛液のトロトロの感触と、膣の肉の弾力、熱い体温が相まって極上の快感をもたらしてくれる。"

[[dialogue]]
speaker = "ジグ"
# 「はぁ、ふぅ……早く……動いてくれ……<emoji=heart04>」
line = "「はぁ、ふぅ……早く……動いてくれ……<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「私のおま○こ、いっぱい突いて、おち○ぽ気持ち良くなってくれ……<emoji=heart04>　私のこと、無茶苦茶にして……<emoji=heart04>」
line = "「私のおま○こ、いっぱい突いて、おち○ぽ気持ち良くなってくれ……<emoji=heart04>　私のこと、無茶苦茶にして……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 催促するように、自分から小さく腰を揺らすレナーテ。
line = "催促するように、自分から小さく腰を揺らすレナーテ。"

[[dialogue]]
speaker = "unk"
# 強く求められて俺も昂り、レナーテの腰を掴んでペニスを突き出した。
line = "強く求められて俺も昂り、レナーテの腰を掴んでペニスを突き出した。"

[[dialogue]]
speaker = "ジグ"
# 「ひぁああっ……<emoji=heart04>　はぁっ……はっ……あっ……んんっ……<emoji=heart04>　私の中で、君が、動いてるっ……<emoji=heart04>」
line = "「ひぁああっ……<emoji=heart04>　はぁっ……はっ……あっ……んんっ……<emoji=heart04>　私の中で、君が、動いてるっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「んっ、はあぁっ……中で、擦れて……ふあぁっ……ああっ……<emoji=heart04>　はあぁ、はっ、あっ……んんっ……<emoji=heart04>」
line = "「んっ、はあぁっ……中で、擦れて……ふあぁっ……ああっ……<emoji=heart04>　はあぁ、はっ、あっ……んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「そう、いいよ……んっ……ふぁ……ああぁっ<emoji=heart04>　私のおま○こ、君のおち○ぽの、形になってる……<emoji=heart04>」
line = "「そう、いいよ……んっ……ふぁ……ああぁっ<emoji=heart04>　私のおま○こ、君のおち○ぽの、形になってる……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ペニスを突き入れる度、窓に押し付けられた大きな胸が柔らかそうに形を変える。
line = "ペニスを突き入れる度、窓に押し付けられた大きな胸が柔らかそうに形を変える。"

[[dialogue]]
speaker = "unk"
# 亀頭が深いところまで届くと、膣内が嬉しそうにきゅっと締まって反応した。
line = "亀頭が深いところまで届くと、膣内が嬉しそうにきゅっと締まって反応した。"

[[dialogue]]
speaker = "ジグ"
# 「んはっ、はぁっ……はっ、はぁっ……<emoji=heart04>　あっ、はぁ……私の中、君のでズボズボってされて……ふはぁ、はぁ、あっ、んんっ……<emoji=heart04>」
line = "「んはっ、はぁっ……はっ、はぁっ……<emoji=heart04>　あっ、はぁ……私の中、君のでズボズボってされて……ふはぁ、はぁ、あっ、んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「おち○ぽで突かれて……あっ……お腹の奥、熱くなる……<emoji=heart04>　はぁ、ふぅっ……んっ、ああっ……<emoji=heart04>」
line = "「おち○ぽで突かれて……あっ……お腹の奥、熱くなる……<emoji=heart04>　はぁ、ふぅっ……んっ、ああっ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 平行世界ベガでは、レナーテは誰よりも強く、誰からも尊敬される星騎士だったという。
line = "平行世界ベガでは、レナーテは誰よりも強く、誰からも尊敬される星騎士だったという。"

[[dialogue]]
speaker = "unk"
# そんな彼女が星徒会室であられもない姿になり、俺のペニスでよがっていた。
line = "そんな彼女が星徒会室であられもない姿になり、俺のペニスでよがっていた。"

[[dialogue]]
speaker = "ジグ"
# 「あっ、はぁ……んぁ……はぁんっ<emoji=heart04>　ここでしていると、星徒会のみんなの前で、エッチしているみたいだ……」
line = "「あっ、はぁ……んぁ……はぁんっ<emoji=heart04>　ここでしていると、星徒会のみんなの前で、エッチしているみたいだ……」"

[[dialogue]]
speaker = "ジグ"
# 「はぁっ、ふっ、んんっ……おち○ぽで貫かれて、おま○こがきゅうってなる……<emoji=heart04>」
line = "「はぁっ、ふっ、んんっ……おち○ぽで貫かれて、おま○こがきゅうってなる……<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「んぁっ、はぁっ、はっ、あぁんっ<emoji=heart04>　おま○こ、気持ち良くて、もっとして欲しくなる……<emoji=heart04>　はぁっ、はっ……あっ……ひあぁっ<emoji=heart04>」
line = "「んぁっ、はぁっ、はっ、あぁんっ<emoji=heart04>　おま○こ、気持ち良くて、もっとして欲しくなる……<emoji=heart04>　はぁっ、はっ……あっ……ひあぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# レナーテは艶めかしい嬌声を上げ、俺とのエッチに夢中になっている。
line = "レナーテは艶めかしい嬌声を上げ、俺とのエッチに夢中になっている。"

[[dialogue]]
speaker = "unk"
# だけど窓の向こうで、下校中の女子生徒がこちらを振り返ったような気がした。
line = "だけど窓の向こうで、下校中の女子生徒がこちらを振り返ったような気がした。"

[[dialogue]]
speaker = "ジグ"
# 「──ッ！？」
line = "「──ッ！？」"

[[dialogue]]
speaker = "unk"
# その瞬間、ぎゅっと膣が収縮し、ペニスを強く締め付けた。
line = "その瞬間、ぎゅっと膣が収縮し、ペニスを強く締め付けた。"

[[dialogue]]
speaker = "クロト"
# 「今、おま○こが締まったよ。見られて興奮するなんて変態なんだな」
line = "「今、おま○こが締まったよ。見られて興奮するなんて変態なんだな」"

[[dialogue]]
speaker = "ジグ"
# 「んっ……<emoji=heart04>　そんなことは……」
line = "「んっ……<emoji=heart04>　そんなことは……」"

[[dialogue]]
speaker = "クロト"
# 「ほら、あの生徒、こっちを見てる。エッチしてるところ見られてるよ」
line = "「ほら、あの生徒、こっちを見てる。エッチしてるところ見られてるよ」"

[[dialogue]]
speaker = "ジグ"
# 「んんんっ……<emoji=heart04>　見ないで、くれ……んっ……<emoji=heart04>　ひあぁっ、あっ、ああぁっ……知らない生徒の前で、こんな……ふああぁっ<emoji=heart04>」
line = "「んんんっ……<emoji=heart04>　見ないで、くれ……んっ……<emoji=heart04>　ひあぁっ、あっ、ああぁっ……知らない生徒の前で、こんな……ふああぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 実際にはあの生徒はたまたまこっちを振り返っただけで、俺たちには気付いていないだろう。
line = "実際にはあの生徒はたまたまこっちを振り返っただけで、俺たちには気付いていないだろう。"

[[dialogue]]
speaker = "unk"
# だけど興奮を盛り上げるスパイスとしては十分だ。
line = "だけど興奮を盛り上げるスパイスとしては十分だ。"

[[dialogue]]
speaker = "クロト"
# 「見られて余計濡れてるぞ。裸でも戦えるって言ってたし、見られるのが好きな淫乱なんじゃないか？」
line = "「見られて余計濡れてるぞ。裸でも戦えるって言ってたし、見られるのが好きな淫乱なんじゃないか？」"

[[dialogue]]
speaker = "ジグ"
# 「ち、違う……ぁっ、はぁっ……<emoji=heart04>　私は、淫乱じゃ……ない……んんっ<emoji=heart04>」
line = "「ち、違う……ぁっ、はぁっ……<emoji=heart04>　私は、淫乱じゃ……ない……んんっ<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「違わないだろ。この変態騎士」
line = "「違わないだろ。この変態騎士」"

[[dialogue]]
speaker = "ジグ"
# 「ああ──ああぁっ<emoji=heart04>　言わないで、くれ……はあぁ、あっ……ふぁああっ<emoji=heart04>」
line = "「ああ──ああぁっ<emoji=heart04>　言わないで、くれ……はあぁ、あっ……ふぁああっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 俺に詰られてゾクゾクと体を震わせるレナーテ。
line = "俺に詰られてゾクゾクと体を震わせるレナーテ。"

[[dialogue]]
speaker = "unk"
# 羞恥が快感になっているようで、蜜を溢れさせながら、きゅっと膣壁が締め付けてきた。
line = "羞恥が快感になっているようで、蜜を溢れさせながら、きゅっと膣壁が締め付けてきた。"

[[dialogue]]
speaker = "unk"
# それなら──
line = "それなら──"

[[dialogue]]
speaker = "クロト"
# 「そんなに見られるのが好きなら、レナーテのいやらしいところを全部見せつけてやろうじゃないか」
line = "「そんなに見られるのが好きなら、レナーテのいやらしいところを全部見せつけてやろうじゃないか」"

[[dialogue]]
speaker = "ジグ"
# 「～～～っ！」
line = "「～～～っ！」"

[[dialogue]]
speaker = "unk"
# みんなに見られるのを想像したのか、膣が強く締まり、痛いほどにペニスを絞る。
line = "みんなに見られるのを想像したのか、膣が強く締まり、痛いほどにペニスを絞る。"

[[dialogue]]
speaker = "ジグ"
# 「ああ、そうだ……はぁっ、あっ……<emoji=heart04>　私は犯されているところを見られて悦ぶ、浅ましい女なんだ……<emoji=heart04>」
line = "「ああ、そうだ……はぁっ、あっ……<emoji=heart04>　私は犯されているところを見られて悦ぶ、浅ましい女なんだ……<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「今の私は、淫乱なメスだ……<emoji=heart04>　あっ、はあぁっ<emoji=heart04>　だから君の欲望のまま、思う存分、犯してくれ……<emoji=heart04>」
line = "「今の私は、淫乱なメスだ……<emoji=heart04>　あっ、はあぁっ<emoji=heart04>　だから君の欲望のまま、思う存分、犯してくれ……<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「はあぁっ、はっ、ああぁっ<emoji=heart04>　壊れるくらい、強く……！　私を、快楽で塗り潰してくれ……！」
line = "「はあぁっ、はっ、ああぁっ<emoji=heart04>　壊れるくらい、強く……！　私を、快楽で塗り潰してくれ……！」"

[[dialogue]]
speaker = "unk"
# レナーテはリクリエの使徒から解放されたけど、その心はまだ壊れたままなのかもしれない。
line = "レナーテはリクリエの使徒から解放されたけど、その心はまだ壊れたままなのかもしれない。"

[[dialogue]]
speaker = "unk"
# 心の欠けた部分を快楽で埋めるように、あえて淫らなメスに堕ちている。
line = "心の欠けた部分を快楽で埋めるように、あえて淫らなメスに堕ちている。"

[[dialogue]]
speaker = "unk"
# それなら俺は──
line = "それなら俺は──"

[[dialogue]]
speaker = "ジグ"
# 「ひやぁああぁっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　んんんっ<emoji=heart04>　ズン、ズンって、激しいっ<emoji=heart04>　あぁっ<emoji=heart04>　はっ<emoji=heart04>　あぁんっ<emoji=heart04>」
line = "「ひやぁああぁっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　んんんっ<emoji=heart04>　ズン、ズンって、激しいっ<emoji=heart04>　あぁっ<emoji=heart04>　はっ<emoji=heart04>　あぁんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「んぁっ<emoji=heart04>　はっ<emoji=heart04>　あっ、ああぁんっ<emoji=heart04>　私の中、おち○ぽでぐちゃぐちゃにされてるっ<emoji=heart04>」
line = "「んぁっ<emoji=heart04>　はっ<emoji=heart04>　あっ、ああぁんっ<emoji=heart04>　私の中、おち○ぽでぐちゃぐちゃにされてるっ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「はぁっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　んんっ<emoji=heart04>　乱暴に突かれて、感じてるっ<emoji=heart04>　気持ち、いいっ<emoji=heart04>　はぁっ、あぁああっ<emoji=heart04>」
line = "「はぁっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　んんっ<emoji=heart04>　乱暴に突かれて、感じてるっ<emoji=heart04>　気持ち、いいっ<emoji=heart04>　はぁっ、あぁああっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# レナーテの腰を捕まえ、窓に押し付けながら思い切り突きまくる。
line = "レナーテの腰を捕まえ、窓に押し付けながら思い切り突きまくる。"

[[dialogue]]
speaker = "unk"
# するとレナーテのお尻に俺の下半身が当たり、肌がぶつかる音が響いた。
line = "するとレナーテのお尻に俺の下半身が当たり、肌がぶつかる音が響いた。"

[[dialogue]]
speaker = "ジグ"
# 「いい、いいよっ<emoji=heart04>　おち○ぽ、気持ちいいっ<emoji=heart04>　はぁっ、はあぁっ<emoji=heart04>　ふぁ──ああぁああっ<emoji=heart04>」
line = "「いい、いいよっ<emoji=heart04>　おち○ぽ、気持ちいいっ<emoji=heart04>　はぁっ、はあぁっ<emoji=heart04>　ふぁ──ああぁああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「ひぁああっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　んんっ<emoji=heart04>　ひやぁああっ<emoji=heart04>　んぁ──あ──あ──んん～～～っ<emoji=heart04>」
line = "「ひぁああっ<emoji=heart04>　あっ<emoji=heart04>　あっ<emoji=heart04>　んんっ<emoji=heart04>　ひやぁああっ<emoji=heart04>　んぁ──あ──あ──んん～～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 光る銀髪を振り乱しながら喘ぐレナーテ。
line = "光る銀髪を振り乱しながら喘ぐレナーテ。"

[[dialogue]]
speaker = "unk"
# その眩いばかりの美しさとは対照的に、お尻の肉が弾み、愛液がぐちゅぐちゅと音を立てる。
line = "その眩いばかりの美しさとは対照的に、お尻の肉が弾み、愛液がぐちゅぐちゅと音を立てる。"

[[dialogue]]
speaker = "ジグ"
# 「はっ、あっ<emoji=heart04>　もっと、もっと……<emoji=heart04>　もっと深く、もっと強く……突き立ててくれっ<emoji=heart04>」
line = "「はっ、あっ<emoji=heart04>　もっと、もっと……<emoji=heart04>　もっと深く、もっと強く……突き立ててくれっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 麗しい女騎士を犯す征服感を味わいながら、ペニスで一番奥を突く。
line = "麗しい女騎士を犯す征服感を味わいながら、ペニスで一番奥を突く。"

[[dialogue]]
speaker = "ジグ"
# 「ひやぁあああっ<emoji=heart04>　奥におち○ぽ来て、おま○こ、壊れそうっ<emoji=heart04>　ひあぁっ<emoji=heart04>　あっ<emoji=heart04>　んんぁああっ<emoji=heart04>」
line = "「ひやぁあああっ<emoji=heart04>　奥におち○ぽ来て、おま○こ、壊れそうっ<emoji=heart04>　ひあぁっ<emoji=heart04>　あっ<emoji=heart04>　んんぁああっ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「でもいい<emoji=heart04>　壊していい<emoji=heart04>　壊れしてくれ<emoji=heart04>　んぁっ<emoji=heart04>　あっ<emoji=heart04>　今は、気持ちいいのだけ、感じたいんだ<emoji=heart04>」
line = "「でもいい<emoji=heart04>　壊していい<emoji=heart04>　壊れしてくれ<emoji=heart04>　んぁっ<emoji=heart04>　あっ<emoji=heart04>　今は、気持ちいいのだけ、感じたいんだ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「ふああぁっ<emoji=heart04>　あっ<emoji=heart04>　んぁあっ<emoji=heart04>　私が私でなくなるくらい、めちゃくちゃにしてくれ<emoji=heart04>」
line = "「ふああぁっ<emoji=heart04>　あっ<emoji=heart04>　んぁあっ<emoji=heart04>　私が私でなくなるくらい、めちゃくちゃにしてくれ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 亀頭が子宮に届く度、レナーテの体がビクビクと小さく跳ね、嬌声が星徒会室に響く。
line = "亀頭が子宮に届く度、レナーテの体がビクビクと小さく跳ね、嬌声が星徒会室に響く。"

[[dialogue]]
speaker = "unk"
# そんなレナーテを窓の外に見せつけるように、しゃにむに奥を突き続ける。
line = "そんなレナーテを窓の外に見せつけるように、しゃにむに奥を突き続ける。"

[[dialogue]]
speaker = "ジグ"
# 「んん～～～～っ<emoji=heart04>　子宮に、おち○ぽ当たってっ<emoji=heart04>　すごいぃっ<emoji=heart04>　ひああっ<emoji=heart04>　んぁっ<emoji=heart04>　ああぁっ<emoji=heart04>」
line = "「んん～～～～っ<emoji=heart04>　子宮に、おち○ぽ当たってっ<emoji=heart04>　すごいぃっ<emoji=heart04>　ひああっ<emoji=heart04>　んぁっ<emoji=heart04>　ああぁっ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「私のおま○こ、太いおち○ぽでいっぱいになってるっ<emoji=heart04>　あっ、はぁっ<emoji=heart04>　これ、いいっ<emoji=heart04>」
line = "「私のおま○こ、太いおち○ぽでいっぱいになってるっ<emoji=heart04>　あっ、はぁっ<emoji=heart04>　これ、いいっ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「ふはぁ、はっ、あぁんっ<emoji=heart04>　おま○この奥、キュンキュンして、切なくなるっ<emoji=heart04>　あぁっ<emoji=heart04>　くるっ<emoji=heart04>　おま○こ、イッちゃいそうだっ<emoji=heart04>」
line = "「ふはぁ、はっ、あぁんっ<emoji=heart04>　おま○この奥、キュンキュンして、切なくなるっ<emoji=heart04>　あぁっ<emoji=heart04>　くるっ<emoji=heart04>　おま○こ、イッちゃいそうだっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# レナーテが絶頂に近づくにつれ、俺も限界が迫り、体の奥から熱がせり上がってくる。
line = "レナーテが絶頂に近づくにつれ、俺も限界が迫り、体の奥から熱がせり上がってくる。"

[[dialogue]]
speaker = "ジグ"
# 「んんっ<emoji=heart04>　私の中で、おち○ぽビクビクしてっ<emoji=heart04>　はぁっ<emoji=heart04>　あっ<emoji=heart04>　君も、イキそうなんだね<emoji=heart04>」
line = "「んんっ<emoji=heart04>　私の中で、おち○ぽビクビクしてっ<emoji=heart04>　はぁっ<emoji=heart04>　あっ<emoji=heart04>　君も、イキそうなんだね<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「んぁっ、はぁっ<emoji=heart04>　いいよっ<emoji=heart04>　中に出してくれっ<emoji=heart04>　あっ<emoji=heart04>　私も、子宮、切なくて、君の子種が欲しいんだっ<emoji=heart04>」
line = "「んぁっ、はぁっ<emoji=heart04>　いいよっ<emoji=heart04>　中に出してくれっ<emoji=heart04>　あっ<emoji=heart04>　私も、子宮、切なくて、君の子種が欲しいんだっ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「本能が、欲しがってる<emoji=heart04>　あっ、んんんっ<emoji=heart04>　孕ませるつもりでっ<emoji=heart04>　君の全部、私の子宮に注ぎ込んでくれっ<emoji=heart04>」
line = "「本能が、欲しがってる<emoji=heart04>　あっ、んんんっ<emoji=heart04>　孕ませるつもりでっ<emoji=heart04>　君の全部、私の子宮に注ぎ込んでくれっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# メスを孕ませる──それはオスの最大の悦びだ。
line = "メスを孕ませる──それはオスの最大の悦びだ。"

[[dialogue]]
speaker = "unk"
# レナーテに誘われ、本能に衝き動かされながら、ペニスを力任せに叩きつける。
line = "レナーテに誘われ、本能に衝き動かされながら、ペニスを力任せに叩きつける。"

[[dialogue]]
speaker = "ジグ"
# 「ふぁああぁ～～～っ<emoji=heart04>　あ──あ──あ──んんんっ<emoji=heart04>　おち○ぽ、種付けしようとしてるっ<emoji=heart04>」
line = "「ふぁああぁ～～～っ<emoji=heart04>　あ──あ──あ──んんんっ<emoji=heart04>　おち○ぽ、種付けしようとしてるっ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「ひやぁああっ<emoji=heart04>　んぁあっ<emoji=heart04>　んんんっ<emoji=heart04>　出してっ<emoji=heart04>　思いっきり、熱いの、注いでっ<emoji=heart04>　子宮いっぱいにして、私の奥まで、君のものにしてっ<emoji=heart04>」
line = "「ひやぁああっ<emoji=heart04>　んぁあっ<emoji=heart04>　んんんっ<emoji=heart04>　出してっ<emoji=heart04>　思いっきり、熱いの、注いでっ<emoji=heart04>　子宮いっぱいにして、私の奥まで、君のものにしてっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 生半可な射精ではもう満足できない。
line = "生半可な射精ではもう満足できない。"

[[dialogue]]
speaker = "unk"
# 今にも爆発しそうなのを堪え、最大限に高まったところをレナーテの奥に吐き出す……！
line = "今にも爆発しそうなのを堪え、最大限に高まったところをレナーテの奥に吐き出す……！"

[[dialogue]]
speaker = "ジグ"
# 「ふぁあっ<emoji=heart04>　ああぁっ<emoji=heart04> おち○ぽドクンドクンって、爆発しそうっ<emoji=heart04>　ああっ<emoji=heart04>　んんんっ<emoji=heart04>」
line = "「ふぁあっ<emoji=heart04>　ああぁっ<emoji=heart04> おち○ぽドクンドクンって、爆発しそうっ<emoji=heart04>　ああっ<emoji=heart04>　んんんっ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「私も、イキそうっ<emoji=heart04>　イクッ<emoji=heart04>　はぁっ<emoji=heart04>　はぁはっ<emoji=heart04>　あっ──ん──んん──ふぁああ～～っ<emoji=heart04>」
line = "「私も、イキそうっ<emoji=heart04>　イクッ<emoji=heart04>　はぁっ<emoji=heart04>　はぁはっ<emoji=heart04>　あっ──ん──んん──ふぁああ～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「ひぁっ<emoji=heart04>　あっ<emoji=heart04>　あぁっ<emoji=heart04>　おま○こイクッ<emoji=heart04>　種付けされて、イッちゃうっ<emoji=heart04>　ふぁっ──ぁっ──イッ、イクぅっ──」
line = "「ひぁっ<emoji=heart04>　あっ<emoji=heart04>　あぁっ<emoji=heart04>　おま○こイクッ<emoji=heart04>　種付けされて、イッちゃうっ<emoji=heart04>　ふぁっ──ぁっ──イッ、イクぅっ──」"

[[dialogue]]
speaker = "ジグ"
# 「ふぁああぁあああ～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「ふぁああぁあああ～～～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# レナーテの奥で欲望を解き放ち、亀頭を子宮口に密着させながら精を吐き出す。
line = "レナーテの奥で欲望を解き放ち、亀頭を子宮口に密着させながら精を吐き出す。"

[[dialogue]]
speaker = "ジグ"
# 「んんんっ……んっ……<emoji=heart04>　あっ……熱いっ<emoji=heart04>　はあぁっ……はっ……んんっ……<emoji=heart04>」
line = "「んんんっ……んっ……<emoji=heart04>　あっ……熱いっ<emoji=heart04>　はあぁっ……はっ……んんっ……<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「ドクドクって、おち○ぽ跳ねて……ぁっ……はっ……<emoji=heart04>　おま○この奥に、精液、注がれてる……ふあぁ……はぁ……っ<emoji=heart04>」
line = "「ドクドクって、おち○ぽ跳ねて……ぁっ……はっ……<emoji=heart04>　おま○この奥に、精液、注がれてる……ふあぁ……はぁ……っ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 全身を震わせながら、子宮で射精を受け止めるレナーテ。
line = "全身を震わせながら、子宮で射精を受け止めるレナーテ。"

[[dialogue]]
speaker = "unk"
# 同時に強く膣壁が収縮して、少しでも多く精を絞ろうと締め付けてくる。
line = "同時に強く膣壁が収縮して、少しでも多く精を絞ろうと締め付けてくる。"

[[dialogue]]
speaker = "ジグ"
# 「はぁ……あっ……まだ出てるっ<emoji=heart04>　私の子宮……君の精液で、いっぱいになってる……ん……はあぁ……<emoji=heart04>」
line = "「はぁ……あっ……まだ出てるっ<emoji=heart04>　私の子宮……君の精液で、いっぱいになってる……ん……はあぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 下半身に力を込め、一滴も出なくなるまでレナーテの中に注ぎ込んだ。
line = "下半身に力を込め、一滴も出なくなるまでレナーテの中に注ぎ込んだ。"

[[dialogue]]
speaker = "ジグ"
# 「はぁ、はぁ……ふはぁ……はあぁ……<emoji=heart04>」
line = "「はぁ、はぁ……ふはぁ……はあぁ……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# レナーテは荒い息を吐き、窓にもたれかかりながら脱力する。
line = "レナーテは荒い息を吐き、窓にもたれかかりながら脱力する。"

[[dialogue]]
speaker = "unk"
# ペニスが抜けた膣口からは、中に注いだ精液がドロリと溢れてきた。
line = "ペニスが抜けた膣口からは、中に注いだ精液がドロリと溢れてきた。"

[[dialogue]]
speaker = "ジグ"
# 「あ……君が出してくれたのが、こぼれてしまっている……<emoji=heart04>」
line = "「あ……君が出してくれたのが、こぼれてしまっている……<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「んん……たくさん、出したね……<emoji=heart04>　お腹が熱いよ……<emoji=heart04>」
line = "「んん……たくさん、出したね……<emoji=heart04>　お腹が熱いよ……<emoji=heart04>」"

[[dialogue]]
speaker = "クロト"
# 「レナーテ、今日のは……」
line = "「レナーテ、今日のは……」"

[[dialogue]]
speaker = "unk"
# 結局最後まで付き合ったけど、レナーテの様子には危うさを感じた。
line = "結局最後まで付き合ったけど、レナーテの様子には危うさを感じた。"

[[dialogue]]
speaker = "ジグ"
# 「言っておくけど、別に自棄になっているわけではないよ。今日は本当に羽目を外したかっただけさ」
line = "「言っておくけど、別に自棄になっているわけではないよ。今日は本当に羽目を外したかっただけさ」"

[[dialogue]]
speaker = "クロト"
# 「ならいいんだけど……」
line = "「ならいいんだけど……」"

[[dialogue]]
speaker = "ジグ"
# 「そんなに心配しなくても大丈夫だよ。せっかくアガサが助けてくれたんだし、自分を粗末に扱うつもりはない」
line = "「そんなに心配しなくても大丈夫だよ。せっかくアガサが助けてくれたんだし、自分を粗末に扱うつもりはない」"

[[dialogue]]
speaker = "ジグ"
# 「それに私を名前で呼んでくれる相手もいることだし」
line = "「それに私を名前で呼んでくれる相手もいることだし」"

[[dialogue]]
speaker = "クロト"
# 「う……」
line = "「う……」"

[[dialogue]]
speaker = "unk"
# 婉曲な、けれどストレートに伝わる言い方に、思わず照れてしまう。
line = "婉曲な、けれどストレートに伝わる言い方に、思わず照れてしまう。"

[[dialogue]]
speaker = "ジグ"
# 「さて、もう下校時間だ。星徒会長といえど、平時なら帰らないといけないね」
line = "「さて、もう下校時間だ。星徒会長といえど、平時なら帰らないといけないね」"

[[dialogue]]
speaker = "ジグ"
# 「でもその前に……ちゅっ<emoji=heart04>」
line = "「でもその前に……ちゅっ<emoji=heart04>」"

[[dialogue]]
speaker = "ジグ"
# 「んむぅ……ちゅる……ちゅるちゅるっ<emoji=heart04>　んふっ、んっ……んれろっ、じゅるるるっ<emoji=heart04>」
line = "「んむぅ……ちゅる……ちゅるちゅるっ<emoji=heart04>　んふっ、んっ……んれろっ、じゅるるるっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 時間ギリギリまで濃密なキスを交わし、下校時刻ちょうどに校門を出たのだった。
line = "時間ギリギリまで濃密なキスを交わし、下校時刻ちょうどに校門を出たのだった。"
