[[dialogue]]
speaker = "unk"
# 第３話,紅明と性教育の時間,P
line = "第３話,紅明と性教育の時間,P"

[[dialogue]]
speaker = "unk"
# ある日の放課後。クーシェンから空き教室に呼び出されて向かうと――
line = "ある日の放課後。クーシェンから空き教室に呼び出されて向かうと――"

[[dialogue]]
speaker = "紅明"
# 「クーちん、前に言ってた『正しい性教育』のお時間だぜ☆　アタシと一緒にエッチなお勉強するっしょ～！」
line = "「クーちん、前に言ってた『正しい性教育』のお時間だぜ☆　アタシと一緒にエッチなお勉強するっしょ～！」"

[[dialogue]]
speaker = "クーシェン"
# 「わ～い！　勉強はやだけど、エッチな内容ならやるやる～！」
line = "「わ～い！　勉強はやだけど、エッチな内容ならやるやる～！」"

[[dialogue]]
speaker = "紅明"
# 「うっし☆　じゃあ、まずはアタシが持ってきた秘蔵のエロ本の１ページ目から――」
line = "「うっし☆　じゃあ、まずはアタシが持ってきた秘蔵のエロ本の１ページ目から――」"

[[dialogue]]
speaker = "unk"
# ちょっと待てぇーい！！！
line = "ちょっと待てぇーい！！！"

[[dialogue]]
speaker = "クーシェン"
# 「あっ、にーにー♪」
line = "「あっ、にーにー♪」"

[[dialogue]]
speaker = "紅明"
# 「ありゃ！？　ダーリンが何故ここに？」
line = "「ありゃ！？　ダーリンが何故ここに？」"

[[dialogue]]
speaker = "クーシェン"
# 「ボクが呼んでたんだ～♪　ほら、にーにーもまだ子供だから、エッチな勉強をやるなら『大人ゲージ』を貯める為に誘ってあげた方がいいと思って～」
line = "「ボクが呼んでたんだ～♪　ほら、にーにーもまだ子供だから、エッチな勉強をやるなら『大人ゲージ』を貯める為に誘ってあげた方がいいと思って～」"

[[dialogue]]
speaker = "紅明"
# 「しまったぜ……そこはちゃんと、ダーリンには秘密と言っておくべきだったっしょ……」
line = "「しまったぜ……そこはちゃんと、ダーリンには秘密と言っておくべきだったっしょ……」"

[[dialogue]]
speaker = "unk"
# クーシェンに何を教える気だったんだ！？
line = "クーシェンに何を教える気だったんだ！？"

[[dialogue]]
speaker = "紅明"
# 「バレてしまったなら仕方ない。それは――」
line = "「バレてしまったなら仕方ない。それは――」"

[[dialogue]]
speaker = "unk"
# そう言って彼女は、立派な古文書のような本を取り出して見せる。
line = "そう言って彼女は、立派な古文書のような本を取り出して見せる。"

[[dialogue]]
speaker = "紅明"
# 「じゃじゃーーん☆　我が牛家に伝わる秘伝の『エロスの書』だぜ！」
line = "「じゃじゃーーん☆　我が牛家に伝わる秘伝の『エロスの書』だぜ！」"

[[dialogue]]
speaker = "unk"
# 没収っ！！！
line = "没収っ！！！"

[[dialogue]]
speaker = "紅明"
# 「速攻！？　落ち着くんだ、ダーリン！」
line = "「速攻！？　落ち着くんだ、ダーリン！」"

[[dialogue]]
speaker = "紅明"
# 「これはただのエロ本じゃない！　確かにすごくエロいことも書いてあるけど、牛家が２０００年間、正しい性知識を子孫に伝える為に受け継いできた『性書』なんだ！！」
line = "「これはただのエロ本じゃない！　確かにすごくエロいことも書いてあるけど、牛家が２０００年間、正しい性知識を子孫に伝える為に受け継いできた『性書』なんだ！！」"

[[dialogue]]
speaker = "unk"
# 怪しさしか感じないんだけど！？
line = "怪しさしか感じないんだけど！？"

[[dialogue]]
speaker = "紅明"
# 「大丈夫だって！　ダーリンも知っての通り、アタシはこう見えて、前世でママをやってたんだぜ？　任せときなって☆」
line = "「大丈夫だって！　ダーリンも知っての通り、アタシはこう見えて、前世でママをやってたんだぜ？　任せときなって☆」"

[[dialogue]]
speaker = "クーシェン"
# 「ねーねー、エッチなこと早く教えて～！　ボク、ウッキウキで待ちきれないよ～♪」
line = "「ねーねー、エッチなこと早く教えて～！　ボク、ウッキウキで待ちきれないよ～♪」"

[[dialogue]]
speaker = "unk"
# それから、授業が進み――クーシェンはショックを受けたように頭を抱えていた。
line = "それから、授業が進み――クーシェンはショックを受けたように頭を抱えていた。"

[[dialogue]]
speaker = "クーシェン"
# 「そんな……まさか――」
line = "「そんな……まさか――」"

[[dialogue]]
speaker = "クーシェン"
# 「おっぱいを触るよりもエッチなことが、この世に存在するだなんて……！」
line = "「おっぱいを触るよりもエッチなことが、この世に存在するだなんて……！」"

[[dialogue]]
speaker = "unk"
# （奇跡レベルの無知！）
line = "（奇跡レベルの無知！）"

[[dialogue]]
speaker = "クーシェン"
# 「でも……<b>ソレ</b>をすることで、『大人ゲージ』が大きく貯まるんだね！？」
line = "「でも……<b>ソレ</b>をすることで、『大人ゲージ』が大きく貯まるんだね！？」"

[[dialogue]]
speaker = "紅明"
# 「その通りっしょ！　<b>ソレ</b>は妊娠する為に必要な儀式でもある。ただ――」
line = "「その通りっしょ！　<b>ソレ</b>は妊娠する為に必要な儀式でもある。ただ――」"

[[dialogue]]
speaker = "紅明"
# 「したいからすればいいってわけじゃないんだ、クーちん。そういうのは、やっぱり心から好きになったヒトとするべきっしょ」
line = "「したいからすればいいってわけじゃないんだ、クーちん。そういうのは、やっぱり心から好きになったヒトとするべきっしょ」"

[[dialogue]]
speaker = "紅明"
# 「実を言うと、アタシも転生してから１度もしたことがないんだぞ☆」
line = "「実を言うと、アタシも転生してから１度もしたことがないんだぞ☆」"

[[dialogue]]
speaker = "クーシェン"
# 「え？　でもそれじゃあ、ねーねーはどうやって大人に……？」
line = "「え？　でもそれじゃあ、ねーねーはどうやって大人に……？」"

[[dialogue]]
speaker = "紅明"
# 「ふっ……クーちんよ。よくぞ矛盾に気づいた。今こそ、エッチの真実について語ろう――」
line = "「ふっ……クーちんよ。よくぞ矛盾に気づいた。今こそ、エッチの真実について語ろう――」"

[[dialogue]]
speaker = "クーシェン"
# 「エッチの真実……！？」
line = "「エッチの真実……！？」"

[[dialogue]]
speaker = "unk"
# （存在しないと明かす時が！！）
line = "（存在しないと明かす時が！！）"

[[dialogue]]
speaker = "unk"
# （ついに例の謎ゲージが……）
line = "（ついに例の謎ゲージが……）"

[[dialogue]]
speaker = "紅明"
# 「クーちん……この世界にはもう１つ――『おっぱいゲージ』というのが存在しているんだ！」
line = "「クーちん……この世界にはもう１つ――『おっぱいゲージ』というのが存在しているんだ！」"

[[dialogue]]
speaker = "クーシェン"
# 「おっぱいゲージ！？！？」
line = "「おっぱいゲージ！？！？」"

[[dialogue]]
speaker = "unk"
# 待て待て待てぇーいっ！！！
line = "待て待て待てぇーいっ！！！"

[[dialogue]]
speaker = "クーシェン"
# 「どういうこと！？　進化する為の『大人ゲージ』と、妊娠する為の『好きゲージ』以外に、３つ目のゲージが存在していたの！？」
line = "「どういうこと！？　進化する為の『大人ゲージ』と、妊娠する為の『好きゲージ』以外に、３つ目のゲージが存在していたの！？」"

[[dialogue]]
speaker = "紅明"
# 「今まで隠していたけど……クーちん、アタシは実はまだ大人じゃないんだ。アタシの胸が大きいのは――そのおっぱいゲージの影響なんだよ！」
line = "「今まで隠していたけど……クーちん、アタシは実はまだ大人じゃないんだ。アタシの胸が大きいのは――そのおっぱいゲージの影響なんだよ！」"

[[dialogue]]
speaker = "クーシェン"
# 「なっ……なんだってーーーっ！？」
line = "「なっ……なんだってーーーっ！？」"

[[dialogue]]
speaker = "クーシェン"
# 「つまり、おっぱいゲージが貯まると……おっぱいが大きくなる、ってコト！？」
line = "「つまり、おっぱいゲージが貯まると……おっぱいが大きくなる、ってコト！？」"

[[dialogue]]
speaker = "紅明"
# 「その通り！　そして、個人的にはまず、大人ゲージよりも先におっぱいゲージから貯めるのがオススメだ！　何故ならおっぱいは大きい方が……カッコいいっしょ？」
line = "「その通り！　そして、個人的にはまず、大人ゲージよりも先におっぱいゲージから貯めるのがオススメだ！　何故ならおっぱいは大きい方が……カッコいいっしょ？」"

[[dialogue]]
speaker = "クーシェン"
# 「た、確かに……！　大きなおっぱい、カッコいいからボクも欲しい……！」
line = "「た、確かに……！　大きなおっぱい、カッコいいからボクも欲しい……！」"

[[dialogue]]
speaker = "紅明"
# 「ならクーちん、話は早いぜ！　牛家は代々、おっぱいゲージを貯める技術を高めてきた一族だ」
line = "「ならクーちん、話は早いぜ！　牛家は代々、おっぱいゲージを貯める技術を高めてきた一族だ」"

[[dialogue]]
speaker = "紅明"
# 「だから、アタシと一緒にエッチな勉強をすれば、クーちんもおっぱいが大きくなること間違いなしだぜ！」
line = "「だから、アタシと一緒にエッチな勉強をすれば、クーちんもおっぱいが大きくなること間違いなしだぜ！」"

[[dialogue]]
speaker = "クーシェン"
# 「うんっ、わかった！　ボク、まずはおっぱいゲージから貯めることにするよ！　だからもっと色々と教えて、ねーねー！」
line = "「うんっ、わかった！　ボク、まずはおっぱいゲージから貯めることにするよ！　だからもっと色々と教えて、ねーねー！」"

[[dialogue]]
speaker = "unk"
# そこでふと、紅明が俺にウインクをする。
line = "そこでふと、紅明が俺にウインクをする。"

[[dialogue]]
speaker = "unk"
# それで彼女がクーシェンの勘違いをすぐ全否定するのではなく、徐々に正しい知識を教えて行くことにしたのだと、俺はなんとなく察した。
line = "それで彼女がクーシェンの勘違いをすぐ全否定するのではなく、徐々に正しい知識を教えて行くことにしたのだと、俺はなんとなく察した。"

[[dialogue]]
speaker = "unk"
# さすがは人生２周目といったところか――と感心していると、クーシェンが口を開く。
line = "さすがは人生２周目といったところか――と感心していると、クーシェンが口を開く。"

[[dialogue]]
speaker = "クーシェン"
# 「あれ……？　でも思ったんだけど、３本目のゲージがあるってことは……それって男のヒトの場合だと、どうなるんだろう？」
line = "「あれ……？　でも思ったんだけど、３本目のゲージがあるってことは……それって男のヒトの場合だと、どうなるんだろう？」"

[[dialogue]]
speaker = "クーシェン"
# 「はっ！？　もしかして――」
line = "「はっ！？　もしかして――」"

[[dialogue]]
speaker = "クーシェン"
# 「『■■■■■ゲージ』！？　■■■■■ゲージってコト！？」
line = "「『■■■■■ゲージ』！？　■■■■■ゲージってコト！？」"

[[dialogue]]
speaker = "unk"
# ちょっ！？　ストップストォーップ！！！
line = "ちょっ！？　ストップストォーップ！！！"

[[dialogue]]
speaker = "クーシェン"
# 「？　にーにー、なに慌ててるの？　――はしたないから、■■■■■連呼はダメ？」
line = "「？　にーにー、なに慌ててるの？　――はしたないから、■■■■■連呼はダメ？」"

[[dialogue]]
speaker = "クーシェン"
# 「あっ！　さてはにーにー、■■■■■の話題が恥ずかしいんだ～？」
line = "「あっ！　さてはにーにー、■■■■■の話題が恥ずかしいんだ～？」"

[[dialogue]]
speaker = "クーシェン"
# 「もう、にーにーってば、■■■■■くらいで慌てちゃって～！　ほんと、エッチな話題では雑魚ザコなんだから～♪　ウキキ♪」
line = "「もう、にーにーってば、■■■■■くらいで慌てちゃって～！　ほんと、エッチな話題では雑魚ザコなんだから～♪　ウキキ♪」"

[[dialogue]]
speaker = "クーシェン"
# 「仕方ないから、■■■■■ゲージを貯める時はボクが協力してあげるね♪」
line = "「仕方ないから、■■■■■ゲージを貯める時はボクが協力してあげるね♪」"

[[dialogue]]
speaker = "紅明"
# 「ぷっ、ふふっ……ふふふっ！　あはははははっ！！　お、■■■■■ゲージ……あはははははははっ！！！」
line = "「ぷっ、ふふっ……ふふふっ！　あはははははっ！！　お、■■■■■ゲージ……あはははははははっ！！！」"

[[dialogue]]
speaker = "unk"
# 無邪気に連呼するクーシェンの横で、もう堪えきれないとばかりに腹を抱えて爆笑する紅明なのであった――
line = "無邪気に連呼するクーシェンの横で、もう堪えきれないとばかりに腹を抱えて爆笑する紅明なのであった――"
