[[dialogue]]
speaker = "unk"
# 第４話,追加要求いたします,P
line = "第４話,追加要求いたします,P"

[[dialogue]]
speaker = "unk"
# 元の世界に帰れる目処もようやく立ち、残り僅かな時を過ごしている。
line = "元の世界に帰れる目処もようやく立ち、残り僅かな時を過ごしている。"

[[dialogue]]
speaker = "unk"
# この日はナナカに招待されて、流星学園の食堂に来ていた。
line = "この日はナナカに招待されて、流星学園の食堂に来ていた。"

[[dialogue]]
speaker = "ナナカ"
# 「へいお待ち！　ナナカちゃん特製手打ちソバでいっ！」
line = "「へいお待ち！　ナナカちゃん特製手打ちソバでいっ！」"

[[dialogue]]
speaker = "ナナカ"
# 「おお～、いい食べっぷりだね！　どうよ、お味の方は？」
line = "「おお～、いい食べっぷりだね！　どうよ、お味の方は？」"

[[dialogue]]
speaker = "ナナカ"
# 「あーっ、皆まで言わなくていいって。夢中で食べてくれてるってのが、一番の褒め言葉だからね！」
line = "「あーっ、皆まで言わなくていいって。夢中で食べてくれてるってのが、一番の褒め言葉だからね！」"

[[dialogue]]
speaker = "ナナカ"
# 「とはいえ、ちょっと作りすぎちゃったかな。アタシも食べるにしても、まだまだおかわりできそうだし……」
line = "「とはいえ、ちょっと作りすぎちゃったかな。アタシも食べるにしても、まだまだおかわりできそうだし……」"

[[dialogue]]
speaker = "ナナカ"
# 「っと、いいところにロロちゃん発見！」
line = "「っと、いいところにロロちゃん発見！」"

[[dialogue]]
speaker = "ロロット"
# 「きゅぴーん……！」
line = "「きゅぴーん……！」"

[[dialogue]]
speaker = "ロロット"
# 「ああ～……食べなくてもサクサクの食感が伝わる、キュートなエビフライ！」
line = "「ああ～……食べなくてもサクサクの食感が伝わる、キュートなエビフライ！」"

[[dialogue]]
speaker = "ロロット"
# 「ちょこんとデミをまとったミニハンバーグ！」
line = "「ちょこんとデミをまとったミニハンバーグ！」"

[[dialogue]]
speaker = "ロロット"
# 「カリカリに揚がったポテトに、うさぎさんりんご！　その上、プチゼリーまで……」
line = "「カリカリに揚がったポテトに、うさぎさんりんご！　その上、プチゼリーまで……」"

[[dialogue]]
speaker = "ロロット"
# 「そしてメインは、ケチャップで花丸を描いたオムライス……！」
line = "「そしてメインは、ケチャップで花丸を描いたオムライス……！」"

[[dialogue]]
speaker = "ロロット"
# 「パーフェクト……なんて完璧なんでしょう……これぞ宇宙の黄金律！」
line = "「パーフェクト……なんて完璧なんでしょう……これぞ宇宙の黄金律！」"

[[dialogue]]
speaker = "ロロット"
# 「さあ、いざ実食なのです！」
line = "「さあ、いざ実食なのです！」"

[[dialogue]]
speaker = "ナナカ"
# 「おーい、ロロちゃん」
line = "「おーい、ロロちゃん」"

[[dialogue]]
speaker = "ロロット"
# 「ななっ！？　なんですかっ、人の幸せな食事の時間を邪魔しないで下さい～っ」
line = "「ななっ！？　なんですかっ、人の幸せな食事の時間を邪魔しないで下さい～っ」"

[[dialogue]]
speaker = "ナナカ"
# 「あ、ごめん、邪魔するつもりはなかったんだけどさ」
line = "「あ、ごめん、邪魔するつもりはなかったんだけどさ」"

[[dialogue]]
speaker = "ロロット"
# 「会計さんにはあげませんよっ」
line = "「会計さんにはあげませんよっ」"

[[dialogue]]
speaker = "ナナカ"
# 「違う違う。張り切りすぎて、ソバを多めに茹でちゃったもんでさ、よかったら食べるの手伝って欲しいな～って」
line = "「違う違う。張り切りすぎて、ソバを多めに茹でちゃったもんでさ、よかったら食べるの手伝って欲しいな～って」"

[[dialogue]]
speaker = "ロロット"
# 「ギロリ！」
line = "「ギロリ！」"

[[dialogue]]
speaker = "ナナカ"
# 「ひぃ！」
line = "「ひぃ！」"

[[dialogue]]
speaker = "unk"
# ギロリって言う人はじめて見た
line = "ギロリって言う人はじめて見た"

[[dialogue]]
speaker = "ナナカ"
# 「メチャクチャ塩対応なんだけど、ロロちゃん……」
line = "「メチャクチャ塩対応なんだけど、ロロちゃん……」"

[[dialogue]]
speaker = "ロロット"
# 「いいですか？　わたしは今、特製お子様ランチと真摯に向き合うという、とっても大切な儀式の真っ最中なのです」
line = "「いいですか？　わたしは今、特製お子様ランチと真摯に向き合うという、とっても大切な儀式の真っ最中なのです」"

[[dialogue]]
speaker = "ロロット"
# 「ということで、申し訳ありませんが、会計さんのお相手はできかねますのであしからず」
line = "「ということで、申し訳ありませんが、会計さんのお相手はできかねますのであしからず」"

[[dialogue]]
speaker = "unk"
# そのお子様ランチ、凄くおいしそう
line = "そのお子様ランチ、凄くおいしそう"

[[dialogue]]
speaker = "ロロット"
# 「おお、お目が高いのです！　見た目は勿論のこと、味も最高なんですよ～」
line = "「おお、お目が高いのです！　見た目は勿論のこと、味も最高なんですよ～」"

[[dialogue]]
speaker = "ナナカ"
# 「アタシのソバよりも？」
line = "「アタシのソバよりも？」"

[[dialogue]]
speaker = "ロロット"
# 「会計さんのおソバはもう食べ飽きてしまったので、残念ながら、新鮮味に欠けてしまいますね」
line = "「会計さんのおソバはもう食べ飽きてしまったので、残念ながら、新鮮味に欠けてしまいますね」"

[[dialogue]]
speaker = "ナナカ"
# 「い、言ったなー、よし勝負だ！」
line = "「い、言ったなー、よし勝負だ！」"

[[dialogue]]
speaker = "ロロット"
# 「ご自由にどうぞ」
line = "「ご自由にどうぞ」"

[[dialogue]]
speaker = "ナナカ"
# 「うう、ロロちゃんが全然相手にしてくれない……」
line = "「うう、ロロちゃんが全然相手にしてくれない……」"

[[dialogue]]
speaker = "unk"
# それだけおいしいんだよ
line = "それだけおいしいんだよ"

[[dialogue]]
speaker = "ロロット"
# 「……あ、あなたにも、あげませんからねっ？」
line = "「……あ、あなたにも、あげませんからねっ？」"

[[dialogue]]
speaker = "ロロット"
# 「どうしても食べたいというのでしたら、ご自分で注文されてはどうでしょう」
line = "「どうしても食べたいというのでしたら、ご自分で注文されてはどうでしょう」"

[[dialogue]]
speaker = "ナナカ"
# 「待った待った、そうはいかないよっ。新星の会長さんは、もうあたしのソバをがっつり食べちゃってるんだから」
line = "「待った待った、そうはいかないよっ。新星の会長さんは、もうあたしのソバをがっつり食べちゃってるんだから」"

[[dialogue]]
speaker = "unk"
# 全部は無理だから味見させて
line = "全部は無理だから味見させて"

[[dialogue]]
speaker = "ロロット"
# 「それでしたら、日を改めれば……と、いう訳には、いかないんでしたっけ」
line = "「それでしたら、日を改めれば……と、いう訳には、いかないんでしたっけ」"

[[dialogue]]
speaker = "ナナカ"
# 「そうだよ、明日急に帰っちゃうかもしれないんだから。これを味わっとくには、今しかチャンスがないかもよ？」
line = "「そうだよ、明日急に帰っちゃうかもしれないんだから。これを味わっとくには、今しかチャンスがないかもよ？」"

[[dialogue]]
speaker = "ロロット"
# 「やれやれ、仕方がありませんねぇ。幸せのお裾分けも吝かではありませんし、トレードなら応じることができますよ。なにせ、わたしはとっても心が広いのですから！」
line = "「やれやれ、仕方がありませんねぇ。幸せのお裾分けも吝かではありませんし、トレードなら応じることができますよ。なにせ、わたしはとっても心が広いのですから！」"

[[dialogue]]
speaker = "ロロット"
# 「ちなみに、ハンバーグは選択禁止です。断固拒否です。これは一番のお楽しみなのですから」
line = "「ちなみに、ハンバーグは選択禁止です。断固拒否です。これは一番のお楽しみなのですから」"

[[dialogue]]
speaker = "ナナカ"
# 「アタシのソバなら３口あげるよ～」
line = "「アタシのソバなら３口あげるよ～」"

[[dialogue]]
speaker = "ロロット"
# 「そんなに食べられません」
line = "「そんなに食べられません」"

[[dialogue]]
speaker = "unk"
# ならオムライスを１口！
line = "ならオムライスを１口！"

[[dialogue]]
speaker = "ナナカ"
# 「こっちはなんと！　ソバを１枚提供しちゃうよ！」
line = "「こっちはなんと！　ソバを１枚提供しちゃうよ！」"

[[dialogue]]
speaker = "ロロット"
# 「増やさないで下さ～い！」
line = "「増やさないで下さ～い！」"

[[dialogue]]
speaker = "ナナカ"
# 「だってだって、ロロちゃんも、アタシのソバはおいしいって言ってくれてたじゃん！」
line = "「だってだって、ロロちゃんも、アタシのソバはおいしいって言ってくれてたじゃん！」"

[[dialogue]]
speaker = "ロロット"
# 「非常に残念ですが、この目の前に広がるテーマパークのような、お子様ランチの魅力には抗えません」
line = "「非常に残念ですが、この目の前に広がるテーマパークのような、お子様ランチの魅力には抗えません」"

[[dialogue]]
speaker = "ナナカ"
# 「そんなにおいしいわけ？　アタシもちょっと気になって来たかも……」
line = "「そんなにおいしいわけ？　アタシもちょっと気になって来たかも……」"

[[dialogue]]
speaker = "ロロット"
# 「だから、あげませんってば～！　いくらおソバを積み上げられたって、応じませんからね！」
line = "「だから、あげませんってば～！　いくらおソバを積み上げられたって、応じませんからね！」"

[[dialogue]]
speaker = "ナナカ"
# 「ロロちゃんのけちー。せめてさ、ちょっとだけでも味見させたげてよ」
line = "「ロロちゃんのけちー。せめてさ、ちょっとだけでも味見させたげてよ」"

[[dialogue]]
speaker = "ロロット"
# 「うう～……それもそうですね。では、ほんのちょこっとだけ……」
line = "「うう～……それもそうですね。では、ほんのちょこっとだけ……」"

[[dialogue]]
speaker = "ロロット"
# 「……あーん、です」
line = "「……あーん、です」"

[[dialogue]]
speaker = "ロロット"
# 「さあ、お早くどうぞ。食べてくれないと、落っこちちゃいます」
line = "「さあ、お早くどうぞ。食べてくれないと、落っこちちゃいます」"

[[dialogue]]
speaker = "ロロット"
# 「そうですそうです、お味はどうですか？　おいしいですか？　おいしいに決まってますよね♪」
line = "「そうですそうです、お味はどうですか？　おいしいですか？　おいしいに決まってますよね♪」"

[[dialogue]]
speaker = "ナナカ"
# 「ロロちゃん、それはちょっと……」
line = "「ロロちゃん、それはちょっと……」"

[[dialogue]]
speaker = "ロロット"
# 「ほえ？　お口がいっぱいで、感想どころではありませんでした？」
line = "「ほえ？　お口がいっぱいで、感想どころではありませんでした？」"

[[dialogue]]
speaker = "ナナカ"
# 「いや、そういうことじゃなくてさぁ……」
line = "「いや、そういうことじゃなくてさぁ……」"

[[dialogue]]
speaker = "unk"
# あーんって、ちょっと恥ずかしいかも
line = "あーんって、ちょっと恥ずかしいかも"

[[dialogue]]
speaker = "ロロット"
# 「はっ！　そそ、それはっ！　不可抗力です！　別にそういうつもりじゃありませ～ん！」
line = "「はっ！　そそ、それはっ！　不可抗力です！　別にそういうつもりじゃありませ～ん！」"

[[dialogue]]
speaker = "ナナカ"
# 「たはは、ロロちゃん、照れちゃってんじゃん」
line = "「たはは、ロロちゃん、照れちゃってんじゃん」"

[[dialogue]]
speaker = "ロロット"
# 「どうやら、わたしの深い包容力が、垣間見えてしまったようですね」
line = "「どうやら、わたしの深い包容力が、垣間見えてしまったようですね」"

[[dialogue]]
speaker = "unk"
# あーん♪
line = "あーん♪"

[[dialogue]]
speaker = "ロロット"
# 「むむっ、追加要求ですか！？　なんと強欲な……」
line = "「むむっ、追加要求ですか！？　なんと強欲な……」"

[[dialogue]]
speaker = "ナナカ"
# 「どうするの？」
line = "「どうするの？」"

[[dialogue]]
speaker = "ロロット"
# 「ううう～……自分で食べて下さい、と言いたいところですが……」
line = "「ううう～……自分で食べて下さい、と言いたいところですが……」"

[[dialogue]]
speaker = "unk"
# あーん♪
line = "あーん♪"

[[dialogue]]
speaker = "ロロット"
# 「まったく……思っていた以上に、甘えんぼさんな方だったようですね。心優しいわたしが突き動かされてしまうのも、仕方のないことだと思います」
line = "「まったく……思っていた以上に、甘えんぼさんな方だったようですね。心優しいわたしが突き動かされてしまうのも、仕方のないことだと思います」"

[[dialogue]]
speaker = "ロロット"
# 「ただし、あーんって食べさせてあげるのは、これで最後ですからね。これ以上は、もうあげませんから！」
line = "「ただし、あーんって食べさせてあげるのは、これで最後ですからね。これ以上は、もうあげませんから！」"

[[dialogue]]
speaker = "unk"
# こうして俺はロロットのお子様ランチを食べさせてもらった。
line = "こうして俺はロロットのお子様ランチを食べさせてもらった。"

[[dialogue]]
speaker = "unk"
# これで最後と言ってたけど、そんなことはなく、もう少しサービスしてくれるロロットだった。
line = "これで最後と言ってたけど、そんなことはなく、もう少しサービスしてくれるロロットだった。"
