[[dialogue]]
speaker = "unk"
# 第２話,レイル鑑賞会,P
line = "第２話,レイル鑑賞会,P"

[[dialogue]]
speaker = "アポロ"
# 「よーし、これで全員集まったな！」
line = "「よーし、これで全員集まったな！」"

[[dialogue]]
speaker = "プトラ"
# 「はーい！」
line = "「はーい！」"

[[dialogue]]
speaker = "unk"
# とある休日のこと、アポロに呼び出されて星見家のお屋敷にやってきた。
line = "とある休日のこと、アポロに呼び出されて星見家のお屋敷にやってきた。"

[[dialogue]]
speaker = "unk"
# 仁王立ちするアポロの前には、プトラとフィオナが居住まいを正している。
line = "仁王立ちするアポロの前には、プトラとフィオナが居住まいを正している。"

[[dialogue]]
speaker = "unk"
# この展開はまさか……
line = "この展開はまさか……"

[[dialogue]]
speaker = "アポロ"
# 「これより流星ライダーの鑑賞会を始めるぞ！」
line = "「これより流星ライダーの鑑賞会を始めるぞ！」"

[[dialogue]]
speaker = "プトラ"
# 「わー、パチパチ！」
line = "「わー、パチパチ！」"

[[dialogue]]
speaker = "フィオナ"
# 「わー、パチパチ……ほら、会長も」
line = "「わー、パチパチ……ほら、会長も」"

[[dialogue]]
speaker = "unk"
# つい最近、全シリーズ一気見したような……
line = "つい最近、全シリーズ一気見したような……"

[[dialogue]]
speaker = "アポロ"
# 「いいだろ、何度見たって！　流星ライダーは周回上等だぜ！」
line = "「いいだろ、何度見たって！　流星ライダーは周回上等だぜ！」"

[[dialogue]]
speaker = "アポロ"
# 「ホントはシリーズの最初からと言いたいところなんだけど、プトラが興味津々な『流星ライダーレイル』から見ていくぞ」
line = "「ホントはシリーズの最初からと言いたいところなんだけど、プトラが興味津々な『流星ライダーレイル』から見ていくぞ」"

[[dialogue]]
speaker = "フィオナ"
# 「レイルも名作ですからね～、きっとプトラさんも楽しめると思います」
line = "「レイルも名作ですからね～、きっとプトラさんも楽しめると思います」"

[[dialogue]]
speaker = "プトラ"
# 「鉄道が出てくるんでしょ？　楽しみだよ～♪」
line = "「鉄道が出てくるんでしょ？　楽しみだよ～♪」"

[[dialogue]]
speaker = "アポロ"
# 「流星ライナーな。時間も空間も飛び越えてキミの元へ駆けつけるんだぜ！」
line = "「流星ライナーな。時間も空間も飛び越えてキミの元へ駆けつけるんだぜ！」"

[[dialogue]]
speaker = "プトラ"
# 「か、カッコイイ！」
line = "「か、カッコイイ！」"

[[dialogue]]
speaker = "アポロ"
# 「よーし、それじゃ視聴開始だ！」
line = "「よーし、それじゃ視聴開始だ！」"

[[dialogue]]
speaker = "プトラ"
# 「おー、始まった！」
line = "「おー、始まった！」"

[[dialogue]]
speaker = "プトラ"
# 「わわっ、すごいスピードで走ってる！　いきなり出てきたけど、これが流星ライナーだよね？　だよね？」
line = "「わわっ、すごいスピードで走ってる！　いきなり出てきたけど、これが流星ライナーだよね？　だよね？」"

[[dialogue]]
speaker = "プトラ"
# 「すごいすごい、何もないところに線路が現れてその上を走ってるー！」
line = "「すごいすごい、何もないところに線路が現れてその上を走ってるー！」"

[[dialogue]]
speaker = "フィオナ"
# 「そこはファンタジーですから。プトラさんの世界の線路も、普通に地面に敷かれているんですよね？」
line = "「そこはファンタジーですから。プトラさんの世界の線路も、普通に地面に敷かれているんですよね？」"

[[dialogue]]
speaker = "プトラ"
# 「うん、でもその線路はどこの誰が敷いたものなのか分かってないんだ」
line = "「うん、でもその線路はどこの誰が敷いたものなのか分かってないんだ」"

[[dialogue]]
speaker = "プトラ"
# 「ずっと昔に敷かれた線路が大陸じゅうに走ってるの。『ミストトレイン』はその上を走るんだよ」
line = "「ずっと昔に敷かれた線路が大陸じゅうに走ってるの。『ミストトレイン』はその上を走るんだよ」"

[[dialogue]]
speaker = "プトラ"
# 「あ、なんか変なのが出てきたよ！　こいつらが敵なのかな？」
line = "「あ、なんか変なのが出てきたよ！　こいつらが敵なのかな？」"

[[dialogue]]
speaker = "プトラ"
# 「人の心に忍び込んで、怪物にしちゃうなんて……まるで霧みたい……」
line = "「人の心に忍び込んで、怪物にしちゃうなんて……まるで霧みたい……」"

[[dialogue]]
speaker = "アポロ"
# 「プトラの世界の霧ってそんなに危ないのか？」
line = "「プトラの世界の霧ってそんなに危ないのか？」"

[[dialogue]]
speaker = "プトラ"
# 「そうだよ。霧に蝕まれちゃうとミストモンスターになっちゃうんだ」
line = "「そうだよ。霧に蝕まれちゃうとミストモンスターになっちゃうんだ」"

[[dialogue]]
speaker = "プトラ"
# 「今度のはすごく強そうな敵だよ！　大丈夫かな？　本当に勝てるのかな？」
line = "「今度のはすごく強そうな敵だよ！　大丈夫かな？　本当に勝てるのかな？」"

[[dialogue]]
speaker = "アポロ"
# 「大丈夫！　正義を信じる心が、流星ライダーを強くするんだ！」
line = "「大丈夫！　正義を信じる心が、流星ライダーを強くするんだ！」"

[[dialogue]]
speaker = "プトラ"
# 「がんばれっ！　負けるな流星ライダー！」
line = "「がんばれっ！　負けるな流星ライダー！」"

[[dialogue]]
speaker = "プトラ"
# 「あうぅぅ、こんなラストシーン泣いちゃうよ～！　みんなちゃんと消えずにいてくれてよかった～！」
line = "「あうぅぅ、こんなラストシーン泣いちゃうよ～！　みんなちゃんと消えずにいてくれてよかった～！」"

[[dialogue]]
speaker = "フィオナ"
# 「はい、ティッシュです」
line = "「はい、ティッシュです」"

[[dialogue]]
speaker = "プトラ"
# 「ぐしゅん、ありがとう……」
line = "「ぐしゅん、ありがとう……」"

[[dialogue]]
speaker = "フィオナ"
# 「プトラさんにも流星ライダーの魅力が分かってもらえたみたいですね」
line = "「プトラさんにも流星ライダーの魅力が分かってもらえたみたいですね」"

[[dialogue]]
speaker = "プトラ"
# 「うん、すっごく面白かったよ」
line = "「うん、すっごく面白かったよ」"

[[dialogue]]
speaker = "unk"
# プトラ的にはどのシーンがお気に入り？
line = "プトラ的にはどのシーンがお気に入り？"

[[dialogue]]
speaker = "プトラ"
# 「うーん、いっぱいあって悩んじゃうけど……やっぱりあそこかな」
line = "「うーん、いっぱいあって悩んじゃうけど……やっぱりあそこかな」"

[[dialogue]]
speaker = "プトラ"
# 「レイルがみんなに向かって『誰だっていつか、悲しみを乗り越えて笑顔になれる！』って叫ぶところ」
line = "「レイルがみんなに向かって『誰だっていつか、悲しみを乗り越えて笑顔になれる！』って叫ぶところ」"

[[dialogue]]
speaker = "アポロ"
# 「うんうん、『笑顔の大切さ』はレイルのテーマだからな！」
line = "「うんうん、『笑顔の大切さ』はレイルのテーマだからな！」"

[[dialogue]]
speaker = "フィオナ"
# 「あそこは屈指の名シーンですね♪」
line = "「あそこは屈指の名シーンですね♪」"

[[dialogue]]
speaker = "プトラ"
# 「あたしもおばあちゃんから言われてるんだ～」
line = "「あたしもおばあちゃんから言われてるんだ～」"

[[dialogue]]
speaker = "プトラ"
# 「『大切な涙なら流してもいい。でも、笑顔は絶対に忘れちゃいけない』って」
line = "「『大切な涙なら流してもいい。でも、笑顔は絶対に忘れちゃいけない』って」"

[[dialogue]]
speaker = "プトラ"
# 「その言葉にずっと支えられてきたところあるから、あのシーンはホントに響いたよ～」
line = "「その言葉にずっと支えられてきたところあるから、あのシーンはホントに響いたよ～」"

[[dialogue]]
speaker = "アポロ"
# 「なんだよ……プトラのおばあちゃん、すっごくいい事言うじゃないか」
line = "「なんだよ……プトラのおばあちゃん、すっごくいい事言うじゃないか」"

[[dialogue]]
speaker = "フィオナ"
# 「プトラさんがいつも元気に笑顔でいるのは、そういう理由もあったんですね」
line = "「プトラさんがいつも元気に笑顔でいるのは、そういう理由もあったんですね」"

[[dialogue]]
speaker = "プトラ"
# 「えへへ、そうなんだ～」
line = "「えへへ、そうなんだ～」"

[[dialogue]]
speaker = "プトラ"
# 「あ、あとビックリしたのが、途中で出てきた列車だよ！」
line = "「あ、あとビックリしたのが、途中で出てきた列車だよ！」"

[[dialogue]]
speaker = "プトラ"
# 「蒸気機関車、っていうの？　あれがあたしの乗ってる『ミストトレイン』にそっくりだった！」
line = "「蒸気機関車、っていうの？　あれがあたしの乗ってる『ミストトレイン』にそっくりだった！」"

[[dialogue]]
speaker = "アポロ"
# 「ミストトレインってあんな感じなのか！？　すごいな！　くぅぅ……乗ってみたいっ！！」
line = "「ミストトレインってあんな感じなのか！？　すごいな！　くぅぅ……乗ってみたいっ！！」"

[[dialogue]]
speaker = "プトラ"
# 「あたしも元の世界に戻って乗った時、思い出して泣いちゃうかもね～、あはは♪」
line = "「あたしも元の世界に戻って乗った時、思い出して泣いちゃうかもね～、あはは♪」"

[[dialogue]]
speaker = "unk"
# こうして丸１日がかりの流星ライダーレイルの鑑賞会は幕を閉じたが、この次は『流星ライダーアポロ』の鑑賞会をするらしい。
line = "こうして丸１日がかりの流星ライダーレイルの鑑賞会は幕を閉じたが、この次は『流星ライダーアポロ』の鑑賞会をするらしい。"

[[dialogue]]
speaker = "unk"
# プトラも流星ライダーシリーズを気に入ってくれて、俺も嬉しく思うのだった。
line = "プトラも流星ライダーシリーズを気に入ってくれて、俺も嬉しく思うのだった。"
