[[dialogue]]
speaker = "unk"
# 第１話,チキンが結ぶ縁,P
line = "第１話,チキンが結ぶ縁,P"

[[dialogue]]
speaker = "unk"
# 放課後。星徒会室。
line = "放課後。星徒会室。"

[[dialogue]]
speaker = "unk"
# 書類仕事が立て込んでいたところ、突然ドアが開いた。
line = "書類仕事が立て込んでいたところ、突然ドアが開いた。"

[[dialogue]]
speaker = "シルヴィ"
# 「やっほー！　遊びに来たよ！」
line = "「やっほー！　遊びに来たよ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「いらっしゃーい！　ようこそ、シルヴィさん！」
line = "「いらっしゃーい！　ようこそ、シルヴィさん！」"

[[dialogue]]
speaker = "シルヴィ"
# 「今日は星徒会長くん、ちゃんといる！　よかった！」
line = "「今日は星徒会長くん、ちゃんといる！　よかった！」"

[[dialogue]]
speaker = "シルヴィ"
# 「あたし、シルヴィ・グリムランド！　３年生！　よろしくね！」
line = "「あたし、シルヴィ・グリムランド！　３年生！　よろしくね！」"

[[dialogue]]
speaker = "unk"
# 初めまして、緋宮クロトです
line = "初めまして、緋宮クロトです"

[[dialogue]]
speaker = "シルヴィ"
# 「おお、礼儀正しい！　さすが現星徒会長！」
line = "「おお、礼儀正しい！　さすが現星徒会長！」"

[[dialogue]]
speaker = "サーシャ"
# 「シルヴィは私が星徒会長だったときに副会長だったの～。故郷を守るために一時期、学園を離れていたけど最近、戻ってきたのよ～」
line = "「シルヴィは私が星徒会長だったときに副会長だったの～。故郷を守るために一時期、学園を離れていたけど最近、戻ってきたのよ～」"

[[dialogue]]
speaker = "アナ"
# 「実は以前も星徒会室にいらっしゃったんですが、運悪く会長はお留守でした」
line = "「実は以前も星徒会室にいらっしゃったんですが、運悪く会長はお留守でした」"

[[dialogue]]
speaker = "マトイ"
# 「確か、その時は購買部に行って帰ってこなかったんだよね……」
line = "「確か、その時は購買部に行って帰ってこなかったんだよね……」"

[[dialogue]]
speaker = "unk"
# ……あの時のことは忘れよう
line = "……あの時のことは忘れよう"

[[dialogue]]
speaker = "アナ"
# 「会長の目から光が失われています。かわいそうに。よしよし」
line = "「会長の目から光が失われています。かわいそうに。よしよし」"

[[dialogue]]
speaker = "サーシャ"
# 「で、今日は何か用かしら？　特に約束とかはなかったわよね？」
line = "「で、今日は何か用かしら？　特に約束とかはなかったわよね？」"

[[dialogue]]
speaker = "シルヴィ"
# 「うん、ヒマだったから遊びに来た！」
line = "「うん、ヒマだったから遊びに来た！」"

[[dialogue]]
speaker = "シルヴィ"
# 「あだだだだっ！」
line = "「あだだだだっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「すごいわ！　あのサーシャさんがシルヴィさんにアームロックしてるわ！」
line = "「すごいわ！　あのサーシャさんがシルヴィさんにアームロックしてるわ！」"

[[dialogue]]
speaker = "マトイ"
# 「確かにすごい状況だけど、なんで！？　理解が追い付かないよー！」
line = "「確かにすごい状況だけど、なんで！？　理解が追い付かないよー！」"

[[dialogue]]
speaker = "サーシャ"
# 「シ～ル～ヴィ～。この机に積んである書類を見て、なんとも思わないの？　明らかにヒマだからで来ていいタイミングじゃないでしょう？」
line = "「シ～ル～ヴィ～。この机に積んである書類を見て、なんとも思わないの？　明らかにヒマだからで来ていいタイミングじゃないでしょう？」"

[[dialogue]]
speaker = "サーシャ"
# 「そもそもあなた、自分から星徒会に入ったくせに、ぜんぜん書類仕事やらなかったじゃない」
line = "「そもそもあなた、自分から星徒会に入ったくせに、ぜんぜん書類仕事やらなかったじゃない」"

[[dialogue]]
speaker = "マトイ"
# 「思い出し怒り！？　サーシャさんでもそんなことあるんだ！？」
line = "「思い出し怒り！？　サーシャさんでもそんなことあるんだ！？」"

[[dialogue]]
speaker = "シルヴィ"
# 「いだだだだだ！　ごめん、ごめんてば！」
line = "「いだだだだだ！　ごめん、ごめんてば！」"

[[dialogue]]
speaker = "アナ"
# 「サーシャ先輩、それ以上いけない。シルヴィ先輩も反省しています。多分おそらくメイビー」
line = "「サーシャ先輩、それ以上いけない。シルヴィ先輩も反省しています。多分おそらくメイビー」"

[[dialogue]]
speaker = "サーシャ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "サーシャ"
# 「えい♪」
line = "「えい♪」"

[[dialogue]]
speaker = "シルヴィ"
# 「ぎゃあああああああああああっ！」
line = "「ぎゃあああああああああああっ！」"

[[dialogue]]
speaker = "シルヴィ"
# 「ガクリ」
line = "「ガクリ」"

[[dialogue]]
speaker = "unk"
# なんで今トドメ差したんですか！？
line = "なんで今トドメ差したんですか！？"

[[dialogue]]
speaker = "サーシャ"
# 「だって、つい……魔が差して？」
line = "「だって、つい……魔が差して？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だってじゃないわよ！　今ドン引きしてるわよ私も！」
line = "「だってじゃないわよ！　今ドン引きしてるわよ私も！」"

[[dialogue]]
speaker = "サーシャ"
# 「えぇ～。大丈夫よ、この子頑丈だから……３、２、１──」
line = "「えぇ～。大丈夫よ、この子頑丈だから……３、２、１──」"

[[dialogue]]
speaker = "シルヴィ"
# 「ふっか～つ！」
line = "「ふっか～つ！」"

[[dialogue]]
speaker = "unk"
# 本当に立ち上がった！
line = "本当に立ち上がった！"

[[dialogue]]
speaker = "サーシャ"
# 「昔からタフだったのよ～。入学したばかりの頃からマムの鉄球を受けてもピンピンしてたわ～」
line = "「昔からタフだったのよ～。入学したばかりの頃からマムの鉄球を受けてもピンピンしてたわ～」"

[[dialogue]]
speaker = "シルヴィ"
# 「イエ～イ！！」
line = "「イエ～イ！！」"

[[dialogue]]
speaker = "シルヴィ"
# 「あれ？　君、なんだか見覚えが……じー……」
line = "「あれ？　君、なんだか見覚えが……じー……」"

[[dialogue]]
speaker = "シルヴィ"
# 「会長くん、もしかして、<ruby=ジーエフシー>ＧＦＣ</ruby>で働いてたことある？」
line = "「会長くん、もしかして、<ruby>ＧＦＣ<rt>ジーエフシー</rt></ruby>で働いてたことある？」"

[[dialogue]]
speaker = "unk"
# はい、新星に転入する前に
line = "はい、新星に転入する前に"

[[dialogue]]
speaker = "シルヴィ"
# 「だよねー！　君の顔見たことあるもん！」
line = "「だよねー！　君の顔見たことあるもん！」"

[[dialogue]]
speaker = "シルヴィ"
# 「確か環ちゃんと一緒のお店だったよね？　環ちゃん、ＧＦＣの制服似合ってたな～」
line = "「確か環ちゃんと一緒のお店だったよね？　環ちゃん、ＧＦＣの制服似合ってたな～」"

[[dialogue]]
speaker = "unk"
# ＧＦＣとは、<ruby=ガルス>ＧＡＬＬＵＳ</ruby>・<ruby=フライド>ＦＲＩＥＤ</ruby>・<ruby=チキン>ＣＨＩＣＫＥＮ</ruby>の略であり、世界的に有名なフライドチキンのチェーン店だ。
line = "ＧＦＣとは、<ruby>ＧＡＬＬＵＳ<rt>ガルス</rt></ruby>・<ruby>ＦＲＩＥＤ<rt>フライド</rt></ruby>・<ruby>ＣＨＩＣＫＥＮ<rt>チキン</rt></ruby>の略であり、世界的に有名なフライドチキンのチェーン店だ。"

[[dialogue]]
speaker = "unk"
# 当然、俺も働いたことがある。学生のアルバイト先としては、最も身近な選択肢のひとつだろう。
line = "当然、俺も働いたことがある。学生のアルバイト先としては、最も身近な選択肢のひとつだろう。"

[[dialogue]]
speaker = "シルヴィ"
# 「そうなんだ、やっぱり！　どーりで見たことあると思った！」
line = "「そうなんだ、やっぱり！　どーりで見たことあると思った！」"

[[dialogue]]
speaker = "unk"
# 実はチキンを揚げる社内資格も持ってました
line = "実はチキンを揚げる社内資格も持ってました"

[[dialogue]]
speaker = "シルヴィ"
# 「すっご！　あたし、感動してきた！！」
line = "「すっご！　あたし、感動してきた！！」"

[[dialogue]]
speaker = "マトイ"
# 「そんなにすごいのかな？」
line = "「そんなにすごいのかな？」"

[[dialogue]]
speaker = "アナ"
# 「さぁ……和菓子職人の凄さは分かるのですが」
line = "「さぁ……和菓子職人の凄さは分かるのですが」"

[[dialogue]]
speaker = "シルヴィ"
# 「初対面だと思ったら、すでに出会ってたなんて、運命感じちゃう！　フライドチキンが結んだ縁だね！」
line = "「初対面だと思ったら、すでに出会ってたなんて、運命感じちゃう！　フライドチキンが結んだ縁だね！」"

[[dialogue]]
speaker = "シルヴィ"
# 「じゃ、改めてよろしく！　これでもプリマステラだから何かあったら遠慮なく頼ってね！」
line = "「じゃ、改めてよろしく！　これでもプリマステラだから何かあったら遠慮なく頼ってね！」"

[[dialogue]]
speaker = "unk"
# シルヴィ先輩は俺の手を取ると、ぶんぶん握手するのだった。
line = "シルヴィ先輩は俺の手を取ると、ぶんぶん握手するのだった。"
