[[dialogue]]
speaker = "unk"
# 第３話,１０年ぶりの……,P
line = "第３話,１０年ぶりの……,P"

[[dialogue]]
speaker = "unk"
# 最近、グレイスと一緒に過ごす日々が増えている。
line = "最近、グレイスと一緒に過ごす日々が増えている。"

[[dialogue]]
speaker = "unk"
# 彼女は一見すると能天気で賑やかな魔族の少女だけれど……先日のエステルとの一件以来、ナイーブな一面もあることを知った。
line = "彼女は一見すると能天気で賑やかな魔族の少女だけれど……先日のエステルとの一件以来、ナイーブな一面もあることを知った。"

[[dialogue]]
speaker = "unk"
# 彼女に惹かれ始めていた俺は、少しでもグレイスに喜んでもらえることはないかと考えるようになり──
line = "彼女に惹かれ始めていた俺は、少しでもグレイスに喜んでもらえることはないかと考えるようになり──"

[[dialogue]]
speaker = "グレイス"
# 「むふふふ～♪　サランさんからワッフルをいただいちゃいました。魔王さんもお１ついかがですか？」
line = "「むふふふ～♪　サランさんからワッフルをいただいちゃいました。魔王さんもお１ついかがですか？」"

[[dialogue]]
speaker = "グレイス"
# 「……あれ？　どうかしましたか、真面目なお顔ですね」
line = "「……あれ？　どうかしましたか、真面目なお顔ですね」"

[[dialogue]]
speaker = "unk"
# グレイス、明日の予定は空いてる？
line = "グレイス、明日の予定は空いてる？"

[[dialogue]]
speaker = "グレイス"
# 「はい、空いてますよ！　何か美味しいものでも食べに行くんですか？　だったら──」
line = "「はい、空いてますよ！　何か美味しいものでも食べに行くんですか？　だったら──」"

[[dialogue]]
speaker = "unk"
# 明日、君の両親がここに来る
line = "明日、君の両親がここに来る"

[[dialogue]]
speaker = "グレイス"
# 「えっ……！？」
line = "「えっ……！？」"

[[dialogue]]
speaker = "unk"
# 君さえよかったら、会ってみないか？
line = "君さえよかったら、会ってみないか？"

[[dialogue]]
speaker = "グレイス"
# 「…………それは」
line = "「…………それは」"

[[dialogue]]
speaker = "unk"
# 翌日の放課後──
line = "翌日の放課後──"

[[dialogue]]
speaker = "アナ"
# 「オベロニア夫妻が今、受付を終えたとの連絡が。すぐにここに到着するはずです」
line = "「オベロニア夫妻が今、受付を終えたとの連絡が。すぐにここに到着するはずです」"

[[dialogue]]
speaker = "マトイ"
# 「……本当に会わなくていいの、グレイスちゃん？」
line = "「……本当に会わなくていいの、グレイスちゃん？」"

[[dialogue]]
speaker = "グレイス"
# 「い、いいですっ。物陰から見るだけで……大丈夫です……」
line = "「い、いいですっ。物陰から見るだけで……大丈夫です……」"

[[dialogue]]
speaker = "グレイス"
# 「……っ！！」
line = "「……っ！！」"

[[dialogue]]
speaker = "アナ"
# 「どうぞ──お入りください」
line = "「どうぞ──お入りください」"

[[dialogue]]
speaker = "アナ"
# 「初めまして。オベロニアさん。新星星徒会へようこそ」
line = "「初めまして。オベロニアさん。新星星徒会へようこそ」"

[[dialogue]]
speaker = "グレイスの父"
# 「お忙しいところをすみません。失礼いたします」
line = "「お忙しいところをすみません。失礼いたします」"

[[dialogue]]
speaker = "グレイスの母"
# 「貴方が緋宮クロト様ですね。星徒会長としてのご活躍は、かねがね──」
line = "「貴方が緋宮クロト様ですね。星徒会長としてのご活躍は、かねがね──」"

[[dialogue]]
speaker = "グレイス"
# 「お父さん……お母さん……」
line = "「お父さん……お母さん……」"

[[dialogue]]
speaker = "グレイス"
# 「……………………生きてます」
line = "「……………………生きてます」"

[[dialogue]]
speaker = "unk"
# 平行世界人は、１つの世界において、同一存在が同時に意識を保つことはできない。
line = "平行世界人は、１つの世界において、同一存在が同時に意識を保つことはできない。"

[[dialogue]]
speaker = "unk"
# 『アルタイルのグレイス』は、チナやエステルと同じく昏倒しており、現在は流星市国の病院に入院中だ。
line = "『アルタイルのグレイス』は、チナやエステルと同じく昏倒しており、現在は流星市国の病院に入院中だ。"

[[dialogue]]
speaker = "unk"
# 平行世界のトラブルにまつわる昏倒のため、学園側が入院の手続きなどを取った結果、オベロニア夫妻からお礼を言いたいとの連絡を受けていたのだ。
line = "平行世界のトラブルにまつわる昏倒のため、学園側が入院の手続きなどを取った結果、オベロニア夫妻からお礼を言いたいとの連絡を受けていたのだ。"

[[dialogue]]
speaker = "unk"
# ならば学園に呼べば、１０年ぶりの再会となる。グレイスはきっと喜んでくれると思っていたのだけれど──
line = "ならば学園に呼べば、１０年ぶりの再会となる。グレイスはきっと喜んでくれると思っていたのだけれど──"

[[dialogue]]
speaker = "グレイス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# グレイスは結局、両親の顔を眺めるだけで、決して物影から出ようとしないのだった──
line = "グレイスは結局、両親の顔を眺めるだけで、決して物影から出ようとしないのだった──"

[[dialogue]]
speaker = "アナ"
# 「──グレイスさん。ご両親が、お帰りになりましたよ」
line = "「──グレイスさん。ご両親が、お帰りになりましたよ」"

[[dialogue]]
speaker = "グレイス"
# 「……ふぅ。緊張しました！」
line = "「……ふぅ。緊張しました！」"

[[dialogue]]
speaker = "マトイ"
# 「落ち着いてて、優しい人達だったね」
line = "「落ち着いてて、優しい人達だったね」"

[[dialogue]]
speaker = "グレイス"
# 「ふふふ。自慢の両親ですから！　あと、やっぱり確信しました。私はお母さん似だと！」
line = "「ふふふ。自慢の両親ですから！　あと、やっぱり確信しました。私はお母さん似だと！」"

[[dialogue]]
speaker = "アナ"
# 「そうですね。外見はお母様に似ていました」
line = "「そうですね。外見はお母様に似ていました」"

[[dialogue]]
speaker = "マトイ"
# 「性格の方は、見た目通りの大人しい人だったから……ちょっと違うかも？　あはは」
line = "「性格の方は、見た目通りの大人しい人だったから……ちょっと違うかも？　あはは」"

[[dialogue]]
speaker = "グレイス"
# 「そ、そんなぁっ！？」
line = "「そ、そんなぁっ！？」"

[[dialogue]]
speaker = "unk"
# ──余計なお節介、だったかな？
line = "──余計なお節介、だったかな？"

[[dialogue]]
speaker = "unk"
# （……明るくふるまってる感じだ）
line = "（……明るくふるまってる感じだ）"

[[dialogue]]
speaker = "グレイス"
# 「……いいえ、そんなことないですっ！　魔王さんの申し出はすごくありがたかったですよ！」
line = "「……いいえ、そんなことないですっ！　魔王さんの申し出はすごくありがたかったですよ！」"

[[dialogue]]
speaker = "グレイス"
# 「１０年ぶりです。元気なお父さんとお母さんを見ることができた──それだけで十分です！」
line = "「１０年ぶりです。元気なお父さんとお母さんを見ることができた──それだけで十分です！」"

[[dialogue]]
speaker = "グレイス"
# 「私が名乗る時は……全てを終えた時。リクリエを跳ねのけて、世界が平和になったその時にしますから。今は大丈夫です！」
line = "「私が名乗る時は……全てを終えた時。リクリエを跳ねのけて、世界が平和になったその時にしますから。今は大丈夫です！」"

[[dialogue]]
speaker = "unk"
# ……そうか
line = "……そうか"

[[dialogue]]
speaker = "アナ"
# 「それにしても今日は貴重な話がたくさん聞けました。やはり平行世界間では大筋、同じようなことが起こるようですね」
line = "「それにしても今日は貴重な話がたくさん聞けました。やはり平行世界間では大筋、同じようなことが起こるようですね」"

[[dialogue]]
speaker = "アナ"
# 「まあ、『同じ人物が、同じタイミングで、同じようなことを考えた』となれば、出来事が似通るのは当然のことですが」
line = "「まあ、『同じ人物が、同じタイミングで、同じようなことを考えた』となれば、出来事が似通るのは当然のことですが」"

[[dialogue]]
speaker = "マトイ"
# 「ね。デネブで１０年前に起きた、子供グレイスちゃんの潜入捜査……実はアルタイルでも起こってただなんて」
line = "「ね。デネブで１０年前に起きた、子供グレイスちゃんの潜入捜査……実はアルタイルでも起こってただなんて」"

[[dialogue]]
speaker = "unk"
# ただ、アルタイル固有の現象もある、か……
line = "ただ、アルタイル固有の現象もある、か……"

[[dialogue]]
speaker = "グレイス"
# 「お母さん、世間話をする時にいつも私のやらかしエピソードを喋るんです。困ったものです」
line = "「お母さん、世間話をする時にいつも私のやらかしエピソードを喋るんです。困ったものです」"

[[dialogue]]
speaker = "マトイ"
# 「それはグレイスちゃんがいつも周りを振り回してるからじゃあ……？」
line = "「それはグレイスちゃんがいつも周りを振り回してるからじゃあ……？」"

[[dialogue]]
speaker = "unk"
# アルタイルで起きたグレイスの潜入は、開始１分で終わったらしい。
line = "アルタイルで起きたグレイスの潜入は、開始１分で終わったらしい。"

[[dialogue]]
speaker = "unk"
# 見咎めたのは──セイファート学園長。
line = "見咎めたのは──セイファート学園長。"

[[dialogue]]
speaker = "unk"
# 彼が見つけて、ご両親に引き渡したらしい……だから俺たち星徒会役員も、グレイスのことを知らなかった──
line = "彼が見つけて、ご両親に引き渡したらしい……だから俺たち星徒会役員も、グレイスのことを知らなかった──"

[[dialogue]]
speaker = "unk"
# その日の夜──
line = "その日の夜──"

[[dialogue]]
speaker = "グレイス"
# （本当は会いたかった。顔を見せて、名前を名乗って……平行世界人ではあるけれど、実の娘だと言いたかったです……）
line = "（本当は会いたかった。顔を見せて、名前を名乗って……平行世界人ではあるけれど、実の娘だと言いたかったです……）"

[[dialogue]]
speaker = "チナ"
# 「なんかあったのかグレイス。今日はやけに静かだな？」
line = "「なんかあったのかグレイス。今日はやけに静かだな？」"

[[dialogue]]
speaker = "グレイス"
# （でも……チナも先日、街で偶然ご両親に会ったと。その時に、名乗らずにごまかしたって聞きました……）
line = "（でも……チナも先日、街で偶然ご両親に会ったと。その時に、名乗らずにごまかしたって聞きました……）"

[[dialogue]]
speaker = "グレイス"
# （だったら私だけ先に再会を果たしちゃうのは……チナに悪いですからねっ）
line = "（だったら私だけ先に再会を果たしちゃうのは……チナに悪いですからねっ）"

[[dialogue]]
speaker = "チナ"
# 「グレイス、調子でも悪いのか……？」
line = "「グレイス、調子でも悪いのか……？」"

[[dialogue]]
speaker = "グレイス"
# 「──いいえ！　今日の夕食は何だろうって考えてました！」
line = "「──いいえ！　今日の夕食は何だろうって考えてました！」"

[[dialogue]]
speaker = "チナ"
# 「はぁああ……！　お前ってやつは、ほんっと能天気だよなぁ。心配して損した」
line = "「はぁああ……！　お前ってやつは、ほんっと能天気だよなぁ。心配して損した」"

[[dialogue]]
speaker = "グレイス"
# 「なにおう～っ！？」
line = "「なにおう～っ！？」"

[[dialogue]]
speaker = "グレイス"
# （お父さん、お母さん。全てが終わったら──その時にまた会いましょう！）
line = "（お父さん、お母さん。全てが終わったら──その時にまた会いましょう！）"
