[[dialogue]]
speaker = "unk"
# 第１話,錬金術師の弟子です、ぶい,P
line = "第１話,錬金術師の弟子です、ぶい,P"

[[dialogue]]
speaker = "unk"
# 先日のギガンドム事件を経て、晴れて錬金術師・アニマ先輩の弟子と認められたシュティレ。
line = "先日のギガンドム事件を経て、晴れて錬金術師・アニマ先輩の弟子と認められたシュティレ。"

[[dialogue]]
speaker = "unk"
# そんな彼女が、新星学園の星徒会室へとやってきた──
line = "そんな彼女が、新星学園の星徒会室へとやってきた──"

[[dialogue]]
speaker = "シュティレ"
# 「失礼いたします。会長はいらっしゃいますでしょうか？　先日のお礼を改めてお伝えに参りました」
line = "「失礼いたします。会長はいらっしゃいますでしょうか？　先日のお礼を改めてお伝えに参りました」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あら？　あなたは確か……」
line = "「あら？　あなたは確か……」"

[[dialogue]]
speaker = "シュティレ"
# 「はい。天才錬金術師、アニマ先輩の一番弟子。閃光のシュティレと申します。ぶい」
line = "「はい。天才錬金術師、アニマ先輩の一番弟子。閃光のシュティレと申します。ぶい」"

[[dialogue]]
speaker = "マトイ"
# 「なんかカッコイイ二つ名がついてる！？　ふ、普通じゃない……！！」
line = "「なんかカッコイイ二つ名がついてる！？　ふ、普通じゃない……！！」"

[[dialogue]]
speaker = "シュティレ"
# 「先日見たロボットアニメのタイトルを一部拝借して、名乗りに使わせていただきました。ぶいぶい」
line = "「先日見たロボットアニメのタイトルを一部拝借して、名乗りに使わせていただきました。ぶいぶい」"

[[dialogue]]
speaker = "ヴィーナス"
# 「こうして私と顔を合わせるのは初めてよね。ふっふーん、なかなか面白い女の子みたいじゃない！」
line = "「こうして私と顔を合わせるのは初めてよね。ふっふーん、なかなか面白い女の子みたいじゃない！」"

[[dialogue]]
speaker = "シュティレ"
# 「はい。常に『おもしれー女』を目指しております。ぶい」
line = "「はい。常に『おもしれー女』を目指しております。ぶい」"

[[dialogue]]
speaker = "マトイ"
# 「しっかりピースサインも作ってキャラ付けもバッチリ……！　そ、そうかっ、こんな風にアピールすれば普通じゃなくなるんだ……！」
line = "「しっかりピースサインも作ってキャラ付けもバッチリ……！　そ、そうかっ、こんな風にアピールすれば普通じゃなくなるんだ……！」"

[[dialogue]]
speaker = "unk"
# マトイはすぐ影響を受けるんだから……
line = "マトイはすぐ影響を受けるんだから……"

[[dialogue]]
speaker = "ヴィーナス"
# 「初めまして、私の名前は九浄ヴィーナス！　この新星星徒会のスーパー……いいえ、ウルトラフィクサーよ！！」
line = "「初めまして、私の名前は九浄ヴィーナス！　この新星星徒会のスーパー……いいえ、ウルトラフィクサーよ！！」"

[[dialogue]]
speaker = "マトイ"
# 「また肩書きがグレードアップしてる！？　え、ええと、ウルトラ書記の詠野マトイです！」
line = "「また肩書きがグレードアップしてる！？　え、ええと、ウルトラ書記の詠野マトイです！」"

[[dialogue]]
speaker = "シュティレ"
# 「お二人とも、仔細なご挨拶、恐縮の至り。それにしてもヴィーナス先輩は、フィクサー……？」
line = "「お二人とも、仔細なご挨拶、恐縮の至り。それにしてもヴィーナス先輩は、フィクサー……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうよ、フィクサー！」
line = "「そうよ、フィクサー！」"

[[dialogue]]
speaker = "シュティレ"
# 「なんだか『グリッターマン』に出てきそうな肩書きですね。もしやビームを撃つのが得意ではありませんか？」
line = "「なんだか『グリッターマン』に出てきそうな肩書きですね。もしやビームを撃つのが得意ではありませんか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「っ！　クロト、この子鋭いわ！　只者じゃないわね！」
line = "「っ！　クロト、この子鋭いわ！　只者じゃないわね！」"

[[dialogue]]
speaker = "シュティレ"
# 「はい。シュティレは只者ではありません。なにせ錬金術師の弟子ですから」
line = "「はい。シュティレは只者ではありません。なにせ錬金術師の弟子ですから」"

[[dialogue]]
speaker = "マトイ"
# 「前からシュティレちゃんのこと、アナから話だけは聞いてたんだ。ちょうどお茶しようと思ってたところだから、ゆっくりしていってね」
line = "「前からシュティレちゃんのこと、アナから話だけは聞いてたんだ。ちょうどお茶しようと思ってたところだから、ゆっくりしていってね」"

[[dialogue]]
speaker = "シュティレ"
# 「なんと。アポもなく訊ねた私を歓迎してくださるとは」
line = "「なんと。アポもなく訊ねた私を歓迎してくださるとは」"

[[dialogue]]
speaker = "ヴィーナス"
# 「マトイの作るお菓子は絶品よ！　ほっぺが落ちないように注意することね！」
line = "「マトイの作るお菓子は絶品よ！　ほっぺが落ちないように注意することね！」"

[[dialogue]]
speaker = "シュティレ"
# 「承知いたしました。ご相伴に預かります。甘い物は好きです。わくわく」
line = "「承知いたしました。ご相伴に預かります。甘い物は好きです。わくわく」"

[[dialogue]]
speaker = "マトイ"
# 「あはは……普通のマドレーヌだから、過度な期待しないでね……？」
line = "「あはは……普通のマドレーヌだから、過度な期待しないでね……？」"

[[dialogue]]
speaker = "シュティレ"
# 「市販されていないマドレーヌ、初めて食べました。卵やバターの香りがほのかに残り、口の中で溶ける。まさに<ruby=ふうみぜっか>風味絶佳</ruby>」
line = "「市販されていないマドレーヌ、初めて食べました。卵やバターの香りがほのかに残り、口の中で溶ける。まさに<ruby>風味絶佳<rt>ふうみぜっか</rt></ruby>」"

[[dialogue]]
speaker = "マトイ"
# 「経験したことのない語彙で褒められてる……！」
line = "「経験したことのない語彙で褒められてる……！」"

[[dialogue]]
speaker = "シュティレ"
# 「ご馳走様でした。時に先輩方、不躾なご依頼で恐縮なのですが……シュティレと記念撮影をしていただけませんか？」
line = "「ご馳走様でした。時に先輩方、不躾なご依頼で恐縮なのですが……シュティレと記念撮影をしていただけませんか？」"

[[dialogue]]
speaker = "シュティレ"
# 「私、お近づきになった方と、自撮りをするのが趣味なのです」
line = "「私、お近づきになった方と、自撮りをするのが趣味なのです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「もちろんよ！　ほら、マトイもクロトも！」
line = "「もちろんよ！　ほら、マトイもクロトも！」"

[[dialogue]]
speaker = "マトイ"
# 「ちょっと恥ずかしいけど……こ、こうかな？」
line = "「ちょっと恥ずかしいけど……こ、こうかな？」"

[[dialogue]]
speaker = "シュティレ"
# 「では、カメラタイマー起動です。３、２、１──ぶいっ」
line = "「では、カメラタイマー起動です。３、２、１──ぶいっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ぶい！」
line = "「ぶい！」"

[[dialogue]]
speaker = "マトイ"
# 「ぶ、ぶい……？」
line = "「ぶ、ぶい……？」"

[[dialogue]]
speaker = "unk"
# ぶい！（←もう慣れっこ）
line = "ぶい！（←もう慣れっこ）"

[[dialogue]]
speaker = "シュティレ"
# 「ありがとうございます。ＤＩＳＣに写真、お送りしますね」
line = "「ありがとうございます。ＤＩＳＣに写真、お送りしますね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ありがと～！　へぇ、綺麗に取れてるじゃない！」
line = "「ありがと～！　へぇ、綺麗に取れてるじゃない！」"

[[dialogue]]
speaker = "マトイ"
# 「撮影した後の写真データ、光の強さとか色々と数値をいじってたけど……シュティレちゃんってＤＩＳＣに詳しいの？」
line = "「撮影した後の写真データ、光の強さとか色々と数値をいじってたけど……シュティレちゃんってＤＩＳＣに詳しいの？」"

[[dialogue]]
speaker = "unk"
# シュティレは機械系の専門だよ
line = "シュティレは機械系の専門だよ"

[[dialogue]]
speaker = "シュティレ"
# 「はい。錬金術師としては卵ですが、機械いじりは得意です。たっぷりロボットアニメを見ているので」
line = "「はい。錬金術師としては卵ですが、機械いじりは得意です。たっぷりロボットアニメを見ているので」"

[[dialogue]]
speaker = "マトイ"
# 「それって関係あるのかな……？」
line = "「それって関係あるのかな……？」"

[[dialogue]]
speaker = "シュティレ"
# 「では会長のＤＩＳＣにも送信を……と、妙ですね。送信エラーが出てしまいます」
line = "「では会長のＤＩＳＣにも送信を……と、妙ですね。送信エラーが出てしまいます」"

[[dialogue]]
speaker = "unk"
# 最近、ＤＩＳＣの調子が悪いんだ
line = "最近、ＤＩＳＣの調子が悪いんだ"

[[dialogue]]
speaker = "シュティレ"
# 「なんと。でしたら私にお任せください。ドリルやパイルバンカー制作は言うに及ばず、ＤＩＳＣいじりも得意です」
line = "「なんと。でしたら私にお任せください。ドリルやパイルバンカー制作は言うに及ばず、ＤＩＳＣいじりも得意です」"

[[dialogue]]
speaker = "シュティレ"
# 「では失礼して──分解」
line = "「では失礼して──分解」"

[[dialogue]]
speaker = "マトイ"
# 「わっ……会長のＤＩＳＣ、あっという間にばらばらになっちゃった……！」
line = "「わっ……会長のＤＩＳＣ、あっという間にばらばらになっちゃった……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「これ、元に戻せるの？　さらに壊しちゃってない？」
line = "「これ、元に戻せるの？　さらに壊しちゃってない？」"

[[dialogue]]
speaker = "シュティレ"
# 「そんなことはありません。機械の異常は、分解しなくてはわかりませんから……ああ、なるほど」
line = "「そんなことはありません。機械の異常は、分解しなくてはわかりませんから……ああ、なるほど」"

[[dialogue]]
speaker = "シュティレ"
# 「原因がわかりました。部品交換の必要はありませんので、このまま処置します」
line = "「原因がわかりました。部品交換の必要はありませんので、このまま処置します」"

[[dialogue]]
speaker = "マトイ"
# 「わー……すごく手際がいいね！」
line = "「わー……すごく手際がいいね！」"

[[dialogue]]
speaker = "シュティレ"
# 「よろしければ会長。ついでに機体スペックも上げておきましょうか？　耐衝撃と冷却を兼ねたジェルを仕込んだりなど、小さな改造ですが」
line = "「よろしければ会長。ついでに機体スペックも上げておきましょうか？　耐衝撃と冷却を兼ねたジェルを仕込んだりなど、小さな改造ですが」"

[[dialogue]]
speaker = "ヴィーナス"
# 「えー、すごいすごい！　私のもやって！」
line = "「えー、すごいすごい！　私のもやって！」"

[[dialogue]]
speaker = "シュティレ"
# 「問題ありません。この後、作業します」
line = "「問題ありません。この後、作業します」"

[[dialogue]]
speaker = "unk"
# ちょっぴり表情が硬いところもあるけれど、誰かと喋ったり親切をしたりするのはとても能動的なシュティレ。
line = "ちょっぴり表情が硬いところもあるけれど、誰かと喋ったり親切をしたりするのはとても能動的なシュティレ。"

[[dialogue]]
speaker = "unk"
# 変わり者だけど優しいアニマ先輩と、似通ったところのある錬金術師の弟子なのだった。
line = "変わり者だけど優しいアニマ先輩と、似通ったところのある錬金術師の弟子なのだった。"

[[dialogue]]
speaker = "シュティレ"
# 「ついでにタップ１つでドリルに変形するモードも搭載しましょう。ドリルはロマンですから」
line = "「ついでにタップ１つでドリルに変形するモードも搭載しましょう。ドリルはロマンですから」"

[[dialogue]]
speaker = "unk"
# 待って──！？
line = "待って──！？"

[[dialogue]]
speaker = "unk"
# こういうところも、やっぱりアニマ先輩の弟子だなあと思うのだった……
line = "こういうところも、やっぱりアニマ先輩の弟子だなあと思うのだった……"
