[[dialogue]]
speaker = "unk"
# 第３話,魅了の力,P
line = "第３話,魅了の力,P"

[[dialogue]]
speaker = "unk"
# 街での捜索を切り上げ、目撃情報のあった学園のカフェテリアにやってきた。
line = "街での捜索を切り上げ、目撃情報のあった学園のカフェテリアにやってきた。"

[[dialogue]]
speaker = "unk"
# しかし情報を確認してみると、どうやらそれは俺たちの捜している相手ではなかったようだった。
line = "しかし情報を確認してみると、どうやらそれは俺たちの捜している相手ではなかったようだった。"

[[dialogue]]
speaker = "マハムート"
# 「簡単に捕まえられるかと思っていたけれど、案外長期戦になってしまいそうね」
line = "「簡単に捕まえられるかと思っていたけれど、案外長期戦になってしまいそうね」"

[[dialogue]]
speaker = "フィオナ"
# 「カフェテリアに戻ってきたことですし、軽く食事をしていきませんか？」
line = "「カフェテリアに戻ってきたことですし、軽く食事をしていきませんか？」"

[[dialogue]]
speaker = "マハムート"
# 「それがいいわね。一旦、手がかりも途切れてしまったし、空腹を満たしながら新しい情報を待つことにするわよ」
line = "「それがいいわね。一旦、手がかりも途切れてしまったし、空腹を満たしながら新しい情報を待つことにするわよ」"

[[dialogue]]
speaker = "ルルゥ"
# 「わわ、とっても美味しそうなの♪」
line = "「わわ、とっても美味しそうなの♪」"

[[dialogue]]
speaker = "マハムート"
# 「ふふっ。むこうの世界の料理も美味しかったけれど、ここの料理も負けていないわよ。たっぷり味わいなさい」
line = "「ふふっ。むこうの世界の料理も美味しかったけれど、ここの料理も負けていないわよ。たっぷり味わいなさい」"

[[dialogue]]
speaker = "ルルゥ"
# 「いただきます、なの♪」
line = "「いただきます、なの♪」"

[[dialogue]]
speaker = "ルルゥ"
# 「もぐ……もぐ…………ふわ！　美味しい、なのっ！」
line = "「もぐ……もぐ…………ふわ！　美味しい、なのっ！」"

[[dialogue]]
speaker = "フィオナ"
# 「これは蛍火さんの料理ですね。今日は厨房に立っているって掲示板で流れてましたけど、どうやら本当だったみたいですね」
line = "「これは蛍火さんの料理ですね。今日は厨房に立っているって掲示板で流れてましたけど、どうやら本当だったみたいですね」"

[[dialogue]]
speaker = "マハムート"
# 「心なしか客が多いように感じていたけれど、それが理由だったのね」
line = "「心なしか客が多いように感じていたけれど、それが理由だったのね」"

[[dialogue]]
speaker = "ルルゥ"
# 「ウェイトレスさんも忙しそう、なの……」
line = "「ウェイトレスさんも忙しそう、なの……」"

[[dialogue]]
speaker = "フィオナ"
# 「そうですね。クエスト受付嬢のヨミさんもお手伝いしているみたいですし」
line = "「そうですね。クエスト受付嬢のヨミさんもお手伝いしているみたいですし」"

[[dialogue]]
speaker = "ルルゥ"
# 「実は……ルルゥ、臆病な性格をちょっとでも改善しようと思って、メイド喫茶のウェイトレスをしたことがある、なの」
line = "「実は……ルルゥ、臆病な性格をちょっとでも改善しようと思って、メイド喫茶のウェイトレスをしたことがある、なの」"

[[dialogue]]
speaker = "マハムート"
# 「それは中々の荒療治ね……。けれど、いい気概だと思うわ。結果はどうだったのかしら？」
line = "「それは中々の荒療治ね……。けれど、いい気概だと思うわ。結果はどうだったのかしら？」"

[[dialogue]]
speaker = "ルルゥ"
# 「……大変なことになっちゃった、なの」
line = "「……大変なことになっちゃった、なの」"

[[dialogue]]
speaker = "フィオナ"
# 「苦手なことに挑戦したのですから、失敗は仕方ないと思いますよ」
line = "「苦手なことに挑戦したのですから、失敗は仕方ないと思いますよ」"

[[dialogue]]
speaker = "マハムート"
# 「そうね。失敗を糧にして、自分をどう成長させるかを考えることが重要よ」
line = "「そうね。失敗を糧にして、自分をどう成長させるかを考えることが重要よ」"

[[dialogue]]
speaker = "unk"
# ここで少し働いてみる？
line = "ここで少し働いてみる？"

[[dialogue]]
speaker = "unk"
# もしよかったら
line = "もしよかったら"

[[dialogue]]
speaker = "ルルゥ"
# 「ふわっ！？　そ、それはやめた方がいいの……ここも大変なことになっちゃうかも、なの」
line = "「ふわっ！？　そ、それはやめた方がいいの……ここも大変なことになっちゃうかも、なの」"

[[dialogue]]
speaker = "フィオナ"
# 「大変なこと……具体的に、どういうことになったんですか？」
line = "「大変なこと……具体的に、どういうことになったんですか？」"

[[dialogue]]
speaker = "ルルゥ"
# 「働いてる最中に、魅了の力が発動しちゃった、なの……そうしたら、お店にいたお客さんが一斉にルルゥのところに押しかけちゃったの」
line = "「働いてる最中に、魅了の力が発動しちゃった、なの……そうしたら、お店にいたお客さんが一斉にルルゥのところに押しかけちゃったの」"

[[dialogue]]
speaker = "ルルゥ"
# 「特に一部のお客さんが……その……興奮してしまって、とっても怖かったの……」
line = "「特に一部のお客さんが……その……興奮してしまって、とっても怖かったの……」"

[[dialogue]]
speaker = "フィオナ"
# 「そ、それは……」
line = "「そ、それは……」"

[[dialogue]]
speaker = "マハムート"
# 「何となく状況が浮かんでくるわね……」
line = "「何となく状況が浮かんでくるわね……」"

[[dialogue]]
speaker = "ルルゥ"
# 「だからウェイトレスはもうしない、なの」
line = "「だからウェイトレスはもうしない、なの」"

[[dialogue]]
speaker = "unk"
# どうしても力の制御は難しいの？
line = "どうしても力の制御は難しいの？"

[[dialogue]]
speaker = "ルルゥ"
# 「ごめんなさい、なの……頑張ってるけど、やっぱり自分では上手く制御できないの」
line = "「ごめんなさい、なの……頑張ってるけど、やっぱり自分では上手く制御できないの」"

[[dialogue]]
speaker = "ルルゥ"
# 「ルルゥが相手の人と仲良くなりたいって思った時、無意識に働いてしまうことが多いみたいなの」
line = "「ルルゥが相手の人と仲良くなりたいって思った時、無意識に働いてしまうことが多いみたいなの」"

[[dialogue]]
speaker = "ルルゥ"
# 「そのせいで……ご主人様のこともおかしくしちゃうことがよくある、なの……」
line = "「そのせいで……ご主人様のこともおかしくしちゃうことがよくある、なの……」"

[[dialogue]]
speaker = "ルルゥ"
# 「でもご主人様はとっても優しくて、ルルゥが失敗しても笑って許してくれるの<emoji=heart04>」
line = "「でもご主人様はとっても優しくて、ルルゥが失敗しても笑って許してくれるの<emoji=heart04>」"

[[dialogue]]
speaker = "マハムート"
# 「あの少年はルルゥだけではなくて、本当に島中のモンスター娘から好かれていたわね」
line = "「あの少年はルルゥだけではなくて、本当に島中のモンスター娘から好かれていたわね」"

[[dialogue]]
speaker = "ルルゥ"
# 「そうなの♪　みんな、ご主人様のことが大好きなの♪」
line = "「そうなの♪　みんな、ご主人様のことが大好きなの♪」"

[[dialogue]]
speaker = "ルルゥ"
# 「ルルゥも最初は怖かったの……でも、チールちゃんからいいニンゲンだって教えてもらったの」
line = "「ルルゥも最初は怖かったの……でも、チールちゃんからいいニンゲンだって教えてもらったの」"

[[dialogue]]
speaker = "ルルゥ"
# 「だからちゃんとお話、してみたの。それで仲良くなって、ルルゥが１人でいたら声をかけてくれるし、密猟者から守ってくれるようになったの」
line = "「だからちゃんとお話、してみたの。それで仲良くなって、ルルゥが１人でいたら声をかけてくれるし、密猟者から守ってくれるようになったの」"

[[dialogue]]
speaker = "ルルゥ"
# 「それでそれで──」
line = "「それでそれで──」"

[[dialogue]]
speaker = "unk"
# 『ご主人様』の話をしているルルゥは、臆病な気持ちをどこかに忘れてきたかのようだった。
line = "『ご主人様』の話をしているルルゥは、臆病な気持ちをどこかに忘れてきたかのようだった。"

[[dialogue]]
speaker = "unk"
# そんなルルゥの笑顔を見ていると、ゲシュペンス島のモンスター娘たちが、その少年を中心に仲良く過ごしていることが伝わってくる。
line = "そんなルルゥの笑顔を見ていると、ゲシュペンス島のモンスター娘たちが、その少年を中心に仲良く過ごしていることが伝わってくる。"

[[dialogue]]
speaker = "unk"
# そして、ルルゥの能力について──
line = "そして、ルルゥの能力について──"

[[dialogue]]
speaker = "unk"
# 難しい能力ではあるが、さきほど魅了されかかったことを思い出し、嬉しい気持ちにもなってしまう。
line = "難しい能力ではあるが、さきほど魅了されかかったことを思い出し、嬉しい気持ちにもなってしまう。"

[[dialogue]]
speaker = "unk"
# それは、ルルゥが俺とも仲良くしようとしてくれた、気持ちの表れでもあるからだった。
line = "それは、ルルゥが俺とも仲良くしようとしてくれた、気持ちの表れでもあるからだった。"
