[[dialogue]]
speaker = "unk"
# 第３話,メルエルとサチ,P
line = "第３話,メルエルとサチ,P"

[[dialogue]]
speaker = "サチ"
# 「あっ！　お兄さん、こんにちは」
line = "「あっ！　お兄さん、こんにちは」"

[[dialogue]]
speaker = "unk"
# 放課後、飲み物を買いに来たカフェテリアで声をかけられて振り返ると、そこにいたのは流星学園附属校生徒会長の『<ruby=しろつめ>白詰</ruby>サチ』だった。
line = "放課後、飲み物を買いに来たカフェテリアで声をかけられて振り返ると、そこにいたのは流星学園附属校生徒会長の『<ruby>白詰<rt>しろつめ</rt></ruby>サチ』だった。"

[[dialogue]]
speaker = "unk"
# こんにちは。サチ、最近調子はどう？
line = "こんにちは。サチ、最近調子はどう？"

[[dialogue]]
speaker = "サチ"
# 「はい。お兄さんに負けないように、生徒会長としての業務も、星騎士としての訓練も頑張ってますよ♪」
line = "「はい。お兄さんに負けないように、生徒会長としての業務も、星騎士としての訓練も頑張ってますよ♪」"

[[dialogue]]
speaker = "サチ"
# 「あと、回収の方も。前に話した、お兄さんが不在の時に出現したロストアイテムの一件以降は、大きな騒動もなくて……」
line = "「あと、回収の方も。前に話した、お兄さんが不在の時に出現したロストアイテムの一件以降は、大きな騒動もなくて……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「じ～っ……」
line = "「じ～っ……」"

[[dialogue]]
speaker = "サチ"
# 「って、な、なんか強い視線を感じます……！」
line = "「って、な、なんか強い視線を感じます……！」"

[[dialogue]]
speaker = "unk"
# メルエル、なんで隠れて見てるんだ？
line = "メルエル、なんで隠れて見てるんだ？"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「――こんにちは、白詰サチさん♪」
line = "「――こんにちは、白詰サチさん♪」"

[[dialogue]]
speaker = "unk"
# 一緒に飲み物を買いにきていたメルエルが、隠れていた柱の影から出て、近くにやって来る。
line = "一緒に飲み物を買いにきていたメルエルが、隠れていた柱の影から出て、近くにやって来る。"

[[dialogue]]
speaker = "サチ"
# 「は、はい、こんにちは。……ええっと、もしかして姫咲先輩、ですか？」
line = "「は、はい、こんにちは。……ええっと、もしかして姫咲先輩、ですか？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「そう、今は『リトルフォーム』に変身して、体が小さくなってるんだ♪　最近は新フォームの感覚を体に覚えさせるために、よく変身してるの」
line = "「そう、今は『リトルフォーム』に変身して、体が小さくなってるんだ♪　最近は新フォームの感覚を体に覚えさせるために、よく変身してるの」"

[[dialogue]]
speaker = "サチ"
# 「それが噂に聞いたリトルフォーム……！　で、でも……じ～っ……大きいんですね……」
line = "「それが噂に聞いたリトルフォーム……！　で、でも……じ～っ……大きいんですね……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「えっ？」
line = "「えっ？」"

[[dialogue]]
speaker = "サチ"
# 「あ、いえ！　失礼しました、なんでもないです……！」
line = "「あ、いえ！　失礼しました、なんでもないです……！」"

[[dialogue]]
speaker = "サチ"
# （背丈は私と同じくらい小さくなっているはずなのに、胸はトレジアンナさんみたいに大きい……！）
line = "（背丈は私と同じくらい小さくなっているはずなのに、胸はトレジアンナさんみたいに大きい……！）"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「えっと……私ね、会長くんが白詰さんとは面識があって、仲良くしてることは前から知ってたんだ」
line = "「えっと……私ね、会長くんが白詰さんとは面識があって、仲良くしてることは前から知ってたんだ」"

[[dialogue]]
speaker = "サチ"
# 「そ、そうでしたか。私も、姫咲先輩のことはお兄さんからよく聞いていて……」
line = "「そ、そうでしたか。私も、姫咲先輩のことはお兄さんからよく聞いていて……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「ねぇ、白詰さん！　このあと、時間あったりするかな？」
line = "「ねぇ、白詰さん！　このあと、時間あったりするかな？」"

[[dialogue]]
speaker = "unk"
# メルエルはクロトと別れて、サチに附属校の校内を案内してもらっていた。
line = "メルエルはクロトと別れて、サチに附属校の校内を案内してもらっていた。"

[[dialogue]]
speaker = "サチ"
# 「ここが私が所属している、附属校３年の教室になります」
line = "「ここが私が所属している、附属校３年の教室になります」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「わぁ～っ♪　新星学園の教室とは雰囲気が違うんだね～」
line = "「わぁ～っ♪　新星学園の教室とは雰囲気が違うんだね～」"

[[dialogue]]
speaker = "unk"
# メルエルはサチに案内してもらって、附属校の校舎へとやって来ていた。
line = "メルエルはサチに案内してもらって、附属校の校舎へとやって来ていた。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「白詰さん、附属校を詳しく案内してくれてありがとう♪」
line = "「白詰さん、附属校を詳しく案内してくれてありがとう♪」"

[[dialogue]]
speaker = "サチ"
# 「いえ。私は附属校の生徒会長ですから」
line = "「いえ。私は附属校の生徒会長ですから」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「私、附属校には通ったことなかったから、ちょっと憧れみたいなものがあったんだ」
line = "「私、附属校には通ったことなかったから、ちょっと憧れみたいなものがあったんだ」"

[[dialogue]]
speaker = "サチ"
# 「あ、あの……それで、２人きりで話したいことって？」
line = "「あ、あの……それで、２人きりで話したいことって？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「あのっ……前からちょっと気になっていたというか、気づいてたことがあるんだけど……」
line = "「あのっ……前からちょっと気になっていたというか、気づいてたことがあるんだけど……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「白詰さんたちと会長くんって、何か危ないことというか、秘密のこと、してるんじゃないかな？」
line = "「白詰さんたちと会長くんって、何か危ないことというか、秘密のこと、してるんじゃないかな？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「──ああいや！　そもそもリクリエと戦う私たちが、今更危ないことも何もないんだけど、ただ……」
line = "「──ああいや！　そもそもリクリエと戦う私たちが、今更危ないことも何もないんだけど、ただ……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「なんだか、リクリエ以外のモノと戦っていたりもしてて、それが内緒のことなのかなって思ったんだ」
line = "「なんだか、リクリエ以外のモノと戦っていたりもしてて、それが内緒のことなのかなって思ったんだ」"

[[dialogue]]
speaker = "サチ"
# （姫咲先輩、鋭すぎる……！）
line = "（姫咲先輩、鋭すぎる……！）"

[[dialogue]]
speaker = "サチ"
# 「えっとぉ……その、ですね……」
line = "「えっとぉ……その、ですね……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「ああっ、ごめんね！　その件で責めたいとか、そういうことじゃないの！」
line = "「ああっ、ごめんね！　その件で責めたいとか、そういうことじゃないの！」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「ただあのっ、会長くんがわざわざ秘密にしてるくらいのことだから、何だが凄く重要なことなんじゃないかなって思っちゃって……」
line = "「ただあのっ、会長くんがわざわざ秘密にしてるくらいのことだから、何だが凄く重要なことなんじゃないかなって思っちゃって……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「だから、その……」
line = "「だから、その……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「もし可能なら、私も手伝わせてほしいなって、そう思ってお願いしに来たの！」
line = "「もし可能なら、私も手伝わせてほしいなって、そう思ってお願いしに来たの！」"

[[dialogue]]
speaker = "サチ"
# 「えぇっ！？　姫咲先輩が私たちのお手伝い……！？」
line = "「えぇっ！？　姫咲先輩が私たちのお手伝い……！？」"

[[dialogue]]
speaker = "unk"
# その時、サチの四つ葉のクローバーの髪飾りが点滅し、突然この場にいない第三者の声が響き渡る。
line = "その時、サチの四つ葉のクローバーの髪飾りが点滅し、突然この場にいない第三者の声が響き渡る。"

[[dialogue]]
speaker = "トレジアンナ"
# 『メルエルさん！　その件については、私から説明しましょう！！』
line = "『メルエルさん！　その件については、私から説明しましょう！！』"

[[dialogue]]
speaker = "サチ"
# 「トレジアンナさん！？　一体どこから声をかけてるんですか！！」
line = "「トレジアンナさん！？　一体どこから声をかけてるんですか！！」"

[[dialogue]]
speaker = "トレジアンナ"
# 『いや～、すみません☆　秘密がピンチな緊急事態かと思い、突然失礼しちゃいました！』
line = "『いや～、すみません☆　秘密がピンチな緊急事態かと思い、突然失礼しちゃいました！』"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「えっと、附属校のトレジアンナさんですよね。会長くんやアニマ先輩と話しているところを見かけたことがあります」
line = "「えっと、附属校のトレジアンナさんですよね。会長くんやアニマ先輩と話しているところを見かけたことがあります」"

[[dialogue]]
speaker = "トレジアンナ"
# 『はい～、そのトレジアンナさんですよぉ♪　それで早速なんですが、確かに私たちには秘密があります！』
line = "『はい～、そのトレジアンナさんですよぉ♪　それで早速なんですが、確かに私たちには秘密があります！』"

[[dialogue]]
speaker = "トレジアンナ"
# 『ただですねぇ、その秘密をメルエルさんにお教えすることはできません！』
line = "『ただですねぇ、その秘密をメルエルさんにお教えすることはできません！』"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「それは……私が部外者だからでしょうか？」
line = "「それは……私が部外者だからでしょうか？」"

[[dialogue]]
speaker = "トレジアンナ"
# 『とんでもありません！　メルエルさんほど魔法少女姿が似合いそうな……じゃなかった、強力な星騎士の方に協力を申し出てもらえるのは、私としては凄く嬉しいです！』
line = "『とんでもありません！　メルエルさんほど魔法少女姿が似合いそうな……じゃなかった、強力な星騎士の方に協力を申し出てもらえるのは、私としては凄く嬉しいです！』"

[[dialogue]]
speaker = "トレジアンナ"
# 『信用、信頼の面においても……会長さんの恋人さんですから、そういう意味でも秘密を打ち明ける相手としては申し分ありません！』
line = "『信用、信頼の面においても……会長さんの恋人さんですから、そういう意味でも秘密を打ち明ける相手としては申し分ありません！』"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「なら、どうして……？」
line = "「なら、どうして……？」"

[[dialogue]]
speaker = "トレジアンナ"
# 『実は他でもない、会長さん自身に口止めされているんです！　メルエルさんをこの件に巻き込みたくない、と』
line = "『実は他でもない、会長さん自身に口止めされているんです！　メルエルさんをこの件に巻き込みたくない、と』"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「えっ、会長くんに！？」
line = "「えっ、会長くんに！？」"

[[dialogue]]
speaker = "トレジアンナ"
# 『いや～、お熱いですねぇ☆　私としては、メルエルさんにご協力いただくことはウェルカムなんですが、そのためにはまず、会長さんを口説き落とさないといけません』
line = "『いや～、お熱いですねぇ☆　私としては、メルエルさんにご協力いただくことはウェルカムなんですが、そのためにはまず、会長さんを口説き落とさないといけません』"

[[dialogue]]
speaker = "トレジアンナ"
# 『と、いうわけで、この件につきましては、もう少々お時間をいただけると幸いです！』
line = "『と、いうわけで、この件につきましては、もう少々お時間をいただけると幸いです！』"

[[dialogue]]
speaker = "トレジアンナ"
# 『そんなわけで、トレジアンナさんからの緊急通信は以上になります！』
line = "『そんなわけで、トレジアンナさんからの緊急通信は以上になります！』"

[[dialogue]]
speaker = "トレジアンナ"
# 『……あっ、それはそれとして、メルエルさんはサチさんと仲良くしてあげてください』
line = "『……あっ、それはそれとして、メルエルさんはサチさんと仲良くしてあげてください』"

[[dialogue]]
speaker = "トレジアンナ"
# 『協力をお願いしている私が言えた立場じゃないですが、サチさん、秘密の活動が忙しくてあんまりお友達がいないんですよ～』
line = "『協力をお願いしている私が言えた立場じゃないですが、サチさん、秘密の活動が忙しくてあんまりお友達がいないんですよ～』"

[[dialogue]]
speaker = "サチ"
# 「余計なお世話ですぅ！　ていうか別に、私、友達少なくないもん！」
line = "「余計なお世話ですぅ！　ていうか別に、私、友達少なくないもん！」"

[[dialogue]]
speaker = "サチ"
# 「って！　言いたいことだけ言って通信切れてる！？　もう、なんなんですか～～～！」
line = "「って！　言いたいことだけ言って通信切れてる！？　もう、なんなんですか～～～！」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「あはは……。初めてお話したけど、凄く勢いのある人だったね、トレジアンナさん」
line = "「あはは……。初めてお話したけど、凄く勢いのある人だったね、トレジアンナさん」"

[[dialogue]]
speaker = "サチ"
# 「も～～～～～、本当にそうなんです！　聞いてください、姫咲先輩！　この間も、こんなことがあってですね！？」
line = "「も～～～～～、本当にそうなんです！　聞いてください、姫咲先輩！　この間も、こんなことがあってですね！？」"

[[dialogue]]
speaker = "unk"
# 翌日の昼休み。
line = "翌日の昼休み。"

[[dialogue]]
speaker = "サチ"
# 「あっ！　お２人共、こんにちは♪」
line = "「あっ！　お２人共、こんにちは♪」"

[[dialogue]]
speaker = "unk"
# 俺がメルエルと一緒にカフェテリアへ行くと、サチとまた顔を合わせた。
line = "俺がメルエルと一緒にカフェテリアへ行くと、サチとまた顔を合わせた。"

[[dialogue]]
speaker = "メルエル"
# 「サチちゃ～ん！　昨日はありがとう♪」
line = "「サチちゃ～ん！　昨日はありがとう♪」"

[[dialogue]]
speaker = "サチ"
# 「いえいえ♪　私も昨日は色々お話できて楽しかったです、メルエル<b>お姉さん</b>♪」
line = "「いえいえ♪　私も昨日は色々お話できて楽しかったです、メルエル<b>お姉さん</b>♪」"

[[dialogue]]
speaker = "unk"
# お姉さん！？
line = "お姉さん！？"

[[dialogue]]
speaker = "メルエル"
# 「えへへ～♪　実はそうなんだ～♪」
line = "「えへへ～♪　実はそうなんだ～♪」"

[[dialogue]]
speaker = "unk"
# メルエルはサチへ親しげにくっ付きながら言う。
line = "メルエルはサチへ親しげにくっ付きながら言う。"

[[dialogue]]
speaker = "サチ"
# 「そ、その……昨日あれから話している内に、お姉さんの方から仲良くなろうって言って下さって。それでお話させてもらっている内に、なんだかそう呼びたくなって……♪」
line = "「そ、その……昨日あれから話している内に、お姉さんの方から仲良くなろうって言って下さって。それでお話させてもらっている内に、なんだかそう呼びたくなって……♪」"

[[dialogue]]
speaker = "メルエル"
# 「私もなんだか妹ができたみたいで、すごく嬉しくて～♪　ふふっ、会長くんがサチちゃんからお兄さん呼びされている時の気持ちが、ちょっとわかっちゃった♪」
line = "「私もなんだか妹ができたみたいで、すごく嬉しくて～♪　ふふっ、会長くんがサチちゃんからお兄さん呼びされている時の気持ちが、ちょっとわかっちゃった♪」"

[[dialogue]]
speaker = "unk"
# 昨日、一体あの後何があったんだ……
line = "昨日、一体あの後何があったんだ……"

[[dialogue]]
speaker = "メルエル"
# 「ふふっ、それは女の子同士の秘密だよ♪　ね、サチちゃん♪」
line = "「ふふっ、それは女の子同士の秘密だよ♪　ね、サチちゃん♪」"

[[dialogue]]
speaker = "サチ"
# 「はい、お姉さん♪」
line = "「はい、お姉さん♪」"

[[dialogue]]
speaker = "unk"
# そう言って、２人で仲良さそうに両手のひらをくっつけ合う、メルエルとサチなのであった。
line = "そう言って、２人で仲良さそうに両手のひらをくっつけ合う、メルエルとサチなのであった。"
