[[dialogue]]
speaker = "unk"
# 場所を変え、星徒会室で事情を聞くことになった。
line = "場所を変え、星徒会室で事情を聞くことになった。"

[[dialogue]]
speaker = "サチ"
# 「あの本、私たちが追いつくまでの間に、お兄さんの記憶も奪ってたなんて……！」
line = "「あの本、私たちが追いつくまでの間に、お兄さんの記憶も奪ってたなんて……！」"

[[dialogue]]
speaker = "プリムラ"
# 「眷族よ、大丈夫か！？　怪我はないのか！？」
line = "「眷族よ、大丈夫か！？　怪我はないのか！？」"

[[dialogue]]
speaker = "プリムラ"
# 「――そうか、記憶喪失というだけなんじゃな？　それならば、ひとまずはよい。怪我をされるよりマシじゃからな」
line = "「――そうか、記憶喪失というだけなんじゃな？　それならば、ひとまずはよい。怪我をされるよりマシじゃからな」"

[[dialogue]]
speaker = "サチ"
# 「ちょっと！　私が記憶を失った時と、反応違くない！？　なんで私の場合は怒るわけ！？」
line = "「ちょっと！　私が記憶を失った時と、反応違くない！？　なんで私の場合は怒るわけ！？」"

[[dialogue]]
speaker = "プリムラ"
# 「うっさいわ！　眷族は、我の第一の配下なんじゃ！　<ruby=あるじ>主</ruby>として、その身を案じるのは当然のことじゃ！」
line = "「うっさいわ！　眷族は、我の第一の配下なんじゃ！　<ruby>主<rt>あるじ</rt></ruby>として、その身を案じるのは当然のことじゃ！」"

[[dialogue]]
speaker = "プリムラ"
# 「大体、サチ！　貴様の場合は、幸運だからと調子に乗った挙句に、記憶を取られたんじゃろうが！　後先考えない行動しおってからに……！」
line = "「大体、サチ！　貴様の場合は、幸運だからと調子に乗った挙句に、記憶を取られたんじゃろうが！　後先考えない行動しおってからに……！」"

[[dialogue]]
speaker = "プリムラ"
# 「あそこでロストアイテムを逃がしてなければ、眷族の記憶が奪われることもなかったんじゃ！」
line = "「あそこでロストアイテムを逃がしてなければ、眷族の記憶が奪われることもなかったんじゃ！」"

[[dialogue]]
speaker = "サチ"
# 「逃がしたのはアンタも一緒でしょ！　１年くらい記憶を忘れてるからって、なんなのよ！」
line = "「逃がしたのはアンタも一緒でしょ！　１年くらい記憶を忘れてるからって、なんなのよ！」"

[[dialogue]]
speaker = "プリムラ"
# 「その『我に関する記憶』を忘れているせいで、連携ガタガタだったじゃろうが！」
line = "「その『我に関する記憶』を忘れているせいで、連携ガタガタだったじゃろうが！」"

[[dialogue]]
speaker = "サチ"
# 「アンタがもっと協力的なら、カバーできてたと思うんだけど！？」
line = "「アンタがもっと協力的なら、カバーできてたと思うんだけど！？」"

[[dialogue]]
speaker = "トマル"
# 「お、お２人とも、落ち着いて……それよりも今は、記憶喪失の会長さまに色々説明してあげませんと。ね？」
line = "「お、お２人とも、落ち着いて……それよりも今は、記憶喪失の会長さまに色々説明してあげませんと。ね？」"

[[dialogue]]
speaker = "サチ"
# 「……ごめんなさい。トマルくんの言う通りですね」
line = "「……ごめんなさい。トマルくんの言う通りですね」"

[[dialogue]]
speaker = "プリムラ"
# 「ふん」
line = "「ふん」"

[[dialogue]]
speaker = "サチ"
# 「お兄さん。私やプリムラのことも忘れちゃってるっていうのは、本当ですか？」
line = "「お兄さん。私やプリムラのことも忘れちゃってるっていうのは、本当ですか？」"

[[dialogue]]
speaker = "unk"
# ごめん。思い出せないんだ……
line = "ごめん。思い出せないんだ……"

[[dialogue]]
speaker = "サチ"
# 「いえ、元は私の不始末が原因ですから。私たちのことを覚えてないのなら、改めて自己紹介しないとですね――」
line = "「いえ、元は私の不始末が原因ですから。私たちのことを覚えてないのなら、改めて自己紹介しないとですね――」"

[[dialogue]]
speaker = "サチ"
# 「私は、流星学園附属校で<b>生徒会長</b>をやっている、<ruby=しろつめ>白詰</ruby>サチです」
line = "「私は、流星学園附属校で<b>生徒会長</b>をやっている、<ruby>白詰<rt>しろつめ</rt></ruby>サチです」"

[[dialogue]]
speaker = "サチ"
# 「附属校については――覚えてるみたいですね。流星学園の本校よりも、学年が下の生徒達が通っているところです」
line = "「附属校については――覚えてるみたいですね。流星学園の本校よりも、学年が下の生徒達が通っているところです」"

[[dialogue]]
speaker = "unk"
# ━━ちなみに新星学園の附属校はない。
line = "━━ちなみに新星学園の附属校はない。"

[[dialogue]]
speaker = "unk"
# 新星学園にスカウトした子がまだ若かった場合には、流星学園附属校に通ってから、新星学園に進学するパターンもあるのだとか。
line = "新星学園にスカウトした子がまだ若かった場合には、流星学園附属校に通ってから、新星学園に進学するパターンもあるのだとか。"

[[dialogue]]
speaker = "unk"
# 新星学園が開校した現在では、附属生は卒業後、どちらの学園に通うかを自身で選ぶことができるらしい。
line = "新星学園が開校した現在では、附属生は卒業後、どちらの学園に通うかを自身で選ぶことができるらしい。"

[[dialogue]]
speaker = "サチ"
# 「それで、こちらが私と同じく、生徒会所属の――」
line = "「それで、こちらが私と同じく、生徒会所属の――」"

[[dialogue]]
speaker = "プリムラ"
# 「我こそは、悪の終末兵器にして、やがて世界征服を成し遂げる支配者、プリムラじゃ！」
line = "「我こそは、悪の終末兵器にして、やがて世界征服を成し遂げる支配者、プリムラじゃ！」"

[[dialogue]]
speaker = "サチ"
# 「自称なんで、悪とか終末兵器とかは、とりあえずスルーしてください」
line = "「自称なんで、悪とか終末兵器とかは、とりあえずスルーしてください」"

[[dialogue]]
speaker = "プリムラ"
# 「自称じゃないわ！　眷族よ、忘れているかもしれんが貴様は、我と主従の契約を結んでいるのじゃ！」
line = "「自称じゃないわ！　眷族よ、忘れているかもしれんが貴様は、我と主従の契約を結んでいるのじゃ！」"

[[dialogue]]
speaker = "サチ"
# 「……眷族って、どうせプリムラが一方的にそう呼んでるだけなんじゃないの？」
line = "「……眷族って、どうせプリムラが一方的にそう呼んでるだけなんじゃないの？」"

[[dialogue]]
speaker = "プリムラ"
# 「嘘じゃないわい！　我が眷属の主なのじゃ！」
line = "「嘘じゃないわい！　我が眷属の主なのじゃ！」"

[[dialogue]]
speaker = "？？？"
# 「眷族なのは合ってますけど、力関係は逆ですよね～。契約失敗しちゃって、会長さんの方がプリムラさんの主なんですよ」
line = "「眷族なのは合ってますけど、力関係は逆ですよね～。契約失敗しちゃって、会長さんの方がプリムラさんの主なんですよ」"

[[dialogue]]
speaker = "プリムラ"
# 「こらっ、トレジアンナ！　余計なこと言うでないわ！」
line = "「こらっ、トレジアンナ！　余計なこと言うでないわ！」"

[[dialogue]]
speaker = "マトイ"
# 「これって、保健室で聞いたのと同じ声……！　一体どこから……？」
line = "「これって、保健室で聞いたのと同じ声……！　一体どこから……？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「マトイさんとは、これが初めましてですね～。サチさんの髪飾りから、声だけで失礼します～」
line = "「マトイさんとは、これが初めましてですね～。サチさんの髪飾りから、声だけで失礼します～」"

[[dialogue]]
speaker = "トレジアンナ"
# 「私、サチさんのロストアイテムに宿ってる、トレジアンナって言います～。よろしくお願いしますね～♪」
line = "「私、サチさんのロストアイテムに宿ってる、トレジアンナって言います～。よろしくお願いしますね～♪」"

[[dialogue]]
speaker = "マトイ"
# 「は、はい、よろしくお願いします……って、そろそろ教えて欲しいんだけど、ロストアイテムって一体なんなの？」
line = "「は、はい、よろしくお願いします……って、そろそろ教えて欲しいんだけど、ロストアイテムって一体なんなの？」"

[[dialogue]]
speaker = "サチ"
# 「あの本や、トレジアンナさん等ロストアイテムは……３０００年以上前から存在している、特殊な力を持つ道具なんです」
line = "「あの本や、トレジアンナさん等ロストアイテムは……３０００年以上前から存在している、特殊な力を持つ道具なんです」"

[[dialogue]]
speaker = "プリムラ"
# 「悪の終末兵器である我も、元はロストアイテム『賢者の石』から作られた存在なのじゃ」
line = "「悪の終末兵器である我も、元はロストアイテム『賢者の石』から作られた存在なのじゃ」"

[[dialogue]]
speaker = "マトイ"
# 「えっ！？　プリムラちゃんもそうなの！？」
line = "「えっ！？　プリムラちゃんもそうなの！？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「ロストアイテムは、それぞれ理屈を超越した力を持っていて、使い方を誤れば、それこそ世界を滅ぼすことも可能なくらい危険なものなんです」
line = "「ロストアイテムは、それぞれ理屈を超越した力を持っていて、使い方を誤れば、それこそ世界を滅ぼすことも可能なくらい危険なものなんです」"

[[dialogue]]
speaker = "プリムラ"
# 「ふふん、悪の終末兵器は自称でないと言ったじゃろう？」
line = "「ふふん、悪の終末兵器は自称でないと言ったじゃろう？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「世界にリクリエの危機が迫りつつある今、私を含めて、ロストアイテム達は長き眠りから目覚めつつあります」
line = "「世界にリクリエの危機が迫りつつある今、私を含めて、ロストアイテム達は長き眠りから目覚めつつあります」"

[[dialogue]]
speaker = "トレジアンナ"
# 「いえ、正確には、リクリエを引き起こす為に目覚めているのかもしれませんが……」
line = "「いえ、正確には、リクリエを引き起こす為に目覚めているのかもしれませんが……」"

[[dialogue]]
speaker = "サチ"
# 「そうならないように、私はトレジアンナさんに協力して、ロストアイテムの回収をしているんです」
line = "「そうならないように、私はトレジアンナさんに協力して、ロストアイテムの回収をしているんです」"

[[dialogue]]
speaker = "トレジアンナ"
# 「そう……サチさんに、魔法少女トレジャー☆サチへと変身してもらって！」
line = "「そう……サチさんに、魔法少女トレジャー☆サチへと変身してもらって！」"

[[dialogue]]
speaker = "サチ"
# 「魔法少女っていうのは認めてませんから！　お兄さん、違いますからね！？」
line = "「魔法少女っていうのは認めてませんから！　お兄さん、違いますからね！？」"

[[dialogue]]
speaker = "サチ"
# 「トレジアンナさんの趣味で、勝手にそう言ってるだけですから！」
line = "「トレジアンナさんの趣味で、勝手にそう言ってるだけですから！」"

[[dialogue]]
speaker = "トレジアンナ"
# 「え～、魔法少女、可愛いじゃないですか～。サチさんの戦闘服も、それっぽいですし～☆」
line = "「え～、魔法少女、可愛いじゃないですか～。サチさんの戦闘服も、それっぽいですし～☆」"

[[dialogue]]
speaker = "マトイ"
# 「言われてみれば、確かに……！」
line = "「言われてみれば、確かに……！」"

[[dialogue]]
speaker = "unk"
# 違和感なかった
line = "違和感なかった"

[[dialogue]]
speaker = "トレジアンナ"
# 「ですよね！　ですよね～♪」
line = "「ですよね！　ですよね～♪」"

[[dialogue]]
speaker = "サチ"
# 「うぅ……好きであの戦闘服なわけじゃないんですが……」
line = "「うぅ……好きであの戦闘服なわけじゃないんですが……」"

[[dialogue]]
speaker = "マトイ"
# 「でも、トマルや記憶を失う前の会長は知ってたみたいだけど、サチちゃん達が危険なロストアイテムを回収してたなら、もっと早く教えてくれればよかったのに」
line = "「でも、トマルや記憶を失う前の会長は知ってたみたいだけど、サチちゃん達が危険なロストアイテムを回収してたなら、もっと早く教えてくれればよかったのに」"

[[dialogue]]
speaker = "マトイ"
# 「知ってたら、私も協力してたよ？」
line = "「知ってたら、私も協力してたよ？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「そこはごめんなさ～い。私からサチさん達に、あまりロストアイテムの存在を広めないようにお願いしてたんですよ～」
line = "「そこはごめんなさ～い。私からサチさん達に、あまりロストアイテムの存在を広めないようにお願いしてたんですよ～」"

[[dialogue]]
speaker = "トレジアンナ"
# 「残念ながら、世の中は良い人ばかりではありませんから。悪い人の手に渡れば、ロストアイテムは本当に世界を滅ぼす兵器にもなりえます」
line = "「残念ながら、世の中は良い人ばかりではありませんから。悪い人の手に渡れば、ロストアイテムは本当に世界を滅ぼす兵器にもなりえます」"

[[dialogue]]
speaker = "マトイ"
# 「なるほどねぇ……それはそうかも」
line = "「なるほどねぇ……それはそうかも」"

[[dialogue]]
speaker = "サチ"
# 「それで、今回の『記憶のロストアイテム』についてですが――」
line = "「それで、今回の『記憶のロストアイテム』についてですが――」"

[[dialogue]]
speaker = "サチ"
# 「あの本はもうお分かりの通り、人の記憶を奪う力を持っています。放置しておくことはできません」
line = "「あの本はもうお分かりの通り、人の記憶を奪う力を持っています。放置しておくことはできません」"

[[dialogue]]
speaker = "サチ"
# 「ただ情けない話ですが、見ての通り苦戦していて……お兄さんとマトイ先輩にも協力してほしいんですが……お願いできませんか？」
line = "「ただ情けない話ですが、見ての通り苦戦していて……お兄さんとマトイ先輩にも協力してほしいんですが……お願いできませんか？」"

[[dialogue]]
speaker = "unk"
# もちろん協力するよ
line = "もちろん協力するよ"

[[dialogue]]
speaker = "マトイ"
# 「２人の記憶を取り戻さないといけないし、後輩の頼みなら力を貸さないとね」
line = "「２人の記憶を取り戻さないといけないし、後輩の頼みなら力を貸さないとね」"

[[dialogue]]
speaker = "サチ"
# 「ありがとうございます」
line = "「ありがとうございます」"

[[dialogue]]
speaker = "トレジアンナ"
# 「それじゃあ、皆で魔法少女活動、再開しましょ～！　お～☆」
line = "「それじゃあ、皆で魔法少女活動、再開しましょ～！　お～☆」"

[[dialogue]]
speaker = "トマル"
# 「お～！」
line = "「お～！」"

[[dialogue]]
speaker = "サチ"
# 「おー！　……って、魔法少女じゃないですからっ！」
line = "「おー！　……って、魔法少女じゃないですからっ！」"

[[dialogue]]
speaker = "トレジアンナ"
# 「え～、サチさんのいけず～」
line = "「え～、サチさんのいけず～」"

[[dialogue]]
speaker = "unk"
# こうして、サチ達のロストアイテム回収を手伝うことになったのだった。
line = "こうして、サチ達のロストアイテム回収を手伝うことになったのだった。"
