[[dialogue]]
speaker = "unk"
# ロストアイテム捜索パーティの分断……そのきっかけは、ほんの些細なことだった。
line = "ロストアイテム捜索パーティの分断……そのきっかけは、ほんの些細なことだった。"

[[dialogue]]
speaker = "unk"
# プリムラがサチと口喧嘩して、そのままお互いにヒートアップしてしまい━━
line = "プリムラがサチと口喧嘩して、そのままお互いにヒートアップしてしまい━━"

[[dialogue]]
speaker = "プリムラ"
# 「――ふん。サチがこんな体たらくではやってられん」
line = "「――ふん。サチがこんな体たらくではやってられん」"

[[dialogue]]
speaker = "プリムラ"
# 「我は別行動させてもらうぞ」
line = "「我は別行動させてもらうぞ」"

[[dialogue]]
speaker = "unk"
# そう言って１人、違う場所へ向かおうとする。
line = "そう言って１人、違う場所へ向かおうとする。"

[[dialogue]]
speaker = "unk"
# それを放っておけず、サチの方はトマルに任せて、マトイと一緒にプリムラの後を追いかけることにした――
line = "それを放っておけず、サチの方はトマルに任せて、マトイと一緒にプリムラの後を追いかけることにした――"

[[dialogue]]
speaker = "プリムラ"
# 「全く、別に我１人でも困らんのに、わざわざ追いかけてくるとは……お節介な眷族じゃ」
line = "「全く、別に我１人でも困らんのに、わざわざ追いかけてくるとは……お節介な眷族じゃ」"

[[dialogue]]
speaker = "unk"
# 聞きたいことがあったから
line = "聞きたいことがあったから"

[[dialogue]]
speaker = "プリムラ"
# 「ふん。あいにく我は今、機嫌が悪いのじゃ。喧嘩の仲裁とかぬかすのであれば、なにも答えてやらぬぞ」
line = "「ふん。あいにく我は今、機嫌が悪いのじゃ。喧嘩の仲裁とかぬかすのであれば、なにも答えてやらぬぞ」"

[[dialogue]]
speaker = "プリムラ"
# 「――なぬ？　記憶喪失だから、サチと我がそもそもどういう関係なのか、よくわかってないじゃと？」
line = "「――なぬ？　記憶喪失だから、サチと我がそもそもどういう関係なのか、よくわかってないじゃと？」"

[[dialogue]]
speaker = "プリムラ"
# 「はぁ……そうじゃったな。まあよい。貴様が記憶を失ったのは、一部我のせいでもある」
line = "「はぁ……そうじゃったな。まあよい。貴様が記憶を失ったのは、一部我のせいでもある」"

[[dialogue]]
speaker = "プリムラ"
# 「……我がもともと賢者の石というロストアイテムであることは、もう話したじゃろう？」
line = "「……我がもともと賢者の石というロストアイテムであることは、もう話したじゃろう？」"

[[dialogue]]
speaker = "プリムラ"
# 「我の真の名は、何者かが賢者の石を使って作り出した終末兵器『メルクリウス』という」
line = "「我の真の名は、何者かが賢者の石を使って作り出した終末兵器『メルクリウス』という」"

[[dialogue]]
speaker = "プリムラ"
# 「言っておくが、我が悪の終末兵器だというのは自称ではない。今から約１年前、我は何者かによって流星市国に投入された」
line = "「言っておくが、我が悪の終末兵器だというのは自称ではない。今から約１年前、我は何者かによって流星市国に投入された」"

[[dialogue]]
speaker = "プリムラ"
# 「その目的は、流星市国を中心にリクリエを引き起こす為じゃ」
line = "「その目的は、流星市国を中心にリクリエを引き起こす為じゃ」"

[[dialogue]]
speaker = "マトイ"
# 「ま、待って待って！　人為的にリクリエを起こそうとしたやつがいるってこと！？　それって一体、誰なの！？」
line = "「ま、待って待って！　人為的にリクリエを起こそうとしたやつがいるってこと！？　それって一体、誰なの！？」"

[[dialogue]]
speaker = "プリムラ"
# 「我にもわからん！」
line = "「我にもわからん！」"

[[dialogue]]
speaker = "マトイ"
# 「わからん、って……！」
line = "「わからん、って……！」"

[[dialogue]]
speaker = "プリムラ"
# 「何者かから、世界を滅ぼすように命令を受けて目覚めたのは確かじゃが、その者に関する情報は、我の中にも全く存在しないのじゃ」
line = "「何者かから、世界を滅ぼすように命令を受けて目覚めたのは確かじゃが、その者に関する情報は、我の中にも全く存在しないのじゃ」"

[[dialogue]]
speaker = "マトイ"
# 「それって……その何者かが自分の正体を隠そうとしたってこと？」
line = "「それって……その何者かが自分の正体を隠そうとしたってこと？」"

[[dialogue]]
speaker = "プリムラ"
# 「おそらくはな」
line = "「おそらくはな」"

[[dialogue]]
speaker = "マトイ"
# 「で、でも、プリムラちゃんが本当に終末兵器なら、なんでニュースになったりしてないの？　なにか大事件になっててもおかしくないよね？」
line = "「で、でも、プリムラちゃんが本当に終末兵器なら、なんでニュースになったりしてないの？　なにか大事件になっててもおかしくないよね？」"

[[dialogue]]
speaker = "プリムラ"
# 「我が投入された直後、活動を開始しようとしたその瞬間に、最悪な相手と遭遇したからじゃ」
line = "「我が投入された直後、活動を開始しようとしたその瞬間に、最悪な相手と遭遇したからじゃ」"

[[dialogue]]
speaker = "unk"
# それって、もしかして……？
line = "それって、もしかして……？"

[[dialogue]]
speaker = "プリムラ"
# 「そう、サチのやつじゃ。運の悪いことに、我が目覚めたその時、すぐ近くで、あやつは別のロストアイテムを回収し終わった直後じゃった」
line = "「そう、サチのやつじゃ。運の悪いことに、我が目覚めたその時、すぐ近くで、あやつは別のロストアイテムを回収し終わった直後じゃった」"

[[dialogue]]
speaker = "プリムラ"
# 「そして、これまた不運にも、トレジアンナが人払いの星術を使っていた為、我の存在は誰に知られることもなく、サチと出会って、戦い――」
line = "「そして、これまた不運にも、トレジアンナが人払いの星術を使っていた為、我の存在は誰に知られることもなく、サチと出会って、戦い――」"

[[dialogue]]
speaker = "プリムラ"
# 「運勢最悪なことに、サチが回収したばかりのロストアイテムによって、力の大部分を封印されて、敗れ去ったのじゃ」
line = "「運勢最悪なことに、サチが回収したばかりのロストアイテムによって、力の大部分を封印されて、敗れ去ったのじゃ」"

[[dialogue]]
speaker = "プリムラ"
# 「その後はあの馬鹿、何を思ったか我を生かして更生させるとか言い出して……今に至るというわけじゃ」
line = "「その後はあの馬鹿、何を思ったか我を生かして更生させるとか言い出して……今に至るというわけじゃ」"

[[dialogue]]
speaker = "unk"
# なんとなく、２人の関係はわかったよ
line = "なんとなく、２人の関係はわかったよ"

[[dialogue]]
speaker = "プリムラ"
# 「つまり、我とサチはもともと敵同士だったというわけじゃ。因縁の相手……別に喧嘩してもおかしくはなかろう？」
line = "「つまり、我とサチはもともと敵同士だったというわけじゃ。因縁の相手……別に喧嘩してもおかしくはなかろう？」"

[[dialogue]]
speaker = "プリムラ"
# 「――なんじゃ、眷族よ。まだ納得のいってなさそうな顔じゃな？」
line = "「――なんじゃ、眷族よ。まだ納得のいってなさそうな顔じゃな？」"

[[dialogue]]
speaker = "unk"
# 今のプリムラは、サチに何か怒ってるよね？
line = "今のプリムラは、サチに何か怒ってるよね？"

[[dialogue]]
speaker = "プリムラ"
# 「……だったら、なんだと言うんじゃ？　なにに対して怒っているか知りたいとでも？」
line = "「……だったら、なんだと言うんじゃ？　なにに対して怒っているか知りたいとでも？」"

[[dialogue]]
speaker = "プリムラ"
# 「我は言う気はないぞ。たとえ眷族……貴様であってもじゃ」
line = "「我は言う気はないぞ。たとえ眷族……貴様であってもじゃ」"

[[dialogue]]
speaker = "プリムラ"
# 「第一、別に言わなくとも、ロストアイテムを回収し、その能力を解除すれば、サチも貴様も忘れている記憶を取り戻す」
line = "「第一、別に言わなくとも、ロストアイテムを回収し、その能力を解除すれば、サチも貴様も忘れている記憶を取り戻す」"

[[dialogue]]
speaker = "プリムラ"
# 「そうすれば、我がわざわざ口にする必要はない。違うか？　眷族よ」
line = "「そうすれば、我がわざわざ口にする必要はない。違うか？　眷族よ」"

[[dialogue]]
speaker = "マトイ"
# 「会長、ちょっと……」
line = "「会長、ちょっと……」"

[[dialogue]]
speaker = "unk"
# そこでマトイが、耳打ちしてくる。
line = "そこでマトイが、耳打ちしてくる。"

[[dialogue]]
speaker = "マトイ"
# 「プリムラちゃんとサチちゃんを仲直りさせる為にも、トマルが教えてくれた秘策を使うべきじゃない？」
line = "「プリムラちゃんとサチちゃんを仲直りさせる為にも、トマルが教えてくれた秘策を使うべきじゃない？」"

[[dialogue]]
speaker = "unk"
# （試しにやってみるか……）
line = "（試しにやってみるか……）"

[[dialogue]]
speaker = "プリムラ"
# 「なんじゃ、まだなにか言うことがあるのか、眷族よ？　なんと言われようとも、我は――」
line = "「なんじゃ、まだなにか言うことがあるのか、眷族よ？　なんと言われようとも、我は――」"

[[dialogue]]
speaker = "プリムラ"
# 「って、いきなり我の手を取ったりして……なんじゃ？」
line = "「って、いきなり我の手を取ったりして……なんじゃ？」"

[[dialogue]]
speaker = "プリムラ"
# 「――いま、気づいたじゃと？　一体何に……」
line = "「――いま、気づいたじゃと？　一体何に……」"

[[dialogue]]
speaker = "unk"
# プリムラって……すごく可愛いよね！
line = "プリムラって……すごく可愛いよね！"

[[dialogue]]
speaker = "プリムラ"
# 「ファッ！？」
line = "「ファッ！？」"

[[dialogue]]
speaker = "unk"
# プリムラを異性として見るなら、すごく美少女だと思う。小さくて可愛いし、金色の髪も褐色の肌も宝石のようだ。なにより――
line = "プリムラを異性として見るなら、すごく美少女だと思う。小さくて可愛いし、金色の髪も褐色の肌も宝石のようだ。なにより――"

[[dialogue]]
speaker = "unk"
# 今こうして、サチに怒りつつも、サチの記憶を取り戻す為にロストアイテムを回収しようと奔走していることが、頭を撫でたくなるくらい可愛いと思う。
line = "今こうして、サチに怒りつつも、サチの記憶を取り戻す為にロストアイテムを回収しようと奔走していることが、頭を撫でたくなるくらい可愛いと思う。"

[[dialogue]]
speaker = "unk"
# そんな風に、プリムラを褒めまくる。
line = "そんな風に、プリムラを褒めまくる。"

[[dialogue]]
speaker = "プリムラ"
# 「な、撫でたくなるっていうか……もう既に我の頭を撫でているではないか！　ええい、気安く我の頭を撫でるでない！」
line = "「な、撫でたくなるっていうか……もう既に我の頭を撫でているではないか！　ええい、気安く我の頭を撫でるでない！」"

[[dialogue]]
speaker = "プリムラ"
# 「それに可愛いとか、馬鹿にしておるのか、貴様！？　我は悪の終末兵器なのじゃぞ！？」
line = "「それに可愛いとか、馬鹿にしておるのか、貴様！？　我は悪の終末兵器なのじゃぞ！？」"

[[dialogue]]
speaker = "プリムラ"
# 「そんな安い褒め言葉で我が喜ぶとでも！？　フ……フヘへへ♪」
line = "「そんな安い褒め言葉で我が喜ぶとでも！？　フ……フヘへへ♪」"

[[dialogue]]
speaker = "unk"
# （き、効いてるーーーっ！？）
line = "（き、効いてるーーーっ！？）"

[[dialogue]]
speaker = "マトイ"
# （ちょ、チョロい……！　トマルの言ってた通り、誰かに騙されないか不安になるレベルで、褒め言葉に弱い……！）
line = "（ちょ、チョロい……！　トマルの言ってた通り、誰かに騙されないか不安になるレベルで、褒め言葉に弱い……！）"

[[dialogue]]
speaker = "プリムラ"
# 「頭をそんな撫でたら髪が乱れるじゃろうが、さっさと手を退けんか馬鹿者め！　フヘへへ……♪」
line = "「頭をそんな撫でたら髪が乱れるじゃろうが、さっさと手を退けんか馬鹿者め！　フヘへへ……♪」"

[[dialogue]]
speaker = "マトイ"
# （と言いつつ、もっと撫でろという顔をしている……！）
line = "（と言いつつ、もっと撫でろという顔をしている……！）"

[[dialogue]]
speaker = "マトイ"
# （会長、プリムラちゃんから聞き出すなら、デレデレしてる今がチャンスだよっ！）
line = "（会長、プリムラちゃんから聞き出すなら、デレデレしてる今がチャンスだよっ！）"

[[dialogue]]
speaker = "unk"
# マトイから目配せをされて、少し考える。
line = "マトイから目配せをされて、少し考える。"

[[dialogue]]
speaker = "unk"
# プリムラは素直じゃないし、自分のことを悪だと言う。だけど……さっき褒めた言葉は嘘じゃない。
line = "プリムラは素直じゃないし、自分のことを悪だと言う。だけど……さっき褒めた言葉は嘘じゃない。"

[[dialogue]]
speaker = "プリムラ"
# 「――なぬ？　我にお願いごとがあるじゃと？」
line = "「――なぬ？　我にお願いごとがあるじゃと？」"

[[dialogue]]
speaker = "プリムラ"
# 「し、仕方がないのう……眷族の頼みなら、聞いてやらないこともないぞ？　一体何じゃ？」
line = "「し、仕方がないのう……眷族の頼みなら、聞いてやらないこともないぞ？　一体何じゃ？」"

[[dialogue]]
speaker = "unk"
# 素直に言えないことってあると思う。でも――
line = "素直に言えないことってあると思う。でも――"

[[dialogue]]
speaker = "unk"
# 素直に言わなきゃ伝わらないこともあって……勇気を出して伝えなきゃいけない時もあるんだって、覚えておいて欲しい。
line = "素直に言わなきゃ伝わらないこともあって……勇気を出して伝えなきゃいけない時もあるんだって、覚えておいて欲しい。"

[[dialogue]]
speaker = "プリムラ"
# 「……ふん」
line = "「……ふん」"

[[dialogue]]
speaker = "プリムラ"
# 「我が眷族の忠告なら、仕方がない。一応……覚えておくのじゃ」
line = "「我が眷族の忠告なら、仕方がない。一応……覚えておくのじゃ」"

[[dialogue]]
speaker = "unk"
# そう言って、唇を尖らせるプリムラを見て――
line = "そう言って、唇を尖らせるプリムラを見て――"

[[dialogue]]
speaker = "unk"
# 本当は、怒っているんじゃなくて、拗ねているのかもしれない……なんだかそんな風に感じたのだった。
line = "本当は、怒っているんじゃなくて、拗ねているのかもしれない……なんだかそんな風に感じたのだった。"
