[[dialogue]]
speaker = "unk"
# 合宿は５日目。
line = "合宿は５日目。"

[[dialogue]]
speaker = "unk"
# 今日は午前中から、水着フォームを使いこなす為の訓練を続けていた。
line = "今日は午前中から、水着フォームを使いこなす為の訓練を続けていた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「よし、今日は水着フォームの機動力アップの訓練も兼ねて、遠泳をやるわよ！」
line = "「よし、今日は水着フォームの機動力アップの訓練も兼ねて、遠泳をやるわよ！」"

[[dialogue]]
speaker = "マトイ"
# 「遠泳って言ったって、どこまで泳ぐ気なの？　そもそもリゾート結界って、どれくらいの広さなのか分からないし……」
line = "「遠泳って言ったって、どこまで泳ぐ気なの？　そもそもリゾート結界って、どれくらいの広さなのか分からないし……」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふっ、実はこの結界の端っこまで行くと、島の反対側にループするようになっているのよ～」
line = "「ふふっ、実はこの結界の端っこまで行くと、島の反対側にループするようになっているのよ～」"

[[dialogue]]
speaker = "マトイ"
# 「まさかのゲームのワールドマップみたいな！？　というか、サーシャさん調べたんですか！？」
line = "「まさかのゲームのワールドマップみたいな！？　というか、サーシャさん調べたんですか！？」"

[[dialogue]]
speaker = "サーシャ"
# 「だって端っこがどうなってるかとか、気になるじゃない？　ちなみに空は限界高度まで行くと、強制的に押し戻される感じね～」
line = "「だって端っこがどうなってるかとか、気になるじゃない？　ちなみに空は限界高度まで行くと、強制的に押し戻される感じね～」"

[[dialogue]]
speaker = "アナ"
# 「なるほど。ということは前会長、遠泳は結界の端っこまで行ってループし、島の反対側まで泳いで戻るといった感じでしょうか？」
line = "「なるほど。ということは前会長、遠泳は結界の端っこまで行ってループし、島の反対側まで泳いで戻るといった感じでしょうか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そういうことよ！　じゃあ、早速全員でスタート……って、あら？」
line = "「そういうことよ！　じゃあ、早速全員でスタート……って、あら？」"

[[dialogue]]
speaker = "アナ"
# 「どうしました？」
line = "「どうしました？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そういえばさっきから、フィオナの姿が見当たらないような……」
line = "「そういえばさっきから、フィオナの姿が見当たらないような……」"

[[dialogue]]
speaker = "マトイ"
# 「ちょっと前に、１人で海の家の方へ向かっていったような……？」
line = "「ちょっと前に、１人で海の家の方へ向かっていったような……？」"

[[dialogue]]
speaker = "unk"
# 俺、ちょっと様子を見て来るよ
line = "俺、ちょっと様子を見て来るよ"

[[dialogue]]
speaker = "リップル"
# 「ふんふん、ふふ～ん♪　……うん、今日も凄く調子がイイで～す♪　海の家の外装も素敵にナッテきました～」
line = "「ふんふん、ふふ～ん♪　……うん、今日も凄く調子がイイで～す♪　海の家の外装も素敵にナッテきました～」"

[[dialogue]]
speaker = "フィオナ"
# 「リップルさん、結界作りご苦労様です」
line = "「リップルさん、結界作りご苦労様です」"

[[dialogue]]
speaker = "リップル"
# 「あれ？　フィオナ、１人でドウしました？　今日は皆、水着フォームの訓練するって言ってマセンでしたか？」
line = "「あれ？　フィオナ、１人でドウしました？　今日は皆、水着フォームの訓練するって言ってマセンでしたか？」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ。ただ、今日はちょっと気分的に、リップルさんの仕事のお手伝いが出来たらなと思いまして」
line = "「ええ。ただ、今日はちょっと気分的に、リップルさんの仕事のお手伝いが出来たらなと思いまして」"

[[dialogue]]
speaker = "リップル"
# 「アハハ、仕事なんてオオゲサで～す！　ワタシの結界作りはスキでやってることデスから。仕事というより、趣味デスね！」
line = "「アハハ、仕事なんてオオゲサで～す！　ワタシの結界作りはスキでやってることデスから。仕事というより、趣味デスね！」"

[[dialogue]]
speaker = "フィオナ"
# 「趣味……」
line = "「趣味……」"

[[dialogue]]
speaker = "リップル"
# 「それにワタシのせいで皆を巻き込んじゃったワケですし、今は順調なので、手伝いとか気にしなくてもダイジョウブです！」
line = "「それにワタシのせいで皆を巻き込んじゃったワケですし、今は順調なので、手伝いとか気にしなくてもダイジョウブです！」"

[[dialogue]]
speaker = "リップル"
# 「せっかくの夏なのデスから、皆と思う存分、海を楽しんでクダさい！」
line = "「せっかくの夏なのデスから、皆と思う存分、海を楽しんでクダさい！」"

[[dialogue]]
speaker = "フィオナ"
# 「……そうですか。分かりました」
line = "「……そうですか。分かりました」"

[[dialogue]]
speaker = "リップル"
# 「じゃあワタシは、温泉の方も作り直して来ま～す！　後で入るのを楽しみにしててクダさい♪」
line = "「じゃあワタシは、温泉の方も作り直して来ま～す！　後で入るのを楽しみにしててクダさい♪」"

[[dialogue]]
speaker = "フィオナ"
# 「はぁ……」
line = "「はぁ……」"

[[dialogue]]
speaker = "unk"
# フィオナ、何か悩み事？
line = "フィオナ、何か悩み事？"

[[dialogue]]
speaker = "フィオナ"
# 「あ……！　緋宮会長……？」
line = "「あ……！　緋宮会長……？」"

[[dialogue]]
speaker = "フィオナ"
# 「――私の様子を見に？　すみません、気を遣わせてしまって……」
line = "「――私の様子を見に？　すみません、気を遣わせてしまって……」"

[[dialogue]]
speaker = "フィオナ"
# 「悩みなら相談に乗る？　その……悩みと言っても、リップルさんの壮大な野望に比べれば、とても些細なものなのですが――」
line = "「悩みなら相談に乗る？　その……悩みと言っても、リップルさんの壮大な野望に比べれば、とても些細なものなのですが――」"

[[dialogue]]
speaker = "unk"
# フィオナと海に戻ると、皆が離れたところで泳いでいるのが見えた。
line = "フィオナと海に戻ると、皆が離れたところで泳いでいるのが見えた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あはは！　皆、私に付いて来なさい！」
line = "「あはは！　皆、私に付いて来なさい！」"

[[dialogue]]
speaker = "マトイ"
# 「ちょっ、ヴィーナス泳ぐの速過ぎ！　というか、バタフライで軽く宙に浮いてない！？」
line = "「ちょっ、ヴィーナス泳ぐの速過ぎ！　というか、バタフライで軽く宙に浮いてない！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私は海でも自由に飛んでみせるわ！」
line = "「私は海でも自由に飛んでみせるわ！」"

[[dialogue]]
speaker = "サーシャ"
# 「あ～ん♪　マトイちゃん助けて～！　タコと遊んでたら、触手が絡みついちゃったの～」
line = "「あ～ん♪　マトイちゃん助けて～！　タコと遊んでたら、触手が絡みついちゃったの～」"

[[dialogue]]
speaker = "マトイ"
# 「何かエッチなことになってる！？　ああもう、サーシャさんがタコに触ったりしたら、そうなるに決まってるじゃないですか！」
line = "「何かエッチなことになってる！？　ああもう、サーシャさんがタコに触ったりしたら、そうなるに決まってるじゃないですか！」"

[[dialogue]]
speaker = "サーシャ"
# 「酷いわ～」
line = "「酷いわ～」"

[[dialogue]]
speaker = "アナ"
# 「取ったど～」
line = "「取ったど～」"

[[dialogue]]
speaker = "マトイ"
# 「アナに至っては魚取ってるし！」
line = "「アナに至っては魚取ってるし！」"

[[dialogue]]
speaker = "フィオナ"
# 「皆さん、楽しそうに訓練をしてらっしゃいますね」
line = "「皆さん、楽しそうに訓練をしてらっしゃいますね」"

[[dialogue]]
speaker = "unk"
# 半分水遊びみたいな感じだけどね
line = "半分水遊びみたいな感じだけどね"

[[dialogue]]
speaker = "フィオナ"
# 「私も、皆さんのように楽しめたらと思うのですが……」
line = "「私も、皆さんのように楽しめたらと思うのですが……」"

[[dialogue]]
speaker = "フィオナ"
# 「私はいざ遊ぼうと考えると、何をどうするのが正しいのか、よく分からなくて……」
line = "「私はいざ遊ぼうと考えると、何をどうするのが正しいのか、よく分からなくて……」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長は、私が今回の合宿に参加した理由って、ヴィーナスさんから詳しく聞いてますか？」
line = "「緋宮会長は、私が今回の合宿に参加した理由って、ヴィーナスさんから詳しく聞いてますか？」"

[[dialogue]]
speaker = "unk"
# いや、特別参加することになったってだけ
line = "いや、特別参加することになったってだけ"

[[dialogue]]
speaker = "フィオナ"
# 「私、実は流星学園の星徒会の皆から、仕事禁止を言い渡されてしまったんです」
line = "「私、実は流星学園の星徒会の皆から、仕事禁止を言い渡されてしまったんです」"

[[dialogue]]
speaker = "フィオナ"
# 「先日、学園の近くに巨大なアステライトが発生したことはご存知ですよね？」
line = "「先日、学園の近くに巨大なアステライトが発生したことはご存知ですよね？」"

[[dialogue]]
speaker = "フィオナ"
# 「――そう、流星学園の星徒会の方で対処させて頂いた案件です。その巨大さ故に、攻略が難航してしまって……」
line = "「――そう、流星学園の星徒会の方で対処させて頂いた案件です。その巨大さ故に、攻略が難航してしまって……」"

[[dialogue]]
speaker = "フィオナ"
# 「早急な排除を優先する為、星徒会の皆にモンスターの大軍を抑えてもらっている間に、私が単独でボスモンスターに挑むことになりました」
line = "「早急な排除を優先する為、星徒会の皆にモンスターの大軍を抑えてもらっている間に、私が単独でボスモンスターに挑むことになりました」"

[[dialogue]]
speaker = "フィオナ"
# 「苦戦を強いられましたが、全力で戦い、アステラの攻略には何とか成功しました。ですが……」
line = "「苦戦を強いられましたが、全力で戦い、アステラの攻略には何とか成功しました。ですが……」"

[[dialogue]]
speaker = "フィオナ"
# 「そのせいで、ニャリオンをかなり疲弊させてしまって。回復の為に、しばらく休眠状態に入ることになってしまったんです」
line = "「そのせいで、ニャリオンをかなり疲弊させてしまって。回復の為に、しばらく休眠状態に入ることになってしまったんです」"

[[dialogue]]
speaker = "unk"
# 合宿中に見かけなかったのはそういう理由か
line = "合宿中に見かけなかったのはそういう理由か"

[[dialogue]]
speaker = "フィオナ"
# 「はい、今も眠っています。ですので、全力で戦うことは出来ませんから、しばらく戦闘は任せろと皆から言われてしまって……」
line = "「はい、今も眠っています。ですので、全力で戦うことは出来ませんから、しばらく戦闘は任せろと皆から言われてしまって……」"

[[dialogue]]
speaker = "フィオナ"
# 「ならばその代わりに星徒会の事務作業は私がしようと、率先して引き受けていたんですが……」
line = "「ならばその代わりに星徒会の事務作業は私がしようと、率先して引き受けていたんですが……」"

[[dialogue]]
speaker = "フィオナ"
# 「そうしたら今度は、ちゃんと休めと仕事を取り上げられてしまいまして……」
line = "「そうしたら今度は、ちゃんと休めと仕事を取り上げられてしまいまして……」"

[[dialogue]]
speaker = "フィオナ"
# 「ニャリオンに相談することもできず困っていたら、セーラさんからこの合宿へ参加するようにと言われたんです」
line = "「ニャリオンに相談することもできず困っていたら、セーラさんからこの合宿へ参加するようにと言われたんです」"

[[dialogue]]
speaker = "フィオナ"
# 「休暇をちゃんと楽しんで来い、と。どこからかこの合宿の話を聞きつけて、ヴィーナスさんに私を参加させて欲しいとお願いしたみたいです」
line = "「休暇をちゃんと楽しんで来い、と。どこからかこの合宿の話を聞きつけて、ヴィーナスさんに私を参加させて欲しいとお願いしたみたいです」"

[[dialogue]]
speaker = "フィオナ"
# 「ただ、私は休暇と言われても……お恥ずかしい話ですが、どう楽しんだらいいのかも悩んでしまうくらい、遊ぶことに関して疎いというか……」
line = "「ただ、私は休暇と言われても……お恥ずかしい話ですが、どう楽しんだらいいのかも悩んでしまうくらい、遊ぶことに関して疎いというか……」"

[[dialogue]]
speaker = "フィオナ"
# 「何をどうするのが正しい休み方なのか、分からなくて考えてしまうんです……」
line = "「何をどうするのが正しい休み方なのか、分からなくて考えてしまうんです……」"

[[dialogue]]
speaker = "フィオナ"
# 「――真面目？　そうですね……悪い意味で真面目なんだと思います。仕事を取られてもなお、何かするべきことを探さないと、落ち着かなくって……」
line = "「――真面目？　そうですね……悪い意味で真面目なんだと思います。仕事を取られてもなお、何かするべきことを探さないと、落ち着かなくって……」"

[[dialogue]]
speaker = "unk"
# それなら何か、新しいことを始めてみたら？
line = "それなら何か、新しいことを始めてみたら？"

[[dialogue]]
speaker = "フィオナ"
# 「新しいこと……ですか？」
line = "「新しいこと……ですか？」"

[[dialogue]]
speaker = "unk"
# 休むといっても、考え方は人それぞれ。水遊びも捉え方次第だ。
line = "休むといっても、考え方は人それぞれ。水遊びも捉え方次第だ。"

[[dialogue]]
speaker = "unk"
# 遊びとしてじゃなく人生勉強だと捉えて、これまでして来なかった新しいことを試してみるのはどうかな、とフィオナに提案した。
line = "遊びとしてじゃなく人生勉強だと捉えて、これまでして来なかった新しいことを試してみるのはどうかな、とフィオナに提案した。"

[[dialogue]]
speaker = "フィオナ"
# 「でも、一体何をすれば……」
line = "「でも、一体何をすれば……」"

[[dialogue]]
speaker = "リップル"
# 「フィオナ！　でしたら、サーフィンをやってみまセンか！？」
line = "「フィオナ！　でしたら、サーフィンをやってみまセンか！？」"

[[dialogue]]
speaker = "フィオナ"
# 「リップルさん？　いつの間に――」
line = "「リップルさん？　いつの間に――」"

[[dialogue]]
speaker = "リップル"
# 「フィオナの様子が何かヘンだなと感じて、追いかけてキテしまいました！」
line = "「フィオナの様子が何かヘンだなと感じて、追いかけてキテしまいました！」"

[[dialogue]]
speaker = "リップル"
# 「新しいことをしたいなら、ワタシはサーフィンをオススメです！　サーフィンの趣味ナカマを見つけるのは、ワタシのやりたいことでもアリます！」
line = "「新しいことをしたいなら、ワタシはサーフィンをオススメです！　サーフィンの趣味ナカマを見つけるのは、ワタシのやりたいことでもアリます！」"

[[dialogue]]
speaker = "リップル"
# 「だから、フィオナさえ嫌じゃなければ、是非ワタシと一緒にサーフィンをやりませんか！？」
line = "「だから、フィオナさえ嫌じゃなければ、是非ワタシと一緒にサーフィンをやりませんか！？」"

[[dialogue]]
speaker = "unk"
# 試してみてもいいんじゃないかな？
line = "試してみてもいいんじゃないかな？"

[[dialogue]]
speaker = "フィオナ"
# 「サーフィン……でも、それだと訓練関係なく、ただの遊びに……」
line = "「サーフィン……でも、それだと訓練関係なく、ただの遊びに……」"

[[dialogue]]
speaker = "リップル"
# 「時には気分転換も必要、デスよ！　フィオナ！」
line = "「時には気分転換も必要、デスよ！　フィオナ！」"

[[dialogue]]
speaker = "フィオナ"
# 「……！　それは緋宮会長が言っていた……」
line = "「……！　それは緋宮会長が言っていた……」"

[[dialogue]]
speaker = "フィオナ"
# 「――分かりました。リップルさん、お願いしてもいいですか？」
line = "「――分かりました。リップルさん、お願いしてもいいですか？」"

[[dialogue]]
speaker = "リップル"
# 「ハイ♪　新しい趣味、タメしてみましょう！」
line = "「ハイ♪　新しい趣味、タメしてみましょう！」"

[[dialogue]]
speaker = "unk"
# そうして、フィオナはサーフィン体験をしてみることになったのだった。
line = "そうして、フィオナはサーフィン体験をしてみることになったのだった。"
