[[dialogue]]
speaker = "unk"
# 新たな水着フォームの力を駆使して、俺達は結界内のアステライト攻略に成功。
line = "新たな水着フォームの力を駆使して、俺達は結界内のアステライト攻略に成功。"

[[dialogue]]
speaker = "unk"
# 結界の歪みは修正され、俺達は無事、現実世界へ帰還した。
line = "結界の歪みは修正され、俺達は無事、現実世界へ帰還した。"

[[dialogue]]
speaker = "unk"
# そして、現在――
line = "そして、現在――"

[[dialogue]]
speaker = "マトイ"
# 「それにしても驚いたよ。一体何者なのかとは思ってたけど……まさか、リップルが古代天使の生き残りだなんて……！」
line = "「それにしても驚いたよ。一体何者なのかとは思ってたけど……まさか、リップルが古代天使の生き残りだなんて……！」"

[[dialogue]]
speaker = "アナ"
# 「学園でリップルさんの体を調べてもらったら、現代の天使にはない特徴が色々と見つかったんだとか。興味深いです」
line = "「学園でリップルさんの体を調べてもらったら、現代の天使にはない特徴が色々と見つかったんだとか。興味深いです」"

[[dialogue]]
speaker = "サーシャ"
# 天使の翼とか、珍しい色をしてるなって思ってたのよね～」
line = "天使の翼とか、珍しい色をしてるなって思ってたのよね～」"

[[dialogue]]
speaker = "フィオナ"
# 「３０００年前、リクリエの力を削ぐ為に自らを犠牲にして封印結界を使ったという、古代天使のことを記した石板があったんです」
line = "「３０００年前、リクリエの力を削ぐ為に自らを犠牲にして封印結界を使ったという、古代天使のことを記した石板があったんです」"

[[dialogue]]
speaker = "フィオナ"
# 「おそらくそこに書かれた天使というのが……」
line = "「おそらくそこに書かれた天使というのが……」"

[[dialogue]]
speaker = "リップル"
# 「ワタシのお母さんですね！　お母さん……リクリエと戦っていたんデスね」
line = "「ワタシのお母さんですね！　お母さん……リクリエと戦っていたんデスね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「さすがリップルのお母さんね！　誰かの幸せの為に、勇敢に戦ったんだわ」
line = "「さすがリップルのお母さんね！　誰かの幸せの為に、勇敢に戦ったんだわ」"

[[dialogue]]
speaker = "リップル"
# 「ハイ……！　そのことをワタシは、誇りにオモいます！」
line = "「ハイ……！　そのことをワタシは、誇りにオモいます！」"

[[dialogue]]
speaker = "リップル"
# 「そしてここが……今、リクリエと戦っている、皆の通うガクエンなんですね！」
line = "「そしてここが……今、リクリエと戦っている、皆の通うガクエンなんですね！」"

[[dialogue]]
speaker = "フィオナ"
# 「はい。新星学園です。隣には、私の通う流星学園があって、その２校で協力してリクリエに立ち向かっています」
line = "「はい。新星学園です。隣には、私の通う流星学園があって、その２校で協力してリクリエに立ち向かっています」"

[[dialogue]]
speaker = "サーシャ"
# 「隣接する大聖堂のカフェテリアには、凄い料理人の子がいて、美味しい焼きそばもあるわよ～♪」
line = "「隣接する大聖堂のカフェテリアには、凄い料理人の子がいて、美味しい焼きそばもあるわよ～♪」"

[[dialogue]]
speaker = "リップル"
# 「あっ、プールはありマスか！？　ワタシ、プールの部活がやりタイです！」
line = "「あっ、プールはありマスか！？　ワタシ、プールの部活がやりタイです！」"

[[dialogue]]
speaker = "マトイ"
# 「それなら水泳部かな？　今度案内するね」
line = "「それなら水泳部かな？　今度案内するね」"

[[dialogue]]
speaker = "リップル"
# 「ワタシ、海の近くで過ごして来ましたし、冬でも結界で夏の海を出せるので、実は１度もプールに入ったことがナクて！」
line = "「ワタシ、海の近くで過ごして来ましたし、冬でも結界で夏の海を出せるので、実は１度もプールに入ったことがナクて！」"

[[dialogue]]
speaker = "アナ"
# 「リップルさん、泳ぐのも速かったですもんね。水泳部の人達、喜びそうです」
line = "「リップルさん、泳ぐのも速かったですもんね。水泳部の人達、喜びそうです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そっか。リップルがいれば、リゾート結界はいつでも行けるのよね！　学園の皆に声をかけたら、大喜びで遊びに来るんじゃないかしら？」
line = "「そっか。リップルがいれば、リゾート結界はいつでも行けるのよね！　学園の皆に声をかけたら、大喜びで遊びに来るんじゃないかしら？」"

[[dialogue]]
speaker = "マトイ"
# 「確かに！　というか、あの海が夏以外でも楽しめるとか、普通に考えて最高じゃない？」
line = "「確かに！　というか、あの海が夏以外でも楽しめるとか、普通に考えて最高じゃない？」"

[[dialogue]]
speaker = "フィオナ"
# 「今度はぜひ、流星学園星徒会の皆も呼びたいです。リップルさん、いいでしょうか？」
line = "「今度はぜひ、流星学園星徒会の皆も呼びたいです。リップルさん、いいでしょうか？」"

[[dialogue]]
speaker = "リップル"
# 「もちろん！　ワタシは皆にハッピーになって欲しくて、リゾート結界を作ったのですから！　どんどんアソビに来てクダさ～い♪」
line = "「もちろん！　ワタシは皆にハッピーになって欲しくて、リゾート結界を作ったのですから！　どんどんアソビに来てクダさ～い♪」"

[[dialogue]]
speaker = "フィオナ"
# 「ありがとうございます。ふふっ、また私もサーフィンがしたいです♪」
line = "「ありがとうございます。ふふっ、また私もサーフィンがしたいです♪」"

[[dialogue]]
speaker = "リップル"
# 「ハイ♪　これから一緒にたくさんサーフィンしましょう！」
line = "「ハイ♪　これから一緒にたくさんサーフィンしましょう！」"

[[dialogue]]
speaker = "リップル"
# 「やっぱり、カイチョー達と来て良かったです。ガクエン通うの、ＢＩＧ楽しみになってキマした！」
line = "「やっぱり、カイチョー達と来て良かったです。ガクエン通うの、ＢＩＧ楽しみになってキマした！」"

[[dialogue]]
speaker = "unk"
# リップルなら、たくさん友達ができるよ
line = "リップルなら、たくさん友達ができるよ"

[[dialogue]]
speaker = "リップル"
# 「ふふっ。トモダチをリゾート結界にいっぱい呼んで、夏の海をスキになってもらえれば、更に結界を拡大デキます……♪」
line = "「ふふっ。トモダチをリゾート結界にいっぱい呼んで、夏の海をスキになってもらえれば、更に結界を拡大デキます……♪」"

[[dialogue]]
speaker = "リップル"
# 「まずはこの流星市国を結界で包んで、トコナツハッピー空間にするコトを目標に……！」
line = "「まずはこの流星市国を結界で包んで、トコナツハッピー空間にするコトを目標に……！」"

[[dialogue]]
speaker = "マトイ"
# 「だから怖いって！　リップル、そこは１度、私達と相談してよく話し合おうか！？　ねっ！？」
line = "「だから怖いって！　リップル、そこは１度、私達と相談してよく話し合おうか！？　ねっ！？」"

[[dialogue]]
speaker = "リップル"
# 「オウ♪　更に良いリゾート世界にする為の、サクセン会議というコトですね？　わかりマシタで～す♪」
line = "「オウ♪　更に良いリゾート世界にする為の、サクセン会議というコトですね？　わかりマシタで～す♪」"

[[dialogue]]
speaker = "マトイ"
# 「天真爛漫な笑顔が逆に不安……！」
line = "「天真爛漫な笑顔が逆に不安……！」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら♪　面白い会議になりそうね～」
line = "「あらあら♪　面白い会議になりそうね～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「何はともあれ、トラブルはあったけど、リップルのおかげで楽しい強化合宿になったわ！」
line = "「何はともあれ、トラブルはあったけど、リップルのおかげで楽しい強化合宿になったわ！」"

[[dialogue]]
speaker = "アナ"
# 「新しい水着フォームは、本来の守護星に戻っても使えるようです。気付いていなかった新しい力の使い方がわかった、という感じでしょうか」
line = "「新しい水着フォームは、本来の守護星に戻っても使えるようです。気付いていなかった新しい力の使い方がわかった、という感じでしょうか」"

[[dialogue]]
speaker = "フィオナ"
# 「そういう意味でも、リップルさんが学園に来てくれたことは大きいですね」
line = "「そういう意味でも、リップルさんが学園に来てくれたことは大きいですね」"

[[dialogue]]
speaker = "unk"
# 改めて、これからよろしく、リップル！
line = "改めて、これからよろしく、リップル！"

[[dialogue]]
speaker = "リップル"
# 「ハイ！　カイチョー、こちらこそヨロシクで～す♪」
line = "「ハイ！　カイチョー、こちらこそヨロシクで～す♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「じゃあ皆、打ち合わせ通り、アレをやりましょうか！」
line = "「じゃあ皆、打ち合わせ通り、アレをやりましょうか！」"

[[dialogue]]
speaker = "リップル"
# 「ヴィーナス？　何の話デスか？」
line = "「ヴィーナス？　何の話デスか？」"

[[dialogue]]
speaker = "サーシャ"
# 「うふふ♪　実はリップルちゃんに秘密で、皆で決めていたことがあるの～」
line = "「うふふ♪　実はリップルちゃんに秘密で、皆で決めていたことがあるの～」"

[[dialogue]]
speaker = "リップル"
# 「ワタシだけナカマ外れデスかー！？」
line = "「ワタシだけナカマ外れデスかー！？」"

[[dialogue]]
speaker = "マトイ"
# 「まあまあ、そう言わず。悪いことじゃないから」
line = "「まあまあ、そう言わず。悪いことじゃないから」"

[[dialogue]]
speaker = "アナ"
# 「ノープロブレム。私達はもう、リップルさんの仲間です」
line = "「ノープロブレム。私達はもう、リップルさんの仲間です」"

[[dialogue]]
speaker = "フィオナ"
# 「リップルさん、私達はあなたを心から歓迎します」
line = "「リップルさん、私達はあなたを心から歓迎します」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そういうことよ！　せ～のっ！」
line = "「そういうことよ！　せ～のっ！」"

[[dialogue]]
speaker = "みんな"
# 「ようこそ、私達の学園へ！」
line = "「ようこそ、私達の学園へ！」"

[[dialogue]]
speaker = "リップル"
# 「ワオ♪」
line = "「ワオ♪」"

[[dialogue]]
speaker = "リップル"
# 「アリガトございます！　とってもハッピー♪　ＢＩＧ嬉しいサプライズです！」
line = "「アリガトございます！　とってもハッピー♪　ＢＩＧ嬉しいサプライズです！」"

[[dialogue]]
speaker = "リップル"
# 「ワタシ、皆と一緒にリクリエとタタカイます！」
line = "「ワタシ、皆と一緒にリクリエとタタカイます！」"

[[dialogue]]
speaker = "リップル"
# 「そして、皆と一緒に、もっと素敵なリゾートをツクっていきます♪」
line = "「そして、皆と一緒に、もっと素敵なリゾートをツクっていきます♪」"

[[dialogue]]
speaker = "リップル"
# 「ワタシのエンドレスサマーはまだまだオワリません！　ココからで～す♪」
line = "「ワタシのエンドレスサマーはまだまだオワリません！　ココからで～す♪」"

[[dialogue]]
speaker = "unk"
# そう言って、夏の海で出会った古代天使は、天真爛漫な笑顔で高々と宣言するのだった。
line = "そう言って、夏の海で出会った古代天使は、天真爛漫な笑顔で高々と宣言するのだった。"
