[[dialogue]]
speaker = "メルクリウス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "サチ"
# 「これが、プリムラの元の姿……！？　でも私……プリムラと出会ったことは覚えてるはずなのに、この形態と戦った時の記憶がない……！」
line = "「これが、プリムラの元の姿……！？　でも私……プリムラと出会ったことは覚えてるはずなのに、この形態と戦った時の記憶がない……！」"

[[dialogue]]
speaker = "プリムラ"
# 「やはりか。こいつがサチから奪い取った記憶は、終末兵器を再現する為のもの……！」
line = "「やはりか。こいつがサチから奪い取った記憶は、終末兵器を再現する為のもの……！」"

[[dialogue]]
speaker = "プリムラ"
# 「それに付随して、我に関する１年間の記憶も、再現に必要な分を奪い取ったのじゃ！」
line = "「それに付随して、我に関する１年間の記憶も、再現に必要な分を奪い取ったのじゃ！」"

[[dialogue]]
speaker = "マトイ"
# 「うわ～。なんかすごくボスっぽい見た目……」
line = "「うわ～。なんかすごくボスっぽい見た目……」"

[[dialogue]]
speaker = "プリムラ"
# 「気を抜くな！　くるぞ！」
line = "「気を抜くな！　くるぞ！」"

[[dialogue]]
speaker = "トマル"
# 「え？　あ……！？」
line = "「え？　あ……！？」"

[[dialogue]]
speaker = "unk"
# き、急に体の力が抜けて……！
line = "き、急に体の力が抜けて……！"

[[dialogue]]
speaker = "トレジアンナ"
# 「これ、あの時のプリムラさんの能力を再現しているなら、ヤバくないですか！？　シャレにならない状況ですよ！」
line = "「これ、あの時のプリムラさんの能力を再現しているなら、ヤバくないですか！？　シャレにならない状況ですよ！」"

[[dialogue]]
speaker = "プリムラ"
# 「いいか、全員よく聞くのじゃ！　時間がないから１度しか言わん！」
line = "「いいか、全員よく聞くのじゃ！　時間がないから１度しか言わん！」"

[[dialogue]]
speaker = "プリムラ"
# 「今そいつが再現しているのは、終末兵器メルクリウスの<b>防御形態</b>！」
line = "「今そいつが再現しているのは、終末兵器メルクリウスの<b>防御形態</b>！」"

[[dialogue]]
speaker = "プリムラ"
# 「柔らかい体で物理衝撃を吸収するだけでなく、周囲のあらゆるエネルギーを取り込み、己が力に変える我本来の能力『吸収変換』を使う！」
line = "「柔らかい体で物理衝撃を吸収するだけでなく、周囲のあらゆるエネルギーを取り込み、己が力に変える我本来の能力『吸収変換』を使う！」"

[[dialogue]]
speaker = "プリムラ"
# 「体の力が抜けていくのは、こいつが吸収変換のフィールドを周囲に展開し、我らの星力や生命力が吸収されているからじゃ！」
line = "「体の力が抜けていくのは、こいつが吸収変換のフィールドを周囲に展開し、我らの星力や生命力が吸収されているからじゃ！」"

[[dialogue]]
speaker = "プリムラ"
# 「そして取り込んだエネルギーを更なる力に変えて、この吸収フィールドは際限なく広がり続ける！」
line = "「そして取り込んだエネルギーを更なる力に変えて、この吸収フィールドは際限なく広がり続ける！」"

[[dialogue]]
speaker = "プリムラ"
# 「どこまでも無限にじゃ！　このまま止めなければ、フィールドは最終的に人間界を覆い尽くすぞ！」
line = "「どこまでも無限にじゃ！　このまま止めなければ、フィールドは最終的に人間界を覆い尽くすぞ！」"

[[dialogue]]
speaker = "マトイ"
# 「そ、それって……」
line = "「そ、それって……」"

[[dialogue]]
speaker = "プリムラ"
# 「世界の終末が――」
line = "「世界の終末が――」"

[[dialogue]]
speaker = "プリムラ"
# 「<b>リクリエ</b>が今、目の前で始まったということじゃ！」
line = "「<b>リクリエ</b>が今、目の前で始まったということじゃ！」"

[[dialogue]]
speaker = "プリムラ"
# 「フィールドはあらゆるエネルギーを吸収する！　人や生き物の生命力、星力、電力、熱量、それに光さえも！」
line = "「フィールドはあらゆるエネルギーを吸収する！　人や生き物の生命力、星力、電力、熱量、それに光さえも！」"

[[dialogue]]
speaker = "トマル"
# 「周囲が夜みたいに暗く見えるのは、そのせいで……！」
line = "「周囲が夜みたいに暗く見えるのは、そのせいで……！」"

[[dialogue]]
speaker = "プリムラ"
# 「それが、終末兵器メルクリウスじゃ！　吸収フィールドがトレジアンナの人払いの範囲を越える前に、なんとしても止めるのじゃ！」
line = "「それが、終末兵器メルクリウスじゃ！　吸収フィールドがトレジアンナの人払いの範囲を越える前に、なんとしても止めるのじゃ！」"

[[dialogue]]
speaker = "プリムラ"
# 「さもなくば、本当に世界が滅びるぞ！」
line = "「さもなくば、本当に世界が滅びるぞ！」"

[[dialogue]]
speaker = "unk"
# っ……みんな、やるぞ！
line = "っ……みんな、やるぞ！"

[[dialogue]]
speaker = "サチ"
# 「はい！」
line = "「はい！」"

[[dialogue]]
speaker = "unk"
# しかし――
line = "しかし――"

[[dialogue]]
speaker = "サチ"
# 「くっ……！　隙がない……！」
line = "「くっ……！　隙がない……！」"

[[dialogue]]
speaker = "サチ"
# （弾幕のように強力なビームを連射して近寄らせず、接近しても柔らかい体で衝撃を吸収して防がれる）
line = "（弾幕のように強力なビームを連射して近寄らせず、接近しても柔らかい体で衝撃を吸収して防がれる）"

[[dialogue]]
speaker = "サチ"
# （おまけに、私の幸運体質が通用しない。奪われた記憶からメルクリウス自身も幸運体質を再現して、相殺してる……！）
line = "（おまけに、私の幸運体質が通用しない。奪われた記憶からメルクリウス自身も幸運体質を再現して、相殺してる……！）"

[[dialogue]]
speaker = "サチ"
# （そして、手間取って時間をかける程に、私達の星力は吸われて、衰弱していく……！）
line = "（そして、手間取って時間をかける程に、私達の星力は吸われて、衰弱していく……！）"

[[dialogue]]
speaker = "サチ"
# （いや、弱気になるな……！　私は運勢がよくない時だって、生徒会長として恥じない実力でいられるように、訓練を積んできたんだから……！）
line = "（いや、弱気になるな……！　私は運勢がよくない時だって、生徒会長として恥じない実力でいられるように、訓練を積んできたんだから……！）"

[[dialogue]]
speaker = "サチ"
# 「フォーチュンウェーブ！」
line = "「フォーチュンウェーブ！」"

[[dialogue]]
speaker = "サチ"
# 「よし、直撃した！　怯んでる今のうちに……！」
line = "「よし、直撃した！　怯んでる今のうちに……！」"

[[dialogue]]
speaker = "プリムラ"
# 「いかん、サチ！　攻撃を受けたのはわざとじゃ！」
line = "「いかん、サチ！　攻撃を受けたのはわざとじゃ！」"

[[dialogue]]
speaker = "サチ"
# 「え？　しまっ……！」
line = "「え？　しまっ……！」"

[[dialogue]]
speaker = "unk"
# それは、追撃しようとサチが見せた一瞬の隙。メルクリウスはダメージを無視して、瞬時にカウンターでビームを放っていた。
line = "それは、追撃しようとサチが見せた一瞬の隙。メルクリウスはダメージを無視して、瞬時にカウンターでビームを放っていた。"

[[dialogue]]
speaker = "unk"
# 間に合わない！
line = "間に合わない！"

[[dialogue]]
speaker = "unk"
# 咄嗟にサチの元へ飛び込んだが、あと数メートル距離が届かない。サチの体をビームが貫こうとする、その時だった。
line = "咄嗟にサチの元へ飛び込んだが、あと数メートル距離が届かない。サチの体をビームが貫こうとする、その時だった。"

[[dialogue]]
speaker = "プリムラ"
# 「この馬鹿者が！」
line = "「この馬鹿者が！」"

[[dialogue]]
speaker = "サチ"
# 「きゃっ！？　プリムラ！？」
line = "「きゃっ！？　プリムラ！？」"

[[dialogue]]
speaker = "プリムラ"
# 「っ……！」
line = "「っ……！」"

[[dialogue]]
speaker = "unk"
# サチを突き飛ばし、割って入ったプリムラが、ビームに貫かれた。
line = "サチを突き飛ばし、割って入ったプリムラが、ビームに貫かれた。"

[[dialogue]]
speaker = "サチ"
# 「プリ……ムラ……？　嘘でしょ……！？」
line = "「プリ……ムラ……？　嘘でしょ……！？」"

[[dialogue]]
speaker = "unk"
# 倒れたプリムラはそのまま、力を急速に失っていき……やがて光の粒に変わって、その場から消滅した――
line = "倒れたプリムラはそのまま、力を急速に失っていき……やがて光の粒に変わって、その場から消滅した――"

[[dialogue]]
speaker = "サチ"
# 「そ、そんな……！　プリムラ！　どうしてよ……プリムラぁぁぁっ！」
line = "「そ、そんな……！　プリムラ！　どうしてよ……プリムラぁぁぁっ！」"

[[dialogue]]
speaker = "プリムラ"
# 「――そんなもん、死なんからに決まっとるじゃろ、全く……」
line = "「――そんなもん、死なんからに決まっとるじゃろ、全く……」"

[[dialogue]]
speaker = "サチ"
# 「え……？　あれ！？　プリムラ……なんで……！？」
line = "「え……？　あれ！？　プリムラ……なんで……！？」"

[[dialogue]]
speaker = "サチ"
# 「あ……私のペンダントが……封印のロストアイテムが光ってる……？」
line = "「あ……私のペンダントが……封印のロストアイテムが光ってる……？」"

[[dialogue]]
speaker = "unk"
# サチがペンダントを取り出すと、繋がれた宝石が光り輝いていた。
line = "サチがペンダントを取り出すと、繋がれた宝石が光り輝いていた。"

[[dialogue]]
speaker = "プリムラ"
# 「我の力の大部分――賢者の石の核は、お前の持つ『星の鎖』によって封印されている。簡単に言うと、我の本体はペンダントの中にあるということじゃ」
line = "「我の力の大部分――賢者の石の核は、お前の持つ『星の鎖』によって封印されている。簡単に言うと、我の本体はペンダントの中にあるということじゃ」"

[[dialogue]]
speaker = "プリムラ"
# 「こうして外に出ている我は、本体から遠隔操作している端末――アバターのようなもの。よって、消滅すればペンダントから復活――リスポーンできるというわけじゃ」
line = "「こうして外に出ている我は、本体から遠隔操作している端末――アバターのようなもの。よって、消滅すればペンダントから復活――リスポーンできるというわけじゃ」"

[[dialogue]]
speaker = "プリムラ"
# 「ただ、クールタイムがあって連続でポンポン復活できるわけではないがな」
line = "「ただ、クールタイムがあって連続でポンポン復活できるわけではないがな」"

[[dialogue]]
speaker = "プリムラ"
# 「まあ、それに……あれじゃ……」
line = "「まあ、それに……あれじゃ……」"

[[dialogue]]
speaker = "プリムラ"
# 「不本意ではあるが、貴様は<b>相棒</b>じゃからな」
line = "「不本意ではあるが、貴様は<b>相棒</b>じゃからな」"

[[dialogue]]
speaker = "サチ"
# 「あ……」
line = "「あ……」"

[[dialogue]]
speaker = "サチ"
# （激しい既視感。それと共に、私は半年前の記憶が、パズルのピースが埋まるように蘇ってきた――）
line = "（激しい既視感。それと共に、私は半年前の記憶が、パズルのピースが埋まるように蘇ってきた――）"

[[dialogue]]
speaker = "サチ"
# （そう、その時もプリムラと一緒にロストアイテム回収を行っていて。私が苦戦して、攻撃をくらいそうになったんだ）
line = "（そう、その時もプリムラと一緒にロストアイテム回収を行っていて。私が苦戦して、攻撃をくらいそうになったんだ）"

[[dialogue]]
speaker = "サチ"
# （そこでプリムラが私を庇って、ダメージを受けて消滅。星の鎖から復活して……）
line = "（そこでプリムラが私を庇って、ダメージを受けて消滅。星の鎖から復活して……）"

[[dialogue]]
speaker = "サチ"
# （私は、ロストアイテムが逃げるのも構わず、プリムラに泣いて怒ってしまった――）
line = "（私は、ロストアイテムが逃げるのも構わず、プリムラに泣いて怒ってしまった――）"

[[dialogue]]
speaker = "プリムラ"
# 「お、おい！　サチ、貴様……なんで泣くのじゃ！？」
line = "「お、おい！　サチ、貴様……なんで泣くのじゃ！？」"

[[dialogue]]
speaker = "サチ"
# 「よく知ってる奴が死んだら、泣くのは当たり前でしょ！？」
line = "「よく知ってる奴が死んだら、泣くのは当たり前でしょ！？」"

[[dialogue]]
speaker = "プリムラ"
# 「我は貴様の宿敵！　悪の終末兵器じゃぞ！？」
line = "「我は貴様の宿敵！　悪の終末兵器じゃぞ！？」"

[[dialogue]]
speaker = "サチ"
# 「悪でも宿敵でも、泣くものは泣くのよ！」
line = "「悪でも宿敵でも、泣くものは泣くのよ！」"

[[dialogue]]
speaker = "プリムラ"
# 「わけわからん！　生意気だとか、ムカつくとか、ひどい奴だとかいつも言っていたではないか！」
line = "「わけわからん！　生意気だとか、ムカつくとか、ひどい奴だとかいつも言っていたではないか！」"

[[dialogue]]
speaker = "サチ"
# 「仕方ないでしょ！　不本意でも――」
line = "「仕方ないでしょ！　不本意でも――」"

[[dialogue]]
speaker = "サチ"
# 「これまで一緒にやってきた相棒なんだから！」
line = "「これまで一緒にやってきた相棒なんだから！」"

[[dialogue]]
speaker = "プリムラ"
# 「我が……相棒、じゃと……？」
line = "「我が……相棒、じゃと……？」"

[[dialogue]]
speaker = "サチ"
# （そうだ、思い出した。私達の関係は、トマルくんみたいな友達とも、トレジアンナさんのような家族とも、違う――）
line = "（そうだ、思い出した。私達の関係は、トマルくんみたいな友達とも、トレジアンナさんのような家族とも、違う――）"

[[dialogue]]
speaker = "サチ"
# 「プリムラ」
line = "「プリムラ」"

[[dialogue]]
speaker = "サチ"
# 「――私、謝らないからね。不本意な記憶喪失だったんだし」
line = "「――私、謝らないからね。不本意な記憶喪失だったんだし」"

[[dialogue]]
speaker = "プリムラ"
# 「サチ、まさか貴様……？」
line = "「サチ、まさか貴様……？」"

[[dialogue]]
speaker = "プリムラ"
# 「フ、フフ……」
line = "「フ、フフ……」"

[[dialogue]]
speaker = "プリムラ"
# 「ふん、よく言うわ。庇って死んだら泣くとか言っておきながら、貴様の方は我を庇って記憶を奪われた癖に」
line = "「ふん、よく言うわ。庇って死んだら泣くとか言っておきながら、貴様の方は我を庇って記憶を奪われた癖に」"

[[dialogue]]
speaker = "プリムラ"
# 「まあよい。何が起こったかわからぬが、記憶が戻ったなら好都合」
line = "「まあよい。何が起こったかわからぬが、記憶が戻ったなら好都合」"

[[dialogue]]
speaker = "プリムラ"
# 「さっさと手を貸せ。我はこんな面倒くさいことを引き起こしたロストアイテムに、痛い目を見せてやらねば気が済まん」
line = "「さっさと手を貸せ。我はこんな面倒くさいことを引き起こしたロストアイテムに、痛い目を見せてやらねば気が済まん」"

[[dialogue]]
speaker = "サチ"
# 「そうね……私も借りがあるし、お兄さんの記憶も返してもらわないとだし――」
line = "「そうね……私も借りがあるし、お兄さんの記憶も返してもらわないとだし――」"

[[dialogue]]
speaker = "unk"
# 魔法少女２人が並んで、終末兵器へ向き直る。
line = "魔法少女２人が並んで、終末兵器へ向き直る。"

[[dialogue]]
speaker = "unk"
# その時、確かに見えた。
line = "その時、確かに見えた。"

[[dialogue]]
speaker = "unk"
# 終末兵器の絶望的な強さを前にしながら……サチを中心として、見えない大きな流れがこちらへ傾くのを。
line = "終末兵器の絶望的な強さを前にしながら……サチを中心として、見えない大きな流れがこちらへ傾くのを。"

[[dialogue]]
speaker = "unk"
# みんな！　今がチャンスだ！
line = "みんな！　今がチャンスだ！"

[[dialogue]]
speaker = "サチ"
# 「！　はい、お兄さん！」
line = "「！　はい、お兄さん！」"

[[dialogue]]
speaker = "プリムラ"
# 「ふっ、眷族の頼みならば、仕方あるまい」
line = "「ふっ、眷族の頼みならば、仕方あるまい」"

[[dialogue]]
speaker = "トレジアンナ"
# 「魔法少女活動のクライマックスですよ～！」
line = "「魔法少女活動のクライマックスですよ～！」"

[[dialogue]]
speaker = "マトイ"
# 「防御は私に任せて！」
line = "「防御は私に任せて！」"

[[dialogue]]
speaker = "トマル"
# 「援護は私に！　ですから、サチさま、プリムラさま――」
line = "「援護は私に！　ですから、サチさま、プリムラさま――」"

[[dialogue]]
speaker = "トマル"
# 「ご存分に暴れて下さい！」
line = "「ご存分に暴れて下さい！」"

[[dialogue]]
speaker = "サチ"
# 「うん！　行くよ、相棒」
line = "「うん！　行くよ、相棒」"

[[dialogue]]
speaker = "プリムラ"
# 「おう！」
line = "「おう！」"

[[dialogue]]
speaker = "サチ"
# 「人事天命……ここからは――」
line = "「人事天命……ここからは――」"

[[dialogue]]
speaker = "プリムラ"
# 「ハズレなしじゃ！」
line = "「ハズレなしじゃ！」"

[[dialogue]]
speaker = "unk"
# ロストアイテムとの決戦が、幕を開けるのだった。
line = "ロストアイテムとの決戦が、幕を開けるのだった。"
