[[dialogue]]
speaker = "unk"
# マトイに気を失った生徒たちの保護を任せた後、プリムラは１人、ロストアイテムと対峙していた。
line = "マトイに気を失った生徒たちの保護を任せた後、プリムラは１人、ロストアイテムと対峙していた。"

[[dialogue]]
speaker = "ロストアイテム"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "プリムラ"
# 「貴様……いよいよ本格的に人を襲いはじめたかと思えば……なんのつもりじゃ、その姿は……！」
line = "「貴様……いよいよ本格的に人を襲いはじめたかと思えば……なんのつもりじゃ、その姿は……！」"

[[dialogue]]
speaker = "プリムラ"
# 「奪い取ったサチの記憶から再現したということか？　ふざけた真似をしおって……」
line = "「奪い取ったサチの記憶から再現したということか？　ふざけた真似をしおって……」"

[[dialogue]]
speaker = "プリムラ"
# 「まさか、サチが我を１度倒した存在だからか……？　ククク――」
line = "「まさか、サチが我を１度倒した存在だからか……？　ククク――」"

[[dialogue]]
speaker = "プリムラ"
# 「１０万年早いのじゃ、このコピー風情がっ！！！」
line = "「１０万年早いのじゃ、このコピー風情がっ！！！」"

[[dialogue]]
speaker = "プリムラ"
# （こうして戦っていると、１年前に出会った時のことを思い出す）
line = "（こうして戦っていると、１年前に出会った時のことを思い出す）"

[[dialogue]]
speaker = "プリムラ"
# （その日、終末兵器として目覚めた我は、人のひしめき合う街のど真ん中に投入されたはず……じゃったが）
line = "（その日、終末兵器として目覚めた我は、人のひしめき合う街のど真ん中に投入されたはず……じゃったが）"

[[dialogue]]
speaker = "プリムラ"
# 「なぜじゃ……？　なぜ誰も人がいない？」
line = "「なぜじゃ……？　なぜ誰も人がいない？」"

[[dialogue]]
speaker = "プリムラ"
# （これでは我にインプットされた、破壊活動が開始できないではないか！　そう思った時じゃった――）
line = "（これでは我にインプットされた、破壊活動が開始できないではないか！　そう思った時じゃった――）"

[[dialogue]]
speaker = "プリムラ"
# （そいつが――幸運の化け物が目の前に現れたのは）
line = "（そいつが――幸運の化け物が目の前に現れたのは）"

[[dialogue]]
speaker = "サチ"
# 「あなたが創造のロストアイテム……賢者の石？」
line = "「あなたが創造のロストアイテム……賢者の石？」"

[[dialogue]]
speaker = "プリムラ"
# 「誰じゃお前は？」
line = "「誰じゃお前は？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「人呼んで、幸運の魔法少女トレジャー☆サチ！　人事天命、ここからはハズレなしですよ～♪」
line = "「人呼んで、幸運の魔法少女トレジャー☆サチ！　人事天命、ここからはハズレなしですよ～♪」"

[[dialogue]]
speaker = "サチ"
# 「いえ、人違いです」
line = "「いえ、人違いです」"

[[dialogue]]
speaker = "プリムラ"
# 「……ふざけておるのか？」
line = "「……ふざけておるのか？」"

[[dialogue]]
speaker = "プリムラ"
# （後から知ったが、誰も人がいなかったのは、トレジアンナの使う人払いの星術によるものじゃった）
line = "（後から知ったが、誰も人がいなかったのは、トレジアンナの使う人払いの星術によるものじゃった）"

[[dialogue]]
speaker = "プリムラ"
# 「我を誰だと思っとるのじゃ。我はリクリエを引き起こす為に作られた終末兵器メルクリウス――」
line = "「我を誰だと思っとるのじゃ。我はリクリエを引き起こす為に作られた終末兵器メルクリウス――」"

[[dialogue]]
speaker = "プリムラ"
# 「舐めてると貴様……殺すぞ？」
line = "「舐めてると貴様……殺すぞ？」"

[[dialogue]]
speaker = "サチ"
# 「……！　と、とてつもない力を感じます……！　これは……！」
line = "「……！　と、とてつもない力を感じます……！　これは……！」"

[[dialogue]]
speaker = "プリムラ"
# 「終末術式……起動。インフィニットドレイン！」
line = "「終末術式……起動。インフィニットドレイン！」"

[[dialogue]]
speaker = "プリムラ"
# （そうして、我と化け物の死闘は始まった。この時、ビルが１つ消し飛んで、幸運なことに被害者ゼロだった爆発事故、として記録が残されておる）
line = "（そうして、我と化け物の死闘は始まった。この時、ビルが１つ消し飛んで、幸運なことに被害者ゼロだった爆発事故、として記録が残されておる）"

[[dialogue]]
speaker = "プリムラ"
# 「なんなんじゃ……なんで攻撃が当たらん！？　なぜそんなロストアイテムを持っている！？　そもそもなぜ、貴様がここにいる！？」
line = "「なんなんじゃ……なんで攻撃が当たらん！？　なぜそんなロストアイテムを持っている！？　そもそもなぜ、貴様がここにいる！？」"

[[dialogue]]
speaker = "プリムラ"
# （そして悲しいかな、不運なことに我は、終末兵器としてそのビル１つしか成果を残せず、幸運の化け物には掠り傷１つも負わせられず）
line = "（そして悲しいかな、不運なことに我は、終末兵器としてそのビル１つしか成果を残せず、幸運の化け物には掠り傷１つも負わせられず）"

[[dialogue]]
speaker = "プリムラ"
# 「貴様は一体、なんなのじゃあぁぁぁーーーーーーっ！！？」
line = "「貴様は一体、なんなのじゃあぁぁぁーーーーーーっ！！？」"

[[dialogue]]
speaker = "プリムラ"
# （根本的な力の総量において、圧倒的に上であるはずの我は、幸運というイレギュラーの前には手も足も出ずに、敗北を喫したのじゃった――）
line = "（根本的な力の総量において、圧倒的に上であるはずの我は、幸運というイレギュラーの前には手も足も出ずに、敗北を喫したのじゃった――）"

[[dialogue]]
speaker = "プリムラ"
# 「おのれ……貴様に出会いさえしなければ……！　こんな不運な出会いさえなければ、我は……！」
line = "「おのれ……貴様に出会いさえしなければ……！　こんな不運な出会いさえなければ、我は……！」"

[[dialogue]]
speaker = "プリムラ"
# （じゃが……我は死ななかった）
line = "（じゃが……我は死ななかった）"

[[dialogue]]
speaker = "プリムラ"
# （幸運の化け物はその後、なぜか学園の上層部にかけあって、我を保護観察処分として味方につける選択をした）
line = "（幸運の化け物はその後、なぜか学園の上層部にかけあって、我を保護観察処分として味方につける選択をした）"

[[dialogue]]
speaker = "プリムラ"
# （サチの持つペンダント――封印のロストアイテム『星の鎖』で、力の大半を封じられてるとはいえ、精神は未だ悪の終末兵器のままである我を）
line = "（サチの持つペンダント――封印のロストアイテム『星の鎖』で、力の大半を封じられてるとはいえ、精神は未だ悪の終末兵器のままである我を）"

[[dialogue]]
speaker = "プリムラ"
# 「何故じゃ……なぜ我を生かしておく？　わからぬ……貴様は一体、なにを考えている！？」
line = "「何故じゃ……なぜ我を生かしておく？　わからぬ……貴様は一体、なにを考えている！？」"

[[dialogue]]
speaker = "プリムラ"
# 「我は悪の終末兵器なのじゃぞ！？　我は貴様が憎い！　不運にも貴様が現れたから、我はこんな無様な姿になって、生き恥を晒しておる！」
line = "「我は悪の終末兵器なのじゃぞ！？　我は貴様が憎い！　不運にも貴様が現れたから、我はこんな無様な姿になって、生き恥を晒しておる！」"

[[dialogue]]
speaker = "プリムラ"
# 「まさか、我が貴様に手も足も出なかったから舐めておるのか！？　言っておくが我は、そのペンダントさえ無ければ、今すぐにでも貴様を殺すぞ！？」
line = "「まさか、我が貴様に手も足も出なかったから舐めておるのか！？　言っておくが我は、そのペンダントさえ無ければ、今すぐにでも貴様を殺すぞ！？」"

[[dialogue]]
speaker = "プリムラ"
# 「このまま生かしておれば、いずれそのペンダントを奪って、必ず貴様を殺す！　我は生まれながらの悪！　世界を滅ぼす終末兵器じゃ！」
line = "「このまま生かしておれば、いずれそのペンダントを奪って、必ず貴様を殺す！　我は生まれながらの悪！　世界を滅ぼす終末兵器じゃ！」"

[[dialogue]]
speaker = "プリムラ"
# 「それでも貴様は、我を生かすというのか！？」
line = "「それでも貴様は、我を生かすというのか！？」"

[[dialogue]]
speaker = "サチ"
# 「あなた……私と出会ったのが不運だって、戦いの最後にも言ってたでしょ？　私にとって、それは違うって思ったから」
line = "「あなた……私と出会ったのが不運だって、戦いの最後にも言ってたでしょ？　私にとって、それは違うって思ったから」"

[[dialogue]]
speaker = "サチ"
# 「私、特殊な体質で生まれてきたから……感覚的なものだけど、この世に『幸運』があるっていうことを、確かに知ってるの」
line = "「私、特殊な体質で生まれてきたから……感覚的なものだけど、この世に『幸運』があるっていうことを、確かに知ってるの」"

[[dialogue]]
speaker = "サチ"
# 「あなたが誰も殺さずに済んだことは、私は幸運なことだと思う。それに今の状態なら、あなたは悪さができない。それも幸運」
line = "「あなたが誰も殺さずに済んだことは、私は幸運なことだと思う。それに今の状態なら、あなたは悪さができない。それも幸運」"

[[dialogue]]
speaker = "プリムラ"
# 「それは貴様にとっての幸運で！　我からしたら、不運！　ただのエゴじゃ！」
line = "「それは貴様にとっての幸運で！　我からしたら、不運！　ただのエゴじゃ！」"

[[dialogue]]
speaker = "サチ"
# 「そうなのかもしれない。でも、生まれたばかりだっていうあなたの命を奪ったら、私は自分の信じている幸運を、わかっていながら握り潰すことになる」
line = "「そうなのかもしれない。でも、生まれたばかりだっていうあなたの命を奪ったら、私は自分の信じている幸運を、わかっていながら握り潰すことになる」"

[[dialogue]]
speaker = "サチ"
# 「それはできない。少なくともプリムラ……あなたはまだ、違う生き方ができるんだから」
line = "「それはできない。少なくともプリムラ……あなたはまだ、違う生き方ができるんだから」"

[[dialogue]]
speaker = "プリムラ"
# 「……何じゃその、プリムラという名前は」
line = "「……何じゃその、プリムラという名前は」"

[[dialogue]]
speaker = "サチ"
# 「昔見た魔法少女のアニメで、スライムの妖精が出てきたのを覚えてたんだよね」
line = "「昔見た魔法少女のアニメで、スライムの妖精が出てきたのを覚えてたんだよね」"

[[dialogue]]
speaker = "サチ"
# 「ラッキースライムのプリムラ。メルクリウスよりは女の子っぽくて、可愛い名前かなって思うんだけど、どうかな？」
line = "「ラッキースライムのプリムラ。メルクリウスよりは女の子っぽくて、可愛い名前かなって思うんだけど、どうかな？」"

[[dialogue]]
speaker = "プリムラ"
# 「か、可愛いじゃと……！？　ああもう……！」
line = "「か、可愛いじゃと……！？　ああもう……！」"

[[dialogue]]
speaker = "プリムラ"
# 「本当になんなのじゃ貴様は……！　なにが幸運じゃ……！　我は認めぬ……絶対にこんなのは認めぬのだ！」
line = "「本当になんなのじゃ貴様は……！　なにが幸運じゃ……！　我は認めぬ……絶対にこんなのは認めぬのだ！」"

[[dialogue]]
speaker = "プリムラ"
# 「――よく聞け、<ruby=しろつめ>白詰</ruby>サチ！」
line = "「――よく聞け、<ruby>白詰<rt>しろつめ</rt></ruby>サチ！」"

[[dialogue]]
speaker = "プリムラ"
# 「こうなれば、我は恥を飲み込んで、生きてやる！　だが、必ず生きて、貴様に奪われた終末兵器としての力を取り戻してやるのじゃ！」
line = "「こうなれば、我は恥を飲み込んで、生きてやる！　だが、必ず生きて、貴様に奪われた終末兵器としての力を取り戻してやるのじゃ！」"

[[dialogue]]
speaker = "プリムラ"
# 「そして、その時こそ貴様を倒して、後悔させてやる！」
line = "「そして、その時こそ貴様を倒して、後悔させてやる！」"

[[dialogue]]
speaker = "プリムラ"
# 「我を生かしたことは、幸運ではなく、不運な勘違いであったと！」
line = "「我を生かしたことは、幸運ではなく、不運な勘違いであったと！」"

[[dialogue]]
speaker = "サチ"
# 「……まあ、今はそれでいっか」
line = "「……まあ、今はそれでいっか」"

[[dialogue]]
speaker = "サチ"
# 「私も１度あなたを助けた以上、必ず更生させて、いいスライムにさせるから」
line = "「私も１度あなたを助けた以上、必ず更生させて、いいスライムにさせるから」"

[[dialogue]]
speaker = "サチ"
# 「そして、生きてて幸運だったって、いつか言わせてみせる」
line = "「そして、生きてて幸運だったって、いつか言わせてみせる」"

[[dialogue]]
speaker = "プリムラ"
# 「というか、そもそも我はスライムではないのじゃ！」
line = "「というか、そもそも我はスライムではないのじゃ！」"

[[dialogue]]
speaker = "unk"
# ――何度目のぶつかり合いになるのか。プリムラはロストアイテムが再現したサチの幸運によって攻撃が当たらず、逆に放たれた水球によって吹っ飛ばされた。
line = "――何度目のぶつかり合いになるのか。プリムラはロストアイテムが再現したサチの幸運によって攻撃が当たらず、逆に放たれた水球によって吹っ飛ばされた。"

[[dialogue]]
speaker = "プリムラ"
# 「カハッ……！　くっ……ククク――」
line = "「カハッ……！　くっ……ククク――」"

[[dialogue]]
speaker = "プリムラ"
# 「ハハハハハハッ！　ぬるいわっ！！　この程度、あの時戦った本物の化け物に比べればっ！！！」
line = "「ハハハハハハッ！　ぬるいわっ！！　この程度、あの時戦った本物の化け物に比べればっ！！！」"

[[dialogue]]
speaker = "ロストアイテム"
# 「…………！」
line = "「…………！」"

[[dialogue]]
speaker = "プリムラ"
# 「いいか？　あの化け物は、馬鹿みたいに甘い幸運を信じておるのじゃ。故に、どうやっても悪側に回ることはない」
line = "「いいか？　あの化け物は、馬鹿みたいに甘い幸運を信じておるのじゃ。故に、どうやっても悪側に回ることはない」"

[[dialogue]]
speaker = "プリムラ"
# 「わかるか？　他人の記憶を奪うことしかできない脳なしよ！」
line = "「わかるか？　他人の記憶を奪うことしかできない脳なしよ！」"

[[dialogue]]
speaker = "プリムラ"
# 「貴様のやっていることは、チョコレートに混ぜる砂糖と塩を間違えたようなもの！　そんな化け物の劣化コピーなんぞにっ！！」
line = "「貴様のやっていることは、チョコレートに混ぜる砂糖と塩を間違えたようなもの！　そんな化け物の劣化コピーなんぞにっ！！」"

[[dialogue]]
speaker = "プリムラ"
# 「真の終末兵器たる我が負けるかぁぁぁーーーーーーっ！！！」
line = "「真の終末兵器たる我が負けるかぁぁぁーーーーーーっ！！！」"

[[dialogue]]
speaker = "unk"
# プリムラは巨大な拳を振りかぶり、ロストアイテムの懐に飛び込む。
line = "プリムラは巨大な拳を振りかぶり、ロストアイテムの懐に飛び込む。"

[[dialogue]]
speaker = "unk"
# ロストアイテムはサチの幸運を再現して、それをまた避けようとするが――
line = "ロストアイテムはサチの幸運を再現して、それをまた避けようとするが――"

[[dialogue]]
speaker = "プリムラ"
# 「そんな生温い幸運なんぞ、握り潰してくれるわぁぁぁっ！」
line = "「そんな生温い幸運なんぞ、握り潰してくれるわぁぁぁっ！」"

[[dialogue]]
speaker = "ロストアイテム"
# 「…………！？」
line = "「…………！？」"

[[dialogue]]
speaker = "unk"
# 
line = ""

[[dialogue]]
speaker = "unk"
# プリムラの拳が、幸運の壁を打ち砕く！
line = "プリムラの拳が、幸運の壁を打ち砕く！"

[[dialogue]]
speaker = "プリムラ"
# 「ぶち抜け！　ドレインハンドクラッシャーッ！！！」
line = "「ぶち抜け！　ドレインハンドクラッシャーッ！！！」"

[[dialogue]]
speaker = "ロストアイテム"
# 「…………っ」
line = "「…………っ」"

[[dialogue]]
speaker = "プリムラ"
# 「ふん……相手が悪かったな、偽物よ」
line = "「ふん……相手が悪かったな、偽物よ」"

[[dialogue]]
speaker = "プリムラ"
# 「――あいにく我は、いずれ本物の幸運に勝つと決めておるのじゃ」
line = "「――あいにく我は、いずれ本物の幸運に勝つと決めておるのじゃ」"

[[dialogue]]
speaker = "サチ"
# 「プリムラ！」
line = "「プリムラ！」"

[[dialogue]]
speaker = "unk"
# 無事か！？
line = "無事か！？"

[[dialogue]]
speaker = "プリムラ"
# 「遅かったな、貴様達……ロストアイテムなら、そこに倒れておるぞ」
line = "「遅かったな、貴様達……ロストアイテムなら、そこに倒れておるぞ」"

[[dialogue]]
speaker = "プリムラ"
# 「トレジアンナ、あとは貴様の回収術式で――なに……！？」
line = "「トレジアンナ、あとは貴様の回収術式で――なに……！？」"

[[dialogue]]
speaker = "マトイ"
# 「な、何これ……！？　周りが急に、夜みたいに暗くなって……！？」
line = "「な、何これ……！？　周りが急に、夜みたいに暗くなって……！？」"

[[dialogue]]
speaker = "トマル"
# 「プリムラさま、後ろです！」
line = "「プリムラさま、後ろです！」"

[[dialogue]]
speaker = "プリムラ"
# 「ロストアイテム……！　まだ動くのか……！」
line = "「ロストアイテム……！　まだ動くのか……！」"

[[dialogue]]
speaker = "サチ"
# 「ロストアイテムの姿が変わって……！」
line = "「ロストアイテムの姿が変わって……！」"

[[dialogue]]
speaker = "プリムラ"
# 「この姿は、まさか……！　我が勝ったから、切り換えたのか……！？」
line = "「この姿は、まさか……！　我が勝ったから、切り換えたのか……！？」"

[[dialogue]]
speaker = "プリムラ"
# 「終末兵器メルクリウス……！」
line = "「終末兵器メルクリウス……！」"
