[[dialogue]]
speaker = "聖沙"
# 「ティンクル☆くるせいだーすコラボ、第３弾！」
line = "「ティンクル☆くるせいだーすコラボ、第３弾！」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「ついに、開催当日よ～♪」
line = "「ついに、開催当日よ～♪」"

[[dialogue]]
speaker = "リア"
# 「どんどん、ぱふぱふ～♪」
line = "「どんどん、ぱふぱふ～♪」"

[[dialogue]]
speaker = "ルネア"
# 「流星町の『ルネアリゾート結界』、お披露目の時ね♪」
line = "「流星町の『ルネアリゾート結界』、お披露目の時ね♪」"

[[dialogue]]
speaker = "ロロット"
# 「待ってました～♪」
line = "「待ってました～♪」"

[[dialogue]]
speaker = "ナナカ"
# 「よ～し、夏の海を思いっきり楽しんじゃうぞ～！」
line = "「よ～し、夏の海を思いっきり楽しんじゃうぞ～！」"

[[dialogue]]
speaker = "パッキー"
# 「クックック、俺様も、水着のリアちゃんとスウィートなバカンスを楽しむぜ……！」
line = "「クックック、俺様も、水着のリアちゃんとスウィートなバカンスを楽しむぜ……！」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「パーちゃ～ん？　私の可愛いリアに、オイタしたりしちゃダメよ～？」
line = "「パーちゃ～ん？　私の可愛いリアに、オイタしたりしちゃダメよ～？」"

[[dialogue]]
speaker = "パッキー"
# 「ヒエッ！？　ハ、ハイ……」
line = "「ヒエッ！？　ハ、ハイ……」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「ふふっ<emoji=heart04>　それじゃあ、あんまり待たせちゃっても悪いし、そろそろ始めましょうか♪」
line = "「ふふっ<emoji=heart04>　それじゃあ、あんまり待たせちゃっても悪いし、そろそろ始めましょうか♪」"

[[dialogue]]
speaker = "リア"
# 「うん♪　みんな、せ～ので行くよ～♪」
line = "「うん♪　みんな、せ～ので行くよ～♪」"

[[dialogue]]
speaker = "ルネア"
# 「いつでもいいわよ♪」
line = "「いつでもいいわよ♪」"

[[dialogue]]
speaker = "ロロット"
# 「は～い♪」
line = "「は～い♪」"

[[dialogue]]
speaker = "ナナカ"
# 「よっしゃ♪」
line = "「よっしゃ♪」"

[[dialogue]]
speaker = "聖沙"
# 「せ～のっ♪」
line = "「せ～のっ♪」"

[[dialogue]]
speaker = "全員"
# 「コラボイベント、<ruby=レディー>ＲＥＡＤＹ</ruby>　<ruby=ゴー>ＧＯ</ruby>！！」
line = "「コラボイベント、<ruby>ＲＥＡＤＹ<rt>レディー</rt></ruby>　<ruby>ＧＯ<rt>ゴー</rt></ruby>！！」"
