[[dialogue]]
speaker = "unk"
# 第９話,未熟でも、二人なら,B
line = "第９話,未熟でも、二人なら,B"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# 午後５時──今日の活動を始めて半日が過ぎた。
line = "午後５時──今日の活動を始めて半日が過ぎた。"

[[dialogue]]
speaker = "unk"
# 俺は、そろそろレゾフへ戻ろうと……
line = "俺は、そろそろレゾフへ戻ろうと……"

[[dialogue]]
speaker = "フィオナ"
# 「──緋宮会長」
line = "「──緋宮会長」"

[[dialogue]]
speaker = "クロト"
# 「……フィオナ」
line = "「……フィオナ」"

[[dialogue]]
speaker = "unk"
# 街の裏手には、フィオナが待ち構えていた。
line = "街の裏手には、フィオナが待ち構えていた。"

[[dialogue]]
speaker = "フィオナ"
# 「危ないですよ。その近辺には──強大な魔獣のねぐらが固まっていると、親切な旅人さんも言っていました」
line = "「危ないですよ。その近辺には──強大な魔獣のねぐらが固まっていると、親切な旅人さんも言っていました」"

[[dialogue]]
speaker = "クロト"
# 「……ああ。それは俺も聞いた」
line = "「……ああ。それは俺も聞いた」"

[[dialogue]]
speaker = "クロト"
# 「だから、今のうちに一掃しておいたんだ。万が一ってこともある──街の近くは片付けておいたほうが安全だろ」
line = "「だから、今のうちに一掃しておいたんだ。万が一ってこともある──街の近くは片付けておいたほうが安全だろ」"

[[dialogue]]
speaker = "フィオナ"
# 「お一人で……ですか？」
line = "「お一人で……ですか？」"

[[dialogue]]
speaker = "クロト"
# 「聞き込みを終えて、時間が余ってたからな」
line = "「聞き込みを終えて、時間が余ってたからな」"

[[dialogue]]
speaker = "unk"
# 他のみんなの手を煩わせるわけにもいかなかった──
line = "他のみんなの手を煩わせるわけにもいかなかった──"

[[dialogue]]
speaker = "unk"
# 俺はそう付け足して、街へ戻ろうとする……。
line = "俺はそう付け足して、街へ戻ろうとする……。"

[[dialogue]]
speaker = "フィオナ"
# 「本当に、それだけでしょうか」
line = "「本当に、それだけでしょうか」"

[[dialogue]]
speaker = "unk"
# しかしフィオナは俺を阻むようにして、こちらをどっしりと睨んでいた。
line = "しかしフィオナは俺を阻むようにして、こちらをどっしりと睨んでいた。"

[[dialogue]]
speaker = "フィオナ"
# 「『森』を探していたんじゃないですか？」
line = "「『森』を探していたんじゃないですか？」"

[[dialogue]]
speaker = "クロト"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "フィオナ"
# 「図星ですね。お一人で──近くの森林地帯へ出向き、魔獣すら掃討しながらヴィーナスさんを探していた」
line = "「図星ですね。お一人で──近くの森林地帯へ出向き、魔獣すら掃討しながらヴィーナスさんを探していた」"

[[dialogue]]
speaker = "フィオナ"
# 「長老さんから聞きました。北方へ向かえば、手つかずの針葉樹林がいくつも広がっていると」
line = "「長老さんから聞きました。北方へ向かえば、手つかずの針葉樹林がいくつも広がっていると」"

[[dialogue]]
speaker = "unk"
# どうやらお見通しらしかった。俺は素直に白状する。
line = "どうやらお見通しらしかった。俺は素直に白状する。"

[[dialogue]]
speaker = "クロト"
# 「みんなで向かう前に、ある程度の目星はつけておいた方がいいかと思ってさ」
line = "「みんなで向かう前に、ある程度の目星はつけておいた方がいいかと思ってさ」"

[[dialogue]]
speaker = "クロト"
# 「レゾフの住人だって寄りつかないような地帯だ。前もって現場を見ておいたほうが安全だろ」
line = "「レゾフの住人だって寄りつかないような地帯だ。前もって現場を見ておいたほうが安全だろ」"

[[dialogue]]
speaker = "フィオナ"
# 「確かに──効率の面だけで言えば有益なことかもしれません。でも」
line = "「確かに──効率の面だけで言えば有益なことかもしれません。でも」"

[[dialogue]]
speaker = "フィオナ"
# 「ここは魔界。私たちの想像もつかない脅威が、どこに潜んでいるともしれないんです」
line = "「ここは魔界。私たちの想像もつかない脅威が、どこに潜んでいるともしれないんです」"

[[dialogue]]
speaker = "フィオナ"
# 「なのに……お一人で魔獣の巣を掃討するなんて、危険すぎます。緋宮会長の実力があったとしても！」
line = "「なのに……お一人で魔獣の巣を掃討するなんて、危険すぎます。緋宮会長の実力があったとしても！」"

[[dialogue]]
speaker = "クロト"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "フィオナ"
# 「──無理をしないでください。緋宮会長」
line = "「──無理をしないでください。緋宮会長」"

[[dialogue]]
speaker = "クロト"
# 「……っ」
line = "「……っ」"

[[dialogue]]
speaker = "unk"
# 接近したフィオナが──ぎゅっと俺の両手を握った。
line = "接近したフィオナが──ぎゅっと俺の両手を握った。"

[[dialogue]]
speaker = "unk"
# 冷え切った掌に、彼女の熱が伝わってくる。
line = "冷え切った掌に、彼女の熱が伝わってくる。"

[[dialogue]]
speaker = "フィオナ"
# 「ほら。両手にこんな傷をつけて……きっと激しい戦闘になったんですよね」
line = "「ほら。両手にこんな傷をつけて……きっと激しい戦闘になったんですよね」"

[[dialogue]]
speaker = "フィオナ"
# 「今日だって──ほとんど寝れていないはずです。昨日も不眠の状態だったのに」
line = "「今日だって──ほとんど寝れていないはずです。昨日も不眠の状態だったのに」"

[[dialogue]]
speaker = "クロト"
# 「……仮眠はしたさ。それに、俺は自前で回復だって……」
line = "「……仮眠はしたさ。それに、俺は自前で回復だって……」"

[[dialogue]]
speaker = "フィオナ"
# 「足りません。煌竜を倒し、黒騎士と戦って、ネビュラとも……消耗は過去にないほど<ruby=いちじる>著</ruby>しいはずなんです」
line = "「足りません。煌竜を倒し、黒騎士と戦って、ネビュラとも……消耗は過去にないほど<ruby>著<rt>いちじる</rt></ruby>しいはずなんです」"

[[dialogue]]
speaker = "フィオナ"
# 「昨日の夜もそうでした。マトイさんのことを気遣って、私たちを休ませながらも……緋宮会長は夜になると抜け出していた」
line = "「昨日の夜もそうでした。マトイさんのことを気遣って、私たちを休ませながらも……緋宮会長は夜になると抜け出していた」"

[[dialogue]]
speaker = "フィオナ"
# 「気持ちが先走ってしまうのはわかります。そんな中でも、星徒会長として仲間に気配りするところも尊敬します」
line = "「気持ちが先走ってしまうのはわかります。そんな中でも、星徒会長として仲間に気配りするところも尊敬します」"

[[dialogue]]
speaker = "フィオナ"
# 「ですが……もう少しくらい、私たちを頼ってくれてもいいんじゃないでしょうか。せっかくの仲間なんですから」
line = "「ですが……もう少しくらい、私たちを頼ってくれてもいいんじゃないでしょうか。せっかくの仲間なんですから」"

[[dialogue]]
speaker = "クロト"
# 「フィオナ……」
line = "「フィオナ……」"

[[dialogue]]
speaker = "フィオナ"
# 「私は少し前、計り知れない試練に見舞われて、自分一人ではどうしようもなくなった時、ヴィーナスさんならどうするのかを尋ねました」
line = "「私は少し前、計り知れない試練に見舞われて、自分一人ではどうしようもなくなった時、ヴィーナスさんならどうするのかを尋ねました」"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナスは、なんて……？」
line = "「ヴィーナスは、なんて……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ま、みんなに任せればいいんじゃない？　私たちって１人じゃないし♪」
line = "「ま、みんなに任せればいいんじゃない？　私たちって１人じゃないし♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私が頼ってるのはクロトだけじゃないもの。アナにもマトイにもサーシャさんにも、最近じゃ流星のみんなにだってお世話になってる」
line = "「私が頼ってるのはクロトだけじゃないもの。アナにもマトイにもサーシャさんにも、最近じゃ流星のみんなにだってお世話になってる」"

[[dialogue]]
speaker = "ヴィーナス"
# 「もちろんフィオナもね。だから──もし絶望的な未来が見えたら、お任せしちゃうかも！」
line = "「もちろんフィオナもね。だから──もし絶望的な未来が見えたら、お任せしちゃうかも！」"

[[dialogue]]
speaker = "クロト"
# 「ははっ……そりゃなんとも、ヴィーナスらしいセリフだ」
line = "「ははっ……そりゃなんとも、ヴィーナスらしいセリフだ」"

[[dialogue]]
speaker = "フィオナ"
# 「はい。私もとてもそう思います」
line = "「はい。私もとてもそう思います」"

[[dialogue]]
speaker = "フィオナ"
# 「自分にできないことは、全部できそうな仲間に丸投げ……それこそが、新星学園星徒会フィクサーの真の力なのでしょう」
line = "「自分にできないことは、全部できそうな仲間に丸投げ……それこそが、新星学園星徒会フィクサーの真の力なのでしょう」"

[[dialogue]]
speaker = "unk"
# 確かにその通りだ。
line = "確かにその通りだ。"

[[dialogue]]
speaker = "unk"
# ヴィーナスはいつも無茶振りで、唐突で、猪突猛進で……だけど、いつだって俺たち仲間を頼りにしていた。
line = "ヴィーナスはいつも無茶振りで、唐突で、猪突猛進で……だけど、いつだって俺たち仲間を頼りにしていた。"

[[dialogue]]
speaker = "unk"
# 俺はそれを彼女なりのわがままだと捉えていた。でも……
line = "俺はそれを彼女なりのわがままだと捉えていた。でも……"

[[dialogue]]
speaker = "クロト"
# 「……それで、いいのか」
line = "「……それで、いいのか」"

[[dialogue]]
speaker = "クロト"
# 「マトイやサーシャ先輩、それにフィオナたちを頼っても……」
line = "「マトイやサーシャ先輩、それにフィオナたちを頼っても……」"

[[dialogue]]
speaker = "フィオナ"
# 「もちろんです。私たちは別の学園ですが──今は運命共同体です」
line = "「もちろんです。私たちは別の学園ですが──今は運命共同体です」"

[[dialogue]]
speaker = "フィオナ"
# 「本当に大事な想いなら……抱え込まないで、仲間に打ち明けてください。私たちだってそれを背負えます」
line = "「本当に大事な想いなら……抱え込まないで、仲間に打ち明けてください。私たちだってそれを背負えます」"

[[dialogue]]
speaker = "クロト"
# 「フィオナ……ありがとう。そうかもな」
line = "「フィオナ……ありがとう。そうかもな」"

[[dialogue]]
speaker = "クロト"
# 「ちょっと──先走りすぎてたみたいだ。みんなに心配かけてちゃ本末転倒だな」
line = "「ちょっと──先走りすぎてたみたいだ。みんなに心配かけてちゃ本末転倒だな」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ。わかってくれればよいのです」
line = "「ええ。わかってくれればよいのです」"

[[dialogue]]
speaker = "unk"
# 凝り固まっていた考えが、フィオナの温かい言葉によって氷解していく気がした。
line = "凝り固まっていた考えが、フィオナの温かい言葉によって氷解していく気がした。"

[[dialogue]]
speaker = "クロト"
# 「それにしても……はは。フィオナにこんなことを言われるなんて、思わなかったよ」
line = "「それにしても……はは。フィオナにこんなことを言われるなんて、思わなかったよ」"

[[dialogue]]
speaker = "フィオナ"
# 「あ……」
line = "「あ……」"

[[dialogue]]
speaker = "フィオナ"
# 「仮面の少女アポロを抹殺します──願わくは、私自ら、この手で」
line = "「仮面の少女アポロを抹殺します──願わくは、私自ら、この手で」"

[[dialogue]]
speaker = "ヴィーナス"
# 「フィオナは──自分の役目に縛られすぎてる。無理をしすぎよ、どう見ても」
line = "「フィオナは──自分の役目に縛られすぎてる。無理をしすぎよ、どう見ても」"

[[dialogue]]
speaker = "ヴィーナス"
# 「本当はお姉さんのことを助けたいのに……みんなに迷惑がかかるからって、本心を押し殺してる。違う？」
line = "「本当はお姉さんのことを助けたいのに……みんなに迷惑がかかるからって、本心を押し殺してる。違う？」"

[[dialogue]]
speaker = "フィオナ"
# 「……お恥ずかしい。いつか、ヴィーナスさんにも指摘されました」
line = "「……お恥ずかしい。いつか、ヴィーナスさんにも指摘されました」"

[[dialogue]]
speaker = "フィオナ"
# 「自分のことがよく見えていない──未熟なのは、お互い様だったようですね」
line = "「自分のことがよく見えていない──未熟なのは、お互い様だったようですね」"

[[dialogue]]
speaker = "クロト"
# 「かもしれないな。人間としても、魔王としても」
line = "「かもしれないな。人間としても、魔王としても」"

[[dialogue]]
speaker = "クロト"
# 「でもそれは──まだまだ伸びしろがあるってことだろ」
line = "「でもそれは──まだまだ伸びしろがあるってことだろ」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ、そうですね」
line = "「ふふ、そうですね」"

[[dialogue]]
speaker = "フィオナ"
# 「それに──じっとしていられないのは私も同じ」
line = "「それに──じっとしていられないのは私も同じ」"

[[dialogue]]
speaker = "フィオナ"
# 「なら、未熟な者同士……せめて高め合うべきじゃないでしょうか」
line = "「なら、未熟な者同士……せめて高め合うべきじゃないでしょうか」"

[[dialogue]]
speaker = "クロト"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "クロト"
# 「手合わせ──ってことか？」
line = "「手合わせ──ってことか？」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ。鍛錬の相手というなら、魔獣よりも不足はないかと」
line = "「ええ。鍛錬の相手というなら、魔獣よりも不足はないかと」"

[[dialogue]]
speaker = "フィオナ"
# 「それに──今の私たちならきっと。お互いに、得られるものがあるはずです」
line = "「それに──今の私たちならきっと。お互いに、得られるものがあるはずです」"

[[dialogue]]
speaker = "クロト"
# 「今の……なるほどな」
line = "「今の……なるほどな」"

[[dialogue]]
speaker = "マグダレナ"
# 「魔王──そう呼ばれた存在の系譜です」
line = "「魔王──そう呼ばれた存在の系譜です」"

[[dialogue]]
speaker = "クロト"
# 「……わかった」
line = "「……わかった」"

[[dialogue]]
speaker = "クロト"
# 「敵は黒騎士──得体も知れない最強の相手だ。足りないものを埋め合うなら、今しかない」
line = "「敵は黒騎士──得体も知れない最強の相手だ。足りないものを埋め合うなら、今しかない」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ。磨き上げましょう──あの影に届くまで、私たちの刃を」
line = "「ええ。磨き上げましょう──あの影に届くまで、私たちの刃を」"
