[[dialogue]]
speaker = "unk"
# 第１話,再会,B
line = "第１話,再会,B"

[[dialogue]]
speaker = "サーシャ"
# 「♪～」
line = "「♪～」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふっ、高揚してるわね……自分でも不思議なくらい」
line = "「ふふっ、高揚してるわね……自分でも不思議なくらい」"

[[dialogue]]
speaker = "サーシャ"
# 「早く、放課後が来ないかしら」
line = "「早く、放課後が来ないかしら」"

[[dialogue]]
speaker = "unk"
# 世界の命運を分けたリクリエからしばらく。
line = "世界の命運を分けたリクリエからしばらく。"

[[dialogue]]
speaker = "unk"
# 星徒会がいつも通りの仕事をしていたある日の午後――
line = "星徒会がいつも通りの仕事をしていたある日の午後――"

[[dialogue]]
speaker = "サーシャ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ヴィーナス"
# 「サーシャさん、どうしたのかしら？　さっきから窓の外ばかり見てそわそわしてるけど」
line = "「サーシャさん、どうしたのかしら？　さっきから窓の外ばかり見てそわそわしてるけど」"

[[dialogue]]
speaker = "アナ"
# 「何かご用事ですか？　それとも今日のおやつが気になりますか？」
line = "「何かご用事ですか？　それとも今日のおやつが気になりますか？」"

[[dialogue]]
speaker = "マトイ"
# 「今日のおやつはわらびもちですよ。登校の途中で移動販売をやってて、つい買っちゃって。冷蔵庫でキンキンに冷えてます」
line = "「今日のおやつはわらびもちですよ。登校の途中で移動販売をやってて、つい買っちゃって。冷蔵庫でキンキンに冷えてます」"

[[dialogue]]
speaker = "サーシャ"
# 「そうなの～、それは楽しみね～……」
line = "「そうなの～、それは楽しみね～……」"

[[dialogue]]
speaker = "アナ"
# 「心ここにあらずですね。もしや、外にたい焼きの屋台でも……」
line = "「心ここにあらずですね。もしや、外にたい焼きの屋台でも……」"

[[dialogue]]
speaker = "アナ"
# 「あ……もしかして今日でしたか？」
line = "「あ……もしかして今日でしたか？」"

[[dialogue]]
speaker = "マトイ"
# 「え、なに？　今日って何か特別な日なの？」
line = "「え、なに？　今日って何か特別な日なの？」"

[[dialogue]]
speaker = "アナ"
# 「確か以前にサーシャ先輩が話してくださった、仲良しの方が天界から帰ってくる日だったかと」
line = "「確か以前にサーシャ先輩が話してくださった、仲良しの方が天界から帰ってくる日だったかと」"

[[dialogue]]
speaker = "サーシャ"
# 「は～い……アナちゃん、大正解～」
line = "「は～い……アナちゃん、大正解～」"

[[dialogue]]
speaker = "マトイ"
# 「ええと……その親友さんというのは、サーシャさんが会長をされていた時の副会長さんですよね？」
line = "「ええと……その親友さんというのは、サーシャさんが会長をされていた時の副会長さんですよね？」"

[[dialogue]]
speaker = "サーシャ"
# 「ん……そーなのよ～……」
line = "「ん……そーなのよ～……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だったらノンビリしてる場合じゃないわね！　サーシャさん、今日はもういいからあがってあがって！」
line = "「だったらノンビリしてる場合じゃないわね！　サーシャさん、今日はもういいからあがってあがって！」"

[[dialogue]]
speaker = "サーシャ"
# 「でも悪いわ～。仕事も残っているのに、なんだか申し訳なくなっちゃう」
line = "「でも悪いわ～。仕事も残っているのに、なんだか申し訳なくなっちゃう」"

[[dialogue]]
speaker = "アナ"
# 「リクリエも過ぎて、星徒会の仕事もひと段落しましたから。書類も私たちだけで片付けられますよ」
line = "「リクリエも過ぎて、星徒会の仕事もひと段落しましたから。書類も私たちだけで片付けられますよ」"

[[dialogue]]
speaker = "マトイ"
# 「それに緋宮くんだってお休みですからね。サーシャさんも遠慮せずに休んじゃってください」
line = "「それに緋宮くんだってお休みですからね。サーシャさんも遠慮せずに休んじゃってください」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうよ！　クロトなんて『妹から逃げるから来れない』なんて理由なんだから、サーシャさんが遠慮する必要なんてないわ！」
line = "「そうよ！　クロトなんて『妹から逃げるから来れない』なんて理由なんだから、サーシャさんが遠慮する必要なんてないわ！」"

[[dialogue]]
speaker = "アナ"
# 「どの妹さんなんでしょうね。やれやれ」
line = "「どの妹さんなんでしょうね。やれやれ」"

[[dialogue]]
speaker = "マトイ"
# 「あはは……本人的には死活問題なんだろうけど」
line = "「あはは……本人的には死活問題なんだろうけど」"

[[dialogue]]
speaker = "サーシャ"
# 「そうね、それじゃお言葉に甘えさせてもらおうかしら。今日は失礼するわね～」
line = "「そうね、それじゃお言葉に甘えさせてもらおうかしら。今日は失礼するわね～」"

[[dialogue]]
speaker = "マトイ"
# 「お疲れ様です」
line = "「お疲れ様です」"

[[dialogue]]
speaker = "ヴィーナス"
# 「また明日！」
line = "「また明日！」"

[[dialogue]]
speaker = "アナ"
# 「グッドラックです、サーシャ先輩」
line = "「グッドラックです、サーシャ先輩」"

[[dialogue]]
speaker = "サーシャ"
# 「お疲れ様～」
line = "「お疲れ様～」"

[[dialogue]]
speaker = "サーシャ"
# （時間は……うん、大丈夫。ちょうどいい頃合いね）
line = "（時間は……うん、大丈夫。ちょうどいい頃合いね）"

[[dialogue]]
speaker = "サーシャ"
# （あの子、私のこと、すぐに気づいてくれるかしら？）
line = "（あの子、私のこと、すぐに気づいてくれるかしら？）"

[[dialogue]]
speaker = "サーシャ"
# （どうかしらね？　あれからだいぶ時間も経っちゃったし……）
line = "（どうかしらね？　あれからだいぶ時間も経っちゃったし……）"

[[dialogue]]
speaker = "サーシャ"
# （…………）
line = "（…………）"

[[dialogue]]
speaker = "サーシャ"
# （星徒会室に続く廊下を最初に通ったのは、先代星徒会長の指名を受けた時だったわね）
line = "（星徒会室に続く廊下を最初に通ったのは、先代星徒会長の指名を受けた時だったわね）"

[[dialogue]]
speaker = "サーシャ"
# （その次は、あの子とふたりで……気がつけば時間は積み重なっていくのね）
line = "（その次は、あの子とふたりで……気がつけば時間は積み重なっていくのね）"

[[dialogue]]
speaker = "サーシャ"
# （あの時は今に繋がって、今も未来に繋がって……）
line = "（あの時は今に繋がって、今も未来に繋がって……）"

[[dialogue]]
speaker = "サーシャ"
# （そうして私も卒業して、その頃にはまた新しい星徒会がここを通るのね～）
line = "（そうして私も卒業して、その頃にはまた新しい星徒会がここを通るのね～）"

[[dialogue]]
speaker = "unk"
# 校門は生徒たちがまばらに、連れ立って下校していく。
line = "校門は生徒たちがまばらに、連れ立って下校していく。"

[[dialogue]]
speaker = "unk"
# リクリエによって大きなダメージを受けた流星市国だったが、学園付近は比較的無事であり、景観もそう変わっていない。
line = "リクリエによって大きなダメージを受けた流星市国だったが、学園付近は比較的無事であり、景観もそう変わっていない。"

[[dialogue]]
speaker = "サーシャ"
# （私たちが守った景色。変わり映え映えのない日常といってしまえばそれだけだけど……）
line = "（私たちが守った景色。変わり映え映えのない日常といってしまえばそれだけだけど……）"

[[dialogue]]
speaker = "サーシャ"
# 「ふふっ、感傷に浸りすぎかしら……こんな感覚、久しぶりかも」
line = "「ふふっ、感傷に浸りすぎかしら……こんな感覚、久しぶりかも」"

[[dialogue]]
speaker = "サーシャ"
# 「──あら」
line = "「──あら」"

[[dialogue]]
speaker = "？？？"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "サーシャ"
# （……向こうはまだ気付いてないみたいね～）
line = "（……向こうはまだ気付いてないみたいね～）"

[[dialogue]]
speaker = "サーシャ"
# （というか久しぶりの流星市国にウキウキみたい。声をかけてあげないと気づいてもらえないかしら？）
line = "（というか久しぶりの流星市国にウキウキみたい。声をかけてあげないと気づいてもらえないかしら？）"

[[dialogue]]
speaker = "サーシャ"
# 「も～……仕方ないんだから」
line = "「も～……仕方ないんだから」"

[[dialogue]]
speaker = "サーシャ"
# 「相変わらずね、シルヴィ」
line = "「相変わらずね、シルヴィ」"

[[dialogue]]
speaker = "シルヴィ"
# 「えっ、あ！？　サーシャ！？」
line = "「えっ、あ！？　サーシャ！？」"

[[dialogue]]
speaker = "サーシャ"
# 「おかえりなさい。あなたの帰りを、ずっと待ってたわ」
line = "「おかえりなさい。あなたの帰りを、ずっと待ってたわ」"
