[[dialogue]]
speaker = "unk"
# 第６話,逃げるが勝ちってね,B
line = "第６話,逃げるが勝ちってね,B"

[[dialogue]]
speaker = "ヨミ"
# 「爆裂ーっ！」
line = "「爆裂ーっ！」"

[[dialogue]]
speaker = "鏡像"
# 「…………！」
line = "「…………！」"

[[dialogue]]
speaker = "せつな"
# 「これにて終いにござる！」
line = "「これにて終いにござる！」"

[[dialogue]]
speaker = "鏡像"
# 「…………！」
line = "「…………！」"

[[dialogue]]
speaker = "湖の魔女"
# 「あら、やられてしまいましたか」
line = "「あら、やられてしまいましたか」"

[[dialogue]]
speaker = "美鶴"
# 「せつなもヨミーも、やるねー」
line = "「せつなもヨミーも、やるねー」"

[[dialogue]]
speaker = "ヨミ"
# 「お褒めいただき感謝です！」
line = "「お褒めいただき感謝です！」"

[[dialogue]]
speaker = "せつな"
# 「残ったのは、魔女殿だけでござるよ！　お覚悟！」
line = "「残ったのは、魔女殿だけでござるよ！　お覚悟！」"

[[dialogue]]
speaker = "美鶴"
# 「これで終わりなら楽なんだけどね」
line = "「これで終わりなら楽なんだけどね」"

[[dialogue]]
speaker = "湖の魔女"
# 「あなたは次の展開が予想できているようですね。そう、私が呼び出したのはただの鏡像です」
line = "「あなたは次の展開が予想できているようですね。そう、私が呼び出したのはただの鏡像です」"

[[dialogue]]
speaker = "湖の魔女"
# 「私の魔法は、鏡に写した者を、鏡像として呼び出すことができます。つまり──出なさい」
line = "「私の魔法は、鏡に写した者を、鏡像として呼び出すことができます。つまり──出なさい」"

[[dialogue]]
speaker = "せつな"
# 「あの愛くるしいくのいち、どこかで見覚えが……？」
line = "「あの愛くるしいくのいち、どこかで見覚えが……？」"

[[dialogue]]
speaker = "ヨミ"
# 「こやっ！？　あれって私ですよね！？」
line = "「こやっ！？　あれって私ですよね！？」"

[[dialogue]]
speaker = "美鶴"
# 「あんたのお友達と戦ってる隙に、ふたりをコピーしたんだね」
line = "「あんたのお友達と戦ってる隙に、ふたりをコピーしたんだね」"

[[dialogue]]
speaker = "湖の魔女"
# 「ええ、よくできているでしょう？　お気に召したのならば幸いです」
line = "「ええ、よくできているでしょう？　お気に召したのならば幸いです」"

[[dialogue]]
speaker = "せつな"
# 「ぐぬぬぅ……偽物だと分かっていても、戦いづらいでござるな」
line = "「ぐぬぬぅ……偽物だと分かっていても、戦いづらいでござるな」"

[[dialogue]]
speaker = "ヨミ"
# 「でも、鏡像の動きは単調です。連携も取れていませんし、勝てない相手ではないですよ！」
line = "「でも、鏡像の動きは単調です。連携も取れていませんし、勝てない相手ではないですよ！」"

[[dialogue]]
speaker = "美鶴"
# 「うちはコピーしなかったんだね」
line = "「うちはコピーしなかったんだね」"

[[dialogue]]
speaker = "湖の魔女"
# 「だって、あなた、本気で戦ってないですよね？」
line = "「だって、あなた、本気で戦ってないですよね？」"

[[dialogue]]
speaker = "湖の魔女"
# 「あなたの持つその武器……管槍と言いましたか？　筒を用いて、その遠心力で突きの速度と威力を増幅させる」
line = "「あなたの持つその武器……管槍と言いましたか？　筒を用いて、その遠心力で突きの速度と威力を増幅させる」"

[[dialogue]]
speaker = "湖の魔女"
# 「その特性をまるで活かすことなく、あくまで様子見な戦い方。私の力を推し量っているみたいに」
line = "「その特性をまるで活かすことなく、あくまで様子見な戦い方。私の力を推し量っているみたいに」"

[[dialogue]]
speaker = "美鶴"
# 「ご名答です。聡明ですね」
line = "「ご名答です。聡明ですね」"

[[dialogue]]
speaker = "美鶴"
# 「そういうあんたも全然本気じゃないよね。ちょろっと攻める素振りは見せるけど、ずっと守りっぱなし」
line = "「そういうあんたも全然本気じゃないよね。ちょろっと攻める素振りは見せるけど、ずっと守りっぱなし」"

[[dialogue]]
speaker = "美鶴"
# 「鏡を使うくらいだから、反撃のカウンター狙い？　自分から攻めるのは苦手なのかと思ったけど……それもちょっと違うっぽい」
line = "「鏡を使うくらいだから、反撃のカウンター狙い？　自分から攻めるのは苦手なのかと思ったけど……それもちょっと違うっぽい」"

[[dialogue]]
speaker = "せつな"
# 「ヨミ殿、すまぬでござる！　てぃやぁーーーっ！」
line = "「ヨミ殿、すまぬでござる！　てぃやぁーーーっ！」"

[[dialogue]]
speaker = "ヨミ"
# 「謝ってる暇はないですよ！　せつなさん、第３陣、来ます！」
line = "「謝ってる暇はないですよ！　せつなさん、第３陣、来ます！」"

[[dialogue]]
speaker = "美鶴"
# 「またおかわり？　キリないね、これ」
line = "「またおかわり？　キリないね、これ」"

[[dialogue]]
speaker = "せつな"
# 「まだまだやれるでござるよ！」
line = "「まだまだやれるでござるよ！」"

[[dialogue]]
speaker = "美鶴"
# 「２人とも元気いっぱいだね。血気盛んなのはいいけど、そろそろここで逃げよっか」
line = "「２人とも元気いっぱいだね。血気盛んなのはいいけど、そろそろここで逃げよっか」"

[[dialogue]]
speaker = "ヨミ"
# 「こやっ！？　尻尾を巻いて逃げるんですか！？」
line = "「こやっ！？　尻尾を巻いて逃げるんですか！？」"

[[dialogue]]
speaker = "美鶴"
# 「逃げるのが嫌なら戦略的撤退？　戦ってみて分かったと思うけどさ、相手さん、かなり強いよ」
line = "「逃げるのが嫌なら戦略的撤退？　戦ってみて分かったと思うけどさ、相手さん、かなり強いよ」"

[[dialogue]]
speaker = "ヨミ"
# 「手ごわいですが、決して倒せないほどの相手では……」
line = "「手ごわいですが、決して倒せないほどの相手では……」"

[[dialogue]]
speaker = "美鶴"
# 「そりゃ倒せるよ。倒せるけどさ」
line = "「そりゃ倒せるよ。倒せるけどさ」"

[[dialogue]]
speaker = "美鶴"
# 「このまま戦い続けても、魔女さんは無限に鏡像を作るだけでしょ。敵は無限だけど、うちらの体力は無限じゃない」
line = "「このまま戦い続けても、魔女さんは無限に鏡像を作るだけでしょ。敵は無限だけど、うちらの体力は無限じゃない」"

[[dialogue]]
speaker = "せつな"
# 「なれば、そちらの魔女を先に倒せば！」
line = "「なれば、そちらの魔女を先に倒せば！」"

[[dialogue]]
speaker = "美鶴"
# 「そーだね。術士本人を倒したら、無限湧きが止まるってのがデフォだけど。この魔女さん自身も鏡像だからさ」
line = "「そーだね。術士本人を倒したら、無限湧きが止まるってのがデフォだけど。この魔女さん自身も鏡像だからさ」"

[[dialogue]]
speaker = "せつな"
# 「にゃんと！？　偽物とは思えぬクオリティでござるが」
line = "「にゃんと！？　偽物とは思えぬクオリティでござるが」"

[[dialogue]]
speaker = "美鶴"
# 「魔女さん本人の鏡像だからじゃない？　あんたを倒したところで、第二、第三の魔女さんが出てくるんでしょ？」
line = "「魔女さん本人の鏡像だからじゃない？　あんたを倒したところで、第二、第三の魔女さんが出てくるんでしょ？」"

[[dialogue]]
speaker = "湖の魔女"
# 「……へえ？　いつから気づいてたんです？」
line = "「……へえ？　いつから気づいてたんです？」"

[[dialogue]]
speaker = "美鶴"
# 「今さっき。だってあんた影ないじゃん」
line = "「今さっき。だってあんた影ないじゃん」"

[[dialogue]]
speaker = "湖の魔女"
# 「ええ、鏡像ですから」
line = "「ええ、鏡像ですから」"

[[dialogue]]
speaker = "湖の魔女"
# 「私は水鏡の魔女。そしてここは<ruby=ラーゴ・シエロ>鏡界の湖</ruby>。魔法の相性は最高です」
line = "「私は水鏡の魔女。そしてここは<ruby>鏡界の湖<rt>ラーゴ・シエロ</rt></ruby>。魔法の相性は最高です」"

[[dialogue]]
speaker = "湖の魔女"
# 「ゆえにここなら無尽蔵に鏡像を生み出すことが可能です。地の利はこちらにあります」
line = "「ゆえにここなら無尽蔵に鏡像を生み出すことが可能です。地の利はこちらにあります」"

[[dialogue]]
speaker = "美鶴"
# 「ほらね。別に、敵をぶっ潰してこいとは言われてないしさ。どっかの誰かが湖を占拠してるってことがわかれば十二分」
line = "「ほらね。別に、敵をぶっ潰してこいとは言われてないしさ。どっかの誰かが湖を占拠してるってことがわかれば十二分」"

[[dialogue]]
speaker = "せつな"
# 「生きて情報を持ち帰るのが先決……諜報活動の基本でござる」
line = "「生きて情報を持ち帰るのが先決……諜報活動の基本でござる」"

[[dialogue]]
speaker = "美鶴"
# 「そーゆーわけで、ね、魔女さん。うちらはここから退くからさ。もう手ぇ出さないでくれる？」
line = "「そーゆーわけで、ね、魔女さん。うちらはここから退くからさ。もう手ぇ出さないでくれる？」"

[[dialogue]]
speaker = "美鶴"
# 「結界壊しちゃったのは謝るから。この通り。ごめーんね」
line = "「結界壊しちゃったのは謝るから。この通り。ごめーんね」"

[[dialogue]]
speaker = "せつな"
# 「美鶴殿、ナチュラルに煽り性能高いでござるな」
line = "「美鶴殿、ナチュラルに煽り性能高いでござるな」"

[[dialogue]]
speaker = "ヨミ"
# 「火に油を注いでいるだけなのでは……？」
line = "「火に油を注いでいるだけなのでは……？」"

[[dialogue]]
speaker = "美鶴"
# 「いや、水に流してもらうつもりだけど」
line = "「いや、水に流してもらうつもりだけど」"

[[dialogue]]
speaker = "湖の魔女"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "せつな"
# 「水を打ったように黙ったでござるな」
line = "「水を打ったように黙ったでござるな」"

[[dialogue]]
speaker = "美鶴"
# 「どうかなー？　やっちゃったかなー？　呆れたわけでもドン引いたわけでもないといいんだけど」
line = "「どうかなー？　やっちゃったかなー？　呆れたわけでもドン引いたわけでもないといいんだけど」"

[[dialogue]]
speaker = "湖の魔女"
# 「……わかりました。取引成立です」
line = "「……わかりました。取引成立です」"

[[dialogue]]
speaker = "せつな"
# 「いいのでござるか！？」
line = "「いいのでござるか！？」"

[[dialogue]]
speaker = "湖の魔女"
# 「これ以上、交戦したところで、お互いに利はありませんからね。速やかに立ち去ってください」
line = "「これ以上、交戦したところで、お互いに利はありませんからね。速やかに立ち去ってください」"

[[dialogue]]
speaker = "美鶴"
# 「話の分かる子で助かったー。じゃ、せつな、ヨミー、とっとと帰ろ。やー、終わった終わった」
line = "「話の分かる子で助かったー。じゃ、せつな、ヨミー、とっとと帰ろ。やー、終わった終わった」"

[[dialogue]]
speaker = "美鶴"
# 「あー、魔女さん。一応、言っとくけどさ」
line = "「あー、魔女さん。一応、言っとくけどさ」"

[[dialogue]]
speaker = "湖の魔女"
# 「なんでしょう。まだ何か？」
line = "「なんでしょう。まだ何か？」"

[[dialogue]]
speaker = "美鶴"
# 「うちらの鏡像で、悪さしないでね」
line = "「うちらの鏡像で、悪さしないでね」"

[[dialogue]]
speaker = "湖の魔女"
# 「……約束しましょう」
line = "「……約束しましょう」"

[[dialogue]]
speaker = "せつな"
# 「魔女殿が尾けてくる気配はないでござる。無事に脱出成功でござるな」
line = "「魔女殿が尾けてくる気配はないでござる。無事に脱出成功でござるな」"

[[dialogue]]
speaker = "ヨミ"
# 「いよいよリクリエが本格化しようという時に、おかしな敵まで登場するなんて……いったいどうしたらいいんですかー！？」
line = "「いよいよリクリエが本格化しようという時に、おかしな敵まで登場するなんて……いったいどうしたらいいんですかー！？」"

[[dialogue]]
speaker = "美鶴"
# 「まあまあ、ヨミー、悩んでもしゃーない。なるようにしかなんないよ」
line = "「まあまあ、ヨミー、悩んでもしゃーない。なるようにしかなんないよ」"

[[dialogue]]
speaker = "せつな"
# 「それはまあ、そうでござろうが……美鶴殿、軽いでござるなぁ」
line = "「それはまあ、そうでござろうが……美鶴殿、軽いでござるなぁ」"

[[dialogue]]
speaker = "美鶴"
# 「せつなの身のこなし程じゃーないよ」
line = "「せつなの身のこなし程じゃーないよ」"

[[dialogue]]
speaker = "せつな"
# 「えー、それほどでもないでござるよぉ」
line = "「えー、それほどでもないでござるよぉ」"

[[dialogue]]
speaker = "美鶴"
# 「世界が動き出してんなら、うちみたいなモブ子ちゃんがワーワー騒いだところで何も変わんないでしょ」
line = "「世界が動き出してんなら、うちみたいなモブ子ちゃんがワーワー騒いだところで何も変わんないでしょ」"

[[dialogue]]
speaker = "美鶴"
# 「世界の一大事は、当主様とかお嬢様みたいな大物やヒロインに任しときゃいーの。とっとと報告に帰るのが、うちらの仕事じゃん」
line = "「世界の一大事は、当主様とかお嬢様みたいな大物やヒロインに任しときゃいーの。とっとと報告に帰るのが、うちらの仕事じゃん」"

[[dialogue]]
speaker = "ヨミ"
# 「そう、ですね。自分の手が届くところを堅実に……」
line = "「そう、ですね。自分の手が届くところを堅実に……」"

[[dialogue]]
speaker = "せつな"
# 「ヨミ殿は１人で戦っているわけではないでござる。せつなたちが傍にいること、<ruby=ゆめゆめ>努々</ruby>忘れるべからずでござる」
line = "「ヨミ殿は１人で戦っているわけではないでござる。せつなたちが傍にいること、<ruby>努々<rt>ゆめゆめ</rt></ruby>忘れるべからずでござる」"

[[dialogue]]
speaker = "ヨミ"
# 「ありがとうございます、美鶴さん、せつなさん。少し落ち着きました」
line = "「ありがとうございます、美鶴さん、せつなさん。少し落ち着きました」"

[[dialogue]]
speaker = "せつな"
# 「しかしながら、得体の知れぬ魔女が潜伏していようとは。当主様もビックリされるでござろうな」
line = "「しかしながら、得体の知れぬ魔女が潜伏していようとは。当主様もビックリされるでござろうな」"

[[dialogue]]
speaker = "美鶴"
# 「どーだろ。たぶんだけど、そんなに驚かないんじゃない」
line = "「どーだろ。たぶんだけど、そんなに驚かないんじゃない」"

[[dialogue]]
speaker = "せつな"
# 「そのココロは？」
line = "「そのココロは？」"

[[dialogue]]
speaker = "美鶴"
# 「勘の良い当主様なら、ここに魔女がいることも、なんなら正体まで予想がついてたんじゃないかなって」
line = "「勘の良い当主様なら、ここに魔女がいることも、なんなら正体まで予想がついてたんじゃないかなって」"

[[dialogue]]
speaker = "ヨミ"
# 「あの魔女さん以上に、当主様は底がしれませんからね」
line = "「あの魔女さん以上に、当主様は底がしれませんからね」"

[[dialogue]]
speaker = "せつな"
# 「おっかないでござるな。にんともかんとも」
line = "「おっかないでござるな。にんともかんとも」"
