[[dialogue]]
speaker = "unk"
# 第６話,極星は輝いているか,B
line = "第６話,極星は輝いているか,B"

[[dialogue]]
speaker = "テルル"
# 『すべてを思い出したようですね、ルヴィネ』
line = "『すべてを思い出したようですね、ルヴィネ』"

[[dialogue]]
speaker = "ルヴィネ"
# 「テルル……みんなは今、どうしているの！？」
line = "「テルル……みんなは今、どうしているの！？」"

[[dialogue]]
speaker = "テルル"
# 『次々に複製される女神の幼体を相手に、抵抗を続けています。死の<ruby=みぎわ>水際</ruby>にいる貴女を庇いながら……』
line = "『次々に複製される女神の幼体を相手に、抵抗を続けています。死の<ruby>水際<rt>みぎわ</rt></ruby>にいる貴女を庇いながら……』"

[[dialogue]]
speaker = "テルル"
# 『しかしそれも時間の問題です。すでに魔王もヴィーナスも……他の者たちも限界が近づいています』
line = "『しかしそれも時間の問題です。すでに魔王もヴィーナスも……他の者たちも限界が近づいています』"

[[dialogue]]
speaker = "ルヴィネ"
# 「そんな……お願い、貴女の助力で何とか──」
line = "「そんな……お願い、貴女の助力で何とか──」"

[[dialogue]]
speaker = "テルル"
# 『申し訳ありません。今の私には、余力がないのです……』
line = "『申し訳ありません。今の私には、余力がないのです……』"

[[dialogue]]
speaker = "ルヴィネ"
# 「だったら……声だけでも届けて！」
line = "「だったら……声だけでも届けて！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「私のことは見捨てなさいと伝えて！　そうすれば少しでも余裕が……！」
line = "「私のことは見捨てなさいと伝えて！　そうすれば少しでも余裕が……！」"

[[dialogue]]
speaker = "テルル"
# 『ルヴィネ。貴女自身がわかっているはずです。その申し出を、あの子たちが受け入れると思うのですか？』
line = "『ルヴィネ。貴女自身がわかっているはずです。その申し出を、あの子たちが受け入れると思うのですか？』"

[[dialogue]]
speaker = "ルヴィネ"
# 「……っ！　だったら、貴女はなぜここに来たの……！？」
line = "「……っ！　だったら、貴女はなぜここに来たの……！？」"

[[dialogue]]
speaker = "テルル"
# 『貴女に死んでほしくない……生き延びて欲しいのです』
line = "『貴女に死んでほしくない……生き延びて欲しいのです』"

[[dialogue]]
speaker = "テルル"
# 『同じ父から生まれた姉妹である貴女を、このまま逝かせるのは忍びない。それに……』
line = "『同じ父から生まれた姉妹である貴女を、このまま逝かせるのは忍びない。それに……』"

[[dialogue]]
speaker = "テルル"
# 『貴女でなければできないことを頼みたい……そのために、私はここへ来ました──』
line = "『貴女でなければできないことを頼みたい……そのために、私はここへ来ました──』"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「対ディザスターハンド、相当な消耗だったようね？　私たちとの戦いはまだ始まったばかりだと言うのに、動きがどんどん鈍くなっているわよ」
line = "「対ディザスターハンド、相当な消耗だったようね？　私たちとの戦いはまだ始まったばかりだと言うのに、動きがどんどん鈍くなっているわよ」"

[[dialogue]]
speaker = "クロト"
# 「はぁっ……ぜぇっ、はぁっ！！」
line = "「はぁっ……ぜぇっ、はぁっ！！」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「しかし私の肉体も潮時かしら──新調しましょう」
line = "「しかし私の肉体も潮時かしら──新調しましょう」"

[[dialogue]]
speaker = "クロト"
# 「くそっ……きりが、ない……！」
line = "「くそっ……きりが、ない……！」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「クロトっ……ごめんなさい……！」
line = "「クロトっ……ごめんなさい……！」"

[[dialogue]]
speaker = "フィオナ（魔王）"
# 「げ、限界、ですっ……！」
line = "「げ、限界、ですっ……！」"

[[dialogue]]
speaker = "unk"
# ヴィーナスたちのノヴァフォームも時間切れ──俺ももう、立っているのがやっとだ……！
line = "ヴィーナスたちのノヴァフォームも時間切れ──俺ももう、立っているのがやっとだ……！"

[[dialogue]]
speaker = "煌嶺"
# 「壁にもならぬ騎士など邪魔なだけだ、下がれ」
line = "「壁にもならぬ騎士など邪魔なだけだ、下がれ」"

[[dialogue]]
speaker = "クロト"
# 「煌嶺……！？」
line = "「煌嶺……！？」"

[[dialogue]]
speaker = "煌嶺"
# 「ここまで手を焼かせる相手は久方ぶりだ。複製体と、妾の集めた魔物たちの軍勢──どちらが先に尽きるか試してやろう」
line = "「ここまで手を焼かせる相手は久方ぶりだ。複製体と、妾の集めた魔物たちの軍勢──どちらが先に尽きるか試してやろう」"

[[dialogue]]
speaker = "unk"
# ぐわ──と空気が歪み、煌嶺の背後に大量の魔獣たちがひしめき始める。
line = "ぐわ──と空気が歪み、煌嶺の背後に大量の魔獣たちがひしめき始める。"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「生物型に、機械型のリクリエモンスター。大型の魔獣に極星従騎……まるで百鬼夜行ね」
line = "「生物型に、機械型のリクリエモンスター。大型の魔獣に極星従騎……まるで百鬼夜行ね」"

[[dialogue]]
speaker = "煌嶺"
# 「千を優に超え、万に届く魔の軍勢を拝ませてやる。光栄に思え──<ruby=せんしばんこう>千熾万紅</ruby>！！」
line = "「千を優に超え、万に届く魔の軍勢を拝ませてやる。光栄に思え──<ruby>千熾万紅<rt>せんしばんこう</rt></ruby>！！」"

[[dialogue]]
speaker = "unk"
# 煌嶺の戦闘力はすさまじいの一言だが、無限とも言えるホロウが相手ではいつかは押し切られてしまう。
line = "煌嶺の戦闘力はすさまじいの一言だが、無限とも言えるホロウが相手ではいつかは押し切られてしまう。"

[[dialogue]]
speaker = "unk"
# 俺も渾身の星力を注ぎ直し、戦線に復帰しなくては──！！
line = "俺も渾身の星力を注ぎ直し、戦線に復帰しなくては──！！"

[[dialogue]]
speaker = "unk"
# テルルが頼みたいこと。その想いはくみ取れる──けれど。
line = "テルルが頼みたいこと。その想いはくみ取れる──けれど。"

[[dialogue]]
speaker = "ルヴィネ"
# 「──無理よ。今さら私に、そんな大役……」
line = "「──無理よ。今さら私に、そんな大役……」"

[[dialogue]]
speaker = "テルル"
# 『貴女はもう、創造神の傀儡ではありません。意思を持ち、願いを抱き、作り物でしかなかった命を輝かせた──１人の貴い天使です』
line = "『貴女はもう、創造神の傀儡ではありません。意思を持ち、願いを抱き、作り物でしかなかった命を輝かせた──１人の貴い天使です』"

[[dialogue]]
speaker = "テルル"
# 『そんな貴女だからこそ託したい。だからどうか、生き延びてください。息を吹き返し、現実世界への帰還を果たすのです』
line = "『そんな貴女だからこそ託したい。だからどうか、生き延びてください。息を吹き返し、現実世界への帰還を果たすのです』"

[[dialogue]]
speaker = "ルヴィネ"
# 「でも、どうやって……？」
line = "「でも、どうやって……？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「わかるのよ、テルル。今こうしている間も……私は失われ続けている……」
line = "「わかるのよ、テルル。今こうしている間も……私は失われ続けている……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「命を繋ぎ留められない……それにもし戻ったとしても、今の私には何もない……！」
line = "「命を繋ぎ留められない……それにもし戻ったとしても、今の私には何もない……！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「霊力はもうないの！　みんなどころか、自分の身だって守れない……役立たずなのよ！」
line = "「霊力はもうないの！　みんなどころか、自分の身だって守れない……役立たずなのよ！」"

[[dialogue]]
speaker = "テルル"
# 『星に願いを届けて──嘘を真にするのです』
line = "『星に願いを届けて──嘘を真にするのです』"

[[dialogue]]
speaker = "テルル"
# 『私は強き想いを抱くヒトの子らのために、夜空に星々を浮かべました……』
line = "『私は強き想いを抱くヒトの子らのために、夜空に星々を浮かべました……』"

[[dialogue]]
speaker = "テルル"
# 『守護の星は──私が授けているものではないのです。あくまでヒトと星々の橋渡しを、取り計らったにすぎません』
line = "『守護の星は──私が授けているものではないのです。あくまでヒトと星々の橋渡しを、取り計らったにすぎません』"

[[dialogue]]
speaker = "テルル"
# 『ですから……全ては貴女次第。どうか、どうか戻ってきてください。ルヴィネ……』
line = "『ですから……全ては貴女次第。どうか、どうか戻ってきてください。ルヴィネ……』"

[[dialogue]]
speaker = "ルヴィネ"
# 「──テルル！　待って、そんなこと……！！」
line = "「──テルル！　待って、そんなこと……！！」"

[[dialogue]]
speaker = "unk"
# ──テルルの声が聴こえなくなった。
line = "──テルルの声が聴こえなくなった。"

[[dialogue]]
speaker = "unk"
# 彼女は本当に消耗している──本当なら自分に会いに来るなど、とてもできないほどに弱り果てていた。
line = "彼女は本当に消耗している──本当なら自分に会いに来るなど、とてもできないほどに弱り果てていた。"

[[dialogue]]
speaker = "unk"
# それなのに、声を届けに来てくれた。
line = "それなのに、声を届けに来てくれた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「……星に、願いを？」
line = "「……星に、願いを？」"

[[dialogue]]
speaker = "unk"
# 夜空を見上げることが大嫌いだった。
line = "夜空を見上げることが大嫌いだった。"

[[dialogue]]
speaker = "ルヴィネ"
# 「嘘を……真に…………？」
line = "「嘘を……真に…………？」"

[[dialogue]]
speaker = "unk"
# 己の嘘を、咎められているような気がして──だから目を背けていた。
line = "己の嘘を、咎められているような気がして──だから目を背けていた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………ポラリス」
line = "「…………ポラリス」"

[[dialogue]]
speaker = "unk"
# 私の声は、届くのだろうか？
line = "私の声は、届くのだろうか？"

[[dialogue]]
speaker = "unk"
# あまりに虫が良すぎることは理解している。どの面を下げて、となじられて当然──だけど。
line = "あまりに虫が良すぎることは理解している。どの面を下げて、となじられて当然──だけど。"

[[dialogue]]
speaker = "ルヴィネ"
# 「お願い……私に……愛しい世界を……」
line = "「お願い……私に……愛しい世界を……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「大好きな友達を……守る力を…………！！」
line = "「大好きな友達を……守る力を…………！！」"

[[dialogue]]
speaker = "unk"
# どうか、私に──
line = "どうか、私に──"

[[dialogue]]
speaker = "ベアトリス"
# 「……っ！？　ルヴィが──！」
line = "「……っ！？　ルヴィが──！」"

[[dialogue]]
speaker = "unk"
# 瞳は閉ざされ、脈も呼吸も止めていたルヴィネの右腕が──持ち上がる。
line = "瞳は閉ざされ、脈も呼吸も止めていたルヴィネの右腕が──持ち上がる。"

[[dialogue]]
speaker = "トリュファイナ"
# 「目が覚めた……わけではない──いったい……！？」
line = "「目が覚めた……わけではない──いったい……！？」"

[[dialogue]]
speaker = "unk"
# その華奢な手のひらは、何かを掴み取ろうとするように天空へ向かって伸ばされて──
line = "その華奢な手のひらは、何かを掴み取ろうとするように天空へ向かって伸ばされて──"

[[dialogue]]
speaker = "チナ"
# 「ルヴィ……！？」
line = "「ルヴィ……！？」"

[[dialogue]]
speaker = "グレイス"
# 「あっ──！？」
line = "「あっ──！？」"

[[dialogue]]
speaker = "unk"
# 天使の少女の制服に忍ばせられていたものが。
line = "天使の少女の制服に忍ばせられていたものが。"

[[dialogue]]
speaker = "レティシア"
# 「────綺麗」
line = "「────綺麗」"

[[dialogue]]
speaker = "unk"
# 偽りの象徴であったはずのセレスティアが、爆発的な閃光を巻き起こす──
line = "偽りの象徴であったはずのセレスティアが、爆発的な閃光を巻き起こす──"

[[dialogue]]
speaker = "ベアトリス"
# 「ここを使えばきっとアルタイルに行ける……はず！」
line = "「ここを使えばきっとアルタイルに行ける……はず！」"

[[dialogue]]
speaker = "ベアトリス"
# 「何だか不思議だね。前に似たようなことがあった時は『待ちなさい、ベアト』って止められたのに」
line = "「何だか不思議だね。前に似たようなことがあった時は『待ちなさい、ベアト』って止められたのに」"

[[dialogue]]
speaker = "ベアトリス"
# 「でも、大好きな友達とのお別れなんて１回でたくさん。だからルヴィ──」
line = "「でも、大好きな友達とのお別れなんて１回でたくさん。だからルヴィ──」"

[[dialogue]]
speaker = "ベアトリス"
# 「今度は……一緒に行こっ！」
line = "「今度は……一緒に行こっ！」"

[[dialogue]]
speaker = "unk"
# ……ありがとう、ベアト。
line = "……ありがとう、ベアト。"

[[dialogue]]
speaker = "unk"
# そして、今度こそ────
line = "そして、今度こそ────"
