[[dialogue]]
speaker = "unk"
# 第７話,光の栞,B
line = "第７話,光の栞,B"

[[dialogue]]
speaker = "unk"
# ──それから。
line = "──それから。"

[[dialogue]]
speaker = "unk"
# 俺たちは同じ帰路を辿り、学園の敷地まで戻った。
line = "俺たちは同じ帰路を辿り、学園の敷地まで戻った。"

[[dialogue]]
speaker = "unk"
# 流星学園と新星学園は姉妹校──そして、流星学園のほうが姉の関係にあたる。
line = "流星学園と新星学園は姉妹校──そして、流星学園のほうが姉の関係にあたる。"

[[dialogue]]
speaker = "unk"
# ２校は同じ敷地に面していながら、授業でも顔を合わせることはないという静かなライバル関係にある。
line = "２校は同じ敷地に面していながら、授業でも顔を合わせることはないという静かなライバル関係にある。"

[[dialogue]]
speaker = "unk"
# もっともこれは学園の意図通りで、よりよい星騎士の育成がため、競争意識を持たせるために併設されたんだとか。
line = "もっともこれは学園の意図通りで、よりよい星騎士の育成がため、競争意識を持たせるために併設されたんだとか。"

[[dialogue]]
speaker = "unk"
# 事実ヴィーナスは対抗意識を燃やしっぱなしだったので効果てきめんと言えただろう。
line = "事実ヴィーナスは対抗意識を燃やしっぱなしだったので効果てきめんと言えただろう。"

[[dialogue]]
speaker = "unk"
# そこへいくと俺は新星に対しても新参だから……いささか帰属意識に欠けているのかもしれないな。
line = "そこへいくと俺は新星に対しても新参だから……いささか帰属意識に欠けているのかもしれないな。"

[[dialogue]]
speaker = "unk"
# 放課後。
line = "放課後。"

[[dialogue]]
speaker = "unk"
# 一度は解散になった俺たちだったが、星見会長の誘いによって再び集まっていた。
line = "一度は解散になった俺たちだったが、星見会長の誘いによって再び集まっていた。"

[[dialogue]]
speaker = "フィオナ"
# 「──改めてご足労いただきありがとうございます、緋宮会長。九浄さん」
line = "「──改めてご足労いただきありがとうございます、緋宮会長。九浄さん」"

[[dialogue]]
speaker = "クロト"
# 「構わないよ。むしろ俺たちのほうこそ話を聞きたかった」
line = "「構わないよ。むしろ俺たちのほうこそ話を聞きたかった」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ヴィーナスでいいわよ。流星のメンバーもなかなか濃ゆそうで気になっちゃったわね」
line = "「ヴィーナスでいいわよ。流星のメンバーもなかなか濃ゆそうで気になっちゃったわね」"

[[dialogue]]
speaker = "unk"
# そんな話をしながら２人に連れてこられたのは、学園敷地内でも俺が足を踏み入れたことのない場所だった。
line = "そんな話をしながら２人に連れてこられたのは、学園敷地内でも俺が足を踏み入れたことのない場所だった。"

[[dialogue]]
speaker = "クロト"
# 「ここは……大聖堂ファリア、だったか」
line = "「ここは……大聖堂ファリア、だったか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そういえば──クロトは大聖堂に来たことはあるのかしら？」
line = "「そういえば──クロトは大聖堂に来たことはあるのかしら？」"

[[dialogue]]
speaker = "クロト"
# 「小さい頃、何度か礼拝にはな。ただ──こんな平日に入ったのは初めてだ」
line = "「小さい頃、何度か礼拝にはな。ただ──こんな平日に入ったのは初めてだ」"

[[dialogue]]
speaker = "クロト"
# 「ここは……普通に両校の生徒が集まるんだな」
line = "「ここは……普通に両校の生徒が集まるんだな」"

[[dialogue]]
speaker = "unk"
# 大聖堂の景観は他と比べて特殊だった。
line = "大聖堂の景観は他と比べて特殊だった。"

[[dialogue]]
speaker = "unk"
# 流星学園と新星学園、どちらもの制服を着た生徒たちが一堂に会しているのは……今だからこそ、不思議に思う。
line = "流星学園と新星学園、どちらもの制服を着た生徒たちが一堂に会しているのは……今だからこそ、不思議に思う。"

[[dialogue]]
speaker = "ニャリオン"
# 「大聖堂は両校の中立地帯なのニャン！　ここでは特に制約なく交流することが許可されているのニャン！」
line = "「大聖堂は両校の中立地帯なのニャン！　ここでは特に制約なく交流することが許可されているのニャン！」"

[[dialogue]]
speaker = "キリカ"
# 「地理的にも流星、新星の中心に位置していますね」
line = "「地理的にも流星、新星の中心に位置していますね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ま、元々交流しちゃダメなんてルールはないけど……なんとなくここが丁度いい場所ってわけ♪」
line = "「ま、元々交流しちゃダメなんてルールはないけど……なんとなくここが丁度いい場所ってわけ♪」"

[[dialogue]]
speaker = "クロト"
# 「なるほど」
line = "「なるほど」"

[[dialogue]]
speaker = "unk"
# ただ、その両校どちらもの生徒から視線を向けられているのは……
line = "ただ、その両校どちらもの生徒から視線を向けられているのは……"

[[dialogue]]
speaker = "unk"
# 会長同士が顔を突き合わせているからなんだろうな。
line = "会長同士が顔を突き合わせているからなんだろうな。"

[[dialogue]]
speaker = "フィオナ"
# 「カフェへ行きましょうか。あそこなら、落ち着いてお話もできるはずです」
line = "「カフェへ行きましょうか。あそこなら、落ち着いてお話もできるはずです」"

[[dialogue]]
speaker = "unk"
# 大聖堂にはカフェテリアまで併設されていた。
line = "大聖堂にはカフェテリアまで併設されていた。"

[[dialogue]]
speaker = "unk"
# 俺たちはひとつのテーブルを囲み、会話を始める。
line = "俺たちはひとつのテーブルを囲み、会話を始める。"

[[dialogue]]
speaker = "クロト"
# 「こんな風になってるんだな……星見会長は、よくここに来るのか？」
line = "「こんな風になってるんだな……星見会長は、よくここに来るのか？」"

[[dialogue]]
speaker = "フィオナ"
# 「そう堅く仰らずとも。フィオナで構いませんよ、お２人とも」
line = "「そう堅く仰らずとも。フィオナで構いませんよ、お２人とも」"

[[dialogue]]
speaker = "クロト"
# 「わかった。フィオナ」
line = "「わかった。フィオナ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「相変わらず名前呼びのハードルが低いわね……」
line = "「相変わらず名前呼びのハードルが低いわね……」"

[[dialogue]]
speaker = "unk"
# ある程度フィオナとの距離感も掴めたところで、話題は彼女のそばにいた２人（１人と１匹？）へと移った。
line = "ある程度フィオナとの距離感も掴めたところで、話題は彼女のそばにいた２人（１人と１匹？）へと移った。"

[[dialogue]]
speaker = "フィオナ"
# 「２人とも。彼らに自己紹介をしてくれる？」
line = "「２人とも。彼らに自己紹介をしてくれる？」"

[[dialogue]]
speaker = "キリカ"
# 「はい」
line = "「はい」"

[[dialogue]]
speaker = "unk"
# そうフィオナに促されたのは、ずっと彼女に付き従っていた女性と──一匹だった。
line = "そうフィオナに促されたのは、ずっと彼女に付き従っていた女性と──一匹だった。"

[[dialogue]]
speaker = "キリカ"
# 「<ruby=こうづき>上月</ruby>キリカと申します。星見家の秘書……またフィオナ様のお付きを務めております。以後お見知り置きを」
line = "「<ruby>上月<rt>こうづき</rt></ruby>キリカと申します。星見家の秘書……またフィオナ様のお付きを務めております。以後お見知り置きを」"

[[dialogue]]
speaker = "ニャリオン"
# 「ワガハイはニャリオンである！　偉大なるフィオナ嬢に召喚された使い魔にして、第一の臣下なのニャン！」
line = "「ワガハイはニャリオンである！　偉大なるフィオナ嬢に召喚された使い魔にして、第一の臣下なのニャン！」"

[[dialogue]]
speaker = "フィオナ"
# 「キリカは星見家メイド隊のメイド長も務めています。ですので学生ではありませんが、うちと学園を行き来してもらっていますね」
line = "「キリカは星見家メイド隊のメイド長も務めています。ですので学生ではありませんが、うちと学園を行き来してもらっていますね」"

[[dialogue]]
speaker = "クロト"
# 「星見家……というと、流星教皇庁の──あの星見家だよな」
line = "「星見家……というと、流星教皇庁の──あの星見家だよな」"

[[dialogue]]
speaker = "キリカ"
# 「はい。フィオナ様のお父上──教皇様は、流星・新星学園の理事長も務められています」
line = "「はい。フィオナ様のお父上──教皇様は、流星・新星学園の理事長も務められています」"

[[dialogue]]
speaker = "クロト"
# 「（メイドに使い魔まで連れてるなんて……すごい人たちだな。流星の星徒会は）」
line = "「（メイドに使い魔まで連れてるなんて……すごい人たちだな。流星の星徒会は）」"

[[dialogue]]
speaker = "ヴィーナス"
# 「（ぐぬぬ……このまま引き下がるわけには……）」
line = "「（ぐぬぬ……このまま引き下がるわけには……）」"

[[dialogue]]
speaker = "ヴィーナス"
# 「（そうだ。いっそのこと、アナたちもクロトの使い魔ってことにしちゃう？）」
line = "「（そうだ。いっそのこと、アナたちもクロトの使い魔ってことにしちゃう？）」"

[[dialogue]]
speaker = "クロト"
# 「（みんなに怒られるよ……）」
line = "「（みんなに怒られるよ……）」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは流星に対してライバル心を燃やしていた。
line = "ヴィーナスは流星に対してライバル心を燃やしていた。"

[[dialogue]]
speaker = "unk"
# 彼女の九浄家も国内外に名を轟かせる『五名門』のひとつなのだが、どうも本人に家柄を誇る気はないらしい。
line = "彼女の九浄家も国内外に名を轟かせる『五名門』のひとつなのだが、どうも本人に家柄を誇る気はないらしい。"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ。では、お互いのこともわかったところで……本題と参りましょう」
line = "「ふふ。では、お互いのこともわかったところで……本題と参りましょう」"

[[dialogue]]
speaker = "クロト"
# 「……アステラだな。事態を未然に解決してくれて、俺たちとしては助かった」
line = "「……アステラだな。事態を未然に解決してくれて、俺たちとしては助かった」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ。何事もなくてよかった──のですが。少々、頭を悩ませることも」
line = "「ええ。何事もなくてよかった──のですが。少々、頭を悩ませることも」"

[[dialogue]]
speaker = "ヴィーナス"
# 「？　アステラは消したのに？」
line = "「？　アステラは消したのに？」"

[[dialogue]]
speaker = "unk"
# アステラはリクリエの影響によって生じるモンスターの巣だと聞いている。
line = "アステラはリクリエの影響によって生じるモンスターの巣だと聞いている。"

[[dialogue]]
speaker = "unk"
# 彼女たちもその認識に誤りはないようだが、それゆえのイレギュラーが発生したという。
line = "彼女たちもその認識に誤りはないようだが、それゆえのイレギュラーが発生したという。"

[[dialogue]]
speaker = "フィオナ"
# 「キリカ。例のものをくれる？」
line = "「キリカ。例のものをくれる？」"

[[dialogue]]
speaker = "キリカ"
# 「こちらです」
line = "「こちらです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「？」
line = "「？」"

[[dialogue]]
speaker = "クロト"
# 「これは……？」
line = "「これは……？」"

[[dialogue]]
speaker = "unk"
# メイドのキリカさんがテーブルの上に取り出したもの。
line = "メイドのキリカさんがテーブルの上に取り出したもの。"

[[dialogue]]
speaker = "unk"
# それは、白い羽の形をした栞だった。
line = "それは、白い羽の形をした栞だった。"

[[dialogue]]
speaker = "フィオナ"
# 「これは、私たちがあのアステラの最奥にて手に入れたもの。そして……」
line = "「これは、私たちがあのアステラの最奥にて手に入れたもの。そして……」"

[[dialogue]]
speaker = "フィオナ"
# 「その場にいたのはモンスターではなく──一人の堕天使でした」
line = "「その場にいたのはモンスターではなく──一人の堕天使でした」"
