[[dialogue]]
speaker = "unk"
# 第４話,バトルフォーム強化装置,B
line = "第４話,バトルフォーム強化装置,B"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「はい、これ。腰に巻いてね」
line = "「はい、これ。腰に巻いてね」"

[[dialogue]]
speaker = "ウェンディ"
# 「何です？　やたらとゴツゴツしたベルトのようですが……」
line = "「何です？　やたらとゴツゴツしたベルトのようですが……」"

[[dialogue]]
speaker = "ウェンディ"
# 「バックルのところに何かがセットできるようになっていますけど、こんな玩具みたいなもので本当に性能が向上するんですか？」
line = "「バックルのところに何かがセットできるようになっていますけど、こんな玩具みたいなもので本当に性能が向上するんですか？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「論より証拠、って言葉はあんま好きじゃないんだけど。まあ騙されたと思って使ってみてよ」
line = "「論より証拠、って言葉はあんま好きじゃないんだけど。まあ騙されたと思って使ってみてよ」"

[[dialogue]]
speaker = "ウェンディ"
# 「わかりました。うんしょ、と……」
line = "「わかりました。うんしょ、と……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「あー、ウェンディでも装着出来るように、ちゃーんとサイズは調整されてるよん♪」
line = "「あー、ウェンディでも装着出来るように、ちゃーんとサイズは調整されてるよん♪」"

[[dialogue]]
speaker = "ウェンディ"
# 「ひと言多いです！　つけましたけど、これでいいんですか？」
line = "「ひと言多いです！　つけましたけど、これでいいんですか？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「バッチリ！　それじゃ次はこの端末にウェンディの隊員コードを入力して」
line = "「バッチリ！　それじゃ次はこの端末にウェンディの隊員コードを入力して」"

[[dialogue]]
speaker = "ウェンディ"
# 「えーと……入力しましたよ」
line = "「えーと……入力しましたよ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「そしたらそれをバックルにセットしながら、アタシのアクションを真似して『変身っ』て叫びながら変身してみよう！」
line = "「そしたらそれをバックルにセットしながら、アタシのアクションを真似して『変身っ』て叫びながら変身してみよう！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「いくよ～♪　バッ！　バババッ！　へん……しんっ……！！」
line = "「いくよ～♪　バッ！　バババッ！　へん……しんっ……！！」"

[[dialogue]]
speaker = "ウェンディ"
# 「はぁ！？　そ、それ必要なんですか？」
line = "「はぁ！？　そ、それ必要なんですか？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「めっちゃ大事。星騎士たちだって変身する時、叫んでたりする子もいるでしょ？」
line = "「めっちゃ大事。星騎士たちだって変身する時、叫んでたりする子もいるでしょ？」"

[[dialogue]]
speaker = "ウェンディ"
# 「まあ、確かに……」
line = "「まあ、確かに……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「まんまじゃなくてもいいよ。多少のアレンジなら入れてもいいからね」
line = "「まんまじゃなくてもいいよ。多少のアレンジなら入れてもいいからね」"

[[dialogue]]
speaker = "ウェンディ"
# 「わかりました。コホン……では、いきます……」
line = "「わかりました。コホン……では、いきます……」"

[[dialogue]]
speaker = "ウェンディ"
# 「すぅ……はぁ……バッ！　ババババッ！　変身ですっ！！」
line = "「すぅ……はぁ……バッ！　ババババッ！　変身ですっ！！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「たははははははっ！　ウェンディ、カッコイイｗｗｗｗｗｗ！！」
line = "「たははははははっ！　ウェンディ、カッコイイｗｗｗｗｗｗ！！」"

[[dialogue]]
speaker = "ウェンディ"
# 「笑わないでくださいっ！　あなたやっぱり私を騙して――！」
line = "「笑わないでくださいっ！　あなたやっぱり私を騙して――！」"

[[dialogue]]
speaker = "ウェンディ"
# 「えっ！？」
line = "「えっ！？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「どう？　パワーアップした戦闘服の着心地は」
line = "「どう？　パワーアップした戦闘服の着心地は」"

[[dialogue]]
speaker = "ウェンディ"
# 「すごいです！　体感でも分かるくらい性能が向上しています！」
line = "「すごいです！　体感でも分かるくらい性能が向上しています！」"

[[dialogue]]
speaker = "ウェンディ"
# 「２００パーセントっていう数字も嘘じゃないかも……本当にすごい発明じゃありませんか、ツェツィーリエ！！」
line = "「２００パーセントっていう数字も嘘じゃないかも……本当にすごい発明じゃありませんか、ツェツィーリエ！！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「うんうん、ウェンディもようやくアタシのすごさを認める気になったわけね」
line = "「うんうん、ウェンディもようやくアタシのすごさを認める気になったわけね」"

[[dialogue]]
speaker = "ウェンディ"
# 「ええ、まあ……あとはコストの問題ですが、どのくらいになります？」
line = "「ええ、まあ……あとはコストの問題ですが、どのくらいになります？」"

[[dialogue]]
speaker = "ウェンディ"
# 「今回の発明は多少コストがかかったとしても、予算を確保したいほど有用な発明だと思っていますよ！」
line = "「今回の発明は多少コストがかかったとしても、予算を確保したいほど有用な発明だと思っていますよ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「お金的には、そうだね～。一本あたりこのくらいになるんだけど……」
line = "「お金的には、そうだね～。一本あたりこのくらいになるんだけど……」"

[[dialogue]]
speaker = "ウェンディ"
# 「むむ……それなりにかかりますね。でも許容範囲内です。これならきっと長官も前向きに考えてくださるでしょう」
line = "「むむ……それなりにかかりますね。でも許容範囲内です。これならきっと長官も前向きに考えてくださるでしょう」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ホント？　やったあ～♪」
line = "「ホント？　やったあ～♪」"

[[dialogue]]
speaker = "ウェンディ"
# 「私からも推しておきますよ」
line = "「私からも推しておきますよ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「たはは、財布の紐が硬いで有名なウェンディが珍しいね」
line = "「たはは、財布の紐が硬いで有名なウェンディが珍しいね」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「それじゃ気が変わらないうちに見積もりを出しておくから」
line = "「それじゃ気が変わらないうちに見積もりを出しておくから」"

[[dialogue]]
speaker = "ウェンディ"
# 「ええ、お願いします」
line = "「ええ、お願いします」"

[[dialogue]]
speaker = "ウェンディ"
# 「それにしても……これはどういう仕組みなんですか？　簡単に私にも分かるよう教えてくれませんか？」
line = "「それにしても……これはどういう仕組みなんですか？　簡単に私にも分かるよう教えてくれませんか？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「簡単にか～。うーん……クラウディア様の光の魔法を応用してるんだよ。鏡の反射を利用して魔力を増幅して戦闘服に注ぎ込んでる感じかな」
line = "「簡単にか～。うーん……クラウディア様の光の魔法を応用してるんだよ。鏡の反射を利用して魔力を増幅して戦闘服に注ぎ込んでる感じかな」"

[[dialogue]]
speaker = "ウェンディ"
# 「魔力を注ぎ込む……となるとある程度魔力の強さは必要そうですね」
line = "「魔力を注ぎ込む……となるとある程度魔力の強さは必要そうですね」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「そうね～、どうしてもある程度以上、魔力を持った者でないとダメっていう制限はあるね～」
line = "「そうね～、どうしてもある程度以上、魔力を持った者でないとダメっていう制限はあるね～」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「とはいえ、要求される出力や量はそれほど大きいものじゃないよ」
line = "「とはいえ、要求される出力や量はそれほど大きいものじゃないよ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「魔女なら大半が使えるだろうし、ネビュラのメンバーだったら誰が使っても問題ないんじゃないかな？」
line = "「魔女なら大半が使えるだろうし、ネビュラのメンバーだったら誰が使っても問題ないんじゃないかな？」"

[[dialogue]]
speaker = "ウェンディ"
# 「すごいです……ケチを付けるところがありませんね」
line = "「すごいです……ケチを付けるところがありませんね」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「でしょでしょ？　今回のはアタシ的にも自信作だからっ」
line = "「でしょでしょ？　今回のはアタシ的にも自信作だからっ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「きっと元老会の時代遅れどもも、この発明を見たら度肝を抜かれるだろうね～」
line = "「きっと元老会の時代遅れどもも、この発明を見たら度肝を抜かれるだろうね～」"

[[dialogue]]
speaker = "ウェンディ"
# 「ええ、ええ、想像しただけで愉快です。目を丸くして口をあんぐりさせている光景が目に浮かびますね。見ものですよ～、たっはっは～」
line = "「ええ、ええ、想像しただけで愉快です。目を丸くして口をあんぐりさせている光景が目に浮かびますね。見ものですよ～、たっはっは～」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「一緒にドヤ顔しまくってやろうぜ～、たははははは♪」
line = "「一緒にドヤ顔しまくってやろうぜ～、たははははは♪」"

[[dialogue]]
speaker = "セドナ"
# 「どうした、ずいぶんと盛り上がっているようだが？」
line = "「どうした、ずいぶんと盛り上がっているようだが？」"

[[dialogue]]
speaker = "ウェンディ"
# 「セドナ長官、もう大丈夫なんですか？　もう少しお休みになられていても……」
line = "「セドナ長官、もう大丈夫なんですか？　もう少しお休みになられていても……」"

[[dialogue]]
speaker = "セドナ"
# 「大丈夫だ、十分に休ませてもらった」
line = "「大丈夫だ、十分に休ませてもらった」"

[[dialogue]]
speaker = "セドナ"
# 「それよりも珍しいな。犬猿の仲であるウェンディとツェツィーリエが一緒になって盛り上がっているとは」
line = "「それよりも珍しいな。犬猿の仲であるウェンディとツェツィーリエが一緒になって盛り上がっているとは」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「たはは、実は極秘に行っていた研究がついに完成したんで、それを見せに来たんですよ～」
line = "「たはは、実は極秘に行っていた研究がついに完成したんで、それを見せに来たんですよ～」"

[[dialogue]]
speaker = "ウェンディ"
# 「長官、今回の発明は本当にすごいですよ！」
line = "「長官、今回の発明は本当にすごいですよ！」"

[[dialogue]]
speaker = "セドナ"
# 「ウェンディがそこまで言うなら余程のものだろうな」
line = "「ウェンディがそこまで言うなら余程のものだろうな」"

[[dialogue]]
speaker = "ウェンディ"
# 「そうなんです！　ご覧ください！　私が今着ている戦闘服はツェツィーリエの装置で能力が向上されているんですよ！」
line = "「そうなんです！　ご覧ください！　私が今着ている戦闘服はツェツィーリエの装置で能力が向上されているんですよ！」"

[[dialogue]]
speaker = "セドナ"
# 「なに？　……近くで見ても構わないか？」
line = "「なに？　……近くで見ても構わないか？」"

[[dialogue]]
speaker = "ウェンディ"
# 「ええ、どうぞご確認ください」
line = "「ええ、どうぞご確認ください」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「どーぞどーぞ、舐めるように見てやってくださいな～」
line = "「どーぞどーぞ、舐めるように見てやってくださいな～」"

[[dialogue]]
speaker = "ウェンディ"
# 「えっ……？　あ……ちょ、長官……そんな、近くで……熱い視線を……」
line = "「えっ……？　あ……ちょ、長官……そんな、近くで……熱い視線を……」"

[[dialogue]]
speaker = "セドナ"
# 「これはすごいな……触ってみてもいいか？」
line = "「これはすごいな……触ってみてもいいか？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「もっちろん♪」
line = "「もっちろん♪」"

[[dialogue]]
speaker = "ウェンディ"
# 「ふえっ！？　ちょっと待ってください！　さ、触るって、そんな、大胆なコトっ！　こ、困りますっ！！」
line = "「ふえっ！？　ちょっと待ってください！　さ、触るって、そんな、大胆なコトっ！　こ、困りますっ！！」"

[[dialogue]]
speaker = "セドナ"
# 「む……ダメなのか？」
line = "「む……ダメなのか？」"

[[dialogue]]
speaker = "ウェンディ"
# 「あ……いえ……ダメ、ではなくて……むしろ触って欲しいまでありますけど……」
line = "「あ……いえ……ダメ、ではなくて……むしろ触って欲しいまでありますけど……」"

[[dialogue]]
speaker = "セドナ"
# 「そうか、では、いいんだな？」
line = "「そうか、では、いいんだな？」"

[[dialogue]]
speaker = "ウェンディ"
# 「…………はい<emoji=heart04>　優しく、お願いします……」
line = "「…………はい<emoji=heart04>　優しく、お願いします……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「あ、でも、そろそろ時間切れかも？」
line = "「あ、でも、そろそろ時間切れかも？」"

[[dialogue]]
speaker = "ウェンディ"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "ウェンディ"
# 「きゃーーーーーーーーーーーーーーーーーーっ！！！！！！」
line = "「きゃーーーーーーーーーーーーーーーーーーっ！！！！！！」"

[[dialogue]]
speaker = "セドナ"
# 「……服が、消えてしまったようだが？」
line = "「……服が、消えてしまったようだが？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「時間制限あるんだよね、それが今抱えてる最大の問題点なのよ」
line = "「時間制限あるんだよね、それが今抱えてる最大の問題点なのよ」"

[[dialogue]]
speaker = "ウェンディ"
# 「なんでそれを先に言わないんですか！！！」
line = "「なんでそれを先に言わないんですか！！！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ごめんごめん♪」
line = "「ごめんごめん♪」"

[[dialogue]]
speaker = "ウェンディ"
# 「長官に全部見られた……私の裸……全部、見られちゃった……」
line = "「長官に全部見られた……私の裸……全部、見られちゃった……」"

[[dialogue]]
speaker = "セドナ"
# 「まあ……幸い、我々は女性同士だ。それほど気にすることはないだろう」
line = "「まあ……幸い、我々は女性同士だ。それほど気にすることはないだろう」"

[[dialogue]]
speaker = "ウェンディ"
# 「そうなんですけど～っ！　ふぇええええええええんっっ！！！」
line = "「そうなんですけど～っ！　ふぇええええええええんっっ！！！」"
