[[dialogue]]
speaker = "unk"
# 第９話,冥界の視座,B
line = "第９話,冥界の視座,B"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「ようやく仕留めたわ。２つの世界を指揮する、最も厄介な星騎士を……」
line = "「ようやく仕留めたわ。２つの世界を指揮する、最も厄介な星騎士を……」"

[[dialogue]]
speaker = "unk"
# 『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』の光弾により心の臓を貫かれ、魔王・緋宮クロトは絶命した。
line = "『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』の光弾により心の臓を貫かれ、魔王・緋宮クロトは絶命した。"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「…………パパ？」
line = "「…………パパ？」"

[[dialogue]]
speaker = "unk"
# 少年からの返事はない。すでに彼の髪色は黒髪へと戻り、戦闘服すらも制服へと立ち戻っている。
line = "少年からの返事はない。すでに彼の髪色は黒髪へと戻り、戦闘服すらも制服へと立ち戻っている。"

[[dialogue]]
speaker = "unk"
# 彼の傍らには、絶命の一撃と同時に砕かれたセレスティアが転がっており──全てが終わっていたことを、告げていた。
line = "彼の傍らには、絶命の一撃と同時に砕かれたセレスティアが転がっており──全てが終わっていたことを、告げていた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「……そんな」
line = "「……そんな」"

[[dialogue]]
speaker = "フィオナ（魔王）"
# 「緋宮、会長……？」
line = "「緋宮、会長……？」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「あ、あるわけない……こんなこと……だって、パパは魔王で……世界を救う、ヒーローなんだから……」
line = "「あ、あるわけない……こんなこと……だって、パパは魔王で……世界を救う、ヒーローなんだから……」"

[[dialogue]]
speaker = "unk"
# ヴィーナスがへたり込み、ぴくりとも動かない緋宮クロトを抱き上げる。
line = "ヴィーナスがへたり込み、ぴくりとも動かない緋宮クロトを抱き上げる。"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「パパ。目を、覚まして……お願い……ねぇ……！？」
line = "「パパ。目を、覚まして……お願い……ねぇ……！？」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「ラクシャ……！　治療をして！　マグダレナの権能を使えるんでしょう？　早く……！！」
line = "「ラクシャ……！　治療をして！　マグダレナの権能を使えるんでしょう？　早く……！！」"

[[dialogue]]
speaker = "ラクシャ"
# 「…………無理だ。守護天使の力で傷は癒やせても……失った命までは──」
line = "「…………無理だ。守護天使の力で傷は癒やせても……失った命までは──」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「そんな……な、何とかなるはずよ！　今までだって何度も奇蹟を起こしてきたもの！　今度だって、きっと──」
line = "「そんな……な、何とかなるはずよ！　今までだって何度も奇蹟を起こしてきたもの！　今度だって、きっと──」"

[[dialogue]]
speaker = "ラクシャ"
# 「…………ごめんよ、ヴィーナス」
line = "「…………ごめんよ、ヴィーナス」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「…………ぁ、ぁぁぁ、あぁあぁ──」
line = "「…………ぁ、ぁぁぁ、あぁあぁ──」"

[[dialogue]]
speaker = "unk"
# ヴィーナスの変身が、無意識のうちに解除される──戦う意志を、喪失した証だった。
line = "ヴィーナスの変身が、無意識のうちに解除される──戦う意志を、喪失した証だった。"

[[dialogue]]
speaker = "梨緒"
# 「ヴィーナス！　何をしている……立て！　まだ戦いは終わっていない！！　彼の遺志を、無駄にするつもりか！？」
line = "「ヴィーナス！　何をしている……立て！　まだ戦いは終わっていない！！　彼の遺志を、無駄にするつもりか！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「いや……いやよ……こんなの……いやぁ……」
line = "「いや……いやよ……こんなの……いやぁ……」"

[[dialogue]]
speaker = "梨緒"
# 「ヴィーナスッ！！」
line = "「ヴィーナスッ！！」"

[[dialogue]]
speaker = "unk"
# 梨緒が懸命に、途切れかける士気を繋ごうと声をかけるが……その言葉はもうヴィーナスには届かない。
line = "梨緒が懸命に、途切れかける士気を繋ごうと声をかけるが……その言葉はもうヴィーナスには届かない。"

[[dialogue]]
speaker = "unk"
# アルタイルとデネブの希望であった、救世の魔王が倒れたことが、遺された者たちの心を折っていく。
line = "アルタイルとデネブの希望であった、救世の魔王が倒れたことが、遺された者たちの心を折っていく。"

[[dialogue]]
speaker = "unk"
# 諦めの気持ちが、周りに侵食していく──
line = "諦めの気持ちが、周りに侵食していく──"

[[dialogue]]
speaker = "unk"
# 彼がいなくてはどうにもならない──その想いが、伝播していく。
line = "彼がいなくてはどうにもならない──その想いが、伝播していく。"

[[dialogue]]
speaker = "梨緒"
# 「みんな──しっかりしろ！　こんなところで諦めて、彼が喜ぶと思うのか！？」
line = "「みんな──しっかりしろ！　こんなところで諦めて、彼が喜ぶと思うのか！？」"

[[dialogue]]
speaker = "ジグ"
# （真っ暗闇の未来。そういうことだったか……）
line = "（真っ暗闇の未来。そういうことだったか……）"

[[dialogue]]
speaker = "ジグ"
# 「……………………終わりだ」
line = "「……………………終わりだ」"

[[dialogue]]
speaker = "クロト"
# （ここは……どこだ……？）
line = "（ここは……どこだ……？）"

[[dialogue]]
speaker = "クロト"
# （俺…………どうなったんだ……？）
line = "（俺…………どうなったんだ……？）"

[[dialogue]]
speaker = "unk"
# デネブに渡って、教皇庁前で『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』と対峙して──それで？
line = "デネブに渡って、教皇庁前で『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』と対峙して──それで？"

[[dialogue]]
speaker = "ラクシャ"
# 「────やぁ、会長」
line = "「────やぁ、会長」"

[[dialogue]]
speaker = "クロト"
# 「…………環？」
line = "「…………環？」"

[[dialogue]]
speaker = "ラクシャ"
# 「逢いに来たよ、最期だからね」
line = "「逢いに来たよ、最期だからね」"

[[dialogue]]
speaker = "ラクシャ"
# 「魂の管理はパテルの領分だけど……今この世界にいる彼女のコアはボクが持っている。だからボクの口から伝えるよ」
line = "「魂の管理はパテルの領分だけど……今この世界にいる彼女のコアはボクが持っている。だからボクの口から伝えるよ」"

[[dialogue]]
speaker = "ラクシャ"
# 「──きみは死んだ。もう、ボクたち守護天使の力でも、どうすることもできない……」
line = "「──きみは死んだ。もう、ボクたち守護天使の力でも、どうすることもできない……」"

[[dialogue]]
speaker = "ラクシャ"
# 「ここは冥界の視座──きみたちのいた現世と、死後の世界のはざまの場所だ」
line = "「ここは冥界の視座──きみたちのいた現世と、死後の世界のはざまの場所だ」"

[[dialogue]]
speaker = "ラクシャ"
# 「この冥界の視座に来た者が行く先は１つだけ。次の輪廻のために、進むしかない……」
line = "「この冥界の視座に来た者が行く先は１つだけ。次の輪廻のために、進むしかない……」"

[[dialogue]]
speaker = "クロト"
# 「環……待ってくれ。どうにか……どうにかならないのかっ？　パテルや、ラクシャの力を使って、現世に戻れないのか！？」
line = "「環……待ってくれ。どうにか……どうにかならないのかっ？　パテルや、ラクシャの力を使って、現世に戻れないのか！？」"

[[dialogue]]
speaker = "ラクシャ"
# 「魂の依り代となる肉体を作ることはできる。けれど、命はみんな１つきり。失えば、取り戻せない……」
line = "「魂の依り代となる肉体を作ることはできる。けれど、命はみんな１つきり。失えば、取り戻せない……」"

[[dialogue]]
speaker = "クロト"
# 「俺にはまだやらなくちゃいけないことがあるんだ……！　みんなを救える、わずかな時間だけでもいい！！」
line = "「俺にはまだやらなくちゃいけないことがあるんだ……！　みんなを救える、わずかな時間だけでもいい！！」"

[[dialogue]]
speaker = "クロト"
# 「デネブに……現世に戻してくれ！！　頼む──！！」
line = "「デネブに……現世に戻してくれ！！　頼む──！！」"

[[dialogue]]
speaker = "ラクシャ"
# 「……ボクの命なんかで代わりになるなら、喜んで渡したいところなんだけれどね」
line = "「……ボクの命なんかで代わりになるなら、喜んで渡したいところなんだけれどね」"

[[dialogue]]
speaker = "ラクシャ"
# 「……魂の色は人それぞれ違う。代替は利かないんだ」
line = "「……魂の色は人それぞれ違う。代替は利かないんだ」"

[[dialogue]]
speaker = "ラクシャ"
# 「きみの命は、きみだけのものだから……どうしようもないんだ……ごめんよ……」
line = "「きみの命は、きみだけのものだから……どうしようもないんだ……ごめんよ……」"

[[dialogue]]
speaker = "unk"
# 『ＸＥＬＯＳ』が真なる姿を再び、その無機質な立方体の中に収めた。
line = "『ＸＥＬＯＳ』が真なる姿を再び、その無機質な立方体の中に収めた。"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「魔王が死んだ今、脅威はもはやない──後は私たちとあの右腕にお任せください」
line = "「魔王が死んだ今、脅威はもはやない──後は私たちとあの右腕にお任せください」"

[[dialogue]]
speaker = "梨緒"
# 「くそっ……！！」
line = "「くそっ……！！」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「厄災、次の獲物はあれよ。守護天使ノルンごと、轢き潰しなさい」
line = "「厄災、次の獲物はあれよ。守護天使ノルンごと、轢き潰しなさい」"

[[dialogue]]
speaker = "unk"
# 絶命を免れない一撃が己に届く、その数瞬先を覗く梨緒は──
line = "絶命を免れない一撃が己に届く、その数瞬先を覗く梨緒は──"

[[dialogue]]
speaker = "梨緒"
# （避ける必要がない──これは！？）
line = "（避ける必要がない──これは！？）"

[[dialogue]]
speaker = "クラウディア"
# 「──何をしておるのだ、星騎士ども！！」
line = "「──何をしておるのだ、星騎士ども！！」"

[[dialogue]]
speaker = "梨緒"
# 「君たちは……ネビュラ！？」
line = "「君たちは……ネビュラ！？」"

[[dialogue]]
speaker = "セドナ"
# 「市街地はあらかた片付けた。助力に──、っ！？」
line = "「市街地はあらかた片付けた。助力に──、っ！？」"

[[dialogue]]
speaker = "リーリア（覚醒）"
# 「え……セン、パイ？」
line = "「え……セン、パイ？」"

[[dialogue]]
speaker = "unk"
# 事切れた緋宮クロトを抱き、嗚咽するヴィーナスを見つけたネビュラ陣営──
line = "事切れた緋宮クロトを抱き、嗚咽するヴィーナスを見つけたネビュラ陣営──"

[[dialogue]]
speaker = "リノ"
# 「……クロト？」
line = "「……クロト？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……おばあちゃん！　クロトが……パパが……！」
line = "「……おばあちゃん！　クロトが……パパが……！」"

[[dialogue]]
speaker = "リノ"
# 「…………そんな」
line = "「…………そんな」"

[[dialogue]]
speaker = "クラウディア"
# 「…………セドナ」
line = "「…………セドナ」"

[[dialogue]]
speaker = "セドナ"
# 「……はい、姫様」
line = "「……はい、姫様」"

[[dialogue]]
speaker = "クラウディア"
# 「仇を討つ。邪魔をするでない」
line = "「仇を討つ。邪魔をするでない」"

[[dialogue]]
speaker = "unk"
# 本来、セドナの役目はクラウディアを止めること。
line = "本来、セドナの役目はクラウディアを止めること。"

[[dialogue]]
speaker = "unk"
# リクリエの発生が確実ともなれば、魔女の森に逃げ帰ってやり過ごさねばならない。だが──
line = "リクリエの発生が確実ともなれば、魔女の森に逃げ帰ってやり過ごさねばならない。だが──"

[[dialogue]]
speaker = "セドナ"
# （今の姫様を止めるのは……無理だ）
line = "（今の姫様を止めるのは……無理だ）"

[[dialogue]]
speaker = "unk"
# 今クラウディアの邪魔をすれば、自分があの右腕よりも先に灰となることは明らかだった。
line = "今クラウディアの邪魔をすれば、自分があの右腕よりも先に灰となることは明らかだった。"

[[dialogue]]
speaker = "unk"
# ネビュラ構成員が束になっても本気のクラウディアに勝つことはできない。
line = "ネビュラ構成員が束になっても本気のクラウディアに勝つことはできない。"

[[dialogue]]
speaker = "クラウディア"
# 「あの腕も……『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』とやらも余が<ruby=たお>斃</ruby>す！！」
line = "「あの腕も……『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』とやらも余が<ruby>斃<rt>たお</rt></ruby>す！！」"

[[dialogue]]
speaker = "unk"
# そしてクラウディアは、魔女として若輩ではあったが、彼我の実力差を測れないほど愚かではない。
line = "そしてクラウディアは、魔女として若輩ではあったが、彼我の実力差を測れないほど愚かではない。"

[[dialogue]]
speaker = "unk"
# 自身の魔力を全て用いても敵うわけがないことくらい──承知していた。
line = "自身の魔力を全て用いても敵うわけがないことくらい──承知していた。"

[[dialogue]]
speaker = "クラウディア"
# 「……やらねばならん！　これは弔いぞ！！」
line = "「……やらねばならん！　これは弔いぞ！！」"

[[dialogue]]
speaker = "unk"
# 光の白杖を掲げたクラウディアが、ディザスターハンドに相対する。
line = "光の白杖を掲げたクラウディアが、ディザスターハンドに相対する。"

[[dialogue]]
speaker = "厄災の右腕"
# 「ギ──」
line = "「ギ──」"

[[dialogue]]
speaker = "クラウディア"
# 「む……？」
line = "「む……？」"

[[dialogue]]
speaker = "厄災の右腕"
# 「ギ──ガ、ガァアアア────！？！？」
line = "「ギ──ガ、ガァアアア────！？！？」"

[[dialogue]]
speaker = "unk"
# 突如、ディザスターハンドが暴れ始める。
line = "突如、ディザスターハンドが暴れ始める。"

[[dialogue]]
speaker = "unk"
# 元々、動く者すべてを抹殺する腕ではあったが──今は、壁や大地を手当たり次第に殴り続けるばかり。
line = "元々、動く者すべてを抹殺する腕ではあったが──今は、壁や大地を手当たり次第に殴り続けるばかり。"

[[dialogue]]
speaker = "クラウディア"
# 「な、何が……起こっているのだ？」
line = "「な、何が……起こっているのだ？」"

[[dialogue]]
speaker = "セドナ"
# 「我々を、狙わなくなっている……？　どういう、ことだ……？」
line = "「我々を、狙わなくなっている……？　どういう、ことだ……？」"

[[dialogue]]
speaker = "厄災の右腕"
# 「ガ、ガガガ────ギギ────！！」
line = "「ガ、ガガガ────ギギ────！！」"

[[dialogue]]
speaker = "リノ"
# 「……危ない、ヴィーナスちゃん！」
line = "「……危ない、ヴィーナスちゃん！」"

[[dialogue]]
speaker = "unk"
# 緋宮クロトの死体を抱いて泣くヴィーナスに右腕が伸ばされる──リノは庇うように２人を守ると。
line = "緋宮クロトの死体を抱いて泣くヴィーナスに右腕が伸ばされる──リノは庇うように２人を守ると。"

[[dialogue]]
speaker = "厄災の右腕"
# 「ガ、ギギギ！　ギ……ガガ……ガッ……！！」
line = "「ガ、ギギギ！　ギ……ガガ……ガッ……！！」"

[[dialogue]]
speaker = "unk"
# 掌の中にリノたちを収めつつ、握りつぶそうとはしない。
line = "掌の中にリノたちを収めつつ、握りつぶそうとはしない。"

[[dialogue]]
speaker = "unk"
# 厄災の右腕が、自らの意思で止めているのは明白だった。
line = "厄災の右腕が、自らの意思で止めているのは明白だった。"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「……？　壊れてしまったのかしら」
line = "「……？　壊れてしまったのかしら」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「元々狂ってはいたけれど……肝心な時に役立たずになるとはね」
line = "「元々狂ってはいたけれど……肝心な時に役立たずになるとはね」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「まあいいでしょう。もうこの腕に頼ることもないわ」
line = "「まあいいでしょう。もうこの腕に頼ることもないわ」"

[[dialogue]]
speaker = "厄災の右腕"
# 「ギ…………ゴ………………」
line = "「ギ…………ゴ………………」"

[[dialogue]]
speaker = "リノ"
# 「…………え？　なんて──」
line = "「…………え？　なんて──」"

[[dialogue]]
speaker = "リノ"
# （今……私の名前を……呼んだの…………？）
line = "（今……私の名前を……呼んだの…………？）"

[[dialogue]]
speaker = "ラクシャ"
# 「……逝こう、会長。ここに留まっても、何もない。何も起きないんだ」
line = "「……逝こう、会長。ここに留まっても、何もない。何も起きないんだ」"

[[dialogue]]
speaker = "クロト"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# 冥界の視座。死んだ俺の魂が、次の場所へ向かうための、通過点となる領域──
line = "冥界の視座。死んだ俺の魂が、次の場所へ向かうための、通過点となる領域──"

[[dialogue]]
speaker = "unk"
# 痛いほどの静寂に支配されたその空間に……
line = "痛いほどの静寂に支配されたその空間に……"

[[dialogue]]
speaker = "クロト"
# 「…………あの、光は？」
line = "「…………あの、光は？」"

[[dialogue]]
speaker = "ラクシャ"
# 「……光？」
line = "「……光？」"

[[dialogue]]
speaker = "クロト"
# 「ほら、向こうに──小さく、光ってる……」
line = "「ほら、向こうに──小さく、光ってる……」"

[[dialogue]]
speaker = "ラクシャ"
# 「…………どうして？　この場所は、何人にも侵すことができない個人の領域。その人の魂しか入ることのできない場所なのに……」
line = "「…………どうして？　この場所は、何人にも侵すことができない個人の領域。その人の魂しか入ることのできない場所なのに……」"

[[dialogue]]
speaker = "ラクシャ"
# 「あれは……キミを、呼んでる……？」
line = "「あれは……キミを、呼んでる……？」"

[[dialogue]]
speaker = "クロト"
# 「ああ。俺も、そんな気がする……」
line = "「ああ。俺も、そんな気がする……」"

[[dialogue]]
speaker = "unk"
# あの光は、俺を呼んでいる──
line = "あの光は、俺を呼んでいる──"

[[dialogue]]
speaker = "unk"
# 闇を掻いて、近づく──そして。
line = "闇を掻いて、近づく──そして。"

[[dialogue]]
speaker = "unk"
# その真っ白な光に包まれた、俺と環は──
line = "その真っ白な光に包まれた、俺と環は──"

[[dialogue]]
speaker = "unk"
# １人の男の意識を、覗き見ることになった。
line = "１人の男の意識を、覗き見ることになった。"
