[[dialogue]]
speaker = "unk"
# 第８話,ヘレナ様へのプレゼントだぴょん！,B
line = "第８話,ヘレナ様へのプレゼントだぴょん！,B"

[[dialogue]]
speaker = "ヴィーナス"
# 「蘭美……！？」
line = "「蘭美……！？」"

[[dialogue]]
speaker = "蘭美"
# 「さあ！　今こそ目覚めなさい、私のクリスマスフォームっ！！！」
line = "「さあ！　今こそ目覚めなさい、私のクリスマスフォームっ！！！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「戦闘服が覚醒した！？　やったわ、蘭美！　すごい力を感じるわよ！」
line = "「戦闘服が覚醒した！？　やったわ、蘭美！　すごい力を感じるわよ！」"

[[dialogue]]
speaker = "蘭美"
# 「さあ、お嬢様！　一気に蹴散らしてしまいましょう！」
line = "「さあ、お嬢様！　一気に蹴散らしてしまいましょう！」"

[[dialogue]]
speaker = "ガーディアン"
# 『標的ノエネルギー拡大ヲ確認。危険度レベルＳ──速ヤカニ排除シマス──』
line = "『標的ノエネルギー拡大ヲ確認。危険度レベルＳ──速ヤカニ排除シマス──』"

[[dialogue]]
speaker = "蘭美"
# 「させないわ！！」
line = "「させないわ！！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それがクリスマスフォームの力ね……ふふ、ワクワクさせてくれるじゃない！」
line = "「それがクリスマスフォームの力ね……ふふ、ワクワクさせてくれるじゃない！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私も負けないわよ！　そりゃぁああああっ！！！」
line = "「私も負けないわよ！　そりゃぁああああっ！！！」"

[[dialogue]]
speaker = "ガーディアン"
# 『排ジョ──』
line = "『排ジョ──』"

[[dialogue]]
speaker = "unk"
# ヴィーナスとクリスマスフォームの蘭美。
line = "ヴィーナスとクリスマスフォームの蘭美。"

[[dialogue]]
speaker = "unk"
# ２人は圧倒的な殲滅力で次々に現れるコピーガーディアンを次々に破壊していく。
line = "２人は圧倒的な殲滅力で次々に現れるコピーガーディアンを次々に破壊していく。"

[[dialogue]]
speaker = "蘭美"
# 「やぁああああああっ！！！！」
line = "「やぁああああああっ！！！！」"

[[dialogue]]
speaker = "蘭美"
# 「今よ、お屋敷への道が開けたわ！」
line = "「今よ、お屋敷への道が開けたわ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「オッケー、一気に突撃よ！」
line = "「オッケー、一気に突撃よ！」"

[[dialogue]]
speaker = "unk"
# 転がるようにして屋敷の廊下へ飛び込んだ。
line = "転がるようにして屋敷の廊下へ飛び込んだ。"

[[dialogue]]
speaker = "unk"
# そのまま息もつかずに廊下を駆け抜け……そして九浄ヘレナの待つ部屋へと突入する。
line = "そのまま息もつかずに廊下を駆け抜け……そして九浄ヘレナの待つ部屋へと突入する。"

[[dialogue]]
speaker = "unk"
# そこには美鶴、せつな──
line = "そこには美鶴、せつな──"

[[dialogue]]
speaker = "unk"
# ヨミ、閃──。
line = "ヨミ、閃──。"

[[dialogue]]
speaker = "unk"
# そして、ずらりと並んだメイト隊の前に、屋敷の主であるヘレナが立っていた。
line = "そして、ずらりと並んだメイト隊の前に、屋敷の主であるヘレナが立っていた。"

[[dialogue]]
speaker = "ヘレナ"
# 「さすがは蘭美にヴィーナス、あの警備網を突破してここまでたどり着くとはな」
line = "「さすがは蘭美にヴィーナス、あの警備網を突破してここまでたどり着くとはな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「残念ながらあの程度で私たちは止められないわ」
line = "「残念ながらあの程度で私たちは止められないわ」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふむ……ガーディアンの更なる強化も検討に入れねばならぬようだ」
line = "「ふむ……ガーディアンの更なる強化も検討に入れねばならぬようだ」"

[[dialogue]]
speaker = "蘭美"
# 「当主様」
line = "「当主様」"

[[dialogue]]
speaker = "ヘレナ"
# 「……どうやら戦闘服の起動には成功したようだな」
line = "「……どうやら戦闘服の起動には成功したようだな」"

[[dialogue]]
speaker = "蘭美"
# 「はい。時間はかかってしまいましたが、先程の戦いの中で……」
line = "「はい。時間はかかってしまいましたが、先程の戦いの中で……」"

[[dialogue]]
speaker = "ヘレナ"
# 「見ていたぞ。素晴らしい戦いぶりであった」
line = "「見ていたぞ。素晴らしい戦いぶりであった」"

[[dialogue]]
speaker = "ヘレナ"
# 「だがまだ完全に使いこなすまでには至っていない、引き出そうと思えばまだまだ力を引き出すことが出来る」
line = "「だがまだ完全に使いこなすまでには至っていない、引き出そうと思えばまだまだ力を引き出すことが出来る」"

[[dialogue]]
speaker = "蘭美"
# 「精進いたします」
line = "「精進いたします」"

[[dialogue]]
speaker = "蘭美"
# 「当主様……ささやかな物ではありますが、サンタクロースからのプレゼントです」
line = "「当主様……ささやかな物ではありますが、サンタクロースからのプレゼントです」"

[[dialogue]]
speaker = "ヘレナ"
# 「ありがとう、蘭美」
line = "「ありがとう、蘭美」"

[[dialogue]]
speaker = "ヘレナ"
# 「ほう……これは素晴らしい扇子だ」
line = "「ほう……これは素晴らしい扇子だ」"

[[dialogue]]
speaker = "蘭美"
# 「当主様がお持ちの扇子にくらぶべきもない品ですが、その蒐集のひとつにお加えください」
line = "「当主様がお持ちの扇子にくらぶべきもない品ですが、その蒐集のひとつにお加えください」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふふ、何を言うか……大切にするぞ、一番の宝として私のコレクションに加えさせてもらう」
line = "「ふふ、何を言うか……大切にするぞ、一番の宝として私のコレクションに加えさせてもらう」"

[[dialogue]]
speaker = "ヘレナ"
# 「それから、これはクリスマスカードだな？」
line = "「それから、これはクリスマスカードだな？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「へぇ、そんなもの用意してたんだ……エモいわね。ヘレナちゃん、せっかくだから蘭美に読んでもらったら？」
line = "「へぇ、そんなもの用意してたんだ……エモいわね。ヘレナちゃん、せっかくだから蘭美に読んでもらったら？」"

[[dialogue]]
speaker = "ヘレナ"
# 「それはいいな。蘭美、頼めるか？」
line = "「それはいいな。蘭美、頼めるか？」"

[[dialogue]]
speaker = "蘭美"
# 「かしこまりました」
line = "「かしこまりました」"

[[dialogue]]
speaker = "蘭美"
# 「──御当主、九浄ヘレナ様」
line = "「──御当主、九浄ヘレナ様」"

[[dialogue]]
speaker = "蘭美"
# 「メイドとして貴方の様な素晴らしい主にお仕えできたことを、何よりの幸運と思わぬ日はございません」
line = "「メイドとして貴方の様な素晴らしい主にお仕えできたことを、何よりの幸運と思わぬ日はございません」"

[[dialogue]]
speaker = "蘭美"
# 「それは私だけではなくメイド隊の皆が、いえ、屋敷にお仕えする全ての者の気持ちであると存じます」
line = "「それは私だけではなくメイド隊の皆が、いえ、屋敷にお仕えする全ての者の気持ちであると存じます」"

[[dialogue]]
speaker = "蘭美"
# 「大いなる感謝の気持ちを以って、この先もお仕えさせて頂きます」
line = "「大いなる感謝の気持ちを以って、この先もお仕えさせて頂きます」"

[[dialogue]]
speaker = "蘭美"
# 「貴方様の忠実なるメイド、羽宮蘭美」
line = "「貴方様の忠実なるメイド、羽宮蘭美」"

[[dialogue]]
speaker = "unk"
# 蘭美の言葉が終わると、九浄ヘレナは静かに──だが深く頷く。
line = "蘭美の言葉が終わると、九浄ヘレナは静かに──だが深く頷く。"

[[dialogue]]
speaker = "unk"
# そして、蘭美の方に手を置くと優しく声をかけた。
line = "そして、蘭美の方に手を置くと優しく声をかけた。"

[[dialogue]]
speaker = "ヘレナ"
# 「こちらこそ……今後ともよろしく頼むぞ、蘭美」
line = "「こちらこそ……今後ともよろしく頼むぞ、蘭美」"

[[dialogue]]
speaker = "蘭美"
# 「はい、当主様」
line = "「はい、当主様」"

[[dialogue]]
speaker = "unk"
# 周囲から拍手が巻き起こる。
line = "周囲から拍手が巻き起こる。"

[[dialogue]]
speaker = "unk"
# こうして、九浄家のクリスマスは第二次サンタ作戦の大成功と共に幕を閉じたのだった。
line = "こうして、九浄家のクリスマスは第二次サンタ作戦の大成功と共に幕を閉じたのだった。"
