[[dialogue]]
speaker = "unk"
# 第８話,ベガの記憶,B
line = "第８話,ベガの記憶,B"

[[dialogue]]
speaker = "ジグ"
# 「私の勝ちだよ、アガサ。これで次の星徒会長は私だね」
line = "「私の勝ちだよ、アガサ。これで次の星徒会長は私だね」"

[[dialogue]]
speaker = "梨緒"
# 「くっ……私の……負けだ」
line = "「くっ……私の……負けだ」"

[[dialogue]]
speaker = "ジグ"
# 「まぁ、元々私が会長の指名を受けていたんだけど」
line = "「まぁ、元々私が会長の指名を受けていたんだけど」"

[[dialogue]]
speaker = "ジグ"
# 「君が星徒会長は最強であるべきだと言うものだから、こうして御前試合じみた模擬戦を受けたんだ。結局、結果は変わらなかったね」
line = "「君が星徒会長は最強であるべきだと言うものだから、こうして御前試合じみた模擬戦を受けたんだ。結局、結果は変わらなかったね」"

[[dialogue]]
speaker = "梨緒"
# 「うっ……」
line = "「うっ……」"

[[dialogue]]
speaker = "ジグ"
# 「じゃあ、副会長はよろしくね、アガサ」
line = "「じゃあ、副会長はよろしくね、アガサ」"

[[dialogue]]
speaker = "梨緒"
# 「は……？　慰めのつもりか？」
line = "「は……？　慰めのつもりか？」"

[[dialogue]]
speaker = "ジグ"
# 「いいや。慰めなんかじゃないよ」
line = "「いいや。慰めなんかじゃないよ」"

[[dialogue]]
speaker = "ジグ"
# 「星徒会長は最も強い星騎士がなるものだ。では副会長はその次に強い星騎士がなるべきだろう？」
line = "「星徒会長は最も強い星騎士がなるものだ。では副会長はその次に強い星騎士がなるべきだろう？」"

[[dialogue]]
speaker = "ジグ"
# 「だから私は、君を副会長として任命するよ」
line = "「だから私は、君を副会長として任命するよ」"

[[dialogue]]
speaker = "梨緒"
# 「……情けのつもりなら受ける気はなかったが、了承した」
line = "「……情けのつもりなら受ける気はなかったが、了承した」"

[[dialogue]]
speaker = "梨緒"
# 「だが君が会長として不甲斐ない様を見せたら、容赦なくその座を奪わせてもらうからな」
line = "「だが君が会長として不甲斐ない様を見せたら、容赦なくその座を奪わせてもらうからな」"

[[dialogue]]
speaker = "ジグ"
# 「はは、それは気が抜けないな」
line = "「はは、それは気が抜けないな」"

[[dialogue]]
speaker = "ジグ"
# 「うん、アガサはそれでいいよ。私が油断しないように、目を光らせておいてくれ」
line = "「うん、アガサはそれでいいよ。私が油断しないように、目を光らせておいてくれ」"

[[dialogue]]
speaker = "梨緒"
# 「くっ……負けた……。紅茶には自信があったのに……」
line = "「くっ……負けた……。紅茶には自信があったのに……」"

[[dialogue]]
speaker = "ジグ"
# 「私のコーヒーの勝利だ。ま、厳正な審査の結果だから仕方ないね」
line = "「私のコーヒーの勝利だ。ま、厳正な審査の結果だから仕方ないね」"

[[dialogue]]
speaker = "梨緒"
# 「いつの間にコーヒーを淹れられるようになったんだ……！？　ジグがコーヒーを淹れているところなんて見たことなかったのに、どうやって……？」
line = "「いつの間にコーヒーを淹れられるようになったんだ……！？　ジグがコーヒーを淹れているところなんて見たことなかったのに、どうやって……？」"

[[dialogue]]
speaker = "ジグ"
# 「まぁ、勘かな」
line = "「まぁ、勘かな」"

[[dialogue]]
speaker = "梨緒"
# 「勘！？　そんなわけあるか！」
line = "「勘！？　そんなわけあるか！」"

[[dialogue]]
speaker = "梨緒"
# 「きっと何かの間違いだ！　私にも飲ませてみろ！　……ごくっ」
line = "「きっと何かの間違いだ！　私にも飲ませてみろ！　……ごくっ」"

[[dialogue]]
speaker = "梨緒"
# 「～～～っ……！　お、美味しい……！」
line = "「～～～っ……！　お、美味しい……！」"

[[dialogue]]
speaker = "梨緒"
# 「負けた……完敗だ……」
line = "「負けた……完敗だ……」"

[[dialogue]]
speaker = "ジグ"
# 「乾杯とかけてる？」
line = "「乾杯とかけてる？」"

[[dialogue]]
speaker = "梨緒"
# 「かけてない！！」
line = "「かけてない！！」"

[[dialogue]]
speaker = "ナターシャ"
# 「何、今の記憶？　いやアリーナで模擬戦してるのは、星徒会長を決める勝負なのはわかったけど」
line = "「何、今の記憶？　いやアリーナで模擬戦してるのは、星徒会長を決める勝負なのはわかったけど」"

[[dialogue]]
speaker = "梨緒"
# 「私の紅茶とジグのコーヒーで勝負した時の記憶だ」
line = "「私の紅茶とジグのコーヒーで勝負した時の記憶だ」"

[[dialogue]]
speaker = "ナターシャ"
# 「ほんと何してんのさ」
line = "「ほんと何してんのさ」"

[[dialogue]]
speaker = "梨緒"
# 「言っただろう。私が淹れた紅茶と、ジグが淹れたコーヒー、どちらの味がいいか勝負していたんだ」
line = "「言っただろう。私が淹れた紅茶と、ジグが淹れたコーヒー、どちらの味がいいか勝負していたんだ」"

[[dialogue]]
speaker = "ナターシャ"
# 「ベガって滅亡するくらいヤバかったんじゃないの？」
line = "「ベガって滅亡するくらいヤバかったんじゃないの？」"

[[dialogue]]
speaker = "梨緒"
# 「全てが全て戦いの記憶だったわけじゃない。リクリエが本格化する前は、ちゃんと日常もあった」
line = "「全てが全て戦いの記憶だったわけじゃない。リクリエが本格化する前は、ちゃんと日常もあった」"

[[dialogue]]
speaker = "梨緒"
# 「私にとっては忘れたくても忘れられない敗北の記憶だがな……！」
line = "「私にとっては忘れたくても忘れられない敗北の記憶だがな……！」"

[[dialogue]]
speaker = "ナターシャ"
# 「どーでもいー。心底どーでもいー。あ、どうでもよすぎて２回言っちゃった」
line = "「どーでもいー。心底どーでもいー。あ、どうでもよすぎて２回言っちゃった」"

[[dialogue]]
speaker = "ナターシャ"
# 「ジグはよく毎回勝負に付き合ってくれたね。ジグのことはいけ好かないけど、ちょっと同情するよ」
line = "「ジグはよく毎回勝負に付き合ってくれたね。ジグのことはいけ好かないけど、ちょっと同情するよ」"

[[dialogue]]
speaker = "ナターシャ"
# 「ま、このくらいの記憶ならどうってことないし、さっさと先に──」
line = "「ま、このくらいの記憶ならどうってことないし、さっさと先に──」"

[[dialogue]]
speaker = "フェアリー"
# 「──」
line = "「──」"

[[dialogue]]
speaker = "ナターシャ"
# 「あ、また出た」
line = "「あ、また出た」"

[[dialogue]]
speaker = "フェアリー"
# 「──」
line = "「──」"

[[dialogue]]
speaker = "ナターシャ"
# 「さて、今度は何を見せられることやら」
line = "「さて、今度は何を見せられることやら」"

[[dialogue]]
speaker = "梨緒"
# 「この前の中間テスト……私は５教科合わせて４８５点だ！　どうだ、ジグ！」
line = "「この前の中間テスト……私は５教科合わせて４８５点だ！　どうだ、ジグ！」"

[[dialogue]]
speaker = "ジグ"
# 「平均９７点か。やるね、アガサ。ちなみに私はこの通り」
line = "「平均９７点か。やるね、アガサ。ちなみに私はこの通り」"

[[dialogue]]
speaker = "梨緒"
# 「どれどれ……全教科１００点！？　そんなバカな！？」
line = "「どれどれ……全教科１００点！？　そんなバカな！？」"

[[dialogue]]
speaker = "梨緒"
# 「くっ……負けた……！　昨日のアステラ討伐でも、モンスターの撃破数で負けたばかりなのに……」
line = "「くっ……負けた……！　昨日のアステラ討伐でも、モンスターの撃破数で負けたばかりなのに……」"

[[dialogue]]
speaker = "ジグ"
# 「また私の勝ちだね。これで５００勝目かな？」
line = "「また私の勝ちだね。これで５００勝目かな？」"

[[dialogue]]
speaker = "梨緒"
# 「まだ４９６敗目だ！　次は……次こそは勝つからな！」
line = "「まだ４９６敗目だ！　次は……次こそは勝つからな！」"

[[dialogue]]
speaker = "ジグ"
# 「ふふ、楽しみにしているよ♪」
line = "「ふふ、楽しみにしているよ♪」"

[[dialogue]]
speaker = "ジグ"
# 「新星学園へ通信連絡。こちらレナーテ・Ｚ・サイフリート」
line = "「新星学園へ通信連絡。こちらレナーテ・Ｚ・サイフリート」"

[[dialogue]]
speaker = "ジグ"
# 「うん、モンスターの討伐は完了したよ。星徒会に被害はない。だけど──」
line = "「うん、モンスターの討伐は完了したよ。星徒会に被害はない。だけど──」"

[[dialogue]]
speaker = "梨緒"
# 「うぅっ……間に合わなかった……」
line = "「うぅっ……間に合わなかった……」"

[[dialogue]]
speaker = "ジグ"
# 「一般人と、初期対応にあたった星騎士に犠牲者が出た。保健委員も懸命に救護しようとしてくれたが……手の施しようがなかった」
line = "「一般人と、初期対応にあたった星騎士に犠牲者が出た。保健委員も懸命に救護しようとしてくれたが……手の施しようがなかった」"

[[dialogue]]
speaker = "梨緒"
# 「対応してくれた星騎士は、昨日校門で挨拶したばかりだった……」
line = "「対応してくれた星騎士は、昨日校門で挨拶したばかりだった……」"

[[dialogue]]
speaker = "梨緒"
# 「一般人の犠牲者の中には小さな子どももいた。家族もろとも、モンスターに<ruby=ひ>轢</ruby>き潰された……」
line = "「一般人の犠牲者の中には小さな子どももいた。家族もろとも、モンスターに<ruby>轢<rt>ひ</rt></ruby>き潰された……」"

[[dialogue]]
speaker = "ジグ"
# 「……ああ、残念だ。本当に」
line = "「……ああ、残念だ。本当に」"

[[dialogue]]
speaker = "ジグ"
# 「流星市国の内外で、モンスターの犠牲者が相次いでいる」
line = "「流星市国の内外で、モンスターの犠牲者が相次いでいる」"

[[dialogue]]
speaker = "ジグ"
# 「最近出現したモンスターは非常に高い攻撃力と凶暴性を持っていた。おそらく、この傾向は一過性のものではないだろう」
line = "「最近出現したモンスターは非常に高い攻撃力と凶暴性を持っていた。おそらく、この傾向は一過性のものではないだろう」"

[[dialogue]]
speaker = "梨緒"
# 「リクリエが近づいているから……？」
line = "「リクリエが近づいているから……？」"

[[dialogue]]
speaker = "ジグ"
# 「きっとそうだね。リクリエが本格的に近づいてくるにつれて、モンスターはより強力になり、出現頻度も上がっていくだろう」
line = "「きっとそうだね。リクリエが本格的に近づいてくるにつれて、モンスターはより強力になり、出現頻度も上がっていくだろう」"

[[dialogue]]
speaker = "梨緒"
# 「これからも、こんなことが起こるのか……！　今よりももっとたくさんの犠牲が……」
line = "「これからも、こんなことが起こるのか……！　今よりももっとたくさんの犠牲が……」"

[[dialogue]]
speaker = "梨緒"
# 「うぅ……くぅぅっ……！」
line = "「うぅ……くぅぅっ……！」"

[[dialogue]]
speaker = "ナターシャ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "梨緒"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ナターシャ"
# 「はぁ、思ったより効くなぁ……。ごめん、何か言ってあげたいんだけど、何も思い付かないや」
line = "「はぁ、思ったより効くなぁ……。ごめん、何か言ってあげたいんだけど、何も思い付かないや」"

[[dialogue]]
speaker = "ナターシャ"
# 「状況的に余裕がないからこれだけ聞くよ。まだ戦える、梨緒？」
line = "「状況的に余裕がないからこれだけ聞くよ。まだ戦える、梨緒？」"

[[dialogue]]
speaker = "梨緒"
# 「ああ……私なら大丈夫だ」
line = "「ああ……私なら大丈夫だ」"

[[dialogue]]
speaker = "ナターシャ"
# 「聞いといてなんだけど、あんまり大丈夫そうじゃないね。でも進むよ」
line = "「聞いといてなんだけど、あんまり大丈夫そうじゃないね。でも進むよ」"

[[dialogue]]
speaker = "unk"
# ガーディアンの動きを伺いながら神殿の中枢へと向かう。
line = "ガーディアンの動きを伺いながら神殿の中枢へと向かう。"

[[dialogue]]
speaker = "unk"
# 梨緒たちも、守りの固いところが神殿の重要部位だとにらんでいた。
line = "梨緒たちも、守りの固いところが神殿の重要部位だとにらんでいた。"

[[dialogue]]
speaker = "フェアリー"
# 「──」
line = "「──」"

[[dialogue]]
speaker = "ナターシャ"
# 「邪魔！」
line = "「邪魔！」"

[[dialogue]]
speaker = "unk"
# 急降下する隼のように、ナターシャが目にも止まらぬ速さでガーディアンを切り捨てる。
line = "急降下する隼のように、ナターシャが目にも止まらぬ速さでガーディアンを切り捨てる。"

[[dialogue]]
speaker = "フェアリー"
# 「──」
line = "「──」"

[[dialogue]]
speaker = "ナターシャ"
# 「次から次へと……！」
line = "「次から次へと……！」"

[[dialogue]]
speaker = "ナターシャ"
# 「邪魔だって言ってるでしょ！　梨緒もガンガン撃って！」
line = "「邪魔だって言ってるでしょ！　梨緒もガンガン撃って！」"

[[dialogue]]
speaker = "梨緒"
# 「ああ、わかっている……！」
line = "「ああ、わかっている……！」"

[[dialogue]]
speaker = "unk"
# 物量で押し潰すがごとく、梨緒とナターシャに殺到するガーディアン。
line = "物量で押し潰すがごとく、梨緒とナターシャに殺到するガーディアン。"

[[dialogue]]
speaker = "unk"
# ２人は手数で対抗するが、ガーディアンの１体が攻撃をすり抜けて接近する。
line = "２人は手数で対抗するが、ガーディアンの１体が攻撃をすり抜けて接近する。"

[[dialogue]]
speaker = "フェアリー"
# 「──」
line = "「──」"

[[dialogue]]
speaker = "ナターシャ"
# 「くっ……」
line = "「くっ……」"

[[dialogue]]
speaker = "梨緒"
# 「今……なんて……？」
line = "「今……なんて……？」"

[[dialogue]]
speaker = "ジグ"
# 「ロンドンが壊滅した。巨大なアステラに呑み込まれたそうだ」
line = "「ロンドンが壊滅した。巨大なアステラに呑み込まれたそうだ」"

[[dialogue]]
speaker = "ジグ"
# 「星徒会にも内々に連絡が入ったが、じきにメディアでも報道されるだろう」
line = "「星徒会にも内々に連絡が入ったが、じきにメディアでも報道されるだろう」"

[[dialogue]]
speaker = "梨緒"
# 「うぅ……うぅっ……」
line = "「うぅ……うぅっ……」"

[[dialogue]]
speaker = "ジグ"
# 「アガサ……」
line = "「アガサ……」"

[[dialogue]]
speaker = "梨緒"
# 「ロンドンには、家族がいるんだ……祖父と祖母が住んでいて……幼い頃一緒に遊んだ友達も……」
line = "「ロンドンには、家族がいるんだ……祖父と祖母が住んでいて……幼い頃一緒に遊んだ友達も……」"

[[dialogue]]
speaker = "梨緒"
# 「ぐすっ……ひぐっ、うぅっ……何も、できなかった……」
line = "「ぐすっ……ひぐっ、うぅっ……何も、できなかった……」"

[[dialogue]]
speaker = "梨緒"
# 「私たちが……私が弱いせいで……うぅ、ぅっ……ううぅっ……！」
line = "「私たちが……私が弱いせいで……うぅ、ぅっ……ううぅっ……！」"

[[dialogue]]
speaker = "ジグ"
# 「いつの間にか、流星市国の外にもモンスターやアステラが出現することが常識になってしまった」
line = "「いつの間にか、流星市国の外にもモンスターやアステラが出現することが常識になってしまった」"

[[dialogue]]
speaker = "ジグ"
# 「星騎士は何をやっているんだとまた言われそうだ。私たちも命を懸けて必死に戦っているのに。昨日もプリマステラが死んだばかりだ」
line = "「星騎士は何をやっているんだとまた言われそうだ。私たちも命を懸けて必死に戦っているのに。昨日もプリマステラが死んだばかりだ」"

[[dialogue]]
speaker = "梨緒"
# 「うぅ……ああ……あああぁっ……」
line = "「うぅ……ああ……あああぁっ……」"

[[dialogue]]
speaker = "ジグ"
# 「アガサ、ディザスターハンドとの決戦前にすまない。残念な知らせだ」
line = "「アガサ、ディザスターハンドとの決戦前にすまない。残念な知らせだ」"

[[dialogue]]
speaker = "ジグ"
# 「エリシアが死んだ」
line = "「エリシアが死んだ」"

[[dialogue]]
speaker = "梨緒"
# 「え……！？」
line = "「え……！？」"

[[dialogue]]
speaker = "ジグ"
# 「ああ。逃げ遅れた人々を守ろうとして、最期まで戦ったそうだ」
line = "「ああ。逃げ遅れた人々を守ろうとして、最期まで戦ったそうだ」"

[[dialogue]]
speaker = "梨緒"
# 「ああ……ああぁああああっ……！！」
line = "「ああ……ああぁああああっ……！！」"

[[dialogue]]
speaker = "梨緒"
# 「そんな……そんなことって……うぅ、ううぅっ……うっ……」
line = "「そんな……そんなことって……うぅ、ううぅっ……うっ……」"

[[dialogue]]
speaker = "梨緒"
# 「ぅっ……うぅっ……エリシアは、昔からの友人で……フィオナと一緒に、星術の練習もして……ひぐ……うぅぅっ……！」
line = "「ぅっ……うぅっ……エリシアは、昔からの友人で……フィオナと一緒に、星術の練習もして……ひぐ……うぅぅっ……！」"

[[dialogue]]
speaker = "ジグ"
# 「できればエリシアの弔いをしてあげたいけど、その時間はない」
line = "「できればエリシアの弔いをしてあげたいけど、その時間はない」"

[[dialogue]]
speaker = "梨緒"
# 「わかって……いる。生き残った私たちが、エリシアの分まで、戦わなければ……くぅっ……」
line = "「わかって……いる。生き残った私たちが、エリシアの分まで、戦わなければ……くぅっ……」"

[[dialogue]]
speaker = "梨緒"
# 「ひくっ……うぅぅっ……エリシア……うぁああぁああっ……！！」
line = "「ひくっ……うぅぅっ……エリシア……うぁああぁああっ……！！」"

[[dialogue]]
speaker = "ナターシャ"
# 「はぁ、はぁ……ようやく倒せた。あのガーディアン、本当に悪趣味なんだから」
line = "「はぁ、はぁ……ようやく倒せた。あのガーディアン、本当に悪趣味なんだから」"

[[dialogue]]
speaker = "梨緒"
# 「っ……はぁ……はぁ……」
line = "「っ……はぁ……はぁ……」"

[[dialogue]]
speaker = "ナターシャ"
# 「梨緒、大丈夫？」
line = "「梨緒、大丈夫？」"

[[dialogue]]
speaker = "梨緒"
# 「！　あ、ああ……平気だ。心配をかけてすまない。先に進もう」
line = "「！　あ、ああ……平気だ。心配をかけてすまない。先に進もう」"

[[dialogue]]
speaker = "ナターシャ"
# 「いや、一旦退くか、ちょっと休憩しよう？　このまま進むのはまずい気がする」
line = "「いや、一旦退くか、ちょっと休憩しよう？　このまま進むのはまずい気がする」"

[[dialogue]]
speaker = "梨緒"
# 「事態は一分一秒を争う。猶予はないはずだ」
line = "「事態は一分一秒を争う。猶予はないはずだ」"

[[dialogue]]
speaker = "梨緒"
# 「極星星徒会が神殿の機能を停止させれば、君まで消えてしまう。そんなことはさせられない」
line = "「極星星徒会が神殿の機能を停止させれば、君まで消えてしまう。そんなことはさせられない」"

[[dialogue]]
speaker = "ナターシャ"
# 「それはそうだけど、このままだと何を見せられるかわかったもんじゃないよ？」
line = "「それはそうだけど、このままだと何を見せられるかわかったもんじゃないよ？」"

[[dialogue]]
speaker = "梨緒"
# 「そうだな。心配してくれてありがとう」
line = "「そうだな。心配してくれてありがとう」"

[[dialogue]]
speaker = "梨緒"
# 「それでも私はこの続きを見なければいけない。そんな気がするんだ」
line = "「それでも私はこの続きを見なければいけない。そんな気がするんだ」"

[[dialogue]]
speaker = "ナターシャ"
# 「そこまで言うなら止めないけど……」
line = "「そこまで言うなら止めないけど……」"

[[dialogue]]
speaker = "梨緒"
# （ガーディアンが見せた私の記憶は……次第にベガの最期へと近づいている）
line = "（ガーディアンが見せた私の記憶は……次第にベガの最期へと近づいている）"

[[dialogue]]
speaker = "梨緒"
# （だが引っかかることがある……）
line = "（だが引っかかることがある……）"

[[dialogue]]
speaker = "梨緒"
# （ベガの最期──すなわちディザスターハンドとの戦い）
line = "（ベガの最期──すなわちディザスターハンドとの戦い）"

[[dialogue]]
speaker = "梨緒"
# 『立て、フィオナ！　動け！　逃げろっ！！』
line = "『立て、フィオナ！　動け！　逃げろっ！！』"

[[dialogue]]
speaker = "梨緒"
# （ベガのフィオナが死んだあの戦いで、ジグもあそこにいたはずだ）
line = "（ベガのフィオナが死んだあの戦いで、ジグもあそこにいたはずだ）"

[[dialogue]]
speaker = "梨緒"
# （なのにどうして、私の記憶の中にジグがいないんだ……？）
line = "（なのにどうして、私の記憶の中にジグがいないんだ……？）"
