[[dialogue]]
speaker = "unk"
# 第１３話,決意,B
line = "第１３話,決意,B"

[[dialogue]]
speaker = "チナ"
# 「色々脱線もしたけど……アタシがルヴィと出会って、この１０年をどう過ごしたか。少しは伝わったか、魔王？」
line = "「色々脱線もしたけど……アタシがルヴィと出会って、この１０年をどう過ごしたか。少しは伝わったか、魔王？」"

[[dialogue]]
speaker = "クロト"
# 「……ああ。話してくれてありがとう。おかげでルヴィネのこと、そしてキミたちのこと……少しだけわかった気がする」
line = "「……ああ。話してくれてありがとう。おかげでルヴィネのこと、そしてキミたちのこと……少しだけわかった気がする」"

[[dialogue]]
speaker = "unk"
# チナの口から語られた、１０年前に起こったニュクス流星群の惨劇。
line = "チナの口から語られた、１０年前に起こったニュクス流星群の惨劇。"

[[dialogue]]
speaker = "unk"
# どれほどの絶望と苦境が流星市国を襲ったのか、そしてルヴィネという存在がどれほど人々の心の支えとなったのか。
line = "どれほどの絶望と苦境が流星市国を襲ったのか、そしてルヴィネという存在がどれほど人々の心の支えとなったのか。"

[[dialogue]]
speaker = "unk"
# ルヴィネは『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』に生み出された、新たな女神の幼体。リクリエを扇動する人類の敵……アルタイルに住む俺たちの目からはどうしてもそう見える。
line = "ルヴィネは『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』に生み出された、新たな女神の幼体。リクリエを扇動する人類の敵……アルタイルに住む俺たちの目からはどうしてもそう見える。"

[[dialogue]]
speaker = "unk"
# けれど、ルヴィネと１０年を過ごしたチナたちからはそう見えていない。心優しく、思いやりのある、かけがえのない仲間であることがよくわかった。
line = "けれど、ルヴィネと１０年を過ごしたチナたちからはそう見えていない。心優しく、思いやりのある、かけがえのない仲間であることがよくわかった。"

[[dialogue]]
speaker = "クロト"
# （ルヴィネ……キミの真意は何なんだ？　どうしてそこまで身を粉にして、デネブを復興させ、チナたちと友情を築いたんだ……？）
line = "（ルヴィネ……キミの真意は何なんだ？　どうしてそこまで身を粉にして、デネブを復興させ、チナたちと友情を築いたんだ……？）"

[[dialogue]]
speaker = "unk"
# その場にいる他の皆も、俺と似たような感想を抱いているようだった。
line = "その場にいる他の皆も、俺と似たような感想を抱いているようだった。"

[[dialogue]]
speaker = "グレイス"
# 「じゃあ次は、私の視点から見たルヴィとのエピソードを──」
line = "「じゃあ次は、私の視点から見たルヴィとのエピソードを──」"

[[dialogue]]
speaker = "ジグ"
# 「まあまあ。喉も渇いたし、ずいぶん長いこと話し込んでる。今日はこのくらいでいいんじゃないか？」
line = "「まあまあ。喉も渇いたし、ずいぶん長いこと話し込んでる。今日はこのくらいでいいんじゃないか？」"

[[dialogue]]
speaker = "グレイス"
# 「え～っ！？　チナばっかり喋ってずるいですよ！」
line = "「え～っ！？　チナばっかり喋ってずるいですよ！」"

[[dialogue]]
speaker = "チナ"
# 「いや、ずるいってなんだよ……つーかグレイスに喋らせたら収拾つかなくなるだろ」
line = "「いや、ずるいってなんだよ……つーかグレイスに喋らせたら収拾つかなくなるだろ」"

[[dialogue]]
speaker = "グレイス"
# 「どうしてですかー！？　ひどいです！！」
line = "「どうしてですかー！？　ひどいです！！」"

[[dialogue]]
speaker = "チナ"
# 「ともかく、だ。魔王、これでわかってくれただろ？」
line = "「ともかく、だ。魔王、これでわかってくれただろ？」"

[[dialogue]]
speaker = "チナ"
# 「アタシは今、確かにほんの少しだけ、ルヴィに疑いを持ってはいる」
line = "「アタシは今、確かにほんの少しだけ、ルヴィに疑いを持ってはいる」"

[[dialogue]]
speaker = "チナ"
# 「でも……ルヴィの口から、そんなの誤解だ、私を信じてって説得されたら……」
line = "「でも……ルヴィの口から、そんなの誤解だ、私を信じてって説得されたら……」"

[[dialogue]]
speaker = "チナ"
# 「アタシは、ルヴィを信じると思う……悪いけどさ」
line = "「アタシは、ルヴィを信じると思う……悪いけどさ」"

[[dialogue]]
speaker = "クロト"
# 「──当然だと思う。俺だって、チナの立場だったら同じことを言うだろう」
line = "「──当然だと思う。俺だって、チナの立場だったら同じことを言うだろう」"

[[dialogue]]
speaker = "unk"
# 苦楽を共にした、１０年来の親友の言葉なのだから。
line = "苦楽を共にした、１０年来の親友の言葉なのだから。"

[[dialogue]]
speaker = "クロト"
# 「……今日は本当にありがとう。極星学園のみんなはゆっくり休んでくれ」
line = "「……今日は本当にありがとう。極星学園のみんなはゆっくり休んでくれ」"

[[dialogue]]
speaker = "クロト"
# 「新しく聞けた話も多い。アルタイルとしても、今後の方針をまとめ直して行きたい──だから、また明日も頼む」
line = "「新しく聞けた話も多い。アルタイルとしても、今後の方針をまとめ直して行きたい──だから、また明日も頼む」"

[[dialogue]]
speaker = "チナ"
# 「…………ああ」
line = "「…………ああ」"

[[dialogue]]
speaker = "レティシア"
# 「私はよろしくしたくないけれど、休めるのは助かるわ」
line = "「私はよろしくしたくないけれど、休めるのは助かるわ」"

[[dialogue]]
speaker = "グレイス"
# 「長くお喋りしてお腹が空きましたね。チナ、捕虜にはどんな夕食が出るのでしょうか……！」
line = "「長くお喋りしてお腹が空きましたね。チナ、捕虜にはどんな夕食が出るのでしょうか……！」"

[[dialogue]]
speaker = "チナ"
# 「お前はほんっとーに、もうちょい緊張感を持て！　マジで！！」
line = "「お前はほんっとーに、もうちょい緊張感を持て！　マジで！！」"

[[dialogue]]
speaker = "unk"
# ──やるべきことは見えた。あとは行動に移し、掴み取るだけだ。
line = "──やるべきことは見えた。あとは行動に移し、掴み取るだけだ。"

[[dialogue]]
speaker = "unk"
# 翌日、俺はメルエルとナターシャを星徒会室に呼び出した。
line = "翌日、俺はメルエルとナターシャを星徒会室に呼び出した。"

[[dialogue]]
speaker = "メルエル"
# 「お、おはよう会長くん。それに……ナターシャちゃんも」
line = "「お、おはよう会長くん。それに……ナターシャちゃんも」"

[[dialogue]]
speaker = "ナターシャ"
# 「……うん、おはよ。会長さん、これってどういう状況？」
line = "「……うん、おはよ。会長さん、これってどういう状況？」"

[[dialogue]]
speaker = "クロト"
# 「そう遠くないうちに、俺たちアルタイルはルヴィネと激突することになる。だからできうる限りの準備はしておきたい」
line = "「そう遠くないうちに、俺たちアルタイルはルヴィネと激突することになる。だからできうる限りの準備はしておきたい」"

[[dialogue]]
speaker = "クロト"
# 「俺たちの手元には、天界襲撃の際にグレイスが使っていた転送装置がある。あれを使えば……」
line = "「俺たちの手元には、天界襲撃の際にグレイスが使っていた転送装置がある。あれを使えば……」"

[[dialogue]]
speaker = "ナターシャ"
# 「デネブに乗り込めるってことでしょ。それはわかる」
line = "「デネブに乗り込めるってことでしょ。それはわかる」"

[[dialogue]]
speaker = "クロト"
# 「ああ。その際、少しでも戦力になる人員が欲しい。そこでメルエルには、天界へ戦力補強の打診に向かってもらうことにした」
line = "「ああ。その際、少しでも戦力になる人員が欲しい。そこでメルエルには、天界へ戦力補強の打診に向かってもらうことにした」"

[[dialogue]]
speaker = "クロト"
# 「天界襲撃があったのはつい先日……まだ片付いていないこともたくさんあると思う」
line = "「天界襲撃があったのはつい先日……まだ片付いていないこともたくさんあると思う」"

[[dialogue]]
speaker = "クロト"
# 「そんな状況で援軍を連れてこられるとしたら、リガルタ翁の娘であるメルエルだけだ」
line = "「そんな状況で援軍を連れてこられるとしたら、リガルタ翁の娘であるメルエルだけだ」"

[[dialogue]]
speaker = "ナターシャ"
# 「そう、だね。……それで、どうして私まで？」
line = "「そう、だね。……それで、どうして私まで？」"

[[dialogue]]
speaker = "クロト"
# 「人手が足りないとは言え、１人で向かわせるのは心配だろ。サポートできる人を連れて行っていいと言ったら、メルエルがキミを希望したんだ」
line = "「人手が足りないとは言え、１人で向かわせるのは心配だろ。サポートできる人を連れて行っていいと言ったら、メルエルがキミを希望したんだ」"

[[dialogue]]
speaker = "ナターシャ"
# 「…………いいの、メルエル？」
line = "「…………いいの、メルエル？」"

[[dialogue]]
speaker = "メルエル"
# 「うん。ナターシャちゃんも、今私と２人旅なんて居心地が悪いとは思うんだけど……やっぱり私、このままでいるの、嫌だなって……」
line = "「うん。ナターシャちゃんも、今私と２人旅なんて居心地が悪いとは思うんだけど……やっぱり私、このままでいるの、嫌だなって……」"

[[dialogue]]
speaker = "メルエル"
# 「隠してたこととか、思ってたこととか……たくさん聞きたい。お話がしたいの。だから、ナターシャちゃんがよかったら……」
line = "「隠してたこととか、思ってたこととか……たくさん聞きたい。お話がしたいの。だから、ナターシャちゃんがよかったら……」"

[[dialogue]]
speaker = "ナターシャ"
# 「──そう。そういうこと」
line = "「──そう。そういうこと」"

[[dialogue]]
speaker = "ナターシャ"
# 「……わかった。言っておくけど居心地悪いよー、絶対。メルエルには、積もり積もった恨みつらみがあるからねー」
line = "「……わかった。言っておくけど居心地悪いよー、絶対。メルエルには、積もり積もった恨みつらみがあるからねー」"

[[dialogue]]
speaker = "メルエル"
# 「うん！　いっぱい聞かせて！」
line = "「うん！　いっぱい聞かせて！」"

[[dialogue]]
speaker = "ナターシャ"
# 「メルエルは眩しいなぁ……まあ。退屈はしないで済みそうかな？」
line = "「メルエルは眩しいなぁ……まあ。退屈はしないで済みそうかな？」"

[[dialogue]]
speaker = "ナターシャ"
# 「会長さんのオーダーは了解。ドタバタしてる天界から、強～い星騎士を引っ張って来ればＯＫだね？」
line = "「会長さんのオーダーは了解。ドタバタしてる天界から、強～い星騎士を引っ張って来ればＯＫだね？」"

[[dialogue]]
speaker = "クロト"
# 「ああ。メルエル、ナターシャ。頼んだ」
line = "「ああ。メルエル、ナターシャ。頼んだ」"

[[dialogue]]
speaker = "メルエル"
# 「任せて！」
line = "「任せて！」"

[[dialogue]]
speaker = "ナターシャ"
# 「できうる範囲で、頑張らせてもらうよ」
line = "「できうる範囲で、頑張らせてもらうよ」"

[[dialogue]]
speaker = "unk"
# 退室していく２人を見送る。
line = "退室していく２人を見送る。"

[[dialogue]]
speaker = "unk"
# どれだけかき集めても戦力は足りない。決戦の準備を整えなくてはならない──
line = "どれだけかき集めても戦力は足りない。決戦の準備を整えなくてはならない──"

[[dialogue]]
speaker = "unk"
# そのまましばらく部屋で待機していると、次の約束の人物がやってきた。
line = "そのまましばらく部屋で待機していると、次の約束の人物がやってきた。"

[[dialogue]]
speaker = "ジグ"
# 「やあ、わざわざ私だけを呼び出すだなんて……愛の告白でもしてくれるのかな？」
line = "「やあ、わざわざ私だけを呼び出すだなんて……愛の告白でもしてくれるのかな？」"

[[dialogue]]
speaker = "クロト"
# 「悪いな。少しも艶っぽくない、真面目な話だ」
line = "「悪いな。少しも艶っぽくない、真面目な話だ」"

[[dialogue]]
speaker = "ジグ"
# 「そいつは残念──それで？」
line = "「そいつは残念──それで？」"

[[dialogue]]
speaker = "クロト"
# 「俺たちアルタイルは、デネブと共存の道を探す……ずっとそう言ってきた」
line = "「俺たちアルタイルは、デネブと共存の道を探す……ずっとそう言ってきた」"

[[dialogue]]
speaker = "クロト"
# 「そこにもう１つ、我儘を言いたい」
line = "「そこにもう１つ、我儘を言いたい」"

[[dialogue]]
speaker = "クロト"
# 「ルヴィネが死ぬ運命を阻止する。極星学園星徒会が、誰一人欠けることなく、この戦いを終わらせたいんだ」
line = "「ルヴィネが死ぬ運命を阻止する。極星学園星徒会が、誰一人欠けることなく、この戦いを終わらせたいんだ」"

[[dialogue]]
speaker = "ジグ"
# 「へぇ……？」
line = "「へぇ……？」"

[[dialogue]]
speaker = "クロト"
# 「……極星学園の皆は、もうすでにたくさんのものを失っている。彼女たちにとって、ルヴィネはかけがえのない友人だ」
line = "「……極星学園の皆は、もうすでにたくさんのものを失っている。彼女たちにとって、ルヴィネはかけがえのない友人だ」"

[[dialogue]]
speaker = "クロト"
# 「このまま時が進むと、ジグが見た未来は実現する……そうなると、彼女たちは死に別れてしまうことになるだろう」
line = "「このまま時が進むと、ジグが見た未来は実現する……そうなると、彼女たちは死に別れてしまうことになるだろう」"

[[dialogue]]
speaker = "ジグ"
# 「必要な犠牲ってやつだね。違うかい？」
line = "「必要な犠牲ってやつだね。違うかい？」"

[[dialogue]]
speaker = "クロト"
# 「俺は……違うと思う」
line = "「俺は……違うと思う」"

[[dialogue]]
speaker = "ジグ"
# 「一軍の将が、情に流されているようでは話にならないと思うけど？」
line = "「一軍の将が、情に流されているようでは話にならないと思うけど？」"

[[dialogue]]
speaker = "クロト"
# 「同情する気持ちがないと言えば嘘になる。だけど、重要なのはそこじゃない」
line = "「同情する気持ちがないと言えば嘘になる。だけど、重要なのはそこじゃない」"

[[dialogue]]
speaker = "クロト"
# 「ジグの視た未来のことを聞いてからずっと考えていた──ルヴィネが死ぬこと、イコール俺たちの勝利とは思えない」
line = "「ジグの視た未来のことを聞いてからずっと考えていた──ルヴィネが死ぬこと、イコール俺たちの勝利とは思えない」"

[[dialogue]]
speaker = "クロト"
# 「仮にルヴィネが死亡したところで、あの子に代わる、第２、第３の『女神の幼体』が生み出されるだけなんじゃないか？」
line = "「仮にルヴィネが死亡したところで、あの子に代わる、第２、第３の『女神の幼体』が生み出されるだけなんじゃないか？」"

[[dialogue]]
speaker = "クロト"
# 「だから俺は新しいルートを見つけたい。この世界で最も『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』のことを知るルヴィネを、仲間に引き込めたら……きっと心強いはずだ」
line = "「だから俺は新しいルートを見つけたい。この世界で最も『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』のことを知るルヴィネを、仲間に引き込めたら……きっと心強いはずだ」"

[[dialogue]]
speaker = "クロト"
# 「可能性が視えるジグに聞きたい。キミが見た、すでに決定しているであろう『ルヴィネ死亡の未来』を回避した上で──」
line = "「可能性が視えるジグに聞きたい。キミが見た、すでに決定しているであろう『ルヴィネ死亡の未来』を回避した上で──」"

[[dialogue]]
speaker = "クロト"
# 「誰１人欠けることなくリクリエを止める。そんな未来を引き寄せることは……可能か？」
line = "「誰１人欠けることなくリクリエを止める。そんな未来を引き寄せることは……可能か？」"

[[dialogue]]
speaker = "ジグ"
# 「……………………」
line = "「……………………」"

[[dialogue]]
speaker = "unk"
# 長い、長い沈黙。
line = "長い、長い沈黙。"

[[dialogue]]
speaker = "ジグ"
# 「これはまた……ずいぶんと業突く張りな宣言だね。失敗したらベガのように滅ぶ。そのことは本当に理解しているのかい？」
line = "「これはまた……ずいぶんと業突く張りな宣言だね。失敗したらベガのように滅ぶ。そのことは本当に理解しているのかい？」"

[[dialogue]]
speaker = "unk"
# ジグは呆れたようにそうこぼしてから──
line = "ジグは呆れたようにそうこぼしてから──"

[[dialogue]]
speaker = "ジグ"
# 「方法はなくもない──かもしれないね？」
line = "「方法はなくもない──かもしれないね？」"
