[[dialogue]]
speaker = "unk"
# 第１３話,『ＸＥＬＯＳ』,B
line = "第１３話,『ＸＥＬＯＳ』,B"

[[dialogue]]
speaker = "ベアトリス"
# 「ん～、ジューシー♪　この餃子サイコーだよ、アポロちゃん！」
line = "「ん～、ジューシー♪　この餃子サイコーだよ、アポロちゃん！」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ふふん。あたしの餃子は特別だからな」
line = "「ふふん。あたしの餃子は特別だからな」"

[[dialogue]]
speaker = "unk"
# アポロ特製の餃子に舌鼓を打つベアトリス。
line = "アポロ特製の餃子に舌鼓を打つベアトリス。"

[[dialogue]]
speaker = "unk"
# こうしてベアトリスが戻ってきて、俺もほっとしている。
line = "こうしてベアトリスが戻ってきて、俺もほっとしている。"

[[dialogue]]
speaker = "梨緒"
# 「相変わらずニンニクが好きだな、吸血鬼なのに」
line = "「相変わらずニンニクが好きだな、吸血鬼なのに」"

[[dialogue]]
speaker = "ベアトリス"
# 「だって美味しいんだも～ん！　ほら、ナターシャちゃんも食べようよ！」
line = "「だって美味しいんだも～ん！　ほら、ナターシャちゃんも食べようよ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「いや私、匂いの強いものは食べない主義なんで」
line = "「いや私、匂いの強いものは食べない主義なんで」"

[[dialogue]]
speaker = "ベアトリス"
# 「そんなこと言わずにさ！　とっても美味しいから！」
line = "「そんなこと言わずにさ！　とっても美味しいから！」"

[[dialogue]]
speaker = "ナターシャ"
# 「ガーリックハラスメントだよ、それ」
line = "「ガーリックハラスメントだよ、それ」"

[[dialogue]]
speaker = "クロト"
# 「新しいハラスメントが誕生したな……」
line = "「新しいハラスメントが誕生したな……」"

[[dialogue]]
speaker = "ナターシャ"
# 「でもさ、私たちは黙って見てたけど、もしベアトが本当に敵だったらどうしたの？」
line = "「でもさ、私たちは黙って見てたけど、もしベアトが本当に敵だったらどうしたの？」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「その時はその時であたしが何とかしたさ」
line = "「その時はその時であたしが何とかしたさ」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ま、それはないって信じてたけど。梨緒の仲間なら、あたしにとっても仲間だからな」
line = "「ま、それはないって信じてたけど。梨緒の仲間なら、あたしにとっても仲間だからな」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ナターシャこそ、ベアトのことあんまり疑ってなかったみたいだが」
line = "「ナターシャこそ、ベアトのことあんまり疑ってなかったみたいだが」"

[[dialogue]]
speaker = "ナターシャ"
# 「正直、ベアトがスパイはありえないって。全然基本がなってないし、もし味方のスパイだったら足を引っ張られる前に消してるレベル」
line = "「正直、ベアトがスパイはありえないって。全然基本がなってないし、もし味方のスパイだったら足を引っ張られる前に消してるレベル」"

[[dialogue]]
speaker = "ベアトリス"
# 「ナターシャちゃんひどいっ！？」
line = "「ナターシャちゃんひどいっ！？」"

[[dialogue]]
speaker = "unk"
# 本気か冗談かわからないナターシャに、ショックを受けるベアトリス。
line = "本気か冗談かわからないナターシャに、ショックを受けるベアトリス。"

[[dialogue]]
speaker = "unk"
# 選挙管理委員会の仲間が戻ってきて、本当に良かった。
line = "選挙管理委員会の仲間が戻ってきて、本当に良かった。"

[[dialogue]]
speaker = "ベアトリス"
# 「ごめんなさい、会長さん、ヴィーナスさん。私、本当は極星学園の副会長でした」
line = "「ごめんなさい、会長さん、ヴィーナスさん。私、本当は極星学園の副会長でした」"

[[dialogue]]
speaker = "ベアトリス"
# 「でもアルタイルを滅ぼす意志はありません。デネブもアルタイルも救いたいと思っています」
line = "「でもアルタイルを滅ぼす意志はありません。デネブもアルタイルも救いたいと思っています」"

[[dialogue]]
speaker = "クロト"
# 「それなら俺たち同じだ。これからもよろしく、ベアトリス」
line = "「それなら俺たち同じだ。これからもよろしく、ベアトリス」"

[[dialogue]]
speaker = "ベアトリス"
# 「はい！」
line = "「はい！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「雨が降って自家用車ってやつね！」
line = "「雨が降って自家用車ってやつね！」"

[[dialogue]]
speaker = "ベアトリス"
# 「へ……？」
line = "「へ……？」"

[[dialogue]]
speaker = "クロト"
# 「雨降って地固まる、って言いたいんだと思う……」
line = "「雨降って地固まる、って言いたいんだと思う……」"

[[dialogue]]
speaker = "ベアトリス"
# 「あ、ああ……なるほど？」
line = "「あ、ああ……なるほど？」"

[[dialogue]]
speaker = "unk"
# 相変わらず微妙に慣用句を間違えるヴィーナスだった。
line = "相変わらず微妙に慣用句を間違えるヴィーナスだった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「フィオナはもう大丈夫なの？」
line = "「フィオナはもう大丈夫なの？」"

[[dialogue]]
speaker = "フィオナ"
# 「はい、ゆっくり休んだおかげですっかり良くなりました。もう魔王因子も機能しています」
line = "「はい、ゆっくり休んだおかげですっかり良くなりました。もう魔王因子も機能しています」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ラクシャは？」
line = "「ラクシャは？」"

[[dialogue]]
speaker = "ラクシャ"
# 「ま、ちょっとは元気になったかな。ボクも餃子いただきーっと。あ、これほんとに美味しい」
line = "「ま、ちょっとは元気になったかな。ボクも餃子いただきーっと。あ、これほんとに美味しい」"

[[dialogue]]
speaker = "リノ"
# 「みんなー、探してた資料あったわよ～！　ジグが言っていた“真なる神”の解明に繋がるかもしれないわ」
line = "「みんなー、探してた資料あったわよ～！　ジグが言っていた“真なる神”の解明に繋がるかもしれないわ」"

[[dialogue]]
speaker = "クロト"
# 「！　本当に？」
line = "「！　本当に？」"

[[dialogue]]
speaker = "リノ"
# 「ええ。ネビュラには昔イザベラっていう考古学者がいてね。彼女が研究していたの」
line = "「ええ。ネビュラには昔イザベラっていう考古学者がいてね。彼女が研究していたの」"

[[dialogue]]
speaker = "リノ"
# 「魔王ラクシスの時代に存在した『チャカパラ神』と、それを信じる『バジュラ教』に代表されるように……」
line = "「魔王ラクシスの時代に存在した『チャカパラ神』と、それを信じる『バジュラ教』に代表されるように……」"

[[dialogue]]
speaker = "リノ"
# 「女神テルルと異なる神を信じ、厄災を『天啓』と呼ぶ信仰は、名前を変えていろんな時代に出現していた」
line = "「女神テルルと異なる神を信じ、厄災を『天啓』と呼ぶ信仰は、名前を変えていろんな時代に出現していた」"

[[dialogue]]
speaker = "リノ"
# 「信じる神の名前は違うけど、その教義は同じ。リクリエを神の意志として受け入れようというもの」
line = "「信じる神の名前は違うけど、その教義は同じ。リクリエを神の意志として受け入れようというもの」"

[[dialogue]]
speaker = "リノ"
# 「教義以外に共通点らしいものはない。だけどそれは不自然でしょ？　文化や時代が違えば信仰も変わってくるものなのに」
line = "「教義以外に共通点らしいものはない。だけどそれは不自然でしょ？　文化や時代が違えば信仰も変わってくるものなのに」"

[[dialogue]]
speaker = "リノ"
# 「だからイザベラは、それらを同じ神を信仰しているものと解釈し、その神をこう名付けた」
line = "「だからイザベラは、それらを同じ神を信仰しているものと解釈し、その神をこう名付けた」"

[[dialogue]]
speaker = "リノ"
# 「女神と異なる信仰を持つ神──『<ruby=ゼノ>Ｘｅｎｏ</ruby>　<ruby=ロード>Ｌｏｒｄ</ruby>　<ruby=サンクティファイド>Ｓａｎｃｔｉｆｉｅｄ</ruby>』」
line = "「女神と異なる信仰を持つ神──『<ruby>Ｘｅｎｏ<rt>ゼノ</rt></ruby>　<ruby>Ｌｏｒｄ<rt>ロード</rt></ruby>　<ruby>Ｓａｎｃｔｉｆｉｅｄ<rt>サンクティファイド</rt></ruby>』」"

[[dialogue]]
speaker = "リノ"
# 「それぞれの頭を取って『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』──と」
line = "「それぞれの頭を取って『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』──と」"

[[dialogue]]
speaker = "ヴィーナス"
# 「チャカパラ神よりかっこいいじゃない！　なんかムカつくわね！」
line = "「チャカパラ神よりかっこいいじゃない！　なんかムカつくわね！」"

[[dialogue]]
speaker = "梨緒"
# 「『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』……」
line = "「『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』……」"

[[dialogue]]
speaker = "unk"
# それがリクリエを進める神の名。
line = "それがリクリエを進める神の名。"

[[dialogue]]
speaker = "unk"
# 実在しているのかも不明だが、もし存在するとすれば、ジグが語る“真なる神”とはそれのことだろう。
line = "実在しているのかも不明だが、もし存在するとすれば、ジグが語る“真なる神”とはそれのことだろう。"

[[dialogue]]
speaker = "梨緒"
# 「敵の言葉を鵜呑みにするわけにはいかないが、あえて否定せず、正しいと仮定してみると……」
line = "「敵の言葉を鵜呑みにするわけにはいかないが、あえて否定せず、正しいと仮定してみると……」"

[[dialogue]]
speaker = "unk"
# 『チャカパラ神』を信仰する『バジュラ教団』はこう主張していた。
line = "『チャカパラ神』を信仰する『バジュラ教団』はこう主張していた。"

[[dialogue]]
speaker = "unk"
# 『リクリエは崇高なるチャカパラ様の啓示！』
line = "『リクリエは崇高なるチャカパラ様の啓示！』"

[[dialogue]]
speaker = "unk"
# 『チャカパラ神は、女神をも超越する“大宇宙”のご意思である！』
line = "『チャカパラ神は、女神をも超越する“大宇宙”のご意思である！』"

[[dialogue]]
speaker = "unk"
# ──と。
line = "──と。"

[[dialogue]]
speaker = "敗残の亡霊"
# 『よって……世界の再創生とは……女神をも超越する……チャカパラ神のご意思なのだァ……ッ……！！』
line = "『よって……世界の再創生とは……女神をも超越する……チャカパラ神のご意思なのだァ……ッ……！！』"

[[dialogue]]
speaker = "unk"
# とも語っていた。
line = "とも語っていた。"

[[dialogue]]
speaker = "ジグ"
# 「私は<ruby=ジグ>Ｚ</ruby>。“真なる神の騎士”だ」
line = "「私は<ruby>Ｚ<rt>ジグ</rt></ruby>。“真なる神の騎士”だ」"

[[dialogue]]
speaker = "ジグ"
# 「言葉通りの意味さ。私が仕えるのは、世界を創り<ruby=たも>給</ruby>うた真なる神。女神なんて所詮お飾りだよ」
line = "「言葉通りの意味さ。私が仕えるのは、世界を創り<ruby>給<rt>たも</rt></ruby>うた真なる神。女神なんて所詮お飾りだよ」"

[[dialogue]]
speaker = "クロト"
# 「彼らの言葉が正しいと仮定するなら、女神テルルの上に、さらなる上位存在──『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』がいる」
line = "「彼らの言葉が正しいと仮定するなら、女神テルルの上に、さらなる上位存在──『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』がいる」"

[[dialogue]]
speaker = "クロト"
# 「ジグの言う通りだとすると、世界を創造したのも女神ではなく『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』ということになる」
line = "「ジグの言う通りだとすると、世界を創造したのも女神ではなく『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』ということになる」"

[[dialogue]]
speaker = "ナターシャ"
# 「世界の信仰が覆るね。時代が時代なら流星教に目をつけられるかも」
line = "「世界の信仰が覆るね。時代が時代なら流星教に目をつけられるかも」"

[[dialogue]]
speaker = "unk"
# もしこんなことを発表すれば、世界は大騒ぎになるだろう。
line = "もしこんなことを発表すれば、世界は大騒ぎになるだろう。"

[[dialogue]]
speaker = "unk"
# いや、荒唐無稽な説で相手にされない可能性もあるかもしれないが。
line = "いや、荒唐無稽な説で相手にされない可能性もあるかもしれないが。"

[[dialogue]]
speaker = "ヴィーナス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナス？」
line = "「ヴィーナス？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「全然話についていけないわ！」
line = "「全然話についていけないわ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「チャカパラとか『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』とか、よくわかんない名前ばっかり出てきて覚えられないもの！」
line = "「チャカパラとか『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』とか、よくわかんない名前ばっかり出てきて覚えられないもの！」"

[[dialogue]]
speaker = "クロト"
# 「そ、そうか……また細かく説明するよ」
line = "「そ、そうか……また細かく説明するよ」"

[[dialogue]]
speaker = "ナターシャ"
# 「あー、そういえばこういう子だったねー」
line = "「あー、そういえばこういう子だったねー」"

[[dialogue]]
speaker = "クロト"
# 「ラクシャは守護天使としてどう思う？」
line = "「ラクシャは守護天使としてどう思う？」"

[[dialogue]]
speaker = "ラクシャ"
# 「んー……」
line = "「んー……」"

[[dialogue]]
speaker = "unk"
# ラクシャに話を向けると、彼女は難しい物理学の講義を聞くみたいに、しかめっ面をしていた。
line = "ラクシャに話を向けると、彼女は難しい物理学の講義を聞くみたいに、しかめっ面をしていた。"

[[dialogue]]
speaker = "ラクシャ"
# 「女神以上の存在が本当にいるとして、ボクたち守護天使はそれを直接認識できないようになっている」
line = "「女神以上の存在が本当にいるとして、ボクたち守護天使はそれを直接認識できないようになっている」"

[[dialogue]]
speaker = "ラクシャ"
# 「だからボクからはノーコメントとしか言えないよ」
line = "「だからボクからはノーコメントとしか言えないよ」"

[[dialogue]]
speaker = "クロト"
# 「……そうか」
line = "「……そうか」"

[[dialogue]]
speaker = "unk"
# 守護天使は女神に近い高位存在だ。
line = "守護天使は女神に近い高位存在だ。"

[[dialogue]]
speaker = "unk"
# だから守護天使なりの意見をもらえればと思ったんだが、それは難しいようだ。
line = "だから守護天使なりの意見をもらえればと思ったんだが、それは難しいようだ。"

[[dialogue]]
speaker = "リノ"
# 「『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』が実在しているか、それが女神より上位の存在であるかはまだ仮説の段階よ」
line = "「『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』が実在しているか、それが女神より上位の存在であるかはまだ仮説の段階よ」"

[[dialogue]]
speaker = "リノ"
# 「研究では仮説を立てて検証していくのが大事。肯定する材料も、否定する材料もこれから探していきましょう」
line = "「研究では仮説を立てて検証していくのが大事。肯定する材料も、否定する材料もこれから探していきましょう」"

[[dialogue]]
speaker = "unk"
# 女神より上位に存在するとされ、<ruby=リクリエ>再創造</ruby>を望むとされる『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』。
line = "女神より上位に存在するとされ、<ruby>再創造<rt>リクリエ</rt></ruby>を望むとされる『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』。"

[[dialogue]]
speaker = "unk"
# その情報を集めることが、世界の謎を解き明かすことに繋がるのかもしれない。
line = "その情報を集めることが、世界の謎を解き明かすことに繋がるのかもしれない。"

[[dialogue]]
speaker = "クロト"
# 「そうそう、今日、買い出しの途中でルヴィネがアルバイトしてるところを見かけたんだ」
line = "「そうそう、今日、買い出しの途中でルヴィネがアルバイトしてるところを見かけたんだ」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「何かわかったことはあるか？」
line = "「何かわかったことはあるか？」"

[[dialogue]]
speaker = "クロト"
# 「ルヴィネが担々麺が好きなことくらいかな……」
line = "「ルヴィネが担々麺が好きなことくらいかな……」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「なんだそりゃ」
line = "「なんだそりゃ」"

[[dialogue]]
speaker = "ベアトリス"
# 「あはは、ルヴィは担々麺にはうるさいからね……」
line = "「あはは、ルヴィは担々麺にはうるさいからね……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「おかげで私たちも担々麺食べたくなって、お昼は担々麺にしたのよねー」
line = "「おかげで私たちも担々麺食べたくなって、お昼は担々麺にしたのよねー」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でもデネブまんじゅうは探してもみつからなかったわ。残念」
line = "「でもデネブまんじゅうは探してもみつからなかったわ。残念」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「そりゃそうだろ。誰が買うんだ」
line = "「そりゃそうだろ。誰が買うんだ」"

[[dialogue]]
speaker = "クロト"
# 「ははは……」
line = "「ははは……」"

[[dialogue]]
speaker = "クロト"
# 「ただ、ルヴィネはちゃんと人々を守っていた。モンスターと戦う彼女は、純粋に世界を救おうとしているように見えたよ」
line = "「ただ、ルヴィネはちゃんと人々を守っていた。モンスターと戦う彼女は、純粋に世界を救おうとしているように見えたよ」"

[[dialogue]]
speaker = "ベアトリス"
# 「だって極星の星徒会長だもん。デネブの人にとって、ルヴィは間違いなく英雄だよ」
line = "「だって極星の星徒会長だもん。デネブの人にとって、ルヴィは間違いなく英雄だよ」"

[[dialogue]]
speaker = "ベアトリス"
# 「平行世界同士の生存競争は止めたいと思ってるけど、私はルヴィを信じてる」
line = "「平行世界同士の生存競争は止めたいと思ってるけど、私はルヴィを信じてる」"

[[dialogue]]
speaker = "unk"
# ベアトリスのルヴィネへの信頼は今も揺らいでいない。
line = "ベアトリスのルヴィネへの信頼は今も揺らいでいない。"

[[dialogue]]
speaker = "unk"
# 普通のデネブの住民からすれば、それが当然なのだろう。
line = "普通のデネブの住民からすれば、それが当然なのだろう。"

[[dialogue]]
speaker = "梨緒"
# 「アルタイルとデネブが共調するには、ルヴィネを説得することが不可欠だ」
line = "「アルタイルとデネブが共調するには、ルヴィネを説得することが不可欠だ」"

[[dialogue]]
speaker = "梨緒"
# 「だが私たちはルヴィネに疑いを持っている。彼女がリクリエの側にいるのではないかとな」
line = "「だが私たちはルヴィネに疑いを持っている。彼女がリクリエの側にいるのではないかとな」"

[[dialogue]]
speaker = "ベアトリス"
# 「ルヴィが……！？　そんなはずないよ！　だったらデネブを救うはずないもん！」
line = "「ルヴィが……！？　そんなはずないよ！　だったらデネブを救うはずないもん！」"

[[dialogue]]
speaker = "梨緒"
# 「問題はそこだ。ルヴィネが破滅寸前の世界を救ったというが、１人の天使にそんなことが可能なのか？」
line = "「問題はそこだ。ルヴィネが破滅寸前の世界を救ったというが、１人の天使にそんなことが可能なのか？」"

[[dialogue]]
speaker = "ベアトリス"
# 「で、でも実際にデネブはこうして……」
line = "「で、でも実際にデネブはこうして……」"

[[dialogue]]
speaker = "梨緒"
# 「ああ、デネブが存続しているのは事実だ。だが不自然なんだ。彼女の何もかもが」
line = "「ああ、デネブが存続しているのは事実だ。だが不自然なんだ。彼女の何もかもが」"

[[dialogue]]
speaker = "ベアトリス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "梨緒"
# 「ベアトにまでルヴィネを疑えとは言わない。だけどルヴィネについては調査させてもらう」
line = "「ベアトにまでルヴィネを疑えとは言わない。だけどルヴィネについては調査させてもらう」"

[[dialogue]]
speaker = "ベアトリス"
# 「ううん、それなら私もやるよ。疑いが晴れれば、梨緒ちゃんたちもそれでいいんだもんね？」
line = "「ううん、それなら私もやるよ。疑いが晴れれば、梨緒ちゃんたちもそれでいいんだもんね？」"

[[dialogue]]
speaker = "梨緒"
# 「ああ、もし誤解ならその方がいいからな」
line = "「ああ、もし誤解ならその方がいいからな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でもどうやってルヴィネのことを調べるの？　本人に聞いてみる？」
line = "「でもどうやってルヴィネのことを調べるの？　本人に聞いてみる？」"

[[dialogue]]
speaker = "梨緒"
# 「いや、答えてくれるわけないだろう……インタビューじゃあるまいし」
line = "「いや、答えてくれるわけないだろう……インタビューじゃあるまいし」"

[[dialogue]]
speaker = "ナターシャ"
# 「はーい。それなら考えがあるんだけど……」
line = "「はーい。それなら考えがあるんだけど……」"

[[dialogue]]
speaker = "unk"
# 手を上げながら提案するナターシャに、みんなの注目が集まる。
line = "手を上げながら提案するナターシャに、みんなの注目が集まる。"

[[dialogue]]
speaker = "unk"
# そして──
line = "そして──"

[[dialogue]]
speaker = "ナターシャ"
# 「みんなでルヴィネを尾行してみるってのはどうかな？」
line = "「みんなでルヴィネを尾行してみるってのはどうかな？」"
