[[dialogue]]
speaker = "unk"
# 第１１話,まぶたに浮かぶは,B
line = "第１１話,まぶたに浮かぶは,B"

[[dialogue]]
speaker = "フィオナ"
# 『──姉さん……姉さんっ……！』
line = "『──姉さん……姉さんっ……！』"

[[dialogue]]
speaker = "unk"
# ５年前、姉さんは原因不明の昏睡状態に陥った。
line = "５年前、姉さんは原因不明の昏睡状態に陥った。"

[[dialogue]]
speaker = "unk"
# 世界を救う<ruby=えいゆう>魔王</ruby>となるべく、星術の修行をこなしてきた、真っ只中の出来事だった。
line = "世界を救う<ruby>魔王<rt>えいゆう</rt></ruby>となるべく、星術の修行をこなしてきた、真っ只中の出来事だった。"

[[dialogue]]
speaker = "unk"
# その時から私は──姉に代わってフィオナという号を授かった。
line = "その時から私は──姉に代わってフィオナという号を授かった。"

[[dialogue]]
speaker = "unk"
# エリシアという個人の心は殺して、星見の長女という立ち場を演じるようになった。
line = "エリシアという個人の心は殺して、星見の長女という立ち場を演じるようになった。"

[[dialogue]]
speaker = "unk"
# 姉さんはいつか目覚めてくれるのだろうか？
line = "姉さんはいつか目覚めてくれるのだろうか？"

[[dialogue]]
speaker = "unk"
# 姉さんを奪ったのは未知の病か、それともモンスター種の呪いか何かではないかと思っていた。
line = "姉さんを奪ったのは未知の病か、それともモンスター種の呪いか何かではないかと思っていた。"

[[dialogue]]
speaker = "unk"
# だけど……
line = "だけど……"

[[dialogue]]
speaker = "アポロ"
# 『出てこい、サイキョーの魔王！　さもなくばこの人間界はぜ～んぶまっさらにしてアポロ様のおもちゃ箱にしちゃうぞ！』
line = "『出てこい、サイキョーの魔王！　さもなくばこの人間界はぜ～んぶまっさらにしてアポロ様のおもちゃ箱にしちゃうぞ！』"

[[dialogue]]
speaker = "unk"
# あの時。
line = "あの時。"

[[dialogue]]
speaker = "unk"
# 変わり果てた姉の姿を見て──私は、自分がとんだ思い違いをしていたと知った。
line = "変わり果てた姉の姿を見て──私は、自分がとんだ思い違いをしていたと知った。"

[[dialogue]]
speaker = "unk"
# そして、その背景は……後により鮮明になって。
line = "そして、その背景は……後により鮮明になって。"

[[dialogue]]
speaker = "セイファート"
# 「だが。それでも。<ruby=マルキア>妻</ruby>と会う機がリクリエにしかないというならば……私は喜んで終末を望もう！」
line = "「だが。それでも。<ruby>妻<rt>マルキア</rt></ruby>と会う機がリクリエにしかないというならば……私は喜んで終末を望もう！」"

[[dialogue]]
speaker = "unk"
# 私たちは彼の記憶を覗いた。同じだ、と思った。
line = "私たちは彼の記憶を覗いた。同じだ、と思った。"

[[dialogue]]
speaker = "unk"
# ジェラルド・セイファート学園長の奥方はここアルタイルから<ruby=さら>攫</ruby>われ、渡った先のデネブで『使徒』と化した。化された。
line = "ジェラルド・セイファート学園長の奥方はここアルタイルから<ruby>攫<rt>さら</rt></ruby>われ、渡った先のデネブで『使徒』と化した。化された。"

[[dialogue]]
speaker = "unk"
# そして彼の奥様は……仮面に操られながら、デネブの世界を<ruby=じゅうりん>蹂躙</ruby>していた。
line = "そして彼の奥様は……仮面に操られながら、デネブの世界を<ruby>蹂躙<rt>じゅうりん</rt></ruby>していた。"

[[dialogue]]
speaker = "フィオナ"
# （だから……姉さんは、その逆で）
line = "（だから……姉さんは、その逆で）"

[[dialogue]]
speaker = "unk"
# 私たちの前に現れた『アポロ』の素体となったのは──デネブ世界にいたはずの姉さんなのだろう。
line = "私たちの前に現れた『アポロ』の素体となったのは──デネブ世界にいたはずの姉さんなのだろう。"

[[dialogue]]
speaker = "unk"
# 仮面によって『リクリエの使徒』と化した姉さんは、こちらアルタイルへと乗り込んできた。
line = "仮面によって『リクリエの使徒』と化した姉さんは、こちらアルタイルへと乗り込んできた。"

[[dialogue]]
speaker = "unk"
# だから恐らく……デネブの世界じゃ、あのマルキアさんのように、姉さんが神隠しに遭っていたに違いない。
line = "だから恐らく……デネブの世界じゃ、あのマルキアさんのように、姉さんが神隠しに遭っていたに違いない。"

[[dialogue]]
speaker = "unk"
# さらにその影響によって、本来アルタイルにいたはずの姉さんまでも意識を失ってしまった……。
line = "さらにその影響によって、本来アルタイルにいたはずの姉さんまでも意識を失ってしまった……。"

[[dialogue]]
speaker = "unk"
# リクリエは私から、どちらの姉さんも奪っていったことになる。
line = "リクリエは私から、どちらの姉さんも奪っていったことになる。"

[[dialogue]]
speaker = "フィオナ"
# （でも──そこに、私の責任は、なかったと言えるのでしょうか）
line = "（でも──そこに、私の責任は、なかったと言えるのでしょうか）"

[[dialogue]]
speaker = "unk"
# 一緒に流星ライダーごっこをして遊んでいた姉さん。
line = "一緒に流星ライダーごっこをして遊んでいた姉さん。"

[[dialogue]]
speaker = "unk"
# けれど、星見の長女として、いつしか鍛錬にばかり精を出すようになっていた姉さん。
line = "けれど、星見の長女として、いつしか鍛錬にばかり精を出すようになっていた姉さん。"

[[dialogue]]
speaker = "unk"
# アポロと化した今の姿は……そんな、無邪気だった頃の自分を求めているようにしか思えなくて。
line = "アポロと化した今の姿は……そんな、無邪気だった頃の自分を求めているようにしか思えなくて。"

[[dialogue]]
speaker = "フィオナ"
# （姉さんは──疲れていたのかもしれません。私が……妹として、もっと支えられていれば──）
line = "（姉さんは──疲れていたのかもしれません。私が……妹として、もっと支えられていれば──）"

[[dialogue]]
speaker = "ヴィーナス"
# 「なーにくよくよしてんのよ、フィオナ！」
line = "「なーにくよくよしてんのよ、フィオナ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ヴィーナスさん──」
line = "「ヴィーナスさん──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「また意固地になりかけてたんじゃない？　いいのよ、過去のことなんか気にしなくて」
line = "「また意固地になりかけてたんじゃない？　いいのよ、過去のことなんか気にしなくて」"

[[dialogue]]
speaker = "ヴィーナス"
# 「アポロを救いにいくわよ！　今の私たちは私たち史上最高に強いんだから、悩む必要なんてないじゃない！」
line = "「アポロを救いにいくわよ！　今の私たちは私たち史上最高に強いんだから、悩む必要なんてないじゃない！」"

[[dialogue]]
speaker = "サーシャ"
# 「そーそー。ヴィーナスちゃんなんか、自分が助けられたばかりなのに」
line = "「そーそー。ヴィーナスちゃんなんか、自分が助けられたばかりなのに」"

[[dialogue]]
speaker = "ヴィーナス"
# 「今度は私が助ける番ってことなんだから！」
line = "「今度は私が助ける番ってことなんだから！」"

[[dialogue]]
speaker = "クロト"
# 「頼ってくれ、フィオナ。どんなに我がままだっていい」
line = "「頼ってくれ、フィオナ。どんなに我がままだっていい」"

[[dialogue]]
speaker = "クロト"
# 「俺もずっと迷ってた。ヴィーナスがいなくなった時は、何度も己を見失いそうになった」
line = "「俺もずっと迷ってた。ヴィーナスがいなくなった時は、何度も己を見失いそうになった」"

[[dialogue]]
speaker = "クロト"
# 「でも、フィオナと一緒に修行して。乗り越えたからこそ──ヴィーナスだって助け出せたんだ」
line = "「でも、フィオナと一緒に修行して。乗り越えたからこそ──ヴィーナスだって助け出せたんだ」"

[[dialogue]]
speaker = "クロト"
# 「お姉さんも同じだ。今度はフィオナの家族のために……俺も戦わせてほしい」
line = "「お姉さんも同じだ。今度はフィオナの家族のために……俺も戦わせてほしい」"

[[dialogue]]
speaker = "ソフィア"
# 「世界の命運も大事ですが……それと同じくらい、お姉さんのことも大事です」
line = "「世界の命運も大事ですが……それと同じくらい、お姉さんのことも大事です」"

[[dialogue]]
speaker = "マトイ"
# 「そだね。もう、フィオナさんだけの話じゃないよっ」
line = "「そだね。もう、フィオナさんだけの話じゃないよっ」"

[[dialogue]]
speaker = "セーラ"
# 「ヴィーナスちゃん救出作戦には噛めなかったし──うちも参加させてもらいたいかな」
line = "「ヴィーナスちゃん救出作戦には噛めなかったし──うちも参加させてもらいたいかな」"

[[dialogue]]
speaker = "フィオナ"
# 「皆さん……ありがとうございます」
line = "「皆さん……ありがとうございます」"

[[dialogue]]
speaker = "unk"
# フィオナはうつむいていた顔を上げ、凛々しい眼差しで語った。
line = "フィオナはうつむいていた顔を上げ、凛々しい眼差しで語った。"

[[dialogue]]
speaker = "フィオナ"
# 「姉さんの姿かたちは……あの頃と変わっていません。姉妹２人でごっこ遊びをしていた、あの日から」
line = "「姉さんの姿かたちは……あの頃と変わっていません。姉妹２人でごっこ遊びをしていた、あの日から」"

[[dialogue]]
speaker = "フィオナ"
# 「けれど──私は違います。流星の仲間がいて、新星の皆さんもいる。これらの絆はすべて……星見フィオナになってから得たものです」
line = "「けれど──私は違います。流星の仲間がいて、新星の皆さんもいる。これらの絆はすべて……星見フィオナになってから得たものです」"

[[dialogue]]
speaker = "フィオナ"
# 「そして、私自身も。素直になって、人を信じることを教えてもらいました。魔王の血統なんて関係なく」
line = "「そして、私自身も。素直になって、人を信じることを教えてもらいました。魔王の血統なんて関係なく」"

[[dialogue]]
speaker = "フィオナ"
# 「この流星学園で得たもの。知ったもの。姉さんの立ち場なら、手に入れられるはずだったもの。その総てを、姉さんにぶつけます」
line = "「この流星学園で得たもの。知ったもの。姉さんの立ち場なら、手に入れられるはずだったもの。その総てを、姉さんにぶつけます」"

[[dialogue]]
speaker = "フィオナ"
# 「そして、叶うなら──姉さんを取り返したい」
line = "「そして、叶うなら──姉さんを取り返したい」"

[[dialogue]]
speaker = "クロト"
# 「ああ。きっとできる」
line = "「ああ。きっとできる」"

[[dialogue]]
speaker = "アナ"
# 「私たち<ruby=スターナイト>星騎士</ruby>は──リクリエを打倒するために組織されています。なら、敵はお姉さんではなく『使徒』でしょうね」
line = "「私たち<ruby>星騎士<rt>スターナイト</rt></ruby>は──リクリエを打倒するために組織されています。なら、敵はお姉さんではなく『使徒』でしょうね」"

[[dialogue]]
speaker = "ユウリ"
# 「あの仮面から、今度こそ解き放ってやりゃいいってわけだ」
line = "「あの仮面から、今度こそ解き放ってやりゃいいってわけだ」"

[[dialogue]]
speaker = "unk"
# そうだ。今までのことからして、俺たちの目指すべき理想は決まっている。
line = "そうだ。今までのことからして、俺たちの目指すべき理想は決まっている。"

[[dialogue]]
speaker = "クロト"
# 「アポロをリクリエから解放する。それから３０００年前と同じように──リクリエを撃退してやればいい」
line = "「アポロをリクリエから解放する。それから３０００年前と同じように──リクリエを撃退してやればいい」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なんだ、一石二鳥じゃない！」
line = "「なんだ、一石二鳥じゃない！」"

[[dialogue]]
speaker = "unk"
# それは──セイファート学園長が最後まで叶えられなかった願い。
line = "それは──セイファート学園長が最後まで叶えられなかった願い。"

[[dialogue]]
speaker = "unk"
# 俺たちの求める結末はそんな、何もかも手に入れるハッピーエンドだ。
line = "俺たちの求める結末はそんな、何もかも手に入れるハッピーエンドだ。"

[[dialogue]]
speaker = "フィオナ"
# 「向かいましょう──空の上へ。姉さんが待っています」
line = "「向かいましょう──空の上へ。姉さんが待っています」"

[[dialogue]]
speaker = "フィオナ"
# 「この夜で……すべてを終わらせます」
line = "「この夜で……すべてを終わらせます」"

[[dialogue]]
speaker = "unk"
# 必勝の誓いを胸に期す。
line = "必勝の誓いを胸に期す。"

[[dialogue]]
speaker = "unk"
# そうして俺たちは、最後の敵のもとまで駆け上がっていった──
line = "そうして俺たちは、最後の敵のもとまで駆け上がっていった──"
