[[dialogue]]
speaker = "unk"
# 第３話,煌めきへの導き,B
line = "第３話,煌めきへの導き,B"

[[dialogue]]
speaker = "unk"
# ──そうして、放課後。
line = "──そうして、放課後。"

[[dialogue]]
speaker = "ヴィーナス"
# 「みんな待たせて悪かったわね──集まってもらったのは他でもないわ。ついに進展があったのよ！」
line = "「みんな待たせて悪かったわね──集まってもらったのは他でもないわ。ついに進展があったのよ！」"

[[dialogue]]
speaker = "アナ"
# 「もしや……例の日誌が更新されましたか」
line = "「もしや……例の日誌が更新されましたか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ええ──これでようやく、こちらから動けるというものだわ」
line = "「ええ──これでようやく、こちらから動けるというものだわ」"

[[dialogue]]
speaker = "サーシャ"
# 「ここ２週間くらい、いやに平和だったものねえ」
line = "「ここ２週間くらい、いやに平和だったものねえ」"

[[dialogue]]
speaker = "ユウリ"
# 「ですね。アステラなんかも普段よりめっきり少なかったっつーか……」
line = "「ですね。アステラなんかも普段よりめっきり少なかったっつーか……」"

[[dialogue]]
speaker = "ソフィア"
# 「あれだけのことがあった後ですので、逆に薄気味悪いくらいでした」
line = "「あれだけのことがあった後ですので、逆に薄気味悪いくらいでした」"

[[dialogue]]
speaker = "フィオナ"
# 「──お聞かせいただけますか。ヴィーナスさん」
line = "「──お聞かせいただけますか。ヴィーナスさん」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ええ。クロト、そのまま読み上げちゃって」
line = "「ええ。クロト、そのまま読み上げちゃって」"

[[dialogue]]
speaker = "クロト"
# 「了解──」
line = "「了解──」"

[[dialogue]]
speaker = "クロト"
# 「『私たちは再び天高き無窮の塔を昇る』」
line = "「『私たちは再び天高き無窮の塔を昇る』」"

[[dialogue]]
speaker = "クロト"
# 「『最奥にて待ち受けるは煌竜ヴィライア。かの竜を討滅することで、星徒会はついに第三階層をも踏破する』」
line = "「『最奥にて待ち受けるは煌竜ヴィライア。かの竜を討滅することで、星徒会はついに第三階層をも踏破する』」"

[[dialogue]]
speaker = "クロト"
# 「『そして、私たちはようやく《流れ星の魔王》をその<ruby=いまし>縛</ruby>めから解き放つ……』
line = "「『そして、私たちはようやく《流れ星の魔王》をその<ruby>縛<rt>いまし</rt></ruby>めから解き放つ……』"

[[dialogue]]
speaker = "クロト"
# 「……だそうだ」
line = "「……だそうだ」"

[[dialogue]]
speaker = "アナ"
# 「無窮の塔──という表現は以前にもありましたね。フィーニスの塔のことでしたか」
line = "「無窮の塔──という表現は以前にもありましたね。フィーニスの塔のことでしたか」"

[[dialogue]]
speaker = "セーラ"
# 「最後の文、なんか意味深な感じっぽい」
line = "「最後の文、なんか意味深な感じっぽい」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ええ！　流れ星の魔王──これって、誰かさんのことを指してると思わない？」
line = "「ええ！　流れ星の魔王──これって、誰かさんのことを指してると思わない？」"

[[dialogue]]
speaker = "マトイ"
# 「もしかして……アポロのこと？」
line = "「もしかして……アポロのこと？」"

[[dialogue]]
speaker = "サーシャ"
# 「流星ライダー、とかって名乗ってたものねえ」
line = "「流星ライダー、とかって名乗ってたものねえ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そう！　でもって、イマシメっていうのは──えっと──なんだっけ？」
line = "「そう！　でもって、イマシメっていうのは──えっと──なんだっけ？」"

[[dialogue]]
speaker = "アナ"
# 「縛りつけること──捕縛、束縛といったところでしょうか」
line = "「縛りつけること──捕縛、束縛といったところでしょうか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうそれ！　つまりこれを読み解くとこうよ！」
line = "「そうそれ！　つまりこれを読み解くとこうよ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「塔のボスを倒して、第三層を攻略できれば──フィオナのお姉さんを解放できるってワケ♪」
line = "「塔のボスを倒して、第三層を攻略できれば──フィオナのお姉さんを解放できるってワケ♪」"

[[dialogue]]
speaker = "ルリエル"
# 「ほええ……なんでもお見通しなのですね。その日記さんは！」
line = "「ほええ……なんでもお見通しなのですね。その日記さんは！」"

[[dialogue]]
speaker = "ニャリオン"
# 「相変わらず原理が不明で怪しいのニャン……」
line = "「相変わらず原理が不明で怪しいのニャン……」"

[[dialogue]]
speaker = "フィオナ"
# 「ヴィーナスさんなりの解釈が入っている気もしますが──これまでの例からしても、あの塔が鍵を握っている可能性は少なくなさそうです」
line = "「ヴィーナスさんなりの解釈が入っている気もしますが──これまでの例からしても、あの塔が鍵を握っている可能性は少なくなさそうです」"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "アナ"
# 「？　どうされましたか、会長」
line = "「？　どうされましたか、会長」"

[[dialogue]]
speaker = "クロト"
# 「いや……なんでもない」
line = "「いや……なんでもない」"

[[dialogue]]
speaker = "unk"
# 『フィーニスの塔』が気にかかるというのは俺も先日、ヴィーナスに伝えていた話。
line = "『フィーニスの塔』が気にかかるというのは俺も先日、ヴィーナスに伝えていた話。"

[[dialogue]]
speaker = "unk"
# あの時は躊躇していたのに、いざ日誌に書かれるとこうも機敏に動くものか──と、やややきもきしてしまった。
line = "あの時は躊躇していたのに、いざ日誌に書かれるとこうも機敏に動くものか──と、やややきもきしてしまった。"

[[dialogue]]
speaker = "ルリエル"
# 「それにしても──その竜というのはかっこよさそうな名でありますね」
line = "「それにしても──その竜というのはかっこよさそうな名でありますね」"

[[dialogue]]
speaker = "フィオナ"
# 「……そこが問題ですね」
line = "「……そこが問題ですね」"

[[dialogue]]
speaker = "クロト"
# 「だな……」
line = "「だな……」"

[[dialogue]]
speaker = "ソフィア"
# 「？　お心当たりがあるのですか？」
line = "「？　お心当たりがあるのですか？」"

[[dialogue]]
speaker = "クロト"
# 「ああ……覚えがあるんだ」
line = "「ああ……覚えがあるんだ」"

[[dialogue]]
speaker = "フィオナ"
# 「煌竜ヴィライア……その名は」
line = "「煌竜ヴィライア……その名は」"

[[dialogue]]
speaker = "フィオナ"
# 「かつて、朱雀暦の魔界を破滅へ追いやった──魔竜ですね」
line = "「かつて、朱雀暦の魔界を破滅へ追いやった──魔竜ですね」"

[[dialogue]]
speaker = "アナ"
# 「！　異なる暦……」
line = "「！　異なる暦……」"

[[dialogue]]
speaker = "セーラ"
# 「この前話してた～……かつてあった世界、ってヤツだね」
line = "「この前話してた～……かつてあった世界、ってヤツだね」"

[[dialogue]]
speaker = "マグダレナ"
# 「煌竜ヴィライア──そう称された魔物の襲来により、あまねく生命は息絶えてしまいました」
line = "「煌竜ヴィライア──そう称された魔物の襲来により、あまねく生命は息絶えてしまいました」"

[[dialogue]]
speaker = "unk"
# ──壁画に描かれていた煌めくドラゴン。
line = "──壁画に描かれていた煌めくドラゴン。"

[[dialogue]]
speaker = "unk"
# 今の森羅暦から何代か前の世界──を終焉へと導いた存在。
line = "今の森羅暦から何代か前の世界──を終焉へと導いた存在。"

[[dialogue]]
speaker = "unk"
# 滅亡の歴史に名を刻んでいた魔竜が、あの塔に待ち構えていると日誌は言う。
line = "滅亡の歴史に名を刻んでいた魔竜が、あの塔に待ち構えていると日誌は言う。"

[[dialogue]]
speaker = "ソフィア"
# 「そ、そんな相手を倒しにいけってことですか？」
line = "「そ、そんな相手を倒しにいけってことですか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「大ボスってところね。でも大丈夫よ、最後には勝つって書いてあるんだから」
line = "「大ボスってところね。でも大丈夫よ、最後には勝つって書いてあるんだから」"

[[dialogue]]
speaker = "アナ"
# 「とはいえ──そのアイテムを信じすぎるのも危険かと」
line = "「とはいえ──そのアイテムを信じすぎるのも危険かと」"

[[dialogue]]
speaker = "アナ"
# 「それこそアポロと初めて出会った時のように、改ざんされてしまう恐れもありますし」
line = "「それこそアポロと初めて出会った時のように、改ざんされてしまう恐れもありますし」"

[[dialogue]]
speaker = "ユウリ"
# 「なんか都合よすぎる気はするよな」
line = "「なんか都合よすぎる気はするよな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「確かに絶対とは言えないわ。でも、今回の日誌にはしっかり『星徒会』って書かれてる。だから──みんなの力が必要なの。敵が強大なら、なおさらね」
line = "「確かに絶対とは言えないわ。でも、今回の日誌にはしっかり『星徒会』って書かれてる。だから──みんなの力が必要なの。敵が強大なら、なおさらね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「何より──フィオナのお姉さんのことが懸かってるんだから！」
line = "「何より──フィオナのお姉さんのことが懸かってるんだから！」"

[[dialogue]]
speaker = "unk"
# 日誌そのものへの信憑性に疑問は呈されつつも──
line = "日誌そのものへの信憑性に疑問は呈されつつも──"

[[dialogue]]
speaker = "unk"
# こちらから動ける唯一の道筋が提示されたことで、いくらか前向きになれていた。
line = "こちらから動ける唯一の道筋が提示されたことで、いくらか前向きになれていた。"

[[dialogue]]
speaker = "ユウリ"
# 「まあ内容はわかった。んで……そいつはいつ頃の出来事なんだ？」
line = "「まあ内容はわかった。んで……そいつはいつ頃の出来事なんだ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「今日よ！」
line = "「今日よ！」"

[[dialogue]]
speaker = "マトイ"
# 「今日！？」
line = "「今日！？」"

[[dialogue]]
speaker = "サーシャ"
# 「困ったわねえ。何も準備できてないのに」
line = "「困ったわねえ。何も準備できてないのに」"

[[dialogue]]
speaker = "ヴィーナス"
# 「日誌の日付を違えるわけにはいかないわ。ひとまず──みんなで塔まで行きましょ！」
line = "「日誌の日付を違えるわけにはいかないわ。ひとまず──みんなで塔まで行きましょ！」"

[[dialogue]]
speaker = "マトイ"
# 「フィーニスの塔──絶対入っちゃダメって言われてるのに」
line = "「フィーニスの塔──絶対入っちゃダメって言われてるのに」"

[[dialogue]]
speaker = "ソフィア"
# 「両学園の星徒会が侵入したと知れたら、大問題ですね……」
line = "「両学園の星徒会が侵入したと知れたら、大問題ですね……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「大丈夫大丈夫♪　私たちはもう何度も入ってるから──ね、フィオナ」
line = "「大丈夫大丈夫♪　私たちはもう何度も入ってるから──ね、フィオナ」"

[[dialogue]]
speaker = "フィオナ"
# 「う……は、はい」
line = "「う……は、はい」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふふ。会長くん達から聞いてはいるけど、中が見てみたいものよね」
line = "「ふふふ。会長くん達から聞いてはいるけど、中が見てみたいものよね」"

[[dialogue]]
speaker = "ルリエル"
# 「確かに……立ち入り厳禁と言われるほど、気になってしまうものであります！」
line = "「確かに……立ち入り厳禁と言われるほど、気になってしまうものであります！」"

[[dialogue]]
speaker = "ユウリ"
# 「どっから入りゃいいんだ？」
line = "「どっから入りゃいいんだ？」"

[[dialogue]]
speaker = "クロト"
# 「勝手に招かれるようになってる。恐らく、ヴィーナスの存在をキーとして」
line = "「勝手に招かれるようになってる。恐らく、ヴィーナスの存在をキーとして」"

[[dialogue]]
speaker = "unk"
# 塔の内部からは常にヴィーナスを呼ぶ『声』がしていた。
line = "塔の内部からは常にヴィーナスを呼ぶ『声』がしていた。"

[[dialogue]]
speaker = "unk"
# 恐らく彼女についていけば、他の面々も共に塔の中へ入れるはずだ。
line = "恐らく彼女についていけば、他の面々も共に塔の中へ入れるはずだ。"

[[dialogue]]
speaker = "unk"
# そこへ……
line = "そこへ……"

[[dialogue]]
speaker = "アニュラス"
# 「──待て、星徒会」
line = "「──待て、星徒会」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あら？　この声は……」
line = "「あら？　この声は……」"

[[dialogue]]
speaker = "アニュラス"
# 「話は聞いたぞ。ドラゴン退治に行くのだな」
line = "「話は聞いたぞ。ドラゴン退治に行くのだな」"

[[dialogue]]
speaker = "クロト"
# 「どこで聞いてたの……？」
line = "「どこで聞いてたの……？」"

[[dialogue]]
speaker = "アニュラス"
# 「そんなことはどうでもいい。私も連れて行け。数多の精鋭と修行して鍛えたこの魔剣──必ずや役に立つ」
line = "「そんなことはどうでもいい。私も連れて行け。数多の精鋭と修行して鍛えたこの魔剣──必ずや役に立つ」"

[[dialogue]]
speaker = "unk"
# どこからか事情を聞きつけていたアニュラスは、赤黒くきらめいた剣を抜いて俺たちに示した。
line = "どこからか事情を聞きつけていたアニュラスは、赤黒くきらめいた剣を抜いて俺たちに示した。"

[[dialogue]]
speaker = "unk"
# ひしひしと感じる星力の強さは星徒会メンバーのそれと比べても遜色ない。
line = "ひしひしと感じる星力の強さは星徒会メンバーのそれと比べても遜色ない。"

[[dialogue]]
speaker = "アニュラス"
# 「それに緋宮クロト！　おまえは先ほどしきりに眼をこすっていたな──戦士に寝不足などあってはならない！」
line = "「それに緋宮クロト！　おまえは先ほどしきりに眼をこすっていたな──戦士に寝不足などあってはならない！」"

[[dialogue]]
speaker = "クロト"
# 「よく見てるなあ……ちょっと夜更かししちゃっただけだよ」
line = "「よく見てるなあ……ちょっと夜更かししちゃっただけだよ」"

[[dialogue]]
speaker = "ルリエル"
# 「あ、アニュラスさん。こんなところで」
line = "「あ、アニュラスさん。こんなところで」"

[[dialogue]]
speaker = "アニュラス"
# 「む、ルリエル殿か。ちょうどいい。あなたも説得してくれ」
line = "「む、ルリエル殿か。ちょうどいい。あなたも説得してくれ」"

[[dialogue]]
speaker = "ユウリ"
# 「戦闘じゃなくてもその仮面してんのか……？」
line = "「戦闘じゃなくてもその仮面してんのか……？」"

[[dialogue]]
speaker = "アニュラス"
# 「悪いか！？　ああいや先輩？　悪いですか！？」
line = "「悪いか！？　ああいや先輩？　悪いですか！？」"

[[dialogue]]
speaker = "セーラ"
# 「おバカなのか律儀なのか、よくわかんないコだよね～」
line = "「おバカなのか律儀なのか、よくわかんないコだよね～」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふふ。でもそういう子、可愛いわ～」
line = "「ふふふ。でもそういう子、可愛いわ～」"

[[dialogue]]
speaker = "ソフィア"
# （むっ……）
line = "（むっ……）"

[[dialogue]]
speaker = "マトイ"
# （初めて見る子だけど……）
line = "（初めて見る子だけど……）"

[[dialogue]]
speaker = "アナ"
# （セイファート学園長の娘。クロト会長とは何やらただならぬ関係にある模様）
line = "（セイファート学園長の娘。クロト会長とは何やらただならぬ関係にある模様）"

[[dialogue]]
speaker = "クロト"
# （言い方）
line = "（言い方）"

[[dialogue]]
speaker = "unk"
# 一方的にライバル視されているというだけで、やましい縁ではない。
line = "一方的にライバル視されているというだけで、やましい縁ではない。"

[[dialogue]]
speaker = "unk"
# にしても……
line = "にしても……"

[[dialogue]]
speaker = "ルリエル"
# 「アニュラスさん。これからわたし達がどこへ行くかわかっておられますか……？」
line = "「アニュラスさん。これからわたし達がどこへ行くかわかっておられますか……？」"

[[dialogue]]
speaker = "アニュラス"
# 「ああ。フィーニスの塔、だろう」
line = "「ああ。フィーニスの塔、だろう」"

[[dialogue]]
speaker = "アニュラス"
# 「フィーニスの塔といえば流星市国のシンボル──しかしその面はあくまで表の顔」
line = "「フィーニスの塔といえば流星市国のシンボル──しかしその面はあくまで表の顔」"

[[dialogue]]
speaker = "アニュラス"
# 「本来は魔界、人間界、天界を繋ぐ──４０００階にも及ぶ神々の連絡塔。お前たちはこの塔で三界の摂理を司る守護天使とも出会っている」
line = "「本来は魔界、人間界、天界を繋ぐ──４０００階にも及ぶ神々の連絡塔。お前たちはこの塔で三界の摂理を司る守護天使とも出会っている」"

[[dialogue]]
speaker = "ソフィア"
# 「！　守護天使のことまで……」
line = "「！　守護天使のことまで……」"

[[dialogue]]
speaker = "クロト"
# 「どうして一緒に来たいんだ？」
line = "「どうして一緒に来たいんだ？」"

[[dialogue]]
speaker = "アニュラス"
# 「決まっている。目覚ましい戦果を上げることが、お父様に認められる近道だからだ」
line = "「決まっている。目覚ましい戦果を上げることが、お父様に認められる近道だからだ」"

[[dialogue]]
speaker = "アニュラス"
# 「おまえ達が目立った成果を上げてきたのはわかっている。お父様にあれだけ目をかけられているのだからな」
line = "「おまえ達が目立った成果を上げてきたのはわかっている。お父様にあれだけ目をかけられているのだからな」"

[[dialogue]]
speaker = "アニュラス"
# 「しかし私も！　腕では決して劣るものではないと自負している。ダンジョン攻略なら決して引けを取らないぞ！」
line = "「しかし私も！　腕では決して劣るものではないと自負している。ダンジョン攻略なら決して引けを取らないぞ！」"

[[dialogue]]
speaker = "ユウリ"
# （へえ。根性ありそーな一年じゃねーか）
line = "（へえ。根性ありそーな一年じゃねーか）"

[[dialogue]]
speaker = "ソフィア"
# （新星の学園長さんの娘ですし）
line = "（新星の学園長さんの娘ですし）"

[[dialogue]]
speaker = "クロト"
# （実力は確かだよ）
line = "（実力は確かだよ）"

[[dialogue]]
speaker = "ヴィーナス"
# 「よくわからないけれど、確かに中々腕が立ちそうだわ！　ちょうど今は戦力をかき集めたかったところだし」
line = "「よくわからないけれど、確かに中々腕が立ちそうだわ！　ちょうど今は戦力をかき集めたかったところだし」"

[[dialogue]]
speaker = "アニュラス"
# 「おお！　新星の元会長殿……ならば」
line = "「おお！　新星の元会長殿……ならば」"

[[dialogue]]
speaker = "サーシャ"
# 「は～い、きびだんごをあげますからねえ～」
line = "「は～い、きびだんごをあげますからねえ～」"

[[dialogue]]
speaker = "アニュラス"
# 「む、よいのですか──じゃない！　私をイヌ猿キジと一緒にするな！」
line = "「む、よいのですか──じゃない！　私をイヌ猿キジと一緒にするな！」"

[[dialogue]]
speaker = "サーシャ"
# 「やっぱり可愛いわねぇ～」
line = "「やっぱり可愛いわねぇ～」"

[[dialogue]]
speaker = "unk"
# アニュラスもパーティご一行に──と思いきや。
line = "アニュラスもパーティご一行に──と思いきや。"

[[dialogue]]
speaker = "フィオナ"
# 「──いえ。セイファートさん、あなたは地上に留まっていてください」
line = "「──いえ。セイファートさん、あなたは地上に留まっていてください」"

[[dialogue]]
speaker = "アニュラス"
# 「！？　なぜですか、星見会長……今の私では不足と仰るのですか」
line = "「！？　なぜですか、星見会長……今の私では不足と仰るのですか」"

[[dialogue]]
speaker = "フィオナ"
# 「いいえ。むしろ、逆です。今の流星市国は度重なる異変の生じている非常事態──あまり戦力を分散させるのは好ましくありません」
line = "「いいえ。むしろ、逆です。今の流星市国は度重なる異変の生じている非常事態──あまり戦力を分散させるのは好ましくありません」"

[[dialogue]]
speaker = "ソフィア"
# 「確かに……いつ<b>彼女</b>がこちらに現れてもおかしくありません」
line = "「確かに……いつ<b>彼女</b>がこちらに現れてもおかしくありません」"

[[dialogue]]
speaker = "アニュラス"
# 「う……で、ですが……」
line = "「う……で、ですが……」"

[[dialogue]]
speaker = "セーラ"
# 「うちらもなるべくチャチャッと帰ってこないとね～」
line = "「うちらもなるべくチャチャッと帰ってこないとね～」"

[[dialogue]]
speaker = "unk"
# フィオナの態度は毅然としたものだった。
line = "フィオナの態度は毅然としたものだった。"

[[dialogue]]
speaker = "unk"
# アニュラスの実力を信頼しているからこそ、軽々しく連れていくわけにはいかないのだろう。
line = "アニュラスの実力を信頼しているからこそ、軽々しく連れていくわけにはいかないのだろう。"

[[dialogue]]
speaker = "ヴィーナス"
# 「学園長から許可もらってくればいいんじゃないの？　娘なのよね！？」
line = "「学園長から許可もらってくればいいんじゃないの？　娘なのよね！？」"

[[dialogue]]
speaker = "アニュラス"
# 「お、お父様からは……星見会長の判断に従えと。お父様はあくまで、新星の学園長なので……」
line = "「お、お父様からは……星見会長の判断に従えと。お父様はあくまで、新星の学園長なので……」"

[[dialogue]]
speaker = "アナ"
# 「まあ、妥当な判断ですね」
line = "「まあ、妥当な判断ですね」"

[[dialogue]]
speaker = "unk"
# アニュラスはしばらくもにょもにょしていたが、やがて納得したのかキリッと居住まいを正した。
line = "アニュラスはしばらくもにょもにょしていたが、やがて納得したのかキリッと居住まいを正した。"

[[dialogue]]
speaker = "アニュラス"
# 「く……わかりました。星見会長の命とあらば仕方ありません。今の私ではまだ実力不足というわけですね」
line = "「く……わかりました。星見会長の命とあらば仕方ありません。今の私ではまだ実力不足というわけですね」"

[[dialogue]]
speaker = "フィオナ"
# 「あ、いえ、そういうわけではなく逆で……」
line = "「あ、いえ、そういうわけではなく逆で……」"

[[dialogue]]
speaker = "アニュラス"
# 「いつかお父様にも、星見会長にも認めてもらえるような<ruby=スターナイト>星騎士</ruby>となって……目にもの見せてやるぞ。待っていろ、緋宮クロト！」
line = "「いつかお父様にも、星見会長にも認めてもらえるような<ruby>星騎士<rt>スターナイト</rt></ruby>となって……目にもの見せてやるぞ。待っていろ、緋宮クロト！」"

[[dialogue]]
speaker = "アナ"
# 「あまり人の話を聞かない方のようです」
line = "「あまり人の話を聞かない方のようです」"

[[dialogue]]
speaker = "クロト"
# 「別に俺は敵じゃないんだけどな……」
line = "「別に俺は敵じゃないんだけどな……」"

[[dialogue]]
speaker = "マトイ"
# 「あはは。好かれてるんだね、会長」
line = "「あはは。好かれてるんだね、会長」"

[[dialogue]]
speaker = "unk"
# アニュラスがいなくなって──
line = "アニュラスがいなくなって──"

[[dialogue]]
speaker = "unk"
# その場に残った俺たちは、いよいよ立ちはだかる塔の前に立った。
line = "その場に残った俺たちは、いよいよ立ちはだかる塔の前に立った。"

[[dialogue]]
speaker = "フィオナ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "フィオナ"
# 「本当に……よいのでしょうか」
line = "「本当に……よいのでしょうか」"

[[dialogue]]
speaker = "フィオナ"
# 「この先には恐らく──かつてないほどの脅威が待っています。そんな死地に、みんなを連れていくなんて……」
line = "「この先には恐らく──かつてないほどの脅威が待っています。そんな死地に、みんなを連れていくなんて……」"

[[dialogue]]
speaker = "ソフィア"
# 「……言いっこなしですよ、フィオナ会長」
line = "「……言いっこなしですよ、フィオナ会長」"

[[dialogue]]
speaker = "ソフィア"
# 「お姉さんを救いたいという気持ちは──ヴィーナスさんだけじゃありません。たとえ、会長ご自身が否定されたとしても」
line = "「お姉さんを救いたいという気持ちは──ヴィーナスさんだけじゃありません。たとえ、会長ご自身が否定されたとしても」"

[[dialogue]]
speaker = "ユウリ"
# 「だな。ま、頑固なのは知ってっから今さらだ」
line = "「だな。ま、頑固なのは知ってっから今さらだ」"

[[dialogue]]
speaker = "セーラ"
# 「まーねー。それにこの塔の中、いっつも会長さん達だけでずるいし♪」
line = "「まーねー。それにこの塔の中、いっつも会長さん達だけでずるいし♪」"

[[dialogue]]
speaker = "フィオナ"
# 「みんな……」
line = "「みんな……」"

[[dialogue]]
speaker = "マトイ"
# （フィオナさんって……流星のみんなから、すごく信頼されてるよね）
line = "（フィオナさんって……流星のみんなから、すごく信頼されてるよね）"

[[dialogue]]
speaker = "アナ"
# （どこぞの自称フィクサーとはえらい違いですね）
line = "（どこぞの自称フィクサーとはえらい違いですね）"

[[dialogue]]
speaker = "ヴィーナス"
# （誰のこと？）
line = "（誰のこと？）"

[[dialogue]]
speaker = "unk"
# <ruby=おれたち>新星星徒会</ruby>にしたって気持ちは同じだ。
line = "<ruby>新星星徒会<rt>おれたち</rt></ruby>にしたって気持ちは同じだ。"

[[dialogue]]
speaker = "unk"
# 現状を打破したいという想いを胸に──みんなで塔の前へ立つ。
line = "現状を打破したいという想いを胸に──みんなで塔の前へ立つ。"

[[dialogue]]
speaker = "unk"
# いつもの調子なら、このまま内部へ招かれて──
line = "いつもの調子なら、このまま内部へ招かれて──"

[[dialogue]]
speaker = "クロト"
# （────っ）
line = "（────っ）"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "マトイ"
# 「？　どしたの、緋宮くん」
line = "「？　どしたの、緋宮くん」"

[[dialogue]]
speaker = "クロト"
# 「………………いや」
line = "「………………いや」"

[[dialogue]]
speaker = "unk"
# 振り向いた先には──誰もいなかった。
line = "振り向いた先には──誰もいなかった。"

[[dialogue]]
speaker = "unk"
# 一瞬、刺すような気配を覚えたが……。
line = "一瞬、刺すような気配を覚えたが……。"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら。まだあの子が見ていたのかしら」
line = "「あらあら。まだあの子が見ていたのかしら」"

[[dialogue]]
speaker = "クロト"
# 「いえ……アニュラスは校舎のほうへ去っていきましたが……」
line = "「いえ……アニュラスは校舎のほうへ去っていきましたが……」"

[[dialogue]]
speaker = "クロト"
# （気のせい──では、なさそうだが。これ以上気配は追えないな）
line = "（気のせい──では、なさそうだが。これ以上気配は追えないな）"

[[dialogue]]
speaker = "unk"
# どうやら彼女以外にも、俺たちの動向を気にかけている人物がいるようだ。
line = "どうやら彼女以外にも、俺たちの動向を気にかけている人物がいるようだ。"

[[dialogue]]
speaker = "unk"
# ソフィアちゃんの言っていたように、見咎められたら校則違反になってしまうが──その報いは後で受けるとしよう。
line = "ソフィアちゃんの言っていたように、見咎められたら校則違反になってしまうが──その報いは後で受けるとしよう。"

[[dialogue]]
speaker = "ヴィーナス"
# 「さあ、行くわよみんな──準備はいい？」
line = "「さあ、行くわよみんな──準備はいい？」"

[[dialogue]]
speaker = "クロト"
# 「ああ。もちろんだ。アポロを解放するためにも──必ず塔を攻略しよう」
line = "「ああ。もちろんだ。アポロを解放するためにも──必ず塔を攻略しよう」"

[[dialogue]]
speaker = "unk"
# 何者かの影を背後に感じつつも──
line = "何者かの影を背後に感じつつも──"

[[dialogue]]
speaker = "unk"
# 俺たちは初のフルメンバーで、フィーニスの塔へ突入した。
line = "俺たちは初のフルメンバーで、フィーニスの塔へ突入した。"
