[[dialogue]]
speaker = "unk"
# 第５話,もしも……,B
line = "第５話,もしも……,B"

[[dialogue]]
speaker = "unk"
# 本日も快晴。アステラの発生はなし──
line = "本日も快晴。アステラの発生はなし──"

[[dialogue]]
speaker = "unk"
# 私は日課となっている会長日誌への記述を終えて、ぱたりと閉じる。
line = "私は日課となっている会長日誌への記述を終えて、ぱたりと閉じる。"

[[dialogue]]
speaker = "ルヴィネ"
# 「……ふう」
line = "「……ふう」"

[[dialogue]]
speaker = "レティシア"
# 「お疲れ様ルヴィ。紅茶をどうぞ？」
line = "「お疲れ様ルヴィ。紅茶をどうぞ？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ありがとうレティシア。いただくわ」
line = "「ありがとうレティシア。いただくわ」"

[[dialogue]]
speaker = "unk"
# 極星学園に転入してはや数ヵ月──
line = "極星学園に転入してはや数ヵ月──"

[[dialogue]]
speaker = "unk"
# 私は、稀なくらいの『星力』総量を持っているという理由で、留学したばかりなのに星徒会長を任されることになってしまった。
line = "私は、稀なくらいの『星力』総量を持っているという理由で、留学したばかりなのに星徒会長を任されることになってしまった。"

[[dialogue]]
speaker = "unk"
# 役員は星徒会長による指名式だ。留学したばかりで右も左もわからないのに、人員を集めなくてはいけなかったから大変だった。
line = "役員は星徒会長による指名式だ。留学したばかりで右も左もわからないのに、人員を集めなくてはいけなかったから大変だった。"

[[dialogue]]
speaker = "unk"
# レティシアは、そんな私のスカウトを二つ返事で引き受けてくれた、１学年先輩の天使の女の子。とても優しくて気が利くお姉さんだ。
line = "レティシアは、そんな私のスカウトを二つ返事で引き受けてくれた、１学年先輩の天使の女の子。とても優しくて気が利くお姉さんだ。"

[[dialogue]]
speaker = "グレイス"
# 「あれれ？　今度の大交流の名簿が見つかりません……！　家に忘れてきちゃいましたかね。お母さんにメールして聞いてみましょう」
line = "「あれれ？　今度の大交流の名簿が見つかりません……！　家に忘れてきちゃいましたかね。お母さんにメールして聞いてみましょう」"

[[dialogue]]
speaker = "チナ"
# 「お前なあ。だから持ち帰って仕事はするなって言っただろ……てか、これじゃね？」
line = "「お前なあ。だから持ち帰って仕事はするなって言っただろ……てか、これじゃね？」"

[[dialogue]]
speaker = "グレイス"
# 「おぉ！　流石ですチナ！」
line = "「おぉ！　流石ですチナ！」"

[[dialogue]]
speaker = "unk"
# あの２人はチナとグレイス。レティシアと同じく、数ヵ月前に私が勧誘した星徒会の役員だ。
line = "あの２人はチナとグレイス。レティシアと同じく、数ヵ月前に私が勧誘した星徒会の役員だ。"

[[dialogue]]
speaker = "unk"
# グレイスは２年生で、チナは１つ歳下なのだけど……どっちがお姉さんかわからないわね。
line = "グレイスは２年生で、チナは１つ歳下なのだけど……どっちがお姉さんかわからないわね。"

[[dialogue]]
speaker = "チナ"
# 「あ、そうだルヴィ。母さんたちがさ、また家で夕食はどうかって言ってたぞ」
line = "「あ、そうだルヴィ。母さんたちがさ、また家で夕食はどうかって言ってたぞ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「そうなの？　わかった、バイトのシフトを調整しておくわね」
line = "「そうなの？　わかった、バイトのシフトを調整しておくわね」"

[[dialogue]]
speaker = "unk"
# 学業と星騎士活動とアルバイト、すべてをこなすのは大変だけれど……とても楽しい。
line = "学業と星騎士活動とアルバイト、すべてをこなすのは大変だけれど……とても楽しい。"

[[dialogue]]
speaker = "unk"
# 大交流で天界から留学する前は、こんなに楽しい日々が待っているだなんて思わなかった──
line = "大交流で天界から留学する前は、こんなに楽しい日々が待っているだなんて思わなかった──"

[[dialogue]]
speaker = "ベアトリス"
# 「みんな、お疲れ様～！」
line = "「みんな、お疲れ様～！」"

[[dialogue]]
speaker = "unk"
# 彼女はベアトリス──魔界からの留学生。
line = "彼女はベアトリス──魔界からの留学生。"

[[dialogue]]
speaker = "unk"
# 私と同じタイミングの大交流で人間界にやってきて、一番最初に友人となった吸血鬼の女の子で──
line = "私と同じタイミングの大交流で人間界にやってきて、一番最初に友人となった吸血鬼の女の子で──"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………？」
line = "「…………？」"

[[dialogue]]
speaker = "unk"
# ……どうしてだろう、彼女の姿を見た瞬間、違和感を覚えてしまった。
line = "……どうしてだろう、彼女の姿を見た瞬間、違和感を覚えてしまった。"

[[dialogue]]
speaker = "？？？"
# 『────ルヴィネ』
line = "『────ルヴィネ』"

[[dialogue]]
speaker = "？？？"
# 『いけません──それ以上、そこにいては──』
line = "『いけません──それ以上、そこにいては──』"

[[dialogue]]
speaker = "ベアトリス"
# 「ルヴィ？　どうかしたの、ぼーっとして」
line = "「ルヴィ？　どうかしたの、ぼーっとして」"

[[dialogue]]
speaker = "ルヴィネ"
# 「えっ……あっ……いいえ。何でもないわ……」
line = "「えっ……あっ……いいえ。何でもないわ……」"

[[dialogue]]
speaker = "レティシア"
# 「ふふ。星徒会長さんはお疲れみたい。今日はお休みにして、みんなで遊びに行きましょうか」
line = "「ふふ。星徒会長さんはお疲れみたい。今日はお休みにして、みんなで遊びに行きましょうか」"

[[dialogue]]
speaker = "グレイス"
# 「いいですね！　美味しいものを食べに行きましょう！」
line = "「いいですね！　美味しいものを食べに行きましょう！」"

[[dialogue]]
speaker = "ベアトリス"
# 「あっ、それだったらとっておきのニンニク料理専門店があって──」
line = "「あっ、それだったらとっておきのニンニク料理専門店があって──」"

[[dialogue]]
speaker = "unk"
# いつも通りの日常。何もおかしいことなんてない。
line = "いつも通りの日常。何もおかしいことなんてない。"

[[dialogue]]
speaker = "unk"
# …………そう、よね？
line = "…………そう、よね？"

[[dialogue]]
speaker = "チナ"
# 「はむっ！　もぐっ！　もぐもぐっ……！」
line = "「はむっ！　もぐっ！　もぐもぐっ……！」"

[[dialogue]]
speaker = "エステル"
# 「わっ。プリンにシュークリーム、凄い量ですね……！　ルヴィネ会長、これは？」
line = "「わっ。プリンにシュークリーム、凄い量ですね……！　ルヴィネ会長、これは？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「先日の出撃でチナが助けた子供が、桜十路の人だったらしくて。お礼が届いたのよ」
line = "「先日の出撃でチナが助けた子供が、桜十路の人だったらしくて。お礼が届いたのよ」"

[[dialogue]]
speaker = "チナ"
# 「絶品だぞこれ！　やっぱ人助けってのは最高だな！！」
line = "「絶品だぞこれ！　やっぱ人助けってのは最高だな！！」"

[[dialogue]]
speaker = "チナ"
# 「ルヴィもエステルも食べろ食べろ！　グレイスが来ないうちが勝負だからな！」
line = "「ルヴィもエステルも食べろ食べろ！　グレイスが来ないうちが勝負だからな！」"

[[dialogue]]
speaker = "エステル"
# 「あ、は、はい……」
line = "「あ、は、はい……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「──グレイスからメッセージが来たわ。『飛んで向かいます』ですって」
line = "「──グレイスからメッセージが来たわ。『飛んで向かいます』ですって」"

[[dialogue]]
speaker = "チナ"
# 「っ！？　市国の外に出かけてるから、時間かかると思ってたのに──こうしちゃいられない！　もぐもぐもぐっ！」
line = "「っ！？　市国の外に出かけてるから、時間かかると思ってたのに──こうしちゃいられない！　もぐもぐもぐっ！」"

[[dialogue]]
speaker = "エステル"
# 「そ、そんなにがっついたら胸やけしてしまいますよ……！」
line = "「そ、そんなにがっついたら胸やけしてしまいますよ……！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ふふふっ……」
line = "「ふふふっ……」"

[[dialogue]]
speaker = "unk"
# 世界は平和そのもの。私が欲しいものは、全てここにある──でも。
line = "世界は平和そのもの。私が欲しいものは、全てここにある──でも。"

[[dialogue]]
speaker = "ベアトリス"
# 「ふん、ふん、ふーん♪」
line = "「ふん、ふん、ふーん♪」"

[[dialogue]]
speaker = "unk"
# 花壇の花に、水やりをしているベアトを見ると、やっぱり胸がざわざわする──
line = "花壇の花に、水やりをしているベアトを見ると、やっぱり胸がざわざわする──"

[[dialogue]]
speaker = "unk"
# どこかがおかしい、そんな違和感を振り払うように……
line = "どこかがおかしい、そんな違和感を振り払うように……"

[[dialogue]]
speaker = "ルヴィネ"
# 「チナったらもう……詰め込みすぎよ！　あはははははっ！」
line = "「チナったらもう……詰め込みすぎよ！　あはははははっ！」"

[[dialogue]]
speaker = "unk"
# 笑わなければ──いけない気がした。
line = "笑わなければ──いけない気がした。"

[[dialogue]]
speaker = "チナ"
# 「よーっし、撮るぞ～？　祝、限定クレープゲット記念！」
line = "「よーっし、撮るぞ～？　祝、限定クレープゲット記念！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「はむっ♪」
line = "「はむっ♪」"

[[dialogue]]
speaker = "unk"
# 撮影される瞬間に、ベアトの持っているクレープにかじりつく。
line = "撮影される瞬間に、ベアトの持っているクレープにかじりつく。"

[[dialogue]]
speaker = "ベアトリス"
# 「きゃ～っ！？」
line = "「きゃ～っ！？」"

[[dialogue]]
speaker = "チナ"
# 「ルヴィ、どした？　なんかずいぶんテンション高いじゃん」
line = "「ルヴィ、どした？　なんかずいぶんテンション高いじゃん」"

[[dialogue]]
speaker = "ルヴィネ"
# 「そう？　私はいつもこんなじゃないかしら！」
line = "「そう？　私はいつもこんなじゃないかしら！」"

[[dialogue]]
speaker = "ベアトリス"
# 「お、お返しだよルヴィ！　そっちのクレープ──はむんっ！」
line = "「お、お返しだよルヴィ！　そっちのクレープ──はむんっ！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ちょっ──わ、私の一口より絶対に大きいじゃない！？」
line = "「ちょっ──わ、私の一口より絶対に大きいじゃない！？」"

[[dialogue]]
speaker = "ベアトリス"
# 「えへへ、お返しだもん！」
line = "「えへへ、お返しだもん！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「やったわね～……お返しのお返しをしてあげるわ！」
line = "「やったわね～……お返しのお返しをしてあげるわ！」"

[[dialogue]]
speaker = "チナ"
# 「子供みたいだぞ、２人とも……もぐもぐ。んまいなコレ！」
line = "「子供みたいだぞ、２人とも……もぐもぐ。んまいなコレ！」"

[[dialogue]]
speaker = "unk"
# 自分でもテンションがおかしいことは承知している。だけど……
line = "自分でもテンションがおかしいことは承知している。だけど……"

[[dialogue]]
speaker = "ルヴィネ"
# 「あはははははっ♪」
line = "「あはははははっ♪」"

[[dialogue]]
speaker = "unk"
# 笑っていないと──
line = "笑っていないと──"

[[dialogue]]
speaker = "unk"
# 怖くて、仕方がないの──
line = "怖くて、仕方がないの──"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………怖い。怖いわ……」
line = "「…………怖い。怖いわ……」"

[[dialogue]]
speaker = "unk"
# この数日で──私の恐怖心は限界にまで膨れ上がっていた。
line = "この数日で──私の恐怖心は限界にまで膨れ上がっていた。"

[[dialogue]]
speaker = "unk"
# 街全体に違和感がある。決定的なボタンを掛け違っているような、居心地の悪さ……
line = "街全体に違和感がある。決定的なボタンを掛け違っているような、居心地の悪さ……"

[[dialogue]]
speaker = "ルヴィネ"
# 「……セレスティア」
line = "「……セレスティア」"

[[dialogue]]
speaker = "unk"
# 大交流で留学してから、肌身離さず持ち続けているはずのデバイスを見ると、胸が締め付けられるように苦しい。
line = "大交流で留学してから、肌身離さず持ち続けているはずのデバイスを見ると、胸が締め付けられるように苦しい。"

[[dialogue]]
speaker = "ルヴィネ"
# 「どうして、こんなにも苦しいの……？」
line = "「どうして、こんなにも苦しいの……？」"

[[dialogue]]
speaker = "？？？"
# 『──それは、貴女が真実から目を背けているからです』
line = "『──それは、貴女が真実から目を背けているからです』"

[[dialogue]]
speaker = "ルヴィネ"
# 「……っ！？　また、この声……！　誰、誰なの！？　私をどうするつもり！？」
line = "「……っ！？　また、この声……！　誰、誰なの！？　私をどうするつもり！？」"

[[dialogue]]
speaker = "？？？"
# 『落ち着いてください……このままここにいては、貴女は本当に戻れなくなってしまいます』
line = "『落ち着いてください……このままここにいては、貴女は本当に戻れなくなってしまいます』"

[[dialogue]]
speaker = "？？？"
# 『本当に大切なものを、思い出してください……』
line = "『本当に大切なものを、思い出してください……』"

[[dialogue]]
speaker = "ルヴィネ"
# 「やめて……大切なものは、ここにあるわ──」
line = "「やめて……大切なものは、ここにあるわ──」"

[[dialogue]]
speaker = "unk"
# ずっと。ずっとずっとずっと、欲しかった。それは全てここに──
line = "ずっと。ずっとずっとずっと、欲しかった。それは全てここに──"

[[dialogue]]
speaker = "？？？"
# 『いいえ。貴女の本当に大切なものは……ここではない場所に──』
line = "『いいえ。貴女の本当に大切なものは……ここではない場所に──』"

[[dialogue]]
speaker = "ルヴィネ"
# 「………………ぁ」
line = "「………………ぁ」"

[[dialogue]]
speaker = "？？？"
# 『眼をそらさないで、受け入れるのです。そうでないと、貴女は本当に死んでしまう────』
line = "『眼をそらさないで、受け入れるのです。そうでないと、貴女は本当に死んでしまう────』"

[[dialogue]]
speaker = "ルヴィネ"
# 「……ぁ……ぁああぁあっ……！！」
line = "「……ぁ……ぁああぁあっ……！！」"

[[dialogue]]
speaker = "unk"
# 私は、ルヴィネ。
line = "私は、ルヴィネ。"

[[dialogue]]
speaker = "unk"
# 私は────女神の幼体。
line = "私は────女神の幼体。"

[[dialogue]]
speaker = "unk"
# リクリエを起こすために遣わされ、そしてお父様に見捨てられて……今まさに死のうとしている、ただの抜け殻……
line = "リクリエを起こすために遣わされ、そしてお父様に見捨てられて……今まさに死のうとしている、ただの抜け殻……"

[[dialogue]]
speaker = "unk"
# この世界は、死の間際の私が見た、<ruby=うたかた>泡沫</ruby>の夢──
line = "この世界は、死の間際の私が見た、<ruby>泡沫<rt>うたかた</rt></ruby>の夢──"
