[[dialogue]]
speaker = "unk"
# 第３話,天敵・ツェツィーリエ,B
line = "第３話,天敵・ツェツィーリエ,B"

[[dialogue]]
speaker = "unk"
# セドナが休憩に入った後も、ウェンディは指令室で事後処理を行っていた。
line = "セドナが休憩に入った後も、ウェンディは指令室で事後処理を行っていた。"

[[dialogue]]
speaker = "unk"
# それもあらかた終わり、改めてネビュラの財政事情に思考を巡らせる。
line = "それもあらかた終わり、改めてネビュラの財政事情に思考を巡らせる。"

[[dialogue]]
speaker = "ウェンディ"
# 「うーん……だめだぁ。このままじゃ到底、組織を維持していくことなんて出来ない」
line = "「うーん……だめだぁ。このままじゃ到底、組織を維持していくことなんて出来ない」"

[[dialogue]]
speaker = "ウェンディ"
# （リクリエを乗り越えたら、元老会はネビュラを解体しにかかるだろうとは思ってました）
line = "（リクリエを乗り越えたら、元老会はネビュラを解体しにかかるだろうとは思ってました）"

[[dialogue]]
speaker = "ウェンディ"
# （資金の援助が打ち切られるだろうってことも読めてたんですけど……）
line = "（資金の援助が打ち切られるだろうってことも読めてたんですけど……）"

[[dialogue]]
speaker = "ウェンディ"
# （まあ、それは仕方ないです。あくまでネビュラは対リクリエのための一組織に過ぎないんだから）
line = "（まあ、それは仕方ないです。あくまでネビュラは対リクリエのための一組織に過ぎないんだから）"

[[dialogue]]
speaker = "ウェンディ"
# （だから私はリクリエ後も、ネビュラという組織が単独で存続していく道筋を考えました）
line = "（だから私はリクリエ後も、ネビュラという組織が単独で存続していく道筋を考えました）"

[[dialogue]]
speaker = "ウェンディ"
# （人間界で作った資金を滅亡前に回収。その資金を使ってネビュラを維持しつつ、再生された人間界の経済活動をコントロールする）
line = "（人間界で作った資金を滅亡前に回収。その資金を使ってネビュラを維持しつつ、再生された人間界の経済活動をコントロールする）"

[[dialogue]]
speaker = "ウェンディ"
# （組織としては人員を縮小することになるでしょうけど、リクリエという最大の脅威が去っているのだから大きな問題にはならない）
line = "（組織としては人員を縮小することになるでしょうけど、リクリエという最大の脅威が去っているのだから大きな問題にはならない）"

[[dialogue]]
speaker = "ウェンディ"
# （そこで経済基盤を築いて、それを元に魔女の森へ人間界の『経済学』を輸入する）
line = "（そこで経済基盤を築いて、それを元に魔女の森へ人間界の『経済学』を輸入する）"

[[dialogue]]
speaker = "ウェンディ"
# （この啓蒙が成功すれば、後進的な魔女の森もようやく天界、魔界、人間界と肩を並べることが出来る──はずだったのに）
line = "（この啓蒙が成功すれば、後進的な魔女の森もようやく天界、魔界、人間界と肩を並べることが出来る──はずだったのに）"

[[dialogue]]
speaker = "ウェンディ"
# 「人間界は残ってしまいました……中途半端に」
line = "「人間界は残ってしまいました……中途半端に」"

[[dialogue]]
speaker = "ウェンディ"
# （乗り越えたはずのリクリエの影は未だ消えていません。各地でモンスターの出現は収まらず、それどころか新種まで現れ始めたとか）
line = "（乗り越えたはずのリクリエの影は未だ消えていません。各地でモンスターの出現は収まらず、それどころか新種まで現れ始めたとか）"

[[dialogue]]
speaker = "ウェンディ"
# 「厳しい延長戦だよぉ……嘆いてばかりもいられないですけど……」
line = "「厳しい延長戦だよぉ……嘆いてばかりもいられないですけど……」"

[[dialogue]]
speaker = "ウェンディ"
# 「ネビュラの人間界進出のときやったみたいに、人間界に新しい財政基盤を築いていく？」
line = "「ネビュラの人間界進出のときやったみたいに、人間界に新しい財政基盤を築いていく？」"

[[dialogue]]
speaker = "ウェンディ"
# 「でも、それだって一朝一夕にはいきません。その前に資本が尽きてしまいます……」
line = "「でも、それだって一朝一夕にはいきません。その前に資本が尽きてしまいます……」"

[[dialogue]]
speaker = "ウェンディ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ウェンディ"
# 「あ～～～っ、もうっ！　ダメです、いい方法なーんにも思い浮かびませんっ！！」
line = "「あ～～～っ、もうっ！　ダメです、いい方法なーんにも思い浮かびませんっ！！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「なーに一人で悶えちゃってんのよん」
line = "「なーに一人で悶えちゃってんのよん」"

[[dialogue]]
speaker = "ウェンディ"
# 「っ！？　ツェツィーリエ！？」
line = "「っ！？　ツェツィーリエ！？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ハロー、ウェンディ♪」
line = "「ハロー、ウェンディ♪」"

[[dialogue]]
speaker = "ウェンディ"
# 「万年、研究室に引きこもっているあなたが指令室に顔を出すなんて、どういう風の吹き回しです？」
line = "「万年、研究室に引きこもっているあなたが指令室に顔を出すなんて、どういう風の吹き回しです？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「やだな～、そいつは偏見ってもんよ？」
line = "「やだな～、そいつは偏見ってもんよ？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「むしろこうやってお散歩することが、斬新なアイデアを生み出す秘訣ってわけ♪」
line = "「むしろこうやってお散歩することが、斬新なアイデアを生み出す秘訣ってわけ♪」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ウェンディもさ、机にかじりついてばっかだから煮詰まるんよ。どう、一緒にイッとく？」
line = "「ウェンディもさ、机にかじりついてばっかだから煮詰まるんよ。どう、一緒にイッとく？」"

[[dialogue]]
speaker = "ウェンディ"
# 「お断りです！　行くとしても誰があなたと一緒になんか……」
line = "「お断りです！　行くとしても誰があなたと一緒になんか……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「あ～、冷たいの。アタシたち同期みたいなモンなんだから仲良くしようよ～♪」
line = "「あ～、冷たいの。アタシたち同期みたいなモンなんだから仲良くしようよ～♪」"

[[dialogue]]
speaker = "ウェンディ"
# 「確かに同期ではありますよ。ですが仲良くはしません。敵です。不倶戴天の宿敵です」
line = "「確かに同期ではありますよ。ですが仲良くはしません。敵です。不倶戴天の宿敵です」"

[[dialogue]]
speaker = "ウェンディ"
# 「あ～もう、くっつかないで離れてください！　そのグイグイ来るの、苦手なんですから」
line = "「あ～もう、くっつかないで離れてください！　そのグイグイ来るの、苦手なんですから」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「お近づきのシルシにアメちゃんをどーぞ♪」
line = "「お近づきのシルシにアメちゃんをどーぞ♪」"

[[dialogue]]
speaker = "ウェンディ"
# 「グイグイ来ないでって言ってるじゃないですか！　勝手におかしをポケットに突っ込まないでください！」
line = "「グイグイ来ないでって言ってるじゃないですか！　勝手におかしをポケットに突っ込まないでください！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ウェンディ、イライラするのはよくないよ～」
line = "「ウェンディ、イライラするのはよくないよ～」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「そんな時は甘いものを食べるのが一番♪　糖分が頭に回ってアイデアもポンポンポーンってなカンジよ～」
line = "「そんな時は甘いものを食べるのが一番♪　糖分が頭に回ってアイデアもポンポンポーンってなカンジよ～」"

[[dialogue]]
speaker = "ウェンディ"
# 「む、う……まあ、一理ありますね。身体が甘いものを欲してる感はあります」
line = "「む、う……まあ、一理ありますね。身体が甘いものを欲してる感はあります」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「だよね、だよねぇ～」
line = "「だよね、だよねぇ～」"

[[dialogue]]
speaker = "ウェンディ"
# 「っ……！　でも、ダメっ！　そうやって油断しておやつを食べ過ぎたせいで、体重がヤバいことになったことあるでしょう！」
line = "「っ……！　でも、ダメっ！　そうやって油断しておやつを食べ過ぎたせいで、体重がヤバいことになったことあるでしょう！」"

[[dialogue]]
speaker = "ウェンディ"
# 「ここでグッと我慢できるかどうかが運命の分かれ道なんです」
line = "「ここでグッと我慢できるかどうかが運命の分かれ道なんです」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「あ、そうだウェンディ。予算ちょーだい」
line = "「あ、そうだウェンディ。予算ちょーだい」"

[[dialogue]]
speaker = "ウェンディ"
# 「おちょくってるんですか、あなたは！」
line = "「おちょくってるんですか、あなたは！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「アタシはいつだって真面目だよ？　ちょー大真面目」
line = "「アタシはいつだって真面目だよ？　ちょー大真面目」"

[[dialogue]]
speaker = "ウェンディ"
# 「だとしても突然『予算ちょーだい』で通るわけないでしょう！　舐めてるんですか？」
line = "「だとしても突然『予算ちょーだい』で通るわけないでしょう！　舐めてるんですか？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「いーじゃない。今度のはホントーにすごい発明なんだよね～」
line = "「いーじゃない。今度のはホントーにすごい発明なんだよね～」"

[[dialogue]]
speaker = "ウェンディ"
# 「あなた毎回それ！」
line = "「あなた毎回それ！」"

[[dialogue]]
speaker = "ウェンディ"
# 「いつもそんな調子で、蓋を開けてみたら使い道のないガラクタばっかりじゃないですか……」
line = "「いつもそんな調子で、蓋を開けてみたら使い道のないガラクタばっかりじゃないですか……」"

[[dialogue]]
speaker = "ウェンディ"
# 「そのおかげで、貴重なネビュラの資金がどれだけ失われてしまったことか！」
line = "「そのおかげで、貴重なネビュラの資金がどれだけ失われてしまったことか！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ウェンディのケチ、ドケチ、ドドドケチ～！　脳みそがお金で出来てるウェンディにはアタシの発明の偉大さが分からないんだよ！」
line = "「ウェンディのケチ、ドケチ、ドドドケチ～！　脳みそがお金で出来てるウェンディにはアタシの発明の偉大さが分からないんだよ！」"

[[dialogue]]
speaker = "ウェンディ"
# 「悔しかったら私を唸らせるような発明品のひとつでも作ってきてください」
line = "「悔しかったら私を唸らせるような発明品のひとつでも作ってきてください」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ほほう……言ったねぇ。待っていたよ、その言葉を！」
line = "「ほほう……言ったねぇ。待っていたよ、その言葉を！」"

[[dialogue]]
speaker = "ウェンディ"
# 「はぁ？」
line = "「はぁ？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「今回の発明はホントーにすごいんだから」
line = "「今回の発明はホントーにすごいんだから」"

[[dialogue]]
speaker = "ウェンディ"
# 「それはさっき聞きました。で、どんな発明なんですか？」
line = "「それはさっき聞きました。で、どんな発明なんですか？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ひょっとしたらこの発明のおかげで、ネビュラの金欠問題も解決しちゃうかも」
line = "「ひょっとしたらこの発明のおかげで、ネビュラの金欠問題も解決しちゃうかも」"

[[dialogue]]
speaker = "ウェンディ"
# 「はいはい、さようですか。期待していないんで、さっさと発表してください」
line = "「はいはい、さようですか。期待していないんで、さっさと発表してください」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「おーけーおーけー、オーディエンスの盛り上がりも最高潮ってところだね」
line = "「おーけーおーけー、オーディエンスの盛り上がりも最高潮ってところだね」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「では発表しよう。今回アタシが発明したのは～……じゃーん、バトルスーツ強化装置～♪」
line = "「では発表しよう。今回アタシが発明したのは～……じゃーん、バトルスーツ強化装置～♪」"

[[dialogue]]
speaker = "ウェンディ"
# 「強化ぁー？　一体何を強化するって言うんです？」
line = "「強化ぁー？　一体何を強化するって言うんです？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「全部だよ全部。耐久力、反応力、魔力出力、あらゆる性能がなんと２００パーセント以上アップ！」
line = "「全部だよ全部。耐久力、反応力、魔力出力、あらゆる性能がなんと２００パーセント以上アップ！」"

[[dialogue]]
speaker = "ウェンディ"
# 「本当ですか？　本当だったらすごいんですが……」
line = "「本当ですか？　本当だったらすごいんですが……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「まだまだ基礎研究レベルだよ。ゆくゆくは星騎士たちやクラウディア様のように、ネビュラの構成員も複数の戦闘服が持てるんじゃないかと思ってね」
line = "「まだまだ基礎研究レベルだよ。ゆくゆくは星騎士たちやクラウディア様のように、ネビュラの構成員も複数の戦闘服が持てるんじゃないかと思ってね」"

[[dialogue]]
speaker = "ウェンディ"
# 「えっ、そんなことが可能なんですか……？」
line = "「えっ、そんなことが可能なんですか……？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「まあ星騎士の技術は見様見真似だし、光の魔法はクラウディア様にしか使えないから、改善点は多いがね」
line = "「まあ星騎士の技術は見様見真似だし、光の魔法はクラウディア様にしか使えないから、改善点は多いがね」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「それでも既存の戦闘服の強化なら実現できたんだ～。疑うなら試してみる？」
line = "「それでも既存の戦闘服の強化なら実現できたんだ～。疑うなら試してみる？」"

[[dialogue]]
speaker = "ウェンディ"
# 「私が？　え、ええ……まあ、いいですけど……」
line = "「私が？　え、ええ……まあ、いいですけど……」"
