[[dialogue]]
speaker = "unk"
# 第６話,スター・リユニオン,B
line = "第６話,スター・リユニオン,B"

[[dialogue]]
speaker = "unk"
# 『<ruby=スター・リユニオン>星の再会</ruby>』──これが俺の最後の計画だ。
line = "『<ruby>星の再会<rt>スター・リユニオン</rt></ruby>』──これが俺の最後の計画だ。"

[[dialogue]]
speaker = "unk"
# 天界襲撃時にグレイスから確保した転送装置を、アニマ先輩とトレジアンナさんに解析してもらい……
line = "天界襲撃時にグレイスから確保した転送装置を、アニマ先輩とトレジアンナさんに解析してもらい……"

[[dialogue]]
speaker = "unk"
# 先刻、ホロウ複製体との戦闘で手に入れた２台目を用いることで、出力の問題もクリアされた。
line = "先刻、ホロウ複製体との戦闘で手に入れた２台目を用いることで、出力の問題もクリアされた。"

[[dialogue]]
speaker = "unk"
# だからこそ実現できる──超大型ゲートを、デネブ各地に複数かつ同時展開することが！
line = "だからこそ実現できる──超大型ゲートを、デネブ各地に複数かつ同時展開することが！"

[[dialogue]]
speaker = "煌嶺"
# 「妾は言ったな？　『戦争』ではなく『蹂躙』をしてみせろと」
line = "「妾は言ったな？　『戦争』ではなく『蹂躙』をしてみせろと」"

[[dialogue]]
speaker = "煌嶺"
# 「クク……魔王、合格点をやろう──見事だ！！」
line = "「クク……魔王、合格点をやろう──見事だ！！」"

[[dialogue]]
speaker = "unk"
# デネブで散っていった、かつての星騎士たちは、今ここに再会を果たす──
line = "デネブで散っていった、かつての星騎士たちは、今ここに再会を果たす──"

[[dialogue]]
speaker = "煌嶺"
# 「数え切れぬほどの世界の門が生まれ、開く──絢爛たる景色ではないか！！！」
line = "「数え切れぬほどの世界の門が生まれ、開く──絢爛たる景色ではないか！！！」"

[[dialogue]]
speaker = "unk"
# 大型ゲートをくぐり、教皇庁前にまず現れたのは、天使の大軍勢──！
line = "大型ゲートをくぐり、教皇庁前にまず現れたのは、天使の大軍勢──！"

[[dialogue]]
speaker = "メルエル"
# 「会長くん！　お待たせ！！」
line = "「会長くん！　お待たせ！！」"

[[dialogue]]
speaker = "ナターシャ"
# 「すっごい状況になってるねー。へぇ、あれが創造神……『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』か」
line = "「すっごい状況になってるねー。へぇ、あれが創造神……『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』か」"

[[dialogue]]
speaker = "unk"
# メルエルたちの背後には、俺も名を知らない膨大な数の天使たちの姿──それだけじゃない！
line = "メルエルたちの背後には、俺も名を知らない膨大な数の天使たちの姿──それだけじゃない！"

[[dialogue]]
speaker = "unk"
# その中には見知った顔──
line = "その中には見知った顔──"

[[dialogue]]
speaker = "unk"
# 学園生の神族の星騎士──
line = "学園生の神族の星騎士──"

[[dialogue]]
speaker = "unk"
# 教皇庁所属の者たちまで──！
line = "教皇庁所属の者たちまで──！"

[[dialogue]]
speaker = "ナターシャ"
# 「事前にこっちのコハルコさん？　に確認を取って、被りのない星騎士にできる限り声をかけてきたよ。これで満足？」
line = "「事前にこっちのコハルコさん？　に確認を取って、被りのない星騎士にできる限り声をかけてきたよ。これで満足？」"

[[dialogue]]
speaker = "クロト"
# 「──ありがとう。想像以上だ！　２人とも、よくやってくれた……！」
line = "「──ありがとう。想像以上だ！　２人とも、よくやってくれた……！」"

[[dialogue]]
speaker = "メルエル"
# 「えへへ！　会長くんの頼みだもん、張り切っちゃった！」
line = "「えへへ！　会長くんの頼みだもん、張り切っちゃった！」"

[[dialogue]]
speaker = "ナターシャ"
# 「あーあ、可哀想。ホロウだっけ……あいつら、ケイティ姉さんに『制圧』されちゃうんでしょ？　敵ながら同情しちゃうね」
line = "「あーあ、可哀想。ホロウだっけ……あいつら、ケイティ姉さんに『制圧』されちゃうんでしょ？　敵ながら同情しちゃうね」"

[[dialogue]]
speaker = "マグダレナ"
# 「もちろん天使の皆様だけではありません。アルタイルの守護天使たちもここに！」
line = "「もちろん天使の皆様だけではありません。アルタイルの守護天使たちもここに！」"

[[dialogue]]
speaker = "アルモタヘル"
# 「血沸き肉躍るとはこのことだな、人の子よ！」
line = "「血沸き肉躍るとはこのことだな、人の子よ！」"

[[dialogue]]
speaker = "unk"
# マグダレナとアルモタヘルだけではない。他の守護天使たちの姿も見える！
line = "マグダレナとアルモタヘルだけではない。他の守護天使たちの姿も見える！"

[[dialogue]]
speaker = "unk"
# そして、守護天使を祀る一族の者たちも傍に控えて──
line = "そして、守護天使を祀る一族の者たちも傍に控えて──"

[[dialogue]]
speaker = "ラクシャ"
# 「ちゃーんとアルタイルのボクだけは留守番してるね。これなら問題なし！」
line = "「ちゃーんとアルタイルのボクだけは留守番してるね。これなら問題なし！」"

[[dialogue]]
speaker = "マグダレナ"
# 「デネブのラクシャですね。ふふ、永き時を生きていますが、このような形での共闘があるとは」
line = "「デネブのラクシャですね。ふふ、永き時を生きていますが、このような形での共闘があるとは」"

[[dialogue]]
speaker = "アルモタヘル"
# 「世界を超えた大戦だ。久方ぶりにお前の戦を見せてもらうぞ、ラクシャよ！」
line = "「世界を超えた大戦だ。久方ぶりにお前の戦を見せてもらうぞ、ラクシャよ！」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「はろはろ～♪　立朽ネーゼマイン、魔界より帰還しました～♪」
line = "「はろはろ～♪　立朽ネーゼマイン、魔界より帰還しました～♪」"

[[dialogue]]
speaker = "クロト"
# 「マイン……！　魔界での交渉は──」
line = "「マイン……！　魔界での交渉は──」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「もちろんバッチリ。煌嶺さんが提示した、魔界のならず者たちは残らずあちらに♪」
line = "「もちろんバッチリ。煌嶺さんが提示した、魔界のならず者たちは残らずあちらに♪」"

[[dialogue]]
speaker = "魔族の星術使い"
# 「ヒャッハァ──『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』ってのはアイツかァ！？」
line = "「ヒャッハァ──『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』ってのはアイツかァ！？」"

[[dialogue]]
speaker = "魔族の星術使い"
# 「ゲヘヘヘヘ！　ついでに煌嶺の首も狙ってやらぁ！！　そうすりゃキュリオスは俺たちのモンだぁ！！」
line = "「ゲヘヘヘヘ！　ついでに煌嶺の首も狙ってやらぁ！！　そうすりゃキュリオスは俺たちのモンだぁ！！」"

[[dialogue]]
speaker = "unk"
# ……うわぁ。
line = "……うわぁ。"

[[dialogue]]
speaker = "クロト"
# 「なんか世紀末みたいな奴らばっかりなんだけど……」
line = "「なんか世紀末みたいな奴らばっかりなんだけど……」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「ほんっとひどいよね～。あいつら相手の交渉、めちゃくちゃ大変だったんだよ？　いっぱい感謝してよね！」
line = "「ほんっとひどいよね～。あいつら相手の交渉、めちゃくちゃ大変だったんだよ？　いっぱい感謝してよね！」"

[[dialogue]]
speaker = "クロト"
# 「本当にありがとう、マイン……」
line = "「本当にありがとう、マイン……」"

[[dialogue]]
speaker = "セナリィ"
# 「会長様？　なんでも報酬を弾んでいただけると聞きまして──ゴールデングースも一枚噛ませていただきますわ！」
line = "「会長様？　なんでも報酬を弾んでいただけると聞きまして──ゴールデングースも一枚噛ませていただきますわ！」"

[[dialogue]]
speaker = "unk"
# セナリィの後ろには、ゴールデングースの新入社員たちの姿──それだけじゃない。
line = "セナリィの後ろには、ゴールデングースの新入社員たちの姿──それだけじゃない。"

[[dialogue]]
speaker = "unk"
# 九浄家メイド隊のみんなも、この魔族部隊に組み込まれていたのか！
line = "九浄家メイド隊のみんなも、この魔族部隊に組み込まれていたのか！"

[[dialogue]]
speaker = "クロト"
# 「──先生たちまで！？」
line = "「──先生たちまで！？」"

[[dialogue]]
speaker = "セナリィ"
# 「教え子が死地に向かうのを、指を咥えて待つことはできないと……報酬もないのに律儀な人達ですこと」
line = "「教え子が死地に向かうのを、指を咥えて待つことはできないと……報酬もないのに律儀な人達ですこと」"

[[dialogue]]
speaker = "unk"
# ウィステリアさんの姿もある──リィベルにモネも！
line = "ウィステリアさんの姿もある──リィベルにモネも！"

[[dialogue]]
speaker = "ルヴィネ"
# 「アルタイルの星騎士をデネブに集める……『<ruby=スター・リユニオン>星の再会</ruby>』とは、よく言ったものね」
line = "「アルタイルの星騎士をデネブに集める……『<ruby>星の再会<rt>スター・リユニオン</rt></ruby>』とは、よく言ったものね」"

[[dialogue]]
speaker = "チナ"
# 「でも教皇庁前だけじゃ……複製体はデネブの流星市国全域に……！」
line = "「でも教皇庁前だけじゃ……複製体はデネブの流星市国全域に……！」"

[[dialogue]]
speaker = "メルエル"
# 「安心して！　こっちに乗り込む前にちゃんと打ち合わせしてきてるから！」
line = "「安心して！　こっちに乗り込む前にちゃんと打ち合わせしてきてるから！」"

[[dialogue]]
speaker = "極星学園の星騎士"
# 「あ、あなた達は……！？」
line = "「あ、あなた達は……！？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「こんにちは～☆　魔法少女、トレジャーアンナです☆」
line = "「こんにちは～☆　魔法少女、トレジャーアンナです☆」"

[[dialogue]]
speaker = "シズハ"
# 「私は魔法少女、グレイル・シズハ！」
line = "「私は魔法少女、グレイル・シズハ！」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「フハハハ！！　我は悪の終末兵器、プリムラ†ノワール！」
line = "「フハハハ！！　我は悪の終末兵器、プリムラ†ノワール！」"

[[dialogue]]
speaker = "極星学園の星騎士"
# 「魔法少女に……終末兵器！？　──どういうことです！？」
line = "「魔法少女に……終末兵器！？　──どういうことです！？」"

[[dialogue]]
speaker = "サチ（覚醒）"
# 「アルタイルの星騎士だって名乗って欲しい……あ、あの。救援に来ました！」
line = "「アルタイルの星騎士だって名乗って欲しい……あ、あの。救援に来ました！」"

[[dialogue]]
speaker = "unk"
# もちろん魔法少女だけではなく、附属校生徒会長・サチに従う星騎士も結集している。
line = "もちろん魔法少女だけではなく、附属校生徒会長・サチに従う星騎士も結集している。"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「随分と賑やかだ。まるで同窓会だね」
line = "「随分と賑やかだ。まるで同窓会だね」"

[[dialogue]]
speaker = "ミネコ"
# 「世界の危機に『<ruby=ロールスター>選星者</ruby>』が駆けつけないのもおかしな話だからね。ついでに平行世界のお宝も探しちゃおっかな～♪」
line = "「世界の危機に『<ruby>選星者<rt>ロールスター</rt></ruby>』が駆けつけないのもおかしな話だからね。ついでに平行世界のお宝も探しちゃおっかな～♪」"

[[dialogue]]
speaker = "unk"
# 呼べるだけの<ruby=ロールスター>選星者</ruby>も集い──その知己である吸血鬼の姿も。
line = "呼べるだけの<ruby>選星者<rt>ロールスター</rt></ruby>も集い──その知己である吸血鬼の姿も。"

[[dialogue]]
speaker = "unk"
# さらにネーゼマインが所属する公安委員会も、九浄家の命令により駆けつけていた──
line = "さらにネーゼマインが所属する公安委員会も、九浄家の命令により駆けつけていた──"

[[dialogue]]
speaker = "クラウディア"
# 「おお、ここが平行世界──デネブか！　未来の流星市国を拝めるとは、なんと愉快なことか！」
line = "「おお、ここが平行世界──デネブか！　未来の流星市国を拝めるとは、なんと愉快なことか！」"

[[dialogue]]
speaker = "セドナ"
# 「姫様……はしゃぐのは結構ですが、我々の目的は救援です」
line = "「姫様……はしゃぐのは結構ですが、我々の目的は救援です」"

[[dialogue]]
speaker = "クラウディア"
# 「わかっておる。さぁネビュラの魔女よ、余に続け！」
line = "「わかっておる。さぁネビュラの魔女よ、余に続け！」"

[[dialogue]]
speaker = "リーリア（覚醒）"
# 「センパイは教皇庁前かぁ。あっちに行きたかったな～」
line = "「センパイは教皇庁前かぁ。あっちに行きたかったな～」"

[[dialogue]]
speaker = "セドナ"
# 「ここを蹴散らせばすぐに合流できる。励め、リーリア」
line = "「ここを蹴散らせばすぐに合流できる。励め、リーリア」"

[[dialogue]]
speaker = "リーリア（覚醒）"
# 「は～い──って、あれれ？」
line = "「は～い──って、あれれ？」"

[[dialogue]]
speaker = "リノ"
# 「セドナ。来てくれたのね」
line = "「セドナ。来てくれたのね」"

[[dialogue]]
speaker = "セドナ"
# 「……リノか。１０年も未来だと聞いていたが──変わらんな、お前は」
line = "「……リノか。１０年も未来だと聞いていたが──変わらんな、お前は」"

[[dialogue]]
speaker = "リノ"
# 「会って第一声がそれ？　あなたも相変わらずね」
line = "「会って第一声がそれ？　あなたも相変わらずね」"

[[dialogue]]
speaker = "リノ"
# 「……懐かしい顔ばかりだわ」
line = "「……懐かしい顔ばかりだわ」"

[[dialogue]]
speaker = "セドナ"
# 「デネブでは前線にいた魔女はお前以外、殆どが戦死したと聞いている──雪辱を果たそう」
line = "「デネブでは前線にいた魔女はお前以外、殆どが戦死したと聞いている──雪辱を果たそう」"

[[dialogue]]
speaker = "リノ"
# 「ええ……今度こそ、みんなで勝利を掴みましょう！」
line = "「ええ……今度こそ、みんなで勝利を掴みましょう！」"

[[dialogue]]
speaker = "レイラ"
# 「あ、あれ？　イングリットは！？　メテオラは！？　一体どこに……！？」
line = "「あ、あれ？　イングリットは！？　メテオラは！？　一体どこに……！？」"

[[dialogue]]
speaker = "キサナ"
# 「さっき飛び出してっただろ。見てねぇのか？」
line = "「さっき飛び出してっただろ。見てねぇのか？」"

[[dialogue]]
speaker = "レイラ"
# 「そんな！？　ちゃんと私の言うこと聞いてって言ったのに……！」
line = "「そんな！？　ちゃんと私の言うこと聞いてって言ったのに……！」"

[[dialogue]]
speaker = "キサナ"
# 「ンなもん、あいつらが聞くわけねえだろが」
line = "「ンなもん、あいつらが聞くわけねえだろが」"

[[dialogue]]
speaker = "リーナ"
# 「ふーん。あの同じ顔した……ルヴィネっていうのが、お兄ちゃんを困らせてるんだ？　リーナからお兄ちゃんを取ろうとしてるんだ……？」
line = "「ふーん。あの同じ顔した……ルヴィネっていうのが、お兄ちゃんを困らせてるんだ？　リーナからお兄ちゃんを取ろうとしてるんだ……？」"

[[dialogue]]
speaker = "リーナ"
# 「許さない許さない許さない許さないゼッタイ許さない……」
line = "「許さない許さない許さない許さないゼッタイ許さない……」"

[[dialogue]]
speaker = "キサナ"
# 「リーナの子守はしといてやるからよ。オマエはあいつらを探しに行けよ」
line = "「リーナの子守はしといてやるからよ。オマエはあいつらを探しに行けよ」"

[[dialogue]]
speaker = "レイラ"
# 「うぅぅう！　平行世界に来てもこんな役回りばっかり──！」
line = "「うぅぅう！　平行世界に来てもこんな役回りばっかり──！」"

[[dialogue]]
speaker = "unk"
# ホロウ・ルヴィネへ対応するために、今も続々とアルタイルからの増援は送りこまれ続けている──
line = "ホロウ・ルヴィネへ対応するために、今も続々とアルタイルからの増援は送りこまれ続けている──"

[[dialogue]]
speaker = "ルリエル"
# 「アルタイルからの応援がどんどん到着しているのです……！」
line = "「アルタイルからの応援がどんどん到着しているのです……！」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「これが魔王の計画した最終作戦か！　全員集合イベントってやつだな、熱いじゃないか！！」
line = "「これが魔王の計画した最終作戦か！　全員集合イベントってやつだな、熱いじゃないか！！」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「創造神と女神の力を舐めすぎよ。世界を超えてきた者の魂を、端から全て回収してあげるわ……！」
line = "「創造神と女神の力を舐めすぎよ。世界を超えてきた者の魂を、端から全て回収してあげるわ……！」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「にひぃ♪　それはどうかなー？」
line = "「にひぃ♪　それはどうかなー？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「会長、間に合ったよ。人工ノヴァフォーム──その到達点の実戦配備♪」
line = "「会長、間に合ったよ。人工ノヴァフォーム──その到達点の実戦配備♪」"

[[dialogue]]
speaker = "クロト"
# 「……！　まさか、マインが？」
line = "「……！　まさか、マインが？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「そ♪　ノヴァフォーム覚醒に必要な要素は全部で３つ。本人の類まれな才能、心理的ブレイクスルー、そして魔王との絆──」
line = "「そ♪　ノヴァフォーム覚醒に必要な要素は全部で３つ。本人の類まれな才能、心理的ブレイクスルー、そして魔王との絆──」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「最新式の人工ノヴァフォームは、その『本人の才能』が足りない場合でも、アルケインコードを受け取れるような機構を搭載してるんだ♪」
line = "「最新式の人工ノヴァフォームは、その『本人の才能』が足りない場合でも、アルケインコードを受け取れるような機構を搭載してるんだ♪」"

[[dialogue]]
speaker = "クロト"
# 「……量産は大変そうだな」
line = "「……量産は大変そうだな」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「うん、今のとこ１着だけ。だからお願い、会長。最後のプッシュ、お願いしまーす♪」
line = "「うん、今のとこ１着だけ。だからお願い、会長。最後のプッシュ、お願いしまーす♪」"

[[dialogue]]
speaker = "unk"
# 俺はマインに向かって掌を掲げる──なるほど、確かにアルケインコードが使用可能な、魂の輝きが見える！
line = "俺はマインに向かって掌を掲げる──なるほど、確かにアルケインコードが使用可能な、魂の輝きが見える！"

[[dialogue]]
speaker = "クロト"
# 「行くぞ──アルケインノヴァエクストリーム！！」
line = "「行くぞ──アルケインノヴァエクストリーム！！」"

[[dialogue]]
speaker = "unk"
# マインの心臓の奥に見えた魂の輝きを、俺は強く、強く押す──！
line = "マインの心臓の奥に見えた魂の輝きを、俺は強く、強く押す──！"

[[dialogue]]
speaker = "ネーゼマイン"
# 「チェンジ――ノヴァフォーム♪」
line = "「チェンジ――ノヴァフォーム♪」"

[[dialogue]]
speaker = "ネーゼマイン（覚醒）"
# 「じゃ～～ん♪　というわけでこれが、立朽ネーゼマイン、完成形人工ノヴァフォームだよ♪」
line = "「じゃ～～ん♪　というわけでこれが、立朽ネーゼマイン、完成形人工ノヴァフォームだよ♪」"

[[dialogue]]
speaker = "ネーゼマイン（覚醒）"
# 「私の才能じゃ、アルケインコードを受け取り切れない──そんな風に思ったこともあったけど、足りない分は外から補えばいいんだよね♪」
line = "「私の才能じゃ、アルケインコードを受け取り切れない──そんな風に思ったこともあったけど、足りない分は外から補えばいいんだよね♪」"

[[dialogue]]
speaker = "ネーゼマイン（覚醒）"
# 「──うん、うん。イイ感じだね～、これがノヴァフォームかぁ。早速、試射しちゃお～っと♪」
line = "「──うん、うん。イイ感じだね～、これがノヴァフォームかぁ。早速、試射しちゃお～っと♪」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「ぐう、ぁ──！？」
line = "「ぐう、ぁ──！？」"

[[dialogue]]
speaker = "ネーゼマイン（覚醒）"
# 「おー、火力はバッチリ。今までは小細工ばっかりで、前線に立ててなかったけど……これならガンガンやれちゃいそうだね♪」
line = "「おー、火力はバッチリ。今までは小細工ばっかりで、前線に立ててなかったけど……これならガンガンやれちゃいそうだね♪」"

[[dialogue]]
speaker = "メルエル"
# 「会長くん……乱戦になる前に、私にもお願い！！」
line = "「会長くん……乱戦になる前に、私にもお願い！！」"

[[dialogue]]
speaker = "クロト"
# 「メルエル──君も天界で、何か新しいアルケインコードを？」
line = "「メルエル──君も天界で、何か新しいアルケインコードを？」"

[[dialogue]]
speaker = "unk"
# 今まで、メルエルにもアルケインノヴァエクストリームを試したことはあった。
line = "今まで、メルエルにもアルケインノヴァエクストリームを試したことはあった。"

[[dialogue]]
speaker = "unk"
# しかし、『<ruby=アルケインノヴァエクストリーム>魔王の力を貸し与える技</ruby>』と『メルエルの血に流れる魔王因子』が反発するせいなのか、技が成功することはなかった。
line = "しかし、『<ruby>魔王の力を貸し与える技<rt>アルケインノヴァエクストリーム</rt></ruby>』と『メルエルの血に流れる魔王因子』が反発するせいなのか、技が成功することはなかった。"

[[dialogue]]
speaker = "メルエル"
# 「ううん。新しい技を習得したとか、魔王として何か進化したとか、そういうんじゃないの」
line = "「ううん。新しい技を習得したとか、魔王として何か進化したとか、そういうんじゃないの」"

[[dialogue]]
speaker = "メルエル"
# 「むしろ逆……かな？」
line = "「むしろ逆……かな？」"

[[dialogue]]
speaker = "クロト"
# 「逆……？」
line = "「逆……？」"

[[dialogue]]
speaker = "メルエル"
# 「私ね、自分の出自のこととか、ナターシャちゃんが小さい頃から抱いていた気持ちのこととか……」
line = "「私ね、自分の出自のこととか、ナターシャちゃんが小さい頃から抱いていた気持ちのこととか……」"

[[dialogue]]
speaker = "メルエル"
# 「そういうこと、全部受け止めたつもりだった。でも『つもり』なだけだったんだ」
line = "「そういうこと、全部受け止めたつもりだった。でも『つもり』なだけだったんだ」"

[[dialogue]]
speaker = "メルエル"
# 「天界へ行って……ナターシャちゃんといっぱい言葉を交わして……知らなかったことと、改めて向き合ってきたよ」
line = "「天界へ行って……ナターシャちゃんといっぱい言葉を交わして……知らなかったことと、改めて向き合ってきたよ」"

[[dialogue]]
speaker = "メルエル"
# 「そのうえでひとつ、決めたことがあるの！」
line = "「そのうえでひとつ、決めたことがあるの！」"

[[dialogue]]
speaker = "メルエル"
# 「私は──姫にも王にもならない！　天界の魔王は、リガルタ様で終わり！」
line = "「私は──姫にも王にもならない！　天界の魔王は、リガルタ様で終わり！」"

[[dialogue]]
speaker = "メルエル"
# 「私は<b>天界の魔王にはならない</b>って、そう決めたの！」
line = "「私は<b>天界の魔王にはならない</b>って、そう決めたの！」"

[[dialogue]]
speaker = "unk"
# メルエルのその宣言を聞いた瞬間──彼女の胸を中心に、清廉に輝く魂のきらめきが、爆発的な広がりを見せた。
line = "メルエルのその宣言を聞いた瞬間──彼女の胸を中心に、清廉に輝く魂のきらめきが、爆発的な広がりを見せた。"

[[dialogue]]
speaker = "メルエル"
# 「これが、私がナターシャちゃんに示せる覚悟だよ！！　そうやってお腹を割って話をして、仲直りしてきたの！　ねっ？」
line = "「これが、私がナターシャちゃんに示せる覚悟だよ！！　そうやってお腹を割って話をして、仲直りしてきたの！　ねっ？」"

[[dialogue]]
speaker = "ナターシャ"
# 「……ねちねち嫌味をいっぱい言ったんだけど、全然効果がないんだもん。我ながら無意味な抵抗だったよね」
line = "「……ねちねち嫌味をいっぱい言ったんだけど、全然効果がないんだもん。我ながら無意味な抵抗だったよね」"

[[dialogue]]
speaker = "メルエル"
# 「魔王因子って、すっごく心の力の影響を受けるでしょ？　だから『魔王じゃなくなった私』に、もう一度試してほしいの」
line = "「魔王因子って、すっごく心の力の影響を受けるでしょ？　だから『魔王じゃなくなった私』に、もう一度試してほしいの」"

[[dialogue]]
speaker = "メルエル"
# 「だって私は、魔王メルエルなんかじゃなくって……」
line = "「だって私は、魔王メルエルなんかじゃなくって……」"

[[dialogue]]
speaker = "メルエル"
# 「魔王クロトの眷属として、キミの力で戦いたいから！！」
line = "「魔王クロトの眷属として、キミの力で戦いたいから！！」"

[[dialogue]]
speaker = "クロト"
# 「……わかった。メルエル。俺の剣として、世界を救う手助けをしてほしい」
line = "「……わかった。メルエル。俺の剣として、世界を救う手助けをしてほしい」"

[[dialogue]]
speaker = "メルエル"
# 「──うん！！」
line = "「──うん！！」"

[[dialogue]]
speaker = "クロト"
# 「受け取れ！　────アルケインノヴァエクストリーム！！」
line = "「受け取れ！　────アルケインノヴァエクストリーム！！」"

[[dialogue]]
speaker = "メルエル"
# 「……！　これが、会長くんのアルケインコードの力……！」
line = "「……！　これが、会長くんのアルケインコードの力……！」"

[[dialogue]]
speaker = "メルエル"
# 「チェンジ――ノヴァフォーム！！」
line = "「チェンジ――ノヴァフォーム！！」"

[[dialogue]]
speaker = "メルエル（覚醒）"
# 「これが会長くんと私の絆の力──ノヴァフォームだよ！」
line = "「これが会長くんと私の絆の力──ノヴァフォームだよ！」"

[[dialogue]]
speaker = "クロト"
# 「！！　力同士の結びつきがどうなってるのか、分からないけど……すごいな」
line = "「！！　力同士の結びつきがどうなってるのか、分からないけど……すごいな」"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナスのノヴァフォームや、フィオナの魔王フォームにも引けを取らないくらいの力を感じる！」
line = "「ヴィーナスのノヴァフォームや、フィオナの魔王フォームにも引けを取らないくらいの力を感じる！」"

[[dialogue]]
speaker = "メルエル（覚醒）"
# 「うん！　この姿なら、キミの剣として、世界だって救えちゃうよ！」
line = "「うん！　この姿なら、キミの剣として、世界だって救えちゃうよ！」"

[[dialogue]]
speaker = "クロト"
# 「『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』……これが俺の描いた、最後の絵図だ！」
line = "「『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』……これが俺の描いた、最後の絵図だ！」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 「──────ッ！！」
line = "「──────ッ！！」"

[[dialogue]]
speaker = "クロト"
# 「行くぞ、最終決戦だ！！！」
line = "「行くぞ、最終決戦だ！！！」"
