[[dialogue]]
speaker = "unk"
# 第１４話,ディザスターハンド,B
line = "第１４話,ディザスターハンド,B"

[[dialogue]]
speaker = "クロト"
# 「はぁ、はぁ……みんな、無事か……？」
line = "「はぁ、はぁ……みんな、無事か……？」"

[[dialogue]]
speaker = "マトイ"
# 「うん、生きてる……。死ぬかと思ったけど……」
line = "「うん、生きてる……。死ぬかと思ったけど……」"

[[dialogue]]
speaker = "アナ"
# 「同じく」
line = "「同じく」"

[[dialogue]]
speaker = "サーシャ"
# 「私も無事だわ～」
line = "「私も無事だわ～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「何だったのよ、あれは……」
line = "「何だったのよ、あれは……」"

[[dialogue]]
speaker = "unk"
# 命からがら頂上を脱出した俺たちは、フィーニスの塔を降り、大聖堂まで来ていた。
line = "命からがら頂上を脱出した俺たちは、フィーニスの塔を降り、大聖堂まで来ていた。"

[[dialogue]]
speaker = "unk"
# 全員の健在を確認し、ほっと一息つく。
line = "全員の健在を確認し、ほっと一息つく。"

[[dialogue]]
speaker = "unk"
# 緊張が解けたことで力が抜け、その場から動くことができない。
line = "緊張が解けたことで力が抜け、その場から動くことができない。"

[[dialogue]]
speaker = "クロト"
# 「ありがとう、梨緒のおかげで助かった」
line = "「ありがとう、梨緒のおかげで助かった」"

[[dialogue]]
speaker = "梨緒"
# 「構わない。魔王が敵の手に堕ちることは、避けなければいけないからな」
line = "「構わない。魔王が敵の手に堕ちることは、避けなければいけないからな」"

[[dialogue]]
speaker = "梨緒"
# 「……っ」
line = "「……っ」"

[[dialogue]]
speaker = "クロト"
# 「大丈夫か！？　どこかやられたのか！？」
line = "「大丈夫か！？　どこかやられたのか！？」"

[[dialogue]]
speaker = "梨緒"
# 「いや、これは元々だ。時折頭が痛むだけ……気にしないでくれ」
line = "「いや、これは元々だ。時折頭が痛むだけ……気にしないでくれ」"

[[dialogue]]
speaker = "サーシャ"
# 「本調子じゃないのに助けに来てくれたのね。……ありがとう、本当に」
line = "「本調子じゃないのに助けに来てくれたのね。……ありがとう、本当に」"

[[dialogue]]
speaker = "梨緒"
# 「監視すると言っても、選管は星徒会の敵ではない。協力は惜しまない……」
line = "「監視すると言っても、選管は星徒会の敵ではない。協力は惜しまない……」"

[[dialogue]]
speaker = "アナ"
# 「あの<b>手</b>が追ってくる気配はなさそうですね」
line = "「あの<b>手</b>が追ってくる気配はなさそうですね」"

[[dialogue]]
speaker = "梨緒"
# 「今のところフィーニスの塔から出る気はないらしい。不幸中の幸いだ」
line = "「今のところフィーニスの塔から出る気はないらしい。不幸中の幸いだ」"

[[dialogue]]
speaker = "マトイ"
# 「でもどうして梨緒さんがフィーニスの塔に？」
line = "「でもどうして梨緒さんがフィーニスの塔に？」"

[[dialogue]]
speaker = "梨緒"
# 「私の中で声がしたんだ。……塔の中で何かが起きている、と」
line = "「私の中で声がしたんだ。……塔の中で何かが起きている、と」"

[[dialogue]]
speaker = "クロト"
# 「声……？」
line = "「声……？」"

[[dialogue]]
speaker = "梨緒"
# 「ああ、声だ。私にも、誰のものかはわからなかった……」
line = "「ああ、声だ。私にも、誰のものかはわからなかった……」"

[[dialogue]]
speaker = "unk"
# フィーニスの塔を登っている時、ヴィーナスはしばしば声が聞こえると言っていたが、それと似たようなものだろうか……？
line = "フィーニスの塔を登っている時、ヴィーナスはしばしば声が聞こえると言っていたが、それと似たようなものだろうか……？"

[[dialogue]]
speaker = "ヴィーナス"
# 「よく私たちの後を追ってこれたわね」
line = "「よく私たちの後を追ってこれたわね」"

[[dialogue]]
speaker = "梨緒"
# 「まぁ、天井に大穴が空いていたからな。それを辿っていったんだ」
line = "「まぁ、天井に大穴が空いていたからな。それを辿っていったんだ」"

[[dialogue]]
speaker = "梨緒"
# 「それに塔の中が懐かしい気もして……まるで以前から知っているような……」
line = "「それに塔の中が懐かしい気もして……まるで以前から知っているような……」"

[[dialogue]]
speaker = "クロト"
# 「懐かしい？」
line = "「懐かしい？」"

[[dialogue]]
speaker = "梨緒"
# 「フィーニスの塔に入ったのは、初めてのはずなんだが……」
line = "「フィーニスの塔に入ったのは、初めてのはずなんだが……」"

[[dialogue]]
speaker = "unk"
# 答えながら自分で首を傾げる梨緒。
line = "答えながら自分で首を傾げる梨緒。"

[[dialogue]]
speaker = "unk"
# どうやら彼女自身も釈然としないらしい。
line = "どうやら彼女自身も釈然としないらしい。"

[[dialogue]]
speaker = "サーシャ"
# 「結局、あの<b>手</b>はなんだったのかしら？」
line = "「結局、あの<b>手</b>はなんだったのかしら？」"

[[dialogue]]
speaker = "unk"
# リクリエの使徒であったアポロを守った手。リクリエの側の存在で、敵であることは間違いないようだ。
line = "リクリエの使徒であったアポロを守った手。リクリエの側の存在で、敵であることは間違いないようだ。"

[[dialogue]]
speaker = "unk"
# 間近で相対して感じたのは、圧倒的な力。
line = "間近で相対して感じたのは、圧倒的な力。"

[[dialogue]]
speaker = "unk"
# あれは今まで戦ってきた誰よりも、何よりも、強い。
line = "あれは今まで戦ってきた誰よりも、何よりも、強い。"

[[dialogue]]
speaker = "unk"
# 当然、あのギエルよりも。
line = "当然、あのギエルよりも。"

[[dialogue]]
speaker = "unk"
# そして梨緒は最初からあの<b>手</b>を知っているような口ぶりだった。
line = "そして梨緒は最初からあの<b>手</b>を知っているような口ぶりだった。"

[[dialogue]]
speaker = "unk"
# <b>手</b>がアポロを助けた時、あの場にいなかったにも拘わらず。
line = "<b>手</b>がアポロを助けた時、あの場にいなかったにも拘わらず。"

[[dialogue]]
speaker = "クロト"
# 「梨緒はあの<b>手</b>を知っているのか？」
line = "「梨緒はあの<b>手</b>を知っているのか？」"

[[dialogue]]
speaker = "梨緒"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# 梨緒は目をつむって一瞬逡巡し、小さく頷く。
line = "梨緒は目をつむって一瞬逡巡し、小さく頷く。"

[[dialogue]]
speaker = "unk"
# そして──
line = "そして──"

[[dialogue]]
speaker = "梨緒"
# 「ああ、知っている」
line = "「ああ、知っている」"

[[dialogue]]
speaker = "梨緒"
# 「あれはディザスターハンド。世界を破滅させる厄災の化身だ」
line = "「あれはディザスターハンド。世界を破滅させる厄災の化身だ」"
