[[dialogue]]
speaker = "unk"
# 第１２話,降臨,B
line = "第１２話,降臨,B"

[[dialogue]]
speaker = "unk"
# 極星学園の中庭を奪還し、極星学園のプリマステラたちと合流した。
line = "極星学園の中庭を奪還し、極星学園のプリマステラたちと合流した。"

[[dialogue]]
speaker = "クロト"
# 「──先遣部隊をさらに分割して、各所の対応にあたる」
line = "「──先遣部隊をさらに分割して、各所の対応にあたる」"

[[dialogue]]
speaker = "ルヴィネ"
# 「１つは、教皇庁前の時空の裂け目に対応する攻撃チームね。ホロウの複製体がアルタイルに投入される、その発送元を叩く」
line = "「１つは、教皇庁前の時空の裂け目に対応する攻撃チームね。ホロウの複製体がアルタイルに投入される、その発送元を叩く」"

[[dialogue]]
speaker = "クロト"
# 「ああ。新星学園と極星学園の星徒会。あとは……」
line = "「ああ。新星学園と極星学園の星徒会。あとは……」"

[[dialogue]]
speaker = "フィオナ（魔王）"
# 「私も行きましょう。ホロウとの戦闘に慣れている者が当たった方が効率がいいはずです」
line = "「私も行きましょう。ホロウとの戦闘に慣れている者が当たった方が効率がいいはずです」"

[[dialogue]]
speaker = "煌嶺"
# 「妾たちも参るぞ、リーエン。キュリオスの力をデネブの民に知らしめろ。失態は許さん」
line = "「妾たちも参るぞ、リーエン。キュリオスの力をデネブの民に知らしめろ。失態は許さん」"

[[dialogue]]
speaker = "unk"
# 煌嶺の言葉にリーエンは静かに膝を折り、鋭い眼差しのまま「御意」と短く応じる。
line = "煌嶺の言葉にリーエンは静かに膝を折り、鋭い眼差しのまま「御意」と短く応じる。"

[[dialogue]]
speaker = "梨緒"
# 「そして私たち選管は、フィーニスの塔に向かう。目的は……」
line = "「そして私たち選管は、フィーニスの塔に向かう。目的は……」"

[[dialogue]]
speaker = "ジグ"
# 「第零層に封印されている、デネブの守護天使を解放する部隊というわけだ」
line = "「第零層に封印されている、デネブの守護天使を解放する部隊というわけだ」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「魔王たちを帰還させるために、ラクシャは塔に封印されて動けなくなってる……」
line = "「魔王たちを帰還させるために、ラクシャは塔に封印されて動けなくなってる……」"

[[dialogue]]
speaker = "エステル"
# 「守護天使様の御助力をいただけるのならば、これ以上の支援はありませんね！」
line = "「守護天使様の御助力をいただけるのならば、これ以上の支援はありませんね！」"

[[dialogue]]
speaker = "フィオナ（魔王）"
# 「セーラさん。流星星徒会は解放チームに当たってください！」
line = "「セーラさん。流星星徒会は解放チームに当たってください！」"

[[dialogue]]
speaker = "セーラ"
# 「オッケー、フィオナちゃん。解放次第、教皇庁前に行くから待ってて！」
line = "「オッケー、フィオナちゃん。解放次第、教皇庁前に行くから待ってて！」"

[[dialogue]]
speaker = "梨緒"
# 「ルヴィネ。ラクシャを含め守護天使は皆、君の手で封印されたと聞いているが……今でも働きかけることは可能か？」
line = "「ルヴィネ。ラクシャを含め守護天使は皆、君の手で封印されたと聞いているが……今でも働きかけることは可能か？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……ごめんなさい。すでにホロウへ塔のコントロール権が移っているみたい。霊力を扱えない今の私では……」
line = "「……ごめんなさい。すでにホロウへ塔のコントロール権が移っているみたい。霊力を扱えない今の私では……」"

[[dialogue]]
speaker = "梨緒"
# 「まあ、そうだろうな。敵もそこまでバカではない、か……」
line = "「まあ、そうだろうな。敵もそこまでバカではない、か……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「代わりに極星学園のプリマステラを派遣するわ。この場にいる数十人──全員を連れて行って。みんな、できるわね？」
line = "「代わりに極星学園のプリマステラを派遣するわ。この場にいる数十人──全員を連れて行って。みんな、できるわね？」"

[[dialogue]]
speaker = "極星学園の星騎士"
# 「──はい、ルヴィネ様！！」
line = "「──はい、ルヴィネ様！！」"

[[dialogue]]
speaker = "unk"
# かつて１度目のデネブ来訪の際、ラクシャ──環はその身を挺して俺たちを救ってくれた。
line = "かつて１度目のデネブ来訪の際、ラクシャ──環はその身を挺して俺たちを救ってくれた。"

[[dialogue]]
speaker = "クロト"
# （いつか迎えに行くと約束したのに……）
line = "（いつか迎えに行くと約束したのに……）"

[[dialogue]]
speaker = "unk"
# 俺が行くことができなくてすまない、環──
line = "俺が行くことができなくてすまない、環──"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「──ふふ。見つけたわ」
line = "「──ふふ。見つけたわ」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「アルタイルの流星市国……その市街地に直通するための転送ルート。もう『私たち』を無駄をしなくていいわね──」
line = "「アルタイルの流星市国……その市街地に直通するための転送ルート。もう『私たち』を無駄をしなくていいわね──」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「ぐぅっ……！？」
line = "「ぐぅっ……！？」"

[[dialogue]]
speaker = "クロト"
# 「タッチの差だったな、ホロウ！　お前の好きにはさせない！」
line = "「タッチの差だったな、ホロウ！　お前の好きにはさせない！」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「緋宮、クロト……！！！　どこまでも諦めが悪い……３０００年前から、貴方は何度、私たちの邪魔をすれば気がすむの……！」
line = "「緋宮、クロト……！！！　どこまでも諦めが悪い……３０００年前から、貴方は何度、私たちの邪魔をすれば気がすむの……！」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「私への妨害は、創造神であるお父様の御意思に盾突くことに他ならない……咎人は粛清しなくては──」
line = "「私への妨害は、創造神であるお父様の御意思に盾突くことに他ならない……咎人は粛清しなくては──」"

[[dialogue]]
speaker = "unk"
# ホロウがはっきりと敵意を向けてくる。このまま自身の複製体を大量に展開するはず──
line = "ホロウがはっきりと敵意を向けてくる。このまま自身の複製体を大量に展開するはず──"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「────っ！？」
line = "「────っ！？」"

[[dialogue]]
speaker = "unk"
# しかしその瞬間、びくりとホロウの瞳が見開かれた。
line = "しかしその瞬間、びくりとホロウの瞳が見開かれた。"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「……そんな。私だけでも……し、しかし──」
line = "「……そんな。私だけでも……し、しかし──」"

[[dialogue]]
speaker = "ルヴィネ"
# 「──っ！？　まさか！　魔王、まずいわ……！！」
line = "「──っ！？　まさか！　魔王、まずいわ……！！」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「……喜びなさい、緋宮クロト」
line = "「……喜びなさい、緋宮クロト」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「お父様が御姿を見せる、と仰っているわ」
line = "「お父様が御姿を見せる、と仰っているわ」"

[[dialogue]]
speaker = "クロト"
# 「──ッ！？」
line = "「──ッ！？」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「私が相手をするのは合理的ではない……とお父様は判断なされた」
line = "「私が相手をするのは合理的ではない……とお父様は判断なされた」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「自らの不甲斐なさに、今すぐ命を絶って詫びたい気持ちよ……申し訳ございません、お父様……」
line = "「自らの不甲斐なさに、今すぐ命を絶って詫びたい気持ちよ……申し訳ございません、お父様……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「魔王！　ここを離れるわよ、早く──！！」
line = "「魔王！　ここを離れるわよ、早く──！！」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「──ふざけるな。それだけは認めない」
line = "「──ふざけるな。それだけは認めない」"

[[dialogue]]
speaker = "unk"
# 俺たちの背後を埋め尽くすように、数十体の複製体が横並びになる──
line = "俺たちの背後を埋め尽くすように、数十体の複製体が横並びになる──"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「この世すべてを創りたもうた主に、背を向ける無礼など絶対に許されることではない──」
line = "「この世すべてを創りたもうた主に、背を向ける無礼など絶対に許されることではない──」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「ひれ伏しなさい。お父様が、おいでになられるわ──」
line = "「ひれ伏しなさい。お父様が、おいでになられるわ──」"

[[dialogue]]
speaker = "unk"
# <b>それ</b>がいったい何なのか──すぐには理解できなかった。
line = "<b>それ</b>がいったい何なのか──すぐには理解できなかった。"

[[dialogue]]
speaker = "unk"
# しいて表現をするならば、それは途方もなく巨大な立方体で──
line = "しいて表現をするならば、それは途方もなく巨大な立方体で──"

[[dialogue]]
speaker = "unk"
# 今まで見てきた何よりも整然としているのに、何よりもグロテスクな。
line = "今まで見てきた何よりも整然としているのに、何よりもグロテスクな。"

[[dialogue]]
speaker = "unk"
# 目が、脳が、本能が、理解を拒む──<b>それ</b>はきっと、本来なら見てはならないもの。
line = "目が、脳が、本能が、理解を拒む──<b>それ</b>はきっと、本来なら見てはならないもの。"

[[dialogue]]
speaker = "unk"
# ヒトの身で、その存在には触れてはならぬと直感させるもの──
line = "ヒトの身で、その存在には触れてはならぬと直感させるもの──"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「いつ見ても美しい御姿。ああ、お父様──」
line = "「いつ見ても美しい御姿。ああ、お父様──」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「これが……ママを創った……」
line = "「これが……ママを創った……」"

[[dialogue]]
speaker = "フィオナ（魔王）"
# 「私たちの世界の……創造神……？」
line = "「私たちの世界の……創造神……？」"

[[dialogue]]
speaker = "unk"
# ──『<ruby=ゼノ>Ｘｅｎｏ</ruby>　<ruby=ロード>Ｌｏｒｄ</ruby>　<ruby=サンクティファイド>Ｓａｎｃｔｉｆｉｅｄ</ruby>』。
line = "──『<ruby>Ｘｅｎｏ<rt>ゼノ</rt></ruby>　<ruby>Ｌｏｒｄ<rt>ロード</rt></ruby>　<ruby>Ｓａｎｃｔｉｆｉｅｄ<rt>サンクティファイド</rt></ruby>』。"

[[dialogue]]
speaker = "unk"
# 全てを創りし、真の敵との邂逅だった────
line = "全てを創りし、真の敵との邂逅だった────"
