[[dialogue]]
speaker = "unk"
# 第８話,炎星,B
line = "第８話,炎星,B"

[[dialogue]]
speaker = "unk"
# 一方、こちらは──
line = "一方、こちらは──"

[[dialogue]]
speaker = "モンスター"
# 「イ～ッ！」
line = "「イ～ッ！」"

[[dialogue]]
speaker = "ユウリ"
# 「ち──おらよっ！　これでも、食らっとけ──！」
line = "「ち──おらよっ！　これでも、食らっとけ──！」"

[[dialogue]]
speaker = "モンスター"
# 「イイイイイッ……！！」
line = "「イイイイイッ……！！」"

[[dialogue]]
speaker = "ユウリ"
# 「あーもーったく！　キリがねえなあこいつら。しぶとすぎんだろ」
line = "「あーもーったく！　キリがねえなあこいつら。しぶとすぎんだろ」"

[[dialogue]]
speaker = "ルリエル"
# 「ひええ……倒しても倒しても起き上がってきます。だんだん数も増えてきましたし……」
line = "「ひええ……倒しても倒しても起き上がってきます。だんだん数も増えてきましたし……」"

[[dialogue]]
speaker = "モンスター"
# 「イイイイイイ！！」
line = "「イイイイイイ！！」"

[[dialogue]]
speaker = "モンスター"
# 「イ～ッ！」
line = "「イ～ッ！」"

[[dialogue]]
speaker = "unk"
# 繁華街──
line = "繁華街──"

[[dialogue]]
speaker = "unk"
# 人口の密集するこの地において、特殊モンスターの出現もまた増大していた。
line = "人口の密集するこの地において、特殊モンスターの出現もまた増大していた。"

[[dialogue]]
speaker = "unk"
# 彼らは星騎士を見るや誘引される性質のようで、飢えた獣のごとき凶暴性で何度でもよみがえっている。
line = "彼らは星騎士を見るや誘引される性質のようで、飢えた獣のごとき凶暴性で何度でもよみがえっている。"

[[dialogue]]
speaker = "unk"
# 変化することのない状況を見て、アナは小さく手を挙げた。
line = "変化することのない状況を見て、アナは小さく手を挙げた。"

[[dialogue]]
speaker = "アナ"
# 「あの」
line = "「あの」"

[[dialogue]]
speaker = "アナ"
# 「丸焼きにしてもいいでしょうか」
line = "「丸焼きにしてもいいでしょうか」"

[[dialogue]]
speaker = "ユウリ"
# 「丸焼き……って炎の星術ってことか？」
line = "「丸焼き……って炎の星術ってことか？」"

[[dialogue]]
speaker = "アナ"
# 「はい」
line = "「はい」"

[[dialogue]]
speaker = "ユウリ"
# 「構わねえけど……さっきあたしの炎を食らわせた感じ、効いてる素振りもなかったぞ」
line = "「構わねえけど……さっきあたしの炎を食らわせた感じ、効いてる素振りもなかったぞ」"

[[dialogue]]
speaker = "アナ"
# 「火力の問題と思われます。この個体たちは高い再生能力を有しているようですので、根こそぎ焼き尽くすのが有効かと」
line = "「火力の問題と思われます。この個体たちは高い再生能力を有しているようですので、根こそぎ焼き尽くすのが有効かと」"

[[dialogue]]
speaker = "unk"
# 淡々と語るアナ。
line = "淡々と語るアナ。"

[[dialogue]]
speaker = "unk"
# 他校の先輩であっても、彼女に怖気づく様子はなかった。
line = "他校の先輩であっても、彼女に怖気づく様子はなかった。"

[[dialogue]]
speaker = "ユウリ"
# 「ＯＫ。任せる。んで、あたしはどうすりゃいい？」
line = "「ＯＫ。任せる。んで、あたしはどうすりゃいい？」"

[[dialogue]]
speaker = "アナ"
# 「はい。これから私は発射まで約一分ほど無防備になります。その間のカバーをお願いしたいのですが」
line = "「はい。これから私は発射まで約一分ほど無防備になります。その間のカバーをお願いしたいのですが」"

[[dialogue]]
speaker = "ユウリ"
# 「護んのか。大丈夫だ、それなら得意分野だからな──指一本触れさせやしねえよ」
line = "「護んのか。大丈夫だ、それなら得意分野だからな──指一本触れさせやしねえよ」"

[[dialogue]]
speaker = "ルリエル"
# 「ユウリ先輩、あのモンスターに指はないのでは！？」
line = "「ユウリ先輩、あのモンスターに指はないのでは！？」"

[[dialogue]]
speaker = "ユウリ"
# 「細けぇことはいいんだよ、ノリだノリ！」
line = "「細けぇことはいいんだよ、ノリだノリ！」"

[[dialogue]]
speaker = "モンスター"
# 「ウィイイイイイ！！」
line = "「ウィイイイイイ！！」"

[[dialogue]]
speaker = "ユウリ"
# 「はっ──甘ぇっての！」
line = "「はっ──甘ぇっての！」"

[[dialogue]]
speaker = "モンスター"
# 「イイイイ──ッ！？」
line = "「イイイイ──ッ！？」"

[[dialogue]]
speaker = "unk"
# しかし、ユウリの鉄壁を前にその牙はまるで通らない。
line = "しかし、ユウリの鉄壁を前にその牙はまるで通らない。"

[[dialogue]]
speaker = "unk"
# 彼女の頑強さは学園最硬──
line = "彼女の頑強さは学園最硬──"

[[dialogue]]
speaker = "unk"
# 半魔族としての<ruby=フィジカル>身体能力</ruby>と、守護星カペラによる炎の庇護がその堅牢さを実現していた。
line = "半魔族としての<ruby>身体能力<rt>フィジカル</rt></ruby>と、守護星カペラによる炎の庇護がその堅牢さを実現していた。"

[[dialogue]]
speaker = "ルリエル"
# 「おおっ……さすがはユウリ先輩。どんな攻撃もへっちゃらですね」
line = "「おおっ……さすがはユウリ先輩。どんな攻撃もへっちゃらですね」"

[[dialogue]]
speaker = "ユウリ"
# 「ま、多少痛ぇことは痛ぇんだが……これくらいならどうってことねえな」
line = "「ま、多少痛ぇことは痛ぇんだが……これくらいならどうってことねえな」"

[[dialogue]]
speaker = "ルリエル"
# 「よーし……わたしもいっちょ頑張っちゃいますよ！　エネルギー全開です！」
line = "「よーし……わたしもいっちょ頑張っちゃいますよ！　エネルギー全開です！」"

[[dialogue]]
speaker = "unk"
# ルリエルは生まれながらにして、絶大な星力を持っていた。
line = "ルリエルは生まれながらにして、絶大な星力を持っていた。"

[[dialogue]]
speaker = "unk"
# それでも攻撃や防御、回復にあたってのコントロールを苦手としていた彼女は、その力を丸ごと他者へ贈る術を身に着けた。
line = "それでも攻撃や防御、回復にあたってのコントロールを苦手としていた彼女は、その力を丸ごと他者へ贈る術を身に着けた。"

[[dialogue]]
speaker = "ルリエル"
# 「２人に届け──エールホルン！」
line = "「２人に届け──エールホルン！」"

[[dialogue]]
speaker = "ユウリ"
# 「おおお……！　ハッ、さすがルリ──これなら一分と言わず、一時間でも保ちそうだ」
line = "「おおお……！　ハッ、さすがルリ──これなら一分と言わず、一時間でも保ちそうだ」"

[[dialogue]]
speaker = "モンスター"
# 「ィィィ！」
line = "「ィィィ！」"

[[dialogue]]
speaker = "unk"
# ルリエルの星力──守護星リゲルの加護を受けたその音色は、アナの攻撃力とユウリの防御力を爆発的に向上させた。
line = "ルリエルの星力──守護星リゲルの加護を受けたその音色は、アナの攻撃力とユウリの防御力を爆発的に向上させた。"

[[dialogue]]
speaker = "unk"
# そして……
line = "そして……"

[[dialogue]]
speaker = "ルリエル"
# 「どうですか、アナちゃん！？」
line = "「どうですか、アナちゃん！？」"

[[dialogue]]
speaker = "アナ"
# 「──」
line = "「──」"

[[dialogue]]
speaker = "unk"
# 返事はない。
line = "返事はない。"

[[dialogue]]
speaker = "unk"
# 極限まで<ruby=コンセントレーション>集中力</ruby>を高めている今の彼女には、外野の声すら届いていなかった。
line = "極限まで<ruby>集中力<rt>コンセントレーション</rt></ruby>を高めている今の彼女には、外野の声すら届いていなかった。"

[[dialogue]]
speaker = "unk"
# 軌道の計算。星力の制御。市街地への影響。
line = "軌道の計算。星力の制御。市街地への影響。"

[[dialogue]]
speaker = "unk"
# アナの頭脳では星術式が恐ろしい速度で組み合わされてゆき、その結晶が灼熱の焔となって矢先に宿る。
line = "アナの頭脳では星術式が恐ろしい速度で組み合わされてゆき、その結晶が灼熱の焔となって矢先に宿る。"

[[dialogue]]
speaker = "ユウリ"
# 「──そろそろか！？」
line = "「──そろそろか！？」"

[[dialogue]]
speaker = "ルリエル"
# 「みたいです！」
line = "「みたいです！」"

[[dialogue]]
speaker = "unk"
# アナが弓を構えてからちょうど６０秒が経過した。
line = "アナが弓を構えてからちょうど６０秒が経過した。"

[[dialogue]]
speaker = "アナ"
# 「──解析完了」
line = "「──解析完了」"

[[dialogue]]
speaker = "アナ"
# 「カーディナルエプシロン」
line = "「カーディナルエプシロン」"

[[dialogue]]
speaker = "モンスター"
# 「イイイイ──ッ！」
line = "「イイイイ──ッ！」"

[[dialogue]]
speaker = "unk"
# 放たれたのは弓矢というより砲撃だった。
line = "放たれたのは弓矢というより砲撃だった。"

[[dialogue]]
speaker = "unk"
# 絶大な火力と範囲を伴って直進する炎の波は、群がっていた相手どころか遥か彼方を周遊していたモンスターまでもを根こそぎ焼き尽くす。
line = "絶大な火力と範囲を伴って直進する炎の波は、群がっていた相手どころか遥か彼方を周遊していたモンスターまでもを根こそぎ焼き尽くす。"

[[dialogue]]
speaker = "ユウリ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "ルリエル"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# ５秒、１０秒と経過する。
line = "５秒、１０秒と経過する。"

[[dialogue]]
speaker = "unk"
# 起き上がってくる様子のない──というより跡形もない──特殊モンスターの末路を見て、アナは冷静に呟いた。
line = "起き上がってくる様子のない──というより跡形もない──特殊モンスターの末路を見て、アナは冷静に呟いた。"

[[dialogue]]
speaker = "アナ"
# 「<ruby=ミッションコンプリート>任務完了</ruby>。ご協力ありがとうございました」
line = "「<ruby>任務完了<rt>ミッションコンプリート</rt></ruby>。ご協力ありがとうございました」"

[[dialogue]]
speaker = "ユウリ"
# 「お、おう……ドン引きしちまったよ。すげえな」
line = "「お、おう……ドン引きしちまったよ。すげえな」"

[[dialogue]]
speaker = "ルリエル"
# 「しかもあれだけの大火力なのに街が一切焼けていません……！　これはどういう技術なのですか……！？」
line = "「しかもあれだけの大火力なのに街が一切焼けていません……！　これはどういう技術なのですか……！？」"

[[dialogue]]
speaker = "アナ"
# 「敵性のみを対象にするよう星力をコントロールしました。それと、軌道上にも複数体のモンスターがいたのを先ほど上空から確認しましたので」
line = "「敵性のみを対象にするよう星力をコントロールしました。それと、軌道上にも複数体のモンスターがいたのを先ほど上空から確認しましたので」"

[[dialogue]]
speaker = "ユウリ"
# 「サラッと言ってっけどとんでもねえ神業だぞ」
line = "「サラッと言ってっけどとんでもねえ神業だぞ」"

[[dialogue]]
speaker = "ルリエル"
# 「こ、これが新星副会長でありますか……！　同じ一年生なのに少々凹むであります……！」
line = "「こ、これが新星副会長でありますか……！　同じ一年生なのに少々凹むであります……！」"

[[dialogue]]
speaker = "アナ"
# 「２人のサポートあってのこと。凹む必要はない」
line = "「２人のサポートあってのこと。凹む必要はない」"

[[dialogue]]
speaker = "ユウリ"
# 「落ち着きが年下とは思えねえ……」
line = "「落ち着きが年下とは思えねえ……」"

[[dialogue]]
speaker = "アナ"
# 「ですが、私は空気が読めないとたまに言われます。どうでしょう？」
line = "「ですが、私は空気が読めないとたまに言われます。どうでしょう？」"

[[dialogue]]
speaker = "ユウリ"
# 「どうでしょうと言われてもな……」
line = "「どうでしょうと言われてもな……」"

[[dialogue]]
speaker = "unk"
# ひと段落した一行。
line = "ひと段落した一行。"

[[dialogue]]
speaker = "unk"
# 人払いをしていた繁華街にも、次第に人が戻り始めていった。
line = "人払いをしていた繁華街にも、次第に人が戻り始めていった。"
