[[dialogue]]
speaker = "unk"
# 第４話,墜落,B
line = "第４話,墜落,B"

[[dialogue]]
speaker = "アポロ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "アポロ"
# 「フィーニスの塔……か」
line = "「フィーニスの塔……か」"

[[dialogue]]
speaker = "アポロ"
# 「ふ……悪くない。<b>めがみ</b>とかいうやつもきっと、このアポロの敵なんだろうからな」
line = "「ふ……悪くない。<b>めがみ</b>とかいうやつもきっと、このアポロの敵なんだろうからな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「──っあっ！」
line = "「──っあっ！」"

[[dialogue]]
speaker = "ユウリ"
# 「っつつ……！　派手に叩き落とされたな──みんな、無事か！？」
line = "「っつつ……！　派手に叩き落とされたな──みんな、無事か！？」"

[[dialogue]]
speaker = "ルリエル"
# 「なんとか……っ！」
line = "「なんとか……っ！」"

[[dialogue]]
speaker = "マトイ"
# 「い、生きてる……？　ほっ……死んだかと思った──」
line = "「い、生きてる……？　ほっ……死んだかと思った──」"

[[dialogue]]
speaker = "セーラ"
# 「フィオナちゃん達のおかげかな？　この程度の衝撃で済んだのは……」
line = "「フィオナちゃん達のおかげかな？　この程度の衝撃で済んだのは……」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ……今の私には、星術がなくとも霊力がありましたから」
line = "「ええ……今の私には、星術がなくとも霊力がありましたから」"

[[dialogue]]
speaker = "フィオナ"
# 「ただ、それより緋宮会長のおかげでしょうか」
line = "「ただ、それより緋宮会長のおかげでしょうか」"

[[dialogue]]
speaker = "クロト"
# 「ああ──俺はまだ星術も使えるからな」
line = "「ああ──俺はまだ星術も使えるからな」"

[[dialogue]]
speaker = "サーシャ"
# 「そっか、会長くんの守護星は地球だから……」
line = "「そっか、会長くんの守護星は地球だから……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「さっすがクロトね！　最強の魔王は空に蓋をされてもバッチリってわけ！」
line = "「さっすがクロトね！　最強の魔王は空に蓋をされてもバッチリってわけ！」"

[[dialogue]]
speaker = "クロト"
# 「ただ、ひとまず凌いだとはいえ──窮地には変わりない」
line = "「ただ、ひとまず凌いだとはいえ──窮地には変わりない」"

[[dialogue]]
speaker = "unk"
# 俺とフィオナが手分けすることで、なんとかみんなをかばって着地した。
line = "俺とフィオナが手分けすることで、なんとかみんなをかばって着地した。"

[[dialogue]]
speaker = "unk"
# だが、もし俺たちがただの星騎士のままだったなら……間違いなく全員が粉々になっていた。
line = "だが、もし俺たちがただの星騎士のままだったなら……間違いなく全員が粉々になっていた。"

[[dialogue]]
speaker = "ニャリオン"
# 「と、とんでもないことになったニャン。このままじゃ会いにもいけニャいニャン……！」
line = "「と、とんでもないことになったニャン。このままじゃ会いにもいけニャいニャン……！」"

[[dialogue]]
speaker = "アナ"
# 「私たちだけではありません。恐らくここ以外でも、リンクを切られた星騎士が多数出ているはずです」
line = "「私たちだけではありません。恐らくここ以外でも、リンクを切られた星騎士が多数出ているはずです」"

[[dialogue]]
speaker = "ソフィア"
# 「それは……とんでもなく危険なんじゃ……？」
line = "「それは……とんでもなく危険なんじゃ……？」"

[[dialogue]]
speaker = "セーラ"
# 「ここで飛ぼうとしても──うん。無理っぽい。やばいね、打つ手なしだ」
line = "「ここで飛ぼうとしても──うん。無理っぽい。やばいね、打つ手なしだ」"

[[dialogue]]
speaker = "クロト"
# 「あの規模から見て、少なくとも流星市国全域は天蓋の影響下にありそうです。その分、モンスターの侵攻だって止めきれない」
line = "「あの規模から見て、少なくとも流星市国全域は天蓋の影響下にありそうです。その分、モンスターの侵攻だって止めきれない」"

[[dialogue]]
speaker = "unk"
# フィーニスの塔の頂上──アポロはあそこから、人間界を見下ろしてる。
line = "フィーニスの塔の頂上──アポロはあそこから、人間界を見下ろしてる。"

[[dialogue]]
speaker = "unk"
# それはかつてセイファート学園長も達した世界の『視座』。
line = "それはかつてセイファート学園長も達した世界の『視座』。"

[[dialogue]]
speaker = "unk"
# <ruby=いただき>頂</ruby>に立つアポロが、そこから傘のように天蓋を張っているのが現状だ。
line = "<ruby>頂<rt>いただき</rt></ruby>に立つアポロが、そこから傘のように天蓋を張っているのが現状だ。"

[[dialogue]]
speaker = "ニャリオン"
# 「フィオナ嬢。霊力を使ってなんとかあそこまで飛べないのかニャ？」
line = "「フィオナ嬢。霊力を使ってなんとかあそこまで飛べないのかニャ？」"

[[dialogue]]
speaker = "フィオナ"
# 「塔の頂上は成層圏より上……霊力だけであの高空まで飛翔するのは困難です。まして、そのまま姉さんと戦うことなど」
line = "「塔の頂上は成層圏より上……霊力だけであの高空まで飛翔するのは困難です。まして、そのまま姉さんと戦うことなど」"

[[dialogue]]
speaker = "クロト"
# 「……同感だ。到達できるにしても、それがやっとだろう」
line = "「……同感だ。到達できるにしても、それがやっとだろう」"

[[dialogue]]
speaker = "unk"
# 仮面にダメージは入れられても、再生を防ぐことはできなかった。
line = "仮面にダメージは入れられても、再生を防ぐことはできなかった。"

[[dialogue]]
speaker = "unk"
# 片手落ちの状態で対面できたとしても、また叩き落されるのが見えている。
line = "片手落ちの状態で対面できたとしても、また叩き落されるのが見えている。"

[[dialogue]]
speaker = "マトイ"
# 「じゃ、じゃあもう無理ってこと……？」
line = "「じゃ、じゃあもう無理ってこと……？」"

[[dialogue]]
speaker = "クロト"
# 「いや──そうとも限らない」
line = "「いや──そうとも限らない」"

[[dialogue]]
speaker = "セーラ"
# 「もしかして……会長さんだけで行くつもり？」
line = "「もしかして……会長さんだけで行くつもり？」"

[[dialogue]]
speaker = "クロト"
# 「いえ……正直、俺一人では厳しい。みんなの力が必要なのは変わりません」
line = "「いえ……正直、俺一人では厳しい。みんなの力が必要なのは変わりません」"

[[dialogue]]
speaker = "ソフィア"
# 「ですが、今の私たちでは……」
line = "「ですが、今の私たちでは……」"

[[dialogue]]
speaker = "ニャリオン"
# 「天蓋をなんとかする方法があるのかニャ……？」
line = "「天蓋をなんとかする方法があるのかニャ……？」"

[[dialogue]]
speaker = "クロト"
# 「試してみないとわからないが──うまくいけば。間に合いそうか、アナ」
line = "「試してみないとわからないが──うまくいけば。間に合いそうか、アナ」"

[[dialogue]]
speaker = "アナ"
# 「ぎりぎりですね。すでに根回しは終えていますが」
line = "「ぎりぎりですね。すでに根回しは終えていますが」"

[[dialogue]]
speaker = "unk"
# 天蓋への対策は事前に考えられていた重要事項だった。
line = "天蓋への対策は事前に考えられていた重要事項だった。"

[[dialogue]]
speaker = "unk"
# 展開される前に叩く──という作戦は失敗に終わったが、次の一手がないわけじゃない。
line = "展開される前に叩く──という作戦は失敗に終わったが、次の一手がないわけじゃない。"

[[dialogue]]
speaker = "サーシャ"
# 「でも……いざ頂上までたどり着いたとしても、不安よね」
line = "「でも……いざ頂上までたどり着いたとしても、不安よね」"

[[dialogue]]
speaker = "セーラ"
# 「また同じにならないとも限らないしねー。ま……１％でも希望があるならいい方なのかな」
line = "「また同じにならないとも限らないしねー。ま……１％でも希望があるならいい方なのかな」"

[[dialogue]]
speaker = "クロト"
# 「それについては……むしろ、俺は先ほどのアポロを見て、可能性を感じました」
line = "「それについては……むしろ、俺は先ほどのアポロを見て、可能性を感じました」"

[[dialogue]]
speaker = "クロト"
# 「だってアポロは……悲しんでいるように見えた」
line = "「だってアポロは……悲しんでいるように見えた」"

[[dialogue]]
speaker = "フィオナ"
# 「……はい。姉さんは……私たち以外とも、戦っているように感じました」
line = "「……はい。姉さんは……私たち以外とも、戦っているように感じました」"

[[dialogue]]
speaker = "unk"
# アポロは間違いなく<ruby=さいな>苛</ruby>まれていた。
line = "アポロは間違いなく<ruby>苛<rt>さいな</rt></ruby>まれていた。"

[[dialogue]]
speaker = "unk"
# 仮面のもたらす使徒としての使命と、己が本当の姿との狭間で。
line = "仮面のもたらす使徒としての使命と、己が本当の姿との狭間で。"

[[dialogue]]
speaker = "クロト"
# 「記憶を失っても。自我が封じられても。お姉さんの人格は生きている」
line = "「記憶を失っても。自我が封じられても。お姉さんの人格は生きている」"

[[dialogue]]
speaker = "クロト"
# 「それに、事実──フィオナの言葉はあの仮面にヒビを入れた」
line = "「それに、事実──フィオナの言葉はあの仮面にヒビを入れた」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ。すぐに修復されてしまいましたが……」
line = "「ええ。すぐに修復されてしまいましたが……」"

[[dialogue]]
speaker = "サーシャ"
# 「けれど、どんな攻撃よりもフィオナちゃんの言葉が響いた──」
line = "「けれど、どんな攻撃よりもフィオナちゃんの言葉が響いた──」"

[[dialogue]]
speaker = "セーラ"
# 「ワンチャンある、って感じかなー」
line = "「ワンチャンある、って感じかなー」"

[[dialogue]]
speaker = "unk"
# <ruby=フィオナ>妹</ruby>の想いはきっと届く。そう信じずにはいられなかった。
line = "<ruby>妹<rt>フィオナ</rt></ruby>の想いはきっと届く。そう信じずにはいられなかった。"

[[dialogue]]
speaker = "ニャリオン"
# 「で、でも結局、ワガハイ達の状況は変わってないニャ……？」
line = "「で、でも結局、ワガハイ達の状況は変わってないニャ……？」"

[[dialogue]]
speaker = "クロト"
# 「……まだ希望が潰えたわけじゃない。天蓋の上にさえ出られれば──星力をまたを取り戻せる」
line = "「……まだ希望が潰えたわけじゃない。天蓋の上にさえ出られれば──星力をまたを取り戻せる」"

[[dialogue]]
speaker = "ユウリ"
# 「けど、あそこに向かう方法がねーって話だろ？　このままじゃ地上にいたって何もできねえし──」
line = "「けど、あそこに向かう方法がねーって話だろ？　このままじゃ地上にいたって何もできねえし──」"

[[dialogue]]
speaker = "ユウリ"
# 「って……待て。会長さん、まさかとんでもないこと考えてねーか？」
line = "「って……待て。会長さん、まさかとんでもないこと考えてねーか？」"

[[dialogue]]
speaker = "クロト"
# 「ああ。そのまさかしかないよ、ユウリ」
line = "「ああ。そのまさかしかないよ、ユウリ」"

[[dialogue]]
speaker = "unk"
# 俺は、改めてみんなを見渡して言った。
line = "俺は、改めてみんなを見渡して言った。"

[[dialogue]]
speaker = "クロト"
# 「もう一度──俺たちで塔を昇る。今度は一階から、アポロのいる頂上まで」
line = "「もう一度──俺たちで塔を昇る。今度は一階から、アポロのいる頂上まで」"

[[dialogue]]
speaker = "マトイ"
# 「！？　てっぺんまで──！？」
line = "「！？　てっぺんまで──！？」"

[[dialogue]]
speaker = "アナ"
# 「無茶──としか思えませんが……」
line = "「無茶──としか思えませんが……」"

[[dialogue]]
speaker = "クロト"
# 「自分でもそう思う。だけど、他に方法はない」
line = "「自分でもそう思う。だけど、他に方法はない」"

[[dialogue]]
speaker = "フィオナ"
# 「確かに──塔の内部で流れる時間は現実よりも穏やかです。踏破さえできれば、間に合うかもしれませんが……」
line = "「確かに──塔の内部で流れる時間は現実よりも穏やかです。踏破さえできれば、間に合うかもしれませんが……」"

[[dialogue]]
speaker = "unk"
# それは──かつてセイファート学園長が通った道筋だ。
line = "それは──かつてセイファート学園長が通った道筋だ。"

[[dialogue]]
speaker = "unk"
# 仮面によって失われた妻を求めて塔を昇った。そんな制覇者たる彼と同じ軌跡を、俺たちで辿る。
line = "仮面によって失われた妻を求めて塔を昇った。そんな制覇者たる彼と同じ軌跡を、俺たちで辿る。"

[[dialogue]]
speaker = "ヴィーナス"
# 「──いいじゃない。だって、これが最後のリクリエなんでしょ？　だったら、今ムチャしないでいつムチャするのよ」
line = "「──いいじゃない。だって、これが最後のリクリエなんでしょ？　だったら、今ムチャしないでいつムチャするのよ」"

[[dialogue]]
speaker = "サーシャ"
# 「ふぅ。ヴィーナスちゃんはヴィーナスちゃんねえ」
line = "「ふぅ。ヴィーナスちゃんはヴィーナスちゃんねえ」"

[[dialogue]]
speaker = "ルリエル"
# 「ですが……わずかでも希望が残っているなら、そこに懸けてみたいです！」
line = "「ですが……わずかでも希望が残っているなら、そこに懸けてみたいです！」"

[[dialogue]]
speaker = "unk"
# 全員で──そびえ立つフィーニスの塔に向き直る。
line = "全員で──そびえ立つフィーニスの塔に向き直る。"

[[dialogue]]
speaker = "unk"
# どんなに果てしない道だとしても、そこに希望の光があるなら俺たちは諦めない──
line = "どんなに果てしない道だとしても、そこに希望の光があるなら俺たちは諦めない──"
