[[dialogue]]
speaker = "unk"
# 第３話,抹殺の剣,B
line = "第３話,抹殺の剣,B"

[[dialogue]]
speaker = "フィオナ（魔王）"
# 「平行世界デネブの……セイファート学園長！」
line = "「平行世界デネブの……セイファート学園長！」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「ママが言ってた頼もしい増援って、学園長のことだったのね！」
line = "「ママが言ってた頼もしい増援って、学園長のことだったのね！」"

[[dialogue]]
speaker = "セイファート"
# 「──懐かしい顔ぶれだな。本当に、１０年前の流星市国に戻ってきたようだ……」
line = "「──懐かしい顔ぶれだな。本当に、１０年前の流星市国に戻ってきたようだ……」"

[[dialogue]]
speaker = "クロト"
# 「まさかあなたが来てくれるだなんて、思っていませんでした……もう、会えないとばかり……！」
line = "「まさかあなたが来てくれるだなんて、思っていませんでした……もう、会えないとばかり……！」"

[[dialogue]]
speaker = "梨緒"
# 「魔王、無事か！？」
line = "「魔王、無事か！？」"

[[dialogue]]
speaker = "クロト"
# 「梨緒、ジグ……！　守護天使たちの解放は終わったんだな！」
line = "「梨緒、ジグ……！　守護天使たちの解放は終わったんだな！」"

[[dialogue]]
speaker = "梨緒"
# 「ああ。そちらは問題ない。<ruby=だいれいそう>第零層</ruby>でホロウたちに手こずっていたところに、学園長が駆けつけてくれてな」
line = "「ああ。そちらは問題ない。<ruby>第零層<rt>だいれいそう</rt></ruby>でホロウたちに手こずっていたところに、学園長が駆けつけてくれてな」"

[[dialogue]]
speaker = "ジグ"
# 「意外な再会だったね。まさか学園長に助けてもらうとは思わなかったよ」
line = "「意外な再会だったね。まさか学園長に助けてもらうとは思わなかったよ」"

[[dialogue]]
speaker = "クロト"
# 「２人とも『学園長』って……そうか。ベガでも、セイファート『学園長』だったんだな……」
line = "「２人とも『学園長』って……そうか。ベガでも、セイファート『学園長』だったんだな……」"

[[dialogue]]
speaker = "梨緒"
# 「かつて死に別れた人との再会は、何度味わっても不思議なものだが……」
line = "「かつて死に別れた人との再会は、何度味わっても不思議なものだが……」"

[[dialogue]]
speaker = "ジグ"
# 「ああ。まだ取り返しがつく──そう思うだけでも、気を強く持てるというものさ」
line = "「ああ。まだ取り返しがつく──そう思うだけでも、気を強く持てるというものさ」"

[[dialogue]]
speaker = "ベアトリス"
# 「おじさん……間違いない！　おじさん、ですよね！？」
line = "「おじさん……間違いない！　おじさん、ですよね！？」"

[[dialogue]]
speaker = "セイファート"
# 「──む？　君は……」
line = "「──む？　君は……」"

[[dialogue]]
speaker = "ベアトリス"
# 「わ、私です！　１０年前に、魔界で助けてもらった……！」
line = "「わ、私です！　１０年前に、魔界で助けてもらった……！」"

[[dialogue]]
speaker = "セイファート"
# 「……あの吸血鬼の少女か。この場に居合わすほどの星騎士に成長していたとは──立派になったな」
line = "「……あの吸血鬼の少女か。この場に居合わすほどの星騎士に成長していたとは──立派になったな」"

[[dialogue]]
speaker = "ベアトリス"
# 「は、はいっ……！　私、おじさんとの約束を果たし続けて、ここまで来ました……！」
line = "「は、はいっ……！　私、おじさんとの約束を果たし続けて、ここまで来ました……！」"

[[dialogue]]
speaker = "セイファート"
# 「いい面構えだ。だが傷も深いだろう……しばし、休んでいるがいい」
line = "「いい面構えだ。だが傷も深いだろう……しばし、休んでいるがいい」"

[[dialogue]]
speaker = "ラクシャ"
# 「うーわ。いくら恩師との再会だからって、なっさけない顔しちゃって。ボクがこんなに近づいても気づかないし」
line = "「うーわ。いくら恩師との再会だからって、なっさけない顔しちゃって。ボクがこんなに近づいても気づかないし」"

[[dialogue]]
speaker = "クロト"
# 「環……！？　いや、そんな情けない顔なんて」
line = "「環……！？　いや、そんな情けない顔なんて」"

[[dialogue]]
speaker = "ラクシャ"
# 「してた。すっごいしてた。ていうか、ひどいよね？　迎えに行くって約束してくれたのにさー？」
line = "「してた。すっごいしてた。ていうか、ひどいよね？　迎えに行くって約束してくれたのにさー？」"

[[dialogue]]
speaker = "ラクシャ"
# 「封印から解放されて目を開けたら、キミじゃなくムサいおじさんが立ってた時のボクの気持ちを答えよ──って感じなんだけど？」
line = "「封印から解放されて目を開けたら、キミじゃなくムサいおじさんが立ってた時のボクの気持ちを答えよ──って感じなんだけど？」"

[[dialogue]]
speaker = "クロト"
# 「すまない環……この埋め合わせは絶対にするから」
line = "「すまない環……この埋め合わせは絶対にするから」"

[[dialogue]]
speaker = "ラクシャ"
# 「ま、嫌味はこのくらいにしとこっか。ここまで頑張ったキミたちに、守護天使の癒しの力を贈るよ！」
line = "「ま、嫌味はこのくらいにしとこっか。ここまで頑張ったキミたちに、守護天使の癒しの力を贈るよ！」"

[[dialogue]]
speaker = "クロト"
# 「守護天使ラクシャに、こんな力はないはずじゃ……？」
line = "「守護天使ラクシャに、こんな力はないはずじゃ……？」"

[[dialogue]]
speaker = "ラクシャ"
# 「デネブの守護天使たちは今、みーんな世界の摂理を維持するために休眠中だよ。元々弱らされて、封印されたわけだしね」
line = "「デネブの守護天使たちは今、みーんな世界の摂理を維持するために休眠中だよ。元々弱らされて、封印されたわけだしね」"

[[dialogue]]
speaker = "ラクシャ"
# 「今から体を創るより、権能だけをボクに預けた方が効率がいいって判断。これはマグダレナから借りた力さ」
line = "「今から体を創るより、権能だけをボクに預けた方が効率がいいって判断。これはマグダレナから借りた力さ」"

[[dialogue]]
speaker = "ラクシャ"
# 「ふふっ。最終決戦にふさわしいスーパーモードでしょ？」
line = "「ふふっ。最終決戦にふさわしいスーパーモードでしょ？」"

[[dialogue]]
speaker = "unk"
# 俺と環の会話の傍ら、セイファート学園長がＤＩＳＣを取り出して通信を行っていた。
line = "俺と環の会話の傍ら、セイファート学園長がＤＩＳＣを取り出して通信を行っていた。"

[[dialogue]]
speaker = "セイファート"
# 「──マルキア、アニュラス。配置についたか？」
line = "「──マルキア、アニュラス。配置についたか？」"

[[dialogue]]
speaker = "マルキア"
# 『ええ──あなた』
line = "『ええ──あなた』"

[[dialogue]]
speaker = "アニュラス"
# 『問題ありません、お父様！！』
line = "『問題ありません、お父様！！』"

[[dialogue]]
speaker = "セイファート"
# 「よし──私は創造神の相手をする。１０年前の雪辱を晴らすぞ。デネブ各地にはびこる複製体を蹂躙しろ！！」
line = "「よし──私は創造神の相手をする。１０年前の雪辱を晴らすぞ。デネブ各地にはびこる複製体を蹂躙しろ！！」"

[[dialogue]]
speaker = "アニュラス"
# 『承知いたしました！！』
line = "『承知いたしました！！』"

[[dialogue]]
speaker = "チナ"
# 「マジかよ……英雄ジェラルドも、戦姫マルキアも、生きてただなんて！！」
line = "「マジかよ……英雄ジェラルドも、戦姫マルキアも、生きてただなんて！！」"

[[dialogue]]
speaker = "グレイス"
# 「私たちも膝を折っている場合じゃありませんね！　何としても、ここから巻き返さねばっ！」
line = "「私たちも膝を折っている場合じゃありませんね！　何としても、ここから巻き返さねばっ！」"

[[dialogue]]
speaker = "レティシア"
# 「顔を見るのは初めてだけれど……チナたちが信頼を置く相手なら、背中を預けられそうね」
line = "「顔を見るのは初めてだけれど……チナたちが信頼を置く相手なら、背中を預けられそうね」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「本当に……愚かな者たち。ピークをとうに過ぎた老体の星騎士が来たくらいで、盛り返せると本気で信じているだなんて」
line = "「本当に……愚かな者たち。ピークをとうに過ぎた老体の星騎士が来たくらいで、盛り返せると本気で信じているだなんて」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「お父様を堕落させる剣……あの出来損ないが、命を賭してまで創り出したものがそれ？」
line = "「お父様を堕落させる剣……あの出来損ないが、命を賭してまで創り出したものがそれ？」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「お笑いだわ。そんなもの、届くわけがないでしょう」
line = "「お笑いだわ。そんなもの、届くわけがないでしょう」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「教えてあげるわ。どうしようもない実力の差というもの──」
line = "「教えてあげるわ。どうしようもない実力の差というもの──」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「────をっ！？」
line = "「────をっ！？」"

[[dialogue]]
speaker = "セイファート"
# 「──遅い」
line = "「──遅い」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 「────────！？！？」
line = "「────────！？！？」"

[[dialogue]]
speaker = "クロト"
# 「──なっ！？」
line = "「──なっ！？」"

[[dialogue]]
speaker = "unk"
# ホロウが瞬く間に両断され、遠く離れていた『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』にも、セイファート学園長が一太刀を浴びせていた──
line = "ホロウが瞬く間に両断され、遠く離れていた『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』にも、セイファート学園長が一太刀を浴びせていた──"

[[dialogue]]
speaker = "セイファート"
# 「まず１次元、楔を打ち込ませてもらった。あと７度、斬りつければそこまでだ」
line = "「まず１次元、楔を打ち込ませてもらった。あと７度、斬りつければそこまでだ」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「いくらテルルの霊力補助を受けているとはいえ……そんな、馬鹿な……！？」
line = "「いくらテルルの霊力補助を受けているとはいえ……そんな、馬鹿な……！？」"

[[dialogue]]
speaker = "セイファート"
# 「私もこの１０年……遊んでいたわけではない」
line = "「私もこの１０年……遊んでいたわけではない」"

[[dialogue]]
speaker = "セイファート"
# 「──少年、呼吸を整えろ。復帰できるようになったら、援護を頼みたい。老体に鞭を打っているのだ。長くはもたない」
line = "「──少年、呼吸を整えろ。復帰できるようになったら、援護を頼みたい。老体に鞭を打っているのだ。長くはもたない」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 「──────ッ！！」
line = "「──────ッ！！」"

[[dialogue]]
speaker = "unk"
# 『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』の放つ光弾がセイファート学園長に殺到するが、彼は怯むことなく距離を詰める。
line = "『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』の放つ光弾がセイファート学園長に殺到するが、彼は怯むことなく距離を詰める。"

[[dialogue]]
speaker = "セイファート"
# 「──無駄だッ！！！」
line = "「──無駄だッ！！！」"

[[dialogue]]
speaker = "unk"
# 高次元存在に触れられる剣によって、その光弾が全て弾き落とされ──
line = "高次元存在に触れられる剣によって、その光弾が全て弾き落とされ──"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 「────ギ、ギ────！！」
line = "「────ギ、ギ────！！」"

[[dialogue]]
speaker = "セイファート"
# 「２つ目の楔だ。このまま我々の次元まで降りてきてもらおう──悪神よ！」
line = "「２つ目の楔だ。このまま我々の次元まで降りてきてもらおう──悪神よ！」"

[[dialogue]]
speaker = "unk"
# 『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』とホロウ・ルヴィネ。２つの脅威を、舞うようにいなし、圧倒していく流星の騎士の背中から目が離せない。
line = "『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』とホロウ・ルヴィネ。２つの脅威を、舞うようにいなし、圧倒していく流星の騎士の背中から目が離せない。"

[[dialogue]]
speaker = "unk"
# あなたをずっと見てきた。いつか追い付きたい、追い越したいと思い続けて──その想いは儚く砕けて消えたはずだった……
line = "あなたをずっと見てきた。いつか追い付きたい、追い越したいと思い続けて──その想いは儚く砕けて消えたはずだった……"

[[dialogue]]
speaker = "unk"
# ──でも！
line = "──でも！"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「──クロト！！」
line = "「──クロト！！」"

[[dialogue]]
speaker = "フィオナ（魔王）"
# 「──緋宮会長！！」
line = "「──緋宮会長！！」"

[[dialogue]]
speaker = "クロト"
# 「ああ！！　もう、立ち上がれる……行ける！！」
line = "「ああ！！　もう、立ち上がれる……行ける！！」"

[[dialogue]]
speaker = "クロト"
# 「総員──学園長への、ホロウの接近を許すな！」
line = "「総員──学園長への、ホロウの接近を許すな！」"

[[dialogue]]
speaker = "クロト"
# 「露払いは俺たちの役目……流星の騎士の刃を届ける！　死力を尽くすぞ！！」
line = "「露払いは俺たちの役目……流星の騎士の刃を届ける！　死力を尽くすぞ！！」"
