[[dialogue]]
speaker = "unk"
# 第７話,破滅の誘惑,B
line = "第７話,破滅の誘惑,B"

[[dialogue]]
speaker = "梨緒"
# 「ジグ……？」
line = "「ジグ……？」"

[[dialogue]]
speaker = "ジグ"
# 「君はかつて共に戦った仲間だ。だから言うよ」
line = "「君はかつて共に戦った仲間だ。だから言うよ」"

[[dialogue]]
speaker = "ジグ"
# 「やり直そう、アガサ」
line = "「やり直そう、アガサ」"

[[dialogue]]
speaker = "梨緒"
# 「──ッ」
line = "「──ッ」"

[[dialogue]]
speaker = "ジグ"
# 「君も自分の弱さを痛感したはずだ。だけど世界がなくなれば、その弱さもなかったことになる」
line = "「君も自分の弱さを痛感したはずだ。だけど世界がなくなれば、その弱さもなかったことになる」"

[[dialogue]]
speaker = "ジグ"
# 「私の絶望も、君の弱さもまっさらにして、一から世界をやり直すんだ」
line = "「私の絶望も、君の弱さもまっさらにして、一から世界をやり直すんだ」"

[[dialogue]]
speaker = "梨緒"
# 「やり……なおす……」
line = "「やり……なおす……」"

[[dialogue]]
speaker = "ジグ"
# 「ああ、そうだ」
line = "「ああ、そうだ」"

[[dialogue]]
speaker = "ジグ"
# 「ベガの滅びの瞬間、私は“真なる神”を拝する機会を賜った」
line = "「ベガの滅びの瞬間、私は“真なる神”を拝する機会を賜った」"

[[dialogue]]
speaker = "ジグ"
# 「そして気付いたんだ。神に抗おうとすることが愚かだったのだと」
line = "「そして気付いたんだ。神に抗おうとすることが愚かだったのだと」"

[[dialogue]]
speaker = "ジグ"
# 「だから私は願った。そんな愚かな自分を捨てて、何もかもなかったことにしたいと」
line = "「だから私は願った。そんな愚かな自分を捨てて、何もかもなかったことにしたいと」"

[[dialogue]]
speaker = "ジグ"
# 「神は私にその機会を与えてくださった」
line = "「神は私にその機会を与えてくださった」"

[[dialogue]]
speaker = "unk"
# ジグが倒れた梨緒に向かって、微笑みながら手を差し伸べる。
line = "ジグが倒れた梨緒に向かって、微笑みながら手を差し伸べる。"

[[dialogue]]
speaker = "unk"
# 梨緒が泣いていた時に『可能性はある』と言ってくれた時の笑顔が、仮面越しに見えた気がした。
line = "梨緒が泣いていた時に『可能性はある』と言ってくれた時の笑顔が、仮面越しに見えた気がした。"

[[dialogue]]
speaker = "ジグ"
# 「さぁ、一緒に行こう、アガサ」
line = "「さぁ、一緒に行こう、アガサ」"

[[dialogue]]
speaker = "ジグ"
# 「弱くて役に立たない自分はここに捨てて、新しい自分になろう」
line = "「弱くて役に立たない自分はここに捨てて、新しい自分になろう」"

[[dialogue]]
speaker = "梨緒"
# 「自分を……捨てる……」
line = "「自分を……捨てる……」"

[[dialogue]]
speaker = "unk"
# ジグの手を取るか逡巡する梨緒。
line = "ジグの手を取るか逡巡する梨緒。"

[[dialogue]]
speaker = "unk"
# 潤んだ瞳に、ジグの優しい笑みが映る。
line = "潤んだ瞳に、ジグの優しい笑みが映る。"

[[dialogue]]
speaker = "梨緒"
# 「わた、し……は──」
line = "「わた、し……は──」"

[[dialogue]]
speaker = "unk"
# そして梨緒は──
line = "そして梨緒は──"

[[dialogue]]
speaker = "ベアトリス"
# 「おおおおっ！！」
line = "「おおおおっ！！」"

[[dialogue]]
speaker = "unk"
# 頭上から鮮血色の閃光が走り、梨緒とジグの間に槍撃が突き刺さる。
line = "頭上から鮮血色の閃光が走り、梨緒とジグの間に槍撃が突き刺さる。"

[[dialogue]]
speaker = "ナターシャ"
# 「スワローテイルダンス！」
line = "「スワローテイルダンス！」"

[[dialogue]]
speaker = "unk"
# 高速で飛行するナターシャの残像が実像を持ち、分身を生む。
line = "高速で飛行するナターシャの残像が実像を持ち、分身を生む。"

[[dialogue]]
speaker = "unk"
# さらに無数のナターシャの分身が、次々にジグに斬りかかった。
line = "さらに無数のナターシャの分身が、次々にジグに斬りかかった。"

[[dialogue]]
speaker = "unk"
# しかしジグは平然と反応し、大剣の一振りでナターシャの分身を薙ぎ払う。
line = "しかしジグは平然と反応し、大剣の一振りでナターシャの分身を薙ぎ払う。"

[[dialogue]]
speaker = "ジグ"
# 「モンスターがいたはずだけど、あれだけじゃ不十分だったかな」
line = "「モンスターがいたはずだけど、あれだけじゃ不十分だったかな」"

[[dialogue]]
speaker = "ナターシャ"
# 「極星従騎を残してきたからね。少しは持ちこたえてくれるはずだよ」
line = "「極星従騎を残してきたからね。少しは持ちこたえてくれるはずだよ」"

[[dialogue]]
speaker = "梨緒"
# 「ベアト……ナターシャ……」
line = "「ベアト……ナターシャ……」"

[[dialogue]]
speaker = "ナターシャ"
# 「あーあ、また顔ぐしゃぐしゃにして泣いちゃって。手のかかる委員長なんだから」
line = "「あーあ、また顔ぐしゃぐしゃにして泣いちゃって。手のかかる委員長なんだから」"

[[dialogue]]
speaker = "ナターシャ"
# 「ベアト、任せた！」
line = "「ベアト、任せた！」"

[[dialogue]]
speaker = "ベアトリス"
# 「うん！」
line = "「うん！」"

[[dialogue]]
speaker = "unk"
# ナターシャが梨緒とベアトリスを背に庇うと、ベアトリスは梨緒を抱え、来た道を全速力で飛ぶ。
line = "ナターシャが梨緒とベアトリスを背に庇うと、ベアトリスは梨緒を抱え、来た道を全速力で飛ぶ。"

[[dialogue]]
speaker = "unk"
# ベアトリスは神殿の最奥を離脱し、先刻の戦いでできた瓦礫に隠れた。
line = "ベアトリスは神殿の最奥を離脱し、先刻の戦いでできた瓦礫に隠れた。"

[[dialogue]]
speaker = "ベアトリス"
# 「梨緒ちゃん、大丈夫！？」
line = "「梨緒ちゃん、大丈夫！？」"

[[dialogue]]
speaker = "梨緒"
# 「戻ら……ないと……ナターシャが……ジグが……」
line = "「戻ら……ないと……ナターシャが……ジグが……」"

[[dialogue]]
speaker = "梨緒"
# 「ジグは、私が助けないと……ナターシャを、１人には……あ、うぅぅっ……ああぁっ……！」
line = "「ジグは、私が助けないと……ナターシャを、１人には……あ、うぅぅっ……ああぁっ……！」"

[[dialogue]]
speaker = "ベアトリス"
# 「落ち着いて、梨緒ちゃん！」
line = "「落ち着いて、梨緒ちゃん！」"

[[dialogue]]
speaker = "梨緒"
# 「でも、このままじゃ、ナターシャが……っ……ジグ……ぅっ……うぅああっ……！」
line = "「でも、このままじゃ、ナターシャが……っ……ジグ……ぅっ……うぅああっ……！」"

[[dialogue]]
speaker = "ベアトリス"
# 「今の梨緒ちゃんが行っても何もできないよ！　何が起きたの！？　あの人と何があったのか教えて！？」
line = "「今の梨緒ちゃんが行っても何もできないよ！　何が起きたの！？　あの人と何があったのか教えて！？」"

[[dialogue]]
speaker = "梨緒"
# 「ぅっ……私は……わた、しは……何も、できなくて……」
line = "「ぅっ……私は……わた、しは……何も、できなくて……」"

[[dialogue]]
speaker = "梨緒"
# 「ジグは、私を支えてくれたのに……っ……私は、何も、してやれなくて……」
line = "「ジグは、私を支えてくれたのに……っ……私は、何も、してやれなくて……」"

[[dialogue]]
speaker = "梨緒"
# 「ジグは、未来を知って……誰よりも絶望していたのに……なのに……それでも戦って……」
line = "「ジグは、未来を知って……誰よりも絶望していたのに……なのに……それでも戦って……」"

[[dialogue]]
speaker = "梨緒"
# 「私は、そんなジグを……見捨てて……っ」
line = "「私は、そんなジグを……見捨てて……っ」"

[[dialogue]]
speaker = "梨緒"
# 「私は──私の弱さに耐えられない！！」
line = "「私は──私の弱さに耐えられない！！」"

[[dialogue]]
speaker = "梨緒"
# 「うぅっ、うぅっ……あああ……っ！　う──ああぁあぁあああっ！！」
line = "「うぅっ、うぅっ……あああ……っ！　う──ああぁあぁあああっ！！」"

[[dialogue]]
speaker = "ベアトリス"
# 「梨緒ちゃん……」
line = "「梨緒ちゃん……」"

[[dialogue]]
speaker = "ベアトリス"
# 「私、梨緒ちゃんのために何ができるかわからないけど……それでも……」
line = "「私、梨緒ちゃんのために何ができるかわからないけど……それでも……」"

[[dialogue]]
speaker = "unk"
# ベアトリスが打ちひしがれる梨緒にそっと近づき、こぼれる涙をハンカチで優しく拭う。
line = "ベアトリスが打ちひしがれる梨緒にそっと近づき、こぼれる涙をハンカチで優しく拭う。"

[[dialogue]]
speaker = "梨緒"
# 「ベア、ト……」
line = "「ベア、ト……」"

[[dialogue]]
speaker = "ベアトリス"
# 「約束したでしょ、梨緒ちゃんが泣いてたら、私が涙を拭うって」
line = "「約束したでしょ、梨緒ちゃんが泣いてたら、私が涙を拭うって」"

[[dialogue]]
speaker = "ベアトリス"
# 「いいよ、わかったよ。今度梨緒ちゃんが泣いてるところ見かけたら、『梨緒ちゃんが泣くわけない！』って言って勝手に顔をハンカチでゴシゴシしちゃうから」
line = "「いいよ、わかったよ。今度梨緒ちゃんが泣いてるところ見かけたら、『梨緒ちゃんが泣くわけない！』って言って勝手に顔をハンカチでゴシゴシしちゃうから」"

[[dialogue]]
speaker = "梨緒"
# 「君は言ってくれたな。もし私が泣いていたら、その涙を拭ってくれると」
line = "「君は言ってくれたな。もし私が泣いていたら、その涙を拭ってくれると」"

[[dialogue]]
speaker = "梨緒"
# 「私はどうやら泣き虫のようだから……その約束を果たしてほしい」
line = "「私はどうやら泣き虫のようだから……その約束を果たしてほしい」"

[[dialogue]]
speaker = "ベアトリス"
# 「私じゃ梨緒ちゃんとジグさんのつらさや苦しみはわからないかもしれない。梨緒ちゃんの悲しみを受け止めきれないかもしれない」
line = "「私じゃ梨緒ちゃんとジグさんのつらさや苦しみはわからないかもしれない。梨緒ちゃんの悲しみを受け止めきれないかもしれない」"

[[dialogue]]
speaker = "ベアトリス"
# 「それでも私は梨緒ちゃんの傍にいるよ。仲間だもん」
line = "「それでも私は梨緒ちゃんの傍にいるよ。仲間だもん」"

[[dialogue]]
speaker = "梨緒"
# 「────」
line = "「────」"

[[dialogue]]
speaker = "梨緒"
# 「っ──うぅぅっ……ああぁっ、あっ、ああぁあああっ……！！」
line = "「っ──うぅぅっ……ああぁっ、あっ、ああぁあああっ……！！」"

[[dialogue]]
speaker = "ベアトリス"
# 「梨緒ちゃん！？　大丈夫！？」
line = "「梨緒ちゃん！？　大丈夫！？」"

[[dialogue]]
speaker = "梨緒"
# 「違う、違うんだ……私は……うぅ、あぅぅっ……ああああっ！」
line = "「違う、違うんだ……私は……うぅ、あぅぅっ……ああああっ！」"

[[dialogue]]
speaker = "unk"
# 溢れる涙を拭こうと、ベアトリスが少し強くハンカチを押し付ける。
line = "溢れる涙を拭こうと、ベアトリスが少し強くハンカチを押し付ける。"

[[dialogue]]
speaker = "unk"
# するとハンカチはあっという間にびしょびしょになってしまった。
line = "するとハンカチはあっという間にびしょびしょになってしまった。"

[[dialogue]]
speaker = "梨緒"
# （私が泣いていた時、君も傷ついていた。私に笑いかけながら、君は闇の中にいた）
line = "（私が泣いていた時、君も傷ついていた。私に笑いかけながら、君は闇の中にいた）"

[[dialogue]]
speaker = "梨緒"
# （負けず嫌いな私よりもあがいて、もがいて、苦しんでいた）
line = "（負けず嫌いな私よりもあがいて、もがいて、苦しんでいた）"

[[dialogue]]
speaker = "梨緒"
# （泣き虫な私よりも、心の中で泣いていた。涙すら枯れ果てるほどに）
line = "（泣き虫な私よりも、心の中で泣いていた。涙すら枯れ果てるほどに）"

[[dialogue]]
speaker = "梨緒"
# （仲間なら、ジグの涙を拭ってやらなければいけなかった）
line = "（仲間なら、ジグの涙を拭ってやらなければいけなかった）"

[[dialogue]]
speaker = "梨緒"
# （ジグの絶望に気付かなければいけなかったのに──）
line = "（ジグの絶望に気付かなければいけなかったのに──）"

[[dialogue]]
speaker = "梨緒"
# （だけど何もできないまま、ベガは滅びてしまった）
line = "（だけど何もできないまま、ベガは滅びてしまった）"

[[dialogue]]
speaker = "梨緒"
# （ジグはリクリエの使徒にされ、私はそれすら忘却して、平行世界に漂着した）
line = "（ジグはリクリエの使徒にされ、私はそれすら忘却して、平行世界に漂着した）"

[[dialogue]]
speaker = "梨緒"
# （今までジグの苦しみも絶望も知らずにのうのうと生きてきた）
line = "（今までジグの苦しみも絶望も知らずにのうのうと生きてきた）"

[[dialogue]]
speaker = "梨緒"
# （でも──）
line = "（でも──）"

[[dialogue]]
speaker = "梨緒"
# （私はまだ生きている）
line = "（私はまだ生きている）"

[[dialogue]]
speaker = "梨緒"
# （ジグは今、あそこにいる）
line = "（ジグは今、あそこにいる）"

[[dialogue]]
speaker = "梨緒"
# （まだ私の声は届く。私の手は届く）
line = "（まだ私の声は届く。私の手は届く）"

[[dialogue]]
speaker = "梨緒"
# （私の矢は届く。届かせる）
line = "（私の矢は届く。届かせる）"

[[dialogue]]
speaker = "梨緒"
# （まだ終わっていない……！）
line = "（まだ終わっていない……！）"

[[dialogue]]
speaker = "梨緒"
# 「……もう大丈夫だ。ありがとう、ベアト」
line = "「……もう大丈夫だ。ありがとう、ベアト」"

[[dialogue]]
speaker = "ベアトリス"
# 「梨緒ちゃん……」
line = "「梨緒ちゃん……」"

[[dialogue]]
speaker = "梨緒"
# 「私がするべきことは、やり直しを願うことじゃない」
line = "「私がするべきことは、やり直しを願うことじゃない」"

[[dialogue]]
speaker = "梨緒"
# 「あのいけ好かない仮面を叩き割って、すかした表情を歪ませて、絶望の闇から引きずり出すことだ」
line = "「あのいけ好かない仮面を叩き割って、すかした表情を歪ませて、絶望の闇から引きずり出すことだ」"

[[dialogue]]
speaker = "梨緒"
# 「ジグはきっと今も待っている──」
line = "「ジグはきっと今も待っている──」"

[[dialogue]]
speaker = "梨緒"
# 「いや、もう待っていないかもしれない。私のことなんてとっくに愛想が尽きて、顔を見るのも嫌かもしれない」
line = "「いや、もう待っていないかもしれない。私のことなんてとっくに愛想が尽きて、顔を見るのも嫌かもしれない」"

[[dialogue]]
speaker = "梨緒"
# 「それでも私は諦めない。ジグが参ったと言うまで、私の声を届け続けてやる！」
line = "「それでも私は諦めない。ジグが参ったと言うまで、私の声を届け続けてやる！」"

[[dialogue]]
speaker = "ベアトリス"
# 「あはは……言い方が梨緒ちゃんらしいね」
line = "「あはは……言い方が梨緒ちゃんらしいね」"

[[dialogue]]
speaker = "ベアトリス"
# 「でも、梨緒ちゃんらしさが戻って良かった」
line = "「でも、梨緒ちゃんらしさが戻って良かった」"

[[dialogue]]
speaker = "梨緒"
# 「すまない。迷惑をかけた、ベアト」
line = "「すまない。迷惑をかけた、ベアト」"

[[dialogue]]
speaker = "ベアトリス"
# 「ううん、迷惑じゃないよ。仲間だもん」
line = "「ううん、迷惑じゃないよ。仲間だもん」"

[[dialogue]]
speaker = "梨緒"
# 「行こう。ナターシャが待っている」
line = "「行こう。ナターシャが待っている」"

[[dialogue]]
speaker = "ベアトリス"
# 「うん！」
line = "「うん！」"
