[[dialogue]]
speaker = "unk"
# 第１話,フィーニスの塔・第二階層,B
line = "第１話,フィーニスの塔・第二階層,B"

[[dialogue]]
speaker = "unk"
# 時間は、不吉な夜が再び流星市国を覆う、数時間前に遡る──
line = "時間は、不吉な夜が再び流星市国を覆う、数時間前に遡る──"

[[dialogue]]
speaker = "ヴィーナス"
# 『誰も見てないわね？　先生とか』
line = "『誰も見てないわね？　先生とか』"

[[dialogue]]
speaker = "フィオナ"
# 『ふふ。なんだか不良になってしまったようです』
line = "『ふふ。なんだか不良になってしまったようです』"

[[dialogue]]
speaker = "クロト"
# 『共犯だな』
line = "『共犯だな』"

[[dialogue]]
speaker = "ヴィーナス"
# 『これ──塔の──っ……！？』
line = "『これ──塔の──っ……！？』"

[[dialogue]]
speaker = "フィオナ"
# 『……！　私たちが、ここに立った時点で──』
line = "『……！　私たちが、ここに立った時点で──』"

[[dialogue]]
speaker = "クロト"
# 『問答無用──ってことか……！』
line = "『問答無用──ってことか……！』"

[[dialogue]]
speaker = "クロト"
# 「いつつ……みんな、大丈夫か？」
line = "「いつつ……みんな、大丈夫か？」"

[[dialogue]]
speaker = "unk"
# 学園の敷地内で話していた俺たちだったが──
line = "学園の敷地内で話していた俺たちだったが──"

[[dialogue]]
speaker = "unk"
# 不意に白い光に包まれ、気がつけばここに転がされていた。
line = "不意に白い光に包まれ、気がつけばここに転がされていた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「んもう──なんなのよ、急に！」
line = "「んもう──なんなのよ、急に！」"

[[dialogue]]
speaker = "フィオナ"
# 「少し、覚えのある感覚でしたが……」
line = "「少し、覚えのある感覚でしたが……」"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# この場の光景に見覚えはない。
line = "この場の光景に見覚えはない。"

[[dialogue]]
speaker = "unk"
# しかし、ここの空気には覚えがある。
line = "しかし、ここの空気には覚えがある。"

[[dialogue]]
speaker = "unk"
# そして何より、足元に沈殿している紫のよどんだ瘴気……つまりここは……。
line = "そして何より、足元に沈殿している紫のよどんだ瘴気……つまりここは……。"

[[dialogue]]
speaker = "クロト"
# 「フィーニスの塔──の、中か」
line = "「フィーニスの塔──の、中か」"

[[dialogue]]
speaker = "ヴィーナス"
# 「歓迎にしちゃ、えらく手荒だったけど……」
line = "「歓迎にしちゃ、えらく手荒だったけど……」"

[[dialogue]]
speaker = "unk"
# <b>招かれた</b>。
line = "<b>招かれた</b>。"

[[dialogue]]
speaker = "unk"
# 本能的に察したこの感覚は、恐らく彼女たち２人も同様だろう。
line = "本能的に察したこの感覚は、恐らく彼女たち２人も同様だろう。"

[[dialogue]]
speaker = "フィオナ"
# 「間違いないとは思いますが──また随分と様変わりしていますね」
line = "「間違いないとは思いますが──また随分と様変わりしていますね」"

[[dialogue]]
speaker = "unk"
# ここがフィーニスの塔であることは状況からしても明らかだが……
line = "ここがフィーニスの塔であることは状況からしても明らかだが……"

[[dialogue]]
speaker = "unk"
# 内部の意匠は、俺たちが以前訪れた地とハッキリ異なる。
line = "内部の意匠は、俺たちが以前訪れた地とハッキリ異なる。"

[[dialogue]]
speaker = "unk"
# そして……かつて守護天使が言っていたことを考えるなら答えはひとつだ。
line = "そして……かつて守護天使が言っていたことを考えるなら答えはひとつだ。"

[[dialogue]]
speaker = "クロト"
# 「第二階層──ということだろうな」
line = "「第二階層──ということだろうな」"

[[dialogue]]
speaker = "フィオナ"
# 「その可能性が高いですね。ここまで変貌するとは思いませんでしたが」
line = "「その可能性が高いですね。ここまで変貌するとは思いませんでしたが」"

[[dialogue]]
speaker = "ヴィーナス"
# 「遺跡みたい……あの塔の中身がこんなのなんて、信じられないわね」
line = "「遺跡みたい……あの塔の中身がこんなのなんて、信じられないわね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ていうか、引き返す道もないわね。ま──どうせ入るつもりだったからいいけど」
line = "「ていうか、引き返す道もないわね。ま──どうせ入るつもりだったからいいけど」"

[[dialogue]]
speaker = "クロト"
# 「<ruby=ディスク>ＤＩＳＣ</ruby>もやっぱり通じない。俺たちだけで進むしかなさそうだな」
line = "「<ruby>ＤＩＳＣ<rt>ディスク</rt></ruby>もやっぱり通じない。俺たちだけで進むしかなさそうだな」"

[[dialogue]]
speaker = "フィオナ"
# 「そうですね。とはいえ、３人では心細いですし……ニャリオンを呼びましょう」
line = "「そうですね。とはいえ、３人では心細いですし……ニャリオンを呼びましょう」"

[[dialogue]]
speaker = "unk"
# 魔導書を取り出して詠唱を諳んじるフィオナ。
line = "魔導書を取り出して詠唱を諳んじるフィオナ。"

[[dialogue]]
speaker = "unk"
# が……
line = "が……"

[[dialogue]]
speaker = "フィオナ"
# 「え──あ……あれ」
line = "「え──あ……あれ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「どしたの？　ニャリオン、居留守？」
line = "「どしたの？　ニャリオン、居留守？」"

[[dialogue]]
speaker = "クロト"
# 「居留守はできないんじゃないか？」
line = "「居留守はできないんじゃないか？」"

[[dialogue]]
speaker = "フィオナ"
# 「どうやら……ニャリオン召喚の経路さえ絶たれているようです」
line = "「どうやら……ニャリオン召喚の経路さえ絶たれているようです」"

[[dialogue]]
speaker = "フィオナ"
# 「というより──私たちが、そもそもあちらと繋がっていない……と称したほうが正しいでしょうか」
line = "「というより──私たちが、そもそもあちらと繋がっていない……と称したほうが正しいでしょうか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「？　どゆこと？」
line = "「？　どゆこと？」"

[[dialogue]]
speaker = "フィオナ"
# 「私の召喚術はたとえ天界や魔界であっても座標を結び、呼び出します」
line = "「私の召喚術はたとえ天界や魔界であっても座標を結び、呼び出します」"

[[dialogue]]
speaker = "フィオナ"
# 「それが今は人間界にいるはずのニャリオンにも通じない。つまり、ここは三界のどこでもない場所」
line = "「それが今は人間界にいるはずのニャリオンにも通じない。つまり、ここは三界のどこでもない場所」"

[[dialogue]]
speaker = "クロト"
# 「そこまでの……」
line = "「そこまでの……」"

[[dialogue]]
speaker = "unk"
# 天界でも、魔界でも、そして人間界でもない世界。
line = "天界でも、魔界でも、そして人間界でもない世界。"

[[dialogue]]
speaker = "unk"
# 塔という外観に惑わされていたが、この中は完全なる異界なのだと知る。
line = "塔という外観に惑わされていたが、この中は完全なる異界なのだと知る。"

[[dialogue]]
speaker = "フィオナ"
# 「私の星術も工夫をしなくてはなりませんね。戦闘くらいであれば何とかなると思いますが」
line = "「私の星術も工夫をしなくてはなりませんね。戦闘くらいであれば何とかなると思いますが」"

[[dialogue]]
speaker = "unk"
# そうして、俺たちが足を進めようとすると……
line = "そうして、俺たちが足を進めようとすると……"

[[dialogue]]
speaker = "unk"
# 『よく来たわね……ヴィーナス……いい子……おいでなさい……こちらへ……』
line = "『よく来たわね……ヴィーナス……いい子……おいでなさい……こちらへ……』"

[[dialogue]]
speaker = "ヴィーナス"
# 「やっぱり……また……前と同じ声が聞こえる」
line = "「やっぱり……また……前と同じ声が聞こえる」"

[[dialogue]]
speaker = "クロト"
# 「今度は俺にも聞こえた。もしかしたら……」
line = "「今度は俺にも聞こえた。もしかしたら……」"

[[dialogue]]
speaker = "フィオナ"
# 「声の主に近づいている──のかもしれませんね。上へ昇るにつれて」
line = "「声の主に近づいている──のかもしれませんね。上へ昇るにつれて」"

[[dialogue]]
speaker = "unk"
# ならばこの先に行けば本体と会えるのかもしれない。
line = "ならばこの先に行けば本体と会えるのかもしれない。"

[[dialogue]]
speaker = "unk"
# 俺たちは期待と不安を抱いて、第二階層の遺跡を進んでいった。
line = "俺たちは期待と不安を抱いて、第二階層の遺跡を進んでいった。"

[[dialogue]]
speaker = "unk"
# その道中には……
line = "その道中には……"

[[dialogue]]
speaker = "ガーディアン"
# 「ポロポロ……パロパロ……ピピ、ガガガ」
line = "「ポロポロ……パロパロ……ピピ、ガガガ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「！　塔の敵──ってことは、ガーディアンね！」
line = "「！　塔の敵──ってことは、ガーディアンね！」"

[[dialogue]]
speaker = "ガーディアン"
# 「エネミー発見。エネミー発見。迎撃モードに移行シマス」
line = "「エネミー発見。エネミー発見。迎撃モードに移行シマス」"

[[dialogue]]
speaker = "フィオナ"
# 「私たちを敵視しているのは変わりないようですね」
line = "「私たちを敵視しているのは変わりないようですね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ほんと。勝手に呼んどいて侵入者扱いなんて無礼よね──ま、突破するっきゃないけど！」
line = "「ほんと。勝手に呼んどいて侵入者扱いなんて無礼よね──ま、突破するっきゃないけど！」"

[[dialogue]]
speaker = "ガーディアン"
# 「侵入者──排除──シマス。ピ──ガ──！」
line = "「侵入者──排除──シマス。ピ──ガ──！」"
