[[dialogue]]
speaker = "unk"
# 第４話,レゾフでの休息,B
line = "第４話,レゾフでの休息,B"

[[dialogue]]
speaker = "unk"
# 来た道をはるばると駆け、ようやくレゾフにまで戻ってくる俺たち。
line = "来た道をはるばると駆け、ようやくレゾフにまで戻ってくる俺たち。"

[[dialogue]]
speaker = "unk"
# 街では『スタンピード』により押し寄せた魔獣たちの死骸が、そこら中に所狭しと打ち捨てられていた。
line = "街では『スタンピード』により押し寄せた魔獣たちの死骸が、そこら中に所狭しと打ち捨てられていた。"

[[dialogue]]
speaker = "マトイ"
# 「うぇ、すご……」
line = "「うぇ、すご……」"

[[dialogue]]
speaker = "ラティエ"
# 「後片付けまでしている余裕はなかったのでな。ま、すぐに凍るから腐臭の心配はなかろう」
line = "「後片付けまでしている余裕はなかったのでな。ま、すぐに凍るから腐臭の心配はなかろう」"

[[dialogue]]
speaker = "サーシャ"
# 「よかった。街にはほとんど被害がないみたい」
line = "「よかった。街にはほとんど被害がないみたい」"

[[dialogue]]
speaker = "フィオナ"
# 「学園長は……しっかりお役目を果たしてくれていましたか？」
line = "「学園長は……しっかりお役目を果たしてくれていましたか？」"

[[dialogue]]
speaker = "ソフィア"
# 「はい。なんというか……壮絶でした」
line = "「はい。なんというか……壮絶でした」"

[[dialogue]]
speaker = "ユウリ"
# 「ああ。剣の一振りで魔獣の十体二十体は当たり前……全盛期には振らずに<ruby=せんめつ>殲滅</ruby>って感じだったな」
line = "「ああ。剣の一振りで魔獣の十体二十体は当たり前……全盛期には振らずに<ruby>殲滅<rt>せんめつ</rt></ruby>って感じだったな」"

[[dialogue]]
speaker = "ラティエ"
# 「ふふ。今後は鍛錬も兼ねて、冬にはここを訪れることとしようか」
line = "「ふふ。今後は鍛錬も兼ねて、冬にはここを訪れることとしようか」"

[[dialogue]]
speaker = "unk"
# 『大いなる冬』もいくらか落ち着いてきたようで、俺たちが街を出たころより吹雪はずっとおとなしくなっていた。
line = "『大いなる冬』もいくらか落ち着いてきたようで、俺たちが街を出たころより吹雪はずっとおとなしくなっていた。"

[[dialogue]]
speaker = "unk"
# と、そこへ──
line = "と、そこへ──"

[[dialogue]]
speaker = "トリシャ"
# 「おお……迷える仔羊たち！」
line = "「おお……迷える仔羊たち！」"

[[dialogue]]
speaker = "クロト"
# 「──トリシャさん」
line = "「──トリシャさん」"

[[dialogue]]
speaker = "unk"
# 近くの小屋からローブ姿で出てきたのは、占星術師のトリシャさんだった。
line = "近くの小屋からローブ姿で出てきたのは、占星術師のトリシャさんだった。"

[[dialogue]]
speaker = "トリシャ"
# 「ひい、ふう、みい……全員無事。見知らぬ方も。ほっ……作戦はうまくいったようですね。いえ、これも星の導き通り」
line = "「ひい、ふう、みい……全員無事。見知らぬ方も。ほっ……作戦はうまくいったようですね。いえ、これも星の導き通り」"

[[dialogue]]
speaker = "ヴィーナス"
# 「みんなの新しい友だち？　私ヴィーナス、よろしくね！」
line = "「みんなの新しい友だち？　私ヴィーナス、よろしくね！」"

[[dialogue]]
speaker = "トリシャ"
# 「よ、よ、よろしく。へ、へへ……また友だちが増えました」
line = "「よ、よ、よろしく。へ、へへ……また友だちが増えました」"

[[dialogue]]
speaker = "クロト"
# 「おかげでみんな無事で済んだよ。ありがとう」
line = "「おかげでみんな無事で済んだよ。ありがとう」"

[[dialogue]]
speaker = "unk"
# 俺たちは、トリシャさんの示した『森』ですべての決着をつけてきたことを話した。
line = "俺たちは、トリシャさんの示した『森』ですべての決着をつけてきたことを話した。"

[[dialogue]]
speaker = "トリシャ"
# 「なるほど……想像以上の死闘であった様子。血で血を洗うほどの……」
line = "「なるほど……想像以上の死闘であった様子。血で血を洗うほどの……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「すごい。そんなことまでわかっちゃうのね！」
line = "「すごい。そんなことまでわかっちゃうのね！」"

[[dialogue]]
speaker = "トリシャ"
# 「いえ、単にあなた方がものすごい傷だらけなので」
line = "「いえ、単にあなた方がものすごい傷だらけなので」"

[[dialogue]]
speaker = "ニャリオン"
# 「そりゃそうだニャ」
line = "「そりゃそうだニャ」"

[[dialogue]]
speaker = "トリシャ"
# 「こちらはようやく吹雪も静まりつつあり……こうして、ようやく表に出られるくらいには落ち着いてきました」
line = "「こちらはようやく吹雪も静まりつつあり……こうして、ようやく表に出られるくらいには落ち着いてきました」"

[[dialogue]]
speaker = "トリシャ"
# 「スタンピードの猛攻は凄まじかったですが──主にそちらの方のおかげで被害もなく」
line = "「スタンピードの猛攻は凄まじかったですが──主にそちらの方のおかげで被害もなく」"

[[dialogue]]
speaker = "ラティエ"
# 「フ。トリシャ殿も助力していただろうに、謙遜することはない」
line = "「フ。トリシャ殿も助力していただろうに、謙遜することはない」"

[[dialogue]]
speaker = "トリシャ"
# 「ふへへ」
line = "「ふへへ」"

[[dialogue]]
speaker = "ソフィア"
# 「ありがとうございます。町を……レゾフを守ってくれて」
line = "「ありがとうございます。町を……レゾフを守ってくれて」"

[[dialogue]]
speaker = "unk"
# 一件落着──といったところか。
line = "一件落着──といったところか。"

[[dialogue]]
speaker = "unk"
# すっかり陽も暮れたレゾフの町には、徐々にランプの明かりが灯り始める。
line = "すっかり陽も暮れたレゾフの町には、徐々にランプの明かりが灯り始める。"

[[dialogue]]
speaker = "サーシャ"
# 「それじゃあ……みんな疲れたでしょうし、一旦はうちでお休みかしら」
line = "「それじゃあ……みんな疲れたでしょうし、一旦はうちでお休みかしら」"

[[dialogue]]
speaker = "マトイ"
# 「さ、賛成っ！　もう色んなことありすぎて疲れたよ～！」
line = "「さ、賛成っ！　もう色んなことありすぎて疲れたよ～！」"

[[dialogue]]
speaker = "クロト"
# 「人間界に残したみんなには、一刻も早く連絡したいところだけど……」
line = "「人間界に残したみんなには、一刻も早く連絡したいところだけど……」"

[[dialogue]]
speaker = "ラティエ"
# 「なに、急がば回れだ。戦士には休息も必要というものだよ」
line = "「なに、急がば回れだ。戦士には休息も必要というものだよ」"

[[dialogue]]
speaker = "フィオナ"
# 「確かに……今日、これ以上の行動は厳しいですね」
line = "「確かに……今日、これ以上の行動は厳しいですね」"

[[dialogue]]
speaker = "unk"
# 捕縛されていたヴィーナスは元より、戦い漬けの俺たちも消耗は激しい。
line = "捕縛されていたヴィーナスは元より、戦い漬けの俺たちも消耗は激しい。"

[[dialogue]]
speaker = "unk"
# 寒波が落ち着いている今のうちに休んでおくべきかもしれない。
line = "寒波が落ち着いている今のうちに休んでおくべきかもしれない。"

[[dialogue]]
speaker = "ヴィーナス"
# 「サーシャさんのお家に遊びに行く日が来るなんて思わなかったわ！　楽しみね！」
line = "「サーシャさんのお家に遊びに行く日が来るなんて思わなかったわ！　楽しみね！」"

[[dialogue]]
speaker = "ユウリ"
# 「そういや、ヴィーナスはレゾフも初めてか」
line = "「そういや、ヴィーナスはレゾフも初めてか」"

[[dialogue]]
speaker = "サーシャ"
# 「ヴィーナスちゃんには特製のシチューを振る舞ってあげるわ。隠し味にコオリンゴが入ったやつよ」
line = "「ヴィーナスちゃんには特製のシチューを振る舞ってあげるわ。隠し味にコオリンゴが入ったやつよ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それって、いつかレゾフ名物って言ってたやつよね！？　あー楽しみー私が一番乗りーっと♪」
line = "「それって、いつかレゾフ名物って言ってたやつよね！？　あー楽しみー私が一番乗りーっと♪」"

[[dialogue]]
speaker = "サーシャ"
# 「ああっ、違うわヴィーナスちゃんそっちじゃなくて……もう」
line = "「ああっ、違うわヴィーナスちゃんそっちじゃなくて……もう」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ……まだまだ気力が有り余っているようですね」
line = "「ふふ……まだまだ気力が有り余っているようですね」"

[[dialogue]]
speaker = "クロト"
# 「底なしだな、もう」
line = "「底なしだな、もう」"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャッニャッニャッ。九浄の娘はああでないとニャン！」
line = "「ニャッニャッニャッ。九浄の娘はああでないとニャン！」"

[[dialogue]]
speaker = "unk"
# 久方ぶりの賑わいがなんだか懐かしく思えて……
line = "久方ぶりの賑わいがなんだか懐かしく思えて……"

[[dialogue]]
speaker = "unk"
# 俺はその晩ずっと、戻ってきた喧騒のありがたみを噛みしめるのだった。
line = "俺はその晩ずっと、戻ってきた喧騒のありがたみを噛みしめるのだった。"
