[[dialogue]]
speaker = "unk"
# 第６話,『間違いだらけの教本』,B
line = "第６話,『間違いだらけの教本』,B"

[[dialogue]]
speaker = "unk"
# 昼休みになり、揃って大聖堂併設のカフェテリアへと向かう。
line = "昼休みになり、揃って大聖堂併設のカフェテリアへと向かう。"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「ここに来るのは初めてではないのに、何故か新鮮な気持ちになってしまうな」
line = "「ここに来るのは初めてではないのに、何故か新鮮な気持ちになってしまうな」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ふふっ、わかります。私も同じような気持ちになりましたから」
line = "「ふふっ、わかります。私も同じような気持ちになりましたから」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「昼時だからか、お客の数が多いな。席は空いているだろうか？」
line = "「昼時だからか、お客の数が多いな。席は空いているだろうか？」"

[[dialogue]]
speaker = "ナミエル"
# 「あちらの席が空いていますね。ちょうど４人座れそうです」
line = "「あちらの席が空いていますね。ちょうど４人座れそうです」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「ではあの席にしよう」
line = "「ではあの席にしよう」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「よーし、さっそく注文なのだ！　肉！　肉を持ってくるのだ！」
line = "「よーし、さっそく注文なのだ！　肉！　肉を持ってくるのだ！」"

[[dialogue]]
speaker = "ナミエル"
# 「落ち着いてください、アルモたん。ヒメさんは慣れていないのだから、ゆっくり選ばせてあげましょう」
line = "「落ち着いてください、アルモたん。ヒメさんは慣れていないのだから、ゆっくり選ばせてあげましょう」"

[[dialogue]]
speaker = "ナミエル"
# 「ヒメさん、こちらがメニューになります」
line = "「ヒメさん、こちらがメニューになります」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「そうか、ありがとう」
line = "「そうか、ありがとう」"

[[dialogue]]
speaker = "ナミエル"
# 「この時間はランチメニューをやっているのですが、ヒメさんはご存知ですか？」
line = "「この時間はランチメニューをやっているのですが、ヒメさんはご存知ですか？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「いや、知らなかった」
line = "「いや、知らなかった」"

[[dialogue]]
speaker = "ナミエル"
# 「ランチメニューはこれですね。今日は２種から選べるようですが、ヒメさんは肉と魚、どちらがお好きですか？」
line = "「ランチメニューはこれですね。今日は２種から選べるようですが、ヒメさんは肉と魚、どちらがお好きですか？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「ん……どちらかというと魚の方が好きだな」
line = "「ん……どちらかというと魚の方が好きだな」"

[[dialogue]]
speaker = "ナミエル"
# 「であれば、魚のフライ……こちらの定食の方が良いでしょうか？　私もこちらにしようと思っていますが」
line = "「であれば、魚のフライ……こちらの定食の方が良いでしょうか？　私もこちらにしようと思っていますが」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「そうか。であれば私も同じものにしよう」
line = "「そうか。であれば私も同じものにしよう」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「あらあら、ふふっ♪」
line = "「あらあら、ふふっ♪」"

[[dialogue]]
speaker = "ナミエル"
# 「なんでしょうか……？」
line = "「なんでしょうか……？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ナミエル、オオヒメに親切なのだ」
line = "「ナミエル、オオヒメに親切なのだ」"

[[dialogue]]
speaker = "ナミエル"
# 「転入生に親切にするのは別段おかしなことではないと思いますが？」
line = "「転入生に親切にするのは別段おかしなことではないと思いますが？」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「とても良いことだと思いますよ～。私の大切な仲間に親切にしていただいてありがとうございます」
line = "「とても良いことだと思いますよ～。私の大切な仲間に親切にしていただいてありがとうございます」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「よければこれからもずっと仲良くしてあげてください～、私たちともども♪」
line = "「よければこれからもずっと仲良くしてあげてください～、私たちともども♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「なあ、もう注文してもいいのだ？　アルモたんはお腹ペコペコだぞ！」
line = "「なあ、もう注文してもいいのだ？　アルモたんはお腹ペコペコだぞ！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「はいはい」
line = "「はいはい」"

[[dialogue]]
speaker = "unk"
# 店員さんを呼び、各々が注文を済ませる。
line = "店員さんを呼び、各々が注文を済ませる。"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ところでオオヒメ。これで午前の授業が終わったわけですがどうですか、初めての学園生活は？」
line = "「ところでオオヒメ。これで午前の授業が終わったわけですがどうですか、初めての学園生活は？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「そうだな……順調、と言ってよいのではないだろうか？」
line = "「そうだな……順調、と言ってよいのではないだろうか？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「最初、少しだけ失敗してしまったが、その後は上手く軌道修正できたように思う。やはり事前に勉強しておいたのが良かったのだろうな」
line = "「最初、少しだけ失敗してしまったが、その後は上手く軌道修正できたように思う。やはり事前に勉強しておいたのが良かったのだろうな」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「勉強、ですか？」
line = "「勉強、ですか？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「オオヒメ、そんなことしてたのだ？」
line = "「オオヒメ、そんなことしてたのだ？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「うむ、学園生活を円滑に送るために参考になりそうなものを一通りな」
line = "「うむ、学園生活を円滑に送るために参考になりそうなものを一通りな」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「生真面目すぎて呆れちゃうのだ！」
line = "「生真面目すぎて呆れちゃうのだ！」"

[[dialogue]]
speaker = "ナミエル"
# 「ちなみにどんなことを調べたのですか？」
line = "「ちなみにどんなことを調べたのですか？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「そうだな──王道学園ものから、ファンタジー学園もの。異世界転生ものや悪徳令嬢もの、タイムリープものに田舎の学校ぐらし、それから……」
line = "「そうだな──王道学園ものから、ファンタジー学園もの。異世界転生ものや悪徳令嬢もの、タイムリープものに田舎の学校ぐらし、それから……」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ちょっと待ってください！　あなたは一体何を調べているのですか？」
line = "「ちょっと待ってください！　あなたは一体何を調べているのですか？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「ん？　だから学園生活のセオリーというものを、様々な文献から読み漁ったのだ。おかげで命拾いした場面が何度かあったぞ」
line = "「ん？　だから学園生活のセオリーというものを、様々な文献から読み漁ったのだ。おかげで命拾いした場面が何度かあったぞ」"

[[dialogue]]
speaker = "ナミエル"
# 「ヒメさん……それは……」
line = "「ヒメさん……それは……」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「オオヒメの様子が少し変だとは思っていましたが、そういう事だったのですね……」
line = "「オオヒメの様子が少し変だとは思っていましたが、そういう事だったのですね……」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「な、何だ？　私はまた、何か間違えてしまったのか？」
line = "「な、何だ？　私はまた、何か間違えてしまったのか？」"

[[dialogue]]
speaker = "ナミエル"
# 「ヒメさんが目を通されたそれらは、おそらくあまり参考にしない方がよいものだと思われますので、一旦忘れてください」
line = "「ヒメさんが目を通されたそれらは、おそらくあまり参考にしない方がよいものだと思われますので、一旦忘れてください」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「なん、だと……！！」
line = "「なん、だと……！！」"

[[dialogue]]
speaker = "ナミエル"
# 「ふふっ、ヒメさんは、天然なのですね。そうではないかと思ってはいましたが、今の話を聞いて確信しました」
line = "「ふふっ、ヒメさんは、天然なのですね。そうではないかと思ってはいましたが、今の話を聞いて確信しました」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「そうなのだ。その癖、自分ではしっかり者で、守護天使のまとめ役だと思っているから手に負えないのだ」
line = "「そうなのだ。その癖、自分ではしっかり者で、守護天使のまとめ役だと思っているから手に負えないのだ」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「て、手に負えない……私はそんな風に思われていたのか……」
line = "「て、手に負えない……私はそんな風に思われていたのか……」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「そんなに落ち込まないでください。天然というところは否定できませんけど、しっかり者で私たちのまとめ役であることは間違いありませんから」
line = "「そんなに落ち込まないでください。天然というところは否定できませんけど、しっかり者で私たちのまとめ役であることは間違いありませんから」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「うぅぅ……どこか閉じこもれるところはないか？　今すぐ引きこもりたいのだが……」
line = "「うぅぅ……どこか閉じこもれるところはないか？　今すぐ引きこもりたいのだが……」"

[[dialogue]]
speaker = "ナミエル"
# 「元気を出してください。ヒメさんの真面目なところは好感が持てますし、天然なところも親しみやすくて可愛いと思います」
line = "「元気を出してください。ヒメさんの真面目なところは好感が持てますし、天然なところも親しみやすくて可愛いと思います」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「か、可愛い……」
line = "「か、可愛い……」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「そうだろうか？　ナミエル殿にそう言ってもらえるなら……天然も悪くない気がしてきたな……」
line = "「そうだろうか？　ナミエル殿にそう言ってもらえるなら……天然も悪くない気がしてきたな……」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「しかし……私の読んだあれらを参考にしない方が良いとなると、今後どうすればよいのか分からなくなってしまったな」
line = "「しかし……私の読んだあれらを参考にしない方が良いとなると、今後どうすればよいのか分からなくなってしまったな」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「うーん……そうだ、いい事を思いついたのだ！」
line = "「うーん……そうだ、いい事を思いついたのだ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「授業が終わったらみんなで遊びに行くのだ！　オオヒメの歓迎会を開いて、今よりもっと打ち解けるのだ！」
line = "「授業が終わったらみんなで遊びに行くのだ！　オオヒメの歓迎会を開いて、今よりもっと打ち解けるのだ！」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「何だそれは、アルモタヘルが遊びたいだけではないか」
line = "「何だそれは、アルモタヘルが遊びたいだけではないか」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「そんなことないのだ！　みんなで遊ぶことも、大事な体験なのだ！」
line = "「そんなことないのだ！　みんなで遊ぶことも、大事な体験なのだ！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「アルモタヘルの言う通りかもしれませんね～」
line = "「アルモタヘルの言う通りかもしれませんね～」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「マニュアル通りに動いていても、本質を掴むことは出来ません。自然体で日常を楽しむことこそオオヒメに必要なことかもしれませんよ」
line = "「マニュアル通りに動いていても、本質を掴むことは出来ません。自然体で日常を楽しむことこそオオヒメに必要なことかもしれませんよ」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「むぅ……そうだな。２人の言うことも、一理ある……」
line = "「むぅ……そうだな。２人の言うことも、一理ある……」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「決まりなのだ！　放課後はみんなで思いっきり楽しむのだ♪」
line = "「決まりなのだ！　放課後はみんなで思いっきり楽しむのだ♪」"
