[[dialogue]]
speaker = "unk"
# 第５話,さすらいの旅人,B
line = "第５話,さすらいの旅人,B"

[[dialogue]]
speaker = "クロト"
# 「……ふぅ」
line = "「……ふぅ」"

[[dialogue]]
speaker = "unk"
# 荒鷹ノ月十七日・午前５時３０分──
line = "荒鷹ノ月十七日・午前５時３０分──"

[[dialogue]]
speaker = "unk"
# 仮眠を終えて外へ出ると、凍てつくような寒さが肌を刺した。
line = "仮眠を終えて外へ出ると、凍てつくような寒さが肌を刺した。"

[[dialogue]]
speaker = "クロト"
# （とてつもない気候だな。明らかに、人間の住める環境を超えてる）
line = "（とてつもない気候だな。明らかに、人間の住める環境を超えてる）"

[[dialogue]]
speaker = "unk"
# 魔族の人たちは──もしくレゾフの人たちはどうも普通の人間より寒さに強いようだ。
line = "魔族の人たちは──もしくレゾフの人たちはどうも普通の人間より寒さに強いようだ。"

[[dialogue]]
speaker = "unk"
# 観察も兼ねて朝の街を歩いていると……
line = "観察も兼ねて朝の街を歩いていると……"

[[dialogue]]
speaker = "リタおばさん"
# 「おはよう。何か困ったことがあったら言うんだよ、事情は詮索しないけどねえ」
line = "「おはよう。何か困ったことがあったら言うんだよ、事情は詮索しないけどねえ」"

[[dialogue]]
speaker = "クロト"
# 「あ……昨日の。おはようございます」
line = "「あ……昨日の。おはようございます」"

[[dialogue]]
speaker = "リタおばさん"
# 「なあに。レゾフはめっぽう寒い土地だが──住んどる人の心だきゃ温かいからねえ」
line = "「なあに。レゾフはめっぽう寒い土地だが──住んどる人の心だきゃ温かいからねえ」"

[[dialogue]]
speaker = "リタおばさん"
# 「ま……こんな時期なのは災難だろうけども。サーシャ達がついてるんなら安心だよ。じゃあね」
line = "「ま……こんな時期なのは災難だろうけども。サーシャ達がついてるんなら安心だよ。じゃあね」"

[[dialogue]]
speaker = "クロト"
# （こんな時期……？）
line = "（こんな時期……？）"

[[dialogue]]
speaker = "unk"
# 羊のような巻き角を生やしたリタおばさんを見送る。
line = "羊のような巻き角を生やしたリタおばさんを見送る。"

[[dialogue]]
speaker = "unk"
# 他に行き交う人々も、ほぼ全員が魔族だった。それが魔界にとっては当然なのだが、俺からすると新鮮に映る。
line = "他に行き交う人々も、ほぼ全員が魔族だった。それが魔界にとっては当然なのだが、俺からすると新鮮に映る。"

[[dialogue]]
speaker = "クロト"
# （サーシャ先輩の生まれ故郷……ヴィーナスがいたらどんな反応をするかな）
line = "（サーシャ先輩の生まれ故郷……ヴィーナスがいたらどんな反応をするかな）"

[[dialogue]]
speaker = "unk"
# 彼女を無事に取り返したら、一緒にここへ立ち寄ってみたい。そう思った。
line = "彼女を無事に取り返したら、一緒にここへ立ち寄ってみたい。そう思った。"

[[dialogue]]
speaker = "クロト"
# （……さて。そのためにも、あいつを見つけてやらないとな）
line = "（……さて。そのためにも、あいつを見つけてやらないとな）"

[[dialogue]]
speaker = "unk"
# 星力探知アンテナ──
line = "星力探知アンテナ──"

[[dialogue]]
speaker = "unk"
# アニマ先輩から預かったアイテムを使い、『金星』の星力をサーチする。
line = "アニマ先輩から預かったアイテムを使い、『金星』の星力をサーチする。"

[[dialogue]]
speaker = "unk"
# しかしながら魔界へ降り立った時から変わらず、ヴィーナスの力の痕跡は見つけられなかった。
line = "しかしながら魔界へ降り立った時から変わらず、ヴィーナスの力の痕跡は見つけられなかった。"

[[dialogue]]
speaker = "クロト"
# （魔界にいるのは確か──なのに場所は探れない。どこかに幽閉されているのか……？）
line = "（魔界にいるのは確か──なのに場所は探れない。どこかに幽閉されているのか……？）"

[[dialogue]]
speaker = "unk"
# 嫌な想像が頭の中を駆け巡る。
line = "嫌な想像が頭の中を駆け巡る。"

[[dialogue]]
speaker = "unk"
# 俺は、改めて昨日ヴィーナスから送られてきたメッセージを見た。
line = "俺は、改めて昨日ヴィーナスから送られてきたメッセージを見た。"

[[dialogue]]
speaker = "クロト"
# （『冬』……『森』……『来て』……この３通。一体どういう意味があるのか）
line = "（『冬』……『森』……『来て』……この３通。一体どういう意味があるのか）"

[[dialogue]]
speaker = "unk"
# それぞれ時機と、場所と、行動を示しているのはハッキリしている。
line = "それぞれ時機と、場所と、行動を示しているのはハッキリしている。"

[[dialogue]]
speaker = "unk"
# 森に置き去りにされたヴィーナスの様子がそれとなく浮かんだ。
line = "森に置き去りにされたヴィーナスの様子がそれとなく浮かんだ。"

[[dialogue]]
speaker = "クロト"
# （にしても……『冬』？　今は荒鷹ノ月だ、レゾフはたまたま寒いけど、人間界に照らして言えば冬じゃあない）
line = "（にしても……『冬』？　今は荒鷹ノ月だ、レゾフはたまたま寒いけど、人間界に照らして言えば冬じゃあない）"

[[dialogue]]
speaker = "unk"
# それに、時機を指定するにしたって季節じゃ大ざっぱすぎる。
line = "それに、時機を指定するにしたって季節じゃ大ざっぱすぎる。"

[[dialogue]]
speaker = "unk"
# あれほど『日誌』にこだわっていた彼女なら、より詳細な日時を伝えたかったはずだ。
line = "あれほど『日誌』にこだわっていた彼女なら、より詳細な日時を伝えたかったはずだ。"

[[dialogue]]
speaker = "クロト"
# （……わからないな。まだ手がかりが足りない）
line = "（……わからないな。まだ手がかりが足りない）"

[[dialogue]]
speaker = "unk"
# 焦燥がにわかに募り始める。
line = "焦燥がにわかに募り始める。"

[[dialogue]]
speaker = "unk"
# だが、それを表に出すわけにはいかない。
line = "だが、それを表に出すわけにはいかない。"

[[dialogue]]
speaker = "クロト"
# （俺はみんなを率いる星徒会長なんだ。みっともなく焦ってたんじゃ、ヴィーナスにだってたどり着けない）
line = "（俺はみんなを率いる星徒会長なんだ。みっともなく焦ってたんじゃ、ヴィーナスにだってたどり着けない）"

[[dialogue]]
speaker = "unk"
# こんな時は、日課の鍛錬をして心を落ち着かせよう。
line = "こんな時は、日課の鍛錬をして心を落ち着かせよう。"

[[dialogue]]
speaker = "クロト"
# （ユウリじゃないけど──体を鈍らせるわけにもいかないしな。どこか拳を振るえる場所はないか……？）
line = "（ユウリじゃないけど──体を鈍らせるわけにもいかないしな。どこか拳を振るえる場所はないか……？）"

[[dialogue]]
speaker = "unk"
# 普段なら学園のトレーニング施設を使わせてもらってたものだけど……ここじゃそうもいかない。
line = "普段なら学園のトレーニング施設を使わせてもらってたものだけど……ここじゃそうもいかない。"

[[dialogue]]
speaker = "unk"
# 俺は土地勘のない中を、きょろきょろと見回しながらほっつき歩く……
line = "俺は土地勘のない中を、きょろきょろと見回しながらほっつき歩く……"

[[dialogue]]
speaker = "unk"
# ──と、そこへ。
line = "──と、そこへ。"

[[dialogue]]
speaker = "？？？"
# 「──やあ、青年」
line = "「──やあ、青年」"

[[dialogue]]
speaker = "クロト"
# 「！　おはようございます」
line = "「！　おはようございます」"

[[dialogue]]
speaker = "？？？"
# 「おはよう。何をしているのかな？」
line = "「おはよう。何をしているのかな？」"

[[dialogue]]
speaker = "クロト"
# 「朝の鍛錬を──ああ、いえ。俺はレイル区のシードルさん宅でお世話になっている緋宮クロトという人間です」
line = "「朝の鍛錬を──ああ、いえ。俺はレイル区のシードルさん宅でお世話になっている緋宮クロトという人間です」"

[[dialogue]]
speaker = "unk"
# 俺はまず怪しまれないよう素性を名乗った。
line = "俺はまず怪しまれないよう素性を名乗った。"

[[dialogue]]
speaker = "unk"
# レイル区のシードルさんというのは──サーシャ先輩たちのお父さんのことだ。
line = "レイル区のシードルさんというのは──サーシャ先輩たちのお父さんのことだ。"

[[dialogue]]
speaker = "unk"
# レゾフを含むズヴィエダ地方には本来名字という概念がないらしく、こう言わないとどの家だか通じないらしい。
line = "レゾフを含むズヴィエダ地方には本来名字という概念がないらしく、こう言わないとどの家だか通じないらしい。"

[[dialogue]]
speaker = "unk"
# ちなみに『奏』というのは、サーシャ先輩が人間界で生活していくために自ら決めた名字とのことだった。
line = "ちなみに『奏』というのは、サーシャ先輩が人間界で生活していくために自ら決めた名字とのことだった。"

[[dialogue]]
speaker = "？？？"
# 「はっはっはっ──道理でそんな薄着なわけだ。レゾフは初めてのようだな」
line = "「はっはっはっ──道理でそんな薄着なわけだ。レゾフは初めてのようだな」"

[[dialogue]]
speaker = "クロト"
# 「昨日着いたばかりで。つかぬことをおうかがいしますが、あなたは……？」
line = "「昨日着いたばかりで。つかぬことをおうかがいしますが、あなたは……？」"

[[dialogue]]
speaker = "？？？"
# 「私か。私は──ふむ。そうだな……さすらいの旅人、とでも名乗っておこうか」
line = "「私か。私は──ふむ。そうだな……さすらいの旅人、とでも名乗っておこうか」"

[[dialogue]]
speaker = "クロト"
# 「さすらいの──はあ……」
line = "「さすらいの──はあ……」"

[[dialogue]]
speaker = "unk"
# 警戒されているのかと思ったが──
line = "警戒されているのかと思ったが──"

[[dialogue]]
speaker = "unk"
# どうやら彼女も地元民ではなく、レゾフを訪れた旅人だという。
line = "どうやら彼女も地元民ではなく、レゾフを訪れた旅人だという。"

[[dialogue]]
speaker = "unk"
# レゾフの人たちが揃って装備している耳あてや毛皮の帽子もつけていない。
line = "レゾフの人たちが揃って装備している耳あてや毛皮の帽子もつけていない。"

[[dialogue]]
speaker = "？？？"
# 「私は各地を巡って困りごとを解決するのを生業としていてね。君も、何か手助けが必要になったら言うといい」
line = "「私は各地を巡って困りごとを解決するのを生業としていてね。君も、何か手助けが必要になったら言うといい」"

[[dialogue]]
speaker = "？？？"
# 「もうじき、大いなる冬も訪れる──ここは嵐の渦中になるだろうからね」
line = "「もうじき、大いなる冬も訪れる──ここは嵐の渦中になるだろうからね」"

[[dialogue]]
speaker = "クロト"
# 「は、はあ……覚えておきます」
line = "「は、はあ……覚えておきます」"

[[dialogue]]
speaker = "unk"
# なんだか呑まれそうになる雰囲気のお人だった。
line = "なんだか呑まれそうになる雰囲気のお人だった。"

[[dialogue]]
speaker = "レゾフの住人"
# 「お～い！　旅人さんよ──正門にも防風網を張りたいんだが、手伝ってくれねえかー！？」
line = "「お～い！　旅人さんよ──正門にも防風網を張りたいんだが、手伝ってくれねえかー！？」"

[[dialogue]]
speaker = "？？？"
# 「おっと──今日もどこかで私を呼ぶ声がする。ではな、青年」
line = "「おっと──今日もどこかで私を呼ぶ声がする。ではな、青年」"

[[dialogue]]
speaker = "クロト"
# 「はい。俺の仲間も何人かレゾフに滞在しているので、お見知りおきを」
line = "「はい。俺の仲間も何人かレゾフに滞在しているので、お見知りおきを」"

[[dialogue]]
speaker = "？？？"
# 「フフ。心得た」
line = "「フフ。心得た」"

[[dialogue]]
speaker = "unk"
# そうして、彼女は背を向ける──寸前。
line = "そうして、彼女は背を向ける──寸前。"

[[dialogue]]
speaker = "？？？"
# 「──ああそうだ。鍛錬なら……南口に数匹の魔獣が湧いているから、手頃な相手になるだろう」
line = "「──ああそうだ。鍛錬なら……南口に数匹の魔獣が湧いているから、手頃な相手になるだろう」"

[[dialogue]]
speaker = "クロト"
# 「……！　当たってみます」
line = "「……！　当たってみます」"

[[dialogue]]
speaker = "unk"
# そう言い残して──『さすらい』さんは去っていった。
line = "そう言い残して──『さすらい』さんは去っていった。"

[[dialogue]]
speaker = "クロト"
# （旅人か……確かに今の人には、角がなかったな）
line = "（旅人か……確かに今の人には、角がなかったな）"

[[dialogue]]
speaker = "unk"
# 俺と同じ人間だろうか。
line = "俺と同じ人間だろうか。"

[[dialogue]]
speaker = "unk"
# 昨日、リタおばさんが語っていた人物かもしれない。
line = "昨日、リタおばさんが語っていた人物かもしれない。"

[[dialogue]]
speaker = "クロト"
# （南口か……行ってみる価値はあるな）
line = "（南口か……行ってみる価値はあるな）"

[[dialogue]]
speaker = "unk"
# ──南口からレゾフを出た俺。そこには……
line = "──南口からレゾフを出た俺。そこには……"

[[dialogue]]
speaker = "鹿の魔獣"
# 「オォーン！　オォッ、オォーン！！」
line = "「オォーン！　オォッ、オォーン！！」"

[[dialogue]]
speaker = "クロト"
# 「おっと……本当にお出ましか」
line = "「おっと……本当にお出ましか」"

[[dialogue]]
speaker = "unk"
# ゾウほどもある鹿の魔獣が数頭の群れをなしていた。
line = "ゾウほどもある鹿の魔獣が数頭の群れをなしていた。"

[[dialogue]]
speaker = "クロト"
# 「こいつは……かなり歯ごたえのありそうな魔獣だな」
line = "「こいつは……かなり歯ごたえのありそうな魔獣だな」"

[[dialogue]]
speaker = "unk"
# トレーニング施設のモンスターレベルに換算すればＡ──いやＳランクは固いか。
line = "トレーニング施設のモンスターレベルに換算すればＡ──いやＳランクは固いか。"

[[dialogue]]
speaker = "unk"
# 今の俺なら程よく打ちのめせる相手で、確かに朝の鍛錬としてはちょうどいい。
line = "今の俺なら程よく打ちのめせる相手で、確かに朝の鍛錬としてはちょうどいい。"

[[dialogue]]
speaker = "クロト"
# （って──待て。どうしてあの人……俺がそこまで戦えるってわかったんだ？）
line = "（って──待て。どうしてあの人……俺がそこまで戦えるってわかったんだ？）"

[[dialogue]]
speaker = "鹿の魔獣"
# 「オォォン……！　オォォォォン……！！」
line = "「オォォン……！　オォォォォン……！！」"

[[dialogue]]
speaker = "unk"
# この魔獣はどう見たって──一頭でも一般人の手に負える相手じゃない。手頃だなんてもってのほかだ。
line = "この魔獣はどう見たって──一頭でも一般人の手に負える相手じゃない。手頃だなんてもってのほかだ。"

[[dialogue]]
speaker = "unk"
# じゃあさっきのやり取りだけで、俺は実力を見抜かれていたっていうのか……？
line = "じゃあさっきのやり取りだけで、俺は実力を見抜かれていたっていうのか……？"

[[dialogue]]
speaker = "クロト"
# 「まあいいか──望んでた通りの相手には違いない。いくぞっ！」
line = "「まあいいか──望んでた通りの相手には違いない。いくぞっ！」"

[[dialogue]]
speaker = "鹿の魔獣"
# 「オオオォォォォ────ン！」
line = "「オオオォォォォ────ン！」"
