[[dialogue]]
speaker = "unk"
# 第１１話,ジャスティス・ウィザード,B
line = "第１１話,ジャスティス・ウィザード,B"

[[dialogue]]
speaker = "デネブ市民"
# 「どうしてこの裏切り者と……ルヴィネ様が！？」
line = "「どうしてこの裏切り者と……ルヴィネ様が！？」"

[[dialogue]]
speaker = "デネブ市民"
# 「間違いない、緋宮クロトだ！！　何をしに来た──この裏切り者め！！」
line = "「間違いない、緋宮クロトだ！！　何をしに来た──この裏切り者め！！」"

[[dialogue]]
speaker = "ベアトリス"
# 「ど、どうしようルヴィ……！？」
line = "「ど、どうしようルヴィ……！？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……私のせいだわ。誤解を解いている暇はない、せめて魔王を他の場所に──」
line = "「……私のせいだわ。誤解を解いている暇はない、せめて魔王を他の場所に──」"

[[dialogue]]
speaker = "レティシア"
# 「デネブのみんな──落ち着いて！」
line = "「デネブのみんな──落ち着いて！」"

[[dialogue]]
speaker = "unk"
# 混乱が広がりかけていた市民に向けて声を張り上げたのは──<b>あの</b>レティシアだった。
line = "混乱が広がりかけていた市民に向けて声を張り上げたのは──<b>あの</b>レティシアだった。"

[[dialogue]]
speaker = "デネブ市民"
# 「レ、レティシアさんっ！？　でも……！」
line = "「レ、レティシアさんっ！？　でも……！」"

[[dialogue]]
speaker = "レティシア"
# 「気持ちは理解できる。でも、どうか私の話を聞いてちょうだい！」
line = "「気持ちは理解できる。でも、どうか私の話を聞いてちょうだい！」"

[[dialogue]]
speaker = "レティシア"
# 「時間がないから端的に伝えるわ。この人は確かに緋宮クロト。だけど私たちの味方よ。敵ではないわ！」
line = "「時間がないから端的に伝えるわ。この人は確かに緋宮クロト。だけど私たちの味方よ。敵ではないわ！」"

[[dialogue]]
speaker = "デネブ市民"
# 「な──！？」
line = "「な──！？」"

[[dialogue]]
speaker = "レティシア"
# 「みんなも感じているでしょう。今の流星市国は、１０年前ととても似ている！　世界の終末が迫っていると！」
line = "「みんなも感じているでしょう。今の流星市国は、１０年前ととても似ている！　世界の終末が迫っていると！」"

[[dialogue]]
speaker = "レティシア"
# 「そのことを憂いて、デネブを助けに来てくれた……彼は、アルタイルの緋宮クロト！」
line = "「そのことを憂いて、デネブを助けに来てくれた……彼は、アルタイルの緋宮クロト！」"

[[dialogue]]
speaker = "デネブ市民"
# 「どっ、どういうことですか？　アルタイルの彼は、すでにデネブの彼の手で殺され、成り代わっていると！」
line = "「どっ、どういうことですか？　アルタイルの彼は、すでにデネブの彼の手で殺され、成り代わっていると！」"

[[dialogue]]
speaker = "デネブ市民"
# 「私たちを見捨ててアルタイルに逃げ出した……緋宮クロトは裏切ったと、女神様が仰っていたのでは……！？」
line = "「私たちを見捨ててアルタイルに逃げ出した……緋宮クロトは裏切ったと、女神様が仰っていたのでは……！？」"

[[dialogue]]
speaker = "レティシア"
# 「……急に信じろと言う方が難しいかもしれない。私たちもずいぶん時間がかかったから……でも、真実はそうではなかったの」
line = "「……急に信じろと言う方が難しいかもしれない。私たちもずいぶん時間がかかったから……でも、真実はそうではなかったの」"

[[dialogue]]
speaker = "レティシア"
# 「あなたたちもルヴィが、テルル様の御声を聞くことができるのは知っているわよね？」
line = "「あなたたちもルヴィが、テルル様の御声を聞くことができるのは知っているわよね？」"

[[dialogue]]
speaker = "レティシア"
# 「でも……女神様の声を騙る、別の悪神がいたのよ」
line = "「でも……女神様の声を騙る、別の悪神がいたのよ」"

[[dialogue]]
speaker = "レティシア"
# 「そいつが……本当は名誉の戦死をしたはずのデネブの緋宮クロトを『裏切り者だ』と偽り、まだ幼かったルヴィに伝えた！」
line = "「そいつが……本当は名誉の戦死をしたはずのデネブの緋宮クロトを『裏切り者だ』と偽り、まだ幼かったルヴィに伝えた！」"

[[dialogue]]
speaker = "レティシア"
# 「すべては私たちデネブと、アルタイルの世界を仲たがいさせるための策略よ……！」
line = "「すべては私たちデネブと、アルタイルの世界を仲たがいさせるための策略よ……！」"

[[dialogue]]
speaker = "レティシア"
# 「今のように世界の破滅が近づいた時、２つの世界を協力させないために……！」
line = "「今のように世界の破滅が近づいた時、２つの世界を協力させないために……！」"

[[dialogue]]
speaker = "レティシア"
# 「私たち極星星徒会は、平行世界アルタイルでその真実を知り、持ち帰って来たの！」
line = "「私たち極星星徒会は、平行世界アルタイルでその真実を知り、持ち帰って来たの！」"

[[dialogue]]
speaker = "unk"
# デネブ市民に動揺が広がり、お互いの顔を見合わせて会話がなされていく。
line = "デネブ市民に動揺が広がり、お互いの顔を見合わせて会話がなされていく。"

[[dialogue]]
speaker = "デネブ市民"
# 「そんな……まさか……」
line = "「そんな……まさか……」"

[[dialogue]]
speaker = "デネブ市民"
# 「テルル様の御声を騙り、ルヴィネ様を騙した真の敵がいる……！？」
line = "「テルル様の御声を騙り、ルヴィネ様を騙した真の敵がいる……！？」"

[[dialogue]]
speaker = "レティシア"
# 「みんなも見ているはずよ。ルヴィにそっくりの敵が暴れまわる姿を！　あれも全て、その敵が創り出している──私たちの心を折るために！」
line = "「みんなも見ているはずよ。ルヴィにそっくりの敵が暴れまわる姿を！　あれも全て、その敵が創り出している──私たちの心を折るために！」"

[[dialogue]]
speaker = "デネブ市民"
# 「そ、そいつはいったい──何者なんです！？」
line = "「そ、そいつはいったい──何者なんです！？」"

[[dialogue]]
speaker = "レティシア"
# 「リクリエを起こそうとしている悪神。私たちは──『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』と呼んでいるわ」
line = "「リクリエを起こそうとしている悪神。私たちは──『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』と呼んでいるわ」"

[[dialogue]]
speaker = "デネブ市民"
# 「……ぜろ、す？」
line = "「……ぜろ、す？」"

[[dialogue]]
speaker = "デネブ市民"
# 「わ、わけがわからない……そんな……」
line = "「わ、わけがわからない……そんな……」"

[[dialogue]]
speaker = "デネブ市民"
# 「で、でも！　ルヴィネ様が……！」
line = "「で、でも！　ルヴィネ様が……！」"

[[dialogue]]
speaker = "デネブ市民"
# 「ああ！　あの偽物とは違う、私たちのことをいつも一番に考えてくださる、ルヴィネ様が……正しいと仰るのなら！！」
line = "「ああ！　あの偽物とは違う、私たちのことをいつも一番に考えてくださる、ルヴィネ様が……正しいと仰るのなら！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……っ！」
line = "「……っ！」"

[[dialogue]]
speaker = "デネブ市民"
# 「この１０年間、ずっと私たちを救ってくださった……貴女が仰るのなら、どんなことでも信じます！」
line = "「この１０年間、ずっと私たちを救ってくださった……貴女が仰るのなら、どんなことでも信じます！」"

[[dialogue]]
speaker = "デネブ市民"
# 「ルヴィネ様……そうなのですか！？」
line = "「ルヴィネ様……そうなのですか！？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……ええ。緋宮クロトは裏切り者ではなかった。私たちの、味方よ……」
line = "「……ええ。緋宮クロトは裏切り者ではなかった。私たちの、味方よ……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「今まで、誤った情報で混乱させてしまって──ごめんなさい」
line = "「今まで、誤った情報で混乱させてしまって──ごめんなさい」"

[[dialogue]]
speaker = "デネブ市民"
# 「……！　では、その『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』という輩が──」
line = "「……！　では、その『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』という輩が──」"

[[dialogue]]
speaker = "デネブ市民"
# 「ルヴィネ様に嘘を教えて、アルタイルの罪もない人々を殺させようとしていたと！？」
line = "「ルヴィネ様に嘘を教えて、アルタイルの罪もない人々を殺させようとしていたと！？」"

[[dialogue]]
speaker = "クロト"
# 「──まさかレティシアが、ここまで言ってくれるとは思わなかった。ありがとう」
line = "「──まさかレティシアが、ここまで言ってくれるとは思わなかった。ありがとう」"

[[dialogue]]
speaker = "レティシア"
# 「ええ。流石はデネブで大人気のルヴィネ様ね。みんな、どんどん信じてくれている」
line = "「ええ。流石はデネブで大人気のルヴィネ様ね。みんな、どんどん信じてくれている」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……嘘が多いわ。それに、私にとって都合がよすぎる……」
line = "「……嘘が多いわ。それに、私にとって都合がよすぎる……」"

[[dialogue]]
speaker = "レティシア"
# 「いいじゃない。この方が合理的よ？　本当の真実を知るのは、私たちだけで十分」
line = "「いいじゃない。この方が合理的よ？　本当の真実を知るのは、私たちだけで十分」"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………ごめんなさい。ありがとう」
line = "「…………ごめんなさい。ありがとう」"

[[dialogue]]
speaker = "デネブ市民"
# 「い、今すぐにこの事実を市国中に伝えなければ……！」
line = "「い、今すぐにこの事実を市国中に伝えなければ……！」"

[[dialogue]]
speaker = "デネブ市民"
# 「ルヴィネ様と極星星徒会が帰ってきた。そして私たちの世界は、見捨てられてなんていなかった！」
line = "「ルヴィネ様と極星星徒会が帰ってきた。そして私たちの世界は、見捨てられてなんていなかった！」"

[[dialogue]]
speaker = "unk"
# デネブの流星市国内は、混乱と絶望が広がっていた──しかし、ルヴィネの帰還や、かつての俺への誤解が払拭できれば、持ち直すこともできるかもしれない。
line = "デネブの流星市国内は、混乱と絶望が広がっていた──しかし、ルヴィネの帰還や、かつての俺への誤解が払拭できれば、持ち直すこともできるかもしれない。"

[[dialogue]]
speaker = "ルヴィネ"
# 「でも手段と時間がどちらも足りないわ……伝える情報も多すぎる……」
line = "「でも手段と時間がどちらも足りないわ……伝える情報も多すぎる……」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ならちょうどいい。奥の手を使うか──リノ！」
line = "「ならちょうどいい。奥の手を使うか──リノ！」"

[[dialogue]]
speaker = "リノ"
# 「ええ──音声データは彼女にも共有済みよ。やるのね？」
line = "「ええ──音声データは彼女にも共有済みよ。やるのね？」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ああ。プラン・ジャスティスウィザード──お披露目の時だ！！」
line = "「ああ。プラン・ジャスティスウィザード──お披露目の時だ！！」"

[[dialogue]]
speaker = "unk"
# ジャスティスウィザード──その二つ名は、まさか。
line = "ジャスティスウィザード──その二つ名は、まさか。"

[[dialogue]]
speaker = "アポロ（大人）"
# 「あいつと繋いでくれ。魔王に代わる」
line = "「あいつと繋いでくれ。魔王に代わる」"

[[dialogue]]
speaker = "unk"
# アポロに投げられたＤＩＳＣをキャッチし、通話口に耳を当てると──
line = "アポロに投げられたＤＩＳＣをキャッチし、通話口に耳を当てると──"

[[dialogue]]
speaker = "？？？"
# 『──もしもし。会長さん、ですか？』
line = "『──もしもし。会長さん、ですか？』"

[[dialogue]]
speaker = "クロト"
# 「…………コハルコさん」
line = "「…………コハルコさん」"

[[dialogue]]
speaker = "コハルコ"
# 『はい。朝比奈コハルコです。１０年ぶりですね……ああ。いけません。懐かしすぎて……泣いてしまいそうです』
line = "『はい。朝比奈コハルコです。１０年ぶりですね……ああ。いけません。懐かしすぎて……泣いてしまいそうです』"

[[dialogue]]
speaker = "コハルコ"
# 『でも──非常事態ですものね。アポロさんの言っていたプランは、我々レジスタンスが水面下で進めていた、大規模なハッキング計画です』
line = "『でも──非常事態ですものね。アポロさんの言っていたプランは、我々レジスタンスが水面下で進めていた、大規模なハッキング計画です』"

[[dialogue]]
speaker = "コハルコ"
# 『実行すれば……流星市国内にあるディスプレイ、住民の個人端末に至るまで、全てを同時に長時間、乗っとることが可能です』
line = "『実行すれば……流星市国内にあるディスプレイ、住民の個人端末に至るまで、全てを同時に長時間、乗っとることが可能です』"

[[dialogue]]
speaker = "クロト"
# 「それは……なんていうか、規格外の凄さですね？」
line = "「それは……なんていうか、規格外の凄さですね？」"

[[dialogue]]
speaker = "コハルコ"
# 『こんなの正義のハッカーがやる行いじゃないですけど……いずれルヴィネの正体と、貴方の汚名を晴らすために、用意をしていました』
line = "『こんなの正義のハッカーがやる行いじゃないですけど……いずれルヴィネの正体と、貴方の汚名を晴らすために、用意をしていました』"

[[dialogue]]
speaker = "クロト"
# 「……お願いします。プラン・ジャスティスウィザード──実行してください！」
line = "「……お願いします。プラン・ジャスティスウィザード──実行してください！」"

[[dialogue]]
speaker = "コハルコ"
# 『……その名称だけは、ほんっとーに不服なんですよね！　センスを疑います！！』
line = "『……その名称だけは、ほんっとーに不服なんですよね！　センスを疑います！！』"

[[dialogue]]
speaker = "アポロ（大人）"
# 「……なんでだ？　かっこいいのに」
line = "「……なんでだ？　かっこいいのに」"

[[dialogue]]
speaker = "コハルコ"
# 『はぁ──了解しました、お任せください会長さん。全てが終わったら、今度こそ約束を果たしに来てください』
line = "『はぁ──了解しました、お任せください会長さん。全てが終わったら、今度こそ約束を果たしに来てください』"

[[dialogue]]
speaker = "コハルコ"
# 『戦いが終わったらまた会おうって……私、もう１０年も待ってるんですから！』
line = "『戦いが終わったらまた会おうって……私、もう１０年も待ってるんですから！』"

[[dialogue]]
speaker = "クロト"
# 「はい……必ず！」
line = "「はい……必ず！」"

[[dialogue]]
speaker = "unk"
# コハルコさんとの通話を終えた後──デネブの流星市国全域に、現在の状況が伝えられた。
line = "コハルコさんとの通話を終えた後──デネブの流星市国全域に、現在の状況が伝えられた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「これが最後の戦い──デネブのみんな！　死力を尽くして！　私たちが決着をつけるまで……お願い！　生き抜いて頂戴！！」
line = "「これが最後の戦い──デネブのみんな！　死力を尽くして！　私たちが決着をつけるまで……お願い！　生き抜いて頂戴！！」"

[[dialogue]]
speaker = "unk"
# そしてルヴィネの激励の声が発信された瞬間──街中が震えるような大歓声に包まれたのだった。
line = "そしてルヴィネの激励の声が発信された瞬間──街中が震えるような大歓声に包まれたのだった。"
