[[dialogue]]
speaker = "unk"
# 第１話,１０年前のデネブ,B
line = "第１話,１０年前のデネブ,B"

[[dialogue]]
speaker = "unk"
# あの時の<b>アタシ</b>たちは、いつもお腹をぐーぐー鳴らしていた。文字通り、泥水をすすって喉の渇きをいやす毎日だった。
line = "あの時の<b>アタシ</b>たちは、いつもお腹をぐーぐー鳴らしていた。文字通り、泥水をすすって喉の渇きをいやす毎日だった。"

[[dialogue]]
speaker = "unk"
# おしゃれもできない、遊ぶものもない、大好きな家族もいない。
line = "おしゃれもできない、遊ぶものもない、大好きな家族もいない。"

[[dialogue]]
speaker = "unk"
# そんな絶望的な状況でも、アタシたちの心が折れなかったのは──ぜんぶ。
line = "そんな絶望的な状況でも、アタシたちの心が折れなかったのは──ぜんぶ。"

[[dialogue]]
speaker = "unk"
# ルヴィがいてくれたからだ──
line = "ルヴィがいてくれたからだ──"

[[dialogue]]
speaker = "チナ"
# 「今日も大活躍だったな、アタシたち！」
line = "「今日も大活躍だったな、アタシたち！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ええ。チナもだいぶ星力の扱いに慣れてきたわね」
line = "「ええ。チナもだいぶ星力の扱いに慣れてきたわね」"

[[dialogue]]
speaker = "ベアトリス"
# 「グレイスちゃんもレティシアちゃんもおつかれさま！」
line = "「グレイスちゃんもレティシアちゃんもおつかれさま！」"

[[dialogue]]
speaker = "グレイス"
# 「ふふふ。我ら『ポラリス』にかかれば、モンスターなんて恐るるに足らずというやつです！」
line = "「ふふふ。我ら『ポラリス』にかかれば、モンスターなんて恐るるに足らずというやつです！」"

[[dialogue]]
speaker = "レティシア"
# 「…………ん」
line = "「…………ん」"

[[dialogue]]
speaker = "ルヴィネ"
# 「みんな疲れたでしょう。夕食にしましょうか」
line = "「みんな疲れたでしょう。夕食にしましょうか」"

[[dialogue]]
speaker = "グレイス"
# 「はい！　今日のメニューも、豆の缶詰と乾パンですね……ではルヴィ。リーダーから分配をおねがいします！」
line = "「はい！　今日のメニューも、豆の缶詰と乾パンですね……ではルヴィ。リーダーから分配をおねがいします！」"

[[dialogue]]
speaker = "チナ"
# 「きっちり五等分だぞ、ルヴィ」
line = "「きっちり五等分だぞ、ルヴィ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……どうして釘をさすのかしら」
line = "「……どうして釘をさすのかしら」"

[[dialogue]]
speaker = "ベアトリス"
# 「ルヴィはすぐ自分のぶん、グレイスちゃんにわけちゃうもん。ちゃんと食べなきゃ、また体こわしちゃうよ？」
line = "「ルヴィはすぐ自分のぶん、グレイスちゃんにわけちゃうもん。ちゃんと食べなきゃ、また体こわしちゃうよ？」"

[[dialogue]]
speaker = "チナ"
# 「そーだぞ。ルヴィはグレイスに甘いところがあるからな！」
line = "「そーだぞ。ルヴィはグレイスに甘いところがあるからな！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……ごめんなさいグレイス。監視の目が厳しいから、今日はちゃんと五等分ね？」
line = "「……ごめんなさいグレイス。監視の目が厳しいから、今日はちゃんと五等分ね？」"

[[dialogue]]
speaker = "グレイス"
# 「がーん……！　この恨み、忘れませんよチナ……！」
line = "「がーん……！　この恨み、忘れませんよチナ……！」"

[[dialogue]]
speaker = "チナ"
# 「つまんねーことで恨むな、ばーか」
line = "「つまんねーことで恨むな、ばーか」"

[[dialogue]]
speaker = "レティシア"
# 「…………にぎやか」
line = "「…………にぎやか」"

[[dialogue]]
speaker = "unk"
# ──１０年前のデネブ。
line = "──１０年前のデネブ。"

[[dialogue]]
speaker = "unk"
# 魔王クロトに見捨てられ、荒廃の極みに達した、絶望しかない流星市国でアタシたちは出会った。
line = "魔王クロトに見捨てられ、荒廃の極みに達した、絶望しかない流星市国でアタシたちは出会った。"

[[dialogue]]
speaker = "unk"
# 寝るのも、起きるのも、食べるものもすべて一緒……その中心にはいつもルヴィがいた。
line = "寝るのも、起きるのも、食べるものもすべて一緒……その中心にはいつもルヴィがいた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「大丈夫よ。あなたたちは死なない。救援が来るまで、私が命に代えても守るわ」
line = "「大丈夫よ。あなたたちは死なない。救援が来るまで、私が命に代えても守るわ」"

[[dialogue]]
speaker = "unk"
# アタシたちが不安に押しつぶされそうになった時は、いつもルヴィが励ましてくれた。
line = "アタシたちが不安に押しつぶされそうになった時は、いつもルヴィが励ましてくれた。"

[[dialogue]]
speaker = "unk"
# 寝るのが怖いと言えば、手を繋いでくれた。話し相手になって、安心させてくれた。
line = "寝るのが怖いと言えば、手を繋いでくれた。話し相手になって、安心させてくれた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「明日は、建物の修理をしましょうか。大聖堂の雨漏りがひどいから」
line = "「明日は、建物の修理をしましょうか。大聖堂の雨漏りがひどいから」"

[[dialogue]]
speaker = "ルヴィネ"
# 「この間、図書館で日曜大工の本を見つけたの。みんなで修理してみましょう」
line = "「この間、図書館で日曜大工の本を見つけたの。みんなで修理してみましょう」"

[[dialogue]]
speaker = "ベアトリス"
# 「おもしろそう！　やるやる！」
line = "「おもしろそう！　やるやる！」"

[[dialogue]]
speaker = "unk"
# モンスターと戦うだけじゃない。ルヴィはあらゆるところに気を配った。
line = "モンスターと戦うだけじゃない。ルヴィはあらゆるところに気を配った。"

[[dialogue]]
speaker = "ルヴィネ"
# 「就寝の前に、避難民の人達にも挨拶をしておくわ。最近、モンスターがたくさん出現しているから、きっと不安だと思うの」
line = "「就寝の前に、避難民の人達にも挨拶をしておくわ。最近、モンスターがたくさん出現しているから、きっと不安だと思うの」"

[[dialogue]]
speaker = "unk"
# 魔王クロトはデネブを見捨てた。魔王以外の星騎士は、そのほとんどが『仮面の女』に殺された。
line = "魔王クロトはデネブを見捨てた。魔王以外の星騎士は、そのほとんどが『仮面の女』に殺された。"

[[dialogue]]
speaker = "unk"
# 流星群が収まった後もアステラは湧き出て、モンスターは次々に現れる──そんな辛い状況下で、アタシたちの結束は生まれた。
line = "流星群が収まった後もアステラは湧き出て、モンスターは次々に現れる──そんな辛い状況下で、アタシたちの結束は生まれた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「ここで星力を扱えるのは、私たち５人だけ。みんな、明日も頑張りましょう。力を貸してちょうだい」
line = "「ここで星力を扱えるのは、私たち５人だけ。みんな、明日も頑張りましょう。力を貸してちょうだい」"

[[dialogue]]
speaker = "unk"
# 文字どおり一蓮托生の、かけがえのない５人のともだち──
line = "文字どおり一蓮托生の、かけがえのない５人のともだち──"

[[dialogue]]
speaker = "チナ"
# 「…………夢、か」
line = "「…………夢、か」"

[[dialogue]]
speaker = "unk"
# グレイスとレティシアの天界襲撃を止めるため、一時的にアルタイルの側についたチナ。
line = "グレイスとレティシアの天界襲撃を止めるため、一時的にアルタイルの側についたチナ。"

[[dialogue]]
speaker = "unk"
# チナも緋宮クロトたち星騎士の帰還に合わせて、人間界の新星学園へと戻ってきていた。
line = "チナも緋宮クロトたち星騎士の帰還に合わせて、人間界の新星学園へと戻ってきていた。"

[[dialogue]]
speaker = "チナ"
# 「……明日から、本格的にルヴィについての話し合いをしていくって、魔王は言ってたよな」
line = "「……明日から、本格的にルヴィについての話し合いをしていくって、魔王は言ってたよな」"

[[dialogue]]
speaker = "unk"
# ルヴィネは、リクリエを扇動する新しい女神の幼体。それが真実であれば激突は避けられない。
line = "ルヴィネは、リクリエを扇動する新しい女神の幼体。それが真実であれば激突は避けられない。"

[[dialogue]]
speaker = "unk"
# そのことは、何度も何度も自問したはずだったのに。
line = "そのことは、何度も何度も自問したはずだったのに。"

[[dialogue]]
speaker = "チナ"
# 「…………ルヴィ」
line = "「…………ルヴィ」"

[[dialogue]]
speaker = "unk"
# 先ほど見た夢が、チナの心を揺さぶる。
line = "先ほど見た夢が、チナの心を揺さぶる。"

[[dialogue]]
speaker = "unk"
# ルヴィネの行動はすべてが嘘なのか。偽りなのか──チナにはどうしてもそう思えないのだった。
line = "ルヴィネの行動はすべてが嘘なのか。偽りなのか──チナにはどうしてもそう思えないのだった。"
