[[dialogue]]
speaker = "unk"
# 第５話,プラネット大作戦,B
line = "第５話,プラネット大作戦,B"

[[dialogue]]
speaker = "セーラ"
# 「その特殊コタイ？　ってやつは何が違うんだっけ？」
line = "「その特殊コタイ？　ってやつは何が違うんだっけ？」"

[[dialogue]]
speaker = "ソフィア"
# 「従来のモンスターとは見た目が明らかに違うそうです。また、強さもこれまで以上だと報告されています」
line = "「従来のモンスターとは見た目が明らかに違うそうです。また、強さもこれまで以上だと報告されています」"

[[dialogue]]
speaker = "ユウリ"
# 「んで、それが出てきたのが……」
line = "「んで、それが出てきたのが……」"

[[dialogue]]
speaker = "マトイ"
# 「アポロ──あの女の子が生み出したせい……」
line = "「アポロ──あの女の子が生み出したせい……」"

[[dialogue]]
speaker = "unk"
# アポロの振るった大剣から、それら特殊個体が湧き出ていたのを新星星徒会は思い出す。
line = "アポロの振るった大剣から、それら特殊個体が湧き出ていたのを新星星徒会は思い出す。"

[[dialogue]]
speaker = "サーシャ"
# 「確かにあの時見たモンスターは、これまでの敵より強力だったわね」
line = "「確かにあの時見たモンスターは、これまでの敵より強力だったわね」"

[[dialogue]]
speaker = "アナ"
# 「残党がいるなら、<ruby=アポロ>ボス</ruby>が出てくる前に叩く」
line = "「残党がいるなら、<ruby>ボス<rt>アポロ</rt></ruby>が出てくる前に叩く」"

[[dialogue]]
speaker = "ルリエル"
# 「モンスターを従える女の子……でありますか！？　末恐ろしいであります……！」
line = "「モンスターを従える女の子……でありますか！？　末恐ろしいであります……！」"

[[dialogue]]
speaker = "unk"
# アポロが産み落としていった特殊個体のモンスターは、あれ以来世界の各地で目撃されるようになった。
line = "アポロが産み落としていった特殊個体のモンスターは、あれ以来世界の各地で目撃されるようになった。"

[[dialogue]]
speaker = "unk"
# ただしそれらは強力な力を持ちつつも、どこか<ruby=もうろう>朦朧</ruby>としているのが特徴とされていた。
line = "ただしそれらは強力な力を持ちつつも、どこか<ruby>朦朧<rt>もうろう</rt></ruby>としているのが特徴とされていた。"

[[dialogue]]
speaker = "ルリエル"
# 「──あ！　あそこにいます！　ルリエルが見つけました、大手柄です！」
line = "「──あ！　あそこにいます！　ルリエルが見つけました、大手柄です！」"

[[dialogue]]
speaker = "セーラ"
# 「ほんとだ。へー、見た目はなんかカワイイけど」
line = "「ほんとだ。へー、見た目はなんかカワイイけど」"

[[dialogue]]
speaker = "サーシャ"
# 「中身はあんまり可愛くないのよねえ～」
line = "「中身はあんまり可愛くないのよねえ～」"

[[dialogue]]
speaker = "マトイ"
# 「──あ、あっちにもいます。こうして見ると……色んなところに点在しているというか……」
line = "「──あ、あっちにもいます。こうして見ると……色んなところに点在しているというか……」"

[[dialogue]]
speaker = "ユウリ"
# 「ま、各個撃破できるならその方がいいかもな」
line = "「ま、各個撃破できるならその方がいいかもな」"

[[dialogue]]
speaker = "ソフィア"
# 「では、各星徒会ごとに分かれて駆除していきましょう。少なくとも市国内は掃討した方がよいと思います」
line = "「では、各星徒会ごとに分かれて駆除していきましょう。少なくとも市国内は掃討した方がよいと思います」"

[[dialogue]]
speaker = "セーラ"
# 「ん～……」
line = "「ん～……」"

[[dialogue]]
speaker = "ユウリ"
# 「セーラさん？」
line = "「セーラさん？」"

[[dialogue]]
speaker = "unk"
# <ruby=おとがい>顎</ruby>に指をあて小考するセーラ。
line = "<ruby>顎<rt>おとがい</rt></ruby>に指をあて小考するセーラ。"

[[dialogue]]
speaker = "unk"
# さっそく出動しようとしていた両星徒会の生徒たちに、彼女は異なる提案をぶつける。
line = "さっそく出動しようとしていた両星徒会の生徒たちに、彼女は異なる提案をぶつける。"

[[dialogue]]
speaker = "セーラ"
# 「今回は流星新星ミックスでやってみない？　せっかくなんだし、敵もバラバラだしさ」
line = "「今回は流星新星ミックスでやってみない？　せっかくなんだし、敵もバラバラだしさ」"

[[dialogue]]
speaker = "アナ"
# 「ミックスというと……別け隔てなくチームを組むということでしょうか」
line = "「ミックスというと……別け隔てなくチームを組むということでしょうか」"

[[dialogue]]
speaker = "ソフィア"
# 「は……反対です！　どうしてですかセーラ先輩、私たちじゃダメなんですか」
line = "「は……反対です！　どうしてですかセーラ先輩、私たちじゃダメなんですか」"

[[dialogue]]
speaker = "セーラ"
# 「ダメってことはないけど～。今後のためになると思わない？」
line = "「ダメってことはないけど～。今後のためになると思わない？」"

[[dialogue]]
speaker = "ソフィア"
# 「今後の……？」
line = "「今後の……？」"

[[dialogue]]
speaker = "セーラ"
# 「だって、もしもっと強い敵が出てきたら両学園で連携しなくちゃダメっしょ？　<b>姉妹校</b>なんだし」
line = "「だって、もしもっと強い敵が出てきたら両学園で連携しなくちゃダメっしょ？　<b>姉妹校</b>なんだし」"

[[dialogue]]
speaker = "ソフィア"
# 「そ──それは、その通りですが……！」
line = "「そ──それは、その通りですが……！」"

[[dialogue]]
speaker = "サーシャ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "アナ"
# 「確かによい機会と言えます。新たな連携も試せるかと」
line = "「確かによい機会と言えます。新たな連携も試せるかと」"

[[dialogue]]
speaker = "ユウリ"
# 「あたしも賛成だ。たまには共闘っつーのも、燃えるだろ」
line = "「あたしも賛成だ。たまには共闘っつーのも、燃えるだろ」"

[[dialogue]]
speaker = "マトイ"
# 「私も……足を引っ張ってしまうかもしれませんが、精一杯頑張ります！」
line = "「私も……足を引っ張ってしまうかもしれませんが、精一杯頑張ります！」"

[[dialogue]]
speaker = "ソフィア"
# 「う、うぅ……」
line = "「う、うぅ……」"

[[dialogue]]
speaker = "セーラ"
# 「じゃ、そゆことで♪　各自、流星市国に散らばるモンスター特殊個体を撃破すること」
line = "「じゃ、そゆことで♪　各自、流星市国に散らばるモンスター特殊個体を撃破すること」"

[[dialogue]]
speaker = "ルリエル"
# 「えいえいおーなのです！」
line = "「えいえいおーなのです！」"
