[[dialogue]]
speaker = "unk"
# 第１０話,破壊の爪痕,B
line = "第１０話,破壊の爪痕,B"

[[dialogue]]
speaker = "unk"
# 俺とヴィーナスもデネブの街に繰り出したのだが──
line = "俺とヴィーナスもデネブの街に繰り出したのだが──"

[[dialogue]]
speaker = "ヴィーナス"
# 「本当に誰も見向きもしないわね。ちゃんと溶けこめているみたいだわ」
line = "「本当に誰も見向きもしないわね。ちゃんと溶けこめているみたいだわ」"

[[dialogue]]
speaker = "クロト"
# 「ああ。母さんには助けられっぱなしだ」
line = "「ああ。母さんには助けられっぱなしだ」"

[[dialogue]]
speaker = "unk"
# 母さんの魔法で、周囲からは同年代の一般人に見えているんだとか。
line = "母さんの魔法で、周囲からは同年代の一般人に見えているんだとか。"

[[dialogue]]
speaker = "unk"
# ただし戦うと隠蔽が解除されてしまうので、戦闘は厳禁だと言われている。
line = "ただし戦うと隠蔽が解除されてしまうので、戦闘は厳禁だと言われている。"

[[dialogue]]
speaker = "クロト"
# 「食料品はここから西のスーパーがいいらしい。でも先に──」
line = "「食料品はここから西のスーパーがいいらしい。でも先に──」"

[[dialogue]]
speaker = "unk"
# 目的に向かって歩き出そうとしていると、男の子が向こうから走ってきた。
line = "目的に向かって歩き出そうとしていると、男の子が向こうから走ってきた。"

[[dialogue]]
speaker = "男の子"
# 「わ～～～～っ！！」
line = "「わ～～～～っ！！」"

[[dialogue]]
speaker = "クロト"
# 「おっとっと」
line = "「おっとっと」"

[[dialogue]]
speaker = "unk"
# ぶつかってきた男の子を受け止める。普段モンスターと戦ってるから、子どもの突進なんてかわいいものだ。
line = "ぶつかってきた男の子を受け止める。普段モンスターと戦ってるから、子どもの突進なんてかわいいものだ。"

[[dialogue]]
speaker = "unk"
# 男の子を追いかけて、母親らしき若い女性が心配そうに駆けてくる。
line = "男の子を追いかけて、母親らしき若い女性が心配そうに駆けてくる。"

[[dialogue]]
speaker = "母親"
# 「す、すみません！　この子ったら、久しぶりに都会に来て、はしゃいでるみたいで……」
line = "「す、すみません！　この子ったら、久しぶりに都会に来て、はしゃいでるみたいで……」"

[[dialogue]]
speaker = "クロト"
# 「いえ、大丈夫です。子どもは元気なのが仕事ですから」
line = "「いえ、大丈夫です。子どもは元気なのが仕事ですから」"

[[dialogue]]
speaker = "クロト"
# 「でも危ないから、他の人がいるところで走っちゃダメだよ」
line = "「でも危ないから、他の人がいるところで走っちゃダメだよ」"

[[dialogue]]
speaker = "男の子"
# 「はーい、ごめんなさーい」
line = "「はーい、ごめんなさーい」"

[[dialogue]]
speaker = "unk"
# 男の子と母親が手を繋いで、向こうのビルに歩いていく。
line = "男の子と母親が手を繋いで、向こうのビルに歩いていく。"

[[dialogue]]
speaker = "unk"
# 見えなくなる前に２人でペコリと頭を下げて、ビルの中に消えていった。
line = "見えなくなる前に２人でペコリと頭を下げて、ビルの中に消えていった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ほんとにパパみたいなこと言うのね」
line = "「ほんとにパパみたいなこと言うのね」"

[[dialogue]]
speaker = "クロト"
# 「俺には大きな娘がいるからな」
line = "「俺には大きな娘がいるからな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふふ、きっとかわいくて素敵な娘さんに違いないわね♪」
line = "「ふふ、きっとかわいくて素敵な娘さんに違いないわね♪」"

[[dialogue]]
speaker = "unk"
# あえて誰のこととは言わず、笑いながらとぼけ合う。
line = "あえて誰のこととは言わず、笑いながらとぼけ合う。"

[[dialogue]]
speaker = "クロト"
# 「平和だな」
line = "「平和だな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「平和ねー」
line = "「平和ねー」"

[[dialogue]]
speaker = "unk"
# １０年前にリクリエを乗り越えたこの街は、何者にも脅かされない平穏を享受しているように見える。
line = "１０年前にリクリエを乗り越えたこの街は、何者にも脅かされない平穏を享受しているように見える。"

[[dialogue]]
speaker = "ヴィーナス"
# 「今は極星学園は敵だけど、デネブだろうと、アルタイルだろうと、やっぱり平和が一番よね」
line = "「今は極星学園は敵だけど、デネブだろうと、アルタイルだろうと、やっぱり平和が一番よね」"

[[dialogue]]
speaker = "クロト"
# 「ああ。アルタイルもデネブも、両方守りたいな」
line = "「ああ。アルタイルもデネブも、両方守りたいな」"

[[dialogue]]
speaker = "unk"
# 俺たちは世界を守るために、誰かの幸せのために戦っている。
line = "俺たちは世界を守るために、誰かの幸せのために戦っている。"

[[dialogue]]
speaker = "unk"
# 平和に暮らしている人々を見ると、そう実感させられるのだった。
line = "平和に暮らしている人々を見ると、そう実感させられるのだった。"

[[dialogue]]
speaker = "unk"
# アポロから『一度自分たちの目で見た方がいい』と言われている場所があった。
line = "アポロから『一度自分たちの目で見た方がいい』と言われている場所があった。"

[[dialogue]]
speaker = "unk"
# それは俺とヴィーナスに深く関わる場所で──
line = "それは俺とヴィーナスに深く関わる場所で──"

[[dialogue]]
speaker = "unk"
# 破壊の痕が残る教皇庁と、その周辺の広場。
line = "破壊の痕が残る教皇庁と、その周辺の広場。"

[[dialogue]]
speaker = "unk"
# 目を覆いたくなる惨状だが、ここで起きたことを思えば、これでもまだ綺麗な方だろう。
line = "目を覆いたくなる惨状だが、ここで起きたことを思えば、これでもまだ綺麗な方だろう。"

[[dialogue]]
speaker = "ヴィーナス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは目を逸らしそうになるのをこらえて、この光景を目に焼き付けようとしていた。
line = "ヴィーナスは目を逸らしそうになるのをこらえて、この光景を目に焼き付けようとしていた。"

[[dialogue]]
speaker = "クロト"
# （壊れている以外は、アルタイルの教皇庁と変わらないな。だから余計に見るのが苦しいんだけど……）
line = "（壊れている以外は、アルタイルの教皇庁と変わらないな。だから余計に見るのが苦しいんだけど……）"

[[dialogue]]
speaker = "unk"
# 市民も観光客も、この辺りを訪れることはないという。
line = "市民も観光客も、この辺りを訪れることはないという。"

[[dialogue]]
speaker = "unk"
# 流星市国の中心であり、象徴であったこの場所が、まるで存在しないかのように捨て置かれている。
line = "流星市国の中心であり、象徴であったこの場所が、まるで存在しないかのように捨て置かれている。"

[[dialogue]]
speaker = "unk"
# 流星市国やその周辺はビル街のように復興がなされているが、どうしてここだけ廃墟のままなのか。
line = "流星市国やその周辺はビル街のように復興がなされているが、どうしてここだけ廃墟のままなのか。"

[[dialogue]]
speaker = "unk"
# リクリエとの戦いの<ruby=モニュメント>記念碑</ruby>として保存されているわけではない。
line = "リクリエとの戦いの<ruby>記念碑<rt>モニュメント</rt></ruby>として保存されているわけではない。"

[[dialogue]]
speaker = "unk"
# それは──
line = "それは──"

[[dialogue]]
speaker = "クロト"
# 「──！」
line = "「──！」"

[[dialogue]]
speaker = "unk"
# 空の色が変わる──いや、空が裂けた。
line = "空の色が変わる──いや、空が裂けた。"

[[dialogue]]
speaker = "unk"
# 上空には光すら呑み込む闇が広がっていて、さながらブラックホールだ。
line = "上空には光すら呑み込む闇が広がっていて、さながらブラックホールだ。"

[[dialogue]]
speaker = "unk"
# 危険がないように離れているものの、虚空が空気を吸い込んで、唸るような風の音を巻き起こしている。
line = "危険がないように離れているものの、虚空が空気を吸い込んで、唸るような風の音を巻き起こしている。"

[[dialogue]]
speaker = "unk"
# リクリエによる破壊の余波のようだけど……これをやったのは<b>俺</b>だ。
line = "リクリエによる破壊の余波のようだけど……これをやったのは<b>俺</b>だ。"

[[dialogue]]
speaker = "クロト"
# 「もう少しで勝てそうだったんだが……残念ながら俺はここまでのようだ」
line = "「もう少しで勝てそうだったんだが……残念ながら俺はここまでのようだ」"

[[dialogue]]
speaker = "クロト"
# 「<ruby=ヴィーナス>娘</ruby>を頼んだぞ……ラク──」
line = "「<ruby>娘<rt>ヴィーナス</rt></ruby>を頼んだぞ……ラク──」"

[[dialogue]]
speaker = "unk"
# デネブの俺は自身を犠牲にアルタイルへの道を開き、ヴィーナスをアルタイルに送り出した。
line = "デネブの俺は自身を犠牲にアルタイルへの道を開き、ヴィーナスをアルタイルに送り出した。"

[[dialogue]]
speaker = "unk"
# しかしその代償として、次元の裂け目が残されてしまった。
line = "しかしその代償として、次元の裂け目が残されてしまった。"

[[dialogue]]
speaker = "unk"
# １０年経った今でも不規則に空に穴が空いてしまい、そのせいで教皇庁の復興ができないのだという。
line = "１０年経った今でも不規則に空に穴が空いてしまい、そのせいで教皇庁の復興ができないのだという。"

[[dialogue]]
speaker = "unk"
# ルヴィネの思惑はさておき、元からあった太陽の壁画への信仰と、この惨状があれば、“魔王”が嫌われるのは無理もない。
line = "ルヴィネの思惑はさておき、元からあった太陽の壁画への信仰と、この惨状があれば、“魔王”が嫌われるのは無理もない。"

[[dialogue]]
speaker = "ヴィーナス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# ここはヴィーナスが実の父を喪った場所。そして自分が送り出された場所。
line = "ここはヴィーナスが実の父を喪った場所。そして自分が送り出された場所。"

[[dialogue]]
speaker = "unk"
# ヴィーナスにとっての始まりの場所だ。
line = "ヴィーナスにとっての始まりの場所だ。"

[[dialogue]]
speaker = "ヴィーナス"
# 「……ねぇ、クロト」
line = "「……ねぇ、クロト」"

[[dialogue]]
speaker = "ヴィーナス"
# 「花を手向けたら、吸い込まれちゃうかしら」
line = "「花を手向けたら、吸い込まれちゃうかしら」"

[[dialogue]]
speaker = "クロト"
# 「そうだな。きっと吹き飛ばされる」
line = "「そうだな。きっと吹き飛ばされる」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……そうよね」
line = "「……そうよね」"

[[dialogue]]
speaker = "クロト"
# 「だから、言いたいことがあるなら言葉にすればいいんじゃないか」
line = "「だから、言いたいことがあるなら言葉にすればいいんじゃないか」"

[[dialogue]]
speaker = "クロト"
# 「きっと伝わるよ。平行世界でも俺は俺だから、保証する」
line = "「きっと伝わるよ。平行世界でも俺は俺だから、保証する」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……うん」
line = "「……うん」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは虚空の空を見上げ、風にかき消されそうなか細い声で告げる。
line = "ヴィーナスは虚空の空を見上げ、風にかき消されそうなか細い声で告げる。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ありがとう、パパ。……ただいま」
line = "「ありがとう、パパ。……ただいま」"

[[dialogue]]
speaker = "unk"
# それでも俺にははっきりと聞こえた。
line = "それでも俺にははっきりと聞こえた。"

[[dialogue]]
speaker = "unk"
# 確かにここは、俺とヴィーナスが来なければいけない場所だった。
line = "確かにここは、俺とヴィーナスが来なければいけない場所だった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# やがて時空の穴が閉じ、風も収まった。
line = "やがて時空の穴が閉じ、風も収まった。"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナス、そろそろお腹空かないか？　買い物の前にお昼にしよう」
line = "「ヴィーナス、そろそろお腹空かないか？　買い物の前にお昼にしよう」"

[[dialogue]]
speaker = "クロト"
# 「母さんには外で食べてもいいって言われてるし、どうせならアルタイルにないお店で美味しいもの食べよう」
line = "「母さんには外で食べてもいいって言われてるし、どうせならアルタイルにないお店で美味しいもの食べよう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「いいわね！　新星星徒会のみんなに思い出話しましょ！」
line = "「いいわね！　新星星徒会のみんなに思い出話しましょ！」"
