[[dialogue]]
speaker = "unk"
# 第４話,宣戦布告,B
line = "第４話,宣戦布告,B"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「斬り刻んじゃうわよ～」
line = "「斬り刻んじゃうわよ～」"

[[dialogue]]
speaker = "チナ"
# 「また会長の極星従騎が……この……！」
line = "「また会長の極星従騎が……この……！」"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「新星星徒会の盾として、もう攻撃は通さない！」
line = "「新星星徒会の盾として、もう攻撃は通さない！」"

[[dialogue]]
speaker = "チナ"
# 「ッ……！」
line = "「ッ……！」"

[[dialogue]]
speaker = "unk"
# 大槍を真正面から受け止められ、動揺を見せた。
line = "大槍を真正面から受け止められ、動揺を見せた。"

[[dialogue]]
speaker = "unk"
# その瞬間──
line = "その瞬間──"

[[dialogue]]
speaker = "アナ（覚醒）"
# 「撃ち抜きます……！」
line = "「撃ち抜きます……！」"

[[dialogue]]
speaker = "unk"
# そして大弓に炎の矢を番え、過たず射貫く──！
line = "そして大弓に炎の矢を番え、過たず射貫く──！"

[[dialogue]]
speaker = "チナ"
# 「うあああぁああーーーーーーーっ！！？」
line = "「うあああぁああーーーーーーーっ！！？」"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 「はぁ、はぁ……何とかなった……のかな？」
line = "「はぁ、はぁ……何とかなった……のかな？」"

[[dialogue]]
speaker = "マトイ"
# 「あっ……ノヴァフォームが……」
line = "「あっ……ノヴァフォームが……」"

[[dialogue]]
speaker = "サーシャ"
# 「ふぅ。元の姿に戻っちゃったわね～」
line = "「ふぅ。元の姿に戻っちゃったわね～」"

[[dialogue]]
speaker = "アナ"
# 「やはりまだ短時間しか維持できません。研究、運用、そして私たち自身の成長と……いずれの面でも課題があります」
line = "「やはりまだ短時間しか維持できません。研究、運用、そして私たち自身の成長と……いずれの面でも課題があります」"

[[dialogue]]
speaker = "マトイ"
# 「うん。もっと長く戦えるようにならないと……」
line = "「うん。もっと長く戦えるようにならないと……」"

[[dialogue]]
speaker = "マトイ"
# 「あれ……セレスティア？　でも私たちのと違うような……」
line = "「あれ……セレスティア？　でも私たちのと違うような……」"

[[dialogue]]
speaker = "チナ"
# 「か、返せ！」
line = "「か、返せ！」"

[[dialogue]]
speaker = "チナ"
# 「それはアタシの……会長にもらったセレスティアだ！」
line = "「それはアタシの……会長にもらったセレスティアだ！」"

[[dialogue]]
speaker = "unk"
# セレスティアを失った彼女は変身が解け、ガーディアンに受け止められていた。
line = "セレスティアを失った彼女は変身が解け、ガーディアンに受け止められていた。"

[[dialogue]]
speaker = "クロト"
# 「何度でも聞くぞ！　君はいったい何者なんだ！？」
line = "「何度でも聞くぞ！　君はいったい何者なんだ！？」"

[[dialogue]]
speaker = "unk"
# さっきは一蹴された疑問をもう一度ぶつける。
line = "さっきは一蹴された疑問をもう一度ぶつける。"

[[dialogue]]
speaker = "unk"
# するとチナは、有り余る憤怒をにじませ、俺をにらみつけながら──
line = "するとチナは、有り余る憤怒をにじませ、俺をにらみつけながら──"

[[dialogue]]
speaker = "チナ"
# 「アタシは……星騎士だ」
line = "「アタシは……星騎士だ」"

[[dialogue]]
speaker = "クロト"
# 「星騎士だって……！？　だが新星にも流星学園にも、君みたいな星騎士はいないはずだ！」
line = "「星騎士だって……！？　だが新星にも流星学園にも、君みたいな星騎士はいないはずだ！」"

[[dialogue]]
speaker = "unk"
# 現に、まとっている制服は新星、流星どちらのものとも違う。
line = "現に、まとっている制服は新星、流星どちらのものとも違う。"

[[dialogue]]
speaker = "unk"
# 彼女が星力を使っているのは確かに感じていたが……
line = "彼女が星力を使っているのは確かに感じていたが……"

[[dialogue]]
speaker = "チナ"
# 「当たり前だ！　アタシはお前らとは違う。<ruby=きょくせい>極星</ruby>学園の星騎士だ！」
line = "「当たり前だ！　アタシはお前らとは違う。<ruby>極星<rt>きょくせい</rt></ruby>学園の星騎士だ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「極星……？　聞いたことない学園だけど」
line = "「極星……？　聞いたことない学園だけど」"

[[dialogue]]
speaker = "チナ"
# 「デネブの流星と新星は、リクリエに敗北した……」
line = "「デネブの流星と新星は、リクリエに敗北した……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「──！」
line = "「──！」"

[[dialogue]]
speaker = "unk"
# ３つあるとされる平行世界のうちのひとつで、俺たちが今いるアルタイルとは別の軸にある。
line = "３つあるとされる平行世界のうちのひとつで、俺たちが今いるアルタイルとは別の軸にある。"

[[dialogue]]
speaker = "unk"
# そしてヴィーナスが生まれた世界だ。
line = "そしてヴィーナスが生まれた世界だ。"

[[dialogue]]
speaker = "チナ"
# 「だが、<ruby=アタシたち>デネブ</ruby>は屈しなかった！　それが極星学園だ！」
line = "「だが、<ruby>デネブ<rt>アタシたち</rt></ruby>は屈しなかった！　それが極星学園だ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あなたがデネブから来たって、本当なの！？」
line = "「あなたがデネブから来たって、本当なの！？」"

[[dialogue]]
speaker = "チナ"
# 「本当だとも！　そしてアタシは、お前たちに宣戦布告しに来たんだ！」
line = "「本当だとも！　そしてアタシは、お前たちに宣戦布告しに来たんだ！」"

[[dialogue]]
speaker = "unk"
# 宣戦布告──剣呑な言葉に緊張がさらに高まる。
line = "宣戦布告──剣呑な言葉に緊張がさらに高まる。"

[[dialogue]]
speaker = "チナ"
# 「アタシは極星学園星徒会・庶務、<ruby=こうどう>香堂</ruby>チナ」
line = "「アタシは極星学園星徒会・庶務、<ruby>香堂<rt>こうどう</rt></ruby>チナ」"

[[dialogue]]
speaker = "チナ"
# 「平行世界アルタイルとデネブは敵対関係にある」
line = "「平行世界アルタイルとデネブは敵対関係にある」"

[[dialogue]]
speaker = "チナ"
# 「アルタイルのリクリエを止めれば、デネブのリクリエが加速する。デネブのリクリエを止めれば、アルタイルのリクリエが激化する」
line = "「アルタイルのリクリエを止めれば、デネブのリクリエが加速する。デネブのリクリエを止めれば、アルタイルのリクリエが激化する」"

[[dialogue]]
speaker = "チナ"
# 「いいか、これは生存競争だ。生き残るのはデネブかアルタイル、２つに１つ」
line = "「いいか、これは生存競争だ。生き残るのはデネブかアルタイル、２つに１つ」"

[[dialogue]]
speaker = "チナ"
# 「生き残るのはアタシらだ……！」
line = "「生き残るのはアタシらだ……！」"

[[dialogue]]
speaker = "unk"
# 彼女の表情が、怒りと憎悪で歪み、槍よりも鋭い殺意が俺を貫こうとしていた。
line = "彼女の表情が、怒りと憎悪で歪み、槍よりも鋭い殺意が俺を貫こうとしていた。"

[[dialogue]]
speaker = "チナ"
# 「極星従騎！」
line = "「極星従騎！」"

[[dialogue]]
speaker = "マトイ"
# 「きゃっ！？」
line = "「きゃっ！？」"

[[dialogue]]
speaker = "unk"
# 極星従騎の突進で、マトイの手からセレスティアが落ちる。
line = "極星従騎の突進で、マトイの手からセレスティアが落ちる。"

[[dialogue]]
speaker = "チナ"
# 「次こそはアルタイルを滅ぼす！」
line = "「次こそはアルタイルを滅ぼす！」"

[[dialogue]]
speaker = "unk"
# チナは自身のセレスティアを極星従騎から受け取ると、その背に乗って戦場を後にした。
line = "チナは自身のセレスティアを極星従騎から受け取ると、その背に乗って戦場を後にした。"

[[dialogue]]
speaker = "クロト"
# 「追うのは……難しいか」
line = "「追うのは……難しいか」"

[[dialogue]]
speaker = "クロト"
# 「ありがとう、みんなのおかげで助かったよ」
line = "「ありがとう、みんなのおかげで助かったよ」"

[[dialogue]]
speaker = "unk"
# 今回はマトイたちのノヴァフォームに助けられた。
line = "今回はマトイたちのノヴァフォームに助けられた。"

[[dialogue]]
speaker = "unk"
# 星徒会長としてふがいなく思う反面、みんなの新しい力はとても頼もしく思えた。
line = "星徒会長としてふがいなく思う反面、みんなの新しい力はとても頼もしく思えた。"

[[dialogue]]
speaker = "アナ"
# 「元はといえば、ノヴァフォームは魔王の力ですから」
line = "「元はといえば、ノヴァフォームは魔王の力ですから」"

[[dialogue]]
speaker = "マトイ"
# 「そうそう。それに今までいっぱい助けてもらったしね」
line = "「そうそう。それに今までいっぱい助けてもらったしね」"

[[dialogue]]
speaker = "サーシャ"
# 「あとは、ノヴァフォームを使えるようにしてくれたメイプルちゃんにも感謝ね～」
line = "「あとは、ノヴァフォームを使えるようにしてくれたメイプルちゃんにも感謝ね～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私もノヴァフォームになれたら良かったのに……」
line = "「私もノヴァフォームになれたら良かったのに……」"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナス？」
line = "「ヴィーナス？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ううん、何でもないわ！　それよりあの子よ、あの子！　デネブから来たっていう」
line = "「ううん、何でもないわ！　それよりあの子よ、あの子！　デネブから来たっていう」"

[[dialogue]]
speaker = "サーシャ"
# 「チナって言ってたかしら～？　強敵だったわね～」
line = "「チナって言ってたかしら～？　強敵だったわね～」"

[[dialogue]]
speaker = "マトイ"
# 「でも多分、あの子は普通の星騎士……だよね？」
line = "「でも多分、あの子は普通の星騎士……だよね？」"

[[dialogue]]
speaker = "クロト"
# 「リクリエの力は感じなかったし、リクリエに対して否定的だったのを見ると……使徒ではなさそうだ」
line = "「リクリエの力は感じなかったし、リクリエに対して否定的だったのを見ると……使徒ではなさそうだ」"

[[dialogue]]
speaker = "unk"
# 彼女が使っていたのは、俺たちと同じ星の力だった。
line = "彼女が使っていたのは、俺たちと同じ星の力だった。"

[[dialogue]]
speaker = "unk"
# ただ、鍛錬の度合いで言えば新星星徒会だって生半可なものではない。
line = "ただ、鍛錬の度合いで言えば新星星徒会だって生半可なものではない。"

[[dialogue]]
speaker = "unk"
# リクリエの力も、魔王の力もなしに、普通の星騎士があれほどまでに強くなれるものなのだろうか？
line = "リクリエの力も、魔王の力もなしに、普通の星騎士があれほどまでに強くなれるものなのだろうか？"

[[dialogue]]
speaker = "ヴィーナス"
# 「それにデネブが敵ってどういうこと？　極星学園とか、アルタイルを守るとデネブのリクリエが進むとか、わけわかんないことばっかりよ」
line = "「それにデネブが敵ってどういうこと？　極星学園とか、アルタイルを守るとデネブのリクリエが進むとか、わけわかんないことばっかりよ」"

[[dialogue]]
speaker = "クロト"
# 「それは……また後で整理しよう」
line = "「それは……また後で整理しよう」"

[[dialogue]]
speaker = "unk"
# それに以前の話では、デネブはすでにリクリエに敗北したとも聞いていた。
line = "それに以前の話では、デネブはすでにリクリエに敗北したとも聞いていた。"

[[dialogue]]
speaker = "unk"
# そこから刺客──しかも星騎士の──が現れるなんて、予想もしていなかった。
line = "そこから刺客──しかも星騎士の──が現れるなんて、予想もしていなかった。"

[[dialogue]]
speaker = "クロト"
# 「ひとまず学園に戻ろう。流星市国全体の被害状況を確認しないと──」
line = "「ひとまず学園に戻ろう。流星市国全体の被害状況を確認しないと──」"

[[dialogue]]
speaker = "？？？"
# 「しまった、パーティーに遅れてしまったね」
line = "「しまった、パーティーに遅れてしまったね」"

[[dialogue]]
speaker = "クロト"
# 「──！？」
line = "「──！？」"

[[dialogue]]
speaker = "マトイ"
# 「そんな……！？」
line = "「そんな……！？」"

[[dialogue]]
speaker = "unk"
# 彼女が俺たちの前に現れた瞬間、理解する。
line = "彼女が俺たちの前に現れた瞬間、理解する。"

[[dialogue]]
speaker = "unk"
# 仮面に宿る禍々しい破滅の力は、幾度も相対したアポロと同じ。
line = "仮面に宿る禍々しい破滅の力は、幾度も相対したアポロと同じ。"

[[dialogue]]
speaker = "unk"
# すなわち──彼女こそ新たなリクリエの使徒。
line = "すなわち──彼女こそ新たなリクリエの使徒。"

[[dialogue]]
speaker = "ジグ"
# 「お初にお目にかかるよ、魔王様。私はジグ。“真なる神の騎士”だ」
line = "「お初にお目にかかるよ、魔王様。私はジグ。“真なる神の騎士”だ」"

[[dialogue]]
speaker = "クロト"
# 「真なる神……？」
line = "「真なる神……？」"

[[dialogue]]
speaker = "ジグ"
# 「君たちが信仰する女神のような紛い物とは違う、世界を創造せし真なる神だ」
line = "「君たちが信仰する女神のような紛い物とは違う、世界を創造せし真なる神だ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「紛い物ですって！？」
line = "「紛い物ですって！？」"

[[dialogue]]
speaker = "ジグ"
# 「うん、紛い物。そう言っただろう？」
line = "「うん、紛い物。そう言っただろう？」"

[[dialogue]]
speaker = "unk"
# 怒りをにじませるヴィーナスにも動じず、ジグと名乗った使徒は仮面の下でにこりと微笑む。
line = "怒りをにじませるヴィーナスにも動じず、ジグと名乗った使徒は仮面の下でにこりと微笑む。"

[[dialogue]]
speaker = "ジグ"
# 「まぁ、そんなわけで短い間になるかもしれないけどよろしくね、魔王様」
line = "「まぁ、そんなわけで短い間になるかもしれないけどよろしくね、魔王様」"

[[dialogue]]
speaker = "unk"
# 恭しくお辞儀をし、鷹揚に挨拶してみせるリクリエの使徒。
line = "恭しくお辞儀をし、鷹揚に挨拶してみせるリクリエの使徒。"

[[dialogue]]
speaker = "unk"
# 今のところ攻撃の意思は見えないが、対応を誤れば即座にこちらが壊滅してしまうだろう。
line = "今のところ攻撃の意思は見えないが、対応を誤れば即座にこちらが壊滅してしまうだろう。"

[[dialogue]]
speaker = "ジグ"
# 「いや、しかし失態だ。記念すべきアルタイルとデネブの星騎士の初邂逅を見届けに来たのだけど、遅くなってしまった」
line = "「いや、しかし失態だ。記念すべきアルタイルとデネブの星騎士の初邂逅を見届けに来たのだけど、遅くなってしまった」"

[[dialogue]]
speaker = "ジグ"
# 「まあ終わってしまったものは仕方がない。挨拶も済んだことだし、出直すとしよう」
line = "「まあ終わってしまったものは仕方がない。挨拶も済んだことだし、出直すとしよう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ちょっと……！　リクリエの使徒なのに、ホントに見に来ただけなの！？」
line = "「ちょっと……！　リクリエの使徒なのに、ホントに見に来ただけなの！？」"

[[dialogue]]
speaker = "ジグ"
# 「うん、<b>あの子</b>にはあの子なりの思惑があるようだからね。お手並み拝見しようと思って」
line = "「うん、<b>あの子</b>にはあの子なりの思惑があるようだからね。お手並み拝見しようと思って」"

[[dialogue]]
speaker = "ジグ"
# 「でもお土産くらいは──」
line = "「でもお土産くらいは──」"

[[dialogue]]
speaker = "ジグ"
# 「置いていこうかな」
line = "「置いていこうかな」"

[[dialogue]]
speaker = "クロト"
# 「！？」
line = "「！？」"

[[dialogue]]
speaker = "unk"
# リクリエの使徒が瞬時に距離を詰めてきた。
line = "リクリエの使徒が瞬時に距離を詰めてきた。"

[[dialogue]]
speaker = "unk"
# 反応が間に合わない。
line = "反応が間に合わない。"

[[dialogue]]
speaker = "ジグ"
# 「えい♪」
line = "「えい♪」"

[[dialogue]]
speaker = "unk"
# 剣先がツン、と胸に触れた。
line = "剣先がツン、と胸に触れた。"

[[dialogue]]
speaker = "unk"
# 痛みはない。出血もない。
line = "痛みはない。出血もない。"

[[dialogue]]
speaker = "unk"
# ただ切っ先が届いただけ──
line = "ただ切っ先が届いただけ──"

[[dialogue]]
speaker = "クロト"
# 「！！？？」
line = "「！！？？」"

[[dialogue]]
speaker = "ジグ"
# 「フフフ……」
line = "「フフフ……」"

[[dialogue]]
speaker = "梨緒"
# 「インパルスストリーム！」
line = "「インパルスストリーム！」"

[[dialogue]]
speaker = "ジグ"
# 「！！」
line = "「！！」"

[[dialogue]]
speaker = "unk"
# 轟く雷光を避け、リクリエの使徒が距離を取る。
line = "轟く雷光を避け、リクリエの使徒が距離を取る。"

[[dialogue]]
speaker = "梨緒"
# 「はぁ、はぁ……魔王から離れろ、ジグ……！」
line = "「はぁ、はぁ……魔王から離れろ、ジグ……！」"

[[dialogue]]
speaker = "ジグ"
# 「おや。残してきたモンスター、ちゃんと倒してきたんだ。偉いね」
line = "「おや。残してきたモンスター、ちゃんと倒してきたんだ。偉いね」"

[[dialogue]]
speaker = "梨緒"
# 「あれくらいで、私たちを止められると思うな……！」
line = "「あれくらいで、私たちを止められると思うな……！」"

[[dialogue]]
speaker = "ジグ"
# 「それは失礼。もてなし足りなかったのは謝るよ」
line = "「それは失礼。もてなし足りなかったのは謝るよ」"

[[dialogue]]
speaker = "ジグ"
# 「では今度こそさよならだ。また会えるといいね」
line = "「では今度こそさよならだ。また会えるといいね」"

[[dialogue]]
speaker = "梨緒"
# 「待て、ジグ……！」
line = "「待て、ジグ……！」"

[[dialogue]]
speaker = "梨緒"
# 「ぅ……」
line = "「ぅ……」"

[[dialogue]]
speaker = "クロト"
# 「梨緒！？」
line = "「梨緒！？」"

[[dialogue]]
speaker = "unk"
# ジグを追いかけようとした梨緒が、顔を歪めながらその場に倒れる。
line = "ジグを追いかけようとした梨緒が、顔を歪めながらその場に倒れる。"

[[dialogue]]
speaker = "unk"
# 梨緒は気を失いながらも苦悶に満ちた表情を浮かべ、もがくようにジグが去った方向に手を伸ばしていた。
line = "梨緒は気を失いながらも苦悶に満ちた表情を浮かべ、もがくようにジグが去った方向に手を伸ばしていた。"
