[[dialogue]]
speaker = "unk"
# 第７話,シエルの筐,B
line = "第７話,シエルの筐,B"

[[dialogue]]
speaker = "リノ"
# 「よく言ったわ──フィオナちゃん。何もかも救える未来があるなら、人類はそれに賭けるべきよね」
line = "「よく言ったわ──フィオナちゃん。何もかも救える未来があるなら、人類はそれに賭けるべきよね」"

[[dialogue]]
speaker = "ルリエル"
# 「ほえ？」
line = "「ほえ？」"

[[dialogue]]
speaker = "リノ"
# 「よっ──と。お邪魔するわね、星徒会のみんな♪」
line = "「よっ──と。お邪魔するわね、星徒会のみんな♪」"

[[dialogue]]
speaker = "クロト"
# 「か……母さん！？」
line = "「か……母さん！？」"

[[dialogue]]
speaker = "マトイ"
# 「ひ……緋宮くんのお母さん！？」
line = "「ひ……緋宮くんのお母さん！？」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら。意外なご来客ばかりねえ」
line = "「あらあら。意外なご来客ばかりねえ」"

[[dialogue]]
speaker = "unk"
# 俺たちとネビュラとの火花の間に、割って入るように現れたのは──魔女服に身を包んだ母さんだった。
line = "俺たちとネビュラとの火花の間に、割って入るように現れたのは──魔女服に身を包んだ母さんだった。"

[[dialogue]]
speaker = "クロト"
# 「えーと──待ってくれ。まず、どうしてここに」
line = "「えーと──待ってくれ。まず、どうしてここに」"

[[dialogue]]
speaker = "ユウリ"
# 「な、なんだあ……！？　クロトの母ちゃん……？」
line = "「な、なんだあ……！？　クロトの母ちゃん……？」"

[[dialogue]]
speaker = "ソフィア"
# 「若すぎません？」
line = "「若すぎません？」"

[[dialogue]]
speaker = "リノ"
# 「まあまあ。細かいことはさておき」
line = "「まあまあ。細かいことはさておき」"

[[dialogue]]
speaker = "ニャリオン"
# 「色々と言いたいことはあるニャンが、いちいち話してたらキリない気もするニャン」
line = "「色々と言いたいことはあるニャンが、いちいち話してたらキリない気もするニャン」"

[[dialogue]]
speaker = "unk"
# 恐らくはニャリオンの言う通り。
line = "恐らくはニャリオンの言う通り。"

[[dialogue]]
speaker = "unk"
# そして何より、母さんに物申したいのはどうやら俺だけでもなかったようで……
line = "そして何より、母さんに物申したいのはどうやら俺だけでもなかったようで……"

[[dialogue]]
speaker = "セドナ"
# 「リノ──貴様は介入するなと伝えたはずだ。最後まで<ruby=われわれ>古巣</ruby>の邪魔をする気か？」
line = "「リノ──貴様は介入するなと伝えたはずだ。最後まで<ruby>古巣<rt>われわれ</rt></ruby>の邪魔をする気か？」"

[[dialogue]]
speaker = "リノ"
# 「今こそ実行の時だもの。フィオナちゃんの提案は、決して無下にできるものじゃないはずだわ」
line = "「今こそ実行の時だもの。フィオナちゃんの提案は、決して無下にできるものじゃないはずだわ」"

[[dialogue]]
speaker = "ルリエル"
# （ネ、ネビュラの方々ともお知り合いなのでありますか！？）
line = "（ネ、ネビュラの方々ともお知り合いなのでありますか！？）"

[[dialogue]]
speaker = "アナ"
# （いつの間に……いえ。あるいは元々<ruby=ちき>知己</ruby>だったのでしょうか）
line = "（いつの間に……いえ。あるいは元々<ruby>知己<rt>ちき</rt></ruby>だったのでしょうか）"

[[dialogue]]
speaker = "クロト"
# （ああ。恐らくな）
line = "（ああ。恐らくな）"

[[dialogue]]
speaker = "unk"
# 俺は、フィーニス第零層を踏破していく中で自分のルーツを見た。
line = "俺は、フィーニス第零層を踏破していく中で自分のルーツを見た。"

[[dialogue]]
speaker = "unk"
# そして、俺が目覚める瞬間に登場した母さんのことも。
line = "そして、俺が目覚める瞬間に登場した母さんのことも。"

[[dialogue]]
speaker = "リノ"
# 「ごめんなさいね、クロト。今はあまり説明している余裕はないのだけど──味方ってことはわかってくれると嬉しいわ」
line = "「ごめんなさいね、クロト。今はあまり説明している余裕はないのだけど──味方ってことはわかってくれると嬉しいわ」"

[[dialogue]]
speaker = "クロト"
# 「わかってるよ。母さんは、元々魔女だったんだろ」
line = "「わかってるよ。母さんは、元々魔女だったんだろ」"

[[dialogue]]
speaker = "リノ"
# 「あら。さすが私の息子、理解が早いわ」
line = "「あら。さすが私の息子、理解が早いわ」"

[[dialogue]]
speaker = "ユウリ"
# 「いやいやいや。何もわかんねーけど！？」
line = "「いやいやいや。何もわかんねーけど！？」"

[[dialogue]]
speaker = "マトイ"
# 「ま、魔女ってことはネビュラ側ってこと……？」
line = "「ま、魔女ってことはネビュラ側ってこと……？」"

[[dialogue]]
speaker = "リノ"
# 「違うわ。マトイちゃん。ほら、セドナだってあんな嫌そうにしているでしょう」
line = "「違うわ。マトイちゃん。ほら、セドナだってあんな嫌そうにしているでしょう」"

[[dialogue]]
speaker = "unk"
# 母さんの言葉を受けると、セドナさんは億劫そうにため息をついた。
line = "母さんの言葉を受けると、セドナさんは億劫そうにため息をついた。"

[[dialogue]]
speaker = "セドナ"
# 「その女は<ruby=ヤーガ>はぐれ魔女</ruby>──森を去り、ネビュラからも除名された裏切り者だ。仲間と思われるのはこちらとしても心外だな」
line = "「その女は<ruby>はぐれ魔女<rt>ヤーガ</rt></ruby>──森を去り、ネビュラからも除名された裏切り者だ。仲間と思われるのはこちらとしても心外だな」"

[[dialogue]]
speaker = "ソフィア"
# 「追い出された……魔女……そんな人が……」
line = "「追い出された……魔女……そんな人が……」"

[[dialogue]]
speaker = "セーラ"
# 「ていうか、超冷たい感じ」
line = "「ていうか、超冷たい感じ」"

[[dialogue]]
speaker = "リノ"
# 「そうそう。だから今はみんなの味方よ」
line = "「そうそう。だから今はみんなの味方よ」"

[[dialogue]]
speaker = "ニャリオン"
# 「で、でもニャ。どうして魔女たちと仲違いしちゃったのニャン……？」
line = "「で、でもニャ。どうして魔女たちと仲違いしちゃったのニャン……？」"

[[dialogue]]
speaker = "アイリーン"
# 「えっと……」
line = "「えっと……」"

[[dialogue]]
speaker = "カヤ"
# 「そういえば、原因については聞いてなかったかも……」
line = "「そういえば、原因については聞いてなかったかも……」"

[[dialogue]]
speaker = "unk"
# なぜ、母さんはセドナさんと──そして魔女たちと<ruby=たもと>袂</ruby>を分かってしまったのか。
line = "なぜ、母さんはセドナさんと──そして魔女たちと<ruby>袂<rt>たもと</rt></ruby>を分かってしまったのか。"

[[dialogue]]
speaker = "unk"
# その真相はセドナさんの口から語られた。
line = "その真相はセドナさんの口から語られた。"

[[dialogue]]
speaker = "セドナ"
# 「リノは──世界樹に封印されていた先代魔王の生まれ変わりを人間界へ持ち出した。組織にまったくの無断でな」
line = "「リノは──世界樹に封印されていた先代魔王の生まれ変わりを人間界へ持ち出した。組織にまったくの無断でな」"

[[dialogue]]
speaker = "アイリーン"
# 「！？」
line = "「！？」"

[[dialogue]]
speaker = "フィオナ"
# 「っ……魔王の生まれ変わり──それは……」
line = "「っ……魔王の生まれ変わり──それは……」"

[[dialogue]]
speaker = "セドナ"
# 「これは、つい最近まで判明していなかった事実だ。当初リノは、ただ組織への離反を行ったとして元老会から処理されていた」
line = "「これは、つい最近まで判明していなかった事実だ。当初リノは、ただ組織への離反を行ったとして元老会から処理されていた」"

[[dialogue]]
speaker = "セドナ"
# 「なぜなら先代魔王ラクシスの<ruby=みのしろ>身代</ruby>は……３０００年前より続く謎として伝えられていた」
line = "「なぜなら先代魔王ラクシスの<ruby>身代<rt>みのしろ</rt></ruby>は……３０００年前より続く謎として伝えられていた」"

[[dialogue]]
speaker = "アナ"
# 「確かに──現代でも謎とされていました。魔王をどう捉えるにしろ、その亡骸は未だ見つかっていないと」
line = "「確かに──現代でも謎とされていました。魔王をどう捉えるにしろ、その亡骸は未だ見つかっていないと」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ。星見家の古文書にも記されておりませんでした。抹消された歴史、ですね」
line = "「ええ。星見家の古文書にも記されておりませんでした。抹消された歴史、ですね」"

[[dialogue]]
speaker = "フィオナ"
# 「先代魔王の肉体は──魔女たちの領域に眠っていたのですね」
line = "「先代魔王の肉体は──魔女たちの領域に眠っていたのですね」"

[[dialogue]]
speaker = "セーラ"
# 「でも、それをリノさんが見つけて目覚めさせた──」
line = "「でも、それをリノさんが見つけて目覚めさせた──」"

[[dialogue]]
speaker = "リノ"
# 「少し違うわ。ただ、覚醒の時が近づいているのを、私だけが認識していたの」
line = "「少し違うわ。ただ、覚醒の時が近づいているのを、私だけが認識していたの」"

[[dialogue]]
speaker = "リノ"
# 「先代魔王は再誕の魔法を受けた。そうして３０００年越しに目覚めた彼は──魂だけを残して、記憶も知識も備えていない１人の少年に戻っていた」
line = "「先代魔王は再誕の魔法を受けた。そうして３０００年越しに目覚めた彼は──魂だけを残して、記憶も知識も備えていない１人の少年に戻っていた」"

[[dialogue]]
speaker = "リノ"
# 「いわば別人として、改めてこの世に生を受けたのよ。私が拾ったのはそんな状態の彼」
line = "「いわば別人として、改めてこの世に生を受けたのよ。私が拾ったのはそんな状態の彼」"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# 母さんの語る過去は……塔の教えてくれた事実と、何も違わなかった。
line = "母さんの語る過去は……塔の教えてくれた事実と、何も違わなかった。"

[[dialogue]]
speaker = "アイリーン"
# 「ですが──だとしたら、その少年というのはどこに？」
line = "「ですが──だとしたら、その少年というのはどこに？」"

[[dialogue]]
speaker = "セドナ"
# 「今、目の前にいるだろう？　ずいぶん立派に育て上げたものだ」
line = "「今、目の前にいるだろう？　ずいぶん立派に育て上げたものだ」"

[[dialogue]]
speaker = "アイリーン"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "マトイ"
# 「も、もしかして……？」
line = "「も、もしかして……？」"

[[dialogue]]
speaker = "unk"
# 全員の視線が俺へ集まる──
line = "全員の視線が俺へ集まる──"

[[dialogue]]
speaker = "unk"
# 先代魔王ラクシスの生まれ変わりとは、この、緋宮クロトに他ならなかった。
line = "先代魔王ラクシスの生まれ変わりとは、この、緋宮クロトに他ならなかった。"

[[dialogue]]
speaker = "ユウリ"
# 「うっそだろ……んじゃ、クロトが先代魔王本人ってことかよ！」
line = "「うっそだろ……んじゃ、クロトが先代魔王本人ってことかよ！」"

[[dialogue]]
speaker = "フィオナ"
# 「魔王の血統──では、確かにない。なるほど……私との違いは、そういうことでしたか」
line = "「魔王の血統──では、確かにない。なるほど……私との違いは、そういうことでしたか」"

[[dialogue]]
speaker = "ニャリオン"
# 「ど、道理で懐かしい雰囲気を感じるわけニャン！」
line = "「ど、道理で懐かしい雰囲気を感じるわけニャン！」"

[[dialogue]]
speaker = "クロト"
# 「俺もついさっき知ったばかりだ。塔を通じてな」
line = "「俺もついさっき知ったばかりだ。塔を通じてな」"

[[dialogue]]
speaker = "unk"
# 実感があるかどうかと言われれば、ない。
line = "実感があるかどうかと言われれば、ない。"

[[dialogue]]
speaker = "unk"
# だが──先代魔王の記憶を覗いた立ち場として、彼の想いを継いでやりたい気持ちはあった。
line = "だが──先代魔王の記憶を覗いた立ち場として、彼の想いを継いでやりたい気持ちはあった。"

[[dialogue]]
speaker = "セドナ"
# 「再誕の魔法を使ったのは当時の光の魔女。だが、その事実は近年に至るまで闇に葬られていた」
line = "「再誕の魔法を使ったのは当時の光の魔女。だが、その事実は近年に至るまで闇に葬られていた」"

[[dialogue]]
speaker = "クラウディア"
# 「先代か。大方、そのような契約を結んだのであろうな」
line = "「先代か。大方、そのような契約を結んだのであろうな」"

[[dialogue]]
speaker = "リノ"
# 「そうね。私がクロトを拾ったあの日……まだ、他に『再誕』の秘密に気づいていた魔女はいなかったと思う」
line = "「そうね。私がクロトを拾ったあの日……まだ、他に『再誕』の秘密に気づいていた魔女はいなかったと思う」"

[[dialogue]]
speaker = "セドナ"
# 「貴様は目ざとくも先代魔王の再誕の絡繰りを解き明かし、新たな身代を発見した。それはいい」
line = "「貴様は目ざとくも先代魔王の再誕の絡繰りを解き明かし、新たな身代を発見した。それはいい」"

[[dialogue]]
speaker = "セドナ"
# 「だが……それは本来、真っ先に組織へ報告すべき事案だ。なぜ無断で持ち去り、あまつさえ育てようとした？」
line = "「だが……それは本来、真っ先に組織へ報告すべき事案だ。なぜ無断で持ち去り、あまつさえ育てようとした？」"

[[dialogue]]
speaker = "リノ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "クロト"
# 「母さん……」
line = "「母さん……」"

[[dialogue]]
speaker = "unk"
# 俺にとっても思いもよらぬ過去だった。
line = "俺にとっても思いもよらぬ過去だった。"

[[dialogue]]
speaker = "unk"
# 母さんが俺を拾ったことで、他の魔女たちを裏切ることになっていたなんて。
line = "母さんが俺を拾ったことで、他の魔女たちを裏切ることになっていたなんて。"

[[dialogue]]
speaker = "リノ"
# 「だって……あなた達ネビュラは、彼を犠牲にしようとしていたでしょう？」
line = "「だって……あなた達ネビュラは、彼を犠牲にしようとしていたでしょう？」"

[[dialogue]]
speaker = "アイリーン"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "ソフィア"
# 「犠牲……」
line = "「犠牲……」"

[[dialogue]]
speaker = "セドナ"
# 「だったらなんだ？　一族の宿願を忘れたのかと聞いたはずだ、リノ。どんな事情があれ組織からの命令違反は重罪だ」
line = "「だったらなんだ？　一族の宿願を忘れたのかと聞いたはずだ、リノ。どんな事情があれ組織からの命令違反は重罪だ」"

[[dialogue]]
speaker = "リノ"
# 「私はそのやり方に賛同できなかった。このまま彼を連れ帰ったらどうなるのか、察してしまったからよ」
line = "「私はそのやり方に賛同できなかった。このまま彼を連れ帰ったらどうなるのか、察してしまったからよ」"

[[dialogue]]
speaker = "クラウディア"
# 「余が生まれる前の時代……か。ふむ」
line = "「余が生まれる前の時代……か。ふむ」"

[[dialogue]]
speaker = "リノ"
# 「ええ。私がクロトを見つけた当時──まだ、森にはクラウディア様が生まれていなかった」
line = "「ええ。私がクロトを見つけた当時──まだ、森にはクラウディア様が生まれていなかった」"

[[dialogue]]
speaker = "リノ"
# 「光の魔女が誕生するのは数百年か、あるいは数千年に一度の奇跡。必ずしも次のリクリエまでに生まれる保証はない」
line = "「光の魔女が誕生するのは数百年か、あるいは数千年に一度の奇跡。必ずしも次のリクリエまでに生まれる保証はない」"

[[dialogue]]
speaker = "リノ"
# 「だから……当時のネビュラは《光の魔女》には頼れなかった。そこで目をつけたのが、どこかに眠っているはずの先代魔王の亡骸よ」
line = "「だから……当時のネビュラは《光の魔女》には頼れなかった。そこで目をつけたのが、どこかに眠っているはずの先代魔王の亡骸よ」"

[[dialogue]]
speaker = "セーラ"
# 「先代魔王──ってのは、今の新星会長さんのことだよね。それを犠牲にしよう、ってことは……」
line = "「先代魔王──ってのは、今の新星会長さんのことだよね。それを犠牲にしよう、ってことは……」"

[[dialogue]]
speaker = "リノ"
# 「今とそう図式は変わらないわ。いわば、生け贄に用いられるはずだったの」
line = "「今とそう図式は変わらないわ。いわば、生け贄に用いられるはずだったの」"

[[dialogue]]
speaker = "リノ"
# 「グレート・ウォールの前身とも言える計画──『ヴォイド・プラン』のね」
line = "「グレート・ウォールの前身とも言える計画──『ヴォイド・プラン』のね」"

[[dialogue]]
speaker = "マトイ"
# 「生け贄……！」
line = "「生け贄……！」"

[[dialogue]]
speaker = "クロト"
# 「……初耳だ」
line = "「……初耳だ」"

[[dialogue]]
speaker = "セドナ"
# 「『ヴォイド・プラン』において、確かに先代魔王の亡骸は仮のリソースに含まれていた。実現しうるかはともかく、な」
line = "「『ヴォイド・プラン』において、確かに先代魔王の亡骸は仮のリソースに含まれていた。実現しうるかはともかく、な」"

[[dialogue]]
speaker = "リノ"
# 「私は何度も組織に言ったわ。もっと他に、三界すべてを救う方法があるはずだって」
line = "「私は何度も組織に言ったわ。もっと他に、三界すべてを救う方法があるはずだって」"

[[dialogue]]
speaker = "リノ"
# 「それに、何より──希少な魔王を消耗してしまうこと自体、とてつもないリスクを孕む行為よ」
line = "「それに、何より──希少な魔王を消耗してしまうこと自体、とてつもないリスクを孕む行為よ」"

[[dialogue]]
speaker = "unk"
# 母さんの懸念は正しいものだ。
line = "母さんの懸念は正しいものだ。"

[[dialogue]]
speaker = "unk"
# 魔王を魔王たらしめる因子は、元はといえば青年Ｓのいたオルタナティブ宇宙からもたらされたもの──
line = "魔王を魔王たらしめる因子は、元はといえば青年Ｓのいたオルタナティブ宇宙からもたらされたもの──"

[[dialogue]]
speaker = "unk"
# もし俺という存在がいなくなれば、二度とこの宇宙から生まれてくることはないだろう。
line = "もし俺という存在がいなくなれば、二度とこの宇宙から生まれてくることはないだろう。"

[[dialogue]]
speaker = "マトイ"
# 「じゃ、じゃあ……リノさんがいなかったら、緋宮くんはもうここにいなかったってこと……！？」
line = "「じゃ、じゃあ……リノさんがいなかったら、緋宮くんはもうここにいなかったってこと……！？」"

[[dialogue]]
speaker = "ニャリオン"
# 「ワ、ワケわかんなくなってきたニャン……！」
line = "「ワ、ワケわかんなくなってきたニャン……！」"

[[dialogue]]
speaker = "フィオナ"
# 「色々な思惑が……時を超えて交錯しあっていたようですね」
line = "「色々な思惑が……時を超えて交錯しあっていたようですね」"

[[dialogue]]
speaker = "クロト"
# 「ああ。でも俺は──母さんのおかげでこうして生かされた」
line = "「ああ。でも俺は──母さんのおかげでこうして生かされた」"

[[dialogue]]
speaker = "unk"
# 行方知れずだった先代魔王の身代は……ネビュラだけじゃない、もっと多くの勢力が狙っていたのかもしれない。
line = "行方知れずだった先代魔王の身代は……ネビュラだけじゃない、もっと多くの勢力が狙っていたのかもしれない。"

[[dialogue]]
speaker = "リノ"
# 「私はネビュラと相容れなかった。私の描く理想は、三界どれも欠かさずに、３０００年前と同じようにリクリエを撃退すること」
line = "「私はネビュラと相容れなかった。私の描く理想は、三界どれも欠かさずに、３０００年前と同じようにリクリエを撃退すること」"

[[dialogue]]
speaker = "マトイ"
# 「それって……」
line = "「それって……」"

[[dialogue]]
speaker = "リノ"
# 「ええ。星騎士に近いものだったから」
line = "「ええ。星騎士に近いものだったから」"

[[dialogue]]
speaker = "リノ"
# 「でもね、セドナ。本当は今の状況を望んでたわけじゃないのよ」
line = "「でもね、セドナ。本当は今の状況を望んでたわけじゃないのよ」"

[[dialogue]]
speaker = "セドナ"
# 「何……？」
line = "「何……？」"

[[dialogue]]
speaker = "リノ"
# 「クロトは昔から──外に出るたびモンスターに襲われるような子だった。この子の出自を考えれば無理もないことなんでしょうけど」
line = "「クロトは昔から──外に出るたびモンスターに襲われるような子だった。この子の出自を考えれば無理もないことなんでしょうけど」"

[[dialogue]]
speaker = "リノ"
# 「この時代に生まれたクロトは、魔王としての力を完全に失っていたわ。だから思ったの。この子は先代魔王とは違う。クロトは、クロトなんだって」
line = "「この時代に生まれたクロトは、魔王としての力を完全に失っていたわ。だから思ったの。この子は先代魔王とは違う。クロトは、クロトなんだって」"

[[dialogue]]
speaker = "リノ"
# 「だから……ふふ。親バカかもしれないけど──なるべく、危険には踏み入ってほしくなかった」
line = "「だから……ふふ。親バカかもしれないけど──なるべく、危険には踏み入ってほしくなかった」"

[[dialogue]]
speaker = "リノ"
# 「もし、この子の体質で、自らリクリエに遭遇するようなことがあったら……きっと無事ではいられないでしょうから」
line = "「もし、この子の体質で、自らリクリエに遭遇するようなことがあったら……きっと無事ではいられないでしょうから」"

[[dialogue]]
speaker = "クロト"
# 「母さん……」
line = "「母さん……」"

[[dialogue]]
speaker = "リノ"
# 「でも──血は争えないわね。クロトは結局、自分で世界を救うために立ち上がった」
line = "「でも──血は争えないわね。クロトは結局、自分で世界を救うために立ち上がった」"

[[dialogue]]
speaker = "unk"
# そうだ。俺はセイファート学園長との出会いを通じて、星騎士を志すようになるのだから。
line = "そうだ。俺はセイファート学園長との出会いを通じて、星騎士を志すようになるのだから。"

[[dialogue]]
speaker = "リノ"
# 「確かに今代のリクリエは過去のそれよりも強大で……何かを犠牲にしなくちゃ助からないのかもしれない」
line = "「確かに今代のリクリエは過去のそれよりも強大で……何かを犠牲にしなくちゃ助からないのかもしれない」"

[[dialogue]]
speaker = "リノ"
# 「だけど──前回のリクリエに打ち勝った魔王の系譜だって、間違いなく進化を遂げているのよ」
line = "「だけど──前回のリクリエに打ち勝った魔王の系譜だって、間違いなく進化を遂げているのよ」"

[[dialogue]]
speaker = "セドナ"
# 「……ふぅ」
line = "「……ふぅ」"

[[dialogue]]
speaker = "セドナ"
# 「そいつはわざわざネビュラの基地にまで出戻り──我々に嘆願した。機会をくれ、とな」
line = "「そいつはわざわざネビュラの基地にまで出戻り──我々に嘆願した。機会をくれ、とな」"

[[dialogue]]
speaker = "セドナ"
# 「それで？　可愛い我が子に希望を託すというのが、貴様のいう代案なのか？」
line = "「それで？　可愛い我が子に希望を託すというのが、貴様のいう代案なのか？」"

[[dialogue]]
speaker = "リノ"
# 「──それだけじゃないわ」
line = "「──それだけじゃないわ」"

[[dialogue]]
speaker = "リノ"
# 「私も……今日という日のために、準備はしてきたのよ」
line = "「私も……今日という日のために、準備はしてきたのよ」"

[[dialogue]]
speaker = "アイリーン"
# 「……？　なんですか──？」
line = "「……？　なんですか──？」"

[[dialogue]]
speaker = "unk"
# 母さんが取り出したのは一辺がノート程度の立方体だった。
line = "母さんが取り出したのは一辺がノート程度の立方体だった。"

[[dialogue]]
speaker = "unk"
# そのキューブは、それ自体が浮力をもって滞空し、また神々しい<ruby=こんじき>金色</ruby>の光を放ち始める。
line = "そのキューブは、それ自体が浮力をもって滞空し、また神々しい<ruby>金色<rt>こんじき</rt></ruby>の光を放ち始める。"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャ、ニャんニャあれは……？」
line = "「ニャ、ニャんニャあれは……？」"

[[dialogue]]
speaker = "ルリエル"
# 「おっきいサイコロみたいです──ってあれ？　なんか見覚えがあるような……？」
line = "「おっきいサイコロみたいです──ってあれ？　なんか見覚えがあるような……？」"

[[dialogue]]
speaker = "ユウリ"
# 「？　そうか……？」
line = "「？　そうか……？」"

[[dialogue]]
speaker = "アナ"
# 「！　それは──もしや、<ruby=せいていえん>聖庭園</ruby>に秘されているという『シエルの<ruby=はこ>筐</ruby>』では？」
line = "「！　それは──もしや、<ruby>聖庭園<rt>せいていえん</rt></ruby>に秘されているという『シエルの<ruby>筐<rt>はこ</rt></ruby>』では？」"

[[dialogue]]
speaker = "リノ"
# 「ええ。無理を言って、中身はカラにしてもらったけどね」
line = "「ええ。無理を言って、中身はカラにしてもらったけどね」"

[[dialogue]]
speaker = "ルリエル"
# 「シ、シエルの筐！？」
line = "「シ、シエルの筐！？」"

[[dialogue]]
speaker = "ユウリ"
# 「知ってんのか、ルリエル」
line = "「知ってんのか、ルリエル」"

[[dialogue]]
speaker = "ルリエル"
# 「天界ではおとぎ話でも伝えられている伝説のアイテムです──天界にまつわる災いがいくつも封印されていると！」
line = "「天界ではおとぎ話でも伝えられている伝説のアイテムです──天界にまつわる災いがいくつも封印されていると！」"

[[dialogue]]
speaker = "ルリエル"
# 「で、ですが、本物が実在しているだなんて……」
line = "「で、ですが、本物が実在しているだなんて……」"

[[dialogue]]
speaker = "アナ"
# 「私も驚きです。聖庭園で厳重に管理されていると聞いていましたが……」
line = "「私も驚きです。聖庭園で厳重に管理されていると聞いていましたが……」"

[[dialogue]]
speaker = "unk"
# 母さんが持ってきたのは、どうやら天界で知らぬものはいないほどの宝だったらしく。
line = "母さんが持ってきたのは、どうやら天界で知らぬものはいないほどの宝だったらしく。"

[[dialogue]]
speaker = "クロト"
# 「母さん。どうしてそんなものを──」
line = "「母さん。どうしてそんなものを──」"

[[dialogue]]
speaker = "リノ"
# 「これは天界のリガルタ老から譲り受けたもの。一時的にだけどね」
line = "「これは天界のリガルタ老から譲り受けたもの。一時的にだけどね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「リガルタ──あれ、これもどっかで聞いたような……？」
line = "「リガルタ──あれ、これもどっかで聞いたような……？」"

[[dialogue]]
speaker = "フィオナ"
# 「確か、塔の中で聞いた──」
line = "「確か、塔の中で聞いた──」"

[[dialogue]]
speaker = "unk"
# 『天界の天使──リガルタ。聖庭園の長老として知られる彼ですが、魔王の血であることは古くより悟られぬよう暮らしているようです』
line = "『天界の天使──リガルタ。聖庭園の長老として知られる彼ですが、魔王の血であることは古くより悟られぬよう暮らしているようです』"

[[dialogue]]
speaker = "unk"
# あれは……フィオナが最たる魔王候補として告げられた時だ。
line = "あれは……フィオナが最たる魔王候補として告げられた時だ。"

[[dialogue]]
speaker = "unk"
# 三界に散っているという『魔王の血統』──そのうちの１人として、その名が挙げられていたはず。
line = "三界に散っているという『魔王の血統』──そのうちの１人として、その名が挙げられていたはず。"

[[dialogue]]
speaker = "リノ"
# 「当初、私はあなた達と同じように先代魔王がリクリエを討つキーになると考えた。でもクロトを育てていくうちに、この子１人に背負わせるわけにはいかないと思った」
line = "「当初、私はあなた達と同じように先代魔王がリクリエを討つキーになると考えた。でもクロトを育てていくうちに、この子１人に背負わせるわけにはいかないと思った」"

[[dialogue]]
speaker = "リノ"
# 「だから私は──三界に散らばっている、他の魔王の血筋をあたった」
line = "「だから私は──三界に散らばっている、他の魔王の血筋をあたった」"

[[dialogue]]
speaker = "リノ"
# 「そうして何度も交渉を重ねて譲り受けたの。実際、彼は天界でも姿を忍んでいたから見つけるのが大変だったけれど」
line = "「そうして何度も交渉を重ねて譲り受けたの。実際、彼は天界でも姿を忍んでいたから見つけるのが大変だったけれど」"

[[dialogue]]
speaker = "セドナ"
# 「なるほど。それで──貴様はどうするつもりだ」
line = "「なるほど。それで──貴様はどうするつもりだ」"

[[dialogue]]
speaker = "リノ"
# 「私の目的はひとつ。このシエルの筐に──『使徒の仮面』を封印する」
line = "「私の目的はひとつ。このシエルの筐に──『使徒の仮面』を封印する」"

[[dialogue]]
speaker = "フィオナ"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "ニャリオン"
# 「か、仮面をニャ！　でも確かに、それができればニャ……！」
line = "「か、仮面をニャ！　でも確かに、それができればニャ……！」"

[[dialogue]]
speaker = "unk"
# リクリエの全力が集約されるアポロ──そのアポロを使徒化させる仮面──いわば物体化した元凶。
line = "リクリエの全力が集約されるアポロ──そのアポロを使徒化させる仮面──いわば物体化した元凶。"

[[dialogue]]
speaker = "unk"
# それを封印することができたなら、確かにこの危機は乗り越えられる。
line = "それを封印することができたなら、確かにこの危機は乗り越えられる。"

[[dialogue]]
speaker = "マトイ"
# 「それに……お姉さんも助かるかも！」
line = "「それに……お姉さんも助かるかも！」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふ。確かに私たちの味方ね」
line = "「ふふ。確かに私たちの味方ね」"

[[dialogue]]
speaker = "セドナ"
# 「肝心の『使徒』まで向かうのにどうするという？」
line = "「肝心の『使徒』まで向かうのにどうするという？」"

[[dialogue]]
speaker = "リノ"
# 「私が行くわ。魔力を使い果たしてでも」
line = "「私が行くわ。魔力を使い果たしてでも」"

[[dialogue]]
speaker = "カヤ"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "クロト"
# （こんな母さんは──初めて見る──）
line = "（こんな母さんは──初めて見る──）"

[[dialogue]]
speaker = "unk"
# 母さんからみなぎる魔力は、セドナさんにも引けを取らないものだった。
line = "母さんからみなぎる魔力は、セドナさんにも引けを取らないものだった。"

[[dialogue]]
speaker = "リノ"
# 「実を言えばね。こうして、魔王の血統をあたっていた時……彼女にも会ったことがあるのよ。アポロ──じゃないわね、星見家の長女さんに」
line = "「実を言えばね。こうして、魔王の血統をあたっていた時……彼女にも会ったことがあるのよ。アポロ──じゃないわね、星見家の長女さんに」"

[[dialogue]]
speaker = "フィオナ"
# 「姉さんと──」
line = "「姉さんと──」"

[[dialogue]]
speaker = "unk"
# ──向こうは覚えていないでしょうけど、と母さんはつけ加えて。
line = "──向こうは覚えていないでしょうけど、と母さんはつけ加えて。"

[[dialogue]]
speaker = "セドナ"
# 「……本気か」
line = "「……本気か」"

[[dialogue]]
speaker = "リノ"
# 「ええ。あなた達がどれだけ止めても──私は彼女のもとへ向かい、この『<ruby=はこ>筐</ruby>』を試させてもらう」
line = "「ええ。あなた達がどれだけ止めても──私は彼女のもとへ向かい、この『<ruby>筐<rt>はこ</rt></ruby>』を試させてもらう」"

[[dialogue]]
speaker = "リノ"
# 「もし、グレート・ウォールを実行したいのなら……私の死に様を見届けてからにすることね」
line = "「もし、グレート・ウォールを実行したいのなら……私の死に様を見届けてからにすることね」"

[[dialogue]]
speaker = "セドナ"
# 「承服しかねる。星騎士どもが弱体化している今、魔力を使えるだけで貴重な人材だ。<ruby=ヤーガ>はぐれ魔女</ruby>とはいえ、我々の計画に従って動いてもらう」
line = "「承服しかねる。星騎士どもが弱体化している今、魔力を使えるだけで貴重な人材だ。<ruby>はぐれ魔女<rt>ヤーガ</rt></ruby>とはいえ、我々の計画に従って動いてもらう」"

[[dialogue]]
speaker = "リノ"
# 「優しいのね。無駄死にさせてくれないなんて」
line = "「優しいのね。無駄死にさせてくれないなんて」"

[[dialogue]]
speaker = "セドナ"
# 「愚かな。ここまで言ってもわからんとは」
line = "「愚かな。ここまで言ってもわからんとは」"

[[dialogue]]
speaker = "unk"
# にらみ合う２人の魔女。
line = "にらみ合う２人の魔女。"

[[dialogue]]
speaker = "unk"
# 誰にも冒せない静寂が、一瞬その場を支配して……
line = "誰にも冒せない静寂が、一瞬その場を支配して……"
