[[dialogue]]
speaker = "unk"
# 第１話,時期はずれの転入生,B
line = "第１話,時期はずれの転入生,B"

[[dialogue]]
speaker = "unk"
# ──流星市国。
line = "──流星市国。"

[[dialogue]]
speaker = "unk"
# 東京都内に位置し、以来３０００年の歴史を誇る独立国家。
line = "東京都内に位置し、以来３０００年の歴史を誇る独立国家。"

[[dialogue]]
speaker = "unk"
# 面積こそ小規模ながら由緒正しいこの国は、世界に滅亡をもたらす脅威“リクリエ”問題の総本山として知られている。
line = "面積こそ小規模ながら由緒正しいこの国は、世界に滅亡をもたらす脅威“リクリエ”問題の総本山として知られている。"

[[dialogue]]
speaker = "unk"
# なぜなら流星市国は、３０００年前の“リクリエ”を決着させた特異点──
line = "なぜなら流星市国は、３０００年前の“リクリエ”を決着させた特異点──"

[[dialogue]]
speaker = "unk"
# そして今、そんな流星市国の中心には。
line = "そして今、そんな流星市国の中心には。"

[[dialogue]]
speaker = "unk"
# 『流星学園』『新星学園』という──世界の内外にその名を轟かせる、二つの学園が存在していた。
line = "『流星学園』『新星学園』という──世界の内外にその名を轟かせる、二つの学園が存在していた。"

[[dialogue]]
speaker = "クロト"
# 「……緋宮クロトです。これから<b>新星</b>学園の生徒として、みんなと仲良くやっていきたいと思います──よろしくお願いします」
line = "「……緋宮クロトです。これから<b>新星</b>学園の生徒として、みんなと仲良くやっていきたいと思います──よろしくお願いします」"

[[dialogue]]
speaker = "unk"
# 転入初日──俺はクラスへの挨拶を無難な言葉で締めくくる。
line = "転入初日──俺はクラスへの挨拶を無難な言葉で締めくくる。"

[[dialogue]]
speaker = "unk"
# 変に奇をてらって悪目立ちするのも避けたい。
line = "変に奇をてらって悪目立ちするのも避けたい。"

[[dialogue]]
speaker = "トワ先生"
# 「ぱちぱちぱち～！　いい挨拶だったねぇ、ほらみんなも拍手拍手ぅ～！」
line = "「ぱちぱちぱち～！　いい挨拶だったねぇ、ほらみんなも拍手拍手ぅ～！」"

[[dialogue]]
speaker = "unk"
# 担任の先生はさらなるボルテージを要求していた。
line = "担任の先生はさらなるボルテージを要求していた。"

[[dialogue]]
speaker = "unk"
# まばらだった拍手がだんだん大きくなる。
line = "まばらだった拍手がだんだん大きくなる。"

[[dialogue]]
speaker = "トワ先生"
# 「まだまだ！　ガッツが足りてないよ、ほら緋宮くんも拍手拍手ぅ～！」
line = "「まだまだ！　ガッツが足りてないよ、ほら緋宮くんも拍手拍手ぅ～！」"

[[dialogue]]
speaker = "クロト"
# 「は、はあ……」
line = "「は、はあ……」"

[[dialogue]]
speaker = "unk"
# 無理やり手首を掴まれ、拍手させられる。俺は誰を祝っているのだろうか。
line = "無理やり手首を掴まれ、拍手させられる。俺は誰を祝っているのだろうか。"

[[dialogue]]
speaker = "マトイ"
# 「あのー、トワちゃん先生？　緋宮くんも戸惑ってるみたいですけど……」
line = "「あのー、トワちゃん先生？　緋宮くんも戸惑ってるみたいですけど……」"

[[dialogue]]
speaker = "トワ先生"
# 「おっと、こりゃ失礼」
line = "「おっと、こりゃ失礼」"

[[dialogue]]
speaker = "unk"
# 両手を放され、強制拍手から解放される。
line = "両手を放され、強制拍手から解放される。"

[[dialogue]]
speaker = "unk"
# とりあえず、先生が陽気な人だというのは伝わった。
line = "とりあえず、先生が陽気な人だというのは伝わった。"

[[dialogue]]
speaker = "トワ先生"
# 「とにかくっ。今日からみんな、新星学園２年Ｂ組に──新たな仲間が加わったよ！　仲良くしてあげてね！」
line = "「とにかくっ。今日からみんな、新星学園２年Ｂ組に──新たな仲間が加わったよ！　仲良くしてあげてね！」"

[[dialogue]]
speaker = "トワ先生"
# 「緋宮くんの席は……あそこ！　わからないことがあったら隣のマトイちゃんに聞いてね。いいよね？」
line = "「緋宮くんの席は……あそこ！　わからないことがあったら隣のマトイちゃんに聞いてね。いいよね？」"

[[dialogue]]
speaker = "マトイ"
# 「はい。構いません」
line = "「はい。構いません」"

[[dialogue]]
speaker = "unk"
# マトイちゃん。
line = "マトイちゃん。"

[[dialogue]]
speaker = "unk"
# そう呼ばれた女の子は、明らかに見覚えのある顔をしていた。
line = "そう呼ばれた女の子は、明らかに見覚えのある顔をしていた。"

[[dialogue]]
speaker = "クロト"
# 「（さっきの……やっぱり、新星学園の生徒だったんだな）」
line = "「（さっきの……やっぱり、新星学園の生徒だったんだな）」"

[[dialogue]]
speaker = "unk"
# あの時と今とでは、格好こそ様変わりしているけれど。
line = "あの時と今とでは、格好こそ様変わりしているけれど。"

[[dialogue]]
speaker = "unk"
# 向こうも俺のことを認識してくれたようだった。
line = "向こうも俺のことを認識してくれたようだった。"

[[dialogue]]
speaker = "クロト"
# 「……よろしく」
line = "「……よろしく」"

[[dialogue]]
speaker = "マトイ"
# 「うん、よろしく。私は詠野マトイ──また会ったね」
line = "「うん、よろしく。私は詠野マトイ──また会ったね」"

[[dialogue]]
speaker = "unk"
# 席につく。
line = "席につく。"

[[dialogue]]
speaker = "unk"
# 転入生へのざわめきは、もうとっくにピークをすぎた──
line = "転入生へのざわめきは、もうとっくにピークをすぎた──"

[[dialogue]]
speaker = "クラスの女子Ａ"
# 「（転入生って……この時期に……？）」
line = "「（転入生って……この時期に……？）」"

[[dialogue]]
speaker = "クラスの女子Ｂ"
# 「（そもそも、うちの学園で転入生なんて……聞いたことあったっけ……？）」
line = "「（そもそも、うちの学園で転入生なんて……聞いたことあったっけ……？）」"

[[dialogue]]
speaker = "unk"
# ──なんてことはなかった。
line = "──なんてことはなかった。"

[[dialogue]]
speaker = "unk"
# クラス内のざわめきは未だ落ち着かず、そこには俺への好奇心というより、転入生そのものへの物珍しさも混じっていた。
line = "クラス内のざわめきは未だ落ち着かず、そこには俺への好奇心というより、転入生そのものへの物珍しさも混じっていた。"

[[dialogue]]
speaker = "トワ先生"
# 「あーはいはいみんな静かに！　ホームルームは終わり、次は星騎士学の時間でしょ！　教頭先生が待ってるよ！」
line = "「あーはいはいみんな静かに！　ホームルームは終わり、次は星騎士学の時間でしょ！　教頭先生が待ってるよ！」"

[[dialogue]]
speaker = "クロト"
# 「星騎士学……？」
line = "「星騎士学……？」"

[[dialogue]]
speaker = "マトイ"
# 「一時間目の授業。ついてきて──アリーナまで案内してあげる」
line = "「一時間目の授業。ついてきて──アリーナまで案内してあげる」"

[[dialogue]]
speaker = "教頭"
# 「──今。世界は大きなうねりを迎え、３０００年来の危機が再びすぐそこまで迫っている」
line = "「──今。世界は大きなうねりを迎え、３０００年来の危機が再びすぐそこまで迫っている」"

[[dialogue]]
speaker = "unk"
# そうして詠野さんに連れてこられたのは大きなホールだった。
line = "そうして詠野さんに連れてこられたのは大きなホールだった。"

[[dialogue]]
speaker = "unk"
# なんでも星騎士学は週に一度の合同授業らしく、他クラスの生徒も一堂に会しているとわかる。
line = "なんでも星騎士学は週に一度の合同授業らしく、他クラスの生徒も一堂に会しているとわかる。"

[[dialogue]]
speaker = "教頭"
# 「急変する気候。隆起する大地。街中に湧くモンスター。これらは全てその兆候だ」
line = "「急変する気候。隆起する大地。街中に湧くモンスター。これらは全てその兆候だ」"

[[dialogue]]
speaker = "unk"
# 教頭先生──らしき人の話を聞く。
line = "教頭先生──らしき人の話を聞く。"

[[dialogue]]
speaker = "unk"
# やたら鍛えられた体つきに、つい目がいってしまいそうになるが……。
line = "やたら鍛えられた体つきに、つい目がいってしまいそうになるが……。"

[[dialogue]]
speaker = "教頭"
# 「つまりは──世界滅亡の超常現象。通称『リクリエ』だ」
line = "「つまりは──世界滅亡の超常現象。通称『リクリエ』だ」"

[[dialogue]]
speaker = "教頭"
# 「人間界だけではない──魔界も、天界も。リクリエはすべてを消滅させうる最大の脅威」
line = "「人間界だけではない──魔界も、天界も。リクリエはすべてを消滅させうる最大の脅威」"

[[dialogue]]
speaker = "教頭"
# 「──しかし！　人類は３０００年前、確かにそれを退けた。ならば現代の我々にも不可能な道理はないッ」
line = "「──しかし！　人類は３０００年前、確かにそれを退けた。ならば現代の我々にも不可能な道理はないッ」"

[[dialogue]]
speaker = "unk"
# 簡単に言えばこうだ。
line = "簡単に言えばこうだ。"

[[dialogue]]
speaker = "unk"
# 『リクリエ』と呼ばれる世界の破滅を、人類は３０００年前に一度跳ね返した。
line = "『リクリエ』と呼ばれる世界の破滅を、人類は３０００年前に一度跳ね返した。"

[[dialogue]]
speaker = "unk"
# しかし、その揺り戻しとでも言うべき強大な波が、この森羅暦３００２年に再びやってきている。
line = "しかし、その揺り戻しとでも言うべき強大な波が、この森羅暦３００２年に再びやってきている。"

[[dialogue]]
speaker = "教頭"
# 「かつての選ばれし戦士『クルセイダース』は<ruby=やくさい>厄災</ruby>を撃退した」
line = "「かつての選ばれし戦士『クルセイダース』は<ruby>厄災<rt>やくさい</rt></ruby>を撃退した」"

[[dialogue]]
speaker = "教頭"
# 「しかしその代償として、彼らの用いていた『霊力』は永遠にこの世界から失われてしまった……」
line = "「しかしその代償として、彼らの用いていた『霊力』は永遠にこの世界から失われてしまった……」"

[[dialogue]]
speaker = "教頭"
# 「ゆえにこそ、今！　星力という新たなる加護を女神様より授かりし若き戦士──すなわち、君たちのような<ruby=スターナイト>星騎士</ruby>が求められているのである」
line = "「ゆえにこそ、今！　星力という新たなる加護を女神様より授かりし若き戦士──すなわち、君たちのような<ruby>星騎士<rt>スターナイト</rt></ruby>が求められているのである」"

[[dialogue]]
speaker = "unk"
# ３０００年来の滅亡の危機。
line = "３０００年来の滅亡の危機。"

[[dialogue]]
speaker = "unk"
# かつてのリクリエを退けたクルセイダースに代わり、厄災に抗うべく現れたのが<ruby=スターナイト>星騎士</ruby>と言われていた。
line = "かつてのリクリエを退けたクルセイダースに代わり、厄災に抗うべく現れたのが<ruby>星騎士<rt>スターナイト</rt></ruby>と言われていた。"

[[dialogue]]
speaker = "unk"
# 世界の終焉に抗う戦士──
line = "世界の終焉に抗う戦士──"

[[dialogue]]
speaker = "unk"
# こうしていざ直々にその使命を告げられると、武者震いじみた緊張感が湧き上がってきた。
line = "こうしていざ直々にその使命を告げられると、武者震いじみた緊張感が湧き上がってきた。"

[[dialogue]]
speaker = "unk"
# ……それと同時に、まったく別ベクトルの震えも。
line = "……それと同時に、まったく別ベクトルの震えも。"

[[dialogue]]
speaker = "クロト"
# 「（もう俺も、星騎士の一員なんだ……そうか）」
line = "「（もう俺も、星騎士の一員なんだ……そうか）」"

[[dialogue]]
speaker = "マトイ"
# 「（？　どうかした……？）」
line = "「（？　どうかした……？）」"

[[dialogue]]
speaker = "unk"
# マトイの声で我に返る。震えを気づかれないように止めて、小声で返す。
line = "マトイの声で我に返る。震えを気づかれないように止めて、小声で返す。"

[[dialogue]]
speaker = "クロト"
# 「（いや……俺も今日から戦うことになるんだって、実感してたところ）」
line = "「（いや……俺も今日から戦うことになるんだって、実感してたところ）」"

[[dialogue]]
speaker = "unk"
# モンスターにただ襲われる日々。それを変えたくて、今日まで頑張ってきた。
line = "モンスターにただ襲われる日々。それを変えたくて、今日まで頑張ってきた。"

[[dialogue]]
speaker = "unk"
# 普通の学校に通いながらのバイト生活や独学によるトレーニングは、目が回りそうな毎日だったけれど……
line = "普通の学校に通いながらのバイト生活や独学によるトレーニングは、目が回りそうな毎日だったけれど……"

[[dialogue]]
speaker = "unk"
# ああして貯めた入学資金で今日この日を迎えられて、本当によかったと俺はしみじみ思っていた。
line = "ああして貯めた入学資金で今日この日を迎えられて、本当によかったと俺はしみじみ思っていた。"

[[dialogue]]
speaker = "マトイ"
# 「（……ふふ。変なの。そのために入ってきたんでしょう？）」
line = "「（……ふふ。変なの。そのために入ってきたんでしょう？）」"

[[dialogue]]
speaker = "クロト"
# 「（ああ。だから、嬉しいことなんだけどさ）」
line = "「（ああ。だから、嬉しいことなんだけどさ）」"

[[dialogue]]
speaker = "unk"
# その後も、リクリエ問題に関する教頭先生の話は続き……
line = "その後も、リクリエ問題に関する教頭先生の話は続き……"

[[dialogue]]
speaker = "unk"
# 俺にとって初となる授業は、それを夢中に聞いているだけで終わった。
line = "俺にとって初となる授業は、それを夢中に聞いているだけで終わった。"

[[dialogue]]
speaker = "クロト"
# 「……ためになる話だった。これが新星学園か……」
line = "「……ためになる話だった。これが新星学園か……」"

[[dialogue]]
speaker = "マトイ"
# 「教頭先生の話をあそこまで熱心に聞ける人は珍しいかも。聞くだけの授業は、どうしても眠くなっちゃうから」
line = "「教頭先生の話をあそこまで熱心に聞ける人は珍しいかも。聞くだけの授業は、どうしても眠くなっちゃうから」"

[[dialogue]]
speaker = "クロト"
# 「詠野さんだってちゃんとノートを取ってただろ」
line = "「詠野さんだってちゃんとノートを取ってただろ」"

[[dialogue]]
speaker = "マトイ"
# 「私はね。あと、マトイでいいから。みんなそう呼ぶし」
line = "「私はね。あと、マトイでいいから。みんなそう呼ぶし」"

[[dialogue]]
speaker = "unk"
# 名前で呼ぶ許可をもらった。
line = "名前で呼ぶ許可をもらった。"

[[dialogue]]
speaker = "unk"
# そこでふと、初対面の時を思い出す。
line = "そこでふと、初対面の時を思い出す。"

[[dialogue]]
speaker = "クロト"
# 「そう言えば……さっきはありがとう。助かった」
line = "「そう言えば……さっきはありがとう。助かった」"

[[dialogue]]
speaker = "マトイ"
# 「？　アリーナに案内したこと？」
line = "「？　アリーナに案内したこと？」"

[[dialogue]]
speaker = "クロト"
# 「そっちじゃなくて──今朝の件だよ。町が襲われてた時、飛んできてくれただろ」
line = "「そっちじゃなくて──今朝の件だよ。町が襲われてた時、飛んできてくれただろ」"

[[dialogue]]
speaker = "マトイ"
# 「ああ……あのこと」
line = "「ああ……あのこと」"

[[dialogue]]
speaker = "unk"
# 通学路に湧いていたモンスターの群れ。
line = "通学路に湧いていたモンスターの群れ。"

[[dialogue]]
speaker = "unk"
# あれも、教頭先生の言っていた“リクリエ接近の予兆”──その現象に違いない。
line = "あれも、教頭先生の言っていた“リクリエ接近の予兆”──その現象に違いない。"

[[dialogue]]
speaker = "マトイ"
# 「あはは……気にしなくていいよ。市街地の保護は星徒会の立派な役目だし」
line = "「あはは……気にしなくていいよ。市街地の保護は星徒会の立派な役目だし」"

[[dialogue]]
speaker = "クロト"
# 「と……そうだ。あの小さい子にもらったこれ、返すよ」
line = "「と……そうだ。あの小さい子にもらったこれ、返すよ」"

[[dialogue]]
speaker = "unk"
# そう言って、俺はポケットにしまっていた変身アイテムを取り出した。
line = "そう言って、俺はポケットにしまっていた変身アイテムを取り出した。"

[[dialogue]]
speaker = "クロト"
# 「これのおかげで変身もできて、普段の俺よりずっと力を発揮できたよ」
line = "「これのおかげで変身もできて、普段の俺よりずっと力を発揮できたよ」"

[[dialogue]]
speaker = "マトイ"
# 「あ──ううん！　それはもう緋宮くんのセレスティアだから、もらっていいんだよ」
line = "「あ──ううん！　それはもう緋宮くんのセレスティアだから、もらっていいんだよ」"

[[dialogue]]
speaker = "クロト"
# 「え……そうなのか」
line = "「え……そうなのか」"

[[dialogue]]
speaker = "マトイ"
# 「そうそう。これはね、新星学園の生徒一人ひとりに与えられる……私たちが星騎士に変身するための大事な道具なの」
line = "「そうそう。これはね、新星学園の生徒一人ひとりに与えられる……私たちが星騎士に変身するための大事な道具なの」"

[[dialogue]]
speaker = "マトイ"
# 「でも、ホントなら星徒会長から直々に伝授されるはずなんだけど……アナはどうして緋宮くんのを持ってたんだろ？」
line = "「でも、ホントなら星徒会長から直々に伝授されるはずなんだけど……アナはどうして緋宮くんのを持ってたんだろ？」"

[[dialogue]]
speaker = "unk"
# あのピンチに駆けつけてきてくれたのはイレギュラーなようだった。転入生だから、手順が特殊だったのだろうか？
line = "あのピンチに駆けつけてきてくれたのはイレギュラーなようだった。転入生だから、手順が特殊だったのだろうか？"

[[dialogue]]
speaker = "クロト"
# 「ともかくこれは俺のものっていうなら受け取っておこう」
line = "「ともかくこれは俺のものっていうなら受け取っておこう」"

[[dialogue]]
speaker = "マトイ"
# 「そうそう。むしろ、セレスティアをもらってないのに戦おうとしてた方がすごいよ」
line = "「そうそう。むしろ、セレスティアをもらってないのに戦おうとしてた方がすごいよ」"

[[dialogue]]
speaker = "unk"
# 苦笑されてしまった。
line = "苦笑されてしまった。"

[[dialogue]]
speaker = "unk"
# それは、自慢じゃないが、歩いているだけでもモンスターと出会ってしまう俺の体質のせいだった。
line = "それは、自慢じゃないが、歩いているだけでもモンスターと出会ってしまう俺の体質のせいだった。"

[[dialogue]]
speaker = "クロト"
# 「そうは言っても今朝の戦いだって、俺なんかよりマトイの方がよっぽど……」
line = "「そうは言っても今朝の戦いだって、俺なんかよりマトイの方がよっぽど……」"

[[dialogue]]
speaker = "教頭"
# 「はっはっはっ！　詠野くんは優秀だからねえ、でも賞賛は素直に受け止めておくべきじゃないかなあ」
line = "「はっはっはっ！　詠野くんは優秀だからねえ、でも賞賛は素直に受け止めておくべきじゃないかなあ」"

[[dialogue]]
speaker = "クロト"
# 「びっくりした」
line = "「びっくりした」"

[[dialogue]]
speaker = "unk"
# 振り返ると、そこには大柄の男性が呵々と大口を開けて笑っていた。
line = "振り返ると、そこには大柄の男性が呵々と大口を開けて笑っていた。"

[[dialogue]]
speaker = "マトイ"
# 「教頭先生……どうかされましたか」
line = "「教頭先生……どうかされましたか」"

[[dialogue]]
speaker = "教頭"
# 「うむ。何、期待の転入生くんをひと目見てみようと思ってね。果たしてどれほどの筋肉を引っさげてきたのかと！」
line = "「うむ。何、期待の転入生くんをひと目見てみようと思ってね。果たしてどれほどの筋肉を引っさげてきたのかと！」"

[[dialogue]]
speaker = "クロト"
# 「緋宮クロトです」
line = "「緋宮クロトです」"

[[dialogue]]
speaker = "教頭"
# 「むむむっ！？　思いのほか線の細い男子……これではリンゴも潰せまい。私のように筋肉をつけたまえ、君もこの上腕二頭筋が羨ましいだろう？」
line = "「むむむっ！？　思いのほか線の細い男子……これではリンゴも潰せまい。私のように筋肉をつけたまえ、君もこの上腕二頭筋が羨ましいだろう？」"

[[dialogue]]
speaker = "クロト"
# 「みんなより遅れたスタートですが、早く一人前の星騎士として戦えるよう頑張ります」
line = "「みんなより遅れたスタートですが、早く一人前の星騎士として戦えるよう頑張ります」"

[[dialogue]]
speaker = "マトイ"
# 「教頭先生の筋肉ハラスメントを自然に受け流してる……ちょっとすごいかも」
line = "「教頭先生の筋肉ハラスメントを自然に受け流してる……ちょっとすごいかも」"

[[dialogue]]
speaker = "unk"
# アリーナの中心にいた時よりも、実際に相対すると圧を感じるお方だった。
line = "アリーナの中心にいた時よりも、実際に相対すると圧を感じるお方だった。"

[[dialogue]]
speaker = "教頭"
# 「ふむ。しかし、内に秘めたるパワーも感じる──見た目で判断するのは早計か」
line = "「ふむ。しかし、内に秘めたるパワーも感じる──見た目で判断するのは早計か」"

[[dialogue]]
speaker = "教頭"
# 「何にせよ、同じクラスに星徒会の詠野くんがいるなら安心だろう」
line = "「何にせよ、同じクラスに星徒会の詠野くんがいるなら安心だろう」"

[[dialogue]]
speaker = "クロト"
# 「ええ。今朝も助けてもらいました」
line = "「ええ。今朝も助けてもらいました」"

[[dialogue]]
speaker = "マトイ"
# 「別に大したことはしていませんが……」
line = "「別に大したことはしていませんが……」"

[[dialogue]]
speaker = "unk"
# 教頭先生の言葉からは、マトイへの厚い信頼感がうかがえた。
line = "教頭先生の言葉からは、マトイへの厚い信頼感がうかがえた。"

[[dialogue]]
speaker = "教頭"
# 「謙遜することはない。我々教師も星徒会を信頼している。市内の危機に柔軟に動けるのも、彼女たちの存在あってこそだ」
line = "「謙遜することはない。我々教師も星徒会を信頼している。市内の危機に柔軟に動けるのも、彼女たちの存在あってこそだ」"

[[dialogue]]
speaker = "クロト"
# 「……星徒会は、やはり特別なんですね」
line = "「……星徒会は、やはり特別なんですね」"

[[dialogue]]
speaker = "教頭"
# 「もちろんだ。新星の<b>星徒会</b>は、ただの<b>生徒会</b>にあらず……名実ともに選ばれしエリートにより構成された組織」
line = "「もちろんだ。新星の<b>星徒会</b>は、ただの<b>生徒会</b>にあらず……名実ともに選ばれしエリートにより構成された組織」"

[[dialogue]]
speaker = "unk"
# 教頭先生は、新星学園における生徒会の立場について語った。
line = "教頭先生は、新星学園における生徒会の立場について語った。"

[[dialogue]]
speaker = "unk"
# 全学生たちの代表──その立場は取りも直さず、<ruby=スターナイト>星騎士</ruby>たちの代表ともなりえること。
line = "全学生たちの代表──その立場は取りも直さず、<ruby>星騎士<rt>スターナイト</rt></ruby>たちの代表ともなりえること。"

[[dialogue]]
speaker = "unk"
# 彼らはその肩書きに違わぬ実力を持ち、また、その身分に応じた権力を与えられているとも。
line = "彼らはその肩書きに違わぬ実力を持ち、また、その身分に応じた権力を与えられているとも。"

[[dialogue]]
speaker = "unk"
# 新星学園の規模の大きさを再認識するとともに、その中核を担う星徒会という存在の大きさを思い知らされた。
line = "新星学園の規模の大きさを再認識するとともに、その中核を担う星徒会という存在の大きさを思い知らされた。"

[[dialogue]]
speaker = "教頭"
# 「例えば詠野くんが、ホットドッグを山ほど食べたいから食堂がもうひとつ欲しいと言うなら、学園は対応せざるを得ないだろうね」
line = "「例えば詠野くんが、ホットドッグを山ほど食べたいから食堂がもうひとつ欲しいと言うなら、学園は対応せざるを得ないだろうね」"

[[dialogue]]
speaker = "クロト"
# 「そんなことまで……！」
line = "「そんなことまで……！」"

[[dialogue]]
speaker = "マトイ"
# 「私、そこまで食い意地張って見えるかな……？　でもいっそ開き直って食いしん坊キャラっていう属性をつけるのも……」
line = "「私、そこまで食い意地張って見えるかな……？　でもいっそ開き直って食いしん坊キャラっていう属性をつけるのも……」"

[[dialogue]]
speaker = "unk"
# 夢のようだと俺は感心したものの、当のマトイは眉をしかめながらうんうんと唸っていた。
line = "夢のようだと俺は感心したものの、当のマトイは眉をしかめながらうんうんと唸っていた。"

[[dialogue]]
speaker = "教頭"
# 「それに星徒会長ともなれば、一般生徒の退学さえ命じることができる。無論、誰彼構わずでは認可されないが」
line = "「それに星徒会長ともなれば、一般生徒の退学さえ命じることができる。無論、誰彼構わずでは認可されないが」"

[[dialogue]]
speaker = "クロト"
# 「た──退学ですか。そこまで……」
line = "「た──退学ですか。そこまで……」"

[[dialogue]]
speaker = "unk"
# この学園における生殺与奪。
line = "この学園における生殺与奪。"

[[dialogue]]
speaker = "unk"
# 下手すれば一介の教師さえ越える権力があるらしい。
line = "下手すれば一介の教師さえ越える権力があるらしい。"

[[dialogue]]
speaker = "教頭"
# 「だが、当然ただただ特権を与えているわけではない……星徒会にはその権力に応じた“責任”も負わせている。君を助けたこともその一環だろう」
line = "「だが、当然ただただ特権を与えているわけではない……星徒会にはその権力に応じた“責任”も負わせている。君を助けたこともその一環だろう」"

[[dialogue]]
speaker = "クロト"
# 「む……なるほど」
line = "「む……なるほど」"

[[dialogue]]
speaker = "教頭"
# 「何にせよ──これからの未来を切り拓くのは君たちのような若人だ。期待しているぞ、２人とも」
line = "「何にせよ──これからの未来を切り拓くのは君たちのような若人だ。期待しているぞ、２人とも」"

[[dialogue]]
speaker = "unk"
# はっはっはっと、教頭先生は笑いながら去っていった。
line = "はっはっはっと、教頭先生は笑いながら去っていった。"

[[dialogue]]
speaker = "マトイ"
# 「そろそろ教室に戻ろっか。次はトワちゃん先生の授業だから」
line = "「そろそろ教室に戻ろっか。次はトワちゃん先生の授業だから」"

[[dialogue]]
speaker = "クロト"
# 「ああ。早く慣れておきたいしな」
line = "「ああ。早く慣れておきたいしな」"

[[dialogue]]
speaker = "unk"
# 俺もいつか、星徒会とは言わないまでも世界に貢献できるような人物になりたい。
line = "俺もいつか、星徒会とは言わないまでも世界に貢献できるような人物になりたい。"

[[dialogue]]
speaker = "unk"
# だって、そのために……俺はこの学園を志したのだから。
line = "だって、そのために……俺はこの学園を志したのだから。"

[[dialogue]]
speaker = "クロト"
# 「ただいまー」
line = "「ただいまー」"

[[dialogue]]
speaker = "リノ"
# 「おっかえりークロト～。どう、新生活は楽しかった？　やっていけそう？」
line = "「おっかえりークロト～。どう、新生活は楽しかった？　やっていけそう？」"

[[dialogue]]
speaker = "クロト"
# 「うん。クラスメイトもいい人ばかりだったし……そんな心配しなくて大丈夫だよ」
line = "「うん。クラスメイトもいい人ばかりだったし……そんな心配しなくて大丈夫だよ」"

[[dialogue]]
speaker = "unk"
# くたびれて自宅へ帰ると、夕飯の匂いと共に母さんが顔を出した。
line = "くたびれて自宅へ帰ると、夕飯の匂いと共に母さんが顔を出した。"

[[dialogue]]
speaker = "unk"
# 慣れない環境にずっといたおかげか──緊張の糸がぷつりと切れたのを感じる。
line = "慣れない環境にずっといたおかげか──緊張の糸がぷつりと切れたのを感じる。"

[[dialogue]]
speaker = "リノ"
# 「ならよかった。もしクロトがいじめられたりでもしたら……って、親としては心配になるもの」
line = "「ならよかった。もしクロトがいじめられたりでもしたら……って、親としては心配になるもの」"

[[dialogue]]
speaker = "クロト"
# 「はは……もうそんな歳でもないよ。お風呂、湧いてる？」
line = "「はは……もうそんな歳でもないよ。お風呂、湧いてる？」"

[[dialogue]]
speaker = "リノ"
# 「もちろん。ま、明日も学校なんだしゆっくり休みなさいな」
line = "「もちろん。ま、明日も学校なんだしゆっくり休みなさいな」"

[[dialogue]]
speaker = "unk"
# そう。明日も授業だ。
line = "そう。明日も授業だ。"

[[dialogue]]
speaker = "unk"
# 半端な時期の転入だから仕方ないけど、入学のガイダンスみたいな期間もない。
line = "半端な時期の転入だから仕方ないけど、入学のガイダンスみたいな期間もない。"

[[dialogue]]
speaker = "unk"
# 俺は、英気を養うべくその日はぐっすりと眠った……。
line = "俺は、英気を養うべくその日はぐっすりと眠った……。"
