[[dialogue]]
speaker = "unk"
# 第７話,秘密基地,B
line = "第７話,秘密基地,B"

[[dialogue]]
speaker = "アポロ（大人）"
# 「よし、ここだ」
line = "「よし、ここだ」"

[[dialogue]]
speaker = "unk"
# アポロに連れられてきたのは、ビル群の一角。
line = "アポロに連れられてきたのは、ビル群の一角。"

[[dialogue]]
speaker = "unk"
# 言われた通りにドアを開けると──
line = "言われた通りにドアを開けると──"

[[dialogue]]
speaker = "クロト"
# 「！？　ここは……？」
line = "「！？　ここは……？」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「あたしたちの秘密基地だ。ここならルヴィネに見つかる心配もない」
line = "「あたしたちの秘密基地だ。ここならルヴィネに見つかる心配もない」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「どうだ、かっこいいだろう？」
line = "「どうだ、かっこいいだろう？」"

[[dialogue]]
speaker = "unk"
# 堂々と腕を組み、フンと自慢げに鼻を鳴らすアポロ。
line = "堂々と腕を組み、フンと自慢げに鼻を鳴らすアポロ。"

[[dialogue]]
speaker = "フィオナ"
# 「まるで流星ライダーの基地みたいです……！」
line = "「まるで流星ライダーの基地みたいです……！」"

[[dialogue]]
speaker = "unk"
# そしてフィオナは基地のメカメカしい威容に目を輝かせていた。
line = "そしてフィオナは基地のメカメカしい威容に目を輝かせていた。"

[[dialogue]]
speaker = "unk"
# 世界が違っても、時を隔てても、やはり姉妹だ。
line = "世界が違っても、時を隔てても、やはり姉妹だ。"

[[dialogue]]
speaker = "フィオナ"
# 「……コホン。はしゃいでいる場合ではありませんでしたね」
line = "「……コホン。はしゃいでいる場合ではありませんでしたね」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「いいじゃないか。テンション上がってくれた方があたしも嬉しいぞ」
line = "「いいじゃないか。テンション上がってくれた方があたしも嬉しいぞ」"

[[dialogue]]
speaker = "フィオナ"
# 「い、いえ……その……また後で見学させてください」
line = "「い、いえ……その……また後で見学させてください」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ああ、いいぞ。武器を作るファクトリーもあるしな」
line = "「ああ、いいぞ。武器を作るファクトリーもあるしな」"

[[dialogue]]
speaker = "フィオナ"
# 「ファクトリー！？　ぜひ見たいです……！」
line = "「ファクトリー！？　ぜひ見たいです……！」"

[[dialogue]]
speaker = "unk"
# アポロはヒーローのように振る舞うところは以前と変わらないが、どこか落ち着きがあって、やはり大人になったと感じられた。
line = "アポロはヒーローのように振る舞うところは以前と変わらないが、どこか落ち着きがあって、やはり大人になったと感じられた。"

[[dialogue]]
speaker = "unk"
# 外見の成長通り、それだけの月日を経たということなのだろう。
line = "外見の成長通り、それだけの月日を経たということなのだろう。"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長、お体は大丈夫ですか？　随分つらそうに見えましたけど……」
line = "「緋宮会長、お体は大丈夫ですか？　随分つらそうに見えましたけど……」"

[[dialogue]]
speaker = "クロト"
# 「ああ、ありがとう、何とか動けるようになってきたよ。ヴィーナスは？」
line = "「ああ、ありがとう、何とか動けるようになってきたよ。ヴィーナスは？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ええ、私も調子が戻ってきたわ。運んでくれてありがとう、ナターシャ」
line = "「ええ、私も調子が戻ってきたわ。運んでくれてありがとう、ナターシャ」"

[[dialogue]]
speaker = "ナターシャ"
# 「どーいたしまして」
line = "「どーいたしまして」"

[[dialogue]]
speaker = "クロト"
# 「金髪の女の子と、魔族の女の子もデネブに来ていたと思うんだけど、アポロは知らないか？」
line = "「金髪の女の子と、魔族の女の子もデネブに来ていたと思うんだけど、アポロは知らないか？」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「いいや、見てないな。その２人も仲間か？」
line = "「いいや、見てないな。その２人も仲間か？」"

[[dialogue]]
speaker = "ナターシャ"
# 「うん、梨緒とベアトリスっていうんだけど。私と同じ選挙管理委員会でね」
line = "「うん、梨緒とベアトリスっていうんだけど。私と同じ選挙管理委員会でね」"

[[dialogue]]
speaker = "ナターシャ"
# 「ついでに言うと、アルタイルのアポロも選管の一員だよ」
line = "「ついでに言うと、アルタイルのアポロも選管の一員だよ」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「へぇ、アルタイルのあたしは難しそうなのに入ってるんだな。ちょっと意外だ」
line = "「へぇ、アルタイルのあたしは難しそうなのに入ってるんだな。ちょっと意外だ」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「向こうのあたしの仲間なら、こっちのあたしにとっても仲間だ。準備ができ次第探しに行くとしよう」
line = "「向こうのあたしの仲間なら、こっちのあたしにとっても仲間だ。準備ができ次第探しに行くとしよう」"

[[dialogue]]
speaker = "ナターシャ"
# 「うん、助かるよ」
line = "「うん、助かるよ」"

[[dialogue]]
speaker = "unk"
# 敵地であるデネブで孤立するのは危険だ。
line = "敵地であるデネブで孤立するのは危険だ。"

[[dialogue]]
speaker = "unk"
# 戦闘に巻き込まれていないのであればまだ無事だと思うが、早く合流したい。
line = "戦闘に巻き込まれていないのであればまだ無事だと思うが、早く合流したい。"

[[dialogue]]
speaker = "アポロ（大人）"
# 「さて、詳しいことはまた改めて説明するが……デネブでは今は森羅暦３０１２年。お前たちとアルタイルで別れて十年後だ」
line = "「さて、詳しいことはまた改めて説明するが……デネブでは今は森羅暦３０１２年。お前たちとアルタイルで別れて十年後だ」"

[[dialogue]]
speaker = "アポロ"
# 「ああ。あたしは本来……<ruby=ここ>アルタイル</ruby>にいるべき存在じゃないからな」
line = "「ああ。あたしは本来……<ruby>アルタイル<rt>ここ</rt></ruby>にいるべき存在じゃないからな」"

[[dialogue]]
speaker = "アポロ"
# 「こっちのあたしが目覚めたら……なんて言うか知らないけど。フォローは頼んだぞ、ニャリオン」
line = "「こっちのあたしが目覚めたら……なんて言うか知らないけど。フォローは頼んだぞ、ニャリオン」"

[[dialogue]]
speaker = "アポロ"
# 「じゃあな。あたしを見捨てないでくれて、ありがとう。みんな」
line = "「じゃあな。あたしを見捨てないでくれて、ありがとう。みんな」"

[[dialogue]]
speaker = "アポロ"
# 「たくさん迷惑かけて……悪かったな。今度こそ、本物のヒーローになれるよう、頑張ってみるさ」
line = "「たくさん迷惑かけて……悪かったな。今度こそ、本物のヒーローになれるよう、頑張ってみるさ」"

[[dialogue]]
speaker = "unk"
# ギエルと決着をつけた、フィーニスの塔の頂上での戦いの最後。
line = "ギエルと決着をつけた、フィーニスの塔の頂上での戦いの最後。"

[[dialogue]]
speaker = "unk"
# 『デネブからやってきた』リクリエの使徒であるアポロは、そう言って自分の世界へと帰っていった。
line = "『デネブからやってきた』リクリエの使徒であるアポロは、そう言って自分の世界へと帰っていった。"

[[dialogue]]
speaker = "unk"
# そのアポロと記憶を共有していた『アルタイルのアポロ』は選挙管理委員会をやっているが、今目の前にいる彼女は正真正銘、<ruby=デネブ>あの時</ruby>のアポロだった。
line = "そのアポロと記憶を共有していた『アルタイルのアポロ』は選挙管理委員会をやっているが、今目の前にいる彼女は正真正銘、<ruby>あの時<rt>デネブ</rt></ruby>のアポロだった。"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ここはルヴィネに反抗するレジスタンスの秘密基地だ。まぁ実働メンバーは少数だし、反抗といっても微々たるものだがな」
line = "「ここはルヴィネに反抗するレジスタンスの秘密基地だ。まぁ実働メンバーは少数だし、反抗といっても微々たるものだがな」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「確証はないが、あたしたちレジスタンスはルヴィネを疑っている。やつには何か裏があるんじゃないかとな」
line = "「確証はないが、あたしたちレジスタンスはルヴィネを疑っている。やつには何か裏があるんじゃないかとな」"

[[dialogue]]
speaker = "フィオナ"
# 「……正直、デネブに来たばかりで困惑することばかりです。情報が多くて受け止め切れていません。でも──」
line = "「……正直、デネブに来たばかりで困惑することばかりです。情報が多くて受け止め切れていません。でも──」"

[[dialogue]]
speaker = "フィオナ"
# 「姉さんが生きていて良かった」
line = "「姉さんが生きていて良かった」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ホントよ！ <ruby=あっち>アルタイル</ruby>で別れた後心配してたんだから！」
line = "「ホントよ！ <ruby>アルタイル<rt>あっち</rt></ruby>で別れた後心配してたんだから！」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「──」
line = "「──」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ああ、そっか。アルタイル的には、デネブは滅びたと思われてたんだっけ。十年前の話だから忘れてた」
line = "「ああ、そっか。アルタイル的には、デネブは滅びたと思われてたんだっけ。十年前の話だから忘れてた」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「この通り、あたしは元気そのものだ。なんならお前たちより年上だぞ？」
line = "「この通り、あたしは元気そのものだ。なんならお前たちより年上だぞ？」"

[[dialogue]]
speaker = "unk"
# 口角を上げて不敵に笑むアポロ。
line = "口角を上げて不敵に笑むアポロ。"

[[dialogue]]
speaker = "unk"
# 共に戦えたのはギエルとの決戦だけだったけど、彼女は確かに俺たちの仲間だ。
line = "共に戦えたのはギエルとの決戦だけだったけど、彼女は確かに俺たちの仲間だ。"

[[dialogue]]
speaker = "アポロ（大人）"
# 「さてと……本当に久しぶりだな、エリシア」
line = "「さてと……本当に久しぶりだな、エリシア」"

[[dialogue]]
speaker = "フィオナ"
# 「姉さん……また会えて嬉しいです」
line = "「姉さん……また会えて嬉しいです」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ああ、あたしもだ」
line = "「ああ、あたしもだ」"

[[dialogue]]
speaker = "unk"
# 時と世界を超えて向かい合う姉と妹。
line = "時と世界を超えて向かい合う姉と妹。"

[[dialogue]]
speaker = "unk"
# 俺たちにとっては別れたのは数か月前だけど、アポロにとっては十年ぶりの再会だ。
line = "俺たちにとっては別れたのは数か月前だけど、アポロにとっては十年ぶりの再会だ。"

[[dialogue]]
speaker = "フィオナ"
# 「大きく……なりましたね」
line = "「大きく……なりましたね」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ああ、もうお前より年上だ。別れた時はお前より小さかったのに、今は追い越してしまった」
line = "「ああ、もうお前より年上だ。別れた時はお前より小さかったのに、今は追い越してしまった」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「双子だから歳の差なんてないはずなのに、小さかったり大きかったり、不思議なもんだ」
line = "「双子だから歳の差なんてないはずなのに、小さかったり大きかったり、不思議なもんだ」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「あたしがいない間、エリシアは元気だったか？　病気しなかったか？　流星ライダーばっかり見て勉強サボってないよな？」
line = "「あたしがいない間、エリシアは元気だったか？　病気しなかったか？　流星ライダーばっかり見て勉強サボってないよな？」"

[[dialogue]]
speaker = "フィオナ"
# 「心配しなくても大丈夫です。病気もしてませんし、私、優等生ですから」
line = "「心配しなくても大丈夫です。病気もしてませんし、私、優等生ですから」"

[[dialogue]]
speaker = "フィオナ"
# 「姉さんこそ、この十年、大変だったんでしょう？」
line = "「姉さんこそ、この十年、大変だったんでしょう？」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「まぁ……いろいろあったな。デネブに戻ったらリクリエは終わっていて、ルヴィネなんてやつがいて、魔王が悪者になっていた」
line = "「まぁ……いろいろあったな。デネブに戻ったらリクリエは終わっていて、ルヴィネなんてやつがいて、魔王が悪者になっていた」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ルヴィネから逃げて、隠れて、何度か戦って、こうして秘密基地も作った」
line = "「ルヴィネから逃げて、隠れて、何度か戦って、こうして秘密基地も作った」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「アルタイルでの戦いに負けないくらい、波乱の日々だったな」
line = "「アルタイルでの戦いに負けないくらい、波乱の日々だったな」"

[[dialogue]]
speaker = "フィオナ"
# 「姉さん……」
line = "「姉さん……」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ふ……そんな顔をするな。あたしはこうして元気にしてるからな」
line = "「ふ……そんな顔をするな。あたしはこうして元気にしてるからな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ところでデネブのフィオナ……というかエリシアはどうしたの？」
line = "「ところでデネブのフィオナ……というかエリシアはどうしたの？」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「まさか──」
line = "「まさか──」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ああ……あたしがデネブに戻った時には、こっちのエリシアは命を落としていた」
line = "「ああ……あたしがデネブに戻った時には、こっちのエリシアは命を落としていた」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「世界と人々を守るために戦い抜いた……ヒーローみたいに立派な最期だったと聞いている」
line = "「世界と人々を守るために戦い抜いた……ヒーローみたいに立派な最期だったと聞いている」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そう……」
line = "「そう……」"

[[dialogue]]
speaker = "unk"
# デネブは破滅の寸前まで追い込まれ、アルタイルよりも大きな被害を受けたと聞いている。
line = "デネブは破滅の寸前まで追い込まれ、アルタイルよりも大きな被害を受けたと聞いている。"

[[dialogue]]
speaker = "unk"
# アポロは語らないが、きっと俺たちが知る多くの星騎士も戦いで倒れているのだろう。
line = "アポロは語らないが、きっと俺たちが知る多くの星騎士も戦いで倒れているのだろう。"

[[dialogue]]
speaker = "フィオナ"
# 「そんな……」
line = "「そんな……」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「どうしてお前が泣く？」
line = "「どうしてお前が泣く？」"

[[dialogue]]
speaker = "フィオナ"
# 「あの戦いの後、私はアルタイルの姉さんとまた会うことができました。また話すことができました」
line = "「あの戦いの後、私はアルタイルの姉さんとまた会うことができました。また話すことができました」"

[[dialogue]]
speaker = "フィオナ"
# 「でも姉さんはあの時別れた後、ひとりで……」
line = "「でも姉さんはあの時別れた後、ひとりで……」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ひとりじゃないさ。アルタイルで共に戦ったお前たちがいるし、エリシアが遺してくれた世界がある」
line = "「ひとりじゃないさ。アルタイルで共に戦ったお前たちがいるし、エリシアが遺してくれた世界がある」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「だからあたしは、エリシアが命を懸けて守った世界を、あたしなりに守ろうとしているんだ。今度こそヒーローになれるように」
line = "「だからあたしは、エリシアが命を懸けて守った世界を、あたしなりに守ろうとしているんだ。今度こそヒーローになれるように」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「なぁ……エリシア。あたしはヒーローになれてるかな？」
line = "「なぁ……エリシア。あたしはヒーローになれてるかな？」"

[[dialogue]]
speaker = "フィオナ"
# 「はい……姉さんはずっと戦い続けてきた、最高のヒーローです」
line = "「はい……姉さんはずっと戦い続けてきた、最高のヒーローです」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「……ありがとう、エリシア」
line = "「……ありがとう、エリシア」"

[[dialogue]]
speaker = "unk"
# 運命に翻弄された姉妹は、別れた時と同じようにまたぎゅっと抱き合う。
line = "運命に翻弄された姉妹は、別れた時と同じようにまたぎゅっと抱き合う。"

[[dialogue]]
speaker = "unk"
# 俺たちはその様子を静かに見守っていた。
line = "俺たちはその様子を静かに見守っていた。"

[[dialogue]]
speaker = "ナターシャ"
# 「ところでさ、ここって本当にルヴィネに見つからないの？　どうやって追手の目を逃れてるわけ？」
line = "「ところでさ、ここって本当にルヴィネに見つからないの？　どうやって追手の目を逃れてるわけ？」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「いいところに気が付いたな。ここは通常の空間から切り離された隔離空間なんだ。普通に潜伏してたらルヴィネに見つかるからな」
line = "「いいところに気が付いたな。ここは通常の空間から切り離された隔離空間なんだ。普通に潜伏してたらルヴィネに見つかるからな」"

[[dialogue]]
speaker = "クロト"
# 「隔離空間？　そんなのどうやって──」
line = "「隔離空間？　そんなのどうやって──」"

[[dialogue]]
speaker = "？？？"
# 「あなたが<b>緋宮</b>クロトなら、知ってるんじゃないかしら？　空間を操る魔女を」
line = "「あなたが<b>緋宮</b>クロトなら、知ってるんじゃないかしら？　空間を操る魔女を」"

[[dialogue]]
speaker = "クロト"
# 「！　この声は──」
line = "「！　この声は──」"

[[dialogue]]
speaker = "リノ"
# 「や、クロト、久しぶり！　元気してたかしら～？」
line = "「や、クロト、久しぶり！　元気してたかしら～？」"

[[dialogue]]
speaker = "クロト"
# 「母さん……！？」
line = "「母さん……！？」"
