[[dialogue]]
speaker = "unk"
# 第２話,チナとの対話,B
line = "第２話,チナとの対話,B"

[[dialogue]]
speaker = "unk"
# チナが新星学園に拘束されて３日が経過した。緋宮クロトたちはまだ帰還していない。
line = "チナが新星学園に拘束されて３日が経過した。緋宮クロトたちはまだ帰還していない。"

[[dialogue]]
speaker = "unk"
# そしてチナは出された食事に手を付けず、未だに沈黙を続けていた。
line = "そしてチナは出された食事に手を付けず、未だに沈黙を続けていた。"

[[dialogue]]
speaker = "チナ"
# （敵に利用されるくらいなら……このまま死んでやる……）
line = "（敵に利用されるくらいなら……このまま死んでやる……）"

[[dialogue]]
speaker = "チナ"
# （でも魔王クロトがアルタイルに逃げたのは、間違いだったのか……？　どうしてルヴィは──）
line = "（でも魔王クロトがアルタイルに逃げたのは、間違いだったのか……？　どうしてルヴィは──）"

[[dialogue]]
speaker = "シノ"
# 「こんにちは、香堂チナさん」
line = "「こんにちは、香堂チナさん」"

[[dialogue]]
speaker = "チナ"
# 「！　何の用だ……？」
line = "「！　何の用だ……？」"

[[dialogue]]
speaker = "unk"
# チナの眼光には敵意と警戒心が込められていたが、シノは動じずに名乗る。
line = "チナの眼光には敵意と警戒心が込められていたが、シノは動じずに名乗る。"

[[dialogue]]
speaker = "シノ"
# 「初めまして。私は十六夜シノ。新星学園の学園長です」
line = "「初めまして。私は十六夜シノ。新星学園の学園長です」"

[[dialogue]]
speaker = "チナ"
# 「は……？　こんな若い女が学園長なわけないだろ。バカにしてるのか？」
line = "「は……？　こんな若い女が学園長なわけないだろ。バカにしてるのか？」"

[[dialogue]]
speaker = "シノ"
# 「これが本当なんです。私も新星学園の学園長にならないかと声をかけられた時は、とても驚きましたけど」
line = "「これが本当なんです。私も新星学園の学園長にならないかと声をかけられた時は、とても驚きましたけど」"

[[dialogue]]
speaker = "シノ"
# 「就任したのは最近ですが、ちゃんと理事会で選ばれたんですよ」
line = "「就任したのは最近ですが、ちゃんと理事会で選ばれたんですよ」"

[[dialogue]]
speaker = "unk"
# そう言って職員証を見せるシノ。そこには彼女の顔写真とともに学園長という役職が記されていた。
line = "そう言って職員証を見せるシノ。そこには彼女の顔写真とともに学園長という役職が記されていた。"

[[dialogue]]
speaker = "チナ"
# 「……お前が学園長だろうがどうでもいい。だいたい、その学園長が何しに来たんだ？」
line = "「……お前が学園長だろうがどうでもいい。だいたい、その学園長が何しに来たんだ？」"

[[dialogue]]
speaker = "シノ"
# 「チナさんと食事をしたいと思いまして」
line = "「チナさんと食事をしたいと思いまして」"

[[dialogue]]
speaker = "チナ"
# 「食事？　アタシが食べないから心配して来たのか？」
line = "「食事？　アタシが食べないから心配して来たのか？」"

[[dialogue]]
speaker = "チナ"
# 「ハッ、残念だったな。人質になってデネブの足を引っ張るくらいなら、アタシはこのまま死ぬ……！」
line = "「ハッ、残念だったな。人質になってデネブの足を引っ張るくらいなら、アタシはこのまま死ぬ……！」"

[[dialogue]]
speaker = "シノ"
# 「あなたは一度、命を捨てて特攻をかけた身。デネブにとって人質の価値があるかは疑問です」
line = "「あなたは一度、命を捨てて特攻をかけた身。デネブにとって人質の価値があるかは疑問です」"

[[dialogue]]
speaker = "シノ"
# 「であれば今は、食事を摂って体力を養い、脱出の機会を窺う方が、デネブや極星学園にとって利益になる可能性が高いのでは？」
line = "「であれば今は、食事を摂って体力を養い、脱出の機会を窺う方が、デネブや極星学園にとって利益になる可能性が高いのでは？」"

[[dialogue]]
speaker = "チナ"
# 「なんだと……！」
line = "「なんだと……！」"

[[dialogue]]
speaker = "unk"
# シノは冷静に反論しつつ、手に提げていた袋を差し出す。
line = "シノは冷静に反論しつつ、手に提げていた袋を差し出す。"

[[dialogue]]
speaker = "シノ"
# 「これ、よかったらどうぞ」
line = "「これ、よかったらどうぞ」"

[[dialogue]]
speaker = "チナ"
# 「！　それは<ruby=ローローハンテン>肉肉飯店</ruby>の肉まん……！」
line = "「！　それは<ruby>肉肉飯店<rt>ローローハンテン</rt></ruby>の肉まん……！」"

[[dialogue]]
speaker = "シノ"
# 「はい。とても美味しいと評判で、さっき買ってきました。とてもいい匂いがしてお腹がペコペコになってしまいます」
line = "「はい。とても美味しいと評判で、さっき買ってきました。とてもいい匂いがしてお腹がペコペコになってしまいます」"

[[dialogue]]
speaker = "シノ"
# 「肉肉飯店……あなたもよくご存じのお店ですよね？」
line = "「肉肉飯店……あなたもよくご存じのお店ですよね？」"

[[dialogue]]
speaker = "チナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "シノ"
# 「あなたが平行世界デネブから来たのならば、アルタイルにも『香堂チナ』がいるはず。そこでこちらの世界の『香堂チナ』さんについて調べさせてもらいました」
line = "「あなたが平行世界デネブから来たのならば、アルタイルにも『香堂チナ』がいるはず。そこでこちらの世界の『香堂チナ』さんについて調べさせてもらいました」"

[[dialogue]]
speaker = "シノ"
# 「出身は流星市国。肉肉飯店の近くにお住まいで、そこの肉まんが好物だそうです」
line = "「出身は流星市国。肉肉飯店の近くにお住まいで、そこの肉まんが好物だそうです」"

[[dialogue]]
speaker = "シノ"
# 「こちらの彼女はあなたより幼い。年齢から推測すると、デネブはアルタイルより１０年ほど時間が進んでいるようですね」
line = "「こちらの彼女はあなたより幼い。年齢から推測すると、デネブはアルタイルより１０年ほど時間が進んでいるようですね」"

[[dialogue]]
speaker = "シノ"
# 「現在、彼女は眠っています。命に別状はないようですが、以前のアポロさんと同じく時間が止まったような状態です」
line = "「現在、彼女は眠っています。命に別状はないようですが、以前のアポロさんと同じく時間が止まったような状態です」"

[[dialogue]]
speaker = "シノ"
# 「話を聞くと、この前あなたがアルタイルに来た時も、一時的に同じ状態になったそうです」
line = "「話を聞くと、この前あなたがアルタイルに来た時も、一時的に同じ状態になったそうです」"

[[dialogue]]
speaker = "シノ"
# 「同じ世界に同一存在がいる影響なのでしょう。なのでデネブに帰還する手段がわかり次第、あなたにはお帰り願いますね」
line = "「同じ世界に同一存在がいる影響なのでしょう。なのでデネブに帰還する手段がわかり次第、あなたにはお帰り願いますね」"

[[dialogue]]
speaker = "チナ"
# 「それならアタシを殺せばいいだろ」
line = "「それならアタシを殺せばいいだろ」"

[[dialogue]]
speaker = "シノ"
# 「いえ、いけません。同一存在であるあなたが死ねば、彼女にどんな影響が及ぶか予想できません」
line = "「いえ、いけません。同一存在であるあなたが死ねば、彼女にどんな影響が及ぶか予想できません」"

[[dialogue]]
speaker = "シノ"
# 「この世界の『香堂チナ』を守るためにも、あなたを傷つけるわけにはいきません」
line = "「この世界の『香堂チナ』を守るためにも、あなたを傷つけるわけにはいきません」"

[[dialogue]]
speaker = "チナ"
# 「……だから食え、ってか？　わざわざアタシの知ってる店の肉まんを持ってきて、皮肉のつもりか？」
line = "「……だから食え、ってか？　わざわざアタシの知ってる店の肉まんを持ってきて、皮肉のつもりか？」"

[[dialogue]]
speaker = "チナ"
# 「肉肉飯店はデネブにはもうない。１０年前のリクリエで壊されたままだ。アタシが知ってる街はみんななくなっちまった」
line = "「肉肉飯店はデネブにはもうない。１０年前のリクリエで壊されたままだ。アタシが知ってる街はみんななくなっちまった」"

[[dialogue]]
speaker = "チナ"
# 「それをアタシの前に持ってきて、『これをお前が滅ぼそうとした』って、そう言いたいのかよ？」
line = "「それをアタシの前に持ってきて、『これをお前が滅ぼそうとした』って、そう言いたいのかよ？」"

[[dialogue]]
speaker = "シノ"
# 「いいえ。私が肉肉飯店の肉まんを選んだのは、あなたの好物と聞いたからです。深い意味はありませんよ」
line = "「いいえ。私が肉肉飯店の肉まんを選んだのは、あなたの好物と聞いたからです。深い意味はありませんよ」"

[[dialogue]]
speaker = "シノ"
# 「私はあなたを非難する気はありません。その資格もありません」
line = "「私はあなたを非難する気はありません。その資格もありません」"

[[dialogue]]
speaker = "シノ"
# 「『カルネアデスの板』ではありませんが……人には、生き物には、生きる権利があります。時に他者を害してでも」
line = "「『カルネアデスの板』ではありませんが……人には、生き物には、生きる権利があります。時に他者を害してでも」"

[[dialogue]]
speaker = "シノ"
# 「平行世界のどちらかが滅びなければいけない。その前提に立つならば、あなたに非はありません」
line = "「平行世界のどちらかが滅びなければいけない。その前提に立つならば、あなたに非はありません」"

[[dialogue]]
speaker = "シノ"
# 「──ですが」
line = "「──ですが」"

[[dialogue]]
speaker = "シノ"
# 「あなたはアルタイルを滅ぼしたいわけではない。むしろアルタイルにいる自分の家族や、生まれ育った街も守りたい」
line = "「あなたはアルタイルを滅ぼしたいわけではない。むしろアルタイルにいる自分の家族や、生まれ育った街も守りたい」"

[[dialogue]]
speaker = "シノ"
# 「破壊される流星市国の街を見て、あなた自身が心を痛めている。……そうじゃないですか？」
line = "「破壊される流星市国の街を見て、あなた自身が心を痛めている。……そうじゃないですか？」"

[[dialogue]]
speaker = "チナ"
# 「──！」
line = "「──！」"

[[dialogue]]
speaker = "チナ"
# 「だからどうした……！　やりたいとかやりたくないじゃない、やらなくちゃいけないんだ！」
line = "「だからどうした……！　やりたいとかやりたくないじゃない、やらなくちゃいけないんだ！」"

[[dialogue]]
speaker = "シノ"
# 「私は新星学園の学園長になる前、民間企業の社長として商売をしていました」
line = "「私は新星学園の学園長になる前、民間企業の社長として商売をしていました」"

[[dialogue]]
speaker = "シノ"
# 「だから思うんです。取引の理想はウィンウィン……両者が得をすることだと」
line = "「だから思うんです。取引の理想はウィンウィン……両者が得をすることだと」"

[[dialogue]]
speaker = "シノ"
# 「私はあなたとも、デネブともウィンウィンでありたい」
line = "「私はあなたとも、デネブともウィンウィンでありたい」"

[[dialogue]]
speaker = "シノ"
# 「そして『アルタイルとデネブの両方を救う』──その選択こそ、両者にとって最も大きな利益となる、ウィンウィンの取引だと思うんです」
line = "「そして『アルタイルとデネブの両方を救う』──その選択こそ、両者にとって最も大きな利益となる、ウィンウィンの取引だと思うんです」"

[[dialogue]]
speaker = "チナ"
# 「お前もバカなのか！？　それができないからアタシたちは──」
line = "「お前もバカなのか！？　それができないからアタシたちは──」"

[[dialogue]]
speaker = "シノ"
# 「私だって何の根拠もなく提案しているわけではありません。これを見ていただけますか？」
line = "「私だって何の根拠もなく提案しているわけではありません。これを見ていただけますか？」"

[[dialogue]]
speaker = "unk"
# シノはそう言ってリモコンを操作し、会議室のスクリーンに映像を投影する。
line = "シノはそう言ってリモコンを操作し、会議室のスクリーンに映像を投影する。"

[[dialogue]]
speaker = "チナ"
# 「！？　これは……？」
line = "「！？　これは……？」"

[[dialogue]]
speaker = "シノ"
# 「私たちはディザスターハンドと呼んでいます。破滅そのものと表現するに相応しい、巨大な手です」
line = "「私たちはディザスターハンドと呼んでいます。破滅そのものと表現するに相応しい、巨大な手です」"

[[dialogue]]
speaker = "チナ"
# 「ディザスターハンド……？」
line = "「ディザスターハンド……？」"

[[dialogue]]
speaker = "シノ"
# 「その様子ですと、ご存じないのですね。ディザスターハンドはまだデネブには現れていないのでしょう」
line = "「その様子ですと、ご存じないのですね。ディザスターハンドはまだデネブには現れていないのでしょう」"

[[dialogue]]
speaker = "シノ"
# 「もうひとつ。平行世界ベガについて聞いたことはありますか？　ここアルタイルとも、あなたのデネブとも違う世界です」
line = "「もうひとつ。平行世界ベガについて聞いたことはありますか？　ここアルタイルとも、あなたのデネブとも違う世界です」"

[[dialogue]]
speaker = "チナ"
# 「……ルヴィネ会長から聞いたことがある。確か、もう滅んだ世界って言っていた」
line = "「……ルヴィネ会長から聞いたことがある。確か、もう滅んだ世界って言っていた」"

[[dialogue]]
speaker = "シノ"
# 「ええ、そうです。そしてそのベガを滅ぼしたのが、このディザスターハンドとされています」
line = "「ええ、そうです。そしてそのベガを滅ぼしたのが、このディザスターハンドとされています」"

[[dialogue]]
speaker = "チナ"
# 「──！！」
line = "「──！！」"

[[dialogue]]
speaker = "シノ"
# 「私たちはベガの数少ない生き残りから話を聞きました。残念ながらベガは……ディザスターハンドに勝てなかった」
line = "「私たちはベガの数少ない生き残りから話を聞きました。残念ながらベガは……ディザスターハンドに勝てなかった」"

[[dialogue]]
speaker = "シノ"
# 「ですがアルタイルとデネブが力を合わせれば、このディザスターハンドに……リクリエに勝てるかもしれない。私はそう考えています」
line = "「ですがアルタイルとデネブが力を合わせれば、このディザスターハンドに……リクリエに勝てるかもしれない。私はそう考えています」"

[[dialogue]]
speaker = "チナ"
# 「リクリエに……勝てる……」
line = "「リクリエに……勝てる……」"

[[dialogue]]
speaker = "シノ"
# 「……すみません、長々と話をしてしまいましたね。でも私が今話したこと、少し考えてみていただけると嬉しいです」
line = "「……すみません、長々と話をしてしまいましたね。でも私が今話したこと、少し考えてみていただけると嬉しいです」"

[[dialogue]]
speaker = "シノ"
# 「じゃあとりあえず──肉まん食べませんか？　せっかく買ってきたのに、このままでは冷めてしまいます」
line = "「じゃあとりあえず──肉まん食べませんか？　せっかく買ってきたのに、このままでは冷めてしまいます」"

[[dialogue]]
speaker = "シノ"
# 「さ、どうぞ。もちろん毒は入っていませんよ」
line = "「さ、どうぞ。もちろん毒は入っていませんよ」"

[[dialogue]]
speaker = "チナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# 差し出された肉まんを、チナは無言で受け取る。
line = "差し出された肉まんを、チナは無言で受け取る。"

[[dialogue]]
speaker = "シノ"
# 「では私もいただきます。……あむ」
line = "「では私もいただきます。……あむ」"

[[dialogue]]
speaker = "シノ"
# 「ん～♪　さすが煌嶺さんのオススメ、これは絶品ですね♪」
line = "「ん～♪　さすが煌嶺さんのオススメ、これは絶品ですね♪」"

[[dialogue]]
speaker = "チナ"
# 「……あむ」
line = "「……あむ」"

[[dialogue]]
speaker = "チナ"
# 「──！　ぅ……うぅ……」
line = "「──！　ぅ……うぅ……」"

[[dialogue]]
speaker = "unk"
# そしてチナも一口肉まんをかじり、懐かしい味に目を潤ませるのだった。
line = "そしてチナも一口肉まんをかじり、懐かしい味に目を潤ませるのだった。"
