[[dialogue]]
speaker = "unk"
# 第８話,大聖堂の誓い,B
line = "第８話,大聖堂の誓い,B"

[[dialogue]]
speaker = "シルヴィ"
# 「よかった、誰もいな～い！」
line = "「よかった、誰もいな～い！」"

[[dialogue]]
speaker = "サーシャ"
# 「こら、暴れないの～。どうして、こんなところに連れてきたの？」
line = "「こら、暴れないの～。どうして、こんなところに連れてきたの？」"

[[dialogue]]
speaker = "シルヴィ"
# 「こんなところなんて言っちゃダメだよ！　女神様が見てるんだから！」
line = "「こんなところなんて言っちゃダメだよ！　女神様が見てるんだから！」"

[[dialogue]]
speaker = "シルヴィ"
# 「女神様にもさっきのお話を聞いてもらおうと思ってさ！　守護星に願いを捧げて誓いを立てると女神様の加護があるんだよ！」
line = "「女神様にもさっきのお話を聞いてもらおうと思ってさ！　守護星に願いを捧げて誓いを立てると女神様の加護があるんだよ！」"

[[dialogue]]
speaker = "サーシャ"
# 「へえ～、地元のおばあちゃんも似たようなこと言ってた気がするわ～」
line = "「へえ～、地元のおばあちゃんも似たようなこと言ってた気がするわ～」"

[[dialogue]]
speaker = "シルヴィ"
# 「あたし、おばあちゃんじゃないもん！」
line = "「あたし、おばあちゃんじゃないもん！」"

[[dialogue]]
speaker = "サーシャ"
# 「いいわ、やりましょう。やり方を教えて？」
line = "「いいわ、やりましょう。やり方を教えて？」"

[[dialogue]]
speaker = "シルヴィ"
# 「おっけー！　まずは、守護星に向かって……屋内なので、窓に向かってひざまずきます」
line = "「おっけー！　まずは、守護星に向かって……屋内なので、窓に向かってひざまずきます」"

[[dialogue]]
speaker = "サーシャ"
# 「ふむふむ……」
line = "「ふむふむ……」"

[[dialogue]]
speaker = "シルヴィ"
# 「それから星術を使うみたいに、気を研ぎ澄ませます」
line = "「それから星術を使うみたいに、気を研ぎ澄ませます」"

[[dialogue]]
speaker = "サーシャ"
# 「ええ」
line = "「ええ」"

[[dialogue]]
speaker = "サーシャ"
# （――こうしていると……ほのかに力を感じるわ……）
line = "（――こうしていると……ほのかに力を感じるわ……）"

[[dialogue]]
speaker = "サーシャ"
# （守護星の星力……）
line = "（守護星の星力……）"

[[dialogue]]
speaker = "サーシャ"
# （この暗闇と静寂が、遠く離れた守護星の力を鋭敏に感じさせるのかもしれないわね）
line = "（この暗闇と静寂が、遠く離れた守護星の力を鋭敏に感じさせるのかもしれないわね）"

[[dialogue]]
speaker = "シルヴィ"
# 「あたしの真似して言って……我が守護星アヴィオールよ、我が願いを聞き届けた給え」
line = "「あたしの真似して言って……我が守護星アヴィオールよ、我が願いを聞き届けた給え」"

[[dialogue]]
speaker = "サーシャ"
# 「我が守護星エウロパよ、我が願いを聞き届け給え」
line = "「我が守護星エウロパよ、我が願いを聞き届け給え」"

[[dialogue]]
speaker = "シルヴィ"
# 「あたしの願いは、みんなを守ることです。あたしの知る人、知るところ、全てを守らせてください」
line = "「あたしの願いは、みんなを守ることです。あたしの知る人、知るところ、全てを守らせてください」"

[[dialogue]]
speaker = "サーシャ"
# 「私の願いは、世界を知ることです。三界すべてを、あるいはその先があるというなら、遍く見てみたい」
line = "「私の願いは、世界を知ることです。三界すべてを、あるいはその先があるというなら、遍く見てみたい」"

[[dialogue]]
speaker = "シルヴィ"
# 「創造主たる女神よ、我が誓いを見届け給え」
line = "「創造主たる女神よ、我が誓いを見届け給え」"

[[dialogue]]
speaker = "サーシャ"
# 「創造主たる女神よ、我が誓いを見届け給え」
line = "「創造主たる女神よ、我が誓いを見届け給え」"

[[dialogue]]
speaker = "シルヴィ"
# 「星騎士シルヴィ・グリムランド。星騎士サーシャとともにリクリエを阻止し、みんなを守ります」
line = "「星騎士シルヴィ・グリムランド。星騎士サーシャとともにリクリエを阻止し、みんなを守ります」"

[[dialogue]]
speaker = "サーシャ"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "シルヴィ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "サーシャ"
# 「……ふふっ」
line = "「……ふふっ」"

[[dialogue]]
speaker = "サーシャ"
# 「星騎士サーシャ。星騎士シルヴィ・グリムランドとともにリクリエを阻止し、世界を救います」
line = "「星騎士サーシャ。星騎士シルヴィ・グリムランドとともにリクリエを阻止し、世界を救います」"

[[dialogue]]
speaker = "シルヴィ"
# 「これでばっちりだね！」
line = "「これでばっちりだね！」"

[[dialogue]]
speaker = "サーシャ"
# 「これってシルヴィの町に伝わるやり方なの？　由来とかあるのかしら？」
line = "「これってシルヴィの町に伝わるやり方なの？　由来とかあるのかしら？」"

[[dialogue]]
speaker = "シルヴィ"
# 「え？　ううん、お姉さんに教わったやつ！」
line = "「え？　ううん、お姉さんに教わったやつ！」"

[[dialogue]]
speaker = "サーシャ"
# 「あ、あの蛍火ちゃんに似てる人ね……」
line = "「あ、あの蛍火ちゃんに似てる人ね……」"

[[dialogue]]
speaker = "シルヴィ"
# 「それより、約束だからね！」
line = "「それより、約束だからね！」"

[[dialogue]]
speaker = "サーシャ"
# 「ええ。リクリエが来たら必ず一緒に戦いましょう」
line = "「ええ。リクリエが来たら必ず一緒に戦いましょう」"

[[dialogue]]
speaker = "シルヴィ"
# 「サーシャの背中はあたしが守る！」
line = "「サーシャの背中はあたしが守る！」"

[[dialogue]]
speaker = "unk"
# 高く拳を突き上げるシルヴィ。
line = "高く拳を突き上げるシルヴィ。"

[[dialogue]]
speaker = "unk"
# その拳は──
line = "その拳は──"

[[dialogue]]
speaker = "unk"
# ──今はここにあった。
line = "──今はここにあった。"

[[dialogue]]
speaker = "unk"
# シルヴィの固く握りしめられた手に、サーシャはそっと自分の手を重ねる。
line = "シルヴィの固く握りしめられた手に、サーシャはそっと自分の手を重ねる。"

[[dialogue]]
speaker = "サーシャ"
# 「泣かないで、シルヴィ」
line = "「泣かないで、シルヴィ」"

[[dialogue]]
speaker = "シルヴィ"
# 「ごめん……でも、あたし、自分から言い出したのに、約束、守れなくて……ぐすっ、間に合わなくて……」
line = "「ごめん……でも、あたし、自分から言い出したのに、約束、守れなくて……ぐすっ、間に合わなくて……」"

[[dialogue]]
speaker = "サーシャ"
# 「仕方のないことよ。誰にも、いつリクリエが来るかなんて分からなかったんだから」
line = "「仕方のないことよ。誰にも、いつリクリエが来るかなんて分からなかったんだから」"

[[dialogue]]
speaker = "サーシャ"
# 「まだ泣き止まない？　よしよししてあげましょうか？」
line = "「まだ泣き止まない？　よしよししてあげましょうか？」"

[[dialogue]]
speaker = "シルヴィ"
# 「……それはハズい。ぐすっ」
line = "「……それはハズい。ぐすっ」"

[[dialogue]]
speaker = "サーシャ"
# 「はい、ティッシュ」
line = "「はい、ティッシュ」"

[[dialogue]]
speaker = "シルヴィ"
# 「ありがと……いいよ、鼻くらい自分でかめるからっ！　チーン！」
line = "「ありがと……いいよ、鼻くらい自分でかめるからっ！　チーン！」"

[[dialogue]]
speaker = "サーシャ"
# 「……落ち着いた？」
line = "「……落ち着いた？」"

[[dialogue]]
speaker = "シルヴィ"
# 「ごめん、いや、えっと、約束のごめんじゃなくて、急に泣き出してごめん……」
line = "「ごめん、いや、えっと、約束のごめんじゃなくて、急に泣き出してごめん……」"

[[dialogue]]
speaker = "サーシャ"
# 「いいのよ～。泣いてるシルヴィ、珍しいから面白かったわ～」
line = "「いいのよ～。泣いてるシルヴィ、珍しいから面白かったわ～」"

[[dialogue]]
speaker = "シルヴィ"
# 「サーシャっていい性格してるよねー」
line = "「サーシャっていい性格してるよねー」"

[[dialogue]]
speaker = "サーシャ"
# 「誉め言葉として受け取っておくわ。それにね、助けられているって言ったでしょう？」
line = "「誉め言葉として受け取っておくわ。それにね、助けられているって言ったでしょう？」"

[[dialogue]]
speaker = "サーシャ"
# 「シルヴィが、あなたの故郷をちゃんと守ってくれたから、私は戦えたのよ～」
line = "「シルヴィが、あなたの故郷をちゃんと守ってくれたから、私は戦えたのよ～」"

[[dialogue]]
speaker = "シルヴィ"
# 「え？」
line = "「え？」"
