[[dialogue]]
speaker = "unk"
# 第１２話,使徒,B
line = "第１２話,使徒,B"

[[dialogue]]
speaker = "グレイス"
# 「うぅ……うっ……ひくっ……」
line = "「うぅ……うっ……ひくっ……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「泣いちゃった！？　あなた、大丈夫なの！？」
line = "「泣いちゃった！？　あなた、大丈夫なの！？」"

[[dialogue]]
speaker = "グレイス"
# 「ほ、ほっといてください！　ただの思い出し泣きですっ！」
line = "「ほ、ほっといてください！　ただの思い出し泣きですっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「どういうこと？」
line = "「どういうこと？」"

[[dialogue]]
speaker = "クロト"
# 「まぁ、もう戦えないみたいだし、今はそっとしておこう」
line = "「まぁ、もう戦えないみたいだし、今はそっとしておこう」"

[[dialogue]]
speaker = "unk"
# ひとまず極星星徒会の１人を無力化できた。
line = "ひとまず極星星徒会の１人を無力化できた。"

[[dialogue]]
speaker = "unk"
# あとは仲間の安否と、レティシアがどうなっているかが気になる。
line = "あとは仲間の安否と、レティシアがどうなっているかが気になる。"

[[dialogue]]
speaker = "ナターシャ"
# 「あ、もう終わってる感じ？」
line = "「あ、もう終わってる感じ？」"

[[dialogue]]
speaker = "メルエル"
# 「ナターシャちゃん！　無事でよかった！」
line = "「ナターシャちゃん！　無事でよかった！」"

[[dialogue]]
speaker = "ナターシャ"
# 「メルエルもね。極星星徒会を倒すなんて大手柄じゃん」
line = "「メルエルもね。極星星徒会を倒すなんて大手柄じゃん」"

[[dialogue]]
speaker = "メルエル"
# 「ううん、会長くんと力を合わせたからだよ」
line = "「ううん、会長くんと力を合わせたからだよ」"

[[dialogue]]
speaker = "メルエル"
# 「でもありがとう。天使の１人として、女神様の神殿を守ることができたよ」
line = "「でもありがとう。天使の１人として、女神様の神殿を守ることができたよ」"

[[dialogue]]
speaker = "unk"
# 無事を喜び合うメルエルとナターシャ。
line = "無事を喜び合うメルエルとナターシャ。"

[[dialogue]]
speaker = "unk"
# だけどナターシャと一緒にやってきた梨緒は、ひどく暗い顔をしていた。
line = "だけどナターシャと一緒にやってきた梨緒は、ひどく暗い顔をしていた。"

[[dialogue]]
speaker = "梨緒"
# 「すまない……役に立てなかった」
line = "「すまない……役に立てなかった」"

[[dialogue]]
speaker = "クロト"
# 「いや、それはいいんだが……」
line = "「いや、それはいいんだが……」"

[[dialogue]]
speaker = "ナターシャ"
# （ごめん、今はほっといてあげて。途中でガーディアンにやられたんだ）
line = "（ごめん、今はほっといてあげて。途中でガーディアンにやられたんだ）"

[[dialogue]]
speaker = "クロト"
# （……わかった）
line = "（……わかった）"

[[dialogue]]
speaker = "unk"
# 梨緒は明らかに平静な状態ではなかったが、今はかける言葉がなさそうだった。
line = "梨緒は明らかに平静な状態ではなかったが、今はかける言葉がなさそうだった。"

[[dialogue]]
speaker = "アポロ"
# 「大丈夫か、みんな！？」
line = "「大丈夫か、みんな！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「アポロも無事だったのね！」
line = "「アポロも無事だったのね！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「こっちはクロトとメルエルと一緒にグレイスを止めたわ。ナターシャと梨緒も合流したところよ」
line = "「こっちはクロトとメルエルと一緒にグレイスを止めたわ。ナターシャと梨緒も合流したところよ」"

[[dialogue]]
speaker = "アポロ"
# 「そっか、じゃあみんな無事なんだな。あたしはベアトと一緒にレティシアを倒したぞ」
line = "「そっか、じゃあみんな無事なんだな。あたしはベアトと一緒にレティシアを倒したぞ」"

[[dialogue]]
speaker = "アポロ"
# 「チナが力を貸してくれて、なんとかなったんだ」
line = "「チナが力を貸してくれて、なんとかなったんだ」"

[[dialogue]]
speaker = "グレイス"
# 「チナが！？　ここにいるんですか！？」
line = "「チナが！？　ここにいるんですか！？」"

[[dialogue]]
speaker = "アポロ"
# 「ああ。ルヴィネの気持ちを確かめるって言ってな」
line = "「ああ。ルヴィネの気持ちを確かめるって言ってな」"

[[dialogue]]
speaker = "グレイス"
# 「そう……ですか」
line = "「そう……ですか」"

[[dialogue]]
speaker = "unk"
# チナがアルタイル側についたと聞き、落ち込む様子を見せるグレイス。
line = "チナがアルタイル側についたと聞き、落ち込む様子を見せるグレイス。"

[[dialogue]]
speaker = "unk"
# だけど今ならチナと直接話すこともできる。
line = "だけど今ならチナと直接話すこともできる。"

[[dialogue]]
speaker = "unk"
# 落ち着いて話せば、きっと分かり合えると思う。
line = "落ち着いて話せば、きっと分かり合えると思う。"

[[dialogue]]
speaker = "クロト"
# 「極星星徒会の２人を無力化できたし、みんなのおかげで女神の神殿を守ることができた」
line = "「極星星徒会の２人を無力化できたし、みんなのおかげで女神の神殿を守ることができた」"

[[dialogue]]
speaker = "クロト"
# 「だけど守護天使の神殿も守らないといけない。一旦聖庭園に帰還して──」
line = "「だけど守護天使の神殿も守らないといけない。一旦聖庭園に帰還して──」"

[[dialogue]]
speaker = "ジグ"
# 「おや、もうステージはお終いかい？」
line = "「おや、もうステージはお終いかい？」"

[[dialogue]]
speaker = "梨緒"
# 「──！？」
line = "「──！？」"

[[dialogue]]
speaker = "クロト"
# 「ジグ……！？」
line = "「ジグ……！？」"

[[dialogue]]
speaker = "ジグ"
# 「やぁ、こうして会うのは久しぶりだね、星騎士の諸君」
line = "「やぁ、こうして会うのは久しぶりだね、星騎士の諸君」"

[[dialogue]]
speaker = "クロト"
# 「……っ！？　なんだ、力が抜ける……！？」
line = "「……っ！？　なんだ、力が抜ける……！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「何、これ……ちょっと体が重いんだけど……」
line = "「何、これ……ちょっと体が重いんだけど……」"

[[dialogue]]
speaker = "アポロ"
# 「ぐぅぅっ……ぐぬぬ……」
line = "「ぐぅぅっ……ぐぬぬ……」"

[[dialogue]]
speaker = "メルエル"
# 「体が……うご、かない……」
line = "「体が……うご、かない……」"

[[dialogue]]
speaker = "unk"
# 神殿に光が走った瞬間、俺とヴィーナス、アポロ、メルエルがその場に膝をつく。
line = "神殿に光が走った瞬間、俺とヴィーナス、アポロ、メルエルがその場に膝をつく。"

[[dialogue]]
speaker = "unk"
# 星力が勝手に放出されてしまって、うまく体に力が入らない。
line = "星力が勝手に放出されてしまって、うまく体に力が入らない。"

[[dialogue]]
speaker = "ジグ"
# 「神殿の仕掛けに細工させてもらったんだ。どうだい、戦ったばかりだからリラックスにはちょうどいいだろう？」
line = "「神殿の仕掛けに細工させてもらったんだ。どうだい、戦ったばかりだからリラックスにはちょうどいいだろう？」"

[[dialogue]]
speaker = "グレイス"
# 「何が起こっているんですか！？　私は何も感じないんですけど！？」
line = "「何が起こっているんですか！？　私は何も感じないんですけど！？」"

[[dialogue]]
speaker = "ナターシャ"
# 「多分、魔王関係者にしか効かない仕掛けじゃないかな。他にも魔王対策の罠があったし」
line = "「多分、魔王関係者にしか効かない仕掛けじゃないかな。他にも魔王対策の罠があったし」"

[[dialogue]]
speaker = "メルエル"
# （えっ……！？　魔王対策ならどうして私にも効いてるの……！？）
line = "（えっ……！？　魔王対策ならどうして私にも効いてるの……！？）"

[[dialogue]]
speaker = "梨緒"
# 「！？　女神の神殿が揺れて……いや、動いている！？」
line = "「！？　女神の神殿が揺れて……いや、動いている！？」"

[[dialogue]]
speaker = "梨緒"
# 「何をした、ジグ！？」
line = "「何をした、ジグ！？」"

[[dialogue]]
speaker = "ジグ"
# 「神殿の機能をいじって行き先を設定させてもらったんだ」
line = "「神殿の機能をいじって行き先を設定させてもらったんだ」"

[[dialogue]]
speaker = "ジグ"
# 「女神の神殿はもうすぐ──聖庭園に衝突するよ」
line = "「女神の神殿はもうすぐ──聖庭園に衝突するよ」"
