[[dialogue]]
speaker = "unk"
# 第１８話,仮面の少女？,B
line = "第１８話,仮面の少女？,B"

[[dialogue]]
speaker = "？？？"
# 「やっほー！　見てたよ、今の戦い！　あの大群を一人で倒しちゃうなんてすごいじゃん！」
line = "「やっほー！　見てたよ、今の戦い！　あの大群を一人で倒しちゃうなんてすごいじゃん！」"

[[dialogue]]
speaker = "クロト"
# 「君は……？　というか危ないぞ、今の今まで危険なモンスター達が……」
line = "「君は……？　というか危ないぞ、今の今まで危険なモンスター達が……」"

[[dialogue]]
speaker = "？？？"
# 「あはは。気にしない気にしない！」
line = "「あはは。気にしない気にしない！」"

[[dialogue]]
speaker = "unk"
# あっけらかんと笑う仮面の少女。見覚えはなかった。
line = "あっけらかんと笑う仮面の少女。見覚えはなかった。"

[[dialogue]]
speaker = "クロト"
# 「（というか今この子、どこから……？）」
line = "「（というか今この子、どこから……？）」"

[[dialogue]]
speaker = "？？？"
# 「お兄さんかっこいいなあって思っただけ！　もっと強い敵も倒せる？」
line = "「お兄さんかっこいいなあって思っただけ！　もっと強い敵も倒せる？」"

[[dialogue]]
speaker = "クロト"
# 「どうだろう……でも必要なら、きっと戦うと思う」
line = "「どうだろう……でも必要なら、きっと戦うと思う」"

[[dialogue]]
speaker = "？？？"
# 「ふーん」
line = "「ふーん」"

[[dialogue]]
speaker = "unk"
# 少女は、にやついた笑みを浮かべてこちらを見てくる。
line = "少女は、にやついた笑みを浮かべてこちらを見てくる。"

[[dialogue]]
speaker = "unk"
# 変な子だ。
line = "変な子だ。"

[[dialogue]]
speaker = "クロト"
# 「お父さんとお母さんは？　いないなら俺が付き添って──」
line = "「お父さんとお母さんは？　いないなら俺が付き添って──」"

[[dialogue]]
speaker = "？？？"
# 「あはは、大丈夫大丈夫！　もう帰るから！」
line = "「あはは、大丈夫大丈夫！　もう帰るから！」"

[[dialogue]]
speaker = "？？？"
# 「んじゃおにーさんも頑張ってね！　今の力なら、どんな強い相手だってへっちゃらだよ！」
line = "「んじゃおにーさんも頑張ってね！　今の力なら、どんな強い相手だってへっちゃらだよ！」"

[[dialogue]]
speaker = "クロト"
# 「ああ……」
line = "「ああ……」"

[[dialogue]]
speaker = "クロト"
# 「……！？」
line = "「……！？」"

[[dialogue]]
speaker = "unk"
# 君の名前は──と、訊ねるまでもなく。少女は、ぴょんぴょんと辺りの屋根を飛び渡って夜闇に消えてしまった。
line = "君の名前は──と、訊ねるまでもなく。少女は、ぴょんぴょんと辺りの屋根を飛び渡って夜闇に消えてしまった。"

[[dialogue]]
speaker = "unk"
# なんという身のこなし。
line = "なんという身のこなし。"

[[dialogue]]
speaker = "unk"
# 一瞬、自分が見ていた夢じゃないかと思ってしまった。
line = "一瞬、自分が見ていた夢じゃないかと思ってしまった。"

[[dialogue]]
speaker = "クロト"
# 「どんな強い相手でも……か」
line = "「どんな強い相手でも……か」"

[[dialogue]]
speaker = "unk"
# 俺は、少女の言葉に感じ入るものを覚えながら……
line = "俺は、少女の言葉に感じ入るものを覚えながら……"

[[dialogue]]
speaker = "unk"
# 明日に備えて、家に帰って体を休めることにした。
line = "明日に備えて、家に帰って体を休めることにした。"

[[dialogue]]
speaker = "アナ"
# 「これはまた、凄いですね……」
line = "「これはまた、凄いですね……」"

[[dialogue]]
speaker = "unk"
# 近隣住民の通報を受けて寮からアナとサーシャが現場に急行すると、そこではすべてが終わっていた。
line = "近隣住民の通報を受けて寮からアナとサーシャが現場に急行すると、そこではすべてが終わっていた。"

[[dialogue]]
speaker = "サーシャ"
# 「あら～、これ全部、クロトくんがやったの？」
line = "「あら～、これ全部、クロトくんがやったの？」"

[[dialogue]]
speaker = "アナ"
# 「状況から推察するに、恐らく」
line = "「状況から推察するに、恐らく」"

[[dialogue]]
speaker = "サーシャ"
# 「戦いの痕跡から考えると、３０体近くいたんじゃないかしら」
line = "「戦いの痕跡から考えると、３０体近くいたんじゃないかしら」"

[[dialogue]]
speaker = "サーシャ"
# 「アナちゃんはこれ、一人でできる？」
line = "「アナちゃんはこれ、一人でできる？」"

[[dialogue]]
speaker = "アナ"
# 「まず不可能かと」
line = "「まず不可能かと」"

[[dialogue]]
speaker = "サーシャ"
# 「そうよねぇ～。私も無理だと思うわ」
line = "「そうよねぇ～。私も無理だと思うわ」"

[[dialogue]]
speaker = "アナ"
# 「これが、現会長の言う、魔王の力……」
line = "「これが、現会長の言う、魔王の力……」"

[[dialogue]]
speaker = "サーシャ"
# 「本音を言えば、今すぐクロトくんから話を聞きたいところだけれど……」
line = "「本音を言えば、今すぐクロトくんから話を聞きたいところだけれど……」"

[[dialogue]]
speaker = "アナ"
# 「明日は御前試合本番」
line = "「明日は御前試合本番」"

[[dialogue]]
speaker = "サーシャ"
# 「そうなのよねぇ～」
line = "「そうなのよねぇ～」"

[[dialogue]]
speaker = "アナ"
# 「……次期会長は無事」
line = "「……次期会長は無事」"

[[dialogue]]
speaker = "unk"
# アナの元へ先日連絡先を交換したリノから、クロトが無事帰宅したという連絡が届いていた。
line = "アナの元へ先日連絡先を交換したリノから、クロトが無事帰宅したという連絡が届いていた。"

[[dialogue]]
speaker = "サーシャ"
# 「そっかそっか～。お疲れみたいだったし、やっぱり今日は休んでほしいわよねぇ」
line = "「そっかそっか～。お疲れみたいだったし、やっぱり今日は休んでほしいわよねぇ」"

[[dialogue]]
speaker = "アナ"
# 「詳しいことは、明日全部わかる」
line = "「詳しいことは、明日全部わかる」"

[[dialogue]]
speaker = "サーシャ"
# 「そうね～。ヴィーナスちゃんも説明不足なところあるし、明日が終わったら私たちも色々聞かせてもらおうかしら」
line = "「そうね～。ヴィーナスちゃんも説明不足なところあるし、明日が終わったら私たちも色々聞かせてもらおうかしら」"

[[dialogue]]
speaker = "アナ"
# 「そうしましょう」
line = "「そうしましょう」"

[[dialogue]]
speaker = "unk"
# アナはこくりとうなずきつつ、現場を学園職員に引き渡すため、各所に連絡を飛ばし始めるのだった。
line = "アナはこくりとうなずきつつ、現場を学園職員に引き渡すため、各所に連絡を飛ばし始めるのだった。"
