[[dialogue]]
speaker = "unk"
# 第１０話,ベガの光,B
line = "第１０話,ベガの光,B"

[[dialogue]]
speaker = "梨緒"
# 「私はリクリエの使徒にはならない。君も戻ってこい、ジグ！」
line = "「私はリクリエの使徒にはならない。君も戻ってこい、ジグ！」"

[[dialogue]]
speaker = "ジグ"
# 「馬鹿な……！　“真なる神”の天啓を拒むなど、何かの間違いだ……！」
line = "「馬鹿な……！　“真なる神”の天啓を拒むなど、何かの間違いだ……！」"

[[dialogue]]
speaker = "unk"
# 梨緒は己の決意で、リクリエの使徒への誘惑を絶ち切った。
line = "梨緒は己の決意で、リクリエの使徒への誘惑を絶ち切った。"

[[dialogue]]
speaker = "unk"
# それを目の当たりにしたジグからいつもの余裕が完全に消え去り、声に怒りがにじむ。
line = "それを目の当たりにしたジグからいつもの余裕が完全に消え去り、声に怒りがにじむ。"

[[dialogue]]
speaker = "ジグ"
# 「君が“真なる神”の声を拒めるはずがない！　あんなに弱かった君が！」
line = "「君が“真なる神”の声を拒めるはずがない！　あんなに弱かった君が！」"

[[dialogue]]
speaker = "unk"
# もう一度瘴気が仮面を形作り、再び梨緒に仮面が装着される。
line = "もう一度瘴気が仮面を形作り、再び梨緒に仮面が装着される。"

[[dialogue]]
speaker = "unk"
# しかし梨緒は避けることすらしなかった。
line = "しかし梨緒は避けることすらしなかった。"

[[dialogue]]
speaker = "幼い梨緒"
# 『うぅ……ぐす……ひくっ……』
line = "『うぅ……ぐす……ひくっ……』"

[[dialogue]]
speaker = "幼い梨緒"
# 『どうして……？　どうして私、何もできないの？　算数も運動もできなくて……絵もぐちゃぐちゃだし、歌もダメで……』
line = "『どうして……？　どうして私、何もできないの？　算数も運動もできなくて……絵もぐちゃぐちゃだし、歌もダメで……』"

[[dialogue]]
speaker = "梨緒"
# （私は何もできない子だった。かけっこも、勉強も、お絵かきも、何をしても勝てなくて、負ける度に泣いていた）
line = "（私は何もできない子だった。かけっこも、勉強も、お絵かきも、何をしても勝てなくて、負ける度に泣いていた）"

[[dialogue]]
speaker = "幼い梨緒"
# 『私が星騎士になれる……！？　こんな私でも……？』
line = "『私が星騎士になれる……！？　こんな私でも……？』"

[[dialogue]]
speaker = "幼い梨緒"
# 『星騎士になれば、私は──』
line = "『星騎士になれば、私は──』"

[[dialogue]]
speaker = "幼い梨緒"
# 『負けない』
line = "『負けない』"

[[dialogue]]
speaker = "梨緒"
# （だから私は星騎士になった。星騎士になれば、もう負けないと思ったから）
line = "（だから私は星騎士になった。星騎士になれば、もう負けないと思ったから）"

[[dialogue]]
speaker = "梨緒"
# （ジグが嫌いだった。何をしても勝てない、弱い自分を思い出させられるから）
line = "（ジグが嫌いだった。何をしても勝てない、弱い自分を思い出させられるから）"

[[dialogue]]
speaker = "梨緒"
# （ジグに負ける度に思っていた。こんなはずじゃない、やり直したい、と）
line = "（ジグに負ける度に思っていた。こんなはずじゃない、やり直したい、と）"

[[dialogue]]
speaker = "梨緒"
# （だけど──）
line = "（だけど──）"

[[dialogue]]
speaker = "ベアトリス"
# 「泣くならちゃんと、私の見えるところで泣いて。そうじゃないと、必要な時に助けられなくなっちゃう」
line = "「泣くならちゃんと、私の見えるところで泣いて。そうじゃないと、必要な時に助けられなくなっちゃう」"

[[dialogue]]
speaker = "ベアトリス"
# 「まだ結成して日は浅いかもしれないけど、私たちは同じ、選挙管理委員会の仲間でしょ？」
line = "「まだ結成して日は浅いかもしれないけど、私たちは同じ、選挙管理委員会の仲間でしょ？」"

[[dialogue]]
speaker = "ナターシャ"
# 「うん、負けを認められないのは梨緒の弱いところだと思ってるけど、かわいげがあるじゃん」
line = "「うん、負けを認められないのは梨緒の弱いところだと思ってるけど、かわいげがあるじゃん」"

[[dialogue]]
speaker = "ナターシャ"
# 「何でもかんでもその調子じゃ困るけど、負けて悔しがってる梨緒を見るのは嫌いじゃないからね」
line = "「何でもかんでもその調子じゃ困るけど、負けて悔しがってる梨緒を見るのは嫌いじゃないからね」"

[[dialogue]]
speaker = "アポロ"
# 「オマエは全てを失ったかもしれない。あたしたちじゃ、オマエが失くしたものの代わりになれないなんてわかってる」
line = "「オマエは全てを失ったかもしれない。あたしたちじゃ、オマエが失くしたものの代わりになれないなんてわかってる」"

[[dialogue]]
speaker = "アポロ"
# 「それでも今、オマエは１人じゃない。あたしたちがいる！」
line = "「それでも今、オマエは１人じゃない。あたしたちがいる！」"

[[dialogue]]
speaker = "梨緒"
# （負け続けたから出会えた仲間がいる）
line = "（負け続けたから出会えた仲間がいる）"

[[dialogue]]
speaker = "梨緒"
# （仲間のおかげで、弱い自分も認められるようになった）
line = "（仲間のおかげで、弱い自分も認められるようになった）"

[[dialogue]]
speaker = "梨緒"
# （自分の弱さから目を逸らすために、世界を救うと嘯いて、星騎士になった）
line = "（自分の弱さから目を逸らすために、世界を救うと嘯いて、星騎士になった）"

[[dialogue]]
speaker = "梨緒"
# （だけどその嘘を信じてもがき続けていなければ、ここまで戦ってこれなかった）
line = "（だけどその嘘を信じてもがき続けていなければ、ここまで戦ってこれなかった）"

[[dialogue]]
speaker = "梨緒"
# （ベガの最期の時、抵抗を諦めてジグを見捨て、ジグはリクリエの使徒にされた）
line = "（ベガの最期の時、抵抗を諦めてジグを見捨て、ジグはリクリエの使徒にされた）"

[[dialogue]]
speaker = "梨緒"
# （情けなくて、自分の弱さが嫌で、一度は忘却すらしてしまった。それでもあの時立ち向かっていれば、私は生きていなかった）
line = "（情けなくて、自分の弱さが嫌で、一度は忘却すらしてしまった。それでもあの時立ち向かっていれば、私は生きていなかった）"

[[dialogue]]
speaker = "梨緒"
# （弱い自分がいたから、私は今ここにいる）
line = "（弱い自分がいたから、私は今ここにいる）"

[[dialogue]]
speaker = "梨緒"
# 「人は弱いか強いかじゃない。弱くて強いんだ」
line = "「人は弱いか強いかじゃない。弱くて強いんだ」"

[[dialogue]]
speaker = "梨緒"
# 「弱さを強さに変えて、君に勝つ！　それが私だ！」
line = "「弱さを強さに変えて、君に勝つ！　それが私だ！」"

[[dialogue]]
speaker = "ジグ"
# 「──ッ！？」
line = "「──ッ！？」"

[[dialogue]]
speaker = "梨緒"
# 「私をリクリエの使徒にしようとしても、もう通用しないぞ、ジグ」
line = "「私をリクリエの使徒にしようとしても、もう通用しないぞ、ジグ」"

[[dialogue]]
speaker = "ジグ"
# 「何故だ！？　どうして“真なる神”の声を拒絶する！？　どうして拒めるんだ！？」
line = "「何故だ！？　どうして“真なる神”の声を拒絶する！？　どうして拒めるんだ！？」"

[[dialogue]]
speaker = "梨緒"
# 「だって使徒になったら、君に勝てないじゃないか」
line = "「だって使徒になったら、君に勝てないじゃないか」"

[[dialogue]]
speaker = "ジグ"
# 「は──？」
line = "「は──？」"

[[dialogue]]
speaker = "梨緒"
# 「私は君に勝ちたいし、勝つまで勝負をやめるつもりはない。勝ち逃げはさせないぞ」
line = "「私は君に勝ちたいし、勝つまで勝負をやめるつもりはない。勝ち逃げはさせないぞ」"

[[dialogue]]
speaker = "ジグ"
# 「は？　はぁ？　こんな時に何を言っているんだ……？」
line = "「は？　はぁ？　こんな時に何を言っているんだ……？」"

[[dialogue]]
speaker = "unk"
# あくまで個人の勝負にこだわる場違いな言葉に、忘我するほどの混乱を見せるジグ。
line = "あくまで個人の勝負にこだわる場違いな言葉に、忘我するほどの混乱を見せるジグ。"

[[dialogue]]
speaker = "unk"
# だがジグを見つめる梨緒の表情は何もふざけてなどいなかった。
line = "だがジグを見つめる梨緒の表情は何もふざけてなどいなかった。"

[[dialogue]]
speaker = "梨緒"
# 「自分を失いたくないばかりに、勝ちにこだわるのは私の弱さだ」
line = "「自分を失いたくないばかりに、勝ちにこだわるのは私の弱さだ」"

[[dialogue]]
speaker = "梨緒"
# 「だけど自分の弱さを少しは認められるようになった。今さら君に勝てなかったからといって、私が私でなくなるとは思わない」
line = "「だけど自分の弱さを少しは認められるようになった。今さら君に勝てなかったからといって、私が私でなくなるとは思わない」"

[[dialogue]]
speaker = "梨緒"
# 「それでも君に勝ちたいという気持ちを消し去ることはできない」
line = "「それでも君に勝ちたいという気持ちを消し去ることはできない」"

[[dialogue]]
speaker = "梨緒"
# 「君に勝つために、リクリエの使徒になんてなっている暇はない！！」
line = "「君に勝つために、リクリエの使徒になんてなっている暇はない！！」"

[[dialogue]]
speaker = "ベアトリス"
# 「さすが梨緒ちゃん！」
line = "「さすが梨緒ちゃん！」"

[[dialogue]]
speaker = "ナターシャ"
# 「結局、梨緒は梨緒ってことか……一周回ってかっこよく見えてきたよ」
line = "「結局、梨緒は梨緒ってことか……一周回ってかっこよく見えてきたよ」"

[[dialogue]]
speaker = "ナターシャ"
# 「まぁ、負けられない戦いだし、意地張ってるくらいでちょうどいいか」
line = "「まぁ、負けられない戦いだし、意地張ってるくらいでちょうどいいか」"

[[dialogue]]
speaker = "ベアトリス"
# 「私、梨緒ちゃんが必ず勝つって信じてるから！」
line = "「私、梨緒ちゃんが必ず勝つって信じてるから！」"

[[dialogue]]
speaker = "ベアトリス"
# 「梨緒ちゃん──」
line = "「梨緒ちゃん──」"

[[dialogue]]
speaker = "ナターシャ"
# 「梨緒──」
line = "「梨緒──」"

[[dialogue]]
speaker = "２人"
# 「勝って！！」
line = "「勝って！！」"

[[dialogue]]
speaker = "梨緒"
# 「ああ！　私は今度こそ勝つ！」
line = "「ああ！　私は今度こそ勝つ！」"

[[dialogue]]
speaker = "梨緒"
# 「今まで何度も“今度こそ”と言って負けてきた。それでも言う。勝つまで何度でも言ってやる──“今度こそ”と！」
line = "「今まで何度も“今度こそ”と言って負けてきた。それでも言う。勝つまで何度でも言ってやる──“今度こそ”と！」"

[[dialogue]]
speaker = "梨緒"
# 「君を救うには、君に勝つしかないのだから！」
line = "「君を救うには、君に勝つしかないのだから！」"

[[dialogue]]
speaker = "ジグ"
# 「そうかい。君はそうまでして“真なる神”の救いを拒むんだね」
line = "「そうかい。君はそうまでして“真なる神”の救いを拒むんだね」"

[[dialogue]]
speaker = "ジグ"
# 「君はどうしようもない愚か者だ。その愚かさを、命で償ってもらおう！」
line = "「君はどうしようもない愚か者だ。その愚かさを、命で償ってもらおう！」"

[[dialogue]]
speaker = "unk"
# ジグの剣に炎が滾り、攻撃が激しさを増す。
line = "ジグの剣に炎が滾り、攻撃が激しさを増す。"

[[dialogue]]
speaker = "unk"
# 首や心臓、一撃で致命となる急所ばかり狙った攻撃を繰り出すが、梨緒は斬撃をことごとく躱していく。
line = "首や心臓、一撃で致命となる急所ばかり狙った攻撃を繰り出すが、梨緒は斬撃をことごとく躱していく。"

[[dialogue]]
speaker = "梨緒"
# 「より速く……より鋭く……！　運命の糸を手繰り寄せろ……！」
line = "「より速く……より鋭く……！　運命の糸を手繰り寄せろ……！」"

[[dialogue]]
speaker = "梨緒"
# 「見えた！」
line = "「見えた！」"

[[dialogue]]
speaker = "ジグ"
# 「くっ……！」
line = "「くっ……！」"

[[dialogue]]
speaker = "ジグ"
# 「何故だ……！？　『可能性』の中ではまだ私が勝っている！　もう梨緒を幾万──いや、億は斬った！」
line = "「何故だ……！？　『可能性』の中ではまだ私が勝っている！　もう梨緒を幾万──いや、億は斬った！」"

[[dialogue]]
speaker = "ジグ"
# 「なのに何故、この眼で見れば見るほど、可能性が増えていく……！？」
line = "「なのに何故、この眼で見れば見るほど、可能性が増えていく……！？」"

[[dialogue]]
speaker = "梨緒"
# 「君に勝つためなら増えもするさっ！」
line = "「君に勝つためなら増えもするさっ！」"

[[dialogue]]
speaker = "梨緒"
# 「私は負けて、負けて、負け続けて……その敗北が糧になる。私は負けるほど強くなるんだ……！」
line = "「私は負けて、負けて、負け続けて……その敗北が糧になる。私は負けるほど強くなるんだ……！」"

[[dialogue]]
speaker = "梨緒"
# （私はジグが嫌いだった。負けるのが嫌だった）
line = "（私はジグが嫌いだった。負けるのが嫌だった）"

[[dialogue]]
speaker = "梨緒"
# （だけどそれだけじゃなかった）
line = "（だけどそれだけじゃなかった）"

[[dialogue]]
speaker = "梨緒"
# （ジグとの勝負は自分を高めてくれた）
line = "（ジグとの勝負は自分を高めてくれた）"

[[dialogue]]
speaker = "梨緒"
# （ジグと勝負するのが楽しかった）
line = "（ジグと勝負するのが楽しかった）"

[[dialogue]]
speaker = "梨緒"
# （私はジグとの勝負が好きだった）
line = "（私はジグとの勝負が好きだった）"

[[dialogue]]
speaker = "梨緒"
# （だからありがとう、ジグ）
line = "（だからありがとう、ジグ）"

[[dialogue]]
speaker = "梨緒"
# 「ジグ──君は私のライバルだ！　君が私をそう思っていなくても！」
line = "「ジグ──君は私のライバルだ！　君が私をそう思っていなくても！」"

[[dialogue]]
speaker = "ジグ"
# 「君は本当に身勝手だな……！　私は君が嫌いだと言っただろう！」
line = "「君は本当に身勝手だな……！　私は君が嫌いだと言っただろう！」"

[[dialogue]]
speaker = "梨緒"
# 「問題ない！　私だって君が気に入らない！」
line = "「問題ない！　私だって君が気に入らない！」"

[[dialogue]]
speaker = "ジグ"
# 「話が通じないな、このストーカー！」
line = "「話が通じないな、このストーカー！」"

[[dialogue]]
speaker = "梨緒"
# 「気安くアガサと呼んできたのは君の方だろう！」
line = "「気安くアガサと呼んできたのは君の方だろう！」"

[[dialogue]]
speaker = "ジグ"
# 「こんなにしつこい女だとは思わなかったさ！」
line = "「こんなにしつこい女だとは思わなかったさ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「うわー、天使みんなの命がかかってるのに超低レベル……」
line = "「うわー、天使みんなの命がかかってるのに超低レベル……」"

[[dialogue]]
speaker = "ベアトリス"
# 「あはは、梨緒ちゃんらしいね」
line = "「あはは、梨緒ちゃんらしいね」"

[[dialogue]]
speaker = "unk"
# 梨緒は一見クールで凛々しく見えるが、中身は子どもっぽくて、強情の塊だ。
line = "梨緒は一見クールで凛々しく見えるが、中身は子どもっぽくて、強情の塊だ。"

[[dialogue]]
speaker = "unk"
# 世界の命運がかかっていても、梨緒はどうしようもなく梨緒だった。
line = "世界の命運がかかっていても、梨緒はどうしようもなく梨緒だった。"

[[dialogue]]
speaker = "ジグ"
# 「君は私が殺す。我が神のため、新しい世界のために……！」
line = "「君は私が殺す。我が神のため、新しい世界のために……！」"

[[dialogue]]
speaker = "unk"
# 劫火とリクリエの力を漲らせて、その命を絶たんと襲い掛かるジグ。
line = "劫火とリクリエの力を漲らせて、その命を絶たんと襲い掛かるジグ。"

[[dialogue]]
speaker = "unk"
# 梨緒も自身の星力と、ノルンの霊力を全開にして迎え撃つ。
line = "梨緒も自身の星力と、ノルンの霊力を全開にして迎え撃つ。"

[[dialogue]]
speaker = "ジグ"
# 「はぁああっ！」
line = "「はぁああっ！」"

[[dialogue]]
speaker = "梨緒"
# 「おおおぉっ！」
line = "「おおおぉっ！」"

[[dialogue]]
speaker = "unk"
# ジグはリクリエの力を最大まで解放し、その圧倒的な力で梨緒を押し潰そうとする。
line = "ジグはリクリエの力を最大まで解放し、その圧倒的な力で梨緒を押し潰そうとする。"

[[dialogue]]
speaker = "梨緒"
# （ジグも全力を出してきた。それは追い込まれているということだ。ようやく勝利が見えてきた）
line = "（ジグも全力を出してきた。それは追い込まれているということだ。ようやく勝利が見えてきた）"

[[dialogue]]
speaker = "梨緒"
# （だが、たとえジグを倒して仮面を割ったとしても、リクリエの力がある限り、仮面は再生する）
line = "（だが、たとえジグを倒して仮面を割ったとしても、リクリエの力がある限り、仮面は再生する）"

[[dialogue]]
speaker = "梨緒"
# （ジグの中のリクリエだけを消し去る方法はないか？　私とノルンの力だけでは……）
line = "（ジグの中のリクリエだけを消し去る方法はないか？　私とノルンの力だけでは……）"

[[dialogue]]
speaker = "？？？"
# 『梨緒、聞こえる？』
line = "『梨緒、聞こえる？』"

[[dialogue]]
speaker = "梨緒"
# 「！？　この声は──」
line = "「！？　この声は──」"

[[dialogue]]
speaker = "？？？"
# 『ようやく話せたわね、梨緒』
line = "『ようやく話せたわね、梨緒』"

[[dialogue]]
speaker = "梨緒"
# 「ここは……？　君は誰だ……？」
line = "「ここは……？　君は誰だ……？」"

[[dialogue]]
speaker = "ノルン"
# 『ここはあなたの精神世界──夢みたいなものよ。私はノルン。最初の守護天使、《運命》のノルンと言えばわかるかしら』
line = "『ここはあなたの精神世界──夢みたいなものよ。私はノルン。最初の守護天使、《運命》のノルンと言えばわかるかしら』"

[[dialogue]]
speaker = "梨緒"
# 「！　君が……私の中にいる守護天使なのか……」
line = "「！　君が……私の中にいる守護天使なのか……」"

[[dialogue]]
speaker = "ノルン"
# 『ええ、そうよ。あなたが私の力を使いこなすのに時間がかかったおかげで、話すのも今さらになっちゃったわ』
line = "『ええ、そうよ。あなたが私の力を使いこなすのに時間がかかったおかげで、話すのも今さらになっちゃったわ』"

[[dialogue]]
speaker = "梨緒"
# 「それはすまない……だが君、そんな性格だったのか……」
line = "「それはすまない……だが君、そんな性格だったのか……」"

[[dialogue]]
speaker = "梨緒"
# 「私は君のおかげで生きながらえて、ここまで来ることができた。感謝する」
line = "「私は君のおかげで生きながらえて、ここまで来ることができた。感謝する」"

[[dialogue]]
speaker = "梨緒"
# 「だがどうして私に力を貸してくれたんだ……？」
line = "「だがどうして私に力を貸してくれたんだ……？」"

[[dialogue]]
speaker = "ノルン"
# 『私はラクシャの言う通り、リクリエに敗れ、残滓として時空の狭間を彷徨っていた』
line = "『私はラクシャの言う通り、リクリエに敗れ、残滓として時空の狭間を彷徨っていた』"

[[dialogue]]
speaker = "ノルン"
# 『そこに、ディザスターハンドの力の余波で飛ばされてきたあなたがやってきた』
line = "『そこに、ディザスターハンドの力の余波で飛ばされてきたあなたがやってきた』"

[[dialogue]]
speaker = "ノルン"
# 『それはただの偶然。創造神でもなく、女神様でもなく、誰が意図したものでもない』
line = "『それはただの偶然。創造神でもなく、女神様でもなく、誰が意図したものでもない』"

[[dialogue]]
speaker = "ノルン"
# 『死に瀕しているあなたを救うために、私はあなたの半身になることにした』
line = "『死に瀕しているあなたを救うために、私はあなたの半身になることにした』"

[[dialogue]]
speaker = "ノルン"
# 『もちろんリクリエと戦うためでもあるけど。私はリクリエに対抗するために、女神テルル様に生み出された第一世代の守護天使なんだから』
line = "『もちろんリクリエと戦うためでもあるけど。私はリクリエに対抗するために、女神テルル様に生み出された第一世代の守護天使なんだから』"

[[dialogue]]
speaker = "ノルン"
# 『ベガから飛ばされてきたあなたは世界を滅ぼされ、ジグを見捨ててしまった絶望に打ちひしがれていた』
line = "『ベガから飛ばされてきたあなたは世界を滅ぼされ、ジグを見捨ててしまった絶望に打ちひしがれていた』"

[[dialogue]]
speaker = "ノルン"
# 『だけど、あなたなら一度絶望しても──いいえ、何度心折れても、また立ち上がってくれると信じていたわ』
line = "『だけど、あなたなら一度絶望しても──いいえ、何度心折れても、また立ち上がってくれると信じていたわ』"

[[dialogue]]
speaker = "梨緒"
# 「そこまで私を信じてくれていたんだな」
line = "「そこまで私を信じてくれていたんだな」"

[[dialogue]]
speaker = "ノルン"
# 『ええ、あなたのことはわかるわ。私も負けず嫌いだから』
line = "『ええ、あなたのことはわかるわ。私も負けず嫌いだから』"

[[dialogue]]
speaker = "梨緒"
# 「フ──なるほど。私も君も、死に損ないの上に筋金入りの負けず嫌いで、似た者同士のようだ」
line = "「フ──なるほど。私も君も、死に損ないの上に筋金入りの負けず嫌いで、似た者同士のようだ」"

[[dialogue]]
speaker = "ノルン"
# 『今のあなたなら、私の力を──いえ、みんなの力を使うことができるわ』
line = "『今のあなたなら、私の力を──いえ、みんなの力を使うことができるわ』"

[[dialogue]]
speaker = "梨緒"
# 「みんな……？　まさか君以外の第一世代の守護天使か？」
line = "「みんな……？　まさか君以外の第一世代の守護天使か？」"

[[dialogue]]
speaker = "ノルン"
# 『いいえ、あなたのよく知る人たちよ』
line = "『いいえ、あなたのよく知る人たちよ』"

[[dialogue]]
speaker = "梨緒"
# 「──！」
line = "「──！」"

[[dialogue]]
speaker = "梨緒"
# 「この力は……太陽と月の守護星……それだけじゃない、他の星の力も感じる……」
line = "「この力は……太陽と月の守護星……それだけじゃない、他の星の力も感じる……」"

[[dialogue]]
speaker = "梨緒"
# 「しかもこの星々は、アルタイルのものじゃない……」
line = "「しかもこの星々は、アルタイルのものじゃない……」"

[[dialogue]]
speaker = "ノルン"
# 『私は《運命》のノルン。因果の摂理を司る者。そして運命の糸を紡ぐ者』
line = "『私は《運命》のノルン。因果の摂理を司る者。そして運命の糸を紡ぐ者』"

[[dialogue]]
speaker = "ノルン"
# 『あなたがベガからアルタイルに飛ばされてくる時、守護星と運命の糸を結んでおいたわ。あなたの仲間──ベガの星騎士の守護星とね』
line = "『あなたがベガからアルタイルに飛ばされてくる時、守護星と運命の糸を結んでおいたわ。あなたの仲間──ベガの星騎士の守護星とね』"

[[dialogue]]
speaker = "梨緒"
# 「ベガの……みんなの……守護星……」
line = "「ベガの……みんなの……守護星……」"

[[dialogue]]
speaker = "ノルン"
# 『あなたは私の運命の糸を通して、ベガと繋がっている。本当に細い、今にも切れてしまいそうな繋がりだけど』
line = "『あなたは私の運命の糸を通して、ベガと繋がっている。本当に細い、今にも切れてしまいそうな繋がりだけど』"

[[dialogue]]
speaker = "ノルン"
# 『私の力を解放しても、もしあなたが弱いままであれば、ベガの滅びの因果に呑み込まれていたわ』
line = "『私の力を解放しても、もしあなたが弱いままであれば、ベガの滅びの因果に呑み込まれていたわ』"

[[dialogue]]
speaker = "ノルン"
# 『だけど梨緒・Ａ・クリステレスは、アルタイルに根付き、独自の因果を紡ぐ存在になった。あなた自身の成長と、仲間との関わりのおかげでね』
line = "『だけど梨緒・Ａ・クリステレスは、アルタイルに根付き、独自の因果を紡ぐ存在になった。あなた自身の成長と、仲間との関わりのおかげでね』"

[[dialogue]]
speaker = "ノルン"
# 『今なら滅びたベガの因果に引き寄せられることなく、運命の糸を通して守護星の力を呼び起こせるわ』
line = "『今なら滅びたベガの因果に引き寄せられることなく、運命の糸を通して守護星の力を呼び起こせるわ』"

[[dialogue]]
speaker = "ノルン"
# 『守護天使ノルンの──いえ、ベガの星騎士の真の力を見せてやりなさい！』
line = "『守護天使ノルンの──いえ、ベガの星騎士の真の力を見せてやりなさい！』"

[[dialogue]]
speaker = "梨緒"
# 「私はまだ……いいや、ずっとベガと繋がっていたんだな」
line = "「私はまだ……いいや、ずっとベガと繋がっていたんだな」"

[[dialogue]]
speaker = "梨緒"
# 「ありがとう、ノルン」
line = "「ありがとう、ノルン」"

[[dialogue]]
speaker = "ノルン"
# 『ええ、存分に恩に着るといいわ』
line = "『ええ、存分に恩に着るといいわ』"

[[dialogue]]
speaker = "ノルン"
# 『私がここまでやってあげたんだから勝ちなさい！　梨緒！』
line = "『私がここまでやってあげたんだから勝ちなさい！　梨緒！』"

[[dialogue]]
speaker = "梨緒"
# 「ああ、行ってくる！」
line = "「ああ、行ってくる！」"

[[dialogue]]
speaker = "ジグ"
# 「焼き尽くせ──シャルラハロート・フリューゲル！」
line = "「焼き尽くせ──シャルラハロート・フリューゲル！」"

[[dialogue]]
speaker = "unk"
# ジグが魔剣を薙ぎ払うと、炎の奔流が竜となり、翼を広げて襲い掛かる。
line = "ジグが魔剣を薙ぎ払うと、炎の奔流が竜となり、翼を広げて襲い掛かる。"

[[dialogue]]
speaker = "梨緒"
# 「力を貸してくれ──<b>エリシア</b>！」
line = "「力を貸してくれ──<b>エリシア</b>！」"

[[dialogue]]
speaker = "unk"
# 迎え撃つ梨緒の手の中に、灼熱の太陽が生まれる。
line = "迎え撃つ梨緒の手の中に、灼熱の太陽が生まれる。"

[[dialogue]]
speaker = "梨緒"
# 「ヒューペリオンイレイザー！！」
line = "「ヒューペリオンイレイザー！！」"

[[dialogue]]
speaker = "unk"
# そして竜と太陽がぶつかり合い、神殿を揺るがす衝撃と共に相殺された。
line = "そして竜と太陽がぶつかり合い、神殿を揺るがす衝撃と共に相殺された。"

[[dialogue]]
speaker = "ジグ"
# 「な……！？　その星術はエリシアの……！？」
line = "「な……！？　その星術はエリシアの……！？」"

[[dialogue]]
speaker = "梨緒"
# 「ああ、そうだ。どうやら私は知らず知らずのうちに、守護天使ノルンだけでなく、ベガのみんなの力を借りていたらしい」
line = "「ああ、そうだ。どうやら私は知らず知らずのうちに、守護天使ノルンだけでなく、ベガのみんなの力を借りていたらしい」"

[[dialogue]]
speaker = "梨緒"
# 「フィオナ、エリシア、みんな……一緒にジグを救わせてくれ！」
line = "「フィオナ、エリシア、みんな……一緒にジグを救わせてくれ！」"

[[dialogue]]
speaker = "unk"
# 梨緒の脳裏に、星見家の双子の顔が浮かぶ。
line = "梨緒の脳裏に、星見家の双子の顔が浮かぶ。"

[[dialogue]]
speaker = "梨緒"
# （フィオナ、エリシア……私は君たちを守れなかった。それでもジグを救いたい。だからこそ、ジグだけは救いたい）
line = "（フィオナ、エリシア……私は君たちを守れなかった。それでもジグを救いたい。だからこそ、ジグだけは救いたい）"

[[dialogue]]
speaker = "梨緒"
# （虫のいい話だが、きっと君たちも同じ気持ちのはずだ！）
line = "（虫のいい話だが、きっと君たちも同じ気持ちのはずだ！）"

[[dialogue]]
speaker = "ジグ"
# 「く──！」
line = "「く──！」"

[[dialogue]]
speaker = "unk"
# 雷の矢がジグの胸に吸い込まれる。
line = "雷の矢がジグの胸に吸い込まれる。"

[[dialogue]]
speaker = "unk"
# さらに──
line = "さらに──"

[[dialogue]]
speaker = "ジグ"
# 「ぐぁあああっ！！？」
line = "「ぐぁあああっ！！？」"

[[dialogue]]
speaker = "unk"
# 緋宮クロトに植え付けられた力を取り除いた時のように、電流が内側から<ruby=リクリエ>厄災</ruby>を焼く。
line = "緋宮クロトに植え付けられた力を取り除いた時のように、電流が内側から<ruby>厄災<rt>リクリエ</rt></ruby>を焼く。"

[[dialogue]]
speaker = "梨緒"
# 「あの時は魔王の中の、使徒の力を除くことはできなかった。だが……！」
line = "「あの時は魔王の中の、使徒の力を除くことはできなかった。だが……！」"

[[dialogue]]
speaker = "unk"
# 雷撃から逃れるように、ジグの中から紫の瘴気が溢れ、仮面が溶けるように消えた。
line = "雷撃から逃れるように、ジグの中から紫の瘴気が溢れ、仮面が溶けるように消えた。"

[[dialogue]]
speaker = "unk"
# 器を失ったリクリエの瘴気が溢れ、神殿を埋め尽くそうとするが、ノルンの糸が光の網となって瘴気を抑え込む。
line = "器を失ったリクリエの瘴気が溢れ、神殿を埋め尽くそうとするが、ノルンの糸が光の網となって瘴気を抑え込む。"

[[dialogue]]
speaker = "unk"
# そして梨緒はクロスボウに矢を番え、過たず狙い撃つ。
line = "そして梨緒はクロスボウに矢を番え、過たず狙い撃つ。"

[[dialogue]]
speaker = "梨緒"
# 「<ruby=ベガ>我ら</ruby>の守護星たちよ。今こそ救世の誓いに応えてくれ」
line = "「<ruby>我ら<rt>ベガ</rt></ruby>の守護星たちよ。今こそ救世の誓いに応えてくれ」"

[[dialogue]]
speaker = "梨緒"
# 「星力結晶、装填」
line = "「星力結晶、装填」"

[[dialogue]]
speaker = "梨緒"
# 「次元を超えて、破滅を切り裂け」
line = "「次元を超えて、破滅を切り裂け」"

[[dialogue]]
speaker = "梨緒"
# 「ディメンション──」
line = "「ディメンション──」"

[[dialogue]]
speaker = "梨緒"
# 「エクスウェーブ！！！」
line = "「エクスウェーブ！！！」"
