[[dialogue]]
speaker = "unk"
# 第８話,梨緒とフィオナ,B
line = "第８話,梨緒とフィオナ,B"

[[dialogue]]
speaker = "クロト"
# 「わざわざ来てもらってすまない。聞きたいことがあって」
line = "「わざわざ来てもらってすまない。聞きたいことがあって」"

[[dialogue]]
speaker = "フィオナ"
# 「いえ、私もお話したかったところですから」
line = "「いえ、私もお話したかったところですから」"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャー。また騒ぎになってるって聞いたニャンよ」
line = "「ニャー。また騒ぎになってるって聞いたニャンよ」"

[[dialogue]]
speaker = "クロト"
# 「はは……まぁそうなんだ」
line = "「はは……まぁそうなんだ」"

[[dialogue]]
speaker = "unk"
# カフェテリアでフィオナ（とニャリオン）と落ち合う。
line = "カフェテリアでフィオナ（とニャリオン）と落ち合う。"

[[dialogue]]
speaker = "unk"
# 先日のモンスターのことも相談したかったが……
line = "先日のモンスターのことも相談したかったが……"

[[dialogue]]
speaker = "フィオナ"
# 「聞きたかったのは梨緒さんのことですよね？」
line = "「聞きたかったのは梨緒さんのことですよね？」"

[[dialogue]]
speaker = "クロト"
# 「ああ。今は星見家にいるって聞いたんだが、知り合いなのか？」
line = "「ああ。今は星見家にいるって聞いたんだが、知り合いなのか？」"

[[dialogue]]
speaker = "フィオナ"
# 「いえ、彼女は……」
line = "「いえ、彼女は……」"

[[dialogue]]
speaker = "フィオナ"
# 「彼女は教皇庁の前で倒れていたんです」
line = "「彼女は教皇庁の前で倒れていたんです」"

[[dialogue]]
speaker = "梨緒"
# 「ん、んん……」
line = "「ん、んん……」"

[[dialogue]]
speaker = "フィオナ"
# 「目が覚めましたか？　あなたは意識を失っていて──」
line = "「目が覚めましたか？　あなたは意識を失っていて──」"

[[dialogue]]
speaker = "梨緒"
# 「エリシア！？　生きていたんだな！　良かった！」
line = "「エリシア！？　生きていたんだな！　良かった！」"

[[dialogue]]
speaker = "フィオナ"
# 「──！？　どうしてその名前を……？」
line = "「──！？　どうしてその名前を……？」"

[[dialogue]]
speaker = "フィオナ"
# 「いえ、私は星見フィオナです。エリシアという人間はここにはいません」
line = "「いえ、私は星見フィオナです。エリシアという人間はここにはいません」"

[[dialogue]]
speaker = "梨緒"
# 「何を言っている？　いくら双子でも見分けはつくぞ。私にそんな冗談は通じな──」
line = "「何を言っている？　いくら双子でも見分けはつくぞ。私にそんな冗談は通じな──」"

[[dialogue]]
speaker = "アポロ"
# 「フィオナ～！　一緒に流星ライダーの劇場版見ようぜ！」
line = "「フィオナ～！　一緒に流星ライダーの劇場版見ようぜ！」"

[[dialogue]]
speaker = "梨緒"
# 「は──？」
line = "「は──？」"

[[dialogue]]
speaker = "梨緒"
# 「フィオナ！？　フィオナが小さくなった！？　本当にフィオナなのか！？　どういうことだ！？」
line = "「フィオナ！？　フィオナが小さくなった！？　本当にフィオナなのか！？　どういうことだ！？」"

[[dialogue]]
speaker = "アポロ"
# 「だ、誰だおまえ？　どうしてあたしたち姉妹のことを知っている！？」
line = "「だ、誰だおまえ？　どうしてあたしたち姉妹のことを知っている！？」"

[[dialogue]]
speaker = "梨緒"
# 「誰って……梨緒だ！　梨緒・Ａ・クリステレスだ！　わからないのか！？」
line = "「誰って……梨緒だ！　梨緒・Ａ・クリステレスだ！　わからないのか！？」"

[[dialogue]]
speaker = "フィオナ"
# 「いえ……私はあなたのことを存じ上げません」
line = "「いえ……私はあなたのことを存じ上げません」"

[[dialogue]]
speaker = "梨緒"
# 「何……！？」
line = "「何……！？」"

[[dialogue]]
speaker = "フィオナ"
# 「彼女は私たち姉妹のことをよく知っているようでした。でも私たちは彼女を知りません」
line = "「彼女は私たち姉妹のことをよく知っているようでした。でも私たちは彼女を知りません」"

[[dialogue]]
speaker = "クロト"
# 「ニャリオンの知り合いだったり……？」
line = "「ニャリオンの知り合いだったり……？」"

[[dialogue]]
speaker = "ニャリオン"
# 「心当たりがないニャン」
line = "「心当たりがないニャン」"

[[dialogue]]
speaker = "unk"
# フィオナの本名も、アポロとの関係も本当に一部の者しか知りえないはず……なのにフィオナたちは梨緒を知らない。
line = "フィオナの本名も、アポロとの関係も本当に一部の者しか知りえないはず……なのにフィオナたちは梨緒を知らない。"

[[dialogue]]
speaker = "unk"
# ますます梨緒のことがわからなくなった。
line = "ますます梨緒のことがわからなくなった。"

[[dialogue]]
speaker = "フィオナ"
# 「彼女は身寄りがないそうで、当面は様子を見るために星見家にいてもらうことになりました」
line = "「彼女は身寄りがないそうで、当面は様子を見るために星見家にいてもらうことになりました」"

[[dialogue]]
speaker = "ニャリオン"
# 「フィオナ嬢の秘密を知ってるから、放っておくわけにはいかないニャン」
line = "「フィオナ嬢の秘密を知ってるから、放っておくわけにはいかないニャン」"

[[dialogue]]
speaker = "フィオナ"
# 「姉さんを見た梨緒さんはひどく驚いて、取り乱していましたが……しばらくすると落ち着いて、自分は新星学園の星騎士だと説明しました」
line = "「姉さんを見た梨緒さんはひどく驚いて、取り乱していましたが……しばらくすると落ち着いて、自分は新星学園の星騎士だと説明しました」"

[[dialogue]]
speaker = "フィオナ"
# 「しかし新星学園に彼女の籍はなく、彼女が見せてくれた学生証も現行のものとは違うものでした」
line = "「しかし新星学園に彼女の籍はなく、彼女が見せてくれた学生証も現行のものとは違うものでした」"

[[dialogue]]
speaker = "フィオナ"
# 「ただ星騎士としての力は確かだったので、教皇庁から手回しして特例として転入させてもらったのですが……」
line = "「ただ星騎士としての力は確かだったので、教皇庁から手回しして特例として転入させてもらったのですが……」"

[[dialogue]]
speaker = "フィオナ"
# 「まさか緋宮会長に御前試合を挑むなんて思いませんでした。それに緋宮会長を攻撃したとも聞いていますし……本当にすみません」
line = "「まさか緋宮会長に御前試合を挑むなんて思いませんでした。それに緋宮会長を攻撃したとも聞いていますし……本当にすみません」"

[[dialogue]]
speaker = "クロト"
# 「いやあれは……助かった」
line = "「いやあれは……助かった」"

[[dialogue]]
speaker = "フィオナ"
# 「？　助かった……ですか？」
line = "「？　助かった……ですか？」"

[[dialogue]]
speaker = "unk"
# あの光景を見た途端、得体の知れない破壊衝動が沸き起こった。
line = "あの光景を見た途端、得体の知れない破壊衝動が沸き起こった。"

[[dialogue]]
speaker = "unk"
# 梨緒の雷が俺を撃っていなかったら今頃どうなっていたか。
line = "梨緒の雷が俺を撃っていなかったら今頃どうなっていたか。"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "フィオナ"
# 「何か……あったんですか？」
line = "「何か……あったんですか？」"

[[dialogue]]
speaker = "unk"
# あの時のことをフィオナに伝えなければならない。
line = "あの時のことをフィオナに伝えなければならない。"

[[dialogue]]
speaker = "unk"
# だけど自分でも何が起きたか理解できていないのに、どうやって説明すればいいんだ……？
line = "だけど自分でも何が起きたか理解できていないのに、どうやって説明すればいいんだ……？"

[[dialogue]]
speaker = "梨緒"
# 「エリシア──」
line = "「エリシア──」"

[[dialogue]]
speaker = "梨緒"
# 「……緋宮クロト」
line = "「……緋宮クロト」"

[[dialogue]]
speaker = "unk"
# フィオナに声をかけようとしたのだろうが、俺の顔を見た途端、梨緒の表情が強張る。
line = "フィオナに声をかけようとしたのだろうが、俺の顔を見た途端、梨緒の表情が強張る。"

[[dialogue]]
speaker = "クロト"
# 「昨日以来だな」
line = "「昨日以来だな」"

[[dialogue]]
speaker = "梨緒"
# 「フン。よくも顔を見せられたものだな」
line = "「フン。よくも顔を見せられたものだな」"

[[dialogue]]
speaker = "フィオナ"
# 「梨緒さん」
line = "「梨緒さん」"

[[dialogue]]
speaker = "unk"
# フィオナがたしなめるが、梨緒は敵意を向けたままだ。
line = "フィオナがたしなめるが、梨緒は敵意を向けたままだ。"

[[dialogue]]
speaker = "unk"
# どうやら彼女にはとことん嫌われているらしい。
line = "どうやら彼女にはとことん嫌われているらしい。"

[[dialogue]]
speaker = "クロト"
# 「すまない、フィオナ。彼女とも話したい」
line = "「すまない、フィオナ。彼女とも話したい」"

[[dialogue]]
speaker = "フィオナ"
# 「ですが……」
line = "「ですが……」"

[[dialogue]]
speaker = "梨緒"
# 「大丈夫だ、エリ──……流星の会長。ここで緋宮クロトと戦うつもりはない。ここではな」
line = "「大丈夫だ、エリ──……流星の会長。ここで緋宮クロトと戦うつもりはない。ここではな」"

[[dialogue]]
speaker = "フィオナ"
# 「ならいいのですけど……」
line = "「ならいいのですけど……」"

[[dialogue]]
speaker = "梨緒"
# 「すまない、まだフィオナと呼ぶ気にはなれないんだ。もう少し時間をくれ」
line = "「すまない、まだフィオナと呼ぶ気にはなれないんだ。もう少し時間をくれ」"

[[dialogue]]
speaker = "unk"
# 梨緒はフィオナの本名まで知っている。
line = "梨緒はフィオナの本名まで知っている。"

[[dialogue]]
speaker = "unk"
# だけどフィオナは梨緒を知らなくて、そのズレが居心地の悪さを生んでいるようだった。
line = "だけどフィオナは梨緒を知らなくて、そのズレが居心地の悪さを生んでいるようだった。"

[[dialogue]]
speaker = "フィオナ"
# 「……わかりました。では少し外します」
line = "「……わかりました。では少し外します」"

[[dialogue]]
speaker = "ニャリオン"
# 「近くにいるから何かあったら呼ぶのニャン」
line = "「近くにいるから何かあったら呼ぶのニャン」"

[[dialogue]]
speaker = "梨緒"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# フィオナが離れると、間に沈黙が落ちる。
line = "フィオナが離れると、間に沈黙が落ちる。"

[[dialogue]]
speaker = "unk"
# 痛いくらいの緊張が走り、ビリビリと電流が流れているようだ。
line = "痛いくらいの緊張が走り、ビリビリと電流が流れているようだ。"

[[dialogue]]
speaker = "梨緒"
# 「君は今、新星学園の星徒会長だそうだな。周囲の人間には隠し通せているようだが、私は騙されないぞ」
line = "「君は今、新星学園の星徒会長だそうだな。周囲の人間には隠し通せているようだが、私は騙されないぞ」"

[[dialogue]]
speaker = "梨緒"
# 「君は世界を滅ぼす魔王だ。だが君の好きにはさせない。私が必ず君を止める。今度こそ……！」
line = "「君は世界を滅ぼす魔王だ。だが君の好きにはさせない。私が必ず君を止める。今度こそ……！」"

[[dialogue]]
speaker = "クロト"
# 「俺はそんなつもりはないけど……俺が世界を滅ぼすってどういう意味なんだ？」
line = "「俺はそんなつもりはないけど……俺が世界を滅ぼすってどういう意味なんだ？」"

[[dialogue]]
speaker = "梨緒"
# 「言葉通りの意味だ。それが私が見た君の姿。君の未来だ」
line = "「言葉通りの意味だ。それが私が見た君の姿。君の未来だ」"

[[dialogue]]
speaker = "クロト"
# 「じゃあ世界は一度滅びたのか？」
line = "「じゃあ世界は一度滅びたのか？」"

[[dialogue]]
speaker = "梨緒"
# 「……そのはずだった。だが何故か私は生きていて、今ここにいる。それ以上は聞かれても私にはわからない」
line = "「……そのはずだった。だが何故か私は生きていて、今ここにいる。それ以上は聞かれても私にはわからない」"

[[dialogue]]
speaker = "unk"
# 目を伏せながら答える梨緒の表情は、俺に対する明確な敵意と裏腹にどこか不安げだった。
line = "目を伏せながら答える梨緒の表情は、俺に対する明確な敵意と裏腹にどこか不安げだった。"

[[dialogue]]
speaker = "梨緒"
# 「私が御前試合を挑んだのは、星徒会長になって君を退学にするためだ。セレスティアを没収し、戦う力を奪う」
line = "「私が御前試合を挑んだのは、星徒会長になって君を退学にするためだ。セレスティアを没収し、戦う力を奪う」"

[[dialogue]]
speaker = "クロト"
# 「また退学か……」
line = "「また退学か……」"

[[dialogue]]
speaker = "unk"
# やはり御前試合と退学は切っては切れないらしい。なぜだ。
line = "やはり御前試合と退学は切っては切れないらしい。なぜだ。"

[[dialogue]]
speaker = "クロト"
# 「ところで……君が着ているその制服は？」
line = "「ところで……君が着ているその制服は？」"

[[dialogue]]
speaker = "unk"
# まとう赤は、新星学園の女子制服と同じ色。
line = "まとう赤は、新星学園の女子制服と同じ色。"

[[dialogue]]
speaker = "unk"
# 制服を改造している者は多いが、彼女はまた違うもののように思えた。
line = "制服を改造している者は多いが、彼女はまた違うもののように思えた。"

[[dialogue]]
speaker = "梨緒"
# 「これはれっきとした新星学園の制服のはずなんだが……やはり今の新星学園では私は異分子のようだな」
line = "「これはれっきとした新星学園の制服のはずなんだが……やはり今の新星学園では私は異分子のようだな」"

[[dialogue]]
speaker = "梨緒"
# 「私の記憶では、新星の会長は君とは違う別の人間だった。私も元は副会長で……いや、いい。この話はエリシアも混乱していた」
line = "「私の記憶では、新星の会長は君とは違う別の人間だった。私も元は副会長で……いや、いい。この話はエリシアも混乱していた」"

[[dialogue]]
speaker = "梨緒"
# 「説明したくとも、私にもわからないことが多い。だが──」
line = "「説明したくとも、私にもわからないことが多い。だが──」"

[[dialogue]]
speaker = "梨緒"
# 「私は世界を守れなかった」
line = "「私は世界を守れなかった」"

[[dialogue]]
speaker = "梨緒"
# 「だから今度こそ君を止める。それだけだ」
line = "「だから今度こそ君を止める。それだけだ」"

[[dialogue]]
speaker = "クロト"
# 「……そうか」
line = "「……そうか」"

[[dialogue]]
speaker = "unk"
# 俺を睨む梨緒の目に迷いはない。
line = "俺を睨む梨緒の目に迷いはない。"

[[dialogue]]
speaker = "unk"
# その視線は俺の中の戸惑いを射貫くように、鋭く胸に突き刺さっていた。
line = "その視線は俺の中の戸惑いを射貫くように、鋭く胸に突き刺さっていた。"
