[[dialogue]]
speaker = "unk"
# 第５話,実践撃破訓練,B
line = "第５話,実践撃破訓練,B"

[[dialogue]]
speaker = "unk"
# 入ったばかりの転入生が、現星徒会長ヴィーナスと果し合いを行う。
line = "入ったばかりの転入生が、現星徒会長ヴィーナスと果し合いを行う。"

[[dialogue]]
speaker = "unk"
# その噂はまたたく間に校内を駆け巡った。
line = "その噂はまたたく間に校内を駆け巡った。"

[[dialogue]]
speaker = "生徒Ａ"
# 「ねぇねぇ聞いた！？　噂の新入生が会長に下剋上を叩きつけたんだって！」
line = "「ねぇねぇ聞いた！？　噂の新入生が会長に下剋上を叩きつけたんだって！」"

[[dialogue]]
speaker = "生徒Ｂ"
# 「そんな無謀な……会長の実力をご存じないのでしょうか……」
line = "「そんな無謀な……会長の実力をご存じないのでしょうか……」"

[[dialogue]]
speaker = "生徒Ｃ"
# 「負けたら退学なんて、そんなの無茶だよ……」
line = "「負けたら退学なんて、そんなの無茶だよ……」"

[[dialogue]]
speaker = "クロト"
# 「……とんでもないことになった」
line = "「……とんでもないことになった」"

[[dialogue]]
speaker = "マトイ"
# 「他人事じゃないでしょう……」
line = "「他人事じゃないでしょう……」"

[[dialogue]]
speaker = "unk"
# 気づけば俺は、入学早々トップに果たし状を叩きつける破天荒転入生として有名になってしまっていた。
line = "気づけば俺は、入学早々トップに果たし状を叩きつける破天荒転入生として有名になってしまっていた。"

[[dialogue]]
speaker = "unk"
# 本当は不可抗力だったのだが……。
line = "本当は不可抗力だったのだが……。"

[[dialogue]]
speaker = "クロト"
# 「（午後の授業はほとんど頭に入ってこなかったな……）」
line = "「（午後の授業はほとんど頭に入ってこなかったな……）」"

[[dialogue]]
speaker = "unk"
# 星徒会長か、退学か。
line = "星徒会長か、退学か。"

[[dialogue]]
speaker = "unk"
# こんなにも落差のある二択を突きつけられることもそうそうないだろう。
line = "こんなにも落差のある二択を突きつけられることもそうそうないだろう。"

[[dialogue]]
speaker = "マトイ"
# 「会長も無茶だわ。緋宮くんはまだ来たばかりなのに……」
line = "「会長も無茶だわ。緋宮くんはまだ来たばかりなのに……」"

[[dialogue]]
speaker = "アナ"
# 「でもある意味幸運。いきなりトップを狙える」
line = "「でもある意味幸運。いきなりトップを狙える」"

[[dialogue]]
speaker = "マトイ"
# 「そういう問題じゃ……」
line = "「そういう問題じゃ……」"

[[dialogue]]
speaker = "クロト"
# 「確かにそうだ。いいこと言うな、アナ」
line = "「確かにそうだ。いいこと言うな、アナ」"

[[dialogue]]
speaker = "マトイ"
# 「あなたもポジティブすぎっ」
line = "「あなたもポジティブすぎっ」"

[[dialogue]]
speaker = "unk"
# 現実問題、受けなければ退学だったのだから選択の余地はなかった。
line = "現実問題、受けなければ退学だったのだから選択の余地はなかった。"

[[dialogue]]
speaker = "unk"
# 至難と呼ばれる編入試験をくぐり抜けてそんな末路はごめんだ。
line = "至難と呼ばれる編入試験をくぐり抜けてそんな末路はごめんだ。"

[[dialogue]]
speaker = "クロト"
# 「今朝、クラスの子やマトイたちの話を聞いて……思ったんだ。俺、世界の危機に出動して立ち向かえるようになりたいって」
line = "「今朝、クラスの子やマトイたちの話を聞いて……思ったんだ。俺、世界の危機に出動して立ち向かえるようになりたいって」"

[[dialogue]]
speaker = "クロト"
# 「世界の危機──は大げさだとしても、この流星市国くらいはさ」
line = "「世界の危機──は大げさだとしても、この流星市国くらいはさ」"

[[dialogue]]
speaker = "unk"
# 一定の実力が認められた星騎士はプリマステラと称され、モンスターの出現時などにも出動が許可される。
line = "一定の実力が認められた星騎士はプリマステラと称され、モンスターの出現時などにも出動が許可される。"

[[dialogue]]
speaker = "unk"
# その話を聞いて、まずそこを目指すべきだと強く思ったのも事実。
line = "その話を聞いて、まずそこを目指すべきだと強く思ったのも事実。"

[[dialogue]]
speaker = "クロト"
# 「でも。それ以上の、星徒会長になれる道があるのなら……逃げてる場合じゃないと思うんだ」
line = "「でも。それ以上の、星徒会長になれる道があるのなら……逃げてる場合じゃないと思うんだ」"

[[dialogue]]
speaker = "マトイ"
# 「緋宮くん……」
line = "「緋宮くん……」"

[[dialogue]]
speaker = "クロト"
# 「とはいえ……星徒会に入るのも容易じゃないってのは、マトイにも聞いた通りだもんな」
line = "「とはいえ……星徒会に入るのも容易じゃないってのは、マトイにも聞いた通りだもんな」"

[[dialogue]]
speaker = "unk"
# 新星学園総生徒数２５４４名。うち、星徒会役員は現会長含め４名。
line = "新星学園総生徒数２５４４名。うち、星徒会役員は現会長含め４名。"

[[dialogue]]
speaker = "unk"
# 恐ろしく狭き門。
line = "恐ろしく狭き門。"

[[dialogue]]
speaker = "unk"
# 選ばれし<ruby=スターナイト>星騎士</ruby>を育成するこの学園において、さらに選りすぐられた人たちによって構成されたエリート集団なのだ。無理もない。
line = "選ばれし<ruby>星騎士<rt>スターナイト</rt></ruby>を育成するこの学園において、さらに選りすぐられた人たちによって構成されたエリート集団なのだ。無理もない。"

[[dialogue]]
speaker = "クロト"
# 「……そう考えるとアナはすごいんだな」
line = "「……そう考えるとアナはすごいんだな」"

[[dialogue]]
speaker = "アナ"
# 「それなりに」
line = "「それなりに」"

[[dialogue]]
speaker = "unk"
# ──アナ。
line = "──アナ。"

[[dialogue]]
speaker = "unk"
# 俺の右を歩く天使の少女はそう簡素に返事した。
line = "俺の右を歩く天使の少女はそう簡素に返事した。"

[[dialogue]]
speaker = "unk"
# 軽く話したところによれば、彼女のつけている腕章は『副会長』の証らしい。
line = "軽く話したところによれば、彼女のつけている腕章は『副会長』の証らしい。"

[[dialogue]]
speaker = "マトイ"
# 「アナは別格。一年生なのに副会長なんて、歴代初って聞いたし」
line = "「アナは別格。一年生なのに副会長なんて、歴代初って聞いたし」"

[[dialogue]]
speaker = "アナ"
# 「現会長はデスクワークが苦手だから。事務仕事は私が全部やってる。適材適所」
line = "「現会長はデスクワークが苦手だから。事務仕事は私が全部やってる。適材適所」"

[[dialogue]]
speaker = "クロト"
# 「優秀なんだな」
line = "「優秀なんだな」"

[[dialogue]]
speaker = "unk"
# アナはその小さい背丈からもわかるようにまだ一年生。
line = "アナはその小さい背丈からもわかるようにまだ一年生。"

[[dialogue]]
speaker = "unk"
# にもかかわらず副会長という重役に抜擢されているのは驚きで、それも彼女の秀抜な能力によるものらしい。
line = "にもかかわらず副会長という重役に抜擢されているのは驚きで、それも彼女の秀抜な能力によるものらしい。"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナスに勝つ……とは言ったけど。どうすればいいんだろう」
line = "「ヴィーナスに勝つ……とは言ったけど。どうすればいいんだろう」"

[[dialogue]]
speaker = "マトイ"
# 「どうする、と言っても……」
line = "「どうする、と言っても……」"

[[dialogue]]
speaker = "unk"
# 御前試合。そう銘打たれた転入生ｖｓ星徒会長の試合は、一週間後に執り行われることになっていた。
line = "御前試合。そう銘打たれた転入生ｖｓ星徒会長の試合は、一週間後に執り行われることになっていた。"

[[dialogue]]
speaker = "unk"
# 新星学園を司る学園長先生の御前で、俺の星徒会長たりえる力を見せつけるのが目的なのだ。
line = "新星学園を司る学園長先生の御前で、俺の星徒会長たりえる力を見せつけるのが目的なのだ。"

[[dialogue]]
speaker = "アナ"
# 「強くなるしかない。マトイ先輩、地下は空いてる？」
line = "「強くなるしかない。マトイ先輩、地下は空いてる？」"

[[dialogue]]
speaker = "マトイ"
# 「空いてたと思うけど……」
line = "「空いてたと思うけど……」"

[[dialogue]]
speaker = "クロト"
# 「（地下……？）」
line = "「（地下……？）」"

[[dialogue]]
speaker = "unk"
# 何のことだろう。
line = "何のことだろう。"

[[dialogue]]
speaker = "unk"
# そう思いつつも、俺は彼女たちに連れられていった。
line = "そう思いつつも、俺は彼女たちに連れられていった。"

[[dialogue]]
speaker = "クロト"
# 「ここは……」
line = "「ここは……」"

[[dialogue]]
speaker = "アナ"
# 「地下訓練施設。普通はたまに授業で使うけど、星徒会役員なら借りられる」
line = "「地下訓練施設。普通はたまに授業で使うけど、星徒会役員なら借りられる」"

[[dialogue]]
speaker = "unk"
# どうやら俺のために役員権限を行使してくれたようだ。
line = "どうやら俺のために役員権限を行使してくれたようだ。"

[[dialogue]]
speaker = "アナ"
# 「会長のわがままが原因だから。私たちもできる限り協力する」
line = "「会長のわがままが原因だから。私たちもできる限り協力する」"

[[dialogue]]
speaker = "マトイ"
# 「しょうがないもんね。さすがに退学が懸かってるなんて……見過ごせないし」
line = "「しょうがないもんね。さすがに退学が懸かってるなんて……見過ごせないし」"

[[dialogue]]
speaker = "クロト"
# 「２人とも……ありがとう」
line = "「２人とも……ありがとう」"

[[dialogue]]
speaker = "アナ"
# 「それじゃ、さっそく」
line = "「それじゃ、さっそく」"

[[dialogue]]
speaker = "クロト"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "ビュンタ"
# 「ウィイーッ」
line = "「ウィイーッ」"

[[dialogue]]
speaker = "unk"
# アナがホール端にあった仰々しい機械を操作すると、目の前にモンスターが出現した。
line = "アナがホール端にあった仰々しい機械を操作すると、目の前にモンスターが出現した。"

[[dialogue]]
speaker = "unk"
# また、一帯に光の障壁のようなフィールドが展開される。
line = "また、一帯に光の障壁のようなフィールドが展開される。"

[[dialogue]]
speaker = "アナ"
# 「倒してみてください。まずはあなたのポテンシャルを測ります」
line = "「倒してみてください。まずはあなたのポテンシャルを測ります」"

[[dialogue]]
speaker = "マトイ"
# 「い、いきなり？」
line = "「い、いきなり？」"

[[dialogue]]
speaker = "アナ"
# 「実践撃破訓練──これは誰しも入学時に受けるトレーニング・テストです。転入されたばかりの次期会長には、丁度いいかと」
line = "「実践撃破訓練──これは誰しも入学時に受けるトレーニング・テストです。転入されたばかりの次期会長には、丁度いいかと」"

[[dialogue]]
speaker = "クロト"
# 「わかった。任せてくれ」
line = "「わかった。任せてくれ」"

[[dialogue]]
speaker = "unk"
# 展開されたフィールド内には俺１人。
line = "展開されたフィールド内には俺１人。"

[[dialogue]]
speaker = "unk"
# 俺はセレスティアに触れ、戦闘態勢へ移行した。
line = "俺はセレスティアに触れ、戦闘態勢へ移行した。"

[[dialogue]]
speaker = "アナ"
# 「まずはＣランクのモンスターが相手です。れでぃ、ごー」
line = "「まずはＣランクのモンスターが相手です。れでぃ、ごー」"
