[[dialogue]]
speaker = "unk"
# 第６話,ヒーロー見参,B
line = "第６話,ヒーロー見参,B"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「ノヴァセイクリッドアロー！」
line = "「ノヴァセイクリッドアロー！」"

[[dialogue]]
speaker = "unk"
# ルヴィネが光球を放つと同時、ヴィーナスも光の矢を撃ち出した。
line = "ルヴィネが光球を放つと同時、ヴィーナスも光の矢を撃ち出した。"

[[dialogue]]
speaker = "unk"
# 三度ぶつかる光と光。
line = "三度ぶつかる光と光。"

[[dialogue]]
speaker = "unk"
# だが今度は──
line = "だが今度は──"

[[dialogue]]
speaker = "ルヴィネ"
# 「ッ──！？」
line = "「ッ──！？」"

[[dialogue]]
speaker = "unk"
# 光の矢が光球を貫き、ルヴィネの顔を掠めた。
line = "光の矢が光球を貫き、ルヴィネの顔を掠めた。"

[[dialogue]]
speaker = "unk"
# 横を通り過ぎた光条はそのまま勢いよく彼方へと飛んでいく。
line = "横を通り過ぎた光条はそのまま勢いよく彼方へと飛んでいく。"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「これがノヴァフォームよ！　いつまでもやられっぱなしじゃないんだから！」
line = "「これがノヴァフォームよ！　いつまでもやられっぱなしじゃないんだから！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……なるほど、星力の爆発的な上昇を感じるわ。見掛け倒しではないようね」
line = "「……なるほど、星力の爆発的な上昇を感じるわ。見掛け倒しではないようね」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「当然よ、クロトがくれた力なんだもの！　それに強力なのはママのお墨付きよ！」
line = "「当然よ、クロトがくれた力なんだもの！　それに強力なのはママのお墨付きよ！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「でもそれだけで逆転したつもり？」
line = "「でもそれだけで逆転したつもり？」"

[[dialogue]]
speaker = "unk"
# ルヴィネが光弾を撃とうと、ヴィーナスに掌を向ける。
line = "ルヴィネが光弾を撃とうと、ヴィーナスに掌を向ける。"

[[dialogue]]
speaker = "unk"
# しかしヴィーナスの姿はもう消えていた。
line = "しかしヴィーナスの姿はもう消えていた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「──！？」
line = "「──！？」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「わ──っととと。ちょっと勢い付けすぎたわね」
line = "「わ──っととと。ちょっと勢い付けすぎたわね」"

[[dialogue]]
speaker = "unk"
# そして次の瞬間、ルヴィネの背後に現れる。
line = "そして次の瞬間、ルヴィネの背後に現れる。"

[[dialogue]]
speaker = "unk"
# ノヴァフォームはスピードも通常フォームの比ではなく、瞬間移動のごとき速度でルヴィネを圧倒していた。
line = "ノヴァフォームはスピードも通常フォームの比ではなく、瞬間移動のごとき速度でルヴィネを圧倒していた。"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「ふふんっ、絶好調♪　今までで一番調子がいいわ♪　ドンドンいくわよー！」
line = "「ふふんっ、絶好調♪　今までで一番調子がいいわ♪　ドンドンいくわよー！」"

[[dialogue]]
speaker = "unk"
# 光が嵐のようにルヴィネを襲う。
line = "光が嵐のようにルヴィネを襲う。"

[[dialogue]]
speaker = "unk"
# さっきの連射がマシンガンなら、今のはさながら大砲。一撃一撃が今までの最高出力を上回っている。
line = "さっきの連射がマシンガンなら、今のはさながら大砲。一撃一撃が今までの最高出力を上回っている。"

[[dialogue]]
speaker = "unk"
# それどころか連射速度まで上昇し、閃光の砲撃が怒涛のように押し寄せる。
line = "それどころか連射速度まで上昇し、閃光の砲撃が怒涛のように押し寄せる。"

[[dialogue]]
speaker = "ルヴィネ"
# 「ッ……！」
line = "「ッ……！」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「ようやく澄まし顔が崩れたわね。でもまだまだこんなもんじゃないわよ！」
line = "「ようやく澄まし顔が崩れたわね。でもまだまだこんなもんじゃないわよ！」"

[[dialogue]]
speaker = "unk"
# アステラを一撃で吹き飛ばすような砲撃の嵐。
line = "アステラを一撃で吹き飛ばすような砲撃の嵐。"

[[dialogue]]
speaker = "unk"
# ヴィーナスは鬱憤を晴らすように猛攻を仕掛け、一撃ごとにルヴィネが押され、ジリジリと後ろに下がっていく。
line = "ヴィーナスは鬱憤を晴らすように猛攻を仕掛け、一撃ごとにルヴィネが押され、ジリジリと後ろに下がっていく。"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「私がどうしてノヴァフォームに覚醒できなかったのか、ようやく理由がわかったわ」
line = "「私がどうしてノヴァフォームに覚醒できなかったのか、ようやく理由がわかったわ」"

[[dialogue]]
speaker = "クロト"
# 「理由……？」
line = "「理由……？」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「マトイたちを見てて、私に足りないものがあるんじゃないかと思ってたけど、そうじゃなかった」
line = "「マトイたちを見てて、私に足りないものがあるんじゃないかと思ってたけど、そうじゃなかった」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「力を出し過ぎると私自身が危ないから、ママがセーブしてくれてたってわけ。でもそのリミッターは今外してもらったわ！」
line = "「力を出し過ぎると私自身が危ないから、ママがセーブしてくれてたってわけ。でもそのリミッターは今外してもらったわ！」"

[[dialogue]]
speaker = "unk"
# なるほど、ヴィーナスにアルケインコードが使えないと感じていた理由はそれか。
line = "なるほど、ヴィーナスにアルケインコードが使えないと感じていた理由はそれか。"

[[dialogue]]
speaker = "unk"
# 女神からの封印となれば、魔王の秘術を拒絶するのも無理はない。
line = "女神からの封印となれば、魔王の秘術を拒絶するのも無理はない。"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「それじゃフルパワーいくわよ！　ノヴァゴッデス──」
line = "「それじゃフルパワーいくわよ！　ノヴァゴッデス──」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「ビィーーーーームッ！！！」
line = "「ビィーーーーームッ！！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "unk"
# 巨大な光の塊がルヴィネを襲う。
line = "巨大な光の塊がルヴィネを襲う。"

[[dialogue]]
speaker = "unk"
# ルヴィネは不可視の障壁を張るが、ヴィーナスの一撃はそれすら打ち砕き、初めて攻撃を届かせた。
line = "ルヴィネは不可視の障壁を張るが、ヴィーナスの一撃はそれすら打ち砕き、初めて攻撃を届かせた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「くぅぅっ……！」
line = "「くぅぅっ……！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「はぁ、はぁ……想像以上の破壊力ね……」
line = "「はぁ、はぁ……想像以上の破壊力ね……」"

[[dialogue]]
speaker = "unk"
# 顔を歪めて光の向こうから現れるルヴィネ。
line = "顔を歪めて光の向こうから現れるルヴィネ。"

[[dialogue]]
speaker = "unk"
# 先ほどまで汚れひとつなかったマントは、ところどころが焼け焦げていた。
line = "先ほどまで汚れひとつなかったマントは、ところどころが焼け焦げていた。"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「今のでよくそれで済んだわね。私たちを見下ろすのをやめて、いい加減変身したらどうなの？」
line = "「今のでよくそれで済んだわね。私たちを見下ろすのをやめて、いい加減変身したらどうなの？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「そうね。これ以上戦闘を続けるなら、その必要がありそうだわ」
line = "「そうね。これ以上戦闘を続けるなら、その必要がありそうだわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「でもそれは今じゃないわ。万全を期すとしましょう」
line = "「でもそれは今じゃないわ。万全を期すとしましょう」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「あれだけ大口叩いてたのに逃げるの？」
line = "「あれだけ大口叩いてたのに逃げるの？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ええ。ここは退くわ」
line = "「ええ。ここは退くわ」"

[[dialogue]]
speaker = "クロト"
# 「その前にもう一度聞かせてくれ。アルタイルと共にリクリエと戦う道は本当にあり得ないのか」
line = "「その前にもう一度聞かせてくれ。アルタイルと共にリクリエと戦う道は本当にあり得ないのか」"

[[dialogue]]
speaker = "ルヴィネ"
# 「くどいわ。平行世界は滅ぼし合う運命にある」
line = "「くどいわ。平行世界は滅ぼし合う運命にある」"

[[dialogue]]
speaker = "ルヴィネ"
# 「次はあなたたちを消す。覚悟しておいて」
line = "「次はあなたたちを消す。覚悟しておいて」"

[[dialogue]]
speaker = "ルヴィネ"
# 「──次があればの話だけど」
line = "「──次があればの話だけど」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「え──」
line = "「え──」"

[[dialogue]]
speaker = "スレイプニル"
# 「ブルル……！」
line = "「ブルル……！」"

[[dialogue]]
speaker = "クロト"
# 「極星従騎……！」
line = "「極星従騎……！」"

[[dialogue]]
speaker = "unk"
# いつの間にか極星従騎が俺たちを取り囲んでいた。
line = "いつの間にか極星従騎が俺たちを取り囲んでいた。"

[[dialogue]]
speaker = "unk"
# おそらくヴィーナスと戦っている間にルヴィネが呼び寄せたのだろう。
line = "おそらくヴィーナスと戦っている間にルヴィネが呼び寄せたのだろう。"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「ふん、そんなの私が全部ぶっ飛ばして──」
line = "「ふん、そんなの私が全部ぶっ飛ばして──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「きゃぁっ！？」
line = "「きゃぁっ！？」"

[[dialogue]]
speaker = "unk"
# 突如ノヴァフォームが解除され、空を飛ぶ力を失って落下するヴィーナス。
line = "突如ノヴァフォームが解除され、空を飛ぶ力を失って落下するヴィーナス。"

[[dialogue]]
speaker = "unk"
# 痛む体に鞭打って、ヴィーナスを受け止める──
line = "痛む体に鞭打って、ヴィーナスを受け止める──"

[[dialogue]]
speaker = "クロト"
# 「ぐ……っ」
line = "「ぐ……っ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロト、大丈夫！？」
line = "「クロト、大丈夫！？」"

[[dialogue]]
speaker = "クロト"
# 「あ、ああ、大丈夫だ……」
line = "「あ、ああ、大丈夫だ……」"

[[dialogue]]
speaker = "unk"
# 受け止めようと思ったが体が動かず、下敷きになってしまった。
line = "受け止めようと思ったが体が動かず、下敷きになってしまった。"

[[dialogue]]
speaker = "unk"
# でもヴィーナスが地面と激突しなかったから、まぁいいだろう……
line = "でもヴィーナスが地面と激突しなかったから、まぁいいだろう……"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナスこそ大丈夫か？」
line = "「ヴィーナスこそ大丈夫か？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「うん、大丈夫だけど……ごめん。星力がもう……ちょっと飛ばし過ぎたかも……」
line = "「うん、大丈夫だけど……ごめん。星力がもう……ちょっと飛ばし過ぎたかも……」"

[[dialogue]]
speaker = "unk"
# 星力を消耗しただけでなく、先ほどと打って変わって覇気がない。見るからに顔色も青くなっていた。
line = "星力を消耗しただけでなく、先ほどと打って変わって覇気がない。見るからに顔色も青くなっていた。"

[[dialogue]]
speaker = "クロト"
# （もしかして、これがノヴァフォームの反動か……？）
line = "（もしかして、これがノヴァフォームの反動か……？）"

[[dialogue]]
speaker = "unk"
# おそらくヴィーナスのノヴァフォームは、マトイたちとは違う。
line = "おそらくヴィーナスのノヴァフォームは、マトイたちとは違う。"

[[dialogue]]
speaker = "unk"
# より強力であるがゆえに、その代償があるようだ。
line = "より強力であるがゆえに、その代償があるようだ。"

[[dialogue]]
speaker = "ホルン"
# 「クルルルッ」
line = "「クルルルッ」"

[[dialogue]]
speaker = "スレイプニル"
# 「ヒヒィン……！」
line = "「ヒヒィン……！」"

[[dialogue]]
speaker = "unk"
# 極星従騎が１体、また１体と飛来してくる。
line = "極星従騎が１体、また１体と飛来してくる。"

[[dialogue]]
speaker = "unk"
# 俺は情けないことにリクリエの力を使った反動で動けず、ヴィーナスは星力をほぼ使い果たしてしまった。
line = "俺は情けないことにリクリエの力を使った反動で動けず、ヴィーナスは星力をほぼ使い果たしてしまった。"

[[dialogue]]
speaker = "クロト"
# （今度こそ、万事休すか──）
line = "（今度こそ、万事休すか──）"

[[dialogue]]
speaker = "？？？"
# 「あたしの出番だな！」
line = "「あたしの出番だな！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「──！？」
line = "「──！？」"

[[dialogue]]
speaker = "unk"
# 声が届くと同時、星のように閃く刃が極星従騎を切り裂いた。
line = "声が届くと同時、星のように閃く刃が極星従騎を切り裂いた。"

[[dialogue]]
speaker = "unk"
# 絶体絶命の俺たちの前に現れたのは──
line = "絶体絶命の俺たちの前に現れたのは──"

[[dialogue]]
speaker = "？？？"
# 「ヒーローはピンチにやってくる──ってな！」
line = "「ヒーローはピンチにやってくる──ってな！」"

[[dialogue]]
speaker = "unk"
# 二本一対の剣を携えた、黒いスーツの女性。
line = "二本一対の剣を携えた、黒いスーツの女性。"

[[dialogue]]
speaker = "unk"
# 極星従騎から助けてくれたみたいで、どうやら彼女は俺たちの味方らしい。
line = "極星従騎から助けてくれたみたいで、どうやら彼女は俺たちの味方らしい。"

[[dialogue]]
speaker = "unk"
# だけどその面影には見覚えがある気がして……
line = "だけどその面影には見覚えがある気がして……"

[[dialogue]]
speaker = "？？？"
# 「よう、久しぶりだな。そっちは前に見た時とそんなに変わらないみたいだが」
line = "「よう、久しぶりだな。そっちは前に見た時とそんなに変わらないみたいだが」"

[[dialogue]]
speaker = "クロト"
# 「あなたは……？」
line = "「あなたは……？」"

[[dialogue]]
speaker = "？？？"
# 「ん？　わからないか。まぁ随分成長したから無理もない」
line = "「ん？　わからないか。まぁ随分成長したから無理もない」"

[[dialogue]]
speaker = "？？？"
# 「こう言えばわかるだろう？　闇夜に紛れ彗星のごとく敵を討つ！　──ってな」
line = "「こう言えばわかるだろう？　闇夜に紛れ彗星のごとく敵を討つ！　──ってな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「まさか──」
line = "「まさか──」"

[[dialogue]]
speaker = "クロト"
# 「アポロ！？」
line = "「アポロ！？」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ああ！　流星ライダーアポロ、ここに見参だ！！」
line = "「ああ！　流星ライダーアポロ、ここに見参だ！！」"

[[dialogue]]
speaker = "unk"
# アポロと名乗った女性の姿に、俺もヴィーナスも目を丸くする。
line = "アポロと名乗った女性の姿に、俺もヴィーナスも目を丸くする。"

[[dialogue]]
speaker = "unk"
# そうだ、デネブに帰還したアポロはこの世界にいるはずだ。
line = "そうだ、デネブに帰還したアポロはこの世界にいるはずだ。"

[[dialogue]]
speaker = "unk"
# だけどこうして成長した姿を見ることになるとは思っていなかった。
line = "だけどこうして成長した姿を見ることになるとは思っていなかった。"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ここでルヴィネと雌雄を決するつもりはない。一旦退くぞ」
line = "「ここでルヴィネと雌雄を決するつもりはない。一旦退くぞ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「またあなたなの。そう簡単に逃がすと思う？」
line = "「またあなたなの。そう簡単に逃がすと思う？」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ああ、通させてもらう！」
line = "「ああ、通させてもらう！」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「スターダスト──ストーム！！」
line = "「スターダスト──ストーム！！」"

[[dialogue]]
speaker = "unk"
# 十字に振るった剣の軌跡から、無数の流星が降り注ぐ。
line = "十字に振るった剣の軌跡から、無数の流星が降り注ぐ。"

[[dialogue]]
speaker = "ルヴィネ"
# 「く──！」
line = "「く──！」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長、ヴィーナスさん、今のうちに」
line = "「緋宮会長、ヴィーナスさん、今のうちに」"

[[dialogue]]
speaker = "クロト"
# 「フィオナ！？　無事だったのか！？」
line = "「フィオナ！？　無事だったのか！？」"

[[dialogue]]
speaker = "ナターシャ"
# 「私もいるよー」
line = "「私もいるよー」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ナターシャも！？」
line = "「ナターシャも！？」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「よし、行くぞ！」
line = "「よし、行くぞ！」"

[[dialogue]]
speaker = "unk"
# フィオナが俺を、ナターシャがヴィーナスを抱える。
line = "フィオナが俺を、ナターシャがヴィーナスを抱える。"

[[dialogue]]
speaker = "unk"
# 流星の雨がルヴィネの目を<ruby=くら>晦</ruby>ませている間に、俺たちは戦場を後にした。
line = "流星の雨がルヴィネの目を<ruby>晦<rt>くら</rt></ruby>ませている間に、俺たちは戦場を後にした。"
