[[dialogue]]
speaker = "unk"
# 第６話,ナターシャの記憶,B
line = "第６話,ナターシャの記憶,B"

[[dialogue]]
speaker = "unk"
# クロト、ヴィーナス、メルエルが神殿内部で動き出した頃。
line = "クロト、ヴィーナス、メルエルが神殿内部で動き出した頃。"

[[dialogue]]
speaker = "unk"
# 梨緒とナターシャも同じく、神殿内に墜落していた。
line = "梨緒とナターシャも同じく、神殿内に墜落していた。"

[[dialogue]]
speaker = "梨緒"
# 「くっ……飛べない……さっきの爆発のせいか？」
line = "「くっ……飛べない……さっきの爆発のせいか？」"

[[dialogue]]
speaker = "梨緒"
# 「みんな、大丈夫か？」
line = "「みんな、大丈夫か？」"

[[dialogue]]
speaker = "ナターシャ"
# 「くそっ！　魔王ピンポイント狙いとかそんなのアリ！？　聞いてないっての！？」
line = "「くそっ！　魔王ピンポイント狙いとかそんなのアリ！？　聞いてないっての！？」"

[[dialogue]]
speaker = "梨緒"
# 「ナターシャ……？」
line = "「ナターシャ……？」"

[[dialogue]]
speaker = "unk"
# 普段の飄々とした態度と打って変わって、焦りと憤りを露わにするナターシャ。
line = "普段の飄々とした態度と打って変わって、焦りと憤りを露わにするナターシャ。"

[[dialogue]]
speaker = "unk"
# 初めて見る仲間の様子に、梨緒も困惑の表情を浮かべる。
line = "初めて見る仲間の様子に、梨緒も困惑の表情を浮かべる。"

[[dialogue]]
speaker = "ナターシャ"
# 「くそっ、くそっ……失敗した……！　これじゃ任務が……メルエルを見つけないと……」
line = "「くそっ、くそっ……失敗した……！　これじゃ任務が……メルエルを見つけないと……」"

[[dialogue]]
speaker = "梨緒"
# 「落ち着け、ナターシャ」
line = "「落ち着け、ナターシャ」"

[[dialogue]]
speaker = "ナターシャ"
# 「梨緒は何も知らないでしょ！」
line = "「梨緒は何も知らないでしょ！」"

[[dialogue]]
speaker = "梨緒"
# 「そうだ。君の任務のことなんて知らない」
line = "「そうだ。君の任務のことなんて知らない」"

[[dialogue]]
speaker = "梨緒"
# 「だが私が取り乱した時、君が落ち着かせてくれた。頼んでもいないのに、ズケズケと言ってくれただろう」
line = "「だが私が取り乱した時、君が落ち着かせてくれた。頼んでもいないのに、ズケズケと言ってくれただろう」"

[[dialogue]]
speaker = "梨緒"
# 「だから今は私が言うんだ。落ち着け、騒いだところで事態は好転しない」
line = "「だから今は私が言うんだ。落ち着け、騒いだところで事態は好転しない」"

[[dialogue]]
speaker = "ナターシャ"
# 「梨緒……」
line = "「梨緒……」"

[[dialogue]]
speaker = "ナターシャ"
# 「ごめん、ちょっと動転してた」
line = "「ごめん、ちょっと動転してた」"

[[dialogue]]
speaker = "ナターシャ"
# 「はぁ……梨緒になだめられるとか、私も焼きが回っちゃったかな」
line = "「はぁ……梨緒になだめられるとか、私も焼きが回っちゃったかな」"

[[dialogue]]
speaker = "梨緒"
# 「どういう意味だ」
line = "「どういう意味だ」"

[[dialogue]]
speaker = "梨緒"
# 「だが頭が冷えたならよかった。では、ひとまず整理するぞ」
line = "「だが頭が冷えたならよかった。では、ひとまず整理するぞ」"

[[dialogue]]
speaker = "梨緒"
# 「私たちはガーディアンの自爆に巻き込まれて、神殿内部に墜落した。飛行ができないのもおそらくそのガーディアンによるものだ」
line = "「私たちはガーディアンの自爆に巻き込まれて、神殿内部に墜落した。飛行ができないのもおそらくそのガーディアンによるものだ」"

[[dialogue]]
speaker = "ナターシャ"
# 「うん。あのガーディアンは多分、魔王の力に反応して爆発するようになっていたんだと思う」
line = "「うん。あのガーディアンは多分、魔王の力に反応して爆発するようになっていたんだと思う」"

[[dialogue]]
speaker = "ナターシャ"
# 「来る途中で説明した通り、この神殿は２０００年前、魔王に襲われたことがある」
line = "「来る途中で説明した通り、この神殿は２０００年前、魔王に襲われたことがある」"

[[dialogue]]
speaker = "ナターシャ"
# 「魔王に対して何かしら対策があるって、気付けたと思うんだけどな……。私が気を付けておかないといけなかったのに……」
line = "「魔王に対して何かしら対策があるって、気付けたと思うんだけどな……。私が気を付けておかないといけなかったのに……」"

[[dialogue]]
speaker = "梨緒"
# 「聖庭園で神殿の調査は行わなかったのか？」
line = "「聖庭園で神殿の調査は行わなかったのか？」"

[[dialogue]]
speaker = "ナターシャ"
# 「神殿は強力なガーディアンに防衛されてたから、なかなか近づけなかったんだよ」
line = "「神殿は強力なガーディアンに防衛されてたから、なかなか近づけなかったんだよ」"

[[dialogue]]
speaker = "ナターシャ"
# 「神殿を守ってくれるガーディアンを倒してまで、調査するのは合理的じゃないでしょ？」
line = "「神殿を守ってくれるガーディアンを倒してまで、調査するのは合理的じゃないでしょ？」"

[[dialogue]]
speaker = "梨緒"
# 「確かにな。でもそれならナターシャが悪いわけではないし、悔いても仕方ないことだろう」
line = "「確かにな。でもそれならナターシャが悪いわけではないし、悔いても仕方ないことだろう」"

[[dialogue]]
speaker = "ナターシャ"
# 「珍しく梨緒の方が切り替え早いなー。まぁそうだけど」
line = "「珍しく梨緒の方が切り替え早いなー。まぁそうだけど」"

[[dialogue]]
speaker = "梨緒"
# 「問題は味方と離れたこと、敵もまた神殿内部に侵入した可能性が高いことだ」
line = "「問題は味方と離れたこと、敵もまた神殿内部に侵入した可能性が高いことだ」"

[[dialogue]]
speaker = "梨緒"
# 「合流したいところだが……みんな実力者だ、私たちのようにそれぞれ生き残っているだろう」
line = "「合流したいところだが……みんな実力者だ、私たちのようにそれぞれ生き残っているだろう」"

[[dialogue]]
speaker = "梨緒"
# 「それより神殿の中枢に極星星徒会が到着する方がまずい。私たちも奥を目指すべきだ」
line = "「それより神殿の中枢に極星星徒会が到着する方がまずい。私たちも奥を目指すべきだ」"

[[dialogue]]
speaker = "ナターシャ"
# 「まぁ……そうだよね。メルエルたちも奥を目指してるなら、結果的にその方が合流もしやすいか」
line = "「まぁ……そうだよね。メルエルたちも奥を目指してるなら、結果的にその方が合流もしやすいか」"

[[dialogue]]
speaker = "フェアリー"
# 「──」
line = "「──」"

[[dialogue]]
speaker = "梨緒"
# 「やはり神殿内部にもガーディアンがいたか──！」
line = "「やはり神殿内部にもガーディアンがいたか──！」"

[[dialogue]]
speaker = "フェアリー"
# 「──！」
line = "「──！」"

[[dialogue]]
speaker = "梨緒"
# 「く……！？」
line = "「く……！？」"

[[dialogue]]
speaker = "？？？"
# 『私たちは歴史の影。闇に生き、消える者』
line = "『私たちは歴史の影。闇に生き、消える者』"

[[dialogue]]
speaker = "？？？"
# 『あなたの命は天界のためにある』
line = "『あなたの命は天界のためにある』"

[[dialogue]]
speaker = "？？？"
# 『あの子を守りなさい。もしあの子が死ぬなら、あなたが代わりに死になさい』
line = "『あの子を守りなさい。もしあの子が死ぬなら、あなたが代わりに死になさい』"

[[dialogue]]
speaker = "？？？"
# 『それが天界に生きる天使たちのためであり、あなたの生まれた意味よ』
line = "『それが天界に生きる天使たちのためであり、あなたの生まれた意味よ』"

[[dialogue]]
speaker = "梨緒"
# 「邪魔だ……！」
line = "「邪魔だ……！」"

[[dialogue]]
speaker = "unk"
# 頭の中に響く声に困惑しながらも、梨緒はクロスボウの一撃でガーディアンを射貫く。
line = "頭の中に響く声に困惑しながらも、梨緒はクロスボウの一撃でガーディアンを射貫く。"

[[dialogue]]
speaker = "梨緒"
# 「今の声は……何だ？」
line = "「今の声は……何だ？」"

[[dialogue]]
speaker = "ナターシャ"
# 「あ～、さっきの聞こえたんだ。ごめん。多分、私の記憶」
line = "「あ～、さっきの聞こえたんだ。ごめん。多分、私の記憶」"

[[dialogue]]
speaker = "梨緒"
# 「ナターシャの記憶……？」
line = "「ナターシャの記憶……？」"

[[dialogue]]
speaker = "ナターシャ"
# 「うん。侵入者を惑わせるために、記憶を喚起してるんじゃないかな」
line = "「うん。侵入者を惑わせるために、記憶を喚起してるんじゃないかな」"

[[dialogue]]
speaker = "ナターシャ"
# 「梨緒にまであれが聞こえたのは、きっとついでだね。侵入者が複数いる場合、余計に苦しむようにしてるんだ」
line = "「梨緒にまであれが聞こえたのは、きっとついでだね。侵入者が複数いる場合、余計に苦しむようにしてるんだ」"

[[dialogue]]
speaker = "梨緒"
# 「じゃあ今のは、本当に誰かが君に言った言葉なのか？　しかも君の声に似ている気がしたが……」
line = "「じゃあ今のは、本当に誰かが君に言った言葉なのか？　しかも君の声に似ている気がしたが……」"

[[dialogue]]
speaker = "ナターシャ"
# 「そりゃ似てるよ。言ったのはうちの母親だからね」
line = "「そりゃ似てるよ。言ったのはうちの母親だからね」"

[[dialogue]]
speaker = "梨緒"
# 「母親が……！？　実の娘に命を捨てろと言ったのか！？」
line = "「母親が……！？　実の娘に命を捨てろと言ったのか！？」"

[[dialogue]]
speaker = "ナターシャ"
# 「そうだよ。うちの家系は代々そんな感じだし」
line = "「そうだよ。うちの家系は代々そんな感じだし」"

[[dialogue]]
speaker = "梨緒"
# 「影に生きる暗殺者の家系……ということか」
line = "「影に生きる暗殺者の家系……ということか」"

[[dialogue]]
speaker = "ナターシャ"
# 「だから気にしないで。さっさと進も」
line = "「だから気にしないで。さっさと進も」"

[[dialogue]]
speaker = "unk"
# 墜落して取り乱した時とは反対に、あっけらかんとするナターシャ。
line = "墜落して取り乱した時とは反対に、あっけらかんとするナターシャ。"

[[dialogue]]
speaker = "unk"
# だが梨緒は眉をひそめたままだ。
line = "だが梨緒は眉をひそめたままだ。"

[[dialogue]]
speaker = "ナターシャ"
# 「梨緒？」
line = "「梨緒？」"

[[dialogue]]
speaker = "梨緒"
# 「……私は君のことをよく知っているわけではない。あまり感情を見せない君のことだから、なんとも思っていないのかもしれない」
line = "「……私は君のことをよく知っているわけではない。あまり感情を見せない君のことだから、なんとも思っていないのかもしれない」"

[[dialogue]]
speaker = "梨緒"
# 「だが……不愉快だ」
line = "「だが……不愉快だ」"

[[dialogue]]
speaker = "ナターシャ"
# 「不愉快？」
line = "「不愉快？」"

[[dialogue]]
speaker = "梨緒"
# 「だって、自分の意志で命を懸けるのと、人に命を捨てさせられるのは違うだろう……！」
line = "「だって、自分の意志で命を懸けるのと、人に命を捨てさせられるのは違うだろう……！」"

[[dialogue]]
speaker = "梨緒"
# 「だから……不愉快だ。たとえ君がそれを良しとしていても」
line = "「だから……不愉快だ。たとえ君がそれを良しとしていても」"

[[dialogue]]
speaker = "ナターシャ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ナターシャ"
# 「ふっ」
line = "「ふっ」"

[[dialogue]]
speaker = "梨緒"
# 「何がおかしい？」
line = "「何がおかしい？」"

[[dialogue]]
speaker = "ナターシャ"
# 「いや、確かに不愉快だなって思って。親の言うことでもムカつく時はムカつくよね」
line = "「いや、確かに不愉快だなって思って。親の言うことでもムカつく時はムカつくよね」"

[[dialogue]]
speaker = "ナターシャ"
# 「んじゃ気を取り直して、神殿の中を探検といきますか」
line = "「んじゃ気を取り直して、神殿の中を探検といきますか」"
