[[dialogue]]
speaker = "unk"
# 第２話,闇に生き、消える者,B
line = "第２話,闇に生き、消える者,B"

[[dialogue]]
speaker = "ケイティ"
# 「敵の規模と詳細を教えてください！　極星従騎と……何ですって！？　先日の仮面を被った使徒が……また現れた！？」
line = "「敵の規模と詳細を教えてください！　極星従騎と……何ですって！？　先日の仮面を被った使徒が……また現れた！？」"

[[dialogue]]
speaker = "メルエル"
# 「ど、どういうことっ！？　使徒だったジグさんは倒したはずだよね！？」
line = "「ど、どういうことっ！？　使徒だったジグさんは倒したはずだよね！？」"

[[dialogue]]
speaker = "ナターシャ"
# 「ジグがまた操られたってこと？　そんなまさか……通話だけじゃどうにもならないね。現場に行かないことには──」
line = "「ジグがまた操られたってこと？　そんなまさか……通話だけじゃどうにもならないね。現場に行かないことには──」"

[[dialogue]]
speaker = "メルエル"
# 「うん……！　会長くんのいる人間界で、何かトラブルがあったのかも……確かめなきゃ！」
line = "「うん……！　会長くんのいる人間界で、何かトラブルがあったのかも……確かめなきゃ！」"

[[dialogue]]
speaker = "ケイティ"
# 「──今しばらく持ちこたえてください！　すぐに衛兵隊が向かいます！」
line = "「──今しばらく持ちこたえてください！　すぐに衛兵隊が向かいます！」"

[[dialogue]]
speaker = "ケイティ"
# 「メルエルちゃん、ナターシャちゃんも！　到着して早々悪いけれど──手伝ってくれる！？」
line = "「メルエルちゃん、ナターシャちゃんも！　到着して早々悪いけれど──手伝ってくれる！？」"

[[dialogue]]
speaker = "メルエル"
# 「もちろんだよ、ケイティお姉ちゃん！」
line = "「もちろんだよ、ケイティお姉ちゃん！」"

[[dialogue]]
speaker = "ナターシャ"
# 「了解。極星従騎に使徒のジグ……戦力を出し惜しみしてる場合じゃないしね」
line = "「了解。極星従騎に使徒のジグ……戦力を出し惜しみしてる場合じゃないしね」"

[[dialogue]]
speaker = "ケイティ"
# 「仮面を被った使徒が相手となると、衛兵隊の人員も選抜しないと……少し待ってて！」
line = "「仮面を被った使徒が相手となると、衛兵隊の人員も選抜しないと……少し待ってて！」"

[[dialogue]]
speaker = "メルエル"
# 「まさか、デネブにいるルヴィネちゃんが、攻め込んできたのかな……？」
line = "「まさか、デネブにいるルヴィネちゃんが、攻め込んできたのかな……？」"

[[dialogue]]
speaker = "ナターシャ"
# 「その線は大いにあるだろうね。こんなに間を置かずに来るとは思ってなかったけど」
line = "「その線は大いにあるだろうね。こんなに間を置かずに来るとは思ってなかったけど」"

[[dialogue]]
speaker = "メルエル"
# 「ルヴィネちゃんの説得──できるかな？　会長くんは『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』と交渉するために、共闘したいって言ってたけど……」
line = "「ルヴィネちゃんの説得──できるかな？　会長くんは『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』と交渉するために、共闘したいって言ってたけど……」"

[[dialogue]]
speaker = "ナターシャ"
# 「お気楽すぎない？　私たちの言葉で心を動かすようなタマじゃないよ、あの天使は」
line = "「お気楽すぎない？　私たちの言葉で心を動かすようなタマじゃないよ、あの天使は」"

[[dialogue]]
speaker = "メルエル"
# 「そ、そっか。ナターシャちゃんは、デネブでルヴィネちゃんに会ってるんだよね」
line = "「そ、そっか。ナターシャちゃんは、デネブでルヴィネちゃんに会ってるんだよね」"

[[dialogue]]
speaker = "ナターシャ"
# 「そ。だから甘い考えは捨てて。戦闘中に説得なんてしてる暇、絶対ないから」
line = "「そ。だから甘い考えは捨てて。戦闘中に説得なんてしてる暇、絶対ないから」"

[[dialogue]]
speaker = "メルエル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ナターシャ"
# （やっぱりメルエルは危ういね。こんな状況でも、説得だとか。性善説が服を着て歩いてるみたい）
line = "（やっぱりメルエルは危ういね。こんな状況でも、説得だとか。性善説が服を着て歩いてるみたい）"

[[dialogue]]
speaker = "unk"
# 幼なじみの天使にばれないように嘆息したナターシャだったが──
line = "幼なじみの天使にばれないように嘆息したナターシャだったが──"

[[dialogue]]
speaker = "ナターシャ"
# 「────ぁ」
line = "「────ぁ」"

[[dialogue]]
speaker = "unk"
# その時、天使の人混みに紛れて立つ、１人の女性の姿を捉えた。
line = "その時、天使の人混みに紛れて立つ、１人の女性の姿を捉えた。"

[[dialogue]]
speaker = "ナターシャ"
# 「…………ごめん、メルエル。ちょっと席を外すよ」
line = "「…………ごめん、メルエル。ちょっと席を外すよ」"

[[dialogue]]
speaker = "メルエル"
# 「えっ？　う、うん……」
line = "「えっ？　う、うん……」"

[[dialogue]]
speaker = "unk"
# 続々と聖庭園内に集まる天使たちの間を縫い、ナターシャは自分の上司の元へと歩を進める。
line = "続々と聖庭園内に集まる天使たちの間を縫い、ナターシャは自分の上司の元へと歩を進める。"

[[dialogue]]
speaker = "ナターシャ"
# 「……何、母さん」
line = "「……何、母さん」"

[[dialogue]]
speaker = "ナターシャの母"
# 「想定外の事態となったようね、ナターシャ」
line = "「想定外の事態となったようね、ナターシャ」"

[[dialogue]]
speaker = "ナターシャ"
# 「そうだね。天界がまた襲撃されるだなんて……これから出撃するよ」
line = "「そうだね。天界がまた襲撃されるだなんて……これから出撃するよ」"

[[dialogue]]
speaker = "ナターシャの母"
# 「私たちの一族の役目、忘れてはいないわね？」
line = "「私たちの一族の役目、忘れてはいないわね？」"

[[dialogue]]
speaker = "ナターシャの母"
# 「……姫にあなたの正体がバレてしまったことは報告で聞いたわ。その落ち度については、もうどうしようもない」
line = "「……姫にあなたの正体がバレてしまったことは報告で聞いたわ。その落ち度については、もうどうしようもない」"

[[dialogue]]
speaker = "ナターシャの母"
# 「けれど──全てが明るみに出たとしても、あなたの使命に変わりはないわ」
line = "「けれど──全てが明るみに出たとしても、あなたの使命に変わりはないわ」"

[[dialogue]]
speaker = "ナターシャ"
# 「……命令したリガルタ老は、もういないけどね」
line = "「……命令したリガルタ老は、もういないけどね」"

[[dialogue]]
speaker = "ナターシャの母"
# 「口を慎みなさい。リガルタ様がお隠れになったとて、受けた命は遂行する。それが我ら一族の役目よ」
line = "「口を慎みなさい。リガルタ様がお隠れになったとて、受けた命は遂行する。それが我ら一族の役目よ」"

[[dialogue]]
speaker = "ナターシャ"
# （……本当に変わらないね、この人は）
line = "（……本当に変わらないね、この人は）"

[[dialogue]]
speaker = "ナターシャの母"
# 「本来なら使徒との戦いの場に姫を向かわせるなど、あってはならないこと……けれど口で制して聞く御方でないのだから、仕方がない」
line = "「本来なら使徒との戦いの場に姫を向かわせるなど、あってはならないこと……けれど口で制して聞く御方でないのだから、仕方がない」"

[[dialogue]]
speaker = "ナターシャの母"
# 「──何があっても姫を守りなさい」
line = "「──何があっても姫を守りなさい」"

[[dialogue]]
speaker = "ナターシャ"
# （あなたの娘だって、これから死地に行くのに。いつもメルエルのことしか喋らない──ほんと、機械みたい）
line = "（あなたの娘だって、これから死地に行くのに。いつもメルエルのことしか喋らない──ほんと、機械みたい）"

[[dialogue]]
speaker = "ナターシャの母"
# 「姫が死の危険に相対したときは……わかっているわね？」
line = "「姫が死の危険に相対したときは……わかっているわね？」"

[[dialogue]]
speaker = "ナターシャ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ナターシャの母"
# 「返事をしなさい、ナターシャ」
line = "「返事をしなさい、ナターシャ」"

[[dialogue]]
speaker = "ナターシャ"
# 「…………承知いたしました」
line = "「…………承知いたしました」"

[[dialogue]]
speaker = "ナターシャの母"
# 「話は終わりよ。戻りなさい」
line = "「話は終わりよ。戻りなさい」"

[[dialogue]]
speaker = "unk"
# 言うだけ言い放ち、聖庭園の建物の中へ消えていく母親を一瞥してから、ナターシャはメルエルの元へ戻った。
line = "言うだけ言い放ち、聖庭園の建物の中へ消えていく母親を一瞥してから、ナターシャはメルエルの元へ戻った。"

[[dialogue]]
speaker = "ナターシャ"
# 「──お待たせ、メルエル」
line = "「──お待たせ、メルエル」"

[[dialogue]]
speaker = "メルエル"
# 「う、うん……。さっきの人って、ナターシャちゃんのお母さん、だよね？」
line = "「う、うん……。さっきの人って、ナターシャちゃんのお母さん、だよね？」"

[[dialogue]]
speaker = "ナターシャ"
# 「それが？」
line = "「それが？」"

[[dialogue]]
speaker = "メルエル"
# 「えっと……何のお話、してたのかなって……」
line = "「えっと……何のお話、してたのかなって……」"

[[dialogue]]
speaker = "ナターシャ"
# 「別に大したことはしてないよ。これから死地に向かうわけだから、色々心配してくれただけ」
line = "「別に大したことはしてないよ。これから死地に向かうわけだから、色々心配してくれただけ」"

[[dialogue]]
speaker = "ナターシャ"
# 「天界を守るために頑張れとか、武運を祈るとか、そういう言葉をかけてもらったよ」
line = "「天界を守るために頑張れとか、武運を祈るとか、そういう言葉をかけてもらったよ」"

[[dialogue]]
speaker = "メルエル"
# 「…………ほんとに？」
line = "「…………ほんとに？」"

[[dialogue]]
speaker = "ナターシャ"
# 「──ふふっ。なんだ、察しがいいね。ついこの間まで、うちの母さんのこと……『物静かだけど優しそうな人』だとか言ってたのにね？」
line = "「──ふふっ。なんだ、察しがいいね。ついこの間まで、うちの母さんのこと……『物静かだけど優しそうな人』だとか言ってたのにね？」"

[[dialogue]]
speaker = "メルエル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ナターシャ"
# 「──やっぱり私、メルエルのこと、嫌いだな」
line = "「──やっぱり私、メルエルのこと、嫌いだな」"

[[dialogue]]
speaker = "メルエル"
# 「ナターシャちゃん──」
line = "「ナターシャちゃん──」"

[[dialogue]]
speaker = "ケイティ"
# 「２人とも、お待たせ！　行きましょう！！」
line = "「２人とも、お待たせ！　行きましょう！！」"

[[dialogue]]
speaker = "メルエル"
# 「あ──う、うんっ……！」
line = "「あ──う、うんっ……！」"

[[dialogue]]
speaker = "ナターシャ"
# 「ケイティ姉さんにも教えておくよ。ジグは未来の可能性を視る星眼を持ってる。気を付けて──」
line = "「ケイティ姉さんにも教えておくよ。ジグは未来の可能性を視る星眼を持ってる。気を付けて──」"

[[dialogue]]
speaker = "ネビュラの魔女"
# 「ぐっ──ぅうっ……！！」
line = "「ぐっ──ぅうっ……！！」"

[[dialogue]]
speaker = "ジグ"
# 「何だ──永き時を生きる魔女だなんて言っても、こんなものか。期待外れだね」
line = "「何だ──永き時を生きる魔女だなんて言っても、こんなものか。期待外れだね」"

[[dialogue]]
speaker = "ネビュラの魔女"
# （まずいっ……世界樹の門を奪われては、人間界にも害が及ぶ！）
line = "（まずいっ……世界樹の門を奪われては、人間界にも害が及ぶ！）"

[[dialogue]]
speaker = "ネビュラの魔女"
# （敵の手に、世界樹を渡すわけにはいかない──！）
line = "（敵の手に、世界樹を渡すわけにはいかない──！）"

[[dialogue]]
speaker = "unk"
# ネビュラの魔女は最後の力を振り絞り、魔力を編む──
line = "ネビュラの魔女は最後の力を振り絞り、魔力を編む──"

[[dialogue]]
speaker = "ジグ"
# 「散れ──『真なる神』に仇名す、不忠者──」
line = "「散れ──『真なる神』に仇名す、不忠者──」"

[[dialogue]]
speaker = "ネビュラの魔女"
# 「──あぁぁぁあああぁっ！！」
line = "「──あぁぁぁあああぁっ！！」"

[[dialogue]]
speaker = "unk"
# 使徒ジグの斬撃をまともに受けながらも、魔女は編み込んだ魔力を解き放つ──その狙いは敵ではなく、世界樹の扉。
line = "使徒ジグの斬撃をまともに受けながらも、魔女は編み込んだ魔力を解き放つ──その狙いは敵ではなく、世界樹の扉。"

[[dialogue]]
speaker = "ジグ"
# 「……へえ？」
line = "「……へえ？」"

[[dialogue]]
speaker = "unk"
# 魔力の鎖が世界樹の扉に巻き付き、強固な結界となって封鎖された。
line = "魔力の鎖が世界樹の扉に巻き付き、強固な結界となって封鎖された。"

[[dialogue]]
speaker = "ネビュラの魔女"
# 「申し訳、ありませんっ……クラウディア様…………」
line = "「申し訳、ありませんっ……クラウディア様…………」"

[[dialogue]]
speaker = "unk"
# 倒れ伏す魔女を見下ろす、使徒ジグのシャドウ──
line = "倒れ伏す魔女を見下ろす、使徒ジグのシャドウ──"

[[dialogue]]
speaker = "ジグ"
# 「自分の身の安全よりも、主人のために動いたか……その忠義は評価するよ」
line = "「自分の身の安全よりも、主人のために動いたか……その忠義は評価するよ」"

[[dialogue]]
speaker = "ジグ"
# 「でも──皮肉だね。手間が省けた。君が扉を封印しなければ、私がしようと思っていたんだよ……ふふっ」
line = "「でも──皮肉だね。手間が省けた。君が扉を封印しなければ、私がしようと思っていたんだよ……ふふっ」"

[[dialogue]]
speaker = "？？？"
# 『──使徒の影。首尾はどうかしら？』
line = "『──使徒の影。首尾はどうかしら？』"

[[dialogue]]
speaker = "ジグ"
# 「問題ない。世界樹は封鎖された。人間界からの応援は絶望的──天界が襲撃されている事実も、一切漏れていない」
line = "「問題ない。世界樹は封鎖された。人間界からの応援は絶望的──天界が襲撃されている事実も、一切漏れていない」"

[[dialogue]]
speaker = "？？？"
# 『上出来ね。手筈通り動きなさい。できうる限り、天界を破壊するのよ』
line = "『上出来ね。手筈通り動きなさい。できうる限り、天界を破壊するのよ』"

[[dialogue]]
speaker = "ジグ"
# 「承知した。『真なる神』のために、今度こそ──」
line = "「承知した。『真なる神』のために、今度こそ──」"

[[dialogue]]
speaker = "ナターシャ"
# 「ふっ──！！！」
line = "「ふっ──！！！」"

[[dialogue]]
speaker = "ジグ"
# 「おやおや。遅い到着だね、星騎士たち？」
line = "「おやおや。遅い到着だね、星騎士たち？」"

[[dialogue]]
speaker = "ナターシャ"
# 「……やっぱり未来視を持ってる相手に奇襲は通じない、か」
line = "「……やっぱり未来視を持ってる相手に奇襲は通じない、か」"

[[dialogue]]
speaker = "メルエル"
# 「使徒だった頃のジグさんとは、雰囲気が違う……！？」
line = "「使徒だった頃のジグさんとは、雰囲気が違う……！？」"

[[dialogue]]
speaker = "ナターシャ"
# 「急造した模造品ってところかな。この前交戦したジグと比べるべくもない。これは希望が出てきたかな？」
line = "「急造した模造品ってところかな。この前交戦したジグと比べるべくもない。これは希望が出てきたかな？」"

[[dialogue]]
speaker = "ジグ"
# 「呑気なものだ。確かにオリジナルに比べると幾分、力は劣るが……それでも君たちを葬るくらい、わけはないことさ」
line = "「呑気なものだ。確かにオリジナルに比べると幾分、力は劣るが……それでも君たちを葬るくらい、わけはないことさ」"

[[dialogue]]
speaker = "ケイティ"
# 「それはやってみなくてはわかりませんね。聖庭園の力、ご覧に入れましょう！」
line = "「それはやってみなくてはわかりませんね。聖庭園の力、ご覧に入れましょう！」"

[[dialogue]]
speaker = "ジグ"
# 「──おや。そちらの天使は、相当な手練れだね。これは愉しめそうだ」
line = "「──おや。そちらの天使は、相当な手練れだね。これは愉しめそうだ」"

[[dialogue]]
speaker = "ジグ"
# 「前菜は本当に期待外れでね……退屈していたんだよ」
line = "「前菜は本当に期待外れでね……退屈していたんだよ」"

[[dialogue]]
speaker = "unk"
# ジグのシャドウが、足元に倒れ伏した魔女を一瞥してくつくつと笑う。
line = "ジグのシャドウが、足元に倒れ伏した魔女を一瞥してくつくつと笑う。"

[[dialogue]]
speaker = "メルエル"
# 「──っ！？　魔女さんが……！！」
line = "「──っ！？　魔女さんが……！！」"

[[dialogue]]
speaker = "ナターシャ"
# 「息はある……みたいだけど。かなり危ない状況だね」
line = "「息はある……みたいだけど。かなり危ない状況だね」"

[[dialogue]]
speaker = "メルエル"
# 「こんな、ひどい……絶対に許さない！」
line = "「こんな、ひどい……絶対に許さない！」"

[[dialogue]]
speaker = "ケイティ"
# 「天界を荒らす輩を見過ごすわけにはまいりません──制圧させていただきます！！」
line = "「天界を荒らす輩を見過ごすわけにはまいりません──制圧させていただきます！！」"
