[[dialogue]]
speaker = "unk"
# 第３話,はじめてのアステラ,B
line = "第３話,はじめてのアステラ,B"

[[dialogue]]
speaker = "ヴィーナス"
# 「私たちの星徒会、最初の行事は──」
line = "「私たちの星徒会、最初の行事は──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「新入生歓迎会よ！」
line = "「新入生歓迎会よ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「未来の新星学園を担う新入生たちを、盛大に歓迎するわ！　一生忘れられない想い出にするわよ！」
line = "「未来の新星学園を担う新入生たちを、盛大に歓迎するわ！　一生忘れられない想い出にするわよ！」"

[[dialogue]]
speaker = "サーシャ"
# 「去年は私たちがやったのよね～。ヴィーナスちゃん、マトイちゃん、どうだった？」
line = "「去年は私たちがやったのよね～。ヴィーナスちゃん、マトイちゃん、どうだった？」"

[[dialogue]]
speaker = "マトイ"
# 「サーシャさんの星徒会長挨拶が印象的でした。凛としてて、素敵な会長さんだって思いました」
line = "「サーシャさんの星徒会長挨拶が印象的でした。凛としてて、素敵な会長さんだって思いました」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら、嬉しいわ～♪」
line = "「あらあら、嬉しいわ～♪」"

[[dialogue]]
speaker = "マトイ"
# 「他には、学園での生活を紹介したり、体育祭や文化祭といった年間行事の伝達……あと各部活動によるデモンストレーションなどですね」
line = "「他には、学園での生活を紹介したり、体育祭や文化祭といった年間行事の伝達……あと各部活動によるデモンストレーションなどですね」"

[[dialogue]]
speaker = "マトイ"
# 「毎年やっていることですし、記録も残ってますから、段取り通りに進めれば、それなりに盛り上が――」
line = "「毎年やっていることですし、記録も残ってますから、段取り通りに進めれば、それなりに盛り上が――」"

[[dialogue]]
speaker = "ヴィーナス"
# 「段取り通り？　それなり？　そんなの面白くないわ！」
line = "「段取り通り？　それなり？　そんなの面白くないわ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「今までとは一味も七味も違う星徒会だというところを、発足最初のイベントで学園中に見せつけるの！」
line = "「今までとは一味も七味も違う星徒会だというところを、発足最初のイベントで学園中に見せつけるの！」"

[[dialogue]]
speaker = "マトイ"
# 「星徒会は唐辛子じゃないです！」
line = "「星徒会は唐辛子じゃないです！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「スーパーミラクル面白イベントができないかしら？　素晴らしいアイデアをちょうだい。例えば……そうね、流星市国フルマラソンとか！」
line = "「スーパーミラクル面白イベントができないかしら？　素晴らしいアイデアをちょうだい。例えば……そうね、流星市国フルマラソンとか！」"

[[dialogue]]
speaker = "マトイ"
# 「入ったばかりの新入生に過酷すぎません！？」
line = "「入ったばかりの新入生に過酷すぎません！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「平等に在校生全員強制参加にするわ！」
line = "「平等に在校生全員強制参加にするわ！」"

[[dialogue]]
speaker = "マトイ"
# 「支持率大暴落待ったなしです！」
line = "「支持率大暴落待ったなしです！」"

[[dialogue]]
speaker = "サーシャ"
# 「もっと見ているだけでも、楽しめる物の方が良いんじゃないかしら～」
line = "「もっと見ているだけでも、楽しめる物の方が良いんじゃないかしら～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それならサーカスなんてどうかしら！」
line = "「それならサーカスなんてどうかしら！」"

[[dialogue]]
speaker = "マトイ"
# 「サーカス団でも呼ぶんですか？　突然のオファーは難しいと思いますけど……」
line = "「サーカス団でも呼ぶんですか？　突然のオファーは難しいと思いますけど……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「もちろん、私たちでやるのよ！　ライオンを調教して日の輪くぐりをマスターさせるの！」
line = "「もちろん、私たちでやるのよ！　ライオンを調教して日の輪くぐりをマスターさせるの！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「クライマックスは、サーシャさんとマトイの命綱なしの空中ブランコ３回転半！」
line = "「クライマックスは、サーシャさんとマトイの命綱なしの空中ブランコ３回転半！」"

[[dialogue]]
speaker = "サーシャ"
# 「まあまあ、綺麗に決められたら、絶対盛り上がるわね～。マトイちゃん、できる～？」
line = "「まあまあ、綺麗に決められたら、絶対盛り上がるわね～。マトイちゃん、できる～？」"

[[dialogue]]
speaker = "マトイ"
# 「できるわけないですねー！？」
line = "「できるわけないですねー！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「特訓の時間が欲しい、ってことね？」
line = "「特訓の時間が欲しい、ってことね？」"

[[dialogue]]
speaker = "マトイ"
# 「特訓してもです！　そんな離れ技、一朝一夕でできるはずがないじゃないですか！」
line = "「特訓してもです！　そんな離れ技、一朝一夕でできるはずがないじゃないですか！」"

[[dialogue]]
speaker = "マトイ"
# （あ、あれ？　この星徒会って、放っておいたらヴィーナス会長の暴走を止める人が……いない？）
line = "（あ、あれ？　この星徒会って、放っておいたらヴィーナス会長の暴走を止める人が……いない？）"

[[dialogue]]
speaker = "ヴィーナス"
# 「それなら……花火大会はどう？　ドドーンって！　盛り上がること間違いなしよ！」
line = "「それなら……花火大会はどう？　ドドーンって！　盛り上がること間違いなしよ！」"

[[dialogue]]
speaker = "マトイ"
# 「今までのアイデアに比べたら、幾分か現実味がありますけど……花火玉ってすごく高いんですよ？」
line = "「今までのアイデアに比べたら、幾分か現実味がありますけど……花火玉ってすごく高いんですよ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「１万テルスくらい？」
line = "「１万テルスくらい？」"

[[dialogue]]
speaker = "マトイ"
# 「桁が２つ違います！」
line = "「桁が２つ違います！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「１００テルス？」
line = "「１００テルス？」"

[[dialogue]]
speaker = "マトイ"
# 「なんで減るんですか！　逆です！　増えるんです！」
line = "「なんで減るんですか！　逆です！　増えるんです！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「へ～、１００万テルスもするのね？　会計のサーシャさん、予算は？」
line = "「へ～、１００万テルスもするのね？　会計のサーシャさん、予算は？」"

[[dialogue]]
speaker = "サーシャ"
# 「会計的にはＯＫ出せませ～ん」
line = "「会計的にはＯＫ出せませ～ん」"

[[dialogue]]
speaker = "ヴィーナス"
# 「も～、あれもダメ、これもダメで仕方ないわね。アイデア出しは持ち帰りで。また明日、改めて話し合いましょ！」
line = "「も～、あれもダメ、これもダメで仕方ないわね。アイデア出しは持ち帰りで。また明日、改めて話し合いましょ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうだわ、話は変わるけど、私、流星の会長みたいにマントが欲しいの！　あれがあれば一目で星徒会長ってわかるでしょ。風でたなびいたりすると格好いいじゃない！」
line = "「そうだわ、話は変わるけど、私、流星の会長みたいにマントが欲しいの！　あれがあれば一目で星徒会長ってわかるでしょ。風でたなびいたりすると格好いいじゃない！」"

[[dialogue]]
speaker = "マトイ"
# 「それは確かに……代々、会長に受け継がれていったりすると素敵ですね」
line = "「それは確かに……代々、会長に受け継がれていったりすると素敵ですね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でしょう？　やがて歴代の血と汗と想いが染み込んだエモエモマントになるの」
line = "「でしょう？　やがて歴代の血と汗と想いが染み込んだエモエモマントになるの」"

[[dialogue]]
speaker = "ヴィーナス"
# 「マントって、どれくらいするのかしら？　さすがに１００万テルスはしないわよね？」
line = "「マントって、どれくらいするのかしら？　さすがに１００万テルスはしないわよね？」"

[[dialogue]]
speaker = "サーシャ"
# 「どうかしら～。ピンキリだと思うけど……あまり複雑な物でなければ、私でも作れるわよ～」
line = "「どうかしら～。ピンキリだと思うけど……あまり複雑な物でなければ、私でも作れるわよ～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ホント！？　それは是非お願いしたいわ！　なるはやだと嬉しい──」
line = "「ホント！？　それは是非お願いしたいわ！　なるはやだと嬉しい──」"

[[dialogue]]
speaker = "マトイ"
# 「！　この音は──」
line = "「！　この音は──」"

[[dialogue]]
speaker = "サーシャ"
# 「アステラが発生したわね～」
line = "「アステラが発生したわね～」"

[[dialogue]]
speaker = "マトイ"
# （一般人だったら、緊急避難のアラーム。速やかに安全な建物に避難し、救援を待つ……）
line = "（一般人だったら、緊急避難のアラーム。速やかに安全な建物に避難し、救援を待つ……）"

[[dialogue]]
speaker = "マトイ"
# （でも、今の私は違う！　私もまた、アステラを制圧する部隊なんだから！！）
line = "（でも、今の私は違う！　私もまた、アステラを制圧する部隊なんだから！！）"

[[dialogue]]
speaker = "ヴィーナス"
# 「出撃の合図よ！　新星学園星徒会、行くわよ！」
line = "「出撃の合図よ！　新星学園星徒会、行くわよ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「到着ーっと！　ちゃんとついてきてる？」
line = "「到着ーっと！　ちゃんとついてきてる？」"

[[dialogue]]
speaker = "サーシャ"
# 「ヴィーナスちゃん星徒会、初めての出撃ね」
line = "「ヴィーナスちゃん星徒会、初めての出撃ね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「記念すべき初陣、失敗は許されないわ！　失敗なんてしたことないけど！」
line = "「記念すべき初陣、失敗は許されないわ！　失敗なんてしたことないけど！」"

[[dialogue]]
speaker = "サーシャ"
# 「マトイちゃんはアステラに入るのは初めて？」
line = "「マトイちゃんはアステラに入るのは初めて？」"

[[dialogue]]
speaker = "マトイ"
# 「は、はい、見たことはありますけど、入るのは初めてです」
line = "「は、はい、見たことはありますけど、入るのは初めてです」"

[[dialogue]]
speaker = "サーシャ"
# 「初めてはなんでもドキドキしちゃうわよね～。でも安心して。マトイちゃんが怪我しないよう、私たちがちゃ～んと守るから」
line = "「初めてはなんでもドキドキしちゃうわよね～。でも安心して。マトイちゃんが怪我しないよう、私たちがちゃ～んと守るから」"

[[dialogue]]
speaker = "マトイ"
# 「あ、ありがとうございます」
line = "「あ、ありがとうございます」"

[[dialogue]]
speaker = "ヴィーナス"
# 「サーシャさん、あんまり甘やかしてばっかりもダメよ。マトイにも星徒会役員として、ちゃんと仕事してもらうんだから。できるわよね？」
line = "「サーシャさん、あんまり甘やかしてばっかりもダメよ。マトイにも星徒会役員として、ちゃんと仕事してもらうんだから。できるわよね？」"

[[dialogue]]
speaker = "マトイ"
# 「……っ！」
line = "「……っ！」"

[[dialogue]]
speaker = "マトイ"
# 「そうですよね……私だって星徒会役員の端くれ。２人におんぶに抱っこじゃダメですよね」
line = "「そうですよね……私だって星徒会役員の端くれ。２人におんぶに抱っこじゃダメですよね」"

[[dialogue]]
speaker = "マトイ"
# （初めてのことだし……『やれる』なんて断言はできないけど、私は私にできる努力をするだけだ）
line = "（初めてのことだし……『やれる』なんて断言はできないけど、私は私にできる努力をするだけだ）"

[[dialogue]]
speaker = "マトイ"
# （私から努力を取ったら、何も残らないんだから！）
line = "（私から努力を取ったら、何も残らないんだから！）"

[[dialogue]]
speaker = "マトイ"
# 「やります！」
line = "「やります！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「うん、良い返事だわ！　突入よ！」
line = "「うん、良い返事だわ！　突入よ！」"

[[dialogue]]
speaker = "マトイ"
# 「はぁっ！」
line = "「はぁっ！」"

[[dialogue]]
speaker = "サーシャ"
# 「マトイちゃん、やるじゃな～い！」
line = "「マトイちゃん、やるじゃな～い！」"

[[dialogue]]
speaker = "マトイ"
# （確かにアステラの外のモンスターよりは強いけれど、歯が立たないわけじゃない、攻撃は通っている）
line = "（確かにアステラの外のモンスターよりは強いけれど、歯が立たないわけじゃない、攻撃は通っている）"

[[dialogue]]
speaker = "マトイ"
# 「ぐっ！」
line = "「ぐっ！」"

[[dialogue]]
speaker = "マトイ"
# （盾でモンスターの攻撃を受け止められる。私が盾で受け止めて、隙を作れば──）
line = "（盾でモンスターの攻撃を受け止められる。私が盾で受け止めて、隙を作れば──）"

[[dialogue]]
speaker = "ヴィーナス"
# 「消し飛びなさい！」
line = "「消し飛びなさい！」"

[[dialogue]]
speaker = "マトイ"
# 「サーシャさん、後ろです！」
line = "「サーシャさん、後ろです！」"

[[dialogue]]
speaker = "サーシャ"
# 「マトイちゃん、ありがと～。えーーーいっ！」
line = "「マトイちゃん、ありがと～。えーーーいっ！」"

[[dialogue]]
speaker = "マトイ"
# （サーシャさんが倒してくれた！）
line = "（サーシャさんが倒してくれた！）"

[[dialogue]]
speaker = "マトイ"
# （大丈夫。ちゃんと周りだって、見えてる！　私だって星徒会のみんなと一緒に戦えるんだ！）
line = "（大丈夫。ちゃんと周りだって、見えてる！　私だって星徒会のみんなと一緒に戦えるんだ！）"

[[dialogue]]
speaker = "ヴィーナス"
# 「お疲れさまー！」
line = "「お疲れさまー！」"

[[dialogue]]
speaker = "サーシャ"
# 「思っていたよりもずっと楽に片付いたわね～」
line = "「思っていたよりもずっと楽に片付いたわね～」"

[[dialogue]]
speaker = "マトイ"
# 「はぁ、はぁっ、お疲れ、さま、でしたっ……！」
line = "「はぁ、はぁっ、お疲れ、さま、でしたっ……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「マトイ、さっきの戦い、星力を出し過ぎよ。常にフルパワーにするんじゃなくって、必要な時に必要な分だけ出した方が、長時間戦えるようになるわよ」
line = "「マトイ、さっきの戦い、星力を出し過ぎよ。常にフルパワーにするんじゃなくって、必要な時に必要な分だけ出した方が、長時間戦えるようになるわよ」"

[[dialogue]]
speaker = "サーシャ"
# 「まあまあ。そういわれても、初めてのアステラじゃわからないわよね～」
line = "「まあまあ。そういわれても、初めてのアステラじゃわからないわよね～」"

[[dialogue]]
speaker = "サーシャ"
# 「大丈夫よ、マトイちゃん。気を抜いても大丈夫な時とダメな時。任務を重ねる内に、自然とわかるようになるわ～」
line = "「大丈夫よ、マトイちゃん。気を抜いても大丈夫な時とダメな時。任務を重ねる内に、自然とわかるようになるわ～」"

[[dialogue]]
speaker = "マトイ"
# 「そ、そうですか……頑張ります……」
line = "「そ、そうですか……頑張ります……」"

[[dialogue]]
speaker = "マトイ"
# 「私、おふたりの足を引っ張ってませんでしたか……？」
line = "「私、おふたりの足を引っ張ってませんでしたか……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「？　おかしなこと言うのね。すっごくいい仕事してたわよ！」
line = "「？　おかしなこと言うのね。すっごくいい仕事してたわよ！」"

[[dialogue]]
speaker = "サーシャ"
# 「マトイちゃんのおかげで、いつもより楽チンに戦えたわ～。さすがヴィーナスちゃんが選んだ子ね～」
line = "「マトイちゃんのおかげで、いつもより楽チンに戦えたわ～。さすがヴィーナスちゃんが選んだ子ね～」"

[[dialogue]]
speaker = "マトイ"
# 「そう、ですか……？　ちゃんと役に立ててたなら、良かったです……嬉しいです……！」
line = "「そう、ですか……？　ちゃんと役に立ててたなら、良かったです……嬉しいです……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「自分がチームにどれだけ貢献できているのか、気づけるようになったら一人前かもね。次も頑張りなさい！　期待してるわ！」
line = "「自分がチームにどれだけ貢献できているのか、気づけるようになったら一人前かもね。次も頑張りなさい！　期待してるわ！」"

[[dialogue]]
speaker = "マトイ"
# 「は、はいっ……！」
line = "「は、はいっ……！」"

[[dialogue]]
speaker = "マトイ"
# 「……あれっ？」
line = "「……あれっ？」"

[[dialogue]]
speaker = "マトイ"
# 「あの、ごめんなさい、肩、貸してもらえませんか……？　もう一歩も動けそうになくて……」
line = "「あの、ごめんなさい、肩、貸してもらえませんか……？　もう一歩も動けそうになくて……」"

[[dialogue]]
speaker = "サーシャ"
# 「うんうん、マトイちゃん、頑張ったものね～」
line = "「うんうん、マトイちゃん、頑張ったものね～」"

[[dialogue]]
speaker = "マトイ"
# 「はい、すみま……せん……」
line = "「はい、すみま……せん……」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら、気を失っちゃったみたい。初めての戦いだし無理もないかしら？」
line = "「あらあら、気を失っちゃったみたい。初めての戦いだし無理もないかしら？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうね。後のことは私たちに任せて、マトイはゆっくり休んでなさい！」
line = "「そうね。後のことは私たちに任せて、マトイはゆっくり休んでなさい！」"

[[dialogue]]
speaker = "マトイ"
# （はい……ありがとう、ございます……）
line = "（はい……ありがとう、ございます……）"

[[dialogue]]
speaker = "マトイ"
# （……ふふ……私、やれた……よね……？）
line = "（……ふふ……私、やれた……よね……？）"

[[dialogue]]
speaker = "マトイ"
# （私でも……星徒会でやっていけるんだ……うん……これからも頑張るぞ……）
line = "（私でも……星徒会でやっていけるんだ……うん……これからも頑張るぞ……）"
