[[dialogue]]
speaker = "unk"
# 第４話,流星教皇庁,B
line = "第４話,流星教皇庁,B"

[[dialogue]]
speaker = "unk"
# ──翌日。
line = "──翌日。"

[[dialogue]]
speaker = "unk"
# 週末ということで学園もお休みの今日だったが、俺たちは制服を着てある場所へと出向いていた。
line = "週末ということで学園もお休みの今日だったが、俺たちは制服を着てある場所へと出向いていた。"

[[dialogue]]
speaker = "unk"
# それというのが……
line = "それというのが……"

[[dialogue]]
speaker = "マトイ"
# 「こ──ここが星見会長の邸宅……！」
line = "「こ──ここが星見会長の邸宅……！」"

[[dialogue]]
speaker = "サーシャ"
# 「ん～ゴージャスね♪　ふふふ、お姫様になったみたいだわ」
line = "「ん～ゴージャスね♪　ふふふ、お姫様になったみたいだわ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「やるわね！　九浄の家とは違った趣があるわ」
line = "「やるわね！　九浄の家とは違った趣があるわ」"

[[dialogue]]
speaker = "ルリエル"
# 「ひええ……！　初めて入るでありますっ！　わたしのような者が踏み入って良いものでしょうか……！？」
line = "「ひええ……！　初めて入るでありますっ！　わたしのような者が踏み入って良いものでしょうか……！？」"

[[dialogue]]
speaker = "ソフィア"
# 「フィ、フィ、フィオナ会長のお家に……！　し、しし深呼吸しないと……！」
line = "「フィ、フィ、フィオナ会長のお家に……！　し、しし深呼吸しないと……！」"

[[dialogue]]
speaker = "クロト"
# 「すごいな……」
line = "「すごいな……」"

[[dialogue]]
speaker = "unk"
# 口々に豪奢な景観への感想を述べる。
line = "口々に豪奢な景観への感想を述べる。"

[[dialogue]]
speaker = "unk"
# 誰にそうしろと言われたわけでもないが、自然と口をついてしまうほどその場の空気が圧巻だった。
line = "誰にそうしろと言われたわけでもないが、自然と口をついてしまうほどその場の空気が圧巻だった。"

[[dialogue]]
speaker = "クロト"
# 『もしもし──』
line = "『もしもし──』"

[[dialogue]]
speaker = "フィオナ"
# 『夜分にごめんなさい、緋宮会長。フィオナです』
line = "『夜分にごめんなさい、緋宮会長。フィオナです』"

[[dialogue]]
speaker = "クロト"
# 『あ……うん。どうしたの』
line = "『あ……うん。どうしたの』"

[[dialogue]]
speaker = "フィオナ"
# 『明日の休日、少しお時間もらえませんか。来てほしい場所があります』
line = "『明日の休日、少しお時間もらえませんか。来てほしい場所があります』"

[[dialogue]]
speaker = "unk"
# 夜、かかってきた連絡というのがフィオナからのもので……
line = "夜、かかってきた連絡というのがフィオナからのもので……"

[[dialogue]]
speaker = "unk"
# 用件としては、新星星徒会のみんなを連れて彼女の実家──流星教皇庁まで来てほしいとのことだった。
line = "用件としては、新星星徒会のみんなを連れて彼女の実家──流星教皇庁まで来てほしいとのことだった。"

[[dialogue]]
speaker = "ユウリ"
# 「あたしは何度か来たことあるけどな～。ま、初めてのヤツじゃそんな反応でも無理ねーか」
line = "「あたしは何度か来たことあるけどな～。ま、初めてのヤツじゃそんな反応でも無理ねーか」"

[[dialogue]]
speaker = "ルリエル"
# 「どーしてユウリ先輩まで得意げでありますかっ！　羨ましいですけどっ！」
line = "「どーしてユウリ先輩まで得意げでありますかっ！　羨ましいですけどっ！」"

[[dialogue]]
speaker = "セーラ"
# 「あはは、うちも何度かお招きされちゃってまーす」
line = "「あはは、うちも何度かお招きされちゃってまーす」"

[[dialogue]]
speaker = "アナ"
# 「興味深い調度品が随所に見られます。こうして入れただけで貴重な経験」
line = "「興味深い調度品が随所に見られます。こうして入れただけで貴重な経験」"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# 流星教皇庁──その内部に構えられた居住スペース。
line = "流星教皇庁──その内部に構えられた居住スペース。"

[[dialogue]]
speaker = "unk"
# 俺のような庶民じゃ、本来一生入ることのない領域だった。
line = "俺のような庶民じゃ、本来一生入ることのない領域だった。"

[[dialogue]]
speaker = "unk"
# ただ……
line = "ただ……"

[[dialogue]]
speaker = "リノ"
# 『あら、そう？　でも～、女の子の声がしたわねえ。一体どんな関係なんでしょう。デートのお誘い？』
line = "『あら、そう？　でも～、女の子の声がしたわねえ。一体どんな関係なんでしょう。デートのお誘い？』"

[[dialogue]]
speaker = "フィオナ"
# 「……？　あの、やはりご迷惑だったでしょうか。お忙しいところ……」
line = "「……？　あの、やはりご迷惑だったでしょうか。お忙しいところ……」"

[[dialogue]]
speaker = "クロト"
# 「いや！　なんでもない。全然暇だったし──まさかあの教皇庁に入れるなんてと思ってさ。緊張してただけだ」
line = "「いや！　なんでもない。全然暇だったし──まさかあの教皇庁に入れるなんてと思ってさ。緊張してただけだ」"

[[dialogue]]
speaker = "unk"
# どんなに豪勢な装いでも、ここは俺にとって『同級生の女子の家』になる。
line = "どんなに豪勢な装いでも、ここは俺にとって『同級生の女子の家』になる。"

[[dialogue]]
speaker = "unk"
# そう考えると、男子ならば身がこわばってしまうのも致し方なかった。
line = "そう考えると、男子ならば身がこわばってしまうのも致し方なかった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「それで？　私たちをわざわざ招待してくれたからには、きっと用があるのよね」
line = "「それで？　私たちをわざわざ招待してくれたからには、きっと用があるのよね」"

[[dialogue]]
speaker = "フィオナ"
# 「はい。私にとって、誰よりも信頼のおける星徒会の皆さん……あなた方にだけは、改めて説明の責を果たすべきと考えました」
line = "「はい。私にとって、誰よりも信頼のおける星徒会の皆さん……あなた方にだけは、改めて説明の責を果たすべきと考えました」"

[[dialogue]]
speaker = "フィオナ"
# 「──確たる証拠をもって」
line = "「──確たる証拠をもって」"

[[dialogue]]
speaker = "マトイ"
# 「！　それって、もしかして昨日の……」
line = "「！　それって、もしかして昨日の……」"

[[dialogue]]
speaker = "フィオナ"
# 「はい。それでは、こちらへ」
line = "「はい。それでは、こちらへ」"

[[dialogue]]
speaker = "unk"
# 真剣な表情のフィオナに連れられ、俺たちは別室へと移動する。
line = "真剣な表情のフィオナに連れられ、俺たちは別室へと移動する。"

[[dialogue]]
speaker = "unk"
# そして、その先にあったのは……
line = "そして、その先にあったのは……"

[[dialogue]]
speaker = "クロト"
# 「！？」
line = "「！？」"

[[dialogue]]
speaker = "サーシャ"
# 「あら……さすがに驚きね」
line = "「あら……さすがに驚きね」"

[[dialogue]]
speaker = "unk"
# ──ベッドに横たわる、一人の少女の姿だった。
line = "──ベッドに横たわる、一人の少女の姿だった。"

[[dialogue]]
speaker = "ルリエル"
# 「こ──これは……！」
line = "「こ──これは……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「アポロ……！？」
line = "「アポロ……！？」"

[[dialogue]]
speaker = "unk"
# その顔を見て、俺たちは誰しも驚愕する。
line = "その顔を見て、俺たちは誰しも驚愕する。"

[[dialogue]]
speaker = "unk"
# アポロ──そう名乗っていた仮面の少女の素顔と、目の前にあるそれはまったく同じだった。
line = "アポロ──そう名乗っていた仮面の少女の素顔と、目の前にあるそれはまったく同じだった。"

[[dialogue]]
speaker = "フィオナ"
# 「彼女は──私の姉。本来の、星見フィオナ。５年前、眠りについたきりの<b>本人</b>です」
line = "「彼女は──私の姉。本来の、星見フィオナ。５年前、眠りについたきりの<b>本人</b>です」"

[[dialogue]]
speaker = "クロト"
# 「……なるほど、な」
line = "「……なるほど、な」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なーんとなくは昨日のうちに聞いてたけど……こうして実際に見せられると、ねえ」
line = "「なーんとなくは昨日のうちに聞いてたけど……こうして実際に見せられると、ねえ」"

[[dialogue]]
speaker = "ルリエル"
# 「わ、わたしは頭が混乱して参りました！　昨日暴れてらっしゃったのはこのお方ではなく……！？」
line = "「わ、わたしは頭が混乱して参りました！　昨日暴れてらっしゃったのはこのお方ではなく……！？」"

[[dialogue]]
speaker = "アナ"
# 「あれは彼女を象ったまがい物──と言ったところでしょうか」
line = "「あれは彼女を象ったまがい物──と言ったところでしょうか」"

[[dialogue]]
speaker = "クロト"
# 「……改めて聞こうか」
line = "「……改めて聞こうか」"

[[dialogue]]
speaker = "フィオナ"
# 「はい。私と姉は……元より、ただ仲の良い双子でした。星見の家に生まれたという背景はありましたが」
line = "「はい。私と姉は……元より、ただ仲の良い双子でした。星見の家に生まれたという背景はありましたが」"

[[dialogue]]
speaker = "フィオナ"
# 「しかし、５年前──姉は突如として覚めぬ眠りについてしまいました。それ以来、彼女はずっとここにおります」
line = "「しかし、５年前──姉は突如として覚めぬ眠りについてしまいました。それ以来、彼女はずっとここにおります」"

[[dialogue]]
speaker = "フィオナ"
# 「元々──『フィオナ』というのは星見の家の長女が襲名する名にすぎないのです」
line = "「元々──『フィオナ』というのは星見の家の長女が襲名する名にすぎないのです」"

[[dialogue]]
speaker = "フィオナ"
# 「本来それは、妹の私ではなく姉に与えられた名でした。ですが、姉の昏睡をきっかけに私が『フィオナ』へと成り代わった」
line = "「本来それは、妹の私ではなく姉に与えられた名でした。ですが、姉の昏睡をきっかけに私が『フィオナ』へと成り代わった」"

[[dialogue]]
speaker = "マトイ"
# （今のフィオナさんの本名は、エリシアさんだったかしら……？）
line = "（今のフィオナさんの本名は、エリシアさんだったかしら……？）"

[[dialogue]]
speaker = "クロト"
# （星見家の長女が空位になったとなれば大問題だ。入れ替われる妹がいたのは、教皇庁としても好都合だったんだろう）
line = "（星見家の長女が空位になったとなれば大問題だ。入れ替われる妹がいたのは、教皇庁としても好都合だったんだろう）"

[[dialogue]]
speaker = "unk"
# 聞いた事情と、先日の出来事を突き合わせてみる。
line = "聞いた事情と、先日の出来事を突き合わせてみる。"

[[dialogue]]
speaker = "unk"
# それらを妹フィオナの立場で見れば──こうなる。
line = "それらを妹フィオナの立場で見れば──こうなる。"

[[dialogue]]
speaker = "クロト"
# 「５年前から昏睡したきりだった君のお姉さんが──突如『アポロ』として俺たちの前に現れた」
line = "「５年前から昏睡したきりだった君のお姉さんが──突如『アポロ』として俺たちの前に現れた」"

[[dialogue]]
speaker = "マトイ"
# 「自称・正義のヒーロー……だけど」
line = "「自称・正義のヒーロー……だけど」"

[[dialogue]]
speaker = "アナ"
# 「実態は『リクリエの使徒』として、ですね……」
line = "「実態は『リクリエの使徒』として、ですね……」"

[[dialogue]]
speaker = "セーラ"
# 「それであんな好き勝手されてたら……そりゃーむかつくよね」
line = "「それであんな好き勝手されてたら……そりゃーむかつくよね」"

[[dialogue]]
speaker = "フィオナ"
# 「……はい。私にとって、姉は……かけがえのない家族でした。優しくて。いつも私と遊んでくれて」
line = "「……はい。私にとって、姉は……かけがえのない家族でした。優しくて。いつも私と遊んでくれて」"

[[dialogue]]
speaker = "フィオナ"
# 「あんな──人に迷惑をかけて笑っているような方では、決してありませんでした」
line = "「あんな──人に迷惑をかけて笑っているような方では、決してありませんでした」"

[[dialogue]]
speaker = "unk"
# フィオナは慈しむように、寝たきりになった少女の頬へ指を這わせた。
line = "フィオナは慈しむように、寝たきりになった少女の頬へ指を這わせた。"

[[dialogue]]
speaker = "unk"
# あの時、彼女の見せた激昂の理由も知れた。
line = "あの時、彼女の見せた激昂の理由も知れた。"

[[dialogue]]
speaker = "unk"
# 『アポロ』という存在は明らかにリクリエの生み出した産物──それが事もあろうに、姉の姿かたちを模しているというのだ。
line = "『アポロ』という存在は明らかにリクリエの生み出した産物──それが事もあろうに、姉の姿かたちを模しているというのだ。"

[[dialogue]]
speaker = "ルリエル"
# 「会長のお姉さんを利用するなんて、許せませんね……！」
line = "「会長のお姉さんを利用するなんて、許せませんね……！」"

[[dialogue]]
speaker = "ソフィア"
# 「同感です。ただ……本物のお姉さんがこちらにいるのに、あの仮面の少女が現れたというのも不可解ですね」
line = "「同感です。ただ……本物のお姉さんがこちらにいるのに、あの仮面の少女が現れたというのも不可解ですね」"

[[dialogue]]
speaker = "ユウリ"
# 「乗っ取られた……っつうわけじゃねえんだよな」
line = "「乗っ取られた……っつうわけじゃねえんだよな」"

[[dialogue]]
speaker = "フィオナ"
# 「それについてはまだ、私も整理ができていません」
line = "「それについてはまだ、私も整理ができていません」"

[[dialogue]]
speaker = "フィオナ"
# 「……戻りましょう。これ以上は姉さんの耳に入れるべきことではありません」
line = "「……戻りましょう。これ以上は姉さんの耳に入れるべきことではありません」"
