[[dialogue]]
speaker = "unk"
# 第３話,三種のメッセージ,B
line = "第３話,三種のメッセージ,B"

[[dialogue]]
speaker = "狒々の魔獣"
# 「ガ──ガウガウガ……ァッ……！」
line = "「ガ──ガウガウガ……ァッ……！」"

[[dialogue]]
speaker = "フィオナ"
# 「フゥ──こんなところですか」
line = "「フゥ──こんなところですか」"

[[dialogue]]
speaker = "ソフィア"
# 「ばっちりです。ユウリ先輩も、助かりました」
line = "「ばっちりです。ユウリ先輩も、助かりました」"

[[dialogue]]
speaker = "ユウリ"
# 「ああ。なんつーか、動物をいじめてるみたいで気が悪いけどな」
line = "「ああ。なんつーか、動物をいじめてるみたいで気が悪いけどな」"

[[dialogue]]
speaker = "サーシャ"
# 「油断は禁物よ～。人気のないところに出かけたら、魔獣に襲われて骨だけになっちゃいました～、なんてこと珍しくないんだから」
line = "「油断は禁物よ～。人気のないところに出かけたら、魔獣に襲われて骨だけになっちゃいました～、なんてこと珍しくないんだから」"

[[dialogue]]
speaker = "マトイ"
# 「お、恐ろしい場所なんですね……」
line = "「お、恐ろしい場所なんですね……」"

[[dialogue]]
speaker = "ソフィア"
# 「都市部に行けば安全ではありますが」
line = "「都市部に行けば安全ではありますが」"

[[dialogue]]
speaker = "ユウリ"
# 「もうちょっと栄えた町とかに下ろしてくれてもよかったのによ」
line = "「もうちょっと栄えた町とかに下ろしてくれてもよかったのによ」"

[[dialogue]]
speaker = "クロト"
# 「これでも彼女たちなりに、考えてくれたんだとは思うけど……」
line = "「これでも彼女たちなりに、考えてくれたんだとは思うけど……」"

[[dialogue]]
speaker = "unk"
# 俺は魔界の地理に明るくないが、この地方を指定したのは他ならぬサーシャ先輩だ。
line = "俺は魔界の地理に明るくないが、この地方を指定したのは他ならぬサーシャ先輩だ。"

[[dialogue]]
speaker = "アイリーン"
# 『魔界に配置されている『うろ』の<ruby=フォワード>転送</ruby>ポイントは多くありません。なるべくご希望には沿うように致しますが、人里から離れていることは覚悟してください』
line = "『魔界に配置されている『うろ』の<ruby>転送<rt>フォワード</rt></ruby>ポイントは多くありません。なるべくご希望には沿うように致しますが、人里から離れていることは覚悟してください』"

[[dialogue]]
speaker = "サーシャ"
# 『それじゃあ、ズヴィエダ地方でお願いできるかしら？』
line = "『それじゃあ、ズヴィエダ地方でお願いできるかしら？』"

[[dialogue]]
speaker = "アイリーン"
# 『了解です。魔獣の脅威度もそれなりと記録されていますが、大丈夫ですか？』
line = "『了解です。魔獣の脅威度もそれなりと記録されていますが、大丈夫ですか？』"

[[dialogue]]
speaker = "サーシャ"
# 『ええ。あそこなら、最低限の土地勘はあるから』
line = "『ええ。あそこなら、最低限の土地勘はあるから』"

[[dialogue]]
speaker = "unk"
# 俺に魔界の土地勘はないが、ここが<ruby=へんぴ>辺鄙</ruby>な場所だというのはわかる。
line = "俺に魔界の土地勘はないが、ここが<ruby>辺鄙<rt>へんぴ</rt></ruby>な場所だというのはわかる。"

[[dialogue]]
speaker = "unk"
# 恐らく魔女たちからしても、そう大っぴらな場所に出口を繋げることはしにくいのだろう。
line = "恐らく魔女たちからしても、そう大っぴらな場所に出口を繋げることはしにくいのだろう。"

[[dialogue]]
speaker = "unk"
# どう動くべきか──と、思案していたところ。
line = "どう動くべきか──と、思案していたところ。"

[[dialogue]]
speaker = "フィオナ"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "クロト"
# 「ＤＩＳＣの着信──それもみんなに？」
line = "「ＤＩＳＣの着信──それもみんなに？」"

[[dialogue]]
speaker = "マトイ"
# 「も──もしかして……！」
line = "「も──もしかして……！」"

[[dialogue]]
speaker = "unk"
# 誰もが淡い期待を抱きながらＤＩＳＣを開く。
line = "誰もが淡い期待を抱きながらＤＩＳＣを開く。"

[[dialogue]]
speaker = "unk"
# そこに表示されていたのは──まさしく期待通りの人物の名だった。
line = "そこに表示されていたのは──まさしく期待通りの人物の名だった。"

[[dialogue]]
speaker = "ユウリ"
# 「おいおい──マジでヴィーナスからの連絡かよ！」
line = "「おいおい──マジでヴィーナスからの連絡かよ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ──ですが、これは……」
line = "「ええ──ですが、これは……」"

[[dialogue]]
speaker = "クロト"
# 「メッセージ──それも意味深な……ですね」
line = "「メッセージ──それも意味深な……ですね」"

[[dialogue]]
speaker = "unk"
# 『来て』
line = "『来て』"

[[dialogue]]
speaker = "unk"
# 『森』
line = "『森』"

[[dialogue]]
speaker = "unk"
# 『冬』
line = "『冬』"

[[dialogue]]
speaker = "unk"
# 計３通──それぞれが両星徒会全メンバーに送られている。
line = "計３通──それぞれが両星徒会全メンバーに送られている。"

[[dialogue]]
speaker = "フィオナ"
# 「来て、森、冬──いえ。送信された順番は逆ですから……冬、森、来て、となるでしょうか」
line = "「来て、森、冬──いえ。送信された順番は逆ですから……冬、森、来て、となるでしょうか」"

[[dialogue]]
speaker = "マトイ"
# 「……？？？　さっぱり意味がわからないけど……」
line = "「……？？？　さっぱり意味がわからないけど……」"

[[dialogue]]
speaker = "サーシャ"
# 「それでも──ヴィーナスちゃんからの貴重な連絡に変わりないわね」
line = "「それでも──ヴィーナスちゃんからの貴重な連絡に変わりないわね」"

[[dialogue]]
speaker = "クロト"
# 「ええ。送信されたのは数時間前のようです。ただ、それが……今になって届いた」
line = "「ええ。送信されたのは数時間前のようです。ただ、それが……今になって届いた」"

[[dialogue]]
speaker = "フィオナ"
# 「……なるほど。私たちが魔界に来たことで、受信可能となったのですね」
line = "「……なるほど。私たちが魔界に来たことで、受信可能となったのですね」"

[[dialogue]]
speaker = "ユウリ"
# 「──ってことはやっぱり、ヴィーナスは魔界にいるんだな……！」
line = "「──ってことはやっぱり、ヴィーナスは魔界にいるんだな……！」"

[[dialogue]]
speaker = "unk"
# アニマ先輩の助力もあって推測した俺たちだったが──ここへきていよいよ確定となった。
line = "アニマ先輩の助力もあって推測した俺たちだったが──ここへきていよいよ確定となった。"

[[dialogue]]
speaker = "クロト"
# （……よかった。ヴィーナスは少なくともまだ生きていて──同じ大地を踏んでいる）
line = "（……よかった。ヴィーナスは少なくともまだ生きていて──同じ大地を踏んでいる）"

[[dialogue]]
speaker = "unk"
# 安堵するとともに、底知れない闘志も湧き上がってきた。
line = "安堵するとともに、底知れない闘志も湧き上がってきた。"

[[dialogue]]
speaker = "クロト"
# 「よし。俺たちも魔界に着いたことを伝えよう。できればこの場所のことも」
line = "「よし。俺たちも魔界に着いたことを伝えよう。できればこの場所のことも」"

[[dialogue]]
speaker = "マトイ"
# 「だねっ。もしかしたら、案外近くにいるかもしれないし──」
line = "「だねっ。もしかしたら、案外近くにいるかもしれないし──」"

[[dialogue]]
speaker = "フィオナ"
# 「──いえ。少々お待ち下さい、緋宮会長」
line = "「──いえ。少々お待ち下さい、緋宮会長」"

[[dialogue]]
speaker = "クロト"
# 「ん？」
line = "「ん？」"

[[dialogue]]
speaker = "フィオナ"
# 「その連絡に対して返信するのは、いささか危険を孕むのではないでしょうか」
line = "「その連絡に対して返信するのは、いささか危険を孕むのではないでしょうか」"

[[dialogue]]
speaker = "ユウリ"
# 「おいおい、どういうことだよフィオナ。せっかくヴィーナスと繋がったってのに」
line = "「おいおい、どういうことだよフィオナ。せっかくヴィーナスと繋がったってのに」"

[[dialogue]]
speaker = "クロト"
# 「……あ、そうか」
line = "「……あ、そうか」"

[[dialogue]]
speaker = "クロト"
# 「このメッセージ自体が罠である可能性──か」
line = "「このメッセージ自体が罠である可能性──か」"

[[dialogue]]
speaker = "ソフィア"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "フィオナ"
# 「はい。そうでなくとも、随分と怪しい文面ですから」
line = "「はい。そうでなくとも、随分と怪しい文面ですから」"

[[dialogue]]
speaker = "マトイ"
# 「でも……そんなまどろっこしいことするかな？　あの凶暴な黒騎士──さんが」
line = "「でも……そんなまどろっこしいことするかな？　あの凶暴な黒騎士──さんが」"

[[dialogue]]
speaker = "クロト"
# 「あくまでも可能性の話だ。実際、俺も十中八九、この連絡はヴィーナス本人からのものだと思う」
line = "「あくまでも可能性の話だ。実際、俺も十中八九、この連絡はヴィーナス本人からのものだと思う」"

[[dialogue]]
speaker = "クロト"
# 「だけど──そうだとしても、返信することにはリスクがある。フィオナが言ってるのはそういうことだ」
line = "「だけど──そうだとしても、返信することにはリスクがある。フィオナが言ってるのはそういうことだ」"

[[dialogue]]
speaker = "フィオナ"
# 「その通りです。もし、ヴィーナスさんが自由に連絡を取れる状態であるなら──わざわざこんな意味深な内容にする必要はありません」
line = "「その通りです。もし、ヴィーナスさんが自由に連絡を取れる状態であるなら──わざわざこんな意味深な内容にする必要はありません」"

[[dialogue]]
speaker = "unk"
# この『冬』『森』『来て』という短文の羅列は内容的にもヴィーナスらしくない。
line = "この『冬』『森』『来て』という短文の羅列は内容的にもヴィーナスらしくない。"

[[dialogue]]
speaker = "unk"
# 切羽詰まった状況のなか、どうにかこの３つのメッセージだけを託してくれた……と見るのが自然だろう。
line = "切羽詰まった状況のなか、どうにかこの３つのメッセージだけを託してくれた……と見るのが自然だろう。"

[[dialogue]]
speaker = "サーシャ"
# 「……どうする？　会長くん」
line = "「……どうする？　会長くん」"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは今もどこかで耐え忍んでいる。
line = "ヴィーナスは今もどこかで耐え忍んでいる。"

[[dialogue]]
speaker = "unk"
# ならばなおさら、一刻も早く駆けつけてやりたい。が……
line = "ならばなおさら、一刻も早く駆けつけてやりたい。が……"

[[dialogue]]
speaker = "クロト"
# 「……やめよう。これに返信するのはまだ、危険だ」
line = "「……やめよう。これに返信するのはまだ、危険だ」"

[[dialogue]]
speaker = "unk"
# こちらから有益な情報を送れるならともかく──『着いたよ』程度じゃ、リスクになる恐れのほうが高い。
line = "こちらから有益な情報を送れるならともかく──『着いたよ』程度じゃ、リスクになる恐れのほうが高い。"

[[dialogue]]
speaker = "ユウリ"
# 「ま、こっちからの着信のせいで<ruby=アイツ>黒騎士</ruby>に気づかれる──とかなっても寒いしな」
line = "「ま、こっちからの着信のせいで<ruby>黒騎士<rt>アイツ</rt></ruby>に気づかれる──とかなっても寒いしな」"

[[dialogue]]
speaker = "マトイ"
# 「うん。それに、ヴィーナスからメッセージが来たってだけでも、すっごい進歩だよ！」
line = "「うん。それに、ヴィーナスからメッセージが来たってだけでも、すっごい進歩だよ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ。これは私たちに託された情報……必ずその真意を突き止めましょう」
line = "「ええ。これは私たちに託された情報……必ずその真意を突き止めましょう」"

[[dialogue]]
speaker = "クロト"
# 「ああ。それにはもっと情報が必要だ」
line = "「ああ。それにはもっと情報が必要だ」"

[[dialogue]]
speaker = "クロト"
# 「この広大な魔界から、どこにヴィーナスがいるのか突き止めるなら──」
line = "「この広大な魔界から、どこにヴィーナスがいるのか突き止めるなら──」"

[[dialogue]]
speaker = "ユウリ"
# 「そういや……ソフィア。さっき魔獣が出る前、寒いのは好都合とか言ってなかったか？」
line = "「そういや……ソフィア。さっき魔獣が出る前、寒いのは好都合とか言ってなかったか？」"

[[dialogue]]
speaker = "ソフィア"
# 「そうでした。ちょうどこの寒冷な気候が──よい傾向かもということです」
line = "「そうでした。ちょうどこの寒冷な気候が──よい傾向かもということです」"

[[dialogue]]
speaker = "フィオナ"
# 「というと、もしかして……」
line = "「というと、もしかして……」"

[[dialogue]]
speaker = "サーシャ"
# 「ええ。魔女さん達にお願いした甲斐があったみたいね」
line = "「ええ。魔女さん達にお願いした甲斐があったみたいね」"

[[dialogue]]
speaker = "サーシャ"
# 「この風景に見覚えはないけれど──懐かしい風を感じるわ。ここからなら、私たちの街も近いはず」
line = "「この風景に見覚えはないけれど──懐かしい風を感じるわ。ここからなら、私たちの街も近いはず」"

[[dialogue]]
speaker = "マトイ"
# 「そういえば──サーシャさんの地元は超寒かったって、前に聞いたような……」
line = "「そういえば──サーシャさんの地元は超寒かったって、前に聞いたような……」"

[[dialogue]]
speaker = "unk"
# ソフィアちゃんのいう『好都合』──それはつまり。
line = "ソフィアちゃんのいう『好都合』──それはつまり。"

[[dialogue]]
speaker = "ソフィア"
# 「ここからなら私たちの故郷──レゾフが近いと思われます。情報を集めるなら、まずはそちらへ向かうべきでしょう」
line = "「ここからなら私たちの故郷──レゾフが近いと思われます。情報を集めるなら、まずはそちらへ向かうべきでしょう」"

[[dialogue]]
speaker = "マトイ"
# 「わあ……！　サーシャさんの故郷……！」
line = "「わあ……！　サーシャさんの故郷……！」"

[[dialogue]]
speaker = "ユウリ"
# 「近いってどんくらいだ？　バスでも捕まんのか？」
line = "「近いってどんくらいだ？　バスでも捕まんのか？」"

[[dialogue]]
speaker = "ソフィア"
# 「人間界で言うと、<ruby=しゅうざかい>州境</ruby>を２つまたぐくらいでしょうか」
line = "「人間界で言うと、<ruby>州境<rt>しゅうざかい</rt></ruby>を２つまたぐくらいでしょうか」"

[[dialogue]]
speaker = "ユウリ"
# 「どこが近いんだよ……」
line = "「どこが近いんだよ……」"

[[dialogue]]
speaker = "クロト"
# 「それでも──情報収集ができそうな、栄えた街があるってことですよね？」
line = "「それでも──情報収集ができそうな、栄えた街があるってことですよね？」"

[[dialogue]]
speaker = "サーシャ"
# 「ええ。レゾフなら私とソフィアが案内できるし……間違いなくヴィーナスちゃん探しの近道になるはずよ」
line = "「ええ。レゾフなら私とソフィアが案内できるし……間違いなくヴィーナスちゃん探しの近道になるはずよ」"

[[dialogue]]
speaker = "フィオナ"
# 「魔界で行動するにおいて──魔族の方の協力を仰げるなら、それに越したことはありませんね」
line = "「魔界で行動するにおいて──魔族の方の協力を仰げるなら、それに越したことはありませんね」"

[[dialogue]]
speaker = "ユウリ"
# 「決まりだ。目的地はソフィアの実家な！」
line = "「決まりだ。目的地はソフィアの実家な！」"

[[dialogue]]
speaker = "ソフィア"
# （どんな顔して帰ればいいかはわかりませんが……）
line = "（どんな顔して帰ればいいかはわかりませんが……）"

[[dialogue]]
speaker = "クロト"
# 「わかった。そうと決まれば急ごう──ここにいたら、またいつ魔獣に襲われるとも限らない」
line = "「わかった。そうと決まれば急ごう──ここにいたら、またいつ魔獣に襲われるとも限らない」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふ、みんなついてきて♪」
line = "「ふふ、みんなついてきて♪」"

[[dialogue]]
speaker = "unk"
# そうして俺たちは、魔界の都市──レゾフを目指すこととなった。
line = "そうして俺たちは、魔界の都市──レゾフを目指すこととなった。"
