[[dialogue]]
speaker = "unk"
# 第１１話,魔女たちの誇り,B
line = "第１１話,魔女たちの誇り,B"

[[dialogue]]
speaker = "セドナ"
# 「我々が危惧しているのは今代のリクリエの特殊性だ。過去の記録には一切見られなかったものが、今回にはある」
line = "「我々が危惧しているのは今代のリクリエの特殊性だ。過去の記録には一切見られなかったものが、今回にはある」"

[[dialogue]]
speaker = "ヴィーナス"
# 「過去になかったもの……？　って？」
line = "「過去になかったもの……？　って？」"

[[dialogue]]
speaker = "セドナ"
# 「あの、仮面の少女だ」
line = "「あの、仮面の少女だ」"

[[dialogue]]
speaker = "フィオナ"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "セドナ"
# 「リクリエは本来ただの自然現象だ。意志を持つ使徒が現れるなど前例がない」
line = "「リクリエは本来ただの自然現象だ。意志を持つ使徒が現れるなど前例がない」"

[[dialogue]]
speaker = "クロト"
# 「前例……ですか」
line = "「前例……ですか」"

[[dialogue]]
speaker = "セドナ"
# 「ああ。魔女の森にはこう伝えられている──リクリエとは、終焉をもたらす天災であるとな」
line = "「ああ。魔女の森にはこう伝えられている──リクリエとは、終焉をもたらす天災であるとな」"

[[dialogue]]
speaker = "unk"
# 確かに、フィーニスの塔で見て回った壁画の中には……
line = "確かに、フィーニスの塔で見て回った壁画の中には……"

[[dialogue]]
speaker = "unk"
# 戦争や破滅の竜なんかの描写こそあれ、使徒なる存在は描かれていなかった。
line = "戦争や破滅の竜なんかの描写こそあれ、使徒なる存在は描かれていなかった。"

[[dialogue]]
speaker = "セドナ"
# 「『モンスター』というのもそうだ。あれは本来、三界のどこにも生息していないはずの存在──<b>今回の</b>リクリエが生み出したバグのようなもの」
line = "「『モンスター』というのもそうだ。あれは本来、三界のどこにも生息していないはずの存在──<b>今回の</b>リクリエが生み出したバグのようなもの」"

[[dialogue]]
speaker = "セドナ"
# 「それを、あの仮面の少女が操っていたというのだから──おおよその因果は繋がっていよう」
line = "「それを、あの仮面の少女が操っていたというのだから──おおよその因果は繋がっていよう」"

[[dialogue]]
speaker = "アナ"
# 「モンスターも……イレギュラーな存在というのですか」
line = "「モンスターも……イレギュラーな存在というのですか」"

[[dialogue]]
speaker = "アイリーン"
# 「加えて言えば、魔王を敵視するような言動も意味深です。なにせ魔王が英雄というのは<b>前回</b>の結果ですから」
line = "「加えて言えば、魔王を敵視するような言動も意味深です。なにせ魔王が英雄というのは<b>前回</b>の結果ですから」"

[[dialogue]]
speaker = "unk"
# 彼女たちはアポロを前もって警戒していた。
line = "彼女たちはアポロを前もって警戒していた。"

[[dialogue]]
speaker = "unk"
# 数万年の歴史を持つ魔女をして、由縁のわからない存在であると。
line = "数万年の歴史を持つ魔女をして、由縁のわからない存在であると。"

[[dialogue]]
speaker = "セドナ"
# 「我々はあの少女が<b>どこから来て</b>、<b>どこへ行くのか</b>に着目している。すると期せずして今日、ヒントになりそうな言葉を得た」
line = "「我々はあの少女が<b>どこから来て</b>、<b>どこへ行くのか</b>に着目している。すると期せずして今日、ヒントになりそうな言葉を得た」"

[[dialogue]]
speaker = "unk"
# そしてセドナさんは、ニヤリと笑ってフィオナを見た。
line = "そしてセドナさんは、ニヤリと笑ってフィオナを見た。"

[[dialogue]]
speaker = "セドナ"
# 「あれは──はて、何だったかな？　星見の少女」
line = "「あれは──はて、何だったかな？　星見の少女」"

[[dialogue]]
speaker = "フィオナ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "ユウリ"
# 「フィオナ……」
line = "「フィオナ……」"

[[dialogue]]
speaker = "unk"
# セドナさんに問い詰められ、フィオナはわずかに逡巡した。
line = "セドナさんに問い詰められ、フィオナはわずかに逡巡した。"

[[dialogue]]
speaker = "unk"
# 彼女の出自と本名──
line = "彼女の出自と本名──"

[[dialogue]]
speaker = "unk"
# それからアポロが本物の『星見フィオナ』を模していることを、俺たちは彼女から直接聞いて知っている。
line = "それからアポロが本物の『星見フィオナ』を模していることを、俺たちは彼女から直接聞いて知っている。"

[[dialogue]]
speaker = "unk"
# ネビュラの方々も彼女が『姉さん』と呼んだのを見ていたのだろう。
line = "ネビュラの方々も彼女が『姉さん』と呼んだのを見ていたのだろう。"

[[dialogue]]
speaker = "unk"
# そのことを聞き出そうとしているのだ。
line = "そのことを聞き出そうとしているのだ。"

[[dialogue]]
speaker = "セドナ"
# 「どうした。あれの見てくれについて覚えはないか？」
line = "「どうした。あれの見てくれについて覚えはないか？」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ、そうですね──」
line = "「ええ、そうですね──」"

[[dialogue]]
speaker = "unk"
# フィオナもまた迷っている。
line = "フィオナもまた迷っている。"

[[dialogue]]
speaker = "unk"
# 助けてもらった恩義と、これまでずっと隠してきた秘密とのどちらを取るかで。
line = "助けてもらった恩義と、これまでずっと隠してきた秘密とのどちらを取るかで。"

[[dialogue]]
speaker = "クロト"
# （──）
line = "（──）"

[[dialogue]]
speaker = "フィオナ"
# （……！　緋宮会長……）
line = "（……！　緋宮会長……）"

[[dialogue]]
speaker = "unk"
# その折──俺は彼女に目配せした。
line = "その折──俺は彼女に目配せした。"

[[dialogue]]
speaker = "クロト"
# （まだ明かすべきじゃない。この人たちが信を置ける存在かどうか判断できるまでは）
line = "（まだ明かすべきじゃない。この人たちが信を置ける存在かどうか判断できるまでは）"

[[dialogue]]
speaker = "フィオナ"
# （……わかりました）
line = "（……わかりました）"

[[dialogue]]
speaker = "フィオナ"
# 「あいにくですが……私たちがあの少女と交戦したのは、今回が初めてで。新星さんは二度目だったようなのですが」
line = "「あいにくですが……私たちがあの少女と交戦したのは、今回が初めてで。新星さんは二度目だったようなのですが」"

[[dialogue]]
speaker = "フィオナ"
# 「『仮面の少女』に関しては──手がかりになるようなことは知りません」
line = "「『仮面の少女』に関しては──手がかりになるようなことは知りません」"

[[dialogue]]
speaker = "セドナ"
# 「……何もわからない、と？」
line = "「……何もわからない、と？」"

[[dialogue]]
speaker = "フィオナ"
# 「はい」
line = "「はい」"

[[dialogue]]
speaker = "アイリーン"
# 「そんな……！」
line = "「そんな……！」"

[[dialogue]]
speaker = "セドナ"
# 「ふーむ。君が姉さんと口走っていたのは──我々の聞き間違いだったとでも？」
line = "「ふーむ。君が姉さんと口走っていたのは──我々の聞き間違いだったとでも？」"

[[dialogue]]
speaker = "フィオナ"
# 「後ろ姿が少々似ていたので……それに、私の姉ならあんなに小さくありません」
line = "「後ろ姿が少々似ていたので……それに、私の姉ならあんなに小さくありません」"

[[dialogue]]
speaker = "アイリーン"
# 「フィオナさん。あなたには先ほどまで、使い魔がついていたとお見受けしますが……あれは？」
line = "「フィオナさん。あなたには先ほどまで、使い魔がついていたとお見受けしますが……あれは？」"

[[dialogue]]
speaker = "フィオナ"
# 「彼には休んでいてもらっています。長時間の戦闘を終えたばかりなので」
line = "「彼には休んでいてもらっています。長時間の戦闘を終えたばかりなので」"

[[dialogue]]
speaker = "ソフィア"
# （そういえば）
line = "（そういえば）"

[[dialogue]]
speaker = "マトイ"
# （静かだと思った）
line = "（静かだと思った）"

[[dialogue]]
speaker = "unk"
# この基地に入る直前からニャリオンの姿はなかった。
line = "この基地に入る直前からニャリオンの姿はなかった。"

[[dialogue]]
speaker = "unk"
# どんな時でも一緒にいるのが彼女たちだったが……フィオナの警戒心のあらわれなのだろうか。
line = "どんな時でも一緒にいるのが彼女たちだったが……フィオナの警戒心のあらわれなのだろうか。"

[[dialogue]]
speaker = "フィオナ"
# 「ごめんなさい。ですが、私たちもまだ混乱しているのです」
line = "「ごめんなさい。ですが、私たちもまだ混乱しているのです」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふ、そうね。あんなのは私たちも初めて見たわ」
line = "「ふふ、そうね。あんなのは私たちも初めて見たわ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「確かに！　あのでっかい手は、前回戦った時も出てこなかったわ！」
line = "「確かに！　あのでっかい手は、前回戦った時も出てこなかったわ！」"

[[dialogue]]
speaker = "ルリエル"
# 「手だけであんなに大っきいってことは……ほ、本体はどんな大きさなんでしょう。ひええ」
line = "「手だけであんなに大っきいってことは……ほ、本体はどんな大きさなんでしょう。ひええ」"

[[dialogue]]
speaker = "アナ"
# 「本体が潜んでてもおかしくない……確かにいい着眼点」
line = "「本体が潜んでてもおかしくない……確かにいい着眼点」"

[[dialogue]]
speaker = "unk"
# サーシャさんの助け舟でやや話題がアポロから逸れる。
line = "サーシャさんの助け舟でやや話題がアポロから逸れる。"

[[dialogue]]
speaker = "unk"
# あの『手』に関しては、俺も思うところがあるものの……
line = "あの『手』に関しては、俺も思うところがあるものの……"

[[dialogue]]
speaker = "セーラ"
# 「ま、それにほら。原則うちらって他の組織にペラペラ喋っていいわけじゃないしね」
line = "「ま、それにほら。原則うちらって他の組織にペラペラ喋っていいわけじゃないしね」"

[[dialogue]]
speaker = "ルリエル"
# 「そうだったのですか？」
line = "「そうだったのですか？」"

[[dialogue]]
speaker = "アナ"
# 「情報統制。当然」
line = "「情報統制。当然」"

[[dialogue]]
speaker = "unk"
# 実際それもある。
line = "実際それもある。"

[[dialogue]]
speaker = "unk"
# この『ネビュラ』という組織──確かに俺たちも知らない超大な力を持っているが、だからといって任務で得た情報をすぐに共有はできない。
line = "この『ネビュラ』という組織──確かに俺たちも知らない超大な力を持っているが、だからといって任務で得た情報をすぐに共有はできない。"

[[dialogue]]
speaker = "アイリーン"
# 「つまり結局……何も喋れない、と？」
line = "「つまり結局……何も喋れない、と？」"

[[dialogue]]
speaker = "フィオナ"
# 「あくまで、今は──ですが」
line = "「あくまで、今は──ですが」"

[[dialogue]]
speaker = "unk"
# 本当に彼女らが信頼できる仲間であれ、どうであれ。
line = "本当に彼女らが信頼できる仲間であれ、どうであれ。"

[[dialogue]]
speaker = "unk"
# 強引にねぐらへ連れ込まれた今の状況で身の上を開示するのは──避けるのが懸命と言えた。
line = "強引にねぐらへ連れ込まれた今の状況で身の上を開示するのは──避けるのが懸命と言えた。"

[[dialogue]]
speaker = "アイリーン"
# 「ふう……困りましたね。我々は敵ではないと、わかってもらえたと思うのですが」
line = "「ふう……困りましたね。我々は敵ではないと、わかってもらえたと思うのですが」"

[[dialogue]]
speaker = "セドナ"
# 「そうとも。同志と言ったろう、この世界を救いたいという気持ちは君たちと同じだ」
line = "「そうとも。同志と言ったろう、この世界を救いたいという気持ちは君たちと同じだ」"

[[dialogue]]
speaker = "ルリエル"
# 「おおっ、素晴らしい理念です！」
line = "「おおっ、素晴らしい理念です！」"

[[dialogue]]
speaker = "unk"
# 確かにその一点は俺たちと同じだ。
line = "確かにその一点は俺たちと同じだ。"

[[dialogue]]
speaker = "unk"
# だが、これまでの発言を踏まえるに総体としてのスタンスは矛盾している。
line = "だが、これまでの発言を踏まえるに総体としてのスタンスは矛盾している。"

[[dialogue]]
speaker = "unk"
# 彼女たちはまだ何かを隠している──何もかもを明かすのは、早計だ。
line = "彼女たちはまだ何かを隠している──何もかもを明かすのは、早計だ。"

[[dialogue]]
speaker = "セドナ"
# 「ならば、魔王。君はどうだ？　共に力を合わせようとは思わんか？」
line = "「ならば、魔王。君はどうだ？　共に力を合わせようとは思わんか？」"

[[dialogue]]
speaker = "クロト"
# 「思います。ですが……」
line = "「思います。ですが……」"

[[dialogue]]
speaker = "unk"
# 平然と俺のことを魔王呼ばわりしてくる──
line = "平然と俺のことを魔王呼ばわりしてくる──"

[[dialogue]]
speaker = "unk"
# あの壁画の真実も、もしや承知の上なのかもしれない。
line = "あの壁画の真実も、もしや承知の上なのかもしれない。"

[[dialogue]]
speaker = "unk"
# 俺はあくまでも知らない体を装って話を進めた。
line = "俺はあくまでも知らない体を装って話を進めた。"

[[dialogue]]
speaker = "クロト"
# 「……ひとつお訊ねします」
line = "「……ひとつお訊ねします」"

[[dialogue]]
speaker = "セドナ"
# 「いいだろう」
line = "「いいだろう」"

[[dialogue]]
speaker = "クロト"
# 「先ほど──あなた達『ネビュラ』は俺たちの活動を観測していた、と仰っしゃりましたね」
line = "「先ほど──あなた達『ネビュラ』は俺たちの活動を観測していた、と仰っしゃりましたね」"

[[dialogue]]
speaker = "アイリーン"
# 「はい」
line = "「はい」"

[[dialogue]]
speaker = "unk"
# こくり、とアイリーンさんが頷いた。
line = "こくり、とアイリーンさんが頷いた。"

[[dialogue]]
speaker = "アイリーン"
# 「あなた達、星騎士──とりわけ両学園星徒会の活動については、過去の全出動を観測しています」
line = "「あなた達、星騎士──とりわけ両学園星徒会の活動については、過去の全出動を観測しています」"

[[dialogue]]
speaker = "アイリーン"
# 「ああもちろん、ただ見ていたわけではありませんよ。あなた方のデータから次なる『計画』を練っていたのです」
line = "「ああもちろん、ただ見ていたわけではありませんよ。あなた方のデータから次なる『計画』を練っていたのです」"

[[dialogue]]
speaker = "アイリーン"
# 「もちろん、世界存続のための！　ですよ」
line = "「もちろん、世界存続のための！　ですよ」"

[[dialogue]]
speaker = "マトイ"
# 「すごい……学園以外にも、そんな組織がいたなんて……」
line = "「すごい……学園以外にも、そんな組織がいたなんて……」"

[[dialogue]]
speaker = "ソフィア"
# 「どこからどう観測しているのかは気になりますけど」
line = "「どこからどう観測しているのかは気になりますけど」"

[[dialogue]]
speaker = "unk"
# アイリーンさん達が嘘をついているようには見えない。
line = "アイリーンさん達が嘘をついているようには見えない。"

[[dialogue]]
speaker = "unk"
# だから、信じたい気持ちも山々なのだけど……確かめなくてはならないことがあった。
line = "だから、信じたい気持ちも山々なのだけど……確かめなくてはならないことがあった。"

[[dialogue]]
speaker = "クロト"
# 「ならお分かりかと思いますが、これまで俺たちの活動は全てがうまくやれていたわけではありません」
line = "「ならお分かりかと思いますが、これまで俺たちの活動は全てがうまくやれていたわけではありません」"

[[dialogue]]
speaker = "クロト"
# 「前回のアポロ出現時には、多くの犠牲も出しました。不甲斐ないところですが」
line = "「前回のアポロ出現時には、多くの犠牲も出しました。不甲斐ないところですが」"

[[dialogue]]
speaker = "アイリーン"
# 「そのようですね。あれほどの相手にしては、少ない被害に抑えたとも言えそうですが」
line = "「そのようですね。あれほどの相手にしては、少ない被害に抑えたとも言えそうですが」"

[[dialogue]]
speaker = "unk"
# アステラ、モンスター、流星の嵐……
line = "アステラ、モンスター、流星の嵐……"

[[dialogue]]
speaker = "unk"
# 数々の苦難に見舞われて、ピンチに陥ったのも一度や二度じゃない。
line = "数々の苦難に見舞われて、ピンチに陥ったのも一度や二度じゃない。"

[[dialogue]]
speaker = "unk"
# それを彼女たちが知っているというのなら、疑問がある。
line = "それを彼女たちが知っているというのなら、疑問がある。"

[[dialogue]]
speaker = "クロト"
# 「なぜ、今回に限って俺たちを助けてくれたんですか？」
line = "「なぜ、今回に限って俺たちを助けてくれたんですか？」"

[[dialogue]]
speaker = "アイリーン"
# 「それは……」
line = "「それは……」"

[[dialogue]]
speaker = "unk"
# 単純な問いかけだった。
line = "単純な問いかけだった。"

[[dialogue]]
speaker = "unk"
# セドナさんも、当然とばかりに答える。
line = "セドナさんも、当然とばかりに答える。"

[[dialogue]]
speaker = "セドナ"
# 「決まっている。君たちは使える。失うには早いと判断しただけのこと」
line = "「決まっている。君たちは使える。失うには早いと判断しただけのこと」"

[[dialogue]]
speaker = "unk"
# 今回ばかりは手助けせざるを得ないピンチだったというセドナさん。
line = "今回ばかりは手助けせざるを得ないピンチだったというセドナさん。"

[[dialogue]]
speaker = "unk"
# そして事実、俺たちは命を救われたわけだ。
line = "そして事実、俺たちは命を救われたわけだ。"

[[dialogue]]
speaker = "クロト"
# 「その評価は光栄なこと──ですが」
line = "「その評価は光栄なこと──ですが」"

[[dialogue]]
speaker = "セーラ"
# 「星騎士じゃないフツーの人たちのことは、どうでもいいってコトなのかな？」
line = "「星騎士じゃないフツーの人たちのことは、どうでもいいってコトなのかな？」"

[[dialogue]]
speaker = "unk"
# セーラさんが俺の訊きたいことを汲んでくれた。
line = "セーラさんが俺の訊きたいことを汲んでくれた。"

[[dialogue]]
speaker = "unk"
# まごつくアイリーンさんに対して、セドナさんの態度は変わらない。
line = "まごつくアイリーンさんに対して、セドナさんの態度は変わらない。"

[[dialogue]]
speaker = "セドナ"
# 「経緯はどうあれ、リクリエの時期に人が死ぬのは避けられんことだ。どうでもいいとは言わんが、優先度が低い」
line = "「経緯はどうあれ、リクリエの時期に人が死ぬのは避けられんことだ。どうでもいいとは言わんが、優先度が低い」"

[[dialogue]]
speaker = "セドナ"
# 「自然現象と言っただろう？　越冬のようなものだ──そして残念ながら、やり過ごせる穴ぐらは三界のどこにもない」
line = "「自然現象と言っただろう？　越冬のようなものだ──そして残念ながら、やり過ごせる穴ぐらは三界のどこにもない」"

[[dialogue]]
speaker = "マトイ"
# 「そ、そんなっ……！　皆さんのお力があれば、もっと多くの人が助けられるはずです！」
line = "「そ、そんなっ……！　皆さんのお力があれば、もっと多くの人が助けられるはずです！」"

[[dialogue]]
speaker = "アイリーン"
# 「お気持ちはわかりますが、それはあなた方のなすべき責務です」
line = "「お気持ちはわかりますが、それはあなた方のなすべき責務です」"

[[dialogue]]
speaker = "アイリーン"
# 「我々はあくまでも裏方──表の秩序を守るのは、<ruby=スターナイト>星騎士</ruby>の領分でしょう」
line = "「我々はあくまでも裏方──表の秩序を守るのは、<ruby>星騎士<rt>スターナイト</rt></ruby>の領分でしょう」"

[[dialogue]]
speaker = "マトイ"
# 「だ……だからって、見殺しにするなんて……」
line = "「だ……だからって、見殺しにするなんて……」"

[[dialogue]]
speaker = "ルリエル"
# 「そうですよう！　あんなに強い力があるなら、アステラの排除だってできると思います！」
line = "「そうですよう！　あんなに強い力があるなら、アステラの排除だってできると思います！」"

[[dialogue]]
speaker = "セドナ"
# 「キリのない掃除に付き合わされるなど、御免だ。根本的な解決にならん」
line = "「キリのない掃除に付き合わされるなど、御免だ。根本的な解決にならん」"

[[dialogue]]
speaker = "unk"
# にべもない様子で突っ返すセドナさん。
line = "にべもない様子で突っ返すセドナさん。"

[[dialogue]]
speaker = "unk"
# 彼女たちの力は、俺たちと同じ用途にはないと。
line = "彼女たちの力は、俺たちと同じ用途にはないと。"

[[dialogue]]
speaker = "セドナ"
# 「それとも泣きついているのか？　自分たちだけでは人間界すら守りきれぬ──と」
line = "「それとも泣きついているのか？　自分たちだけでは人間界すら守りきれぬ──と」"

[[dialogue]]
speaker = "ヴィーナス"
# 「むか！　別にそんなんじゃないし！」
line = "「むか！　別にそんなんじゃないし！」"

[[dialogue]]
speaker = "セドナ"
# 「なら営々と責務に励みたまえ。所詮私たちは別組織、部分的に共闘するのが関の山だ」
line = "「なら営々と責務に励みたまえ。所詮私たちは別組織、部分的に共闘するのが関の山だ」"

[[dialogue]]
speaker = "クロト"
# 「なるほど……」
line = "「なるほど……」"

[[dialogue]]
speaker = "クロト"
# 「ならやっぱり、あなた達の組織は『世界存続』のために動いている」
line = "「ならやっぱり、あなた達の組織は『世界存続』のために動いている」"

[[dialogue]]
speaker = "セドナ"
# 「その通りだ」
line = "「その通りだ」"

[[dialogue]]
speaker = "unk"
# なんとなく彼女たちのポリシーが判ってきた。
line = "なんとなく彼女たちのポリシーが判ってきた。"

[[dialogue]]
speaker = "unk"
# つまり彼女たちは『世界の存亡』のためには働くものの、『生命の存亡』までは興味がないと。
line = "つまり彼女たちは『世界の存亡』のためには働くものの、『生命の存亡』までは興味がないと。"

[[dialogue]]
speaker = "アイリーン"
# 「別にあなた方が人命救助を行うのを咎めるつもりもありません。適材適所というまでです」
line = "「別にあなた方が人命救助を行うのを咎めるつもりもありません。適材適所というまでです」"

[[dialogue]]
speaker = "セーラ"
# 「ま、確かにこっちから強制できる義理もないけどさ」
line = "「ま、確かにこっちから強制できる義理もないけどさ」"

[[dialogue]]
speaker = "unk"
# 俺たちとしても『ネビュラ』にどうこう言える権利はない。
line = "俺たちとしても『ネビュラ』にどうこう言える権利はない。"

[[dialogue]]
speaker = "unk"
# だが組織としてのスタンスが違う彼女らに、どこまで懐を開いてよいものか──
line = "だが組織としてのスタンスが違う彼女らに、どこまで懐を開いてよいものか──"

[[dialogue]]
speaker = "アイリーン"
# 「！　これは……？」
line = "「！　これは……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あ、私らの連絡だ。もっしもーし」
line = "「あ、私らの連絡だ。もっしもーし」"

[[dialogue]]
speaker = "unk"
# そこへ、俺たち全員のＤＩＳＣ連絡が再び鳴った。
line = "そこへ、俺たち全員のＤＩＳＣ連絡が再び鳴った。"

[[dialogue]]
speaker = "セイファート"
# 『こちらセイファート。聞こえるかね、星徒会メンバー諸君』
line = "『こちらセイファート。聞こえるかね、星徒会メンバー諸君』"

[[dialogue]]
speaker = "クロト"
# 「はい、学園長。どうぞ」
line = "「はい、学園長。どうぞ」"

[[dialogue]]
speaker = "セイファート"
# 『星力の復旧が確認されたのは既に連絡したことかと思う。本件にあたり緊急会議を開くため、ただちに学園まで帰還せよ』
line = "『星力の復旧が確認されたのは既に連絡したことかと思う。本件にあたり緊急会議を開くため、ただちに学園まで帰還せよ』"

[[dialogue]]
speaker = "フィオナ"
# 「了解です。メンバー総員、至急帰還いたします」
line = "「了解です。メンバー総員、至急帰還いたします」"

[[dialogue]]
speaker = "unk"
# ＤＩＳＣの連絡が切れる。
line = "ＤＩＳＣの連絡が切れる。"

[[dialogue]]
speaker = "unk"
# 今の連絡は、俺たち全員へ向けての帰還命令だった。
line = "今の連絡は、俺たち全員へ向けての帰還命令だった。"

[[dialogue]]
speaker = "クロト"
# 「申し訳ありません。そういうことなので」
line = "「申し訳ありません。そういうことなので」"

[[dialogue]]
speaker = "アイリーン"
# 「……このまま帰ると言うのですか」
line = "「……このまま帰ると言うのですか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「命令だもの、ちょっと戻るだけよ♪」
line = "「命令だもの、ちょっと戻るだけよ♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それに──助けてくれたことは感謝してるわ。だけど、私たちもまだ整理がついてないから」
line = "「それに──助けてくれたことは感謝してるわ。だけど、私たちもまだ整理がついてないから」"

[[dialogue]]
speaker = "unk"
# ヴィーナスがあっけなく席を立ったことで、俺たちも揃ってそれに続いた。
line = "ヴィーナスがあっけなく席を立ったことで、俺たちも揃ってそれに続いた。"

[[dialogue]]
speaker = "unk"
# たぶん彼女は素でああ言っているだけなのだが、結果的にけっこう舌が回っている。
line = "たぶん彼女は素でああ言っているだけなのだが、結果的にけっこう舌が回っている。"

[[dialogue]]
speaker = "アイリーン"
# 「まだあなた方の持つ情報について聞けていません」
line = "「まだあなた方の持つ情報について聞けていません」"

[[dialogue]]
speaker = "クロト"
# 「すみません。ヴィーナスの言う通り、俺たちもまだ不確定なことが多いので」
line = "「すみません。ヴィーナスの言う通り、俺たちもまだ不確定なことが多いので」"

[[dialogue]]
speaker = "クロト"
# 「それに……<ruby=スターナイト>星騎士</ruby>はこの三界と、そこにいる命を守るために動いています。俺たちの目的は似ているようで違うものかと」
line = "「それに……<ruby>星騎士<rt>スターナイト</rt></ruby>はこの三界と、そこにいる命を守るために動いています。俺たちの目的は似ているようで違うものかと」"

[[dialogue]]
speaker = "アイリーン"
# 「ふ……ええ、そうですね。私たちはあなた方ほど夢見がちじゃありません」
line = "「ふ……ええ、そうですね。私たちはあなた方ほど夢見がちじゃありません」"

[[dialogue]]
speaker = "アイリーン"
# 「かつて同じようなことを言って、何度も文明が滅んできた歴史を……魔女はずっと見てきていますから」
line = "「かつて同じようなことを言って、何度も文明が滅んできた歴史を……魔女はずっと見てきていますから」"

[[dialogue]]
speaker = "ルリエル"
# 「アイリーンさん……？」
line = "「アイリーンさん……？」"

[[dialogue]]
speaker = "unk"
# 遠い目をするアイリーンさん。
line = "遠い目をするアイリーンさん。"

[[dialogue]]
speaker = "unk"
# 残る問題は、彼女の上司であるセドナさんだったが──
line = "残る問題は、彼女の上司であるセドナさんだったが──"

[[dialogue]]
speaker = "セドナ"
# 「……やれやれ、仕方ないな。君たちの決意は本物らしい」
line = "「……やれやれ、仕方ないな。君たちの決意は本物らしい」"

[[dialogue]]
speaker = "unk"
# 彼女は俺たちの<ruby=まなじり>眦</ruby>を見ると、肩をすくめて笑った。
line = "彼女は俺たちの<ruby>眦<rt>まなじり</rt></ruby>を見ると、肩をすくめて笑った。"

[[dialogue]]
speaker = "マトイ"
# 「じゃあ……」
line = "「じゃあ……」"

[[dialogue]]
speaker = "セドナ"
# 「ああ。では、気をつけてお帰り願おう──」
line = "「ああ。では、気をつけてお帰り願おう──」"

[[dialogue]]
speaker = "ソフィア"
# 「っ！？」
line = "「っ！？」"

[[dialogue]]
speaker = "セドナ"
# 「──などと、甘えた態度を許すとでも？」
line = "「──などと、甘えた態度を許すとでも？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「──何のつもり！？」
line = "「──何のつもり！？」"

[[dialogue]]
speaker = "unk"
# 各所に潜んでいたネビュラの兵士たちが揃って俺たちに銃口を突きつける。
line = "各所に潜んでいたネビュラの兵士たちが揃って俺たちに銃口を突きつける。"

[[dialogue]]
speaker = "unk"
# 先ほどから視線を感じてはいたが……想定していたより多い。
line = "先ほどから視線を感じてはいたが……想定していたより多い。"

[[dialogue]]
speaker = "セドナ"
# 「使えるから生かしたと言っただろう。我々も善意で助けたわけではないのだよ」
line = "「使えるから生かしたと言っただろう。我々も善意で助けたわけではないのだよ」"

[[dialogue]]
speaker = "セドナ"
# 「まあ、それにしてもふん縛るような趣味はない。多少の気概を見せるなら帰してやるさ」
line = "「まあ、それにしてもふん縛るような趣味はない。多少の気概を見せるなら帰してやるさ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「戦え──ってこと……！？」
line = "「戦え──ってこと……！？」"

[[dialogue]]
speaker = "セドナ"
# 「何、ちょっとしたテストだ。我々としても、使えん仲間なら願い下げだからな」
line = "「何、ちょっとしたテストだ。我々としても、使えん仲間なら願い下げだからな」"

[[dialogue]]
speaker = "ユウリ"
# 「なんつー日だよ、ったく……もう散々消耗してるっつーのによ」
line = "「なんつー日だよ、ったく……もう散々消耗してるっつーのによ」"

[[dialogue]]
speaker = "サーシャ"
# 「勝手に連れてきたくせに、強引よね～」
line = "「勝手に連れてきたくせに、強引よね～」"

[[dialogue]]
speaker = "セドナ"
# 「遊んでやれ、アイリーン。私は姫のところへ向かう」
line = "「遊んでやれ、アイリーン。私は姫のところへ向かう」"

[[dialogue]]
speaker = "アイリーン"
# 「イエス、マム。総員──構え！」
line = "「イエス、マム。総員──構え！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「本気みたいね──！」
line = "「本気みたいね──！」"

[[dialogue]]
speaker = "フィオナ"
# 「仕方ありません。お相手しましょう」
line = "「仕方ありません。お相手しましょう」"

[[dialogue]]
speaker = "クロト"
# 「行くぞ、皆！」
line = "「行くぞ、皆！」"
