[[dialogue]]
speaker = "unk"
# 第１０話,世界樹,B
line = "第１０話,世界樹,B"

[[dialogue]]
speaker = "セドナ"
# 「まあいい。存外と気難し屋のようだ──アイリーン、お近づきの印に情報をくれてやれ」
line = "「まあいい。存外と気難し屋のようだ──アイリーン、お近づきの印に情報をくれてやれ」"

[[dialogue]]
speaker = "アイリーン"
# 「はい」
line = "「はい」"

[[dialogue]]
speaker = "unk"
# セドナ長官の命を受け、アイリーンさんが再び俺たちの前に出てくる。
line = "セドナ長官の命を受け、アイリーンさんが再び俺たちの前に出てくる。"

[[dialogue]]
speaker = "アイリーン"
# 「まず──我々は、魔女と呼ばれる一族です。ご存知でしょうか？」
line = "「まず──我々は、魔女と呼ばれる一族です。ご存知でしょうか？」"

[[dialogue]]
speaker = "マトイ"
# 「魔女……」
line = "「魔女……」"

[[dialogue]]
speaker = "ソフィア"
# 「……姉さん。あれでは？」
line = "「……姉さん。あれでは？」"

[[dialogue]]
speaker = "サーシャ"
# 「そうね。まさか本物がいるとは思わなかったわ」
line = "「そうね。まさか本物がいるとは思わなかったわ」"

[[dialogue]]
speaker = "クロト"
# 「魔界で──という、ことですか？」
line = "「魔界で──という、ことですか？」"

[[dialogue]]
speaker = "サーシャ"
# 「ええ。おとぎ話みたいな言い伝えだけど……そんな人たちがいるって聞いたことはあるわ」
line = "「ええ。おとぎ話みたいな言い伝えだけど……そんな人たちがいるって聞いたことはあるわ」"

[[dialogue]]
speaker = "ソフィア"
# 「地元の都市伝説かと思っていました」
line = "「地元の都市伝説かと思っていました」"

[[dialogue]]
speaker = "ルリエル"
# 「ほえー……？　聞いたことありませんね！」
line = "「ほえー……？　聞いたことありませんね！」"

[[dialogue]]
speaker = "アナ"
# 「古い文献に載ってるのなら見たことあります。確か、三界のどこでもない地に住んでいるとか」
line = "「古い文献に載ってるのなら見たことあります。確か、三界のどこでもない地に住んでいるとか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「三界のどこでもない、って──そんなとこ本当にあるの？」
line = "「三界のどこでもない、って──そんなとこ本当にあるの？」"

[[dialogue]]
speaker = "アイリーン"
# 「ええ。無論、天界や人間界に比べるとせせこましい場所ですが」
line = "「ええ。無論、天界や人間界に比べるとせせこましい場所ですが」"

[[dialogue]]
speaker = "アイリーン"
# 「私たちは通常──『魔女の森』と呼ばれる領域で暮らしています。そこには人間も魔族も、天使もおりません」
line = "「私たちは通常──『魔女の森』と呼ばれる領域で暮らしています。そこには人間も魔族も、天使もおりません」"

[[dialogue]]
speaker = "クロト"
# 「森なのに、三界と地続きではないんですか？」
line = "「森なのに、三界と地続きではないんですか？」"

[[dialogue]]
speaker = "アイリーン"
# 「はい。森一帯が亜空間に閉ざされている──と言えばわかりやすいでしょうか」
line = "「はい。森一帯が亜空間に閉ざされている──と言えばわかりやすいでしょうか」"

[[dialogue]]
speaker = "アイリーン"
# 「魔女の森には世界樹と呼ばれる樹がそびえています。その麓が丸ごと、魔女の住まう世界なのです」
line = "「魔女の森には世界樹と呼ばれる樹がそびえています。その麓が丸ごと、魔女の住まう世界なのです」"

[[dialogue]]
speaker = "アイリーン"
# 「なのでここ、ネビュラ基地は──その人間界支部のようなイメージですね」
line = "「なのでここ、ネビュラ基地は──その人間界支部のようなイメージですね」"

[[dialogue]]
speaker = "unk"
# 魔女。
line = "魔女。"

[[dialogue]]
speaker = "unk"
# 人間、魔族、天使──そのどれでもない存在が目の前にいる。
line = "人間、魔族、天使──そのどれでもない存在が目の前にいる。"

[[dialogue]]
speaker = "unk"
# あまりに突飛な話だというのに、不思議と受け入れている自分がいた。
line = "あまりに突飛な話だというのに、不思議と受け入れている自分がいた。"

[[dialogue]]
speaker = "ルリエル"
# 「はいはい、ご質問です！　三界のどこでもない──と仰りましたが、皆さんも私たちのように『大交流』でやって来られたのですか？」
line = "「はいはい、ご質問です！　三界のどこでもない──と仰りましたが、皆さんも私たちのように『大交流』でやって来られたのですか？」"

[[dialogue]]
speaker = "ソフィア"
# 「確かに……あの転送には、各種族ごとの定員が決められていたはずですが」
line = "「確かに……あの転送には、各種族ごとの定員が決められていたはずですが」"

[[dialogue]]
speaker = "unk"
# 四半期に一度、三界の間で行われる大規模な人物移動──大交流。
line = "四半期に一度、三界の間で行われる大規模な人物移動──大交流。"

[[dialogue]]
speaker = "unk"
# 天使や魔族の生徒たちはみな、それに選ばれて学園に来ていたはずだが……
line = "天使や魔族の生徒たちはみな、それに選ばれて学園に来ていたはずだが……"

[[dialogue]]
speaker = "アイリーン"
# 「いいえ。『大交流』には選ばれておりません──あちらを利用すれば、公的な記録にも残ってしまいますしね」
line = "「いいえ。『大交流』には選ばれておりません──あちらを利用すれば、公的な記録にも残ってしまいますしね」"

[[dialogue]]
speaker = "クロト"
# 「なら、あなた達はどうやって人間界に？」
line = "「なら、あなた達はどうやって人間界に？」"

[[dialogue]]
speaker = "アイリーン"
# 「難しい話ではありません。私たちの暮らす森は──三界から離れてはおりますが、架け橋も残っております」
line = "「難しい話ではありません。私たちの暮らす森は──三界から離れてはおりますが、架け橋も残っております」"

[[dialogue]]
speaker = "アイリーン"
# 「あれを通って、やってきたのです」
line = "「あれを通って、やってきたのです」"

[[dialogue]]
speaker = "unk"
# アイリーンさんが基地の奥を指し示す。
line = "アイリーンさんが基地の奥を指し示す。"

[[dialogue]]
speaker = "unk"
# 俺たちが身を乗り出して覗いた先には──<b>巨大な樹の根</b>があった。
line = "俺たちが身を乗り出して覗いた先には──<b>巨大な樹の根</b>があった。"

[[dialogue]]
speaker = "マトイ"
# 「樹……？」
line = "「樹……？」"

[[dialogue]]
speaker = "セーラ"
# 「うける。こんなサイバーなカンジの基地なのに、似合わなすぎ」
line = "「うける。こんなサイバーなカンジの基地なのに、似合わなすぎ」"

[[dialogue]]
speaker = "unk"
# みんなセーラさんの感想に同感だった。
line = "みんなセーラさんの感想に同感だった。"

[[dialogue]]
speaker = "unk"
# ガジェットのひしめく基地内の奥に、ぽつんと一本だけ──剥き出しの樹木が根を張っている。
line = "ガジェットのひしめく基地内の奥に、ぽつんと一本だけ──剥き出しの樹木が根を張っている。"

[[dialogue]]
speaker = "unk"
# うねるような樹皮にはぽっかりと大きな穴が空いており、数人は余裕で入り込めそうに見えた。
line = "うねるような樹皮にはぽっかりと大きな穴が空いており、数人は余裕で入り込めそうに見えた。"

[[dialogue]]
speaker = "unk"
# 観葉植物……というレベルの大きさでないのは確かだ。
line = "観葉植物……というレベルの大きさでないのは確かだ。"

[[dialogue]]
speaker = "クロト"
# 「……なるほど。推察するに──あれが<b>世界樹</b>。いえ、その一部……ということですか」
line = "「……なるほど。推察するに──あれが<b>世界樹</b>。いえ、その一部……ということですか」"

[[dialogue]]
speaker = "アイリーン"
# 「ふふ──お察しがよくて助かります。その通りです」
line = "「ふふ──お察しがよくて助かります。その通りです」"

[[dialogue]]
speaker = "アイリーン"
# 「世界樹とは文字通り──世界と世界を結ぶ樹。あの穴をくぐった先には、私どもの暮らす魔女の森があります」
line = "「世界樹とは文字通り──世界と世界を結ぶ樹。あの穴をくぐった先には、私どもの暮らす魔女の森があります」"

[[dialogue]]
speaker = "アイリーン"
# 「つまりあれは──異世界同士を繋ぐ『世界樹のうろ』なのです」
line = "「つまりあれは──異世界同士を繋ぐ『世界樹のうろ』なのです」"

[[dialogue]]
speaker = "マトイ"
# 「そ、そんな仕組みがあるなんて……」
line = "「そ、そんな仕組みがあるなんて……」"

[[dialogue]]
speaker = "ルリエル"
# 「ほえぇ～。世界はやっぱり広いのですねえ！」
line = "「ほえぇ～。世界はやっぱり広いのですねえ！」"

[[dialogue]]
speaker = "アナ"
# （信じていますか？）
line = "（信じていますか？）"

[[dialogue]]
speaker = "クロト"
# （嘘と決めつける理由はないかな。虚実織り交ぜられてる恐れはあるが）
line = "（嘘と決めつける理由はないかな。虚実織り交ぜられてる恐れはあるが）"

[[dialogue]]
speaker = "unk"
# 魔女──ただでさえ怪しげな存在だ。
line = "魔女──ただでさえ怪しげな存在だ。"

[[dialogue]]
speaker = "unk"
# 油断はせず、けれど貴重な情報と信じて聞くようにしたい。
line = "油断はせず、けれど貴重な情報と信じて聞くようにしたい。"

[[dialogue]]
speaker = "アイリーン"
# 「こほん。話が少々それてしまいましたね。ひとまずご理解いただきたかったのは──私たちが魔女という一族であること」
line = "「こほん。話が少々それてしまいましたね。ひとまずご理解いただきたかったのは──私たちが魔女という一族であること」"

[[dialogue]]
speaker = "アイリーン"
# 「そして、あなた方と同じく、リクリエに対抗しようとしているってことです。ご理解いただけましたか？」
line = "「そして、あなた方と同じく、リクリエに対抗しようとしているってことです。ご理解いただけましたか？」"

[[dialogue]]
speaker = "クロト"
# 「はい。まだ朧げではありますが、ことの輪郭は把握しました」
line = "「はい。まだ朧げではありますが、ことの輪郭は把握しました」"

[[dialogue]]
speaker = "フィオナ"
# 「私からも──詳細なご説明、感謝いたします。また、窮地を救ってくださった件についても」
line = "「私からも──詳細なご説明、感謝いたします。また、窮地を救ってくださった件についても」"

[[dialogue]]
speaker = "アイリーン"
# 「同志ですから。お礼には及びません」
line = "「同志ですから。お礼には及びません」"

[[dialogue]]
speaker = "unk"
# 笑顔でうなずくアイリーンさん。
line = "笑顔でうなずくアイリーンさん。"

[[dialogue]]
speaker = "unk"
# しかし、まだ説明の足りていない点がひとつある。
line = "しかし、まだ説明の足りていない点がひとつある。"

[[dialogue]]
speaker = "クロト"
# 「──皆さんは俺たちを助けてくれました」
line = "「──皆さんは俺たちを助けてくれました」"

[[dialogue]]
speaker = "クロト"
# 「ですが、あの時……地上一帯はアポロの仕業によって星術の使用が封じられていた。これは学園からの連絡でも確かだったことです」
line = "「ですが、あの時……地上一帯はアポロの仕業によって星術の使用が封じられていた。これは学園からの連絡でも確かだったことです」"

[[dialogue]]
speaker = "クロト"
# 「にもかかわらずあなた方はアポロに対抗できるだけの術式を使用していた。あれは、一体どういう理屈でしょうか？」
line = "「にもかかわらずあなた方はアポロに対抗できるだけの術式を使用していた。あれは、一体どういう理屈でしょうか？」"

[[dialogue]]
speaker = "サーシャ"
# 「それって……」
line = "「それって……」"

[[dialogue]]
speaker = "マトイ"
# 「緋宮くんと同じで、守護星が地球ってこと……？」
line = "「緋宮くんと同じで、守護星が地球ってこと……？」"

[[dialogue]]
speaker = "アイリーン"
# 「ふふ──いえ。そういうわけではありません」
line = "「ふふ──いえ。そういうわけではありません」"

[[dialogue]]
speaker = "アイリーン"
# 「私たちの用いる力は──そもそも星術ではないからです」
line = "「私たちの用いる力は──そもそも星術ではないからです」"

[[dialogue]]
speaker = "フィオナ"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "ルリエル"
# 「ほえ……！　じゃ、じゃあなんなのですか……！？」
line = "「ほえ……！　じゃ、じゃあなんなのですか……！？」"

[[dialogue]]
speaker = "unk"
# もしやと勘ぐっていたが、アイリーンさんはあっさりとそう答えた。
line = "もしやと勘ぐっていたが、アイリーンさんはあっさりとそう答えた。"

[[dialogue]]
speaker = "アイリーン"
# 「魔女に伝えられし太古の<ruby=ことわり>理</ruby>──それを指して、魔法と呼びます」
line = "「魔女に伝えられし太古の<ruby>理<rt>ことわり</rt></ruby>──それを指して、魔法と呼びます」"

[[dialogue]]
speaker = "アイリーン"
# 「そして、その源は魔力。私たち魔女は──星騎士の皆さんとは全く異なる摂理で動いているのです」
line = "「そして、その源は魔力。私たち魔女は──星騎士の皆さんとは全く異なる摂理で動いているのです」"

[[dialogue]]
speaker = "unk"
# アポロを焼き払った黒き炎を思い出す。
line = "アポロを焼き払った黒き炎を思い出す。"

[[dialogue]]
speaker = "unk"
# ひと目で異質と感じたあの攻撃は、まさしく異質なものだったという。
line = "ひと目で異質と感じたあの攻撃は、まさしく異質なものだったという。"

[[dialogue]]
speaker = "マトイ"
# 「星力以外にそんなパワーがあるんだ……」
line = "「星力以外にそんなパワーがあるんだ……」"

[[dialogue]]
speaker = "セドナ"
# 「ヒトは古くから超常的な力を見つけ、体系化してきた。世界の破滅に対抗するために」
line = "「ヒトは古くから超常的な力を見つけ、体系化してきた。世界の破滅に対抗するために」"

[[dialogue]]
speaker = "セドナ"
# 「過去には霊力という代物も存在していた──ま、そちらは真実失われた遺物となってしまったがな」
line = "「過去には霊力という代物も存在していた──ま、そちらは真実失われた遺物となってしまったがな」"

[[dialogue]]
speaker = "アイリーン"
# 「そんな感じです。ですが、私たちが皆さんを助けたいと思ったことに、変わりはありませんよ」
line = "「そんな感じです。ですが、私たちが皆さんを助けたいと思ったことに、変わりはありませんよ」"

[[dialogue]]
speaker = "フィオナ"
# （星術以外の力……魔力……霊力……ですか）
line = "（星術以外の力……魔力……霊力……ですか）"

[[dialogue]]
speaker = "unk"
# アポロの『天蓋』によって、俺たち以外も全世界で星術が使えなくなったと連絡されていた。
line = "アポロの『天蓋』によって、俺たち以外も全世界で星術が使えなくなったと連絡されていた。"

[[dialogue]]
speaker = "unk"
# しかし彼女たち『魔女』の操る力はまったく異なる因果で動いているという。
line = "しかし彼女たち『魔女』の操る力はまったく異なる因果で動いているという。"

[[dialogue]]
speaker = "アイリーン"
# 「今回のリクリエは──歴代の中でも最大級の脅威と認識されています」
line = "「今回のリクリエは──歴代の中でも最大級の脅威と認識されています」"

[[dialogue]]
speaker = "アイリーン"
# 「私たちが『ネビュラ』という組織を発足したのも、事態の大きさを鑑みてのことですから」
line = "「私たちが『ネビュラ』という組織を発足したのも、事態の大きさを鑑みてのことですから」"

[[dialogue]]
speaker = "クロト"
# 「……待ってください。歴代の？」
line = "「……待ってください。歴代の？」"

[[dialogue]]
speaker = "アイリーン"
# 「はい」
line = "「はい」"

[[dialogue]]
speaker = "unk"
# 今、アイリーンさんはさり気なく重要なことを言った。
line = "今、アイリーンさんはさり気なく重要なことを言った。"

[[dialogue]]
speaker = "クロト"
# 「<b>前回</b>より前のリクリエを……知っているとでもいうんですか」
line = "「<b>前回</b>より前のリクリエを……知っているとでもいうんですか」"

[[dialogue]]
speaker = "アイリーン"
# 「ええ。魔女の一族は、先代、先々代と……これまで幾度にも渡ってリクリエを観測してきました」
line = "「ええ。魔女の一族は、先代、先々代と……これまで幾度にも渡ってリクリエを観測してきました」"

[[dialogue]]
speaker = "アイリーン"
# 「先ほども言ったように、魔女の森は三界の外にあります。そのためかの災害を免れ、次代まで生き延びることができるわけです」
line = "「先ほども言ったように、魔女の森は三界の外にあります。そのためかの災害を免れ、次代まで生き延びることができるわけです」"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "フィオナ"
# 「……なるほど」
line = "「……なるほど」"

[[dialogue]]
speaker = "ルリエル"
# （先々代……？　あれ……？　リクリエさんって、今回が２度目じゃなかったでしたっけ……？）
line = "（先々代……？　あれ……？　リクリエさんって、今回が２度目じゃなかったでしたっけ……？）"

[[dialogue]]
speaker = "アナ"
# （どうやら私たちも知らない事情があるようです。会長たちは理解しているようなので、口をつぐみましょう）
line = "（どうやら私たちも知らない事情があるようです。会長たちは理解しているようなので、口をつぐみましょう）"

[[dialogue]]
speaker = "unk"
# 前回のみならず、これまでに連綿とリクリエは起こり続けている──
line = "前回のみならず、これまでに連綿とリクリエは起こり続けている──"

[[dialogue]]
speaker = "unk"
# それは、俺たちがフィーニスの塔で学んだ歴史外の歴史だった。
line = "それは、俺たちがフィーニスの塔で学んだ歴史外の歴史だった。"

[[dialogue]]
speaker = "unk"
# 世界の初期化。文明の破滅。
line = "世界の初期化。文明の破滅。"

[[dialogue]]
speaker = "unk"
# あの石版に描かれていたリセットに、魔女の森は巻き込まれていなかったというのか。
line = "あの石版に描かれていたリセットに、魔女の森は巻き込まれていなかったというのか。"

[[dialogue]]
speaker = "セドナ"
# 「直近のリクリエは３０００年前。観測史上初めて、ヒトがその決行を阻止した。魔王と呼ばれる血族の者によってな」
line = "「直近のリクリエは３０００年前。観測史上初めて、ヒトがその決行を阻止した。魔王と呼ばれる血族の者によってな」"

[[dialogue]]
speaker = "ルリエル"
# 「ま……魔王！」
line = "「ま……魔王！」"

[[dialogue]]
speaker = "マトイ"
# 「それって、もしかして……」
line = "「それって、もしかして……」"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……ホントになんでも知ってるのね」
line = "「……ホントになんでも知ってるのね」"

[[dialogue]]
speaker = "unk"
# 俺たちでさえ、フィーニスの塔に登ってようやく得た事実をズバズバと告げられる。
line = "俺たちでさえ、フィーニスの塔に登ってようやく得た事実をズバズバと告げられる。"

[[dialogue]]
speaker = "unk"
# マトイたちに話す手間が奇遇にも省けてしまった。
line = "マトイたちに話す手間が奇遇にも省けてしまった。"

[[dialogue]]
speaker = "セドナ"
# 「集積された智というものだよ。魔女の歴史は数万年──リクリエにまつわる記録はすべて森に残されている」
line = "「集積された智というものだよ。魔女の歴史は数万年──リクリエにまつわる記録はすべて森に残されている」"

[[dialogue]]
speaker = "アナ"
# 「興味深いですね」
line = "「興味深いですね」"

[[dialogue]]
speaker = "unk"
# 彼女たち魔女は、言ってしまえば滅亡を逃れ続けてきた一族だ。
line = "彼女たち魔女は、言ってしまえば滅亡を逃れ続けてきた一族だ。"

[[dialogue]]
speaker = "unk"
# 人間も、天使も、魔族も文明を初期化される中で……
line = "人間も、天使も、魔族も文明を初期化される中で……"

[[dialogue]]
speaker = "unk"
# 魔女だけが生き永らえてきたというなら、その智は確かに本物だろう。
line = "魔女だけが生き永らえてきたというなら、その智は確かに本物だろう。"

[[dialogue]]
speaker = "セドナ"
# 「──ゆえにだ、諸君。我々はかの現象について君たちより遥かに熟知している。よろしいか？」
line = "「──ゆえにだ、諸君。我々はかの現象について君たちより遥かに熟知している。よろしいか？」"

[[dialogue]]
speaker = "クロト"
# 「……はい」
line = "「……はい」"

[[dialogue]]
speaker = "アイリーン"
# 「本題ですね。私たちから皆さまへ訊きたいことが多くあります」
line = "「本題ですね。私たちから皆さまへ訊きたいことが多くあります」"

[[dialogue]]
speaker = "クロト"
# 「わかりました。答えられることなら」
line = "「わかりました。答えられることなら」"

[[dialogue]]
speaker = "unk"
# ネビュラ、そして魔女。
line = "ネビュラ、そして魔女。"

[[dialogue]]
speaker = "unk"
# 全てを明かしてくれたとは言い切れないが──彼女たちはある程度の素性を語ってくれた。
line = "全てを明かしてくれたとは言い切れないが──彼女たちはある程度の素性を語ってくれた。"

[[dialogue]]
speaker = "unk"
# こちらも真摯に答えなくてはならないだろう。
line = "こちらも真摯に答えなくてはならないだろう。"
