[[dialogue]]
speaker = "unk"
# 第６話,新しい星徒会,B
line = "第６話,新しい星徒会,B"

[[dialogue]]
speaker = "unk"
# サーシャが留学したばかりのこと。
line = "サーシャが留学したばかりのこと。"

[[dialogue]]
speaker = "unk"
# 図書館で蔵書を物色していると、一冊の本を見付けた。
line = "図書館で蔵書を物色していると、一冊の本を見付けた。"

[[dialogue]]
speaker = "unk"
# その本の名は『異界探訪』。三界について広くまとめた本で、サーシャをレゾフから連れ出した一冊だった。
line = "その本の名は『異界探訪』。三界について広くまとめた本で、サーシャをレゾフから連れ出した一冊だった。"

[[dialogue]]
speaker = "unk"
# 同じ本を、学園でも見付けられるとは思わなかった。
line = "同じ本を、学園でも見付けられるとは思わなかった。"

[[dialogue]]
speaker = "シルヴィ"
# 「何読んでるの？　その本、楽しい？」
line = "「何読んでるの？　その本、楽しい？」"

[[dialogue]]
speaker = "シルヴィ"
# 「あれ？　もしかして分かんない？　同じクラスのサーシャさんだよね？」
line = "「あれ？　もしかして分かんない？　同じクラスのサーシャさんだよね？」"

[[dialogue]]
speaker = "サーシャ"
# 「あなたは、ええと……ごめんなさい、まだ名前と顔、ちゃんと覚えられていないかも」
line = "「あなたは、ええと……ごめんなさい、まだ名前と顔、ちゃんと覚えられていないかも」"

[[dialogue]]
speaker = "シルヴィ"
# 「あはは、いいよいいよ♪　クラスメイトのシルヴィ・グリムランド！　よろしくね！」
line = "「あはは、いいよいいよ♪　クラスメイトのシルヴィ・グリムランド！　よろしくね！」"

[[dialogue]]
speaker = "シルヴィ"
# 「サーシャ、ごはん行こうよ！」
line = "「サーシャ、ごはん行こうよ！」"

[[dialogue]]
speaker = "シルヴィ"
# 「サーシャ、次の移動教室どこだっけ？」
line = "「サーシャ、次の移動教室どこだっけ？」"

[[dialogue]]
speaker = "シルヴィ"
# 「サーシャ～、これすごい美味しい！　フライドチキンってこんなに美味しかったんだ！」
line = "「サーシャ～、これすごい美味しい！　フライドチキンってこんなに美味しかったんだ！」"

[[dialogue]]
speaker = "unk"
# シルヴィは不思議な子だった。
line = "シルヴィは不思議な子だった。"

[[dialogue]]
speaker = "unk"
# 用がなくても話しかけてくるし、あっても大した用ではなかったりする。
line = "用がなくても話しかけてくるし、あっても大した用ではなかったりする。"

[[dialogue]]
speaker = "unk"
# なんということはない。それが普通の友達だというだけだ。
line = "なんということはない。それが普通の友達だというだけだ。"

[[dialogue]]
speaker = "unk"
# 彼女の周りにはいつも人がいて、いつも笑っていた。サーシャもそのひとりだった。
line = "彼女の周りにはいつも人がいて、いつも笑っていた。サーシャもそのひとりだった。"

[[dialogue]]
speaker = "unk"
# 彼女と深く関わるようになったのは、星徒会長になってからだ。
line = "彼女と深く関わるようになったのは、星徒会長になってからだ。"

[[dialogue]]
speaker = "unk"
# ２年生に上がってすぐ、転機は訪れた。
line = "２年生に上がってすぐ、転機は訪れた。"

[[dialogue]]
speaker = "コハルコ"
# 「聞いたよ、星徒会長に指名されたんだって？」
line = "「聞いたよ、星徒会長に指名されたんだって？」"

[[dialogue]]
speaker = "サーシャ"
# 「そうなのよ～。さすがにびっくりしちゃったわ～」
line = "「そうなのよ～。さすがにびっくりしちゃったわ～」"

[[dialogue]]
speaker = "コハルコ"
# 「まぁ、サーシャならあり得るとは思ってたけど……どうするの？」
line = "「まぁ、サーシャならあり得るとは思ってたけど……どうするの？」"

[[dialogue]]
speaker = "サーシャ"
# 「お引き受けしますって答えたわ～」
line = "「お引き受けしますって答えたわ～」"

[[dialogue]]
speaker = "コハルコ"
# 「えぇっ、即答！？」
line = "「えぇっ、即答！？」"

[[dialogue]]
speaker = "サーシャ"
# 「私にできることなら、そうするだけよ～」
line = "「私にできることなら、そうするだけよ～」"

[[dialogue]]
speaker = "シルヴィ"
# 「はいはい！　サーシャサーシャ！」
line = "「はいはい！　サーシャサーシャ！」"

[[dialogue]]
speaker = "サーシャ"
# 「どうしたの～？」
line = "「どうしたの～？」"

[[dialogue]]
speaker = "シルヴィ"
# 「サーシャ、星徒会長やるんでしょ？」
line = "「サーシャ、星徒会長やるんでしょ？」"

[[dialogue]]
speaker = "サーシャ"
# 「ええ、そうよ～」
line = "「ええ、そうよ～」"

[[dialogue]]
speaker = "シルヴィ"
# 「副会長は決まってるの？」
line = "「副会長は決まってるの？」"

[[dialogue]]
speaker = "サーシャ"
# 「いえ、まだよ～。いい人がいたら教えてちょうだいね」
line = "「いえ、まだよ～。いい人がいたら教えてちょうだいね」"

[[dialogue]]
speaker = "シルヴィ"
# 「じゃあ、あたしがやる！」
line = "「じゃあ、あたしがやる！」"

[[dialogue]]
speaker = "サーシャ"
# 「え」
line = "「え」"

[[dialogue]]
speaker = "サーシャ"
# （……この子、本気で言ってるのかしら？）
line = "（……この子、本気で言ってるのかしら？）"

[[dialogue]]
speaker = "サーシャ"
# 「……あなたもプリマステラだから分かっていると思うけど、星徒会役員は常に危険と隣り合わせなのよ？」
line = "「……あなたもプリマステラだから分かっていると思うけど、星徒会役員は常に危険と隣り合わせなのよ？」"

[[dialogue]]
speaker = "サーシャ"
# （この子が強いのは知ってるけど、戦い方が強引すぎるわ）
line = "（この子が強いのは知ってるけど、戦い方が強引すぎるわ）"

[[dialogue]]
speaker = "シルヴィ"
# 「もちろん分かってる！　だからサーシャとやりたいんだ！」
line = "「もちろん分かってる！　だからサーシャとやりたいんだ！」"

[[dialogue]]
speaker = "サーシャ"
# 「……え？　それはどういう……？」
line = "「……え？　それはどういう……？」"

[[dialogue]]
speaker = "シルヴィ"
# 「だってサーシャって、アステラに入ったらそのままいなくなっちゃいそうだから！」
line = "「だってサーシャって、アステラに入ったらそのままいなくなっちゃいそうだから！」"

[[dialogue]]
speaker = "サーシャ"
# （もしかして私が心配されてる～～～～！？）
line = "（もしかして私が心配されてる～～～～！？）"

[[dialogue]]
speaker = "サーシャ"
# 「こ、コハルコちゃんはどう思う……？」
line = "「こ、コハルコちゃんはどう思う……？」"

[[dialogue]]
speaker = "コハルコ"
# 「私はアリだと思うなぁ。シルヴィ、みんなに頼りにされてるし」
line = "「私はアリだと思うなぁ。シルヴィ、みんなに頼りにされてるし」"

[[dialogue]]
speaker = "サーシャ"
# 「う～～～～ん」
line = "「う～～～～ん」"

[[dialogue]]
speaker = "サーシャ"
# （シルヴィは軽音楽部に所属しつつも、色んな部活に顔を出してる）
line = "（シルヴィは軽音楽部に所属しつつも、色んな部活に顔を出してる）"

[[dialogue]]
speaker = "サーシャ"
# （同級生からだけでなく、後輩からの人望も厚い）
line = "（同級生からだけでなく、後輩からの人望も厚い）"

[[dialogue]]
speaker = "サーシャ"
# （それに生徒の間だけじゃなくて、それ以外の人たちに対しても星騎士として顔が広い）
line = "（それに生徒の間だけじゃなくて、それ以外の人たちに対しても星騎士として顔が広い）"

[[dialogue]]
speaker = "サーシャ"
# （副会長を任せるに、これ以上の適任はいないかもしれない）
line = "（副会長を任せるに、これ以上の適任はいないかもしれない）"

[[dialogue]]
speaker = "サーシャ"
# （でも、不安なところもあるわ。何度か一緒に戦ったけど、向こう見ずというか、勢い任せというか……）
line = "（でも、不安なところもあるわ。何度か一緒に戦ったけど、向こう見ずというか、勢い任せというか……）"

[[dialogue]]
speaker = "サーシャ"
# （この子は強い。けれど、星徒会役員が務まるかどうかは別の話だし……）
line = "（この子は強い。けれど、星徒会役員が務まるかどうかは別の話だし……）"

[[dialogue]]
speaker = "サーシャ"
# （どうするべき、なのかしら……）
line = "（どうするべき、なのかしら……）"

[[dialogue]]
speaker = "シルヴィ"
# 「あはは、いいよいいよ♪　クラスメイトのシルヴィ・グリムランド！　よろしくね！」
line = "「あはは、いいよいいよ♪　クラスメイトのシルヴィ・グリムランド！　よろしくね！」"

[[dialogue]]
speaker = "サーシャ"
# （……そうね、この子の誰とでも仲良くなれるところは星徒会運営の役に立つはず）
line = "（……そうね、この子の誰とでも仲良くなれるところは星徒会運営の役に立つはず）"

[[dialogue]]
speaker = "サーシャ"
# 「分かったわ。私が正式に星徒会長になったら、あなたを副会長に任命します」
line = "「分かったわ。私が正式に星徒会長になったら、あなたを副会長に任命します」"

[[dialogue]]
speaker = "サーシャ"
# 「シルヴィ・グリムランド。あなたの力を貸して」
line = "「シルヴィ・グリムランド。あなたの力を貸して」"

[[dialogue]]
speaker = "シルヴィ"
# 「オッケー！　改めてよろしくね、会長！」
line = "「オッケー！　改めてよろしくね、会長！」"

[[dialogue]]
speaker = "unk"
# こうして、新星星徒会が始動した。
line = "こうして、新星星徒会が始動した。"
