[[dialogue]]
speaker = "unk"
# 第１１話,終焉と絶望,B
line = "第１１話,終焉と絶望,B"

[[dialogue]]
speaker = "unk"
# 滅亡が具現していた。
line = "滅亡が具現していた。"

[[dialogue]]
speaker = "unk"
# 巨大な手の形をした破滅の化身は、“<ruby=リ・クリエイション>世界の再創生</ruby>”という使命のまま、退廃した荒野をなお終わらぬ暴虐に巻き込んでゆく。
line = "巨大な手の形をした破滅の化身は、“<ruby>世界の再創生<rt>リ・クリエイション</rt></ruby>”という使命のまま、退廃した荒野をなお終わらぬ暴虐に巻き込んでゆく。"

[[dialogue]]
speaker = "unk"
# <b>手</b>が指をひとつ動かすだけで、破壊の嵐が吹き荒れる。
line = "<b>手</b>が指をひとつ動かすだけで、破壊の嵐が吹き荒れる。"

[[dialogue]]
speaker = "unk"
# その嵐は、建物を、大地を、これまで積み上げてきた全てを、ただの塵へと変えていく。
line = "その嵐は、建物を、大地を、これまで積み上げてきた全てを、ただの塵へと変えていく。"

[[dialogue]]
speaker = "梨緒"
# 「立て、フィオナ！　動け！　逃げろっ！！」
line = "「立て、フィオナ！　動け！　逃げろっ！！」"

[[dialogue]]
speaker = "unk"
# 傷つき倒れた友を前にして、思わず叫んでいた。
line = "傷つき倒れた友を前にして、思わず叫んでいた。"

[[dialogue]]
speaker = "unk"
# 逃げるところなんてないとわかっているはずなのに、叫ばずにはいられなかった。
line = "逃げるところなんてないとわかっているはずなのに、叫ばずにはいられなかった。"

[[dialogue]]
speaker = "unk"
# もう満足に動けないフィオナにとどめを刺すように、<b>手</b>が爪を振り下ろす。
line = "もう満足に動けないフィオナにとどめを刺すように、<b>手</b>が爪を振り下ろす。"

[[dialogue]]
speaker = "フィオナ"
# （ごめん、エリシア──私のせいで）
line = "（ごめん、エリシア──私のせいで）"

[[dialogue]]
speaker = "？？？"
# 「フィオナ！　フィオナーーーーーッ！！！」
line = "「フィオナ！　フィオナーーーーーッ！！！」"

[[dialogue]]
speaker = "unk"
# フィオナはそれきりピクリとも動かなくなった。
line = "フィオナはそれきりピクリとも動かなくなった。"

[[dialogue]]
speaker = "unk"
# しっかり者だけど甘えん坊な、双子の妹の跡を追った。
line = "しっかり者だけど甘えん坊な、双子の妹の跡を追った。"

[[dialogue]]
speaker = "梨緒"
# 「フィオ……ナ……あぁ……うぅ……」
line = "「フィオ……ナ……あぁ……うぅ……」"

[[dialogue]]
speaker = "unk"
# 残った戦力だけで、あの破滅の化身に勝とうなんて無理だったのだ。
line = "残った戦力だけで、あの破滅の化身に勝とうなんて無理だったのだ。"

[[dialogue]]
speaker = "unk"
# 最強の星騎士の１人も今逝った。もう勝ち目なんて──
line = "最強の星騎士の１人も今逝った。もう勝ち目なんて──"

[[dialogue]]
speaker = "梨緒"
# （いや、私はまだ……生きている……！）
line = "（いや、私はまだ……生きている……！）"

[[dialogue]]
speaker = "unk"
# 少なくとも、ここにまだ１人星騎士がいる。
line = "少なくとも、ここにまだ１人星騎士がいる。"

[[dialogue]]
speaker = "unk"
# どうやって勝つのかなんてわからない。それでも勝つ。実力で勝てないのならば、奇跡でも起こせばいい。
line = "どうやって勝つのかなんてわからない。それでも勝つ。実力で勝てないのならば、奇跡でも起こせばいい。"

[[dialogue]]
speaker = "unk"
# そうでなければ、今まで生き残った意味がない……！
line = "そうでなければ、今まで生き残った意味がない……！"

[[dialogue]]
speaker = "ジグ"
# 「やぁ生きてるかい、アガサ」
line = "「やぁ生きてるかい、アガサ」"

[[dialogue]]
speaker = "梨緒"
# 「ジグ！？　まだ生きて……！？」
line = "「ジグ！？　まだ生きて……！？」"

[[dialogue]]
speaker = "ジグ"
# 「すまない、少し気を失っていたようだ。だけど私はまだ戦えるよ」
line = "「すまない、少し気を失っていたようだ。だけど私はまだ戦えるよ」"

[[dialogue]]
speaker = "unk"
# 目の前に現れたのは、いつも飄々とした笑みを浮かべる、憎きライバル。
line = "目の前に現れたのは、いつも飄々とした笑みを浮かべる、憎きライバル。"

[[dialogue]]
speaker = "unk"
# その軽さは窮地でも変わっていないが、全身に負った傷から鮮血が流れ続けている。本来なら即座に撤退しているはずの負傷だ。
line = "その軽さは窮地でも変わっていないが、全身に負った傷から鮮血が流れ続けている。本来なら即座に撤退しているはずの負傷だ。"

[[dialogue]]
speaker = "unk"
# ろくに傷を負ったところを見たことがない、あのジグが──だ。
line = "ろくに傷を負ったところを見たことがない、あのジグが──だ。"

[[dialogue]]
speaker = "梨緒"
# 「私も……まだ、諦めていない……！　この世界を、守るんだ……！」
line = "「私も……まだ、諦めていない……！　この世界を、守るんだ……！」"

[[dialogue]]
speaker = "ジグ"
# 「ああ、それでこそアガサだ。倒れていったみんなの分まで頑張ろう」
line = "「ああ、それでこそアガサだ。倒れていったみんなの分まで頑張ろう」"

[[dialogue]]
speaker = "unk"
# ジグが空に浮かぶディザスターハンドを見据える。
line = "ジグが空に浮かぶディザスターハンドを見据える。"

[[dialogue]]
speaker = "unk"
# 軽薄な笑顔が険しい表情に変わり、見極めるように目を細めて──
line = "軽薄な笑顔が険しい表情に変わり、見極めるように目を細めて──"

[[dialogue]]
speaker = "ジグ"
# 「──！」
line = "「──！」"

[[dialogue]]
speaker = "unk"
# <b>それ</b>が現れた。
line = "<b>それ</b>が現れた。"

[[dialogue]]
speaker = "unk"
# <b>それ</b>が何かは理解できなかった。
line = "<b>それ</b>が何かは理解できなかった。"

[[dialogue]]
speaker = "unk"
# <b>それ</b>は、しいて表現するなら途方もなく巨大な立方体だった。
line = "<b>それ</b>は、しいて表現するなら途方もなく巨大な立方体だった。"

[[dialogue]]
speaker = "unk"
# 今まで見てきた何よりも整然としていて、何よりもグロテスクだった。
line = "今まで見てきた何よりも整然としていて、何よりもグロテスクだった。"

[[dialogue]]
speaker = "unk"
# 目が、脳が、本能が、理解を拒む。
line = "目が、脳が、本能が、理解を拒む。"

[[dialogue]]
speaker = "unk"
# <b>それ</b>は見てはならないもの。
line = "<b>それ</b>は見てはならないもの。"

[[dialogue]]
speaker = "unk"
# 本来なら人の身で触れてはならないものだった。
line = "本来なら人の身で触れてはならないものだった。"

[[dialogue]]
speaker = "ジグ"
# 「ぁ……」
line = "「ぁ……」"

[[dialogue]]
speaker = "unk"
# ジグの目から光が消える。
line = "ジグの目から光が消える。"

[[dialogue]]
speaker = "unk"
# ディザスターハンドを前にしても軽い笑みを浮かべていたジグが、目を見開き、呆然としていた。
line = "ディザスターハンドを前にしても軽い笑みを浮かべていたジグが、目を見開き、呆然としていた。"

[[dialogue]]
speaker = "unk"
# その表情は──絶望だった。
line = "その表情は──絶望だった。"

[[dialogue]]
speaker = "unk"
# <b>それ</b>から光の触手が伸びる。
line = "<b>それ</b>から光の触手が伸びる。"

[[dialogue]]
speaker = "unk"
# 触手が目の前まで伸びてきて、ジグに触れた。
line = "触手が目の前まで伸びてきて、ジグに触れた。"

[[dialogue]]
speaker = "unk"
# このままではジグが殺される──いや、殺されるのならまだマシかもしれない。
line = "このままではジグが殺される──いや、殺されるのならまだマシかもしれない。"

[[dialogue]]
speaker = "unk"
# きっと、もっとおぞましい何かをされる。
line = "きっと、もっとおぞましい何かをされる。"

[[dialogue]]
speaker = "unk"
# 助けなければ。動かなければ。
line = "助けなければ。動かなければ。"

[[dialogue]]
speaker = "unk"
# 死んでもいい。体を引き千切られてもいい。だから何かしなければ──
line = "死んでもいい。体を引き千切られてもいい。だから何かしなければ──"

[[dialogue]]
speaker = "梨緒"
# （そんなの……無理だ）
line = "（そんなの……無理だ）"

[[dialogue]]
speaker = "unk"
# 勝てない。敵わない。抗えない。
line = "勝てない。敵わない。抗えない。"

[[dialogue]]
speaker = "unk"
# あんなのに抗っても無意味だ。無駄だ。勝てるわけがない。
line = "あんなのに抗っても無意味だ。無駄だ。勝てるわけがない。"

[[dialogue]]
speaker = "unk"
# だから……何もできなかった。
line = "だから……何もできなかった。"

[[dialogue]]
speaker = "unk"
# そして<b>それ</b>は星騎士ジグを作り変え──
line = "そして<b>それ</b>は星騎士ジグを作り変え──"

[[dialogue]]
speaker = "unk"
# リクリエの使徒『ジグ』が生まれた。
line = "リクリエの使徒『ジグ』が生まれた。"

[[dialogue]]
speaker = "梨緒"
# 「私は何もできなかった……ジグを助けられなかった……」
line = "「私は何もできなかった……ジグを助けられなかった……」"

[[dialogue]]
speaker = "梨緒"
# 「いや違う……」
line = "「いや違う……」"

[[dialogue]]
speaker = "梨緒"
# 「私は何もしなかったんだ……」
line = "「私は何もしなかったんだ……」"

[[dialogue]]
speaker = "？？？"
# 「梨緒！」
line = "「梨緒！」"

[[dialogue]]
speaker = "？？？"
# 「梨緒！　起きて！　目を覚まして！」
line = "「梨緒！　起きて！　目を覚まして！」"

[[dialogue]]
speaker = "？？？"
# 「梨緒！！！」
line = "「梨緒！！！」"

[[dialogue]]
speaker = "梨緒"
# 「──ッ」
line = "「──ッ」"

[[dialogue]]
speaker = "ナターシャ"
# 「梨緒、目が覚めた？　邪魔してくるガーディアンなら倒したよ」
line = "「梨緒、目が覚めた？　邪魔してくるガーディアンなら倒したよ」"

[[dialogue]]
speaker = "梨緒"
# 「あ、ああ……ありがとう……」
line = "「あ、ああ……ありがとう……」"

[[dialogue]]
speaker = "ナターシャ"
# 「さっき見えたのは……」
line = "「さっき見えたのは……」"

[[dialogue]]
speaker = "梨緒"
# 「ベガの最期の瞬間だ」
line = "「ベガの最期の瞬間だ」"

[[dialogue]]
speaker = "ナターシャ"
# 「やっぱり、そうだよね……」
line = "「やっぱり、そうだよね……」"

[[dialogue]]
speaker = "unk"
# ベガの破滅を目の当たりにして、さすがのナターシャも顔を曇らせていた。
line = "ベガの破滅を目の当たりにして、さすがのナターシャも顔を曇らせていた。"

[[dialogue]]
speaker = "梨緒"
# 「私の欠けていた記憶が、何なのか思い出した」
line = "「私の欠けていた記憶が、何なのか思い出した」"

[[dialogue]]
speaker = "梨緒"
# 「ベガが滅びた時、私が見たもの。今なら何なのかわかる。あれがきっと『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』だ」
line = "「ベガが滅びた時、私が見たもの。今なら何なのかわかる。あれがきっと『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』だ」"

[[dialogue]]
speaker = "ナターシャ"
# 「じゃあ梨緒は『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』を見て記憶を失ったってこと？」
line = "「じゃあ梨緒は『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』を見て記憶を失ったってこと？」"

[[dialogue]]
speaker = "梨緒"
# 「いや違う」
line = "「いや違う」"

[[dialogue]]
speaker = "梨緒"
# 「私は自分が情けなくて、記憶を閉ざしていただけだったんだ」
line = "「私は自分が情けなくて、記憶を閉ざしていただけだったんだ」"

[[dialogue]]
speaker = "梨緒"
# 「私はジグを──」
line = "「私はジグを──」"

[[dialogue]]
speaker = "梨緒"
# 「見捨てたんだ」
line = "「見捨てたんだ」"
