[[dialogue]]
speaker = "unk"
# 第１話,予期された運命,B
line = "第１話,予期された運命,B"

[[dialogue]]
speaker = "unk"
# 荒鷹ノ月・十四日──
line = "荒鷹ノ月・十四日──"

[[dialogue]]
speaker = "unk"
# 新星学園星徒会はその新たなる出発から、ひと月が経過していた。
line = "新星学園星徒会はその新たなる出発から、ひと月が経過していた。"

[[dialogue]]
speaker = "アナ"
# 「<ruby=こうじゃく>黄雀</ruby>ノ月十二日。《魔王》は始まりの階層を踏破し、塔の頂へ至る道を歩み始めた」
line = "「<ruby>黄雀<rt>こうじゃく</rt></ruby>ノ月十二日。《魔王》は始まりの階層を踏破し、塔の頂へ至る道を歩み始めた」"

[[dialogue]]
speaker = "アナ"
# 「彼の背中は日に日に大きくなっていく。真の力が目覚める日も、そう遠くないのかもしれない……」
line = "「彼の背中は日に日に大きくなっていく。真の力が目覚める日も、そう遠くないのかもしれない……」"

[[dialogue]]
speaker = "アナ"
# 「──確かに、先月、前会長たちが『フィーニスの塔』に踏み込んだ出来事を指しているように思えます」
line = "「──確かに、先月、前会長たちが『フィーニスの塔』に踏み込んだ出来事を指しているように思えます」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でしょう？　この日誌に間違いはないんだから！」
line = "「でしょう？　この日誌に間違いはないんだから！」"

[[dialogue]]
speaker = "アナ"
# 「相変わらず不思議さ満点のアイテムですね……」
line = "「相変わらず不思議さ満点のアイテムですね……」"

[[dialogue]]
speaker = "unk"
# ペラペラと『未来の日誌』をめくるアナ。
line = "ペラペラと『未来の日誌』をめくるアナ。"

[[dialogue]]
speaker = "unk"
# 彼女たちの座る机には、それ以外の書物も大量に散乱していた。
line = "彼女たちの座る机には、それ以外の書物も大量に散乱していた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「にしても、ふう……ここの図書館なら見つかると思ったんだけど」
line = "「にしても、ふう……ここの図書館なら見つかると思ったんだけど」"

[[dialogue]]
speaker = "アナ"
# 「<ruby=かんば>芳</ruby>しくありませんね」
line = "「<ruby>芳<rt>かんば</rt></ruby>しくありませんね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ん～、もう頭いたーい！　私、文字ばかり読んでると身体が参ってきちゃうのよね」
line = "「ん～、もう頭いたーい！　私、文字ばかり読んでると身体が参ってきちゃうのよね」"

[[dialogue]]
speaker = "アナ"
# 「こちらにも『予言の書』なるものが収蔵されていましたが……中身はデタラメ。この手の本はインチキばっかりですね」
line = "「こちらにも『予言の書』なるものが収蔵されていましたが……中身はデタラメ。この手の本はインチキばっかりですね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「星術関連もゼンメツよ！　未来予知の能力なんて、どこにも前例がないわ」
line = "「星術関連もゼンメツよ！　未来予知の能力なんて、どこにも前例がないわ」"

[[dialogue]]
speaker = "unk"
# ２人はヴィーナスの持つ『未来の日誌』について何か手がかりがないか調査していた。
line = "２人はヴィーナスの持つ『未来の日誌』について何か手がかりがないか調査していた。"

[[dialogue]]
speaker = "unk"
# しかしながら２時間経ってもそれらしい情報は得られず、ヴィーナスもいよいよ脚をばたつかせ始めている。
line = "しかしながら２時間経ってもそれらしい情報は得られず、ヴィーナスもいよいよ脚をばたつかせ始めている。"

[[dialogue]]
speaker = "ヴィーナス"
# 「うちのメイドに似たような『眼』を持つ子がいたから、ヒントくらいはあるかと思ったんだけど」
line = "「うちのメイドに似たような『眼』を持つ子がいたから、ヒントくらいはあるかと思ったんだけど」"

[[dialogue]]
speaker = "アナ"
# 「眼……？　未来予知の、ですか？」
line = "「眼……？　未来予知の、ですか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「予知っていうか……予測？　んでも、見えるのは一瞬先までみたいなのよね」
line = "「予知っていうか……予測？　んでも、見えるのは一瞬先までみたいなのよね」"

[[dialogue]]
speaker = "アナ"
# 「なるほど。それはまた──別種の能力である可能性が高そうですね」
line = "「なるほど。それはまた──別種の能力である可能性が高そうですね」"

[[dialogue]]
speaker = "unk"
# ２人はさらに調査を進めるも、やはり<ruby=かんば>芳</ruby>しい成果は得られなかった。
line = "２人はさらに調査を進めるも、やはり<ruby>芳<rt>かんば</rt></ruby>しい成果は得られなかった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ねーアナ、もういいんじゃない？　日誌が間違ってたってわけでもないんだし～」
line = "「ねーアナ、もういいんじゃない？　日誌が間違ってたってわけでもないんだし～」"

[[dialogue]]
speaker = "アナ"
# 「正体もわからず頼り続けるのは危険です。人智を超えたアイテム──追究するに越したことはありません」
line = "「正体もわからず頼り続けるのは危険です。人智を超えたアイテム──追究するに越したことはありません」"

[[dialogue]]
speaker = "ヴィーナス"
# 「うへぇ～」
line = "「うへぇ～」"

[[dialogue]]
speaker = "unk"
# アナに言われ、またしばらく書物とにらめっこを続ける２人。
line = "アナに言われ、またしばらく書物とにらめっこを続ける２人。"

[[dialogue]]
speaker = "unk"
# そこへ……
line = "そこへ……"

[[dialogue]]
speaker = "ウィステリア"
# 「どうかしら、２人とも。ちゃんと探してたものは調べられた？」
line = "「どうかしら、２人とも。ちゃんと探してたものは調べられた？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ウィステリアさん──ううん、全然ダメ！」
line = "「ウィステリアさん──ううん、全然ダメ！」"

[[dialogue]]
speaker = "アナ"
# 「釣りで言うとボウズ」
line = "「釣りで言うとボウズ」"

[[dialogue]]
speaker = "ウィステリア"
# 「釣りで言う必要はよくわからないけれど……学生が自分から調べて学習するのは良いことだわ」
line = "「釣りで言う必要はよくわからないけれど……学生が自分から調べて学習するのは良いことだわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「それに、九浄さんが図書館を利用する日が来るなんてね。アナさんは常連だけれど」
line = "「それに、九浄さんが図書館を利用する日が来るなんてね。アナさんは常連だけれど」"

[[dialogue]]
speaker = "ヴィーナス"
# 「わ、私だって本くらい読めるんだから！」
line = "「わ、私だって本くらい読めるんだから！」"

[[dialogue]]
speaker = "アナ"
# 「さっき初めて利用者登録してた。元星徒会長なのに」
line = "「さっき初めて利用者登録してた。元星徒会長なのに」"

[[dialogue]]
speaker = "ウィステリア"
# 「うふふ。ところで、何の本を探していたの？　ここにある書籍……随分と昔のものみたいだけど」
line = "「うふふ。ところで、何の本を探していたの？　ここにある書籍……随分と昔のものみたいだけど」"

[[dialogue]]
speaker = "アナ"
# 「前会長の不思議アイテムについて調べてました。６００年前の書まで遡ってみましたが……それらしい記述は見当たらず」
line = "「前会長の不思議アイテムについて調べてました。６００年前の書まで遡ってみましたが……それらしい記述は見当たらず」"

[[dialogue]]
speaker = "ウィステリア"
# 「そ、そんなに昔のまで？」
line = "「そ、そんなに昔のまで？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でもアナ、この図鑑にある『相手の心を見通すメガネ』ってやつ欲しくない！？」
line = "「でもアナ、この図鑑にある『相手の心を見通すメガネ』ってやつ欲しくない！？」"

[[dialogue]]
speaker = "アナ"
# 「それは一人で探しに行ってください」
line = "「それは一人で探しに行ってください」"

[[dialogue]]
speaker = "ウィステリア"
# 「アナさんがここの蔵書を漁っても見つからない、となると……確かに不思議ねぇ」
line = "「アナさんがここの蔵書を漁っても見つからない、となると……確かに不思議ねぇ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「やっぱり、記録にはない未知のアイテムなのよ」
line = "「やっぱり、記録にはない未知のアイテムなのよ」"

[[dialogue]]
speaker = "アナ"
# 「それでも……似たような例がないかは調べるべきです」
line = "「それでも……似たような例がないかは調べるべきです」"

[[dialogue]]
speaker = "ウィステリア"
# 「人間界じゃなくて、他の世界にあるとかかしら？　そういえば天界にも立派な図書館があるみたいよ」
line = "「人間界じゃなくて、他の世界にあるとかかしら？　そういえば天界にも立派な図書館があるみたいよ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「気軽に行ける場所じゃないわね……」
line = "「気軽に行ける場所じゃないわね……」"

[[dialogue]]
speaker = "unk"
# 流星／新星学園には天使・魔族の留学生が多くいる。
line = "流星／新星学園には天使・魔族の留学生が多くいる。"

[[dialogue]]
speaker = "unk"
# しかし、彼らがこうして人間界にやってくるのも決して簡単な道のりではなかった。
line = "しかし、彼らがこうして人間界にやってくるのも決して簡単な道のりではなかった。"

[[dialogue]]
speaker = "アナ"
# 「天界の立派な図書館──となると、恐らくウル大図書館。私の地元ですね」
line = "「天界の立派な図書館──となると、恐らくウル大図書館。私の地元ですね」"

[[dialogue]]
speaker = "ウィステリア"
# 「あら、そうなの？」
line = "「あら、そうなの？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「じゃあアナが里帰りしたら──と思ったけど、ムリなんだっけ」
line = "「じゃあアナが里帰りしたら──と思ったけど、ムリなんだっけ」"

[[dialogue]]
speaker = "アナ"
# 「そうですね。私が次に帰れるのは、卒業時の『大交流』と決まっています」
line = "「そうですね。私が次に帰れるのは、卒業時の『大交流』と決まっています」"

[[dialogue]]
speaker = "unk"
# 通常、三界の行き来には大幅な制限が伴う。
line = "通常、三界の行き来には大幅な制限が伴う。"

[[dialogue]]
speaker = "unk"
# それは人間が出ていく場合も、天使が里帰りをする場合も例外ではない。
line = "それは人間が出ていく場合も、天使が里帰りをする場合も例外ではない。"

[[dialogue]]
speaker = "unk"
# 本来は分かたれている天界──人間界──魔界──の狭間に、限定的な<ruby=ホール>穴</ruby>を構築する必要があるためだ。
line = "本来は分かたれている天界──人間界──魔界──の狭間に、限定的な<ruby>穴<rt>ホール</rt></ruby>を構築する必要があるためだ。"

[[dialogue]]
speaker = "unk"
# これは極めて大掛かりな作業であるほか、狭く一時的なものしか開けることができない。
line = "これは極めて大掛かりな作業であるほか、狭く一時的なものしか開けることができない。"

[[dialogue]]
speaker = "unk"
# 唯一、定期的に三界の物資をやり取りできる機会こそが『大交流』だった。
line = "唯一、定期的に三界の物資をやり取りできる機会こそが『大交流』だった。"

[[dialogue]]
speaker = "unk"
# およそ四半期に一度、三界が同時に穴を構築することで──前もって決められた物資・人員をその機に転送し合うというものだ。
line = "およそ四半期に一度、三界が同時に穴を構築することで──前もって決められた物資・人員をその機に転送し合うというものだ。"

[[dialogue]]
speaker = "unk"
# 例えるならば船を<ruby=いっせき>一隻</ruby>だけ運航できるといったところか。
line = "例えるならば船を<ruby>一隻<rt>いっせき</rt></ruby>だけ運航できるといったところか。"

[[dialogue]]
speaker = "unk"
# この船に乗れる人員は決して多くなく、また選ばれるには『送るべき要人』として認められる必要もあった。
line = "この船に乗れる人員は決して多くなく、また選ばれるには『送るべき要人』として認められる必要もあった。"

[[dialogue]]
speaker = "unk"
# アナのような流星／新星学園の留学生たちはそんな希少な人材として人間界へやってきている。
line = "アナのような流星／新星学園の留学生たちはそんな希少な人材として人間界へやってきている。"

[[dialogue]]
speaker = "アナ"
# 「とはいえ、本一冊の取り寄せ程度なら可能なはずです。次の『大交流』までに要請しておきましょう」
line = "「とはいえ、本一冊の取り寄せ程度なら可能なはずです。次の『大交流』までに要請しておきましょう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そんな先まで待てるかしら。日誌はどんどん先に進んじゃうわよ！」
line = "「そんな先まで待てるかしら。日誌はどんどん先に進んじゃうわよ！」"

[[dialogue]]
speaker = "ウィステリア"
# 「本当に不思議なアイテムなのねぇ」
line = "「本当に不思議なアイテムなのねぇ」"

[[dialogue]]
speaker = "unk"
# と、彼女たちが会話を続けていると……
line = "と、彼女たちが会話を続けていると……"

[[dialogue]]
speaker = "モネ"
# 「ウィステリアさーん！　今度の読書週間について相談が～！」
line = "「ウィステリアさーん！　今度の読書週間について相談が～！」"

[[dialogue]]
speaker = "ウィステリア"
# 「はーい。それじゃ、また困ったらいつでも声かけてね～」
line = "「はーい。それじゃ、また困ったらいつでも声かけてね～」"

[[dialogue]]
speaker = "unk"
# 図書委員の学生に呼ばれ、ウィステリアはその場を去っていった。
line = "図書委員の学生に呼ばれ、ウィステリアはその場を去っていった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「にしても──司書さんって魔族の先生がやってたのね。知らなかったわ」
line = "「にしても──司書さんって魔族の先生がやってたのね。知らなかったわ」"

[[dialogue]]
speaker = "アナ"
# 「他にも何名かいらっしゃるようですが、基本は彼女ですね」
line = "「他にも何名かいらっしゃるようですが、基本は彼女ですね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それに、大人の色気を感じる女性だったわね……あれは。えろいわ！」
line = "「それに、大人の色気を感じる女性だったわね……あれは。えろいわ！」"

[[dialogue]]
speaker = "アナ"
# 「私たちも頑張りましょう」
line = "「私たちも頑張りましょう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……アナよりは私のほうがオトナよね？」
line = "「……アナよりは私のほうがオトナよね？」"

[[dialogue]]
speaker = "アナ"
# 「いえ。身体面と精神面を差し引きして、どっこいどっこいかと」
line = "「いえ。身体面と精神面を差し引きして、どっこいどっこいかと」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なんかフクザツだわ……」
line = "「なんかフクザツだわ……」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは年下のアナからの仲間意識にもやもやしつつ、手元にあった日誌から今日のページを開いた。
line = "ヴィーナスは年下のアナからの仲間意識にもやもやしつつ、手元にあった日誌から今日のページを開いた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「そだ。今のこともそれっぽく書かれてたわね。ほらここ」
line = "「そだ。今のこともそれっぽく書かれてたわね。ほらここ」"

[[dialogue]]
speaker = "アナ"
# 「えと……<ruby=あらたか>荒鷹</ruby>ノ月十四日。知の殿堂を司りし魔族と初の邂逅を果たす──」
line = "「えと……<ruby>荒鷹<rt>あらたか</rt></ruby>ノ月十四日。知の殿堂を司りし魔族と初の邂逅を果たす──」"

[[dialogue]]
speaker = "アナ"
# 「なるほど。確かに司書──ウィステリア女史のことを指しているように取れます」
line = "「なるほど。確かに司書──ウィステリア女史のことを指しているように取れます」"

[[dialogue]]
speaker = "アナ"
# 「こんなことまで記されているなんて……改めてとんでもない道具ですね」
line = "「こんなことまで記されているなんて……改めてとんでもない道具ですね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふふん。ざっと来週くらいまでは書かれてるわね──大した事件もなさそうだけど」
line = "「ふふん。ざっと来週くらいまでは書かれてるわね──大した事件もなさそうだけど」"

[[dialogue]]
speaker = "アナ"
# 「とはいえ仕組みが気になります。いくらでも悪用のできるものですから」
line = "「とはいえ仕組みが気になります。いくらでも悪用のできるものですから」"

[[dialogue]]
speaker = "ヴィーナス"
# 「仕組み……って言っても。前にも言った通りよ、未来のことが書かれてるの♪」
line = "「仕組み……って言っても。前にも言った通りよ、未来のことが書かれてるの♪」"

[[dialogue]]
speaker = "アナ"
# 「でも、前会長が書いているわけではないのですよね」
line = "「でも、前会長が書いているわけではないのですよね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうね。今みたいのが先々まで既に書かれてて……私はそれに従って動くって感じ！」
line = "「そうね。今みたいのが先々まで既に書かれてて……私はそれに従って動くって感じ！」"

[[dialogue]]
speaker = "アナ"
# 「どこで拾ったのです？　いつから所有しているのです？　筆跡に心当たりはないのです？」
line = "「どこで拾ったのです？　いつから所有しているのです？　筆跡に心当たりはないのです？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「フフフ──全部わからないわ！！」
line = "「フフフ──全部わからないわ！！」"

[[dialogue]]
speaker = "アナ"
# 「相変わらず頼もしくない自信です……」
line = "「相変わらず頼もしくない自信です……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だから……私にもうまく説明できないのよね。<b>そういうもの</b>、としか」
line = "「だから……私にもうまく説明できないのよね。<b>そういうもの</b>、としか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「物心ついた時から……私はこれを持ってたの。<b>なぜか</b>」
line = "「物心ついた時から……私はこれを持ってたの。<b>なぜか</b>」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でもって、この日誌の最後に書かれていたのが──『魔王』との出会いだった。だから、私はそれを待つのが自然なことだと思ってた」
line = "「でもって、この日誌の最後に書かれていたのが──『魔王』との出会いだった。だから、私はそれを待つのが自然なことだと思ってた」"

[[dialogue]]
speaker = "アナ"
# 「前会長はそんな昔から、現会長のことを……」
line = "「前会長はそんな昔から、現会長のことを……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「今、クロトと出会って。この先どうなるんだろうって思ったら──まさかページが増えるなんてね。びっくりだわ」
line = "「今、クロトと出会って。この先どうなるんだろうって思ったら──まさかページが増えるなんてね。びっくりだわ」"

[[dialogue]]
speaker = "unk"
# ──未来の日誌。
line = "──未来の日誌。"

[[dialogue]]
speaker = "unk"
# 彼女はこれをそう呼んでいたが、もちろん正式な名称ではない。
line = "彼女はこれをそう呼んでいたが、もちろん正式な名称ではない。"

[[dialogue]]
speaker = "unk"
# なにせ表紙に何も書かれていなければ、筆者の正体もわかっていないのだ。
line = "なにせ表紙に何も書かれていなければ、筆者の正体もわかっていないのだ。"

[[dialogue]]
speaker = "アナ"
# 「その日誌の通りにいかなかったイレギュラーですとか……これまでにはなかったのでしょうか？」
line = "「その日誌の通りにいかなかったイレギュラーですとか……これまでにはなかったのでしょうか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なかったわね。ただの一度も！」
line = "「なかったわね。ただの一度も！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「アナだって──この日誌の通り『魔王が来たる』のを目の当たりにしたでしょ？」
line = "「アナだって──この日誌の通り『魔王が来たる』のを目の当たりにしたでしょ？」"

[[dialogue]]
speaker = "アナ"
# 「ええ……それは確かに、そうなのですが」
line = "「ええ……それは確かに、そうなのですが」"

[[dialogue]]
speaker = "unk"
# それは、緋宮クロトが入学する以前のこと──
line = "それは、緋宮クロトが入学する以前のこと──"

[[dialogue]]
speaker = "ヴィーナス"
# 「ねえアナ。今度、転入試験に来る子の資料ってまとめた？」
line = "「ねえアナ。今度、転入試験に来る子の資料ってまとめた？」"

[[dialogue]]
speaker = "アナ"
# 「はい。問題がなければ、職員室へ提出するつもりですが……」
line = "「はい。問題がなければ、職員室へ提出するつもりですが……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「その男の子、魔王だから。いずれ私たちの仲間になるわよ」
line = "「その男の子、魔王だから。いずれ私たちの仲間になるわよ」"

[[dialogue]]
speaker = "アナ"
# 「……。はい……？」
line = "「……。はい……？」"

[[dialogue]]
speaker = "unk"
# ヴィーナスの突飛な言動にアナは目を丸くした。
line = "ヴィーナスの突飛な言動にアナは目を丸くした。"

[[dialogue]]
speaker = "unk"
# 副会長のアナは当時、会長であった彼女のわがままに大層振り回されていたが、中でも理解を越えていたのがこの時だった。
line = "副会長のアナは当時、会長であった彼女のわがままに大層振り回されていたが、中でも理解を越えていたのがこの時だった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「だから心の準備をしといてねって話。あと、もし彼が入学して困ったことがあったらサポートしてあげて」
line = "「だから心の準備をしといてねって話。あと、もし彼が入学して困ったことがあったらサポートしてあげて」"

[[dialogue]]
speaker = "アナ"
# 「あの……会長？　そもそも転入は通常の試験より狭い門ですし、この方が合格できるかどうかはまだ……」
line = "「あの……会長？　そもそも転入は通常の試験より狭い門ですし、この方が合格できるかどうかはまだ……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「するわよ。だって、私たちはこの学園で出会うんだもの」
line = "「するわよ。だって、私たちはこの学園で出会うんだもの」"

[[dialogue]]
speaker = "unk"
# 窓の外を見るヴィーナス。その語調はいつも以上の確信に満ちていた──
line = "窓の外を見るヴィーナス。その語調はいつも以上の確信に満ちていた──"

[[dialogue]]
speaker = "unk"
# そうして入学してきた緋宮クロトはヴィーナスの予言通り、彼女をも凌ぐ潜在能力を全校生徒の前で見せつけてみせた。
line = "そうして入学してきた緋宮クロトはヴィーナスの予言通り、彼女をも凌ぐ潜在能力を全校生徒の前で見せつけてみせた。"

[[dialogue]]
speaker = "unk"
# アナにとっても件の日誌が無視できなくなった瞬間である。
line = "アナにとっても件の日誌が無視できなくなった瞬間である。"

[[dialogue]]
speaker = "アナ"
# 「だからこそというものです。超常の力というのは否定しませんが、何もかも頭から信じ込むのは危険かと」
line = "「だからこそというものです。超常の力というのは否定しませんが、何もかも頭から信じ込むのは危険かと」"

[[dialogue]]
speaker = "ヴィーナス"
# 「も～。アナは心配性ねえ～。こーんな便利な道具なんだから、素直に従っておけばいいのに～」
line = "「も～。アナは心配性ねえ～。こーんな便利な道具なんだから、素直に従っておけばいいのに～」"

[[dialogue]]
speaker = "アナ"
# （必然的な運命の記述……しかし、これまでの記述がいくら<ruby=むびゅう>無謬</ruby>であったとて今後も正しいという証明にはならない）
line = "（必然的な運命の記述……しかし、これまでの記述がいくら<ruby>無謬<rt>むびゅう</rt></ruby>であったとて今後も正しいという証明にはならない）"

[[dialogue]]
speaker = "アナ"
# （この日誌に従うことが、私たちにとってメリットのあることなのかどうかも、今はまだ……」）
line = "（この日誌に従うことが、私たちにとってメリットのあることなのかどうかも、今はまだ……」）"

[[dialogue]]
speaker = "アナ"
# （でも、前会長を説得するのは厳しそうなので……少なくとも私は警戒しておくとしましょう）
line = "（でも、前会長を説得するのは厳しそうなので……少なくとも私は警戒しておくとしましょう）"

[[dialogue]]
speaker = "ヴィーナス"
# 「ホントはどこで買ったかとか、誰にもらったかとか、わかればいーんだけど」
line = "「ホントはどこで買ったかとか、誰にもらったかとか、わかればいーんだけど」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ごめんね。私、<b>５年以上前の記憶がない</b>から」
line = "「ごめんね。私、<b>５年以上前の記憶がない</b>から」"

[[dialogue]]
speaker = "アナ"
# 「……そうでしたね。でも、それなら……」
line = "「……そうでしたね。でも、それなら……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それなら……？」
line = "「それなら……？」"

[[dialogue]]
speaker = "アナ"
# 「もし本当に前会長が、気づかないうちからその日誌を持っていたとするなら……」
line = "「もし本当に前会長が、気づかないうちからその日誌を持っていたとするなら……」"

[[dialogue]]
speaker = "アナ"
# 「あるいはその日誌も前会長と共に<b>生まれた</b>……と考えることも、できるのではないかと思いまして」
line = "「あるいはその日誌も前会長と共に<b>生まれた</b>……と考えることも、できるのではないかと思いまして」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ほえー……でも確かに、この日誌に書かれているのは私の運命だとしたら……」
line = "「ほえー……でも確かに、この日誌に書かれているのは私の運命だとしたら……」"

[[dialogue]]
speaker = "アナ"
# 「いえ……忘れてください。非論理的な考えでした」
line = "「いえ……忘れてください。非論理的な考えでした」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そう？　面白い発想と思ったのに～」
line = "「そう？　面白い発想と思ったのに～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あ、そういえば。後ろのほうに『魔王』についてのページも追加されてたのよね。こっちは日付もなかったんだけど」
line = "「あ、そういえば。後ろのほうに『魔王』についてのページも追加されてたのよね。こっちは日付もなかったんだけど」"

[[dialogue]]
speaker = "アナ"
# 「ほう。それはどんな内容でしたか」
line = "「ほう。それはどんな内容でしたか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それがね～難しくてよくわかんなかったの。アナ読んで？」
line = "「それがね～難しくてよくわかんなかったの。アナ読んで？」"

[[dialogue]]
speaker = "アナ"
# 「仕方ありませんね……」
line = "「仕方ありませんね……」"

[[dialogue]]
speaker = "unk"
# アナはヴィーナスから日誌を借り受け、新たに増えたというページに目を通した。
line = "アナはヴィーナスから日誌を借り受け、新たに増えたというページに目を通した。"

[[dialogue]]
speaker = "アナ"
# 「『終焉を打ち砕きし魔王の真実は未だ偽りの悪に虚飾されている。この世界に根を張る日輪の図が、過去の因果を捻じ曲げているのだ』」
line = "「『終焉を打ち砕きし魔王の真実は未だ偽りの悪に虚飾されている。この世界に根を張る日輪の図が、過去の因果を捻じ曲げているのだ』」"

[[dialogue]]
speaker = "アナ"
# 「『真実を描いた月輪の図はどこかに隠されているという。私は、その在り処を求めるべく友の力を借りた』」
line = "「『真実を描いた月輪の図はどこかに隠されているという。私は、その在り処を求めるべく友の力を借りた』」"

[[dialogue]]
speaker = "アナ"
# 「これは……」
line = "「これは……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ね、よくわかんないでしょ？　この日誌、もうちょい私にもわかりやすく書いてくれたら完璧なんだけどな～」
line = "「ね、よくわかんないでしょ？　この日誌、もうちょい私にもわかりやすく書いてくれたら完璧なんだけどな～」"

[[dialogue]]
speaker = "unk"
# 肩をすくめるヴィーナスに対し、今回はアナのほうが目を大きくした。
line = "肩をすくめるヴィーナスに対し、今回はアナのほうが目を大きくした。"

[[dialogue]]
speaker = "アナ"
# 「……あの、前会長。これって、もしかして──」
line = "「……あの、前会長。これって、もしかして──」"
