[[dialogue]]
speaker = "unk"
# 第５話,ヨミへのプレゼントだぴょん！,B
line = "第５話,ヨミへのプレゼントだぴょん！,B"

[[dialogue]]
speaker = "ヴィーナス"
# 「ヨミヨミはどこかな～？　あ、いたいた」
line = "「ヨミヨミはどこかな～？　あ、いたいた」"

[[dialogue]]
speaker = "ヨミ"
# 「こやっ、お嬢様にメイド長。いらっしゃいませ、どのようなご用件でしょうか？」
line = "「こやっ、お嬢様にメイド長。いらっしゃいませ、どのようなご用件でしょうか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「任務管轄係のお仕事、お疲れ様ね」
line = "「任務管轄係のお仕事、お疲れ様ね」"

[[dialogue]]
speaker = "ヨミ"
# 「はいっ！　<b>クエスト受付嬢</b>のお仕事、頑張ってます♪」
line = "「はいっ！　<b>クエスト受付嬢</b>のお仕事、頑張ってます♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「まだその呼び方にこだわってるのね」
line = "「まだその呼び方にこだわってるのね」"

[[dialogue]]
speaker = "ヨミ"
# 「ええ、まあ。自分の中で定着してしまっていまして」
line = "「ええ、まあ。自分の中で定着してしまっていまして」"

[[dialogue]]
speaker = "ヨミ"
# 「それよりお２人は、どの様なご用件でしょう？」
line = "「それよりお２人は、どの様なご用件でしょう？」"

[[dialogue]]
speaker = "蘭美"
# 「違うわ、ヨミ。今日はそういうのじゃなくてね、皆にプレゼントを配って回っているのよ」
line = "「違うわ、ヨミ。今日はそういうのじゃなくてね、皆にプレゼントを配って回っているのよ」"

[[dialogue]]
speaker = "ヨミ"
# 「プレゼント、ですか？」
line = "「プレゼント、ですか？」"

[[dialogue]]
speaker = "蘭美"
# 「ええ。実はね──」
line = "「ええ。実はね──」"

[[dialogue]]
speaker = "ヨミ"
# 「なるほどです。それでお嬢様とメイド長の２人でクリスマスプレゼントを配っているんですね」
line = "「なるほどです。それでお嬢様とメイド長の２人でクリスマスプレゼントを配っているんですね」"

[[dialogue]]
speaker = "蘭美"
# 「そうよ。で、この人工戦闘服の能力を引き出すために、クリスマスの思い出を語ってもらっているってわけね」
line = "「そうよ。で、この人工戦闘服の能力を引き出すために、クリスマスの思い出を語ってもらっているってわけね」"

[[dialogue]]
speaker = "ヨミ"
# 「クリスマスの思い出……というと、やっぱり前回のクリスマスでしょうか……」
line = "「クリスマスの思い出……というと、やっぱり前回のクリスマスでしょうか……」"

[[dialogue]]
speaker = "ヨミ"
# 「大変でしたけど、今となってはとってもいい思い出です♪」
line = "「大変でしたけど、今となってはとってもいい思い出です♪」"

[[dialogue]]
speaker = "蘭美"
# 「新星寮に忍び込んで、寮長と戦うハメになってしまった、っていうアレね？」
line = "「新星寮に忍び込んで、寮長と戦うハメになってしまった、っていうアレね？」"

[[dialogue]]
speaker = "ヨミ"
# 「……………………」
line = "「……………………」"

[[dialogue]]
speaker = "ヨミ"
# 「がくがくぶるぶるがくがくぶるぶる──」
line = "「がくがくぶるぶるがくがくぶるぶる──」"

[[dialogue]]
speaker = "蘭美"
# 「気を確かに持ちなさい、ヨミ！」
line = "「気を確かに持ちなさい、ヨミ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「うふふ、ヨミヨミのトラウマが再発しちゃったみたいね～」
line = "「うふふ、ヨミヨミのトラウマが再発しちゃったみたいね～」"

[[dialogue]]
speaker = "ヨミ"
# 「笑い事じゃないですよ～！　わたし、お嬢様に巻き込まれたんですからね！」
line = "「笑い事じゃないですよ～！　わたし、お嬢様に巻き込まれたんですからね！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ごめんごめん。じゃあさ、他には何か面白い思い出はないの？」
line = "「ごめんごめん。じゃあさ、他には何か面白い思い出はないの？」"

[[dialogue]]
speaker = "ヨミ"
# 「他に、ですか……ええと……申し訳ありません、魔界に居た頃はクリスマスにあまり縁が無かったので」
line = "「他に、ですか……ええと……申し訳ありません、魔界に居た頃はクリスマスにあまり縁が無かったので」"

[[dialogue]]
speaker = "蘭美"
# 「あら、そうなの？」
line = "「あら、そうなの？」"

[[dialogue]]
speaker = "ヨミ"
# 「毎年クリスマスの時期は、年末に向けて神社のお仕事で大忙しだったんですよ」
line = "「毎年クリスマスの時期は、年末に向けて神社のお仕事で大忙しだったんですよ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ヨミヨミは巫女さんだから、まあ、そうなっちゃうか……」
line = "「ヨミヨミは巫女さんだから、まあ、そうなっちゃうか……」"

[[dialogue]]
speaker = "蘭美"
# 「お正月に向けての準備というのは、どんなことをしていたのかしら？」
line = "「お正月に向けての準備というのは、どんなことをしていたのかしら？」"

[[dialogue]]
speaker = "ヨミ"
# 「そうですね……煤払いだったり、お正月の飾りをしたり、お札や絵馬や破魔矢なんかを用意したり……」
line = "「そうですね……煤払いだったり、お正月の飾りをしたり、お札や絵馬や破魔矢なんかを用意したり……」"

[[dialogue]]
speaker = "ヨミ"
# 「あとは舞のためのお稽古もやってましたよ」
line = "「あとは舞のためのお稽古もやってましたよ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あれ？　でもヨミヨミの舞ってどうなんだっけ？　確か爆裂下手だって言ってたような……」
line = "「あれ？　でもヨミヨミの舞ってどうなんだっけ？　確か爆裂下手だって言ってたような……」"

[[dialogue]]
speaker = "ヨミ"
# 「こやっ！！？」
line = "「こやっ！！？」"

[[dialogue]]
speaker = "蘭美"
# 「確かにヨミの絶望的なリズム感では、まともに舞が踊れる気がしないわね」
line = "「確かにヨミの絶望的なリズム感では、まともに舞が踊れる気がしないわね」"

[[dialogue]]
speaker = "ヨミ"
# 「こややややっ！！　ひ、酷い言われようですっ！」
line = "「こややややっ！！　ひ、酷い言われようですっ！」"

[[dialogue]]
speaker = "ヨミ"
# 「確かにわたしの舞は未熟ですけど、それでも頑張ってるんです～っ！！」
line = "「確かにわたしの舞は未熟ですけど、それでも頑張ってるんです～っ！！」"

[[dialogue]]
speaker = "蘭美"
# 「ふふっ、まあまあ、これで機嫌を直してちょうだい。はい、プレゼント」
line = "「ふふっ、まあまあ、これで機嫌を直してちょうだい。はい、プレゼント」"

[[dialogue]]
speaker = "ヨミ"
# 「わわっ、ありがとうございます！」
line = "「わわっ、ありがとうございます！」"

[[dialogue]]
speaker = "蘭美"
# 「クリスマスに縁が無かったって言ってたけど、プレゼントを貰うのも初めてかしら？」
line = "「クリスマスに縁が無かったって言ってたけど、プレゼントを貰うのも初めてかしら？」"

[[dialogue]]
speaker = "ヨミ"
# 「あ、いえ、お父様とお母様から頂いたことはありますよ」
line = "「あ、いえ、お父様とお母様から頂いたことはありますよ」"

[[dialogue]]
speaker = "ヨミ"
# 「『サンタクロースさんに魔界まで来てもらうのは大変だから、私たちから代わりにプレゼントだよ』って」
line = "「『サンタクロースさんに魔界まで来てもらうのは大変だから、私たちから代わりにプレゼントだよ』って」"

[[dialogue]]
speaker = "ヨミ"
# 「でも、それ以外の人からプレゼントを頂いたのは初めてかもしれません、えへへ♪」
line = "「でも、それ以外の人からプレゼントを頂いたのは初めてかもしれません、えへへ♪」"

[[dialogue]]
speaker = "蘭美"
# 「光栄ね、気に入ってもらえるといいのだけど」
line = "「光栄ね、気に入ってもらえるといいのだけど」"

[[dialogue]]
speaker = "ヨミ"
# 「こやっ！？　手袋とマフラーじゃないですか！」
line = "「こやっ！？　手袋とマフラーじゃないですか！」"

[[dialogue]]
speaker = "蘭美"
# 「どうかしら？」
line = "「どうかしら？」"

[[dialogue]]
speaker = "ヨミ"
# 「とっても嬉しいです！」
line = "「とっても嬉しいです！」"

[[dialogue]]
speaker = "ヨミ"
# 「そうだ、クリスマスの思い出じゃないんですけど、手袋とマフラーを見ると、一緒に舞の練習をしていたお友達のことを思い出します」
line = "「そうだ、クリスマスの思い出じゃないんですけど、手袋とマフラーを見ると、一緒に舞の練習をしていたお友達のことを思い出します」"

[[dialogue]]
speaker = "ヨミ"
# 「休憩時間になるとストーブの周りに輪を作って、みーんな巫女服なのにマフラーを巻いて手袋をつけてて」
line = "「休憩時間になるとストーブの周りに輪を作って、みーんな巫女服なのにマフラーを巻いて手袋をつけてて」"

[[dialogue]]
speaker = "ヨミ"
# 「爆裂変な格好だねって、それが面白くて休憩で顔を合わせる度にみんな笑いが止まらなくて……ふふふっ♪」
line = "「爆裂変な格好だねって、それが面白くて休憩で顔を合わせる度にみんな笑いが止まらなくて……ふふふっ♪」"

[[dialogue]]
speaker = "蘭美"
# 「なによ、素敵な思い出じゃない」
line = "「なによ、素敵な思い出じゃない」"

[[dialogue]]
speaker = "ヨミ"
# 「はい、このプレゼントのおかげで思い出すことが出来ました」
line = "「はい、このプレゼントのおかげで思い出すことが出来ました」"

[[dialogue]]
speaker = "ヨミ"
# 「ありがとうございます。今年の初詣はこれをつけてお参りに行きますねっ♪」
line = "「ありがとうございます。今年の初詣はこれをつけてお参りに行きますねっ♪」"
