[[dialogue]]
speaker = "unk"
# 第２話,『女神との契約』,B
line = "第２話,『女神との契約』,B"

[[dialogue]]
speaker = "オオヒメ"
# 「では、お願いします。ルヴィネ様」
line = "「では、お願いします。ルヴィネ様」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ええ、わかったわ」
line = "「ええ、わかったわ」"

[[dialogue]]
speaker = "unk"
# 守護天使たちの会議が行われてから数日後、デネブよりルヴィネがやってきた。
line = "守護天使たちの会議が行われてから数日後、デネブよりルヴィネがやってきた。"

[[dialogue]]
speaker = "unk"
# オオヒメはマグダレナと共に先日の守護天使会議の報告を済ませると、早速ルヴィネに主従の契約を申し込んだ。
line = "オオヒメはマグダレナと共に先日の守護天使会議の報告を済ませると、早速ルヴィネに主従の契約を申し込んだ。"

[[dialogue]]
speaker = "ルヴィネ"
# 「これで、どうかしら？」
line = "「これで、どうかしら？」"

[[dialogue]]
speaker = "オオヒメ"
# 「問題なく……私の内にルヴィネ様との新たな繋がりが作られました」
line = "「問題なく……私の内にルヴィネ様との新たな繋がりが作られました」"

[[dialogue]]
speaker = "ルヴィネ"
# 「嬉しいわ。オオヒメ、今後ともお願いね」
line = "「嬉しいわ。オオヒメ、今後ともお願いね」"

[[dialogue]]
speaker = "オオヒメ"
# 「宜しくお願いします、次代の女神よ」
line = "「宜しくお願いします、次代の女神よ」"

[[dialogue]]
speaker = "マグダレナ"
# 「ではルヴィネ様、次は私と──」
line = "「ではルヴィネ様、次は私と──」"

[[dialogue]]
speaker = "オオヒメ"
# 「っ！？　な──！？」
line = "「っ！？　な──！？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「何が……起きたの？」
line = "「何が……起きたの？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「わ、私の身体が……小さく！？」
line = "「わ、私の身体が……小さく！？」"

[[dialogue]]
speaker = "マグダレナ"
# 「もしかしてこれは、新たな契約の影響でしょうか……？」
line = "「もしかしてこれは、新たな契約の影響でしょうか……？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「摂理への影響は？　守護天使としての力を失っていたりは、していない……わよね？」
line = "「摂理への影響は？　守護天使としての力を失っていたりは、していない……わよね？」"

[[dialogue]]
speaker = "マグダレナ"
# 「どうなのでしょうか、オオヒメ？」
line = "「どうなのでしょうか、オオヒメ？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「……身体は小さくなりましたが、守護天使としての力が失われたといったことはないようです」
line = "「……身体は小さくなりましたが、守護天使としての力が失われたといったことはないようです」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「摂理への影響もありません。ご安心ください、ルヴィネ様」
line = "「摂理への影響もありません。ご安心ください、ルヴィネ様」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……そう、よかったわ」
line = "「……そう、よかったわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「けれど、あなたをこんな姿にしてしまって。私が女神として未熟なせいね……ごめんなさい」
line = "「けれど、あなたをこんな姿にしてしまって。私が女神として未熟なせいね……ごめんなさい」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「お、落ち込まずとも大丈夫です！　ただ外見が変化しただけに過ぎないのですから！」
line = "「お、落ち込まずとも大丈夫です！　ただ外見が変化しただけに過ぎないのですから！」"

[[dialogue]]
speaker = "マグダレナ"
# 「そうですね。私やアルモタヘルもこの姿だけでなく『幼アバター』なるものを所持しています」
line = "「そうですね。私やアルモタヘルもこの姿だけでなく『幼アバター』なるものを所持しています」"

[[dialogue]]
speaker = "マグダレナ"
# 「小さい姿でしか得られない知見もありますし、この機会にいろいろ経験してみてはいかがでしょう？」
line = "「小さい姿でしか得られない知見もありますし、この機会にいろいろ経験してみてはいかがでしょう？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「そうだな！　女神ルヴィネ様、貴重な機会を頂き、ありがとうございます」
line = "「そうだな！　女神ルヴィネ様、貴重な機会を頂き、ありがとうございます」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ありがとう。オオヒメ、マグダレナ……」
line = "「ありがとう。オオヒメ、マグダレナ……」"

[[dialogue]]
speaker = "マグダレナ"
# 「そうです。オオヒメ、いっそあなたも附属校に通ってみませんか？」
line = "「そうです。オオヒメ、いっそあなたも附属校に通ってみませんか？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "マグダレナ"
# 「会長さまを通じてヘレナさまにお願いすれば、きっと手配してくださるでしょう」
line = "「会長さまを通じてヘレナさまにお願いすれば、きっと手配してくださるでしょう」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「そ、それはまあ……ヘレナ殿なら大喜びで手配してくれそうではあるが……」
line = "「そ、それはまあ……ヘレナ殿なら大喜びで手配してくれそうではあるが……」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「しかし良いのだろうか？　守護天使の面々がこぞって人の子らの真似事に興じていては……本来の役目に支障が出るのでは？」
line = "「しかし良いのだろうか？　守護天使の面々がこぞって人の子らの真似事に興じていては……本来の役目に支障が出るのでは？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「特に今は、世界がどのように転換していくか大事な時期だ。摂理の維持に注力し、未知の世界の危機に対して備えなければならないのではないか？」
line = "「特に今は、世界がどのように転換していくか大事な時期だ。摂理の維持に注力し、未知の世界の危機に対して備えなければならないのではないか？」"

[[dialogue]]
speaker = "マグダレナ"
# 「ええ、それは勿論、その通りでしょう」
line = "「ええ、それは勿論、その通りでしょう」"

[[dialogue]]
speaker = "マグダレナ"
# 「ですが、もうひとつ……『私たち』にしか出来ない、重要な役目があります」
line = "「ですが、もうひとつ……『私たち』にしか出来ない、重要な役目があります」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「重要な役目……？」
line = "「重要な役目……？」"

[[dialogue]]
speaker = "マグダレナ"
# 「それは、今、この世界に生きる人々の生を見て、知って、私たち自身が経験を積むことです」
line = "「それは、今、この世界に生きる人々の生を見て、知って、私たち自身が経験を積むことです」"

[[dialogue]]
speaker = "マグダレナ"
# 「これは霊体の<b>私たち</b>には出来なかったこと、ヒトの身体を得なければ出来なかったこと……今の<b>私たち</b>にしか出来ないことです」
line = "「これは霊体の<b>私たち</b>には出来なかったこと、ヒトの身体を得なければ出来なかったこと……今の<b>私たち</b>にしか出来ないことです」"

[[dialogue]]
speaker = "マグダレナ"
# 「あなたもそれを分かっているから、眠りから覚めた後、様々な場所に足を向け、積極的に人々と交流を持とうとしたのでしょう？」
line = "「あなたもそれを分かっているから、眠りから覚めた後、様々な場所に足を向け、積極的に人々と交流を持とうとしたのでしょう？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「……その通りだ。私もその考えには同意できる。重要なことであると理解している」
line = "「……その通りだ。私もその考えには同意できる。重要なことであると理解している」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「だが、やはり今は……最も重要な役目を疎かには出来ない」
line = "「だが、やはり今は……最も重要な役目を疎かには出来ない」"

[[dialogue]]
speaker = "マグダレナ"
# 「では期限付き、と言うことにしてはどうでしょう？」
line = "「では期限付き、と言うことにしてはどうでしょう？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「期限付き？」
line = "「期限付き？」"

[[dialogue]]
speaker = "マグダレナ"
# 「そうですね……２週間、その期間だけ集中して附属校に通う……短い期間であれば摂理の維持に支障が出ることはないでしょう」
line = "「そうですね……２週間、その期間だけ集中して附属校に通う……短い期間であれば摂理の維持に支障が出ることはないでしょう」"

[[dialogue]]
speaker = "マグダレナ"
# 「それに私たちは、こうしてヒトの形を得て生活を送っていますが、実際の私たちの本体はフィーニスの塔の内部に存在しています」
line = "「それに私たちは、こうしてヒトの形を得て生活を送っていますが、実際の私たちの本体はフィーニスの塔の内部に存在しています」"

[[dialogue]]
speaker = "マグダレナ"
# 「世界の摂理を司る役目を担っているのはその本体。２週間ほどであれば、分体である私たちが別な行動を取っていても問題はないはずです」
line = "「世界の摂理を司る役目を担っているのはその本体。２週間ほどであれば、分体である私たちが別な行動を取っていても問題はないはずです」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「むぅ、だが……だがな……」
line = "「むぅ、だが……だがな……」"

[[dialogue]]
speaker = "マグダレナ"
# 「まだ何か気にかかっていることがあるようですね？」
line = "「まだ何か気にかかっていることがあるようですね？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「我々は守護天使だ。守るべき対象である人々に混じって気軽に学園生活を送るなどあっていいのか？」
line = "「我々は守護天使だ。守るべき対象である人々に混じって気軽に学園生活を送るなどあっていいのか？」"

[[dialogue]]
speaker = "マグダレナ"
# 「あら、それに何の不都合があるのです？」
line = "「あら、それに何の不都合があるのです？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「今はヒトの形を取っているが、守護天使は本来、人々に畏れられる対象だ」
line = "「今はヒトの形を取っているが、守護天使は本来、人々に畏れられる対象だ」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「そのような者たちが日常の中に踏み入っては、とても心穏やかには過ごせまい」
line = "「そのような者たちが日常の中に踏み入っては、とても心穏やかには過ごせまい」"

[[dialogue]]
speaker = "マグダレナ"
# 「私は今も時折、アバターを使って附属校に通わせてもらっていますが、そのような事を気にしているヒトはいませんよ？」
line = "「私は今も時折、アバターを使って附属校に通わせてもらっていますが、そのような事を気にしているヒトはいませんよ？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「そう、なのか……？」
line = "「そう、なのか……？」"

[[dialogue]]
speaker = "マグダレナ"
# 「ええ。皆と変わらない、１人のクラスメイトとして親しくしてもらっています」
line = "「ええ。皆と変わらない、１人のクラスメイトとして親しくしてもらっています」"

[[dialogue]]
speaker = "マグダレナ"
# 「今の言葉で分かりました。オオヒメ、あなたはやはり附属校に通い、知見を広めるべきです」
line = "「今の言葉で分かりました。オオヒメ、あなたはやはり附属校に通い、知見を広めるべきです」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……マグダレナの言うことにも一理あるわね。オオヒメ、ものは試しということで、やってみてはどうかしら？」
line = "「……マグダレナの言うことにも一理あるわね。オオヒメ、ものは試しということで、やってみてはどうかしら？」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「むぅ……ルヴィネ様まで、そうおっしゃるなら」
line = "「むぅ……ルヴィネ様まで、そうおっしゃるなら」"

[[dialogue]]
speaker = "マグダレナ"
# 「決まりですね。ふふっ、クラスメイトが増えて嬉しいです♪」
line = "「決まりですね。ふふっ、クラスメイトが増えて嬉しいです♪」"

[[dialogue]]
speaker = "ルヴィネ"
# 「それにしても、附属校ね……」
line = "「それにしても、附属校ね……」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「附属校がどうかしたのですか？」
line = "「附属校がどうかしたのですか？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「極星学園には、まだ附属校がないわ。……だから近いうちに、視察させてもらおうと考えていたの」
line = "「極星学園には、まだ附属校がないわ。……だから近いうちに、視察させてもらおうと考えていたの」"

[[dialogue]]
speaker = "ルヴィネ"
# 「デネブは先のリクリエで、多くの星騎士が失われたわ」
line = "「デネブは先のリクリエで、多くの星騎士が失われたわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「今は平和な時代が訪れているけれど、いつまた世界が危機に見舞われるとも限らない」
line = "「今は平和な時代が訪れているけれど、いつまた世界が危機に見舞われるとも限らない」"

[[dialogue]]
speaker = "ルヴィネ"
# 「その時に向けて、新たな星騎士たちを育てていかなければならないわ」
line = "「その時に向けて、新たな星騎士たちを育てていかなければならないわ」"

[[dialogue]]
speaker = "マグダレナ"
# 「仰る通りだと思います」
line = "「仰る通りだと思います」"

[[dialogue]]
speaker = "マグダレナ"
# 「では、善は急げと申しますから、今から連絡を取ってみましょう」
line = "「では、善は急げと申しますから、今から連絡を取ってみましょう」"

[[dialogue]]
speaker = "ヘレナ"
# 「もちろん、承認だ！」
line = "「もちろん、承認だ！」"

[[dialogue]]
speaker = "ヘレナ"
# 「オオヒメ殿の転入手続きはすぐにでも済ませられる。その気であれば明日からでも通えるようにしておこう」
line = "「オオヒメ殿の転入手続きはすぐにでも済ませられる。その気であれば明日からでも通えるようにしておこう」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# 「か、感謝する」
line = "「か、感謝する」"

[[dialogue]]
speaker = "ヘレナ"
# 「そしてルヴィネ殿の視察の件だが、こちらも問題ない」
line = "「そしてルヴィネ殿の視察の件だが、こちらも問題ない」"

[[dialogue]]
speaker = "ヘレナ"
# 「期間は２週間でよいのか？　ひと月でも半年でも、お望みであればそれ以上でも構わないのだが」
line = "「期間は２週間でよいのか？　ひと月でも半年でも、お望みであればそれ以上でも構わないのだが」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ありがとう。貴女の協力に感謝するわ」
line = "「ありがとう。貴女の協力に感謝するわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「デネブでやり残した仕事があるもの。今回の滞在は、２週間でちょうどいいわ」
line = "「デネブでやり残した仕事があるもの。今回の滞在は、２週間でちょうどいいわ」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# （承認されるであろうとは予測していたが、こうもあっさり決まってしまうとは思わなかったぞ。トントン拍子とはこの事だな）
line = "（承認されるであろうとは予測していたが、こうもあっさり決まってしまうとは思わなかったぞ。トントン拍子とはこの事だな）"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# （それにしても守護天使である私が学園生活を送ることになるとは……）
line = "（それにしても守護天使である私が学園生活を送ることになるとは……）"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# （……学園生活？）
line = "（……学園生活？）"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# （待て、学園生活とは何だ？）
line = "（待て、学園生活とは何だ？）"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# （冷静になって考えてみると、私は『学園生活』という物について何も知らない……）
line = "（冷静になって考えてみると、私は『学園生活』という物について何も知らない……）"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# （急に不安になってきてしまった！　ど、どうすればいいのだ？）
line = "（急に不安になってきてしまった！　ど、どうすればいいのだ？）"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# （このままではまずい！　急いで学園生活の何たるかを学習しなくては！）
line = "（このままではまずい！　急いで学園生活の何たるかを学習しなくては！）"

[[dialogue]]
speaker = "ヘレナ"
# 「そうだ、良いことを思いついたぞ」
line = "「そうだ、良いことを思いついたぞ」"

[[dialogue]]
speaker = "ヘレナ"
# 「良い機会であるから、ルヴィネ殿も附属校へ通ってみてはいかがか？」
line = "「良い機会であるから、ルヴィネ殿も附属校へ通ってみてはいかがか？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "マグダレナ"
# 「まあ、それは素晴らしい考えです！　私たちと一緒に、学園生活を送ってみましょう！」
line = "「まあ、それは素晴らしい考えです！　私たちと一緒に、学園生活を送ってみましょう！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「い、いや、私の目的は附属校の視察！　今更附属生になって通うというのは、少し話が違ってくるでしょう！？」
line = "「い、いや、私の目的は附属校の視察！　今更附属生になって通うというのは、少し話が違ってくるでしょう！？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「それに私は極星学園の生徒よ、学園生活はそちらで十分に経験を積んでいるから！」
line = "「それに私は極星学園の生徒よ、学園生活はそちらで十分に経験を積んでいるから！」"

[[dialogue]]
speaker = "マグダレナ"
# 「こちらの附属校ではまた別な経験が得られるかもしれませんよ？」
line = "「こちらの附属校ではまた別な経験が得られるかもしれませんよ？」"

[[dialogue]]
speaker = "マグダレナ"
# 「実際に身を置いて経験することでしか得られない知見もある、そうは思いませんか？」
line = "「実際に身を置いて経験することでしか得られない知見もある、そうは思いませんか？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ぅ……」
line = "「ぅ……」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# （気が付けばこちらも大変なことになってきているな）
line = "（気が付けばこちらも大変なことになってきているな）"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# （だが、先ほど私はこのマグダレナの言い分に押し切られて、転入を決意した）
line = "（だが、先ほど私はこのマグダレナの言い分に押し切られて、転入を決意した）"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# （その際にルヴィネ様は『マグダレナに理がある』と納得していた。その手前、これは断り切れないだろう……）
line = "（その際にルヴィネ様は『マグダレナに理がある』と納得していた。その手前、これは断り切れないだろう……）"

[[dialogue]]
speaker = "ヘレナ"
# 「──聞いた話によると、ルヴィネ殿は今、女神を引き継ぐために経験を積んでいる最中であるとか」
line = "「──聞いた話によると、ルヴィネ殿は今、女神を引き継ぐために経験を積んでいる最中であるとか」"

[[dialogue]]
speaker = "ヘレナ"
# 「であればどうだろう？　物は試しに、こちらでも学園生活を送ってみてはいかがかな？」
line = "「であればどうだろう？　物は試しに、こちらでも学園生活を送ってみてはいかがかな？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「わ、わかったわよ。あなたたちの言い分もわかるし、覚悟を決めて視察の２週間、流星学園附属校に通う事にするわ」
line = "「わ、わかったわよ。あなたたちの言い分もわかるし、覚悟を決めて視察の２週間、流星学園附属校に通う事にするわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「けれど私の本分はあくまで視察だから。その事を理解しておきなさい、いいわね！」
line = "「けれど私の本分はあくまで視察だから。その事を理解しておきなさい、いいわね！」"

[[dialogue]]
speaker = "オオヒメ（幼少）"
# （やはり、こういう展開になってしまったか……）
line = "（やはり、こういう展開になってしまったか……）"

[[dialogue]]
speaker = "unk"
# 嘆息と共に、自らの状況を受け入れる。
line = "嘆息と共に、自らの状況を受け入れる。"

[[dialogue]]
speaker = "unk"
# こうして小さな体になってしまった守護天使オオヒメと、次代の女神ルヴィネは、半ば強引に流星学園附属校で学園生活を送ることになってしまったのだった。
line = "こうして小さな体になってしまった守護天使オオヒメと、次代の女神ルヴィネは、半ば強引に流星学園附属校で学園生活を送ることになってしまったのだった。"
