[[dialogue]]
speaker = "unk"
# 第３話,闘争を終えて,B
line = "第３話,闘争を終えて,B"

[[dialogue]]
speaker = "unk"
# 魔界──
line = "魔界──"

[[dialogue]]
speaker = "マトイ"
# 「ふー、ふーっ……！　なんとか──ここまで来れば、ひと安心……！？」
line = "「ふー、ふーっ……！　なんとか──ここまで来れば、ひと安心……！？」"

[[dialogue]]
speaker = "ユウリ"
# 「ああ。つっても、あたしから離れんなよ。まだ寒波はひっきりなしに襲ってくる」
line = "「ああ。つっても、あたしから離れんなよ。まだ寒波はひっきりなしに襲ってくる」"

[[dialogue]]
speaker = "unk"
# <ruby=セイファート>黒騎士</ruby>を打倒し、冥森林を脱した俺たちは、大急ぎでレゾフへの帰路を駆けていた。
line = "<ruby>黒騎士<rt>セイファート</rt></ruby>を打倒し、冥森林を脱した俺たちは、大急ぎでレゾフへの帰路を駆けていた。"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長……大丈夫ですか？」
line = "「緋宮会長……大丈夫ですか？」"

[[dialogue]]
speaker = "クロト"
# 「……ああ。大丈夫だ。少し、気持ちの整理をしていた」
line = "「……ああ。大丈夫だ。少し、気持ちの整理をしていた」"

[[dialogue]]
speaker = "unk"
# 学園長の件については──俺にとって、失ったものも大きかった。
line = "学園長の件については──俺にとって、失ったものも大きかった。"

[[dialogue]]
speaker = "unk"
# それでも、俺たちは無事に目的を達成することができた。
line = "それでも、俺たちは無事に目的を達成することができた。"

[[dialogue]]
speaker = "unk"
# 俺は、改めて隣を翔けるヴィーナスを見る。
line = "俺は、改めて隣を翔けるヴィーナスを見る。"

[[dialogue]]
speaker = "ヴィーナス"
# 「みんな……助けに来てくれてほんとにありがと！」
line = "「みんな……助けに来てくれてほんとにありがと！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「信じてたわよ。マトイも、サーシャさんも、フィオナもユウリもソフィアちゃんもドラ猫も──」
line = "「信じてたわよ。マトイも、サーシャさんも、フィオナもユウリもソフィアちゃんもドラ猫も──」"

[[dialogue]]
speaker = "サーシャ"
# 「あんな目に遭ったばかりなのに、ヴィーナスちゃんは相変わらずねえ」
line = "「あんな目に遭ったばかりなのに、ヴィーナスちゃんは相変わらずねえ」"

[[dialogue]]
speaker = "ソフィア"
# 「でも……本当によかったです。一時はどうなることかと」
line = "「でも……本当によかったです。一時はどうなることかと」"

[[dialogue]]
speaker = "ニャリオン"
# 「ちゃんとワガハイのことも名前で呼ぶニャン！」
line = "「ちゃんとワガハイのことも名前で呼ぶニャン！」"

[[dialogue]]
speaker = "ラティエ"
# 「はっはっは──若人たちの情熱を見ていると、つい昂ぶってしまうな」
line = "「はっはっは──若人たちの情熱を見ていると、つい昂ぶってしまうな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……あれ？　一人、知らない人いるんだけど……？」
line = "「……あれ？　一人、知らない人いるんだけど……？」"

[[dialogue]]
speaker = "クロト"
# 「話せば長く──は、ならないか。流星の学園長、ラティエさんだ」
line = "「話せば長く──は、ならないか。流星の学園長、ラティエさんだ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「流星の！？　あの、もっぱらフラついちゃ、人に仕事を丸投げしてるっていう、伝説のおサボりマスター……！？」
line = "「流星の！？　あの、もっぱらフラついちゃ、人に仕事を丸投げしてるっていう、伝説のおサボりマスター……！？」"

[[dialogue]]
speaker = "ラティエ"
# 「うむ。<ruby=せじん>世人</ruby>はそう呼ぶこともあるな」
line = "「うむ。<ruby>世人<rt>せじん</rt></ruby>はそう呼ぶこともあるな」"

[[dialogue]]
speaker = "ソフィア"
# 「そんなのを羨望の眼差しで見ないでください」
line = "「そんなのを羨望の眼差しで見ないでください」"

[[dialogue]]
speaker = "フィオナ"
# （やっぱりなんでも安請け合いするのはやめておきましょうか……）
line = "（やっぱりなんでも安請け合いするのはやめておきましょうか……）"

[[dialogue]]
speaker = "unk"
# そんなやり取りを交わしつつ、俺たちは寒々しい荒野を駆け抜けていく……。
line = "そんなやり取りを交わしつつ、俺たちは寒々しい荒野を駆け抜けていく……。"

[[dialogue]]
speaker = "フィオナ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "サーシャ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "クロト"
# 「……？　どうした、２人とも」
line = "「……？　どうした、２人とも」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうそう。さっきからなんかヘンじゃない？」
line = "「そうそう。さっきからなんかヘンじゃない？」"

[[dialogue]]
speaker = "unk"
# フィオナとサーシャ先輩が、やたらこっちをジロジロ見ていることに気づいた。
line = "フィオナとサーシャ先輩が、やたらこっちをジロジロ見ていることに気づいた。"

[[dialogue]]
speaker = "unk"
# 正確に言えば俺とヴィーナスのことを交互にチラチラと──
line = "正確に言えば俺とヴィーナスのことを交互にチラチラと──"

[[dialogue]]
speaker = "フィオナ"
# 「いえ、その……気になってやまないと申しますか」
line = "「いえ、その……気になってやまないと申しますか」"

[[dialogue]]
speaker = "サーシャ"
# 「似てる……のかしら？　うーん……あんまりそうは見えないけれど……」
line = "「似てる……のかしら？　うーん……あんまりそうは見えないけれど……」"

[[dialogue]]
speaker = "クロト"
# 「何のことです？」
line = "「何のことです？」"

[[dialogue]]
speaker = "ニャリオン"
# 「おニャーらが親娘だって話ニャンよ！　ワガハイもさすがにビックリ仰天ニャン！」
line = "「おニャーらが親娘だって話ニャンよ！　ワガハイもさすがにビックリ仰天ニャン！」"

[[dialogue]]
speaker = "クロト"
# 「ああ。そのことか」
line = "「ああ。そのことか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ま、平行世界での話だけどね」
line = "「ま、平行世界での話だけどね」"

[[dialogue]]
speaker = "マトイ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "マトイ"
# 「……あ、そうだ！　それ！　それなんなの！？　娘とか急に言いだして！？」
line = "「……あ、そうだ！　それ！　それなんなの！？　娘とか急に言いだして！？」"

[[dialogue]]
speaker = "サーシャ"
# 「忘れてたの？　マトイちゃん」
line = "「忘れてたの？　マトイちゃん」"

[[dialogue]]
speaker = "ユウリ"
# 「……？　さっきから何の話してんだ？　娘？　誰が？　誰の？」
line = "「……？　さっきから何の話してんだ？　娘？　誰が？　誰の？」"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナスが、俺の」
line = "「ヴィーナスが、俺の」"

[[dialogue]]
speaker = "ソフィア"
# 「はい！？」
line = "「はい！？」"

[[dialogue]]
speaker = "unk"
# 学園長の記憶を通じて──俺たちはデネブ・アルタイル・ベガという平行世界の理を知った。
line = "学園長の記憶を通じて──俺たちはデネブ・アルタイル・ベガという平行世界の理を知った。"

[[dialogue]]
speaker = "unk"
# この世界はアルタイル。
line = "この世界はアルタイル。"

[[dialogue]]
speaker = "unk"
# しかし九浄ヴィーナスという人間は、デネブ出身の緋宮クロトの娘。
line = "しかし九浄ヴィーナスという人間は、デネブ出身の緋宮クロトの娘。"

[[dialogue]]
speaker = "unk"
# 恐らくデネブの世界では、こちらより時間が進んでいるのだろう。
line = "恐らくデネブの世界では、こちらより時間が進んでいるのだろう。"

[[dialogue]]
speaker = "unk"
# そして、デネブの世界もまた、既に破滅したベガと同じ道筋を辿りかねない状況に陥っていた。
line = "そして、デネブの世界もまた、既に破滅したベガと同じ道筋を辿りかねない状況に陥っていた。"

[[dialogue]]
speaker = "unk"
# だからこそ彼女は、平行世界の中で最も若い、まだ無事なアルタイルの俺に<b>救い</b>を求めた……。
line = "だからこそ彼女は、平行世界の中で最も若い、まだ無事なアルタイルの俺に<b>救い</b>を求めた……。"

[[dialogue]]
speaker = "unk"
# 俺とヴィーナスは肌でこれらの相関関係を感じていたが、他のみんなからすると受け入れがたい事実だったかもしれない。
line = "俺とヴィーナスは肌でこれらの相関関係を感じていたが、他のみんなからすると受け入れがたい事実だったかもしれない。"

[[dialogue]]
speaker = "ユウリ"
# 「クロトが──この見た目で──ヴィーナスの……？　えぇぇ……！？　わ、わけわかんねえぞ……！」
line = "「クロトが──この見た目で──ヴィーナスの……？　えぇぇ……！？　わ、わけわかんねえぞ……！」"

[[dialogue]]
speaker = "ソフィア"
# 「<b>ここ</b>にいる新星会長さんじゃなく……ってことなんでしょうけど。それにしても、理解がなかなか……」
line = "「<b>ここ</b>にいる新星会長さんじゃなく……ってことなんでしょうけど。それにしても、理解がなかなか……」"

[[dialogue]]
speaker = "サーシャ"
# 「衝撃的よねえ」
line = "「衝撃的よねえ」"

[[dialogue]]
speaker = "ラティエ"
# 「ふふっ……実に面白い。数奇な縁もあるものだな」
line = "「ふふっ……実に面白い。数奇な縁もあるものだな」"

[[dialogue]]
speaker = "クロト"
# 「まだ謎は多いですけどね」
line = "「まだ謎は多いですけどね」"

[[dialogue]]
speaker = "unk"
# 平行世界をまたぐことはできない──という原則を、ヴィーナスがどうやって飛び越えたのかはまだわかっていない。
line = "平行世界をまたぐことはできない──という原則を、ヴィーナスがどうやって飛び越えたのかはまだわかっていない。"

[[dialogue]]
speaker = "unk"
# 残っている謎については、恐らくデネブの世界に真実が眠っているのだろう。
line = "残っている謎については、恐らくデネブの世界に真実が眠っているのだろう。"

[[dialogue]]
speaker = "マトイ"
# 「な、ならヴィーナスのお母さんは誰なの……！？」
line = "「な、ならヴィーナスのお母さんは誰なの……！？」"

[[dialogue]]
speaker = "ソフィア"
# 「新星会長の……お、奥さん……？」
line = "「新星会長の……お、奥さん……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ん～……そっちは思い出せないわねぇ。けど、ま、そのうちなんとかなるでしょ！」
line = "「ん～……そっちは思い出せないわねぇ。けど、ま、そのうちなんとかなるでしょ！」"

[[dialogue]]
speaker = "クロト"
# 「そうだな。今はヴィーナスが無事ならそれでいい」
line = "「そうだな。今はヴィーナスが無事ならそれでいい」"

[[dialogue]]
speaker = "マトイ"
# 「そ、そんなんでいいの……？」
line = "「そ、そんなんでいいの……？」"

[[dialogue]]
speaker = "unk"
# 実を言えば、昔……薄っすらと掴みかけたような記憶はある。
line = "実を言えば、昔……薄っすらと掴みかけたような記憶はある。"

[[dialogue]]
speaker = "unk"
# だが、必死に記憶の糸を辿ろうとも、それを鮮明に思い出せる気はしなかった。
line = "だが、必死に記憶の糸を辿ろうとも、それを鮮明に思い出せる気はしなかった。"

[[dialogue]]
speaker = "unk"
# 平行世界は交わらぬ可能性同士──どうやったって手の届かない域にある。
line = "平行世界は交わらぬ可能性同士──どうやったって手の届かない域にある。"

[[dialogue]]
speaker = "ラティエ"
# 「魔王覚醒──噂には聞いていた。御前試合という場で、得体の知れぬ実力を発揮した男子生徒がいたとな」
line = "「魔王覚醒──噂には聞いていた。御前試合という場で、得体の知れぬ実力を発揮した男子生徒がいたとな」"

[[dialogue]]
speaker = "ラティエ"
# 「よもやあれほどの力とは思わなかったが。私も一度、手合わせ願いたいものだ」
line = "「よもやあれほどの力とは思わなかったが。私も一度、手合わせ願いたいものだ」"

[[dialogue]]
speaker = "クロト"
# 「はは……恐縮です。学園長のお相手が務まるかはわかりませんが」
line = "「はは……恐縮です。学園長のお相手が務まるかはわかりませんが」"

[[dialogue]]
speaker = "マトイ"
# 「もう、緋宮くんはあの力を自在に引き出せるの……？」
line = "「もう、緋宮くんはあの力を自在に引き出せるの……？」"

[[dialogue]]
speaker = "クロト"
# 「ああ。ヴィーナスからの願いを通じて……魔王の器をどう発揮させればいいのか、完全に掴んだ」
line = "「ああ。ヴィーナスからの願いを通じて……魔王の器をどう発揮させればいいのか、完全に掴んだ」"

[[dialogue]]
speaker = "ユウリ"
# 「へへ、頼もしいな」
line = "「へへ、頼もしいな」"

[[dialogue]]
speaker = "クロト"
# 「もっとも──あれだけの窮地に立たされるまで眠りっぱなしだったのは、我ながら<ruby=じくじ>忸怩</ruby>たる思いだけどな」
line = "「もっとも──あれだけの窮地に立たされるまで眠りっぱなしだったのは、我ながら<ruby>忸怩<rt>じくじ</rt></ruby>たる思いだけどな」"

[[dialogue]]
speaker = "unk"
# 俺が最初から強ければ、そもそもヴィーナスを危険にさらすこともなく済んだはずなのに。
line = "俺が最初から強ければ、そもそもヴィーナスを危険にさらすこともなく済んだはずなのに。"

[[dialogue]]
speaker = "unk"
# そんな後悔を噛み締めていると、隣からドンと背中を叩かれた。
line = "そんな後悔を噛み締めていると、隣からドンと背中を叩かれた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「そんなの今さら気にしないの！　クロトはばっちり私の期待に応えてくれたじゃない！」
line = "「そんなの今さら気にしないの！　クロトはばっちり私の期待に応えてくれたじゃない！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロトこそ正真正銘本物の魔王！　それが証明できただけでも──私が来た甲斐あったってものだわ！」
line = "「クロトこそ正真正銘本物の魔王！　それが証明できただけでも──私が来た甲斐あったってものだわ！」"

[[dialogue]]
speaker = "サーシャ"
# 「ヴィーナスちゃんはブレないわねえ」
line = "「ヴィーナスちゃんはブレないわねえ」"

[[dialogue]]
speaker = "フィオナ"
# 「そのブレなさが、緋宮会長への信頼に繋がったわけですか……」
line = "「そのブレなさが、緋宮会長への信頼に繋がったわけですか……」"

[[dialogue]]
speaker = "クロト"
# 「ふう……俺はやっぱり、ヴィーナスに発破をかけられないと始まらないな」
line = "「ふう……俺はやっぱり、ヴィーナスに発破をかけられないと始まらないな」"

[[dialogue]]
speaker = "unk"
# 正直、俺としても理屈が理解できただけで、ヴィーナスに対しての印象までは変わらない。
line = "正直、俺としても理屈が理解できただけで、ヴィーナスに対しての印象までは変わらない。"

[[dialogue]]
speaker = "unk"
# だから今後も、今までのように振り回されるんだろうなと思った。
line = "だから今後も、今までのように振り回されるんだろうなと思った。"

[[dialogue]]
speaker = "ニャリオン"
# 「あの時のおニャーからは……先代魔王の気配すら感じたニャン。末恐ろしいニャン」
line = "「あの時のおニャーからは……先代魔王の気配すら感じたニャン。末恐ろしいニャン」"

[[dialogue]]
speaker = "ラティエ"
# 「ほう。先代魔王というと──大聖堂の壁画にあった人物か？」
line = "「ほう。先代魔王というと──大聖堂の壁画にあった人物か？」"

[[dialogue]]
speaker = "フィオナ"
# 「いえ。私の家にある壁画のほうです」
line = "「いえ。私の家にある壁画のほうです」"

[[dialogue]]
speaker = "ラティエ"
# 「あちらか。察するに、英雄視のほうが真実というわけかな」
line = "「あちらか。察するに、英雄視のほうが真実というわけかな」"

[[dialogue]]
speaker = "ユウリ"
# 「そういやこの前はなんか大ボラこいてたな。先代魔王に仕えた大賢者だとか、なんとか」
line = "「そういやこの前はなんか大ボラこいてたな。先代魔王に仕えた大賢者だとか、なんとか」"

[[dialogue]]
speaker = "ニャリオン"
# 「ホラではないニャン！　ワガハイの前世は事実、３０００年前の魔王に仕えし大賢者なのニャン」
line = "「ホラではないニャン！　ワガハイの前世は事実、３０００年前の魔王に仕えし大賢者なのニャン」"

[[dialogue]]
speaker = "ニャリオン"
# 「そしてあの姿の新星会長からは……前世で浴びたのと同じ波動を感じたニャン」
line = "「そしてあの姿の新星会長からは……前世で浴びたのと同じ波動を感じたニャン」"

[[dialogue]]
speaker = "ニャリオン"
# 「ただの霊力の発露……というだけではニャかったニャン」
line = "「ただの霊力の発露……というだけではニャかったニャン」"

[[dialogue]]
speaker = "クロト"
# 「先代魔王ってのはどんな人だったんだ？」
line = "「先代魔王ってのはどんな人だったんだ？」"

[[dialogue]]
speaker = "ニャリオン"
# 「ぜんぜん覚えてないニャン！」
line = "「ぜんぜん覚えてないニャン！」"

[[dialogue]]
speaker = "ユウリ"
# 「なんつー名前だったか？」
line = "「なんつー名前だったか？」"

[[dialogue]]
speaker = "ニャリオン"
# 「えーっと……」
line = "「えーっと……」"

[[dialogue]]
speaker = "クロト"
# 「ラクシス」
line = "「ラクシス」"

[[dialogue]]
speaker = "ニャリオン"
# 「それニャ！」
line = "「それニャ！」"

[[dialogue]]
speaker = "ソフィア"
# 「本当に覚えているんですか？」
line = "「本当に覚えているんですか？」"

[[dialogue]]
speaker = "フィオナ"
# 「星見家の祖にあたる人物ですね」
line = "「星見家の祖にあたる人物ですね」"

[[dialogue]]
speaker = "unk"
# 無論、その名は表向きには知られていない。
line = "無論、その名は表向きには知られていない。"

[[dialogue]]
speaker = "unk"
# だからこそ『月の壁画』と共に、先代魔王の真実は星見家によって守られ続けてきた。
line = "だからこそ『月の壁画』と共に、先代魔王の真実は星見家によって守られ続けてきた。"

[[dialogue]]
speaker = "ユウリ"
# 「ドラ猫のフカシだろ。なんで３０００年も前の大賢者が、今ここにいるんだよ」
line = "「ドラ猫のフカシだろ。なんで３０００年も前の大賢者が、今ここにいるんだよ」"

[[dialogue]]
speaker = "ニャリオン"
# 「そ、それはフィオナ嬢によって召喚されたからに決まってるニャン！」
line = "「そ、それはフィオナ嬢によって召喚されたからに決まってるニャン！」"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャからこそ──大賢者を呼び寄せたフィオナ嬢こそ真の魔王の血統というわけニャン。フィーニスの塔でもそう言われてたニャン」
line = "「ニャからこそ──大賢者を呼び寄せたフィオナ嬢こそ真の魔王の血統というわけニャン。フィーニスの塔でもそう言われてたニャン」"

[[dialogue]]
speaker = "ユウリ"
# 「そうなのか？　フィオナ」
line = "「そうなのか？　フィオナ」"

[[dialogue]]
speaker = "フィオナ"
# 「ええと……どうでしょう。私も、ニャリオンを召喚した時はまだ幼い時分でしたから……大賢者というのはこの間が初耳でした」
line = "「ええと……どうでしょう。私も、ニャリオンを召喚した時はまだ幼い時分でしたから……大賢者というのはこの間が初耳でした」"

[[dialogue]]
speaker = "ソフィア"
# 「ますます疑わしいですね」
line = "「ますます疑わしいですね」"

[[dialogue]]
speaker = "ニャリオン"
# 「ワガハイの前世はしかと魂に刻み込まれているのニャン！　信じるニャンよ！」
line = "「ワガハイの前世はしかと魂に刻み込まれているのニャン！　信じるニャンよ！」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふふ。私はニャリオンちゃんの言うことなら信じるわよ」
line = "「ふふふ。私はニャリオンちゃんの言うことなら信じるわよ」"

[[dialogue]]
speaker = "クロト"
# （３０００年前の──リクリエを退けた魔王、か）
line = "（３０００年前の──リクリエを退けた魔王、か）"

[[dialogue]]
speaker = "unk"
# 太陽の壁画という偽りの歴史で塗り潰されてしまった真の英雄。
line = "太陽の壁画という偽りの歴史で塗り潰されてしまった真の英雄。"

[[dialogue]]
speaker = "unk"
# 果たして、彼はどんな人物だったのか……俺は無性に気になってしまった。
line = "果たして、彼はどんな人物だったのか……俺は無性に気になってしまった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ま、なんでもいいわ。クロトもフィオナも同じ魔王の一族ってことなら、パワーはさらに倍ってことでしょ！」
line = "「ま、なんでもいいわ。クロトもフィオナも同じ魔王の一族ってことなら、パワーはさらに倍ってことでしょ！」"

[[dialogue]]
speaker = "クロト"
# 「ああ。俺たちがリベンジを果たせたのも……二人で高め合えたおかげだしな」
line = "「ああ。俺たちがリベンジを果たせたのも……二人で高め合えたおかげだしな」"

[[dialogue]]
speaker = "サーシャ"
# 「フィオナちゃんも頑張ってくれたわ～♪」
line = "「フィオナちゃんも頑張ってくれたわ～♪」"

[[dialogue]]
speaker = "ラティエ"
# 「うむ。セイファートは剣士としても比類なき使い手──霊力とやらまで飲み込んだ状態の奴に、よく食らいついたものだ」
line = "「うむ。セイファートは剣士としても比類なき使い手──霊力とやらまで飲み込んだ状態の奴に、よく食らいついたものだ」"

[[dialogue]]
speaker = "ソフィア"
# 「フィオナ会長の勇姿……！　この目で見届けられなかったのが惜しいです」
line = "「フィオナ会長の勇姿……！　この目で見届けられなかったのが惜しいです」"

[[dialogue]]
speaker = "unk"
# 俺もフィオナも似たような存在──共に魔王としての『器』を有しているのは間違いない。
line = "俺もフィオナも似たような存在──共に魔王としての『器』を有しているのは間違いない。"

[[dialogue]]
speaker = "unk"
# しかし当のフィオナは……どこか物憂げに考え込む様子だった、
line = "しかし当のフィオナは……どこか物憂げに考え込む様子だった、"

[[dialogue]]
speaker = "フィオナ"
# （緋宮会長を最後のステージへ引き上げたのは……ヴィーナスさんという家族からの心の叫び……）
line = "（緋宮会長を最後のステージへ引き上げたのは……ヴィーナスさんという家族からの心の叫び……）"

[[dialogue]]
speaker = "フィオナ"
# （だとするなら……私にとっての、最後の鍵は……）
line = "（だとするなら……私にとっての、最後の鍵は……）"
