[[dialogue]]
speaker = "unk"
# 第１４話,女帝ＶＳ元星徒会,B
line = "第１４話,女帝ＶＳ元星徒会,B"

[[dialogue]]
speaker = "シノ"
# 「この映像は先日、新星星徒会がフィーニスの塔に登った際、ＤＩＳＣの自動撮影機能で録画したものです」
line = "「この映像は先日、新星星徒会がフィーニスの塔に登った際、ＤＩＳＣの自動撮影機能で録画したものです」"

[[dialogue]]
speaker = "シノ"
# 「未だ正体は不明ですが、新星星徒会によれば、このディザスターハンドがベガを滅亡させたとのことです」
line = "「未だ正体は不明ですが、新星星徒会によれば、このディザスターハンドがベガを滅亡させたとのことです」"

[[dialogue]]
speaker = "シノ"
# 「その力は、極星学園の刺客である香堂チナはもちろん、リクリエの使徒であったアポロよりも遥かに強大です」
line = "「その力は、極星学園の刺客である香堂チナはもちろん、リクリエの使徒であったアポロよりも遥かに強大です」"

[[dialogue]]
speaker = "シノ"
# 「残念ながら、私の言葉ではこの<b>手</b>の脅威を正確に表すに足りません。それほど桁外れに危険な存在です。ですが──」
line = "「残念ながら、私の言葉ではこの<b>手</b>の脅威を正確に表すに足りません。それほど桁外れに危険な存在です。ですが──」"

[[dialogue]]
speaker = "シノ"
# 「煌嶺殿はその力でキュリオスを統べる強者。他の誰でもないあなたが、この場で一番あれの脅威を理解しているのではないですか？」
line = "「煌嶺殿はその力でキュリオスを統べる強者。他の誰でもないあなたが、この場で一番あれの脅威を理解しているのではないですか？」"

[[dialogue]]
speaker = "煌嶺"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# 煌嶺は眉根を寄せてスクリーンを見つめたまま動かない。
line = "煌嶺は眉根を寄せてスクリーンを見つめたまま動かない。"

[[dialogue]]
speaker = "unk"
# シノの言う通り、映像越しでもその危険性を察したようだ。
line = "シノの言う通り、映像越しでもその危険性を察したようだ。"

[[dialogue]]
speaker = "シノ"
# 「ですが新星星徒会は、あのディザスターハンドを倒すつもりです」
line = "「ですが新星星徒会は、あのディザスターハンドを倒すつもりです」"

[[dialogue]]
speaker = "煌嶺"
# 「ほう……？」
line = "「ほう……？」"

[[dialogue]]
speaker = "シノ"
# 「ディザスターハンドとの戦いは、デネブに勝つよりも困難かもしれません」
line = "「ディザスターハンドとの戦いは、デネブに勝つよりも困難かもしれません」"

[[dialogue]]
speaker = "シノ"
# 「そのうえで、改めて煌嶺殿にお聞きします」
line = "「そのうえで、改めて煌嶺殿にお聞きします」"

[[dialogue]]
speaker = "シノ"
# 「ディザスターハンドに潰されるのに怯えながらデネブと戦うか、それとも<ruby=リクリエ>厄災</ruby>の化身たるディザスターハンドと戦うか。煌嶺殿はどちらがお好みですか？」
line = "「ディザスターハンドに潰されるのに怯えながらデネブと戦うか、それとも<ruby>厄災<rt>リクリエ</rt></ruby>の化身たるディザスターハンドと戦うか。煌嶺殿はどちらがお好みですか？」"

[[dialogue]]
speaker = "シノ"
# 「強大な敵から逃げ、弱い方を潰す……あなたが星騎士に求める強さとは、そんなものですか？」
line = "「強大な敵から逃げ、弱い方を潰す……あなたが星騎士に求める強さとは、そんなものですか？」"

[[dialogue]]
speaker = "unk"
# 真っ直ぐ煌嶺を見据え、シノは普段と変わらぬ平静さで問う。
line = "真っ直ぐ煌嶺を見据え、シノは普段と変わらぬ平静さで問う。"

[[dialogue]]
speaker = "unk"
# 一方煌嶺は、くつくつと笑ってていた。
line = "一方煌嶺は、くつくつと笑ってていた。"

[[dialogue]]
speaker = "煌嶺"
# 「ふふ……くっくっく……言うではないか、シノとやら。つまり貴殿は、ディザスターハンドと戦う方が、星騎士がより輝くと言うのだな？」
line = "「ふふ……くっくっく……言うではないか、シノとやら。つまり貴殿は、ディザスターハンドと戦う方が、星騎士がより輝くと言うのだな？」"

[[dialogue]]
speaker = "煌嶺"
# 「ふふふ……これは予想外だ。人間界の経営者などつまらぬものと思っていたが、なかなか酔狂ではないか」
line = "「ふふふ……これは予想外だ。人間界の経営者などつまらぬものと思っていたが、なかなか酔狂ではないか」"

[[dialogue]]
speaker = "煌嶺"
# 「だが口先だけでは無意味。守る戦いが星騎士の本質というならば、妾が直々にその輝きを試してやろう」
line = "「だが口先だけでは無意味。守る戦いが星騎士の本質というならば、妾が直々にその輝きを試してやろう」"

[[dialogue]]
speaker = "煌嶺"
# 「ただしノヴァフォームはなしだ。あれは魔王の力の一端ゆえに、星騎士の輝きを見るには適さぬ」
line = "「ただしノヴァフォームはなしだ。あれは魔王の力の一端ゆえに、星騎士の輝きを見るには適さぬ」"

[[dialogue]]
speaker = "シノ"
# 「そう仰ると思っていました。では──シルヴィさん」
line = "「そう仰ると思っていました。では──シルヴィさん」"

[[dialogue]]
speaker = "シルヴィ"
# 「はーい！　シルヴィ・グリムランド、いきまーす！」
line = "「はーい！　シルヴィ・グリムランド、いきまーす！」"

[[dialogue]]
speaker = "unk"
# 狭い会議室からアリーナへと場所を移し、煌嶺にシルヴィが対峙する。
line = "狭い会議室からアリーナへと場所を移し、煌嶺にシルヴィが対峙する。"

[[dialogue]]
speaker = "煌嶺"
# 「こやつは？」
line = "「こやつは？」"

[[dialogue]]
speaker = "シノ"
# 「前年度の星徒会において、副会長を務めたシルヴィ・グリムランドさんです」
line = "「前年度の星徒会において、副会長を務めたシルヴィ・グリムランドさんです」"

[[dialogue]]
speaker = "シノ"
# 「一時、分校の星騎士の指導のために学園を離れていましたが、その実力は指折り。新星学園を背負うに相応しい星騎士の１人と言えるでしょう」
line = "「一時、分校の星騎士の指導のために学園を離れていましたが、その実力は指折り。新星学園を背負うに相応しい星騎士の１人と言えるでしょう」"

[[dialogue]]
speaker = "シルヴィ"
# 「いやー、そこまで言われると照れちゃうなー」
line = "「いやー、そこまで言われると照れちゃうなー」"

[[dialogue]]
speaker = "シルヴィ"
# 「魔界のお偉いさんと戦ってって頼まれた時はびっくりしちゃったけど、新星学園がかかってるならやるっきゃないね！」
line = "「魔界のお偉いさんと戦ってって頼まれた時はびっくりしちゃったけど、新星学園がかかってるならやるっきゃないね！」"

[[dialogue]]
speaker = "シノ"
# 「頼みますね、シルヴィさん」
line = "「頼みますね、シルヴィさん」"

[[dialogue]]
speaker = "シルヴィ"
# 「うん、任せといて！」
line = "「うん、任せといて！」"

[[dialogue]]
speaker = "シルヴィ"
# 「で、あたしはどうすればいいの？」
line = "「で、あたしはどうすればいいの？」"

[[dialogue]]
speaker = "煌嶺"
# 「妾を打ち負かす必要はない。それは貴様ごときには不可能だ」
line = "「妾を打ち負かす必要はない。それは貴様ごときには不可能だ」"

[[dialogue]]
speaker = "シルヴィ"
# 「カッチーン！　ムカつくー！」
line = "「カッチーン！　ムカつくー！」"

[[dialogue]]
speaker = "シルヴィ"
# 「……って言いたいところだけど、そう言うだけの力はあるね。今まで戦った相手の中で一番強いって、見ただけでわかるよ」
line = "「……って言いたいところだけど、そう言うだけの力はあるね。今まで戦った相手の中で一番強いって、見ただけでわかるよ」"

[[dialogue]]
speaker = "煌嶺"
# 「一撃だ。それだけ妾の術に耐えてみせよ。それで星騎士の輝きを量る」
line = "「一撃だ。それだけ妾の術に耐えてみせよ。それで星騎士の輝きを量る」"

[[dialogue]]
speaker = "シルヴィ"
# 「オッケー！　いつでも来い！」
line = "「オッケー！　いつでも来い！」"

[[dialogue]]
speaker = "煌嶺"
# 「フ──」
line = "「フ──」"

[[dialogue]]
speaker = "unk"
# 煌嶺は手に持った扇を軽く横に払った。ただそれだけ。
line = "煌嶺は手に持った扇を軽く横に払った。ただそれだけ。"

[[dialogue]]
speaker = "シルヴィ"
# 「！？」
line = "「！？」"

[[dialogue]]
speaker = "unk"
# その瞬間、爆炎がシルヴィを包み込んだ。
line = "その瞬間、爆炎がシルヴィを包み込んだ。"

[[dialogue]]
speaker = "unk"
# 劫火に呑み込まれ、シルヴィの姿が一瞬消えるが──
line = "劫火に呑み込まれ、シルヴィの姿が一瞬消えるが──"

[[dialogue]]
speaker = "シルヴィ"
# 「アチチチ……ローストチキンの気分だよ～」
line = "「アチチチ……ローストチキンの気分だよ～」"

[[dialogue]]
speaker = "unk"
# 並の星騎士なら消し炭になる炎を、シルヴィは瞬時に星力の障壁を生み出して防御した。
line = "並の星騎士なら消し炭になる炎を、シルヴィは瞬時に星力の障壁を生み出して防御した。"

[[dialogue]]
speaker = "unk"
# 守りに長けたシルヴィでなければ、今の一撃で絶命していただろう。
line = "守りに長けたシルヴィでなければ、今の一撃で絶命していただろう。"

[[dialogue]]
speaker = "シルヴィ"
# 「はい、一撃耐えたよ。これで終わり──」
line = "「はい、一撃耐えたよ。これで終わり──」"

[[dialogue]]
speaker = "unk"
# シルヴィの表情が緩んだ瞬間、再び劫火がシルヴィを襲った。
line = "シルヴィの表情が緩んだ瞬間、再び劫火がシルヴィを襲った。"

[[dialogue]]
speaker = "煌嶺"
# 「すまぬ、さっきのはくしゃみだ」
line = "「すまぬ、さっきのはくしゃみだ」"

[[dialogue]]
speaker = "unk"
# 先ほどより激しく燃える炎がシルヴィを焼く。
line = "先ほどより激しく燃える炎がシルヴィを焼く。"

[[dialogue]]
speaker = "unk"
# だが──
line = "だが──"

[[dialogue]]
speaker = "シルヴィ"
# 「ふーっ、ギリギリセーフ！」
line = "「ふーっ、ギリギリセーフ！」"

[[dialogue]]
speaker = "シルヴィ"
# 「シノが『煌嶺はひねくれてるから気を付けろ』って、前もって言ってくれたおかげで助かったよ」
line = "「シノが『煌嶺はひねくれてるから気を付けろ』って、前もって言ってくれたおかげで助かったよ」"

[[dialogue]]
speaker = "unk"
# 煌嶺は一撃と言ったが、それはシルヴィの力を見るための方便に過ぎなかった。
line = "煌嶺は一撃と言ったが、それはシルヴィの力を見るための方便に過ぎなかった。"

[[dialogue]]
speaker = "unk"
# 己が欲のままに生き、奪う。それが頽廃都市キュリオスの女帝・煌嶺であり、つまるところ彼女を満足させなければ意味がない。
line = "己が欲のままに生き、奪う。それが頽廃都市キュリオスの女帝・煌嶺であり、つまるところ彼女を満足させなければ意味がない。"

[[dialogue]]
speaker = "unk"
# だがシノは煌嶺がどう動くかを予測し、シルヴィに助言を与えていた。
line = "だがシノは煌嶺がどう動くかを予測し、シルヴィに助言を与えていた。"

[[dialogue]]
speaker = "シルヴィ"
# 「ま、くしゃみならうっかり出ちゃっても仕方ないね。大丈夫？　鼻水出てない？」
line = "「ま、くしゃみならうっかり出ちゃっても仕方ないね。大丈夫？　鼻水出てない？」"

[[dialogue]]
speaker = "シルヴィ"
# 「あたしは一発なんてセコセコしたこと言わないからさ。気が済むまでくしゃみするといいよ、女帝陛下」
line = "「あたしは一発なんてセコセコしたこと言わないからさ。気が済むまでくしゃみするといいよ、女帝陛下」"

[[dialogue]]
speaker = "煌嶺"
# 「フッ──ではそうさせてもらおうか」
line = "「フッ──ではそうさせてもらおうか」"

[[dialogue]]
speaker = "シルヴィ"
# 「くぅっ……！」
line = "「くぅっ……！」"

[[dialogue]]
speaker = "unk"
# 煌嶺が遊ぶように扇を振るう度、骨も残さぬ劫火が巻き起こる。
line = "煌嶺が遊ぶように扇を振るう度、骨も残さぬ劫火が巻き起こる。"

[[dialogue]]
speaker = "unk"
# シルヴィは雷をまとわせたメイスで炎を相殺しつつ、星術の障壁で受け止めるが、その度に大量の星力を消耗し、顔から血の気が失われていく。
line = "シルヴィは雷をまとわせたメイスで炎を相殺しつつ、星術の障壁で受け止めるが、その度に大量の星力を消耗し、顔から血の気が失われていく。"

[[dialogue]]
speaker = "シルヴィ"
# （うっへぇ……火力ヤバッ！　ちょっとでも気を抜いたら丸焼きだよ！）
line = "（うっへぇ……火力ヤバッ！　ちょっとでも気を抜いたら丸焼きだよ！）"

[[dialogue]]
speaker = "シルヴィ"
# （ちゃんと防御してるはずなのに、その上から焼かれてヒリヒリするし、星力もめっちゃ使うし、かなりキツい……！）
line = "（ちゃんと防御してるはずなのに、その上から焼かれてヒリヒリするし、星力もめっちゃ使うし、かなりキツい……！）"

[[dialogue]]
speaker = "シルヴィ"
# （でもシノさんに声をかけられたのが、あたしでよかった。こんなに熱くてしんどい思いするのが、他の子じゃなくてよかった）
line = "（でもシノさんに声をかけられたのが、あたしでよかった。こんなに熱くてしんどい思いするのが、他の子じゃなくてよかった）"

[[dialogue]]
speaker = "シルヴィ"
# 「はぁ、はぁ……はあぁ……」
line = "「はぁ、はぁ……はあぁ……」"

[[dialogue]]
speaker = "煌嶺"
# 「どうした、息が切れているぞ。妾の気が済むまで付き合ってくれるのではなかったかな？」
line = "「どうした、息が切れているぞ。妾の気が済むまで付き合ってくれるのではなかったかな？」"

[[dialogue]]
speaker = "シルヴィ"
# 「大丈夫、全然へっちゃら！　これならドラム叩く方が疲れるよ！」
line = "「大丈夫、全然へっちゃら！　これならドラム叩く方が疲れるよ！」"

[[dialogue]]
speaker = "煌嶺"
# 「そうかそうか。もう終いかと心配したが、妾の杞憂であったようだな。そぅら、たらふく食らえ」
line = "「そうかそうか。もう終いかと心配したが、妾の杞憂であったようだな。そぅら、たらふく食らえ」"

[[dialogue]]
speaker = "シルヴィ"
# 「ッ……！！」
line = "「ッ……！！」"

[[dialogue]]
speaker = "シルヴィ"
# （また火力が上がった……！　割とマジで人生最大の危機かも……！）
line = "（また火力が上がった……！　割とマジで人生最大の危機かも……！）"

[[dialogue]]
speaker = "シルヴィ"
# （でも──）
line = "（でも──）"

[[dialogue]]
speaker = "シルヴィ"
# 「新星学園を守ってほしいってどういうこと？　しかも今の星徒会じゃなくて、あたしに？」
line = "「新星学園を守ってほしいってどういうこと？　しかも今の星徒会じゃなくて、あたしに？」"

[[dialogue]]
speaker = "シノ"
# 「ええ。シルヴィ・グリムランドさん──あなたが最適だと、私は判断しました」
line = "「ええ。シルヴィ・グリムランドさん──あなたが最適だと、私は判断しました」"

[[dialogue]]
speaker = "シノ"
# 「このまま煌嶺さんが学園長になれば、新星学園の星騎士たちは、彼女の私兵としてデネブとの戦いに投入されるでしょう」
line = "「このまま煌嶺さんが学園長になれば、新星学園の星騎士たちは、彼女の私兵としてデネブとの戦いに投入されるでしょう」"

[[dialogue]]
speaker = "シノ"
# 「生徒の皆さんが何と戦うかは、みなさんが決めて、それが尊重される必要があると思うのです」
line = "「生徒の皆さんが何と戦うかは、みなさんが決めて、それが尊重される必要があると思うのです」"

[[dialogue]]
speaker = "シノ"
# 「しかし煌嶺さんが言葉だけで納得する確率はかなり低い。何らかの形で実力を試してくるはずです」
line = "「しかし煌嶺さんが言葉だけで納得する確率はかなり低い。何らかの形で実力を試してくるはずです」"

[[dialogue]]
speaker = "シノ"
# 「だから──あなたの力が必要なんです」
line = "「だから──あなたの力が必要なんです」"

[[dialogue]]
speaker = "シルヴィ"
# （学園長候補から呼ばれて、煌嶺の相手をしてほしいって言われた時はビックリしちゃった）
line = "（学園長候補から呼ばれて、煌嶺の相手をしてほしいって言われた時はビックリしちゃった）"

[[dialogue]]
speaker = "シルヴィ"
# （でも新星学園をあんなやつの好きにはさせない。会長くんやサーシャが星徒会として頑張っているんだから）
line = "（でも新星学園をあんなやつの好きにはさせない。会長くんやサーシャが星徒会として頑張っているんだから）"

[[dialogue]]
speaker = "シルヴィ"
# （それにあたしは、みんなを守るために戦ってる）
line = "（それにあたしは、みんなを守るために戦ってる）"

[[dialogue]]
speaker = "シルヴィ"
# （サーシャの隣で女神様に誓ったんだ。あたしがみんなを守るって……！）
line = "（サーシャの隣で女神様に誓ったんだ。あたしがみんなを守るって……！）"

[[dialogue]]
speaker = "シルヴィ"
# 「はぁ、はぁ……もう終わり？　アンコールならまだまだ受け付けてるよ」
line = "「はぁ、はぁ……もう終わり？　アンコールならまだまだ受け付けてるよ」"

[[dialogue]]
speaker = "unk"
# 本来ならとうに限界を迎えているはずのシルヴィ。
line = "本来ならとうに限界を迎えているはずのシルヴィ。"

[[dialogue]]
speaker = "unk"
# 全身は煤で汚れ、火傷を負っていない箇所がないくらいだが、シルヴィは気力と星力を振り絞って立ち続ける。
line = "全身は煤で汚れ、火傷を負っていない箇所がないくらいだが、シルヴィは気力と星力を振り絞って立ち続ける。"

[[dialogue]]
speaker = "煌嶺"
# 「ほう、なかなか持ちこたえるではないか。キュリオスでもここまで頑健な者はそういない」
line = "「ほう、なかなか持ちこたえるではないか。キュリオスでもここまで頑健な者はそういない」"

[[dialogue]]
speaker = "シルヴィ"
# 「へへっ、そいつはどうも。でも引き抜きはお断りだから」
line = "「へへっ、そいつはどうも。でも引き抜きはお断りだから」"

[[dialogue]]
speaker = "煌嶺"
# 「ではこれで最後だ。これまでは児戯。妾の<b>一撃</b>をくれてやる」
line = "「ではこれで最後だ。これまでは児戯。妾の<b>一撃</b>をくれてやる」"

[[dialogue]]
speaker = "unk"
# 九尾の１つから火の玉が放たれ、空中で弾けた。
line = "九尾の１つから火の玉が放たれ、空中で弾けた。"

[[dialogue]]
speaker = "シルヴィ"
# 「アステラ……！？　どうしてここに……！？」
line = "「アステラ……！？　どうしてここに……！？」"

[[dialogue]]
speaker = "煌嶺"
# 「あれは先日、我が尾に吸収したアステラだ」
line = "「あれは先日、我が尾に吸収したアステラだ」"

[[dialogue]]
speaker = "煌嶺"
# 「あのアステラを圧縮して貴様に叩き落とす。まともに受ければ跡形もなく消し飛ぶだろう」
line = "「あのアステラを圧縮して貴様に叩き落とす。まともに受ければ跡形もなく消し飛ぶだろう」"

[[dialogue]]
speaker = "煌嶺"
# 「どうする？　ここで妾に頭を垂れるなら、アステラを尾に戻してやるが」
line = "「どうする？　ここで妾に頭を垂れるなら、アステラを尾に戻してやるが」"

[[dialogue]]
speaker = "シルヴィ"
# 「答えは決まってる」
line = "「答えは決まってる」"

[[dialogue]]
speaker = "シルヴィ"
# 「──来いっ！！」
line = "「──来いっ！！」"

[[dialogue]]
speaker = "煌嶺"
# 「フ──よく言った」
line = "「フ──よく言った」"

[[dialogue]]
speaker = "煌嶺"
# 「さぁ、星の加護を受けし戦士よ。妾に抗ってみせよ──！」
line = "「さぁ、星の加護を受けし戦士よ。妾に抗ってみせよ──！」"

[[dialogue]]
speaker = "シルヴィ"
# （っ……くっ……体が、バラバラになりそう……！　でも新星学園のみんなのために、倒れるわけにはいかない……！）
line = "（っ……くっ……体が、バラバラになりそう……！　でも新星学園のみんなのために、倒れるわけにはいかない……！）"

[[dialogue]]
speaker = "シルヴィ"
# （我が守護星アヴィオールよ……！　サーシャ、蛍火ちゃん、みんな……力を貸して！）
line = "（我が守護星アヴィオールよ……！　サーシャ、蛍火ちゃん、みんな……力を貸して！）"

[[dialogue]]
speaker = "シルヴィ"
# 「おおおーーーーーっ！！」
line = "「おおおーーーーーっ！！」"

[[dialogue]]
speaker = "unk"
# 星騎士同士の戦いを想定して作られたアリーナの地面を、深々と抉る一撃。
line = "星騎士同士の戦いを想定して作られたアリーナの地面を、深々と抉る一撃。"

[[dialogue]]
speaker = "unk"
# だがクレーターのその中心で、傷だらけになりながらもシルヴィは立っていた。
line = "だがクレーターのその中心で、傷だらけになりながらもシルヴィは立っていた。"

[[dialogue]]
speaker = "シルヴィ"
# 「ふぅ、はぁ、はぁ……どんなもんだいっ！」
line = "「ふぅ、はぁ、はぁ……どんなもんだいっ！」"

[[dialogue]]
speaker = "煌嶺"
# 「──フ」
line = "「──フ」"

[[dialogue]]
speaker = "煌嶺"
# 「フハハハハッ！　よくぞ大欲の女帝から新星学園を守り切った！」
line = "「フハハハハッ！　よくぞ大欲の女帝から新星学園を守り切った！」"

[[dialogue]]
speaker = "煌嶺"
# 「シルヴィちゃん、カッコよかった！　星騎士のこと見直しちゃったよ！」
line = "「シルヴィちゃん、カッコよかった！　星騎士のこと見直しちゃったよ！」"

[[dialogue]]
speaker = "シルヴィ"
# 「うわ！？　キャラ変わった！？」
line = "「うわ！？　キャラ変わった！？」"

[[dialogue]]
speaker = "煌嶺"
# 「女の子にはいろんな顔があるからね～。ていうかいつも女帝モードだと、肩凝っちゃうでしょ」
line = "「女の子にはいろんな顔があるからね～。ていうかいつも女帝モードだと、肩凝っちゃうでしょ」"

[[dialogue]]
speaker = "シルヴィ"
# 「そういうもんなのかー……」
line = "「そういうもんなのかー……」"

[[dialogue]]
speaker = "煌嶺"
# 「守る戦いは理解できないけど、確かにあなたは輝いていた。だから学園長になるのはやめとくよ」
line = "「守る戦いは理解できないけど、確かにあなたは輝いていた。だから学園長になるのはやめとくよ」"

[[dialogue]]
speaker = "煌嶺"
# 「“欲しいものは手に入れる”──それが私の流儀だけど、手に入れるなら最高の状態じゃないと意味ないからね」
line = "「“欲しいものは手に入れる”──それが私の流儀だけど、手に入れるなら最高の状態じゃないと意味ないからね」"

[[dialogue]]
speaker = "シルヴィ"
# 「へへっ、そっかそっか。それじゃ、あたしがあぶり焼きになった甲斐があるってもんだ！」
line = "「へへっ、そっかそっか。それじゃ、あたしがあぶり焼きになった甲斐があるってもんだ！」"

[[dialogue]]
speaker = "シノ"
# 「ありがとうございます、シルヴィさん。あなたのおかげで新星学園は守られました。ですがお怪我の方は……」
line = "「ありがとうございます、シルヴィさん。あなたのおかげで新星学園は守られました。ですがお怪我の方は……」"

[[dialogue]]
speaker = "シルヴィ"
# 「大丈夫、フライドチキン食べて寝たら治るから！　現役の星徒会に怪我させるわけにはいかないし、あたしでよかったよ！」
line = "「大丈夫、フライドチキン食べて寝たら治るから！　現役の星徒会に怪我させるわけにはいかないし、あたしでよかったよ！」"

[[dialogue]]
speaker = "シノ"
# 「それならよかったです。お元気そうで安心しました」
line = "「それならよかったです。お元気そうで安心しました」"

[[dialogue]]
speaker = "シルヴィ"
# 「あたしは元気が取り柄だからね。ま、煌嶺が本気出してたら、あたしは今頃黒焦げになってただろうけど」
line = "「あたしは元気が取り柄だからね。ま、煌嶺が本気出してたら、あたしは今頃黒焦げになってただろうけど」"

[[dialogue]]
speaker = "unk"
# 満身創痍のシルヴィに対し、煌嶺はあれだけの星術を使い、アステラさえ操ってみせたのに涼しい顔をしていた。
line = "満身創痍のシルヴィに対し、煌嶺はあれだけの星術を使い、アステラさえ操ってみせたのに涼しい顔をしていた。"

[[dialogue]]
speaker = "unk"
# 煌嶺にとっては、あれも準備運動程度でしかないのだろう。
line = "煌嶺にとっては、あれも準備運動程度でしかないのだろう。"

[[dialogue]]
speaker = "シノ"
# 「ところで煌嶺さんは、本当は平行世界を滅ぼす気はなかったのでしょう？　デネブを掌中に収めることこそあなたの目論見だった」
line = "「ところで煌嶺さんは、本当は平行世界を滅ぼす気はなかったのでしょう？　デネブを掌中に収めることこそあなたの目論見だった」"

[[dialogue]]
speaker = "煌嶺"
# 「な～んだ、バレてたんだ。そだよ、平行世界なんて“欲しい”に決まってるじゃん」
line = "「な～んだ、バレてたんだ。そだよ、平行世界なんて“欲しい”に決まってるじゃん」"

[[dialogue]]
speaker = "unk"
# 女の子の顔をした女帝がおかしそうに笑う。
line = "女の子の顔をした女帝がおかしそうに笑う。"

[[dialogue]]
speaker = "unk"
# 年相応の女の子の姿をしていても、その本質は大欲の権化に他ならない。
line = "年相応の女の子の姿をしていても、その本質は大欲の権化に他ならない。"

[[dialogue]]
speaker = "ヘレナ"
# 「煌嶺殿は辞退し、学園長の立候補者は十六夜シノ殿だけになった。では規則に則り、信任に足るか理事の投票を行う」
line = "「煌嶺殿は辞退し、学園長の立候補者は十六夜シノ殿だけになった。では規則に則り、信任に足るか理事の投票を行う」"

[[dialogue]]
speaker = "unk"
# 候補者は１人に絞られ、奇しくも星徒会長と同じく信任投票となった。
line = "候補者は１人に絞られ、奇しくも星徒会長と同じく信任投票となった。"

[[dialogue]]
speaker = "unk"
# 煌嶺と渡り合ったシノを拒む者はおらず、満票を得て、学園長に就任が決定したのだった。
line = "煌嶺と渡り合ったシノを拒む者はおらず、満票を得て、学園長に就任が決定したのだった。"
