[[dialogue]]
speaker = "unk"
# 第１３話,頂上で待つもの,B
line = "第１３話,頂上で待つもの,B"

[[dialogue]]
speaker = "unk"
# ガーディアンを倒しながら最短距離を進み、ようやく頂上に辿り着いた。
line = "ガーディアンを倒しながら最短距離を進み、ようやく頂上に辿り着いた。"

[[dialogue]]
speaker = "unk"
# だが……
line = "だが……"

[[dialogue]]
speaker = "クロト"
# 「さすがに疲れたな……」
line = "「さすがに疲れたな……」"

[[dialogue]]
speaker = "マトイ"
# 「だねー……」
line = "「だねー……」"

[[dialogue]]
speaker = "unk"
# フィーニスの塔は天高くそびえ、その頂上は天界すらも超える。物理的には繋がっていないはずの三界を貫く塔だ。
line = "フィーニスの塔は天高くそびえ、その頂上は天界すらも超える。物理的には繋がっていないはずの三界を貫く塔だ。"

[[dialogue]]
speaker = "unk"
# 前回の登頂時も、天井を破壊、ぶち抜いたところを飛翔してショートカットした。
line = "前回の登頂時も、天井を破壊、ぶち抜いたところを飛翔してショートカットした。"

[[dialogue]]
speaker = "unk"
# その時の穴がまだ修復されきってなかったため同じルートを飛んできたが、それでも流石に骨が折れた。
line = "その時の穴がまだ修復されきってなかったため同じルートを飛んできたが、それでも流石に骨が折れた。"

[[dialogue]]
speaker = "サーシャ"
# 「フィーニスの塔の中って普段は見られないから、私は楽しかったわ～」
line = "「フィーニスの塔の中って普段は見られないから、私は楽しかったわ～」"

[[dialogue]]
speaker = "アナ"
# 「ガーディアンが塔内部の修復を行っているところも見られました」
line = "「ガーディアンが塔内部の修復を行っているところも見られました」"

[[dialogue]]
speaker = "マトイ"
# 「あはは……」
line = "「あはは……」"

[[dialogue]]
speaker = "unk"
# 元々知的好奇心の強い２人にとっては、世界の深奥ともいえるフィーニスの塔内部は、興味をそそられるようだ。
line = "元々知的好奇心の強い２人にとっては、世界の深奥ともいえるフィーニスの塔内部は、興味をそそられるようだ。"

[[dialogue]]
speaker = "ヴィーナス"
# 「帰りが憂鬱ね～。ここまで来たからには情報持って帰るわよ！」
line = "「帰りが憂鬱ね～。ここまで来たからには情報持って帰るわよ！」"

[[dialogue]]
speaker = "unk"
# セイファート前学園長はここからベガを見た。デネブを見た。
line = "セイファート前学園長はここからベガを見た。デネブを見た。"

[[dialogue]]
speaker = "unk"
# ならば今の俺たちにも何か見えるはず──
line = "ならば今の俺たちにも何か見えるはず──"

[[dialogue]]
speaker = "クロト"
# 「──！？」
line = "「──！？」"

[[dialogue]]
speaker = "unk"
# 鋭い鉤爪に心臓を鷲掴みにされたような感覚。
line = "鋭い鉤爪に心臓を鷲掴みにされたような感覚。"

[[dialogue]]
speaker = "unk"
# 嫌な胸騒ぎがして左胸を押さえる。
line = "嫌な胸騒ぎがして左胸を押さえる。"

[[dialogue]]
speaker = "unk"
# 冷や汗が噴き出る。動悸が激しい。頭がズキズキと痛くて割れそうだ。
line = "冷や汗が噴き出る。動悸が激しい。頭がズキズキと痛くて割れそうだ。"

[[dialogue]]
speaker = "クロト"
# 「はぁ……はぁ……」
line = "「はぁ……はぁ……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロト、どうしたの！？　大丈夫！？」
line = "「クロト、どうしたの！？　大丈夫！？」"

[[dialogue]]
speaker = "クロト"
# 「ダメだ──来る──！！」
line = "「ダメだ──来る──！！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「！！？」
line = "「！！？」"

[[dialogue]]
speaker = "unk"
# 塔の頂上に突如現れたのは、かつてアポロを助けた巨大な手。
line = "塔の頂上に突如現れたのは、かつてアポロを助けた巨大な手。"

[[dialogue]]
speaker = "unk"
# ただの一撃で、しかも指の一本でフィオナを打ち倒した謎の敵。
line = "ただの一撃で、しかも指の一本でフィオナを打ち倒した謎の敵。"

[[dialogue]]
speaker = "unk"
# それが今俺たちの前に現れ、その大きな<ruby=てのひら>掌</ruby>を広げていた。
line = "それが今俺たちの前に現れ、その大きな<ruby>掌<rt>てのひら</rt></ruby>を広げていた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あの時はよくも邪魔してくれたわね！」
line = "「あの時はよくも邪魔してくれたわね！」"

[[dialogue]]
speaker = "unk"
# ヴィーナスが星術で極大の光条を放つ。
line = "ヴィーナスが星術で極大の光条を放つ。"

[[dialogue]]
speaker = "unk"
# まるで虫にでも刺されたみたいに……いや虫刺されの方がまだ痕は大きかったか。<b>手</b>には焦げ跡ひとつ付かなかった。
line = "まるで虫にでも刺されたみたいに……いや虫刺されの方がまだ痕は大きかったか。<b>手</b>には焦げ跡ひとつ付かなかった。"

[[dialogue]]
speaker = "unk"
# <b>手</b>が自らを広げ、さながら虫を潰すかのように振り下ろされる。
line = "<b>手</b>が自らを広げ、さながら虫を潰すかのように振り下ろされる。"

[[dialogue]]
speaker = "ヴィーナス"
# 「──」
line = "「──」"

[[dialogue]]
speaker = "サーシャ"
# 「ダメね」
line = "「ダメね」"

[[dialogue]]
speaker = "アナ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "マトイ"
# 「みんな、私の後ろに──！」
line = "「みんな、私の後ろに──！」"

[[dialogue]]
speaker = "unk"
# 勝てない。敵わない。届かない。
line = "勝てない。敵わない。届かない。"

[[dialogue]]
speaker = "unk"
# 幾多の戦いを潜り抜けてきたからこそ理解し、忘我する。
line = "幾多の戦いを潜り抜けてきたからこそ理解し、忘我する。"

[[dialogue]]
speaker = "unk"
# 圧倒的などという言葉ではとても足りない、絶望しかない力の差に──
line = "圧倒的などという言葉ではとても足りない、絶望しかない力の差に──"

[[dialogue]]
speaker = "梨緒"
# 「ライトニングテンペスト！」
line = "「ライトニングテンペスト！」"

[[dialogue]]
speaker = "unk"
# <b>手</b>の動きが一瞬止まった。
line = "<b>手</b>の動きが一瞬止まった。"

[[dialogue]]
speaker = "unk"
# 我に返って振り向くと、梨緒がクロスボウを構えていた。
line = "我に返って振り向くと、梨緒がクロスボウを構えていた。"

[[dialogue]]
speaker = "クロト"
# 「梨緒……！？」
line = "「梨緒……！？」"

[[dialogue]]
speaker = "梨緒"
# 「くっ……アレには勝てない！　逃げるぞ！」
line = "「くっ……アレには勝てない！　逃げるぞ！」"

[[dialogue]]
speaker = "クロト"
# 「ああ……！　新星星徒会、撤退だ！」
line = "「ああ……！　新星星徒会、撤退だ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「え、ええっ！」
line = "「え、ええっ！」"

[[dialogue]]
speaker = "unk"
# 敗北を認め、ただ生き延びるために全速力で飛ぶ。
line = "敗北を認め、ただ生き延びるために全速力で飛ぶ。"

[[dialogue]]
speaker = "unk"
# だが視界の遠くに、見慣れた場所の、見たことのない光景が映った。
line = "だが視界の遠くに、見慣れた場所の、見たことのない光景が映った。"

[[dialogue]]
speaker = "クロト"
# （あれは──）
line = "（あれは──）"

[[dialogue]]
speaker = "？？？"
# 「もう少しで勝てそうだったんだが……残念ながら俺はここまでのようだ」
line = "「もう少しで勝てそうだったんだが……残念ながら俺はここまでのようだ」"

[[dialogue]]
speaker = "unk"
# 息も絶え絶えに、傷ついた体を引き摺る青年。
line = "息も絶え絶えに、傷ついた体を引き摺る青年。"

[[dialogue]]
speaker = "unk"
# 出血がひどく、その言葉通り彼の命はあと数分と持たないだろう。
line = "出血がひどく、その言葉通り彼の命はあと数分と持たないだろう。"

[[dialogue]]
speaker = "unk"
# その顔は俺と瓜二つ。だが今の俺より大人びて見えた。
line = "その顔は俺と瓜二つ。だが今の俺より大人びて見えた。"

[[dialogue]]
speaker = "？？？"
# 「このままでは俺は──となるだろう。枝分かれした可能性の中に、そうなった──が見え──」
line = "「このままでは俺は──となるだろう。枝分かれした可能性の中に、そうなった──が見え──」"

[[dialogue]]
speaker = "？？？"
# 「だが俺の心も体もリクリエには──」
line = "「だが俺の心も体もリクリエには──」"

[[dialogue]]
speaker = "unk"
# 声にはノイズが混じって全部は聞こえない。
line = "声にはノイズが混じって全部は聞こえない。"

[[dialogue]]
speaker = "unk"
# だけど彼は不思議と落ち着いていて……
line = "だけど彼は不思議と落ち着いていて……"

[[dialogue]]
speaker = "？？？"
# 「道は俺が────娘の成長をこの目で見られないのは残念だが──元気に育ってくれるなら──」
line = "「道は俺が────娘の成長をこの目で見られないのは残念だが──元気に育ってくれるなら──」"

[[dialogue]]
speaker = "？？？"
# 「<ruby=ヴィーナス>娘</ruby>を頼んだぞ……ラク──」
line = "「<ruby>娘<rt>ヴィーナス</rt></ruby>を頼んだぞ……ラク──」"

[[dialogue]]
speaker = "unk"
# 次の瞬間、世界が弾けた。
line = "次の瞬間、世界が弾けた。"

[[dialogue]]
speaker = "unk"
# 遥か彼方の世界で起きた爆発が塔の頂上にまで届き、光に紛れて頂上を脱したのだった。
line = "遥か彼方の世界で起きた爆発が塔の頂上にまで届き、光に紛れて頂上を脱したのだった。"
