[[dialogue]]
speaker = "unk"
# 第１０話,芽吹きし魔王,B
line = "第１０話,芽吹きし魔王,B"

[[dialogue]]
speaker = "unk"
# そして俺たちはついに辿り着く──
line = "そして俺たちはついに辿り着く──"

[[dialogue]]
speaker = "unk"
# かつて盆地であり、今は森羅万象を融合させられた終焉の地へ。
line = "かつて盆地であり、今は森羅万象を融合させられた終焉の地へ。"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロト──ッ……！」
line = "「クロト──ッ……！」"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナス──！」
line = "「ヴィーナス──！」"

[[dialogue]]
speaker = "unk"
# 森の深奥では──全身を闇色の『檻』に囚われた彼女が、苦しそうに俺の名を叫んでいた。
line = "森の深奥では──全身を闇色の『檻』に囚われた彼女が、苦しそうに俺の名を叫んでいた。"

[[dialogue]]
speaker = "黒騎士"
# 『……想定外の来客だ。よもや<ruby=こちら>魔界</ruby>まで追いかけてくるとは──<ruby=ラーゴ・シエロ>鏡界の湖</ruby>は通れない時期のはずだが』
line = "『……想定外の来客だ。よもや<ruby>魔界<rt>こちら</rt></ruby>まで追いかけてくるとは──<ruby>鏡界の湖<rt>ラーゴ・シエロ</rt></ruby>は通れない時期のはずだが』"

[[dialogue]]
speaker = "クロト"
# 「ちょっとしたツテでね。まあ、帰り道の保証はないんだが」
line = "「ちょっとしたツテでね。まあ、帰り道の保証はないんだが」"

[[dialogue]]
speaker = "黒騎士"
# 『それに……ラクシャをも退けたか』
line = "『それに……ラクシャをも退けたか』"

[[dialogue]]
speaker = "クロト"
# 「友人に道を譲ってもらっただけだ。大したことじゃない」
line = "「友人に道を譲ってもらっただけだ。大したことじゃない」"

[[dialogue]]
speaker = "unk"
# 黒騎士の声音からは本気の驚きが感じられた。
line = "黒騎士の声音からは本気の驚きが感じられた。"

[[dialogue]]
speaker = "unk"
# 人間界にいるはずの俺たちが、数々の壁を越えてここへ来たのが信じられないようだ。
line = "人間界にいるはずの俺たちが、数々の壁を越えてここへ来たのが信じられないようだ。"

[[dialogue]]
speaker = "フィオナ"
# 「……ここが」
line = "「……ここが」"

[[dialogue]]
speaker = "サーシャ"
# 「ネメシス──」
line = "「ネメシス──」"

[[dialogue]]
speaker = "unk"
# そこは奇妙な森だった。
line = "そこは奇妙な森だった。"

[[dialogue]]
speaker = "unk"
# 子どもが乱雑に描いたような自然と生態系とが、おぞましい実体となって蠢いている。
line = "子どもが乱雑に描いたような自然と生態系とが、おぞましい実体となって蠢いている。"

[[dialogue]]
speaker = "マトイ"
# 「な、なんか両目から樹の生えた魔獣がいる……！」
line = "「な、なんか両目から樹の生えた魔獣がいる……！」"

[[dialogue]]
speaker = "ニャリオン"
# 「ひ、ひええ……上下さかさまのサソリが這ってるニャン……！？　足元もうねうね動いてるニャンよ……！」
line = "「ひ、ひええ……上下さかさまのサソリが這ってるニャン……！？　足元もうねうね動いてるニャンよ……！」"

[[dialogue]]
speaker = "クロト"
# 「──踏むな！　この森の由来からして……今も再構築の瘴気が<ruby=よど>澱</ruby>んでいる」
line = "「──踏むな！　この森の由来からして……今も再構築の瘴気が<ruby>澱<rt>よど</rt></ruby>んでいる」"

[[dialogue]]
speaker = "サーシャ"
# 「アステラとは比べ物にならない濃度……巻き込まれたら一巻の終わりね」
line = "「アステラとは比べ物にならない濃度……巻き込まれたら一巻の終わりね」"

[[dialogue]]
speaker = "unk"
# ここはリクリエに呑まれたものの末路──
line = "ここはリクリエに呑まれたものの末路──"

[[dialogue]]
speaker = "unk"
# かつてあったという盆地と、森と、魔獣とが、今もぐちゃぐちゃにかき回されている最中に違いない。
line = "かつてあったという盆地と、森と、魔獣とが、今もぐちゃぐちゃにかき回されている最中に違いない。"

[[dialogue]]
speaker = "クロト"
# 「だが……こうして林道を歩む分には大丈夫だ。大部分が、再構築の途中でフリーズしている」
line = "「だが……こうして林道を歩む分には大丈夫だ。大部分が、再構築の途中でフリーズしている」"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナスはきっとこの奥にいる。慎重に進むぞ、みんな」
line = "「ヴィーナスはきっとこの奥にいる。慎重に進むぞ、みんな」"

[[dialogue]]
speaker = "フィオナ"
# 「はい──！」
line = "「はい──！」"

[[dialogue]]
speaker = "黒騎士"
# 『なるほど……冥森林への侵入の機を、冬の大凍結に見出したか』
line = "『なるほど……冥森林への侵入の機を、冬の大凍結に見出したか』"

[[dialogue]]
speaker = "黒騎士"
# 『現地の魔族──いや。こちらの娘による手引きか？』
line = "『現地の魔族──いや。こちらの娘による手引きか？』"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふん……あんたが、よそ見してるうちに……ッ……教えた、だけよ……！　けほっ、こほっ……！」
line = "「ふん……あんたが、よそ見してるうちに……ッ……教えた、だけよ……！　けほっ、こほっ……！」"

[[dialogue]]
speaker = "サーシャ"
# 「ヴィーナスちゃん、無理しないで──！」
line = "「ヴィーナスちゃん、無理しないで──！」"

[[dialogue]]
speaker = "クロト"
# 「ああ。おかげで俺たちもここまで来れた──必ずそこから助けてやる」
line = "「ああ。おかげで俺たちもここまで来れた──必ずそこから助けてやる」"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロト……っ、みんな……！」
line = "「クロト……っ、みんな……！」"

[[dialogue]]
speaker = "unk"
# 俺たちとヴィーナスを分断するように立ちはだかる黒騎士。
line = "俺たちとヴィーナスを分断するように立ちはだかる黒騎士。"

[[dialogue]]
speaker = "unk"
# 奴を突破しない限り──背後に囚われたヴィーナスには手を出せない。
line = "奴を突破しない限り──背後に囚われたヴィーナスには手を出せない。"

[[dialogue]]
speaker = "クロト"
# 「面白い話をしていたな──リクリエの到来を待ち望んでるとかなんとか」
line = "「面白い話をしていたな──リクリエの到来を待ち望んでるとかなんとか」"

[[dialogue]]
speaker = "黒騎士"
# 『フッ……正確には新世界の創成だがな。“塔”の壁画を見たおまえ達なら、その意味がわかるだろう？』
line = "『フッ……正確には新世界の創成だがな。“塔”の壁画を見たおまえ達なら、その意味がわかるだろう？』"

[[dialogue]]
speaker = "フィオナ"
# 「……！　あなたも、ご存知なのですね──」
line = "「……！　あなたも、ご存知なのですね──」"

[[dialogue]]
speaker = "サーシャ"
# 「リクリエを望む者──アポロちゃんみたいな存在ってこと……？」
line = "「リクリエを望む者──アポロちゃんみたいな存在ってこと……？」"

[[dialogue]]
speaker = "黒騎士"
# 『私とあれは異なる存在だ。私はただ、一介の人間としてリクリエという現象を望んでいるのみ』
line = "『私とあれは異なる存在だ。私はただ、一介の人間としてリクリエという現象を望んでいるのみ』"

[[dialogue]]
speaker = "クロト"
# 「──人間、か。随分さらっと明かすんだな」
line = "「──人間、か。随分さらっと明かすんだな」"

[[dialogue]]
speaker = "ニャリオン"
# 「なら余計になぜニャ……！　世界が破滅したら、おミャーだってまとめて消えてしまうニャンよ！」
line = "「なら余計になぜニャ……！　世界が破滅したら、おミャーだってまとめて消えてしまうニャンよ！」"

[[dialogue]]
speaker = "黒騎士"
# 『そうだな。だが……それこそ私の望んだこと。森羅万象の終焉でしか、私の心の穴は埋められない』
line = "『そうだな。だが……それこそ私の望んだこと。森羅万象の終焉でしか、私の心の穴は埋められない』"

[[dialogue]]
speaker = "クロト"
# 「だから、<ruby=おれたち>星騎士</ruby>を敵視していると？」
line = "「だから、<ruby>星騎士<rt>おれたち</rt></ruby>を敵視していると？」"

[[dialogue]]
speaker = "黒騎士"
# 『一部的にはそう──が、いささか語弊があるな。<ruby=スターナイト>星騎士</ruby>──おまえ達程度の抵抗は本来、取るに足らない存在でしかなかった』
line = "『一部的にはそう──が、いささか語弊があるな。<ruby>星騎士<rt>スターナイト</rt></ruby>──おまえ達程度の抵抗は本来、取るに足らない存在でしかなかった』"

[[dialogue]]
speaker = "黒騎士"
# 『しかし──そこに揺らぎが生じた。デネブから飛来した一人の人間……そしてその者が所有していた日誌によってな』
line = "『しかし──そこに揺らぎが生じた。デネブから飛来した一人の人間……そしてその者が所有していた日誌によってな』"

[[dialogue]]
speaker = "マトイ"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……また人のことデブ、デブって──私、けっこうスリムなんですけど……！？」
line = "「……また人のことデブ、デブって──私、けっこうスリムなんですけど……！？」"

[[dialogue]]
speaker = "フィオナ"
# （デネブ……トリシャさんも口にしていた単語──）
line = "（デネブ……トリシャさんも口にしていた単語──）"

[[dialogue]]
speaker = "クロト"
# （トリシャさんによればこの世界は『アルタイル』──そしてヴィーナスは『デネブ』から来た存在──）
line = "（トリシャさんによればこの世界は『アルタイル』──そしてヴィーナスは『デネブ』から来た存在──）"

[[dialogue]]
speaker = "unk"
# どうやら黒騎士の目論見にとって──ヴィーナスとその日誌こそが計算外の<b>変数</b>だった。
line = "どうやら黒騎士の目論見にとって──ヴィーナスとその日誌こそが計算外の<b>変数</b>だった。"

[[dialogue]]
speaker = "unk"
# そして奴が欲することとやらもまた……その異世界とやらにあるらしい。
line = "そして奴が欲することとやらもまた……その異世界とやらにあるらしい。"

[[dialogue]]
speaker = "unk"
# いくつかのピースが頭の中で嵌まっていくが、それを整理している余裕はなかった。
line = "いくつかのピースが頭の中で嵌まっていくが、それを整理している余裕はなかった。"

[[dialogue]]
speaker = "クロト"
# 「──いいさ。不明瞭なことは多いが……おまえの個人的な事情にはさして興味もない」
line = "「──いいさ。不明瞭なことは多いが……おまえの個人的な事情にはさして興味もない」"

[[dialogue]]
speaker = "クロト"
# 「リクリエを望むなら望めばいい。嫌気がさして何もかも滅んでしまえばいいなんて、わかりやすい幼稚な理屈でしかないんだ」
line = "「リクリエを望むなら望めばいい。嫌気がさして何もかも滅んでしまえばいいなんて、わかりやすい幼稚な理屈でしかないんだ」"

[[dialogue]]
speaker = "クロト"
# 「だからこれ以上──おまえの御託に付き合う気はない。俺たちの大切な仲間を奪った落とし前はつけさせてもらうぞ」
line = "「だからこれ以上──おまえの御託に付き合う気はない。俺たちの大切な仲間を奪った落とし前はつけさせてもらうぞ」"

[[dialogue]]
speaker = "フィオナ"
# （緋宮会長……）
line = "（緋宮会長……）"

[[dialogue]]
speaker = "サーシャ"
# （本気で怒ってるわね……）
line = "（本気で怒ってるわね……）"

[[dialogue]]
speaker = "黒騎士"
# 『フ……フフフ！　なかなかの気概だ』
line = "『フ……フフフ！　なかなかの気概だ』"

[[dialogue]]
speaker = "黒騎士"
# 『だが……力が伴っていなければ、いかに勇猛な決意であろうと無意味！』
line = "『だが……力が伴っていなければ、いかに勇猛な決意であろうと無意味！』"

[[dialogue]]
speaker = "マトイ"
# 「ッ……この波動は……！」
line = "「ッ……この波動は……！」"

[[dialogue]]
speaker = "黒騎士"
# 『今度こそこの場で……<ruby=ほふ>屠</ruby>り去ってやろう。新世界の礎となれ』
line = "『今度こそこの場で……<ruby>屠<rt>ほふ</rt></ruby>り去ってやろう。新世界の礎となれ』"

[[dialogue]]
speaker = "黒騎士"
# 『<ruby=くら>昏</ruby>き断罪をここに下す──最終審判の時・闇の制裁』
line = "『<ruby>昏<rt>くら</rt></ruby>き断罪をここに下す──最終審判の時・闇の制裁』"

[[dialogue]]
speaker = "サーシャ"
# 「──ッ……！」
line = "「──ッ……！」"

[[dialogue]]
speaker = "ニャリオン"
# 「あ──あれが来るニャ！　に、逃げなきゃヤバイニャ──！」
line = "「あ──あれが来るニャ！　に、逃げなきゃヤバイニャ──！」"

[[dialogue]]
speaker = "unk"
# 前回なすすべなく<ruby=じゅうりん>蹂躙</ruby>された──黒き霊力の奔流が俺たちへ迫る。
line = "前回なすすべなく<ruby>蹂躙<rt>じゅうりん</rt></ruby>された──黒き霊力の奔流が俺たちへ迫る。"

[[dialogue]]
speaker = "unk"
# 何もかも闇の中へ呑まれる──その寸前。
line = "何もかも闇の中へ呑まれる──その寸前。"

[[dialogue]]
speaker = "フィオナ"
# 「──レイジングノヴァ」
line = "「──レイジングノヴァ」"

[[dialogue]]
speaker = "黒騎士"
# 『……！？』
line = "『……！？』"

[[dialogue]]
speaker = "マトイ"
# 「えっ──？」
line = "「えっ──？」"

[[dialogue]]
speaker = "unk"
# フィオナから拡散した光の波動が──深淵の闇を打ち払った。
line = "フィオナから拡散した光の波動が──深淵の闇を打ち払った。"

[[dialogue]]
speaker = "黒騎士"
# 『……なんだと』
line = "『……なんだと』"

[[dialogue]]
speaker = "フィオナ"
# 「確かに──以前のままの私たちでは、あなたに勝てませんでした。──ですが」
line = "「確かに──以前のままの私たちでは、あなたに勝てませんでした。──ですが」"

[[dialogue]]
speaker = "クロト"
# 「おまえと並び立つために……俺たちもできる限りのことを尽くしてきた」
line = "「おまえと並び立つために……俺たちもできる限りのことを尽くしてきた」"

[[dialogue]]
speaker = "マトイ"
# 「こ……これって……」
line = "「こ……これって……」"

[[dialogue]]
speaker = "ニャリオン"
# 「<ruby=クロスダスト>霊屑</ruby>と魔王の血が──共鳴しているニャン！」
line = "「<ruby>霊屑<rt>クロスダスト</rt></ruby>と魔王の血が──共鳴しているニャン！」"

[[dialogue]]
speaker = "unk"
# 最後に<ruby=ラクシャ>環</ruby>から譲り受けた霊屑によって──最後のピースが嵌まった。
line = "最後に<ruby>環<rt>ラクシャ</rt></ruby>から譲り受けた霊屑によって──最後のピースが嵌まった。"

[[dialogue]]
speaker = "unk"
# 闇の霊力──光の霊力──俺たちの血と共鳴するように、体の奥底から未知の力があふれ出す。
line = "闇の霊力──光の霊力──俺たちの血と共鳴するように、体の奥底から未知の力があふれ出す。"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長。あの時──黒騎士の振るっていた技を、覚えていますか？」
line = "「緋宮会長。あの時──黒騎士の振るっていた技を、覚えていますか？」"

[[dialogue]]
speaker = "クロト"
# 「嫌というほど。今も脳裏に焼き付いている」
line = "「嫌というほど。今も脳裏に焼き付いている」"

[[dialogue]]
speaker = "フィオナ"
# 「……なら」
line = "「……なら」"

[[dialogue]]
speaker = "クロト"
# 「ああ。俺が──あれを再現してみせる」
line = "「ああ。俺が──あれを再現してみせる」"

[[dialogue]]
speaker = "フィオナ"
# 「頼もしいです。なら私は──あれに打ち勝つ道筋を、なんとしても見出すとしましょう」
line = "「頼もしいです。なら私は──あれに打ち勝つ道筋を、なんとしても見出すとしましょう」"

[[dialogue]]
speaker = "unk"
# 俺たち魔王の系譜に託された霊力の残滓──<ruby=クロスダスト>霊屑</ruby>。
line = "俺たち魔王の系譜に託された霊力の残滓──<ruby>霊屑<rt>クロスダスト</rt></ruby>。"

[[dialogue]]
speaker = "unk"
# 失われし霊力を操る黒騎士に抗するためには、俺たちが同じ力を身につけるしかない。
line = "失われし霊力を操る黒騎士に抗するためには、俺たちが同じ力を身につけるしかない。"

[[dialogue]]
speaker = "unk"
# 普通の人間なら呑まれかねないというその塊を解放し──全身へとみなぎらせた。もう後戻りはできない。
line = "普通の人間なら呑まれかねないというその塊を解放し──全身へとみなぎらせた。もう後戻りはできない。"

[[dialogue]]
speaker = "フィオナ"
# 「さあ──最後の仕上げと参りましょう、緋宮会長」
line = "「さあ──最後の仕上げと参りましょう、緋宮会長」"

[[dialogue]]
speaker = "クロト"
# 「ああ──いくぞっ！」
line = "「ああ──いくぞっ！」"

[[dialogue]]
speaker = "フィオナ"
# 「来てください──はあああッ！！」
line = "「来てください──はあああッ！！」"

[[dialogue]]
speaker = "クロト＆フィオナ"
# 「<ruby=エーテル>最終審判の時</ruby>・<ruby=パニッシュメント>光の制裁</ruby>」
line = "「<ruby>最終審判の時<rt>エーテル</rt></ruby>・<ruby>光の制裁<rt>パニッシュメント</rt></ruby>」"

[[dialogue]]
speaker = "サーシャ"
# 「２人の秘密特訓の成果……実っていたのね──」
line = "「２人の秘密特訓の成果……実っていたのね──」"

[[dialogue]]
speaker = "黒騎士"
# 『ッ……！　霊力だと──なぜ──なぜ貴様たちが、その術を使える……！？』
line = "『ッ……！　霊力だと──なぜ──なぜ貴様たちが、その術を使える……！？』"

[[dialogue]]
speaker = "クロト"
# 「ゼロから習得したわけじゃない。ただ、信じてくれる仲間がいたんだ」
line = "「ゼロから習得したわけじゃない。ただ、信じてくれる仲間がいたんだ」"

[[dialogue]]
speaker = "クロト"
# 「三千年前──クルセイダースが用いた救世の武器。おまえが世界の破滅を願うというのなら、容赦なくこの力を振るえる」
line = "「三千年前──クルセイダースが用いた救世の武器。おまえが世界の破滅を願うというのなら、容赦なくこの力を振るえる」"

[[dialogue]]
speaker = "unk"
# 俺とフィオナ。２人の本来の力の源は星力だ。
line = "俺とフィオナ。２人の本来の力の源は星力だ。"

[[dialogue]]
speaker = "unk"
# しかし、<ruby=クロスダスト>霊屑</ruby>に宿った霊力を操り、星力と織り交ぜることで……俺たちの技の出力は未知なる混沌の領域にまで引き上げられた。
line = "しかし、<ruby>霊屑<rt>クロスダスト</rt></ruby>に宿った霊力を操り、星力と織り交ぜることで……俺たちの技の出力は未知なる混沌の領域にまで引き上げられた。"

[[dialogue]]
speaker = "unk"
# 「異なる力を混ぜ合わせ、より大きな力に転換できる」──これこそが、俺たちの血に宿る魔王の力！
line = "「異なる力を混ぜ合わせ、より大きな力に転換できる」──これこそが、俺たちの血に宿る魔王の力！"

[[dialogue]]
speaker = "クロト"
# 「俺たちは魔王だ──どんな血統も種族も、そして力だって併せのむ」
line = "「俺たちは魔王だ──どんな血統も種族も、そして力だって併せのむ」"

[[dialogue]]
speaker = "フィオナ"
# 「それは時として、大きな危険をも孕むのでしょう。いつかは世界を破滅に追いやってしまった魔王もいたとも聞きます」
line = "「それは時として、大きな危険をも孕むのでしょう。いつかは世界を破滅に追いやってしまった魔王もいたとも聞きます」"

[[dialogue]]
speaker = "フィオナ"
# 「しかし私たちは──どんな苦渋を舐めようとも、歩んでいきます。終焉から人々を救うのが──私たち<ruby=スターナイト>星騎士</ruby>なのですから」
line = "「しかし私たちは──どんな苦渋を舐めようとも、歩んでいきます。終焉から人々を救うのが──私たち<ruby>星騎士<rt>スターナイト</rt></ruby>なのですから」"

[[dialogue]]
speaker = "ニャリオン"
# 「フィオナ嬢……」
line = "「フィオナ嬢……」"

[[dialogue]]
speaker = "黒騎士"
# 『……フッ。フハハッハハハハハァッ！！』
line = "『……フッ。フハハッハハハハハァッ！！』"

[[dialogue]]
speaker = "黒騎士"
# 『いいだろう。星騎士たちよ──この手で貴様たちを滅し、果てなき終わりを迎えさせてやる！』
line = "『いいだろう。星騎士たちよ──この手で貴様たちを滅し、果てなき終わりを迎えさせてやる！』"

[[dialogue]]
speaker = "クロト"
# 「させない──ヴィーナスを返してもらう！」
line = "「させない──ヴィーナスを返してもらう！」"

[[dialogue]]
speaker = "ニャリオン"
# 「強烈な殺気──来るニャン！」
line = "「強烈な殺気──来るニャン！」"

[[dialogue]]
speaker = "サーシャ"
# 「全身全霊っ……会長くん達を援護するわよ！」
line = "「全身全霊っ……会長くん達を援護するわよ！」"

[[dialogue]]
speaker = "マトイ"
# 「了解です──新星星徒会、迎撃！」
line = "「了解です──新星星徒会、迎撃！」"

[[dialogue]]
speaker = "黒騎士"
# 『──むうううゥゥゥゥゥンッッ！！』
line = "『──むうううゥゥゥゥゥンッッ！！』"
