[[dialogue]]
speaker = "unk"
# 第１話,オルタナティブ宇宙,B
line = "第１話,オルタナティブ宇宙,B"

[[dialogue]]
speaker = "unk"
# 後に魔王──そして英雄と称されることになる青年ラクシス。
line = "後に魔王──そして英雄と称されることになる青年ラクシス。"

[[dialogue]]
speaker = "unk"
# <ruby=ラーゴ・シエロ>鏡界の湖</ruby>の渡し守であった彼はある日、湖のうねりに呑まれて沈んでしまう。
line = "<ruby>鏡界の湖<rt>ラーゴ・シエロ</rt></ruby>の渡し守であった彼はある日、湖のうねりに呑まれて沈んでしまう。"

[[dialogue]]
speaker = "unk"
# すると、彼の存在は数奇にも宇宙そのものを飛び越えてしまい──
line = "すると、彼の存在は数奇にも宇宙そのものを飛び越えてしまい──"

[[dialogue]]
speaker = "unk"
# 流星町という、見知らぬ異界の地へ降り立つのだった。
line = "流星町という、見知らぬ異界の地へ降り立つのだった。"

[[dialogue]]
speaker = "ラクシス"
# 「ここは……」
line = "「ここは……」"

[[dialogue]]
speaker = "unk"
# ラクシスはその場の異質さにすぐ勘づいた。
line = "ラクシスはその場の異質さにすぐ勘づいた。"

[[dialogue]]
speaker = "unk"
# 一見すると自分の知る人間界のどこかに見える。だが、<b>何かが違う</b>。
line = "一見すると自分の知る人間界のどこかに見える。だが、<b>何かが違う</b>。"

[[dialogue]]
speaker = "unk"
# 彼の勘は正しかった。
line = "彼の勘は正しかった。"

[[dialogue]]
speaker = "unk"
# そこは全く別の宇宙の──<ruby=オルタナティブ>新次元</ruby>な人間界だった。
line = "そこは全く別の宇宙の──<ruby>新次元<rt>オルタナティブ</rt></ruby>な人間界だった。"

[[dialogue]]
speaker = "ラクシス"
# 「どうして俺はここに……？　湖に溺れて、三界のどこでもない場所に出るなんて……」
line = "「どうして俺はここに……？　湖に溺れて、三界のどこでもない場所に出るなんて……」"

[[dialogue]]
speaker = "unk"
# 予想外の事態にラクシスは困惑した。
line = "予想外の事態にラクシスは困惑した。"

[[dialogue]]
speaker = "unk"
# 別の宇宙に迷い込んでしまった彼を待ち受けていたのは、ある青年との運命的な出会いだった。
line = "別の宇宙に迷い込んでしまった彼を待ち受けていたのは、ある青年との運命的な出会いだった。"

[[dialogue]]
speaker = "unk"
# その青年──名を仮にＳとしよう──はラクシスが異次元の来訪者であることをひと目で見抜き、彼を歓待した。
line = "その青年──名を仮にＳとしよう──はラクシスが異次元の来訪者であることをひと目で見抜き、彼を歓待した。"

[[dialogue]]
speaker = "unk"
# そしてＳとの交流を経て、ラクシスは多くの知見を得た。
line = "そしてＳとの交流を経て、ラクシスは多くの知見を得た。"

[[dialogue]]
speaker = "unk"
# 自分たちの世界に迫っている厄災が『リクリエ』と呼ばれる現象であること。
line = "自分たちの世界に迫っている厄災が『リクリエ』と呼ばれる現象であること。"

[[dialogue]]
speaker = "unk"
# また、ここ流星町でもかつて同じ現象が発生していたこと。
line = "また、ここ流星町でもかつて同じ現象が発生していたこと。"

[[dialogue]]
speaker = "unk"
# そして、その危機は『魔王』という存在によって食い止められたこと。
line = "そして、その危機は『魔王』という存在によって食い止められたこと。"

[[dialogue]]
speaker = "unk"
# 魔王とは、三種族を統べる唯一の存在であり、霊力と魔力の両用を可能にした器であること。
line = "魔王とは、三種族を統べる唯一の存在であり、霊力と魔力の両用を可能にした器であること。"

[[dialogue]]
speaker = "unk"
# そして最後に──青年Ｓこそリクリエを防いだ『魔王』そのものであることだった。
line = "そして最後に──青年Ｓこそリクリエを防いだ『魔王』そのものであることだった。"

[[dialogue]]
speaker = "ラクシス"
# 「魔王……！　間違いない。まさに俺の──いや、俺たちの求めていた存在だ」
line = "「魔王……！　間違いない。まさに俺の──いや、俺たちの求めていた存在だ」"

[[dialogue]]
speaker = "unk"
# ラクシスは英雄を切望していた。
line = "ラクシスは英雄を切望していた。"

[[dialogue]]
speaker = "unk"
# Ｓという人間は、まさしく彼にとって希望の光だった。
line = "Ｓという人間は、まさしく彼にとって希望の光だった。"

[[dialogue]]
speaker = "ラクシス"
# 「頼む──俺たちの世界を救ってくれ。そのリクリエという厄災が、こちらでも起きているんだ」
line = "「頼む──俺たちの世界を救ってくれ。そのリクリエという厄災が、こちらでも起きているんだ」"

[[dialogue]]
speaker = "unk"
# 切なる願い。しかし、Ｓは首を振った。
line = "切なる願い。しかし、Ｓは首を振った。"

[[dialogue]]
speaker = "unk"
# 『残念ながら……僕では君の世界へ踏み入ることができない』
line = "『残念ながら……僕では君の世界へ踏み入ることができない』"

[[dialogue]]
speaker = "unk"
# 『オルタナティブ宇宙間の移動。それは──こちらの常識でさえ、到底ありえないと思われていた離れ業なんだ』
line = "『オルタナティブ宇宙間の移動。それは──こちらの常識でさえ、到底ありえないと思われていた離れ業なんだ』"

[[dialogue]]
speaker = "ラクシス"
# 「なら、これは──俺だけの現象だっていうのか……？」
line = "「なら、これは──俺だけの現象だっていうのか……？」"

[[dialogue]]
speaker = "unk"
# 後に彼が知ることになる事実によれば──
line = "後に彼が知ることになる事実によれば──"

[[dialogue]]
speaker = "unk"
# 鏡界の湖に溺れた人間は通常、三界の揺らぎに巻き込まれて宇宙の真空へ投げ出される。
line = "鏡界の湖に溺れた人間は通常、三界の揺らぎに巻き込まれて宇宙の真空へ投げ出される。"

[[dialogue]]
speaker = "unk"
# そんな絶体絶命の運命を跳ね除け、ラクシスが流星町へ迷い込んだのは、彼だからこその特質だったという。
line = "そんな絶体絶命の運命を跳ね除け、ラクシスが流星町へ迷い込んだのは、彼だからこその特質だったという。"

[[dialogue]]
speaker = "unk"
# 『僕には今の君が、ひとつの<b>花</b>に見える』
line = "『僕には今の君が、ひとつの<b>花</b>に見える』"

[[dialogue]]
speaker = "ラクシス"
# 「花だって？　そんな柄じゃないさ」
line = "「花だって？　そんな柄じゃないさ」"

[[dialogue]]
speaker = "unk"
# 『印象の話じゃない。ただ、ラクシス。君の存在は……どこか重ね合わさって見えるんだ』
line = "『印象の話じゃない。ただ、ラクシス。君の存在は……どこか重ね合わさって見えるんだ』"

[[dialogue]]
speaker = "unk"
# Ｓは言った。
line = "Ｓは言った。"

[[dialogue]]
speaker = "unk"
# ラクシスという人物の存在感は、なぜか幾重にも重なった花びらのように映ると。
line = "ラクシスという人物の存在感は、なぜか幾重にも重なった花びらのように映ると。"

[[dialogue]]
speaker = "ラクシス"
# 「重ね合わさって……？　どういうことだ……？」
line = "「重ね合わさって……？　どういうことだ……？」"

[[dialogue]]
speaker = "unk"
# 『うん。これは僕の見立てだけど……君はいくつもの可能性の中から、か細い道筋を選び取ってここへ来たのかもしれない』
line = "『うん。これは僕の見立てだけど……君はいくつもの可能性の中から、か細い道筋を選び取ってここへ来たのかもしれない』"

[[dialogue]]
speaker = "unk"
# 『さっきも言ったよね。多次元宇宙間の移動なんて、本来はありえない。元の世界から投げ出されれば、どんな生命も無事じゃ済まないからだ』
line = "『さっきも言ったよね。多次元宇宙間の移動なんて、本来はありえない。元の世界から投げ出されれば、どんな生命も無事じゃ済まないからだ』"

[[dialogue]]
speaker = "unk"
# 『だけど君は、何千億分の一という奇蹟を起こして、このオルタナティブ宇宙へたどり着いた……』
line = "『だけど君は、何千億分の一という奇蹟を起こして、このオルタナティブ宇宙へたどり着いた……』"

[[dialogue]]
speaker = "unk"
# 単なる偶然では済ませられないとＳは言う。
line = "単なる偶然では済ませられないとＳは言う。"

[[dialogue]]
speaker = "unk"
# ラクシスには、そんな奇蹟を手ずから引き寄せることのできる素質があると。
line = "ラクシスには、そんな奇蹟を手ずから引き寄せることのできる素質があると。"

[[dialogue]]
speaker = "unk"
# 『花びらのように重ね合わさった君の存在がその証拠だ。今も君は、この場にいながらいくつもの可能性を<b>同時に</b>探っている』
line = "『花びらのように重ね合わさった君の存在がその証拠だ。今も君は、この場にいながらいくつもの可能性を<b>同時に</b>探っている』"

[[dialogue]]
speaker = "unk"
# 『そんな生命は見たことがない。宇宙に１人いるかいないかの特別な存在だと思う』
line = "『そんな生命は見たことがない。宇宙に１人いるかいないかの特別な存在だと思う』"

[[dialogue]]
speaker = "unk"
# 『平行する全ての可能性を切り<ruby=ひら>拓</ruby>く力──それは他の誰にもない、君だけのものだ』
line = "『平行する全ての可能性を切り<ruby>拓<rt>ひら</rt></ruby>く力──それは他の誰にもない、君だけのものだ』"

[[dialogue]]
speaker = "ラクシス"
# 「俺だけの……切り拓く、力……」
line = "「俺だけの……切り拓く、力……」"

[[dialogue]]
speaker = "unk"
# 特別なのは他ならぬ自分だった。
line = "特別なのは他ならぬ自分だった。"

[[dialogue]]
speaker = "unk"
# この不思議な巡り合わせも、己に起因したものだと知るラクシス。
line = "この不思議な巡り合わせも、己に起因したものだと知るラクシス。"

[[dialogue]]
speaker = "ラクシス"
# 「だが、なら結局……自分たちのことは自分たちで何とかするしかない、ってことか」
line = "「だが、なら結局……自分たちのことは自分たちで何とかするしかない、ってことか」"

[[dialogue]]
speaker = "unk"
# 悲嘆するラクシスに、『まだ手はある』とＳは言った。
line = "悲嘆するラクシスに、『まだ手はある』とＳは言った。"

[[dialogue]]
speaker = "unk"
# それは──Ｓに宿る魔王の因子をラクシスが預かり、元の世界へ持ち帰るという方法だった。
line = "それは──Ｓに宿る魔王の因子をラクシスが預かり、元の世界へ持ち帰るという方法だった。"

[[dialogue]]
speaker = "ラクシス"
# 「この石は……？」
line = "「この石は……？」"

[[dialogue]]
speaker = "unk"
# Ｓが手渡したのはひとつの水晶石だった。
line = "Ｓが手渡したのはひとつの水晶石だった。"

[[dialogue]]
speaker = "unk"
# Ｓは言った。リクリエの訪れる世界なら、自分のように魔王の資質を秘めた存在がいる。
line = "Ｓは言った。リクリエの訪れる世界なら、自分のように魔王の資質を秘めた存在がいる。"

[[dialogue]]
speaker = "unk"
# そして、魔王の因子が封入されたこの水晶石は、その人物に適合するはずだ──と。
line = "そして、魔王の因子が封入されたこの水晶石は、その人物に適合するはずだ──と。"

[[dialogue]]
speaker = "ラクシス"
# 「なるほど──魔王の因子だけを俺の宇宙へ持ち帰れるというわけか」
line = "「なるほど──魔王の因子だけを俺の宇宙へ持ち帰れるというわけか」"

[[dialogue]]
speaker = "ラクシス"
# 「助かった……！　これがあれば、元の世界でも英雄を探すことができる！」
line = "「助かった……！　これがあれば、元の世界でも英雄を探すことができる！」"

[[dialogue]]
speaker = "unk"
# Ｓより水晶石を受け取って、ラクシスは元の世界へ帰る。
line = "Ｓより水晶石を受け取って、ラクシスは元の世界へ帰る。"

[[dialogue]]
speaker = "unk"
# きっとこの因子に適合する──魔王の器にふさわしい人物がいると信じて。
line = "きっとこの因子に適合する──魔王の器にふさわしい人物がいると信じて。"

[[dialogue]]
speaker = "unk"
# だが──運命は彼をこのままで終わらせなかった。
line = "だが──運命は彼をこのままで終わらせなかった。"

[[dialogue]]
speaker = "unk"
# Ｓより授かった魔王の因子は、元の宇宙へ戻るやいなや、あろうことかラクシス本人へと適合してしまったのだ。
line = "Ｓより授かった魔王の因子は、元の宇宙へ戻るやいなや、あろうことかラクシス本人へと適合してしまったのだ。"

[[dialogue]]
speaker = "ラクシス"
# 「そんなバカな……これじゃ、俺が英雄ってことになってしまう」
line = "「そんなバカな……これじゃ、俺が英雄ってことになってしまう」"

[[dialogue]]
speaker = "unk"
# ラクシスは英雄を求めていた。
line = "ラクシスは英雄を求めていた。"

[[dialogue]]
speaker = "unk"
# しかし悪戯な運命は彼を別宇宙へと連れ去り、Ｓとの出会いを通じて、彼自身を英雄なる存在へと昇華させた。
line = "しかし悪戯な運命は彼を別宇宙へと連れ去り、Ｓとの出会いを通じて、彼自身を英雄なる存在へと昇華させた。"

[[dialogue]]
speaker = "ラクシス"
# 「俺が、魔王……ハハ……そんな大それた願いを抱いたわけじゃなかったんだけどな」
line = "「俺が、魔王……ハハ……そんな大それた願いを抱いたわけじゃなかったんだけどな」"

[[dialogue]]
speaker = "ラクシス"
# 「……でも……案外、歴史に残る英雄なんてのも──こういうものなのかもしれない」
line = "「……でも……案外、歴史に残る英雄なんてのも──こういうものなのかもしれない」"

[[dialogue]]
speaker = "unk"
# 彼はふと思った。
line = "彼はふと思った。"

[[dialogue]]
speaker = "unk"
# もしかするとＳは──こうなることまで予見していたのかもしれないと。
line = "もしかするとＳは──こうなることまで予見していたのかもしれないと。"

[[dialogue]]
speaker = "unk"
# 果たしてラクシスはこの現実を受け入れ、自らの使命を背負い込むことに決めた。
line = "果たしてラクシスはこの現実を受け入れ、自らの使命を背負い込むことに決めた。"

[[dialogue]]
speaker = "unk"
# 彼は魔王として──リクリエという厄災を撃ち倒すべく立ち上がった。
line = "彼は魔王として──リクリエという厄災を撃ち倒すべく立ち上がった。"

[[dialogue]]
speaker = "unk"
# オルタナティブ宇宙で得た知識をもとに、クルセイダースという戦士たちを組織した。
line = "オルタナティブ宇宙で得た知識をもとに、クルセイダースという戦士たちを組織した。"

[[dialogue]]
speaker = "unk"
# その軌跡は順風満帆ではなかった。
line = "その軌跡は順風満帆ではなかった。"

[[dialogue]]
speaker = "unk"
# 立ちはだかる天災に、魔獣たち……前人未到の試みゆえにラクシスへの反発勢力も少なくなかった。
line = "立ちはだかる天災に、魔獣たち……前人未到の試みゆえにラクシスへの反発勢力も少なくなかった。"

[[dialogue]]
speaker = "unk"
# 『バジュラ教団』と呼ばれる組織もその一つだった。
line = "『バジュラ教団』と呼ばれる組織もその一つだった。"

[[dialogue]]
speaker = "unk"
# 彼らは<ruby=リクリエ>厄災</ruby>を『天啓』と信じ、世界の真理を解き明かそうとする集団だった。
line = "彼らは<ruby>厄災<rt>リクリエ</rt></ruby>を『天啓』と信じ、世界の真理を解き明かそうとする集団だった。"

[[dialogue]]
speaker = "unk"
# 『リクリエは崇高なるチャカパラ様の啓示！』
line = "『リクリエは崇高なるチャカパラ様の啓示！』"

[[dialogue]]
speaker = "unk"
# 『チャカパラ神は、女神をも超越する“大宇宙”のご意思である！』
line = "『チャカパラ神は、女神をも超越する“大宇宙”のご意思である！』"

[[dialogue]]
speaker = "unk"
# バジュラ教団の教祖は怪しげな秘術を使い、黙示録なる伝道を通じて信者たちを率いた。
line = "バジュラ教団の教祖は怪しげな秘術を使い、黙示録なる伝道を通じて信者たちを率いた。"

[[dialogue]]
speaker = "unk"
# 地上の厄災は彼らの信奉する『チャカパラ様』によるもので、またリクリエの到来に応じてその神が降臨すると信じていた。
line = "地上の厄災は彼らの信奉する『チャカパラ様』によるもので、またリクリエの到来に応じてその神が降臨すると信じていた。"

[[dialogue]]
speaker = "ラクシス"
# 「すべての人間が人間の味方とは限らない──他の種族についても、同じことか」
line = "「すべての人間が人間の味方とは限らない──他の種族についても、同じことか」"

[[dialogue]]
speaker = "unk"
# クルセイダースに種族の壁はなかった。
line = "クルセイダースに種族の壁はなかった。"

[[dialogue]]
speaker = "unk"
# 天使が、魔族が、人間が──時に紛れ込んだ一人の魔女が──共に力を合わせて戦った。
line = "天使が、魔族が、人間が──時に紛れ込んだ一人の魔女が──共に力を合わせて戦った。"

[[dialogue]]
speaker = "unk"
# 時にはヒトでない生き物さえも、魔王の軍勢として加わった。
line = "時にはヒトでない生き物さえも、魔王の軍勢として加わった。"

[[dialogue]]
speaker = "ラクシス"
# 「おかげで死線を切り抜けられた。ありがとう、ディノレオン」
line = "「おかげで死線を切り抜けられた。ありがとう、ディノレオン」"

[[dialogue]]
speaker = "ディノレオン"
# 「フ──共に参ろうぞ、魔王よ。吾輩も大賢者として……この結末を見届ける責務がある」
line = "「フ──共に参ろうぞ、魔王よ。吾輩も大賢者として……この結末を見届ける責務がある」"

[[dialogue]]
speaker = "unk"
# ラクシスの従えていた剣虎の使い魔もその一体だった。
line = "ラクシスの従えていた剣虎の使い魔もその一体だった。"

[[dialogue]]
speaker = "unk"
# 剣虎は自らを大賢者と名乗り、魔王と共に幾多もの戦線を切り抜けていった。
line = "剣虎は自らを大賢者と名乗り、魔王と共に幾多もの戦線を切り抜けていった。"

[[dialogue]]
speaker = "unk"
# セレーネ流星群──
line = "セレーネ流星群──"

[[dialogue]]
speaker = "unk"
# リクリエ危機終盤の流れ星の雨に対しても、彼はその拳でもって撃退した。
line = "リクリエ危機終盤の流れ星の雨に対しても、彼はその拳でもって撃退した。"

[[dialogue]]
speaker = "unk"
# ラクシスがいなければ、三界は無数の隕石衝突に見舞われ、世界は崩壊していただろう。
line = "ラクシスがいなければ、三界は無数の隕石衝突に見舞われ、世界は崩壊していただろう。"

[[dialogue]]
speaker = "unk"
# そうして──旧森羅暦を一掃するはずだったリクリエは初の失敗を迎える。
line = "そうして──旧森羅暦を一掃するはずだったリクリエは初の失敗を迎える。"

[[dialogue]]
speaker = "ラクシス"
# 「俺のやるべきことは……すべて終わった……」
line = "「俺のやるべきことは……すべて終わった……」"

[[dialogue]]
speaker = "unk"
# 彼は魔王と、そして英雄として讃えられた。
line = "彼は魔王と、そして英雄として讃えられた。"

[[dialogue]]
speaker = "unk"
# そんな彼の隣には、いつも──月のように淑やかな女性が立っていた。
line = "そんな彼の隣には、いつも──月のように淑やかな女性が立っていた。"
