[[dialogue]]
speaker = "unk"
# 第５話,フィーニスの塔へ,B
line = "第５話,フィーニスの塔へ,B"

[[dialogue]]
speaker = "アポロ（大人）"
# 「おはよう。朝ご飯できてるぞ」
line = "「おはよう。朝ご飯できてるぞ」"

[[dialogue]]
speaker = "クロト"
# 「いつもありがとう。アポロには世話になりっぱなしだな」
line = "「いつもありがとう。アポロには世話になりっぱなしだな」"

[[dialogue]]
speaker = "フィオナ"
# 「おはようございます。秘密基地で過ごしているうちに、姉さんの朝食が楽しみになってきました」
line = "「おはようございます。秘密基地で過ごしているうちに、姉さんの朝食が楽しみになってきました」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「そいつは嬉しいな。リノ以外にも食べてくれる相手ができて、あたしも作り甲斐がある」
line = "「そいつは嬉しいな。リノ以外にも食べてくれる相手ができて、あたしも作り甲斐がある」"

[[dialogue]]
speaker = "ラクシャ"
# 「お、今日はお味噌汁に玉子焼き、塩じゃけ、おひたしか……和食もいいねぇ。なんだかほっとするよ」
line = "「お、今日はお味噌汁に玉子焼き、塩じゃけ、おひたしか……和食もいいねぇ。なんだかほっとするよ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あなた守護天使でしょ」
line = "「あなた守護天使でしょ」"

[[dialogue]]
speaker = "ラクシャ"
# 「流星市国暮らしも長いからねー」
line = "「流星市国暮らしも長いからねー」"

[[dialogue]]
speaker = "梨緒"
# 「おはよう」
line = "「おはよう」"

[[dialogue]]
speaker = "ナターシャ"
# 「おはよー」
line = "「おはよー」"

[[dialogue]]
speaker = "ベアトリス"
# 「あ、朝ご飯できてる。ありがとう、アポロちゃん」
line = "「あ、朝ご飯できてる。ありがとう、アポロちゃん」"

[[dialogue]]
speaker = "unk"
# そこに選挙管理委員会の３人も起きてきて……
line = "そこに選挙管理委員会の３人も起きてきて……"

[[dialogue]]
speaker = "リノ"
# 「おっはよー！　今日も一日頑張りましょ！」
line = "「おっはよー！　今日も一日頑張りましょ！」"

[[dialogue]]
speaker = "unk"
# 最後に母さんがやってきて、今秘密基地にいる全員が揃った。
line = "最後に母さんがやってきて、今秘密基地にいる全員が揃った。"

[[dialogue]]
speaker = "ヴィーナス"
# 「それじゃ……いただきまーす！」
line = "「それじゃ……いただきまーす！」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「よし、じゃあ食べながら調査の結果をまとめるぞ」
line = "「よし、じゃあ食べながら調査の結果をまとめるぞ」"

[[dialogue]]
speaker = "unk"
# ５日間ルヴィネの尾行を続けて記録した、彼女の行動パターンは……
line = "５日間ルヴィネの尾行を続けて記録した、彼女の行動パターンは……"

[[dialogue]]
speaker = "ナターシャ"
# 「まず、ルヴィネは極星学園の寮に住んでいる。寮の場所は、アルタイルの流星寮と同じだね」
line = "「まず、ルヴィネは極星学園の寮に住んでいる。寮の場所は、アルタイルの流星寮と同じだね」"

[[dialogue]]
speaker = "ナターシャ"
# 「学園に登校したら、パトロールに出発」
line = "「学園に登校したら、パトロールに出発」"

[[dialogue]]
speaker = "ナターシャ"
# 「モンスターと遭遇したら、すぐさま駆逐。モンスターがいない場合はいろんなところでバイトしてるね」
line = "「モンスターと遭遇したら、すぐさま駆逐。モンスターがいない場合はいろんなところでバイトしてるね」"

[[dialogue]]
speaker = "ナターシャ"
# 「何のためにバイトしてるんだろうね？　まさか救世主様が金欠ってことはないと思うけど」
line = "「何のためにバイトしてるんだろうね？　まさか救世主様が金欠ってことはないと思うけど」"

[[dialogue]]
speaker = "ベアトリス"
# 「前に聞いた時は、世界を知るため……みたいなこと言ってた気がする」
line = "「前に聞いた時は、世界を知るため……みたいなこと言ってた気がする」"

[[dialogue]]
speaker = "ナターシャ"
# 「世界を知るため、ね。勉強熱心だね」
line = "「世界を知るため、ね。勉強熱心だね」"

[[dialogue]]
speaker = "ラクシャ"
# 「バイトしまくってるとか、どっかの誰かさんみたいだ。奇遇だね」
line = "「バイトしまくってるとか、どっかの誰かさんみたいだ。奇遇だね」"

[[dialogue]]
speaker = "クロト"
# 「俺は入学資金のためだったんだけどな……いい経験になったけど」
line = "「俺は入学資金のためだったんだけどな……いい経験になったけど」"

[[dialogue]]
speaker = "unk"
# そしてルヴィネの尾行でわかったことがもう１つ──
line = "そしてルヴィネの尾行でわかったことがもう１つ──"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ルヴィネは昼過ぎになると、毎日のようにフィーニスの塔の中へ姿を消す」
line = "「ルヴィネは昼過ぎになると、毎日のようにフィーニスの塔の中へ姿を消す」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「だが戻ってくる時間はまちまちで、すぐに戻ってきて再びバイトに精を出すこともあれば、深夜を回ってからフィーニスの塔から出てくることもある」
line = "「だが戻ってくる時間はまちまちで、すぐに戻ってきて再びバイトに精を出すこともあれば、深夜を回ってからフィーニスの塔から出てくることもある」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「ベアトは知ってたか？」
line = "「ベアトは知ってたか？」"

[[dialogue]]
speaker = "ベアトリス"
# 「ううん。ルヴィがフィーニスの塔に行ってるのは知ってたけど、そんな毎日だとは思わなかった」
line = "「ううん。ルヴィがフィーニスの塔に行ってるのは知ってたけど、そんな毎日だとは思わなかった」"

[[dialogue]]
speaker = "クロト"
# 「みんなも知っての通り、フィーニスの塔は女神の聖域だ」
line = "「みんなも知っての通り、フィーニスの塔は女神の聖域だ」"

[[dialogue]]
speaker = "クロト"
# 「そしてルヴィネは女神の声が聞こえると言っていた。ルヴィネの言葉の真偽は不明だが、おそらくフィーニスの塔で何かしているんだろう」
line = "「そしてルヴィネは女神の声が聞こえると言っていた。ルヴィネの言葉の真偽は不明だが、おそらくフィーニスの塔で何かしているんだろう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「よーし！　じゃあ私たちもフィーニスの塔に入って、現場を押さえるわよ！」
line = "「よーし！　じゃあ私たちもフィーニスの塔に入って、現場を押さえるわよ！」"

[[dialogue]]
speaker = "梨緒"
# 「待て、ヴィーナス。フィーニスの塔にはディザスターハンドがいるかもしれない」
line = "「待て、ヴィーナス。フィーニスの塔にはディザスターハンドがいるかもしれない」"

[[dialogue]]
speaker = "unk"
# アルタイルでフィーニスの塔に登った時、ディザスターハンドに襲われ、命からがら逃げ出した。
line = "アルタイルでフィーニスの塔に登った時、ディザスターハンドに襲われ、命からがら逃げ出した。"

[[dialogue]]
speaker = "unk"
# ディザスターハンドと遭遇したのはアルタイルだが、あれは平行世界を超えることができる。
line = "ディザスターハンドと遭遇したのはアルタイルだが、あれは平行世界を超えることができる。"

[[dialogue]]
speaker = "unk"
# ならばデネブに現れても不思議じゃない。
line = "ならばデネブに現れても不思議じゃない。"

[[dialogue]]
speaker = "ヴィーナス"
# 「『コテツに入れば玉の輿』っていうでしょ！　このままじゃ大事なことはわからないままよ！」
line = "「『コテツに入れば玉の輿』っていうでしょ！　このままじゃ大事なことはわからないままよ！」"

[[dialogue]]
speaker = "梨緒"
# 「虎穴に入らずんば虎子を得ず……か？　だが一理あるか」
line = "「虎穴に入らずんば虎子を得ず……か？　だが一理あるか」"

[[dialogue]]
speaker = "フィオナ"
# 「ディザスターハンドが脅威だということは聞いています」
line = "「ディザスターハンドが脅威だということは聞いています」"

[[dialogue]]
speaker = "フィオナ"
# 「ですが私は魔王フォームを体得しましたし、ヴィーナスさんもノヴァフォームを使えるようになったので、遭遇しても撤退することはできるのではないでしょうか」
line = "「ですが私は魔王フォームを体得しましたし、ヴィーナスさんもノヴァフォームを使えるようになったので、遭遇しても撤退することはできるのではないでしょうか」"

[[dialogue]]
speaker = "unk"
# 確かに今はあの時と比べて戦力は大きく向上しているし、ディザスターハンドの存在を知っているから、ある程度想定した動きができる。
line = "確かに今はあの時と比べて戦力は大きく向上しているし、ディザスターハンドの存在を知っているから、ある程度想定した動きができる。"

[[dialogue]]
speaker = "unk"
# 足踏みしているわけにはいかないし、リスクを取るのもやむなし……か。
line = "足踏みしているわけにはいかないし、リスクを取るのもやむなし……か。"

[[dialogue]]
speaker = "クロト"
# 「よし、行こう。フィーニスの塔へ」
line = "「よし、行こう。フィーニスの塔へ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「決まりね」
line = "「決まりね」"

[[dialogue]]
speaker = "梨緒"
# 「ベアトとナターシャもそれで構わないか？」
line = "「ベアトとナターシャもそれで構わないか？」"

[[dialogue]]
speaker = "ナターシャ"
# 「いいよ。いつまで経っても成果なしってわけにはいかないからね」
line = "「いいよ。いつまで経っても成果なしってわけにはいかないからね」"

[[dialogue]]
speaker = "ベアトリス"
# 「うん。ルヴィが何をしているのか、私も知りたいから」
line = "「うん。ルヴィが何をしているのか、私も知りたいから」"

[[dialogue]]
speaker = "ラクシャ"
# 「じゃあボクはフィーニスの塔の中に入ったら、別行動させてもらうよ」
line = "「じゃあボクはフィーニスの塔の中に入ったら、別行動させてもらうよ」"

[[dialogue]]
speaker = "クロト"
# 「一緒に来ないのか？」
line = "「一緒に来ないのか？」"

[[dialogue]]
speaker = "ラクシャ"
# 「うん。ちょっと心当たりがあるんだ」
line = "「うん。ちょっと心当たりがあるんだ」"

[[dialogue]]
speaker = "ラクシャ"
# 「ボクがヴィーナスとともにアルタイルへ渡る時、半身をデネブに残してきたんだ」
line = "「ボクがヴィーナスとともにアルタイルへ渡る時、半身をデネブに残してきたんだ」"

[[dialogue]]
speaker = "ラクシャ"
# 「考えてもみてよ。１０年も守護天使が不在だったら、今頃デネブは大変なことになってるでしょ」
line = "「考えてもみてよ。１０年も守護天使が不在だったら、今頃デネブは大変なことになってるでしょ」"

[[dialogue]]
speaker = "クロト"
# 「そう言われれば確かに……」
line = "「そう言われれば確かに……」"

[[dialogue]]
speaker = "ラクシャ"
# 「ボクの半身は第零層に潜ませて、権能の維持と、塔内の情報の収集をさせている。接触できれば情報を得られるはずだよ」
line = "「ボクの半身は第零層に潜ませて、権能の維持と、塔内の情報の収集をさせている。接触できれば情報を得られるはずだよ」"

[[dialogue]]
speaker = "クロト"
# 「わかった。二面作戦でいこう」
line = "「わかった。二面作戦でいこう」"

[[dialogue]]
speaker = "unk"
# ルヴィネを追うのも確実ではない以上、情報を得る手段は複数あった方がいいだろう。
line = "ルヴィネを追うのも確実ではない以上、情報を得る手段は複数あった方がいいだろう。"

[[dialogue]]
speaker = "リノ"
# 「じゃあ私とアポロちゃんは、緊急の時、あなたたちがアルタイルに帰れるよう準備しておくわね」
line = "「じゃあ私とアポロちゃんは、緊急の時、あなたたちがアルタイルに帰れるよう準備しておくわね」"

[[dialogue]]
speaker = "クロト"
# 「アルタイルに戻れるの？」
line = "「アルタイルに戻れるの？」"

[[dialogue]]
speaker = "リノ"
# 「ええ。具体的には──」
line = "「ええ。具体的には──」"
