[[dialogue]]
speaker = "unk"
# 第８話,第８話『余は諦めない』,B
line = "第８話,第８話『余は諦めない』,B"

[[dialogue]]
speaker = "クラウディア"
# 「えー光の魔女クラウディア、クラウディアをよろしくお願いするぞ。１２月２５日はクラウディア・イルゼ・フォン・ゴットフリートの誕生日……」
line = "「えー光の魔女クラウディア、クラウディアをよろしくお願いするぞ。１２月２５日はクラウディア・イルゼ・フォン・ゴットフリートの誕生日……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「選挙演説みたいになってきた……」
line = "「選挙演説みたいになってきた……」"

[[dialogue]]
speaker = "クラウディア"
# 「ふう。サンタ稼業も楽ではないな」
line = "「ふう。サンタ稼業も楽ではないな」"

[[dialogue]]
speaker = "クラウディア"
# 「だが、これだけプレゼントを配れば、きっと大衆の意識に余の誕生日というものが刷り込まれたであろう」
line = "「だが、これだけプレゼントを配れば、きっと大衆の意識に余の誕生日というものが刷り込まれたであろう」"

[[dialogue]]
speaker = "クラウディア"
# 「いずれ人間界でも、世界中の民が余の生誕を祝うというわけだ！　あっはっは！」
line = "「いずれ人間界でも、世界中の民が余の生誕を祝うというわけだ！　あっはっは！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「よ！　さすがクラウディア様！」
line = "「よ！　さすがクラウディア様！」"

[[dialogue]]
speaker = "クラウディア"
# 「世間の声はどうだ、ちぇちゅーりえ？」
line = "「世間の声はどうだ、ちぇちゅーりえ？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「そーですねぇ……あ、あそこでさっき会った子が遊んでますよ」
line = "「そーですねぇ……あ、あそこでさっき会った子が遊んでますよ」"

[[dialogue]]
speaker = "ブランコに乗る男子"
# 「あのねあのね、僕と同じくらいの女の子がお菓子くれたんだよ」
line = "「あのねあのね、僕と同じくらいの女の子がお菓子くれたんだよ」"

[[dialogue]]
speaker = "ブランコに乗る女子"
# 「わたしのところにも来たよ！　ちっさいお人形くれた！」
line = "「わたしのところにも来たよ！　ちっさいお人形くれた！」"

[[dialogue]]
speaker = "ブランコに乗る男子"
# 「お菓子もいいけど、僕はゲームが欲しいな」
line = "「お菓子もいいけど、僕はゲームが欲しいな」"

[[dialogue]]
speaker = "ブランコに乗る女子"
# 「そろそろクリスマスだね！　サンタさんにお願いするプレゼント、何にしよっかな～？」
line = "「そろそろクリスマスだね！　サンタさんにお願いするプレゼント、何にしよっかな～？」"

[[dialogue]]
speaker = "クラウディア"
# 「むぅ……！」
line = "「むぅ……！」"

[[dialogue]]
speaker = "クラウディア"
# 「まだクリスマスなどと抜かしておる。サンタクロース──なかなか強力なライバルよ」
line = "「まだクリスマスなどと抜かしておる。サンタクロース──なかなか強力なライバルよ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「サンタ人気は根強いみたいですねぇ」
line = "「サンタ人気は根強いみたいですねぇ」"

[[dialogue]]
speaker = "クラウディア"
# 「うむ。だが、この調子でプレゼントを配っていけば──きっと意識も変わっていくはずだ……！」
line = "「うむ。だが、この調子でプレゼントを配っていけば──きっと意識も変わっていくはずだ……！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「その意気だよ、クラウディア様！」
line = "「その意気だよ、クラウディア様！」"

[[dialogue]]
speaker = "クラウディア"
# 「ふう……ただ、少し休憩だ」
line = "「ふう……ただ、少し休憩だ」"

[[dialogue]]
speaker = "クラウディア"
# 「ところでちぇちゅーりえよ。このロッド、余が自分に振るとどうなるのだ？」
line = "「ところでちぇちゅーりえよ。このロッド、余が自分に振るとどうなるのだ？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「自分に？　あー……それは試したことなかったけど、何かプレゼントが降ってくるんじゃないかな？」
line = "「自分に？　あー……それは試したことなかったけど、何かプレゼントが降ってくるんじゃないかな？」"

[[dialogue]]
speaker = "クラウディア"
# 「ほう！？　それは景気のいい話ではないか！」
line = "「ほう！？　それは景気のいい話ではないか！」"

[[dialogue]]
speaker = "クラウディア"
# 「なぜ今までやらなかったのか。余の欲しいものはいくらでもあるぞ……むふふ、夢が膨らむようだ！」
line = "「なぜ今までやらなかったのか。余の欲しいものはいくらでもあるぞ……むふふ、夢が膨らむようだ！」"

[[dialogue]]
speaker = "クラウディア"
# 「そーれ……メリーマイバースデ～！！」
line = "「そーれ……メリーマイバースデ～！！」"

[[dialogue]]
speaker = "クラウディア"
# 「──出たぞ！」
line = "「──出たぞ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ほほう、これは──『ビフテキさん次郎』だね」
line = "「ほほう、これは──『ビフテキさん次郎』だね」"

[[dialogue]]
speaker = "クラウディア"
# 「なんなのだ、それは」
line = "「なんなのだ、それは」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「まるで肉厚のビーフステーキ──のような味を目指した駄菓子らしい。原材料は魚のすり身」
line = "「まるで肉厚のビーフステーキ──のような味を目指した駄菓子らしい。原材料は魚のすり身」"

[[dialogue]]
speaker = "クラウディア"
# 「もぐもぐ……うーん、悪くはないが、誕生日プレゼントとしてはパンチが弱いぞ。ごちそーさま」
line = "「もぐもぐ……うーん、悪くはないが、誕生日プレゼントとしてはパンチが弱いぞ。ごちそーさま」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「食べるの早っ！？」
line = "「食べるの早っ！？」"

[[dialogue]]
speaker = "クラウディア"
# 「もういっぺんだ！　食べ物はもういい。余は新しいドールハウスが欲しいぞ。魔法でカスタマイズして遊ぶのだ」
line = "「もういっぺんだ！　食べ物はもういい。余は新しいドールハウスが欲しいぞ。魔法でカスタマイズして遊ぶのだ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「これは……ワラ人形だね。ドール違いだ」
line = "「これは……ワラ人形だね。ドール違いだ」"

[[dialogue]]
speaker = "クラウディア"
# 「も……もういっぺんだ！　なんでもいいから余の欲しいものを出せ！」
line = "「も……もういっぺんだ！　なんでもいいから余の欲しいものを出せ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「すごい、ビフテキ人形だ」
line = "「すごい、ビフテキ人形だ」"

[[dialogue]]
speaker = "クラウディア"
# 「──なぜ混ざるのだ！？　欠陥品だぞこれは、振れば振るほどトンチンカンなものが出てくるではないか！」
line = "「──なぜ混ざるのだ！？　欠陥品だぞこれは、振れば振るほどトンチンカンなものが出てくるではないか！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「うーん、まだまだオリジナルフォームの性能には遠いか……」
line = "「うーん、まだまだオリジナルフォームの性能には遠いか……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「でも、おかげでいい実験結果が得られたよ。ありがとうクラウディア様」
line = "「でも、おかげでいい実験結果が得られたよ。ありがとうクラウディア様」"

[[dialogue]]
speaker = "クラウディア"
# 「やれやれ……やはり自分に使うものではないということか」
line = "「やれやれ……やはり自分に使うものではないということか」"

[[dialogue]]
speaker = "クラウディア"
# 「というか、よくよく考えたらなぜ余は自分の誕生日に他人へプレゼントを配っているのだ？　何もかもあべこべな気がしてきたぞ」
line = "「というか、よくよく考えたらなぜ余は自分の誕生日に他人へプレゼントを配っているのだ？　何もかもあべこべな気がしてきたぞ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「急に冷静になられるとアタシが困るっていうか……」
line = "「急に冷静になられるとアタシが困るっていうか……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「このままクラウディア様の誕生日が忘れ去られてもいいの？　このままじゃ世間はクリスマス一色だよ」
line = "「このままクラウディア様の誕生日が忘れ去られてもいいの？　このままじゃ世間はクリスマス一色だよ」"

[[dialogue]]
speaker = "クラウディア"
# 「おお、そうだった。余の誕生日を知らしめるためならなんでもするぞ」
line = "「おお、そうだった。余の誕生日を知らしめるためならなんでもするぞ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「よっ！　魔女界いち～！」
line = "「よっ！　魔女界いち～！」"

[[dialogue]]
speaker = "セドナ"
# 「──見つけたぞ！」
line = "「──見つけたぞ！」"

[[dialogue]]
speaker = "ウェンディ"
# 「──クラウディア様！　ツェツィーリエ！　ここにいたんですね！」
line = "「──クラウディア様！　ツェツィーリエ！　ここにいたんですね！」"

[[dialogue]]
speaker = "クラウディア"
# 「む？」
line = "「む？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「あ、やば」
line = "「あ、やば」"

[[dialogue]]
speaker = "セドナ"
# 「まったく、手間をかけさせてくれる──姫様。帰りますよ」
line = "「まったく、手間をかけさせてくれる──姫様。帰りますよ」"

[[dialogue]]
speaker = "クラウディア"
# 「嫌だ。余にはまだまだやることがあるのだ」
line = "「嫌だ。余にはまだまだやることがあるのだ」"

[[dialogue]]
speaker = "セドナ"
# 「やること──？」
line = "「やること──？」"

[[dialogue]]
speaker = "ウェンディ"
# 「クラウディア様の服……それって……」
line = "「クラウディア様の服……それって……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「アタシのＮＥＷ発明品でーす♪」
line = "「アタシのＮＥＷ発明品でーす♪」"

[[dialogue]]
speaker = "クラウディア"
# 「ふっふっふ。この服のおかげで余はサンタを超える存在となったのだ！」
line = "「ふっふっふ。この服のおかげで余はサンタを超える存在となったのだ！」"

[[dialogue]]
speaker = "ウェンディ"
# 「やっぱりツェツィーリエのせいじゃない！」
line = "「やっぱりツェツィーリエのせいじゃない！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「いやあ、アタシはただクラウディア様の笑顔が見たくてこの戦闘服を造っただけっていうか」
line = "「いやあ、アタシはただクラウディア様の笑顔が見たくてこの戦闘服を造っただけっていうか」"

[[dialogue]]
speaker = "ウェンディ"
# 「──っていうか待って、発明とか聞いてない。その開発費はどこから出たっていうんです……？」
line = "「──っていうか待って、発明とか聞いてない。その開発費はどこから出たっていうんです……？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「まあまあ、細かいことは気にせず。クラウディア様の笑顔はプライスレスだよ」
line = "「まあまあ、細かいことは気にせず。クラウディア様の笑顔はプライスレスだよ」"

[[dialogue]]
speaker = "ウェンディ"
# 「ま……またネビュラの運用資金が～～！」
line = "「ま……またネビュラの運用資金が～～！」"

[[dialogue]]
speaker = "セドナ"
# 「おめかしは基地でもできます。姫様。無断での外出は禁止と、再三言い付けていたはずです」
line = "「おめかしは基地でもできます。姫様。無断での外出は禁止と、再三言い付けていたはずです」"

[[dialogue]]
speaker = "クラウディア"
# 「よいではないか！　お主たちだって学園やら九浄家やらと<b>ふれんどりい</b>にしておる」
line = "「よいではないか！　お主たちだって学園やら九浄家やらと<b>ふれんどりい</b>にしておる」"

[[dialogue]]
speaker = "クラウディア"
# 「もはや魔女と人間が交流する開国の時代！　今どき外出禁止など古いのだ！」
line = "「もはや魔女と人間が交流する開国の時代！　今どき外出禁止など古いのだ！」"

[[dialogue]]
speaker = "セドナ"
# 「なるほど……確かに、魔女と人間の交流は解禁されました。今までのような<ruby=こしょくそうぜん>古色蒼然</ruby>とした規律は通じないでしょう」
line = "「なるほど……確かに、魔女と人間の交流は解禁されました。今までのような<ruby>古色蒼然<rt>こしょくそうぜん</rt></ruby>とした規律は通じないでしょう」"

[[dialogue]]
speaker = "クラウディア"
# 「だろう？」
line = "「だろう？」"

[[dialogue]]
speaker = "セドナ"
# 「──が！　私と姫様の間にある『ネビュラとのおやくそく』はまだ活きております！」
line = "「──が！　私と姫様の間にある『ネビュラとのおやくそく』はまだ活きております！」"

[[dialogue]]
speaker = "セドナ"
# 「なので姫様だけは無断外出禁止！　ちゃんと私の許可を得てからでないと外出はなりません！」
line = "「なので姫様だけは無断外出禁止！　ちゃんと私の許可を得てからでないと外出はなりません！」"

[[dialogue]]
speaker = "クラウディア"
# 「なあっ！？　ず、ずるいぞそんなの！　オーボーだ！　殿様商売だ！」
line = "「なあっ！？　ず、ずるいぞそんなの！　オーボーだ！　殿様商売だ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「殿様商売ではないよ」
line = "「殿様商売ではないよ」"

[[dialogue]]
speaker = "セドナ"
# 「姫様を自由にさせたら大抵ろくなことにならない──今は大事な時期だというのに、魔女全体が誤解されるような事をしでかすに決まっている」
line = "「姫様を自由にさせたら大抵ろくなことにならない──今は大事な時期だというのに、魔女全体が誤解されるような事をしでかすに決まっている」"

[[dialogue]]
speaker = "クラウディア"
# 「言いがかりはよすのだ！　余がどんな誤解を与えたという！？」
line = "「言いがかりはよすのだ！　余がどんな誤解を与えたという！？」"

[[dialogue]]
speaker = "ブランコに乗る男子"
# 「そういえばさっきの子、ひかりの魔女だって言ってたよ」
line = "「そういえばさっきの子、ひかりの魔女だって言ってたよ」"

[[dialogue]]
speaker = "ブランコに乗る女子"
# 「へー！　魔女ってお菓子くれるんだ」
line = "「へー！　魔女ってお菓子くれるんだ」"

[[dialogue]]
speaker = "ブランコに乗る男子"
# 「ハロウィンだけかと思ってたよ。季節ごとに来てくれるのかも」
line = "「ハロウィンだけかと思ってたよ。季節ごとに来てくれるのかも」"

[[dialogue]]
speaker = "ブランコに乗る女子"
# 「なら、今度のお正月もお菓子配ってくれそう！」
line = "「なら、今度のお正月もお菓子配ってくれそう！」"

[[dialogue]]
speaker = "セドナ"
# 「──立派に間違った認識を与えているようですが？」
line = "「──立派に間違った認識を与えているようですが？」"

[[dialogue]]
speaker = "クラウディア"
# 「別によいではないか。地域密着というやつだ」
line = "「別によいではないか。地域密着というやつだ」"

[[dialogue]]
speaker = "ウェンディ"
# 「いや、それは問題ですから……ほら、基地にはクラウディア様のお菓子もありますよ？」
line = "「いや、それは問題ですから……ほら、基地にはクラウディア様のお菓子もありますよ？」"

[[dialogue]]
speaker = "クラウディア"
# 「ふん。そんなもので<ruby=ろうらく>籠絡</ruby>されるほど、余は子どもではない！　嫌だ嫌だ、まだ余の野望は達成されておらんのだ！」
line = "「ふん。そんなもので<ruby>籠絡<rt>ろうらく</rt></ruby>されるほど、余は子どもではない！　嫌だ嫌だ、まだ余の野望は達成されておらんのだ！」"

[[dialogue]]
speaker = "ウェンディ"
# 「あ、逃げた！」
line = "「あ、逃げた！」"

[[dialogue]]
speaker = "セドナ"
# 「追うぞ──！」
line = "「追うぞ──！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ひえー、大変だー！」
line = "「ひえー、大変だー！」"
