[[dialogue]]
speaker = "unk"
# 第１３話,仮面の裏には……,B
line = "第１３話,仮面の裏には……,B"

[[dialogue]]
speaker = "unk"
# 一方その頃……
line = "一方その頃……"

[[dialogue]]
speaker = "unk"
# アステライトの掃討をあらかた終えたメンバーが空まで浮上してきていた。
line = "アステライトの掃討をあらかた終えたメンバーが空まで浮上してきていた。"

[[dialogue]]
speaker = "unk"
# 話は無論、今も先行しているフィオナのことに及ぶ。
line = "話は無論、今も先行しているフィオナのことに及ぶ。"

[[dialogue]]
speaker = "ユウリ"
# 「──おいクロト！　ヴィーナス！　塔でフィオナに何があったんだ！？」
line = "「──おいクロト！　ヴィーナス！　塔でフィオナに何があったんだ！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「何にもないわよ！　強いて言うならアレだけど──別状があったわけじゃないし……！」
line = "「何にもないわよ！　強いて言うならアレだけど──別状があったわけじゃないし……！」"

[[dialogue]]
speaker = "unk"
# 謎の声がフィオナを『魔王』であると告げた。
line = "謎の声がフィオナを『魔王』であると告げた。"

[[dialogue]]
speaker = "unk"
# しかし、彼女に取り乱す様子がなかったのは事実であり……
line = "しかし、彼女に取り乱す様子がなかったのは事実であり……"

[[dialogue]]
speaker = "unk"
# スイッチが切り替わったのは、まさに今になってのことだ。
line = "スイッチが切り替わったのは、まさに今になってのことだ。"

[[dialogue]]
speaker = "ソフィア"
# 「あのようなフィオナ会長は……見たことがありません……」
line = "「あのようなフィオナ会長は……見たことがありません……」"

[[dialogue]]
speaker = "クロト"
# 「とにかく追おう──結果がどうなるにせよ、放っておいたらよくない予感がする」
line = "「とにかく追おう──結果がどうなるにせよ、放っておいたらよくない予感がする」"

[[dialogue]]
speaker = "フィオナ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "アポロ"
# 「っ、づうっ……！　な、なんでこのアポロ様が……！」
line = "「っ、づうっ……！　な、なんでこのアポロ様が……！」"

[[dialogue]]
speaker = "フィオナ"
# 「その体で……勝手なことをされては困る、と申し上げたいのです」
line = "「その体で……勝手なことをされては困る、と申し上げたいのです」"

[[dialogue]]
speaker = "アポロ"
# 「なんだ……ナニモノだ、オマエ！　オマエも『魔王』なのか！？」
line = "「なんだ……ナニモノだ、オマエ！　オマエも『魔王』なのか！？」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ」
line = "「ええ」"

[[dialogue]]
speaker = "unk"
# アポロの問いにフィオナは鷹揚と答えた。
line = "アポロの問いにフィオナは鷹揚と答えた。"

[[dialogue]]
speaker = "フィオナ"
# 「私が、先代魔王ラクシスの血を継ぐ一族であることに、間違いはありませんね」
line = "「私が、先代魔王ラクシスの血を継ぐ一族であることに、間違いはありませんね」"

[[dialogue]]
speaker = "unk"
# 『月の壁画』が彼女の脳裏によぎる。
line = "『月の壁画』が彼女の脳裏によぎる。"

[[dialogue]]
speaker = "unk"
# それは、彼女が幼い頃から眺めてきた歴史の１ページ……
line = "それは、彼女が幼い頃から眺めてきた歴史の１ページ……"

[[dialogue]]
speaker = "フィオナ"
# 「私は流星学園２年、星徒会会長・星見フィオナ──」
line = "「私は流星学園２年、星徒会会長・星見フィオナ──」"

[[dialogue]]
speaker = "unk"
# そして。
line = "そして。"

[[dialogue]]
speaker = "unk"
# 太陽の凝縮された一振りの剣が、アポロの仮面に振り下ろされた。
line = "太陽の凝縮された一振りの剣が、アポロの仮面に振り下ろされた。"

[[dialogue]]
speaker = "フィオナ"
# 「あなたから<b>その名を受け継いだ</b>者です」
line = "「あなたから<b>その名を受け継いだ</b>者です」"

[[dialogue]]
speaker = "アポロ"
# 「っっ────！！」
line = "「っっ────！！」"

[[dialogue]]
speaker = "unk"
# アポロをアポロたらしめていたペルソナが砕け散る。
line = "アポロをアポロたらしめていたペルソナが砕け散る。"

[[dialogue]]
speaker = "unk"
# 未だ消えない太陽の残照は、少女の素顔を露わにし……
line = "未だ消えない太陽の残照は、少女の素顔を露わにし……"

[[dialogue]]
speaker = "フィオナ"
# 「これ以上……言葉を尽くす必要はありませんね」
line = "「これ以上……言葉を尽くす必要はありませんね」"

[[dialogue]]
speaker = "アポロ"
# 「────」
line = "「────」"

[[dialogue]]
speaker = "フィオナ"
# 「目を覚ましてください──姉さん」
line = "「目を覚ましてください──姉さん」"

[[dialogue]]
speaker = "unk"
# 時空を隔てたもうひとつの姉妹が、ここに再会を果たしていた。
line = "時空を隔てたもうひとつの姉妹が、ここに再会を果たしていた。"
