[[dialogue]]
speaker = "unk"
# 第１３話,破滅を呼ぶ者,B
line = "第１３話,破滅を呼ぶ者,B"

[[dialogue]]
speaker = "スレイプニル"
# 「ブルルル……！」
line = "「ブルルル……！」"

[[dialogue]]
speaker = "unk"
# 猛る神馬が<ruby=いなな>嘶</ruby>く。
line = "猛る神馬が<ruby>嘶<rt>いなな</rt></ruby>く。"

[[dialogue]]
speaker = "unk"
# 蹄が建物を蹴り砕き、鋭い刃が地面を抉る。
line = "蹄が建物を蹴り砕き、鋭い刃が地面を抉る。"

[[dialogue]]
speaker = "クロト"
# 「こいつ……強い……！」
line = "「こいつ……強い……！」"

[[dialogue]]
speaker = "unk"
# 今までフィーニスの塔で戦ってきたガーディアンとは、スピード、パワー、耐久力、どれも段違いだ。
line = "今までフィーニスの塔で戦ってきたガーディアンとは、スピード、パワー、耐久力、どれも段違いだ。"

[[dialogue]]
speaker = "unk"
# それでも……！
line = "それでも……！"

[[dialogue]]
speaker = "クロト"
# 「ディマイズ──ブレイカー！」
line = "「ディマイズ──ブレイカー！」"

[[dialogue]]
speaker = "スレイプニル"
# 「ブルル……！？」
line = "「ブルル……！？」"

[[dialogue]]
speaker = "unk"
# 星力を込めた拳の一撃がガーディアンを貫く。
line = "星力を込めた拳の一撃がガーディアンを貫く。"

[[dialogue]]
speaker = "unk"
# 打ち込む拳の数は三ではなく一。魔王の力を抑えた純粋な星騎士としての拳が、暴威を振るうガーディアンを打ち倒した。
line = "打ち込む拳の数は三ではなく一。魔王の力を抑えた純粋な星騎士としての拳が、暴威を振るうガーディアンを打ち倒した。"

[[dialogue]]
speaker = "マトイ"
# 「はぁ、はぁ、はぁ……何とか倒せた……」
line = "「はぁ、はぁ、はぁ……何とか倒せた……」"

[[dialogue]]
speaker = "サーシャ"
# 「でも流星市国全域で同じガーディアンが暴れているみたいね」
line = "「でも流星市国全域で同じガーディアンが暴れているみたいね」"

[[dialogue]]
speaker = "マトイ"
# 「！　そんな……星徒会でも苦戦するようなのが、そんな何体も出てきたら……」
line = "「！　そんな……星徒会でも苦戦するようなのが、そんな何体も出てきたら……」"

[[dialogue]]
speaker = "アナ"
# 「今はまだプリマステラが持ちこたえていますが、非常に危うい状態です。私たちで支援しましょう」
line = "「今はまだプリマステラが持ちこたえていますが、非常に危うい状態です。私たちで支援しましょう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「どうしてガーディアンが暴れてるのかわからないけど、許さないわ！　行くわよ、クロ──」
line = "「どうしてガーディアンが暴れてるのかわからないけど、許さないわ！　行くわよ、クロ──」"

[[dialogue]]
speaker = "？？？"
# 「カラミティ──バスターーーッ！！！」
line = "「カラミティ──バスターーーッ！！！」"

[[dialogue]]
speaker = "マトイ"
# 「──！？」
line = "「──！？」"

[[dialogue]]
speaker = "unk"
# 嵐をまとった槍が、弾丸となって迸る。
line = "嵐をまとった槍が、弾丸となって迸る。"

[[dialogue]]
speaker = "マトイ"
# 「く──！！」
line = "「く──！！」"

[[dialogue]]
speaker = "unk"
# ギリギリでマトイの反応が間に合い、直線的な破壊力を盾で逸らした。
line = "ギリギリでマトイの反応が間に合い、直線的な破壊力を盾で逸らした。"

[[dialogue]]
speaker = "unk"
# もし一瞬でも遅れていれば、上半身が吹き飛んでいたかもしれない。
line = "もし一瞬でも遅れていれば、上半身が吹き飛んでいたかもしれない。"

[[dialogue]]
speaker = "？？？"
# 「チッ、仕留めそこなったか」
line = "「チッ、仕留めそこなったか」"

[[dialogue]]
speaker = "マトイ"
# 「はぁ、はぁ……何とか、耐えた……」
line = "「はぁ、はぁ……何とか、耐えた……」"

[[dialogue]]
speaker = "クロト"
# 「誰だ……！？」
line = "「誰だ……！？」"

[[dialogue]]
speaker = "unk"
# 嵐が止むと、そこにいたのは小柄な人影で──
line = "嵐が止むと、そこにいたのは小柄な人影で──"

[[dialogue]]
speaker = "チナ"
# 「アタシはチナ。お前らの……敵だ」
line = "「アタシはチナ。お前らの……敵だ」"
