[[dialogue]]
speaker = "unk"
# 第４話,蝕む絶望,B
line = "第４話,蝕む絶望,B"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「抵抗しても無意味だと……なぜわからないのかしら」
line = "「抵抗しても無意味だと……なぜわからないのかしら」"

[[dialogue]]
speaker = "フィオナ（魔王）"
# 「ホロウ・ルヴィネ──あなたがどれほどの力を秘めていようと！　私たちに屈するという選択肢はないんです！」
line = "「ホロウ・ルヴィネ──あなたがどれほどの力を秘めていようと！　私たちに屈するという選択肢はないんです！」"

[[dialogue]]
speaker = "アポロ"
# 「あたしたちの未来は、あたしたちが決めるんだ！！」
line = "「あたしたちの未来は、あたしたちが決めるんだ！！」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「ぶっ飛びなさい──ディバインスーパーノヴァ！！」
line = "「ぶっ飛びなさい──ディバインスーパーノヴァ！！」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「くぅっ──！？」
line = "「くぅっ──！？」"

[[dialogue]]
speaker = "unk"
# フィオナ達双子の連携で生まれた隙にヴィーナスが大技を合わせた──手ごたえ、ありだ！
line = "フィオナ達双子の連携で生まれた隙にヴィーナスが大技を合わせた──手ごたえ、ありだ！"

[[dialogue]]
speaker = "煌嶺"
# 「どれ。先の厄災では惜しいことをした──代わりに貴様を、妾のものにしてやろう！」
line = "「どれ。先の厄災では惜しいことをした──代わりに貴様を、妾のものにしてやろう！」"

[[dialogue]]
speaker = "unk"
# 煌嶺の九尾が、包んだ対象を傀儡とする火球を出現させ──ホロウを呑みこみにかかる。
line = "煌嶺の九尾が、包んだ対象を傀儡とする火球を出現させ──ホロウを呑みこみにかかる。"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「──許しがたい。私を使役するのはお父様をおいて他にいない。一介の魔族が踏み入っていい領域ではないわ……！」
line = "「──許しがたい。私を使役するのはお父様をおいて他にいない。一介の魔族が踏み入っていい領域ではないわ……！」"

[[dialogue]]
speaker = "煌嶺"
# 「言っていろ。貴様はあの厄災と違い、自我が薄いようだ──クク、創造主の人形はどのような使い心地か！？」
line = "「言っていろ。貴様はあの厄災と違い、自我が薄いようだ──クク、創造主の人形はどのような使い心地か！？」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「仕方がない。処分しましょう」
line = "「仕方がない。処分しましょう」"

[[dialogue]]
speaker = "クロト"
# 「なッ──！？」
line = "「なッ──！？」"

[[dialogue]]
speaker = "煌嶺"
# 「……ほう。操られる前に、自裁するとはな」
line = "「……ほう。操られる前に、自裁するとはな」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「ふふ……敵の傀儡に堕ちるくらいなら、<b>交換</b>するのが一番効率がいいもの……」
line = "「ふふ……敵の傀儡に堕ちるくらいなら、<b>交換</b>するのが一番効率がいいもの……」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「さあ、来なさい──<b>新しいルヴィネ</b>」
line = "「さあ、来なさい──<b>新しいルヴィネ</b>」"

[[dialogue]]
speaker = "アポロ"
# 「嘘、だろ……！？」
line = "「嘘、だろ……！？」"

[[dialogue]]
speaker = "unk"
# 今、倒れ伏したホロウを追い込むだけでも、かなりの消耗を強いられたというのに。
line = "今、倒れ伏したホロウを追い込むだけでも、かなりの消耗を強いられたというのに。"

[[dialogue]]
speaker = "unk"
# 新たに現れたホロウ・ルヴィネは、汗一つかいていない『新品』。
line = "新たに現れたホロウ・ルヴィネは、汗一つかいていない『新品』。"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「２体目。役目を果たせなかったようね。不手際は死で償いなさい」
line = "「２体目。役目を果たせなかったようね。不手際は死で償いなさい」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「ええ……あとは、新しい貴女に託すとするわ。転送装置を受け取って。出来損ないの私は、消えましょう……」
line = "「ええ……あとは、新しい貴女に託すとするわ。転送装置を受け取って。出来損ないの私は、消えましょう……」"

[[dialogue]]
speaker = "unk"
# 自傷によって深手を負ったホロウの身体が、光の粒となって塔の頂上に溶けていく……
line = "自傷によって深手を負ったホロウの身体が、光の粒となって塔の頂上に溶けていく……"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「魔王たちに不覚を取ったのは度し難い。けれど有益な戦闘データを入手できたわね」
line = "「魔王たちに不覚を取ったのは度し難い。けれど有益な戦闘データを入手できたわね」"

[[dialogue]]
speaker = "クロト"
# 「お前は……お前たちは……どうしてそんなことができる？」
line = "「お前は……お前たちは……どうしてそんなことができる？」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「先だって伝えたはず、価値観が違うのよ。短い時を生きるヒトでは、私のお父様に対する無心の忠誠は理解できないわ」
line = "「先だって伝えたはず、価値観が違うのよ。短い時を生きるヒトでは、私のお父様に対する無心の忠誠は理解できないわ」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「魔王とその血統は脅威──特に煌嶺。貴女の能力と私は、ひどく相性が悪いようね」
line = "「魔王とその血統は脅威──特に煌嶺。貴女の能力と私は、ひどく相性が悪いようね」"

[[dialogue]]
speaker = "煌嶺"
# 「虚ろという言葉に似合いの中身の無さだったな、ホロウよ。新しい貴様は、少しは期待してよいのか？」
line = "「虚ろという言葉に似合いの中身の無さだったな、ホロウよ。新しい貴様は、少しは期待してよいのか？」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「ええ。存分に<b>私たち</b>に期待して頂戴」
line = "「ええ。存分に<b>私たち</b>に期待して頂戴」"

[[dialogue]]
speaker = "unk"
# ホロウが転送装置を掲げると、空間に裂け目が生まれ──
line = "ホロウが転送装置を掲げると、空間に裂け目が生まれ──"

[[dialogue]]
speaker = "アポロ"
# 「お、おいおいっ……！？」
line = "「お、おいおいっ……！？」"

[[dialogue]]
speaker = "煌嶺"
# 「なるほど──木偶と呼ぶにふさわしい。確かに楽しめそうだ！」
line = "「なるほど──木偶と呼ぶにふさわしい。確かに楽しめそうだ！」"

[[dialogue]]
speaker = "フィオナ（魔王）"
# 「１体１体の霊力も、先ほどのホロウよりずっと高い……！？」
line = "「１体１体の霊力も、先ほどのホロウよりずっと高い……！？」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「は、反則じゃないの！？　恥ずかしくないわけ、あんた！」
line = "「は、反則じゃないの！？　恥ずかしくないわけ、あんた！」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「恥など覚えるわけがないわ。与えられた役割のために全霊を尽くす──それこそ私の誉れであり、生まれてきた意味なのだから」
line = "「恥など覚えるわけがないわ。与えられた役割のために全霊を尽くす──それこそ私の誉れであり、生まれてきた意味なのだから」"

[[dialogue]]
speaker = "ジグ"
# 「……魔王。どうにかして、転送装置を持った個体を撃破しなくてはね」
line = "「……魔王。どうにかして、転送装置を持った個体を撃破しなくてはね」"

[[dialogue]]
speaker = "クロト"
# 「わかっている。だけど──」
line = "「わかっている。だけど──」"

[[dialogue]]
speaker = "unk"
# ホロウ・ルヴィネ自身も俺たちの狙いを承知している。４体のホロウが、装置を持つ１体の守備をがっちりと固めている……！
line = "ホロウ・ルヴィネ自身も俺たちの狙いを承知している。４体のホロウが、装置を持つ１体の守備をがっちりと固めている……！"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「ついでよ。何事も並行して進めるのが効率的──」
line = "「ついでよ。何事も並行して進めるのが効率的──」"

[[dialogue]]
speaker = "unk"
# ホロウ・ルヴィネが転送装置を掲げるが──
line = "ホロウ・ルヴィネが転送装置を掲げるが──"

[[dialogue]]
speaker = "フィオナ（魔王）"
# 「……何も、現れない？」
line = "「……何も、現れない？」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「ここにはね。今、地上で極大のアステラと、私の複製体を多数、展開したわ」
line = "「ここにはね。今、地上で極大のアステラと、私の複製体を多数、展開したわ」"

[[dialogue]]
speaker = "クロト"
# 「なん──だって！？」
line = "「なん──だって！？」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「あと１時間も経たず、流星市国はこの地上から消滅する──再創生はもう止められないわ」
line = "「あと１時間も経たず、流星市国はこの地上から消滅する──再創生はもう止められないわ」"

[[dialogue]]
speaker = "クロト"
# 「──くそっ！　一刻も早く、転送装置を奪取するぞ！！」
line = "「──くそっ！　一刻も早く、転送装置を奪取するぞ！！」"

[[dialogue]]
speaker = "ベアトリス"
# 「ルヴィ、がんばって！　もうすぐ治るから、きっと治るから……！！」
line = "「ルヴィ、がんばって！　もうすぐ治るから、きっと治るから……！！」"

[[dialogue]]
speaker = "グレイス"
# 「そうですよ……！　魔女様が奇跡を起こしてくれます！　気をしっかり！！」
line = "「そうですよ……！　魔女様が奇跡を起こしてくれます！　気をしっかり！！」"

[[dialogue]]
speaker = "トリュファイナ"
# （くっ……！　想像以上に、傷が深い……深すぎます！）
line = "（くっ……！　想像以上に、傷が深い……深すぎます！）"

[[dialogue]]
speaker = "トリュファイナ"
# （私の治癒による再生のスピードより、ルヴィネ様の命が失われていくペースの方が、倍は早い……！！）
line = "（私の治癒による再生のスピードより、ルヴィネ様の命が失われていくペースの方が、倍は早い……！！）"

[[dialogue]]
speaker = "チナ"
# 「だ、大丈夫だよな？　ルヴィは、助かるよな……！？」
line = "「だ、大丈夫だよな？　ルヴィは、助かるよな……！？」"

[[dialogue]]
speaker = "レティシア"
# 「わ、私にできることはある？　魔法の対価に命が必要ならあげる！　全部あげるから……お願い、ルヴィを助けて！！」
line = "「わ、私にできることはある？　魔法の対価に命が必要ならあげる！　全部あげるから……お願い、ルヴィを助けて！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ま、じょ……」
line = "「ま、じょ……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「わかってる、でしょ……？　……もう、むだ、だって……」
line = "「わかってる、でしょ……？　……もう、むだ、だって……」"

[[dialogue]]
speaker = "トリュファイナ"
# 「…………っ！！」
line = "「…………っ！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「もう、いい、から…………みんな、を……まも、って……」
line = "「もう、いい、から…………みんな、を……まも、って……」"

[[dialogue]]
speaker = "グレイス"
# 「嫌です！　嫌です嫌です！！　わ、私は！　まだ許してないですからね！？　許してないのに──逝っちゃダメです！！！」
line = "「嫌です！　嫌です嫌です！！　わ、私は！　まだ許してないですからね！？　許してないのに──逝っちゃダメです！！！」"

[[dialogue]]
speaker = "チナ"
# 「デネブで、みんなで過ごすんだろ！？　約束したそばから破ってんじゃねえぞ！！」
line = "「デネブで、みんなで過ごすんだろ！？　約束したそばから破ってんじゃねえぞ！！」"

[[dialogue]]
speaker = "トリュファイナ"
# （私はかつて、呪いに蝕まれたラクシス様を救えなかった……！）
line = "（私はかつて、呪いに蝕まれたラクシス様を救えなかった……！）"

[[dialogue]]
speaker = "トリュファイナ"
# （もうあんな思いは、二度とごめんだと心に誓ったのに……！！　届いてください、癒しの力よ！！）
line = "（もうあんな思いは、二度とごめんだと心に誓ったのに……！！　届いてください、癒しの力よ！！）"

[[dialogue]]
speaker = "ルヴィネ"
# （ベアトたちが……私の名前を呼んでいる……）
line = "（ベアトたちが……私の名前を呼んでいる……）"

[[dialogue]]
speaker = "ルヴィネ"
# （でも、もう、返事をする力すらない……）
line = "（でも、もう、返事をする力すらない……）"

[[dialogue]]
speaker = "unk"
# 何とかして動きたい。何も心配いらないと見栄を張りたい──でも、指１本すら動かせない。
line = "何とかして動きたい。何も心配いらないと見栄を張りたい──でも、指１本すら動かせない。"

[[dialogue]]
speaker = "unk"
# さっきからずっと……ぽたぽたと──私の顔に落ちる、温かい涙の粒が、胸を締め付ける。
line = "さっきからずっと……ぽたぽたと──私の顔に落ちる、温かい涙の粒が、胸を締め付ける。"

[[dialogue]]
speaker = "unk"
# どんどん、どんどん──意識が遠のいていく────
line = "どんどん、どんどん──意識が遠のいていく────"

[[dialogue]]
speaker = "ルヴィネ"
# （ベアト。チナ。グレイス。レティシア……）
line = "（ベアト。チナ。グレイス。レティシア……）"

[[dialogue]]
speaker = "チナ"
# 「ルヴィ……！？」
line = "「ルヴィ……！？」"

[[dialogue]]
speaker = "ルヴィネ"
# （本当に……ごめんなさい…………）
line = "（本当に……ごめんなさい…………）"

[[dialogue]]
speaker = "グレイス"
# 「待って、待ってください……！」
line = "「待って、待ってください……！」"

[[dialogue]]
speaker = "ルヴィネ"
# （これからもみんな一緒にって……約束したそばから……）
line = "（これからもみんな一緒にって……約束したそばから……）"

[[dialogue]]
speaker = "レティシア"
# 「ルヴィ、目を閉じないで……だめ、だめよ……！！」
line = "「ルヴィ、目を閉じないで……だめ、だめよ……！！」"

[[dialogue]]
speaker = "ルヴィネ"
# （守れ──なくて────ご────め──────）
line = "（守れ──なくて────ご────め──────）"

[[dialogue]]
speaker = "ベアトリス"
# 「ルヴィ！？　いやあぁぁああぁああ──っ！！！」
line = "「ルヴィ！？　いやあぁぁああぁああ──っ！！！」"
