[[dialogue]]
speaker = "unk"
# 第７話,星騎士と守護星,B
line = "第７話,星騎士と守護星,B"

[[dialogue]]
speaker = "クロト"
# 「ふぅ──っと。なかなか手ごわい相手だったな」
line = "「ふぅ──っと。なかなか手ごわい相手だったな」"

[[dialogue]]
speaker = "アナ"
# 「計測終了です。お疲れさまでした」
line = "「計測終了です。お疲れさまでした」"

[[dialogue]]
speaker = "unk"
# モンスターを倒し終えると、バトルフィールドも終了した。
line = "モンスターを倒し終えると、バトルフィールドも終了した。"

[[dialogue]]
speaker = "unk"
# 力を測るということなので、全力を出した。それなりに早く討伐できたように思う。
line = "力を測るということなので、全力を出した。それなりに早く討伐できたように思う。"

[[dialogue]]
speaker = "クロト"
# 「これで俺のポテンシャルがわかる──のか？」
line = "「これで俺のポテンシャルがわかる──のか？」"

[[dialogue]]
speaker = "アナ"
# 「はい。結果がこちらになります」
line = "「はい。結果がこちらになります」"

[[dialogue]]
speaker = "unk"
# アナが施設にあった機械をピポパポと操作すると、ウィーンと電子画面が浮かび上がってきた。
line = "アナが施設にあった機械をピポパポと操作すると、ウィーンと電子画面が浮かび上がってきた。"

[[dialogue]]
speaker = "unk"
# <size=30>計測結果</size>
line = "<size=30>計測結果</size>"

[[dialogue]]
speaker = "unk"
# <size=30>TIME_02:45.00</size>
line = "<size=30>TIME_02:45.00</size>"

[[dialogue]]
speaker = "unk"
# <size=30>守護星：地球　適正属性：闇</size>
line = "<size=30>守護星：地球　適正属性：闇</size>"

[[dialogue]]
speaker = "アナ"
# 「２分４５秒──でもって守護星は……え？」
line = "「２分４５秒──でもって守護星は……え？」"

[[dialogue]]
speaker = "マトイ"
# 「これって……！」
line = "「これって……！」"

[[dialogue]]
speaker = "クロト"
# 「？」
line = "「？」"

[[dialogue]]
speaker = "unk"
# ２人が画面を見て何やら驚いていた。
line = "２人が画面を見て何やら驚いていた。"

[[dialogue]]
speaker = "unk"
# どうしたことかと訊ねようとすると……
line = "どうしたことかと訊ねようとすると……"

[[dialogue]]
speaker = "トワ先生"
# 「あ、こらーっ！　そこの生徒、勝手にトレーニングモードを起動するのは危険だからダメって言ったでしょ～！」
line = "「あ、こらーっ！　そこの生徒、勝手にトレーニングモードを起動するのは危険だからダメって言ったでしょ～！」"

[[dialogue]]
speaker = "マトイ"
# 「トワちゃん先生……！？」
line = "「トワちゃん先生……！？」"

[[dialogue]]
speaker = "トワ先生"
# 「ってあれ……星徒会のみんな？　それに緋宮くんも」
line = "「ってあれ……星徒会のみんな？　それに緋宮くんも」"

[[dialogue]]
speaker = "アナ"
# 「かくかくしかじかで必要になった。一応、許可はもらっています」
line = "「かくかくしかじかで必要になった。一応、許可はもらっています」"

[[dialogue]]
speaker = "クロト"
# 「俺の面倒を見てもらっています」
line = "「俺の面倒を見てもらっています」"

[[dialogue]]
speaker = "unk"
# 一般生徒と早とちりしたトワちゃん先生に、俺たちは経緯を説明した。
line = "一般生徒と早とちりしたトワちゃん先生に、俺たちは経緯を説明した。"

[[dialogue]]
speaker = "トワ先生"
# 「なるほどぉ～。それで、緋宮くんの腕前を測ってたわけだね～」
line = "「なるほどぉ～。それで、緋宮くんの腕前を測ってたわけだね～」"

[[dialogue]]
speaker = "トワ先生"
# 「どれどれ、先生が見てあげよぉ～」
line = "「どれどれ、先生が見てあげよぉ～」"

[[dialogue]]
speaker = "トワ先生"
# 「──ってえぇっ！？」
line = "「──ってえぇっ！？」"

[[dialogue]]
speaker = "クロト"
# 「先生にも驚かれてしまった……」
line = "「先生にも驚かれてしまった……」"

[[dialogue]]
speaker = "マトイ"
# 「だ、だってこんなのすごく珍しいもん──守護星が地球なんて！」
line = "「だ、だってこんなのすごく珍しいもん──守護星が地球なんて！」"

[[dialogue]]
speaker = "アナ"
# 「会長が気にかける理由が少しわかった気がします」
line = "「会長が気にかける理由が少しわかった気がします」"

[[dialogue]]
speaker = "クロト"
# 「そうなのか……？」
line = "「そうなのか……？」"

[[dialogue]]
speaker = "トワ先生"
# 「そうだよ！　わたしも教師として色んな生徒を見てきたけど……まさか地球とリンクしてる子がいるなんて思わなかった」
line = "「そうだよ！　わたしも教師として色んな生徒を見てきたけど……まさか地球とリンクしてる子がいるなんて思わなかった」"

[[dialogue]]
speaker = "クロト"
# 「そう言われると……守護星というのはそもそも何なのでしょう？」
line = "「そう言われると……守護星というのはそもそも何なのでしょう？」"

[[dialogue]]
speaker = "トワ先生"
# 「いい質問だね！」
line = "「いい質問だね！」"

[[dialogue]]
speaker = "トワ先生"
# 「守護星っていうのは<ruby=スターナイト>星騎士</ruby>が星力を借り受ける星のことだよ。あ、星力はわかるよね？」
line = "「守護星っていうのは<ruby>星騎士<rt>スターナイト</rt></ruby>が星力を借り受ける星のことだよ。あ、星力はわかるよね？」"

[[dialogue]]
speaker = "クロト"
# 「なんとなくは。こう、モンスターに対して有効なすごいパワーみたいな……？」
line = "「なんとなくは。こう、モンスターに対して有効なすごいパワーみたいな……？」"

[[dialogue]]
speaker = "トワ先生"
# 「うーん、ちょっと大雑把すぎるかなあ。転入してきたばかりだからしょうがないんだけどね！」
line = "「うーん、ちょっと大雑把すぎるかなあ。転入してきたばかりだからしょうがないんだけどね！」"

[[dialogue]]
speaker = "マトイ"
# 「（今までフィーリングだけであれだけ戦えてたんだ……逆にすごいかも……）」
line = "「（今までフィーリングだけであれだけ戦えてたんだ……逆にすごいかも……）」"

[[dialogue]]
speaker = "unk"
# 『星力』。
line = "『星力』。"

[[dialogue]]
speaker = "unk"
# 平たく言えば俺たち<ruby=スターナイト>星騎士</ruby>の扱う力の総称であり、たとえば戦闘服への変身も星々の加護を伴う。
line = "平たく言えば俺たち<ruby>星騎士<rt>スターナイト</rt></ruby>の扱う力の総称であり、たとえば戦闘服への変身も星々の加護を伴う。"

[[dialogue]]
speaker = "unk"
# また星力を扱うことができるのは「（ごく一部の例外を除き）」若年層に限られており、加齢と共にそのエネルギーは衰えていくという。
line = "また星力を扱うことができるのは「（ごく一部の例外を除き）」若年層に限られており、加齢と共にそのエネルギーは衰えていくという。"

[[dialogue]]
speaker = "unk"
# そして、人がその力を引き出す源の星を『守護星』と言うらしい。
line = "そして、人がその力を引き出す源の星を『守護星』と言うらしい。"

[[dialogue]]
speaker = "トワ先生"
# 「星騎士はまるで恋人みたいに、宇宙にある一つの星とリンクを結ぶよ。そして、その天体と交信することで『星力』を引き出せるってこと」
line = "「星騎士はまるで恋人みたいに、宇宙にある一つの星とリンクを結ぶよ。そして、その天体と交信することで『星力』を引き出せるってこと」"

[[dialogue]]
speaker = "トワ先生"
# 「緋宮くんとか詠野さんがモンスター相手に使ってる力も、ぜんぶ星力だからね」
line = "「緋宮くんとか詠野さんがモンスター相手に使ってる力も、ぜんぶ星力だからね」"

[[dialogue]]
speaker = "クロト"
# 「なるほど。みんな守護星から力を借りて戦ってるわけですね」
line = "「なるほど。みんな守護星から力を借りて戦ってるわけですね」"

[[dialogue]]
speaker = "トワ先生"
# 「そうそう！　ちなみに、例えば私の守護星なら『水星』だよ。アナちゃんは……」
line = "「そうそう！　ちなみに、例えば私の守護星なら『水星』だよ。アナちゃんは……」"

[[dialogue]]
speaker = "アナ"
# 「火星です。適正属性は炎」
line = "「火星です。適正属性は炎」"

[[dialogue]]
speaker = "クロト"
# 「へえ、火星か。なんとなく意外なイメージだな」
line = "「へえ、火星か。なんとなく意外なイメージだな」"

[[dialogue]]
speaker = "クロト"
# 「マトイは？」
line = "「マトイは？」"

[[dialogue]]
speaker = "マトイ"
# 「私はオシリス──って言っても、わかんないよね」
line = "「私はオシリス──って言っても、わかんないよね」"

[[dialogue]]
speaker = "マトイ"
# 「ペガスス座にある惑星なんだ。地球からはとんでもなく離れてるんだけど……」
line = "「ペガスス座にある惑星なんだ。地球からはとんでもなく離れてるんだけど……」"

[[dialogue]]
speaker = "クロト"
# 「へえ。でも、オシリスなんて強そうだな」
line = "「へえ。でも、オシリスなんて強そうだな」"

[[dialogue]]
speaker = "アナ"
# 「実際、オシリスの直径は太陽系のどの惑星よりも大きいです。私たちに身近じゃないだけですね」
line = "「実際、オシリスの直径は太陽系のどの惑星よりも大きいです。私たちに身近じゃないだけですね」"

[[dialogue]]
speaker = "トワ先生"
# 「守護星は自分じゃ選べないからね～。でも、それだけに運命的って感じがするよね～！」
line = "「守護星は自分じゃ選べないからね～。でも、それだけに運命的って感じがするよね～！」"

[[dialogue]]
speaker = "unk"
# 守護星の候補は、文字通り星の数だけ存在する。
line = "守護星の候補は、文字通り星の数だけ存在する。"

[[dialogue]]
speaker = "unk"
# 自分がどれと紐づくかの法則は解き明かされておらず、また星の質量が大きければ星力が強いというわけでもない。
line = "自分がどれと紐づくかの法則は解き明かされておらず、また星の質量が大きければ星力が強いというわけでもない。"

[[dialogue]]
speaker = "unk"
# どこまで星の加護を引き出せるかは──ひとえに、星騎士の腕にかかっているという話だった。
line = "どこまで星の加護を引き出せるかは──ひとえに、星騎士の腕にかかっているという話だった。"

[[dialogue]]
speaker = "クロト"
# 「それで俺の守護星『地球』はレアケースだと」
line = "「それで俺の守護星『地球』はレアケースだと」"

[[dialogue]]
speaker = "マトイ"
# 「うんうん！　まさか私たちの住んでる地球なんて……」
line = "「うんうん！　まさか私たちの住んでる地球なんて……」"

[[dialogue]]
speaker = "トワ先生"
# 「ヒーローっぽくて素敵だぞ、緋宮くん！」
line = "「ヒーローっぽくて素敵だぞ、緋宮くん！」"

[[dialogue]]
speaker = "マトイ"
# 「（主人公属性……いいなあ……）」
line = "「（主人公属性……いいなあ……）」"

[[dialogue]]
speaker = "unk"
# どうやら俺の守護星が『特別』なのは間違いないようだった。
line = "どうやら俺の守護星が『特別』なのは間違いないようだった。"

[[dialogue]]
speaker = "クロト"
# 「待てよ──ってことは。もしかしてこのタイムもかなりの高スコアなんじゃ……！？」
line = "「待てよ──ってことは。もしかしてこのタイムもかなりの高スコアなんじゃ……！？」"

[[dialogue]]
speaker = "マトイ"
# 「……いや」
line = "「……いや」"

[[dialogue]]
speaker = "アナ"
# 「そっちはフツー」
line = "「そっちはフツー」"

[[dialogue]]
speaker = "クロト"
# 「フツーなんかい」
line = "「フツーなんかい」"

[[dialogue]]
speaker = "トワ先生"
# 「あはは。そこそこ早いけど、Ｃランクモンスター相手だからね」
line = "「あはは。そこそこ早いけど、Ｃランクモンスター相手だからね」"

[[dialogue]]
speaker = "アナ"
# 「ただ、一般人ではありえないスコア。今まで市井の学校にいたものとは思えない」
line = "「ただ、一般人ではありえないスコア。今まで市井の学校にいたものとは思えない」"

[[dialogue]]
speaker = "クロト"
# 「環境のせいかな……」
line = "「環境のせいかな……」"

[[dialogue]]
speaker = "unk"
# 昔からモンスターにばかり好かれる俺は、そのぶん一人で対処しなくちゃいけない機会も多かった。
line = "昔からモンスターにばかり好かれる俺は、そのぶん一人で対処しなくちゃいけない機会も多かった。"

[[dialogue]]
speaker = "unk"
# しかしその甲斐あって、新星の編入試験にも受かれたと考えると……いいトレーニングだったのかもしれない。
line = "しかしその甲斐あって、新星の編入試験にも受かれたと考えると……いいトレーニングだったのかもしれない。"

[[dialogue]]
speaker = "アナ"
# 「Ｃランク討伐のタイムは新星全生徒の平均が確か３分１４秒。そもそも勝てない生徒の数も合わせると、はっきり上位には位置してる」
line = "「Ｃランク討伐のタイムは新星全生徒の平均が確か３分１４秒。そもそも勝てない生徒の数も合わせると、はっきり上位には位置してる」"

[[dialogue]]
speaker = "アナ"
# 「学園での訓練を積んでないのにこの数値で、しかも守護星は希少な地球。次期会長は優れた素質。現会長が目をつけたのも頷ける」
line = "「学園での訓練を積んでないのにこの数値で、しかも守護星は希少な地球。次期会長は優れた素質。現会長が目をつけたのも頷ける」"

[[dialogue]]
speaker = "マトイ"
# 「す、すごいんだ……」
line = "「す、すごいんだ……」"

[[dialogue]]
speaker = "unk"
# べた褒めだった。
line = "べた褒めだった。"

[[dialogue]]
speaker = "unk"
# なら──
line = "なら──"

[[dialogue]]
speaker = "クロト"
# 「星徒会長──ヴィーナスなら今の相手、どのくらいで倒せるんだ？」
line = "「星徒会長──ヴィーナスなら今の相手、どのくらいで倒せるんだ？」"

[[dialogue]]
speaker = "アナ"
# 「２秒」
line = "「２秒」"

[[dialogue]]
speaker = "クロト"
# 「２びょ……？」
line = "「２びょ……？」"

[[dialogue]]
speaker = "unk"
# 顔が引きつってしまった。
line = "顔が引きつってしまった。"

[[dialogue]]
speaker = "unk"
# 上出来と慢心しかけていた自分が恥ずかしくなるほどの開きがある。
line = "上出来と慢心しかけていた自分が恥ずかしくなるほどの開きがある。"

[[dialogue]]
speaker = "アナ"
# 「２秒もかからないかもしれない。Ｃランクならモンスターのほうが逃げてく」
line = "「２秒もかからないかもしれない。Ｃランクならモンスターのほうが逃げてく」"

[[dialogue]]
speaker = "トワ先生"
# 「うーん、九浄さんはねえ。ちょっと別格だからねえ」
line = "「うーん、九浄さんはねえ。ちょっと別格だからねえ」"

[[dialogue]]
speaker = "クロト"
# 「思った以上の化け物みたいだな……」
line = "「思った以上の化け物みたいだな……」"

[[dialogue]]
speaker = "アナ"
# 「むしろ現会長は星力の強さだけでその座についてると言っても過言じゃない。星騎士は実力主義」
line = "「むしろ現会長は星力の強さだけでその座についてると言っても過言じゃない。星騎士は実力主義」"

[[dialogue]]
speaker = "unk"
# そう言えば、机仕事はアナに任せっきりなんだっけか。
line = "そう言えば、机仕事はアナに任せっきりなんだっけか。"

[[dialogue]]
speaker = "unk"
# 俺はまだヴィーナスのことをよく知らないが、星徒会長というのはやはり伊達ではないらしい。
line = "俺はまだヴィーナスのことをよく知らないが、星徒会長というのはやはり伊達ではないらしい。"

[[dialogue]]
speaker = "クロト"
# 「もし俺がヴィーナスに勝とうと思ったら、この訓練でどのくらい太刀打ちできればいいんだ？」
line = "「もし俺がヴィーナスに勝とうと思ったら、この訓練でどのくらい太刀打ちできればいいんだ？」"

[[dialogue]]
speaker = "マトイ"
# 「少なくとも、Ｃランクは余裕で瞬殺できなきゃダメかも」
line = "「少なくとも、Ｃランクは余裕で瞬殺できなきゃダメかも」"

[[dialogue]]
speaker = "アナ"
# 「確か会長のハイスコアはＳランク相手に１０秒１１。互角にやるつもりならそのあたりを最終目標にしないと、厳しい」
line = "「確か会長のハイスコアはＳランク相手に１０秒１１。互角にやるつもりならそのあたりを最終目標にしないと、厳しい」"

[[dialogue]]
speaker = "トワ先生"
# 「アナちゃん、なんでも覚えててスゴイねぇ～」
line = "「アナちゃん、なんでも覚えててスゴイねぇ～」"

[[dialogue]]
speaker = "マトイ"
# 「ちなみに言うと……私でもＣランク相手なら１０秒かからないと思う」
line = "「ちなみに言うと……私でもＣランク相手なら１０秒かからないと思う」"

[[dialogue]]
speaker = "クロト"
# 「マトイもか。……強いんだな」
line = "「マトイもか。……強いんだな」"

[[dialogue]]
speaker = "アナ"
# 「星徒会メンバーなら大体それくらいが平均かと。過去の例を見ても」
line = "「星徒会メンバーなら大体それくらいが平均かと。過去の例を見ても」"

[[dialogue]]
speaker = "アナ"
# 「ただ、それを大きく上回るのが現会長です。少なくとも彼女と同じ域で星力を操れる生徒は過去にもいない」
line = "「ただ、それを大きく上回るのが現会長です。少なくとも彼女と同じ域で星力を操れる生徒は過去にもいない」"

[[dialogue]]
speaker = "unk"
# ヴィーナスが俺にどれほどの無茶振りを課したのか理解できた。
line = "ヴィーナスが俺にどれほどの無茶振りを課したのか理解できた。"

[[dialogue]]
speaker = "unk"
# しかし……
line = "しかし……"

[[dialogue]]
speaker = "クロト"
# 「Ｃランク相手に２分……か」
line = "「Ｃランク相手に２分……か」"

[[dialogue]]
speaker = "クロト"
# 「これまで何度もモンスターに襲われて。その度に勝てるよう鍛錬して、努力を積み重ねてきた結果がこれってことは……」
line = "「これまで何度もモンスターに襲われて。その度に勝てるよう鍛錬して、努力を積み重ねてきた結果がこれってことは……」"

[[dialogue]]
speaker = "マトイ"
# 「緋宮くん……」
line = "「緋宮くん……」"

[[dialogue]]
speaker = "アナ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "クロト"
# 「もっと努力するしかないってことだな」
line = "「もっと努力するしかないってことだな」"

[[dialogue]]
speaker = "マトイ"
# 「ポ、ポジティブなのね。やっぱり」
line = "「ポ、ポジティブなのね。やっぱり」"

[[dialogue]]
speaker = "unk"
# 険しい道のりなのはわかった。でも、それが諦める理由にはならない。
line = "険しい道のりなのはわかった。でも、それが諦める理由にはならない。"

[[dialogue]]
speaker = "unk"
# 何より、九浄ヴィーナス──彼女の底知れない強さを聞くたびに体がぞくぞくするのを感じていた。
line = "何より、九浄ヴィーナス──彼女の底知れない強さを聞くたびに体がぞくぞくするのを感じていた。"

[[dialogue]]
speaker = "クロト"
# 「俺の守護星は地球だ。つまり、地球からもっと力を引き出せればあいつくらい強い<ruby=スターナイト>星騎士</ruby>になれるってことだろう？」
line = "「俺の守護星は地球だ。つまり、地球からもっと力を引き出せればあいつくらい強い<ruby>星騎士<rt>スターナイト</rt></ruby>になれるってことだろう？」"

[[dialogue]]
speaker = "トワ先生"
# 「おお……」
line = "「おお……」"

[[dialogue]]
speaker = "アナ"
# 「でも、実際そう。もう受けちゃった以上しょうがない。私たちも応援する」
line = "「でも、実際そう。もう受けちゃった以上しょうがない。私たちも応援する」"

[[dialogue]]
speaker = "マトイ"
# 「……そうね。私も、あんまりネガティブなこと言うのは悪い癖かも」
line = "「……そうね。私も、あんまりネガティブなこと言うのは悪い癖かも」"

[[dialogue]]
speaker = "unk"
# マトイがそっと自身のセレスティアを俺へあてる。
line = "マトイがそっと自身のセレスティアを俺へあてる。"

[[dialogue]]
speaker = "unk"
# すると、俺の身にささやかな光が宿った。
line = "すると、俺の身にささやかな光が宿った。"

[[dialogue]]
speaker = "クロト"
# 「これは……」
line = "「これは……」"

[[dialogue]]
speaker = "マトイ"
# 「回復の星術──私はヒーラーが専門じゃないから、あんまり上手にできないけど」
line = "「回復の星術──私はヒーラーが専門じゃないから、あんまり上手にできないけど」"

[[dialogue]]
speaker = "マトイ"
# 「緋宮くんが頑張るなら、私もできる限り応援するよ！　入ったばかりなんだから──これからまだまだ伸びるってこともあると思う！」
line = "「緋宮くんが頑張るなら、私もできる限り応援するよ！　入ったばかりなんだから──これからまだまだ伸びるってこともあると思う！」"

[[dialogue]]
speaker = "unk"
# マトイに握られた手から、消耗した怪我や星力が癒やされていくのを感じた。
line = "マトイに握られた手から、消耗した怪我や星力が癒やされていくのを感じた。"

[[dialogue]]
speaker = "クロト"
# 「ありがとう──マトイ。世話になるよ」
line = "「ありがとう──マトイ。世話になるよ」"

[[dialogue]]
speaker = "マトイ"
# 「うん。て言っても、それでも会長に届くかどうかは……厳しいけど……」
line = "「うん。て言っても、それでも会長に届くかどうかは……厳しいけど……」"

[[dialogue]]
speaker = "アナ"
# 「明日から頑張りましょう──次期会長。星徒会の権限で、この施設をしばらく貸し切るようにしておきます」
line = "「明日から頑張りましょう──次期会長。星徒会の権限で、この施設をしばらく貸し切るようにしておきます」"

[[dialogue]]
speaker = "クロト"
# 「恩に着る。時間もないしな──やれることをやるしかない」
line = "「恩に着る。時間もないしな──やれることをやるしかない」"

[[dialogue]]
speaker = "unk"
# 俺のこれからの方針が決まった。
line = "俺のこれからの方針が決まった。"

[[dialogue]]
speaker = "unk"
# 一週間後に控えたヴィーナスとの果し合い──それまでに彼女を超えられるよう、己を鍛える。
line = "一週間後に控えたヴィーナスとの果し合い──それまでに彼女を超えられるよう、己を鍛える。"

[[dialogue]]
speaker = "アナ"
# 「それじゃ、打倒ヴィーナス現会長ということで。がんばろ～」
line = "「それじゃ、打倒ヴィーナス現会長ということで。がんばろ～」"

[[dialogue]]
speaker = "クロト"
# 「応！」
line = "「応！」"

[[dialogue]]
speaker = "マトイ"
# 「おー！」
line = "「おー！」"

[[dialogue]]
speaker = "トワ先生"
# 「おー？」
line = "「おー？」"

[[dialogue]]
speaker = "unk"
# そんなこんなで、俺はみんなの助力を得られるようになった。
line = "そんなこんなで、俺はみんなの助力を得られるようになった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# 月明かりの差す星徒会室。
line = "月明かりの差す星徒会室。"

[[dialogue]]
speaker = "unk"
# <b>現</b>星徒会長である九浄ヴィーナスはただ１人、窓の向こうを歩くクロトらを眺めてつぶやいた。
line = "<b>現</b>星徒会長である九浄ヴィーナスはただ１人、窓の向こうを歩くクロトらを眺めてつぶやいた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「目覚めなさい──緋宮クロト。あなたこそ真の魔王に他ならないわ」
line = "「目覚めなさい──緋宮クロト。あなたこそ真の魔王に他ならないわ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そして、私も……これから全力であなたにぶつかる。それが私の使命」
line = "「そして、私も……これから全力であなたにぶつかる。それが私の使命」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは開いていた日誌をパタンと閉じた。
line = "ヴィーナスは開いていた日誌をパタンと閉じた。"

[[dialogue]]
speaker = "unk"
# 万感の思いを、そのわずかな動作に込めるかのように。
line = "万感の思いを、そのわずかな動作に込めるかのように。"

[[dialogue]]
speaker = "ヴィーナス"
# 「私はこの時を……ずっと待ち続けてきたんだから！」
line = "「私はこの時を……ずっと待ち続けてきたんだから！」"
