[[dialogue]]
speaker = "unk"
# 第２３話,エピローグ1,B
line = "第２３話,エピローグ1,B"

[[dialogue]]
speaker = "unk"
# 翌日──
line = "翌日──"

[[dialogue]]
speaker = "unk"
# 強烈な疲労の反動をなんとかやり過ごした俺は、ゲストでなく正式なメンバーとして星徒会室にやって来ていた。
line = "強烈な疲労の反動をなんとかやり過ごした俺は、ゲストでなく正式なメンバーとして星徒会室にやって来ていた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「──さあ！　今日から<b>新生</b>星徒会のハッソクよ！　みんな準備はいいわね！？」
line = "「──さあ！　今日から<b>新生</b>星徒会のハッソクよ！　みんな準備はいいわね！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あれ？　でも、新生星徒会だと新星星徒会と被るわね。新生新星星徒会？　新星新生星徒会？　それとも……」
line = "「あれ？　でも、新生星徒会だと新星星徒会と被るわね。新生新星星徒会？　新星新生星徒会？　それとも……」"

[[dialogue]]
speaker = "マトイ"
# 「会長、そのあたりで」
line = "「会長、そのあたりで」"

[[dialogue]]
speaker = "アナ"
# 「あと、ハッソクじゃなくて、発足」
line = "「あと、ハッソクじゃなくて、発足」"

[[dialogue]]
speaker = "サーシャ"
# 「この部屋も賑やかになっていいわね～」
line = "「この部屋も賑やかになっていいわね～」"

[[dialogue]]
speaker = "unk"
# ヴィーナスはアホの子だった。
line = "ヴィーナスはアホの子だった。"

[[dialogue]]
speaker = "unk"
# 俺が加わり、この部屋に集うメンバーは５人となる。
line = "俺が加わり、この部屋に集うメンバーは５人となる。"

[[dialogue]]
speaker = "ヴィーナス"
# 「さて。それじゃあこの腕章をあなたに預けるわ──クロト」
line = "「さて。それじゃあこの腕章をあなたに預けるわ──クロト」"

[[dialogue]]
speaker = "クロト"
# 「ああ」
line = "「ああ」"

[[dialogue]]
speaker = "unk"
# 出会ったあの日以来初めて、ようやく正式に腕章が俺へ贈られる。
line = "出会ったあの日以来初めて、ようやく正式に腕章が俺へ贈られる。"

[[dialogue]]
speaker = "unk"
# 全星騎士の頂点にある証──
line = "全星騎士の頂点にある証──"

[[dialogue]]
speaker = "unk"
# 無論、今の俺にとっては過ぎた代物だから、これからも邁進していく必要があるだろう。
line = "無論、今の俺にとっては過ぎた代物だから、これからも邁進していく必要があるだろう。"

[[dialogue]]
speaker = "マトイ"
# 「ふう……どうなることかと思ったけど。結局ヴィーナスの我がままにさんざん振り回されちゃった」
line = "「ふう……どうなることかと思ったけど。結局ヴィーナスの我がままにさんざん振り回されちゃった」"

[[dialogue]]
speaker = "ヴィーナス"
# 「わ、我がままなんかじゃないわよ。クロトのことはしっかり書かれてたんだから」
line = "「わ、我がままなんかじゃないわよ。クロトのことはしっかり書かれてたんだから」"

[[dialogue]]
speaker = "クロト"
# 「ああ──そのことなんだが……」
line = "「ああ──そのことなんだが……」"

[[dialogue]]
speaker = "unk"
# こうして約束を果たせた以上、ちゃんと訊いてみたいと思っていた。
line = "こうして約束を果たせた以上、ちゃんと訊いてみたいと思っていた。"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナスはどうして俺のことを知って、待ち受けてたんだ？」
line = "「ヴィーナスはどうして俺のことを知って、待ち受けてたんだ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「？　前にも言った通りよ、これのおかげ」
line = "「？　前にも言った通りよ、これのおかげ」"

[[dialogue]]
speaker = "unk"
# そう言うと、ヴィーナスは以前と同じく一冊の書物を取り出した。
line = "そう言うと、ヴィーナスは以前と同じく一冊の書物を取り出した。"

[[dialogue]]
speaker = "ヴィーナス"
# 「この『未来日誌』にしかと記されていたの。魔王クロト──あなたがあの日、新星学園を訪れるってことはね！」
line = "「この『未来日誌』にしかと記されていたの。魔王クロト──あなたがあの日、新星学園を訪れるってことはね！」"

[[dialogue]]
speaker = "unk"
# ででん。胸を張るヴィーナス。待ってもそれ以上の理由は出てこなかった。
line = "ででん。胸を張るヴィーナス。待ってもそれ以上の理由は出てこなかった。"

[[dialogue]]
speaker = "クロト"
# 「それは……君が書いたものだろ？」
line = "「それは……君が書いたものだろ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「違うわ。けれど、昔からずっとあの日の出来事はここにはっきり書かれていたわ」
line = "「違うわ。けれど、昔からずっとあの日の出来事はここにはっきり書かれていたわ」"

[[dialogue]]
speaker = "unk"
# また、前と同じく占い師のようなことを言われる。
line = "また、前と同じく占い師のようなことを言われる。"

[[dialogue]]
speaker = "unk"
# 前回はてっきり煙に巻かれたのだと思っていたが……
line = "前回はてっきり煙に巻かれたのだと思っていたが……"

[[dialogue]]
speaker = "クロト"
# 「彼女は本気なのか？」
line = "「彼女は本気なのか？」"

[[dialogue]]
speaker = "サーシャ"
# 「うん」
line = "「うん」"

[[dialogue]]
speaker = "ヴィーナス"
# 「どういう意味よ！」
line = "「どういう意味よ！」"

[[dialogue]]
speaker = "アナ"
# 「トンデモオカルトアイテムですが、あれが新会長の到来を言い当てていたことは事実です。私も春ごろに確認していました」
line = "「トンデモオカルトアイテムですが、あれが新会長の到来を言い当てていたことは事実です。私も春ごろに確認していました」"

[[dialogue]]
speaker = "マトイ"
# 「え、そうなの？」
line = "「え、そうなの？」"

[[dialogue]]
speaker = "クロト"
# 「俺が転入試験を受ける前から……？　どういう理屈なんだ」
line = "「俺が転入試験を受ける前から……？　どういう理屈なんだ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「まあまあ、いいじゃない。赤坂レコードみたいなものよ」
line = "「まあまあ、いいじゃない。赤坂レコードみたいなものよ」"

[[dialogue]]
speaker = "アナ"
# 「アカシックレコードです」
line = "「アカシックレコードです」"

[[dialogue]]
speaker = "unk"
# なんでも、彼女すら<ruby=あずか>与</ruby>り知らない誰かによって書かれた謎の日誌──
line = "なんでも、彼女すら<ruby>与<rt>あずか</rt></ruby>り知らない誰かによって書かれた謎の日誌──"

[[dialogue]]
speaker = "unk"
# 未来の出来事を日誌という形で予言するため、そう称しているらしい。
line = "未来の出来事を日誌という形で予言するため、そう称しているらしい。"

[[dialogue]]
speaker = "クロト"
# 「（まったく理解はできないが……これ以上の説明は出てこなそうだし、一旦考えるのはやめよう）」
line = "「（まったく理解はできないが……これ以上の説明は出てこなそうだし、一旦考えるのはやめよう）」"

[[dialogue]]
speaker = "unk"
# 今はとりあえず、この新生星徒会で俺がどうしていくかだ。
line = "今はとりあえず、この新生星徒会で俺がどうしていくかだ。"

[[dialogue]]
speaker = "サーシャ"
# 「ちなみに～。これからヴィーナスちゃんはどういう立場になるの？」
line = "「ちなみに～。これからヴィーナスちゃんはどういう立場になるの？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んーと……なんだろ？　顧問専務理事？」
line = "「んーと……なんだろ？　顧問専務理事？」"

[[dialogue]]
speaker = "マトイ"
# 「天下りじゃないですか」
line = "「天下りじゃないですか」"

[[dialogue]]
speaker = "クロト"
# 「なんでそういうことは知ってるんだ」
line = "「なんでそういうことは知ってるんだ」"

[[dialogue]]
speaker = "アナ"
# 「ＯＧ、ではダメなのでしょうか」
line = "「ＯＧ、ではダメなのでしょうか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「別に卒業生ってワケでもないし、盛り上がらないわよね。私に合うビューティな役職を考えておくわ！」
line = "「別に卒業生ってワケでもないし、盛り上がらないわよね。私に合うビューティな役職を考えておくわ！」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは星徒会に残りつつ、新たなポジションに生まれ変わると張り切っていた。
line = "ヴィーナスは星徒会に残りつつ、新たなポジションに生まれ変わると張り切っていた。"

[[dialogue]]
speaker = "unk"
# 他のみんなについては、これまで通りの役職に就くようだ。
line = "他のみんなについては、これまで通りの役職に就くようだ。"

[[dialogue]]
speaker = "クロト"
# 「それで……星徒会長と言っても、何をすればいいんだ」
line = "「それで……星徒会長と言っても、何をすればいいんだ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ドーンと構えて座ってればいいの！　威厳を見せるのが会長のお仕事！」
line = "「ドーンと構えて座ってればいいの！　威厳を見せるのが会長のお仕事！」"

[[dialogue]]
speaker = "サーシャ"
# 「本当は事務仕事も会長の責務なんだけど～……」
line = "「本当は事務仕事も会長の責務なんだけど～……」"

[[dialogue]]
speaker = "アナ"
# 「前会長に任せてると日が暮れても終わらないから私がやってた。だけ」
line = "「前会長に任せてると日が暮れても終わらないから私がやってた。だけ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうでした！　アナありがと！」
line = "「そうでした！　アナありがと！」"

[[dialogue]]
speaker = "unk"
# アナはすごく優秀だった。
line = "アナはすごく優秀だった。"

[[dialogue]]
speaker = "unk"
# しかし、となるとその仕事も俺が引き継ぐことに……？
line = "しかし、となるとその仕事も俺が引き継ぐことに……？"

[[dialogue]]
speaker = "マトイ"
# 「でも、緋宮くんはまだ学園のこともよくわからないだろうし……」
line = "「でも、緋宮くんはまだ学園のこともよくわからないだろうし……」"

[[dialogue]]
speaker = "アナ"
# 「うん。基本的には今まで通り、机仕事は私がやる」
line = "「うん。基本的には今まで通り、机仕事は私がやる」"

[[dialogue]]
speaker = "クロト"
# 「本当か。助かるよ、アナ」
line = "「本当か。助かるよ、アナ」"

[[dialogue]]
speaker = "unk"
# この小さい一年生には、ずっと世話になりっぱなしだな。
line = "この小さい一年生には、ずっと世話になりっぱなしだな。"

[[dialogue]]
speaker = "アナ"
# 「でも、新会長は前会長より考えてくれそうなので、少しは仕事を戻そうかと」
line = "「でも、新会長は前会長より考えてくれそうなので、少しは仕事を戻そうかと」"

[[dialogue]]
speaker = "クロト"
# 「はは……お手柔らかに」
line = "「はは……お手柔らかに」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なんか、私がすごくバカにされてるような」
line = "「なんか、私がすごくバカにされてるような」"

[[dialogue]]
speaker = "マトイ"
# 「そ、そんなことないよ。会長にはカリスマがあったから！」
line = "「そ、そんなことないよ。会長にはカリスマがあったから！」"

[[dialogue]]
speaker = "サーシャ"
# 「マトイちゃん～。会長はもう会長じゃないのよ～」
line = "「マトイちゃん～。会長はもう会長じゃないのよ～」"

[[dialogue]]
speaker = "マトイ"
# 「あ……そうでした」
line = "「あ……そうでした」"

[[dialogue]]
speaker = "クロト"
# 「慣れないだろうが、よろしく頼む。マトイのことも頼りにしてるよ」
line = "「慣れないだろうが、よろしく頼む。マトイのことも頼りにしてるよ」"

[[dialogue]]
speaker = "マトイ"
# 「わ、わかったわ……会長。なんか照れるけど」
line = "「わ、わかったわ……会長。なんか照れるけど」"

[[dialogue]]
speaker = "クロト"
# 「はは、基本的には今まで通りでいてくれ」
line = "「はは、基本的には今まで通りでいてくれ」"

[[dialogue]]
speaker = "unk"
# それから俺は、皆に星徒会の役目について聞いた。
line = "それから俺は、皆に星徒会の役目について聞いた。"

[[dialogue]]
speaker = "unk"
# イベントの執行だったり、予算の編成だったり……大きすぎる権限に改めて戸惑いもしたけれど。
line = "イベントの執行だったり、予算の編成だったり……大きすぎる権限に改めて戸惑いもしたけれど。"

[[dialogue]]
speaker = "マトイ"
# 「それと……何より大事なのは、リクリエの予兆が起こった時の出動ね」
line = "「それと……何より大事なのは、リクリエの予兆が起こった時の出動ね」"

[[dialogue]]
speaker = "クロト"
# 「！　前みたいな──だな」
line = "「！　前みたいな──だな」"

[[dialogue]]
speaker = "unk"
# 世界中で混乱を起こしている目下の大事──リクリエ。
line = "世界中で混乱を起こしている目下の大事──リクリエ。"

[[dialogue]]
speaker = "unk"
# その到来が近づくにつれ起きる予兆は、各地にモンスター出現などのトラブルを引き起こす。
line = "その到来が近づくにつれ起きる予兆は、各地にモンスター出現などのトラブルを引き起こす。"

[[dialogue]]
speaker = "unk"
# そもそも<ruby=おれたち>星騎士</ruby>の存在意義が街や人の防衛である以上、星徒会がその先頭に立つのは自然なことだった。
line = "そもそも<ruby>星騎士<rt>おれたち</rt></ruby>の存在意義が街や人の防衛である以上、星徒会がその先頭に立つのは自然なことだった。"

[[dialogue]]
speaker = "マトイ"
# 「私たち星徒会は全星騎士たちの代表。だから、どんなトラブルでも即座に駆けつける必要がある」
line = "「私たち星徒会は全星騎士たちの代表。だから、どんなトラブルでも即座に駆けつける必要がある」"

[[dialogue]]
speaker = "クロト"
# 「ああ、知ってるさ。そのために頑張ってきたんだからな」
line = "「ああ、知ってるさ。そのために頑張ってきたんだからな」"

[[dialogue]]
speaker = "アナ"
# 「授業中であっても基本的には出動優先。街中に被害が出るのは避けなきゃならないので」
line = "「授業中であっても基本的には出動優先。街中に被害が出るのは避けなきゃならないので」"

[[dialogue]]
speaker = "unk"
# 俺がみんなに助けてもらったように。
line = "俺がみんなに助けてもらったように。"

[[dialogue]]
speaker = "unk"
# 今後は、俺が街の人たちを助ける役割を担うわけだ。
line = "今後は、俺が街の人たちを助ける役割を担うわけだ。"

[[dialogue]]
speaker = "ヴィーナス"
# 「でも！　これからはあのクロトが戦力に加わるんだから、どんなモンスターが来ても余裕よね！」
line = "「でも！　これからはあのクロトが戦力に加わるんだから、どんなモンスターが来ても余裕よね！」"

[[dialogue]]
speaker = "クロト"
# 「あー……それなんだけど」
line = "「あー……それなんだけど」"

[[dialogue]]
speaker = "unk"
# ヴィーナスにまだ説明できていなかったので、改めてみんなに伝えた。
line = "ヴィーナスにまだ説明できていなかったので、改めてみんなに伝えた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「へ──もうあの状態になれないの！？」
line = "「へ──もうあの状態になれないの！？」"

[[dialogue]]
speaker = "クロト"
# 「わからない。けど、少なくとも自由にはなれない」
line = "「わからない。けど、少なくとも自由にはなれない」"

[[dialogue]]
speaker = "サーシャ"
# 「あの時のクロトくん、つよつよだったのにね～」
line = "「あの時のクロトくん、つよつよだったのにね～」"

[[dialogue]]
speaker = "マトイ"
# 「暴走してたってこと……？」
line = "「暴走してたってこと……？」"

[[dialogue]]
speaker = "アナ"
# 「コントロールはできてたから、どちらかというとスイッチが入らないと言うべき。何か条件があるのかも」
line = "「コントロールはできてたから、どちらかというとスイッチが入らないと言うべき。何か条件があるのかも」"

[[dialogue]]
speaker = "unk"
# やはり、またピンチにならないとダメなのだろうか？
line = "やはり、またピンチにならないとダメなのだろうか？"

[[dialogue]]
speaker = "unk"
# だが、個人的な感覚としてはそれもちょっと違う気がしていた。
line = "だが、個人的な感覚としてはそれもちょっと違う気がしていた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロトの魔王スイッチ！　ここね！」
line = "「クロトの魔王スイッチ！　ここね！」"

[[dialogue]]
speaker = "サーシャ"
# 「違うわヴィーナスちゃん、ここよ～」
line = "「違うわヴィーナスちゃん、ここよ～」"

[[dialogue]]
speaker = "クロト"
# 「ちょ──お尻を触るのはやめてください！」
line = "「ちょ──お尻を触るのはやめてください！」"

[[dialogue]]
speaker = "unk"
# などと、益体もないやり取りを続けていると……
line = "などと、益体もないやり取りを続けていると……"

[[dialogue]]
speaker = "マトイ"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "アナ"
# 「学園長……」
line = "「学園長……」"
