[[dialogue]]
speaker = "unk"
# 第４話,ポラリスの再会,B
line = "第４話,ポラリスの再会,B"

[[dialogue]]
speaker = "ルヴィネ"
# 「みんな。久しぶりね」
line = "「みんな。久しぶりね」"

[[dialogue]]
speaker = "unk"
# 戦闘服に変身すらせずに、ルヴィネは友人たちに語りかける。
line = "戦闘服に変身すらせずに、ルヴィネは友人たちに語りかける。"

[[dialogue]]
speaker = "ルヴィネ"
# 「チナ。よく無事でいてくれたわね。あなたではなく、緋宮クロトたちがデネブに来た時は驚いたわ」
line = "「チナ。よく無事でいてくれたわね。あなたではなく、緋宮クロトたちがデネブに来た時は驚いたわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「『チナは無事だ』と聞いていたけれど……やっぱりこの目で見るまでは不安だったから。元気そうで何より」
line = "「『チナは無事だ』と聞いていたけれど……やっぱりこの目で見るまでは不安だったから。元気そうで何より」"

[[dialogue]]
speaker = "チナ"
# 「…………何、言ってんだよ。ルヴィ」
line = "「…………何、言ってんだよ。ルヴィ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「グレイス、レティシア。天界襲撃は失敗したみたいね」
line = "「グレイス、レティシア。天界襲撃は失敗したみたいね」"

[[dialogue]]
speaker = "ルヴィネ"
# 「転送装置を使って戻ってこないから……あの日から今日まで、ずっと眠りが浅かった」
line = "「転送装置を使って戻ってこないから……あの日から今日まで、ずっと眠りが浅かった」"

[[dialogue]]
speaker = "ルヴィネ"
# 「あなたたちがただ捕まっているだけなのか、それとも命を落としてしまったのか、わからなかったから……」
line = "「あなたたちがただ捕まっているだけなのか、それとも命を落としてしまったのか、わからなかったから……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「安心したわ。２人とも、元気そうね」
line = "「安心したわ。２人とも、元気そうね」"

[[dialogue]]
speaker = "レティシア"
# 「…………ルヴィ」
line = "「…………ルヴィ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ベアトとは、デネブで一度会って以来ね……」
line = "「ベアトとは、デネブで一度会って以来ね……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「もう５人で集まれることはないと思ってた。だからこうして会えて……本当に嬉しいわ」
line = "「もう５人で集まれることはないと思ってた。だからこうして会えて……本当に嬉しいわ」"

[[dialogue]]
speaker = "グレイス"
# 「──やめてくださいルヴィ！　私たちは……真実を確かめに来たんです！」
line = "「──やめてくださいルヴィ！　私たちは……真実を確かめに来たんです！」"

[[dialogue]]
speaker = "グレイス"
# 「天界襲撃の日から今日まで……いろんなことがあって！　いろんな話を聞いて……混乱してるんです！！」
line = "「天界襲撃の日から今日まで……いろんなことがあって！　いろんな話を聞いて……混乱してるんです！！」"

[[dialogue]]
speaker = "グレイス"
# 「リクリエモンスターと極星従騎が今、一緒になって地上を攻撃しています……どうしてですか！？」
line = "「リクリエモンスターと極星従騎が今、一緒になって地上を攻撃しています……どうしてですか！？」"

[[dialogue]]
speaker = "グレイス"
# 「ルヴィの口から聞きたいんです、真実を！　あなたはいったい──」
line = "「ルヴィの口から聞きたいんです、真実を！　あなたはいったい──」"

[[dialogue]]
speaker = "ルヴィネ"
# 「──<b>そうよ</b>」
line = "「──<b>そうよ</b>」"

[[dialogue]]
speaker = "レティシア"
# 「……そうよ、って。どういう意味なの、ルヴィ？」
line = "「……そうよ、って。どういう意味なの、ルヴィ？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「私は女神テルルの遣いの天使ではない。そしてデネブを守る救世主でもない──という意味よ。レティシア」
line = "「私は女神テルルの遣いの天使ではない。そしてデネブを守る救世主でもない──という意味よ。レティシア」"

[[dialogue]]
speaker = "ルヴィネ"
# 「私は、あなたたちが『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』と呼ぶ神によって創り出された、新時代の女神……その幼体」
line = "「私は、あなたたちが『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』と呼ぶ神によって創り出された、新時代の女神……その幼体」"

[[dialogue]]
speaker = "ルヴィネ"
# 「デネブとアルタイルも、ベガと同じ末路を辿るよう……リクリエを起こすことを目的に、地上へ遣わされた」
line = "「デネブとアルタイルも、ベガと同じ末路を辿るよう……リクリエを起こすことを目的に、地上へ遣わされた」"

[[dialogue]]
speaker = "ルヴィネ"
# 「出来損ないの女神テルルに代わる、新たな女神。世界と人類に、成長と進化をもたらす者よ」
line = "「出来損ないの女神テルルに代わる、新たな女神。世界と人類に、成長と進化をもたらす者よ」"

[[dialogue]]
speaker = "unk"
# あまりに簡単に認めるルヴィネの態度に、チナの心がざわつく。
line = "あまりに簡単に認めるルヴィネの態度に、チナの心がざわつく。"

[[dialogue]]
speaker = "チナ"
# 「……なんでだ。どうして……どうして言い訳の一つもしないんだよ、ルヴィ！？」
line = "「……なんでだ。どうして……どうして言い訳の一つもしないんだよ、ルヴィ！？」"

[[dialogue]]
speaker = "チナ"
# 「アルタイルの奴らに出まかせを吹き込まれてるんだって……幼なじみの私を信じてくれって……下手くそでもいいから言い訳してくれよ！！」
line = "「アルタイルの奴らに出まかせを吹き込まれてるんだって……幼なじみの私を信じてくれって……下手くそでもいいから言い訳してくれよ！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「無駄だわ、そんなこと」
line = "「無駄だわ、そんなこと」"

[[dialogue]]
speaker = "ルヴィネ"
# 「デネブの塔の頂上で……ベアトにディザスターハンドと共にいるところを見られている」
line = "「デネブの塔の頂上で……ベアトにディザスターハンドと共にいるところを見られている」"

[[dialogue]]
speaker = "ルヴィネ"
# 「それにチナ。あなたもアルタイルに留まっている間に、たくさんのことを見聞きしてきたのでしょう？」
line = "「それにチナ。あなたもアルタイルに留まっている間に、たくさんのことを見聞きしてきたのでしょう？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「だったら……隠したりごまかしたりしても意味がない」
line = "「だったら……隠したりごまかしたりしても意味がない」"

[[dialogue]]
speaker = "ルヴィネ"
# 「私たち、ずっと長いこと一緒にいたんだもの。嘘を吐いたところですぐにばれる──何事も合理的に運ばないといけないわ」
line = "「私たち、ずっと長いこと一緒にいたんだもの。嘘を吐いたところですぐにばれる──何事も合理的に運ばないといけないわ」"

[[dialogue]]
speaker = "ベアトリス"
# 「……ルヴィ。そんな言い方、ひどいよ……」
line = "「……ルヴィ。そんな言い方、ひどいよ……」"

[[dialogue]]
speaker = "チナ"
# 「だったら聞かせろ！！　１０年前、お前はアタシたちを救ってくれたじゃないか！？」
line = "「だったら聞かせろ！！　１０年前、お前はアタシたちを救ってくれたじゃないか！？」"

[[dialogue]]
speaker = "チナ"
# 「リクリエを起こすのが目的なら……なんであんなことしたんだ！！　それこそ無駄じゃないか！！」
line = "「リクリエを起こすのが目的なら……なんであんなことしたんだ！！　それこそ無駄じゃないか！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「そういう『命令』だったからよ」
line = "「そういう『命令』だったからよ」"

[[dialogue]]
speaker = "レティシア"
# 「……命令？」
line = "「……命令？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「そう。『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』…………お父様からの、命令」
line = "「そう。『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』…………お父様からの、命令」"

[[dialogue]]
speaker = "ルヴィネ"
# 「私は『デネブの緋宮クロト』が死んだ、その日に創造された」
line = "「私は『デネブの緋宮クロト』が死んだ、その日に創造された」"

[[dialogue]]
speaker = "ルヴィネ"
# 「最初にかけられた言葉は『世界をリセットしろ』。その目的のためだけに、私は造られたわ」
line = "「最初にかけられた言葉は『世界をリセットしろ』。その目的のためだけに、私は造られたわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「３０００年前──魔王ラクシスはリクリエを跳ねのけた。そして光の魔女の禁術によって『生まれ直し』まで行った……」
line = "「３０００年前──魔王ラクシスはリクリエを跳ねのけた。そして光の魔女の禁術によって『生まれ直し』まで行った……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「デネブ、アルタイル、ベガ──それらの発生は、魔王ラクシスが、緋宮クロトとして再誕したことによって生まれたもの」
line = "「デネブ、アルタイル、ベガ──それらの発生は、魔王ラクシスが、緋宮クロトとして再誕したことによって生まれたもの」"

[[dialogue]]
speaker = "ルヴィネ"
# 「お父様は危惧された。世界が３つに分かれたことで……よりリクリエの達成が困難になってしまったから」
line = "「お父様は危惧された。世界が３つに分かれたことで……よりリクリエの達成が困難になってしまったから」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ベガは、リクリエによって堕ちた緋宮クロト……ディザスターハンドが滅ぼした。けれどデネブとアルタイルは違った」
line = "「ベガは、リクリエによって堕ちた緋宮クロト……ディザスターハンドが滅ぼした。けれどデネブとアルタイルは違った」"

[[dialogue]]
speaker = "ルヴィネ"
# 「デネブの緋宮クロトは、自らの力の脅威に気づいていたの。平行世界に干渉することができる──お父様でさえ容易ではないその権能」
line = "「デネブの緋宮クロトは、自らの力の脅威に気づいていたの。平行世界に干渉することができる──お父様でさえ容易ではないその権能」"

[[dialogue]]
speaker = "ルヴィネ"
# 「その力を再利用されることを恐れたデネブの緋宮クロトは、自らの力を暴走させ──跡形もなく爆散することで神の支配を逃れたのよ」
line = "「その力を再利用されることを恐れたデネブの緋宮クロトは、自らの力を暴走させ──跡形もなく爆散することで神の支配を逃れたのよ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「おまけに女神との間に作った、御子だなんていう異物まで平行世界に飛ばす始末……」
line = "「おまけに女神との間に作った、御子だなんていう異物まで平行世界に飛ばす始末……」"

[[dialogue]]
speaker = "グレイス"
# 「……九浄、ヴィーナスさん。デネブの魔王さんが、死の間際に、アルタイルに送ったと……」
line = "「……九浄、ヴィーナスさん。デネブの魔王さんが、死の間際に、アルタイルに送ったと……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「そうよ。平行世界の中で、最も時の流れが遅れていたのがアルタイル。そこへ御子という異物が紛れてしまった」
line = "「そうよ。平行世界の中で、最も時の流れが遅れていたのがアルタイル。そこへ御子という異物が紛れてしまった」"

[[dialogue]]
speaker = "ルヴィネ"
# 「お父様は強い脅威を感じられた。アルタイルで覚醒する魔王は、九浄ヴィーナスの影響で、デネブよりも厄介な存在に成長するだろうと」
line = "「お父様は強い脅威を感じられた。アルタイルで覚醒する魔王は、九浄ヴィーナスの影響で、デネブよりも厄介な存在に成長するだろうと」"

[[dialogue]]
speaker = "ルヴィネ"
# 「だから私に命じられた……強大に成長するアルタイルの力を削ぐために、滅びかかったデネブを利用しろ、とね」
line = "「だから私に命じられた……強大に成長するアルタイルの力を削ぐために、滅びかかったデネブを利用しろ、とね」"

[[dialogue]]
speaker = "ルヴィネ"
# 「使徒マルキアとの戦いで滅びの一歩手前までいったデネブ。けれどまだ搾れる。利用価値がある。だから復興させよ、と」
line = "「使徒マルキアとの戦いで滅びの一歩手前までいったデネブ。けれどまだ搾れる。利用価値がある。だから復興させよ、と」"

[[dialogue]]
speaker = "チナ"
# 「……だから？　『命令』されたから……１０年前、アタシたちを助けたって？」
line = "「……だから？　『命令』されたから……１０年前、アタシたちを助けたって？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ええ。お父様から、ヒトを懐柔するための情報はたくさんもらっていたわ」
line = "「ええ。お父様から、ヒトを懐柔するための情報はたくさんもらっていたわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「親切にされると、ヒトは喜ぶ。自己犠牲を見せつけると、ヒトは心を許す──」
line = "「親切にされると、ヒトは喜ぶ。自己犠牲を見せつけると、ヒトは心を許す──」"

[[dialogue]]
speaker = "ルヴィネ"
# 「デネブの緋宮クロトの自爆の影響で、時空がねじれて……陸の孤島となった流星市国は都合がよかった」
line = "「デネブの緋宮クロトの自爆の影響で、時空がねじれて……陸の孤島となった流星市国は都合がよかった」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……あまりに過酷で、何度か死にかけもしたけれど。結果として私は、流星市国の住人のほとんどを懐柔できた」
line = "「……あまりに過酷で、何度か死にかけもしたけれど。結果として私は、流星市国の住人のほとんどを懐柔できた」"

[[dialogue]]
speaker = "ルヴィネ"
# 「１０年間……本当に長かったわ」
line = "「１０年間……本当に長かったわ」"

[[dialogue]]
speaker = "グレイス"
# 「……やっぱり、嘘だったんですね。魔王さんは逃げ出してなんかいない……ルヴィは、全てを知っていた！」
line = "「……やっぱり、嘘だったんですね。魔王さんは逃げ出してなんかいない……ルヴィは、全てを知っていた！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「デネブの魔王の最期は、生まれた時にお父様から全て聞いていたわ」
line = "「デネブの魔王の最期は、生まれた時にお父様から全て聞いていたわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「捨て身の自爆で、最強の使徒だったマルキアとも刺し違えて、デネブを滅びから救った。ヒトの目から見たら、疑いようのない英雄でしょう」
line = "「捨て身の自爆で、最強の使徒だったマルキアとも刺し違えて、デネブを滅びから救った。ヒトの目から見たら、疑いようのない英雄でしょう」"

[[dialogue]]
speaker = "グレイス"
# 「──ふざけないでください！！　ずっと、ずっと騙していたんですね！？　私があれだけ否定していたのに……！！」
line = "「──ふざけないでください！！　ずっと、ずっと騙していたんですね！？　私があれだけ否定していたのに……！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「グレイスはあの避難地で一番強情だったわね。なかなか認めてくれないから、苦労したわ」
line = "「グレイスはあの避難地で一番強情だったわね。なかなか認めてくれないから、苦労したわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「でもあの嘘は、吐いた方が得だった。だって緋宮クロトの人気は便利だもの」
line = "「でもあの嘘は、吐いた方が得だった。だって緋宮クロトの人気は便利だもの」"

[[dialogue]]
speaker = "ルヴィネ"
# 「彼に向いていた信頼と尊敬を、そっくりそのまま私に移すことができれば……デネブを懐柔する上で大幅なショートカットになる」
line = "「彼に向いていた信頼と尊敬を、そっくりそのまま私に移すことができれば……デネブを懐柔する上で大幅なショートカットになる」"

[[dialogue]]
speaker = "グレイス"
# 「許せません！　私たちを騙していた以上に、許せない！！　魔王さんへの侮辱、愚弄ッ……よくもあんな優しい人を……！！」
line = "「許せません！　私たちを騙していた以上に、許せない！！　魔王さんへの侮辱、愚弄ッ……よくもあんな優しい人を……！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ええ。その怒りと嫌悪は、妥当なものだと思うわ」
line = "「ええ。その怒りと嫌悪は、妥当なものだと思うわ」"

[[dialogue]]
speaker = "グレイス"
# 「ルヴィ──！！」
line = "「ルヴィ──！！」"

[[dialogue]]
speaker = "unk"
# 今にもルヴィネにつかみかかろうとするグレイス──しかし、その動きを止めたのは、他ならぬグレイス自身だった。
line = "今にもルヴィネにつかみかかろうとするグレイス──しかし、その動きを止めたのは、他ならぬグレイス自身だった。"

[[dialogue]]
speaker = "グレイス"
# 「どうしてっ……なんで！　よりによってルヴィが……魔王さんを……」
line = "「どうしてっ……なんで！　よりによってルヴィが……魔王さんを……」"

[[dialogue]]
speaker = "グレイス"
# 「私の大切な友達が……私の好きだった人を……貶めるんですか…………！？」
line = "「私の大切な友達が……私の好きだった人を……貶めるんですか…………！？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "レティシア"
# 「──ルヴィ。どうして最初から、全てを言ってくれなかったの？」
line = "「──ルヴィ。どうして最初から、全てを言ってくれなかったの？」"

[[dialogue]]
speaker = "レティシア"
# 「ルヴィが女神で、その目的がリクリエを起こすことでも。昔の私ならきっと受け入れたのに……」
line = "「ルヴィが女神で、その目的がリクリエを起こすことでも。昔の私ならきっと受け入れたのに……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……そうかしら？　私はそうは思わないわ」
line = "「……そうかしら？　私はそうは思わないわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「レティシア。あなたは私の指示に忠実だった。私が命令したら、命だって捨ててくれたでしょう」
line = "「レティシア。あなたは私の指示に忠実だった。私が命令したら、命だって捨ててくれたでしょう」"

[[dialogue]]
speaker = "レティシア"
# 「ええ。私にとってルヴィの命令は絶対……『空っぽ』の私なら、きっと言うことを聞いて──」
line = "「ええ。私にとってルヴィの命令は絶対……『空っぽ』の私なら、きっと言うことを聞いて──」"

[[dialogue]]
speaker = "ルヴィネ"
# 「でもあなたは──『空っぽ』なんかじゃないわ」
line = "「でもあなたは──『空っぽ』なんかじゃないわ」"

[[dialogue]]
speaker = "unk"
# 緋宮クロトや奏サーシャに言われたのと同じ言葉を投げかけられ、レティシアが口を<ruby=つぐ>噤</ruby>む。
line = "緋宮クロトや奏サーシャに言われたのと同じ言葉を投げかけられ、レティシアが口を<ruby>噤<rt>つぐ</rt></ruby>む。"

[[dialogue]]
speaker = "ルヴィネ"
# 「自我が希薄で、命令は何でも聞く……でもあなたの心の底には、人一倍の優しさがある。私はずっとそう思っていた」
line = "「自我が希薄で、命令は何でも聞く……でもあなたの心の底には、人一倍の優しさがある。私はずっとそう思っていた」"

[[dialogue]]
speaker = "ルヴィネ"
# 「デネブを守るためにアルタイルを滅ぼす──そこまでは聞いてくれたでしょう」
line = "「デネブを守るためにアルタイルを滅ぼす──そこまでは聞いてくれたでしょう」"

[[dialogue]]
speaker = "ルヴィネ"
# 「でもリクリエを起こして、デネブをも滅ぼす。ベアトもチナもグレイスも、みんないなくなる……その手伝いをしろと言ったら？」
line = "「でもリクリエを起こして、デネブをも滅ぼす。ベアトもチナもグレイスも、みんないなくなる……その手伝いをしろと言ったら？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「きっとあなたは『嫌だ』と言ったはずよ」
line = "「きっとあなたは『嫌だ』と言ったはずよ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「誰よりも傷つくことの痛みを、独りぼっちの怖さを知っている。そんなとても優しい子だもの」
line = "「誰よりも傷つくことの痛みを、独りぼっちの怖さを知っている。そんなとても優しい子だもの」"

[[dialogue]]
speaker = "レティシア"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "チナ"
# 「……ルヴィ。こっちの世界でアタシ、死んだ父さんたちに会ったんだ」
line = "「……ルヴィ。こっちの世界でアタシ、死んだ父さんたちに会ったんだ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「そう。よかったわね」
line = "「そう。よかったわね」"

[[dialogue]]
speaker = "チナ"
# 「母さんのお腹には、子供もいるって……」
line = "「母さんのお腹には、子供もいるって……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………そう」
line = "「…………そう」"

[[dialogue]]
speaker = "チナ"
# 「ルヴィがリクリエを起こそうとしてるなら──ルヴィはアタシの敵だ。星騎士として、絶対に止めなきゃならない」
line = "「ルヴィがリクリエを起こそうとしてるなら──ルヴィはアタシの敵だ。星騎士として、絶対に止めなきゃならない」"

[[dialogue]]
speaker = "ルヴィネ"
# 「チナは本当に強い子ね。５人の中で一番歳下だけど、あなたは本当にしっかり者だわ」
line = "「チナは本当に強い子ね。５人の中で一番歳下だけど、あなたは本当にしっかり者だわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「チナのまっすぐで、ひたむきなところ。昔からすごく好きだった」
line = "「チナのまっすぐで、ひたむきなところ。昔からすごく好きだった」"

[[dialogue]]
speaker = "チナ"
# 「……それも女神サマの、人心掌握のセリフか？」
line = "「……それも女神サマの、人心掌握のセリフか？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ええ。いつもこうやって、あなたが喜びそうな言葉を選んで……信頼を稼いでいたわ。とても効果があったでしょう？」
line = "「ええ。いつもこうやって、あなたが喜びそうな言葉を選んで……信頼を稼いでいたわ。とても効果があったでしょう？」"

[[dialogue]]
speaker = "チナ"
# 「ああ、そうかよ！　くそったれ……！」
line = "「ああ、そうかよ！　くそったれ……！」"

[[dialogue]]
speaker = "チナ"
# 「アタシの家族に手出しはさせない。ルヴィ、お前は、敵だ……！」
line = "「アタシの家族に手出しはさせない。ルヴィ、お前は、敵だ……！」"

[[dialogue]]
speaker = "unk"
# チナが奥歯を噛んで槍を構える──が、ベアトリスが一歩前に出た。
line = "チナが奥歯を噛んで槍を構える──が、ベアトリスが一歩前に出た。"

[[dialogue]]
speaker = "ベアトリス"
# 「ねえ、ルヴィ？　聞かせて欲しいの……」
line = "「ねえ、ルヴィ？　聞かせて欲しいの……」"

[[dialogue]]
speaker = "ベアトリス"
# 「本当は……リクリエなんて起こしたくないって、思ってない……？」
line = "「本当は……リクリエなんて起こしたくないって、思ってない……？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ベアトリス"
# 「『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』に脅されて、無理やり従わされて、ないかな……？」
line = "「『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』に脅されて、無理やり従わされて、ないかな……？」"

[[dialogue]]
speaker = "ベアトリス"
# 「もういいよ……１０年間騙してたことは、もういい……それはもういいから、本当のこと、教えてほしいの……」
line = "「もういいよ……１０年間騙してたことは、もういい……それはもういいから、本当のこと、教えてほしいの……」"

[[dialogue]]
speaker = "ベアトリス"
# 「私はルヴィの本心が知りたいよ……！」
line = "「私はルヴィの本心が知りたいよ……！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……こんな時でも、ベアトは変わらないのね」
line = "「……こんな時でも、ベアトは変わらないのね」"

[[dialogue]]
speaker = "ルヴィネ"
# 「あなたは本当に不思議。誰よりも操りやすそうなのに、実際はものすごく頑固」
line = "「あなたは本当に不思議。誰よりも操りやすそうなのに、実際はものすごく頑固」"

[[dialogue]]
speaker = "ルヴィネ"
# 「人の感情を計算するのは得意なはずなのだけれど……ベアトはいつも私の予想を裏切る」
line = "「人の感情を計算するのは得意なはずなのだけれど……ベアトはいつも私の予想を裏切る」"

[[dialogue]]
speaker = "ルヴィネ"
# 「こういう時は『よくも騙してくれたな』って。『許さない』って言わなくちゃダメでしょう？」
line = "「こういう時は『よくも騙してくれたな』って。『許さない』って言わなくちゃダメでしょう？」"

[[dialogue]]
speaker = "ベアトリス"
# 「──そんなことできない！！　ルヴィは私の大切な友達だもん！！　自分の命よりも大事な……大好きな友達なの！！！」
line = "「──そんなことできない！！　ルヴィは私の大切な友達だもん！！　自分の命よりも大事な……大好きな友達なの！！！」"

[[dialogue]]
speaker = "ベアトリス"
# 「一族にも、家族にも見捨てられた私にできた……一番最初にできた……かけがえのないっ……！！」
line = "「一族にも、家族にも見捨てられた私にできた……一番最初にできた……かけがえのないっ……！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「演技だと言ったでしょう。アルタイルを滅ぼすために、便利だから利用したにすぎないと」
line = "「演技だと言ったでしょう。アルタイルを滅ぼすために、便利だから利用したにすぎないと」"

[[dialogue]]
speaker = "ルヴィネ"
# 「１０年前……出会った時からベアトは星力が使えた。あの荒廃した流星市国で……とても便利だったわ、あなた」
line = "「１０年前……出会った時からベアトは星力が使えた。あの荒廃した流星市国で……とても便利だったわ、あなた」"

[[dialogue]]
speaker = "ベアトリス"
# 「そんな……！？」
line = "「そんな……！？」"

[[dialogue]]
speaker = "チナ"
# 「……変身しろよルヴィ。こうなったら力づくでもお前を止める」
line = "「……変身しろよルヴィ。こうなったら力づくでもお前を止める」"

[[dialogue]]
speaker = "ルヴィネ"
# 「無駄よ。女神に勝てると本気で思っているの？　今すぐ投降しなさい──命だけは助けてあげる」
line = "「無駄よ。女神に勝てると本気で思っているの？　今すぐ投降しなさい──命だけは助けてあげる」"

[[dialogue]]
speaker = "チナ"
# 「長い付き合いだ、わかるだろ。そんなことを聞くアタシたちだと思うか？」
line = "「長い付き合いだ、わかるだろ。そんなことを聞くアタシたちだと思うか？」"

[[dialogue]]
speaker = "グレイス"
# 「これだけひどいことを言われても……ルヴィのことを嫌いきれない、自分がイヤです……全力でいきますから！」
line = "「これだけひどいことを言われても……ルヴィのことを嫌いきれない、自分がイヤです……全力でいきますから！」"

[[dialogue]]
speaker = "レティシア"
# 「みんなが離ればなれになるのは、私もイヤだわ──ルヴィ」
line = "「みんなが離ればなれになるのは、私もイヤだわ──ルヴィ」"

[[dialogue]]
speaker = "レティシア"
# 「初めて自分の意思を自覚できたのに。それでルヴィと争うことになるだなんて……」
line = "「初めて自分の意思を自覚できたのに。それでルヴィと争うことになるだなんて……」"

[[dialogue]]
speaker = "ベアトリス"
# 「やらせない……アルタイルとデネブを滅ぼすだなんて。そんなひどいこと、ルヴィにやらせない！！」
line = "「やらせない……アルタイルとデネブを滅ぼすだなんて。そんなひどいこと、ルヴィにやらせない！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……仕方ないわね」
line = "「……仕方ないわね」"

[[dialogue]]
speaker = "ルヴィネ"
# 「１０年間も騙していたんだもの。納得するまで付き合ってあげるのが、せめてものお詫びかしら」
line = "「１０年間も騙していたんだもの。納得するまで付き合ってあげるのが、せめてものお詫びかしら」"

[[dialogue]]
speaker = "チナ"
# 「舐めるな、このぉっ──！！！」
line = "「舐めるな、このぉっ──！！！」"
