[[dialogue]]
speaker = "unk"
# 第１１話,星徒会長,B
line = "第１１話,星徒会長,B"

[[dialogue]]
speaker = "unk"
# 梨緒に返事をした翌日。
line = "梨緒に返事をした翌日。"

[[dialogue]]
speaker = "unk"
# 俺は星徒会のみんなにそのことを話した。
line = "俺は星徒会のみんなにそのことを話した。"

[[dialogue]]
speaker = "クロト"
# 「御前試合、受けることにしたんだ。ごめん」
line = "「御前試合、受けることにしたんだ。ごめん」"

[[dialogue]]
speaker = "ヴィーナス"
# 「何で謝るのよ。好きにしなさいって言ったし、クロトが負けるとも思ってないから問題ないわ」
line = "「何で謝るのよ。好きにしなさいって言ったし、クロトが負けるとも思ってないから問題ないわ」"

[[dialogue]]
speaker = "アナ"
# 「ラジャー」
line = "「ラジャー」"

[[dialogue]]
speaker = "サーシャ"
# 「わかったわ～」
line = "「わかったわ～」"

[[dialogue]]
speaker = "マトイ"
# 「うん、了解」
line = "「うん、了解」"

[[dialogue]]
speaker = "クロト"
# 「……みんな、驚いてないんだな」
line = "「……みんな、驚いてないんだな」"

[[dialogue]]
speaker = "unk"
# すんなり受け入れられて俺の方が驚いてしまった。
line = "すんなり受け入れられて俺の方が驚いてしまった。"

[[dialogue]]
speaker = "マトイ"
# 「緋宮くん、最近悩んでたでしょ。受けようって気持ちが強かったからそんなに悩んでたんだろうなって」
line = "「緋宮くん、最近悩んでたでしょ。受けようって気持ちが強かったからそんなに悩んでたんだろうなって」"

[[dialogue]]
speaker = "サーシャ"
# 「そんな気はしてたわね～。男の子なんだから腕試しはしたいじゃない」
line = "「そんな気はしてたわね～。男の子なんだから腕試しはしたいじゃない」"

[[dialogue]]
speaker = "クロト"
# 「そうか。みんなにはお見通しだったんだな」
line = "「そうか。みんなにはお見通しだったんだな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でも理由くらいは知りたいわね。ただ戦いたいわけじゃないんでしょ？」
line = "「でも理由くらいは知りたいわね。ただ戦いたいわけじゃないんでしょ？」"

[[dialogue]]
speaker = "クロト"
# 「ああ。俺もみんなに聞いてほしい」
line = "「ああ。俺もみんなに聞いてほしい」"

[[dialogue]]
speaker = "クロト"
# 「まず梨緒について。彼女に関してはわからないことも多いし、言ってることが正しいかわからないけど……」
line = "「まず梨緒について。彼女に関してはわからないことも多いし、言ってることが正しいかわからないけど……」"

[[dialogue]]
speaker = "クロト"
# 「世界を守りたいって意志は真摯なものだと感じた。俺はその気持ちに応えたい」
line = "「世界を守りたいって意志は真摯なものだと感じた。俺はその気持ちに応えたい」"

[[dialogue]]
speaker = "クロト"
# 「そして──俺自身について」
line = "「そして──俺自身について」"

[[dialogue]]
speaker = "unk"
# もしかすると失望されるかもしれない。
line = "もしかすると失望されるかもしれない。"

[[dialogue]]
speaker = "unk"
# でもみんなには包み隠さず話したい。だって一緒に戦ってきた仲間なんだから。
line = "でもみんなには包み隠さず話したい。だって一緒に戦ってきた仲間なんだから。"

[[dialogue]]
speaker = "梨緒"
# 「私にできるのか……？　仲間も、親友も、学園も、全て失っておきながら、おめおめと生き残った私に……」
line = "「私にできるのか……？　仲間も、親友も、学園も、全て失っておきながら、おめおめと生き残った私に……」"

[[dialogue]]
speaker = "梨緒"
# 「いや弱気になるな。今度こそ世界を救うんだろう」
line = "「いや弱気になるな。今度こそ世界を救うんだろう」"

[[dialogue]]
speaker = "unk"
# それにあんな心細い想いをしているのに、懸命に戦おうとしている梨緒を見ていたら、悩んでいるだけの自分が情けなくなった。
line = "それにあんな心細い想いをしているのに、懸命に戦おうとしている梨緒を見ていたら、悩んでいるだけの自分が情けなくなった。"

[[dialogue]]
speaker = "unk"
# 俺に起きたことを言えば、みんなと一緒に戦えなくなるかもしれない。みんなと一緒にいられなくなるかもしれない。
line = "俺に起きたことを言えば、みんなと一緒に戦えなくなるかもしれない。みんなと一緒にいられなくなるかもしれない。"

[[dialogue]]
speaker = "unk"
# それでも向き合わなくちゃいけない。俺も気持ちを言葉にしなくちゃいけない。
line = "それでも向き合わなくちゃいけない。俺も気持ちを言葉にしなくちゃいけない。"

[[dialogue]]
speaker = "クロト"
# 「正直に言う。今の俺は魔王の力は使えない」
line = "「正直に言う。今の俺は魔王の力は使えない」"

[[dialogue]]
speaker = "ヴィーナス"
# 「どういうこと！？」
line = "「どういうこと！？」"

[[dialogue]]
speaker = "unk"
# いつも明るいヴィーナスも、魔王のことなると険しい表情に変わった。
line = "いつも明るいヴィーナスも、魔王のことなると険しい表情に変わった。"

[[dialogue]]
speaker = "unk"
# 星徒会室全体に緊張が走り、みんなの顔にも不安が表れる。
line = "星徒会室全体に緊張が走り、みんなの顔にも不安が表れる。"

[[dialogue]]
speaker = "クロト"
# 「この前のモンスターとの戦いで、俺の力が暴走しそうになったんだ」
line = "「この前のモンスターとの戦いで、俺の力が暴走しそうになったんだ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「暴走？　やっぱりリクリエを自分の中に封印したせい？」
line = "「暴走？　やっぱりリクリエを自分の中に封印したせい？」"

[[dialogue]]
speaker = "クロト"
# 「そうかもしれないし、そうじゃないかもしれない。でも俺の中のラクシスの力が、制御できなくなりそうだったのは確かだ」
line = "「そうかもしれないし、そうじゃないかもしれない。でも俺の中のラクシスの力が、制御できなくなりそうだったのは確かだ」"

[[dialogue]]
speaker = "クロト"
# 「ラクシスの力の根幹は平行世界への干渉。平行世界に分かれた俺自身の可能性を収束させ、力を集めることができた。だけど……」
line = "「ラクシスの力の根幹は平行世界への干渉。平行世界に分かれた俺自身の可能性を収束させ、力を集めることができた。だけど……」"

[[dialogue]]
speaker = "クロト"
# 「きっと平行世界の俺が見たんだろう。リクリエで破滅した世界の光景が頭に流れ込んできて、何もかも破壊したくてたまらなくなった」
line = "「きっと平行世界の俺が見たんだろう。リクリエで破滅した世界の光景が頭に流れ込んできて、何もかも破壊したくてたまらなくなった」"

[[dialogue]]
speaker = "クロト"
# 「俺にも何が起こったのかわからない。でもあの時、梨緒が止めてくれなかったら……俺はみんなを手にかけていたかもしれない」
line = "「俺にも何が起こったのかわからない。でもあの時、梨緒が止めてくれなかったら……俺はみんなを手にかけていたかもしれない」"

[[dialogue]]
speaker = "マトイ"
# 「そんな……！」
line = "「そんな……！」"

[[dialogue]]
speaker = "サーシャ"
# 「俺から離れてくれ、って言っていたのはそういう意味だったのね～」
line = "「俺から離れてくれ、って言っていたのはそういう意味だったのね～」"

[[dialogue]]
speaker = "アナ"
# 「平行世界の可能性を呼び込む力──多大な力を得られる反面、害あるものを呼び寄せるリスクがあるのかもしれませんね」
line = "「平行世界の可能性を呼び込む力──多大な力を得られる反面、害あるものを呼び寄せるリスクがあるのかもしれませんね」"

[[dialogue]]
speaker = "クロト"
# 「正直、梨緒の言っていることが腑に落ちたんだ。俺は本当に世界を滅ぼす魔王なのかもしれないって」
line = "「正直、梨緒の言っていることが腑に落ちたんだ。俺は本当に世界を滅ぼす魔王なのかもしれないって」"

[[dialogue]]
speaker = "クロト"
# 「今は力の暴走を抑えながら戦っている状態で……梨緒の言う通り、俺は星徒会長を退いて、戦いから離れた方がいいのかもしれない」
line = "「今は力の暴走を抑えながら戦っている状態で……梨緒の言う通り、俺は星徒会長を退いて、戦いから離れた方がいいのかもしれない」"

[[dialogue]]
speaker = "クロト"
# 「でも俺はまだ星徒会でいたい。新星学園の星徒会長でありたい」
line = "「でも俺はまだ星徒会でいたい。新星学園の星徒会長でありたい」"

[[dialogue]]
speaker = "unk"
# そう思ってしまうのはわがままなのかもしれない。弱さなのかもしれない。
line = "そう思ってしまうのはわがままなのかもしれない。弱さなのかもしれない。"

[[dialogue]]
speaker = "unk"
# でも新星の星徒会長であることは、いつの間にか俺の一部になってしまった。
line = "でも新星の星徒会長であることは、いつの間にか俺の一部になってしまった。"

[[dialogue]]
speaker = "クロト"
# 「最初はヴィーナスに御前試合を挑まれて、ヴィーナスの求めに応じたくて星徒会長になった。でも今はここが俺の居場所なんだって思えるんだ」
line = "「最初はヴィーナスに御前試合を挑まれて、ヴィーナスの求めに応じたくて星徒会長になった。でも今はここが俺の居場所なんだって思えるんだ」"

[[dialogue]]
speaker = "unk"
# こうして気持ちをぶつけるのは、みんなに甘えているんだと思う。
line = "こうして気持ちをぶつけるのは、みんなに甘えているんだと思う。"

[[dialogue]]
speaker = "unk"
# だけど仲間だから。きっと受け止めてくれると信じているから、今は吐き出させてほしい。
line = "だけど仲間だから。きっと受け止めてくれると信じているから、今は吐き出させてほしい。"

[[dialogue]]
speaker = "クロト"
# 「これは星騎士としての使命感じゃない。正義感でもない。他ならない俺のエゴだ」
line = "「これは星騎士としての使命感じゃない。正義感でもない。他ならない俺のエゴだ」"

[[dialogue]]
speaker = "クロト"
# 「だから俺が星徒会長にふさわしいと、証明するチャンスが欲しい。俺がここにいていいと自分で認められるように、戦わせてほしい」
line = "「だから俺が星徒会長にふさわしいと、証明するチャンスが欲しい。俺がここにいていいと自分で認められるように、戦わせてほしい」"

[[dialogue]]
speaker = "クロト"
# 「それが御前試合を受けた理由だ」
line = "「それが御前試合を受けた理由だ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……なるほど、そういうことだったのね」
line = "「……なるほど、そういうことだったのね」"

[[dialogue]]
speaker = "unk"
# 神妙な顔をして頷くヴィーナス。
line = "神妙な顔をして頷くヴィーナス。"

[[dialogue]]
speaker = "unk"
# 彼女はどんな反応をするだろう。失望するだろうか。情けないと言うだろうか。
line = "彼女はどんな反応をするだろう。失望するだろうか。情けないと言うだろうか。"

[[dialogue]]
speaker = "unk"
# それが怖かったけど、言うべきことは言った。
line = "それが怖かったけど、言うべきことは言った。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ま、いいんじゃない」
line = "「ま、いいんじゃない」"

[[dialogue]]
speaker = "クロト"
# 「え」
line = "「え」"

[[dialogue]]
speaker = "unk"
# そして実際の彼女の言葉は、予想していたものと反対に至極軽いものだった。
line = "そして実際の彼女の言葉は、予想していたものと反対に至極軽いものだった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「大丈夫、最初は魔王の力だって使えなかったじゃない。でもギエルに勝つくらいになったんだし、そのうちなんとかなるわ」
line = "「大丈夫、最初は魔王の力だって使えなかったじゃない。でもギエルに勝つくらいになったんだし、そのうちなんとかなるわ」"

[[dialogue]]
speaker = "アナ"
# 「そうですね。現状で力が使えないと断定するのは早計です。魔王の力が大きな戦力になるのは事実ですし、より分析を進めてからでよいかと」
line = "「そうですね。現状で力が使えないと断定するのは早計です。魔王の力が大きな戦力になるのは事実ですし、より分析を進めてからでよいかと」"

[[dialogue]]
speaker = "アナ"
# 「それに私たちは緋宮会長の星徒会役員です。会長の方針に従います」
line = "「それに私たちは緋宮会長の星徒会役員です。会長の方針に従います」"

[[dialogue]]
speaker = "マトイ"
# 「うん、緋宮くんの気持ちを否定したりしないよ」
line = "「うん、緋宮くんの気持ちを否定したりしないよ」"

[[dialogue]]
speaker = "マトイ"
# 「びっくりした話もあったけど、正直に言ってくれて嬉しかった。私も星徒会役員だから頼られたいもん」
line = "「びっくりした話もあったけど、正直に言ってくれて嬉しかった。私も星徒会役員だから頼られたいもん」"

[[dialogue]]
speaker = "サーシャ"
# 「助け合うのが星徒会だものね～。ふふ、微笑ましいわ～」
line = "「助け合うのが星徒会だものね～。ふふ、微笑ましいわ～」"

[[dialogue]]
speaker = "サーシャ"
# 「星徒会長は一番強い星騎士がなるものだし、戦って決めるのもいいんじゃないかしら～」
line = "「星徒会長は一番強い星騎士がなるものだし、戦って決めるのもいいんじゃないかしら～」"

[[dialogue]]
speaker = "クロト"
# 「みんな……ありがとう」
line = "「みんな……ありがとう」"

[[dialogue]]
speaker = "unk"
# じんと目頭が熱くなる。俺はいい仲間を持った。
line = "じんと目頭が熱くなる。俺はいい仲間を持った。"

[[dialogue]]
speaker = "ヴィーナス"
# 「それに何よ、私たちを手にかけようとしたって。俺が本気になったら私たちなんて簡単に仕留められるとでも思ってるワケ？」
line = "「それに何よ、私たちを手にかけようとしたって。俺が本気になったら私たちなんて簡単に仕留められるとでも思ってるワケ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そんなに弱くなったつもりはないわ。あなたが正気を失ったら、ブン殴って正気に戻してあげる！」
line = "「そんなに弱くなったつもりはないわ。あなたが正気を失ったら、ブン殴って正気に戻してあげる！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だって私はあなたの娘なんだもの。パパの面倒くらい見てあげるわ！」
line = "「だって私はあなたの娘なんだもの。パパの面倒くらい見てあげるわ！」"

[[dialogue]]
speaker = "マトイ"
# 「そんな介護みたいな……」
line = "「そんな介護みたいな……」"

[[dialogue]]
speaker = "クロト"
# 「ハハ……頼もしいな……」
line = "「ハハ……頼もしいな……」"

[[dialogue]]
speaker = "unk"
# さすがに介護されるほど<ruby=もうろく>耄碌</ruby>していない──と言いたいが、実際に危ないところだったから苦笑いしかない。
line = "さすがに介護されるほど<ruby>耄碌<rt>もうろく</rt></ruby>していない──と言いたいが、実際に危ないところだったから苦笑いしかない。"

[[dialogue]]
speaker = "ヴィーナス"
# 「よし、じゃあ特訓よ！」
line = "「よし、じゃあ特訓よ！」"

[[dialogue]]
speaker = "クロト"
# 「特訓？」
line = "「特訓？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「力を抑えながら戦ってるって言ってたでしょ？　なら新しい戦い方に慣れないといけないわ」
line = "「力を抑えながら戦ってるって言ってたでしょ？　なら新しい戦い方に慣れないといけないわ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だから私が鍛えてあげる。前の御前試合の時は仲間外れで寂しかったんだから！」
line = "「だから私が鍛えてあげる。前の御前試合の時は仲間外れで寂しかったんだから！」"

[[dialogue]]
speaker = "マトイ"
# 「ヴィーナスが対戦相手なんだから当然でしょ……。あ、特訓は私も手伝うから」
line = "「ヴィーナスが対戦相手なんだから当然でしょ……。あ、特訓は私も手伝うから」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふ、懐かしいわね～」
line = "「ふふ、懐かしいわね～」"

[[dialogue]]
speaker = "アナ"
# 「限界に挑戦」
line = "「限界に挑戦」"

[[dialogue]]
speaker = "クロト"
# 「ああ、頼んだ。とことん甘えさせてもらうぞ」
line = "「ああ、頼んだ。とことん甘えさせてもらうぞ」"

[[dialogue]]
speaker = "unk"
# ヴィーナスとの御前試合では、不完全ながらも魔王の力に覚醒して勝利した。
line = "ヴィーナスとの御前試合では、不完全ながらも魔王の力に覚醒して勝利した。"

[[dialogue]]
speaker = "unk"
# でもあれはヴィーナスが俺を呼んでくれたから、求めてくれたからで、偶然で勝てたようなものだ。
line = "でもあれはヴィーナスが俺を呼んでくれたから、求めてくれたからで、偶然で勝てたようなものだ。"

[[dialogue]]
speaker = "unk"
# だから今度は自分の力で星徒会長になってみせる……！
line = "だから今度は自分の力で星徒会長になってみせる……！"
