[[dialogue]]
speaker = "unk"
# 第６話,第６話『学園へ向かうぞ』,B
line = "第６話,第６話『学園へ向かうぞ』,B"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ここは──おお、学園だね」
line = "「ここは──おお、学園だね」"

[[dialogue]]
speaker = "クラウディア"
# 「うむ！　ここには迷える少年少女がたくさんおるからな」
line = "「うむ！　ここには迷える少年少女がたくさんおるからな」"

[[dialogue]]
speaker = "クラウディア"
# 「きっと、余のプレゼントを心待ちにしていることであろう──」
line = "「きっと、余のプレゼントを心待ちにしていることであろう──」"

[[dialogue]]
speaker = "トワ先生"
# 「あれ、あなたは？　ダメだよ、勝手に校舎まで入ってきたら」
line = "「あれ、あなたは？　ダメだよ、勝手に校舎まで入ってきたら」"

[[dialogue]]
speaker = "クラウディア"
# 「余はクラウディア。ネビュラが総帥にして光の魔女だ」
line = "「余はクラウディア。ネビュラが総帥にして光の魔女だ」"

[[dialogue]]
speaker = "トワ先生"
# 「ネビュラの総帥──って、えぇ！？　よく見たら、そっちにいるのも魔女さんだし……」
line = "「ネビュラの総帥──って、えぇ！？　よく見たら、そっちにいるのも魔女さんだし……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ツェツィーリエです。キミはトワちゃんさんだね。今のネビュラは学園と提携してるし、まあちょっとの立ち入りくらい大目に見てよ」
line = "「ツェツィーリエです。キミはトワちゃんさんだね。今のネビュラは学園と提携してるし、まあちょっとの立ち入りくらい大目に見てよ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「それより今からクラウディア様が、キミの欲しいものをなんでも恵んでくれるよ！」
line = "「それより今からクラウディア様が、キミの欲しいものをなんでも恵んでくれるよ！」"

[[dialogue]]
speaker = "トワ先生"
# 「え！　欲しいものをなんでも……？」
line = "「え！　欲しいものをなんでも……？」"

[[dialogue]]
speaker = "クラウディア"
# 「ふっふっふ。その通り」
line = "「ふっふっふ。その通り」"

[[dialogue]]
speaker = "トワ先生"
# 「そんなうまい話があるの？　わたし、もういい大人だけど……」
line = "「そんなうまい話があるの？　わたし、もういい大人だけど……」"

[[dialogue]]
speaker = "クラウディア"
# 「１２月２５日は余の誕生日だからな。それを祝うがため、皆にプレゼントを配っておる最中なのだ」
line = "「１２月２５日は余の誕生日だからな。それを祝うがため、皆にプレゼントを配っておる最中なのだ」"

[[dialogue]]
speaker = "クラウディア"
# 「余はサンタと違って、大人子どもの区別などしないのだ」
line = "「余はサンタと違って、大人子どもの区別などしないのだ」"

[[dialogue]]
speaker = "トワ先生"
# 「おお……なんか懐が深い感じ」
line = "「おお……なんか懐が深い感じ」"

[[dialogue]]
speaker = "クラウディア"
# 「そーれ！　メリークラウディアバースデ～！」
line = "「そーれ！　メリークラウディアバースデ～！」"

[[dialogue]]
speaker = "トワ先生"
# 「わ、すごい光が──」
line = "「わ、すごい光が──」"

[[dialogue]]
speaker = "トワ先生"
# 「って……？　何これ。水素入りコラーゲンゼリー？」
line = "「って……？　何これ。水素入りコラーゲンゼリー？」"

[[dialogue]]
speaker = "クラウディア"
# 「美容・若見え・アンチエイジングに効果あり！　……と書かれているぞ」
line = "「美容・若見え・アンチエイジングに効果あり！　……と書かれているぞ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「うーん、よくあるインチキ商品だね。水素が人体に効くエビデンスはないし、コラーゲンも経口摂取じゃほとんど吸収できない」
line = "「うーん、よくあるインチキ商品だね。水素が人体に効くエビデンスはないし、コラーゲンも経口摂取じゃほとんど吸収できない」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「もしかしてだけど……トワちゃんさんはアンチエイジング化粧品が欲しかったんじゃないかな？」
line = "「もしかしてだけど……トワちゃんさんはアンチエイジング化粧品が欲しかったんじゃないかな？」"

[[dialogue]]
speaker = "トワ先生"
# 「な、ぁっ……！？」
line = "「な、ぁっ……！？」"

[[dialogue]]
speaker = "クラウディア"
# 「ふむ。それでグレードの下がったインチキ商品が出てきてしまったというわけか」
line = "「ふむ。それでグレードの下がったインチキ商品が出てきてしまったというわけか」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「残念ながら。今回のプレゼントは失敗かも」
line = "「残念ながら。今回のプレゼントは失敗かも」"

[[dialogue]]
speaker = "トワ先生"
# 「えぇっ、じゃあプレゼントはなしってこと……？」
line = "「えぇっ、じゃあプレゼントはなしってこと……？」"

[[dialogue]]
speaker = "トワ先生"
# 「──じゃなくて！　わたしは元々若いから、アンチエイジングとか必要ないんですけど！」
line = "「──じゃなくて！　わたしは元々若いから、アンチエイジングとか必要ないんですけど！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「大丈夫、トワちゃんさん。アタシも女だから気持ちはわかるよ」
line = "「大丈夫、トワちゃんさん。アタシも女だから気持ちはわかるよ」"

[[dialogue]]
speaker = "クラウディア"
# 「うむ。せっかくゆえ、後で魔女の秘薬でも教えてやろうかの」
line = "「うむ。せっかくゆえ、後で魔女の秘薬でも教えてやろうかの」"

[[dialogue]]
speaker = "トワ先生"
# 「え、それはけっこう聞きたい……じゃなくて！」
line = "「え、それはけっこう聞きたい……じゃなくて！」"

[[dialogue]]
speaker = "クラウディア"
# 「とりあえずプレゼントは完了した！　次へ向かうぞ！」
line = "「とりあえずプレゼントは完了した！　次へ向かうぞ！」"

[[dialogue]]
speaker = "トワ先生"
# 「話を聞きなさ～～い！」
line = "「話を聞きなさ～～い！」"

[[dialogue]]
speaker = "アム"
# 「うぇぇ、にがぁ……ほんと、なんなのこの飲み物……！」
line = "「うぇぇ、にがぁ……ほんと、なんなのこの飲み物……！」"

[[dialogue]]
speaker = "アム"
# 「ううん、でも諦めたらダメ。絶対にこのブラックコーヒーを克服して──カッコイイ星騎士に……！」
line = "「ううん、でも諦めたらダメ。絶対にこのブラックコーヒーを克服して──カッコイイ星騎士に……！」"

[[dialogue]]
speaker = "クラウディア"
# 「──そこで余の出番というわけだ！」
line = "「──そこで余の出番というわけだ！」"

[[dialogue]]
speaker = "アム"
# 「──ってぶふーっ！　急になに！？」
line = "「──ってぶふーっ！　急になに！？」"

[[dialogue]]
speaker = "クラウディア"
# 「細かいことは気にするでない。それより、ずいぶん苦々しい顔をしておったようだが」
line = "「細かいことは気にするでない。それより、ずいぶん苦々しい顔をしておったようだが」"

[[dialogue]]
speaker = "アム"
# 「えーと……あたし、ブラックコーヒーが飲めなくて。なんとか飲めるようになろうと頑張ってたんだけど……」
line = "「えーと……あたし、ブラックコーヒーが飲めなくて。なんとか飲めるようになろうと頑張ってたんだけど……」"

[[dialogue]]
speaker = "クラウディア"
# 「なんだ、そんなことか。コーヒーくらいで音を上げるとは、可愛いものよの」
line = "「なんだ、そんなことか。コーヒーくらいで音を上げるとは、可愛いものよの」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「クラウディア様は飲めるのー？」
line = "「クラウディア様は飲めるのー？」"

[[dialogue]]
speaker = "クラウディア"
# 「もちろんだ！　余にかかればこの程度──んっ……うぇっ！　苦ぁっ！」
line = "「もちろんだ！　余にかかればこの程度──んっ……うぇっ！　苦ぁっ！」"

[[dialogue]]
speaker = "アム"
# 「ダメじゃん！」
line = "「ダメじゃん！」"

[[dialogue]]
speaker = "クラウディア"
# 「なんだ、この液体は！　こんな苦いものを好んで飲む者がいるとは信じられん」
line = "「なんだ、この液体は！　こんな苦いものを好んで飲む者がいるとは信じられん」"

[[dialogue]]
speaker = "アム"
# 「でしょ？　でも、あたしには新星の星徒会長になるっていう夢があるの！」
line = "「でしょ？　でも、あたしには新星の星徒会長になるっていう夢があるの！」"

[[dialogue]]
speaker = "アム"
# 「その時にコーヒーが苦手なんて、格好がつかないから……」
line = "「その時にコーヒーが苦手なんて、格好がつかないから……」"

[[dialogue]]
speaker = "アム"
# 「前に裏技で飲めたことはあったんだけど……やっぱ一度は正々堂々飲んでみたいなって……」
line = "「前に裏技で飲めたことはあったんだけど……やっぱ一度は正々堂々飲んでみたいなって……」"

[[dialogue]]
speaker = "クラウディア"
# 「なるほど。よくわかったぞ」
line = "「なるほど。よくわかったぞ」"

[[dialogue]]
speaker = "クラウディア"
# 「お主にひと足早い１２月２５日のプレゼントを恵んでやろう」
line = "「お主にひと足早い１２月２５日のプレゼントを恵んでやろう」"

[[dialogue]]
speaker = "アム"
# 「ほんと！？　じゃあ、コーヒーが飲めるようになるアイテムを！」
line = "「ほんと！？　じゃあ、コーヒーが飲めるようになるアイテムを！」"

[[dialogue]]
speaker = "クラウディア"
# 「任せよ──そーれ！」
line = "「任せよ──そーれ！」"

[[dialogue]]
speaker = "アム"
# 「これは！？」
line = "「これは！？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「コーヒーシュガーだね。ほら、これがあれば飲みやすいから」
line = "「コーヒーシュガーだね。ほら、これがあれば飲みやすいから」"

[[dialogue]]
speaker = "アム"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "アム"
# 「いや、それは知ってるんだけど……ブラックで飲めなきゃ意味がないから、特訓してたっていうか……」
line = "「いや、それは知ってるんだけど……ブラックで飲めなきゃ意味がないから、特訓してたっていうか……」"

[[dialogue]]
speaker = "クラウディア"
# 「無理に背伸びをするでない。せーとかいちょーには、親しみやすさも重要だぞ。たぶん」
line = "「無理に背伸びをするでない。せーとかいちょーには、親しみやすさも重要だぞ。たぶん」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「まあ、本来はブラックコーヒーの定義って、ミルクとかクリームが入ってないもののことだから──砂糖が入ってても問題なくブラックといえるよ」
line = "「まあ、本来はブラックコーヒーの定義って、ミルクとかクリームが入ってないもののことだから──砂糖が入ってても問題なくブラックといえるよ」"

[[dialogue]]
speaker = "アム"
# 「そうなの！？　そう言われたら、これでいい気がしてきたかも……」
line = "「そうなの！？　そう言われたら、これでいい気がしてきたかも……」"

[[dialogue]]
speaker = "クラウディア"
# 「あっはっは、そうであろうそうであろう」
line = "「あっはっは、そうであろうそうであろう」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「いい気づきを得られたね！」
line = "「いい気づきを得られたね！」"

[[dialogue]]
speaker = "クラウディア"
# 「それもこれも１２月２５日が余の誕生日だからということ、ゆめゆめ忘れるでないぞ！」
line = "「それもこれも１２月２５日が余の誕生日だからということ、ゆめゆめ忘れるでないぞ！」"
