[[dialogue]]
speaker = "unk"
# 第１話,新・戦闘服だぴょん！,B
line = "第１話,新・戦闘服だぴょん！,B"

[[dialogue]]
speaker = "unk"
# 季節は１２月も半ばに差しかかろうというある日のこと。
line = "季節は１２月も半ばに差しかかろうというある日のこと。"

[[dialogue]]
speaker = "unk"
# 九浄家のメイド長である羽宮蘭美は、当主、九浄ヘレナの元に呼び出されていた。
line = "九浄家のメイド長である羽宮蘭美は、当主、九浄ヘレナの元に呼び出されていた。"

[[dialogue]]
speaker = "ヘレナ"
# 「ついに今年もやってきたな、この時期が……」
line = "「ついに今年もやってきたな、この時期が……」"

[[dialogue]]
speaker = "蘭美"
# 「クリスマスを間近に控えていますが……そういう時期という意味で合っているでしょうか？」
line = "「クリスマスを間近に控えていますが……そういう時期という意味で合っているでしょうか？」"

[[dialogue]]
speaker = "ヘレナ"
# 「正解だ。そう、もうすぐクリスマスがやってくる……蘭美、前回のクリスマスのことは覚えているか？」
line = "「正解だ。そう、もうすぐクリスマスがやってくる……蘭美、前回のクリスマスのことは覚えているか？」"

[[dialogue]]
speaker = "蘭美"
# 「ヴィーナスお嬢様が、セシア様の記憶をよみがえらせるために計画した『サンタ大作戦』という事件がありましたね」
line = "「ヴィーナスお嬢様が、セシア様の記憶をよみがえらせるために計画した『サンタ大作戦』という事件がありましたね」"

[[dialogue]]
speaker = "蘭美"
# 「プレゼントを配るため、深夜に新星寮『ラルーナ』に無断で忍び込み、そして寮長のマハムート様に見つかって大騒ぎになってしまった」
line = "「プレゼントを配るため、深夜に新星寮『ラルーナ』に無断で忍び込み、そして寮長のマハムート様に見つかって大騒ぎになってしまった」"

[[dialogue]]
speaker = "ヘレナ"
# 「うむ。それで、我が娘の非礼を詫びるべく、我ら２人で新星寮へ謝罪に赴いたな」
line = "「うむ。それで、我が娘の非礼を詫びるべく、我ら２人で新星寮へ謝罪に赴いたな」"

[[dialogue]]
speaker = "蘭美"
# 「あの時のマハムート様の迫力に満ちた視線は今でも忘れることができません」
line = "「あの時のマハムート様の迫力に満ちた視線は今でも忘れることができません」"

[[dialogue]]
speaker = "蘭美"
# 「セシア様の記憶を取り戻したいという想いからの行動で、あの時は大目には見てくれたものの……」
line = "「セシア様の記憶を取り戻したいという想いからの行動で、あの時は大目には見てくれたものの……」"

[[dialogue]]
speaker = "ヘレナ"
# 「はっはっは、あれは確かに恐かったな。正直ちびりそうであったわ！」
line = "「はっはっは、あれは確かに恐かったな。正直ちびりそうであったわ！」"

[[dialogue]]
speaker = "蘭美"
# 「今なら笑い話にできますが……巻き込まれて作戦に参加することになったヨミは、よく無事でいられたものです」
line = "「今なら笑い話にできますが……巻き込まれて作戦に参加することになったヨミは、よく無事でいられたものです」"

[[dialogue]]
speaker = "ヘレナ"
# 「そういえば翌日に、珍しく休みを取っていたな」
line = "「そういえば翌日に、珍しく休みを取っていたな」"

[[dialogue]]
speaker = "蘭美"
# 「それだけ恐い思いをしたということでしょう」
line = "「それだけ恐い思いをしたということでしょう」"

[[dialogue]]
speaker = "蘭美"
# 「ところで当主様、私を呼んだのはクリスマスの思い出に浸るため、というわけではありませんよね？」
line = "「ところで当主様、私を呼んだのはクリスマスの思い出に浸るため、というわけではありませんよね？」"

[[dialogue]]
speaker = "ヘレナ"
# 「無論。そうだな……もったいつけても仕方あるまい、お披露目といこうか」
line = "「無論。そうだな……もったいつけても仕方あるまい、お披露目といこうか」"

[[dialogue]]
speaker = "蘭美"
# 「っ！？　これは……！！」
line = "「っ！？　これは……！！」"

[[dialogue]]
speaker = "ヘレナ"
# 「私からのクリスマスプレゼントだ」
line = "「私からのクリスマスプレゼントだ」"

[[dialogue]]
speaker = "蘭美"
# 「人工戦闘服、ですか……？　これを私に……？」
line = "「人工戦闘服、ですか……？　これを私に……？」"

[[dialogue]]
speaker = "ヘレナ"
# 「その通り！　この人工戦闘服は、前回ヨミヨミに渡した『クリスマスフォーム』の第２弾となる」
line = "「その通り！　この人工戦闘服は、前回ヨミヨミに渡した『クリスマスフォーム』の第２弾となる」"

[[dialogue]]
speaker = "ヘレナ"
# 「今回もデザインは私が行ったのだが……気に入ってもらえそうか？」
line = "「今回もデザインは私が行ったのだが……気に入ってもらえそうか？」"

[[dialogue]]
speaker = "蘭美"
# 「もちろんです！　ありがとうございます、当主様！」
line = "「もちろんです！　ありがとうございます、当主様！」"

[[dialogue]]
speaker = "ヘレナ"
# 「喜んでもらえて何よりだ……では早速、着てみせてくれ」
line = "「喜んでもらえて何よりだ……では早速、着てみせてくれ」"

[[dialogue]]
speaker = "蘭美"
# 「はいっ！」
line = "「はいっ！」"

[[dialogue]]
speaker = "蘭美"
# 「いかがでしょう、当主様？」
line = "「いかがでしょう、当主様？」"

[[dialogue]]
speaker = "ヘレナ"
# 「うむ、良く似合っているな。我ながらほれぼれするような仕上がりだ」
line = "「うむ、良く似合っているな。我ながらほれぼれするような仕上がりだ」"

[[dialogue]]
speaker = "蘭美"
# 「こんな素晴らしいものを……本当にありがとうございます」
line = "「こんな素晴らしいものを……本当にありがとうございます」"

[[dialogue]]
speaker = "ヘレナ"
# 「うむ。……しかし、まだ戦闘服としての機能は発揮されていないようだ」
line = "「うむ。……しかし、まだ戦闘服としての機能は発揮されていないようだ」"

[[dialogue]]
speaker = "蘭美"
# 「はい。先ほどから起動しようとしているのですが反応はありません」
line = "「はい。先ほどから起動しようとしているのですが反応はありません」"

[[dialogue]]
speaker = "ヘレナ"
# 「他のフォームもそうだったのだが、人工戦闘服は単にそれを身にまとっているだけでは力を発揮しない」
line = "「他のフォームもそうだったのだが、人工戦闘服は単にそれを身にまとっているだけでは力を発揮しない」"

[[dialogue]]
speaker = "ヘレナ"
# 「その戦闘服が真に持ち主のものとなるには、それを覚醒させる何らかの精神的アクセスが必要となるようだ」
line = "「その戦闘服が真に持ち主のものとなるには、それを覚醒させる何らかの精神的アクセスが必要となるようだ」"

[[dialogue]]
speaker = "ヘレナ"
# 「人によってはそれに時間がかかってしまう者もいるからな……」
line = "「人によってはそれに時間がかかってしまう者もいるからな……」"

[[dialogue]]
speaker = "蘭美"
# 「ふっ、問題ありません、当主様……」
line = "「ふっ、問題ありません、当主様……」"

[[dialogue]]
speaker = "蘭美"
# 「私は『光速のメイドマスター』羽宮蘭美！　九浄家メイド隊の誇りにかけ、最速でこのクリスマスフォームを覚醒させてみせましょう！」
line = "「私は『光速のメイドマスター』羽宮蘭美！　九浄家メイド隊の誇りにかけ、最速でこのクリスマスフォームを覚醒させてみせましょう！」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふふふ、頼もしいな。では期待しているぞ、蘭美」
line = "「ふふふ、頼もしいな。では期待しているぞ、蘭美」"

[[dialogue]]
speaker = "蘭美"
# 「はい、お任せください！」
line = "「はい、お任せください！」"
