[[dialogue]]
speaker = "unk"
# 第７話,聖庭園の刺客,B
line = "第７話,聖庭園の刺客,B"

[[dialogue]]
speaker = "梨緒"
# 「選挙管理委員会に入る者は……いないか」
line = "「選挙管理委員会に入る者は……いないか」"

[[dialogue]]
speaker = "unk"
# 選挙管理委員会の新たな仲間を探し、カフェテリアの片隅に佇む梨緒。
line = "選挙管理委員会の新たな仲間を探し、カフェテリアの片隅に佇む梨緒。"

[[dialogue]]
speaker = "unk"
# だが彼女の表情は険しかった。
line = "だが彼女の表情は険しかった。"

[[dialogue]]
speaker = "梨緒"
# （緋宮クロトは星徒会長として支持されている。全幅の信頼を受けていると言っても過言ではないだろう）
line = "（緋宮クロトは星徒会長として支持されている。全幅の信頼を受けていると言っても過言ではないだろう）"

[[dialogue]]
speaker = "梨緒"
# （そんな彼を監視するといっても、誰もやりたがらないに決まっている。これでは善政を敷く王に反逆を呼びかけるようなものだ）
line = "（そんな彼を監視するといっても、誰もやりたがらないに決まっている。これでは善政を敷く王に反逆を呼びかけるようなものだ）"

[[dialogue]]
speaker = "梨緒"
# （それとも私が不甲斐ないから誰もついてこないのか？　御前試合で負けたから……私が弱いから……）
line = "（それとも私が不甲斐ないから誰もついてこないのか？　御前試合で負けたから……私が弱いから……）"

[[dialogue]]
speaker = "梨緒"
# （いや、弱気になるな。彼が間違った道に進みかけた時、止める者は必要だ。この世界を守るために……！）
line = "（いや、弱気になるな。彼が間違った道に進みかけた時、止める者は必要だ。この世界を守るために……！）"

[[dialogue]]
speaker = "梨緒"
# 「私は諦めない……絶対に……！」
line = "「私は諦めない……絶対に……！」"

[[dialogue]]
speaker = "ベアトリス"
# 「だ、大丈夫ですか？」
line = "「だ、大丈夫ですか？」"

[[dialogue]]
speaker = "梨緒"
# 「ひあっ！？　き、君は……？」
line = "「ひあっ！？　き、君は……？」"

[[dialogue]]
speaker = "ベアトリス"
# 「あ、驚かせてごめんなさい！　私、この前の大交流で来た留学生で、ベアトリスといいます……」
line = "「あ、驚かせてごめんなさい！　私、この前の大交流で来た留学生で、ベアトリスといいます……」"

[[dialogue]]
speaker = "ベアトリス"
# 「顔色が優れなかったので、声をかけさせていただいたんですが……」
line = "「顔色が優れなかったので、声をかけさせていただいたんですが……」"

[[dialogue]]
speaker = "梨緒"
# 「すまない、ベアトリス。心配させてしまった」
line = "「すまない、ベアトリス。心配させてしまった」"

[[dialogue]]
speaker = "梨緒"
# 「私は梨緒・Ａ・クリステレス。選挙管理委員会だ」
line = "「私は梨緒・Ａ・クリステレス。選挙管理委員会だ」"

[[dialogue]]
speaker = "ベアトリス"
# 「選挙管理委員会？　でもこの学園に選挙はないんじゃ……」
line = "「選挙管理委員会？　でもこの学園に選挙はないんじゃ……」"

[[dialogue]]
speaker = "梨緒"
# 「ああ、その通りだ。だが──」
line = "「ああ、その通りだ。だが──」"

[[dialogue]]
speaker = "unk"
# 梨緒は選挙管理委員会の設立理由を説明した。
line = "梨緒は選挙管理委員会の設立理由を説明した。"

[[dialogue]]
speaker = "ベアトリス"
# 「な、なるほど……。でもおひとりなんですか？」
line = "「な、なるほど……。でもおひとりなんですか？」"

[[dialogue]]
speaker = "梨緒"
# 「まぁ、な」
line = "「まぁ、な」"

[[dialogue]]
speaker = "梨緒"
# 「星徒会長──緋宮クロトはこの学園の生徒から信任を得ている。私は後から聞いたが、以前の戦いでの活躍からすれば当然だ」
line = "「星徒会長──緋宮クロトはこの学園の生徒から信任を得ている。私は後から聞いたが、以前の戦いでの活躍からすれば当然だ」"

[[dialogue]]
speaker = "梨緒"
# 「他の生徒からすれば、そんな彼を監視しようなんて言う私がおかしいんだろう」
line = "「他の生徒からすれば、そんな彼を監視しようなんて言う私がおかしいんだろう」"

[[dialogue]]
speaker = "ベアトリス"
# （選挙管理委員会……星徒会と魔王クロトの監視。目立つのは良くないけど、私の目的とは一致してる……）
line = "（選挙管理委員会……星徒会と魔王クロトの監視。目立つのは良くないけど、私の目的とは一致してる……）"

[[dialogue]]
speaker = "梨緒"
# 「いや、誰も集まらないのは、私が無能だからなのかもしれないが」
line = "「いや、誰も集まらないのは、私が無能だからなのかもしれないが」"

[[dialogue]]
speaker = "梨緒"
# 「私は弱くて使えない、何も守れない星騎士だから……」
line = "「私は弱くて使えない、何も守れない星騎士だから……」"

[[dialogue]]
speaker = "ベアトリス"
# 「あわわっ！？　お気を確かにっ」
line = "「あわわっ！？　お気を確かにっ」"

[[dialogue]]
speaker = "梨緒"
# 「すまない……また弱気になってしまった」
line = "「すまない……また弱気になってしまった」"

[[dialogue]]
speaker = "梨緒"
# 「だが私は、緋宮会長を監視することは必要だと思っている。彼が強いからこそ、目を離すわけにはいかない」
line = "「だが私は、緋宮会長を監視することは必要だと思っている。彼が強いからこそ、目を離すわけにはいかない」"

[[dialogue]]
speaker = "梨緒"
# 「最も強い者が、常に正しい道を往くとは限らない。誤った道を往くなら止める必要がある」
line = "「最も強い者が、常に正しい道を往くとは限らない。誤った道を往くなら止める必要がある」"

[[dialogue]]
speaker = "ベアトリス"
# 「最も強い者が、常に正しいとは限らない……」
line = "「最も強い者が、常に正しいとは限らない……」"

[[dialogue]]
speaker = "ベアトリス"
# 「あ、あのっ！　私、選挙管理委員会に入ってもいいですか？」
line = "「あ、あのっ！　私、選挙管理委員会に入ってもいいですか？」"

[[dialogue]]
speaker = "梨緒"
# 「いいのか？　ありがたい申し出だが、率直に言って肩身が狭いぞ？」
line = "「いいのか？　ありがたい申し出だが、率直に言って肩身が狭いぞ？」"

[[dialogue]]
speaker = "ベアトリス"
# 「いいんです。梨緒さんが言ってること……私にも、わかりますから」
line = "「いいんです。梨緒さんが言ってること……私にも、わかりますから」"

[[dialogue]]
speaker = "梨緒"
# 「わかった。では選挙管理委員会は君を歓迎しよう。……よろしく、ベアトリス」
line = "「わかった。では選挙管理委員会は君を歓迎しよう。……よろしく、ベアトリス」"

[[dialogue]]
speaker = "ベアトリス"
# 「よろしくお願いしますっ」
line = "「よろしくお願いしますっ」"

[[dialogue]]
speaker = "クロト"
# 「今日はクイズオリエンテーションの準備で遅くなっちゃたな……」
line = "「今日はクイズオリエンテーションの準備で遅くなっちゃたな……」"

[[dialogue]]
speaker = "unk"
# 星徒会の仕事を終えての帰り道。
line = "星徒会の仕事を終えての帰り道。"

[[dialogue]]
speaker = "unk"
# １人で帰路を歩いていると──
line = "１人で帰路を歩いていると──"

[[dialogue]]
speaker = "？？？"
# 「や。魔王さん。初めまして」
line = "「や。魔王さん。初めまして」"

[[dialogue]]
speaker = "クロト"
# 「──！？」
line = "「──！？」"

[[dialogue]]
speaker = "unk"
# 冷たく鋭い殺気にゾクリと背筋が震える。
line = "冷たく鋭い殺気にゾクリと背筋が震える。"

[[dialogue]]
speaker = "unk"
# さっきまで気配はなかったはずなのに、背後に誰かいる。
line = "さっきまで気配はなかったはずなのに、背後に誰かいる。"

[[dialogue]]
speaker = "unk"
# 迂闊に動くのは危険だ。首に刃を突き付けられるような、ひりついた感覚を覚えながら、出方を伺う。
line = "迂闊に動くのは危険だ。首に刃を突き付けられるような、ひりついた感覚を覚えながら、出方を伺う。"

[[dialogue]]
speaker = "？？？"
# 「大丈夫。刺さないからこっち見ていいよ。ゆっくり振り返ってね」
line = "「大丈夫。刺さないからこっち見ていいよ。ゆっくり振り返ってね」"

[[dialogue]]
speaker = "unk"
# 言われた通り振り向くと──
line = "言われた通り振り向くと──"

[[dialogue]]
speaker = "？？？"
# 「こんばんは」
line = "「こんばんは」"

[[dialogue]]
speaker = "クロト"
# 「君は……？」
line = "「君は……？」"

[[dialogue]]
speaker = "unk"
# 歳はおそらく俺と同じくらい。制服を着ているから、彼女も大交流でやってきた留学生だろうか。
line = "歳はおそらく俺と同じくらい。制服を着ているから、彼女も大交流でやってきた留学生だろうか。"

[[dialogue]]
speaker = "ナターシャ"
# 「初めまして、魔王さん。私はナターシャ。天界の特務エージェントだよ」
line = "「初めまして、魔王さん。私はナターシャ。天界の特務エージェントだよ」"

[[dialogue]]
speaker = "クロト"
# 「エージェント……？」
line = "「エージェント……？」"

[[dialogue]]
speaker = "ナターシャ"
# 「そ、エージェント。要するに暗殺者。魔王がヤバくなったら消せって命令されてるんだ」
line = "「そ、エージェント。要するに暗殺者。魔王がヤバくなったら消せって命令されてるんだ」"

[[dialogue]]
speaker = "unk"
# 剣呑な言葉にますます緊張が強くなる。
line = "剣呑な言葉にますます緊張が強くなる。"

[[dialogue]]
speaker = "unk"
# 裏の仕事をする公安委員会も学園には存在するが、堂々と暗殺者を名乗ることはない。
line = "裏の仕事をする公安委員会も学園には存在するが、堂々と暗殺者を名乗ることはない。"

[[dialogue]]
speaker = "ナターシャ"
# 「おや。あんまり驚かないね？」
line = "「おや。あんまり驚かないね？」"

[[dialogue]]
speaker = "クロト"
# 「似たようなことを言われたことがあるからな」
line = "「似たようなことを言われたことがあるからな」"

[[dialogue]]
speaker = "ナターシャ"
# 「さすが魔王だ。人気者だね」
line = "「さすが魔王だ。人気者だね」"

[[dialogue]]
speaker = "unk"
# 梨緒は消すとまでは言わなかったけど、前例がなければもっと衝撃だったかもしれない。
line = "梨緒は消すとまでは言わなかったけど、前例がなければもっと衝撃だったかもしれない。"

[[dialogue]]
speaker = "クロト"
# 「その暗殺者がわざわざ姿を現してどうしたんだ？　暗殺者って隠れてるものじゃないのか？」
line = "「その暗殺者がわざわざ姿を現してどうしたんだ？　暗殺者って隠れてるものじゃないのか？」"

[[dialogue]]
speaker = "ナターシャ"
# 「暗殺者は背後から忍び寄るものでしょ？　様式美に従ってみようと思って」
line = "「暗殺者は背後から忍び寄るものでしょ？　様式美に従ってみようと思って」"

[[dialogue]]
speaker = "クロト"
# 「それだけ？」
line = "「それだけ？」"

[[dialogue]]
speaker = "ナターシャ"
# 「うん、それだけ♪」
line = "「うん、それだけ♪」"

[[dialogue]]
speaker = "unk"
# ナターシャと名乗った暗殺者がご機嫌そうに笑う。
line = "ナターシャと名乗った暗殺者がご機嫌そうに笑う。"

[[dialogue]]
speaker = "unk"
# 研ぎ澄まされた殺気はそのままに。
line = "研ぎ澄まされた殺気はそのままに。"

[[dialogue]]
speaker = "ナターシャ"
# 「私の飼い主は<ruby=せいていえん>聖庭園</ruby>でね。前の戦いで活躍した魔王を恐れてるんだよ」
line = "「私の飼い主は<ruby>聖庭園<rt>せいていえん</rt></ruby>でね。前の戦いで活躍した魔王を恐れてるんだよ」"

[[dialogue]]
speaker = "クロト"
# 「聖庭園っていうと確か……」
line = "「聖庭園っていうと確か……」"

[[dialogue]]
speaker = "ナターシャ"
# 「聖庭園は天界の中枢。国の首都みたいなもの。アメリカのワシントン？　みたいなものかな」
line = "「聖庭園は天界の中枢。国の首都みたいなもの。アメリカのワシントン？　みたいなものかな」"

[[dialogue]]
speaker = "unk"
# アナから聞いたことがある。聖庭園には長老格の天使が集まり、天界全体の意志決定をしているとか。
line = "アナから聞いたことがある。聖庭園には長老格の天使が集まり、天界全体の意志決定をしているとか。"

[[dialogue]]
speaker = "unk"
# 人間界や魔界と違って天界は規模が小さく、まとまったひとつの国のようになっているとも。
line = "人間界や魔界と違って天界は規模が小さく、まとまったひとつの国のようになっているとも。"

[[dialogue]]
speaker = "クロト"
# 「魔王を警戒するのはわからなくはないけど、それは本人に言ってよかったのか……？」
line = "「魔王を警戒するのはわからなくはないけど、それは本人に言ってよかったのか……？」"

[[dialogue]]
speaker = "ナターシャ"
# 「手をかけさせないでってことだよ。杞憂で済めば一番いいからね」
line = "「手をかけさせないでってことだよ。杞憂で済めば一番いいからね」"

[[dialogue]]
speaker = "ナターシャ"
# 「多分大丈夫じゃないかなーと思ってるけど……いざという時はバッサリやるから気を付けてね」
line = "「多分大丈夫じゃないかなーと思ってるけど……いざという時はバッサリやるから気を付けてね」"

[[dialogue]]
speaker = "クロト"
# 「ああ。ご忠告感謝するよ」
line = "「ああ。ご忠告感謝するよ」"

[[dialogue]]
speaker = "ナターシャ"
# 「じゃあね～」
line = "「じゃあね～」"

[[dialogue]]
speaker = "unk"
# ナターシャが手をひらひら振りながら去っていく。
line = "ナターシャが手をひらひら振りながら去っていく。"

[[dialogue]]
speaker = "unk"
# 最初からそこにいなかったみたいに、刃を突き付けられるような感覚は消え失せていた。
line = "最初からそこにいなかったみたいに、刃を突き付けられるような感覚は消え失せていた。"

[[dialogue]]
speaker = "クロト"
# 「今度は聖庭園か……」
line = "「今度は聖庭園か……」"

[[dialogue]]
speaker = "unk"
# 聖庭園のリガルタ老は、前の戦いの際、『シエルの<ruby=はこ>筐</ruby>』という宝物を貸し与えてくれた。
line = "聖庭園のリガルタ老は、前の戦いの際、『シエルの<ruby>筐<rt>はこ</rt></ruby>』という宝物を貸し与えてくれた。"

[[dialogue]]
speaker = "unk"
# リクリエとの戦いにおいて、聖庭園は敵ではない。
line = "リクリエとの戦いにおいて、聖庭園は敵ではない。"

[[dialogue]]
speaker = "unk"
# だけど魔王に対する警戒は確かなようだ。
line = "だけど魔王に対する警戒は確かなようだ。"

[[dialogue]]
speaker = "クロト"
# 「しっかりしなきゃいけない理由がまた増えたな」
line = "「しっかりしなきゃいけない理由がまた増えたな」"

[[dialogue]]
speaker = "unk"
# 魔王である俺が道を誤れば世界が滅ぶ。
line = "魔王である俺が道を誤れば世界が滅ぶ。"

[[dialogue]]
speaker = "unk"
# 一応背後に警戒しつつ、その責任を噛みしめながら帰るのだった。
line = "一応背後に警戒しつつ、その責任を噛みしめながら帰るのだった。"
