[[dialogue]]
speaker = "unk"
# 第９話,迸る雷,B
line = "第９話,迸る雷,B"

[[dialogue]]
speaker = "unk"
# 御前試合を申し込まれてから数日。
line = "御前試合を申し込まれてから数日。"

[[dialogue]]
speaker = "unk"
# 受けて立つのか、それとも断るのか、俺はまだ答えを出せていなかった。
line = "受けて立つのか、それとも断るのか、俺はまだ答えを出せていなかった。"

[[dialogue]]
speaker = "unk"
# 俺が悩んでいようと、モンスターはお構いなく現れる。
line = "俺が悩んでいようと、モンスターはお構いなく現れる。"

[[dialogue]]
speaker = "unk"
# 自宅近くに出現したと知らせを受けて現場に急行。対処に当たっていた。
line = "自宅近くに出現したと知らせを受けて現場に急行。対処に当たっていた。"

[[dialogue]]
speaker = "クロト"
# 「ハッ！」
line = "「ハッ！」"

[[dialogue]]
speaker = "unk"
# 幸い今いるのは旧来のモンスターだけなので、魔王の力がなくても十分相手できる。
line = "幸い今いるのは旧来のモンスターだけなので、魔王の力がなくても十分相手できる。"

[[dialogue]]
speaker = "unk"
# だけど──
line = "だけど──"

[[dialogue]]
speaker = "unk"
# あの光景が頭から離れない。
line = "あの光景が頭から離れない。"

[[dialogue]]
speaker = "unk"
# 破滅した世界が俺を呼んでいる。
line = "破滅した世界が俺を呼んでいる。"

[[dialogue]]
speaker = "unk"
# あれが俺の魂にこびりついている限り、魔王の力を使おうとすればきっとまた暴走する。
line = "あれが俺の魂にこびりついている限り、魔王の力を使おうとすればきっとまた暴走する。"

[[dialogue]]
speaker = "unk"
# そんな俺が星徒会長にふさわしいのか？
line = "そんな俺が星徒会長にふさわしいのか？"

[[dialogue]]
speaker = "unk"
# 爆弾を抱えた俺が、星騎士として戦っていていいのか……？
line = "爆弾を抱えた俺が、星騎士として戦っていていいのか……？"

[[dialogue]]
speaker = "unk"
# いや、今は目の前にいる人を助けるのが先だ。頭を振って迷いを振り切る。
line = "いや、今は目の前にいる人を助けるのが先だ。頭を振って迷いを振り切る。"

[[dialogue]]
speaker = "女の子"
# 「きゃっ！？　モンスターが──」
line = "「きゃっ！？　モンスターが──」"

[[dialogue]]
speaker = "クロト"
# 「させない──アビスインパクト！」
line = "「させない──アビスインパクト！」"

[[dialogue]]
speaker = "？？？"
# 「ボルテクスシューター！」
line = "「ボルテクスシューター！」"

[[dialogue]]
speaker = "クロト"
# 「モンスターは倒した。今のうちに逃げてくれ」
line = "「モンスターは倒した。今のうちに逃げてくれ」"

[[dialogue]]
speaker = "女の子"
# 「あ、ありがとうございますっ」
line = "「あ、ありがとうございますっ」"

[[dialogue]]
speaker = "unk"
# さっき俺の拳と同時に、雷を帯びた矢がモンスターを貫いた。
line = "さっき俺の拳と同時に、雷を帯びた矢がモンスターを貫いた。"

[[dialogue]]
speaker = "unk"
# 今のはもしかして──
line = "今のはもしかして──"

[[dialogue]]
speaker = "梨緒"
# 「君、大丈夫か？」
line = "「君、大丈夫か？」"

[[dialogue]]
speaker = "梨緒"
# 「……なんだ、君か」
line = "「……なんだ、君か」"

[[dialogue]]
speaker = "クロト"
# 「そんな露骨な反応しなくてもいいだろ……」
line = "「そんな露骨な反応しなくてもいいだろ……」"

[[dialogue]]
speaker = "梨緒"
# 「私と君は敵同士だからな。慣れ合う気はない」
line = "「私と君は敵同士だからな。慣れ合う気はない」"

[[dialogue]]
speaker = "梨緒"
# 「それに御前試合の返事はどうした？　ヴィーナス前会長の時は即決だったと聞くが、勝負を申し込んでからしばらく経つぞ」
line = "「それに御前試合の返事はどうした？　ヴィーナス前会長の時は即決だったと聞くが、勝負を申し込んでからしばらく経つぞ」"

[[dialogue]]
speaker = "クロト"
# 「それはごめん……」
line = "「それはごめん……」"

[[dialogue]]
speaker = "unk"
# 女の子を待たせるのは純粋に悪いと思いつつ、轟音とともに新たな敵がやってきて──
line = "女の子を待たせるのは純粋に悪いと思いつつ、轟音とともに新たな敵がやってきて──"

[[dialogue]]
speaker = "ドラケルス"
# 「グルルルル……！！」
line = "「グルルルル……！！」"

[[dialogue]]
speaker = "クロト"
# 「！　この前の──」
line = "「！　この前の──」"

[[dialogue]]
speaker = "unk"
# 山をも突き崩す突進を、俺と梨緒はギリギリで回避する。
line = "山をも突き崩す突進を、俺と梨緒はギリギリで回避する。"

[[dialogue]]
speaker = "クロト"
# 「あのモンスターは危険だ。耐久力が高い上に、放っておくと周囲の物をモンスターに変えて仲間を増やす」
line = "「あのモンスターは危険だ。耐久力が高い上に、放っておくと周囲の物をモンスターに変えて仲間を増やす」"

[[dialogue]]
speaker = "梨緒"
# 「確かにそれは厄介だな。だがそう珍しい特性でもない」
line = "「確かにそれは厄介だな。だがそう珍しい特性でもない」"

[[dialogue]]
speaker = "クロト"
# 「え」
line = "「え」"

[[dialogue]]
speaker = "梨緒"
# 「？　乱暴に言えば、リクリエやモンスターとはそういうものだろう？」
line = "「？　乱暴に言えば、リクリエやモンスターとはそういうものだろう？」"

[[dialogue]]
speaker = "クロト"
# 「いや……乱暴に言えばそうだけど」
line = "「いや……乱暴に言えばそうだけど」"

[[dialogue]]
speaker = "unk"
# 梨緒は嘘をついている様子はなく、本当に不思議そうにしている。
line = "梨緒は嘘をついている様子はなく、本当に不思議そうにしている。"

[[dialogue]]
speaker = "unk"
# 互いの感覚がずれている気がするが、今は問答している場合じゃない。
line = "互いの感覚がずれている気がするが、今は問答している場合じゃない。"

[[dialogue]]
speaker = "クロト"
# 「こちらからいくぞ──シュバルツシュラーク！」
line = "「こちらからいくぞ──シュバルツシュラーク！」"

[[dialogue]]
speaker = "ドラケルス"
# 「グゥウウ……！」
line = "「グゥウウ……！」"

[[dialogue]]
speaker = "クロト"
# 「くっ──やっぱり一筋縄じゃいかないか」
line = "「くっ──やっぱり一筋縄じゃいかないか」"

[[dialogue]]
speaker = "クロト"
# 「──！？」
line = "「──！？」"

[[dialogue]]
speaker = "unk"
# もっと力を──そう考えた瞬間、またあの光景が俺を呼ぶ。
line = "もっと力を──そう考えた瞬間、またあの光景が俺を呼ぶ。"

[[dialogue]]
speaker = "unk"
# 意識があの世界に吸い込まれそうになって、俺の中で暴れそうになる力を抑えるので精いっぱいだ。
line = "意識があの世界に吸い込まれそうになって、俺の中で暴れそうになる力を抑えるので精いっぱいだ。"

[[dialogue]]
speaker = "梨緒"
# 「そこだ！」
line = "「そこだ！」"

[[dialogue]]
speaker = "ドラケルス"
# 「グルル……！」
line = "「グルル……！」"

[[dialogue]]
speaker = "梨緒"
# 「なるほど、確かに硬い。だがやれない訳ではないな」
line = "「なるほど、確かに硬い。だがやれない訳ではないな」"

[[dialogue]]
speaker = "unk"
# バチバチと弾ける雷鳴が、俺の意識を現実へと引き戻す。
line = "バチバチと弾ける雷鳴が、俺の意識を現実へと引き戻す。"

[[dialogue]]
speaker = "unk"
# そう、魔王の力がなくても俺は星騎士だ。
line = "そう、魔王の力がなくても俺は星騎士だ。"

[[dialogue]]
speaker = "unk"
# 新星学園に転入した頃とは比較にならないくらい星力を引き出せるようになったし、実戦の経験も積んできた。
line = "新星学園に転入した頃とは比較にならないくらい星力を引き出せるようになったし、実戦の経験も積んできた。"

[[dialogue]]
speaker = "unk"
# 俺は戦える。だからできることをするだけだ。
line = "俺は戦える。だからできることをするだけだ。"

[[dialogue]]
speaker = "クロト"
# 「梨緒ならあのモンスターを倒せるんだな？」
line = "「梨緒ならあのモンスターを倒せるんだな？」"

[[dialogue]]
speaker = "梨緒"
# 「ああ。倒せる」
line = "「ああ。倒せる」"

[[dialogue]]
speaker = "クロト"
# 「じゃあ俺が前に出る。その隙に仕留めてくれ」
line = "「じゃあ俺が前に出る。その隙に仕留めてくれ」"

[[dialogue]]
speaker = "梨緒"
# 「待て。私が君の背中を撃つとは思わないのか？」
line = "「待て。私が君の背中を撃つとは思わないのか？」"

[[dialogue]]
speaker = "クロト"
# 「君は星騎士だ。少なくとも、モンスターを倒すまではそんなことしない。違うか？」
line = "「君は星騎士だ。少なくとも、モンスターを倒すまではそんなことしない。違うか？」"

[[dialogue]]
speaker = "梨緒"
# 「……違わない」
line = "「……違わない」"

[[dialogue]]
speaker = "クロト"
# 「じゃあいくぞ」
line = "「じゃあいくぞ」"

[[dialogue]]
speaker = "梨緒"
# 「君と協力するのは不本意だが……仕方ない！」
line = "「君と協力するのは不本意だが……仕方ない！」"

[[dialogue]]
speaker = "unk"
# 梨緒が電光を帯びて稲妻の速さで宙を<ruby=はし>奔</ruby>る。
line = "梨緒が電光を帯びて稲妻の速さで宙を<ruby>奔<rt>はし</rt></ruby>る。"

[[dialogue]]
speaker = "unk"
# 俺はモンスターの鼻面めがけて一気に踏み込む！
line = "俺はモンスターの鼻面めがけて一気に踏み込む！"

[[dialogue]]
speaker = "クロト"
# 「おおおっ！！」
line = "「おおおっ！！」"

[[dialogue]]
speaker = "ドラケルス"
# 「ガァウゥ！」
line = "「ガァウゥ！」"

[[dialogue]]
speaker = "unk"
# モンスターがまた突進する寸前、加速が乗る前に肉薄し、正面から拳で動きを押さえた。
line = "モンスターがまた突進する寸前、加速が乗る前に肉薄し、正面から拳で動きを押さえた。"

[[dialogue]]
speaker = "unk"
# 全身が肉塊になりそうな衝撃に骨が軋み、体が弾けそうになる。
line = "全身が肉塊になりそうな衝撃に骨が軋み、体が弾けそうになる。"

[[dialogue]]
speaker = "unk"
# だが──
line = "だが──"

[[dialogue]]
speaker = "梨緒"
# 「ディヴァインサンダーボルト！」
line = "「ディヴァインサンダーボルト！」"

[[dialogue]]
speaker = "ドラケルス"
# 「グルルル……！！」
line = "「グルルル……！！」"

[[dialogue]]
speaker = "unk"
# 梨緒が上空から放った無数の矢が一条の巨大な雷に変わり、モンスターを撃ち抜いた。
line = "梨緒が上空から放った無数の矢が一条の巨大な雷に変わり、モンスターを撃ち抜いた。"

[[dialogue]]
speaker = "unk"
# モンスターはその姿を保てなくなり、物言わぬ残骸になり果てた。
line = "モンスターはその姿を保てなくなり、物言わぬ残骸になり果てた。"

[[dialogue]]
speaker = "梨緒"
# 「ふぅ……倒せたな」
line = "「ふぅ……倒せたな」"

[[dialogue]]
speaker = "unk"
# 彼女の力はヴィーナスに比肩する……いやそれ以上かもしれない。
line = "彼女の力はヴィーナスに比肩する……いやそれ以上かもしれない。"

[[dialogue]]
speaker = "unk"
# つまり星徒会長に値する実力を持っている。御前試合を挑むだけのことはあるということだ。
line = "つまり星徒会長に値する実力を持っている。御前試合を挑むだけのことはあるということだ。"

[[dialogue]]
speaker = "クロト"
# 「周囲にモンスターの反応なし。梨緒のおかげで街を守れたよ。ありがとう」
line = "「周囲にモンスターの反応なし。梨緒のおかげで街を守れたよ。ありがとう」"

[[dialogue]]
speaker = "梨緒"
# 「良かった。私は<ruby=むこ>無辜</ruby>の人々を守るために星騎士になったんだからな」
line = "「良かった。私は<ruby>無辜<rt>むこ</rt></ruby>の人々を守るために星騎士になったんだからな」"

[[dialogue]]
speaker = "unk"
# 嬉しそうに梨緒の顔が綻ぶ。
line = "嬉しそうに梨緒の顔が綻ぶ。"

[[dialogue]]
speaker = "unk"
# ずっと張り詰めていた表情をしていたから、笑顔を見たのは初めてだ。
line = "ずっと張り詰めていた表情をしていたから、笑顔を見たのは初めてだ。"

[[dialogue]]
speaker = "unk"
# 彼女についてはわからないことだらけだけど、街を守れて喜ぶ様子は、俺たちと変わらない１人の星騎士のように思えた。
line = "彼女についてはわからないことだらけだけど、街を守れて喜ぶ様子は、俺たちと変わらない１人の星騎士のように思えた。"

[[dialogue]]
speaker = "梨緒"
# 「──！　礼はいらない。慣れ合う気はないと言っただろう」
line = "「──！　礼はいらない。慣れ合う気はないと言っただろう」"

[[dialogue]]
speaker = "梨緒"
# 「次に会った時は御前試合の答えを聞かせてもらう。また会おう」
line = "「次に会った時は御前試合の答えを聞かせてもらう。また会おう」"

[[dialogue]]
speaker = "クロト"
# 「ああ……次はちゃんと答えないとな」
line = "「ああ……次はちゃんと答えないとな」"

[[dialogue]]
speaker = "unk"
# 笑顔を消して去っていく梨緒の背中を見送り、俺も帰路に就いた。
line = "笑顔を消して去っていく梨緒の背中を見送り、俺も帰路に就いた。"
