[[dialogue]]
speaker = "unk"
# 第１１話,平行世界の日常,B
line = "第１１話,平行世界の日常,B"

[[dialogue]]
speaker = "unk"
# 昼食と買い出しのために、またビル街に戻ってきた。
line = "昼食と買い出しのために、またビル街に戻ってきた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「せっかく未来の流星市国に来たんだから、なにか斬新なものが食べたいわね」
line = "「せっかく未来の流星市国に来たんだから、なにか斬新なものが食べたいわね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ところでせっかくデネブに里帰りしたんだし、デネブ土産とか売ってないのかしら。デネブまんじゅうとか」
line = "「ところでせっかくデネブに里帰りしたんだし、デネブ土産とか売ってないのかしら。デネブまんじゅうとか」"

[[dialogue]]
speaker = "クロト"
# 「平行世界から来てるのは俺たちだけだから、誰も買わないんじゃないか……？」
line = "「平行世界から来てるのは俺たちだけだから、誰も買わないんじゃないか……？」"

[[dialogue]]
speaker = "？？？"
# 「流星市国のお土産にいかがですかー」
line = "「流星市国のお土産にいかがですかー」"

[[dialogue]]
speaker = "ヴィーナス"
# 「──！？」
line = "「──！？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「流星ハニーサンド、おひとついかがですか？　通販していない商品で、こちらのショップでのみお買い求めいただけます」
line = "「流星ハニーサンド、おひとついかがですか？　通販していない商品で、こちらのショップでのみお買い求めいただけます」"

[[dialogue]]
speaker = "unk"
# 声を聞いて振り返ると、ルヴィネがスイーツショップの店頭に立って、商品の宣伝をしていた。
line = "声を聞いて振り返ると、ルヴィネがスイーツショップの店頭に立って、商品の宣伝をしていた。"

[[dialogue]]
speaker = "ヴィーナス"
# （リノおばあちゃんが言ってたけど、ほんとにルヴィネがバイトしてるわね……）
line = "（リノおばあちゃんが言ってたけど、ほんとにルヴィネがバイトしてるわね……）"

[[dialogue]]
speaker = "リノ"
# 「あ、そうそう。街ではルヴィネに気を付けて」
line = "「あ、そうそう。街ではルヴィネに気を付けて」"

[[dialogue]]
speaker = "リノ"
# 「どういうつもりか知らないけど、彼女、流星市国のいろんなところでバイトしてるの」
line = "「どういうつもりか知らないけど、彼女、流星市国のいろんなところでバイトしてるの」"

[[dialogue]]
speaker = "リノ"
# 「どこで出くわすかわからないから、周囲には注意して行動してね」
line = "「どこで出くわすかわからないから、周囲には注意して行動してね」"

[[dialogue]]
speaker = "ルヴィネ"
# 「流星市国限定、流星ハニーサンドいかがですか？　定番商品のバターサンドもご用意していますよ」
line = "「流星市国限定、流星ハニーサンドいかがですか？　定番商品のバターサンドもご用意していますよ」"

[[dialogue]]
speaker = "unk"
# ルヴィネの視界に入らないよう注意しながら、遠巻きに様子を窺う。
line = "ルヴィネの視界に入らないよう注意しながら、遠巻きに様子を窺う。"

[[dialogue]]
speaker = "unk"
# 母さんの魔法がかかっているとはいえ、ルヴィネなら見破ってもおかしくない。
line = "母さんの魔法がかかっているとはいえ、ルヴィネなら見破ってもおかしくない。"

[[dialogue]]
speaker = "？？？"
# 「お疲れ様です、ルヴィネ会長。今日はこちらでアルバイトされていたのですね」
line = "「お疲れ様です、ルヴィネ会長。今日はこちらでアルバイトされていたのですね」"

[[dialogue]]
speaker = "ルヴィネ"
# 「あら、エステルじゃない。流星ハニーサンド、試食していく？」
line = "「あら、エステルじゃない。流星ハニーサンド、試食していく？」"

[[dialogue]]
speaker = "エステル"
# 「ではおひとつ頂きます」
line = "「ではおひとつ頂きます」"

[[dialogue]]
speaker = "エステル"
# 「ふむふむ、これは……しっかりした甘さがありながら、ハチミツの風味が生きた味わいですね。とても美味です」
line = "「ふむふむ、これは……しっかりした甘さがありながら、ハチミツの風味が生きた味わいですね。とても美味です」"

[[dialogue]]
speaker = "エステル"
# 「一箱頂きます。家族で分けたいと思います」
line = "「一箱頂きます。家族で分けたいと思います」"

[[dialogue]]
speaker = "ルヴィネ"
# 「お買い上げありがとう」
line = "「お買い上げありがとう」"

[[dialogue]]
speaker = "ヴィーナス"
# （流星ハニーサンド、美味しそうね……）
line = "（流星ハニーサンド、美味しそうね……）"

[[dialogue]]
speaker = "クロト"
# （今買いに行っちゃダメだぞ）
line = "（今買いに行っちゃダメだぞ）"

[[dialogue]]
speaker = "ヴィーナス"
# （わかってるわよー）
line = "（わかってるわよー）"

[[dialogue]]
speaker = "ルヴィネ"
# 「そろそろお昼休憩ね。せっかくだから一緒に食事でもどう？」
line = "「そろそろお昼休憩ね。せっかくだから一緒に食事でもどう？」"

[[dialogue]]
speaker = "エステル"
# 「よろしいのですか？　光栄に預かり恐縮です」
line = "「よろしいのですか？　光栄に預かり恐縮です」"

[[dialogue]]
speaker = "エステル"
# 「ですが、この辺りですとどんなお店があるのでしょう？　普段外食をしないものですから、存じ上げなくて」
line = "「ですが、この辺りですとどんなお店があるのでしょう？　普段外食をしないものですから、存じ上げなくて」"

[[dialogue]]
speaker = "ルヴィネ"
# 「それならいいお店を知ってるわ。──担々麺<ruby=かせん>火仙</ruby>。関東に初出店した仙台の名店よ」
line = "「それならいいお店を知ってるわ。──担々麺<ruby>火仙<rt>かせん</rt></ruby>。関東に初出店した仙台の名店よ」"

[[dialogue]]
speaker = "エステル"
# 「担々麺……！？　ルヴィネ会長が、担々麺がお好きだったとは思いませんでした」
line = "「担々麺……！？　ルヴィネ会長が、担々麺がお好きだったとは思いませんでした」"

[[dialogue]]
speaker = "エステル"
# 「その……正直に言いますと、食事に拘りを持たない方かと思っておりましたので……」
line = "「その……正直に言いますと、食事に拘りを持たない方かと思っておりましたので……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「そうね、昔の自分はそうだったわ。今でも非効率だとは思っているのだけど」
line = "「そうね、昔の自分はそうだったわ。今でも非効率だとは思っているのだけど」"

[[dialogue]]
speaker = "ルヴィネ"
# 「だけど友人に言われたことがあるの。食事を楽しまないなんて、人生損してるって」
line = "「だけど友人に言われたことがあるの。食事を楽しまないなんて、人生損してるって」"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "エステル"
# 「ルヴィネ会長？　何か気掛かりなことが……？」
line = "「ルヴィネ会長？　何か気掛かりなことが……？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「いえ、何でもないわ。今気にしても仕方ないことだわ」
line = "「いえ、何でもないわ。今気にしても仕方ないことだわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「彼女に言われて色々試しに食べてみたら、担々麺を気に入ってね」
line = "「彼女に言われて色々試しに食べてみたら、担々麺を気に入ってね」"

[[dialogue]]
speaker = "ルヴィネ"
# 「でも私思うの──」
line = "「でも私思うの──」"

[[dialogue]]
speaker = "ルヴィネ"
# 「担々麺はゴマが命！」
line = "「担々麺はゴマが命！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ひき肉のジューシーさも、唐辛子の辛さも、<ruby=ホアジャオ>花椒</ruby>の痺れも、担々麺の美味しさを引き立ててくれる」
line = "「ひき肉のジューシーさも、唐辛子の辛さも、<ruby>花椒<rt>ホアジャオ</rt></ruby>の痺れも、担々麺の美味しさを引き立ててくれる」"

[[dialogue]]
speaker = "ルヴィネ"
# 「だけど担々麺を担々麺たらしめるのはゴマの旨味よ！」
line = "「だけど担々麺を担々麺たらしめるのはゴマの旨味よ！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ゴマを使うのはオリジナルとは違うアレンジなのは知っているわ。それでもやはりゴマを欠かしては担々麺たりえないと──」
line = "「ゴマを使うのはオリジナルとは違うアレンジなのは知っているわ。それでもやはりゴマを欠かしては担々麺たりえないと──」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……語り過ぎてしまったわ。ごめんなさい」
line = "「……語り過ぎてしまったわ。ごめんなさい」"

[[dialogue]]
speaker = "エステル"
# 「い、いえ……参考になりました」
line = "「い、いえ……参考になりました」"

[[dialogue]]
speaker = "ヴィーナス"
# （担々麺が好きなんて、見た目はちっちゃくてお人形みたいなのに似合わないわね）
line = "（担々麺が好きなんて、見た目はちっちゃくてお人形みたいなのに似合わないわね）"

[[dialogue]]
speaker = "クロト"
# （まぁ、好きなものは人それぞれだし……確かに意外であるけど）
line = "（まぁ、好きなものは人それぞれだし……確かに意外であるけど）"

[[dialogue]]
speaker = "クロト"
# 「──！」
line = "「──！」"

[[dialogue]]
speaker = "unk"
# その時、モンスターの襲来を知らせるアラートがＤＩＳＣから鳴り響く。
line = "その時、モンスターの襲来を知らせるアラートがＤＩＳＣから鳴り響く。"

[[dialogue]]
speaker = "ルヴィネ"
# 「モンスター……ここの近くと、東の２箇所ね」
line = "「モンスター……ここの近くと、東の２箇所ね」"

[[dialogue]]
speaker = "ルヴィネ"
# 「エステル。ここは私に任せて、あなたは東に現れたモンスターをお願い」
line = "「エステル。ここは私に任せて、あなたは東に現れたモンスターをお願い」"

[[dialogue]]
speaker = "エステル"
# 「かしこまりました」
line = "「かしこまりました」"

[[dialogue]]
speaker = "エステル"
# 「エステル・ミルフォード、参ります」
line = "「エステル・ミルフォード、参ります」"

[[dialogue]]
speaker = "unk"
# エステルと呼ばれた星騎士は、戦闘服に変身するとルヴィネの指示通りに飛んでいった。
line = "エステルと呼ばれた星騎士は、戦闘服に変身するとルヴィネの指示通りに飛んでいった。"

[[dialogue]]
speaker = "ダークキングフワッチ"
# 「イ～～～～～～～～ッ！！」
line = "「イ～～～～～～～～ッ！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「消えなさい」
line = "「消えなさい」"

[[dialogue]]
speaker = "ダークキングフワッチ"
# 「イ～～～……」
line = "「イ～～～……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「みんな、もう大丈夫よ」
line = "「みんな、もう大丈夫よ」"

[[dialogue]]
speaker = "unk"
# あっという間にモンスターを倒し、周囲の人に微笑みかけるルヴィネ。
line = "あっという間にモンスターを倒し、周囲の人に微笑みかけるルヴィネ。"

[[dialogue]]
speaker = "unk"
# その様は、デネブの守護者と表現されるに相応しいものだった。
line = "その様は、デネブの守護者と表現されるに相応しいものだった。"

[[dialogue]]
speaker = "ルヴィネ"
# 「これからお昼を食べるところだったのに……エステルと合流しましょう」
line = "「これからお昼を食べるところだったのに……エステルと合流しましょう」"

[[dialogue]]
speaker = "unk"
# ルヴィネは昼食を邪魔されたことに若干の憤りを見せつつ、エステルが飛んだ方向へと向かっていった。
line = "ルヴィネは昼食を邪魔されたことに若干の憤りを見せつつ、エステルが飛んだ方向へと向かっていった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「行ったわね……」
line = "「行ったわね……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だけどルヴィネのやつ、いろいろ怪しいのにモンスターは倒すのね。敵と敵が戦ってるみたいで不思議だわ」
line = "「だけどルヴィネのやつ、いろいろ怪しいのにモンスターは倒すのね。敵と敵が戦ってるみたいで不思議だわ」"

[[dialogue]]
speaker = "クロト"
# 「そうだな……少なくとも今見た限りでは、彼女は真摯に流星市国を守ろうとしているみたいだった」
line = "「そうだな……少なくとも今見た限りでは、彼女は真摯に流星市国を守ろうとしているみたいだった」"

[[dialogue]]
speaker = "クロト"
# （俺たちはルヴィネはリクリエ側だと疑っている……でも本当にそれだけなんだろうか……？）
line = "（俺たちはルヴィネはリクリエ側だと疑っている……でも本当にそれだけなんだろうか……？）"
