[[dialogue]]
speaker = "unk"
# 第１０話,日誌に導かれて,B
line = "第１０話,日誌に導かれて,B"

[[dialogue]]
speaker = "クロト"
# 「それでヴィーナス──『日誌』の増えたページには、他になにか書かれてなかったのか？」
line = "「それでヴィーナス──『日誌』の増えたページには、他になにか書かれてなかったのか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んー、ちょいとあるわね」
line = "「んー、ちょいとあるわね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「『塔の奥地で私たちは《境界》に出会う。彼女との出会いは《魔王》の目覚めを促進するものと信じて……』」
line = "「『塔の奥地で私たちは《境界》に出会う。彼女との出会いは《魔王》の目覚めを促進するものと信じて……』」"

[[dialogue]]
speaker = "ヴィーナス"
# 「──だって！」
line = "「──だって！」"

[[dialogue]]
speaker = "クロト"
# 「《境界》……あれ。さっき、フィオナの話でその言葉が出なかったか？」
line = "「《境界》……あれ。さっき、フィオナの話でその言葉が出なかったか？」"

[[dialogue]]
speaker = "フィオナ"
# 「！　そうですね。私たち流星星徒会がアステラで出会った守護天使──彼女は《境界》を司るものと名乗っていました」
line = "「！　そうですね。私たち流星星徒会がアステラで出会った守護天使──彼女は《境界》を司るものと名乗っていました」"

[[dialogue]]
speaker = "ヴィーナス"
# 「へえ。ビンゴじゃない！」
line = "「へえ。ビンゴじゃない！」"

[[dialogue]]
speaker = "ニャリオン"
# 「ニャニャ。この先に同じのが待ってるのかニャン……？」
line = "「ニャニャ。この先に同じのが待ってるのかニャン……？」"

[[dialogue]]
speaker = "クロト"
# 「それに魔王の目覚め……か。わからないが、今は進んでいくしかない」
line = "「それに魔王の目覚め……か。わからないが、今は進んでいくしかない」"

[[dialogue]]
speaker = "unk"
# ヴィーナスに栞を託した存在がこの先で待ち受けている──とすれば、筋は通っている。
line = "ヴィーナスに栞を託した存在がこの先で待ち受けている──とすれば、筋は通っている。"

[[dialogue]]
speaker = "unk"
# 俺たちは日誌の記述に従い、塔の奥へと進んでいった……。
line = "俺たちは日誌の記述に従い、塔の奥へと進んでいった……。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふー……また階段ね。もう３階くらいは昇ったのに」
line = "「ふー……また階段ね。もう３階くらいは昇ったのに」"

[[dialogue]]
speaker = "クロト"
# 「外から見た高さを考えると……まだ序の口なんだろうな」
line = "「外から見た高さを考えると……まだ序の口なんだろうな」"

[[dialogue]]
speaker = "unk"
# 行っても行っても同じ景色が続く。
line = "行っても行っても同じ景色が続く。"

[[dialogue]]
speaker = "unk"
# だんだんと、自分たちがどこにいるのか麻痺しかけてくる頃……
line = "だんだんと、自分たちがどこにいるのか麻痺しかけてくる頃……"

[[dialogue]]
speaker = "unk"
# 曲がり角から影が飛び出してきた。
line = "曲がり角から影が飛び出してきた。"

[[dialogue]]
speaker = "不思議な機械？"
# 「ピ……ピ……ガガ……ピピ……ガガ……」
line = "「ピ……ピ……ガガ……ピピ……ガガ……」"

[[dialogue]]
speaker = "フィオナ"
# 「！　驚きました……何でしょう、あれは」
line = "「！　驚きました……何でしょう、あれは」"

[[dialogue]]
speaker = "unk"
# ノイズのような音を出して徘徊する謎の物体。
line = "ノイズのような音を出して徘徊する謎の物体。"

[[dialogue]]
speaker = "unk"
# 機械……のように見えるが。
line = "機械……のように見えるが。"

[[dialogue]]
speaker = "ヴィーナス"
# 「お掃除ロボね、きっと！　マトイの部屋で似たようなのを見たことあるわ！」
line = "「お掃除ロボね、きっと！　マトイの部屋で似たようなのを見たことあるわ！」"

[[dialogue]]
speaker = "クロト"
# 「待て、ヴィーナス。様子がおかしい」
line = "「待て、ヴィーナス。様子がおかしい」"

[[dialogue]]
speaker = "不思議な機械？"
# 「侵入者・発見。対象・四名。人間・<emoji=abb><emoji=abb><emoji=abb>・人間・人間ト推定」
line = "「侵入者・発見。対象・四名。人間・<emoji=abb><emoji=abb><emoji=abb>・人間・人間ト推定」"

[[dialogue]]
speaker = "ニャリオン"
# 「ワガハイが頭数に入っていないニャン！」
line = "「ワガハイが頭数に入っていないニャン！」"

[[dialogue]]
speaker = "不思議な機械？"
# 「モンスター確認。戦力微小ト推定」
line = "「モンスター確認。戦力微小ト推定」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ぷ。モンスター扱いされてる」
line = "「ぷ。モンスター扱いされてる」"

[[dialogue]]
speaker = "ニャリオン"
# 「あ、頭に来たニャン！　あんなロボットもどきはワガハイがスクラップにしてやるニャン！」
line = "「あ、頭に来たニャン！　あんなロボットもどきはワガハイがスクラップにしてやるニャン！」"

[[dialogue]]
speaker = "unk"
# ニャリオンは怒ってそのロボットもどきに突撃していった！
line = "ニャリオンは怒ってそのロボットもどきに突撃していった！"

[[dialogue]]
speaker = "unk"
# しかし……
line = "しかし……"

[[dialogue]]
speaker = "ニャリオン"
# 「グエー！　や、やられたニャン！　こいつ強いニャン！」
line = "「グエー！　や、やられたニャン！　こいつ強いニャン！」"

[[dialogue]]
speaker = "不思議な機械？"
# 「ピピ。ガガ。撃退成功」
line = "「ピピ。ガガ。撃退成功」"

[[dialogue]]
speaker = "unk"
# ニャリオン怒涛のひっかきも機械の体には通用せず、たやすく返り討ちにされてしまった。
line = "ニャリオン怒涛のひっかきも機械の体には通用せず、たやすく返り討ちにされてしまった。"

[[dialogue]]
speaker = "フィオナ"
# 「！　確かに結構な脅威のようです……皆さん、ご注意を」
line = "「！　確かに結構な脅威のようです……皆さん、ご注意を」"

[[dialogue]]
speaker = "クロト"
# 「どうやら──侵入者と見なされてるみたいだな」
line = "「どうやら──侵入者と見なされてるみたいだな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふふん。機械風情がパトロールなんて生意気じゃない！」
line = "「ふふん。機械風情がパトロールなんて生意気じゃない！」"

[[dialogue]]
speaker = "unk"
# 俺たちは臨戦態勢を取る──が、それより先に。
line = "俺たちは臨戦態勢を取る──が、それより先に。"

[[dialogue]]
speaker = "キリカ"
# 「──お下がりください、皆さま」
line = "「──お下がりください、皆さま」"

[[dialogue]]
speaker = "不思議な機械？"
# 「ピガッ──ギギギ！」
line = "「ピガッ──ギギギ！」"

[[dialogue]]
speaker = "クロト"
# 「！？」
line = "「！？」"

[[dialogue]]
speaker = "unk"
# キリカさんの放った拳撃──それから蹴りの合わせ技が、機械をたちまち破壊していた。
line = "キリカさんの放った拳撃──それから蹴りの合わせ技が、機械をたちまち破壊していた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「見えなかった──<ruby=はや>疾</ruby>っ……！」
line = "「見えなかった──<ruby>疾<rt>はや</rt></ruby>っ……！」"

[[dialogue]]
speaker = "クロト"
# 「なんて身のこなしだ──」
line = "「なんて身のこなしだ──」"

[[dialogue]]
speaker = "キリカ"
# 「恐縮です。ですが──そこにも」
line = "「恐縮です。ですが──そこにも」"

[[dialogue]]
speaker = "不思議な機械？"
# 「ピガァッ──！！」
line = "「ピガァッ──！！」"

[[dialogue]]
speaker = "フィオナ"
# 「！　──ありがとうございます、キリカ」
line = "「！　──ありがとうございます、キリカ」"

[[dialogue]]
speaker = "キリカ"
# 「いえ。この身はそのためにあるものですから──それに、まだ来ます」
line = "「いえ。この身はそのためにあるものですから──それに、まだ来ます」"

[[dialogue]]
speaker = "不思議な機械？"
# 「増援……要請……至急、侵入者、排除サレタシ」
line = "「増援……要請……至急、侵入者、排除サレタシ」"

[[dialogue]]
speaker = "不思議な機械？"
# 「ピ……ガ……ガガピピ……ピピ……ガガ……」
line = "「ピ……ガ……ガガピピ……ピピ……ガガ……」"

[[dialogue]]
speaker = "クロト"
# 「さっきより数が増えてる──壊されると仲間を呼ぶ仕組みになってるのか」
line = "「さっきより数が増えてる──壊されると仲間を呼ぶ仕組みになってるのか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なるほどね！　なら、全部集まったところをまとめてぶっ叩くしかないわ！」
line = "「なるほどね！　なら、全部集まったところをまとめてぶっ叩くしかないわ！」"

[[dialogue]]
speaker = "フィオナ"
# 「その算段で参りましょう。新星のお二方、お力を貸していただけますか」
line = "「その算段で参りましょう。新星のお二方、お力を貸していただけますか」"

[[dialogue]]
speaker = "クロト"
# 「もちろんだ。それに、今の俺たちは互いに当事者だろう？」
line = "「もちろんだ。それに、今の俺たちは互いに当事者だろう？」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ、それもそうでしたね。では──共に参りましょう」
line = "「ふふ、それもそうでしたね。では──共に参りましょう」"

[[dialogue]]
speaker = "unk"
# 機械は次々と仲間を呼び、おびただしい頭数に膨れ上がっていた。
line = "機械は次々と仲間を呼び、おびただしい頭数に膨れ上がっていた。"

[[dialogue]]
speaker = "unk"
# しかし、俺たち４人なら戦える。キリカさんも相当な戦力になってくれそうだ。
line = "しかし、俺たち４人なら戦える。キリカさんも相当な戦力になってくれそうだ。"

[[dialogue]]
speaker = "不思議な機械？"
# 「迎撃ヲ開始スル。バトルフォーメーション・Ｂ」
line = "「迎撃ヲ開始スル。バトルフォーメーション・Ｂ」"

[[dialogue]]
speaker = "フィオナ"
# 「──来ます。総員、戦闘準備を」
line = "「──来ます。総員、戦闘準備を」"
