[[dialogue]]
speaker = "unk"
# 第２話,第２話『ホーリー・ベル』,B
line = "第２話,第２話『ホーリー・ベル』,B"

[[dialogue]]
speaker = "クラウディア"
# 「おお！　お主は……ちぇちゅーりえ！」
line = "「おお！　お主は……ちぇちゅーりえ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ツェツィーリエね。それより、なんか不満爆発してるみたいだったけど？」
line = "「ツェツィーリエね。それより、なんか不満爆発してるみたいだったけど？」"

[[dialogue]]
speaker = "クラウディア"
# 「うむ。余は嘆いておる。すっかり人間界の影響を受け、魔女たちがクリスマスなるものに染まっているのではないかと」
line = "「うむ。余は嘆いておる。すっかり人間界の影響を受け、魔女たちがクリスマスなるものに染まっているのではないかと」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「なるほど。確かに、人間はみんなクリスマスが好きだよね」
line = "「なるほど。確かに、人間はみんなクリスマスが好きだよね」"

[[dialogue]]
speaker = "クラウディア"
# 「１２月２５日は余の誕生日だ。故に魔女にとって……否、生きとし生けるもの全てにとって最も尊ぶべき日である！　そういうことであろう！」
line = "「１２月２５日は余の誕生日だ。故に魔女にとって……否、生きとし生けるもの全てにとって最も尊ぶべき日である！　そういうことであろう！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「なるほど……自分の誕生日がクリスマスにかき消されてる気がしてもどかしい、と」
line = "「なるほど……自分の誕生日がクリスマスにかき消されてる気がしてもどかしい、と」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「でも安心して！　今日はそんなおいたわしいクラウディア様のために、特別なプレゼントを持ってきたんだ♪」
line = "「でも安心して！　今日はそんなおいたわしいクラウディア様のために、特別なプレゼントを持ってきたんだ♪」"

[[dialogue]]
speaker = "クラウディア"
# 「おお、もうプレゼントを！？　ちぇちゅりんこ、お主なかなか見どころがあるではないか」
line = "「おお、もうプレゼントを！？　ちぇちゅりんこ、お主なかなか見どころがあるではないか」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ん～、惜しくないっ。ツェツィーリエだよん」
line = "「ん～、惜しくないっ。ツェツィーリエだよん」"

[[dialogue]]
speaker = "クラウディア"
# 「わかっておる！　それで、どんなプレゼントなのだ？」
line = "「わかっておる！　それで、どんなプレゼントなのだ？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「実はですね、秘密裏に作っていた特別な戦闘服があって……」
line = "「実はですね、秘密裏に作っていた特別な戦闘服があって……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ちょ、ちょっと！　どこ行くのさクラウディア様」
line = "「ちょ、ちょっと！　どこ行くのさクラウディア様」"

[[dialogue]]
speaker = "クラウディア"
# 「お主の戦闘服といえば、あのすぐ溶けて裸になる失敗作だろう。ウェンディが痛い目を見たと言っておったぞ」
line = "「お主の戦闘服といえば、あのすぐ溶けて裸になる失敗作だろう。ウェンディが痛い目を見たと言っておったぞ」"

[[dialogue]]
speaker = "クラウディア"
# 「余はそんなもの要らん！　倍増させずとも、魔力だってたっぷりあるしな」
line = "「余はそんなもの要らん！　倍増させずとも、魔力だってたっぷりあるしな」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「やだな～、それって超開発初期の試作バトルスーツの時の話じゃん」
line = "「やだな～、それって超開発初期の試作バトルスーツの時の話じゃん」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「大丈夫大丈夫。今じゃそんなこと起きないし、アタシだってクラウディア様にそんなもの贈らないよん」
line = "「大丈夫大丈夫。今じゃそんなこと起きないし、アタシだってクラウディア様にそんなもの贈らないよん」"

[[dialogue]]
speaker = "クラウディア"
# 「本当か……？」
line = "「本当か……？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「そーそー。ま、騙されたと思って着てみなって～♪」
line = "「そーそー。ま、騙されたと思って着てみなって～♪」"

[[dialogue]]
speaker = "クラウディア"
# 「──おお！？　これは！？」
line = "「──おお！？　これは！？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「じゃじゃーん！　これがクラウディア様専用フォーム──『ホーリー・ベル』ってワケ！」
line = "「じゃじゃーん！　これがクラウディア様専用フォーム──『ホーリー・ベル』ってワケ！」"

[[dialogue]]
speaker = "クラウディア"
# 「これは……ほう……ふむ！　悪くない着心地だぞ」
line = "「これは……ほう……ふむ！　悪くない着心地だぞ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「クラウディア様のために造ったんだよん、ひと足早いけどお誕生日プレゼントってことで」
line = "「クラウディア様のために造ったんだよん、ひと足早いけどお誕生日プレゼントってことで」"

[[dialogue]]
speaker = "クラウディア"
# 「なんと！　余のためにこんなものを開発しておったとは」
line = "「なんと！　余のためにこんなものを開発しておったとは」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「けっこうイケるでしょ」
line = "「けっこうイケるでしょ」"

[[dialogue]]
speaker = "クラウディア"
# 「うむ。このロッドも特別製だな。先端にベルがついておる」
line = "「うむ。このロッドも特別製だな。先端にベルがついておる」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ふふん。それは魔力を使ってジングルベルを奏でることができる優れモノなのさ」
line = "「ふふん。それは魔力を使ってジングルベルを奏でることができる優れモノなのさ」"

[[dialogue]]
speaker = "クラウディア"
# 「どれどれ……おお、本当だ！」
line = "「どれどれ……おお、本当だ！」"

[[dialogue]]
speaker = "クラウディア"
# 「ふんふんふーん♪　ふんふんふーん♪　ふんふんふーんふふーん♪」
line = "「ふんふんふーん♪　ふんふんふーん♪　ふんふんふーんふふーん♪」"

[[dialogue]]
speaker = "クラウディア"
# 「──って違う！　これではすっかり余までクリスマスに染まっておるようではないか！」
line = "「──って違う！　これではすっかり余までクリスマスに染まっておるようではないか！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「まあまあ。愉快なそれは他にも機能が満載なのさ。ホーリー・ベル専用のパーツを取りつけることで、ね」
line = "「まあまあ。愉快なそれは他にも機能が満載なのさ。ホーリー・ベル専用のパーツを取りつけることで、ね」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「たとえば好きなところに雪を降らせたり、空飛ぶソリを出現させたり……」
line = "「たとえば好きなところに雪を降らせたり、空飛ぶソリを出現させたり……」"

[[dialogue]]
speaker = "クラウディア"
# 「ほほー！　それは実に楽しそうだの。ちぇちりーえ、お主の発明も見上げたものではないか！」
line = "「ほほー！　それは実に楽しそうだの。ちぇちりーえ、お主の発明も見上げたものではないか！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ちょっと惜しい！　でもツェツィーリエね」
line = "「ちょっと惜しい！　でもツェツィーリエね」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「これはあの新星、流星学園からの技術提供を受けて開発した戦闘服でね。アタシの自信作なのだよ！」
line = "「これはあの新星、流星学園からの技術提供を受けて開発した戦闘服でね。アタシの自信作なのだよ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「光の魔力をふんだんに利用してるから、クラウディア様にしか扱えない一品だったりするんだよね～」
line = "「光の魔力をふんだんに利用してるから、クラウディア様にしか扱えない一品だったりするんだよね～」"

[[dialogue]]
speaker = "クラウディア"
# 「ふむふむ！　確かにこれは素敵なプレゼントであるぞ！」
line = "「ふむふむ！　確かにこれは素敵なプレゼントであるぞ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「でしょ！？　ついついやりすぎて、ちょいと予算はかさんじゃったんだけど……」
line = "「でしょ！？　ついついやりすぎて、ちょいと予算はかさんじゃったんだけど……」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ともかく、これでクラウディア様もクリスマスをめいっぱい楽しめちゃうってコト♪」
line = "「ともかく、これでクラウディア様もクリスマスをめいっぱい楽しめちゃうってコト♪」"

[[dialogue]]
speaker = "クラウディア"
# 「なるほど……そうか。そういうことか」
line = "「なるほど……そうか。そういうことか」"

[[dialogue]]
speaker = "クラウディア"
# 「余がこれを着ることによって……クリスマスのイメージを塗り替えればいいというわけだな！？」
line = "「余がこれを着ることによって……クリスマスのイメージを塗り替えればいいというわけだな！？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「そうそ……ん？　んん？」
line = "「そうそ……ん？　んん？」"

[[dialogue]]
speaker = "クラウディア"
# 「となれば、こうしてはいられん。大衆の認識を改める必要がある」
line = "「となれば、こうしてはいられん。大衆の認識を改める必要がある」"

[[dialogue]]
speaker = "クラウディア"
# 「１２月２５日は余の誕生日！　それ以外のイベントなど必要ない！　サンタがなんだというのだ！」
line = "「１２月２５日は余の誕生日！　それ以外のイベントなど必要ない！　サンタがなんだというのだ！」"

[[dialogue]]
speaker = "クラウディア"
# 「いずれすべてのカレンダーに余の誕生日と記載するためにも……クリスマスなど忘却の彼方へ追いやってくれるぞ～～～！！」
line = "「いずれすべてのカレンダーに余の誕生日と記載するためにも……クリスマスなど忘却の彼方へ追いやってくれるぞ～～～！！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「おー、予想外の展開だけど……面白いかも？　クラウディア様がどこまでフォームの性能を引き出してくれるか、データが取り放題だ！」
line = "「おー、予想外の展開だけど……面白いかも？　クラウディア様がどこまでフォームの性能を引き出してくれるか、データが取り放題だ！」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「というわけでクラウディア様、アタシもお供しま～す！」
line = "「というわけでクラウディア様、アタシもお供しま～す！」"

[[dialogue]]
speaker = "クラウディア"
# 「わーっはっはっは！　いいぞ、ついて来ーい！」
line = "「わーっはっはっは！　いいぞ、ついて来ーい！」"

[[dialogue]]
speaker = "unk"
# ──そうして、クラウディアの野望が産声をあげたのだった。
line = "──そうして、クラウディアの野望が産声をあげたのだった。"
