[[dialogue]]
speaker = "unk"
# 第１０話,茶屋でひと休み,B
line = "第１０話,茶屋でひと休み,B"

[[dialogue]]
speaker = "unk"
# それから俺たちは街を移動し……
line = "それから俺たちは街を移動し……"

[[dialogue]]
speaker = "unk"
# やはりヴィーナスが『ビビッときた』茶屋を見つけて、そこになだれ込むこととなった。
line = "やはりヴィーナスが『ビビッときた』茶屋を見つけて、そこになだれ込むこととなった。"

[[dialogue]]
speaker = "クロト"
# 「ここは……古民家を改装したカフェみたいだな」
line = "「ここは……古民家を改装したカフェみたいだな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「落ち着くわ～。いい汗もかいたし、ちょうどいいわね」
line = "「落ち着くわ～。いい汗もかいたし、ちょうどいいわね」"

[[dialogue]]
speaker = "unk"
# 俺たちは軒先のテラスに着席し、人通りを眺めながら甘味を楽しむ。
line = "俺たちは軒先のテラスに着席し、人通りを眺めながら甘味を楽しむ。"

[[dialogue]]
speaker = "ヴィーナス"
# 「この抹茶あんみつ中々やるわね──蜜漬けの虎豆を使ってるみたい」
line = "「この抹茶あんみつ中々やるわね──蜜漬けの虎豆を使ってるみたい」"

[[dialogue]]
speaker = "クロト"
# 「豆か。あまり気にしたことはなかったけど……ヴィーナスはこだわるのか？」
line = "「豆か。あまり気にしたことはなかったけど……ヴィーナスはこだわるのか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「家じゃ和菓子しか出てこないから。嫌でも詳しくなるって感じね」
line = "「家じゃ和菓子しか出てこないから。嫌でも詳しくなるって感じね」"

[[dialogue]]
speaker = "クロト"
# 「そうか。九浄家のメイドさんも──言われてみたら和スイーツみたいな格好してるよな」
line = "「そうか。九浄家のメイドさんも──言われてみたら和スイーツみたいな格好してるよな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「何よ、その例え」
line = "「何よ、その例え」"

[[dialogue]]
speaker = "unk"
# 他愛ない話に花を咲かせて……
line = "他愛ない話に花を咲かせて……"

[[dialogue]]
speaker = "unk"
# ひとしきり今日の振り返りを終えたところで、あの件について触れてみた。
line = "ひとしきり今日の振り返りを終えたところで、あの件について触れてみた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「へ？　ため息？」
line = "「へ？　ため息？」"

[[dialogue]]
speaker = "クロト"
# 「ああ。ヴィーナスが、最近浮かない顔してるからって……みんな心配してたよ」
line = "「ああ。ヴィーナスが、最近浮かない顔してるからって……みんな心配してたよ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あー……うん。見通しがつかなくて参ってただけなんだけど」
line = "「あー……うん。見通しがつかなくて参ってただけなんだけど」"

[[dialogue]]
speaker = "クロト"
# 「わかってる。でもみんな、普段のヴィーナスに支えられてるから──心配してたぞ」
line = "「わかってる。でもみんな、普段のヴィーナスに支えられてるから──心配してたぞ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あはは……ごめんごめん。もう、みんな私がいないとダメねぇ」
line = "「あはは……ごめんごめん。もう、みんな私がいないとダメねぇ」"

[[dialogue]]
speaker = "unk"
# 今日はいつもより落ち着いていたし、楽しんでくれたみたいでよかった。
line = "今日はいつもより落ち着いていたし、楽しんでくれたみたいでよかった。"

[[dialogue]]
speaker = "unk"
# もしかしたら昨日あたりに──誰かと何かあったのかもな。
line = "もしかしたら昨日あたりに──誰かと何かあったのかもな。"

[[dialogue]]
speaker = "ヴィーナス"
# 「……待っててね」
line = "「……待っててね」"

[[dialogue]]
speaker = "クロト"
# 「……何をだ？」
line = "「……何をだ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「アポロのこと。クロトだって、ここ最近ずっと考えてるでしょ」
line = "「アポロのこと。クロトだって、ここ最近ずっと考えてるでしょ」"

[[dialogue]]
speaker = "クロト"
# 「……そうだな。まだ糸口は見えないが」
line = "「……そうだな。まだ糸口は見えないが」"

[[dialogue]]
speaker = "unk"
# アポロは悪で、それを倒す──そう単純に図式化できているうちはまだよかった。
line = "アポロは悪で、それを倒す──そう単純に図式化できているうちはまだよかった。"

[[dialogue]]
speaker = "unk"
# でも現実は、フィオナの素性までも絡んだ複雑な関係になってしまっている。ただの勧善懲悪で済む話ではない。
line = "でも現実は、フィオナの素性までも絡んだ複雑な関係になってしまっている。ただの勧善懲悪で済む話ではない。"

[[dialogue]]
speaker = "クロト"
# 「──俺、ひとつ考えたんだ。現状を打開するための策を」
line = "「──俺、ひとつ考えたんだ。現状を打開するための策を」"

[[dialogue]]
speaker = "ヴィーナス"
# 「！　それって？」
line = "「！　それって？」"

[[dialogue]]
speaker = "クロト"
# 「ああ。フィーニスの塔に登ってみる──ってのはどうだ」
line = "「ああ。フィーニスの塔に登ってみる──ってのはどうだ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……学園を離れることになるわよ。それでも？」
line = "「……学園を離れることになるわよ。それでも？」"

[[dialogue]]
speaker = "クロト"
# 「確かにリスクもある。けど、月の壁画にしろ、リクリエの真実にしろ……今まで俺たちを導いてきた真実はいつもあそこにあった」
line = "「確かにリスクもある。けど、月の壁画にしろ、リクリエの真実にしろ……今まで俺たちを導いてきた真実はいつもあそこにあった」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そう言われてみれば、そうね……」
line = "「そう言われてみれば、そうね……」"

[[dialogue]]
speaker = "unk"
# 無論、あの塔に入るからには相応の覚悟が要る。
line = "無論、あの塔に入るからには相応の覚悟が要る。"

[[dialogue]]
speaker = "unk"
# 道中の険しさも半端ではないし、奥には必ず強敵が待ち受けているだろう。
line = "道中の険しさも半端ではないし、奥には必ず強敵が待ち受けているだろう。"

[[dialogue]]
speaker = "クロト"
# 「フィオナにも声をかけて、また俺たち３人で行ってもいい。何もしないよりは、あえて虎穴に入ってみるのも大事だろう」
line = "「フィオナにも声をかけて、また俺たち３人で行ってもいい。何もしないよりは、あえて虎穴に入ってみるのも大事だろう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……なるほどね。よくわかったわ──けど」
line = "「……なるほどね。よくわかったわ──けど」"

[[dialogue]]
speaker = "ヴィーナス"
# 「今まで、塔に登る時は……必ず日誌をあてにしてきたわよね。天高き塔がなんとか──って」
line = "「今まで、塔に登る時は……必ず日誌をあてにしてきたわよね。天高き塔がなんとか──って」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でも今は、まだ塔のことなんてひとつも書かれていないわ。まだ動いちゃダメなのかもしれない」
line = "「でも今は、まだ塔のことなんてひとつも書かれていないわ。まだ動いちゃダメなのかもしれない」"

[[dialogue]]
speaker = "クロト"
# 「何も記述を待たなくてもいい。日誌の先手を打つことに不都合はないだろ？」
line = "「何も記述を待たなくてもいい。日誌の先手を打つことに不都合はないだろ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「わかんない。けどやっぱり──日誌に背くのは座りが悪いのよ。大事なことならなおさらね」
line = "「わかんない。けどやっぱり──日誌に背くのは座りが悪いのよ。大事なことならなおさらね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「お願いクロト。もう少し待って。それもこれも──日誌が書かれるまでの辛抱だから」
line = "「お願いクロト。もう少し待って。それもこれも──日誌が書かれるまでの辛抱だから」"

[[dialogue]]
speaker = "クロト"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは譲らなかった。
line = "ヴィーナスは譲らなかった。"

[[dialogue]]
speaker = "unk"
# 今日も明日も平穏な日々と、日誌に記されている以上、それを裏切るような行動はしたくないのだという。
line = "今日も明日も平穏な日々と、日誌に記されている以上、それを裏切るような行動はしたくないのだという。"

[[dialogue]]
speaker = "unk"
# 先ほどまでの、直感とフィーリングで動いていた彼女とは──えらい違いだ。
line = "先ほどまでの、直感とフィーリングで動いていた彼女とは──えらい違いだ。"

[[dialogue]]
speaker = "クロト"
# 「わかった。日誌なんだけど──少し見せてみてくれ」
line = "「わかった。日誌なんだけど──少し見せてみてくれ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「？　いいけど……」
line = "「？　いいけど……」"

[[dialogue]]
speaker = "クロト"
# （……）
line = "（……）"

[[dialogue]]
speaker = "unk"
# 今日の日付を見る。
line = "今日の日付を見る。"

[[dialogue]]
speaker = "unk"
# なんの事件もない平穏な一日──確かに今のところその通りだ。
line = "なんの事件もない平穏な一日──確かに今のところその通りだ。"

[[dialogue]]
speaker = "unk"
# そこには当然、風船のこともあんみつのことも書かれちゃいなかった。
line = "そこには当然、風船のこともあんみつのことも書かれちゃいなかった。"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナス。これ、借りてもいいか？」
line = "「ヴィーナス。これ、借りてもいいか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「へ？　日誌のこと？」
line = "「へ？　日誌のこと？」"

[[dialogue]]
speaker = "クロト"
# 「ああ。ちょっと気になることがあって──明日には返すよ」
line = "「ああ。ちょっと気になることがあって──明日には返すよ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ん～～～…………ホントは、命と同じくらい大切なものなんだけど……」
line = "「ん～～～…………ホントは、命と同じくらい大切なものなんだけど……」"

[[dialogue]]
speaker = "unk"
# うんうんと悩むヴィーナス。しかし。
line = "うんうんと悩むヴィーナス。しかし。"

[[dialogue]]
speaker = "ヴィーナス"
# 「うん、クロトならいいわ！　──特別よ。ただし、明日までには返すこと」
line = "「うん、クロトならいいわ！　──特別よ。ただし、明日までには返すこと」"

[[dialogue]]
speaker = "クロト"
# 「ありがとう。もし、重要な追記がされたらすぐに連絡するよ」
line = "「ありがとう。もし、重要な追記がされたらすぐに連絡するよ」"

[[dialogue]]
speaker = "unk"
# 俺はヴィーナスから借りた『未来の日誌』を大事にしまった。
line = "俺はヴィーナスから借りた『未来の日誌』を大事にしまった。"

[[dialogue]]
speaker = "unk"
# それから席を立つ。
line = "それから席を立つ。"

[[dialogue]]
speaker = "クロト"
# 「ちょっとお手洗いに行ってくる。俺の分のわらび餅、食べてていいよ」
line = "「ちょっとお手洗いに行ってくる。俺の分のわらび餅、食べてていいよ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ほへ？」
line = "「ほへ？」"

[[dialogue]]
speaker = "クロト"
# 「もう口に入れてんのかい」
line = "「もう口に入れてんのかい」"

[[dialogue]]
speaker = "unk"
# 俺はテーブルを後にして洗面所へと向かう。
line = "俺はテーブルを後にして洗面所へと向かう。"

[[dialogue]]
speaker = "unk"
# こうしてお手洗いに行っておいて──その隙に会計も済ませておくというデキる男のテクを使わせてもらおうか。
line = "こうしてお手洗いに行っておいて──その隙に会計も済ませておくというデキる男のテクを使わせてもらおうか。"

[[dialogue]]
speaker = "クロト"
# （ヴィーナスはきっと、男として俺を見直すことだろう……ふふ）
line = "（ヴィーナスはきっと、男として俺を見直すことだろう……ふふ）"
