[[dialogue]]
speaker = "unk"
# 第１話,光の魔法,B
line = "第１話,光の魔法,B"

[[dialogue]]
speaker = "unk"
# 息抜きと称して、街へ繰り出したヴィーナスにクロト──
line = "息抜きと称して、街へ繰り出したヴィーナスにクロト──"

[[dialogue]]
speaker = "unk"
# ２人はしばらくぶりの安息を楽しみ、買い食いやショッピングで羽を伸ばしていた。
line = "２人はしばらくぶりの安息を楽しみ、買い食いやショッピングで羽を伸ばしていた。"

[[dialogue]]
speaker = "unk"
# そんな一幕でのこと──
line = "そんな一幕でのこと──"

[[dialogue]]
speaker = "クラウディア"
# 「──お悩みのようだのう」
line = "「──お悩みのようだのう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……はい？」
line = "「……はい？」"

[[dialogue]]
speaker = "unk"
# それは、クロトが離席していたほんのひと時。
line = "それは、クロトが離席していたほんのひと時。"

[[dialogue]]
speaker = "unk"
# テラス席で物思いにふけるヴィーナスのもとへやってきたのは、ただならぬ雰囲気の二人組だった。
line = "テラス席で物思いにふけるヴィーナスのもとへやってきたのは、ただならぬ雰囲気の二人組だった。"

[[dialogue]]
speaker = "クラウディア"
# 「のう。ここで会ったのも何かの縁だ。悩みがあるなら話してみぬか」
line = "「のう。ここで会ったのも何かの縁だ。悩みがあるなら話してみぬか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「いや──いきなり現れて誰なのよ。っていうか……あんたの方こそがきんちょじゃない！」
line = "「いや──いきなり現れて誰なのよ。っていうか……あんたの方こそがきんちょじゃない！」"

[[dialogue]]
speaker = "クラウディア"
# 「はっはっは。気にするでない」
line = "「はっはっは。気にするでない」"

[[dialogue]]
speaker = "クラウディア"
# 「余はクラウディア──この近くには馴染みの菓子店があってな。ま、滅多には連れ出してもらえんのだが」
line = "「余はクラウディア──この近くには馴染みの菓子店があってな。ま、滅多には連れ出してもらえんのだが」"

[[dialogue]]
speaker = "セドナ"
# 「姫。本来は外出自体許されることではないのです。ご自重を」
line = "「姫。本来は外出自体許されることではないのです。ご自重を」"

[[dialogue]]
speaker = "クラウディア"
# 「けちくさいのう」
line = "「けちくさいのう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あなたは──見覚えあると思ったら、この前の魔女じゃない！」
line = "「あなたは──見覚えあると思ったら、この前の魔女じゃない！」"

[[dialogue]]
speaker = "unk"
# ヴィーナスの脳裏にネビュラの基地が思い描かれる。
line = "ヴィーナスの脳裏にネビュラの基地が思い描かれる。"

[[dialogue]]
speaker = "unk"
# セドナ──そう名乗った黒炎の魔女は、天蓋の危機から星騎士を救った恩人でもあった。
line = "セドナ──そう名乗った黒炎の魔女は、天蓋の危機から星騎士を救った恩人でもあった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ってことは、このチンチクリンも魔女ってこと？」
line = "「ってことは、このチンチクリンも魔女ってこと？」"

[[dialogue]]
speaker = "クラウディア"
# 「そうだ。それもただの魔女ではないぞ、余はすごくてえら～い魔女なのだ」
line = "「そうだ。それもただの魔女ではないぞ、余はすごくてえら～い魔女なのだ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なーんか偉そうで腹立つわね……」
line = "「なーんか偉そうで腹立つわね……」"

[[dialogue]]
speaker = "クラウディア"
# 「どれ──余に手を貸してみるがよい。その浮かぬ顔、晴らしてやれるやもしれんぞ」
line = "「どれ──余に手を貸してみるがよい。その浮かぬ顔、晴らしてやれるやもしれんぞ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「何それ……占い師ごっこでもしてるの？」
line = "「何それ……占い師ごっこでもしてるの？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「確かに考え込んではいたけど──乙女の悩みはフクザツなのよ。あんたみたいなチンチクリンにはわからな──」
line = "「確かに考え込んではいたけど──乙女の悩みはフクザツなのよ。あんたみたいなチンチクリンにはわからな──」"

[[dialogue]]
speaker = "クラウディア"
# 「ふむ──あの男との関係についてか」
line = "「ふむ──あの男との関係についてか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「！　ど、どうしてわかるの……！？」
line = "「！　ど、どうしてわかるの……！？」"

[[dialogue]]
speaker = "クラウディア"
# 「闇を払う──というのは、余の得意分野でのう。吉と出るか凶と出るかは、お主次第だが──」
line = "「闇を払う──というのは、余の得意分野でのう。吉と出るか凶と出るかは、お主次第だが──」"

[[dialogue]]
speaker = "クラウディア"
# 「お主の<ruby=うち>裡</ruby>にある悩みのモヤ──この場で払ってやろう」
line = "「お主の<ruby>裡<rt>うち</rt></ruby>にある悩みのモヤ──この場で払ってやろう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "unk"
# ヴィーナスの頭を占める悩み──それはクロトのことだった。
line = "ヴィーナスの頭を占める悩み──それはクロトのことだった。"

[[dialogue]]
speaker = "unk"
# 九浄ヴィーナスという自我がこの世に芽生えて以降、片時も忘れることのなかった彼の存在を、今になって不思議に思っている。
line = "九浄ヴィーナスという自我がこの世に芽生えて以降、片時も忘れることのなかった彼の存在を、今になって不思議に思っている。"

[[dialogue]]
speaker = "unk"
# 私はなぜ、ここまで彼に惹かれるのだろう──と。
line = "私はなぜ、ここまで彼に惹かれるのだろう──と。"

[[dialogue]]
speaker = "クラウディア"
# 「人助けというやつだ。光の魔女──その力の真髄、とくと味わうがよい」
line = "「人助けというやつだ。光の魔女──その力の真髄、とくと味わうがよい」"

[[dialogue]]
speaker = "セドナ"
# 「っ……姫。お戯れもそれくらいに──組織の掟をお忘れですか」
line = "「っ……姫。お戯れもそれくらいに──組織の掟をお忘れですか」"

[[dialogue]]
speaker = "クラウディア"
# 「ちょっとじゃ、ちょっと♪　セドナは相変わらずお堅いやつよのう」
line = "「ちょっとじゃ、ちょっと♪　セドナは相変わらずお堅いやつよのう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「っ、な──何これ……光の星術……！？」
line = "「っ、な──何これ……光の星術……！？」"

[[dialogue]]
speaker = "クラウディア"
# 「否、否。余は魔女なのだから、使う術など決まっておろう」
line = "「否、否。余は魔女なのだから、使う術など決まっておろう」"

[[dialogue]]
speaker = "unk"
# セドナの制止も振り払い、クラウディアの両手がヴィーナスの両手を包み込む。
line = "セドナの制止も振り払い、クラウディアの両手がヴィーナスの両手を包み込む。"

[[dialogue]]
speaker = "unk"
# すると、目を覆うような輝きが一帯へと漏れ始め──
line = "すると、目を覆うような輝きが一帯へと漏れ始め──"

[[dialogue]]
speaker = "クラウディア"
# 「魔法だ」
line = "「魔法だ」"

[[dialogue]]
speaker = "unk"
# ──まばゆき光の奔流が白鳥の翼のように広がり、ヴィーナスをくるみ込む。
line = "──まばゆき光の奔流が白鳥の翼のように広がり、ヴィーナスをくるみ込む。"

[[dialogue]]
speaker = "unk"
# それと同時に、ヴィーナスの脳裏にはどこかの光景が駆け巡った。
line = "それと同時に、ヴィーナスの脳裏にはどこかの光景が駆け巡った。"

[[dialogue]]
speaker = "？？？"
# 『来季のクラブ予算編成──どうしようかしら。星徒会としては、なるべくどの部にも平等に割り振ってあげたいのだけど』
line = "『来季のクラブ予算編成──どうしようかしら。星徒会としては、なるべくどの部にも平等に割り振ってあげたいのだけど』"

[[dialogue]]
speaker = "クロト"
# 『わかった。なら俺が全部の部長から話を聞いてくるよ』
line = "『わかった。なら俺が全部の部長から話を聞いてくるよ』"

[[dialogue]]
speaker = "？？？"
# 『そんな地道な作業──と思ったけど……それをやっちゃうのがあなたよね』
line = "『そんな地道な作業──と思ったけど……それをやっちゃうのがあなたよね』"

[[dialogue]]
speaker = "？？？"
# 『世界が大変な時だからこそ……そんな時間も、大切にしなくちゃいけないのかも』
line = "『世界が大変な時だからこそ……そんな時間も、大切にしなくちゃいけないのかも』"

[[dialogue]]
speaker = "？？？"
# 『それじゃ、頼りにしてるわね──クロト？』
line = "『それじゃ、頼りにしてるわね──クロト？』"

[[dialogue]]
speaker = "ヴィーナス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "クラウディア"
# 「──ま、こんなところか。まじない程度の術だがのう」
line = "「──ま、こんなところか。まじない程度の術だがのう」"

[[dialogue]]
speaker = "unk"
# 一連の動作を終えて離れるクラウディア。
line = "一連の動作を終えて離れるクラウディア。"

[[dialogue]]
speaker = "unk"
# 一方で、魔法を<b>かけられた</b>ヴィーナスはぽかんと大口を開けたまま唖然としていた。
line = "一方で、魔法を<b>かけられた</b>ヴィーナスはぽかんと大口を開けたまま唖然としていた。"

[[dialogue]]
speaker = "クラウディア"
# 「<ruby=すたあないと>星騎士</ruby>──お主らは余の同志だからな。いずれ、こちらの<b>ぷろじぇくと</b>にも関わってもらわねばならぬ」
line = "「<ruby>星騎士<rt>すたあないと</rt></ruby>──お主らは余の同志だからな。いずれ、こちらの<b>ぷろじぇくと</b>にも関わってもらわねばならぬ」"

[[dialogue]]
speaker = "クラウディア"
# 「って……聞こえておるのかの？」
line = "「って……聞こえておるのかの？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「わた、し……クロト──そっか……そういう…………」
line = "「わた、し……クロト──そっか……そういう…………」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは虚空を見つめたまま、立ち尽くしていた。
line = "ヴィーナスは虚空を見つめたまま、立ち尽くしていた。"

[[dialogue]]
speaker = "unk"
# クラウディアの光の魔法によって──ようやく取り払われたモヤの内側を、整理している。
line = "クラウディアの光の魔法によって──ようやく取り払われたモヤの内側を、整理している。"

[[dialogue]]
speaker = "クラウディア"
# 「ふうむ。当てずっぽうのつもりじゃったが──思いのほか功を奏したようだ。わはは、よいことをしたぞ！」
line = "「ふうむ。当てずっぽうのつもりじゃったが──思いのほか功を奏したようだ。わはは、よいことをしたぞ！」"

[[dialogue]]
speaker = "unk"
# 満足げに高笑いするクラウディア──
line = "満足げに高笑いするクラウディア──"

[[dialogue]]
speaker = "unk"
# しかしその隣では、射抜くような眼光のセドナが腕を組んでいた。
line = "しかしその隣では、射抜くような眼光のセドナが腕を組んでいた。"

[[dialogue]]
speaker = "セドナ"
# 「姫──ご満悦のところ恐縮ですが」
line = "「姫──ご満悦のところ恐縮ですが」"

[[dialogue]]
speaker = "セドナ"
# 「ネビュラとのおやくそく第二十二条──『お外で魔法は使わない』を破りましたね？」
line = "「ネビュラとのおやくそく第二十二条──『お外で魔法は使わない』を破りましたね？」"

[[dialogue]]
speaker = "クラウディア"
# 「ん？　ああ……<ruby=オブリビオン>忘却魔法</ruby>でも使っておけ。見聞きした者の<ruby=メモリー>記憶</ruby>を抹消すれば、問題あるまい！」
line = "「ん？　ああ……<ruby>忘却魔法<rt>オブリビオン</rt></ruby>でも使っておけ。見聞きした者の<ruby>記憶<rt>メモリー</rt></ruby>を抹消すれば、問題あるまい！」"

[[dialogue]]
speaker = "unk"
# クラウディアが派手に魔法を行使したため、テラス席は衆目を集めていた。
line = "クラウディアが派手に魔法を行使したため、テラス席は衆目を集めていた。"

[[dialogue]]
speaker = "unk"
# それでも後始末として、周囲の人間から記憶を消せばよいと彼女は言う。しかし……
line = "それでも後始末として、周囲の人間から記憶を消せばよいと彼女は言う。しかし……"

[[dialogue]]
speaker = "セドナ"
# 「そういう問題ではありません。禁止事項は守るようにと再三お伝えしていたはずです」
line = "「そういう問題ではありません。禁止事項は守るようにと再三お伝えしていたはずです」"

[[dialogue]]
speaker = "セドナ"
# 「よって、来月の日曜外出は禁止とさせていただきます。代わりに英会話の時間でも設けましょうか」
line = "「よって、来月の日曜外出は禁止とさせていただきます。代わりに英会話の時間でも設けましょうか」"

[[dialogue]]
speaker = "クラウディア"
# 「なぬっ！？　な、なぜだ！？　見られても忘れさせればチャラではないのか！？」
line = "「なぬっ！？　な、なぜだ！？　見られても忘れさせればチャラではないのか！？」"

[[dialogue]]
speaker = "セドナ"
# 「関係ありません。我々はあくまで第三組織──表立って魔法を発動するなど言語道断」
line = "「関係ありません。我々はあくまで第三組織──表立って魔法を発動するなど言語道断」"

[[dialogue]]
speaker = "セドナ"
# 「基地へ帰りますよ。森から贈られた新鮮なアスパラガスが待っています」
line = "「基地へ帰りますよ。森から贈られた新鮮なアスパラガスが待っています」"

[[dialogue]]
speaker = "クラウディア"
# 「い……嫌だぞ！　余は野菜など食いとうない！　あああ～～！！」
line = "「い……嫌だぞ！　余は野菜など食いとうない！　あああ～～！！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# クラウディアを引きずって去っていくセドナ──
line = "クラウディアを引きずって去っていくセドナ──"

[[dialogue]]
speaker = "unk"
# 彼女が一帯に忘却のパウダーを散布したことも気に留めず、ヴィーナスは呆然と佇んでいた。
line = "彼女が一帯に忘却のパウダーを散布したことも気に留めず、ヴィーナスは呆然と佇んでいた。"

[[dialogue]]
speaker = "ヴィーナス"
# 「わた、し……クロト──そっか……そういう…………」
line = "「わた、し……クロト──そっか……そういう…………」"

[[dialogue]]
speaker = "unk"
# 悩みの答えとは、己の中にあるものだ──
line = "悩みの答えとは、己の中にあるものだ──"

[[dialogue]]
speaker = "unk"
# クラウディアの言が幾度もヴィーナスの脳裏にリフレインする。
line = "クラウディアの言が幾度もヴィーナスの脳裏にリフレインする。"

[[dialogue]]
speaker = "unk"
# なぜならその指摘は、ヴィーナスにとって紛れもない真実だったからだ。
line = "なぜならその指摘は、ヴィーナスにとって紛れもない真実だったからだ。"

[[dialogue]]
speaker = "unk"
# つまり──
line = "つまり──"

[[dialogue]]
speaker = "ヴィーナス"
# 「──私は、クロトの……………………」
line = "「──私は、クロトの……………………」"
