[[dialogue]]
speaker = "unk"
# 第３話,星騎士の意義,B
line = "第３話,星騎士の意義,B"

[[dialogue]]
speaker = "unk"
# 俺は新星学園の星徒会長として、この前フィーニスの塔で起こったことについて、学園各所や流星星徒会に報告した。
line = "俺は新星学園の星徒会長として、この前フィーニスの塔で起こったことについて、学園各所や流星星徒会に報告した。"

[[dialogue]]
speaker = "unk"
# もちろんディザスターハンドとの遭遇や、梨緒から得た情報も含めてだ。
line = "もちろんディザスターハンドとの遭遇や、梨緒から得た情報も含めてだ。"

[[dialogue]]
speaker = "unk"
# また流星星徒会からも連絡があり、魔界ではまだ危機が去っていないらしく、フィオナはまだ動けそうにないという。
line = "また流星星徒会からも連絡があり、魔界ではまだ危機が去っていないらしく、フィオナはまだ動けそうにないという。"

[[dialogue]]
speaker = "マトイ"
# 「あの手があんな近くにいると思うと、怖いよね……」
line = "「あの手があんな近くにいると思うと、怖いよね……」"

[[dialogue]]
speaker = "unk"
# 窓からフィーニスの塔を眺めながら、マトイが心配そうに呟く。
line = "窓からフィーニスの塔を眺めながら、マトイが心配そうに呟く。"

[[dialogue]]
speaker = "unk"
# ディザスターハンドがいつ世界を襲うかわからない状態なのだから、不安になるのも当然だろう。
line = "ディザスターハンドがいつ世界を襲うかわからない状態なのだから、不安になるのも当然だろう。"

[[dialogue]]
speaker = "サーシャ"
# 「でも今までじっとしてたんだから、きっと動かない理由があるのよね～」
line = "「でも今までじっとしてたんだから、きっと動かない理由があるのよね～」"

[[dialogue]]
speaker = "unk"
# あの手自体に意思があるのか、それとも誰かが操っているのか。
line = "あの手自体に意思があるのか、それとも誰かが操っているのか。"

[[dialogue]]
speaker = "unk"
# 強大な敵であること以外、わからないことだらけだ。
line = "強大な敵であること以外、わからないことだらけだ。"

[[dialogue]]
speaker = "ヴィーナス"
# 「ま、クヨクヨしてても仕方ないわ。あの手はいつか倒す。でしょ、クロト？」
line = "「ま、クヨクヨしてても仕方ないわ。あの手はいつか倒す。でしょ、クロト？」"

[[dialogue]]
speaker = "クロト"
# 「ああ、必ずな」
line = "「ああ、必ずな」"

[[dialogue]]
speaker = "unk"
# その力を目の当たりにしたからこそ、絶望に心折れるわけにはいかない。
line = "その力を目の当たりにしたからこそ、絶望に心折れるわけにはいかない。"

[[dialogue]]
speaker = "unk"
# 決戦の時は必ず来る。それまでに力を取り戻す──いや、それ以上の力を身に付けなければ。
line = "決戦の時は必ず来る。それまでに力を取り戻す──いや、それ以上の力を身に付けなければ。"

[[dialogue]]
speaker = "アナ"
# 「皆さん、大変です……！」
line = "「皆さん、大変です……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あら、珍しいわね。アナがＤＩＳＣで動画見てるなんて」
line = "「あら、珍しいわね。アナがＤＩＳＣで動画見てるなんて」"

[[dialogue]]
speaker = "アナ"
# 「とにかくこれを見てください……！」
line = "「とにかくこれを見てください……！」"

[[dialogue]]
speaker = "unk"
# ＤＩＳＣ片手に現れたのは、慌てた様子のアナ。
line = "ＤＩＳＣ片手に現れたのは、慌てた様子のアナ。"

[[dialogue]]
speaker = "unk"
# 言われた通りアナのＤＩＳＣを見てみると──
line = "言われた通りアナのＤＩＳＣを見てみると──"

[[dialogue]]
speaker = "チナ"
# 『平行世界アルタイルとデネブは敵対関係にある』
line = "『平行世界アルタイルとデネブは敵対関係にある』"

[[dialogue]]
speaker = "チナ"
# 『アルタイルのリクリエを止めれば、デネブのリクリエが加速する。デネブのリクリエを止めれば、アルタイルのリクリエが激化する』
line = "『アルタイルのリクリエを止めれば、デネブのリクリエが加速する。デネブのリクリエを止めれば、アルタイルのリクリエが激化する』"

[[dialogue]]
speaker = "クロト"
# 「！　これは──」
line = "「！　これは──」"

[[dialogue]]
speaker = "アナ"
# 「今朝、彼女の映像が動画配信サイトに投稿されました」
line = "「今朝、彼女の映像が動画配信サイトに投稿されました」"

[[dialogue]]
speaker = "アナ"
# 「ＳＮＳでも拡散されており、今も右肩上がりに再生数が伸び続けています」
line = "「ＳＮＳでも拡散されており、今も右肩上がりに再生数が伸び続けています」"

[[dialogue]]
speaker = "チナ"
# 『いいか、これは生存競争だ。生き残るのはデネブかアルタイル、２つに１つ』
line = "『いいか、これは生存競争だ。生き残るのはデネブかアルタイル、２つに１つ』"

[[dialogue]]
speaker = "チナ"
# 『生き残るのはアタシらだ……！』
line = "『生き残るのはアタシらだ……！』"

[[dialogue]]
speaker = "unk"
# デネブの刺客からの宣戦布告。センセーショナルな内容なのは間違いない。
line = "デネブの刺客からの宣戦布告。センセーショナルな内容なのは間違いない。"

[[dialogue]]
speaker = "unk"
# 数ヶ月前、この世界は存亡の危機にあったのだからなおさらだ。
line = "数ヶ月前、この世界は存亡の危機にあったのだからなおさらだ。"

[[dialogue]]
speaker = "unk"
# 教皇庁周辺は激戦だったから、周囲の人は避難していると思っていたけど、俺たち以外に誰か見ていたのか。
line = "教皇庁周辺は激戦だったから、周囲の人は避難していると思っていたけど、俺たち以外に誰か見ていたのか。"

[[dialogue]]
speaker = "アナ"
# 「コハルコ先輩によれば、動画の削除自体は可能だそうです。拡散したものも手段を選ばなければ消せるとのことですが……」
line = "「コハルコ先輩によれば、動画の削除自体は可能だそうです。拡散したものも手段を選ばなければ消せるとのことですが……」"

[[dialogue]]
speaker = "アナ"
# 「見た人の記憶は消せないし、むしろ隠蔽と見られて悪影響を与えるだろうと」
line = "「見た人の記憶は消せないし、むしろ隠蔽と見られて悪影響を与えるだろうと」"

[[dialogue]]
speaker = "クロト"
# 「それはそうだろうな……」
line = "「それはそうだろうな……」"

[[dialogue]]
speaker = "unk"
# 一度広まったものを躍起になって消そうとするのは逆効果だ。
line = "一度広まったものを躍起になって消そうとするのは逆効果だ。"

[[dialogue]]
speaker = "unk"
# 情報の真偽はともかく、チナがこう言ったことも事実。
line = "情報の真偽はともかく、チナがこう言ったことも事実。"

[[dialogue]]
speaker = "unk"
# 拡散を止めようとすれば不信を招くだろう。
line = "拡散を止めようとすれば不信を招くだろう。"

[[dialogue]]
speaker = "サーシャ"
# 「今調べてみたけど、ネットの反応はまちまちね。平行世界なんて普通の人は知らないもの」
line = "「今調べてみたけど、ネットの反応はまちまちね。平行世界なんて普通の人は知らないもの」"

[[dialogue]]
speaker = "アナ"
# 「特撮やＣＧだと受け取っている人も見られます。ですが彼女の言葉を信じている人も少なからず存在しているようです」
line = "「特撮やＣＧだと受け取っている人も見られます。ですが彼女の言葉を信じている人も少なからず存在しているようです」"

[[dialogue]]
speaker = "unk"
# 平行世界が実在し、アルタイルとデネブという２つの世界が争っている──にわかには信じがたい話だが、チナの言葉を受け入れた人々はいたようだ。
line = "平行世界が実在し、アルタイルとデネブという２つの世界が争っている──にわかには信じがたい話だが、チナの言葉を受け入れた人々はいたようだ。"

[[dialogue]]
speaker = "unk"
# そしてチナがリクリエという言葉を使ったことから、教皇庁や学園が絡んでいると察した人たちもいるらしい。
line = "そしてチナがリクリエという言葉を使ったことから、教皇庁や学園が絡んでいると察した人たちもいるらしい。"

[[dialogue]]
speaker = "マトイ"
# 「う……『隠してたのか』なんて、星騎士に怒ってる人もいる……」
line = "「う……『隠してたのか』なんて、星騎士に怒ってる人もいる……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「隠すも何も、極星学園なんて私たちもついこの前知ったところよ！」
line = "「隠すも何も、極星学園なんて私たちもついこの前知ったところよ！」"

[[dialogue]]
speaker = "unk"
# 俺たち星徒会も、チナの言葉が真実かわからず混乱の<ruby=ただなか>直中</ruby>にあった。
line = "俺たち星徒会も、チナの言葉が真実かわからず混乱の<ruby>直中<rt>ただなか</rt></ruby>にあった。"

[[dialogue]]
speaker = "unk"
# だが今後、リクリエとの戦いの先頭に立つ者として説明を求められるだろう。
line = "だが今後、リクリエとの戦いの先頭に立つ者として説明を求められるだろう。"

[[dialogue]]
speaker = "クロト"
# 「状況は待ってくれないものなんだな、本当に……」
line = "「状況は待ってくれないものなんだな、本当に……」"
