[[dialogue]]
speaker = "unk"
# 第７話,ベアトリスとチナ,B
line = "第７話,ベアトリスとチナ,B"

[[dialogue]]
speaker = "チナ"
# 「ベアト……！？」
line = "「ベアト……！？」"

[[dialogue]]
speaker = "unk"
# ベアトリスが部屋に入った瞬間、驚きで目を丸くするチナ。
line = "ベアトリスが部屋に入った瞬間、驚きで目を丸くするチナ。"

[[dialogue]]
speaker = "unk"
# しかしベアトリスへの呼び方が、以前教皇庁前で出会った時と異なる。
line = "しかしベアトリスへの呼び方が、以前教皇庁前で出会った時と異なる。"

[[dialogue]]
speaker = "ベアトリス"
# 「あ、その呼び方。久しぶりかも」
line = "「あ、その呼び方。久しぶりかも」"

[[dialogue]]
speaker = "チナ"
# 「あ──いや。ベアトリス副会長……無事だったんですね」
line = "「あ──いや。ベアトリス副会長……無事だったんですね」"

[[dialogue]]
speaker = "ベアトリス"
# 「別に言い直さなくてもいいのに……チナちゃんは真面目なんだから」
line = "「別に言い直さなくてもいいのに……チナちゃんは真面目なんだから」"

[[dialogue]]
speaker = "ベアトリス"
# 「ちゃんとした言葉遣いをしないと、極星星徒会の役員として示しがつかない。その考えは理解してるけど……」
line = "「ちゃんとした言葉遣いをしないと、極星星徒会の役員として示しがつかない。その考えは理解してるけど……」"

[[dialogue]]
speaker = "unk"
# チナの生真面目さはベアトリスもよく知っている。
line = "チナの生真面目さはベアトリスもよく知っている。"

[[dialogue]]
speaker = "unk"
# 荒っぽいところはあるが、彼女が振るう槍のように真っ直ぐで一本気な気質だ。
line = "荒っぽいところはあるが、彼女が振るう槍のように真っ直ぐで一本気な気質だ。"

[[dialogue]]
speaker = "ベアトリス"
# 「今はこのとおり、２人きりだよ。だから楽にして欲しいな？　それに──」
line = "「今はこのとおり、２人きりだよ。だから楽にして欲しいな？　それに──」"

[[dialogue]]
speaker = "チナ"
# 「それに？」
line = "「それに？」"

[[dialogue]]
speaker = "ベアトリス"
# 「久しぶりに会えた幼なじみに、役職に縛られて敬語を使われるのは寂しいかなって」
line = "「久しぶりに会えた幼なじみに、役職に縛られて敬語を使われるのは寂しいかなって」"

[[dialogue]]
speaker = "チナ"
# 「……うん」
line = "「……うん」"

[[dialogue]]
speaker = "unk"
# ベアトリスとチナが出会ったのは、今からずっと昔──デネブの、崩壊した流星市国で苦楽を共にしてきた１０年来の親友だった。
line = "ベアトリスとチナが出会ったのは、今からずっと昔──デネブの、崩壊した流星市国で苦楽を共にしてきた１０年来の親友だった。"

[[dialogue]]
speaker = "ベアトリス"
# 「チナちゃんが元気で安心した。あの時別れたきりだったから」
line = "「チナちゃんが元気で安心した。あの時別れたきりだったから」"

[[dialogue]]
speaker = "チナ"
# 「それはこっちのセリフだよ。あの時、ベアトが助けてくれなかったら、アタシはどうなっていたか……。本当にありがとな」
line = "「それはこっちのセリフだよ。あの時、ベアトが助けてくれなかったら、アタシはどうなっていたか……。本当にありがとな」"

[[dialogue]]
speaker = "チナ"
# 「ベアトも怪我してなくてよかった……転送装置に呑まれた後、どうなったのか、気が気じゃなくて……」
line = "「ベアトも怪我してなくてよかった……転送装置に呑まれた後、どうなったのか、気が気じゃなくて……」"

[[dialogue]]
speaker = "ベアトリス"
# 「デネブに戻ってたんだよ。それで、ちょっと前にまたアルタイルに来たところ」
line = "「デネブに戻ってたんだよ。それで、ちょっと前にまたアルタイルに来たところ」"

[[dialogue]]
speaker = "チナ"
# 「ってことはルヴィにも会えたんだな！　よかった、ベアトが留守にしてる間、ずっと心配してたからさ！」
line = "「ってことはルヴィにも会えたんだな！　よかった、ベアトが留守にしてる間、ずっと心配してたからさ！」"

[[dialogue]]
speaker = "ベアトリス"
# 「あ……うん……」
line = "「あ……うん……」"

[[dialogue]]
speaker = "チナ"
# 「でもどうしてベアトがアルタイルのやつらと同じ制服を？」
line = "「でもどうしてベアトがアルタイルのやつらと同じ制服を？」"

[[dialogue]]
speaker = "チナ"
# 「あ、新星学園に潜入してるのか！　ルヴィが言ってた極秘任務ってそれだったんだな！」
line = "「あ、新星学園に潜入してるのか！　ルヴィが言ってた極秘任務ってそれだったんだな！」"

[[dialogue]]
speaker = "チナ"
# 「……あれ？　ってことは、アタシはベアトがいるアルタイルを滅ぼそうとして……いや、ベアトがいるってわかってるなら、ルヴィはそんなことさせないはず……」
line = "「……あれ？　ってことは、アタシはベアトがいるアルタイルを滅ぼそうとして……いや、ベアトがいるってわかってるなら、ルヴィはそんなことさせないはず……」"

[[dialogue]]
speaker = "ベアトリス"
# 「ごくひにんむ？」
line = "「ごくひにんむ？」"

[[dialogue]]
speaker = "チナ"
# 「へ？」
line = "「へ？」"

[[dialogue]]
speaker = "unk"
# お互いに見つめ合ったままキョトンとするベアトリスとチナ。
line = "お互いに見つめ合ったままキョトンとするベアトリスとチナ。"

[[dialogue]]
speaker = "unk"
# どうやら２人の間には認識の齟齬があるようだ。
line = "どうやら２人の間には認識の齟齬があるようだ。"

[[dialogue]]
speaker = "チナ"
# 「ええっと、ベアトは極秘任務で不在だって、ルヴィから聞いてたんだけど……」
line = "「ええっと、ベアトは極秘任務で不在だって、ルヴィから聞いてたんだけど……」"

[[dialogue]]
speaker = "ベアトリス"
# 「あー……実はそうじゃなくてね……」
line = "「あー……実はそうじゃなくてね……」"

[[dialogue]]
speaker = "unk"
# ベアトリスは自身がアルタイルに飛んだ時の出来事とその顛末、そして今はアルタイルの新星学園で選挙管理委員会に所属していることを説明した。
line = "ベアトリスは自身がアルタイルに飛んだ時の出来事とその顛末、そして今はアルタイルの新星学園で選挙管理委員会に所属していることを説明した。"

[[dialogue]]
speaker = "unk"
# それを聞いたチナは、肩を落として大きなため息をつく。
line = "それを聞いたチナは、肩を落として大きなため息をつく。"

[[dialogue]]
speaker = "チナ"
# 「ベアトらしいっちゃベアトらしいけど、教皇庁のあの穴からアルタイルに行くなんて無茶にも程があるだろ……」
line = "「ベアトらしいっちゃベアトらしいけど、教皇庁のあの穴からアルタイルに行くなんて無茶にも程があるだろ……」"

[[dialogue]]
speaker = "チナ"
# 「魔界から流星市国に密航したこともあったし、常習犯じゃないか……」
line = "「魔界から流星市国に密航したこともあったし、常習犯じゃないか……」"

[[dialogue]]
speaker = "チナ"
# 「考えなしっていうか、無鉄砲っていうか、ベアトが優しいのはわかるけど、そういうとこホントよくないと思うぞ……」
line = "「考えなしっていうか、無鉄砲っていうか、ベアトが優しいのはわかるけど、そういうとこホントよくないと思うぞ……」"

[[dialogue]]
speaker = "ベアトリス"
# 「ごめんなさ～いっ」
line = "「ごめんなさ～いっ」"

[[dialogue]]
speaker = "チナ"
# 「ってことは、ルヴィがああ言ったのは、ベアトを庇ったんだな……。ルヴィって、けっこう甘いところあるからな……」
line = "「ってことは、ルヴィがああ言ったのは、ベアトを庇ったんだな……。ルヴィって、けっこう甘いところあるからな……」"

[[dialogue]]
speaker = "チナ"
# 「でも──本当に無事でよかった。装置なしで平行世界を渡るなんて、死んでもおかしくないからな」
line = "「でも──本当に無事でよかった。装置なしで平行世界を渡るなんて、死んでもおかしくないからな」"

[[dialogue]]
speaker = "チナ"
# 「でもどうしてまたアルタイルに？　向こうでルヴィに会ったんじゃ……」
line = "「でもどうしてまたアルタイルに？　向こうでルヴィに会ったんじゃ……」"

[[dialogue]]
speaker = "ベアトリス"
# 「うん。それがチナちゃんに話したいことなの」
line = "「うん。それがチナちゃんに話したいことなの」"

[[dialogue]]
speaker = "ベアトリス"
# 「すごくびっくりするだろうし、信じられないかもしれないけど、聞いて」
line = "「すごくびっくりするだろうし、信じられないかもしれないけど、聞いて」"

[[dialogue]]
speaker = "unk"
# そしてベアトリスは、チナの瞳を真っ直ぐ見つめながら話し始めた──
line = "そしてベアトリスは、チナの瞳を真っ直ぐ見つめながら話し始めた──"

[[dialogue]]
speaker = "チナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ベアトリス"
# 「やっぱり、信じられないよね。でもルヴィは新しい女神で──」
line = "「やっぱり、信じられないよね。でもルヴィは新しい女神で──」"

[[dialogue]]
speaker = "チナ"
# 「ウソだ！　ベアトはアルタイルの連中に騙されてるんだ！」
line = "「ウソだ！　ベアトはアルタイルの連中に騙されてるんだ！」"

[[dialogue]]
speaker = "チナ"
# 「じゃなきゃ、ルヴィが……あのルヴィが！　リクリエを起こそうとしてるなんて、そんなはずない！！」
line = "「じゃなきゃ、ルヴィが……あのルヴィが！　リクリエを起こそうとしてるなんて、そんなはずない！！」"

[[dialogue]]
speaker = "ベアトリス"
# 「違うよ。私は騙されてなんかない。全部私がこの目で見て、聞いてきたことなんだ」
line = "「違うよ。私は騙されてなんかない。全部私がこの目で見て、聞いてきたことなんだ」"

[[dialogue]]
speaker = "チナ"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "unk"
# 取り乱して怒りを露わにするチナに、ベアトリスは険しい顔をしながらも、努めて冷静に応える。
line = "取り乱して怒りを露わにするチナに、ベアトリスは険しい顔をしながらも、努めて冷静に応える。"

[[dialogue]]
speaker = "unk"
# その目は潤み、不安で震えそうになるのを堪えながら、チナに向かい合う。
line = "その目は潤み、不安で震えそうになるのを堪えながら、チナに向かい合う。"

[[dialogue]]
speaker = "ベアトリス"
# 「ディザスターハンドはベガを滅ぼした。ルヴィはそのディザスターハンドと一緒にいた」
line = "「ディザスターハンドはベガを滅ぼした。ルヴィはそのディザスターハンドと一緒にいた」"

[[dialogue]]
speaker = "ベアトリス"
# 「他ならぬ女神テルル様が、ルヴィは新たな女神だって言った」
line = "「他ならぬ女神テルル様が、ルヴィは新たな女神だって言った」"

[[dialogue]]
speaker = "ベアトリス"
# 「そしてルヴィを生み出したのは、女神様の上にいる創造神……『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』だった」
line = "「そしてルヴィを生み出したのは、女神様の上にいる創造神……『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』だった」"

[[dialogue]]
speaker = "ベアトリス"
# 「少なくとも、それは確か。否定したくてもできないんだ」
line = "「少なくとも、それは確か。否定したくてもできないんだ」"

[[dialogue]]
speaker = "チナ"
# 「……っ」
line = "「……っ」"

[[dialogue]]
speaker = "unk"
# チナはベアトリスの発言を否定しようとするが、うまく言葉が出てこない。
line = "チナはベアトリスの発言を否定しようとするが、うまく言葉が出てこない。"

[[dialogue]]
speaker = "ベアトリス"
# 「ごめん……いきなりこんなこと言われても受け止め切れないよね。正直、私だってまだ全部信じられない」
line = "「ごめん……いきなりこんなこと言われても受け止め切れないよね。正直、私だってまだ全部信じられない」"

[[dialogue]]
speaker = "ベアトリス"
# 「でも私、まだ納得してないから」
line = "「でも私、まだ納得してないから」"

[[dialogue]]
speaker = "ベアトリス"
# 「リクリエを起こそうとしてるのが『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』に従ってるからなのか、それともルヴィ自身の意志なのか……もう一度ルヴィに会って、直接聞くの」
line = "「リクリエを起こそうとしてるのが『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』に従ってるからなのか、それともルヴィ自身の意志なのか……もう一度ルヴィに会って、直接聞くの」"

[[dialogue]]
speaker = "ベアトリス"
# 「女神だってことを隠していたように、きっと他にも話してないことたくさんあると思うんだ」
line = "「女神だってことを隠していたように、きっと他にも話してないことたくさんあると思うんだ」"

[[dialogue]]
speaker = "ベアトリス"
# 「それを全部話してもらって、それからどうするか決める」
line = "「それを全部話してもらって、それからどうするか決める」"

[[dialogue]]
speaker = "ベアトリス"
# 「でもその前に、アルタイルを守らないと。天界が襲われて──」
line = "「でもその前に、アルタイルを守らないと。天界が襲われて──」"

[[dialogue]]
speaker = "チナ"
# 「天界が……！？」
line = "「天界が……！？」"

[[dialogue]]
speaker = "unk"
# ベアトリスが天界と口にした途端、チナの表情に動揺が走った。
line = "ベアトリスが天界と口にした途端、チナの表情に動揺が走った。"

[[dialogue]]
speaker = "ベアトリス"
# 「チナちゃん？」
line = "「チナちゃん？」"

[[dialogue]]
speaker = "チナ"
# 「いや……何でもない……」
line = "「いや……何でもない……」"

[[dialogue]]
speaker = "unk"
# 不思議そうに問うベアトリスに、チナはごまかすように目を逸らす。
line = "不思議そうに問うベアトリスに、チナはごまかすように目を逸らす。"

[[dialogue]]
speaker = "ベアトリス"
# 「チナちゃん、何か知ってるの？　だったら私に教えて」
line = "「チナちゃん、何か知ってるの？　だったら私に教えて」"

[[dialogue]]
speaker = "チナ"
# 「そんなの言えるわけ……」
line = "「そんなの言えるわけ……」"

[[dialogue]]
speaker = "ベアトリス"
# 「お願い！　今ならまだ、デネブもアルタイルも救えるかもしれない！」
line = "「お願い！　今ならまだ、デネブもアルタイルも救えるかもしれない！」"

[[dialogue]]
speaker = "ベアトリス"
# 「でもこのままじゃアルタイルが滅びちゃう！　それが『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』の目論見通りだったとしたら、デネブも危ない！」
line = "「でもこのままじゃアルタイルが滅びちゃう！　それが『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』の目論見通りだったとしたら、デネブも危ない！」"

[[dialogue]]
speaker = "ベアトリス"
# 「私は……アルタイルもデネブも救いたい！　誰も見捨てない！　それが私が星騎士になった理由だから！」
line = "「私は……アルタイルもデネブも救いたい！　誰も見捨てない！　それが私が星騎士になった理由だから！」"

[[dialogue]]
speaker = "チナ"
# 「──！」
line = "「──！」"

[[dialogue]]
speaker = "ベアトリス"
# 「デネブとアルタイルが戦えば、リクリエを望む者の思い通りになる。デネブのためにもアルタイルを守らないと！」
line = "「デネブとアルタイルが戦えば、リクリエを望む者の思い通りになる。デネブのためにもアルタイルを守らないと！」"

[[dialogue]]
speaker = "ベアトリス"
# 「だからお願い！　チナちゃんが知ってることを教えて！」
line = "「だからお願い！　チナちゃんが知ってることを教えて！」"

[[dialogue]]
speaker = "チナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "チナ"
# 「……女神の神殿」
line = "「……女神の神殿」"

[[dialogue]]
speaker = "ベアトリス"
# 「女神の……神殿？　守護天使様の神殿じゃなくて？」
line = "「女神の……神殿？　守護天使様の神殿じゃなくて？」"

[[dialogue]]
speaker = "チナ"
# 「うん……女神のほう。約３０００年前、リクリエが退けられた後、三界からは霊力が失われただろ……？」
line = "「うん……女神のほう。約３０００年前、リクリエが退けられた後、三界からは霊力が失われただろ……？」"

[[dialogue]]
speaker = "チナ"
# 「天使たちは元は実体のない霊体で、霊力がなくなれば消滅するはずだった」
line = "「天使たちは元は実体のない霊体で、霊力がなくなれば消滅するはずだった」"

[[dialogue]]
speaker = "チナ"
# 「だけど女神テルルは女神の神殿を作り出し、天使と天界を実体化させた」
line = "「だけど女神テルルは女神の神殿を作り出し、天使と天界を実体化させた」"

[[dialogue]]
speaker = "チナ"
# 「だから女神の神殿が破壊されれば、全ての天使と天界が消滅する……ってルヴィが言ってたんだ」
line = "「だから女神の神殿が破壊されれば、全ての天使と天界が消滅する……ってルヴィが言ってたんだ」"

[[dialogue]]
speaker = "ベアトリス"
# 「──！？　じゃあそれが襲撃の真の狙い！？」
line = "「──！？　じゃあそれが襲撃の真の狙い！？」"

[[dialogue]]
speaker = "チナ"
# 「多分……。ベアトが極星学園からいなくなった後、アルタイルの神殿を破壊する計画を立ててたから」
line = "「多分……。ベアトが極星学園からいなくなった後、アルタイルの神殿を破壊する計画を立ててたから」"

[[dialogue]]
speaker = "チナ"
# 「襲撃があったってことは、天界の調査に行ってたレティシアとグレイスが女神の神殿を見つけた……んだと思う」
line = "「襲撃があったってことは、天界の調査に行ってたレティシアとグレイスが女神の神殿を見つけた……んだと思う」"

[[dialogue]]
speaker = "ベアトリス"
# 「デネブに戻った時、２人と会わなかったのはそのせいだったんだ……」
line = "「デネブに戻った時、２人と会わなかったのはそのせいだったんだ……」"

[[dialogue]]
speaker = "ベアトリス"
# 「チナちゃんは神殿の場所は知らないんだよね？」
line = "「チナちゃんは神殿の場所は知らないんだよね？」"

[[dialogue]]
speaker = "チナ"
# 「うん。アタシがアルタイルに来ている間に、２人は天界に行ってたから……」
line = "「うん。アタシがアルタイルに来ている間に、２人は天界に行ってたから……」"

[[dialogue]]
speaker = "ベアトリス"
# 「そうだよね。ありがとう、チナちゃん。話しづらいことまで話してくれて」
line = "「そうだよね。ありがとう、チナちゃん。話しづらいことまで話してくれて」"

[[dialogue]]
speaker = "ベアトリス"
# 「本当はもっと話したいけど……ごめん！　行ってくる！」
line = "「本当はもっと話したいけど……ごめん！　行ってくる！」"

[[dialogue]]
speaker = "チナ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# 会議室を急いで出ていくベアトリスを、チナは唇を噛みながら見送った。
line = "会議室を急いで出ていくベアトリスを、チナは唇を噛みながら見送った。"
