[[dialogue]]
speaker = "unk"
# 第２話,知られざる秘密,B
line = "第２話,知られざる秘密,B"

[[dialogue]]
speaker = "セイファート"
# 「──緋宮会長、星見会長」
line = "「──緋宮会長、星見会長」"

[[dialogue]]
speaker = "クロト"
# 「──はい」
line = "「──はい」"

[[dialogue]]
speaker = "セイファート"
# 「君たちが現地で得た情報の中で──まだ、共有できていないことはないか？」
line = "「君たちが現地で得た情報の中で──まだ、共有できていないことはないか？」"

[[dialogue]]
speaker = "フィオナ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "アポロ？"
# 「違う──違う違う違う！　あたしは……あたしはアポロだ、フィオナなんかじゃない！」
line = "「違う──違う違う違う！　あたしは……あたしはアポロだ、フィオナなんかじゃない！」"

[[dialogue]]
speaker = "エリシア"
# 「いいえ姉さん。あなたはフィオナ。星見家の長女として生まれ、魔王となる宿命を背負った人間です」
line = "「いいえ姉さん。あなたはフィオナ。星見家の長女として生まれ、魔王となる宿命を背負った人間です」"

[[dialogue]]
speaker = "エリシア"
# 「それとも──妹の顔も忘れてしまいましたか？　私ばかりが成長してしまったから」
line = "「それとも──妹の顔も忘れてしまいましたか？　私ばかりが成長してしまったから」"

[[dialogue]]
speaker = "アポロ？"
# 「っ……黙れ！　オマエなんか知らない──勝手に妹ヅラするな！」
line = "「っ……黙れ！　オマエなんか知らない──勝手に妹ヅラするな！」"

[[dialogue]]
speaker = "アポロ？"
# 「あたしは──あたしの名前は、アポロなんだ──！！」
line = "「あたしは──あたしの名前は、アポロなんだ──！！」"

[[dialogue]]
speaker = "クロト"
# （……）
line = "（……）"

[[dialogue]]
speaker = "unk"
# 共有できていないこと──無論ある。
line = "共有できていないこと──無論ある。"

[[dialogue]]
speaker = "unk"
# そして俺たちのトップ、かつ俺にとって憧れの彼がより詳細な情報を求めている。
line = "そして俺たちのトップ、かつ俺にとって憧れの彼がより詳細な情報を求めている。"

[[dialogue]]
speaker = "unk"
# なら……
line = "なら……"

[[dialogue]]
speaker = "クロト"
# 「……ありました」
line = "「……ありました」"

[[dialogue]]
speaker = "フィオナ"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "セイファート"
# 「ほう。聞かせてもらおう、緋宮会長」
line = "「ほう。聞かせてもらおう、緋宮会長」"

[[dialogue]]
speaker = "unk"
# セイファート学園長は身を乗り出し、まっすぐに俺の目を捉えた。
line = "セイファート学園長は身を乗り出し、まっすぐに俺の目を捉えた。"

[[dialogue]]
speaker = "クロト"
# 「はい。最後に『仮面の少女』を<ruby=さら>拐</ruby>っていった──謎の『手』のことです」
line = "「はい。最後に『仮面の少女』を<ruby>拐<rt>さら</rt></ruby>っていった──謎の『手』のことです」"

[[dialogue]]
speaker = "セイファート"
# 「……ふむ。手、とな」
line = "「……ふむ。手、とな」"

[[dialogue]]
speaker = "クロト"
# 「ええ。それと、最後に僕らの前に現れ、基地までも招待された『ネビュラ』について」
line = "「ええ。それと、最後に僕らの前に現れ、基地までも招待された『ネビュラ』について」"

[[dialogue]]
speaker = "エスメラルダ"
# 「！　ネビュラ──なるほど。名前程度は聞き及んでおりましたが」
line = "「！　ネビュラ──なるほど。名前程度は聞き及んでおりましたが」"

[[dialogue]]
speaker = "unk"
# 俺は最終的な事の顛末と、ここに来るまで『ネビュラ』の基地に寄っていて遅れたことを伝えた。
line = "俺は最終的な事の顛末と、ここに来るまで『ネビュラ』の基地に寄っていて遅れたことを伝えた。"

[[dialogue]]
speaker = "unk"
# フィオナとアポロにまつわるやり取りについては巧妙に隠して……。
line = "フィオナとアポロにまつわるやり取りについては巧妙に隠して……。"

[[dialogue]]
speaker = "アニュラス"
# 「！　ひ、緋宮クロト！　おまえは！」
line = "「！　ひ、緋宮クロト！　おまえは！」"

[[dialogue]]
speaker = "アニュラス"
# 「会長ともあろう者が──臨時招集の呼び出しを無視して、そんなよそ者の組織にノコノコついていったというのか！」
line = "「会長ともあろう者が──臨時招集の呼び出しを無視して、そんなよそ者の組織にノコノコついていったというのか！」"

[[dialogue]]
speaker = "クロト"
# 「それは……」
line = "「それは……」"

[[dialogue]]
speaker = "セイファート"
# 「アニュラス。彼の行動は咎めるべきものではない」
line = "「アニュラス。彼の行動は咎めるべきものではない」"

[[dialogue]]
speaker = "セイファート"
# 「我々以外の第三者組織。その懐に入って帰還してくれたのだから、勇敢かつ有益な行動と言えよう」
line = "「我々以外の第三者組織。その懐に入って帰還してくれたのだから、勇敢かつ有益な行動と言えよう」"

[[dialogue]]
speaker = "アニュラス"
# 「はっ──はい……失礼しました、お父様」
line = "「はっ──はい……失礼しました、お父様」"

[[dialogue]]
speaker = "クロト"
# （はは……）
line = "（はは……）"

[[dialogue]]
speaker = "unk"
# セイファート学園長の娘──アニュラスもこの場に同席していた。
line = "セイファート学園長の娘──アニュラスもこの場に同席していた。"

[[dialogue]]
speaker = "unk"
# どうやら書記として抜擢されているみたいだが……ノリは相変わらずのようだ。
line = "どうやら書記として抜擢されているみたいだが……ノリは相変わらずのようだ。"

[[dialogue]]
speaker = "セイファート"
# 「それ以外で共有すべき事項は？」
line = "「それ以外で共有すべき事項は？」"

[[dialogue]]
speaker = "クロト"
# 「ありません。星徒会内でも、まだあまり事態が整理できておらず」
line = "「ありません。星徒会内でも、まだあまり事態が整理できておらず」"

[[dialogue]]
speaker = "セイファート"
# 「うむ。貴重な情報感謝する、緋宮会長」
line = "「うむ。貴重な情報感謝する、緋宮会長」"

[[dialogue]]
speaker = "unk"
# 俺はセイファート学園長に促されるや、軽く一礼してからゆっくりと席に座った。
line = "俺はセイファート学園長に促されるや、軽く一礼してからゆっくりと席に座った。"

[[dialogue]]
speaker = "フィオナ"
# （緋宮会長……）
line = "（緋宮会長……）"

[[dialogue]]
speaker = "クロト"
# （何か？）
line = "（何か？）"

[[dialogue]]
speaker = "フィオナ"
# （……いえ。ありがとうございます）
line = "（……いえ。ありがとうございます）"

[[dialogue]]
speaker = "unk"
# フィオナ──と俺たちが呼んでいる彼女──とアポロの関係についてはまだ不明瞭な点も多い。
line = "フィオナ──と俺たちが呼んでいる彼女──とアポロの関係についてはまだ不明瞭な点も多い。"

[[dialogue]]
speaker = "unk"
# 彼女本人がフィオナを名乗り続ける限り……俺もそれに合わせようと思った。
line = "彼女本人がフィオナを名乗り続ける限り……俺もそれに合わせようと思った。"

[[dialogue]]
speaker = "アニュラス"
# （我らが星見会長ともあんな親しげに……！　やはり要注意人物に変わりありませんね、緋宮クロト……！）
line = "（我らが星見会長ともあんな親しげに……！　やはり要注意人物に変わりありませんね、緋宮クロト……！）"

[[dialogue]]
speaker = "フィオナ"
# （……彼女と、何かあったのでしょうか？）
line = "（……彼女と、何かあったのでしょうか？）"

[[dialogue]]
speaker = "クロト"
# （はは……まあ、少しね）
line = "（はは……まあ、少しね）"

[[dialogue]]
speaker = "unk"
# ますます睨みを利かされてしまっていた。
line = "ますます睨みを利かされてしまっていた。"

[[dialogue]]
speaker = "unk"
# アニュラスは流星学園の一年生──フィオナには馴染みのある後輩なのかもしれない。
line = "アニュラスは流星学園の一年生──フィオナには馴染みのある後輩なのかもしれない。"

[[dialogue]]
speaker = "セイファート"
# 「今、世界は明らかな転換期を迎えている──これらの危機を乗り越えることこそ、我ら<ruby=スターナイト>星騎士</ruby>の真の役目と言えよう」
line = "「今、世界は明らかな転換期を迎えている──これらの危機を乗り越えることこそ、我ら<ruby>星騎士<rt>スターナイト</rt></ruby>の真の役目と言えよう」"

[[dialogue]]
speaker = "unk"
# その後、俺たちの持ち帰った情報を元に今後の方針などが話し合われ……
line = "その後、俺たちの持ち帰った情報を元に今後の方針などが話し合われ……"

[[dialogue]]
speaker = "unk"
# 次に同じようなアクシデントが発生した時のため、様々な対策が練られることになった。
line = "次に同じようなアクシデントが発生した時のため、様々な対策が練られることになった。"
