[[dialogue]]
speaker = "unk"
# 第８話,この身は全てを穿つ針,B
line = "第８話,この身は全てを穿つ針,B"

[[dialogue]]
speaker = "蘭美"
# 「都内各地域にてモンスターが大量発生中。混乱が広がっており、一般人の避難状況も<ruby=かんば>芳</ruby>しくありません」
line = "「都内各地域にてモンスターが大量発生中。混乱が広がっており、一般人の避難状況も<ruby>芳<rt>かんば</rt></ruby>しくありません」"

[[dialogue]]
speaker = "ヘレナ"
# 「九浄家メイド隊、分散して、各地のモンスター鎮圧に向かえ」
line = "「九浄家メイド隊、分散して、各地のモンスター鎮圧に向かえ」"

[[dialogue]]
speaker = "蘭美"
# 「了解しました。ヨミ、あなたは閃とともに浅草方面へ。せつな、あなたには各所を繋ぐ伝令をお願いするわ」
line = "「了解しました。ヨミ、あなたは閃とともに浅草方面へ。せつな、あなたには各所を繋ぐ伝令をお願いするわ」"

[[dialogue]]
speaker = "ヨミ"
# 「はいっ！　至急、現場に向かいます！」
line = "「はいっ！　至急、現場に向かいます！」"

[[dialogue]]
speaker = "せつな"
# 「かしこまりでござる！　散っ！」
line = "「かしこまりでござる！　散っ！」"

[[dialogue]]
speaker = "蘭美"
# 「美鶴は私とともに渋谷方面に向かうわよ。いいわね」
line = "「美鶴は私とともに渋谷方面に向かうわよ。いいわね」"

[[dialogue]]
speaker = "美鶴"
# 「しゃーないですね。もうひと頑張りしますよ」
line = "「しゃーないですね。もうひと頑張りしますよ」"

[[dialogue]]
speaker = "蘭美"
# 「邪魔ね！　弾け飛べ！　ダッシュハンマー！」
line = "「邪魔ね！　弾け飛べ！　ダッシュハンマー！」"

[[dialogue]]
speaker = "美鶴"
# 「うわ、着地と同時に吹っ飛ばすとかエグ」
line = "「うわ、着地と同時に吹っ飛ばすとかエグ」"

[[dialogue]]
speaker = "蘭美"
# 「足元にちょうどいいスペースがなかったのよ。ないのなら作るまでだわ」
line = "「足元にちょうどいいスペースがなかったのよ。ないのなら作るまでだわ」"

[[dialogue]]
speaker = "美鶴"
# 「報告通り、足の踏み場もないくらい、モンスターがわんさかですね」
line = "「報告通り、足の踏み場もないくらい、モンスターがわんさかですね」"

[[dialogue]]
speaker = "蘭美"
# 「どんなにいようが、ちんたら時間をかけてられないわ！　光速で終わらせる！　美鶴、全力でついてきなさい！」
line = "「どんなにいようが、ちんたら時間をかけてられないわ！　光速で終わらせる！　美鶴、全力でついてきなさい！」"

[[dialogue]]
speaker = "美鶴"
# 「はいはーい」
line = "「はいはーい」"

[[dialogue]]
speaker = "蘭美"
# 「返事は１回！　てぇりゃあぁぁっ！」
line = "「返事は１回！　てぇりゃあぁぁっ！」"

[[dialogue]]
speaker = "蘭美"
# 「さぁ、私にお片付けされたいヤツは、どこからでもかかってきなさい！　ぺちゃんこのお煎餅にしてやるわ！」
line = "「さぁ、私にお片付けされたいヤツは、どこからでもかかってきなさい！　ぺちゃんこのお煎餅にしてやるわ！」"

[[dialogue]]
speaker = "美鶴"
# 「メイド長、やっぱし強ぉ。うちなんかいなくても、ひとりで全部やれるんじゃん？」
line = "「メイド長、やっぱし強ぉ。うちなんかいなくても、ひとりで全部やれるんじゃん？」"

[[dialogue]]
speaker = "美鶴"
# 「つーわけでさ。メイド長が気持ちよ～く戦ってるとこ、ジャマすんなし」
line = "「つーわけでさ。メイド長が気持ちよ～く戦ってるとこ、ジャマすんなし」"

[[dialogue]]
speaker = "蘭美"
# 「やるじゃない、美鶴」
line = "「やるじゃない、美鶴」"

[[dialogue]]
speaker = "美鶴"
# 「いやいや、うちはメイド長の手の回らないトコをチビチビ刺してるだけですよ」
line = "「いやいや、うちはメイド長の手の回らないトコをチビチビ刺してるだけですよ」"

[[dialogue]]
speaker = "蘭美"
# 「謙遜？　それとも、本当に目立ちたくないだけ？　あなたの働きにもちゃんと気づいてるわよ」
line = "「謙遜？　それとも、本当に目立ちたくないだけ？　あなたの働きにもちゃんと気づいてるわよ」"

[[dialogue]]
speaker = "蘭美"
# 「私が倒し損ねたモンスターにトドメを刺してくれていたでしょう。手負いのモンスターを逃すと、後でまた悪さを始めるものね」
line = "「私が倒し損ねたモンスターにトドメを刺してくれていたでしょう。手負いのモンスターを逃すと、後でまた悪さを始めるものね」"

[[dialogue]]
speaker = "美鶴"
# 「そーですね。美味しいトコだけいただいてましたけど。大暴れしながら細かいトコまでよく見てますね」
line = "「そーですね。美味しいトコだけいただいてましたけど。大暴れしながら細かいトコまでよく見てますね」"

[[dialogue]]
speaker = "蘭美"
# 「部下の仕事を逐一確認するのが、メイド長の仕事よ。褒められるまでもないわ、ふふん」
line = "「部下の仕事を逐一確認するのが、メイド長の仕事よ。褒められるまでもないわ、ふふん」"

[[dialogue]]
speaker = "蘭美"
# 「細やかなサポートは、メイドの大切な心得。やっぱり、あなたは素晴らしいメイドになれる才能の持ち主よ」
line = "「細やかなサポートは、メイドの大切な心得。やっぱり、あなたは素晴らしいメイドになれる才能の持ち主よ」"

[[dialogue]]
speaker = "せつな"
# 「蘭美殿ー！　美鶴殿ー！　大変でござるー！」
line = "「蘭美殿ー！　美鶴殿ー！　大変でござるー！」"

[[dialogue]]
speaker = "美鶴"
# 「せつな？　……あの様子から見て、悪いニュースか、とても悪いニュースのどちらでしょう？」
line = "「せつな？　……あの様子から見て、悪いニュースか、とても悪いニュースのどちらでしょう？」"

[[dialogue]]
speaker = "せつな"
# 「浅草に向かった閃殿、ヨミ殿が大苦戦中！　至急救援を求む、でござるー！」
line = "「浅草に向かった閃殿、ヨミ殿が大苦戦中！　至急救援を求む、でござるー！」"

[[dialogue]]
speaker = "蘭美"
# 「あの２人が押されるなんて、とても悪い方だったようね」
line = "「あの２人が押されるなんて、とても悪い方だったようね」"

[[dialogue]]
speaker = "蘭美"
# 「メイド長、羽宮蘭美。並びに──」
line = "「メイド長、羽宮蘭美。並びに──」"

[[dialogue]]
speaker = "美鶴"
# 「メイド隊、長篠美鶴。浅草に向かう」
line = "「メイド隊、長篠美鶴。浅草に向かう」"

[[dialogue]]
speaker = "閃"
# 「くぅぅ……！　お嬢様にもう一度お会いするまで……やられるわけにはいかないの……！」
line = "「くぅぅ……！　お嬢様にもう一度お会いするまで……やられるわけにはいかないの……！」"

[[dialogue]]
speaker = "ヨミ"
# 「せつなさんが救援要請に向かっています！　もう少し……もう少し持ちこたえれば、きっとみんなが──」
line = "「せつなさんが救援要請に向かっています！　もう少し……もう少し持ちこたえれば、きっとみんなが──」"

[[dialogue]]
speaker = "蘭美"
# 「速攻で駆けつけたわ！」
line = "「速攻で駆けつけたわ！」"

[[dialogue]]
speaker = "美鶴"
# 「お待たせー」
line = "「お待たせー」"

[[dialogue]]
speaker = "ヨミ"
# 「メイド長！　美鶴さんも！」
line = "「メイド長！　美鶴さんも！」"

[[dialogue]]
speaker = "せつな"
# 「ヨミ殿！　閃殿！　間に合ったでござる！」
line = "「ヨミ殿！　閃殿！　間に合ったでござる！」"

[[dialogue]]
speaker = "蘭美"
# 「よく耐えたわね、あなたたち！」
line = "「よく耐えたわね、あなたたち！」"

[[dialogue]]
speaker = "閃"
# 「メイド長！　良かった、助かりました……！」
line = "「メイド長！　良かった、助かりました……！」"

[[dialogue]]
speaker = "蘭美"
# 「気を抜くのはまだ早いわよ。これだけの数となると私たちが加わったところで、殲滅は容易じゃないわ」
line = "「気を抜くのはまだ早いわよ。これだけの数となると私たちが加わったところで、殲滅は容易じゃないわ」"

[[dialogue]]
speaker = "蘭美"
# 「今までで一番ピンチかもしれないわね。いよいよ世界が終わる瀬戸際ってところかしら」
line = "「今までで一番ピンチかもしれないわね。いよいよ世界が終わる瀬戸際ってところかしら」"

[[dialogue]]
speaker = "美鶴"
# 「どこから湧いてきたんだか……ってアステラか。全部片づけんのは骨が折れそうだわ」
line = "「どこから湧いてきたんだか……ってアステラか。全部片づけんのは骨が折れそうだわ」"

[[dialogue]]
speaker = "蘭美"
# 「不可能とは言わないのね」
line = "「不可能とは言わないのね」"

[[dialogue]]
speaker = "美鶴"
# 「これで世界が終わっちゃうんなら、できないなんて言ってらんないでしょ」
line = "「これで世界が終わっちゃうんなら、できないなんて言ってらんないでしょ」"

[[dialogue]]
speaker = "美鶴"
# 「作りかけの服もたくさん溜まってるし、まだまだやり足りないことだらけなんですよ」
line = "「作りかけの服もたくさん溜まってるし、まだまだやり足りないことだらけなんですよ」"

[[dialogue]]
speaker = "蘭美"
# 「ふうん。あなたが死にたがりなダウナー系じゃなくって良かったわ」
line = "「ふうん。あなたが死にたがりなダウナー系じゃなくって良かったわ」"

[[dialogue]]
speaker = "美鶴"
# 「うちのこと、どんな風に思ってたんすか」
line = "「うちのこと、どんな風に思ってたんすか」"

[[dialogue]]
speaker = "蘭美"
# 「だって、美鶴、あまり話してくれないじゃない。この戦いが終わったら、いろいろ教えてよね、あなたのこと」
line = "「だって、美鶴、あまり話してくれないじゃない。この戦いが終わったら、いろいろ教えてよね、あなたのこと」"

[[dialogue]]
speaker = "美鶴"
# 「死亡フラグっぽいの、やめてもらえます？」
line = "「死亡フラグっぽいの、やめてもらえます？」"

[[dialogue]]
speaker = "せつな"
# 「一斉に押し寄せてきたでござる！」
line = "「一斉に押し寄せてきたでござる！」"

[[dialogue]]
speaker = "蘭美"
# 「さ、ここが正念場よ！　メイド隊、迎撃態勢！」
line = "「さ、ここが正念場よ！　メイド隊、迎撃態勢！」"

[[dialogue]]
speaker = "美鶴"
# （ま、ここが一番の山場っていうなら──）
line = "（ま、ここが一番の山場っていうなら──）"

[[dialogue]]
speaker = "美鶴"
# 「メイド長のいう本気っての、ちょこっと出してみますか」
line = "「メイド長のいう本気っての、ちょこっと出してみますか」"

[[dialogue]]
speaker = "蘭美"
# 「美鶴、そっちは任せていいのね？」
line = "「美鶴、そっちは任せていいのね？」"

[[dialogue]]
speaker = "美鶴"
# 「やれるだけやりますけど、期待しないでくださいね。ぶっ倒れちゃったら、ごめん」
line = "「やれるだけやりますけど、期待しないでくださいね。ぶっ倒れちゃったら、ごめん」"

[[dialogue]]
speaker = "蘭美"
# 「ダメよ、許してあげない。骨だって拾ってあげないわ」
line = "「ダメよ、許してあげない。骨だって拾ってあげないわ」"

[[dialogue]]
speaker = "美鶴"
# 「厳しいっすね」
line = "「厳しいっすね」"

[[dialogue]]
speaker = "蘭美"
# 「だから──絶対に生き残りなさい。これはメイド長命令よ」
line = "「だから──絶対に生き残りなさい。これはメイド長命令よ」"

[[dialogue]]
speaker = "美鶴"
# 「りょ、です」
line = "「りょ、です」"

[[dialogue]]
speaker = "美鶴"
# 「長篠美鶴、参る！」
line = "「長篠美鶴、参る！」"

[[dialogue]]
speaker = "ヨミ"
# 「単騎特攻！？　美鶴さん、そんなの自殺行為ですよ！」
line = "「単騎特攻！？　美鶴さん、そんなの自殺行為ですよ！」"

[[dialogue]]
speaker = "蘭美"
# 「あの子なら大丈夫でしょ。ヨミ、人を案じる余裕があるなら、自分の身を最優先にしなさい」
line = "「あの子なら大丈夫でしょ。ヨミ、人を案じる余裕があるなら、自分の身を最優先にしなさい」"

[[dialogue]]
speaker = "蘭美"
# 「光になりなさい、ゴルディオンスマッシャー！　これで……１００！」
line = "「光になりなさい、ゴルディオンスマッシャー！　これで……１００！」"

[[dialogue]]
speaker = "せつな"
# 「はーっ、はーっ、はーっ……！　もう何時間戦ってるでござるか……！？」
line = "「はーっ、はーっ、はーっ……！　もう何時間戦ってるでござるか……！？」"

[[dialogue]]
speaker = "閃"
# 「そんなには経ってませんよ、せいぜい３０分くらいだと思いますけど……時間の感覚もなくなりますよね……！」
line = "「そんなには経ってませんよ、せいぜい３０分くらいだと思いますけど……時間の感覚もなくなりますよね……！」"

[[dialogue]]
speaker = "ヨミ"
# 「倒しても倒しても減ってる気がしないです……倒しましたよね？　蘇ってるわけじゃないですよねー？」
line = "「倒しても倒しても減ってる気がしないです……倒しましたよね？　蘇ってるわけじゃないですよねー？」"

[[dialogue]]
speaker = "蘭美"
# 「ちゃんと倒してるし、モンスターの数は減ってるわ。安心しなさい。ただちょっとだけ、その数が膨大ってだけよ」
line = "「ちゃんと倒してるし、モンスターの数は減ってるわ。安心しなさい。ただちょっとだけ、その数が膨大ってだけよ」"

[[dialogue]]
speaker = "せつな"
# 「嘆いたところで何も始まらぬでござるな。泣き言はなしでござる。それに──」
line = "「嘆いたところで何も始まらぬでござるな。泣き言はなしでござる。それに──」"

[[dialogue]]
speaker = "ヨミ"
# 「あっちで戦ってる美鶴さんに笑われちゃいますよね」
line = "「あっちで戦ってる美鶴さんに笑われちゃいますよね」"

[[dialogue]]
speaker = "美鶴"
# 「ふっ」
line = "「ふっ」"

[[dialogue]]
speaker = "美鶴"
# （突き出した槍は、目の前のモンスターを貫く）
line = "（突き出した槍は、目の前のモンスターを貫く）"

[[dialogue]]
speaker = "美鶴"
# （これで何匹目？　５０くらいまでは覚えてるけど、数えたトコで何の意味もないことに気づいて途中でやめた）
line = "（これで何匹目？　５０くらいまでは覚えてるけど、数えたトコで何の意味もないことに気づいて途中でやめた）"

[[dialogue]]
speaker = "美鶴"
# （メイド長には本気の出し方が分からないといったけど、うちには『本気』という感覚がない）
line = "（メイド長には本気の出し方が分からないといったけど、うちには『本気』という感覚がない）"

[[dialogue]]
speaker = "美鶴"
# （うちが何かをやる時は、いつだって本気。本気を、最小の労力でやり、最高のコスパを叩き出す）
line = "（うちが何かをやる時は、いつだって本気。本気を、最小の労力でやり、最高のコスパを叩き出す）"

[[dialogue]]
speaker = "美鶴"
# （本気を出さそうが、出さなかろうが。敵が多かろうが、少なかろうが）
line = "（本気を出さそうが、出さなかろうが。敵が多かろうが、少なかろうが）"

[[dialogue]]
speaker = "美鶴"
# （うちのやることは何も変わらない）
line = "（うちのやることは何も変わらない）"

[[dialogue]]
speaker = "美鶴"
# （うちは、針。万物を貫く１本の針。視界に入った対象を、ただ穿つ）
line = "（うちは、針。万物を貫く１本の針。視界に入った対象を、ただ穿つ）"

[[dialogue]]
speaker = "美鶴"
# 「すぅーーー……はぁぁーーー……！」
line = "「すぅーーー……はぁぁーーー……！」"

[[dialogue]]
speaker = "美鶴"
# （敵陣の只中で、意識が研ぎ澄まされていく）
line = "（敵陣の只中で、意識が研ぎ澄まされていく）"

[[dialogue]]
speaker = "美鶴"
# （生地に針を通すように、視界に入った敵に、槍を突き出す）
line = "（生地に針を通すように、視界に入った敵に、槍を突き出す）"

[[dialogue]]
speaker = "美鶴"
# （生地の針を通しやすい穴が感覚的に分かるのと同様に、モンスターの体のどこに穂先が通るのかが分かる）
line = "（生地の針を通しやすい穴が感覚的に分かるのと同様に、モンスターの体のどこに穂先が通るのかが分かる）"

[[dialogue]]
speaker = "美鶴"
# （硬い表皮であっても、分厚い体毛に覆われていても、隙間を縫って、弱点へと届く）
line = "（硬い表皮であっても、分厚い体毛に覆われていても、隙間を縫って、弱点へと届く）"

[[dialogue]]
speaker = "美鶴"
# （うちのポリシーである最低最小限度の労力で、敵の弱点を的確に貫き、穿つ）
line = "（うちのポリシーである最低最小限度の労力で、敵の弱点を的確に貫き、穿つ）"

[[dialogue]]
speaker = "美鶴"
# 「しぃーーー……ふぅぅーーー……！」
line = "「しぃーーー……ふぅぅーーー……！」"

[[dialogue]]
speaker = "美鶴"
# （何の雑音も届かない。うち自身の呼吸と心臓の鼓動しか聞こえない）
line = "（何の雑音も届かない。うち自身の呼吸と心臓の鼓動しか聞こえない）"

[[dialogue]]
speaker = "美鶴"
# （うちの身体が、うちのじゃないみたいだ。羽だけじゃなくて全身が羽毛になって、重力から解き放たれたみたいに体が軽い）
line = "（うちの身体が、うちのじゃないみたいだ。羽だけじゃなくて全身が羽毛になって、重力から解き放たれたみたいに体が軽い）"

[[dialogue]]
speaker = "美鶴"
# （これなら、いつまでも──戦える）
line = "（これなら、いつまでも──戦える）"

[[dialogue]]
speaker = "せつな"
# 「ひぇぇ……美鶴殿、あんなに強かったでござるか」
line = "「ひぇぇ……美鶴殿、あんなに強かったでござるか」"

[[dialogue]]
speaker = "閃"
# 「あちら側を抑えてくれているおかげで、かなり楽に戦えていますけど……」
line = "「あちら側を抑えてくれているおかげで、かなり楽に戦えていますけど……」"

[[dialogue]]
speaker = "閃"
# 「美鶴さんの槍捌き……最前線で戦い続けているのに、ますます研ぎ澄まされているような……」
line = "「美鶴さんの槍捌き……最前線で戦い続けているのに、ますます研ぎ澄まされているような……」"

[[dialogue]]
speaker = "蘭美"
# 「いわゆる『ゾーン』に入ってるんでしょうね。今のあの子には、私たちの声も届かないと思うわ」
line = "「いわゆる『ゾーン』に入ってるんでしょうね。今のあの子には、私たちの声も届かないと思うわ」"

[[dialogue]]
speaker = "ヨミ"
# 「今の美鶴さんに近づいたら、モンスター諸共、貫かれちゃいそうですね……」
line = "「今の美鶴さんに近づいたら、モンスター諸共、貫かれちゃいそうですね……」"

[[dialogue]]
speaker = "蘭美"
# 「見惚れてしまうのもわかるけど、自分たちの仕事をしなさい。美鶴に負けてられないわよ」
line = "「見惚れてしまうのもわかるけど、自分たちの仕事をしなさい。美鶴に負けてられないわよ」"

[[dialogue]]
speaker = "３人"
# 「はいっ！」
line = "「はいっ！」"
