[[dialogue]]
speaker = "unk"
# 第７話,雷電,B
line = "第７話,雷電,B"

[[dialogue]]
speaker = "unk"
# 流星学園正門──
line = "流星学園正門──"

[[dialogue]]
speaker = "unk"
# モンスターの姿を見て降り立ったマトイとセーラは、上空から発見したモンスターの姿を改めて捜索していた。
line = "モンスターの姿を見て降り立ったマトイとセーラは、上空から発見したモンスターの姿を改めて捜索していた。"

[[dialogue]]
speaker = "セーラ"
# 「んじゃーよろしくね、マトイちゃん♪」
line = "「んじゃーよろしくね、マトイちゃん♪」"

[[dialogue]]
speaker = "マトイ"
# 「は……はいセーラ先輩！　足手まといにならないように頑張り奉り候でして……」
line = "「は……はいセーラ先輩！　足手まといにならないように頑張り奉り候でして……」"

[[dialogue]]
speaker = "セーラ"
# 「まーまー、そう固くならずに。うちこんなんだしさ、もっとリラックスしてこ？」
line = "「まーまー、そう固くならずに。うちこんなんだしさ、もっとリラックスしてこ？」"

[[dialogue]]
speaker = "マトイ"
# 「は、はい。すーっ、はーっ……」
line = "「は、はい。すーっ、はーっ……」"

[[dialogue]]
speaker = "セーラ"
# 「イヤイヤ、深呼吸するほどの相手でもないっしょ」
line = "「イヤイヤ、深呼吸するほどの相手でもないっしょ」"

[[dialogue]]
speaker = "unk"
# 気楽さを促すセーラに対し、マトイは慣れない緊張に苛まれていた。
line = "気楽さを促すセーラに対し、マトイは慣れない緊張に苛まれていた。"

[[dialogue]]
speaker = "マトイ"
# （セーラ先輩かー……近くで見ると綺麗だな……私なんかよりずっと……）
line = "（セーラ先輩かー……近くで見ると綺麗だな……私なんかよりずっと……）"

[[dialogue]]
speaker = "セーラ"
# 「マトイちゃん？　あれ、なんか凹んでる感じ……？」
line = "「マトイちゃん？　あれ、なんか凹んでる感じ……？」"

[[dialogue]]
speaker = "マトイ"
# 「いえ……これは単なる持病と申しますか……」
line = "「いえ……これは単なる持病と申しますか……」"

[[dialogue]]
speaker = "unk"
# 彼女お得意のネガティブが発動しかける。
line = "彼女お得意のネガティブが発動しかける。"

[[dialogue]]
speaker = "unk"
# 自称も他称もめんどくさい女マトイであったが、今日はその真価が発揮するよりも……
line = "自称も他称もめんどくさい女マトイであったが、今日はその真価が発揮するよりも……"

[[dialogue]]
speaker = "モンスター"
# 「キェルルルッ！」
line = "「キェルルルッ！」"

[[dialogue]]
speaker = "マトイ"
# 「あっ──向こうから！」
line = "「あっ──向こうから！」"

[[dialogue]]
speaker = "unk"
# 林に隠れていた特殊個体のモンスターが獲物を狩りに姿を現す。
line = "林に隠れていた特殊個体のモンスターが獲物を狩りに姿を現す。"

[[dialogue]]
speaker = "unk"
# それは、セーラの背後から彼女たちを強襲する──も。
line = "それは、セーラの背後から彼女たちを強襲する──も。"

[[dialogue]]
speaker = "モンスター"
# 「──キェェェェェッ！？」
line = "「──キェェェェェッ！？」"

[[dialogue]]
speaker = "マトイ"
# 「！？」
line = "「！？」"

[[dialogue]]
speaker = "セーラ"
# 「も～。せっかく可愛い後輩ちゃんと話してる最中なのに」
line = "「も～。せっかく可愛い後輩ちゃんと話してる最中なのに」"

[[dialogue]]
speaker = "unk"
# ２人の喉元を狙った鷲型のモンスターは、そのクチバシを活かすまでもなくセーラの雷撃銃により撃墜された。
line = "２人の喉元を狙った鷲型のモンスターは、そのクチバシを活かすまでもなくセーラの雷撃銃により撃墜された。"

[[dialogue]]
speaker = "マトイ"
# （今の銃……いつの間に……！？）
line = "（今の銃……いつの間に……！？）"

[[dialogue]]
speaker = "セーラ"
# 「前もこんなん出てきた感じ？」
line = "「前もこんなん出てきた感じ？」"

[[dialogue]]
speaker = "マトイ"
# 「は、はい！　今のと同じやつ──この前のおかしな夜の時に見ました！」
line = "「は、はい！　今のと同じやつ──この前のおかしな夜の時に見ました！」"

[[dialogue]]
speaker = "セーラ"
# 「なるほど～。わざわざうちらに向かってきたのは、星力の強いところに惹かれて集まる習性でもあるのかな……？」
line = "「なるほど～。わざわざうちらに向かってきたのは、星力の強いところに惹かれて集まる習性でもあるのかな……？」"

[[dialogue]]
speaker = "セーラ"
# 「あと、ん～。<ruby=アステラ>巣</ruby>がないからかな？　なんとなくさまよってるカンジ……勘だけど」
line = "「あと、ん～。<ruby>巣<rt>アステラ</rt></ruby>がないからかな？　なんとなくさまよってるカンジ……勘だけど」"

[[dialogue]]
speaker = "unk"
# 勘と言いつつも的確な分析に、マトイは憧れと頼もしさを感じた。
line = "勘と言いつつも的確な分析に、マトイは憧れと頼もしさを感じた。"

[[dialogue]]
speaker = "マトイ"
# 「私も──私も、腐っても新星の星徒会ですから。目一杯セーラ先輩をサポートします！」
line = "「私も──私も、腐っても新星の星徒会ですから。目一杯セーラ先輩をサポートします！」"

[[dialogue]]
speaker = "セーラ"
# 「あはは、その調子。同じ雷だしね──けっこういい練習になるんじゃない？」
line = "「あはは、その調子。同じ雷だしね──けっこういい練習になるんじゃない？」"

[[dialogue]]
speaker = "unk"
# マトイのロングソードに電流が宿り、足先までが雷速の加護を得る。
line = "マトイのロングソードに電流が宿り、足先までが雷速の加護を得る。"

[[dialogue]]
speaker = "unk"
# 対してセーラの銃口にも迸るほどの星力が宿り、二人の戦闘態勢は整った。
line = "対してセーラの銃口にも迸るほどの星力が宿り、二人の戦闘態勢は整った。"

[[dialogue]]
speaker = "モンスター"
# 「キェルルルッ！」
line = "「キェルルルッ！」"

[[dialogue]]
speaker = "unk"
# そんな準備万端の彼女らの前に──数匹のモンスターが現れる。
line = "そんな準備万端の彼女らの前に──数匹のモンスターが現れる。"

[[dialogue]]
speaker = "セーラ"
# 「──んじゃ、軽くひねっちゃおっか」
line = "「──んじゃ、軽くひねっちゃおっか」"

[[dialogue]]
speaker = "マトイ"
# 「了解ですっ！」
line = "「了解ですっ！」"
