[[dialogue]]
speaker = "unk"
# 第１３話,可能性の収束,B
line = "第１３話,可能性の収束,B"

[[dialogue]]
speaker = "unk"
# ──効いている。
line = "──効いている。"

[[dialogue]]
speaker = "unk"
# 間違いなく、ディザスターハンドにダメージが蓄積されているのがわかる。
line = "間違いなく、ディザスターハンドにダメージが蓄積されているのがわかる。"

[[dialogue]]
speaker = "unk"
# アルタイルの戦力はとうとう、この厄災の化身と渡り合えるまでに成長していた。
line = "アルタイルの戦力はとうとう、この厄災の化身と渡り合えるまでに成長していた。"

[[dialogue]]
speaker = "煌嶺"
# 「頃合いだ──厄災よ」
line = "「頃合いだ──厄災よ」"

[[dialogue]]
speaker = "煌嶺"
# 「妾のものとなれ──！！」
line = "「妾のものとなれ──！！」"

[[dialogue]]
speaker = "unk"
# 煌嶺の九尾から、以前にも見た火球──機械型モンスターを包み込んだ──が姿を現す。大きさは、あの時と比べるべくもない極大サイズだ。
line = "煌嶺の九尾から、以前にも見た火球──機械型モンスターを包み込んだ──が姿を現す。大きさは、あの時と比べるべくもない極大サイズだ。"

[[dialogue]]
speaker = "unk"
# そのままディザスターハンドを包み込むが……
line = "そのままディザスターハンドを包み込むが……"

[[dialogue]]
speaker = "煌嶺"
# 「ほう、拒むか──」
line = "「ほう、拒むか──」"

[[dialogue]]
speaker = "煌嶺"
# （知性のない、意思を持たぬモンスターならばこれで意のままだが──そうか）
line = "（知性のない、意思を持たぬモンスターならばこれで意のままだが──そうか）"

[[dialogue]]
speaker = "煌嶺"
# 「ククク……貴様──その<ruby=なり>形</ruby>でまだ生きておるのか？　……興味が尽きん！」
line = "「ククク……貴様──その<ruby>形<rt>なり</rt></ruby>でまだ生きておるのか？　……興味が尽きん！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「離れなさい──霊力の鎖をかける！！」
line = "「離れなさい──霊力の鎖をかける！！」"

[[dialogue]]
speaker = "unk"
# ルヴィネの霊力による拘束で、厄災の右腕ははっきりとその動きを鈍らせている。
line = "ルヴィネの霊力による拘束で、厄災の右腕ははっきりとその動きを鈍らせている。"

[[dialogue]]
speaker = "unk"
# だが──
line = "だが──"

[[dialogue]]
speaker = "ルヴィネ"
# 「命令系統は、復活させた……！　でも、くっ……長くは持たない……！」
line = "「命令系統は、復活させた……！　でも、くっ……長くは持たない……！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「こいつは何かを破壊する以外は、激しい抵抗をする……！　その場で大人しくしろというのは、もう難しい……！！」
line = "「こいつは何かを破壊する以外は、激しい抵抗をする……！　その場で大人しくしろというのは、もう難しい……！！」"

[[dialogue]]
speaker = "ベアトリス"
# 「そ、そうだっ……！　転送装置でベガに送るのはどうかな！？」
line = "「そ、そうだっ……！　転送装置でベガに送るのはどうかな！？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「いいえ。それは無意味……平行世界の移動はラクシスの持つ、お父様さえ自由にはできない権能……！」
line = "「いいえ。それは無意味……平行世界の移動はラクシスの持つ、お父様さえ自由にはできない権能……！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「転送装置の力も、ディザスターハンドから抽出したものを利用している……ベガに送っても自身の力ですぐに戻ってくるわ！」
line = "「転送装置の力も、ディザスターハンドから抽出したものを利用している……ベガに送っても自身の力ですぐに戻ってくるわ！」"

[[dialogue]]
speaker = "unk"
# この暴れ狂う怪物を拘束できる空間さえあれば……そんな場所、この地球には……
line = "この暴れ狂う怪物を拘束できる空間さえあれば……そんな場所、この地球には……"

[[dialogue]]
speaker = "unk"
# ──いや！
line = "──いや！"

[[dialogue]]
speaker = "クロト"
# 「ルヴィネ──宇宙だ！　あの天体なら、もしかしたら……！」
line = "「ルヴィネ──宇宙だ！　あの天体なら、もしかしたら……！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「──！　いいアイデアだわ……！」
line = "「──！　いいアイデアだわ……！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「命令するわ、厄災の右腕……！　あなたに目的を与えてあげる──一直線で向かいなさい！！」
line = "「命令するわ、厄災の右腕……！　あなたに目的を与えてあげる──一直線で向かいなさい！！」"

[[dialogue]]
speaker = "unk"
# その天体は、宇宙空間に点在する特異点。
line = "その天体は、宇宙空間に点在する特異点。"

[[dialogue]]
speaker = "unk"
# きわめて高密度で、凄まじい重力を持つ。物質だけでなく光すらも飲み込む漆黒の天体。
line = "きわめて高密度で、凄まじい重力を持つ。物質だけでなく光すらも飲み込む漆黒の天体。"

[[dialogue]]
speaker = "unk"
# コラプサーと言えば俺たちになじみが深い──その名を、ブラックホール。
line = "コラプサーと言えば俺たちになじみが深い──その名を、ブラックホール。"

[[dialogue]]
speaker = "ルヴィネ"
# 「アドミン・オーバーライド──！！！」
line = "「アドミン・オーバーライド──！！！」"

[[dialogue]]
speaker = "unk"
# ルヴィネが強固に命じた、単純で明快な目的指示。
line = "ルヴィネが強固に命じた、単純で明快な目的指示。"

[[dialogue]]
speaker = "unk"
# ディザスターハンドは、その指示を忠実に受け──地球の外へ放逐された。
line = "ディザスターハンドは、その指示を忠実に受け──地球の外へ放逐された。"

[[dialogue]]
speaker = "グレイス"
# 「や、やりました、か……？」
line = "「や、やりました、か……？」"

[[dialogue]]
speaker = "チナ"
# 「……ああ。やった……ルヴィを止められた……死の未来も回避できた……！」
line = "「……ああ。やった……ルヴィを止められた……死の未来も回避できた……！」"

[[dialogue]]
speaker = "ベアトリス"
# 「ルヴィ……！！」
line = "「ルヴィ……！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「みんな……ありがとう。それに……本当にごめんなさい……」
line = "「みんな……ありがとう。それに……本当にごめんなさい……」"

[[dialogue]]
speaker = "レティシア"
# 「もう謝らないで。ルヴィが無事だった。それだけで、十分だわ」
line = "「もう謝らないで。ルヴィが無事だった。それだけで、十分だわ」"

[[dialogue]]
speaker = "クロト"
# 「ああ──俺たちの……勝ちだ！！」
line = "「ああ──俺たちの……勝ちだ！！」"

[[dialogue]]
speaker = "梨緒"
# 「空が……！！　元に、戻った……」
line = "「空が……！！　元に、戻った……」"

[[dialogue]]
speaker = "unk"
# 地上で獅子奮迅の働きをした梨緒は、アルタイルの勝利を実感していた──
line = "地上で獅子奮迅の働きをした梨緒は、アルタイルの勝利を実感していた──"

[[dialogue]]
speaker = "梨緒"
# 「……ジグが視た未来は回避できたか、ベアト？」
line = "「……ジグが視た未来は回避できたか、ベアト？」"

[[dialogue]]
speaker = "梨緒"
# 「いいや、心配することはないな。ベアトのことだ、きっとうまくやっている」
line = "「いいや、心配することはないな。ベアトのことだ、きっとうまくやっている」"

[[dialogue]]
speaker = "梨緒"
# 「……流石に、今から登るのは無理だな」
line = "「……流石に、今から登るのは無理だな」"

[[dialogue]]
speaker = "unk"
# フィーニスの塔の入口に腰を下ろした梨緒は、空を見上げる。
line = "フィーニスの塔の入口に腰を下ろした梨緒は、空を見上げる。"

[[dialogue]]
speaker = "梨緒"
# 「…………綺麗だ」
line = "「…………綺麗だ」"

[[dialogue]]
speaker = "unk"
# 一面の青空をまた見ることができた。
line = "一面の青空をまた見ることができた。"

[[dialogue]]
speaker = "unk"
# そのことが、何よりも──
line = "そのことが、何よりも──"

[[dialogue]]
speaker = "梨緒"
# 「…………！？」
line = "「…………！？」"

[[dialogue]]
speaker = "梨緒"
# 「お、終わったんじゃないのか……？　なぜ！？」
line = "「お、終わったんじゃないのか……？　なぜ！？」"

[[dialogue]]
speaker = "梨緒"
# 「────誰だッ！？」
line = "「────誰だッ！？」"

[[dialogue]]
speaker = "unk"
# 背後に何者かの気配を察し、梨緒がクロスボウを構える。
line = "背後に何者かの気配を察し、梨緒がクロスボウを構える。"

[[dialogue]]
speaker = "unk"
# 視線の先にいたのは──
line = "視線の先にいたのは──"

[[dialogue]]
speaker = "梨緒"
# 「お前は、一体……！？」
line = "「お前は、一体……！？」"

[[dialogue]]
speaker = "unk"
# ──理解を拒む、１人の敵。
line = "──理解を拒む、１人の敵。"

[[dialogue]]
speaker = "クロト"
# 「終わったな、ルヴィネ」
line = "「終わったな、ルヴィネ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……ええ。でもまだ、お父様の説得が待っている。むしろここからが本番でしょう」
line = "「……ええ。でもまだ、お父様の説得が待っている。むしろここからが本番でしょう」"

[[dialogue]]
speaker = "ルヴィネ"
# 「緋宮クロト。あなたに預けておくわ。この転送装置」
line = "「緋宮クロト。あなたに預けておくわ。この転送装置」"

[[dialogue]]
speaker = "ルヴィネ"
# 「私にはもう必要ない。世界のために、あなたが使ってくれれば──」
line = "「私にはもう必要ない。世界のために、あなたが使ってくれれば──」"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………？」
line = "「…………？」"

[[dialogue]]
speaker = "クロト"
# 「ルヴィネ？　急にどうしたんだ、変身を解くなんて」
line = "「ルヴィネ？　急にどうしたんだ、変身を解くなんて」"

[[dialogue]]
speaker = "ルヴィネ"
# 「いえ……私はそんなこと……していない……」
line = "「いえ……私はそんなこと……していない……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「どうして……？　霊力が突然、なくなった──？」
line = "「どうして……？　霊力が突然、なくなった──？」"

[[dialogue]]
speaker = "？？？"
# 「──返してもらったのよ。不出来な姉には過ぎた力だもの」
line = "「──返してもらったのよ。不出来な姉には過ぎた力だもの」"

[[dialogue]]
speaker = "unk"
# 聞き覚えのある──しかしまるで聞き覚えのない、そんな声が届いた瞬間。
line = "聞き覚えのある──しかしまるで聞き覚えのない、そんな声が届いた瞬間。"

[[dialogue]]
speaker = "ルヴィネ"
# 「────か、はっ……！？」
line = "「────か、はっ……！？」"

[[dialogue]]
speaker = "unk"
# ルヴィネの華奢な身体を──幾本もの光の羽根が貫いた。
line = "ルヴィネの華奢な身体を──幾本もの光の羽根が貫いた。"

[[dialogue]]
speaker = "unk"
# おびただしい量の鮮血が噴きだし──
line = "おびただしい量の鮮血が噴きだし──"

[[dialogue]]
speaker = "unk"
# ルヴィネが──倒れた。
line = "ルヴィネが──倒れた。"

[[dialogue]]
speaker = "レティシア"
# 「……え？」
line = "「……え？」"

[[dialogue]]
speaker = "チナ"
# 「あ……？」
line = "「あ……？」"

[[dialogue]]
speaker = "グレイス"
# 「ルッ──」
line = "「ルッ──」"

[[dialogue]]
speaker = "ベアトリス"
# 「ルヴィ──！？」
line = "「ルヴィ──！？」"

[[dialogue]]
speaker = "unk"
# 血の海で横たわるルヴィネに駆け寄る、極星学園のみんな。
line = "血の海で横たわるルヴィネに駆け寄る、極星学園のみんな。"

[[dialogue]]
speaker = "unk"
# ジグが視た死の未来が、実現──してしまった……？
line = "ジグが視た死の未来が、実現──してしまった……？"

[[dialogue]]
speaker = "unk"
# ──誰だ、こいつは。
line = "──誰だ、こいつは。"

[[dialogue]]
speaker = "？？？"
# 「仲間を守護天使として連れていく──まさか本気にしていただなんてね。お父様がそんなことを許すはずがないでしょう？」
line = "「仲間を守護天使として連れていく──まさか本気にしていただなんてね。お父様がそんなことを許すはずがないでしょう？」"

[[dialogue]]
speaker = "？？？"
# 「貴女はとっくに見限られている。利用できそうだから、今日まで泳がせていたにすぎない」
line = "「貴女はとっくに見限られている。利用できそうだから、今日まで泳がせていたにすぎない」"

[[dialogue]]
speaker = "？？？"
# 「お父様はとても失望しておられたわ。友達と離れたくない……リクリエなんて起こしたくない……何を言っているの？　気持ち悪い」
line = "「お父様はとても失望しておられたわ。友達と離れたくない……リクリエなんて起こしたくない……何を言っているの？　気持ち悪い」"

[[dialogue]]
speaker = "？？？"
# 「本当に無様……生命の維持に必要な臓器は全て潰した。そのまま苦しみもがいて、死になさい」
line = "「本当に無様……生命の維持に必要な臓器は全て潰した。そのまま苦しみもがいて、死になさい」"

[[dialogue]]
speaker = "？？？"
# 「１０年間、お疲れ様……役立たずのルヴィネ。そしてさようなら」
line = "「１０年間、お疲れ様……役立たずのルヴィネ。そしてさようなら」"

[[dialogue]]
speaker = "ルヴィネ"
# 「これからは私──新しいルヴィネが、リクリエを引き継ぐわ」
line = "「これからは私──新しいルヴィネが、リクリエを引き継ぐわ」"
