[[dialogue]]
speaker = "unk"
# 第１話,神への願い事,B
line = "第１話,神への願い事,B"

[[dialogue]]
speaker = "unk"
# 平行世界デネブのフィーニスの塔、その頂上。
line = "平行世界デネブのフィーニスの塔、その頂上。"

[[dialogue]]
speaker = "unk"
# ルヴィネは、自身の頭上に現れた存在に向かって<ruby=こうべ>頭</ruby>を垂れた。
line = "ルヴィネは、自身の頭上に現れた存在に向かって<ruby>頭<rt>こうべ</rt></ruby>を垂れた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「お会いできて光栄です──<b>お父様</b>」
line = "「お会いできて光栄です──<b>お父様</b>」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『────。──、────』
line = "『────。──、────』"

[[dialogue]]
speaker = "unk"
# 『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』は文字どおり、住む次元の違う存在──ゆえに発される『声』は、三次元世界において明確に翻訳することは不可能だ。
line = "『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』は文字どおり、住む次元の違う存在──ゆえに発される『声』は、三次元世界において明確に翻訳することは不可能だ。"

[[dialogue]]
speaker = "unk"
# しかし次世代の女神、その幼体であるルヴィネならば、その意味を<ruby=ひもと>繙</ruby>くことができる。
line = "しかし次世代の女神、その幼体であるルヴィネならば、その意味を<ruby>繙<rt>ひもと</rt></ruby>くことができる。"

[[dialogue]]
speaker = "ルヴィネ"
# 「……報告いたします。先日、２名の部下にアルタイルの天界襲撃を命じました」
line = "「……報告いたします。先日、２名の部下にアルタイルの天界襲撃を命じました」"

[[dialogue]]
speaker = "ルヴィネ"
# 「天界にある神殿を破壊すれば、かの地の天使をすべて消し去ることができ……アルタイルの破滅は秒読みになる予定でした」
line = "「天界にある神殿を破壊すれば、かの地の天使をすべて消し去ることができ……アルタイルの破滅は秒読みになる予定でした」"

[[dialogue]]
speaker = "ルヴィネ"
# 「──しかし３日経った今も、部下たちは戻ってきておりません。おそらく、緋宮クロト率いる星騎士たちに敗北したと思われます」
line = "「──しかし３日経った今も、部下たちは戻ってきておりません。おそらく、緋宮クロト率いる星騎士たちに敗北したと思われます」"

[[dialogue]]
speaker = "ルヴィネ"
# 「転送装置は破壊されたか、<ruby=ろかく>鹵獲</ruby>されたか……申し訳ございません。リクリエの成就の日が遠のきました……私の失態です」
line = "「転送装置は破壊されたか、<ruby>鹵獲<rt>ろかく</rt></ruby>されたか……申し訳ございません。リクリエの成就の日が遠のきました……私の失態です」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『──────、──？』
line = "『──────、──？』"

[[dialogue]]
speaker = "ルヴィネ"
# 「──っ！　そ、それは……」
line = "「──っ！　そ、それは……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「転送装置を暴走させ、自爆しないよう命じたのは……あの２名が……とても、優秀だからです」
line = "「転送装置を暴走させ、自爆しないよう命じたのは……あの２名が……とても、優秀だからです」"

[[dialogue]]
speaker = "ルヴィネ"
# 「天界襲撃が成功したとしても、すぐにアルタイルが消滅するわけではありません」
line = "「天界襲撃が成功したとしても、すぐにアルタイルが消滅するわけではありません」"

[[dialogue]]
speaker = "ルヴィネ"
# 「天使がいなくなった後となれば、残る人間族と魔族の抵抗は激しいものが予想されました。その時のために、戦力を残しておく必要が……」
line = "「天使がいなくなった後となれば、残る人間族と魔族の抵抗は激しいものが予想されました。その時のために、戦力を残しておく必要が……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「それに緋宮クロトたちは一度、転送装置の暴走を防いでいます。失敗した手段を、二度続けるのは得策ではないと、判断しました……」
line = "「それに緋宮クロトたちは一度、転送装置の暴走を防いでいます。失敗した手段を、二度続けるのは得策ではないと、判断しました……」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『──。────』
line = "『──。────』"

[[dialogue]]
speaker = "ルヴィネ"
# 「次は……私が出ます。これまではできる限り手の内を明かさず、緋宮クロトたちの力を削ぐ予定でしたが……計画を変更せざるを得ません」
line = "「次は……私が出ます。これまではできる限り手の内を明かさず、緋宮クロトたちの力を削ぐ予定でしたが……計画を変更せざるを得ません」"

[[dialogue]]
speaker = "ルヴィネ"
# 「新しい転送装置が完成すれば、すぐにアルタイルを滅ぼし、そして──」
line = "「新しい転送装置が完成すれば、すぐにアルタイルを滅ぼし、そして──」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……デネブも。ベガのように滅ぼしてご覧に入れます」
line = "「……デネブも。ベガのように滅ぼしてご覧に入れます」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『……………………』
line = "『……………………』"

[[dialogue]]
speaker = "unk"
# 長い沈黙の果てに、『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』は。
line = "長い沈黙の果てに、『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』は。"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『──────』
line = "『──────』"

[[dialogue]]
speaker = "ルヴィネ"
# 「え……」
line = "「え……」"

[[dialogue]]
speaker = "unk"
# お前には期待している──ルヴィネにそう告げた。
line = "お前には期待している──ルヴィネにそう告げた。"

[[dialogue]]
speaker = "ルヴィネ"
# 「も……もったいないお言葉です、お父様」
line = "「も……もったいないお言葉です、お父様」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『────、──────、────？』
line = "『────、──────、────？』"

[[dialogue]]
speaker = "ルヴィネ"
# （今日のお父様は珍しい……こんなにも喋ってくれること、今までになかった）
line = "（今日のお父様は珍しい……こんなにも喋ってくれること、今までになかった）"

[[dialogue]]
speaker = "ルヴィネ"
# （『必要なものがあれば、何でも願い出ろ』だなんて……）
line = "（『必要なものがあれば、何でも願い出ろ』だなんて……）"

[[dialogue]]
speaker = "unk"
# 今までにも似たような問いかけはあった。そのたびにルヴィネは様々なものを創ってもらった。
line = "今までにも似たような問いかけはあった。そのたびにルヴィネは様々なものを創ってもらった。"

[[dialogue]]
speaker = "unk"
# 極星従騎。霊力による強化を行える特製のセレスティア。そして平行世界を跳躍する転送装置。
line = "極星従騎。霊力による強化を行える特製のセレスティア。そして平行世界を跳躍する転送装置。"

[[dialogue]]
speaker = "unk"
# たくさんのものを<ruby=かし>下賜</ruby>してくれたにも関わらず、さらに願ってよいと父は言う。
line = "たくさんのものを<ruby>下賜<rt>かし</rt></ruby>してくれたにも関わらず、さらに願ってよいと父は言う。"

[[dialogue]]
speaker = "ルヴィネ"
# 「あの……それは、どんなことでもよいのでしょうか？　例えば、モノでなくとも……？」
line = "「あの……それは、どんなことでもよいのでしょうか？　例えば、モノでなくとも……？」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『────』
line = "『────』"

[[dialogue]]
speaker = "ルヴィネ"
# （望むものを、与えてくださる……）
line = "（望むものを、与えてくださる……）"

[[dialogue]]
speaker = "unk"
# ルヴィネは考える。
line = "ルヴィネは考える。"

[[dialogue]]
speaker = "unk"
# 考えて、考えて、考えて──
line = "考えて、考えて、考えて──"

[[dialogue]]
speaker = "ルヴィネ"
# 「それではお父様……お願いがあります」
line = "「それではお父様……お願いがあります」"

[[dialogue]]
speaker = "ルヴィネ"
# 「すべての平行世界を刷新し、私が新たな女神となった暁には……」
line = "「すべての平行世界を刷新し、私が新たな女神となった暁には……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「極星学園星徒会の……あの４人の魂を、次の世界へ連れて行っても、よいでしょうか……？」
line = "「極星学園星徒会の……あの４人の魂を、次の世界へ連れて行っても、よいでしょうか……？」"

[[dialogue]]
speaker = "unk"
# ずっと昔から温めていた、ついぞ口に出せなかった願いを、ルヴィネは口に出した。
line = "ずっと昔から温めていた、ついぞ口に出せなかった願いを、ルヴィネは口に出した。"

[[dialogue]]
speaker = "ルヴィネ"
# 「テルルには、己の手足とも言うべき守護天使がいます。私にも、守護天使を持つ許可を、いただきたく……」
line = "「テルルには、己の手足とも言うべき守護天使がいます。私にも、守護天使を持つ許可を、いただきたく……」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『……………………』
line = "『……………………』"

[[dialogue]]
speaker = "unk"
# 父は何も喋らない。まだ世界の刷新もできていないのに、皮算用が過ぎただろうか。
line = "父は何も喋らない。まだ世界の刷新もできていないのに、皮算用が過ぎただろうか。"

[[dialogue]]
speaker = "unk"
# 沈黙を破ろうとルヴィネが口を開きかけた、その時だった。
line = "沈黙を破ろうとルヴィネが口を開きかけた、その時だった。"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『────』
line = "『────』"

[[dialogue]]
speaker = "ルヴィネ"
# 「あ……ありがとうございます！　お父様……！！」
line = "「あ……ありがとうございます！　お父様……！！」"

[[dialogue]]
speaker = "ルヴィネ"
# （聞き届けて、いただけた……！　でも、私の願いは、それだけではなくて……）
line = "（聞き届けて、いただけた……！　でも、私の願いは、それだけではなくて……）"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『──。────、────』
line = "『──。────、────』"

[[dialogue]]
speaker = "ルヴィネ"
# 「え……あ……」
line = "「え……あ……」"

[[dialogue]]
speaker = "ルヴィネ"
# （他に連れていきたい者があれば、好きなだけ連れていくがよい──？）
line = "（他に連れていきたい者があれば、好きなだけ連れていくがよい──？）"

[[dialogue]]
speaker = "ルヴィネ"
# （流石はお父様……私の考えることなど、お見通しということ？）
line = "（流石はお父様……私の考えることなど、お見通しということ？）"

[[dialogue]]
speaker = "ルヴィネ"
# 「──で、では。転生を望むデネブの住人は、霊体の下級天使として連れて行かせてください」
line = "「──で、では。転生を望むデネブの住人は、霊体の下級天使として連れて行かせてください」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『────』
line = "『────』"

[[dialogue]]
speaker = "ルヴィネ"
# 「はい。必ず……！　次代の女神として。世界の刷新を、お約束いたします……！」
line = "「はい。必ず……！　次代の女神として。世界の刷新を、お約束いたします……！」"

[[dialogue]]
speaker = "unk"
# 世界の終幕は、着実に近づきつつあった──
line = "世界の終幕は、着実に近づきつつあった──"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 『……………………』
line = "『……………………』"
