[[dialogue]]
speaker = "unk"
# 第５話,ステルス番犬,B
line = "第５話,ステルス番犬,B"

[[dialogue]]
speaker = "unk"
# ──そして。
line = "──そして。"

[[dialogue]]
speaker = "マトイ"
# 「えっと……あの基地はこのあたりでいいんだっけ？」
line = "「えっと……あの基地はこのあたりでいいんだっけ？」"

[[dialogue]]
speaker = "アナ"
# 「はい。前回、連行──<b>案内</b>された際に座標を記録しておきました。沿岸部の一角に基地を構えているようです」
line = "「はい。前回、連行──<b>案内</b>された際に座標を記録しておきました。沿岸部の一角に基地を構えているようです」"

[[dialogue]]
speaker = "ソフィア"
# 「こちらから出向くのは初めてですね。ネビュラ……未だ謎多き組織ですが」
line = "「こちらから出向くのは初めてですね。ネビュラ……未だ謎多き組織ですが」"

[[dialogue]]
speaker = "ユウリ"
# 「なるほどな。うちらにない知恵を持ってそうな相手ってワケか」
line = "「なるほどな。うちらにない知恵を持ってそうな相手ってワケか」"

[[dialogue]]
speaker = "クロト"
# 「ああ。今回はその『謎』に賭けてみたいと思ってな」
line = "「ああ。今回はその『謎』に賭けてみたいと思ってな」"

[[dialogue]]
speaker = "unk"
# 俺の勘が正しければ鍵はここにある。
line = "俺の勘が正しければ鍵はここにある。"

[[dialogue]]
speaker = "unk"
# そう信じて、この基地近辺までやってきたのだが……
line = "そう信じて、この基地近辺までやってきたのだが……"

[[dialogue]]
speaker = "？？？"
# 「──何者だ」
line = "「──何者だ」"

[[dialogue]]
speaker = "セーラ"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "マトイ"
# 「いつの間に──！？」
line = "「いつの間に──！？」"

[[dialogue]]
speaker = "unk"
# 無人かと思ったのも束の間、どこからか出現した少女に俺たちは睨まれていた。
line = "無人かと思ったのも束の間、どこからか出現した少女に俺たちは睨まれていた。"

[[dialogue]]
speaker = "？？？"
# 「……侵入者発見。非モンスター」
line = "「……侵入者発見。非モンスター」"

[[dialogue]]
speaker = "クロト"
# 「──待ってくれ。俺たちは新星学園の者だ」
line = "「──待ってくれ。俺たちは新星学園の者だ」"

[[dialogue]]
speaker = "？？？"
# 「人間４体──魔族３体──天使２体──計９体の敵性対象確認。これより迎撃を開始する」
line = "「人間４体──魔族３体──天使２体──計９体の敵性対象確認。これより迎撃を開始する」"

[[dialogue]]
speaker = "サーシャ"
# 「問答無用みたいね──よほど客人が珍しいのかしら？」
line = "「問答無用みたいね──よほど客人が珍しいのかしら？」"

[[dialogue]]
speaker = "クロト"
# 「後ろにも何人か待機しているようです」
line = "「後ろにも何人か待機しているようです」"

[[dialogue]]
speaker = "フィオナ"
# 「話は後で──きますっ！」
line = "「話は後で──きますっ！」"
