[[dialogue]]
speaker = "unk"
# 第２話,星徒会って？,B
line = "第２話,星徒会って？,B"

[[dialogue]]
speaker = "unk"
# 夢を見た。
line = "夢を見た。"

[[dialogue]]
speaker = "unk"
# そこにいるのは５年ほど前の俺……
line = "そこにいるのは５年ほど前の俺……"

[[dialogue]]
speaker = "unk"
# もう何度も見ている夢で、それは俺の心の奥深くに刻まれた記憶でもある。
line = "もう何度も見ている夢で、それは俺の心の奥深くに刻まれた記憶でもある。"

[[dialogue]]
speaker = "飢えたモンスターＡ"
# 「グッグッグッ……ガッガッガッガッ」
line = "「グッグッグッ……ガッガッガッガッ」"

[[dialogue]]
speaker = "飢えたモンスターＢ"
# 「グルル……ゲヘェ」
line = "「グルル……ゲヘェ」"

[[dialogue]]
speaker = "クロト"
# 「う……ぁ……や、めろ……やめてくれ……っ……！」
line = "「う……ぁ……や、めろ……やめてくれ……っ……！」"

[[dialogue]]
speaker = "unk"
# ぼろぼろの俺。餓狼のように群がるモンスター。
line = "ぼろぼろの俺。餓狼のように群がるモンスター。"

[[dialogue]]
speaker = "unk"
# 気力も体力も使い果たし、もう拳の一発も繰り出せない。
line = "気力も体力も使い果たし、もう拳の一発も繰り出せない。"

[[dialogue]]
speaker = "unk"
# そして連れ去られる先は──彼らの巣だった。
line = "そして連れ去られる先は──彼らの巣だった。"

[[dialogue]]
speaker = "unk"
# その最奥に連れ去られた俺は、死を覚悟した。
line = "その最奥に連れ去られた俺は、死を覚悟した。"

[[dialogue]]
speaker = "unk"
# だが次の瞬間、俺を苦しめていたモンスターたちは一刀のもとに斬り伏せられた。
line = "だが次の瞬間、俺を苦しめていたモンスターたちは一刀のもとに斬り伏せられた。"

[[dialogue]]
speaker = "？？？"
# 「──怪我はないか、少年」
line = "「──怪我はないか、少年」"

[[dialogue]]
speaker = "？？？"
# 「強くあれ。世界を取り込まんとする力に、決して飲まれることなきように」
line = "「強くあれ。世界を取り込まんとする力に、決して飲まれることなきように」"

[[dialogue]]
speaker = "？？？"
# 「君の両手には……他者を救う温かさが宿っている」
line = "「君の両手には……他者を救う温かさが宿っている」"

[[dialogue]]
speaker = "unk"
# それが……俺の初めて見た星の輝き。
line = "それが……俺の初めて見た星の輝き。"

[[dialogue]]
speaker = "unk"
# 彼は、訊ねても、名乗ってくれることはなかったけど。
line = "彼は、訊ねても、名乗ってくれることはなかったけど。"

[[dialogue]]
speaker = "unk"
# <ruby=スターナイト>星騎士</ruby>──そんな存在が自分の街にはいるんだと、心に深く刻み込まれた瞬間だった。
line = "<ruby>星騎士<rt>スターナイト</rt></ruby>──そんな存在が自分の街にはいるんだと、心に深く刻み込まれた瞬間だった。"

[[dialogue]]
speaker = "unk"
# そして翌日。
line = "そして翌日。"

[[dialogue]]
speaker = "unk"
# ２つの学園に別れた岐路を右へ曲がって、俺は新星学園への登校２日目を迎える。
line = "２つの学園に別れた岐路を右へ曲がって、俺は新星学園への登校２日目を迎える。"

[[dialogue]]
speaker = "クラスの女子Ａ"
# 「あ！　転入生くんだ──ねえねえ、もう新星には慣れた？」
line = "「あ！　転入生くんだ──ねえねえ、もう新星には慣れた？」"

[[dialogue]]
speaker = "クラスの女子Ｂ"
# 「そんな呼び方じゃ失礼でしょー。ね、クロトくん」
line = "「そんな呼び方じゃ失礼でしょー。ね、クロトくん」"

[[dialogue]]
speaker = "クロト"
# 「大丈夫、気にしないよ。学園は……これから慣れてくところかな」
line = "「大丈夫、気にしないよ。学園は……これから慣れてくところかな」"

[[dialogue]]
speaker = "unk"
# 教室で今日の時間割を確認していると、クラスメイトの女の子から話しかけられた。
line = "教室で今日の時間割を確認していると、クラスメイトの女の子から話しかけられた。"

[[dialogue]]
speaker = "マトイ"
# 「おはよう、緋宮くん。今日は襲われなかった？」
line = "「おはよう、緋宮くん。今日は襲われなかった？」"

[[dialogue]]
speaker = "クロト"
# 「おはよう──マトイ」
line = "「おはよう──マトイ」"

[[dialogue]]
speaker = "unk"
# そして隣の席からは、一足早く登校していたマトイが微笑みかけてきた。
line = "そして隣の席からは、一足早く登校していたマトイが微笑みかけてきた。"

[[dialogue]]
speaker = "クラスの女子Ａ"
# 「襲われたなかった、ってどゆこと？　マトイっち」
line = "「襲われたなかった、ってどゆこと？　マトイっち」"

[[dialogue]]
speaker = "マトイ"
# 「昨日、緋宮くんってば初登校なのに通学路でモンスターに襲われてたの」
line = "「昨日、緋宮くんってば初登校なのに通学路でモンスターに襲われてたの」"

[[dialogue]]
speaker = "クラスの女子Ｂ"
# 「あはは、めっちゃ不運じゃん。さすがに２日も続けてそんな……」
line = "「あはは、めっちゃ不運じゃん。さすがに２日も続けてそんな……」"

[[dialogue]]
speaker = "クロト"
# 「襲われたよ」
line = "「襲われたよ」"

[[dialogue]]
speaker = "クラスの女子Ａ"
# 「ってええぇ……！？」
line = "「ってええぇ……！？」"

[[dialogue]]
speaker = "クロト"
# 「けど、あれも『リクリエ』が近づいてる前兆だと思うと、気を抜いてられないよな」
line = "「けど、あれも『リクリエ』が近づいてる前兆だと思うと、気を抜いてられないよな」"

[[dialogue]]
speaker = "unk"
# リクリエ──世界の破滅──の接近に伴って、今地上では多くの混乱が起きている。
line = "リクリエ──世界の破滅──の接近に伴って、今地上では多くの混乱が起きている。"

[[dialogue]]
speaker = "unk"
# 俺もこの学園の生徒である以上、立ち向かわなくてはいけないだろう。
line = "俺もこの学園の生徒である以上、立ち向かわなくてはいけないだろう。"

[[dialogue]]
speaker = "クロト"
# 「（まあ……俺はそもそも普段からモンスターによく遭遇するから、今に始まった話でもないけど……）」
line = "「（まあ……俺はそもそも普段からモンスターによく遭遇するから、今に始まった話でもないけど……）」"

[[dialogue]]
speaker = "クラスの女子Ｂ"
# 「モンスターに襲われたって……え、それはどうしたの？　助けてもらったの？」
line = "「モンスターに襲われたって……え、それはどうしたの？　助けてもらったの？」"

[[dialogue]]
speaker = "クロト"
# 「……いや？　一人で倒したけど」
line = "「……いや？　一人で倒したけど」"

[[dialogue]]
speaker = "クラスの女子Ａ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "unk"
# 俺がそう言うと、女子３人は引きつった顔を浮かべた。
line = "俺がそう言うと、女子３人は引きつった顔を浮かべた。"

[[dialogue]]
speaker = "クロト"
# 「だって星騎士はモンスターを倒して平和を守るものだろ？　みんなもそうしてるんじゃないのか」
line = "「だって星騎士はモンスターを倒して平和を守るものだろ？　みんなもそうしてるんじゃないのか」"

[[dialogue]]
speaker = "クラスの女子Ａ"
# 「そ、そりゃ～そうだけど！　許可もなしに勝手に出動しちゃダメでしょ！」
line = "「そ、そりゃ～そうだけど！　許可もなしに勝手に出動しちゃダメでしょ！」"

[[dialogue]]
speaker = "クラスの女子Ｂ"
# 「いやでも、クロトくんは自分が襲われたんだから出動ってワケじゃ……」
line = "「いやでも、クロトくんは自分が襲われたんだから出動ってワケじゃ……」"

[[dialogue]]
speaker = "unk"
# どうもあまり良くない話だったらしい。陽気だった２人が慌てている。
line = "どうもあまり良くない話だったらしい。陽気だった２人が慌てている。"

[[dialogue]]
speaker = "クロト"
# 「２人も、街で何かあったら戦うんじゃないのか……？」
line = "「２人も、街で何かあったら戦うんじゃないのか……？」"

[[dialogue]]
speaker = "クラスの女子Ｂ"
# 「戦うかもしんないけど……まずは応援を待つかな」
line = "「戦うかもしんないけど……まずは応援を待つかな」"

[[dialogue]]
speaker = "マトイ"
# 「その……緋宮くん。実はこの学園の星騎士たちもね、誰でも自由に出動できるわけじゃないの」
line = "「その……緋宮くん。実はこの学園の星騎士たちもね、誰でも自由に出動できるわけじゃないの」"

[[dialogue]]
speaker = "クロト"
# 「そうだったのか……！？」
line = "「そうだったのか……！？」"

[[dialogue]]
speaker = "クラスの女子Ａ"
# 「そーそー、出撃するにはプリマステラに選ばれなきゃダメなんだから！」
line = "「そーそー、出撃するにはプリマステラに選ばれなきゃダメなんだから！」"

[[dialogue]]
speaker = "unk"
# ──プリマステラ。
line = "──プリマステラ。"

[[dialogue]]
speaker = "unk"
# 耳慣れない単語に疑問符を浮かべていると、補足が飛んでくる。
line = "耳慣れない単語に疑問符を浮かべていると、補足が飛んでくる。"

[[dialogue]]
speaker = "クラスの女子Ｂ"
# 「一番星って意味でね。新星学園の中でも特に優秀な生徒に与えられる称号なんだ」
line = "「一番星って意味でね。新星学園の中でも特に優秀な生徒に与えられる称号なんだ」"

[[dialogue]]
speaker = "クラスの女子Ｂ"
# 「星騎士としての実力はもちろん、成績とか判断力に優れてないとプリマステラにはなれないんだよ」
line = "「星騎士としての実力はもちろん、成績とか判断力に優れてないとプリマステラにはなれないんだよ」"

[[dialogue]]
speaker = "マトイ"
# 「みんな星力をうまく制御できるわけじゃないから。学園に認められた生徒だけが、星騎士として繰り出せる権利があるの」
line = "「みんな星力をうまく制御できるわけじゃないから。学園に認められた生徒だけが、星騎士として繰り出せる権利があるの」"

[[dialogue]]
speaker = "クロト"
# 「知らなかった。エリートの特権だったんだな」
line = "「知らなかった。エリートの特権だったんだな」"

[[dialogue]]
speaker = "unk"
# 特待生徒──みたいなものだろうか。
line = "特待生徒──みたいなものだろうか。"

[[dialogue]]
speaker = "unk"
# じゃあ、昨日俺を助けに来てくれたマトイや──
line = "じゃあ、昨日俺を助けに来てくれたマトイや──"

[[dialogue]]
speaker = "unk"
# 一緒に馳せ参じてくれた２人は、星騎士としても特別な存在だったんだな。
line = "一緒に馳せ参じてくれた２人は、星騎士としても特別な存在だったんだな。"

[[dialogue]]
speaker = "クロト"
# 「（しかし、そう考えると……民間で勝手にモンスターの相手をしていた俺は……ダメだったのか？）」
line = "「（しかし、そう考えると……民間で勝手にモンスターの相手をしていた俺は……ダメだったのか？）」"

[[dialogue]]
speaker = "unk"
# 狩猟を許可されていないのにクマを撃っちゃったみたいな──そんな感じだろうか。
line = "狩猟を許可されていないのにクマを撃っちゃったみたいな──そんな感じだろうか。"

[[dialogue]]
speaker = "unk"
# いつも襲われて戦っていたことは内緒にしておこう……。
line = "いつも襲われて戦っていたことは内緒にしておこう……。"

[[dialogue]]
speaker = "マトイ"
# 「何事もなかったならいいけど……これからは無理しないで、星騎士の救助を待ってね。すぐに駆けつけられるようになってるから」
line = "「何事もなかったならいいけど……これからは無理しないで、星騎士の救助を待ってね。すぐに駆けつけられるようになってるから」"

[[dialogue]]
speaker = "クロト"
# 「ああ……わかった。そうするよ」
line = "「ああ……わかった。そうするよ」"

[[dialogue]]
speaker = "クロト"
# 「あれ？　そうなると、マトイもプリマステラってやつなのか」
line = "「あれ？　そうなると、マトイもプリマステラってやつなのか」"

[[dialogue]]
speaker = "クラスの女子Ａ"
# 「違うよ！　マトイっちは星徒会役員だもん、プリマステラよりさらに上の役職だよ！」
line = "「違うよ！　マトイっちは星徒会役員だもん、プリマステラよりさらに上の役職だよ！」"

[[dialogue]]
speaker = "unk"
# なるほど。
line = "なるほど。"

[[dialogue]]
speaker = "unk"
# どうやらこの学園では星徒会＞プリマステラ＞一般生徒の順に、星騎士としての優秀さが定められているようだ。
line = "どうやらこの学園では星徒会＞プリマステラ＞一般生徒の順に、星騎士としての優秀さが定められているようだ。"

[[dialogue]]
speaker = "クロト"
# 「へえ……ならやっぱりマトイはすごいんだな。この学園のトップみたいな存在なんだろ」
line = "「へえ……ならやっぱりマトイはすごいんだな。この学園のトップみたいな存在なんだろ」"

[[dialogue]]
speaker = "クラスの女子Ｂ"
# 「そう、そう！　あたしら一般生徒からしたら、手の届かないお人だから！」
line = "「そう、そう！　あたしら一般生徒からしたら、手の届かないお人だから！」"

[[dialogue]]
speaker = "クロト"
# 「昨日、助けに来てくれたマトイの変身姿は確かに格好よかったな」
line = "「昨日、助けに来てくれたマトイの変身姿は確かに格好よかったな」"

[[dialogue]]
speaker = "マトイ"
# 「い、いやあ……私なんてたまたま拾ってもらえただけっていうか。星徒会にはもっとすごい人たちもいるから」
line = "「い、いやあ……私なんてたまたま拾ってもらえただけっていうか。星徒会にはもっとすごい人たちもいるから」"

[[dialogue]]
speaker = "マトイ"
# 「アナなんか……一年生とは思えないくらい仕事もできるし。サーシャ先輩もナイスバディだし。私のキャラなんて……」
line = "「アナなんか……一年生とは思えないくらい仕事もできるし。サーシャ先輩もナイスバディだし。私のキャラなんて……」"

[[dialogue]]
speaker = "クラスの女子Ａ"
# 「マトイっちって、無駄にネガティブだよね」
line = "「マトイっちって、無駄にネガティブだよね」"

[[dialogue]]
speaker = "unk"
# 心からの賛辞だったのに、照れて縮こまってしまうマトイだった。
line = "心からの賛辞だったのに、照れて縮こまってしまうマトイだった。"

[[dialogue]]
speaker = "クロト"
# 「でも、マトイだっていつかは星徒会長になるんじゃないのか？」
line = "「でも、マトイだっていつかは星徒会長になるんじゃないのか？」"

[[dialogue]]
speaker = "マトイ"
# 「まさか。会長はもうヴィーナスがいるし、私はこうして星徒会の一員になれただけでも幸運なんだから……おこがましいよ」
line = "「まさか。会長はもうヴィーナスがいるし、私はこうして星徒会の一員になれただけでも幸運なんだから……おこがましいよ」"

[[dialogue]]
speaker = "unk"
# やんわりと否定するマトイ。
line = "やんわりと否定するマトイ。"

[[dialogue]]
speaker = "unk"
# だが、その左腕に巻かれた腕章には、新参の俺には想像もつかないような苦労があるのだろう。
line = "だが、その左腕に巻かれた腕章には、新参の俺には想像もつかないような苦労があるのだろう。"

[[dialogue]]
speaker = "unk"
# にしても……
line = "にしても……"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナス？」
line = "「ヴィーナス？」"

[[dialogue]]
speaker = "クラスの女子Ａ"
# 「今の星徒会長だよ！　Ｄ組の九浄ヴィーナスさん──緋宮くんもそのうち会うことあるんじゃないかな！」
line = "「今の星徒会長だよ！　Ｄ組の九浄ヴィーナスさん──緋宮くんもそのうち会うことあるんじゃないかな！」"

[[dialogue]]
speaker = "クラスの女子Ｂ"
# 「ま、あたしらみたいなひよっ子からしたら雲の上の存在だけどね～。あたしも早くプリマステラにならないとなっ」
line = "「ま、あたしらみたいなひよっ子からしたら雲の上の存在だけどね～。あたしも早くプリマステラにならないとなっ」"

[[dialogue]]
speaker = "unk"
# クラスメイトの彼女たちは星騎士として、早く一人前になるよう奮起していた。
line = "クラスメイトの彼女たちは星騎士として、早く一人前になるよう奮起していた。"

[[dialogue]]
speaker = "unk"
# <ruby=プリマステラ>一番星</ruby>──リクリエの危機から実際に人々を守る、出撃を許されたエリート星騎士。
line = "<ruby>一番星<rt>プリマステラ</rt></ruby>──リクリエの危機から実際に人々を守る、出撃を許されたエリート星騎士。"

[[dialogue]]
speaker = "unk"
# 俺もこの学園で努力して、認められるよう頑張ろう。
line = "俺もこの学園で努力して、認められるよう頑張ろう。"

[[dialogue]]
speaker = "unk"
# マトイのように星徒会へ入る──っていうのは、転入生だから厳しいかもしれないけど……
line = "マトイのように星徒会へ入る──っていうのは、転入生だから厳しいかもしれないけど……"

[[dialogue]]
speaker = "unk"
# 人々の役に立てるなら、そこを目指すべきだと思った。
line = "人々の役に立てるなら、そこを目指すべきだと思った。"
