[[dialogue]]
speaker = "コハルコ"
# 「星騎士の皆さん、応答願います。緊急事態です！　未確認のアステラが発生しました！」
line = "「星騎士の皆さん、応答願います。緊急事態です！　未確認のアステラが発生しました！」"

[[dialogue]]
speaker = "unk"
# 流星市国、上空。
line = "流星市国、上空。"

[[dialogue]]
speaker = "unk"
# そこには紫色の不気味なアステラが発生していた。
line = "そこには紫色の不気味なアステラが発生していた。"

[[dialogue]]
speaker = "unk"
# 即応できたプリマステラとともに、星徒会長として調査にやってきたのだが……
line = "即応できたプリマステラとともに、星徒会長として調査にやってきたのだが……"

[[dialogue]]
speaker = "イクシリオン"
# 「どうなっているんでしょう、これは……！？　禍々しい雰囲気を感じます！」
line = "「どうなっているんでしょう、これは……！？　禍々しい雰囲気を感じます！」"

[[dialogue]]
speaker = "パルミエ"
# 「むぅ……初めて見るタイプのアステラよね～？」
line = "「むぅ……初めて見るタイプのアステラよね～？」"

[[dialogue]]
speaker = "パルミエ"
# 「う～ん。サボりすぎて私だけ知らない、とかじゃなければいいんだけど～」
line = "「う～ん。サボりすぎて私だけ知らない、とかじゃなければいいんだけど～」"

[[dialogue]]
speaker = "マハムート"
# 「やれやれ。この威圧感を前に、それだけ軽口が叩ければ上等よ」
line = "「やれやれ。この威圧感を前に、それだけ軽口が叩ければ上等よ」"

[[dialogue]]
speaker = "マハムート"
# 「ちょっといいかしら、会長。私もコレは初めて見るけど、あなたはどう？」
line = "「ちょっといいかしら、会長。私もコレは初めて見るけど、あなたはどう？」"

[[dialogue]]
speaker = "unk"
# 初めてです。マム
line = "初めてです。マム"

[[dialogue]]
speaker = "メルエル"
# 「会長くん、どうしよう？　このまま突入してもいいのかな？」
line = "「会長くん、どうしよう？　このまま突入してもいいのかな？」"

[[dialogue]]
speaker = "unk"
# 通常のアステラであれば、これだけのメンバーなら容易に対処できるだろう。しかし、どう見てもこれは普通ではない。
line = "通常のアステラであれば、これだけのメンバーなら容易に対処できるだろう。しかし、どう見てもこれは普通ではない。"

[[dialogue]]
speaker = "unk"
# 星騎士としての経験が、人間の生物としての本能が、警告を発する。
line = "星騎士としての経験が、人間の生物としての本能が、警告を発する。"

[[dialogue]]
speaker = "コハルコ"
# 「トワ先生が到着しました。今、通信に出てもらいます。トワ先生、お願いします」
line = "「トワ先生が到着しました。今、通信に出てもらいます。トワ先生、お願いします」"

[[dialogue]]
speaker = "トワ先生"
# 「はーい！　もしもーし、会長くん、みんな、聞こえる？　まずは現在の状況を教えてくれるかな？」
line = "「はーい！　もしもーし、会長くん、みんな、聞こえる？　まずは現在の状況を教えてくれるかな？」"

[[dialogue]]
speaker = "イクシリオン"
# 「そうですね。現在、モンスターは出現しておらず、奥の様子は伺いしれません。ですが気配からして、今までにない脅威であることは間違いなさそうです」
line = "「そうですね。現在、モンスターは出現しておらず、奥の様子は伺いしれません。ですが気配からして、今までにない脅威であることは間違いなさそうです」"

[[dialogue]]
speaker = "トワ先生"
# 「そっか、なるほど……未知数なことが多いね。脅威度が高いからこそ、ここは一度帰還して、戦力を整えてから……」
line = "「そっか、なるほど……未知数なことが多いね。脅威度が高いからこそ、ここは一度帰還して、戦力を整えてから……」"

[[dialogue]]
speaker = "マハムート"
# 「お言葉ですが、先生。どうやらそう悠長なことも言っていられないようです」
line = "「お言葉ですが、先生。どうやらそう悠長なことも言っていられないようです」"

[[dialogue]]
speaker = "トワ先生"
# 「えっ！？　どういうこと！？」
line = "「えっ！？　どういうこと！？」"

[[dialogue]]
speaker = "マハムート"
# 「この特殊なアステラは、少しずつ肥大化しているようです。このまま大きくなり続けるようであれば、いずれ街に大きな被害が出ます」
line = "「この特殊なアステラは、少しずつ肥大化しているようです。このまま大きくなり続けるようであれば、いずれ街に大きな被害が出ます」"

[[dialogue]]
speaker = "パルミエ"
# 「対処は急を要する、ってことよね？　賛成～。私も二度手間はイヤだもの」
line = "「対処は急を要する、ってことよね？　賛成～。私も二度手間はイヤだもの」"

[[dialogue]]
speaker = "トワ先生"
# 「……みんな同じ意見なんだね。でも、くれぐれも無理はしないで。応援も編成次第、すぐ出撃させるから！」
line = "「……みんな同じ意見なんだね。でも、くれぐれも無理はしないで。応援も編成次第、すぐ出撃させるから！」"

[[dialogue]]
speaker = "イクシリオン"
# 「はい、ありがとうございます！」
line = "「はい、ありがとうございます！」"

[[dialogue]]
speaker = "メルエル"
# 「き、緊張するけど、頑張るよっ！」
line = "「き、緊張するけど、頑張るよっ！」"

[[dialogue]]
speaker = "パルミエ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "パルミエ"
# 「ところで～、ダーリンとメルエルちゃんって、どういう関係なの～？」
line = "「ところで～、ダーリンとメルエルちゃんって、どういう関係なの～？」"

[[dialogue]]
speaker = "メルエル"
# 「ダ、ダダダ、ダーリン！？　会長くんが！？」
line = "「ダ、ダダダ、ダーリン！？　会長くんが！？」"

[[dialogue]]
speaker = "パルミエ"
# 「そうよ～？　ここに殿方はダーリンしかいないでしょ？」
line = "「そうよ～？　ここに殿方はダーリンしかいないでしょ？」"

[[dialogue]]
speaker = "メルエル"
# 「会長くんと私は、その、幼馴染というか……パルミエ先輩こそ、どういうご関係なんですか！？」
line = "「会長くんと私は、その、幼馴染というか……パルミエ先輩こそ、どういうご関係なんですか！？」"

[[dialogue]]
speaker = "パルミエ"
# 「私～？　ダーリンがいれば、隣にはハニーがいるものよ～」
line = "「私～？　ダーリンがいれば、隣にはハニーがいるものよ～」"

[[dialogue]]
speaker = "イクシリオン"
# （これは……修羅場！？　本で読んだシチュエーションでは！？）
line = "（これは……修羅場！？　本で読んだシチュエーションでは！？）"

[[dialogue]]
speaker = "イクシリオン"
# 「お２人とも、争いはいけません！　ここは公平に、会長との体の相性で決着を付けましょう！」
line = "「お２人とも、争いはいけません！　ここは公平に、会長との体の相性で決着を付けましょう！」"

[[dialogue]]
speaker = "メルエル"
# 「……ほぇ？」
line = "「……ほぇ？」"

[[dialogue]]
speaker = "パルミエ"
# 「……は？」
line = "「……は？」"

[[dialogue]]
speaker = "unk"
# 「ああいえ、その！？　今のはいかがわしい意味ではなくてですね！　連携の相性的な話です！！」
line = "「ああいえ、その！？　今のはいかがわしい意味ではなくてですね！　連携の相性的な話です！！」"

[[dialogue]]
speaker = "マハムート"
# 「まったく、そういうのは帰ってからやりなさい。これから戦うのは間違いなく強敵。油断は命取りよ」
line = "「まったく、そういうのは帰ってからやりなさい。これから戦うのは間違いなく強敵。油断は命取りよ」"

[[dialogue]]
speaker = "マハムート"
# 「会長も、あなたが原因なんだから、見てないでなんとかなさい」
line = "「会長も、あなたが原因なんだから、見てないでなんとかなさい」"

[[dialogue]]
speaker = "unk"
# 今どうすればよかったんですか！？
line = "今どうすればよかったんですか！？"

[[dialogue]]
speaker = "マハムート"
# 「さて、<ruby=イルソーレ>流星寮</ruby>の連中が来る前に、新星学園の星騎士の力、見せつけてやるわ。行くわよ！」
line = "「さて、<ruby>流星寮<rt>イルソーレ</rt></ruby>の連中が来る前に、新星学園の星騎士の力、見せつけてやるわ。行くわよ！」"

[[dialogue]]
speaker = "メルエル"
# 「イエス、マム！」
line = "「イエス、マム！」"

[[dialogue]]
speaker = "イクシリオン"
# 「イエス、マム！」
line = "「イエス、マム！」"

[[dialogue]]
speaker = "パルミエ"
# 「は～い。滅多に出さない私の本気、見せてあげるわ～」
line = "「は～い。滅多に出さない私の本気、見せてあげるわ～」"

[[dialogue]]
speaker = "unk"
# そうして俺たちは、臨時の編成を組み立て、未知のアステライトへと突入するのだった。
line = "そうして俺たちは、臨時の編成を組み立て、未知のアステライトへと突入するのだった。"
