[[dialogue]]
speaker = "unk"
# 元旦から数日後。
line = "元旦から数日後。"

[[dialogue]]
speaker = "リーリア"
# 「う～ん、これってどういうことなんだろう……？」
line = "「う～ん、これってどういうことなんだろう……？」"

[[dialogue]]
speaker = "シズハ"
# 「あっ！　リーリア先輩、ごきげんよう♪」
line = "「あっ！　リーリア先輩、ごきげんよう♪」"

[[dialogue]]
speaker = "リーリア"
# 「シズハちゃん！　こんにちマジカル～☆」
line = "「シズハちゃん！　こんにちマジカル～☆」"

[[dialogue]]
speaker = "unk"
# それぞれ学園の寮住まいの２人は、大聖堂カフェテリアで顔を合わせるとすっかり親しげに挨拶を交わす。
line = "それぞれ学園の寮住まいの２人は、大聖堂カフェテリアで顔を合わせるとすっかり親しげに挨拶を交わす。"

[[dialogue]]
speaker = "シズハ"
# 「なんだかずっと、考えるような顔でＤＩＳＣの画面と睨めっこしてましたけど、何かありましたか？」
line = "「なんだかずっと、考えるような顔でＤＩＳＣの画面と睨めっこしてましたけど、何かありましたか？」"

[[dialogue]]
speaker = "リーリア"
# 「うん、実はね～、獅子舞さんから急にＤＩＳＣにメッセージが送られてきたんだけど、なんかちょっと変で……」
line = "「うん、実はね～、獅子舞さんから急にＤＩＳＣにメッセージが送られてきたんだけど、なんかちょっと変で……」"

[[dialogue]]
speaker = "リーリア"
# 「ほら、見て。件名が『魔弾の魔女様へ』で、内容が――」
line = "「ほら、見て。件名が『魔弾の魔女様へ』で、内容が――」"

[[dialogue]]
speaker = "リーリア"
# 「『新年の縁をお祝いしたく、貴方にお会いできたら嬉しく思います。お寺にて改めてお待ちしております。ｂｙ獅子舞』って。なんか妙に違和感あるんだよね～」
line = "「『新年の縁をお祝いしたく、貴方にお会いできたら嬉しく思います。お寺にて改めてお待ちしております。ｂｙ獅子舞』って。なんか妙に違和感あるんだよね～」"

[[dialogue]]
speaker = "シズハ"
# 「獅子舞さんのイメージとは、あまり合わない文面ですね……」
line = "「獅子舞さんのイメージとは、あまり合わない文面ですね……」"

[[dialogue]]
speaker = "リーリア"
# 「しかも、この後に書かれてる指定の時間が、今日なんだよね……う～ん」
line = "「しかも、この後に書かれてる指定の時間が、今日なんだよね……う～ん」"

[[dialogue]]
speaker = "unk"
# 一方、その頃──
line = "一方、その頃──"

[[dialogue]]
speaker = "ヴィーナス"
# 「サーシャさん、アナ～！　あけましておめでとーっ♪」
line = "「サーシャさん、アナ～！　あけましておめでとーっ♪」"

[[dialogue]]
speaker = "マトイ"
# 「今年も普通に過ごせるよう、どうぞよろしくお願いします」
line = "「今年も普通に過ごせるよう、どうぞよろしくお願いします」"

[[dialogue]]
speaker = "unk"
# 俺はヴィーナスやマトイと一緒に、アナとサーシャさんに新年の挨拶をする。
line = "俺はヴィーナスやマトイと一緒に、アナとサーシャさんに新年の挨拶をする。"

[[dialogue]]
speaker = "unk"
# ２人共、あけましておめでとうございます
line = "２人共、あけましておめでとうございます"

[[dialogue]]
speaker = "サーシャ"
# 「みんな～、あけましておめでと～♪　お姉ちゃん、とっても会いたかったわ～」
line = "「みんな～、あけましておめでと～♪　お姉ちゃん、とっても会いたかったわ～」"

[[dialogue]]
speaker = "アナ"
# 「みなさん、今年も星徒会をノープロブレムで頑張っていきましょう」
line = "「みなさん、今年も星徒会をノープロブレムで頑張っていきましょう」"

[[dialogue]]
speaker = "unk"
# 新星学園星徒会のメンバーで集まって、初詣をしようと約束していた日。それが今日だった。
line = "新星学園星徒会のメンバーで集まって、初詣をしようと約束していた日。それが今日だった。"

[[dialogue]]
speaker = "マトイ"
# 「――へぇ～、ＤＩＳＣのメッセージで簡単には聞いてましたけど、元旦にそんなことがあったんですね。獅子舞と羽根突きなんて、普通じゃないっ！」
line = "「――へぇ～、ＤＩＳＣのメッセージで簡単には聞いてましたけど、元旦にそんなことがあったんですね。獅子舞と羽根突きなんて、普通じゃないっ！」"

[[dialogue]]
speaker = "サーシャ"
# 「そうなの～、リーリアちゃんが大活躍でね～。それで私も、先輩としてもっと頑張らなくちゃって、晴れ着フォームを訓練しているの」
line = "「そうなの～、リーリアちゃんが大活躍でね～。それで私も、先輩としてもっと頑張らなくちゃって、晴れ着フォームを訓練しているの」"

[[dialogue]]
speaker = "マトイ"
# 「私は久しぶりに、親戚の神社でトマルと巫女のバイトをしてきました。改めて巫女の仕事をすると、違った景色が見えてくる感じがしますね」
line = "「私は久しぶりに、親戚の神社でトマルと巫女のバイトをしてきました。改めて巫女の仕事をすると、違った景色が見えてくる感じがしますね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私とクロトは星見家と五名門の会合に行ってきたわよ！　今回はクロトが参加したこともあって、前の時よりすごく楽しかったわ♪」
line = "「私とクロトは星見家と五名門の会合に行ってきたわよ！　今回はクロトが参加したこともあって、前の時よりすごく楽しかったわ♪」"

[[dialogue]]
speaker = "アナ"
# 「ほう、それは気になりますね。特に五名門はどんな顔ぶれが揃っていたのか……後でじっくり話を聞かせてください」
line = "「ほう、それは気になりますね。特に五名門はどんな顔ぶれが揃っていたのか……後でじっくり話を聞かせてください」"

[[dialogue]]
speaker = "unk"
# そんな風に、お互いに近況報告をし合っていると。
line = "そんな風に、お互いに近況報告をし合っていると。"

[[dialogue]]
speaker = "？？？"
# 「おや？　おやおや～？　これはこれはこれは！　新年からなんっと、幸先の良い！」
line = "「おや？　おやおや～？　これはこれはこれは！　新年からなんっと、幸先の良い！」"

[[dialogue]]
speaker = "マトイ"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "ダッチ"
# 「まさか、こんなところで再会するとは！　緋宮クロト様、お久しぶりです！」
line = "「まさか、こんなところで再会するとは！　緋宮クロト様、お久しぶりです！」"

[[dialogue]]
speaker = "unk"
# お前は……ダッチ！？
line = "お前は……ダッチ！？"

[[dialogue]]
speaker = "ダッチ"
# 「フフフ！　皆様、あけましておめでとうございます！」
line = "「フフフ！　皆様、あけましておめでとうございます！」"

[[dialogue]]
speaker = "unk"
# 振り向くと、そこに立っていたのは頭にハート型の被り物をしたかのような長身の紳士。俺の記憶の中でも強烈な印象を残す、人型のロストアイテムだった。
line = "振り向くと、そこに立っていたのは頭にハート型の被り物をしたかのような長身の紳士。俺の記憶の中でも強烈な印象を残す、人型のロストアイテムだった。"

[[dialogue]]
speaker = "ヴィーナス"
# 「あなた、誰！？　なんだか変な力を感じるわ！」
line = "「あなた、誰！？　なんだか変な力を感じるわ！」"

[[dialogue]]
speaker = "ダッチ"
# 「新星星徒会の皆様は初めまして。私、『欲望』を司るロストアイテム『ダッチ』と申します。改めて、お見知りおきを！」
line = "「新星星徒会の皆様は初めまして。私、『欲望』を司るロストアイテム『ダッチ』と申します。改めて、お見知りおきを！」"

[[dialogue]]
speaker = "マトイ"
# 「ダッチって確か……前に会長が巻き込まれた、アステラカジノ事件の！？」
line = "「ダッチって確か……前に会長が巻き込まれた、アステラカジノ事件の！？」"

[[dialogue]]
speaker = "アナ"
# 「獅子舞さんと同じ……自我を持ったロストアイテム！」
line = "「獅子舞さんと同じ……自我を持ったロストアイテム！」"

[[dialogue]]
speaker = "サーシャ"
# 「ダッチさんは、一体何が目的でここへ来たのかしら？」
line = "「ダッチさんは、一体何が目的でここへ来たのかしら？」"

[[dialogue]]
speaker = "ダッチ"
# 「ああ、お会いできて光栄です、サーシャ様！　貴方のその抜群のプロポーションは必ずやバニー衣装が似合うと、以前から思っておりました」
line = "「ああ、お会いできて光栄です、サーシャ様！　貴方のその抜群のプロポーションは必ずやバニー衣装が似合うと、以前から思っておりました」"

[[dialogue]]
speaker = "ダッチ"
# 「お近づきの印に、よろしければ試着でもいかがです？　私の力を使えば、余計な手間は一切不要でこのように――」
line = "「お近づきの印に、よろしければ試着でもいかがです？　私の力を使えば、余計な手間は一切不要でこのように――」"

[[dialogue]]
speaker = "unk"
# ダッチが指をパチンと鳴らすと、俺の体が突然光に包まれて。
line = "ダッチが指をパチンと鳴らすと、俺の体が突然光に包まれて。"

[[dialogue]]
speaker = "マトイ"
# 「って、会長が女体化してバニー姿になったーーーっ！？」
line = "「って、会長が女体化してバニー姿になったーーーっ！？」"

[[dialogue]]
speaker = "unk"
# きゃああぁっ～～～～～！？
line = "きゃああぁっ～～～～～！？"

[[dialogue]]
speaker = "ダッチ"
# 「フオオオォ～！　久しぶりに拝見致しましたが、やはり会長様のバニー衣装はこの上なく素晴らしい……！　女体化爆乳美少女バニー、堪りませんねぇ～」
line = "「フオオオォ～！　久しぶりに拝見致しましたが、やはり会長様のバニー衣装はこの上なく素晴らしい……！　女体化爆乳美少女バニー、堪りませんねぇ～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「わかったわ！　こいつ<b>ヘンタイ</b>ね！」
line = "「わかったわ！　こいつ<b>ヘンタイ</b>ね！」"

[[dialogue]]
speaker = "ダッチ"
# 「ありがとうございます！　それは私にとって最高の褒め言葉！　最も強い『欲望』を持つ存在として、誇るべき称号です！」
line = "「ありがとうございます！　それは私にとって最高の褒め言葉！　最も強い『欲望』を持つ存在として、誇るべき称号です！」"

[[dialogue]]
speaker = "ダッチ"
# 「いやしかし、今はお正月。ここは１つ、可愛いウサギの耳を付けて、晴れ着バニーに改造するのも悪くありませんねぇ～」
line = "「いやしかし、今はお正月。ここは１つ、可愛いウサギの耳を付けて、晴れ着バニーに改造するのも悪くありませんねぇ～」"

[[dialogue]]
speaker = "ダッチ"
# 「ああ、そうです！　皆様の晴れ着も同じくアレンジして差し上げますよ。可愛さも強さも盛り盛りにパワーアップすること間違いなしです！」
line = "「ああ、そうです！　皆様の晴れ着も同じくアレンジして差し上げますよ。可愛さも強さも盛り盛りにパワーアップすること間違いなしです！」"

[[dialogue]]
speaker = "獅子舞"
# 「そんなことは認めんぞ、この俗物が！」
line = "「そんなことは認めんぞ、この俗物が！」"

[[dialogue]]
speaker = "unk"
# と、そこへ現れたのは、サーシャさんとアナが言っていた正月のロストアイテム『獅子舞』さんであった。
line = "と、そこへ現れたのは、サーシャさんとアナが言っていた正月のロストアイテム『獅子舞』さんであった。"

[[dialogue]]
speaker = "ダッチ"
# 「おやおや、これはこれは！　改めて、初詣に参りましたよ」
line = "「おやおや、これはこれは！　改めて、初詣に参りましたよ」"

[[dialogue]]
speaker = "獅子舞"
# 「何をしに来たかは知らんが、崇高なる晴れ着にバニーを加えるなど愚の骨頂！　崇高な料理に、砂糖壺をひっくり返すかのような愚行だ！！」
line = "「何をしに来たかは知らんが、崇高なる晴れ着にバニーを加えるなど愚の骨頂！　崇高な料理に、砂糖壺をひっくり返すかのような愚行だ！！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「つまり、唐揚げに無断でレモン汁をかけるみたいな感じね！」
line = "「つまり、唐揚げに無断でレモン汁をかけるみたいな感じね！」"

[[dialogue]]
speaker = "マトイ"
# 「微妙に違うような……？」
line = "「微妙に違うような……？」"

[[dialogue]]
speaker = "ダッチ"
# 「つれないことを言いますねぇ、<b>兄上</b>。せっかくこうして、可愛い<b>弟</b>が顔を見せにきたというのに！」
line = "「つれないことを言いますねぇ、<b>兄上</b>。せっかくこうして、可愛い<b>弟</b>が顔を見せにきたというのに！」"

[[dialogue]]
speaker = "unk"
# はっ！？　弟！？
line = "はっ！？　弟！？"

[[dialogue]]
speaker = "獅子舞"
# 「……そうだ。吾輩とダッチは同じ魔女によって作られた、自我を持つ７つのロストアイテム」
line = "「……そうだ。吾輩とダッチは同じ魔女によって作られた、自我を持つ７つのロストアイテム」"

[[dialogue]]
speaker = "獅子舞"
# 「認めたくないが、こいつは吾輩の<b>愚弟</b>なのだ……！」
line = "「認めたくないが、こいつは吾輩の<b>愚弟</b>なのだ……！」"

[[dialogue]]
speaker = "アナ"
# 「衝撃の事実……！」
line = "「衝撃の事実……！」"

[[dialogue]]
speaker = "ダッチ"
# 「ああ、そうです！　せっかくのお正月ですし、ここは我らの<ruby=あるじ>主</ruby>が好きだった羽根突きで勝負いたしませんか？」
line = "「ああ、そうです！　せっかくのお正月ですし、ここは我らの<ruby>主<rt>あるじ</rt></ruby>が好きだった羽根突きで勝負いたしませんか？」"

[[dialogue]]
speaker = "ダッチ"
# 「そして、私の欲望の力が勝利した暁には、皆様に晴れ着バニーを着て頂くというルールで！！」
line = "「そして、私の欲望の力が勝利した暁には、皆様に晴れ着バニーを着て頂くというルールで！！」"

[[dialogue]]
speaker = "獅子舞"
# 「ふざけるな俗物め。崇高な晴れ着に俗なバニーを混ぜるなど、許されざる愚行！　吾輩は絶対に認めん！！」
line = "「ふざけるな俗物め。崇高な晴れ着に俗なバニーを混ぜるなど、許されざる愚行！　吾輩は絶対に認めん！！」"

[[dialogue]]
speaker = "ダッチ"
# 「ンン～！　相変わらず兄上は頭が固い。晴れ着にバニーを混ぜることの一体何が悪だと言うのか！」
line = "「ンン～！　相変わらず兄上は頭が固い。晴れ着にバニーを混ぜることの一体何が悪だと言うのか！」"

[[dialogue]]
speaker = "ダッチ"
# 「多様性のこの時代、晴れ着のみを肯定するその考え方は実に傲慢ですよ、兄上？」
line = "「多様性のこの時代、晴れ着のみを肯定するその考え方は実に傲慢ですよ、兄上？」"

[[dialogue]]
speaker = "獅子舞"
# 「黙れ、愚弟。欲望のままに好みを他人に押し付けようとするお前とは、決して相容れぬ！」
line = "「黙れ、愚弟。欲望のままに好みを他人に押し付けようとするお前とは、決して相容れぬ！」"

[[dialogue]]
speaker = "ダッチ"
# 「ならば、やはり羽根突きで勝負するしかありませんねぇ！　そこまで晴れ着を崇高と仰るのであれば、バニー推しの私に是非、その崇高さを見せてもらいましょう！」
line = "「ならば、やはり羽根突きで勝負するしかありませんねぇ！　そこまで晴れ着を崇高と仰るのであれば、バニー推しの私に是非、その崇高さを見せてもらいましょう！」"

[[dialogue]]
speaker = "獅子舞"
# 「望むところだ！　晴れ着の星騎士たちよ、この俗物にお前たちの晴れ着の力を見せつけてやるがいい！」
line = "「望むところだ！　晴れ着の星騎士たちよ、この俗物にお前たちの晴れ着の力を見せつけてやるがいい！」"

[[dialogue]]
speaker = "アナ"
# 「え、あの……獅子舞さんではなく私たちが戦うんですか？」
line = "「え、あの……獅子舞さんではなく私たちが戦うんですか？」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら、どうやらそういう流れみたいね～」
line = "「あらあら、どうやらそういう流れみたいね～」"

[[dialogue]]
speaker = "マトイ"
# 「えっと、私の衣装、正確には晴れ着じゃなくて、巫女なんですけど……」
line = "「えっと、私の衣装、正確には晴れ着じゃなくて、巫女なんですけど……」"

[[dialogue]]
speaker = "獅子舞"
# 「今だけは晴れ着である！　吾輩がそう認めた！！」
line = "「今だけは晴れ着である！　吾輩がそう認めた！！」"

[[dialogue]]
speaker = "マトイ"
# 「えぇえええぇっ……！？」
line = "「えぇえええぇっ……！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「よく分からないけど、面白そうね！　その羽根突き勝負、受けて立つわ！」
line = "「よく分からないけど、面白そうね！　その羽根突き勝負、受けて立つわ！」"

[[dialogue]]
speaker = "unk"
# と、その時、お寺の境内に駆けつける者たちがいた。
line = "と、その時、お寺の境内に駆けつける者たちがいた。"

[[dialogue]]
speaker = "リーリア"
# 「――やけに騒がしいと思ったら、どういう状況ですか、これ！？」
line = "「――やけに騒がしいと思ったら、どういう状況ですか、これ！？」"

[[dialogue]]
speaker = "シズハ"
# 「会長たちと……なんか変なハート頭の人がいる！？」
line = "「会長たちと……なんか変なハート頭の人がいる！？」"

[[dialogue]]
speaker = "ダッチ"
# 「フフフ！　来ましたね。お待ちしておりましたよ、<b>魔弾の魔女様</b>」
line = "「フフフ！　来ましたね。お待ちしておりましたよ、<b>魔弾の魔女様</b>」"

[[dialogue]]
speaker = "unk"
# ダッチはリーリアの方へ視線を向けて、嬉しそうに告げるのだった。
line = "ダッチはリーリアの方へ視線を向けて、嬉しそうに告げるのだった。"
