[[dialogue]]
speaker = "ダッチ"
# 「フフ。勝負の前に喉が渇きましたね。可愛い子ウサギのセナリィ様、ワインを一杯いただけますか？」
line = "「フフ。勝負の前に喉が渇きましたね。可愛い子ウサギのセナリィ様、ワインを一杯いただけますか？」"

[[dialogue]]
speaker = "セナリィ"
# 「ぐ、ぐぅっ……！　このバンデット・セナリィを給仕として使うだなんて……この屈辱、後で必ずや……！」
line = "「ぐ、ぐぅっ……！　このバンデット・セナリィを給仕として使うだなんて……この屈辱、後で必ずや……！」"

[[dialogue]]
speaker = "ダッチ"
# 「嗚呼、いけません。いけませんねぇ」
line = "「嗚呼、いけません。いけませんねぇ」"

[[dialogue]]
speaker = "ダッチ"
# 「まだ全員が敗北されていないため意思までは奪っておりませんが……それでももう貴女は私の子ウサギなのですよ？」
line = "「まだ全員が敗北されていないため意思までは奪っておりませんが……それでももう貴女は私の子ウサギなのですよ？」"

[[dialogue]]
speaker = "ダッチ"
# 「先ほど、きちんとお伝えしたはず。語尾には何をつけろと言いましたか？」
line = "「先ほど、きちんとお伝えしたはず。語尾には何をつけろと言いましたか？」"

[[dialogue]]
speaker = "セナリィ"
# 「ぐぬぬぬっ……！」
line = "「ぐぬぬぬっ……！」"

[[dialogue]]
speaker = "セナリィ"
# 「お、お待たせいたしましたわ……ぴょん♪　ダッチ様にドリンクサービスっ<emoji=heart04>　子ウサギの愛情たっぷり赤ワインです、ぴょーんっ♪」
line = "「お、お待たせいたしましたわ……ぴょん♪　ダッチ様にドリンクサービスっ<emoji=heart04>　子ウサギの愛情たっぷり赤ワインです、ぴょーんっ♪」"

[[dialogue]]
speaker = "ダッチ"
# 「フォォオオォ！！　これだ！　これでこそウサギだ！　魔界はラパン地方の方言を取り入れたこの口調こそが正義！　フォォオ～……！」
line = "「フォォオオォ！！　これだ！　これでこそウサギだ！　魔界はラパン地方の方言を取り入れたこの口調こそが正義！　フォォオ～……！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ぜ、絶対に負けられません……死よりも恐ろしい罰ゲームですわ……」
line = "「ぜ、絶対に負けられません……死よりも恐ろしい罰ゲームですわ……」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「これは相当に業の深い欲望だね。ロストアイテムってみんなあんな感じなの、会長？」
line = "「これは相当に業の深い欲望だね。ロストアイテムってみんなあんな感じなの、会長？」"

[[dialogue]]
speaker = "unk"
# あいつだけだと思う……
line = "あいつだけだと思う……"

[[dialogue]]
speaker = "ダッチ"
# 「さぁセナリィ様。次は肩揉みです。その可憐な手のひらで、私の肩を優しく揉みほぐしていただけますかな？」
line = "「さぁセナリィ様。次は肩揉みです。その可憐な手のひらで、私の肩を優しく揉みほぐしていただけますかな？」"

[[dialogue]]
speaker = "セナリィ"
# 「ぐぎぎぎっ……！　お、お揉み致しますぴょん、ダッチ様……モミモミ、モ～ミっ……だぴょんっ♪」
line = "「ぐぎぎぎっ……！　お、お揉み致しますぴょん、ダッチ様……モミモミ、モ～ミっ……だぴょんっ♪」"

[[dialogue]]
speaker = "ダッチ"
# 「オゥフ……！　やる気がムンムン湧いてまいりましたよ！　では──２回戦と参りましょうか！」
line = "「オゥフ……！　やる気がムンムン湧いてまいりましたよ！　では──２回戦と参りましょうか！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「次戦は、ゲームが苦手な私が参ります。緋宮会長、ネーゼマイン様。後はよろしくお願いいたしますわ！」
line = "「次戦は、ゲームが苦手な私が参ります。緋宮会長、ネーゼマイン様。後はよろしくお願いいたしますわ！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「……先ほどのゲーム、どこか不自然な空気は私も感じておりますわ。ならば遊戯に慣れているあなたたちの思考時間を増やすべきだと考えておりますの」
line = "「……先ほどのゲーム、どこか不自然な空気は私も感じておりますわ。ならば遊戯に慣れているあなたたちの思考時間を増やすべきだと考えておりますの」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「千園寺先輩……」
line = "「千園寺先輩……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「おーっほっほっほ！　だからと言って端っから負けるつもりもありません！　千園寺の底力、見せて差し上げますわ！」
line = "「おーっほっほっほ！　だからと言って端っから負けるつもりもありません！　千園寺の底力、見せて差し上げますわ！」"

[[dialogue]]
speaker = "ダッチ"
# 「ヒルディオーネ様ですか……フフ！　手に汗握る名勝負をいたしましょう！」
line = "「ヒルディオーネ様ですか……フフ！　手に汗握る名勝負をいたしましょう！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「御託はよろしくてよ。さぁ、カードを！」
line = "「御託はよろしくてよ。さぁ、カードを！」"

[[dialogue]]
speaker = "モンスター"
# 「イ～っ！」
line = "「イ～っ！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# （大見得を切りましたが、トランプなんて本当に数えるほどしか触ったことがありませんわ……）
line = "（大見得を切りましたが、トランプなんて本当に数えるほどしか触ったことがありませんわ……）"

[[dialogue]]
speaker = "ヒルディオーネ"
# （クラブの４、ダイヤの４、ハートの６、ハートの７、ダイヤのＱ……）
line = "（クラブの４、ダイヤの４、ハートの６、ハートの７、ダイヤのＱ……）"

[[dialogue]]
speaker = "ヒルディオーネ"
# （これ……どうするのが正解ですの？　流石に緋宮会長たちに相談するのはルール違反ですし……）
line = "（これ……どうするのが正解ですの？　流石に緋宮会長たちに相談するのはルール違反ですし……）"

[[dialogue]]
speaker = "ネーゼマイン"
# （セナリィの時ほどじゃないけど、いいハンドだね。ワンペアでも役があるのは大きい）
line = "（セナリィの時ほどじゃないけど、いいハンドだね。ワンペアでも役があるのは大きい）"

[[dialogue]]
speaker = "ヒルディオーネ"
# （強いハンドを作らなければ勝負には勝てない、ですわよね？　ワンペアって一番弱い役だったはずですし……）
line = "（強いハンドを作らなければ勝負には勝てない、ですわよね？　ワンペアって一番弱い役だったはずですし……）"

[[dialogue]]
speaker = "ヒルディオーネ"
# （もっと強い役……そういえば同じ色で階段状になれば、ストレートフラッシュという役があったはずですわ！）
line = "（もっと強い役……そういえば同じ色で階段状になれば、ストレートフラッシュという役があったはずですわ！）"

[[dialogue]]
speaker = "ヒルディオーネ"
# （よし！　ハートの６と７以外、全部捨てますわ！　女は度胸でしてよ！）
line = "（よし！　ハートの６と７以外、全部捨てますわ！　女は度胸でしてよ！）"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「おーっほっほっほ！　３枚チェンジですわ！！」
line = "「おーっほっほっほ！　３枚チェンジですわ！！」"

[[dialogue]]
speaker = "unk"
# （うわあああ！？）
line = "（うわあああ！？）"

[[dialogue]]
speaker = "ネーゼマイン"
# （完成してるワンペアを捨てたー！？　ここからストレートを狙おうとしてるの！？　そんなのできるわけないよ先輩！？）
line = "（完成してるワンペアを捨てたー！？　ここからストレートを狙おうとしてるの！？　そんなのできるわけないよ先輩！？）"

[[dialogue]]
speaker = "ヒルディオーネ"
# （ストレートフラッシュを作るのですわ……！　来てくださいまし！　ハートの６、７まわりの３枚……！）
line = "（ストレートフラッシュを作るのですわ……！　来てくださいまし！　ハートの６、７まわりの３枚……！）"

[[dialogue]]
speaker = "モンスター"
# 「イ～っ……！」
line = "「イ～っ……！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「あ──！」
line = "「あ──！」"

[[dialogue]]
speaker = "ネーゼマイン"
# （嘘ぉ！？　ハートの８、９、１０が来た！？　ストフラの完成っ……これが財閥令嬢の運ってこと！？）
line = "（嘘ぉ！？　ハートの８、９、１０が来た！？　ストフラの完成っ……これが財閥令嬢の運ってこと！？）"

[[dialogue]]
speaker = "ヒルディオーネ"
# （な、何か思った通りの役ができましたわ！？　でもこれなら……あの変態紳士に一泡吹かせられるはず！）
line = "（な、何か思った通りの役ができましたわ！？　でもこれなら……あの変態紳士に一泡吹かせられるはず！）"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「レイズです！　さぁ、かかってきなさいダッチ！」
line = "「レイズです！　さぁ、かかってきなさいダッチ！」"

[[dialogue]]
speaker = "ダッチ"
# 「フフフ……星騎士の女性は気の強い方が多いのでしょうか？　まさかセナリィ様と同じく、一気に２０枚積みとは……！」
line = "「フフフ……星騎士の女性は気の強い方が多いのでしょうか？　まさかセナリィ様と同じく、一気に２０枚積みとは……！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# （うぅう……！　オリられるわけがないじゃありませんの！　ストレートフラッシュが出来てしまったら……！）
line = "（うぅう……！　オリられるわけがないじゃありませんの！　ストレートフラッシュが出来てしまったら……！）"

[[dialogue]]
speaker = "セナリィ"
# 「そこまで積み上げるということは！　先ほどの私レベルに強いハンドということですわよね！？　信じてますわよ！？」
line = "「そこまで積み上げるということは！　先ほどの私レベルに強いハンドということですわよね！？　信じてますわよ！？」"

[[dialogue]]
speaker = "セナリィ"
# 「というかダッチ！　千園寺様は腹芸のできないお人！　きっと最強クラスのハンドが完成してるはずですわ！」
line = "「というかダッチ！　千園寺様は腹芸のできないお人！　きっと最強クラスのハンドが完成してるはずですわ！」"

[[dialogue]]
speaker = "セナリィ"
# 「オリた方が賢明ではなくて！？　そのまま積んである１５枚のチップを回収されてしまいなさい！」
line = "「オリた方が賢明ではなくて！？　そのまま積んである１５枚のチップを回収されてしまいなさい！」"

[[dialogue]]
speaker = "ダッチ"
# 「いけませんよセナリィ様。ぴょんを付けてくださらないと」
line = "「いけませんよセナリィ様。ぴょんを付けてくださらないと」"

[[dialogue]]
speaker = "セナリィ"
# 「どうしてコイツ、こんなに余裕ですの！？　……ぴょん！」
line = "「どうしてコイツ、こんなに余裕ですの！？　……ぴょん！」"

[[dialogue]]
speaker = "ダッチ"
# 「フフフ。子ウサギに応援されて勇気も１００倍です。お受けしましょう──２０枚でコールです！」
line = "「フフフ。子ウサギに応援されて勇気も１００倍です。お受けしましょう──２０枚でコールです！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ショウダウンですわね！　刮目しなさい、これが千園寺の底力！　ストレートフラッシュですわ！！」
line = "「ショウダウンですわね！　刮目しなさい、これが千園寺の底力！　ストレートフラッシュですわ！！」"

[[dialogue]]
speaker = "セナリィ"
# 「役満クラスの化け物ハンド！！　来ましたわ～！！」
line = "「役満クラスの化け物ハンド！！　来ましたわ～！！」"

[[dialogue]]
speaker = "ダッチ"
# 「──失敬。またまた私の勝ちです」
line = "「──失敬。またまた私の勝ちです」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「──ですわっ！？」
line = "「──ですわっ！？」"

[[dialogue]]
speaker = "unk"
# またロイヤルストレートフラッシュ！？
line = "またロイヤルストレートフラッシュ！？"

[[dialogue]]
speaker = "ダッチ"
# 「嗚呼、僅差の勝負でございましたね！」
line = "「嗚呼、僅差の勝負でございましたね！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「こ、こんなのイカサマですわ！　ロイヤルストレートフラッシュが２連続だなんて、確率的にありえません！！」
line = "「こ、こんなのイカサマですわ！　ロイヤルストレートフラッシュが２連続だなんて、確率的にありえません！！」"

[[dialogue]]
speaker = "ダッチ"
# 「そう仰られても……ヒルディオーネ様だって、同じくらいに強いハンドを作られているではないですか？」
line = "「そう仰られても……ヒルディオーネ様だって、同じくらいに強いハンドを作られているではないですか？」"

[[dialogue]]
speaker = "ダッチ"
# 「もしもイカサマだと断じるなら、証拠を出して頂かないと？」
line = "「もしもイカサマだと断じるなら、証拠を出して頂かないと？」"

[[dialogue]]
speaker = "セナリィ"
# 「このっ……言わせておけば……！」
line = "「このっ……言わせておけば……！」"

[[dialogue]]
speaker = "セナリィ"
# （でも妙ですわ……。私の眼で監視していましたが、ダッチの動きに怪しいそぶりは一切ない……！）
line = "（でも妙ですわ……。私の眼で監視していましたが、ダッチの動きに怪しいそぶりは一切ない……！）"

[[dialogue]]
speaker = "セナリィ"
# （トランプモンスターのカード配りも、デッキトップからただ配るだけ……セカンドディールなどのイカサマも無し）
line = "（トランプモンスターのカード配りも、デッキトップからただ配るだけ……セカンドディールなどのイカサマも無し）"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「千園寺の娘である私が……悪党の後塵を拝するだなんて……！」
line = "「千園寺の娘である私が……悪党の後塵を拝するだなんて……！」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「……まずいね会長。このポーカー、普通じゃないよ」
line = "「……まずいね会長。このポーカー、普通じゃないよ」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「ダッチは絶対に何かをしてる。手口はまだわからないけど……たぶんセナリィも同じ。星眼ですらイカサマが見つけられないんだと思う」
line = "「ダッチは絶対に何かをしてる。手口はまだわからないけど……たぶんセナリィも同じ。星眼ですらイカサマが見つけられないんだと思う」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「だけど絶対に何かはしてる。その裏をかかないと……私たち全員、何もできずに負けちゃう……！」
line = "「だけど絶対に何かはしてる。その裏をかかないと……私たち全員、何もできずに負けちゃう……！」"
