[[dialogue]]
speaker = "unk"
# カティアとヒヨの練習を見守るのはミルフィーに任せて、続いて応援団の練習を見に来た。
line = "カティアとヒヨの練習を見守るのはミルフィーに任せて、続いて応援団の練習を見に来た。"

[[dialogue]]
speaker = "フラン"
# 「フレーッ！　フレーッ！　し・ん・せ・いーーッ！　はいっ！」
line = "「フレーッ！　フレーッ！　し・ん・せ・いーーッ！　はいっ！」"

[[dialogue]]
speaker = "応援団員"
# 「フレッ！　フレッ！　し・ん・せ・いっ！　フレッ！　フレッ！　し・ん・せ・いっ！」
line = "「フレッ！　フレッ！　し・ん・せ・いっ！　フレッ！　フレッ！　し・ん・せ・いっ！」"

[[dialogue]]
speaker = "フラン"
# 「押せ押せ、新星っ！　イケイケ、新星っ！　もっと声を出せっ！　今から命を燃やせーっ！」
line = "「押せ押せ、新星っ！　イケイケ、新星っ！　もっと声を出せっ！　今から命を燃やせーっ！」"

[[dialogue]]
speaker = "応援団員"
# 「はいっ！　押せ押せ、新星っ！　イケイケ、新星ーーっ！」
line = "「はいっ！　押せ押せ、新星っ！　イケイケ、新星ーーっ！」"

[[dialogue]]
speaker = "unk"
# 応援団員のフランが今年こそ新星学園を勝たせるべく、燃えるような熱量で応援団を指揮していた。
line = "応援団員のフランが今年こそ新星学園を勝たせるべく、燃えるような熱量で応援団を指揮していた。"

[[dialogue]]
speaker = "フラン"
# 「応援合戦で勝つのは当然として！　オレたちの魂の応援は、時に競技の勝敗を分ける！」
line = "「応援合戦で勝つのは当然として！　オレたちの魂の応援は、時に競技の勝敗を分ける！」"

[[dialogue]]
speaker = "フラン"
# 「オレたちの声は、選手たちの魂を奮い起こす！　たった１センチが勝負を決める過酷な世界で、背中を押すのはオレたちの声だ！」
line = "「オレたちの声は、選手たちの魂を奮い起こす！　たった１センチが勝負を決める過酷な世界で、背中を押すのはオレたちの声だ！」"

[[dialogue]]
speaker = "フラン"
# 「たった１センチに屈した悔し涙を何度も見てきた！　勝ちを掴んだ１センチの嬉し涙もまた何度も見てきた！」
line = "「たった１センチに屈した悔し涙を何度も見てきた！　勝ちを掴んだ１センチの嬉し涙もまた何度も見てきた！」"

[[dialogue]]
speaker = "フラン"
# 「オレたちが選手の目に輝かせるのは、どっちの涙だ！？」
line = "「オレたちが選手の目に輝かせるのは、どっちの涙だ！？」"

[[dialogue]]
speaker = "応援団員"
# 「はいっ！　嬉し涙です！」
line = "「はいっ！　嬉し涙です！」"

[[dialogue]]
speaker = "フラン"
# 「わかっていれば問題なーし！　もう１回、通しでいくぞー！」
line = "「わかっていれば問題なーし！　もう１回、通しでいくぞー！」"

[[dialogue]]
speaker = "応援団員"
# 「はーーーいっ！」
line = "「はーーーいっ！」"

[[dialogue]]
speaker = "unk"
# 応援団のフランの声は、団員たちをも鼓舞する。流石の手腕だと感心していると──
line = "応援団のフランの声は、団員たちをも鼓舞する。流石の手腕だと感心していると──"

[[dialogue]]
speaker = "美鶴"
# 「うへ、熱苦しー。見てるこっちが汗かきそ」
line = "「うへ、熱苦しー。見てるこっちが汗かきそ」"

[[dialogue]]
speaker = "美鶴"
# 「あれ、会長さんじゃん」
line = "「あれ、会長さんじゃん」"

[[dialogue]]
speaker = "unk"
# 美鶴がどうして……？
line = "美鶴がどうして……？"

[[dialogue]]
speaker = "美鶴"
# 「はは、うちがここにいるのはおかしい、って顔してんね。だよね、応援団とかうちのキャラじゃないよねー」
line = "「はは、うちがここにいるのはおかしい、って顔してんね。だよね、応援団とかうちのキャラじゃないよねー」"

[[dialogue]]
speaker = "美鶴"
# 「ま、簡単な話でさ。うち服飾やってるから、今年のチアガール衣装の制作、頼まれたの」
line = "「ま、簡単な話でさ。うち服飾やってるから、今年のチアガール衣装の制作、頼まれたの」"

[[dialogue]]
speaker = "美鶴"
# 「チア衣装は星騎士用の人工戦闘服になってるから、仕立てるの大変だったんだよねー。使いこなせるかは人次第だけど」
line = "「チア衣装は星騎士用の人工戦闘服になってるから、仕立てるの大変だったんだよねー。使いこなせるかは人次第だけど」"

[[dialogue]]
speaker = "美鶴"
# 「今チアの子たちが着てるやつがそう。昨日、納品したばっかだから、着て練習してるところを直に見に来たってわけ」
line = "「今チアの子たちが着てるやつがそう。昨日、納品したばっかだから、着て練習してるところを直に見に来たってわけ」"

[[dialogue]]
speaker = "美鶴"
# 「会長さんの目から見てどう？」
line = "「会長さんの目から見てどう？」"

[[dialogue]]
speaker = "unk"
# （ちょっと露出多めだけど……）
line = "（ちょっと露出多めだけど……）"

[[dialogue]]
speaker = "unk"
# 躍動感があって素晴らしいね！
line = "躍動感があって素晴らしいね！"

[[dialogue]]
speaker = "美鶴"
# 「会長さんが満足そうならアレでいいのかな……」
line = "「会長さんが満足そうならアレでいいのかな……」"

[[dialogue]]
speaker = "美鶴"
# 「んー……完成した時はまあまあだと思ってたんだけどさ。こうして見ると、イマイチしっくりきてなくて」
line = "「んー……完成した時はまあまあだと思ってたんだけどさ。こうして見ると、イマイチしっくりきてなくて」"

[[dialogue]]
speaker = "美鶴"
# 「なんでかな。会長さん、わかる？」
line = "「なんでかな。会長さん、わかる？」"

[[dialogue]]
speaker = "unk"
# 気になるなら、美鶴も着てみたら？
line = "気になるなら、美鶴も着てみたら？"

[[dialogue]]
speaker = "unk"
# 俺にはよくわかんないけど……
line = "俺にはよくわかんないけど……"

[[dialogue]]
speaker = "美鶴"
# 「え？　うちがチア衣装着るの？」
line = "「え？　うちがチア衣装着るの？」"

[[dialogue]]
speaker = "美鶴"
# 「うちはチアしないんだけど……ま、試しに着てみたら、今まで気づかなかったことにも気付くかもしんないか」
line = "「うちはチアしないんだけど……ま、試しに着てみたら、今まで気づかなかったことにも気付くかもしんないか」"

[[dialogue]]
speaker = "美鶴"
# 「それじゃ会長さん、教室行こっか」
line = "「それじゃ会長さん、教室行こっか」"

[[dialogue]]
speaker = "unk"
# なんで教室に？
line = "なんで教室に？"

[[dialogue]]
speaker = "美鶴"
# 「いやだって、外でお着替えすんのは流石に恥ずいじゃん。会長さん、うちを辱める趣味とかあんの？」
line = "「いやだって、外でお着替えすんのは流石に恥ずいじゃん。会長さん、うちを辱める趣味とかあんの？」"

[[dialogue]]
speaker = "unk"
# ノーコメントで
line = "ノーコメントで"

[[dialogue]]
speaker = "unk"
# ないよ！
line = "ないよ！"

[[dialogue]]
speaker = "美鶴"
# 「ふーん……怪しい……」
line = "「ふーん……怪しい……」"

[[dialogue]]
speaker = "美鶴"
# 「ま、その辺の追及はまた後でするとして……ほら、うちの教室こっちだから」
line = "「ま、その辺の追及はまた後でするとして……ほら、うちの教室こっちだから」"

[[dialogue]]
speaker = "unk"
# 美鶴に腕を引かれ、俺は校舎へと向かうのだった。
line = "美鶴に腕を引かれ、俺は校舎へと向かうのだった。"
