[[dialogue]]
speaker = "ウィステリア"
# 「フォビドゥンリアクター！」
line = "「フォビドゥンリアクター！」"

[[dialogue]]
speaker = "unk"
# ウィステリアが放った闇が、地下図書館の防衛システムが生み出した幻影を消滅させていく。
line = "ウィステリアが放った闇が、地下図書館の防衛システムが生み出した幻影を消滅させていく。"

[[dialogue]]
speaker = "モネ"
# 「すごい破壊力……いつ見てもウィステリアさんの星術は凄まじいですね……」
line = "「すごい破壊力……いつ見てもウィステリアさんの星術は凄まじいですね……」"

[[dialogue]]
speaker = "ウィステリア"
# 「大袈裟よ～。私のは魔力も使ってるから、星術としては邪道だしね」
line = "「大袈裟よ～。私のは魔力も使ってるから、星術としては邪道だしね」"

[[dialogue]]
speaker = "ウィステリア"
# 「しっかし、入るたびに防衛システムを蹴散らすのもうんざりね……。私のコピーなんて出してきたところでどうせ敵わないんだから、大人しく入れてくれればいいのに」
line = "「しっかし、入るたびに防衛システムを蹴散らすのもうんざりね……。私のコピーなんて出してきたところでどうせ敵わないんだから、大人しく入れてくれればいいのに」"

[[dialogue]]
speaker = "モネ"
# 「あはは……普通の星騎士だと、コピーのウィステリアさんでも全く勝てないんですけどね……」
line = "「あはは……普通の星騎士だと、コピーのウィステリアさんでも全く勝てないんですけどね……」"

[[dialogue]]
speaker = "モネ"
# （ここは新星学園の地下３０００メートルにある『地下図書館』。またの名を『深淵書庫』）
line = "（ここは新星学園の地下３０００メートルにある『地下図書館』。またの名を『深淵書庫』）"

[[dialogue]]
speaker = "モネ"
# （ある専門家によれば、リクリエ以前に生み出された遺物──ロストアイテムのひとつで、すでに何度かリクリエを乗り越えているとか）
line = "（ある専門家によれば、リクリエ以前に生み出された遺物──ロストアイテムのひとつで、すでに何度かリクリエを乗り越えているとか）"

[[dialogue]]
speaker = "モネ"
# （逆に言えば、それ以外の全ては謎に包まれている。その謎を調査するのが、ウィステリアさんの司書としての仕事。私は無理を言ってお手伝いをさせてもらっている）
line = "（逆に言えば、それ以外の全ては謎に包まれている。その謎を調査するのが、ウィステリアさんの司書としての仕事。私は無理を言ってお手伝いをさせてもらっている）"

[[dialogue]]
speaker = "ウィステリア"
# 「私からはぐれないでね、紙屋敷さん。あなたがここに入る許可を得られたのは、私が護衛につくって条件付きなんだから」
line = "「私からはぐれないでね、紙屋敷さん。あなたがここに入る許可を得られたのは、私が護衛につくって条件付きなんだから」"

[[dialogue]]
speaker = "ウィステリア"
# 「尋常じゃない量の魔力が渦巻いているし、防衛システムの攻撃もあるから、ここはとても危険よ」
line = "「尋常じゃない量の魔力が渦巻いているし、防衛システムの攻撃もあるから、ここはとても危険よ」"

[[dialogue]]
speaker = "モネ"
# 「はい、わかっています。私ひとりじゃいくつ命があっても足りません」
line = "「はい、わかっています。私ひとりじゃいくつ命があっても足りません」"

[[dialogue]]
speaker = "モネ"
# 「では行きましょう！　まだ見ぬ本が私たちを待っています！」
line = "「では行きましょう！　まだ見ぬ本が私たちを待っています！」"

[[dialogue]]
speaker = "ウィステリア"
# 「あっ、ちょっと、だから離れないでってば！　命がいくつあっても足りないって言ったのあなたでしょ！」
line = "「あっ、ちょっと、だから離れないでってば！　命がいくつあっても足りないって言ったのあなたでしょ！」"

[[dialogue]]
speaker = "ウィステリア"
# 「もう、今日もテンション高いわね、紙屋敷さん……」
line = "「もう、今日もテンション高いわね、紙屋敷さん……」"

[[dialogue]]
speaker = "モネ"
# 「未知の本たちと出合える絶好の機会ですからね！」
line = "「未知の本たちと出合える絶好の機会ですからね！」"

[[dialogue]]
speaker = "ウィステリア"
# 「危ないって何度も言ってるのに……本当に本に目がないのね」
line = "「危ないって何度も言ってるのに……本当に本に目がないのね」"

[[dialogue]]
speaker = "モネ"
# 「あ……ふわぁ～……」
line = "「あ……ふわぁ～……」"

[[dialogue]]
speaker = "ウィステリア"
# 「あら、眠そうね。もしかして探索が楽しみで眠れなかったの？」
line = "「あら、眠そうね。もしかして探索が楽しみで眠れなかったの？」"

[[dialogue]]
speaker = "モネ"
# 「それもあるんですが……実は夕べ遅くまで小説を書いていまして……」
line = "「それもあるんですが……実は夕べ遅くまで小説を書いていまして……」"

[[dialogue]]
speaker = "ウィステリア"
# 「小説を自分で？　すごいじゃない！」
line = "「小説を自分で？　すごいじゃない！」"

[[dialogue]]
speaker = "モネ"
# 「いえいえ、すごくなんかないですよ。原稿用紙とペンがあれば誰でも書けますから」
line = "「いえいえ、すごくなんかないですよ。原稿用紙とペンがあれば誰でも書けますから」"

[[dialogue]]
speaker = "ウィステリア"
# 「……それはできる人が言うことよ、紙屋敷さん。ちなみに、どんなのを書いてるの？」
line = "「……それはできる人が言うことよ、紙屋敷さん。ちなみに、どんなのを書いてるの？」"

[[dialogue]]
speaker = "モネ"
# 「不思議な力を持った少年を主人公にした冒険小説です。もうすぐ完成しそうで、つい熱が入ってしまって、最近は寝不足気味なんです」
line = "「不思議な力を持った少年を主人公にした冒険小説です。もうすぐ完成しそうで、つい熱が入ってしまって、最近は寝不足気味なんです」"

[[dialogue]]
speaker = "ウィステリア"
# 「ふふ、完成したらぜひ読ませてね。根っからの本好きの紙屋敷さんが書くんだから面白いに決まってるわ」
line = "「ふふ、完成したらぜひ読ませてね。根っからの本好きの紙屋敷さんが書くんだから面白いに決まってるわ」"

[[dialogue]]
speaker = "モネ"
# 「面白いかは約束できませんが、ウィステリアさんに読んでいただけるなら私も嬉しいです」
line = "「面白いかは約束できませんが、ウィステリアさんに読んでいただけるなら私も嬉しいです」"

[[dialogue]]
speaker = "モネ"
# 「それに、面白いって言ってもらえたら賞にも応募してみようかな……とか思ってたり……」
line = "「それに、面白いって言ってもらえたら賞にも応募してみようかな……とか思ってたり……」"

[[dialogue]]
speaker = "モネ"
# 「今回の小説は自分でもよく書けたと思ってるんです。でもけっこう攻めた設定と表現で……人によっては不愉快な気がして、自信が持てなくて……」
line = "「今回の小説は自分でもよく書けたと思ってるんです。でもけっこう攻めた設定と表現で……人によっては不愉快な気がして、自信が持てなくて……」"

[[dialogue]]
speaker = "モネ"
# 「私的には、当然面白いし、これがベストだと思っているんですけど……」
line = "「私的には、当然面白いし、これがベストだと思っているんですけど……」"

[[dialogue]]
speaker = "ウィステリア"
# 「う～ん……書いた人が面白いと思うのなら、それでいいんじゃない？　創作ってそういうものでしょ」
line = "「う～ん……書いた人が面白いと思うのなら、それでいいんじゃない？　創作ってそういうものでしょ」"

[[dialogue]]
speaker = "ウィステリア"
# 「偉そうなことは言えないけど、迷うなら応募した方がいいと思うわ。私だけじゃなくて、たくさんの人に読んでもらうべきよ」
line = "「偉そうなことは言えないけど、迷うなら応募した方がいいと思うわ。私だけじゃなくて、たくさんの人に読んでもらうべきよ」"

[[dialogue]]
speaker = "ウィステリア"
# 「だって、そのために書いたんでしょう？」
line = "「だって、そのために書いたんでしょう？」"

[[dialogue]]
speaker = "モネ"
# 「それは……そうなんですけど～」
line = "「それは……そうなんですけど～」"

[[dialogue]]
speaker = "ウィステリア"
# 「大丈夫大丈夫。紙屋敷さんが頑張って書いたんでしょ。なら悪いようにはならないわ」
line = "「大丈夫大丈夫。紙屋敷さんが頑張って書いたんでしょ。なら悪いようにはならないわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「それに思うようにいかなくたって、次に活かせばいい。紙屋敷さんならそれができるはずよ」
line = "「それに思うようにいかなくたって、次に活かせばいい。紙屋敷さんならそれができるはずよ」"

[[dialogue]]
speaker = "ウィステリア"
# 「私には作家になりたいとか、そういうしっかりした夢はないし、ちょっと尊敬しちゃうかも」
line = "「私には作家になりたいとか、そういうしっかりした夢はないし、ちょっと尊敬しちゃうかも」"

[[dialogue]]
speaker = "モネ"
# 「ウィステリアさんが、私を……？」
line = "「ウィステリアさんが、私を……？」"

[[dialogue]]
speaker = "モネ"
# 「ウィステリアさん、強くて、キレイで、何でもできる人だと思っていました。私なんかを尊敬するなんて、信じられません」
line = "「ウィステリアさん、強くて、キレイで、何でもできる人だと思っていました。私なんかを尊敬するなんて、信じられません」"

[[dialogue]]
speaker = "ウィステリア"
# 「もう、おだてても何も出ないわよ。そりゃ多少は戦えるけど、それだけ。ただの普通の魔族よ」
line = "「もう、おだてても何も出ないわよ。そりゃ多少は戦えるけど、それだけ。ただの普通の魔族よ」"

[[dialogue]]
speaker = "ウィステリア"
# 「ま、学生からしたら大人って、そう見えるものなんでしょうね。私も学生の頃は、大人ってもっと自由なものだと思ってたし」
line = "「ま、学生からしたら大人って、そう見えるものなんでしょうね。私も学生の頃は、大人ってもっと自由なものだと思ってたし」"

[[dialogue]]
speaker = "モネ"
# 「？　今は違うんですか？」
line = "「？　今は違うんですか？」"

[[dialogue]]
speaker = "ウィステリア"
# 「……卒業した後の就職先は一ヶ月で潰れちゃうし、お目当てのスイーツはいつも売り切れ、自由どころか思い通りにならないことばっかり……」
line = "「……卒業した後の就職先は一ヶ月で潰れちゃうし、お目当てのスイーツはいつも売り切れ、自由どころか思い通りにならないことばっかり……」"

[[dialogue]]
speaker = "ウィステリア"
# 「……いいえ、なんでもないわ。紙屋敷さんはそのままの紙屋敷さんでいてね」
line = "「……いいえ、なんでもないわ。紙屋敷さんはそのままの紙屋敷さんでいてね」"

[[dialogue]]
speaker = "モネ"
# 「はぁ……あっ！　見たことのない扉です」
line = "「はぁ……あっ！　見たことのない扉です」"

[[dialogue]]
speaker = "unk"
# 話しながら進むうちに、見覚えのない扉を見付けた。前回の探索までは、ここに扉はなかったはずだ。
line = "話しながら進むうちに、見覚えのない扉を見付けた。前回の探索までは、ここに扉はなかったはずだ。"

[[dialogue]]
speaker = "ウィステリア"
# 「なるほど、新しい領域ってわけね」
line = "「なるほど、新しい領域ってわけね」"

[[dialogue]]
speaker = "モネ"
# 「早く、早く開けましょう！　この先で、まだ見ぬ本たちが待ってます！」
line = "「早く、早く開けましょう！　この先で、まだ見ぬ本たちが待ってます！」"

[[dialogue]]
speaker = "ウィステリア"
# 「紙屋敷さん、落ち着いてー！」
line = "「紙屋敷さん、落ち着いてー！」"
