[[dialogue]]
speaker = "unk"
# お正月休みが明けて、登校日初日の放課後。
line = "お正月休みが明けて、登校日初日の放課後。"

[[dialogue]]
speaker = "unk"
# 俺たち新星学園星徒会のメンバーは、星徒会室に集まっていた――
line = "俺たち新星学園星徒会のメンバーは、星徒会室に集まっていた――"

[[dialogue]]
speaker = "ヴィーナス"
# 「久しぶりね、マトイ、アナ！　改めて、あけましておめでとう！」
line = "「久しぶりね、マトイ、アナ！　改めて、あけましておめでとう！」"

[[dialogue]]
speaker = "マトイ"
# 「あけましておめでとう、ヴィーナス、サーシャさん」
line = "「あけましておめでとう、ヴィーナス、サーシャさん」"

[[dialogue]]
speaker = "サーシャ"
# 「あ～ん、マトイちゃん、アナちゃん、久しぶりね～♪　しばらく会えなくて、お姉ちゃん寂しかったわ～」
line = "「あ～ん、マトイちゃん、アナちゃん、久しぶりね～♪　しばらく会えなくて、お姉ちゃん寂しかったわ～」"

[[dialogue]]
speaker = "アナ"
# 「会長も、あけましておめでとうございます」
line = "「会長も、あけましておめでとうございます」"

[[dialogue]]
speaker = "unk"
# お正月休みの間、元気してた？
line = "お正月休みの間、元気してた？"

[[dialogue]]
speaker = "アナ"
# 「はい。アニマ先輩と一緒に、年末から日本各地を研究で飛び回ってたんですが、旅行みたいな感じで楽しかったです」
line = "「はい。アニマ先輩と一緒に、年末から日本各地を研究で飛び回ってたんですが、旅行みたいな感じで楽しかったです」"

[[dialogue]]
speaker = "マトイ"
# 「私は家族でお祖母ちゃんの家に行って、親戚集まっての大宴会って感じかな。それよりも、会長たちは初詣で色々あったんでしょ？」
line = "「私は家族でお祖母ちゃんの家に行って、親戚集まっての大宴会って感じかな。それよりも、会長たちは初詣で色々あったんでしょ？」"

[[dialogue]]
speaker = "アナ"
# 「サーシャ先輩とソフィアさんが仲直りされたとか。おめでたです」
line = "「サーシャ先輩とソフィアさんが仲直りされたとか。おめでたです」"

[[dialogue]]
speaker = "サーシャ"
# 「うふふ、ありがと～♪」
line = "「うふふ、ありがと～♪」"

[[dialogue]]
speaker = "マトイ"
# 「教室で会長から聞きましたけど、晴れ着フォームにも変身できるようになったんですよね？」
line = "「教室で会長から聞きましたけど、晴れ着フォームにも変身できるようになったんですよね？」"

[[dialogue]]
speaker = "マトイ"
# 「う～ん、新年早々に目覚める新しい力、羨ましい～！　私も一緒に初詣に行きたかったな～」
line = "「う～ん、新年早々に目覚める新しい力、羨ましい～！　私も一緒に初詣に行きたかったな～」"

[[dialogue]]
speaker = "アナ"
# 「同じく。今後の研究の為にも、後でぜひ、晴れ着フォームを見せてもらいたいです」
line = "「同じく。今後の研究の為にも、後でぜひ、晴れ着フォームを見せてもらいたいです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「２人ならそう言うんじゃないかと思ってたわ！　というわけで――」
line = "「２人ならそう言うんじゃないかと思ってたわ！　というわけで――」"

[[dialogue]]
speaker = "ヴィーナス"
# 「今日これから、みんなで初詣に行くわよ！」
line = "「今日これから、みんなで初詣に行くわよ！」"

[[dialogue]]
speaker = "マトイ"
# 「へ！？」
line = "「へ！？」"

[[dialogue]]
speaker = "アナ"
# 「わお。そう来ましたか」
line = "「わお。そう来ましたか」"

[[dialogue]]
speaker = "サーシャ"
# 「あら～♪　それは面白そう♪」
line = "「あら～♪　それは面白そう♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「お寺や神社は別に逃げたりしないもの！　今からでも遅くないわ！」
line = "「お寺や神社は別に逃げたりしないもの！　今からでも遅くないわ！」"

[[dialogue]]
speaker = "unk"
# そうなりそうな気はしてた
line = "そうなりそうな気はしてた"

[[dialogue]]
speaker = "ヴィーナス"
# 「私たちは一緒に戦う仲間なんだし、みんなでリクリエへの必勝祈願をしておかないとね♪」
line = "「私たちは一緒に戦う仲間なんだし、みんなでリクリエへの必勝祈願をしておかないとね♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「さあ、フィクサーとして命じるわ――」
line = "「さあ、フィクサーとして命じるわ――」"

[[dialogue]]
speaker = "ヴィーナス"
# 「新星星徒会、初詣に出撃よ！」
line = "「新星星徒会、初詣に出撃よ！」"

[[dialogue]]
speaker = "unk"
# そうして俺たちは、再び浅草へとやってきた――
line = "そうして俺たちは、再び浅草へとやってきた――"

[[dialogue]]
speaker = "マトイ"
# 「本当に初詣をすることになるとは……」
line = "「本当に初詣をすることになるとは……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「よ～し、それじゃあ、まずは――」
line = "「よ～し、それじゃあ、まずは――」"

[[dialogue]]
speaker = "ヴィーナス"
# 「『おみくじ』からね！」
line = "「『おみくじ』からね！」"

[[dialogue]]
speaker = "マトイ"
# 「なんでおみくじ！？」
line = "「なんでおみくじ！？」"

[[dialogue]]
speaker = "マトイ"
# 「いや、引くのは別にいいんだけど、普通はお参りが先じゃないの？」
line = "「いや、引くのは別にいいんだけど、普通はお参りが先じゃないの？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私はケーキのイチゴは先に食べる派なのよ！」
line = "「私はケーキのイチゴは先に食べる派なのよ！」"

[[dialogue]]
speaker = "サーシャ"
# 「ヴィーナスちゃんは占い好きだものね～」
line = "「ヴィーナスちゃんは占い好きだものね～」"

[[dialogue]]
speaker = "unk"
# この前、大凶を引いてたな
line = "この前、大凶を引いてたな"

[[dialogue]]
speaker = "アナ"
# 「なるほど。つまり、前会長はおみくじリベンジをしたいというわけですね」
line = "「なるほど。つまり、前会長はおみくじリベンジをしたいというわけですね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「その通りよ！　ほら、その場で２回おみくじを引くのは意味なさそうだけど、後日改めて参拝にきて引いたら、セーフっぽい感じがするでしょ？」
line = "「その通りよ！　ほら、その場で２回おみくじを引くのは意味なさそうだけど、後日改めて参拝にきて引いたら、セーフっぽい感じがするでしょ？」"

[[dialogue]]
speaker = "マトイ"
# 「いや、どうかな……」
line = "「いや、どうかな……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ノープロブレムよ！」
line = "「ノープロブレムよ！」"

[[dialogue]]
speaker = "アナ"
# 「台詞をパクられました。訴訟問題です」
line = "「台詞をパクられました。訴訟問題です」"

[[dialogue]]
speaker = "unk"
# そんなこんなで、俺たちはおみくじを引くことになるのだった――
line = "そんなこんなで、俺たちはおみくじを引くことになるのだった――"
