[[dialogue]]
speaker = "unk"
# 今日は休日──アナはシュティレを誘って遊びに出かけている。
line = "今日は休日──アナはシュティレを誘って遊びに出かけている。"

[[dialogue]]
speaker = "unk"
# そのため俺は、アニマ先輩のところへ顔を出していた。
line = "そのため俺は、アニマ先輩のところへ顔を出していた。"

[[dialogue]]
speaker = "アニマ"
# 「なるほど、シュティレはアナとお出かけ？　珍しいこともあるものだナ。どうりで静かだと思ったヨ」
line = "「なるほど、シュティレはアナとお出かけ？　珍しいこともあるものだナ。どうりで静かだと思ったヨ」"

[[dialogue]]
speaker = "アニマ"
# 「フヒ。それならそれで、今日はじっくりと研究に集中できるナ♪」
line = "「フヒ。それならそれで、今日はじっくりと研究に集中できるナ♪」"

[[dialogue]]
speaker = "unk"
# シュティレのことなんですが……
line = "シュティレのことなんですが……"

[[dialogue]]
speaker = "アニマ"
# 「あぁ、やっぱりカ。わざわざ休日にアニマのところに来るから、きっとそのことだろうと思ってはいたヨ」
line = "「あぁ、やっぱりカ。わざわざ休日にアニマのところに来るから、きっとそのことだろうと思ってはいたヨ」"

[[dialogue]]
speaker = "アニマ"
# 「前に伝えた通りダ。アニマの弟子になるには、シュティレはロマンが足りなイ。こればっかりは会長の頼みでもマケられないナ」
line = "「前に伝えた通りダ。アニマの弟子になるには、シュティレはロマンが足りなイ。こればっかりは会長の頼みでもマケられないナ」"

[[dialogue]]
speaker = "アニマ"
# 「それよりキミ、シュティレのことばかりじゃなく、アナの世話をしてやらなくていいのかイ？」
line = "「それよりキミ、シュティレのことばかりじゃなく、アナの世話をしてやらなくていいのかイ？」"

[[dialogue]]
speaker = "アニマ"
# 「ノヴァフォームを発現できず、焦っているように見えル。あくまでアニマの主観だがナ」
line = "「ノヴァフォームを発現できず、焦っているように見えル。あくまでアニマの主観だがナ」"

[[dialogue]]
speaker = "アニマ"
# 「普段の会長なら、アナにべったりとくっついて相談に乗っていそうなものだガ？」
line = "「普段の会長なら、アナにべったりとくっついて相談に乗っていそうなものだガ？」"

[[dialogue]]
speaker = "unk"
# だけど今は俺の出番じゃない気がします
line = "だけど今は俺の出番じゃない気がします"

[[dialogue]]
speaker = "unk"
# 気にかけてはいますよ
line = "気にかけてはいますよ"

[[dialogue]]
speaker = "アニマ"
# 「フヒッ♪　極限と言えるほどのギリギリの戦闘訓練を繰り返し、それでも覚醒に至らなかっタ……故に別のアプローチが必要、ト？」
line = "「フヒッ♪　極限と言えるほどのギリギリの戦闘訓練を繰り返し、それでも覚醒に至らなかっタ……故に別のアプローチが必要、ト？」"

[[dialogue]]
speaker = "アニマ"
# 「ふ～む。確かにマトイが覚醒した時も、精神的なブレイクスルーが要因だったと聞いているヨ」
line = "「ふ～む。確かにマトイが覚醒した時も、精神的なブレイクスルーが要因だったと聞いているヨ」"

[[dialogue]]
speaker = "アニマ"
# 「おそらくアナに必要なのは、未知の体験による刺激！　そう考えると、シュティレとの繋がりは糸口になるかもしれないナ」
line = "「おそらくアナに必要なのは、未知の体験による刺激！　そう考えると、シュティレとの繋がりは糸口になるかもしれないナ」"

[[dialogue]]
speaker = "アニマ"
# 「星徒会の副会長という立場上、先輩とつるむことが多かっただろうし……後輩の世話を焼く、頼られるというのは、アナにとっても貴重な経験ということカ」
line = "「星徒会の副会長という立場上、先輩とつるむことが多かっただろうし……後輩の世話を焼く、頼られるというのは、アナにとっても貴重な経験ということカ」"

[[dialogue]]
speaker = "アニマ"
# 「フヒヒ♪　なんだかんだでアナのこと、よ～く考えてるみたいだナ♪」
line = "「フヒヒ♪　なんだかんだでアナのこと、よ～く考えてるみたいだナ♪」"

[[dialogue]]
speaker = "アニマ"
# 「アナが覚醒した暁には、どんな感情がトリガーになっていたのか……ぜひ教えてくれたまエ。とても興味があるヨ！」
line = "「アナが覚醒した暁には、どんな感情がトリガーになっていたのか……ぜひ教えてくれたまエ。とても興味があるヨ！」"

[[dialogue]]
speaker = "unk"
# 自身のノヴァフォームに興味はないんですか
line = "自身のノヴァフォームに興味はないんですか"

[[dialogue]]
speaker = "unk"
# そういうアニマ先輩はどうなんです？
line = "そういうアニマ先輩はどうなんです？"

[[dialogue]]
speaker = "アニマ"
# 「フヒヒヒッ、もちろんあるとモ！」
line = "「フヒヒヒッ、もちろんあるとモ！」"

[[dialogue]]
speaker = "アニマ"
# 「だが会長の目からは、アニマの裡側に覚醒の輝きは見えないのダロウ？」
line = "「だが会長の目からは、アニマの裡側に覚醒の輝きは見えないのダロウ？」"

[[dialogue]]
speaker = "アニマ"
# 「精神的なブレイクスルー……というのは苦手だヨ。心の分析は、アニマの最も苦手とするところダ」
line = "「精神的なブレイクスルー……というのは苦手だヨ。心の分析は、アニマの最も苦手とするところダ」"

[[dialogue]]
speaker = "アニマ"
# 「好きなものはいっぱいあるし、好奇心も人一倍。もちろん、会長のことも大好きダ♪　では何故、アニマの力は目覚めないんだろうネ？」
line = "「好きなものはいっぱいあるし、好奇心も人一倍。もちろん、会長のことも大好きダ♪　では何故、アニマの力は目覚めないんだろうネ？」"

[[dialogue]]
speaker = "アニマ"
# 「──さてと。あてにならない謎の力など置いておいて、弱体化薬の実験の続きでも……」
line = "「──さてと。あてにならない謎の力など置いておいて、弱体化薬の実験の続きでも……」"

[[dialogue]]
speaker = "アニマ"
# 「ム！　モンスターが現れたようだナ……！」
line = "「ム！　モンスターが現れたようだナ……！」"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 『会長、大変……市街地に機械型モンスターが出たよ！　数は……とにかくいっぱい！』
line = "『会長、大変……市街地に機械型モンスターが出たよ！　数は……とにかくいっぱい！』"

[[dialogue]]
speaker = "unk"
# わかった、応戦してくれ！
line = "わかった、応戦してくれ！"

[[dialogue]]
speaker = "マトイ（覚醒）"
# 『了解！　応援が来るまで私が食い止めるから！』
line = "『了解！　応援が来るまで私が食い止めるから！』"

[[dialogue]]
speaker = "アニマ"
# 「よし、出撃可能なメンバーを急行させるカ──ムムっ！？」
line = "「よし、出撃可能なメンバーを急行させるカ──ムムっ！？」"

[[dialogue]]
speaker = "アニマ"
# 「連続でアラートだト…！？」
line = "「連続でアラートだト…！？」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 『会長くん、大変よ！　学園の通学路付近、機械型モンスターが現れたわ！』
line = "『会長くん、大変よ！　学園の通学路付近、機械型モンスターが現れたわ！』"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 『えっ……マトイちゃんは別の場所で戦ってる！？　同時に出現だなんて……わかったわ。こっちはお姉ちゃんに任せて！』
line = "『えっ……マトイちゃんは別の場所で戦ってる！？　同時に出現だなんて……わかったわ。こっちはお姉ちゃんに任せて！』"

[[dialogue]]
speaker = "アニマ"
# 「大変ダ、会長。他からも連絡が入ったが……学園周辺や市街地で、機械型モンスターが同時発生しているらしイ……！」
line = "「大変ダ、会長。他からも連絡が入ったが……学園周辺や市街地で、機械型モンスターが同時発生しているらしイ……！」"

[[dialogue]]
speaker = "アニマ"
# 「複数個所を同時に襲撃……妙だナ。リクリエのモンスターに思考能力はないはずダ。偶然なのカ……！？」
line = "「複数個所を同時に襲撃……妙だナ。リクリエのモンスターに思考能力はないはずダ。偶然なのカ……！？」"

[[dialogue]]
speaker = "アナ"
# 『緊急事態です会長！　以前に観に行った立像が……ギガンドムがモンスター化しました！』
line = "『緊急事態です会長！　以前に観に行った立像が……ギガンドムがモンスター化しました！』"

[[dialogue]]
speaker = "unk"
# な──なんだって！？
line = "な──なんだって！？"

[[dialogue]]
speaker = "アナ"
# 『今までの機械型モンスターの比ではない耐久力です……至急、応援を！』
line = "『今までの機械型モンスターの比ではない耐久力です……至急、応援を！』"

[[dialogue]]
speaker = "unk"
# すぐに行く！
line = "すぐに行く！"

[[dialogue]]
speaker = "アニマ"
# 「おや、アニマのＤＩＳＣにもシュティレから通信ダ」
line = "「おや、アニマのＤＩＳＣにもシュティレから通信ダ」"

[[dialogue]]
speaker = "シュティレ"
# 『マスター、緊急事態です。実は……』
line = "『マスター、緊急事態です。実は……』"

[[dialogue]]
speaker = "アニマ"
# 「今、会長と一緒ダ、事態は把握していル！　持ちこたえろ、シュティレ！」
line = "「今、会長と一緒ダ、事態は把握していル！　持ちこたえろ、シュティレ！」"

[[dialogue]]
speaker = "アニマ"
# 「人命と自身の安全を最優先ダ！　決して無茶はするんじゃないゾ！」
line = "「人命と自身の安全を最優先ダ！　決して無茶はするんじゃないゾ！」"

[[dialogue]]
speaker = "シュティレ"
# 『嬉しいです。やはり弟子が可愛いのですね。ぶい』
line = "『嬉しいです。やはり弟子が可愛いのですね。ぶい』"

[[dialogue]]
speaker = "アニマ"
# 「冗談が言えるなら、まだ余裕はあるナ……！」
line = "「冗談が言えるなら、まだ余裕はあるナ……！」"

[[dialogue]]
speaker = "アニマ"
# 「いいカ、この通信は繋いだままにしておくんダ！　アナの指示を良く聞くんだゾ！」
line = "「いいカ、この通信は繋いだままにしておくんダ！　アナの指示を良く聞くんだゾ！」"

[[dialogue]]
speaker = "シュティレ"
# 『イエス、マイマスター……くっ！　手強い……！』
line = "『イエス、マイマスター……くっ！　手強い……！』"

[[dialogue]]
speaker = "アニマ"
# 「会長、出撃ダ！　弱体化薬もたんまり持って行くゾ……！」
line = "「会長、出撃ダ！　弱体化薬もたんまり持って行くゾ……！」"

[[dialogue]]
speaker = "アニマ"
# 「ノヴァフォームの星騎士の応援が頼めないとあっては、何とか時間を稼ぐしかなイ……！」
line = "「ノヴァフォームの星騎士の応援が頼めないとあっては、何とか時間を稼ぐしかなイ……！」"

[[dialogue]]
speaker = "unk"
# ヴィーナスも、トワ先生も、それぞれが外出先で出現した機械型モンスターの相手に追われているとの連絡があった。
line = "ヴィーナスも、トワ先生も、それぞれが外出先で出現した機械型モンスターの相手に追われているとの連絡があった。"

[[dialogue]]
speaker = "unk"
# アナ、シュティレ──持ちこたえてくれ……！
line = "アナ、シュティレ──持ちこたえてくれ……！"
