[[dialogue]]
speaker = "unk"
# ダッチの支配するアステラカジノから帰還した俺たちは、文字通り空中で投げ出され、九浄家のカジノに尻もちをつく形で帰還した。
line = "ダッチの支配するアステラカジノから帰還した俺たちは、文字通り空中で投げ出され、九浄家のカジノに尻もちをつく形で帰還した。"

[[dialogue]]
speaker = "ユーリス"
# 「みなさん！？　よかった、急にいなくなるから心配してたんですよ──って！？」
line = "「みなさん！？　よかった、急にいなくなるから心配してたんですよ──って！？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「いったぁ～……お尻打った～……！」
line = "「いったぁ～……お尻打った～……！」"

[[dialogue]]
speaker = "セナリィ"
# 「あんちきしょうっ……もっとスマートに送れなかったんですの……！？」
line = "「あんちきしょうっ……もっとスマートに送れなかったんですの……！？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「おーっほっほっほ！　突然の状況でも受け身くらい取れなくてはいけませんわ！」
line = "「おーっほっほっほ！　突然の状況でも受け身くらい取れなくてはいけませんわ！」"

[[dialogue]]
speaker = "ユーリス"
# 「な、なな、何なんですか、そのハレンチな恰好は──！！？？」
line = "「な、なな、何なんですか、そのハレンチな恰好は──！！？？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「あっ、王子様。ただいま～♪　いやー、ちょっと色々あってさ～」
line = "「あっ、王子様。ただいま～♪　いやー、ちょっと色々あってさ～」"

[[dialogue]]
speaker = "ユーリス"
# 「色々あったって……えぇえ……！？」
line = "「色々あったって……えぇえ……！？」"

[[dialogue]]
speaker = "unk"
# ユーリス、ただいま！
line = "ユーリス、ただいま！"

[[dialogue]]
speaker = "ユーリス"
# 「あっ、会長！　よかった、キミも無事に──」
line = "「あっ、会長！　よかった、キミも無事に──」"

[[dialogue]]
speaker = "ユーリス"
# 「～～～～っ！？」
line = "「～～～～っ！？」"

[[dialogue]]
speaker = "unk"
# ……ユーリス？
line = "……ユーリス？"

[[dialogue]]
speaker = "ユーリス"
# 「会長、気は確かか！？　その恰好は一体っ！？」
line = "「会長、気は確かか！？　その恰好は一体っ！？」"

[[dialogue]]
speaker = "unk"
# 俺の格好……？　うわああああ！？
line = "俺の格好……？　うわああああ！？"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ですわっ！？　緋宮会長、女体化は解かれているのに！」
line = "「ですわっ！？　緋宮会長、女体化は解かれているのに！」"

[[dialogue]]
speaker = "セナリィ"
# 「服装だけバニーのままで、やべぇ絵面ですわ！？」
line = "「服装だけバニーのままで、やべぇ絵面ですわ！？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「あははははははっ♪　待って、こんな不意打ち……！」
line = "「あははははははっ♪　待って、こんな不意打ち……！」"

[[dialogue]]
speaker = "ユーリス"
# 「なんで！？　なんでバニー！？　いきなりどこかに消えちゃうからずっと心配してたのに！」
line = "「なんで！？　なんでバニー！？　いきなりどこかに消えちゃうからずっと心配してたのに！」"

[[dialogue]]
speaker = "ユーリス"
# 「戻って来たと思ったら、どうしてそんな気の触れた格好をしてるの！？　意味がわからないんだけど！？」
line = "「戻って来たと思ったら、どうしてそんな気の触れた格好をしてるの！？　意味がわからないんだけど！？」"

[[dialogue]]
speaker = "unk"
# これはあの変態の仕業なんだ！！！
line = "これはあの変態の仕業なんだ！！！"

[[dialogue]]
speaker = "unk"
# 違うんだユーリス！
line = "違うんだユーリス！"

[[dialogue]]
speaker = "ユーリス"
# 「間違いなく今一番変態なのは会長だよ！？　前！　前を隠して！！　見えちゃいそうだよ～っ！？」
line = "「間違いなく今一番変態なのは会長だよ！？　前！　前を隠して！！　見えちゃいそうだよ～っ！？」"

[[dialogue]]
speaker = "セナリィ"
# 「というか大変ですわ！　カジノ中が騒がしいと思ったら……失踪者の皆様も、みんなバニー服で帰還してますわ！？」
line = "「というか大変ですわ！　カジノ中が騒がしいと思ったら……失踪者の皆様も、みんなバニー服で帰還してますわ！？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「壮年の紳士の皆様も、全員バニー衣装を着て……でも性別もご年齢も元に戻って……まずいですわ！　カジノ中、阿鼻叫喚でしてよ！？」
line = "「壮年の紳士の皆様も、全員バニー衣装を着て……でも性別もご年齢も元に戻って……まずいですわ！　カジノ中、阿鼻叫喚でしてよ！？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「あはははははっ♪　無理無理♪　我慢無理っ♪　お腹痛いっ！　あはははっ♪　さいって～なオチ……！」
line = "「あはははははっ♪　無理無理♪　我慢無理っ♪　お腹痛いっ！　あはははっ♪　さいって～なオチ……！」"

[[dialogue]]
speaker = "unk"
# 九浄家のカジノで発生する神隠し事件は無事に解決したのだが──その日、カジノは当然のごとく緊急閉店することとなり。
line = "九浄家のカジノで発生する神隠し事件は無事に解決したのだが──その日、カジノは当然のごとく緊急閉店することとなり。"

[[dialogue]]
speaker = "unk"
# 老若男女を問わず大量のバニーコスプレ客であふれたその日の出来事の一切に、<ruby=かんこうれい>緘口令</ruby>が敷かれることになるのだった──
line = "老若男女を問わず大量のバニーコスプレ客であふれたその日の出来事の一切に、<ruby>緘口令<rt>かんこうれい</rt></ruby>が敷かれることになるのだった──"
