[[dialogue]]
speaker = "ウェンディ"
# 「あ、モンスターがそちらに！」
line = "「あ、モンスターがそちらに！」"

[[dialogue]]
speaker = "unk"
# 任せろ
line = "任せろ"

[[dialogue]]
speaker = "ウェンディ"
# 「会長さん、ナイス足止めです。では──スミス！」
line = "「会長さん、ナイス足止めです。では──スミス！」"

[[dialogue]]
speaker = "スミス"
# 「ゲコ」
line = "「ゲコ」"

[[dialogue]]
speaker = "ウェンディ"
# 「アクアシーリング！」
line = "「アクアシーリング！」"

[[dialogue]]
speaker = "ウェンディ"
# 「ゲッコー！」
line = "「ゲッコー！」"

[[dialogue]]
speaker = "ウェンディ"
# 「ふぅ、これでまた一体捕まえられましたね」
line = "「ふぅ、これでまた一体捕まえられましたね」"

[[dialogue]]
speaker = "unk"
# 彼女はネビュラの魔女ウェンディ。
line = "彼女はネビュラの魔女ウェンディ。"

[[dialogue]]
speaker = "unk"
# どうして俺がネビュラの魔女とモンスターを捕獲しているのかというと──
line = "どうして俺がネビュラの魔女とモンスターを捕獲しているのかというと──"

[[dialogue]]
speaker = "unk"
# 本当は星徒会のみんなと、備品を購入するついでにお茶でもする予定だったのだけど。
line = "本当は星徒会のみんなと、備品を購入するついでにお茶でもする予定だったのだけど。"

[[dialogue]]
speaker = "unk"
# それぞれ用事が入ってしまって、俺１人でお使いをすることになった。
line = "それぞれ用事が入ってしまって、俺１人でお使いをすることになった。"

[[dialogue]]
speaker = "unk"
# せっかくの休日なのに残念だ。
line = "せっかくの休日なのに残念だ。"

[[dialogue]]
speaker = "unk"
# しかしこの辺りに来ると先日の戦いを思い出す──
line = "しかしこの辺りに来ると先日の戦いを思い出す──"

[[dialogue]]
speaker = "unk"
# アポロが呼び出す特殊なモンスター。
line = "アポロが呼び出す特殊なモンスター。"

[[dialogue]]
speaker = "unk"
# アポロとフィオナの秘密。
line = "アポロとフィオナの秘密。"

[[dialogue]]
speaker = "unk"
# 星騎士と守護星のリンクを遮断する“天蓋”。
line = "星騎士と守護星のリンクを遮断する“天蓋”。"

[[dialogue]]
speaker = "unk"
# 謎の巨大な“手”。
line = "謎の巨大な“手”。"

[[dialogue]]
speaker = "unk"
# どれも記憶に残る出来事で、新たに判明したこともあれば、余計にわからなくなった謎もある。
line = "どれも記憶に残る出来事で、新たに判明したこともあれば、余計にわからなくなった謎もある。"

[[dialogue]]
speaker = "unk"
# そして──
line = "そして──"

[[dialogue]]
speaker = "unk"
# “魔女”。
line = "“魔女”。"

[[dialogue]]
speaker = "unk"
# 魔力と呼ばれる未知の力を操る者たち。
line = "魔力と呼ばれる未知の力を操る者たち。"

[[dialogue]]
speaker = "unk"
# ネビュラと名乗る秘密組織。
line = "ネビュラと名乗る秘密組織。"

[[dialogue]]
speaker = "unk"
# 彼女たちもリクリエを防ごうとしているらしいが、本当のところはわからない。
line = "彼女たちもリクリエを防ごうとしているらしいが、本当のところはわからない。"

[[dialogue]]
speaker = "unk"
# そして俺は新星学園の星徒会長だ。
line = "そして俺は新星学園の星徒会長だ。"

[[dialogue]]
speaker = "unk"
# 流星と新星──この世界を守る星騎士の両翼の、その頂点に立つ存在。
line = "流星と新星──この世界を守る星騎士の両翼の、その頂点に立つ存在。"

[[dialogue]]
speaker = "unk"
# 大きな責任を負う者として、俺は数々の異変にどう向き合っていくべきだろうか。
line = "大きな責任を負う者として、俺は数々の異変にどう向き合っていくべきだろうか。"

[[dialogue]]
speaker = "unk"
# だけど今この瞬間、街は紛れもなく平和だ。
line = "だけど今この瞬間、街は紛れもなく平和だ。"

[[dialogue]]
speaker = "unk"
# たとえこの先厳しい運命が待ち受けているとしても、俺１人だとしても、ひとまずはこの平和を享受しようと──
line = "たとえこの先厳しい運命が待ち受けているとしても、俺１人だとしても、ひとまずはこの平和を享受しようと──"

[[dialogue]]
speaker = "unk"
# …………
line = "…………"

[[dialogue]]
speaker = "unk"
# ……………………
line = "……………………"

[[dialogue]]
speaker = "unk"
# アポロのモンスター！？
line = "アポロのモンスター！？"

[[dialogue]]
speaker = "unk"
# 見るからに大人しく、暴れるようなそぶりはない。
line = "見るからに大人しく、暴れるようなそぶりはない。"

[[dialogue]]
speaker = "unk"
# だけどモンスターは人々に危害をもたらす脅威だ。
line = "だけどモンスターは人々に危害をもたらす脅威だ。"

[[dialogue]]
speaker = "unk"
# まだ被害が出ていないうちに仕留めようと、拳を握り──
line = "まだ被害が出ていないうちに仕留めようと、拳を握り──"

[[dialogue]]
speaker = "？？？"
# 「そのモンスター、倒すのちょっと待って下さい！」
line = "「そのモンスター、倒すのちょっと待って下さい！」"

[[dialogue]]
speaker = "unk"
# ！？
line = "！？"

[[dialogue]]
speaker = "ウェンディ"
# 「はぁ、はぁ、はぁ……すみません、そこのモンスター、うちから逃げ出したやつでして……」
line = "「はぁ、はぁ、はぁ……すみません、そこのモンスター、うちから逃げ出したやつでして……」"

[[dialogue]]
speaker = "unk"
# うちから？
line = "うちから？"

[[dialogue]]
speaker = "ウェンディ"
# 「あ、モンスターが逃げちゃいます！？　詳しいことは後で説明しますから、捕まえるの手伝ってくださーい！」
line = "「あ、モンスターが逃げちゃいます！？　詳しいことは後で説明しますから、捕まえるの手伝ってくださーい！」"
