[[dialogue]]
speaker = "蘭美"
# 「せつなと閃から報告を受けたわ。２人ともなかなかやるようね！」
line = "「せつなと閃から報告を受けたわ。２人ともなかなかやるようね！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「それはもう見事なお手並みでしたの！　肝心の捕り物シーンが見られなかったのは残念でしたけど」
line = "「それはもう見事なお手並みでしたの！　肝心の捕り物シーンが見られなかったのは残念でしたけど」"

[[dialogue]]
speaker = "蘭美"
# 「そう……でも九浄家に仕える使用人たる者、荒事に長けているだけでもダメよ。頭脳や対応力も優秀でなければね」
line = "「そう……でも九浄家に仕える使用人たる者、荒事に長けているだけでもダメよ。頭脳や対応力も優秀でなければね」"

[[dialogue]]
speaker = "蘭美"
# 「というわけで、ヨミの事務仕事を手伝ってもらうわ！」
line = "「というわけで、ヨミの事務仕事を手伝ってもらうわ！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「事務仕事ですか？」
line = "「事務仕事ですか？」"

[[dialogue]]
speaker = "ヨミ"
# 「お願いしてしまってごめんなさい！　メイドのお仕事じゃないんですけど……」
line = "「お願いしてしまってごめんなさい！　メイドのお仕事じゃないんですけど……」"

[[dialogue]]
speaker = "ミウ"
# 「どういったお仕事なんですか？」
line = "「どういったお仕事なんですか？」"

[[dialogue]]
speaker = "ヨミ"
# 「ご存知かと思いますが、私、学園では任務管轄係として働いておりまして」
line = "「ご存知かと思いますが、私、学園では任務管轄係として働いておりまして」"

[[dialogue]]
speaker = "ヒマワリ"
# 「知ってますよ。何度かお世話になったこともありますし」
line = "「知ってますよ。何度かお世話になったこともありますし」"

[[dialogue]]
speaker = "unk"
# モンスターとの戦闘時にオペレーターを務めたり、任務の発注や案内などを行うのが任務管轄係の主な仕事だ。
line = "モンスターとの戦闘時にオペレーターを務めたり、任務の発注や案内などを行うのが任務管轄係の主な仕事だ。"

[[dialogue]]
speaker = "unk"
# 星騎士の出撃数や、モンスターの撃墜数などの管理も行っているが、ヨミもその任務管轄係として働いている。
line = "星騎士の出撃数や、モンスターの撃墜数などの管理も行っているが、ヨミもその任務管轄係として働いている。"

[[dialogue]]
speaker = "unk"
# ヒマワリもミウも大聖堂カフェテリアで、仕事に従事しているヨミの姿を何度も見たことがあった。
line = "ヒマワリもミウも大聖堂カフェテリアで、仕事に従事しているヨミの姿を何度も見たことがあった。"

[[dialogue]]
speaker = "ヨミ"
# 「最近、利用者が大幅に増えたのは嬉しい悲鳴なんですけど、お仕事がいっぱい過ぎて事務作業が追いつかない状態になってしまってまして」
line = "「最近、利用者が大幅に増えたのは嬉しい悲鳴なんですけど、お仕事がいっぱい過ぎて事務作業が追いつかない状態になってしまってまして」"

[[dialogue]]
speaker = "蘭美"
# 「利用者のリスト化と上手な捌き方を考案して、ヨミを手伝ってあげてほしいの。どう、できるかしら？」
line = "「利用者のリスト化と上手な捌き方を考案して、ヨミを手伝ってあげてほしいの。どう、できるかしら？」"

[[dialogue]]
speaker = "ミウ"
# 「大丈夫です。むしろ、荒事よりも得意ジャンルです」
line = "「大丈夫です。むしろ、荒事よりも得意ジャンルです」"

[[dialogue]]
speaker = "ヒマワリ"
# 「分業にしよっか。利用者のリスト化はあたしが入力するんで、誰か未処理のリストを仕分けて並べてくれませんか？」
line = "「分業にしよっか。利用者のリスト化はあたしが入力するんで、誰か未処理のリストを仕分けて並べてくれませんか？」"

[[dialogue]]
speaker = "蘭美"
# 「私がやるわ！　ヒマワリの入力スピード、私の仕分けスピードに追いつけるかしら？」
line = "「私がやるわ！　ヒマワリの入力スピード、私の仕分けスピードに追いつけるかしら？」"

[[dialogue]]
speaker = "ヨミ"
# 「あの、では私はどうしましょう……？」
line = "「あの、では私はどうしましょう……？」"

[[dialogue]]
speaker = "ミウ"
# 「私と一緒にリスト化の効率的なフローを考えませんか？　それが終わったら、リスト化作業に合流ということで」
line = "「私と一緒にリスト化の効率的なフローを考えませんか？　それが終わったら、リスト化作業に合流ということで」"

[[dialogue]]
speaker = "ヨミ"
# 「わ、わかりました～！」
line = "「わ、わかりました～！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「うううっ！　何なんですの、２人のこのお仕事出来るオーラ！　私の入り込む隙がありませんわ！」
line = "「うううっ！　何なんですの、２人のこのお仕事出来るオーラ！　私の入り込む隙がありませんわ！」"

[[dialogue]]
speaker = "蘭美"
# 「ふふ、ヒマワリもミウもやるわね。山積みだった報告書がこんなに簡単に片づいてしまうなんて」
line = "「ふふ、ヒマワリもミウもやるわね。山積みだった報告書がこんなに簡単に片づいてしまうなんて」"

[[dialogue]]
speaker = "ヨミ"
# 「明日からのお仕事が、とっても楽になりますー！　ミウさん、ありがとうございます！」
line = "「明日からのお仕事が、とっても楽になりますー！　ミウさん、ありがとうございます！」"

[[dialogue]]
speaker = "ミウ"
# 「いえいえ、私はちょっとアイデアを出しただけですから。元々のヨミさんの処理能力の高さを活かしているだけですよ」
line = "「いえいえ、私はちょっとアイデアを出しただけですから。元々のヨミさんの処理能力の高さを活かしているだけですよ」"

[[dialogue]]
speaker = "蘭美"
# 「閃やせつなも、あなたたちをべた褒めしていたわ。『見習い』が外れるのも、そう遠い先の話じゃなさそうね」
line = "「閃やせつなも、あなたたちをべた褒めしていたわ。『見習い』が外れるのも、そう遠い先の話じゃなさそうね」"

[[dialogue]]
speaker = "ヒマワリ"
# 「えへへー、そういってもらえて嬉しいです。早く立派な使用人になりたいですねー」
line = "「えへへー、そういってもらえて嬉しいです。早く立派な使用人になりたいですねー」"

[[dialogue]]
speaker = "ミウ"
# （ヒマワリちゃん、楽しむのもいいけど、私たちの本当の目的は忘れないようにね）
line = "（ヒマワリちゃん、楽しむのもいいけど、私たちの本当の目的は忘れないようにね）"

[[dialogue]]
speaker = "ヒマワリ"
# （そうなんだよねー。メイド隊のみんなを騙してるみたいで、ちょっと胸が痛いなー）
line = "（そうなんだよねー。メイド隊のみんなを騙してるみたいで、ちょっと胸が痛いなー）"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ヒマワリ様もミウ様も使用人体験を満喫していて……羨ましいですわ」
line = "「ヒマワリ様もミウ様も使用人体験を満喫していて……羨ましいですわ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「せっかくの可愛いメイドタイプの人工戦闘服なのですし、持ち腐れになってしまいますわ！　私ももっとメイドとしてご奉仕したいですのっ！」
line = "「せっかくの可愛いメイドタイプの人工戦闘服なのですし、持ち腐れになってしまいますわ！　私ももっとメイドとしてご奉仕したいですのっ！」"

[[dialogue]]
speaker = "蘭美"
# 「ヘレナ様からは許可を頂いているけど……本当にいいのかしら？　あなたは桜十路家という名家のお嬢様なのに」
line = "「ヘレナ様からは許可を頂いているけど……本当にいいのかしら？　あなたは桜十路家という名家のお嬢様なのに」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「あら、名家というならば蘭美様も魔界の名家の出身ですわよね？　それなのにメイドとして働いていらっしゃるではありませんの」
line = "「あら、名家というならば蘭美様も魔界の名家の出身ですわよね？　それなのにメイドとして働いていらっしゃるではありませんの」"

[[dialogue]]
speaker = "蘭美"
# 「あら、これは１本取られたわね……」
line = "「あら、これは１本取られたわね……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「可愛いだけではなくてとても動きやすくて、お仕事でも戦闘でも力を発揮できますのよ？　黙って見ているだけなんてもったいないですわ！」
line = "「可愛いだけではなくてとても動きやすくて、お仕事でも戦闘でも力を発揮できますのよ？　黙って見ているだけなんてもったいないですわ！」"

[[dialogue]]
speaker = "ミウ"
# 「その人工戦闘服、すごくハイスペックそうですもんね？　それにしても何故エルデリーゼ先輩が、その人工戦闘服を着ることになったんですか？」
line = "「その人工戦闘服、すごくハイスペックそうですもんね？　それにしても何故エルデリーゼ先輩が、その人工戦闘服を着ることになったんですか？」"

[[dialogue]]
speaker = "ヒマワリ"
# 「あ、それ気になってました！　あたしも知りたいです！」
line = "「あ、それ気になってました！　あたしも知りたいです！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「あら、おふたりにはお話ししてませんでしたか？　実はヘレナ様がこの人工戦闘服を思いついた際に私をイメージしてくださったのです」
line = "「あら、おふたりにはお話ししてませんでしたか？　実はヘレナ様がこの人工戦闘服を思いついた際に私をイメージしてくださったのです」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「実際に戦闘服が出来上がったら、どうしても私が着ているところをみたくて、モデルとしてスカウトされたという事ですのよ」
line = "「実際に戦闘服が出来上がったら、どうしても私が着ているところをみたくて、モデルとしてスカウトされたという事ですのよ」"

[[dialogue]]
speaker = "ミウ"
# 「では本当に、エルデリーゼ先輩のために作られた戦闘服なんですね」
line = "「では本当に、エルデリーゼ先輩のために作られた戦闘服なんですね」"

[[dialogue]]
speaker = "ヒマワリ"
# 「少しだけ戦った感じだと、なんか普通の人工戦闘服に感じない力を感じたんですけど……何か秘密があったりするんですか？」
line = "「少しだけ戦った感じだと、なんか普通の人工戦闘服に感じない力を感じたんですけど……何か秘密があったりするんですか？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「いいえ？　特にうかがってはいませんけど……」
line = "「いいえ？　特にうかがってはいませんけど……」"

[[dialogue]]
speaker = "ヒマワリ"
# 「そっかー……エルゼ先輩がそう言うなら、そうなのかなー」
line = "「そっかー……エルゼ先輩がそう言うなら、そうなのかなー」"

[[dialogue]]
speaker = "ミウ"
# （何かを隠している様子はなし……あてが外れちゃったかな？）
line = "（何かを隠している様子はなし……あてが外れちゃったかな？）"

[[dialogue]]
speaker = "蘭美"
# 「２人とも、随分と食いつきがいいのね……はっ！？　もしかして、あなたたち……！」
line = "「２人とも、随分と食いつきがいいのね……はっ！？　もしかして、あなたたち……！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「ぎくっ！？」
line = "「ぎくっ！？」"

[[dialogue]]
speaker = "ミウ"
# （潜入捜査が勘付かれた！？　ちょっと前のめりになりすぎちゃったから──）
line = "（潜入捜査が勘付かれた！？　ちょっと前のめりになりすぎちゃったから──）"

[[dialogue]]
speaker = "蘭美"
# 「チーパオよりもメイド服に興味があったのかしら？　それなら今度、美鶴にお願いしてみるといいわ！」
line = "「チーパオよりもメイド服に興味があったのかしら？　それなら今度、美鶴にお願いしてみるといいわ！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「め、メイド服もいいですね～！　長いスカートの中に武器を仕込んでおくのとか格好いいですしー！」
line = "「め、メイド服もいいですね～！　長いスカートの中に武器を仕込んでおくのとか格好いいですしー！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「まあ！　言われてみれば、映画やアニメで見たことがありますわ！　素敵ですわよね！」
line = "「まあ！　言われてみれば、映画やアニメで見たことがありますわ！　素敵ですわよね！」"

[[dialogue]]
speaker = "ミウ"
# 「それも含めて、今度、美鶴さんにも詳しいお話をうかがいたいです」
line = "「それも含めて、今度、美鶴さんにも詳しいお話をうかがいたいです」"

[[dialogue]]
speaker = "ミウ"
# （ふぅ……気づかれてない……よね？）
line = "（ふぅ……気づかれてない……よね？）"
