[[dialogue]]
speaker = "unk"
# そして――約束の日、当日。
line = "そして――約束の日、当日。"

[[dialogue]]
speaker = "セドナ"
# 「こうして直接まみえるのはリクリエ以来か？　久しいな緋宮クロト」
line = "「こうして直接まみえるのはリクリエ以来か？　久しいな緋宮クロト」"

[[dialogue]]
speaker = "セドナ"
# 「今日はこのような場を設けていただき、ネビュラを代表して感謝を述べさせてもらおう」
line = "「今日はこのような場を設けていただき、ネビュラを代表して感謝を述べさせてもらおう」"

[[dialogue]]
speaker = "unk"
# ようこそお越しくださいました
line = "ようこそお越しくださいました"

[[dialogue]]
speaker = "アイリーン"
# 「お世話になりま～す♪」
line = "「お世話になりま～す♪」"

[[dialogue]]
speaker = "リーリア"
# 「はえ～。何だかんだ、星徒会室までお邪魔するのは久々かも～」
line = "「はえ～。何だかんだ、星徒会室までお邪魔するのは久々かも～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「え～と、ネビュラからの参加者は３人ってことでいいのかしら？」
line = "「え～と、ネビュラからの参加者は３人ってことでいいのかしら？」"

[[dialogue]]
speaker = "セドナ"
# 「ああ、我々も何かと忙しくてな。リーリアと私、それからアイリーンの３名の参加になる」
line = "「ああ、我々も何かと忙しくてな。リーリアと私、それからアイリーンの３名の参加になる」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ネビュラも大変なのね～」
line = "「ネビュラも大変なのね～」"

[[dialogue]]
speaker = "セドナ"
# 「リクリエを退けたことで平穏が訪れてくれていれば、余裕もあっただろうがな」
line = "「リクリエを退けたことで平穏が訪れてくれていれば、余裕もあっただろうがな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「まあまあ、今日くらいはそういう事も忘れてリフレッシュしていきなさい♪」
line = "「まあまあ、今日くらいはそういう事も忘れてリフレッシュしていきなさい♪」"

[[dialogue]]
speaker = "セドナ"
# 「ああ、そうさせてもらうつもりだ」
line = "「ああ、そうさせてもらうつもりだ」"

[[dialogue]]
speaker = "リーリア"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# 元気がないみたいだけど
line = "元気がないみたいだけど"

[[dialogue]]
speaker = "unk"
# あれ？　どうしたの、リーリア？
line = "あれ？　どうしたの、リーリア？"

[[dialogue]]
speaker = "リーリア"
# 「あはは、そ、そんなことないですよ～……」
line = "「あはは、そ、そんなことないですよ～……」"

[[dialogue]]
speaker = "リーリア"
# 「…………えっと、実はですね……」
line = "「…………えっと、実はですね……」"

[[dialogue]]
speaker = "リーリア"
# 「――というわけで、新星の星徒会長からお誘いを頂いたんですけど、セドナ長官的にはどうですか？」
line = "「――というわけで、新星の星徒会長からお誘いを頂いたんですけど、セドナ長官的にはどうですか？」"

[[dialogue]]
speaker = "セドナ"
# 「ふむ、ありがたい申し出だが、こちらも色々と忙しい状態だからな……全員でという訳にもいかないだろう」
line = "「ふむ、ありがたい申し出だが、こちらも色々と忙しい状態だからな……全員でという訳にもいかないだろう」"

[[dialogue]]
speaker = "リーリア"
# （うんうん、長官がこんな話に乗り気になるわけないもんね。ここまでは読み通り）
line = "（うんうん、長官がこんな話に乗り気になるわけないもんね。ここまでは読み通り）"

[[dialogue]]
speaker = "リーリア"
# 「えーと……それじゃ仕方ありませんね！」
line = "「えーと……それじゃ仕方ありませんね！」"

[[dialogue]]
speaker = "リーリア"
# 「学園側の心遣いを無下にするわけにもいきませんし、ここは代表して私が行ってきます！」
line = "「学園側の心遣いを無下にするわけにもいきませんし、ここは代表して私が行ってきます！」"

[[dialogue]]
speaker = "セドナ"
# 「ああ、お前なら先方とのコミュニケーションも円滑に進められるだろう。リーリアにはもちろん行ってもらう」
line = "「ああ、お前なら先方とのコミュニケーションも円滑に進められるだろう。リーリアにはもちろん行ってもらう」"

[[dialogue]]
speaker = "リーリア"
# 「はーい、お任せください♪」
line = "「はーい、お任せください♪」"

[[dialogue]]
speaker = "セドナ"
# 「後は……私も参加しよう」
line = "「後は……私も参加しよう」"

[[dialogue]]
speaker = "リーリア"
# 「へっ！？」
line = "「へっ！？」"

[[dialogue]]
speaker = "セドナ"
# 「今しがた報告を受けたばかりなのだが、私の水着形体の戦闘服も完成したのだ」
line = "「今しがた報告を受けたばかりなのだが、私の水着形体の戦闘服も完成したのだ」"

[[dialogue]]
speaker = "リーリア"
# 「そ、それは……おめでとうございます……」
line = "「そ、それは……おめでとうございます……」"

[[dialogue]]
speaker = "セドナ"
# 「この戦闘服に用いられている技術は同盟の証として学園側より提供されたもの」
line = "「この戦闘服に用いられている技術は同盟の証として学園側より提供されたもの」"

[[dialogue]]
speaker = "セドナ"
# 「それを元に作られたこの戦闘服の性能テストに、新星の星徒会が協力してくれるというのは願ってもない話だ」
line = "「それを元に作られたこの戦闘服の性能テストに、新星の星徒会が協力してくれるというのは願ってもない話だ」"

[[dialogue]]
speaker = "リーリア"
# 「あの～……セドナ長官？　これは水着戦闘服の戦闘テストではなく、あくまで『オペレーション・ペンダグラム』の打ち上げで……」
line = "「あの～……セドナ長官？　これは水着戦闘服の戦闘テストではなく、あくまで『オペレーション・ペンダグラム』の打ち上げで……」"

[[dialogue]]
speaker = "セドナ"
# 「分かっている。あくまで今回の目的は親睦だ」
line = "「分かっている。あくまで今回の目的は親睦だ」"

[[dialogue]]
speaker = "セドナ"
# 「だが新しい戦闘服の能力を確かめる絶好の機会であることも間違いないだろう……違うか？」
line = "「だが新しい戦闘服の能力を確かめる絶好の機会であることも間違いないだろう……違うか？」"

[[dialogue]]
speaker = "リーリア"
# 「まあ、そういう側面も無きにしもあらず、かもしれませんが……」
line = "「まあ、そういう側面も無きにしもあらず、かもしれませんが……」"

[[dialogue]]
speaker = "セドナ"
# 「ならばこの機会を活用することに何の不都合もあるまい」
line = "「ならばこの機会を活用することに何の不都合もあるまい」"

[[dialogue]]
speaker = "セドナ"
# 「その招待にはお前と私で応じるとしよう」
line = "「その招待にはお前と私で応じるとしよう」"

[[dialogue]]
speaker = "セドナ"
# 「そうと決まれば早速、先方と段取りをつけた方が良いだろう。それはお前に一任するが問題ないか？」
line = "「そうと決まれば早速、先方と段取りをつけた方が良いだろう。それはお前に一任するが問題ないか？」"

[[dialogue]]
speaker = "リーリア"
# 「イ、イエス、マム……」
line = "「イ、イエス、マム……」"

[[dialogue]]
speaker = "セドナ"
# 「よし、では頼んだぞ」
line = "「よし、では頼んだぞ」"

[[dialogue]]
speaker = "リーリア"
# （ちょっと待ってよ！　な、何でこんな事になっちゃったのーーーーっ！！！）
line = "（ちょっと待ってよ！　な、何でこんな事になっちゃったのーーーーっ！！！）"

[[dialogue]]
speaker = "リーリア"
# 「とまあそんなわけで、『親睦』とは程遠いところにいるヒトが来ちゃったんです……」
line = "「とまあそんなわけで、『親睦』とは程遠いところにいるヒトが来ちゃったんです……」"

[[dialogue]]
speaker = "アイリーン"
# 「あはは～♪　ちなみに私は『長官と２人きりだけは勘弁して』と泣きつかれて参加することになりました」
line = "「あはは～♪　ちなみに私は『長官と２人きりだけは勘弁して』と泣きつかれて参加することになりました」"

[[dialogue]]
speaker = "unk"
# そ、それはご苦労さま
line = "そ、それはご苦労さま"

[[dialogue]]
speaker = "リーリア"
# 「他人事みたいに言ってる場合じゃありませんよ、センパイ」
line = "「他人事みたいに言ってる場合じゃありませんよ、センパイ」"

[[dialogue]]
speaker = "リーリア"
# 「セドナ長官が参加したら、絶対ただの親睦会で収まるはずがないんですから」
line = "「セドナ長官が参加したら、絶対ただの親睦会で収まるはずがないんですから」"

[[dialogue]]
speaker = "リーリア"
# 「ほら、見てください。案の定、向こうではどんどんそういう流れになっちゃってますし」
line = "「ほら、見てください。案の定、向こうではどんどんそういう流れになっちゃってますし」"

[[dialogue]]
speaker = "セドナ"
# 「我らネビュラの研究所でも水着戦闘服の能力試験を行ったが、期待以上の性能を見せてくれていた」
line = "「我らネビュラの研究所でも水着戦闘服の能力試験を行ったが、期待以上の性能を見せてくれていた」"

[[dialogue]]
speaker = "セドナ"
# 「だが、やはり数値だけでは測れない部分もある。今回は先達の胸を借りて戦闘服の性能を引き出せるよう学びたい」
line = "「だが、やはり数値だけでは測れない部分もある。今回は先達の胸を借りて戦闘服の性能を引き出せるよう学びたい」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうよねー、私たちも最初は制御が難しかったし」
line = "「そうよねー、私たちも最初は制御が難しかったし」"

[[dialogue]]
speaker = "サーシャ"
# 「ちょっと独特のコツみたいなものがあるのよね～」
line = "「ちょっと独特のコツみたいなものがあるのよね～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうそう、コツと言えばね！　私、水着フォームをさらにパワーアップさせることに成功したのよ！」
line = "「そうそう、コツと言えばね！　私、水着フォームをさらにパワーアップさせることに成功したのよ！」"

[[dialogue]]
speaker = "アナ"
# 「は？　……あの前会長、それは初耳なんですが……？」
line = "「は？　……あの前会長、それは初耳なんですが……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「みんなを驚かせようと思って！　デザインも性能も一新した、スーパーフォームなんだから！」
line = "「みんなを驚かせようと思って！　デザインも性能も一新した、スーパーフォームなんだから！」"

[[dialogue]]
speaker = "マトイ"
# 「アナ……水着フォームのパワーアップって、できるものなの……？」
line = "「アナ……水着フォームのパワーアップって、できるものなの……？」"

[[dialogue]]
speaker = "アナ"
# 「いえ……本来であれば、ありえないことです。原理上、そういうことができるようにはなっていないはずですが……」
line = "「いえ……本来であれば、ありえないことです。原理上、そういうことができるようにはなっていないはずですが……」"

[[dialogue]]
speaker = "サーシャ"
# 「まあそこは、ヴィーナスちゃんだからね～」
line = "「まあそこは、ヴィーナスちゃんだからね～」"

[[dialogue]]
speaker = "アナ"
# 「前会長は、本当に研究者泣かせです……」
line = "「前会長は、本当に研究者泣かせです……」"

[[dialogue]]
speaker = "アナ"
# 「何れにしても、前会長の新フォームも、ネビュラの方々の新フォームも、引き続きデータ分析していきましょう。用意はしていますので、色々任せてください」
line = "「何れにしても、前会長の新フォームも、ネビュラの方々の新フォームも、引き続きデータ分析していきましょう。用意はしていますので、色々任せてください」"

[[dialogue]]
speaker = "セドナ"
# 「感謝する」
line = "「感謝する」"

[[dialogue]]
speaker = "リーリア"
# 「あのー、長官……そういうのもいいんですけど、今回の一番の目的は親睦ですからね、親睦」
line = "「あのー、長官……そういうのもいいんですけど、今回の一番の目的は親睦ですからね、親睦」"

[[dialogue]]
speaker = "セドナ"
# 「もちろんだとも。この機会を通じてより確固たる新星学園との協力体制を築いてゆきたいものだ」
line = "「もちろんだとも。この機会を通じてより確固たる新星学園との協力体制を築いてゆきたいものだ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「うんうん。それじゃ出発するわよ！　常夏のビーチにレッツゴー！！」
line = "「うんうん。それじゃ出発するわよ！　常夏のビーチにレッツゴー！！」"
