[[dialogue]]
speaker = "unk"
# メルエルが『大聖堂』へ行くと、そこには小さなメルエルが１人で待っていた。
line = "メルエルが『大聖堂』へ行くと、そこには小さなメルエルが１人で待っていた。"

[[dialogue]]
speaker = "メルエル"
# 「やっぱり、ここにいた……！」
line = "「やっぱり、ここにいた……！」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「……やっぱり、私自身には隠し通せないか」
line = "「……やっぱり、私自身には隠し通せないか」"

[[dialogue]]
speaker = "メルエル"
# 「うん。ここは昔……私が会長くんと約束を交わした場所だからね」
line = "「うん。ここは昔……私が会長くんと約束を交わした場所だからね」"

[[dialogue]]
speaker = "メルエル"
# 「私から告白するなら、ここに会長くんを呼び出してするって思ったから……」
line = "「私から告白するなら、ここに会長くんを呼び出してするって思ったから……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「……ねぇ、どうして邪魔をするの？」
line = "「……ねぇ、どうして邪魔をするの？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「私は、今まで勇気が出せなくて、会長くんに本当の気持ちを言うことができなかった」
line = "「私は、今まで勇気が出せなくて、会長くんに本当の気持ちを言うことができなかった」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「だからこそ、今回はチャンスなのに。だって――」
line = "「だからこそ、今回はチャンスなのに。だって――」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「小さい姿の私は、<b>精神強化の能力</b>によって、普段の私よりも『勇気を出す』ことができるって、前に説明しておいたでしょ？」
line = "「小さい姿の私は、<b>精神強化の能力</b>によって、普段の私よりも『勇気を出す』ことができるって、前に説明しておいたでしょ？」"

[[dialogue]]
speaker = "メルエル"
# 「うん。確かに、私は今まで勇気が足りてなかった。それでも――」
line = "「うん。確かに、私は今まで勇気が足りてなかった。それでも――」"

[[dialogue]]
speaker = "メルエル"
# 「会長くんへの気持ちだけは、あなたにも譲れないよ」
line = "「会長くんへの気持ちだけは、あなたにも譲れないよ」"

[[dialogue]]
speaker = "メルエル"
# 「告白は、能力を使わずに……自分自身の力でちゃんとしたい」
line = "「告白は、能力を使わずに……自分自身の力でちゃんとしたい」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「……そんな綺麗ごとばっかり言って。じゃあどうして、その自分自身の力で、ちゃんと告白しなかったの」
line = "「……そんな綺麗ごとばっかり言って。じゃあどうして、その自分自身の力で、ちゃんと告白しなかったの」"

[[dialogue]]
speaker = "メルエル"
# 「言い訳にはなっちゃうんだけど……聞いて欲しいな」
line = "「言い訳にはなっちゃうんだけど……聞いて欲しいな」"

[[dialogue]]
speaker = "メルエル"
# 「もし、もしね……？　会長くんが私と一緒に遊んだ１０年前の記憶を覚えてたら……」
line = "「もし、もしね……？　会長くんが私と一緒に遊んだ１０年前の記憶を覚えてたら……」"

[[dialogue]]
speaker = "メルエル"
# 「そうじゃなかったとしても、断片的にでも思い出してくれていたら、私はすぐにでも告白したと思うんだ」
line = "「そうじゃなかったとしても、断片的にでも思い出してくれていたら、私はすぐにでも告白したと思うんだ」"

[[dialogue]]
speaker = "メルエル"
# 「でもね……会長くんは覚えてなかった。再会の約束も……『<ruby=もうひとつ>結婚</ruby>』の約束も」
line = "「でもね……会長くんは覚えてなかった。再会の約束も……『<ruby>結婚<rt>もうひとつ</rt></ruby>』の約束も」"

[[dialogue]]
speaker = "メルエル"
# 「そんな会長くんに、私が告白するのは……迷惑になっちゃうかもって、ずっと思ってたの」
line = "「そんな会長くんに、私が告白するのは……迷惑になっちゃうかもって、ずっと思ってたの」"

[[dialogue]]
speaker = "メルエル"
# 「それに、会長くんは魔王で、リクリエと戦うリーダーでしょ」
line = "「それに、会長くんは魔王で、リクリエと戦うリーダーでしょ」"

[[dialogue]]
speaker = "メルエル"
# 「会長くんは色んな人と交渉したり、肩を並べて戦ったりしなきゃいけない人で……私も、プリマステラの１人として、戦力になっている自負はあるんだ」
line = "「会長くんは色んな人と交渉したり、肩を並べて戦ったりしなきゃいけない人で……私も、プリマステラの１人として、戦力になっている自負はあるんだ」"

[[dialogue]]
speaker = "メルエル"
# 「もし、会長くんが責任ある立場じゃなかったら、きっとわき目も振らず告白してたと思う」
line = "「もし、会長くんが責任ある立場じゃなかったら、きっとわき目も振らず告白してたと思う」"

[[dialogue]]
speaker = "メルエル"
# 「それで会長くんと両想いになれて、恋人になれたら、本当に幸せだと思う。本当に、どうにかなっちゃうくらい、幸せ」
line = "「それで会長くんと両想いになれて、恋人になれたら、本当に幸せだと思う。本当に、どうにかなっちゃうくらい、幸せ」"

[[dialogue]]
speaker = "メルエル"
# 「だけど、もし会長くんが私のことをそういう風には見ていなかったら……告白された会長くんは、苦しいと思うの」
line = "「だけど、もし会長くんが私のことをそういう風には見ていなかったら……告白された会長くんは、苦しいと思うの」"

[[dialogue]]
speaker = "メルエル"
# 「告白って……断る側も傷つくものだと思うから」
line = "「告白って……断る側も傷つくものだと思うから」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「って、そういう風に都合のいい言い訳をして、逃げていたんだよね？」
line = "「って、そういう風に都合のいい言い訳をして、逃げていたんだよね？」"

[[dialogue]]
speaker = "メルエル"
# 「うん、そうだと思う。本当は……私は怖かったんだよ――」
line = "「うん、そうだと思う。本当は……私は怖かったんだよ――」"

[[dialogue]]
speaker = "メルエル"
# 「会長くんに好きだって気持ちを伝えて、フラれてしまうのが」
line = "「会長くんに好きだって気持ちを伝えて、フラれてしまうのが」"

[[dialogue]]
speaker = "メルエル"
# 「でもね、会長くんの迷惑になりたくなかったのも本当。フラれるのが怖かったのも本当。どっちも本当の自分だよ」
line = "「でもね、会長くんの迷惑になりたくなかったのも本当。フラれるのが怖かったのも本当。どっちも本当の自分だよ」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「だからこそ、私は『勇気を出す』能力で、もっと積極的な自分になろうと思ったんだよ」
line = "「だからこそ、私は『勇気を出す』能力で、もっと積極的な自分になろうと思ったんだよ」"

[[dialogue]]
speaker = "メルエル"
# 「わかるよ。あなたは私だもん……もうこれ以上、我慢できなかったんだよね」
line = "「わかるよ。あなたは私だもん……もうこれ以上、我慢できなかったんだよね」"

[[dialogue]]
speaker = "メルエル"
# 「だって……一緒の時間を過ごせば過ごすほど、会長くんのことが好きで好きで、たまらなくなってきちゃうもんね」
line = "「だって……一緒の時間を過ごせば過ごすほど、会長くんのことが好きで好きで、たまらなくなってきちゃうもんね」"

[[dialogue]]
speaker = "メルエル"
# 「再会する前よりずっと、再会したときよりずっと、何千倍も、会長くんのことが大好き」
line = "「再会する前よりずっと、再会したときよりずっと、何千倍も、会長くんのことが大好き」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「……っ」
line = "「……っ」"

[[dialogue]]
speaker = "メルエル"
# 「ちゃんと伝える。ちゃんとするから……」
line = "「ちゃんと伝える。ちゃんとするから……」"

[[dialogue]]
speaker = "メルエル"
# 「だからその役目は、私に譲って欲しいな」
line = "「だからその役目は、私に譲って欲しいな」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「今までずっと言えなかったのに……ちゃんと言えるの？」
line = "「今までずっと言えなかったのに……ちゃんと言えるの？」"

[[dialogue]]
speaker = "メルエル"
# 「うん。友達から、勇気をもらったから」
line = "「うん。友達から、勇気をもらったから」"

[[dialogue]]
speaker = "メルエル"
# 「それに……小さい私から、学んだこともあるの」
line = "「それに……小さい私から、学んだこともあるの」"

[[dialogue]]
speaker = "unk"
# メルエルはそう言って、後ろを振り返る。
line = "メルエルはそう言って、後ろを振り返る。"

[[dialogue]]
speaker = "クロト"
# 「メルエル……」
line = "「メルエル……」"

[[dialogue]]
speaker = "unk"
# そこにはメルエルが想いを寄せる相手――クロトの姿があった。
line = "そこにはメルエルが想いを寄せる相手――クロトの姿があった。"

[[dialogue]]
speaker = "unk"
# 俺が、小さなメルエルに呼び出されて大聖堂へ向かうと、そこには話し合っている２人のメルエルの姿があった。
line = "俺が、小さなメルエルに呼び出されて大聖堂へ向かうと、そこには話し合っている２人のメルエルの姿があった。"

[[dialogue]]
speaker = "メルエル"
# 「えへへっ。恥ずかしいところ、見られちゃったね」
line = "「えへへっ。恥ずかしいところ、見られちゃったね」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# 俺は少し前から２人の会話が聞こえていて、メルエルたちもそのことに気づいていたようだった。
line = "俺は少し前から２人の会話が聞こえていて、メルエルたちもそのことに気づいていたようだった。"

[[dialogue]]
speaker = "メルエル"
# 「話が聞こえてたなら……ううん。会長くんのことだから、本当はもっとずっと前から、気持ちが伝わっちゃってるかもしれないけど……」
line = "「話が聞こえてたなら……ううん。会長くんのことだから、本当はもっとずっと前から、気持ちが伝わっちゃってるかもしれないけど……」"

[[dialogue]]
speaker = "unk"
# 大きなメルエルが俺に正面から向き直って、視線を真っすぐに合わせる。
line = "大きなメルエルが俺に正面から向き直って、視線を真っすぐに合わせる。"

[[dialogue]]
speaker = "メルエル"
# 「すぅ～……はあぁ……」
line = "「すぅ～……はあぁ……」"

[[dialogue]]
speaker = "unk"
# 彼女は１度深呼吸をしてから、告げた。
line = "彼女は１度深呼吸をしてから、告げた。"

[[dialogue]]
speaker = "メルエル"
# 「私、姫咲メルエルは――会長くんのことが好きです」
line = "「私、姫咲メルエルは――会長くんのことが好きです」"

[[dialogue]]
speaker = "メルエル"
# 「ずっと前から――子供の頃から、キミのことが好きでしたっ」
line = "「ずっと前から――子供の頃から、キミのことが好きでしたっ」"

[[dialogue]]
speaker = "メルエル"
# 「再会してからは、好きって気持ちがもっともっと大きくなってて……」
line = "「再会してからは、好きって気持ちがもっともっと大きくなってて……」"

[[dialogue]]
speaker = "メルエル"
# 「今ではもう、伝えずにいたら……破裂しちゃいそうなくらい、私の中はキミへの気持ちで一杯なの」
line = "「今ではもう、伝えずにいたら……破裂しちゃいそうなくらい、私の中はキミへの気持ちで一杯なの」"

[[dialogue]]
speaker = "メルエル"
# 「それくらい……キミのことが大好き<emoji=heart04>」
line = "「それくらい……キミのことが大好き<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル"
# 「もしかしたら、私の気持ちなんて、ずっと前からバレちゃってたかもしれないけど……」
line = "「もしかしたら、私の気持ちなんて、ずっと前からバレちゃってたかもしれないけど……」"

[[dialogue]]
speaker = "メルエル"
# 「でもやっぱり、『好き』って口にするのはちょっと勇気がいるね……えへへっ」
line = "「でもやっぱり、『好き』って口にするのはちょっと勇気がいるね……えへへっ」"

[[dialogue]]
speaker = "メルエル"
# 「ああ、でもようやく……会長くんに『好き』って言えた……本当に好き<emoji=heart04>　大好き<emoji=heart04>」
line = "「ああ、でもようやく……会長くんに『好き』って言えた……本当に好き<emoji=heart04>　大好き<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# メルエル、えっと……
line = "メルエル、えっと……"

[[dialogue]]
speaker = "メルエル"
# 「あっ、ごめんね！　そのうえで、会長くんにはお願いしたいことがあるの……！」
line = "「あっ、ごめんね！　そのうえで、会長くんにはお願いしたいことがあるの……！」"

[[dialogue]]
speaker = "メルエル"
# 「えっと、これは本当に私のワガママになっちゃうんだけど……」
line = "「えっと、これは本当に私のワガママになっちゃうんだけど……」"

[[dialogue]]
speaker = "メルエル"
# 「告白の返事は、もう少しだけ待って欲しいんだ」
line = "「告白の返事は、もう少しだけ待って欲しいんだ」"

[[dialogue]]
speaker = "メルエル"
# 「告白はしたけど、振ったり、ＯＫしたりするのを待って欲しいというか、なんというか……」
line = "「告白はしたけど、振ったり、ＯＫしたりするのを待って欲しいというか、なんというか……」"

[[dialogue]]
speaker = "unk"
# 保留してほしい、ってこと？
line = "保留してほしい、ってこと？"

[[dialogue]]
speaker = "メルエル"
# 「う、うん……。今、世界はすごく大変な時期でしょ？」
line = "「う、うん……。今、世界はすごく大変な時期でしょ？」"

[[dialogue]]
speaker = "メルエル"
# 「これからリクリエとの最終決戦が始まるかもしれないって時に、余計なトラブルは持ち込みたくないから」
line = "「これからリクリエとの最終決戦が始まるかもしれないって時に、余計なトラブルは持ち込みたくないから」"

[[dialogue]]
speaker = "メルエル"
# 「会長くんに振られても……もし万が一、お付き合いできることになっても……どっちにしろ私、たぶん正気じゃいられなくなっちゃうと思うんだよねっ」
line = "「会長くんに振られても……もし万が一、お付き合いできることになっても……どっちにしろ私、たぶん正気じゃいられなくなっちゃうと思うんだよねっ」"

[[dialogue]]
speaker = "メルエル"
# 「一生懸命戦っている会長くんの邪魔も、したくないし……」
line = "「一生懸命戦っている会長くんの邪魔も、したくないし……」"

[[dialogue]]
speaker = "メルエル"
# 「だから、リクリエとの決戦が終わったら、その時に告白の答え、聞かせてほしいな！」
line = "「だから、リクリエとの決戦が終わったら、その時に告白の答え、聞かせてほしいな！」"

[[dialogue]]
speaker = "unk"
# メルエルが、それでいいなら
line = "メルエルが、それでいいなら"

[[dialogue]]
speaker = "unk"
# ……わかった。
line = "……わかった。"

[[dialogue]]
speaker = "メルエル"
# 「ありがとう、会長くん♪」
line = "「ありがとう、会長くん♪」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「やっと言えたね、大きな私」
line = "「やっと言えたね、大きな私」"

[[dialogue]]
speaker = "unk"
# メルエルの告白の後、その様子を黙って見ていた小さなメルエルが口を開く。
line = "メルエルの告白の後、その様子を黙って見ていた小さなメルエルが口を開く。"

[[dialogue]]
speaker = "メルエル"
# 「あなたが私の気持ちを後押ししてくれたからだよ、ちっちゃな私」
line = "「あなたが私の気持ちを後押ししてくれたからだよ、ちっちゃな私」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「そんな風に言われたら、私の完敗だよ」
line = "「そんな風に言われたら、私の完敗だよ」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「でも……これからも勇気を出さずにまごまごしてたら、また私が出てきて、会長くんにアプローチしちゃうんだからね！」
line = "「でも……これからも勇気を出さずにまごまごしてたら、また私が出てきて、会長くんにアプローチしちゃうんだからね！」"

[[dialogue]]
speaker = "メルエル"
# 「うん。これからも全力で頑張るよ。……ううん、違うね――」
line = "「うん。これからも全力で頑張るよ。……ううん、違うね――」"

[[dialogue]]
speaker = "メルエル"
# 「これからも一緒に頑張ろう！」
line = "「これからも一緒に頑張ろう！」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「そうだね。私たち２人、抱いている気持ちは、同じものだから――」
line = "「そうだね。私たち２人、抱いている気持ちは、同じものだから――」"

[[dialogue]]
speaker = "unk"
# そうして、笑顔を浮かべて握手を交わす２人。
line = "そうして、笑顔を浮かべて握手を交わす２人。"

[[dialogue]]
speaker = "unk"
# すると、２人のメルエルの体は、眩い白い光に包まれて――
line = "すると、２人のメルエルの体は、眩い白い光に包まれて――"

[[dialogue]]
speaker = "unk"
# 収まった後には、小さな天使の姿はなく。
line = "収まった後には、小さな天使の姿はなく。"

[[dialogue]]
speaker = "メルエル"
# 「告白する勇気をくれて、ありがとう。ちっちゃな昔の私」
line = "「告白する勇気をくれて、ありがとう。ちっちゃな昔の私」"

[[dialogue]]
speaker = "unk"
# 元の１人へと戻ったメルエルは、大切なものを心にしまうように、胸に両手を重ねながら微笑むのだった。
line = "元の１人へと戻ったメルエルは、大切なものを心にしまうように、胸に両手を重ねながら微笑むのだった。"
