[[dialogue]]
speaker = "unk"
# アルテとプトラが流星市国に来てから数日が経過した。
line = "アルテとプトラが流星市国に来てから数日が経過した。"

[[dialogue]]
speaker = "unk"
# クマロボたちの襲撃は何度か受けていたが、アルテもプトラも力の使い方に慣れてきたのか、難なく撃退することに成功している。
line = "クマロボたちの襲撃は何度か受けていたが、アルテもプトラも力の使い方に慣れてきたのか、難なく撃退することに成功している。"

[[dialogue]]
speaker = "unk"
# そして、こちらの生活にすっかり馴染んだようで、日々を退屈せずに過ごしていた。
line = "そして、こちらの生活にすっかり馴染んだようで、日々を退屈せずに過ごしていた。"

[[dialogue]]
speaker = "アルテ"
# 「ふむふむ……流星市国・焼肉百選……」
line = "「ふむふむ……流星市国・焼肉百選……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「って、ちょっと慣れ過ぎじゃない？」
line = "「って、ちょっと慣れ過ぎじゃない？」"

[[dialogue]]
speaker = "アルテ"
# 「順応性は高い方ですから」
line = "「順応性は高い方ですから」"

[[dialogue]]
speaker = "unk"
# 何を読んでるの？
line = "何を読んでるの？"

[[dialogue]]
speaker = "アルテ"
# 「『流星ウォーカー』です。街の情報が詰まっていて便利なんですよ」
line = "「『流星ウォーカー』です。街の情報が詰まっていて便利なんですよ」"

[[dialogue]]
speaker = "unk"
# 満喫してるな～
line = "満喫してるな～"

[[dialogue]]
speaker = "アルテ"
# 「せっかくこんな珍しい世界に来たのですから、帰ったら館長たちにしこたま自慢してあげようと思います」
line = "「せっかくこんな珍しい世界に来たのですから、帰ったら館長たちにしこたま自慢してあげようと思います」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それで、どこか興味を引かれるところはあるのかしら？」
line = "「それで、どこか興味を引かれるところはあるのかしら？」"

[[dialogue]]
speaker = "アルテ"
# 「色々ありますが一番は……ここでしょうか？」
line = "「色々ありますが一番は……ここでしょうか？」"

[[dialogue]]
speaker = "unk"
# 秋葉原？
line = "秋葉原？"

[[dialogue]]
speaker = "アルテ"
# 「この世界に来た時から気になっていたんですよね、街中に絵画が溢れていることが」
line = "「この世界に来た時から気になっていたんですよね、街中に絵画が溢れていることが」"

[[dialogue]]
speaker = "アルテ"
# 「道を歩けば建物のあちこちに絵が貼り付けられている。これはアテネスでは見られない景色です」
line = "「道を歩けば建物のあちこちに絵が貼り付けられている。これはアテネスでは見られない景色です」"

[[dialogue]]
speaker = "アルテ"
# 「秋葉原の街は、特にそういった絵画──『イラスト』と呼ぶようですけど、それで埋め尽くされているという話ではないですか」
line = "「秋葉原の街は、特にそういった絵画──『イラスト』と呼ぶようですけど、それで埋め尽くされているという話ではないですか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「アルテが藝術家っぽいことを言ってる！？」
line = "「アルテが藝術家っぽいことを言ってる！？」"

[[dialogue]]
speaker = "アルテ"
# 「私は正真正銘の、しかも一流の藝術家なんですけど……記憶力が欠如しているのですか？」
line = "「私は正真正銘の、しかも一流の藝術家なんですけど……記憶力が欠如しているのですか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だって、こっちの世界に来て絵を描いてるところを見たことないし」
line = "「だって、こっちの世界に来て絵を描いてるところを見たことないし」"

[[dialogue]]
speaker = "アルテ"
# 「私はその気にならないと筆はとらない主義なので」
line = "「私はその気にならないと筆はとらない主義なので」"

[[dialogue]]
speaker = "ヴィーナス"
# 「おお～、またまた藝術家っぽいことを！」
line = "「おお～、またまた藝術家っぽいことを！」"

[[dialogue]]
speaker = "アルテ"
# 「だから私は正真正銘の藝術家だと言っているでしょう！」
line = "「だから私は正真正銘の藝術家だと言っているでしょう！」"

[[dialogue]]
speaker = "unk"
# それじゃ今日は秋葉原に行ってみる？
line = "それじゃ今日は秋葉原に行ってみる？"

[[dialogue]]
speaker = "アルテ"
# 「ええ、案内をお願いします」
line = "「ええ、案内をお願いします」"

[[dialogue]]
speaker = "ヴィーナス"
# 「せっかくだからフィオナたちにも連絡してみましょう♪」
line = "「せっかくだからフィオナたちにも連絡してみましょう♪」"

[[dialogue]]
speaker = "プトラ"
# 「うわー、ここが秋葉原！　他の街とはちょっと雰囲気が違うね」
line = "「うわー、ここが秋葉原！　他の街とはちょっと雰囲気が違うね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「プトラもすっかりこっちの世界に慣れたわね～」
line = "「プトラもすっかりこっちの世界に慣れたわね～」"

[[dialogue]]
speaker = "プトラ"
# 「えへへ、みんなに色々連れてってもらったから」
line = "「えへへ、みんなに色々連れてってもらったから」"

[[dialogue]]
speaker = "プトラ"
# 「あっ、ゲームセンターがいっぱいあるよ！　クレーンゲームはあるかな？」
line = "「あっ、ゲームセンターがいっぱいあるよ！　クレーンゲームはあるかな？」"

[[dialogue]]
speaker = "アポロ"
# 「クレーンゲームが好きなのか？」
line = "「クレーンゲームが好きなのか？」"

[[dialogue]]
speaker = "プトラ"
# 「うん、あの釣り上げる感じがね、海の女の血を滾らせるんだよ。うぃーん、えーいって♪」
line = "「うん、あの釣り上げる感じがね、海の女の血を滾らせるんだよ。うぃーん、えーいって♪」"

[[dialogue]]
speaker = "フィオナ"
# 「あっちの建物は１フロアまるまるクレーンゲームですよ」
line = "「あっちの建物は１フロアまるまるクレーンゲームですよ」"

[[dialogue]]
speaker = "プトラ"
# 「１フロア全部？　すごい！　行ってみたい！」
line = "「１フロア全部？　すごい！　行ってみたい！」"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ、じゃ少し遊んでいきましょうか」
line = "「ふふ、じゃ少し遊んでいきましょうか」"

[[dialogue]]
speaker = "プトラ"
# 「えへへ～、おっさかなさん、おっさかなさん♪　おっきなおっきなおっさかなさん♪」
line = "「えへへ～、おっさかなさん、おっさかなさん♪　おっきなおっきなおっさかなさん♪」"

[[dialogue]]
speaker = "フィオナ"
# 「大きいのが取れてよかったですね」
line = "「大きいのが取れてよかったですね」"

[[dialogue]]
speaker = "プトラ"
# 「アドバイスしてもらったおかげだよ～、ひとりじゃ絶対に無理だった」
line = "「アドバイスしてもらったおかげだよ～、ひとりじゃ絶対に無理だった」"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロトのアドバイスも的確だったわね～」
line = "「クロトのアドバイスも的確だったわね～」"

[[dialogue]]
speaker = "プトラ"
# 「うんうん、すごく分かりやすかったよ」
line = "「うんうん、すごく分かりやすかったよ」"

[[dialogue]]
speaker = "unk"
# さっきからアルテが大人しい気がするけど
line = "さっきからアルテが大人しい気がするけど"

[[dialogue]]
speaker = "アルテ"
# 「ええ……」
line = "「ええ……」"

[[dialogue]]
speaker = "アルテ"
# 「あちこちに何気なく飾られているイラストに、技術の粋が詰め込まれていて……興味深いです」
line = "「あちこちに何気なく飾られているイラストに、技術の粋が詰め込まれていて……興味深いです」"

[[dialogue]]
speaker = "アルテ"
# 「とはいえ、私が本気になってしまったら、この秋葉原でも頂点を取ること間違いなしですけどね」
line = "「とはいえ、私が本気になってしまったら、この秋葉原でも頂点を取ること間違いなしですけどね」"

[[dialogue]]
speaker = "プトラ"
# 「さすが藝術家さん、そういうのも分かっちゃうんだね」
line = "「さすが藝術家さん、そういうのも分かっちゃうんだね」"

[[dialogue]]
speaker = "アルテ"
# 「私からすれば、まるで町全体が美術館のようです」
line = "「私からすれば、まるで町全体が美術館のようです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「少しはインスピレーションが湧いてきたかしら？　言ってくれれば画材なんかはすぐに用意してあげるわよ」
line = "「少しはインスピレーションが湧いてきたかしら？　言ってくれれば画材なんかはすぐに用意してあげるわよ」"

[[dialogue]]
speaker = "アルテ"
# 「残念ですが。技術は素晴らしいと思いますが、それとこれとは別なので」
line = "「残念ですが。技術は素晴らしいと思いますが、それとこれとは別なので」"

[[dialogue]]
speaker = "ヴィーナス"
# 「もったいぶるわね～」
line = "「もったいぶるわね～」"

[[dialogue]]
speaker = "プトラ"
# 「あたしもアルテの絵、見てみたいな」
line = "「あたしもアルテの絵、見てみたいな」"

[[dialogue]]
speaker = "unk"
# 気が向いたら描いてみてよ
line = "気が向いたら描いてみてよ"

[[dialogue]]
speaker = "アルテ"
# 「そうですね……まぁ、気が向いたら、ということで」
line = "「そうですね……まぁ、気が向いたら、ということで」"

[[dialogue]]
speaker = "クマロボ"
# 「クマァーーーーーーーーーー！！！！！！」
line = "「クマァーーーーーーーーーー！！！！！！」"

[[dialogue]]
speaker = "アポロ"
# 「性懲りもないぜ。いつものみたいに、かるーくぶっ飛ばしてやる！　変身！！」
line = "「性懲りもないぜ。いつものみたいに、かるーくぶっ飛ばしてやる！　変身！！」"

[[dialogue]]
speaker = "プトラ"
# 「アルテ、あたしたちも！」
line = "「アルテ、あたしたちも！」"

[[dialogue]]
speaker = "アルテ"
# 「えー、面倒なのでみんなに任せます。私は応援してますよ」
line = "「えー、面倒なのでみんなに任せます。私は応援してますよ」"

[[dialogue]]
speaker = "プトラ"
# 「そんなこと言わずに、さあ！」
line = "「そんなこと言わずに、さあ！」"

[[dialogue]]
speaker = "アルテ"
# 「はいはい、わかりました」
line = "「はいはい、わかりました」"
