[[dialogue]]
speaker = "ヒマワリ"
# 「──というわけで！　首尾よく九浄家に潜入することができたんですよ」
line = "「──というわけで！　首尾よく九浄家に潜入することができたんですよ」"

[[dialogue]]
speaker = "依頼人Ａ"
# 「なんと、あの難攻不落の九浄家に？」
line = "「なんと、あの難攻不落の九浄家に？」"

[[dialogue]]
speaker = "ミウ"
# 「はい。問題の人工戦闘服も確認しましたし、次回はより詳細な情報を報告することが出来ると思います」
line = "「はい。問題の人工戦闘服も確認しましたし、次回はより詳細な情報を報告することが出来ると思います」"

[[dialogue]]
speaker = "依頼人Ａ"
# 「ふむ、それは有難い」
line = "「ふむ、それは有難い」"

[[dialogue]]
speaker = "依頼人Ｂ"
# 「ところで……キミらのその服は？」
line = "「ところで……キミらのその服は？」"

[[dialogue]]
speaker = "ヒマワリ"
# 「へへ～、可愛いでしょ？　今回の任務のためにお揃いで用意した服なんですよ♪」
line = "「へへ～、可愛いでしょ？　今回の任務のためにお揃いで用意した服なんですよ♪」"

[[dialogue]]
speaker = "ミウ"
# 「実は私たちの衣装を九浄家当主のヘレナさんが気に入ったようで、この衣装を元に新たな人工戦闘服を作ってもらえることになりました」
line = "「実は私たちの衣装を九浄家当主のヘレナさんが気に入ったようで、この衣装を元に新たな人工戦闘服を作ってもらえることになりました」"

[[dialogue]]
speaker = "依頼人Ａ"
# 「ほう！　ならば、君たちのその人工戦闘服を分析すれば──」
line = "「ほう！　ならば、君たちのその人工戦闘服を分析すれば──」"

[[dialogue]]
speaker = "ミウ"
# 「残念ながら私たちの人工戦闘服がいつ完成するか、という話は聞かされていないんです」
line = "「残念ながら私たちの人工戦闘服がいつ完成するか、という話は聞かされていないんです」"

[[dialogue]]
speaker = "ミウ"
# 「それに私たちの人工戦闘服に、件の危険な新技術が使用されるとは限りませんから」
line = "「それに私たちの人工戦闘服に、件の危険な新技術が使用されるとは限りませんから」"

[[dialogue]]
speaker = "依頼人Ａ"
# 「う、うむ……その通り、だな……」
line = "「う、うむ……その通り、だな……」"

[[dialogue]]
speaker = "依頼人Ｂ"
# 「しかし、九浄家のみならず、桜十路家まで絡んでいるとは……ますますもってきな臭いではないか」
line = "「しかし、九浄家のみならず、桜十路家まで絡んでいるとは……ますますもってきな臭いではないか」"

[[dialogue]]
speaker = "ヒマワリ"
# 「あたしたちもまさかエルゼ先輩がいて、戦うことになるとは思わなかったですよ」
line = "「あたしたちもまさかエルゼ先輩がいて、戦うことになるとは思わなかったですよ」"

[[dialogue]]
speaker = "ヒマワリ"
# 「いきなり攻撃を仕掛けられましたからね。しかもその一撃が超強力で……」
line = "「いきなり攻撃を仕掛けられましたからね。しかもその一撃が超強力で……」"

[[dialogue]]
speaker = "ミウ"
# 「エルデリーゼ先輩の実力もさることながら、あの人工戦闘服に強い力が備わっていることは間違いなさそうです」
line = "「エルデリーゼ先輩の実力もさることながら、あの人工戦闘服に強い力が備わっていることは間違いなさそうです」"

[[dialogue]]
speaker = "ミウ"
# 「詳細な性能については引き続き探ってゆきますので、もう少しお時間をください」
line = "「詳細な性能については引き続き探ってゆきますので、もう少しお時間をください」"

[[dialogue]]
speaker = "依頼人Ａ"
# 「わかった。では引き続き、よろしくお願いしますよ。……では、我々はこれで」
line = "「わかった。では引き続き、よろしくお願いしますよ。……では、我々はこれで」"

[[dialogue]]
speaker = "unk"
# 依頼人たちは小さく頭を下げ、ゴールデングースのアジトから去っていった。
line = "依頼人たちは小さく頭を下げ、ゴールデングースのアジトから去っていった。"

[[dialogue]]
speaker = "ヒマワリ"
# 「一時はどうなるかと思ったけど上手くいってるね。依頼人さんもあたしたちのこと見直してくれたみたいだし」
line = "「一時はどうなるかと思ったけど上手くいってるね。依頼人さんもあたしたちのこと見直してくれたみたいだし」"

[[dialogue]]
speaker = "ミウ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ヒマワリ"
# 「上手くいったらセナリィ社長も喜んでくれるだろうなー……ってどうしたの、ミウ。ちょっと怖い顔になってるよ？」
line = "「上手くいったらセナリィ社長も喜んでくれるだろうなー……ってどうしたの、ミウ。ちょっと怖い顔になってるよ？」"

[[dialogue]]
speaker = "ミウ"
# 「ううん、なんでもないよ。あっ、そろそろ九浄家にお勤めに行く時間だね。ヒマワリちゃん、準備しよう」
line = "「ううん、なんでもないよ。あっ、そろそろ九浄家にお勤めに行く時間だね。ヒマワリちゃん、準備しよう」"

[[dialogue]]
speaker = "ヒマワリ"
# 「九浄家での初仕事、ドキワクだね！」
line = "「九浄家での初仕事、ドキワクだね！」"

[[dialogue]]
speaker = "ミウ"
# 「ふふ、楽しみにするのもいいけど、本来の目的を忘れないようにしないとね」
line = "「ふふ、楽しみにするのもいいけど、本来の目的を忘れないようにしないとね」"

[[dialogue]]
speaker = "ヒマワリ"
# 「そうだったー。任務、任務」
line = "「そうだったー。任務、任務」"

[[dialogue]]
speaker = "依頼人Ａ"
# 「てっきり、早々に泣き言を漏らすと思っていたのだがな。小娘と思っていたが、なかなかどうして上手くやってくれている」
line = "「てっきり、早々に泣き言を漏らすと思っていたのだがな。小娘と思っていたが、なかなかどうして上手くやってくれている」"

[[dialogue]]
speaker = "依頼人Ｂ"
# 「本当に機密情報を入手してくれれば、それもよし。失敗したとしても、我々の作戦の体のいいカムフラージュになってくれることでしょう」
line = "「本当に機密情報を入手してくれれば、それもよし。失敗したとしても、我々の作戦の体のいいカムフラージュになってくれることでしょう」"

[[dialogue]]
speaker = "依頼人Ａ"
# 「──ああ、私だ。例の件についてだが──」
line = "「──ああ、私だ。例の件についてだが──」"
