[[dialogue]]
speaker = "unk"
# セシアと話していたところにやって来た、クリスマス衣装のフ二とルルカ。
line = "セシアと話していたところにやって来た、クリスマス衣装のフ二とルルカ。"

[[dialogue]]
speaker = "ルルカ"
# 「ねぇねぇ、どうかな、お兄ちゃん？　クリスマスフォーム、似合ってる～？」
line = "「ねぇねぇ、どうかな、お兄ちゃん？　クリスマスフォーム、似合ってる～？」"

[[dialogue]]
speaker = "フェニエル"
# 「セシアちゃんのプレゼント配りをお手伝いするということで、ヘレナ様が私たちの衣装も作って下さったんです」
line = "「セシアちゃんのプレゼント配りをお手伝いするということで、ヘレナ様が私たちの衣装も作って下さったんです」"

[[dialogue]]
speaker = "unk"
# ２人ともすごくかわいい！　似合ってるよ！
line = "２人ともすごくかわいい！　似合ってるよ！"

[[dialogue]]
speaker = "ルルカ"
# 「えへへ～♪　ありがとう、お兄ちゃん♪」
line = "「えへへ～♪　ありがとう、お兄ちゃん♪」"

[[dialogue]]
speaker = "unk"
# 彼女は新星学園１年生『<ruby=うみのべ>海野辺</ruby>ルルカ』。
line = "彼女は新星学園１年生『<ruby>海野辺<rt>うみのべ</rt></ruby>ルルカ』。"

[[dialogue]]
speaker = "unk"
# プリマステラではないため、星騎士としては目立った活躍はないルルカだが、彼女には大きな秘密があり……
line = "プリマステラではないため、星騎士としては目立った活躍はないルルカだが、彼女には大きな秘密があり……"

[[dialogue]]
speaker = "unk"
# 実は周りには秘密で、人気Ｖチューバー『<ruby=うしお>汐</ruby>ルカルカ』として活動している。最近は調子が良く、チャンネル登録者数も１００万人を超えそうな勢いだ。
line = "実は周りには秘密で、人気Ｖチューバー『<ruby>汐<rt>うしお</rt></ruby>ルカルカ』として活動している。最近は調子が良く、チャンネル登録者数も１００万人を超えそうな勢いだ。"

[[dialogue]]
speaker = "フェニエル"
# 「あ、ありがとうございます、会長さん……♪　えへへ♪」
line = "「あ、ありがとうございます、会長さん……♪　えへへ♪」"

[[dialogue]]
speaker = "フェニエル"
# 「会長さんに褒められると、なまら照れちゃいます……」
line = "「会長さんに褒められると、なまら照れちゃいます……」"

[[dialogue]]
speaker = "unk"
# 彼女は流星学園１年生の『フェニエル』。周りからは『フニ』という愛称で親しまれている。
line = "彼女は流星学園１年生の『フェニエル』。周りからは『フニ』という愛称で親しまれている。"

[[dialogue]]
speaker = "unk"
# 後天的に星力を獲得したという珍しい体質で、出会った当時はまだ星術の扱いもつたなく、ルルカと同じ非プリマステラだ。
line = "後天的に星力を獲得したという珍しい体質で、出会った当時はまだ星術の扱いもつたなく、ルルカと同じ非プリマステラだ。"

[[dialogue]]
speaker = "unk"
# しかし、あれから時間も経ち、今では流星寮の寮長『千園寺ヒルディオーネ』先輩の下でその実力をメキメキと伸ばしている。
line = "しかし、あれから時間も経ち、今では流星寮の寮長『千園寺ヒルディオーネ』先輩の下でその実力をメキメキと伸ばしている。"

[[dialogue]]
speaker = "unk"
# 成長率も含めての評価だが、『次期寮長候補』なんて言われることもあるくらいになっていた。
line = "成長率も含めての評価だが、『次期寮長候補』なんて言われることもあるくらいになっていた。"

[[dialogue]]
speaker = "フェニエル"
# 「でも、このクリスマスフォーム、本当にかわいい衣装ですっ。私のは『マッチ売りの女の子』がモチーフみたいで」
line = "「でも、このクリスマスフォーム、本当にかわいい衣装ですっ。私のは『マッチ売りの女の子』がモチーフみたいで」"

[[dialogue]]
speaker = "ルルカ"
# 「あたしのは『クリスマスツリー』がモチーフなんだって！　ほら、頭に星が付いてるでしょ？」
line = "「あたしのは『クリスマスツリー』がモチーフなんだって！　ほら、頭に星が付いてるでしょ？」"

[[dialogue]]
speaker = "フェニエル"
# 「ルルカちゃんの衣装、なまらかわいいです！」
line = "「ルルカちゃんの衣装、なまらかわいいです！」"

[[dialogue]]
speaker = "ルルカ"
# 「いやいや、フニちゃんの方がもっとかわいいよ～♪」
line = "「いやいや、フニちゃんの方がもっとかわいいよ～♪」"

[[dialogue]]
speaker = "ルルカ"
# 「こう、フニちゃんが本来持っている健気さとマッチして、庇護欲を掻き立てられる感じがするんだよね～！　マッチだけに！」
line = "「こう、フニちゃんが本来持っている健気さとマッチして、庇護欲を掻き立てられる感じがするんだよね～！　マッチだけに！」"

[[dialogue]]
speaker = "フェニエル"
# 「あぅ……な、なしてそんなこと言うんしょや、ルルカちゃんっ。　なまら恥ずかしいべさ……！」
line = "「あぅ……な、なしてそんなこと言うんしょや、ルルカちゃんっ。　なまら恥ずかしいべさ……！」"

[[dialogue]]
speaker = "ルルカ"
# 「あぁ～<emoji=heart04>　時々出る方言＋その頭の羽で顔を隠しちゃう仕草がまた、すごく可愛いんだよね～♪」
line = "「あぁ～<emoji=heart04>　時々出る方言＋その頭の羽で顔を隠しちゃう仕草がまた、すごく可愛いんだよね～♪」"

[[dialogue]]
speaker = "ルルカ"
# 「フニちゃんもＶチューバーやれば、絶対にバズって売れるよ！　その一芸だけでやっていけるね！」
line = "「フニちゃんもＶチューバーやれば、絶対にバズって売れるよ！　その一芸だけでやっていけるね！」"

[[dialogue]]
speaker = "ルルカ"
# 「って……ハッ！？　違うよ！？　『フニちゃんも』って言ったけど、別にあたしがＶチューバーやってるって意味ではなくてね！？」
line = "「って……ハッ！？　違うよ！？　『フニちゃんも』って言ったけど、別にあたしがＶチューバーやってるって意味ではなくてね！？」"

[[dialogue]]
speaker = "セシア"
# 「他意はないのだけれど……」
line = "「他意はないのだけれど……」"

[[dialogue]]
speaker = "セシア"
# 「最近人気急上昇中の『汐ルカルカ』、ルルカにお声がそっくりね？」
line = "「最近人気急上昇中の『汐ルカルカ』、ルルカにお声がそっくりね？」"

[[dialogue]]
speaker = "unk"
# 他意がない、ってなんだっけ！？
line = "他意がない、ってなんだっけ！？"

[[dialogue]]
speaker = "セシア"
# 「冗談よ、会長。わたくしたちは大丈夫だから」
line = "「冗談よ、会長。わたくしたちは大丈夫だから」"

[[dialogue]]
speaker = "セシア"
# 「わたくしもフニも、ルルカがＶチューバーをやっていることは、もうすでに知っているわ」
line = "「わたくしもフニも、ルルカがＶチューバーをやっていることは、もうすでに知っているわ」"

[[dialogue]]
speaker = "unk"
# えっ！？　そうなの？
line = "えっ！？　そうなの？"

[[dialogue]]
speaker = "フェニエル"
# 「はい。１週間前にセシアちゃんに誘われて、プレゼント配りをお手伝いすることが決まって。それから仲良くなろうと、３人で集まって話している内に……」
line = "「はい。１週間前にセシアちゃんに誘われて、プレゼント配りをお手伝いすることが決まって。それから仲良くなろうと、３人で集まって話している内に……」"

[[dialogue]]
speaker = "ルルカ"
# 「そうだった！　あたしがうっかり口走っちゃって、２人にはもうバレちゃってるんだった。危ない、セーフ……！」
line = "「そうだった！　あたしがうっかり口走っちゃって、２人にはもうバレちゃってるんだった。危ない、セーフ……！」"

[[dialogue]]
speaker = "unk"
# 何もセーフじゃないが……？
line = "何もセーフじゃないが……？"

[[dialogue]]
speaker = "ルルカ"
# 「……てへっ☆」
line = "「……てへっ☆」"

[[dialogue]]
speaker = "unk"
# それから俺たちは、クリスマスに向けての相談を始めることになった。
line = "それから俺たちは、クリスマスに向けての相談を始めることになった。"

[[dialogue]]
speaker = "unk"
# 聞けば今回のクリスマスは、ヒルディオーネ先輩と新星寮の寮長――『マム』こと『妃竜院マハムート』先輩から、寮への立ち入り許可を既に貰っているとのこと。
line = "聞けば今回のクリスマスは、ヒルディオーネ先輩と新星寮の寮長――『マム』こと『妃竜院マハムート』先輩から、寮への立ち入り許可を既に貰っているとのこと。"

[[dialogue]]
speaker = "unk"
# クリスマス当日にはそれぞれの寮へ出向いて、プレゼントを配る手はずになっているらしい。
line = "クリスマス当日にはそれぞれの寮へ出向いて、プレゼントを配る手はずになっているらしい。"

[[dialogue]]
speaker = "セシア"
# 「――それで会長。今回のクリスマスプレゼントは、手作りアクセサリーを配ろうと思っているの」
line = "「――それで会長。今回のクリスマスプレゼントは、手作りアクセサリーを配ろうと思っているの」"

[[dialogue]]
speaker = "セシア"
# 「わたくしのクリスマスフォームには、紅明ママと同じ『イメージしたプレゼントをサンタの袋から取り出す』能力があるわ」
line = "「わたくしのクリスマスフォームには、紅明ママと同じ『イメージしたプレゼントをサンタの袋から取り出す』能力があるわ」"

[[dialogue]]
speaker = "セシア"
# 「だから最初は、前回と同じように『その人が欲しいもの』をその場で作って回ろうと考えていたのだけれど……」
line = "「だから最初は、前回と同じように『その人が欲しいもの』をその場で作って回ろうと考えていたのだけれど……」"

[[dialogue]]
speaker = "フェニエル"
# 「ヒルディーお姉様から、『理由なく高価なプレゼントを、一方的に配るのはよくない』という意見を頂いたんです」
line = "「ヒルディーお姉様から、『理由なく高価なプレゼントを、一方的に配るのはよくない』という意見を頂いたんです」"

[[dialogue]]
speaker = "unk"
# さすがヒルディオーネ先輩だ。一理ある
line = "さすがヒルディオーネ先輩だ。一理ある"

[[dialogue]]
speaker = "unk"
# セシアをよく知らない人からしたら、貰う側としても理由のよく分からない高価なプレゼントは喜びよりも困惑が勝つだろう。
line = "セシアをよく知らない人からしたら、貰う側としても理由のよく分からない高価なプレゼントは喜びよりも困惑が勝つだろう。"

[[dialogue]]
speaker = "unk"
# 逆に、今後セシアに頼めば何でもタダで貰えると思われても困る。何にせよあまりいいことではない。
line = "逆に、今後セシアに頼めば何でもタダで貰えると思われても困る。何にせよあまりいいことではない。"

[[dialogue]]
speaker = "ルルカ"
# 「だから、あたしたち３人で相談して、今回のプレゼントは手作りすることに決めたんだ。フニちゃんの提案で――」
line = "「だから、あたしたち３人で相談して、今回のプレゼントは手作りすることに決めたんだ。フニちゃんの提案で――」"

[[dialogue]]
speaker = "フェニエル"
# 「ビーズを使った、クリスマスらしい色合いの手作りブレスレットとか、どうかなって……」
line = "「ビーズを使った、クリスマスらしい色合いの手作りブレスレットとか、どうかなって……」"

[[dialogue]]
speaker = "フェニエル"
# 「昔、私が北海道にいた時……村のみんなに作って渡したら、すごく喜んでくれたんです」
line = "「昔、私が北海道にいた時……村のみんなに作って渡したら、すごく喜んでくれたんです」"

[[dialogue]]
speaker = "フェニエル"
# 「素材としても安物ですし、全然、大したものじゃないんですけど……その分、受け取るのも困らないんじゃないかなって」
line = "「素材としても安物ですし、全然、大したものじゃないんですけど……その分、受け取るのも困らないんじゃないかなって」"

[[dialogue]]
speaker = "フェニエル"
# 「流星と新星の生徒は、クリスマスでも任務や仕事に忙しい方が、沢山います。そういう方々にも、ちょっとでもクリスマスを感じてもらえたらなって……」
line = "「流星と新星の生徒は、クリスマスでも任務や仕事に忙しい方が、沢山います。そういう方々にも、ちょっとでもクリスマスを感じてもらえたらなって……」"

[[dialogue]]
speaker = "unk"
# フニのもてなしの心、きっと伝わると思う
line = "フニのもてなしの心、きっと伝わると思う"

[[dialogue]]
speaker = "セシア"
# 「ふふっ♪　『メリークリスマス』の気持ちを込めてプレゼントを用意することが、一番大事なんだってわたくしも思うの」
line = "「ふふっ♪　『メリークリスマス』の気持ちを込めてプレゼントを用意することが、一番大事なんだってわたくしも思うの」"

[[dialogue]]
speaker = "セシア"
# 「前回のクリスマスのように、沢山のヒトに笑顔になってもらえるように頑張るわ」
line = "「前回のクリスマスのように、沢山のヒトに笑顔になってもらえるように頑張るわ」"

[[dialogue]]
speaker = "ルルカ"
# 「あたしは正直、クリスマスプレゼントを配る経験とか初めてだから、不安もあるんだけど……」
line = "「あたしは正直、クリスマスプレゼントを配る経験とか初めてだから、不安もあるんだけど……」"

[[dialogue]]
speaker = "ルルカ"
# 「でも、前回セッシーちゃん達からプレゼント貰った時、すごく嬉しかったんだ！」
line = "「でも、前回セッシーちゃん達からプレゼント貰った時、すごく嬉しかったんだ！」"

[[dialogue]]
speaker = "ルルカ"
# 「だから、クリスマスプレゼントを配るからには、あたしも紅明先輩やセッシーちゃんをリスペクトして、みんなを喜ばせたいって思う！」
line = "「だから、クリスマスプレゼントを配るからには、あたしも紅明先輩やセッシーちゃんをリスペクトして、みんなを喜ばせたいって思う！」"

[[dialogue]]
speaker = "unk"
# 俺ももちろん、手伝うぞ
line = "俺ももちろん、手伝うぞ"

[[dialogue]]
speaker = "ルルカ"
# 「ありがとう、お兄ちゃん♪」
line = "「ありがとう、お兄ちゃん♪」"

[[dialogue]]
speaker = "セシア"
# 「じゃあ、会長への説明も終わったところで改めて――」
line = "「じゃあ、会長への説明も終わったところで改めて――」"

[[dialogue]]
speaker = "セシア"
# 「わたくしたち４人で、クリスマスプレゼント配りを頑張りましょう♪　せ～のっ」
line = "「わたくしたち４人で、クリスマスプレゼント配りを頑張りましょう♪　せ～のっ」"

[[dialogue]]
speaker = "全員"
# 「おー！」
line = "「おー！」"

[[dialogue]]
speaker = "unk"
# 俺たちはぐっと握った拳を上げて、かけ声と共にクリスマスの準備を開始する――
line = "俺たちはぐっと握った拳を上げて、かけ声と共にクリスマスの準備を開始する――"

[[dialogue]]
speaker = "unk"
# ふと、その時。
line = "ふと、その時。"

[[dialogue]]
speaker = "セシア"
# 「――あら？　フニ、ちょっといいかしら？」
line = "「――あら？　フニ、ちょっといいかしら？」"

[[dialogue]]
speaker = "フェニエル"
# 「はい？　セシアちゃん、どうかしましたか？」
line = "「はい？　セシアちゃん、どうかしましたか？」"

[[dialogue]]
speaker = "セシア"
# 「ちょっと、おでこを借りるわね。んっ……」
line = "「ちょっと、おでこを借りるわね。んっ……」"

[[dialogue]]
speaker = "フェニエル"
# 「ひゃっ！？　セシアちゃん、いきなりそんな、おでこをくっ付けて……！？」
line = "「ひゃっ！？　セシアちゃん、いきなりそんな、おでこをくっ付けて……！？」"

[[dialogue]]
speaker = "セシア"
# 「……フニ、あなた、ひょっとして熱があるんじゃないかしら？」
line = "「……フニ、あなた、ひょっとして熱があるんじゃないかしら？」"

[[dialogue]]
speaker = "フェニエル"
# 「……！　はい、そうかもしれません。実はちょっとだけ……」
line = "「……！　はい、そうかもしれません。実はちょっとだけ……」"

[[dialogue]]
speaker = "ルルカ"
# 「えっ、そうなの！？　フニちゃん、大丈夫！？」
line = "「えっ、そうなの！？　フニちゃん、大丈夫！？」"

[[dialogue]]
speaker = "フェニエル"
# 「あっ、いえいえ。体調が悪いとか、そんなんじゃないんです。確かにここ数日、自分でも体温が普段より高い気がしてますけど――」
line = "「あっ、いえいえ。体調が悪いとか、そんなんじゃないんです。確かにここ数日、自分でも体温が普段より高い気がしてますけど――」"

[[dialogue]]
speaker = "フェニエル"
# 「だからこそ、むしろ普段よりも体の調子が良いというか……」
line = "「だからこそ、むしろ普段よりも体の調子が良いというか……」"

[[dialogue]]
speaker = "ルルカ"
# 「体温が高いのに、調子が良い？　それってどういう……？」
line = "「体温が高いのに、調子が良い？　それってどういう……？」"

[[dialogue]]
speaker = "フェニエル"
# 「時々体温が高くなるのは――私の中にいるホウちゃんの影響なんです」
line = "「時々体温が高くなるのは――私の中にいるホウちゃんの影響なんです」"

[[dialogue]]
speaker = "セシア"
# 「ホウちゃん？」
line = "「ホウちゃん？」"

[[dialogue]]
speaker = "フェニエル"
# 「あっ、ホウちゃんっていうのは、あくまで私が呼んでるだけの愛称、なんですけど……」
line = "「あっ、ホウちゃんっていうのは、あくまで私が呼んでるだけの愛称、なんですけど……」"

[[dialogue]]
speaker = "フェニエル"
# 「私が星力を使えているのは、私の中に宿っている不死鳥――魔獣『フェニックス』が、力を貸してくれているからなんです」
line = "「私が星力を使えているのは、私の中に宿っている不死鳥――魔獣『フェニックス』が、力を貸してくれているからなんです」"

[[dialogue]]
speaker = "unk"
# そう言ってフニは、俺も今まで知らなかった秘密を明かすのだった――
line = "そう言ってフニは、俺も今まで知らなかった秘密を明かすのだった――"
