[[dialogue]]
speaker = "ヒルディオーネ"
# 「フニ、そろそろ気分は落ち着きまして？」
line = "「フニ、そろそろ気分は落ち着きまして？」"

[[dialogue]]
speaker = "フェニエル"
# 「は、はい……。申し訳ありません、お姉様。『イルソーレ』の新人として、恥ずかしい姿をさらしてしまいました……」
line = "「は、はい……。申し訳ありません、お姉様。『イルソーレ』の新人として、恥ずかしい姿をさらしてしまいました……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ええ、ええ、そうですとも。フェニエル、あなたは誇り高き『イルソーレ』の一員。相手が寮長だからと言って、『ラルーナ』の者にヘコヘコする必要などありませんわ！」
line = "「ええ、ええ、そうですとも。フェニエル、あなたは誇り高き『イルソーレ』の一員。相手が寮長だからと言って、『ラルーナ』の者にヘコヘコする必要などありませんわ！」"

[[dialogue]]
speaker = "フェニエル"
# 「わ、わかりましたっ。……ただ、『イルソーレ』と『ラルーナ』は競い合うライバルだと聞いています。寮長であるマハムート先輩には、ちゃんと敬意を表したい、です」
line = "「わ、わかりましたっ。……ただ、『イルソーレ』と『ラルーナ』は競い合うライバルだと聞いています。寮長であるマハムート先輩には、ちゃんと敬意を表したい、です」"

[[dialogue]]
speaker = "マハムート"
# 「ふっ、マムでいいわ。みんな私のことは、畏怖を持ってそう呼ぶから。……あなたのことは、フニでいいのかしら、不死鳥の天使さん？」
line = "「ふっ、マムでいいわ。みんな私のことは、畏怖を持ってそう呼ぶから。……あなたのことは、フニでいいのかしら、不死鳥の天使さん？」"

[[dialogue]]
speaker = "フェニエル"
# 「イ、イエス、マムっ」
line = "「イ、イエス、マムっ」"

[[dialogue]]
speaker = "マハムート"
# 「ふふっ。素直で可愛い転入生ね。あなたにはもったいないくらいだわ、隣のドリルロールさん？」
line = "「ふふっ。素直で可愛い転入生ね。あなたにはもったいないくらいだわ、隣のドリルロールさん？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「それを言ったら、同じ転入生である緋宮会長も、あなたの手に余る逸材でしてよ、リトルマム」
line = "「それを言ったら、同じ転入生である緋宮会長も、あなたの手に余る逸材でしてよ、リトルマム」"

[[dialogue]]
speaker = "フェニエル"
# 「はわわわっ……お姉様とマムが、私のせいで喧嘩を……！？」
line = "「はわわわっ……お姉様とマムが、私のせいで喧嘩を……！？」"

[[dialogue]]
speaker = "unk"
# 大丈夫、２人の喧嘩は挨拶みたいなものだから
line = "大丈夫、２人の喧嘩は挨拶みたいなものだから"

[[dialogue]]
speaker = "フェニエル"
# 「ぴぃ！？　それってどんな関係なんですかぁ。ぜ、全然わかんないですぅ……っ」
line = "「ぴぃ！？　それってどんな関係なんですかぁ。ぜ、全然わかんないですぅ……っ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ふっ、どうやら『学園対抗杯』の月次報告書をまとめていたようですけれど、その成果を見ればどちらがより優れた寮長であるかは一目瞭然……」
line = "「ふっ、どうやら『学園対抗杯』の月次報告書をまとめていたようですけれど、その成果を見ればどちらがより優れた寮長であるかは一目瞭然……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「今月も月間成績では流星学園の圧勝……！　ライバル校として新設された新星学園とはいえ、伝統ある流星には手も足も出ないってことじゃなくて？」
line = "「今月も月間成績では流星学園の圧勝……！　ライバル校として新設された新星学園とはいえ、伝統ある流星には手も足も出ないってことじゃなくて？」"

[[dialogue]]
speaker = "マハムート"
# 「嘘おっしゃい。確かに今月は新星側のスコアが負けているけれど、大げさに言うほどの差じゃないでしょう」
line = "「嘘おっしゃい。確かに今月は新星側のスコアが負けているけれど、大げさに言うほどの差じゃないでしょう」"

[[dialogue]]
speaker = "マハムート"
# 「そもそも、こっちは御前試合があって、新星側の星徒会長が交代してるのよ。新体制も整いきっていないのにもうこのスコアなんだから、来月が楽しみね？」
line = "「そもそも、こっちは御前試合があって、新星側の星徒会長が交代してるのよ。新体制も整いきっていないのにもうこのスコアなんだから、来月が楽しみね？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ふ、ふふふ……。全く、ああ言えばこう言う……事実負けている癖に、口の減らない寮長ですわ！」
line = "「ふ、ふふふ……。全く、ああ言えばこう言う……事実負けている癖に、口の減らない寮長ですわ！」"

[[dialogue]]
speaker = "マハムート"
# 「ふふん。長たるもの、常に余裕は必要よ。……でもそうね、白黒付けるのに学年末が待ちきれないのなら、１週間後の月間報告の数字で優劣を競ってもいいわ」
line = "「ふふん。長たるもの、常に余裕は必要よ。……でもそうね、白黒付けるのに学年末が待ちきれないのなら、１週間後の月間報告の数字で優劣を競ってもいいわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「……なんですって？」
line = "「……なんですって？」"

[[dialogue]]
speaker = "マハムート"
# 「負けた方は勝った方の寮に、なにか大切なものを差し出す、っていうのはどうかしら？」
line = "「負けた方は勝った方の寮に、なにか大切なものを差し出す、っていうのはどうかしら？」"

[[dialogue]]
speaker = "unk"
# マム、学園対抗杯は寮対抗じゃないですよ
line = "マム、学園対抗杯は寮対抗じゃないですよ"

[[dialogue]]
speaker = "マハムート"
# 「なによ、いいじゃない。……学園対抗杯の勝利にこだわっているのは、新星学園生全員ではないんだもの」
line = "「なによ、いいじゃない。……学園対抗杯の勝利にこだわっているのは、新星学園生全員ではないんだもの」"

[[dialogue]]
speaker = "マハムート"
# 「特に影響が大きいのは、次年度の寮予算に影響がある寮生。私はもう卒業だけれど、私が寮長であるうちに、『ラルーナ』に勝利をもたらして見せるわ」
line = "「特に影響が大きいのは、次年度の寮予算に影響がある寮生。私はもう卒業だけれど、私が寮長であるうちに、『ラルーナ』に勝利をもたらして見せるわ」"

[[dialogue]]
speaker = "unk"
# マムに教えてもらった戦績によると、ここ３年ほど、新星学園は学園対抗杯に敗れているらしい。それは、マムと千園寺先輩が寮長になった去年も含めて、だ。
line = "マムに教えてもらった戦績によると、ここ３年ほど、新星学園は学園対抗杯に敗れているらしい。それは、マムと千園寺先輩が寮長になった去年も含めて、だ。"

[[dialogue]]
speaker = "フェニエル"
# 「そ、そ、そ……それって！」
line = "「そ、そ、そ……それって！」"

[[dialogue]]
speaker = "フェニエル"
# 「私と会長さんで、『花いちもんめ』……ってことでしょうか！？」
line = "「私と会長さんで、『花いちもんめ』……ってことでしょうか！？」"

[[dialogue]]
speaker = "マハムート"
# 「ん……？」
line = "「ん……？」"

[[dialogue]]
speaker = "フェニエル"
# 「勝負に負けたら、私は新星寮に……でもでも、勝負に勝ったら、会長さんを流星寮にいただける……ってことですね！？」
line = "「勝負に負けたら、私は新星寮に……でもでも、勝負に勝ったら、会長さんを流星寮にいただける……ってことですね！？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「なっ……！？　なんて恐ろしい勝負を考えるんですの、妃竜院マハムート……！！」
line = "「なっ……！？　なんて恐ろしい勝負を考えるんですの、妃竜院マハムート……！！」"

[[dialogue]]
speaker = "マハムート"
# 「んん……？」
line = "「んん……？」"

[[dialogue]]
speaker = "フェニエル"
# 「でも、お姉様……！　会長さんは、未来の流星寮にとっても、きっと必要な方だと思うんですっ」
line = "「でも、お姉様……！　会長さんは、未来の流星寮にとっても、きっと必要な方だと思うんですっ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「フニっ！　イルソーレに来たばかりだというのに、あなたはそこまで……っ！」
line = "「フニっ！　イルソーレに来たばかりだというのに、あなたはそこまで……っ！」"

[[dialogue]]
speaker = "フェニエル"
# 「だから私、『花いちもんめ』されるかもしれないですけど、やります……！」
line = "「だから私、『花いちもんめ』されるかもしれないですけど、やります……！」"

[[dialogue]]
speaker = "マハムート"
# 「何か勝手に盛り上がってるわね……あら？　何かしら、会長？」
line = "「何か勝手に盛り上がってるわね……あら？　何かしら、会長？」"

[[dialogue]]
speaker = "マハムート"
# 「――生徒交換が可能なのかどうか？　まあ、星徒会長のあなたが権限を行使すれば……そういうこともあるでしょ」
line = "「――生徒交換が可能なのかどうか？　まあ、星徒会長のあなたが権限を行使すれば……そういうこともあるでしょ」"

[[dialogue]]
speaker = "unk"
# えぇぇ……本当に？？？
line = "えぇぇ……本当に？？？"

[[dialogue]]
speaker = "マハムート"
# 「まあでも、なんだか面白いことにはなってきたから、そのまま勝負は始めましょうか」
line = "「まあでも、なんだか面白いことにはなってきたから、そのまま勝負は始めましょうか」"

[[dialogue]]
speaker = "マハムート"
# 「ふふっ、細かいことを気にする必要はないわ。要するに、勝てばいいのよ。勝てば」
line = "「ふふっ、細かいことを気にする必要はないわ。要するに、勝てばいいのよ。勝てば」"

[[dialogue]]
speaker = "マハムート"
# 「題して、『寮生争奪チキチキ花いちもんめバトルウィーク』、開催よ！！」
line = "「題して、『寮生争奪チキチキ花いちもんめバトルウィーク』、開催よ！！」"
