[[dialogue]]
speaker = "セナリィ"
# 「新規依頼が３件……」
line = "「新規依頼が３件……」"

[[dialogue]]
speaker = "セナリィ"
# （以前より仕事の依頼が来てくれるのはありがたいのだけど……ヒマワリが稼いでくれてるおかげか、報酬がしょぼく見えてしまうわね……）
line = "（以前より仕事の依頼が来てくれるのはありがたいのだけど……ヒマワリが稼いでくれてるおかげか、報酬がしょぼく見えてしまうわね……）"

[[dialogue]]
speaker = "セナリィ"
# （何も危険に身を晒さなくとも、しばらくは食い繋げ──いいえ！　金額の大小じゃないわ！　『裏社会にゴールデングースあり！』と知らしめなければ！）
line = "（何も危険に身を晒さなくとも、しばらくは食い繋げ──いいえ！　金額の大小じゃないわ！　『裏社会にゴールデングースあり！』と知らしめなければ！）"

[[dialogue]]
speaker = "セナリィ"
# （実績に基づいた圧倒的な知名度は、お金で買うものではないの。これぞまさにプライスレス！）
line = "（実績に基づいた圧倒的な知名度は、お金で買うものではないの。これぞまさにプライスレス！）"

[[dialogue]]
speaker = "セナリィ"
# （よもや、この子たちにお金では買えないものを教えられるとは思いもよらなかったわ……）
line = "（よもや、この子たちにお金では買えないものを教えられるとは思いもよらなかったわ……）"

[[dialogue]]
speaker = "ミウ"
# 「セナリィ社長？　遠い目をされて、どうかしました？」
line = "「セナリィ社長？　遠い目をされて、どうかしました？」"

[[dialogue]]
speaker = "セナリィ"
# 「なんでもありませんわ。今晩は犯罪者を追いかけ回すだけの簡単なお仕事。ゴールデングース出撃しますわよ！」
line = "「なんでもありませんわ。今晩は犯罪者を追いかけ回すだけの簡単なお仕事。ゴールデングース出撃しますわよ！」"

[[dialogue]]
speaker = "ミウ＆ヒマワリ"
# 「了解っ！」
line = "「了解っ！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「さぁ、あたしらゴールデングースの恐怖を心に刻みつけて、お縄につけー！」
line = "「さぁ、あたしらゴールデングースの恐怖を心に刻みつけて、お縄につけー！」"

[[dialogue]]
speaker = "ミウ"
# 「私たち２人でも余裕そうだね、ヒマワリちゃん」
line = "「私たち２人でも余裕そうだね、ヒマワリちゃん」"

[[dialogue]]
speaker = "ヒマワリ"
# 「セナリィ社長の手を煩わせるまでもないっ！　あたしたちだけで終わらせちゃおーよ！　これなら見習いから昇格するのも、あっという間だね！」
line = "「セナリィ社長の手を煩わせるまでもないっ！　あたしたちだけで終わらせちゃおーよ！　これなら見習いから昇格するのも、あっという間だね！」"

[[dialogue]]
speaker = "ミウ"
# 「事前の話通り、逃げ足だけは速いね。このままだと引き離されちゃう。狙撃で脳天を撃ち抜けば、簡単なのに……」
line = "「事前の話通り、逃げ足だけは速いね。このままだと引き離されちゃう。狙撃で脳天を撃ち抜けば、簡単なのに……」"

[[dialogue]]
speaker = "ヒマワリ"
# 「ヘッドショットしたい気持ちはよーくわかるけど、ダメだよ！　生かしたまま捕らえろって任務だし──」
line = "「ヘッドショットしたい気持ちはよーくわかるけど、ダメだよ！　生かしたまま捕らえろって任務だし──」"

[[dialogue]]
speaker = "ミウ"
# 「──！？　止まって、ヒマワリちゃん！」
line = "「──！？　止まって、ヒマワリちゃん！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「え？　──うわぁっ！？」
line = "「え？　──うわぁっ！？」"

[[dialogue]]
speaker = "モンスター"
# 「ピガーーー！」
line = "「ピガーーー！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「なに、このモンスター！？　こんな変なの見たことないよー！」
line = "「なに、このモンスター！？　こんな変なの見たことないよー！」"

[[dialogue]]
speaker = "ミウ"
# 「全身が機械でできてる……噂には聞いてましたけど、これが新型……？」
line = "「全身が機械でできてる……噂には聞いてましたけど、これが新型……？」"

[[dialogue]]
speaker = "ヒマワリ"
# 「ああっ、くそー！　おまえのせいで逃げられちゃうじゃないかー！」
line = "「ああっ、くそー！　おまえのせいで逃げられちゃうじゃないかー！」"

[[dialogue]]
speaker = "ミウ"
# 「初見の相手ですから、プランの立てようがないです……困っちゃいましたね」
line = "「初見の相手ですから、プランの立てようがないです……困っちゃいましたね」"

[[dialogue]]
speaker = "ヒマワリ"
# 「あー、そこだよね。ミウの弱点」
line = "「あー、そこだよね。ミウの弱点」"

[[dialogue]]
speaker = "ミウ"
# 「むぅ……とりあえず脆そうな部分を狙ってみましょう」
line = "「むぅ……とりあえず脆そうな部分を狙ってみましょう」"

[[dialogue]]
speaker = "ヒマワリ"
# 「うわ、カッタぁ！　あたしの銃弾がちっとも通んないよー！」
line = "「うわ、カッタぁ！　あたしの銃弾がちっとも通んないよー！」"

[[dialogue]]
speaker = "ミウ"
# 「私の狙撃も弾かれちゃってます。装甲が薄そうな部分を狙っているんですが……」
line = "「私の狙撃も弾かれちゃってます。装甲が薄そうな部分を狙っているんですが……」"

[[dialogue]]
speaker = "ヒマワリ"
# 「なんだよもー！　そんなのズルだよ、ズル！　チートだ、チート！」
line = "「なんだよもー！　そんなのズルだよ、ズル！　チートだ、チート！」"

[[dialogue]]
speaker = "ミウ"
# 「ターゲットには逃げられてしまいましたし、任務失敗ですね……生死を問わなければ、楽だったのに……」
line = "「ターゲットには逃げられてしまいましたし、任務失敗ですね……生死を問わなければ、楽だったのに……」"

[[dialogue]]
speaker = "ヒマワリ"
# 「中途半端に攻撃したから、モンスターくんも怒ってるみたいだし……ヘイト集めすぎちゃった？」
line = "「中途半端に攻撃したから、モンスターくんも怒ってるみたいだし……ヘイト集めすぎちゃった？」"

[[dialogue]]
speaker = "ミウ"
# 「そうですね。ちょっとヤバい、かも」
line = "「そうですね。ちょっとヤバい、かも」"

[[dialogue]]
speaker = "ヒマワリ"
# 「ミウがそう言うなら、めちゃヤバなんだろーね……どうしよっか」
line = "「ミウがそう言うなら、めちゃヤバなんだろーね……どうしよっか」"

[[dialogue]]
speaker = "ミウ"
# 「私のプランなら、撤退推奨です」
line = "「私のプランなら、撤退推奨です」"

[[dialogue]]
speaker = "ヒマワリ"
# 「逃げるってことだね！　あたしも賛成っ！」
line = "「逃げるってことだね！　あたしも賛成っ！」"

[[dialogue]]
speaker = "モンスター"
# 「ピピガガーーー！」
line = "「ピピガガーーー！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「うわ、ヤバ、ヤバーッ！　コイツ速ーいっ！」
line = "「うわ、ヤバ、ヤバーッ！　コイツ速ーいっ！」"

[[dialogue]]
speaker = "ミウ"
# 「５秒後には追い付かれちゃいます！　ヒマワリちゃん、もっと加速してっ！」
line = "「５秒後には追い付かれちゃいます！　ヒマワリちゃん、もっと加速してっ！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「そう言われても、これで目一杯だってー！」
line = "「そう言われても、これで目一杯だってー！」"

[[dialogue]]
speaker = "セナリィ（覚醒）"
# 「ごめんなさい、２人とも。待たせてしまったようですわね」
line = "「ごめんなさい、２人とも。待たせてしまったようですわね」"

[[dialogue]]
speaker = "ミウ"
# 「セナリィ社長、ですか……？　その姿は……！？」
line = "「セナリィ社長、ですか……？　その姿は……！？」"

[[dialogue]]
speaker = "セナリィ（覚醒）"
# 「２人にも秘密にしていた<ruby=エンプレス>女帝</ruby>フォーム。今こそお披露目の時ですわ」
line = "「２人にも秘密にしていた<ruby>女帝<rt>エンプレス</rt></ruby>フォーム。今こそお披露目の時ですわ」"

[[dialogue]]
speaker = "ヒマワリ"
# 「<ruby=エンプレス>女帝</ruby>フォーム……カッコよ！」
line = "「<ruby>女帝<rt>エンプレス</rt></ruby>フォーム……カッコよ！」"

[[dialogue]]
speaker = "セナリィ（覚醒）"
# 「私の部下を可愛がってくれた礼、させていただきますわ。覚悟なさい！」
line = "「私の部下を可愛がってくれた礼、させていただきますわ。覚悟なさい！」"

[[dialogue]]
speaker = "ミウ"
# 「そいつ、すっごく硬いですよ！　気をつけてください！」
line = "「そいつ、すっごく硬いですよ！　気をつけてください！」"

[[dialogue]]
speaker = "セナリィ（覚醒）"
# 「ふふ、心配には及びませんわ。私を誰だと思っていますの？」
line = "「ふふ、心配には及びませんわ。私を誰だと思っていますの？」"

[[dialogue]]
speaker = "セナリィ（覚醒）"
# 「あなたたちを統べる者の力、とくと見るがいいですわ！　ガトリングパーティー！」
line = "「あなたたちを統べる者の力、とくと見るがいいですわ！　ガトリングパーティー！」"

[[dialogue]]
speaker = "セナリィ（覚醒）"
# 「ゴールデングース総帥、バンデット・セナリィ。以後、お見知りおきを」
line = "「ゴールデングース総帥、バンデット・セナリィ。以後、お見知りおきを」"

[[dialogue]]
speaker = "モンスター"
# 「ピガガー……」
line = "「ピガガー……」"

[[dialogue]]
speaker = "ミウ"
# 「い、一撃ですか……！？　私たちが手も足も出なかったモンスターを……たったの一撃で……！？」
line = "「い、一撃ですか……！？　私たちが手も足も出なかったモンスターを……たったの一撃で……！？」"

[[dialogue]]
speaker = "ヒマワリ"
# 「うわぁあぁぁぁぁ社長カッコよぉおおぉぉっ！」
line = "「うわぁあぁぁぁぁ社長カッコよぉおおぉぉっ！」"

[[dialogue]]
speaker = "セナリィ"
# （なるほど。やはり星力の消耗が尋常ではないわね……一撃で決める短期決戦なら、さっきのように使用できるけど……）
line = "（なるほど。やはり星力の消耗が尋常ではないわね……一撃で決める短期決戦なら、さっきのように使用できるけど……）"

[[dialogue]]
speaker = "ヒマワリ"
# 「ありがとうございます、社長ーーっ！」
line = "「ありがとうございます、社長ーーっ！」"

[[dialogue]]
speaker = "ミウ"
# 「素敵でした……素敵が溢れ過ぎてました……！　一生ついていこうと、固く心に誓いました！」
line = "「素敵でした……素敵が溢れ過ぎてました……！　一生ついていこうと、固く心に誓いました！」"

[[dialogue]]
speaker = "セナリィ"
# （ま……とりあえず、社長の面目躍如といったところかしら……）
line = "（ま……とりあえず、社長の面目躍如といったところかしら……）"
