[[dialogue]]
speaker = "レイラ"
# （あれが魔王……新星学園で最強の星騎士にして、救世の英雄）
line = "（あれが魔王……新星学園で最強の星騎士にして、救世の英雄）"

[[dialogue]]
speaker = "レイラ"
# （だけど私は負けられない。星騎士にも、魔王にも）
line = "（だけど私は負けられない。星騎士にも、魔王にも）"

[[dialogue]]
speaker = "レイラ"
# （私は……私は……──）
line = "（私は……私は……──）"

[[dialogue]]
speaker = "unk"
# 小さいころは、両親とよく礼拝に通っていた。
line = "小さいころは、両親とよく礼拝に通っていた。"

[[dialogue]]
speaker = "幼いレイラ"
# 「世界がよりよくなりますように」
line = "「世界がよりよくなりますように」"

[[dialogue]]
speaker = "unk"
# 両親とひざまずいて祈りを捧げる。言葉の意味は分からないが、いいことだって信じていた。だってお父さまとお母さまが喜んでくれるから。
line = "両親とひざまずいて祈りを捧げる。言葉の意味は分からないが、いいことだって信じていた。だってお父さまとお母さまが喜んでくれるから。"

[[dialogue]]
speaker = "幼いレイラ"
# 「お母さま、あの絵なぁに？」
line = "「お母さま、あの絵なぁに？」"

[[dialogue]]
speaker = "レイラ母"
# 「あれは太陽の壁画っていうの。魔王っていう悪い人をやっつけたときの絵で、３つの種族が手を取り合って魔王を倒したことで、世界に平和が訪れたの」
line = "「あれは太陽の壁画っていうの。魔王っていう悪い人をやっつけたときの絵で、３つの種族が手を取り合って魔王を倒したことで、世界に平和が訪れたの」"

[[dialogue]]
speaker = "幼いレイラ"
# 「じゃあ、わたしもまおうさん？　をやっつける！　あの絵みたいにたくさんお友だちつくるの！」
line = "「じゃあ、わたしもまおうさん？　をやっつける！　あの絵みたいにたくさんお友だちつくるの！」"

[[dialogue]]
speaker = "レイラ父"
# 「ははは。レイラ、魔王はもういないんだよ」
line = "「ははは。レイラ、魔王はもういないんだよ」"

[[dialogue]]
speaker = "レイラ母"
# 「でも、モンスターは出るわ。レイラなら立派な星騎士になれる。世界をよりよくできるわ」
line = "「でも、モンスターは出るわ。レイラなら立派な星騎士になれる。世界をよりよくできるわ」"

[[dialogue]]
speaker = "unk"
# 母は若い頃、星騎士だったそうだ。百目騎は星騎士の家系でもあり、その活躍から百目鬼の「鬼」を星騎士の「騎」に改めたと聞いている。
line = "母は若い頃、星騎士だったそうだ。百目騎は星騎士の家系でもあり、その活躍から百目鬼の「鬼」を星騎士の「騎」に改めたと聞いている。"

[[dialogue]]
speaker = "unk"
# 世界をよりよくする。それが両親の口癖だった。
line = "世界をよりよくする。それが両親の口癖だった。"

[[dialogue]]
speaker = "unk"
# 百目騎の家訓でもあり、家業である半導体産業もその延長で始まったそうだ。新しい技術が世界を豊かにすると信じていたのだ。
line = "百目騎の家訓でもあり、家業である半導体産業もその延長で始まったそうだ。新しい技術が世界を豊かにすると信じていたのだ。"

[[dialogue]]
speaker = "unk"
# けれど、それだけでやっていけるほど世間は甘くない。日進月歩の技術開発に追いつき、リードしていかなければ、競争の波に呑み込まれる。
line = "けれど、それだけでやっていけるほど世間は甘くない。日進月歩の技術開発に追いつき、リードしていかなければ、競争の波に呑み込まれる。"

[[dialogue]]
speaker = "数年前のレイラ"
# 「お父様、お休みになってください。働きすぎは体に毒ですよ」
line = "「お父様、お休みになってください。働きすぎは体に毒ですよ」"

[[dialogue]]
speaker = "レイラ父"
# 「これくらい大丈夫だよ、レイラ。それに、従業員だけ働かせて、社長の私が怠けているわけにはいかないからね」
line = "「これくらい大丈夫だよ、レイラ。それに、従業員だけ働かせて、社長の私が怠けているわけにはいかないからね」"

[[dialogue]]
speaker = "unk"
# そう言って、隈の浮いた顔で笑っていた。事業が傾くとともに、お父様は家に帰らなくなってしまった。
line = "そう言って、隈の浮いた顔で笑っていた。事業が傾くとともに、お父様は家に帰らなくなってしまった。"

[[dialogue]]
speaker = "レイラ母"
# 「大丈夫よ、レイラ。あなたは私が守るからね」
line = "「大丈夫よ、レイラ。あなたは私が守るからね」"

[[dialogue]]
speaker = "unk"
# お父様が過労で亡くなってすぐ、お母様も後を追うように──
line = "お父様が過労で亡くなってすぐ、お母様も後を追うように──"

[[dialogue]]
speaker = "unk"
# そして両親を喪ってすぐ、心を整理する間もなく、あるものを奪われた。
line = "そして両親を喪ってすぐ、心を整理する間もなく、あるものを奪われた。"

[[dialogue]]
speaker = "unk"
# 多額の資金を投じてようやく実用化が見えてきた先進技術を、お父様とお母様が亡くなった混乱に乗じて、会社幹部が持ち出したのだ。
line = "多額の資金を投じてようやく実用化が見えてきた先進技術を、お父様とお母様が亡くなった混乱に乗じて、会社幹部が持ち出したのだ。"

[[dialogue]]
speaker = "unk"
# 技術革新に社運を懸けていた会社は抜け殻となり、残された事業も足元を見た価格で買い取られた。
line = "技術革新に社運を懸けていた会社は抜け殻となり、残された事業も足元を見た価格で買い取られた。"

[[dialogue]]
speaker = "unk"
# 当然、百目騎の名は残らなかった。
line = "当然、百目騎の名は残らなかった。"

[[dialogue]]
speaker = "数年前のレイラ"
# 「守護星よ、どうか私に力をお与えください…………どうして、どうして私には星力が目覚めないの……？」
line = "「守護星よ、どうか私に力をお与えください…………どうして、どうして私には星力が目覚めないの……？」"

[[dialogue]]
speaker = "unk"
# せめて星騎士として名前を残そうとも思ったが、私に星力は発現しなかった。
line = "せめて星騎士として名前を残そうとも思ったが、私に星力は発現しなかった。"

[[dialogue]]
speaker = "unk"
# 夜空にはあんなに星が輝いて綺麗なのに、ひとつも私に応えてはくれなかった。
line = "夜空にはあんなに星が輝いて綺麗なのに、ひとつも私に応えてはくれなかった。"

[[dialogue]]
speaker = "unk"
# 気が付いたら、私は海の中だった。
line = "気が付いたら、私は海の中だった。"

[[dialogue]]
speaker = "数年前のレイラ"
# 「はぁ、はぁ、はぁ、はぁ…………私、生きて……浮いてる！？」
line = "「はぁ、はぁ、はぁ、はぁ…………私、生きて……浮いてる！？」"

[[dialogue]]
speaker = "イザベラ"
# 「あなた、こんなところで何してるの？」
line = "「あなた、こんなところで何してるの？」"

[[dialogue]]
speaker = "数年前のレイラ"
# 「あなたはどなたですか？　この状況はいったいどうなっているのですか？　え、星空が私の足元に……違う、私が逆さまに浮いて……？」
line = "「あなたはどなたですか？　この状況はいったいどうなっているのですか？　え、星空が私の足元に……違う、私が逆さまに浮いて……？」"

[[dialogue]]
speaker = "unk"
# 魔法で夜空に吊り上げられて、ふよふよ浮いて。それがイザベラさんとの出会いだった。満天の星を見下ろしながら、私は彼女に出会った。
line = "魔法で夜空に吊り上げられて、ふよふよ浮いて。それがイザベラさんとの出会いだった。満天の星を見下ろしながら、私は彼女に出会った。"

[[dialogue]]
speaker = "イザベラ"
# 「私は魔女のイザベラ」
line = "「私は魔女のイザベラ」"

[[dialogue]]
speaker = "イザベラ"
# 「詳しいことは後で話すとして、あなたはもう力に目覚めているはず。ほら、魔法を解除するから飛んでみなさい」
line = "「詳しいことは後で話すとして、あなたはもう力に目覚めているはず。ほら、魔法を解除するから飛んでみなさい」"

[[dialogue]]
speaker = "数年前のレイラ"
# 「え、あ、うわあっぁああああっ！？」
line = "「え、あ、うわあっぁああああっ！？」"

[[dialogue]]
speaker = "数年前のレイラ"
# 「ほ、ほんとだ。私、飛んでる……ということは、星騎士になれたってコト！？」
line = "「ほ、ほんとだ。私、飛んでる……ということは、星騎士になれたってコト！？」"

[[dialogue]]
speaker = "イザベラ"
# 「そう、あなたは正真正銘の星騎士よ。ただし……守護星はブラックホールだけど」
line = "「そう、あなたは正真正銘の星騎士よ。ただし……守護星はブラックホールだけど」"

[[dialogue]]
speaker = "イザベラ"
# 「こんなところで水遊びしているくらいなら、私の研究を手伝いなさい。世界を救う大仕事よ」
line = "「こんなところで水遊びしているくらいなら、私の研究を手伝いなさい。世界を救う大仕事よ」"

[[dialogue]]
speaker = "数年前のレイラ"
# 「世界を、救う……？」
line = "「世界を、救う……？」"

[[dialogue]]
speaker = "unk"
# それからイザベラさんの魔法でコラプサーの覚醒を予知し、三界を駆け回った。
line = "それからイザベラさんの魔法でコラプサーの覚醒を予知し、三界を駆け回った。"

[[dialogue]]
speaker = "unk"
# そうして出会ったのが──
line = "そうして出会ったのが──"

[[dialogue]]
speaker = "unk"
# キサナ。リーナ。ヴァレリー。
line = "キサナ。リーナ。ヴァレリー。"

[[dialogue]]
speaker = "unk"
# イングリット。ジュリエッテ。
line = "イングリット。ジュリエッテ。"

[[dialogue]]
speaker = "unk"
# メテオラ。エンジュ。
line = "メテオラ。エンジュ。"

[[dialogue]]
speaker = "unk"
# みんなひと筋縄ではいかなかったし（特にイングリット）、移動するだけでひと苦労だった（主にイングリット）。
line = "みんなひと筋縄ではいかなかったし（特にイングリット）、移動するだけでひと苦労だった（主にイングリット）。"

[[dialogue]]
speaker = "unk"
# イザベラさんのことはみんなに秘密だったから、もう気分は中間管理職だ。
line = "イザベラさんのことはみんなに秘密だったから、もう気分は中間管理職だ。"

[[dialogue]]
speaker = "unk"
# みんなと過ごすうちに分かったことがある。
line = "みんなと過ごすうちに分かったことがある。"

[[dialogue]]
speaker = "レイラ"
# 「私たちの存在は、この世界と相容れない……」
line = "「私たちの存在は、この世界と相容れない……」"

[[dialogue]]
speaker = "unk"
# 星騎士は世界を守る正義の味方で、私たちはその天敵だ。
line = "星騎士は世界を守る正義の味方で、私たちはその天敵だ。"

[[dialogue]]
speaker = "unk"
# 存在するだけで、世界を危うくする。それ以前にみんな社会不適合者すぎるけど、それはそれとして。
line = "存在するだけで、世界を危うくする。それ以前にみんな社会不適合者すぎるけど、それはそれとして。"

[[dialogue]]
speaker = "レイラ"
# 「なら、世界を変えればいい。私たちコラプサーが正義の味方になればいいんだ」
line = "「なら、世界を変えればいい。私たちコラプサーが正義の味方になればいいんだ」"

[[dialogue]]
speaker = "レイラ"
# 「私は３つの種族を率いて、世界を救う『英雄』になってみせる。あの壁画みたいに」
line = "「私は３つの種族を率いて、世界を救う『英雄』になってみせる。あの壁画みたいに」"

[[dialogue]]
speaker = "レイラ"
# 「そして、百目騎の名を歴史に残してみせます。どうか見ていてください、お父様、お母様」
line = "「そして、百目騎の名を歴史に残してみせます。どうか見ていてください、お父様、お母様」"

[[dialogue]]
speaker = "unk"
# 朝比奈コハルコを生贄にする。そんな話を聞いたのは学園襲撃失敗後だった。
line = "朝比奈コハルコを生贄にする。そんな話を聞いたのは学園襲撃失敗後だった。"

[[dialogue]]
speaker = "レイラ"
# 「早くみんなを助けないと……っ！」
line = "「早くみんなを助けないと……っ！」"

[[dialogue]]
speaker = "イザベラ"
# 「放っておきなさい。命を取るつもりなら最初から捕らえていないわ。無事は確認できているんでしょう？」
line = "「放っておきなさい。命を取るつもりなら最初から捕らえていないわ。無事は確認できているんでしょう？」"

[[dialogue]]
speaker = "レイラ"
# 「ええ、まあ……ネビュラ基地はハッキング済みですので、みんなの様子は把握しています。魔女がパソコン音痴で助かりました」
line = "「ええ、まあ……ネビュラ基地はハッキング済みですので、みんなの様子は把握しています。魔女がパソコン音痴で助かりました」"

[[dialogue]]
speaker = "イザベラ"
# 「私たちが世界を救えば、あとはどうとでもなるわ。今は計画の成就を考えなさい」
line = "「私たちが世界を救えば、あとはどうとでもなるわ。今は計画の成就を考えなさい」"

[[dialogue]]
speaker = "レイラ"
# 「……はい。でも、本当に必要なんですか？　生贄なんて……」
line = "「……はい。でも、本当に必要なんですか？　生贄なんて……」"

[[dialogue]]
speaker = "イザベラ"
# 「いい加減、選びなさい。コラプサーたちを見捨て、ただの人間として生きていくのか。それとも朝比奈コハルコを犠牲にして、コラプサーたちと英雄になるか」
line = "「いい加減、選びなさい。コラプサーたちを見捨て、ただの人間として生きていくのか。それとも朝比奈コハルコを犠牲にして、コラプサーたちと英雄になるか」"

[[dialogue]]
speaker = "レイラ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "レイラ"
# （私はもう立ち止まれない）
line = "（私はもう立ち止まれない）"

[[dialogue]]
speaker = "レイラ"
# （魔王に勝利し、百目騎の名を再び歴史に刻む……！）
line = "（魔王に勝利し、百目騎の名を再び歴史に刻む……！）"
