[[dialogue]]
speaker = "フィオナ"
# 「フレイムフォーム……？？」
line = "「フレイムフォーム……？？」"

[[dialogue]]
speaker = "アポロ"
# 「そう、さっき突然変身できるようになったんだ！　かっこいいだろ！」
line = "「そう、さっき突然変身できるようになったんだ！　かっこいいだろ！」"

[[dialogue]]
speaker = "アルテ"
# 「おや、私の持っている衣装に似ています。その華麗さゆえに真似したくなるのも理解できますが、さすがに私には及びませんね」
line = "「おや、私の持っている衣装に似ています。その華麗さゆえに真似したくなるのも理解できますが、さすがに私には及びませんね」"

[[dialogue]]
speaker = "アルテ"
# 「まぁでも、私の次くらいには似合ってますよ。自信を持ってください」
line = "「まぁでも、私の次くらいには似合ってますよ。自信を持ってください」"

[[dialogue]]
speaker = "アポロ"
# 「なんだ、こいつ……？　妙に上から目線だな……」
line = "「なんだ、こいつ……？　妙に上から目線だな……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「アルテはこういう子なのよ」
line = "「アルテはこういう子なのよ」"

[[dialogue]]
speaker = "アポロ"
# 「そ、そうか……そういうもんなのか……」
line = "「そ、そうか……そういうもんなのか……」"

[[dialogue]]
speaker = "アポロ"
# 「だけど１つ問題があってな。このフォームに変身したと同時に、普通のフォームに変身出来なくなっちゃったんだ」
line = "「だけど１つ問題があってな。このフォームに変身したと同時に、普通のフォームに変身出来なくなっちゃったんだ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それって大問題じゃないの！」
line = "「それって大問題じゃないの！」"

[[dialogue]]
speaker = "アルテ"
# 「タイミングを考えると……これもあの黒ベア子の起こした異変のひとつ、ということですかね？」
line = "「タイミングを考えると……これもあの黒ベア子の起こした異変のひとつ、ということですかね？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「多分、そういうことね。ひとまず当面は……」
line = "「多分、そういうことね。ひとまず当面は……」"

[[dialogue]]
speaker = "unk"
# 相談の結果、プトラは星見家、アルテは九浄家に滞在することになった。
line = "相談の結果、プトラは星見家、アルテは九浄家に滞在することになった。"

[[dialogue]]
speaker = "unk"
# 方針が定まったところで、２人にこの世界のことを知ってもらおうと、軽く街を案内することに。
line = "方針が定まったところで、２人にこの世界のことを知ってもらおうと、軽く街を案内することに。"

[[dialogue]]
speaker = "プトラ"
# 「うわー、人がいっぱい！　着てる服もあたしたちの世界と全然違うな～！」
line = "「うわー、人がいっぱい！　着てる服もあたしたちの世界と全然違うな～！」"

[[dialogue]]
speaker = "アルテ"
# 「ここも巨大な建物がたくさんありますね。しかし先ほどの街よりも落ち着いた雰囲気です」
line = "「ここも巨大な建物がたくさんありますね。しかし先ほどの街よりも落ち着いた雰囲気です」"

[[dialogue]]
speaker = "プトラ"
# 「ねえねえ、あっちの大きな建物はなんだろ？」
line = "「ねえねえ、あっちの大きな建物はなんだろ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あれは東京駅よ」
line = "「あれは東京駅よ」"

[[dialogue]]
speaker = "プトラ"
# 「駅！？　この世界の列車！？」
line = "「駅！？　この世界の列車！？」"

[[dialogue]]
speaker = "フィオナ"
# 「ああ、当然プトラさんは興味を示しますよね」
line = "「ああ、当然プトラさんは興味を示しますよね」"

[[dialogue]]
speaker = "プトラ"
# 「こっちの世界の列車がどんな感じか見てみたいな～」
line = "「こっちの世界の列車がどんな感じか見てみたいな～」"

[[dialogue]]
speaker = "アポロ"
# 「乗ってみるか？」
line = "「乗ってみるか？」"

[[dialogue]]
speaker = "プトラ"
# 「いいの！？」
line = "「いいの！？」"

[[dialogue]]
speaker = "アルテ"
# 「面白そうですね。私も乗ってみたいです」
line = "「面白そうですね。私も乗ってみたいです」"

[[dialogue]]
speaker = "プトラ"
# 「でも、幻霧の中でミストモンスターに襲われたらどうしよう？　今の装備じゃ戦えないよ」
line = "「でも、幻霧の中でミストモンスターに襲われたらどうしよう？　今の装備じゃ戦えないよ」"

[[dialogue]]
speaker = "unk"
# 幻霧？
line = "幻霧？"

[[dialogue]]
speaker = "プトラ"
# 「うん……イリスクラウドは大陸全土を幻霧っていう謎の霧に覆われてるの」
line = "「うん……イリスクラウドは大陸全土を幻霧っていう謎の霧に覆われてるの」"

[[dialogue]]
speaker = "プトラ"
# 「それでね、霧の中には凶悪なミストモンスターが棲みついていて、人を惑わせたり襲ったりするんだ」
line = "「それでね、霧の中には凶悪なミストモンスターが棲みついていて、人を惑わせたり襲ったりするんだ」"

[[dialogue]]
speaker = "プトラ"
# 「そんな霧の中を突っ切って走ることが出来る列車──それが魔導列車ミストトレインなんだよ！」
line = "「そんな霧の中を突っ切って走ることが出来る列車──それが魔導列車ミストトレインなんだよ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そっちはそっちで大変な世界みたいね……」
line = "「そっちはそっちで大変な世界みたいね……」"

[[dialogue]]
speaker = "フィオナ"
# 「大丈夫です。こちらの世界に幻霧は発生しませんから」
line = "「大丈夫です。こちらの世界に幻霧は発生しませんから」"

[[dialogue]]
speaker = "ヴィーナス"
# 「代わりにアステラが発生して、モンスターに襲われる可能性もあるけどね」
line = "「代わりにアステラが発生して、モンスターに襲われる可能性もあるけどね」"

[[dialogue]]
speaker = "プトラ"
# 「モンスター？　ミストモンスターじゃないモンスターがこっちにはいるんだ？」
line = "「モンスター？　ミストモンスターじゃないモンスターがこっちにはいるんだ？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「この世界は、リクリエという破滅の危機に直面しているわ」
line = "「この世界は、リクリエという破滅の危機に直面しているわ」"

[[dialogue]]
speaker = "フィオナ"
# 「リクリエはモンスターを生み出し、モンスターは人々や街を襲います。アステラはモンスターの巣なんです」
line = "「リクリエはモンスターを生み出し、モンスターは人々や街を襲います。アステラはモンスターの巣なんです」"

[[dialogue]]
speaker = "アポロ"
# 「あたしたち星騎士は、日夜そのモンスターと戦ってるんだ！」
line = "「あたしたち星騎士は、日夜そのモンスターと戦ってるんだ！」"

[[dialogue]]
speaker = "プトラ"
# 「ほぇ～……こっちの世界も大変なんだ……」
line = "「ほぇ～……こっちの世界も大変なんだ……」"

[[dialogue]]
speaker = "アポロ"
# 「ま、プトラとアルテは安心してていいぞ。いざという時はあたしたちが守るからな！」
line = "「ま、プトラとアルテは安心してていいぞ。いざという時はあたしたちが守るからな！」"

[[dialogue]]
speaker = "unk"
# 山手線に乗った俺たちは、ぐるりと一周して東京駅へと戻ってきた。
line = "山手線に乗った俺たちは、ぐるりと一周して東京駅へと戻ってきた。"

[[dialogue]]
speaker = "unk"
# 電車から降りて駅の外へ出ると、プトラの魂が抜けかかっている。
line = "電車から降りて駅の外へ出ると、プトラの魂が抜けかかっている。"

[[dialogue]]
speaker = "プトラ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ヴィーナス"
# 「プトラ、どうしちゃったの？」
line = "「プトラ、どうしちゃったの？」"

[[dialogue]]
speaker = "フィオナ"
# 「おそらく、カルチャーショックを受けてるんじゃないかと」
line = "「おそらく、カルチャーショックを受けてるんじゃないかと」"

[[dialogue]]
speaker = "プトラ"
# 「特鉄隊じゃない一般の人たちもミストトレイン……じゃない列車に乗ってるし……」
line = "「特鉄隊じゃない一般の人たちもミストトレイン……じゃない列車に乗ってるし……」"

[[dialogue]]
speaker = "プトラ"
# 「幻霧が無くなれば、あたしたちの世界もあんな風になるのかな」
line = "「幻霧が無くなれば、あたしたちの世界もあんな風になるのかな」"

[[dialogue]]
speaker = "プトラ"
# 「あたし、何だかワクワクしてきたよ！」
line = "「あたし、何だかワクワクしてきたよ！」"

[[dialogue]]
speaker = "アルテ"
# 「きっとそうなりますよ。もぐもぐ……」
line = "「きっとそうなりますよ。もぐもぐ……」"

[[dialogue]]
speaker = "アポロ"
# 「で、おまえは何をしこたま買い込んでるんだ？」
line = "「で、おまえは何をしこたま買い込んでるんだ？」"

[[dialogue]]
speaker = "アルテ"
# 「おみやげコーナーを見ていたら美味しそうなものがたくさん並んでいたので、フィオナにお願いして買ってもらいました」
line = "「おみやげコーナーを見ていたら美味しそうなものがたくさん並んでいたので、フィオナにお願いして買ってもらいました」"

[[dialogue]]
speaker = "unk"
# ……フィオナ？
line = "……フィオナ？"

[[dialogue]]
speaker = "フィオナ"
# 「お店の前で食べたそうにしていたので……つい」
line = "「お店の前で食べたそうにしていたので……つい」"

[[dialogue]]
speaker = "アルテ"
# 「ん～、フワフワの生地にバナナ味のクリーム……このお菓子、お土産に持って帰りたいですね」
line = "「ん～、フワフワの生地にバナナ味のクリーム……このお菓子、お土産に持って帰りたいですね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「フィオナ、甘やかしちゃだめじゃないの！」
line = "「フィオナ、甘やかしちゃだめじゃないの！」"

[[dialogue]]
speaker = "フィオナ"
# 「す、すみません……」
line = "「す、すみません……」"

[[dialogue]]
speaker = "アルテ"
# 「おや、あれは……？」
line = "「おや、あれは……？」"

[[dialogue]]
speaker = "アルテ"
# 「建物の中に絵が飾ってありますが、美術館というわけではなさそうですね」
line = "「建物の中に絵が飾ってありますが、美術館というわけではなさそうですね」"

[[dialogue]]
speaker = "フィオナ"
# 「あれはギャラリーですね。スペースを借りて個展をしているんです」
line = "「あれはギャラリーですね。スペースを借りて個展をしているんです」"

[[dialogue]]
speaker = "フィオナ"
# 「ここから少し行くと銀座って場所があるんですけど、そこにはああいうギャラリーが沢山あるんですよ」
line = "「ここから少し行くと銀座って場所があるんですけど、そこにはああいうギャラリーが沢山あるんですよ」"

[[dialogue]]
speaker = "アルテ"
# 「ほうほう」
line = "「ほうほう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「へぇ、藝術家の血が騒ぐのかしら？　行ってみたい？」
line = "「へぇ、藝術家の血が騒ぐのかしら？　行ってみたい？」"

[[dialogue]]
speaker = "アルテ"
# 「面白そうですね。ですが、それより私はあちこちに建っている料理のお店の方に興味があります」
line = "「面白そうですね。ですが、それより私はあちこちに建っている料理のお店の方に興味があります」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あなたさっきお菓子を食べてたでしょう？」
line = "「あなたさっきお菓子を食べてたでしょう？」"

[[dialogue]]
speaker = "アルテ"
# 「それは別腹です」
line = "「それは別腹です」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でも確かに、そろそろお腹が空いてきた頃合いではあるわね」
line = "「でも確かに、そろそろお腹が空いてきた頃合いではあるわね」"

[[dialogue]]
speaker = "フィオナ"
# 「どこかお店を探して入りましょうか？」
line = "「どこかお店を探して入りましょうか？」"

[[dialogue]]
speaker = "アポロ"
# 「２人は何が食べたいんだ？」
line = "「２人は何が食べたいんだ？」"

[[dialogue]]
speaker = "アルテ"
# 「それはもちろん──」
line = "「それはもちろん──」"

[[dialogue]]
speaker = "プトラ"
# 「あたしはね──」
line = "「あたしはね──」"
