[[dialogue]]
speaker = "unk"
# 魔界から九浄家へと戻った編成隊は、再び作戦会議の席に着いた。
line = "魔界から九浄家へと戻った編成隊は、再び作戦会議の席に着いた。"

[[dialogue]]
speaker = "トリシャ"
# 「あと一歩、届きませんでしたか……守護天使様は一筋縄ではいきませんね……」
line = "「あと一歩、届きませんでしたか……守護天使様は一筋縄ではいきませんね……」"

[[dialogue]]
speaker = "ウズメイア"
# 「でもでも！　アイドルの２人を呼んでくれたのはマジ最高だったよ！　あたしもめーっちゃアガったし！」
line = "「でもでも！　アイドルの２人を呼んでくれたのはマジ最高だったよ！　あたしもめーっちゃアガったし！」"

[[dialogue]]
speaker = "フィオナ"
# 「私が冷えさせてしまった場を見事に温めて──うぅ……思い出すだけで恥ずかしさと申し訳なさがこみ上げてきます……」
line = "「私が冷えさせてしまった場を見事に温めて──うぅ……思い出すだけで恥ずかしさと申し訳なさがこみ上げてきます……」"

[[dialogue]]
speaker = "舞亜"
# 「ごめんなさい。やっぱり私の表現力が足りてなかったみたいだね」
line = "「ごめんなさい。やっぱり私の表現力が足りてなかったみたいだね」"

[[dialogue]]
speaker = "ソフィア"
# 「そんなことない！　舞亜は完璧だった。悔しいけど、あれを超える個人技なんて私には考えつかないよ……」
line = "「そんなことない！　舞亜は完璧だった。悔しいけど、あれを超える個人技なんて私には考えつかないよ……」"

[[dialogue]]
speaker = "マグダレナ"
# 「はい、悲観することはありません。あと少しでオオヒメが姿を現すところまでいっていました。実に惜しかったです」
line = "「はい、悲観することはありません。あと少しでオオヒメが姿を現すところまでいっていました。実に惜しかったです」"

[[dialogue]]
speaker = "舞亜"
# 「ほんと？」
line = "「ほんと？」"

[[dialogue]]
speaker = "マグダレナ"
# 「舞亜さまの演技は見事なものでした。その場にいた誰もが心を奪われるほどに」
line = "「舞亜さまの演技は見事なものでした。その場にいた誰もが心を奪われるほどに」"

[[dialogue]]
speaker = "マグダレナ"
# 「むしろ舞亜さまのパフォーマンスが素晴らしかったからこそ、より高みを求めたのだと思います。オオヒメは貪欲が過ぎます」
line = "「むしろ舞亜さまのパフォーマンスが素晴らしかったからこそ、より高みを求めたのだと思います。オオヒメは貪欲が過ぎます」"

[[dialogue]]
speaker = "舞亜"
# 「高み……か」
line = "「高み……か」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それなら簡単ね。さっきのを超えた、もっともーっと素晴らしい演技をすればいいだけよ！」
line = "「それなら簡単ね。さっきのを超えた、もっともーっと素晴らしい演技をすればいいだけよ！」"

[[dialogue]]
speaker = "ソフィア"
# 「『だけ』って簡単に言いますけど、そんな簡単にできるわけありません！　金メダルを更に超えるとなると──」
line = "「『だけ』って簡単に言いますけど、そんな簡単にできるわけありません！　金メダルを更に超えるとなると──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「宇宙レベルってことかしら。それこそ星騎士に相応しい到達点だわ！」
line = "「宇宙レベルってことかしら。それこそ星騎士に相応しい到達点だわ！」"

[[dialogue]]
speaker = "舞亜"
# 「ふふ、簡単に言ってくれちゃうね。悩んでるこっちが馬鹿馬鹿しくなっちゃう」
line = "「ふふ、簡単に言ってくれちゃうね。悩んでるこっちが馬鹿馬鹿しくなっちゃう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「馬鹿馬鹿しいくらいで良いのよ。だって、隠し芸大会なんだから！」
line = "「馬鹿馬鹿しいくらいで良いのよ。だって、隠し芸大会なんだから！」"

[[dialogue]]
speaker = "舞亜"
# 「そうだね。新しいプログラムを組み立てるには、ヴィーナスさんみたいな自由で柔軟な発想を忘れちゃいけない……うーん、もう少しで閃けそうなんだけど」
line = "「そうだね。新しいプログラムを組み立てるには、ヴィーナスさんみたいな自由で柔軟な発想を忘れちゃいけない……うーん、もう少しで閃けそうなんだけど」"

[[dialogue]]
speaker = "ヘレナ"
# 「そんなこともあろうかとー！」
line = "「そんなこともあろうかとー！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ヘレナちゃん！？」
line = "「ヘレナちゃん！？」"

[[dialogue]]
speaker = "ヘレナ"
# 「我が魂の囁きに応じて、追加衣装を用意した！　巫女装束の新春フォームである。舞亜、貴殿にこれを託そう」
line = "「我が魂の囁きに応じて、追加衣装を用意した！　巫女装束の新春フォームである。舞亜、貴殿にこれを託そう」"

[[dialogue]]
speaker = "舞亜"
# 「え、ありがとうございます」
line = "「え、ありがとうございます」"

[[dialogue]]
speaker = "ヘレナ"
# 「守護天使は女神を補佐する神聖なる存在。つまり神殿にて奉納する舞とは神楽だ。神楽舞を奉納するならば、この衣装こそが最適解であろう」
line = "「守護天使は女神を補佐する神聖なる存在。つまり神殿にて奉納する舞とは神楽だ。神楽舞を奉納するならば、この衣装こそが最適解であろう」"

[[dialogue]]
speaker = "ヘレナ"
# 「そして、最も舞を愛する貴殿に相応しいプリティーな代物であろう？　蘭美、着付けを」
line = "「そして、最も舞を愛する貴殿に相応しいプリティーな代物であろう？　蘭美、着付けを」"

[[dialogue]]
speaker = "蘭美"
# 「お任せください。さあ舞亜様、行くわよ」
line = "「お任せください。さあ舞亜様、行くわよ」"

[[dialogue]]
speaker = "舞亜"
# 「え、いいよ。脱がされるの、ちょっと恥ずかしいし」
line = "「え、いいよ。脱がされるの、ちょっと恥ずかしいし」"

[[dialogue]]
speaker = "蘭美"
# 「自分で和服を着たことあるかしら？　ちゃんと締めないとだらしないことになるわよ」
line = "「自分で和服を着たことあるかしら？　ちゃんと締めないとだらしないことになるわよ」"

[[dialogue]]
speaker = "舞亜"
# 「あ、それは勘弁。じゃあお願いしようかな」
line = "「あ、それは勘弁。じゃあお願いしようかな」"

[[dialogue]]
speaker = "蘭美"
# 「心配しなくても大丈夫よ、そんなに時間はかけないから」
line = "「心配しなくても大丈夫よ、そんなに時間はかけないから」"

[[dialogue]]
speaker = "unk"
# 俺、ちょっと外すね……
line = "俺、ちょっと外すね……"

[[dialogue]]
speaker = "舞亜"
# 「あ、見ていかないんだ、会長さん？」
line = "「あ、見ていかないんだ、会長さん？」"

[[dialogue]]
speaker = "unk"
# 見ていくわけないでしょ！？
line = "見ていくわけないでしょ！？"

[[dialogue]]
speaker = "舞亜"
# 「はは、冗談冗談。じゃ、また後でね」
line = "「はは、冗談冗談。じゃ、また後でね」"

[[dialogue]]
speaker = "unk"
# 舞亜の着替えを待つこと少し──
line = "舞亜の着替えを待つこと少し──"

[[dialogue]]
speaker = "蘭美"
# 「どう、あっという間だったでしょう？　それでどうかしら、自分の巫女装束を見てみて」
line = "「どう、あっという間だったでしょう？　それでどうかしら、自分の巫女装束を見てみて」"

[[dialogue]]
speaker = "舞亜"
# 「うん、いつもと全然違うから、とても新鮮。スタイリッシュだと思うけど、どうかな？」
line = "「うん、いつもと全然違うから、とても新鮮。スタイリッシュだと思うけど、どうかな？」"

[[dialogue]]
speaker = "unk"
# すごく綺麗だね
line = "すごく綺麗だね"

[[dialogue]]
speaker = "ソフィア"
# 「に、似合ってると思いますよ。舞亜のためだけに作られたような仕上がりで、すごく、とても……」
line = "「に、似合ってると思いますよ。舞亜のためだけに作られたような仕上がりで、すごく、とても……」"

[[dialogue]]
speaker = "ウズメイア"
# 「舞亜きゃわわ～♪　これ着て踊ったら、オオヒメ様だってイチコロでしょ～！」
line = "「舞亜きゃわわ～♪　これ着て踊ったら、オオヒメ様だってイチコロでしょ～！」"

[[dialogue]]
speaker = "ヘレナ"
# 「うむ！　やはり我が魂の囁きは確かであった！　守護天使であろうと秒で顔を出すであろう！」
line = "「うむ！　やはり我が魂の囁きは確かであった！　守護天使であろうと秒で顔を出すであろう！」"

[[dialogue]]
speaker = "舞亜"
# 「ありがとう、ヘレナさん。……だけどこれだけじゃ足りないかも。私だけの力じゃなくて……」
line = "「ありがとう、ヘレナさん。……だけどこれだけじゃ足りないかも。私だけの力じゃなくて……」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふむ、何か閃いたようだな。新しい着想たり得たか」
line = "「ふむ、何か閃いたようだな。新しい着想たり得たか」"

[[dialogue]]
speaker = "舞亜"
# 「うん。今までにやったことのないパフォーマンスができそう。一度失敗したのは無駄じゃなかったかも」
line = "「うん。今までにやったことのないパフォーマンスができそう。一度失敗したのは無駄じゃなかったかも」"

[[dialogue]]
speaker = "舞亜"
# 「ソフィ、ウズメ、ちょっと手伝ってくれる？」
line = "「ソフィ、ウズメ、ちょっと手伝ってくれる？」"

[[dialogue]]
speaker = "ソフィア"
# 「え……は、はい。私にできることなら」
line = "「え……は、はい。私にできることなら」"

[[dialogue]]
speaker = "ウズメイア"
# 「面白いこと見つけちゃったカンジ？　なんでも言って！」
line = "「面白いこと見つけちゃったカンジ？　なんでも言って！」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふふ、仲の良いことだ。貴殿らの打開策と救世に期待しておるぞ」
line = "「ふふ、仲の良いことだ。貴殿らの打開策と救世に期待しておるぞ」"
