[[dialogue]]
speaker = "リーナ"
# 「ゲーム楽しかったね、お兄ちゃん♪　クレーンゲームのぬいぐるみも取ってくれてありがとう！」
line = "「ゲーム楽しかったね、お兄ちゃん♪　クレーンゲームのぬいぐるみも取ってくれてありがとう！」"

[[dialogue]]
speaker = "リーナ"
# 「ねぇ、お洋服見に行ってもいい？　リーナ、お兄ちゃんの好きなお洋服着たいな～」
line = "「ねぇ、お洋服見に行ってもいい？　リーナ、お兄ちゃんの好きなお洋服着たいな～」"

[[dialogue]]
speaker = "unk"
# リーナと俺は家族なんだよな……？
line = "リーナと俺は家族なんだよな……？"

[[dialogue]]
speaker = "リーナ"
# 「うん！　お兄ちゃんが兄で、リーナが妹。そんなの当たり前だよ」
line = "「うん！　お兄ちゃんが兄で、リーナが妹。そんなの当たり前だよ」"

[[dialogue]]
speaker = "unk"
# じゃあお父さんとお母さんはどこに？
line = "じゃあお父さんとお母さんはどこに？"

[[dialogue]]
speaker = "リーナ"
# 「え──？」
line = "「え──？」"

[[dialogue]]
speaker = "リーナ"
# 「お父さんと、お母さんならおうちに……あれ？　リーナのおうち、どこ……？　リーナのお父さんとお母さんは今……」
line = "「お父さんと、お母さんならおうちに……あれ？　リーナのおうち、どこ……？　リーナのお父さんとお母さんは今……」"

[[dialogue]]
speaker = "リーナ"
# 「そ、そう！　旅行！　福引で旅行が当たっちゃって、２人で遠いところに行っちゃったの」
line = "「そ、そう！　旅行！　福引で旅行が当たっちゃって、２人で遠いところに行っちゃったの」"

[[dialogue]]
speaker = "リーナ"
# 「リーナ、お父さんとお母さんはキライ。何かあるとすぐ『お兄ちゃんはー……』って言うの」
line = "「リーナ、お父さんとお母さんはキライ。何かあるとすぐ『お兄ちゃんはー……』って言うの」"

[[dialogue]]
speaker = "リーナ"
# 「『リーナはお兄ちゃんと違って元気だね』とか『お兄ちゃんの分まで勉強しなさい』とかいちいち言うんだよ」
line = "「『リーナはお兄ちゃんと違って元気だね』とか『お兄ちゃんの分まで勉強しなさい』とかいちいち言うんだよ」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃんはずっと前にいなくなったのに、リーナじゃなくてお兄ちゃんのことばっかり……」
line = "「お兄ちゃんはずっと前にいなくなったのに、リーナじゃなくてお兄ちゃんのことばっかり……」"

[[dialogue]]
speaker = "リーナ"
# 「──！　ごめんごめんごめん！　リーナ変なこと言ってたよね、お兄ちゃんはお兄ちゃんだもんね！」
line = "「──！　ごめんごめんごめん！　リーナ変なこと言ってたよね、お兄ちゃんはお兄ちゃんだもんね！」"

[[dialogue]]
speaker = "リーナ"
# 「……リーナのお兄ちゃんは、ここにいるお兄ちゃんだよね？」
line = "「……リーナのお兄ちゃんは、ここにいるお兄ちゃんだよね？」"

[[dialogue]]
speaker = "unk"
# そ、そうだよ
line = "そ、そうだよ"

[[dialogue]]
speaker = "リーナ"
# 「だよね！　リーナのお兄ちゃんはお兄ちゃんだよね！」
line = "「だよね！　リーナのお兄ちゃんはお兄ちゃんだよね！」"

[[dialogue]]
speaker = "リーナ"
# 「さ、気を取り直してお洋服見に行こっ！　リーナ、お兄ちゃんが好きなお洋服なら何でも着るよっ！」
line = "「さ、気を取り直してお洋服見に行こっ！　リーナ、お兄ちゃんが好きなお洋服なら何でも着るよっ！」"

[[dialogue]]
speaker = "リーナ"
# 「お兄ちゃん大好き<emoji=heart04>　だからお兄ちゃんもリーナのこと大好きだよね<emoji=heart04>」
line = "「お兄ちゃん大好き<emoji=heart04>　だからお兄ちゃんもリーナのこと大好きだよね<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 無邪気に腕に抱きついてくるリーナ。
line = "無邪気に腕に抱きついてくるリーナ。"

[[dialogue]]
speaker = "unk"
# だけどその小さな体は少し震えているように感じた。
line = "だけどその小さな体は少し震えているように感じた。"

[[dialogue]]
speaker = "unk"
# リーナの言葉を否定すると何かが壊れる気がして、ただ頷くことしかできなかった。
line = "リーナの言葉を否定すると何かが壊れる気がして、ただ頷くことしかできなかった。"

[[dialogue]]
speaker = "？？？"
# 「ここが浅草……風情がありますね。雷門と提灯は写真で目にしたことはありましたが、こうして自分の目で見るのは初めてです」
line = "「ここが浅草……風情がありますね。雷門と提灯は写真で目にしたことはありましたが、こうして自分の目で見るのは初めてです」"

[[dialogue]]
speaker = "？？？"
# 「雷門の堂々とした佇まい、威風溢れる風神・雷神。提灯底部の彫刻も見事な迫力です。ああ、美しい……」
line = "「雷門の堂々とした佇まい、威風溢れる風神・雷神。提灯底部の彫刻も見事な迫力です。ああ、美しい……」"

[[dialogue]]
speaker = "？？？"
# 「そうは思いませんか？　そこの星騎士のお方」
line = "「そうは思いませんか？　そこの星騎士のお方」"

[[dialogue]]
speaker = "蛍火"
# 「何か御用でしょうか？　私はこの近くに評判の店ができたと聞いてきたのですが……」
line = "「何か御用でしょうか？　私はこの近くに評判の店ができたと聞いてきたのですが……」"

[[dialogue]]
speaker = "？？？"
# 「それはとてもいいことを聞きました。私も気になるので、ぜひお聞かせ願いたいです」
line = "「それはとてもいいことを聞きました。私も気になるので、ぜひお聞かせ願いたいです」"

[[dialogue]]
speaker = "蛍火"
# 「そう言いながら、まとっているのは尋常な殺気ではありませんね」
line = "「そう言いながら、まとっているのは尋常な殺気ではありませんね」"

[[dialogue]]
speaker = "？？？"
# 「おや。殺気なんてとんでもありません。あなたを前にして少々昂っているだけですよ。──東雲蛍火さん」
line = "「おや。殺気なんてとんでもありません。あなたを前にして少々昂っているだけですよ。──東雲蛍火さん」"

[[dialogue]]
speaker = "蛍火"
# 「……私のことをご存じで？」
line = "「……私のことをご存じで？」"

[[dialogue]]
speaker = "？？？"
# 「もちろんですとも。昨年度の星徒会役員ともなれば、知らないはずありません」
line = "「もちろんですとも。昨年度の星徒会役員ともなれば、知らないはずありません」"

[[dialogue]]
speaker = "ヴァレリー"
# 「おっと、申し遅れました。私の名はヴァレリー・スチュアート。あなたのファンなんです」
line = "「おっと、申し遅れました。私の名はヴァレリー・スチュアート。あなたのファンなんです」"

[[dialogue]]
speaker = "蛍火"
# 「……？」
line = "「……？」"

[[dialogue]]
speaker = "ヴァレリー"
# 「あれ、おかしなことを言いましたかね？　世界を守るために戦う星騎士……その中でも特に優れた力を持つ星徒会役員はまさしく綺羅星のような存在」
line = "「あれ、おかしなことを言いましたかね？　世界を守るために戦う星騎士……その中でも特に優れた力を持つ星徒会役員はまさしく綺羅星のような存在」"

[[dialogue]]
speaker = "ヴァレリー"
# 「憧れる者がいても何も不思議ではないでしょう？」
line = "「憧れる者がいても何も不思議ではないでしょう？」"

[[dialogue]]
speaker = "蛍火"
# 「憧れ……ですか」
line = "「憧れ……ですか」"

[[dialogue]]
speaker = "ヴァレリー"
# 「ええ。この胸の高鳴りはそれ以外ありえません」
line = "「ええ。この胸の高鳴りはそれ以外ありえません」"

[[dialogue]]
speaker = "ヴァレリー"
# 「しかし私は、あなたの美をもっと輝かせたいとも思っているのです」
line = "「しかし私は、あなたの美をもっと輝かせたいとも思っているのです」"

[[dialogue]]
speaker = "蛍火"
# 「輝かせる……？」
line = "「輝かせる……？」"

[[dialogue]]
speaker = "ヴァレリー"
# 「はい」
line = "「はい」"

[[dialogue]]
speaker = "ヴァレリー"
# 「だって美しいものは、壊れる瞬間が最も輝くのですから……！」
line = "「だって美しいものは、壊れる瞬間が最も輝くのですから……！」"

[[dialogue]]
speaker = "蛍火"
# 「！　まさかあなたはコラプサーの──」
line = "「！　まさかあなたはコラプサーの──」"

[[dialogue]]
speaker = "蛍火"
# 「東雲蛍火、参ります──！」
line = "「東雲蛍火、参ります──！」"
