[[dialogue]]
speaker = "unk"
# そうして始まったおなか部への特別試験だったが──
line = "そうして始まったおなか部への特別試験だったが──"

[[dialogue]]
speaker = "パルミエ"
# 「ぜぇぜぇ、もう限界よ……。や、休ませて……」
line = "「ぜぇぜぇ、もう限界よ……。や、休ませて……」"

[[dialogue]]
speaker = "シフォン"
# 「だらしないですね。まだ始めたばかりじゃないですか」
line = "「だらしないですね。まだ始めたばかりじゃないですか」"

[[dialogue]]
speaker = "モナカ"
# 「えへへ、お掃除、お掃除、ピッカピカ～……♪」
line = "「えへへ、お掃除、お掃除、ピッカピカ～……♪」"

[[dialogue]]
speaker = "unk"
# 次はカフェテリアの手伝いだね
line = "次はカフェテリアの手伝いだね"

[[dialogue]]
speaker = "シフォン"
# 「その後は倉庫の整理に、資料の仕分け、壊れた器具の修理ですか」
line = "「その後は倉庫の整理に、資料の仕分け、壊れた器具の修理ですか」"

[[dialogue]]
speaker = "シフォン"
# 「なんだか拍子抜けですね。特別試験と言うからにはもっと大変なことを頼まれると思ってましたのに」
line = "「なんだか拍子抜けですね。特別試験と言うからにはもっと大変なことを頼まれると思ってましたのに」"

[[dialogue]]
speaker = "パルミエ"
# 「十分大変よぉ……。うぅ、こんなはずじゃなかったのにぃ……」
line = "「十分大変よぉ……。うぅ、こんなはずじゃなかったのにぃ……」"

[[dialogue]]
speaker = "モナカ"
# 「えへへ、でもなんだかやり甲斐があるね……？」
line = "「えへへ、でもなんだかやり甲斐があるね……？」"

[[dialogue]]
speaker = "シフォン"
# 「ええ。こういうモンスターが関わらない仕事こそ、おなか部の本分ですから」
line = "「ええ。こういうモンスターが関わらない仕事こそ、おなか部の本分ですから」"

[[dialogue]]
speaker = "パルミエ"
# 「こんなのただ雑用を押しつけられてるだけじゃな～い。私が宿題押しつけるのとどう違うのよぉ～」
line = "「こんなのただ雑用を押しつけられてるだけじゃな～い。私が宿題押しつけるのとどう違うのよぉ～」"

[[dialogue]]
speaker = "モナカ"
# 「だけど、こんなことで本当にプリマステラになれるのかな……？　普通にお掃除してるだけだけど……」
line = "「だけど、こんなことで本当にプリマステラになれるのかな……？　普通にお掃除してるだけだけど……」"

[[dialogue]]
speaker = "シフォン"
# 「そうですね……何か秘密の意図があるのでしょうか？」
line = "「そうですね……何か秘密の意図があるのでしょうか？」"

[[dialogue]]
speaker = "パルミエ"
# 「あ、わかったわ。星力を使って依頼をこなせってことじゃない？　そのためにダーリンが付いてくれてるんでしょ？」
line = "「あ、わかったわ。星力を使って依頼をこなせってことじゃない？　そのためにダーリンが付いてくれてるんでしょ？」"

[[dialogue]]
speaker = "unk"
# ああ、ヴィーナスからも許可は出てるよ
line = "ああ、ヴィーナスからも許可は出てるよ"

[[dialogue]]
speaker = "パルミエ"
# 「ほらやっぱり！　だと思ったのよ～。この子たち、いつも星力の制御に失敗して試験に落ちてばかりだから」
line = "「ほらやっぱり！　だと思ったのよ～。この子たち、いつも星力の制御に失敗して試験に落ちてばかりだから」"

[[dialogue]]
speaker = "シフォン"
# 「な、なるほど。つまりそういう試験だったわけですね。今日一日、星力を使って依頼を解決して回って、その結果を見る。と……」
line = "「な、なるほど。つまりそういう試験だったわけですね。今日一日、星力を使って依頼を解決して回って、その結果を見る。と……」"

[[dialogue]]
speaker = "モナカ"
# 「そこに気付くところから試験だったってこと……？　あぅ、だったら出遅れちゃったかも……」
line = "「そこに気付くところから試験だったってこと……？　あぅ、だったら出遅れちゃったかも……」"

[[dialogue]]
speaker = "パルミエ"
# 「今からでも全然遅くないわ。ほらみんな変身変身♪」
line = "「今からでも全然遅くないわ。ほらみんな変身変身♪」"

[[dialogue]]
speaker = "モナカ"
# 「う、うん」
line = "「う、うん」"

[[dialogue]]
speaker = "シフォン"
# 「あまり戦闘服姿は好きではないんですが……」
line = "「あまり戦闘服姿は好きではないんですが……」"

[[dialogue]]
speaker = "パルミエ"
# 「あ～、これで楽ができるわ～。水精ちゃんたち～。後は任せたわよ～」
line = "「あ～、これで楽ができるわ～。水精ちゃんたち～。後は任せたわよ～」"

[[dialogue]]
speaker = "モナカ"
# 「わぁ、水精さんたちが箒を持ってお掃除してくれてる……。流石はパルちゃんだね……。すごいなぁ……」
line = "「わぁ、水精さんたちが箒を持ってお掃除してくれてる……。流石はパルちゃんだね……。すごいなぁ……」"

[[dialogue]]
speaker = "シフォン"
# 「パルミエはホント器用に星力を扱いますよね。普段もお菓子の買い出しからマッサージまで水精にさせていますし」
line = "「パルミエはホント器用に星力を扱いますよね。普段もお菓子の買い出しからマッサージまで水精にさせていますし」"

[[dialogue]]
speaker = "パルミエ"
# 「ふふん、それほどでもないわよ♪　常日頃からいかに星力を上手く使って楽をできるか考えてるだ～け♪」
line = "「ふふん、それほどでもないわよ♪　常日頃からいかに星力を上手く使って楽をできるか考えてるだ～け♪」"

[[dialogue]]
speaker = "モナカ"
# 「あ、あはは、どや顔で言うことなのかなぁ……」
line = "「あ、あはは、どや顔で言うことなのかなぁ……」"

[[dialogue]]
speaker = "シフォン"
# 「ま、これで頭数も増えましたし、ちゃっちゃと終わらせちゃいましょう。ほらパルミエもサボってないで箒を持ってください」
line = "「ま、これで頭数も増えましたし、ちゃっちゃと終わらせちゃいましょう。ほらパルミエもサボってないで箒を持ってください」"

[[dialogue]]
speaker = "パルミエ"
# 「それじゃ意味ないじゃなーい。私が何もしなくて済むように水精ちゃんを出したんだから～」
line = "「それじゃ意味ないじゃなーい。私が何もしなくて済むように水精ちゃんを出したんだから～」"

[[dialogue]]
speaker = "unk"
# ３人とも仲が良いよね
line = "３人とも仲が良いよね"

[[dialogue]]
speaker = "モナカ"
# 「えへへ、モナカたち、小さい頃からずっと一緒だから……」
line = "「えへへ、モナカたち、小さい頃からずっと一緒だから……」"

[[dialogue]]
speaker = "シフォン"
# 「幼馴染みというヤツですよ。私たち、同じ田舎町出身でして」
line = "「幼馴染みというヤツですよ。私たち、同じ田舎町出身でして」"

[[dialogue]]
speaker = "パルミエ"
# 「２人とも私が大好きすぎて学園まで追いかけてきたくらいだものね～♪　ホント私って罪な女だわ～♪」
line = "「２人とも私が大好きすぎて学園まで追いかけてきたくらいだものね～♪　ホント私って罪な女だわ～♪」"

[[dialogue]]
speaker = "シフォン"
# 「寂しいから２人とも早く来て～。とか毎日毎日電話かけてきたのはどこの誰ですか、まったく……」
line = "「寂しいから２人とも早く来て～。とか毎日毎日電話かけてきたのはどこの誰ですか、まったく……」"

[[dialogue]]
speaker = "モナカ"
# 「でも良かったね……。ちゃんと３人揃って入学できて……。モナカ、落ちこぼれだから……。１人だけ入学できないかもって不安だったの……」
line = "「でも良かったね……。ちゃんと３人揃って入学できて……。モナカ、落ちこぼれだから……。１人だけ入学できないかもって不安だったの……」"

[[dialogue]]
speaker = "シフォン"
# 「ふふ、あとは揃ってプリマステラになるだけです！　気合いを入れ直して試験に取り組みましょう！」
line = "「ふふ、あとは揃ってプリマステラになるだけです！　気合いを入れ直して試験に取り組みましょう！」"

[[dialogue]]
speaker = "パルミエ"
# 「あんまり張り切りすぎないようにね～。シフォンはやる気を出せば出すほど周りが見えなくなる脳筋アホの子なんだから～」
line = "「あんまり張り切りすぎないようにね～。シフォンはやる気を出せば出すほど周りが見えなくなる脳筋アホの子なんだから～」"

[[dialogue]]
speaker = "シフォン"
# 「だ、誰が脳筋アホの子ですか！　万年グータラ娘に言われたくありません！」
line = "「だ、誰が脳筋アホの子ですか！　万年グータラ娘に言われたくありません！」"

[[dialogue]]
speaker = "モナカ"
# 「あわわ、２人とも今は試験に集中しないとだから……」
line = "「あわわ、２人とも今は試験に集中しないとだから……」"

[[dialogue]]
speaker = "シフォン"
# 「ふぅ。これで頼まれていた仕事は大体片付きましたかね」
line = "「ふぅ。これで頼まれていた仕事は大体片付きましたかね」"

[[dialogue]]
speaker = "パルミエ"
# 「シフォンのせいで倍の時間がかかったけれどね～。鍋の中に香辛料を一瓶丸々ぶちこんだり、修理を頼まれてた品を叩いてぶっ壊そうとしちゃうんだもの～」
line = "「シフォンのせいで倍の時間がかかったけれどね～。鍋の中に香辛料を一瓶丸々ぶちこんだり、修理を頼まれてた品を叩いてぶっ壊そうとしちゃうんだもの～」"

[[dialogue]]
speaker = "シフォン"
# 「う、うるさいですね。カフェテリアの料理なんて大味でいいんです！　電化製品もとりあえず叩いておけば直るんですから！」
line = "「う、うるさいですね。カフェテリアの料理なんて大味でいいんです！　電化製品もとりあえず叩いておけば直るんですから！」"

[[dialogue]]
speaker = "モナカ"
# 「あ、あはは……。料理も修理もモナカがちゃんとしておいたから……」
line = "「あ、あはは……。料理も修理もモナカがちゃんとしておいたから……」"

[[dialogue]]
speaker = "パルミエ"
# 「モナカはしっかりしてるわね～。偉いわよ～」
line = "「モナカはしっかりしてるわね～。偉いわよ～」"

[[dialogue]]
speaker = "モナカ"
# 「えへへ、モナカ、部長さんだから。パルちゃんにはもう少し真面目になってもらいたいけど……」
line = "「えへへ、モナカ、部長さんだから。パルちゃんにはもう少し真面目になってもらいたいけど……」"

[[dialogue]]
speaker = "パルミエ"
# 「あら、言われちゃってるわよ、シフォン」
line = "「あら、言われちゃってるわよ、シフォン」"

[[dialogue]]
speaker = "シフォン"
# 「あなたに言ってるんですよ！？」
line = "「あなたに言ってるんですよ！？」"

[[dialogue]]
speaker = "unk"
# 次の依頼で最後だっけ？
line = "次の依頼で最後だっけ？"

[[dialogue]]
speaker = "シフォン"
# 「そうですね。この手紙だけはヴィーナスさんから最後に開くようにと言われてまして」
line = "「そうですね。この手紙だけはヴィーナスさんから最後に開くようにと言われてまして」"

[[dialogue]]
speaker = "モナカ"
# 「これが本番ってことかな……？　どんなお悩み相談なの……？」
line = "「これが本番ってことかな……？　どんなお悩み相談なの……？」"

[[dialogue]]
speaker = "シフォン"
# 「どうやら最近、寮の冷蔵庫やお菓子棚から物がなくなってるみたいです。複数人の生徒たちから同じ相談が届いてるみたいですね」
line = "「どうやら最近、寮の冷蔵庫やお菓子棚から物がなくなってるみたいです。複数人の生徒たちから同じ相談が届いてるみたいですね」"

[[dialogue]]
speaker = "モナカ"
# 「お、お菓子泥棒ってこと……？　そんな人がこの学園にいるなんて……」
line = "「お、お菓子泥棒ってこと……？　そんな人がこの学園にいるなんて……」"

[[dialogue]]
speaker = "シフォン"
# 「まだ学園の生徒とは決まってませんよ。外部犯かもしれません」
line = "「まだ学園の生徒とは決まってませんよ。外部犯かもしれません」"

[[dialogue]]
speaker = "パルミエ"
# 「面倒くさそうな相談ね～。そうだ、星徒会に任せちゃったらいいんじゃないかしら♪」
line = "「面倒くさそうな相談ね～。そうだ、星徒会に任せちゃったらいいんじゃないかしら♪」"

[[dialogue]]
speaker = "モナカ"
# 「そ、その星徒会さんから頼まれてるんだよね……？」
line = "「そ、その星徒会さんから頼まれてるんだよね……？」"

[[dialogue]]
speaker = "シフォン"
# 「とにかく早速張り込んでみましょう！　善は急げです！」
line = "「とにかく早速張り込んでみましょう！　善は急げです！」"
