[[dialogue]]
speaker = "ユウリ"
# 「あんたの趣味か？　趣味なのかっ！？　返答次第じゃ今日の夕陽は拝ませねえぞ！？」
line = "「あんたの趣味か？　趣味なのかっ！？　返答次第じゃ今日の夕陽は拝ませねえぞ！？」"

[[dialogue]]
speaker = "ユーリス"
# 「い、いえ、こ、これはその……違うんです！　誤解です！」
line = "「い、いえ、こ、これはその……違うんです！　誤解です！」"

[[dialogue]]
speaker = "セーラ"
# 「なーるなる。カジノといえばバニーガールだもんね～。こりゃ納得するしかないよ、ユウリちゃん♪」
line = "「なーるなる。カジノといえばバニーガールだもんね～。こりゃ納得するしかないよ、ユウリちゃん♪」"

[[dialogue]]
speaker = "ユウリ"
# 「んじゃあたしらもシャツとベストでいいじゃないっすか！　百歩譲ってウサ耳までだろ！？」
line = "「んじゃあたしらもシャツとベストでいいじゃないっすか！　百歩譲ってウサ耳までだろ！？」"

[[dialogue]]
speaker = "ユーリス"
# 「勇者スキル『早着替え』は聖剣自身が最適な形態を選択する仕組みでして……」
line = "「勇者スキル『早着替え』は聖剣自身が最適な形態を選択する仕組みでして……」"

[[dialogue]]
speaker = "ユウリ"
# 「はぁ～っ！？　じゃあこの聖剣がバニーを選んだってのかよ！？　どうなってんだよあんたの王国は！？」
line = "「はぁ～っ！？　じゃあこの聖剣がバニーを選んだってのかよ！？　どうなってんだよあんたの王国は！？」"

[[dialogue]]
speaker = "ユーリス"
# （反論できない……！）
line = "（反論できない……！）"

[[dialogue]]
speaker = "ユウリ"
# 「肩も足も出てるし……こんなエロ衣装、誰が進んで着たがるんだよ！？」
line = "「肩も足も出てるし……こんなエロ衣装、誰が進んで着たがるんだよ！？」"

[[dialogue]]
speaker = "セーラ"
# 「えーそう？　うちは着てみたいと思ってたケドな～。バニースーツ可愛いじゃん♪　おっぱい超盛りやすいし、お尻や太もももムチムチに見えるし♪」
line = "「えーそう？　うちは着てみたいと思ってたケドな～。バニースーツ可愛いじゃん♪　おっぱい超盛りやすいし、お尻や太もももムチムチに見えるし♪」"

[[dialogue]]
speaker = "ユウリ"
# 「セーラさんは普段から胸の谷間おっぴろげてるからそう思うだけで……！　あたしはこういうの似合わないんすってば！」
line = "「セーラさんは普段から胸の谷間おっぴろげてるからそう思うだけで……！　あたしはこういうの似合わないんすってば！」"

[[dialogue]]
speaker = "セーラ"
# 「人を脱ぎたがりみたいに言わないでってばー。てゆかユウリちゃんも超似合ってるって。新星の会長さんもそう思うっしょ？」
line = "「人を脱ぎたがりみたいに言わないでってばー。てゆかユウリちゃんも超似合ってるって。新星の会長さんもそう思うっしょ？」"

[[dialogue]]
speaker = "unk"
# ２人ともエ──すごく可愛いよ
line = "２人ともエ──すごく可愛いよ"

[[dialogue]]
speaker = "ユウリ"
# 「いまエロいっつおうとしたよな！？　まさかあんたも共犯か、この真性のエロ会長っ！」
line = "「いまエロいっつおうとしたよな！？　まさかあんたも共犯か、この真性のエロ会長っ！」"

[[dialogue]]
speaker = "セーラ"
# 「お、上手いこと言うね～♪　真性と新星をかけたワケだ♪」
line = "「お、上手いこと言うね～♪　真性と新星をかけたワケだ♪」"

[[dialogue]]
speaker = "ユウリ"
# 「別にかけたつもりじゃないっすよ！？」
line = "「別にかけたつもりじゃないっすよ！？」"

[[dialogue]]
speaker = "ユーリス"
# 「と、とにかく申し訳ありませんでしたっ。まさかこうなるとは思いもしなかったもので……」
line = "「と、とにかく申し訳ありませんでしたっ。まさかこうなるとは思いもしなかったもので……」"

[[dialogue]]
speaker = "ユウリ"
# 「少し考えりゃわかるだろ！？　あんたも海パン一丁で過ごしてみろ！？」
line = "「少し考えりゃわかるだろ！？　あんたも海パン一丁で過ごしてみろ！？」"

[[dialogue]]
speaker = "ユーリス"
# 「海パン一丁って──わ、私がですかっ！？　そんな破廉恥な真似できるわけがっ……！」
line = "「海パン一丁って──わ、私がですかっ！？　そんな破廉恥な真似できるわけがっ……！」"

[[dialogue]]
speaker = "ユウリ"
# 「そのできるわけのない破廉恥な真似をあんたはあたしにやらせてんだよぉ～……！」
line = "「そのできるわけのない破廉恥な真似をあんたはあたしにやらせてんだよぉ～……！」"

[[dialogue]]
speaker = "unk"
# まぁまぁ落ち着いて
line = "まぁまぁ落ち着いて"

[[dialogue]]
speaker = "ユウリ"
# 「こっち見んじゃねえ！　こんな格好で人前に出ろっつーなら、あたし……！」
line = "「こっち見んじゃねえ！　こんな格好で人前に出ろっつーなら、あたし……！」"

[[dialogue]]
speaker = "セーラ"
# 「まさかバイト辞めるとかゆわないよね～？　後輩がお腹空かせて待ってるぞ～？　近々誕生日会もあるとか聞いたケド？」
line = "「まさかバイト辞めるとかゆわないよね～？　後輩がお腹空かせて待ってるぞ～？　近々誕生日会もあるとか聞いたケド？」"

[[dialogue]]
speaker = "ユウリ"
# 「うっ、確かにあのバイト代は見過ごせねえ……！　豪勢な誕生日会開いてやるって啖呵切っちまってるし……！」
line = "「うっ、確かにあのバイト代は見過ごせねえ……！　豪勢な誕生日会開いてやるって啖呵切っちまってるし……！」"

[[dialogue]]
speaker = "セーラ"
# 「なら頑張らないと♪　王子も悪気があったわけじゃないんだしさ～？」
line = "「なら頑張らないと♪　王子も悪気があったわけじゃないんだしさ～？」"

[[dialogue]]
speaker = "セーラ"
# 「だよね、王子<emoji=heart04>　うちらのセクシーな格好見たくてバニーにしたわけじゃないよね～<emoji=heart04>」
line = "「だよね、王子<emoji=heart04>　うちらのセクシーな格好見たくてバニーにしたわけじゃないよね～<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「は、はい。それはもちろん」
line = "「は、はい。それはもちろん」"

[[dialogue]]
speaker = "セーラ"
# 「……あれ？　うち、あんま似合ってない？」
line = "「……あれ？　うち、あんま似合ってない？」"

[[dialogue]]
speaker = "ユーリス"
# 「へ？　いえ、とてもお似合いかと思いますが……」
line = "「へ？　いえ、とてもお似合いかと思いますが……」"

[[dialogue]]
speaker = "セーラ"
# 「なら反応が薄いな～。こーんなに近づいてるのに。もしかしてもしかして、王子って女の子に興味ない感じ？」
line = "「なら反応が薄いな～。こーんなに近づいてるのに。もしかしてもしかして、王子って女の子に興味ない感じ？」"

[[dialogue]]
speaker = "ユーリス"
# 「そ、そんなことはないですよっ？　興味津々です！　男ですからね！」
line = "「そ、そんなことはないですよっ？　興味津々です！　男ですからね！」"

[[dialogue]]
speaker = "セーラ"
# 「その割には全然ドキドキしてなさそーな。新星の会長さん的には、うちのバニー姿どう思う？」
line = "「その割には全然ドキドキしてなさそーな。新星の会長さん的には、うちのバニー姿どう思う？」"

[[dialogue]]
speaker = "unk"
# い、いつも以上に絶景です……
line = "い、いつも以上に絶景です……"

[[dialogue]]
speaker = "セーラ"
# 「そーそーそうゆう反応が見たかったんだよ～♪　自己肯定感爆上がり♪　くれぐれもバイト中に鼻の下伸ばさないようにね～<emoji=heart04>」
line = "「そーそーそうゆう反応が見たかったんだよ～♪　自己肯定感爆上がり♪　くれぐれもバイト中に鼻の下伸ばさないようにね～<emoji=heart04>」"

[[dialogue]]
speaker = "ユーリス"
# 「な……なるほど。男なら鼻の下を伸ばすべきだったのですね……。あれくらい凝視する方が女性の自信にも繋がる、と……」
line = "「な……なるほど。男なら鼻の下を伸ばすべきだったのですね……。あれくらい凝視する方が女性の自信にも繋がる、と……」"

[[dialogue]]
speaker = "ユウリ"
# 「……ん？　ちょっ──てめっ、なに人の胸覗き込もうとしてやがんだ、ぶっ殺すぞ！？」
line = "「……ん？　ちょっ──てめっ、なに人の胸覗き込もうとしてやがんだ、ぶっ殺すぞ！？」"

[[dialogue]]
speaker = "ユーリス"
# 「えっ！？　す、少しでも励みになればと思いまして……！」
line = "「えっ！？　す、少しでも励みになればと思いまして……！」"

[[dialogue]]
speaker = "ユウリ"
# 「人の胸見て何に励むつもりだ、このエロ王子！　次覗き込もうとしたら本気でぶっ飛ばすからな！？」
line = "「人の胸見て何に励むつもりだ、このエロ王子！　次覗き込もうとしたら本気でぶっ飛ばすからな！？」"

[[dialogue]]
speaker = "ユーリス"
# 「ご、ごめんなさ～いっ！！」
line = "「ご、ごめんなさ～いっ！！」"

[[dialogue]]
speaker = "セーラ"
# 「ん～……？　王子ってどっか不思議だねー？　男の子として、ちょっちズレてるってゆーか……」
line = "「ん～……？　王子ってどっか不思議だねー？　男の子として、ちょっちズレてるってゆーか……」"

[[dialogue]]
speaker = "unk"
# そ、それより肩慣らしでもしておかないか？
line = "そ、それより肩慣らしでもしておかないか？"

[[dialogue]]
speaker = "セーラ"
# 「あー確かに。力の使い方も変わってるもんね～」
line = "「あー確かに。力の使い方も変わってるもんね～」"

[[dialogue]]
speaker = "ユウリ"
# 「まさかこの格好でトレーニング行く気っすか！？　あたしはごめんすよ……」
line = "「まさかこの格好でトレーニング行く気っすか！？　あたしはごめんすよ……」"

[[dialogue]]
speaker = "セーラ"
# 「人目には慣れておいた方がいーって。じゃないといざという時に対応できないじゃん」
line = "「人目には慣れておいた方がいーって。じゃないといざという時に対応できないじゃん」"

[[dialogue]]
speaker = "ユウリ"
# 「それはそうっすけどっ」
line = "「それはそうっすけどっ」"

[[dialogue]]
speaker = "ユーリス"
# 「！　どうやら街にモンスターが出現したようです！」
line = "「！　どうやら街にモンスターが出現したようです！」"

[[dialogue]]
speaker = "セーラ"
# 「お<ruby=あつら>誂</ruby>え向きじゃん♪　前哨戦に蹴散らしちゃおうよ♪」
line = "「お<ruby>誂<rt>あつら</rt></ruby>え向きじゃん♪　前哨戦に蹴散らしちゃおうよ♪」"

[[dialogue]]
speaker = "ユウリ"
# 「蹴散らしにって──この格好で！？」
line = "「蹴散らしにって──この格好で！？」"

[[dialogue]]
speaker = "セーラ"
# 「ふ。羞恥心はここに置いていきな、お嬢さん……。そんな重たい荷物背負ってたら次の戦場じゃ生きていけないぜ？」
line = "「ふ。羞恥心はここに置いていきな、お嬢さん……。そんな重たい荷物背負ってたら次の戦場じゃ生きていけないぜ？」"

[[dialogue]]
speaker = "ユウリ"
# 「セーラさんはなんでそんなノリノリなんすか！？」
line = "「セーラさんはなんでそんなノリノリなんすか！？」"

[[dialogue]]
speaker = "unk"
# とにかく急ごう！
line = "とにかく急ごう！"

[[dialogue]]
speaker = "ユウリ"
# 「嘘だろ、おいっ！？　今回ばかりは他の人に任せて──」
line = "「嘘だろ、おいっ！？　今回ばかりは他の人に任せて──」"

[[dialogue]]
speaker = "セーラ"
# 「いいからいいから♪　はい連行♪」
line = "「いいからいいから♪　はい連行♪」"

[[dialogue]]
speaker = "ユウリ"
# 「い──嫌だぁぁああっ～～！！　行きたくないっ～～！！」
line = "「い──嫌だぁぁああっ～～！！　行きたくないっ～～！！」"

[[dialogue]]
speaker = "ユーリス"
# 「いましたっ！　あそこです！」
line = "「いましたっ！　あそこです！」"

[[dialogue]]
speaker = "セーラ"
# 「よーし行くよユウリちゃん！　セクシーに決めちゃうよん！」
line = "「よーし行くよユウリちゃん！　セクシーに決めちゃうよん！」"

[[dialogue]]
speaker = "ユウリ"
# 「こんな姿あたしのキャラじゃねえ……。こんな姿あたしのキャラじゃねえ……。こんな姿あたしのキャラじゃねえ……！」
line = "「こんな姿あたしのキャラじゃねえ……。こんな姿あたしのキャラじゃねえ……。こんな姿あたしのキャラじゃねえ……！」"

[[dialogue]]
speaker = "ユーリス"
# 「ふぅ。どうやら皆さん、問題なく戦えそうですね」
line = "「ふぅ。どうやら皆さん、問題なく戦えそうですね」"

[[dialogue]]
speaker = "セーラ"
# 「ユウリちゃんも上手く新しい力使いこなしてたじゃん♪　サイコロを武器にするなんて超お洒落だし♪」
line = "「ユウリちゃんも上手く新しい力使いこなしてたじゃん♪　サイコロを武器にするなんて超お洒落だし♪」"

[[dialogue]]
speaker = "ユウリ"
# 「み、見られた……。こんな格好してるとこ、街の人に……。あはは、もうあたし、お嫁に行けねえ……」
line = "「み、見られた……。こんな格好してるとこ、街の人に……。あはは、もうあたし、お嫁に行けねえ……」"

[[dialogue]]
speaker = "セーラ"
# 「あー……燃え尽きちゃってるや。バイトまでに血の気が戻るといいけど」
line = "「あー……燃え尽きちゃってるや。バイトまでに血の気が戻るといいけど」"

[[dialogue]]
speaker = "ユーリス"
# 「スタイルが良くてとてもお似合いだと思うのですが……」
line = "「スタイルが良くてとてもお似合いだと思うのですが……」"

[[dialogue]]
speaker = "unk"
# うな垂れると谷間がさらに──
line = "うな垂れると谷間がさらに──"

[[dialogue]]
speaker = "ユウリ"
# 「～～っっ！？　どこ見てんだ、このエロ会長！！」
line = "「～～っっ！？　どこ見てんだ、このエロ会長！！」"

[[dialogue]]
speaker = "unk"
# ユウリの平手の音が、小気味よく街に響いたのだった──
line = "ユウリの平手の音が、小気味よく街に響いたのだった──"
