[[dialogue]]
speaker = "unk"
# それから数日後、募集を見て名乗りを上げたメンバーが集められた。
line = "それから数日後、募集を見て名乗りを上げたメンバーが集められた。"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「おーっほっほっほ！　皆さん、よくぞ集まってくださいましたわ！　私が流星寮の寮長、千園寺ヒルディオーネですの！」
line = "「おーっほっほっほ！　皆さん、よくぞ集まってくださいましたわ！　私が流星寮の寮長、千園寺ヒルディオーネですの！」"

[[dialogue]]
speaker = "アニュラス"
# 「流星学園１年、アニュラス・セイファートだ。よろしく頼む」
line = "「流星学園１年、アニュラス・セイファートだ。よろしく頼む」"

[[dialogue]]
speaker = "舞亜"
# 「同じく流星学園１年の柊舞亜です。素敵なパーティーになるよう頑張りますねっ」
line = "「同じく流星学園１年の柊舞亜です。素敵なパーティーになるよう頑張りますねっ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「アニュラスさんは前学園長の息女にして優秀な星騎士。舞亜さんはフィギュアスケート選手として語るまでもないほどの世界的有名人……」
line = "「アニュラスさんは前学園長の息女にして優秀な星騎士。舞亜さんはフィギュアスケート選手として語るまでもないほどの世界的有名人……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「申し分ない人材ですわ！　きっと素晴らしいクリスマスパーティーになることでしょう！　ところで──」
line = "「申し分ない人材ですわ！　きっと素晴らしいクリスマスパーティーになることでしょう！　ところで──」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「あなたも実行委員に参加希望ですの？　あなたは確か星見家に住んでいて……つまり流星寮の生徒ではありませんわよね？」
line = "「あなたも実行委員に参加希望ですの？　あなたは確か星見家に住んでいて……つまり流星寮の生徒ではありませんわよね？」"

[[dialogue]]
speaker = "アポロ"
# 「おう、それがどうかしたのか？」
line = "「おう、それがどうかしたのか？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「流星寮のクリスマスパーティーですのよ？　なぜ寮生でもないあなたが応募してくるんですの？」
line = "「流星寮のクリスマスパーティーですのよ？　なぜ寮生でもないあなたが応募してくるんですの？」"

[[dialogue]]
speaker = "アポロ"
# 「ポスターを見て楽しそうだったからだ！　それに募集の条件に『流星寮で生活している寮生であること』なんて書いてなかったぞ？」
line = "「ポスターを見て楽しそうだったからだ！　それに募集の条件に『流星寮で生活している寮生であること』なんて書いてなかったぞ？」"

[[dialogue]]
speaker = "舞亜"
# 「確かに書いてないね」
line = "「確かに書いてないね」"

[[dialogue]]
speaker = "アニュラス"
# 「ああ、書いていなかったな」
line = "「ああ、書いていなかったな」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「うぐぐ……フニ、これはどういうことですの？」
line = "「うぐぐ……フニ、これはどういうことですの？」"

[[dialogue]]
speaker = "フェニエル"
# 「すみません……ちょっとした手違いで流星寮だけではなく、学園の掲示板にも募集のポスターが貼られてしまったみたいで……」
line = "「すみません……ちょっとした手違いで流星寮だけではなく、学園の掲示板にも募集のポスターが貼られてしまったみたいで……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「し、仕方ありませんわ。あなたは附属生ですわよね？　流星学園の生徒であればギリギリセーフですの──」
line = "「し、仕方ありませんわ。あなたは附属生ですわよね？　流星学園の生徒であればギリギリセーフですの──」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「で、あなたはどうしてここにいますの？」
line = "「で、あなたはどうしてここにいますの？」"

[[dialogue]]
speaker = "unk"
# すみません……
line = "すみません……"

[[dialogue]]
speaker = "アポロ"
# 「あたしが連れてきたんだ。ダメだったか？」
line = "「あたしが連れてきたんだ。ダメだったか？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ダメに決まっていますわ！　この人は新星学園の、しかも会長ではありませんのっ！」
line = "「ダメに決まっていますわ！　この人は新星学園の、しかも会長ではありませんのっ！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「それがどうして流星寮のクリスマスパーティーの実行委員になるなんてことになりますのっ！」
line = "「それがどうして流星寮のクリスマスパーティーの実行委員になるなんてことになりますのっ！」"

[[dialogue]]
speaker = "アポロ"
# 「でも募集の条件には『新星学園の生徒はダメ』なんて書いてなかったぞ！」
line = "「でも募集の条件には『新星学園の生徒はダメ』なんて書いてなかったぞ！」"

[[dialogue]]
speaker = "舞亜"
# 「うんうん、書いてなかったね」
line = "「うんうん、書いてなかったね」"

[[dialogue]]
speaker = "アニュラス"
# 「ああ、書いていなかったな」
line = "「ああ、書いていなかったな」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ああもうっ、いいですわっ！　許可しますっ！」
line = "「ああもうっ、いいですわっ！　許可しますっ！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「あなたなら真面目に力を貸してくれそうですし、人手は多いに越したことはないでしょうから！」
line = "「あなたなら真面目に力を貸してくれそうですし、人手は多いに越したことはないでしょうから！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ただし、これ以上はダメですわ！　あくまでこれは流星寮のパーティーなんですから！」
line = "「ただし、これ以上はダメですわ！　あくまでこれは流星寮のパーティーなんですから！」"

[[dialogue]]
speaker = "unk"
# よろしく頼むな
line = "よろしく頼むな"

[[dialogue]]
speaker = "unk"
# アニュラス、舞亜、アポロ
line = "アニュラス、舞亜、アポロ"

[[dialogue]]
speaker = "アポロ"
# 「おう！　みんなもよろしくっ！」
line = "「おう！　みんなもよろしくっ！」"

[[dialogue]]
speaker = "アニュラス"
# 「よろしく頼む」
line = "「よろしく頼む」"

[[dialogue]]
speaker = "舞亜"
# 「よろしくね～♪」
line = "「よろしくね～♪」"

[[dialogue]]
speaker = "ヒルディオーネ"
# （想定外の人材が紛れ込みましたけれど……まあ、アニュラスさんと舞亜さんがいれば大丈夫でしょう）
line = "（想定外の人材が紛れ込みましたけれど……まあ、アニュラスさんと舞亜さんがいれば大丈夫でしょう）"

[[dialogue]]
speaker = "ヒルディオーネ"
# （アポロさんがいれば附属生の意見も取り入れることができますし、会長にまとめ役になってもらえば……案外悪くない布陣かもしれません）
line = "（アポロさんがいれば附属生の意見も取り入れることができますし、会長にまとめ役になってもらえば……案外悪くない布陣かもしれません）"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「では、流星寮クリスマスパーティー実行委員の設立をここに宣言しますわ」
line = "「では、流星寮クリスマスパーティー実行委員の設立をここに宣言しますわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「実行委員の皆さん、素晴らしきパーティーになるよう、よろしくお願いしますわね！」
line = "「実行委員の皆さん、素晴らしきパーティーになるよう、よろしくお願いしますわね！」"

[[dialogue]]
speaker = "全員"
# 「おーっ！」
line = "「おーっ！」"
