[[dialogue]]
speaker = "unk"
# 俺の前で、新たな戦闘服『リバースフォーム』に変身してみせたサチとプリムラ。
line = "俺の前で、新たな戦闘服『リバースフォーム』に変身してみせたサチとプリムラ。"

[[dialogue]]
speaker = "サチ"
# 「あ、あの、お兄さん！　この姿は不可抗力ですからね！？　わ、私が望んでこうなったわけじゃなくて……！」
line = "「あ、あの、お兄さん！　この姿は不可抗力ですからね！？　わ、私が望んでこうなったわけじゃなくて……！」"

[[dialogue]]
speaker = "プリムラ"
# 「なぜサチが恥ずかしがるのか意味がわからんのじゃ。黒くて実にカッコよいではないか！」
line = "「なぜサチが恥ずかしがるのか意味がわからんのじゃ。黒くて実にカッコよいではないか！」"

[[dialogue]]
speaker = "unk"
# えっと……褒めていいのかわからないけど
line = "えっと……褒めていいのかわからないけど"

[[dialogue]]
speaker = "サチ"
# 「えっ？　……か、可愛い？　あ、ありがとうございます……<emoji=heart04>」
line = "「えっ？　……か、可愛い？　あ、ありがとうございます……<emoji=heart04>」"

[[dialogue]]
speaker = "プリムラ"
# 「はぁ！？　我の衣装もか！？　カッコいいならまだしも、可愛いなどと呼ばれて喜ぶとでも――」
line = "「はぁ！？　我の衣装もか！？　カッコいいならまだしも、可愛いなどと呼ばれて喜ぶとでも――」"

[[dialogue]]
speaker = "プリムラ"
# 「……フヘへへぇ<emoji=heart04>」
line = "「……フヘへへぇ<emoji=heart04>」"

[[dialogue]]
speaker = "サチ"
# 「喜んでるし……相変わらずチョロい……」
line = "「喜んでるし……相変わらずチョロい……」"

[[dialogue]]
speaker = "トレジアンナ"
# 「今回の衣装は、私がデザインしたわけではなく、通常の戦闘服と同様、力の発現によって自然形成されたものなんです」
line = "「今回の衣装は、私がデザインしたわけではなく、通常の戦闘服と同様、力の発現によって自然形成されたものなんです」"

[[dialogue]]
speaker = "トレジアンナ"
# 「反転の力には未知数の部分が多く……まずは安全に制御できる機能の構築を優先し、アニマさんにもご協力頂いて製作しました」
line = "「反転の力には未知数の部分が多く……まずは安全に制御できる機能の構築を優先し、アニマさんにもご協力頂いて製作しました」"

[[dialogue]]
speaker = "トレジアンナ"
# 「改めて説明しますと――お２人は現在、『反転のロストアイテム』の影響で、本来持っていた力の性質が逆転してしまっている状態です」
line = "「改めて説明しますと――お２人は現在、『反転のロストアイテム』の影響で、本来持っていた力の性質が逆転してしまっている状態です」"

[[dialogue]]
speaker = "プリムラ"
# 「そのせいで、これまで通りの力を使っての変身ができなくなってしまったのじゃ」
line = "「そのせいで、これまで通りの力を使っての変身ができなくなってしまったのじゃ」"

[[dialogue]]
speaker = "プリムラ"
# 「慣れ親しんだ力を奪われ、体に合わぬ力を与えられたような感覚じゃな」
line = "「慣れ親しんだ力を奪われ、体に合わぬ力を与えられたような感覚じゃな」"

[[dialogue]]
speaker = "トレジアンナ"
# 「その『反転した力』を制御し、戦闘可能にしたのが今回の『リバースフォーム』というわけです」
line = "「その『反転した力』を制御し、戦闘可能にしたのが今回の『リバースフォーム』というわけです」"

[[dialogue]]
speaker = "サチ"
# 「ですから私たち、この力をちゃんと使いこなせるよう、訓練をしておきたくて……」
line = "「ですから私たち、この力をちゃんと使いこなせるよう、訓練をしておきたくて……」"

[[dialogue]]
speaker = "トレジアンナ"
# 「力を元に戻すには、エントロフィーさんの持つロストアイテムを回収するしかないでしょう」
line = "「力を元に戻すには、エントロフィーさんの持つロストアイテムを回収するしかないでしょう」"

[[dialogue]]
speaker = "サチ"
# 「次にエントロフィーさんが現れた時、自分たちの力で戦えるようにしたいんです」
line = "「次にエントロフィーさんが現れた時、自分たちの力で戦えるようにしたいんです」"

[[dialogue]]
speaker = "プリムラ"
# 「奴め、こんな厄介な目に遭わせおって……この手で直接とっちめてやらねば気が済まんからな！」
line = "「奴め、こんな厄介な目に遭わせおって……この手で直接とっちめてやらねば気が済まんからな！」"

[[dialogue]]
speaker = "トレジアンナ"
# 「ただし現状、反転した力のデータは不十分です。制御を誤れば、暴走の危険性もあります」
line = "「ただし現状、反転した力のデータは不十分です。制御を誤れば、暴走の危険性もあります」"

[[dialogue]]
speaker = "サチ"
# 「その時、私たちを抑え込んでもらう為に、お兄さんにも協力をお願いしたいんです」
line = "「その時、私たちを抑え込んでもらう為に、お兄さんにも協力をお願いしたいんです」"

[[dialogue]]
speaker = "プリムラ"
# 「眷族よ、頼めるか？」
line = "「眷族よ、頼めるか？」"

[[dialogue]]
speaker = "unk"
# わかった。任せてくれ
line = "わかった。任せてくれ"

[[dialogue]]
speaker = "サチ"
# 「ありがとうございます、お兄さん♪」
line = "「ありがとうございます、お兄さん♪」"

[[dialogue]]
speaker = "シズハ"
# 「もちろん、私たちもチームとして協力するよ！　ね、ディーちゃん♪」
line = "「もちろん、私たちもチームとして協力するよ！　ね、ディーちゃん♪」"

[[dialogue]]
speaker = "ディーラック"
# 「はぁ？　ボクは別に味方になったつもりはないし、面倒だからイヤなんだけど？」
line = "「はぁ？　ボクは別に味方になったつもりはないし、面倒だからイヤなんだけど？」"

[[dialogue]]
speaker = "シズハ"
# 「そう言わずに！　この前だって、私のことを助けてくれたでしょ？　ねっ？」
line = "「そう言わずに！　この前だって、私のことを助けてくれたでしょ？　ねっ？」"

[[dialogue]]
speaker = "unk"
# こうして俺は、サチとプリムラのリバースフォームを制御する訓練に協力することになった。
line = "こうして俺は、サチとプリムラのリバースフォームを制御する訓練に協力することになった。"

[[dialogue]]
speaker = "unk"
# 『仮想結界システム』を使い、選択した訓練フィールドは『魔界』。
line = "『仮想結界システム』を使い、選択した訓練フィールドは『魔界』。"

[[dialogue]]
speaker = "プリムラ"
# 「フハハハ！　では、まず我からいくのじゃ♪」
line = "「フハハハ！　では、まず我からいくのじゃ♪」"

[[dialogue]]
speaker = "プリムラ"
# 「見るがよい！　これが我の、リバースフォームの力じゃ！」
line = "「見るがよい！　これが我の、リバースフォームの力じゃ！」"

[[dialogue]]
speaker = "unk"
# プリムラが杖を振るい、魔力を解放する。
line = "プリムラが杖を振るい、魔力を解放する。"

[[dialogue]]
speaker = "サチ"
# 「これは……！　体に力が湧いてきて、回復してる……？」
line = "「これは……！　体に力が湧いてきて、回復してる……？」"

[[dialogue]]
speaker = "プリムラ"
# 「そう！　元々の我の能力は、周囲のあらゆるエネルギーを吸収し、自らの力へと変換する『吸収変換』じゃった」
line = "「そう！　元々の我の能力は、周囲のあらゆるエネルギーを吸収し、自らの力へと変換する『吸収変換』じゃった」"

[[dialogue]]
speaker = "プリムラ"
# 「それが反転し、他者へ適したエネルギーを送り込む力――名づけて『放出供給』へと変化したのじゃ！」
line = "「それが反転し、他者へ適したエネルギーを送り込む力――名づけて『放出供給』へと変化したのじゃ！」"

[[dialogue]]
speaker = "トレジアンナ"
# 「つまり、仲間への回復や、エネルギー供給が可能になったということですね♪」
line = "「つまり、仲間への回復や、エネルギー供給が可能になったということですね♪」"

[[dialogue]]
speaker = "プリムラ"
# 「うむ！　その代わり、今までのフォームに比べて、火力は落ちてしまっているのは不本意じゃがな」
line = "「うむ！　その代わり、今までのフォームに比べて、火力は落ちてしまっているのは不本意じゃがな」"

[[dialogue]]
speaker = "シズハ"
# 「いやいや、すごいよ♪　私たちの中で回復役ができるのは大きいし、戦い方の幅もすっごく広がるよ！」
line = "「いやいや、すごいよ♪　私たちの中で回復役ができるのは大きいし、戦い方の幅もすっごく広がるよ！」"

[[dialogue]]
speaker = "プリムラ"
# 「ふん……そんなおだてても、我は調子には乗らぬぞ！」
line = "「ふん……そんなおだてても、我は調子には乗らぬぞ！」"

[[dialogue]]
speaker = "プリムラ"
# 「――フハハハハ！！　どうじゃ！　我の供給するエネルギーは絶大であろう？」
line = "「――フハハハハ！！　どうじゃ！　我の供給するエネルギーは絶大であろう？」"

[[dialogue]]
speaker = "unk"
# 仮想モンスターを相手に訓練は続いていた。
line = "仮想モンスターを相手に訓練は続いていた。"

[[dialogue]]
speaker = "unk"
# た、確かにすごいけど……
line = "た、確かにすごいけど……"

[[dialogue]]
speaker = "シズハ"
# 「う、うん。ちょっと過剰すぎるような……」
line = "「う、うん。ちょっと過剰すぎるような……」"

[[dialogue]]
speaker = "ディーラック"
# 「あ～あ、完全に調子に乗ってるのサ」
line = "「あ～あ、完全に調子に乗ってるのサ」"

[[dialogue]]
speaker = "unk"
# 俺たちの技の出力は跳ね上がり、仮想モンスターは瞬殺状態。
line = "俺たちの技の出力は跳ね上がり、仮想モンスターは瞬殺状態。"

[[dialogue]]
speaker = "unk"
# しかし、プリムラから供給されるエネルギー量は、明らかに過剰だった。
line = "しかし、プリムラから供給されるエネルギー量は、明らかに過剰だった。"

[[dialogue]]
speaker = "プリムラ"
# 「ほれほれ～！　我が眷族たちよ！　もっと我の力で大暴れするのじゃ～！　フハハハハ♪」
line = "「ほれほれ～！　我が眷族たちよ！　もっと我の力で大暴れするのじゃ～！　フハハハハ♪」"

[[dialogue]]
speaker = "サチ"
# 「プリムラ、飛ばしすぎだよ！　リバースフォームは、まだ何が起こるかわからないんだから慎重に――」
line = "「プリムラ、飛ばしすぎだよ！　リバースフォームは、まだ何が起こるかわからないんだから慎重に――」"

[[dialogue]]
speaker = "トレジアンナ"
# 「って、プリムラさん！？　なんか体が発光していますよ！？」
line = "「って、プリムラさん！？　なんか体が発光していますよ！？」"

[[dialogue]]
speaker = "プリムラ"
# 「な、なに！？　ぬおっ……出力を上げ過ぎて、抑えが――」
line = "「な、なに！？　ぬおっ……出力を上げ過ぎて、抑えが――」"

[[dialogue]]
speaker = "プリムラ"
# 「ぬわぁ～～～っ！？！？」
line = "「ぬわぁ～～～っ！？！？」"

[[dialogue]]
speaker = "サチ"
# 「プリムラ！」
line = "「プリムラ！」"

[[dialogue]]
speaker = "プリムラ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "サチ"
# 「ちょっと！　大丈夫……！？」
line = "「ちょっと！　大丈夫……！？」"

[[dialogue]]
speaker = "プリムラ"
# 「ばぶぅ……？」
line = "「ばぶぅ……？」"

[[dialogue]]
speaker = "シズハ"
# 「赤ちゃんになっちゃった！？」
line = "「赤ちゃんになっちゃった！？」"

[[dialogue]]
speaker = "サチ"
# 「えぇ～～～っ！？」
line = "「えぇ～～～っ！？」"

[[dialogue]]
speaker = "プリムラ"
# 「あぁ～い<emoji=heart04>」
line = "「あぁ～い<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 唖然とする俺たちの前で、プリムラは無邪気な笑顔を浮かべるのだった。
line = "唖然とする俺たちの前で、プリムラは無邪気な笑顔を浮かべるのだった。"
