[[dialogue]]
speaker = "unk"
# 俺たちが暴走したサチやプリムラを相手する一方で、変身したエントロフィーと戦うシズハ。
line = "俺たちが暴走したサチやプリムラを相手する一方で、変身したエントロフィーと戦うシズハ。"

[[dialogue]]
speaker = "unk"
# しかし――
line = "しかし――"

[[dialogue]]
speaker = "エントロフィー"
# 「はぁ～、残念っすね～」
line = "「はぁ～、残念っすね～」"

[[dialogue]]
speaker = "シズハ"
# 「くっ……！」
line = "「くっ……！」"

[[dialogue]]
speaker = "unk"
# シズハはディーラックとの連携が噛み合わず、一瞬の隙を突かれ、エントロフィーの手に捕らえられてしまった。
line = "シズハはディーラックとの連携が噛み合わず、一瞬の隙を突かれ、エントロフィーの手に捕らえられてしまった。"

[[dialogue]]
speaker = "シズハ"
# 「なんてスピードなの……！」
line = "「なんてスピードなの……！」"

[[dialogue]]
speaker = "エントロフィー"
# 「きゃははっ☆　めっちゃ速いでしょ～？　ウチ、そこが自慢ポイントなんすよ～♪」
line = "「きゃははっ☆　めっちゃ速いでしょ～？　ウチ、そこが自慢ポイントなんすよ～♪」"

[[dialogue]]
speaker = "エントロフィー"
# 「まあ、それと『反転のロストアイテム』のワンタッチアウトな力が組み合わさってるのが、凶悪ではあるんすけど♪」
line = "「まあ、それと『反転のロストアイテム』のワンタッチアウトな力が組み合わさってるのが、凶悪ではあるんすけど♪」"

[[dialogue]]
speaker = "ディーラック"
# 「こいつ……！」
line = "「こいつ……！」"

[[dialogue]]
speaker = "ディーラック"
# （形態変化したら、ボクの目でも追い切れなかった……！　速さだけなら、ボクよりも間違いなく上だ……！）
line = "（形態変化したら、ボクの目でも追い切れなかった……！　速さだけなら、ボクよりも間違いなく上だ……！）"

[[dialogue]]
speaker = "シズハ"
# 「くっ……うああぁっ……！？」
line = "「くっ……うああぁっ……！？」"

[[dialogue]]
speaker = "unk"
# ふと、エントロフィーに掴まれて、苦しみ出すシズハ。
line = "ふと、エントロフィーに掴まれて、苦しみ出すシズハ。"

[[dialogue]]
speaker = "ディーラック"
# 「！　シズハちゃん……！？」
line = "「！　シズハちゃん……！？」"

[[dialogue]]
speaker = "エントロフィー"
# 「あ～、なるほど？　これはもしかして、あれっすかね～？」
line = "「あ～、なるほど？　これはもしかして、あれっすかね～？」"

[[dialogue]]
speaker = "エントロフィー"
# 「シズハのアネさんって確か、聖杯の力で生きているって話っすよね？　それが反転させられるってことは、聖杯が機能不全になるってことで～」
line = "「シズハのアネさんって確か、聖杯の力で生きているって話っすよね？　それが反転させられるってことは、聖杯が機能不全になるってことで～」"

[[dialogue]]
speaker = "エントロフィー"
# 「下手したら死んじゃうかも、って感じっすかね？　ん～、この場合はどうしよっかな～」
line = "「下手したら死んじゃうかも、って感じっすかね？　ん～、この場合はどうしよっかな～」"

[[dialogue]]
speaker = "シズハ"
# 「くぅっ……うあああぁっ！？」
line = "「くぅっ……うあああぁっ！？」"

[[dialogue]]
speaker = "ディーラック"
# 「やめろっ！！」
line = "「やめろっ！！」"

[[dialogue]]
speaker = "unk"
# エントロフィーに向けて、飛び込むディーラック。
line = "エントロフィーに向けて、飛び込むディーラック。"

[[dialogue]]
speaker = "エントロフィー"
# 「残念、見えてるっすよ♪」
line = "「残念、見えてるっすよ♪」"

[[dialogue]]
speaker = "ディーラック"
# 「ぐあっ！？」
line = "「ぐあっ！？」"

[[dialogue]]
speaker = "unk"
# 瞬時に回避して、手の甲でディーラックを弾き飛ばすエントロフィー。
line = "瞬時に回避して、手の甲でディーラックを弾き飛ばすエントロフィー。"

[[dialogue]]
speaker = "エントロフィー"
# 「ディーラックのアネさん、必死っすね～。そういえば、シズハのアネさんの聖杯を直そうとして、魔法少女に負けたんでしたっけ？」
line = "「ディーラックのアネさん、必死っすね～。そういえば、シズハのアネさんの聖杯を直そうとして、魔法少女に負けたんでしたっけ？」"

[[dialogue]]
speaker = "ディーラック"
# 「くっ……！」
line = "「くっ……！」"

[[dialogue]]
speaker = "ディーラック"
# （ボクは世界の裏側、どこまでも広がる真っ暗な空間――『虚数の海』から、ひとりきりで生まれた）
line = "（ボクは世界の裏側、どこまでも広がる真っ暗な空間――『虚数の海』から、ひとりきりで生まれた）"

[[dialogue]]
speaker = "ディーラック"
# （善悪なんて、ボクは知らない）
line = "（善悪なんて、ボクは知らない）"

[[dialogue]]
speaker = "ディーラック"
# （ボクはエネルギー生命体として、本能のままにマイナスエネルギーを欲して喰らう。ただ……それだけだった）
line = "（ボクはエネルギー生命体として、本能のままにマイナスエネルギーを欲して喰らう。ただ……それだけだった）"

[[dialogue]]
speaker = "unk"
# ディーラックは、生まれてからしばらくして――病院で闘病に励むシズハを見つけた。
line = "ディーラックは、生まれてからしばらくして――病院で闘病に励むシズハを見つけた。"

[[dialogue]]
speaker = "unk"
# マイナスエネルギーを効率よく喰らう為に、ロストアイテムの『聖杯』を彼女に埋め込んだ。
line = "マイナスエネルギーを効率よく喰らう為に、ロストアイテムの『聖杯』を彼女に埋め込んだ。"

[[dialogue]]
speaker = "unk"
# そして、ディーラックが学園に『解放のロストアイテム』を送り込むよりも以前。
line = "そして、ディーラックが学園に『解放のロストアイテム』を送り込むよりも以前。"

[[dialogue]]
speaker = "シズハ"
# 「――今日からここに通い始めるのね♪」
line = "「――今日からここに通い始めるのね♪」"

[[dialogue]]
speaker = "ディーラック"
# 「ああ。シズハちゃんが行きたいって言ってた学園だよ」
line = "「ああ。シズハちゃんが行きたいって言ってた学園だよ」"

[[dialogue]]
speaker = "unk"
# 聖杯の力で元気に歩けるようになり、退院したシズハは、流星学園附属校へと通い始めていた。
line = "聖杯の力で元気に歩けるようになり、退院したシズハは、流星学園附属校へと通い始めていた。"

[[dialogue]]
speaker = "ディーラック"
# （……ボクはマイナスエネルギーを生み出す『家畜』として利用する為に、シズハちゃんに聖杯を埋め込んだ）
line = "（……ボクはマイナスエネルギーを生み出す『家畜』として利用する為に、シズハちゃんに聖杯を埋め込んだ）"

[[dialogue]]
speaker = "ディーラック"
# （でも……心を持つヒトカスってのは、実際に接するようになると、想像よりもずっと面倒くさい下等生物だった）
line = "（でも……心を持つヒトカスってのは、実際に接するようになると、想像よりもずっと面倒くさい下等生物だった）"

[[dialogue]]
speaker = "シズハ"
# 「ディーちゃん、一緒にお風呂入ろ～♪」
line = "「ディーちゃん、一緒にお風呂入ろ～♪」"

[[dialogue]]
speaker = "ディーラック"
# 「はぁ？　イヤなんだけど～……」
line = "「はぁ？　イヤなんだけど～……」"

[[dialogue]]
speaker = "unk"
# シズハは、なにかとディーラックと一緒に行動をしたがった。
line = "シズハは、なにかとディーラックと一緒に行動をしたがった。"

[[dialogue]]
speaker = "シズハ"
# 「ディーちゃん、一緒に寝よ～」
line = "「ディーちゃん、一緒に寝よ～」"

[[dialogue]]
speaker = "ディーラック"
# 「いや、ボクはひとりで寝たいんだけど……？」
line = "「いや、ボクはひとりで寝たいんだけど……？」"

[[dialogue]]
speaker = "unk"
# シズハには抱き着き癖があり、ぬいぐるみのように抱きしめられながら寝ることになるディーラック。
line = "シズハには抱き着き癖があり、ぬいぐるみのように抱きしめられながら寝ることになるディーラック。"

[[dialogue]]
speaker = "シズハ"
# 「すぅ……すぅ……」
line = "「すぅ……すぅ……」"

[[dialogue]]
speaker = "ディーラック"
# （……なんでボクは、下等生物なんかとくっ付いて寝てるんだ？）
line = "（……なんでボクは、下等生物なんかとくっ付いて寝てるんだ？）"

[[dialogue]]
speaker = "ディーラック"
# （ヒトカスはヒトカス、ボクが生きるための食糧を生み出す家畜でしかないのに……）
line = "（ヒトカスはヒトカス、ボクが生きるための食糧を生み出す家畜でしかないのに……）"

[[dialogue]]
speaker = "ディーラック"
# （ダルい、キモい、めんどい……）
line = "（ダルい、キモい、めんどい……）"

[[dialogue]]
speaker = "ディーラック"
# （けど、仕方ない……）
line = "（けど、仕方ない……）"

[[dialogue]]
speaker = "ディーラック"
# （ヒトカス共が美味しい物を喰らう為に、動物やら野菜やらを育てているのと一緒サ……）
line = "（ヒトカス共が美味しい物を喰らう為に、動物やら野菜やらを育てているのと一緒サ……）"

[[dialogue]]
speaker = "unk"
# そんなある日。
line = "そんなある日。"

[[dialogue]]
speaker = "シズハ"
# 「あ……れ……？」
line = "「あ……れ……？」"

[[dialogue]]
speaker = "サチ"
# 「シズハちゃん……どうしたの！？」
line = "「シズハちゃん……どうしたの！？」"

[[dialogue]]
speaker = "unk"
# 運動場で訓練していたシズハが突然、床に倒れ込んでしまった。
line = "運動場で訓練していたシズハが突然、床に倒れ込んでしまった。"

[[dialogue]]
speaker = "シズハ"
# 「なんか急に、クラっとして……」
line = "「なんか急に、クラっとして……」"

[[dialogue]]
speaker = "unk"
# 透明化して、その様子を窺っていたディーラックは、思わず息をのんだ。
line = "透明化して、その様子を窺っていたディーラックは、思わず息をのんだ。"

[[dialogue]]
speaker = "ディーラック"
# （おい……ウソだろ……！？）
line = "（おい……ウソだろ……！？）"

[[dialogue]]
speaker = "unk"
# 術式でシズハの体内を精査する。
line = "術式でシズハの体内を精査する。"

[[dialogue]]
speaker = "unk"
# すると――聖杯の表面に、無数の微細なヒビが走っているのが見えた。
line = "すると――聖杯の表面に、無数の微細なヒビが走っているのが見えた。"

[[dialogue]]
speaker = "ディーラック"
# （ロストアイテムの……経年劣化だと……？　そんな話、知らないぞ……！）
line = "（ロストアイテムの……経年劣化だと……？　そんな話、知らないぞ……！）"

[[dialogue]]
speaker = "ディーラック"
# （……いや、仕方ないのか……。ロストアイテムにも寿命があるってことなんだろう……）
line = "（……いや、仕方ないのか……。ロストアイテムにも寿命があるってことなんだろう……）"

[[dialogue]]
speaker = "unk"
# 冷静に考えれば、結論は単純だった。
line = "冷静に考えれば、結論は単純だった。"

[[dialogue]]
speaker = "ディーラック"
# （なら、シズハちゃんは――ここまで）
line = "（なら、シズハちゃんは――ここまで）"

[[dialogue]]
speaker = "ディーラック"
# （聖杯が壊れるまで利用して……限界が来たら切り捨てる。そして次に利用できる他の奴を探す。それがいちばん、合理的だ）
line = "（聖杯が壊れるまで利用して……限界が来たら切り捨てる。そして次に利用できる他の奴を探す。それがいちばん、合理的だ）"

[[dialogue]]
speaker = "unk"
# ――そのはずだった。
line = "――そのはずだった。"

[[dialogue]]
speaker = "unk"
# だが……そこまで考えた瞬間、なぜか思考が止まる。
line = "だが……そこまで考えた瞬間、なぜか思考が止まる。"

[[dialogue]]
speaker = "ディーラック"
# （…………）
line = "（…………）"

[[dialogue]]
speaker = "unk"
# 理由は分からない。
line = "理由は分からない。"

[[dialogue]]
speaker = "unk"
# ただ、次の一歩を踏み出せない。
line = "ただ、次の一歩を踏み出せない。"

[[dialogue]]
speaker = "unk"
# しばらく沈黙した後、ディーラックは小さく呟く。
line = "しばらく沈黙した後、ディーラックは小さく呟く。"

[[dialogue]]
speaker = "ディーラック"
# 「仕方ない……」
line = "「仕方ない……」"

[[dialogue]]
speaker = "ディーラック"
# （……『記憶のロストアイテム』の一件で、トレジアンナからはロストアイテムに関する知識を手に入れている）
line = "（……『記憶のロストアイテム』の一件で、トレジアンナからはロストアイテムに関する知識を手に入れている）"

[[dialogue]]
speaker = "unk"
# シズハに聖杯を与える前、ディーラックは『記憶のロストアイテム』を使い、サチやプリムラを巻き込む騒動を起こしていた。
line = "シズハに聖杯を与える前、ディーラックは『記憶のロストアイテム』を使い、サチやプリムラを巻き込む騒動を起こしていた。"

[[dialogue]]
speaker = "unk"
# サチの記憶喪失に意識を逸らしつつ、真の狙いは、トレジアンナからロストアイテム製作に関する記憶を一時的に奪い、その知識を読み取る為であった。
line = "サチの記憶喪失に意識を逸らしつつ、真の狙いは、トレジアンナからロストアイテム製作に関する記憶を一時的に奪い、その知識を読み取る為であった。"

[[dialogue]]
speaker = "unk"
# 元々は、ロストアイテムを詳しく知ることで、マイナスエネルギーを効率良く得る為の手段に過ぎなかったが……。
line = "元々は、ロストアイテムを詳しく知ることで、マイナスエネルギーを効率良く得る為の手段に過ぎなかったが……。"

[[dialogue]]
speaker = "ディーラック"
# （……聖杯を修復するには、膨大なマイナスエネルギーが必要だ）
line = "（……聖杯を修復するには、膨大なマイナスエネルギーが必要だ）"

[[dialogue]]
speaker = "ディーラック"
# （それが最も効率良く得られるのは――）
line = "（それが最も効率良く得られるのは――）"

[[dialogue]]
speaker = "unk"
# その後、ディーラックは『解放のロストアイテム』の事件を引き起こす。
line = "その後、ディーラックは『解放のロストアイテム』の事件を引き起こす。"

[[dialogue]]
speaker = "unk"
# シズハの聖杯を使った『認識改変』によって生じる、大量のマイナスエネルギーを得る為に。
line = "シズハの聖杯を使った『認識改変』によって生じる、大量のマイナスエネルギーを得る為に。"

[[dialogue]]
speaker = "unk"
# 全ては――シズハの聖杯を修復する為……。
line = "全ては――シズハの聖杯を修復する為……。"

[[dialogue]]
speaker = "ディーラック"
# 「……触んな」
line = "「……触んな」"

[[dialogue]]
speaker = "エントロフィー"
# 「は？　なんて？」
line = "「は？　なんて？」"

[[dialogue]]
speaker = "ディーラック"
# 「それ以上、ヒトのもんに触んなって言ったんだっ！！　さもないと――」
line = "「それ以上、ヒトのもんに触んなって言ったんだっ！！　さもないと――」"

[[dialogue]]
speaker = "ディーラック"
# 「お前をぶっ殺してやるッ！！！」
line = "「お前をぶっ殺してやるッ！！！」"

[[dialogue]]
speaker = "unk"
# ディーラックの体から爆発的に噴き出したマイナスエネルギーに、エントロフィーが一歩後ずさる。
line = "ディーラックの体から爆発的に噴き出したマイナスエネルギーに、エントロフィーが一歩後ずさる。"

[[dialogue]]
speaker = "エントロフィー"
# 「っ……！　これは……すごい気迫っすね……！」
line = "「っ……！　これは……すごい気迫っすね……！」"

[[dialogue]]
speaker = "シズハ"
# 「……ディーちゃんの記憶、私にも見えたよ」
line = "「……ディーちゃんの記憶、私にも見えたよ」"

[[dialogue]]
speaker = "ディーラック"
# 「！？　シズハちゃん……？」
line = "「！？　シズハちゃん……？」"

[[dialogue]]
speaker = "unk"
# ディーラックと精神がリンクしているせいか、シズハにはディーラックの記憶や、その時に抱いた感情が流れ込んできていた。
line = "ディーラックと精神がリンクしているせいか、シズハにはディーラックの記憶や、その時に抱いた感情が流れ込んできていた。"

[[dialogue]]
speaker = "シズハ"
# 「私の為に……ありがとう」
line = "「私の為に……ありがとう」"

[[dialogue]]
speaker = "unk"
# その瞬間、シズハの体から眩い光が溢れ出す。
line = "その瞬間、シズハの体から眩い光が溢れ出す。"

[[dialogue]]
speaker = "エントロフィー"
# 「この光は……！？　くっ……！？」
line = "「この光は……！？　くっ……！？」"

[[dialogue]]
speaker = "unk"
# シズハはその力で、エントロフィーの掴んでいた手をバチッと弾き飛ばした。
line = "シズハはその力で、エントロフィーの掴んでいた手をバチッと弾き飛ばした。"

[[dialogue]]
speaker = "エントロフィー"
# 「反転の力が無効化された……！？　この感覚はまさか――」
line = "「反転の力が無効化された……！？　この感覚はまさか――」"

[[dialogue]]
speaker = "エントロフィー"
# 「マイナスエネルギーの力っすか！？」
line = "「マイナスエネルギーの力っすか！？」"

[[dialogue]]
speaker = "シズハ"
# 「私……ディーちゃんの気持ちをわかったような気になっていたけど……そんな簡単なことじゃなかったんだよね？」
line = "「私……ディーちゃんの気持ちをわかったような気になっていたけど……そんな簡単なことじゃなかったんだよね？」"

[[dialogue]]
speaker = "ディーラック"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "シズハ"
# 「ディーちゃんの中にあったのは、簡単には言葉で言い表せない……ディーちゃん自身でもまだよくわかっていない……複雑な感情だったんだ」
line = "「ディーちゃんの中にあったのは、簡単には言葉で言い表せない……ディーちゃん自身でもまだよくわかっていない……複雑な感情だったんだ」"

[[dialogue]]
speaker = "ディーラック"
# 「そうサ……ボクにはよくわからない……」
line = "「そうサ……ボクにはよくわからない……」"

[[dialogue]]
speaker = "ディーラック"
# 「自分の感情もよくわからないのに、ましてや『絆』とか、わかるわけないだろう？」
line = "「自分の感情もよくわからないのに、ましてや『絆』とか、わかるわけないだろう？」"

[[dialogue]]
speaker = "シズハ"
# 「でも、私の為に怒ってくれた」
line = "「でも、私の為に怒ってくれた」"

[[dialogue]]
speaker = "ディーラック"
# 「それもわからない……ただ、ムカついただけサ」
line = "「それもわからない……ただ、ムカついただけサ」"

[[dialogue]]
speaker = "シズハ"
# 「今はそれで十分だよ」
line = "「今はそれで十分だよ」"

[[dialogue]]
speaker = "unk"
# シズハ、大丈夫か！？
line = "シズハ、大丈夫か！？"

[[dialogue]]
speaker = "unk"
# 俺は乱戦の中で隙を見て、駆けつける。
line = "俺は乱戦の中で隙を見て、駆けつける。"

[[dialogue]]
speaker = "シズハ"
# 「会長、ナイスタイミング！」
line = "「会長、ナイスタイミング！」"

[[dialogue]]
speaker = "シズハ"
# 「あのね、私……今なら行ける気がするの。だから――」
line = "「あのね、私……今なら行ける気がするの。だから――」"

[[dialogue]]
speaker = "unk"
# 俺はそこで気づく。
line = "俺はそこで気づく。"

[[dialogue]]
speaker = "unk"
# シズハの心に灯った――眩い星の輝きに。
line = "シズハの心に灯った――眩い星の輝きに。"

[[dialogue]]
speaker = "シズハ"
# 「会長、お願い！　私に力を貸して！」
line = "「会長、お願い！　私に力を貸して！」"

[[dialogue]]
speaker = "unk"
# 俺は頷き、魔王の力を発動する。
line = "俺は頷き、魔王の力を発動する。"

[[dialogue]]
speaker = "unk"
# アルケインノヴァエクストリーム！！！
line = "アルケインノヴァエクストリーム！！！"

[[dialogue]]
speaker = "シズハ"
# 「――ディーちゃんとの関係は、マイナスエネルギーのように難しくて、簡単には理解できないのかもしれない」
line = "「――ディーちゃんとの関係は、マイナスエネルギーのように難しくて、簡単には理解できないのかもしれない」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「それでも……私はディーちゃんのことを、『友達』って呼びたい！」
line = "「それでも……私はディーちゃんのことを、『友達』って呼びたい！」"

[[dialogue]]
speaker = "ディーラック"
# 「……！　これがシズハちゃんの覚醒した姿……！」
line = "「……！　これがシズハちゃんの覚醒した姿……！」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「そう、私とディーちゃんの『絆』の力だよ」
line = "「そう、私とディーちゃんの『絆』の力だよ」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「私は――そう信じてる」
line = "「私は――そう信じてる」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「だから、ディーちゃん。私のお願い、聞いてくれる？」
line = "「だから、ディーちゃん。私のお願い、聞いてくれる？」"

[[dialogue]]
speaker = "ディーラック"
# 「……はぁ」
line = "「……はぁ」"

[[dialogue]]
speaker = "ディーラック"
# 「仕方ないなぁ……どうせ、シズハちゃんは１度言い出したら、止まらないんでしょ？」
line = "「仕方ないなぁ……どうせ、シズハちゃんは１度言い出したら、止まらないんでしょ？」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「うん。私は決めたから、その願いが叶うまで、いけいけゴーゴーだから！」
line = "「うん。私は決めたから、その願いが叶うまで、いけいけゴーゴーだから！」"

[[dialogue]]
speaker = "ディーラック"
# 「だったら――面倒だけど聞いてあげるよ」
line = "「だったら――面倒だけど聞いてあげるよ」"

[[dialogue]]
speaker = "エントロフィー"
# 「くっ……ふふっ……♪」
line = "「くっ……ふふっ……♪」"

[[dialogue]]
speaker = "エントロフィー"
# 「きゃははははっ♪　これは……マジですごいっす！　めちゃくちゃ面白いじゃないっすか、シズハのアネさん！」
line = "「きゃははははっ♪　これは……マジですごいっす！　めちゃくちゃ面白いじゃないっすか、シズハのアネさん！」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「行こう、ディーちゃん」
line = "「行こう、ディーちゃん」"

[[dialogue]]
speaker = "シズハ（覚醒）"
# 「今こそ、心願成就――願いを叶える時だよ！」
line = "「今こそ、心願成就――願いを叶える時だよ！」"

[[dialogue]]
speaker = "ディーラック"
# 「仕方ない、その願い――付き合ってあげるサ！」
line = "「仕方ない、その願い――付き合ってあげるサ！」"

[[dialogue]]
speaker = "unk"
# 覚醒したシズハとディーラックは並び立ち、共にエントロフィーへの反撃を開始するのだった。
line = "覚醒したシズハとディーラックは並び立ち、共にエントロフィーへの反撃を開始するのだった。"
