[[dialogue]]
speaker = "ヴィーナス"
# 「サプライズ歓迎会をするわよー！」
line = "「サプライズ歓迎会をするわよー！」"

[[dialogue]]
speaker = "unk"
# ヴィーナスの声かけにより、今回の隠し芸大会に参加した面々が集合した。
line = "ヴィーナスの声かけにより、今回の隠し芸大会に参加した面々が集合した。"

[[dialogue]]
speaker = "ソフィア"
# 「歓迎会……誰のですか？」
line = "「歓迎会……誰のですか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「決まってるじゃない！　ヒメちゃんよ！」
line = "「決まってるじゃない！　ヒメちゃんよ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ヒメちゃん……？　ヒメちゃん……って、もしかして、オオヒメ様のことですか！？」
line = "「ヒメちゃん……？　ヒメちゃん……って、もしかして、オオヒメ様のことですか！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうよ。本人が『アルモたん』みたいにきゃわわな愛称で呼んでほしいって言ってたわ。だから、ヒメちゃん」
line = "「そうよ。本人が『アルモたん』みたいにきゃわわな愛称で呼んでほしいって言ってたわ。だから、ヒメちゃん」"

[[dialogue]]
speaker = "オオヒメ"
# 「オオヒメが呼びにくければ、ヒメとでも呼んでくれ。私にはいささか可愛すぎる響きだが……」
line = "「オオヒメが呼びにくければ、ヒメとでも呼んでくれ。私にはいささか可愛すぎる響きだが……」"

[[dialogue]]
speaker = "unk"
# ヒメの実際の発言がこれなので、ヴィーナスの認識は大分ズレていた。
line = "ヒメの実際の発言がこれなので、ヴィーナスの認識は大分ズレていた。"

[[dialogue]]
speaker = "ウズメイア"
# 「ちょっち恐れ多いけど、めちゃかわ～。ギャップ萌えってヤツ～？」
line = "「ちょっち恐れ多いけど、めちゃかわ～。ギャップ萌えってヤツ～？」"

[[dialogue]]
speaker = "舞亜"
# 「でも、歓迎会ね……ヒメさんの好きな芸は散々披露しちゃったじゃない？　また隠し芸する？」
line = "「でも、歓迎会ね……ヒメさんの好きな芸は散々披露しちゃったじゃない？　また隠し芸する？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうなのよねー。ヒメちゃんは喜んでくれるでしょうけど、二番煎じじゃ物足りないし、他にも大きな催しが欲しいところだわ！」
line = "「そうなのよねー。ヒメちゃんは喜んでくれるでしょうけど、二番煎じじゃ物足りないし、他にも大きな催しが欲しいところだわ！」"

[[dialogue]]
speaker = "unk"
# （ヴィーナスがド派手にやりたいだけでは）
line = "（ヴィーナスがド派手にやりたいだけでは）"

[[dialogue]]
speaker = "蘭美"
# 「歓談中に申し訳ないけれど、お嬢様、少しばかり厄介なことになってしまったわ」
line = "「歓談中に申し訳ないけれど、お嬢様、少しばかり厄介なことになってしまったわ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あら、どうかしたの？」
line = "「あら、どうかしたの？」"

[[dialogue]]
speaker = "蘭美"
# 「年末、色々と慌ただしかった影響で、鏡餅用のお餅がつけていないのよ。由々しき事態だわ！」
line = "「年末、色々と慌ただしかった影響で、鏡餅用のお餅がつけていないのよ。由々しき事態だわ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それは確かに困るわね！」
line = "「それは確かに困るわね！」"

[[dialogue]]
speaker = "トリシャ"
# 「お餅がないというのは……人間界では大騒ぎするほどの……事件なのでしょうか……？」
line = "「お餅がないというのは……人間界では大騒ぎするほどの……事件なのでしょうか……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「お正月に鏡餅がないなんて一大事に決まってるわ！　九浄家一丸となって、お餅つきの用意をしないと──」
line = "「お正月に鏡餅がないなんて一大事に決まってるわ！　九浄家一丸となって、お餅つきの用意をしないと──」"

[[dialogue]]
speaker = "unk"
# それなら餅つきを歓迎会にしたら？
line = "それなら餅つきを歓迎会にしたら？"

[[dialogue]]
speaker = "ヴィーナス"
# 「それよ！　大名案だわ、クロト！　みんなでお餅つきパーティーをやりましょ！」
line = "「それよ！　大名案だわ、クロト！　みんなでお餅つきパーティーをやりましょ！」"

[[dialogue]]
speaker = "unk"
# そして、翌日。早速、九浄家総出でのお餅つきパーティーが開催された。
line = "そして、翌日。早速、九浄家総出でのお餅つきパーティーが開催された。"

[[dialogue]]
speaker = "オオヒメ"
# 「年越しに続いてお招きいただき、感謝の極みだ。こうして集まるのは、賑やかでいいことだ」
line = "「年越しに続いてお招きいただき、感謝の極みだ。こうして集まるのは、賑やかでいいことだ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「みんなはお餅つきってやったことある？」
line = "「みんなはお餅つきってやったことある？」"

[[dialogue]]
speaker = "フィオナ"
# 「杵と臼を使って、ぺったんぺったんするアレですよね。幼い頃に一度やった気がしないでもないような……」
line = "「杵と臼を使って、ぺったんぺったんするアレですよね。幼い頃に一度やった気がしないでもないような……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そう、お月様で兎がやってるアレよ。九浄家では毎年の風物詩なの。つきたてのお餅は、出来合いとは一味違って最高よ！」
line = "「そう、お月様で兎がやってるアレよ。九浄家では毎年の風物詩なの。つきたてのお餅は、出来合いとは一味違って最高よ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「というわけで、フィオナ、見ざる言わざる働かざる者、食うべからず！　あなたもお餅つきに参加するのよ！」
line = "「というわけで、フィオナ、見ざる言わざる働かざる者、食うべからず！　あなたもお餅つきに参加するのよ！」"

[[dialogue]]
speaker = "フィオナ"
# 「わかりました。でもつく方と捏ねる方、どっちにしましょう……？」
line = "「わかりました。でもつく方と捏ねる方、どっちにしましょう……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私が捏ねるから、フィオナがつく方やって。ぺったん、ぺったん、ってやれば簡単にできるから。ぺたんぺたんじゃないわよ」
line = "「私が捏ねるから、フィオナがつく方やって。ぺったん、ぺったん、ってやれば簡単にできるから。ぺたんぺたんじゃないわよ」"

[[dialogue]]
speaker = "フィオナ"
# 「ぺったんとぺたんには違いがあるのでしょうか……？」
line = "「ぺったんとぺたんには違いがあるのでしょうか……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「違うわよ～！　ぺったんはぺったんで、ぺたんはぺたんなんだから！」
line = "「違うわよ～！　ぺったんはぺったんで、ぺたんはぺたんなんだから！」"

[[dialogue]]
speaker = "フィオナ"
# 「だからどう違うんですか……？」
line = "「だからどう違うんですか……？」"

[[dialogue]]
speaker = "unk"
# フィオナが困惑しているその一方で──
line = "フィオナが困惑しているその一方で──"

[[dialogue]]
speaker = "ウズメイア"
# 「トリシャさん、行っくよ～。そーれ、ぺったんこ～、ぺったんこ～♪」
line = "「トリシャさん、行っくよ～。そーれ、ぺったんこ～、ぺったんこ～♪」"

[[dialogue]]
speaker = "トリシャ"
# 「よい、しょっ……あちちち……炊き立てのもち米……アツアツですね……」
line = "「よい、しょっ……あちちち……炊き立てのもち米……アツアツですね……」"

[[dialogue]]
speaker = "ウズメイア"
# 「だいじょぶ？　やっぱ、あたしが捏ねよっか」
line = "「だいじょぶ？　やっぱ、あたしが捏ねよっか」"

[[dialogue]]
speaker = "トリシャ"
# 「いえ、力仕事は向いていませんので……それに捏ねる方のコツが掴めてきましたし……このまま……」
line = "「いえ、力仕事は向いていませんので……それに捏ねる方のコツが掴めてきましたし……このまま……」"

[[dialogue]]
speaker = "ウズメイア"
# 「そ？　んじゃ、ぺったんこ～、ぺったんこ～」
line = "「そ？　んじゃ、ぺったんこ～、ぺったんこ～」"

[[dialogue]]
speaker = "トリシャ"
# 「よいしょっ……よいしょっ……あちち……でも、友達との共同作業……すごく楽しい……にへへ……♪」
line = "「よいしょっ……よいしょっ……あちち……でも、友達との共同作業……すごく楽しい……にへへ……♪」"

[[dialogue]]
speaker = "蘭美"
# 「ふっ……遅れなんて、私にかかれば有って無きが如しよ！　すぐに取り返して見せるわ！」
line = "「ふっ……遅れなんて、私にかかれば有って無きが如しよ！　すぐに取り返して見せるわ！」"

[[dialogue]]
speaker = "蘭美"
# 「はぁあぁぁぁっ、ぺったんぺったんぺったんたーん！」
line = "「はぁあぁぁぁっ、ぺったんぺったんぺったんたーん！」"

[[dialogue]]
speaker = "ヘレナ"
# 「ふふ、出たな、蘭美の秘奥義・超高速もちつき。大量のもち米が、１分でつき立ての美味なる餅と化す」
line = "「ふふ、出たな、蘭美の秘奥義・超高速もちつき。大量のもち米が、１分でつき立ての美味なる餅と化す」"

[[dialogue]]
speaker = "unk"
# なんて速さだ！
（ぺったん……ぺったん）
line = "なんて速さだ！\n（ぺったん……ぺったん）"

[[dialogue]]
speaker = "蘭美"
# 「誰のお胸がぺったんですって！？」
line = "「誰のお胸がぺったんですって！？」"

[[dialogue]]
speaker = "ヘレナ"
# 「誰も言っておらぬぞ、蘭美」
line = "「誰も言っておらぬぞ、蘭美」"

[[dialogue]]
speaker = "蘭美"
# 「どこからか心の声が聞こえたような気がしたのだけど……まあいいわ、そんなことよりも餅つきよ！」
line = "「どこからか心の声が聞こえたような気がしたのだけど……まあいいわ、そんなことよりも餅つきよ！」"

[[dialogue]]
speaker = "蘭美"
# 「さぁ、次のもち米を持ってきなさい！　全てぺったんぺったんにしてやるわ！」
line = "「さぁ、次のもち米を持ってきなさい！　全てぺったんぺったんにしてやるわ！」"

[[dialogue]]
speaker = "ヘレナ"
# 「つき立てのお餅が、次から次にできるぞ！　皆の者、熱い内に食せ！」
line = "「つき立てのお餅が、次から次にできるぞ！　皆の者、熱い内に食せ！」"

[[dialogue]]
speaker = "ヘレナ"
# 「だが喉に詰まらないよう気をつけるのだぞ！　ほれ、魔王も食え、食え。これぞ本物の餅だ」
line = "「だが喉に詰まらないよう気をつけるのだぞ！　ほれ、魔王も食え、食え。これぞ本物の餅だ」"

[[dialogue]]
speaker = "unk"
# はふはふ、もぐもぐ
つきたてのお餅、うんま～～い！
line = "はふはふ、もぐもぐ\nつきたてのお餅、うんま～～い！"

[[dialogue]]
speaker = "メルエル"
# 「最後まで作戦に参加できなかったけど、お呼ばれしちゃってよかったのかな……？」
line = "「最後まで作戦に参加できなかったけど、お呼ばれしちゃってよかったのかな……？」"

[[dialogue]]
speaker = "レミカ"
# 「呼ばれてるからにはいいんじゃない？　遠慮なくお餅いただいちゃおうっと。……うん、おいしい」
line = "「呼ばれてるからにはいいんじゃない？　遠慮なくお餅いただいちゃおうっと。……うん、おいしい」"

[[dialogue]]
speaker = "アイリーン"
# 「ん～、お餅おいしー！　ね、ミーちゃん♪」
line = "「ん～、お餅おいしー！　ね、ミーちゃん♪」"

[[dialogue]]
speaker = "オオヒメ"
# 「ふふ……」
line = "「ふふ……」"

[[dialogue]]
speaker = "マグダレナ"
# 「そんなところで黄昏れてどうしました、オオヒメ。みなさまの輪の中に入りづらいのですか？」
line = "「そんなところで黄昏れてどうしました、オオヒメ。みなさまの輪の中に入りづらいのですか？」"

[[dialogue]]
speaker = "オオヒメ"
# 「いや、そうではない。食を楽しむ皆の姿に喜びを感じているのだ」
line = "「いや、そうではない。食を楽しむ皆の姿に喜びを感じているのだ」"

[[dialogue]]
speaker = "オオヒメ"
# 「私が司る摂理は普遍──光や水、空気……『世にあるべきもの』を行き渡らせること。故に私は《天恵》の二つ名を持つ」
line = "「私が司る摂理は普遍──光や水、空気……『世にあるべきもの』を行き渡らせること。故に私は《天恵》の二つ名を持つ」"

[[dialogue]]
speaker = "オオヒメ"
# 「農作物とは光と水、土の結晶だ。餅の原料であるもち米もまた、光や水によって育まれたもの。私の力が世界に貢献している証そのものだ」
line = "「農作物とは光と水、土の結晶だ。餅の原料であるもち米もまた、光や水によって育まれたもの。私の力が世界に貢献している証そのものだ」"

[[dialogue]]
speaker = "オオヒメ"
# 「美味しい餅を口にした者たちが、余すことなく笑顔を浮かべている。私の力で生まれたものが、人々を幸せにしていることが、こんなにも喜ばしい」
line = "「美味しい餅を口にした者たちが、余すことなく笑顔を浮かべている。私の力で生まれたものが、人々を幸せにしていることが、こんなにも喜ばしい」"

[[dialogue]]
speaker = "マグダレナ"
# 「なるほど……あなたらしいですね。せっかくですから、私もあなたがもたらした豊穣のおこぼれにあずかるとしましょう」
line = "「なるほど……あなたらしいですね。せっかくですから、私もあなたがもたらした豊穣のおこぼれにあずかるとしましょう」"

[[dialogue]]
speaker = "マグダレナ"
# 「あ～ん。うふふ……何も付けていないのに、ほのかな甘みがあって美味しいです」
line = "「あ～ん。うふふ……何も付けていないのに、ほのかな甘みがあって美味しいです」"

[[dialogue]]
speaker = "マグダレナ"
# 「はい、あなたもどうぞ♪」
line = "「はい、あなたもどうぞ♪」"

[[dialogue]]
speaker = "オオヒメ"
# 「ああ、頂こう。……うむ、美味い」
line = "「ああ、頂こう。……うむ、美味い」"

[[dialogue]]
speaker = "マグダレナ"
# 「おや、あんこもあるのですね。しかも抹茶あんまで……！　これはおもちを食べるのが止まらなくなってしまいます。オオヒメはどれがお好きですか？」
line = "「おや、あんこもあるのですね。しかも抹茶あんまで……！　これはおもちを食べるのが止まらなくなってしまいます。オオヒメはどれがお好きですか？」"

[[dialogue]]
speaker = "オオヒメ"
# 「そうだな……ひとまず全部試してみるとするか」
line = "「そうだな……ひとまず全部試してみるとするか」"

[[dialogue]]
speaker = "unk"
# 餅はまだまだつき上がる。楽しいパーティはまだまだ終わりを迎えそうにない。
line = "餅はまだまだつき上がる。楽しいパーティはまだまだ終わりを迎えそうにない。"
