[[dialogue]]
speaker = "unk"
# 突然増えてしまったヴィーナス、メルエル、レミカの小さな分身たち。
line = "突然増えてしまったヴィーナス、メルエル、レミカの小さな分身たち。"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「ねぇねぇパパ、どう？　小さくなった私の姿、可愛い？」
line = "「ねぇねぇパパ、どう？　小さくなった私の姿、可愛い？」"

[[dialogue]]
speaker = "unk"
# 俺が『可愛い』と答えると、小さなヴィーナスは嬉しそうな笑顔を見せる。
line = "俺が『可愛い』と答えると、小さなヴィーナスは嬉しそうな笑顔を見せる。"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「えへへぇ～♪　パパに褒められて嬉しいわ♪」
line = "「えへへぇ～♪　パパに褒められて嬉しいわ♪」"

[[dialogue]]
speaker = "unk"
# なんか精神も少し子供っぽくなってるような？
line = "なんか精神も少し子供っぽくなってるような？"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうかしら？　自分から見ると、いつも通りって感じがするけど」
line = "「そうかしら？　自分から見ると、いつも通りって感じがするけど」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「あっ、でも、この姿だと、いつもよりたくさん『パパ』って呼びたくなるわ♪」
line = "「あっ、でも、この姿だと、いつもよりたくさん『パパ』って呼びたくなるわ♪」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「ねぇ、会長くん、私はどうかな？　ヴィーナスちゃんみたいに、可愛くなってる？」
line = "「ねぇ、会長くん、私はどうかな？　ヴィーナスちゃんみたいに、可愛くなってる？」"

[[dialogue]]
speaker = "メルエル"
# 「えっ！？　と、突然何を言ってるの、ちっちゃな私！？」
line = "「えっ！？　と、突然何を言ってるの、ちっちゃな私！？」"

[[dialogue]]
speaker = "unk"
# 俺が小さなメルエルにも素直に『可愛い』と告げると、照れた笑顔を見せる。
line = "俺が小さなメルエルにも素直に『可愛い』と告げると、照れた笑顔を見せる。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「え、えへへへへへぇ<emoji=heart04>　ありがとう♪　すごく嬉しくて、メルトしちゃいそう<emoji=heart04>」
line = "「え、えへへへへへぇ<emoji=heart04>　ありがとう♪　すごく嬉しくて、メルトしちゃいそう<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル"
# 「か、可愛いんだ……<emoji=heart04>」
line = "「か、可愛いんだ……<emoji=heart04>」"

[[dialogue]]
speaker = "メルエル"
# （はうぅぅ<emoji=heart04>　そんなこと言われたら、大きい私までメルトしちゃうよぉ～<emoji=heart04>）
line = "（はうぅぅ<emoji=heart04>　そんなこと言われたら、大きい私までメルトしちゃうよぉ～<emoji=heart04>）"

[[dialogue]]
speaker = "レミカ（幼少）"
# 「あっ、えっと……私のことは褒めてもらわなくても大丈夫だから。小さい姿になっても、２人より『可愛い』ってことはないと思うし……」
line = "「あっ、えっと……私のことは褒めてもらわなくても大丈夫だから。小さい姿になっても、２人より『可愛い』ってことはないと思うし……」"

[[dialogue]]
speaker = "unk"
# 俺と視線が合うと、そんなことを言う小さなレミカ。
line = "俺と視線が合うと、そんなことを言う小さなレミカ。"

[[dialogue]]
speaker = "レミカ（幼少）"
# 「――え？　元の私も可愛いけど、小さくなった姿もすごく可愛い？　も、もう、会長っ、言わなくていいって言ったのに……！」
line = "「――え？　元の私も可愛いけど、小さくなった姿もすごく可愛い？　も、もう、会長っ、言わなくていいって言ったのに……！」"

[[dialogue]]
speaker = "レミカ"
# 「い、いやまぁ、褒めてくれるのは嬉しいんだけど……照れるじゃん……」
line = "「い、いやまぁ、褒めてくれるのは嬉しいんだけど……照れるじゃん……」"

[[dialogue]]
speaker = "unk"
# ２人共顔を赤くして、仲良く視線を逸らしてしまう。うん、可愛い。
line = "２人共顔を赤くして、仲良く視線を逸らしてしまう。うん、可愛い。"

[[dialogue]]
speaker = "unk"
# でも３人共、なんで増えたりしたんだ？
line = "でも３人共、なんで増えたりしたんだ？"

[[dialogue]]
speaker = "ヴィーナス"
# 「それがよくわからないのよね！　なんだか『不思議な力』が私の体から湧いてきて、気づいたら小さい私が増えてて」
line = "「それがよくわからないのよね！　なんだか『不思議な力』が私の体から湧いてきて、気づいたら小さい私が増えてて」"

[[dialogue]]
speaker = "レミカ"
# 「心当たりがあるとすれば……『こどもの日』の話をしてたことかな？」
line = "「心当たりがあるとすれば……『こどもの日』の話をしてたことかな？」"

[[dialogue]]
speaker = "メルエル"
# 「ヴィーナスちゃんの体が突然光り出して、その後に小さな私たちが現れたんだよね」
line = "「ヴィーナスちゃんの体が突然光り出して、その後に小さな私たちが現れたんだよね」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「言われてみれば私、あの時『こどもの日をパパにお祝いされたい』って思ってたわ！」
line = "「言われてみれば私、あの時『こどもの日をパパにお祝いされたい』って思ってたわ！」"

[[dialogue]]
speaker = "unk"
# だとしたら、ヴィーナスの中にある『女神』の力が発動したのかもしれない。
line = "だとしたら、ヴィーナスの中にある『女神』の力が発動したのかもしれない。"

[[dialogue]]
speaker = "unk"
# 俺はその推測をみんなに話す。
line = "俺はその推測をみんなに話す。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「――ヴィーナスちゃんの願いがきっかけで、ちっちゃな私たちが生まれたのかも、ってこと？」
line = "「――ヴィーナスちゃんの願いがきっかけで、ちっちゃな私たちが生まれたのかも、ってこと？」"

[[dialogue]]
speaker = "レミカ（幼少）"
# 「それなら、ヴィーナスの望みを叶えたら元に戻れる、とか……？」
line = "「それなら、ヴィーナスの望みを叶えたら元に戻れる、とか……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それだわ！」
line = "「それだわ！」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「願いを叶えてもらえるなら、私、パパから『こどもの日』をちゃんとお祝いしてもらいたいわ♪」
line = "「願いを叶えてもらえるなら、私、パパから『こどもの日』をちゃんとお祝いしてもらいたいわ♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「いいわね！　それなら、みんなで『こどもの日パーティー』を開催しましょ♪」
line = "「いいわね！　それなら、みんなで『こどもの日パーティー』を開催しましょ♪」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「そうね！　メルエルとレミカも一緒に！」
line = "「そうね！　メルエルとレミカも一緒に！」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「え？　私たちも参加していいの？」
line = "「え？　私たちも参加していいの？」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「もちろん♪　だって、パーティーはみんなでやった方が楽しいでしょ？」
line = "「もちろん♪　だって、パーティーはみんなでやった方が楽しいでしょ？」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「それに小さくなっちゃったのは２人も一緒なんだから、こどもの日をちゃんとお祝いしてもらわないと！」
line = "「それに小さくなっちゃったのは２人も一緒なんだから、こどもの日をちゃんとお祝いしてもらわないと！」"

[[dialogue]]
speaker = "レミカ（幼少）"
# 「確かに、私たちもお祝いしてもらわないと、元に戻れない可能性があるのか……」
line = "「確かに、私たちもお祝いしてもらわないと、元に戻れない可能性があるのか……」"

[[dialogue]]
speaker = "unk"
# ２人のことも全力でお祝いするぞ
line = "２人のことも全力でお祝いするぞ"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「わぁっ♪　会長くんにお祝いしてもらえると思ったら、すごく嬉しくなってきちゃう♪」
line = "「わぁっ♪　会長くんにお祝いしてもらえると思ったら、すごく嬉しくなってきちゃう♪」"

[[dialogue]]
speaker = "レミカ（幼少）"
# 「じゃあ、せっかくだし……お願いしようかな？」
line = "「じゃあ、せっかくだし……お願いしようかな？」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「決まりね♪　よ～し、それじゃあ、今夜のパーティーの準備を始めるわよ！」
line = "「決まりね♪　よ～し、それじゃあ、今夜のパーティーの準備を始めるわよ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「お～♪」
line = "「お～♪」"

[[dialogue]]
speaker = "メルエル"
# 「って、パーティーって今日やるの！？」
line = "「って、パーティーって今日やるの！？」"

[[dialogue]]
speaker = "ヴィーナス（幼少）"
# 「もちろん！　『善は急がばすぐ回れ』よ♪」
line = "「もちろん！　『善は急がばすぐ回れ』よ♪」"

[[dialogue]]
speaker = "レミカ"
# 「う～ん、安定の無茶ぶりだね……」
line = "「う～ん、安定の無茶ぶりだね……」"

[[dialogue]]
speaker = "unk"
# そんなこんなで、俺も協力して『こどもの日パーティー』を開催することになるのだった。
line = "そんなこんなで、俺も協力して『こどもの日パーティー』を開催することになるのだった。"
