[[dialogue]]
speaker = "イニシュ"
# 「蛤塩ラーメン、ごちそうさまでした。あっさりとした味わいながらも確かな貝の存在感があり、洗練された一杯でした」
line = "「蛤塩ラーメン、ごちそうさまでした。あっさりとした味わいながらも確かな貝の存在感があり、洗練された一杯でした」"

[[dialogue]]
speaker = "ウェンディ"
# 「いつの間にかラーメン通みたいな語りになってきましたね……」
line = "「いつの間にかラーメン通みたいな語りになってきましたね……」"

[[dialogue]]
speaker = "イニシュ"
# 「ウェンディはどうでしたか？」
line = "「ウェンディはどうでしたか？」"

[[dialogue]]
speaker = "ウェンディ"
# 「確かに美味しかったです。それに女性でも入れるお洒落な雰囲気で、また訪れてもいいと思いました」
line = "「確かに美味しかったです。それに女性でも入れるお洒落な雰囲気で、また訪れてもいいと思いました」"

[[dialogue]]
speaker = "ウェンディ"
# 「ラーメンに対するイメージが少し変わる体験でした。飲食部門でも新事業を立ち上げたいと考えていましたが、検討してみましょうか」
line = "「ラーメンに対するイメージが少し変わる体験でした。飲食部門でも新事業を立ち上げたいと考えていましたが、検討してみましょうか」"

[[dialogue]]
speaker = "unk"
# 何の話？
line = "何の話？"

[[dialogue]]
speaker = "ウェンディ"
# 「ハッ──しまった！？」
line = "「ハッ──しまった！？」"

[[dialogue]]
speaker = "ウェンディ"
# 「あー……ええっと……コホン。今から言うことはオフレコにしていただきたいのですが……」
line = "「あー……ええっと……コホン。今から言うことはオフレコにしていただきたいのですが……」"

[[dialogue]]
speaker = "ウェンディ"
# 「ネビュラは人間界に傘下の企業を複数持ち、それらを資金源としています。その管理や運用が私の主な仕事です」
line = "「ネビュラは人間界に傘下の企業を複数持ち、それらを資金源としています。その管理や運用が私の主な仕事です」"

[[dialogue]]
speaker = "ウェンディ"
# 「かつて他のネビュラ構成員から人間界──特に経済のことを学んだ私は、魔女の森に銀行を設立し、産業を興して、森を発展させようと提案しました」
line = "「かつて他のネビュラ構成員から人間界──特に経済のことを学んだ私は、魔女の森に銀行を設立し、産業を興して、森を発展させようと提案しました」"

[[dialogue]]
speaker = "ウェンディ"
# 「しかし魔女の森は閉鎖的かつ保守的で、危険思想を持つ者として追放されそうになったんです」
line = "「しかし魔女の森は閉鎖的かつ保守的で、危険思想を持つ者として追放されそうになったんです」"

[[dialogue]]
speaker = "ウェンディ"
# 「そんな私を拾ってくれたのがセドナ長官でした」
line = "「そんな私を拾ってくれたのがセドナ長官でした」"

[[dialogue]]
speaker = "ウェンディ"
# 「ネビュラが人間界で活動するためにウェンディが必要だ──と長老たちを説得して、私を引き抜いてくれたんです」
line = "「ネビュラが人間界で活動するためにウェンディが必要だ──と長老たちを説得して、私を引き抜いてくれたんです」"

[[dialogue]]
speaker = "ウェンディ"
# 「だから私はセドナ長官を強く尊敬しています。私はあの人のためにネビュラで働いていると言っても過言ではありません」
line = "「だから私はセドナ長官を強く尊敬しています。私はあの人のためにネビュラで働いていると言っても過言ではありません」"

[[dialogue]]
speaker = "ウェンディ"
# 「なのでこんなことで長官を煩わせたくはないのですが……」
line = "「なのでこんなことで長官を煩わせたくはないのですが……」"

[[dialogue]]
speaker = "イニシュ"
# 「ウェンディも栄養補給が済んだようですし、モンスターの捜索を再開しましょう」
line = "「ウェンディも栄養補給が済んだようですし、モンスターの捜索を再開しましょう」"

[[dialogue]]
speaker = "ウェンディ"
# 「その前に……三郎系、でしたっけ。少し歩きますが大盛りで有名なお店があるそうです。私と会長さんは満腹なので気になるならおひとりでどうぞ」
line = "「その前に……三郎系、でしたっけ。少し歩きますが大盛りで有名なお店があるそうです。私と会長さんは満腹なので気になるならおひとりでどうぞ」"

[[dialogue]]
speaker = "ウェンディ"
# 「ちなみにマシマシでトッピングを倍にできるそうですよ」
line = "「ちなみにマシマシでトッピングを倍にできるそうですよ」"

[[dialogue]]
speaker = "イニシュ"
# 「情報提供ありがとうございます。行ってきます」
line = "「情報提供ありがとうございます。行ってきます」"

[[dialogue]]
speaker = "ウェンディ"
# 「迷いなく行きましたね……彼女の胃袋はどうなってるんでしょうか……」
line = "「迷いなく行きましたね……彼女の胃袋はどうなってるんでしょうか……」"

[[dialogue]]
speaker = "unk"
# ところでイニシュにも聞いたんだけど……
line = "ところでイニシュにも聞いたんだけど……"

[[dialogue]]
speaker = "ウェンディ"
# 「我々魔女がリクリエと戦う理由……ですか？」
line = "「我々魔女がリクリエと戦う理由……ですか？」"

[[dialogue]]
speaker = "ウェンディ"
# 「リクリエが魔女の森に及ばないなら、三界に干渉する必要はないと。……ふむ。新星学園の会長さんともあろう方が冷たいことを言いますね」
line = "「リクリエが魔女の森に及ばないなら、三界に干渉する必要はないと。……ふむ。新星学園の会長さんともあろう方が冷たいことを言いますね」"

[[dialogue]]
speaker = "ウェンディ"
# 「結論から言うとそれは違います。魔女はそんな薄情な種族ではありません」
line = "「結論から言うとそれは違います。魔女はそんな薄情な種族ではありません」"

[[dialogue]]
speaker = "ウェンディ"
# 「他の種族を信用していないのには理由があるんですけど……それは置いておくとして。ネビュラには三界の破滅を願っている魔女は１人もいません」
line = "「他の種族を信用していないのには理由があるんですけど……それは置いておくとして。ネビュラには三界の破滅を願っている魔女は１人もいません」"

[[dialogue]]
speaker = "ウェンディ"
# 「会長さんには理解できないかもしれませんが……我々の活動は、先人たちの無念を晴らすため」
line = "「会長さんには理解できないかもしれませんが……我々の活動は、先人たちの無念を晴らすため」"

[[dialogue]]
speaker = "ウェンディ"
# 「あるいは、数千、数万年前からの宿題を終わらせるためと言ってもいいかもしれません」
line = "「あるいは、数千、数万年前からの宿題を終わらせるためと言ってもいいかもしれません」"

[[dialogue]]
speaker = "コハルコ"
# 『会長さん、そこから南東５００メートル、モンスターらしき反応です』
line = "『会長さん、そこから南東５００メートル、モンスターらしき反応です』"

[[dialogue]]
speaker = "unk"
# 了解です！
line = "了解です！"

[[dialogue]]
speaker = "モンスター"
# 「────！」
line = "「────！」"

[[dialogue]]
speaker = "ウェンディ"
# 「強い……！」
line = "「強い……！」"

[[dialogue]]
speaker = "ウェンディ"
# 「攻撃力、耐久力、反応速度……どれもデータを大きく上回っています。おかしいです。この個体はこれほどの戦闘力は持っていなかったはず……」
line = "「攻撃力、耐久力、反応速度……どれもデータを大きく上回っています。おかしいです。この個体はこれほどの戦闘力は持っていなかったはず……」"

[[dialogue]]
speaker = "ウェンディ"
# 「この強さはネビュラの改造によるものではない……それにこの狂暴性も改造で修正したはずです」
line = "「この強さはネビュラの改造によるものではない……それにこの狂暴性も改造で修正したはずです」"

[[dialogue]]
speaker = "モンスター"
# 「～～～～！」
line = "「～～～～！」"

[[dialogue]]
speaker = "ウェンディ"
# 「くっ……この強さでは捕獲は困難。それにことが大きくなればネビュラの存在が明るみに……」
line = "「くっ……この強さでは捕獲は困難。それにことが大きくなればネビュラの存在が明るみに……」"

[[dialogue]]
speaker = "ウェンディ"
# 「会長さん、このモンスターの捕獲は諦めてここで消滅させます！」
line = "「会長さん、このモンスターの捕獲は諦めてここで消滅させます！」"

[[dialogue]]
speaker = "unk"
# いいのか？
line = "いいのか？"

[[dialogue]]
speaker = "ウェンディ"
# 「はい、セドナ長官なら的確な判断をしろと仰るはずです」
line = "「はい、セドナ長官なら的確な判断をしろと仰るはずです」"

[[dialogue]]
speaker = "ウェンディ"
# 「会長さん、力を借ります。──ミラージュアルター！」
line = "「会長さん、力を借ります。──ミラージュアルター！」"

[[dialogue]]
speaker = "ウェンディ"
# 「分身と同時攻撃です！　合わせてください！」
line = "「分身と同時攻撃です！　合わせてください！」"

[[dialogue]]
speaker = "モンスター"
# 「～～～～～！？」
line = "「～～～～～！？」"

[[dialogue]]
speaker = "ウェンディ"
# 「ふぅ……なんとかなりました……」
line = "「ふぅ……なんとかなりました……」"

[[dialogue]]
speaker = "ウェンディ"
# 「残るモンスターは１体……長官に怒られるのは確実ですけど、燃やされないことを祈りますかね……」
line = "「残るモンスターは１体……長官に怒られるのは確実ですけど、燃やされないことを祈りますかね……」"

[[dialogue]]
speaker = "コハルコ"
# 『会長さん、お疲れ様。さっきの反応はやっぱりモンスターだったみたいだね』
line = "『会長さん、お疲れ様。さっきの反応はやっぱりモンスターだったみたいだね』"

[[dialogue]]
speaker = "コハルコ"
# 『会長さんの周りで他にも誰か戦ってるみたいだけど……流星の人？』
line = "『会長さんの周りで他にも誰か戦ってるみたいだけど……流星の人？』"

[[dialogue]]
speaker = "ウェンディ"
# （魔法を星術に誤認させる魔法で、直接は魔女とわからないようにしてます。適当にごまかしておいてください）
line = "（魔法を星術に誤認させる魔法で、直接は魔女とわからないようにしてます。適当にごまかしておいてください）"

[[dialogue]]
speaker = "unk"
# 企業秘密ということで……
line = "企業秘密ということで……"

[[dialogue]]
speaker = "コハルコ"
# 『？　みんな無事ならそれでいいんだけど──』
line = "『？　みんな無事ならそれでいいんだけど──』"

[[dialogue]]
speaker = "？？？"
# 「ほっと一息ついたところ悪いけど……メインイベントはこれからだよ！」
line = "「ほっと一息ついたところ悪いけど……メインイベントはこれからだよ！」"

[[dialogue]]
speaker = "コハルコ"
# 『！　アステライト反応──多数！？　１つ、２つ、３つ……数えきれない速度で増加中です！』
line = "『！　アステライト反応──多数！？　１つ、２つ、３つ……数えきれない速度で増加中です！』"

[[dialogue]]
speaker = "コハルコ"
# 『しかも会長さんの周りだけ局所的に……？　なんなのこの現象、見たことない……』
line = "『しかも会長さんの周りだけ局所的に……？　なんなのこの現象、見たことない……』"

[[dialogue]]
speaker = "ウェンディ"
# 「空がアステライトだらけ……？　いくらなんでもめちゃくちゃな……」
line = "「空がアステライトだらけ……？　いくらなんでもめちゃくちゃな……」"

[[dialogue]]
speaker = "アイリーン"
# 『ウェンディさん！　大変だよ！』
line = "『ウェンディさん！　大変だよ！』"

[[dialogue]]
speaker = "ウェンディ"
# 「あ、とうとう長官にバレましたか？　いろんな意味でファイアされる覚悟をしておきますか……」
line = "「あ、とうとう長官にバレましたか？　いろんな意味でファイアされる覚悟をしておきますか……」"

[[dialogue]]
speaker = "アイリーン"
# 『それどころじゃないよ！　ウェンディさんが捕まえたモンスターが全部逃げたんだ！』
line = "『それどころじゃないよ！　ウェンディさんが捕まえたモンスターが全部逃げたんだ！』"

[[dialogue]]
speaker = "ウェンディ"
# 「はああぁっ！？」
line = "「はああぁっ！？」"

[[dialogue]]
speaker = "ウェンディ"
# 「ウソ……何これ……」
line = "「ウソ……何これ……」"

[[dialogue]]
speaker = "ウェンディ"
# 「ハハ、冗談ですよね……ちょっとシャレになりませんよ？　ていうかコレ私のせいじゃないですよね！？」
line = "「ハハ、冗談ですよね……ちょっとシャレになりませんよ？　ていうかコレ私のせいじゃないですよね！？」"

[[dialogue]]
speaker = "unk"
# 数が多いだけならなんとか……
line = "数が多いだけならなんとか……"

[[dialogue]]
speaker = "モンスター"
# 「～～～～～！」
line = "「～～～～～！」"

[[dialogue]]
speaker = "ウェンディ"
# 「くっ……このタイミングで最後のモンスター……しかもさっきのより強くなってませんか……？」
line = "「くっ……このタイミングで最後のモンスター……しかもさっきのより強くなってませんか……？」"

[[dialogue]]
speaker = "リーリア"
# 「センパイのピンチにリーリアが応援に駆け付けましたよ！　もちろん喜んでくれますよね、セ・ン・パ・イ♪」
line = "「センパイのピンチにリーリアが応援に駆け付けましたよ！　もちろん喜んでくれますよね、セ・ン・パ・イ♪」"

[[dialogue]]
speaker = "リーリア"
# 「──って、きゃああ！？　タイヘンなことになってますよぉ～！？」
line = "「──って、きゃああ！？　タイヘンなことになってますよぉ～！？」"
