[[dialogue]]
speaker = "ウェンディ"
# 「くっ……虫みたいに次から次へとモンスターが……」
line = "「くっ……虫みたいに次から次へとモンスターが……」"

[[dialogue]]
speaker = "リーリア"
# 「ちょっと多すぎなんですけど！　しかも普通のよりちょっと強いし！」
line = "「ちょっと多すぎなんですけど！　しかも普通のよりちょっと強いし！」"

[[dialogue]]
speaker = "リーリア"
# （わかってると思いますけど、余計なこと言わないでくださいね？）
line = "（わかってると思いますけど、余計なこと言わないでくださいね？）"

[[dialogue]]
speaker = "ウェンディ"
# （当然です。あなたを送り込むのにどれだけコストがかかったと思っているんですか）
line = "（当然です。あなたを送り込むのにどれだけコストがかかったと思っているんですか）"

[[dialogue]]
speaker = "ウェンディ"
# 「アステラを叩かないとキリがありません！　このままだと押し潰されます！」
line = "「アステラを叩かないとキリがありません！　このままだと押し潰されます！」"

[[dialogue]]
speaker = "リーリア"
# 「できるならやってますよ！　でも目の前のモンスターの相手をするので手一杯です！」
line = "「できるならやってますよ！　でも目の前のモンスターの相手をするので手一杯です！」"

[[dialogue]]
speaker = "unk"
# 俺が切り開く……！
line = "俺が切り開く……！"

[[dialogue]]
speaker = "ウェンディ"
# 「会長さん！？　大丈夫ですか！？」
line = "「会長さん！？　大丈夫ですか！？」"

[[dialogue]]
speaker = "unk"
# なんとか……
line = "なんとか……"

[[dialogue]]
speaker = "ウェンディ"
# 「会長さんもアポロのモンスターの相手で精いっぱいのようですね。しかも今まで捕まえたやつまで狂暴化してますし」
line = "「会長さんもアポロのモンスターの相手で精いっぱいのようですね。しかも今まで捕まえたやつまで狂暴化してますし」"

[[dialogue]]
speaker = "コハルコ"
# 『ごめんなさい。応援の星騎士が向かっているんだけど、モンスターの大群に阻まれてて』
line = "『ごめんなさい。応援の星騎士が向かっているんだけど、モンスターの大群に阻まれてて』"

[[dialogue]]
speaker = "コハルコ"
# 『私の方でも打開策を考えてるんだけど、こんなに局所的にモンスターやアステラが発生するなんて例がなくて……』
line = "『私の方でも打開策を考えてるんだけど、こんなに局所的にモンスターやアステラが発生するなんて例がなくて……』"

[[dialogue]]
speaker = "リーリア"
# 「コハルコ先輩に策がないって言われると何気にショックですね……。そこの鏡の人！　何か切り札とかないんですか？」
line = "「コハルコ先輩に策がないって言われると何気にショックですね……。そこの鏡の人！　何か切り札とかないんですか？」"

[[dialogue]]
speaker = "ウェンディ"
# 「かが──！？　コホン。また会長さんの分身を作れば一点突破できるかもしれませんが、守りが薄くなるのでこちらが瓦解する可能性の方が高いです」
line = "「かが──！？　コホン。また会長さんの分身を作れば一点突破できるかもしれませんが、守りが薄くなるのでこちらが瓦解する可能性の方が高いです」"

[[dialogue]]
speaker = "リーリア"
# 「それでもやるしかないですよ！　このまま追い詰められるよりマシです！」
line = "「それでもやるしかないですよ！　このまま追い詰められるよりマシです！」"

[[dialogue]]
speaker = "ウェンディ"
# 「やむをえません。一か八か──ミラージュアルター！」
line = "「やむをえません。一か八か──ミラージュアルター！」"

[[dialogue]]
speaker = "リーリア"
# 「ちょっと！？　分身センパイあっさり消えちゃったんですけど！？」
line = "「ちょっと！？　分身センパイあっさり消えちゃったんですけど！？」"

[[dialogue]]
speaker = "ウェンディ"
# 「すみません、鏡像の強度不足でした……。魔力がもうギリギリで……」
line = "「すみません、鏡像の強度不足でした……。魔力がもうギリギリで……」"

[[dialogue]]
speaker = "リーリア"
# 「私も弾がそろそろヤバいです！　このままじゃ本当にすり潰されますよ！」
line = "「私も弾がそろそろヤバいです！　このままじゃ本当にすり潰されますよ！」"

[[dialogue]]
speaker = "イニシュ"
# 「申し訳ありません。ヤサイブタアブラマシマシマシは想定以上のボリュームで、完食に時間がかかってしまいました」
line = "「申し訳ありません。ヤサイブタアブラマシマシマシは想定以上のボリュームで、完食に時間がかかってしまいました」"

[[dialogue]]
speaker = "ウェンディ"
# 「どれだけラーメンに夢中になってたんですか！　ていうかマシ過ぎです！」
line = "「どれだけラーメンに夢中になってたんですか！　ていうかマシ過ぎです！」"

[[dialogue]]
speaker = "イニシュ"
# 「塩味が強めの醤油に、背脂のコク、ニンニクの刺激が相まって、とても力強い味でした。満足感があるのに、また食したくなる不思議な感覚です」
line = "「塩味が強めの醤油に、背脂のコク、ニンニクの刺激が相まって、とても力強い味でした。満足感があるのに、また食したくなる不思議な感覚です」"

[[dialogue]]
speaker = "リーリア"
# 「感想はいいですから！」
line = "「感想はいいですから！」"

[[dialogue]]
speaker = "イニシュ"
# 「──多数のモンスターおよびアステラを確認」
line = "「──多数のモンスターおよびアステラを確認」"

[[dialogue]]
speaker = "イニシュ"
# 「これより殲滅を開始します」
line = "「これより殲滅を開始します」"

[[dialogue]]
speaker = "イニシュ"
# 「アンブラル──」
line = "「アンブラル──」"

[[dialogue]]
speaker = "イニシュ"
# 「ヴァナルガンド」
line = "「ヴァナルガンド」"

[[dialogue]]
speaker = "unk"
# イニシュのマントから溢れた闇の奔流が、黒い狼の群れとなってモンスターに襲い掛かる。
line = "イニシュのマントから溢れた闇の奔流が、黒い狼の群れとなってモンスターに襲い掛かる。"

[[dialogue]]
speaker = "unk"
# それは蹂躙だった。
line = "それは蹂躙だった。"

[[dialogue]]
speaker = "unk"
# 爪は紙を裂くようにモンスターを八つ裂きにし、牙は泡を刺すように容易く貫く。
line = "爪は紙を裂くようにモンスターを八つ裂きにし、牙は泡を刺すように容易く貫く。"

[[dialogue]]
speaker = "unk"
# 貪欲に、強欲に。
line = "貪欲に、強欲に。"

[[dialogue]]
speaker = "unk"
# リクリエの尖兵を余すことなく喰らい尽くさんと、黒狼が<ruby=あぎと>顎</ruby>を振るった。
line = "リクリエの尖兵を余すことなく喰らい尽くさんと、黒狼が<ruby>顎<rt>あぎと</rt></ruby>を振るった。"

[[dialogue]]
speaker = "イニシュ"
# 「アステラを駆除します」
line = "「アステラを駆除します」"

[[dialogue]]
speaker = "unk"
# 黒い狼は夜空を駆けてアステラに飛び込み、巣穴を駆逐していく。
line = "黒い狼は夜空を駆けてアステラに飛び込み、巣穴を駆逐していく。"

[[dialogue]]
speaker = "unk"
# 狼に喰われた巣はひとつ、またひとつと瞬く間に数を減らしていき──
line = "狼に喰われた巣はひとつ、またひとつと瞬く間に数を減らしていき──"

[[dialogue]]
speaker = "イニシュ"
# 「全てのアステラの消滅を確認しました」
line = "「全てのアステラの消滅を確認しました」"

[[dialogue]]
speaker = "unk"
# アステラがこんな簡単に……
line = "アステラがこんな簡単に……"

[[dialogue]]
speaker = "unk"
# ！　まだモンスターの残りが──
line = "！　まだモンスターの残りが──"

[[dialogue]]
speaker = "？？？"
# 「魔王の力はその程度か？」
line = "「魔王の力はその程度か？」"

[[dialogue]]
speaker = "ウェンディ"
# 「セ、セ、セ、セドナ長官！？」
line = "「セ、セ、セ、セドナ長官！？」"

[[dialogue]]
speaker = "セドナ"
# 「アイリーンの報告を聞いて人間界に出てみればこの騒ぎ。ウェンディ、後で話を聞かせてもらうぞ」
line = "「アイリーンの報告を聞いて人間界に出てみればこの騒ぎ。ウェンディ、後で話を聞かせてもらうぞ」"

[[dialogue]]
speaker = "ウェンディ"
# 「すみませええぇぇんっ！」
line = "「すみませええぇぇんっ！」"

[[dialogue]]
speaker = "セドナ"
# 「だがその前に掃除だ。魔導八式──プロメテウス」
line = "「だがその前に掃除だ。魔導八式──プロメテウス」"

[[dialogue]]
speaker = "unk"
# 魔女が指をパチンと鳴らす。
line = "魔女が指をパチンと鳴らす。"

[[dialogue]]
speaker = "unk"
# それだけモンスターが黒炎に包まれ、俺とウェンディの頑張りは灰も残らず燃え尽きた──
line = "それだけモンスターが黒炎に包まれ、俺とウェンディの頑張りは灰も残らず燃え尽きた──"
