[[dialogue]]
speaker = "unk"
# パテルストーンの事件からしばらくして──
line = "パテルストーンの事件からしばらくして──"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「はぁ……パテルの肝試しで、あんなに怖がってしまうとは思いませんでした」
line = "「はぁ……パテルの肝試しで、あんなに怖がってしまうとは思いませんでした」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「大人の姿ならあそこまで怖いと思わないはず……やっぱり肉体に感覚が引きずられているんですね」
line = "「大人の姿ならあそこまで怖いと思わないはず……やっぱり肉体に感覚が引きずられているんですね」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「マグダレナ、大変なのだ！」
line = "「マグダレナ、大変なのだ！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「どうしました、アルモタヘル？」
line = "「どうしました、アルモタヘル？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「アルモたんの肉巻きおにぎりが──」
line = "「アルモたんの肉巻きおにぎりが──」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「とろろ昆布巻きおにぎりになっていたのだ！！」
line = "「とろろ昆布巻きおにぎりになっていたのだ！！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「えええ～～っ！？」
line = "「えええ～～っ！？」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「って、つい驚いちゃいましたけど、それは大したことないような……」
line = "「って、つい驚いちゃいましたけど、それは大したことないような……」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「大問題なのだ！　昆布も美味しいけど、お肉と昆布は違うのだ！」
line = "「大問題なのだ！　昆布も美味しいけど、お肉と昆布は違うのだ！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ハッ──！？　私の抹茶クッキーもほうじ茶クッキーにすり替えられてます！　だ、誰がこんなことを……！？」
line = "「ハッ──！？　私の抹茶クッキーもほうじ茶クッキーにすり替えられてます！　だ、誰がこんなことを……！？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「あんまり違わないのだ」
line = "「あんまり違わないのだ」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「違いますぅ～っ！　ほうじ茶もいいですけど、私は抹茶味が好きなんですぅ～っ！」
line = "「違いますぅ～っ！　ほうじ茶もいいですけど、私は抹茶味が好きなんですぅ～っ！」"

[[dialogue]]
speaker = "？？？"
# 「アハハ、ちっちゃい方の２人はからかい甲斐があるなぁ～」
line = "「アハハ、ちっちゃい方の２人はからかい甲斐があるなぁ～」"

[[dialogue]]
speaker = "？？？"
# 「それじゃ次は……」
line = "「それじゃ次は……」"

[[dialogue]]
speaker = "unk"
# 星徒会の仕事を終えて、いつものように通学路を通って帰宅していると──
line = "星徒会の仕事を終えて、いつものように通学路を通って帰宅していると──"

[[dialogue]]
speaker = "？？？"
# 「だ～れだ？」
line = "「だ～れだ？」"

[[dialogue]]
speaker = "unk"
# パテル？
line = "パテル？"

[[dialogue]]
speaker = "パテル"
# 「正解！　また会ったね、魔王」
line = "「正解！　また会ったね、魔王」"

[[dialogue]]
speaker = "パテル"
# 「ほら、パテルストーンを一番見つけた人にご褒美あげるって言ってたでしょ。はい、肉巻きおにぎりと抹茶クッキーあげるね」
line = "「ほら、パテルストーンを一番見つけた人にご褒美あげるって言ってたでしょ。はい、肉巻きおにぎりと抹茶クッキーあげるね」"

[[dialogue]]
speaker = "パテル"
# 「え？　どこから持ってきたのって？　大丈夫、食べても問題ないやつだから」
line = "「え？　どこから持ってきたのって？　大丈夫、食べても問題ないやつだから」"

[[dialogue]]
speaker = "unk"
# 少し雰囲気変わった？
line = "少し雰囲気変わった？"

[[dialogue]]
speaker = "パテル"
# 「そうかなー？　そうかも」
line = "「そうかなー？　そうかも」"

[[dialogue]]
speaker = "パテル"
# 「魔王やマグダレナたちのことはこっそり監視するつもりだったけど、監視してるって本人に言っちゃったからね。あんまり隠れる必要もないと思って」
line = "「魔王やマグダレナたちのことはこっそり監視するつもりだったけど、監視してるって本人に言っちゃったからね。あんまり隠れる必要もないと思って」"

[[dialogue]]
speaker = "パテル"
# 「だから今後はもう少しみんなの前に顔を出すと思うよ」
line = "「だから今後はもう少しみんなの前に顔を出すと思うよ」"

[[dialogue]]
speaker = "unk"
# それはよかった
line = "それはよかった"

[[dialogue]]
speaker = "パテル"
# 「フランとグロリアにも会ってきたところ。フランは相変わらずだけど、グロリアは喜んでくれたよ」
line = "「フランとグロリアにも会ってきたところ。フランは相変わらずだけど、グロリアは喜んでくれたよ」"

[[dialogue]]
speaker = "パテル"
# 「魔王、ちょっとお願いしていい？」
line = "「魔王、ちょっとお願いしていい？」"

[[dialogue]]
speaker = "パテル"
# 「正直言うと、勢いで肉体を作ってもらったし、後悔したこともあるから、あたしの分身が言ってたこともあながち否定できないんだよね」
line = "「正直言うと、勢いで肉体を作ってもらったし、後悔したこともあるから、あたしの分身が言ってたこともあながち否定できないんだよね」"

[[dialogue]]
speaker = "パテル"
# 「自分にあんなこと言った手前かっこ悪いけど、ちょっぴり不安なんだ。あたしがダメな死神にならないかって」
line = "「自分にあんなこと言った手前かっこ悪いけど、ちょっぴり不安なんだ。あたしがダメな死神にならないかって」"

[[dialogue]]
speaker = "パテル"
# 「だから、あたしが死神らしくないことしそうになったら止めてほしいんだ」
line = "「だから、あたしが死神らしくないことしそうになったら止めてほしいんだ」"

[[dialogue]]
speaker = "unk"
# そうならないと信じてるけど、わかった
line = "そうならないと信じてるけど、わかった"

[[dialogue]]
speaker = "パテル"
# 「ありがと。頼りにしてるからね」
line = "「ありがと。頼りにしてるからね」"

[[dialogue]]
speaker = "パテル"
# 「それじゃ──」
line = "「それじゃ──」"

[[dialogue]]
speaker = "パテル"
# 「コチョコチョコチョコチョ～♪」
line = "「コチョコチョコチョコチョ～♪」"

[[dialogue]]
speaker = "unk"
# ワハハハハッ！？
line = "ワハハハハッ！？"

[[dialogue]]
speaker = "パテル"
# 「真面目な話してて油断した？　アハハ、死神に隙を見せちゃいけないんだよ～♪」
line = "「真面目な話してて油断した？　アハハ、死神に隙を見せちゃいけないんだよ～♪」"

[[dialogue]]
speaker = "unk"
# パテルはかわいい女の子で、その本分は冷酷な死神で、だけどイタズラ好きで。
line = "パテルはかわいい女の子で、その本分は冷酷な死神で、だけどイタズラ好きで。"

[[dialogue]]
speaker = "unk"
# 彼女の前ではいろんな意味で気を抜けないと、改めて思うのだった。
line = "彼女の前ではいろんな意味で気を抜けないと、改めて思うのだった。"
