[[dialogue]]
speaker = "unk"
# マトイがマムに指導をお願いしに来たところで遭遇した、<ruby=しろたて>白楯</ruby>アム。俺が彼女に事情を説明すると――
line = "マトイがマムに指導をお願いしに来たところで遭遇した、<ruby>白楯<rt>しろたて</rt></ruby>アム。俺が彼女に事情を説明すると――"

[[dialogue]]
speaker = "アム"
# 「――ふむふむ、なるほど。つまり、マトイ先輩は……あたしと同じってことですね！」
line = "「――ふむふむ、なるほど。つまり、マトイ先輩は……あたしと同じってことですね！」"

[[dialogue]]
speaker = "アム"
# 「実はあたしも最近、マムに訓練を見てもらってるんです！」
line = "「実はあたしも最近、マムに訓練を見てもらってるんです！」"

[[dialogue]]
speaker = "unk"
# 彼女は流星学園附属校３年生の白楯アム。
line = "彼女は流星学園附属校３年生の白楯アム。"

[[dialogue]]
speaker = "unk"
# 難攻不落と言われる程の盾使いとして有名であり、附属校の枠にとどまらず２つの本校を含めても、鉄壁の防御力を誇る星騎士だ。
line = "難攻不落と言われる程の盾使いとして有名であり、附属校の枠にとどまらず２つの本校を含めても、鉄壁の防御力を誇る星騎士だ。"

[[dialogue]]
speaker = "unk"
# ヴィーナスに憧れており、本人も新星学園への進学を希望していることから、次期星徒会メンバーとしての有望株。
line = "ヴィーナスに憧れており、本人も新星学園への進学を希望していることから、次期星徒会メンバーとしての有望株。"

[[dialogue]]
speaker = "unk"
# また、俺が御前試合でヴィーナスに勝ったことから、星徒会長になることを目標としている彼女にライバル視され、よく勝負を挑まれていたりする。
line = "また、俺が御前試合でヴィーナスに勝ったことから、星徒会長になることを目標としている彼女にライバル視され、よく勝負を挑まれていたりする。"

[[dialogue]]
speaker = "マトイ"
# 「そういえばさっき言ってたけど、アムちゃんのそれって、水着フォームなの？」
line = "「そういえばさっき言ってたけど、アムちゃんのそれって、水着フォームなの？」"

[[dialogue]]
speaker = "アム"
# 「ふっふっふ！　実はそうなんですよ～♪　前にヴィーナス前会長が手に入れたって聞いた時から、なにそれあたしも欲しい！　ってずっと思ってて！」
line = "「ふっふっふ！　実はそうなんですよ～♪　前にヴィーナス前会長が手に入れたって聞いた時から、なにそれあたしも欲しい！　ってずっと思ってて！」"

[[dialogue]]
speaker = "アム"
# 「リゾート結界に水着を着てきて変身を試したら、見事水着フォームの獲得に成功したというわけです！　へっへ～ん♪」
line = "「リゾート結界に水着を着てきて変身を試したら、見事水着フォームの獲得に成功したというわけです！　へっへ～ん♪」"

[[dialogue]]
speaker = "アム"
# 「ねぇ、会長！　どうどう？　あたしの水着フォーム、カッコいいでしょ～♪」
line = "「ねぇ、会長！　どうどう？　あたしの水着フォーム、カッコいいでしょ～♪」"

[[dialogue]]
speaker = "アム"
# 「――ん？　似合ってるけど、１つ質問がある？」
line = "「――ん？　似合ってるけど、１つ質問がある？」"

[[dialogue]]
speaker = "unk"
# なんでスクール水着なんだ？
line = "なんでスクール水着なんだ？"

[[dialogue]]
speaker = "マトイ"
# 「聞きづらいところにツッコんだ！」
line = "「聞きづらいところにツッコんだ！」"

[[dialogue]]
speaker = "アム"
# 「それはだって――」
line = "「それはだって――」"

[[dialogue]]
speaker = "アム"
# 「学園指定のスク水って、ほら……カッコいいじゃん？」
line = "「学園指定のスク水って、ほら……カッコいいじゃん？」"

[[dialogue]]
speaker = "マトイ"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "アム"
# 「流星学園附属校指定の水着ということは、それすなわち星騎士であることの証！」
line = "「流星学園附属校指定の水着ということは、それすなわち星騎士であることの証！」"

[[dialogue]]
speaker = "アム"
# 「この水着フォームで堂々とビーチを歩けば、リゾート結界に遊びに来た一般の人達はこう思うはず――」
line = "「この水着フォームで堂々とビーチを歩けば、リゾート結界に遊びに来た一般の人達はこう思うはず――」"

[[dialogue]]
speaker = "アム"
# 「『おっ、あの子、星騎士なんだ。しかも、水着が纏う星力から、すごく強いに違いない』って……！」
line = "「『おっ、あの子、星騎士なんだ。しかも、水着が纏う星力から、すごく強いに違いない』って……！」"

[[dialogue]]
speaker = "アム"
# 「それってこう、想像しただけでニヤニヤしちゃうというか……ふふふ♪」
line = "「それってこう、想像しただけでニヤニヤしちゃうというか……ふふふ♪」"

[[dialogue]]
speaker = "unk"
# き、気がつくかな……
line = "き、気がつくかな……"

[[dialogue]]
speaker = "マトイ"
# （そもそも普通の人は星力が感知できないし、ただのスク水と思われるだけの気が……戦闘服化しちゃってるし、言わないけども……）
line = "（そもそも普通の人は星力が感知できないし、ただのスク水と思われるだけの気が……戦闘服化しちゃってるし、言わないけども……）"

[[dialogue]]
speaker = "リップル"
# 「ワタシはアムの水着フォーム、ＢＩＧカッコイイと思いますよ！　スク水と言うのデスね！」
line = "「ワタシはアムの水着フォーム、ＢＩＧカッコイイと思いますよ！　スク水と言うのデスね！」"

[[dialogue]]
speaker = "アム"
# 「でしょ～？　えへへ♪　ありがとうございます、リップル先輩！」
line = "「でしょ～？　えへへ♪　ありがとうございます、リップル先輩！」"

[[dialogue]]
speaker = "unk"
# 『水着フォーム』とは、リップルのリゾート結界内において、星騎士が結界の空に作られた疑似守護星とリンクすることで変身可能となる、特殊な戦闘服のことである。
line = "『水着フォーム』とは、リップルのリゾート結界内において、星騎士が結界の空に作られた疑似守護星とリンクすることで変身可能となる、特殊な戦闘服のことである。"

[[dialogue]]
speaker = "unk"
# その戦闘力は決して伊達ではなく、通常戦闘服に匹敵、あるいは上回る程。
line = "その戦闘力は決して伊達ではなく、通常戦闘服に匹敵、あるいは上回る程。"

[[dialogue]]
speaker = "unk"
# 更に１度水着フォームを覚醒させれば、以後はリゾート結界の外でも変身可能と、非常に強力な力である。
line = "更に１度水着フォームを覚醒させれば、以後はリゾート結界の外でも変身可能と、非常に強力な力である。"

[[dialogue]]
speaker = "unk"
# ただし、後の調査で、誰しもすぐ水着フォームに変身できるわけではないと判明しており、何らかの条件――水着が戦闘服化するだけの<ruby=インシデント>要因</ruby>が必要だということが確認されている。
line = "ただし、後の調査で、誰しもすぐ水着フォームに変身できるわけではないと判明しており、何らかの条件――水着が戦闘服化するだけの<ruby>要因<rt>インシデント</rt></ruby>が必要だということが確認されている。"

[[dialogue]]
speaker = "アム"
# 「とにかく、そんな感じで水着フォームを手に入れたんですけど、新しく目覚めた能力が、マムに近い感じだったんです！」
line = "「とにかく、そんな感じで水着フォームを手に入れたんですけど、新しく目覚めた能力が、マムに近い感じだったんです！」"

[[dialogue]]
speaker = "アム"
# 「名付けて『重力操作』！　重力バリアーを張ったり、反重力を展開して盾を浮かせることで、乗って突撃したりとかできるんですよ～！」
line = "「名付けて『重力操作』！　重力バリアーを張ったり、反重力を展開して盾を浮かせることで、乗って突撃したりとかできるんですよ～！」"

[[dialogue]]
speaker = "マトイ"
# 「え？　そ、それってかなり強くない……？」
line = "「え？　そ、それってかなり強くない……？」"

[[dialogue]]
speaker = "マトイ"
# 「ただでさえ、『学園最硬』『歩く要塞』『盾の擬人化』とか言われてるアムちゃんが重力のバリアー張れるようになるって……突破できるイメージが湧かないんだけど……」
line = "「ただでさえ、『学園最硬』『歩く要塞』『盾の擬人化』とか言われてるアムちゃんが重力のバリアー張れるようになるって……突破できるイメージが湧かないんだけど……」"

[[dialogue]]
speaker = "アム"
# 「ま、マトイ先輩！　その辺のニックネームは子供っぽいんで、個人的にはあまり呼ばないでもらえると……！」
line = "「ま、マトイ先輩！　その辺のニックネームは子供っぽいんで、個人的にはあまり呼ばないでもらえると……！」"

[[dialogue]]
speaker = "マトイ"
# 「スク水は堂々と着るのに！？」
line = "「スク水は堂々と着るのに！？」"

[[dialogue]]
speaker = "アム"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "マトイ"
# 「い、いや、何でもない――コホン。とりあえず、重力操作が使えるようになったから、マムに指導をお願いしてたって感じかな……？」
line = "「い、いや、何でもない――コホン。とりあえず、重力操作が使えるようになったから、マムに指導をお願いしてたって感じかな……？」"

[[dialogue]]
speaker = "アム"
# 「はい、そういうことです！」
line = "「はい、そういうことです！」"

[[dialogue]]
speaker = "マハムート"
# 「全く……あなた達、この私に鍛えてもらおうだなんて、いい度胸してるわね」
line = "「全く……あなた達、この私に鍛えてもらおうだなんて、いい度胸してるわね」"

[[dialogue]]
speaker = "アム"
# 「いや～、それ程でも～♪　えへへ♪」
line = "「いや～、それ程でも～♪　えへへ♪」"

[[dialogue]]
speaker = "マハムート"
# 「まあ、仕方ないわ。弟子は取らないけど、寮長として寮生には、個人の戦闘力アップを常日頃求めているわけだし」
line = "「まあ、仕方ないわ。弟子は取らないけど、寮長として寮生には、個人の戦闘力アップを常日頃求めているわけだし」"

[[dialogue]]
speaker = "マトイ"
# 「え？　それって……」
line = "「え？　それって……」"

[[dialogue]]
speaker = "マハムート"
# 「こうなったら<b>２人まとめて</b>面倒をみてあげるわ。だから、畏怖を持って感謝なさい」
line = "「こうなったら<b>２人まとめて</b>面倒をみてあげるわ。だから、畏怖を持って感謝なさい」"

[[dialogue]]
speaker = "マハムート"
# 「強くなりたいんでしょ、マトイ？」
line = "「強くなりたいんでしょ、マトイ？」"

[[dialogue]]
speaker = "マトイ"
# 「マム……！」
line = "「マム……！」"

[[dialogue]]
speaker = "リップル"
# 「さすがマムでーす♪　ＢＩＧ優しい、みんなのお母さんみたいデスね！」
line = "「さすがマムでーす♪　ＢＩＧ優しい、みんなのお母さんみたいデスね！」"

[[dialogue]]
speaker = "マハムート"
# 「何を言っているのかしら、リップル？　私はただ、寮長としての責務を果たしているだけよ」
line = "「何を言っているのかしら、リップル？　私はただ、寮長としての責務を果たしているだけよ」"

[[dialogue]]
speaker = "マハムート"
# 「とにかく、訓練をするというなら、さっさと始めるから準備なさい。２人共、私に対しての返事は、当然わかってるわね？」
line = "「とにかく、訓練をするというなら、さっさと始めるから準備なさい。２人共、私に対しての返事は、当然わかってるわね？」"

[[dialogue]]
speaker = "２人"
# 「イエス・マム！」
line = "「イエス・マム！」"

[[dialogue]]
speaker = "マハムート"
# 「よろしい」
line = "「よろしい」"

[[dialogue]]
speaker = "unk"
# そうして、マムによる特訓指導が始まったのだが――
line = "そうして、マムによる特訓指導が始まったのだが――"

[[dialogue]]
speaker = "マハムート"
# 「それじゃあ、ビーチバレーを始めるわよ」
line = "「それじゃあ、ビーチバレーを始めるわよ」"

[[dialogue]]
speaker = "マトイ"
# 「何故にビーチバレー！？」
line = "「何故にビーチバレー！？」"

[[dialogue]]
speaker = "マハムート"
# 「それが私の<b>能力</b>だからよ」
line = "「それが私の<b>能力</b>だからよ」"

[[dialogue]]
speaker = "unk"
# じゃあ、マムの水着って……！
line = "じゃあ、マムの水着って……！"

[[dialogue]]
speaker = "マハムート"
# 「ふふ、会長。私を一体、誰だと思っているのかしら？」
line = "「ふふ、会長。私を一体、誰だと思っているのかしら？」"

[[dialogue]]
speaker = "マハムート"
# 「あなた達にできて、この私が水着フォームに変身できないはずがないでしょう？」
line = "「あなた達にできて、この私が水着フォームに変身できないはずがないでしょう？」"

[[dialogue]]
speaker = "unk"
# そう言って、マムがもう片方の手を広げると、そこにもビーチボールが出現する。
line = "そう言って、マムがもう片方の手を広げると、そこにもビーチボールが出現する。"

[[dialogue]]
speaker = "マトイ"
# 「って、いつの間にか私の周りに、ふわふわと宙に浮いてるビーチボールが沢山……！？」
line = "「って、いつの間にか私の周りに、ふわふわと宙に浮いてるビーチボールが沢山……！？」"

[[dialogue]]
speaker = "マハムート"
# 「私は水着フォームの武器として、ビーチボールを無数に召喚することができる。これを引力操作で操って、今から攻撃を仕掛けるわ」
line = "「私は水着フォームの武器として、ビーチボールを無数に召喚することができる。これを引力操作で操って、今から攻撃を仕掛けるわ」"

[[dialogue]]
speaker = "マハムート"
# 「ヒルディオーネから話を聞いたけど、最近出現している新種モンスターは群れで行動するとのこと」
line = "「ヒルディオーネから話を聞いたけど、最近出現している新種モンスターは群れで行動するとのこと」"

[[dialogue]]
speaker = "マハムート"
# 「これはそれを想定した防御訓練よ。マトイ、あなたはアムと一緒に、私の攻撃を全部防げるようになりなさい」
line = "「これはそれを想定した防御訓練よ。マトイ、あなたはアムと一緒に、私の攻撃を全部防げるようになりなさい」"

[[dialogue]]
speaker = "マハムート"
# 「じゃあまずは第１波、行くわよ！」
line = "「じゃあまずは第１波、行くわよ！」"

[[dialogue]]
speaker = "マハムート"
# 「グラビトンサーブ！」
line = "「グラビトンサーブ！」"

[[dialogue]]
speaker = "マトイ"
# 「ちょっ！？　マムのサーブ、凄まじく重い……！」
line = "「ちょっ！？　マムのサーブ、凄まじく重い……！」"

[[dialogue]]
speaker = "マハムート"
# 「最初の一撃に驚いている暇はないわよ、ほら！」
line = "「最初の一撃に驚いている暇はないわよ、ほら！」"

[[dialogue]]
speaker = "unk"
# マムが無数のビーチボールを操り、マトイの四方八方から、スパイクのごとき豪速球を絶え間なく放つ。
line = "マムが無数のビーチボールを操り、マトイの四方八方から、スパイクのごとき豪速球を絶え間なく放つ。"

[[dialogue]]
speaker = "マトイ"
# 「わわっ！？　一発一発がサーブと同等の威力って……！　いやいや、これを全部防ぎ切るのは無理～っ！」
line = "「わわっ！？　一発一発がサーブと同等の威力って……！　いやいや、これを全部防ぎ切るのは無理～っ！」"

[[dialogue]]
speaker = "unk"
# 数が多くて捌き切れず、マトイはかわそうとするが――
line = "数が多くて捌き切れず、マトイはかわそうとするが――"

[[dialogue]]
speaker = "アム"
# 「あっ！　マトイ先輩、気を付けて下さい！　そのビーチボールは避けると――」
line = "「あっ！　マトイ先輩、気を付けて下さい！　そのビーチボールは避けると――」"

[[dialogue]]
speaker = "マハムート"
# 「爆発するわよ」
line = "「爆発するわよ」"

[[dialogue]]
speaker = "マトイ"
# 「え」
line = "「え」"

[[dialogue]]
speaker = "マトイ"
# 「きゃあああぁぁぁーーーーーーっ！！？」
line = "「きゃあああぁぁぁーーーーーーっ！！？」"

[[dialogue]]
speaker = "unk"
# マトイが吹っ飛んだぁぁぁーーーっ！？
line = "マトイが吹っ飛んだぁぁぁーーーっ！？"

[[dialogue]]
speaker = "unk"
# こうして、初夏のビーチバレー特訓がスタートするのだった。
line = "こうして、初夏のビーチバレー特訓がスタートするのだった。"
