[[dialogue]]
speaker = "unk"
# 秋葉原でのコラプサーとの決戦から数日後。
line = "秋葉原でのコラプサーとの決戦から数日後。"

[[dialogue]]
speaker = "unk"
# 集まったコラプサーたちの前に、魔女イニシュが立つ。
line = "集まったコラプサーたちの前に、魔女イニシュが立つ。"

[[dialogue]]
speaker = "イニシュ"
# 「あなたたちコラプサーは我々ネビュラの管理下に置かれることになりました」
line = "「あなたたちコラプサーは我々ネビュラの管理下に置かれることになりました」"

[[dialogue]]
speaker = "イニシュ"
# 「私は魔女イニシュ。本日付であなたたちの上官となります。よろしくお願いします」
line = "「私は魔女イニシュ。本日付であなたたちの上官となります。よろしくお願いします」"

[[dialogue]]
speaker = "イニシュ"
# 「検査の結果、守護星であるブラックホールとのリンクは弱くなっており、あなたたちの戦闘能力は大幅に弱体化しています」
line = "「検査の結果、守護星であるブラックホールとのリンクは弱くなっており、あなたたちの戦闘能力は大幅に弱体化しています」"

[[dialogue]]
speaker = "イニシュ"
# 「とはいえ、敵が味方になったときには、レベル１からやり直しになるもの。レベリングには私も付き合いますので大丈夫です」
line = "「とはいえ、敵が味方になったときには、レベル１からやり直しになるもの。レベリングには私も付き合いますので大丈夫です」"

[[dialogue]]
speaker = "レイラ"
# 「はぁ……あの、よろしいでしょうか」
line = "「はぁ……あの、よろしいでしょうか」"

[[dialogue]]
speaker = "イニシュ"
# 「はい、どうぞ」
line = "「はい、どうぞ」"

[[dialogue]]
speaker = "レイラ"
# 「コラプサーの首領はあくまで私です。罪を犯した身で厚顔無恥なことを申しますが、コラプサーたちは私が指揮します」
line = "「コラプサーの首領はあくまで私です。罪を犯した身で厚顔無恥なことを申しますが、コラプサーたちは私が指揮します」"

[[dialogue]]
speaker = "レイラ"
# 「それがこの子たちを集めた私の責務であり、希望です。コラプサーへの命令は私を通していただけますか」
line = "「それがこの子たちを集めた私の責務であり、希望です。コラプサーへの命令は私を通していただけますか」"

[[dialogue]]
speaker = "イニシュ"
# 「いいでしょう。ですが、その責任はあなたが負うことになります。……いいですね？」
line = "「いいでしょう。ですが、その責任はあなたが負うことになります。……いいですね？」"

[[dialogue]]
speaker = "レイラ"
# 「はい！」
line = "「はい！」"

[[dialogue]]
speaker = "レイラ"
# （私は道を間違えた。だけどその過程で出会ったものを、全て否定したりはしない。仲間も過ちも背負って未来に進む）
line = "（私は道を間違えた。だけどその過程で出会ったものを、全て否定したりはしない。仲間も過ちも背負って未来に進む）"

[[dialogue]]
speaker = "レイラ"
# （これから、私たちの新しい戦いが始まる。今度こそ、世界をよりよくするため……コラプサーのみんなとともに！）
line = "（これから、私たちの新しい戦いが始まる。今度こそ、世界をよりよくするため……コラプサーのみんなとともに！）"

[[dialogue]]
speaker = "unk"
# マリオンは、赤ん坊になったイザベラを魔女の森に預けに来ていた。
line = "マリオンは、赤ん坊になったイザベラを魔女の森に預けに来ていた。"

[[dialogue]]
speaker = "マリオン"
# 「よしよし……泣かないで」
line = "「よしよし……泣かないで」"

[[dialogue]]
speaker = "unk"
# 揺らしてやると泣き止む。赤ん坊は本当に不思議だ。
line = "揺らしてやると泣き止む。赤ん坊は本当に不思議だ。"

[[dialogue]]
speaker = "マリオン"
# 「私にもこんな瞬間があったのでしょうね」
line = "「私にもこんな瞬間があったのでしょうね」"

[[dialogue]]
speaker = "unk"
# 腕の中にある小さな命。かつての友の面影がほんの少し。過ぎ去った時間は幾星霜。
line = "腕の中にある小さな命。かつての友の面影がほんの少し。過ぎ去った時間は幾星霜。"

[[dialogue]]
speaker = "マリオン"
# 「いつか、私も自分の子を持つことができるでしょうか……」
line = "「いつか、私も自分の子を持つことができるでしょうか……」"

[[dialogue]]
speaker = "unk"
# いつしか抱いた夢に思いを馳せる。自分によく似た、けれど決定的に違う存在。
line = "いつしか抱いた夢に思いを馳せる。自分によく似た、けれど決定的に違う存在。"

[[dialogue]]
speaker = "unk"
# もしそんな存在をこの世界に残せるとしたら、どんな気持ちだろう。
line = "もしそんな存在をこの世界に残せるとしたら、どんな気持ちだろう。"

[[dialogue]]
speaker = "unk"
# 嬉しいのだろうか。誇らしいのだろうか。想像は尽きない。
line = "嬉しいのだろうか。誇らしいのだろうか。想像は尽きない。"

[[dialogue]]
speaker = "マリオン"
# 「名前はどうしましょうか……なんて。ふふっ」
line = "「名前はどうしましょうか……なんて。ふふっ」"

[[dialogue]]
speaker = "unk"
# 放課後、コハルコは保健室に呼び出しを受けていた。
line = "放課後、コハルコは保健室に呼び出しを受けていた。"

[[dialogue]]
speaker = "コハルコ"
# 「失礼します……え？」
line = "「失礼します……え？」"

[[dialogue]]
speaker = "パテル"
# 「やっほー、直接会うのは初めてかな？　ま、あたし基本レアキャラだからね」
line = "「やっほー、直接会うのは初めてかな？　ま、あたし基本レアキャラだからね」"

[[dialogue]]
speaker = "パテル"
# 「みんなのぷりちー守護天使、パテルちゃんだよっ♪」
line = "「みんなのぷりちー守護天使、パテルちゃんだよっ♪」"

[[dialogue]]
speaker = "マグダレナ"
# 「こら、パテル。挨拶はきちんとなさい。コハルコさま、此度の事件、解決お疲れさまでした」
line = "「こら、パテル。挨拶はきちんとなさい。コハルコさま、此度の事件、解決お疲れさまでした」"

[[dialogue]]
speaker = "アルモタヘル"
# 「コハルコにはいつも世話になっているというのに、助力できなくてすまなかったな」
line = "「コハルコにはいつも世話になっているというのに、助力できなくてすまなかったな」"

[[dialogue]]
speaker = "コハルコ"
# 「いえ、守護天使のみなさんが気にされることでは……ところで、今日はどういったご用ですか？」
line = "「いえ、守護天使のみなさんが気にされることでは……ところで、今日はどういったご用ですか？」"

[[dialogue]]
speaker = "パテル"
# 「はいはーい、主にあたしー」
line = "「はいはーい、主にあたしー」"

[[dialogue]]
speaker = "パテル"
# 「あたしが『淘汰』を司る守護天使……つまり死神なのは知ってるよね？　その死神としては、死ぬはずの人が簡単に生き返ると困っちゃうんだよね」
line = "「あたしが『淘汰』を司る守護天使……つまり死神なのは知ってるよね？　その死神としては、死ぬはずの人が簡単に生き返ると困っちゃうんだよね」"

[[dialogue]]
speaker = "パテル"
# 「でもでも～、死ぬはずの命がぱぱっと蘇生しちゃった！　それも９人！」
line = "「でもでも～、死ぬはずの命がぱぱっと蘇生しちゃった！　それも９人！」"

[[dialogue]]
speaker = "unk"
# コラプサー８人と、イザベラ。
line = "コラプサー８人と、イザベラ。"

[[dialogue]]
speaker = "unk"
# イザベラは赤ん坊に戻ってしまったから完全な蘇生とは言えないけれど、死を覆し、生き長らえさせたことは間違いない。
line = "イザベラは赤ん坊に戻ってしまったから完全な蘇生とは言えないけれど、死を覆し、生き長らえさせたことは間違いない。"

[[dialogue]]
speaker = "パテル"
# 「というわけで、<ruby=レナトゥス>封理再誕</ruby>はこの世界の摂理を乱しうるものだからもう使わないでね！　今日はその警告に来たんだよ」
line = "「というわけで、<ruby>封理再誕<rt>レナトゥス</rt></ruby>はこの世界の摂理を乱しうるものだからもう使わないでね！　今日はその警告に来たんだよ」"

[[dialogue]]
speaker = "パテル"
# 「まぁ、残りの寿命……あと数十年くらいでコラプサーみたいなイレギュラーにはもう遭遇しないと思うけど、一応ね」
line = "「まぁ、残りの寿命……あと数十年くらいでコラプサーみたいなイレギュラーにはもう遭遇しないと思うけど、一応ね」"

[[dialogue]]
speaker = "コハルコ"
# 「え、数十年……？　寿命……？」
line = "「え、数十年……？　寿命……？」"

[[dialogue]]
speaker = "パテル"
# 「あれ、言ってなかったっけ？　実はあたし、生き物の寿命はだいたい分かるんだ」
line = "「あれ、言ってなかったっけ？　実はあたし、生き物の寿命はだいたい分かるんだ」"

[[dialogue]]
speaker = "パテル"
# 「はっきり言って、あなたの魂はボロボロ。不完全な光の魔女が、無茶な魔法の連続行使をしたからだね」
line = "「はっきり言って、あなたの魂はボロボロ。不完全な光の魔女が、無茶な魔法の連続行使をしたからだね」"

[[dialogue]]
speaker = "パテル"
# 「だから、あなたの寿命は残り数十年。まるで人間みたいだね♪」
line = "「だから、あなたの寿命は残り数十年。まるで人間みたいだね♪」"

[[dialogue]]
speaker = "コハルコ"
# 「──！」
line = "「──！」"

[[dialogue]]
speaker = "コハルコ"
# 「ぐすっ……」
line = "「ぐすっ……」"

[[dialogue]]
speaker = "unk"
# 事件は終息したものの、寿命の問題は残されていた。けれど、こんな形で解決するとは思ってもみなかった。
line = "事件は終息したものの、寿命の問題は残されていた。けれど、こんな形で解決するとは思ってもみなかった。"

[[dialogue]]
speaker = "マグダレナ"
# 「コハルコさまは私たちでも働くことができると導いてくださいました」
line = "「コハルコさまは私たちでも働くことができると導いてくださいました」"

[[dialogue]]
speaker = "アルモタヘル"
# 「確かにお前は普通の『命脈』からは外れた存在かもしれない。それでも、お前はここにこうして生きている」
line = "「確かにお前は普通の『命脈』からは外れた存在かもしれない。それでも、お前はここにこうして生きている」"

[[dialogue]]
speaker = "アルモタヘル"
# 「守護天使として、お前を贔屓してやることはできない。だが……」
line = "「守護天使として、お前を贔屓してやることはできない。だが……」"

[[dialogue]]
speaker = "マグダレナ"
# 「あなたに助けられた者として、あなたの幸せを願っていますよ」
line = "「あなたに助けられた者として、あなたの幸せを願っていますよ」"

[[dialogue]]
speaker = "コハルコ"
# 「私、独りで生きていかなくてもいいんだ……ぐすっ、よかった、よかったよぉ～」
line = "「私、独りで生きていかなくてもいいんだ……ぐすっ、よかった、よかったよぉ～」"

[[dialogue]]
speaker = "コハルコ"
# 「うわぁぁぁああ～～～～っ」
line = "「うわぁぁぁああ～～～～っ」"

[[dialogue]]
speaker = "unk"
# 心に重くのしかかっていた不安が消え、安堵の涙が溢れる。それはあたかも、再びの産声のようだった。
line = "心に重くのしかかっていた不安が消え、安堵の涙が溢れる。それはあたかも、再びの産声のようだった。"
