[[dialogue]]
speaker = "unk"
# レミカがライブを成功させた日から、１週間が経過しようとしていた。
line = "レミカがライブを成功させた日から、１週間が経過しようとしていた。"

[[dialogue]]
speaker = "メルエル"
# 「――会長くん……会長くん」
line = "「――会長くん……会長くん」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「朝だよ～、起きて♪」
line = "「朝だよ～、起きて♪」"

[[dialogue]]
speaker = "unk"
# 目を覚ますと、そこには小さな天使の姿があって。
line = "目を覚ますと、そこには小さな天使の姿があって。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「ふふっ……会長くん、おはよ<emoji=heart04>」
line = "「ふふっ……会長くん、おはよ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# って、メルエル！？　どうして俺の部屋に！？
line = "って、メルエル！？　どうして俺の部屋に！？"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「えへへ<emoji=heart04>　幼なじみっぽいことがしてみたくて……朝のお迎えに来ちゃった♪」
line = "「えへへ<emoji=heart04>　幼なじみっぽいことがしてみたくて……朝のお迎えに来ちゃった♪」"

[[dialogue]]
speaker = "unk"
# えぇ～っ！？　と、大きな声を上げてしまう俺なのだった。
line = "えぇ～っ！？　と、大きな声を上げてしまう俺なのだった。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「はい♪　会長くん、朝ご飯ができたよ。召し上がれ～♪」
line = "「はい♪　会長くん、朝ご飯ができたよ。召し上がれ～♪」"

[[dialogue]]
speaker = "unk"
# いただきます
line = "いただきます"

[[dialogue]]
speaker = "unk"
# 手を合わせて、小さなメルエルが作ってくれた朝ご飯を食べる。
line = "手を合わせて、小さなメルエルが作ってくれた朝ご飯を食べる。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「会長くん、どうかな？」
line = "「会長くん、どうかな？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「――すごく美味しい？　えへへ<emoji=heart04>　いつか会長くんに食べてもらいたいと思って、練習しておいてよかったぁ～♪」
line = "「――すごく美味しい？　えへへ<emoji=heart04>　いつか会長くんに食べてもらいたいと思って、練習しておいてよかったぁ～♪」"

[[dialogue]]
speaker = "リノ"
# 「ふふっ、クロトってば、こんなに可愛い女の子に朝ご飯を作ってもらえるなんて、幸せものね～。このこの～♪」
line = "「ふふっ、クロトってば、こんなに可愛い女の子に朝ご飯を作ってもらえるなんて、幸せものね～。このこの～♪」"

[[dialogue]]
speaker = "リノ"
# 「あれ？　でも確か、メルエルちゃんってクロトと同級生じゃなかったかしら？」
line = "「あれ？　でも確か、メルエルちゃんってクロトと同級生じゃなかったかしら？」"

[[dialogue]]
speaker = "unk"
# それにはちょっと事情があって……
line = "それにはちょっと事情があって……"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「リノさん、会長くんをまた朝迎えに来てもいいでしょうか？」
line = "「リノさん、会長くんをまた朝迎えに来てもいいでしょうか？」"

[[dialogue]]
speaker = "リノ"
# 「ええ。もちろんいいわよ♪　メルエルちゃんはいい子だから、お母さん、いつでも大歓迎～♪」
line = "「ええ。もちろんいいわよ♪　メルエルちゃんはいい子だから、お母さん、いつでも大歓迎～♪」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「ありがとうございます♪　会長くん、そういうわけで、明日もまた幼なじみとして起こしにくるね<emoji=heart04>」
line = "「ありがとうございます♪　会長くん、そういうわけで、明日もまた幼なじみとして起こしにくるね<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# それから俺は、小さなメルエルと並んで学園に登校した。
line = "それから俺は、小さなメルエルと並んで学園に登校した。"

[[dialogue]]
speaker = "メルエル"
# 「会長くん、おはよう♪　――って、えぇええぇええぇえ～～～っ！？」
line = "「会長くん、おはよう♪　――って、えぇええぇええぇえ～～～っ！？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「ふふっ、おはよう。大きな私♪」
line = "「ふふっ、おはよう。大きな私♪」"

[[dialogue]]
speaker = "unk"
# 上機嫌な様子で、小さなメルエルが大きなメルエルにひらひらと手を振ってみせる。
line = "上機嫌な様子で、小さなメルエルが大きなメルエルにひらひらと手を振ってみせる。"

[[dialogue]]
speaker = "メルエル"
# 「なっ、ななっ、なんで小さな私が、会長くんと一緒に……！？　まさか、会長くんの家まで迎えに行ってたの！？」
line = "「なっ、ななっ、なんで小さな私が、会長くんと一緒に……！？　まさか、会長くんの家まで迎えに行ってたの！？」"

[[dialogue]]
speaker = "unk"
# 実はそうなんだ……
line = "実はそうなんだ……"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「寝てる会長くんを起こしに行くって、すっごく幼なじみらしいでしょ？　ずっとしてみたいって思ってたから♪」
line = "「寝てる会長くんを起こしに行くって、すっごく幼なじみらしいでしょ？　ずっとしてみたいって思ってたから♪」"

[[dialogue]]
speaker = "メルエル"
# 「ど、どうして……？」
line = "「ど、どうして……？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「今まで色々遠慮してたけど、全力で挑戦するべきだって、思い直したから」
line = "「今まで色々遠慮してたけど、全力で挑戦するべきだって、思い直したから」"

[[dialogue]]
speaker = "メルエル"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「じゃあね、会長くん<emoji=heart04>　私、附属校のクラスに行くから、またお昼休みに♪」
line = "「じゃあね、会長くん<emoji=heart04>　私、附属校のクラスに行くから、またお昼休みに♪」"

[[dialogue]]
speaker = "unk"
# あ、ああ……
line = "あ、ああ……"

[[dialogue]]
speaker = "unk"
# 小さなメルエルは笑顔で手を振って、附属校の校舎へと向かっていく。
line = "小さなメルエルは笑顔で手を振って、附属校の校舎へと向かっていく。"

[[dialogue]]
speaker = "メルエル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "メルエル"
# 「あ……か、会長くん、私たちも行こっか？　あはは……」
line = "「あ……か、会長くん、私たちも行こっか？　あはは……」"

[[dialogue]]
speaker = "unk"
# なんとなく気まずい雰囲気が流れる中、俺たちは一緒に新星学園の方へと向かうのだった。
line = "なんとなく気まずい雰囲気が流れる中、俺たちは一緒に新星学園の方へと向かうのだった。"

[[dialogue]]
speaker = "unk"
# その日の昼休み。
line = "その日の昼休み。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「はい♪　会長くん、あ～ん♪」
line = "「はい♪　会長くん、あ～ん♪」"

[[dialogue]]
speaker = "unk"
# 隣に座った小さなメルエルが、周りに生徒たちがいる中でも昼食を口元に運んできてくれて、俺は気恥ずかしくなってしまう。
line = "隣に座った小さなメルエルが、周りに生徒たちがいる中でも昼食を口元に運んできてくれて、俺は気恥ずかしくなってしまう。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「――こうやって会長くんに食べさせてあげるのも、前からしてみたかったんだ♪　……ダメ、かな？」
line = "「――こうやって会長くんに食べさせてあげるのも、前からしてみたかったんだ♪　……ダメ、かな？」"

[[dialogue]]
speaker = "unk"
# 照れながら言うメルエルを見て、俺は運んでもらった唐揚げを１口で頬張る。
line = "照れながら言うメルエルを見て、俺は運んでもらった唐揚げを１口で頬張る。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「あっ……！　えへへ、嬉しい<emoji=heart04>　じゃあもっと……あ～ん♪」
line = "「あっ……！　えへへ、嬉しい<emoji=heart04>　じゃあもっと……あ～ん♪」"

[[dialogue]]
speaker = "unk"
# 唐揚げを丸ごと１口で食べている途中なので、ちょっと待ってとジェスチャーで伝えようとしたところで、後ろから声が聞こえてくる。
line = "唐揚げを丸ごと１口で食べている途中なので、ちょっと待ってとジェスチャーで伝えようとしたところで、後ろから声が聞こえてくる。"

[[dialogue]]
speaker = "メルエル"
# 「って、な、何をしてるのかな、私！？」
line = "「って、な、何をしてるのかな、私！？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「会長くんを誘って、一緒にお昼を食べてたんだよ♪」
line = "「会長くんを誘って、一緒にお昼を食べてたんだよ♪」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「朝にも言ってた通り、私、もう遠慮しないって決めたから」
line = "「朝にも言ってた通り、私、もう遠慮しないって決めたから」"

[[dialogue]]
speaker = "メルエル"
# 「ち、ちょっといいかな！？　小さい私と２人で話したいから、こっちに来て！」
line = "「ち、ちょっといいかな！？　小さい私と２人で話したいから、こっちに来て！」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「え？　ちょっと！　会長くんと過ごしてる途中なのに～……！」
line = "「え？　ちょっと！　会長くんと過ごしてる途中なのに～……！」"

[[dialogue]]
speaker = "メルエル"
# 「会長くん、ごめんね！　お昼ご飯はまた今度～！」
line = "「会長くん、ごめんね！　お昼ご飯はまた今度～！」"

[[dialogue]]
speaker = "unk"
# （メルエル、大丈夫だろうか……）
line = "（メルエル、大丈夫だろうか……）"

[[dialogue]]
speaker = "unk"
# 急いでカフェテリアから出て行く２人を見て、ちょっと心配になってしまうのだった。
line = "急いでカフェテリアから出て行く２人を見て、ちょっと心配になってしまうのだった。"

[[dialogue]]
speaker = "unk"
# メルエルは、もう１人の小さな自分の手を引っ張り、人の居ない空き教室へとやって来ていた。
line = "メルエルは、もう１人の小さな自分の手を引っ張り、人の居ない空き教室へとやって来ていた。"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「もう、こういう時だけ積極的に行動して……」
line = "「もう、こういう時だけ積極的に行動して……」"

[[dialogue]]
speaker = "メルエル"
# 「あ、あのさ！　なんで１人で勝手に行動し始めちゃったの！？」
line = "「あ、あのさ！　なんで１人で勝手に行動し始めちゃったの！？」"

[[dialogue]]
speaker = "メルエル"
# 「あんなにグイグイ行ったら、その、会長くんに迷惑……かけちゃうでしょ？」
line = "「あんなにグイグイ行ったら、その、会長くんに迷惑……かけちゃうでしょ？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「だから、今までみたいに遠慮しないとって？　そんな消極的だから、いつまで経っても私は――」
line = "「だから、今までみたいに遠慮しないとって？　そんな消極的だから、いつまで経っても私は――」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「会長くんに『好き』って気持ちも伝えられないし、恋人にもなれないんだよ」
line = "「会長くんに『好き』って気持ちも伝えられないし、恋人にもなれないんだよ」"

[[dialogue]]
speaker = "メルエル"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「会長くんが誰を好きになるかは、会長くんが決めることだよ」
line = "「会長くんが誰を好きになるかは、会長くんが決めることだよ」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「だけど、自分の気持ちを伝えることもなく、『好き』って気持ちを知られないまま、ずっと我慢してるなんて、私にはもう耐えられないよ」
line = "「だけど、自分の気持ちを伝えることもなく、『好き』って気持ちを知られないまま、ずっと我慢してるなんて、私にはもう耐えられないよ」"

[[dialogue]]
speaker = "メルエル"
# 「そ、それは……」
line = "「そ、それは……」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「消極的な気持ちが変わらないなら、私は元の１人に戻る気はないよ」
line = "「消極的な気持ちが変わらないなら、私は元の１人に戻る気はないよ」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「私、会長くんがレミカちゃんにアドバイスしたのを聞いてて、思ったんだ」
line = "「私、会長くんがレミカちゃんにアドバイスしたのを聞いてて、思ったんだ」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「今が、これまでの自分から変わるチャンスなんだって」
line = "「今が、これまでの自分から変わるチャンスなんだって」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「だから――このまま私が、会長くんに好きだって告白する！」
line = "「だから――このまま私が、会長くんに好きだって告白する！」"

[[dialogue]]
speaker = "メルエル"
# 「えっ！？」
line = "「えっ！？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「恋に全力になれない大きな私よりも、ちっちゃい私を選んでって、告白するもん」
line = "「恋に全力になれない大きな私よりも、ちっちゃい私を選んでって、告白するもん」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「それで私を選んでもらえたら……私は元の１人には戻らない」
line = "「それで私を選んでもらえたら……私は元の１人には戻らない」"

[[dialogue]]
speaker = "メルエル"
# 「なっ……で、でも、それじゃあ、ヴィーナスちゃんやレミカちゃんの体が小さくなったままで、戻れなくなっちゃうかもしれないんだよ！？」
line = "「なっ……で、でも、それじゃあ、ヴィーナスちゃんやレミカちゃんの体が小さくなったままで、戻れなくなっちゃうかもしれないんだよ！？」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「２人にはちゃんと謝るよ。でも、いざとなったらアニマ先輩に相談すれば、きっと何とかしてくれるはずだもん」
line = "「２人にはちゃんと謝るよ。でも、いざとなったらアニマ先輩に相談すれば、きっと何とかしてくれるはずだもん」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「私はたとえ周りに迷惑をかけてしまうことがあっても、会長くんへの好きって気持ちを譲りたくない……！」
line = "「私はたとえ周りに迷惑をかけてしまうことがあっても、会長くんへの好きって気持ちを譲りたくない……！」"

[[dialogue]]
speaker = "メルエル"
# 「っ……！」
line = "「っ……！」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「何も言えないよね？　だって、私とあなたは同じ。会長くんのことが、大好きなんだから」
line = "「何も言えないよね？　だって、私とあなたは同じ。会長くんのことが、大好きなんだから」"

[[dialogue]]
speaker = "メルエル（幼少）"
# 「それじゃあ、私は行くね」
line = "「それじゃあ、私は行くね」"

[[dialogue]]
speaker = "メルエル"
# 「あ……」
line = "「あ……」"

[[dialogue]]
speaker = "unk"
# 去って行くもう１人の自分にそれ以上何も声をかけられず、メルエルはその場に立ち尽くしてしまうのだった。
line = "去って行くもう１人の自分にそれ以上何も声をかけられず、メルエルはその場に立ち尽くしてしまうのだった。"
