[[dialogue]]
speaker = "unk"
# １週間が経って、オムニスが正気に戻った陽彩を連れて帰ってきた。
line = "１週間が経って、オムニスが正気に戻った陽彩を連れて帰ってきた。"

[[dialogue]]
speaker = "陽彩"
# 「ごめん……ぼくの好奇心のせいで、きみたちをとんでもない目に遭わせてしまった」
line = "「ごめん……ぼくの好奇心のせいで、きみたちをとんでもない目に遭わせてしまった」"

[[dialogue]]
speaker = "いろは"
# 「いいのいいの、気にしないで～」
line = "「いいのいいの、気にしないで～」"

[[dialogue]]
speaker = "花織"
# 「陽彩ちゃんがそういう性格だっていうことは、今に始まった話じゃないしね」
line = "「陽彩ちゃんがそういう性格だっていうことは、今に始まった話じゃないしね」"

[[dialogue]]
speaker = "ここあ"
# 「初めて悪魔に襲われた時も、巷の『アクマカクシ』の真相を解き明かそうとして巻き込まれたんだっけ～？」
line = "「初めて悪魔に襲われた時も、巷の『アクマカクシ』の真相を解き明かそうとして巻き込まれたんだっけ～？」"

[[dialogue]]
speaker = "いろは"
# 「でも無事元に戻ってくれて、本当によかったよ～！」
line = "「でも無事元に戻ってくれて、本当によかったよ～！」"

[[dialogue]]
speaker = "陽彩"
# 「うん。ありがとう……」
line = "「うん。ありがとう……」"

[[dialogue]]
speaker = "陽彩"
# 「そうだ、トレジアンナというのは、どの人だい？」
line = "「そうだ、トレジアンナというのは、どの人だい？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「はいは～い☆　私がその蒐集の魔法少女、トレジアンナですよ～♪」
line = "「はいは～い☆　私がその蒐集の魔法少女、トレジアンナですよ～♪」"

[[dialogue]]
speaker = "陽彩"
# 「これが悪魔のロストアイテムの力を移した魔石だ」
line = "「これが悪魔のロストアイテムの力を移した魔石だ」"

[[dialogue]]
speaker = "トレジアンナ"
# 「ロストアイテム自体はどうなりましたか？」
line = "「ロストアイテム自体はどうなりましたか？」"

[[dialogue]]
speaker = "陽彩"
# 「魔石がロストアイテムの力を吸い終わるのと同時に、悪魔と共にボロボロに崩れて消えた」
line = "「魔石がロストアイテムの力を吸い終わるのと同時に、悪魔と共にボロボロに崩れて消えた」"

[[dialogue]]
speaker = "陽彩"
# 「寄生されていたから感覚でわかるのだが、その力は完全にこの石に移された。今はこれが悪魔のロストアイテムだ」
line = "「寄生されていたから感覚でわかるのだが、その力は完全にこの石に移された。今はこれが悪魔のロストアイテムだ」"

[[dialogue]]
speaker = "トレジアンナ"
# 「ありがとうございます☆　ではそちらは私の方でお預かりして、完全に封印しておきますね～」
line = "「ありがとうございます☆　ではそちらは私の方でお預かりして、完全に封印しておきますね～」"

[[dialogue]]
speaker = "陽彩"
# 「ああ、頼んだ」
line = "「ああ、頼んだ」"

[[dialogue]]
speaker = "オムニス"
# 「後は元の世界に戻るだけだが……もう一度、俺たち全員を元の世界に送ることは出来るのか？」
line = "「後は元の世界に戻るだけだが……もう一度、俺たち全員を元の世界に送ることは出来るのか？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「ええ、もちろん大丈夫ですよ☆　お任せ下さい！」
line = "「ええ、もちろん大丈夫ですよ☆　お任せ下さい！」"

[[dialogue]]
speaker = "花織"
# 「ほっ……良かったぁ～」
line = "「ほっ……良かったぁ～」"

[[dialogue]]
speaker = "いろは"
# 「それじゃあもう帰らなきゃか～……せっかくみんなとも仲良くなれたのに～」
line = "「それじゃあもう帰らなきゃか～……せっかくみんなとも仲良くなれたのに～」"

[[dialogue]]
speaker = "ここあ"
# 「とはいえ、ここあたちが居なくなったままじゃ、他のみんなも心配してるだろうし……そろそろ帰らなきゃじゃない？」
line = "「とはいえ、ここあたちが居なくなったままじゃ、他のみんなも心配してるだろうし……そろそろ帰らなきゃじゃない？」"

[[dialogue]]
speaker = "いろは"
# 「うん、それもそうだねっ」
line = "「うん、それもそうだねっ」"

[[dialogue]]
speaker = "いろは"
# 「サチちゃん、プリちゃん、アンナちゃん、シズシズ、またね♪」
line = "「サチちゃん、プリちゃん、アンナちゃん、シズシズ、またね♪」"

[[dialogue]]
speaker = "花織"
# 「いろいろお世話になりました、ありがとう！」
line = "「いろいろお世話になりました、ありがとう！」"

[[dialogue]]
speaker = "サチ"
# 「いえ、こちらこそ楽しかったです。いい経験になりました」
line = "「いえ、こちらこそ楽しかったです。いい経験になりました」"

[[dialogue]]
speaker = "プリムラ"
# 「また気が向いたら、この世界に遊びに来るといいのじゃ」
line = "「また気が向いたら、この世界に遊びに来るといいのじゃ」"

[[dialogue]]
speaker = "ここあ"
# 「プリちん、ここあのこと、ちゃーんと覚えててよ？」
line = "「プリちん、ここあのこと、ちゃーんと覚えててよ？」"

[[dialogue]]
speaker = "プリムラ"
# 「ふん、そうじゃな……まあ、覚えといてやらんこともない」
line = "「ふん、そうじゃな……まあ、覚えといてやらんこともない」"

[[dialogue]]
speaker = "サチ"
# 「ふふっ、プリムラってば、お別れの時くらい素直になればいいのに」
line = "「ふふっ、プリムラってば、お別れの時くらい素直になればいいのに」"

[[dialogue]]
speaker = "プリムラ"
# 「う、うるさいのじゃ、サチ！」
line = "「う、うるさいのじゃ、サチ！」"

[[dialogue]]
speaker = "ここあ"
# 「ふふっ♪　このケンカが見られなくなるのも寂しいね～」
line = "「ふふっ♪　このケンカが見られなくなるのも寂しいね～」"

[[dialogue]]
speaker = "シズハ"
# 「いろはさんに教えてもらったポロキュアの主題歌、大好きになっちゃった♪　また一緒に歌いたいから、絶対に遊びに来てね！」
line = "「いろはさんに教えてもらったポロキュアの主題歌、大好きになっちゃった♪　また一緒に歌いたいから、絶対に遊びに来てね！」"

[[dialogue]]
speaker = "いろは"
# 「うん、約束だよ♪」
line = "「うん、約束だよ♪」"

[[dialogue]]
speaker = "シズハ"
# 「花織さんの熱唱もすごかったよ！　また聞かせて♪」
line = "「花織さんの熱唱もすごかったよ！　また聞かせて♪」"

[[dialogue]]
speaker = "花織"
# 「あはは、ありがとう。その時に備えてもっと練習しとくね」
line = "「あはは、ありがとう。その時に備えてもっと練習しとくね」"

[[dialogue]]
speaker = "トレジアンナ"
# 「――名残惜しいとは思いますが、そろそろ始めましょうか」
line = "「――名残惜しいとは思いますが、そろそろ始めましょうか」"

[[dialogue]]
speaker = "オムニス"
# 「そうだな。トレジアンナさん、お願いします」
line = "「そうだな。トレジアンナさん、お願いします」"

[[dialogue]]
speaker = "トレジアンナ"
# 「……よし。わっかりました～！」
line = "「……よし。わっかりました～！」"

[[dialogue]]
speaker = "unk"
# いろは、花織、ここあ、陽彩、そしてオムニスが一ヶ所に固まる。
line = "いろは、花織、ここあ、陽彩、そしてオムニスが一ヶ所に固まる。"

[[dialogue]]
speaker = "unk"
# トレジアンナはその前に立ち、『バカアワビ』に魔力を込め始めた。
line = "トレジアンナはその前に立ち、『バカアワビ』に魔力を込め始めた。"

[[dialogue]]
speaker = "いろは"
# 「それじゃあ、またね！！！」
line = "「それじゃあ、またね！！！」"

[[dialogue]]
speaker = "unk"
# 周囲の空気に歪みが生まれる。
line = "周囲の空気に歪みが生まれる。"

[[dialogue]]
speaker = "unk"
# その中へと、異世界から来た魔法少女たちは姿を消していった。
line = "その中へと、異世界から来た魔法少女たちは姿を消していった。"

[[dialogue]]
speaker = "サチ"
# 「……行っちゃいました」
line = "「……行っちゃいました」"

[[dialogue]]
speaker = "プリムラ"
# 「そうじゃな……」
line = "「そうじゃな……」"

[[dialogue]]
speaker = "シズハ"
# 「あ……トレジアンナさん、バカアワビが……！」
line = "「あ……トレジアンナさん、バカアワビが……！」"

[[dialogue]]
speaker = "トレジアンナ"
# 「……消滅してしまいましたか。これでバカアワビを使っての世界を転移する方法は失われてしまいましたね……」
line = "「……消滅してしまいましたか。これでバカアワビを使っての世界を転移する方法は失われてしまいましたね……」"

[[dialogue]]
speaker = "サチ"
# 「バカアワビについては調べていたんですよね？　トレジアンナさんでも詳しい原理はわからなかったんですか？」
line = "「バカアワビについては調べていたんですよね？　トレジアンナさんでも詳しい原理はわからなかったんですか？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「ええ。もうしばらく、調べる時間があればよかったのですが……」
line = "「ええ。もうしばらく、調べる時間があればよかったのですが……」"

[[dialogue]]
speaker = "トレジアンナ"
# 「やはり世界を転移するなんていうのは、そう簡単に出来ることではないということみたいですね」
line = "「やはり世界を転移するなんていうのは、そう簡単に出来ることではないということみたいですね」"

[[dialogue]]
speaker = "シズハ"
# 「それじゃあ、いろはさんたちには、もう会えないのかな……？」
line = "「それじゃあ、いろはさんたちには、もう会えないのかな……？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「いえ、それはどうでしょう？　悪魔が現れる時、バカアワビが生まれると言っていましたからね～」
line = "「いえ、それはどうでしょう？　悪魔が現れる時、バカアワビが生まれると言っていましたからね～」"

[[dialogue]]
speaker = "トレジアンナ"
# 「もしかしたら、それを使ってまた会いに来てくれるかもしれませんよ♪　それにオールスターズ春映画というのは、定期的に次があるものなので♪」
line = "「もしかしたら、それを使ってまた会いに来てくれるかもしれませんよ♪　それにオールスターズ春映画というのは、定期的に次があるものなので♪」"

[[dialogue]]
speaker = "サチ"
# 「だったらその時までに、もっと強くならなくちゃですね……魔法少女として、それぞれの世界を守れるように」
line = "「だったらその時までに、もっと強くならなくちゃですね……魔法少女として、それぞれの世界を守れるように」"

[[dialogue]]
speaker = "プリムラ"
# 「ふっ、そうじゃな！　次あった時は、我の新フォームを見せてやるのじゃ！」
line = "「ふっ、そうじゃな！　次あった時は、我の新フォームを見せてやるのじゃ！」"

[[dialogue]]
speaker = "トレジアンナ"
# 「――さて、それではいろはさんたちを無事に見送ることもできましたし……」
line = "「――さて、それではいろはさんたちを無事に見送ることもできましたし……」"

[[dialogue]]
speaker = "トレジアンナ"
# 「今回も無事にロストアイテムを回収できたということで、打ち上げ会といきましょうか☆」
line = "「今回も無事にロストアイテムを回収できたということで、打ち上げ会といきましょうか☆」"

[[dialogue]]
speaker = "３人"
# 「さんせーいっ♪」
line = "「さんせーいっ♪」"

[[dialogue]]
speaker = "unk"
# 平和を取り戻した夕暮れの空の下──魔法少女たちの明るい声が響き渡る。
line = "平和を取り戻した夕暮れの空の下──魔法少女たちの明るい声が響き渡る。"

[[dialogue]]
speaker = "unk"
# こうして、悪魔のロストアイテムを巡る事件は幕を閉じたのだった。
line = "こうして、悪魔のロストアイテムを巡る事件は幕を閉じたのだった。"
