[[dialogue]]
speaker = "エルデリーゼ"
# 「お掃除、終わりましたわ！」
line = "「お掃除、終わりましたわ！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「お洗濯完了です♪」
line = "「お洗濯完了です♪」"

[[dialogue]]
speaker = "ミウ"
# 「次は何をすればいいですか？」
line = "「次は何をすればいいですか？」"

[[dialogue]]
speaker = "unk"
# ヒマワリとミウは九浄家の見習い使用人として、そして時々エルデリーゼも飛び入り参加しながら、日々の仕事をこなしていた。
line = "ヒマワリとミウは九浄家の見習い使用人として、そして時々エルデリーゼも飛び入り参加しながら、日々の仕事をこなしていた。"

[[dialogue]]
speaker = "unk"
# そして──
line = "そして──"

[[dialogue]]
speaker = "ヒマワリ"
# 「これでお屋敷の構造はだいたい掴めたかなー」
line = "「これでお屋敷の構造はだいたい掴めたかなー」"

[[dialogue]]
speaker = "ミウ"
# 「踏み入れてない部屋は、ほとんど残ってないね。逆に言えば、その踏み入れてない場所に秘密が隠されてるのかも」
line = "「踏み入れてない部屋は、ほとんど残ってないね。逆に言えば、その踏み入れてない場所に秘密が隠されてるのかも」"

[[dialogue]]
speaker = "unk"
# 裏では屋敷の調査を着々と進めていた。
line = "裏では屋敷の調査を着々と進めていた。"

[[dialogue]]
speaker = "美鶴"
# 「お、チーパオちゃんたちー。なんかうちに聞きたいことがあるらしいじゃないすか」
line = "「お、チーパオちゃんたちー。なんかうちに聞きたいことがあるらしいじゃないすか」"

[[dialogue]]
speaker = "ヒマワリ"
# 「美鶴さん！　そうなんですよー、エルゼ様のメイド服についてなんですけど」
line = "「美鶴さん！　そうなんですよー、エルゼ様のメイド服についてなんですけど」"

[[dialogue]]
speaker = "美鶴"
# 「エルデリーゼ様のメイド服すか」
line = "「エルデリーゼ様のメイド服すか」"

[[dialogue]]
speaker = "ミウ"
# 「とても素敵なデザインですけど、他の方のとは趣きが違うじゃないですか。どういった心境の変化なのか……」
line = "「とても素敵なデザインですけど、他の方のとは趣きが違うじゃないですか。どういった心境の変化なのか……」"

[[dialogue]]
speaker = "ヒマワリ"
# 「それとも、他のメイド服にはない、とてつもない能力なんかが隠されてるのかなーなんて思いまして」
line = "「それとも、他のメイド服にはない、とてつもない能力なんかが隠されてるのかなーなんて思いまして」"

[[dialogue]]
speaker = "美鶴"
# 「はは、そんなのないない」
line = "「はは、そんなのないない」"

[[dialogue]]
speaker = "ヒマワリ"
# 「ないの！？」
line = "「ないの！？」"

[[dialogue]]
speaker = "美鶴"
# 「アレを作ったのは当主様の気まぐれすよ。たまには和風メイドじゃなくて、洋風メイドの衣装をデザインしたいって欲望が弾けたからみたいで」
line = "「アレを作ったのは当主様の気まぐれすよ。たまには和風メイドじゃなくて、洋風メイドの衣装をデザインしたいって欲望が弾けたからみたいで」"

[[dialogue]]
speaker = "ミウ"
# 「え……？　それだけ、ですか？」
line = "「え……？　それだけ、ですか？」"

[[dialogue]]
speaker = "美鶴"
# 「それ以外に何かあるなら、うちが知りたいくらいすね。当主様の気まぐれには、うちも手を焼いてるんでー」
line = "「それ以外に何かあるなら、うちが知りたいくらいすね。当主様の気まぐれには、うちも手を焼いてるんでー」"

[[dialogue]]
speaker = "ヒマワリ"
# 「そうですか。お話、有難うございました」
line = "「そうですか。お話、有難うございました」"

[[dialogue]]
speaker = "美鶴"
# 「ん？　もういいの？　ほんじゃね、チーパオちゃんたち、がんばれ～」
line = "「ん？　もういいの？　ほんじゃね、チーパオちゃんたち、がんばれ～」"

[[dialogue]]
speaker = "ミウ"
# 「やっぱりメイド型人工戦闘服に、危険な新技術が用いられているなんてことはないみたいだね」
line = "「やっぱりメイド型人工戦闘服に、危険な新技術が用いられているなんてことはないみたいだね」"

[[dialogue]]
speaker = "ヒマワリ"
# 「そんなー！　今まで無駄骨を折っちゃったってことー！？」
line = "「そんなー！　今まで無駄骨を折っちゃったってことー！？」"

[[dialogue]]
speaker = "ミウ"
# 「どこかで情報が食い違っている……？　ううん、そもそも──」
line = "「どこかで情報が食い違っている……？　ううん、そもそも──」"

[[dialogue]]
speaker = "ヒマワリ"
# 「決定的な情報を得るには、やっぱり本丸に切り込まないとかな？」
line = "「決定的な情報を得るには、やっぱり本丸に切り込まないとかな？」"

[[dialogue]]
speaker = "ミウ"
# 「踏み入れてない部屋──ヘレナさんの私室。衣装のデザインもそこで行っているみたいだし、この屋敷に人工戦闘服の情報があるとしたら、そこしかない」
line = "「踏み入れてない部屋──ヘレナさんの私室。衣装のデザインもそこで行っているみたいだし、この屋敷に人工戦闘服の情報があるとしたら、そこしかない」"

[[dialogue]]
speaker = "ヒマワリ"
# 「そんな場所、潜入難易度ＭＡＸだよね。セキュリティもちゃんと敷かれてるだろうなー」
line = "「そんな場所、潜入難易度ＭＡＸだよね。セキュリティもちゃんと敷かれてるだろうなー」"

[[dialogue]]
speaker = "ミウ"
# 「一応、部屋へ侵入する最も安全な経路は確認済み。セキュリティを無力化するプログラムも用意してるよ」
line = "「一応、部屋へ侵入する最も安全な経路は確認済み。セキュリティを無力化するプログラムも用意してるよ」"

[[dialogue]]
speaker = "ヒマワリ"
# 「わぉ、完璧じゃん。さっすが、ミウ」
line = "「わぉ、完璧じゃん。さっすが、ミウ」"

[[dialogue]]
speaker = "ミウ"
# （何か見落としがあるんじゃないかって気がするし、嫌な予感もするけど……任務の期日まで猶予はないし……）
line = "（何か見落としがあるんじゃないかって気がするし、嫌な予感もするけど……任務の期日まで猶予はないし……）"

[[dialogue]]
speaker = "ミウ"
# 「決行は今晩にしよう。頑張ろうね、ヒマワリちゃん」
line = "「決行は今晩にしよう。頑張ろうね、ヒマワリちゃん」"

[[dialogue]]
speaker = "unk"
# ２人は意を決し、ヘレナの私室への侵入を敢行する。
line = "２人は意を決し、ヘレナの私室への侵入を敢行する。"

[[dialogue]]
speaker = "unk"
# その夜──
line = "その夜──"

[[dialogue]]
speaker = "ヒマワリ"
# 「抜き足、差し足……あった！　ミウ、これじゃない！？」
line = "「抜き足、差し足……あった！　ミウ、これじゃない！？」"

[[dialogue]]
speaker = "ミウ"
# 「データコピー開始──よし、完了っと。これさえ手に入れば、もうここに用はないね」
line = "「データコピー開始──よし、完了っと。これさえ手に入れば、もうここに用はないね」"

[[dialogue]]
speaker = "ヒマワリ"
# 「九浄家の使用人生活、結構楽しかったのに。これでおしまいなのも、ちょっと残念だね」
line = "「九浄家の使用人生活、結構楽しかったのに。これでおしまいなのも、ちょっと残念だね」"

[[dialogue]]
speaker = "ミウ"
# 「仕方ないよ。でも、まだ油断は禁物だよ。ここから無事に脱出するまでが──」
line = "「仕方ないよ。でも、まだ油断は禁物だよ。ここから無事に脱出するまでが──」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「そうは問屋が卸しませんですわ」
line = "「そうは問屋が卸しませんですわ」"

[[dialogue]]
speaker = "ヒマワリ"
# 「この声は！！？」
line = "「この声は！！？」"

[[dialogue]]
speaker = "ミウ"
# 「エルデリーゼ先輩！！？　こんな夜中に、どうして！？」
line = "「エルデリーゼ先輩！！？　こんな夜中に、どうして！？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ヘレナ様からご招待いただいて、今夜はお屋敷にお泊りしておりましたの」
line = "「ヘレナ様からご招待いただいて、今夜はお屋敷にお泊りしておりましたの」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「そうしたらあなたたちがこの部屋に忍びこむところを見つけましたわ」
line = "「そうしたらあなたたちがこの部屋に忍びこむところを見つけましたわ」"

[[dialogue]]
speaker = "ヒマワリ"
# 「う……タイミング悪かったかぁ……」
line = "「う……タイミング悪かったかぁ……」"

[[dialogue]]
speaker = "ミウ"
# 「ううん、違うかも……これは……」
line = "「ううん、違うかも……これは……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「こそこそといったい何を……まさか今までここで働いていたのは、何かを目論んでいらっしゃったの？」
line = "「こそこそといったい何を……まさか今までここで働いていたのは、何かを目論んでいらっしゃったの？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「あなたたちとはお友達になれると思っていましたのに……！」
line = "「あなたたちとはお友達になれると思っていましたのに……！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「うぅ、ごめんね、エルゼ先輩」
line = "「うぅ、ごめんね、エルゼ先輩」"

[[dialogue]]
speaker = "ミウ"
# 「戦略的撤退だよ、ヒマワリちゃん！」
line = "「戦略的撤退だよ、ヒマワリちゃん！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「あら……そちらに逃げても無駄ですのに」
line = "「あら……そちらに逃げても無駄ですのに」"

[[dialogue]]
speaker = "ヒマワリ"
# 「よし、ここまで逃げれば！　エルゼ先輩を振り切って──」
line = "「よし、ここまで逃げれば！　エルゼ先輩を振り切って──」"

[[dialogue]]
speaker = "蘭美"
# 「追いかけっこなら私も混ぜて欲しいわね」
line = "「追いかけっこなら私も混ぜて欲しいわね」"

[[dialogue]]
speaker = "ミウ"
# 「蘭美……さんっ……！？」
line = "「蘭美……さんっ……！？」"

[[dialogue]]
speaker = "閃"
# 「こんな夜更けにどちらにお出かけです？　子供はふかふかのベッドで夢を見る時間ですよ？」
line = "「こんな夜更けにどちらにお出かけです？　子供はふかふかのベッドで夢を見る時間ですよ？」"

[[dialogue]]
speaker = "せつな"
# 「夜遊びが楽しいのはわかるでござるが……危険な火遊びは感心しないでござるな」
line = "「夜遊びが楽しいのはわかるでござるが……危険な火遊びは感心しないでござるな」"

[[dialogue]]
speaker = "ヒマワリ"
# 「わ、わぁ……閃さんにせつなさん、美鶴さんにヨミさんも……メイド隊の皆さん、お揃いで……」
line = "「わ、わぁ……閃さんにせつなさん、美鶴さんにヨミさんも……メイド隊の皆さん、お揃いで……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「お待ちになりなさいですわー！」
line = "「お待ちになりなさいですわー！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「前門のメイド隊！　後門からは槍を持ったメイドさんだよー！」
line = "「前門のメイド隊！　後門からは槍を持ったメイドさんだよー！」"

[[dialogue]]
speaker = "ミウ"
# 「まさに四面楚歌だね……この窮地を脱する切り札なんて、そんなの──」
line = "「まさに四面楚歌だね……この窮地を脱する切り札なんて、そんなの──」"

[[dialogue]]
speaker = "セナリィ（覚醒）"
# 「ジョーカーを切るしかありませんわねぇ！」
line = "「ジョーカーを切るしかありませんわねぇ！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「セナリィ社長っ！？」
line = "「セナリィ社長っ！？」"

[[dialogue]]
speaker = "ミウ"
# 「ど、どうして、ここに──」
line = "「ど、どうして、ここに──」"

[[dialogue]]
speaker = "セナリィ（覚醒）"
# 「説明は後！　とにかく今は、脱兎の如く撤退ですわーっ！」
line = "「説明は後！　とにかく今は、脱兎の如く撤退ですわーっ！」"
