[[dialogue]]
speaker = "聖沙"
# 「う～ん。どうやらこの魔族たち、福引きのガラガラを回したかっただけみたいですね」
line = "「う～ん。どうやらこの魔族たち、福引きのガラガラを回したかっただけみたいですね」"

[[dialogue]]
speaker = "雑魚魔族"
# 「イー……」
line = "「イー……」"

[[dialogue]]
speaker = "リア"
# 「だとしても他人の福引き券を使おうとするのはメっだよ。どうしてもって言うなら──はい、このガラガラをあげるから」
line = "「だとしても他人の福引き券を使おうとするのはメっだよ。どうしてもって言うなら──はい、このガラガラをあげるから」"

[[dialogue]]
speaker = "リア"
# 「その代わり、もうこんな悪さしないでね？　約束だよ？」
line = "「その代わり、もうこんな悪さしないでね？　約束だよ？」"

[[dialogue]]
speaker = "雑魚魔族"
# 「イー！」
line = "「イー！」"

[[dialogue]]
speaker = "聖沙"
# 「良かったんですか、先輩？　魔族を逃がしちゃったりして」
line = "「良かったんですか、先輩？　魔族を逃がしちゃったりして」"

[[dialogue]]
speaker = "リア"
# 「ふふ、きっとシン君ならこうしたと思うから」
line = "「ふふ、きっとシン君ならこうしたと思うから」"

[[dialogue]]
speaker = "リア"
# 「それより今は──」
line = "「それより今は──」"

[[dialogue]]
speaker = "リア"
# 「手伝ってくれてありがとう、ございます。それで、えっと……あなたたちは？」
line = "「手伝ってくれてありがとう、ございます。それで、えっと……あなたたちは？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「自己紹介が遅れたわね。私は九浄ヴィーナス。流星市国、新星学園所属の星騎士よ。こっちの男は星徒会長の──」
line = "「自己紹介が遅れたわね。私は九浄ヴィーナス。流星市国、新星学園所属の星騎士よ。こっちの男は星徒会長の──」"

[[dialogue]]
speaker = "unk"
# 緋宮クロトです
line = "緋宮クロトです"

[[dialogue]]
speaker = "聖沙"
# 「流星市国……？　新星学園……？　星騎士……？　それに九浄って……」
line = "「流星市国……？　新星学園……？　星騎士……？　それに九浄って……」"

[[dialogue]]
speaker = "フィオナ"
# 「どうも聞きなじみのないご様子です。やはりここは流星市国の外みたいですね」
line = "「どうも聞きなじみのないご様子です。やはりここは流星市国の外みたいですね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうね。でも星騎士なら流星市国の名前くらいは知っていてもよさそうなものだけど」
line = "「そうね。でも星騎士なら流星市国の名前くらいは知っていてもよさそうなものだけど」"

[[dialogue]]
speaker = "リア"
# 「ええと……それで皆さんはその新星学園の生徒さんなのかな？」
line = "「ええと……それで皆さんはその新星学園の生徒さんなのかな？」"

[[dialogue]]
speaker = "フィオナ"
# 「あ、いえ。私は流星学園に通っていまして──星見フィオナです。流星学園で星徒会長を務めさせていただいています」
line = "「あ、いえ。私は流星学園に通っていまして──星見フィオナです。流星学園で星徒会長を務めさせていただいています」"

[[dialogue]]
speaker = "聖沙"
# 「流星学園の生徒会長ぉ！？」
line = "「流星学園の生徒会長ぉ！？」"

[[dialogue]]
speaker = "リア"
# 「うーん……。聞けば聞くほど頭がこんがらがっちゃうね……」
line = "「うーん……。聞けば聞くほど頭がこんがらがっちゃうね……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「どういうこと？」
line = "「どういうこと？」"

[[dialogue]]
speaker = "リア"
# 「落ち着いて聞いてね？　ここは流星学園なの。そして、私と聖沙ちゃんは流星学園の<b>生徒会</b>メンバーなんだ」
line = "「落ち着いて聞いてね？　ここは流星学園なの。そして、私と聖沙ちゃんは流星学園の<b>生徒会</b>メンバーなんだ」"

[[dialogue]]
speaker = "フィオナ"
# 「ここが流星学園、ですか？　それにあなた方が生徒会の一員……？」
line = "「ここが流星学園、ですか？　それにあなた方が生徒会の一員……？」"

[[dialogue]]
speaker = "聖沙"
# 「ええ。私は聖沙・Ｂ・クリステレス。流星学園生徒会の副会長よ」
line = "「ええ。私は聖沙・Ｂ・クリステレス。流星学園生徒会の副会長よ」"

[[dialogue]]
speaker = "リア"
# 「私は九浄リア。今はもう肩書きは譲っちゃったけど、これでも元生徒会長だよ」
line = "「私は九浄リア。今はもう肩書きは譲っちゃったけど、これでも元生徒会長だよ」"

[[dialogue]]
speaker = "フィオナ"
# 「す、すみません。理解が追いつかなくて……。実際に私は流星学園の星徒会長ですし……」
line = "「す、すみません。理解が追いつかなくて……。実際に私は流星学園の星徒会長ですし……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それに今、九浄って……」
line = "「それに今、九浄って……」"

[[dialogue]]
speaker = "リア"
# 「色々と疑問があると思うけど、その前に私からも質問させてもらっていいかな？」
line = "「色々と疑問があると思うけど、その前に私からも質問させてもらっていいかな？」"

[[dialogue]]
speaker = "リア"
# 「さっきの戦い……それにその姿。あなたたちは一体どこでその力を手に入れたの？」
line = "「さっきの戦い……それにその姿。あなたたちは一体どこでその力を手に入れたの？」"

[[dialogue]]
speaker = "リア"
# 「あの力はクルセイダースである私たちにしか使えないはず。ううん、正確には私たちと力の出所が違うみたいだけど」
line = "「あの力はクルセイダースである私たちにしか使えないはず。ううん、正確には私たちと力の出所が違うみたいだけど」"

[[dialogue]]
speaker = "unk"
# クルセイダース？
line = "クルセイダース？"

[[dialogue]]
speaker = "ヴィーナス"
# 「ま、待って。クルセイダースって言ったら！」
line = "「ま、待って。クルセイダースって言ったら！」"

[[dialogue]]
speaker = "フィオナ"
# 「３０００年前にリクリエを退けたという英雄の……！」
line = "「３０００年前にリクリエを退けたという英雄の……！」"

[[dialogue]]
speaker = "聖沙"
# 「大昔の、英雄？　先輩……私、頭が痛くなってきました。この子たち、魔族の精神攻撃でも受けているんじゃ？」
line = "「大昔の、英雄？　先輩……私、頭が痛くなってきました。この子たち、魔族の精神攻撃でも受けているんじゃ？」"

[[dialogue]]
speaker = "リア"
# 「うーん……。私たちの認識とは色々とズレていることは確かだね。まずはその辺りを擦り合わせることが大切かも」
line = "「うーん……。私たちの認識とは色々とズレていることは確かだね。まずはその辺りを擦り合わせることが大切かも」"

[[dialogue]]
speaker = "リア"
# 「よく聞いてね？　あなたたちがいるこの町は流星町。そして私たちは流星学園、生徒会」
line = "「よく聞いてね？　あなたたちがいるこの町は流星町。そして私たちは流星学園、生徒会」"

[[dialogue]]
speaker = "リア"
# 「リ・クリエを阻止するためにこの力を使って、日夜魔族と戦っている──流星クルセイダース、だよ」
line = "「リ・クリエを阻止するためにこの力を使って、日夜魔族と戦っている──流星クルセイダース、だよ」"

[[dialogue]]
speaker = "フィオナ"
# 「あの伝説のクルセイダースが目の前にいらっしゃるなんて、にわかには信じられません……」
line = "「あの伝説のクルセイダースが目の前にいらっしゃるなんて、にわかには信じられません……」"

[[dialogue]]
speaker = "フィオナ"
# 「しかしクルセイダースが魔族と戦っていたという伝説は聞いたことがありません」
line = "「しかしクルセイダースが魔族と戦っていたという伝説は聞いたことがありません」"

[[dialogue]]
speaker = "フィオナ"
# 「それに流星町という地名も。過去の世界というわけではなさそうです」
line = "「それに流星町という地名も。過去の世界というわけではなさそうです」"

[[dialogue]]
speaker = "聖沙"
# 「謎は深まるばかりね。事情を聞く限り、境界の乱れっていうものに巻き込まれたのが関係していそうだけど」
line = "「謎は深まるばかりね。事情を聞く限り、境界の乱れっていうものに巻き込まれたのが関係していそうだけど」"

[[dialogue]]
speaker = "リア"
# 「ところどころ共通点はあるもんね。ヴィーナスちゃんたちもフィーニスの塔については知っているみたいだし」
line = "「ところどころ共通点はあるもんね。ヴィーナスちゃんたちもフィーニスの塔については知っているみたいだし」"

[[dialogue]]
speaker = "リア"
# 「あ、そうだ。お姉ちゃん──理事長の九浄ヘレナなら何か知ってるかも」
line = "「あ、そうだ。お姉ちゃん──理事長の九浄ヘレナなら何か知ってるかも」"

[[dialogue]]
speaker = "ヴィーナス"
# 「九浄──ヘレナ！？」
line = "「九浄──ヘレナ！？」"

[[dialogue]]
speaker = "リア"
# 「あれ？　お姉ちゃんのことは知ってるの？」
line = "「あれ？　お姉ちゃんのことは知ってるの？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「知ってるも何も、私のお義母さまよ。私、九浄家の養子だから。確かＤＩＳＣに写真が……」
line = "「知ってるも何も、私のお義母さまよ。私、九浄家の養子だから。確かＤＩＳＣに写真が……」"

[[dialogue]]
speaker = "リア"
# 「ええっと…… この人が九浄ヘレナ、さん？ お姉ちゃんとは似ても似つかないような…… 」
line = "「ええっと…… この人が九浄ヘレナ、さん？ お姉ちゃんとは似ても似つかないような…… 」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうは言っても、これが私の知る九浄ヘレナよ！」
line = "「そうは言っても、これが私の知る九浄ヘレナよ！」"

[[dialogue]]
speaker = "リア"
# 「同姓同名の別人…… ？ でも、お姉ちゃんがそれを知ったら──」
line = "「同姓同名の別人…… ？ でも、お姉ちゃんがそれを知ったら──」"

[[dialogue]]
speaker = "リア"
# 「『ドッペルゲンガーは見つけ次第、始末する。でなければ次は俺が死んでしまうからな』とか言いそうだしなぁ…… 」
line = "「『ドッペルゲンガーは見つけ次第、始末する。でなければ次は俺が死んでしまうからな』とか言いそうだしなぁ…… 」"

[[dialogue]]
speaker = "リア"
# 「そもそも、流星町で九浄家のヘレナを名乗るなんて、正気の沙汰じゃないよ」
line = "「そもそも、流星町で九浄家のヘレナを名乗るなんて、正気の沙汰じゃないよ」"

[[dialogue]]
speaker = "フィオナ"
# 「どういうことでしょう……」
line = "「どういうことでしょう……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「わかったわ！　ここはきっと平行世界なのよ！」
line = "「わかったわ！　ここはきっと平行世界なのよ！」"

[[dialogue]]
speaker = "unk"
# 平行世界？
line = "平行世界？"

[[dialogue]]
speaker = "ヴィーナス"
# 「ええ、漫画で見たわ！　この世界は私たちの世界と似て非なる場所ってこと！」
line = "「ええ、漫画で見たわ！　この世界は私たちの世界と似て非なる場所ってこと！」"

[[dialogue]]
speaker = "フィオナ"
# 「へ、平行世界っ……！！　今風に言えばマルチバース──いえ正確には似て非なるものですが、違う世界に同じ人間がいるなんてロマンが……！！」
line = "「へ、平行世界っ……！！　今風に言えばマルチバース──いえ正確には似て非なるものですが、違う世界に同じ人間がいるなんてロマンが……！！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「フィオナ？」
line = "「フィオナ？」"

[[dialogue]]
speaker = "フィオナ"
# 「──ハッ。コ、コホン……。少々取り乱しました。私はただ理に適っていると思っただけです」
line = "「──ハッ。コ、コホン……。少々取り乱しました。私はただ理に適っていると思っただけです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そ、そう？　冗談半分で言ったつもりだったんだけど……」
line = "「そ、そう？　冗談半分で言ったつもりだったんだけど……」"

[[dialogue]]
speaker = "マグダレナ"
# 「いいえ──あながち的外れではありません」
line = "「いいえ──あながち的外れではありません」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ひゃっ！？　マグダレナ、いたのっ！？」
line = "「ひゃっ！？　マグダレナ、いたのっ！？」"

[[dialogue]]
speaker = "マグダレナ"
# 「はい。お邪魔しないようにずっと傍に控えておりました」
line = "「はい。お邪魔しないようにずっと傍に控えておりました」"

[[dialogue]]
speaker = "聖沙"
# 「……ついに喋り始めてしまったわ。触れるとさらにややこしくなりそうだったから、あえて触れずにいたのに……」
line = "「……ついに喋り始めてしまったわ。触れるとさらにややこしくなりそうだったから、あえて触れずにいたのに……」"

[[dialogue]]
speaker = "リア"
# 「あの人、明らかに天使だよね？　輪っかや羽根も付いてるし……」
line = "「あの人、明らかに天使だよね？　輪っかや羽根も付いてるし……」"

[[dialogue]]
speaker = "フィオナ"
# 「やはり平行世界なのですねっ？　守護天使さまの言うことなら間違いありませんよね！？」
line = "「やはり平行世界なのですねっ？　守護天使さまの言うことなら間違いありませんよね！？」"

[[dialogue]]
speaker = "聖沙"
# 「守護天使ぃ！？　天使は天使でも守護天使ぃ！？」
line = "「守護天使ぃ！？　天使は天使でも守護天使ぃ！？」"

[[dialogue]]
speaker = "リア"
# 「は、初めて見た……。人の形をした守護天使なんて……」
line = "「は、初めて見た……。人の形をした守護天使なんて……」"

[[dialogue]]
speaker = "聖沙"
# 「クルセイダースって、このロザリオの中に宿る守護天使の力を借りて戦っているんですよね……？　この人がいたらもう、私たちの存在価値なくなっちゃうんじゃ……」
line = "「クルセイダースって、このロザリオの中に宿る守護天使の力を借りて戦っているんですよね……？　この人がいたらもう、私たちの存在価値なくなっちゃうんじゃ……」"

[[dialogue]]
speaker = "マグダレナ"
# 「そんなことはありませんよ。この世界の守護天使の力と私の持つ力もまた、似て非なるもののようですから」
line = "「そんなことはありませんよ。この世界の守護天使の力と私の持つ力もまた、似て非なるもののようですから」"

[[dialogue]]
speaker = "リア"
# 「そ、そうなんだ……。それにしても平行世界って……」
line = "「そ、そうなんだ……。それにしても平行世界って……」"

[[dialogue]]
speaker = "マグダレナ"
# 「思うに、こちらの世界でも近頃フィーニスの塔に何か異変が起こっていたのではありませんか？」
line = "「思うに、こちらの世界でも近頃フィーニスの塔に何か異変が起こっていたのではありませんか？」"

[[dialogue]]
speaker = "リア"
# 「それは……うん。実は数日前から妙な気配を放っていて……」
line = "「それは……うん。実は数日前から妙な気配を放っていて……」"

[[dialogue]]
speaker = "マグダレナ"
# 「恐らく、こちらの世界でも私たちの世界と同じく境界の乱れが発生していたのでしょう。そして偶然にも異なる世界でフィーニスの塔同士がリンクしてしまった」
line = "「恐らく、こちらの世界でも私たちの世界と同じく境界の乱れが発生していたのでしょう。そして偶然にも異なる世界でフィーニスの塔同士がリンクしてしまった」"

[[dialogue]]
speaker = "マグダレナ"
# 「その結果、フィーニスの塔の近くにいた我々が次元の層を飛び越えて、こちらの世界に転移してしまったのです」
line = "「その結果、フィーニスの塔の近くにいた我々が次元の層を飛び越えて、こちらの世界に転移してしまったのです」"

[[dialogue]]
speaker = "リア"
# 「でも私はなんともなかったよ？　昨日もフィーニスの塔に様子を見に行ったけれど」
line = "「でも私はなんともなかったよ？　昨日もフィーニスの塔に様子を見に行ったけれど」"

[[dialogue]]
speaker = "マグダレナ"
# 「何か条件があるのかもしれません。次元の境界が大きく乱れてしまうような出来事か何かが」
line = "「何か条件があるのかもしれません。次元の境界が大きく乱れてしまうような出来事か何かが」"

[[dialogue]]
speaker = "ヴィーナス"
# 「フィーニスの塔に行けばすんなり元の世界に戻れるってわけでもないわけね」
line = "「フィーニスの塔に行けばすんなり元の世界に戻れるってわけでもないわけね」"

[[dialogue]]
speaker = "フィオナ"
# 「それに、もしかするとルリエルもこちらの世界に迷い込んでしまったのかもしれません。私たちと同じように……」
line = "「それに、もしかするとルリエルもこちらの世界に迷い込んでしまったのかもしれません。私たちと同じように……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「大いに有り得るわね。元の世界に戻る方法を探しながら、彼女のことも探してみましょ」
line = "「大いに有り得るわね。元の世界に戻る方法を探しながら、彼女のことも探してみましょ」"

[[dialogue]]
speaker = "フィオナ"
# 「はい！　では早速散策してみましょう……！　平行世界を歩き回れるなんて、滅多に出来ない体験ですから……！」
line = "「はい！　では早速散策してみましょう……！　平行世界を歩き回れるなんて、滅多に出来ない体験ですから……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「わわっ、そんなに引っ張らなくても……！　珍しいわね、フィオナがそこまでテンションを上げるなんて……」
line = "「わわっ、そんなに引っ張らなくても……！　珍しいわね、フィオナがそこまでテンションを上げるなんて……」"

[[dialogue]]
speaker = "フィオナ"
# 「そ、そのようなつもりは。私は、えと、ルリエルのことが心配で心配で堪らないだけで」
line = "「そ、そのようなつもりは。私は、えと、ルリエルのことが心配で心配で堪らないだけで」"

[[dialogue]]
speaker = "聖沙"
# 「なら私たちが案内してあげるわ。いいですよね、先輩？」
line = "「なら私たちが案内してあげるわ。いいですよね、先輩？」"

[[dialogue]]
speaker = "リア"
# 「もっちろん♪　困っている人の助けになるのも流星クルセイダースの務めだから。ね♪」
line = "「もっちろん♪　困っている人の助けになるのも流星クルセイダースの務めだから。ね♪」"
