[[dialogue]]
speaker = "グロリア"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "フラン"
# 「てめえ、オレがいねえ間に何してやがる？」
line = "「てめえ、オレがいねえ間に何してやがる？」"

[[dialogue]]
speaker = "グロリア"
# 「フ、フランさん……」
line = "「フ、フランさん……」"

[[dialogue]]
speaker = "unk"
# グロリアさん、大丈夫ですか？
line = "グロリアさん、大丈夫ですか？"

[[dialogue]]
speaker = "グロリア"
# 「会長さんっ」
line = "「会長さんっ」"

[[dialogue]]
speaker = "フラン"
# 「グロリアが孤立したところを狙うとはいい度胸じゃねえか。だが姿を見せたからには容赦しねえ。きれいさっぱり燃やし尽くしてやる！」
line = "「グロリアが孤立したところを狙うとはいい度胸じゃねえか。だが姿を見せたからには容赦しねえ。きれいさっぱり燃やし尽くしてやる！」"

[[dialogue]]
speaker = "フラン"
# 「ハッ、この程度！」
line = "「ハッ、この程度！」"

[[dialogue]]
speaker = "フラン"
# 「会長、合わせろ！　フレイムリインフォース！」
line = "「会長、合わせろ！　フレイムリインフォース！」"

[[dialogue]]
speaker = "フラン"
# 「いねえ……チッ、逃げたか……」
line = "「いねえ……チッ、逃げたか……」"

[[dialogue]]
speaker = "グロリア"
# 「ご無事ですか、フランさんっ、会長さんっ」
line = "「ご無事ですか、フランさんっ、会長さんっ」"

[[dialogue]]
speaker = "フラン"
# 「見ての通りピンピンしてるよ。……ったく、みすみす逃がしちまうとはオレも焼きが回ったな」
line = "「見ての通りピンピンしてるよ。……ったく、みすみす逃がしちまうとはオレも焼きが回ったな」"

[[dialogue]]
speaker = "unk"
# 怪我はないですか？
line = "怪我はないですか？"

[[dialogue]]
speaker = "グロリア"
# 「はい。フランさんも会長さんも、助けていただいてありがとうございました。おふたりにはいつもお世話になってばかりで……」
line = "「はい。フランさんも会長さんも、助けていただいてありがとうございました。おふたりにはいつもお世話になってばかりで……」"

[[dialogue]]
speaker = "グロリア"
# 「……おふたりとも一緒に死んでいただけませんか？」
line = "「……おふたりとも一緒に死んでいただけませんか？」"

[[dialogue]]
speaker = "フラン"
# 「それじゃ助けた意味ねえだろうが！」
line = "「それじゃ助けた意味ねえだろうが！」"

[[dialogue]]
speaker = "unk"
# あはは……
line = "あはは……"

[[dialogue]]
speaker = "プルちゃん"
# 「おーい、なんかあったー？　賑やかな音が聞こえてきたんだけど」
line = "「おーい、なんかあったー？　賑やかな音が聞こえてきたんだけど」"

[[dialogue]]
speaker = "フラン"
# 「なんかあったー、じゃねえよ。お前がいない間に出たんだよ、死神が」
line = "「なんかあったー、じゃねえよ。お前がいない間に出たんだよ、死神が」"

[[dialogue]]
speaker = "プルちゃん"
# 「やった！　あたし自由研究に死神捕まえに来たんだよね～！　標本にしてやる～！」
line = "「やった！　あたし自由研究に死神捕まえに来たんだよね～！　標本にしてやる～！」"

[[dialogue]]
speaker = "フラン"
# 「夏休みの昆虫採集か」
line = "「夏休みの昆虫採集か」"

[[dialogue]]
speaker = "グロリア"
# 「でも厳密には堕天した守護天使様だそうで……。堕天使になっているのは《試練》のパテル様だそうです」
line = "「でも厳密には堕天した守護天使様だそうで……。堕天使になっているのは《試練》のパテル様だそうです」"

[[dialogue]]
speaker = "プルちゃん"
# 「へー、しゅごてんしのパテルさまねー。きっとプリチーでエレガントな天使様なんだろうな～」
line = "「へー、しゅごてんしのパテルさまねー。きっとプリチーでエレガントな天使様なんだろうな～」"

[[dialogue]]
speaker = "フラン"
# 「ハッ、グロリアが１人になったところを狙ってきた卑怯者だろ。守護天使が聞いて呆れるぜ」
line = "「ハッ、グロリアが１人になったところを狙ってきた卑怯者だろ。守護天使が聞いて呆れるぜ」"

[[dialogue]]
speaker = "プルちゃん"
# 「ハハ、それはスマートっていうんだよ。さすが守護天使様だね！」
line = "「ハハ、それはスマートっていうんだよ。さすが守護天使様だね！」"

[[dialogue]]
speaker = "プルちゃん"
# 「でも……それは利用できるかも」
line = "「でも……それは利用できるかも」"

[[dialogue]]
speaker = "フラン"
# 「利用？」
line = "「利用？」"

[[dialogue]]
speaker = "プルちゃん"
# 「パテルはグロリアおねーさんが１人になったところを狙ってきた。てことはあたしたちが集まってる間はきっと襲ってこないよ」
line = "「パテルはグロリアおねーさんが１人になったところを狙ってきた。てことはあたしたちが集まってる間はきっと襲ってこないよ」"

[[dialogue]]
speaker = "プルちゃん"
# 「だからあえてバラバラになって、パテルが襲撃してきたところを、連絡を取り合って挟み撃ちにする」
line = "「だからあえてバラバラになって、パテルが襲撃してきたところを、連絡を取り合って挟み撃ちにする」"

[[dialogue]]
speaker = "プルちゃん"
# 「悠長にしてられないし、おびき寄せて逃がさないようにするっていうならこれが一番なんじゃない？」
line = "「悠長にしてられないし、おびき寄せて逃がさないようにするっていうならこれが一番なんじゃない？」"

[[dialogue]]
speaker = "フラン"
# 「ダメだ。オレと会長はともかく、グロリアが心配だ。そもそもグロリアは１人で戦うには不向きなんだよ」
line = "「ダメだ。オレと会長はともかく、グロリアが心配だ。そもそもグロリアは１人で戦うには不向きなんだよ」"

[[dialogue]]
speaker = "グロリア"
# 「大丈夫です。私とてプリマステラですから、フランさんと会長さんと合流するまでは耐えてみせます」
line = "「大丈夫です。私とてプリマステラですから、フランさんと会長さんと合流するまでは耐えてみせます」"

[[dialogue]]
speaker = "グロリア"
# 「ダメでも守護天使様に連れていってもらえるなら……」
line = "「ダメでも守護天使様に連れていってもらえるなら……」"

[[dialogue]]
speaker = "フラン"
# 「ぶれねーなぁ……」
line = "「ぶれねーなぁ……」"

[[dialogue]]
speaker = "プルちゃん"
# 「んじゃあさぁ、あたしＤＩＳＣ忘れて連絡できないし、単独行動は不安だし、あたしとグロリアおねーさんで行動しようよ。戦力的にはバランス取れるんじゃない？」
line = "「んじゃあさぁ、あたしＤＩＳＣ忘れて連絡できないし、単独行動は不安だし、あたしとグロリアおねーさんで行動しようよ。戦力的にはバランス取れるんじゃない？」"

[[dialogue]]
speaker = "フラン"
# 「それで大丈夫かぁ？」
line = "「それで大丈夫かぁ？」"

[[dialogue]]
speaker = "プルちゃん"
# 「あたしだって星騎士だよ？　おねーさんを守るくらいはできるって。屋形船に乗ったつもりで任せといてよ」
line = "「あたしだって星騎士だよ？　おねーさんを守るくらいはできるって。屋形船に乗ったつもりで任せといてよ」"

[[dialogue]]
speaker = "グロリア"
# 「ふふふ、頼りにしていますね、プルちゃん」
line = "「ふふふ、頼りにしていますね、プルちゃん」"

[[dialogue]]
speaker = "プルちゃん"
# 「うん！　大暴れしておにーさんとフランおねーさんをビックリさせてやろー！」
line = "「うん！　大暴れしておにーさんとフランおねーさんをビックリさせてやろー！」"

[[dialogue]]
speaker = "unk"
# それからプルちゃんの言うとり、３つに分かれて堕天使パテルをおびき寄せることになった。
line = "それからプルちゃんの言うとり、３つに分かれて堕天使パテルをおびき寄せることになった。"

[[dialogue]]
speaker = "unk"
# そして──
line = "そして──"

[[dialogue]]
speaker = "unk"
# こっちに出た！
line = "こっちに出た！"

[[dialogue]]
speaker = "フラン"
# 『ああ？　こっちにも死神出たぞ！　どうなってんだ！？』
line = "『ああ？　こっちにも死神出たぞ！　どうなってんだ！？』"

[[dialogue]]
speaker = "フラン"
# 『もしかしてグロリアの方にも──』
line = "『もしかしてグロリアの方にも──』"

[[dialogue]]
speaker = "グロリア"
# 「堕天使が来ました。フランさんたちが来るまで一緒に頑張りましょう、プルちゃん！」
line = "「堕天使が来ました。フランさんたちが来るまで一緒に頑張りましょう、プルちゃん！」"

[[dialogue]]
speaker = "グロリア"
# 「え……あれ……堕天使がたくさん……？」
line = "「え……あれ……堕天使がたくさん……？」"

[[dialogue]]
speaker = "プルちゃん"
# 「フフ……」
line = "「フフ……」"

[[dialogue]]
speaker = "グロリア"
# 「プルちゃん……？」
line = "「プルちゃん……？」"

[[dialogue]]
speaker = "プルちゃん"
# 「改めて自己紹介するよ。附属のアイドル・プルちゃんは仮の姿──」
line = "「改めて自己紹介するよ。附属のアイドル・プルちゃんは仮の姿──」"

[[dialogue]]
speaker = "パテル"
# 「あたしは《試練》のパテル。この世界の死神さ！」
line = "「あたしは《試練》のパテル。この世界の死神さ！」"
