[[dialogue]]
speaker = "unk"
# 日が暮れたのでパテルストーン探しを中断し、浜辺でバーベキューをすることになった。
line = "日が暮れたのでパテルストーン探しを中断し、浜辺でバーベキューをすることになった。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「おにっく、おにっく、おにっく～♪　待ちに待ったバーベキューなのだ～♪」
line = "「おにっく、おにっく、おにっく～♪　待ちに待ったバーベキューなのだ～♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「お肉がじゅうじゅう焼ける匂いがして……うぅぅっ、お腹が空いてフラフラなのだ～……」
line = "「お肉がじゅうじゅう焼ける匂いがして……うぅぅっ、お腹が空いてフラフラなのだ～……」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「はい、お肉が焼けましたよー」
line = "「はい、お肉が焼けましたよー」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ありがとうなのだ！　いただきますなのだ！　あ～んっ♪」
line = "「ありがとうなのだ！　いただきますなのだ！　あ～んっ♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「んん～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>　やっぱりお肉は最高なのだっ<emoji=heart04><emoji=heart04>」
line = "「んん～～～っ<emoji=heart04><emoji=heart04><emoji=heart04>　やっぱりお肉は最高なのだっ<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「会長とパテルもどうぞ～」
line = "「会長とパテルもどうぞ～」"

[[dialogue]]
speaker = "unk"
# ありがとう
line = "ありがとう"

[[dialogue]]
speaker = "パテル"
# 「ありがとー」
line = "「ありがとー」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「パテルもママダレナって呼んでいいんですよ～」
line = "「パテルもママダレナって呼んでいいんですよ～」"

[[dialogue]]
speaker = "パテル"
# 「ヤダ。アウクセシアじゃあるまいし、同僚をママと呼ぶ趣味はないよ」
line = "「ヤダ。アウクセシアじゃあるまいし、同僚をママと呼ぶ趣味はないよ」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「そんな！？」
line = "「そんな！？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「あはは、セシアにもウケが悪かったのに、パテルにも拒否られたのだ」
line = "「あはは、セシアにもウケが悪かったのに、パテルにも拒否られたのだ」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「うぅ～っ……ママダレナ悲しいです～っ」
line = "「うぅ～っ……ママダレナ悲しいです～っ」"

[[dialogue]]
speaker = "パテル"
# 「じゃあお肉いただき～。あ～んっ。……ん～、お肉おいし～っ<emoji=heart04>」
line = "「じゃあお肉いただき～。あ～んっ。……ん～、お肉おいし～っ<emoji=heart04>」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「でもパテルがお肉を食べるのは意外なのだ」
line = "「でもパテルがお肉を食べるのは意外なのだ」"

[[dialogue]]
speaker = "パテル"
# 「最初は抵抗あったけどね。でもあたしも肉体がある以上、食べないと生きられないし」
line = "「最初は抵抗あったけどね。でもあたしも肉体がある以上、食べないと生きられないし」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「そうですね。私たちも命を持った存在ですから」
line = "「そうですね。私たちも命を持った存在ですから」"

[[dialogue]]
speaker = "パテル"
# 「もし何か起きても、全部あたしを堕天させたリクリエのせいだからね♪」
line = "「もし何か起きても、全部あたしを堕天させたリクリエのせいだからね♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「開き直ったのだ！？」
line = "「開き直ったのだ！？」"

[[dialogue]]
speaker = "unk"
# 魚のホイル焼きもできたよ
line = "魚のホイル焼きもできたよ"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「やったのだ～！　会長と２人で獲ったお魚、いただきますなのだ！　あ～むっ」
line = "「やったのだ～！　会長と２人で獲ったお魚、いただきますなのだ！　あ～むっ」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ん～っ<emoji=heart04>　ホロッと柔らかくて美味しいのだ～っ<emoji=heart04>　会長も食べるのだ」
line = "「ん～っ<emoji=heart04>　ホロッと柔らかくて美味しいのだ～っ<emoji=heart04>　会長も食べるのだ」"

[[dialogue]]
speaker = "unk"
# うん、美味しい！
line = "うん、美味しい！"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「リップルさまからもらったお野菜にお魚の旨味が染みて、こちらも絶品ですね～♪」
line = "「リップルさまからもらったお野菜にお魚の旨味が染みて、こちらも絶品ですね～♪」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「あ、潮干狩りで採った貝も焼けてきました。こっちも美味しそうです♪」
line = "「あ、潮干狩りで採った貝も焼けてきました。こっちも美味しそうです♪」"

[[dialogue]]
speaker = "unk"
# 一番貝を採ったマグダレナからどうぞ
line = "一番貝を採ったマグダレナからどうぞ"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ありがとうございます。それじゃ遠慮なく……ん～っ<emoji=heart04>　ジューシーな旨味が溢れます……<emoji=heart04>」
line = "「ありがとうございます。それじゃ遠慮なく……ん～っ<emoji=heart04>　ジューシーな旨味が溢れます……<emoji=heart04>」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「海の味がするのだ！　贅沢なのだ～っ♪」
line = "「海の味がするのだ！　贅沢なのだ～っ♪」"

[[dialogue]]
speaker = "unk"
# サザエもハマグリも美味しい！
line = "サザエもハマグリも美味しい！"

[[dialogue]]
speaker = "パテル"
# 「はぁ～、食べた食べた。ごちそうさま～」
line = "「はぁ～、食べた食べた。ごちそうさま～」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「早いのだ！？　パテル、ちゃんと食べたか！？」
line = "「早いのだ！？　パテル、ちゃんと食べたか！？」"

[[dialogue]]
speaker = "パテル"
# 「うん、お肉もお魚も貝も食べたよ。美味しかった」
line = "「うん、お肉もお魚も貝も食べたよ。美味しかった」"

[[dialogue]]
speaker = "unk"
# 遠慮してない？
line = "遠慮してない？"

[[dialogue]]
speaker = "パテル"
# 「お肉もお魚も結界で出してるものだし、遠慮なんかしないよ。あなたたちより小食なだけ」
line = "「お肉もお魚も結界で出してるものだし、遠慮なんかしないよ。あなたたちより小食なだけ」"

[[dialogue]]
speaker = "パテル"
# 「アルモタヘル、あたしの分も食べていいよ」
line = "「アルモタヘル、あたしの分も食べていいよ」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ありがとうなのだ！　はむっ、はむっ、はむっ……お肉もお魚も美味しいのだ～っ<emoji=heart04>」
line = "「ありがとうなのだ！　はむっ、はむっ、はむっ……お肉もお魚も美味しいのだ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "パテル"
# 「……まぁ、アルモタヘルと比べたら誰でも小食になりそうだけど」
line = "「……まぁ、アルモタヘルと比べたら誰でも小食になりそうだけど」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「お肉が足りないのだ！　なくなっちゃったのだ！」
line = "「お肉が足りないのだ！　なくなっちゃったのだ！」"

[[dialogue]]
speaker = "パテル"
# 「あれだけ食べたらそうなるでしょ。ていうかまだ食べるつもりなの？」
line = "「あれだけ食べたらそうなるでしょ。ていうかまだ食べるつもりなの？」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「アルモタヘルは小さくなっても食いしん坊さんですね」
line = "「アルモタヘルは小さくなっても食いしん坊さんですね」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「リップルさまが、お肉が足りなくなったら海の家に取りに来て、と仰っていましたから、行ってきますね」
line = "「リップルさまが、お肉が足りなくなったら海の家に取りに来て、と仰っていましたから、行ってきますね」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「アルモたんも行くのだ！　お肉が待ちきれないのだ！」
line = "「アルモたんも行くのだ！　お肉が待ちきれないのだ！」"

[[dialogue]]
speaker = "unk"
# 行ってらっしゃい
line = "行ってらっしゃい"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「は～い、行ってきますねー」
line = "「は～い、行ってきますねー」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ふんふんふふ～ん♪」
line = "「ふんふんふふ～ん♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ふんふふ～ん……」
line = "「ふんふふ～ん……」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「夜の海で２人きりだと怖くなってきたのだ……」
line = "「夜の海で２人きりだと怖くなってきたのだ……」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「そうですね……ちょっと不安になるかもしれません……」
line = "「そうですね……ちょっと不安になるかもしれません……」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「どうしてなのだ？　アルモたんとマグダレナは守護天使。暗いくらいで怖がらないはずなのだ」
line = "「どうしてなのだ？　アルモたんとマグダレナは守護天使。暗いくらいで怖がらないはずなのだ」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「うーん……肉体に引っ張られているのかもしれませんね」
line = "「うーん……肉体に引っ張られているのかもしれませんね」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「お腹が空くのも、食べ物が美味しいのも、肉体から来る感情です。だから肉体の本能で『怖い』と感じてもおかしくないと思います」
line = "「お腹が空くのも、食べ物が美味しいのも、肉体から来る感情です。だから肉体の本能で『怖い』と感じてもおかしくないと思います」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「なるほどなのだ……肉体があると、いい気持ちばかりじゃないのだな……」
line = "「なるほどなのだ……肉体があると、いい気持ちばかりじゃないのだな……」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ん……？　後ろから誰か来て……会長も手伝ってくれるのか？」
line = "「ん……？　後ろから誰か来て……会長も手伝ってくれるのか？」"

[[dialogue]]
speaker = "？？？"
# 「──」
line = "「──」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「ひっ！？」
line = "「ひっ！？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「──って、パテルなのだ。ビックリしちゃったのだ」
line = "「──って、パテルなのだ。ビックリしちゃったのだ」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「でもどうしてその姿なのだ？　さっきは水着で──」
line = "「でもどうしてその姿なのだ？　さっきは水着で──」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「あ、アルモタヘル！　後ろに──！」
line = "「あ、アルモタヘル！　後ろに──！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「へ──？」
line = "「へ──？」"

[[dialogue]]
speaker = "サメ"
# 「シャーーーッ！！！」
line = "「シャーーーッ！！！」"
