[[dialogue]]
speaker = "unk"
# 果たして、ディーラックとの戦闘は始まった。
line = "果たして、ディーラックとの戦闘は始まった。"

[[dialogue]]
speaker = "unk"
# しかし――
line = "しかし――"

[[dialogue]]
speaker = "ディーラック"
# 「ばあああぁぁぁ～～～っ♪」
line = "「ばあああぁぁぁ～～～っ♪」"

[[dialogue]]
speaker = "サチ"
# 「くっ……！？」
line = "「くっ……！？」"

[[dialogue]]
speaker = "unk"
# 強い……！
line = "強い……！"

[[dialogue]]
speaker = "ディーラック"
# 「ひひっ♪　当たり前サ！　この星にロストアイテムが生まれた時から、貯まりに貯まった負のエネルギーの集合体がこのボク！」
line = "「ひひっ♪　当たり前サ！　この星にロストアイテムが生まれた時から、貯まりに貯まった負のエネルギーの集合体がこのボク！」"

[[dialogue]]
speaker = "ディーラック"
# 「根本的なエネルギー総量において、キミたちが束になろうとも、敵いはしないよ！」
line = "「根本的なエネルギー総量において、キミたちが束になろうとも、敵いはしないよ！」"

[[dialogue]]
speaker = "ディーラック"
# 「サーシャちゃんも、さっさと空間の凍結を解いた方がいいんじゃない？　そっちに力を使っていたら、ボクには勝てないよ？」
line = "「サーシャちゃんも、さっさと空間の凍結を解いた方がいいんじゃない？　そっちに力を使っていたら、ボクには勝てないよ？」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「ええ。私１人ならそうね。でも――」
line = "「ええ。私１人ならそうね。でも――」"

[[dialogue]]
speaker = "ディーラック"
# 「あん？」
line = "「あん？」"

[[dialogue]]
speaker = "プリムラ"
# 「おい、サチ」
line = "「おい、サチ」"

[[dialogue]]
speaker = "サチ"
# 「プリムラ、どうしたの？」
line = "「プリムラ、どうしたの？」"

[[dialogue]]
speaker = "プリムラ"
# 「我に、もう１度変身する許可を寄こせ」
line = "「我に、もう１度変身する許可を寄こせ」"

[[dialogue]]
speaker = "サチ"
# 「えっ？　もう１度って……？」
line = "「えっ？　もう１度って……？」"

[[dialogue]]
speaker = "プリムラ"
# 「思い出すのじゃ。お前はもう、２度見ているじゃろう」
line = "「思い出すのじゃ。お前はもう、２度見ているじゃろう」"

[[dialogue]]
speaker = "サチ"
# 「……！　大丈夫なの？」
line = "「……！　大丈夫なの？」"

[[dialogue]]
speaker = "プリムラ"
# 「無論じゃ。信用しろ！」
line = "「無論じゃ。信用しろ！」"

[[dialogue]]
speaker = "サチ"
# 「わかった。――プリムラ！」
line = "「わかった。――プリムラ！」"

[[dialogue]]
speaker = "サチ"
# 「変身を許可する！　私たちに力を貸して！」
line = "「変身を許可する！　私たちに力を貸して！」"

[[dialogue]]
speaker = "プリムラ"
# 「よかろう。行くぞ――」
line = "「よかろう。行くぞ――」"

[[dialogue]]
speaker = "プリムラ"
# 「解放ッ！！！」
line = "「解放ッ！！！」"

[[dialogue]]
speaker = "ディーラック"
# 「なんだ……！？」
line = "「なんだ……！？」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「待たせたな、ディーラック」
line = "「待たせたな、ディーラック」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「我の第２形態――名づけて『デストロイフォーム』じゃ」
line = "「我の第２形態――名づけて『デストロイフォーム』じゃ」"

[[dialogue]]
speaker = "ディーラック"
# 「その姿……『解放』のロストアイテムを使ってないのに……！」
line = "「その姿……『解放』のロストアイテムを使ってないのに……！」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「ああ、じゃから、もう変身できないとさっきまで思い込んでいた」
line = "「ああ、じゃから、もう変身できないとさっきまで思い込んでいた」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「しかしよく考えれば、要するに封印の一部が解ければいいんじゃろう？」
line = "「しかしよく考えれば、要するに封印の一部が解ければいいんじゃろう？」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「だったらサチに言って、我の力を解放する許可をもらえばよい」
line = "「だったらサチに言って、我の力を解放する許可をもらえばよい」"

[[dialogue]]
speaker = "ディーラック"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「しくじったな、ディーラック。そもそも我の力を暴走させようと企まなければ、こんなことを仕出かそうという発想も生まれなかったというのに」
line = "「しくじったな、ディーラック。そもそも我の力を暴走させようと企まなければ、こんなことを仕出かそうという発想も生まれなかったというのに」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「さあ、覚悟しろ！　元は貴様が作った終末兵器じゃ。それが本気を出せばどれ程の脅威か、わかっていよう？」
line = "「さあ、覚悟しろ！　元は貴様が作った終末兵器じゃ。それが本気を出せばどれ程の脅威か、わかっていよう？」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「さあ、行くぞ、サチ！」
line = "「さあ、行くぞ、サチ！」"

[[dialogue]]
speaker = "サチ"
# 「うん！　人事天命……ここからは――」
line = "「うん！　人事天命……ここからは――」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「ハズレなしじゃ！！！」
line = "「ハズレなしじゃ！！！」"

[[dialogue]]
speaker = "unk"
# そう言うと同時に、プリムラは巨大なキャノン砲をぶっ放すのだった。
line = "そう言うと同時に、プリムラは巨大なキャノン砲をぶっ放すのだった。"

[[dialogue]]
speaker = "unk"
# それから、強化変身を遂げたプリムラが戦力に加わったことで、戦局はこちらに傾き始めていた。
line = "それから、強化変身を遂げたプリムラが戦力に加わったことで、戦局はこちらに傾き始めていた。"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「フハハハハハハ！　そらそらそらそらぁ！　さっさと降参するのじゃあぁぁぁっ！」
line = "「フハハハハハハ！　そらそらそらそらぁ！　さっさと降参するのじゃあぁぁぁっ！」"

[[dialogue]]
speaker = "unk"
# ノンストップで凄まじい火力の砲撃をディーラックに浴びせ続けるプリムラ。
line = "ノンストップで凄まじい火力の砲撃をディーラックに浴びせ続けるプリムラ。"

[[dialogue]]
speaker = "ディーラック"
# 「ちいぃっ！　これだけの威力の攻撃を連発して、何故エネルギー切れしない！？」
line = "「ちいぃっ！　これだけの威力の攻撃を連発して、何故エネルギー切れしない！？」"

[[dialogue]]
speaker = "ディーラック"
# 「いや待てよ！？　それどころか、ボクのエネルギーが消耗している！？　これは……！」
line = "「いや待てよ！？　それどころか、ボクのエネルギーが消耗している！？　これは……！」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「気づくのが遅いわ！　このフォームは遠距離であっても、ターゲットロックした相手のエネルギーを吸収することができるのじゃ！」
line = "「気づくのが遅いわ！　このフォームは遠距離であっても、ターゲットロックした相手のエネルギーを吸収することができるのじゃ！」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「そして、それを砲撃のエネルギーに変換する！　相手が倒れるまで終わらない攻撃――」
line = "「そして、それを砲撃のエネルギーに変換する！　相手が倒れるまで終わらない攻撃――」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「つまりは、無限ループのデスコンボ成立というわけじゃなあぁぁぁ！　フハハハハハハ！！！」
line = "「つまりは、無限ループのデスコンボ成立というわけじゃなあぁぁぁ！　フハハハハハハ！！！」"

[[dialogue]]
speaker = "ディーラック"
# 「何それ知らん……怖っ！」
line = "「何それ知らん……怖っ！」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「お前が作ったんじゃろがあぁぁぁっ！！！」
line = "「お前が作ったんじゃろがあぁぁぁっ！！！」"

[[dialogue]]
speaker = "unk"
# と、ディーラックの動きが一瞬、凍ったように停止する。
line = "と、ディーラックの動きが一瞬、凍ったように停止する。"

[[dialogue]]
speaker = "ディーラック"
# 「なにっ……！？」
line = "「なにっ……！？」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「捕らえたわ」
line = "「捕らえたわ」"

[[dialogue]]
speaker = "ディーラック"
# 「ピンポイントの空間凍結！？　くっ……これくらい力づくでぇぇぇ！」
line = "「ピンポイントの空間凍結！？　くっ……これくらい力づくでぇぇぇ！」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「ええ。だけど、一瞬でも止められれば――プリムラちゃん！」
line = "「ええ。だけど、一瞬でも止められれば――プリムラちゃん！」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「任せるのじゃ！　エネルギー最大出力！！」
line = "「任せるのじゃ！　エネルギー最大出力！！」"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「くらえっ！！！　シャイニング・ブレイズキャノン！！」
line = "「くらえっ！！！　シャイニング・ブレイズキャノン！！」"

[[dialogue]]
speaker = "ディーラック"
# 「避けられないっ！？　このっ……舐めるなあああぁぁぁーーーーーーーーーっ！！！」
line = "「避けられないっ！？　このっ……舐めるなあああぁぁぁーーーーーーーーーっ！！！」"

[[dialogue]]
speaker = "unk"
# ディーラックがプリムラの極大砲撃に対して大きく口を開き、なんと――
line = "ディーラックがプリムラの極大砲撃に対して大きく口を開き、なんと――"

[[dialogue]]
speaker = "ディーラック"
# 「これくらいのエネルギー、全部食らいつくしてやるのサァァァーーーーーーーーーっ！！！」
line = "「これくらいのエネルギー、全部食らいつくしてやるのサァァァーーーーーーーーーっ！！！」"

[[dialogue]]
speaker = "unk"
# 真正面から砲撃を飲み込み始めた。
line = "真正面から砲撃を飲み込み始めた。"

[[dialogue]]
speaker = "プリムラ（覚醒）"
# 「はあああぁぁぁーーーーーーーーーっ！！！」
line = "「はあああぁぁぁーーーーーーーーーっ！！！」"

[[dialogue]]
speaker = "ディーラック"
# 「うおおおぉぉぉーーーーーーーーーっ！！！」
line = "「うおおおぉぉぉーーーーーーーーーっ！！！」"

[[dialogue]]
speaker = "unk"
# そんなエネルギーの綱引きとも言えるような攻防が続く中。
line = "そんなエネルギーの綱引きとも言えるような攻防が続く中。"

[[dialogue]]
speaker = "unk"
# プリムラの両肩に、後ろから手を添える人物が１人。
line = "プリムラの両肩に、後ろから手を添える人物が１人。"

[[dialogue]]
speaker = "シズハ"
# 「――ディーちゃん」
line = "「――ディーちゃん」"

[[dialogue]]
speaker = "ディーラック"
# 「……！　シズハちゃん」
line = "「……！　シズハちゃん」"

[[dialogue]]
speaker = "シズハ"
# 「ねぇ、ディーちゃんはどうして、私の前に現れたの？」
line = "「ねぇ、ディーちゃんはどうして、私の前に現れたの？」"

[[dialogue]]
speaker = "ディーラック"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ディーラック"
# 「……聖杯は、他のロストアイテムよりもマイナスエネルギーが生まれやすい。それが主食であるボクには、キミの存在はうってつけだった！」
line = "「……聖杯は、他のロストアイテムよりもマイナスエネルギーが生まれやすい。それが主食であるボクには、キミの存在はうってつけだった！」"

[[dialogue]]
speaker = "シズハ"
# 「聖杯ちゃんは……ディーちゃんが私にくれたの？」
line = "「聖杯ちゃんは……ディーちゃんが私にくれたの？」"

[[dialogue]]
speaker = "ディーラック"
# 「ああ、そうサ！　恨むなら、好きにするんだネ！」
line = "「ああ、そうサ！　恨むなら、好きにするんだネ！」"

[[dialogue]]
speaker = "シズハ"
# 「ありがとね」
line = "「ありがとね」"

[[dialogue]]
speaker = "ディーラック"
# 「……！？」
line = "「……！？」"

[[dialogue]]
speaker = "シズハ"
# 「私はそのおかげで、今こうして生きていられる。死んじゃったお姉ちゃんの願いを叶えることができる。それとね――」
line = "「私はそのおかげで、今こうして生きていられる。死んじゃったお姉ちゃんの願いを叶えることができる。それとね――」"

[[dialogue]]
speaker = "シズハ"
# 「この２ヶ月、ディーちゃんと居て楽しかったよ。……ディーちゃんは、どうだった？」
line = "「この２ヶ月、ディーちゃんと居て楽しかったよ。……ディーちゃんは、どうだった？」"

[[dialogue]]
speaker = "ディーラック"
# 「別に、何も思わなかったサ！」
line = "「別に、何も思わなかったサ！」"

[[dialogue]]
speaker = "シズハ"
# 「ねぇ、ディーちゃん……！」
line = "「ねぇ、ディーちゃん……！」"

[[dialogue]]
speaker = "シズハ"
# 「悪さはもう止めて、これからも一緒に仲良くしない？」
line = "「悪さはもう止めて、これからも一緒に仲良くしない？」"

[[dialogue]]
speaker = "ディーラック"
# 「…………キミに願いがあるように、ボクにも――」
line = "「…………キミに願いがあるように、ボクにも――」"

[[dialogue]]
speaker = "ディーラック"
# 「叶えたい目的がある！　だから、それはできないネ！！」
line = "「叶えたい目的がある！　だから、それはできないネ！！」"

[[dialogue]]
speaker = "シズハ"
# 「そう……」
line = "「そう……」"

[[dialogue]]
speaker = "シズハ"
# 「なら――私はディーちゃんを止める。サーシャさんが、私にしてくれたように！」
line = "「なら――私はディーちゃんを止める。サーシャさんが、私にしてくれたように！」"

[[dialogue]]
speaker = "シズハ"
# 「お願い。聖杯ちゃん……」
line = "「お願い。聖杯ちゃん……」"

[[dialogue]]
speaker = "シズハ"
# 「ディーちゃんを止める力を――私に頂戴！！！」
line = "「ディーちゃんを止める力を――私に頂戴！！！」"

[[dialogue]]
speaker = "unk"
# シズハがそう言った瞬間、彼女の体が眩しい輝きを帯びて。
line = "シズハがそう言った瞬間、彼女の体が眩しい輝きを帯びて。"

[[dialogue]]
speaker = "シズハ"
# 「行っけぇぇぇーーーーーーーーーっ！！！」
line = "「行っけぇぇぇーーーーーーーーーっ！！！」"

[[dialogue]]
speaker = "unk"
# その輝きがプリムラのキャノン砲へと伝わり、砲撃の閃光が何倍にも膨れ上がった。
line = "その輝きがプリムラのキャノン砲へと伝わり、砲撃の閃光が何倍にも膨れ上がった。"

[[dialogue]]
speaker = "ディーラック"
# 「ぐっ……うおおおおおおぉぉぉーーーーーーーーーっ！！？」
line = "「ぐっ……うおおおおおおぉぉぉーーーーーーーーーっ！！？」"

[[dialogue]]
speaker = "unk"
# そうして、アリーナが白い光に包まれる中で――
line = "そうして、アリーナが白い光に包まれる中で――"

[[dialogue]]
speaker = "ディーラック"
# 「――またね、シズハちゃん」
line = "「――またね、シズハちゃん」"

[[dialogue]]
speaker = "unk"
# そんな言葉が、小さく聞こえたのだった。
line = "そんな言葉が、小さく聞こえたのだった。"
