[[dialogue]]
speaker = "リップル"
# 「隙間が生まれたのは……ワタシ自身にゲンインがある……？　ど、どういうコトです！？」
line = "「隙間が生まれたのは……ワタシ自身にゲンインがある……？　ど、どういうコトです！？」"

[[dialogue]]
speaker = "雪女"
# 「フフフ……聞いての通りデス。ワカラナイとはイワセませんよ」
line = "「フフフ……聞いての通りデス。ワカラナイとはイワセませんよ」"

[[dialogue]]
speaker = "雪女"
# 「……スノボ」
line = "「……スノボ」"

[[dialogue]]
speaker = "リップル"
# 「う！？」
line = "「う！？」"

[[dialogue]]
speaker = "雪女"
# 「……こたつ。みかん。雪だるま。イルミネーション」
line = "「……こたつ。みかん。雪だるま。イルミネーション」"

[[dialogue]]
speaker = "リップル"
# 「う、う……！？」
line = "「う、う……！？」"

[[dialogue]]
speaker = "unk"
# リップル……？
line = "リップル……？"

[[dialogue]]
speaker = "unk"
# 心当たりが？
line = "心当たりが？"

[[dialogue]]
speaker = "ルリエル"
# 「リップルさん……？」
line = "「リップルさん……？」"

[[dialogue]]
speaker = "リップル"
# 「エエト、ジツは……」
line = "「エエト、ジツは……」"

[[dialogue]]
speaker = "リップル"
# 「ワタシは以前──モネやコウメイからクリスマスのハッピーをマナビました」
line = "「ワタシは以前──モネやコウメイからクリスマスのハッピーをマナビました」"

[[dialogue]]
speaker = "リップル"
# 「誰かをヨロコバせたい。大好きな誰かと一緒にタノシミたい……そんなキモチがこもった特別な日ナンだと」
line = "「誰かをヨロコバせたい。大好きな誰かと一緒にタノシミたい……そんなキモチがこもった特別な日ナンだと」"

[[dialogue]]
speaker = "リップル"
# 「ソシテ、学園にいる他のフレンズからも、タクサンの冬の楽しみを教えてもらいマシタ」
line = "「ソシテ、学園にいる他のフレンズからも、タクサンの冬の楽しみを教えてもらいマシタ」"

[[dialogue]]
speaker = "アナ"
# 「ふむふむ……ですが、それがどうして？」
line = "「ふむふむ……ですが、それがどうして？」"

[[dialogue]]
speaker = "リップル"
# 「ハイ。そしてワタシは、それら『冬の楽しみ』もまとめてエンドレスサマーに取り込もうとシマシタ。ですが……」
line = "「ハイ。そしてワタシは、それら『冬の楽しみ』もまとめてエンドレスサマーに取り込もうとシマシタ。ですが……」"

[[dialogue]]
speaker = "リップル"
# 「常夏のスノボや雪だるまについて──ワタシはまだ十分にイメージできていないのデス……！」
line = "「常夏のスノボや雪だるまについて──ワタシはまだ十分にイメージできていないのデス……！」"

[[dialogue]]
speaker = "雪女"
# 「フフ……ソウ。アナタはまだ夏スノボや夏こたつの開発ができてイナイ！」
line = "「フフ……ソウ。アナタはまだ夏スノボや夏こたつの開発ができてイナイ！」"

[[dialogue]]
speaker = "雪女"
# 「つまり、このリゾート結界は今、一時的にフカンゼンな状態になってイルのデース！」
line = "「つまり、このリゾート結界は今、一時的にフカンゼンな状態になってイルのデース！」"

[[dialogue]]
speaker = "マトイ"
# 「確かに夏こたつなんて見かけなかったけど…………って夏こたつって何！？」
line = "「確かに夏こたつなんて見かけなかったけど…………って夏こたつって何！？」"

[[dialogue]]
speaker = "リップル"
# 「ソレをコレから考案するのデス！　ソレが──常夏を永遠のモノとスル、リップルの使命デース！」
line = "「ソレをコレから考案するのデス！　ソレが──常夏を永遠のモノとスル、リップルの使命デース！」"

[[dialogue]]
speaker = "雪女"
# 「フフ。無駄なコトを」
line = "「フフ。無駄なコトを」"

[[dialogue]]
speaker = "雪女"
# 「認めるのです。あれらは冬にしかない、冬だけの醍醐味なのデスよ……！」
line = "「認めるのです。あれらは冬にしかない、冬だけの醍醐味なのデスよ……！」"

[[dialogue]]
speaker = "unk"
# まとめると──
line = "まとめると──"

[[dialogue]]
speaker = "unk"
# 人間界の『冬』を教えてもらったリップルは、その楽しみや醍醐味をエンドレスサマーに取り込もうと考えた。
line = "人間界の『冬』を教えてもらったリップルは、その楽しみや醍醐味をエンドレスサマーに取り込もうと考えた。"

[[dialogue]]
speaker = "unk"
# しかし、その開発が追いつかずにいるうち、結界に『隙間』が生まれてしまった。
line = "しかし、その開発が追いつかずにいるうち、結界に『隙間』が生まれてしまった。"

[[dialogue]]
speaker = "unk"
# 今までのように結界の中で過ごしていたリップルには──芽生えるはずのないエラーなのだった。
line = "今までのように結界の中で過ごしていたリップルには──芽生えるはずのないエラーなのだった。"

[[dialogue]]
speaker = "アナ"
# 「なるほど……急速なリゾートの開発によって、一部でひずみが生じてしまっていたのですね」
line = "「なるほど……急速なリゾートの開発によって、一部でひずみが生じてしまっていたのですね」"

[[dialogue]]
speaker = "アポロ"
# 「んで、その隙間からあのチビが入り込んできたってわけだ！」
line = "「んで、その隙間からあのチビが入り込んできたってわけだ！」"

[[dialogue]]
speaker = "フィオナ"
# 「確かに──リゾート地の急激な開発は、環境破壊をもたらすと言われていますからね」
line = "「確かに──リゾート地の急激な開発は、環境破壊をもたらすと言われていますからね」"

[[dialogue]]
speaker = "ユウリ"
# （んな常識的な理屈が関係あんのか……？）
line = "（んな常識的な理屈が関係あんのか……？）"

[[dialogue]]
speaker = "雪女"
# 「フフ……この調子で結界内に『フユ』をさらに広げるとしまショウ」
line = "「フフ……この調子で結界内に『フユ』をさらに広げるとしまショウ」"

[[dialogue]]
speaker = "雪女"
# 「ソーレ──お雑煮パニックデース！」
line = "「ソーレ──お雑煮パニックデース！」"

[[dialogue]]
speaker = "unk"
# 雪女が羽衣の袖を振りまくと──
line = "雪女が羽衣の袖を振りまくと──"

[[dialogue]]
speaker = "unk"
# 海の家を侵食するように、どでかいお雑煮の化け物が飛び出した！
line = "海の家を侵食するように、どでかいお雑煮の化け物が飛び出した！"

[[dialogue]]
speaker = "リップル"
# 「オー！　夏の風情が台無しデ～ス！」
line = "「オー！　夏の風情が台無しデ～ス！」"

[[dialogue]]
speaker = "雪女"
# 「フッフッフッ……リゾート開発を中止するのデス、リップル。夏におこたやイルミネーションナンテ、到底ジツゲン不可能な夢モノガタリでーす！」
line = "「フッフッフッ……リゾート開発を中止するのデス、リップル。夏におこたやイルミネーションナンテ、到底ジツゲン不可能な夢モノガタリでーす！」"

[[dialogue]]
speaker = "リップル"
# 「く……屈するわけにはイキマセン！　きっと海の家に適したイルミネーションもあるハズなんデス！」
line = "「く……屈するわけにはイキマセン！　きっと海の家に適したイルミネーションもあるハズなんデス！」"

[[dialogue]]
speaker = "リップル"
# 「ゲンカイってヤツは──他人に決められるモノじゃないんデスよ……！」
line = "「ゲンカイってヤツは──他人に決められるモノじゃないんデスよ……！」"

[[dialogue]]
speaker = "ルリエル"
# 「リップルさん……！」
line = "「リップルさん……！」"

[[dialogue]]
speaker = "アナ"
# （まあ、別に冬をそのまま楽しめばいいだけなんですが……）
line = "（まあ、別に冬をそのまま楽しめばいいだけなんですが……）"

[[dialogue]]
speaker = "雪女"
# 「何を言ってもムダなコト。冬の楽しさにひれ伏すがよいでーす！」
line = "「何を言ってもムダなコト。冬の楽しさにひれ伏すがよいでーす！」"
