[[dialogue]]
speaker = "unk"
# 俺たちの他に誰もいない、静寂のアリーナ。そこで、サーシャさんはシズハと向き合っていた――
line = "俺たちの他に誰もいない、静寂のアリーナ。そこで、サーシャさんはシズハと向き合っていた――"

[[dialogue]]
speaker = "サーシャ"
# 「シズハちゃん。私は、あなたのお姉ちゃんにはなれない」
line = "「シズハちゃん。私は、あなたのお姉ちゃんにはなれない」"

[[dialogue]]
speaker = "シズハ"
# 「……どうして？　サーシャさん、前にお姉ちゃんって呼んでいいって、言ってくれたじゃない」
line = "「……どうして？　サーシャさん、前にお姉ちゃんって呼んでいいって、言ってくれたじゃない」"

[[dialogue]]
speaker = "サーシャ"
# 「ええ、確かに言ったわ。だけど……実際にシズハちゃんの『お姉ちゃん』になってみて、間違ってるって気づいたの」
line = "「ええ、確かに言ったわ。だけど……実際にシズハちゃんの『お姉ちゃん』になってみて、間違ってるって気づいたの」"

[[dialogue]]
speaker = "サーシャ"
# 「だから……ごめんなさい。自分の言葉を訂正するわ」
line = "「だから……ごめんなさい。自分の言葉を訂正するわ」"

[[dialogue]]
speaker = "サーシャ"
# 「私はあなたのお姉ちゃんの代わりにはなれない。なっちゃいけない」
line = "「私はあなたのお姉ちゃんの代わりにはなれない。なっちゃいけない」"

[[dialogue]]
speaker = "シズハ"
# 「なんでそんな、冷たいことを言うの……？」
line = "「なんでそんな、冷たいことを言うの……？」"

[[dialogue]]
speaker = "サーシャ"
# 「あなたに忘れて欲しくないから。あなたの――本当のお姉ちゃんのことを」
line = "「あなたに忘れて欲しくないから。あなたの――本当のお姉ちゃんのことを」"

[[dialogue]]
speaker = "シズハ"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "サーシャ"
# 「あの時、私に教えてくれたでしょう？　お姉ちゃんがあなたに残した言葉――」
line = "「あの時、私に教えてくれたでしょう？　お姉ちゃんがあなたに残した言葉――」"

[[dialogue]]
speaker = "unk"
# その日はなんの前触れもなく、突然やってきた。
line = "その日はなんの前触れもなく、突然やってきた。"

[[dialogue]]
speaker = "unk"
# 放課後にお見舞いに来てくれる約束だったお姉ちゃんが交通事故に遭い、病院に運ばれてきたのだった。
line = "放課後にお見舞いに来てくれる約束だったお姉ちゃんが交通事故に遭い、病院に運ばれてきたのだった。"

[[dialogue]]
speaker = "シズハ"
# 「お姉ちゃん……嘘でしょ……お姉ちゃん……なんで、こんな……！」
line = "「お姉ちゃん……嘘でしょ……お姉ちゃん……なんで、こんな……！」"

[[dialogue]]
speaker = "シズハの姉"
# 「ごめん……ごめんね、シズハ」
line = "「ごめん……ごめんね、シズハ」"

[[dialogue]]
speaker = "シズハの姉"
# 「お姉ちゃん……シズハのそばにいるって、約束したのに……守れなくて……」
line = "「お姉ちゃん……シズハのそばにいるって、約束したのに……守れなくて……」"

[[dialogue]]
speaker = "シズハ"
# 「ダメだよ！　死んじゃダメ！　私より先に死んじゃうなんて、そんなのダメ！」
line = "「ダメだよ！　死んじゃダメ！　私より先に死んじゃうなんて、そんなのダメ！」"

[[dialogue]]
speaker = "シズハの姉"
# 「シズハ……よく聞いて……」
line = "「シズハ……よく聞いて……」"

[[dialogue]]
speaker = "シズハの姉"
# 「最後まで……生きるのを諦めないで。私の分も……少しでも長く生きて。どうか――」
line = "「最後まで……生きるのを諦めないで。私の分も……少しでも長く生きて。どうか――」"

[[dialogue]]
speaker = "シズハの姉"
# 「幸せになって……シズハ」
line = "「幸せになって……シズハ」"

[[dialogue]]
speaker = "シズハの姉"
# 「お姉ちゃんからの……最後のお願い……」
line = "「お姉ちゃんからの……最後のお願い……」"

[[dialogue]]
speaker = "シズハ"
# 「お姉ちゃん……？　お姉ちゃん……ねぇ、お姉ちゃんってば……！」
line = "「お姉ちゃん……？　お姉ちゃん……ねぇ、お姉ちゃんってば……！」"

[[dialogue]]
speaker = "シズハ"
# 「嫌だ！　起きてよ！　１人にしないで！」
line = "「嫌だ！　起きてよ！　１人にしないで！」"

[[dialogue]]
speaker = "シズハ"
# 「お姉ちゃん！　お姉ちゃん！！　お姉ちゃんっ！！！」
line = "「お姉ちゃん！　お姉ちゃん！！　お姉ちゃんっ！！！」"

[[dialogue]]
speaker = "シズハ"
# 「うっ……うああああああぁぁぁーーーーーーーーーっ！！！」
line = "「うっ……うああああああぁぁぁーーーーーーーーーっ！！！」"

[[dialogue]]
speaker = "シズハ"
# 「お姉ちゃんっ！！！　ああああああぁぁぁーーーーーーーーーっ！！！」
line = "「お姉ちゃんっ！！！　ああああああぁぁぁーーーーーーーーーっ！！！」"

[[dialogue]]
speaker = "シズハ"
# 「っ……お姉……ちゃん……」
line = "「っ……お姉……ちゃん……」"

[[dialogue]]
speaker = "サーシャ"
# 「……本当のお姉ちゃんが言ったように、シズハちゃんはこれからも生きて、幸せにならなくちゃ。だから、ダメなの」
line = "「……本当のお姉ちゃんが言ったように、シズハちゃんはこれからも生きて、幸せにならなくちゃ。だから、ダメなの」"

[[dialogue]]
speaker = "サーシャ"
# 「あなたのお姉ちゃんはもういない。自分の足で立って、しっかりと前を向いて進まなくちゃダメ」
line = "「あなたのお姉ちゃんはもういない。自分の足で立って、しっかりと前を向いて進まなくちゃダメ」"

[[dialogue]]
speaker = "シズハ"
# 「嫌……私は……！」
line = "「嫌……私は……！」"

[[dialogue]]
speaker = "unk"
# 子供のように、首を強く横に振るシズハ。
line = "子供のように、首を強く横に振るシズハ。"

[[dialogue]]
speaker = "サーシャ"
# 「あなたのお姉ちゃんはもういないの。それは、誰であっても代わりにはなれないわ」
line = "「あなたのお姉ちゃんはもういないの。それは、誰であっても代わりにはなれないわ」"

[[dialogue]]
speaker = "シズハ"
# 「嫌だ……そんなこと言っちゃ嫌だ……！」
line = "「嫌だ……そんなこと言っちゃ嫌だ……！」"

[[dialogue]]
speaker = "シズハ"
# 「――どこにも行かないでよ、お姉ちゃんっ！！！」
line = "「――どこにも行かないでよ、お姉ちゃんっ！！！」"

[[dialogue]]
speaker = "unk"
# シズハがそう叫んだ、次の瞬間。
line = "シズハがそう叫んだ、次の瞬間。"

[[dialogue]]
speaker = "unk"
# 水面に雫が落ちて揺れるように、空間が歪んで行くのがわかった。
line = "水面に雫が落ちて揺れるように、空間が歪んで行くのがわかった。"

[[dialogue]]
speaker = "unk"
# そう、あの『違和感が消えてなくなる修正』がまた起ころうとしていた。
line = "そう、あの『違和感が消えてなくなる修正』がまた起ころうとしていた。"

[[dialogue]]
speaker = "unk"
# しかし――
line = "しかし――"

[[dialogue]]
speaker = "サーシャ"
# 「チェンジ――ノヴァフォーム！」
line = "「チェンジ――ノヴァフォーム！」"

[[dialogue]]
speaker = "シズハ"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "unk"
# 俺たちが再び修正現象に巻き込まれることは、なかった。
line = "俺たちが再び修正現象に巻き込まれることは、なかった。"

[[dialogue]]
speaker = "unk"
# シズハの前に立つサーシャさんの姿は――
line = "シズハの前に立つサーシャさんの姿は――"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「シズハちゃん」
line = "「シズハちゃん」"

[[dialogue]]
speaker = "unk"
# 新たな姿、ノヴァフォームへと覚醒を果たしていたから。
line = "新たな姿、ノヴァフォームへと覚醒を果たしていたから。"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「私は、あなたのお姉ちゃんじゃない」
line = "「私は、あなたのお姉ちゃんじゃない」"

[[dialogue]]
speaker = "シズハ"
# 「どう……して……！？」
line = "「どう……して……！？」"

[[dialogue]]
speaker = "unk"
# シズハと話をしようと教室を出る直前、サーシャさんは言った。
line = "シズハと話をしようと教室を出る直前、サーシャさんは言った。"

[[dialogue]]
speaker = "サーシャ"
# 「会長くん、お願いがあるの。私に……アルケインコードを使ってくれないかしら？」
line = "「会長くん、お願いがあるの。私に……アルケインコードを使ってくれないかしら？」"

[[dialogue]]
speaker = "サーシャ"
# 「私、シズハちゃんを止められる力が欲しいの。自分の大切なものを守れる力を。だから――」
line = "「私、シズハちゃんを止められる力が欲しいの。自分の大切なものを守れる力を。だから――」"

[[dialogue]]
speaker = "サーシャ"
# 「聖杯に勝てる力を、私に頂戴」
line = "「聖杯に勝てる力を、私に頂戴」"

[[dialogue]]
speaker = "unk"
# その時。サーシャさんの中に煌めく、星のような輝きが見えた。
line = "その時。サーシャさんの中に煌めく、星のような輝きが見えた。"

[[dialogue]]
speaker = "unk"
# マトイの時と同じような、新たな星が生まれるような眩しい光が――
line = "マトイの時と同じような、新たな星が生まれるような眩しい光が――"

[[dialogue]]
speaker = "unk"
# ――アルケインノヴァエクストリーム！！
line = "――アルケインノヴァエクストリーム！！"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「――シズハちゃん、聖杯の力はもう発動しないわ」
line = "「――シズハちゃん、聖杯の力はもう発動しないわ」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「私の能力で、<b>凍らせた</b>から」
line = "「私の能力で、<b>凍らせた</b>から」"

[[dialogue]]
speaker = "unk"
# 星騎士の能力は、進化すると物理法則を超えた『概念』にまで、影響を及ぼすこともある。
line = "星騎士の能力は、進化すると物理法則を超えた『概念』にまで、影響を及ぼすこともある。"

[[dialogue]]
speaker = "unk"
# サーシャさんが元々得意としていたのは、『氷』を操る星術。通常フォームの時点でも、学園でトップクラスの使い手であったが……
line = "サーシャさんが元々得意としていたのは、『氷』を操る星術。通常フォームの時点でも、学園でトップクラスの使い手であったが……"

[[dialogue]]
speaker = "unk"
# ノヴァフォームへと進化したことで至ったその力は、名付けるなら『事象凍結』。
line = "ノヴァフォームへと進化したことで至ったその力は、名付けるなら『事象凍結』。"

[[dialogue]]
speaker = "unk"
# それによって、聖杯による修正を封じたのだ。
line = "それによって、聖杯による修正を封じたのだ。"

[[dialogue]]
speaker = "シズハ"
# 「っ…………」
line = "「っ…………」"

[[dialogue]]
speaker = "unk"
# シズハはその場で力が抜けたように、両膝を着く。
line = "シズハはその場で力が抜けたように、両膝を着く。"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「……本当は、私が気づくよりも前から、聖杯の能力が発動していたことに気づいていたのよね？」
line = "「……本当は、私が気づくよりも前から、聖杯の能力が発動していたことに気づいていたのよね？」"

[[dialogue]]
speaker = "シズハ"
# 「……うん。ごめん、なさい……」
line = "「……うん。ごめん、なさい……」"

[[dialogue]]
speaker = "シズハ"
# 「私……聖杯ちゃんと出会った時に、『生きたい』っていう願いを叶えてもらった。でも……」
line = "「私……聖杯ちゃんと出会った時に、『生きたい』っていう願いを叶えてもらった。でも……」"

[[dialogue]]
speaker = "シズハ"
# 「もうひとつ……聖杯ちゃんにだって叶えようのないものだってわかっていて、それでも捨て切れなかった願いもあった……」
line = "「もうひとつ……聖杯ちゃんにだって叶えようのないものだってわかっていて、それでも捨て切れなかった願いもあった……」"

[[dialogue]]
speaker = "シズハ"
# 「叶うなら……お姉ちゃんと、もう１度会いたいって……」
line = "「叶うなら……お姉ちゃんと、もう１度会いたいって……」"

[[dialogue]]
speaker = "シズハ"
# 「サーシャさんと出会ってから、お姉ちゃんが戻って来たみたいで嬉しかった……」
line = "「サーシャさんと出会ってから、お姉ちゃんが戻って来たみたいで嬉しかった……」"

[[dialogue]]
speaker = "シズハ"
# 「私が外を歩けるようになって、病院の外でお姉ちゃんと過ごしたかった日々が、願いが叶ったみたいで……！」
line = "「私が外を歩けるようになって、病院の外でお姉ちゃんと過ごしたかった日々が、願いが叶ったみたいで……！」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「私が指摘しなかったとしても、あなたはいつか必ず、自分自身の欺瞞に気づくわ。シズハちゃんは賢いから……」
line = "「私が指摘しなかったとしても、あなたはいつか必ず、自分自身の欺瞞に気づくわ。シズハちゃんは賢いから……」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「そうなった時、あなたは本当の姉を自分で消し去ったことを許せなくなる」
line = "「そうなった時、あなたは本当の姉を自分で消し去ったことを許せなくなる」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「それは、シズハちゃんのお姉ちゃんが願った『幸せ』からは程遠い。だから……」
line = "「それは、シズハちゃんのお姉ちゃんが願った『幸せ』からは程遠い。だから……」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「……私はあなたのお姉ちゃんには、ならない」
line = "「……私はあなたのお姉ちゃんには、ならない」"

[[dialogue]]
speaker = "シズハ"
# 「サーシャ、さん……」
line = "「サーシャ、さん……」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「でも――」
line = "「でも――」"

[[dialogue]]
speaker = "unk"
# サーシャさんはシズハに歩み寄ると、その体をそっと抱き締めた。
line = "サーシャさんはシズハに歩み寄ると、その体をそっと抱き締めた。"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「あなたが寂しくなった時は、こうして寄り添ってあげたいと思う」
line = "「あなたが寂しくなった時は、こうして寄り添ってあげたいと思う」"

[[dialogue]]
speaker = "シズハ"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「だって、せっかく仲良くなったんだもの」
line = "「だって、せっかく仲良くなったんだもの」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「年上の『お姉さん』として優しくする分には、別に何の問題もないでしょう？」
line = "「年上の『お姉さん』として優しくする分には、別に何の問題もないでしょう？」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「あなたは私の、可愛い後輩なんだから」
line = "「あなたは私の、可愛い後輩なんだから」"

[[dialogue]]
speaker = "unk"
# そう言って優しく、シズハの頭を撫でる。
line = "そう言って優しく、シズハの頭を撫でる。"

[[dialogue]]
speaker = "シズハ"
# 「サーシャさん……」
line = "「サーシャさん……」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「ね、シズハちゃん。もう１度、ここから私と仲良くしてくれるかしら？」
line = "「ね、シズハちゃん。もう１度、ここから私と仲良くしてくれるかしら？」"

[[dialogue]]
speaker = "シズハ"
# 「はい……はい……！　だって私……」
line = "「はい……はい……！　だって私……」"

[[dialogue]]
speaker = "シズハ"
# 「サーシャさんのこと、大好きですから……！」
line = "「サーシャさんのこと、大好きですから……！」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「ありがとう。私もよ」
line = "「ありがとう。私もよ」"

[[dialogue]]
speaker = "unk"
# そうして、２人は嬉しそうに、しばらく抱き合うのだった――
line = "そうして、２人は嬉しそうに、しばらく抱き合うのだった――"

[[dialogue]]
speaker = "unk"
# それから、シズハが落ち着いた後。
line = "それから、シズハが落ち着いた後。"

[[dialogue]]
speaker = "unk"
# サーシャさんの手を取って立ち上がり、彼女は照れ臭そうな笑顔を浮かべてみせた。
line = "サーシャさんの手を取って立ち上がり、彼女は照れ臭そうな笑顔を浮かべてみせた。"

[[dialogue]]
speaker = "シズハ"
# 「その……サーシャさん、会長、なんか……色々とご迷惑をお掛けしました」
line = "「その……サーシャさん、会長、なんか……色々とご迷惑をお掛けしました」"

[[dialogue]]
speaker = "unk"
# いいさ。こういうのはお互い様だよ
line = "いいさ。こういうのはお互い様だよ"

[[dialogue]]
speaker = "シズハ"
# 「ありがとう。会長」
line = "「ありがとう。会長」"

[[dialogue]]
speaker = "ディーラック"
# 「ひひっ♪　シズハちゃん、元気になったみたいでよかったね～」
line = "「ひひっ♪　シズハちゃん、元気になったみたいでよかったね～」"

[[dialogue]]
speaker = "シズハ"
# 「うん！　もう大丈夫！　ここからは私、名誉挽回で頑張るよ！」
line = "「うん！　もう大丈夫！　ここからは私、名誉挽回で頑張るよ！」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「あとは『解放』のロストアイテムを回収するだけね」
line = "「あとは『解放』のロストアイテムを回収するだけね」"

[[dialogue]]
speaker = "サチ"
# 「いえ、それについてはもう既に回収済です」
line = "「いえ、それについてはもう既に回収済です」"

[[dialogue]]
speaker = "シズハ"
# 「サチちゃん！　プリムラちゃんも！」
line = "「サチちゃん！　プリムラちゃんも！」"

[[dialogue]]
speaker = "プリムラ"
# 「おう。どうやらそっちも、知らぬ間に色々あったようじゃな」
line = "「おう。どうやらそっちも、知らぬ間に色々あったようじゃな」"

[[dialogue]]
speaker = "シズハ"
# 「ロストアイテムを２人が回収したなら、今回は、これにて一件落着ってことでいいのかな？」
line = "「ロストアイテムを２人が回収したなら、今回は、これにて一件落着ってことでいいのかな？」"

[[dialogue]]
speaker = "サチ"
# 「いいえ。残念ながら、まだ終わりではありません」
line = "「いいえ。残念ながら、まだ終わりではありません」"

[[dialogue]]
speaker = "サーシャ（覚醒）"
# 「あら？　それってどういう……？」
line = "「あら？　それってどういう……？」"

[[dialogue]]
speaker = "サチ"
# 「シズハちゃんの聖杯が暴走していたのは――『解放』のロストアイテムが原因ではないからです」
line = "「シズハちゃんの聖杯が暴走していたのは――『解放』のロストアイテムが原因ではないからです」"

[[dialogue]]
speaker = "unk"
# サチは俺たちにそう告げるのだった――
line = "サチは俺たちにそう告げるのだった――"
