[[dialogue]]
speaker = "マグダレナ"
# 『星霊祭も３日目に突入です。ここまでは新星学園リードで進んでいますが、結果はまだまだわかりません。逆転の機会はたくさんありますよ』
line = "『星霊祭も３日目に突入です。ここまでは新星学園リードで進んでいますが、結果はまだまだわかりません。逆転の機会はたくさんありますよ』"

[[dialogue]]
speaker = "カティア"
# 「ふふーん、１日目、２日目と連続で新星の優勢！　このまま最後まで完封もありえるワン♪」
line = "「ふふーん、１日目、２日目と連続で新星の優勢！　このまま最後まで完封もありえるワン♪」"

[[dialogue]]
speaker = "ミルフィー"
# 「カティアちゃん、油断は禁物だよ！　勝って兜の緒を締めよなんだから！」
line = "「カティアちゃん、油断は禁物だよ！　勝って兜の緒を締めよなんだから！」"

[[dialogue]]
speaker = "美鶴"
# 「次の競技は、大玉転がしだってさ。運動会って、ほんとにいろんな競技があるんだねー」
line = "「次の競技は、大玉転がしだってさ。運動会って、ほんとにいろんな競技があるんだねー」"

[[dialogue]]
speaker = "シノ"
# 『こちらの大玉を先にゴールまで運んだほうが勝利！　いたってシンプルなルールです』
line = "『こちらの大玉を先にゴールまで運んだほうが勝利！　いたってシンプルなルールです』"

[[dialogue]]
speaker = "カティア"
# 「わふんっ！　玉を転がすなら、私にお任せあれだワン！」
line = "「わふんっ！　玉を転がすなら、私にお任せあれだワン！」"

[[dialogue]]
speaker = "ヒヨ"
# 「ワン公はボールを転がしたり、取って来いするのが上手いからなあ。適材適所ってヤツかい」
line = "「ワン公はボールを転がしたり、取って来いするのが上手いからなあ。適材適所ってヤツかい」"

[[dialogue]]
speaker = "unk"
# よし、行ってこい。カティア！
line = "よし、行ってこい。カティア！"

[[dialogue]]
speaker = "カティア"
# 「行ってきます、魔王様っ！　必ずやお役に立ってみせますワン！」
line = "「行ってきます、魔王様っ！　必ずやお役に立ってみせますワン！」"

[[dialogue]]
speaker = "ミルフィー"
# 「頑張ってね、カティアちゃん！　ゴー・ファイト・ウィン！」
line = "「頑張ってね、カティアちゃん！　ゴー・ファイト・ウィン！」"

[[dialogue]]
speaker = "マグダレナ"
# 『新星学園からはカティアさん、流星学園からはフェニエルさんが出走です。位置についてくださーい！』
line = "『新星学園からはカティアさん、流星学園からはフェニエルさんが出走です。位置についてくださーい！』"

[[dialogue]]
speaker = "フェニエル"
# 「よ、よろしくお願いします」
line = "「よ、よろしくお願いします」"

[[dialogue]]
speaker = "カティア"
# 「ちっちゃいけど、油断も手加減もしません！　絶対負けないワン！」
line = "「ちっちゃいけど、油断も手加減もしません！　絶対負けないワン！」"

[[dialogue]]
speaker = "シノ"
# 『位置について──よーーーい、ドン！』
line = "『位置について──よーーーい、ドン！』"

[[dialogue]]
speaker = "カティア"
# 「一気に転がして──えいっ！　んぬっ！？　んぬぐぎぎぎぎぎぎ！？」
line = "「一気に転がして──えいっ！　んぬっ！？　んぬぐぎぎぎぎぎぎ！？」"

[[dialogue]]
speaker = "美鶴"
# 「大玉、ビクともしてないね」
line = "「大玉、ビクともしてないね」"

[[dialogue]]
speaker = "ミルフィー"
# 「今までの競技からすると、あの大玉もきっと普通のじゃないんだろうね……」
line = "「今までの競技からすると、あの大玉もきっと普通のじゃないんだろうね……」"

[[dialogue]]
speaker = "マグダレナ"
# 『当然、こちらも星騎士仕様の競技、普通の大玉転がしで終わるはずがありません。こちらの大玉鉄球の重量、なんと１０ｔです』
line = "『当然、こちらも星騎士仕様の競技、普通の大玉転がしで終わるはずがありません。こちらの大玉鉄球の重量、なんと１０ｔです』"

[[dialogue]]
speaker = "unk"
# 後出し情報だー！？
line = "後出し情報だー！？"

[[dialogue]]
speaker = "unk"
# １０ｔの鉄球！？
line = "１０ｔの鉄球！？"

[[dialogue]]
speaker = "ヒヨ"
# 「１０ｔだとぉ！？　ただでさえ非力なワン公が、そんなん動かせるわけねえ！」
line = "「１０ｔだとぉ！？　ただでさえ非力なワン公が、そんなん動かせるわけねえ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「しかも、カティアちゃんの簡易戦闘服は、スピードに特化してるから……今の筋力は一般人と大差ないんじゃないかな」
line = "「しかも、カティアちゃんの簡易戦闘服は、スピードに特化してるから……今の筋力は一般人と大差ないんじゃないかな」"

[[dialogue]]
speaker = "美鶴"
# 「でも、１０ｔなんて流星の天使ちゃんも動かせないんじゃない？　泥仕合になりそ」
line = "「でも、１０ｔなんて流星の天使ちゃんも動かせないんじゃない？　泥仕合になりそ」"

[[dialogue]]
speaker = "ミルフィー"
# 「うーん、それはどうかなー……」
line = "「うーん、それはどうかなー……」"

[[dialogue]]
speaker = "フェニエル"
# 「んっしょ、んっしょ、んっしょ」
line = "「んっしょ、んっしょ、んっしょ」"

[[dialogue]]
speaker = "美鶴"
# 「うへ。天使ちゃん、平気な顔ですいすい転がしてる……細い身体でとんでもない馬鹿力」
line = "「うへ。天使ちゃん、平気な顔ですいすい転がしてる……細い身体でとんでもない馬鹿力」"

[[dialogue]]
speaker = "ミルフィー"
# 「見た目で判断すると、痛い目を見るっていういい例だね……」
line = "「見た目で判断すると、痛い目を見るっていういい例だね……」"

[[dialogue]]
speaker = "unk"
# フニは特別力持ちだから……
line = "フニは特別力持ちだから……"

[[dialogue]]
speaker = "カティア"
# 「そんなー！　ま、まだまだ負けてないワン！　ゴールするまでが運動会だガオ！　ぐぬぎぎぎぎぎぃ！」
line = "「そんなー！　ま、まだまだ負けてないワン！　ゴールするまでが運動会だガオ！　ぐぬぎぎぎぎぎぃ！」"

[[dialogue]]
speaker = "ヒヨ"
# 「あ、諦めんな、ワン公っ！　為せば成るでえ！」
line = "「あ、諦めんな、ワン公っ！　為せば成るでえ！」"

[[dialogue]]
speaker = "unk"
# 大汗をかきつつ、額に血管を浮かべ、押したり引いたりを繰り返すカティアだったが、その頑張りも虚しく──
line = "大汗をかきつつ、額に血管を浮かべ、押したり引いたりを繰り返すカティアだったが、その頑張りも虚しく──"

[[dialogue]]
speaker = "フェニエル"
# 「んっしょ、んっしょ……あ、ゴールです。やりました♪」
line = "「んっしょ、んっしょ……あ、ゴールです。やりました♪」"

[[dialogue]]
speaker = "シノ"
# 『細腕に秘められた無限のパワーで、フェニエル選手ゴールイン！』
line = "『細腕に秘められた無限のパワーで、フェニエル選手ゴールイン！』"

[[dialogue]]
speaker = "ミネコ"
# 「やったー♪　１本取り返したね！」
line = "「やったー♪　１本取り返したね！」"

[[dialogue]]
speaker = "フェニエル"
# 「えへへ、皆さん、応援ありがとうございます」
line = "「えへへ、皆さん、応援ありがとうございます」"

[[dialogue]]
speaker = "マグダレナ"
# 『一方、カティア選手の押す大玉は……スタート地点からほとんど動いておりません』
line = "『一方、カティア選手の押す大玉は……スタート地点からほとんど動いておりません』"

[[dialogue]]
speaker = "ヒヨ"
# 「何やってやがんでえ──って責めるのは酷ってもんか。あんなのあたしでもきちぃぜ」
line = "「何やってやがんでえ──って責めるのは酷ってもんか。あんなのあたしでもきちぃぜ」"

[[dialogue]]
speaker = "カティア"
# 「ウワーーン！　みんなに合わす顔がないワーーーン！」
line = "「ウワーーン！　みんなに合わす顔がないワーーーン！」"

[[dialogue]]
speaker = "フェニエル"
# 「あ、あのあの、気を落とさないでください……勝負は時の運って言いますし……」
line = "「あ、あのあの、気を落とさないでください……勝負は時の運って言いますし……」"

[[dialogue]]
speaker = "カティア"
# 「対戦相手に慰められるなんて、もっと惨めだワーン！」
line = "「対戦相手に慰められるなんて、もっと惨めだワーン！」"

[[dialogue]]
speaker = "フェニエル"
# 「ご、ご、ごめんなさーい！」
line = "「ご、ご、ごめんなさーい！」"

[[dialogue]]
speaker = "unk"
# 他の参加選手も流星学園に後れを取ってしまい、大玉転がしは完敗を喫してしまったのだった。
line = "他の参加選手も流星学園に後れを取ってしまい、大玉転がしは完敗を喫してしまったのだった。"
