[[dialogue]]
speaker = "unk"
# 『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』との決戦から数日。星騎士たちが激戦の疲れを癒す傍ら、ネビュラは慌ただしく活動していた。
line = "『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』との決戦から数日。星騎士たちが激戦の疲れを癒す傍ら、ネビュラは慌ただしく活動していた。"

[[dialogue]]
speaker = "unk"
# 元凶である『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』を倒したことで、リクリエのない世界は実現された。
line = "元凶である『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』を倒したことで、リクリエのない世界は実現された。"

[[dialogue]]
speaker = "unk"
# 同時に世界はこれまでにない新しい段階に至った。この先何が起こるかは未知数であり、その調査で魔女たちは三界を駆け回っているのだ。
line = "同時に世界はこれまでにない新しい段階に至った。この先何が起こるかは未知数であり、その調査で魔女たちは三界を駆け回っているのだ。"

[[dialogue]]
speaker = "unk"
# それは当然、ネビュラに身を預ける彼女たちコラプサーも例外ではない。
line = "それは当然、ネビュラに身を預ける彼女たちコラプサーも例外ではない。"

[[dialogue]]
speaker = "イニシュ"
# 「極星学園の流星市国襲撃、天界防衛、『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』との戦い等々、先の戦闘ではお疲れ様でした」
line = "「極星学園の流星市国襲撃、天界防衛、『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』との戦い等々、先の戦闘ではお疲れ様でした」"

[[dialogue]]
speaker = "イニシュ"
# 「今は休息を、と言いたいところですが、我々にはやるべきことがあります。──次の任務です」
line = "「今は休息を、と言いたいところですが、我々にはやるべきことがあります。──次の任務です」"

[[dialogue]]
speaker = "レイラ"
# （うぅ、イニシュさん、容赦ない……）
line = "（うぅ、イニシュさん、容赦ない……）"

[[dialogue]]
speaker = "レイラ"
# （私たちコラプサーは、かつて星騎士の敵だったところを、ネビュラに戦闘員として拾ってもらった。だから仕方ないとは思うけど……）
line = "（私たちコラプサーは、かつて星騎士の敵だったところを、ネビュラに戦闘員として拾ってもらった。だから仕方ないとは思うけど……）"

[[dialogue]]
speaker = "イニシュ"
# 「任務内容は魔界の調査。マップを立体映像に表示します」
line = "「任務内容は魔界の調査。マップを立体映像に表示します」"

[[dialogue]]
speaker = "レイラ"
# 「ここは……魔界にいた時に聞いたことがあります。魔界の貴族に古くから愛されるリゾート地だとか」
line = "「ここは……魔界にいた時に聞いたことがあります。魔界の貴族に古くから愛されるリゾート地だとか」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「そうそう、いいとこなんだよね～。だけどこの地点で不自然な空間の歪みが観測されてさ、コラプサーにはその調査にあたってもらいたいんだ」
line = "「そうそう、いいとこなんだよね～。だけどこの地点で不自然な空間の歪みが観測されてさ、コラプサーにはその調査にあたってもらいたいんだ」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「それじゃメンバー発表の前に……はい、レイラたちにアタシからプレゼント！」
line = "「それじゃメンバー発表の前に……はい、レイラたちにアタシからプレゼント！」"

[[dialogue]]
speaker = "レイラ"
# 「これは……水着、ですか？」
line = "「これは……水着、ですか？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「ザッツライト！　ネビュラ版水着戦闘服第２弾だよ。まぁ魔力じゃなくて星力稼働だから、正確にはネビュラ版ていうより再現版というべきかな？」
line = "「ザッツライト！　ネビュラ版水着戦闘服第２弾だよ。まぁ魔力じゃなくて星力稼働だから、正確にはネビュラ版ていうより再現版というべきかな？」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「まぁ細かいことは置いといて、これ着ていってね～。一度着れば戦闘服として変身できるようになるから」
line = "「まぁ細かいことは置いといて、これ着ていってね～。一度着れば戦闘服として変身できるようになるから」"

[[dialogue]]
speaker = "イニシュ"
# 「今回の任務は人工戦闘服のテストも兼ねています。よって、メンバーは戦闘服が完成したレイラ、キサナ、リーナ、イングリットの４名です」
line = "「今回の任務は人工戦闘服のテストも兼ねています。よって、メンバーは戦闘服が完成したレイラ、キサナ、リーナ、イングリットの４名です」"

[[dialogue]]
speaker = "イニシュ"
# 「……これは捕捉ですが。今回の任務はあくまで調査です。必要なデータを取り終えたら自由行動でも構いません」
line = "「……これは捕捉ですが。今回の任務はあくまで調査です。必要なデータを取り終えたら自由行動でも構いません」"

[[dialogue]]
speaker = "レイラ"
# 「つまり、海でバカンス……ってコト！？」
line = "「つまり、海でバカンス……ってコト！？」"

[[dialogue]]
speaker = "イニシュ"
# 「そうは言っていません。任務は確実に遂行してください」
line = "「そうは言っていません。任務は確実に遂行してください」"

[[dialogue]]
speaker = "レイラ"
# 「は、はい。失礼しました」
line = "「は、はい。失礼しました」"

[[dialogue]]
speaker = "ツェツィーリエ"
# 「まぁまぁ、上官からはそう言うしかないからさ。あ、でも戦闘服のレポートはしっかりね？」
line = "「まぁまぁ、上官からはそう言うしかないからさ。あ、でも戦闘服のレポートはしっかりね？」"

[[dialogue]]
speaker = "レイラ"
# 「はい、かしこまりました」
line = "「はい、かしこまりました」"

[[dialogue]]
speaker = "イニシュ"
# 「では、出発は明日です。速やかに準備を」
line = "「では、出発は明日です。速やかに準備を」"

[[dialogue]]
speaker = "レイラ"
# 「というわけで海でバカンスだよ！　ドンドンパフパフ～！」
line = "「というわけで海でバカンスだよ！　ドンドンパフパフ～！」"

[[dialogue]]
speaker = "リーナ"
# 「やったー！　リーナ、スイカ割りしたい！」
line = "「やったー！　リーナ、スイカ割りしたい！」"

[[dialogue]]
speaker = "キサナ"
# 「いや、仕事だっつってんだろ」
line = "「いや、仕事だっつってんだろ」"

[[dialogue]]
speaker = "イングリット"
# 「ふん……」
line = "「ふん……」"

[[dialogue]]
speaker = "メテオラ"
# 「いってらっしゃいだぞ！」
line = "「いってらっしゃいだぞ！」"

[[dialogue]]
speaker = "リーナ"
# 「お土産いっぱい持って帰ってくるね！　ヒトデとかキレイな貝殻とか！」
line = "「お土産いっぱい持って帰ってくるね！　ヒトデとかキレイな貝殻とか！」"

[[dialogue]]
speaker = "メテオラ"
# 「おー、楽しみにしてるぞ！　……ヒトデってなんだー？」
line = "「おー、楽しみにしてるぞ！　……ヒトデってなんだー？」"

[[dialogue]]
speaker = "レイラ"
# 「ごめんね、私たちだけでバカンスなんて」
line = "「ごめんね、私たちだけでバカンスなんて」"

[[dialogue]]
speaker = "エンジュ"
# 「いいよ、あたしは暑いの苦手だし……って任務だからな？　ホントに分かってるのか？」
line = "「いいよ、あたしは暑いの苦手だし……って任務だからな？　ホントに分かってるのか？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「行ってらっしゃいませ。ゆっくりしてきてくださいまし」
line = "「行ってらっしゃいませ。ゆっくりしてきてくださいまし」"

[[dialogue]]
speaker = "ジュリエッテ"
# （これでしばらくはイングリット様に振り回されないで済みますわ。というか、もう帰ってこなくて結構でございますわ～！）
line = "（これでしばらくはイングリット様に振り回されないで済みますわ。というか、もう帰ってこなくて結構でございますわ～！）"

[[dialogue]]
speaker = "レイラ"
# 「ヴァレリー、みんなのことお願いね。あ、でも、女の子をいやらしい目でジロジロ見ないこと。ひとりで美術品に近付くのも禁止だからね」
line = "「ヴァレリー、みんなのことお願いね。あ、でも、女の子をいやらしい目でジロジロ見ないこと。ひとりで美術品に近付くのも禁止だからね」"

[[dialogue]]
speaker = "ヴァレリー"
# 「おやおや、信用がありませんね。まぁ日頃の行いが行いだけに反論はできませんが。フフフ」
line = "「おやおや、信用がありませんね。まぁ日頃の行いが行いだけに反論はできませんが。フフフ」"

[[dialogue]]
speaker = "レイラ"
# 「いや、笑いごとじゃないんだけど。何かあったら怒られるの私なんだよ！」
line = "「いや、笑いごとじゃないんだけど。何かあったら怒られるの私なんだよ！」"

[[dialogue]]
speaker = "レイラ"
# （いつもと変わらず賑やかだけど……みんなとこうしていられるのは、あとどれくらいなんだろう）
line = "（いつもと変わらず賑やかだけど……みんなとこうしていられるのは、あとどれくらいなんだろう）"

[[dialogue]]
speaker = "レイラ"
# （私たちコラプサーの目的は世界を救うこと。それは今でも変わらない。でも本当に救ってしまったら……リクリエがなくなったら、私たちは……）
line = "（私たちコラプサーの目的は世界を救うこと。それは今でも変わらない。でも本当に救ってしまったら……リクリエがなくなったら、私たちは……）"

[[dialogue]]
speaker = "キサナ"
# 「おい、下向いてんじゃねえ。コラプサーの<ruby=ボス>首領</ruby>はお前だろ」
line = "「おい、下向いてんじゃねえ。コラプサーの<ruby>首領<rt>ボス</rt></ruby>はお前だろ」"

[[dialogue]]
speaker = "レイラ"
# 「……ごめん、ちょっと考え事してて。ありがとう、キサナ」
line = "「……ごめん、ちょっと考え事してて。ありがとう、キサナ」"

[[dialogue]]
speaker = "レイラ"
# 「では、改めて……コラプサー４名、バカンスに出撃！」
line = "「では、改めて……コラプサー４名、バカンスに出撃！」"

[[dialogue]]
speaker = "エンジュ"
# 「ああ、行ってらっしゃい……ってやっぱ分かってないだろお前！」
line = "「ああ、行ってらっしゃい……ってやっぱ分かってないだろお前！」"
