[[dialogue]]
speaker = "ナミエル"
# 「フィオナお嬢様にお掃除を指導するなど、畏れ多いのですが……本当に良いのでしょうか？」
line = "「フィオナお嬢様にお掃除を指導するなど、畏れ多いのですが……本当に良いのでしょうか？」"

[[dialogue]]
speaker = "フィオナ"
# 「いいの、私がやりたいことなんだから。それに、教皇の娘だからって、ちゃんと掃除もできなかったら恥ずかしいでしょう？」
line = "「いいの、私がやりたいことなんだから。それに、教皇の娘だからって、ちゃんと掃除もできなかったら恥ずかしいでしょう？」"

[[dialogue]]
speaker = "フィオナ"
# 「というわけで、今はナミエルが師匠だよ。掃除ならキリカにも負けないんだから」
line = "「というわけで、今はナミエルが師匠だよ。掃除ならキリカにも負けないんだから」"

[[dialogue]]
speaker = "ナミエル"
# 「かしこまりました。では今日ばかりは遠慮なく指導させていただきます」
line = "「かしこまりました。では今日ばかりは遠慮なく指導させていただきます」"

[[dialogue]]
speaker = "ナミエル"
# 「フィオナお嬢様、質問です。この部屋を全体的に掃除する場合、どこから始めるべきでしょうか」
line = "「フィオナお嬢様、質問です。この部屋を全体的に掃除する場合、どこから始めるべきでしょうか」"

[[dialogue]]
speaker = "フィオナ"
# 「それは……窓とか？」
line = "「それは……窓とか？」"

[[dialogue]]
speaker = "ナミエル"
# 「正解は天井です。一見すると綺麗に見える天井ですが、実は汚れが溜まっています」
line = "「正解は天井です。一見すると綺麗に見える天井ですが、実は汚れが溜まっています」"

[[dialogue]]
speaker = "ナミエル"
# 「また天井を先にしないと、落ちてきた埃などで、掃除した場所が汚れてしまいますから。<ruby=ほこり>埃</ruby>を取る時は、上から下へ、奥から手前へ、が基本です」
line = "「また天井を先にしないと、落ちてきた埃などで、掃除した場所が汚れてしまいますから。<ruby>埃<rt>ほこり</rt></ruby>を取る時は、上から下へ、奥から手前へ、が基本です」"

[[dialogue]]
speaker = "フィオナ"
# 「なるほど……。じゃあ天井はどうやって掃除すればいいの？」
line = "「なるほど……。じゃあ天井はどうやって掃除すればいいの？」"

[[dialogue]]
speaker = "ナミエル"
# 「リビングであれば、主な汚れは埃ですので、はたきで落としたり、フローリング用のワイパーで拭いていきます」
line = "「リビングであれば、主な汚れは埃ですので、はたきで落としたり、フローリング用のワイパーで拭いていきます」"

[[dialogue]]
speaker = "ナミエル"
# 「ただしキッチンですと油汚れもあります。こちらはアルカリ性の洗剤が有効です」
line = "「ただしキッチンですと油汚れもあります。こちらはアルカリ性の洗剤が有効です」"

[[dialogue]]
speaker = "トワ先生"
# 「ふむふむ、なるほど……」
line = "「ふむふむ、なるほど……」"

[[dialogue]]
speaker = "unk"
# トワちゃんは何してるの？
line = "トワちゃんは何してるの？"

[[dialogue]]
speaker = "トワ先生"
# 「いや～、私も今後のために花嫁力を上げておこうと思って」
line = "「いや～、私も今後のために花嫁力を上げておこうと思って」"

[[dialogue]]
speaker = "トワ先生"
# 「星見家メイド隊のお掃除術は勉強になるなぁ～。今度マリオンにも教えてもらおうかな？」
line = "「星見家メイド隊のお掃除術は勉強になるなぁ～。今度マリオンにも教えてもらおうかな？」"

[[dialogue]]
speaker = "ナミエル"
# 「では実際に天井の掃除を始めていきましょう。まずは天井から落ちた埃で床や家具が汚れないよう、新聞紙を敷いていきます。埃が舞うのでマスクも忘れないでくださいね」
line = "「では実際に天井の掃除を始めていきましょう。まずは天井から落ちた埃で床や家具が汚れないよう、新聞紙を敷いていきます。埃が舞うのでマスクも忘れないでくださいね」"

[[dialogue]]
speaker = "フィオナ"
# 「うん、新聞紙を敷いて……と。じゃあ、ワイパーで天井の埃を拭いて……あ、でもけっこう天井が高いから届かないな……。緋宮会長、脚立ってありますか？」
line = "「うん、新聞紙を敷いて……と。じゃあ、ワイパーで天井の埃を拭いて……あ、でもけっこう天井が高いから届かないな……。緋宮会長、脚立ってありますか？」"

[[dialogue]]
speaker = "フィオナ"
# 「ありがとうございます。これで届きますね」
line = "「ありがとうございます。これで届きますね」"

[[dialogue]]
speaker = "unk"
# （スリットから太ももがチラチラと……）
line = "（スリットから太ももがチラチラと……）"

[[dialogue]]
speaker = "ナミエル"
# 「緋宮会長、視線がいやらしいですよ」
line = "「緋宮会長、視線がいやらしいですよ」"

[[dialogue]]
speaker = "フィオナ"
# 「え！？　私、どこかはしたないですか！？」
line = "「え！？　私、どこかはしたないですか！？」"

[[dialogue]]
speaker = "ナミエル"
# 「いえ、懸命に花嫁修業をされているフィオナお嬢様を、<ruby=ふらち>不埒</ruby>な目で見る緋宮会長がいけないのです」
line = "「いえ、懸命に花嫁修業をされているフィオナお嬢様を、<ruby>不埒<rt>ふらち</rt></ruby>な目で見る緋宮会長がいけないのです」"

[[dialogue]]
speaker = "unk"
# （ナミエルの視線が痛い……）
line = "（ナミエルの視線が痛い……）"

[[dialogue]]
speaker = "フィオナ"
# 「も、もう、ナミエルってば……。その、緋宮会長？　あんまり足やお尻ばっかり見ないでくださいね……？」
line = "「も、もう、ナミエルってば……。その、緋宮会長？　あんまり足やお尻ばっかり見ないでくださいね……？」"

[[dialogue]]
speaker = "unk"
# 俺も手伝った方が……
line = "俺も手伝った方が……"

[[dialogue]]
speaker = "キリカ"
# 「いえ、時には見守ることも必要です。ナミエルだって、本当は自分で掃除したいのを我慢しているのですから」
line = "「いえ、時には見守ることも必要です。ナミエルだって、本当は自分で掃除したいのを我慢しているのですから」"

[[dialogue]]
speaker = "ナミエル"
# 「うぅ……」
line = "「うぅ……」"

[[dialogue]]
speaker = "フィオナ"
# 「ありがとう、ナミエル。でも大丈夫だよ」
line = "「ありがとう、ナミエル。でも大丈夫だよ」"

[[dialogue]]
speaker = "フィオナ"
# 「ここは私と緋宮会長の家で、自分たちが暮らす家を、自分で掃除するのは当たり前のことなんだから」
line = "「ここは私と緋宮会長の家で、自分たちが暮らす家を、自分で掃除するのは当たり前のことなんだから」"

[[dialogue]]
speaker = "フィオナ"
# 「だから掃除のこといっぱい教えて、ナミエル。好きな人と過ごす場所を、自分の手で綺麗にしたいの」
line = "「だから掃除のこといっぱい教えて、ナミエル。好きな人と過ごす場所を、自分の手で綺麗にしたいの」"

[[dialogue]]
speaker = "ナミエル"
# 「はい！　お任せください！」
line = "「はい！　お任せください！」"

[[dialogue]]
speaker = "フィオナ"
# 「ふぅ、終わりました」
line = "「ふぅ、終わりました」"

[[dialogue]]
speaker = "ナミエル"
# 「お疲れ様でした。天井から床までピカピカです」
line = "「お疲れ様でした。天井から床までピカピカです」"

[[dialogue]]
speaker = "unk"
# 本当に綺麗になった！
line = "本当に綺麗になった！"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ、ありがとうございます」
line = "「ふふ、ありがとうございます」"

[[dialogue]]
speaker = "フィオナ"
# 「まだまだ至らないところはありますけど、花嫁修業で少し自信がつきました。今なら式を挙げられる気がします！」
line = "「まだまだ至らないところはありますけど、花嫁修業で少し自信がつきました。今なら式を挙げられる気がします！」"

[[dialogue]]
speaker = "unk"
# 翌日──
line = "翌日──"

[[dialogue]]
speaker = "イレーナ"
# 「星見フィオナ。あなたは永遠の愛を誓いますか？」
line = "「星見フィオナ。あなたは永遠の愛を誓いますか？」"

[[dialogue]]
speaker = "フィオナ"
# 「……はい、誓います」
line = "「……はい、誓います」"

[[dialogue]]
speaker = "フィオナ"
# 「不思議と、前に誓った時よりも晴れやかな気持ちです。今度こそ元の戦闘服に──」
line = "「不思議と、前に誓った時よりも晴れやかな気持ちです。今度こそ元の戦闘服に──」"

[[dialogue]]
speaker = "フィオナ"
# 「あれ、戻らない？」
line = "「あれ、戻らない？」"

[[dialogue]]
speaker = "ナミエル"
# 「私もウェディングドレスのままです。トワ先生の見立てが間違っている可能性もあるのではないでしょうか？」
line = "「私もウェディングドレスのままです。トワ先生の見立てが間違っている可能性もあるのではないでしょうか？」"

[[dialogue]]
speaker = "トワ先生"
# 「うーん、過去の事例から考えても、そんなことないと思うんだけどな。まだフィオナちゃんが満足できてないのかも」
line = "「うーん、過去の事例から考えても、そんなことないと思うんだけどな。まだフィオナちゃんが満足できてないのかも」"

[[dialogue]]
speaker = "フィオナ"
# 「私が満足していない……？　十分、花嫁になったつもりだったんですけど……」
line = "「私が満足していない……？　十分、花嫁になったつもりだったんですけど……」"

[[dialogue]]
speaker = "キリカ"
# 「以前はお嬢様の花嫁力が足りませんでした。ですが今はそれに見合う、緋宮会長の花婿力が伴っていないのかと」
line = "「以前はお嬢様の花嫁力が足りませんでした。ですが今はそれに見合う、緋宮会長の花婿力が伴っていないのかと」"

[[dialogue]]
speaker = "unk"
# 花婿力！？
line = "花婿力！？"

[[dialogue]]
speaker = "キリカ"
# 「ですので──」
line = "「ですので──」"

[[dialogue]]
speaker = "キリカ"
# 「緋宮会長の花婿修行を開始します！」
line = "「緋宮会長の花婿修行を開始します！」"
