[[dialogue]]
speaker = "エルデリーゼ"
# （ラティエ学園長様の噂は以前より聞いていましたわ）
line = "（ラティエ学園長様の噂は以前より聞いていましたわ）"

[[dialogue]]
speaker = "エルデリーゼ"
# （その噂は決して良いものではありませんでした）
line = "（その噂は決して良いものではありませんでした）"

[[dialogue]]
speaker = "エルデリーゼ"
# （学園長でありながらその職務を投げ出して世界各地を旅していて、そのしわ寄せをフィオナ会長が受けている……）
line = "（学園長でありながらその職務を投げ出して世界各地を旅していて、そのしわ寄せをフィオナ会長が受けている……）"

[[dialogue]]
speaker = "エルデリーゼ"
# （いつかその人に会うことがあったら、その行動についてビシッと言ってやるつもりでしたわ）
line = "（いつかその人に会うことがあったら、その行動についてビシッと言ってやるつもりでしたわ）"

[[dialogue]]
speaker = "エルデリーゼ"
# （なのに……）
line = "（なのに……）"

[[dialogue]]
speaker = "エルデリーゼ"
# （不思議な方ですの……この人と話していると全部を忘れて話に引き込まれてしまう）
line = "（不思議な方ですの……この人と話していると全部を忘れて話に引き込まれてしまう）"

[[dialogue]]
speaker = "エルデリーゼ"
# （ユーモアがあって自然と楽しい気持ちにさせてくれる。余裕があって一緒にいると安心させてくれる）
line = "（ユーモアがあって自然と楽しい気持ちにさせてくれる。余裕があって一緒にいると安心させてくれる）"

[[dialogue]]
speaker = "エルデリーゼ"
# （それに何より、彼女の語る世界は色鮮やかで……まさにこの人の生き方こそ、私が憧れていた自由な生き方──）
line = "（それに何より、彼女の語る世界は色鮮やかで……まさにこの人の生き方こそ、私が憧れていた自由な生き方──）"

[[dialogue]]
speaker = "エルデリーゼ"
# （知りたいですわ。この人のことをもっと……一緒に旅をして、いろんな世界を見て──）
line = "（知りたいですわ。この人のことをもっと……一緒に旅をして、いろんな世界を見て──）"

[[dialogue]]
speaker = "エルデリーゼ"
# 「私を旅に連れて行ってくださいませ！！」
line = "「私を旅に連れて行ってくださいませ！！」"

[[dialogue]]
speaker = "ラティエ"
# 「どうして、そんな事を言い始めたんだ？」
line = "「どうして、そんな事を言い始めたんだ？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「突然で申し訳ありません。ですが学園長様のお話を聞いていて、あなたの生き方こそ私の目指す道だと気が付いたのですわ！」
line = "「突然で申し訳ありません。ですが学園長様のお話を聞いていて、あなたの生き方こそ私の目指す道だと気が付いたのですわ！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ですからお願いです。私を旅に連れて行ってくださいませっ！！」
line = "「ですからお願いです。私を旅に連れて行ってくださいませっ！！」"

[[dialogue]]
speaker = "エスメラルダ"
# 『こ、これはまずい流れです！　あの学園長に感化される人間を増やしてはいけません！　すぐに止めてください！』
line = "『こ、これはまずい流れです！　あの学園長に感化される人間を増やしてはいけません！　すぐに止めてください！』"

[[dialogue]]
speaker = "エスメラルダ"
# 『桜十路のお嬢様を悪の道に誘ったとあっては、学園の経営にも影響が出てしまいます』
line = "『桜十路のお嬢様を悪の道に誘ったとあっては、学園の経営にも影響が出てしまいます』"

[[dialogue]]
speaker = "unk"
# ええと、落ち着いて……
line = "ええと、落ち着いて……"

[[dialogue]]
speaker = "unk"
# （止めてくれって言われても）
line = "（止めてくれって言われても）"

[[dialogue]]
speaker = "ラティエ"
# 「私としては、きみの様な可愛い同行者が出来るのは大歓迎だ」
line = "「私としては、きみの様な可愛い同行者が出来るのは大歓迎だ」"

[[dialogue]]
speaker = "ラティエ"
# 「だが、申し訳ない。その要望にはお応えできない」
line = "「だが、申し訳ない。その要望にはお応えできない」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ど、どうしてですの！？」
line = "「ど、どうしてですの！？」"

[[dialogue]]
speaker = "ラティエ"
# 「きみを連れて行って欲しくない者がたくさんいるだろうからな」
line = "「きみを連れて行って欲しくない者がたくさんいるだろうからな」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「っ……」
line = "「っ……」"

[[dialogue]]
speaker = "ラティエ"
# 「それにきみはとても若い。私の旅につき合わせて、危険な目に遭わせるわけにはいかないのだ」
line = "「それにきみはとても若い。私の旅につき合わせて、危険な目に遭わせるわけにはいかないのだ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「実力不足、とおっしゃりたいのですね？」
line = "「実力不足、とおっしゃりたいのですね？」"

[[dialogue]]
speaker = "ラティエ"
# 「決してきみは未熟ではない。星騎士として既に十分な実力を備えている」
line = "「決してきみは未熟ではない。星騎士として既に十分な実力を備えている」"

[[dialogue]]
speaker = "ラティエ"
# 「だが、そうだな……それでもやはり、私の旅に同行するには──強さが足りない」
line = "「だが、そうだな……それでもやはり、私の旅に同行するには──強さが足りない」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「……では、私が学園長様と共に旅する強さを備えていること、それを認めさせることが出来ればよいということですわね？」
line = "「……では、私が学園長様と共に旅する強さを備えていること、それを認めさせることが出来ればよいということですわね？」"

[[dialogue]]
speaker = "ラティエ"
# 「認めさせることが出来れば、だがね……」
line = "「認めさせることが出来れば、だがね……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「分かりましたわ……」
line = "「分かりましたわ……」"

[[dialogue]]
speaker = "unk"
# エルゼの言葉には本気の色が宿っていた。
line = "エルゼの言葉には本気の色が宿っていた。"

[[dialogue]]
speaker = "unk"
# その瞳を見て、学園長にも本気の気配が漂う。
line = "その瞳を見て、学園長にも本気の気配が漂う。"

[[dialogue]]
speaker = "エルデリーゼ"
# 「必ず認めさせて見せますわ。今度は先ほどのようにはいきませんわよ」
line = "「必ず認めさせて見せますわ。今度は先ほどのようにはいきませんわよ」"

[[dialogue]]
speaker = "ラティエ"
# 「どうだろうね？」
line = "「どうだろうね？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「やぁああああああっ！！！！！」
line = "「やぁああああああっ！！！！！」"

[[dialogue]]
speaker = "unk"
# 目にもとまらぬほどのスピードで攻撃を繰り出したエルゼ。
line = "目にもとまらぬほどのスピードで攻撃を繰り出したエルゼ。"

[[dialogue]]
speaker = "unk"
# それを難なく受け止める学園長。
line = "それを難なく受け止める学園長。"

[[dialogue]]
speaker = "ラティエ"
# 「公平に見極めることを約束しよう。きみが『強い』か『弱い』か……」
line = "「公平に見極めることを約束しよう。きみが『強い』か『弱い』か……」"

[[dialogue]]
speaker = "ラティエ"
# 「示された実力によって、きみの想いに答えを返そう……それで文句はあるまい！」
line = "「示された実力によって、きみの想いに答えを返そう……それで文句はあるまい！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「っ……！？」
line = "「っ……！？」"

[[dialogue]]
speaker = "unk"
# 学園長の反撃を、ギリギリのところでかわした。
line = "学園長の反撃を、ギリギリのところでかわした。"

[[dialogue]]
speaker = "ラティエ"
# 「甘いことを考えていたのではないだろうな？　強さを測っているのだ、当然私も反撃する」
line = "「甘いことを考えていたのではないだろうな？　強さを測っているのだ、当然私も反撃する」"

[[dialogue]]
speaker = "ラティエ"
# 「さあ、続けようか！」
line = "「さあ、続けようか！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「ま、負けませんわっ！！！！！」
line = "「ま、負けませんわっ！！！！！」"
