[[dialogue]]
speaker = "unk"
# 翌日。
line = "翌日。"

[[dialogue]]
speaker = "unk"
# 俺は引き続き公安委員会の作戦に協力して、一般の人たちで賑わうリゾート結界で過ごしていると――
line = "俺は引き続き公安委員会の作戦に協力して、一般の人たちで賑わうリゾート結界で過ごしていると――"

[[dialogue]]
speaker = "ネーゼマイン"
# 「会長～、ちょっとお願いがあるんだけど～♪」
line = "「会長～、ちょっとお願いがあるんだけど～♪」"

[[dialogue]]
speaker = "unk"
# 母さんとリコさんが海の家の方へ行っており、２人きりの時にマインが言い出した。
line = "母さんとリコさんが海の家の方へ行っており、２人きりの時にマインが言い出した。"

[[dialogue]]
speaker = "ネーゼマイン"
# 「実はサンオイルを塗って欲しくて～」
line = "「実はサンオイルを塗って欲しくて～」"

[[dialogue]]
speaker = "unk"
# えぇっ！？
line = "えぇっ！？"

[[dialogue]]
speaker = "ネーゼマイン"
# 「にひひ♪　そんな動揺しなくてもいいじゃ～ん」
line = "「にひひ♪　そんな動揺しなくてもいいじゃ～ん」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「――今のリゾート結界は、デフォルトで紫外線カットがされているから必要ないのでは、って？」
line = "「――今のリゾート結界は、デフォルトで紫外線カットがされているから必要ないのでは、って？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「このサンオイル、今回の作戦の為に必要なんだよね～。特殊な成分で出来ててさ、体に塗ると星力の気配を消すことができるんだ」
line = "「このサンオイル、今回の作戦の為に必要なんだよね～。特殊な成分で出来ててさ、体に塗ると星力の気配を消すことができるんだ」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「だけど、自分では背中とか塗りにくいじゃん？　だから２人で協力したいな～って♪」
line = "「だけど、自分では背中とか塗りにくいじゃん？　だから２人で協力したいな～って♪」"

[[dialogue]]
speaker = "unk"
# せ、せめてプライベートビーチの方で……
line = "せ、せめてプライベートビーチの方で……"

[[dialogue]]
speaker = "ネーゼマイン"
# 「大丈夫、周りを見てみなよ。カップルも多いし、イチャイチャしてるから、平気平気♪」
line = "「大丈夫、周りを見てみなよ。カップルも多いし、イチャイチャしてるから、平気平気♪」"

[[dialogue]]
speaker = "unk"
# そんな感じで押し切られてしまったのだが――
line = "そんな感じで押し切られてしまったのだが――"

[[dialogue]]
speaker = "ネーゼマイン"
# 「それじゃあ会長、私がサンオイル塗ってあげちゃうね～♪」
line = "「それじゃあ会長、私がサンオイル塗ってあげちゃうね～♪」"

[[dialogue]]
speaker = "unk"
# 俺はマインの前で、ビーチマットの上にうつ伏せにさせられていた。
line = "俺はマインの前で、ビーチマットの上にうつ伏せにさせられていた。"

[[dialogue]]
speaker = "unk"
# なんで俺が塗られる側に！？
line = "なんで俺が塗られる側に！？"

[[dialogue]]
speaker = "ネーゼマイン"
# 「え～？　塗って欲しいとは言ったけど、<b>私に</b>とは別に言ってないよ～？」
line = "「え～？　塗って欲しいとは言ったけど、<b>私に</b>とは別に言ってないよ～？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「それとも～、会長は私の体にサンオイル塗ってみたかったのかな～？　にひひ♪」
line = "「それとも～、会長は私の体にサンオイル塗ってみたかったのかな～？　にひひ♪」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「じゃあ早速、サンオイルを会長の背中に垂らして～♪」
line = "「じゃあ早速、サンオイルを会長の背中に垂らして～♪」"

[[dialogue]]
speaker = "unk"
# ひゃんっ！
line = "ひゃんっ！"

[[dialogue]]
speaker = "unk"
# オイルが冷やっとして、思わず声が出てしまう。
line = "オイルが冷やっとして、思わず声が出てしまう。"

[[dialogue]]
speaker = "ネーゼマイン"
# 「にひっ♪　会長ってば、可愛い声出しちゃって～。女の子みた～い<emoji=heart04>」
line = "「にひっ♪　会長ってば、可愛い声出しちゃって～。女の子みた～い<emoji=heart04>」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「そんな情けない会長には～、こっちの方がいいかな～？　えいっ♪」
line = "「そんな情けない会長には～、こっちの方がいいかな～？　えいっ♪」"

[[dialogue]]
speaker = "unk"
# 背中に当たる感触に違和感があり、彼女の方を見てみると――
line = "背中に当たる感触に違和感があり、彼女の方を見てみると――"

[[dialogue]]
speaker = "unk"
# 手じゃなくて『足』！？
line = "手じゃなくて『足』！？"

[[dialogue]]
speaker = "ネーゼマイン"
# 「だって～、手でするより面白そうじゃない？」
line = "「だって～、手でするより面白そうじゃない？」"

[[dialogue]]
speaker = "unk"
# マインは俺の体を跨ぐように立ちながらこちらを見下ろし、片足でオイルを塗り広げて行く。
line = "マインは俺の体を跨ぐように立ちながらこちらを見下ろし、片足でオイルを塗り広げて行く。"

[[dialogue]]
speaker = "ネーゼマイン"
# 「ほ～ら、足でしてあげる<emoji=heart04>　ヌリヌリ～♪」
line = "「ほ～ら、足でしてあげる<emoji=heart04>　ヌリヌリ～♪」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「この辺りもし～っかり、塗っておかないとね♪　にひっ<emoji=heart04>」
line = "「この辺りもし～っかり、塗っておかないとね♪　にひっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そう言って彼女の足の指が伸びて来た場所は、脇腹であった。
line = "そう言って彼女の足の指が伸びて来た場所は、脇腹であった。"

[[dialogue]]
speaker = "ネーゼマイン"
# 「きゃはっ<emoji=heart04>　またちょっと可愛い声が出たね～♪　な～に？　会長、もしかして脇腹弱いの～？」
line = "「きゃはっ<emoji=heart04>　またちょっと可愛い声が出たね～♪　な～に？　会長、もしかして脇腹弱いの～？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「うりうり～<emoji=heart04>　んっ――きゃはははっ！　喘いでる喘いでる～！　そんな声出してたら、周りの人たちから注目されちゃうよ～？」
line = "「うりうり～<emoji=heart04>　んっ――きゃはははっ！　喘いでる喘いでる～！　そんな声出してたら、周りの人たちから注目されちゃうよ～？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「ほらほら<emoji=heart04>　他の人たちもいる前で、年下の女の子に足で弄ばれて、どんな気持ち～？　ねぇ、どんな気持ち～？」
line = "「ほらほら<emoji=heart04>　他の人たちもいる前で、年下の女の子に足で弄ばれて、どんな気持ち～？　ねぇ、どんな気持ち～？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「学園代表の星騎士なのに～、こんな程度で声を上げちゃうなんて、学園の生徒たちが見たら、どう思うかな～？」
line = "「学園代表の星騎士なのに～、こんな程度で声を上げちゃうなんて、学園の生徒たちが見たら、どう思うかな～？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「雑魚ザコ、ざ～こ<emoji=heart04>　ザコ会長<emoji=heart04>」
line = "「雑魚ザコ、ざ～こ<emoji=heart04>　ザコ会長<emoji=heart04>」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「はあぁっ……<emoji=heart04>　会長の可愛い声聞いてると、背筋がゾクゾクしちゃう……！」
line = "「はあぁっ……<emoji=heart04>　会長の可愛い声聞いてると、背筋がゾクゾクしちゃう……！」"

[[dialogue]]
speaker = "リコリンフィア"
# 「随分とお楽しみのようだな、マイン？」
line = "「随分とお楽しみのようだな、マイン？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「おっと♪　お２人共、もう戻って来ちゃいました～？」
line = "「おっと♪　お２人共、もう戻って来ちゃいました～？」"

[[dialogue]]
speaker = "unk"
# 気が付けば、リコさんと母さんが飲み物や食べ物を持って、帰って来ていた。
line = "気が付けば、リコさんと母さんが飲み物や食べ物を持って、帰って来ていた。"

[[dialogue]]
speaker = "リノ"
# 「なるほどね～、マインちゃんとクロトは、そんな感じの関係だったのね～」
line = "「なるほどね～、マインちゃんとクロトは、そんな感じの関係だったのね～」"

[[dialogue]]
speaker = "unk"
# 母さん、これには事情があって！
line = "母さん、これには事情があって！"

[[dialogue]]
speaker = "リノ"
# 「ふふっ、大丈夫よ、クロト。わかってるわ♪」
line = "「ふふっ、大丈夫よ、クロト。わかってるわ♪」"

[[dialogue]]
speaker = "リノ"
# 「お母さん、息子がМだとしても、ちゃんと理解して受け入れるから！」
line = "「お母さん、息子がМだとしても、ちゃんと理解して受け入れるから！」"

[[dialogue]]
speaker = "unk"
# 全然わかってないよ！？
line = "全然わかってないよ！？"

[[dialogue]]
speaker = "unk"
# サンオイルが今回の作戦に必要なものであることを話すと――
line = "サンオイルが今回の作戦に必要なものであることを話すと――"

[[dialogue]]
speaker = "リコリンフィア"
# 「星力の気配を消すサンオイル？　なんだそれは？」
line = "「星力の気配を消すサンオイル？　なんだそれは？」"

[[dialogue]]
speaker = "unk"
# え？
line = "え？"

[[dialogue]]
speaker = "unk"
# ネーゼマインに視線を向けると、彼女は小さく舌を出してみせる。
line = "ネーゼマインに視線を向けると、彼女は小さく舌を出してみせる。"

[[dialogue]]
speaker = "ネーゼマイン"
# 「にひっ、会長、ごめ～ん！　サンオイルの話、それ嘘なんだ☆」
line = "「にひっ、会長、ごめ～ん！　サンオイルの話、それ嘘なんだ☆」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「せっかくの海だから、ちょっと悪戯したくなっちゃって～♪」
line = "「せっかくの海だから、ちょっと悪戯したくなっちゃって～♪」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「でも、おかげでいいストレス発散になったから、ありがとね♪」
line = "「でも、おかげでいいストレス発散になったから、ありがとね♪」"

[[dialogue]]
speaker = "unk"
# ま、マイン～～～！！！
line = "ま、マイン～～～！！！"

[[dialogue]]
speaker = "ネーゼマイン"
# 「あっ！　きゃはははっ☆　会長が怒った～！」
line = "「あっ！　きゃはははっ☆　会長が怒った～！」"

[[dialogue]]
speaker = "unk"
# 海の方へ逃げ出すマインを、俺は追いかける。
line = "海の方へ逃げ出すマインを、俺は追いかける。"

[[dialogue]]
speaker = "リノ"
# 「あらあら、青春ね～♪」
line = "「あらあら、青春ね～♪」"

[[dialogue]]
speaker = "リコリンフィア"
# 「ふっ……」
line = "「ふっ……」"

[[dialogue]]
speaker = "リコリンフィア"
# 「マインがあんな顔をするとはな」
line = "「マインがあんな顔をするとはな」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「私、こう見えても逃げ足には自信があるんだけど、会長は捕まえられるかな～？」
line = "「私、こう見えても逃げ足には自信があるんだけど、会長は捕まえられるかな～？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「でも、もし捕まえられたら、私にもオイル塗ってくれてもいいよ～？」
line = "「でも、もし捕まえられたら、私にもオイル塗ってくれてもいいよ～？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「会長がしたいならだけど<emoji=heart04>　にひひ♪」
line = "「会長がしたいならだけど<emoji=heart04>　にひひ♪」"

[[dialogue]]
speaker = "unk"
# 砂浜で追いかけっこをしながら、楽しそうな悪戯スマイルを浮かべるマインなのだった――
line = "砂浜で追いかけっこをしながら、楽しそうな悪戯スマイルを浮かべるマインなのだった――"

[[dialogue]]
speaker = "unk"
# 一方、離れた場所から、その様子を監視している者たちがいた――
line = "一方、離れた場所から、その様子を監視している者たちがいた――"

[[dialogue]]
speaker = "怪人"
# 「ククッ……自ら出張って来たか、リコリンフィア」
line = "「ククッ……自ら出張って来たか、リコリンフィア」"

[[dialogue]]
speaker = "部下"
# 「どうしますか？　もう仕掛けてしまいますか、ヤハト様」
line = "「どうしますか？　もう仕掛けてしまいますか、ヤハト様」"

[[dialogue]]
speaker = "unk"
# 水着姿の成人男性が、怪人に尋ねる。
line = "水着姿の成人男性が、怪人に尋ねる。"

[[dialogue]]
speaker = "ヤハト"
# 「いや、まだだ。事前に話した通り、入念に準備する」
line = "「いや、まだだ。事前に話した通り、入念に準備する」"

[[dialogue]]
speaker = "ヤハト"
# 「仕掛けるのは――予定通り、<b>１週間後</b>だ」
line = "「仕掛けるのは――予定通り、<b>１週間後</b>だ」"

[[dialogue]]
speaker = "部下"
# 「はっ、かしこまりました」
line = "「はっ、かしこまりました」"

[[dialogue]]
speaker = "ヤハト"
# 「それまでは引き続き、監視を続けろ」
line = "「それまでは引き続き、監視を続けろ」"

[[dialogue]]
speaker = "unk"
# 怪人『ミュータント』へと変身している男の名は――<ruby=いとう>異東</ruby>ヤハト。
line = "怪人『ミュータント』へと変身している男の名は――<ruby>異東<rt>いとう</rt></ruby>ヤハト。"

[[dialogue]]
speaker = "unk"
# そして、彼が所属するのは、世界的に悪名を馳せる星術犯罪組織『ユゴス』。
line = "そして、彼が所属するのは、世界的に悪名を馳せる星術犯罪組織『ユゴス』。"

[[dialogue]]
speaker = "ヤハト"
# 「……しかし、公安委員会も甘いな」
line = "「……しかし、公安委員会も甘いな」"

[[dialogue]]
speaker = "ヤハト"
# 「緋宮クロトを囮に使って来ることは、もうとっくに<b>予測済み</b>だというのに……ククッ」
line = "「緋宮クロトを囮に使って来ることは、もうとっくに<b>予測済み</b>だというのに……ククッ」"

[[dialogue]]
speaker = "unk"
# 国際指名手配犯の星術使いは、ほくそ笑みながら、スッと幻影のようにその場から消え去るのだった――
line = "国際指名手配犯の星術使いは、ほくそ笑みながら、スッと幻影のようにその場から消え去るのだった――"
