[[dialogue]]
speaker = "トワ先生"
# 「――ふぅ、今日はここまでにしとこうかな」
line = "「――ふぅ、今日はここまでにしとこうかな」"

[[dialogue]]
speaker = "トワ先生"
# 「あー、もう、つっかれた～！　こんな時間になっちゃって、急がないとお店が閉まっちゃうよ」
line = "「あー、もう、つっかれた～！　こんな時間になっちゃって、急がないとお店が閉まっちゃうよ」"

[[dialogue]]
speaker = "トワ先生"
# 「さっさと片付けして帰ろ～っと」
line = "「さっさと片付けして帰ろ～っと」"

[[dialogue]]
speaker = "トワ先生"
# 「いつも遅くなっちゃって、メイプルちゃんに申し訳ないなぁ」
line = "「いつも遅くなっちゃって、メイプルちゃんに申し訳ないなぁ」"

[[dialogue]]
speaker = "トワ先生"
# 「ノヴァフォームの経験を活かしてウェディングフォームの研究を進められるかも、なんて期待してたけど……そう上手くはいかないね」
line = "「ノヴァフォームの経験を活かしてウェディングフォームの研究を進められるかも、なんて期待してたけど……そう上手くはいかないね」"

[[dialogue]]
speaker = "トワ先生"
# 「でも新フォームの謎が解明できたらみんなの戦力アップに繋がるんだし、頑張らなくちゃ！」
line = "「でも新フォームの謎が解明できたらみんなの戦力アップに繋がるんだし、頑張らなくちゃ！」"

[[dialogue]]
speaker = "トワ先生"
# 「それにしても……もう６月……ジューンブライドの季節か～……」
line = "「それにしても……もう６月……ジューンブライドの季節か～……」"

[[dialogue]]
speaker = "トワ先生"
# 「研究してるテーマがテーマだからつい考えちゃうな。わたしもいつかウェディングドレスを着る日が来るのかな、なーんて……」
line = "「研究してるテーマがテーマだからつい考えちゃうな。わたしもいつかウェディングドレスを着る日が来るのかな、なーんて……」"

[[dialogue]]
speaker = "トワ先生"
# 「そのためにまずは結婚しなきゃなんだけど……でもお相手もいないし、どんどん歳を取っていっちゃうし──」
line = "「そのためにまずは結婚しなきゃなんだけど……でもお相手もいないし、どんどん歳を取っていっちゃうし──」"

[[dialogue]]
speaker = "トワ先生"
# 「うわああああ～～～ん、わたしも結婚したいよおおお～～！！」
line = "「うわああああ～～～ん、わたしも結婚したいよおおお～～！！」"

[[dialogue]]
speaker = "unk"
# ある日の放課後、ヘレナに呼び出されたクロトとマトイは九浄家に向かっていた。
line = "ある日の放課後、ヘレナに呼び出されたクロトとマトイは九浄家に向かっていた。"

[[dialogue]]
speaker = "unk"
# これまでも突然呼び出されることはあったが、今日は珍しいメンバーがもう１人──
line = "これまでも突然呼び出されることはあったが、今日は珍しいメンバーがもう１人──"

[[dialogue]]
speaker = "トワ先生"
# 「会長くんとマトイちゃんはどうして理事長に呼び出されたの？」
line = "「会長くんとマトイちゃんはどうして理事長に呼び出されたの？」"

[[dialogue]]
speaker = "unk"
# いつものように何も聞かされてません
line = "いつものように何も聞かされてません"

[[dialogue]]
speaker = "unk"
# 来てからのお楽しみだそうで
line = "来てからのお楽しみだそうで"

[[dialogue]]
speaker = "マトイ"
# 「トワちゃん先生はどんな用事で呼ばれたんですか？」
line = "「トワちゃん先生はどんな用事で呼ばれたんですか？」"

[[dialogue]]
speaker = "トワ先生"
# 「うーん……わたしもおんなじで、何も聞かされてないんだよね～」
line = "「うーん……わたしもおんなじで、何も聞かされてないんだよね～」"

[[dialogue]]
speaker = "トワ先生"
# 「でも多分あれじゃないかなって心当たりは一応あるんだよ」
line = "「でも多分あれじゃないかなって心当たりは一応あるんだよ」"

[[dialogue]]
speaker = "マトイ"
# 「え、そうなんですか？」
line = "「え、そうなんですか？」"

[[dialogue]]
speaker = "トワ先生"
# 「うん。ずっと前から研究してることがあって、それについての報告を求められるんじゃないかな、って……もう６月になっちゃったしね」
line = "「うん。ずっと前から研究してることがあって、それについての報告を求められるんじゃないかな、って……もう６月になっちゃったしね」"

[[dialogue]]
speaker = "トワ先生"
# 「６月って言ったら、マトイちゃんは何を思い浮かべる？」
line = "「６月って言ったら、マトイちゃんは何を思い浮かべる？」"

[[dialogue]]
speaker = "マトイ"
# 「えっ？　ええと、やっぱり……ジューンブライド？」
line = "「えっ？　ええと、やっぱり……ジューンブライド？」"

[[dialogue]]
speaker = "トワ先生"
# 「はい、正解」
line = "「はい、正解」"

[[dialogue]]
speaker = "unk"
# ウェディングフォームのこと？
line = "ウェディングフォームのこと？"

[[dialogue]]
speaker = "unk"
# あ、もしかして……
line = "あ、もしかして……"

[[dialogue]]
speaker = "トワ先生"
# 「そうなんだよ～。星見家で起きたウェディングフォーム騒動があったでしょ？」
line = "「そうなんだよ～。星見家で起きたウェディングフォーム騒動があったでしょ？」"

[[dialogue]]
speaker = "トワ先生"
# 「あれからずっとあの現象について調べてるんだよ。理事長もウェディングフォームを人工戦闘服で作れないかって研究をしてるから協力してね」
line = "「あれからずっとあの現象について調べてるんだよ。理事長もウェディングフォームを人工戦闘服で作れないかって研究をしてるから協力してね」"

[[dialogue]]
speaker = "マトイ"
# 「ヘレナさん、人工戦闘服の開発にすごく力を入れてますもんね。でも……ウェディングフォームか～、いいなぁ」
line = "「ヘレナさん、人工戦闘服の開発にすごく力を入れてますもんね。でも……ウェディングフォームか～、いいなぁ」"

[[dialogue]]
speaker = "マトイ"
# 「フィオナさんたちのウェディングフォーム、すごく綺麗だったし……私も着てみたいな～」
line = "「フィオナさんたちのウェディングフォーム、すごく綺麗だったし……私も着てみたいな～」"

[[dialogue]]
speaker = "トワ先生"
# 「あはは、あのフォームについてはまだまだ未知数なところだらけなんだよね。早く解明したいんだけどなかなか上手くいかなくて」
line = "「あはは、あのフォームについてはまだまだ未知数なところだらけなんだよね。早く解明したいんだけどなかなか上手くいかなくて」"

[[dialogue]]
speaker = "マトイ"
# 「そうなんですね。残念……」
line = "「そうなんですね。残念……」"

[[dialogue]]
speaker = "トワ先生"
# 「あ、けど九浄家でも独自に研究を進めてるみたいだから、もしかすると向こうで何か発見があったのかも？」
line = "「あ、けど九浄家でも独自に研究を進めてるみたいだから、もしかすると向こうで何か発見があったのかも？」"

[[dialogue]]
speaker = "トワ先生"
# 「もしかしたら試作品が完成した～、みたいな話かもしれないし……そしたらマトイちゃん、着せてもらったらいいんじゃない？」
line = "「もしかしたら試作品が完成した～、みたいな話かもしれないし……そしたらマトイちゃん、着せてもらったらいいんじゃない？」"

[[dialogue]]
speaker = "マトイ"
# 「わ、私がですか？　それだったらトワちゃん先生の方が先じゃないですか？」
line = "「わ、私がですか？　それだったらトワちゃん先生の方が先じゃないですか？」"

[[dialogue]]
speaker = "トワ先生"
# 「いやいや、さすがにわたしはないよ～。先生だもん」
line = "「いやいや、さすがにわたしはないよ～。先生だもん」"

[[dialogue]]
speaker = "マトイ"
# 「トワちゃん先生のウェディングドレス姿、絶対似合うと思いますけどね」
line = "「トワちゃん先生のウェディングドレス姿、絶対似合うと思いますけどね」"

[[dialogue]]
speaker = "トワ先生"
# 「またまた～。優しいね、マトイちゃんは。お世辞でも嬉しいよ」
line = "「またまた～。優しいね、マトイちゃんは。お世辞でも嬉しいよ」"

[[dialogue]]
speaker = "unk"
# アステラだ！
line = "アステラだ！"

[[dialogue]]
speaker = "unk"
# 待って、２人とも！
line = "待って、２人とも！"

[[dialogue]]
speaker = "マトイ"
# 「私たちで対処しましょう！　先生、許可をお願いします！」
line = "「私たちで対処しましょう！　先生、許可をお願いします！」"

[[dialogue]]
speaker = "トワ先生"
# 「うん！　わたしも一緒に戦うよ！」
line = "「うん！　わたしも一緒に戦うよ！」"

[[dialogue]]
speaker = "トワ先生"
# 「ここだよ！　しばらく持ちこたえれば、援軍も来てくれるはず！　頑張ろう、２人とも！」
line = "「ここだよ！　しばらく持ちこたえれば、援軍も来てくれるはず！　頑張ろう、２人とも！」"

[[dialogue]]
speaker = "トワ先生"
# 「さあ、行くよっ！」
line = "「さあ、行くよっ！」"

[[dialogue]]
speaker = "unk"
# ……………………
line = "……………………"

[[dialogue]]
speaker = "マトイ"
# 「………………」
line = "「………………」"

[[dialogue]]
speaker = "トワ先生"
# 「え……？　どうしたの２人とも、ぼーっとしてたら危ないよ？」
line = "「え……？　どうしたの２人とも、ぼーっとしてたら危ないよ？」"

[[dialogue]]
speaker = "マトイ"
# 「ええと、すみません……ちょっと現実に追いつけなくって」
line = "「ええと、すみません……ちょっと現実に追いつけなくって」"

[[dialogue]]
speaker = "unk"
# 自分の格好を見てみて
line = "自分の格好を見てみて"

[[dialogue]]
speaker = "トワ先生"
# 「え？　わたしの格好がどうかした……の……」
line = "「え？　わたしの格好がどうかした……の……」"

[[dialogue]]
speaker = "トワ先生"
# 「って、ええええ！！？　なんなの、これ～～～～っ！！？」
line = "「って、ええええ！！？　なんなの、これ～～～～っ！！？」"
