[[dialogue]]
speaker = "ヴィーナス"
# 「ふむふむ……それが交流会の企画書？」
line = "「ふむふむ……それが交流会の企画書？」"

[[dialogue]]
speaker = "unk"
# どうかな？
line = "どうかな？"

[[dialogue]]
speaker = "ヴィーナス"
# 「うん、バッチリだと思うわ！　あとはフィオナと話を詰めていくだけね」
line = "「うん、バッチリだと思うわ！　あとはフィオナと話を詰めていくだけね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「早速、流星学園にお邪魔しましょ。あちらも何かアイデアを思いついてる頃だろうし」
line = "「早速、流星学園にお邪魔しましょ。あちらも何かアイデアを思いついてる頃だろうし」"

[[dialogue]]
speaker = "フィオナ"
# 「ごめんください」
line = "「ごめんください」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あ、フィオナ。ちょうど訪ねるところだったのよ」
line = "「あ、フィオナ。ちょうど訪ねるところだったのよ」"

[[dialogue]]
speaker = "フィオナ"
# 「例の交流会のお話ですね？　私たちも良案を思いついていますよ」
line = "「例の交流会のお話ですね？　私たちも良案を思いついていますよ」"

[[dialogue]]
speaker = "フィオナ"
# 「でもごめんなさい。その前にお伺いしたいことがありまして。お二人ともルリエルを──」
line = "「でもごめんなさい。その前にお伺いしたいことがありまして。お二人ともルリエルを──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「きゃっ！？　日誌が……！」
line = "「きゃっ！？　日誌が……！」"

[[dialogue]]
speaker = "unk"
# まさかまた新しいページが？
line = "まさかまた新しいページが？"

[[dialogue]]
speaker = "ヴィーナス"
# 「今度は一体──って、あら？　特にページは増えてないわね」
line = "「今度は一体──って、あら？　特にページは増えてないわね」"

[[dialogue]]
speaker = "フィオナ"
# 「まさか……」
line = "「まさか……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ん？　何か心当たりあるの？　で、さっき言ってた伺いたいことって？」
line = "「ん？　何か心当たりあるの？　で、さっき言ってた伺いたいことって？」"

[[dialogue]]
speaker = "フィオナ"
# 「もしかすると関係があるのかもしれませんが……お二人とも、ルリエルを見かけませんでしたか？」
line = "「もしかすると関係があるのかもしれませんが……お二人とも、ルリエルを見かけませんでしたか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ルリエル？　ああ、あのそそっかしい天使の子よね？　私たちは見ていないけど」
line = "「ルリエル？　ああ、あのそそっかしい天使の子よね？　私たちは見ていないけど」"

[[dialogue]]
speaker = "フィオナ"
# 「やはり……そうですか。実は彼女、数日前から行方知れずになっているんです」
line = "「やはり……そうですか。実は彼女、数日前から行方知れずになっているんです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「大変じゃない！　モンスターに囚われていたりしたら……！」
line = "「大変じゃない！　モンスターに囚われていたりしたら……！」"

[[dialogue]]
speaker = "フィオナ"
# 「いえ、それはないと思います。アステラが発生したという報告も受けていませんから」
line = "「いえ、それはないと思います。アステラが発生したという報告も受けていませんから」"

[[dialogue]]
speaker = "フィオナ"
# 「しかしだからこそ心配で。そこでお二人にも相談をと思って訪ねてきたのですが」
line = "「しかしだからこそ心配で。そこでお二人にも相談をと思って訪ねてきたのですが」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そのタイミングで私の日誌が光った……と。これはきっと偶然じゃないわね！」
line = "「そのタイミングで私の日誌が光った……と。これはきっと偶然じゃないわね！」"

[[dialogue]]
speaker = "フィオナ"
# 「そうなのかもしれません。もしかするとルリエルはあの塔に……」
line = "「そうなのかもしれません。もしかするとルリエルはあの塔に……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「とにかくフィーニスの塔へ行ってみましょ。何かわかるかもしれないわ」
line = "「とにかくフィーニスの塔へ行ってみましょ。何かわかるかもしれないわ」"

[[dialogue]]
speaker = "マグダレナ"
# 「これは一体……」
line = "「これは一体……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あら、マグダレナ？」
line = "「あら、マグダレナ？」"

[[dialogue]]
speaker = "マグダレナ"
# 「ヴィーナスさま。フィオナさまや会長さまも。どうしてこちらに？」
line = "「ヴィーナスさま。フィオナさまや会長さまも。どうしてこちらに？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私たちはルリエルを探しに──いえ、それよりマグダレナこそどうしたの？　深刻な顔をして」
line = "「私たちはルリエルを探しに──いえ、それよりマグダレナこそどうしたの？　深刻な顔をして」"

[[dialogue]]
speaker = "マグダレナ"
# 「実は世界の境界に、原因不明の乱れが発生しているようなのです」
line = "「実は世界の境界に、原因不明の乱れが発生しているようなのです」"

[[dialogue]]
speaker = "フィオナ"
# 「乱れ、ですか？」
line = "「乱れ、ですか？」"

[[dialogue]]
speaker = "マグダレナ"
# 「はい。このようなことは私も初めてです」
line = "「はい。このようなことは私も初めてです」"

[[dialogue]]
speaker = "マグダレナ"
# 「邪悪な気配は感じませんが、しかし何が起こるか──」
line = "「邪悪な気配は感じませんが、しかし何が起こるか──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「きゃっ。また日誌が」
line = "「きゃっ。また日誌が」"

[[dialogue]]
speaker = "フィオナ"
# 「フィーニスの塔も光り輝いています……！」
line = "「フィーニスの塔も光り輝いています……！」"

[[dialogue]]
speaker = "マグダレナ"
# 「これは……日誌とフィーニスの塔が共鳴している……？　光が──」
line = "「これは……日誌とフィーニスの塔が共鳴している……？　光が──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「何が何だかわからないけど望むところよ！　受けて立つわ！」
line = "「何が何だかわからないけど望むところよ！　受けて立つわ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ええっ、ヴィーナスさん！？　ダメです、呑み込まれます……！」
line = "「ええっ、ヴィーナスさん！？　ダメです、呑み込まれます……！」"

[[dialogue]]
speaker = "unk"
# っっ──！！
line = "っっ──！！"

[[dialogue]]
speaker = "ヴィーナス"
# 「ここ、は……？　フィーニスの塔の中じゃないわよね」
line = "「ここ、は……？　フィーニスの塔の中じゃないわよね」"

[[dialogue]]
speaker = "フィオナ"
# 「どこかの学園……でしょうか？　なぜ私たちはこんな場所に？」
line = "「どこかの学園……でしょうか？　なぜ私たちはこんな場所に？」"

[[dialogue]]
speaker = "マグダレナ"
# 「境界の乱れに巻き込まれてしまったようですね……。人間界のどこかに転移させられてしまったようです」
line = "「境界の乱れに巻き込まれてしまったようですね……。人間界のどこかに転移させられてしまったようです」"

[[dialogue]]
speaker = "unk"
# 見慣れない場所だ
line = "見慣れない場所だ"

[[dialogue]]
speaker = "ヴィーナス"
# 「相当遠くまで飛ばされちゃったのかしら。現在地の確認を──って、あら？　ＤＩＳＣが圏外だわ」
line = "「相当遠くまで飛ばされちゃったのかしら。現在地の確認を──って、あら？　ＤＩＳＣが圏外だわ」"

[[dialogue]]
speaker = "フィオナ"
# 「私のＤＩＳＣもです。おかしいですね、人間界で圏外だなんて……」
line = "「私のＤＩＳＣもです。おかしいですね、人間界で圏外だなんて……」"

[[dialogue]]
speaker = "マグダレナ"
# 「世界の摂理が機能していない……？　いえ、そもそも世界の構造が違う……？　いったい何が……」
line = "「世界の摂理が機能していない……？　いえ、そもそも世界の構造が違う……？　いったい何が……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ブツブツ言ってどうしたの、マグダレナ？」
line = "「ブツブツ言ってどうしたの、マグダレナ？」"

[[dialogue]]
speaker = "マグダレナ"
# 「まだ推測の域を出ませんが。もしかすると──」
line = "「まだ推測の域を出ませんが。もしかすると──」"

[[dialogue]]
speaker = "？？？"
# 「待ちなさーいっ！！」
line = "「待ちなさーいっ！！」"

[[dialogue]]
speaker = "？？？"
# 「また悪さばっかりしてっ。お仕置きなんだからーっ！」
line = "「また悪さばっかりしてっ。お仕置きなんだからーっ！」"

[[dialogue]]
speaker = "雑魚魔族"
# 「イー！」
line = "「イー！」"

[[dialogue]]
speaker = "リア"
# 「相変わらず逃げ足だけは速い……！　聖沙ちゃん、追いかけるよ！」
line = "「相変わらず逃げ足だけは速い……！　聖沙ちゃん、追いかけるよ！」"

[[dialogue]]
speaker = "聖沙"
# 「は、はいっ！　どこまでもお供します、お姉さまっ！」
line = "「は、はいっ！　どこまでもお供します、お姉さまっ！」"

[[dialogue]]
speaker = "unk"
# ここにもモンスターが！
line = "ここにもモンスターが！"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうね。でもさっきの２人、見覚えがないわね。流星学園の星騎士かしら」
line = "「そうね。でもさっきの２人、見覚えがないわね。流星学園の星騎士かしら」"

[[dialogue]]
speaker = "フィオナ"
# 「いえ、私も知らない星騎士ですね。とにかく先程の二人を追いかけましょう」
line = "「いえ、私も知らない星騎士ですね。とにかく先程の二人を追いかけましょう」"

[[dialogue]]
speaker = "聖沙"
# 「追い詰めたわよ、観念なさい！」
line = "「追い詰めたわよ、観念なさい！」"

[[dialogue]]
speaker = "リア"
# 「みんなから盗ったものを返して！」
line = "「みんなから盗ったものを返して！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「手を貸すわ！　二人だけじゃ危険よ！」
line = "「手を貸すわ！　二人だけじゃ危険よ！」"

[[dialogue]]
speaker = "聖沙"
# 「えっ、と……どちら様？」
line = "「えっ、と……どちら様？」"

[[dialogue]]
speaker = "リア"
# 「ダメだよ。魔族は普通の人には倒せな──」
line = "「ダメだよ。魔族は普通の人には倒せな──」"

[[dialogue]]
speaker = "フィオナ"
# 「心配しないでください。私たちも──<ruby=スターナイト>星騎士</ruby>ですから」
line = "「心配しないでください。私たちも──<ruby>星騎士<rt>スターナイト</rt></ruby>ですから」"

[[dialogue]]
speaker = "聖沙"
# 「へ？　すたー……ないと……？」
line = "「へ？　すたー……ないと……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「みんな、戦闘準備！」
line = "「みんな、戦闘準備！」"

[[dialogue]]
speaker = "フィオナ"
# 「さぁ、参りましょう！」
line = "「さぁ、参りましょう！」"

[[dialogue]]
speaker = "リア"
# 「どういう、こと？　どうして私たち以外にクルセイダースが……」
line = "「どういう、こと？　どうして私たち以外にクルセイダースが……」"

[[dialogue]]
speaker = "聖沙"
# 「先輩っ、今は魔族をっ」
line = "「先輩っ、今は魔族をっ」"

[[dialogue]]
speaker = "リア"
# 「そ、そうだねっ。とにかく、みんなから奪った福引き券は返してもらうんだから～っ！」
line = "「そ、そうだねっ。とにかく、みんなから奪った福引き券は返してもらうんだから～っ！」"
