[[dialogue]]
speaker = "ウェンディ"
# 「アクアシーリング！」
line = "「アクアシーリング！」"

[[dialogue]]
speaker = "スミス"
# 「ゲコ！」
line = "「ゲコ！」"

[[dialogue]]
speaker = "？？？"
# 「あとはこれを基地に送って……と」
line = "「あとはこれを基地に送って……と」"

[[dialogue]]
speaker = "？？？"
# 「ふぅ……ご協力ありがとうございました」
line = "「ふぅ……ご協力ありがとうございました」"

[[dialogue]]
speaker = "unk"
# 君はいったい？
line = "君はいったい？"

[[dialogue]]
speaker = "？？？"
# 「あなたは新星学園の星徒会長さん……ですよね」
line = "「あなたは新星学園の星徒会長さん……ですよね」"

[[dialogue]]
speaker = "？？？"
# 「どこからお話しましょうか。本当は言っちゃいけないんですけど……説明する義務がありますよね……」
line = "「どこからお話しましょうか。本当は言っちゃいけないんですけど……説明する義務がありますよね……」"

[[dialogue]]
speaker = "ウェンディ"
# 「まず、私はウェンディ。ネビュラ所属の魔女で、組織の資金運用と、セドナ長官の補佐を担当しています」
line = "「まず、私はウェンディ。ネビュラ所属の魔女で、組織の資金運用と、セドナ長官の補佐を担当しています」"

[[dialogue]]
speaker = "ウェンディ"
# 「どうして私がモンスターを捕獲していたのかと言いますとですね……」
line = "「どうして私がモンスターを捕獲していたのかと言いますとですね……」"

[[dialogue]]
speaker = "ウェンディ"
# 「実際に戦ったのですから、リクリエの使徒アポロは当然ご存じでしょう」
line = "「実際に戦ったのですから、リクリエの使徒アポロは当然ご存じでしょう」"

[[dialogue]]
speaker = "ウェンディ"
# 「そして、彼女が使役する特殊なモンスターのことも」
line = "「そして、彼女が使役する特殊なモンスターのことも」"

[[dialogue]]
speaker = "ウェンディ"
# 「あなた方がモンスターと戦っている間、我々は秘密裏にこれを捕獲。改造してネビュラの戦力とする実験を行っていました」
line = "「あなた方がモンスターと戦っている間、我々は秘密裏にこれを捕獲。改造してネビュラの戦力とする実験を行っていました」"

[[dialogue]]
speaker = "ウェンディ"
# 「誤解はしないでください。これもリクリエに対抗するためです」
line = "「誤解はしないでください。これもリクリエに対抗するためです」"

[[dialogue]]
speaker = "ウェンディ"
# 「ネビュラは目的のためなら手段を選ばない。それだけのことです」
line = "「ネビュラは目的のためなら手段を選ばない。それだけのことです」"

[[dialogue]]
speaker = "unk"
# で、どうしてそのモンスターが街に？
line = "で、どうしてそのモンスターが街に？"

[[dialogue]]
speaker = "ウェンディ"
# 「うっ……！？　そ、それはですね……」
line = "「うっ……！？　そ、それはですね……」"

[[dialogue]]
speaker = "アイリーン"
# 「ねぇねぇ、ウェンディさん、今ヒマ？　チェスやろうよー」
line = "「ねぇねぇ、ウェンディさん、今ヒマ？　チェスやろうよー」"

[[dialogue]]
speaker = "ウェンディ"
# 「見ての通り仕事中です。関係会社の業績予測修正を出さないといけないので放っておいてください」
line = "「見ての通り仕事中です。関係会社の業績予測修正を出さないといけないので放っておいてください」"

[[dialogue]]
speaker = "アイリーン"
# 「え～、それじゃいつまでたってもセドナさんの相手はできないよ？　ウェンディさん、アイリーンより弱いんだから」
line = "「え～、それじゃいつまでたってもセドナさんの相手はできないよ？　ウェンディさん、アイリーンより弱いんだから」"

[[dialogue]]
speaker = "ウェンディ"
# 「む。アイリーンが意地悪な攻め方をするから悪いんです」
line = "「む。アイリーンが意地悪な攻め方をするから悪いんです」"

[[dialogue]]
speaker = "アイリーン"
# 「だってウェンディさん、素直すぎて何したいか見え見えなんだもん。セドナさんとやったらボッコボコのメッタメタだよ？」
line = "「だってウェンディさん、素直すぎて何したいか見え見えなんだもん。セドナさんとやったらボッコボコのメッタメタだよ？」"

[[dialogue]]
speaker = "ウェンディ"
# 「うぐ……そんな直球に言わなくても……」
line = "「うぐ……そんな直球に言わなくても……」"

[[dialogue]]
speaker = "ウェンディ"
# （私の方がずっと年上なのに、ちゃんと計算してるのに、どうして勝てないんですか……）
line = "（私の方がずっと年上なのに、ちゃんと計算してるのに、どうして勝てないんですか……）"

[[dialogue]]
speaker = "アイリーン"
# 「セドナさんとチェスしたいなら直接言えばいいのに」
line = "「セドナさんとチェスしたいなら直接言えばいいのに」"

[[dialogue]]
speaker = "ウェンディ"
# 「ダメです。セドナ長官のお時間を頂くからには、相応の実力を以てお相手をしなければいけません」
line = "「ダメです。セドナ長官のお時間を頂くからには、相応の実力を以てお相手をしなければいけません」"

[[dialogue]]
speaker = "ウェンディ"
# 「あとアイリーン、本部にいる時はセドナ長官と呼びなさい」
line = "「あとアイリーン、本部にいる時はセドナ長官と呼びなさい」"

[[dialogue]]
speaker = "アイリーン"
# 「は～い」
line = "「は～い」"

[[dialogue]]
speaker = "セドナ"
# 「ウェンディ」
line = "「ウェンディ」"

[[dialogue]]
speaker = "ウェンディ"
# 「はいぃぃっ！？」
line = "「はいぃぃっ！？」"

[[dialogue]]
speaker = "セドナ"
# 「私は予定通り、定期報告のために魔女の森へ戻る。数日基地を空けるが、留守にしている間のことは任せた」
line = "「私は予定通り、定期報告のために魔女の森へ戻る。数日基地を空けるが、留守にしている間のことは任せた」"

[[dialogue]]
speaker = "セドナ"
# 「長老たちの相手をせねばならんのは気が進まんが、これも立場だ。私がいない間に面倒ごとは起こしてくれるなよ」
line = "「長老たちの相手をせねばならんのは気が進まんが、これも立場だ。私がいない間に面倒ごとは起こしてくれるなよ」"

[[dialogue]]
speaker = "ウェンディ"
# 「もちろんです。お帰りをお待ちしていますね」
line = "「もちろんです。お帰りをお待ちしていますね」"

[[dialogue]]
speaker = "セドナ"
# 「ああ」
line = "「ああ」"

[[dialogue]]
speaker = "ウェンディ"
# 「というわけでアイリーン、残念ながらチェスをしている時間はありません。長官の分まで、このネビュラ本部を管理しなければいけませんので」
line = "「というわけでアイリーン、残念ながらチェスをしている時間はありません。長官の分まで、このネビュラ本部を管理しなければいけませんので」"

[[dialogue]]
speaker = "アイリーン"
# 「わかった。頑張ってねー」
line = "「わかった。頑張ってねー」"

[[dialogue]]
speaker = "ウェンディ"
# 「ええ、まぁ、ネビュラ本部を任されたまではいいのですが……」
line = "「ええ、まぁ、ネビュラ本部を任されたまではいいのですが……」"

[[dialogue]]
speaker = "ウェンディ"
# 「決算報告書と、来季の事業計画書と、マーケティング資料の作成と……ああ、タスクがたくさん……」
line = "「決算報告書と、来季の事業計画書と、マーケティング資料の作成と……ああ、タスクがたくさん……」"

[[dialogue]]
speaker = "ウェンディ"
# 「それにネビュラ内部の会計もしないといけませんし……うぅ、最近は必要な人員と設備が多くて支出が……」
line = "「それにネビュラ内部の会計もしないといけませんし……うぅ、最近は必要な人員と設備が多くて支出が……」"

[[dialogue]]
speaker = "ウェンディ"
# 「あ、モンスター改造実験の様子も見ないといけないんでした。えーと、観測機器の操作は……」
line = "「あ、モンスター改造実験の様子も見ないといけないんでした。えーと、観測機器の操作は……」"

[[dialogue]]
speaker = "ウェンディ"
# 「え？　あっ！？　ロックが外れて……あ、ちょっと！　待ちなさ～い！」
line = "「え？　あっ！？　ロックが外れて……あ、ちょっと！　待ちなさ～い！」"

[[dialogue]]
speaker = "ウェンディ"
# 「というわけで、他の仕事に忙殺されているうちに、私のミスで２０体のモンスターが解き放たれてしまいまして……」
line = "「というわけで、他の仕事に忙殺されているうちに、私のミスで２０体のモンスターが解き放たれてしまいまして……」"

[[dialogue]]
speaker = "unk"
# 多忙な管理職の悲劇……
line = "多忙な管理職の悲劇……"

[[dialogue]]
speaker = "ウェンディ"
# 「くっ……学生に言われると余計に……心にダメージが……」
line = "「くっ……学生に言われると余計に……心にダメージが……」"

[[dialogue]]
speaker = "ウェンディ"
# 「ひとまずモンスターを倒すのは待ってください」
line = "「ひとまずモンスターを倒すのは待ってください」"

[[dialogue]]
speaker = "ウェンディ"
# 「モンスターはネビュラで改造実験を受けており、ただちに暴れる危険はありません。実際、先ほどはモンスターをほぼ無抵抗で制圧できました」
line = "「モンスターはネビュラで改造実験を受けており、ただちに暴れる危険はありません。実際、先ほどはモンスターをほぼ無抵抗で制圧できました」"

[[dialogue]]
speaker = "ウェンディ"
# 「セドナ長官は多忙なお方。こんなことで長官を煩わせたくはありません。それに……」
line = "「セドナ長官は多忙なお方。こんなことで長官を煩わせたくはありません。それに……」"

[[dialogue]]
speaker = "ウェンディ"
# 「長官、めちゃくちゃ怖いじゃないですか！」
line = "「長官、めちゃくちゃ怖いじゃないですか！」"

[[dialogue]]
speaker = "unk"
# 確かに迫力あったなぁ……
line = "確かに迫力あったなぁ……"

[[dialogue]]
speaker = "ウェンディ"
# 「長官のことはとってもとっても尊敬してますけど、怖いものは怖いんです！」
line = "「長官のことはとってもとっても尊敬してますけど、怖いものは怖いんです！」"

[[dialogue]]
speaker = "ウェンディ"
# 「長官が戻ってきて、実験中のモンスターがいなくなったと知れたらどうなるか……」
line = "「長官が戻ってきて、実験中のモンスターがいなくなったと知れたらどうなるか……」"

[[dialogue]]
speaker = "ウェンディ"
# 「だからこの件は内密に解決したいんです！　どうか……どうかお願いします！」
line = "「だからこの件は内密に解決したいんです！　どうか……どうかお願いします！」"

[[dialogue]]
speaker = "unk"
# わかった
line = "わかった"

[[dialogue]]
speaker = "ウェンディ"
# 「本当ですか！？　ありがとうございます！」
line = "「本当ですか！？　ありがとうございます！」"

[[dialogue]]
speaker = "unk"
# ──というわけで今に至る。
line = "──というわけで今に至る。"

[[dialogue]]
speaker = "ウェンディ"
# 「このモンスターはネビュラ基地に送っておきますね」
line = "「このモンスターはネビュラ基地に送っておきますね」"

[[dialogue]]
speaker = "ウェンディ"
# 「私の計算が正しければ、逃げ出したモンスターはあと１５体」
line = "「私の計算が正しければ、逃げ出したモンスターはあと１５体」"

[[dialogue]]
speaker = "ウェンディ"
# 「それにネビュラでモンスターを戦力化するにあたり、命令を聞くようにするほか、透明化や瞬間移動など特殊能力の追加も試みました」
line = "「それにネビュラでモンスターを戦力化するにあたり、命令を聞くようにするほか、透明化や瞬間移動など特殊能力の追加も試みました」"

[[dialogue]]
speaker = "ウェンディ"
# 「そのせいで捕捉するのも難しくて……こうして足で探すしかないんですよね……」
line = "「そのせいで捕捉するのも難しくて……こうして足で探すしかないんですよね……」"

[[dialogue]]
speaker = "ウェンディ"
# 「はぁ……こんなことじゃ長官に怒られちゃう……」
line = "「はぁ……こんなことじゃ長官に怒られちゃう……」"

[[dialogue]]
speaker = "unk"
# セドナさんってそんなに怖いの？
line = "セドナさんってそんなに怖いの？"

[[dialogue]]
speaker = "ウェンディ"
# 「理由もなく怒る方ではないのですが……厳しい方なのは間違いないですね」
line = "「理由もなく怒る方ではないのですが……厳しい方なのは間違いないですね」"

[[dialogue]]
speaker = "ウェンディ"
# 「でも長官は素晴らしい人なんです！」
line = "「でも長官は素晴らしい人なんです！」"

[[dialogue]]
speaker = "ウェンディ"
# 「強くて、聡明で、意志が強くて……」
line = "「強くて、聡明で、意志が強くて……」"

[[dialogue]]
speaker = "ウェンディ"
# 「冷静にして果断。即断即決。凛々しく、美しく、完璧で……最高の魔女です！」
line = "「冷静にして果断。即断即決。凛々しく、美しく、完璧で……最高の魔女です！」"

[[dialogue]]
speaker = "ウェンディ"
# 「それに長官は私の恩人──」
line = "「それに長官は私の恩人──」"

[[dialogue]]
speaker = "ウェンディ"
# （──！　モンスター！　ほら、あの路地にいます）
line = "（──！　モンスター！　ほら、あの路地にいます）"

[[dialogue]]
speaker = "ウェンディ"
# （確かあの個体はステルス能力を付与されていたはず。今は解除しているようですが、気付かれたら厄介です）
line = "（確かあの個体はステルス能力を付与されていたはず。今は解除しているようですが、気付かれたら厄介です）"

[[dialogue]]
speaker = "ウェンディ"
# （慎重に近づいて挟み打ちにしましょう。合図するまで変身は控えてください」
line = "（慎重に近づいて挟み打ちにしましょう。合図するまで変身は控えてください」"

[[dialogue]]
speaker = "ウェンディ"
# （まだですよ、まだ……もう少し……）
line = "（まだですよ、まだ……もう少し……）"

[[dialogue]]
speaker = "ウェンディ"
# 「今です！」
line = "「今です！」"

[[dialogue]]
speaker = "ウェンディ"
# 「逃げ場はありませんよ。アクアシーリン──」
line = "「逃げ場はありませんよ。アクアシーリン──」"

[[dialogue]]
speaker = "？？？"
# 「ダークネスソーン」
line = "「ダークネスソーン」"

[[dialogue]]
speaker = "ウェンディ"
# 「！？　あなたは──」
line = "「！？　あなたは──」"
