[[dialogue]]
speaker = "シュティレ"
# 「どちら様と訊ねられましたので、改めて名乗らせていただきます」
line = "「どちら様と訊ねられましたので、改めて名乗らせていただきます」"

[[dialogue]]
speaker = "シュティレ"
# 「私は不動シュティレ。購買部の美少女看板娘、その２号を担っております」
line = "「私は不動シュティレ。購買部の美少女看板娘、その２号を担っております」"

[[dialogue]]
speaker = "シュティレ"
# 「流星学園附属の１年生。天使ですが人間界生まれの人間界育ち。趣味はロボットアニメ鑑賞とラーメン屋めぐり。嫌いなものは納豆です」
line = "「流星学園附属の１年生。天使ですが人間界生まれの人間界育ち。趣味はロボットアニメ鑑賞とラーメン屋めぐり。嫌いなものは納豆です」"

[[dialogue]]
speaker = "アナ"
# 「えっと、これはご丁寧にどうも……？」
line = "「えっと、これはご丁寧にどうも……？」"

[[dialogue]]
speaker = "シュティレ"
# 「ちなみに、天才錬金術師であるアニマ先輩の弟子もやっております。錬金術師の弟子です」
line = "「ちなみに、天才錬金術師であるアニマ先輩の弟子もやっております。錬金術師の弟子です」"

[[dialogue]]
speaker = "unk"
# そこ、一番に喋るべき情報じゃない！？
line = "そこ、一番に喋るべき情報じゃない！？"

[[dialogue]]
speaker = "シュティレ"
# 「実はこれも作戦なのです」
line = "「実はこれも作戦なのです」"

[[dialogue]]
speaker = "シュティレ"
# 「最も大切な情報を最後にお伝えすることで、お相手に強く印象付けることが可能となります。シュティレの頭脳プレーです。ぶいぶい」
line = "「最も大切な情報を最後にお伝えすることで、お相手に強く印象付けることが可能となります。シュティレの頭脳プレーです。ぶいぶい」"

[[dialogue]]
speaker = "アナ"
# 「なるほど、独特の雰囲気を持ったお方のようですね。流石はアニマ先輩の弟子……初耳ですが」
line = "「なるほど、独特の雰囲気を持ったお方のようですね。流石はアニマ先輩の弟子……初耳ですが」"

[[dialogue]]
speaker = "アナ"
# 「──ご挨拶が遅れました、私はアナ。新星学園星徒会の副会長をしています。和菓子が三度のご飯より大好きです。ぶいぶい」
line = "「──ご挨拶が遅れました、私はアナ。新星学園星徒会の副会長をしています。和菓子が三度のご飯より大好きです。ぶいぶい」"

[[dialogue]]
speaker = "シュティレ"
# 「まさか『ピース返し』とは……高度な技をお持ちですね、アナ先輩」
line = "「まさか『ピース返し』とは……高度な技をお持ちですね、アナ先輩」"

[[dialogue]]
speaker = "アナ"
# 「フ……あなたこそ、附属１年とは思えぬ実力です」
line = "「フ……あなたこそ、附属１年とは思えぬ実力です」"

[[dialogue]]
speaker = "unk"
# ルールを説明してもらえる？？？
line = "ルールを説明してもらえる？？？"

[[dialogue]]
speaker = "アナ"
# 「無粋ですよ、会長」
line = "「無粋ですよ、会長」"

[[dialogue]]
speaker = "シュティレ"
# 「そちらの先輩は……まだまだ我々と渡り合える<b>カルマ</b>はお持ちではないようです」
line = "「そちらの先輩は……まだまだ我々と渡り合える<b>カルマ</b>はお持ちではないようです」"

[[dialogue]]
speaker = "unk"
# （初対面なのに仲いいな……）
line = "（初対面なのに仲いいな……）"

[[dialogue]]
speaker = "unk"
# 絶対適当に喋ってるだけだろ……と思ったが、それこそ無粋なので沈黙を選択した。
line = "絶対適当に喋ってるだけだろ……と思ったが、それこそ無粋なので沈黙を選択した。"

[[dialogue]]
speaker = "シュティレ"
# 「アナ先輩。お近づきの印に、私と１枚、記念撮影よろしいでしょうか」
line = "「アナ先輩。お近づきの印に、私と１枚、記念撮影よろしいでしょうか」"

[[dialogue]]
speaker = "シュティレ"
# 「好きな風景や人物と共に、ピースサインで自撮りするのが３度のご飯より好きなのです」
line = "「好きな風景や人物と共に、ピースサインで自撮りするのが３度のご飯より好きなのです」"

[[dialogue]]
speaker = "アナ"
# 「うむ、よかろー。さ、会長もご一緒に」
line = "「うむ、よかろー。さ、会長もご一緒に」"

[[dialogue]]
speaker = "シュティレ"
# 「新星学園の会長と写真が撮れるなんて光栄です。では失礼します」
line = "「新星学園の会長と写真が撮れるなんて光栄です。では失礼します」"

[[dialogue]]
speaker = "シュティレ"
# 「タイマーを起動します。ポーズはピースサインにて。３、２、１──ぶいっ」
line = "「タイマーを起動します。ポーズはピースサインにて。３、２、１──ぶいっ」"

[[dialogue]]
speaker = "アナ"
# 「ぶい」
line = "「ぶい」"

[[dialogue]]
speaker = "unk"
# ぶ、ぶい？（ピースをする）
line = "ぶ、ぶい？（ピースをする）"

[[dialogue]]
speaker = "シュティレ"
# 「思い出のメモリーをゲット。つきましてはＤＩＳＣの連絡先交換を。写真、お送りします」
line = "「思い出のメモリーをゲット。つきましてはＤＩＳＣの連絡先交換を。写真、お送りします」"

[[dialogue]]
speaker = "アナ"
# 「早速ありがとうございます。ところでシュティレさん。私たち、あなたのお師匠様に用事があるのですが……」
line = "「早速ありがとうございます。ところでシュティレさん。私たち、あなたのお師匠様に用事があるのですが……」"

[[dialogue]]
speaker = "シュティレ"
# 「はい。マスターは不在……だったのですが──前方数メートル先、お姿を発見しました」
line = "「はい。マスターは不在……だったのですが──前方数メートル先、お姿を発見しました」"

[[dialogue]]
speaker = "アニマ"
# 「──やぁ、会長にアナ。呼び出したのに席を外してしまってすまないネ」
line = "「──やぁ、会長にアナ。呼び出したのに席を外してしまってすまないネ」"

[[dialogue]]
speaker = "アニマ"
# 「ちょ～っと実験室でトラブルがあってネ。遅刻してしまったようだ、面目ない」
line = "「ちょ～っと実験室でトラブルがあってネ。遅刻してしまったようだ、面目ない」"

[[dialogue]]
speaker = "unk"
# ──彼女は、新星学園３年生のアニマ先輩。学園きっての錬金術師であり、その発明には毎度のことながら驚かされている。
line = "──彼女は、新星学園３年生のアニマ先輩。学園きっての錬金術師であり、その発明には毎度のことながら驚かされている。"

[[dialogue]]
speaker = "unk"
# 守護天使の義体を作成したり、人工戦闘服の理論を組み立てたり。彼女の作り出す奇蹟によって、俺たちは何度も命を救われてきた。
line = "守護天使の義体を作成したり、人工戦闘服の理論を組み立てたり。彼女の作り出す奇蹟によって、俺たちは何度も命を救われてきた。"

[[dialogue]]
speaker = "unk"
# ただ……ぶっ飛んだ副作用のある薬を嬉々として飲ませてくるのだけは、何とかしてほしかったりする。
line = "ただ……ぶっ飛んだ副作用のある薬を嬉々として飲ませてくるのだけは、何とかしてほしかったりする。"

[[dialogue]]
speaker = "アニマ"
# 「フヒ。その様子だと、シュティレとはずいぶん打ち解けたようだナ？」
line = "「フヒ。その様子だと、シュティレとはずいぶん打ち解けたようだナ？」"

[[dialogue]]
speaker = "アナ"
# 「はい。しかし驚きました。まさかアニマ先輩が弟子を取っていただなんて」
line = "「はい。しかし驚きました。まさかアニマ先輩が弟子を取っていただなんて」"

[[dialogue]]
speaker = "アニマ"
# 「いや？　アニマは弟子なんか取っていないゾ？」
line = "「いや？　アニマは弟子なんか取っていないゾ？」"

[[dialogue]]
speaker = "アナ"
# 「え、でも……」
line = "「え、でも……」"

[[dialogue]]
speaker = "シュティレ"
# 「どうも。マスターの弟子をやってます。ぶい」
line = "「どうも。マスターの弟子をやってます。ぶい」"

[[dialogue]]
speaker = "アニマ"
# 「フヒヒ。実は認めていないんだナ、これが！」
line = "「フヒヒ。実は認めていないんだナ、これが！」"

[[dialogue]]
speaker = "シュティレ"
# 「どうも。マスターの弟子（仮）をやってます。ぶい」
line = "「どうも。マスターの弟子（仮）をやってます。ぶい」"

[[dialogue]]
speaker = "アナ"
# 「えぇえ……？」
line = "「えぇえ……？」"

[[dialogue]]
speaker = "unk"
# 弟子じゃなかったの！？
line = "弟子じゃなかったの！？"

[[dialogue]]
speaker = "アニマ"
# 「ちょっと前に、錬金術を習いたいと言って訪ねて来たんだがネ。実験の時間が減ってしまうのは困るので、断ったんダ」
line = "「ちょっと前に、錬金術を習いたいと言って訪ねて来たんだがネ。実験の時間が減ってしまうのは困るので、断ったんダ」"

[[dialogue]]
speaker = "アニマ"
# 「なのにあんまりしつこいから、近くで見て盗む分には構わないって言ってあるんだヨ」
line = "「なのにあんまりしつこいから、近くで見て盗む分には構わないって言ってあるんだヨ」"

[[dialogue]]
speaker = "シュティレ"
# 「好きにしろと言われたので、好きにさせてもらってます」
line = "「好きにしろと言われたので、好きにさせてもらってます」"

[[dialogue]]
speaker = "アニマ"
# 「まぁ店番を頼めるのは助かっているヨ。見てのとおりオモシロイ奴だから近くに置いてるわけだナ♪」
line = "「まぁ店番を頼めるのは助かっているヨ。見てのとおりオモシロイ奴だから近くに置いてるわけだナ♪」"

[[dialogue]]
speaker = "シュティレ"
# 「こうやってお傍に控えていれば、いずれマスターも<ruby=きょうきん>胸襟</ruby>を開いてくれるはず。目指せ、マスターとも仲良し自撮りピクチャー」
line = "「こうやってお傍に控えていれば、いずれマスターも<ruby>胸襟<rt>きょうきん</rt></ruby>を開いてくれるはず。目指せ、マスターとも仲良し自撮りピクチャー」"

[[dialogue]]
speaker = "アニマ"
# 「フヒヒ。アニマは写真が嫌いなんダ。何度おねだりしても無駄だヨ？」
line = "「フヒヒ。アニマは写真が嫌いなんダ。何度おねだりしても無駄だヨ？」"

[[dialogue]]
speaker = "シュティレ"
# 「諦めません、勝つまでは」
line = "「諦めません、勝つまでは」"

[[dialogue]]
speaker = "アナ"
# 「……アニマ先輩とは、また違った意味で変わったお方のようですね」
line = "「……アニマ先輩とは、また違った意味で変わったお方のようですね」"

[[dialogue]]
speaker = "unk"
# アナの感想に、俺は首肯するしかないのだった。
line = "アナの感想に、俺は首肯するしかないのだった。"

[[dialogue]]
speaker = "アニマ"
# 「アナ、これが例の機械型モンスターを弱体化させる新薬──」
line = "「アナ、これが例の機械型モンスターを弱体化させる新薬──」"

[[dialogue]]
speaker = "アニマ"
# 「名付けて『ヨワッチクナール』ダ！」
line = "「名付けて『ヨワッチクナール』ダ！」"

[[dialogue]]
speaker = "シュティレ"
# 「流石はマスター。ネーミングセンスも一級品です。惚れ直しました」
line = "「流石はマスター。ネーミングセンスも一級品です。惚れ直しました」"

[[dialogue]]
speaker = "アナ"
# 「個人的にはあまり良くないセンスかと思いますが、期待は膨らみます。アニマ先輩お手製となれば、効果は抜群でしょう」
line = "「個人的にはあまり良くないセンスかと思いますが、期待は膨らみます。アニマ先輩お手製となれば、効果は抜群でしょう」"

[[dialogue]]
speaker = "アニマ"
# 「ン～、それなんだがネ。実はこの弱体化薬、まだ試作段階なんダ」
line = "「ン～、それなんだがネ。実はこの弱体化薬、まだ試作段階なんダ」"

[[dialogue]]
speaker = "アニマ"
# 「小瓶に入っている液体……コイツをモンスターにぶちまければいいんダガ、体の核とでも呼べる部分にしっかりとしみこませなければならナイ」
line = "「小瓶に入っている液体……コイツをモンスターにぶちまければいいんダガ、体の核とでも呼べる部分にしっかりとしみこませなければならナイ」"

[[dialogue]]
speaker = "アナ"
# 「……機械型モンスターは装甲が分厚い。薬効が出る前に弾かれてしまう、と？」
line = "「……機械型モンスターは装甲が分厚い。薬効が出る前に弾かれてしまう、と？」"

[[dialogue]]
speaker = "アニマ"
# 「話が早くて助かるヨ。そこが今の課題だナ。どうやって装甲を打ち破るか……」
line = "「話が早くて助かるヨ。そこが今の課題だナ。どうやって装甲を打ち破るか……」"

[[dialogue]]
speaker = "アニマ"
# 「別の薬品も混ぜて装甲を溶かすか、ウイルスのようにモンスターの体内で薬品が増殖するように配合を組み立て直すか……悩みどころダ」
line = "「別の薬品も混ぜて装甲を溶かすか、ウイルスのようにモンスターの体内で薬品が増殖するように配合を組み立て直すか……悩みどころダ」"

[[dialogue]]
speaker = "アニマ"
# 「そういうワケで、開発もちょっと壁に当たっているんダ。しばらく追加の時間をもらえるかナ？」
line = "「そういうワケで、開発もちょっと壁に当たっているんダ。しばらく追加の時間をもらえるかナ？」"

[[dialogue]]
speaker = "アナ"
# 「それはもちろん問題ありません。よろしくお願いします」
line = "「それはもちろん問題ありません。よろしくお願いします」"

[[dialogue]]
speaker = "アニマ"
# 「フヒ。報酬はいつもの……」
line = "「フヒ。報酬はいつもの……」"

[[dialogue]]
speaker = "アナ"
# 「はい。うちの会長を煮るなり焼くなり、お好きにどうぞ」
line = "「はい。うちの会長を煮るなり焼くなり、お好きにどうぞ」"

[[dialogue]]
speaker = "unk"
# 俺のことを売らないで、アナ！
line = "俺のことを売らないで、アナ！"

[[dialogue]]
speaker = "アナ"
# 「必要な犠牲でした。アーメン」
line = "「必要な犠牲でした。アーメン」"

[[dialogue]]
speaker = "アニマ"
# 「フヒヒッ♪　なーに、会長。少しの間、気持ち良くなるだけダ。怖くないヨ？」
line = "「フヒヒッ♪　なーに、会長。少しの間、気持ち良くなるだけダ。怖くないヨ？」"

[[dialogue]]
speaker = "unk"
# 逆に怖いし痛い方がまだマシだ！
line = "逆に怖いし痛い方がまだマシだ！"

[[dialogue]]
speaker = "シュティレ"
# 「──マスター、少しよろしいでしょうか」
line = "「──マスター、少しよろしいでしょうか」"

[[dialogue]]
speaker = "アニマ"
# 「なんだ、シュティレ。マスターじゃないけど話は聞くゾ？」
line = "「なんだ、シュティレ。マスターじゃないけど話は聞くゾ？」"

[[dialogue]]
speaker = "シュティレ"
# 「その装甲を破るアイデア、私に任せていただけませんか？　我に策あり、です」
line = "「その装甲を破るアイデア、私に任せていただけませんか？　我に策あり、です」"

[[dialogue]]
speaker = "アニマ"
# 「──フム、なるほど。シュティレの知識と技術、もしかしたら役に立つかもしれないナ」
line = "「──フム、なるほど。シュティレの知識と技術、もしかしたら役に立つかもしれないナ」"

[[dialogue]]
speaker = "アニマ"
# 「会長。シュティレはこう見えて、アニマとは違ったベクトルに突き抜けた才能を持っていル」
line = "「会長。シュティレはこう見えて、アニマとは違ったベクトルに突き抜けた才能を持っていル」"

[[dialogue]]
speaker = "アニマ"
# 「アナログ錬金術師のアニマとは正反対の、機械技術に特化した子なんダ」
line = "「アナログ錬金術師のアニマとは正反対の、機械技術に特化した子なんダ」"

[[dialogue]]
speaker = "アニマ"
# 「星力を動力源とした、機械兵器の製造を行える子でネ。アニマとは違ったアプローチも取れるはず」
line = "「星力を動力源とした、機械兵器の製造を行える子でネ。アニマとは違ったアプローチも取れるはず」"

[[dialogue]]
speaker = "アニマ"
# 「いいダロウ、やってみろシュティレ！　どちらがモンスターの装甲を突破するアイデアを先に出せるか、勝負だナ！」
line = "「いいダロウ、やってみろシュティレ！　どちらがモンスターの装甲を突破するアイデアを先に出せるか、勝負だナ！」"

[[dialogue]]
speaker = "シュティレ"
# 「嬉しいです。この問題をクリアすれば、マスターに弟子と認めていただける。ワクワクします」
line = "「嬉しいです。この問題をクリアすれば、マスターに弟子と認めていただける。ワクワクします」"

[[dialogue]]
speaker = "アニマ"
# 「フヒヒ、しれっとご褒美を加えるんじゃない！　上手くいっても弟子にはしないゾ？」
line = "「フヒヒ、しれっとご褒美を加えるんじゃない！　上手くいっても弟子にはしないゾ？」"

[[dialogue]]
speaker = "シュティレ"
# 「残念です。また振られてしまいました。でも諦めません」
line = "「残念です。また振られてしまいました。でも諦めません」"

[[dialogue]]
speaker = "アニマ"
# 「さて、ではアニマは実験室に戻る。店番は頼んだゾ、シュティレ！」
line = "「さて、ではアニマは実験室に戻る。店番は頼んだゾ、シュティレ！」"

[[dialogue]]
speaker = "シュティレ"
# 「イエス、マスター。粉骨砕身の店番、お見せします」
line = "「イエス、マスター。粉骨砕身の店番、お見せします」"

[[dialogue]]
speaker = "アナ"
# 「都合のいい時だけ、弟子のような扱いをしている気が……」
line = "「都合のいい時だけ、弟子のような扱いをしている気が……」"

[[dialogue]]
speaker = "アナ"
# 「アニマ先輩に良いように使われているようですが……大丈夫なのですか？」
line = "「アニマ先輩に良いように使われているようですが……大丈夫なのですか？」"

[[dialogue]]
speaker = "シュティレ"
# 「問題ありません。雨垂れ石を穿つ、と申します。こういう小さな積み重ねが、いつかマスターの心を溶かすのです」
line = "「問題ありません。雨垂れ石を穿つ、と申します。こういう小さな積み重ねが、いつかマスターの心を溶かすのです」"

[[dialogue]]
speaker = "アナ"
# 「……あなたも、目標に向かって頑張っているんですね」
line = "「……あなたも、目標に向かって頑張っているんですね」"

[[dialogue]]
speaker = "シュティレ"
# 「……あなた『も』？」
line = "「……あなた『も』？」"

[[dialogue]]
speaker = "アナ"
# 「いえ。良かったら、私にもシュティレさんの作業を手伝わせてくれませんか？」
line = "「いえ。良かったら、私にもシュティレさんの作業を手伝わせてくれませんか？」"

[[dialogue]]
speaker = "アナ"
# 「元々、弱体化薬の制作は星徒会からの依頼ですし。それにアニマ先輩が認める、あなたの才能にも興味があります」
line = "「元々、弱体化薬の制作は星徒会からの依頼ですし。それにアニマ先輩が認める、あなたの才能にも興味があります」"

[[dialogue]]
speaker = "アナ"
# 「及ばずながらお手伝いさせていただければ、と」
line = "「及ばずながらお手伝いさせていただければ、と」"

[[dialogue]]
speaker = "シュティレ"
# 「なんと。新星学園が誇る２人の天才──マスターと並ぶ逸材であるアナ先輩のサポートとは。これはもう勝ち確というやつです」
line = "「なんと。新星学園が誇る２人の天才──マスターと並ぶ逸材であるアナ先輩のサポートとは。これはもう勝ち確というやつです」"

[[dialogue]]
speaker = "シュティレ"
# 「ではこれからは、親しみを込めて『アナお姉ちゃん』と呼ばせていただきます。ぶい」
line = "「ではこれからは、親しみを込めて『アナお姉ちゃん』と呼ばせていただきます。ぶい」"

[[dialogue]]
speaker = "アナ"
# 「い、いきなり距離を詰めてきますね……？　いえ、全然いいんですが」
line = "「い、いきなり距離を詰めてきますね……？　いえ、全然いいんですが」"

[[dialogue]]
speaker = "unk"
# 俺も力を貸すよ
line = "俺も力を貸すよ"

[[dialogue]]
speaker = "シュティレ"
# 「ありがとうございます。それでは会長とアナお姉ちゃん」
line = "「ありがとうございます。それでは会長とアナお姉ちゃん」"

[[dialogue]]
speaker = "シュティレ"
# 「今日から機械型モンスターの装甲を破るための発明に取り掛かりますので、製作に少々お時間をいただけますと幸いです」
line = "「今日から機械型モンスターの装甲を破るための発明に取り掛かりますので、製作に少々お時間をいただけますと幸いです」"

[[dialogue]]
speaker = "unk"
# 独特な距離感を持つ、自称・錬金術師の弟子、シュティレ。
line = "独特な距離感を持つ、自称・錬金術師の弟子、シュティレ。"

[[dialogue]]
speaker = "unk"
# 俺とアナは、彼女の手伝いをすることになったのだった。
line = "俺とアナは、彼女の手伝いをすることになったのだった。"
