[[dialogue]]
speaker = "unk"
# マムに訓練指導してもらうようになってから、１週間が経過した。
line = "マムに訓練指導してもらうようになってから、１週間が経過した。"

[[dialogue]]
speaker = "マハムート"
# 「アム！　このままスパイク行くわよ！」
line = "「アム！　このままスパイク行くわよ！」"

[[dialogue]]
speaker = "アム"
# 「はい！　どんと来いです！」
line = "「はい！　どんと来いです！」"

[[dialogue]]
speaker = "マハムート"
# 「竜の火球、受け止めてみなさい！　スパイクメガフレアッ！」
line = "「竜の火球、受け止めてみなさい！　スパイクメガフレアッ！」"

[[dialogue]]
speaker = "アム"
# 「重力バリアー、集中展開！　はあぁぁぁっ！」
line = "「重力バリアー、集中展開！　はあぁぁぁっ！」"

[[dialogue]]
speaker = "マトイ"
# （アムちゃん、すごい……！）
line = "（アムちゃん、すごい……！）"

[[dialogue]]
speaker = "マトイ"
# （さっきから第３波まで、マムが連続でアタックを繰り返してるのに、１つもボールを落とさず、捌き切ってる……！　私はまだ第２波で苦戦してるのに……）
line = "（さっきから第３波まで、マムが連続でアタックを繰り返してるのに、１つもボールを落とさず、捌き切ってる……！　私はまだ第２波で苦戦してるのに……）"

[[dialogue]]
speaker = "マトイ"
# （附属校一の盾使いと言われるだけある……やっぱり、普通じゃないよね）
line = "（附属校一の盾使いと言われるだけある……やっぱり、普通じゃないよね）"

[[dialogue]]
speaker = "マトイ"
# （ただでさえ堅牢な防御力の持ち主なのに、水着フォームで重力バリアーを張れるようになって、まさに『難攻不落』を体現してる）
line = "（ただでさえ堅牢な防御力の持ち主なのに、水着フォームで重力バリアーを張れるようになって、まさに『難攻不落』を体現してる）"

[[dialogue]]
speaker = "マトイ"
# （純粋な防御能力で、私は絶対に負けてる……私の水着フォームの力は、回復寄りのものだったし……）
line = "（純粋な防御能力で、私は絶対に負けてる……私の水着フォームの力は、回復寄りのものだったし……）"

[[dialogue]]
speaker = "マトイ"
# （……私も盾使いとして、何か新しい力を手に入れられたら……）
line = "（……私も盾使いとして、何か新しい力を手に入れられたら……）"

[[dialogue]]
speaker = "マトイ"
# 「休憩中にごめんね、会長」
line = "「休憩中にごめんね、会長」"

[[dialogue]]
speaker = "unk"
# どうしたんだ？
line = "どうしたんだ？"

[[dialogue]]
speaker = "マトイ"
# 「――実はね、会長にお願いしたいことがあって……」
line = "「――実はね、会長にお願いしたいことがあって……」"

[[dialogue]]
speaker = "マトイ"
# 「前に、『アルケインコード』を試してもらったことがあったでしょ？」
line = "「前に、『アルケインコード』を試してもらったことがあったでしょ？」"

[[dialogue]]
speaker = "unk"
# アルケインコード。それは少し前、伝説の『クルセイダース』の子孫だという女の子――メイプル・モノクラウンが教えてくれた、魔王だけが使えるという秘技だ。
line = "アルケインコード。それは少し前、伝説の『クルセイダース』の子孫だという女の子――メイプル・モノクラウンが教えてくれた、魔王だけが使えるという秘技だ。"

[[dialogue]]
speaker = "unk"
# ３０００年前の魔王ラクシスから受け継がれるそのコードの真名は、『アルケインノヴァエクストリーム』。
line = "３０００年前の魔王ラクシスから受け継がれるそのコードの真名は、『アルケインノヴァエクストリーム』。"

[[dialogue]]
speaker = "unk"
# 魔王と絆を結んだ仲間を強化する技で、発動に成功すると、潜在能力を引き出し新たな戦闘服へと覚醒させることができる。
line = "魔王と絆を結んだ仲間を強化する技で、発動に成功すると、潜在能力を引き出し新たな戦闘服へと覚醒させることができる。"

[[dialogue]]
speaker = "マトイ"
# 「あれをもう１度、私に試してもらえないかな？」
line = "「あれをもう１度、私に試してもらえないかな？」"

[[dialogue]]
speaker = "unk"
# それは構わないけど……
line = "それは構わないけど……"

[[dialogue]]
speaker = "unk"
# アルケインコードについては、リクリエとの決戦の前に１度、両星徒会のみんなには試していた。
line = "アルケインコードについては、リクリエとの決戦の前に１度、両星徒会のみんなには試していた。"

[[dialogue]]
speaker = "unk"
# しかし、何か条件を満たせていないのか、発動することはなかった。
line = "しかし、何か条件を満たせていないのか、発動することはなかった。"

[[dialogue]]
speaker = "マトイ"
# 「お願い。ほら、マムに鍛えてもらった今なら、何か変化してるかもしれないし！」
line = "「お願い。ほら、マムに鍛えてもらった今なら、何か変化してるかもしれないし！」"

[[dialogue]]
speaker = "マトイ"
# 「あ、あと一応……」
line = "「あ、あと一応……」"

[[dialogue]]
speaker = "マトイ"
# 「会長との絆は、ちゃんとあると思うし……」
line = "「会長との絆は、ちゃんとあると思うし……」"

[[dialogue]]
speaker = "unk"
# わかった、やってみようと俺は頷いて、試してみることになった。
line = "わかった、やってみようと俺は頷いて、試してみることになった。"

[[dialogue]]
speaker = "unk"
# しかし――
line = "しかし――"

[[dialogue]]
speaker = "unk"
# ……発動しないな
line = "……発動しないな"

[[dialogue]]
speaker = "マトイ"
# 「ですよねー」
line = "「ですよねー」"

[[dialogue]]
speaker = "マトイ"
# （そう……そんな簡単に秘めたる力の覚醒なんて、上手く行くはずがない。当たり前だ）
line = "（そう……そんな簡単に秘めたる力の覚醒なんて、上手く行くはずがない。当たり前だ）"

[[dialogue]]
speaker = "マトイ"
# （だって私は……ヴィーナスや会長みたいに、特別な存在じゃないんだから……）
line = "（だって私は……ヴィーナスや会長みたいに、特別な存在じゃないんだから……）"

[[dialogue]]
speaker = "マトイ"
# （普通の私は、地道に努力するしかない）
line = "（普通の私は、地道に努力するしかない）"

[[dialogue]]
speaker = "マトイ"
# 「……よし。ありがとう、会長」
line = "「……よし。ありがとう、会長」"

[[dialogue]]
speaker = "マトイ"
# 「自分の現状を再確認できた。私、また頑張るから！」
line = "「自分の現状を再確認できた。私、また頑張るから！」"

[[dialogue]]
speaker = "unk"
# そうして、その日の訓練が終わり――
line = "そうして、その日の訓練が終わり――"

[[dialogue]]
speaker = "アム"
# 「マトイ先輩、お疲れ様で～す！　いや～、今日もなかなかハードでしたね～」
line = "「マトイ先輩、お疲れ様で～す！　いや～、今日もなかなかハードでしたね～」"

[[dialogue]]
speaker = "マトイ"
# 「アムちゃん、お疲れ様。今日もすごかったよ。マムの攻撃をあれだけ捌き続けるなんて、普通じゃなかなかできないと思う」
line = "「アムちゃん、お疲れ様。今日もすごかったよ。マムの攻撃をあれだけ捌き続けるなんて、普通じゃなかなかできないと思う」"

[[dialogue]]
speaker = "アム"
# 「そうですか？　えへへっ、いや～、それほどでも～♪」
line = "「そうですか？　えへへっ、いや～、それほどでも～♪」"

[[dialogue]]
speaker = "マトイ"
# 「それに比べて私は……」
line = "「それに比べて私は……」"

[[dialogue]]
speaker = "アム"
# 「？　マトイ先輩……？」
line = "「？　マトイ先輩……？」"

[[dialogue]]
speaker = "マトイ"
# 「新星学園の星徒会役員っていう肩書きばっかりで、やっぱり普通だ……」
line = "「新星学園の星徒会役員っていう肩書きばっかりで、やっぱり普通だ……」"

[[dialogue]]
speaker = "アム"
# 「え？　いやいや、マトイ先輩は会長たちと一緒にリクリエを退けたじゃないですか！」
line = "「え？　いやいや、マトイ先輩は会長たちと一緒にリクリエを退けたじゃないですか！」"

[[dialogue]]
speaker = "アム"
# 「一緒に訓練してて、マトイ先輩の動きはすごく参考になりますよ！　基本をすごく大事にしてるっていうか、お手本って感じで――」
line = "「一緒に訓練してて、マトイ先輩の動きはすごく参考になりますよ！　基本をすごく大事にしてるっていうか、お手本って感じで――」"

[[dialogue]]
speaker = "マトイ"
# 「あはは、ありがとう。でも、アムちゃんには敵わないよ」
line = "「あはは、ありがとう。でも、アムちゃんには敵わないよ」"

[[dialogue]]
speaker = "マトイ"
# 「私も先輩として、もっと頑張らないとね」
line = "「私も先輩として、もっと頑張らないとね」"

[[dialogue]]
speaker = "アム"
# 「…………う～ん」
line = "「…………う～ん」"

[[dialogue]]
speaker = "アム"
# 「そうだ、マトイ先輩！　明日って訓練休みじゃないですか」
line = "「そうだ、マトイ先輩！　明日って訓練休みじゃないですか」"

[[dialogue]]
speaker = "マトイ"
# 「ああ、うん。マムは用事があるからって……」
line = "「ああ、うん。マムは用事があるからって……」"

[[dialogue]]
speaker = "アム"
# 「もし予定空いてたら――」
line = "「もし予定空いてたら――」"

[[dialogue]]
speaker = "アム"
# 「あたしとデートしませんか？」
line = "「あたしとデートしませんか？」"

[[dialogue]]
speaker = "マトイ"
# 「へ！？」
line = "「へ！？」"

[[dialogue]]
speaker = "unk"
# 突然の誘いに、マトイは目をぱちくりさせてしまうのだった――
line = "突然の誘いに、マトイは目をぱちくりさせてしまうのだった――"
