[[dialogue]]
speaker = "unk"
# 第一次試験を終えた週明け──月曜日。
line = "第一次試験を終えた週明け──月曜日。"

[[dialogue]]
speaker = "セナリィ"
# 「２人とも時間通りに揃いましたわね。では、第二次試験を始めさせていただきます」
line = "「２人とも時間通りに揃いましたわね。では、第二次試験を始めさせていただきます」"

[[dialogue]]
speaker = "セナリィ"
# 「第二次試験の内容は──資金調達ですわ！」
line = "「第二次試験の内容は──資金調達ですわ！」"

[[dialogue]]
speaker = "ミウ"
# 「資金調達、ですか？」
line = "「資金調達、ですか？」"

[[dialogue]]
speaker = "セナリィ"
# 「ええ、金は天下の回り物。円滑な会社経営は、潤沢な資金から」
line = "「ええ、金は天下の回り物。円滑な会社経営は、潤沢な資金から」"

[[dialogue]]
speaker = "セナリィ"
# 「『幸せはお金で買えない』などと綺麗ごとを宣う輩もいますが、お金で買える幸せも数多く存在してます。むしろ、幸せ＝お金までありますわ」
line = "「『幸せはお金で買えない』などと綺麗ごとを宣う輩もいますが、お金で買える幸せも数多く存在してます。むしろ、幸せ＝お金までありますわ」"

[[dialogue]]
speaker = "ミウ"
# 「セナリィ社長が常々仰っている『悪即善』ですね」
line = "「セナリィ社長が常々仰っている『悪即善』ですね」"

[[dialogue]]
speaker = "セナリィ"
# 「わずかなお金がないばかりに、公園で水道水をすすり、コンビニの廃棄弁当を漁ることで空腹を満たす同業がどれだけいることやら……クゥゥッ……！」
line = "「わずかなお金がないばかりに、公園で水道水をすすり、コンビニの廃棄弁当を漁ることで空腹を満たす同業がどれだけいることやら……クゥゥッ……！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「えーと……資金調達をするっていう話ですよね？」
line = "「えーと……資金調達をするっていう話ですよね？」"

[[dialogue]]
speaker = "セナリィ"
# 「ハッ、そうでしたわ。ヒマワリ、あなたには３０万テルスをお渡ししますわ」
line = "「ハッ、そうでしたわ。ヒマワリ、あなたには３０万テルスをお渡ししますわ」"

[[dialogue]]
speaker = "ヒマワリ"
# 「え、お小遣いですか？　やったー！」
line = "「え、お小遣いですか？　やったー！」"

[[dialogue]]
speaker = "セナリィ"
# 「そんなわけがないでしょう！？　これはあなたへの投資です。手段は問いません、この元金を増やして、週末までに返却なさい！」
line = "「そんなわけがないでしょう！？　これはあなたへの投資です。手段は問いません、この元金を増やして、週末までに返却なさい！」"

[[dialogue]]
speaker = "セナリィ"
# 「いくらでも構いませんが、増えた金額に応じて、採用・不採用を決めさせていただきます」
line = "「いくらでも構いませんが、増えた金額に応じて、採用・不採用を決めさせていただきます」"

[[dialogue]]
speaker = "セナリィ"
# 「もちろん、無一文になってしまったら失格。度を越した違法行為も失格ですわ。３０万テルスを失った場合、なんとしてでも取り立てさせてもらいます」
line = "「もちろん、無一文になってしまったら失格。度を越した違法行為も失格ですわ。３０万テルスを失った場合、なんとしてでも取り立てさせてもらいます」"

[[dialogue]]
speaker = "セナリィ"
# （こんなチビッ子に３０万テルスもの大金を託すなんて、無茶ぶりが過ぎるけど……フフフ、ゴールデングースの厳しさ、思い知りなさい）
line = "（こんなチビッ子に３０万テルスもの大金を託すなんて、無茶ぶりが過ぎるけど……フフフ、ゴールデングースの厳しさ、思い知りなさい）"

[[dialogue]]
speaker = "セナリィ"
# （もちろん、金額が変動していなければ問題外。子どものお小遣い程度の額が増えていたところで不採用よ）
line = "（もちろん、金額が変動していなければ問題外。子どものお小遣い程度の額が増えていたところで不採用よ）"

[[dialogue]]
speaker = "ヒマワリ"
# 「そんな簡単でいいんだー！　やっぱり社長はスゴい上に優しいんですねー！」
line = "「そんな簡単でいいんだー！　やっぱり社長はスゴい上に優しいんですねー！」"

[[dialogue]]
speaker = "セナリィ"
# 「フフフ、そう、とても簡単──え？」
line = "「フフフ、そう、とても簡単──え？」"

[[dialogue]]
speaker = "ヒマワリ"
# 「手段は問わないんですよね……それなら、あたし的に手堅いのは、やっぱり株式投資かな。週明けから週末ならタイミング的にもバッチシですし」
line = "「手段は問わないんですよね……それなら、あたし的に手堅いのは、やっぱり株式投資かな。週明けから週末ならタイミング的にもバッチシですし」"

[[dialogue]]
speaker = "セナリィ"
# 「え、ええ、もちろん構わないけれど……でも、その、株式投資って……とても難しいのではなくて？」
line = "「え、ええ、もちろん構わないけれど……でも、その、株式投資って……とても難しいのではなくて？」"

[[dialogue]]
speaker = "ヒマワリ"
# 「そんなことないですよー。流れを見てれば、なんとな～くわかりますし。カジノみたいに最終的に胴元が儲かる仕組みでもないですから」
line = "「そんなことないですよー。流れを見てれば、なんとな～くわかりますし。カジノみたいに最終的に胴元が儲かる仕組みでもないですから」"

[[dialogue]]
speaker = "ヒマワリ"
# 「でも、せっかく増やすんなら３０万テルスじゃちょっとなぁ……社長、あたしの資産も入れてもいいですか？　あたしもリスクを背負った方が、緊張感あって面白いんで！」
line = "「でも、せっかく増やすんなら３０万テルスじゃちょっとなぁ……社長、あたしの資産も入れてもいいですか？　あたしもリスクを背負った方が、緊張感あって面白いんで！」"

[[dialogue]]
speaker = "セナリィ"
# 「え？　ええ、まあ、構いませんけれど……」
line = "「え？　ええ、まあ、構いませんけれど……」"

[[dialogue]]
speaker = "ヒマワリ"
# 「それじゃ今日から１週間ですね！　頑張るぞー！」
line = "「それじゃ今日から１週間ですね！　頑張るぞー！」"

[[dialogue]]
speaker = "ミウ"
# 「ヒマワリちゃん、私に手伝えることがあったら、なんでも言ってね」
line = "「ヒマワリちゃん、私に手伝えることがあったら、なんでも言ってね」"

[[dialogue]]
speaker = "ヒマワリ"
# 「んー、ポチポチするだけだし、特に手伝ってもらうようなこともないかなー。急に世界的大恐慌が来ないことだけ、祈っといて」
line = "「んー、ポチポチするだけだし、特に手伝ってもらうようなこともないかなー。急に世界的大恐慌が来ないことだけ、祈っといて」"

[[dialogue]]
speaker = "unk"
# そして、ただ静かに、第二次試験〆切の金曜日を迎えた。
line = "そして、ただ静かに、第二次試験〆切の金曜日を迎えた。"

[[dialogue]]
speaker = "セナリィ"
# 「ヒマワリさん、第二次試験の締め日です。預けたお金はどうなりました？」
line = "「ヒマワリさん、第二次試験の締め日です。預けたお金はどうなりました？」"

[[dialogue]]
speaker = "セナリィ"
# （つい勢いで彼女に大金を投資してしまったけど、もし無一文になってたら弊社は大損害よ……？）
line = "（つい勢いで彼女に大金を投資してしまったけど、もし無一文になってたら弊社は大損害よ……？）"

[[dialogue]]
speaker = "ヒマワリ"
# 「どーなったかなー……ポチッとな」
line = "「どーなったかなー……ポチッとな」"

[[dialogue]]
speaker = "ヒマワリ"
# 「うん、やっぱりねー。今期の決算報告いい感じだったし、午後から伸びると思ったんだー。カタカタカタ、ッターン！」
line = "「うん、やっぱりねー。今期の決算報告いい感じだったし、午後から伸びると思ったんだー。カタカタカタ、ッターン！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「はい、セナリィ社長、１３７万テルスで利確しました！　お預かりした３０万テルス、手数料プラス税金を差し引いても３倍以上になりましたよー」
line = "「はい、セナリィ社長、１３７万テルスで利確しました！　お預かりした３０万テルス、手数料プラス税金を差し引いても３倍以上になりましたよー」"

[[dialogue]]
speaker = "セナリィ"
# 「はっ？　さ、３倍っ！？　ほ、本当ですわ……３０万が、１００万になってる……！？」
line = "「はっ？　さ、３倍っ！？　ほ、本当ですわ……３０万が、１００万になってる……！？」"

[[dialogue]]
speaker = "ヒマワリ"
# 「最後の最後でちょっぴり下げちゃったのが残念ですけど、ま、上手くいったから結果オーライですよね？」
line = "「最後の最後でちょっぴり下げちゃったのが残念ですけど、ま、上手くいったから結果オーライですよね？」"

[[dialogue]]
speaker = "セナリィ"
# 「え、ええ、もちろんですわ……！　あなた、なかなかやりますわね」
line = "「え、ええ、もちろんですわ……！　あなた、なかなかやりますわね」"

[[dialogue]]
speaker = "ヒマワリ"
# 「えへへー、ありがとうございます♪」
line = "「えへへー、ありがとうございます♪」"

[[dialogue]]
speaker = "セナリィ"
# 「あの……ミウさん？　ヒマワリさんは、どういった方なんですの……？」
line = "「あの……ミウさん？　ヒマワリさんは、どういった方なんですの……？」"

[[dialogue]]
speaker = "ミウ"
# 「ヒマワリちゃんのお父さんって、ベンチャー企業の社長さんなんです。それでヒマワリちゃんも小さい頃からお金の扱いや情勢の読み方を叩きこまれたそうで」
line = "「ヒマワリちゃんのお父さんって、ベンチャー企業の社長さんなんです。それでヒマワリちゃんも小さい頃からお金の扱いや情勢の読み方を叩きこまれたそうで」"

[[dialogue]]
speaker = "ミウ"
# 「ヒマワリちゃん、お小遣いを元手に増やした個人資産も結構あるみたいで。もう一生働かなくても食べていけるんじゃないかな」
line = "「ヒマワリちゃん、お小遣いを元手に増やした個人資産も結構あるみたいで。もう一生働かなくても食べていけるんじゃないかな」"

[[dialogue]]
speaker = "ヒマワリ"
# 「そこまでじゃないよー。あたしの個人資産なんて、ちょっと贅沢したら、あっという間に使い切っちゃうってー」
line = "「そこまでじゃないよー。あたしの個人資産なんて、ちょっと贅沢したら、あっという間に使い切っちゃうってー」"

[[dialogue]]
speaker = "ヒマワリ"
# 「それでも将来の旦那様を養ってあげるくらいはできるかな、えへへ♪」
line = "「それでも将来の旦那様を養ってあげるくらいはできるかな、えへへ♪」"

[[dialogue]]
speaker = "セナリィ"
# （そんな資産を持った子が、どうしてゴールデングースへ……？　危険な仕事で一攫千金を夢見ているわけではないの……？）
line = "（そんな資産を持った子が、どうしてゴールデングースへ……？　危険な仕事で一攫千金を夢見ているわけではないの……？）"

[[dialogue]]
speaker = "ヒマワリ"
# 「それでセナリィ社長！　あたしたちの試験結果は！？」
line = "「それでセナリィ社長！　あたしたちの試験結果は！？」"

[[dialogue]]
speaker = "ミウ"
# 「合格ですか！？　不合格ですか！？」
line = "「合格ですか！？　不合格ですか！？」"

[[dialogue]]
speaker = "セナリィ"
# （ああっ、もう！　そんなキラキラした目で見ないで！）
line = "（ああっ、もう！　そんなキラキラした目で見ないで！）"

[[dialogue]]
speaker = "セナリィ"
# （難癖をつけることもできるけど……１００点満点以上の結果を叩き出したというのに、そんな不正は私の流儀に反するわ）
line = "（難癖をつけることもできるけど……１００点満点以上の結果を叩き出したというのに、そんな不正は私の流儀に反するわ）"

[[dialogue]]
speaker = "セナリィ"
# 「し、仕方ないですわね。２人とも文句なしの合格です。まずは見習いとして雇って差し上げますわ！」
line = "「し、仕方ないですわね。２人とも文句なしの合格です。まずは見習いとして雇って差し上げますわ！」"

[[dialogue]]
speaker = "ヒマワリ"
# 「セナリィ社長の元で働けるー！　やったね、ミウ！」
line = "「セナリィ社長の元で働けるー！　やったね、ミウ！」"

[[dialogue]]
speaker = "ミウ"
# 「ありがとうございます、社長！　やったね、ヒマワリちゃん！」
line = "「ありがとうございます、社長！　やったね、ヒマワリちゃん！」"

[[dialogue]]
speaker = "unk"
# こうして本日付けで、秘密結社ゴールデングースの社員は今までの３倍に増えたのであった。
line = "こうして本日付けで、秘密結社ゴールデングースの社員は今までの３倍に増えたのであった。"
