[[dialogue]]
speaker = "アナ"
# 「バーミリオンイータ……！」
line = "「バーミリオンイータ……！」"

[[dialogue]]
speaker = "アナ"
# 「はぁっ……はぁっ……戦闘終了。自己ベスト更新。ハイスコア……」
line = "「はぁっ……はぁっ……戦闘終了。自己ベスト更新。ハイスコア……」"

[[dialogue]]
speaker = "アナ"
# 「……強くは、なっているはずです。でも」
line = "「……強くは、なっているはずです。でも」"

[[dialogue]]
speaker = "アナ"
# 「ノヴァフォームのために必要な、私のブレイクスルーは、一体どこに……？」
line = "「ノヴァフォームのために必要な、私のブレイクスルーは、一体どこに……？」"

[[dialogue]]
speaker = "アナ"
# 「あぁ……もうすぐ授業ですね……副会長が遅刻したら大ごとです。急がないと……」
line = "「あぁ……もうすぐ授業ですね……副会長が遅刻したら大ごとです。急がないと……」"

[[dialogue]]
speaker = "unk"
# シュティレと出会ってから数日──
line = "シュティレと出会ってから数日──"

[[dialogue]]
speaker = "unk"
# 会長であるクロトがいない時も、アナは懸命に自主鍛錬を続けていた……
line = "会長であるクロトがいない時も、アナは懸命に自主鍛錬を続けていた……"

[[dialogue]]
speaker = "シュティレ"
# 「──会長にアナお姉ちゃん。ここのところ毎日お会いできて嬉しいです。いらっしゃいませ」
line = "「──会長にアナお姉ちゃん。ここのところ毎日お会いできて嬉しいです。いらっしゃいませ」"

[[dialogue]]
speaker = "アナ"
# 「今日も店番に精が出ますね、シュティレさん」
line = "「今日も店番に精が出ますね、シュティレさん」"

[[dialogue]]
speaker = "シュティレ"
# 「はい。私が店番を担うたび、マスターの中で少しずつ好感度が上昇しています。マスター攻略ルートまであと一歩。ぶい」
line = "「はい。私が店番を担うたび、マスターの中で少しずつ好感度が上昇しています。マスター攻略ルートまであと一歩。ぶい」"

[[dialogue]]
speaker = "アナ"
# 「本当にそうなのでしょうか……。私でよければ、あまりシュティレさんをこき使うなと進言もできますが」
line = "「本当にそうなのでしょうか……。私でよければ、あまりシュティレさんをこき使うなと進言もできますが」"

[[dialogue]]
speaker = "シュティレ"
# 「問題ありません。こうして店番をしている時も、発明ノートは逐一つけております」
line = "「問題ありません。こうして店番をしている時も、発明ノートは逐一つけております」"

[[dialogue]]
speaker = "シュティレ"
# 「ところでアナお姉ちゃん。先日の機械型モンスターへのドリル攻撃は、今一つの結果となってしまいました」
line = "「ところでアナお姉ちゃん。先日の機械型モンスターへのドリル攻撃は、今一つの結果となってしまいました」"

[[dialogue]]
speaker = "シュティレ"
# 「そこで私、新たにロマンを感じる武装をいくつかまとめてきたのです。ご意見をいただけますか」
line = "「そこで私、新たにロマンを感じる武装をいくつかまとめてきたのです。ご意見をいただけますか」"

[[dialogue]]
speaker = "アナ"
# 「おー……ノートにびっちりと兵器の構想が……。これは、大型の鉄杭を打ち込む……パイルバンカー？」
line = "「おー……ノートにびっちりと兵器の構想が……。これは、大型の鉄杭を打ち込む……パイルバンカー？」"

[[dialogue]]
speaker = "シュティレ"
# 「ロボットアニメ・<ruby=ゆうしおう>雄姿王</ruby>シリーズを見返していて思ったのです。一転突破で貫くために、パイルバンカーの構造は合理的かと」
line = "「ロボットアニメ・<ruby>雄姿王<rt>ゆうしおう</rt></ruby>シリーズを見返していて思ったのです。一転突破で貫くために、パイルバンカーの構造は合理的かと」"

[[dialogue]]
speaker = "アナ"
# 「素晴らしいですね。それならばこういうのはどうでしょう、杭の先端に爆薬を取り付ける、とか」
line = "「素晴らしいですね。それならばこういうのはどうでしょう、杭の先端に爆薬を取り付ける、とか」"

[[dialogue]]
speaker = "unk"
# ずいぶんと過激だね！？
line = "ずいぶんと過激だね！？"

[[dialogue]]
speaker = "シュティレ"
# 「まさかそのアイデアは……！」
line = "「まさかそのアイデアは……！」"

[[dialogue]]
speaker = "アナ"
# 「はい。シュティレさんがオススメしてくださったギガンドムからヒントを得ました」
line = "「はい。シュティレさんがオススメしてくださったギガンドムからヒントを得ました」"

[[dialogue]]
speaker = "アナ"
# 「爆弾を用いると１回限りの消耗品の武器となってしまいますが、自身の得物を犠牲に敵を撃破するというのもまた──」
line = "「爆弾を用いると１回限りの消耗品の武器となってしまいますが、自身の得物を犠牲に敵を撃破するというのもまた──」"

[[dialogue]]
speaker = "シュティレ"
# 「はい、それもまたロマンです。こんなこともあろうかと、徹甲榴弾の制作も並行しておりました。そちらを転用するとします」
line = "「はい、それもまたロマンです。こんなこともあろうかと、徹甲榴弾の制作も並行しておりました。そちらを転用するとします」"

[[dialogue]]
speaker = "アナ"
# 「グッドタイミング。そうだ、どうせ爆弾を付けるなら、発射式の槍みたいな形状も良いのでは？」
line = "「グッドタイミング。そうだ、どうせ爆弾を付けるなら、発射式の槍みたいな形状も良いのでは？」"

[[dialogue]]
speaker = "シュティレ"
# 「エクセレントです。アイデアがみるみる湧いてきますね」
line = "「エクセレントです。アイデアがみるみる湧いてきますね」"

[[dialogue]]
speaker = "アニマ"
# 「こんにちはダ、諸君。何やら精が出ているようじゃないカ」
line = "「こんにちはダ、諸君。何やら精が出ているようじゃないカ」"

[[dialogue]]
speaker = "シュティレ"
# 「マスター。もしかして可愛い弟子の様子を見に来ていただけたのですか」
line = "「マスター。もしかして可愛い弟子の様子を見に来ていただけたのですか」"

[[dialogue]]
speaker = "アニマ"
# 「フヒ♪　アニマに弟子はいないゾ。シュティレのそのネバーギブアップ根性は評価するが、別件ダ」
line = "「フヒ♪　アニマに弟子はいないゾ。シュティレのそのネバーギブアップ根性は評価するが、別件ダ」"

[[dialogue]]
speaker = "アニマ"
# 「実は弱体化薬の改良中に、ふと新しいアイデアが閃いてネ？　どうだろう会長、この薬を飲んで翼を生やし、大空を飛んでみたくはないカ？」
line = "「実は弱体化薬の改良中に、ふと新しいアイデアが閃いてネ？　どうだろう会長、この薬を飲んで翼を生やし、大空を飛んでみたくはないカ？」"

[[dialogue]]
speaker = "アナ"
# 「本当に別件じゃないですか」
line = "「本当に別件じゃないですか」"

[[dialogue]]
speaker = "unk"
# 人間のままでいさせて……！
line = "人間のままでいさせて……！"

[[dialogue]]
speaker = "アニマ"
# 「ふ～む、残念だナ。今回の薬は自信があるのに……」
line = "「ふ～む、残念だナ。今回の薬は自信があるのに……」"

[[dialogue]]
speaker = "シュティレ"
# 「水臭いです、マスター。私ならいくらでも新薬の実験台に使ってもらって構いません」
line = "「水臭いです、マスター。私ならいくらでも新薬の実験台に使ってもらって構いません」"

[[dialogue]]
speaker = "アニマ"
# 「フヒヒ。シュティレがこの薬を飲むには、ちょっと背が足りないナ！　実に残念ダ」
line = "「フヒヒ。シュティレがこの薬を飲むには、ちょっと背が足りないナ！　実に残念ダ」"

[[dialogue]]
speaker = "アナ"
# 「ジェットコースターじゃないんですから……というか、足りていても許可できません。可愛い後輩を実験に使うのはダメです」
line = "「ジェットコースターじゃないんですから……というか、足りていても許可できません。可愛い後輩を実験に使うのはダメです」"

[[dialogue]]
speaker = "アニマ"
# 「おや？　おやおや？　アナ、ちょっと見ないうちに、ずいぶんとシュティレを可愛がっているみたいじゃないカ？」
line = "「おや？　おやおや？　アナ、ちょっと見ないうちに、ずいぶんとシュティレを可愛がっているみたいじゃないカ？」"

[[dialogue]]
speaker = "シュティレ"
# 「可愛い後輩天使ですから。ぶい」
line = "「可愛い後輩天使ですから。ぶい」"

[[dialogue]]
speaker = "アニマ"
# 「良かったらアナ。キミがシュティレを引き取って、弟子にしてくれてもいいんだゾ？」
line = "「良かったらアナ。キミがシュティレを引き取って、弟子にしてくれてもいいんだゾ？」"

[[dialogue]]
speaker = "シュティレ"
# 「がーん……マスター、冷たい」
line = "「がーん……マスター、冷たい」"

[[dialogue]]
speaker = "シュティレ"
# 「ですが、そんなところも素敵です。これからも粘着して、いつか弟子と言わせて見せましょう」
line = "「ですが、そんなところも素敵です。これからも粘着して、いつか弟子と言わせて見せましょう」"

[[dialogue]]
speaker = "アニマ"
# 「フヒヒヒっ♪　しつこいヤツだナ！　だがそのガッツは素晴らしイ！」
line = "「フヒヒヒっ♪　しつこいヤツだナ！　だがそのガッツは素晴らしイ！」"

[[dialogue]]
speaker = "アナ"
# 「……というかアニマ先輩。ちょっと気になっていることがあるのですが」
line = "「……というかアニマ先輩。ちょっと気になっていることがあるのですが」"

[[dialogue]]
speaker = "アニマ"
# 「フヒッ？　何かナ」
line = "「フヒッ？　何かナ」"

[[dialogue]]
speaker = "アナ"
# 「なぜシュティレさんを弟子と認めてあげないのですか？」
line = "「なぜシュティレさんを弟子と認めてあげないのですか？」"

[[dialogue]]
speaker = "アナ"
# 「プリマステラでこそありませんが、彼女は優秀な星騎士です。普通は附属１年生で、実戦投入可能な機械式の武器なんて作れません」
line = "「プリマステラでこそありませんが、彼女は優秀な星騎士です。普通は附属１年生で、実戦投入可能な機械式の武器なんて作れません」"

[[dialogue]]
speaker = "アナ"
# 「間違いなく天性のスキルです。それにアニマ先輩のおかしなノリにもついていける人となると、もっと少ないでしょう」
line = "「間違いなく天性のスキルです。それにアニマ先輩のおかしなノリにもついていける人となると、もっと少ないでしょう」"

[[dialogue]]
speaker = "アニマ"
# 「フヒヒ♪　そうだろう、そうだろう。アニマもそう思うヨ」
line = "「フヒヒ♪　そうだろう、そうだろう。アニマもそう思うヨ」"

[[dialogue]]
speaker = "アナ"
# 「ではなぜです？　慕われているのなら、育ててあげるのも学園の先輩としての役目だと思うのですが」
line = "「ではなぜです？　慕われているのなら、育ててあげるのも学園の先輩としての役目だと思うのですが」"

[[dialogue]]
speaker = "アニマ"
# 「ン～、弟子にしない理由、か……そうだなぁ。シュティレはあれだナ、アニマから見て──」
line = "「ン～、弟子にしない理由、か……そうだなぁ。シュティレはあれだナ、アニマから見て──」"

[[dialogue]]
speaker = "アニマ"
# 「──圧倒的にロマンが足りなイ！！」
line = "「──圧倒的にロマンが足りなイ！！」"

[[dialogue]]
speaker = "シュティレ"
# 「えええっ──！？」
line = "「えええっ──！？」"

[[dialogue]]
speaker = "アナ"
# 「……驚きました。そんな大きな声も出せるんですね。シュティレさん」
line = "「……驚きました。そんな大きな声も出せるんですね。シュティレさん」"

[[dialogue]]
speaker = "シュティレ"
# 「他の何が足りないと言われても驚きませんが、ロマンが足りないという発言は予想していませんでした。計算外です」
line = "「他の何が足りないと言われても驚きませんが、ロマンが足りないという発言は予想していませんでした。計算外です」"

[[dialogue]]
speaker = "シュティレ"
# 「あの、マスター……僭越ながら、ドリルはロマンの塊なのですが……」
line = "「あの、マスター……僭越ながら、ドリルはロマンの塊なのですが……」"

[[dialogue]]
speaker = "アニマ"
# 「まぁ聞ケ。ドリルナックルにパイルバンカー、それらを作り出せる手腕、実に見事ダ」
line = "「まぁ聞ケ。ドリルナックルにパイルバンカー、それらを作り出せる手腕、実に見事ダ」"

[[dialogue]]
speaker = "アニマ"
# 「個人的には苦手としているが、機械技術そのものの素晴らしさもわかル。アニマには無理な芸当だ、そこは誇ってイイ」
line = "「個人的には苦手としているが、機械技術そのものの素晴らしさもわかル。アニマには無理な芸当だ、そこは誇ってイイ」"

[[dialogue]]
speaker = "アニマ"
# 「しかし！　だからこそアニマにはわからなイ！　シュティレがどうして機械を得意をしないアニマの元で、錬金術を学びたがるのカ！」
line = "「しかし！　だからこそアニマにはわからなイ！　シュティレがどうして機械を得意をしないアニマの元で、錬金術を学びたがるのカ！」"

[[dialogue]]
speaker = "シュティレ"
# 「それは──」
line = "「それは──」"

[[dialogue]]
speaker = "アニマ"
# 「フヒッ。弟子入りとは、師匠の技術と経験を食らい尽くし、<ruby=おの>己</ruby>が糧とする行為に他ならなイ！」
line = "「フヒッ。弟子入りとは、師匠の技術と経験を食らい尽くし、<ruby>己<rt>おの</rt></ruby>が糧とする行為に他ならなイ！」"

[[dialogue]]
speaker = "アニマ"
# 「熱いモチベーション。狂気の炎。身を焦がすような好奇心──それらをひっくるめて『ロマン』とアニマは定義していル」
line = "「熱いモチベーション。狂気の炎。身を焦がすような好奇心──それらをひっくるめて『ロマン』とアニマは定義していル」"

[[dialogue]]
speaker = "アニマ"
# 「シュティレからは残念ながら、焦がれるようなロマンの熱を感じないんダ」
line = "「シュティレからは残念ながら、焦がれるようなロマンの熱を感じないんダ」"

[[dialogue]]
speaker = "アニマ"
# 「『ドリルがロマンだ』というのはちょっとズレていル。アニマが聞きたいのはキミの夢想する悲願の内容ダ。それを熱く語りたまえ」
line = "「『ドリルがロマンだ』というのはちょっとズレていル。アニマが聞きたいのはキミの夢想する悲願の内容ダ。それを熱く語りたまえ」"

[[dialogue]]
speaker = "シュティレ"
# 「…………それは、その」
line = "「…………それは、その」"

[[dialogue]]
speaker = "アニマ"
# 「これをパっと語れないのなら、アニマの弟子とはとても認められないナ」
line = "「これをパっと語れないのなら、アニマの弟子とはとても認められないナ」"

[[dialogue]]
speaker = "シュティレ"
# 「私は……マスターの元で錬金術を学びたいんです……その思いは、誰にも負けないつもりです……」
line = "「私は……マスターの元で錬金術を学びたいんです……その思いは、誰にも負けないつもりです……」"

[[dialogue]]
speaker = "アニマ"
# 「フヒヒ、質問の答えになってないゾ。残念ながら０点ダ！」
line = "「フヒヒ、質問の答えになってないゾ。残念ながら０点ダ！」"

[[dialogue]]
speaker = "アニマ"
# 「まぁ近づくなとは言わないサ。錬金術に興味があるのは純粋に嬉しいからネ。目で見て盗む分には、今後も構わないヨ」
line = "「まぁ近づくなとは言わないサ。錬金術に興味があるのは純粋に嬉しいからネ。目で見て盗む分には、今後も構わないヨ」"

[[dialogue]]
speaker = "シュティレ"
# 「…………はい」
line = "「…………はい」"

[[dialogue]]
speaker = "アニマ"
# 「──おっと、そろそろ隣のクラスの女子に飲ませた薬の効果が出る時間ダ！」
line = "「──おっと、そろそろ隣のクラスの女子に飲ませた薬の効果が出る時間ダ！」"

[[dialogue]]
speaker = "アニマ"
# 「ではな会長、アニマはこれで失礼するゾ！」
line = "「ではな会長、アニマはこれで失礼するゾ！」"

[[dialogue]]
speaker = "アナ"
# 「……行ってしまいましたね。すみません、余計なことを聞いたでしょうか」
line = "「……行ってしまいましたね。すみません、余計なことを聞いたでしょうか」"

[[dialogue]]
speaker = "シュティレ"
# 「いえ、アナお姉ちゃんの気遣い、とても嬉しかったです」
line = "「いえ、アナお姉ちゃんの気遣い、とても嬉しかったです」"

[[dialogue]]
speaker = "アナ"
# 「アニマ先輩は変わり者なところがあるので、何となく弟子入りを拒んでいる可能性もあったので、訊ねてみたのですが」
line = "「アニマ先輩は変わり者なところがあるので、何となく弟子入りを拒んでいる可能性もあったので、訊ねてみたのですが」"

[[dialogue]]
speaker = "シュティレ"
# 「……落ち度は私にあります。マスターの問いにしっかりと答えを返すことができませんでした」
line = "「……落ち度は私にあります。マスターの問いにしっかりと答えを返すことができませんでした」"

[[dialogue]]
speaker = "シュティレ"
# 「でも私は……錬金術でなければ、マスターの弟子でなければ、ならない……そうでなくちゃ絶対に、ダメなんです……」
line = "「でも私は……錬金術でなければ、マスターの弟子でなければ、ならない……そうでなくちゃ絶対に、ダメなんです……」"

[[dialogue]]
speaker = "unk"
# うつむくシュティレに聞こえないように、アナが近づいて耳打ちをしてきた。
line = "うつむくシュティレに聞こえないように、アナが近づいて耳打ちをしてきた。"

[[dialogue]]
speaker = "アナ"
# 「会長、確かにシュティレさんは、アニマ先輩の言う『ロマン』について、しっかりと回答することができませんでした」
line = "「会長、確かにシュティレさんは、アニマ先輩の言う『ロマン』について、しっかりと回答することができませんでした」"

[[dialogue]]
speaker = "アナ"
# 「けれど彼女の胸中には、何か譲れないものがあるように思います」
line = "「けれど彼女の胸中には、何か譲れないものがあるように思います」"

[[dialogue]]
speaker = "unk"
# アナは、先輩として力になってあげたい？
line = "アナは、先輩として力になってあげたい？"

[[dialogue]]
speaker = "アナ"
# 「……はい。私も、自分がされて嬉しかったことを、後輩にしてあげたいです」
line = "「……はい。私も、自分がされて嬉しかったことを、後輩にしてあげたいです」"

[[dialogue]]
speaker = "アナ"
# 「会長に前会長、サーシャ先輩にマトイ先輩。私はたくさん、先輩方にお世話をしてもらいましたから」
line = "「会長に前会長、サーシャ先輩にマトイ先輩。私はたくさん、先輩方にお世話をしてもらいましたから」"

[[dialogue]]
speaker = "unk"
# だったら、こういうのはどう？
line = "だったら、こういうのはどう？"

[[dialogue]]
speaker = "アナ"
# 「……気分転換に、シュティレさんを遊びに誘ってみる、ですか？」
line = "「……気分転換に、シュティレさんを遊びに誘ってみる、ですか？」"

[[dialogue]]
speaker = "アナ"
# 「なるほど。プライベートで遊ぶというのは、いいアイデアかもしれません。肩の力が抜ければ、もっと深い話が聞けるかもしれませんね」
line = "「なるほど。プライベートで遊ぶというのは、いいアイデアかもしれません。肩の力が抜ければ、もっと深い話が聞けるかもしれませんね」"

[[dialogue]]
speaker = "アナ"
# 「ありがとうございます。今度の週末にでも早速、シュティレさんを誘ってみることにします」
line = "「ありがとうございます。今度の週末にでも早速、シュティレさんを誘ってみることにします」"

[[dialogue]]
speaker = "unk"
# ノヴァフォームに覚醒するためにここのところずっと悩み、努力をしているアナ。
line = "ノヴァフォームに覚醒するためにここのところずっと悩み、努力をしているアナ。"

[[dialogue]]
speaker = "unk"
# そんな彼女だからこそ、頑張ってもなかなか報われないシュティレを放っておけないのかもしれない。
line = "そんな彼女だからこそ、頑張ってもなかなか報われないシュティレを放っておけないのかもしれない。"
