[[dialogue]]
speaker = "ヴィーナス"
# 「学園生から星徒会宛てに通報があったのって、こっちよね」
line = "「学園生から星徒会宛てに通報があったのって、こっちよね」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ、アリーナの方が騒がしい、とのことでした」
line = "「ええ、アリーナの方が騒がしい、とのことでした」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ホントに、メイプルのことと関係あるのかしら？」
line = "「ホントに、メイプルのことと関係あるのかしら？」"

[[dialogue]]
speaker = "フィオナ"
# 「可能性はありますが……」
line = "「可能性はありますが……」"

[[dialogue]]
speaker = "unk"
# なんだか、嫌な予感がするな……
line = "なんだか、嫌な予感がするな……"

[[dialogue]]
speaker = "ロロット"
# 「おや……？」
line = "「おや……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ……！　見て、あそこ！」
line = "「あっ……！　見て、あそこ！」"

[[dialogue]]
speaker = "ナナカ"
# 「なんでい、ありゃ……なんかの演説？」
line = "「なんでい、ありゃ……なんかの演説？」"

[[dialogue]]
speaker = "メイプル"
# 「はーっはっはっはー！」
line = "「はーっはっはっはー！」"

[[dialogue]]
speaker = "メイプル"
# 「我こそは、魔王マカロンさまだー！　者ども、遠慮なくあたしを頼りにするがいい～！」
line = "「我こそは、魔王マカロンさまだー！　者ども、遠慮なくあたしを頼りにするがいい～！」"

[[dialogue]]
speaker = "ナナカ"
# 「なんか、見慣れないヤバそうなやつがいる……！」
line = "「なんか、見慣れないヤバそうなやつがいる……！」"

[[dialogue]]
speaker = "ロロット"
# 「確かに騒がしいですね」
line = "「確かに騒がしいですね」"

[[dialogue]]
speaker = "パッキー"
# 「そしてそのお供、大賢者パッキー様だぜ！」
line = "「そしてそのお供、大賢者パッキー様だぜ！」"

[[dialogue]]
speaker = "ナナカ"
# 「見慣れたヤバそうなやつもいた！」
line = "「見慣れたヤバそうなやつもいた！」"

[[dialogue]]
speaker = "ロロット"
# 「おや、パンダさんじゃないですか」
line = "「おや、パンダさんじゃないですか」"

[[dialogue]]
speaker = "ナナカ"
# 「てか、なにやってんでいあいつ！」
line = "「てか、なにやってんでいあいつ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「えぇ……やっぱり、またなの……」
line = "「えぇ……やっぱり、またなの……」"

[[dialogue]]
speaker = "フィオナ"
# 「今回の認識改変のこと、気になっていましたが……なんとなく、これで大体のことは察し、という感じですね」
line = "「今回の認識改変のこと、気になっていましたが……なんとなく、これで大体のことは察し、という感じですね」"

[[dialogue]]
speaker = "ルリエル"
# 「あら……？」
line = "「あら……？」"

[[dialogue]]
speaker = "ルリエル"
# 「妹さん、パンダさん、なにやらお客様のようですよ」
line = "「妹さん、パンダさん、なにやらお客様のようですよ」"

[[dialogue]]
speaker = "パッキー"
# 「クックック……来たか！」
line = "「クックック……来たか！」"

[[dialogue]]
speaker = "ルリエル"
# 「ここは、この一の子分であるわたしにお任せです！」
line = "「ここは、この一の子分であるわたしにお任せです！」"

[[dialogue]]
speaker = "フィオナ"
# 「えっ、ルリエル……？」
line = "「えっ、ルリエル……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「えっと……多分、本物よね」
line = "「えっと……多分、本物よね」"

[[dialogue]]
speaker = "ナナカ"
# 「おっ、なんか、ロロちゃんに雰囲気似てる子だね」
line = "「おっ、なんか、ロロちゃんに雰囲気似てる子だね」"

[[dialogue]]
speaker = "ロロット"
# 「何を言っているんですか、わたしはあんなにふにゃふにゃしていませんよ」
line = "「何を言っているんですか、わたしはあんなにふにゃふにゃしていませんよ」"

[[dialogue]]
speaker = "フィオナ"
# 「ちょっとルリエル、姿が見えないと思ったら、こんなところで何をやっているの」
line = "「ちょっとルリエル、姿が見えないと思ったら、こんなところで何をやっているの」"

[[dialogue]]
speaker = "ルリエル"
# 「ルリエル……？　それはどちら様のことでしょう？」
line = "「ルリエル……？　それはどちら様のことでしょう？」"

[[dialogue]]
speaker = "フィオナ"
# 「えっ」
line = "「えっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「やっぱりまたこのパターン！　絶対あのセクハラパンダのせいでしょ、いい加減にしてよも～っ！」
line = "「やっぱりまたこのパターン！　絶対あのセクハラパンダのせいでしょ、いい加減にしてよも～っ！」"

[[dialogue]]
speaker = "ナナカ"
# 「あぁ、うん、なんかごめん……」
line = "「あぁ、うん、なんかごめん……」"

[[dialogue]]
speaker = "ルリエル"
# 「初めまして。わたしは、ロロットと申します。以後お見知りおきを」
line = "「初めまして。わたしは、ロロットと申します。以後お見知りおきを」"

[[dialogue]]
speaker = "ナナカ"
# 「え？　ああ、そっくりさんとか？」
line = "「え？　ああ、そっくりさんとか？」"

[[dialogue]]
speaker = "ロロット"
# 「そんなわけないじゃないですか～！」
line = "「そんなわけないじゃないですか～！」"

[[dialogue]]
speaker = "ルリエル"
# 「むむむ、あなたは一体……」
line = "「むむむ、あなたは一体……」"

[[dialogue]]
speaker = "ロロット"
# 「ふむ、きちんとしたご挨拶が必要なようですね」
line = "「ふむ、きちんとしたご挨拶が必要なようですね」"

[[dialogue]]
speaker = "ルリエル"
# 「同感です」
line = "「同感です」"

[[dialogue]]
speaker = "ロロット"
# 「わたしこそ――」
line = "「わたしこそ――」"

[[dialogue]]
speaker = "ルリエル"
# 「わたしは――」
line = "「わたしは――」"

[[dialogue]]
speaker = "2人"
# 「ロロット・ローゼンクロイツです！」
line = "「ロロット・ローゼンクロイツです！」"

[[dialogue]]
speaker = "ナナカ"
# 「そっくりじゃん」
line = "「そっくりじゃん」"

[[dialogue]]
speaker = "ロロット"
# 「ほほう、なりすましとは、随分悪質なのです」
line = "「ほほう、なりすましとは、随分悪質なのです」"

[[dialogue]]
speaker = "ルリエル"
# 「そちらこそ、キャラ被りなんて浅はかな真似はやめて下さ～い！」
line = "「そちらこそ、キャラ被りなんて浅はかな真似はやめて下さ～い！」"

[[dialogue]]
speaker = "ロロット"
# 「おや、被せてきているのはそちらでは？」
line = "「おや、被せてきているのはそちらでは？」"

[[dialogue]]
speaker = "ルリエル"
# 「なんですって～！　適当なことを言わないで下さい！」
line = "「なんですって～！　適当なことを言わないで下さい！」"

[[dialogue]]
speaker = "ロロット"
# 「わたしはいつでも、真剣そのものなのです」
line = "「わたしはいつでも、真剣そのものなのです」"

[[dialogue]]
speaker = "ルリエル"
# 「そんなにゆるくて、ふわっとしていて、真剣なわけがありませんっ」
line = "「そんなにゆるくて、ふわっとしていて、真剣なわけがありませんっ」"

[[dialogue]]
speaker = "ロロット"
# 「ゆるふわでかわいいですか？　それはどうも！」
line = "「ゆるふわでかわいいですか？　それはどうも！」"

[[dialogue]]
speaker = "ルリエル"
# 「褒めてません～！」
line = "「褒めてません～！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「えっ、結局、どっちがどっちなんだっけ……？」
line = "「えっ、結局、どっちがどっちなんだっけ……？」"

[[dialogue]]
speaker = "フィオナ"
# 「ああもう、何がなんだか……」
line = "「ああもう、何がなんだか……」"

[[dialogue]]
speaker = "メイプル"
# 「にひひっ……どうやら、役者は揃ったみたいだね！」
line = "「にひひっ……どうやら、役者は揃ったみたいだね！」"

[[dialogue]]
speaker = "unk"
# メイプル、気を確かに！
line = "メイプル、気を確かに！"

[[dialogue]]
speaker = "メイプル"
# 「はあ～？　お兄ちゃんに言われるまでもなく、あたしはバッチリ正気だよ！」
line = "「はあ～？　お兄ちゃんに言われるまでもなく、あたしはバッチリ正気だよ！」"

[[dialogue]]
speaker = "パッキー"
# 「クックック……魔王様、さっさとやっちまおうぜ！」
line = "「クックック……魔王様、さっさとやっちまおうぜ！」"

[[dialogue]]
speaker = "メイプル"
# 「わかってるってば。くらえーっ！」
line = "「わかってるってば。くらえーっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、クロトっ！」
line = "「あっ、クロトっ！」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長っ！」
line = "「緋宮会長っ！」"

[[dialogue]]
speaker = "ナナカ"
# 「な、なんでい、今の光は……あんた、なんかされた？」
line = "「な、なんでい、今の光は……あんた、なんかされた？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ちょっとクロト、大丈夫っ！？　なんだか、ふぬけた顔になっちゃってるわよ！？」
line = "「ちょっとクロト、大丈夫っ！？　なんだか、ふぬけた顔になっちゃってるわよ！？」"

[[dialogue]]
speaker = "unk"
# …………。
line = "…………。"

[[dialogue]]
speaker = "メイプル"
# 「にっひっひ～♪　大賢者印の催眠アプリの力、思い知ったか～っ！」
line = "「にっひっひ～♪　大賢者印の催眠アプリの力、思い知ったか～っ！」"

[[dialogue]]
speaker = "パッキー"
# 「効き目はバッチリのようだぜ！」
line = "「効き目はバッチリのようだぜ！」"

[[dialogue]]
speaker = "メイプル"
# 「さ、こっちにおいで～、お兄ちゃんっ」
line = "「さ、こっちにおいで～、お兄ちゃんっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ、待ちなさいっ！　そっちに行くんじゃないわよっ、止まりなさいってば！」
line = "「あっ、待ちなさいっ！　そっちに行くんじゃないわよっ、止まりなさいってば！」"

[[dialogue]]
speaker = "メイプル"
# 「無駄無駄～、ちょっとやそっとじゃ、この暗示は解けないよっ」
line = "「無駄無駄～、ちょっとやそっとじゃ、この暗示は解けないよっ」"

[[dialogue]]
speaker = "パッキー"
# 「さ～て、ずらかるぜ！」
line = "「さ～て、ずらかるぜ！」"

[[dialogue]]
speaker = "ナナカ"
# 「ちょっと、逃げられるよ！　追いかけないと！」
line = "「ちょっと、逃げられるよ！　追いかけないと！」"

[[dialogue]]
speaker = "ルリエル"
# 「むむむ～！　偽物さんなんかに、邪魔はさせませんよ～！」
line = "「むむむ～！　偽物さんなんかに、邪魔はさせませんよ～！」"

[[dialogue]]
speaker = "ロロット"
# 「んむむむ～！　そっちが邪魔です～！」
line = "「んむむむ～！　そっちが邪魔です～！」"

[[dialogue]]
speaker = "ナナカ"
# 「まだやってたんかい！」
line = "「まだやってたんかい！」"

[[dialogue]]
speaker = "ロロット"
# 「わたしがルリエルです！」
line = "「わたしがルリエルです！」"

[[dialogue]]
speaker = "ルリエル"
# 「わたしがロロットです！」
line = "「わたしがロロットです！」"

[[dialogue]]
speaker = "ナナカ"
# 「いや入れ替わるんかい！」
line = "「いや入れ替わるんかい！」"

[[dialogue]]
speaker = "ルリエル"
# 「はっ……！　わたしの名前を勝手に名乗らないで下さ～い！」
line = "「はっ……！　わたしの名前を勝手に名乗らないで下さ～い！」"

[[dialogue]]
speaker = "ロロット"
# 「どうぞどうぞ」
line = "「どうぞどうぞ」"

[[dialogue]]
speaker = "フィオナ"
# 「もうっ……ルリエルっ！」
line = "「もうっ……ルリエルっ！」"

[[dialogue]]
speaker = "ルリエル"
# 「はっ、はいっ！？　あら、フィオナ会長、どうされましたか……？」
line = "「はっ、はいっ！？　あら、フィオナ会長、どうされましたか……？」"

[[dialogue]]
speaker = "フィオナ"
# 「ほっ、よかった。元に戻ったみたいです……」
line = "「ほっ、よかった。元に戻ったみたいです……」"

[[dialogue]]
speaker = "ロロット"
# 「チョロすぎでは？」
line = "「チョロすぎでは？」"

[[dialogue]]
speaker = "ナナカ"
# 「あんたもね」
line = "「あんたもね」"

[[dialogue]]
speaker = "パッキー"
# 「チッ、ニセ天使の催眠が甘かったようだぜ。だが、時間稼ぎとしちゃ、上出来だぜ」
line = "「チッ、ニセ天使の催眠が甘かったようだぜ。だが、時間稼ぎとしちゃ、上出来だぜ」"

[[dialogue]]
speaker = "パッキー"
# 「魔王さえ手に入れちまえば、もうここに用はないんだからな！」
line = "「魔王さえ手に入れちまえば、もうここに用はないんだからな！」"

[[dialogue]]
speaker = "メイプル"
# 「にひひっ、マカロン様の計画は完璧なんだから！　それじゃあお姉ちゃんたち、バイバ～イ♪」
line = "「にひひっ、マカロン様の計画は完璧なんだから！　それじゃあお姉ちゃんたち、バイバ～イ♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あっ……！」
line = "「あっ……！」"

[[dialogue]]
speaker = "ナナカ"
# 「えっ、消えた……！？」
line = "「えっ、消えた……！？」"

[[dialogue]]
speaker = "フィオナ"
# 「あれは……空間の裂け目……！？」
line = "「あれは……空間の裂け目……！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それって、この前と同じようなやつってこと……？」
line = "「それって、この前と同じようなやつってこと……？」"

[[dialogue]]
speaker = "フィオナ"
# 「そうですね、おそらくこの先はまた例の異世界につながっているのではないかと」
line = "「そうですね、おそらくこの先はまた例の異世界につながっているのではないかと」"

[[dialogue]]
speaker = "フィオナ"
# 「以前のように、リクリエやフィーニスの塔の影響もあるのかと思っていましたが……もしかしたら今回は、何か別の力も働いているのかもしれません」
line = "「以前のように、リクリエやフィーニスの塔の影響もあるのかと思っていましたが……もしかしたら今回は、何か別の力も働いているのかもしれません」"

[[dialogue]]
speaker = "ナナカ"
# 「細かいことはともかく、追っかけて行くっきゃないっしょ！」
line = "「細かいことはともかく、追っかけて行くっきゃないっしょ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ナナカ……！」
line = "「ナナカ……！」"

[[dialogue]]
speaker = "ナナカ"
# 「あいつを助けるんでしょ？　アタシらも協力するよ。街を案内してもらったり、助けてもらった恩もあるしさ」
line = "「あいつを助けるんでしょ？　アタシらも協力するよ。街を案内してもらったり、助けてもらった恩もあるしさ」"

[[dialogue]]
speaker = "ナナカ"
# 「それに、あのひねくれパンダが関わってるってんなら、そもそも他人事じゃないしね！」
line = "「それに、あのひねくれパンダが関わってるってんなら、そもそも他人事じゃないしね！」"

[[dialogue]]
speaker = "ロロット"
# 「よい心がけです。隣人を愛想よくしろと言いますし」
line = "「よい心がけです。隣人を愛想よくしろと言いますし」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ありがとうっ。そうと決まれば、みんな行くわよ！」
line = "「ありがとうっ。そうと決まれば、みんな行くわよ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ！」
line = "「ええ！」"

[[dialogue]]
speaker = "ルリエル"
# 「あの～、ところで、わたしは今まで、一体何を……」
line = "「あの～、ところで、わたしは今まで、一体何を……」"

[[dialogue]]
speaker = "ロロット"
# 「さあさあ、もたもたしていないで、あなたも一緒に行きますよ～！　ビッグウェーブに飛び込むのです～！」
line = "「さあさあ、もたもたしていないで、あなたも一緒に行きますよ～！　ビッグウェーブに飛び込むのです～！」"

[[dialogue]]
speaker = "ルリエル"
# 「えっ、わわっ……ひゃあぁぁ～～！？」
line = "「えっ、わわっ……ひゃあぁぁ～～！？」"
