[[dialogue]]
speaker = "セドナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "リノ"
# 「こんなところで何してるのよ」
line = "「こんなところで何してるのよ」"

[[dialogue]]
speaker = "セドナ"
# 「……リノか」
line = "「……リノか」"

[[dialogue]]
speaker = "セドナ"
# 「どこにでも現れるやつだが、こんな所に何をしにきた」
line = "「どこにでも現れるやつだが、こんな所に何をしにきた」"

[[dialogue]]
speaker = "リノ"
# 「親友の顔を見に来ただけよ」
line = "「親友の顔を見に来ただけよ」"

[[dialogue]]
speaker = "セドナ"
# 「誰が親友だ、裏切者が」
line = "「誰が親友だ、裏切者が」"

[[dialogue]]
speaker = "リノ"
# 「酷いわね～。私たちのわだかまりは溶けたんじゃないの？」
line = "「酷いわね～。私たちのわだかまりは溶けたんじゃないの？」"

[[dialogue]]
speaker = "セドナ"
# 「何を甘いことを言っている」
line = "「何を甘いことを言っている」"

[[dialogue]]
speaker = "セドナ"
# 「ネビュラを裏切り組織を抜け、魔王の身体を連れ去り、グレートウォール計画を中止させた」
line = "「ネビュラを裏切り組織を抜け、魔王の身体を連れ去り、グレートウォール計画を中止させた」"

[[dialogue]]
speaker = "セドナ"
# 「それだけの事をやらかしておいて、リクリエの脅威が去ったから許される、などと思うな……お前は永久に指名手配犯だ」
line = "「それだけの事をやらかしておいて、リクリエの脅威が去ったから許される、などと思うな……お前は永久に指名手配犯だ」"

[[dialogue]]
speaker = "リノ"
# 「やだ～、私捕まって酷いことされちゃうのね♪」
line = "「やだ～、私捕まって酷いことされちゃうのね♪」"

[[dialogue]]
speaker = "セドナ"
# 「はぁ……」
line = "「はぁ……」"

[[dialogue]]
speaker = "リノ"
# 「……元気、無いわね」
line = "「……元気、無いわね」"

[[dialogue]]
speaker = "セドナ"
# 「お前のことだ。全部察しはついているんだろう？」
line = "「お前のことだ。全部察しはついているんだろう？」"

[[dialogue]]
speaker = "リノ"
# 「ん～……リーリアちゃんのこと？」
line = "「ん～……リーリアちゃんのこと？」"

[[dialogue]]
speaker = "セドナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "セドナ"
# 「彼女とどのように接すればいいのか……指針を決めかねている」
line = "「彼女とどのように接すればいいのか……指針を決めかねている」"

[[dialogue]]
speaker = "リノ"
# 「私でよければ話を聞くけど？」
line = "「私でよければ話を聞くけど？」"

[[dialogue]]
speaker = "セドナ"
# 「お前に話しても何の解決にもならん。お前はネビュラではないのだから」
line = "「お前に話しても何の解決にもならん。お前はネビュラではないのだから」"

[[dialogue]]
speaker = "リノ"
# 「誰も解決に協力するなんて言ってないわよ」
line = "「誰も解決に協力するなんて言ってないわよ」"

[[dialogue]]
speaker = "リノ"
# 「ただ聞いてあげるだけ。それだけでも少しは気持ちが楽になると思うんだけどな～」
line = "「ただ聞いてあげるだけ。それだけでも少しは気持ちが楽になると思うんだけどな～」"

[[dialogue]]
speaker = "セドナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "リノ"
# 「むしろ組織外の私だからこそ、部下には話せないことでも話せたりしないかしら？」
line = "「むしろ組織外の私だからこそ、部下には話せないことでも話せたりしないかしら？」"

[[dialogue]]
speaker = "セドナ"
# 「…………はぁ～～～～～～。いいか？　ここで話すことは他言無用だ」
line = "「…………はぁ～～～～～～。いいか？　ここで話すことは他言無用だ」"

[[dialogue]]
speaker = "リノ"
# 「もちろんよ♪」
line = "「もちろんよ♪」"

[[dialogue]]
speaker = "セドナ"
# 「……グレートウォール計画の一端で、私はリーリアに『学園に潜入し、その動向を探る』という任務を与えた」
line = "「……グレートウォール計画の一端で、私はリーリアに『学園に潜入し、その動向を探る』という任務を与えた」"

[[dialogue]]
speaker = "セドナ"
# 「だが……初めからそういう考えだったのか、あるいは任務の遂行中にそのような考えを持つようになったのか」
line = "「だが……初めからそういう考えだったのか、あるいは任務の遂行中にそのような考えを持つようになったのか」"

[[dialogue]]
speaker = "セドナ"
# 「リーリアは組織の方針に対して、不満の色を見せるようになってきた」
line = "「リーリアは組織の方針に対して、不満の色を見せるようになってきた」"

[[dialogue]]
speaker = "セドナ"
# 「スパイとして潜入しているうちに、思想が感化されてしまう……ありえない話ではない」
line = "「スパイとして潜入しているうちに、思想が感化されてしまう……ありえない話ではない」"

[[dialogue]]
speaker = "セドナ"
# 「ある時、彼女はこう言った――学園とネビュラが協力関係を結べば、小を切り捨てずとも、世界を救えるんじゃないか──と」
line = "「ある時、彼女はこう言った――学園とネビュラが協力関係を結べば、小を切り捨てずとも、世界を救えるんじゃないか──と」"

[[dialogue]]
speaker = "セドナ"
# 「私は叱責した。頭を冷やせ、とな」
line = "「私は叱責した。頭を冷やせ、とな」"

[[dialogue]]
speaker = "セドナ"
# 「リクリエの脅威は、本来その程度の小さな協力関係で防ぎ得るほど甘いものではない」
line = "「リクリエの脅威は、本来その程度の小さな協力関係で防ぎ得るほど甘いものではない」"

[[dialogue]]
speaker = "セドナ"
# 「３０００年の時をかけて綿密に練り上げられたグレートウォール計画の遂行こそが、世界の滅亡から逃れる最も高い可能性なのだ」
line = "「３０００年の時をかけて綿密に練り上げられたグレートウォール計画の遂行こそが、世界の滅亡から逃れる最も高い可能性なのだ」"

[[dialogue]]
speaker = "セドナ"
# 「リノ、お前や学園の連中は別の手段を選んだ」
line = "「リノ、お前や学園の連中は別の手段を選んだ」"

[[dialogue]]
speaker = "リノ"
# 「そうね……小さな希望だったけれど、みんなが生き残る可能性に賭けて」
line = "「そうね……小さな希望だったけれど、みんなが生き残る可能性に賭けて」"

[[dialogue]]
speaker = "セドナ"
# 「それは誤った考えだ。結果論としてすべてが救われた今もなお、この結論は私の中で揺らいでいない」
line = "「それは誤った考えだ。結果論としてすべてが救われた今もなお、この結論は私の中で揺らいでいない」"

[[dialogue]]
speaker = "セドナ"
# 「最終的に勝てたとはいえ、あの局面は何もかもが制御不能だった。……リクリエとの戦いが、博打であってはならないのだ」
line = "「最終的に勝てたとはいえ、あの局面は何もかもが制御不能だった。……リクリエとの戦いが、博打であってはならないのだ」"

[[dialogue]]
speaker = "リノ"
# 「結果論に終始しないあなたの姿勢は立派だけど、勝ったのだから結果オーライにはできないかしら？」
line = "「結果論に終始しないあなたの姿勢は立派だけど、勝ったのだから結果オーライにはできないかしら？」"

[[dialogue]]
speaker = "セドナ"
# 「……リノ。私が問題視しているのは過去ではない。これから来る未来の話だ」
line = "「……リノ。私が問題視しているのは過去ではない。これから来る未来の話だ」"

[[dialogue]]
speaker = "セドナ"
# 「未だアステラの発生は収まらず、正体不明のモンスターも現れている」
line = "「未だアステラの発生は収まらず、正体不明のモンスターも現れている」"

[[dialogue]]
speaker = "セドナ"
# 「世界の危機は去っていない……いずれまた非情に徹しなければならない場面も訪れるだろうと私は睨んでいる」
line = "「世界の危機は去っていない……いずれまた非情に徹しなければならない場面も訪れるだろうと私は睨んでいる」"

[[dialogue]]
speaker = "セドナ"
# 「そんな時、リーリアは非情になりきれるのか……」
line = "「そんな時、リーリアは非情になりきれるのか……」"

[[dialogue]]
speaker = "セドナ"
# 「今日、星徒会の面々と接している彼女を見て不安に思ったのだ」
line = "「今日、星徒会の面々と接している彼女を見て不安に思ったのだ」"

[[dialogue]]
speaker = "リノ"
# 「ふぅん……だったら今回も、同じように注意すればいいんじゃないの？」
line = "「ふぅん……だったら今回も、同じように注意すればいいんじゃないの？」"

[[dialogue]]
speaker = "セドナ"
# 「その通りだ……しかし……」
line = "「その通りだ……しかし……」"

[[dialogue]]
speaker = "セドナ"
# 「学園と協調し、連携を取る。その重要性は私も理解しているつもりだ」
line = "「学園と協調し、連携を取る。その重要性は私も理解しているつもりだ」"

[[dialogue]]
speaker = "セドナ"
# 「その道を切り開いてくれた彼女の功績がどれほど大きなものか、ということもな」
line = "「その道を切り開いてくれた彼女の功績がどれほど大きなものか、ということもな」"

[[dialogue]]
speaker = "セドナ"
# 「故に迷っている。私はどうすべきか……と」
line = "「故に迷っている。私はどうすべきか……と」"

[[dialogue]]
speaker = "リノ"
# 「色々考えてるのね～」
line = "「色々考えてるのね～」"

[[dialogue]]
speaker = "セドナ"
# 「当然だろう」
line = "「当然だろう」"

[[dialogue]]
speaker = "リノ"
# 「そうね、昔からあなたはそうだったわ」
line = "「そうね、昔からあなたはそうだったわ」"

[[dialogue]]
speaker = "リノ"
# 「だけどそういう所で不器用なのは相変わらずなのね……ま、知ってたけど」
line = "「だけどそういう所で不器用なのは相変わらずなのね……ま、知ってたけど」"

[[dialogue]]
speaker = "セドナ"
# 「誰のせいでこんなにも苦労していると思っているんだ」
line = "「誰のせいでこんなにも苦労していると思っているんだ」"

[[dialogue]]
speaker = "セドナ"
# 「お前が組織に居てくれれば……そうすればお前の指揮の元、ネビュラはよりまとまっていたのだ」
line = "「お前が組織に居てくれれば……そうすればお前の指揮の元、ネビュラはよりまとまっていたのだ」"

[[dialogue]]
speaker = "リノ"
# 「それは違うと思うわよ」
line = "「それは違うと思うわよ」"

[[dialogue]]
speaker = "リノ"
# 「あなたの努力は、誰もが認めていると思うわ」
line = "「あなたの努力は、誰もが認めていると思うわ」"

[[dialogue]]
speaker = "リノ"
# 「リーリアちゃんともっと話してみたら？　あなたに足りないのは、他人から理解される努力よ」
line = "「リーリアちゃんともっと話してみたら？　あなたに足りないのは、他人から理解される努力よ」"

[[dialogue]]
speaker = "セドナ"
# 「耳が痛いな……」
line = "「耳が痛いな……」"

[[dialogue]]
speaker = "セドナ"
# 「だがその通りかもしれない……。そうだな、思い切って話してみるとしよう」
line = "「だがその通りかもしれない……。そうだな、思い切って話してみるとしよう」"

[[dialogue]]
speaker = "リノ"
# 「それがいいわ。普段と違うこういう環境だからこそ、分かり合えちゃったりするかもしれないわ」
line = "「それがいいわ。普段と違うこういう環境だからこそ、分かり合えちゃったりするかもしれないわ」"

[[dialogue]]
speaker = "セドナ"
# 「ふっ……そこまで楽観的にはなれないがな」
line = "「ふっ……そこまで楽観的にはなれないがな」"

[[dialogue]]
speaker = "unk"
# セドナは自嘲するように笑いながら、胸元から取り出したＤＩＳＣで部下へのコールボタンをタップした。
line = "セドナは自嘲するように笑いながら、胸元から取り出したＤＩＳＣで部下へのコールボタンをタップした。"
