[[dialogue]]
speaker = "プトラ"
# 「うわああああっ！！！」
line = "「うわああああっ！！！」"

[[dialogue]]
speaker = "アポロ"
# 「な、なんだあれ……でかいぞ！」
line = "「な、なんだあれ……でかいぞ！」"

[[dialogue]]
speaker = "モンスター"
# 「グマァアアアアアアアアアアア！！！！！」
line = "「グマァアアアアアアアアアアア！！！！！」"

[[dialogue]]
speaker = "アポロ"
# 「声もでかいっ！！！」
line = "「声もでかいっ！！！」"

[[dialogue]]
speaker = "黒ベア子"
# 「あはははは、とっておきの巨大クマロボなんだっくま。これでもっともっと楽しめるよーっ！」
line = "「あはははは、とっておきの巨大クマロボなんだっくま。これでもっともっと楽しめるよーっ！」"

[[dialogue]]
speaker = "アポロ"
# 「戦いも大詰めってわけか！　いいぞ、やってやるさ！」
line = "「戦いも大詰めってわけか！　いいぞ、やってやるさ！」"

[[dialogue]]
speaker = "モンスター"
# 「グマァアアアアアアアアアアアアアアア！！！！！」
line = "「グマァアアアアアアアアアアアアアアア！！！！！」"

[[dialogue]]
speaker = "アポロ"
# 「だからうるさいって！　ブレイブヒート！」
line = "「だからうるさいって！　ブレイブヒート！」"

[[dialogue]]
speaker = "モンスター"
# 「ガッキーーーーーーーーーーン！！！！！」
line = "「ガッキーーーーーーーーーーン！！！！！」"

[[dialogue]]
speaker = "アポロ"
# 「なっ、攻撃をはじき返した！？」
line = "「なっ、攻撃をはじき返した！？」"

[[dialogue]]
speaker = "黒ベア子"
# 「巨大クマロボはわたしのジョーカー、最後の切り札なんだっくま。ちょっとやそっとの攻撃じゃ効かないくまよ！」
line = "「巨大クマロボはわたしのジョーカー、最後の切り札なんだっくま。ちょっとやそっとの攻撃じゃ効かないくまよ！」"

[[dialogue]]
speaker = "黒ベア子"
# 「よーし、このまま攻撃くまーっ♪」
line = "「よーし、このまま攻撃くまーっ♪」"

[[dialogue]]
speaker = "モンスター"
# 「グッマァアアアアアアアアアアアア！！！！！」
line = "「グッマァアアアアアアアアアアアア！！！！！」"

[[dialogue]]
speaker = "アポロ"
# 「くっ！！？」
line = "「くっ！！？」"

[[dialogue]]
speaker = "アルテ"
# 「プトラ、合わせてください！」
line = "「プトラ、合わせてください！」"

[[dialogue]]
speaker = "プトラ"
# 「うんっ！」
line = "「うんっ！」"

[[dialogue]]
speaker = "アルテ"
# 「だめですね。私たちの攻撃でもびくともしないようです」
line = "「だめですね。私たちの攻撃でもびくともしないようです」"

[[dialogue]]
speaker = "アルテ"
# （イマージュの協力があれば……いえ、私が本来の力をもっと引き出せていれば、何とかなりそうなのですが……）
line = "（イマージュの協力があれば……いえ、私が本来の力をもっと引き出せていれば、何とかなりそうなのですが……）"

[[dialogue]]
speaker = "モンスター"
# 「クマアアアアアアアアアアア！！！！！」
line = "「クマアアアアアアアアアアア！！！！！」"

[[dialogue]]
speaker = "アルテ"
# 「っ……！」
line = "「っ……！」"

[[dialogue]]
speaker = "プトラ"
# 「危ないっ！！」
line = "「危ないっ！！」"

[[dialogue]]
speaker = "プトラ"
# 「大丈夫、アルテ！？」
line = "「大丈夫、アルテ！？」"

[[dialogue]]
speaker = "アルテ"
# 「ええ、ありがとうございます。助かりました」
line = "「ええ、ありがとうございます。助かりました」"

[[dialogue]]
speaker = "プトラ"
# 「きっと突破口は見つかるよ！　ちょっとばかしピンチだけど、ぜんぜん絶望的なんかじゃない！」
line = "「きっと突破口は見つかるよ！　ちょっとばかしピンチだけど、ぜんぜん絶望的なんかじゃない！」"

[[dialogue]]
speaker = "プトラ"
# 「だから、大丈夫だよアルテ！」
line = "「だから、大丈夫だよアルテ！」"

[[dialogue]]
speaker = "アルテ"
# 「……ふっ」
line = "「……ふっ」"

[[dialogue]]
speaker = "アルテ"
# 「何を言ってるんですか、プトラ？　私は別に絶望したりなんてしていませんよ」
line = "「何を言ってるんですか、プトラ？　私は別に絶望したりなんてしていませんよ」"

[[dialogue]]
speaker = "アルテ"
# 「私もアテネスでは命をかけて死の芸術と戦ってきました。この程度の危機は何度もくぐり抜けています」
line = "「私もアテネスでは命をかけて死の芸術と戦ってきました。この程度の危機は何度もくぐり抜けています」"

[[dialogue]]
speaker = "アルテ"
# 「あのデカブツを倒すために、ちょっとだけ本気を出そうと思考を巡らせていただけですよ……ご心配なく」
line = "「あのデカブツを倒すために、ちょっとだけ本気を出そうと思考を巡らせていただけですよ……ご心配なく」"

[[dialogue]]
speaker = "プトラ"
# 「あはっ、よかった」
line = "「あはっ、よかった」"

[[dialogue]]
speaker = "アルテ"
# 「まあ見ててください……すぅ──」
line = "「まあ見ててください……すぅ──」"

[[dialogue]]
speaker = "モンスター"
# 「クマアアアアアアアアアアアアア！！！！！」
line = "「クマアアアアアアアアアアアアア！！！！！」"

[[dialogue]]
speaker = "アポロ"
# 「アルテ！　またそっちに攻撃が行くぞ！」
line = "「アルテ！　またそっちに攻撃が行くぞ！」"

[[dialogue]]
speaker = "アルテ"
# 「問題ありませんよ……攻撃が私に届くことはありません──」
line = "「問題ありませんよ……攻撃が私に届くことはありません──」"

[[dialogue]]
speaker = "アルテ"
# 「ホーリーパニッシュメント！！！！」
line = "「ホーリーパニッシュメント！！！！」"

[[dialogue]]
speaker = "モンスター"
# 「ク、クマァアアア……！？！？」
line = "「ク、クマァアアア……！？！？」"

[[dialogue]]
speaker = "黒ベア子"
# 「くまっ！？　巨大クマロボが吹っ飛ばされちゃったんだくま……！？」
line = "「くまっ！？　巨大クマロボが吹っ飛ばされちゃったんだくま……！？」"

[[dialogue]]
speaker = "プトラ"
# 「いっくよ～……ソルフレア・スプラッシュ！」
line = "「いっくよ～……ソルフレア・スプラッシュ！」"

[[dialogue]]
speaker = "モンスター"
# 「クマァアアア～～～～～～～っ！？！？！？」
line = "「クマァアアア～～～～～～～っ！？！？！？」"

[[dialogue]]
speaker = "黒ベア子"
# 「ああっ！！　巨大クマロボが……やられた！？　そんなのありえっないくまよーーっ！？」
line = "「ああっ！！　巨大クマロボが……やられた！？　そんなのありえっないくまよーーっ！？」"

[[dialogue]]
speaker = "プトラ"
# 「やったね、アルテ！」
line = "「やったね、アルテ！」"

[[dialogue]]
speaker = "アルテ"
# 「まあ、天才の私にかかればこんなものです」
line = "「まあ、天才の私にかかればこんなものです」"

[[dialogue]]
speaker = "アポロ"
# 「へへっ、いいとこ持っていかれたみたいだな」
line = "「へへっ、いいとこ持っていかれたみたいだな」"

[[dialogue]]
speaker = "ヴィーナス"
# 「さて、切り札も無くなったけど、どうするのかしら？」
line = "「さて、切り札も無くなったけど、どうするのかしら？」"

[[dialogue]]
speaker = "黒ベア子"
# 「むむむむ、こんな呆気ない終わり方はつまらないんだくまよ……」
line = "「むむむむ、こんな呆気ない終わり方はつまらないんだくまよ……」"

[[dialogue]]
speaker = "黒ベア子"
# 「黒ベア子はもっとも～～っと盛り上げたいんだくま～～～！！！！！」
line = "「黒ベア子はもっとも～～っと盛り上げたいんだくま～～～！！！！！」"

[[dialogue]]
speaker = "？？？"
# 『いいかげんにするくまーーーーーーっ！！！』
line = "『いいかげんにするくまーーーーーーっ！！！』"

[[dialogue]]
speaker = "フィオナ"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だ、誰よ！？」
line = "「だ、誰よ！？」"

[[dialogue]]
speaker = "unk"
# 黒ベア子と同じ声。
line = "黒ベア子と同じ声。"

[[dialogue]]
speaker = "unk"
# だけど目の前の彼女が叫んだものじゃない、別なところから響いてきた声。
line = "だけど目の前の彼女が叫んだものじゃない、別なところから響いてきた声。"

[[dialogue]]
speaker = "？？？"
# 「なにやってるですかぁあっーーーー成敗！！！！」
line = "「なにやってるですかぁあっーーーー成敗！！！！」"

[[dialogue]]
speaker = "黒ベア子"
# 「ほんげーーーーーーーっ！！！」
line = "「ほんげーーーーーーーっ！！！」"

[[dialogue]]
speaker = "？？？"
# 「何をやってるのかと思ったら、あちこちの世界に迷惑をかけて！」
line = "「何をやってるのかと思ったら、あちこちの世界に迷惑をかけて！」"

[[dialogue]]
speaker = "黒ベア子"
# 「ベア子<emoji=heart04>」
line = "「ベア子<emoji=heart04>」"

[[dialogue]]
speaker = "ベア子"
# 「ベア子<emoji=heart04>　じゃないよ！　反省するくま！！」
line = "「ベア子<emoji=heart04>　じゃないよ！　反省するくま！！」"

[[dialogue]]
speaker = "黒ベア子"
# 「だって、だって、みんな一緒に遊んだら楽しくなって盛り上がるっくまよ？」
line = "「だって、だって、みんな一緒に遊んだら楽しくなって盛り上がるっくまよ？」"

[[dialogue]]
speaker = "ベア子"
# 「周りを見てみるんだくま。クマロボたちが暴れたせいで大変なことになっちゃってるでしょ？」
line = "「周りを見てみるんだくま。クマロボたちが暴れたせいで大変なことになっちゃってるでしょ？」"

[[dialogue]]
speaker = "黒ベア子"
# 「ぁぁーー。怒ったベア子もかんわいいくま……」
line = "「ぁぁーー。怒ったベア子もかんわいいくま……」"

[[dialogue]]
speaker = "黒ベア子"
# 「ああーーっ！！　いたいんだくま～～～～！！！」
line = "「ああーーっ！！　いたいんだくま～～～～！！！」"

[[dialogue]]
speaker = "ベア子"
# 「みなさんご迷惑をおかけいたしました。この子はしっかりとわたしが連れて帰りますので……」
line = "「みなさんご迷惑をおかけいたしました。この子はしっかりとわたしが連れて帰りますので……」"

[[dialogue]]
speaker = "フィオナ"
# 「あ、あの……別世界に飛ばされた子たちは……」
line = "「あ、あの……別世界に飛ばされた子たちは……」"

[[dialogue]]
speaker = "ベア子"
# 「もっちろん、それもすぐに元に戻しますですくま。それでは失礼しっまーーっす！」
line = "「もっちろん、それもすぐに元に戻しますですくま。それでは失礼しっまーーっす！」"

[[dialogue]]
speaker = "黒ベア子"
# 「さらばなんだくま～～～！！」
line = "「さらばなんだくま～～～！！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……行っちゃったわね」
line = "「……行っちゃったわね」"

[[dialogue]]
speaker = "アポロ"
# 「うわっ！？　な、なんだ……」
line = "「うわっ！？　な、なんだ……」"

[[dialogue]]
speaker = "アポロ"
# 「戦闘服が、いつものフォームに……」
line = "「戦闘服が、いつものフォームに……」"

[[dialogue]]
speaker = "フィオナ"
# 「やっぱりこれも、ベア子さんの引き起こした異変だったみたいですね」
line = "「やっぱりこれも、ベア子さんの引き起こした異変だったみたいですね」"

[[dialogue]]
speaker = "unk"
# ということは……
line = "ということは……"

[[dialogue]]
speaker = "unk"
# 異変は解決された
line = "異変は解決された"

[[dialogue]]
speaker = "プトラ"
# 「あっ……あたしたちの、体が……」
line = "「あっ……あたしたちの、体が……」"

[[dialogue]]
speaker = "アルテ"
# 「……どうやら元の世界に戻る時が来たようですね」
line = "「……どうやら元の世界に戻る時が来たようですね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ちょ、待ちなさいよ！　ちゃんとお別れ会とかしたいのに……！」
line = "「ちょ、待ちなさいよ！　ちゃんとお別れ会とかしたいのに……！」"

[[dialogue]]
speaker = "アルテ"
# 「そんなことを言っても仕方ないでしょう」
line = "「そんなことを言っても仕方ないでしょう」"

[[dialogue]]
speaker = "アルテ"
# 「仕方がないので、元の世界に戻ってもあなたたちのことはちゃんと覚えていてあげますよ」
line = "「仕方がないので、元の世界に戻ってもあなたたちのことはちゃんと覚えていてあげますよ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「アルテ……」
line = "「アルテ……」"

[[dialogue]]
speaker = "プトラ"
# 「ううう、せっかく仲良くなれたのに寂しいよ……」
line = "「ううう、せっかく仲良くなれたのに寂しいよ……」"

[[dialogue]]
speaker = "プトラ"
# 「でも、うん、あたしもぜったいみんなのこと忘れないね！」
line = "「でも、うん、あたしもぜったいみんなのこと忘れないね！」"

[[dialogue]]
speaker = "フィオナ"
# 「約束ですよ」
line = "「約束ですよ」"

[[dialogue]]
speaker = "アルテ"
# 「短い間だったけど、お世話になりました」
line = "「短い間だったけど、お世話になりました」"

[[dialogue]]
speaker = "プトラ"
# 「楽しかったよ、元気でね～！」
line = "「楽しかったよ、元気でね～！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "アポロ"
# 「急にいなくなると、寂しいもんだな……」
line = "「急にいなくなると、寂しいもんだな……」"

[[dialogue]]
speaker = "フィオナ"
# 「仕方ないですよ。彼女たちには彼女たちの居るべき世界があるんですから」
line = "「仕方ないですよ。彼女たちには彼女たちの居るべき世界があるんですから」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうね……」
line = "「そうね……」"

[[dialogue]]
speaker = "アナ"
# 「きゃふ……！」
line = "「きゃふ……！」"

[[dialogue]]
speaker = "サーシャ"
# 「到着～」
line = "「到着～」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふふ、どうやら無事に戻って来れたみたいね～」
line = "「ふふふ、どうやら無事に戻って来れたみたいね～」"

[[dialogue]]
speaker = "ヴィーナス"
# 「アナ、サーシャさん！！」
line = "「アナ、サーシャさん！！」"

[[dialogue]]
speaker = "unk"
# 大丈夫？
line = "大丈夫？"

[[dialogue]]
speaker = "サーシャ"
# 「ええ、心配かけてごめんなさい」
line = "「ええ、心配かけてごめんなさい」"

[[dialogue]]
speaker = "アナ"
# 「少しばかり異世界を旅してきました」
line = "「少しばかり異世界を旅してきました」"

[[dialogue]]
speaker = "unk"
# 異世界はどうだった？
line = "異世界はどうだった？"

[[dialogue]]
speaker = "アナ"
# 「ええ、いろいろ大変でしたけど、とても楽しかったですよ」
line = "「ええ、いろいろ大変でしたけど、とても楽しかったですよ」"

[[dialogue]]
speaker = "サーシャ"
# 「あちらで起きたことや、出会った人のこと、いっぱいお話したいわ」
line = "「あちらで起きたことや、出会った人のこと、いっぱいお話したいわ」"

[[dialogue]]
speaker = "アポロ"
# 「よーし、それじゃお茶でもしながら、土産話をたっぷり聞かせてもらおうぜ！」
line = "「よーし、それじゃお茶でもしながら、土産話をたっぷり聞かせてもらおうぜ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうね、私たちも２人に話したいことがいっぱいいっぱいあるわ」
line = "「そうね、私たちも２人に話したいことがいっぱいいっぱいあるわ」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら、それは楽しみね～」
line = "「あらあら、それは楽しみね～」"

[[dialogue]]
speaker = "フィオナ"
# 「では、いきましょう」
line = "「では、いきましょう」"

[[dialogue]]
speaker = "unk"
# アルテやプトラと同じように、おそらく異世界で活躍してきただろう２人と一緒に学園へと帰還する。
line = "アルテやプトラと同じように、おそらく異世界で活躍してきただろう２人と一緒に学園へと帰還する。"

[[dialogue]]
speaker = "unk"
# そして、カフェテリアでテーブルを囲みながら、ここ数日間で起きたことについて語り合う。
line = "そして、カフェテリアでテーブルを囲みながら、ここ数日間で起きたことについて語り合う。"

[[dialogue]]
speaker = "unk"
# こうして黒ベア子によって引き起こされた事件は、穏やかに幕を閉じたのだった。
line = "こうして黒ベア子によって引き起こされた事件は、穏やかに幕を閉じたのだった。"
