[[dialogue]]
speaker = "ここあ"
# 「アンナちん、すご～い！　もう何か分かったの！？」
line = "「アンナちん、すご～い！　もう何か分かったの！？」"

[[dialogue]]
speaker = "いろは"
# 「もしかして、シズシズのこと抱っこしながら分析しちゃったってこと！？」
line = "「もしかして、シズシズのこと抱っこしながら分析しちゃったってこと！？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「そうですね。まだ詳しいことは分からないものの、どうやらこれは、感染させるタイプの能力のようです～」
line = "「そうですね。まだ詳しいことは分からないものの、どうやらこれは、感染させるタイプの能力のようです～」"

[[dialogue]]
speaker = "トレジアンナ"
# 「まあ十中八九、シズハさんがキスされたときに感染させられたのだと思います。そしてこれは、感染主の欲望を暴走させるような作用があるみたいですね～」
line = "「まあ十中八九、シズハさんがキスされたときに感染させられたのだと思います。そしてこれは、感染主の欲望を暴走させるような作用があるみたいですね～」"

[[dialogue]]
speaker = "花織"
# 「欲望の暴走……ですか？」
line = "「欲望の暴走……ですか？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「まあ、見たまんまなんですが、感染者は理性が大幅に低下してしまうようですね～」
line = "「まあ、見たまんまなんですが、感染者は理性が大幅に低下してしまうようですね～」"

[[dialogue]]
speaker = "トレジアンナ"
# 「ちょっと我慢が効かなくなるとかそういうレベルじゃなくて、欲望駄々洩れ、煩悩一直線のおバカさんになっちゃうみたいです☆」
line = "「ちょっと我慢が効かなくなるとかそういうレベルじゃなくて、欲望駄々洩れ、煩悩一直線のおバカさんになっちゃうみたいです☆」"

[[dialogue]]
speaker = "トレジアンナ"
# 「そして、感染者はその内に秘めた欲望を叶えるための歯止めが効かなくなり大暴走！　その欲望が叶うまでは、本人の意思ではまったく止まれないようです」
line = "「そして、感染者はその内に秘めた欲望を叶えるための歯止めが効かなくなり大暴走！　その欲望が叶うまでは、本人の意思ではまったく止まれないようです」"

[[dialogue]]
speaker = "ここあ"
# 「シズハっちが気を失ったのは、欲望が叶えられたから？」
line = "「シズハっちが気を失ったのは、欲望が叶えられたから？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「そういうことになりそうですね～」
line = "「そういうことになりそうですね～」"

[[dialogue]]
speaker = "サチ"
# 「えっと、本当にそれだけですか……？」
line = "「えっと、本当にそれだけですか……？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「あと何か、気持ちよくなっちゃうみたいです☆」
line = "「あと何か、気持ちよくなっちゃうみたいです☆」"

[[dialogue]]
speaker = "サチ"
# 「でしょうね！！？」
line = "「でしょうね！！？」"

[[dialogue]]
speaker = "プリムラ"
# 「なんじゃ、思ったよりも大したことは無さそうじゃの」
line = "「なんじゃ、思ったよりも大したことは無さそうじゃの」"

[[dialogue]]
speaker = "サチ"
# 「緊張感がないよ、プリムラ！　とんでもなく恐ろしい攻撃じゃない、これは！！」
line = "「緊張感がないよ、プリムラ！　とんでもなく恐ろしい攻撃じゃない、これは！！」"

[[dialogue]]
speaker = "プリムラ"
# 「そうかの？」
line = "「そうかの？」"

[[dialogue]]
speaker = "サチ"
# 「そうだよ！？　これは社会的、精神的にヒトの尊厳を破壊する、深刻な病でしょっ！？」
line = "「そうだよ！？　これは社会的、精神的にヒトの尊厳を破壊する、深刻な病でしょっ！？」"

[[dialogue]]
speaker = "サチ"
# 「いくら後で正気に戻ったとしても、失われたシズハちゃんの尊厳は、二度と回復しないんだよ！！！」
line = "「いくら後で正気に戻ったとしても、失われたシズハちゃんの尊厳は、二度と回復しないんだよ！！！」"

[[dialogue]]
speaker = "プリムラ"
# 「……シズハにあの程度の痴態で失われるほどの尊厳など、最初からあったかの？」
line = "「……シズハにあの程度の痴態で失われるほどの尊厳など、最初からあったかの？」"

[[dialogue]]
speaker = "花織"
# 「プリムラちゃん、結構めちゃくちゃ言うね……」
line = "「プリムラちゃん、結構めちゃくちゃ言うね……」"

[[dialogue]]
speaker = "いろは"
# 「あたしはあんまり気にしないかな～？　むしろどんな風になるのか、ちょっと気になるかも！」
line = "「あたしはあんまり気にしないかな～？　むしろどんな風になるのか、ちょっと気になるかも！」"

[[dialogue]]
speaker = "ここあ"
# 「にゃははは。いろはすは最初から本能のままに生きてるって感じするもんね～」
line = "「にゃははは。いろはすは最初から本能のままに生きてるって感じするもんね～」"

[[dialogue]]
speaker = "サチ"
# 「もう！　みなさん、のん気すぎです！　こんな病が流星市国に蔓延するなんて、絶対に許されないことなんですからね！！」
line = "「もう！　みなさん、のん気すぎです！　こんな病が流星市国に蔓延するなんて、絶対に許されないことなんですからね！！」"

[[dialogue]]
speaker = "プリムラ"
# 「……大方、サチは自分の『むっつり』がバレるのを気にしてるんじゃろうが、もうとっくにバレとるから今更隠す必要も特にないのじゃ」
line = "「……大方、サチは自分の『むっつり』がバレるのを気にしてるんじゃろうが、もうとっくにバレとるから今更隠す必要も特にないのじゃ」"

[[dialogue]]
speaker = "サチ"
# 「なぁっっっ！！？！？？」
line = "「なぁっっっ！！？！？？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「まあまあ、プリムラさん。好きな人にちょっとエッチなところがバレるのは逆にアピールにもなりますが……」
line = "「まあまあ、プリムラさん。好きな人にちょっとエッチなところがバレるのは逆にアピールにもなりますが……」"

[[dialogue]]
speaker = "トレジアンナ"
# 「衆人環視の元で自分のエッチさを大公開してしまうのは、さすがに尊厳ある霊長類としては、避けたいところなんじゃないでしょうか☆」
line = "「衆人環視の元で自分のエッチさを大公開してしまうのは、さすがに尊厳ある霊長類としては、避けたいところなんじゃないでしょうか☆」"

[[dialogue]]
speaker = "プリムラ"
# 「そういうものかの？　頭の中が年中ピンク色なのも、色々考えものじゃな」
line = "「そういうものかの？　頭の中が年中ピンク色なのも、色々考えものじゃな」"

[[dialogue]]
speaker = "サチ"
# 「私、そこまでエッチじゃないもんっ！！！」
line = "「私、そこまでエッチじゃないもんっ！！！」"

[[dialogue]]
speaker = "プリムラ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "トレジアンナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "サチ"
# 「なんで突然黙るの、２人共！！？」
line = "「なんで突然黙るの、２人共！！？」"

[[dialogue]]
speaker = "ここあ"
# 「まあまあ、サチサチも落ち着いて～。さっきのあれに、絶対感染するって決まったわけでもないからさ」
line = "「まあまあ、サチサチも落ち着いて～。さっきのあれに、絶対感染するって決まったわけでもないからさ」"

[[dialogue]]
speaker = "いろは"
# 「え～っと、要するにキスさえされなければ大丈夫ってことだよね？」
line = "「え～っと、要するにキスさえされなければ大丈夫ってことだよね？」"

[[dialogue]]
speaker = "花織"
# 「そう考えたら、そこまで恐れる攻撃でもないかも……」
line = "「そう考えたら、そこまで恐れる攻撃でもないかも……」"

[[dialogue]]
speaker = "サチ"
# 「みなさん楽観的過ぎますっ！　本当に恐ろしい攻撃なんですよ！？　こんなの絶対、死よりも恐ろしいことなんですからぁっ！！」
line = "「みなさん楽観的過ぎますっ！　本当に恐ろしい攻撃なんですよ！？　こんなの絶対、死よりも恐ろしいことなんですからぁっ！！」"

[[dialogue]]
speaker = "プリムラ"
# 「どう考えても貴様は深刻にとらえすぎじゃろ……」
line = "「どう考えても貴様は深刻にとらえすぎじゃろ……」"

[[dialogue]]
speaker = "シズハ"
# 「う、う～ん……」
line = "「う、う～ん……」"

[[dialogue]]
speaker = "ここあ"
# 「あ、目が覚めたみたい！　おっはよ～♪　体調の方は大丈夫かにゃ？」
line = "「あ、目が覚めたみたい！　おっはよ～♪　体調の方は大丈夫かにゃ？」"

[[dialogue]]
speaker = "シズハ"
# 「え？　あ、えっと……おはよう、ございます？　……あれ、もしかして私、気を失っちゃってましたか……？」
line = "「え？　あ、えっと……おはよう、ございます？　……あれ、もしかして私、気を失っちゃってましたか……？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「はい。陽彩さんとキスしたことによって、シズハさんは『ピンク脳症候群』にかかっていたようですね～」
line = "「はい。陽彩さんとキスしたことによって、シズハさんは『ピンク脳症候群』にかかっていたようですね～」"

[[dialogue]]
speaker = "シズハ"
# 「『ピンク脳症候群』……？」
line = "「『ピンク脳症候群』……？」"

[[dialogue]]
speaker = "サチ"
# 「これって、そういう名前の病気なんですか？」
line = "「これって、そういう名前の病気なんですか？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「たった今、私が名付けました！　自信作です♪」
line = "「たった今、私が名付けました！　自信作です♪」"

[[dialogue]]
speaker = "いろは"
# 「あはは、確かにそれっぽいかも♪」
line = "「あはは、確かにそれっぽいかも♪」"

[[dialogue]]
speaker = "シズハ"
# 「えっと……それにかかっている間の記憶は、恥ずかしいけど残ってます……みなさん、本当にご迷惑をおかけしました」
line = "「えっと……それにかかっている間の記憶は、恥ずかしいけど残ってます……みなさん、本当にご迷惑をおかけしました」"

[[dialogue]]
speaker = "シズハ"
# 「改めて自己紹介をさせてください、私は<ruby=そめい>染井</ruby>シズハって言います。流星学園附属校３年の星騎士で――」
line = "「改めて自己紹介をさせてください、私は<ruby>染井<rt>そめい</rt></ruby>シズハって言います。流星学園附属校３年の星騎士で――」"

[[dialogue]]
speaker = "いろは"
# 「ねぇねぇ、もしかして……キミも魔法少女って感じ！？」
line = "「ねぇねぇ、もしかして……キミも魔法少女って感じ！？」"

[[dialogue]]
speaker = "シズハ"
# 「あれ？　サチちゃんたちと一緒にいて、『<ruby=それ>魔法少女</ruby>』を知ってるってことは……」
line = "「あれ？　サチちゃんたちと一緒にいて、『<ruby>魔法少女<rt>それ</rt></ruby>』を知ってるってことは……」"

[[dialogue]]
speaker = "いろは"
# 「そーなの！　別の世界から来たんだけど、実はあたしたちも魔法少女なんだっ♪」
line = "「そーなの！　別の世界から来たんだけど、実はあたしたちも魔法少女なんだっ♪」"

[[dialogue]]
speaker = "シズハ"
# 「えぇええぇっ！？　どういうこと！？」
line = "「えぇええぇっ！？　どういうこと！？」"

[[dialogue]]
speaker = "シズハ"
# 「おおよその事情はわかりました……。あの女の子のことも。あの子は元々、あなたたちのお友達なんですね」
line = "「おおよその事情はわかりました……。あの女の子のことも。あの子は元々、あなたたちのお友達なんですね」"

[[dialogue]]
speaker = "オムニス"
# 「そういうことなんだ」
line = "「そういうことなんだ」"

[[dialogue]]
speaker = "シズハ"
# 「なら、何としても元の状態に戻さないと！　一緒に頑張ろう♪　いけいけゴーゴー♪」
line = "「なら、何としても元の状態に戻さないと！　一緒に頑張ろう♪　いけいけゴーゴー♪」"

[[dialogue]]
speaker = "花織"
# 「う、うん……よろしくお願いします」
line = "「う、うん……よろしくお願いします」"

[[dialogue]]
speaker = "シズハ"
# 「じ～っ……」
line = "「じ～っ……」"

[[dialogue]]
speaker = "花織"
# 「え……？　あの～、どうかしましたか？」
line = "「え……？　あの～、どうかしましたか？」"

[[dialogue]]
speaker = "シズハ"
# 「えいっ♪」
line = "「えいっ♪」"

[[dialogue]]
speaker = "花織"
# 「きゃっ！？　ななな、なにをするんですか！」
line = "「きゃっ！？　ななな、なにをするんですか！」"

[[dialogue]]
speaker = "シズハ"
# 「挨拶代わりの、お尻ひと揉みです♪」
line = "「挨拶代わりの、お尻ひと揉みです♪」"

[[dialogue]]
speaker = "花織"
# 「どういうことぉ！？」
line = "「どういうことぉ！？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「説明しましょう！　シズハさんは決して、セクハラがしたいがためにお尻を揉んだわけじゃないんです！」
line = "「説明しましょう！　シズハさんは決して、セクハラがしたいがためにお尻を揉んだわけじゃないんです！」"

[[dialogue]]
speaker = "シズハ"
# 「そうなの！　お尻タッチはコミュニケーションなんだから！」
line = "「そうなの！　お尻タッチはコミュニケーションなんだから！」"

[[dialogue]]
speaker = "プリムラ"
# 「貴様は前々からそういっておるが、本当なのか……？　新しい尻を揉みたい、という邪な気持ちがなかったと誓えるのか？」
line = "「貴様は前々からそういっておるが、本当なのか……？　新しい尻を揉みたい、という邪な気持ちがなかったと誓えるのか？」"

[[dialogue]]
speaker = "シズハ"
# 「新しいお尻を揉むのも、よく知ってるお尻を揉むのも、穢れなき心で言ってるよ！　プリムラちゃん！」
line = "「新しいお尻を揉むのも、よく知ってるお尻を揉むのも、穢れなき心で言ってるよ！　プリムラちゃん！」"

[[dialogue]]
speaker = "プリムラ"
# 「えぇえい、勝手に我の尻を揉むでない！　このハレンチ娘がっ！？」
line = "「えぇえい、勝手に我の尻を揉むでない！　このハレンチ娘がっ！？」"

[[dialogue]]
speaker = "いろは"
# 「あたしはそれ、ちょっとわかるな～。ってことで、あたしも挨拶代わりに、えいっ♪」
line = "「あたしはそれ、ちょっとわかるな～。ってことで、あたしも挨拶代わりに、えいっ♪」"

[[dialogue]]
speaker = "シズハ"
# 「ふわぁあっ<emoji=heart04>　これはこれはご丁寧に、どうもありがとうございます♪　ではこちらからも、もみもみ♪」
line = "「ふわぁあっ<emoji=heart04>　これはこれはご丁寧に、どうもありがとうございます♪　ではこちらからも、もみもみ♪」"

[[dialogue]]
speaker = "プリムラ"
# 「何なのじゃ、このハレンチ空間は……」
line = "「何なのじゃ、このハレンチ空間は……」"

[[dialogue]]
speaker = "花織"
# 「苦労してるんだね、キミも……」
line = "「苦労してるんだね、キミも……」"

[[dialogue]]
speaker = "プリムラ"
# 「常識が通用する奴がいて助かるのじゃ……しかし、我は悪の終末兵器だったはずが、なぜこんなことに……」
line = "「常識が通用する奴がいて助かるのじゃ……しかし、我は悪の終末兵器だったはずが、なぜこんなことに……」"

[[dialogue]]
speaker = "サチ"
# 「って、お尻を揉み合ってる場合じゃないですよ！？　抜本的な対策を１秒でも早く考えて、あの子を止めに行かなくちゃ、とんでもないことになりますっ！！」
line = "「って、お尻を揉み合ってる場合じゃないですよ！？　抜本的な対策を１秒でも早く考えて、あの子を止めに行かなくちゃ、とんでもないことになりますっ！！」"

[[dialogue]]
speaker = "ここあ"
# 「まあ、サチサチの言う通り、あきあきのことも放っておくわけにはいかないよね～」
line = "「まあ、サチサチの言う通り、あきあきのことも放っておくわけにはいかないよね～」"

[[dialogue]]
speaker = "トレジアンナ"
# 「１人だけ、ちょっと必死すぎる感じはしますけどね☆」
line = "「１人だけ、ちょっと必死すぎる感じはしますけどね☆」"

[[dialogue]]
speaker = "ここあ"
# 「あきあきを取り返さなきゃいけない以上、ここあたちもいつまでも遊んでるわけにはいかないけどね～」
line = "「あきあきを取り返さなきゃいけない以上、ここあたちもいつまでも遊んでるわけにはいかないけどね～」"

[[dialogue]]
speaker = "ここあ"
# 「でも、アンナちんの口ぶりからすると、何とかする算段はもうついちゃった感じ？」
line = "「でも、アンナちんの口ぶりからすると、何とかする算段はもうついちゃった感じ？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「ふっふっふっ。もちろん、任せてください♪」
line = "「ふっふっふっ。もちろん、任せてください♪」"

[[dialogue]]
speaker = "トレジアンナ"
# 「この先代魔法少女にして、サチさんのお助け妖精ポジションの私が、すべて丸っとハッピーエンドな劇場版にしてみせますよ！」
line = "「この先代魔法少女にして、サチさんのお助け妖精ポジションの私が、すべて丸っとハッピーエンドな劇場版にしてみせますよ！」"

[[dialogue]]
speaker = "トレジアンナ"
# 「その方法はこれから考えますが☆」
line = "「その方法はこれから考えますが☆」"

[[dialogue]]
speaker = "ここあ"
# 「にゃははは。そんなこと言いつつ、確証がないだけで仮説はもうすっかり立ててそうな気がするな～」
line = "「にゃははは。そんなこと言いつつ、確証がないだけで仮説はもうすっかり立ててそうな気がするな～」"

[[dialogue]]
speaker = "ここあ"
# 「なんにせよ、ここあたちは体を使って戦うことしかできないから、作戦立案はアンナちんにお任せするよ」
line = "「なんにせよ、ここあたちは体を使って戦うことしかできないから、作戦立案はアンナちんにお任せするよ」"

[[dialogue]]
speaker = "ここあ"
# 「アンナちんからは果てしない『姉パワー』を感じるから、きっと面倒見がいいって信じられるんだ♪」
line = "「アンナちんからは果てしない『姉パワー』を感じるから、きっと面倒見がいいって信じられるんだ♪」"

[[dialogue]]
speaker = "トレジアンナ"
# 「ほうほう、『姉パワー』ですかぁ！　それは初めて言われましたが……悪い気はしませんね☆」
line = "「ほうほう、『姉パワー』ですかぁ！　それは初めて言われましたが……悪い気はしませんね☆」"

[[dialogue]]
speaker = "ここあ"
# 「おっと、そんな話をしてたら、さっそくあきあきがお出ましみたい」
line = "「おっと、そんな話をしてたら、さっそくあきあきがお出ましみたい」"

[[dialogue]]
speaker = "トレジアンナ"
# 「了解です。それじゃあ張り切って、魔法少女オールスターズ、出撃しちゃいましょ～！」
line = "「了解です。それじゃあ張り切って、魔法少女オールスターズ、出撃しちゃいましょ～！」"
