[[dialogue]]
speaker = "エルデリーゼ"
# 「はぁ、はぁ、強い、ですわ……」
line = "「はぁ、はぁ、強い、ですわ……」"

[[dialogue]]
speaker = "ラティエ"
# 「完全に息が上がってしまっているようだが、まだ続けるつもりかな？」
line = "「完全に息が上がってしまっているようだが、まだ続けるつもりかな？」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「も、もちろんですのっ！！」
line = "「も、もちろんですのっ！！」"

[[dialogue]]
speaker = "ラティエ"
# 「ふむ……だが熱が入りすぎて、周りのお客様の迷惑になってはならない」
line = "「ふむ……だが熱が入りすぎて、周りのお客様の迷惑になってはならない」"

[[dialogue]]
speaker = "ラティエ"
# 「ここはひとつ間を置くというのも悪くないと思うが」
line = "「ここはひとつ間を置くというのも悪くないと思うが」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「そ、そうですわね……」
line = "「そ、そうですわね……」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「学園長様への挑戦はいつでも受け付けてくださいますの？」
line = "「学園長様への挑戦はいつでも受け付けてくださいますの？」"

[[dialogue]]
speaker = "ラティエ"
# 「ああ、私が再び旅に出てしまう前であれば構わないよ」
line = "「ああ、私が再び旅に出てしまう前であれば構わないよ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「分かりましたわ。それまでに必ず学園長様に認めさせてみせますの」
line = "「分かりましたわ。それまでに必ず学園長様に認めさせてみせますの」"

[[dialogue]]
speaker = "unk"
# どうなる事やらと一瞬ハラハラしたが、エルゼが引き下がったことで一応の決着がついた。
line = "どうなる事やらと一瞬ハラハラしたが、エルゼが引き下がったことで一応の決着がついた。"

[[dialogue]]
speaker = "サラン"
# 「それにしても学園長さんはお強いですね～」
line = "「それにしても学園長さんはお強いですね～」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「それは思いますの……失礼ながら学園長様は、年齢的に星騎士としての全盛期を過ぎているはずですの」
line = "「それは思いますの……失礼ながら学園長様は、年齢的に星騎士としての全盛期を過ぎているはずですの」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「なのにどうしてそんなにもお強いのでしょうか？」
line = "「なのにどうしてそんなにもお強いのでしょうか？」"

[[dialogue]]
speaker = "ラティエ"
# 「さて、どうしてだろうな……」
line = "「さて、どうしてだろうな……」"

[[dialogue]]
speaker = "ラティエ"
# 「よく分からないのだが私は、星力が最も充実している時期を過ぎた今でも、増大し続けているらしい」
line = "「よく分からないのだが私は、星力が最も充実している時期を過ぎた今でも、増大し続けているらしい」"

[[dialogue]]
speaker = "ラティエ"
# 「私としては修行の成果だとしか言いようがないのだがね、エスメラルダ女史あたりは徹底的に調査したがっている」
line = "「私としては修行の成果だとしか言いようがないのだがね、エスメラルダ女史あたりは徹底的に調査したがっている」"

[[dialogue]]
speaker = "unk"
# 協力はしてあげないんですか？
line = "協力はしてあげないんですか？"

[[dialogue]]
speaker = "ラティエ"
# 「協力はしているさ。旅先で得た有益な情報は全て伝えているし、時間のある時はデータ分析に協力している」
line = "「協力はしているさ。旅先で得た有益な情報は全て伝えているし、時間のある時はデータ分析に協力している」"

[[dialogue]]
speaker = "ラティエ"
# 「だが、エスメラルダ女史の分析は苦行以外の何物でもないからな」
line = "「だが、エスメラルダ女史の分析は苦行以外の何物でもないからな」"

[[dialogue]]
speaker = "ラティエ"
# 「トレーニングルームに監禁されて、モンスターとの模擬戦を１０時間も２０時間も強いられるんだ」
line = "「トレーニングルームに監禁されて、モンスターとの模擬戦を１０時間も２０時間も強いられるんだ」"

[[dialogue]]
speaker = "ラティエ"
# 「そんなの私でなくても逃げ出したくなるものだろう？」
line = "「そんなの私でなくても逃げ出したくなるものだろう？」"

[[dialogue]]
speaker = "サラン"
# 「それは大変です～」
line = "「それは大変です～」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「大変、というより酷いですわ……」
line = "「大変、というより酷いですわ……」"

[[dialogue]]
speaker = "unk"
# （そんなことしたんですか？）
line = "（そんなことしたんですか？）"

[[dialogue]]
speaker = "unk"
# （エスメラルダ先生……）
line = "（エスメラルダ先生……）"

[[dialogue]]
speaker = "エスメラルダ"
# 『し、仕方がないのよ！　そうでもしないと学園長の異常な体質は分析できないのだから！』
line = "『し、仕方がないのよ！　そうでもしないと学園長の異常な体質は分析できないのだから！』"

[[dialogue]]
speaker = "エスメラルダ"
# 『あれはさすがにやり過ぎたと思ってるし、以後はもっと短い拘束時間で済むように努めてますし……』
line = "『あれはさすがにやり過ぎたと思ってるし、以後はもっと短い拘束時間で済むように努めてますし……』"

[[dialogue]]
speaker = "unk"
# （どのくらい拘束しているんですか？）
line = "（どのくらい拘束しているんですか？）"

[[dialogue]]
speaker = "エスメラルダ"
# 『５時間から６時間くらい……』
line = "『５時間から６時間くらい……』"

[[dialogue]]
speaker = "unk"
# 短くはなってるけど、それでも嫌気がさすには十分な時間だった。
line = "短くはなってるけど、それでも嫌気がさすには十分な時間だった。"

[[dialogue]]
speaker = "ラティエ"
# 「まあ研究の事となると視野が狭くなるだけで、彼女は真面目で優秀な教師だからな。悪気がないことは分かっている」
line = "「まあ研究の事となると視野が狭くなるだけで、彼女は真面目で優秀な教師だからな。悪気がないことは分かっている」"

[[dialogue]]
speaker = "ラティエ"
# 「この人工戦闘服についても、エスメラルダ女史が知ったらデータを取りたがるだろうな」
line = "「この人工戦闘服についても、エスメラルダ女史が知ったらデータを取りたがるだろうな」"

[[dialogue]]
speaker = "エスメラルダ"
# 『ぎくっ！』
line = "『ぎくっ！』"

[[dialogue]]
speaker = "ラティエ"
# 「案外その辺りに身を潜めていて、データを収集しているかもしれない」
line = "「案外その辺りに身を潜めていて、データを収集しているかもしれない」"

[[dialogue]]
speaker = "エスメラルダ"
# 『ぎくぎくっ！！？』
line = "『ぎくぎくっ！！？』"

[[dialogue]]
speaker = "unk"
# 学園長の言葉に、俺とエスメラルダ先生が冷や汗を流した。その次の瞬間だった。
line = "学園長の言葉に、俺とエスメラルダ先生が冷や汗を流した。その次の瞬間だった。"

[[dialogue]]
speaker = "unk"
# モンスターの出現を知らせるアラートがＤＩＳＣから鳴り響く。
line = "モンスターの出現を知らせるアラートがＤＩＳＣから鳴り響く。"

[[dialogue]]
speaker = "unk"
# 同時にアステラが出現し、その中から大量のモンスターがワラワラと現れた。
line = "同時にアステラが出現し、その中から大量のモンスターがワラワラと現れた。"

[[dialogue]]
speaker = "サラン"
# 「大変～、モンスターさんたちがいっぱい現れちゃった～！」
line = "「大変～、モンスターさんたちがいっぱい現れちゃった～！」"

[[dialogue]]
speaker = "ラティエ"
# 「彼らも夏仕様だね。楽し気な空気に誘われてきたのかな？」
line = "「彼らも夏仕様だね。楽し気な空気に誘われてきたのかな？」"

[[dialogue]]
speaker = "エスメラルダ"
# 『呑気なことを言ってる場合じゃありません！　はやく一般の方々を避難させないと！』
line = "『呑気なことを言ってる場合じゃありません！　はやく一般の方々を避難させないと！』"

[[dialogue]]
speaker = "ラティエ"
# 「その通りだ。非常事態だからな、きみも手伝ってくれたまえ、エスメラルダ女史」
line = "「その通りだ。非常事態だからな、きみも手伝ってくれたまえ、エスメラルダ女史」"

[[dialogue]]
speaker = "エスメラルダ"
# 『！！？』
line = "『！！？』"

[[dialogue]]
speaker = "unk"
# 気付いていたんですか？
line = "気付いていたんですか？"

[[dialogue]]
speaker = "ラティエ"
# 「もちろんだ。私の地獄耳を甘く見ないほうがいい」
line = "「もちろんだ。私の地獄耳を甘く見ないほうがいい」"

[[dialogue]]
speaker = "エスメラルダ"
# 「バレているなら身を隠していても仕方ありません」
line = "「バレているなら身を隠していても仕方ありません」"

[[dialogue]]
speaker = "エスメラルダ"
# 「学園長、私はお客様を避難させますので、モンスターの方はお願い致します」
line = "「学園長、私はお客様を避難させますので、モンスターの方はお願い致します」"

[[dialogue]]
speaker = "ラティエ"
# 「ああ、頼んだぞ」
line = "「ああ、頼んだぞ」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「私も戦いますわ！　学園長様に私の力を見ていただく好機ですの！」
line = "「私も戦いますわ！　学園長様に私の力を見ていただく好機ですの！」"

[[dialogue]]
speaker = "ラティエ"
# 「よし、では我々はモンスターがこの区域より散らぬよう抑え込むぞ」
line = "「よし、では我々はモンスターがこの区域より散らぬよう抑え込むぞ」"

[[dialogue]]
speaker = "サラン"
# 「お任せくださいな～」
line = "「お任せくださいな～」"

[[dialogue]]
speaker = "サラン"
# 「スイーツ・フロート～」
line = "「スイーツ・フロート～」"

[[dialogue]]
speaker = "unk"
# サランがドーナツ型の浮き輪を振り回すと、モンスターたちはそれに弾き飛ばされる。
line = "サランがドーナツ型の浮き輪を振り回すと、モンスターたちはそれに弾き飛ばされる。"

[[dialogue]]
speaker = "エルデリーゼ"
# 「バラッジ・オブ・パラソルっ！」
line = "「バラッジ・オブ・パラソルっ！」"

[[dialogue]]
speaker = "unk"
# そこをエルゼの攻撃が的確に狙い、次々とモンスターを倒していく。
line = "そこをエルゼの攻撃が的確に狙い、次々とモンスターを倒していく。"

[[dialogue]]
speaker = "ラティエ"
# 「ふむ……素晴らしい連携だな」
line = "「ふむ……素晴らしい連携だな」"

[[dialogue]]
speaker = "unk"
# ２人の戦いぶりを横目に見ながら、学園長も着実にモンスターの数を減らしていった。
line = "２人の戦いぶりを横目に見ながら、学園長も着実にモンスターの数を減らしていった。"

[[dialogue]]
speaker = "ラティエ"
# 「さて、後はアステラを潰しに行くだけだが……」
line = "「さて、後はアステラを潰しに行くだけだが……」"

[[dialogue]]
speaker = "ラティエ"
# 「会長くん、ついて来てくれるかな？　それから──」
line = "「会長くん、ついて来てくれるかな？　それから──」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「もちろん私も一緒に行きますわ！」
line = "「もちろん私も一緒に行きますわ！」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「決して足手まといにはなりません！　だから連れて行ってくださいませ！」
line = "「決して足手まといにはなりません！　だから連れて行ってくださいませ！」"

[[dialogue]]
speaker = "unk"
# だからエルゼも！
line = "だからエルゼも！"

[[dialogue]]
speaker = "unk"
# いざという時は俺が守ります
line = "いざという時は俺が守ります"

[[dialogue]]
speaker = "ラティエ"
# 「いいだろう」
line = "「いいだろう」"

[[dialogue]]
speaker = "ラティエ"
# 「会長くん、言った以上は責任もって彼女を守り通したまえ」
line = "「会長くん、言った以上は責任もって彼女を守り通したまえ」"

[[dialogue]]
speaker = "unk"
# はいっ！
line = "はいっ！"

[[dialogue]]
speaker = "サラン"
# 「サランはエスメラルダ先生と一緒に、お客様の安全をかくほするよ～」
line = "「サランはエスメラルダ先生と一緒に、お客様の安全をかくほするよ～」"

[[dialogue]]
speaker = "サラン"
# 「だからエルゼ、頑張って戦ってきてね～♪」
line = "「だからエルゼ、頑張って戦ってきてね～♪」"

[[dialogue]]
speaker = "エルデリーゼ"
# 「任せてください、サランお姉さま！」
line = "「任せてください、サランお姉さま！」"
