[[dialogue]]
speaker = "unk"
# ついに所在が明らかになった最後の守護天使──《天恵》のオオヒメ。
line = "ついに所在が明らかになった最後の守護天使──《天恵》のオオヒメ。"

[[dialogue]]
speaker = "unk"
# 堕天使になった彼女を撃破したものの、オオヒメはフィーニスの塔に戻ることなく、神殿に立てこもってしまった。
line = "堕天使になった彼女を撃破したものの、オオヒメはフィーニスの塔に戻ることなく、神殿に立てこもってしまった。"

[[dialogue]]
speaker = "unk"
# そんな彼女を神殿から連れ戻すために──
line = "そんな彼女を神殿から連れ戻すために──"

[[dialogue]]
speaker = "ヴィーナス"
# 「みーんなー、隠し芸大会、盛り上げていくわよー！」
line = "「みーんなー、隠し芸大会、盛り上げていくわよー！」"

[[dialogue]]
speaker = "アイリーン"
# 「はじまりましたー、隠し芸大会！　司会進行は私、魔女アイリーンとミーちゃん！　そして、解説はー？」
line = "「はじまりましたー、隠し芸大会！　司会進行は私、魔女アイリーンとミーちゃん！　そして、解説はー？」"

[[dialogue]]
speaker = "マグダレナ"
# 「私、マグダレナでお送りします」
line = "「私、マグダレナでお送りします」"

[[dialogue]]
speaker = "アイリーン"
# 「マグダレナさん、この度の隠し芸大会、どう見ますかー？」
line = "「マグダレナさん、この度の隠し芸大会、どう見ますかー？」"

[[dialogue]]
speaker = "マグダレナ"
# 「大変興味深いです。解説の身ではありますが、みなさまの渾身の芸、一観客としても楽しませていただきたいと思います」
line = "「大変興味深いです。解説の身ではありますが、みなさまの渾身の芸、一観客としても楽しませていただきたいと思います」"

[[dialogue]]
speaker = "マグダレナ"
# 「しかし、私すら喜ばせられないようでは、オオヒメの心にまで届かせるのは難しいでしょう」
line = "「しかし、私すら喜ばせられないようでは、オオヒメの心にまで届かせるのは難しいでしょう」"

[[dialogue]]
speaker = "アイリーン"
# 「プレッシャーがかかるねー！　さーて、気になるトップバッターは……てゆーか、この空気の中、一番最初に出られる人なんているのかなー？」
line = "「プレッシャーがかかるねー！　さーて、気になるトップバッターは……てゆーか、この空気の中、一番最初に出られる人なんているのかなー？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「もちろん、言い出しっぺの私から行くわ！　さ、みんな、盛り上げて！　手拍子よ！」
line = "「もちろん、言い出しっぺの私から行くわ！　さ、みんな、盛り上げて！　手拍子よ！」"

[[dialogue]]
speaker = "アイリーン"
# 「おーっと、ヴィーナスさんスゴい！　空気を読んでるのか読んでないのか、一番に出られる勇気は見習いたいですねー」
line = "「おーっと、ヴィーナスさんスゴい！　空気を読んでるのか読んでないのか、一番に出られる勇気は見習いたいですねー」"

[[dialogue]]
speaker = "アイリーン"
# 「ですが、ショーレースでは一番最初に披露した人は優勝できないというジンクスがあります」
line = "「ですが、ショーレースでは一番最初に披露した人は優勝できないというジンクスがあります」"

[[dialogue]]
speaker = "マグダレナ"
# 「『まだ始まったばかりだし、この後、もっと面白いネタが控えているのでは』と期待し、判定が厳しめになってしまいがちですからね」
line = "「『まだ始まったばかりだし、この後、もっと面白いネタが控えているのでは』と期待し、判定が厳しめになってしまいがちですからね」"

[[dialogue]]
speaker = "ウズメイア"
# 「ヤバ。マグダレナ様、理解度が高いんだけど」
line = "「ヤバ。マグダレナ様、理解度が高いんだけど」"

[[dialogue]]
speaker = "マグダレナ"
# 「アニマさまの義体で受肉してから、テレビ番組はよく視聴していますから。お笑いや仮装の大会なども見ております」
line = "「アニマさまの義体で受肉してから、テレビ番組はよく視聴していますから。お笑いや仮装の大会なども見ております」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふふーん、そんな下らないジンクスは、木っ端ミジンコにしてみせるわ！　お正月の伝統芸といえば、なんといってもこれ！　傘回しよ！」
line = "「ふふーん、そんな下らないジンクスは、木っ端ミジンコにしてみせるわ！　お正月の伝統芸といえば、なんといってもこれ！　傘回しよ！」"

[[dialogue]]
speaker = "アイリーン"
# 「ヴィーナスさんは晴れ着衣装の傘を、有効に活かすみたいですねー。無駄がないです！」
line = "「ヴィーナスさんは晴れ着衣装の傘を、有効に活かすみたいですねー。無駄がないです！」"

[[dialogue]]
speaker = "マグダレナ"
# 「ふむ、傘回しですか。ヴィーナスさまならではの破天荒な技をみせていただけるでしょうか」
line = "「ふむ、傘回しですか。ヴィーナスさまならではの破天荒な技をみせていただけるでしょうか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「さぁ、みんな、なんでも投げてちょうだい！　どんなものだって、傘の上でぶん回してみせるわ！　まずはボールから！　よっ、ほっ、はーっ」
line = "「さぁ、みんな、なんでも投げてちょうだい！　どんなものだって、傘の上でぶん回してみせるわ！　まずはボールから！　よっ、ほっ、はーっ」"

[[dialogue]]
speaker = "ウズメイア"
# 「えっ、すごいすごーい！　どうやってんのー？」
line = "「えっ、すごいすごーい！　どうやってんのー？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そこは企業秘密よ！　お次は四角いマスね。角ばってるから難しいのよね、ほっ！」
line = "「そこは企業秘密よ！　お次は四角いマスね。角ばってるから難しいのよね、ほっ！」"

[[dialogue]]
speaker = "フィオナ"
# 「では、この羽子板も。えいっ」
line = "「では、この羽子板も。えいっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私にかかれば、お茶の子さいさいだわ！　ほっ、ほっ、ほっ、ジャンプまでさせちゃうわね！　えーいやっ！」
line = "「私にかかれば、お茶の子さいさいだわ！　ほっ、ほっ、ほっ、ジャンプまでさせちゃうわね！　えーいやっ！」"

[[dialogue]]
speaker = "アイリーン"
# 「あはは、ミーちゃんも回してもらったらー？」
line = "「あはは、ミーちゃんも回してもらったらー？」"

[[dialogue]]
speaker = "ミーちゃん"
# 「ホーホー！」
line = "「ホーホー！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「大物だって生き物だって問題なしよ！　いつもより多く回してあげるわ！　おめでとうございまーす！　以上よ！」
line = "「大物だって生き物だって問題なしよ！　いつもより多く回してあげるわ！　おめでとうございまーす！　以上よ！」"

[[dialogue]]
speaker = "アイリーン"
# 「素晴らしい傘回しでしたけど、気になるオオヒメ様の反応はー！？」
line = "「素晴らしい傘回しでしたけど、気になるオオヒメ様の反応はー！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ひらけゴマー！」
line = "「ひらけゴマー！」"

[[dialogue]]
speaker = "マグダレナ"
# 「…………反応はありませんね。どうやらお気に召さなかったようです」
line = "「…………反応はありませんね。どうやらお気に召さなかったようです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「えーっ、どうしてよ！　完璧な出来栄えだったじゃない！」
line = "「えーっ、どうしてよ！　完璧な出来栄えだったじゃない！」"

[[dialogue]]
speaker = "アイリーン"
# 「ヴィーナスさんにしては、ちょっと地味な芸だったかなー」
line = "「ヴィーナスさんにしては、ちょっと地味な芸だったかなー」"

[[dialogue]]
speaker = "マグダレナ"
# 「もうひとつ、大きなオチが待っているのに期待してしまいました。トップバッターの難しいところですね」
line = "「もうひとつ、大きなオチが待っているのに期待してしまいました。トップバッターの難しいところですね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「くうう、手厳しいわね！　でもちゃんと場はあっためたわ！　次はフィオナ、よろしくね！」
line = "「くうう、手厳しいわね！　でもちゃんと場はあっためたわ！　次はフィオナ、よろしくね！」"

[[dialogue]]
speaker = "フィオナ"
# 「わ、私ですか！？　何も準備してませんよ！？」
line = "「わ、私ですか！？　何も準備してませんよ！？」"

[[dialogue]]
speaker = "ソフィア"
# 「期待してます、フィオナ会長」
line = "「期待してます、フィオナ会長」"

[[dialogue]]
speaker = "ウズメイア"
# 「会長がんば～！」
line = "「会長がんば～！」"

[[dialogue]]
speaker = "フィオナ"
# 「くっ……期待を寄せられているからにはやらないわけにはいきません」
line = "「くっ……期待を寄せられているからにはやらないわけにはいきません」"

[[dialogue]]
speaker = "フィオナ"
# 「では、姉さん仕込みの、流星ライダーの変身ポーズを披露します……こほん」
line = "「では、姉さん仕込みの、流星ライダーの変身ポーズを披露します……こほん」"

[[dialogue]]
speaker = "フィオナ"
# 「出たな、モスキート怪人！」
line = "「出たな、モスキート怪人！」"

[[dialogue]]
speaker = "フィオナ"
# 「しゃきーん……はぁぁぁぁっ……！　ライッダー変ッ身！」
line = "「しゃきーん……はぁぁぁぁっ……！　ライッダー変ッ身！」"

[[dialogue]]
speaker = "フィオナ"
# 「ぎゅいんぎゅいんぎゅいん、とぉ～～～っ！　流星ライダー参ッ・上ッ！」
line = "「ぎゅいんぎゅいんぎゅいん、とぉ～～～っ！　流星ライダー参ッ・上ッ！」"

[[dialogue]]
speaker = "マグダレナ"
# 「………………」
line = "「………………」"

[[dialogue]]
speaker = "アイリーン"
# 「えーっと、終わりってことでいーい？」
line = "「えーっと、終わりってことでいーい？」"

[[dialogue]]
speaker = "フィオナ"
# 「は、はい、どうだったでしょう……？」
line = "「は、はい、どうだったでしょう……？」"

[[dialogue]]
speaker = "ウズメイア"
# 「フィオナ会長……ごめんだけど、かなりビミョぃ～～……」
line = "「フィオナ会長……ごめんだけど、かなりビミョぃ～～……」"

[[dialogue]]
speaker = "フィオナ"
# 「そ、そんなっ……！？」
line = "「そ、そんなっ……！？」"

[[dialogue]]
speaker = "舞亜"
# 「見ててこっちが恥ずかしくなってきちゃった」
line = "「見ててこっちが恥ずかしくなってきちゃった」"

[[dialogue]]
speaker = "ソフィア"
# 「申し訳ないです……会長に無理強いしてしまったばかりに……」
line = "「申し訳ないです……会長に無理強いしてしまったばかりに……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「照れが残っていたのは、減点対象ね。やるからにはアポロくらい振り切ってなきゃだわ」
line = "「照れが残っていたのは、減点対象ね。やるからにはアポロくらい振り切ってなきゃだわ」"

[[dialogue]]
speaker = "マグダレナ"
# 「すみません……私は流星ライダーを存じ上げないので、よくわかりませんでした」
line = "「すみません……私は流星ライダーを存じ上げないので、よくわかりませんでした」"

[[dialogue]]
speaker = "アイリーン"
# 「オオヒメさんも流星ライダーを知らなかったら、完成度の良し悪しが分からないしねー」
line = "「オオヒメさんも流星ライダーを知らなかったら、完成度の良し悪しが分からないしねー」"

[[dialogue]]
speaker = "ヴィーナス"
# 「滑ったなら滑ったなりに滑り芸に昇華できればワンチャンあったかもだけど、フィオナにはハードルが高かったわね！」
line = "「滑ったなら滑ったなりに滑り芸に昇華できればワンチャンあったかもだけど、フィオナにはハードルが高かったわね！」"

[[dialogue]]
speaker = "マグダレナ"
# 「オオヒメも反応していませんね……。むしろ、より深くまで潜ってしまったように思います」
line = "「オオヒメも反応していませんね……。むしろ、より深くまで潜ってしまったように思います」"

[[dialogue]]
speaker = "フィオナ"
# 「そんな～～～っ！？」
line = "「そんな～～～っ！？」"

[[dialogue]]
speaker = "フィオナ"
# 「くぅっ……もっと精進しなければ……姉さんに教わり、完成度を高めておきます……」
line = "「くぅっ……もっと精進しなければ……姉さんに教わり、完成度を高めておきます……」"

[[dialogue]]
speaker = "ウズメイア"
# 「完成度の問題じゃないような……？　ていうかこの空気、どうしよ？」
line = "「完成度の問題じゃないような……？　ていうかこの空気、どうしよ？」"

[[dialogue]]
speaker = "？？？"
# 「芸と言われたら、私たちが出ないわけにはいかないよね」
line = "「芸と言われたら、私たちが出ないわけにはいかないよね」"

[[dialogue]]
speaker = "？？？？"
# 「本物の隠し芸、見せてあげちゃうよー！」
line = "「本物の隠し芸、見せてあげちゃうよー！」"

[[dialogue]]
speaker = "フィオナ"
# 「あ、あなたたちは──！？」
line = "「あ、あなたたちは──！？」"
