[[dialogue]]
speaker = "unk"
# シズハがソフィアと組む一方で、リーリアはウズメイアと組んで羽根突きの練習を行うことになった。
line = "シズハがソフィアと組む一方で、リーリアはウズメイアと組んで羽根突きの練習を行うことになった。"

[[dialogue]]
speaker = "ウズメイア"
# 「今日の出会いに感謝、まさに<ruby=いちごいちえ>一期一会</ruby>ってね♪　というわけでリーリアちゃん、よろしく～♪」
line = "「今日の出会いに感謝、まさに<ruby>一期一会<rt>いちごいちえ</rt></ruby>ってね♪　というわけでリーリアちゃん、よろしく～♪」"

[[dialogue]]
speaker = "リーリア"
# 「はい♪　改めて、渋谷リーリアで～す。よろしくね、ウズメイアちゃん☆」
line = "「はい♪　改めて、渋谷リーリアで～す。よろしくね、ウズメイアちゃん☆」"

[[dialogue]]
speaker = "ウズメイア"
# 「あたしたち、同じ１年生なのにこれまで接点があまりなかったから、こうして新年の最初から縁ができて、ウズウズしてるし♪」
line = "「あたしたち、同じ１年生なのにこれまで接点があまりなかったから、こうして新年の最初から縁ができて、ウズウズしてるし♪」"

[[dialogue]]
speaker = "リーリア"
# 「私も私も☆　今年はなんだか、縁がありそうだよね～♪」
line = "「私も私も☆　今年はなんだか、縁がありそうだよね～♪」"

[[dialogue]]
speaker = "舞亜"
# 「アナさん、よろしく～」
line = "「アナさん、よろしく～」"

[[dialogue]]
speaker = "アナ"
# 「はい、舞亜さん。よろしくお願いします」
line = "「はい、舞亜さん。よろしくお願いします」"

[[dialogue]]
speaker = "unk"
# その横で、アナは舞亜と組んで練習を開始する。
line = "その横で、アナは舞亜と組んで練習を開始する。"

[[dialogue]]
speaker = "ウズメイア"
# 「それじゃあ、リーリアちゃん、行っくよ～♪　ていっ！」
line = "「それじゃあ、リーリアちゃん、行っくよ～♪　ていっ！」"

[[dialogue]]
speaker = "リーリア"
# 「マジカルバッチコイです☆　はいっ！」
line = "「マジカルバッチコイです☆　はいっ！」"

[[dialogue]]
speaker = "リーリア"
# 「――そういえば、気になってたんだけど、ウズメイアちゃんたちは晴れ着フォームの力はもう使えてるよね？」
line = "「――そういえば、気になってたんだけど、ウズメイアちゃんたちは晴れ着フォームの力はもう使えてるよね？」"

[[dialogue]]
speaker = "リーリア"
# 「だったら、無理に獅子舞さんに羽根突きで勝とうとしなくても、大丈夫なんじゃ……」
line = "「だったら、無理に獅子舞さんに羽根突きで勝とうとしなくても、大丈夫なんじゃ……」"

[[dialogue]]
speaker = "ウズメイア"
# 「え？　ああ、それね～。確かにあたし達は、必ずしも参加する必要はないかもだけど――」
line = "「え？　ああ、それね～。確かにあたし達は、必ずしも参加する必要はないかもだけど――」"

[[dialogue]]
speaker = "ウズメイア"
# 「リーリアちゃんたちが獅子舞さんとバトルしてるのに、直接関係ないからって『頑張ってね～』って出てっちゃうのは、なんか違うじゃん？」
line = "「リーリアちゃんたちが獅子舞さんとバトルしてるのに、直接関係ないからって『頑張ってね～』って出てっちゃうのは、なんか違うじゃん？」"

[[dialogue]]
speaker = "ウズメイア"
# 「あたし達は学園が違っていても一緒にリクリエと戦う仲間なんだし、こういうのはお互い様、助け合いっしょ♪」
line = "「あたし達は学園が違っていても一緒にリクリエと戦う仲間なんだし、こういうのはお互い様、助け合いっしょ♪」"

[[dialogue]]
speaker = "リーリア"
# 「ウズメイアちゃん……！　めっちゃいい子！」
line = "「ウズメイアちゃん……！　めっちゃいい子！」"

[[dialogue]]
speaker = "ウズメイア"
# 「あははっ、大げさだし♪　ソフィと舞亜も一緒に参加してるんだから、別にあたしだけの考えってわけじゃないよ～」
line = "「あははっ、大げさだし♪　ソフィと舞亜も一緒に参加してるんだから、別にあたしだけの考えってわけじゃないよ～」"

[[dialogue]]
speaker = "ウズメイア"
# 「それに個人的な趣味もあってさ～。あたし、純粋に日本文化が大好きなんだよね！」
line = "「それに個人的な趣味もあってさ～。あたし、純粋に日本文化が大好きなんだよね！」"

[[dialogue]]
speaker = "ウズメイア"
# 「だからみんなと一緒に、こうやって羽根突きをするの、楽しそうだな～って♪」
line = "「だからみんなと一緒に、こうやって羽根突きをするの、楽しそうだな～って♪」"

[[dialogue]]
speaker = "リーリア"
# 「あっ、ウズメイアちゃんも日本文化、好きなんだ！？　実は私もなんだ♪」
line = "「あっ、ウズメイアちゃんも日本文化、好きなんだ！？　実は私もなんだ♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「えっ、そうなの！？　だったらあたしたち、めっちゃ気が合うじゃん！」
line = "「えっ、そうなの！？　だったらあたしたち、めっちゃ気が合うじゃん！」"

[[dialogue]]
speaker = "リーリア"
# 「バトルフェスタの時に宣言してたから、ウズメイアちゃんたちも知ってるとは思うんだけど……私、魔女なんだよね」
line = "「バトルフェスタの時に宣言してたから、ウズメイアちゃんたちも知ってるとは思うんだけど……私、魔女なんだよね」"

[[dialogue]]
speaker = "リーリア"
# 「だから、人間界に来たのは、学園に入学する時が初めてだったんだ……」
line = "「だから、人間界に来たのは、学園に入学する時が初めてだったんだ……」"

[[dialogue]]
speaker = "リーリア"
# 「生まれてからずっと、魔女の森に引きこもらされてたから……私にとって、人間界は何もかも新鮮な色で溢れてて、すごくワクワクしたんだ♪」
line = "「生まれてからずっと、魔女の森に引きこもらされてたから……私にとって、人間界は何もかも新鮮な色で溢れてて、すごくワクワクしたんだ♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「わかる～！　あたしも昔、天界で人間界の本を読んで、すっごくワクワクしたもん！　いつか絶対人間界に行きたいって、ずっと憧れてたんだよね～」
line = "「わかる～！　あたしも昔、天界で人間界の本を読んで、すっごくワクワクしたもん！　いつか絶対人間界に行きたいって、ずっと憧れてたんだよね～」"

[[dialogue]]
speaker = "ウズメイア"
# 「ねぇねぇ、リーリアちゃんは、人間界で何が１番好きなの？」
line = "「ねぇねぇ、リーリアちゃんは、人間界で何が１番好きなの？」"

[[dialogue]]
speaker = "リーリア"
# 「う～ん、実はそれがなかなか決められないんだよね～。色んなものを知るたびに、どんどん好きが増えてっちゃう感じで～」
line = "「う～ん、実はそれがなかなか決められないんだよね～。色んなものを知るたびに、どんどん好きが増えてっちゃう感じで～」"

[[dialogue]]
speaker = "リーリア"
# 「人間界の衣装は可愛いものが色々あるし～、美味しくてカラフルなスイーツとかも沢山あって～」
line = "「人間界の衣装は可愛いものが色々あるし～、美味しくてカラフルなスイーツとかも沢山あって～」"

[[dialogue]]
speaker = "リーリア"
# 「でも……特に好きなのは、やっぱり『学園』かな」
line = "「でも……特に好きなのは、やっぱり『学園』かな」"

[[dialogue]]
speaker = "リーリア"
# 「素敵な『自分の色』を持っている友達と、学園に通って楽しむ、絶えず鮮やかに色が移り変わっていく青春――私はそれが、すごく大好きで大切なものなんだ☆」
line = "「素敵な『自分の色』を持っている友達と、学園に通って楽しむ、絶えず鮮やかに色が移り変わっていく青春――私はそれが、すごく大好きで大切なものなんだ☆」"

[[dialogue]]
speaker = "ウズメイア"
# 「～～～っ！　それ、すっごくいいよ、<b>リーリア</b>ちゃん！　ううん、<b>リーリア</b>！」
line = "「～～～っ！　それ、すっごくいいよ、<b>リーリア</b>ちゃん！　ううん、<b>リーリア</b>！」"

[[dialogue]]
speaker = "リーリア"
# 「って、わわっ！？　なになに？　ウズメイアちゃん！？」
line = "「って、わわっ！？　なになに？　ウズメイアちゃん！？」"

[[dialogue]]
speaker = "unk"
# 羽根突きの羽根を返すのも忘れ、リーリアに歩み寄ってその両手を取るウズメイア。
line = "羽根突きの羽根を返すのも忘れ、リーリアに歩み寄ってその両手を取るウズメイア。"

[[dialogue]]
speaker = "ウズメイア"
# 「会った瞬間からそんな気がしてたし、さっきも言ったけど……あたしたち、絶対に気が合うよ！　だから、今日から改めて友達になろう、リーリア！」
line = "「会った瞬間からそんな気がしてたし、さっきも言ったけど……あたしたち、絶対に気が合うよ！　だから、今日から改めて友達になろう、リーリア！」"

[[dialogue]]
speaker = "リーリア"
# 「い、いきなりどうしたんですか！？　急に距離詰めて来るから、ビックリしちゃうんですけど！？」
line = "「い、いきなりどうしたんですか！？　急に距離詰めて来るから、ビックリしちゃうんですけど！？」"

[[dialogue]]
speaker = "ウズメイア"
# 「敬語なんてめんどいっしょ！　ギャル同士、バイブスあげてかなきゃなんだから！」
line = "「敬語なんてめんどいっしょ！　ギャル同士、バイブスあげてかなきゃなんだから！」"

[[dialogue]]
speaker = "リーリア"
# 「私ってギャル認定なの！？　まあそっち系のファッション好きだけど！！」
line = "「私ってギャル認定なの！？　まあそっち系のファッション好きだけど！！」"

[[dialogue]]
speaker = "ウズメイア"
# 「あたしの周り、みんなノリがいいんだけど、それでもギャル同士じゃないと合わないバイブスもあるっしょ！」
line = "「あたしの周り、みんなノリがいいんだけど、それでもギャル同士じゃないと合わないバイブスもあるっしょ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ほらほら、リーリアもあたしのことも<b>ウズメ</b>って呼ぶし！　ねっ、ねっ！？」
line = "「ほらほら、リーリアもあたしのことも<b>ウズメ</b>って呼ぶし！　ねっ、ねっ！？」"

[[dialogue]]
speaker = "リーリア"
# 「あ～、えっとぉ～……うん。じゃあ……ウズメ」
line = "「あ～、えっとぉ～……うん。じゃあ……ウズメ」"

[[dialogue]]
speaker = "unk"
# リーリアはちょっと照れ臭そうにしながらも、頬を緩めながらウズメイアを愛称で呼ぶ。
line = "リーリアはちょっと照れ臭そうにしながらも、頬を緩めながらウズメイアを愛称で呼ぶ。"

[[dialogue]]
speaker = "ウズメイア"
# 「うんっ♪　リーリア、よろしくね♪」
line = "「うんっ♪　リーリア、よろしくね♪」"

[[dialogue]]
speaker = "リーリア"
# 「ん……えへへへっ♪　いや～、友達の輪がまたカラフルになっちゃったな～」
line = "「ん……えへへへっ♪　いや～、友達の輪がまたカラフルになっちゃったな～」"

[[dialogue]]
speaker = "unk"
# 未だ照れた色を含みながらも、嬉しそうな笑顔を浮かべるリーリア。
line = "未だ照れた色を含みながらも、嬉しそうな笑顔を浮かべるリーリア。"

[[dialogue]]
speaker = "ウズメイア"
# 「そうだ！　今度一緒に遊びに出かけようよ♪　舞亜とソフィに、アナちゃんも誘って～、１年生組で！」
line = "「そうだ！　今度一緒に遊びに出かけようよ♪　舞亜とソフィに、アナちゃんも誘って～、１年生組で！」"

[[dialogue]]
speaker = "unk"
# テンションの上がりまくったウズメイアが、ばっと勢いよく舞亜とアナの方を振り向く。
line = "テンションの上がりまくったウズメイアが、ばっと勢いよく舞亜とアナの方を振り向く。"

[[dialogue]]
speaker = "舞亜"
# 「すぅ……すぅ……」
line = "「すぅ……すぅ……」"

[[dialogue]]
speaker = "アナ"
# 「すや……すや……」
line = "「すや……すや……」"

[[dialogue]]
speaker = "ウズメイア"
# 「って、なんかあの２人、立ったまま寝てる！？」
line = "「って、なんかあの２人、立ったまま寝てる！？」"

[[dialogue]]
speaker = "舞亜"
# 「ん……？　あ……どうかした、ウズメ？」
line = "「ん……？　あ……どうかした、ウズメ？」"

[[dialogue]]
speaker = "アナ"
# 「……ふぅ。舞亜さん、いま起きました。きっかり５分で起きられたと思うのですが、いかがだったでしょう？」
line = "「……ふぅ。舞亜さん、いま起きました。きっかり５分で起きられたと思うのですが、いかがだったでしょう？」"

[[dialogue]]
speaker = "舞亜"
# 「ごめん、アナさんが気持ち良さそうに寝てるの見てたら、私もいつの間にかうとうとしちゃってたみたいで……」
line = "「ごめん、アナさんが気持ち良さそうに寝てるの見てたら、私もいつの間にかうとうとしちゃってたみたいで……」"

[[dialogue]]
speaker = "ウズメイア"
# 「えっと……なんでアナちゃんたちは立って寝てたわけ？」
line = "「えっと……なんでアナちゃんたちは立って寝てたわけ？」"

[[dialogue]]
speaker = "アナ"
# 「実は舞亜さんとお互いのことについて話をしていたら、『どこでも寝られる』という共通の特技があることがわかりまして」
line = "「実は舞亜さんとお互いのことについて話をしていたら、『どこでも寝られる』という共通の特技があることがわかりまして」"

[[dialogue]]
speaker = "舞亜"
# 「アナさんにはキッチリ５分だけ仮眠して起きられる技があるらしくて、実演してもらってたんだ」
line = "「アナさんにはキッチリ５分だけ仮眠して起きられる技があるらしくて、実演してもらってたんだ」"

[[dialogue]]
speaker = "ウズメイア"
# 「立ったまま仮眠してたの！？　２人で寄りかかり合って！？」
line = "「立ったまま仮眠してたの！？　２人で寄りかかり合って！？」"

[[dialogue]]
speaker = "アナ"
# 「『どこでも寝られる』とはつまり、立ったままでも可能ということです」
line = "「『どこでも寝られる』とはつまり、立ったままでも可能ということです」"

[[dialogue]]
speaker = "舞亜"
# 「私も寝ることについては自信があったんだけど、アナさんみたいに目覚ましなしで、短時間でパッと起きられるのはすごいね。試合前とかに使えたら便利そう」
line = "「私も寝ることについては自信があったんだけど、アナさんみたいに目覚ましなしで、短時間でパッと起きられるのはすごいね。試合前とかに使えたら便利そう」"

[[dialogue]]
speaker = "アナ"
# 「反復練習で体に覚えさせる感じなので、アスリートである舞亜さんなら、私よりも早く習得できますよ」
line = "「反復練習で体に覚えさせる感じなので、アスリートである舞亜さんなら、私よりも早く習得できますよ」"

[[dialogue]]
speaker = "舞亜"
# 「本当？　じゃあ、後で練習に付き合ってもらってもいい、アナさん？」
line = "「本当？　じゃあ、後で練習に付き合ってもらってもいい、アナさん？」"

[[dialogue]]
speaker = "アナ"
# 「ノープロブレム。睡眠について語れる同士は、貴重ですから」
line = "「ノープロブレム。睡眠について語れる同士は、貴重ですから」"

[[dialogue]]
speaker = "ウズメイア"
# 「意外なところで通じ合ってるし……」
line = "「意外なところで通じ合ってるし……」"

[[dialogue]]
speaker = "舞亜"
# 「ふふっ、確かにあんまり居ないよね。アナさんは、他には好きなものとかある？」
line = "「ふふっ、確かにあんまり居ないよね。アナさんは、他には好きなものとかある？」"

[[dialogue]]
speaker = "アナ"
# 「和菓子、でしょうか。あれはまさに、女神様が人間界で最初に作ったものに違いありません」
line = "「和菓子、でしょうか。あれはまさに、女神様が人間界で最初に作ったものに違いありません」"

[[dialogue]]
speaker = "舞亜"
# 「あ、そうなんだ。私も甘い物は好きだよ」
line = "「あ、そうなんだ。私も甘い物は好きだよ」"

[[dialogue]]
speaker = "舞亜"
# 「ただ、カロリー制限しないと体重増えてスケートに支障が出ちゃうから、低カロリーの和菓子を自分で作ったりするかな」
line = "「ただ、カロリー制限しないと体重増えてスケートに支障が出ちゃうから、低カロリーの和菓子を自分で作ったりするかな」"

[[dialogue]]
speaker = "アナ"
# 「！　なんと、自作ですか。ちなみにどういったものを……？」
line = "「！　なんと、自作ですか。ちなみにどういったものを……？」"

[[dialogue]]
speaker = "舞亜"
# 「う～んとね～。私がよく作るのだと、寒天ゼリーかな。あとは水ようかん、わらび餅、大福、おはぎとか？」
line = "「う～んとね～。私がよく作るのだと、寒天ゼリーかな。あとは水ようかん、わらび餅、大福、おはぎとか？」"

[[dialogue]]
speaker = "舞亜"
# 「個人的に、満足感があって気に入ってるのは、フルーツ大福かな。あんを少なめにして、代わりに果物を包むの。美味しくて、カロリー調節もしやすいんだ」
line = "「個人的に、満足感があって気に入ってるのは、フルーツ大福かな。あんを少なめにして、代わりに果物を包むの。美味しくて、カロリー調節もしやすいんだ」"

[[dialogue]]
speaker = "アナ"
# 「フルーツ大福……じゅるり。そ、それは確かに美味しそうですね……」
line = "「フルーツ大福……じゅるり。そ、それは確かに美味しそうですね……」"

[[dialogue]]
speaker = "舞亜"
# 「ふふふっ♪　アナさん、すごく食べたそうな顔してる。本当に和菓子が好きなんだね。今度作ってきてあげよっか？」
line = "「ふふふっ♪　アナさん、すごく食べたそうな顔してる。本当に和菓子が好きなんだね。今度作ってきてあげよっか？」"

[[dialogue]]
speaker = "アナ"
# 「あなたが神か……！　一生ついていきます」
line = "「あなたが神か……！　一生ついていきます」"

[[dialogue]]
speaker = "舞亜"
# 「わかった。じゃあ、それも今度。約束だね」
line = "「わかった。じゃあ、それも今度。約束だね」"

[[dialogue]]
speaker = "アナ"
# 「はい！　美味しい和菓子があれば何でもするので、いつでも呼んでください、舞亜さん」
line = "「はい！　美味しい和菓子があれば何でもするので、いつでも呼んでください、舞亜さん」"

[[dialogue]]
speaker = "ウズメイア"
# 「どうやらアナちゃんと舞亜も気が合ったみたいだし☆」
line = "「どうやらアナちゃんと舞亜も気が合ったみたいだし☆」"

[[dialogue]]
speaker = "リーリア"
# 「アナちゃん、舞亜ちゃんにものすごく綺麗な敬礼してるけど、本当にこれでよかったの？」
line = "「アナちゃん、舞亜ちゃんにものすごく綺麗な敬礼してるけど、本当にこれでよかったの？」"

[[dialogue]]
speaker = "舞亜"
# 「あっ。ウズメとリーリアさんも、和菓子の試食会、くる？」
line = "「あっ。ウズメとリーリアさんも、和菓子の試食会、くる？」"

[[dialogue]]
speaker = "ウズメイア"
# 「いいのっ！？　それもすっごく楽しそう～♪」
line = "「いいのっ！？　それもすっごく楽しそう～♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「あとね、さっきリーリアとも話してたんだけど、１年生組で――ううん、というか今日初詣に集まったみんなで、後で一緒に遊びに行こうよ！」
line = "「あとね、さっきリーリアとも話してたんだけど、１年生組で――ううん、というか今日初詣に集まったみんなで、後で一緒に遊びに行こうよ！」"

[[dialogue]]
speaker = "リーリア"
# 「賛成～！　どうせなら初詣の後に、みんなで浅草巡りに繰り出しちゃいますか☆」
line = "「賛成～！　どうせなら初詣の後に、みんなで浅草巡りに繰り出しちゃいますか☆」"

[[dialogue]]
speaker = "舞亜"
# 「うん、もちろんいいよ。私もまだまだアナさんと話したいことがあるし」
line = "「うん、もちろんいいよ。私もまだまだアナさんと話したいことがあるし」"

[[dialogue]]
speaker = "アナ"
# 「では、そうと決まったら、なるべく早く獅子舞さんに勝たないとですね」
line = "「では、そうと決まったら、なるべく早く獅子舞さんに勝たないとですね」"

[[dialogue]]
speaker = "リーリア"
# 「うん☆　私もそろそろ、マジカル本気を出しちゃいますよ～！」
line = "「うん☆　私もそろそろ、マジカル本気を出しちゃいますよ～！」"

[[dialogue]]
speaker = "unk"
# それからしばらくして──
line = "それからしばらくして──"

[[dialogue]]
speaker = "獅子舞"
# 「どういうつもりだ？　まさかもう、吾輩に挑むつもりか？」
line = "「どういうつもりだ？　まさかもう、吾輩に挑むつもりか？」"

[[dialogue]]
speaker = "unk"
# 全員が集合して見守る中、１人の星騎士が獅子舞と対峙する。
line = "全員が集合して見守る中、１人の星騎士が獅子舞と対峙する。"

[[dialogue]]
speaker = "リーリア"
# 「はい。獅子舞さん……私が、あなたに改めて勝負を挑みます！」
line = "「はい。獅子舞さん……私が、あなたに改めて勝負を挑みます！」"

[[dialogue]]
speaker = "獅子舞"
# 「渋谷リーリア……威勢はいいが、吾輩が見る限り、お前はまだまだ練習が足りていない。それでも挑む気か？」
line = "「渋谷リーリア……威勢はいいが、吾輩が見る限り、お前はまだまだ練習が足りていない。それでも挑む気か？」"

[[dialogue]]
speaker = "リーリア"
# 「策があります。あと――名指しで『認めん』って言われっぱなしのままなのは、めちゃ悔しいんで！」
line = "「策があります。あと――名指しで『認めん』って言われっぱなしのままなのは、めちゃ悔しいんで！」"

[[dialogue]]
speaker = "獅子舞"
# 「ふん……そうか。ならば、見せてもらうとしよう」
line = "「ふん……そうか。ならば、見せてもらうとしよう」"

[[dialogue]]
speaker = "獅子舞"
# 「吾輩にどうやって認めさせるつもりなのか――来るがいい！」
line = "「吾輩にどうやって認めさせるつもりなのか――来るがいい！」"

[[dialogue]]
speaker = "リーリア"
# 「いざ、マジカルにレディーゴーです！」
line = "「いざ、マジカルにレディーゴーです！」"

[[dialogue]]
speaker = "unk"
# こうして、リーリアと獅子舞の羽根突き勝負が幕を開けるのだった。
line = "こうして、リーリアと獅子舞の羽根突き勝負が幕を開けるのだった。"
