[[dialogue]]
speaker = "unk"
# それから数日が経過した。
line = "それから数日が経過した。"

[[dialogue]]
speaker = "unk"
# 俺とルリエル、ラファエロとステラの４人は協力して、赤ちゃんクマロボの面倒を見続けている。
line = "俺とルリエル、ラファエロとステラの４人は協力して、赤ちゃんクマロボの面倒を見続けている。"

[[dialogue]]
speaker = "ステラ"
# 「そ、それにしても……黒ベア子さんはいつ頃この子を迎えに来るのでしょうか？」
line = "「そ、それにしても……黒ベア子さんはいつ頃この子を迎えに来るのでしょうか？」"

[[dialogue]]
speaker = "ラファエロ"
# 「思ったよりも時間がかかっているようだね。ぼくもこんなに滞在が長引くとは思っていなかったよ」
line = "「思ったよりも時間がかかっているようだね。ぼくもこんなに滞在が長引くとは思っていなかったよ」"

[[dialogue]]
speaker = "ラファエロ"
# 「幸いだったのはこの世界がとても住み心地よい場所であるという点かな。みんなとても親切にしてくれるし、寮の生活も快適だ」
line = "「幸いだったのはこの世界がとても住み心地よい場所であるという点かな。みんなとても親切にしてくれるし、寮の生活も快適だ」"

[[dialogue]]
speaker = "ラファエロ"
# 「不思議なのはステラ、きみが寮の部屋に戻らずに生活しているということなんだが……」
line = "「不思議なのはステラ、きみが寮の部屋に戻らずに生活しているということなんだが……」"

[[dialogue]]
speaker = "ステラ"
# 「ボクはちょっと……人の多い場所が苦手で……。親切な人ばかりだし、設備もちゃんとしてるのは分かるんですけど……」
line = "「ボクはちょっと……人の多い場所が苦手で……。親切な人ばかりだし、設備もちゃんとしてるのは分かるんですけど……」"

[[dialogue]]
speaker = "ラファエロ"
# 「ふむふむ。それで、この星徒会室の一角を間借りしているというわけなんだね」
line = "「ふむふむ。それで、この星徒会室の一角を間借りしているというわけなんだね」"

[[dialogue]]
speaker = "unk"
# ステラは『なるべく引きこもらせてほしい』とのことで、星徒会室の一角をパーテーションで包囲して、即席の居住スペースを作り出していた。
line = "ステラは『なるべく引きこもらせてほしい』とのことで、星徒会室の一角をパーテーションで包囲して、即席の居住スペースを作り出していた。"

[[dialogue]]
speaker = "unk"
# まあ、いいんだけれども。ゲストの要望なので。
line = "まあ、いいんだけれども。ゲストの要望なので。"

[[dialogue]]
speaker = "ステラ"
# 「流星寮で生活していると……<ruby=ここ>星徒会室</ruby>に来るまでに、どうしても人がいっぱいいる場所を通らないといけませんし……」
line = "「流星寮で生活していると……<ruby>星徒会室<rt>ここ</rt></ruby>に来るまでに、どうしても人がいっぱいいる場所を通らないといけませんし……」"

[[dialogue]]
speaker = "ステラ"
# 「それにこの部屋、なんだかとっても落ち着くんですよね……」
line = "「それにこの部屋、なんだかとっても落ち着くんですよね……」"

[[dialogue]]
speaker = "unk"
# アルテもそんなことを言ってたな
line = "アルテもそんなことを言ってたな"

[[dialogue]]
speaker = "unk"
# そう言えば以前……
line = "そう言えば以前……"

[[dialogue]]
speaker = "ラファエロ"
# 「ああ、アルテなら確かに言いそうだ。あの子は夢幻美術館でも執務室に入り浸っているからね」
line = "「ああ、アルテなら確かに言いそうだ。あの子は夢幻美術館でも執務室に入り浸っているからね」"

[[dialogue]]
speaker = "ラファエロ"
# 「しかし驚いたよ。アルテも以前、この世界へ飛ばされてきたことがあったなんて」
line = "「しかし驚いたよ。アルテも以前、この世界へ飛ばされてきたことがあったなんて」"

[[dialogue]]
speaker = "unk"
# 以前、黒ベア子がこの世界にやってきて、クマロボを大量発生させる事件を引き起こしたことがあった。
line = "以前、黒ベア子がこの世界にやってきて、クマロボを大量発生させる事件を引き起こしたことがあった。"

[[dialogue]]
speaker = "unk"
# その時、ラファエロのいた芸術都市アテネスからやってきたのが、天才美少女藝術家のアルテだった。
line = "その時、ラファエロのいた芸術都市アテネスからやってきたのが、天才美少女藝術家のアルテだった。"

[[dialogue]]
speaker = "ステラ"
# 「そういえばラファエロさんは……流星寮に絵を提供しているんですよね……？」
line = "「そういえばラファエロさんは……流星寮に絵を提供しているんですよね……？」"

[[dialogue]]
speaker = "ラファエロ"
# 「住まわせてもらっているお礼に絵を描いたんだけど、それをロビーに飾ってもらえてね」
line = "「住まわせてもらっているお礼に絵を描いたんだけど、それをロビーに飾ってもらえてね」"

[[dialogue]]
speaker = "ラファエロ"
# 「それが思いのほか好評で、寮長のヒルディオーネさんからも次回作を期待されているんだ」
line = "「それが思いのほか好評で、寮長のヒルディオーネさんからも次回作を期待されているんだ」"

[[dialogue]]
speaker = "ラファエロ"
# 「近頃ではぼく自身の知名度も上がってきているみたいで、今日もここに来る前にサインを求められてしまったよ」
line = "「近頃ではぼく自身の知名度も上がってきているみたいで、今日もここに来る前にサインを求められてしまったよ」"

[[dialogue]]
speaker = "ステラ"
# 「そ、そんなことになってたんですか……大変ですね……」
line = "「そ、そんなことになってたんですか……大変ですね……」"

[[dialogue]]
speaker = "ラファエロ"
# 「ふふっ……それが天才藝術家の宿命というものだからね。それにファンに囲まれるのは慣れているから問題ないよ」
line = "「ふふっ……それが天才藝術家の宿命というものだからね。それにファンに囲まれるのは慣れているから問題ないよ」"

[[dialogue]]
speaker = "ラファエロ"
# 「……ステラは、人と接するのが苦手なのかい？」
line = "「……ステラは、人と接するのが苦手なのかい？」"

[[dialogue]]
speaker = "ステラ"
# 「……苦手、です」
line = "「……苦手、です」"

[[dialogue]]
speaker = "ラファエロ"
# 「もしよかったら、理由を聞いてもいいかな？」
line = "「もしよかったら、理由を聞いてもいいかな？」"

[[dialogue]]
speaker = "ステラ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ステラ"
# 「<ruby=フラワーナイト>花騎士</ruby>として開花したボクの能力というのが……自身が光を放ったり、触れたものを光らせたりする能力、なんです……」
line = "「<ruby>花騎士<rt>フラワーナイト</rt></ruby>として開花したボクの能力というのが……自身が光を放ったり、触れたものを光らせたりする能力、なんです……」"

[[dialogue]]
speaker = "ステラ"
# 「能力に目覚めたばかりの頃は、上手くコントロールできなくて……それで周りの人たちの注目を、変に集めてしまうことがあって……」
line = "「能力に目覚めたばかりの頃は、上手くコントロールできなくて……それで周りの人たちの注目を、変に集めてしまうことがあって……」"

[[dialogue]]
speaker = "ステラ"
# 「悪目立ちしてからかわれたりしないように、って人と接するのを避けていたら……いつの間にか苦手になってしまってて……」
line = "「悪目立ちしてからかわれたりしないように、って人と接するのを避けていたら……いつの間にか苦手になってしまってて……」"

[[dialogue]]
speaker = "ステラ"
# 「自分の力を嫌だなって思ってた時期もありました。でも今は、この力のおかげで大切な人を守ることができるから、そこはよかったなって思えるようになりました」
line = "「自分の力を嫌だなって思ってた時期もありました。でも今は、この力のおかげで大切な人を守ることができるから、そこはよかったなって思えるようになりました」"

[[dialogue]]
speaker = "ステラ"
# 「それでも、やっぱり人前に出て話をしたりするのは苦手で……。だからラファエロさんは、すごいなって思います……」
line = "「それでも、やっぱり人前に出て話をしたりするのは苦手で……。だからラファエロさんは、すごいなって思います……」"

[[dialogue]]
speaker = "ラファエロ"
# 「そんなに持ち上げるほどのことでもないよ。でもきみがそう思うなら、ぼくの立ち振る舞いを参考にしてみるといいかもしれない」
line = "「そんなに持ち上げるほどのことでもないよ。でもきみがそう思うなら、ぼくの立ち振る舞いを参考にしてみるといいかもしれない」"

[[dialogue]]
speaker = "ラファエロ"
# 「だけど、きみの姿勢も十分に立派だと思うよ。きちんと自身の力と向き合って、折り合いをつけようとしているじゃないか」
line = "「だけど、きみの姿勢も十分に立派だと思うよ。きちんと自身の力と向き合って、折り合いをつけようとしているじゃないか」"

[[dialogue]]
speaker = "ステラ"
# 「そうですか？　えへへ……褒められると、嬉しくなっちゃいますね」
line = "「そうですか？　えへへ……褒められると、嬉しくなっちゃいますね」"

[[dialogue]]
speaker = "ルリエル"
# 「おじゃましま～す♪　今日も赤ちゃんクマロボさんの様子を見に来たのです！」
line = "「おじゃましま～す♪　今日も赤ちゃんクマロボさんの様子を見に来たのです！」"

[[dialogue]]
speaker = "ステラ"
# 「あ……ルリエルさん。お、おはようございます」
line = "「あ……ルリエルさん。お、おはようございます」"

[[dialogue]]
speaker = "ルリエル"
# 「どうですか、赤ちゃんクマロボさんの様子は？」
line = "「どうですか、赤ちゃんクマロボさんの様子は？」"

[[dialogue]]
speaker = "ステラ"
# 「はい、とってもいい子にしてますよ」
line = "「はい、とってもいい子にしてますよ」"

[[dialogue]]
speaker = "赤ちゃんクマロボ"
# 「ばぶー<emoji=heart04>」
line = "「ばぶー<emoji=heart04>」"

[[dialogue]]
speaker = "ルリエル"
# 「そうですか～。いい子にしていて偉いでちゅね～<emoji=heart04>」
line = "「そうですか～。いい子にしていて偉いでちゅね～<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# ルリエルはすっかりこの子にメロメロだな
line = "ルリエルはすっかりこの子にメロメロだな"

[[dialogue]]
speaker = "ルリエル"
# 「だってだって、すっごく可愛いじゃないですかぁ～！！」
line = "「だってだって、すっごく可愛いじゃないですかぁ～！！」"

[[dialogue]]
speaker = "ルリエル"
# 「ルリエルも母性に目覚めちゃったのかもしれません。この子の為だったら、『なんだってしてあげたい』って気持ちになっちゃいます！！」
line = "「ルリエルも母性に目覚めちゃったのかもしれません。この子の為だったら、『なんだってしてあげたい』って気持ちになっちゃいます！！」"

[[dialogue]]
speaker = "ステラ"
# 「わ、わかります！　もう可愛くて可愛くて仕方なくて……最近は寝ても覚めてもこの子のことばかり考えてしまうんです」
line = "「わ、わかります！　もう可愛くて可愛くて仕方なくて……最近は寝ても覚めてもこの子のことばかり考えてしまうんです」"

[[dialogue]]
speaker = "ラファエロ"
# 「ステラほどではないが、ぼくもこの子の可愛さについては認めるよ」
line = "「ステラほどではないが、ぼくもこの子の可愛さについては認めるよ」"

[[dialogue]]
speaker = "ラファエロ"
# 「そういえばステラ、さっきからずっと抱っこしていて疲れただろう？　そろそろぼくが代わろうか。なに、遠慮はいらないよ」
line = "「そういえばステラ、さっきからずっと抱っこしていて疲れただろう？　そろそろぼくが代わろうか。なに、遠慮はいらないよ」"

[[dialogue]]
speaker = "ルリエル"
# 「待ってください！　授業だったり星徒会の仕事だったりで一緒に居られる時間が少ないんですから、先にわたしに抱っこさせてくださいよ～」
line = "「待ってください！　授業だったり星徒会の仕事だったりで一緒に居られる時間が少ないんですから、先にわたしに抱っこさせてくださいよ～」"

[[dialogue]]
speaker = "unk"
# ３人は代わる代わる赤ちゃんクマロボを抱っこしてあやしている。
line = "３人は代わる代わる赤ちゃんクマロボを抱っこしてあやしている。"

[[dialogue]]
speaker = "unk"
# 親身になって面倒を見てくれるのは助かるのだが、この調子だと別れの時に辛くなるんじゃないだろうか？
line = "親身になって面倒を見てくれるのは助かるのだが、この調子だと別れの時に辛くなるんじゃないだろうか？"

[[dialogue]]
speaker = "unk"
# 赤ちゃんクマロボに夢中な３人の様子を見ていると、そんな心配さえ感じてしまうのだった。
line = "赤ちゃんクマロボに夢中な３人の様子を見ていると、そんな心配さえ感じてしまうのだった。"
