[[dialogue]]
speaker = "ルリエル"
# 「今起きてる事件の犯人が赤ちゃんクマロボさんなら、狙われそうなのはやっぱりここなのです！」
line = "「今起きてる事件の犯人が赤ちゃんクマロボさんなら、狙われそうなのはやっぱりここなのです！」"

[[dialogue]]
speaker = "蛍火"
# 「師匠……！　いいところに来てくれました」
line = "「師匠……！　いいところに来てくれました」"

[[dialogue]]
speaker = "unk"
# 実は赤ちゃんクマロボが……
line = "実は赤ちゃんクマロボが……"

[[dialogue]]
speaker = "unk"
# 蛍火！
line = "蛍火！"

[[dialogue]]
speaker = "蛍火"
# 「そうなんです。どうなってるんでしょうか、これは……」
line = "「そうなんです。どうなってるんでしょうか、これは……」"

[[dialogue]]
speaker = "ルリエル"
# 「わわわ……！！」
line = "「わわわ……！！」"

[[dialogue]]
speaker = "unk"
# カフェテリアの中は大惨事になっていた。
line = "カフェテリアの中は大惨事になっていた。"

[[dialogue]]
speaker = "unk"
# 大量の赤ちゃんクマロボ。それこそ３匹どころではなく、数えきれないほど……
line = "大量の赤ちゃんクマロボ。それこそ３匹どころではなく、数えきれないほど……"

[[dialogue]]
speaker = "unk"
# その赤ちゃんクマロボたちがあちこちで、色んなものを食い荒らしている。
line = "その赤ちゃんクマロボたちがあちこちで、色んなものを食い荒らしている。"

[[dialogue]]
speaker = "蛍火"
# 「あの子たち、食べ物だけじゃなくて、何でも食べてしまうんです……」
line = "「あの子たち、食べ物だけじゃなくて、何でも食べてしまうんです……」"

[[dialogue]]
speaker = "unk"
# 迷惑かけちゃってごめん！
line = "迷惑かけちゃってごめん！"

[[dialogue]]
speaker = "蛍火"
# 「いえ、赤ちゃんのすることですから……ただそれより、何でも食べてしまうからお腹を壊してしまわないかな、と」
line = "「いえ、赤ちゃんのすることですから……ただそれより、何でも食べてしまうからお腹を壊してしまわないかな、と」"

[[dialogue]]
speaker = "unk"
# しっかりして、蛍火！
line = "しっかりして、蛍火！"

[[dialogue]]
speaker = "unk"
# そんな心配してる場合じゃない！
line = "そんな心配してる場合じゃない！"

[[dialogue]]
speaker = "ルリエル"
# 「そうですよ！　この数といい、なんでも食べちゃうところといい、この子たち普通じゃありません！」
line = "「そうですよ！　この数といい、なんでも食べちゃうところといい、この子たち普通じゃありません！」"

[[dialogue]]
speaker = "蛍火"
# 「！　……言われてみれば、その通りです」
line = "「！　……言われてみれば、その通りです」"

[[dialogue]]
speaker = "ラファエロ"
# 「ふぅ……正気に戻ってくれたみたいだね」
line = "「ふぅ……正気に戻ってくれたみたいだね」"

[[dialogue]]
speaker = "ルリエル"
# 「とりあえず片っ端から捕まえましょう！」
line = "「とりあえず片っ端から捕まえましょう！」"

[[dialogue]]
speaker = "赤ちゃんクマロボ"
# 「ばぶー<emoji=heart04>」
line = "「ばぶー<emoji=heart04>」"

[[dialogue]]
speaker = "ルリエル"
# 「あっ、逃げた！　待ちなさーいっ！！！」
line = "「あっ、逃げた！　待ちなさーいっ！！！」"

[[dialogue]]
speaker = "アニマ"
# 「フヒ……誰かと思えば会長じゃないカ」
line = "「フヒ……誰かと思えば会長じゃないカ」"

[[dialogue]]
speaker = "ルリエル"
# 「アニマ先輩！」
line = "「アニマ先輩！」"

[[dialogue]]
speaker = "アニマ"
# 「如何にも、購買部の美少女看板娘にして天才錬金術師のアニマ先輩ダ」
line = "「如何にも、購買部の美少女看板娘にして天才錬金術師のアニマ先輩ダ」"

[[dialogue]]
speaker = "ルリエル"
# 「購買部も赤ちゃんクマロボさんに荒らされちゃってます～……ご愁傷様なのです」
line = "「購買部も赤ちゃんクマロボさんに荒らされちゃってます～……ご愁傷様なのです」"

[[dialogue]]
speaker = "アニマ"
# 「この実に興味深い生き物は、赤ちゃんクマロボというのカ？」
line = "「この実に興味深い生き物は、赤ちゃんクマロボというのカ？」"

[[dialogue]]
speaker = "アニマ"
# 「先ほどから大量発生してお店の物を食い荒らしているので、その生態について観察していたところダ」
line = "「先ほどから大量発生してお店の物を食い荒らしているので、その生態について観察していたところダ」"

[[dialogue]]
speaker = "ルリエル"
# 「か、観察ですか……？」
line = "「か、観察ですか……？」"

[[dialogue]]
speaker = "アニマ"
# 「今はいろんな物を食べさせて、その様子を観察しているところダ。近くのものを何でも手当たり次第に食べてしまうようだからナ」
line = "「今はいろんな物を食べさせて、その様子を観察しているところダ。近くのものを何でも手当たり次第に食べてしまうようだからナ」"

[[dialogue]]
speaker = "アニマ"
# 「では次は、アニマの開発した薬品を与えてみよう♪　まずは全身の細胞を活性化させ、筋力を大幅に向上させる薬ヲ……」
line = "「では次は、アニマの開発した薬品を与えてみよう♪　まずは全身の細胞を活性化させ、筋力を大幅に向上させる薬ヲ……」"

[[dialogue]]
speaker = "unk"
# そんなもの与えないでください！
line = "そんなもの与えないでください！"

[[dialogue]]
speaker = "unk"
# ストーーーップ！！
line = "ストーーーップ！！"

[[dialogue]]
speaker = "アニマ"
# 「会長？　何故、止めるのカナ？」
line = "「会長？　何故、止めるのカナ？」"

[[dialogue]]
speaker = "ルリエル"
# 「赤ちゃんクマロボさんがムキムキになって、手に負えなくなっちゃったらどうするんですか～！」
line = "「赤ちゃんクマロボさんがムキムキになって、手に負えなくなっちゃったらどうするんですか～！」"

[[dialogue]]
speaker = "アニマ"
# 「フム……それはそれで興味深いナ？」
line = "「フム……それはそれで興味深いナ？」"

[[dialogue]]
speaker = "ステラ"
# 「会長さん……もしかしたらこの方も、赤ちゃんクマロボさんの魅了の影響を受けているのでは……？」
line = "「会長さん……もしかしたらこの方も、赤ちゃんクマロボさんの魅了の影響を受けているのでは……？」"

[[dialogue]]
speaker = "unk"
# 判断が難しい。アニマ先輩はオールウェイズこういうところがある……
line = "判断が難しい。アニマ先輩はオールウェイズこういうところがある……"

[[dialogue]]
speaker = "ルリエル"
# 「アニマ先輩、しっかりしてくださーい！　実はこの子たちは──！」
line = "「アニマ先輩、しっかりしてくださーい！　実はこの子たちは──！」"

[[dialogue]]
speaker = "unk"
# 俺たちは急いで、なるべく手短にアニマ先輩へこれまでの経緯を説明した。
line = "俺たちは急いで、なるべく手短にアニマ先輩へこれまでの経緯を説明した。"

[[dialogue]]
speaker = "アニマ"
# 「フヒッ……妙に興味をそそられると思っていたガ、この生き物はそういう特性を持っているのカ！　ますます興味深いナ！！」
line = "「フヒッ……妙に興味をそそられると思っていたガ、この生き物はそういう特性を持っているのカ！　ますます興味深いナ！！」"

[[dialogue]]
speaker = "ルリエル"
# 「ひ～んっ。喜んでないで手伝ってくださ～い！」
line = "「ひ～んっ。喜んでないで手伝ってくださ～い！」"

[[dialogue]]
speaker = "アニマ"
# 「全員を捕まえなければならないのカ？　だとすると、この数はなかなか大変だゾ？」
line = "「全員を捕まえなければならないのカ？　だとすると、この数はなかなか大変だゾ？」"

[[dialogue]]
speaker = "unk"
# アニマ先輩の指摘通り、正体を現した赤ちゃんクマロボはモノを食べた端から増殖しており、もはや視界に映るだけでも数十匹。全部で何体になるのかは想像したくもない。
line = "アニマ先輩の指摘通り、正体を現した赤ちゃんクマロボはモノを食べた端から増殖しており、もはや視界に映るだけでも数十匹。全部で何体になるのかは想像したくもない。"

[[dialogue]]
speaker = "ルリエル"
# 「きゅぴーん！　ルリエル、閃きました！」
line = "「きゅぴーん！　ルリエル、閃きました！」"

[[dialogue]]
speaker = "ステラ"
# 「さ、さすがルリエルさんです！　どんな方法ですか！？」
line = "「さ、さすがルリエルさんです！　どんな方法ですか！？」"

[[dialogue]]
speaker = "ルリエル"
# 「相手が赤ちゃんなら、対抗手段はこれしかありません！　ふふふ、少々お待ちください、強力な援軍を呼びますから！」
line = "「相手が赤ちゃんなら、対抗手段はこれしかありません！　ふふふ、少々お待ちください、強力な援軍を呼びますから！」"

[[dialogue]]
speaker = "unk"
# ルリエルはＤＩＳＣを取り出すと、どこかに連絡をかけ始める。
line = "ルリエルはＤＩＳＣを取り出すと、どこかに連絡をかけ始める。"

[[dialogue]]
speaker = "unk"
# そして──
line = "そして──"

[[dialogue]]
speaker = "セシア"
# 「お待たせよ！」
line = "「お待たせよ！」"

[[dialogue]]
speaker = "unk"
# このメンバーは……！
line = "このメンバーは……！"

[[dialogue]]
speaker = "ルリエル"
# 「捕まえようにも捕まえきれない！　それならば、向こうから来るように仕向ければいいのです！」
line = "「捕まえようにも捕まえきれない！　それならば、向こうから来るように仕向ければいいのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「セシアさんにママ力の高いメンバーを集めてもらいました。名付けて『赤ちゃんホイホイ大作戦』なのです！」
line = "「セシアさんにママ力の高いメンバーを集めてもらいました。名付けて『赤ちゃんホイホイ大作戦』なのです！」"

[[dialogue]]
speaker = "セシア"
# 「わたくしの考える、ベストママセレクション５人を用意したわ！」
line = "「わたくしの考える、ベストママセレクション５人を用意したわ！」"

[[dialogue]]
speaker = "ルリエル"
# 「素晴らしいセレクションなのです♪」
line = "「素晴らしいセレクションなのです♪」"

[[dialogue]]
speaker = "ルリエル"
# 「あれ？　マグダレナさん、リノさん、紅明さん、モネさん……４人しか居なくありませんか？」
line = "「あれ？　マグダレナさん、リノさん、紅明さん、モネさん……４人しか居なくありませんか？」"

[[dialogue]]
speaker = "ルリエル"
# 「あ、わかりました！　最後の１人はズバリ、セシアさんご自身なのです！」
line = "「あ、わかりました！　最後の１人はズバリ、セシアさんご自身なのです！」"

[[dialogue]]
speaker = "セシア"
# 「もちろん違うわ！！」
line = "「もちろん違うわ！！」"

[[dialogue]]
speaker = "ルリエル"
# 「違ったのですぅ……」
line = "「違ったのですぅ……」"

[[dialogue]]
speaker = "セシア"
# 「最後の１人は、クロトママよ！」
line = "「最後の１人は、クロトママよ！」"

[[dialogue]]
speaker = "unk"
# 俺をママカウントしないで……
line = "俺をママカウントしないで……"

[[dialogue]]
speaker = "セシア"
# 「さあ、会長？　早く女の子になって、あふれる母性を解放してちょうだい！」
line = "「さあ、会長？　早く女の子になって、あふれる母性を解放してちょうだい！」"

[[dialogue]]
speaker = "ステラ"
# 「会長さん……女の子になれるんですか？」
line = "「会長さん……女の子になれるんですか？」"

[[dialogue]]
speaker = "ラファエロ"
# 「それとも女装が趣味なのかい？　ああいや、構わないよ。どんな趣味でも個人の自由だからね」
line = "「それとも女装が趣味なのかい？　ああいや、構わないよ。どんな趣味でも個人の自由だからね」"

[[dialogue]]
speaker = "unk"
# ちがーーーうっ！
line = "ちがーーーうっ！"

[[dialogue]]
speaker = "unk"
# この世界にはアバターというものが存在していて、性別の違うアバターに入ったことがあるだけだ。
line = "この世界にはアバターというものが存在していて、性別の違うアバターに入ったことがあるだけだ。"

[[dialogue]]
speaker = "unk"
# それもやむにやまれぬ事情があって、期間限定で女の子になってただけで……と必死で説明する。
line = "それもやむにやまれぬ事情があって、期間限定で女の子になってただけで……と必死で説明する。"

[[dialogue]]
speaker = "unk"
# 今はママになれないよ
line = "今はママになれないよ"

[[dialogue]]
speaker = "unk"
# 急に言われてもアバターが無いから
line = "急に言われてもアバターが無いから"

[[dialogue]]
speaker = "アニマ"
# 「無理じゃナイぞ？　女体化薬が必要なら、いつでも言ッテくれ♪　フヒッ」
line = "「無理じゃナイぞ？　女体化薬が必要なら、いつでも言ッテくれ♪　フヒッ」"

[[dialogue]]
speaker = "セシア"
# 「だそうよ、クロトママ♪」
line = "「だそうよ、クロトママ♪」"

[[dialogue]]
speaker = "unk"
# しまった！　アニマ先輩が近くに居たんだった！
line = "しまった！　アニマ先輩が近くに居たんだった！"

[[dialogue]]
speaker = "unk"
# 今は捕まえることを優先しよう
line = "今は捕まえることを優先しよう"

[[dialogue]]
speaker = "unk"
# ４人いれば十分だ！
line = "４人いれば十分だ！"

[[dialogue]]
speaker = "セシア"
# 「えー、久しぶりにクロトママ成分を摂取したかったのに……」
line = "「えー、久しぶりにクロトママ成分を摂取したかったのに……」"

[[dialogue]]
speaker = "セシア"
# 「仕方ないわ！　ママ、みんなで頑張って赤ちゃんクマロボを捕まえましょう！」
line = "「仕方ないわ！　ママ、みんなで頑張って赤ちゃんクマロボを捕まえましょう！」"

[[dialogue]]
speaker = "unk"
# セシアの号令で、ママたちはそれぞれのママ属性を活かしながら赤ちゃんクマロボを捕まえていく。
line = "セシアの号令で、ママたちはそれぞれのママ属性を活かしながら赤ちゃんクマロボを捕まえていく。"

[[dialogue]]
speaker = "unk"
# 強烈なママ力に引き寄せられたのか、わらわらと赤ちゃんクマロボたちが姿を現す。
line = "強烈なママ力に引き寄せられたのか、わらわらと赤ちゃんクマロボたちが姿を現す。"

[[dialogue]]
speaker = "unk"
# ママ軍団の活躍もあって、俺たちは赤ちゃんクマロボたちをすごい勢いで捕まえていったのだった。
line = "ママ軍団の活躍もあって、俺たちは赤ちゃんクマロボたちをすごい勢いで捕まえていったのだった。"
