[[dialogue]]
speaker = "unk"
# アナとシュティレが飲み込まれたアステライトの内部では、ギガンドムが呼び出した大量の機械型モンスターがひしめいていた──
line = "アナとシュティレが飲み込まれたアステライトの内部では、ギガンドムが呼び出した大量の機械型モンスターがひしめいていた──"

[[dialogue]]
speaker = "アナ"
# 「レッドデルタ──シュート！」
line = "「レッドデルタ──シュート！」"

[[dialogue]]
speaker = "モンスター"
# 「──ガァアアッ！」
line = "「──ガァアアッ！」"

[[dialogue]]
speaker = "unk"
# アナはひたすらに矢をつがえ、近くのモンスターを射抜き続ける。
line = "アナはひたすらに矢をつがえ、近くのモンスターを射抜き続ける。"

[[dialogue]]
speaker = "unk"
# 捌ききれず接近を許した時は、攻撃を受けるしかない。元から弓兵は狙撃が専門。接近戦などできない。
line = "捌ききれず接近を許した時は、攻撃を受けるしかない。元から弓兵は狙撃が専門。接近戦などできない。"

[[dialogue]]
speaker = "unk"
# だから機械型モンスターの鉄拳は、気合いで受けきる。むしろ攻撃に寄って吹き飛ばされれば距離が取れる──そうなれば弓兵の自分が有利だ。
line = "だから機械型モンスターの鉄拳は、気合いで受けきる。むしろ攻撃に寄って吹き飛ばされれば距離が取れる──そうなれば弓兵の自分が有利だ。"

[[dialogue]]
speaker = "unk"
# アナは火星とのリンクを最大まで開いて星力を練り続け、重傷を負った後輩を守りながら、大量の機械型モンスターを捌き続けていた。
line = "アナは火星とのリンクを最大まで開いて星力を練り続け、重傷を負った後輩を守りながら、大量の機械型モンスターを捌き続けていた。"

[[dialogue]]
speaker = "アナ"
# 「はぁっ……はっ──う、げほっ……！　ま、まだ……お願い……マルス……力を貸して……」
line = "「はぁっ……はっ──う、げほっ……！　ま、まだ……お願い……マルス……力を貸して……」"

[[dialogue]]
speaker = "シュティレ"
# 「ぐっ……ア、アナお姉ちゃん……ダメです、それ以上、星力を使ったら……」
line = "「ぐっ……ア、アナお姉ちゃん……ダメです、それ以上、星力を使ったら……」"

[[dialogue]]
speaker = "アナ"
# 「シュティレさんこそ、私の後ろに隠れていてください……もう限界です。後は……私が何とかします」
line = "「シュティレさんこそ、私の後ろに隠れていてください……もう限界です。後は……私が何とかします」"

[[dialogue]]
speaker = "シュティレ"
# 「い、いけません……アナお姉ちゃん。本当に、し、死んでしまいます……逃げましょう……！」
line = "「い、いけません……アナお姉ちゃん。本当に、し、死んでしまいます……逃げましょう……！」"

[[dialogue]]
speaker = "アナ"
# 「無理です……こいつらは素早い。逃げても背中を撃たれるだけ……」
line = "「無理です……こいつらは素早い。逃げても背中を撃たれるだけ……」"

[[dialogue]]
speaker = "unk"
# 震える指先に力を込め、炎の矢を生み出す。
line = "震える指先に力を込め、炎の矢を生み出す。"

[[dialogue]]
speaker = "アナ"
# 「どれだけ分の悪い相手でも……退いたり、しません……」
line = "「どれだけ分の悪い相手でも……退いたり、しません……」"

[[dialogue]]
speaker = "unk"
# 目がかすんで的が見えない──ならば耳で音を聞いて、そこを撃つしかない。
line = "目がかすんで的が見えない──ならば耳で音を聞いて、そこを撃つしかない。"

[[dialogue]]
speaker = "アナ"
# 「星徒会の先輩方なら……きっと……最後まで戦う……後輩を守り切る……！」
line = "「星徒会の先輩方なら……きっと……最後まで戦う……後輩を守り切る……！」"

[[dialogue]]
speaker = "アナ"
# 「どこからでも、来い……！　私は、諦めたりなんか、しません……！！」
line = "「どこからでも、来い……！　私は、諦めたりなんか、しません……！！」"

[[dialogue]]
speaker = "unk"
# ──最期の時は、確実に近づいていた。
line = "──最期の時は、確実に近づいていた。"

[[dialogue]]
speaker = "unk"
# 同刻──外の戦いも決着しつつあった。
line = "同刻──外の戦いも決着しつつあった。"

[[dialogue]]
speaker = "アニマ"
# 「し、しまったナ……久しぶりだゾ、こんな窮地は……ぐゥ……！」
line = "「し、しまったナ……久しぶりだゾ、こんな窮地は……ぐゥ……！」"

[[dialogue]]
speaker = "アニマ"
# 「それに……クソ。弱体化薬、ラスト１個、だったの二……！」
line = "「それに……クソ。弱体化薬、ラスト１個、だったの二……！」"

[[dialogue]]
speaker = "unk"
# アステラによる分断に成功したギガンドムは、アニマへの攻撃を執拗に繰り返していた。
line = "アステラによる分断に成功したギガンドムは、アニマへの攻撃を執拗に繰り返していた。"

[[dialogue]]
speaker = "unk"
# 彼女の持つモンスター弱体化薬。それを脅威と感じているのは、ギガンドムの本能か。
line = "彼女の持つモンスター弱体化薬。それを脅威と感じているのは、ギガンドムの本能か。"

[[dialogue]]
speaker = "unk"
# モンスターは言葉を持たない。しかし、獣のように本能が発達しているのかもしれない。
line = "モンスターは言葉を持たない。しかし、獣のように本能が発達しているのかもしれない。"

[[dialogue]]
speaker = "アニマ"
# 「せっかくかばってくれているのに、会長、ごめんヨ……」
line = "「せっかくかばってくれているのに、会長、ごめんヨ……」"

[[dialogue]]
speaker = "unk"
# クロトの守護星は地球である。倒れ伏すたびに、その身に星力を宿す。
line = "クロトの守護星は地球である。倒れ伏すたびに、その身に星力を宿す。"

[[dialogue]]
speaker = "unk"
# アニマを守るために今もギガンドムに単身立ち向かい、打ち合っているが──明らかに分が悪い。
line = "アニマを守るために今もギガンドムに単身立ち向かい、打ち合っているが──明らかに分が悪い。"

[[dialogue]]
speaker = "アニマ"
# 「フヒ、限界は近イ……。応援はまだ、来ないのカ……？」
line = "「フヒ、限界は近イ……。応援はまだ、来ないのカ……？」"

[[dialogue]]
speaker = "アニマ"
# 「アナ……シュティレ……」
line = "「アナ……シュティレ……」"

[[dialogue]]
speaker = "unk"
# ギガンドムが発生させたアステライト。その内部では、地上と同じくらいに激化した戦闘が繰り広げられているはず。
line = "ギガンドムが発生させたアステライト。その内部では、地上と同じくらいに激化した戦闘が繰り広げられているはず。"

[[dialogue]]
speaker = "unk"
# 後輩たちは、まだ生きているだろうか──？
line = "後輩たちは、まだ生きているだろうか──？"

[[dialogue]]
speaker = "アナ"
# 『はぁっ……はーっ……！　よし、１体、撃破っ……ま、まだっ……うぐっ──！』
line = "『はぁっ……はーっ……！　よし、１体、撃破っ……ま、まだっ……うぐっ──！』"

[[dialogue]]
speaker = "アニマ"
# 「ン……？　なんダ、今、声ガ……？」
line = "「ン……？　なんダ、今、声ガ……？」"

[[dialogue]]
speaker = "シュティレ"
# 『アナお姉ちゃん……！　ダメです、それ以上は……血が、血が止まっていないのに……！』
line = "『アナお姉ちゃん……！　ダメです、それ以上は……血が、血が止まっていないのに……！』"

[[dialogue]]
speaker = "アニマ"
# 「……学園でシュティレと繋いだＤＩＳＣの通話……つなげたまま、だったナ……」
line = "「……学園でシュティレと繋いだＤＩＳＣの通話……つなげたまま、だったナ……」"

[[dialogue]]
speaker = "unk"
# アニマの懐にあるＤＩＳＣ。通話口から聞こえてくるのは、今にも息絶えそうなアナとシュティレの会話だった。
line = "アニマの懐にあるＤＩＳＣ。通話口から聞こえてくるのは、今にも息絶えそうなアナとシュティレの会話だった。"

[[dialogue]]
speaker = "アナ"
# 『はぁ……ふぅ……シュティレさん……先ほどの会話の、続き、なんですけど……』
line = "『はぁ……ふぅ……シュティレさん……先ほどの会話の、続き、なんですけど……』"

[[dialogue]]
speaker = "シュティレ"
# 『な、何を……今、そんなこと……！』
line = "『な、何を……今、そんなこと……！』"

[[dialogue]]
speaker = "アナ"
# 『──巨大ロボットを作るのが夢、と言っていましたよね』
line = "『──巨大ロボットを作るのが夢、と言っていましたよね』"

[[dialogue]]
speaker = "アナ"
# 『そんな夢を持つ女の子をどう思うのかと、気にしていましたよね……』
line = "『そんな夢を持つ女の子をどう思うのかと、気にしていましたよね……』"

[[dialogue]]
speaker = "アニマ"
# 「何だっテ……？　シュティレの、夢……？」
line = "「何だっテ……？　シュティレの、夢……？」"

[[dialogue]]
speaker = "unk"
# アニマは、か細く聴こえる通話に、耳を澄ませる──
line = "アニマは、か細く聴こえる通話に、耳を澄ませる──"

[[dialogue]]
speaker = "アナ"
# 「私は素敵な夢だと、思いますよ……ロボットの制作。いいじゃないですか。とても……ロマンが、あります……」
line = "「私は素敵な夢だと、思いますよ……ロボットの制作。いいじゃないですか。とても……ロマンが、あります……」"

[[dialogue]]
speaker = "アナ"
# 「そしてようやく繋がりました……シュティレさんの望む巨大ロボットは、おそらく……機械技術だけでは、作れない。違いますか？」
line = "「そしてようやく繋がりました……シュティレさんの望む巨大ロボットは、おそらく……機械技術だけでは、作れない。違いますか？」"

[[dialogue]]
speaker = "アナ"
# 「錬金術の奇蹟を借りなければ製造すらできないような、アニメに出てくるような巨大ロボットが……作りたいんじゃないですか……？」
line = "「錬金術の奇蹟を借りなければ製造すらできないような、アニメに出てくるような巨大ロボットが……作りたいんじゃないですか……？」"

[[dialogue]]
speaker = "シュティレ"
# 「……そう、です」
line = "「……そう、です」"

[[dialogue]]
speaker = "シュティレ"
# 「私の目標は……小さい頃からの夢は……ファイナルフォームギガンドムのような、スーパーロボットを、作ることで……」
line = "「私の目標は……小さい頃からの夢は……ファイナルフォームギガンドムのような、スーパーロボットを、作ることで……」"

[[dialogue]]
speaker = "アナ"
# 「知らない形態のギガンドム、ですね……」
line = "「知らない形態のギガンドム、ですね……」"

[[dialogue]]
speaker = "シュティレ"
# 「はい。エネルギーは自身の体内で生成する永久機関のため、無尽蔵で……」
line = "「はい。エネルギーは自身の体内で生成する永久機関のため、無尽蔵で……」"

[[dialogue]]
speaker = "シュティレ"
# 「陸海空だけでなく、宇宙空間でも活動可能で……」
line = "「陸海空だけでなく、宇宙空間でも活動可能で……」"

[[dialogue]]
speaker = "シュティレ"
# 「腕が無限に伸びて敵を追跡する、ロケットブースターパンチも搭載していて……」
line = "「腕が無限に伸びて敵を追跡する、ロケットブースターパンチも搭載していて……」"

[[dialogue]]
speaker = "シュティレ"
# 「一兆度もあるウルトラビームを何発でも撃てるんです……」
line = "「一兆度もあるウルトラビームを何発でも撃てるんです……」"

[[dialogue]]
speaker = "アナ"
# 「ふふ……なるほど……それは確かに無理です。機械技術だけでは絶対に無理……錬金術が、必要ですね……」
line = "「ふふ……なるほど……それは確かに無理です。機械技術だけでは絶対に無理……錬金術が、必要ですね……」"

[[dialogue]]
speaker = "シュティレ"
# 「はい……流星附属に入学してしばらくしたある日……併設されている新星学園に、奇蹟を手中に収めた天才錬金術師がいる、と聞きました……」
line = "「はい……流星附属に入学してしばらくしたある日……併設されている新星学園に、奇蹟を手中に収めた天才錬金術師がいる、と聞きました……」"

[[dialogue]]
speaker = "シュティレ"
# 「アニマ先輩の錬金術を見て、衝撃を受けました。会長が女の子になったりしてて……」
line = "「アニマ先輩の錬金術を見て、衝撃を受けました。会長が女の子になったりしてて……」"

[[dialogue]]
speaker = "アナ"
# 「物理の法則を飛び越えてますからね、あの人のやることは……」
line = "「物理の法則を飛び越えてますからね、あの人のやることは……」"

[[dialogue]]
speaker = "シュティレ"
# 「でも、正直に言えませんでした……どうして錬金術を学びたいんだと聞かれた時、ロボットが作りたいとは、言えませんでした……」
line = "「でも、正直に言えませんでした……どうして錬金術を学びたいんだと聞かれた時、ロボットが作りたいとは、言えませんでした……」"

[[dialogue]]
speaker = "アナ"
# 「……どうして、ですか？」
line = "「……どうして、ですか？」"

[[dialogue]]
speaker = "シュティレ"
# 「馬鹿らしい夢だと、自覚しています。小さい頃から、何度も周りから笑われてきたから」
line = "「馬鹿らしい夢だと、自覚しています。小さい頃から、何度も周りから笑われてきたから」"

[[dialogue]]
speaker = "シュティレ"
# 「他人から見たらくだらないものだということくらい、分かってるんです。だから……」
line = "「他人から見たらくだらないものだということくらい、分かってるんです。だから……」"

[[dialogue]]
speaker = "シュティレ"
# 「くだらないものを作るために錬金術を使うなと、そう言われたらと思うと……」
line = "「くだらないものを作るために錬金術を使うなと、そう言われたらと思うと……」"

[[dialogue]]
speaker = "アナ"
# 「そんなことありませんよ。アニマ先輩は笑いません」
line = "「そんなことありませんよ。アニマ先輩は笑いません」"

[[dialogue]]
speaker = "アナ"
# 「そこに確かな熱があれば。ロマンがあれば……あの人は、どんな馬鹿らしいことでも笑ったりしません」
line = "「そこに確かな熱があれば。ロマンがあれば……あの人は、どんな馬鹿らしいことでも笑ったりしません」"

[[dialogue]]
speaker = "アナ"
# 「あの人ほど、ロマンの中で生きている人はいないんですから」
line = "「あの人ほど、ロマンの中で生きている人はいないんですから」"

[[dialogue]]
speaker = "シュティレ"
# 「アナお姉ちゃん……」
line = "「アナお姉ちゃん……」"

[[dialogue]]
speaker = "アナ"
# 「任せてください。私が絶対に、あなたの夢を守って──く、ぅっ……！」
line = "「任せてください。私が絶対に、あなたの夢を守って──く、ぅっ……！」"

[[dialogue]]
speaker = "モンスター"
# 「──グァアァッ！！」
line = "「──グァアァッ！！」"

[[dialogue]]
speaker = "unk"
# 突然、通話が途切れた。おそらく、敵の攻撃によってシュティレのＤＩＳＣが破壊されたのだ。
line = "突然、通話が途切れた。おそらく、敵の攻撃によってシュティレのＤＩＳＣが破壊されたのだ。"

[[dialogue]]
speaker = "アニマ"
# 「……もっと、ちゃんと聞いておくべきだったナ」
line = "「……もっと、ちゃんと聞いておくべきだったナ」"

[[dialogue]]
speaker = "アニマ"
# 「シュティレ……キミも、アニマと同じダ。狂っていル……！」
line = "「シュティレ……キミも、アニマと同じダ。狂っていル……！」"

[[dialogue]]
speaker = "アニマ"
# 「フヒ♪　死に際で語る夢が、一兆度のウルトラビームを無限発射とは……これを狂気と呼ばずに、なんと呼ブ！」
line = "「フヒ♪　死に際で語る夢が、一兆度のウルトラビームを無限発射とは……これを狂気と呼ばずに、なんと呼ブ！」"

[[dialogue]]
speaker = "アニマ"
# 「そうカ。錬金術でないと作れない巨大ロボット……アニマにロボットのことはよくわからないガ……」
line = "「そうカ。錬金術でないと作れない巨大ロボット……アニマにロボットのことはよくわからないガ……」"

[[dialogue]]
speaker = "unk"
# 熱いモチベーション。狂気の炎。身を焦がすような好奇心──それらをひっくるめてアニマは『ロマン』と定義する。
line = "熱いモチベーション。狂気の炎。身を焦がすような好奇心──それらをひっくるめてアニマは『ロマン』と定義する。"

[[dialogue]]
speaker = "アニマ"
# 「ロマンならばわかるゾ……シュティレ！　キミも！　アニマと同類だったのだナ！！」
line = "「ロマンならばわかるゾ……シュティレ！　キミも！　アニマと同類だったのだナ！！」"

[[dialogue]]
speaker = "アニマ"
# 「つまりダ！　今アニマは、ロマンを抱く将来有望な……錬金術師の卵を、失おうとしているわけダ！！」
line = "「つまりダ！　今アニマは、ロマンを抱く将来有望な……錬金術師の卵を、失おうとしているわけダ！！」"

[[dialogue]]
speaker = "unk"
# ──救いたい。自分とは異なる、けれど熱く滾るロマンを抱く後輩を。
line = "──救いたい。自分とは異なる、けれど熱く滾るロマンを抱く後輩を。"

[[dialogue]]
speaker = "アニマ"
# 「……認められなイ！」
line = "「……認められなイ！」"

[[dialogue]]
speaker = "unk"
# ──<ruby=たお>斃</ruby>したい。この世界に灯る情熱の火を消そうとする、あの無粋な機械の人形を。
line = "──<ruby>斃<rt>たお</rt></ruby>したい。この世界に灯る情熱の火を消そうとする、あの無粋な機械の人形を。"

[[dialogue]]
speaker = "アニマ"
# 「認められないゾ、そんなコト！！」
line = "「認められないゾ、そんなコト！！」"

[[dialogue]]
speaker = "アニマ"
# 「会長！　アニマに……このアニマに！　同志を救い出せる力を、寄越セ──！！」
line = "「会長！　アニマに……このアニマに！　同志を救い出せる力を、寄越セ──！！」"
