[[dialogue]]
speaker = "unk"
# ──アニマは、昔から何だって１人でできタ。
line = "──アニマは、昔から何だって１人でできタ。"

[[dialogue]]
speaker = "unk"
# 魔界の片田舎に生まれテ、若くして錬金術師の才能を見出され──その地で一番の天才術師の元に弟子入りをしタ。
line = "魔界の片田舎に生まれテ、若くして錬金術師の才能を見出され──その地で一番の天才術師の元に弟子入りをしタ。"

[[dialogue]]
speaker = "unk"
# けれどその師匠の元でも、６年程度で習うことがなくなっタ。行く先々で『天才だ』と持て囃されたものダ。
line = "けれどその師匠の元でも、６年程度で習うことがなくなっタ。行く先々で『天才だ』と持て囃されたものダ。"

[[dialogue]]
speaker = "unk"
# 他者の評価に興味はなイ。大切なのは、自分で自分を肯定できるコト。自分自身の在り方に納得し、生きて行けるかどうカ。
line = "他者の評価に興味はなイ。大切なのは、自分で自分を肯定できるコト。自分自身の在り方に納得し、生きて行けるかどうカ。"

[[dialogue]]
speaker = "unk"
# だがそんなアニマも、師匠が別れ際に贈ってくれた言葉は覚えていル──
line = "だがそんなアニマも、師匠が別れ際に贈ってくれた言葉は覚えていル──"

[[dialogue]]
speaker = "アニマの師"
# 「──お前は天才だ。だから、そのままでいい。他人を理解などしなくてもいい。好きなようにやれ」
line = "「──お前は天才だ。だから、そのままでいい。他人を理解などしなくてもいい。好きなようにやれ」"

[[dialogue]]
speaker = "アニマの師"
# 「だが、お前と同じ種類の……好奇心の狂人を見つけたなら、そいつとの繋がりは大事にしろ」
line = "「だが、お前と同じ種類の……好奇心の狂人を見つけたなら、そいつとの繋がりは大事にしろ」"

[[dialogue]]
speaker = "アニマの師"
# 「いいか。錬金術師は『ロマン』が全てだ。狂気の炎で身を焦がせ。自分とは違う、けれど同じ炎を持つ者がいたなら、そいつは傍に置くんだ」
line = "「いいか。錬金術師は『ロマン』が全てだ。狂気の炎で身を焦がせ。自分とは違う、けれど同じ炎を持つ者がいたなら、そいつは傍に置くんだ」"

[[dialogue]]
speaker = "アニマの師"
# 「他人の心の炎に影響を受けろ。そいつの炎は、お前にとっての薪となる」
line = "「他人の心の炎に影響を受けろ。そいつの炎は、お前にとっての薪となる」"

[[dialogue]]
speaker = "アニマの師"
# 「いかに天才と言えど、１人でたどり着ける頂きなどたかが知れている──お前がどんな奇人として歴史に名を遺すか、今から楽しみだよアニマ」
line = "「いかに天才と言えど、１人でたどり着ける頂きなどたかが知れている──お前がどんな奇人として歴史に名を遺すか、今から楽しみだよアニマ」"

[[dialogue]]
speaker = "unk"
# 師匠ヨ、今こそアニマは、あなたの言葉を心の底から理解するだろウ──
line = "師匠ヨ、今こそアニマは、あなたの言葉を心の底から理解するだろウ──"

[[dialogue]]
speaker = "unk"
# ──力を寄越せ。
line = "──力を寄越せ。"

[[dialogue]]
speaker = "unk"
# アニマ先輩らしからぬ力強い求めを聞いた俺は、痛む体に鞭打って彼女の元へ近づいた。
line = "アニマ先輩らしからぬ力強い求めを聞いた俺は、痛む体に鞭打って彼女の元へ近づいた。"

[[dialogue]]
speaker = "アニマ"
# 「会長。説明している暇が惜しイ──お前の魔王の力で、アニマの魂を覗いてみてくレ」
line = "「会長。説明している暇が惜しイ──お前の魔王の力で、アニマの魂を覗いてみてくレ」"

[[dialogue]]
speaker = "アニマ"
# 「今なら……行ける気がするんダ！」
line = "「今なら……行ける気がするんダ！」"

[[dialogue]]
speaker = "unk"
# 言われて気づく──見える。
line = "言われて気づく──見える。"

[[dialogue]]
speaker = "unk"
# アニマ先輩という存在の中に煌めく、覚醒の光を……！
line = "アニマ先輩という存在の中に煌めく、覚醒の光を……！"

[[dialogue]]
speaker = "アニマ"
# 「──フヒ♪　さぁ、ギガンドムが突っ込んできてるゾ！　アニマの準備は万全ダ！　魔王……頼ム！！」
line = "「──フヒ♪　さぁ、ギガンドムが突っ込んできてるゾ！　アニマの準備は万全ダ！　魔王……頼ム！！」"

[[dialogue]]
speaker = "unk"
# アルケインノヴァ──エクストリーム！！
line = "アルケインノヴァ──エクストリーム！！"

[[dialogue]]
speaker = "unk"
# ３０００年前の魔王ラクシスから受け継がれる、魔王と絆を結んだ仲間の潜在能力を開放するコード。
line = "３０００年前の魔王ラクシスから受け継がれる、魔王と絆を結んだ仲間の潜在能力を開放するコード。"

[[dialogue]]
speaker = "unk"
# 俺ははっきりと、アニマ先輩の中に眠る覚醒のスイッチをプッシュした──！
line = "俺ははっきりと、アニマ先輩の中に眠る覚醒のスイッチをプッシュした──！"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「フヒッ──フヒヒヒヒッ！　これが魔王……お前だけが引き出せる星騎士の第二形態カ……！！」
line = "「フヒッ──フヒヒヒヒッ！　これが魔王……お前だけが引き出せる星騎士の第二形態カ……！！」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「おいおい、一張羅が変わっただけじゃなイ。傷まで治ってしまっているゾ……ありえなイ！　フヒヒヒ！！　楽しいナァ、魔王！！」
line = "「おいおい、一張羅が変わっただけじゃなイ。傷まで治ってしまっているゾ……ありえなイ！　フヒヒヒ！！　楽しいナァ、魔王！！」"

[[dialogue]]
speaker = "ギガンドム"
# 「ゴォォオォ────！！」
line = "「ゴォォオォ────！！」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「目覚めてゼロ秒で実験させてくれるとハ！　実にありがたイ──来いッ！　ラディカルメディスン！！」
line = "「目覚めてゼロ秒で実験させてくれるとハ！　実にありがたイ──来いッ！　ラディカルメディスン！！」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「フヒッ♪　後ろのビルまですっ飛んでいったゾ♪　試運転は、まぁまぁだナ！」
line = "「フヒッ♪　後ろのビルまですっ飛んでいったゾ♪　試運転は、まぁまぁだナ！」"

[[dialogue]]
speaker = "unk"
# 普段のアニマ先輩からは想像もつかない、規格外の星力量。そして攻撃を食らったギガンドムは、全身を苦しそうに震わせている──！
line = "普段のアニマ先輩からは想像もつかない、規格外の星力量。そして攻撃を食らったギガンドムは、全身を苦しそうに震わせている──！"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「ぶっつけ本番だが、自分の力ダ。ノヴァフォームのアニマが何をできるのか、一瞬で理解したヨ」
line = "「ぶっつけ本番だが、自分の力ダ。ノヴァフォームのアニマが何をできるのか、一瞬で理解したヨ」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「攻撃ついでに、<b>さっき失った弱体化薬を再生成して</b>、一緒にぶつけてやったんダ」
line = "「攻撃ついでに、<b>さっき失った弱体化薬を再生成して</b>、一緒にぶつけてやったんダ」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「物理的な材料を全て、アニマの星力を触媒に生成できル。簡単に言えば、作った事のある錬金薬なら何でもすぐに取り出せるってことかナ？」
line = "「物理的な材料を全て、アニマの星力を触媒に生成できル。簡単に言えば、作った事のある錬金薬なら何でもすぐに取り出せるってことかナ？」"

[[dialogue]]
speaker = "unk"
# ……何でもありじゃないですか
line = "……何でもありじゃないですか"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「フヒヒ、ギガンドムとやら！　さっきのお礼がてら、仕返しをさせてもらうヨ！」
line = "「フヒヒ、ギガンドムとやら！　さっきのお礼がてら、仕返しをさせてもらうヨ！」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「会長は今すぐアステラに行ケ！　ここはアニマ１人で何とかすル！」
line = "「会長は今すぐアステラに行ケ！　ここはアニマ１人で何とかすル！」"

[[dialogue]]
speaker = "unk"
# アナたちは任せてください！
line = "アナたちは任せてください！"

[[dialogue]]
speaker = "unk"
# わかりました！
line = "わかりました！"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「フヒヒ！　また会おう、会長！　……さぁ、実験開始ダ──！！」
line = "「フヒヒ！　また会おう、会長！　……さぁ、実験開始ダ──！！」"
