[[dialogue]]
speaker = "ヴィーナス"
# 「ようやく見つけたわよ！」
line = "「ようやく見つけたわよ！」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長も、なんとか無事のようですね……！」
line = "「緋宮会長も、なんとか無事のようですね……！」"

[[dialogue]]
speaker = "メイプル"
# 「くっ……！」
line = "「くっ……！」"

[[dialogue]]
speaker = "ナナカ"
# 「てかあの子、ちょっと泣いてない？」
line = "「てかあの子、ちょっと泣いてない？」"

[[dialogue]]
speaker = "ルリエル"
# 「花粉症でしょうか……？」
line = "「花粉症でしょうか……？」"

[[dialogue]]
speaker = "ロロット"
# 「お昼寝でもしていたのかもしれませんね」
line = "「お昼寝でもしていたのかもしれませんね」"

[[dialogue]]
speaker = "メイプル"
# 「んも～っ！　泣いてなんかないし、寝起きでもないよっ！」
line = "「んも～っ！　泣いてなんかないし、寝起きでもないよっ！」"

[[dialogue]]
speaker = "ナナカ"
# 「めっちゃ元気だった」
line = "「めっちゃ元気だった」"

[[dialogue]]
speaker = "ロロット"
# 「ではでは、おとなしくお縄を頂戴するのです～！」
line = "「ではでは、おとなしくお縄を頂戴するのです～！」"

[[dialogue]]
speaker = "メイプル"
# 「うぅ～……それにしてもまさか、世界を越えてまで追ってくるなんて……！」
line = "「うぅ～……それにしてもまさか、世界を越えてまで追ってくるなんて……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そんなの当たり前でしょ！　どういうつもりか知らないけど、クロトを返してもらうわよ！」
line = "「そんなの当たり前でしょ！　どういうつもりか知らないけど、クロトを返してもらうわよ！」"

[[dialogue]]
speaker = "メイプル"
# 「ふ～んだ、そうはさせないんだから！」
line = "「ふ～んだ、そうはさせないんだから！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ていうかクロトっ、あなた大丈夫なの！？　いつまでもボ～ッとしてる場合じゃないわよもう！　バカバカ！」
line = "「ていうかクロトっ、あなた大丈夫なの！？　いつまでもボ～ッとしてる場合じゃないわよもう！　バカバカ！」"

[[dialogue]]
speaker = "unk"
# ……っ！
line = "……っ！"

[[dialogue]]
speaker = "メイプル"
# 「にっひっひ～、無駄だよ～だ。お兄ちゃんにかけた拘束の暗示は、そう簡単には解けないんだからっ」
line = "「にっひっひ～、無駄だよ～だ。お兄ちゃんにかけた拘束の暗示は、そう簡単には解けないんだからっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なによそれ、ずるいわ！」
line = "「なによそれ、ずるいわ！」"

[[dialogue]]
speaker = "フィオナ"
# 「なるほど、なかなか厄介ですね……」
line = "「なるほど、なかなか厄介ですね……」"

[[dialogue]]
speaker = "ルリエル"
# 「あの様子だと、自力での脱出は難しそうです……」
line = "「あの様子だと、自力での脱出は難しそうです……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふんっ。だったらまずは、メイプルを正気に戻すところからね！」
line = "「ふんっ。だったらまずは、メイプルを正気に戻すところからね！」"

[[dialogue]]
speaker = "メイプル"
# 「むぅ～……本当は、力ずくでっていうつもりじゃなかったけど、そうも言ってられないみたいだね」
line = "「むぅ～……本当は、力ずくでっていうつもりじゃなかったけど、そうも言ってられないみたいだね」"

[[dialogue]]
speaker = "メイプル"
# 「いいよ、このマカロン様が、直々に相手になってあげる！　さあ、かかってこ～い！」
line = "「いいよ、このマカロン様が、直々に相手になってあげる！　さあ、かかってこ～い！」"

[[dialogue]]
speaker = "ロロット"
# 「ひええええっ！？　なんだか物騒な雰囲気ですよっ……！」
line = "「ひええええっ！？　なんだか物騒な雰囲気ですよっ……！」"

[[dialogue]]
speaker = "ナナカ"
# 「さっきまでの威勢はどこ行ったんでいっ」
line = "「さっきまでの威勢はどこ行ったんでいっ」"

[[dialogue]]
speaker = "ロロット"
# 「これでは、トントロを割られてしまいます～っ！」
line = "「これでは、トントロを割られてしまいます～っ！」"

[[dialogue]]
speaker = "メイプル"
# 「にっひっひ～、このマカロン様の圧倒的なオーラに、恐れをなしちゃった？」
line = "「にっひっひ～、このマカロン様の圧倒的なオーラに、恐れをなしちゃった？」"

[[dialogue]]
speaker = "ナナカ"
# 「なんでい、そっちこそ、一人でこのヤンチャを続けるつもりなわけ？」
line = "「なんでい、そっちこそ、一人でこのヤンチャを続けるつもりなわけ？」"

[[dialogue]]
speaker = "メイプル"
# 「ふっふ～ん、多少の人数の不利なんて、そんなの全然へっちゃらだもんね～っ」
line = "「ふっふ～ん、多少の人数の不利なんて、そんなの全然へっちゃらだもんね～っ」"

[[dialogue]]
speaker = "メイプル"
# 「毎日修行もしてるし、牛乳もちゃんと飲んでるし……このマカロンさまは、やればできる子なんだからっ！」
line = "「毎日修行もしてるし、牛乳もちゃんと飲んでるし……このマカロンさまは、やればできる子なんだからっ！」"

[[dialogue]]
speaker = "メイプル"
# 「シンお兄ちゃんから魔王因子を奪った奴らなんかには、絶対に負けないよっ！」
line = "「シンお兄ちゃんから魔王因子を奪った奴らなんかには、絶対に負けないよっ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ま、まあ、私ほどじゃなさそうだけど、確かにこれは、一筋縄ではいかなそうかも……！」
line = "「ま、まあ、私ほどじゃなさそうだけど、確かにこれは、一筋縄ではいかなそうかも……！」"

[[dialogue]]
speaker = "フィオナ"
# 「それに、このまま正面からぶつかっては、身動きできない緋宮会長を巻き込んでしまう可能性もありますね……！」
line = "「それに、このまま正面からぶつかっては、身動きできない緋宮会長を巻き込んでしまう可能性もありますね……！」"

[[dialogue]]
speaker = "ルリエル"
# 「あら……？　そういえば……」
line = "「あら……？　そういえば……」"

[[dialogue]]
speaker = "ロロット"
# 「おや、きょろきょろとして、どうかしましたか？　お腹でも空いてしまいましたか？」
line = "「おや、きょろきょろとして、どうかしましたか？　お腹でも空いてしまいましたか？」"

[[dialogue]]
speaker = "ルリエル"
# 「違いますよっ、そんなに食いしん坊じゃありませんっ」
line = "「違いますよっ、そんなに食いしん坊じゃありませんっ」"

[[dialogue]]
speaker = "ロロット"
# 「トントロは、食べられませんからね」
line = "「トントロは、食べられませんからね」"

[[dialogue]]
speaker = "ルリエル"
# 「食べませんっ」
line = "「食べませんっ」"

[[dialogue]]
speaker = "メイプル"
# 「にひひ、早速仲間割れしてるじゃ～ん」
line = "「にひひ、早速仲間割れしてるじゃ～ん」"

[[dialogue]]
speaker = "ロロット"
# 「まだ割れてませんからねっ！？」
line = "「まだ割れてませんからねっ！？」"

[[dialogue]]
speaker = "メイプル"
# 「よ～っし、サクッとあいつらを片付けちゃうから、お兄ちゃんはその間、そこでおとなしくしててよねっ」
line = "「よ～っし、サクッとあいつらを片付けちゃうから、お兄ちゃんはその間、そこでおとなしくしててよねっ」"

[[dialogue]]
speaker = "unk"
# メイプル……やめるんだ……っ！
line = "メイプル……やめるんだ……っ！"

[[dialogue]]
speaker = "メイプル"
# 「えっ……！　うそっ……！？」
line = "「えっ……！　うそっ……！？」"

[[dialogue]]
speaker = "ルリエル"
# 「あっ、見て下さいっ！　会長さん、少しずつ動けるようになってきているみたいです……！」
line = "「あっ、見て下さいっ！　会長さん、少しずつ動けるようになってきているみたいです……！」"

[[dialogue]]
speaker = "メイプル"
# 「そんなはずは……！」
line = "「そんなはずは……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「いいわよクロト、あなたの本気を見せてやりなさい！　私が許可するわ！」
line = "「いいわよクロト、あなたの本気を見せてやりなさい！　私が許可するわ！」"

[[dialogue]]
speaker = "メイプル"
# 「ど、どんなに呼びかけたって、無駄だよっ、意味ないんだからっ」
line = "「ど、どんなに呼びかけたって、無駄だよっ、意味ないんだからっ」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長！　意志を強く持って下さい！」
line = "「緋宮会長！　意志を強く持って下さい！」"

[[dialogue]]
speaker = "ナナカ"
# 「気合いだーっ！」
line = "「気合いだーっ！」"

[[dialogue]]
speaker = "ロロット"
# 「根性です～っ！」
line = "「根性です～っ！」"

[[dialogue]]
speaker = "unk"
# ……メイプルっ！
line = "……メイプルっ！"

[[dialogue]]
speaker = "メイプル"
# 「えっ……！？」
line = "「えっ……！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「やったわ、暗示が解けたのね！」
line = "「やったわ、暗示が解けたのね！」"

[[dialogue]]
speaker = "メイプル"
# 「あーっ！　催眠アプリの効果が切れちゃった！」
line = "「あーっ！　催眠アプリの効果が切れちゃった！」"

[[dialogue]]
speaker = "メイプル"
# 「効果時間はもっとあったはずなのに、自力で動けるようになるなんて、想定外だよ……！」
line = "「効果時間はもっとあったはずなのに、自力で動けるようになるなんて、想定外だよ……！」"

[[dialogue]]
speaker = "unk"
# みんな、心配かけてごめん
line = "みんな、心配かけてごめん"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふふっ、私たちの声のおかげで、やる気に目覚めたんじゃない？」
line = "「ふふっ、私たちの声のおかげで、やる気に目覚めたんじゃない？」"

[[dialogue]]
speaker = "ナナカ"
# 「なんなら、アタシらに助けられるまでもなかったかもね。あんた、なかなか根性あるね！」
line = "「なんなら、アタシらに助けられるまでもなかったかもね。あんた、なかなか根性あるね！」"

[[dialogue]]
speaker = "ロロット"
# 「しかし、危ないところだったのは事実……。お礼は、そちらの世界のおいしいおやつで構いませんよ」
line = "「しかし、危ないところだったのは事実……。お礼は、そちらの世界のおいしいおやつで構いませんよ」"

[[dialogue]]
speaker = "ナナカ"
# 「やめんか。いや、あっちの世界のスウィーツは、確かにアタシも気になってはいたけど……」
line = "「やめんか。いや、あっちの世界のスウィーツは、確かにアタシも気になってはいたけど……」"

[[dialogue]]
speaker = "フィオナ"
# 「とにかく、これで一安心ですね」
line = "「とにかく、これで一安心ですね」"

[[dialogue]]
speaker = "ルリエル"
# 「はいっ」
line = "「はいっ」"

[[dialogue]]
speaker = "メイプル"
# 「って、ちょっとーっ！　あたしのこと無視して、解決ムードにならないでよ～っ！」
line = "「って、ちょっとーっ！　あたしのこと無視して、解決ムードにならないでよ～っ！」"

[[dialogue]]
speaker = "ナナカ"
# 「おっと、あとはこっちの暴れん坊を、なんとかしなきゃだね」
line = "「おっと、あとはこっちの暴れん坊を、なんとかしなきゃだね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふっふーん。それじゃあ改めて、あなたも正気に戻してあげるわ！」
line = "「ふっふーん。それじゃあ改めて、あなたも正気に戻してあげるわ！」"

[[dialogue]]
speaker = "フィオナ"
# 「何を企んでいたかはわかりませんが……」
line = "「何を企んでいたかはわかりませんが……」"

[[dialogue]]
speaker = "ロロット"
# 「観念するのです～！」
line = "「観念するのです～！」"

[[dialogue]]
speaker = "メイプル"
# 「んも～っ！　どうあっても抵抗する気っ！？　企むも何も、悪いのはそっちなんだから～っ！」
line = "「んも～っ！　どうあっても抵抗する気っ！？　企むも何も、悪いのはそっちなんだから～っ！」"

[[dialogue]]
speaker = "メイプル"
# 「ただ、奪った魔王因子を返してくれればいいだけなのにっ」
line = "「ただ、奪った魔王因子を返してくれればいいだけなのにっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そういえば……奪ったとか返してとかって、一体どういうこと……？」
line = "「そういえば……奪ったとか返してとかって、一体どういうこと……？」"

[[dialogue]]
speaker = "unk"
# それが……
line = "それが……"

[[dialogue]]
speaker = "ヴィーナス"
# 「えっと、ホントにどういうこと……？」
line = "「えっと、ホントにどういうこと……？」"

[[dialogue]]
speaker = "フィオナ"
# 「何か認識の食い違いがあるようですが……あの気迫、話し合いでは止められそうにありません……！」
line = "「何か認識の食い違いがあるようですが……あの気迫、話し合いでは止められそうにありません……！」"

[[dialogue]]
speaker = "メイプル"
# 「さあ、正々堂々、実力行使させてもらうよ！」
line = "「さあ、正々堂々、実力行使させてもらうよ！」"

[[dialogue]]
speaker = "メイプル"
# 「あなたたちに教えてあげるっ。魔王の正当な後継者は、このマカロンさまなんだからーっ！」
line = "「あなたたちに教えてあげるっ。魔王の正当な後継者は、このマカロンさまなんだからーっ！」"
