[[dialogue]]
speaker = "リーリア"
# 「せんぱーーーい。いきますよーーー、見ててくださいねーーー！！　ひゃああああああ！」
line = "「せんぱーーーい。いきますよーーー、見ててくださいねーーー！！　ひゃああああああ！」"

[[dialogue]]
speaker = "セドナ"
# 「随分と楽しそうにしているようだ」
line = "「随分と楽しそうにしているようだ」"

[[dialogue]]
speaker = "unk"
# セドナさん……
line = "セドナさん……"

[[dialogue]]
speaker = "セドナ"
# 「咎めるつもりはない。先ほども水を差すような真似をしてしまって、済まなかった」
line = "「咎めるつもりはない。先ほども水を差すような真似をしてしまって、済まなかった」"

[[dialogue]]
speaker = "unk"
# セドナさんは遊びにいかないんですか？
line = "セドナさんは遊びにいかないんですか？"

[[dialogue]]
speaker = "セドナ"
# 「それよりも今は、お前と話がしたい」
line = "「それよりも今は、お前と話がしたい」"

[[dialogue]]
speaker = "セドナ"
# 「そうだな……まずは色々とあったが新星、流星星徒会と友好な関係を結べたことを喜ばしく思っている」
line = "「そうだな……まずは色々とあったが新星、流星星徒会と友好な関係を結べたことを喜ばしく思っている」"

[[dialogue]]
speaker = "セドナ"
# 「我々の組織は３０００年前より、此度のリクリエに向けて全てを注いできた」
line = "「我々の組織は３０００年前より、此度のリクリエに向けて全てを注いできた」"

[[dialogue]]
speaker = "セドナ"
# 「それはひとまず退けることが出来たわけだが……三界の状況も、ネビュラという組織も、ここまで五体満足な状態での完勝は想定していなかった」
line = "「それはひとまず退けることが出来たわけだが……三界の状況も、ネビュラという組織も、ここまで五体満足な状態での完勝は想定していなかった」"

[[dialogue]]
speaker = "セドナ"
# 「いや、すまない。もう少し端的に言わせてもらおう。我々は先日のリクリエの日に心中する覚悟であったために、まともなリソースを残していなかったのだ」
line = "「いや、すまない。もう少し端的に言わせてもらおう。我々は先日のリクリエの日に心中する覚悟であったために、まともなリソースを残していなかったのだ」"

[[dialogue]]
speaker = "セドナ"
# 「わかりやすいところで言うと、組織を維持するための金にすら困るほどの体たらくだ」
line = "「わかりやすいところで言うと、組織を維持するための金にすら困るほどの体たらくだ」"

[[dialogue]]
speaker = "セドナ"
# 「だが学園からの援助によって、その危機もどうにか乗り越えられそうだ」
line = "「だが学園からの援助によって、その危機もどうにか乗り越えられそうだ」"

[[dialogue]]
speaker = "unk"
# 今後も友好な関係を続けていきたいです
line = "今後も友好な関係を続けていきたいです"

[[dialogue]]
speaker = "セドナ"
# 「そうだな。もしかすると本当の戦いは、ここからかもしれないのだから……」
line = "「そうだな。もしかすると本当の戦いは、ここからかもしれないのだから……」"

[[dialogue]]
speaker = "セドナ"
# 「…………それから、もうひとつ」
line = "「…………それから、もうひとつ」"

[[dialogue]]
speaker = "セドナ"
# 「……私が言うのも……おかしな話だということは分かっているのだが……」
line = "「……私が言うのも……おかしな話だということは分かっているのだが……」"

[[dialogue]]
speaker = "セドナ"
# 「リーリアと友好な関係を結んでくれて、感謝する……」
line = "「リーリアと友好な関係を結んでくれて、感謝する……」"

[[dialogue]]
speaker = "セドナ"
# 「私の命令で、リーリアはスパイとして人間界に潜入した」
line = "「私の命令で、リーリアはスパイとして人間界に潜入した」"

[[dialogue]]
speaker = "セドナ"
# 「最大の理由は彼女のコミュニケーション能力の高さを見込んでのこと。また、年の若い魔女であり、君たちと同年代であるが故に、感性のズレが少ないと考えた」
line = "「最大の理由は彼女のコミュニケーション能力の高さを見込んでのこと。また、年の若い魔女であり、君たちと同年代であるが故に、感性のズレが少ないと考えた」"

[[dialogue]]
speaker = "セドナ"
# 「なんにせよ、その任命責任は私にあり、スパイ工作は彼女の望んだ仕事ではない」
line = "「なんにせよ、その任命責任は私にあり、スパイ工作は彼女の望んだ仕事ではない」"

[[dialogue]]
speaker = "セドナ"
# 「しかしお前たちの側からすれば、結果的に彼女に騙され、裏切られたということになる」
line = "「しかしお前たちの側からすれば、結果的に彼女に騙され、裏切られたということになる」"

[[dialogue]]
speaker = "セドナ"
# 「にも関わらず、リクリエ以後、お前たちは変わらずリーリアと親しく接してくれている」
line = "「にも関わらず、リクリエ以後、お前たちは変わらずリーリアと親しく接してくれている」"

[[dialogue]]
speaker = "セドナ"
# 「本当に……私が礼を言うような事ではない。だが……心より感謝している……」
line = "「本当に……私が礼を言うような事ではない。だが……心より感謝している……」"

[[dialogue]]
speaker = "unk"
# 部下思いなんですね
line = "部下思いなんですね"

[[dialogue]]
speaker = "セドナ"
# 「そんな立派なものではない……基地では衝突が絶えんよ」
line = "「そんな立派なものではない……基地では衝突が絶えんよ」"

[[dialogue]]
speaker = "セドナ"
# 「私は私の正しいと思う考えを曲げない。合理的であることが、魔女としての矜持だからだ。故に彼女の言い分を力で抑えつけることも度々あった」
line = "「私は私の正しいと思う考えを曲げない。合理的であることが、魔女としての矜持だからだ。故に彼女の言い分を力で抑えつけることも度々あった」"

[[dialogue]]
speaker = "セドナ"
# 「だがリーリアの理屈に筋が通っていないわけではない」
line = "「だがリーリアの理屈に筋が通っていないわけではない」"

[[dialogue]]
speaker = "セドナ"
# 「彼女の言い分もわかる。そして、実際に彼女の考えに基づいた行動によって、ネビュラが救われていることも知っている」
line = "「彼女の言い分もわかる。そして、実際に彼女の考えに基づいた行動によって、ネビュラが救われていることも知っている」"

[[dialogue]]
speaker = "セドナ"
# 「ネビュラと星徒会の友好関係は、彼女の働きかけがなければ存在し得なかったものだろう」
line = "「ネビュラと星徒会の友好関係は、彼女の働きかけがなければ存在し得なかったものだろう」"

[[dialogue]]
speaker = "セドナ"
# 「今日のこの会合に……私がこの場に居ることも無かっただろうな」
line = "「今日のこの会合に……私がこの場に居ることも無かっただろうな」"

[[dialogue]]
speaker = "unk"
# その言葉をリーリアに伝えてみては？
line = "その言葉をリーリアに伝えてみては？"

[[dialogue]]
speaker = "セドナ"
# 「それは、難しいな」
line = "「それは、難しいな」"

[[dialogue]]
speaker = "セドナ"
# 「私たちは私たちのままの関係で良い。互いに煙たく思うほどの距離がむしろ都合がいいのだ」
line = "「私たちは私たちのままの関係で良い。互いに煙たく思うほどの距離がむしろ都合がいいのだ」"

[[dialogue]]
speaker = "セドナ"
# 「とにかく……私はお前にひと言、礼を言っておきたかった……それだけだ」
line = "「とにかく……私はお前にひと言、礼を言っておきたかった……それだけだ」"

[[dialogue]]
speaker = "リーリア"
# 「センパーーーーーーーイ！！！！」
line = "「センパーーーーーーーイ！！！！」"

[[dialogue]]
speaker = "リーリア"
# 「センパイ！　見ててくださいって言ったのに見てなかったですよね！」
line = "「センパイ！　見ててくださいって言ったのに見てなかったですよね！」"

[[dialogue]]
speaker = "セドナ"
# 「私が彼を捕まえて話していたのだ」
line = "「私が彼を捕まえて話していたのだ」"

[[dialogue]]
speaker = "リーリア"
# 「そうでしょうとも！　滑りながら見えてましたから！」
line = "「そうでしょうとも！　滑りながら見えてましたから！」"

[[dialogue]]
speaker = "リーリア"
# 「センパイの浮気者っ！　こうなったら私のことを抱きしめて、一緒に滑ってもらいますからね！」
line = "「センパイの浮気者っ！　こうなったら私のことを抱きしめて、一緒に滑ってもらいますからね！」"

[[dialogue]]
speaker = "unk"
# えー……
line = "えー……"

[[dialogue]]
speaker = "リーリア"
# 「何ですか、その反応は！　こんな美少女が抱っこを求めてるんですから、もっと喜んでください！」
line = "「何ですか、その反応は！　こんな美少女が抱っこを求めてるんですから、もっと喜んでください！」"

[[dialogue]]
speaker = "リーリア"
# 「さあ、行きますよ！　さあ、さあ！！」
line = "「さあ、行きますよ！　さあ、さあ！！」"

[[dialogue]]
speaker = "セドナ"
# 「…………」
line = "「…………」"
