[[dialogue]]
speaker = "unk"
# コラプサーによる新星学園襲撃からしばらく。コハルコは実家のパーツショップの店番をしていた。
line = "コラプサーによる新星学園襲撃からしばらく。コハルコは実家のパーツショップの店番をしていた。"

[[dialogue]]
speaker = "unk"
# 校舎の修理のため学園は臨時休校中。妹ふたりは学校で、父と母は検査で病院に行っている。
line = "校舎の修理のため学園は臨時休校中。妹ふたりは学校で、父と母は検査で病院に行っている。"

[[dialogue]]
speaker = "リーリア"
# 『コハルコ先輩、あなたの正体は魔女なんです』
line = "『コハルコ先輩、あなたの正体は魔女なんです』"

[[dialogue]]
speaker = "コハルコ"
# （私は赤ん坊のころ、今の両親に拾われた。家族と血が繋がってないのは知ってたけど……）
line = "（私は赤ん坊のころ、今の両親に拾われた。家族と血が繋がってないのは知ってたけど……）"

[[dialogue]]
speaker = "リーリア"
# 「コハルコ先輩、荷物の片付け終わりました！」
line = "「コハルコ先輩、荷物の片付け終わりました！」"

[[dialogue]]
speaker = "コハルコ"
# 「ごめんね。護衛で来てくれたのに、お店まで手伝わせちゃって」
line = "「ごめんね。護衛で来てくれたのに、お店まで手伝わせちゃって」"

[[dialogue]]
speaker = "リーリア"
# 「いえいえ、お安い御用です」
line = "「いえいえ、お安い御用です」"

[[dialogue]]
speaker = "unk"
# 彼女は魔女の組織、ネビュラのエージェントだ。先日の襲撃以後、護衛としてコハルコについてくれている。
line = "彼女は魔女の組織、ネビュラのエージェントだ。先日の襲撃以後、護衛としてコハルコについてくれている。"

[[dialogue]]
speaker = "コハルコ"
# 「例の話なんだけど……」
line = "「例の話なんだけど……」"

[[dialogue]]
speaker = "リーリア"
# 「ええと、それはコハルコ先輩の心の準備ができてからで……というか私も詳しくは知らされてなくてですね……ごめんなさい」
line = "「ええと、それはコハルコ先輩の心の準備ができてからで……というか私も詳しくは知らされてなくてですね……ごめんなさい」"

[[dialogue]]
speaker = "コハルコ"
# 「そっか、こっちこそ迷惑かけてごめんね」
line = "「そっか、こっちこそ迷惑かけてごめんね」"

[[dialogue]]
speaker = "コハルコ"
# 「ところで、リーリアさんって実際いくつなの？　ネビュラの人たちって見た目と歳が違うんだよね」
line = "「ところで、リーリアさんって実際いくつなの？　ネビュラの人たちって見た目と歳が違うんだよね」"

[[dialogue]]
speaker = "リーリア"
# 「もう、私はみなさんと変わりませんって！」
line = "「もう、私はみなさんと変わりませんって！」"

[[dialogue]]
speaker = "リーリア"
# 「年齢が上なのは他の魔女です。確かセドナ長官は３００歳くらい、マリオンさんは５００歳……だったかな」
line = "「年齢が上なのは他の魔女です。確かセドナ長官は３００歳くらい、マリオンさんは５００歳……だったかな」"

[[dialogue]]
speaker = "コハルコ"
# 「魔女のひとって本当に長生きなんだね。……その、やっぱり個人差もあるの？」
line = "「魔女のひとって本当に長生きなんだね。……その、やっぱり個人差もあるの？」"

[[dialogue]]
speaker = "リーリア"
# 「もちろんあります。マリオンさんは長生きな方ですけど、それでも２００歳とかは普通ですね。魔女の森の長老格ですと、千年越えもあり得ます」
line = "「もちろんあります。マリオンさんは長生きな方ですけど、それでも２００歳とかは普通ですね。魔女の森の長老格ですと、千年越えもあり得ます」"

[[dialogue]]
speaker = "コハルコ"
# 「千……年……」
line = "「千……年……」"

[[dialogue]]
speaker = "コハルコ"
# （もし私が本当に魔女なら……この先、何年も生きることになる。１００年、２００年、あるいはその先もずっと）
line = "（もし私が本当に魔女なら……この先、何年も生きることになる。１００年、２００年、あるいはその先もずっと）"

[[dialogue]]
speaker = "コハルコ"
# （お父さんやお母さんが私より先に旅立ってしまうことは、まだ、分かる。イヤでイヤで仕方ないけど、納得はできる）
line = "（お父さんやお母さんが私より先に旅立ってしまうことは、まだ、分かる。イヤでイヤで仕方ないけど、納得はできる）"

[[dialogue]]
speaker = "コハルコ"
# （でも、妹たちが私より先に逝くのは耐えられない。想像することさえしたくない）
line = "（でも、妹たちが私より先に逝くのは耐えられない。想像することさえしたくない）"

[[dialogue]]
speaker = "コハルコ"
# （しかも、その先の人生が１００年……もしかすると千年以上も続いてしまうなんて……）
line = "（しかも、その先の人生が１００年……もしかすると千年以上も続いてしまうなんて……）"

[[dialogue]]
speaker = "リーリア"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ナツコ"
# 「お姉ちゃん、ただいま！」
line = "「お姉ちゃん、ただいま！」"

[[dialogue]]
speaker = "トウコ"
# 「ただいま。リーリアさん、来てたんですね」
line = "「ただいま。リーリアさん、来てたんですね」"

[[dialogue]]
speaker = "コハルコ"
# 「おかえり、ふたりとも。今日は一緒だったんだ」
line = "「おかえり、ふたりとも。今日は一緒だったんだ」"

[[dialogue]]
speaker = "unk"
# ナツコとトウコ。コハルコの妹だ。
line = "ナツコとトウコ。コハルコの妹だ。"

[[dialogue]]
speaker = "unk"
# ナツコは名前の通り明るい女の子。トウコはしっかり者の女の子。ふたりとも大切な妹だ。
line = "ナツコは名前の通り明るい女の子。トウコはしっかり者の女の子。ふたりとも大切な妹だ。"

[[dialogue]]
speaker = "ナツコ"
# 「リーリアさん、ゲームしようよ！」
line = "「リーリアさん、ゲームしようよ！」"

[[dialogue]]
speaker = "コハルコ"
# 「こーら。ゲームは宿題が終わってからにしなさい。リーリアさんも無理に付き合わなくていいからね」
line = "「こーら。ゲームは宿題が終わってからにしなさい。リーリアさんも無理に付き合わなくていいからね」"

[[dialogue]]
speaker = "リーリア"
# 「いえ。私、姉妹がいないから、ナツコちゃんやトウコちゃんと遊ぶの楽しいです」
line = "「いえ。私、姉妹がいないから、ナツコちゃんやトウコちゃんと遊ぶの楽しいです」"

[[dialogue]]
speaker = "トウコ"
# 「私も一緒にゲームしていいですか？」
line = "「私も一緒にゲームしていいですか？」"

[[dialogue]]
speaker = "リーリア"
# 「もちろん！　じゃあ早く宿題やろうね」
line = "「もちろん！　じゃあ早く宿題やろうね」"

[[dialogue]]
speaker = "ナツコ"
# 「はーいっ！　行こ、トウコ」
line = "「はーいっ！　行こ、トウコ」"

[[dialogue]]
speaker = "トウコ"
# 「うん」
line = "「うん」"

[[dialogue]]
speaker = "unk"
# ナツコとトウコが嬉しそうに家の中へ駆けていく。
line = "ナツコとトウコが嬉しそうに家の中へ駆けていく。"

[[dialogue]]
speaker = "コハルコ"
# 「魔女にも姉妹っているの？」
line = "「魔女にも姉妹っているの？」"

[[dialogue]]
speaker = "リーリア"
# 「そうですねぇ……私たち魔女は世界樹から生まれるので、本当は親はいないんですけど、年長の魔女が子どもの魔女を育てる習慣があります」
line = "「そうですねぇ……私たち魔女は世界樹から生まれるので、本当は親はいないんですけど、年長の魔女が子どもの魔女を育てる習慣があります」"

[[dialogue]]
speaker = "リーリア"
# 「その魔女を母親って呼んだり、同じ家で育った魔女を姉妹と呼んだりしますね」
line = "「その魔女を母親って呼んだり、同じ家で育った魔女を姉妹と呼んだりしますね」"

[[dialogue]]
speaker = "コハルコ"
# 「なるほど。血は繋がってないけど、家族の関係はあるんだ」
line = "「なるほど。血は繋がってないけど、家族の関係はあるんだ」"

[[dialogue]]
speaker = "コハルコ父"
# 「ただいま、コハルコ。リーリアさんもいらっしゃい」
line = "「ただいま、コハルコ。リーリアさんもいらっしゃい」"

[[dialogue]]
speaker = "unk"
# 病院に行っていたコハルコの両親も帰ってきた。
line = "病院に行っていたコハルコの両親も帰ってきた。"

[[dialogue]]
speaker = "リーリア"
# 「お邪魔してまーすっ」
line = "「お邪魔してまーすっ」"

[[dialogue]]
speaker = "コハルコ母"
# 「コハルコにはいつも面倒かけてごめんね」
line = "「コハルコにはいつも面倒かけてごめんね」"

[[dialogue]]
speaker = "コハルコ"
# 「ううん、気にしないで。検査はどうだった？」
line = "「ううん、気にしないで。検査はどうだった？」"

[[dialogue]]
speaker = "コハルコ母"
# 「数値もレントゲンも異常なしだって。少し疲れが溜まってたのかもしれないわね」
line = "「数値もレントゲンも異常なしだって。少し疲れが溜まってたのかもしれないわね」"

[[dialogue]]
speaker = "コハルコ"
# 「それはよかった。ひと安心だね」
line = "「それはよかった。ひと安心だね」"

[[dialogue]]
speaker = "unk"
# コハルコの母親は生まれつき体が弱い。だから、少々の不調でもすぐ病院にかかるようにしている。
line = "コハルコの母親は生まれつき体が弱い。だから、少々の不調でもすぐ病院にかかるようにしている。"

[[dialogue]]
speaker = "コハルコ母"
# 「コハルコ。あなたこそ、疲れてない？　なんだか元気がないような……」
line = "「コハルコ。あなたこそ、疲れてない？　なんだか元気がないような……」"

[[dialogue]]
speaker = "コハルコ"
# 「……どうだろ。学園が襲撃されるなんて今までなかったから、ナーバスになってるのかも」
line = "「……どうだろ。学園が襲撃されるなんて今までなかったから、ナーバスになってるのかも」"

[[dialogue]]
speaker = "コハルコ"
# （……余計な心配かけたくないから、学園襲撃のターゲットが私だったことは家族には伝えてない。いつも通りにしてるつもりだけど、やっぱりお母さんには分かっちゃうのかな）
line = "（……余計な心配かけたくないから、学園襲撃のターゲットが私だったことは家族には伝えてない。いつも通りにしてるつもりだけど、やっぱりお母さんには分かっちゃうのかな）"

[[dialogue]]
speaker = "コハルコ父"
# 「辛かったら休んでいていいんだよ。店だってずっと開けてなくてもいいんだから」
line = "「辛かったら休んでいていいんだよ。店だってずっと開けてなくてもいいんだから」"

[[dialogue]]
speaker = "コハルコ"
# 「ううん、むしろ店番してる方が気が楽かな。あ、ナツコとトウコもう帰ってるよ」
line = "「ううん、むしろ店番してる方が気が楽かな。あ、ナツコとトウコもう帰ってるよ」"

[[dialogue]]
speaker = "コハルコ父"
# 「ああ、分かった」
line = "「ああ、分かった」"

[[dialogue]]
speaker = "コハルコ母"
# 「今日はお母さんが晩ごはん作るわね。腕によりをかけるから楽しみにしてて」
line = "「今日はお母さんが晩ごはん作るわね。腕によりをかけるから楽しみにしてて」"

[[dialogue]]
speaker = "コハルコ"
# 「……うん、ありがと」
line = "「……うん、ありがと」"

[[dialogue]]
speaker = "？？？"
# 「…………」
line = "「…………」"
