[[dialogue]]
speaker = "unk"
# リバースフォームの訓練中、突如『赤ちゃん化』してしまったプリムラ。
line = "リバースフォームの訓練中、突如『赤ちゃん化』してしまったプリムラ。"

[[dialogue]]
speaker = "プリムラ"
# 「だあぁ♪　ママぁ～<emoji=heart04>」
line = "「だあぁ♪　ママぁ～<emoji=heart04>」"

[[dialogue]]
speaker = "トレジアンナ"
# 「は～い♪　プリムラさん、アンナママでちゅよ～♪」
line = "「は～い♪　プリムラさん、アンナママでちゅよ～♪」"

[[dialogue]]
speaker = "unk"
# 無邪気に抱き着くプリムラを受け止め、優しく頭を撫でる。
line = "無邪気に抱き着くプリムラを受け止め、優しく頭を撫でる。"

[[dialogue]]
speaker = "プリムラ"
# 「きゃっきゃ♪　アンナママのおっぱい、やらかぁ～い<emoji=heart04>」
line = "「きゃっきゃ♪　アンナママのおっぱい、やらかぁ～い<emoji=heart04>」"

[[dialogue]]
speaker = "トレジアンナ"
# 「よちよち～♪　……これはおそらく、プリムラさんの力だけでなく、精神まで反転してしまっているのかもしれませんね～」
line = "「よちよち～♪　……これはおそらく、プリムラさんの力だけでなく、精神まで反転してしまっているのかもしれませんね～」"

[[dialogue]]
speaker = "プリムラ"
# 「あぁ～い♪」
line = "「あぁ～い♪」"

[[dialogue]]
speaker = "シズハ"
# 「つまり、プリムラちゃんの精神年齢が赤ちゃんレベルまで退行しちゃったってこと！？」
line = "「つまり、プリムラちゃんの精神年齢が赤ちゃんレベルまで退行しちゃったってこと！？」"

[[dialogue]]
speaker = "プリムラ"
# 「んぅ～♪　シズハママも、だっこ～<emoji=heart04>」
line = "「んぅ～♪　シズハママも、だっこ～<emoji=heart04>」"

[[dialogue]]
speaker = "シズハ"
# 「えっ！？　私もママなの！？」
line = "「えっ！？　私もママなの！？」"

[[dialogue]]
speaker = "unk"
# 抱きつかれ、困惑しながらも撫でるシズハ。
line = "抱きつかれ、困惑しながらも撫でるシズハ。"

[[dialogue]]
speaker = "プリムラ"
# 「ふへへへぇ～<emoji=heart04>　あたまなでなで、すき～<emoji=heart04>」
line = "「ふへへへぇ～<emoji=heart04>　あたまなでなで、すき～<emoji=heart04>」"

[[dialogue]]
speaker = "シズハ"
# 「ぷ、プリムラちゃん……可愛い……<emoji=heart04>」
line = "「ぷ、プリムラちゃん……可愛い……<emoji=heart04>」"

[[dialogue]]
speaker = "プリムラ"
# 「ばぶぅ～♪　パパも抱っこ～<emoji=heart04>」
line = "「ばぶぅ～♪　パパも抱っこ～<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# プリムラはそう言って、今度は俺に突進。
line = "プリムラはそう言って、今度は俺に突進。"

[[dialogue]]
speaker = "プリムラ"
# 「ぎゅうぅ～～っ<emoji=heart04>」
line = "「ぎゅうぅ～～っ<emoji=heart04>」"

[[dialogue]]
speaker = "サチ"
# 「ちょっ、お兄さんにも……！？」
line = "「ちょっ、お兄さんにも……！？」"

[[dialogue]]
speaker = "unk"
# 俺はパパか～
line = "俺はパパか～"

[[dialogue]]
speaker = "サチ"
# 「動じてないですね……」
line = "「動じてないですね……」"

[[dialogue]]
speaker = "トレジアンナ"
# 「会長さんは慣れてますからね～」
line = "「会長さんは慣れてますからね～」"

[[dialogue]]
speaker = "プリムラ"
# 「じ～っ……」
line = "「じ～っ……」"

[[dialogue]]
speaker = "unk"
# プリムラが次に視線を向けたのは、近くでふわふわ浮いているディーラック。
line = "プリムラが次に視線を向けたのは、近くでふわふわ浮いているディーラック。"

[[dialogue]]
speaker = "ディーラック"
# 「あん？　ボクかい？」
line = "「あん？　ボクかい？」"

[[dialogue]]
speaker = "ディーラック"
# 「まあボクは、実際にプリムラを生み出した『ママ』ではあるけどサ……」
line = "「まあボクは、実際にプリムラを生み出した『ママ』ではあるけどサ……」"

[[dialogue]]
speaker = "プリムラ"
# 「ディーラックは――わんわん！」
line = "「ディーラックは――わんわん！」"

[[dialogue]]
speaker = "ディーラック"
# 「犬扱い！？　いや、なんでだよ！？」
line = "「犬扱い！？　いや、なんでだよ！？」"

[[dialogue]]
speaker = "プリムラ"
# 「だあぁっ♪　わんわんのしっぽ～♪」
line = "「だあぁっ♪　わんわんのしっぽ～♪」"

[[dialogue]]
speaker = "ディーラック"
# 「あっ、いてててっ！　おい、尻尾を引っ張るなってば！」
line = "「あっ、いてててっ！　おい、尻尾を引っ張るなってば！」"

[[dialogue]]
speaker = "プリムラ"
# 「？　わんわん、『タマタマ』ない？」
line = "「？　わんわん、『タマタマ』ない？」"

[[dialogue]]
speaker = "ディーラック"
# 「ないよっ！　ボク、女の子だからね！？　というか、どこ見てんのサ！？」
line = "「ないよっ！　ボク、女の子だからね！？　というか、どこ見てんのサ！？」"

[[dialogue]]
speaker = "サチ"
# 「あ、あの……私は？」
line = "「あ、あの……私は？」"

[[dialogue]]
speaker = "unk"
# 気になったのか、サチがプリムラに尋ねる。
line = "気になったのか、サチがプリムラに尋ねる。"

[[dialogue]]
speaker = "unk"
# プリムラはじっと見つめ――
line = "プリムラはじっと見つめ――"

[[dialogue]]
speaker = "プリムラ"
# 「サチはママじゃない！」
line = "「サチはママじゃない！」"

[[dialogue]]
speaker = "サチ"
# 「ち、違うの？　じゃあ、お姉さん……？」
line = "「ち、違うの？　じゃあ、お姉さん……？」"

[[dialogue]]
speaker = "プリムラ"
# 「ちがう！　サチは、ただのサチ！」
line = "「ちがう！　サチは、ただのサチ！」"

[[dialogue]]
speaker = "サチ"
# 「なんでぇ～っ！？」
line = "「なんでぇ～っ！？」"

[[dialogue]]
speaker = "unk"
# 地味にショックを受けるサチであった。
line = "地味にショックを受けるサチであった。"

[[dialogue]]
speaker = "unk"
# やがて暴走は収まり、プリムラは正気に戻る。
line = "やがて暴走は収まり、プリムラは正気に戻る。"

[[dialogue]]
speaker = "プリムラ"
# 「……フッ」
line = "「……フッ」"

[[dialogue]]
speaker = "unk"
# 小さく笑うと、プリムラは虚ろな目で呟いた。
line = "小さく笑うと、プリムラは虚ろな目で呟いた。"

[[dialogue]]
speaker = "プリムラ"
# 「ハ、ハハ……これは、切腹か……？　生き恥を晒すくらいなら、自ら腹を切るべきではないのか……？」
line = "「ハ、ハハ……これは、切腹か……？　生き恥を晒すくらいなら、自ら腹を切るべきではないのか……？」"

[[dialogue]]
speaker = "サチ"
# 「え～っと、コメントしづらいな……」
line = "「え～っと、コメントしづらいな……」"

[[dialogue]]
speaker = "シズハ"
# 「プリムラちゃん！　暴走しちゃってただけなんだから、誰も気にしてないよ！」
line = "「プリムラちゃん！　暴走しちゃってただけなんだから、誰も気にしてないよ！」"

[[dialogue]]
speaker = "プリムラ"
# 「くっ……！　なんで我があんな『赤ちゃん』みたいな恥ずかしい姿を晒す羽目になっとるのじゃあああぁ～～っ！？」
line = "「くっ……！　なんで我があんな『赤ちゃん』みたいな恥ずかしい姿を晒す羽目になっとるのじゃあああぁ～～っ！？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「別に気にせず、甘えてくれてもいいんですよ～？」
line = "「別に気にせず、甘えてくれてもいいんですよ～？」"

[[dialogue]]
speaker = "unk"
# パパなら任せろ！
line = "パパなら任せろ！"

[[dialogue]]
speaker = "プリムラ"
# 「できるかぁーーーっ！！」
line = "「できるかぁーーーっ！！」"

[[dialogue]]
speaker = "unk"
# 顔を真っ赤にして絶叫するプリムラなのであった。
line = "顔を真っ赤にして絶叫するプリムラなのであった。"

[[dialogue]]
speaker = "unk"
# 精神的にダメージを受けたプリムラと交代し、今度はサチが訓練をすることに。
line = "精神的にダメージを受けたプリムラと交代し、今度はサチが訓練をすることに。"

[[dialogue]]
speaker = "unk"
# 仮想空間も気分を切り替えて、『マリンレジャー』のフィールドへと変更する。
line = "仮想空間も気分を切り替えて、『マリンレジャー』のフィールドへと変更する。"

[[dialogue]]
speaker = "モンスター"
# 「フワッチ～♪」
line = "「フワッチ～♪」"

[[dialogue]]
speaker = "サチ"
# 「よし……行きます！　――はああぁっ！」
line = "「よし……行きます！　――はああぁっ！」"

[[dialogue]]
speaker = "unk"
# 斧を構え、モンスターへ突進するサチ。
line = "斧を構え、モンスターへ突進するサチ。"

[[dialogue]]
speaker = "unk"
# そういえば、サチの能力って？
line = "そういえば、サチの能力って？"

[[dialogue]]
speaker = "トレジアンナ"
# 「あ～、それはですね――」
line = "「あ～、それはですね――」"

[[dialogue]]
speaker = "サチ"
# 「え？　なんでここにビーチボールが埋まって――きゃあぁっ！？」
line = "「え？　なんでここにビーチボールが埋まって――きゃあぁっ！？」"

[[dialogue]]
speaker = "unk"
# 足元に埋まっていたビーチボールを踏んづけてしまい、盛大にズッコケてしまうサチ。
line = "足元に埋まっていたビーチボールを踏んづけてしまい、盛大にズッコケてしまうサチ。"

[[dialogue]]
speaker = "unk"
# そのまま砂浜に顔面スライディングを決め、ちょうどモンスターの目の前で停止する。
line = "そのまま砂浜に顔面スライディングを決め、ちょうどモンスターの目の前で停止する。"

[[dialogue]]
speaker = "モンスター"
# 「フワッチ？」
line = "「フワッチ？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「サチさんの元の能力は『幸運を引き寄せる』というものでしたが、反転した今は――」
line = "「サチさんの元の能力は『幸運を引き寄せる』というものでしたが、反転した今は――」"

[[dialogue]]
speaker = "トレジアンナ"
# 「『不運を引き寄せる』という、とんでもなく厄介な代物になっちゃってるんですよね～」
line = "「『不運を引き寄せる』という、とんでもなく厄介な代物になっちゃってるんですよね～」"

[[dialogue]]
speaker = "サチ"
# 「けほっ、こほっ……！　うぅ……アンラッキーです……」
line = "「けほっ、こほっ……！　うぅ……アンラッキーです……」"

[[dialogue]]
speaker = "unk"
# 砂まみれになった顔で、しょんぼり呟くサチなのであった。
line = "砂まみれになった顔で、しょんぼり呟くサチなのであった。"
