[[dialogue]]
speaker = "unk"
# ミヤハルの住む『浅草安倍野神社』へ、巫女修行にやって来たマトイとルリエル、そしてトマル。
line = "ミヤハルの住む『浅草安倍野神社』へ、巫女修行にやって来たマトイとルリエル、そしてトマル。"

[[dialogue]]
speaker = "ルリエル"
# 「それにしてもトマルさん、マトイさんの弟さんだとお聞きしてましたが、本当にどう見ても女の子にしか見えませんね～」
line = "「それにしてもトマルさん、マトイさんの弟さんだとお聞きしてましたが、本当にどう見ても女の子にしか見えませんね～」"

[[dialogue]]
speaker = "トマル"
# 「ありがとうございます、ルリエルさま。でも、今は本当に、女の子の体になっているんですよ」
line = "「ありがとうございます、ルリエルさま。でも、今は本当に、女の子の体になっているんですよ」"

[[dialogue]]
speaker = "ルリエル"
# 「えっ、やっぱりトマルさんは妹さんだったのですか！？」
line = "「えっ、やっぱりトマルさんは妹さんだったのですか！？」"

[[dialogue]]
speaker = "マトイ"
# 「違う違う。ややこしいと思うけど、本当の性別は男で合ってるよ」
line = "「違う違う。ややこしいと思うけど、本当の性別は男で合ってるよ」"

[[dialogue]]
speaker = "トマル"
# 「巫女修行するに当たり、アニマさまの女体化薬を使わせて頂いて、一時的に性転換をしているんです」
line = "「巫女修行するに当たり、アニマさまの女体化薬を使わせて頂いて、一時的に性転換をしているんです」"

[[dialogue]]
speaker = "トマル"
# 「巫女の力を使えるようになるには、女の子じゃないと、どうやら難しいらしくて……」
line = "「巫女の力を使えるようになるには、女の子じゃないと、どうやら難しいらしくて……」"

[[dialogue]]
speaker = "ミヤハル"
# 「トマルはんは驚くことに、男の体のままでも巫女の適正があったんよ」
line = "「トマルはんは驚くことに、男の体のままでも巫女の適正があったんよ」"

[[dialogue]]
speaker = "ミヤハル"
# 「それが女の体になってみせた途端、巫女の力を一気に引き出せるようになって、あっという間に修行を修めてしまった。あれはまさに覚醒やったね」
line = "「それが女の体になってみせた途端、巫女の力を一気に引き出せるようになって、あっという間に修行を修めてしまった。あれはまさに覚醒やったね」"

[[dialogue]]
speaker = "トマル"
# 「恐縮です。ですが、まだまだ力を使えるようになって日が浅い未熟者です。よろしければ姉さまと一緒に、引き続きご指導をお願いできればと……」
line = "「恐縮です。ですが、まだまだ力を使えるようになって日が浅い未熟者です。よろしければ姉さまと一緒に、引き続きご指導をお願いできればと……」"

[[dialogue]]
speaker = "ミヤハル"
# 「トマルはんは、ほんまに真面目でええ子やねぇ。そんな風にお願いされたら、億劫な仕事でも断れんわ～」
line = "「トマルはんは、ほんまに真面目でええ子やねぇ。そんな風にお願いされたら、億劫な仕事でも断れんわ～」"

[[dialogue]]
speaker = "ミヤハル"
# 「一応、うちが流星市国で真面目にやってますよ～って、京都の両親を安心させる為のポーズにもなるしな」
line = "「一応、うちが流星市国で真面目にやってますよ～って、京都の両親を安心させる為のポーズにもなるしな」"

[[dialogue]]
speaker = "マトイ"
# 「ミヤハルさんの実家は京都に？」
line = "「ミヤハルさんの実家は京都に？」"

[[dialogue]]
speaker = "ミヤハル"
# 「生まれも育ちも京都やよ。この神社よりもっと大きい、『京都安倍野神社』っていうのがそこにあってな。宮司をやっているのが、うちのお母はんなんよ」
line = "「生まれも育ちも京都やよ。この神社よりもっと大きい、『京都安倍野神社』っていうのがそこにあってな。宮司をやっているのが、うちのお母はんなんよ」"

[[dialogue]]
speaker = "ミヤハル"
# 「あっ、ちなみにやけどな？　うちの喋り方、ほんまもんの京都弁やのうて、似非どすえ<emoji=heart04>　はんなりした言い回しが気に入ってて、それっぽく真似しとるだけなんよ～」
line = "「あっ、ちなみにやけどな？　うちの喋り方、ほんまもんの京都弁やのうて、似非どすえ<emoji=heart04>　はんなりした言い回しが気に入ってて、それっぽく真似しとるだけなんよ～」"

[[dialogue]]
speaker = "マトイ"
# 「京都出身者の似非京都弁ってなに！？」
line = "「京都出身者の似非京都弁ってなに！？」"

[[dialogue]]
speaker = "ミヤハル"
# 「しゃーないんよ～。お父はんもお母はんも、うちの前ではあんまり方言使ってくれへんかったんどす<emoji=heart04>」
line = "「しゃーないんよ～。お父はんもお母はんも、うちの前ではあんまり方言使ってくれへんかったんどす<emoji=heart04>」"

[[dialogue]]
speaker = "ルリエル"
# 「ミヤハルさんは流星市国には１人で来たんですか？」
line = "「ミヤハルさんは流星市国には１人で来たんですか？」"

[[dialogue]]
speaker = "ミヤハル"
# 「そ。この神社の裏にある離れで、お気楽な１人暮らしや<emoji=heart04>」
line = "「そ。この神社の裏にある離れで、お気楽な１人暮らしや<emoji=heart04>」"

[[dialogue]]
speaker = "マトイ"
# 「え？　１人？　他に神社を管理している人とかは……」
line = "「え？　１人？　他に神社を管理している人とかは……」"

[[dialogue]]
speaker = "ミヤハル"
# 「ああ、うちは陰陽術で式神を召喚するのが得意技なんで、掃除とかの管理はその子らにお願いしとるんよ。便利な能力やろ？」
line = "「ああ、うちは陰陽術で式神を召喚するのが得意技なんで、掃除とかの管理はその子らにお願いしとるんよ。便利な能力やろ？」"

[[dialogue]]
speaker = "ミヤハル"
# 「それに、１人の方がうちの性に合っとるしな。その代わり、こまめに連絡はしてくれ～って両親はよう心配しとるけど」
line = "「それに、１人の方がうちの性に合っとるしな。その代わり、こまめに連絡はしてくれ～って両親はよう心配しとるけど」"

[[dialogue]]
speaker = "ミヤハル"
# 「さて、うちの話はこれくらいにしておいて――本題の巫女修行の話に戻りまひょか<emoji=heart04>」
line = "「さて、うちの話はこれくらいにしておいて――本題の巫女修行の話に戻りまひょか<emoji=heart04>」"

[[dialogue]]
speaker = "ミヤハル"
# 「巫女の力を上手く扱えるようにする方法なんやけど……『煩悩』を解放するというのが、うちのオススメや<emoji=heart04>」
line = "「巫女の力を上手く扱えるようにする方法なんやけど……『煩悩』を解放するというのが、うちのオススメや<emoji=heart04>」"

[[dialogue]]
speaker = "ルリエル"
# 「煩悩？」
line = "「煩悩？」"

[[dialogue]]
speaker = "マトイ"
# 「それってどういう……？」
line = "「それってどういう……？」"

[[dialogue]]
speaker = "ミヤハル"
# 「簡単に言うと～、心の内に抱える『欲望』やね<emoji=heart04>」
line = "「簡単に言うと～、心の内に抱える『欲望』やね<emoji=heart04>」"

[[dialogue]]
speaker = "ミヤハル"
# 「うちはそれを、陰陽術で<b>心の影</b>として具現化することができる」
line = "「うちはそれを、陰陽術で<b>心の影</b>として具現化することができる」"

[[dialogue]]
speaker = "ミヤハル"
# 「百聞は一見に如かず。実際にやってみまひょか」
line = "「百聞は一見に如かず。実際にやってみまひょか」"

[[dialogue]]
speaker = "ミヤハル"
# 「じゃあ――まずはマトイはんの煩悩から<emoji=heart04>」
line = "「じゃあ――まずはマトイはんの煩悩から<emoji=heart04>」"

[[dialogue]]
speaker = "マトイ"
# 「えっ、私から！？　ちょ、ちょっと待って！　心の準備が……！」
line = "「えっ、私から！？　ちょ、ちょっと待って！　心の準備が……！」"

[[dialogue]]
speaker = "ミヤハル"
# 「ふふっ、ダメやよ～<emoji=heart04>　その心と向き合うことが、今回の修業なんやから。それじゃあ、はんなりと行きますえ～<emoji=heart04>」
line = "「ふふっ、ダメやよ～<emoji=heart04>　その心と向き合うことが、今回の修業なんやから。それじゃあ、はんなりと行きますえ～<emoji=heart04>」"

[[dialogue]]
speaker = "ミヤハル"
# 「<ruby=きゅうきゅうにょりつりょう>急急如律令</ruby>、<ruby=しんえいとうしゃ>心影投射</ruby>――」
line = "「<ruby>急急如律令<rt>きゅうきゅうにょりつりょう</rt></ruby>、<ruby>心影投射<rt>しんえいとうしゃ</rt></ruby>――」"

[[dialogue]]
speaker = "unk"
# 指で五芒星を描きながら、ミヤハルが呪文を口にすると。
line = "指で五芒星を描きながら、ミヤハルが呪文を口にすると。"

[[dialogue]]
speaker = "クロト"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ルリエル"
# 「会長さんが現れたのです！？」
line = "「会長さんが現れたのです！？」"

[[dialogue]]
speaker = "クロト"
# 「……やあ、みんな」
line = "「……やあ、みんな」"

[[dialogue]]
speaker = "マトイ"
# 「しゃ、シャベッタァァァァァァッ！？」
line = "「しゃ、シャベッタァァァァァァッ！？」"

[[dialogue]]
speaker = "クロト"
# 「あはは♪　何を言っているんだ、マトイ？　いつも俺は普通に喋っているじゃないか」
line = "「あはは♪　何を言っているんだ、マトイ？　いつも俺は普通に喋っているじゃないか」"

[[dialogue]]
speaker = "マトイ"
# 「いや、そうなんだけども……！　というか、なんで会長が現れたわけ！？　これって本物じゃないよね！？」
line = "「いや、そうなんだけども……！　というか、なんで会長が現れたわけ！？　これって本物じゃないよね！？」"

[[dialogue]]
speaker = "ミヤハル"
# 「ふふっ<emoji=heart04>　さっき言った通りや。これがうちの陰陽術で具現化した、マトイはんの煩悩の影やよ<emoji=heart04>」
line = "「ふふっ<emoji=heart04>　さっき言った通りや。これがうちの陰陽術で具現化した、マトイはんの煩悩の影やよ<emoji=heart04>」"

[[dialogue]]
speaker = "マトイ"
# 「はい！？　私の煩悩が、か、会長……！？」
line = "「はい！？　私の煩悩が、か、会長……！？」"

[[dialogue]]
speaker = "ルリエル"
# 「つまりは、マトイさんは会長さんに、強い『欲望』を持っているということですね！」
line = "「つまりは、マトイさんは会長さんに、強い『欲望』を持っているということですね！」"

[[dialogue]]
speaker = "マトイ"
# 「ルリエルちゃん！？　べべべ、別にそんなわけ……！」
line = "「ルリエルちゃん！？　べべべ、別にそんなわけ……！」"

[[dialogue]]
speaker = "ミヤハル"
# 「ぷっ……ふふふっ<emoji=heart04>　ルリエルはん、可愛い顔して強烈な発言をする子やねぇ。面白いわぁ<emoji=heart04>」
line = "「ぷっ……ふふふっ<emoji=heart04>　ルリエルはん、可愛い顔して強烈な発言をする子やねぇ。面白いわぁ<emoji=heart04>」"

[[dialogue]]
speaker = "煩悩クロト"
# 「マトイ」
line = "「マトイ」"

[[dialogue]]
speaker = "マトイ"
# 「え？　な、何？　そんないきなり近づいて来て――ひゃっ！？」
line = "「え？　な、何？　そんないきなり近づいて来て――ひゃっ！？」"

[[dialogue]]
speaker = "unk"
# 会長の影はマトイに近づくと、そのまま後退りさせ、<b>壁ドン</b>をする。
line = "会長の影はマトイに近づくと、そのまま後退りさせ、<b>壁ドン</b>をする。"

[[dialogue]]
speaker = "マトイ"
# 「かかか、会長！？　顔が近い近い近い～……！」
line = "「かかか、会長！？　顔が近い近い近い～……！」"

[[dialogue]]
speaker = "マトイ"
# （こ、これってもしかして壁ドンってやつ～！？　う、生まれて初めてされちゃったんですけどぉ～～～！？）
line = "（こ、これってもしかして壁ドンってやつ～！？　う、生まれて初めてされちゃったんですけどぉ～～～！？）"

[[dialogue]]
speaker = "煩悩クロト"
# 「ごめんよ。でも、マトイの煩悩が俺だって知ったら、つい嬉しくなっちゃって――」
line = "「ごめんよ。でも、マトイの煩悩が俺だって知ったら、つい嬉しくなっちゃって――」"

[[dialogue]]
speaker = "unk"
# 会長の影がマトイの耳元で囁く。
line = "会長の影がマトイの耳元で囁く。"

[[dialogue]]
speaker = "煩悩クロト"
# 「ありがとな。俺を選んでくれて（イケボ）」
line = "「ありがとな。俺を選んでくれて（イケボ）」"

[[dialogue]]
speaker = "マトイ"
# 「ひゃあああぁぁぁ～～～っ！？」
line = "「ひゃあああぁぁぁ～～～っ！？」"

[[dialogue]]
speaker = "ルリエル"
# 「マトイさんがスタンしてしまったのです！」
line = "「マトイさんがスタンしてしまったのです！」"

[[dialogue]]
speaker = "トマル"
# 「マトイ姉さま、うらやま――いえ、大丈夫ですか！？」
line = "「マトイ姉さま、うらやま――いえ、大丈夫ですか！？」"

[[dialogue]]
speaker = "煩悩クロト"
# 「トマルも……羨ましかったのか？」
line = "「トマルも……羨ましかったのか？」"

[[dialogue]]
speaker = "トマル"
# 「か、会長さま！？　い、いえ……その……」
line = "「か、会長さま！？　い、いえ……その……」"

[[dialogue]]
speaker = "煩悩クロト"
# 「遠慮しなくてもいい。それなら、ほら――」
line = "「遠慮しなくてもいい。それなら、ほら――」"

[[dialogue]]
speaker = "トマル"
# 「ひゃあっ！？」
line = "「ひゃあっ！？」"

[[dialogue]]
speaker = "ルリエル"
# 「トマルさんにも壁ドン攻撃なのです！」
line = "「トマルさんにも壁ドン攻撃なのです！」"

[[dialogue]]
speaker = "トマル"
# 「はあぁっ……<emoji=heart04>　ダメです、会長さま、こんな……！」
line = "「はあぁっ……<emoji=heart04>　ダメです、会長さま、こんな……！」"

[[dialogue]]
speaker = "トマル"
# 「貴方さまはあくまで、姉さまが呼び出した存在だというのに……！」
line = "「貴方さまはあくまで、姉さまが呼び出した存在だというのに……！」"

[[dialogue]]
speaker = "煩悩クロト"
# 「トマルは優しいな。でも、だからこそ放って置けなくて……」
line = "「トマルは優しいな。でも、だからこそ放って置けなくて……」"

[[dialogue]]
speaker = "煩悩クロト"
# 「姉想いの健気なトマルは、性別関係なく可愛いよ（耳元でイケボ）」
line = "「姉想いの健気なトマルは、性別関係なく可愛いよ（耳元でイケボ）」"

[[dialogue]]
speaker = "トマル"
# 「～～～っ！？<emoji=heart04><emoji=heart04>」
line = "「～～～っ！？<emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "トマル"
# 「はうぅ～ん……<emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「はうぅ～ん……<emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ルリエル"
# 「トマルさんも、会長さんにランブル負けなのです！」
line = "「トマルさんも、会長さんにランブル負けなのです！」"

[[dialogue]]
speaker = "ルリエル"
# 「なんだか、お２人共すごく楽しそうなのです！　次はルリエルもやってみたいのです♪」
line = "「なんだか、お２人共すごく楽しそうなのです！　次はルリエルもやってみたいのです♪」"

[[dialogue]]
speaker = "煩悩クロト"
# 「そうか。それなら、ルリエルだけ仲間ハズレには出来ないな。同じように壁ドンがいいか？」
line = "「そうか。それなら、ルリエルだけ仲間ハズレには出来ないな。同じように壁ドンがいいか？」"

[[dialogue]]
speaker = "ルリエル"
# 「壁ドンも楽しそうですけど、わたしは１度、してみたかったことがあるのです！」
line = "「壁ドンも楽しそうですけど、わたしは１度、してみたかったことがあるのです！」"

[[dialogue]]
speaker = "煩悩クロト"
# 「してみたかったこと？」
line = "「してみたかったこと？」"

[[dialogue]]
speaker = "ルリエル"
# 「はい♪　ルリエルは、『お姫様抱っこ』というものを体験してみたいのです！」
line = "「はい♪　ルリエルは、『お姫様抱っこ』というものを体験してみたいのです！」"

[[dialogue]]
speaker = "煩悩クロト"
# 「なるほど。それじゃあ、失礼するよ。――よいしょっと」
line = "「なるほど。それじゃあ、失礼するよ。――よいしょっと」"

[[dialogue]]
speaker = "ルリエル"
# 「きゃっ♪　わぁ～～っ♪　あはははっ♪」
line = "「きゃっ♪　わぁ～～っ♪　あはははっ♪」"

[[dialogue]]
speaker = "ルリエル"
# 「これがお姫様抱っこなのですね～♪　えへへへへへぇっ♪」
line = "「これがお姫様抱っこなのですね～♪　えへへへへへぇっ♪」"

[[dialogue]]
speaker = "ルリエル"
# 「なんだか、すごく懐かしい感じがして好きなのです♪　昔、じっちゃんにおんぶして貰った時みたいな感じがします♪」
line = "「なんだか、すごく懐かしい感じがして好きなのです♪　昔、じっちゃんにおんぶして貰った時みたいな感じがします♪」"

[[dialogue]]
speaker = "ミヤハル"
# 「あ～ん、みんな楽しそうでずるいわぁ<emoji=heart04>　会長はん、うちとも遊んで～<emoji=heart04>」
line = "「あ～ん、みんな楽しそうでずるいわぁ<emoji=heart04>　会長はん、うちとも遊んで～<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# と、ミヤハルが会長の影に抱き着く。
line = "と、ミヤハルが会長の影に抱き着く。"

[[dialogue]]
speaker = "煩悩クロト"
# 「ミヤハルはどうして欲しいんだ？」
line = "「ミヤハルはどうして欲しいんだ？」"

[[dialogue]]
speaker = "ミヤハル"
# 「ふふっ<emoji=heart04>　ほんなら、離れのうちの部屋で、ゆっくりとお話しまひょ<emoji=heart04>」
line = "「ふふっ<emoji=heart04>　ほんなら、離れのうちの部屋で、ゆっくりとお話しまひょ<emoji=heart04>」"

[[dialogue]]
speaker = "マトイ"
# 「わざわざ離れに移動する必要ある！？」
line = "「わざわざ離れに移動する必要ある！？」"

[[dialogue]]
speaker = "煩悩クロト"
# 「おっと、ミヤハル、ごめんよ。どうやらお姫様がお目覚めみたいだ」
line = "「おっと、ミヤハル、ごめんよ。どうやらお姫様がお目覚めみたいだ」"

[[dialogue]]
speaker = "ミヤハル"
# 「あらぁ、残念やわぁ。あんなことやこんなこともしてみたかったのに……」
line = "「あらぁ、残念やわぁ。あんなことやこんなこともしてみたかったのに……」"

[[dialogue]]
speaker = "煩悩クロト"
# 「マトイ、すまない。みんなが望んでくれるから、つい応えてしまっていたけれど、俺を呼んでくれたのはキミだ」
line = "「マトイ、すまない。みんなが望んでくれるから、つい応えてしまっていたけれど、俺を呼んでくれたのはキミだ」"

[[dialogue]]
speaker = "マトイ"
# 「ちょっ……きゃっ！？　今度は何～！？」
line = "「ちょっ……きゃっ！？　今度は何～！？」"

[[dialogue]]
speaker = "unk"
# 会長の影はマトイをお姫様抱っこすると、告げる。
line = "会長の影はマトイをお姫様抱っこすると、告げる。"

[[dialogue]]
speaker = "煩悩クロト"
# 「――俺にとって、いちばん大切なお姫様はキミだよ（イケボ）」
line = "「――俺にとって、いちばん大切なお姫様はキミだよ（イケボ）」"

[[dialogue]]
speaker = "マトイ"
# 「ほああああああぁ～～～っ！？！？<emoji=heart04><emoji=heart04><emoji=heart04><emoji=heart04>」
line = "「ほああああああぁ～～～っ！？！？<emoji=heart04><emoji=heart04><emoji=heart04><emoji=heart04>」"

[[dialogue]]
speaker = "ルリエル"
# 「マトイさんが爆発して倒れたのです！」
line = "「マトイさんが爆発して倒れたのです！」"

[[dialogue]]
speaker = "トマル"
# 「なんとうらやま――いえ。おいたわしや、姉さま……」
line = "「なんとうらやま――いえ。おいたわしや、姉さま……」"

[[dialogue]]
speaker = "ミヤハル"
# 「ふふっ<emoji=heart04>　マトイはん、普通に見えて、えろう面白い煩悩を持ってはるねぇ<emoji=heart04>」
line = "「ふふっ<emoji=heart04>　マトイはん、普通に見えて、えろう面白い煩悩を持ってはるねぇ<emoji=heart04>」"

[[dialogue]]
speaker = "マトイ"
# 「う～ん……<emoji=heart04>」
line = "「う～ん……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 真っ赤な顔でのぼせながら、またしばらくダウンしてしまうマトイなのであった――
line = "真っ赤な顔でのぼせながら、またしばらくダウンしてしまうマトイなのであった――"
