[[dialogue]]
speaker = "unk"
# ここは──星徒会室？
line = "ここは──星徒会室？"

[[dialogue]]
speaker = "unk"
# おかしいです。私は、アステラの中でシュティレさんと一緒に戦っていたはず……
line = "おかしいです。私は、アステラの中でシュティレさんと一緒に戦っていたはず……"

[[dialogue]]
speaker = "サーシャ"
# 「あ～、よかった。書類がぜんぜん見つからなくて困ってたの。さっすがアナちゃんね～♪」
line = "「あ～、よかった。書類がぜんぜん見つからなくて困ってたの。さっすがアナちゃんね～♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふっふーん、当然よね！　アナがいないとうちの星徒会は１日も持たないんだから！」
line = "「ふっふーん、当然よね！　アナがいないとうちの星徒会は１日も持たないんだから！」"

[[dialogue]]
speaker = "マトイ"
# 「もう、アナにばっかり頼ったらダメだよ！　でもありがとうアナ、助かっちゃった」
line = "「もう、アナにばっかり頼ったらダメだよ！　でもありがとうアナ、助かっちゃった」"

[[dialogue]]
speaker = "アナ"
# 「ノープロブレム。補佐するのが私の役目です」
line = "「ノープロブレム。補佐するのが私の役目です」"

[[dialogue]]
speaker = "アナ"
# 「まあ、それとは別に、先輩方にはもう少ししっかりしていただきたいですが」
line = "「まあ、それとは別に、先輩方にはもう少ししっかりしていただきたいですが」"

[[dialogue]]
speaker = "サーシャ"
# 「そうよね～。私たち、何でもアナちゃんに頼りすぎだったかも」
line = "「そうよね～。私たち、何でもアナちゃんに頼りすぎだったかも」"

[[dialogue]]
speaker = "マトイ"
# 「反省しましょう、反省！」
line = "「反省しましょう、反省！」"

[[dialogue]]
speaker = "unk"
# ──違います。反省なんていりません。
line = "──違います。反省なんていりません。"

[[dialogue]]
speaker = "unk"
# だって私は、いつも先輩たちに、守ってもらっていました。
line = "だって私は、いつも先輩たちに、守ってもらっていました。"

[[dialogue]]
speaker = "サーシャ"
# 「大丈夫、アナちゃん！」
line = "「大丈夫、アナちゃん！」"

[[dialogue]]
speaker = "マトイ"
# 「遅れちゃってごめんね！　あとは私たちに任せておいて！」
line = "「遅れちゃってごめんね！　あとは私たちに任せておいて！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「よくもうちの可愛い後輩をいじめてくれたわね！　どっかーんと百倍返しよ！！」
line = "「よくもうちの可愛い後輩をいじめてくれたわね！　どっかーんと百倍返しよ！！」"

[[dialogue]]
speaker = "unk"
# ──いつも感謝していました。口に出したこと、ありませんでしたけれど。
line = "──いつも感謝していました。口に出したこと、ありませんでしたけれど。"

[[dialogue]]
speaker = "unk"
# 私にとって、あなたたちは憧れそのもの。
line = "私にとって、あなたたちは憧れそのもの。"

[[dialogue]]
speaker = "unk"
# 優しい先輩。甘えられる先輩。頼りになる先輩。
line = "優しい先輩。甘えられる先輩。頼りになる先輩。"

[[dialogue]]
speaker = "unk"
# ──どんな時でも傍にいてくれる、大切な人たち。
line = "──どんな時でも傍にいてくれる、大切な人たち。"

[[dialogue]]
speaker = "unk"
# だから焦っていました。ノヴァフォームの存在を知ったその日から、大好きな先輩たちの足を引っ張っている思いが、日に日に膨らんでいきました。
line = "だから焦っていました。ノヴァフォームの存在を知ったその日から、大好きな先輩たちの足を引っ張っている思いが、日に日に膨らんでいきました。"

[[dialogue]]
speaker = "unk"
# 早くノヴァフォームに目覚めたい。迷惑な存在になりたくない。焦る、焦る、焦る──
line = "早くノヴァフォームに目覚めたい。迷惑な存在になりたくない。焦る、焦る、焦る──"

[[dialogue]]
speaker = "unk"
# ずっと焦り続けて、今日まで来ました──
line = "ずっと焦り続けて、今日まで来ました──"

[[dialogue]]
speaker = "シュティレ"
# 「──アナお姉ちゃん！　目を開けてください……！　しっかり……しっかりして……！」
line = "「──アナお姉ちゃん！　目を開けてください……！　しっかり……しっかりして……！」"

[[dialogue]]
speaker = "unk"
# これは、シュティレさんの声……？
line = "これは、シュティレさんの声……？"

[[dialogue]]
speaker = "アナ"
# 「ああ──そっか」
line = "「ああ──そっか」"

[[dialogue]]
speaker = "アナ"
# 「私、戦い続けて、倒れて……」
line = "「私、戦い続けて、倒れて……」"

[[dialogue]]
speaker = "unk"
# 早く戻らないと──あの子を守らないと。
line = "早く戻らないと──あの子を守らないと。"

[[dialogue]]
speaker = "unk"
# 大好きな先輩に失望されるだなんていう、くだらない焦りよりももっと強い思いが胸に宿る。
line = "大好きな先輩に失望されるだなんていう、くだらない焦りよりももっと強い思いが胸に宿る。"

[[dialogue]]
speaker = "unk"
# 自分を慕ってくれる後輩を守りたい。
line = "自分を慕ってくれる後輩を守りたい。"

[[dialogue]]
speaker = "unk"
# 私の焦りなんてどうでもいい。どうでもいいんです──
line = "私の焦りなんてどうでもいい。どうでもいいんです──"

[[dialogue]]
speaker = "unk"
# 大切なものを守る力を、どうか、私に──
line = "大切なものを守る力を、どうか、私に──"

[[dialogue]]
speaker = "unk"
# ──アナ！！！！
line = "──アナ！！！！"

[[dialogue]]
speaker = "アナ"
# 「あ──」
line = "「あ──」"

[[dialogue]]
speaker = "unk"
# 会長の声が聞こえる。
line = "会長の声が聞こえる。"

[[dialogue]]
speaker = "unk"
# 今ならいける──輝きが見える！！
line = "今ならいける──輝きが見える！！"

[[dialogue]]
speaker = "unk"
# よく頑張ったな……！！
line = "よく頑張ったな……！！"

[[dialogue]]
speaker = "unk"
# 輝き？
line = "輝き？"

[[dialogue]]
speaker = "unk"
# それは──私の、新しい力……？
line = "それは──私の、新しい力……？"

[[dialogue]]
speaker = "アナ"
# 「──はい」
line = "「──はい」"

[[dialogue]]
speaker = "アナ"
# 「お願いします、会長……！！」
line = "「お願いします、会長……！！」"

[[dialogue]]
speaker = "unk"
# アルケインノヴァ……エクストリーム！！
line = "アルケインノヴァ……エクストリーム！！"

[[dialogue]]
speaker = "unk"
# 俺は持てる全ての魔王の力を込めて、アナの中に宿る輝きに触れた。
line = "俺は持てる全ての魔王の力を込めて、アナの中に宿る輝きに触れた。"

[[dialogue]]
speaker = "unk"
# そして降り立つ──覚醒した火星の天使が。
line = "そして降り立つ──覚醒した火星の天使が。"

[[dialogue]]
speaker = "アナ（覚醒）"
# 「──しゅわっち。遅いですよ、会長」
line = "「──しゅわっち。遅いですよ、会長」"

[[dialogue]]
speaker = "unk"
# アナ、気が付いたか……！
line = "アナ、気が付いたか……！"

[[dialogue]]
speaker = "アナ（覚醒）"
# 「……危ない所でした。ああいうのが走馬灯って言うんでしょうか。でも、もう問題ありません。戦線に復帰します」
line = "「……危ない所でした。ああいうのが走馬灯って言うんでしょうか。でも、もう問題ありません。戦線に復帰します」"

[[dialogue]]
speaker = "シュティレ"
# 「アナお姉ちゃん、怪我が治って……さっきとは比較にならない星力を……これが、ノヴァフォーム？」
line = "「アナお姉ちゃん、怪我が治って……さっきとは比較にならない星力を……これが、ノヴァフォーム？」"

[[dialogue]]
speaker = "アナ（覚醒）"
# 「ご心配をおかけしました、シュティレさん。さぁ、反撃開始です」
line = "「ご心配をおかけしました、シュティレさん。さぁ、反撃開始です」"

[[dialogue]]
speaker = "モンスター"
# 「ガァァァアア──！！」
line = "「ガァァァアア──！！」"

[[dialogue]]
speaker = "アナ（覚醒）"
# 「突破します──エクスプロージョン・オメガ！」
line = "「突破します──エクスプロージョン・オメガ！」"

[[dialogue]]
speaker = "モンスター"
# 「ギィィイイ──！？」
line = "「ギィィイイ──！？」"

[[dialogue]]
speaker = "シュティレ"
# 「さっきまであんなに手こずっていたのに……星力総量、解析不能レベル！」
line = "「さっきまであんなに手こずっていたのに……星力総量、解析不能レベル！」"

[[dialogue]]
speaker = "アナ（覚醒）"
# 「アステラを破壊しましょう。会長がここにいるということは、外はアニマ先輩が戦ってくれているんですよね？」
line = "「アステラを破壊しましょう。会長がここにいるということは、外はアニマ先輩が戦ってくれているんですよね？」"

[[dialogue]]
speaker = "unk"
# ああ！
line = "ああ！"

[[dialogue]]
speaker = "アナ（覚醒）"
# 「それではいきます。プラネットマルス・ノヴァ──セット！！」
line = "「それではいきます。プラネットマルス・ノヴァ──セット！！」"

[[dialogue]]
speaker = "unk"
# アナの放った炎熱の弓矢が、アステライトを内部から粉砕していく──！
line = "アナの放った炎熱の弓矢が、アステライトを内部から粉砕していく──！"

[[dialogue]]
speaker = "ギガンドム"
# 「グギギ──ギ──！」
line = "「グギギ──ギ──！」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「やれやれ、大概しつこいナ、キミ。アニマの火力だけじゃあトドメまでは刺せないカ──って？」
line = "「やれやれ、大概しつこいナ、キミ。アニマの火力だけじゃあトドメまでは刺せないカ──って？」"

[[dialogue]]
speaker = "アナ（覚醒）"
# 「本日２度目のしゅわっち」
line = "「本日２度目のしゅわっち」"

[[dialogue]]
speaker = "シュティレ"
# 「私もしゅわっち。遅れてすみません、マスター」
line = "「私もしゅわっち。遅れてすみません、マスター」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「フヒ！　ずいぶんおめかししたナ、アナ？　シュティレも無事でなによりダ」
line = "「フヒ！　ずいぶんおめかししたナ、アナ？　シュティレも無事でなによりダ」"

[[dialogue]]
speaker = "アナ（覚醒）"
# 「そういうアニマ先輩こそ。お互い、実りのある戦いだったようです」
line = "「そういうアニマ先輩こそ。お互い、実りのある戦いだったようです」"

[[dialogue]]
speaker = "アニマ（覚醒）"
# 「うむ、それじゃあ幕引きと行こうカ？」
line = "「うむ、それじゃあ幕引きと行こうカ？」"

[[dialogue]]
speaker = "シュティレ"
# 「はい、シュティレもお手伝いいたします」
line = "「はい、シュティレもお手伝いいたします」"

[[dialogue]]
speaker = "unk"
# よし──行くぞ！！
line = "よし──行くぞ！！"

[[dialogue]]
speaker = "unk"
# 俺たち４人は、決着をつけるためのギガンドムへ突撃する。
line = "俺たち４人は、決着をつけるためのギガンドムへ突撃する。"

[[dialogue]]
speaker = "アナ（覚醒）"
# 「カーマイン・アロー……シュート！！」
line = "「カーマイン・アロー……シュート！！」"
