[[dialogue]]
speaker = "セーラ"
# 「店内にあったカードデックはこれで全部だね」
line = "「店内にあったカードデックはこれで全部だね」"

[[dialogue]]
speaker = "ユウリ"
# 「見たところなんの変哲もない普通のカードっすけど……」
line = "「見たところなんの変哲もない普通のカードっすけど……」"

[[dialogue]]
speaker = "ユーリス"
# 「状況から考えておそらく」
line = "「状況から考えておそらく」"

[[dialogue]]
speaker = "unk"
# でも確かめる方法がないな
line = "でも確かめる方法がないな"

[[dialogue]]
speaker = "セーラ"
# 「水でもぶっかけてみる？」
line = "「水でもぶっかけてみる？」"

[[dialogue]]
speaker = "ユウリ"
# 「いや、予想が外れてたら問題っすよ。カードが全部ビショビショになるのはちょっと」
line = "「いや、予想が外れてたら問題っすよ。カードが全部ビショビショになるのはちょっと」"

[[dialogue]]
speaker = "ユーリス"
# 「擬態をとかせる方法、か。あの勇者スキルを使えばあるいは……」
line = "「擬態をとかせる方法、か。あの勇者スキルを使えばあるいは……」"

[[dialogue]]
speaker = "ユウリ"
# 「何か考えがあんのか？」
line = "「何か考えがあんのか？」"

[[dialogue]]
speaker = "ユーリス"
# 「うん。だけどひとつ問題がある。このスキルを十全に使うには、セーラさんとユウリさんの協力が必要なんだ」
line = "「うん。だけどひとつ問題がある。このスキルを十全に使うには、セーラさんとユウリさんの協力が必要なんだ」"

[[dialogue]]
speaker = "セーラ"
# 「協力？　オッケーオッケー、うちに任せて♪」
line = "「協力？　オッケーオッケー、うちに任せて♪」"

[[dialogue]]
speaker = "ユウリ"
# 「……なんか猛烈に嫌な予感がしてきた」
line = "「……なんか猛烈に嫌な予感がしてきた」"

[[dialogue]]
speaker = "ユーリス"
# 「えっとね──」
line = "「えっとね──」"

[[dialogue]]
speaker = "ユーリス"
# 「それじゃ行くよ！　勇者スキル──『色仕掛け』！！」
line = "「それじゃ行くよ！　勇者スキル──『色仕掛け』！！」"

[[dialogue]]
speaker = "セーラ"
# 「う・ち・と・イイコト、しよ<emoji=heart04>」
line = "「う・ち・と・イイコト、しよ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# カードが動いた！
line = "カードが動いた！"

[[dialogue]]
speaker = "ユーリス"
# 「やっぱりカードに擬態していたんだ！　この調子でみんなでスキルを使い続ければ正体をあらわすはずだよ！」
line = "「やっぱりカードに擬態していたんだ！　この調子でみんなでスキルを使い続ければ正体をあらわすはずだよ！」"

[[dialogue]]
speaker = "セーラ"
# 「んならお次はユーリスくん、いやユリアーナちゃん！　いっちゃって～！」
line = "「んならお次はユーリスくん、いやユリアーナちゃん！　いっちゃって～！」"

[[dialogue]]
speaker = "ユーリス"
# 「正直、自信はないけど……！」
line = "「正直、自信はないけど……！」"

[[dialogue]]
speaker = "ユーリス"
# 「会長っ──んっ、ちゅっ……<emoji=heart04>」
line = "「会長っ──んっ、ちゅっ……<emoji=heart04>」"

[[dialogue]]
speaker = "セーラ"
# 「おお……！　投げキッスでめっちゃガタガタしとるっ」
line = "「おお……！　投げキッスでめっちゃガタガタしとるっ」"

[[dialogue]]
speaker = "unk"
# よし、ユウリがトドメだ！
line = "よし、ユウリがトドメだ！"

[[dialogue]]
speaker = "ユウリ"
# 「あ、あたしはしねえっ！　絶対しねえっ！！　つかなんだ勇者スキル『色仕掛け』って！？」
line = "「あ、あたしはしねえっ！　絶対しねえっ！！　つかなんだ勇者スキル『色仕掛け』って！？」"

[[dialogue]]
speaker = "ユーリス"
# 「何人も色香に惑わされている時は決して隠し事はできない。その昔、聖剣の使い手はこのスキルを以て、自らに近づく敵国の女性を逆に籠絡して──」
line = "「何人も色香に惑わされている時は決して隠し事はできない。その昔、聖剣の使い手はこのスキルを以て、自らに近づく敵国の女性を逆に籠絡して──」"

[[dialogue]]
speaker = "ユウリ"
# 「解説を求めてるわけじゃねえよ！？　そもそもなんでモンスターに色仕掛けなんて効くんだよ！？」
line = "「解説を求めてるわけじゃねえよ！？　そもそもなんでモンスターに色仕掛けなんて効くんだよ！？」"

[[dialogue]]
speaker = "ユーリス"
# 「『早着替え』と同じように、スキルにまで昇華された技は単なる『色仕掛け』に留まらない力を持つ。つまり一種の星術になっているんだ」
line = "「『早着替え』と同じように、スキルにまで昇華された技は単なる『色仕掛け』に留まらない力を持つ。つまり一種の星術になっているんだ」"

[[dialogue]]
speaker = "ユウリ"
# 「ほんとにどうなってんだよその聖剣は！？」
line = "「ほんとにどうなってんだよその聖剣は！？」"

[[dialogue]]
speaker = "セーラ"
# 「いいからやりなって。モンスターの正体を暴くためじゃーん。何が減るわけでもないんだからさ？」
line = "「いいからやりなって。モンスターの正体を暴くためじゃーん。何が減るわけでもないんだからさ？」"

[[dialogue]]
speaker = "ユウリ"
# 「うぐぐ……ぐ……そういう問題じゃあ……」
line = "「うぐぐ……ぐ……そういう問題じゃあ……」"

[[dialogue]]
speaker = "ユーリス"
# 「ちなみにこの『色仕掛け』を伝えたのは『早着替え』を伝えた王子と同一人物だよ。彼の時代は長いジルラント史の中でも特に策謀行き交う波乱の時世だったらしくて──」
line = "「ちなみにこの『色仕掛け』を伝えたのは『早着替え』を伝えた王子と同一人物だよ。彼の時代は長いジルラント史の中でも特に策謀行き交う波乱の時世だったらしくて──」"

[[dialogue]]
speaker = "ユウリ"
# 「それもどうでもいいっつの！！」
line = "「それもどうでもいいっつの！！」"

[[dialogue]]
speaker = "セーラ"
# 「恥ずかしがらずに恥ずかしがらずに。自分が思うかわいいポーズなりセリフなり言えばいいだけじゃーん」
line = "「恥ずかしがらずに恥ずかしがらずに。自分が思うかわいいポーズなりセリフなり言えばいいだけじゃーん」"

[[dialogue]]
speaker = "ユウリ"
# 「か、かわいいポーズとかセリフとか言われても……！　つか会長さんもやってねえし……！」
line = "「か、かわいいポーズとかセリフとか言われても……！　つか会長さんもやってねえし……！」"

[[dialogue]]
speaker = "セーラ"
# 「や。会長さんの色仕掛けに需要ないっしょ」
line = "「や。会長さんの色仕掛けに需要ないっしょ」"

[[dialogue]]
speaker = "unk"
# 必要とあらば……脱ぎましょうか？
line = "必要とあらば……脱ぎましょうか？"

[[dialogue]]
speaker = "ユウリ"
# 「脱ぐな脱ぐな脱ぐな！！　イかれてんのか！？　せめて脱ぐなら上から脱ごうとしろや！？」
line = "「脱ぐな脱ぐな脱ぐな！！　イかれてんのか！？　せめて脱ぐなら上から脱ごうとしろや！？」"

[[dialogue]]
speaker = "ユーリス"
# 「ユウリさん……！　モンスターを倒すためにも、君の助力がどうしても必要なんだ……！」
line = "「ユウリさん……！　モンスターを倒すためにも、君の助力がどうしても必要なんだ……！」"

[[dialogue]]
speaker = "セーラ"
# 「ユウリちゃん……！　星騎士の誇りを思い出して……！」
line = "「ユウリちゃん……！　星騎士の誇りを思い出して……！」"

[[dialogue]]
speaker = "ユウリ"
# 「～～っっ！　く、くそがっ……！　やりゃあいいんだろ、やりゃあ！！」
line = "「～～っっ！　く、くそがっ……！　やりゃあいいんだろ、やりゃあ！！」"

[[dialogue]]
speaker = "ユウリ"
# 「あ……あたしと……」
line = "「あ……あたしと……」"

[[dialogue]]
speaker = "ユーリス・セーラ"
# 「あたしと？」
line = "「あたしと？」"

[[dialogue]]
speaker = "ユウリ"
# 「あたしと──ウサちゃんダンス、踊ろうピョンっ♪」
line = "「あたしと──ウサちゃんダンス、踊ろうピョンっ♪」"

[[dialogue]]
speaker = "unk"
# 正体をあらわしたぞ！
line = "正体をあらわしたぞ！"

[[dialogue]]
speaker = "セーラ"
# 「おおー……ホントにあらわれるとは。ユウリちゃんのウサちゃんダンスがよっぽど気に入ったっぽいピョン？」
line = "「おおー……ホントにあらわれるとは。ユウリちゃんのウサちゃんダンスがよっぽど気に入ったっぽいピョン？」"

[[dialogue]]
speaker = "ユーリス"
# 「とても可愛らしかったからね。あまりの魅力に私の心もピョンピョン飛び跳ねそうだったよ」
line = "「とても可愛らしかったからね。あまりの魅力に私の心もピョンピョン飛び跳ねそうだったよ」"

[[dialogue]]
speaker = "ユウリ"
# 「言うな……！　みんなしてピョンピョン言うなぁ……！！」
line = "「言うな……！　みんなしてピョンピョン言うなぁ……！！」"

[[dialogue]]
speaker = "セーラ"
# 「うわっと！　めっちゃ興奮してんじゃん！　こりゃガチでいかないとヤバそうだね～」
line = "「うわっと！　めっちゃ興奮してんじゃん！　こりゃガチでいかないとヤバそうだね～」"

[[dialogue]]
speaker = "ユーリス"
# 「ならショーダウンといこうか。今更フォールドは受け付けないよ」
line = "「ならショーダウンといこうか。今更フォールドは受け付けないよ」"

[[dialogue]]
speaker = "ユウリ"
# 「元はと言や、全部このモンスターのせいじゃねえか……。こんな恥ずかしい格好させられたのも、あんな恥ずかしい真似させられたのも……」
line = "「元はと言や、全部このモンスターのせいじゃねえか……。こんな恥ずかしい格好させられたのも、あんな恥ずかしい真似させられたのも……」"

[[dialogue]]
speaker = "ユウリ"
# 「絶対に許さねえ……！　一枚残らずズタズタに引き裂いて、細切れにして、焼却処分してやるっ……！！」
line = "「絶対に許さねえ……！　一枚残らずズタズタに引き裂いて、細切れにして、焼却処分してやるっ……！！」"

[[dialogue]]
speaker = "ユウリ"
# 「あと早着替えと色仕掛けなんてアホスキルを伝えた王子もぶっ殺すっ！！」
line = "「あと早着替えと色仕掛けなんてアホスキルを伝えた王子もぶっ殺すっ！！」"

[[dialogue]]
speaker = "unk"
# 行くぞ、みんな！
line = "行くぞ、みんな！"

[[dialogue]]
speaker = "セーラ"
# 「うん！　星徒会＆王子チームの力、今度こそ見せてあげちゃうよ！」
line = "「うん！　星徒会＆王子チームの力、今度こそ見せてあげちゃうよ！」"
