[[dialogue]]
speaker = "ナナカ"
# 「あーーーっ！　こんなところにいたっ！」
line = "「あーーーっ！　こんなところにいたっ！」"

[[dialogue]]
speaker = "unk"
# ん……？
line = "ん……？"

[[dialogue]]
speaker = "ナナカ"
# 「や～っと見つけたよ、ロロちゃん！」
line = "「や～っと見つけたよ、ロロちゃん！」"

[[dialogue]]
speaker = "ルリエル？"
# 「はて……？」
line = "「はて……？」"

[[dialogue]]
speaker = "フィオナ"
# 「誰でしょう、見慣れない人ですけど……」
line = "「誰でしょう、見慣れない人ですけど……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あれは……！」
line = "「あれは……！」"

[[dialogue]]
speaker = "ナナカ"
# 「ったくも～、勝手にフラフラいなくなるんじゃないよ！」
line = "「ったくも～、勝手にフラフラいなくなるんじゃないよ！」"

[[dialogue]]
speaker = "ナナカ"
# 「ただでさえ、気づけば全然知らない場所で、まわりは知らない人ばっかで、めちゃくちゃ困ってるってのにさ！」
line = "「ただでさえ、気づけば全然知らない場所で、まわりは知らない人ばっかで、めちゃくちゃ困ってるってのにさ！」"

[[dialogue]]
speaker = "ルリエル？"
# 「ひええっ、なんなんですかっ、急に怒鳴らないで下さいよ～！」
line = "「ひええっ、なんなんですかっ、急に怒鳴らないで下さいよ～！」"

[[dialogue]]
speaker = "ナナカ"
# 「あたふたしたいのはこっちだってんでい！　一体ここはどこなのさ～！」
line = "「あたふたしたいのはこっちだってんでい！　一体ここはどこなのさ～！」"

[[dialogue]]
speaker = "フィオナ"
# 「あ、ちょっと待って下さい。あの制服は……！」
line = "「あ、ちょっと待って下さい。あの制服は……！」"

[[dialogue]]
speaker = "unk"
# もしかして！
line = "もしかして！"

[[dialogue]]
speaker = "ヴィーナス"
# 「ね、やっぱり、そう思うわよねっ」
line = "「ね、やっぱり、そう思うわよねっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あなた、もしかして……ううん、絶対そうだわ！　私の勘がそう告げてるもの！」
line = "「あなた、もしかして……ううん、絶対そうだわ！　私の勘がそう告げてるもの！」"

[[dialogue]]
speaker = "ナナカ"
# 「えっ！？　ななな、なにさいきなり……あんたたち、どちらさん？」
line = "「えっ！？　ななな、なにさいきなり……あんたたち、どちらさん？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私は九浄ヴィーナス。新星学園所属の星騎士なの。で、こっちが星徒会長の──」
line = "「私は九浄ヴィーナス。新星学園所属の星騎士なの。で、こっちが星徒会長の──」"

[[dialogue]]
speaker = "unk"
# 緋宮クロトです
line = "緋宮クロトです"

[[dialogue]]
speaker = "フィオナ"
# 「私は、この流星学園で星徒会長を務めている、星見フィオナと申します」
line = "「私は、この流星学園で星徒会長を務めている、星見フィオナと申します」"

[[dialogue]]
speaker = "ヴィーナス"
# 「いきなりでびっくりするかもしれないけど、私たち多分、あなたの事情をわかってあげられると思うわ」
line = "「いきなりでびっくりするかもしれないけど、私たち多分、あなたの事情をわかってあげられると思うわ」"

[[dialogue]]
speaker = "ナナカ"
# 「え、待って待って、どういうこと……？　流星学園？　てか、九浄！？　もしかして、リア先輩の親戚とか？」
line = "「え、待って待って、どういうこと……？　流星学園？　てか、九浄！？　もしかして、リア先輩の親戚とか？」"

[[dialogue]]
speaker = "フィオナ"
# 「その反応、やはり……！」
line = "「その反応、やはり……！」"

[[dialogue]]
speaker = "ナナカ"
# 「アタシのことも、知ってるわけ？　ごめん、どっかで会ったことあったっけ……？」
line = "「アタシのことも、知ってるわけ？　ごめん、どっかで会ったことあったっけ……？」"

[[dialogue]]
speaker = "フィオナ"
# 「いえ、そういうわけではないのですが……きっと、見知らぬ場所に飛ばされて、お困りなのではないか、と」
line = "「いえ、そういうわけではないのですが……きっと、見知らぬ場所に飛ばされて、お困りなのではないか、と」"

[[dialogue]]
speaker = "ナナカ"
# 「おっ、察しがよくて助かる～！　ってか、アタシらも名乗らないとね」
line = "「おっ、察しがよくて助かる～！　ってか、アタシらも名乗らないとね」"

[[dialogue]]
speaker = "ナナカ"
# 「アタシは夕霧ナナカ。で、そっちがロロット」
line = "「アタシは夕霧ナナカ。で、そっちがロロット」"

[[dialogue]]
speaker = "ヴィーナス"
# 「えっと……ルリエルのこと？」
line = "「えっと……ルリエルのこと？」"

[[dialogue]]
speaker = "ナナカ"
# 「ルリエルぅ？　どっからどう見ても、ロロット・ローゼンクロイツでしょ。あたしたちの仲間で、生徒会の書記のさ」
line = "「ルリエルぅ？　どっからどう見ても、ロロット・ローゼンクロイツでしょ。あたしたちの仲間で、生徒会の書記のさ」"

[[dialogue]]
speaker = "ルリエル？"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "ナナカ"
# 「へ？」
line = "「へ？」"

[[dialogue]]
speaker = "ルリエル？"
# 「あのっ、人違いですっ。ロロットさんなんて知りませんっ。わたしは、ルリエルですっ！」
line = "「あのっ、人違いですっ。ロロットさんなんて知りませんっ。わたしは、ルリエルですっ！」"

[[dialogue]]
speaker = "ナナカ"
# 「えーっ！？　どうしちゃったのさ、なんか変だよロロちゃん。いや、確かに、いつもちょっと変なところはあったけどさっ」
line = "「えーっ！？　どうしちゃったのさ、なんか変だよロロちゃん。いや、確かに、いつもちょっと変なところはあったけどさっ」"

[[dialogue]]
speaker = "ルリエル？"
# 「むむっ、あなたも失礼ですねっ」
line = "「むむっ、あなたも失礼ですねっ」"

[[dialogue]]
speaker = "ナナカ"
# 「だけどほら、その豚の貯金箱、トントロを持ってるのが証拠だよ！」
line = "「だけどほら、その豚の貯金箱、トントロを持ってるのが証拠だよ！」"

[[dialogue]]
speaker = "ルリエル？"
# 「もももっ、持ってませ～ん！」
line = "「もももっ、持ってませ～ん！」"

[[dialogue]]
speaker = "ルリエル？"
# 「ひえええっ！？」
line = "「ひえええっ！？」"

[[dialogue]]
speaker = "ナナカ"
# 「ほらぁ、ドジだし」
line = "「ほらぁ、ドジだし」"

[[dialogue]]
speaker = "ルリエル？"
# 「ドジじゃありませ～ん！」
line = "「ドジじゃありませ～ん！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「んん～……？　この感じ……やっぱり、なんだか以前にも、似たようなことがあったような……」
line = "「んん～……？　この感じ……やっぱり、なんだか以前にも、似たようなことがあったような……」"

[[dialogue]]
speaker = "ナナカ"
# 「えっ、もしかして、ロロちゃんがこうなっちゃった心当たり、なんかあるの？」
line = "「えっ、もしかして、ロロちゃんがこうなっちゃった心当たり、なんかあるの？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「……はっ！　そうよ、前にもリクリエの影響で、ルリエルがこんなふうになってたじゃない！」
line = "「……はっ！　そうよ、前にもリクリエの影響で、ルリエルがこんなふうになってたじゃない！」"

[[dialogue]]
speaker = "フィオナ"
# 「あ……そうでした！　私たちはまた、認識改変の影響を受けていた、ということですか……！？　不覚ですっ」
line = "「あ……そうでした！　私たちはまた、認識改変の影響を受けていた、ということですか……！？　不覚ですっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「でも、ナナカと話してる内に、思い出せるようになったわよね？　なんで？」
line = "「でも、ナナカと話してる内に、思い出せるようになったわよね？　なんで？」"

[[dialogue]]
speaker = "フィオナ"
# 「影響を受けていないナナカさんの干渉で、認識改変が綻びた、という感じでしょうか」
line = "「影響を受けていないナナカさんの干渉で、認識改変が綻びた、という感じでしょうか」"

[[dialogue]]
speaker = "ナナカ"
# 「え、アタシ、なんかやっちゃいました……？」
line = "「え、アタシ、なんかやっちゃいました……？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「前にもね、私たちの仲間の様子がおかしくなったことがあったの。もう大変だったんだから」
line = "「前にもね、私たちの仲間の様子がおかしくなったことがあったの。もう大変だったんだから」"

[[dialogue]]
speaker = "ルリエル？"
# 「認識改変……？　何を言っているんですか！　わたしは変でもおかしくもありませ～ん！」
line = "「認識改変……？　何を言っているんですか！　わたしは変でもおかしくもありませ～ん！」"

[[dialogue]]
speaker = "ナナカ"
# 「じゃあ、元に戻す方法、知ってるの？」
line = "「じゃあ、元に戻す方法、知ってるの？」"

[[dialogue]]
speaker = "フィオナ"
# 「そのためにもまずは、彼女に少し落ち着いてもらう必要があるかと……」
line = "「そのためにもまずは、彼女に少し落ち着いてもらう必要があるかと……」"

[[dialogue]]
speaker = "ルリエル？"
# 「むむむ～っ、落ち着くのは皆さんの方ですよ！」
line = "「むむむ～っ、落ち着くのは皆さんの方ですよ！」"

[[dialogue]]
speaker = "ルリエル？"
# 「原因はよくわかりませんが、どうやら皆さん、正気ではないご様子……」
line = "「原因はよくわかりませんが、どうやら皆さん、正気ではないご様子……」"

[[dialogue]]
speaker = "ルリエル？"
# 「仕方ありません。ここはわたしが、皆さんの目を覚まさせてあげましょう！」
line = "「仕方ありません。ここはわたしが、皆さんの目を覚まさせてあげましょう！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ふ～ん、意外と手強そうね……！」
line = "「ふ～ん、意外と手強そうね……！」"

[[dialogue]]
speaker = "ナナカ"
# 「てやんでい！」
line = "「てやんでい！」"

[[dialogue]]
speaker = "フィオナ"
# 「て、てやんでい……？」
line = "「て、てやんでい……？」"

[[dialogue]]
speaker = "ナナカ"
# 「ったく、しゃーないね！　なんだかよくわかんないけど、そういうことなら任せときな！」
line = "「ったく、しゃーないね！　なんだかよくわかんないけど、そういうことなら任せときな！」"

[[dialogue]]
speaker = "ナナカ"
# 「ちょ～っと手荒だけど、力ずくでもおとなしくしてもらうよ！」
line = "「ちょ～っと手荒だけど、力ずくでもおとなしくしてもらうよ！」"

[[dialogue]]
speaker = "ルリエル？"
# 「いいでしょう、身の程をわきまえて下さ～い！」
line = "「いいでしょう、身の程をわきまえて下さ～い！」"
