[[dialogue]]
speaker = "unk"
# ヴィーナス発案のサンタ大作戦に、元気よく名乗りを上げた紅明。
line = "ヴィーナス発案のサンタ大作戦に、元気よく名乗りを上げた紅明。"

[[dialogue]]
speaker = "紅明"
# 「アタシもクリスマスプレゼントを配るの、手伝うぜ！」
line = "「アタシもクリスマスプレゼントを配るの、手伝うぜ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「紅明も手を貸してくれるの？　それなら、牛に翼を得たる如しね！」
line = "「紅明も手を貸してくれるの？　それなら、牛に翼を得たる如しね！」"

[[dialogue]]
speaker = "紅明"
# 「実はさ、偶然にもアタシも今度のクリスマスパーティーでサンタをやりたいって思って、ダーリンに許可を貰いにきたところだったんだよね☆」
line = "「実はさ、偶然にもアタシも今度のクリスマスパーティーでサンタをやりたいって思って、ダーリンに許可を貰いにきたところだったんだよね☆」"

[[dialogue]]
speaker = "紅明"
# 「そこでみんなにクリスマスプレゼントを配ったら、笑顔になるじゃん？　アタシ、みんなの笑顔を見るのが好きだからさ！」
line = "「そこでみんなにクリスマスプレゼントを配ったら、笑顔になるじゃん？　アタシ、みんなの笑顔を見るのが好きだからさ！」"

[[dialogue]]
speaker = "unk"
# 紅明らしいな
line = "紅明らしいな"

[[dialogue]]
speaker = "紅明"
# 「うしし♪　世の為人の為、がアタシのモットーだかんね♪　というわけで、ついでにセッシーの為にもなるなら、喜んで協力するぜ☆」
line = "「うしし♪　世の為人の為、がアタシのモットーだかんね♪　というわけで、ついでにセッシーの為にもなるなら、喜んで協力するぜ☆」"

[[dialogue]]
speaker = "セシア"
# 「じ～っ……」
line = "「じ～っ……」"

[[dialogue]]
speaker = "紅明"
# 「って、アタシの顔をじっと見つめて、どうかしたかい、セッシー？　もしかして、呼び方が不満だったかな？」
line = "「って、アタシの顔をじっと見つめて、どうかしたかい、セッシー？　もしかして、呼び方が不満だったかな？」"

[[dialogue]]
speaker = "紅明"
# 「アタシ、その場のノリで名づけちゃうから、たまに怒られちゃうんだよね～。もし嫌だったら、遠慮なく言ってくれな。アタシはセッシーと仲良くなりたいからさ♪」
line = "「アタシ、その場のノリで名づけちゃうから、たまに怒られちゃうんだよね～。もし嫌だったら、遠慮なく言ってくれな。アタシはセッシーと仲良くなりたいからさ♪」"

[[dialogue]]
speaker = "セシア"
# 「……見つけたわ。――あなたがわたくしのママね♪」
line = "「……見つけたわ。――あなたがわたくしのママね♪」"

[[dialogue]]
speaker = "紅明"
# 「え？　なんて？」
line = "「え？　なんて？」"

[[dialogue]]
speaker = "セシア"
# 「わ～い、紅明ママ～♪　セシアのことは、セッシーと呼んでくれていいわ♪　その代わり、わたくしも紅明ママと呼ぶわねっ」
line = "「わ～い、紅明ママ～♪　セシアのことは、セッシーと呼んでくれていいわ♪　その代わり、わたくしも紅明ママと呼ぶわねっ」"

[[dialogue]]
speaker = "unk"
# 急にどうした！？
line = "急にどうした！？"

[[dialogue]]
speaker = "紅明"
# 「えっと、セッシー？　アタシがママってどういう……？」
line = "「えっと、セッシー？　アタシがママってどういう……？」"

[[dialogue]]
speaker = "セシア"
# 「紅明ママからは内なる母性を感じるの！　まるで本当のママであったかのような、心に響くバブみが溢れてくるわ♪」
line = "「紅明ママからは内なる母性を感じるの！　まるで本当のママであったかのような、心に響くバブみが溢れてくるわ♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「出たわね！　セシアの『ママ判定』！」
line = "「出たわね！　セシアの『ママ判定』！」"

[[dialogue]]
speaker = "unk"
# ママ判定ってなに！？
line = "ママ判定ってなに！？"

[[dialogue]]
speaker = "ヴィーナス"
# 「セシアは、初めて会った相手をじ～っと観察して、自分のママに相応しい人物か判定する、面白い癖があるのよ！」
line = "「セシアは、初めて会った相手をじ～っと観察して、自分のママに相応しい人物か判定する、面白い癖があるのよ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうして見事『ママ認定』した相手に対しては、普段の落ち着いた態度から一変、無邪気な子供のように甘えちゃうの！」
line = "「そうして見事『ママ認定』した相手に対しては、普段の落ち着いた態度から一変、無邪気な子供のように甘えちゃうの！」"

[[dialogue]]
speaker = "セシア"
# 「――人はみな、自分のママになってくれる人を求めているのよ。わたくしはただ、人よりもその欲求に素直なだけだわ」
line = "「――人はみな、自分のママになってくれる人を求めているのよ。わたくしはただ、人よりもその欲求に素直なだけだわ」"

[[dialogue]]
speaker = "セシア"
# 「ねぇ、紅明ママ～♪　セシア、ママに抱っこして欲しいの～♪　ダメ～？」
line = "「ねぇ、紅明ママ～♪　セシア、ママに抱っこして欲しいの～♪　ダメ～？」"

[[dialogue]]
speaker = "unk"
# テンションの差っ！！
line = "テンションの差っ！！"

[[dialogue]]
speaker = "ヴィーナス"
# 「ちなみに私は、ママではないらしいわ！」
line = "「ちなみに私は、ママではないらしいわ！」"

[[dialogue]]
speaker = "セシア"
# 「――ちなみに、会長。あなたも残念ながら、ママではないわ」
line = "「――ちなみに、会長。あなたも残念ながら、ママではないわ」"

[[dialogue]]
speaker = "unk"
# いや俺、男なんだけどっ！！？
line = "いや俺、男なんだけどっ！！？"

[[dialogue]]
speaker = "セシア"
# 「甘いわね、会長。真のママに性別は関係ないわ。大事なのは、そこに<b>オギャれるバブみ</b>があるかどうかなのよ」
line = "「甘いわね、会長。真のママに性別は関係ないわ。大事なのは、そこに<b>オギャれるバブみ</b>があるかどうかなのよ」"

[[dialogue]]
speaker = "紅明"
# 「あははははっ♪　んモー、セッシーってば、ウケる～☆」
line = "「あははははっ♪　んモー、セッシーってば、ウケる～☆」"

[[dialogue]]
speaker = "紅明"
# 「そっかそっか、アタシに母性を感じるか～。うんうん、いいぜ？　アタシでよければ、セッシーのママ役、引き受けようじゃん♪」
line = "「そっかそっか、アタシに母性を感じるか～。うんうん、いいぜ？　アタシでよければ、セッシーのママ役、引き受けようじゃん♪」"

[[dialogue]]
speaker = "セシア"
# 「本当っ！？　わ～い、紅明ママ～♪　ありがと～♪」
line = "「本当っ！？　わ～い、紅明ママ～♪　ありがと～♪」"

[[dialogue]]
speaker = "紅明"
# 「よしよし、いいこいいこ♪　記憶を取り戻して、本当のママが見つかるまでの間、好きに甘えていいかんね～♪　ほ～ら、抱っこしちゃうぞ～☆」
line = "「よしよし、いいこいいこ♪　記憶を取り戻して、本当のママが見つかるまでの間、好きに甘えていいかんね～♪　ほ～ら、抱っこしちゃうぞ～☆」"

[[dialogue]]
speaker = "セシア"
# 「えへへ～♪　紅明ママのおっぱい、大きくて柔らか～い<emoji=heart04>　それに温かくて、落ち着くわ♪」
line = "「えへへ～♪　紅明ママのおっぱい、大きくて柔らか～い<emoji=heart04>　それに温かくて、落ち着くわ♪」"

[[dialogue]]
speaker = "unk"
# ママ判定の基準って、もしかして……
line = "ママ判定の基準って、もしかして……"

[[dialogue]]
speaker = "セシア"
# 「――いいえ。それは違うわ、会長」
line = "「――いいえ。それは違うわ、会長」"

[[dialogue]]
speaker = "セシア"
# 「母性とはもっと深淵なるものよ。必ずしもおっぱいの大きさで決まるわけではないわ。勘違いしないで頂戴。だけど――」
line = "「母性とはもっと深淵なるものよ。必ずしもおっぱいの大きさで決まるわけではないわ。勘違いしないで頂戴。だけど――」"

[[dialogue]]
speaker = "セシア"
# 「それはそれとして、大きなおっぱいはいいものよ。プラス１ポイントね」
line = "「それはそれとして、大きなおっぱいはいいものよ。プラス１ポイントね」"

[[dialogue]]
speaker = "紅明"
# 「こうしていると、私もママだった頃を思い出すな～。よしよし♪」
line = "「こうしていると、私もママだった頃を思い出すな～。よしよし♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ママだった頃？」
line = "「ママだった頃？」"

[[dialogue]]
speaker = "紅明"
# 「いや、なんでもないっしょ☆」
line = "「いや、なんでもないっしょ☆」"

[[dialogue]]
speaker = "紅明"
# 「とにかく、セッシー。アタシも手伝うから、クリスマスプレゼントを配るの、一緒に頑張ろうぜ♪」
line = "「とにかく、セッシー。アタシも手伝うから、クリスマスプレゼントを配るの、一緒に頑張ろうぜ♪」"

[[dialogue]]
speaker = "セシア"
# 「うんっ。これからよろしくね、紅明ママ♪」
line = "「うんっ。これからよろしくね、紅明ママ♪」"

[[dialogue]]
speaker = "unk"
# こうして、紅明もサンタ大作戦の仲間に加わるのだった。
line = "こうして、紅明もサンタ大作戦の仲間に加わるのだった。"
