[[dialogue]]
speaker = "ルネア"
# 「――これでよしっと」
line = "「――これでよしっと」"

[[dialogue]]
speaker = "ルネア"
# 「とりあえず、原因を特定する為の『自動解析霊術』を展開しておいたわ」
line = "「とりあえず、原因を特定する為の『自動解析霊術』を展開しておいたわ」"

[[dialogue]]
speaker = "ロロット"
# 「私たちはその間、何をすればいいのでしょう？」
line = "「私たちはその間、何をすればいいのでしょう？」"

[[dialogue]]
speaker = "ルネア"
# 「自動解析が終わるまでは、一旦待つしかないわね」
line = "「自動解析が終わるまでは、一旦待つしかないわね」"

[[dialogue]]
speaker = "ナナカ"
# 「それってどれくらいかかるもんなの？」
line = "「それってどれくらいかかるもんなの？」"

[[dialogue]]
speaker = "ルネア"
# 「大体、半日から、１日くらいってところかしら」
line = "「大体、半日から、１日くらいってところかしら」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「そういうことなら、私は異世界の子たちとは初対面だし、自己紹介をしておきたいわ♪」
line = "「そういうことなら、私は異世界の子たちとは初対面だし、自己紹介をしておきたいわ♪」"

[[dialogue]]
speaker = "unk"
# ヘレナさんは、俺たちの方へ向き直る。
line = "ヘレナさんは、俺たちの方へ向き直る。"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「改めまして、私は流星町の九浄家当主で、私立流星学園の理事長をやっている『九浄ヘレナ』よ。よろしくね♪」
line = "「改めまして、私は流星町の九浄家当主で、私立流星学園の理事長をやっている『九浄ヘレナ』よ。よろしくね♪」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「そ・れ・と、リアの『お姉ちゃん』をやっているわ♪　――えいっ<emoji=heart04>」
line = "「そ・れ・と、リアの『お姉ちゃん』をやっているわ♪　――えいっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# そう言って、ヘレナさんはリア先輩の背後へ回り込むと、脇の下から両手を伸ばして――
line = "そう言って、ヘレナさんはリア先輩の背後へ回り込むと、脇の下から両手を伸ばして――"

[[dialogue]]
speaker = "リア"
# 「ちょっ、お姉ちゃん！？　――きゃあっ！？」
line = "「ちょっ、お姉ちゃん！？　――きゃあっ！？」"

[[dialogue]]
speaker = "unk"
# 突然、リア先輩の胸を揉み始めた。
line = "突然、リア先輩の胸を揉み始めた。"

[[dialogue]]
speaker = "マトイ"
# 「へ、ヘレナさん！？　何をして……！？」
line = "「へ、ヘレナさん！？　何をして……！？」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「ふふっ♪　私たち姉妹のコミュニケーションよ<emoji=heart04>　ね～、リア？」
line = "「ふふっ♪　私たち姉妹のコミュニケーションよ<emoji=heart04>　ね～、リア？」"

[[dialogue]]
speaker = "リア"
# 「ち、違うの！　これは、お姉ちゃんがいつも、勝手にイタズラしてくるだけで～！」
line = "「ち、違うの！　これは、お姉ちゃんがいつも、勝手にイタズラしてくるだけで～！」"

[[dialogue]]
speaker = "リア"
# 「あ～ん！　恥ずかしいから、みんなの前で触るのやめて～！」
line = "「あ～ん！　恥ずかしいから、みんなの前で触るのやめて～！」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「ちなみに、今でもお風呂は一緒に入ってるのよ<emoji=heart04>」
line = "「ちなみに、今でもお風呂は一緒に入ってるのよ<emoji=heart04>」"

[[dialogue]]
speaker = "リア"
# 「それも、お姉ちゃんが勝手に入って来るからでしょ～！」
line = "「それも、お姉ちゃんが勝手に入って来るからでしょ～！」"

[[dialogue]]
speaker = "聖沙"
# 「お、お姉様とお風呂……<emoji=heart04>」
line = "「お、お姉様とお風呂……<emoji=heart04>」"

[[dialogue]]
speaker = "ナナカ"
# 「聖沙？　鼻血出てるよ、鼻血」
line = "「聖沙？　鼻血出てるよ、鼻血」"

[[dialogue]]
speaker = "聖沙"
# 「ハッ！？　べ、別にお姉様の破廉恥な姿を想像したわけじゃないんだからねっ！？」
line = "「ハッ！？　べ、別にお姉様の破廉恥な姿を想像したわけじゃないんだからねっ！？」"

[[dialogue]]
speaker = "unk"
# め、目のやり場に困る……
line = "め、目のやり場に困る……"

[[dialogue]]
speaker = "ロロット"
# 「異世会長さんも、副会長さんと同じで、ムッツリさんですね～」
line = "「異世会長さんも、副会長さんと同じで、ムッツリさんですね～」"

[[dialogue]]
speaker = "聖沙"
# 「ち、違うわよ！？　私はそんなんじゃないんだからっ！」
line = "「ち、違うわよ！？　私はそんなんじゃないんだからっ！」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「さてと、リアの胸も揉んで落ち着いたところで――」
line = "「さてと、リアの胸も揉んで落ち着いたところで――」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「改めて、もう１人の『九浄ヘレナ』さんとも、ちゃんと挨拶しないとね♪」
line = "「改めて、もう１人の『九浄ヘレナ』さんとも、ちゃんと挨拶しないとね♪」"

[[dialogue]]
speaker = "ヘレナ"
# 「そうであったな」
line = "「そうであったな」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「と言っても、ひと目見た時から、全然他人って感じがしなかったのよね～」
line = "「と言っても、ひと目見た時から、全然他人って感じがしなかったのよね～」"

[[dialogue]]
speaker = "ヘレナ"
# 「ああ。私は、そなたの『鏡映し』――」
line = "「ああ。私は、そなたの『鏡映し』――」"

[[dialogue]]
speaker = "ヘレナ"
# 「こちらの世界でも同じく、九浄家の当主と、新星学園の理事長を務めている」
line = "「こちらの世界でも同じく、九浄家の当主と、新星学園の理事長を務めている」"

[[dialogue]]
speaker = "ヘレナ"
# 「……そなたは、私という存在を見てどう思う？」
line = "「……そなたは、私という存在を見てどう思う？」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「う～ん、私としては――すごく気が合いそうで、嬉しいわね♪」
line = "「う～ん、私としては――すごく気が合いそうで、嬉しいわね♪」"

[[dialogue]]
speaker = "ヘレナ"
# 「そうか……ふふっ。私も同じだ」
line = "「そうか……ふふっ。私も同じだ」"

[[dialogue]]
speaker = "ヘレナ"
# 「同じ魂を持つ者だからな。会えたことに、心が高揚している」
line = "「同じ魂を持つ者だからな。会えたことに、心が高揚している」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「ふふっ、よかった♪　でも、１つ問題があるのよね～」
line = "「ふふっ、よかった♪　でも、１つ問題があるのよね～」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「私たち、同姓同名でしょ？　なんて呼んだらいいか、ちょっと迷っちゃわない？」
line = "「私たち、同姓同名でしょ？　なんて呼んだらいいか、ちょっと迷っちゃわない？」"

[[dialogue]]
speaker = "ヘレナ"
# 「それなら、私のことは『ヘレナちゃん』と呼ぶがよい。周りには、よくそう言っているのでな」
line = "「それなら、私のことは『ヘレナちゃん』と呼ぶがよい。周りには、よくそう言っているのでな」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「じゃあ、私のことは呼び捨てで、『ヘレナ』でいいわ♪」
line = "「じゃあ、私のことは呼び捨てで、『ヘレナ』でいいわ♪」"

[[dialogue]]
speaker = "ヘレナ（原作）"
# 「そういうことで――よろしくね、ヘレナちゃん♪」
line = "「そういうことで――よろしくね、ヘレナちゃん♪」"

[[dialogue]]
speaker = "ヘレナ"
# 「ああ。こちらこそ、よろしく頼む。ヘレナよ」
line = "「ああ。こちらこそ、よろしく頼む。ヘレナよ」"

[[dialogue]]
speaker = "unk"
# そう言って、２人のヘレナさんはにこやかに握手を交わす。
line = "そう言って、２人のヘレナさんはにこやかに握手を交わす。"

[[dialogue]]
speaker = "リア"
# 「ふふっ♪　お姉ちゃんたち、仲良くなれそうだね♪」
line = "「ふふっ♪　お姉ちゃんたち、仲良くなれそうだね♪」"

[[dialogue]]
speaker = "聖沙"
# 「マトイは、あれから元気にしてた？」
line = "「マトイは、あれから元気にしてた？」"

[[dialogue]]
speaker = "マトイ"
# 「はい、聖沙お姉様♪」
line = "「はい、聖沙お姉様♪」"

[[dialogue]]
speaker = "ナナカ"
# 「一応聞いてはいたけど……マトイが聖沙を『お姉様』呼びしてるのを見ると、同じ２年生だから変な感じだな～」
line = "「一応聞いてはいたけど……マトイが聖沙を『お姉様』呼びしてるのを見ると、同じ２年生だから変な感じだな～」"

[[dialogue]]
speaker = "unk"
# ちょっと不思議な感じだ
line = "ちょっと不思議な感じだ"

[[dialogue]]
speaker = "unk"
# 俺も４人が揃っているのを見ると
line = "俺も４人が揃っているのを見ると"

[[dialogue]]
speaker = "リア"
# 「あっ、そっか！　会長くんたちからしたら、私たち４人揃っては、これが初めてだもんね」
line = "「あっ、そっか！　会長くんたちからしたら、私たち４人揃っては、これが初めてだもんね」"

[[dialogue]]
speaker = "聖沙"
# 「最初は、私とリア先輩の２人だけで、会長たちと出会ったのよね」
line = "「最初は、私とリア先輩の２人だけで、会長たちと出会ったのよね」"

[[dialogue]]
speaker = "ロロット"
# 「その次に、私と会計さんの２人で、異世界へ行ったのです♪」
line = "「その次に、私と会計さんの２人で、異世界へ行ったのです♪」"

[[dialogue]]
speaker = "パッキー"
# 「俺様は、どっちの時もいたけどな！」
line = "「俺様は、どっちの時もいたけどな！」"

[[dialogue]]
speaker = "聖沙"
# 「パッキーさんは、どっちの時も操られて敵になってたけど……」
line = "「パッキーさんは、どっちの時も操られて敵になってたけど……」"

[[dialogue]]
speaker = "ナナカ"
# 「あははっ、確かに～♪」
line = "「あははっ、確かに～♪」"

[[dialogue]]
speaker = "パッキー"
# 「俺が操られてたのは、ルネアのせいだぜ！」
line = "「俺が操られてたのは、ルネアのせいだぜ！」"

[[dialogue]]
speaker = "ルネア"
# 「そ、それはこの前、ちゃんと理由を説明して謝ったじゃない！　悪かったわよ……！」
line = "「そ、それはこの前、ちゃんと理由を説明して謝ったじゃない！　悪かったわよ……！」"

[[dialogue]]
speaker = "リア"
# 「まあまあ。結果的に、ルネアちゃんのおかげで会長くんやマトイちゃんたちと出会えたわけだし、ね？」
line = "「まあまあ。結果的に、ルネアちゃんのおかげで会長くんやマトイちゃんたちと出会えたわけだし、ね？」"

[[dialogue]]
speaker = "ナナカ"
# 「そうですね。なんだかんだ、異世界に来れてすごく楽しかったし！」
line = "「そうですね。なんだかんだ、異世界に来れてすごく楽しかったし！」"

[[dialogue]]
speaker = "聖沙"
# 「おかげで、元の世界へ戻った後に、咲良クンの『羨ましい～』って顔を見ることができたわ♪」
line = "「おかげで、元の世界へ戻った後に、咲良クンの『羨ましい～』って顔を見ることができたわ♪」"

[[dialogue]]
speaker = "ロロット"
# 「……！　そうだ、いいことを思いついたのです！」
line = "「……！　そうだ、いいことを思いついたのです！」"

[[dialogue]]
speaker = "ロロット"
# 「どうせしばらく待つしかないのなら、その間、海で楽しく過ごしませんか？」
line = "「どうせしばらく待つしかないのなら、その間、海で楽しく過ごしませんか？」"

[[dialogue]]
speaker = "マトイ"
# 「え？　楽しく……？」
line = "「え？　楽しく……？」"

[[dialogue]]
speaker = "ロロット"
# 「はい♪　急いてはことを甘んじる、とも言いますし――」
line = "「はい♪　急いてはことを甘んじる、とも言いますし――」"

[[dialogue]]
speaker = "ロロット"
# 「会長さんが思わず起きてきたくなるくらい、『キラキラで楽しいバカンス』を過ごすのです！」
line = "「会長さんが思わず起きてきたくなるくらい、『キラキラで楽しいバカンス』を過ごすのです！」"

[[dialogue]]
speaker = "ナナカ"
# 「それ、いいかも！　シンは『キラキラな学園生活を送りたい』っていつも言ってるし！」
line = "「それ、いいかも！　シンは『キラキラな学園生活を送りたい』っていつも言ってるし！」"

[[dialogue]]
speaker = "聖沙"
# 「ロロットさん、やるわね……！　確かに、いいアイデアかもしれないわ」
line = "「ロロットさん、やるわね……！　確かに、いいアイデアかもしれないわ」"

[[dialogue]]
speaker = "リア"
# 「うんっ♪　私もいいと思う！」
line = "「うんっ♪　私もいいと思う！」"

[[dialogue]]
speaker = "リア"
# 「私たちが楽しそうにしていたら――」
line = "「私たちが楽しそうにしていたら――」"

[[dialogue]]
speaker = "リア"
# 「シンくんなら『僕も混ざりたい～！』って飛び起きてきそうな、そんな気がする♪」
line = "「シンくんなら『僕も混ざりたい～！』って飛び起きてきそうな、そんな気がする♪」"

[[dialogue]]
speaker = "聖沙"
# 「なら、みんなで、水遊びで勝負しましょう！」
line = "「なら、みんなで、水遊びで勝負しましょう！」"

[[dialogue]]
speaker = "ロロット"
# 「水遊び！　待ってました、なのです～♪」
line = "「水遊び！　待ってました、なのです～♪」"

[[dialogue]]
speaker = "unk"
# こうして俺たちは、ただ待つのではなく、やれることを積極的にしてみようと決めるのだった。
line = "こうして俺たちは、ただ待つのではなく、やれることを積極的にしてみようと決めるのだった。"
