[[dialogue]]
speaker = "リーリア"
# 「２人きりで抜け出しちゃいましたね、センパイ」
line = "「２人きりで抜け出しちゃいましたね、センパイ」"

[[dialogue]]
speaker = "クロト"
# 「ごめんね、急に誘ったりして」
line = "「ごめんね、急に誘ったりして」"

[[dialogue]]
speaker = "リーリア"
# 「何言ってるんですか。センパイから声をかけてくれて、マジカル嬉しかったですよ♪」
line = "「何言ってるんですか。センパイから声をかけてくれて、マジカル嬉しかったですよ♪」"

[[dialogue]]
speaker = "リーリア"
# 「あの～、ひとつお願いがあるんですけど……いいですか？」
line = "「あの～、ひとつお願いがあるんですけど……いいですか？」"

[[dialogue]]
speaker = "リーリア"
# 「せっかく誰も見てないですから……腕、組んでみたいなって……」
line = "「せっかく誰も見てないですから……腕、組んでみたいなって……」"

[[dialogue]]
speaker = "クロト"
# 「いいよ。はい、どうぞ」
line = "「いいよ。はい、どうぞ」"

[[dialogue]]
speaker = "リーリア"
# 「いいんですか！？　え～、どういう風の吹き回しです？　なんだかいつもより優しい気がするんですけど！？」
line = "「いいんですか！？　え～、どういう風の吹き回しです？　なんだかいつもより優しい気がするんですけど！？」"

[[dialogue]]
speaker = "リーリア"
# 「いや、もちろんしますけどね。遠慮なく、ぎゅ～～っと<emoji=heart04>」
line = "「いや、もちろんしますけどね。遠慮なく、ぎゅ～～っと<emoji=heart04>」"

[[dialogue]]
speaker = "リーリア"
# 「…………えへへ、やった……嬉しいな」
line = "「…………えへへ、やった……嬉しいな」"

[[dialogue]]
speaker = "リーリア"
# 「……波の音、静かで……ロマンチック……なんだかドキドキしちゃいますね」
line = "「……波の音、静かで……ロマンチック……なんだかドキドキしちゃいますね」"

[[dialogue]]
speaker = "リーリア"
# 「こうして歩いてると、本当に恋人同士になれた気分です……センパイはどうですか？」
line = "「こうして歩いてると、本当に恋人同士になれた気分です……センパイはどうですか？」"

[[dialogue]]
speaker = "クロト"
# 「うーん、どうかな？」
line = "「うーん、どうかな？」"

[[dialogue]]
speaker = "リーリア"
# 「あ～あ、またそんな意地悪言っちゃうんだ～」
line = "「あ～あ、またそんな意地悪言っちゃうんだ～」"

[[dialogue]]
speaker = "クロト"
# 「一目惚れは嘘だったんだよね？　リーリアの本心はどうなの？」
line = "「一目惚れは嘘だったんだよね？　リーリアの本心はどうなの？」"

[[dialogue]]
speaker = "リーリア"
# 「一目惚れっていうのは、もちろん嘘です……嘘、でした」
line = "「一目惚れっていうのは、もちろん嘘です……嘘、でした」"

[[dialogue]]
speaker = "リーリア"
# 「でも、こうして話しているうちに、センパイのいい所にどんどん気付いていって……」
line = "「でも、こうして話しているうちに、センパイのいい所にどんどん気付いていって……」"

[[dialogue]]
speaker = "リーリア"
# 「一目惚れじゃなかったとしても……嘘から出た誠、そういうのも、あるかもしれませんね♪」
line = "「一目惚れじゃなかったとしても……嘘から出た誠、そういうのも、あるかもしれませんね♪」"

[[dialogue]]
speaker = "クロト"
# 「そうか……」
line = "「そうか……」"

[[dialogue]]
speaker = "リーリア"
# 「ちょ、そ、そんなに考えこまれると！　ガチのやつみたいで、私の方が恥ずかしくなっちゃいますよ――」
line = "「ちょ、そ、そんなに考えこまれると！　ガチのやつみたいで、私の方が恥ずかしくなっちゃいますよ――」"

[[dialogue]]
speaker = "クロト"
# 「リーリアの気持ちが知りたかった」
line = "「リーリアの気持ちが知りたかった」"

[[dialogue]]
speaker = "クロト"
# 「リーリアが真剣なら、俺も真剣に考えなくちゃいけない」
line = "「リーリアが真剣なら、俺も真剣に考えなくちゃいけない」"

[[dialogue]]
speaker = "リーリア"
# 「わ、私は……真剣、ですよ……？　最初から、今だって……」
line = "「わ、私は……真剣、ですよ……？　最初から、今だって……」"

[[dialogue]]
speaker = "クロト"
# 「分かった。じゃあ、応えるよ……リーリア……俺の目を見て……」
line = "「分かった。じゃあ、応えるよ……リーリア……俺の目を見て……」"

[[dialogue]]
speaker = "リーリア"
# 「は、はい……」
line = "「は、はい……」"

[[dialogue]]
speaker = "クロト"
# 「俺は、リーリアのことが――」
line = "「俺は、リーリアのことが――」"

[[dialogue]]
speaker = "セドナ"
# 「何をしている、リーリア。準備はいいのかと聞いているんだ」
line = "「何をしている、リーリア。準備はいいのかと聞いているんだ」"

[[dialogue]]
speaker = "リーリア"
# 「ふぇぇ……」
line = "「ふぇぇ……」"

[[dialogue]]
speaker = "セドナ"
# 「訓練の最中に放心とは、気持ちが緩んでいる証拠だ」
line = "「訓練の最中に放心とは、気持ちが緩んでいる証拠だ」"

[[dialogue]]
speaker = "リーリア"
# 「ぅぅぅ……なんで～～～！！　こんなはずじゃなかったのにぃ！！」
line = "「ぅぅぅ……なんで～～～！！　こんなはずじゃなかったのにぃ！！」"

[[dialogue]]
speaker = "unk"
# あれよあれよという間に、ネビュラの水着戦闘服の性能テストということで、２vs２の対抗模擬戦をするという話になっていた。
line = "あれよあれよという間に、ネビュラの水着戦闘服の性能テストということで、２vs２の対抗模擬戦をするという話になっていた。"

[[dialogue]]
speaker = "unk"
# こちらはヴィーナスとマトイ、ネビュラサイドは戦闘服を持っているセドナさんとリーリアが戦う。
line = "こちらはヴィーナスとマトイ、ネビュラサイドは戦闘服を持っているセドナさんとリーリアが戦う。"

[[dialogue]]
speaker = "ヴィーナス"
# 「こちらは準備ＯＫ！　いつでもかかってきていいわよっ！」
line = "「こちらは準備ＯＫ！　いつでもかかってきていいわよっ！」"

[[dialogue]]
speaker = "リーリア"
# 「セドナ長官はともかく、どうしてヴィーナス先輩までそんなにノリノリなんですか……」
line = "「セドナ長官はともかく、どうしてヴィーナス先輩までそんなにノリノリなんですか……」"

[[dialogue]]
speaker = "unk"
# 軽度の戦闘狂なんだ
line = "軽度の戦闘狂なんだ"

[[dialogue]]
speaker = "リーリア"
# 「娘さんなんでしたっけ……？　意味不明すぎて頭おかしくなりそうですけど、とりあえず教育方針間違えてますよ、ぜったい」
line = "「娘さんなんでしたっけ……？　意味不明すぎて頭おかしくなりそうですけど、とりあえず教育方針間違えてますよ、ぜったい」"

[[dialogue]]
speaker = "unk"
# 面目次第もない
line = "面目次第もない"

[[dialogue]]
speaker = "ヴィーナス"
# 「何をコソコソ喋ってるのか知らないけれど、新しい水着フォームの性能テストをしたいのはネビュラだけじゃないってことよ！」
line = "「何をコソコソ喋ってるのか知らないけれど、新しい水着フォームの性能テストをしたいのはネビュラだけじゃないってことよ！」"

[[dialogue]]
speaker = "セドナ"
# 「そういえば先ほど、水着フォームがパワーアップした、などと話していたか？」
line = "「そういえば先ほど、水着フォームがパワーアップした、などと話していたか？」"

[[dialogue]]
speaker = "アナ"
# 「どうしてそんな事が起きたのか現在調査中ですが、おそらく前会長の有する膨大な星力によるものではないかと」
line = "「どうしてそんな事が起きたのか現在調査中ですが、おそらく前会長の有する膨大な星力によるものではないかと」"

[[dialogue]]
speaker = "サーシャ"
# 「再現性があるのかないのか、今のところまったくわからないわね～♪」
line = "「再現性があるのかないのか、今のところまったくわからないわね～♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「つまり気合いがあれば、何でも出来るってことね！　マトイ、あなたもやってみなさい！」
line = "「つまり気合いがあれば、何でも出来るってことね！　マトイ、あなたもやってみなさい！」"

[[dialogue]]
speaker = "マトイ"
# 「できるか！」
line = "「できるか！」"

[[dialogue]]
speaker = "マトイ"
# 「そんなルール無用のめちゃくちゃがまかり通るのなんて、ヴィーナスだけなんだから！」
line = "「そんなルール無用のめちゃくちゃがまかり通るのなんて、ヴィーナスだけなんだから！」"

[[dialogue]]
speaker = "セドナ"
# 「なるほど、水着の進化フォームか……俄然面白くなってきた」
line = "「なるほど、水着の進化フォームか……俄然面白くなってきた」"

[[dialogue]]
speaker = "ヴィーナス"
# 「元祖水着フォームの新星星徒会としては、そう簡単に負けるわけにはいかないのよ！」
line = "「元祖水着フォームの新星星徒会としては、そう簡単に負けるわけにはいかないのよ！」"

[[dialogue]]
speaker = "セドナ"
# 「その意気やよし……！」
line = "「その意気やよし……！」"

[[dialogue]]
speaker = "リーリア"
# 「あの２人、なんか意気投合しちゃってるんですけど」
line = "「あの２人、なんか意気投合しちゃってるんですけど」"

[[dialogue]]
speaker = "マトイ"
# 「意外……でもないのか。よく考えたら」
line = "「意外……でもないのか。よく考えたら」"

[[dialogue]]
speaker = "マトイ"
# 「去年の水着合宿も、最初は『無人島でサバイバル合宿だ』とか言い出しちゃってて、危なかったんだから」
line = "「去年の水着合宿も、最初は『無人島でサバイバル合宿だ』とか言い出しちゃってて、危なかったんだから」"

[[dialogue]]
speaker = "リーリア"
# 「はぁ……そっちもそっちで苦労してるんですね」
line = "「はぁ……そっちもそっちで苦労してるんですね」"

[[dialogue]]
speaker = "マトイ"
# 「そちらもね……」
line = "「そちらもね……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「マトイ！　なーに対戦相手と和やか雑談してるの！」
line = "「マトイ！　なーに対戦相手と和やか雑談してるの！」"

[[dialogue]]
speaker = "セドナ"
# 「リーリア！　準備が出来たのなら速やかに報告しろ！」
line = "「リーリア！　準備が出来たのなら速やかに報告しろ！」"

[[dialogue]]
speaker = "リーリア"
# 「はいはい！　いつでも大丈夫ですよ！」
line = "「はいはい！　いつでも大丈夫ですよ！」"

[[dialogue]]
speaker = "セドナ"
# 「うむ……では始めようか。行くぞ！」
line = "「うむ……では始めようか。行くぞ！」"

[[dialogue]]
speaker = "unk"
# 次の瞬間、魔法と星術が激しい音でぶつかり合い、戦いの火蓋が切って落とされた。
line = "次の瞬間、魔法と星術が激しい音でぶつかり合い、戦いの火蓋が切って落とされた。"
