[[dialogue]]
speaker = "フィオナ"
# 「ルリエルーっ。いるなら返事をしてくださーいっ」
line = "「ルリエルーっ。いるなら返事をしてくださーいっ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「この辺りにはいないみたいね……」
line = "「この辺りにはいないみたいね……」"

[[dialogue]]
speaker = "マグダレナ"
# 「具体的な位置まで絞り込めれば良かったのですが……」
line = "「具体的な位置まで絞り込めれば良かったのですが……」"

[[dialogue]]
speaker = "聖沙"
# 「天使の羽根と輪っかを付けた小柄な女の子よね？　近くを回ってみたけど、見当たらなかったわ……」
line = "「天使の羽根と輪っかを付けた小柄な女の子よね？　近くを回ってみたけど、見当たらなかったわ……」"

[[dialogue]]
speaker = "リア"
# 「となると中心街の方にいるのかな。てっきりフィーニスの塔の近くにいるかと思ったんだけど」
line = "「となると中心街の方にいるのかな。てっきりフィーニスの塔の近くにいるかと思ったんだけど」"

[[dialogue]]
speaker = "unk"
# 町の方へ行ってみようか
line = "町の方へ行ってみようか"

[[dialogue]]
speaker = "リア"
# 「だね。ちょうどお昼時だし、もしかしたら何か食べに行ってるのかも」
line = "「だね。ちょうどお昼時だし、もしかしたら何か食べに行ってるのかも」"

[[dialogue]]
speaker = "ヴィーナス"
# 「異世界に迷い込んでおいて能天気な……いえ。あの子なら有り得るのかしら……」
line = "「異世界に迷い込んでおいて能天気な……いえ。あの子なら有り得るのかしら……」"

[[dialogue]]
speaker = "フィオナ"
# 「良くも悪くも素直でマイペースな子なので……あはは」
line = "「良くも悪くも素直でマイペースな子なので……あはは」"

[[dialogue]]
speaker = "聖沙"
# 「なら決まりね。私たちも何か食べましょ。腹が減っては戦もできないわ」
line = "「なら決まりね。私たちも何か食べましょ。腹が減っては戦もできないわ」"

[[dialogue]]
speaker = "リア"
# 「じゃあ夕霧庵に行こっか♪　ナナカちゃん──うちの生徒会の会計さんのご実家がソバ屋さんなの♪」
line = "「じゃあ夕霧庵に行こっか♪　ナナカちゃん──うちの生徒会の会計さんのご実家がソバ屋さんなの♪」"

[[dialogue]]
speaker = "マグダレナ"
# 「これがおソバ、ですか……」
line = "「これがおソバ、ですか……」"

[[dialogue]]
speaker = "リア"
# 「なんだか不思議だね。守護天使様とこうして並んでご飯を食べているなんて」
line = "「なんだか不思議だね。守護天使様とこうして並んでご飯を食べているなんて」"

[[dialogue]]
speaker = "マグダレナ"
# 「マグダレナで構いませんよ。皆さまからもそうお呼びいただいていますから」
line = "「マグダレナで構いませんよ。皆さまからもそうお呼びいただいていますから」"

[[dialogue]]
speaker = "聖沙"
# 「さて、会長さん。おソバ屋さんに来たからにはもうわかってるわよね？」
line = "「さて、会長さん。おソバ屋さんに来たからにはもうわかってるわよね？」"

[[dialogue]]
speaker = "unk"
# まさか
line = "まさか"

[[dialogue]]
speaker = "聖沙"
# 「ふふ、そのまさかよ。言ったでしょ、腹が減っては戦もできないって」
line = "「ふふ、そのまさかよ。言ったでしょ、腹が減っては戦もできないって」"

[[dialogue]]
speaker = "聖沙"
# 「ルリエルさん探しに備えるためにも──勝負よ！　どちらがより多くのソバを平らげることができるか競おうじゃない！」
line = "「ルリエルさん探しに備えるためにも──勝負よ！　どちらがより多くのソバを平らげることができるか競おうじゃない！」"

[[dialogue]]
speaker = "聖沙"
# 「ぐ、ぐぬぬ。お腹が、もう……！」
line = "「ぐ、ぐぬぬ。お腹が、もう……！」"

[[dialogue]]
speaker = "unk"
# 俺もお腹いっぱいだ
line = "俺もお腹いっぱいだ"

[[dialogue]]
speaker = "聖沙"
# 「そ、そう。ならこの勝負は引き分けね。あなたも中々良い食べっぷりだったじゃない」
line = "「そ、そう。ならこの勝負は引き分けね。あなたも中々良い食べっぷりだったじゃない」"

[[dialogue]]
speaker = "聖沙"
# 「にしても本当にルリエルさんはこの世界に来ているのかしら。天使が町を歩いていたら大騒ぎになりそうなものだけど……」
line = "「にしても本当にルリエルさんはこの世界に来ているのかしら。天使が町を歩いていたら大騒ぎになりそうなものだけど……」"

[[dialogue]]
speaker = "リア"
# 「確かにそうだよね。私も未だにマグダレナさんの姿が気になっちゃうし」
line = "「確かにそうだよね。私も未だにマグダレナさんの姿が気になっちゃうし」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そんなものなの？　流星市国じゃ天使も魔族も人間も普通に暮らしてるから、よくわからないわ」
line = "「そんなものなの？　流星市国じゃ天使も魔族も人間も普通に暮らしてるから、よくわからないわ」"

[[dialogue]]
speaker = "フィオナ"
# 「そう考えると奇妙ですね。マグダレナ様を見かけるだけでも騒ぎになりそうなものですが」
line = "「そう考えると奇妙ですね。マグダレナ様を見かけるだけでも騒ぎになりそうなものですが」"

[[dialogue]]
speaker = "リア"
# 「あ、言われてみればそうだね。どうしてだろう？」
line = "「あ、言われてみればそうだね。どうしてだろう？」"

[[dialogue]]
speaker = "マグダレナ"
# 「それも境界の乱れによるものでしょう。何かしらの理由でリクリエの持つ世界を改変する力が働いてしまっているのかもしれません」
line = "「それも境界の乱れによるものでしょう。何かしらの理由でリクリエの持つ世界を改変する力が働いてしまっているのかもしれません」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そう言われると恐ろしくなってくるわね……。あまりこの世界に留まり続けるのは危険かもしれないわ」
line = "「そう言われると恐ろしくなってくるわね……。あまりこの世界に留まり続けるのは危険かもしれないわ」"

[[dialogue]]
speaker = "フィオナ"
# 「一刻も早くルリエルを見つけて、元の世界に戻るべきですね」
line = "「一刻も早くルリエルを見つけて、元の世界に戻るべきですね」"

[[dialogue]]
speaker = "聖沙"
# 「そうと決まれば、みんなおかわりよ！　たっぷり食べて、エネルギーを補給しなくっちゃ！」
line = "「そうと決まれば、みんなおかわりよ！　たっぷり食べて、エネルギーを補給しなくっちゃ！」"

[[dialogue]]
speaker = "？？？"
# 「ガツガツガツ！！　モグモグモグ！！」
line = "「ガツガツガツ！！　モグモグモグ！！」"

[[dialogue]]
speaker = "聖沙"
# 「わ……隣の人、ものすごい勢いね。負けていられないわ」
line = "「わ……隣の人、ものすごい勢いね。負けていられないわ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「しかしなんとまぁ品のない食べ方を……」
line = "「しかしなんとまぁ品のない食べ方を……」"

[[dialogue]]
speaker = "フィオナ"
# 「もし我が校に在籍していたら、礼儀作法から教育しているところです」
line = "「もし我が校に在籍していたら、礼儀作法から教育しているところです」"

[[dialogue]]
speaker = "ルリエル"
# 「ズズズズぅ──ぷっはぁ～！！　大満足れふぅ～……」
line = "「ズズズズぅ──ぷっはぁ～！！　大満足れふぅ～……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「えっ！？」
line = "「えっ！？」"

[[dialogue]]
speaker = "フィオナ"
# 「へっ！？」
line = "「へっ！？」"

[[dialogue]]
speaker = "unk"
# ルリエル！？
line = "ルリエル！？"

[[dialogue]]
speaker = "ヴィーナス"
# 「無事だったのね！　探したのよ！」
line = "「無事だったのね！　探したのよ！」"

[[dialogue]]
speaker = "フィオナ"
# 「元気そうで安心しましたが……コホン、後でお話があります」
line = "「元気そうで安心しましたが……コホン、後でお話があります」"

[[dialogue]]
speaker = "ルリエル"
# 「ええと……？　どちら様ですか？」
line = "「ええと……？　どちら様ですか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「はぁ？　何を言ってるのよ」
line = "「はぁ？　何を言ってるのよ」"

[[dialogue]]
speaker = "フィオナ"
# 「言い訳は無用ですよ。お箸の持ち方からみっちり教えますからね？」
line = "「言い訳は無用ですよ。お箸の持ち方からみっちり教えますからね？」"

[[dialogue]]
speaker = "ルリエル"
# 「ほえぇ……？」
line = "「ほえぇ……？」"

[[dialogue]]
speaker = "unk"
# まさか本当にわからないのか？
line = "まさか本当にわからないのか？"

[[dialogue]]
speaker = "ルリエル"
# 「わからないも何も、あなた方とは初対面ですし……」
line = "「わからないも何も、あなた方とは初対面ですし……」"

[[dialogue]]
speaker = "聖沙"
# 「ええと……どういうこと？」
line = "「ええと……どういうこと？」"

[[dialogue]]
speaker = "リア"
# 「彼女がルリエルさんじゃないの？」
line = "「彼女がルリエルさんじゃないの？」"

[[dialogue]]
speaker = "ルリエル"
# 「あっ──副会長さんに先輩さんっ！」
line = "「あっ──副会長さんに先輩さんっ！」"

[[dialogue]]
speaker = "聖沙"
# 「えっ、私たちのこと！？　あなたはあちらの世界の星徒会役員なんじゃ……」
line = "「えっ、私たちのこと！？　あなたはあちらの世界の星徒会役員なんじゃ……」"

[[dialogue]]
speaker = "ルリエル"
# 「ややっ！？　どーしてそんな寂しいこと言うんですかぁ！？　同じ生徒会の仲間ですよね！？」
line = "「ややっ！？　どーしてそんな寂しいこと言うんですかぁ！？　同じ生徒会の仲間ですよね！？」"

[[dialogue]]
speaker = "リア"
# 「わたしたちはあなたとは初対面のはずだけど……」
line = "「わたしたちはあなたとは初対面のはずだけど……」"

[[dialogue]]
speaker = "ルリエル"
# 「なななな、なんと、先輩さんまで！？　このルリエル・ローゼンクロイツを忘れたとでも言うんですかぁ～！？」
line = "「なななな、なんと、先輩さんまで！？　このルリエル・ローゼンクロイツを忘れたとでも言うんですかぁ～！？」"

[[dialogue]]
speaker = "聖沙"
# 「ローゼンクロイツって、それはロロットさんの……」
line = "「ローゼンクロイツって、それはロロットさんの……」"

[[dialogue]]
speaker = "リア"
# 「そう言えばロロットちゃんは？　最近、姿を見ていないけど……」
line = "「そう言えばロロットちゃんは？　最近、姿を見ていないけど……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「一体何が起こってるの？　ルリエルったら、まるでちぐはぐだわ……」
line = "「一体何が起こってるの？　ルリエルったら、まるでちぐはぐだわ……」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ。私たちのことは忘れてしまっているのに、聖沙さんやリアさんのことは本当の先輩のように慕っていて……」
line = "「ええ。私たちのことは忘れてしまっているのに、聖沙さんやリアさんのことは本当の先輩のように慕っていて……」"

[[dialogue]]
speaker = "マグダレナ"
# 「やはり、この気配は……」
line = "「やはり、この気配は……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「どうしたのマグダレナ？」
line = "「どうしたのマグダレナ？」"

[[dialogue]]
speaker = "マグダレナ"
# 「彼女の気配が妙だとは思っていたのです。しかし直接会って……確信しました」
line = "「彼女の気配が妙だとは思っていたのです。しかし直接会って……確信しました」"

[[dialogue]]
speaker = "マグダレナ"
# 「この気配は、リクリエです。彼女の中にリクリエの気配が混じっています」
line = "「この気配は、リクリエです。彼女の中にリクリエの気配が混じっています」"

[[dialogue]]
speaker = "フィオナ"
# 「リクリエ、の？」
line = "「リクリエ、の？」"

[[dialogue]]
speaker = "マグダレナ"
# 「詳しいことはわかりません。ただ事実として、彼女を中心に世界の認識が改変されています」
line = "「詳しいことはわかりません。ただ事実として、彼女を中心に世界の認識が改変されています」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それじゃこの世界の住人が私たちの姿を見て大騒ぎしなかったのも……。ルリエルがリアさんたちの後輩面をするのも……」
line = "「それじゃこの世界の住人が私たちの姿を見て大騒ぎしなかったのも……。ルリエルがリアさんたちの後輩面をするのも……」"

[[dialogue]]
speaker = "マグダレナ"
# 「彼女の仕業でしょう。まだリアさま方には作用していない様子ですが……」
line = "「彼女の仕業でしょう。まだリアさま方には作用していない様子ですが……」"

[[dialogue]]
speaker = "フィオナ"
# 「その言い方だと、時間が経てばリアさんたちもルリエルを後輩だと認識するように聞こえますが」
line = "「その言い方だと、時間が経てばリアさんたちもルリエルを後輩だと認識するように聞こえますが」"

[[dialogue]]
speaker = "マグダレナ"
# 「可能性はあります。それどころか──」
line = "「可能性はあります。それどころか──」"

[[dialogue]]
speaker = "unk"
# ……俺たちも？
line = "……俺たちも？"

[[dialogue]]
speaker = "マグダレナ"
# 「はい……何かしら認識を改変されかねません」
line = "「はい……何かしら認識を改変されかねません」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そんな馬鹿な……と言いたいところだけど、マグダレナの言葉だものね」
line = "「そんな馬鹿な……と言いたいところだけど、マグダレナの言葉だものね」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ、早急に解決しなければ……。リクリエに化かされたとあっては、我ら流星クルセイダースの名が泣きます」
line = "「ええ、早急に解決しなければ……。リクリエに化かされたとあっては、我ら流星クルセイダースの名が泣きます」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうね。私たち、流星クルセイダースの威信にかけて、ルリエルを正気に戻すわよ！」
line = "「そうね。私たち、流星クルセイダースの威信にかけて、ルリエルを正気に戻すわよ！」"

[[dialogue]]
speaker = "unk"
# ああ。俺たち、流星クルセイダースの──って
line = "ああ。俺たち、流星クルセイダースの──って"

[[dialogue]]
speaker = "フィオナ"
# 「ハっ！　私いま、自分を流星クルセイダースの一員だと思い込んでしまっていて……！」
line = "「ハっ！　私いま、自分を流星クルセイダースの一員だと思い込んでしまっていて……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「私もよ……！　どうして、そんな勘違いを……」
line = "「私もよ……！　どうして、そんな勘違いを……」"

[[dialogue]]
speaker = "マグダレナ"
# 「これは……想像以上に危うい状況ですね。ルリエルさまに近づき過ぎました」
line = "「これは……想像以上に危うい状況ですね。ルリエルさまに近づき過ぎました」"

[[dialogue]]
speaker = "マグダレナ"
# 「急いでこの場を離れましょう。早くしないと私たちまで、この世界の住人に──」
line = "「急いでこの場を離れましょう。早くしないと私たちまで、この世界の住人に──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ダ、ダメ。もう遅い、かも……。急に、眠気が……」
line = "「ダ、ダメ。もう遅い、かも……。急に、眠気が……」"

[[dialogue]]
speaker = "フィオナ"
# 「睡魔に抗え……ません……。食後にすぐ寝るのは、身体に良くありません、のに……」
line = "「睡魔に抗え……ません……。食後にすぐ寝るのは、身体に良くありません、のに……」"

[[dialogue]]
speaker = "マグダレナ"
# 「いけません、皆さま……。意識を、強く……保つの、です……」
line = "「いけません、皆さま……。意識を、強く……保つの、です……」"

[[dialogue]]
speaker = "unk"
# っっ……
line = "っっ……"
