[[dialogue]]
speaker = "パッキー"
# 「お、俺様のパラダイスがぁ……。野望がぁ……」
line = "「お、俺様のパラダイスがぁ……。野望がぁ……」"

[[dialogue]]
speaker = "リア"
# 「ふーんだ。えっちなことしようとするからだよ」
line = "「ふーんだ。えっちなことしようとするからだよ」"

[[dialogue]]
speaker = "フィオナ"
# 「随分小さくなりましたね……。これが元の大きさということでしょうか」
line = "「随分小さくなりましたね……。これが元の大きさということでしょうか」"

[[dialogue]]
speaker = "マグダレナ"
# 「そのようですね。感じていたリクリエの気配も消えています」
line = "「そのようですね。感じていたリクリエの気配も消えています」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ともかくこれで一件落着ね。アステラも無事消滅したようだし」
line = "「ともかくこれで一件落着ね。アステラも無事消滅したようだし」"

[[dialogue]]
speaker = "ルリエル"
# 「全く人騒がせなパンダさんです！　魔王の使い魔のくせにリクリエに化かされるなんて情けないことこの上ないですよ！」
line = "「全く人騒がせなパンダさんです！　魔王の使い魔のくせにリクリエに化かされるなんて情けないことこの上ないですよ！」"

[[dialogue]]
speaker = "聖沙"
# 「ルリエルさんがそれを言うのね……」
line = "「ルリエルさんがそれを言うのね……」"

[[dialogue]]
speaker = "unk"
# にしても強敵だった
line = "にしても強敵だった"

[[dialogue]]
speaker = "パッキー"
# 「ふ……そいつは俺様のセリフだぜ。シン様ほどじゃねえがお前も中々やるじゃねえか」
line = "「ふ……そいつは俺様のセリフだぜ。シン様ほどじゃねえがお前も中々やるじゃねえか」"

[[dialogue]]
speaker = "パッキー"
# 「そんなお前に、大賢者さまからのアドバイスだ。……慕ってくれるコイツらをもっと大事にしてやれ」
line = "「そんなお前に、大賢者さまからのアドバイスだ。……慕ってくれるコイツらをもっと大事にしてやれ」"

[[dialogue]]
speaker = "パッキー"
# 「そうすれば、ククク……コイツらのおっぱいをお前だけのものにできるだろーぜ」
line = "「そうすれば、ククク……コイツらのおっぱいをお前だけのものにできるだろーぜ」"

[[dialogue]]
speaker = "unk"
# パッキー……
line = "パッキー……"

[[dialogue]]
speaker = "ヴィーナス"
# 「って、何をいい話風にスケベなこと言ってんのよ！」
line = "「って、何をいい話風にスケベなこと言ってんのよ！」"

[[dialogue]]
speaker = "パッキー"
# 「ぎゃふん！？」
line = "「ぎゃふん！？」"

[[dialogue]]
speaker = "フィオナ"
# 「会長も会長です！　何を深く頷いているのですか！」
line = "「会長も会長です！　何を深く頷いているのですか！」"

[[dialogue]]
speaker = "リア"
# 「も～。あんまりスケベだと女の子に嫌われちゃうゾ？」
line = "「も～。あんまりスケベだと女の子に嫌われちゃうゾ？」"

[[dialogue]]
speaker = "聖沙"
# 「はぁ……。どんな世界でも男の子の不純さは変わらないものね……」
line = "「はぁ……。どんな世界でも男の子の不純さは変わらないものね……」"

[[dialogue]]
speaker = "ルリエル"
# 「マグダレナさんはどうしてそんなにおっぱいが大きいんですか？　私も天使としての格が上がれば大きくなりますかねっ？」
line = "「マグダレナさんはどうしてそんなにおっぱいが大きいんですか？　私も天使としての格が上がれば大きくなりますかねっ？」"

[[dialogue]]
speaker = "マグダレナ"
# 「ええと、天使の位と胸の大きさは無関係だと思いますが……」
line = "「ええと、天使の位と胸の大きさは無関係だと思いますが……」"

[[dialogue]]
speaker = "unk"
# でもこれで流星クルセイダースとは……
line = "でもこれで流星クルセイダースとは……"

[[dialogue]]
speaker = "リア"
# 「うん……お別れだね」
line = "「うん……お別れだね」"

[[dialogue]]
speaker = "聖沙"
# 「短い間だったけど楽しかったわ。あまり先輩らしいことはできなかったけれどね」
line = "「短い間だったけど楽しかったわ。あまり先輩らしいことはできなかったけれどね」"

[[dialogue]]
speaker = "フィオナ"
# 「いえ、そんなことはありません。伝え聞いていた通りの、まさに英雄でした。共に戦うことができて光栄です」
line = "「いえ、そんなことはありません。伝え聞いていた通りの、まさに英雄でした。共に戦うことができて光栄です」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ありがとう、リアさん、聖沙。あなたたちがいなかったら、きっとこの問題は解決できなかったわ」
line = "「ありがとう、リアさん、聖沙。あなたたちがいなかったら、きっとこの問題は解決できなかったわ」"

[[dialogue]]
speaker = "リア"
# 「ふふ、先輩ですもの。こちらこそ、ありがとう、みんな」
line = "「ふふ、先輩ですもの。こちらこそ、ありがとう、みんな」"

[[dialogue]]
speaker = "聖沙"
# 「あなたたちのような星騎士がいるなら、この世界は安心よ。私たちが保証するわ」
line = "「あなたたちのような星騎士がいるなら、この世界は安心よ。私たちが保証するわ」"

[[dialogue]]
speaker = "unk"
# お世話になりました！
line = "お世話になりました！"

[[dialogue]]
speaker = "聖沙"
# 「それじゃあ帰りましょうか、先輩！　私たちの世界へ！」
line = "「それじゃあ帰りましょうか、先輩！　私たちの世界へ！」"

[[dialogue]]
speaker = "リア"
# 「うん！　またね、みんな！」
line = "「うん！　またね、みんな！」"

[[dialogue]]
speaker = "パッキー"
# 「あー……。盛り上がってるところわりぃんだけどよ」
line = "「あー……。盛り上がってるところわりぃんだけどよ」"

[[dialogue]]
speaker = "パッキー"
# 「今すぐ帰れるわけじゃなさそうだぜ？」
line = "「今すぐ帰れるわけじゃなさそうだぜ？」"

[[dialogue]]
speaker = "マグダレナ"
# 「境界の乱れが落ち着くまで、しばらくこちらにいていただくことになりますね」
line = "「境界の乱れが落ち着くまで、しばらくこちらにいていただくことになりますね」"

[[dialogue]]
speaker = "リア＆聖沙"
# 「ええ～～～っ！！？」
line = "「ええ～～～っ！！？」"

[[dialogue]]
speaker = "unk"
# ………………
line = "………………"

[[dialogue]]
speaker = "unk"
# …………
line = "…………"

[[dialogue]]
speaker = "unk"
# ……
line = "……"

[[dialogue]]
speaker = "unk"
# それからしばらくして──
line = "それからしばらくして──"

[[dialogue]]
speaker = "マグダレナ"
# 「世界の交錯が収束しているようですね。今なら元の世界に戻れることでしょう」
line = "「世界の交錯が収束しているようですね。今なら元の世界に戻れることでしょう」"

[[dialogue]]
speaker = "パッキー"
# 「ちっくしょ～！　もー帰んなくちゃなんねーのかよ！　思ってたより早かったぜ！」
line = "「ちっくしょ～！　もー帰んなくちゃなんねーのかよ！　思ってたより早かったぜ！」"

[[dialogue]]
speaker = "聖沙"
# 「……地獄のような数日間だったわ。あれだけ決めに決めたのに、元の世界に戻れず仕舞いだなんて……」
line = "「……地獄のような数日間だったわ。あれだけ決めに決めたのに、元の世界に戻れず仕舞いだなんて……」"

[[dialogue]]
speaker = "リア"
# 「あ、あはは……。でも、その分みんなと過ごせて楽しかったよね」
line = "「あ、あはは……。でも、その分みんなと過ごせて楽しかったよね」"

[[dialogue]]
speaker = "unk"
# 今度こそ帰っちゃうんですね
line = "今度こそ帰っちゃうんですね"

[[dialogue]]
speaker = "ヴィーナス"
# 「寂しくなるわ。せっかく仲良くなれたのに」
line = "「寂しくなるわ。せっかく仲良くなれたのに」"

[[dialogue]]
speaker = "フィオナ"
# 「きっとまた会えますよ。そんな予感がします」
line = "「きっとまた会えますよ。そんな予感がします」"

[[dialogue]]
speaker = "ルリエル"
# 「この制服、大切にします！　お二人との友情の証に！」
line = "「この制服、大切にします！　お二人との友情の証に！」"

[[dialogue]]
speaker = "聖沙"
# 「ふふ、お姉さまの言う通りね。小っ恥ずかしい想いはしたけれど、すぐに元の世界に戻されないで良かったわ」
line = "「ふふ、お姉さまの言う通りね。小っ恥ずかしい想いはしたけれど、すぐに元の世界に戻されないで良かったわ」"

[[dialogue]]
speaker = "リア"
# 「改めて──またね、みんな。あえてさよならは言わないよ？　必ずまた会えると信じてるから」
line = "「改めて──またね、みんな。あえてさよならは言わないよ？　必ずまた会えると信じてるから」"

[[dialogue]]
speaker = "聖沙"
# 「私たちの世界にもまた遊びに来てちょうだい。待ってるから」
line = "「私たちの世界にもまた遊びに来てちょうだい。待ってるから」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ええ、必ず遊びに行くわ」
line = "「ええ、必ず遊びに行くわ」"

[[dialogue]]
speaker = "フィオナ"
# 「はい。私もまだまだ平行世界を堪能しきれていませんから」
line = "「はい。私もまだまだ平行世界を堪能しきれていませんから」"

[[dialogue]]
speaker = "ルリエル"
# 「ローゼンクロイツさんにもお礼を言わなくちゃですし！　短い間とはいえ、お世話になっちゃいましたもん！」
line = "「ローゼンクロイツさんにもお礼を言わなくちゃですし！　短い間とはいえ、お世話になっちゃいましたもん！」"

[[dialogue]]
speaker = "リア"
# 「なら私たちも気合いを入れ直さないと。先輩として、みんなが次に来る時までに世界を救っておかなくっちゃ♪」
line = "「なら私たちも気合いを入れ直さないと。先輩として、みんなが次に来る時までに世界を救っておかなくっちゃ♪」"

[[dialogue]]
speaker = "聖沙"
# 「どっちが先に自分たちの世界を救えるか──勝負よ！　絶対にリ・クリエなんかに負けちゃダメだからねっ？」
line = "「どっちが先に自分たちの世界を救えるか──勝負よ！　絶対にリ・クリエなんかに負けちゃダメだからねっ？」"

[[dialogue]]
speaker = "unk"
# はい！
line = "はい！"

[[dialogue]]
speaker = "聖沙"
# 「ふふ、良い返事だわ。次に会える時が本当に楽しみよ」
line = "「ふふ、良い返事だわ。次に会える時が本当に楽しみよ」"

[[dialogue]]
speaker = "リア"
# 「忘れないでね？　みんなにはたくさんの仲間がいることを。みんなの絆が、世界を救うための一番の武器だっていうことを」
line = "「忘れないでね？　みんなにはたくさんの仲間がいることを。みんなの絆が、世界を救うための一番の武器だっていうことを」"

[[dialogue]]
speaker = "リア"
# 「もし私たちの力が必要な時があればいつでも呼んで？　必ず駆けつけるから」
line = "「もし私たちの力が必要な時があればいつでも呼んで？　必ず駆けつけるから」"

[[dialogue]]
speaker = "聖沙"
# 「たとえ別々の世界にいても──私たちの絆は永遠よ！」
line = "「たとえ別々の世界にいても──私たちの絆は永遠よ！」"

[[dialogue]]
speaker = "パッキー"
# 「欲望はパワーだぜ！　おっぱい揉んでやろうって気持ちを忘れんなよ！」
line = "「欲望はパワーだぜ！　おっぱい揉んでやろうって気持ちを忘れんなよ！」"

[[dialogue]]
speaker = "unk"
# リア先輩、聖沙さん、パッキー……！
line = "リア先輩、聖沙さん、パッキー……！"

[[dialogue]]
speaker = "ヴィーナス"
# 「今度こそ本当に行っちゃったようね」
line = "「今度こそ本当に行っちゃったようね」"

[[dialogue]]
speaker = "フィオナ"
# 「そうですね。でも、思っていたより寂しくはありません」
line = "「そうですね。でも、思っていたより寂しくはありません」"

[[dialogue]]
speaker = "ルリエル"
# 「はい。今もお二人がすぐ傍にいてくれるような気がします。これがＫＩＺＵＮＡというヤツなんでしょうか」
line = "「はい。今もお二人がすぐ傍にいてくれるような気がします。これがＫＩＺＵＮＡというヤツなんでしょうか」"

[[dialogue]]
speaker = "マグダレナ"
# 「きっとそうですよ。縁というものは、たとえ世界を隔てても断ち切れるようなものではありませんから」
line = "「きっとそうですよ。縁というものは、たとえ世界を隔てても断ち切れるようなものではありませんから」"

[[dialogue]]
speaker = "ヴィーナス"
# 「さて、と。それじゃあ私たちも行きましょうか。やることもあるしね？」
line = "「さて、と。それじゃあ私たちも行きましょうか。やることもあるしね？」"

[[dialogue]]
speaker = "unk"
# やること？
line = "やること？"

[[dialogue]]
speaker = "フィオナ"
# 「ふふ、忘れたのですか？　流星学園と新星学園の交流会ですよ」
line = "「ふふ、忘れたのですか？　流星学園と新星学園の交流会ですよ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「世界を隔てても消えない絆があるのだもの。学園同士で結べないわけがないわ」
line = "「世界を隔てても消えない絆があるのだもの。学園同士で結べないわけがないわ」"

[[dialogue]]
speaker = "マグダレナ"
# 「ええ。私どももより強く、深く、絆を結びましょう」
line = "「ええ。私どももより強く、深く、絆を結びましょう」"

[[dialogue]]
speaker = "ルリエル"
# 「流星クルセイダースのように一丸となってリ・クリエに立ち向かうために──ですね！」
line = "「流星クルセイダースのように一丸となってリ・クリエに立ち向かうために──ですね！」"

[[dialogue]]
speaker = "unk"
# To be countinued．．．
line = "To be countinued．．．"
