[[dialogue]]
speaker = "キリカ"
# 「緋宮会長を支えられる花嫁になるべく、フィオナお嬢様は努力しました。しかし緋宮会長はどうでしょうか？」
line = "「緋宮会長を支えられる花嫁になるべく、フィオナお嬢様は努力しました。しかし緋宮会長はどうでしょうか？」"

[[dialogue]]
speaker = "フィオナ"
# 「緋宮会長が花婿にふさわしくないなんて、私思ってないよ？　むしろ素敵な人だと──」
line = "「緋宮会長が花婿にふさわしくないなんて、私思ってないよ？　むしろ素敵な人だと──」"

[[dialogue]]
speaker = "フィオナ"
# 「ひゃっ、今のナシ！？　あ、いや、ナシじゃなくてアリなんですけど──ああっ！？　そういう意味ですけどそういう意味じゃなくて～っ！？」
line = "「ひゃっ、今のナシ！？　あ、いや、ナシじゃなくてアリなんですけど──ああっ！？　そういう意味ですけどそういう意味じゃなくて～っ！？」"

[[dialogue]]
speaker = "ナミエル"
# 「フィオナお嬢様が過去最大レベルで慌てています……」
line = "「フィオナお嬢様が過去最大レベルで慌てています……」"

[[dialogue]]
speaker = "キリカ"
# 「だとしても、フィオナお嬢様の理想はもっと高いのです。その理想に追いついてこそ、この結婚は成り立つものではないでしょうか」
line = "「だとしても、フィオナお嬢様の理想はもっと高いのです。その理想に追いついてこそ、この結婚は成り立つものではないでしょうか」"

[[dialogue]]
speaker = "unk"
# 俺、花婿修行やります！
line = "俺、花婿修行やります！"

[[dialogue]]
speaker = "キリカ"
# 「よろしいです。お嬢様の花婿となるために精進してください」
line = "「よろしいです。お嬢様の花婿となるために精進してください」"

[[dialogue]]
speaker = "フィオナ"
# 「うぅ……余計恥ずかしい展開になっている気が……」
line = "「うぅ……余計恥ずかしい展開になっている気が……」"

[[dialogue]]
speaker = "ナミエル"
# 「花婿修行では、私やメイド長を支えられる殿方になっていただきます」
line = "「花婿修行では、私やメイド長を支えられる殿方になっていただきます」"

[[dialogue]]
speaker = "ナミエル"
# 「男性にも家事が求められる時代になって久しいです。今は私と結婚していると仮定して、家事能力を見せていただきます」
line = "「男性にも家事が求められる時代になって久しいです。今は私と結婚していると仮定して、家事能力を見せていただきます」"

[[dialogue]]
speaker = "unk"
# 夫婦なんだから協力しないとな
line = "夫婦なんだから協力しないとな"

[[dialogue]]
speaker = "ナミエル"
# 「夫婦！？」
line = "「夫婦！？」"

[[dialogue]]
speaker = "ナミエル"
# 「いえ、何を驚いているのでしょう。そう、今の私たちは夫婦……寝食を共にするもの……」
line = "「いえ、何を驚いているのでしょう。そう、今の私たちは夫婦……寝食を共にするもの……」"

[[dialogue]]
speaker = "ナミエル"
# 「つまり一緒に……寝る……！？　同じベッドで寝たりなんかしたら、男は獣になって、欲望のままにあんなことやこんなことをするに決まってます！」
line = "「つまり一緒に……寝る……！？　同じベッドで寝たりなんかしたら、男は獣になって、欲望のままにあんなことやこんなことをするに決まってます！」"

[[dialogue]]
speaker = "ナミエル"
# 「不潔ですっ！！　掃除しますっ！！」
line = "「不潔ですっ！！　掃除しますっ！！」"

[[dialogue]]
speaker = "フィオナ"
# 「ナミエル、落ち着いて！　まだ本当に結婚したわけじゃないから！」
line = "「ナミエル、落ち着いて！　まだ本当に結婚したわけじゃないから！」"

[[dialogue]]
speaker = "ナミエル"
# 「ハッ──！？　申し訳ありません、取り乱しました……」
line = "「ハッ──！？　申し訳ありません、取り乱しました……」"

[[dialogue]]
speaker = "ナミエル"
# 「コホン。では花婿修行を始めましょう。星見家の方々の身の回りのお世話はメイド隊の仕事ですので、メイドの私室の掃除などを私と一緒に行っていただきます」
line = "「コホン。では花婿修行を始めましょう。星見家の方々の身の回りのお世話はメイド隊の仕事ですので、メイドの私室の掃除などを私と一緒に行っていただきます」"

[[dialogue]]
speaker = "ナミエル"
# 「全ての家事を完璧にこなす必要はありません。夫婦とは助け合うものですから」
line = "「全ての家事を完璧にこなす必要はありません。夫婦とは助け合うものですから」"

[[dialogue]]
speaker = "ナミエル"
# 「ただし、拙い部分は指導させていただきますので覚悟してください」
line = "「ただし、拙い部分は指導させていただきますので覚悟してください」"

[[dialogue]]
speaker = "ナミエル"
# 「むむ……緋宮会長、手際が良いです。掃除に関しては少し指導しましたが、料理は私よりも上手ですし……」
line = "「むむ……緋宮会長、手際が良いです。掃除に関しては少し指導しましたが、料理は私よりも上手ですし……」"

[[dialogue]]
speaker = "ナミエル"
# 「緋宮会長はバイトで経験があるからとはいえ……くっ……なぜか悔しいです」
line = "「緋宮会長はバイトで経験があるからとはいえ……くっ……なぜか悔しいです」"

[[dialogue]]
speaker = "キリカ"
# 「ですが、緋宮会長とは息が合っているようでした。役割分担も的確で、スムーズに掃除を終わらせましたね」
line = "「ですが、緋宮会長とは息が合っているようでした。役割分担も的確で、スムーズに掃除を終わらせましたね」"

[[dialogue]]
speaker = "ナミエル"
# 「そうでしょうか？　確かにいつもより掃除が捗った気がしますが……」
line = "「そうでしょうか？　確かにいつもより掃除が捗った気がしますが……」"

[[dialogue]]
speaker = "unk"
# ご飯できたよ
line = "ご飯できたよ"

[[dialogue]]
speaker = "ナミエル"
# 「あ……オムライス」
line = "「あ……オムライス」"

[[dialogue]]
speaker = "フィオナ"
# 「ナミエル、オムライス好きなの？」
line = "「ナミエル、オムライス好きなの？」"

[[dialogue]]
speaker = "ナミエル"
# 「いえ、好きというか……昔、母に作ってもらったことを思い出しました」
line = "「いえ、好きというか……昔、母に作ってもらったことを思い出しました」"

[[dialogue]]
speaker = "ナミエル"
# 「正直、味は覚えていません。でもあの時は嬉しかったような気がしますから……やっぱり好きだったのかもしれません」
line = "「正直、味は覚えていません。でもあの時は嬉しかったような気がしますから……やっぱり好きだったのかもしれません」"

[[dialogue]]
speaker = "ナミエル"
# 「いただきます。……あむ」
line = "「いただきます。……あむ」"

[[dialogue]]
speaker = "unk"
# 美味しい？
line = "美味しい？"

[[dialogue]]
speaker = "ナミエル"
# 「……はい。私に言われても緋宮会長は嬉しくないかもしれませんが、そう感じます」
line = "「……はい。私に言われても緋宮会長は嬉しくないかもしれませんが、そう感じます」"

[[dialogue]]
speaker = "ナミエル"
# 「甘めで子ども向けの味ですけど、母のオムライスもこんな味だったかもしれません」
line = "「甘めで子ども向けの味ですけど、母のオムライスもこんな味だったかもしれません」"

[[dialogue]]
speaker = "ナミエル"
# 「あの……このオムライスの作り方、教えていただけませんか？　料理ならメイド長に教わるのが筋なのですが、私はこのオムライスを覚えたいんです」
line = "「あの……このオムライスの作り方、教えていただけませんか？　料理ならメイド長に教わるのが筋なのですが、私はこのオムライスを覚えたいんです」"

[[dialogue]]
speaker = "ナミエル"
# 「……もちろんＯＫ？　ありがとうございます」
line = "「……もちろんＯＫ？　ありがとうございます」"

[[dialogue]]
speaker = "ナミエル"
# 「緋宮会長と一緒の生活……私が掃除をして……緋宮会長が食事を作って……」
line = "「緋宮会長と一緒の生活……私が掃除をして……緋宮会長が食事を作って……」"

[[dialogue]]
speaker = "ナミエル"
# 「緋宮会長となら、家族になれるかも……」
line = "「緋宮会長となら、家族になれるかも……」"

[[dialogue]]
speaker = "ナミエル"
# 「──！？　私は何を考えているのでしょう。こんなハレンチな人と結婚するなんて、ただれた生活になるに決まっています！」
line = "「──！？　私は何を考えているのでしょう。こんなハレンチな人と結婚するなんて、ただれた生活になるに決まっています！」"

[[dialogue]]
speaker = "フィオナ"
# 「はは……ナミエルは素直になればいいのに」
line = "「はは……ナミエルは素直になればいいのに」"

[[dialogue]]
speaker = "ナミエル"
# 「私は素直です。今のは緋宮会長の客観的な評価です」
line = "「私は素直です。今のは緋宮会長の客観的な評価です」"

[[dialogue]]
speaker = "unk"
# 洗濯もしておいたよ
line = "洗濯もしておいたよ"

[[dialogue]]
speaker = "ナミエル"
# 「ありがとうございます。あ、私のぬいぐるみ、手洗いまでしてくれたんですね。ふわふわになっています」
line = "「ありがとうございます。あ、私のぬいぐるみ、手洗いまでしてくれたんですね。ふわふわになっています」"

[[dialogue]]
speaker = "unk"
# ナミエルが大事にしてるやつだから
line = "ナミエルが大事にしてるやつだから"

[[dialogue]]
speaker = "ナミエル"
# 「そこまでしなくてもいいですって……。でも嬉しいです」
line = "「そこまでしなくてもいいですって……。でも嬉しいです」"

[[dialogue]]
speaker = "ナミエル"
# 「あれ？　これ……私のパンツ……？」
line = "「あれ？　これ……私のパンツ……？」"

[[dialogue]]
speaker = "ナミエル"
# 「キャ～～～～～～ッ！！？　やっぱり不潔です～～～～っ！！！」
line = "「キャ～～～～～～ッ！！？　やっぱり不潔です～～～～っ！！！」"

[[dialogue]]
speaker = "unk"
# ナミエルにたくさん怒られてしまった。
line = "ナミエルにたくさん怒られてしまった。"

[[dialogue]]
speaker = "unk"
# だけどオムライスの作り方を教えてあげて、ナミエルの花婿修行は合格となったのだった。
line = "だけどオムライスの作り方を教えてあげて、ナミエルの花婿修行は合格となったのだった。"
