[[dialogue]]
speaker = "トワ先生"
# 「ようやく見つけたわ！　わたしの旦那さまを返しなさぁーーーい！！」
line = "「ようやく見つけたわ！　わたしの旦那さまを返しなさぁーーーい！！」"

[[dialogue]]
speaker = "マトイ"
# 「会長っ、大丈夫ですか──ってこれは……大丈夫じゃない……みたい？」
line = "「会長っ、大丈夫ですか──ってこれは……大丈夫じゃない……みたい？」"

[[dialogue]]
speaker = "トワ先生"
# 「は、破廉恥だよっ！　わたしというお嫁さんがいるのに、浮気なんて許さないんだからっ！」
line = "「は、破廉恥だよっ！　わたしというお嫁さんがいるのに、浮気なんて許さないんだからっ！」"

[[dialogue]]
speaker = "unk"
# ちょっとお触りしようとしただけだから
line = "ちょっとお触りしようとしただけだから"

[[dialogue]]
speaker = "unk"
# ご、誤解だよ！
line = "ご、誤解だよ！"

[[dialogue]]
speaker = "トワ先生"
# 「言い訳になってない！」
line = "「言い訳になってない！」"

[[dialogue]]
speaker = "トワ先生"
# 「ううっ、やっぱり会長くんも若い子がいいんだ……２人みたいにかわいい耳と尻尾がついてる女の子の方がいいんでしょ？」
line = "「ううっ、やっぱり会長くんも若い子がいいんだ……２人みたいにかわいい耳と尻尾がついてる女の子の方がいいんでしょ？」"

[[dialogue]]
speaker = "トワ先生"
# 「わ、わたしだって！　こう、だっこしてぎゅっとしたら……絶対気持ちいいんだもん」
line = "「わ、わたしだって！　こう、だっこしてぎゅっとしたら……絶対気持ちいいんだもん」"

[[dialogue]]
speaker = "トワ先生"
# 「会長くんがしたいって言ったら……ちょっとくらいなら、だっこさせてあげてもいいのに……」
line = "「会長くんがしたいって言ったら……ちょっとくらいなら、だっこさせてあげてもいいのに……」"

[[dialogue]]
speaker = "unk"
# 本当に！？
line = "本当に！？"

[[dialogue]]
speaker = "マトイ"
# 「会長、落ち着いて！　おかしくなってるよ！　トワちゃん先生も暴走しないでっ！」
line = "「会長、落ち着いて！　おかしくなってるよ！　トワちゃん先生も暴走しないでっ！」"

[[dialogue]]
speaker = "トワ先生"
# 「っ！　そ、そうだね、今は会長くんを取り返すことが何より大事なんだから……」
line = "「っ！　そ、そうだね、今は会長くんを取り返すことが何より大事なんだから……」"

[[dialogue]]
speaker = "トワ先生"
# 「２人とも！　会長くんをさらって結婚式をぶち壊すなんて許せません！　さあ、会長くんをこっちに返しなさい！」
line = "「２人とも！　会長くんをさらって結婚式をぶち壊すなんて許せません！　さあ、会長くんをこっちに返しなさい！」"

[[dialogue]]
speaker = "蘭美"
# 「返せと言われて素直に返すわけがないでしょう？　返して欲しかったら力づくで取り返してみなさい！」
line = "「返せと言われて素直に返すわけがないでしょう？　返して欲しかったら力づくで取り返してみなさい！」"

[[dialogue]]
speaker = "トワ先生"
# 「力づく？　ここで戦って決着をつけようってこと？」
line = "「力づく？　ここで戦って決着をつけようってこと？」"

[[dialogue]]
speaker = "マトイ"
# 「待って待って！　戦うのは絶対ダメだってば！　会長の家が壊れちゃう！　雌雄を決するなら、きちんと専用の場所でお願いね！」
line = "「待って待って！　戦うのは絶対ダメだってば！　会長の家が壊れちゃう！　雌雄を決するなら、きちんと専用の場所でお願いね！」"

[[dialogue]]
speaker = "蘭美"
# 「私たちは問題ないけど……貴方はどうするのかしら？」
line = "「私たちは問題ないけど……貴方はどうするのかしら？」"

[[dialogue]]
speaker = "トワ先生"
# 「もちろん、受けて立つよっ！」
line = "「もちろん、受けて立つよっ！」"

[[dialogue]]
speaker = "トワ先生"
# 「あなた達みたいな悪い子はおしおきです！　泣いて謝ったってぜぇぇぇ～～ったいに許してあげないんだからねっ！！」
line = "「あなた達みたいな悪い子はおしおきです！　泣いて謝ったってぜぇぇぇ～～ったいに許してあげないんだからねっ！！」"

[[dialogue]]
speaker = "マトイ"
# 「皆さん準備はいいですか？」
line = "「皆さん準備はいいですか？」"

[[dialogue]]
speaker = "トワ先生"
# 「ばっちりＯＫだよ！　いつでも全力を出せちゃうんだから！」
line = "「ばっちりＯＫだよ！　いつでも全力を出せちゃうんだから！」"

[[dialogue]]
speaker = "蘭美"
# 「ふふっ、すごい意気込みね。こちらは２人でそちらは１人だけど、本当に大丈夫かしら？」
line = "「ふふっ、すごい意気込みね。こちらは２人でそちらは１人だけど、本当に大丈夫かしら？」"

[[dialogue]]
speaker = "トワ先生"
# 「問題ないよっ、まとめてかかってきなさいっ！」
line = "「問題ないよっ、まとめてかかってきなさいっ！」"

[[dialogue]]
speaker = "ヨミ"
# 「力が漲ってますね……会長を取られた怒りのせいでしょうか？　それともあれがウェディングフォームの力でしょうか？」
line = "「力が漲ってますね……会長を取られた怒りのせいでしょうか？　それともあれがウェディングフォームの力でしょうか？」"

[[dialogue]]
speaker = "蘭美"
# 「どっちだっていいわ。どんな相手だろうと私の速度に追いつける相手なんていない。それが結婚に恋い焦がれる乙女だったとしてもね！」
line = "「どっちだっていいわ。どんな相手だろうと私の速度に追いつける相手なんていない。それが結婚に恋い焦がれる乙女だったとしてもね！」"

[[dialogue]]
speaker = "unk"
# ３人とも頑張って！
line = "３人とも頑張って！"

[[dialogue]]
speaker = "トワ先生"
# 「会長くん！　お嫁さんはわたしだよ！　わたしだけを応援してっ！」
line = "「会長くん！　お嫁さんはわたしだよ！　わたしだけを応援してっ！」"

[[dialogue]]
speaker = "蘭美"
# 「私を応援してくれたら、またうさみみを触らせてあげるぴょん<emoji=heart04>」
line = "「私を応援してくれたら、またうさみみを触らせてあげるぴょん<emoji=heart04>」"

[[dialogue]]
speaker = "ヨミ"
# 「わ、私を応援してくれたら好きなだけ尻尾触らせてあげます～～っ！！」
line = "「わ、私を応援してくれたら好きなだけ尻尾触らせてあげます～～っ！！」"

[[dialogue]]
speaker = "マトイ"
# 「……これ、どうするつもり？　個人的にはトワちゃん先生を応援して欲しいけど」
line = "「……これ、どうするつもり？　個人的にはトワちゃん先生を応援して欲しいけど」"

[[dialogue]]
speaker = "unk"
# トワ先生ーっ！　頑張れーっ！
line = "トワ先生ーっ！　頑張れーっ！"

[[dialogue]]
speaker = "unk"
# （全員を応援したいっ！　だけどここは……）
line = "（全員を応援したいっ！　だけどここは……）"

[[dialogue]]
speaker = "トワ先生"
# 「会長くんっ、ありがとうっ！　ウェディングフォーム、愛のパワーで最大出力だよっ！！」
line = "「会長くんっ、ありがとうっ！　ウェディングフォーム、愛のパワーで最大出力だよっ！！」"

[[dialogue]]
speaker = "ヨミ"
# 「こやぁぁんっ！　尻尾触らせるだけじゃ足りませんでしたかぁぁぁ」
line = "「こやぁぁんっ！　尻尾触らせるだけじゃ足りませんでしたかぁぁぁ」"

[[dialogue]]
speaker = "蘭美"
# 「仕方がないわ、華麗に勝利して愛も声援も勝ち取ればいいのよ」
line = "「仕方がないわ、華麗に勝利して愛も声援も勝ち取ればいいのよ」"

[[dialogue]]
speaker = "蘭美"
# 「さあ！　ヘレナ様が用意して下さったウェディングフォームの力、思い知りなさい！！」
line = "「さあ！　ヘレナ様が用意して下さったウェディングフォームの力、思い知りなさい！！」"

[[dialogue]]
speaker = "マトイ"
# 「では始めますっ」
line = "「では始めますっ」"

[[dialogue]]
speaker = "マトイ"
# 「レディー……ゴー！！」
line = "「レディー……ゴー！！」"
