[[dialogue]]
speaker = "シノ"
# 『星霊祭も２日目に突入です。引き続き、進行は新星学園学園長の十六夜シノと──』
line = "『星霊祭も２日目に突入です。引き続き、進行は新星学園学園長の十六夜シノと──』"

[[dialogue]]
speaker = "マグダレナ"
# 『《境界》のマグダレナでお送りいたします。現在、初日の玉入れで圧倒的勝利を収めた新星学園が得点で上回っています。このまま優勢を維持できるでしょうか？』
line = "『《境界》のマグダレナでお送りいたします。現在、初日の玉入れで圧倒的勝利を収めた新星学園が得点で上回っています。このまま優勢を維持できるでしょうか？』"

[[dialogue]]
speaker = "シノ"
# 『そうは問屋が卸さないのが好敵手である流星学園です。２日目最初の競技は、障害物競走になります』
line = "『そうは問屋が卸さないのが好敵手である流星学園です。２日目最初の競技は、障害物競走になります』"

[[dialogue]]
speaker = "美鶴"
# 「きっと、次も普通の障害物競走じゃないんだよね？」
line = "「きっと、次も普通の障害物競走じゃないんだよね？」"

[[dialogue]]
speaker = "モンスター"
# 「イ～～ッ！！」
line = "「イ～～ッ！！」"

[[dialogue]]
speaker = "モンスター"
# 「ンギャオォゥッ！！」
line = "「ンギャオォゥッ！！」"

[[dialogue]]
speaker = "カティア"
# 「わっ、今度こそモンスターですガオ！？」
line = "「わっ、今度こそモンスターですガオ！？」"

[[dialogue]]
speaker = "シノ"
# 『ご安心ください。それはシミュレーターによって投影されたモンスターです。しかし、その戦闘力は決して侮れません』
line = "『ご安心ください。それはシミュレーターによって投影されたモンスターです。しかし、その戦闘力は決して侮れません』"

[[dialogue]]
speaker = "マグダレナ"
# 『迫りくるモンスターたちを蹴散らしながら、ゴールを目指していただきます。星騎士の能力を存分に活かせる競技ですね』
line = "『迫りくるモンスターたちを蹴散らしながら、ゴールを目指していただきます。星騎士の能力を存分に活かせる競技ですね』"

[[dialogue]]
speaker = "美鶴"
# 「走りながら敵倒すとか、なかなかハードモードじゃん。うちらから出場するのは──」
line = "「走りながら敵倒すとか、なかなかハードモードじゃん。うちらから出場するのは──」"

[[dialogue]]
speaker = "unk"
# 俺が出る！
line = "俺が出る！"

[[dialogue]]
speaker = "マグダレナ"
# 『あらあら、新星学園は会長さん直々の出走ですね。対する流星学園は──』
line = "『あらあら、新星学園は会長さん直々の出走ですね。対する流星学園は──』"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「私が出る！　相手にとって不足はない！」
line = "「私が出る！　相手にとって不足はない！」"

[[dialogue]]
speaker = "シノ"
# 『流星学園からはアニュラスさんが出走です。実技試験では学年主席の実力者ですよ』
line = "『流星学園からはアニュラスさんが出走です。実技試験では学年主席の実力者ですよ』"

[[dialogue]]
speaker = "シノ"
# 『彼女は会長さんに対抗心を燃やしていますからね。注目の一戦となりそうです。目が離せませんね』
line = "『彼女は会長さんに対抗心を燃やしていますからね。注目の一戦となりそうです。目が離せませんね』"

[[dialogue]]
speaker = "フラン"
# 「我らが会長の出番だ！　みんなー、声を振り絞るぞー！　フレー、フレー、か・い・ちょ・う！」
line = "「我らが会長の出番だ！　みんなー、声を振り絞るぞー！　フレー、フレー、か・い・ちょ・う！」"

[[dialogue]]
speaker = "美鶴"
# 「フレー、フレー、会長さーん」
line = "「フレー、フレー、会長さーん」"

[[dialogue]]
speaker = "ミルフィー"
# 「フレー、フレー、会長くーん！　頑張ってーー！」
line = "「フレー、フレー、会長くーん！　頑張ってーー！」"

[[dialogue]]
speaker = "unk"
# 力が湧き出てくる……！
line = "力が湧き出てくる……！"

[[dialogue]]
speaker = "unk"
# みんなの声援が……！
line = "みんなの声援が……！"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「大した応援だな。だが、私にも負けられない理由がある！」
line = "「大した応援だな。だが、私にも負けられない理由がある！」"

[[dialogue]]
speaker = "シノ"
# 『それでは各選手、位置について──よーい……ドン！』
line = "『それでは各選手、位置について──よーい……ドン！』"

[[dialogue]]
speaker = "ミルフィー"
# 「きゃーっ♪　会長くん、いいスタートだよー！　いけいけ！　ゴーゴー！　ジャーンプ！」
line = "「きゃーっ♪　会長くん、いいスタートだよー！　いけいけ！　ゴーゴー！　ジャーンプ！」"

[[dialogue]]
speaker = "モンスター"
# 「イーッ！」
line = "「イーッ！」"

[[dialogue]]
speaker = "unk"
# 邪魔だっ！
line = "邪魔だっ！"

[[dialogue]]
speaker = "モンスター"
# 「イ～～ッ……」
line = "「イ～～ッ……」"

[[dialogue]]
speaker = "マグダレナ"
# 『さすがは星徒会長ですね。腕の一振りごとに、モンスターたちが星屑のように消えていきます』
line = "『さすがは星徒会長ですね。腕の一振りごとに、モンスターたちが星屑のように消えていきます』"

[[dialogue]]
speaker = "カティア"
# 「さすがは魔王様ですワン！　いっけー！」
line = "「さすがは魔王様ですワン！　いっけー！」"

[[dialogue]]
speaker = "モンスター"
# 「ギャオーーゥ！」
line = "「ギャオーーゥ！」"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「ぐっ……！？　こいつ、本当に投影されたモンスターか……！？　見かけによらず手強い！」
line = "「ぐっ……！？　こいつ、本当に投影されたモンスターか……！？　見かけによらず手強い！」"

[[dialogue]]
speaker = "マグダレナ"
# 『アニュラスさんは少しモンスターの対処に追われているようですね』
line = "『アニュラスさんは少しモンスターの対処に追われているようですね』"

[[dialogue]]
speaker = "シノ"
# 『星徒会長の面目躍如です！　２日目も新星学園の勝利となるのでしょうか！』
line = "『星徒会長の面目躍如です！　２日目も新星学園の勝利となるのでしょうか！』"

[[dialogue]]
speaker = "unk"
# （この勝負……もらったっ！）
line = "（この勝負……もらったっ！）"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「──今『もらった』と思ったか？　そう易々と勝利を譲るものかっ！」
line = "「──今『もらった』と思ったか？　そう易々と勝利を譲るものかっ！」"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「油断大敵だな！　勝ったと思ったその瞬間、最大の隙が生まれる！」
line = "「油断大敵だな！　勝ったと思ったその瞬間、最大の隙が生まれる！」"

[[dialogue]]
speaker = "シノ"
# 『いえ、まだでした！　懸命に食らいつくアニュラスさん、勝負はついていません！』
line = "『いえ、まだでした！　懸命に食らいつくアニュラスさん、勝負はついていません！』"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「負けん……！　負けないぞっ！」
line = "「負けん……！　負けないぞっ！」"

[[dialogue]]
speaker = "シノ"
# 『緋宮会長に燃やすのは対抗心か、執念か、はたまたそれとも！　アニュラス選手の猛追ですっ！』
line = "『緋宮会長に燃やすのは対抗心か、執念か、はたまたそれとも！　アニュラス選手の猛追ですっ！』"

[[dialogue]]
speaker = "美鶴"
# 「なかなかやるね。一気に追いついてきた……会長さんの真後ろ──もう射程圏内じゃん」
line = "「なかなかやるね。一気に追いついてきた……会長さんの真後ろ──もう射程圏内じゃん」"

[[dialogue]]
speaker = "フラン"
# 「うおおお、激アツ展開だぁっ！　だけど会長、あんたならやれる！　負けたりしねえよなっ！　なあっ！」
line = "「うおおお、激アツ展開だぁっ！　だけど会長、あんたならやれる！　負けたりしねえよなっ！　なあっ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「会長くんっ、がんばれーーっ！　抜かれちゃダメーっ！」
line = "「会長くんっ、がんばれーーっ！　抜かれちゃダメーっ！」"

[[dialogue]]
speaker = "美鶴"
# 「会長さん、がんばれ、がんばれー」
line = "「会長さん、がんばれ、がんばれー」"

[[dialogue]]
speaker = "カティア"
# 「魔王様ーっ！　負けちゃイヤですーーーっ！」
line = "「魔王様ーっ！　負けちゃイヤですーーーっ！」"

[[dialogue]]
speaker = "ヒヨ"
# 「根性みせろ、根性ーっ！」
line = "「根性みせろ、根性ーっ！」"

[[dialogue]]
speaker = "unk"
# みんなの声援が届く。胸の内から力が湧く。
line = "みんなの声援が届く。胸の内から力が湧く。"

[[dialogue]]
speaker = "unk"
# 新星学園星徒会長の名に懸けて……後に繋ぐためにも、負けるわけにはいかないっ！
line = "新星学園星徒会長の名に懸けて……後に繋ぐためにも、負けるわけにはいかないっ！"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「負けんっ、お前にだけはっ！　うおおおおおおおおおおっっっ！」
line = "「負けんっ、お前にだけはっ！　うおおおおおおおおおおっっっ！」"

[[dialogue]]
speaker = "unk"
# うおおおおおおおおおおおっっっ！！
line = "うおおおおおおおおおおおっっっ！！"

[[dialogue]]
speaker = "unk"
# みんな、俺に力を貸してくれっ！
line = "みんな、俺に力を貸してくれっ！"

[[dialogue]]
speaker = "シノ"
# 『ゴーーーーーーーーール、インッ！！！　ほぼ同着ですっ！』
line = "『ゴーーーーーーーーール、インッ！！！　ほぼ同着ですっ！』"

[[dialogue]]
speaker = "マグダレナ"
# 『カメラ判定に持ち越されますので、今しばらくお待ちくださーい』
line = "『カメラ判定に持ち越されますので、今しばらくお待ちくださーい』"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「はぁっ、はぁ、はぁっ……！　どっちだ……！？　私は勝ったのか……！？」
line = "「はぁっ、はぁ、はぁっ……！　どっちだ……！？　私は勝ったのか……！？」"

[[dialogue]]
speaker = "美鶴"
# 「会長さんの方が、ちょっと早かったよね……？」
line = "「会長さんの方が、ちょっと早かったよね……？」"

[[dialogue]]
speaker = "ミルフィー"
# 「わからないけど、た、たぶん……！　大丈夫だよねっ……！？」
line = "「わからないけど、た、たぶん……！　大丈夫だよねっ……！？」"

[[dialogue]]
speaker = "シノ"
# 『さぁ、注目のカメラ判定が出ました。結果は──』
line = "『さぁ、注目のカメラ判定が出ました。結果は──』"

[[dialogue]]
speaker = "unk"
# アリーナの大画面モニターにゴールテープを切った瞬間が映された。
line = "アリーナの大画面モニターにゴールテープを切った瞬間が映された。"

[[dialogue]]
speaker = "ミルフィー"
# 「ア、アレって！　先にゴールテープを切ったのは──」
line = "「ア、アレって！　先にゴールテープを切ったのは──」"

[[dialogue]]
speaker = "美鶴"
# 「会長さんだ。やっぱりね」
line = "「会長さんだ。やっぱりね」"

[[dialogue]]
speaker = "シノ"
# 『ギリギリのムネ差！　アニュラスさんも頑張りましたが、勝者は緋宮会長！　新星学園の勝利です！』
line = "『ギリギリのムネ差！　アニュラスさんも頑張りましたが、勝者は緋宮会長！　新星学園の勝利です！』"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「くうぅ……っ！　私のバストがもう少し大きければ！」
line = "「くうぅ……っ！　私のバストがもう少し大きければ！」"

[[dialogue]]
speaker = "unk"
# （それ以上大きくなったら不利になりそうだけど……）
line = "（それ以上大きくなったら不利になりそうだけど……）"

[[dialogue]]
speaker = "カティア"
# 「魔王様の勝ちですーっ！」
line = "「魔王様の勝ちですーっ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「やったーーーっ！　さすがは会長くんだよーーーっ！！」
line = "「やったーーーっ！　さすがは会長くんだよーーーっ！！」"

[[dialogue]]
speaker = "美鶴"
# 「すっごいギリギリだったね。勝負を分けたのは……うちらの応援の力だったりする……？」
line = "「すっごいギリギリだったね。勝負を分けたのは……うちらの応援の力だったりする……？」"

[[dialogue]]
speaker = "unk"
# みんな、応援ありがとうー！
line = "みんな、応援ありがとうー！"

[[dialogue]]
speaker = "unk"
# 声援がなかったら、俺の負けだったよ
line = "声援がなかったら、俺の負けだったよ"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「あと一歩、いや半歩のところで、勝利に手が届かなかったか……！　不甲斐ない……！」
line = "「あと一歩、いや半歩のところで、勝利に手が届かなかったか……！　不甲斐ない……！」"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「なぜ私は勝てなかった……あと半歩、私に何が足りなかったのだ……」
line = "「なぜ私は勝てなかった……あと半歩、私に何が足りなかったのだ……」"

[[dialogue]]
speaker = "ミネコ"
# 「んー、星霊祭は個人戦じゃなくて、団体戦だから、じゃないかなー」
line = "「んー、星霊祭は個人戦じゃなくて、団体戦だから、じゃないかなー」"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「それはどういう意味だ……？」
line = "「それはどういう意味だ……？」"

[[dialogue]]
speaker = "ミネコ"
# 「アニュラスさんはさ、会長に勝とうとしてたでしょ？」
line = "「アニュラスさんはさ、会長に勝とうとしてたでしょ？」"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「もちろんだ。勝つことのみを考えて──」
line = "「もちろんだ。勝つことのみを考えて──」"

[[dialogue]]
speaker = "ミネコ"
# 「それだよ。会長を負かそうとして──個人の勝利って宝石に目が眩んでいた」
line = "「それだよ。会長を負かそうとして──個人の勝利って宝石に目が眩んでいた」"

[[dialogue]]
speaker = "ミネコ"
# 「でも会長は個人じゃなくて、新星学園のための勝利を掴もうとした。だから、みんなの声援を受けて、それを力に変えた」
line = "「でも会長は個人じゃなくて、新星学園のための勝利を掴もうとした。だから、みんなの声援を受けて、それを力に変えた」"

[[dialogue]]
speaker = "ミネコ"
# 「アニュラスさんにみんなの声援、届いてた？」
line = "「アニュラスさんにみんなの声援、届いてた？」"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「私への応援……？」
line = "「私への応援……？」"

[[dialogue]]
speaker = "流星生徒Ａ"
# 「アニュラスさーん！　惜しかったよー！」
line = "「アニュラスさーん！　惜しかったよー！」"

[[dialogue]]
speaker = "流星生徒Ｂ"
# 「次は絶対に勝てる！　応援してるからねー！」
line = "「次は絶対に勝てる！　応援してるからねー！」"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「なるほど。勝利に目が眩み、視界が狭まっていた私が愚かだったということか……敗北も道理……」
line = "「なるほど。勝利に目が眩み、視界が狭まっていた私が愚かだったということか……敗北も道理……」"

[[dialogue]]
speaker = "ミネコ"
# 「それがわかったなら、次は大丈夫だね！」
line = "「それがわかったなら、次は大丈夫だね！」"

[[dialogue]]
speaker = "アニュラス（覚醒）"
# 「ああ、次こそは……負けない！」
line = "「ああ、次こそは……負けない！」"
