[[dialogue]]
speaker = "unk"
# バトルウィーク６日目。寮生たちがパトロールを終えて、全員帰宅した後──
line = "バトルウィーク６日目。寮生たちがパトロールを終えて、全員帰宅した後──"

[[dialogue]]
speaker = "unk"
# <ruby=エトワール・イルソーレ>『白昼の極星』</ruby>こと千園寺ヒルディオーネと、<ruby=エトワール・ラルーナ>『宵闇の極星』</ruby>こと妃竜院マハムートは、寮のテーブルを挟んで静かに向かい合っていた。
line = "<ruby>『白昼の極星』<rt>エトワール・イルソーレ</rt></ruby>こと千園寺ヒルディオーネと、<ruby>『宵闇の極星』<rt>エトワール・ラルーナ</rt></ruby>こと妃竜院マハムートは、寮のテーブルを挟んで静かに向かい合っていた。"

[[dialogue]]
speaker = "unk"
# （流れで同席したけど……）
line = "（流れで同席したけど……）"

[[dialogue]]
speaker = "マハムート"
# 「相変わらず、機能性無視の美術品だらけで、悪趣味なロビーね……」
line = "「相変わらず、機能性無視の美術品だらけで、悪趣味なロビーね……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「おーっほっほっほっ！　高貴なものの価値は、高貴な心の持ち主にしか分からないということですわ！」
line = "「おーっほっほっほっ！　高貴なものの価値は、高貴な心の持ち主にしか分からないということですわ！」"

[[dialogue]]
speaker = "マハムート"
# 「あのねぇ……これでも私は、魔界の貴族なのよ？」
line = "「あのねぇ……これでも私は、魔界の貴族なのよ？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「もちろん、存じておりますわ。魔界で３０００年以上……いいえ、<b>有史以前</b>から続くと言われる竜の一族ですもの」
line = "「もちろん、存じておりますわ。魔界で３０００年以上……いいえ、<b>有史以前</b>から続くと言われる竜の一族ですもの」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「あなた方からすれば流星市国の『五名門』程度、最近勢いづいてきただけの成金に見えるのでしょう」
line = "「あなた方からすれば流星市国の『五名門』程度、最近勢いづいてきただけの成金に見えるのでしょう」"

[[dialogue]]
speaker = "マハムート"
# 「……別にそこまで言うつもりはないわよ」
line = "「……別にそこまで言うつもりはないわよ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「いえ、千園寺が力を持ったのは宇宙開発事業が成功してからのこと。歴史の浅さを隠すつもりはありませんわ」
line = "「いえ、千園寺が力を持ったのは宇宙開発事業が成功してからのこと。歴史の浅さを隠すつもりはありませんわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「――ですが、だからこそ、と言えますわ」
line = "「――ですが、だからこそ、と言えますわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「寮長であり、家名を背負う者だからこそ、それに相応しい教養や振る舞いが求められるんですの」
line = "「寮長であり、家名を背負う者だからこそ、それに相応しい教養や振る舞いが求められるんですの」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「リーダーに相応しい振る舞いがあってこそ、仲間たちは躊躇いを捨てて付いてきてくれるのですから」
line = "「リーダーに相応しい振る舞いがあってこそ、仲間たちは躊躇いを捨てて付いてきてくれるのですから」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「その箔付けにお金が必要ならお金を使い、教養が必要なら教養を使う。歴史の浅い我々には、手段を選んでいる余裕なんてありませんの」
line = "「その箔付けにお金が必要ならお金を使い、教養が必要なら教養を使う。歴史の浅い我々には、手段を選んでいる余裕なんてありませんの」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「歴史の重みを知ればこそ、足りない物を補わなければ、決して追いつくことは敵わないのですから」
line = "「歴史の重みを知ればこそ、足りない物を補わなければ、決して追いつくことは敵わないのですから」"

[[dialogue]]
speaker = "マハムート"
# 「ふっ……ふふっ……あははははっ！」
line = "「ふっ……ふふっ……あははははっ！」"

[[dialogue]]
speaker = "unk"
# （マムが……本気で笑ってる？）
line = "（マムが……本気で笑ってる？）"

[[dialogue]]
speaker = "マハムート"
# 「はーっ……どうやら、まだまだ私も、あなたのことを見誤っていたようね」
line = "「はーっ……どうやら、まだまだ私も、あなたのことを見誤っていたようね」"

[[dialogue]]
speaker = "マハムート"
# 「ヒルディー、あなたの言ってることは、何も間違っていないわ」
line = "「ヒルディー、あなたの言ってることは、何も間違っていないわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「マム……？」
line = "「マム……？」"

[[dialogue]]
speaker = "マハムート"
# 「ええ、ええ。その通りよ。持てる手段のすべてを用い、ただ勝利という結果をもたらす」
line = "「ええ、ええ。その通りよ。持てる手段のすべてを用い、ただ勝利という結果をもたらす」"

[[dialogue]]
speaker = "マハムート"
# 「我々高貴なる者に求められるのは、ただただ、その勝利だけだわ」
line = "「我々高貴なる者に求められるのは、ただただ、その勝利だけだわ」"

[[dialogue]]
speaker = "マハムート"
# 「私に芸術や教養はわからないけれど、それがあなたの持てる手段、勝つための努力だというのなら、認めなければならないわ」
line = "「私に芸術や教養はわからないけれど、それがあなたの持てる手段、勝つための努力だというのなら、認めなければならないわ」"

[[dialogue]]
speaker = "マハムート"
# 「千園寺ヒルディオーネ。確かにあなたは私のライバルよ。……いつか必ず、あなたを私の元に跪かせてあげるから、覚悟なさい」
line = "「千園寺ヒルディオーネ。確かにあなたは私のライバルよ。……いつか必ず、あなたを私の元に跪かせてあげるから、覚悟なさい」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「っ……ふふっ、おーっほっほっほ！　実にエレガントですわ、妃竜院マハムート！」
line = "「っ……ふふっ、おーっほっほっほ！　実にエレガントですわ、妃竜院マハムート！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「私はこれまで、どんな不可能も打ち砕いてきましたわ。だからマム、あなたという壁も必ず、最後には優雅に打ち砕いてさしあげましてよ！」
line = "「私はこれまで、どんな不可能も打ち砕いてきましたわ。だからマム、あなたという壁も必ず、最後には優雅に打ち砕いてさしあげましてよ！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ただし、あくまで<b>優雅に</b>、ですわ！　あなたは努力と言いましたけど、そこだけは訂正させて頂きますわ」
line = "「ただし、あくまで<b>優雅に</b>、ですわ！　あなたは努力と言いましたけど、そこだけは訂正させて頂きますわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「努力とは、高貴な者ならばして当然のこと。それをわざわざ口にすることを控えるのがエレガントというものでしてよ」
line = "「努力とは、高貴な者ならばして当然のこと。それをわざわざ口にすることを控えるのがエレガントというものでしてよ」"

[[dialogue]]
speaker = "マハムート"
# 「ふふっ……いいわね。とてもいいわ。私も久々に、竜の血が騒いできた感じがするもの」
line = "「ふふっ……いいわね。とてもいいわ。私も久々に、竜の血が騒いできた感じがするもの」"

[[dialogue]]
speaker = "マハムート"
# 「――今日が終わった時点で、今月の討伐スコアはＳクラスモンスター１体分、流星寮がリード……で合っているわよね？」
line = "「――今日が終わった時点で、今月の討伐スコアはＳクラスモンスター１体分、流星寮がリード……で合っているわよね？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ええ、その通りですわ。あのポイント差を、よくぞこの短期間で埋めたもの。賞賛に値しますわ」
line = "「ええ、その通りですわ。あのポイント差を、よくぞこの短期間で埋めたもの。賞賛に値しますわ」"

[[dialogue]]
speaker = "マハムート"
# 「それは、ここにいる会長のおかげよ。彼が今の<ruby=ラルーナ>新星寮</ruby>に足りなかったものを補ってくれた」
line = "「それは、ここにいる会長のおかげよ。彼が今の<ruby>新星寮<rt>ラルーナ</rt></ruby>に足りなかったものを補ってくれた」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「なるほど……ふふっ、それを聞いてしまったら、ますます<ruby=イルソーレ>流星寮</ruby>に欲しくなってしまいますわね」
line = "「なるほど……ふふっ、それを聞いてしまったら、ますます<ruby>流星寮<rt>イルソーレ</rt></ruby>に欲しくなってしまいますわね」"

[[dialogue]]
speaker = "マハムート"
# 「おあいにく様。最後に勝つのは私達よ。……けれど、このイベントがなければ、今月は負けていたでしょうね」
line = "「おあいにく様。最後に勝つのは私達よ。……けれど、このイベントがなければ、今月は負けていたでしょうね」"

[[dialogue]]
speaker = "マハムート"
# 「私たちの闘争心に火をつけてくれて、感謝しているわ。ヒルディオーネ」
line = "「私たちの闘争心に火をつけてくれて、感謝しているわ。ヒルディオーネ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「何を勝ち誇っていますの。まだ私たちがリードしているんですのよ？」
line = "「何を勝ち誇っていますの。まだ私たちがリードしているんですのよ？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「確かに賞賛に値する追い上げではありましたが、Ｓクラス１体分は決して小さなスコアではありませんわ」
line = "「確かに賞賛に値する追い上げではありましたが、Ｓクラス１体分は決して小さなスコアではありませんわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「そして、明日は学園も休みの日……。<ruby=イルソーレ>流星寮</ruby>総出でパトロールを行えば、これをひっくり返すのは不可能でしてよ！」
line = "「そして、明日は学園も休みの日……。<ruby>流星寮<rt>イルソーレ</rt></ruby>総出でパトロールを行えば、これをひっくり返すのは不可能でしてよ！」"

[[dialogue]]
speaker = "マハムート"
# 「確かに簡単ではないわね。でも、不可能というほど絶望的な差ではないわ。あと一歩、頑張れば届くところまで来ている」
line = "「確かに簡単ではないわね。でも、不可能というほど絶望的な差ではないわ。あと一歩、頑張れば届くところまで来ている」"

[[dialogue]]
speaker = "マハムート"
# 「それに……戦いは逆境ほど燃える。そうでしょう？」
line = "「それに……戦いは逆境ほど燃える。そうでしょう？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「……言いますわね。ならば、受けて立ちましょう」
line = "「……言いますわね。ならば、受けて立ちましょう」"

[[dialogue]]
speaker = "マハムート"
# 「私たちも、明日のパトロールはこれまで以上の人数で計画しているんですもの」
line = "「私たちも、明日のパトロールはこれまで以上の人数で計画しているんですもの」"

[[dialogue]]
speaker = "マハムート"
# 「最終日、総力戦と行こうじゃないの」
line = "「最終日、総力戦と行こうじゃないの」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「望むところですわ……！」
line = "「望むところですわ……！」"

[[dialogue]]
speaker = "unk"
# ２人は不敵に、楽しそうに笑い合う。ここまで来たら勝ちたいと、俺も心が強く燃えている。
line = "２人は不敵に、楽しそうに笑い合う。ここまで来たら勝ちたいと、俺も心が強く燃えている。"

[[dialogue]]
speaker = "unk"
# こうして、運命の最終日が幕を開ける――
line = "こうして、運命の最終日が幕を開ける――"
