[[dialogue]]
speaker = "梨緒"
# 「みんな、警戒を怠らないようにな。あの新星星徒会が途中脱落した新モードだ。何が起こるかわからない」
line = "「みんな、警戒を怠らないようにな。あの新星星徒会が途中脱落した新モードだ。何が起こるかわからない」"

[[dialogue]]
speaker = "ベアトリス"
# 「一筋縄ではいかない強敵とか待ってるのかも。ちょっと緊張してきた……」
line = "「一筋縄ではいかない強敵とか待ってるのかも。ちょっと緊張してきた……」"

[[dialogue]]
speaker = "アポロ"
# 「むしろ燃えるじゃんかっ。あたしたちのキズナの力、見せてやろーぜ！」
line = "「むしろ燃えるじゃんかっ。あたしたちのキズナの力、見せてやろーぜ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「そういえば、ジグには声をかけなかったんだ？　正気に戻ったわけだし、梨緒も一緒に過ごしたいんじゃない？」
line = "「そういえば、ジグには声をかけなかったんだ？　正気に戻ったわけだし、梨緒も一緒に過ごしたいんじゃない？」"

[[dialogue]]
speaker = "梨緒"
# 「……別に一緒に過ごしたいということはないが、もちろん声はかけた」
line = "「……別に一緒に過ごしたいということはないが、もちろん声はかけた」"

[[dialogue]]
speaker = "梨緒"
# 「だがあいつはこう言って断った。──『私がいると、つまらなくなってしまうだろう？』とな！」
line = "「だがあいつはこう言って断った。──『私がいると、つまらなくなってしまうだろう？』とな！」"

[[dialogue]]
speaker = "ナターシャ"
# 「あー、なんか想像できる～……」
line = "「あー、なんか想像できる～……」"

[[dialogue]]
speaker = "梨緒"
# 「さも当然のようにあんなセリフを……あの時のジグの顔は忘れないぞ……！」
line = "「さも当然のようにあんなセリフを……あの時のジグの顔は忘れないぞ……！」"

[[dialogue]]
speaker = "ベアトリス"
# 「どーどー……。落ち着いて、落ち着いて。それよりジグさんがビックリしちゃうような成果を、私たちで上げちゃおうよ！」
line = "「どーどー……。落ち着いて、落ち着いて。それよりジグさんがビックリしちゃうような成果を、私たちで上げちゃおうよ！」"

[[dialogue]]
speaker = "梨緒"
# 「ベアトっ……！　ああ、新星星徒会だけでなく、ジグの鼻も明かしてやろう！」
line = "「ベアトっ……！　ああ、新星星徒会だけでなく、ジグの鼻も明かしてやろう！」"

[[dialogue]]
speaker = "アポロ"
# 「……ん？　ちょっと待て。今そこで何か動いたぞ」
line = "「……ん？　ちょっと待て。今そこで何か動いたぞ」"

[[dialogue]]
speaker = "スクアルス"
# 「グルルッ、ギィィーー！！」
line = "「グルルッ、ギィィーー！！」"

[[dialogue]]
speaker = "ナターシャ"
# 「おっと、お出ましみたいだね。例のボスモンスターかな？」
line = "「おっと、お出ましみたいだね。例のボスモンスターかな？」"

[[dialogue]]
speaker = "アポロ"
# 「いきなりボスを見つけられるなんてラッキー！　クリアしたも同然じゃん！」
line = "「いきなりボスを見つけられるなんてラッキー！　クリアしたも同然じゃん！」"

[[dialogue]]
speaker = "梨緒"
# 「油断するな。アポロはともかく、私たち３人は水着フォームの力を得たばかりだ」
line = "「油断するな。アポロはともかく、私たち３人は水着フォームの力を得たばかりだ」"

[[dialogue]]
speaker = "ベアトリス"
# 「まずは新しい戦い方に慣れないとだよね。普段以上に慎重に立ち回った方がいいかも」
line = "「まずは新しい戦い方に慣れないとだよね。普段以上に慎重に立ち回った方がいいかも」"

[[dialogue]]
speaker = "ナターシャ"
# 「体も重いしね～。星力の扱いもなんかぎこちないし」
line = "「体も重いしね～。星力の扱いもなんかぎこちないし」"

[[dialogue]]
speaker = "アポロ"
# 「なら、あたしが引っ張っていってやるぜっ！　タイダルストライクっ！」
line = "「なら、あたしが引っ張っていってやるぜっ！　タイダルストライクっ！」"

[[dialogue]]
speaker = "スクアルス"
# 「ギァァッ……！」
line = "「ギァァッ……！」"

[[dialogue]]
speaker = "アポロ"
# 「あれ？　なんだコイツ、思ったより硬いな……」
line = "「あれ？　なんだコイツ、思ったより硬いな……」"

[[dialogue]]
speaker = "スクアルス"
# 「ギィィィーーーー！」
line = "「ギィィィーーーー！」"

[[dialogue]]
speaker = "ベアトリス"
# 「きゃあっ！？」
line = "「きゃあっ！？」"

[[dialogue]]
speaker = "梨緒"
# 「ベアトっ！　一旦下がるんだ、私がフォローするっ」
line = "「ベアトっ！　一旦下がるんだ、私がフォローするっ」"

[[dialogue]]
speaker = "ベアトリス"
# 「う、うんっ。ありがとう、梨緒ちゃん」
line = "「う、うんっ。ありがとう、梨緒ちゃん」"

[[dialogue]]
speaker = "ナターシャ"
# 「そこだよ」
line = "「そこだよ」"

[[dialogue]]
speaker = "スクアルス"
# 「ギャオオオン！」
line = "「ギャオオオン！」"

[[dialogue]]
speaker = "ナターシャ"
# 「って、私の攻撃も全然効いてないし。このボス、チートすぎない……？」
line = "「って、私の攻撃も全然効いてないし。このボス、チートすぎない……？」"

[[dialogue]]
speaker = "スクアルス"
# 「ギャオッ！」
line = "「ギャオッ！」"

[[dialogue]]
speaker = "梨緒"
# 「ぐあっ！！」
line = "「ぐあっ！！」"

[[dialogue]]
speaker = "アポロ"
# 「梨緒っ！？　大丈夫かっ！？」
line = "「梨緒っ！？　大丈夫かっ！？」"

[[dialogue]]
speaker = "梨緒"
# 「す、すまない、フォローすると言っておきながら……。水着フォームの影響か、体が思うように動かなくて……」
line = "「す、すまない、フォローすると言っておきながら……。水着フォームの影響か、体が思うように動かなくて……」"

[[dialogue]]
speaker = "スクアルス"
# 「ギィーーーッ！」
line = "「ギィーーーッ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「ここは撤退した方がいいね。このままだと全滅は時間の問題だ」
line = "「ここは撤退した方がいいね。このままだと全滅は時間の問題だ」"

[[dialogue]]
speaker = "アポロ"
# 「逃げるなんてヒーローのやることじゃないが……！　仲間を危険に晒すことはもっとヒーローのやることじゃないっ！」
line = "「逃げるなんてヒーローのやることじゃないが……！　仲間を危険に晒すことはもっとヒーローのやることじゃないっ！」"

[[dialogue]]
speaker = "梨緒"
# 「わかった……ここは一旦退くぞ！」
line = "「わかった……ここは一旦退くぞ！」"

[[dialogue]]
speaker = "アポロ"
# 「了解だ！　ナターシャはベアトを連れていってやってくれっ」
line = "「了解だ！　ナターシャはベアトを連れていってやってくれっ」"

[[dialogue]]
speaker = "ナターシャ"
# 「うん。掴まって、ベアト」
line = "「うん。掴まって、ベアト」"

[[dialogue]]
speaker = "ベアトリス"
# 「ありがとう、ナターシャちゃん……」
line = "「ありがとう、ナターシャちゃん……」"

[[dialogue]]
speaker = "アポロ"
# 「ここまで来たら、大丈夫そうだな」
line = "「ここまで来たら、大丈夫そうだな」"

[[dialogue]]
speaker = "ナターシャ"
# 「海の家には……人はいないみたいだね。サバイバルモードだからかな」
line = "「海の家には……人はいないみたいだね。サバイバルモードだからかな」"

[[dialogue]]
speaker = "ベアトリス"
# 「焼きそば……浜焼き……楽しみにしてたのに」
line = "「焼きそば……浜焼き……楽しみにしてたのに」"

[[dialogue]]
speaker = "梨緒"
# 「それよりみんな無事で良かった。モンスターには……負けてしまったが」
line = "「それよりみんな無事で良かった。モンスターには……負けてしまったが」"

[[dialogue]]
speaker = "ナターシャ"
# 「負けてはいないんじゃない？　ゲームオーバーは避けられたし、まだ終わってないよ」
line = "「負けてはいないんじゃない？　ゲームオーバーは避けられたし、まだ終わってないよ」"

[[dialogue]]
speaker = "ベアトリス"
# 「私も思った以上に星術の威力が出なかったから……。やっぱり新しい力を使いこなすのって難しいんだね」
line = "「私も思った以上に星術の威力が出なかったから……。やっぱり新しい力を使いこなすのって難しいんだね」"

[[dialogue]]
speaker = "アポロ"
# 「そのことなんだけど……なんかおかしいと思うんだ」
line = "「そのことなんだけど……なんかおかしいと思うんだ」"

[[dialogue]]
speaker = "梨緒"
# 「おかしい？」
line = "「おかしい？」"

[[dialogue]]
speaker = "アポロ"
# 「あたしもどーも体が重いんだよ。星力も上手く扱えないし。みんなより水着フォームに慣れてるはずなのにさ」
line = "「あたしもどーも体が重いんだよ。星力も上手く扱えないし。みんなより水着フォームに慣れてるはずなのにさ」"

[[dialogue]]
speaker = "ナターシャ"
# 「つまり、全員の力に制限がかかってるってこと？　一体何が起きて──」
line = "「つまり、全員の力に制限がかかってるってこと？　一体何が起きて──」"

[[dialogue]]
speaker = "水着フワッチ"
# 「イーーーーッ！」
line = "「イーーーーッ！」"

[[dialogue]]
speaker = "梨緒"
# 「くっ、ここにもモンスターがいたか……。みんな、戦えるか？」
line = "「くっ、ここにもモンスターがいたか……。みんな、戦えるか？」"

[[dialogue]]
speaker = "ベアトリス"
# 「う、うんっ。ここで逃げたら、またあのボスと出くわしちゃいそうだしっ」
line = "「う、うんっ。ここで逃げたら、またあのボスと出くわしちゃいそうだしっ」"

[[dialogue]]
speaker = "アポロ"
# 「考えるのは後にした方が良さそうだなっ。来るぞっ！」
line = "「考えるのは後にした方が良さそうだなっ。来るぞっ！」"

[[dialogue]]
speaker = "水着フワッチ"
# 「イィィーーッ！！」
line = "「イィィーーッ！！」"

[[dialogue]]
speaker = "水着フワッチ"
# 「イ～～……」
line = "「イ～～……」"

[[dialogue]]
speaker = "梨緒"
# 「はぁはぁ、なんとか勝てた……」
line = "「はぁはぁ、なんとか勝てた……」"

[[dialogue]]
speaker = "梨緒"
# 「──！？　今のは……？」
line = "「──！？　今のは……？」"

[[dialogue]]
speaker = "ベアトリス"
# 「不思議……さっきより体に力が漲ってるような気がする……」
line = "「不思議……さっきより体に力が漲ってるような気がする……」"

[[dialogue]]
speaker = "アポロ"
# 「ベアトもか？　あたしも今のモンスターを倒してから、身軽になったよーな感じがするぞ！」
line = "「ベアトもか？　あたしも今のモンスターを倒してから、身軽になったよーな感じがするぞ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「なるほどね。新モードのカラクリがわかったよ」
line = "「なるほどね。新モードのカラクリがわかったよ」"

[[dialogue]]
speaker = "梨緒"
# 「カラクリ？」
line = "「カラクリ？」"

[[dialogue]]
speaker = "ナターシャ"
# 「ほらマトイとアナが言ってたじゃない。レベルが低かったやら、雑魚狩りが大事だったやら」
line = "「ほらマトイとアナが言ってたじゃない。レベルが低かったやら、雑魚狩りが大事だったやら」"

[[dialogue]]
speaker = "ナターシャ"
# 「要するに、このモードでは弱いモンスターを倒してレベルアップして、ボスモンスターに挑戦しろってことじゃない？」
line = "「要するに、このモードでは弱いモンスターを倒してレベルアップして、ボスモンスターに挑戦しろってことじゃない？」"

[[dialogue]]
speaker = "梨緒"
# 「なるほど……。あれは私を指して口にしていた言葉ではなかったのか……」
line = "「なるほど……。あれは私を指して口にしていた言葉ではなかったのか……」"

[[dialogue]]
speaker = "ベアトリス"
# 「だからそう言ったよ～！　誰も梨緒ちゃんのことを悪くなんて言わないってばぁ～！」
line = "「だからそう言ったよ～！　誰も梨緒ちゃんのことを悪くなんて言わないってばぁ～！」"

[[dialogue]]
speaker = "アポロ"
# 「じゃあ新星星徒会がゲームオーバーになったのは、レベルアップしないでボスモンスターに挑んだからなのか？」
line = "「じゃあ新星星徒会がゲームオーバーになったのは、レベルアップしないでボスモンスターに挑んだからなのか？」"

[[dialogue]]
speaker = "ナターシャ"
# 「たぶんそうじゃない？　ヴィーナスあたりがそのルールを理解せずに突っ込んで総崩れになったとか」
line = "「たぶんそうじゃない？　ヴィーナスあたりがそのルールを理解せずに突っ込んで総崩れになったとか」"

[[dialogue]]
speaker = "ベアトリス"
# 「ありえそう……って思うのは失礼かな……あはは」
line = "「ありえそう……って思うのは失礼かな……あはは」"

[[dialogue]]
speaker = "ナターシャ"
# 「ま、私たちが全滅しなかったのは梨緒の判断のおかげだね。変に自信家じゃない分、慎重な立ち回りができたわけだし」
line = "「ま、私たちが全滅しなかったのは梨緒の判断のおかげだね。変に自信家じゃない分、慎重な立ち回りができたわけだし」"

[[dialogue]]
speaker = "梨緒"
# 「ナターシャ……」
line = "「ナターシャ……」"

[[dialogue]]
speaker = "ナターシャ"
# 「ふふ。まぁボスモンスターには勝てなかったわけだけど。でも、一度敵わなかったくらいで諦める性格でもないでしょ？」
line = "「ふふ。まぁボスモンスターには勝てなかったわけだけど。でも、一度敵わなかったくらいで諦める性格でもないでしょ？」"

[[dialogue]]
speaker = "梨緒"
# 「ああ……もちろんだっ！　みんなでレベルアップして、ボスモンスターを倒せるように成長しよう！」
line = "「ああ……もちろんだっ！　みんなでレベルアップして、ボスモンスターを倒せるように成長しよう！」"

[[dialogue]]
speaker = "３人"
# 「おー！！！」
line = "「おー！！！」"
