[[dialogue]]
speaker = "ナターシャ"
# 「酷い目に遭った……」
line = "「酷い目に遭った……」"

[[dialogue]]
speaker = "アポロ"
# 「あはは、オーバーだなぁ。カブトムシはロマンなんだぞ？」
line = "「あはは、オーバーだなぁ。カブトムシはロマンなんだぞ？」"

[[dialogue]]
speaker = "ベアトリス"
# 「ついつい遊び過ぎちゃったね。本来の目的、ちょっぴり忘れちゃってたかも」
line = "「ついつい遊び過ぎちゃったね。本来の目的、ちょっぴり忘れちゃってたかも」"

[[dialogue]]
speaker = "梨緒"
# 「焦ることはない。リゾートも満喫して、その上でクリアもする。それでこそ新星星徒会に完全勝利したと言えるはずだ」
line = "「焦ることはない。リゾートも満喫して、その上でクリアもする。それでこそ新星星徒会に完全勝利したと言えるはずだ」"

[[dialogue]]
speaker = "ナターシャ"
# 「それにサバイバルでキツいのはここからだよ？　そろそろ食糧調達や、<ruby=まき>薪</ruby>集めに動いた方がいいんじゃない？」
line = "「それにサバイバルでキツいのはここからだよ？　そろそろ食糧調達や、<ruby>薪<rt>まき</rt></ruby>集めに動いた方がいいんじゃない？」"

[[dialogue]]
speaker = "アポロ"
# 「野営の準備ってヤツか？　そーいうのやってみたかったんだ！」
line = "「野営の準備ってヤツか？　そーいうのやってみたかったんだ！」"

[[dialogue]]
speaker = "ベアトリス"
# 「ふふ、ならせっかくだし、寝床は海の家を使わずビーチに作ろっか」
line = "「ふふ、ならせっかくだし、寝床は海の家を使わずビーチに作ろっか」"

[[dialogue]]
speaker = "梨緒"
# 「賛成だ。見通しがいい分、モンスターの奇襲も避けられる」
line = "「賛成だ。見通しがいい分、モンスターの奇襲も避けられる」"

[[dialogue]]
speaker = "ナターシャ"
# 「んじゃ日が暮れる前に行動開始といきますか」
line = "「んじゃ日が暮れる前に行動開始といきますか」"

[[dialogue]]
speaker = "ベアトリス"
# 「ぷはっ。お魚いっぱい獲れたよ～！」
line = "「ぷはっ。お魚いっぱい獲れたよ～！」"

[[dialogue]]
speaker = "アポロ"
# 「泳ぎ上手になったじゃねーか。素潜りでそれだけ魚を獲れるなんて大したもんだ」
line = "「泳ぎ上手になったじゃねーか。素潜りでそれだけ魚を獲れるなんて大したもんだ」"

[[dialogue]]
speaker = "ベアトリス"
# 「えへへ、みんなのおかげだよ。海で鬼ごっことか潜水勝負とか色々遊んでくれたから」
line = "「えへへ、みんなのおかげだよ。海で鬼ごっことか潜水勝負とか色々遊んでくれたから」"

[[dialogue]]
speaker = "ナターシャ"
# 「意外と訓練になってるのかもね。私もさっきのビーチバレーでコツを掴んだ気がするし」
line = "「意外と訓練になってるのかもね。私もさっきのビーチバレーでコツを掴んだ気がするし」"

[[dialogue]]
speaker = "梨緒"
# 「何事も無駄じゃないということだな」
line = "「何事も無駄じゃないということだな」"

[[dialogue]]
speaker = "アポロ"
# 「あたしの方は……おっと、竿に引きが来た。木の枝の竿でも、なかなか釣れるもんだな」
line = "「あたしの方は……おっと、竿に引きが来た。木の枝の竿でも、なかなか釣れるもんだな」"

[[dialogue]]
speaker = "アポロ"
# 「おっしゃ、１１匹目っ！　釣り勝負はまたあたしのリードだな、梨緒っ！」
line = "「おっしゃ、１１匹目っ！　釣り勝負はまたあたしのリードだな、梨緒っ！」"

[[dialogue]]
speaker = "梨緒"
# 「なんの、私も竿がしなってる。まだまだ追いつけるぞっ！」
line = "「なんの、私も竿がしなってる。まだまだ追いつけるぞっ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「やれやれ、いったい何匹釣るつもりなのやら……」
line = "「やれやれ、いったい何匹釣るつもりなのやら……」"

[[dialogue]]
speaker = "ナターシャ"
# 「寝床はこれでよし、と。枝葉で作った簡易的なテントだけど十分でしょ」
line = "「寝床はこれでよし、と。枝葉で作った簡易的なテントだけど十分でしょ」"

[[dialogue]]
speaker = "ナターシャ"
# 「飲み水も確保しないとね。とりあえずヤシの実は採れるだけ採っておいたけど」
line = "「飲み水も確保しないとね。とりあえずヤシの実は採れるだけ採っておいたけど」"

[[dialogue]]
speaker = "ベアトリス"
# 「水ならあっちに綺麗な川があったよ。煮沸が必要だから、飲めるのは火の準備ができてからになるけど」
line = "「水ならあっちに綺麗な川があったよ。煮沸が必要だから、飲めるのは火の準備ができてからになるけど」"

[[dialogue]]
speaker = "アポロ"
# 「にしてもテキパキしてるな……。みんな、こういうの慣れてるのか？」
line = "「にしてもテキパキしてるな……。みんな、こういうの慣れてるのか？」"

[[dialogue]]
speaker = "ベアトリス"
# 「これでも魔界を旅したこともあるから」
line = "「これでも魔界を旅したこともあるから」"

[[dialogue]]
speaker = "ナターシャ"
# 「サバイバル訓練は一通り受けているからね」
line = "「サバイバル訓練は一通り受けているからね」"

[[dialogue]]
speaker = "梨緒"
# 「私もガールスカウトで幾度かキャンプをした経験があるんだ」
line = "「私もガールスカウトで幾度かキャンプをした経験があるんだ」"

[[dialogue]]
speaker = "アポロ"
# 「へ～、すごいな！　あたしはこーいうの初めてだからな！　色々と教えてくれ！」
line = "「へ～、すごいな！　あたしはこーいうの初めてだからな！　色々と教えてくれ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「もちろんいいよ。薪の選び方は、なるべく乾いているものを──ひぃええぇっ！？」
line = "「もちろんいいよ。薪の選び方は、なるべく乾いているものを──ひぃええぇっ！？」"

[[dialogue]]
speaker = "梨緒"
# 「どうしたんだ、素っ頓狂な声を上げて？」
line = "「どうしたんだ、素っ頓狂な声を上げて？」"

[[dialogue]]
speaker = "ナターシャ"
# 「むむむ、虫がっ！　枯れ木の中からうねうねした気持ち悪いものがぁ！」
line = "「むむむ、虫がっ！　枯れ木の中からうねうねした気持ち悪いものがぁ！」"

[[dialogue]]
speaker = "ベアトリス"
# 「なんだ、幼虫じゃない。摘まんでポイっとすればいいよ」
line = "「なんだ、幼虫じゃない。摘まんでポイっとすればいいよ」"

[[dialogue]]
speaker = "ナターシャ"
# 「ひぃ！？　ベ、ベアト、そういうの大丈夫なの？」
line = "「ひぃ！？　ベ、ベアト、そういうの大丈夫なの？」"

[[dialogue]]
speaker = "ベアトリス"
# 「魔界の洞窟で暮らしてた時は、もっと毒々しい生き物たちとご近所付き合いしてたからね」
line = "「魔界の洞窟で暮らしてた時は、もっと毒々しい生き物たちとご近所付き合いしてたからね」"

[[dialogue]]
speaker = "ナターシャ"
# 「もっと毒々しいって……。想像するだけでも──うぷっ」
line = "「もっと毒々しいって……。想像するだけでも──うぷっ」"

[[dialogue]]
speaker = "ナターシャ"
# 「……私、ちょっと潮風を浴びてくるよ。少し休みたい……」
line = "「……私、ちょっと潮風を浴びてくるよ。少し休みたい……」"

[[dialogue]]
speaker = "梨緒"
# 「あ、ああ……ゆっくりするといい」
line = "「あ、ああ……ゆっくりするといい」"

[[dialogue]]
speaker = "ナターシャ"
# 「ひぃあああっ！！？」
line = "「ひぃあああっ！！？」"

[[dialogue]]
speaker = "梨緒"
# 「今度はどうした！？」
line = "「今度はどうした！？」"

[[dialogue]]
speaker = "ナターシャ"
# 「い、岩にキモいのがっ。大量にモゾモゾしたものがぁ～！」
line = "「い、岩にキモいのがっ。大量にモゾモゾしたものがぁ～！」"

[[dialogue]]
speaker = "ベアトリス"
# 「ホントだ。人間界にもこういう生き物いるんだね～」
line = "「ホントだ。人間界にもこういう生き物いるんだね～」"

[[dialogue]]
speaker = "ナターシャ"
# 「何を平然と……！？」
line = "「何を平然と……！？」"

[[dialogue]]
speaker = "アポロ"
# 「んん、フナムシじゃねーか。これもダメなのか？」
line = "「んん、フナムシじゃねーか。これもダメなのか？」"

[[dialogue]]
speaker = "ナターシャ"
# 「きゃああああっ！？　何を鷲づかみにしてんのっ！？　お願いだから、こっちに持ってこないでぇ～！？」
line = "「きゃああああっ！？　何を鷲づかみにしてんのっ！？　お願いだから、こっちに持ってこないでぇ～！？」"

[[dialogue]]
speaker = "ナターシャ"
# 「私、人間界でサバイバルするの向いてないかもしれない……聖庭園に命令されたら辞表出すかも……」
line = "「私、人間界でサバイバルするの向いてないかもしれない……聖庭園に命令されたら辞表出すかも……」"

[[dialogue]]
speaker = "ベアトリス"
# 「よしよし、私の膝で良ければいくらでも枕にしてくれていいからね」
line = "「よしよし、私の膝で良ければいくらでも枕にしてくれていいからね」"

[[dialogue]]
speaker = "アポロ"
# 「元気出せよ、ナターシャ。ほら魚が焼けたぞ、一番おっきいのくれてやる」
line = "「元気出せよ、ナターシャ。ほら魚が焼けたぞ、一番おっきいのくれてやる」"

[[dialogue]]
speaker = "梨緒"
# 「ハーブを探して摘んでおいた。たき火にくべれば虫除けになるはずだ」
line = "「ハーブを探して摘んでおいた。たき火にくべれば虫除けになるはずだ」"

[[dialogue]]
speaker = "ナターシャ"
# 「うぅ、みんな逞しいね。私、ここまで自分が軟弱だとは思ってなかったよ……」
line = "「うぅ、みんな逞しいね。私、ここまで自分が軟弱だとは思ってなかったよ……」"

[[dialogue]]
speaker = "梨緒"
# 「まあまあ。誰しも苦手なものの１つや２つある」
line = "「まあまあ。誰しも苦手なものの１つや２つある」"

[[dialogue]]
speaker = "アポロ"
# 「でもいい１日だったなぁ～。今日は知らなかったみんなの一面をたくさん見た気がするぜ」
line = "「でもいい１日だったなぁ～。今日は知らなかったみんなの一面をたくさん見た気がするぜ」"

[[dialogue]]
speaker = "ベアトリス"
# 「そうだね。キャンプが得意だったり、虫が苦手だったり、以外な面を知れたよ」
line = "「そうだね。キャンプが得意だったり、虫が苦手だったり、以外な面を知れたよ」"

[[dialogue]]
speaker = "ナターシャ"
# 「一応サバイバルだけどね。けど、まぁ確かに、なんだかんだ楽しい１日だったか。散々な目に遭ったけど……」
line = "「一応サバイバルだけどね。けど、まぁ確かに、なんだかんだ楽しい１日だったか。散々な目に遭ったけど……」"

[[dialogue]]
speaker = "梨緒"
# 「私も楽しかったよ。選管のみんなで旅行でもとは常々考えていたんだ。ずっと戦い続きで暇がなかったがな」
line = "「私も楽しかったよ。選管のみんなで旅行でもとは常々考えていたんだ。ずっと戦い続きで暇がなかったがな」"

[[dialogue]]
speaker = "アポロ"
# 「暇がないのは、梨緒がいっつも魔王やジグに勝負を仕掛けてるからだろー？」
line = "「暇がないのは、梨緒がいっつも魔王やジグに勝負を仕掛けてるからだろー？」"

[[dialogue]]
speaker = "梨緒"
# 「うっ」
line = "「うっ」"

[[dialogue]]
speaker = "ベアトリス"
# 「ふふ、だね。少しは私たちにも時間を使ってくれればいいのに」
line = "「ふふ、だね。少しは私たちにも時間を使ってくれればいいのに」"

[[dialogue]]
speaker = "ナターシャ"
# 「私はどっちでもいいけど。でも誘われたら行くかな。選管の絆？　ってやつも深めたいし」
line = "「私はどっちでもいいけど。でも誘われたら行くかな。選管の絆？　ってやつも深めたいし」"

[[dialogue]]
speaker = "梨緒"
# 「わ、私だって深めたいと思っているぞっ。大切な仲間との絆をっ！」
line = "「わ、私だって深めたいと思っているぞっ。大切な仲間との絆をっ！」"

[[dialogue]]
speaker = "ベアトリス"
# 「なら今度は梨緒ちゃんのお部屋でお泊まり会でもしちゃう？」
line = "「なら今度は梨緒ちゃんのお部屋でお泊まり会でもしちゃう？」"

[[dialogue]]
speaker = "アポロ"
# 「お、いいな、それ！　パジャマパーティーってやつかっ！」
line = "「お、いいな、それ！　パジャマパーティーってやつかっ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「部屋は綺麗なんだよね？　もしも虫が湧くような部屋なら……」
line = "「部屋は綺麗なんだよね？　もしも虫が湧くような部屋なら……」"

[[dialogue]]
speaker = "梨緒"
# 「失礼なことを言うな！　というか勝手に決めて──……ふふ、まぁ構わないか」
line = "「失礼なことを言うな！　というか勝手に決めて──……ふふ、まぁ構わないか」"

[[dialogue]]
speaker = "アポロ"
# 「そうと決まればちゃっちゃとクリアしちまおうぜ！　そして梨緒の部屋で祝勝会だ！」
line = "「そうと決まればちゃっちゃとクリアしちまおうぜ！　そして梨緒の部屋で祝勝会だ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「虫はもうコリゴリだしね。明日中にクリアしちゃおうよ」
line = "「虫はもうコリゴリだしね。明日中にクリアしちゃおうよ」"

[[dialogue]]
speaker = "ベアトリス"
# 「私たちなら楽勝だよ♪　たっぷり遊んで、英気も養ったし♪」
line = "「私たちなら楽勝だよ♪　たっぷり遊んで、英気も養ったし♪」"

[[dialogue]]
speaker = "梨緒"
# 「選挙管理委員の本領発揮だ。私たちの絆の強さを証明してやろう！」
line = "「選挙管理委員の本領発揮だ。私たちの絆の強さを証明してやろう！」"
