[[dialogue]]
speaker = "モンスター"
# 「～～～～～～～～～ッ！！」
line = "「～～～～～～～～～ッ！！」"

[[dialogue]]
speaker = "イングリット"
# 「ふんっ、あっけないな。この程度の雑魚では私の欲望を満たすことはできん」
line = "「ふんっ、あっけないな。この程度の雑魚では私の欲望を満たすことはできん」"

[[dialogue]]
speaker = "カティア"
# 「アステラのボスを一撃で……つ、強すぎる……圧倒的だワン……」
line = "「アステラのボスを一撃で……つ、強すぎる……圧倒的だワン……」"

[[dialogue]]
speaker = "イングリット"
# 「そうだろうそうだろう。私の強さを思い知ったか」
line = "「そうだろうそうだろう。私の強さを思い知ったか」"

[[dialogue]]
speaker = "カティア"
# 「め、めちゃくちゃドヤ顔してるワン……」
line = "「め、めちゃくちゃドヤ顔してるワン……」"

[[dialogue]]
speaker = "イングリット"
# 「強さを誇って何が悪い？」
line = "「強さを誇って何が悪い？」"

[[dialogue]]
speaker = "カティア"
# 「いや、別に悪くはないけど……ダサいガオ……」
line = "「いや、別に悪くはないけど……ダサいガオ……」"

[[dialogue]]
speaker = "イングリット"
# 「よし、行くぞ」
line = "「よし、行くぞ」"

[[dialogue]]
speaker = "カティア"
# 「聞いてないし……」
line = "「聞いてないし……」"

[[dialogue]]
speaker = "カティア"
# 「って、それよりもモンスターを倒したのにアステラが消滅しない……？　どうなってるんですか！？」
line = "「って、それよりもモンスターを倒したのにアステラが消滅しない……？　どうなってるんですか！？」"

[[dialogue]]
speaker = "イングリット"
# 「知るか。貴様、星騎士なのにわからないのか？」
line = "「知るか。貴様、星騎士なのにわからないのか？」"

[[dialogue]]
speaker = "カティア"
# 「アステラに入るの初めてなんですから、わかるわけないですよう！」
line = "「アステラに入るの初めてなんですから、わかるわけないですよう！」"

[[dialogue]]
speaker = "カティア"
# 「さっきのモンスターがボスじゃなかったってこと……？　ていうかアステラってこんなに広いの……？」
line = "「さっきのモンスターがボスじゃなかったってこと……？　ていうかアステラってこんなに広いの……？」"

[[dialogue]]
speaker = "カティア"
# 「もしかして、このアステラ、おかしくなってるとか……？　どうしましょう、私たちここから出れるんでしょうか！？」
line = "「もしかして、このアステラ、おかしくなってるとか……？　どうしましょう、私たちここから出れるんでしょうか！？」"

[[dialogue]]
speaker = "イングリット"
# 「問題ない。私についてこい」
line = "「問題ない。私についてこい」"

[[dialogue]]
speaker = "カティア"
# 「出口が分かるんですか？」
line = "「出口が分かるんですか？」"

[[dialogue]]
speaker = "イングリット"
# 「さぁな。だが目につくものを片っ端から切っていけば、なんとかなるだろう」
line = "「さぁな。だが目につくものを片っ端から切っていけば、なんとかなるだろう」"

[[dialogue]]
speaker = "カティア"
# （この人、本当に大丈夫なのかな……）
line = "（この人、本当に大丈夫なのかな……）"

[[dialogue]]
speaker = "？？？"
# 「はぁ、どうしてわたくしがこんな目に……」
line = "「はぁ、どうしてわたくしがこんな目に……」"

[[dialogue]]
speaker = "？？？"
# 「イングリット様、勝手にアステラに突入して……全く、わたくしの仕事を増やさないでほしいでございますわ……」
line = "「イングリット様、勝手にアステラに突入して……全く、わたくしの仕事を増やさないでほしいでございますわ……」"

[[dialogue]]
speaker = "？？？"
# 「はぁ……彼女はコラプサーの任務をキチンと理解しているのでございましょうか？」
line = "「はぁ……彼女はコラプサーの任務をキチンと理解しているのでございましょうか？」"

[[dialogue]]
speaker = "？？？"
# 「……いえ、あまり期待できませんね。三歩歩けば忘れるような脳みそをお持ちでございますし」
line = "「……いえ、あまり期待できませんね。三歩歩けば忘れるような脳みそをお持ちでございますし」"

[[dialogue]]
speaker = "？？？"
# 「どうにかイングリット様を連れ戻して、任務に戻らなければ──」
line = "「どうにかイングリット様を連れ戻して、任務に戻らなければ──」"

[[dialogue]]
speaker = "マリーベル"
# 「そこのあなた……こんなところで何をしているの？」
line = "「そこのあなた……こんなところで何をしているの？」"

[[dialogue]]
speaker = "？？？"
# 「おやおや……わたくしとしたことが、学園の星騎士に見つかってしまうとは」
line = "「おやおや……わたくしとしたことが、学園の星騎士に見つかってしまうとは」"

[[dialogue]]
speaker = "？？？"
# （ですが、たかが星騎士１人。わたくしの記憶が正しければ、プリマステラに彼女の顔はなかったはず……倒すのは簡単でございますわ♪）
line = "（ですが、たかが星騎士１人。わたくしの記憶が正しければ、プリマステラに彼女の顔はなかったはず……倒すのは簡単でございますわ♪）"

[[dialogue]]
speaker = "マリーベル"
# 「見ない顔ね。あなた、学園の星騎士ではないでしょう？」
line = "「見ない顔ね。あなた、学園の星騎士ではないでしょう？」"

[[dialogue]]
speaker = "？？？"
# 「ふふふ、その通りですの。わたくし、コラプサーでございますから」
line = "「ふふふ、その通りですの。わたくし、コラプサーでございますから」"

[[dialogue]]
speaker = "マリーベル"
# 「コラプサー……！」
line = "「コラプサー……！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「お初にお目にかかります。わたくし、シャリオン十貴族が一氏、ジュリエッテ・ハルヴィーノと申しますの」
line = "「お初にお目にかかります。わたくし、シャリオン十貴族が一氏、ジュリエッテ・ハルヴィーノと申しますの」"

[[dialogue]]
speaker = "マリーベル"
# 「コラプサーが何の目的で？」
line = "「コラプサーが何の目的で？」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「おや、十貴族には反応されませんでしたか……まぁ良いでしょう。ちょっとしたお散歩でございますわ」
line = "「おや、十貴族には反応されませんでしたか……まぁ良いでしょう。ちょっとしたお散歩でございますわ」"

[[dialogue]]
speaker = "マリーベル"
# 「そんな言葉を信じるわけないでしょう」
line = "「そんな言葉を信じるわけないでしょう」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「別に信じられなくても構いませんわ。だって、あなた様は今からわたくしに葬り去られるのでございますからっ」
line = "「別に信じられなくても構いませんわ。だって、あなた様は今からわたくしに葬り去られるのでございますからっ」"

[[dialogue]]
speaker = "マリーベル"
# 「いきなり攻撃とは、お行儀が悪いわね……！」
line = "「いきなり攻撃とは、お行儀が悪いわね……！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「あらまあ、外しましたか……。ですが、いつまで逃げ切れるでしょうか……！」
line = "「あらまあ、外しましたか……。ですが、いつまで逃げ切れるでしょうか……！」"

[[dialogue]]
speaker = "マリーベル"
# 「長距離戦は分が悪いわね……槍の距離まで近づかないと……！」
line = "「長距離戦は分が悪いわね……槍の距離まで近づかないと……！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ふふふ、そう簡単にはやらせませんわよ」
line = "「ふふふ、そう簡単にはやらせませんわよ」"

[[dialogue]]
speaker = "マリーベル"
# 「それはどうかしら──スカーレットペイン！」
line = "「それはどうかしら──スカーレットペイン！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「──っ！」
line = "「──っ！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「この人っ、真っ直ぐ突っ込んできて……！　攻撃が当たるのが恐くないのでございますの！？」
line = "「この人っ、真っ直ぐ突っ込んできて……！　攻撃が当たるのが恐くないのでございますの！？」"

[[dialogue]]
speaker = "マリーベル"
# 「撃ちたければ撃ちなさい。たとえこの身が滅びようとも、罪が消えるまで戦い続けないといけないの」
line = "「撃ちたければ撃ちなさい。たとえこの身が滅びようとも、罪が消えるまで戦い続けないといけないの」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「狂人でございますの！？　このお方っ！！」
line = "「狂人でございますの！？　このお方っ！！」"

[[dialogue]]
speaker = "マリーベル"
# 「この距離なら届くわね──クリムゾンスティンガー！」
line = "「この距離なら届くわね──クリムゾンスティンガー！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「きゃあああああああああああ！」
line = "「きゃあああああああああああ！」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「…………って、言えばいいのでございましょうか？」
line = "「…………って、言えばいいのでございましょうか？」"

[[dialogue]]
speaker = "マリーベル"
# 「私の槍が効いていない……」
line = "「私の槍が効いていない……」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「ふふふ、あなた様の星力を吸収させていただきましたの」
line = "「ふふふ、あなた様の星力を吸収させていただきましたの」"

[[dialogue]]
speaker = "マリーベル"
# 「コラプサーの特殊能力……！　厄介な敵ね……」
line = "「コラプサーの特殊能力……！　厄介な敵ね……」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「お褒めに与り光栄でございますわ♪　コラプサー相手に並大抵の星力は効きませんの♪」
line = "「お褒めに与り光栄でございますわ♪　コラプサー相手に並大抵の星力は効きませんの♪」"

[[dialogue]]
speaker = "マリーベル"
# 「別に褒めてはいないのだけど」
line = "「別に褒めてはいないのだけど」"

[[dialogue]]
speaker = "マリーベル"
# （コラプサーに普通の攻撃は通用しない……どうすればこの槍を届かせられるの？）
line = "（コラプサーに普通の攻撃は通用しない……どうすればこの槍を届かせられるの？）"

[[dialogue]]
speaker = "ジュリエッテ"
# 「あなた様の攻撃はこれで終わりでしょうか？　ではこちらの番でございます！」
line = "「あなた様の攻撃はこれで終わりでしょうか？　ではこちらの番でございます！」"
