[[dialogue]]
speaker = "ルリエル"
# 「はぁっ、はぁっ、あひぃぃっ……！」
line = "「はぁっ、はぁっ、あひぃぃっ……！」"

[[dialogue]]
speaker = "イクシリオン"
# 「んっ、ふっ、んっ、んんっ……！」
line = "「んっ、ふっ、んっ、んんっ……！」"

[[dialogue]]
speaker = "unk"
# 水着戦闘服をものにするべく、砂浜を走る２人。
line = "水着戦闘服をものにするべく、砂浜を走る２人。"

[[dialogue]]
speaker = "unk"
# だが──
line = "だが──"

[[dialogue]]
speaker = "ルリエル"
# 「ぜぇっ、ぜぇっ、ぜぇっ……！　うへぇぇぇ……！」
line = "「ぜぇっ、ぜぇっ、ぜぇっ……！　うへぇぇぇ……！」"

[[dialogue]]
speaker = "イクシリオン"
# 「大丈夫ですか、ルリエルさんっ。遅れていますよっ？」
line = "「大丈夫ですか、ルリエルさんっ。遅れていますよっ？」"

[[dialogue]]
speaker = "ルリエル"
# 「ぜんぜ、大丈夫じゃない、ですぅ……！　というか──」
line = "「ぜんぜ、大丈夫じゃない、ですぅ……！　というか──」"

[[dialogue]]
speaker = "unk"
# 背中が丸まってきてるぞ！　もっと背筋伸ばして！
line = "背中が丸まってきてるぞ！　もっと背筋伸ばして！"

[[dialogue]]
speaker = "ルリエル"
# 「そもそもどーして砂浜なんて走らされてるんですかぁ～！？」
line = "「そもそもどーして砂浜なんて走らされてるんですかぁ～！？」"

[[dialogue]]
speaker = "イクシリオン"
# 「はい？　もちろん、新しい力を使いこなすためにですが」
line = "「はい？　もちろん、新しい力を使いこなすためにですが」"

[[dialogue]]
speaker = "ルリエル"
# 「他にやり方がありますよね！？　これじゃ体育会系ですよ！　もしくは軍隊ですよ！　ピカピカの水着女子がすることじゃないですぅ！」
line = "「他にやり方がありますよね！？　これじゃ体育会系ですよ！　もしくは軍隊ですよ！　ピカピカの水着女子がすることじゃないですぅ！」"

[[dialogue]]
speaker = "イクシリオン"
# 「潮風を浴びながらランニングなんて気持ちいいではありませんか。砂浜の走りづらさも体力向上にもってこいです。体幹も強くなりますしね」
line = "「潮風を浴びながらランニングなんて気持ちいいではありませんか。砂浜の走りづらさも体力向上にもってこいです。体幹も強くなりますしね」"

[[dialogue]]
speaker = "unk"
# 浅瀬を走るのもいいかもな
line = "浅瀬を走るのもいいかもな"

[[dialogue]]
speaker = "イクシリオン"
# 「水の抵抗が加わって天然のパワーアンクルになるわけですね！　膝下くらいまで入って走ってみましょう！」
line = "「水の抵抗が加わって天然のパワーアンクルになるわけですね！　膝下くらいまで入って走ってみましょう！」"

[[dialogue]]
speaker = "ルリエル"
# 「おふたりとも脳まで筋肉さんですか！？　ぜーったいに嫌ですよぉ！　こんな地味で辛いだけの特訓をしても星力制御なんかできませんってばぁ～！」
line = "「おふたりとも脳まで筋肉さんですか！？　ぜーったいに嫌ですよぉ！　こんな地味で辛いだけの特訓をしても星力制御なんかできませんってばぁ～！」"

[[dialogue]]
speaker = "ルリエル"
# 「見てください！　ぶぉ、ぶぉおおおっっ──ぶおっほっ……！？　息が上がりすぎてわたし、法螺貝の演奏すらままならなくなってますよぉ……！！」
line = "「見てください！　ぶぉ、ぶぉおおおっっ──ぶおっほっ……！？　息が上がりすぎてわたし、法螺貝の演奏すらままならなくなってますよぉ……！！」"

[[dialogue]]
speaker = "イクシリオン"
# 「しかし、こういった基礎訓練以外となると、どういった特訓を行うべきなのか……」
line = "「しかし、こういった基礎訓練以外となると、どういった特訓を行うべきなのか……」"

[[dialogue]]
speaker = "ルリエル"
# 「フィオナ会長、カムバーックっ！　ルリエル、新星学園では生きていけそうにありませ～んっ！」
line = "「フィオナ会長、カムバーックっ！　ルリエル、新星学園では生きていけそうにありませ～んっ！」"

[[dialogue]]
speaker = "ルリエル"
# 「絶対に他の方法がありますってば！　ほらヘレナさんも言ってましたよねっ？　人工戦闘服を使いこなすには、きっかけが必要だって……！」
line = "「絶対に他の方法がありますってば！　ほらヘレナさんも言ってましたよねっ？　人工戦闘服を使いこなすには、きっかけが必要だって……！」"

[[dialogue]]
speaker = "イクシリオン"
# 「？？？」
line = "「？？？」"

[[dialogue]]
speaker = "ルリエル"
# 「なんで疑問符を浮かべてるんですか！？　あの時ですよ、あの時！」
line = "「なんで疑問符を浮かべてるんですか！？　あの時ですよ、あの時！」"

[[dialogue]]
speaker = "ヘレナ"
# 「人工戦闘服は半ば強引に力の組成を変化させる。慣れぬ内は自身の潜在能力に振り回されることもあるだろう」
line = "「人工戦闘服は半ば強引に力の組成を変化させる。慣れぬ内は自身の潜在能力に振り回されることもあるだろう」"

[[dialogue]]
speaker = "ヘレナ"
# 「身に付けるものひとつで世界の見え方や気分が変わると言ったが、己がその世界や心持ちに適応できなければ意味がない」
line = "「身に付けるものひとつで世界の見え方や気分が変わると言ったが、己がその世界や心持ちに適応できなければ意味がない」"

[[dialogue]]
speaker = "ヘレナ"
# 「何かきっかけを掴めば、２人も立ち所に新たな力を使いこなせるようになるだろう」
line = "「何かきっかけを掴めば、２人も立ち所に新たな力を使いこなせるようになるだろう」"

[[dialogue]]
speaker = "ルリエル"
# 「ほえー……何かきっかけを掴めば、ですかぁ……」
line = "「ほえー……何かきっかけを掴めば、ですかぁ……」"

[[dialogue]]
speaker = "イクシリオン"
# 「どんな水着にしましょうか……王道のビキニもいいですが、際どいハイレグも捨てがたい……」
line = "「どんな水着にしましょうか……王道のビキニもいいですが、際どいハイレグも捨てがたい……」"

[[dialogue]]
speaker = "イクシリオン"
# 「マイクロビキニなんて大胆過ぎ……。ハッ──ボディペイントは水着に入るのでしょうか……！？」
line = "「マイクロビキニなんて大胆過ぎ……。ハッ──ボディペイントは水着に入るのでしょうか……！？」"

[[dialogue]]
speaker = "ヘレナ"
# 「２人には期待している。より幅広い人工戦闘服が実用化すれば、私も星騎士たちを好きに着替えさせたい放題──ではなく、より貴殿らを助力できるようになるからな」
line = "「２人には期待している。より幅広い人工戦闘服が実用化すれば、私も星騎士たちを好きに着替えさせたい放題──ではなく、より貴殿らを助力できるようになるからな」"

[[dialogue]]
speaker = "イクシリオン"
# 「言われてみれば……。あの時はその、自分の水着のことで頭がおっぱ──じゃなくて、いっぱいで……」
line = "「言われてみれば……。あの時はその、自分の水着のことで頭がおっぱ──じゃなくて、いっぱいで……」"

[[dialogue]]
speaker = "ルリエル"
# 「とにかく！　こんなスポ根な修業は意味ないんです、したくないんです！　せっかく海に来てるんですから、もっと違うことしましょうよ～！」
line = "「とにかく！　こんなスポ根な修業は意味ないんです、したくないんです！　せっかく海に来てるんですから、もっと違うことしましょうよ～！」"

[[dialogue]]
speaker = "イクシリオン"
# 「では向こうに見える岩場でロッククライミングなど如何ですか？　下が柔らかい砂浜ならたとえ落ちても怪我をしませんし！」
line = "「では向こうに見える岩場でロッククライミングなど如何ですか？　下が柔らかい砂浜ならたとえ落ちても怪我をしませんし！」"

[[dialogue]]
speaker = "ルリエル"
# 「いや普通に怪我しますよ！？　何を『妙案を思いつきました！』みたいな顔で言ってるんですか！」
line = "「いや普通に怪我しますよ！？　何を『妙案を思いつきました！』みたいな顔で言ってるんですか！」"

[[dialogue]]
speaker = "ルリエル"
# 「ビーチバレーとか、サーフィンとか、水着ならではの体験をしようって言ってるんです～！」
line = "「ビーチバレーとか、サーフィンとか、水着ならではの体験をしようって言ってるんです～！」"

[[dialogue]]
speaker = "イクシリオン"
# 「ビーチバレー……サーフィン……なるほど！　良いアイデアですね！　目から鱗です！」
line = "「ビーチバレー……サーフィン……なるほど！　良いアイデアですね！　目から鱗です！」"

[[dialogue]]
speaker = "ルリエル"
# 「うぅ、ソフィアって、いつもこんなに大変な仕事をしていたのですね……。今度ツッコんでもらった時はお礼を言わないとですぅ……」
line = "「うぅ、ソフィアって、いつもこんなに大変な仕事をしていたのですね……。今度ツッコんでもらった時はお礼を言わないとですぅ……」"

[[dialogue]]
speaker = "unk"
# まぁまぁかき氷でも食べて落ち着いて
line = "まぁまぁかき氷でも食べて落ち着いて"

[[dialogue]]
speaker = "ルリエル"
# 「そんなあからさまなご機嫌取りじゃルリエルは誤魔化されませんよ！　シャクシャク──んん～！　美味しいです！　頭キーンってしますぅ～！」
line = "「そんなあからさまなご機嫌取りじゃルリエルは誤魔化されませんよ！　シャクシャク──んん～！　美味しいです！　頭キーンってしますぅ～！」"

[[dialogue]]
speaker = "イクシリオン"
# 「アイスクリーム頭痛と呼ばれる症状ですね。おでこやこめかみを冷やせば、痛みが和らぐはずですよ」
line = "「アイスクリーム頭痛と呼ばれる症状ですね。おでこやこめかみを冷やせば、痛みが和らぐはずですよ」"

[[dialogue]]
speaker = "ルリエル"
# 「保健委員さんの豆知識！」
line = "「保健委員さんの豆知識！」"

[[dialogue]]
speaker = "unk"
# それで話は戻るけど
line = "それで話は戻るけど"

[[dialogue]]
speaker = "イクシリオン"
# 「はい。星力の制御をするには何かしらのきっかけを掴めばいいんですよね？　つまり、海や水着に関連する苦手を克服することが肝要ということでしょうか？」
line = "「はい。星力の制御をするには何かしらのきっかけを掴めばいいんですよね？　つまり、海や水着に関連する苦手を克服することが肝要ということでしょうか？」"

[[dialogue]]
speaker = "ルリエル"
# 「苦手は無理に克服しなくていいと思いますよ！　その発想が既に体育会系ですってば！」
line = "「苦手は無理に克服しなくていいと思いますよ！　その発想が既に体育会系ですってば！」"

[[dialogue]]
speaker = "イクシリオン"
# 「そういえばルリエルさんは泳げないとセーラさんが仰っていたような……」
line = "「そういえばルリエルさんは泳げないとセーラさんが仰っていたような……」"

[[dialogue]]
speaker = "ルリエル"
# 「き、気のせいですよぉ～。わたし、泳ぎにだけは自信があるんですぅ～」
line = "「き、気のせいですよぉ～。わたし、泳ぎにだけは自信があるんですぅ～」"

[[dialogue]]
speaker = "イクシリオン"
# 「ふふ、それなら遠泳をしてもいいかもしれませんね。海ならではの楽しい特訓ですし、私も水難救助の訓練になりますから」
line = "「ふふ、それなら遠泳をしてもいいかもしれませんね。海ならではの楽しい特訓ですし、私も水難救助の訓練になりますから」"

[[dialogue]]
speaker = "ルリエル"
# 「ごめんなさい！　法螺を吹きました！　ルリエル、カナヅチなのです！　これっぽっちも泳げないのです！」
line = "「ごめんなさい！　法螺を吹きました！　ルリエル、カナヅチなのです！　これっぽっちも泳げないのです！」"

[[dialogue]]
speaker = "イクシリオン"
# 「では尚更、星力制御に繋がるきっかけになり得るかもですね！」
line = "「では尚更、星力制御に繋がるきっかけになり得るかもですね！」"

[[dialogue]]
speaker = "ルリエル"
# 「うわ～ん、この人、壁が高いほど燃えちゃうタイプの人ですぅ～！　わたしはもっと甘やかされて育ちたいんですよぉ～……！」
line = "「うわ～ん、この人、壁が高いほど燃えちゃうタイプの人ですぅ～！　わたしはもっと甘やかされて育ちたいんですよぉ～……！」"

[[dialogue]]
speaker = "ルリエル"
# 「というか、イクシーさんはどうなんですかっ？　そんなに都合良く苦手なことがあるんですかっ？」
line = "「というか、イクシーさんはどうなんですかっ？　そんなに都合良く苦手なことがあるんですかっ？」"

[[dialogue]]
speaker = "イクシリオン"
# 「私、ですか？　そうですね……」
line = "「私、ですか？　そうですね……」"

[[dialogue]]
speaker = "ルリエル"
# 「あっ、ないならないで構わないんですよっ！　楽しく遊びながら、徐々に力を使いこなしていきましょう……！」
line = "「あっ、ないならないで構わないんですよっ！　楽しく遊びながら、徐々に力を使いこなしていきましょう……！」"

[[dialogue]]
speaker = "イクシリオン"
# 「いえ。強いて挙げるなら……」
line = "「いえ。強いて挙げるなら……」"

[[dialogue]]
speaker = "unk"
# ん……？
line = "ん……？"

[[dialogue]]
speaker = "イクシリオン"
# 「～～っっ。み、水着姿に慣れないというのが一番でしょうか。会長に見つめられるだけでも、その、熱中症になってしまいそうなくらいで……」
line = "「～～っっ。み、水着姿に慣れないというのが一番でしょうか。会長に見つめられるだけでも、その、熱中症になってしまいそうなくらいで……」"

[[dialogue]]
speaker = "イクシリオン"
# 「で……でも、確かにこれを克服すれば、何か変われそうな気はしますね……。新しい世界の扉が開けるような気がします……」
line = "「で……でも、確かにこれを克服すれば、何か変われそうな気はしますね……。新しい世界の扉が開けるような気がします……」"

[[dialogue]]
speaker = "イクシリオン"
# 「想像するだけでも恥ずかしすぎて……はぁはぁ……死んでしまいそうですが……。もしも会長の視線に、んんっ、耐えられるようになれば……」
line = "「想像するだけでも恥ずかしすぎて……はぁはぁ……死んでしまいそうですが……。もしも会長の視線に、んんっ、耐えられるようになれば……」"

[[dialogue]]
speaker = "ルリエル"
# 「待ってくださいっ！　なんだか苦手を克服する流れになってませんかっ？　何度も言いますが、進んで辛いことをする必要は──」
line = "「待ってくださいっ！　なんだか苦手を克服する流れになってませんかっ？　何度も言いますが、進んで辛いことをする必要は──」"

[[dialogue]]
speaker = "イクシリオン"
# 「いいえ、やりましょうっ！　新たな力を身に付けるためですからっ！　会長も協力してくださりますよねっ？」
line = "「いいえ、やりましょうっ！　新たな力を身に付けるためですからっ！　会長も協力してくださりますよねっ？」"

[[dialogue]]
speaker = "ルリエル"
# 「ふえ～ん、苦手なことなんて聞かなきゃ良かったですぅ～！」
line = "「ふえ～ん、苦手なことなんて聞かなきゃ良かったですぅ～！」"
