[[dialogue]]
speaker = "リア"
# 「ちょっと待った～～～～っ！！」
line = "「ちょっと待った～～～～っ！！」"

[[dialogue]]
speaker = "聖沙"
# 「お姉さま！？」
line = "「お姉さま！？」"

[[dialogue]]
speaker = "リア"
# 「先輩として、流星クルセイダースの一員として、聖沙ちゃんだけ戦わせるわけにはいかないよ。一緒に頑張ろう、聖沙ちゃん」
line = "「先輩として、流星クルセイダースの一員として、聖沙ちゃんだけ戦わせるわけにはいかないよ。一緒に頑張ろう、聖沙ちゃん」"

[[dialogue]]
speaker = "聖沙"
# 「はい！　お姉さまがいてくれたらきっと無敵です！」
line = "「はい！　お姉さまがいてくれたらきっと無敵です！」"
