[[dialogue]]
speaker = "ミア"
# 「はぁーっ、はぁーっ、倒せた……の？」
line = "「はぁーっ、はぁーっ、倒せた……の？」"

[[dialogue]]
speaker = "unk"
# おかげで助かったよ
line = "おかげで助かったよ"

[[dialogue]]
speaker = "ミア"
# 「何を言ってるの……。助けられたのは私の方よ……」
line = "「何を言ってるの……。助けられたのは私の方よ……」"

[[dialogue]]
speaker = "ミア"
# 「みんなの忠告を無視して勝手に飛び出して行って……。１人で勝手にムキになって会長さんからも泣いて逃げて……」
line = "「みんなの忠告を無視して勝手に飛び出して行って……。１人で勝手にムキになって会長さんからも泣いて逃げて……」"

[[dialogue]]
speaker = "ミア"
# 「ごめん、なさい……！　ごめんなさいっ……！」
line = "「ごめん、なさい……！　ごめんなさいっ……！」"

[[dialogue]]
speaker = "ミア"
# 「私が子どもだったせいで、ひっくっ……！　会長さんがぁ……！　何度も何度も痛い思いさせられてぇ……！」
line = "「私が子どもだったせいで、ひっくっ……！　会長さんがぁ……！　何度も何度も痛い思いさせられてぇ……！」"

[[dialogue]]
speaker = "unk"
# 無事で良かった
line = "無事で良かった"

[[dialogue]]
speaker = "ミア"
# 「ひっくっ、ひっくっ……！　本当に、ごめんなさいっ……！　怖かった……！　怖かったよぉ……！」
line = "「ひっくっ、ひっくっ……！　本当に、ごめんなさいっ……！　怖かった……！　怖かったよぉ……！」"

[[dialogue]]
speaker = "ミア"
# 「あの人に殺されそうになった時も、ボロボロになっていく会長さんを見るのも、すごくっ、すごくっ……！」
line = "「あの人に殺されそうになった時も、ボロボロになっていく会長さんを見るのも、すごくっ、すごくっ……！」"

[[dialogue]]
speaker = "ミア"
# 「ごめっ、ごめんなさいっ……！　ひっくっ、ぐすぅっ……！　私のせいでっ、ごめんなさいっっ……！！」
line = "「ごめっ、ごめんなさいっ……！　ひっくっ、ぐすぅっ……！　私のせいでっ、ごめんなさいっっ……！！」"

[[dialogue]]
speaker = "ミア"
# 「ふえっ──ふえぇぇぇぇええんんっっ……！！」
line = "「ふえっ──ふえぇぇぇぇええんんっっ……！！」"

[[dialogue]]
speaker = "ミア"
# 「ぐすっ、もう大丈夫……。ありがとう、ずっと抱き締めていてくれて……」
line = "「ぐすっ、もう大丈夫……。ありがとう、ずっと抱き締めていてくれて……」"

[[dialogue]]
speaker = "ミア"
# 「それと……本当にごめんなさい。勝手な行動を取って……」
line = "「それと……本当にごめんなさい。勝手な行動を取って……」"

[[dialogue]]
speaker = "ミア"
# 「本当にありがとう……。危ないところを助けてくれて……」
line = "「本当にありがとう……。危ないところを助けてくれて……」"

[[dialogue]]
speaker = "ミア"
# 「私ね。ずっと勘違いしちゃってた。立派な星騎士っていうものを……星騎士として戦うってことを……」
line = "「私ね。ずっと勘違いしちゃってた。立派な星騎士っていうものを……星騎士として戦うってことを……」"

[[dialogue]]
speaker = "ミア"
# 「ただみんなを守って戦えばいいって思ってたの……。みんなよりも活躍できれば立派なんだって思ってたの……」
line = "「ただみんなを守って戦えばいいって思ってたの……。みんなよりも活躍できれば立派なんだって思ってたの……」"

[[dialogue]]
speaker = "ミア"
# 「でも……全然違った。私はママとパパに、ううん、ヒーローに憧れているだけの子どもだった……」
line = "「でも……全然違った。私はママとパパに、ううん、ヒーローに憧れているだけの子どもだった……」"

[[dialogue]]
speaker = "ミア"
# 「みんなに認められたいって思うばっかりで……。変に背伸びばっかりして……。自分は格好いいヒーローなんだって誤解して……」
line = "「みんなに認められたいって思うばっかりで……。変に背伸びばっかりして……。自分は格好いいヒーローなんだって誤解して……」"

[[dialogue]]
speaker = "ミア"
# 「立派になるってことがどういうことかちゃんとわかってないのに、闇雲に駆け出していって……迷惑をかけて」
line = "「立派になるってことがどういうことかちゃんとわかってないのに、闇雲に駆け出していって……迷惑をかけて」"

[[dialogue]]
speaker = "ミア"
# 「でも、今度こそ私──立派な星騎士になるわ。ママとパパみたいな、会長さんみたいな本当に立派な星騎士に」
line = "「でも、今度こそ私──立派な星騎士になるわ。ママとパパみたいな、会長さんみたいな本当に立派な星騎士に」"

[[dialogue]]
speaker = "ミア"
# 「まだまだ道のりは長いと思うけど、一歩一歩焦らず進んで、会長さんと並んでみせるわ」
line = "「まだまだ道のりは長いと思うけど、一歩一歩焦らず進んで、会長さんと並んでみせるわ」"

[[dialogue]]
speaker = "unk"
# ミア……
line = "ミア……"

[[dialogue]]
speaker = "ミア"
# 「ちょっと、どうしてそんな感動してるの！？　まるで妹の成長を見る兄みたいな顔しないで！」
line = "「ちょっと、どうしてそんな感動してるの！？　まるで妹の成長を見る兄みたいな顔しないで！」"

[[dialogue]]
speaker = "ミア"
# 「それより今は、あのキサナって子をどうにかしなくちゃ」
line = "「それより今は、あのキサナって子をどうにかしなくちゃ」"

[[dialogue]]
speaker = "ミア"
# 「戦っていていくつか気付いたことがあるの。たぶんだけどあの人……１人じゃないわ。きっと他にも仲間がいる」
line = "「戦っていていくつか気付いたことがあるの。たぶんだけどあの人……１人じゃないわ。きっと他にも仲間がいる」"

[[dialogue]]
speaker = "ミア"
# 「会長さんが魔王だってことを誰かに聞いた風なこと言っていたし。あんな狂犬じみた人が今まで事件を起こさなかったことも不思議だもの」
line = "「会長さんが魔王だってことを誰かに聞いた風なこと言っていたし。あんな狂犬じみた人が今まで事件を起こさなかったことも不思議だもの」"

[[dialogue]]
speaker = "ミア"
# 「きっと何者かに今まで暴れないように指示されていたんだわ。それか指示を受けて、どこからか流星市国へ送り込まれてきたのかも……」
line = "「きっと何者かに今まで暴れないように指示されていたんだわ。それか指示を受けて、どこからか流星市国へ送り込まれてきたのかも……」"

[[dialogue]]
speaker = "unk"
# リクリエの使徒、かな？
line = "リクリエの使徒、かな？"

[[dialogue]]
speaker = "ミア"
# 「それってあの星読事変の？　それはないと思うわ。モンスターを見て逃げていったみたいだったし」
line = "「それってあの星読事変の？　それはないと思うわ。モンスターを見て逃げていったみたいだったし」"

[[dialogue]]
speaker = "ミア"
# 「それに私たちのことを正義の味方って言ってたもん。アポロっていうのは正義のヒーローを自称してたんでしょ？　それにモンスターを従えていたっていうし」
line = "「それに私たちのことを正義の味方って言ってたもん。アポロっていうのは正義のヒーローを自称してたんでしょ？　それにモンスターを従えていたっていうし」"

[[dialogue]]
speaker = "ミア"
# 「もちろん全くの無関係とは思えないけど……。星力を打ち消すあの力……天蓋にも近かったし」
line = "「もちろん全くの無関係とは思えないけど……。星力を打ち消すあの力……天蓋にも近かったし」"

[[dialogue]]
speaker = "ミア"
# 「あ、そうだっ……！　あの力のことだけど、弱点らしきものを見つけて──……って、どうしたの？　私の顔、じーっと見て……」
line = "「あ、そうだっ……！　あの力のことだけど、弱点らしきものを見つけて──……って、どうしたの？　私の顔、じーっと見て……」"

[[dialogue]]
speaker = "unk"
# よく観察してると思ってさ
line = "よく観察してると思ってさ"

[[dialogue]]
speaker = "ミア"
# 「こ、これくらい普通だもんっ。敵を知り、己を知れば……ってよく言うじゃない」
line = "「こ、これくらい普通だもんっ。敵を知り、己を知れば……ってよく言うじゃない」"

[[dialogue]]
speaker = "ミア"
# 「とにかく今はあのキサナって子を捕まえなきゃ。あの子が星騎士を狙って襲撃しているのは間違いなさそうだし……！」
line = "「とにかく今はあのキサナって子を捕まえなきゃ。あの子が星騎士を狙って襲撃しているのは間違いなさそうだし……！」"

[[dialogue]]
speaker = "ミア"
# 「もしあの子の裏に大きな組織がついているのなら、敵が集まってくる前にどうにかしないと……！」
line = "「もしあの子の裏に大きな組織がついているのなら、敵が集まってくる前にどうにかしないと……！」"

[[dialogue]]
speaker = "unk"
# でもどうやって捕まえる？
line = "でもどうやって捕まえる？"

[[dialogue]]
speaker = "ミア"
# 「私に考えがあるの。私の予想が当たっていれば、だけど」
line = "「私に考えがあるの。私の予想が当たっていれば、だけど」"

[[dialogue]]
speaker = "ミア"
# 「あの子の性格と、あの力の弱点を突けば、きっと捕まえられるはずよ……！」
line = "「あの子の性格と、あの力の弱点を突けば、きっと捕まえられるはずよ……！」"
