[[dialogue]]
speaker = "unk"
# 放課後のトレーニング施設に、キーボードの小気味よい音がカタカタと響く。
line = "放課後のトレーニング施設に、キーボードの小気味よい音がカタカタと響く。"

[[dialogue]]
speaker = "コハルコ"
# 「……よし、メンテナンス完了。システム異常なしっと」
line = "「……よし、メンテナンス完了。システム異常なしっと」"

[[dialogue]]
speaker = "シルヴィ"
# 「コハルコ、何やってるの？」
line = "「コハルコ、何やってるの？」"

[[dialogue]]
speaker = "コハルコ"
# 「何って……定期メンテナンスだよ。機械でも、定期的にお手入れしてあげないと壊れちゃうの」
line = "「何って……定期メンテナンスだよ。機械でも、定期的にお手入れしてあげないと壊れちゃうの」"

[[dialogue]]
speaker = "コハルコ"
# 「シルヴィがいつも行ってるフライドチキンのお店も、システムを保守してくれる人がいるから毎日営業できるんだよ」
line = "「シルヴィがいつも行ってるフライドチキンのお店も、システムを保守してくれる人がいるから毎日営業できるんだよ」"

[[dialogue]]
speaker = "コハルコ"
# 「こういう目に見えない仕事が日常を支えているの。日々のメンテナンスを疎かにすると、ある日突然トラブルが……」
line = "「こういう目に見えない仕事が日常を支えているの。日々のメンテナンスを疎かにすると、ある日突然トラブルが……」"

[[dialogue]]
speaker = "シルヴィ"
# 「ストップストップー！　あたしが言いたいのはそういうことじゃないって！」
line = "「ストップストップー！　あたしが言いたいのはそういうことじゃないって！」"

[[dialogue]]
speaker = "シルヴィ"
# 「他にやることあるよねって言いたかったの！　ほら、これ！」
line = "「他にやることあるよねって言いたかったの！　ほら、これ！」"

[[dialogue]]
speaker = "unk"
# シルヴィが手にした紙袋には、九浄ヘレナブランドのロゴがデカデカと描かれている。
line = "シルヴィが手にした紙袋には、九浄ヘレナブランドのロゴがデカデカと描かれている。"

[[dialogue]]
speaker = "コハルコ"
# 「うぅ……本当に着ないとダメかなぁ……？」
line = "「うぅ……本当に着ないとダメかなぁ……？」"

[[dialogue]]
speaker = "シルヴィ"
# 「せっかくもらった人工戦闘服だよ？　着ないともったいないって。それに、ヘレナさんにはお世話になってるって言ったのコハルコだし」
line = "「せっかくもらった人工戦闘服だよ？　着ないともったいないって。それに、ヘレナさんにはお世話になってるって言ったのコハルコだし」"

[[dialogue]]
speaker = "コハルコ"
# 「それは……そうなんだけどぉ」
line = "「それは……そうなんだけどぉ」"

[[dialogue]]
speaker = "コハルコ"
# （学園に入学する前、私はハッカーとして活動していた。その中で、身の危険を感じて、ヘレナさんに保護してもらった恩がある）
line = "（学園に入学する前、私はハッカーとして活動していた。その中で、身の危険を感じて、ヘレナさんに保護してもらった恩がある）"

[[dialogue]]
speaker = "コハルコ"
# （新星学園のシステム担当になれたのも、入学できたのも、ヘレナさんのおかげ……なんだけど……）
line = "（新星学園のシステム担当になれたのも、入学できたのも、ヘレナさんのおかげ……なんだけど……）"

[[dialogue]]
speaker = "コハルコ"
# 「だって水着だよ水着！　私なんかが着てどうするのさ。こういうのはもっと似合う人がいると思うんだけどなぁ……」
line = "「だって水着だよ水着！　私なんかが着てどうするのさ。こういうのはもっと似合う人がいると思うんだけどなぁ……」"

[[dialogue]]
speaker = "シルヴィ"
# 「あははっ、コハルコって意外と自分に自信ないよね。大丈夫だって、ヘレナさんがコハルコのためにデザインしてくれたんだしさ」
line = "「あははっ、コハルコって意外と自分に自信ないよね。大丈夫だって、ヘレナさんがコハルコのためにデザインしてくれたんだしさ」"

[[dialogue]]
speaker = "コハルコ"
# 「そりゃシルヴィは似合うと思うよ？　でも私は……」
line = "「そりゃシルヴィは似合うと思うよ？　でも私は……」"

[[dialogue]]
speaker = "シルヴィ"
# 「はいはい、ネガネガしないの。じゃあ、あたしが先に着るから、コハルコはあとからついといで。２人で一緒なら怖くないでしょ？」
line = "「はいはい、ネガネガしないの。じゃあ、あたしが先に着るから、コハルコはあとからついといで。２人で一緒なら怖くないでしょ？」"

[[dialogue]]
speaker = "コハルコ"
# 「もう、子ども扱いしないで」
line = "「もう、子ども扱いしないで」"

[[dialogue]]
speaker = "シルヴィ"
# 「あははっ、そこはお互い様だと思うけど、まぁいいや。じゃあ──」
line = "「あははっ、そこはお互い様だと思うけど、まぁいいや。じゃあ──」"

[[dialogue]]
speaker = "シルヴィ"
# 「変身！」
line = "「変身！」"

[[dialogue]]
speaker = "unk"
# 紙袋を高く掲げ、シルヴィが叫ぶ…………が、何も起きない。
line = "紙袋を高く掲げ、シルヴィが叫ぶ…………が、何も起きない。"

[[dialogue]]
speaker = "シルヴィ"
# 「……変身！　へんっしんっ！　へ～んしん♪　……あれ？　あれあれ？」
line = "「……変身！　へんっしんっ！　へ～んしん♪　……あれ？　あれあれ？」"

[[dialogue]]
speaker = "シルヴィ"
# 「コハルコどうしよ～！？　戦闘服壊れちゃった！？」
line = "「コハルコどうしよ～！？　戦闘服壊れちゃった！？」"

[[dialogue]]
speaker = "コハルコ"
# 「そっか、シルヴィは人工戦闘服は初めてなんだっけ。まずは普通の服みたいに着てから、星力を通すみたいだよ」
line = "「そっか、シルヴィは人工戦闘服は初めてなんだっけ。まずは普通の服みたいに着てから、星力を通すみたいだよ」"

[[dialogue]]
speaker = "シルヴィ"
# 「なるほど～！」
line = "「なるほど～！」"

[[dialogue]]
speaker = "シルヴィ"
# 「というか、そもそも人工戦闘服って何！？　天界から流星市国に帰ってきたらサーシャが知らない戦闘服になっててビックリしたし！」
line = "「というか、そもそも人工戦闘服って何！？　天界から流星市国に帰ってきたらサーシャが知らない戦闘服になっててビックリしたし！」"

[[dialogue]]
speaker = "コハルコ"
# 「さぁ～、私もよく分かんない」
line = "「さぁ～、私もよく分かんない」"

[[dialogue]]
speaker = "unk"
# 戦闘服は本来、天体から与えられた星力が形となったもの。
line = "戦闘服は本来、天体から与えられた星力が形となったもの。"

[[dialogue]]
speaker = "unk"
# 人為的に形態を変えたり能力を付与する人工戦闘服は、長い星騎士の歴史において、まだ始まったばかりの若い技術だ。
line = "人為的に形態を変えたり能力を付与する人工戦闘服は、長い星騎士の歴史において、まだ始まったばかりの若い技術だ。"

[[dialogue]]
speaker = "シルヴィ"
# 「考えても仕方ないから、とりあえず着替えてくる！」
line = "「考えても仕方ないから、とりあえず着替えてくる！」"

[[dialogue]]
speaker = "unk"
# トレーニング施設にはシミュレーターと一緒に更衣室やシャワーが併設されており、コハルコも忙しい時はよく利用している。
line = "トレーニング施設にはシミュレーターと一緒に更衣室やシャワーが併設されており、コハルコも忙しい時はよく利用している。"

[[dialogue]]
speaker = "シルヴィ"
# 「どうかな？　似合ってる？」
line = "「どうかな？　似合ってる？」"

[[dialogue]]
speaker = "コハルコ"
# 「うん。華やかな水着が、元気なシルヴィのイメージにぴったり」
line = "「うん。華やかな水着が、元気なシルヴィのイメージにぴったり」"

[[dialogue]]
speaker = "シルヴィ"
# 「イエーイ！　あたし元気が取り柄だからね！」
line = "「イエーイ！　あたし元気が取り柄だからね！」"

[[dialogue]]
speaker = "シルヴィ"
# 「さぁさぁ、次はコハルコの番だよ」
line = "「さぁさぁ、次はコハルコの番だよ」"

[[dialogue]]
speaker = "コハルコ"
# 「うぅ、もはや逃げ場なし…………変でも笑わないでね」
line = "「うぅ、もはや逃げ場なし…………変でも笑わないでね」"

[[dialogue]]
speaker = "コハルコ"
# 「……ど、どう？　大胆すぎない？」
line = "「……ど、どう？　大胆すぎない？」"

[[dialogue]]
speaker = "シルヴィ"
# 「似合ってる似合ってる！　でもちょっとえっち！」
line = "「似合ってる似合ってる！　でもちょっとえっち！」"

[[dialogue]]
speaker = "コハルコ"
# 「こらー！　そういうこと言わないの！」
line = "「こらー！　そういうこと言わないの！」"

[[dialogue]]
speaker = "シルヴィ"
# 「ごめんごめん。でも本当に似合ってるから、堂々としてればいいのに。じゃあ、このまま海かプールにでも──」
line = "「ごめんごめん。でも本当に似合ってるから、堂々としてればいいのに。じゃあ、このまま海かプールにでも──」"

[[dialogue]]
speaker = "コハルコ"
# 「ま、待って！！」
line = "「ま、待って！！」"

[[dialogue]]
speaker = "コハルコ"
# 「……………………私、泳げないから」
line = "「……………………私、泳げないから」"
