[[dialogue]]
speaker = "unk"
# 緋宮クロトが『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』を討伐した結果、リクリエは終息した。
line = "緋宮クロトが『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』を討伐した結果、リクリエは終息した。"

[[dialogue]]
speaker = "unk"
# 流星市国直属の研究機関、ヘキサグラムの報告によると、アステライトとモンスターの出現は、十分の一以下になったという。
line = "流星市国直属の研究機関、ヘキサグラムの報告によると、アステライトとモンスターの出現は、十分の一以下になったという。"

[[dialogue]]
speaker = "unk"
# しかし──創造神『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』がいなくなったにも関わらず、世界の破壊をうながすモンスターと<ruby=それを生み出す仕組み>アステライト</ruby>が消滅しなかったことも、また事実。
line = "しかし──創造神『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』がいなくなったにも関わらず、世界の破壊をうながすモンスターと<ruby>アステライト<rt>それを生み出す仕組み</rt></ruby>が消滅しなかったことも、また事実。"

[[dialogue]]
speaker = "unk"
# モンスターが消滅しないのであれば、それはリクリエの終息とは言えないのではないか、と論ずる者もいた。
line = "モンスターが消滅しないのであれば、それはリクリエの終息とは言えないのではないか、と論ずる者もいた。"

[[dialogue]]
speaker = "unk"
# 再創生を画策する創造神が不在でも、なおモンスターは活動を続けている──それはむしろ、リクリエはもっと悪質なものに変化したのではないか、と恐れる者もいた。
line = "再創生を画策する創造神が不在でも、なおモンスターは活動を続けている──それはむしろ、リクリエはもっと悪質なものに変化したのではないか、と恐れる者もいた。"

[[dialogue]]
speaker = "unk"
# また、脅威度は下がったものの、一部のモンスターには『ＸＥＬＯＳ』討伐前には見られなかった変異や新たな異常が報告されている。
line = "また、脅威度は下がったものの、一部のモンスターには『ＸＥＬＯＳ』討伐前には見られなかった変異や新たな異常が報告されている。"

[[dialogue]]
speaker = "unk"
# ──後に『アステライト結晶』と命名される<b>それ</b>も、そうした異常のひとつだった。
line = "──後に『アステライト結晶』と命名される<b>それ</b>も、そうした異常のひとつだった。"

[[dialogue]]
speaker = "unk"
# アステライト結晶は『ＸＥＬＯＳ』が生み出した「リクリエを発生させるプログラム」が物質化したもの。
line = "アステライト結晶は『ＸＥＬＯＳ』が生み出した「リクリエを発生させるプログラム」が物質化したもの。"

[[dialogue]]
speaker = "unk"
# 本来、目には見えない高次元に書き込まれたプログラムが、３次元に堕とされた『ＸＥＬＯＳ』の影響で物質化してしまったもの。
line = "本来、目には見えない高次元に書き込まれたプログラムが、３次元に堕とされた『ＸＥＬＯＳ』の影響で物質化してしまったもの。"

[[dialogue]]
speaker = "unk"
# ３次元存在が触れることのできるカタチを得てしまったことで、それを所有するもの、あるいは<b>体に取り込んでしまう</b>モノが現れた。
line = "３次元存在が触れることのできるカタチを得てしまったことで、それを所有するもの、あるいは<b>体に取り込んでしまう</b>モノが現れた。"

[[dialogue]]
speaker = "unk"
# リクリエを発生させるプログラムの断片──そんなものを取り込んでしまった生き物は、本来ではあり得ない異能を手にする。
line = "リクリエを発生させるプログラムの断片──そんなものを取り込んでしまった生き物は、本来ではあり得ない異能を手にする。"

[[dialogue]]
speaker = "unk"
# 完成度で言えば比べるべくもないほど劣化してはいたが……それは『リクリエの使徒化』に近い変質、変異であった。
line = "完成度で言えば比べるべくもないほど劣化してはいたが……それは『リクリエの使徒化』に近い変質、変異であった。"

[[dialogue]]
speaker = "unk"
# その日、ヨミはメイドとして『買い出し』のやり方を教える為に、狛里と共に街へやって来ていた。
line = "その日、ヨミはメイドとして『買い出し』のやり方を教える為に、狛里と共に街へやって来ていた。"

[[dialogue]]
speaker = "狛里"
# 「なるほど！　あそこのお店はお肉が安いのですね！」
line = "「なるほど！　あそこのお店はお肉が安いのですね！」"

[[dialogue]]
speaker = "ヨミ"
# 「はい。品質も良いので、九浄家ではよく利用しています」
line = "「はい。品質も良いので、九浄家ではよく利用しています」"

[[dialogue]]
speaker = "狛里"
# 「メモメモ……覚えたのです！」
line = "「メモメモ……覚えたのです！」"

[[dialogue]]
speaker = "狛里"
# 「これで次からは、狛里１人でも買い出しができるのです！」
line = "「これで次からは、狛里１人でも買い出しができるのです！」"

[[dialogue]]
speaker = "ヨミ"
# 「え？　う～ん……あと何回かは、一緒に来た方がいいと思いますよ？」
line = "「え？　う～ん……あと何回かは、一緒に来た方がいいと思いますよ？」"

[[dialogue]]
speaker = "狛里"
# 「大丈夫なのです！　任せて欲しいのであります！」
line = "「大丈夫なのです！　任せて欲しいのであります！」"

[[dialogue]]
speaker = "狛里"
# 「メモを取ることも覚えたのです！　それに、覚えきれないところは気合いで補うのですっ！」
line = "「メモを取ることも覚えたのです！　それに、覚えきれないところは気合いで補うのですっ！」"

[[dialogue]]
speaker = "ヨミ"
# 「そ、それはちょっと違うような……」
line = "「そ、それはちょっと違うような……」"

[[dialogue]]
speaker = "ヨミ"
# （やっぱり狛里さんは、少し急ぎ過ぎるところがあるなぁ）
line = "（やっぱり狛里さんは、少し急ぎ過ぎるところがあるなぁ）"

[[dialogue]]
speaker = "ヨミ"
# （でも本人は真剣に頑張っているんだろうし……う～～ん）
line = "（でも本人は真剣に頑張っているんだろうし……う～～ん）"

[[dialogue]]
speaker = "unk"
# と、その時だった。
line = "と、その時だった。"

[[dialogue]]
speaker = "ヨミ"
# 「モンスター出現のアラート……！」
line = "「モンスター出現のアラート……！」"

[[dialogue]]
speaker = "狛里"
# 「プリマステラとして、出番であります！」
line = "「プリマステラとして、出番であります！」"

[[dialogue]]
speaker = "ライカンスウォーム"
# 「ガルルルル……！」
line = "「ガルルルル……！」"

[[dialogue]]
speaker = "unk"
# 現場からそう離れていなかった２人が駆けつけると、そこにいたのは見覚えのある『狼』の群れだった。
line = "現場からそう離れていなかった２人が駆けつけると、そこにいたのは見覚えのある『狼』の群れだった。"

[[dialogue]]
speaker = "狛里"
# 「！　あれは……『ライカンスウォーム』！？」
line = "「！　あれは……『ライカンスウォーム』！？」"

[[dialogue]]
speaker = "狛里"
# 「どうして人間界にいるのです！？」
line = "「どうして人間界にいるのです！？」"

[[dialogue]]
speaker = "unk"
# ライカンスウォームは、本来なら魔界に生息している原生生物である。
line = "ライカンスウォームは、本来なら魔界に生息している原生生物である。"

[[dialogue]]
speaker = "ヨミ"
# 「警報システムの反応、そしてアステラから出現しているってことは……」
line = "「警報システムの反応、そしてアステラから出現しているってことは……」"

[[dialogue]]
speaker = "ヨミ"
# 「あれはライカンスウォームの姿を模したモンスター！？　でもそんなの、見たことも聞いたこともありませんっ！」
line = "「あれはライカンスウォームの姿を模したモンスター！？　でもそんなの、見たことも聞いたこともありませんっ！」"

[[dialogue]]
speaker = "狛里"
# 「ヨミ先輩！　狛里が前に出るのです！」
line = "「ヨミ先輩！　狛里が前に出るのです！」"

[[dialogue]]
speaker = "ヨミ"
# 「狛里さん！？」
line = "「狛里さん！？」"

[[dialogue]]
speaker = "狛里"
# 「大丈夫であります！　ライカンスウォームなら、辺境で嫌っていうほど相手にしてきたのです！」
line = "「大丈夫であります！　ライカンスウォームなら、辺境で嫌っていうほど相手にしてきたのです！」"

[[dialogue]]
speaker = "unk"
# そう言うなり、狛里は群れへ向かって駆け出し始める。
line = "そう言うなり、狛里は群れへ向かって駆け出し始める。"

[[dialogue]]
speaker = "ヨミ"
# 「待ってください！　１人でそんな前に出ちゃ……！」
line = "「待ってください！　１人でそんな前に出ちゃ……！」"

[[dialogue]]
speaker = "狛里"
# 「はああぁっ！！」
line = "「はああぁっ！！」"

[[dialogue]]
speaker = "unk"
# 狛里は群れの中心へ飛び込んでいく。
line = "狛里は群れの中心へ飛び込んでいく。"

[[dialogue]]
speaker = "ライカンスウォーム"
# 「ガルルルァッ！」
line = "「ガルルルァッ！」"

[[dialogue]]
speaker = "狛里"
# 「ばうわふっ！！」
line = "「ばうわふっ！！」"

[[dialogue]]
speaker = "unk"
# そして、まるで獣同士がぶつかり合うような荒々しい戦いを繰り広げる。
line = "そして、まるで獣同士がぶつかり合うような荒々しい戦いを繰り広げる。"

[[dialogue]]
speaker = "狛里"
# 「そこでありますっ！」
line = "「そこでありますっ！」"

[[dialogue]]
speaker = "ライカンスウォーム"
# 「ギャウッ！？」
line = "「ギャウッ！？」"

[[dialogue]]
speaker = "unk"
# 狛里は襲い来る群れを、次々と敵を蹴散らしていく。
line = "狛里は襲い来る群れを、次々と敵を蹴散らしていく。"

[[dialogue]]
speaker = "ヨミ"
# （狛里さん、やっぱり強い！）
line = "（狛里さん、やっぱり強い！）"

[[dialogue]]
speaker = "unk"
# ヨミは近くのライカンスウォームと戦いながら、思わず息を呑む。
line = "ヨミは近くのライカンスウォームと戦いながら、思わず息を呑む。"

[[dialogue]]
speaker = "unk"
# 狛里の戦いには迷いがなかった。
line = "狛里の戦いには迷いがなかった。"

[[dialogue]]
speaker = "ライカンスウォーム"
# 「ガアァッ！」
line = "「ガアァッ！」"

[[dialogue]]
speaker = "狛里"
# 「甘いであります！」
line = "「甘いであります！」"

[[dialogue]]
speaker = "ヨミ"
# 「はぁっ！　爆裂鈴音！」
line = "「はぁっ！　爆裂鈴音！」"

[[dialogue]]
speaker = "unk"
# ヨミは狛里がカバーしきれない範囲のライカンスウォームを、狛里の背後を守りながら倒していく。
line = "ヨミは狛里がカバーしきれない範囲のライカンスウォームを、狛里の背後を守りながら倒していく。"

[[dialogue]]
speaker = "unk"
# とはいえ、狛里の撃破数は圧倒的だ。短時間でヨミの数倍のライカンスウォームを倒していた。
line = "とはいえ、狛里の撃破数は圧倒的だ。短時間でヨミの数倍のライカンスウォームを倒していた。"

[[dialogue]]
speaker = "ヨミ"
# （戦闘に関しては、私が口を出さなくても大丈夫なんじゃ……）
line = "（戦闘に関しては、私が口を出さなくても大丈夫なんじゃ……）"

[[dialogue]]
speaker = "unk"
# そう思いかけたところで――ふと違和感を覚える。
line = "そう思いかけたところで――ふと違和感を覚える。"

[[dialogue]]
speaker = "狛里"
# 「はぁ……はぁ……！」
line = "「はぁ……はぁ……！」"

[[dialogue]]
speaker = "ヨミ"
# （あれ？　狛里さんの動きが、少しずつ荒くなって……）
line = "（あれ？　狛里さんの動きが、少しずつ荒くなって……）"

[[dialogue]]
speaker = "unk"
# それはどこか既視感があって。
line = "それはどこか既視感があって。"

[[dialogue]]
speaker = "ヨミ"
# （メイドの仕事の時と同じ……）
line = "（メイドの仕事の時と同じ……）"

[[dialogue]]
speaker = "ヨミ"
# （ペース配分無視の全力全開、オーバーペース）
line = "（ペース配分無視の全力全開、オーバーペース）"

[[dialogue]]
speaker = "unk"
# 判断に迷う。
line = "判断に迷う。"

[[dialogue]]
speaker = "unk"
# 先輩としてグングンと先行していく狛里を止めるべきか。それとも狛里の判断を信じるべきか。
line = "先輩としてグングンと先行していく狛里を止めるべきか。それとも狛里の判断を信じるべきか。"

[[dialogue]]
speaker = "unk"
# 迷っている内に――
line = "迷っている内に――"

[[dialogue]]
speaker = "ライカンスウォーム"
# 「ガルアアァッ！！」
line = "「ガルアアァッ！！」"

[[dialogue]]
speaker = "狛里"
# 「くっ！？」
line = "「くっ！？」"

[[dialogue]]
speaker = "unk"
# 死角から飛び出した一体が、狛里の腕を爪で切り裂いた。
line = "死角から飛び出した一体が、狛里の腕を爪で切り裂いた。"

[[dialogue]]
speaker = "ヨミ"
# 「あっ、狛里さんっ！！」
line = "「あっ、狛里さんっ！！」"

[[dialogue]]
speaker = "unk"
# ヨミは狛里を助ける為に飛び出す。
line = "ヨミは狛里を助ける為に飛び出す。"

[[dialogue]]
speaker = "ヨミ"
# 「破邪の鈴よ――爆裂浄化！」
line = "「破邪の鈴よ――爆裂浄化！」"

[[dialogue]]
speaker = "ライカンスウォーム"
# 「グルアアアァッ！？」
line = "「グルアアアァッ！？」"

[[dialogue]]
speaker = "unk"
# その後。
line = "その後。"

[[dialogue]]
speaker = "unk"
# ライカンスウォームの群れは、ひとまず全て討伐することができた。
line = "ライカンスウォームの群れは、ひとまず全て討伐することができた。"

[[dialogue]]
speaker = "狛里"
# 「ふぅ……！」
line = "「ふぅ……！」"

[[dialogue]]
speaker = "狛里"
# 「ばうわふっ♪　プリマステラとしての初戦闘、完了であります！」
line = "「ばうわふっ♪　プリマステラとしての初戦闘、完了であります！」"

[[dialogue]]
speaker = "ヨミ"
# 「狛里さん！」
line = "「狛里さん！」"

[[dialogue]]
speaker = "ヨミ"
# 「大丈夫ですか！？　怪我を見せて下さい！」
line = "「大丈夫ですか！？　怪我を見せて下さい！」"

[[dialogue]]
speaker = "狛里"
# 「あっ、これでありますか？　掠り傷なのですし、ぜんぜん平気なのですよ♪」
line = "「あっ、これでありますか？　掠り傷なのですし、ぜんぜん平気なのですよ♪」"

[[dialogue]]
speaker = "unk"
# 腕から血が流れている。にもかかわらず、狛里は笑っていた。
line = "腕から血が流れている。にもかかわらず、狛里は笑っていた。"

[[dialogue]]
speaker = "ヨミ"
# 「でも……！」
line = "「でも……！」"

[[dialogue]]
speaker = "狛里"
# 「怪我をしたのは、狛里がちょっと飛び出しすぎちゃったからなのです。もっと上手にできたはずなのに、張り切りすぎちゃったかも……えへへっ」
line = "「怪我をしたのは、狛里がちょっと飛び出しすぎちゃったからなのです。もっと上手にできたはずなのに、張り切りすぎちゃったかも……えへへっ」"

[[dialogue]]
speaker = "狛里"
# 「心配かけてごめんなさいなのです！　でも、これくらいは辺境で毎日のように経験してたのです！」
line = "「心配かけてごめんなさいなのです！　でも、これくらいは辺境で毎日のように経験してたのです！」"

[[dialogue]]
speaker = "狛里"
# 「それよりも、周りに怪我人さんがいないかどうか、確認してくるのです！」
line = "「それよりも、周りに怪我人さんがいないかどうか、確認してくるのです！」"

[[dialogue]]
speaker = "ヨミ"
# 「あっ……！」
line = "「あっ……！」"

[[dialogue]]
speaker = "unk"
# 狛里は怪我も気にせず走って行ってしまう。
line = "狛里は怪我も気にせず走って行ってしまう。"

[[dialogue]]
speaker = "ヨミ"
# （また同じ……私は、気づいてたのに）
line = "（また同じ……私は、気づいてたのに）"

[[dialogue]]
speaker = "ヨミ"
# 「先輩失格です……」
line = "「先輩失格です……」"

[[dialogue]]
speaker = "unk"
# 自分の不甲斐なさに胸が痛み、その場で尻尾と耳を垂らしてしまうヨミなのだった。
line = "自分の不甲斐なさに胸が痛み、その場で尻尾と耳を垂らしてしまうヨミなのだった。"
