[[dialogue]]
speaker = "unk"
# 週末の渋谷ともなれば、何処も人でいっぱいだった。
line = "週末の渋谷ともなれば、何処も人でいっぱいだった。"

[[dialogue]]
speaker = "藍"
# 「わ、わ……人込みは苦手で……あの、落ち着いて話せるところに行きませんか……？」
line = "「わ、わ……人込みは苦手で……あの、落ち着いて話せるところに行きませんか……？」"

[[dialogue]]
speaker = "unk"
# 俺たちはオープンテラスのカフェに腰を落ち着かせた。
line = "俺たちはオープンテラスのカフェに腰を落ち着かせた。"

[[dialogue]]
speaker = "藍"
# 「はぁ……まだ何もしてないのに……なんだか疲れちゃいました」
line = "「はぁ……まだ何もしてないのに……なんだか疲れちゃいました」"

[[dialogue]]
speaker = "藍"
# 「ごめんなさい、私、ずっと緊張しっぱなしで……これでも会長さんとは、お話ができている方なんですけど……」
line = "「ごめんなさい、私、ずっと緊張しっぱなしで……これでも会長さんとは、お話ができている方なんですけど……」"

[[dialogue]]
speaker = "unk"
# 演技してる時は、あんなに堂々としてるのに
line = "演技してる時は、あんなに堂々としてるのに"

[[dialogue]]
speaker = "藍"
# 「い、いえ。演技している時も、すごく緊張しているんですよ？」
line = "「い、いえ。演技している時も、すごく緊張しているんですよ？」"

[[dialogue]]
speaker = "藍"
# 「でも、私の演じている役は、どんなに緊張していても、それを表には出さない子ばかりですから。役に入り込んでしまえば、わりと大丈夫なんです」
line = "「でも、私の演じている役は、どんなに緊張していても、それを表には出さない子ばかりですから。役に入り込んでしまえば、わりと大丈夫なんです」"

[[dialogue]]
speaker = "unk"
# 男性が苦手な原因に心当たりは？
line = "男性が苦手な原因に心当たりは？"

[[dialogue]]
speaker = "藍"
# 「そうですね……私、ずっと女子校に通っていたので……新星学園に来るまで同年代の男性と接点がなかったんです」
line = "「そうですね……私、ずっと女子校に通っていたので……新星学園に来るまで同年代の男性と接点がなかったんです」"

[[dialogue]]
speaker = "unk"
# 同年代以外の男性はあるんだ？
line = "同年代以外の男性はあるんだ？"

[[dialogue]]
speaker = "藍"
# 「あ、えっと……私、一応、芸能事務所に預かりで所属しているんです……あっ、レミカさんと同じ事務所なんですけど」
line = "「あ、えっと……私、一応、芸能事務所に預かりで所属しているんです……あっ、レミカさんと同じ事務所なんですけど」"

[[dialogue]]
speaker = "藍"
# 「たまにお仕事でお会いする男性は、皆さん、年上で……ちょっと怖い感じな方が多くて……」
line = "「たまにお仕事でお会いする男性は、皆さん、年上で……ちょっと怖い感じな方が多くて……」"

[[dialogue]]
speaker = "藍"
# 「その人たちに会う度、ずっと言われているんです。『アピールが弱い』『面白みがない』『そんなんじゃ芸能界じゃやっていけない』って……」
line = "「その人たちに会う度、ずっと言われているんです。『アピールが弱い』『面白みがない』『そんなんじゃ芸能界じゃやっていけない』って……」"

[[dialogue]]
speaker = "藍"
# 「そんな風に言われ続けているから、芸能界にいるのも苦しくって、もう事務所もやめちゃおうかなって考えてたところで……もともと、演者志望でもなかったですしね」
line = "「そんな風に言われ続けているから、芸能界にいるのも苦しくって、もう事務所もやめちゃおうかなって考えてたところで……もともと、演者志望でもなかったですしね」"

[[dialogue]]
speaker = "unk"
# あんなに上手いのに……！？
line = "あんなに上手いのに……！？"

[[dialogue]]
speaker = "藍"
# 「ふふ、ありがとうございます。小さい頃から周りの子より背が高かったので、目立ってはいたんですけど……」
line = "「ふふ、ありがとうございます。小さい頃から周りの子より背が高かったので、目立ってはいたんですけど……」"

[[dialogue]]
speaker = "unk"
# 役者を志す転機があったの？
line = "役者を志す転機があったの？"

[[dialogue]]
speaker = "藍"
# 「昔いた学校の文化祭で、クラスの劇でロミオとジュリエットをやることになったんです」
line = "「昔いた学校の文化祭で、クラスの劇でロミオとジュリエットをやることになったんです」"

[[dialogue]]
speaker = "藍"
# 「ロミオとジュリエットで、最初に与えられたのは木の役でした。ジュリエットの屋敷にある果樹園の木です」
line = "「ロミオとジュリエットで、最初に与えられたのは木の役でした。ジュリエットの屋敷にある果樹園の木です」"

[[dialogue]]
speaker = "藍"
# 「背が高いからって、それだけの理由でした。誰がやってもあまり変わらないような背景役なのに……私はそれでも真剣に取り組んでたんです」
line = "「背が高いからって、それだけの理由でした。誰がやってもあまり変わらないような背景役なのに……私はそれでも真剣に取り組んでたんです」"

[[dialogue]]
speaker = "藍"
# 「でも、本番の３日前に、ジュリエット役の子が転んで足を骨折してしまい、劇に出られなくなっちゃったんです」
line = "「でも、本番の３日前に、ジュリエット役の子が転んで足を骨折してしまい、劇に出られなくなっちゃったんです」"

[[dialogue]]
speaker = "藍"
# 「突然のことだったから、クラスはてんやわんやで……花形のジュリエットですけど、役を覚えるには本番までの期日があまりにも短すぎました」
line = "「突然のことだったから、クラスはてんやわんやで……花形のジュリエットですけど、役を覚えるには本番までの期日があまりにも短すぎました」"

[[dialogue]]
speaker = "藍"
# 「うろ覚えでジュリエットなんてやったら、全校生徒の前で恥をかくからって、皆で押し付け合いになって……最後の最後に木の役だった私に押し付けられたんです」
line = "「うろ覚えでジュリエットなんてやったら、全校生徒の前で恥をかくからって、皆で押し付け合いになって……最後の最後に木の役だった私に押し付けられたんです」"

[[dialogue]]
speaker = "藍"
# 「でも、私は木の役とはいえ、ずっと舞台の上で、ジュリエット役の子が演じているのを傍で見てましたから」
line = "「でも、私は木の役とはいえ、ずっと舞台の上で、ジュリエット役の子が演じているのを傍で見てましたから」"

[[dialogue]]
speaker = "藍"
# 「セリフもだいたい覚えてましたし、見様見真似でやってみたら、なんか……できちゃいまして」
line = "「セリフもだいたい覚えてましたし、見様見真似でやってみたら、なんか……できちゃいまして」"

[[dialogue]]
speaker = "unk"
# 天才だ……！
line = "天才だ……！"

[[dialogue]]
speaker = "藍"
# 「そ、そんなことないです！　今と比べたら、演技も全然稚拙で、お恥ずかしい限りで……！」
line = "「そ、そんなことないです！　今と比べたら、演技も全然稚拙で、お恥ずかしい限りで……！」"

[[dialogue]]
speaker = "藍"
# 「でも、背が高いおかげで舞台俳優に向いていたみたいですし、私の引っ込み思案な性格も、悲劇のヒロインのジュリエットに合っていたんでしょうね」
line = "「でも、背が高いおかげで舞台俳優に向いていたみたいですし、私の引っ込み思案な性格も、悲劇のヒロインのジュリエットに合っていたんでしょうね」"

[[dialogue]]
speaker = "藍"
# 「女子校でロミオ役も女の子だったおかげで、物怖じせずに済みました。文化祭での本番も大成功で、大盛り上がりでした」
line = "「女子校でロミオ役も女の子だったおかげで、物怖じせずに済みました。文化祭での本番も大成功で、大盛り上がりでした」"

[[dialogue]]
speaker = "藍"
# 「そうしたら、文化祭での動画をライブ配信していた人がいて、その動画が今の芸能事務所の目に留まって、スカウトされて……今に至っています」
line = "「そうしたら、文化祭での動画をライブ配信していた人がいて、その動画が今の芸能事務所の目に留まって、スカウトされて……今に至っています」"

[[dialogue]]
speaker = "藍"
# 「演技は少しは上達しましたけど、男性が怖いのはちっとも克服できてないです……あれ？」
line = "「演技は少しは上達しましたけど、男性が怖いのはちっとも克服できてないです……あれ？」"

[[dialogue]]
speaker = "藍"
# 「ど、どうしてですかね……会長さんはあんまり怖くないです……！」
line = "「ど、どうしてですかね……会長さんはあんまり怖くないです……！」"

[[dialogue]]
speaker = "藍"
# 「私、同年代の男の子とこんな風にお喋りするのも、昔のことを話したのも初めてなんですよ……？」
line = "「私、同年代の男の子とこんな風にお喋りするのも、昔のことを話したのも初めてなんですよ……？」"

[[dialogue]]
speaker = "藍"
# 「やっぱり、メイプルさんが言っていた通りです。会長さんには人の心を開かせる不思議な力があるんですね、ふふ」
line = "「やっぱり、メイプルさんが言っていた通りです。会長さんには人の心を開かせる不思議な力があるんですね、ふふ」"

[[dialogue]]
speaker = "藍"
# 「あっ、もうこんな時間……そろそろ帰りましょうか。今日はありがとうございました。とっても楽しかったです」
line = "「あっ、もうこんな時間……そろそろ帰りましょうか。今日はありがとうございました。とっても楽しかったです」"

[[dialogue]]
speaker = "藍"
# 「うぅ……すごい人……きゃっ！？」
line = "「うぅ……すごい人……きゃっ！？」"

[[dialogue]]
speaker = "unk"
# スクランブル交差点でごった返す人波に、藍が飲み込まれそうになる。
line = "スクランブル交差点でごった返す人波に、藍が飲み込まれそうになる。"

[[dialogue]]
speaker = "unk"
# 咄嗟に伸ばした腕は、なんとか藍の手を掴んでいた。
line = "咄嗟に伸ばした腕は、なんとか藍の手を掴んでいた。"

[[dialogue]]
speaker = "藍"
# 「ひゃっ！？　あ、ありがとうございます、会長さん。転んじゃうところでした……」
line = "「ひゃっ！？　あ、ありがとうございます、会長さん。転んじゃうところでした……」"

[[dialogue]]
speaker = "unk"
# 足を骨折したらジュリエットが演れなくなるよ
line = "足を骨折したらジュリエットが演れなくなるよ"

[[dialogue]]
speaker = "藍"
# 「……え？　あっ、私が初めてジュリエットを演った時の話ですか……あはは」
line = "「……え？　あっ、私が初めてジュリエットを演った時の話ですか……あはは」"

[[dialogue]]
speaker = "藍"
# 「……あれ？　私、会長さんと手、繋げてます」
line = "「……あれ？　私、会長さんと手、繋げてます」"

[[dialogue]]
speaker = "藍"
# 「会長さんの手、すごく優しくて、あったかくて……ちっとも怖くないです。これなら私……舞台の上でも大丈夫そうです」
line = "「会長さんの手、すごく優しくて、あったかくて……ちっとも怖くないです。これなら私……舞台の上でも大丈夫そうです」"

[[dialogue]]
speaker = "unk"
# こうして、藍は異性と手を繋ぐことを克服し、ロクサーナの差し向けたデートは見事成功したけど──
line = "こうして、藍は異性と手を繋ぐことを克服し、ロクサーナの差し向けたデートは見事成功したけど──"

[[dialogue]]
speaker = "ロクサーナ"
# 「ふっふっふ……！」
line = "「ふっふっふ……！」"

[[dialogue]]
speaker = "unk"
# 演出家がどこかでほくそ笑んでいるような気がしたのだった。
line = "演出家がどこかでほくそ笑んでいるような気がしたのだった。"
