[[dialogue]]
speaker = "unk"
# 第８話,ＶＳ星喰らいシャドウ・アポロ戦闘後,B
line = "第８話,ＶＳ星喰らいシャドウ・アポロ戦闘後,B"

[[dialogue]]
speaker = "アポロ"
# 「なんでだっ！　どうしてこんなに、こいつらは……強いんだっ──！？」
line = "「なんでだっ！　どうしてこんなに、こいつらは……強いんだっ──！？」"

[[dialogue]]
speaker = "アポロ"
# 「世界は、やり直すべきなんだ……消えるべきなのにっ！！」
line = "「世界は、やり直すべきなんだ……消えるべきなのにっ！！」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「そこの『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』は幻影みたいなものだ！　使徒に攻撃を集中する──セーラ、援護を頼む！！」
line = "「そこの『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』は幻影みたいなものだ！　使徒に攻撃を集中する──セーラ、援護を頼む！！」"

[[dialogue]]
speaker = "セーラ"
# 「おっけーアポロちゃん！　ハートブレイクショット！！」
line = "「おっけーアポロちゃん！　ハートブレイクショット！！」"

[[dialogue]]
speaker = "アポロ"
# 「だめだっ……この拠点も、もう──ぐぅううぅううっ！！」
line = "「だめだっ……この拠点も、もう──ぐぅううぅううっ！！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「最後のトドメ──任せますわ！！」
line = "「最後のトドメ──任せますわ！！」"

[[dialogue]]
speaker = "セナリィ"
# 「風穴ブチ空けてやりましてよ！　ベットショット・ハイローラー！！！」
line = "「風穴ブチ空けてやりましてよ！　ベットショット・ハイローラー！！！」"

[[dialogue]]
speaker = "アポロ"
# 「──────うああぁあぁぁああっ！！！」
line = "「──────うああぁあぁぁああっ！！！」"

[[dialogue]]
speaker = "ルリエル"
# 「やりましたっ！　セナリィさんの攻撃……手応えありなのです！」
line = "「やりましたっ！　セナリィさんの攻撃……手応えありなのです！」"

[[dialogue]]
speaker = "ユウリ"
# 「ああっ。ようやく、使徒の動きが止まった……！！」
line = "「ああっ。ようやく、使徒の動きが止まった……！！」"

[[dialogue]]
speaker = "アポロ"
# 「ここまで、か…………くそ…………！！」
line = "「ここまで、か…………くそ…………！！」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 「ギ…………ィ…………ィィィ…………」
line = "「ギ…………ィ…………ィィィ…………」"

[[dialogue]]
speaker = "ソフィア"
# 「『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』が……何かを、伝えようとしている……？」
line = "「『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』が……何かを、伝えようとしている……？」"

[[dialogue]]
speaker = "サーシャ"
# 「もう抵抗する力はなさそうだけれど……油断しちゃダメよ、ソフィ」
line = "「もう抵抗する力はなさそうだけれど……油断しちゃダメよ、ソフィ」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 「ギ…………ァ…………ァァアァ…………」
line = "「ギ…………ァ…………ァァアァ…………」"

[[dialogue]]
speaker = "アポロ"
# 「へへ……負け、か……最期に、神の言葉を、教えてやるよ……」
line = "「へへ……負け、か……最期に、神の言葉を、教えてやるよ……」"

[[dialogue]]
speaker = "アポロ"
# 「『ヒトの分際で……どこまでも愚弄する……蒙昧な輩たち……許さん……決して……許さん…………』」
line = "「『ヒトの分際で……どこまでも愚弄する……蒙昧な輩たち……許さん……決して……許さん…………』」"

[[dialogue]]
speaker = "セナリィ"
# 「はっ。悪党の最期に似合いのセリフですわね！」
line = "「はっ。悪党の最期に似合いのセリフですわね！」"

[[dialogue]]
speaker = "アポロ"
# 「『決して許さん……呪ってやる……その魂の、輪廻が尽きるまで…………』」
line = "「『決して許さん……呪ってやる……その魂の、輪廻が尽きるまで…………』」"

[[dialogue]]
speaker = "アポロ"
# 「『おのれ…………バンデット・セナリィ────！！』」
line = "「『おのれ…………バンデット・セナリィ────！！』」"

[[dialogue]]
speaker = "セナリィ"
# 「──ええぇえぇえええぇえぇっ！？」
line = "「──ええぇえぇえええぇえぇっ！？」"

[[dialogue]]
speaker = "unk"
# アポロのシャドウと『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』の分身体は──塵のようにかき消えた。
line = "アポロのシャドウと『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』の分身体は──塵のようにかき消えた。"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「……しぶとい連中でしたが、なんとか勝利を手にできましたわね」
line = "「……しぶとい連中でしたが、なんとか勝利を手にできましたわね」"

[[dialogue]]
speaker = "セナリィ"
# 「ちょっとお待ちなさいな！？　なんで私だけ特別に恨まれてますの！？」
line = "「ちょっとお待ちなさいな！？　なんで私だけ特別に恨まれてますの！？」"

[[dialogue]]
speaker = "ソフィア"
# 「最後のトドメを刺したのは、セナリィさんの銃弾でしたから──お見事でした」
line = "「最後のトドメを刺したのは、セナリィさんの銃弾でしたから──お見事でした」"

[[dialogue]]
speaker = "セナリィ"
# 「嬉しくねーですわ！？　なんか呪ってやるとか言ってましたわよ！？」
line = "「嬉しくねーですわ！？　なんか呪ってやるとか言ってましたわよ！？」"

[[dialogue]]
speaker = "マハムート"
# 「……はぁ。戦いが終わった後も騒々しいんだから」
line = "「……はぁ。戦いが終わった後も騒々しいんだから」"

[[dialogue]]
speaker = "マハムート"
# 「負け惜しみを言わせるくらいに圧倒できたことを誇るべきだわ。よくやったわね、皆」
line = "「負け惜しみを言わせるくらいに圧倒できたことを誇るべきだわ。よくやったわね、皆」"

[[dialogue]]
speaker = "マハムート"
# 「アルタイルの星騎士たちの連携も見事だったけれど……リーエン。流石はキュリオスの女帝に仕えるだけはあるわね」
line = "「アルタイルの星騎士たちの連携も見事だったけれど……リーエン。流石はキュリオスの女帝に仕えるだけはあるわね」"

[[dialogue]]
speaker = "リーエン"
# 「妃竜院マハムート。貴様も賞賛に値する戦いぶりだった──いずれ手合わせを願いたいものだ」
line = "「妃竜院マハムート。貴様も賞賛に値する戦いぶりだった──いずれ手合わせを願いたいものだ」"

[[dialogue]]
speaker = "マハムート"
# 「いいでしょう。<ruby=ラルーナ>新星寮</ruby>の寮長として迎え撃ってあげるわ」
line = "「いいでしょう。<ruby>新星寮<rt>ラルーナ</rt></ruby>の寮長として迎え撃ってあげるわ」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「よし……これで『星喰らい』の拠点制圧も３つ目だ！　王手とまではいかないが、『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』をかなり追い詰められたはずだ」
line = "「よし……これで『星喰らい』の拠点制圧も３つ目だ！　王手とまではいかないが、『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』をかなり追い詰められたはずだ」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「しかし驚いたぞ！　幹内世界の可能性ってやつは凄まじいな、まさかバニーガールの戦闘服まであるだなんて！」
line = "「しかし驚いたぞ！　幹内世界の可能性ってやつは凄まじいな、まさかバニーガールの戦闘服まであるだなんて！」"

[[dialogue]]
speaker = "ルリエル"
# 「はいなのです！　セーラ先輩はともかく、あの真面目なユウリ先輩まで……いったい何が起こったらこんなことに！？」
line = "「はいなのです！　セーラ先輩はともかく、あの真面目なユウリ先輩まで……いったい何が起こったらこんなことに！？」"

[[dialogue]]
speaker = "ユウリ"
# 「掘り下げんな！　さっさとアルタイルに戻るぞっ！　一刻も早く、この戦闘服を脱がせろ！！」
line = "「掘り下げんな！　さっさとアルタイルに戻るぞっ！　一刻も早く、この戦闘服を脱がせろ！！」"

[[dialogue]]
speaker = "セーラ"
# 「ちょいちょい、ルリちー？　ウチはともかくってどーゆーことー？」
line = "「ちょいちょい、ルリちー？　ウチはともかくってどーゆーことー？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ユウリさんのお気持ち、私には痛いほど分かりますわ……！」
line = "「ユウリさんのお気持ち、私には痛いほど分かりますわ……！」"

[[dialogue]]
speaker = "ユウリ"
# 「うお！？　ヒルディオーネ先輩……！？」
line = "「うお！？　ヒルディオーネ先輩……！？」"

[[dialogue]]
speaker = "ソフィア"
# 「おぉ。ユウリ先輩の両手をがっちり握って……なるほど、バニーの皆さん、戦闘服が発現した経緯は同じ、ということでしょうか？」
line = "「おぉ。ユウリ先輩の両手をがっちり握って……なるほど、バニーの皆さん、戦闘服が発現した経緯は同じ、ということでしょうか？」"

[[dialogue]]
speaker = "セナリィ"
# 「私やマイン、それに千園寺様だけではなかったんですわね！　あのヘンタイの毒牙にかかった不幸な星騎士は……！」
line = "「私やマイン、それに千園寺様だけではなかったんですわね！　あのヘンタイの毒牙にかかった不幸な星騎士は……！」"

[[dialogue]]
speaker = "ユウリ"
# 「え……へ、ヘンタイ？　ユリアーナ……じゃないっ。ユーリスはそんな奴じゃないですよ、先輩！！」
line = "「え……へ、ヘンタイ？　ユリアーナ……じゃないっ。ユーリスはそんな奴じゃないですよ、先輩！！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「……ユーリス？　新星学園の、ジルラント王国の……？　確か緋宮会長と同じく、珍しい男性の星騎士でしたわよね」
line = "「……ユーリス？　新星学園の、ジルラント王国の……？　確か緋宮会長と同じく、珍しい男性の星騎士でしたわよね」"

[[dialogue]]
speaker = "セーラ"
# 「ウチとユウリちゃんのバニーフォームは、あの王子様から貰ったものだからね～♪」
line = "「ウチとユウリちゃんのバニーフォームは、あの王子様から貰ったものだからね～♪」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ですわっ！？　なんてハレンチな！！！」
line = "「ですわっ！？　なんてハレンチな！！！」"

[[dialogue]]
speaker = "セナリィ"
# 「あの超がつくほど真面目そうな王子様が……？　ヒトは見かけによりませんのね」
line = "「あの超がつくほど真面目そうな王子様が……？　ヒトは見かけによりませんのね」"

[[dialogue]]
speaker = "ユウリ"
# 「ま、待て待て！　あたしら、カジノに潜入捜査をしなくちゃいけなくて、それで用意してもらっただけだって！」
line = "「ま、待て待て！　あたしら、カジノに潜入捜査をしなくちゃいけなくて、それで用意してもらっただけだって！」"

[[dialogue]]
speaker = "セーラ"
# 「そーそー。てゆーか、セナリィちゃんたちの衣装は、王子様経由じゃないってこと？」
line = "「そーそー。てゆーか、セナリィちゃんたちの衣装は、王子様経由じゃないってこと？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「──ううぅっ！！」
line = "「──ううぅっ！！」"

[[dialogue]]
speaker = "セナリィ"
# 「頭がっ……！　存在しないヘンタイの記憶が、また……！！」
line = "「頭がっ……！　存在しないヘンタイの記憶が、また……！！」"

[[dialogue]]
speaker = "ユウリ"
# 「あたしやセーラさん以上に、ヤバイ状況だったみたいだな……」
line = "「あたしやセーラさん以上に、ヤバイ状況だったみたいだな……」"

[[dialogue]]
speaker = "セーラ"
# 「語ると長そうだね～♪　その辺りはまた、帰ってから聞くことにしよっか♪」
line = "「語ると長そうだね～♪　その辺りはまた、帰ってから聞くことにしよっか♪」"

[[dialogue]]
speaker = "サーシャ"
# 「うふふ♪　ソフィもお疲れ様。それにとーってもカワイイ衣装を着てるのね～<emoji=heart04>　ぎゅーってしていい？」
line = "「うふふ♪　ソフィもお疲れ様。それにとーってもカワイイ衣装を着てるのね～<emoji=heart04>　ぎゅーってしていい？」"

[[dialogue]]
speaker = "ソフィア"
# 「いいわけないでしょう。人前でベタベタしないでください、しっしっ」
line = "「いいわけないでしょう。人前でベタベタしないでください、しっしっ」"

[[dialogue]]
speaker = "サーシャ"
# 「あーん、そんなぁ。こんなにオシャレしてる妹をハグできないだなんて、生殺しだわ～……！」
line = "「あーん、そんなぁ。こんなにオシャレしてる妹をハグできないだなんて、生殺しだわ～……！」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「よし──確保だ！」
line = "「よし──確保だ！」"

[[dialogue]]
speaker = "ソフィア"
# 「ちょっ、アポロさん！？　は、離してくださいっ！」
line = "「ちょっ、アポロさん！？　は、離してくださいっ！」"

[[dialogue]]
speaker = "アポロ（大人）"
# 「いーや、離さないぞ！　姉も妹も、いて当たり前じゃない。いつ別れるかわかったもんじゃないんだからな！　ほらサーシャ！」
line = "「いーや、離さないぞ！　姉も妹も、いて当たり前じゃない。いつ別れるかわかったもんじゃないんだからな！　ほらサーシャ！」"

[[dialogue]]
speaker = "サーシャ"
# 「アポロちゃん、ナイスフォロー～♪　ソフィを捕まえて──ぎゅ～ぅ～っ<emoji=heart04>」
line = "「アポロちゃん、ナイスフォロー～♪　ソフィを捕まえて──ぎゅ～ぅ～っ<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「ああぁ、もうっ……姉さんっ、むぎゅぅ！？」
line = "「ああぁ、もうっ……姉さんっ、むぎゅぅ！？」"

[[dialogue]]
speaker = "サーシャ"
# 「甘いパンケーキの香りがするわ～……うふふ<emoji=heart04>　今日はずーっと、ソフィをだっこしちゃおうかしら～<emoji=heart04>」
line = "「甘いパンケーキの香りがするわ～……うふふ<emoji=heart04>　今日はずーっと、ソフィをだっこしちゃおうかしら～<emoji=heart04>」"

[[dialogue]]
speaker = "ソフィア"
# 「ダメに決まってるでしょう！　離れてください～っ！」
line = "「ダメに決まってるでしょう！　離れてください～っ！」"

[[dialogue]]
speaker = "ルリエル"
# 「と言いつつ、ソフィアもまんざらでもなさそうなのです。でんでん♪」
line = "「と言いつつ、ソフィアもまんざらでもなさそうなのです。でんでん♪」"

[[dialogue]]
speaker = "ソフィア"
# 「ルリもからかわないでください、もぅっ！！」
line = "「ルリもからかわないでください、もぅっ！！」"

[[dialogue]]
speaker = "マハムート"
# 「やれやれ、収拾がつかないわね……本当に。帰還するわよ！」
line = "「やれやれ、収拾がつかないわね……本当に。帰還するわよ！」"

[[dialogue]]
speaker = "unk"
# 『星喰らい』の拠点は、残すところあと２つ。
line = "『星喰らい』の拠点は、残すところあと２つ。"

[[dialogue]]
speaker = "unk"
# 創造神との戦いは、終幕へと近づきつつあった──
line = "創造神との戦いは、終幕へと近づきつつあった──"
