[[dialogue]]
speaker = "unk"
# 地下図書館の事件からしばらく経った、とある週末。
line = "地下図書館の事件からしばらく経った、とある週末。"

[[dialogue]]
speaker = "unk"
# 俺はソフレとフェリシーと一緒に、街へとやって来ていた。
line = "俺はソフレとフェリシーと一緒に、街へとやって来ていた。"

[[dialogue]]
speaker = "ソフレ"
# 「せっかくの休日なのに、こんなところに連れ出して、一体なんなのだわ……？」
line = "「せっかくの休日なのに、こんなところに連れ出して、一体なんなのだわ……？」"

[[dialogue]]
speaker = "ソフレ"
# 「しかも朝からなんて……ふわぁ～。ソフレはまだ、眠いのだわ……」
line = "「しかも朝からなんて……ふわぁ～。ソフレはまだ、眠いのだわ……」"

[[dialogue]]
speaker = "フェリシー"
# 「ほら、この間、一緒に卒業旅行へ行こうって約束したでしょ？」
line = "「ほら、この間、一緒に卒業旅行へ行こうって約束したでしょ？」"

[[dialogue]]
speaker = "フェリシー"
# 「その目標を現実にする為にも、形から入ろうと思って！　というわけで――」
line = "「その目標を現実にする為にも、形から入ろうと思って！　というわけで――」"

[[dialogue]]
speaker = "フェリシー"
# 「今日は東京で、ソフレの旅行バッグを選んで買っちゃおう！」
line = "「今日は東京で、ソフレの旅行バッグを選んで買っちゃおう！」"

[[dialogue]]
speaker = "ソフレ"
# 「いや、そもそも、ソフレはまだ、卒業旅行に行くと約束したわけじゃないのだわ！」
line = "「いや、そもそも、ソフレはまだ、卒業旅行に行くと約束したわけじゃないのだわ！」"

[[dialogue]]
speaker = "ソフレ"
# 「それに、どうして会長もここにいるわけ！？」
line = "「それに、どうして会長もここにいるわけ！？」"

[[dialogue]]
speaker = "フェリシー"
# 「この間の一件で、会長くんとも知り合えたわけだし、なんかこれから、３人でもっと仲よくなれそうな予感がしたんだよね！」
line = "「この間の一件で、会長くんとも知り合えたわけだし、なんかこれから、３人でもっと仲よくなれそうな予感がしたんだよね！」"

[[dialogue]]
speaker = "フェリシー"
# 「だから、もしよかったら一緒におでかけしないかって、誘ってみたの！」
line = "「だから、もしよかったら一緒におでかけしないかって、誘ってみたの！」"

[[dialogue]]
speaker = "unk"
# せっかく誘われたし、２人の邪魔でなければ
line = "せっかく誘われたし、２人の邪魔でなければ"

[[dialogue]]
speaker = "ソフレ"
# 「いや、邪魔されるほど、コイツとは仲よくないのだわ！」
line = "「いや、邪魔されるほど、コイツとは仲よくないのだわ！」"

[[dialogue]]
speaker = "ソフレ"
# 「というか、ソフレの旅行バッグ選びに付き合おうだなんて、会長も物好きなのよ……」
line = "「というか、ソフレの旅行バッグ選びに付き合おうだなんて、会長も物好きなのよ……」"

[[dialogue]]
speaker = "フェリシー"
# 「そうだ！　会長くんも私たちとは同学年なんだし、よかったら卒業旅行も一緒に行く？」
line = "「そうだ！　会長くんも私たちとは同学年なんだし、よかったら卒業旅行も一緒に行く？」"

[[dialogue]]
speaker = "unk"
# いいのか？
line = "いいのか？"

[[dialogue]]
speaker = "フェリシー"
# 「私は大歓迎だよ！　３人でって考えると、ますます楽しみになってきたかも！」
line = "「私は大歓迎だよ！　３人でって考えると、ますます楽しみになってきたかも！」"

[[dialogue]]
speaker = "フェリシー"
# 「――会長くんも海外に行く用の旅行バッグを持ってない？　なら今日、ソフレのと一緒に見繕っちゃおっか！」
line = "「――会長くんも海外に行く用の旅行バッグを持ってない？　なら今日、ソフレのと一緒に見繕っちゃおっか！」"

[[dialogue]]
speaker = "ソフレ"
# 「って、勝手に２人で盛り上がって、話を進めるんじゃないのだわ！」
line = "「って、勝手に２人で盛り上がって、話を進めるんじゃないのだわ！」"

[[dialogue]]
speaker = "ソフレ"
# 「――そうこうしている内に、気づけば本当に旅行バッグを買ってしまったのよ……」
line = "「――そうこうしている内に、気づけば本当に旅行バッグを買ってしまったのよ……」"

[[dialogue]]
speaker = "フェリシー"
# 「よかったね、ソフレ！　可愛いやつが見つかって♪」
line = "「よかったね、ソフレ！　可愛いやつが見つかって♪」"

[[dialogue]]
speaker = "ソフレ"
# 「……でも、ソフレの旅行バッグなのに、なんでお前がお金を出すのよ。しかも割と高かったし……」
line = "「……でも、ソフレの旅行バッグなのに、なんでお前がお金を出すのよ。しかも割と高かったし……」"

[[dialogue]]
speaker = "フェリシー"
# 「ん？　卒業旅行の言い出しっぺは私だし、あとは……ソフレの刑期が１００年短くなったお祝いの、プレゼント……みたいな？」
line = "「ん？　卒業旅行の言い出しっぺは私だし、あとは……ソフレの刑期が１００年短くなったお祝いの、プレゼント……みたいな？」"

[[dialogue]]
speaker = "ソフレ"
# 「なんなのよ、それ……」
line = "「なんなのよ、それ……」"

[[dialogue]]
speaker = "ソフレ"
# 「でも、まぁ……その……あり――」
line = "「でも、まぁ……その……あり――」"

[[dialogue]]
speaker = "フェリシー"
# 「あっ……そうだ！」
line = "「あっ……そうだ！」"

[[dialogue]]
speaker = "ソフレ"
# 「えっ？　な、なに？」
line = "「えっ？　な、なに？」"

[[dialogue]]
speaker = "フェリシー"
# 「ソフレと会長くんの旅行バッグを買った記念に、３人一緒に写真を撮ろうよ！」
line = "「ソフレと会長くんの旅行バッグを買った記念に、３人一緒に写真を撮ろうよ！」"

[[dialogue]]
speaker = "フェリシー"
# 「ＤＩＳＣのカメラを起動して……ほら、ソフレ、会長くん、こっちに寄って寄って～！」
line = "「ＤＩＳＣのカメラを起動して……ほら、ソフレ、会長くん、こっちに寄って寄って～！」"

[[dialogue]]
speaker = "ソフレ"
# 「ちょっ、いきなりくっ付くんじゃないのだわ！　お前はまた距離感が――」
line = "「ちょっ、いきなりくっ付くんじゃないのだわ！　お前はまた距離感が――」"

[[dialogue]]
speaker = "フェリシー"
# 「はい、チーズ♪」
line = "「はい、チーズ♪」"

[[dialogue]]
speaker = "フェリシー"
# 「――うん！　よく撮れてるよ！　ほら♪」
line = "「――うん！　よく撮れてるよ！　ほら♪」"

[[dialogue]]
speaker = "unk"
# フェリシーが見せたＤＩＳＣの画面には、３人の姿が収まっていて。
line = "フェリシーが見せたＤＩＳＣの画面には、３人の姿が収まっていて。"

[[dialogue]]
speaker = "ソフレ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ソフレ"
# 「って、ソフレの顔、変な表情で写ってるじゃない！　今のはナシ！　撮り直すのだわ！」
line = "「って、ソフレの顔、変な表情で写ってるじゃない！　今のはナシ！　撮り直すのだわ！」"

[[dialogue]]
speaker = "フェリシー"
# 「え～！　もったいない！　私はこれがいいよ～！」
line = "「え～！　もったいない！　私はこれがいいよ～！」"

[[dialogue]]
speaker = "unk"
# ソフレはその写真を見て、目の前のクラスメイトに容姿も笑い方もそっくりなアイツを思い出しながら、
line = "ソフレはその写真を見て、目の前のクラスメイトに容姿も笑い方もそっくりなアイツを思い出しながら、"

[[dialogue]]
speaker = "ソフレ"
# （まあ……本当にイタリアへ旅行に行けたら――）
line = "（まあ……本当にイタリアへ旅行に行けたら――）"

[[dialogue]]
speaker = "ソフレ"
# （その時は……墓参りくらいはしてやってもいいのだわ）
line = "（その時は……墓参りくらいはしてやってもいいのだわ）"

[[dialogue]]
speaker = "フェリーチェ"
# 「――な？　面白いこと、あっただろ？」
line = "「――な？　面白いこと、あっただろ？」"

[[dialogue]]
speaker = "unk"
# １００年越しに、ソフレはそんな懐かしい声を聞いた気がしたのだった――
line = "１００年越しに、ソフレはそんな懐かしい声を聞いた気がしたのだった――"
