[[dialogue]]
speaker = "マグダレナ"
# 「健勝そうですね、アルモタヘル」
line = "「健勝そうですね、アルモタヘル」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ああ、お前もな」
line = "「ああ、お前もな」"

[[dialogue]]
speaker = "アルモタヘル"
# 「まさかこんな形でお前と見えることになるとは思わなかったがな。不思議なものだ」
line = "「まさかこんな形でお前と見えることになるとは思わなかったがな。不思議なものだ」"

[[dialogue]]
speaker = "マグダレナ"
# 「私たちが人間界にいること、そして肉体を持っていることがそもそもありえない事態ですからね」
line = "「私たちが人間界にいること、そして肉体を持っていることがそもそもありえない事態ですからね」"

[[dialogue]]
speaker = "unk"
# 守護天使とは本来世界の摂理を司る者であり、フィーニスの塔の守護者でもある。
line = "守護天使とは本来世界の摂理を司る者であり、フィーニスの塔の守護者でもある。"

[[dialogue]]
speaker = "unk"
# しかし本体は魔界のどこかに封印され、リクリエの浸食によって堕天使となっていた。
line = "しかし本体は魔界のどこかに封印され、リクリエの浸食によって堕天使となっていた。"

[[dialogue]]
speaker = "unk"
# 敵となった守護天使は流星・新星の星徒会によって倒されたが──
line = "敵となった守護天使は流星・新星の星徒会によって倒されたが──"

[[dialogue]]
speaker = "unk"
# 魂の一端をサルベージし、新星学園の錬金術師・アニマが作った義体に宿すことによって受肉。
line = "魂の一端をサルベージし、新星学園の錬金術師・アニマが作った義体に宿すことによって受肉。"

[[dialogue]]
speaker = "unk"
# まだ守護天使の本体を解放することは叶わないものの、仮初の肉体で活動することが可能になったのだった。
line = "まだ守護天使の本体を解放することは叶わないものの、仮初の肉体で活動することが可能になったのだった。"

[[dialogue]]
speaker = "マグダレナ"
# 「これもアニマさまのおかげですね。あの方の錬金術は驚嘆に値します」
line = "「これもアニマさまのおかげですね。あの方の錬金術は驚嘆に値します」"

[[dialogue]]
speaker = "マグダレナ"
# 「それに教皇庁の方々にもよくしていただいています。この前は──」
line = "「それに教皇庁の方々にもよくしていただいています。この前は──」"

[[dialogue]]
speaker = "マグダレナ"
# 「シャロンさまとイレーナさまに付き添いいただきまして、映画というものを見て参りました」
line = "「シャロンさまとイレーナさまに付き添いいただきまして、映画というものを見て参りました」"

[[dialogue]]
speaker = "マグダレナ"
# 「大きなスクリーンで見る映像は本当に美麗で、音も前後左右から聞こえてきて臨場感がありました」
line = "「大きなスクリーンで見る映像は本当に美麗で、音も前後左右から聞こえてきて臨場感がありました」"

[[dialogue]]
speaker = "マグダレナ"
# 「しかも！　映画の中の衝撃を再現するように座席が揺れるのです！」
line = "「しかも！　映画の中の衝撃を再現するように座席が揺れるのです！」"

[[dialogue]]
speaker = "マグダレナ"
# 「恥ずかしながら最初は驚いてしまいましたが、まるで映画の世界に入ったようでした」
line = "「恥ずかしながら最初は驚いてしまいましたが、まるで映画の世界に入ったようでした」"

[[dialogue]]
speaker = "マグダレナ"
# 「シャロンさまも同様に驚いておられましたね。ふふふ」
line = "「シャロンさまも同様に驚いておられましたね。ふふふ」"

[[dialogue]]
speaker = "マグダレナ"
# 「それにですね、最近はドラマというものもよく見ていまして」
line = "「それにですね、最近はドラマというものもよく見ていまして」"

[[dialogue]]
speaker = "マグダレナ"
# 「愛憎渦巻く複雑な人間模様が見事に描写されていて、道徳に反するとわかっていても目が離せなくなるのです」
line = "「愛憎渦巻く複雑な人間模様が見事に描写されていて、道徳に反するとわかっていても目が離せなくなるのです」"

[[dialogue]]
speaker = "マグダレナ"
# 「異国のドラマも大変興味深く、いろんな作品が気になってしまって……」
line = "「異国のドラマも大変興味深く、いろんな作品が気になってしまって……」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ふ、なるほど。この世界の娯楽にうつつを抜かしているというわけか」
line = "「ふ、なるほど。この世界の娯楽にうつつを抜かしているというわけか」"

[[dialogue]]
speaker = "マグダレナ"
# 「む。そう言うアルモタヘルはどうなのですか？」
line = "「む。そう言うアルモタヘルはどうなのですか？」"

[[dialogue]]
speaker = "アルモタヘル"
# 「我か？　そうだな……」
line = "「我か？　そうだな……」"

[[dialogue]]
speaker = "アルモタヘル"
# 「せっかく肉体を得たのだから、肉体がなければできない経験をせねばな」
line = "「せっかく肉体を得たのだから、肉体がなければできない経験をせねばな」"

[[dialogue]]
speaker = "アルモタヘル"
# 「故に我はこの世界の食を探求している。ヒトが発展させた世界には美味な食物が溢れているからな」
line = "「故に我はこの世界の食を探求している。ヒトが発展させた世界には美味な食物が溢れているからな」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ハンバーグ、すき焼き、小籠包……美味い料理は枚挙に暇がない」
line = "「ハンバーグ、すき焼き、小籠包……美味い料理は枚挙に暇がない」"

[[dialogue]]
speaker = "アルモタヘル"
# 「蛍火には世話になっている。やつの肉料理は最高だ」
line = "「蛍火には世話になっている。やつの肉料理は最高だ」"

[[dialogue]]
speaker = "アルモタヘル"
# 「もぐもぐ……特にケバブは良い。肉と野菜、ピタのバランスは筆舌に尽くしがたい……もぐもぐ、もぐもぐ……」
line = "「もぐもぐ……特にケバブは良い。肉と野菜、ピタのバランスは筆舌に尽くしがたい……もぐもぐ、もぐもぐ……」"

[[dialogue]]
speaker = "マグダレナ"
# 「食べながら話すのはやめなさい、アルモタヘル。ここは女神様の聖堂ですよ」
line = "「食べながら話すのはやめなさい、アルモタヘル。ここは女神様の聖堂ですよ」"

[[dialogue]]
speaker = "マグダレナ"
# 「もう。アルモタヘルもこの世界の文化に骨抜きではないですか」
line = "「もう。アルモタヘルもこの世界の文化に骨抜きではないですか」"

[[dialogue]]
speaker = "マグダレナ"
# 「他の守護天使たちはどうしているのでしょうか。リクリエを阻止するためにいずれ力を合わせたいのですが」
line = "「他の守護天使たちはどうしているのでしょうか。リクリエを阻止するためにいずれ力を合わせたいのですが」"

[[dialogue]]
speaker = "アルモタヘル"
# 「我々と同じように囚われていると見るのが妥当だろう。力ずくでも目を覚まさせてやらねばな」
line = "「我々と同じように囚われていると見るのが妥当だろう。力ずくでも目を覚まさせてやらねばな」"

[[dialogue]]
speaker = "アルモタヘル"
# 「さて、我はこれから流星市国周辺のケバブ店を回るつもりだ。店によって肉の種類や味付けも違うからな。至高の一品を見つけるとしよう。お前は？」
line = "「さて、我はこれから流星市国周辺のケバブ店を回るつもりだ。店によって肉の種類や味付けも違うからな。至高の一品を見つけるとしよう。お前は？」"

[[dialogue]]
speaker = "マグダレナ"
# 「私はドラマの新しいシリーズを見始めようかと」
line = "「私はドラマの新しいシリーズを見始めようかと」"

[[dialogue]]
speaker = "マグダレナ"
# 「リアルタイムで事件が進行するという作品で、一度見たら止まらないと聞いて少し恐れていたのですが、そろそろ挑戦してみようと思っています」
line = "「リアルタイムで事件が進行するという作品で、一度見たら止まらないと聞いて少し恐れていたのですが、そろそろ挑戦してみようと思っています」"

[[dialogue]]
speaker = "アルモタヘル"
# 「ふむ。まるでケバブだな」
line = "「ふむ。まるでケバブだな」"

[[dialogue]]
speaker = "マグダレナ"
# 「いい加減ケバブから離れなさい」
line = "「いい加減ケバブから離れなさい」"

[[dialogue]]
speaker = "マグダレナ"
# 「面白ければあなたにも感想を伝えましょう。きっとアルモタヘルも楽しめる──」
line = "「面白ければあなたにも感想を伝えましょう。きっとアルモタヘルも楽しめる──」"

[[dialogue]]
speaker = "マグダレナ"
# 「ハッ！？」
line = "「ハッ！？」"

[[dialogue]]
speaker = "アルモタヘル"
# 「どうした？　お前もケバブ巡りに参加したいのか？」
line = "「どうした？　お前もケバブ巡りに参加したいのか？」"

[[dialogue]]
speaker = "マグダレナ"
# 「いいですか。今の我々の生活は、教皇庁の方々の援助によって成り立っています」
line = "「いいですか。今の我々の生活は、教皇庁の方々の援助によって成り立っています」"

[[dialogue]]
speaker = "マグダレナ"
# 「しかし我々は日々ドラマを視聴したり、食べ歩きをしたり、ただただ享楽に耽るばかり」
line = "「しかし我々は日々ドラマを視聴したり、食べ歩きをしたり、ただただ享楽に耽るばかり」"

[[dialogue]]
speaker = "マグダレナ"
# 「つまり我々のような者を──穀潰しというのでは？」
line = "「つまり我々のような者を──穀潰しというのでは？」"

[[dialogue]]
speaker = "アルモタヘル"
# 「──」
line = "「──」"
