[[dialogue]]
speaker = "デネブ・カイトス"
# 「グオオオオオオォォーー！！！」
line = "「グオオオオオオォォーー！！！」"

[[dialogue]]
speaker = "アポロ"
# 「なんだコイツっ！？　さっきのがボスモンスターじゃなかったのかっ！？」
line = "「なんだコイツっ！？　さっきのがボスモンスターじゃなかったのかっ！？」"

[[dialogue]]
speaker = "ナターシャ"
# 「どうやらこっちが真のボスモンスターらしいね……」
line = "「どうやらこっちが真のボスモンスターらしいね……」"

[[dialogue]]
speaker = "ベアトリス"
# 「そ、そんな……もうみんな、ヘトヘトなのに……！」
line = "「そ、そんな……もうみんな、ヘトヘトなのに……！」"

[[dialogue]]
speaker = "ナターシャ"
# 「しかもコイツ、さっきのより一回りは強いよ。やっぱり難易度調整バグってるって……」
line = "「しかもコイツ、さっきのより一回りは強いよ。やっぱり難易度調整バグってるって……」"

[[dialogue]]
speaker = "梨緒"
# 「くっ……！」
line = "「くっ……！」"

[[dialogue]]
speaker = "梨緒"
# （どうする？　戦うか？　退くか？）
line = "（どうする？　戦うか？　退くか？）"

[[dialogue]]
speaker = "梨緒"
# （みんな先程の戦闘で疲弊しきってる。今戦っても勝ち目は……）
line = "（みんな先程の戦闘で疲弊しきってる。今戦っても勝ち目は……）"

[[dialogue]]
speaker = "梨緒"
# （しかし退いたところで明日になれば強化が入る。そうなれば、どちらにしても……）
line = "（しかし退いたところで明日になれば強化が入る。そうなれば、どちらにしても……）"

[[dialogue]]
speaker = "デネブ・カイトス"
# 「グオオッ、オオオオォォーー！！！」
line = "「グオオッ、オオオオォォーー！！！」"

[[dialogue]]
speaker = "ベアトリス"
# 「きゃあっ！？」
line = "「きゃあっ！？」"

[[dialogue]]
speaker = "梨緒"
# 「ベアトっ！？」
line = "「ベアトっ！？」"

[[dialogue]]
speaker = "ベアトリス"
# 「だ、大丈夫っ。なんとか避けられたから」
line = "「だ、大丈夫っ。なんとか避けられたから」"

[[dialogue]]
speaker = "アポロ"
# 「あっぶねえ。一撃でも貰ったらヤバそうだな……！」
line = "「あっぶねえ。一撃でも貰ったらヤバそうだな……！」"

[[dialogue]]
speaker = "梨緒"
# （迷ってる暇はない。戦うか、退くか。早く決めなければ、勝機はない……！）
line = "（迷ってる暇はない。戦うか、退くか。早く決めなければ、勝機はない……！）"

[[dialogue]]
speaker = "梨緒"
# （いや、それとも──……）
line = "（いや、それとも──……）"

[[dialogue]]
speaker = "ナターシャ"
# 「ここまでやれたんだし……別に負けても良くない？」
line = "「ここまでやれたんだし……別に負けても良くない？」"

[[dialogue]]
speaker = "アポロ"
# 「はぁ！？　なに気の抜けたこと言ってんだっ、ナターシャ！」
line = "「はぁ！？　なに気の抜けたこと言ってんだっ、ナターシャ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「や、だってこれは向こうの調整ミスでしょ。クリアできるように作られてないよ、これ」
line = "「や、だってこれは向こうの調整ミスでしょ。クリアできるように作られてないよ、これ」"

[[dialogue]]
speaker = "ナターシャ"
# 「私たちはそういう確認をするためのテスターなわけじゃない？　無理に粘って痛い思いする必要はなくない？」
line = "「私たちはそういう確認をするためのテスターなわけじゃない？　無理に粘って痛い思いする必要はなくない？」"

[[dialogue]]
speaker = "アポロ"
# 「そ、それは……！」
line = "「そ、それは……！」"

[[dialogue]]
speaker = "ベアトリス"
# 「確かにナターシャちゃんの言う通りかも……。もう十分満足なくらい、みんなと楽しい時間も過ごせたし……」
line = "「確かにナターシャちゃんの言う通りかも……。もう十分満足なくらい、みんなと楽しい時間も過ごせたし……」"

[[dialogue]]
speaker = "アポロ"
# 「ベアトまでっ！？」
line = "「ベアトまでっ！？」"

[[dialogue]]
speaker = "アポロ"
# 「どうするんだ、梨緒っ。まさかオマエまで負けていいとか言わねえだろうなっ？」
line = "「どうするんだ、梨緒っ。まさかオマエまで負けていいとか言わねえだろうなっ？」"

[[dialogue]]
speaker = "梨緒"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "アポロ"
# 「おい、聞いてんのか、梨緒っ！」
line = "「おい、聞いてんのか、梨緒っ！」"

[[dialogue]]
speaker = "梨緒"
# 「……ナターシャとベアトの言うことももっともだ。私たちはあくまでテスターだ。無理に粘って勝利を目指す必要はないだろう」
line = "「……ナターシャとベアトの言うことももっともだ。私たちはあくまでテスターだ。無理に粘って勝利を目指す必要はないだろう」"

[[dialogue]]
speaker = "梨緒"
# 「リップルに素直な報告をすればいいだけだ。『流石にこの仕様は難易度が高すぎる。誰もクリアできない』と」
line = "「リップルに素直な報告をすればいいだけだ。『流石にこの仕様は難易度が高すぎる。誰もクリアできない』と」"

[[dialogue]]
speaker = "梨緒"
# 「だけど……でも──」
line = "「だけど……でも──」"

[[dialogue]]
speaker = "梨緒"
# 「私は最後の最後まで諦めたくない！　たとえ負け戦だろうと、最後まで足掻きたいっ！」
line = "「私は最後の最後まで諦めたくない！　たとえ負け戦だろうと、最後まで足掻きたいっ！」"

[[dialogue]]
speaker = "梨緒"
# 「いいや、勝ちたいんだっ。テストだとか、星徒会がクリアできなかったからとか関係なく、ただ、選管の仲間で力を合わせて……！」
line = "「いいや、勝ちたいんだっ。テストだとか、星徒会がクリアできなかったからとか関係なく、ただ、選管の仲間で力を合わせて……！」"

[[dialogue]]
speaker = "アポロ"
# 「梨緒……」
line = "「梨緒……」"

[[dialogue]]
speaker = "ベアトリス"
# 「梨緒ちゃん……」
line = "「梨緒ちゃん……」"

[[dialogue]]
speaker = "ナターシャ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "梨緒"
# 「勝とう、みんな！」
line = "「勝とう、みんな！」"

[[dialogue]]
speaker = "梨緒"
# 「私は信じているっ！　たとえ圧倒的な戦力差があろうと、選管のみんなで力を合わせればそれを覆せると！」
line = "「私は信じているっ！　たとえ圧倒的な戦力差があろうと、選管のみんなで力を合わせればそれを覆せると！」"

[[dialogue]]
speaker = "ナターシャ"
# 「まったく……うちの委員長は熱血なんだから」
line = "「まったく……うちの委員長は熱血なんだから」"

[[dialogue]]
speaker = "ナターシャ"
# 「仕方ないね。私だって何も進んで負けたいわけじゃないし」
line = "「仕方ないね。私だって何も進んで負けたいわけじゃないし」"

[[dialogue]]
speaker = "ベアトリス"
# 「勝って終わらせた方がいい思い出にもなるもんねっ」
line = "「勝って終わらせた方がいい思い出にもなるもんねっ」"

[[dialogue]]
speaker = "アポロ"
# 「絶望的な状況を引っ繰り返してこそ、ヒーローってもんだ！」
line = "「絶望的な状況を引っ繰り返してこそ、ヒーローってもんだ！」"

[[dialogue]]
speaker = "梨緒"
# 「みんな……」
line = "「みんな……」"

[[dialogue]]
speaker = "ナターシャ"
# 「指示をお願い、梨緒。勝つための指示を」
line = "「指示をお願い、梨緒。勝つための指示を」"

[[dialogue]]
speaker = "ベアトリス"
# 「私だって信じてるからっ。みんなで戦えば、どんなことだって乗り越えられるってっ」
line = "「私だって信じてるからっ。みんなで戦えば、どんなことだって乗り越えられるってっ」"

[[dialogue]]
speaker = "アポロ"
# 「１人で気張り過ぎんなよ、梨緒っ。あたしたちがついてんだからなっ」
line = "「１人で気張り過ぎんなよ、梨緒っ。あたしたちがついてんだからなっ」"

[[dialogue]]
speaker = "梨緒"
# 「っ……！！」
line = "「っ……！！」"

[[dialogue]]
speaker = "梨緒"
# 「よし、みんなで勝つぞ！　選挙管理委員の仲間でだっ！！」
line = "「よし、みんなで勝つぞ！　選挙管理委員の仲間でだっ！！」"

[[dialogue]]
speaker = "４人"
# 「絶対勝つっ！！」
line = "「絶対勝つっ！！」"

[[dialogue]]
speaker = "デネブ・カイトス"
# 「グオオオオオオォォーーーーッッ！！！」
line = "「グオオオオオオォォーーーーッッ！！！」"
