[[dialogue]]
speaker = "カヤ"
# 「ん。ズヴィエダ地方、レゾフに到着。守護天使が封印された神殿があるのは、冥森林ネメシスとは反対の方向」
line = "「ん。ズヴィエダ地方、レゾフに到着。守護天使が封印された神殿があるのは、冥森林ネメシスとは反対の方向」"

[[dialogue]]
speaker = "ソフィア"
# 「こんな短期間にまたレゾフに帰ってくるとは思いませんでした。少なくとも流星学園を卒業するまでは、戻ることはないと思っていたんですが」
line = "「こんな短期間にまたレゾフに帰ってくるとは思いませんでした。少なくとも流星学園を卒業するまでは、戻ることはないと思っていたんですが」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふ。そう思っていると、案外帰る機会が来るものよ」
line = "「ふふ。そう思っていると、案外帰る機会が来るものよ」"

[[dialogue]]
speaker = "舞亜"
# 「へぇ～、ここがソフィの故郷かぁ～。確かに寒い……っていうかメチャ寒いね。。リンクの上は慣れてるのに凍えそうだよ」
line = "「へぇ～、ここがソフィの故郷かぁ～。確かに寒い……っていうかメチャ寒いね。。リンクの上は慣れてるのに凍えそうだよ」"

[[dialogue]]
speaker = "ソフィア"
# 「舞亜さん！？　来てたんですか！？」
line = "「舞亜さん！？　来てたんですか！？」"

[[dialogue]]
speaker = "ウズメイア"
# 「あたしもいるよー！」
line = "「あたしもいるよー！」"

[[dialogue]]
speaker = "ソフィア"
# 「ウズメも！？」
line = "「ウズメも！？」"

[[dialogue]]
speaker = "舞亜"
# 「ふふ。友達のおうちにお邪魔するこの日のためにプリマステラになったと言っても過言じゃないね」
line = "「ふふ。友達のおうちにお邪魔するこの日のためにプリマステラになったと言っても過言じゃないね」"

[[dialogue]]
speaker = "ソフィア"
# 「舞亜さんの素質は図抜けたものがありましたが、プリマステラになっていたんですね」
line = "「舞亜さんの素質は図抜けたものがありましたが、プリマステラになっていたんですね」"

[[dialogue]]
speaker = "舞亜"
# 「私が育てましたって顔していいよ。ソフィがメダル取ったら私もドヤ顔するから」
line = "「私が育てましたって顔していいよ。ソフィがメダル取ったら私もドヤ顔するから」"

[[dialogue]]
speaker = "ソフィア"
# 「しませんし、私がメダル取ってもドヤ顔しないでくださいね」
line = "「しませんし、私がメダル取ってもドヤ顔しないでくださいね」"

[[dialogue]]
speaker = "ウズメイア"
# 「あははっ、ソフィってばクールなんだから」
line = "「あははっ、ソフィってばクールなんだから」"

[[dialogue]]
speaker = "ラティエ"
# 「ちなみに私も同行させてもらうよ」
line = "「ちなみに私も同行させてもらうよ」"

[[dialogue]]
speaker = "ソフィア"
# 「ラティエ学園長も？　もしかして以前レゾフに来ていたのは、この事態を予想して……？」
line = "「ラティエ学園長も？　もしかして以前レゾフに来ていたのは、この事態を予想して……？」"

[[dialogue]]
speaker = "ラティエ"
# 「いや、ただの偶然だ」
line = "「いや、ただの偶然だ」"

[[dialogue]]
speaker = "ソフィア"
# 「ですよね……」
line = "「ですよね……」"

[[dialogue]]
speaker = "カヤ"
# 「神殿へ移動する。変身してついてきて」
line = "「神殿へ移動する。変身してついてきて」"

[[dialogue]]
speaker = "カヤ"
# 「着いた。このまま《試練》のパテルのところまで先導する」
line = "「着いた。このまま《試練》のパテルのところまで先導する」"

[[dialogue]]
speaker = "サーシャ"
# 「あれが守護天使が封印されてる神殿ね～。考古学的にも価値がありそうだわ～」
line = "「あれが守護天使が封印されてる神殿ね～。考古学的にも価値がありそうだわ～」"

[[dialogue]]
speaker = "ウズメイア"
# 「よーし、このまま守護天使のところまで一直線──」
line = "「よーし、このまま守護天使のところまで一直線──」"

[[dialogue]]
speaker = "ウズメイア"
# 「！？　モンスター！？」
line = "「！？　モンスター！？」"

[[dialogue]]
speaker = "イレーナ"
# 「させません──プリガーレ・アンドロメダ！」
line = "「させません──プリガーレ・アンドロメダ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「イレーナ先輩！　バリアありがとうございました！」
line = "「イレーナ先輩！　バリアありがとうございました！」"

[[dialogue]]
speaker = "イレーナ"
# 「いいえ、聖女と呼ばれる者として当然の務めです」
line = "「いいえ、聖女と呼ばれる者として当然の務めです」"

[[dialogue]]
speaker = "イレーナ"
# （聖女になったかと思えば、魔界にも出張る羽目になっちゃって……どうしてこうなったんだか）
line = "（聖女になったかと思えば、魔界にも出張る羽目になっちゃって……どうしてこうなったんだか）"

[[dialogue]]
speaker = "ウズメイア"
# 「イレーナ先輩？」
line = "「イレーナ先輩？」"

[[dialogue]]
speaker = "イレーナ"
# 「コホン。後方支援なら任せてください。傷ついた方は回復いたします」
line = "「コホン。後方支援なら任せてください。傷ついた方は回復いたします」"

[[dialogue]]
speaker = "ウズメイア"
# 「はい、頼りにしてます！」
line = "「はい、頼りにしてます！」"

[[dialogue]]
speaker = "舞亜"
# 「モンスターがたくさん……リクリエってやっつけたんじゃなかったっけ？　流星市国よりいっぱいいる気がするんだけど」
line = "「モンスターがたくさん……リクリエってやっつけたんじゃなかったっけ？　流星市国よりいっぱいいる気がするんだけど」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「リクリエはこの機に便乗して世界を滅ぼす気なのだ。この前止められたところなのに、往生際が悪いのだ！」
line = "「リクリエはこの機に便乗して世界を滅ぼす気なのだ。この前止められたところなのに、往生際が悪いのだ！」"

[[dialogue]]
speaker = "舞亜"
# 「あれ？　アルモタヘルさん、ちっちゃくなってる？」
line = "「あれ？　アルモタヘルさん、ちっちゃくなってる？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「星騎士のみんなが戦っているのに、待っているだけはイヤなのだ。アルモたんも戦うのだ！」
line = "「星騎士のみんなが戦っているのに、待っているだけはイヤなのだ。アルモたんも戦うのだ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「でも本体に引っ張られてまた堕天使に堕ちるとよくないから、違う場所に来ているのだ。ちっちゃいのも、本来の姿から離れて少しでも堕天しにくくするためなのだ！」
line = "「でも本体に引っ張られてまた堕天使に堕ちるとよくないから、違う場所に来ているのだ。ちっちゃいのも、本来の姿から離れて少しでも堕天しにくくするためなのだ！」"

[[dialogue]]
speaker = "舞亜"
# 「へ～、なるほど～」
line = "「へ～、なるほど～」"

[[dialogue]]
speaker = "ソフィア"
# 「今の説明、わかってます？」
line = "「今の説明、わかってます？」"

[[dialogue]]
speaker = "舞亜"
# 「半分くらいは」
line = "「半分くらいは」"

[[dialogue]]
speaker = "ソフィア"
# 「やっぱり……」
line = "「やっぱり……」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「あははっ、とにかくアルモたんたちも一緒に戦うのだ！　みんなで世界を守るのだ！」
line = "「あははっ、とにかくアルモたんたちも一緒に戦うのだ！　みんなで世界を守るのだ！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「倒しても倒してもモンスターが湧いてきますわ。このままでは<ruby=らち>埒</ruby>が明きませんわね。部隊を分けましょう」
line = "「倒しても倒してもモンスターが湧いてきますわ。このままでは<ruby>埒<rt>らち</rt></ruby>が明きませんわね。部隊を分けましょう」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「星徒会メンバーおよび機動力の高い星騎士は、神殿中心部へ向かって守護天使を解放してください」
line = "「星徒会メンバーおよび機動力の高い星騎士は、神殿中心部へ向かって守護天使を解放してください」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「エリスさんとアニュラスさんは後方から押し寄せるモンスターの迎撃を。その他の者は、<ruby=わたくし>私</ruby>とともに前方のモンスターを蹴散らして道を切り拓きます！」
line = "「エリスさんとアニュラスさんは後方から押し寄せるモンスターの迎撃を。その他の者は、<ruby>私<rt>わたくし</rt></ruby>とともに前方のモンスターを蹴散らして道を切り拓きます！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ダメージを受けた人は即座にイレーナさんの治療を受けてくださいな！　全員生きて帰りますわよ！」
line = "「ダメージを受けた人は即座にイレーナさんの治療を受けてくださいな！　全員生きて帰りますわよ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「はい！　見たいアニメもまだまだたくさんあるしね！」
line = "「はい！　見たいアニメもまだまだたくさんあるしね！」"

[[dialogue]]
speaker = "ラティエ"
# 「ブリガンデ・テンペスタ！」
line = "「ブリガンデ・テンペスタ！」"

[[dialogue]]
speaker = "ソフィア"
# 「大型モンスターをああも容易く……さすがは学園長ですね」
line = "「大型モンスターをああも容易く……さすがは学園長ですね」"

[[dialogue]]
speaker = "ラティエ"
# 「未来を切り開くのは若者に任せよう。行きたまえ」
line = "「未来を切り開くのは若者に任せよう。行きたまえ」"

[[dialogue]]
speaker = "サーシャ"
# 「は～い。飛ばすわよ～！」
line = "「は～い。飛ばすわよ～！」"

[[dialogue]]
speaker = "ソフィア"
# 「最大戦速で突破します！」
line = "「最大戦速で突破します！」"

[[dialogue]]
speaker = "パテル"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "カヤ"
# 「標的を発見──速やかに撃破する」
line = "「標的を発見──速やかに撃破する」"

[[dialogue]]
speaker = "舞亜"
# 「私、この戦いが終わったら金メダル取るんだ」
line = "「私、この戦いが終わったら金メダル取るんだ」"

[[dialogue]]
speaker = "ウズメイア"
# 「ダメ～っ、それ死亡フラグ！？」
line = "「ダメ～っ、それ死亡フラグ！？」"

[[dialogue]]
speaker = "ソフィア"
# 「だいたい、金メダルならいつも取ってるじゃないですか。ふざけてないで戦いますよ」
line = "「だいたい、金メダルならいつも取ってるじゃないですか。ふざけてないで戦いますよ」"

[[dialogue]]
speaker = "サーシャ"
# 「今度こそ大鎌対決ね～。死神の異名、もらっちゃおうかしら？」
line = "「今度こそ大鎌対決ね～。死神の異名、もらっちゃおうかしら？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「鎌ならアルモたんも負けないのだ！」
line = "「鎌ならアルモたんも負けないのだ！」"

[[dialogue]]
speaker = "パテル"
# 「試練など不要。死あるのみだ」
line = "「試練など不要。死あるのみだ」"

[[dialogue]]
speaker = "ソフィア"
# 「生き残るためなら──試練でも死神でも乗り越えてみせます！」
line = "「生き残るためなら──試練でも死神でも乗り越えてみせます！」"
