[[dialogue]]
speaker = "ミルフィー"
# 「これで決める！　イノセントノヴァ！」
line = "「これで決める！　イノセントノヴァ！」"

[[dialogue]]
speaker = "マグダレナ"
# 「──ッ！？」
line = "「──ッ！？」"

[[dialogue]]
speaker = "ミルフィー"
# 「やったの……！？」
line = "「やったの……！？」"

[[dialogue]]
speaker = "コハルコ"
# 『堕天使マグダレナの霊力反応減少──いえ、この反応は！？　ミルフィーさん、逃げて！』
line = "『堕天使マグダレナの霊力反応減少──いえ、この反応は！？　ミルフィーさん、逃げて！』"

[[dialogue]]
speaker = "ミルフィー"
# 「え──」
line = "「え──」"

[[dialogue]]
speaker = "マグダレナ"
# 「ケイオス・コンセントレーション──」
line = "「ケイオス・コンセントレーション──」"

[[dialogue]]
speaker = "ミルフィー"
# 「きゃああああっ！？」
line = "「きゃああああっ！？」"

[[dialogue]]
speaker = "unk"
# ミルフィー！？
line = "ミルフィー！？"

[[dialogue]]
speaker = "マグダレナ"
# 「ああ……世界はどうして分かたれているのでしょう……」
line = "「ああ……世界はどうして分かたれているのでしょう……」"

[[dialogue]]
speaker = "コハルコ"
# 『堕天使マグダレナの霊力、反転して増大……接敵時の値を超えてさらに上昇……！　霊力が２倍……３倍！？』
line = "『堕天使マグダレナの霊力、反転して増大……接敵時の値を超えてさらに上昇……！　霊力が２倍……３倍！？』"

[[dialogue]]
speaker = "ヴィーナス"
# 「３倍！？　いくらなんでも盛り過ぎでしょ！？」
line = "「３倍！？　いくらなんでも盛り過ぎでしょ！？」"

[[dialogue]]
speaker = "マグダレナ"
# 「新たな世界を始めましょう……」
line = "「新たな世界を始めましょう……」"

[[dialogue]]
speaker = "マグダレナ"
# 「世界をひとつに……混沌と終焉を……」
line = "「世界をひとつに……混沌と終焉を……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「！　これが堕天使マグダレナの本気ってワケね……！」
line = "「！　これが堕天使マグダレナの本気ってワケね……！」"

[[dialogue]]
speaker = "コハルコ"
# 『それにこの反応は……！？　魔界中のモンスターが堕天使マグダレナの神殿に集まろうとしています！』
line = "『それにこの反応は……！？　魔界中のモンスターが堕天使マグダレナの神殿に集まろうとしています！』"

[[dialogue]]
speaker = "イニシュ"
# 「──っ」
line = "「──っ」"

[[dialogue]]
speaker = "フィオナ"
# 「イニシュさん、大丈夫ですか！？」
line = "「イニシュさん、大丈夫ですか！？」"

[[dialogue]]
speaker = "イニシュ"
# 「ダメージは軽微。戦闘継続に支障はありません。ですが──」
line = "「ダメージは軽微。戦闘継続に支障はありません。ですが──」"

[[dialogue]]
speaker = "フィオナ"
# 「これは……まずいですね……」
line = "「これは……まずいですね……」"

[[dialogue]]
speaker = "マグダレナ"
# 「世界をひとつに……混沌と終焉を……」
line = "「世界をひとつに……混沌と終焉を……」"

[[dialogue]]
speaker = "ミルフィー"
# 「私……結局何もできなかった……ごめんなさい、マグダレナ様……」
line = "「私……結局何もできなかった……ごめんなさい、マグダレナ様……」"

[[dialogue]]
speaker = "ミルフィー"
# 「帰れなくてごめん、ヒヨちゃん……」
line = "「帰れなくてごめん、ヒヨちゃん……」"
