[[dialogue]]
speaker = "unk"
# サチに起きた異変を確かめる為、俺たちは放課後にトレーニング施設へとやってきていた。
line = "サチに起きた異変を確かめる為、俺たちは放課後にトレーニング施設へとやってきていた。"

[[dialogue]]
speaker = "サチ"
# 「……やっぱり、気のせいじゃない。私、幸運の力が使えなくなってるみたいです」
line = "「……やっぱり、気のせいじゃない。私、幸運の力が使えなくなってるみたいです」"

[[dialogue]]
speaker = "unk"
# サチの仮想戦闘訓練の結果は、以前に比べて評価がガクンと落ちてしまっていた。
line = "サチの仮想戦闘訓練の結果は、以前に比べて評価がガクンと落ちてしまっていた。"

[[dialogue]]
speaker = "プリムラ"
# 「サチ……」
line = "「サチ……」"

[[dialogue]]
speaker = "トレジアンナ"
# 「サチさんの訓練の様子を、解析魔法で確認したんですが……」
line = "「サチさんの訓練の様子を、解析魔法で確認したんですが……」"

[[dialogue]]
speaker = "トレジアンナ"
# 「どうやらサチさんの『幸運』は、ディーラックさんに奪われた可能性が高いですね。マイナスエネルギーの痕跡らしきものが見えました」
line = "「どうやらサチさんの『幸運』は、ディーラックさんに奪われた可能性が高いですね。マイナスエネルギーの痕跡らしきものが見えました」"

[[dialogue]]
speaker = "シズハ"
# 「ディーちゃんが……？」
line = "「ディーちゃんが……？」"

[[dialogue]]
speaker = "トマル"
# 「あっ……まさかこの前の戦闘で、サチさまがディーラックさまからタックルを受けた時に……！？」
line = "「あっ……まさかこの前の戦闘で、サチさまがディーラックさまからタックルを受けた時に……！？」"

[[dialogue]]
speaker = "トレジアンナ"
# 「おそらくは。幸運の力を取り戻す１番手っ取り早い方法は、ディーラックさんに勝って返してもらうことでしょう」
line = "「おそらくは。幸運の力を取り戻す１番手っ取り早い方法は、ディーラックさんに勝って返してもらうことでしょう」"

[[dialogue]]
speaker = "サチ"
# 「つまり、それまでは純粋に星力だけで戦うしかないってことですね……」
line = "「つまり、それまでは純粋に星力だけで戦うしかないってことですね……」"

[[dialogue]]
speaker = "unk"
# 訓練が終わった後、俺はトレジアンナさんにサチを家まで送って欲しいと言われて、一緒に帰ることになった。
line = "訓練が終わった後、俺はトレジアンナさんにサチを家まで送って欲しいと言われて、一緒に帰ることになった。"

[[dialogue]]
speaker = "サチ"
# 「もう、トレジアンナさんってば、変な気を利かせたりして……すみません、お兄さん」
line = "「もう、トレジアンナさんってば、変な気を利かせたりして……すみません、お兄さん」"

[[dialogue]]
speaker = "unk"
# 俺は、構わないと首を横に振ってから――
line = "俺は、構わないと首を横に振ってから――"

[[dialogue]]
speaker = "unk"
# サチ、ショックじゃないか？
line = "サチ、ショックじゃないか？"

[[dialogue]]
speaker = "サチ"
# 「え？　それって……幸運の力が無くなっちゃったことですか？」
line = "「え？　それって……幸運の力が無くなっちゃったことですか？」"

[[dialogue]]
speaker = "サチ"
# 「……前に話したことがあったかもしれませんけど、私、昔から幸運体質に頼りきりにならないようにしようって、意識して生きてきたんです」
line = "「……前に話したことがあったかもしれませんけど、私、昔から幸運体質に頼りきりにならないようにしようって、意識して生きてきたんです」"

[[dialogue]]
speaker = "サチ"
# 「幸運には波がありますから。必ず、ラッキーが起こらないタイミングが訪れる。私はその時、ラッキーが再び起きるまで待つ自分にはなりたくなかったんです」
line = "「幸運には波がありますから。必ず、ラッキーが起こらないタイミングが訪れる。私はその時、ラッキーが再び起きるまで待つ自分にはなりたくなかったんです」"

[[dialogue]]
speaker = "サチ"
# 「だから今がまさに、積み重ねてきた地力が試される時です」
line = "「だから今がまさに、積み重ねてきた地力が試される時です」"

[[dialogue]]
speaker = "サチ"
# 「そ、それに……お兄さんの近くにいても、エッチなことが起きなくなったのはいいことです、うん」
line = "「そ、それに……お兄さんの近くにいても、エッチなことが起きなくなったのはいいことです、うん」"

[[dialogue]]
speaker = "unk"
# 自分に言い聞かせるように語るサチ。
line = "自分に言い聞かせるように語るサチ。"

[[dialogue]]
speaker = "unk"
# 今日の訓練では、俺とサチが連携攻撃を行っても、ラッキースケベな事故が起こることは１度もなかった。
line = "今日の訓練では、俺とサチが連携攻撃を行っても、ラッキースケベな事故が起こることは１度もなかった。"

[[dialogue]]
speaker = "サチ"
# 「でも……」
line = "「でも……」"

[[dialogue]]
speaker = "サチ"
# 「いざ本当に幸運を失ってみると、普段の自分がいかに幸運に頼っていたのかを実感しますね」
line = "「いざ本当に幸運を失ってみると、普段の自分がいかに幸運に頼っていたのかを実感しますね」"

[[dialogue]]
speaker = "サチ"
# 「そこについてはやっぱり、ちょっと落ち込みます……。今日の訓練結果は、私がビリでしたし……」
line = "「そこについてはやっぱり、ちょっと落ち込みます……。今日の訓練結果は、私がビリでしたし……」"

[[dialogue]]
speaker = "unk"
# サチ、頭を撫でてもいい？
line = "サチ、頭を撫でてもいい？"

[[dialogue]]
speaker = "サチ"
# 「へ！？　い、いきなりなんですか、お兄さん！？」
line = "「へ！？　い、いきなりなんですか、お兄さん！？」"

[[dialogue]]
speaker = "unk"
# サチが頑張り屋で、いつもたゆまぬ努力を続けていることを俺は知っている。
line = "サチが頑張り屋で、いつもたゆまぬ努力を続けていることを俺は知っている。"

[[dialogue]]
speaker = "unk"
# でも今までは、サチに不用意に接触するとラッキースケベが起きてしまう可能性があったから、遠慮していた。
line = "でも今までは、サチに不用意に接触するとラッキースケベが起きてしまう可能性があったから、遠慮していた。"

[[dialogue]]
speaker = "unk"
# だから、遠慮しないなら今かなと思った――と、俺は気持ちを伝える。
line = "だから、遠慮しないなら今かなと思った――と、俺は気持ちを伝える。"

[[dialogue]]
speaker = "サチ"
# 「……そ、そうだったんですね。……なら、その……」
line = "「……そ、そうだったんですね。……なら、その……」"

[[dialogue]]
speaker = "サチ"
# 「エッチなことが目的じゃないなら……はい。どうぞ……」
line = "「エッチなことが目的じゃないなら……はい。どうぞ……」"

[[dialogue]]
speaker = "unk"
# サチはもじもじと指を突き合わせながら、上目遣いで俺の様子を伺うように言う。
line = "サチはもじもじと指を突き合わせながら、上目遣いで俺の様子を伺うように言う。"

[[dialogue]]
speaker = "unk"
# 俺はそんな彼女の頭に、そっと手を置き、優しく撫でる。
line = "俺はそんな彼女の頭に、そっと手を置き、優しく撫でる。"

[[dialogue]]
speaker = "サチ"
# 「ん……<emoji=heart04>」
line = "「ん……<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# それから俺は、彼女に言う。
line = "それから俺は、彼女に言う。"

[[dialogue]]
speaker = "サチ"
# 「え？　幸運が戻るまでの間は、みんなで私をサポートする……ですか？」
line = "「え？　幸運が戻るまでの間は、みんなで私をサポートする……ですか？」"

[[dialogue]]
speaker = "unk"
# だから、困った時は相談してくれ
line = "だから、困った時は相談してくれ"

[[dialogue]]
speaker = "サチ"
# 「お兄さん……。はい、ありがとうございます♪」
line = "「お兄さん……。はい、ありがとうございます♪」"

[[dialogue]]
speaker = "サチ"
# 「えへへ♪」
line = "「えへへ♪」"

[[dialogue]]
speaker = "unk"
# その後、少し元気を取り戻したサチと他愛のない話に花を咲かせながら、彼女を家まで送り届けるのだった――
line = "その後、少し元気を取り戻したサチと他愛のない話に花を咲かせながら、彼女を家まで送り届けるのだった――"
