[[dialogue]]
speaker = "unk"
# 俺が２人の元に駆けつけた直後、見たことのないボスモンスターが姿を現していた。
line = "俺が２人の元に駆けつけた直後、見たことのないボスモンスターが姿を現していた。"

[[dialogue]]
speaker = "トワ先生"
# 「会長くん……他の星徒会メンバーのみんなは……？」
line = "「会長くん……他の星徒会メンバーのみんなは……？」"

[[dialogue]]
speaker = "unk"
# ヴィーナス達は俺を早く２人の元へ行かせる為に、アステラ内に多数出現している雑魚モンスターの掃討を引き受けてくれていた。
line = "ヴィーナス達は俺を早く２人の元へ行かせる為に、アステラ内に多数出現している雑魚モンスターの掃討を引き受けてくれていた。"

[[dialogue]]
speaker = "トワ先生"
# 「――そう。まだ少し時間がかかるってことだね……じゃあ、全員揃うまで、３人で切り抜けるしかない、か……！」
line = "「――そう。まだ少し時間がかかるってことだね……じゃあ、全員揃うまで、３人で切り抜けるしかない、か……！」"

[[dialogue]]
speaker = "メイプル"
# 「先生、その傷で無理しないで！」
line = "「先生、その傷で無理しないで！」"

[[dialogue]]
speaker = "トワ先生"
# 「大丈夫だよ。少し休んで、自動回復したから……」
line = "「大丈夫だよ。少し休んで、自動回復したから……」"

[[dialogue]]
speaker = "メイプル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "メイプル"
# 「１つだけ、あたしに考えがある」
line = "「１つだけ、あたしに考えがある」"

[[dialogue]]
speaker = "トワ先生"
# 「考え……？」
line = "「考え……？」"

[[dialogue]]
speaker = "メイプル"
# 「うん。あの新種モンスターを倒せるかもしれない切り札が、あたしにもある」
line = "「うん。あの新種モンスターを倒せるかもしれない切り札が、あたしにもある」"

[[dialogue]]
speaker = "メイプル"
# 「前に言ったことあったよね。魔王の秘伝――」
line = "「前に言ったことあったよね。魔王の秘伝――」"

[[dialogue]]
speaker = "メイプル"
# 「アルケインコード」
line = "「アルケインコード」"

[[dialogue]]
speaker = "トワ先生"
# 「それは……でも、まだ使えないって……」
line = "「それは……でも、まだ使えないって……」"

[[dialogue]]
speaker = "メイプル"
# 「うん。今のあたしには使えない。だから――」
line = "「うん。今のあたしには使えない。だから――」"

[[dialogue]]
speaker = "メイプル"
# 「それを今からお兄ちゃんに託す」
line = "「それを今からお兄ちゃんに託す」"

[[dialogue]]
speaker = "メイプル"
# 「モノクラウン家の伝承星術を使う。――行くよ、お兄ちゃん！」
line = "「モノクラウン家の伝承星術を使う。――行くよ、お兄ちゃん！」"

[[dialogue]]
speaker = "unk"
# メイプルが俺の額に白いパペットで触れる。次の瞬間――
line = "メイプルが俺の額に白いパペットで触れる。次の瞬間――"

[[dialogue]]
speaker = "unk"
# ここは……？
line = "ここは……？"

[[dialogue]]
speaker = "メイプル"
# 「モノクラウン家は代々、アルケインコードの１つを伝承し続けてきた。親から子に、そして魔王の血を引く者へと」
line = "「モノクラウン家は代々、アルケインコードの１つを伝承し続けてきた。親から子に、そして魔王の血を引く者へと」"

[[dialogue]]
speaker = "メイプル"
# 「ここはその伝承を行う精神世界。ここでの時間は、現実では１秒にも満たない。だから、落ち着いて聞いて」
line = "「ここはその伝承を行う精神世界。ここでの時間は、現実では１秒にも満たない。だから、落ち着いて聞いて」"

[[dialogue]]
speaker = "メイプル"
# 「今から渡すアルケインコードは、魔王と仲間の『絆』が試される力」
line = "「今から渡すアルケインコードは、魔王と仲間の『絆』が試される力」"

[[dialogue]]
speaker = "メイプル"
# 「仲間との間に絆がなければ、そもそも発動しない」
line = "「仲間との間に絆がなければ、そもそも発動しない」"

[[dialogue]]
speaker = "メイプル"
# 「そして、この技は魔王ではなく、その仲間に力を与える。だから――」
line = "「そして、この技は魔王ではなく、その仲間に力を与える。だから――」"

[[dialogue]]
speaker = "メイプル"
# 「今この場でお兄ちゃんが力を与えられる相手は、トワ先生ということになる」
line = "「今この場でお兄ちゃんが力を与えられる相手は、トワ先生ということになる」"

[[dialogue]]
speaker = "トワ先生"
# 「えっ、私！？」
line = "「えっ、私！？」"

[[dialogue]]
speaker = "unk"
# 先生！　いつの間に！？
line = "先生！　いつの間に！？"

[[dialogue]]
speaker = "メイプル"
# 「先生にも理解しておいてもらわないといけないから呼んだの」
line = "「先生にも理解しておいてもらわないといけないから呼んだの」"

[[dialogue]]
speaker = "トワ先生"
# 「で、でも、会長くんとの絆って……私で大丈夫なの！？　な、仲は悪くないと思うけど、先生と生徒との間柄だし……」
line = "「で、でも、会長くんとの絆って……私で大丈夫なの！？　な、仲は悪くないと思うけど、先生と生徒との間柄だし……」"

[[dialogue]]
speaker = "メイプル"
# 「言いつつも、なんか乙女なリアクションになってるよ。先生」
line = "「言いつつも、なんか乙女なリアクションになってるよ。先生」"

[[dialogue]]
speaker = "トワ先生"
# 「えっ！？　そ、そんなことないよ！？　確かに会長くんはカッコいいなぁって思ったりすることあるけど……！」
line = "「えっ！？　そ、そんなことないよ！？　確かに会長くんはカッコいいなぁって思ったりすることあるけど……！」"

[[dialogue]]
speaker = "トワ先生"
# 「そ、それは今まで恋愛経験が全くなかったから、反射的にトキめいちゃってるだけだからッ！！！」
line = "「そ、それは今まで恋愛経験が全くなかったから、反射的にトキめいちゃってるだけだからッ！！！」"

[[dialogue]]
speaker = "unk"
# えぇっ！？
line = "えぇっ！？"

[[dialogue]]
speaker = "メイプル"
# 「だ、大胆なカミングアウトだね……」
line = "「だ、大胆なカミングアウトだね……」"

[[dialogue]]
speaker = "トワ先生"
# 「あ…………うわあああぁぁぁっ！？　思わずとんでもないこと言っちゃったあああぁぁぁっ！！！」
line = "「あ…………うわあああぁぁぁっ！？　思わずとんでもないこと言っちゃったあああぁぁぁっ！！！」"

[[dialogue]]
speaker = "メイプル"
# 「と、とりあえず先生の方は思ってたより大丈夫そうとして……後は、お兄ちゃん次第かな」
line = "「と、とりあえず先生の方は思ってたより大丈夫そうとして……後は、お兄ちゃん次第かな」"

[[dialogue]]
speaker = "unk"
# それは大丈夫
line = "それは大丈夫"

[[dialogue]]
speaker = "トワ先生"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "unk"
# 俺は先生のこと、信じてるから
line = "俺は先生のこと、信じてるから"

[[dialogue]]
speaker = "トワ先生"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "トワ先生"
# 「そんなに改まってどうしたの、会長くん？」
line = "「そんなに改まってどうしたの、会長くん？」"

[[dialogue]]
speaker = "トワ先生"
# 「――お願いがある？　星力制御を教えて欲しい？」
line = "「――お願いがある？　星力制御を教えて欲しい？」"

[[dialogue]]
speaker = "トワ先生"
# 「うん、先生でよければ、喜んで教えるよ♪」
line = "「うん、先生でよければ、喜んで教えるよ♪」"

[[dialogue]]
speaker = "トワ先生"
# 「――いつも時間を取らせて、申し訳ないって？」
line = "「――いつも時間を取らせて、申し訳ないって？」"

[[dialogue]]
speaker = "トワ先生"
# 「あはは、そんなこと全然気にしなくていいよ。生徒を教え導くのが、先生の仕事だからね～」
line = "「あはは、そんなこと全然気にしなくていいよ。生徒を教え導くのが、先生の仕事だからね～」"

[[dialogue]]
speaker = "トワ先生"
# 「……というのは、建前。本当は――」
line = "「……というのは、建前。本当は――」"

[[dialogue]]
speaker = "トワ先生"
# 「会長くんが御前試合でヴィーナスちゃんに勝ったあの日、私も負けたくないって思っちゃったんだよね」
line = "「会長くんが御前試合でヴィーナスちゃんに勝ったあの日、私も負けたくないって思っちゃったんだよね」"

[[dialogue]]
speaker = "トワ先生"
# 「――そう。私も星騎士として、もっと強くなりたいって！」
line = "「――そう。私も星騎士として、もっと強くなりたいって！」"

[[dialogue]]
speaker = "トワ先生"
# 「だから……会長くんと一緒に訓練することができて、実は嬉しかったんだ！　えへへ♪」
line = "「だから……会長くんと一緒に訓練することができて、実は嬉しかったんだ！　えへへ♪」"

[[dialogue]]
speaker = "メイプル"
# 「……アルケインコード、確かに伝えたよ。お兄ちゃん！」
line = "「……アルケインコード、確かに伝えたよ。お兄ちゃん！」"

[[dialogue]]
speaker = "unk"
# ああ。……トワ先生！
line = "ああ。……トワ先生！"

[[dialogue]]
speaker = "トワ先生"
# 「……うん！　いつでもいいよ、会長くん！」
line = "「……うん！　いつでもいいよ、会長くん！」"

[[dialogue]]
speaker = "unk"
# 俺はトワ先生の背中に手をかざす。そして、告げる。
line = "俺はトワ先生の背中に手をかざす。そして、告げる。"

[[dialogue]]
speaker = "unk"
# メイプルから託された、その技の名は――
line = "メイプルから託された、その技の名は――"

[[dialogue]]
speaker = "unk"
# アルケインノヴァエクストリーム！！！
line = "アルケインノヴァエクストリーム！！！"

[[dialogue]]
speaker = "unk"
# トワ先生を中心に大きな光が広がっていく、そして――
line = "トワ先生を中心に大きな光が広がっていく、そして――"

[[dialogue]]
speaker = "トワ先生（覚醒）"
# 「これは……！」
line = "「これは……！」"

[[dialogue]]
speaker = "トワ先生（覚醒）"
# 「戦闘服が進化した……！」
line = "「戦闘服が進化した……！」"

[[dialogue]]
speaker = "メイプル"
# 「お兄ちゃん……本当に……！」
line = "「お兄ちゃん……本当に……！」"

[[dialogue]]
speaker = "メイプル"
# 「これが……魔王の力――アルケインノヴァエクストリーム……！」
line = "「これが……魔王の力――アルケインノヴァエクストリーム……！」"

[[dialogue]]
speaker = "トワ先生（覚醒）"
# 「わかる……会長くんを通して……すごい力が流れ込んでくる……！」
line = "「わかる……会長くんを通して……すごい力が流れ込んでくる……！」"

[[dialogue]]
speaker = "トワ先生（覚醒）"
# （自動回復が変化……いや、進化して、体に常時ライズ・オーバーブーストがかかってる。自動だから制御も必要ない）
line = "（自動回復が変化……いや、進化して、体に常時ライズ・オーバーブーストがかかってる。自動だから制御も必要ない）"

[[dialogue]]
speaker = "トワ先生（覚醒）"
# （これなら多分……！）
line = "（これなら多分……！）"

[[dialogue]]
speaker = "トワ先生（覚醒）"
# 「ライズ・オーバーブースト！」
line = "「ライズ・オーバーブースト！」"

[[dialogue]]
speaker = "メイプル"
# 「えっ！？」
line = "「えっ！？」"

[[dialogue]]
speaker = "メイプル"
# 「体から星力が……満ち溢れてくる！」
line = "「体から星力が……満ち溢れてくる！」"

[[dialogue]]
speaker = "unk"
# 俺もだ！
line = "俺もだ！"

[[dialogue]]
speaker = "トワ先生（覚醒）"
# 「やっぱりそうだ……今の姿なら、反動のないライズ・オーバーブーストを２人にも付与することができる！」
line = "「やっぱりそうだ……今の姿なら、反動のないライズ・オーバーブーストを２人にも付与することができる！」"

[[dialogue]]
speaker = "トワ先生（覚醒）"
# 「先生が２人を勝利に導く！　だから！」
line = "「先生が２人を勝利に導く！　だから！」"

[[dialogue]]
speaker = "トワ先生（覚醒）"
# 「一緒に戦おう！　メイプルちゃん！　会長くん！」
line = "「一緒に戦おう！　メイプルちゃん！　会長くん！」"

[[dialogue]]
speaker = "メイプル"
# 「うん！　先生！」
line = "「うん！　先生！」"

[[dialogue]]
speaker = "unk"
# 行きましょう！
line = "行きましょう！"

[[dialogue]]
speaker = "unk"
# 俺たちは新種モンスターに向き直る。
line = "俺たちは新種モンスターに向き直る。"

[[dialogue]]
speaker = "モンスター"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "トワ先生（覚醒）"
# 「……いざ、勝負ッ！！」
line = "「……いざ、勝負ッ！！」"

[[dialogue]]
speaker = "モンスター"
# 「グオオオォォォーーーッ！！！」
line = "「グオオオォォォーーーッ！！！」"

[[dialogue]]
speaker = "トワ先生（覚醒）"
# 「はあああぁぁぁーーーッ！！！」
line = "「はあああぁぁぁーーーッ！！！」"

[[dialogue]]
speaker = "unk"
# トワ先生と新種モンスターが真っ向から攻撃をぶつけ合い、決戦の火蓋が切って落とされるのだった――
line = "トワ先生と新種モンスターが真っ向から攻撃をぶつけ合い、決戦の火蓋が切って落とされるのだった――"
