[[dialogue]]
speaker = "シャルレーヌ"
# 「キャハハっ<emoji=heart04>　今日も楽しい時間が過ごせましたね、会長さん？」
line = "「キャハハっ<emoji=heart04>　今日も楽しい時間が過ごせましたね、会長さん？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「私の所有物になっていただけるなら、もっと素敵なことをして差し上げますけど～？」
line = "「私の所有物になっていただけるなら、もっと素敵なことをして差し上げますけど～？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「…………ふぅん。やっぱり簡単には懐いてくれないんですねぇ。まあいいです、どうせ最後は私のものになるんだし？」
line = "「…………ふぅん。やっぱり簡単には懐いてくれないんですねぇ。まあいいです、どうせ最後は私のものになるんだし？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「結末は決まってるので、道中を楽しむことにしましょうか。くふふ、今日も会長さんの色んなことが知れて楽しかった～<emoji=heart04>」
line = "「結末は決まってるので、道中を楽しむことにしましょうか。くふふ、今日も会長さんの色んなことが知れて楽しかった～<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「んー？　どうしました。何か聞きたいことでも？」
line = "「んー？　どうしました。何か聞きたいことでも？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「くすくす、いいですよ。会長さんからの質問は新鮮です。何でも答えてあげますよ～？」
line = "「くすくす、いいですよ。会長さんからの質問は新鮮です。何でも答えてあげますよ～？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「…………素の性格を出して話せる人は、会長さん以外にいるのか、ですか？」
line = "「…………素の性格を出して話せる人は、会長さん以外にいるのか、ですか？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「くすくすっ♪　そんなの、いるわけないじゃないですか。会長さん以外には、貴族令嬢として慎ましく接してますよ？」
line = "「くすくすっ♪　そんなの、いるわけないじゃないですか。会長さん以外には、貴族令嬢として慎ましく接してますよ？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「まあシャリオンの──同郷の方が相手の場合は、繕わない時もありますけれど。星騎士の方々には折り目正しく接しています」
line = "「まあシャリオンの──同郷の方が相手の場合は、繕わない時もありますけれど。星騎士の方々には折り目正しく接しています」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「貴族の娘なんですから、人当たりよく自分を偽るのは当然でしょう？　今さら本当の顔を見せるメリットも感じません」
line = "「貴族の娘なんですから、人当たりよく自分を偽るのは当然でしょう？　今さら本当の顔を見せるメリットも感じません」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「だって、誰だって嫌でしょう？　仲良くなってから、本当はすっごく性格の悪い女の子だった～、なんてカミングアウトされるのは♪」
line = "「だって、誰だって嫌でしょう？　仲良くなってから、本当はすっごく性格の悪い女の子だった～、なんてカミングアウトされるのは♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「シャルレーヌちゃん……なんかさっきから、人が違うってゆーか……『ざ～こ』とか言ってたけど、そんなまさか……」
line = "「シャルレーヌちゃん……なんかさっきから、人が違うってゆーか……『ざ～こ』とか言ってたけど、そんなまさか……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「あっ、えっと……それは──」
line = "「あっ、えっと……それは──」"

[[dialogue]]
speaker = "ウズメイア"
# 「まさかの──『メスガキ』ってやつだし！？」
line = "「まさかの──『メスガキ』ってやつだし！？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「……………………は？」
line = "「……………………は？」"

[[dialogue]]
speaker = "ウズメイア"
# 「すごい！　すごいすごい！　『ざ～こ<emoji=heart04>』ってリアルで初めて聞いたし！」
line = "「すごい！　すごいすごい！　『ざ～こ<emoji=heart04>』ってリアルで初めて聞いたし！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「えっ……あ、あの……？」
line = "「えっ……あ、あの……？」"

[[dialogue]]
speaker = "ウズメイア"
# 「ヤッバ、ニンジャに続いてメスガキまで見つけちゃった……ジャパンすごい！　流星市国、ヤバイ！　テンション上がってきたし～！」
line = "「ヤッバ、ニンジャに続いてメスガキまで見つけちゃった……ジャパンすごい！　流星市国、ヤバイ！　テンション上がってきたし～！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「か、会長さん……あの、ウズメイア先輩は一体何を言ってるのかしら……？」
line = "「か、会長さん……あの、ウズメイア先輩は一体何を言ってるのかしら……？」"

[[dialogue]]
speaker = "unk"
# 彼女、日本文化のフリークなんだ
line = "彼女、日本文化のフリークなんだ"

[[dialogue]]
speaker = "シャルレーヌ"
# 「それは何となく知ってます！　だからって、何でこんなテンションを上げて喜んでるのかって聞いてるんです！」
line = "「それは何となく知ってます！　だからって、何でこんなテンションを上げて喜んでるのかって聞いてるんです！」"

[[dialogue]]
speaker = "ウズメイア"
# 「そんなのトーゼン！　漫画やアニメにしかいないと思ってたメスガキが現実にあったわけで！　もう青天霹靂～って感じ！」
line = "「そんなのトーゼン！　漫画やアニメにしかいないと思ってたメスガキが現実にあったわけで！　もう青天霹靂～って感じ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「そもそも、何なの？　さっきから散々言われてるけど、メスガキって……！？」
line = "「そもそも、何なの？　さっきから散々言われてるけど、メスガキって……！？」"

[[dialogue]]
speaker = "ウズメイア"
# 「ご存じない！？　え、てことは天然ってコト！？　養殖じゃなく天然のメスガキ！？」
line = "「ご存じない！？　え、てことは天然ってコト！？　養殖じゃなく天然のメスガキ！？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「だからメスガキって何なんですか……！？」
line = "「だからメスガキって何なんですか……！？」"

[[dialogue]]
speaker = "ウズメイア"
# 「よーし、オタク文化布教のために、一席ぶっちゃうし！」
line = "「よーし、オタク文化布教のために、一席ぶっちゃうし！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「……まあ、何となくわかりました。サブカルチャーの中に、そのような用語があるんですね」
line = "「……まあ、何となくわかりました。サブカルチャーの中に、そのような用語があるんですね」"

[[dialogue]]
speaker = "ウズメイア"
# 「そーそー。いや～、でも本当にすごい変貌ぶりだったね～。シャルレーヌちゃんって普段はあれなの。猫かぶり、みたいな？」
line = "「そーそー。いや～、でも本当にすごい変貌ぶりだったね～。シャルレーヌちゃんって普段はあれなの。猫かぶり、みたいな？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ま、まあ…………そうね。がっかりしたでしょ？」
line = "「ま、まあ…………そうね。がっかりしたでしょ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「え、何で？」
line = "「え、何で？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「それは、だって……隠し事をしたまま接せられていたわけだから。不愉快でしょう？」
line = "「それは、だって……隠し事をしたまま接せられていたわけだから。不愉快でしょう？」"

[[dialogue]]
speaker = "ウズメイア"
# 「え～、そんなことないよ？　てゆーか、シャルレーヌちゃんってガチの貴族じゃん？　色々事情があるのはトーゼンっしょ！」
line = "「え～、そんなことないよ？　てゆーか、シャルレーヌちゃんってガチの貴族じゃん？　色々事情があるのはトーゼンっしょ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「あたしみたいな庶民と違って、キャラ付け？　みたいなのが大事ってゆーのも、全然想像つくし～」
line = "「あたしみたいな庶民と違って、キャラ付け？　みたいなのが大事ってゆーのも、全然想像つくし～」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「ウズメイア先輩……」
line = "「ウズメイア先輩……」"

[[dialogue]]
speaker = "ウズメイア"
# 「てゆーかあたし、清楚お嬢様が実は腹黒！　みたいなやつ、大好物♪　漫画で予習済みだし！」
line = "「てゆーかあたし、清楚お嬢様が実は腹黒！　みたいなやつ、大好物♪　漫画で予習済みだし！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「その、何かにつけて『漫画で見た』と言われるのは、ちょっぴり複雑ですけれど……」
line = "「その、何かにつけて『漫画で見た』と言われるのは、ちょっぴり複雑ですけれど……」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「不愉快に思っていないのなら、良かったわ」
line = "「不愉快に思っていないのなら、良かったわ」"

[[dialogue]]
speaker = "ウズメイア"
# 「マジで安心してね。あたし、ギャルだけど口は堅いし♪　誰にも言わないから！」
line = "「マジで安心してね。あたし、ギャルだけど口は堅いし♪　誰にも言わないから！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「……ウズメイア先輩って、よくお人好しって言われません？」
line = "「……ウズメイア先輩って、よくお人好しって言われません？」"

[[dialogue]]
speaker = "ウズメイア"
# 「言われる♪　めっちゃ言われる～♪」
line = "「言われる♪　めっちゃ言われる～♪」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「でしょうね。まあ、そう言ってもらえるならありがたいわ……良かった」
line = "「でしょうね。まあ、そう言ってもらえるならありがたいわ……良かった」"

[[dialogue]]
speaker = "ウズメイア"
# 「そんな不安にならなくても～♪　あたしの薙刀に誓って、シャルレーヌちゃんの秘密は墓まで持って行くし！」
line = "「そんな不安にならなくても～♪　あたしの薙刀に誓って、シャルレーヌちゃんの秘密は墓まで持って行くし！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「いえ、それもですが……せっかくペアになった先輩なので、嫌われなくて良かったってことです」
line = "「いえ、それもですが……せっかくペアになった先輩なので、嫌われなくて良かったってことです」"

[[dialogue]]
speaker = "ウズメイア"
# 「……お～。たまにこうやってデレるから、会長くんも絆されちゃった感じ……？」
line = "「……お～。たまにこうやってデレるから、会長くんも絆されちゃった感じ……？」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「くふっ<emoji=heart04>　まぁバレちゃったものは仕方ないですね～。それに物は考えようです」
line = "「くふっ<emoji=heart04>　まぁバレちゃったものは仕方ないですね～。それに物は考えようです」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「これからはウズメイア先輩が見てる前でも、会長さんとワンちゃんごっこができるってことですし～<emoji=heart04>」
line = "「これからはウズメイア先輩が見てる前でも、会長さんとワンちゃんごっこができるってことですし～<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# それは２人の時でも遠慮して！？
line = "それは２人の時でも遠慮して！？"

[[dialogue]]
speaker = "ウズメイア"
# 「う～ん。下級生が実はドＳのメスガキとか、これもう漫画の世界を超えちゃったりしてない？　事実は小説よりもってやつだし……」
line = "「う～ん。下級生が実はドＳのメスガキとか、これもう漫画の世界を超えちゃったりしてない？　事実は小説よりもってやつだし……」"

[[dialogue]]
speaker = "unk"
# バレた時はどうなることかと思ったけれど、明るいウズメが相手で良かった。
line = "バレた時はどうなることかと思ったけれど、明るいウズメが相手で良かった。"

[[dialogue]]
speaker = "unk"
# こうしてシャルレーヌは、俺以外にも素の自分を見せられる相手が増えたのだけれど──
line = "こうしてシャルレーヌは、俺以外にも素の自分を見せられる相手が増えたのだけれど──"

[[dialogue]]
speaker = "ウズメイア"
# 「ちょい思ったんだけどさ。チョコの味が変になっちゃう原因って、シャルレーヌちゃんが素の状態を隠してたからじゃない？」
line = "「ちょい思ったんだけどさ。チョコの味が変になっちゃう原因って、シャルレーヌちゃんが素の状態を隠してたからじゃない？」"

[[dialogue]]
speaker = "ウズメイア"
# 「チョコに星力を込める時、いつもペアのあたしの前でやってたでしょ？　優等生なお嬢様～なシャルレーヌちゃんを演じてたわけで」
line = "「チョコに星力を込める時、いつもペアのあたしの前でやってたでしょ？　優等生なお嬢様～なシャルレーヌちゃんを演じてたわけで」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「……本当の自分を隠しているから、星力にも影響が出て、味がおかしくなってしまったってことかしら？」
line = "「……本当の自分を隠しているから、星力にも影響が出て、味がおかしくなってしまったってことかしら？」"

[[dialogue]]
speaker = "ウズメイア"
# 「そう！　あたしの親友のソフィも、胸にわだかまりがあるうちは晴れ着フォームをうまく使えてなかったし……」
line = "「そう！　あたしの親友のソフィも、胸にわだかまりがあるうちは晴れ着フォームをうまく使えてなかったし……」"

[[dialogue]]
speaker = "ウズメイア"
# 「星力ってメンタルにすごく影響を受けるってトワ先生も言ってたし！」
line = "「星力ってメンタルにすごく影響を受けるってトワ先生も言ってたし！」"

[[dialogue]]
speaker = "unk"
# 試してみる価値はありそうだね
line = "試してみる価値はありそうだね"

[[dialogue]]
speaker = "シャルレーヌ"
# 「そうですね。会長さんのお夜食にと思って、ちょうど星力を込めていないトリュフチョコは持ってきています」
line = "「そうですね。会長さんのお夜食にと思って、ちょうど星力を込めていないトリュフチョコは持ってきています」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「本当は後で、ワンちゃんごっこのご褒美にしようと思ってたんですけど♪」
line = "「本当は後で、ワンちゃんごっこのご褒美にしようと思ってたんですけど♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「あははっ、シャルレーヌちゃん、その調子だし♪　メスガキのまま星力チャージだよ！」
line = "「あははっ、シャルレーヌちゃん、その調子だし♪　メスガキのまま星力チャージだよ！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「は～い……美味しくなあれ、キャハっ<emoji=heart04>」
line = "「は～い……美味しくなあれ、キャハっ<emoji=heart04>」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「お試しいただけますか、魔王様♪」
line = "「お試しいただけますか、魔王様♪」"

[[dialogue]]
speaker = "unk"
# これは──ものすごく甘いっ！
line = "これは──ものすごく甘いっ！"

[[dialogue]]
speaker = "ウズメイア"
# 「大成功じゃん！　やったし～♪」
line = "「大成功じゃん！　やったし～♪」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「……そうね。ウズメイア先輩のおかげだわ。ありがとうございます♪」
line = "「……そうね。ウズメイア先輩のおかげだわ。ありがとうございます♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「ふふ～ん♪　先輩だからね、後輩の面倒を見るのもお役目だし！」
line = "「ふふ～ん♪　先輩だからね、後輩の面倒を見るのもお役目だし！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ようしっ、それじゃあチョコ作りの憂いもなくなったし……明日はたくさんチョコを作るぞ～！」
line = "「ようしっ、それじゃあチョコ作りの憂いもなくなったし……明日はたくさんチョコを作るぞ～！」"

[[dialogue]]
speaker = "シャルレーヌ"
# 「はい、先輩っ♪」
line = "「はい、先輩っ♪」"

[[dialogue]]
speaker = "unk"
# 今まではきちんとしたチョコレートを用意できないことを気にしていたのだろうか。問題が解決したシャルレーヌは、とても晴れやかな笑顔を浮かべるのだった──
line = "今まではきちんとしたチョコレートを用意できないことを気にしていたのだろうか。問題が解決したシャルレーヌは、とても晴れやかな笑顔を浮かべるのだった──"

[[dialogue]]
speaker = "unk"
# 数時間後──深夜の消灯したカフェテリア。
line = "数時間後──深夜の消灯したカフェテリア。"

[[dialogue]]
speaker = "ルリエル"
# 「よ～し、このまましっかり朝まで警備しちゃうのです！　打倒、チョコレート泥棒っ！」
line = "「よ～し、このまましっかり朝まで警備しちゃうのです！　打倒、チョコレート泥棒っ！」"

[[dialogue]]
speaker = "ルリエル"
# 「でも……はぅう。ずっと張り込みを続けて、お腹が空いてきちゃいました。カフェの中はチョコの香りでいっぱいで、誘惑が多いのです……」
line = "「でも……はぅう。ずっと張り込みを続けて、お腹が空いてきちゃいました。カフェの中はチョコの香りでいっぱいで、誘惑が多いのです……」"

[[dialogue]]
speaker = "ルリエル"
# 「ううっ、いけません。とりあえず学園の購買で、何か買ってきましょう！　腹が減っては何とやら、なのです！」
line = "「ううっ、いけません。とりあえず学園の購買で、何か買ってきましょう！　腹が減っては何とやら、なのです！」"

[[dialogue]]
speaker = "unk"
# ルリエルがいなくなってから──カフェテリアの隅で、ずっと息を殺していた影が動き出す。
line = "ルリエルがいなくなってから──カフェテリアの隅で、ずっと息を殺していた影が動き出す。"

[[dialogue]]
speaker = "フワッチ"
# 「イ～～～～っ♪」
line = "「イ～～～～っ♪」"
