[[dialogue]]
speaker = "リーリア"
# 「センパイ、こんにちマジカル～☆　それじゃヒミツの会議、始めましょうか♪」
line = "「センパイ、こんにちマジカル～☆　それじゃヒミツの会議、始めましょうか♪」"

[[dialogue]]
speaker = "unk"
# ネビュラとコラプサー事件について情報共有するために、リーリアが代表としてやってきた。
line = "ネビュラとコラプサー事件について情報共有するために、リーリアが代表としてやってきた。"

[[dialogue]]
speaker = "unk"
# のだが──
line = "のだが──"

[[dialogue]]
speaker = "リーリア"
# 「はぁ……」
line = "「はぁ……」"

[[dialogue]]
speaker = "unk"
# リーリア、どうかした？
line = "リーリア、どうかした？"

[[dialogue]]
speaker = "リーリア"
# 「ああ、いえ、すみません。ちょっと個人的な考え事が……」
line = "「ああ、いえ、すみません。ちょっと個人的な考え事が……」"

[[dialogue]]
speaker = "リーリア"
# （まさかあの人を監視していたのが、あんな理由だったなんて……バレないといいけど……）
line = "（まさかあの人を監視していたのが、あんな理由だったなんて……バレないといいけど……）"

[[dialogue]]
speaker = "リーリア"
# （いやでも、いずれわかることだし、早い方がいいのかも……。だけど絶対ショックだろうしなぁ……ううん、今考えても仕方ないし、一旦忘れよう）
line = "（いやでも、いずれわかることだし、早い方がいいのかも……。だけど絶対ショックだろうしなぁ……ううん、今考えても仕方ないし、一旦忘れよう）"

[[dialogue]]
speaker = "リーリア"
# 「……コホン。失礼しました、本題に入りましょう。コラプサー事件のことですよね」
line = "「……コホン。失礼しました、本題に入りましょう。コラプサー事件のことですよね」"

[[dialogue]]
speaker = "リーリア"
# 「コラプサーの存在が明るみになったのは、キサナの一件でした。彼女の星騎士襲撃に始まり、続いてリーナ、ヴァレリーとの邂逅」
line = "「コラプサーの存在が明るみになったのは、キサナの一件でした。彼女の星騎士襲撃に始まり、続いてリーナ、ヴァレリーとの邂逅」"

[[dialogue]]
speaker = "リーリア"
# 「さらにイングリット、ジュリエッテとも遭遇しました。今までに判明した構成メンバーは５人です」
line = "「さらにイングリット、ジュリエッテとも遭遇しました。今までに判明した構成メンバーは５人です」"

[[dialogue]]
speaker = "リーリア"
# 「そして、ジュリエッテが語った目的は──」
line = "「そして、ジュリエッテが語った目的は──」"

[[dialogue]]
speaker = "ジュリエッテ"
# 「コラプサーの目的は救世。あなた方と同じく世界を守ることでございます」
line = "「コラプサーの目的は救世。あなた方と同じく世界を守ることでございます」"

[[dialogue]]
speaker = "リーリア"
# 「──な～んて言ってましたけど、それなら星騎士の襲撃も、世界を救うためなんですかね？　言ってることとやってることがちぐはぐですよ」
line = "「──な～んて言ってましたけど、それなら星騎士の襲撃も、世界を救うためなんですかね？　言ってることとやってることがちぐはぐですよ」"

[[dialogue]]
speaker = "リーリア"
# 「あと、彼女たちの目的だけじゃなくて、その力についても判明したことがありました」
line = "「あと、彼女たちの目的だけじゃなくて、その力についても判明したことがありました」"

[[dialogue]]
speaker = "unk"
# 彼女たちの守護星はブラックホールだった
line = "彼女たちの守護星はブラックホールだった"

[[dialogue]]
speaker = "リーリア"
# 「はい。でもブラックホールを守護星に持つ星騎士なんて、今まで流星学園にも新星学園にもいませんでした。ネビュラの記録にもありません」
line = "「はい。でもブラックホールを守護星に持つ星騎士なんて、今まで流星学園にも新星学園にもいませんでした。ネビュラの記録にもありません」"

[[dialogue]]
speaker = "リーリア"
# 「そんな稀少な存在が、少なくとも５人も集まっているとなると、力が発現する特別な条件とかがありそうです」
line = "「そんな稀少な存在が、少なくとも５人も集まっているとなると、力が発現する特別な条件とかがありそうです」"

[[dialogue]]
speaker = "リーリア"
# 「そしてネビュラからも報告です。以前イングリットおよびジュリエッテと遭遇した特殊なアステラから、わずかですが魔力が感じられました」
line = "「そしてネビュラからも報告です。以前イングリットおよびジュリエッテと遭遇した特殊なアステラから、わずかですが魔力が感じられました」"

[[dialogue]]
speaker = "リーリア"
# 「つまり──魔女が関わっている可能性があります」
line = "「つまり──魔女が関わっている可能性があります」"

[[dialogue]]
speaker = "unk"
# 魔女がコラプサー事件に？
line = "魔女がコラプサー事件に？"

[[dialogue]]
speaker = "リーリア"
# 「はい。それもネビュラに属していない、<ruby=ヤーガ>はぐれ魔女</ruby>だと考えられます」
line = "「はい。それもネビュラに属していない、<ruby>はぐれ魔女<rt>ヤーガ</rt></ruby>だと考えられます」"

[[dialogue]]
speaker = "リーリア"
# 「もちろん、センパイのお母様のことじゃないですよ？　あの人がコラプサーに関わる理由がありませんし」
line = "「もちろん、センパイのお母様のことじゃないですよ？　あの人がコラプサーに関わる理由がありませんし」"

[[dialogue]]
speaker = "リーリア"
# 「<ruby=ヤーガ>はぐれ魔女</ruby>の行方はネビュラでも追っているところです。魔女がご迷惑をかけてすみませんが、続報を待っていただければと」
line = "「<ruby>はぐれ魔女<rt>ヤーガ</rt></ruby>の行方はネビュラでも追っているところです。魔女がご迷惑をかけてすみませんが、続報を待っていただければと」"

[[dialogue]]
speaker = "unk"
# わかった。よろしく頼むよ
line = "わかった。よろしく頼むよ"

[[dialogue]]
speaker = "リーリア"
# 「はい、おまかせマジカルです☆」
line = "「はい、おまかせマジカルです☆」"

[[dialogue]]
speaker = "リーリア"
# 「それにしても、星力を吸収しちゃうなんて、コラプサーの能力はほんとチートですよね」
line = "「それにしても、星力を吸収しちゃうなんて、コラプサーの能力はほんとチートですよね」"

[[dialogue]]
speaker = "リーリア"
# 「光だって吸い込んじゃうブラックホールなら、納得といえば納得ですけど。星騎士の天敵とはよく言ったものです」
line = "「光だって吸い込んじゃうブラックホールなら、納得といえば納得ですけど。星騎士の天敵とはよく言ったものです」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ブラックホールがどうとか聞こえましたけど……何かありましたの？」
line = "「ブラックホールがどうとか聞こえましたけど……何かありましたの？」"

[[dialogue]]
speaker = "リーリア"
# 「あ、ヒルディオーネ先輩、こんにちマジカル～☆」
line = "「あ、ヒルディオーネ先輩、こんにちマジカル～☆」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「失礼。聞き耳を立てるつもりはなかったのですけど、気にかかるワードが耳に入ってきたものですから」
line = "「失礼。聞き耳を立てるつもりはなかったのですけど、気にかかるワードが耳に入ってきたものですから」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「光すら吸い込むブラックホール……どのように誕生するのかはご存じ？」
line = "「光すら吸い込むブラックホール……どのように誕生するのかはご存じ？」"

[[dialogue]]
speaker = "unk"
# すみません、あまり詳しくないです
line = "すみません、あまり詳しくないです"

[[dialogue]]
speaker = "リーリア"
# 「星が死んじゃうとなんやかんやでブラックホールになっちゃう……くらいの認識でした」
line = "「星が死んじゃうとなんやかんやでブラックホールになっちゃう……くらいの認識でした」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ええ、死した星の成れの果てという認識で合っていますわ」
line = "「ええ、死した星の成れの果てという認識で合っていますわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「恒星は核融合を繰り返してエネルギーを生み出しますが、その過程でより重い物質が生成されます」
line = "「恒星は核融合を繰り返してエネルギーを生み出しますが、その過程でより重い物質が生成されます」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「この核融合が止まるにつれ、恒星はその自重で収縮していきます。すると引力が強くなり、耐えきれなくなった星が爆発する。これが超新星爆発ですわ」
line = "「この核融合が止まるにつれ、恒星はその自重で収縮していきます。すると引力が強くなり、耐えきれなくなった星が爆発する。これが超新星爆発ですわ」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「しかし、その中でも格別巨大な質量を持つ星は、さらに収縮を続けます」
line = "「しかし、その中でも格別巨大な質量を持つ星は、さらに収縮を続けます」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「そして密度が大きくなり続け……超強力な引力を持つに至ったのがブラックホールですわ」
line = "「そして密度が大きくなり続け……超強力な引力を持つに至ったのがブラックホールですわ」"

[[dialogue]]
speaker = "リーリア"
# 「なんとなくわかりますけど、想像はできないですね……宇宙の話はスケールが大きすぎてピンとこないです」
line = "「なんとなくわかりますけど、想像はできないですね……宇宙の話はスケールが大きすぎてピンとこないです」"

[[dialogue]]
speaker = "リーリア"
# 「でも勉強になりました。さすがヒルディオーネ先輩、天体にマジカル詳しいんですね～☆」
line = "「でも勉強になりました。さすがヒルディオーネ先輩、天体にマジカル詳しいんですね～☆」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「私の千園寺家の事業のひとつとして、宇宙開発がありますから、自然と学びますのよ」
line = "「私の千園寺家の事業のひとつとして、宇宙開発がありますから、自然と学びますのよ」"

[[dialogue]]
speaker = "リーリア"
# 「『千園寺ギャラクティック』ですね。つい先日も無人探査衛星の打ち上げに成功したとか」
line = "「『千園寺ギャラクティック』ですね。つい先日も無人探査衛星の打ち上げに成功したとか」"

[[dialogue]]
speaker = "unk"
# 先輩も五名門の一角だったね
line = "先輩も五名門の一角だったね"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ええ、『人材』を司るヴィーナスさんの『九浄家』、食品を含めた『流通』を得意とするサランさんの『桜十路家』もそうですわ」
line = "「ええ、『人材』を司るヴィーナスさんの『九浄家』、食品を含めた『流通』を得意とするサランさんの『桜十路家』もそうですわ」"

[[dialogue]]
speaker = "リーリア"
# 「『半導体』産業をメインにしていた『<ruby=どうめき>百目騎</ruby>家』は、数年前に本家が没落したそうですけど……」
line = "「『半導体』産業をメインにしていた『<ruby>百目騎<rt>どうめき</rt></ruby>家』は、数年前に本家が没落したそうですけど……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「当家の宇宙開発でも半導体は欠かせない物ですから、当時は衝撃でしたわね」
line = "「当家の宇宙開発でも半導体は欠かせない物ですから、当時は衝撃でしたわね」"

[[dialogue]]
speaker = "リーリア"
# 「みんな気さくなのでふっつう～に接しちゃってますけど、本当ならお近づきになるのも恐れ多い人たちばかりなんですよね～……」
line = "「みんな気さくなのでふっつう～に接しちゃってますけど、本当ならお近づきになるのも恐れ多い人たちばかりなんですよね～……」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「おーっほっほっ、それ程でもありま──あら？　連絡が入っていましたわ」
line = "「おーっほっほっ、それ程でもありま──あら？　連絡が入っていましたわ」"

[[dialogue]]
speaker = "リーリア"
# 「どちらさまからです～？」
line = "「どちらさまからです～？」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「実家からの呼び出しでしたわ。過保護なのも困りものですわね」
line = "「実家からの呼び出しでしたわ。過保護なのも困りものですわね」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「次の機会には美味しい紅茶とお茶菓子で優雅なティータイムにいたしましょう。では、失礼いたしますわ」
line = "「次の機会には美味しい紅茶とお茶菓子で優雅なティータイムにいたしましょう。では、失礼いたしますわ」"

[[dialogue]]
speaker = "リーリア"
# 「は～い、さよならマジカル～☆」
line = "「は～い、さよならマジカル～☆」"

[[dialogue]]
speaker = "リーリア"
# 「それじゃ伝えるべきことは伝えましたし、私たちもここでお開きにしましょうか」
line = "「それじゃ伝えるべきことは伝えましたし、私たちもここでお開きにしましょうか」"

[[dialogue]]
speaker = "リーリア"
# 「センパイ、私がコラプサーに襲われたら、白馬の王子様みたいに助けに来てくださいね♪」
line = "「センパイ、私がコラプサーに襲われたら、白馬の王子様みたいに助けに来てくださいね♪」"

[[dialogue]]
speaker = "unk"
# 馬の被り物でも探しておこうかな
line = "馬の被り物でも探しておこうかな"

[[dialogue]]
speaker = "unk"
# 白馬の王子……ユーリスかな
line = "白馬の王子……ユーリスかな"

[[dialogue]]
speaker = "リーリア"
# 「も～、そこはかっこいいセリフを返してくださいよ～っ」
line = "「も～、そこはかっこいいセリフを返してくださいよ～っ」"

[[dialogue]]
speaker = "unk"
# 最後は軽口を叩き合いつつ、この場はお開きとなったのだった。
line = "最後は軽口を叩き合いつつ、この場はお開きとなったのだった。"
