[[dialogue]]
speaker = "イクシリオン"
# 「新星学園１年、保健委員のイクシリオン・グレゴールです。長い名前なのでイクシーとお呼びください。よろしくお願いします」
line = "「新星学園１年、保健委員のイクシリオン・グレゴールです。長い名前なのでイクシーとお呼びください。よろしくお願いします」"

[[dialogue]]
speaker = "ウィステリア"
# 「よろしく、イクシーさん。紙屋敷さんとはお知り合い？」
line = "「よろしく、イクシーさん。紙屋敷さんとはお知り合い？」"

[[dialogue]]
speaker = "イクシリオン"
# 「はい、私がよく図書館を利用するので、しばしば受付をしていただいています。ちなみに寮も同じです」
line = "「はい、私がよく図書館を利用するので、しばしば受付をしていただいています。ちなみに寮も同じです」"

[[dialogue]]
speaker = "イクシリオン"
# 「それで、図書館の利用者を増やしたいとお聞きしました。さすがモネさん、図書委員の鑑ですね」
line = "「それで、図書館の利用者を増やしたいとお聞きしました。さすがモネさん、図書委員の鑑ですね」"

[[dialogue]]
speaker = "モネ"
# 「いえいえそんな、言い過ぎです」
line = "「いえいえそんな、言い過ぎです」"

[[dialogue]]
speaker = "モネ"
# 「今は図書館に来る人と来ない人の違いを知りたくて、イクシーさんには図書館を利用する側の人のお話を聞きたいんです」
line = "「今は図書館に来る人と来ない人の違いを知りたくて、イクシーさんには図書館を利用する側の人のお話を聞きたいんです」"

[[dialogue]]
speaker = "イクシリオン"
# 「心得ました。私に答えられるものであれば、何でもお聞きください」
line = "「心得ました。私に答えられるものであれば、何でもお聞きください」"

[[dialogue]]
speaker = "モネ"
# 「図書館に来られる人は本を読むか、勉強するかだと思うんですが、イクシーさんは読書されてることが多いですよね。どんな本を読まれていますか？」
line = "「図書館に来られる人は本を読むか、勉強するかだと思うんですが、イクシーさんは読書されてることが多いですよね。どんな本を読まれていますか？」"

[[dialogue]]
speaker = "イクシリオン"
# 「私はいろいろと……小説であったり、先ほどのような美術の本であったり、気分次第ではありますね。知らない言葉を辞書で引くこともあります」
line = "「私はいろいろと……小説であったり、先ほどのような美術の本であったり、気分次第ではありますね。知らない言葉を辞書で引くこともあります」"

[[dialogue]]
speaker = "モネ"
# 「そういえばこの前は……」
line = "「そういえばこの前は……」"

[[dialogue]]
speaker = "イクシリオン"
# 「正常な月経周期は２５日から３８日。変動は６日以内」
line = "「正常な月経周期は２５日から３８日。変動は６日以内」"

[[dialogue]]
speaker = "イクシリオン"
# 「排卵日やその前後には排卵痛が起こることがある。病気ではないが、痛みが強い場合は受診が進められる」
line = "「排卵日やその前後には排卵痛が起こることがある。病気ではないが、痛みが強い場合は受診が進められる」"

[[dialogue]]
speaker = "イクシリオン"
# 「卵子の寿命は排卵後約２４時間と言われ、受精には──」
line = "「卵子の寿命は排卵後約２４時間と言われ、受精には──」"

[[dialogue]]
speaker = "モネ"
# 「って、熱心に性教育の本を読んでいて、さすが保健委員だと思いました」
line = "「って、熱心に性教育の本を読んでいて、さすが保健委員だと思いました」"

[[dialogue]]
speaker = "イクシリオン"
# 「ふぇっ！？　見てたんですか！？」
line = "「ふぇっ！？　見てたんですか！？」"

[[dialogue]]
speaker = "ウィステリア"
# 「そうね。また魔界の話になっちゃうけど、魔界は性教育が十分でないところも多いから、保健委員が女の子の体について詳しいのはいいことだと思うわ」
line = "「そうね。また魔界の話になっちゃうけど、魔界は性教育が十分でないところも多いから、保健委員が女の子の体について詳しいのはいいことだと思うわ」"

[[dialogue]]
speaker = "イクシリオン"
# 「え、ええ……保健委員として復習しておくべきだと思いましたので」
line = "「え、ええ……保健委員として復習しておくべきだと思いましたので」"

[[dialogue]]
speaker = "モネ"
# 「最近読んでよかったと思う本はありますか？」
line = "「最近読んでよかったと思う本はありますか？」"

[[dialogue]]
speaker = "イクシリオン"
# 「人体の本ですね。あんなところやこんなところまで細かに描かれていて、つい食い入るように見てしまいました」
line = "「人体の本ですね。あんなところやこんなところまで細かに描かれていて、つい食い入るように見てしまいました」"

[[dialogue]]
speaker = "イクシリオン"
# 「それと民話の本も。人と妖怪が結ばれて子を成すという内容で、とても興味深かったです」
line = "「それと民話の本も。人と妖怪が結ばれて子を成すという内容で、とても興味深かったです」"

[[dialogue]]
speaker = "モネ"
# 「やはりイクシーさんは多方面に好奇心旺盛なんですね」
line = "「やはりイクシーさんは多方面に好奇心旺盛なんですね」"

[[dialogue]]
speaker = "モネ"
# 「そういえば、イクシーさんは天界出身の天使でしたよね。魔界の図書館事情はウィステリアさんから聞きましたけど、天界の図書館はどうなんでしょう？」
line = "「そういえば、イクシーさんは天界出身の天使でしたよね。魔界の図書館事情はウィステリアさんから聞きましたけど、天界の図書館はどうなんでしょう？」"

[[dialogue]]
speaker = "イクシリオン"
# 「天界はウルという都市に大きな図書館があるのですが、集められているのは学術的な本が中心だそうです」
line = "「天界はウルという都市に大きな図書館があるのですが、集められているのは学術的な本が中心だそうです」"

[[dialogue]]
speaker = "イクシリオン"
# 「それ以外は土地によってまちまちで、蔵書が充実していないところもあれば、図書館自体がないこともあります。天界は人口が少ないので規模が小さくなりがちなのです」
line = "「それ以外は土地によってまちまちで、蔵書が充実していないところもあれば、図書館自体がないこともあります。天界は人口が少ないので規模が小さくなりがちなのです」"

[[dialogue]]
speaker = "イクシリオン"
# 「三界で一番発展しているのは人間界ですから、文芸や趣味の本など、本の種類も含めて人間界の図書館が一番充実していると思います」
line = "「三界で一番発展しているのは人間界ですから、文芸や趣味の本など、本の種類も含めて人間界の図書館が一番充実していると思います」"

[[dialogue]]
speaker = "モネ"
# 「なるほど。確かに天界は真面目そうなイメージがあります」
line = "「なるほど。確かに天界は真面目そうなイメージがあります」"

[[dialogue]]
speaker = "ウィステリア"
# 「そういう意味じゃ、紙屋敷さんは人間界に生まれて良かったわね」
line = "「そういう意味じゃ、紙屋敷さんは人間界に生まれて良かったわね」"

[[dialogue]]
speaker = "モネ"
# 「はい！　いろんな本が読めなかったら、私死んでしまいますよ」
line = "「はい！　いろんな本が読めなかったら、私死んでしまいますよ」"

[[dialogue]]
speaker = "モネ"
# 「でも天界の難しい本も読んでみたいなぁ……」
line = "「でも天界の難しい本も読んでみたいなぁ……」"

[[dialogue]]
speaker = "モネ"
# 「あ、もうひとつ質問です。イクシーさんは図書館の魅力は何だと思いますか？」
line = "「あ、もうひとつ質問です。イクシーさんは図書館の魅力は何だと思いますか？」"

[[dialogue]]
speaker = "イクシリオン"
# 「たくさんの本があること、そしてその本を気軽に手に取ることができることでしょうか」
line = "「たくさんの本があること、そしてその本を気軽に手に取ることができることでしょうか」"

[[dialogue]]
speaker = "イクシリオン"
# 「資金や保管場所の問題もあって、これほど多くの本はいち個人には所有できません」
line = "「資金や保管場所の問題もあって、これほど多くの本はいち個人には所有できません」"

[[dialogue]]
speaker = "イクシリオン"
# 「しかし図書館があれば、お金がなくても、家に書架がなくても、誰でも本に触れることができます。それはとても素晴らしいことだと思います」
line = "「しかし図書館があれば、お金がなくても、家に書架がなくても、誰でも本に触れることができます。それはとても素晴らしいことだと思います」"

[[dialogue]]
speaker = "モネ"
# 「ありがとうございます。イクシーさんのご意見、これからの取り組みに活用させていただきます」
line = "「ありがとうございます。イクシーさんのご意見、これからの取り組みに活用させていただきます」"

[[dialogue]]
speaker = "イクシリオン"
# 「いえいえ、お役に立てたのなら何よりです」
line = "「いえいえ、お役に立てたのなら何よりです」"

[[dialogue]]
speaker = "イクシリオン"
# 「ちなみに、今までは図書館ではどんな取り組みをされていたんですか？」
line = "「ちなみに、今までは図書館ではどんな取り組みをされていたんですか？」"

[[dialogue]]
speaker = "ウィステリア"
# 「そうね、季節行事を特集したり……例えばクリスマスになると、クリスマスの成り立ちを解説した本や、各国のクリスマスの風習を記した本を紹介してるわ」
line = "「そうね、季節行事を特集したり……例えばクリスマスになると、クリスマスの成り立ちを解説した本や、各国のクリスマスの風習を記した本を紹介してるわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「あとはクリスマスの恋愛小説だったり……くっ」
line = "「あとはクリスマスの恋愛小説だったり……くっ」"

[[dialogue]]
speaker = "ウィステリア"
# 「クリスマスに大事な人と過ごすとか、経験ないから……うぅ、自分で言ってて虚しくなってきた……」
line = "「クリスマスに大事な人と過ごすとか、経験ないから……うぅ、自分で言ってて虚しくなってきた……」"

[[dialogue]]
speaker = "イクシリオン"
# 「クリスマスといえば、愛する人と過ごす日……つまり……ムフフフ」
line = "「クリスマスといえば、愛する人と過ごす日……つまり……ムフフフ」"

[[dialogue]]
speaker = "モネ"
# 「あのー……ウィステリアさん？　イクシーさん？　お返事してくださーい」
line = "「あのー……ウィステリアさん？　イクシーさん？　お返事してくださーい」"
