[[dialogue]]
speaker = "unk"
# 第２話,フロンティアドライブ・オーバーロード,B
line = "第２話,フロンティアドライブ・オーバーロード,B"

[[dialogue]]
speaker = "フィオナ"
# 「魔王ラクシスの権能……？　あ──」
line = "「魔王ラクシスの権能……？　あ──」"

[[dialogue]]
speaker = "ヴィーナス"
# 「わかったわ！　フロンティアドライブね！」
line = "「わかったわ！　フロンティアドライブね！」"

[[dialogue]]
speaker = "トリシャ"
# 「その通り……会長さんにフロンティアドライブを使ってもらいます……これで、万事解決……」
line = "「その通り……会長さんにフロンティアドライブを使ってもらいます……これで、万事解決……」"

[[dialogue]]
speaker = "ベアトリス"
# 「フロンティア、ドライブ？　魔王ラクシスの権能は、平行世界を跳躍する力……じゃないんですか？」
line = "「フロンティア、ドライブ？　魔王ラクシスの権能は、平行世界を跳躍する力……じゃないんですか？」"

[[dialogue]]
speaker = "アナ"
# 「それも力の１つですが、ラクシス本来の能力はそれにとどまりません。『平行世界への干渉能力』──それが能力の正体です」
line = "「それも力の１つですが、ラクシス本来の能力はそれにとどまりません。『平行世界への干渉能力』──それが能力の正体です」"

[[dialogue]]
speaker = "マトイ"
# 「前回のフィヴォス流星群……魔神ギエルとの戦いの時に、会長はフロンティアドライブを使って、平行世界に干渉して──」
line = "「前回のフィヴォス流星群……魔神ギエルとの戦いの時に、会長はフロンティアドライブを使って、平行世界に干渉して──」"

[[dialogue]]
speaker = "サーシャ"
# 「ベガとデネブからも星の力を引っ張ってくることができたのよね～。それで私たちも、あの魔神を倒すことができたわ～」
line = "「ベガとデネブからも星の力を引っ張ってくることができたのよね～。それで私たちも、あの魔神を倒すことができたわ～」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……聞けば聞くほどに出鱈目ね。でも、その力があれば──」
line = "「……聞けば聞くほどに出鱈目ね。でも、その力があれば──」"

[[dialogue]]
speaker = "グレイス"
# 「何とかなるかもしれませんねっ！」
line = "「何とかなるかもしれませんねっ！」"

[[dialogue]]
speaker = "クロト"
# 「いや──これだけじゃダメなんだ」
line = "「いや──これだけじゃダメなんだ」"

[[dialogue]]
speaker = "グレイス"
# 「あれぇ！？」
line = "「あれぇ！？」"

[[dialogue]]
speaker = "クロト"
# 「３つの平行世界に干渉して力を集めたとしても、出力が足りない。『星喰らい』の戦闘力……観測数値は、それくらいに絶望的なんだ」
line = "「３つの平行世界に干渉して力を集めたとしても、出力が足りない。『星喰らい』の戦闘力……観測数値は、それくらいに絶望的なんだ」"

[[dialogue]]
speaker = "クロト"
# 「だけど『フロンティアドライブ』は、平行世界の可能性を重ね合わせる能力。だったらその力の影響範囲を、もっと広げればいい」
line = "「だけど『フロンティアドライブ』は、平行世界の可能性を重ね合わせる能力。だったらその力の影響範囲を、もっと広げればいい」"

[[dialogue]]
speaker = "クロト"
# 「無数の世界へアクセスできれば……今まで以上の力だって借りられるはずだ」
line = "「無数の世界へアクセスできれば……今まで以上の力だって借りられるはずだ」"

[[dialogue]]
speaker = "チナ"
# 「いや、ちょっと待てよ。無数の世界って……何言ってるんだよ、魔王」
line = "「いや、ちょっと待てよ。無数の世界って……何言ってるんだよ、魔王」"

[[dialogue]]
speaker = "レティシア"
# 「そうね。デネブ、アルタイル、ベガ──世界はこれだけのはずでしょう？」
line = "「そうね。デネブ、アルタイル、ベガ──世界はこれだけのはずでしょう？」"

[[dialogue]]
speaker = "クロト"
# 「……俺もそう思っていた。だけど、トリシャさんはそうじゃないって言うんだ」
line = "「……俺もそう思っていた。だけど、トリシャさんはそうじゃないって言うんだ」"

[[dialogue]]
speaker = "トリシャ"
# 「はい。あなた方がご存知の、３つの平行世界は……魔王ラクシスが<ruby=レナトゥス>封理再誕</ruby>で生まれ直したことによって、発生したもの……」
line = "「はい。あなた方がご存知の、３つの平行世界は……魔王ラクシスが<ruby>封理再誕<rt>レナトゥス</rt></ruby>で生まれ直したことによって、発生したもの……」"

[[dialogue]]
speaker = "トリシャ"
# 「これを『<ruby=きんじせかい>近似世界</ruby>』と呼びましょう……ですが、このようなイレギュラーがなくとも、そもそも宇宙は無数に枝分かれをしています……」
line = "「これを『<ruby>近似世界<rt>きんじせかい</rt></ruby>』と呼びましょう……ですが、このようなイレギュラーがなくとも、そもそも宇宙は無数に枝分かれをしています……」"

[[dialogue]]
speaker = "グレイス"
# 「そ、そうなのですか！？」
line = "「そ、そうなのですか！？」"

[[dialogue]]
speaker = "トリシャ"
# 「ええ。私の師……メラムから聞いたことがあります。宇宙の可能性は無限大……無数に枝分かれする、可能性という名の『ゆらぎ』の世界……」
line = "「ええ。私の師……メラムから聞いたことがあります。宇宙の可能性は無限大……無数に枝分かれする、可能性という名の『ゆらぎ』の世界……」"

[[dialogue]]
speaker = "トリシャ"
# 「──『<ruby=フラクタル・ワールド>幹内世界</ruby>』。師はそう呼んでいました……」
line = "「──『<ruby>幹内世界<rt>フラクタル・ワールド</rt></ruby>』。師はそう呼んでいました……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「幹内、世界……。近似世界とは違う……？」
line = "「幹内、世界……。近似世界とは違う……？」"

[[dialogue]]
speaker = "トリシャ"
# 「はい。私たちが今いるこのアルタイルを、１本の樹……巨大な幹だと、考えてください……」
line = "「はい。私たちが今いるこのアルタイルを、１本の樹……巨大な幹だと、考えてください……」"

[[dialogue]]
speaker = "トリシャ"
# 「その幹には、いくつもの枝葉が付きます……ですがどの枝も、幹と繋がった、同じ樹の『可能性の一部』……同じアルタイルの中の『ゆらぎ』でしかない……」
line = "「その幹には、いくつもの枝葉が付きます……ですがどの枝も、幹と繋がった、同じ樹の『可能性の一部』……同じアルタイルの中の『ゆらぎ』でしかない……」"

[[dialogue]]
speaker = "ベアトリス"
# 「……？？？」
line = "「……？？？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……平行世界には、管理者である神すらも異なる、異世界と言っても過言ではない、『遠い世界』が存在するわ」
line = "「……平行世界には、管理者である神すらも異なる、異世界と言っても過言ではない、『遠い世界』が存在するわ」"

[[dialogue]]
speaker = "ルヴィネ"
# 「一方で、デネブ、アルタイル、ベガの３つは、元々同じ幹から派生した『近似世界』。だからこそ不自然であるし、管理する神は同一だった」
line = "「一方で、デネブ、アルタイル、ベガの３つは、元々同じ幹から派生した『近似世界』。だからこそ不自然であるし、管理する神は同一だった」"

[[dialogue]]
speaker = "ルヴィネ"
# 「『<ruby=フラクタル・ワールド>幹内世界</ruby>』は、それよりもさらに近い。同じアルタイルの中にある、『起こったかもしれない、ゆらぎの世界』ということね？」
line = "「『<ruby>幹内世界<rt>フラクタル・ワールド</rt></ruby>』は、それよりもさらに近い。同じアルタイルの中にある、『起こったかもしれない、ゆらぎの世界』ということね？」"

[[dialogue]]
speaker = "ルヴィネ"
# 「私たちが観測しなかったところに『あったかもしれない世界』。観測しなければ、やがて同じ歴史に紛れて溶けてしまう、無数の可能性の束──」
line = "「私たちが観測しなかったところに『あったかもしれない世界』。観測しなければ、やがて同じ歴史に紛れて溶けてしまう、無数の可能性の束──」"

[[dialogue]]
speaker = "トリシャ"
# 「その通りです……フフフ。ルヴィネさん……あなたは理解が早いですね……」
line = "「その通りです……フフフ。ルヴィネさん……あなたは理解が早いですね……」"

[[dialogue]]
speaker = "トリシャ"
# 「幹内世界の数は、数え切ることは不可能です……それほどまでに、高次元宇宙というものは、膨大……」
line = "「幹内世界の数は、数え切ることは不可能です……それほどまでに、高次元宇宙というものは、膨大……」"

[[dialogue]]
speaker = "トリシャ"
# 「数多の枝葉の世界から、あなた方の同一存在に会長さんがアクセス……そこから技能、戦闘経験、星力……それら全てを、借りるのです……」
line = "「数多の枝葉の世界から、あなた方の同一存在に会長さんがアクセス……そこから技能、戦闘経験、星力……それら全てを、借りるのです……」"

[[dialogue]]
speaker = "トリシャ"
# 「<ruby=フラクタル・ワールド>幹内世界</ruby>には、今より未来のあなた方もいるかも……今ここにいるあなた方が目覚めていない、戦う力を持っているかもしれません……」
line = "「<ruby>幹内世界<rt>フラクタル・ワールド</rt></ruby>には、今より未来のあなた方もいるかも……今ここにいるあなた方が目覚めていない、戦う力を持っているかもしれません……」"

[[dialogue]]
speaker = "ユウリ"
# 「め、めちゃくちゃなことを言ってるように聞こえるけどよ……要するに、パワーアップできるってことだよな？」
line = "「め、めちゃくちゃなことを言ってるように聞こえるけどよ……要するに、パワーアップできるってことだよな？」"

[[dialogue]]
speaker = "クロト"
# 「そのくらい雑に噛み砕いてくれて大丈夫だ」
line = "「そのくらい雑に噛み砕いてくれて大丈夫だ」"

[[dialogue]]
speaker = "ルリエル"
# 「つまりどこかの<ruby=フラクタル・ワールド>幹内世界</ruby>には、スーパーモードのルリエルがいるかもってことですねっ！」
line = "「つまりどこかの<ruby>幹内世界<rt>フラクタル・ワールド</rt></ruby>には、スーパーモードのルリエルがいるかもってことですねっ！」"

[[dialogue]]
speaker = "クロト"
# 「ああ。ルリエルの持っていない戦闘服だって、<ruby=フラクタル・ワールド>幹内世界</ruby>の同一存在から借りられるかもしれない」
line = "「ああ。ルリエルの持っていない戦闘服だって、<ruby>幹内世界<rt>フラクタル・ワールド</rt></ruby>の同一存在から借りられるかもしれない」"

[[dialogue]]
speaker = "チナ"
# 「す──すげぇな。流石は旧森羅歴でリクリエを食い止めた英雄……イカれた能力だ！！」
line = "「す──すげぇな。流石は旧森羅歴でリクリエを食い止めた英雄……イカれた能力だ！！」"

[[dialogue]]
speaker = "クロト"
# 「ここまで大がかりなフロンティアドライブは、俺１人じゃ無理だ。あくまで『ベガの俺』の助力がある間だけの、限定的な奇蹟……」
line = "「ここまで大がかりなフロンティアドライブは、俺１人じゃ無理だ。あくまで『ベガの俺』の助力がある間だけの、限定的な奇蹟……」"

[[dialogue]]
speaker = "クロト"
# 「<ruby=オーバーロード>過負荷</ruby>をかけたフロンティアドライブを使えるのは、今だけ──だからこそ、『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』を討つ機会は逃せない」
line = "「<ruby>過負荷<rt>オーバーロード</rt></ruby>をかけたフロンティアドライブを使えるのは、今だけ──だからこそ、『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』を討つ機会は逃せない」"

[[dialogue]]
speaker = "ルヴィネ"
# 「フロンティアドライブ・オーバーロード……試してみる価値はありそうね」
line = "「フロンティアドライブ・オーバーロード……試してみる価値はありそうね」"

[[dialogue]]
speaker = "クロト"
# 「みんなに頼りきりで悪いと思っている……でも『星喰らい』の活動は、ベガ内で弱体化した俺では止められない」
line = "「みんなに頼りきりで悪いと思っている……でも『星喰らい』の活動は、ベガ内で弱体化した俺では止められない」"

[[dialogue]]
speaker = "クロト"
# 「星喰らいさえ止められたら……『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』の相手は俺がする。みんな、力を貸してくれるか？」
line = "「星喰らいさえ止められたら……『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』の相手は俺がする。みんな、力を貸してくれるか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「もちろんよ！　そのフラフラワールドでパワーアップできるんでしょ！　だったらいけるわ！」
line = "「もちろんよ！　そのフラフラワールドでパワーアップできるんでしょ！　だったらいけるわ！」"

[[dialogue]]
speaker = "フィオナ"
# 「問題ありません。緋宮会長が『ディザスターハンド』の力を行使できるよう──５人の星喰らいの活動は、私たちが止めてみせます！」
line = "「問題ありません。緋宮会長が『ディザスターハンド』の力を行使できるよう──５人の星喰らいの活動は、私たちが止めてみせます！」"

[[dialogue]]
speaker = "unk"
# ──ヴィーナスやフィオナたちだけではない。
line = "──ヴィーナスやフィオナたちだけではない。"

[[dialogue]]
speaker = "unk"
# その場のみんなが、頷いてくれた。
line = "その場のみんなが、頷いてくれた。"

[[dialogue]]
speaker = "unk"
# 確実な保証なんてどこにもないというのに、俺の作戦を信じ、命を預けてくれた──
line = "確実な保証なんてどこにもないというのに、俺の作戦を信じ、命を預けてくれた──"

[[dialogue]]
speaker = "クロト"
# 「……ありがとう。俺はアルタイルの九浄家に残って、フロンティアドライブの維持に専念する」
line = "「……ありがとう。俺はアルタイルの九浄家に残って、フロンティアドライブの維持に専念する」"

[[dialogue]]
speaker = "クロト"
# 「みんなは精鋭の星騎士を５チームにわけて、ベガの一次攻略に当たって欲しい」
line = "「みんなは精鋭の星騎士を５チームにわけて、ベガの一次攻略に当たって欲しい」"

[[dialogue]]
speaker = "ソフィア"
# 「──待ってください。肝心の『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』の居場所は、どうやって捕捉するのですか？」
line = "「──待ってください。肝心の『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』の居場所は、どうやって捕捉するのですか？」"

[[dialogue]]
speaker = "クロト"
# 「それについては、梨緒とジグにお願いするつもりだ」
line = "「それについては、梨緒とジグにお願いするつもりだ」"

[[dialogue]]
speaker = "梨緒"
# 「……私たちに？」
line = "「……私たちに？」"

[[dialogue]]
speaker = "クロト"
# 「ああ。ベガ世界で『星喰らい』を撃破するたびに──身を隠している『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』本体に送っていた霊力の流れが乱れるはずだ」
line = "「ああ。ベガ世界で『星喰らい』を撃破するたびに──身を隠している『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』本体に送っていた霊力の流れが乱れるはずだ」"

[[dialogue]]
speaker = "クロト"
# 「その因果の流れを梨緒に辿ってもらう。そうすれば──」
line = "「その因果の流れを梨緒に辿ってもらう。そうすれば──」"

[[dialogue]]
speaker = "ジグ"
# 「……なるほど。因果の流れを補足するたびにアガサの『これから取る行動』が変わる。そうなれば──」
line = "「……なるほど。因果の流れを補足するたびにアガサの『これから取る行動』が変わる。そうなれば──」"

[[dialogue]]
speaker = "梨緒"
# 「ジグの、天機の星眼で見える未来も変わる、ということか」
line = "「ジグの、天機の星眼で見える未来も変わる、ということか」"

[[dialogue]]
speaker = "クロト"
# 「そういうことだ。梨緒たちはアルタイルに残って、各地での戦況報告を俺と一緒に受け取って欲しい」
line = "「そういうことだ。梨緒たちはアルタイルに残って、各地での戦況報告を俺と一緒に受け取って欲しい」"

[[dialogue]]
speaker = "ジグ"
# 「酷い作戦だね。まだ本調子じゃない私に、星眼を短時間で５回も使用しろだなんて」
line = "「酷い作戦だね。まだ本調子じゃない私に、星眼を短時間で５回も使用しろだなんて」"

[[dialogue]]
speaker = "クロト"
# 「……すまない、ジグ」
line = "「……すまない、ジグ」"

[[dialogue]]
speaker = "ジグ"
# 「──なんてね、言ってみただけさ。もちろん付き合うとも。創造神の息の根を止められるなら、擦り切れるまで星眼を酷使しようじゃないか」
line = "「──なんてね、言ってみただけさ。もちろん付き合うとも。創造神の息の根を止められるなら、擦り切れるまで星眼を酷使しようじゃないか」"

[[dialogue]]
speaker = "梨緒"
# 「……だが魔王、まだ懸念はあるぞ。ベガにひしめく、１００万のシャドウたちの相手は？」
line = "「……だが魔王、まだ懸念はあるぞ。ベガにひしめく、１００万のシャドウたちの相手は？」"

[[dialogue]]
speaker = "セイファート"
# 「案ずるな。シャドウたちの相手……その陣頭指揮は、私が取ろう」
line = "「案ずるな。シャドウたちの相手……その陣頭指揮は、私が取ろう」"

[[dialogue]]
speaker = "セイファート"
# 「元よりそのつもりで、私をデネブから呼んだのだろう、少年？」
line = "「元よりそのつもりで、私をデネブから呼んだのだろう、少年？」"

[[dialogue]]
speaker = "クロト"
# 「……はい、セイファート学園長」
line = "「……はい、セイファート学園長」"

[[dialogue]]
speaker = "セイファート"
# 「『星喰らい』戦の選抜から漏れた者たちを連れて行く。此度の露払いは、任せてもらおうか」
line = "「『星喰らい』戦の選抜から漏れた者たちを連れて行く。此度の露払いは、任せてもらおうか」"

[[dialogue]]
speaker = "クロト"
# 「ありがとうございます……！」
line = "「ありがとうございます……！」"

[[dialogue]]
speaker = "unk"
# ──話はまとまった。
line = "──話はまとまった。"

[[dialogue]]
speaker = "unk"
# ならば、後は机上の空論を顕現させることに集中しよう。
line = "ならば、後は机上の空論を顕現させることに集中しよう。"

[[dialogue]]
speaker = "クロト"
# 「みんな──今から『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』討伐の最終作戦を始める！」
line = "「みんな──今から『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』討伐の最終作戦を始める！」"

[[dialogue]]
speaker = "フィオナ"
# 「──はい！」
line = "「──はい！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「クロト、お願い！！」
line = "「クロト、お願い！！」"

[[dialogue]]
speaker = "クロト"
# 「<ruby=フラクタル・ワールド>幹内世界</ruby>のみんなから力を借り受ける……今だけの奇蹟を、ここに集約する！」
line = "「<ruby>幹内世界<rt>フラクタル・ワールド</rt></ruby>のみんなから力を借り受ける……今だけの奇蹟を、ここに集約する！」"

[[dialogue]]
speaker = "クロト"
# 「フロンティアドライブ──オーバーロード！！！」
line = "「フロンティアドライブ──オーバーロード！！！」"
