[[dialogue]]
speaker = "カティア"
# 「それで魔王様、早速調査に向かいますか？」
line = "「それで魔王様、早速調査に向かいますか？」"

[[dialogue]]
speaker = "unk"
# もう少し情報が欲しいかな
line = "もう少し情報が欲しいかな"

[[dialogue]]
speaker = "カティア"
# 「魔王様の言う通り、今のままだと少々情報不足ですね……」
line = "「魔王様の言う通り、今のままだと少々情報不足ですね……」"

[[dialogue]]
speaker = "カティア"
# 「しかしコラプサーは私たちと同じく星術を使っていると聞きました。なら星術に詳しいトワちゃん先生に聞いてみましょう」
line = "「しかしコラプサーは私たちと同じく星術を使っていると聞きました。なら星術に詳しいトワちゃん先生に聞いてみましょう」"

[[dialogue]]
speaker = "カティア"
# 「トワちゃん先生なら何かわかったことがあるかもしれませんし」
line = "「トワちゃん先生なら何かわかったことがあるかもしれませんし」"

[[dialogue]]
speaker = "unk"
# 行ってみようか
line = "行ってみようか"

[[dialogue]]
speaker = "カティア"
# 「はい！　魔王様！」
line = "「はい！　魔王様！」"

[[dialogue]]
speaker = "カティア"
# 「トワちゃん先生～聞きたいことがあるんですけど～」
line = "「トワちゃん先生～聞きたいことがあるんですけど～」"

[[dialogue]]
speaker = "トワ先生"
# 「カティアちゃんに会長くん？　急にどうしたの？」
line = "「カティアちゃんに会長くん？　急にどうしたの？」"

[[dialogue]]
speaker = "エスメラルダ"
# 「私たちに何か用かしら？」
line = "「私たちに何か用かしら？」"

[[dialogue]]
speaker = "カティア"
# 「流星のエスメラルダ先生まで……！　初めまして、新星１年のカティアです！」
line = "「流星のエスメラルダ先生まで……！　初めまして、新星１年のカティアです！」"

[[dialogue]]
speaker = "エスメラルダ"
# 「ご丁寧にどうも。流星学園教師のエスメラルダよ……って私のことは知っているみたいね」
line = "「ご丁寧にどうも。流星学園教師のエスメラルダよ……って私のことは知っているみたいね」"

[[dialogue]]
speaker = "トワ先生"
# 「エスメラルダ先生は新星でも有名人ですからね」
line = "「エスメラルダ先生は新星でも有名人ですからね」"

[[dialogue]]
speaker = "エスメラルダ"
# 「ふふ……そういうトワちゃん先生も流星では有名ですよ」
line = "「ふふ……そういうトワちゃん先生も流星では有名ですよ」"

[[dialogue]]
speaker = "unk"
# 星騎士襲撃事件について聞きたいんですが
line = "星騎士襲撃事件について聞きたいんですが"

[[dialogue]]
speaker = "トワ先生"
# 「会長くんたちも例の事件を調査してるんだね。私たちもちょうどその話をしてたところなんだ」
line = "「会長くんたちも例の事件を調査してるんだね。私たちもちょうどその話をしてたところなんだ」"

[[dialogue]]
speaker = "カティア"
# 「おお、これは期待できますね魔王様！　それで何かわかったことはありますか？」
line = "「おお、これは期待できますね魔王様！　それで何かわかったことはありますか？」"

[[dialogue]]
speaker = "トワ先生"
# 「うーん……わからないことがわかった、って感じかな」
line = "「うーん……わからないことがわかった、って感じかな」"

[[dialogue]]
speaker = "カティア"
# 「へ？　どういうことなんです？」
line = "「へ？　どういうことなんです？」"

[[dialogue]]
speaker = "エスメラルダ"
# 「会長さんたちも薄々感づいているとは思うけど、犯人はコラプサーの可能性が高いわ」
line = "「会長さんたちも薄々感づいているとは思うけど、犯人はコラプサーの可能性が高いわ」"

[[dialogue]]
speaker = "カティア"
# 「やっぱり、コラプサー……！」
line = "「やっぱり、コラプサー……！」"

[[dialogue]]
speaker = "エスメラルダ"
# 「ええ、事件現場の観測を行った結果、過去のコラプサー事件と酷似した数値が検出されたの」
line = "「ええ、事件現場の観測を行った結果、過去のコラプサー事件と酷似した数値が検出されたの」"

[[dialogue]]
speaker = "エスメラルダ"
# 「もっと言うと、星術を使った痕跡はあるのに、星力は検出されない……そんな感じね」
line = "「もっと言うと、星術を使った痕跡はあるのに、星力は検出されない……そんな感じね」"

[[dialogue]]
speaker = "カティア"
# 「あるのにない？　ていうかコラプサーは星術を使ってるんじゃ……？　魔王様～、私の頭じゃよくわかりませんガオ～」
line = "「あるのにない？　ていうかコラプサーは星術を使ってるんじゃ……？　魔王様～、私の頭じゃよくわかりませんガオ～」"

[[dialogue]]
speaker = "unk"
# 大丈夫、俺もわかってないから
line = "大丈夫、俺もわかってないから"

[[dialogue]]
speaker = "エスメラルダ"
# 「ふふ、今の説明じゃわからなくて当然よね」
line = "「ふふ、今の説明じゃわからなくて当然よね」"

[[dialogue]]
speaker = "トワ先生"
# 「コラプサーが使う星力は、私たちが使っているのとは違う……負の星力とでも言うべきものなの。それに彼女たちの守護星も観測できてなくて」
line = "「コラプサーが使う星力は、私たちが使っているのとは違う……負の星力とでも言うべきものなの。それに彼女たちの守護星も観測できてなくて」"

[[dialogue]]
speaker = "カティア"
# 「？？？　守護星がないのに、星力を使えるってことです……？」
line = "「？？？　守護星がないのに、星力を使えるってことです……？」"

[[dialogue]]
speaker = "トワ先生"
# 「ううん。守護星は確実に<b>ある</b>はずなの……だけど、数値がちゃんと出ないんだ」
line = "「ううん。守護星は確実に<b>ある</b>はずなの……だけど、数値がちゃんと出ないんだ」"

[[dialogue]]
speaker = "カティア"
# 「数値が出ない？　観測できない守護星なんてあるんですか？　私の守護星なんてちっぽけな衛星でもわかったのに」
line = "「数値が出ない？　観測できない守護星なんてあるんですか？　私の守護星なんてちっぽけな衛星でもわかったのに」"

[[dialogue]]
speaker = "エスメラルダ"
# 「星力がほんの少しだとわからない場合もあるけど、守護星である以上、普通は特定できるわ」
line = "「星力がほんの少しだとわからない場合もあるけど、守護星である以上、普通は特定できるわ」"

[[dialogue]]
speaker = "トワ先生"
# 「だから守護星が観測出来ないのは、コラプサーの能力なのかもしれない」
line = "「だから守護星が観測出来ないのは、コラプサーの能力なのかもしれない」"

[[dialogue]]
speaker = "エスメラルダ"
# 「もしくは、よほど<b>特別な</b>守護星を持っているか、ね」
line = "「もしくは、よほど<b>特別な</b>守護星を持っているか、ね」"

[[dialogue]]
speaker = "カティア"
# 「わからないのにある……あるのにない……ガウ～、考えれば考えるほど頭がこんがらがってきますよ」
line = "「わからないのにある……あるのにない……ガウ～、考えれば考えるほど頭がこんがらがってきますよ」"

[[dialogue]]
speaker = "unk"
# でもヒントになるかもしれません
line = "でもヒントになるかもしれません"

[[dialogue]]
speaker = "エスメラルダ"
# 「だといいわね。コラプサーはとても危険な相手だから気を付けてね」
line = "「だといいわね。コラプサーはとても危険な相手だから気を付けてね」"

[[dialogue]]
speaker = "トワ先生"
# 「会長くんはともかく、カティアちゃんは大丈夫？　危なくなる前に逃げるんだよ？」
line = "「会長くんはともかく、カティアちゃんは大丈夫？　危なくなる前に逃げるんだよ？」"

[[dialogue]]
speaker = "カティア"
# 「言われなくてもわかってますワンっ」
line = "「言われなくてもわかってますワンっ」"

[[dialogue]]
speaker = "カティア"
# 「それじゃ、情報ありがとうございました！　行ってきます！」
line = "「それじゃ、情報ありがとうございました！　行ってきます！」"

[[dialogue]]
speaker = "カティア"
# 「さてさて魔王様、情報は集めましたし、次は調査に向かいましょう！」
line = "「さてさて魔王様、情報は集めましたし、次は調査に向かいましょう！」"

[[dialogue]]
speaker = "カティア"
# 「まずは事件現場にでも行きます？　犯人は現場に戻るとも言いますし……！」
line = "「まずは事件現場にでも行きます？　犯人は現場に戻るとも言いますし……！」"

[[dialogue]]
speaker = "カティア"
# 「このカティア刑事、華麗に事件を解決してみせますワン！」
line = "「このカティア刑事、華麗に事件を解決してみせますワン！」"

[[dialogue]]
speaker = "unk"
# 頼りにしてるよ
line = "頼りにしてるよ"

[[dialogue]]
speaker = "カティア"
# 「はいワン！　行きましょう魔王様！」
line = "「はいワン！　行きましょう魔王様！」"
