[[dialogue]]
speaker = "エリス"
# 「きゃああああああッ！！」
line = "「きゃああああああッ！！」"

[[dialogue]]
speaker = "？？？"
# 「んだよ、呆気ねえな。星騎士ってのはこの程度かよ。拍子抜けもいいところだぜ」
line = "「んだよ、呆気ねえな。星騎士ってのはこの程度かよ。拍子抜けもいいところだぜ」"

[[dialogue]]
speaker = "？？？"
# 「星騎士は正義の味方なんじゃなかったのか？　そのザマで何が守れるっつうんだよ」
line = "「星騎士は正義の味方なんじゃなかったのか？　そのザマで何が守れるっつうんだよ」"

[[dialogue]]
speaker = "エリス"
# 「くっ……！　はぁあああっ！！」
line = "「くっ……！　はぁあああっ！！」"

[[dialogue]]
speaker = "？？？"
# 「フン。効かねえよ」
line = "「フン。効かねえよ」"

[[dialogue]]
speaker = "エリス"
# 「ボルテクス・オラージュ！」
line = "「ボルテクス・オラージュ！」"

[[dialogue]]
speaker = "？？？"
# 「だから効かねえって──」
line = "「だから効かねえって──」"

[[dialogue]]
speaker = "エリス"
# 「皆さん逃げてくださいっ！」
line = "「皆さん逃げてくださいっ！」"

[[dialogue]]
speaker = "？？？"
# 「チッ、目眩ましか。正義の味方のくせにずいぶん姑息なマネすんじゃねえか……」
line = "「チッ、目眩ましか。正義の味方のくせにずいぶん姑息なマネすんじゃねえか……」"

[[dialogue]]
speaker = "エリス"
# 「はぁはぁ、皆さんに伝え、ないと……！　危険な、敵が──……」
line = "「はぁはぁ、皆さんに伝え、ないと……！　危険な、敵が──……」"

[[dialogue]]
speaker = "unk"
# エリスが襲われたって！？
line = "エリスが襲われたって！？"

[[dialogue]]
speaker = "フィオナ"
# 「はい、昨夜何者かに……」
line = "「はい、昨夜何者かに……」"

[[dialogue]]
speaker = "フィオナ"
# 「正確には、他の星騎士が襲われていたところに偶然居合わせて、助けに入ったそうです。そしてその星騎士を逃がそうとして負傷を……」
line = "「正確には、他の星騎士が襲われていたところに偶然居合わせて、助けに入ったそうです。そしてその星騎士を逃がそうとして負傷を……」"

[[dialogue]]
speaker = "エリス"
# 「詳しくは、私から話しま……ぐっ！」
line = "「詳しくは、私から話しま……ぐっ！」"

[[dialogue]]
speaker = "フィオナ"
# 「あっ、まだ起き上がらないでください」
line = "「あっ、まだ起き上がらないでください」"

[[dialogue]]
speaker = "unk"
# エリスをここまで追い詰めるなんて……
line = "エリスをここまで追い詰めるなんて……"

[[dialogue]]
speaker = "ミア"
# 「ええ。どうやら相手は相当の手練れみたいね」
line = "「ええ。どうやら相手は相当の手練れみたいね」"

[[dialogue]]
speaker = "ミア"
# 「だけど臆するわけにはいかないわ！　<ruby=てんもうかいかい>天網恢々</ruby><ruby=そ>疎</ruby>にして漏らさず──風紀委員の威信にかけて、必ず取っ捕まえてやるんだから！」
line = "「だけど臆するわけにはいかないわ！　<ruby>天網恢々<rt>てんもうかいかい</rt></ruby><ruby>疎<rt>そ</rt></ruby>にして漏らさず──風紀委員の威信にかけて、必ず取っ捕まえてやるんだから！」"

[[dialogue]]
speaker = "unk"
# 附属生？
line = "附属生？"

[[dialogue]]
speaker = "ミア"
# 「だーかーらー！　私は附属生じゃないもん！　<ruby=れっき>歴</ruby>とした新星学園の一年生！　風紀委員の<ruby=ゆりさき>百合崎</ruby>ミア！」
line = "「だーかーらー！　私は附属生じゃないもん！　<ruby>歴<rt>れっき</rt></ruby>とした新星学園の一年生！　風紀委員の<ruby>百合崎<rt>ゆりさき</rt></ruby>ミア！」"

[[dialogue]]
speaker = "ミア"
# 「何度同じ間違いをしたら気が済むのっ。ちょっぴり見た目が幼いからって子ども扱いしないでもらえるっ？」
line = "「何度同じ間違いをしたら気が済むのっ。ちょっぴり見た目が幼いからって子ども扱いしないでもらえるっ？」"

[[dialogue]]
speaker = "エリス"
# 「まぁまぁ。お見舞いのお菓子でよければどうぞ」
line = "「まぁまぁ。お見舞いのお菓子でよければどうぞ」"

[[dialogue]]
speaker = "ミア"
# 「これ、有名店のクッキー……！　えへへ、バターたっぷりで美味しい……」
line = "「これ、有名店のクッキー……！　えへへ、バターたっぷりで美味しい……」"

[[dialogue]]
speaker = "ミア"
# 「じゃなくて！　私は新星学園の風紀委員代表として、エリス先輩のお見舞いと聞き取り調査に来たのっ！！」
line = "「じゃなくて！　私は新星学園の風紀委員代表として、エリス先輩のお見舞いと聞き取り調査に来たのっ！！」"

[[dialogue]]
speaker = "ミア"
# 「大丈夫ですか、エリス先輩？　手酷くやられちゃったって聞きましたけど……」
line = "「大丈夫ですか、エリス先輩？　手酷くやられちゃったって聞きましたけど……」"

[[dialogue]]
speaker = "エリス"
# 「ええ、なんとか。幸い深手は負っていませんので、しばらく休めば復帰できると思います」
line = "「ええ、なんとか。幸い深手は負っていませんので、しばらく休めば復帰できると思います」"

[[dialogue]]
speaker = "ミア"
# 「エリス先輩はいつも頑張っているんですから、無理せず休んでください。後は私が引き継ぎますから」
line = "「エリス先輩はいつも頑張っているんですから、無理せず休んでください。後は私が引き継ぎますから」"

[[dialogue]]
speaker = "ミア"
# 「二葉にして絶たざれば斧を持ちうるに至るって言いますしね。悪の芽は早めに摘んでおかなきゃですよ」
line = "「二葉にして絶たざれば斧を持ちうるに至るって言いますしね。悪の芽は早めに摘んでおかなきゃですよ」"

[[dialogue]]
speaker = "エリス"
# 「ふた……？　ええと、すみません。この国のことわざには疎くて……」
line = "「ふた……？　ええと、すみません。この国のことわざには疎くて……」"

[[dialogue]]
speaker = "ミア"
# 「木は芽のうちに取り除かないと、後で斧を使って切り倒さなくてはいけなくなる。災いは小さいうちに除かないと、後が大変という意味です」
line = "「木は芽のうちに取り除かないと、後で斧を使って切り倒さなくてはいけなくなる。災いは小さいうちに除かないと、後が大変という意味です」"

[[dialogue]]
speaker = "エリス"
# 「なるほど、勉強になりました。確かにミアさんの言う通り、早急に対処しなければ」
line = "「なるほど、勉強になりました。確かにミアさんの言う通り、早急に対処しなければ」"

[[dialogue]]
speaker = "unk"
# 犯人の特徴は？
line = "犯人の特徴は？"

[[dialogue]]
speaker = "エリス"
# 「私たちに近い年頃の女の子のようでした。ネコ科のような耳と尻尾があったので、恐らく獣人系の魔族の方かと」
line = "「私たちに近い年頃の女の子のようでした。ネコ科のような耳と尻尾があったので、恐らく獣人系の魔族の方かと」"

[[dialogue]]
speaker = "ミア"
# 「ふむふむ。同じ年代で魔族ということは、学園の生徒でしょうか」
line = "「ふむふむ。同じ年代で魔族ということは、学園の生徒でしょうか」"

[[dialogue]]
speaker = "ミア"
# 「星術で暴力を働く生徒を取り締まるのは風紀委員の務め。早速捕縛に行ってきます！」
line = "「星術で暴力を働く生徒を取り締まるのは風紀委員の務め。早速捕縛に行ってきます！」"

[[dialogue]]
speaker = "エリス"
# 「待ってください、単独行動は危険です。悔しいですが、私ですら手も足も出なかった相手ですから……」
line = "「待ってください、単独行動は危険です。悔しいですが、私ですら手も足も出なかった相手ですから……」"

[[dialogue]]
speaker = "ミア"
# 「私ですらってどういう意味ですか。私だってやれます……！　ちんちくりんだからって見くびらないでください……！」
line = "「私ですらってどういう意味ですか。私だってやれます……！　ちんちくりんだからって見くびらないでください……！」"

[[dialogue]]
speaker = "エリス"
# 「い、いえ。見くびっているわけでは──」
line = "「い、いえ。見くびっているわけでは──」"

[[dialogue]]
speaker = "ミア"
# 「とにかく大丈夫ったら大丈夫です！　エリス先輩が苦戦した相手をあっという間に捕まえて、今こそ私の実力を証明してみせますから！」
line = "「とにかく大丈夫ったら大丈夫です！　エリス先輩が苦戦した相手をあっという間に捕まえて、今こそ私の実力を証明してみせますから！」"

[[dialogue]]
speaker = "エリス"
# 「あっ、ミアさ──……行ってしまいました」
line = "「あっ、ミアさ──……行ってしまいました」"

[[dialogue]]
speaker = "unk"
# 俺が追いかけるよ
line = "俺が追いかけるよ"

[[dialogue]]
speaker = "エリス"
# 「会長さんが一緒なら安心ですね。よろしくお願いします」
line = "「会長さんが一緒なら安心ですね。よろしくお願いします」"

[[dialogue]]
speaker = "フィオナ"
# 「両校の風紀委員たちもパトロールを行うそうです。２人以上──いえ、念のため３人以上で行動することを徹底させましょう」
line = "「両校の風紀委員たちもパトロールを行うそうです。２人以上──いえ、念のため３人以上で行動することを徹底させましょう」"

[[dialogue]]
speaker = "エリス"
# 「ありがとうございます」
line = "「ありがとうございます」"

[[dialogue]]
speaker = "エリス"
# 「敗れた私が言うのもなんですが……いえ、力及ばなかった私だから言えます。相手は今までにない強敵です。くれぐれも気を付けてください」
line = "「敗れた私が言うのもなんですが……いえ、力及ばなかった私だから言えます。相手は今までにない強敵です。くれぐれも気を付けてください」"
