[[dialogue]]
speaker = "unk"
# アーネストのライブが、白紙に……！？
line = "アーネストのライブが、白紙に……！？"

[[dialogue]]
speaker = "レミカ"
# 「……ごめん。昨日の夜に……ポラリスプロダクションの社長から連絡があって……」
line = "「……ごめん。昨日の夜に……ポラリスプロダクションの社長から連絡があって……」"

[[dialogue]]
speaker = "レミカ"
# 「詳しい話を聞いたら、つい最近、別の芸能事務所で似たようなライブがあったみたい」
line = "「詳しい話を聞いたら、つい最近、別の芸能事務所で似たようなライブがあったみたい」"

[[dialogue]]
speaker = "レミカ"
# 「要するに、『カワイイ』系のアイドルが、一度もやったことのない『クール』系の路線でライブにチャレンジしたらしくて……」
line = "「要するに、『カワイイ』系のアイドルが、一度もやったことのない『クール』系の路線でライブにチャレンジしたらしくて……」"

[[dialogue]]
speaker = "レミカ"
# 「その人のライブ、思いっきり大コケしちゃったみたい。今ＳＮＳでお祭りみたいに炎上してて……」
line = "「その人のライブ、思いっきり大コケしちゃったみたい。今ＳＮＳでお祭りみたいに炎上してて……」"

[[dialogue]]
speaker = "レミカ"
# 「こんなライブ見たくなかった。誰得なんだよこれ──みたいなのがずら～っと並んでるみたい……」
line = "「こんなライブ見たくなかった。誰得なんだよこれ──みたいなのがずら～っと並んでるみたい……」"

[[dialogue]]
speaker = "レミカ"
# 「社長、完全にびびっちゃってさ。稼ぎ頭の私に大コケされたら困るからって……予定してた会場も全部白紙。キャンセルされちゃった」
line = "「社長、完全にびびっちゃってさ。稼ぎ頭の私に大コケされたら困るからって……予定してた会場も全部白紙。キャンセルされちゃった」"

[[dialogue]]
speaker = "レミカ"
# 「私がしたいだけならゲリラのライブもありなんだろうけど……今まで本当に、すごくよくしてくれた社長だから……裏切れないし……」
line = "「私がしたいだけならゲリラのライブもありなんだろうけど……今まで本当に、すごくよくしてくれた社長だから……裏切れないし……」"

[[dialogue]]
speaker = "メルエル"
# 「レミカちゃん……」
line = "「レミカちゃん……」"

[[dialogue]]
speaker = "レミカ"
# 「２人とも、本当にごめん……。こんなことになっちゃって……たくさん練習、付き合ってもらったのに」
line = "「２人とも、本当にごめん……。こんなことになっちゃって……たくさん練習、付き合ってもらったのに」"

[[dialogue]]
speaker = "unk"
# レミカ……
line = "レミカ……"

[[dialogue]]
speaker = "レミカ"
# 「もう少しで……昔からの夢が叶えられるって、思ってたんだけどなー……あは。まあしょうがない、のかな……」
line = "「もう少しで……昔からの夢が叶えられるって、思ってたんだけどなー……あは。まあしょうがない、のかな……」"

[[dialogue]]
speaker = "レミカ"
# 「企業が絡んだら当然、大人の事情ってやつもあるし……諦めるしか……」
line = "「企業が絡んだら当然、大人の事情ってやつもあるし……諦めるしか……」"

[[dialogue]]
speaker = "メルエル"
# 「……ダメだよ、そんなの！」
line = "「……ダメだよ、そんなの！」"

[[dialogue]]
speaker = "メルエル"
# 「練習やろう、レミカちゃん！　諦めちゃダメだよ。中止になったのは、今度のライブだけでしょ……！？」
line = "「練習やろう、レミカちゃん！　諦めちゃダメだよ。中止になったのは、今度のライブだけでしょ……！？」"

[[dialogue]]
speaker = "メルエル"
# 「社長さんだってレミカちゃんの想いはわかってるよ！　今だって何とか開催しようと努力してくれてるはず……！」
line = "「社長さんだってレミカちゃんの想いはわかってるよ！　今だって何とか開催しようと努力してくれてるはず……！」"

[[dialogue]]
speaker = "メルエル"
# 「だったらアイドルの私たちは、いつでもライブできるようにしておかないと！」
line = "「だったらアイドルの私たちは、いつでもライブできるようにしておかないと！」"

[[dialogue]]
speaker = "レミカ"
# 「メルエル……」
line = "「メルエル……」"

[[dialogue]]
speaker = "メルエル"
# 「ほら、衣装に着替えて！　今日もいつもどおり練習しよ！」
line = "「ほら、衣装に着替えて！　今日もいつもどおり練習しよ！」"

[[dialogue]]
speaker = "レミカ"
# 「…………うん。変身……！」
line = "「…………うん。変身……！」"

[[dialogue]]
speaker = "レミカ"
# 「あ、れ……？」
line = "「あ、れ……？」"

[[dialogue]]
speaker = "unk"
# 何も、起きない……？
line = "何も、起きない……？"

[[dialogue]]
speaker = "レミカ"
# 「……ごめん。今メルエルが言ってくれた言葉……『そうだね』って思ってない自分がいるんだと思う」
line = "「……ごめん。今メルエルが言ってくれた言葉……『そうだね』って思ってない自分がいるんだと思う」"

[[dialogue]]
speaker = "レミカ"
# 「うちの社長って優しい人だけど、会社の……従業員をよく守る人だってわかってるから……」
line = "「うちの社長って優しい人だけど、会社の……従業員をよく守る人だってわかってるから……」"

[[dialogue]]
speaker = "レミカ"
# 「今回のライブのリスクを考えたら、たぶん……『すまないけど我慢してくれ』って言うと、思うんだよね……」
line = "「今回のライブのリスクを考えたら、たぶん……『すまないけど我慢してくれ』って言うと、思うんだよね……」"

[[dialogue]]
speaker = "レミカ"
# 「本当に、ごめん……」
line = "「本当に、ごめん……」"

[[dialogue]]
speaker = "マトイ"
# 「そんな……中止だなんて。あ、あんなに頑張ってたのに……」
line = "「そんな……中止だなんて。あ、あんなに頑張ってたのに……」"

[[dialogue]]
speaker = "アナ"
# 「大企業だからこそリスクを取りたくないのもわかりますが、あまりに酷です……」
line = "「大企業だからこそリスクを取りたくないのもわかりますが、あまりに酷です……」"

[[dialogue]]
speaker = "サーシャ"
# 「そうね……って、ヴィーナスちゃん。さっきからＤＩＳＣで何を調べてるの？」
line = "「そうね……って、ヴィーナスちゃん。さっきからＤＩＳＣで何を調べてるの？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あったま来ちゃったからポラプロの本社ビルの場所を調べてるの！　社長にゴッデスビームをぶちこんで気合いを入れてやるわ！」
line = "「あったま来ちゃったからポラプロの本社ビルの場所を調べてるの！　社長にゴッデスビームをぶちこんで気合いを入れてやるわ！」"

[[dialogue]]
speaker = "マトイ"
# 「それは本当にダメなやつだよ！？」
line = "「それは本当にダメなやつだよ！？」"

[[dialogue]]
speaker = "サーシャ"
# 「どうするの、会長くん？」
line = "「どうするの、会長くん？」"

[[dialogue]]
speaker = "unk"
# 諦めたくはないですけど……
line = "諦めたくはないですけど……"

[[dialogue]]
speaker = "アナ"
# 「しかし事務所が許可しないのであれば、打つ手はありません」
line = "「しかし事務所が許可しないのであれば、打つ手はありません」"

[[dialogue]]
speaker = "マトイ"
# 「だよね。学生の私たちにできることなんてあるのかな……会長、どうしよう？」
line = "「だよね。学生の私たちにできることなんてあるのかな……会長、どうしよう？」"

[[dialogue]]
speaker = "unk"
# ──ちょっと考えてくる
line = "──ちょっと考えてくる"

[[dialogue]]
speaker = "unk"
# ──芸能事務所からストップをかけられてしまったアーネストのライブ。どうすればいいのだろう。
line = "──芸能事務所からストップをかけられてしまったアーネストのライブ。どうすればいいのだろう。"

[[dialogue]]
speaker = "unk"
# レミカの夢を叶え、メルエルの努力を無駄にせず、そしてポラプロの社長にも納得してもらえるライブ開催の方法……
line = "レミカの夢を叶え、メルエルの努力を無駄にせず、そしてポラプロの社長にも納得してもらえるライブ開催の方法……"

[[dialogue]]
speaker = "unk"
# 悩みながら歩く俺の元へ、声が聞こえてきた。
line = "悩みながら歩く俺の元へ、声が聞こえてきた。"

[[dialogue]]
speaker = "メルエル"
# 「１、２、３、４っ！　５、６、７、８っ！」
line = "「１、２、３、４っ！　５、６、７、８っ！」"

[[dialogue]]
speaker = "unk"
# この声は……？
line = "この声は……？"

[[dialogue]]
speaker = "メルエル"
# 「ふぅっ──こんな感じかな。ちょっと休憩……！」
line = "「ふぅっ──こんな感じかな。ちょっと休憩……！」"

[[dialogue]]
speaker = "unk"
# メルエル？
line = "メルエル？"

[[dialogue]]
speaker = "メルエル"
# 「わわっ！？　会長くん！？　い、いつからいたのっ？」
line = "「わわっ！？　会長くん！？　い、いつからいたのっ？」"

[[dialogue]]
speaker = "メルエル"
# 「ちょっと前からって……あわわ、恥ずかしいっ……！」
line = "「ちょっと前からって……あわわ、恥ずかしいっ……！」"

[[dialogue]]
speaker = "unk"
# 練習、してたんだな
line = "練習、してたんだな"

[[dialogue]]
speaker = "メルエル"
# 「うん。あんなことになっちゃったけど、まだ諦めきれなくって……もやもやした気持ちを吹き飛ばすには、身体を動かすのが一番だし」
line = "「うん。あんなことになっちゃったけど、まだ諦めきれなくって……もやもやした気持ちを吹き飛ばすには、身体を動かすのが一番だし」"

[[dialogue]]
speaker = "unk"
# メルエルは強いんだな
line = "メルエルは強いんだな"

[[dialogue]]
speaker = "メルエル"
# 「そんなことないけど……えへ。私、諦めないことだけは昔から得意なんだ」
line = "「そんなことないけど……えへ。私、諦めないことだけは昔から得意なんだ」"

[[dialogue]]
speaker = "メルエル"
# 「身体を動かしながら色々考えてるんだよ。レミカちゃんと一緒に、ポラプロの社長さんに練習風景を見てもらったらどうかなー、とか」
line = "「身体を動かしながら色々考えてるんだよ。レミカちゃんと一緒に、ポラプロの社長さんに練習風景を見てもらったらどうかなー、とか」"

[[dialogue]]
speaker = "メルエル"
# 「きっと不安になってるだけだと思うの。アーネストがとっても魅力的なユニットだって伝われば……」
line = "「きっと不安になってるだけだと思うの。アーネストがとっても魅力的なユニットだって伝われば……」"

[[dialogue]]
speaker = "メルエル"
# 「──って、やっぱり難しいかな……？」
line = "「──って、やっぱり難しいかな……？」"

[[dialogue]]
speaker = "メルエル"
# 「でもやっぱり何もせずに諦めたくないよ！　辛い時こそ、笑わなきゃ！」
line = "「でもやっぱり何もせずに諦めたくないよ！　辛い時こそ、笑わなきゃ！」"

[[dialogue]]
speaker = "メルエル"
# 「それに！　明日は新星学園のオープンキャンパスでしょ？　このまま暗い顔をしてたら、入学希望の子たちもがっかりしちゃうよ。笑顔、笑顔！」
line = "「それに！　明日は新星学園のオープンキャンパスでしょ？　このまま暗い顔をしてたら、入学希望の子たちもがっかりしちゃうよ。笑顔、笑顔！」"

[[dialogue]]
speaker = "unk"
# オープンキャンパスだ！
line = "オープンキャンパスだ！"

[[dialogue]]
speaker = "unk"
# ──そうか
line = "──そうか"

[[dialogue]]
speaker = "メルエル"
# 「わわっ、会長くん、どうしたの……えっ、アイデアが閃いた……！？」
line = "「わわっ、会長くん、どうしたの……えっ、アイデアが閃いた……！？」"

[[dialogue]]
speaker = "unk"
# やってみる価値はある……！
line = "やってみる価値はある……！"

[[dialogue]]
speaker = "unk"
# できるかどうかわからないけど
line = "できるかどうかわからないけど"

[[dialogue]]
speaker = "アナ"
# 「正気ですか、会長……？」
line = "「正気ですか、会長……？」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら、うふふ♪　面白くなってきたわね～♪」
line = "「あらあら、うふふ♪　面白くなってきたわね～♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「いいアイデアだと思うわ！　そうと決まれば、行動開始ね！」
line = "「いいアイデアだと思うわ！　そうと決まれば、行動開始ね！」"

[[dialogue]]
speaker = "unk"
# そうして俺は、この計画の成功のカギとなる人物へ電話をかけることにした。
line = "そうして俺は、この計画の成功のカギとなる人物へ電話をかけることにした。"

[[dialogue]]
speaker = "ヘレナ"
# 「立てばプリティ、座ればゴージャス。電話越しでもラブリーキュートなヘレナちゃんだ。魔王から電話とは珍しい」
line = "「立てばプリティ、座ればゴージャス。電話越しでもラブリーキュートなヘレナちゃんだ。魔王から電話とは珍しい」"

[[dialogue]]
speaker = "ヘレナ"
# 「要件は何だ。面白いことであったなら嬉しいが……ほう、ほう……♪」
line = "「要件は何だ。面白いことであったなら嬉しいが……ほう、ほう……♪」"
