[[dialogue]]
speaker = "メルエル"
# 「むむむっ、無理だよぉ！？　私、どこにでもいる普通の天使だよ！？　レミカちゃんみたいなトップアイドルとユニットだなんて……！」
line = "「むむむっ、無理だよぉ！？　私、どこにでもいる普通の天使だよ！？　レミカちゃんみたいなトップアイドルとユニットだなんて……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「予想通りの返事ね……どうしてこんなに嫌がるのかしら。メルエルはとっても可愛いのに」
line = "「予想通りの返事ね……どうしてこんなに嫌がるのかしら。メルエルはとっても可愛いのに」"

[[dialogue]]
speaker = "レミカ"
# 「うん、笑顔も素敵だし心もまっすぐ。アイドルの素養を兼ね備えてると私も思うよ」
line = "「うん、笑顔も素敵だし心もまっすぐ。アイドルの素養を兼ね備えてると私も思うよ」"

[[dialogue]]
speaker = "メルエル"
# 「褒めてくれるのは嬉しいけど、あんまりおだてないでよ～……女の子の友達はすぐ可愛いって言うんだから……」
line = "「褒めてくれるのは嬉しいけど、あんまりおだてないでよ～……女の子の友達はすぐ可愛いって言うんだから……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「なら男の子の意見も聞いてみましょ？　クロトはメルエルのこと、どう思う？」
line = "「なら男の子の意見も聞いてみましょ？　クロトはメルエルのこと、どう思う？」"

[[dialogue]]
speaker = "unk"
# メルエルはすごく可愛いよ
line = "メルエルはすごく可愛いよ"

[[dialogue]]
speaker = "unk"
# お世辞なんかじゃなく
line = "お世辞なんかじゃなく"

[[dialogue]]
speaker = "メルエル"
# 「はうぅっ！？　そんなストレートに……め、メルトしちゃうよぉ～～……！？<emoji=heart04>」
line = "「はうぅっ！？　そんなストレートに……め、メルトしちゃうよぉ～～……！？<emoji=heart04>」"

[[dialogue]]
speaker = "レミカ"
# 「さすが会長。その援護射撃が欲しかったんだ」
line = "「さすが会長。その援護射撃が欲しかったんだ」"

[[dialogue]]
speaker = "unk"
# 無理強いはよくないよ
line = "無理強いはよくないよ"

[[dialogue]]
speaker = "unk"
# でも本人が嫌だって言うなら
line = "でも本人が嫌だって言うなら"

[[dialogue]]
speaker = "ヴィーナス"
# 「も～っ！　クロト、あなたはどっちの味方なのよ～っ」
line = "「も～っ！　クロト、あなたはどっちの味方なのよ～っ」"

[[dialogue]]
speaker = "レミカ"
# 「ま、そうなるよね。予想してたとおりかも……ちょっとメルエル、こっち来て」
line = "「ま、そうなるよね。予想してたとおりかも……ちょっとメルエル、こっち来て」"

[[dialogue]]
speaker = "レミカ"
# 「私は学生だけど、一応ビジネスの世界に生きてるし。交渉事ってウィンウィンでなきゃダメだと思ってるんだ」
line = "「私は学生だけど、一応ビジネスの世界に生きてるし。交渉事ってウィンウィンでなきゃダメだと思ってるんだ」"

[[dialogue]]
speaker = "メルエル"
# 「う、うん……？」
line = "「う、うん……？」"

[[dialogue]]
speaker = "レミカ"
# 「まず大前提として、今回のアイドルユニット活動は、あくまでも１回のライブ限定なんだ」
line = "「まず大前提として、今回のアイドルユニット活動は、あくまでも１回のライブ限定なんだ」"

[[dialogue]]
speaker = "レミカ"
# 「アイドルは素敵な職業だけど、しがらみも多いからね。そこにメルエルを付き合わせる気はないよ」
line = "「アイドルは素敵な職業だけど、しがらみも多いからね。そこにメルエルを付き合わせる気はないよ」"

[[dialogue]]
speaker = "レミカ"
# 「アイドルデビューって聞くと大げさに聞こえるなら、ライブ限定で私とコラボしてほしいってことなんだ」
line = "「アイドルデビューって聞くと大げさに聞こえるなら、ライブ限定で私とコラボしてほしいってことなんだ」"

[[dialogue]]
speaker = "メルエル"
# 「な、なるほど……？」
line = "「な、なるほど……？」"

[[dialogue]]
speaker = "レミカ"
# 「後はメルエルが喜ぶかなって思って、会長にアイドルユニットのプロデューサーをお願いしてるよ。ＯＫだって」
line = "「後はメルエルが喜ぶかなって思って、会長にアイドルユニットのプロデューサーをお願いしてるよ。ＯＫだって」"

[[dialogue]]
speaker = "メルエル"
# 「ええっ、会長くんがプロデューサー……！？」
line = "「ええっ、会長くんがプロデューサー……！？」"

[[dialogue]]
speaker = "レミカ"
# 「うん。歌やダンスの練習、できるかぎりサポートしてくれるって約束してもらえてる。つまり……」
line = "「うん。歌やダンスの練習、できるかぎりサポートしてくれるって約束してもらえてる。つまり……」"

[[dialogue]]
speaker = "メルエル"
# 「放課後は……いつも会長くんと一緒っ！？」
line = "「放課後は……いつも会長くんと一緒っ！？」"

[[dialogue]]
speaker = "レミカ"
# 「放課後だけじゃないよ。朝練も昼練もするし……そうだ。休日に待ち合わせするのもいいかもね」
line = "「放課後だけじゃないよ。朝練も昼練もするし……そうだ。休日に待ち合わせするのもいいかもね」"

[[dialogue]]
speaker = "メルエル"
# 「お休みの日まで！？」
line = "「お休みの日まで！？」"

[[dialogue]]
speaker = "レミカ"
# 「メルエル、会長とは幼なじみだけど、昔のことを思い出してもらえてないって言ってたでしょ？　そのきっかけになったらどうかなって」
line = "「メルエル、会長とは幼なじみだけど、昔のことを思い出してもらえてないって言ってたでしょ？　そのきっかけになったらどうかなって」"

[[dialogue]]
speaker = "メルエル"
# 「れ、レミカちゃん……この前と違ってすごいね。プロの交渉って感じがする……！」
line = "「れ、レミカちゃん……この前と違ってすごいね。プロの交渉って感じがする……！」"

[[dialogue]]
speaker = "レミカ"
# 「それだけ本気ってこと。メルエルとライブがしたいんだ、私……どうかな？」
line = "「それだけ本気ってこと。メルエルとライブがしたいんだ、私……どうかな？」"

[[dialogue]]
speaker = "メルエル"
# （レミカちゃん、本気なんだ。応援してあげたいけど、アイドルって恥ずかしい……）
line = "（レミカちゃん、本気なんだ。応援してあげたいけど、アイドルって恥ずかしい……）"

[[dialogue]]
speaker = "メルエル"
# （でも私が断ったら、他の女の子が選ばれるのかな。そうしたら、その子が会長くんと朝も昼も放課後も休日もすごすのかなっ……！？）
line = "（でも私が断ったら、他の女の子が選ばれるのかな。そうしたら、その子が会長くんと朝も昼も放課後も休日もすごすのかなっ……！？）"

[[dialogue]]
speaker = "メルエル"
# 「わ、わかった……！！」
line = "「わ、わかった……！！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あ、戻ってきたわね」
line = "「あ、戻ってきたわね」"

[[dialogue]]
speaker = "メルエル"
# 「──やる！　私っ……姫咲メルエル、未熟者ではありますがっ！　アイドルやりますっ！」
line = "「──やる！　私っ……姫咲メルエル、未熟者ではありますがっ！　アイドルやりますっ！」"

[[dialogue]]
speaker = "unk"
# 大丈夫なのか？　無理してない？
line = "大丈夫なのか？　無理してない？"

[[dialogue]]
speaker = "メルエル"
# 「う、ううん！　レミカちゃんの本気も伝わってきたし……会長くんもお手伝いしてくれるなら私、頑張れると思う！」
line = "「う、ううん！　レミカちゃんの本気も伝わってきたし……会長くんもお手伝いしてくれるなら私、頑張れると思う！」"

[[dialogue]]
speaker = "レミカ"
# 「決まりだね──本当にありがとう、メルエル」
line = "「決まりだね──本当にありがとう、メルエル」"

[[dialogue]]
speaker = "ヴィーナス"
# 「今、ここに誕生したわ！　新星学園の星騎士だけで組まれたアイドルユニットが……！！」
line = "「今、ここに誕生したわ！　新星学園の星騎士だけで組まれたアイドルユニットが……！！」"

[[dialogue]]
speaker = "unk"
# こうしてレミカの夢を叶えるために、１日限りのアイドルユニットが結成されるのであった。
line = "こうしてレミカの夢を叶えるために、１日限りのアイドルユニットが結成されるのであった。"
