[[dialogue]]
speaker = "聖沙"
# 「キャ～～～～っ！？」
line = "「キャ～～～～っ！？」"

[[dialogue]]
speaker = "聖沙"
# 「会長の水着フォームに負けた！？」
line = "「会長の水着フォームに負けた！？」"

[[dialogue]]
speaker = "unk"
# これが俺の『海パン』の力だ！！
line = "これが俺の『海パン』の力だ！！"

[[dialogue]]
speaker = "聖沙"
# 「そ、そんな……私の水着が、海パンに敗れるだなんて……！」
line = "「そ、そんな……私の水着が、海パンに敗れるだなんて……！」"

[[dialogue]]
speaker = "聖沙"
# 「い、いや！　そう簡単に認めるわけには行かないわ！」
line = "「い、いや！　そう簡単に認めるわけには行かないわ！」"

[[dialogue]]
speaker = "聖沙"
# 「会長、もう１度勝負よ！」
line = "「会長、もう１度勝負よ！」"

[[dialogue]]
speaker = "聖沙"
# 「私の水着で、あなたの海パンに勝ってみせるわ！」
line = "「私の水着で、あなたの海パンに勝ってみせるわ！」"
