[[dialogue]]
speaker = "unk"
# 小さい体になった俺や守護天使の２人。そのことについて、アニマ先輩から話を聞くと――
line = "小さい体になった俺や守護天使の２人。そのことについて、アニマ先輩から話を聞くと――"

[[dialogue]]
speaker = "アニマ"
# 「会長たちがいま使っている体は、アニマが何かあった時の予備として作っておいたスペアボディ『幼アバター』だヨ」
line = "「会長たちがいま使っている体は、アニマが何かあった時の予備として作っておいたスペアボディ『幼アバター』だヨ」"

[[dialogue]]
speaker = "アニマ"
# 「アステラの中で謎の新種モンスターと戦った際、会長たちの本体はリクリエの瘴気を浴びて、汚染されてしまった」
line = "「アステラの中で謎の新種モンスターと戦った際、会長たちの本体はリクリエの瘴気を浴びて、汚染されてしまった」"

[[dialogue]]
speaker = "アニマ"
# 「アニマが検査したところ、それの除去には、どうやら時間がかかりそうでネ」
line = "「アニマが検査したところ、それの除去には、どうやら時間がかかりそうでネ」"

[[dialogue]]
speaker = "アニマ"
# 「そこで一時的に、幼アバターに精神を移して、活動できるようにしたというわけダ」
line = "「そこで一時的に、幼アバターに精神を移して、活動できるようにしたというわけダ」"

[[dialogue]]
speaker = "unk"
# 保健室の他のベッドを見やると、確かに俺や、マグダレナさん、アルモタヘルさんの元々の体が寝かされていた。
line = "保健室の他のベッドを見やると、確かに俺や、マグダレナさん、アルモタヘルさんの元々の体が寝かされていた。"

[[dialogue]]
speaker = "unk"
# でも、どうして小さい体に？
line = "でも、どうして小さい体に？"

[[dialogue]]
speaker = "アニマ"
# 「そんなの決まっているダロウ？」
line = "「そんなの決まっているダロウ？」"

[[dialogue]]
speaker = "アニマ"
# 「アニマの趣味ダ♪　小さい姿も楽しめた方がお得ダロウ？　フヒ♪」
line = "「アニマの趣味ダ♪　小さい姿も楽しめた方がお得ダロウ？　フヒ♪」"

[[dialogue]]
speaker = "unk"
# えぇ……
line = "えぇ……"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「ふふ♪　でも、小さくなった会長さまも、とても可愛らしいですよ♪」
line = "「ふふ♪　でも、小さくなった会長さまも、とても可愛らしいですよ♪」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「思わず、私の中にある『ママになりたい欲』が溢れてきてしまいます♪」
line = "「思わず、私の中にある『ママになりたい欲』が溢れてきてしまいます♪」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「うむ！　アルモたん的にも、よく似合っていると思うぞ、会長！　ちょうど我らと同い年くらいの外見になった感じだな！」
line = "「うむ！　アルモたん的にも、よく似合っていると思うぞ、会長！　ちょうど我らと同い年くらいの外見になった感じだな！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「そう思ったら、早く一緒に遊びたくなってきたのだ♪」
line = "「そう思ったら、早く一緒に遊びたくなってきたのだ♪」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「――あら？　会長さま、どうかされました？」
line = "「――あら？　会長さま、どうかされました？」"

[[dialogue]]
speaker = "unk"
# なんか２人とも……性格が変わってない？
line = "なんか２人とも……性格が変わってない？"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「そうか？　アニマからも同じことを言われたのだ。でも、う～む……アルモたん的には普段通りのつもりなのだが……」
line = "「そうか？　アニマからも同じことを言われたのだ。でも、う～む……アルモたん的には普段通りのつもりなのだが……」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「あ！　でも確かに、この姿になってから初めて、附属校に通ってみたいと思ったのだ！」
line = "「あ！　でも確かに、この姿になってから初めて、附属校に通ってみたいと思ったのだ！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「私もです♪　性格がどう変わったのかは、自身ではよくわかりませんが、今までよりも新鮮な気持ちが溢れてくるというか……」
line = "「私もです♪　性格がどう変わったのかは、自身ではよくわかりませんが、今までよりも新鮮な気持ちが溢れてくるというか……」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「アルモタヘルと２人でアニマさまに相談して、流星学園附属校に体験入学させてもらえることになったんです」
line = "「アルモタヘルと２人でアニマさまに相談して、流星学園附属校に体験入学させてもらえることになったんです」"

[[dialogue]]
speaker = "アニマ"
# 「フィオナ会長に守護天使２人が望んでいると話してみたら、快く手続きの協力をしてくれたヨ♪」
line = "「フィオナ会長に守護天使２人が望んでいると話してみたら、快く手続きの協力をしてくれたヨ♪」"

[[dialogue]]
speaker = "アニマ"
# 「これはアニマの推測だガ、２人の『魂』は、小さくなった『体』に引っ張られているのかもしれナイ」
line = "「これはアニマの推測だガ、２人の『魂』は、小さくなった『体』に引っ張られているのかもしれナイ」"

[[dialogue]]
speaker = "アニマ"
# 「アバターを切り替えた副作用とも言い換えられるかもしれないナ。実に興味深い現象ダ」
line = "「アバターを切り替えた副作用とも言い換えられるかもしれないナ。実に興味深い現象ダ」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「そうだ、いいことを思い付いたのだ！　会長もせっかく小さくなったのだから、アルモたんと一緒に附属校体験をしてみるのはどうだ？」
line = "「そうだ、いいことを思い付いたのだ！　会長もせっかく小さくなったのだから、アルモたんと一緒に附属校体験をしてみるのはどうだ？」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「まあ！　それは面白そうですね♪　アニマさま、会長さまの制服を作ることは可能でしょうか？」
line = "「まあ！　それは面白そうですね♪　アニマさま、会長さまの制服を作ることは可能でしょうか？」"

[[dialogue]]
speaker = "アニマ"
# 「フヒ♪　アルモたんとマグたんが附属校に通いたいと言い出した時から、こんなこともあろうかと準備をしていたヨ♪」
line = "「フヒ♪　アルモたんとマグたんが附属校に通いたいと言い出した時から、こんなこともあろうかと準備をしていたヨ♪」"

[[dialogue]]
speaker = "アニマ"
# 「というわけで――附属校の制服～♪」
line = "「というわけで――附属校の制服～♪」"

[[dialogue]]
speaker = "unk"
# ちょっと待って！　それ女子用の制服ですよね！？
line = "ちょっと待って！　それ女子用の制服ですよね！？"

[[dialogue]]
speaker = "アニマ"
# 「フヒ♪　そっちの方が、更に面白いダロウ？」
line = "「フヒ♪　そっちの方が、更に面白いダロウ？」"

[[dialogue]]
speaker = "unk"
# 翌日。流星学園附属校にて――
line = "翌日。流星学園附属校にて――"

[[dialogue]]
speaker = "ナミエル"
# 「え……！？」
line = "「え……！？」"

[[dialogue]]
speaker = "unk"
# １年Ｃ組に所属するナミエル・クレシェンテは、驚きで瞳を見開く。
line = "１年Ｃ組に所属するナミエル・クレシェンテは、驚きで瞳を見開く。"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「――そういう事情があって、今日から附属校に通うことになった、守護天使のアルモタヘルなのだ！　気軽にアルモたんって呼んでくれると嬉しいぞ♪」
line = "「――そういう事情があって、今日から附属校に通うことになった、守護天使のアルモタヘルなのだ！　気軽にアルモたんって呼んでくれると嬉しいぞ♪」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「同じく、小さくなった守護天使のマグダレナです～。私のことも、気軽にママダレナって呼んでくれると嬉しいかな、なんて♪　うふふっ<emoji=heart04>」
line = "「同じく、小さくなった守護天使のマグダレナです～。私のことも、気軽にママダレナって呼んでくれると嬉しいかな、なんて♪　うふふっ<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# 守護天使の２人が転入してきたことにも、もちろん驚いたナミエルだが、それ以上に――
line = "守護天使の２人が転入してきたことにも、もちろん驚いたナミエルだが、それ以上に――"

[[dialogue]]
speaker = "ナミエル"
# （な、なんて可愛らしい子なんでしょう……）
line = "（な、なんて可愛らしい子なんでしょう……）"

[[dialogue]]
speaker = "unk"
# 彼女が、ぽーっと見惚れてしまったのは、もう１人の女子生徒だった。
line = "彼女が、ぽーっと見惚れてしまったのは、もう１人の女子生徒だった。"

[[dialogue]]
speaker = "ナミエル"
# （長くて艶やかな黒髪、星の輝きを内包したかのような綺麗な瞳……それに、スタイルも抜群で……）
line = "（長くて艶やかな黒髪、星の輝きを内包したかのような綺麗な瞳……それに、スタイルも抜群で……）"

[[dialogue]]
speaker = "unk"
# は、初めまして。緋宮クロトです
line = "は、初めまして。緋宮クロトです"

[[dialogue]]
speaker = "ナミエル"
# （クロトさんっていうんですね……親しみを感じる、いい名前です）
line = "（クロトさんっていうんですね……親しみを感じる、いい名前です）"

[[dialogue]]
speaker = "ナミエル"
# （……ん？　クロト……？　緋宮クロトって……）
line = "（……ん？　クロト……？　緋宮クロトって……）"

[[dialogue]]
speaker = "unk"
# その……中身は、新星学園の会長です
line = "その……中身は、新星学園の会長です"

[[dialogue]]
speaker = "ナミエル"
# 「って、ええぇっ！？」
line = "「って、ええぇっ！？」"

[[dialogue]]
speaker = "ナミエル"
# 「緋宮会長～～～っ！？！？」
line = "「緋宮会長～～～っ！？！？」"

[[dialogue]]
speaker = "unk"
# 思わず他のクラスメイト達と一緒に立ち上がって、叫んでしまうナミエルなのであった。
line = "思わず他のクラスメイト達と一緒に立ち上がって、叫んでしまうナミエルなのであった。"
