[[dialogue]]
speaker = "モンスター"
# 「グ──ガアァアアアアッ！！」
line = "「グ──ガアァアアアアッ！！」"

[[dialogue]]
speaker = "イニシュ"
# 「引き裂け──アンブラルヴァナルガンド」
line = "「引き裂け──アンブラルヴァナルガンド」"

[[dialogue]]
speaker = "モンスター"
# 「ガアアァ……！」
line = "「ガアアァ……！」"

[[dialogue]]
speaker = "イニシュ"
# 「モンスターの掃討は私が担当します。みなさんは堕天使を攻撃してください」
line = "「モンスターの掃討は私が担当します。みなさんは堕天使を攻撃してください」"

[[dialogue]]
speaker = "ヴィーナス"
# 「あのイニシュって魔女、めちゃくちゃ強いじゃない！　任せたわよ！」
line = "「あのイニシュって魔女、めちゃくちゃ強いじゃない！　任せたわよ！」"

[[dialogue]]
speaker = "フィオナ"
# 「はい、私たちはマグダレナさんの下へ！」
line = "「はい、私たちはマグダレナさんの下へ！」"

[[dialogue]]
speaker = "unk"
# 全速力で神殿の中心部まで駆け抜けると──
line = "全速力で神殿の中心部まで駆け抜けると──"

[[dialogue]]
speaker = "マグダレナ"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「いたわね！　いかにも堕天使って感じだわ！」
line = "「いたわね！　いかにも堕天使って感じだわ！」"

[[dialogue]]
speaker = "フィオナ"
# 「堕天使となったマグダレナさんと戦うのは二度目ですが──」
line = "「堕天使となったマグダレナさんと戦うのは二度目ですが──」"

[[dialogue]]
speaker = "マグダレナ"
# 「滅びよ──」
line = "「滅びよ──」"

[[dialogue]]
speaker = "フィオナ"
# 「くっ……！　以前戦った時とは段違いの力とプレッシャーです。守護天使の本体ともなれば当然なのでしょうが……」
line = "「くっ……！　以前戦った時とは段違いの力とプレッシャーです。守護天使の本体ともなれば当然なのでしょうが……」"

[[dialogue]]
speaker = "ミルフィー"
# 「守護天使様は世界を運営する存在。守護天使様を相手にするってことは、世界を相手にすることだよ」
line = "「守護天使様は世界を運営する存在。守護天使様を相手にするってことは、世界を相手にすることだよ」"

[[dialogue]]
speaker = "コハルコ"
# 『霊力数値を計測……──っ！　この数値は……他の堕天使より数段上の霊力です』
line = "『霊力数値を計測……──っ！　この数値は……他の堕天使より数段上の霊力です』"

[[dialogue]]
speaker = "コハルコ"
# 『リクリエの浸食も進んでいる……。堕天使マグダレナは今回の作戦で最も脅威度が高いターゲットです！』
line = "『リクリエの浸食も進んでいる……。堕天使マグダレナは今回の作戦で最も脅威度が高いターゲットです！』"

[[dialogue]]
speaker = "ミルフィー"
# 「マグダレナ様……少しだけ待っていてください。今お救いします」
line = "「マグダレナ様……少しだけ待っていてください。今お救いします」"

[[dialogue]]
speaker = "マグダレナ"
# 「世界をひとつに……終焉を……」
line = "「世界をひとつに……終焉を……」"

[[dialogue]]
speaker = "ミルフィー"
# 「っ──！」
line = "「っ──！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「せっかく助けに来たんだから、大人しくしてなさい！　フィオナ！」
line = "「せっかく助けに来たんだから、大人しくしてなさい！　フィオナ！」"

[[dialogue]]
speaker = "フィオナ"
# 「ええ、力を重ねましょう！　──エクリプスディザスター！」
line = "「ええ、力を重ねましょう！　──エクリプスディザスター！」"

[[dialogue]]
speaker = "マグダレナ"
# 「儚き者たちよ……静かに眠りなさい……」
line = "「儚き者たちよ……静かに眠りなさい……」"

[[dialogue]]
speaker = "マグダレナ"
# 「──ッ！」
line = "「──ッ！」"

[[dialogue]]
speaker = "unk"
# 今の俺は魔王の力を十全には扱えない。
line = "今の俺は魔王の力を十全には扱えない。"

[[dialogue]]
speaker = "unk"
# それでも俺は１人の星騎士で、新星学園の星徒会長だ。
line = "それでも俺は１人の星騎士で、新星学園の星徒会長だ。"

[[dialogue]]
speaker = "unk"
# なら力の限りこの拳を振るうだけだ！
line = "なら力の限りこの拳を振るうだけだ！"

[[dialogue]]
speaker = "フィオナ"
# 「生半可な攻撃では回復されてしまいます。一気に決着させましょう！」
line = "「生半可な攻撃では回復されてしまいます。一気に決着させましょう！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「とっとと目を覚まさせてやるわ！」
line = "「とっとと目を覚まさせてやるわ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「効いてはいるようね。このまま押し切るわよ！」
line = "「効いてはいるようね。このまま押し切るわよ！」"

[[dialogue]]
speaker = "unk"
# 世界の崩壊まで残された時間は少ない。
line = "世界の崩壊まで残された時間は少ない。"

[[dialogue]]
speaker = "unk"
# 後先のことは考えず、ひたすらに攻撃を叩き込む！
line = "後先のことは考えず、ひたすらに攻撃を叩き込む！"

[[dialogue]]
speaker = "ミルフィー"
# （子どもの頃からマグダレナ様の話を聞かされていた。三界を見守る優しいお方だと。天界・人間界・魔界──３つの世界が争わずにいられるのはマグダレナ様のおかげなのだと）
line = "（子どもの頃からマグダレナ様の話を聞かされていた。三界を見守る優しいお方だと。天界・人間界・魔界──３つの世界が争わずにいられるのはマグダレナ様のおかげなのだと）"

[[dialogue]]
speaker = "ミルフィー"
# （だからマグダレナ様のように、三界を守る存在になりたかった。優しい人になりたかった）
line = "（だからマグダレナ様のように、三界を守る存在になりたかった。優しい人になりたかった）"

[[dialogue]]
speaker = "ミルフィー"
# （でもリクリエとの戦いでは役に立てなかった。マグダレナ様が囚われていたのに何もできなかった。だから──）
line = "（でもリクリエとの戦いでは役に立てなかった。マグダレナ様が囚われていたのに何もできなかった。だから──）"

[[dialogue]]
speaker = "ミルフィー"
# 「今行きます、マグダレナ様！」
line = "「今行きます、マグダレナ様！」"

[[dialogue]]
speaker = "unk"
# ミルフィー、１人で突っ込むのは危険だ！
line = "ミルフィー、１人で突っ込むのは危険だ！"

[[dialogue]]
speaker = "ミルフィー"
# 「大丈夫！　私、プリマステラの中でも強い方なんだから！　それに攻撃力と機動力なら自信あるし──」
line = "「大丈夫！　私、プリマステラの中でも強い方なんだから！　それに攻撃力と機動力なら自信あるし──」"

[[dialogue]]
speaker = "ミルフィー"
# 「！　この距離なら届く──！」
line = "「！　この距離なら届く──！」"

[[dialogue]]
speaker = "ミルフィー"
# 「私がお救いします！　マグダレナ様……！」
line = "「私がお救いします！　マグダレナ様……！」"
