[[dialogue]]
speaker = "キサナ"
# 「あー、つまんねー……。どこを探しても星騎士どももいやがらねえし……」
line = "「あー、つまんねー……。どこを探しても星騎士どももいやがらねえし……」"

[[dialogue]]
speaker = "キサナ"
# 「ビビって隠れちまったか？　やっぱ直接学園に乗り込んでいきゃあ良かったか？」
line = "「ビビって隠れちまったか？　やっぱ直接学園に乗り込んでいきゃあ良かったか？」"

[[dialogue]]
speaker = "キサナ"
# 「けどカチコミはやめとけっつわれてるしな……ったく、面倒な注文付けやがって……」
line = "「けどカチコミはやめとけっつわれてるしな……ったく、面倒な注文付けやがって……」"

[[dialogue]]
speaker = "キサナ"
# 「あー、かったりぃ。この辺、酒場とかないのかねぇ。賭けカードができる店とかあると退屈しねえんだが……」
line = "「あー、かったりぃ。この辺、酒場とかないのかねぇ。賭けカードができる店とかあると退屈しねえんだが……」"

[[dialogue]]
speaker = "キサナ"
# 「つーかアタシはどこで寝りゃあいいんだよ。まぁその辺の空き家にでも転がり込むか……」
line = "「つーかアタシはどこで寝りゃあいいんだよ。まぁその辺の空き家にでも転がり込むか……」"

[[dialogue]]
speaker = "ミア"
# 「見つけたわよっ！」
line = "「見つけたわよっ！」"

[[dialogue]]
speaker = "キサナ"
# 「あぁ……？　誰かと思えば昼間のチビガキと魔王じゃねえか。わりぃがよ、今から寝るトコなんだわ」
line = "「あぁ……？　誰かと思えば昼間のチビガキと魔王じゃねえか。わりぃがよ、今から寝るトコなんだわ」"

[[dialogue]]
speaker = "ミア"
# 「なっ……！？　戦うつもりはないってこと！？　ふざけないでっ！」
line = "「なっ……！？　戦うつもりはないってこと！？　ふざけないでっ！」"

[[dialogue]]
speaker = "キサナ"
# 「ハハァ、ふざけてんのはテメエの方だろ。誰が寝るから戦わねえっつったよ？」
line = "「ハハァ、ふざけてんのはテメエの方だろ。誰が寝るから戦わねえっつったよ？」"

[[dialogue]]
speaker = "キサナ"
# 「その逆だ！」
line = "「その逆だ！」"

[[dialogue]]
speaker = "ミア"
# 「ぐっ……！？」
line = "「ぐっ……！？」"

[[dialogue]]
speaker = "キサナ"
# 「わざわざやられに来てくれるとは思ってなかったぜ！　やり残しなくスッキリ寝られそうじゃねえか！」
line = "「わざわざやられに来てくれるとは思ってなかったぜ！　やり残しなくスッキリ寝られそうじゃねえか！」"

[[dialogue]]
speaker = "ミア"
# 「眠りたいならいくらでも眠らせてあげるわ！　ただし、冷たい檻の中でね！」
line = "「眠りたいならいくらでも眠らせてあげるわ！　ただし、冷たい檻の中でね！」"

[[dialogue]]
speaker = "unk"
# お前はここで捕まえる！
line = "お前はここで捕まえる！"

[[dialogue]]
speaker = "キサナ"
# 「ハハハッ、攻撃が軽いなァ！　２人がかりでそれかよォ！　もっと人数引き連れてこりゃ良かったんじゃねえかァ、おい！」
line = "「ハハハッ、攻撃が軽いなァ！　２人がかりでそれかよォ！　もっと人数引き連れてこりゃ良かったんじゃねえかァ、おい！」"

[[dialogue]]
speaker = "ミア"
# 「きゃあっ！　あ、あんたなんか私と会長さんだけで十分よっ。星力を打ち消すその力、弱点はもう見抜いてるんだからっ」
line = "「きゃあっ！　あ、あんたなんか私と会長さんだけで十分よっ。星力を打ち消すその力、弱点はもう見抜いてるんだからっ」"

[[dialogue]]
speaker = "キサナ"
# 「へえ、面白えこと言うじゃねえの。アタシの力の弱点だ？」
line = "「へえ、面白えこと言うじゃねえの。アタシの力の弱点だ？」"

[[dialogue]]
speaker = "ミア"
# 「考えてみれば簡単なことよ。その力、正面からの攻撃しか打ち消せないんでしょ？　だからあなたは孤立した星騎士ばかりを狙って襲撃した」
line = "「考えてみれば簡単なことよ。その力、正面からの攻撃しか打ち消せないんでしょ？　だからあなたは孤立した星騎士ばかりを狙って襲撃した」"

[[dialogue]]
speaker = "ミア"
# 「私の攻撃を逃げずに受け止めた時だってそう。正面なら無力化できるからだったんでしょう？」
line = "「私の攻撃を逃げずに受け止めた時だってそう。正面なら無力化できるからだったんでしょう？」"

[[dialogue]]
speaker = "ミア"
# 「極めつけはモンスターが現れた時よ。圧倒的に有利な立場だったのにあなたは逃げだした。モンスターの相手をしてる間に背後から攻撃されることを嫌ったんだわ」
line = "「極めつけはモンスターが現れた時よ。圧倒的に有利な立場だったのにあなたは逃げだした。モンスターの相手をしてる間に背後から攻撃されることを嫌ったんだわ」"

[[dialogue]]
speaker = "キサナ"
# 「ククク、なら試してみろよ。アタシの背後が取れるってならな」
line = "「ククク、なら試してみろよ。アタシの背後が取れるってならな」"

[[dialogue]]
speaker = "unk"
# ミア……
line = "ミア……"

[[dialogue]]
speaker = "ミア"
# 「私を信じて会長さん」
line = "「私を信じて会長さん」"

[[dialogue]]
speaker = "ミア"
# 「間違ってはいない、はずよ。もしも間違っていたら、その時は私が……」
line = "「間違ってはいない、はずよ。もしも間違っていたら、その時は私が……」"

[[dialogue]]
speaker = "キサナ"
# 「くっちゃべってねえでかかって来い！　来ねえならこっちから行くぜっ！」
line = "「くっちゃべってねえでかかって来い！　来ねえならこっちから行くぜっ！」"

[[dialogue]]
speaker = "ミア"
# 「くっ……！　とにかく会長さん、作戦通りにっ……！」
line = "「くっ……！　とにかく会長さん、作戦通りにっ……！」"

[[dialogue]]
speaker = "unk"
# わかった、俺が隙を作る！
line = "わかった、俺が隙を作る！"

[[dialogue]]
speaker = "キサナ"
# 「ハッ、魔王が相手してる間にチビが後ろから攻撃ってか！」
line = "「ハッ、魔王が相手してる間にチビが後ろから攻撃ってか！」"

[[dialogue]]
speaker = "キサナ"
# 「いいぜ、来いよ！　チビガキ程度、いつでも返り討ちにしてやるぜ！」
line = "「いいぜ、来いよ！　チビガキ程度、いつでも返り討ちにしてやるぜ！」"

[[dialogue]]
speaker = "ミア"
# 「まだよ、ミア。焦っちゃダメ。会長さんなら必ず隙を作ってくれる」
line = "「まだよ、ミア。焦っちゃダメ。会長さんなら必ず隙を作ってくれる」"

[[dialogue]]
speaker = "ミア"
# 「でも、もしも私の予想が間違っていたら──……っっ。ダメ、弱気になっちゃ」
line = "「でも、もしも私の予想が間違っていたら──……っっ。ダメ、弱気になっちゃ」"

[[dialogue]]
speaker = "ミア"
# 「ママ、パパ、力を貸して……。恐怖に打ち克つ勇気をちょうだい……！」
line = "「ママ、パパ、力を貸して……。恐怖に打ち克つ勇気をちょうだい……！」"

[[dialogue]]
speaker = "ミア"
# 「っっ！　今よっ！」
line = "「っっ！　今よっ！」"

[[dialogue]]
speaker = "キサナ"
# 「チッ……！」
line = "「チッ……！」"

[[dialogue]]
speaker = "ミア"
# 「取ったっ！！」
line = "「取ったっ！！」"

[[dialogue]]
speaker = "キサナ"
# 「残念だったなァ！　アタシの力は正面からとか関係ねえんだよ！」
line = "「残念だったなァ！　アタシの力は正面からとか関係ねえんだよ！」"

[[dialogue]]
speaker = "ミア"
# 「うぐっ……！！？」
line = "「うぐっ……！！？」"

[[dialogue]]
speaker = "unk"
# ミア！
line = "ミア！"

[[dialogue]]
speaker = "キサナ"
# 「おっと動くなよォ。少しでも動いたらガキの腹に風穴空けてやんぜ？」
line = "「おっと動くなよォ。少しでも動いたらガキの腹に風穴空けてやんぜ？」"

[[dialogue]]
speaker = "ミア"
# 「ぐあっ……」
line = "「ぐあっ……」"

[[dialogue]]
speaker = "キサナ"
# 「とんだ迷推理だったなァ、チビガキィ」
line = "「とんだ迷推理だったなァ、チビガキィ」"

[[dialogue]]
speaker = "キサナ"
# 「ま、めげずに挑んできたことだけは褒めてやんよ。ご褒美に二度と戦えなくなる程度で済ましてやる」
line = "「ま、めげずに挑んできたことだけは褒めてやんよ。ご褒美に二度と戦えなくなる程度で済ましてやる」"

[[dialogue]]
speaker = "キサナ"
# 「今回は挨拶が目的だとか言われてるしな。ここらでアタシも──」
line = "「今回は挨拶が目的だとか言われてるしな。ここらでアタシも──」"

[[dialogue]]
speaker = "キサナ"
# 「熱ッ！　なんだ、このガキ。妙に体がアチいぞ？」
line = "「熱ッ！　なんだ、このガキ。妙に体がアチいぞ？」"

[[dialogue]]
speaker = "ミア"
# 「熱い、と言ったわね……」
line = "「熱い、と言ったわね……」"

[[dialogue]]
speaker = "キサナ"
# 「あァ？」
line = "「あァ？」"

[[dialogue]]
speaker = "ミア"
# 「やっぱり思った通り、だったわ……」
line = "「やっぱり思った通り、だったわ……」"

[[dialogue]]
speaker = "ミア"
# 「あなたのその力……打ち消せる星力には限界があった、ようね……」
line = "「あなたのその力……打ち消せる星力には限界があった、ようね……」"

[[dialogue]]
speaker = "キサナ"
# 「ッ！？　テメエ、何しやがった！？」
line = "「ッ！？　テメエ、何しやがった！？」"

[[dialogue]]
speaker = "ミア"
# 「ぐふっ、ゴホゴホっ。あなたが、言ったのよ……。私の攻撃を受け止めた時に……」
line = "「ぐふっ、ゴホゴホっ。あなたが、言ったのよ……。私の攻撃を受け止めた時に……」"

[[dialogue]]
speaker = "キサナ"
# 「貧相な見た目の割には大した星力だが、所詮こんなもんか。腹の半分にも足りねえ」
line = "「貧相な見た目の割には大した星力だが、所詮こんなもんか。腹の半分にも足りねえ」"

[[dialogue]]
speaker = "ミア"
# 「腹の半分にも足りない……あれは力の容量を意識した発言だったのよ」
line = "「腹の半分にも足りない……あれは力の容量を意識した発言だったのよ」"

[[dialogue]]
speaker = "ミア"
# 「私も少ない力をやりくりして使ってるからわかるの……。私の場合、逆に体に熱を溜めに溜めて力を高める使い方をしているけれどね……」
line = "「私も少ない力をやりくりして使ってるからわかるの……。私の場合、逆に体に熱を溜めに溜めて力を高める使い方をしているけれどね……」"

[[dialogue]]
speaker = "キサナ"
# 「まさかテメエ……さっきの迷推理はブラフか？　アタシに近づくためだけに？　そのチンケな熱でアタシの力を消耗させる気で……」
line = "「まさかテメエ……さっきの迷推理はブラフか？　アタシに近づくためだけに？　そのチンケな熱でアタシの力を消耗させる気で……」"

[[dialogue]]
speaker = "キサナ"
# 「アタシがその気だったら死んでんぞ？　わかってんのか？」
line = "「アタシがその気だったら死んでんぞ？　わかってんのか？」"

[[dialogue]]
speaker = "ミア"
# 「肉を切らせて骨を断つ、虎穴に入らずんば虎児を得ず、よ……。覚えて、おきなさいっ……！」
line = "「肉を切らせて骨を断つ、虎穴に入らずんば虎児を得ず、よ……。覚えて、おきなさいっ……！」"

[[dialogue]]
speaker = "キサナ"
# 「ククク、ハッハァッ！　いいぜ、ビビり散らかしてた昼間のガキとは別人じゃねえか！」
line = "「ククク、ハッハァッ！　いいぜ、ビビり散らかしてた昼間のガキとは別人じゃねえか！」"

[[dialogue]]
speaker = "キサナ"
# 「だがこっからどうするんだ！？　テメエも魔王もズタボロじゃねえか！」
line = "「だがこっからどうするんだ！？　テメエも魔王もズタボロじゃねえか！」"

[[dialogue]]
speaker = "キサナ"
# 「弱ったテメエら２人くらい今のアタシでもぶちのめせるぜ！　逃げるだけならもっと簡単だ！」
line = "「弱ったテメエら２人くらい今のアタシでもぶちのめせるぜ！　逃げるだけならもっと簡単だ！」"

[[dialogue]]
speaker = "ミア"
# 「私たち２人だけなら──ね」
line = "「私たち２人だけなら──ね」"

[[dialogue]]
speaker = "エリス"
# 「はあああああああっっ──！！」
line = "「はあああああああっっ──！！」"

[[dialogue]]
speaker = "キサナ"
# 「ぐあっ！？」
line = "「ぐあっ！？」"

[[dialogue]]
speaker = "エリス"
# 「大丈夫ですか、ミアさん……！　やはり囮役は私か会長さんがするべきだったのでは……」
line = "「大丈夫ですか、ミアさん……！　やはり囮役は私か会長さんがするべきだったのでは……」"

[[dialogue]]
speaker = "ミア"
# 「ダメ、ですよ……。これはあの子が私を子どもだって舐めてるからこその作戦なんですから……」
line = "「ダメ、ですよ……。これはあの子が私を子どもだって舐めてるからこその作戦なんですから……」"

[[dialogue]]
speaker = "ミア"
# 「それに私より強い２人を消耗させちゃったら本末転倒です……。こういうのは、一番戦力にならない人間がやるべきですから……！」
line = "「それに私より強い２人を消耗させちゃったら本末転倒です……。こういうのは、一番戦力にならない人間がやるべきですから……！」"

[[dialogue]]
speaker = "エリス"
# 「ミアさん……」
line = "「ミアさん……」"

[[dialogue]]
speaker = "ミア"
# 「私なら大丈夫です、まだ動けます……！　それより今は、３人であの子を……！」
line = "「私なら大丈夫です、まだ動けます……！　それより今は、３人であの子を……！」"

[[dialogue]]
speaker = "キサナ"
# 「ハハァ、まさか正義の味方サマが不意打ちとはよ……！　もっとお行儀のいいヤツらかと思ってたぜ……！」
line = "「ハハァ、まさか正義の味方サマが不意打ちとはよ……！　もっとお行儀のいいヤツらかと思ってたぜ……！」"

[[dialogue]]
speaker = "キサナ"
# 「いいじゃねえか！　ようやく愉しくなってきたぁっ！　３人まとめてかかってきな！　全員、蹴散らしてやんぜ！」
line = "「いいじゃねえか！　ようやく愉しくなってきたぁっ！　３人まとめてかかってきな！　全員、蹴散らしてやんぜ！」"

[[dialogue]]
speaker = "unk"
# 行くぞ、２人とも！
line = "行くぞ、２人とも！"

[[dialogue]]
speaker = "ミア"
# 「ええっ！」
line = "「ええっ！」"

[[dialogue]]
speaker = "エリス"
# 「はいっ！」
line = "「はいっ！」"
