[[dialogue]]
speaker = "ヴィーナス"
# 「ねぇ、今度、２つの学園の創立記念パーティーがあるじゃない？」
line = "「ねぇ、今度、２つの学園の創立記念パーティーがあるじゃない？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「せっかくだし、何かそこで楽しいイベントがやりたいわ！」
line = "「せっかくだし、何かそこで楽しいイベントがやりたいわ！」"

[[dialogue]]
speaker = "unk"
# ある日、星徒会で書類仕事をしていたところで、ヴィーナスが突然そんなことを言い出した。
line = "ある日、星徒会で書類仕事をしていたところで、ヴィーナスが突然そんなことを言い出した。"

[[dialogue]]
speaker = "アナ"
# 「そういえば、新星学園と流星学園って創立記念日が一緒なんでしたっけ？」
line = "「そういえば、新星学園と流星学園って創立記念日が一緒なんでしたっけ？」"

[[dialogue]]
speaker = "サーシャ"
# 「ええ。正確には、流星学園の創立記念日に合わせて、新星学園が開校されたのが始まりだったみたいね」
line = "「ええ。正確には、流星学園の創立記念日に合わせて、新星学園が開校されたのが始まりだったみたいね」"

[[dialogue]]
speaker = "マトイ"
# 「でも、イベントってなんで突然？」
line = "「でも、イベントってなんで突然？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「だって去年参加した時、みんなで会場に集まって食事するだけで、普通に終わっちゃったんだもの！」
line = "「だって去年参加した時、みんなで会場に集まって食事するだけで、普通に終わっちゃったんだもの！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ハロウィンとかクリスマスみたいに、何か凄いことが起きたり、楽しいことが起こったりしなかったわ！」
line = "「ハロウィンとかクリスマスみたいに、何か凄いことが起きたり、楽しいことが起こったりしなかったわ！」"

[[dialogue]]
speaker = "マトイ"
# 「いや、普通でいいでしょ……。むしろハロウィンとクリスマスに変なことが起き過ぎなだけで」
line = "「いや、普通でいいでしょ……。むしろハロウィンとクリスマスに変なことが起き過ぎなだけで」"

[[dialogue]]
speaker = "unk"
# と、その時だった。
line = "と、その時だった。"

[[dialogue]]
speaker = "アニマ"
# 「失礼するヨ、星徒会の諸君」
line = "「失礼するヨ、星徒会の諸君」"

[[dialogue]]
speaker = "unk"
# 今日はどうしたんですか？
line = "今日はどうしたんですか？"

[[dialogue]]
speaker = "unk"
# アニマ先輩、こんにちは
line = "アニマ先輩、こんにちは"

[[dialogue]]
speaker = "アニマ"
# 「やあ、会長。実はまた、イイ発明ができたから、その報告に来たんだヨ♪」
line = "「やあ、会長。実はまた、イイ発明ができたから、その報告に来たんだヨ♪」"

[[dialogue]]
speaker = "アナ"
# 「もしかして、<b>アレ</b>ですか？」
line = "「もしかして、<b>アレ</b>ですか？」"

[[dialogue]]
speaker = "アニマ"
# 「フヒ、察しがいいな、アナ。その通リ！　名づけて――『仮想結界システム』ダ♪」
line = "「フヒ、察しがいいな、アナ。その通リ！　名づけて――『仮想結界システム』ダ♪」"

[[dialogue]]
speaker = "アニマ"
# 「リップルのリゾート結界と、ルルカのクリスマスフォームが持つ仮想空間を作り出す能力のデータを元に、ツェツィーリエ、トレジアンナの協力も得て、ついに完成しタ」
line = "「リップルのリゾート結界と、ルルカのクリスマスフォームが持つ仮想空間を作り出す能力のデータを元に、ツェツィーリエ、トレジアンナの協力も得て、ついに完成しタ」"

[[dialogue]]
speaker = "アニマ"
# 「このシステムがあれば、周辺環境への配慮や、非常時に備えた星力温存の問題を解決して、本気の仮想戦闘を行うことができル」
line = "「このシステムがあれば、周辺環境への配慮や、非常時に備えた星力温存の問題を解決して、本気の仮想戦闘を行うことができル」"

[[dialogue]]
speaker = "アニマ"
# 「つまりは、キミたち星騎士が全力で戦い、より強くなれる環境が整うというわけダ！」
line = "「つまりは、キミたち星騎士が全力で戦い、より強くなれる環境が整うというわけダ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「全力で戦う……」
line = "「全力で戦う……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「それだわ！」
line = "「それだわ！」"

[[dialogue]]
speaker = "サーシャ"
# 「あら～♪　ヴィーナスちゃん、何か閃いたのね？」
line = "「あら～♪　ヴィーナスちゃん、何か閃いたのね？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ええ！　そのなんとかシステムを使って――」
line = "「ええ！　そのなんとかシステムを使って――」"

[[dialogue]]
speaker = "ヴィーナス"
# 「みんなで集まって、楽しいバトル大会をするのよ！！！」
line = "「みんなで集まって、楽しいバトル大会をするのよ！！！」"

[[dialogue]]
speaker = "unk"
# かくして、ヴィーナス発案の『バトル大会（仮）』が企画されることになり、その週に行われた合同会議でフィオナたち流星星徒会もまた、それを承認した。
line = "かくして、ヴィーナス発案の『バトル大会（仮）』が企画されることになり、その週に行われた合同会議でフィオナたち流星星徒会もまた、それを承認した。"

[[dialogue]]
speaker = "unk"
# そして、企画が通った翌日――
line = "そして、企画が通った翌日――"

[[dialogue]]
speaker = "ヴィーナス"
# 「たのもー！！」
line = "「たのもー！！」"

[[dialogue]]
speaker = "フィオナ"
# 「きゃっ、ヴィーナスさん！？　いきなり入って来るので、ビックリしました……！」
line = "「きゃっ、ヴィーナスさん！？　いきなり入って来るので、ビックリしました……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「こんにちは、フィオナ！　今はあなた１人なの？」
line = "「こんにちは、フィオナ！　今はあなた１人なの？」"

[[dialogue]]
speaker = "フィオナ"
# 「はい。ちょうどみんなには、外回りの仕事をお願いしてまして」
line = "「はい。ちょうどみんなには、外回りの仕事をお願いしてまして」"

[[dialogue]]
speaker = "フィオナ"
# 「それで、今日はどうされましたか？　もしかして例のバトル大会について何かご相談でしょうか？」
line = "「それで、今日はどうされましたか？　もしかして例のバトル大会について何かご相談でしょうか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そうだけど、そうじゃないわ！　私、今日は宣戦布告に来たのよ！」
line = "「そうだけど、そうじゃないわ！　私、今日は宣戦布告に来たのよ！」"

[[dialogue]]
speaker = "フィオナ"
# 「せ、宣戦布告……ですか？」
line = "「せ、宣戦布告……ですか？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「そう！　ねぇ、フィオナ！」
line = "「そう！　ねぇ、フィオナ！」"

[[dialogue]]
speaker = "unk"
# ヴィーナスはフィオナの両手を取ると、顔をぐっと勢いよく近づける。
line = "ヴィーナスはフィオナの両手を取ると、顔をぐっと勢いよく近づける。"

[[dialogue]]
speaker = "ヴィーナス"
# 「私――フィオナと全力でバトルがしてみたいわ！！」
line = "「私――フィオナと全力でバトルがしてみたいわ！！」"

[[dialogue]]
speaker = "フィオナ"
# 「えっ……！？」
line = "「えっ……！？」"

[[dialogue]]
speaker = "unk"
# キラキラと瞳を子供のように輝かせながら言うヴィーナスに、フィオナは目をぱちくりさせてしまうのだった――
line = "キラキラと瞳を子供のように輝かせながら言うヴィーナスに、フィオナは目をぱちくりさせてしまうのだった――"
