[[dialogue]]
speaker = "ウィステリア"
# 「ほんとゴメンね！　私が目を離した隙にあんなことになっちゃって」
line = "「ほんとゴメンね！　私が目を離した隙にあんなことになっちゃって」"

[[dialogue]]
speaker = "モネ"
# 「はぁ、はぁ……あの図書館はいったい何だったんですか？」
line = "「はぁ、はぁ……あの図書館はいったい何だったんですか？」"

[[dialogue]]
speaker = "ウィステリア"
# 「新星学園と私は、あれを“地下図書館”と呼んでいるわ」
line = "「新星学園と私は、あれを“地下図書館”と呼んでいるわ」"

[[dialogue]]
speaker = "モネ"
# 「地下図書館？」
line = "「地下図書館？」"

[[dialogue]]
speaker = "ウィステリア"
# 「地下図書館の座標は、新星学園の真下、地下３０００メートル。本来なら図書館なんて存在しえない場所よ」
line = "「地下図書館の座標は、新星学園の真下、地下３０００メートル。本来なら図書館なんて存在しえない場所よ」"

[[dialogue]]
speaker = "ウィステリア"
# 「なのにあの図書館は確かにある。星力か、はたまた他の力か……とにかく何かが作用しているのは間違いないわね」
line = "「なのにあの図書館は確かにある。星力か、はたまた他の力か……とにかく何かが作用しているのは間違いないわね」"

[[dialogue]]
speaker = "ウィステリア"
# 「そして、新星学園の図書館とは異空間を通じて繋がっている。危ないから普段は私が出入口を封印してるけど」
line = "「そして、新星学園の図書館とは異空間を通じて繋がっている。危ないから普段は私が出入口を封印してるけど」"

[[dialogue]]
speaker = "イクシリオン"
# 「あの偽物のウィステリアさんは？」
line = "「あの偽物のウィステリアさんは？」"

[[dialogue]]
speaker = "ウィステリア"
# 「地下図書館の防衛システムよ。私の姿と技を模倣して、侵入者を撃退しようとしているの。まぁ、私はいつも吹っ飛ばして進んでるけど」
line = "「地下図書館の防衛システムよ。私の姿と技を模倣して、侵入者を撃退しようとしているの。まぁ、私はいつも吹っ飛ばして進んでるけど」"

[[dialogue]]
speaker = "ウィステリア"
# 「私は普通の司書をする傍ら、新星学園の指示で地下図書館を調査しているわ」
line = "「私は普通の司書をする傍ら、新星学園の指示で地下図書館を調査しているわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「今のところ成果はほとんどないけどね。蔵書の解読も進んでないし」
line = "「今のところ成果はほとんどないけどね。蔵書の解読も進んでないし」"

[[dialogue]]
speaker = "ウィステリア"
# 「紙屋敷さんが図書委員として頑張ってるから、私も成果を出そうと思って深く潜ってみたんだけど……入口のロックが外れちゃって２人が落ちちゃったみたい」
line = "「紙屋敷さんが図書委員として頑張ってるから、私も成果を出そうと思って深く潜ってみたんだけど……入口のロックが外れちゃって２人が落ちちゃったみたい」"

[[dialogue]]
speaker = "ウィステリア"
# 「私のミスだわ。ごめんなさい」
line = "「私のミスだわ。ごめんなさい」"

[[dialogue]]
speaker = "イクシリオン"
# 「いえ、助けていただいたのでそれはいいのですが……」
line = "「いえ、助けていただいたのでそれはいいのですが……」"

[[dialogue]]
speaker = "モネ"
# 「ウィステリアさんって星騎士だったんですか？」
line = "「ウィステリアさんって星騎士だったんですか？」"

[[dialogue]]
speaker = "ウィステリア"
# 「あ」
line = "「あ」"

[[dialogue]]
speaker = "ウィステリア"
# 「えーと……あー……うん、そうなのよ。一応流星学園のＯＧでね、学生時代は鳴かず飛ばずの目立たない星騎士だったわ……」
line = "「えーと……あー……うん、そうなのよ。一応流星学園のＯＧでね、学生時代は鳴かず飛ばずの目立たない星騎士だったわ……」"

[[dialogue]]
speaker = "イクシリオン"
# 「あの強さでそれは無理があると思います」
line = "「あの強さでそれは無理があると思います」"

[[dialogue]]
speaker = "モネ"
# 「そうですよ、本当に強くない私の身にもなってください」
line = "「そうですよ、本当に強くない私の身にもなってください」"

[[dialogue]]
speaker = "ウィステリア"
# 「はい、ごめんなさい……」
line = "「はい、ごめんなさい……」"

[[dialogue]]
speaker = "ウィステリア"
# 「……あれ？　今の私が謝るところ？」
line = "「……あれ？　今の私が謝るところ？」"

[[dialogue]]
speaker = "ウィステリア"
# 「とにかく、私が星騎士だったことも含めて、このことは他の生徒には秘密にしておいて！　お願い！」
line = "「とにかく、私が星騎士だったことも含めて、このことは他の生徒には秘密にしておいて！　お願い！」"

[[dialogue]]
speaker = "モネ"
# 「わかりました」
line = "「わかりました」"

[[dialogue]]
speaker = "ウィステリア"
# 「ありがとう！」
line = "「ありがとう！」"

[[dialogue]]
speaker = "モネ"
# 「その代わり、ウィステリアさんの余裕がある時でいいので、私も地下図書館に連れて行ってもらえませんか？」
line = "「その代わり、ウィステリアさんの余裕がある時でいいので、私も地下図書館に連れて行ってもらえませんか？」"

[[dialogue]]
speaker = "ウィステリア"
# 「えっ？」
line = "「えっ？」"

[[dialogue]]
speaker = "イクシリオン"
# 「私もまた行ってみたいです！」
line = "「私もまた行ってみたいです！」"

[[dialogue]]
speaker = "イクシリオン"
# （誰にも知られていない未知の図書館……きっと秘蔵のいやらし本があるに違いありません！）
line = "（誰にも知られていない未知の図書館……きっと秘蔵のいやらし本があるに違いありません！）"

[[dialogue]]
speaker = "ウィステリア"
# 「イクシーさんも！？」
line = "「イクシーさんも！？」"

[[dialogue]]
speaker = "ウィステリア"
# 「はぁ、仕方ないわね……。もっと安全に探索できるようになって、学園の許可が出たら、一緒に連れて行ってあげる。それでいい？」
line = "「はぁ、仕方ないわね……。もっと安全に探索できるようになって、学園の許可が出たら、一緒に連れて行ってあげる。それでいい？」"

[[dialogue]]
speaker = "２人"
# 「はい！」
line = "「はい！」"

[[dialogue]]
speaker = "unk"
# それから数日──
line = "それから数日──"

[[dialogue]]
speaker = "モネ"
# 「すみません、遅くなりましたっ」
line = "「すみません、遅くなりましたっ」"

[[dialogue]]
speaker = "ウィステリア"
# 「図書館大好きな紙屋敷さんが、図書委員の当番に遅れるなんて珍しいわね。何かあったの？」
line = "「図書館大好きな紙屋敷さんが、図書委員の当番に遅れるなんて珍しいわね。何かあったの？」"

[[dialogue]]
speaker = "モネ"
# 「ここに来る途中、おすすめの本を知りたいって声をかけられちゃいまして。対応してたらこんな時間に……」
line = "「ここに来る途中、おすすめの本を知りたいって声をかけられちゃいまして。対応してたらこんな時間に……」"

[[dialogue]]
speaker = "ウィステリア"
# 「それなら仕方ないわね。図書委員のお仕事お疲れ様」
line = "「それなら仕方ないわね。図書委員のお仕事お疲れ様」"

[[dialogue]]
speaker = "ウィステリア"
# 「それにしても、紙屋敷さんは蔵書の内容だけじゃなくて、どの本がどこにあるかまで完璧に覚えているのね」
line = "「それにしても、紙屋敷さんは蔵書の内容だけじゃなくて、どの本がどこにあるかまで完璧に覚えているのね」"

[[dialogue]]
speaker = "モネ"
# 「本は友達ですから。友達がどこにいるのか覚えているのは当然です」
line = "「本は友達ですから。友達がどこにいるのか覚えているのは当然です」"

[[dialogue]]
speaker = "ウィステリア"
# 「ふふ、それもそうね」
line = "「ふふ、それもそうね」"

[[dialogue]]
speaker = "モネ"
# 「そして皆さんに紹介するために、新しく入った本を読みたいのですが……」
line = "「そして皆さんに紹介するために、新しく入った本を読みたいのですが……」"

[[dialogue]]
speaker = "ウィステリア"
# 「ダ～メ。仕事しなさい」
line = "「ダ～メ。仕事しなさい」"

[[dialogue]]
speaker = "モネ"
# 「はーい」
line = "「はーい」"

[[dialogue]]
speaker = "カティア"
# 「モネせんぱーい」
line = "「モネせんぱーい」"

[[dialogue]]
speaker = "モネ"
# 「カティアさん、こんにちは。カティアさんが図書館に来てくれて嬉しいです」
line = "「カティアさん、こんにちは。カティアさんが図書館に来てくれて嬉しいです」"

[[dialogue]]
speaker = "カティア"
# 「べ、別に本が好きになったわけじゃないんですからね」
line = "「べ、別に本が好きになったわけじゃないんですからね」"

[[dialogue]]
speaker = "モネ"
# 「それでもいいんですよ。何かご用ですか？」
line = "「それでもいいんですよ。何かご用ですか？」"

[[dialogue]]
speaker = "カティア"
# 「この前借りた図鑑と園芸の本なんですけど、これって延長とかできますか？」
line = "「この前借りた図鑑と園芸の本なんですけど、これって延長とかできますか？」"

[[dialogue]]
speaker = "モネ"
# 「確認します。……次の予約は入ってないので可能ですね。手続きしておきます」
line = "「確認します。……次の予約は入ってないので可能ですね。手続きしておきます」"

[[dialogue]]
speaker = "モネ"
# 「ただ延長は１度までです。次の期限までには必ず返却お願いします」
line = "「ただ延長は１度までです。次の期限までには必ず返却お願いします」"

[[dialogue]]
speaker = "カティア"
# 「はーい」
line = "「はーい」"

[[dialogue]]
speaker = "蛍火"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "モネ"
# 「あ、蛍火さん」
line = "「あ、蛍火さん」"

[[dialogue]]
speaker = "蛍火"
# 「先日お借りした本、とても興味深かったです。また料理に関する本をご紹介いただきたいのですが」
line = "「先日お借りした本、とても興味深かったです。また料理に関する本をご紹介いただきたいのですが」"

[[dialogue]]
speaker = "モネ"
# 「蛍火さんのお眼鏡にかなったようで何よりです。でしたら中南米の料理の本なんていかがでしょう。発見があるかもしれませんよ」
line = "「蛍火さんのお眼鏡にかなったようで何よりです。でしたら中南米の料理の本なんていかがでしょう。発見があるかもしれませんよ」"

[[dialogue]]
speaker = "蛍火"
# 「確かにその地域の料理にはあまり明るくないですね。お借りします」
line = "「確かにその地域の料理にはあまり明るくないですね。お借りします」"

[[dialogue]]
speaker = "モネ"
# 「どうぞ。この本の返却期限は２週間です」
line = "「どうぞ。この本の返却期限は２週間です」"

[[dialogue]]
speaker = "モネ"
# 「受付落ち着いたので、返却された本を書架に戻してきますね」
line = "「受付落ち着いたので、返却された本を書架に戻してきますね」"

[[dialogue]]
speaker = "ウィステリア"
# 「ええ、私は拾得物のチェックをしてるわ」
line = "「ええ、私は拾得物のチェックをしてるわ」"

[[dialogue]]
speaker = "ウィステリア"
# 「紙屋敷さんったら歩く図書館になっちゃった。大したものね」
line = "「紙屋敷さんったら歩く図書館になっちゃった。大したものね」"

[[dialogue]]
speaker = "ウィステリア"
# 「私が何もしなくても図書館の利用者が増えたし、私よりよっぽど司書らしい気がするわ」
line = "「私が何もしなくても図書館の利用者が増えたし、私よりよっぽど司書らしい気がするわ」"

[[dialogue]]
speaker = "イクシリオン"
# 「ふむふむ……赤ずきんの元になった物語には、女の子が服を脱ぐものがあったと」
line = "「ふむふむ……赤ずきんの元になった物語には、女の子が服を脱ぐものがあったと」"

[[dialogue]]
speaker = "イクシリオン"
# 「ベッドに潜むオオカミに騙されて、一枚一枚服を脱ぎ捨てていく赤ずきんちゃん……こう、ぐっと来るものがあります」
line = "「ベッドに潜むオオカミに騙されて、一枚一枚服を脱ぎ捨てていく赤ずきんちゃん……こう、ぐっと来るものがあります」"

[[dialogue]]
speaker = "ウィステリア"
# 「手伝ってくれたのはありがたかったけど、イクシーさんのことは掴み切れなかったわね……」
line = "「手伝ってくれたのはありがたかったけど、イクシーさんのことは掴み切れなかったわね……」"

[[dialogue]]
speaker = "モネ"
# 「戻りましたー」
line = "「戻りましたー」"

[[dialogue]]
speaker = "ウィステリア"
# 「おかえりなさい」
line = "「おかえりなさい」"

[[dialogue]]
speaker = "メルエル"
# 「モネちゃん、また来たよ。あの小説、本当に胸がキュンキュンした！　同じ作者さんの小説ってあるかな？」
line = "「モネちゃん、また来たよ。あの小説、本当に胸がキュンキュンした！　同じ作者さんの小説ってあるかな？」"

[[dialogue]]
speaker = "モネ"
# 「もちろんです。実はあの作者さん、切ないお話も得意で、涙なしでは語れないと言っても過言ではありません」
line = "「もちろんです。実はあの作者さん、切ないお話も得意で、涙なしでは語れないと言っても過言ではありません」"

[[dialogue]]
speaker = "メルエル"
# 「そうなの！？　気になる～！」
line = "「そうなの！？　気になる～！」"

[[dialogue]]
speaker = "ユーリス"
# 「すみません、この前の続きを借りたいのですが……」
line = "「すみません、この前の続きを借りたいのですが……」"

[[dialogue]]
speaker = "モネ"
# 「こちらですね。１度に借りられるのは５冊までですので注意してください」
line = "「こちらですね。１度に借りられるのは５冊までですので注意してください」"

[[dialogue]]
speaker = "ユーリス"
# 「ありがとうございます。恥ずかしながら我が国は再建中で、自分も節約をしているので……無料で利用できるのは助かります」
line = "「ありがとうございます。恥ずかしながら我が国は再建中で、自分も節約をしているので……無料で利用できるのは助かります」"

[[dialogue]]
speaker = "サーシャ"
# 「聞いたわよ～、出張図書コンシェルジュ、大成功ね～」
line = "「聞いたわよ～、出張図書コンシェルジュ、大成功ね～」"

[[dialogue]]
speaker = "アナ"
# 「お見事」
line = "「お見事」"

[[dialogue]]
speaker = "モネ"
# 「えへへ……ありがとうございます。おふたりに話を聞いてもらったおかげです」
line = "「えへへ……ありがとうございます。おふたりに話を聞いてもらったおかげです」"

[[dialogue]]
speaker = "アナ"
# 「私は何もしていません」
line = "「私は何もしていません」"

[[dialogue]]
speaker = "サーシャ"
# 「そうよ～。モネちゃんにしては大胆な作戦だから驚いちゃった」
line = "「そうよ～。モネちゃんにしては大胆な作戦だから驚いちゃった」"

[[dialogue]]
speaker = "イクシリオン"
# 「ふふ、大人気ですね、モネさん」
line = "「ふふ、大人気ですね、モネさん」"

[[dialogue]]
speaker = "モネ"
# 「あはは……嬉しいやら恥ずかしいやら」
line = "「あはは……嬉しいやら恥ずかしいやら」"

[[dialogue]]
speaker = "モネ"
# 「イクシーさんも手伝ってくれてありがとうございました。思っていたよりうまくいって、私も本たちも喜んでいます」
line = "「イクシーさんも手伝ってくれてありがとうございました。思っていたよりうまくいって、私も本たちも喜んでいます」"

[[dialogue]]
speaker = "モネ"
# 「そしてこの流れを一時的なものにしないよう、これからも頑張っていきたいと思います」
line = "「そしてこの流れを一時的なものにしないよう、これからも頑張っていきたいと思います」"

[[dialogue]]
speaker = "イクシリオン"
# 「さすがモネさん。図書委員の鑑です」
line = "「さすがモネさん。図書委員の鑑です」"

[[dialogue]]
speaker = "モネ"
# 「もう、だから褒めすぎですってば」
line = "「もう、だから褒めすぎですってば」"

[[dialogue]]
speaker = "モネ"
# （ゆくゆくはあの地下図書館も利用者が来ますように……と思うのは欲張りすぎでしょうか）
line = "（ゆくゆくはあの地下図書館も利用者が来ますように……と思うのは欲張りすぎでしょうか）"

[[dialogue]]
speaker = "モネ"
# （あの図書館の子たちも読む人を待っている……そんな気がします）
line = "（あの図書館の子たちも読む人を待っている……そんな気がします）"

[[dialogue]]
speaker = "ウィステリア"
# 「紙屋敷さんのおかげで利用者が増えたし、これできっとクビも回避できたわね」
line = "「紙屋敷さんのおかげで利用者が増えたし、これできっとクビも回避できたわね」"

[[dialogue]]
speaker = "ウィステリア"
# 「今日の仕事は……本の修繕と、企画会議と、新しく入れる本の選定と、書類作成と……あれ？　いつもより仕事が立て込んでいるような……」
line = "「今日の仕事は……本の修繕と、企画会議と、新しく入れる本の選定と、書類作成と……あれ？　いつもより仕事が立て込んでいるような……」"

[[dialogue]]
speaker = "ウィステリア"
# 「って、このままじゃ残業じゃないっ。やっぱり不運だわ……」
line = "「って、このままじゃ残業じゃないっ。やっぱり不運だわ……」"

[[dialogue]]
speaker = "ウィステリア"
# 「でも……たまにはこういうのもいいわよね」
line = "「でも……たまにはこういうのもいいわよね」"

[[dialogue]]
speaker = "ウィステリア"
# 「さ、仕事仕事。これでも司書なんだから、紙屋敷さんには負けてられないわ」
line = "「さ、仕事仕事。これでも司書なんだから、紙屋敷さんには負けてられないわ」"
