[[dialogue]]
speaker = "unk"
# その日の夜。
line = "その日の夜。"

[[dialogue]]
speaker = "unk"
# 九浄家の屋敷に戻った後、ヨミは蘭美の元を訪ねていた。
line = "九浄家の屋敷に戻った後、ヨミは蘭美の元を訪ねていた。"

[[dialogue]]
speaker = "蘭美"
# 「ヨミ、今日はどうしたのかしら！　浮かない顔をしているみたいだけれど」
line = "「ヨミ、今日はどうしたのかしら！　浮かない顔をしているみたいだけれど」"

[[dialogue]]
speaker = "ヨミ"
# 「メイド長……」
line = "「メイド長……」"

[[dialogue]]
speaker = "ヨミ"
# 「私……教育係になるのは早かったかもしれません」
line = "「私……教育係になるのは早かったかもしれません」"

[[dialogue]]
speaker = "蘭美"
# 「あら、それはどうして？」
line = "「あら、それはどうして？」"

[[dialogue]]
speaker = "ヨミ"
# 「狛里さんの問題に気づいていたのに、指摘できなくて。今日あったモンスターとの戦闘で、怪我をさせてしまいました……」
line = "「狛里さんの問題に気づいていたのに、指摘できなくて。今日あったモンスターとの戦闘で、怪我をさせてしまいました……」"

[[dialogue]]
speaker = "ヨミ"
# 「先輩失格です……。それで、どうしたらいいか、私１人ではわからなくて」
line = "「先輩失格です……。それで、どうしたらいいか、私１人ではわからなくて」"

[[dialogue]]
speaker = "蘭美"
# 「なるほどね……」
line = "「なるほどね……」"

[[dialogue]]
speaker = "unk"
# 蘭美は少しだけ考え込む。
line = "蘭美は少しだけ考え込む。"

[[dialogue]]
speaker = "蘭美"
# 「なら、そうね――会長に話を聞いてもらいなさい！」
line = "「なら、そうね――会長に話を聞いてもらいなさい！」"

[[dialogue]]
speaker = "ヨミ"
# 「え？　会長……ですか？」
line = "「え？　会長……ですか？」"

[[dialogue]]
speaker = "蘭美"
# 「ええ。私からも話を聞いてもらえるように頼んでおくわ！」
line = "「ええ。私からも話を聞いてもらえるように頼んでおくわ！」"

[[dialogue]]
speaker = "unk"
# 翌日の昼休み。
line = "翌日の昼休み。"

[[dialogue]]
speaker = "unk"
# ヨミは蘭美に言われた通り、会長――クロトに事情を打ち明けた。
line = "ヨミは蘭美に言われた通り、会長――クロトに事情を打ち明けた。"

[[dialogue]]
speaker = "クロト"
# 「――なるほど」
line = "「――なるほど」"

[[dialogue]]
speaker = "unk"
# 会長は最後まで口を挟まず、真剣な表情で話を聞いてくれた。
line = "会長は最後まで口を挟まず、真剣な表情で話を聞いてくれた。"

[[dialogue]]
speaker = "ヨミ"
# 「私……狛里さんにちゃんと指摘できなかったんです」
line = "「私……狛里さんにちゃんと指摘できなかったんです」"

[[dialogue]]
speaker = "ヨミ"
# 「もし私が間違っていたらって、自信を持てなくて……」
line = "「もし私が間違っていたらって、自信を持てなくて……」"

[[dialogue]]
speaker = "クロト"
# 「ヨミは真面目だもんな。だからこそ、間違えないように慎重になる」
line = "「ヨミは真面目だもんな。だからこそ、間違えないように慎重になる」"

[[dialogue]]
speaker = "クロト"
# 「でも、自信がなくても、ヨミが『先輩』になったって事実は変わらないと思うんだ」
line = "「でも、自信がなくても、ヨミが『先輩』になったって事実は変わらないと思うんだ」"

[[dialogue]]
speaker = "ヨミ"
# 「私が、『先輩』になった事実……」
line = "「私が、『先輩』になった事実……」"

[[dialogue]]
speaker = "クロト"
# 「狛里が来るまで、ヨミはメイド隊の中でも『後輩』、新人寄りだっただろ？」
line = "「狛里が来るまで、ヨミはメイド隊の中でも『後輩』、新人寄りだっただろ？」"

[[dialogue]]
speaker = "クロト"
# 「だから、謙虚であれば誰からも叱られることはなかった。でも、ヒトの上に立つとなったら、謙虚ってだけじゃダメだと思うんだ」
line = "「だから、謙虚であれば誰からも叱られることはなかった。でも、ヒトの上に立つとなったら、謙虚ってだけじゃダメだと思うんだ」"

[[dialogue]]
speaker = "クロト"
# 「ヒトは誰だって、いつかヒトの上に立つことを求められる。先輩であったり、上司であったり、親であったり、さ」
line = "「ヒトは誰だって、いつかヒトの上に立つことを求められる。先輩であったり、上司であったり、親であったり、さ」"

[[dialogue]]
speaker = "クロト"
# 「そうなった時、上に立つ側には、ついてきてくれるヒトに対しての責任が発生すると思うんだ」
line = "「そうなった時、上に立つ側には、ついてきてくれるヒトに対しての責任が発生すると思うんだ」"

[[dialogue]]
speaker = "ヨミ"
# 「責任……はい。確かにそう、だと思います」
line = "「責任……はい。確かにそう、だと思います」"

[[dialogue]]
speaker = "クロト"
# 「……俺もさ、最初から会長になろうと思ってなったわけじゃない」
line = "「……俺もさ、最初から会長になろうと思ってなったわけじゃない」"

[[dialogue]]
speaker = "クロト"
# 「ヴィーナスに突然指名されて、その流れで会長になった」
line = "「ヴィーナスに突然指名されて、その流れで会長になった」"

[[dialogue]]
speaker = "クロト"
# 「でも、会長になった以上は、やるしかない。これは『覚悟』の問題なんだ」
line = "「でも、会長になった以上は、やるしかない。これは『覚悟』の問題なんだ」"

[[dialogue]]
speaker = "ヨミ"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "クロト"
# 「失敗は必ずある。失望されるのも怖い」
line = "「失敗は必ずある。失望されるのも怖い」"

[[dialogue]]
speaker = "クロト"
# 「だけど、それで周りの顔色ばっかりうかがっている『不安』だらけのリーダーには、誰もついていきたくないだろ？」
line = "「だけど、それで周りの顔色ばっかりうかがっている『不安』だらけのリーダーには、誰もついていきたくないだろ？」"

[[dialogue]]
speaker = "クロト"
# 「不安があったとしても、不安を感じさせない。自信がなくても、自信のなさを感じさせない」
line = "「不安があったとしても、不安を感じさせない。自信がなくても、自信のなさを感じさせない」"

[[dialogue]]
speaker = "クロト"
# 「そういう、『ついてきてくれる人のための腹のくくり方』を覚悟って呼ぶんじゃないかな」
line = "「そういう、『ついてきてくれる人のための腹のくくり方』を覚悟って呼ぶんじゃないかな」"

[[dialogue]]
speaker = "クロト"
# 「……そしてそれは『リーダー』だけじゃなくて、『先輩』も同じだ」
line = "「……そしてそれは『リーダー』だけじゃなくて、『先輩』も同じだ」"

[[dialogue]]
speaker = "クロト"
# 「自信があるから、先輩になるわけじゃない」
line = "「自信があるから、先輩になるわけじゃない」"

[[dialogue]]
speaker = "クロト"
# 「後輩ができたから『後輩のために腹をくくる』。その覚悟が、その人を先輩たらしめるんだ」
line = "「後輩ができたから『後輩のために腹をくくる』。その覚悟が、その人を先輩たらしめるんだ」"

[[dialogue]]
speaker = "unk"
# その言葉に、ヨミは思わず目を見開いた。
line = "その言葉に、ヨミは思わず目を見開いた。"

[[dialogue]]
speaker = "ヨミ"
# 「狛里さんのために、私が腹をくくる覚悟……」
line = "「狛里さんのために、私が腹をくくる覚悟……」"

[[dialogue]]
speaker = "クロト"
# 「だからヨミも、自信がついてから教育係になるんじゃなくて」
line = "「だからヨミも、自信がついてから教育係になるんじゃなくて」"

[[dialogue]]
speaker = "クロト"
# 「狛里のために、狛里の先輩になるって……自分が心に決めるんだ」
line = "「狛里のために、狛里の先輩になるって……自分が心に決めるんだ」"

[[dialogue]]
speaker = "ヨミ"
# 「自分が、心に決める……」
line = "「自分が、心に決める……」"

[[dialogue]]
speaker = "クロト"
# 「うん。教育係だって、初めて後輩を指導する時は初心者だ。だから、間違うこともあるかもしれない」
line = "「うん。教育係だって、初めて後輩を指導する時は初心者だ。だから、間違うこともあるかもしれない」"

[[dialogue]]
speaker = "クロト"
# 「でも、その時は俺や、蘭美や、ヘレナちゃんが『それは違うんじゃないか？』って、ちゃんと指摘する」
line = "「でも、その時は俺や、蘭美や、ヘレナちゃんが『それは違うんじゃないか？』って、ちゃんと指摘する」"

[[dialogue]]
speaker = "クロト"
# 「だからヨミも、狛里のやっていることがよくないって思ったら、ちゃんと伝えてあげてほしい」
line = "「だからヨミも、狛里のやっていることがよくないって思ったら、ちゃんと伝えてあげてほしい」"

[[dialogue]]
speaker = "クロト"
# 「それが『先輩』の役目だから」
line = "「それが『先輩』の役目だから」"

[[dialogue]]
speaker = "ヨミ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# ヨミは静かに俯く。
line = "ヨミは静かに俯く。"

[[dialogue]]
speaker = "ヨミ"
# （そうだ……）
line = "（そうだ……）"

[[dialogue]]
speaker = "ヨミ"
# （私も周りの人たちに、こうして教えてもらってきた）
line = "（私も周りの人たちに、こうして教えてもらってきた）"

[[dialogue]]
speaker = "ヨミ"
# （だったら今度は……）
line = "（だったら今度は……）"

[[dialogue]]
speaker = "ヨミ"
# （私が、狛里さんに教える番なんだ！）
line = "（私が、狛里さんに教える番なんだ！）"

[[dialogue]]
speaker = "unk"
# ヨミは顔を上げる。
line = "ヨミは顔を上げる。"

[[dialogue]]
speaker = "ヨミ"
# 「会長、私――」
line = "「会長、私――」"

[[dialogue]]
speaker = "ヨミ"
# 「もう１度、ちゃんと狛里さんに伝えてみます」
line = "「もう１度、ちゃんと狛里さんに伝えてみます」"

[[dialogue]]
speaker = "クロト"
# 「うん、その意気だ」
line = "「うん、その意気だ」"

[[dialogue]]
speaker = "unk"
# 会長は微笑みながら、サムズアップをしてみせる。
line = "会長は微笑みながら、サムズアップをしてみせる。"

[[dialogue]]
speaker = "クロト"
# 「頑張れ、ヨミ<b>先輩</b>！」
line = "「頑張れ、ヨミ<b>先輩</b>！」"

[[dialogue]]
speaker = "ヨミ"
# 「！　……はいっ！」
line = "「！　……はいっ！」"

[[dialogue]]
speaker = "unk"
# ヨミも力強く頷いてみせるのだった。
line = "ヨミも力強く頷いてみせるのだった。"
