[[dialogue]]
speaker = "unk"
# 俺はある日、ＤＩＳＣで呼び出しを受けて、大聖堂へとやって来ていた。
line = "俺はある日、ＤＩＳＣで呼び出しを受けて、大聖堂へとやって来ていた。"

[[dialogue]]
speaker = "unk"
# 少し待っていると、入り口の扉が開いて、１人の女生徒が<b>日傘を差したまま</b>入って来る。
line = "少し待っていると、入り口の扉が開いて、１人の女生徒が<b>日傘を差したまま</b>入って来る。"

[[dialogue]]
speaker = "ジュエリー"
# 「やあ、来てくれてありがとう、我が助手」
line = "「やあ、来てくれてありがとう、我が助手」"

[[dialogue]]
speaker = "ジュエリー"
# 「ひょっとして待たせてしまったかい？」
line = "「ひょっとして待たせてしまったかい？」"

[[dialogue]]
speaker = "unk"
# 大丈夫、今来たところだよ
line = "大丈夫、今来たところだよ"

[[dialogue]]
speaker = "ジュエリー"
# 「ならよかった。……すまないね。いざキミと会うとなると、つい自分の身だしなみが気になってしまうんだよ」
line = "「ならよかった。……すまないね。いざキミと会うとなると、つい自分の身だしなみが気になってしまうんだよ」"

[[dialogue]]
speaker = "ジュエリー"
# 「ここに来る前にちょっとセットして来たんだ。どうだろう？　変なところはないかな？」
line = "「ここに来る前にちょっとセットして来たんだ。どうだろう？　変なところはないかな？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふふっ♪　愛する助手の前では、可愛い自分でいたいからね」
line = "「ふふっ♪　愛する助手の前では、可愛い自分でいたいからね」"

[[dialogue]]
speaker = "unk"
# そう言ってくるくると日傘を回す彼女は、流星学園１年生の『ジュエリー・ブラウン』。
line = "そう言ってくるくると日傘を回す彼女は、流星学園１年生の『ジュエリー・ブラウン』。"

[[dialogue]]
speaker = "unk"
# 流星市国や日本で数々の事件を解決している『名探偵』であり、屋内外問わず日傘を差している姿から『日傘探偵』という愛称で呼ばれている。
line = "流星市国や日本で数々の事件を解決している『名探偵』であり、屋内外問わず日傘を差している姿から『日傘探偵』という愛称で呼ばれている。"

[[dialogue]]
speaker = "unk"
# 日傘を差しているのは生まれつき肌が弱く、日光に当たると火傷してしまうという真っ当な理由なのだが──
line = "日傘を差しているのは生まれつき肌が弱く、日光に当たると火傷してしまうという真っ当な理由なのだが──"

[[dialogue]]
speaker = "unk"
# 屋内でも日傘を差しているのは、そうして常に手に持っていれば、どこかに日傘を置き忘れて困る心配がないから、というズボラな理由だったりする。
line = "屋内でも日傘を差しているのは、そうして常に手に持っていれば、どこかに日傘を置き忘れて困る心配がないから、というズボラな理由だったりする。"

[[dialogue]]
speaker = "ジュエリー"
# 「ああ、そうだ。それでキミを呼び出した用件だったね――」
line = "「ああ、そうだ。それでキミを呼び出した用件だったね――」"

[[dialogue]]
speaker = "ジュエリー"
# 「以前、キミにも話したことがあるだろう？　私と同じ選星者の１人で、友人の『予言者』がいると」
line = "「以前、キミにも話したことがあるだろう？　私と同じ選星者の１人で、友人の『予言者』がいると」"

[[dialogue]]
speaker = "ジュエリー"
# 「彼女からまた、予言を受けてね。それでキミに協力をお願いしたいんだ」
line = "「彼女からまた、予言を受けてね。それでキミに協力をお願いしたいんだ」"

[[dialogue]]
speaker = "unk"
# その予言って……？
line = "その予言って……？"

[[dialogue]]
speaker = "ジュエリー"
# 「友人曰く、魔王との絆によって、私の力が覚醒を迎える……とのことらしい」
line = "「友人曰く、魔王との絆によって、私の力が覚醒を迎える……とのことらしい」"

[[dialogue]]
speaker = "ジュエリー"
# 「キミのこれまでの経緯を踏まえて、その言葉を明解に換言するならば――」
line = "「キミのこれまでの経緯を踏まえて、その言葉を明解に換言するならば――」"

[[dialogue]]
speaker = "ジュエリー"
# 「魔王と絆を結んだ者を覚醒させる術『アルケインコード』によって、私の新たな力が目覚める、ということではないかと推察できる」
line = "「魔王と絆を結んだ者を覚醒させる術『アルケインコード』によって、私の新たな力が目覚める、ということではないかと推察できる」"

[[dialogue]]
speaker = "unk"
# ジュエリーが『ノヴァフォーム』に！？
line = "ジュエリーが『ノヴァフォーム』に！？"

[[dialogue]]
speaker = "ジュエリー"
# 「もしそれが本当ならば、私としては願ってもないことだ。キミとの絆……それは明解に換言するならば、つまり――」
line = "「もしそれが本当ならば、私としては願ってもないことだ。キミとの絆……それは明解に換言するならば、つまり――」"

[[dialogue]]
speaker = "ジュエリー"
# 「キミとの『愛』、ということに他ならないからね。ふふっ♪」
line = "「キミとの『愛』、ということに他ならないからね。ふふっ♪」"

[[dialogue]]
speaker = "unk"
# あ、愛って……
line = "あ、愛って……"

[[dialogue]]
speaker = "unk"
# ジュエリーは俺に対してよく、『愛している』という言葉を口にする。
line = "ジュエリーは俺に対してよく、『愛している』という言葉を口にする。"

[[dialogue]]
speaker = "unk"
# 普通のテンションでさらっと言うので、どこまで本気なのかよくわからず、俺はいつもくすぐったい気持ちになる。
line = "普通のテンションでさらっと言うので、どこまで本気なのかよくわからず、俺はいつもくすぐったい気持ちになる。"

[[dialogue]]
speaker = "ジュエリー"
# 「それに、いざという時の為に力があるに越したことはない。私は『考える』のは得意だが、『戦う』ことは決して得意分野ではないからね」
line = "「それに、いざという時の為に力があるに越したことはない。私は『考える』のは得意だが、『戦う』ことは決して得意分野ではないからね」"

[[dialogue]]
speaker = "ジュエリー"
# 「そういうわけで助手、どうだろうか？　協力してくれるかい？」
line = "「そういうわけで助手、どうだろうか？　協力してくれるかい？」"

[[dialogue]]
speaker = "unk"
# もちろん。試してみようか
line = "もちろん。試してみようか"

[[dialogue]]
speaker = "ジュエリー"
# 「決まりだね。それじゃあ、お願いするよ」
line = "「決まりだね。それじゃあ、お願いするよ」"

[[dialogue]]
speaker = "unk"
# 俺は彼女の額の辺りに手をかざす。
line = "俺は彼女の額の辺りに手をかざす。"

[[dialogue]]
speaker = "unk"
# すると、ジュエリーの奥に灯る星のような輝きが見えた。
line = "すると、ジュエリーの奥に灯る星のような輝きが見えた。"

[[dialogue]]
speaker = "unk"
# （この感じ……）
line = "（この感じ……）"

[[dialogue]]
speaker = "unk"
# （ジュエリーは１発で行けるのか！？）
line = "（ジュエリーは１発で行けるのか！？）"

[[dialogue]]
speaker = "unk"
# 驚くと同時に、いつもとちょっと違うような感覚も受けた。いずれにしても、試してみる価値はある。
line = "驚くと同時に、いつもとちょっと違うような感覚も受けた。いずれにしても、試してみる価値はある。"

[[dialogue]]
speaker = "ジュエリー"
# 「行けそうかい、助手？　私はいつでも準備できているよ」
line = "「行けそうかい、助手？　私はいつでも準備できているよ」"

[[dialogue]]
speaker = "unk"
# 俺は頷いて、アルケインコードを発動する。
line = "俺は頷いて、アルケインコードを発動する。"

[[dialogue]]
speaker = "unk"
# アルケインノヴァエクストリーム！
line = "アルケインノヴァエクストリーム！"

[[dialogue]]
speaker = "ジュエリー"
# 「ああ……キミの温かい心を感じる。これが――」
line = "「ああ……キミの温かい心を感じる。これが――」"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「キミと私の愛の力か……！」
line = "「キミと私の愛の力か……！」"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「ふふっ♪　やったぞ、助手。見てくれ、これが私の新しいフォームだ♪」
line = "「ふふっ♪　やったぞ、助手。見てくれ、これが私の新しいフォームだ♪」"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「どうだい？　似合うかい？」
line = "「どうだい？　似合うかい？」"

[[dialogue]]
speaker = "unk"
# 似合っていて、可愛いと思う
line = "似合っていて、可愛いと思う"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「ん♪　……ふふふっ」
line = "「ん♪　……ふふふっ」"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「キミが可愛いと言ってくれるなら、これ以上に嬉しいことはないよ。しばらくはこの衣装でずっと過ごすことにしよう♪」
line = "「キミが可愛いと言ってくれるなら、これ以上に嬉しいことはないよ。しばらくはこの衣装でずっと過ごすことにしよう♪」"

[[dialogue]]
speaker = "unk"
# と、その時だった。
line = "と、その時だった。"

[[dialogue]]
speaker = "ミネコ"
# 「失礼しま～す♪」
line = "「失礼しま～す♪」"

[[dialogue]]
speaker = "ミネコ"
# 「おっ、いたいた♪　お～い、ジュエリー！」
line = "「おっ、いたいた♪　お～い、ジュエリー！」"

[[dialogue]]
speaker = "unk"
# 見知らぬ女生徒が、大聖堂の中にやって来た。
line = "見知らぬ女生徒が、大聖堂の中にやって来た。"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「ミネコか。何か私に用かい？」
line = "「ミネコか。何か私に用かい？」"

[[dialogue]]
speaker = "ミネコ"
# 「うん♪　ジュエリーと新星学園の会長が、ここへ入るのを見たって聞いてね」
line = "「うん♪　ジュエリーと新星学園の会長が、ここへ入るのを見たって聞いてね」"

[[dialogue]]
speaker = "ミネコ"
# 「せっかくだし、私も会長に挨拶しときたいなと思ってさ♪」
line = "「せっかくだし、私も会長に挨拶しときたいなと思ってさ♪」"

[[dialogue]]
speaker = "unk"
# キミは……？
line = "キミは……？"

[[dialogue]]
speaker = "ミネコ"
# 「はっじめまして～♪　私、流星学園の１年生でジュエリーのクラスメイト、『ミネコ・フランボワーズ』って言いま～す♪」
line = "「はっじめまして～♪　私、流星学園の１年生でジュエリーのクラスメイト、『ミネコ・フランボワーズ』って言いま～す♪」"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「クラスメイトになったのは、<b>今日から</b>だけどね」
line = "「クラスメイトになったのは、<b>今日から</b>だけどね」"

[[dialogue]]
speaker = "unk"
# 転入生ってこと？
line = "転入生ってこと？"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「いいや、そうじゃない。今日登校したら、いつの間にか<b>クラスメイトだったこと</b>になっていたんだ」
line = "「いいや、そうじゃない。今日登校したら、いつの間にか<b>クラスメイトだったこと</b>になっていたんだ」"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「明解に換言するならば――」
line = "「明解に換言するならば――」"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「私以外の学園関係者の記憶や情報が、書き換えられていたんだよ」
line = "「私以外の学園関係者の記憶や情報が、書き換えられていたんだよ」"

[[dialogue]]
speaker = "ミネコ"
# 「いやだな～、ジュエリー、私たち前からズッ友だったじゃない♪」
line = "「いやだな～、ジュエリー、私たち前からズッ友だったじゃない♪」"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「ズッ友じゃなく、『因縁』の間違いだろう」
line = "「ズッ友じゃなく、『因縁』の間違いだろう」"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「キミの正体は……私と以前から高価な宝石や美術品を巡る事件で何度も衝突している相手――」
line = "「キミの正体は……私と以前から高価な宝石や美術品を巡る事件で何度も衝突している相手――」"

[[dialogue]]
speaker = "ジュエリー（究明）"
# 「『選星者』の１人、『大怪盗フランボウ』なのだから」
line = "「『選星者』の１人、『大怪盗フランボウ』なのだから」"

[[dialogue]]
speaker = "unk"
# 大怪盗フランボウっ！？
line = "大怪盗フランボウっ！？"

[[dialogue]]
speaker = "ミネコ"
# 「ふふっ♪　会長、以後どうかお見知りおきを♪」
line = "「ふふっ♪　会長、以後どうかお見知りおきを♪」"

[[dialogue]]
speaker = "unk"
# 彼女は紳士のお辞儀――『ボウ・アンド・スクレープ』をしながら、不敵な笑みを浮かべるのだった。
line = "彼女は紳士のお辞儀――『ボウ・アンド・スクレープ』をしながら、不敵な笑みを浮かべるのだった。"
