[[dialogue]]
speaker = "unk"
# 九浄家メイド隊の新人メイドである狛里を指導することになったヨミ。
line = "九浄家メイド隊の新人メイドである狛里を指導することになったヨミ。"

[[dialogue]]
speaker = "ヨミ"
# 「それでは本日から、九浄家でのメイドの仕事を教えていきますね」
line = "「それでは本日から、九浄家でのメイドの仕事を教えていきますね」"

[[dialogue]]
speaker = "狛里"
# 「ばうわふっ♪　ヨミ先輩、よろしくお願いするであります！」
line = "「ばうわふっ♪　ヨミ先輩、よろしくお願いするであります！」"

[[dialogue]]
speaker = "ヨミ"
# 「はい、一緒に頑張りましょう！」
line = "「はい、一緒に頑張りましょう！」"

[[dialogue]]
speaker = "ヨミ"
# 「ではまず、お屋敷の掃除から始めますね」
line = "「ではまず、お屋敷の掃除から始めますね」"

[[dialogue]]
speaker = "unk"
# 掃除する場所や手順をひと通り教えてから、しばらくして。
line = "掃除する場所や手順をひと通り教えてから、しばらくして。"

[[dialogue]]
speaker = "狛里"
# 「ヨミ先輩！　中庭のお掃除、終わったのです！」
line = "「ヨミ先輩！　中庭のお掃除、終わったのです！」"

[[dialogue]]
speaker = "ヨミ"
# 「えっ、もうですか！？」
line = "「えっ、もうですか！？」"

[[dialogue]]
speaker = "狛里"
# 「はいっ♪　それと、ついでに縁側もお掃除しておいたのです！」
line = "「はいっ♪　それと、ついでに縁側もお掃除しておいたのです！」"

[[dialogue]]
speaker = "ヨミ"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "ヨミ"
# 「あの……私がお願いしたのは中庭だけでしたよね？」
line = "「あの……私がお願いしたのは中庭だけでしたよね？」"

[[dialogue]]
speaker = "狛里"
# 「はいっ！　でも早く終わったので、たくさんお掃除した方がいいと思ったのです♪」
line = "「はいっ！　でも早く終わったので、たくさんお掃除した方がいいと思ったのです♪」"

[[dialogue]]
speaker = "ヨミ"
# 「そ、そうですか」
line = "「そ、そうですか」"

[[dialogue]]
speaker = "ヨミ"
# （やる気があるのはいいことだけど、報告なしに勝手に進めてしまうのはマズいような……）
line = "（やる気があるのはいいことだけど、報告なしに勝手に進めてしまうのはマズいような……）"

[[dialogue]]
speaker = "ヨミ"
# （それに、少し作業スピードが早過ぎる気も……）
line = "（それに、少し作業スピードが早過ぎる気も……）"

[[dialogue]]
speaker = "ヨミ"
# 「狛里さん、一応この辺りをもう少し掃いておきましょうか」
line = "「狛里さん、一応この辺りをもう少し掃いておきましょうか」"

[[dialogue]]
speaker = "狛里"
# 「はいっ！　了解であります！」
line = "「はいっ！　了解であります！」"

[[dialogue]]
speaker = "unk"
# 続いて、洗濯の指導に移る。
line = "続いて、洗濯の指導に移る。"

[[dialogue]]
speaker = "狛里"
# 「教えてもらった通りに、お洗濯をして、干し終わったのであります！」
line = "「教えてもらった通りに、お洗濯をして、干し終わったのであります！」"

[[dialogue]]
speaker = "ヨミ"
# 「て、手早いですね……！」
line = "「て、手早いですね……！」"

[[dialogue]]
speaker = "unk"
# ヨミは洗濯物の状態を確認する。
line = "ヨミは洗濯物の状態を確認する。"

[[dialogue]]
speaker = "ヨミ"
# （うん、干し方は問題ないみたい）
line = "（うん、干し方は問題ないみたい）"

[[dialogue]]
speaker = "ヨミ"
# 「いい感じですね。取り込む時間は覚えていますか？」
line = "「いい感じですね。取り込む時間は覚えていますか？」"

[[dialogue]]
speaker = "狛里"
# 「はいっ、大丈夫なのです！　気合いで覚えておくのです！」
line = "「はいっ、大丈夫なのです！　気合いで覚えておくのです！」"

[[dialogue]]
speaker = "ヨミ"
# 「き、気合いというよりは、ちゃんとメモを……」
line = "「き、気合いというよりは、ちゃんとメモを……」"

[[dialogue]]
speaker = "狛里"
# 「あっ、それもそうなのです！　えへへっ♪」
line = "「あっ、それもそうなのです！　えへへっ♪」"

[[dialogue]]
speaker = "ヨミ"
# （す、少し心配かも……）
line = "（す、少し心配かも……）"

[[dialogue]]
speaker = "unk"
# その日の夜。
line = "その日の夜。"

[[dialogue]]
speaker = "unk"
# 仕事を終えたヨミは、狛里と夕食を共にしていた。
line = "仕事を終えたヨミは、狛里と夕食を共にしていた。"

[[dialogue]]
speaker = "狛里"
# 「ばうわふっ♪　やっぱり人間界のご飯はどれも美味しいのです～♪」
line = "「ばうわふっ♪　やっぱり人間界のご飯はどれも美味しいのです～♪」"

[[dialogue]]
speaker = "ヨミ"
# 「ふふっ、狛里さんは本当に美味しそうに食べますね」
line = "「ふふっ、狛里さんは本当に美味しそうに食べますね」"

[[dialogue]]
speaker = "狛里"
# 「はいっ。狛里、昔から食べるのが大好きなのです♪　そのお陰で、同い年の子よりも大きくなれたのであります！」
line = "「はいっ。狛里、昔から食べるのが大好きなのです♪　そのお陰で、同い年の子よりも大きくなれたのであります！」"

[[dialogue]]
speaker = "ヨミ"
# 「確かに狛里さんは私より１つ年下なのに、その……スタイルもいいですよね」
line = "「確かに狛里さんは私より１つ年下なのに、その……スタイルもいいですよね」"

[[dialogue]]
speaker = "狛里"
# 「えへへっ♪　附属校に初めて登校した日も、クラスのみんなにびっくりされたのです！」
line = "「えへへっ♪　附属校に初めて登校した日も、クラスのみんなにびっくりされたのです！」"

[[dialogue]]
speaker = "ヨミ"
# （確かに附属校３年生だって聞いた時は、私も驚いたなぁ……ご当主様は９６センチって言ってたっけ。ごくりっ）
line = "（確かに附属校３年生だって聞いた時は、私も驚いたなぁ……ご当主様は９６センチって言ってたっけ。ごくりっ）"

[[dialogue]]
speaker = "ヨミ"
# 「狛里さんは、魔界ではどんな暮らしをしていたんですか？」
line = "「狛里さんは、魔界ではどんな暮らしをしていたんですか？」"

[[dialogue]]
speaker = "狛里"
# 「故郷は辺境の小さな村だったので、けっこう大変だったのです！」
line = "「故郷は辺境の小さな村だったので、けっこう大変だったのです！」"

[[dialogue]]
speaker = "狛里"
# 「畑仕事も、狩りも、見張りも、みんなで手分けしてやっていたのです！」
line = "「畑仕事も、狩りも、見張りも、みんなで手分けしてやっていたのです！」"

[[dialogue]]
speaker = "狛里"
# 「狛里は体が丈夫だったので、昔から色んなお仕事を任されることが多かったのであります！」
line = "「狛里は体が丈夫だったので、昔から色んなお仕事を任されることが多かったのであります！」"

[[dialogue]]
speaker = "ヨミ"
# 「そうだったんですね」
line = "「そうだったんですね」"

[[dialogue]]
speaker = "ヨミ"
# （だから、こんなに働き者なんだ。狛里さん、すごいなぁ……）
line = "（だから、こんなに働き者なんだ。狛里さん、すごいなぁ……）"

[[dialogue]]
speaker = "狛里"
# 「そうだ！　ヨミ先輩、聞いてもいいでありますか？」
line = "「そうだ！　ヨミ先輩、聞いてもいいでありますか？」"

[[dialogue]]
speaker = "ヨミ"
# 「はい、なんでしょう？」
line = "「はい、なんでしょう？」"

[[dialogue]]
speaker = "狛里"
# 「ご当主様から、ヨミ先輩も狛里と同じで、魔界でスカウトされて人間界に来たって聞いたのですけど――」
line = "「ご当主様から、ヨミ先輩も狛里と同じで、魔界でスカウトされて人間界に来たって聞いたのですけど――」"

[[dialogue]]
speaker = "狛里"
# 「どうしてメイドのお仕事をしているのかなって、気になったのであります！」
line = "「どうしてメイドのお仕事をしているのかなって、気になったのであります！」"

[[dialogue]]
speaker = "ヨミ"
# 「そう、ですね……」
line = "「そう、ですね……」"

[[dialogue]]
speaker = "ヨミ"
# 「私は、魔界にある『天ヶ崎神宮』という神社を守る一族の者なんです」
line = "「私は、魔界にある『天ヶ崎神宮』という神社を守る一族の者なんです」"

[[dialogue]]
speaker = "ヨミ"
# 「そして、天ヶ崎の一族は、３０００年前にリクリエから世界を守った『クルセイダース』の子孫でもあります」
line = "「そして、天ヶ崎の一族は、３０００年前にリクリエから世界を守った『クルセイダース』の子孫でもあります」"

[[dialogue]]
speaker = "ヨミ"
# 「私はその中でも、ご先祖様が使っていた『破邪の鈴』に選ばれたということで、九浄家にスカウトして頂いたんです」
line = "「私はその中でも、ご先祖様が使っていた『破邪の鈴』に選ばれたということで、九浄家にスカウトして頂いたんです」"

[[dialogue]]
speaker = "狛里"
# 「！　クルセイダース……知ってるのです！」
line = "「！　クルセイダース……知ってるのです！」"

[[dialogue]]
speaker = "狛里"
# 「大昔、魔界で暴れていた魔獣『白虎』を封印した英雄たちなのです！」
line = "「大昔、魔界で暴れていた魔獣『白虎』を封印した英雄たちなのです！」"

[[dialogue]]
speaker = "ヨミ"
# 「そうですね……白虎以外にも、クルセイダースの伝説は三界各地にたくさんあります」
line = "「そうですね……白虎以外にも、クルセイダースの伝説は三界各地にたくさんあります」"

[[dialogue]]
speaker = "ヨミ"
# 「私は、そんなクルセイダースのひとりが使っていた、伝説の武器を受け継いでいるんです」
line = "「私は、そんなクルセイダースのひとりが使っていた、伝説の武器を受け継いでいるんです」"

[[dialogue]]
speaker = "ヨミ"
# 「……ご当主様は最初、私を九浄家の『食客』として迎え入れたいと言ってくれました」
line = "「……ご当主様は最初、私を九浄家の『食客』として迎え入れたいと言ってくれました」"

[[dialogue]]
speaker = "ヨミ"
# 「でも、私はそれをお断りしたんです」
line = "「でも、私はそれをお断りしたんです」"

[[dialogue]]
speaker = "ヨミ"
# 「破邪の鈴に選ばれたとは言え、私はまだまだ未熟でしたし……」
line = "「破邪の鈴に選ばれたとは言え、私はまだまだ未熟でしたし……」"

[[dialogue]]
speaker = "ヨミ"
# 「何より、働きもしないままお世話になるのは嫌だったので」
line = "「何より、働きもしないままお世話になるのは嫌だったので」"

[[dialogue]]
speaker = "ヨミ"
# 「だから九浄家メイド隊の一員として働きながら、学園に通わせてもらうことにしたんです」
line = "「だから九浄家メイド隊の一員として働きながら、学園に通わせてもらうことにしたんです」"

[[dialogue]]
speaker = "狛里"
# 「そうだったのですね！　実は狛里もおんなじなのです♪」
line = "「そうだったのですね！　実は狛里もおんなじなのです♪」"

[[dialogue]]
speaker = "狛里"
# 「人間界でお世話になるなら、その分ちゃんと働きたいって思ったのです！」
line = "「人間界でお世話になるなら、その分ちゃんと働きたいって思ったのです！」"

[[dialogue]]
speaker = "ヨミ"
# 「そうだったんですね」
line = "「そうだったんですね」"

[[dialogue]]
speaker = "unk"
# ヨミは思わず笑みを浮かべる。
line = "ヨミは思わず笑みを浮かべる。"

[[dialogue]]
speaker = "ヨミ"
# 「じゃあ一緒にメイドの仕事、頑張りましょう♪」
line = "「じゃあ一緒にメイドの仕事、頑張りましょう♪」"

[[dialogue]]
speaker = "狛里"
# 「はいっ♪　明日からも、よろしくお願いするであります！」
line = "「はいっ♪　明日からも、よろしくお願いするであります！」"

[[dialogue]]
speaker = "unk"
# 数日後。
line = "数日後。"

[[dialogue]]
speaker = "unk"
# ヨミは狛里に、『任務管轄係』の仕事を教えていた。
line = "ヨミは狛里に、『任務管轄係』の仕事を教えていた。"

[[dialogue]]
speaker = "狛里"
# 「ヨミ先輩、頼まれた書類、ひと通り書き終わったのです！」
line = "「ヨミ先輩、頼まれた書類、ひと通り書き終わったのです！」"

[[dialogue]]
speaker = "ヨミ"
# 「ありがとうございます。確認しますね」
line = "「ありがとうございます。確認しますね」"

[[dialogue]]
speaker = "狛里"
# 「よろしくお願いするであります！　その間に狛里は、別のお仕事を進めておくのです！」
line = "「よろしくお願いするであります！　その間に狛里は、別のお仕事を進めておくのです！」"

[[dialogue]]
speaker = "unk"
# ちなみに『任務管轄係』とは、モンスターやアステラが出現した際、星騎士たちへの情報伝達や任務発注を行う部署である。
line = "ちなみに『任務管轄係』とは、モンスターやアステラが出現した際、星騎士たちへの情報伝達や任務発注を行う部署である。"

[[dialogue]]
speaker = "ヨミ"
# （う～ん……）
line = "（う～ん……）"

[[dialogue]]
speaker = "unk"
# 今日まで仕事を教えて来て、ヨミは狛里の『小さな問題点』に気づき始めていた。
line = "今日まで仕事を教えて来て、ヨミは狛里の『小さな問題点』に気づき始めていた。"

[[dialogue]]
speaker = "ヨミ"
# （仕事の覚えは早いし、作業もテキパキしてる）
line = "（仕事の覚えは早いし、作業もテキパキしてる）"

[[dialogue]]
speaker = "ヨミ"
# （でも、その反面……少し先を急ぎ過ぎている気がするなぁ）
line = "（でも、その反面……少し先を急ぎ過ぎている気がするなぁ）"

[[dialogue]]
speaker = "unk"
# それは洗濯物を取り込む時間を忘れてしまうことだったり……掃除の後に確認すると、掃き忘れた区画が残っていることだったり。
line = "それは洗濯物を取り込む時間を忘れてしまうことだったり……掃除の後に確認すると、掃き忘れた区画が残っていることだったり。"

[[dialogue]]
speaker = "unk"
# いずれも大きな失敗ではない。
line = "いずれも大きな失敗ではない。"

[[dialogue]]
speaker = "unk"
# しかし、そのどれもが『もう少し確認していれば防げたミス』だった。
line = "しかし、そのどれもが『もう少し確認していれば防げたミス』だった。"

[[dialogue]]
speaker = "ヨミ"
# （新人なんだから、ミスをするのは当たり前）
line = "（新人なんだから、ミスをするのは当たり前）"

[[dialogue]]
speaker = "ヨミ"
# （むしろ狛里さんはよく頑張っていると思う。でも……）
line = "（むしろ狛里さんはよく頑張っていると思う。でも……）"

[[dialogue]]
speaker = "unk"
# ヨミは書類へ目を落とす。
line = "ヨミは書類へ目を落とす。"

[[dialogue]]
speaker = "unk"
# そこにもまた、小さな書き間違いが１つ見つかった。
line = "そこにもまた、小さな書き間違いが１つ見つかった。"

[[dialogue]]
speaker = "ヨミ"
# （狛里さんの場合、ミスに気づかないまま『ただ多くの仕事をこなすこと』が目的化しちゃってるように見える）
line = "（狛里さんの場合、ミスに気づかないまま『ただ多くの仕事をこなすこと』が目的化しちゃってるように見える）"

[[dialogue]]
speaker = "ヨミ"
# （仕事は『こなした数』が多いほど偉いわけじゃない。ミスがないこと、終わらせることに責任を持つことも重要だ）
line = "（仕事は『こなした数』が多いほど偉いわけじゃない。ミスがないこと、終わらせることに責任を持つことも重要だ）"

[[dialogue]]
speaker = "ヨミ"
# （今の狛里さんは、もっと早く、もっと沢山って頑張っているけど……）
line = "（今の狛里さんは、もっと早く、もっと沢山って頑張っているけど……）"

[[dialogue]]
speaker = "ヨミ"
# （このままで、本当に大丈夫なのかな……？）
line = "（このままで、本当に大丈夫なのかな……？）"

[[dialogue]]
speaker = "unk"
# もちろん、その都度注意はしている。
line = "もちろん、その都度注意はしている。"

[[dialogue]]
speaker = "unk"
# だが、それだけでは根本的な解決になっていない気がした。
line = "だが、それだけでは根本的な解決になっていない気がした。"

[[dialogue]]
speaker = "unk"
# ヨミは書類を手にしたまま、少しだけ考え込むのだった。
line = "ヨミは書類を手にしたまま、少しだけ考え込むのだった。"
