[[dialogue]]
speaker = "せつな（覚醒）"
# 「にゃああああっ！！！　師匠、頑張ったのですからしみないほうの秘薬で治療して欲しいでござるっ！！」
line = "「にゃああああっ！！！　師匠、頑張ったのですからしみないほうの秘薬で治療して欲しいでござるっ！！」"

[[dialogue]]
speaker = "シズル"
# 「そっちは他のみんなに使っていますから。せつなはこれで我慢してください♪」
line = "「そっちは他のみんなに使っていますから。せつなはこれで我慢してください♪」"

[[dialogue]]
speaker = "ウズメイア"
# 「くぅ～っ、やっぱシズルさんの秘薬はサイコーでしょ！　怪我とか一瞬で直っちゃうし～♪」
line = "「くぅ～っ、やっぱシズルさんの秘薬はサイコーでしょ！　怪我とか一瞬で直っちゃうし～♪」"

[[dialogue]]
speaker = "ヨミ"
# 「すみません、しみないお薬をこっちで使ってしまって」
line = "「すみません、しみないお薬をこっちで使ってしまって」"

[[dialogue]]
speaker = "シズル"
# 「星騎士のみなさんはお客様ですから、どうぞ遠慮なさらず。せつなはこちらで我慢できますよね？」
line = "「星騎士のみなさんはお客様ですから、どうぞ遠慮なさらず。せつなはこちらで我慢できますよね？」"

[[dialogue]]
speaker = "ちとせ"
# 「ごくごく……飲む方の薬もすっごく効くね～」
line = "「ごくごく……飲む方の薬もすっごく効くね～」"

[[dialogue]]
speaker = "さつき"
# 「さすがは師匠の秘薬です」
line = "「さすがは師匠の秘薬です」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「なっ……！　みんなは飲み薬を！　しかもあの様子、苦くない方でござる！」
line = "「なっ……！　みんなは飲み薬を！　しかもあの様子、苦くない方でござる！」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「師匠、わざとやっているでござる！　もしかしてせつなへのお仕置きでござるか！？」
line = "「師匠、わざとやっているでござる！　もしかしてせつなへのお仕置きでござるか！？」"

[[dialogue]]
speaker = "シズル"
# 「せつなの覚悟がなかなか決まらないせいで頑張る羽目になりましたからね♪　はい、背中の方にもぬ～りぬり、と♪」
line = "「せつなの覚悟がなかなか決まらないせいで頑張る羽目になりましたからね♪　はい、背中の方にもぬ～りぬり、と♪」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「みぎゃ～～～～っ！！！」
line = "「みぎゃ～～～～っ！！！」"

[[dialogue]]
speaker = "シズル"
# 「……ですが、見事な戦いでしたよ。新たな忍装束も使いこなせていたようですね」
line = "「……ですが、見事な戦いでしたよ。新たな忍装束も使いこなせていたようですね」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「あ、ありがとうございます。……ですが、この戦闘服はいったい何でござるか？」
line = "「あ、ありがとうございます。……ですが、この戦闘服はいったい何でござるか？」"

[[dialogue]]
speaker = "シズル"
# 「ヘレナさんから預かっていたものですよ」
line = "「ヘレナさんから預かっていたものですよ」"

[[dialogue]]
speaker = "シズル"
# 「せつなを一人前と認めた時、渡そうと決めていたのですが……危うく挫けそうになっていたので焦りました」
line = "「せつなを一人前と認めた時、渡そうと決めていたのですが……危うく挫けそうになっていたので焦りました」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「ううっ……そ、それは……面目次第もないでござる……」
line = "「ううっ……そ、それは……面目次第もないでござる……」"

[[dialogue]]
speaker = "シズル"
# 「まあまあ、最終的には心の奥底に抱いていた恐怖心に打ち勝ち、その装束の力も引き出すことができましたし」
line = "「まあまあ、最終的には心の奥底に抱いていた恐怖心に打ち勝ち、その装束の力も引き出すことができましたし」"

[[dialogue]]
speaker = "シズル"
# 「なのでギリギリ、合格ということにしましょう……おめでとう、せつな」
line = "「なのでギリギリ、合格ということにしましょう……おめでとう、せつな」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「ううっ、ししょおぉ～」
line = "「ううっ、ししょおぉ～」"

[[dialogue]]
speaker = "シズル"
# 「情けない声を出さないでください。本当に大丈夫かなって不安になっちゃうじゃありませんか」
line = "「情けない声を出さないでください。本当に大丈夫かなって不安になっちゃうじゃありませんか」"

[[dialogue]]
speaker = "シズル"
# 「これからも修練に励み、私が安心して隠居できるような立派な忍者になってくださいね」
line = "「これからも修練に励み、私が安心して隠居できるような立派な忍者になってくださいね」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "unk"
# 引退するつもりなんですか？
line = "引退するつもりなんですか？"

[[dialogue]]
speaker = "シズル"
# 「私も力の衰えを感じていますし、後は若い子に頑張ってもらおうかな、って」
line = "「私も力の衰えを感じていますし、後は若い子に頑張ってもらおうかな、って」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「そんなこと言わないで欲しいでござる！　師匠に比べたらせつなはまだまだヒヨッコでござるから！！」
line = "「そんなこと言わないで欲しいでござる！　師匠に比べたらせつなはまだまだヒヨッコでござるから！！」"

[[dialogue]]
speaker = "シズル"
# 「おや？　また元の甘えん坊せつなに逆戻りですか？」
line = "「おや？　また元の甘えん坊せつなに逆戻りですか？」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「うっ……いろいろ覚悟は決めたつもりでござるが……それとこれとは話が別でござる……」
line = "「うっ……いろいろ覚悟は決めたつもりでござるが……それとこれとは話が別でござる……」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「師匠が引退してしまうのは悲しいでござるし、師匠と共に肩を並べて戦うのがせつなの夢なのでござるから」
line = "「師匠が引退してしまうのは悲しいでござるし、師匠と共に肩を並べて戦うのがせつなの夢なのでござるから」"

[[dialogue]]
speaker = "シズル"
# 「やれやれ……仕方ありませんね。ではもう少し頑張ることにしましょう」
line = "「やれやれ……仕方ありませんね。ではもう少し頑張ることにしましょう」"

[[dialogue]]
speaker = "シズル"
# 「魔王さん、まだまだ未熟なせつなですが、これからもお傍に置いてあげてください」
line = "「魔王さん、まだまだ未熟なせつなですが、これからもお傍に置いてあげてください」"

[[dialogue]]
speaker = "unk"
# もちろんです
line = "もちろんです"

[[dialogue]]
speaker = "シズル"
# 「というわけで、せつなは引き続き星騎士として、学園で研鑽を積んできてください」
line = "「というわけで、せつなは引き続き星騎士として、学園で研鑽を積んできてください」"

[[dialogue]]
speaker = "さつき"
# 「里のことは私たちにまかせて」
line = "「里のことは私たちにまかせて」"

[[dialogue]]
speaker = "ちとせ"
# 「がんばれ、せつな！　あっちの方の進展も報告よろしくね～♪」
line = "「がんばれ、せつな！　あっちの方の進展も報告よろしくね～♪」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「にゃあああああっ！　何を言い出すでござるかっ！」
line = "「にゃあああああっ！　何を言い出すでござるかっ！」"

[[dialogue]]
speaker = "unk"
# あっちの方？
line = "あっちの方？"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「何でもないでござる！　主様は何も聞いていないでござるーーーっ！！！！」
line = "「何でもないでござる！　主様は何も聞いていないでござるーーーっ！！！！」"

[[dialogue]]
speaker = "シズル"
# 「ふふっ、まったくもう……」
line = "「ふふっ、まったくもう……」"

[[dialogue]]
speaker = "unk"
# そして、予定していた滞在期間も終わり──
line = "そして、予定していた滞在期間も終わり──"

[[dialogue]]
speaker = "ちとせ"
# 「せつな、もう帰っちゃうんだね～」
line = "「せつな、もう帰っちゃうんだね～」"

[[dialogue]]
speaker = "さつき"
# 「ちとせ、そんな寂しそうな声ださない。空間転移装置で前より行き来はしやすくなったんだから」
line = "「ちとせ、そんな寂しそうな声ださない。空間転移装置で前より行き来はしやすくなったんだから」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「そうでござるよ、里のピンチには真っ先に駆けつけるでござる！」
line = "「そうでござるよ、里のピンチには真っ先に駆けつけるでござる！」"

[[dialogue]]
speaker = "さつき"
# 「頼もしいけど、私たちも私たちで頑張って、せつなが安心して頑張れるような立派な忍者になるから」
line = "「頼もしいけど、私たちも私たちで頑張って、せつなが安心して頑張れるような立派な忍者になるから」"

[[dialogue]]
speaker = "ちとせ"
# 「そうそう、星騎士としての務め、しっかり果たしてきてね♪」
line = "「そうそう、星騎士としての務め、しっかり果たしてきてね♪」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「わかったでござる！」
line = "「わかったでござる！」"

[[dialogue]]
speaker = "ウズメイア"
# 「いろいろ大変だったけど、いい感じに終われそうな感じ？」
line = "「いろいろ大変だったけど、いい感じに終われそうな感じ？」"

[[dialogue]]
speaker = "ヨミ"
# 「ですね、一時はどうなることかと思いましたが……」
line = "「ですね、一時はどうなることかと思いましたが……」"

[[dialogue]]
speaker = "シズル"
# 「ヘレナさんにも感謝の言葉をお伝え下さい。そして、今後ともよろしくお願いします、と」
line = "「ヘレナさんにも感謝の言葉をお伝え下さい。そして、今後ともよろしくお願いします、と」"

[[dialogue]]
speaker = "ヨミ"
# 「承りました。ですが、空間転移装置で一緒に来て直接お話しする、という選択もありなのでは？」
line = "「承りました。ですが、空間転移装置で一緒に来て直接お話しする、という選択もありなのでは？」"

[[dialogue]]
speaker = "シズル"
# 「あっ、そうですね！　ついでに久しぶりの都会を楽しんでくるのも悪くないかもです♪」
line = "「あっ、そうですね！　ついでに久しぶりの都会を楽しんでくるのも悪くないかもです♪」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「師匠！？　お別れでしんみりしてた流れが台無しでござるよ！」
line = "「師匠！？　お別れでしんみりしてた流れが台無しでござるよ！」"

[[dialogue]]
speaker = "シズル"
# 「冗談ですよ。私が里から離れるわけにはいきませんから。でも、里のみんなもしっかりしてきましたし、ちょっとくらいなら……うずうず」
line = "「冗談ですよ。私が里から離れるわけにはいきませんから。でも、里のみんなもしっかりしてきましたし、ちょっとくらいなら……うずうず」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「……ちとせもさつきも師匠の見張り、しかとお願いしたでござるよ」
line = "「……ちとせもさつきも師匠の見張り、しかとお願いしたでござるよ」"

[[dialogue]]
speaker = "ちとせ"
# 「う、うん……」
line = "「う、うん……」"

[[dialogue]]
speaker = "さつき"
# 「保証はできないけど、やれるだけ頑張ってみるよ」
line = "「保証はできないけど、やれるだけ頑張ってみるよ」"

[[dialogue]]
speaker = "ヨミ"
# 「では、私たちはそろそろ……」
line = "「では、私たちはそろそろ……」"

[[dialogue]]
speaker = "ウズメイア"
# 「いろいろお世話になりました！　今度は里のみんなも遊びに来てね～！」
line = "「いろいろお世話になりました！　今度は里のみんなも遊びに来てね～！」"

[[dialogue]]
speaker = "シズル"
# 「必ず行きます。その際はよろしくお願いしますね」
line = "「必ず行きます。その際はよろしくお願いしますね」"

[[dialogue]]
speaker = "せつな（覚醒）"
# 「それでは師匠、みんな、しばしのおさらばにござる！」
line = "「それでは師匠、みんな、しばしのおさらばにござる！」"

[[dialogue]]
speaker = "unk"
# こうしてせつなの帰郷を兼ねた視察の旅は、笑顔で終わりを迎えたのだった。
line = "こうしてせつなの帰郷を兼ねた視察の旅は、笑顔で終わりを迎えたのだった。"
