[[dialogue]]
speaker = "unk"
# サランとネーゼマインが悪戯をした後に、顔を見合わせて笑っている、ちょうどその頃――
line = "サランとネーゼマインが悪戯をした後に、顔を見合わせて笑っている、ちょうどその頃――"

[[dialogue]]
speaker = "セナリィ"
# 「ふふ……うふふふ♪　計画は順調ですわ……♪」
line = "「ふふ……うふふふ♪　計画は順調ですわ……♪」"

[[dialogue]]
speaker = "セナリィ"
# （１個５００テルスのお菓子を、現在７００個売り上げて、３５万テルス。経費を差し引いても２０万テルスで、４人で山分けして１人頭５万テルスの稼ぎ）
line = "（１個５００テルスのお菓子を、現在７００個売り上げて、３５万テルス。経費を差し引いても２０万テルスで、４人で山分けして１人頭５万テルスの稼ぎ）"

[[dialogue]]
speaker = "セナリィ"
# （学生のお金稼ぎとしては、これでも十分過ぎる成果でしょう。会社としてはお祭り価格で、カップケーキを１個７５０テルスくらいで売ってもよかったのでしょうが……）
line = "（学生のお金稼ぎとしては、これでも十分過ぎる成果でしょう。会社としてはお祭り価格で、カップケーキを１個７５０テルスくらいで売ってもよかったのでしょうが……）"

[[dialogue]]
speaker = "セナリィ"
# （今回、実際の売り上げよりも優先したのは、人脈作り。サラン様やマリオン様、キャナンシー様といった方々の協力を得て、販売企画を成功させることが１番の目的）
line = "（今回、実際の売り上げよりも優先したのは、人脈作り。サラン様やマリオン様、キャナンシー様といった方々の協力を得て、販売企画を成功させることが１番の目的）"

[[dialogue]]
speaker = "セナリィ"
# （今回成功して、ハロウィンパーティーを盛り上げたという実績ができれば、次回以降、別の企画でも快く協力してもらえるようになりますわ）
line = "（今回成功して、ハロウィンパーティーを盛り上げたという実績ができれば、次回以降、別の企画でも快く協力してもらえるようになりますわ）"

[[dialogue]]
speaker = "セナリィ"
# （すなわち今後に繋がる、お金稼ぎのチャンスと手札が増える。そういう意味では今回の計画、既に成功していると言えますわ。ですが――）
line = "（すなわち今後に繋がる、お金稼ぎのチャンスと手札が増える。そういう意味では今回の計画、既に成功していると言えますわ。ですが――）"

[[dialogue]]
speaker = "セナリィ"
# （<ruby=わたくし>私</ruby>のモット―は『悪・即・善』。悪とは儲かるもの。お金が儲かることは幸福。そして、幸せなのは善きこと……）
line = "（<ruby>私<rt>わたくし</rt></ruby>のモット―は『悪・即・善』。悪とは儲かるもの。お金が儲かることは幸福。そして、幸せなのは善きこと……）"

[[dialogue]]
speaker = "セナリィ"
# （お金という幸せの為ならば、悪のリスクを厭わないのが、私、バンデッド・セナリィの流儀ですわ。故に――）
line = "（お金という幸せの為ならば、悪のリスクを厭わないのが、私、バンデッド・セナリィの流儀ですわ。故に――）"

[[dialogue]]
speaker = "セナリィ"
# （ここから更に、倍プッシュですわ！！）
line = "（ここから更に、倍プッシュですわ！！）"

[[dialogue]]
speaker = "ヒトリ"
# 「――せ、セナリィさん。こんばんは……」
line = "「――せ、セナリィさん。こんばんは……」"

[[dialogue]]
speaker = "セナリィ"
# 「こんばんはですわ、ヒトリ様♪」
line = "「こんばんはですわ、ヒトリ様♪」"

[[dialogue]]
speaker = "セナリィ"
# 「お待ちしておりましたわ。例の準備はできておりますかしら？」
line = "「お待ちしておりましたわ。例の準備はできておりますかしら？」"

[[dialogue]]
speaker = "ヒトリ"
# 「は、はい。正直、どうなるかわかりませんでしたが……お願いしたら、思っていたよりノリノリで応じてくれました」
line = "「は、はい。正直、どうなるかわかりませんでしたが……お願いしたら、思っていたよりノリノリで応じてくれました」"

[[dialogue]]
speaker = "セナリィ"
# 「あしなに♪　やはり、ヒトリ様にお願いして正解でしたわね。それで、そちらに連れていらっしゃるのが……」
line = "「あしなに♪　やはり、ヒトリ様にお願いして正解でしたわね。それで、そちらに連れていらっしゃるのが……」"

[[dialogue]]
speaker = "？？？"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ヒトリ"
# 「はい、そうです。こちらがハロウィンの――」
line = "「はい、そうです。こちらがハロウィンの――」"

[[dialogue]]
speaker = "unk"
# セナリィ、ただいま～……って、ヒトリ？
line = "セナリィ、ただいま～……って、ヒトリ？"

[[dialogue]]
speaker = "ヒトリ"
# 「ひあっ！？　か、会長さんっ！？」
line = "「ひあっ！？　か、会長さんっ！？」"

[[dialogue]]
speaker = "セナリィ"
# 「あら。驚いて後ろの棺桶の中に隠れてしまいましたわ。男の方が苦手というのは、本当でしたのね」
line = "「あら。驚いて後ろの棺桶の中に隠れてしまいましたわ。男の方が苦手というのは、本当でしたのね」"

[[dialogue]]
speaker = "ヒトリ"
# 「す、すみません……会長さん。いきなりで、ビックリしてしまって……」
line = "「す、すみません……会長さん。いきなりで、ビックリしてしまって……」"

[[dialogue]]
speaker = "ヒトリ"
# 「今、出ますね……」
line = "「今、出ますね……」"

[[dialogue]]
speaker = "ヒトリ"
# 「会長さん、こ、こんばんは……」
line = "「会長さん、こ、こんばんは……」"

[[dialogue]]
speaker = "unk"
# 彼女は新星学園１年生、<ruby=しらぬい>不知火</ruby>ヒトリ。外見は物々しいが、恥ずかしがり屋な女の子だ。
line = "彼女は新星学園１年生、<ruby>不知火<rt>しらぬい</rt></ruby>ヒトリ。外見は物々しいが、恥ずかしがり屋な女の子だ。"

[[dialogue]]
speaker = "unk"
# 『御多摩霊園』を運営する両親を持ち、物心ついた頃から霊を見ることや会話することができたらしい。いつも隣には、幽霊の友達『ゆーちゃん』を連れている。
line = "『御多摩霊園』を運営する両親を持ち、物心ついた頃から霊を見ることや会話することができたらしい。いつも隣には、幽霊の友達『ゆーちゃん』を連れている。"

[[dialogue]]
speaker = "ゆーちゃん"
# 「ゆー♪」
line = "「ゆー♪」"

[[dialogue]]
speaker = "unk"
# あれ？　今日は普通に見える……？
line = "あれ？　今日は普通に見える……？"

[[dialogue]]
speaker = "ヒトリ"
# 「あ、ゆーちゃんですか……？　今日はハロウィンなので、霊感がない人でも見られるようになるんですよ」
line = "「あ、ゆーちゃんですか……？　今日はハロウィンなので、霊感がない人でも見られるようになるんですよ」"

[[dialogue]]
speaker = "ヒトリ"
# 「おかげで、ゆーちゃん、みんなから可愛いって言ってもらえて、私もなんだか嬉しくて……♪」
line = "「おかげで、ゆーちゃん、みんなから可愛いって言ってもらえて、私もなんだか嬉しくて……♪」"

[[dialogue]]
speaker = "unk"
# ところで、そちらの仮装してる方は……？
line = "ところで、そちらの仮装してる方は……？"

[[dialogue]]
speaker = "セナリィ"
# 「ふふふ、今回のハロウィン計画の秘策中の秘策……最強の助っ人ですわ！」
line = "「ふふふ、今回のハロウィン計画の秘策中の秘策……最強の助っ人ですわ！」"

[[dialogue]]
speaker = "ヒトリ"
# 「紹介します……こちら、ハロウィンの本物の幽霊さんで――」
line = "「紹介します……こちら、ハロウィンの本物の幽霊さんで――」"

[[dialogue]]
speaker = "ヒトリ"
# 「かの有名な、カボチャ頭の『ジャック・オー・ランタン』さんです」
line = "「かの有名な、カボチャ頭の『ジャック・オー・ランタン』さんです」"

[[dialogue]]
speaker = "ジャック"
# 「ケラケラケラ♪」
line = "「ケラケラケラ♪」"

[[dialogue]]
speaker = "unk"
# えっ！？　本物！？
line = "えっ！？　本物！？"

[[dialogue]]
speaker = "セナリィ"
# 「そう、ハロウィンを盛り上げるならば、その道のプロフェッショナルに頼むのが１番！　そこでヒトリ様に依頼して、ジャック様を召喚してもらったのですわ」
line = "「そう、ハロウィンを盛り上げるならば、その道のプロフェッショナルに頼むのが１番！　そこでヒトリ様に依頼して、ジャック様を召喚してもらったのですわ」"

[[dialogue]]
speaker = "セナリィ"
# 「さあ、ジャック様、学園の皆様に本物のトリックオアトリートを見せてあげてくださいまし♪」
line = "「さあ、ジャック様、学園の皆様に本物のトリックオアトリートを見せてあげてくださいまし♪」"

[[dialogue]]
speaker = "サラン"
# 「あれ～？　戻ってきたら、なんかすごく賑やかだね～？　なにかあったのかな～？」
line = "「あれ～？　戻ってきたら、なんかすごく賑やかだね～？　なにかあったのかな～？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「確かに……はは～ん、さてはセナリィの仕業だな？」
line = "「確かに……はは～ん、さてはセナリィの仕業だな？」"

[[dialogue]]
speaker = "流星学園１年生"
# 「ねぇ、聞いた！？　５００テルスで売ってる、あの美味しいカップケーキを食べさせてあげると、ダンスしてくれるっていうジャック・オー・ランタンの話！」
line = "「ねぇ、聞いた！？　５００テルスで売ってる、あの美味しいカップケーキを食べさせてあげると、ダンスしてくれるっていうジャック・オー・ランタンの話！」"

[[dialogue]]
speaker = "流星学園附属校３年生"
# 「私、さっき２個目を買ってあげちゃいました♪　すっごくクオリティの高い仮装で、迫力あるんですよ～♪　でも、ダンスする姿がなんか可愛くって<emoji=heart04>」
line = "「私、さっき２個目を買ってあげちゃいました♪　すっごくクオリティの高い仮装で、迫力あるんですよ～♪　でも、ダンスする姿がなんか可愛くって<emoji=heart04>」"

[[dialogue]]
speaker = "新星学園２年生"
# 「わかる～♪　コワ可愛いんだよね～<emoji=heart04>　委員長なんて、本物みたいだって興奮して、目がハートマークになっちゃってたよ～」
line = "「わかる～♪　コワ可愛いんだよね～<emoji=heart04>　委員長なんて、本物みたいだって興奮して、目がハートマークになっちゃってたよ～」"

[[dialogue]]
speaker = "サラン"
# 「本物のジャック・オー・ランタンだって～！　サランも見た～い♪」
line = "「本物のジャック・オー・ランタンだって～！　サランも見た～い♪」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「あ～、やっぱり♪　セナリィと会長がお菓子をバンバン売りまくってるよ～。それと……」
line = "「あ～、やっぱり♪　セナリィと会長がお菓子をバンバン売りまくってるよ～。それと……」"

[[dialogue]]
speaker = "セナリィ"
# 「ほほほ♪　お買い上げ、ありがとうございますわ～♪　……あっ！　マイン、サラン様、帰って参りましたのね」
line = "「ほほほ♪　お買い上げ、ありがとうございますわ～♪　……あっ！　マイン、サラン様、帰って参りましたのね」"

[[dialogue]]
speaker = "ジャック"
# 「ケラケラケラ♪」
line = "「ケラケラケラ♪」"

[[dialogue]]
speaker = "サラン"
# 「わあぁ～♪　本当にジャックちゃんだ～♪　サラン、ジャックちゃん大好きなの～♪　可愛い～♪」
line = "「わあぁ～♪　本当にジャックちゃんだ～♪　サラン、ジャックちゃん大好きなの～♪　可愛い～♪」"

[[dialogue]]
speaker = "キャナンシー"
# 「きゃっふ～ん<emoji=heart04>　ジャック様、もう１つお菓子をあげちゃうわぁ～ん<emoji=heart04>　ダンスをもう１度見せてぇ～<emoji=heart04>」
line = "「きゃっふ～ん<emoji=heart04>　ジャック様、もう１つお菓子をあげちゃうわぁ～ん<emoji=heart04>　ダンスをもう１度見せてぇ～<emoji=heart04>」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「ぷっ……きゃはははっ♪　本当にハロウィン狂もいるし！　ていうか、このジャックさんって、セナリィの隠し玉？」
line = "「ぷっ……きゃはははっ♪　本当にハロウィン狂もいるし！　ていうか、このジャックさんって、セナリィの隠し玉？」"

[[dialogue]]
speaker = "セナリィ"
# 「ほほほ♪　その通りですわ！　実はかくかくしかじかで――あっ、は～い♪　いらっしゃいませ～♪　お１つですわね～？」
line = "「ほほほ♪　その通りですわ！　実はかくかくしかじかで――あっ、は～い♪　いらっしゃいませ～♪　お１つですわね～？」"

[[dialogue]]
speaker = "unk"
# （説明しつつも接客は止めないのすごいな）
line = "（説明しつつも接客は止めないのすごいな）"

[[dialogue]]
speaker = "ネーゼマイン"
# 「にひひひっ♪　セナリィってば、本物のジャック・オー・ランタン呼んじゃうとか、マジかぁ～！　頭イカれてるでしょ～！」
line = "「にひひひっ♪　セナリィってば、本物のジャック・オー・ランタン呼んじゃうとか、マジかぁ～！　頭イカれてるでしょ～！」"

[[dialogue]]
speaker = "セナリィ"
# 「ふふふ、せっかく学園に、幽霊と話せる方がいるんですもの♪　来てもらえれば盛り上がること間違いなしでしょう？」
line = "「ふふふ、せっかく学園に、幽霊と話せる方がいるんですもの♪　来てもらえれば盛り上がること間違いなしでしょう？」"

[[dialogue]]
speaker = "サラン"
# 「わ～♪　ジャックちゃん、すご～い！　ダンス上手～♪」
line = "「わ～♪　ジャックちゃん、すご～い！　ダンス上手～♪」"

[[dialogue]]
speaker = "セナリィ"
# 「お菓子も売り上げが倍に伸びて、計１４００個を越えたところ！　ほほっ♪　ほほほっ♪　もはや笑いが止まりませんわ～♪」
line = "「お菓子も売り上げが倍に伸びて、計１４００個を越えたところ！　ほほっ♪　ほほほっ♪　もはや笑いが止まりませんわ～♪」"

[[dialogue]]
speaker = "サラン"
# 「ぱちぱちぱちぱち～♪　ダンスの次は一体何するの～？　わ～♪　面白そ～♪」
line = "「ぱちぱちぱちぱち～♪　ダンスの次は一体何するの～？　わ～♪　面白そ～♪」"

[[dialogue]]
speaker = "セナリィ"
# 「さすがに少し用意し過ぎたかとも思いましたけれど、この勢いなら在庫２０００個完売して、１００万テルスの売り上げも不可能では――」
line = "「さすがに少し用意し過ぎたかとも思いましたけれど、この勢いなら在庫２０００個完売して、１００万テルスの売り上げも不可能では――」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「にひひ♪　セナリィ。大金を想像して、ニヤついているところ悪いんだけどさ～」
line = "「にひひ♪　セナリィ。大金を想像して、ニヤついているところ悪いんだけどさ～」"

[[dialogue]]
speaker = "サラン"
# 「おぉ～♪　ジャックちゃん、強～い！」
line = "「おぉ～♪　ジャックちゃん、強～い！」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「後ろ、止めなくて大丈夫？」
line = "「後ろ、止めなくて大丈夫？」"

[[dialogue]]
speaker = "セナリィ"
# 「は？」
line = "「は？」"

[[dialogue]]
speaker = "キャナンシー"
# 「きゃっふ～ん！　負けちゃったわぁ～ん<emoji=heart04>」
line = "「きゃっふ～ん！　負けちゃったわぁ～ん<emoji=heart04>」"

[[dialogue]]
speaker = "unk"
# セナリィが後ろを見やると、そこにはカボチャ頭になって倒れるハロウィン狂の姿。
line = "セナリィが後ろを見やると、そこにはカボチャ頭になって倒れるハロウィン狂の姿。"

[[dialogue]]
speaker = "キャナンシー"
# 「推しに負けて、最高にハッピーハロウィンよぉ～ん……<emoji=heart04>　……ガクリ」
line = "「推しに負けて、最高にハッピーハロウィンよぉ～ん……<emoji=heart04>　……ガクリ」"

[[dialogue]]
speaker = "セナリィ"
# 「ホワイ！？　委員長様！？　というか、カボチャ頭の死屍累々がそこら中に転がってますわ！？　ちょっと目を離した隙に、一体どういう状況ですのっ！？」
line = "「ホワイ！？　委員長様！？　というか、カボチャ頭の死屍累々がそこら中に転がってますわ！？　ちょっと目を離した隙に、一体どういう状況ですのっ！？」"

[[dialogue]]
speaker = "サラン"
# 「う～んとね～、なんかジャックちゃんがダンスの次にバトルを始めて、お菓子をあげた星騎士の子達を戦闘服に変身させて、戦い始めたんだ～♪」
line = "「う～んとね～、なんかジャックちゃんがダンスの次にバトルを始めて、お菓子をあげた星騎士の子達を戦闘服に変身させて、戦い始めたんだ～♪」"

[[dialogue]]
speaker = "サラン"
# 「今のところジャックちゃんが全部勝ってて～、負けた子はカボチャ頭になって、脱げなくなっちゃうの～♪」
line = "「今のところジャックちゃんが全部勝ってて～、負けた子はカボチャ頭になって、脱げなくなっちゃうの～♪」"

[[dialogue]]
speaker = "セナリィ"
# 「脱げないんですの、あれ！？」
line = "「脱げないんですの、あれ！？」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「にひひひっ♪　これはセナリィ、やっちゃったかもだね～♪」
line = "「にひひひっ♪　これはセナリィ、やっちゃったかもだね～♪」"

[[dialogue]]
speaker = "セナリィ"
# 「ま、マイン？　やっちゃったって……」
line = "「ま、マイン？　やっちゃったって……」"

[[dialogue]]
speaker = "ネーゼマイン"
# 「これ、ジャックさん暴走してるパターンじゃない？」
line = "「これ、ジャックさん暴走してるパターンじゃない？」"

[[dialogue]]
speaker = "セナリィ"
# 「な……なんですってぇぇぇ～～～っ！！？」
line = "「な……なんですってぇぇぇ～～～っ！！？」"

[[dialogue]]
speaker = "ジャック"
# 「ケラケラケラ♪」
line = "「ケラケラケラ♪」"

[[dialogue]]
speaker = "unk"
# 慌てるセナリィを見て楽しむかのように、ハロウィンの幽霊は嘲笑うのだった。
line = "慌てるセナリィを見て楽しむかのように、ハロウィンの幽霊は嘲笑うのだった。"
