[[dialogue]]
speaker = "unk"
# ある朝、俺はジュエリーから急ぎの話があると、大聖堂に呼び出されていた。
line = "ある朝、俺はジュエリーから急ぎの話があると、大聖堂に呼び出されていた。"

[[dialogue]]
speaker = "ジュエリー"
# 「やあ、助手。来てもらって早々だが、本題に入ろう」
line = "「やあ、助手。来てもらって早々だが、本題に入ろう」"

[[dialogue]]
speaker = "ジュエリー"
# 「また警察から、探偵として協力の依頼がきた。ただし今回は……」
line = "「また警察から、探偵として協力の依頼がきた。ただし今回は……」"

[[dialogue]]
speaker = "ジュエリー"
# 「大怪盗フランボウによる事件だ」
line = "「大怪盗フランボウによる事件だ」"

[[dialogue]]
speaker = "unk"
# えっ！？
line = "えっ！？"

[[dialogue]]
speaker = "ジュエリー"
# 「ミネコ――フランボウが、流星市国の警察に予告状を出してきたんだ。その内容は……」
line = "「ミネコ――フランボウが、流星市国の警察に予告状を出してきたんだ。その内容は……」"

[[dialogue]]
speaker = "ジュエリー"
# 「今夜の０時ちょうど、この大聖堂にある『お宝』を頂戴しに参ります――だそうだ」
line = "「今夜の０時ちょうど、この大聖堂にある『お宝』を頂戴しに参ります――だそうだ」"

[[dialogue]]
speaker = "unk"
# それって……
line = "それって……"

[[dialogue]]
speaker = "unk"
# 考えられるものは１つしかない。俺は大聖堂の奥に視線を向ける。
line = "考えられるものは１つしかない。俺は大聖堂の奥に視線を向ける。"

[[dialogue]]
speaker = "ジュエリー"
# 「ああ、間違いない」
line = "「ああ、間違いない」"

[[dialogue]]
speaker = "ジュエリー"
# 「流星市国の国宝である――『太陽の壁画』」
line = "「流星市国の国宝である――『太陽の壁画』」"

[[dialogue]]
speaker = "ジュエリー"
# 「人間・天使・魔族が協力して魔王を倒す場面が描かれた、人間界で最も有名な絵画だ」
line = "「人間・天使・魔族が協力して魔王を倒す場面が描かれた、人間界で最も有名な絵画だ」"

[[dialogue]]
speaker = "ジュエリー"
# 「正直、ミネコが学園にやって来た時点で、これを狙っている可能性は考えなかったわけじゃない」
line = "「正直、ミネコが学園にやって来た時点で、これを狙っている可能性は考えなかったわけじゃない」"

[[dialogue]]
speaker = "ジュエリー"
# 「だが、ここは三界で最も卓越した星術使いが集まる場所――星騎士の学園だ。あの『ルパン・ザ・ピンキー』も、これまで手を出しては来なかった」
line = "「だが、ここは三界で最も卓越した星術使いが集まる場所――星騎士の学園だ。あの『ルパン・ザ・ピンキー』も、これまで手を出しては来なかった」"

[[dialogue]]
speaker = "ジュエリー"
# 「リスクと実利を天秤にかければ、実行の可能性は低いと踏んでいたんだ。だけど……」
line = "「リスクと実利を天秤にかければ、実行の可能性は低いと踏んでいたんだ。だけど……」"

[[dialogue]]
speaker = "unk"
# ミネコはクソゲーが好きだから
line = "ミネコはクソゲーが好きだから"

[[dialogue]]
speaker = "ジュエリー"
# 「ああ。攻略が難しい状況であればある程、彼女は燃えるタチなんだろう」
line = "「ああ。攻略が難しい状況であればある程、彼女は燃えるタチなんだろう」"

[[dialogue]]
speaker = "ジュエリー"
# 「彼女の父親――<ruby=こんだい>今代</ruby>の怪盗ルパンを超える為にも、ね」
line = "「彼女の父親――<ruby>今代<rt>こんだい</rt></ruby>の怪盗ルパンを超える為にも、ね」"

[[dialogue]]
speaker = "unk"
# そうして迎えた夜。
line = "そうして迎えた夜。"

[[dialogue]]
speaker = "ヴィーナス"
# 「――まさか、あの大怪盗フランボウが、太陽の壁画を盗みに来るなんてね！」
line = "「――まさか、あの大怪盗フランボウが、太陽の壁画を盗みに来るなんてね！」"

[[dialogue]]
speaker = "unk"
# ヴィーナス、来てくれてありがとう
line = "ヴィーナス、来てくれてありがとう"

[[dialogue]]
speaker = "ヴィーナス"
# 「これくらい、お茶の子ザーサイよ！　大聖堂の中は私が守るから、安心して！　クロト、ジュエリー！」
line = "「これくらい、お茶の子ザーサイよ！　大聖堂の中は私が守るから、安心して！　クロト、ジュエリー！」"

[[dialogue]]
speaker = "ジュエリー"
# 「ああ。ヴィーナスさんが力を貸してくれるなら、とても心強い。頼りにさせてもらおう」
line = "「ああ。ヴィーナスさんが力を貸してくれるなら、とても心強い。頼りにさせてもらおう」"

[[dialogue]]
speaker = "ヴィーナス"
# 「任せて！　目の前に現れたら、スーパーフィクサービームで木っ端ミジンコにしてあげるわ！」
line = "「任せて！　目の前に現れたら、スーパーフィクサービームで木っ端ミジンコにしてあげるわ！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「じゃあ２人共、行って来るわね！」
line = "「じゃあ２人共、行って来るわね！」"

[[dialogue]]
speaker = "unk"
# ヴィーナスは張り切りながら、大聖堂の方へ向かって行く。
line = "ヴィーナスは張り切りながら、大聖堂の方へ向かって行く。"

[[dialogue]]
speaker = "unk"
# ジュエリーは懐中時計を開いて、時刻を確認しながら……
line = "ジュエリーは懐中時計を開いて、時刻を確認しながら……"

[[dialogue]]
speaker = "ジュエリー"
# 「さて、助手。間もなく、フランボウの予告した午前０時になる」
line = "「さて、助手。間もなく、フランボウの予告した午前０時になる」"

[[dialogue]]
speaker = "ジュエリー"
# 「怪盗との対決に挑む前に、状況の最終確認をしておこうか」
line = "「怪盗との対決に挑む前に、状況の最終確認をしておこうか」"

[[dialogue]]
speaker = "ジュエリー"
# 「――まず、太陽の壁画には元々、古来より強力な防護星術が付与されている」
line = "「――まず、太陽の壁画には元々、古来より強力な防護星術が付与されている」"

[[dialogue]]
speaker = "ジュエリー"
# 「それによって、飾られているあの場所から動かすのは、基本的に困難だ。にも関わらず、フランボウは予告をしてきた」
line = "「それによって、飾られているあの場所から動かすのは、基本的に困難だ。にも関わらず、フランボウは予告をしてきた」"

[[dialogue]]
speaker = "ジュエリー"
# 「ということは、彼女はその防護星術を解く為に、時間をかけて準備していたのだろう」
line = "「ということは、彼女はその防護星術を解く為に、時間をかけて準備していたのだろう」"

[[dialogue]]
speaker = "ジュエリー"
# 「私の推測では、おそらくもう情報は解析し終わっていて、いつでも防護星術を改竄して無効化できるようになっているはずだ」
line = "「私の推測では、おそらくもう情報は解析し終わっていて、いつでも防護星術を改竄して無効化できるようになっているはずだ」"

[[dialogue]]
speaker = "ジュエリー"
# 「それを踏まえた上で、大聖堂の出入り口は警察の手で完全封鎖、中はヴィーナスさんと警察官の人たちで、壁画の守りを固めてもらっている」
line = "「それを踏まえた上で、大聖堂の出入り口は警察の手で完全封鎖、中はヴィーナスさんと警察官の人たちで、壁画の守りを固めてもらっている」"

[[dialogue]]
speaker = "ジュエリー"
# 「更には、大聖堂の周りも、助手の呼びかけで集まってもらったプリマステラの人たちで警戒に当たっている」
line = "「更には、大聖堂の周りも、助手の呼びかけで集まってもらったプリマステラの人たちで警戒に当たっている」"

[[dialogue]]
speaker = "ジュエリー"
# 「そして重要なポイントとして、フランボウの能力については、今回協力してくれている全員に伝えてある」
line = "「そして重要なポイントとして、フランボウの能力については、今回協力してくれている全員に伝えてある」"

[[dialogue]]
speaker = "ジュエリー"
# 「普通ならば、まず忍び込めない」
line = "「普通ならば、まず忍び込めない」"

[[dialogue]]
speaker = "ジュエリー"
# 「では、怪盗はどうするか。私なら――」
line = "「では、怪盗はどうするか。私なら――」"

[[dialogue]]
speaker = "ジュエリー"
# 「１番厄介な探偵を叩いて倒した後に、その姿に変装して大聖堂に入る」
line = "「１番厄介な探偵を叩いて倒した後に、その姿に変装して大聖堂に入る」"

[[dialogue]]
speaker = "ミネコ"
# 「ご名答。さすがは『名探偵』」
line = "「ご名答。さすがは『名探偵』」"

[[dialogue]]
speaker = "unk"
# 背後から声がした。
line = "背後から声がした。"

[[dialogue]]
speaker = "unk"
# 振り向くとそこには、１人の『人影』が立っていた。
line = "振り向くとそこには、１人の『人影』が立っていた。"

[[dialogue]]
speaker = "ミネコ"
# 「――大怪盗フランボウ、予告通りただいま参上♪」
line = "「――大怪盗フランボウ、予告通りただいま参上♪」"

[[dialogue]]
speaker = "unk"
# ミネコ……なのか？
line = "ミネコ……なのか？"

[[dialogue]]
speaker = "ミネコ"
# 「うん、そうだよ、会長。これが私の怪盗衣装♪」
line = "「うん、そうだよ、会長。これが私の怪盗衣装♪」"

[[dialogue]]
speaker = "ミネコ"
# 「どうどう？　似合ってるかな？　といっても、上手く見えないと思うけど。ふふふっ♪」
line = "「どうどう？　似合ってるかな？　といっても、上手く見えないと思うけど。ふふふっ♪」"

[[dialogue]]
speaker = "unk"
# 彼女の言う通り、俺にはそこに立っているのがミネコなのか、上手く認識できていなかった。
line = "彼女の言う通り、俺にはそこに立っているのがミネコなのか、上手く認識できていなかった。"

[[dialogue]]
speaker = "unk"
# 背が高いのか低いのか、性別が女なのか男なのかすらも、よく分からない。誰かの人影がそこに立っているということだけはわかる、というような状態。
line = "背が高いのか低いのか、性別が女なのか男なのかすらも、よく分からない。誰かの人影がそこに立っているということだけはわかる、というような状態。"

[[dialogue]]
speaker = "unk"
# 彼女の声も同じだ。男性か女性かわからないボイスチェンジャーを通したような声で、俺には聞こえていた。
line = "彼女の声も同じだ。男性か女性かわからないボイスチェンジャーを通したような声で、俺には聞こえていた。"

[[dialogue]]
speaker = "unk"
# これが五感の『情報改竄』……！
line = "これが五感の『情報改竄』……！"

[[dialogue]]
speaker = "ミネコ"
# 「いわゆる、『認識阻害』ってやつだね。こうすることで、私は今まで正体を悟られることなく、怪盗を続けてこれたってわけ」
line = "「いわゆる、『認識阻害』ってやつだね。こうすることで、私は今まで正体を悟られることなく、怪盗を続けてこれたってわけ」"

[[dialogue]]
speaker = "ミネコ"
# 「さて、フランボウとしての対面も済んだところで、攻略を始めようか」
line = "「さて、フランボウとしての対面も済んだところで、攻略を始めようか」"

[[dialogue]]
speaker = "ミネコ"
# 「ゲーム攻略ってのは、時間が短い方がスタイリッシュでカッコいい。キミもそう思うでしょう？　名探偵」
line = "「ゲーム攻略ってのは、時間が短い方がスタイリッシュでカッコいい。キミもそう思うでしょう？　名探偵」"

[[dialogue]]
speaker = "ジュエリー"
# 「あいにく私は、<ruby=ＲＴＡ>リアルタイムアタック</ruby>は嗜まないんだ。だから――」
line = "「あいにく私は、<ruby>リアルタイムアタック<rt>ＲＴＡ</rt></ruby>は嗜まないんだ。だから――」"

[[dialogue]]
speaker = "ジュエリー"
# 「今日こそじっくりとその能力、批評させてもらうよ、大怪盗」
line = "「今日こそじっくりとその能力、批評させてもらうよ、大怪盗」"

[[dialogue]]
speaker = "unk"
# 両者は構える。
line = "両者は構える。"

[[dialogue]]
speaker = "unk"
# ２人の選星者、『名探偵』と『大怪盗』の対決が開始されるのだった――
line = "２人の選星者、『名探偵』と『大怪盗』の対決が開始されるのだった――"
