[[dialogue]]
speaker = "unk"
# その日の放課後。
line = "その日の放課後。"

[[dialogue]]
speaker = "狛里"
# 「ヨミ先輩、お呼びなのですか？」
line = "「ヨミ先輩、お呼びなのですか？」"

[[dialogue]]
speaker = "ヨミ"
# 「はい。狛里さん……」
line = "「はい。狛里さん……」"

[[dialogue]]
speaker = "ヨミ"
# 「――いえ、<b>狛里</b>」
line = "「――いえ、<b>狛里</b>」"

[[dialogue]]
speaker = "ヨミ"
# 「狛里の先輩として、お話があります！」
line = "「狛里の先輩として、お話があります！」"

[[dialogue]]
speaker = "狛里"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "unk"
# 狛里は耳をピンと立て、少し驚いた様子で姿勢を正す。
line = "狛里は耳をピンと立て、少し驚いた様子で姿勢を正す。"

[[dialogue]]
speaker = "ヨミ"
# 「先日の戦闘の時……口では大丈夫と言っていましたけど、無茶をしていましたよね？」
line = "「先日の戦闘の時……口では大丈夫と言っていましたけど、無茶をしていましたよね？」"

[[dialogue]]
speaker = "ヨミ"
# 「予想外の怪我をしたのではなく──怪我をすることを承知で、乱暴に動き回っているように見えました」
line = "「予想外の怪我をしたのではなく──怪我をすることを承知で、乱暴に動き回っているように見えました」"

[[dialogue]]
speaker = "狛里"
# 「そ、それは……はいなのです」
line = "「そ、それは……はいなのです」"

[[dialogue]]
speaker = "ヨミ"
# 「あの戦い方は、良くないと思います」
line = "「あの戦い方は、良くないと思います」"

[[dialogue]]
speaker = "ヨミ"
# 「戦い方だけじゃありません、仕事でもそうです。早く終わらせようとして、小さなミスをしてしまう」
line = "「戦い方だけじゃありません、仕事でもそうです。早く終わらせようとして、小さなミスをしてしまう」"

[[dialogue]]
speaker = "ヨミ"
# 「狛里は、全部自分１人でやろうとしているように見えます」
line = "「狛里は、全部自分１人でやろうとしているように見えます」"

[[dialogue]]
speaker = "ヨミ"
# 「狛里は頑張っていると思います。でも……頑張り方を間違っています！」
line = "「狛里は頑張っていると思います。でも……頑張り方を間違っています！」"

[[dialogue]]
speaker = "ヨミ"
# 「ずっと無理をしていたら、いつか大きなミスをするかもしれない――」
line = "「ずっと無理をしていたら、いつか大きなミスをするかもしれない――」"

[[dialogue]]
speaker = "ヨミ"
# 「それは先輩として、狛里の為にも見過ごせません！！」
line = "「それは先輩として、狛里の為にも見過ごせません！！」"

[[dialogue]]
speaker = "狛里"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "狛里"
# 「ヨミ先輩、ごめんなさいなのです」
line = "「ヨミ先輩、ごめんなさいなのです」"

[[dialogue]]
speaker = "unk"
# 狛里は深々と頭を下げた。
line = "狛里は深々と頭を下げた。"

[[dialogue]]
speaker = "狛里"
# 「……ヨミ先輩の言っていることは、正しいのです」
line = "「……ヨミ先輩の言っていることは、正しいのです」"

[[dialogue]]
speaker = "狛里"
# 「辺境で『白虎』と戦っていた時も、討伐隊の人たちから似たようなことを言われたのです」
line = "「辺境で『白虎』と戦っていた時も、討伐隊の人たちから似たようなことを言われたのです」"

[[dialogue]]
speaker = "ヨミ"
# 「白虎……？」
line = "「白虎……？」"

[[dialogue]]
speaker = "狛里"
# 「はいなのです。ここに来る前、魔界にいた時のことなのですが――」
line = "「はいなのです。ここに来る前、魔界にいた時のことなのですが――」"

[[dialogue]]
speaker = "狛里"
# 「狛里の故郷の村で、今から１年くらい前に、ある異変が起きたのです」
line = "「狛里の故郷の村で、今から１年くらい前に、ある異変が起きたのです」"

[[dialogue]]
speaker = "狛里"
# 「村の近くにある大空洞には、魔獣『白虎』が大昔から封印されていたのです。でも、リクリエの影響で封印が弱くなって、目覚めてしまったのであります」
line = "「村の近くにある大空洞には、魔獣『白虎』が大昔から封印されていたのです。でも、リクリエの影響で封印が弱くなって、目覚めてしまったのであります」"

[[dialogue]]
speaker = "狛里"
# 「それで、大空洞から溢れ出る白虎の魔力で、魔物たちが眷族になって……突然、村を襲うようになったのです」
line = "「それで、大空洞から溢れ出る白虎の魔力で、魔物たちが眷族になって……突然、村を襲うようになったのです」"

[[dialogue]]
speaker = "狛里"
# 「でも、村で戦える星力持ちは、狛里しかいなかったのです」
line = "「でも、村で戦える星力持ちは、狛里しかいなかったのです」"

[[dialogue]]
speaker = "ヨミ"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "狛里"
# 「だから、狛里が『門番』になって、ひとりで村を守るしかなかったのです」
line = "「だから、狛里が『門番』になって、ひとりで村を守るしかなかったのです」"

[[dialogue]]
speaker = "狛里"
# 「誰かが助けを呼びに出たら、その人が白虎の眷族に襲われちゃうのです」
line = "「誰かが助けを呼びに出たら、その人が白虎の眷族に襲われちゃうのです」"

[[dialogue]]
speaker = "狛里"
# 「だから、村に立てこもるしかなかったのです」
line = "「だから、村に立てこもるしかなかったのです」"

[[dialogue]]
speaker = "狛里"
# 「でも、１ヵ月くらい頑張ってたら、隣村の人たちが異変に気づいてくれて――」
line = "「でも、１ヵ月くらい頑張ってたら、隣村の人たちが異変に気づいてくれて――」"

[[dialogue]]
speaker = "狛里"
# 「大きな街から星騎士の人たちが助けに来てくれたおかげで、狛里も村のみんなも生き残れたのです」
line = "「大きな街から星騎士の人たちが助けに来てくれたおかげで、狛里も村のみんなも生き残れたのです」"

[[dialogue]]
speaker = "ヨミ"
# 「１ヵ月間、１人でずっと村を……？」
line = "「１ヵ月間、１人でずっと村を……？」"

[[dialogue]]
speaker = "狛里"
# 「はいなのです。狛里が戦わなかったら、誰かが怪我をする……狛里が頑張らなかったら、村がなくなっちゃう」
line = "「はいなのです。狛里が戦わなかったら、誰かが怪我をする……狛里が頑張らなかったら、村がなくなっちゃう」"

[[dialogue]]
speaker = "狛里"
# 「だから狛里は、白虎の眷族と戦い続けるしかなかったのです」
line = "「だから狛里は、白虎の眷族と戦い続けるしかなかったのです」"

[[dialogue]]
speaker = "ヨミ"
# 「その後、白虎はどうなったんですか……？」
line = "「その後、白虎はどうなったんですか……？」"

[[dialogue]]
speaker = "狛里"
# 「魔界の星騎士による討伐部隊がきて、狛里も一緒に戦って、討伐できたのです」
line = "「魔界の星騎士による討伐部隊がきて、狛里も一緒に戦って、討伐できたのです」"

[[dialogue]]
speaker = "狛里"
# 「それで、たまたま狛里が白虎にトドメを刺したから、九浄家のスカウトさんの目に留まったみたいで……」
line = "「それで、たまたま狛里が白虎にトドメを刺したから、九浄家のスカウトさんの目に留まったみたいで……」"

[[dialogue]]
speaker = "ヨミ"
# 「そういえば、ご当主様が狛里は『英雄』だって……」
line = "「そういえば、ご当主様が狛里は『英雄』だって……」"

[[dialogue]]
speaker = "狛里"
# 「戦いが終わった時、討伐隊の人たちが狛里のことを『辺境の英雄』だーって言ってくれて……えへへ、ちょっと恥ずかしいのです」
line = "「戦いが終わった時、討伐隊の人たちが狛里のことを『辺境の英雄』だーって言ってくれて……えへへ、ちょっと恥ずかしいのです」"

[[dialogue]]
speaker = "狛里"
# 「でも、そんなことがあったから──」
line = "「でも、そんなことがあったから──」"

[[dialogue]]
speaker = "狛里"
# 「今でも……狛里がやらなきゃって、すぐ思っちゃうのです」
line = "「今でも……狛里がやらなきゃって、すぐ思っちゃうのです」"

[[dialogue]]
speaker = "狛里"
# 「頭では、よくないってわかっているのです……」
line = "「頭では、よくないってわかっているのです……」"

[[dialogue]]
speaker = "unk"
# 狛里は困ったように笑う。
line = "狛里は困ったように笑う。"

[[dialogue]]
speaker = "狛里"
# 「あの１ヵ月、ずっとひとりで村を守っていたから……今でも、胸の奥がきゅーってなるのです」
line = "「あの１ヵ月、ずっとひとりで村を守っていたから……今でも、胸の奥がきゅーってなるのです」"

[[dialogue]]
speaker = "狛里"
# 「狛里がやらなきゃって、不安な気持ちになっちゃうのです……」
line = "「狛里がやらなきゃって、不安な気持ちになっちゃうのです……」"

[[dialogue]]
speaker = "ヨミ"
# 「狛里……」
line = "「狛里……」"

[[dialogue]]
speaker = "unk"
# しょんぼりと肩を落とす狛里のことを、ヨミは思わず抱きしめた。
line = "しょんぼりと肩を落とす狛里のことを、ヨミは思わず抱きしめた。"

[[dialogue]]
speaker = "狛里"
# 「わふっ、ヨミ先輩……！？」
line = "「わふっ、ヨミ先輩……！？」"

[[dialogue]]
speaker = "ヨミ"
# 「狛里はすごく頑張ってます！　狛里はとっても偉いです！」
line = "「狛里はすごく頑張ってます！　狛里はとっても偉いです！」"

[[dialogue]]
speaker = "unk"
# ヨミにとってもリクリエやモンスターは恐ろしい存在だったが、それでも狛里や会長のように、自分の両肩に誰かの命を乗せて戦ったことはなかった。
line = "ヨミにとってもリクリエやモンスターは恐ろしい存在だったが、それでも狛里や会長のように、自分の両肩に誰かの命を乗せて戦ったことはなかった。"

[[dialogue]]
speaker = "unk"
# つい先日まで、会長のことはどこか遠い存在のように感じていた。尊敬や憧れはあっても、自分とは違う特別な存在であると、どこか壁を作っていた。
line = "つい先日まで、会長のことはどこか遠い存在のように感じていた。尊敬や憧れはあっても、自分とは違う特別な存在であると、どこか壁を作っていた。"

[[dialogue]]
speaker = "unk"
# だけど、会長は言っていた。不安はあると。自信なんて、最初からなかったと。
line = "だけど、会長は言っていた。不安はあると。自信なんて、最初からなかったと。"

[[dialogue]]
speaker = "ヨミ"
# （それでも、あの人は立ち上がった）
line = "（それでも、あの人は立ち上がった）"

[[dialogue]]
speaker = "ヨミ"
# （ヴィーナスお嬢様や、私たち。『魔王』という肩書きを信じてついてくる人たちのために、腹をくくったんだ）
line = "（ヴィーナスお嬢様や、私たち。『魔王』という肩書きを信じてついてくる人たちのために、腹をくくったんだ）"

[[dialogue]]
speaker = "unk"
# それは、狛里も同じ。
line = "それは、狛里も同じ。"

[[dialogue]]
speaker = "unk"
# 村を救う英雄。まだ若い狛里が、本当は背負う必要のない『英雄』という責任を、その小さな体に背負った。仲間のために覚悟を決めた。
line = "村を救う英雄。まだ若い狛里が、本当は背負う必要のない『英雄』という責任を、その小さな体に背負った。仲間のために覚悟を決めた。"

[[dialogue]]
speaker = "ヨミ"
# （こんな小さな子がやって見せたことを、『私にはできません』じゃ済まされません！）
line = "（こんな小さな子がやって見せたことを、『私にはできません』じゃ済まされません！）"

[[dialogue]]
speaker = "unk"
# だから今度は、自分が狛里を守る。狛里や会長とはやり方は違うかもしれない、力不足かもしれない、でもそんなことは関係ないんだ。
line = "だから今度は、自分が狛里を守る。狛里や会長とはやり方は違うかもしれない、力不足かもしれない、でもそんなことは関係ないんだ。"

[[dialogue]]
speaker = "ヨミ"
# （私が、狛里を守る。私たち九浄家メイド隊が、狛里を守るんだ！）
line = "（私が、狛里を守る。私たち九浄家メイド隊が、狛里を守るんだ！）"

[[dialogue]]
speaker = "ヨミ"
# （私で足りなければせつなさんが、それでも足りなければメイド長が、狛里を守る！　私ひとりは弱くても、九浄家メイド隊は最強なんですから！！）
line = "（私で足りなければせつなさんが、それでも足りなければメイド長が、狛里を守る！　私ひとりは弱くても、九浄家メイド隊は最強なんですから！！）"

[[dialogue]]
speaker = "ヨミ"
# （九浄家メイド隊心得その７！　『１人はみんなのために、みんなは１人のために』です！！）
line = "（九浄家メイド隊心得その７！　『１人はみんなのために、みんなは１人のために』です！！）"

[[dialogue]]
speaker = "unk"
# 狛里を抱きしめながら、ヨミは何度も狛里の頭を撫でる。
line = "狛里を抱きしめながら、ヨミは何度も狛里の頭を撫でる。"

[[dialogue]]
speaker = "ヨミ"
# 「狛里の覚悟は立派です！　でもここは、魔界にある小さな村ではありません！」
line = "「狛里の覚悟は立派です！　でもここは、魔界にある小さな村ではありません！」"

[[dialogue]]
speaker = "ヨミ"
# 「ここは流星市国であり、天下の九浄家です。狛里の味方はたくさんいます！」
line = "「ここは流星市国であり、天下の九浄家です。狛里の味方はたくさんいます！」"

[[dialogue]]
speaker = "ヨミ"
# 「狛里のことは、私たちが守ります……！」
line = "「狛里のことは、私たちが守ります……！」"

[[dialogue]]
speaker = "ヨミ"
# 「だから、狛里は新しい戦い方を覚えなさい！！　これは先輩命令なんですからね！！」
line = "「だから、狛里は新しい戦い方を覚えなさい！！　これは先輩命令なんですからね！！」"

[[dialogue]]
speaker = "狛里"
# 「ばうわふぅ、ヨミ先輩……」
line = "「ばうわふぅ、ヨミ先輩……」"

[[dialogue]]
speaker = "狛里"
# 「わかったのです……狛里、もっとヨミ先輩の指示を守れるように、やってみるのです」
line = "「わかったのです……狛里、もっとヨミ先輩の指示を守れるように、やってみるのです」"

[[dialogue]]
speaker = "ヨミ"
# 「はいっ。約束ですよ、狛里！」
line = "「はいっ。約束ですよ、狛里！」"

[[dialogue]]
speaker = "狛里"
# 「えへへ♪　初めてヨミ先輩に抱きしめてもらいましたが、とってもいい匂いがするのであります♪　安心できる匂いなのですっ」
line = "「えへへ♪　初めてヨミ先輩に抱きしめてもらいましたが、とってもいい匂いがするのであります♪　安心できる匂いなのですっ」"

[[dialogue]]
speaker = "unk"
# 決して侮られていたわけではないものの、今までの反応と違った狛里の反応に、ヨミはほっと息を撫で下ろした。
line = "決して侮られていたわけではないものの、今までの反応と違った狛里の反応に、ヨミはほっと息を撫で下ろした。"

[[dialogue]]
speaker = "unk"
# この信頼を裏切らないよう、これからも先輩として精進しよう……そんなことを改めて決意するのだった。
line = "この信頼を裏切らないよう、これからも先輩として精進しよう……そんなことを改めて決意するのだった。"

[[dialogue]]
speaker = "unk"
# と、そんな時。
line = "と、そんな時。"

[[dialogue]]
speaker = "狛里"
# 「！　モンスター出現のアラートであります！」
line = "「！　モンスター出現のアラートであります！」"

[[dialogue]]
speaker = "unk"
# 街には、先日戦ったライカンスウォームの群れが再び出現していた。
line = "街には、先日戦ったライカンスウォームの群れが再び出現していた。"

[[dialogue]]
speaker = "unk"
# ──しかし、その数は先日の比ではない。数千匹クラスの狼の群れが流星市国を取り囲む大事件となっていた。
line = "──しかし、その数は先日の比ではない。数千匹クラスの狼の群れが流星市国を取り囲む大事件となっていた。"

[[dialogue]]
speaker = "unk"
# ヨミたちだけではない、その日、流星市国内にいたすべてのプリマステラに出動要請がかかった。
line = "ヨミたちだけではない、その日、流星市国内にいたすべてのプリマステラに出動要請がかかった。"

[[dialogue]]
speaker = "ライカンスウォーム"
# 「ガルルルルル！！」
line = "「ガルルルルル！！」"

[[dialogue]]
speaker = "狛里"
# 「あの１匹だけ色が違うライカンスウォーム！　群れのボスかもしれないのです！」
line = "「あの１匹だけ色が違うライカンスウォーム！　群れのボスかもしれないのです！」"

[[dialogue]]
speaker = "モンスターたち"
# 「ガルオオォーーンッ！」
line = "「ガルオオォーーンッ！」"

[[dialogue]]
speaker = "ヨミ"
# 「色違いのライカンスウォームから分裂した！？」
line = "「色違いのライカンスウォームから分裂した！？」"

[[dialogue]]
speaker = "ヨミ"
# 「そうか。こんな大群がどこから現れたのかと思ったけど、こいつらは全部、ボスのコピーなんですね！」
line = "「そうか。こんな大群がどこから現れたのかと思ったけど、こいつらは全部、ボスのコピーなんですね！」"

[[dialogue]]
speaker = "狛里"
# 「それなら、あのボスを倒すであります！」
line = "「それなら、あのボスを倒すであります！」"

[[dialogue]]
speaker = "unk"
# 狛里は反射的に前へ出ようとする。
line = "狛里は反射的に前へ出ようとする。"

[[dialogue]]
speaker = "ヨミ"
# 「待ってください！！」
line = "「待ってください！！」"

[[dialogue]]
speaker = "狛里"
# 「ヨミ先輩っ！？」
line = "「ヨミ先輩っ！？」"

[[dialogue]]
speaker = "ヨミ"
# 「今日は無茶しちゃダメです！」
line = "「今日は無茶しちゃダメです！」"

[[dialogue]]
speaker = "狛里"
# 「でも……！」
line = "「でも……！」"

[[dialogue]]
speaker = "ヨミ"
# 「狛里！！」
line = "「狛里！！」"

[[dialogue]]
speaker = "unk"
# ヨミは真っ直ぐに彼女の目を見て言う。
line = "ヨミは真っ直ぐに彼女の目を見て言う。"

[[dialogue]]
speaker = "ヨミ"
# 「もっと、私たちを頼ってください」
line = "「もっと、私たちを頼ってください」"

[[dialogue]]
speaker = "狛里"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "ヨミ"
# 「さっきも話しましたが、学園には沢山の星騎士がいます。狛里１人じゃありません！」
line = "「さっきも話しましたが、学園には沢山の星騎士がいます。狛里１人じゃありません！」"

[[dialogue]]
speaker = "ヨミ"
# 「そして――私は、あなたの先輩です！」
line = "「そして――私は、あなたの先輩です！」"

[[dialogue]]
speaker = "ヨミ"
# 「だから、１人で無茶はしないで下さい」
line = "「だから、１人で無茶はしないで下さい」"

[[dialogue]]
speaker = "ヨミ"
# 「私も一緒に前線で戦います！！」
line = "「私も一緒に前線で戦います！！」"

[[dialogue]]
speaker = "狛里"
# 「……！！」
line = "「……！！」"

[[dialogue]]
speaker = "狛里"
# 「はいなのです！　よろしくお願いするであります！」
line = "「はいなのです！　よろしくお願いするであります！」"

[[dialogue]]
speaker = "狛里"
# 「狛里に力を貸してください、ヨミ先輩！！」
line = "「狛里に力を貸してください、ヨミ先輩！！」"

[[dialogue]]
speaker = "ヨミ"
# 「っ！　この感覚は……！！」
line = "「っ！　この感覚は……！！」"

[[dialogue]]
speaker = "unk"
# ヨミの胸の奥で何かが灯る。
line = "ヨミの胸の奥で何かが灯る。"

[[dialogue]]
speaker = "unk"
# その頃──
line = "その頃──"

[[dialogue]]
speaker = "unk"
# 校門前で、クロトたち星徒会メンバーも、ライカンスウォームと交戦していた。
line = "校門前で、クロトたち星徒会メンバーも、ライカンスウォームと交戦していた。"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「ノヴァゴッデスビーム！！」
line = "「ノヴァゴッデスビーム！！」"

[[dialogue]]
speaker = "ライカンスウォーム"
# 「ガルオォーーッ！？」
line = "「ガルオォーーッ！？」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「敵の数が多くて、いくら倒してもキリがないわ！」
line = "「敵の数が多くて、いくら倒してもキリがないわ！」"

[[dialogue]]
speaker = "ヴィーナス（覚醒）"
# 「って、クロト！？　どうかしたの！？」
line = "「って、クロト！？　どうかしたの！？」"

[[dialogue]]
speaker = "unk"
# ヨミの『心の輝き』を感じる
line = "ヨミの『心の輝き』を感じる"

[[dialogue]]
speaker = "unk"
# クロトは離れた場所に、瞬く星のような輝きを感じ取っていた。
line = "クロトは離れた場所に、瞬く星のような輝きを感じ取っていた。"

[[dialogue]]
speaker = "unk"
# 確信があった。だから――
line = "確信があった。だから――"

[[dialogue]]
speaker = "unk"
# アルケインノヴァエクストリーム！！！
line = "アルケインノヴァエクストリーム！！！"

[[dialogue]]
speaker = "unk"
# 空に向けて手を掲げながら、叫んだ。
line = "空に向けて手を掲げながら、叫んだ。"

[[dialogue]]
speaker = "ヨミ"
# 「！」
line = "「！」"

[[dialogue]]
speaker = "unk"
# 空高く昇った流星のような光が方向を変え、ヨミへ降り注ぐ。
line = "空高く昇った流星のような光が方向を変え、ヨミへ降り注ぐ。"

[[dialogue]]
speaker = "ヨミ"
# 「この力は、会長の！？　だとしたら、今こそ……！」
line = "「この力は、会長の！？　だとしたら、今こそ……！」"

[[dialogue]]
speaker = "ヨミ"
# 「チェンジ――ノヴァフォーム！！」
line = "「チェンジ――ノヴァフォーム！！」"

[[dialogue]]
speaker = "unk"
# 光がヨミを包み込む――そして。
line = "光がヨミを包み込む――そして。"

[[dialogue]]
speaker = "ヨミ"
# 「エクスノヴァフォーム、起動しました！！」
line = "「エクスノヴァフォーム、起動しました！！」"

[[dialogue]]
speaker = "unk"
# ヨミの姿は、人工覚醒戦闘服へとフォームチェンジしていた。
line = "ヨミの姿は、人工覚醒戦闘服へとフォームチェンジしていた。"

[[dialogue]]
speaker = "狛里"
# 「ヨミ先輩の体から、すごい力を感じるのです！」
line = "「ヨミ先輩の体から、すごい力を感じるのです！」"

[[dialogue]]
speaker = "モンスターたち"
# 「ガルルァッ！」
line = "「ガルルァッ！」"

[[dialogue]]
speaker = "unk"
# ヨミの体から発せられる星力の波動を感じてか、ライカンスウォームたちが一斉に動き出し、飛びかかってくる。
line = "ヨミの体から発せられる星力の波動を感じてか、ライカンスウォームたちが一斉に動き出し、飛びかかってくる。"

[[dialogue]]
speaker = "狛里"
# 「ヨミ先輩、敵が来るのです！」
line = "「ヨミ先輩、敵が来るのです！」"

[[dialogue]]
speaker = "ヨミ"
# （アニマ先輩が搭載したという<b>あの機能</b>が本当なら……！）
line = "（アニマ先輩が搭載したという<b>あの機能</b>が本当なら……！）"

[[dialogue]]
speaker = "ヨミ"
# 「破邪の鈴！」
line = "「破邪の鈴！」"

[[dialogue]]
speaker = "unk"
# 鈴を鳴らす。
line = "鈴を鳴らす。"

[[dialogue]]
speaker = "unk"
# 身体が舞う。
line = "身体が舞う。"

[[dialogue]]
speaker = "unk"
# 祈りを捧げるように踊る。
line = "祈りを捧げるように踊る。"

[[dialogue]]
speaker = "unk"
# 今までできなかったはずの動きが、自然と身体から溢れてくる。
line = "今までできなかったはずの動きが、自然と身体から溢れてくる。"

[[dialogue]]
speaker = "ヨミ"
# 「爆裂神楽――！！」
line = "「爆裂神楽――！！」"

[[dialogue]]
speaker = "unk"
# 清らかな鈴音が響き渡った。
line = "清らかな鈴音が響き渡った。"

[[dialogue]]
speaker = "モンスターたち"
# 「ガアアアッ！？」
line = "「ガアアアッ！？」"

[[dialogue]]
speaker = "unk"
# 襲いかかって来たライカンスウォームたちが浄化されて、次々と吹き飛んだ。
line = "襲いかかって来たライカンスウォームたちが浄化されて、次々と吹き飛んだ。"

[[dialogue]]
speaker = "狛里"
# 「ヨミ先輩の舞う姿……綺麗なのです！」
line = "「ヨミ先輩の舞う姿……綺麗なのです！」"

[[dialogue]]
speaker = "ヨミ"
# 「できた……！　天ヶ崎の『巫女舞』！！」
line = "「できた……！　天ヶ崎の『巫女舞』！！」"

[[dialogue]]
speaker = "unk"
# これまで、『リズム感』が壊滅的で、舞を踊れなかったヨミ。
line = "これまで、『リズム感』が壊滅的で、舞を踊れなかったヨミ。"

[[dialogue]]
speaker = "unk"
# しかし、人工戦闘服に搭載されたアニマ特性のアシストシステム『リズム感補正機能』により、ついに踊ることができるようになったのだ。
line = "しかし、人工戦闘服に搭載されたアニマ特性のアシストシステム『リズム感補正機能』により、ついに踊ることができるようになったのだ。"

[[dialogue]]
speaker = "ライカンスウォーム"
# 「ガルルルル……！」
line = "「ガルルルル……！」"

[[dialogue]]
speaker = "ヨミ"
# 「狛里。あのボスを倒す為に、力を貸して下さい！」
line = "「狛里。あのボスを倒す為に、力を貸して下さい！」"

[[dialogue]]
speaker = "ヨミ"
# 「２人で一緒に戦いましょう！」
line = "「２人で一緒に戦いましょう！」"

[[dialogue]]
speaker = "狛里"
# 「！　はいっ、ヨミ先輩！」
line = "「！　はいっ、ヨミ先輩！」"

[[dialogue]]
speaker = "狛里"
# 「かしこまりましたであります！」
line = "「かしこまりましたであります！」"

[[dialogue]]
speaker = "unk"
# ２人は肩を並べる。
line = "２人は肩を並べる。"

[[dialogue]]
speaker = "unk"
# 先輩と後輩は共に駆け出し、群れを率いるボス個体へと挑むのだった。
line = "先輩と後輩は共に駆け出し、群れを率いるボス個体へと挑むのだった。"
