[[dialogue]]
speaker = "unk"
# 第１３話,ＶＳ『ＸＥＬＯＳ』,B
line = "第１３話,ＶＳ『ＸＥＬＯＳ』,B"

[[dialogue]]
speaker = "unk"
# とうとう『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』を追い詰めた。傷を癒すことは叶わず、防衛のために敷いていた強靭な護り手も今はない。
line = "とうとう『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』を追い詰めた。傷を癒すことは叶わず、防衛のために敷いていた強靭な護り手も今はない。"

[[dialogue]]
speaker = "unk"
# 『ＸＥＬＯＳ』の足元に佇むホロウも１人きり……奴も察したことだろう。どれだけ女神の幼体を増殖させようと、俺たちには敵わないことを。
line = "『ＸＥＬＯＳ』の足元に佇むホロウも１人きり……奴も察したことだろう。どれだけ女神の幼体を増殖させようと、俺たちには敵わないことを。"

[[dialogue]]
speaker = "unk"
# もう逃がさない。『ベガの俺』から受け取ったこの力で──奴らを跡形もなく討ち滅ぼす。
line = "もう逃がさない。『ベガの俺』から受け取ったこの力で──奴らを跡形もなく討ち滅ぼす。"

[[dialogue]]
speaker = "梨緒"
# 「……決着をつけよう。これが本当に最後だ」
line = "「……決着をつけよう。これが本当に最後だ」"

[[dialogue]]
speaker = "ジグ"
# 「崩壊したベガの世界で幕を引く──創造神が散るには、ちょうどいい場所じゃないかな？」
line = "「崩壊したベガの世界で幕を引く──創造神が散るには、ちょうどいい場所じゃないかな？」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「『…………だ』」
line = "「『…………だ』」"

[[dialogue]]
speaker = "梨緒"
# 「……何？」
line = "「……何？」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「『……だめだ。私を消しては、いけない……』」
line = "「『……だめだ。私を消しては、いけない……』」"

[[dialogue]]
speaker = "unk"
# ホロウ・ルヴィネの口を使って、『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』が言葉を発する。
line = "ホロウ・ルヴィネの口を使って、『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』が言葉を発する。"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「『世界を、やりなおさなければ……いけない……』」
line = "「『世界を、やりなおさなければ……いけない……』」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「『“神”の拒絶……オマエたちは必ず、後悔する……』」
line = "「『“神”の拒絶……オマエたちは必ず、後悔する……』」"

[[dialogue]]
speaker = "梨緒"
# 「故郷を滅ぼされた私たちの前で……まだそんな言葉を吐けるとはな」
line = "「故郷を滅ぼされた私たちの前で……まだそんな言葉を吐けるとはな」"

[[dialogue]]
speaker = "ジグ"
# 「最期くらい、潔くしたらどうだい？　何度も君たちがやってきたことだ」
line = "「最期くらい、潔くしたらどうだい？　何度も君たちがやってきたことだ」"

[[dialogue]]
speaker = "梨緒"
# 「フィオナとエリシアの仇……」
line = "「フィオナとエリシアの仇……」"

[[dialogue]]
speaker = "ジグ"
# 「そして、散っていった同胞たちの無念を晴らさせてもらうよ」
line = "「そして、散っていった同胞たちの無念を晴らさせてもらうよ」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「『…………だめだ』」
line = "「『…………だめだ』」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「『だめだ──だめだ──だめだ──』」
line = "「『だめだ──だめだ──だめだ──』」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「『────不合理、不条理──不完全──』」
line = "「『────不合理、不条理──不完全──』」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「『“神”を残せ──消しては、ならない────』」
line = "「『“神”を残せ──消しては、ならない────』」"

[[dialogue]]
speaker = "チナ"
# 「……ふざけんな。全部、お前が始めたことだろうが！」
line = "「……ふざけんな。全部、お前が始めたことだろうが！」"

[[dialogue]]
speaker = "グレイス"
# 「自分が不利になった途端、命乞いですか……！？」
line = "「自分が不利になった途端、命乞いですか……！？」"

[[dialogue]]
speaker = "グレイス"
# 「死にたくない、消えたくない……そんなの、リクリエに消された人たちだって、みんな同じだったんですよ！？」
line = "「死にたくない、消えたくない……そんなの、リクリエに消された人たちだって、みんな同じだったんですよ！？」"

[[dialogue]]
speaker = "レティシア"
# 「聞くに堪えないわね……みんなと一緒の未来を勝ち取るためにも、あなた達は邪魔なの」
line = "「聞くに堪えないわね……みんなと一緒の未来を勝ち取るためにも、あなた達は邪魔なの」"

[[dialogue]]
speaker = "レティシア"
# 「今日ここで消えてもらうわ──『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』！」
line = "「今日ここで消えてもらうわ──『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』！」"

[[dialogue]]
speaker = "ベアトリス"
# 「『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』……あなたが戦いのどこかで、私たちのために言葉を紡いでくれてたら」
line = "「『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』……あなたが戦いのどこかで、私たちのために言葉を紡いでくれてたら」"

[[dialogue]]
speaker = "ベアトリス"
# 「脅迫するような言葉じゃなくって、譲り合える交渉のテーブルについてくれてたら……未来は違ったのかもしれない」
line = "「脅迫するような言葉じゃなくって、譲り合える交渉のテーブルについてくれてたら……未来は違ったのかもしれない」"

[[dialogue]]
speaker = "ベアトリス"
# 「でも、そうはならなかった……だから、私たちも生き残るために、全力を尽くことにしたんだよ！！」
line = "「でも、そうはならなかった……だから、私たちも生き残るために、全力を尽くことにしたんだよ！！」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「『考え直せ……“神”が滅びれば、世界はもうやり直せなくなる……』」
line = "「『考え直せ……“神”が滅びれば、世界はもうやり直せなくなる……』」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「『本当に、許容できるか……？　できるわけが、ない……』」
line = "「『本当に、許容できるか……？　できるわけが、ない……』」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「『ヒトであるオマエは、必ず願う……』」
line = "「『ヒトであるオマエは、必ず願う……』」"

[[dialogue]]
speaker = "ホロウ・ルヴィネL"
# 「『やり直したい。なかったことにしたい。そう思う時が、必ずくる────』」
line = "「『やり直したい。なかったことにしたい。そう思う時が、必ずくる────』」"

[[dialogue]]
speaker = "ベアトリス"
# 「確かに、目をそらしたくなるような不幸は、いつか必ずやってくるよ……でも！」
line = "「確かに、目をそらしたくなるような不幸は、いつか必ずやってくるよ……でも！」"

[[dialogue]]
speaker = "グレイス"
# 「不幸になっても、壊れても、崩れても！　何度だって、もう一度積み上げるだけです！」
line = "「不幸になっても、壊れても、崩れても！　何度だって、もう一度積み上げるだけです！」"

[[dialogue]]
speaker = "チナ"
# 「アタシたちはずっと、そうやって生きてきたんだ！」
line = "「アタシたちはずっと、そうやって生きてきたんだ！」"

[[dialogue]]
speaker = "レティシア"
# 「ええ。今までも、これからも……それは変わらない！！」
line = "「ええ。今までも、これからも……それは変わらない！！」"

[[dialogue]]
speaker = "ルヴィネ"
# 「……お父様。貴方の言うことは……わからないでもない」
line = "「……お父様。貴方の言うことは……わからないでもない」"

[[dialogue]]
speaker = "ルヴィネ"
# 「事実、人間界に降り立ったばかりの頃は──非効率なヒトの考えが理解が出来なかった……」
line = "「事実、人間界に降り立ったばかりの頃は──非効率なヒトの考えが理解が出来なかった……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「どうしてこんなにも、世界は間違っているのだろうと」
line = "「どうしてこんなにも、世界は間違っているのだろうと」"

[[dialogue]]
speaker = "ルヴィネ"
# 「醜く、不合理で、不条理で、正しいものなど１つもない……」
line = "「醜く、不合理で、不条理で、正しいものなど１つもない……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「そんな世界で足掻くくらいなら、全てを打ち捨てて、創り直せばいいじゃないか……って」
line = "「そんな世界で足掻くくらいなら、全てを打ち捨てて、創り直せばいいじゃないか……って」"

[[dialogue]]
speaker = "ルヴィネ"
# 「でも……違うんです。世界とは、命とは……そこまで単純なものではない」
line = "「でも……違うんです。世界とは、命とは……そこまで単純なものではない」"

[[dialogue]]
speaker = "ルヴィネ"
# 「生み出した物が、親の思惑を超えることもある……むしろ、思惑通りに動く生命なんてない」
line = "「生み出した物が、親の思惑を超えることもある……むしろ、思惑通りに動く生命なんてない」"

[[dialogue]]
speaker = "ルヴィネ"
# 「お父様は、ヒトはこれ以上進歩しないと断じていました……けれど、その前提も計算も間違っている。私はそう思っています」
line = "「お父様は、ヒトはこれ以上進歩しないと断じていました……けれど、その前提も計算も間違っている。私はそう思っています」"

[[dialogue]]
speaker = "ルヴィネ"
# 「ヒトや宇宙、星──命を紡ぎ続けるために、無限の成長が不可欠という点は同意しています」
line = "「ヒトや宇宙、星──命を紡ぎ続けるために、無限の成長が不可欠という点は同意しています」"

[[dialogue]]
speaker = "ルヴィネ"
# 「お父様が成し得なかったことは、私が引き継ぎましょう──あなたとは違うやり方で」
line = "「お父様が成し得なかったことは、私が引き継ぎましょう──あなたとは違うやり方で」"

[[dialogue]]
speaker = "unk"
# ルヴィネの言葉を聞いた『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』は──
line = "ルヴィネの言葉を聞いた『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』は──"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「『だめだ────だめだ、だめだ、だめだ──』」
line = "「『だめだ────だめだ、だめだ、だめだ──』」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「『私は────管理者である』」
line = "「『私は────管理者である』」"

[[dialogue]]
speaker = "ホロウ・ルヴィネ"
# 「『消えるわけにはいかない──完全、不滅、超越こそが“神”──』」
line = "「『消えるわけにはいかない──完全、不滅、超越こそが“神”──』」"

[[dialogue]]
speaker = "ルヴィネ"
# 「…………わかりました、お父様」
line = "「…………わかりました、お父様」"

[[dialogue]]
speaker = "ルヴィネ"
# 「あなたは最期まで、宇宙規模のプログラムでしかなかった。対話をすることは、できなかった……」
line = "「あなたは最期まで、宇宙規模のプログラムでしかなかった。対話をすることは、できなかった……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「１つの殻に閉じこもり、自分だけが正しいという前提を破壊できなかった……それは停滞でしかない。進歩も成長も、望めない……」
line = "「１つの殻に閉じこもり、自分だけが正しいという前提を破壊できなかった……それは停滞でしかない。進歩も成長も、望めない……」"

[[dialogue]]
speaker = "ルヴィネ"
# 「この世界を進歩させる、新たな女神として告げます」
line = "「この世界を進歩させる、新たな女神として告げます」"

[[dialogue]]
speaker = "ルヴィネ"
# 「私があなたを終わらせ、私たちの、私たちによる『<ruby=リ・クリエイション>再・創造</ruby>』をここから始めます！」
line = "「私があなたを終わらせ、私たちの、私たちによる『<ruby>再・創造<rt>リ・クリエイション</rt></ruby>』をここから始めます！」"

[[dialogue]]
speaker = "ラクシャ"
# 「デネブの魔王……そしてテルル。キミたちの仇を取る。だから……見守っていて」
line = "「デネブの魔王……そしてテルル。キミたちの仇を取る。だから……見守っていて」"

[[dialogue]]
speaker = "ラクシャ"
# 「守護天使が一柱・《円環》のラクシャ──亡き友と女神のために──『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』、お前を倒す！！」
line = "「守護天使が一柱・《円環》のラクシャ──亡き友と女神のために──『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』、お前を倒す！！」"

[[dialogue]]
speaker = "クロト"
# 「……行くぞ、『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』」
line = "「……行くぞ、『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』」"

[[dialogue]]
speaker = "クロト"
# 「お前が与えた試練によってヒトが得た星々の輝き──その身でとくと味わえ！！！」
line = "「お前が与えた試練によってヒトが得た星々の輝き──その身でとくと味わえ！！！」"
