[[dialogue]]
speaker = "unk"
# ――牛魔王の力を模したモンスターの強さは伊達ではなく、戦いは他の星騎士たちが救援に駆けつけてもなお、長引く程に壮絶なものとなった。
line = "――牛魔王の力を模したモンスターの強さは伊達ではなく、戦いは他の星騎士たちが救援に駆けつけてもなお、長引く程に壮絶なものとなった。"

[[dialogue]]
speaker = "unk"
# そうしてようやく……牛魔王は地に膝を着き、動きが止まる。
line = "そうしてようやく……牛魔王は地に膝を着き、動きが止まる。"

[[dialogue]]
speaker = "牛魔王"
# 「グウゥ……！」
line = "「グウゥ……！」"

[[dialogue]]
speaker = "紅明（羅刹）"
# 「牛魔王……終わりだ」
line = "「牛魔王……終わりだ」"

[[dialogue]]
speaker = "unk"
# 紅明が牛魔王の前へと歩み寄る。
line = "紅明が牛魔王の前へと歩み寄る。"

[[dialogue]]
speaker = "紅明（羅刹）"
# 「今回倒したとしても、アンタはこれからもまた、リクリエのモンスターとして何度も現れるのかもしれない」
line = "「今回倒したとしても、アンタはこれからもまた、リクリエのモンスターとして何度も現れるのかもしれない」"

[[dialogue]]
speaker = "紅明（羅刹）"
# 「だけど――その時はアタシが何度でも倒してみせる。現代に生まれ変わった、牛魔王の娘として」
line = "「だけど――その時はアタシが何度でも倒してみせる。現代に生まれ変わった、牛魔王の娘として」"

[[dialogue]]
speaker = "紅明（羅刹）"
# 「それに……アンタは偽物の魔王だ。だから」
line = "「それに……アンタは偽物の魔王だ。だから」"

[[dialogue]]
speaker = "紅明（羅刹）"
# 「現代に生まれ変わった本物の魔王には、絶対に勝てないよ」
line = "「現代に生まれ変わった本物の魔王には、絶対に勝てないよ」"

[[dialogue]]
speaker = "紅明（羅刹）"
# 「――吹き荒れろ！　芭蕉扇、羅刹のごとく！」
line = "「――吹き荒れろ！　芭蕉扇、羅刹のごとく！」"

[[dialogue]]
speaker = "紅明（羅刹）"
# 「元気大爆風！！！」
line = "「元気大爆風！！！」"

[[dialogue]]
speaker = "unk"
# 紅明が芭蕉扇を勢いよく振り下ろす。
line = "紅明が芭蕉扇を勢いよく振り下ろす。"

[[dialogue]]
speaker = "unk"
# その瞬間、牛魔王に向けて凄まじい突風が吹き荒れる。
line = "その瞬間、牛魔王に向けて凄まじい突風が吹き荒れる。"

[[dialogue]]
speaker = "unk"
# 芭蕉扇はただ強い風を起こすというだけの武器ではない。
line = "芭蕉扇はただ強い風を起こすというだけの武器ではない。"

[[dialogue]]
speaker = "unk"
# その能力は、火焔山の業火を消してみせたという西遊記の伝説にもある通り、『あらゆる力を吹き飛ばす』というもの。
line = "その能力は、火焔山の業火を消してみせたという西遊記の伝説にもある通り、『あらゆる力を吹き飛ばす』というもの。"

[[dialogue]]
speaker = "unk"
# そして、それはもちろん――リクリエの力であっても例外ではない。
line = "そして、それはもちろん――リクリエの力であっても例外ではない。"

[[dialogue]]
speaker = "牛魔王"
# 「グオオオォォォ―――ッ！！？」
line = "「グオオオォォォ―――ッ！！？」"

[[dialogue]]
speaker = "unk"
# 小さくなった蝋燭の火が吹き消されるように、リクリエの力で構成された牛魔王の体が揺らめいて、消滅していく。
line = "小さくなった蝋燭の火が吹き消されるように、リクリエの力で構成された牛魔王の体が揺らめいて、消滅していく。"

[[dialogue]]
speaker = "紅明（羅刹）"
# 「あばよ、親父殿……」
line = "「あばよ、親父殿……」"

[[dialogue]]
speaker = "unk"
# 果たして、後にＳＳランク指定される大型モンスター『牛魔王』は、現代に生まれ変わった娘の手によって討たれたのであった。
line = "果たして、後にＳＳランク指定される大型モンスター『牛魔王』は、現代に生まれ変わった娘の手によって討たれたのであった。"

[[dialogue]]
speaker = "unk"
# 俺は彼女のところへ歩み寄ると、頭に手を置いて――労わるように撫でる。
line = "俺は彼女のところへ歩み寄ると、頭に手を置いて――労わるように撫でる。"

[[dialogue]]
speaker = "unk"
# お疲れ様。紅明
line = "お疲れ様。紅明"

[[dialogue]]
speaker = "紅明（羅刹）"
# 「……うん。ダーリンもね♪」
line = "「……うん。ダーリンもね♪」"

[[dialogue]]
speaker = "クーシェン"
# 「ねーねー、終わったね」
line = "「ねーねー、終わったね」"

[[dialogue]]
speaker = "紅明（羅刹）"
# 「うん。クーちんもありがと♪」
line = "「うん。クーちんもありがと♪」"

[[dialogue]]
speaker = "unk"
# それから、紅明は誰よりも元気な笑顔を浮かべて見せると──
line = "それから、紅明は誰よりも元気な笑顔を浮かべて見せると──"

[[dialogue]]
speaker = "紅明（羅刹）"
# 「……さあ！　みんなで学園に帰って、祝杯をあげよっか☆　ウェ～イ♪」
line = "「……さあ！　みんなで学園に帰って、祝杯をあげよっか☆　ウェ～イ♪」"

[[dialogue]]
speaker = "unk"
# 救援に来てくれた星騎士たち１人１人のところへお礼に行き、ハイタッチを交わす。
line = "救援に来てくれた星騎士たち１人１人のところへお礼に行き、ハイタッチを交わす。"

[[dialogue]]
speaker = "クーシェン"
# 「ねぇ、にーにー」
line = "「ねぇ、にーにー」"

[[dialogue]]
speaker = "クーシェン"
# 「――ねーねーはやっぱり、強いヒトだね」
line = "「――ねーねーはやっぱり、強いヒトだね」"

[[dialogue]]
speaker = "unk"
# ああ、『大人』だな
line = "ああ、『大人』だな"

[[dialogue]]
speaker = "クーシェン"
# 「ま、今回はボクのおかげでもあるけどね～！　ウキキ♪」
line = "「ま、今回はボクのおかげでもあるけどね～！　ウキキ♪」"

[[dialogue]]
speaker = "クーシェン"
# 「あっ♪　もうっ。くすぐったいってば、にーにーっ♪　ボクもう、頭ナデナデされて喜ぶほど小さい子供じゃないんだから、やめてよね～！　えへへへぇ♪」
line = "「あっ♪　もうっ。くすぐったいってば、にーにーっ♪　ボクもう、頭ナデナデされて喜ぶほど小さい子供じゃないんだから、やめてよね～！　えへへへぇ♪」"

[[dialogue]]
speaker = "unk"
# 感謝を込めてクーシェンの頭も撫でてあげると、彼女は憎まれ口を叩きながらも、口元は嬉しそうにほころばせるのだった。
line = "感謝を込めてクーシェンの頭も撫でてあげると、彼女は憎まれ口を叩きながらも、口元は嬉しそうにほころばせるのだった。"

[[dialogue]]
speaker = "紅明"
# 「みんな、飲み物は持ったかな～？」
line = "「みんな、飲み物は持ったかな～？」"

[[dialogue]]
speaker = "クーシェン"
# 「は～い♪」
line = "「は～い♪」"

[[dialogue]]
speaker = "紅明"
# 「よ～し、それじゃあ――」
line = "「よ～し、それじゃあ――」"

[[dialogue]]
speaker = "紅明"
# 「カンパ～イ！」
line = "「カンパ～イ！」"

[[dialogue]]
speaker = "生徒たち"
# 「カンパ～イ！！！」
line = "「カンパ～イ！！！」"

[[dialogue]]
speaker = "クーシェン"
# 「カンパ～イ！」
line = "「カンパ～イ！」"

[[dialogue]]
speaker = "unk"
# 学園に帰還した俺たちは紅明の『祝杯』の宣言通り、牛魔王討伐のお疲れ様会を開催することになった。
line = "学園に帰還した俺たちは紅明の『祝杯』の宣言通り、牛魔王討伐のお疲れ様会を開催することになった。"

[[dialogue]]
speaker = "紅明"
# 「あのさ、ダーリン」
line = "「あのさ、ダーリン」"

[[dialogue]]
speaker = "unk"
# 何気ない話をしている途中、紅明がふと、いつもより少しだけ真剣な顔つきになった。
line = "何気ない話をしている途中、紅明がふと、いつもより少しだけ真剣な顔つきになった。"

[[dialogue]]
speaker = "紅明"
# 「アステラが出現する前にさ、悟空の記憶が戻らなくて寂しくないか、って聞いてくれたじゃん？」
line = "「アステラが出現する前にさ、悟空の記憶が戻らなくて寂しくないか、って聞いてくれたじゃん？」"

[[dialogue]]
speaker = "紅明"
# 「あの話の続きなんだけど……」
line = "「あの話の続きなんだけど……」"

[[dialogue]]
speaker = "紅明"
# 「『寂しくない』って言ったらさ……やっぱり嘘になっちゃうんだよね」
line = "「『寂しくない』って言ったらさ……やっぱり嘘になっちゃうんだよね」"

[[dialogue]]
speaker = "紅明"
# 「長い旅を共にした仲間だったからね。現代に生まれ変わってから、もしかしたら悟空たちにまた会えるのかもって……ずっと、期待してた」
line = "「長い旅を共にした仲間だったからね。現代に生まれ変わってから、もしかしたら悟空たちにまた会えるのかもって……ずっと、期待してた」"

[[dialogue]]
speaker = "紅明"
# 「でも、前世の最後にさ……アタシ、悟空とはちゃんとお別れしてるんだよね。今までずっとありがとうって」
line = "「でも、前世の最後にさ……アタシ、悟空とはちゃんとお別れしてるんだよね。今までずっとありがとうって」"

[[dialogue]]
speaker = "紅明"
# 「だから……悔いはないんだ。悟空とは元気に笑顔でお別れをしたんだよ」
line = "「だから……悔いはないんだ。悟空とは元気に笑顔でお別れをしたんだよ」"

[[dialogue]]
speaker = "紅明"
# 「それに、記憶がなくたって――今こうして、クーちんと出会って、また仲良くなれた」
line = "「それに、記憶がなくたって――今こうして、クーちんと出会って、また仲良くなれた」"

[[dialogue]]
speaker = "紅明"
# 「しかも、今度は可愛い年下の後輩になって！　それってさ、むしろアドじゃん？」
line = "「しかも、今度は可愛い年下の後輩になって！　それってさ、むしろアドじゃん？」"

[[dialogue]]
speaker = "紅明"
# 「それに今のアタシはもう、紅孩児じゃなくて、牛紅明だから」
line = "「それに今のアタシはもう、紅孩児じゃなくて、牛紅明だから」"

[[dialogue]]
speaker = "紅明"
# 「今を楽しんで生きるよ」
line = "「今を楽しんで生きるよ」"

[[dialogue]]
speaker = "紅明"
# 「今、隣にいる――ダーリンと一緒にね☆」
line = "「今、隣にいる――ダーリンと一緒にね☆」"

[[dialogue]]
speaker = "unk"
# 自分に言い聞かせるように、口角をあげて、うんうんと頷いて見せる紅明。
line = "自分に言い聞かせるように、口角をあげて、うんうんと頷いて見せる紅明。"

[[dialogue]]
speaker = "unk"
# そんな彼女の頭を、俺はもう１度、優しく撫でる。
line = "そんな彼女の頭を、俺はもう１度、優しく撫でる。"

[[dialogue]]
speaker = "クーシェン"
# 「にーにー！　ねーねー！　２人ともなんの話してるの～？」
line = "「にーにー！　ねーねー！　２人ともなんの話してるの～？」"

[[dialogue]]
speaker = "紅明"
# 「ん？　クーちんとこうして出会えて、最高にハッピーだって話さ☆」
line = "「ん？　クーちんとこうして出会えて、最高にハッピーだって話さ☆」"

[[dialogue]]
speaker = "クーシェン"
# 「んふふ～♪　そうでしょ～？　ボクってば、カッコ可愛いし、強いしね～☆　えへへへぇ♪」
line = "「んふふ～♪　そうでしょ～？　ボクってば、カッコ可愛いし、強いしね～☆　えへへへぇ♪」"

[[dialogue]]
speaker = "紅明"
# 「うんうん！　今日は星騎士の初仕事ですごく頑張ったから、ねーねーいっぱい頭撫でて褒めちゃうぞ～☆」
line = "「うんうん！　今日は星騎士の初仕事ですごく頑張ったから、ねーねーいっぱい頭撫でて褒めちゃうぞ～☆」"

[[dialogue]]
speaker = "紅明"
# 「ほれほれ～♪　うしし☆」
line = "「ほれほれ～♪　うしし☆」"

[[dialogue]]
speaker = "unk"
# そうして、いつもよりちょっぴり大人な笑顔で、クーシェンとじゃれ合う紅明なのであった――
line = "そうして、いつもよりちょっぴり大人な笑顔で、クーシェンとじゃれ合う紅明なのであった――"
