[[dialogue]]
speaker = "unk"
# 翌日。
line = "翌日。"

[[dialogue]]
speaker = "unk"
# 朝から妙な違和感を感じながら登校していると――
line = "朝から妙な違和感を感じながら登校していると――"

[[dialogue]]
speaker = "unk"
# ヒトリがジャクリーヌを連れて、大慌てで駆け込んできた。
line = "ヒトリがジャクリーヌを連れて、大慌てで駆け込んできた。"

[[dialogue]]
speaker = "ヒトリ"
# 「会長さん、た、たたたたた、大変なんです……っ！！」
line = "「会長さん、た、たたたたた、大変なんです……っ！！」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「ゆー！　ゆー！　ゆー！」
line = "「ゆー！　ゆー！　ゆー！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「トリックオアトリート～♪　会長、ヒトリ、今日もハロウィンに連れてって欲しいの！」
line = "「トリックオアトリート～♪　会長、ヒトリ、今日もハロウィンに連れてって欲しいの！」"

[[dialogue]]
speaker = "ヒトリ"
# 「じ、ジャクリーヌさん……それどころじゃ……！」
line = "「じ、ジャクリーヌさん……それどころじゃ……！」"

[[dialogue]]
speaker = "unk"
# ハロウィンは１年に１日しかないんだよ
line = "ハロウィンは１年に１日しかないんだよ"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆゆゆ？？？　そうなの？？？」
line = "「ゆゆゆ？？？　そうなの？？？」"

[[dialogue]]
speaker = "ヒトリ"
# 「か、会長さん……そ、そそそ、それが……っ！」
line = "「か、会長さん……そ、そそそ、それが……っ！」"

[[dialogue]]
speaker = "ヒトリ"
# 「いいから、落ち着いてって言われても……これを聞いたら会長さんだって落ち着けないですって……！」
line = "「いいから、落ち着いてって言われても……これを聞いたら会長さんだって落ち着けないですって……！」"

[[dialogue]]
speaker = "ヒトリ"
# 「じ、実は……ジャクリーヌさんが言っていることは間違いではなくて……今日もハロウィンになっちゃってるんです！」
line = "「じ、実は……ジャクリーヌさんが言っていることは間違いではなくて……今日もハロウィンになっちゃってるんです！」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「ゆー！　ゆー！」
line = "「ゆー！　ゆー！」"

[[dialogue]]
speaker = "ヒトリ"
# 「ハロウィンの日が、ループしちゃってるんです……！」
line = "「ハロウィンの日が、ループしちゃってるんです……！」"

[[dialogue]]
speaker = "ヒトリ"
# 「……う、うぅ……ぐすっ……わたし、どうしていいか分からなくなってしまって……」
line = "「……う、うぅ……ぐすっ……わたし、どうしていいか分からなくなってしまって……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「余には、ヒトリがどうしてそんなに慌ててるのかわかんないの～」
line = "「余には、ヒトリがどうしてそんなに慌ててるのかわかんないの～」"

[[dialogue]]
speaker = "unk"
# そういえば朝から妙な違和感があったんだ
line = "そういえば朝から妙な違和感があったんだ"

[[dialogue]]
speaker = "ヒトリ"
# 「……か、会長さんも？　よかったです……朝から違和感を感じてたのは、自分だけじゃ無かったんですね……」
line = "「……か、会長さんも？　よかったです……朝から違和感を感じてたのは、自分だけじゃ無かったんですね……」"

[[dialogue]]
speaker = "ヒトリ"
# 「何となくなんですけど……朝起きたらちょっと揺れてる？　感じというか、外に出たら嫌な感じがしたというか……す、すみません、うまく言えなくて……」
line = "「何となくなんですけど……朝起きたらちょっと揺れてる？　感じというか、外に出たら嫌な感じがしたというか……す、すみません、うまく言えなくて……」"

[[dialogue]]
speaker = "ヒトリ"
# 「同じ感覚だった……ですか？　あぁぁ、一緒の人がいて、よかったですぅ……」
line = "「同じ感覚だった……ですか？　あぁぁ、一緒の人がいて、よかったですぅ……」"

[[dialogue]]
speaker = "ヒトリ"
# 「こ、この原因はおそらく……ジャクリーヌさんが現れたからだと思ってるんですけど……どうでしょうか？」
line = "「こ、この原因はおそらく……ジャクリーヌさんが現れたからだと思ってるんですけど……どうでしょうか？」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ヒトリ～、そんなことより、またハロウィンパーティーに行くのー！」
line = "「ヒトリ～、そんなことより、またハロウィンパーティーに行くのー！」"

[[dialogue]]
speaker = "ヒトリ"
# 「ジャクリーヌさんは、ずっとこんな様子で……ど、どどど、どうしましょう……！」
line = "「ジャクリーヌさんは、ずっとこんな様子で……ど、どどど、どうしましょう……！」"

[[dialogue]]
speaker = "ヒトリ"
# 「お、落ち着いてって言われても……え？　俺に任せろって……わ、わかりました、お願いします……！」
line = "「お、落ち着いてって言われても……え？　俺に任せろって……わ、わかりました、お願いします……！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「？　会長、どうしたんだゆ？　本当にハロウィンは１日だけなの？」
line = "「？　会長、どうしたんだゆ？　本当にハロウィンは１日だけなの？」"

[[dialogue]]
speaker = "unk"
# ジャクリーヌ…… どんなイタズラをしたのか、正直に言うんだ
line = "ジャクリーヌ……\nどんなイタズラをしたのか、正直に言うんだ"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ぎくりっ……ゆ、余は何も知らないゆ！」
line = "「ぎくりっ……ゆ、余は何も知らないゆ！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「『１日がループするなんて大がかりなこと、何の制約もなしにできるわけがない』……？」
line = "「『１日がループするなんて大がかりなこと、何の制約もなしにできるわけがない』……？」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ループしてるっていうのは、本当に何を言ってるのかわからないゆ！　余はただ、もう１日ハロウィンの日が続けばいいのに！　って思っただけなの！」
line = "「ループしてるっていうのは、本当に何を言ってるのかわからないゆ！　余はただ、もう１日ハロウィンの日が続けばいいのに！　って思っただけなの！」"

[[dialogue]]
speaker = "unk"
# 仕掛けの中身は自分でもわからないのか……？ でもイタズラ自体は仕掛けただろ？
line = "仕掛けの中身は自分でもわからないのか……？\nでもイタズラ自体は仕掛けただろ？"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「か、かかか、会長が何を言ってるのか、余にはまったくわからないの……」
line = "「か、かかか、会長が何を言ってるのか、余にはまったくわからないの……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「わ、わかってくれたゆ……？　余は何も悪いことはしてないの！」
line = "「わ、わかってくれたゆ……？　余は何も悪いことはしてないの！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ハロウィンは楽しいパーティーなんだから、みんなだって１日じゃ遊び足りないって思ってるはずだゆ！」
line = "「ハロウィンは楽しいパーティーなんだから、みんなだって１日じゃ遊び足りないって思ってるはずだゆ！」"

[[dialogue]]
speaker = "ヒトリ"
# 「しょ、正直に言って、悪影響があるかはわからないです……」
line = "「しょ、正直に言って、悪影響があるかはわからないです……」"

[[dialogue]]
speaker = "ヒトリ"
# 「今のところ、そもそもこの事態に気づいているのが、わたしと会長さんだけっていうのもありますし……」
line = "「今のところ、そもそもこの事態に気づいているのが、わたしと会長さんだけっていうのもありますし……」"

[[dialogue]]
speaker = "ヒトリ"
# 「ただ、わたしのハロウィンフォームの棺桶に溜まっていたハロウィンパワーが、かなりの量減っています」
line = "「ただ、わたしのハロウィンフォームの棺桶に溜まっていたハロウィンパワーが、かなりの量減っています」"

[[dialogue]]
speaker = "ヒトリ"
# 「あ、ハロウィンパワーが減ることは全然問題ありません。これ自体は人間界に渦巻く『ハロウィンの信仰心』が集まった力なので、多く集まっても、消費しても、害はありません」
line = "「あ、ハロウィンパワーが減ることは全然問題ありません。これ自体は人間界に渦巻く『ハロウィンの信仰心』が集まった力なので、多く集まっても、消費しても、害はありません」"

[[dialogue]]
speaker = "ヒトリ"
# 「ジャクリーヌさんの言っていることを信じるなら、パンプキンファントムであるジャクリーヌさんの願いに反応して、ハロウィンの奇跡が起こってしまった、ということでしょうか？」
line = "「ジャクリーヌさんの言っていることを信じるなら、パンプキンファントムであるジャクリーヌさんの願いに反応して、ハロウィンの奇跡が起こってしまった、ということでしょうか？」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「よ、よくわからないけど、たぶんヒトリの言う通りなの！」
line = "「よ、よくわからないけど、たぶんヒトリの言う通りなの！」"

[[dialogue]]
speaker = "unk"
# まあ、もう１日ハロウィンを楽しむだけなら そこまで悪いことも起きようがない……か？
line = "まあ、もう１日ハロウィンを楽しむだけなら\nそこまで悪いことも起きようがない……か？"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「会長は話がわかるの！　そうと決まれば、今日は別の場所で新しいお菓子をもらいにいくの！」
line = "「会長は話がわかるの！　そうと決まれば、今日は別の場所で新しいお菓子をもらいにいくの！」"

[[dialogue]]
speaker = "ヒトリ"
# 「あっ、ジャクリーヌさん、待ってください……！」
line = "「あっ、ジャクリーヌさん、待ってください……！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ヒトリ……？」
line = "「ヒトリ……？」"

[[dialogue]]
speaker = "ヒトリ"
# 「ループの原因について、心当たりがないことは……信じます。ただ、約束してください。自分のためだけのイタズラは、これ以上繰り返さないって」
line = "「ループの原因について、心当たりがないことは……信じます。ただ、約束してください。自分のためだけのイタズラは、これ以上繰り返さないって」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「わかったの！　イタズラは今回だけにするゆ！」
line = "「わかったの！　イタズラは今回だけにするゆ！」"

[[dialogue]]
speaker = "ヒトリ"
# 「はい。それならわたしも……安心です」
line = "「はい。それならわたしも……安心です」"

[[dialogue]]
speaker = "ヒトリ"
# 「せっかくのハロウィン２日目ですから、楽しむことにしましょうか……」
line = "「せっかくのハロウィン２日目ですから、楽しむことにしましょうか……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「そうと決まれば、早速行くのー！」
line = "「そうと決まれば、早速行くのー！」"

[[dialogue]]
speaker = "unk"
# まさかのハロウィンがループしてしまう事態になったものの、その張本人であるジャクリーヌと<b>もう１日だけ</b>という約束で、パーティーを楽しむことにしたのだった。
line = "まさかのハロウィンがループしてしまう事態になったものの、その張本人であるジャクリーヌと<b>もう１日だけ</b>という約束で、パーティーを楽しむことにしたのだった。"
