[[dialogue]]
speaker = "トワ先生"
# 「やっぱりそうだね……。『ウェディングフォーム因子（仮）』が反応してる……」
line = "「やっぱりそうだね……。『ウェディングフォーム因子（仮）』が反応してる……」"

[[dialogue]]
speaker = "unk"
# トワが持つ試験管の中で、光る粒子が漂う。
line = "トワが持つ試験管の中で、光る粒子が漂う。"

[[dialogue]]
speaker = "unk"
# その粒子が放つ白い光は、さながら花嫁がまとうウェディングドレスのようだ。
line = "その粒子が放つ白い光は、さながら花嫁がまとうウェディングドレスのようだ。"

[[dialogue]]
speaker = "トワ先生"
# 「戦闘服がウェディングドレスに固定化されてしまう現象は、太陽フレアによる星力の爆発的な増大から始まった」
line = "「戦闘服がウェディングドレスに固定化されてしまう現象は、太陽フレアによる星力の爆発的な増大から始まった」"

[[dialogue]]
speaker = "トワ先生"
# 「わたし自身にもその現象が起こって、会長くんと疑似結婚式を挙げることになっちゃって……」
line = "「わたし自身にもその現象が起こって、会長くんと疑似結婚式を挙げることになっちゃって……」"

[[dialogue]]
speaker = "トワ先生"
# 「でもそんな大変な目にあったおかげで、この現象が起きている原因が分かってきた」
line = "「でもそんな大変な目にあったおかげで、この現象が起きている原因が分かってきた」"

[[dialogue]]
speaker = "トワ先生"
# 「それが──このウェディングフォーム因子（仮）……」
line = "「それが──このウェディングフォーム因子（仮）……」"

[[dialogue]]
speaker = "ジュエリー"
# 「少々長くて言いづらいね。今後は『ウェディング因子』と呼ぶのはどうだい？」
line = "「少々長くて言いづらいね。今後は『ウェディング因子』と呼ぶのはどうだい？」"

[[dialogue]]
speaker = "トワ先生"
# 「あ、それいいね──」
line = "「あ、それいいね──」"

[[dialogue]]
speaker = "トワ先生"
# 「ふえっ、ジュエリーちゃん？　ど、どうしてここに！？」
line = "「ふえっ、ジュエリーちゃん？　ど、どうしてここに！？」"

[[dialogue]]
speaker = "ジュエリー"
# 「６月といえばジューンブライド、結婚式の季節だ」
line = "「６月といえばジューンブライド、結婚式の季節だ」"

[[dialogue]]
speaker = "ジュエリー"
# 「星力を研究する『星体力学』の専門家であるトワ先生なら、ウェディングフォームの研究のためにここを訪れると思っていたよ」
line = "「星力を研究する『星体力学』の専門家であるトワ先生なら、ウェディングフォームの研究のためにここを訪れると思っていたよ」"

[[dialogue]]
speaker = "ジュエリー"
# 「明解に換言するならば──私もウェディングフォームに興味があるということだ」
line = "「明解に換言するならば──私もウェディングフォームに興味があるということだ」"

[[dialogue]]
speaker = "トワ先生"
# 「うん？　それは言い換えになっていないような……。でも名推理だよ。さすが『名探偵』の選星者だね」
line = "「うん？　それは言い換えになっていないような……。でも名推理だよ。さすが『名探偵』の選星者だね」"

[[dialogue]]
speaker = "ジュエリー"
# 「で、そのウェディング因子というのはいかなるものなのかな？」
line = "「で、そのウェディング因子というのはいかなるものなのかな？」"

[[dialogue]]
speaker = "トワ先生"
# 「えっと……ジュエリーちゃんはフィオナちゃんやわたしに起きた『ウェディングフォーム事件』のこと、知ってる？」
line = "「えっと……ジュエリーちゃんはフィオナちゃんやわたしに起きた『ウェディングフォーム事件』のこと、知ってる？」"

[[dialogue]]
speaker = "ジュエリー"
# 「もちろん知っているよ。学園内の出来事には常にアンテナを張っているからね」
line = "「もちろん知っているよ。学園内の出来事には常にアンテナを張っているからね」"

[[dialogue]]
speaker = "ジュエリー"
# 「まあ、あの事件に関してはアンテナを張る必要が無いほど広まっている話だけれど」
line = "「まあ、あの事件に関してはアンテナを張る必要が無いほど広まっている話だけれど」"

[[dialogue]]
speaker = "トワ先生"
# 「あぅ、そんなに有名になっちゃってるんだ……いやまぁレポート出したのわたしだけど……」
line = "「あぅ、そんなに有名になっちゃってるんだ……いやまぁレポート出したのわたしだけど……」"

[[dialogue]]
speaker = "トワ先生"
# 「あの事件の後、わたしは研究を続けて、自分のウェディングフォームから因子を抽出することに成功したんだ」
line = "「あの事件の後、わたしは研究を続けて、自分のウェディングフォームから因子を抽出することに成功したんだ」"

[[dialogue]]
speaker = "トワ先生"
# 「この因子は最初のウェディングフォームの発現の時に、流星市国全体に飛び散ってしまったんだけど、それが特定の時期、特定の場所に集まってしまうみたいなの」
line = "「この因子は最初のウェディングフォームの発現の時に、流星市国全体に飛び散ってしまったんだけど、それが特定の時期、特定の場所に集まってしまうみたいなの」"

[[dialogue]]
speaker = "ジュエリー"
# 「ということは、今この場所に？」
line = "「ということは、今この場所に？」"

[[dialogue]]
speaker = "トワ先生"
# 「うん。因子がここに集まってきて活性化してるの。ほら、見て……祭壇に近づけば近づくほど光が増してるでしょ？」
line = "「うん。因子がここに集まってきて活性化してるの。ほら、見て……祭壇に近づけば近づくほど光が増してるでしょ？」"

[[dialogue]]
speaker = "ジュエリー"
# 「なるほど、興味深い現象だね……ん？」
line = "「なるほど、興味深い現象だね……ん？」"

[[dialogue]]
speaker = "トワ先生"
# 「あ、あれ？　何だか急に因子の力が強く──」
line = "「あ、あれ？　何だか急に因子の力が強く──」"

[[dialogue]]
speaker = "トワ先生"
# 「はわわわわわっ！！？」
line = "「はわわわわわっ！！？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふむ……どうやら新たな事件が幕を開けてしまったようだね」
line = "「ふむ……どうやら新たな事件が幕を開けてしまったようだね」"

[[dialogue]]
speaker = "unk"
# 一方その頃、大聖堂では──
line = "一方その頃、大聖堂では──"

[[dialogue]]
speaker = "イレーナ"
# 「はぁ……ジューンブライドなんてどこの誰が思いついたのかしら。おかげであたしは結婚式に呼ばれまくって大忙しよ」
line = "「はぁ……ジューンブライドなんてどこの誰が思いついたのかしら。おかげであたしは結婚式に呼ばれまくって大忙しよ」"

[[dialogue]]
speaker = "イレーナ"
# 「わざわざあたしのこと名指ししてくるカップルもいるし……あーもう、神官やめてやろうかしら」
line = "「わざわざあたしのこと名指ししてくるカップルもいるし……あーもう、神官やめてやろうかしら」"

[[dialogue]]
speaker = "イレーナ"
# 「しかも６月って言ったら……『アレ』が起こるかもしれないのよね……」
line = "「しかも６月って言ったら……『アレ』が起こるかもしれないのよね……」"

[[dialogue]]
speaker = "イレーナ"
# 「まーた節操なしの会長が、新しい女の子を連れて結婚式を挙げにくるのかしら……そしたらあたしがまた神官役として駆り出されて……」
line = "「まーた節操なしの会長が、新しい女の子を連れて結婚式を挙げにくるのかしら……そしたらあたしがまた神官役として駆り出されて……」"

[[dialogue]]
speaker = "イレーナ"
# 「あーもうっ！　どうして人の幸せばかり見せつけられなきゃいけないのよ！」
line = "「あーもうっ！　どうして人の幸せばかり見せつけられなきゃいけないのよ！」"

[[dialogue]]
speaker = "イレーナ"
# 「あたしもウェディングドレス着てみたいし、結婚だって──」
line = "「あたしもウェディングドレス着てみたいし、結婚だって──」"

[[dialogue]]
speaker = "イレーナ"
# 「いやいやいや！　何言ってるのあたし！　バッカじゃないの！」
line = "「いやいやいや！　何言ってるのあたし！　バッカじゃないの！」"

[[dialogue]]
speaker = "イレーナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "イレーナ"
# 「結婚……ね」
line = "「結婚……ね」"

[[dialogue]]
speaker = "イレーナ"
# （結婚するなら素顔を……本当のあたしを相手に見せないといけない）
line = "（結婚するなら素顔を……本当のあたしを相手に見せないといけない）"

[[dialogue]]
speaker = "イレーナ"
# （本当のあたしを好きになってくれる人なんてどこにも……）
line = "（本当のあたしを好きになってくれる人なんてどこにも……）"

[[dialogue]]
speaker = "イレーナ"
# 「って、そんなこと考えてる場合じゃなかったわ。ただでさえ神官の仕事があるし、結婚式の説教も考えなきゃいけないし、とにかく忙しいのよ」
line = "「って、そんなこと考えてる場合じゃなかったわ。ただでさえ神官の仕事があるし、結婚式の説教も考えなきゃいけないし、とにかく忙しいのよ」"

[[dialogue]]
speaker = "イレーナ"
# 「ん？　今、セレスティアが一瞬光ったような……」
line = "「ん？　今、セレスティアが一瞬光ったような……」"

[[dialogue]]
speaker = "イレーナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "イレーナ"
# 「すっごく嫌な予感がしてきたわ……。もしかして……もしかして……」
line = "「すっごく嫌な予感がしてきたわ……。もしかして……もしかして……」"

[[dialogue]]
speaker = "イレーナ"
# 「あぁああああっ！！！　やっぱりーーーーーーっ！！！！」
line = "「あぁああああっ！！！　やっぱりーーーーーーっ！！！！」"

[[dialogue]]
speaker = "unk"
# 下校中、ＤＩＳＣの呼び出し音が鳴る。
line = "下校中、ＤＩＳＣの呼び出し音が鳴る。"

[[dialogue]]
speaker = "unk"
# もしもし？
line = "もしもし？"

[[dialogue]]
speaker = "イレーナ"
# 『会長さんですか？』
line = "『会長さんですか？』"

[[dialogue]]
speaker = "unk"
# は、はい……
line = "は、はい……"

[[dialogue]]
speaker = "イレーナ"
# 『今すぐ大聖堂まで来てください』
line = "『今すぐ大聖堂まで来てください』"

[[dialogue]]
speaker = "unk"
# えっ？　でも今から帰るところで……
line = "えっ？　でも今から帰るところで……"

[[dialogue]]
speaker = "イレーナ"
# 『いいから四の五の言わずに来なさい！！！』
line = "『いいから四の五の言わずに来なさい！！！』"

[[dialogue]]
speaker = "イレーナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# あの……ご用件は？
line = "あの……ご用件は？"

[[dialogue]]
speaker = "イレーナ"
# 「……絶対に笑わないでよ？　あと、この事はあたしたちだけの秘密だから……」
line = "「……絶対に笑わないでよ？　あと、この事はあたしたちだけの秘密だから……」"

[[dialogue]]
speaker = "イレーナ"
# 「じゃ……いくわ……」
line = "「じゃ……いくわ……」"

[[dialogue]]
speaker = "イレーナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# こ、これってもしかして……
line = "こ、これってもしかして……"

[[dialogue]]
speaker = "イレーナ"
# 「そうよ！　あたしも花嫁になっちゃったのよ！！！」
line = "「そうよ！　あたしも花嫁になっちゃったのよ！！！」"
