[[dialogue]]
speaker = "unk"
# 水着コンテスト、結果発表──
line = "水着コンテスト、結果発表──"

[[dialogue]]
speaker = "リップル"
# 「さあ、いよいよ審査のお時間デス──皆サン誰に投票するか決まりマシタか～？」
line = "「さあ、いよいよ審査のお時間デス──皆サン誰に投票するか決まりマシタか～？」"

[[dialogue]]
speaker = "マトイ"
# 「なんか光の玉がステージに集まってる──あれは何……？」
line = "「なんか光の玉がステージに集まってる──あれは何……？」"

[[dialogue]]
speaker = "アナ"
# 「観客の意見を星力に変換して吸い上げるシステムのようです」
line = "「観客の意見を星力に変換して吸い上げるシステムのようです」"

[[dialogue]]
speaker = "ヴィーナス"
# 「相変わらずなんでもアリね……」
line = "「相変わらずなんでもアリね……」"

[[dialogue]]
speaker = "ソフィア"
# 「リップルさんはリゾートのためならなんでも作ってしまうのです」
line = "「リップルさんはリゾートのためならなんでも作ってしまうのです」"

[[dialogue]]
speaker = "アポロ"
# 「あたしの優勝もあるか！？」
line = "「あたしの優勝もあるか！？」"

[[dialogue]]
speaker = "マトイ"
# 「うーん……残念だけど、会場の雰囲気を見る限りでは……」
line = "「うーん……残念だけど、会場の雰囲気を見る限りでは……」"

[[dialogue]]
speaker = "ヘレナ"
# 「フ……決まっているというものだ」
line = "「フ……決まっているというものだ」"

[[dialogue]]
speaker = "リップル"
# 「さあ……集計が終了シマシタ……いよいよ結果発表デス！」
line = "「さあ……集計が終了シマシタ……いよいよ結果発表デス！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ごく……」
line = "「ごく……」"

[[dialogue]]
speaker = "リップル"
# 「優勝は……カイチョ―デ～～～～～～～ス！！」
line = "「優勝は……カイチョ―デ～～～～～～～ス！！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「！？」
line = "「！？」"

[[dialogue]]
speaker = "マトイ"
# 「へ！？」
line = "「へ！？」"

[[dialogue]]
speaker = "unk"
# 俺？
line = "俺？"

[[dialogue]]
speaker = "unk"
# え？
line = "え？"

[[dialogue]]
speaker = "リップル"
# 「ハーイ！　ビーチのお客サンから圧倒的票数を集めて優勝デース！」
line = "「ハーイ！　ビーチのお客サンから圧倒的票数を集めて優勝デース！」"

[[dialogue]]
speaker = "リップル"
# 「皆サン最後には目がハートになってマシター！　リップルも納得デース！」
line = "「皆サン最後には目がハートになってマシター！　リップルも納得デース！」"

[[dialogue]]
speaker = "マトイ"
# 「た、確かにあのお姫様抱っこは劇的だったけど……！」
line = "「た、確かにあのお姫様抱っこは劇的だったけど……！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ヘレナちゃん、これって──」
line = "「ヘレナちゃん、これって──」"

[[dialogue]]
speaker = "ヘレナ"
# 「これは迂闊──飛び入り可、かつ、男女の規定を定めていなかったとは」
line = "「これは迂闊──飛び入り可、かつ、男女の規定を定めていなかったとは」"

[[dialogue]]
speaker = "ヘレナ"
# 「そして審査員は女子ばかり──これでは魔王に惹かれるのも無理はないというもの！」
line = "「そして審査員は女子ばかり──これでは魔王に惹かれるのも無理はないというもの！」"

[[dialogue]]
speaker = "サーシャ"
# 「あらあら……確かに私も会長くんにキュンってしちゃったけど」
line = "「あらあら……確かに私も会長くんにキュンってしちゃったけど」"

[[dialogue]]
speaker = "ルリエル"
# 「会長さん、さすがです！」
line = "「会長さん、さすがです！」"

[[dialogue]]
speaker = "リップル"
# 「おめでとうございマース！　初代水着グランプリの栄冠はカイチョーのものデース！」
line = "「おめでとうございマース！　初代水着グランプリの栄冠はカイチョーのものデース！」"

[[dialogue]]
speaker = "unk"
# そんなつもりじゃ……
line = "そんなつもりじゃ……"

[[dialogue]]
speaker = "ヘレナ"
# 「参ったな。せっかくのプロモーションの機会が……」
line = "「参ったな。せっかくのプロモーションの機会が……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「諦めなさい、ヘレナちゃん。公正な審査の結果でしょ♪」
line = "「諦めなさい、ヘレナちゃん。公正な審査の結果でしょ♪」"

[[dialogue]]
speaker = "観覧の女の子Ａ"
# 「やっぱ、最後に会長が全部持ってったよね！」
line = "「やっぱ、最後に会長が全部持ってったよね！」"

[[dialogue]]
speaker = "観覧の女の子Ｂ"
# 「ええ。あんなシチュエーション、女子なら一度は憧れるわ……」
line = "「ええ。あんなシチュエーション、女子なら一度は憧れるわ……」"

[[dialogue]]
speaker = "unk"
# そんなこんなで──
line = "そんなこんなで──"

[[dialogue]]
speaker = "unk"
# リゾート初の水着コンテストは、まさかの結果で幕を下ろすのだった。
line = "リゾート初の水着コンテストは、まさかの結果で幕を下ろすのだった。"

[[dialogue]]
speaker = "リップル"
# 「星徒会の皆サン、ご参加いただきどうもありがとうございマシター！　おかげでイベントは大成功デース！」
line = "「星徒会の皆サン、ご参加いただきどうもありがとうございマシター！　おかげでイベントは大成功デース！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ええ。こちらとしても嬉しいけど……今回、参加したのはヘレナちゃんのせいなのよ」
line = "「ええ。こちらとしても嬉しいけど……今回、参加したのはヘレナちゃんのせいなのよ」"

[[dialogue]]
speaker = "トリシャ"
# 「私の水着……ですか」
line = "「私の水着……ですか」"

[[dialogue]]
speaker = "リップル"
# 「ハーイ。その事情は先日お聞きシマシタ」
line = "「ハーイ。その事情は先日お聞きシマシタ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「い、いいの？　勝手にＰＲの場にされそうだったのに……」
line = "「い、いいの？　勝手にＰＲの場にされそうだったのに……」"

[[dialogue]]
speaker = "リップル"
# 「そのような思惑があったとは知りまセンでしたが、イベントのおかげでたくさんの人がリゾート結界に来てくれマシタ！」
line = "「そのような思惑があったとは知りまセンでしたが、イベントのおかげでたくさんの人がリゾート結界に来てくれマシタ！」"

[[dialogue]]
speaker = "リップル"
# 「盛り上がってたくさんのハッピーを感じられたので、ワタシは大変感謝していマース！」
line = "「盛り上がってたくさんのハッピーを感じられたので、ワタシは大変感謝していマース！」"

[[dialogue]]
speaker = "ヘレナ"
# 「リップルは海よりも広い心の持ち主だ。私も感謝している」
line = "「リップルは海よりも広い心の持ち主だ。私も感謝している」"

[[dialogue]]
speaker = "アポロ"
# 「おう！　あたしもバナナボートもらえたぞ、早くこれで海へ繰り出そうぜ！」
line = "「おう！　あたしもバナナボートもらえたぞ、早くこれで海へ繰り出そうぜ！」"

[[dialogue]]
speaker = "マトイ"
# 「元気ね……！」
line = "「元気ね……！」"

[[dialogue]]
speaker = "アナ"
# 「ふむ……参加賞のドリンクチケットもあるので、後日また来るのはアリですね」
line = "「ふむ……参加賞のドリンクチケットもあるので、後日また来るのはアリですね」"

[[dialogue]]
speaker = "ヴィーナス"
# 「みんな……もう、すっかり楽しんじゃって」
line = "「みんな……もう、すっかり楽しんじゃって」"

[[dialogue]]
speaker = "ヘレナ"
# 「フフ……どうだ？　ＷＩＮ－ＷＩＮだろう？」
line = "「フフ……どうだ？　ＷＩＮ－ＷＩＮだろう？」"

[[dialogue]]
speaker = "ヘレナ"
# 「優勝は逃してしまったが、これでも十分プロモーションにはなった。いっそこの機に、男性用水着にも参入してみるか……」
line = "「優勝は逃してしまったが、これでも十分プロモーションにはなった。いっそこの機に、男性用水着にも参入してみるか……」"

[[dialogue]]
speaker = "アナ"
# 「転んでもただじゃ起きませんね……」
line = "「転んでもただじゃ起きませんね……」"

[[dialogue]]
speaker = "ヴィーナス"
# 「商魂たくましすぎるわよ」
line = "「商魂たくましすぎるわよ」"

[[dialogue]]
speaker = "ヘレナ"
# 「トリシャも、無理を聞いてもらってすまなかったな」
line = "「トリシャも、無理を聞いてもらってすまなかったな」"

[[dialogue]]
speaker = "トリシャ"
# 「いえ……得難い経験ができました。それに……優勝はできませんでしたが、たくさん声をかけてもらいました」
line = "「いえ……得難い経験ができました。それに……優勝はできませんでしたが、たくさん声をかけてもらいました」"

[[dialogue]]
speaker = "トリシャ"
# 「フフ……またビーチで遊ぼう、と言ってくれた子もいました……にへへ……ヘレナさんのおかげ、です……」
line = "「フフ……またビーチで遊ぼう、と言ってくれた子もいました……にへへ……ヘレナさんのおかげ、です……」"

[[dialogue]]
speaker = "リップル"
# 「素晴らしいデース！　リゾート結界はフレンズの輪も広げマース！」
line = "「素晴らしいデース！　リゾート結界はフレンズの輪も広げマース！」"

[[dialogue]]
speaker = "ヘレナ"
# 「では、魔王。優勝賞金だ」
line = "「では、魔王。優勝賞金だ」"

[[dialogue]]
speaker = "unk"
# 受け取れませんよ
line = "受け取れませんよ"

[[dialogue]]
speaker = "unk"
# こんな大金……
line = "こんな大金……"

[[dialogue]]
speaker = "ヘレナ"
# 「遠慮するでない。九浄家当主ヘレナちゃんが、約束を破るケチんぼと思われるわけにはいかんのだ」
line = "「遠慮するでない。九浄家当主ヘレナちゃんが、約束を破るケチんぼと思われるわけにはいかんのだ」"

[[dialogue]]
speaker = "ルリエル"
# 「あーっ！　会長さんがこっそり優勝賞金をもらってますー！」
line = "「あーっ！　会長さんがこっそり優勝賞金をもらってますー！」"

[[dialogue]]
speaker = "アポロ"
# 「なに！？　独り占めか！？　ホントは魔王もグミ・パーティしたいだろ、なあ！？」
line = "「なに！？　独り占めか！？　ホントは魔王もグミ・パーティしたいだろ、なあ！？」"

[[dialogue]]
speaker = "サーシャ"
# 「ふふ……なんだかんだ、いいイベントだったわね♪」
line = "「ふふ……なんだかんだ、いいイベントだったわね♪」"

[[dialogue]]
speaker = "リップル"
# 「リゾート結界はこれからもたくさんのハッピーをお届けシマース！　皆サン、どうぞよろしくデ～～ス！」
line = "「リゾート結界はこれからもたくさんのハッピーをお届けシマース！　皆サン、どうぞよろしくデ～～ス！」"

[[dialogue]]
speaker = "unk"
# そうして、てんやわんやの１日は終わりを迎えるのだった……。
line = "そうして、てんやわんやの１日は終わりを迎えるのだった……。"
