[[dialogue]]
speaker = "エンジュ"
# 「ぅ……ぁ……──」
line = "「ぅ……ぁ……──」"

[[dialogue]]
speaker = "メテオラ"
# 「あぁああああぁぁぁぁっ！！！」
line = "「あぁああああぁぁぁぁっ！！！」"

[[dialogue]]
speaker = "リーリア"
# 「ウソ、立ち上がった！？　コラプサーって不死身なんですかっ！？」
line = "「ウソ、立ち上がった！？　コラプサーって不死身なんですかっ！？」"

[[dialogue]]
speaker = "コハルコ"
# 「なんか様子が変……！？　正気じゃ……ない……？」
line = "「なんか様子が変……！？　正気じゃ……ない……？」"

[[dialogue]]
speaker = "エンジュ"
# 「声……声が……声が聞こえる……うるさい……おまえらっ、うるさいっ、うるざいぃぃっ！」
line = "「声……声が……声が聞こえる……うるさい……おまえらっ、うるさいっ、うるざいぃぃっ！」"

[[dialogue]]
speaker = "メテオラ"
# 「おまえたち、悪いやつ……許さない、ぜったい、ぜったい、ゆるさ、ないいぃいぃ……！」
line = "「おまえたち、悪いやつ……許さない、ぜったい、ぜったい、ゆるさ、ないいぃいぃ……！」"

[[dialogue]]
speaker = "エンジュ"
# 「うぁ……頭が……痛い痛い痛いぃッ！　星騎士、は……潰す、ぶっっっ潰すぅッ！」
line = "「うぁ……頭が……痛い痛い痛いぃッ！　星騎士、は……潰す、ぶっっっ潰すぅッ！」"

[[dialogue]]
speaker = "リーリア"
# 「きゃぁああああぁあぁっ！？」
line = "「きゃぁああああぁあぁっ！？」"

[[dialogue]]
speaker = "unk"
# なんだ、この力っ！？
line = "なんだ、この力っ！？"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ッ……！？　凄まじい衝撃ですわ……！」
line = "「ッ……！？　凄まじい衝撃ですわ……！」"

[[dialogue]]
speaker = "リーリア"
# 「この感じ、星力でも魔力でもない……！？　どうなってるんですか！？」
line = "「この感じ、星力でも魔力でもない……！？　どうなってるんですか！？」"

[[dialogue]]
speaker = "メテオラ"
# 「うぅあああああああっっっ！！！」
line = "「うぅあああああああっっっ！！！」"

[[dialogue]]
speaker = "エンジュ"
# 「おおぉぉおおおーーーッッ！！！」
line = "「おおぉぉおおおーーーッッ！！！」"

[[dialogue]]
speaker = "unk"
# 獣のような咆哮と共に、メテオラとエンジュの体から力が弾けて──
line = "獣のような咆哮と共に、メテオラとエンジュの体から力が弾けて──"

[[dialogue]]
speaker = "unk"
# コラプサーの異常は、新星学園内部だけではなかった。
line = "コラプサーの異常は、新星学園内部だけではなかった。"

[[dialogue]]
speaker = "キサナ"
# 「んがぁあぁああっ！！　止めろ！　声を！　止めろっつってんだよぉぉッ！！」
line = "「んがぁあぁああっ！！　止めろ！　声を！　止めろっつってんだよぉぉッ！！」"

[[dialogue]]
speaker = "ミア"
# 「な、何が起こってるの！？　話がまったく通じなくなってるし、無差別に大暴れするし、あいつもう正気じゃ──」
line = "「な、何が起こってるの！？　話がまったく通じなくなってるし、無差別に大暴れするし、あいつもう正気じゃ──」"

[[dialogue]]
speaker = "キサナ"
# 「ぅあ……あ……あっ──！？」
line = "「ぅあ……あ……あっ──！？」"

[[dialogue]]
speaker = "ミア"
# 「え……動きが、止まった……？　倒れちゃった……また動き出したりしないわよね……？　まるで電池の切れたオモチャみたい……」
line = "「え……動きが、止まった……？　倒れちゃった……また動き出したりしないわよね……？　まるで電池の切れたオモチャみたい……」"

[[dialogue]]
speaker = "ミア"
# 「──えっと……こちら、ミアです。戦闘終了……劣勢でしたが、対象は突然、沈黙……動き出す気配はありません」
line = "「──えっと……こちら、ミアです。戦闘終了……劣勢でしたが、対象は突然、沈黙……動き出す気配はありません」"

[[dialogue]]
speaker = "ミア"
# 「えっ、他の地域のコラプサーも、同じように暴れ出して、急に大人しくなった……？　了解です、ありがとうございます。お疲れさまでした」
line = "「えっ、他の地域のコラプサーも、同じように暴れ出して、急に大人しくなった……？　了解です、ありがとうございます。お疲れさまでした」"

[[dialogue]]
speaker = "ミア"
# 「うーん……なんか腑に落ちないわね……気味が悪い」
line = "「うーん……なんか腑に落ちないわね……気味が悪い」"

[[dialogue]]
speaker = "キサナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "ミア"
# 「とりあえず、この人と戦うのは、もう勘弁。数奇なご縁もこれっきりにしたいものだわ……」
line = "「とりあえず、この人と戦うのは、もう勘弁。数奇なご縁もこれっきりにしたいものだわ……」"

[[dialogue]]
speaker = "unk"
# エンジュとメテオラから迸った衝撃が、俺達を巻き込んでトレーニング施設を破壊する。
line = "エンジュとメテオラから迸った衝撃が、俺達を巻き込んでトレーニング施設を破壊する。"

[[dialogue]]
speaker = "unk"
# 先ほどとは違い、今立っているのはコラプサーの２人の方だった。
line = "先ほどとは違い、今立っているのはコラプサーの２人の方だった。"

[[dialogue]]
speaker = "エンジュ"
# 「はっ！？　何が起こった！？」
line = "「はっ！？　何が起こった！？」"

[[dialogue]]
speaker = "メテオラ"
# 「体がボロボロだぞっ……おまえらがやったんだな！？　くそーっ！」
line = "「体がボロボロだぞっ……おまえらがやったんだな！？　くそーっ！」"

[[dialogue]]
speaker = "unk"
# 正気を取り戻した！？
line = "正気を取り戻した！？"

[[dialogue]]
speaker = "エンジュ"
# 「な、なんだ？　どうなってる、あたしら、やられたはずじゃ──いや、今はどうでもいい、コハルコを捕まえるぞっ！」
line = "「な、なんだ？　どうなってる、あたしら、やられたはずじゃ──いや、今はどうでもいい、コハルコを捕まえるぞっ！」"

[[dialogue]]
speaker = "メテオラ"
# 「おう！　あたしたちの勝ちなのだ！」
line = "「おう！　あたしたちの勝ちなのだ！」"

[[dialogue]]
speaker = "エンジュ"
# 「コハルコ、お前を連れ帰れば、あたしたちの悲願は達成される！」
line = "「コハルコ、お前を連れ帰れば、あたしたちの悲願は達成される！」"

[[dialogue]]
speaker = "コハルコ"
# 「こ、来ないでっ！」
line = "「こ、来ないでっ！」"

[[dialogue]]
speaker = "unk"
# 執念で迫りくるコラプサーに対し、コハルコさんは両手を向けた。
line = "執念で迫りくるコラプサーに対し、コハルコさんは両手を向けた。"

[[dialogue]]
speaker = "メテオラ"
# 「無駄だぞっ……体はボロボロでもあたしたちは星力を吸収し──」
line = "「無駄だぞっ……体はボロボロでもあたしたちは星力を吸収し──」"

[[dialogue]]
speaker = "unk"
# しかし放たれたのはドローンの射撃ではなく、彼女自身の手から生み出された光の矢だった。
line = "しかし放たれたのはドローンの射撃ではなく、彼女自身の手から生み出された光の矢だった。"

[[dialogue]]
speaker = "エンジュ"
# 「ぐぁあぁぁっ！　吸収、できないっ……？　これは、まりょ……く……？」
line = "「ぐぁあぁぁっ！　吸収、できないっ……？　これは、まりょ……く……？」"

[[dialogue]]
speaker = "メテオラ"
# 「今の、なんなんだぞ……！？」
line = "「今の、なんなんだぞ……！？」"

[[dialogue]]
speaker = "unk"
# コハルコさんが放った光は、何度攻撃を喰らっても立ち上がり続けたコラプサーたちへの最後の一撃となった。
line = "コハルコさんが放った光は、何度攻撃を喰らっても立ち上がり続けたコラプサーたちへの最後の一撃となった。"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「はぁ、はぁ……動かなくなりましたわね。今度こそ私たちの勝ち……ですわね」
line = "「はぁ、はぁ……動かなくなりましたわね。今度こそ私たちの勝ち……ですわね」"

[[dialogue]]
speaker = "リーリア"
# 「ふう……お見事なフィニッシュブローでしたね、コハルコ先輩」
line = "「ふう……お見事なフィニッシュブローでしたね、コハルコ先輩」"

[[dialogue]]
speaker = "コハルコ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "コハルコ"
# 「……私が彼女たちに放った咄嗟の一撃……星力を使ったのなら、コラプサーの力によって無力化されたはず。だけど今の力は──」
line = "「……私が彼女たちに放った咄嗟の一撃……星力を使ったのなら、コラプサーの力によって無力化されたはず。だけど今の力は──」"

[[dialogue]]
speaker = "リーリア"
# 「あ～……さすがっていうか、当然っていうか……やっぱり、コハルコ先輩なら気づいちゃいますよね……」
line = "「あ～……さすがっていうか、当然っていうか……やっぱり、コハルコ先輩なら気づいちゃいますよね……」"

[[dialogue]]
speaker = "unk"
# 全てを知っていたリーリアは観念したように、それでいて、複雑そうな面持ちで。
line = "全てを知っていたリーリアは観念したように、それでいて、複雑そうな面持ちで。"

[[dialogue]]
speaker = "リーリア"
# 「コハルコ先輩、あなたの正体は魔女なんです」
line = "「コハルコ先輩、あなたの正体は魔女なんです」"

[[dialogue]]
speaker = "unk"
# そう、はっきりと告げたのだった。
line = "そう、はっきりと告げたのだった。"
