[[dialogue]]
speaker = "蛍火"
# 「子ども会のクリスマスパーティーの料理とその材料のリストです。特製スパイスを使った七面鳥のローストがメインの予定です」
line = "「子ども会のクリスマスパーティーの料理とその材料のリストです。特製スパイスを使った七面鳥のローストがメインの予定です」"

[[dialogue]]
speaker = "イレーナ"
# 「ありがとうございます。予算は……問題なさそうですね」
line = "「ありがとうございます。予算は……問題なさそうですね」"

[[dialogue]]
speaker = "イレーナ"
# 「ですが子ども会なので、刺激が強すぎるのは避けた方がよいかもしれません」
line = "「ですが子ども会なので、刺激が強すぎるのは避けた方がよいかもしれません」"

[[dialogue]]
speaker = "蛍火"
# 「ですので試食を用意しました。こちらでいかがでしょう？」
line = "「ですので試食を用意しました。こちらでいかがでしょう？」"

[[dialogue]]
speaker = "イレーナ"
# 「頂きます。どれどれ……ええ、これなら問題ないですね。とても美味しいです」
line = "「頂きます。どれどれ……ええ、これなら問題ないですね。とても美味しいです」"

[[dialogue]]
speaker = "サラン"
# 「じゃ～んっ、子ども会用のクリスマスケーキのスケッチだよ～♪」
line = "「じゃ～んっ、子ども会用のクリスマスケーキのスケッチだよ～♪」"

[[dialogue]]
speaker = "シャロン"
# 「おおっ、なんと見事な……！　食べるのがもったいないくらいです。これなら子どもたちも喜ぶこと間違いなしですね！」
line = "「おおっ、なんと見事な……！　食べるのがもったいないくらいです。これなら子どもたちも喜ぶこと間違いなしですね！」"

[[dialogue]]
speaker = "サラン"
# 「えへへ～、そう言ってくれると嬉しいな～」
line = "「えへへ～、そう言ってくれると嬉しいな～」"

[[dialogue]]
speaker = "シャロン"
# 「蛍火さま、サランさま。この度はご助力いただき本当にありがとうございます」
line = "「蛍火さま、サランさま。この度はご助力いただき本当にありがとうございます」"

[[dialogue]]
speaker = "蛍火"
# 「いえ、むしろ有り難いです。こういった場で腕を振るうことこそ料理人の本懐でありますので」
line = "「いえ、むしろ有り難いです。こういった場で腕を振るうことこそ料理人の本懐でありますので」"

[[dialogue]]
speaker = "サラン"
# 「楽しいクリスマスパーティーにしようね～♪　サランも腕によりをかけてお菓子を作るから～♪」
line = "「楽しいクリスマスパーティーにしようね～♪　サランも腕によりをかけてお菓子を作るから～♪」"

[[dialogue]]
speaker = "シャロン"
# 「はいっ、もちろん！　子どもたちのため、女神様へ愛を伝えるため、必ずや聖誕祭を成功させましょう！」
line = "「はいっ、もちろん！　子どもたちのため、女神様へ愛を伝えるため、必ずや聖誕祭を成功させましょう！」"

[[dialogue]]
speaker = "サラン"
# 「いえ～～♪」
line = "「いえ～～♪」"

[[dialogue]]
speaker = "蛍火"
# （シャロンさんの圧が強い……ついていけるサランさんもさすがです……）
line = "（シャロンさんの圧が強い……ついていけるサランさんもさすがです……）"

[[dialogue]]
speaker = "unk"
# イレーナとシャロンを中心に、子ども会のクリスマスパーティーの準備を進める面々。
line = "イレーナとシャロンを中心に、子ども会のクリスマスパーティーの準備を進める面々。"

[[dialogue]]
speaker = "unk"
# 本番のパーティーも、この布陣なら間違いなく素敵なものになるだろうな。
line = "本番のパーティーも、この布陣なら間違いなく素敵なものになるだろうな。"

[[dialogue]]
speaker = "イレーナ"
# 「ふぅ……食材関係の手配はだいたい済んだわね。みんな帰ったからようやく気を抜けるわ」
line = "「ふぅ……食材関係の手配はだいたい済んだわね。みんな帰ったからようやく気を抜けるわ」"

[[dialogue]]
speaker = "unk"
# 教皇庁主催だからもっと厳格な会かと思った
line = "教皇庁主催だからもっと厳格な会かと思った"

[[dialogue]]
speaker = "イレーナ"
# 「確かに教皇庁内じゃ、もっと粛々にって声もあるけどね。でも子どもたちに固いこと言っても嫌われるだけよ」
line = "「確かに教皇庁内じゃ、もっと粛々にって声もあるけどね。でも子どもたちに固いこと言っても嫌われるだけよ」"

[[dialogue]]
speaker = "イレーナ"
# 「あくまでこれは子どもたちのためのクリスマスパーティーなんだから。明るく楽しませてあげるのが正解でしょ？」
line = "「あくまでこれは子どもたちのためのクリスマスパーティーなんだから。明るく楽しませてあげるのが正解でしょ？」"

[[dialogue]]
speaker = "unk"
# ところでその格好……
line = "ところでその格好……"

[[dialogue]]
speaker = "イレーナ"
# 「ふふん、どうかしら？　せっかくならクリスマスらしい装いをと思って調整してみたの♪」
line = "「ふふん、どうかしら？　せっかくならクリスマスらしい装いをと思って調整してみたの♪」"

[[dialogue]]
speaker = "イレーナ"
# 「クリスマスといえばサンタだものね。まぁどうしてだか何度調整しても衣装が黒く染まっちゃうんだけど……」
line = "「クリスマスといえばサンタだものね。まぁどうしてだか何度調整しても衣装が黒く染まっちゃうんだけど……」"

[[dialogue]]
speaker = "イレーナ"
# 「でもでも可愛いでしょ♪　ここまで仕上げるのに結構苦労したのよ♪」
line = "「でもでも可愛いでしょ♪　ここまで仕上げるのに結構苦労したのよ♪」"

[[dialogue]]
speaker = "unk"
# ……性夜でも届けにでも行くつもり？
line = "……性夜でも届けにでも行くつもり？"

[[dialogue]]
speaker = "イレーナ"
# 「んなわけあるかっ！　なに想像してるのよ、このエロ魔王！」
line = "「んなわけあるかっ！　なに想像してるのよ、このエロ魔王！」"

[[dialogue]]
speaker = "シャロン"
# 「素晴らしいですっ」
line = "「素晴らしいですっ」"

[[dialogue]]
speaker = "イレーナ"
# 「ひぃあっ！？　シャロ──シスターシャロン！？　まだおられたのですか？」
line = "「ひぃあっ！？　シャロ──シスターシャロン！？　まだおられたのですか？」"

[[dialogue]]
speaker = "シャロン"
# 「素晴らしいです、イレーナさま！　聖誕祭へのその意気込み、女神様にもしかと伝わっておりますよっ！」
line = "「素晴らしいです、イレーナさま！　聖誕祭へのその意気込み、女神様にもしかと伝わっておりますよっ！」"

[[dialogue]]
speaker = "イレーナ"
# 「い、いえ、私はそんなつもりでは……。単にクリスマスらしい気分をと……」
line = "「い、いえ、私はそんなつもりでは……。単にクリスマスらしい気分をと……」"

[[dialogue]]
speaker = "シャロン"
# 「つまり子どもたちと同じ目線に立とうとなさって！　流石は聖女さまですっ。私も見習わなくてはっ」
line = "「つまり子どもたちと同じ目線に立とうとなさって！　流石は聖女さまですっ。私も見習わなくてはっ」"

[[dialogue]]
speaker = "イレーナ"
# 「あ、あはは……恐縮です……」
line = "「あ、あはは……恐縮です……」"

[[dialogue]]
speaker = "イレーナ"
# （この子、いつになくテンション高いわね。勢いに磨きがかかってるわ……）
line = "（この子、いつになくテンション高いわね。勢いに磨きがかかってるわ……）"

[[dialogue]]
speaker = "シャロン"
# 「私もイレーナさまのようにパーティーに相応しい装いをできればよいのですが。このような感じでしょうか……むんっ」
line = "「私もイレーナさまのようにパーティーに相応しい装いをできればよいのですが。このような感じでしょうか……むんっ」"

[[dialogue]]
speaker = "シャロン"
# 「はぅ、上手くいきません……」
line = "「はぅ、上手くいきません……」"

[[dialogue]]
speaker = "イレーナ"
# 「精緻な星力操作が必要になる作業ですからね。かく言う私もいささか露出の多い衣装になってしまいましたし……」
line = "「精緻な星力操作が必要になる作業ですからね。かく言う私もいささか露出の多い衣装になってしまいましたし……」"

[[dialogue]]
speaker = "シャロン"
# 「いえ、きっと私の女神様への愛が足りないせいですよ！　浮かれる前に子どもたちのため、女神様のため、まずは聖誕祭の準備をしろと天が仰っているのです！」
line = "「いえ、きっと私の女神様への愛が足りないせいですよ！　浮かれる前に子どもたちのため、女神様のため、まずは聖誕祭の準備をしろと天が仰っているのです！」"

[[dialogue]]
speaker = "イレーナ"
# 「そ、そうですか。ならどうか頑張ってくださ──」
line = "「そ、そうですか。ならどうか頑張ってくださ──」"

[[dialogue]]
speaker = "シャロン"
# 「共に参りましょう、イレーナさま！　必ずやクリスマスパーティーを成功させるのです！」
line = "「共に参りましょう、イレーナさま！　必ずやクリスマスパーティーを成功させるのです！」"

[[dialogue]]
speaker = "イレーナ"
# 「ちょっ！？　引っ張らないでくださいっ、私は神官の仕事が残って──」
line = "「ちょっ！？　引っ張らないでくださいっ、私は神官の仕事が残って──」"

[[dialogue]]
speaker = "イレーナ"
# 「きゃあ～～～～っ！？」
line = "「きゃあ～～～～っ！？」"

[[dialogue]]
speaker = "イレーナ"
# 「ぜぇぜぇ……。いろいろやらされて疲れた……」
line = "「ぜぇぜぇ……。いろいろやらされて疲れた……」"

[[dialogue]]
speaker = "イレーナ"
# 「シャロンってば、いつにも増して張り切りすぎよ……。振り回されるこっちの身にもなって欲しいわ……」
line = "「シャロンってば、いつにも増して張り切りすぎよ……。振り回されるこっちの身にもなって欲しいわ……」"

[[dialogue]]
speaker = "イレーナ"
# 「はぁ……できることならめんどくさい企画側じゃなくて、参加側に立ちたかったわ……」
line = "「はぁ……できることならめんどくさい企画側じゃなくて、参加側に立ちたかったわ……」"

[[dialogue]]
speaker = "unk"
# 子ども苦手そうだもんな
line = "子ども苦手そうだもんな"

[[dialogue]]
speaker = "イレーナ"
# 「……ふふ、いいことを思いついたわ。あたしがソリに乗って子どもたちにプレゼントを配るの。もちろんソリを引くトナカイ役はあんたね♪」
line = "「……ふふ、いいことを思いついたわ。あたしがソリに乗って子どもたちにプレゼントを配るの。もちろんソリを引くトナカイ役はあんたね♪」"

[[dialogue]]
speaker = "unk"
# どうかお慈悲を……！
line = "どうかお慈悲を……！"

[[dialogue]]
speaker = "イレーナ"
# 「ったくもう……。ただでさえ今日は猫被って疲れたってのに、余計なツッコミ入れさせんじゃないわ」
line = "「ったくもう……。ただでさえ今日は猫被って疲れたってのに、余計なツッコミ入れさせんじゃないわ」"

[[dialogue]]
speaker = "イレーナ"
# 「あ～パネットーネ食べたーい。準備なんかしないでパーティーだけ楽しみたーい」
line = "「あ～パネットーネ食べたーい。準備なんかしないでパーティーだけ楽しみたーい」"

[[dialogue]]
speaker = "unk"
# 食べればいいじゃないか
line = "食べればいいじゃないか"

[[dialogue]]
speaker = "イレーナ"
# 「あのね、パネットーネは普通のパンとは違うの。あたしもよく知らないけど、昔ながらのやり方で作った種を使うんだって。あと発酵にも時間がかかるし」
line = "「あのね、パネットーネは普通のパンとは違うの。あたしもよく知らないけど、昔ながらのやり方で作った種を使うんだって。あと発酵にも時間がかかるし」"

[[dialogue]]
speaker = "イレーナ"
# 「母さんのパネットーネが恋しいわ。この時期になると作ってくれたっけ」
line = "「母さんのパネットーネが恋しいわ。この時期になると作ってくれたっけ」"

[[dialogue]]
speaker = "イレーナ"
# 「うちの地元ではね、クリスマスといえばパネットーネだったの。自作のパネットーネを親しい友人に配るのが慣習でね」
line = "「うちの地元ではね、クリスマスといえばパネットーネだったの。自作のパネットーネを親しい友人に配るのが慣習でね」"

[[dialogue]]
speaker = "イレーナ"
# 「ま、自作っていっても、あたしは母さんを手伝うくらいだったけど」
line = "「ま、自作っていっても、あたしは母さんを手伝うくらいだったけど」"

[[dialogue]]
speaker = "イレーナ"
# 「あ～あ、きっと地元では今頃パネットーネを交換し合ってるんだろうなー。あたしもクリスマスパーティーの準備より、そっちに混ざりた──」
line = "「あ～あ、きっと地元では今頃パネットーネを交換し合ってるんだろうなー。あたしもクリスマスパーティーの準備より、そっちに混ざりた──」"

[[dialogue]]
speaker = "シャロン"
# 「あっ、イレーナさま！　こちらにいらっしゃったのですね！」
line = "「あっ、イレーナさま！　こちらにいらっしゃったのですね！」"

[[dialogue]]
speaker = "イレーナ"
# （げっ、もう見つかった……！）
line = "（げっ、もう見つかった……！）"

[[dialogue]]
speaker = "シャロン"
# 「大聖堂で何をされていたのですか？　お掃除ですか？　説法の練習ですか？　私もお手伝いしますっ」
line = "「大聖堂で何をされていたのですか？　お掃除ですか？　説法の練習ですか？　私もお手伝いしますっ」"

[[dialogue]]
speaker = "イレーナ"
# 「い、いえ、トナカイ──じゃなくて、会長さんと子どもたちへのプレゼントを買いに行く予定を立てていたところでして」
line = "「い、いえ、トナカイ──じゃなくて、会長さんと子どもたちへのプレゼントを買いに行く予定を立てていたところでして」"

[[dialogue]]
speaker = "シャロン"
# 「素晴らしいですっ。ぜひ私もお供させてください！」
line = "「素晴らしいですっ。ぜひ私もお供させてください！」"

[[dialogue]]
speaker = "イレーナ"
# （ぐっ……！　サボらせてもらえない……！）
line = "（ぐっ……！　サボらせてもらえない……！）"
