[[dialogue]]
speaker = "ルネア"
# 「あなたたち、中々やるじゃない！！」
line = "「あなたたち、中々やるじゃない！！」"

[[dialogue]]
speaker = "エグザエル"
# 「ふむ、あれだけ偉そうに登場してあっさり負けるとは……ルネア様、もしや少々太られましたかな？」
line = "「ふむ、あれだけ偉そうに登場してあっさり負けるとは……ルネア様、もしや少々太られましたかな？」"

[[dialogue]]
speaker = "ルネア"
# 「トドメの一撃を入れようったって、そうは行かないわ！」
line = "「トドメの一撃を入れようったって、そうは行かないわ！」"

[[dialogue]]
speaker = "エグザエル"
# 「おっ、フッ！！？」
line = "「おっ、フッ！！？」"

[[dialogue]]
speaker = "ルネア"
# 「女神の奥の手、エグザエルバリアーーーー！！！」
line = "「女神の奥の手、エグザエルバリアーーーー！！！」"

[[dialogue]]
speaker = "エグザエル"
# 「デストロォォーーーーーーーーーィィイ！！？！？」
line = "「デストロォォーーーーーーーーーィィイ！！？！？」"

[[dialogue]]
speaker = "ルネア"
# 「フッ、天使長エグザエルの体は、すべてのビームと攻撃を遮断するわ」
line = "「フッ、天使長エグザエルの体は、すべてのビームと攻撃を遮断するわ」"

[[dialogue]]
speaker = "ヴィーナス"
# 「凄いわ！　全力ビームだったのに無傷よ！！」
line = "「凄いわ！　全力ビームだったのに無傷よ！！」"

[[dialogue]]
speaker = "フィオナ"
# 「ですがキャリーケースは完全にデストロイされているのですが、良かったんでしょうか……」
line = "「ですがキャリーケースは完全にデストロイされているのですが、良かったんでしょうか……」"

[[dialogue]]
speaker = "ルネア"
# 「あれは特別製だもの。すぐに再生するから問題ないわ」
line = "「あれは特別製だもの。すぐに再生するから問題ないわ」"

[[dialogue]]
speaker = "エグザエル"
# 「我が輩の人権もデストロイですぞーーーーーー！！？」
line = "「我が輩の人権もデストロイですぞーーーーーー！！？」"

[[dialogue]]
speaker = "ルネア"
# 「天使長に人権なんてないわ！！　さあ、私のために何度でも砕けなさい！」
line = "「天使長に人権なんてないわ！！　さあ、私のために何度でも砕けなさい！」"
