[[dialogue]]
speaker = "ジュエリー"
# 「どうだい？　私と助手の愛の結晶、血染めのトマトパスタの味は」
line = "「どうだい？　私と助手の愛の結晶、血染めのトマトパスタの味は」"

[[dialogue]]
speaker = "unk"
# 美味しいけどネーミングが物騒！
line = "美味しいけどネーミングが物騒！"

[[dialogue]]
speaker = "ジュエリー"
# 「ふむ、言われてみればそうかもしれない」
line = "「ふむ、言われてみればそうかもしれない」"

[[dialogue]]
speaker = "ジュエリー"
# 「だけど愛する助手のために、不器用なりに頑張らせてもらったよ。……さて、次はイレーナさんの番だ」
line = "「だけど愛する助手のために、不器用なりに頑張らせてもらったよ。……さて、次はイレーナさんの番だ」"

[[dialogue]]
speaker = "イレーナ"
# 「はい。ですがジュエリーさん、いいのですか？」
line = "「はい。ですがジュエリーさん、いいのですか？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ん？」
line = "「ん？」"

[[dialogue]]
speaker = "イレーナ"
# 「あなたにとって会長さんは愛しの存在。それは２人が仲睦まじく料理をしている姿からも見て取れました」
line = "「あなたにとって会長さんは愛しの存在。それは２人が仲睦まじく料理をしている姿からも見て取れました」"

[[dialogue]]
speaker = "イレーナ"
# 「そんな会長さん相手に、ふりとはいえ私が花嫁になるのは、あまりいい気がしないのではありませんか？」
line = "「そんな会長さん相手に、ふりとはいえ私が花嫁になるのは、あまりいい気がしないのではありませんか？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ああ、遠慮することはないよ。今回はやむを得ない事態だし、私は理解のある妻だからね」
line = "「ああ、遠慮することはないよ。今回はやむを得ない事態だし、私は理解のある妻だからね」"

[[dialogue]]
speaker = "ジュエリー"
# 「それに、助手なら最後は私の隣に帰ってきてくれると信じているよ」
line = "「それに、助手なら最後は私の隣に帰ってきてくれると信じているよ」"

[[dialogue]]
speaker = "イレーナ"
# 「そ、そうですか……では──」
line = "「そ、そうですか……では──」"

[[dialogue]]
speaker = "unk"
# ジュエリーに代わって、今度はイレーナがキッチンに立つ。
line = "ジュエリーに代わって、今度はイレーナがキッチンに立つ。"

[[dialogue]]
speaker = "イレーナ"
# （あたしは教皇庁の宿舎で１人暮らししてるし、そこそこのものだったら普通にできちゃうけど……これ、花嫁修業なのよね）
line = "（あたしは教皇庁の宿舎で１人暮らししてるし、そこそこのものだったら普通にできちゃうけど……これ、花嫁修業なのよね）"

[[dialogue]]
speaker = "イレーナ"
# （あたしは花嫁で──いつもみたいな感じじゃなくて──花嫁が愛する旦那に振舞う料理として最適なものは……）
line = "（あたしは花嫁で──いつもみたいな感じじゃなくて──花嫁が愛する旦那に振舞う料理として最適なものは……）"

[[dialogue]]
speaker = "ジュエリー"
# 「悩んでいるようだね。助手に助けてもらわなくていいのかい？」
line = "「悩んでいるようだね。助手に助けてもらわなくていいのかい？」"

[[dialogue]]
speaker = "イレーナ"
# 「大丈夫ですよ。会長さんはソファに座ってゆっくりくつろいでいてください」
line = "「大丈夫ですよ。会長さんはソファに座ってゆっくりくつろいでいてください」"

[[dialogue]]
speaker = "unk"
# イレーナは微笑むと早速料理に取り掛かる。
line = "イレーナは微笑むと早速料理に取り掛かる。"

[[dialogue]]
speaker = "ジュエリー"
# 「慣れた手つきだ。もしかして料理は得意なのかい？」
line = "「慣れた手つきだ。もしかして料理は得意なのかい？」"

[[dialogue]]
speaker = "イレーナ"
# 「得意というほどでもありません。それこそ会長さんの料理の腕には敵わないと思います」
line = "「得意というほどでもありません。それこそ会長さんの料理の腕には敵わないと思います」"

[[dialogue]]
speaker = "イレーナ"
# 「それでも、お口に合うかどうかはわかりませんが頑張って作りますね」
line = "「それでも、お口に合うかどうかはわかりませんが頑張って作りますね」"

[[dialogue]]
speaker = "ジュエリー"
# 「なんとも甲斐甲斐しい新妻だね。夫冥利に尽きるというものじゃないかい？」
line = "「なんとも甲斐甲斐しい新妻だね。夫冥利に尽きるというものじゃないかい？」"

[[dialogue]]
speaker = "イレーナ"
# （……まったく、どうしてあたしがこんなことしなくちゃいけないのかしら）
line = "（……まったく、どうしてあたしがこんなことしなくちゃいけないのかしら）"

[[dialogue]]
speaker = "イレーナ"
# （っと、変なことは考えない方がいいわね。フィオナ会長やトワ先生の例から考えると、花嫁の気持ちも影響するみたいだから）
line = "（っと、変なことは考えない方がいいわね。フィオナ会長やトワ先生の例から考えると、花嫁の気持ちも影響するみたいだから）"

[[dialogue]]
speaker = "イレーナ"
# （あたしは花嫁……愛しの旦那様に美味しい料理を食べてもらいたい……喜んでる顔が見たい、と……）
line = "（あたしは花嫁……愛しの旦那様に美味しい料理を食べてもらいたい……喜んでる顔が見たい、と……）"

[[dialogue]]
speaker = "イレーナ"
# 「お待たせしました。どうぞお召し上がりください」
line = "「お待たせしました。どうぞお召し上がりください」"

[[dialogue]]
speaker = "ジュエリー"
# 「ほう、ティラミスか。食後のデザートというわけだね。これは美味しそうだ」
line = "「ほう、ティラミスか。食後のデザートというわけだね。これは美味しそうだ」"

[[dialogue]]
speaker = "unk"
# いただきます！
line = "いただきます！"

[[dialogue]]
speaker = "イレーナ"
# 「……お味の方は、いかがでしょうか？」
line = "「……お味の方は、いかがでしょうか？」"

[[dialogue]]
speaker = "unk"
# すごく美味しい！
line = "すごく美味しい！"

[[dialogue]]
speaker = "イレーナ"
# 「ふふ、それなら良かったです」
line = "「ふふ、それなら良かったです」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふむ……」
line = "「ふむ……」"

[[dialogue]]
speaker = "イレーナ"
# 「……どうかなさいましたか？」
line = "「……どうかなさいましたか？」"

[[dialogue]]
speaker = "ジュエリー"
# 「なぜイレーナさんは立ったままなのか、と思ってね。せっかくだから助手の隣に座ればいいのに」
line = "「なぜイレーナさんは立ったままなのか、と思ってね。せっかくだから助手の隣に座ればいいのに」"

[[dialogue]]
speaker = "イレーナ"
# 「えっ……！？」
line = "「えっ……！？」"

[[dialogue]]
speaker = "ジュエリー"
# 「先ほども言ったが私に遠慮することはない。何なら助手にあーんして食べさせてあげればいい」
line = "「先ほども言ったが私に遠慮することはない。何なら助手にあーんして食べさせてあげればいい」"

[[dialogue]]
speaker = "イレーナ"
# （ちょ、何言い出すのよこの子！？）
line = "（ちょ、何言い出すのよこの子！？）"

[[dialogue]]
speaker = "ジュエリー"
# 「そういったことも花嫁修業の一環だと私は思うよ。愛しの助手よ、キミもそう思うだろう？」
line = "「そういったことも花嫁修業の一環だと私は思うよ。愛しの助手よ、キミもそう思うだろう？」"

[[dialogue]]
speaker = "unk"
# え、ええと……
line = "え、ええと……"

[[dialogue]]
speaker = "イレーナ"
# （ちょっと、そこであんたが照れたら余計に意識しちゃうじゃない！）
line = "（ちょっと、そこであんたが照れたら余計に意識しちゃうじゃない！）"

[[dialogue]]
speaker = "イレーナ"
# （でも、そうなのよね……これは花嫁修業……ウェディングフォームを解除するために、そういう事も必要なのかもしれないわ……）
line = "（でも、そうなのよね……これは花嫁修業……ウェディングフォームを解除するために、そういう事も必要なのかもしれないわ……）"

[[dialogue]]
speaker = "イレーナ"
# 「で、ではどうぞ……あーん」
line = "「で、ではどうぞ……あーん」"

[[dialogue]]
speaker = "イレーナ"
# 「……ど、どうですか？」
line = "「……ど、どうですか？」"

[[dialogue]]
speaker = "ジュエリー"
# 「うーん、やはり表情が硬いね……」
line = "「うーん、やはり表情が硬いね……」"

[[dialogue]]
speaker = "イレーナ"
# 「そうですか……やはり急に花嫁修業といっても、なかなかうまくいきませんね……」
line = "「そうですか……やはり急に花嫁修業といっても、なかなかうまくいきませんね……」"

[[dialogue]]
speaker = "unk"
# ２人の作ってくれた食事を食べ終わり、花嫁修業は一旦休憩。
line = "２人の作ってくれた食事を食べ終わり、花嫁修業は一旦休憩。"

[[dialogue]]
speaker = "unk"
# 今はジュエリーが紅茶を淹れてくれている。
line = "今はジュエリーが紅茶を淹れてくれている。"

[[dialogue]]
speaker = "イレーナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "unk"
# どうしたの？
line = "どうしたの？"

[[dialogue]]
speaker = "イレーナ"
# 「ちょっと、ね……あたし、あの子ちょっと苦手かもしれないわ……」
line = "「ちょっと、ね……あたし、あの子ちょっと苦手かもしれないわ……」"

[[dialogue]]
speaker = "イレーナ"
# 「何だかね……油断するとあたしの本性を見抜いてきそうな、そんな気がするのよ」
line = "「何だかね……油断するとあたしの本性を見抜いてきそうな、そんな気がするのよ」"

[[dialogue]]
speaker = "unk"
# 見抜かれてもいいと思うけど……
line = "見抜かれてもいいと思うけど……"

[[dialogue]]
speaker = "unk"
# ジュエリーは名探偵だからなあ
line = "ジュエリーは名探偵だからなあ"

[[dialogue]]
speaker = "イレーナ"
# 「そうなったらいよいよ結婚なんてできないわね」
line = "「そうなったらいよいよ結婚なんてできないわね」"

[[dialogue]]
speaker = "イレーナ"
# 「だってそうでしょう？　本当のあたしはこんな感じだから」
line = "「だってそうでしょう？　本当のあたしはこんな感じだから」"

[[dialogue]]
speaker = "イレーナ"
# 「みんなが知ってるのは聖女のあたし。聖女じゃないあたしと結婚したいやつなんていないわよ」
line = "「みんなが知ってるのは聖女のあたし。聖女じゃないあたしと結婚したいやつなんていないわよ」"

[[dialogue]]
speaker = "unk"
# そんなことは──
line = "そんなことは──"

[[dialogue]]
speaker = "ジュエリー"
# 「そんな神妙な顔をして、何を話していたんだい？」
line = "「そんな神妙な顔をして、何を話していたんだい？」"

[[dialogue]]
speaker = "イレーナ"
# 「い、いえ……何でもありませんよ」
line = "「い、いえ……何でもありませんよ」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふむ……」
line = "「ふむ……」"

[[dialogue]]
speaker = "ジュエリー"
# 「イレーナさん、私は以前からキミに疑問を持っていたんだ」
line = "「イレーナさん、私は以前からキミに疑問を持っていたんだ」"

[[dialogue]]
speaker = "イレーナ"
# 「疑問……？　どういうことでしょう？」
line = "「疑問……？　どういうことでしょう？」"

[[dialogue]]
speaker = "ジュエリー"
# 「キミは慈しみ深く、誰に対しても優しい、完璧な聖女だと思われている」
line = "「キミは慈しみ深く、誰に対しても優しい、完璧な聖女だと思われている」"

[[dialogue]]
speaker = "ジュエリー"
# 「だがキミには、まだ人に見せていない意外な一面があるんじゃないかと思っていてね」
line = "「だがキミには、まだ人に見せていない意外な一面があるんじゃないかと思っていてね」"

[[dialogue]]
speaker = "ジュエリー"
# 「キミの花嫁修業の様子をずっと見させてもらっていたのだけど……どうにもぎこちなさを感じてならないんだ」
line = "「キミの花嫁修業の様子をずっと見させてもらっていたのだけど……どうにもぎこちなさを感じてならないんだ」"

[[dialogue]]
speaker = "ジュエリー"
# 「結婚とは互いの真実をさらけ出すもの」
line = "「結婚とは互いの真実をさらけ出すもの」"

[[dialogue]]
speaker = "ジュエリー"
# 「キミにウェディングフォームが発現したのも何かの因果を感じてならない。どうだろう、これを機会に自分を解き放ってみては？」
line = "「キミにウェディングフォームが発現したのも何かの因果を感じてならない。どうだろう、これを機会に自分を解き放ってみては？」"

[[dialogue]]
speaker = "イレーナ"
# 「私は……流星教の神官として、真摯に教えを守っているだけです」
line = "「私は……流星教の神官として、真摯に教えを守っているだけです」"

[[dialogue]]
speaker = "イレーナ"
# 「ジュエリーさんの思っているような素顔などありません。私の素顔と言うなら、今お見せしている私が素顔の私ですよ」
line = "「ジュエリーさんの思っているような素顔などありません。私の素顔と言うなら、今お見せしている私が素顔の私ですよ」"

[[dialogue]]
speaker = "ジュエリー"
# 「そうか……」
line = "「そうか……」"

[[dialogue]]
speaker = "ジュエリー"
# 「ではイレーナさん。キミに花婿をかけて勝負を申し込む！」
line = "「ではイレーナさん。キミに花婿をかけて勝負を申し込む！」"

[[dialogue]]
speaker = "イレーナ"
# 「ええっ！？」
line = "「ええっ！？」"
