[[dialogue]]
speaker = "unk"
# ウェディングフォームが発現した２人には、いつも通り（？）俺の家で花嫁修業をしてもらうことになった。
line = "ウェディングフォームが発現した２人には、いつも通り（？）俺の家で花嫁修業をしてもらうことになった。"

[[dialogue]]
speaker = "ジュエリー"
# 「では私から花嫁修業をさせてもらおうかな」
line = "「では私から花嫁修業をさせてもらおうかな」"

[[dialogue]]
speaker = "イレーナ"
# 「ちなみにジュエリーさんはどのくらい家事の心得があるのですか？」
line = "「ちなみにジュエリーさんはどのくらい家事の心得があるのですか？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふふ、それはもちろん──」
line = "「ふふ、それはもちろん──」"

[[dialogue]]
speaker = "ジュエリー"
# 「からきしだ」
line = "「からきしだ」"

[[dialogue]]
speaker = "イレーナ"
# 「堂々と言うことではないと思いますが……」
line = "「堂々と言うことではないと思いますが……」"

[[dialogue]]
speaker = "ジュエリー"
# 「隠しても仕方がないことだからね。でもだからこそ、花嫁修業のし甲斐がある」
line = "「隠しても仕方がないことだからね。でもだからこそ、花嫁修業のし甲斐がある」"

[[dialogue]]
speaker = "ジュエリー"
# 「さあ、我が助手よ。私が一人前の花嫁になれるよう導いてくれたまえ」
line = "「さあ、我が助手よ。私が一人前の花嫁になれるよう導いてくれたまえ」"

[[dialogue]]
speaker = "unk"
# 一緒に頑張ろう
line = "一緒に頑張ろう"

[[dialogue]]
speaker = "unk"
# 任せて
line = "任せて"

[[dialogue]]
speaker = "ジュエリー"
# 「それにしても、まさか以前の約束がこんな形で果たされることになるとはね」
line = "「それにしても、まさか以前の約束がこんな形で果たされることになるとはね」"

[[dialogue]]
speaker = "イレーナ"
# 「何か約束をされていたのですか？」
line = "「何か約束をされていたのですか？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ああ。私が料理に挑戦して失敗してしまった時、次は助手がいろいろ教えてくれると約束したのだよ」
line = "「ああ。私が料理に挑戦して失敗してしまった時、次は助手がいろいろ教えてくれると約束したのだよ」"

[[dialogue]]
speaker = "ジュエリー"
# 「旦那様が花嫁に料理を教える、そんな家庭があってもいいだろう？」
line = "「旦那様が花嫁に料理を教える、そんな家庭があってもいいだろう？」"

[[dialogue]]
speaker = "ジュエリー"
# 「というわけで、まずお鍋を選ぶとしよう。どのお鍋を使うべきだろうか？　私としてはあの大きな鍋が怪しいと思っているんだが」
line = "「というわけで、まずお鍋を選ぶとしよう。どのお鍋を使うべきだろうか？　私としてはあの大きな鍋が怪しいと思っているんだが」"

[[dialogue]]
speaker = "unk"
# その前に何を作るのかを決めないと
line = "その前に何を作るのかを決めないと"

[[dialogue]]
speaker = "ジュエリー"
# 「おっと、そうだったね。ならばトマト料理がいいな。うん、そうしよう」
line = "「おっと、そうだったね。ならばトマト料理がいいな。うん、そうしよう」"

[[dialogue]]
speaker = "ジュエリー"
# 「何を隠そう私はトマト料理が好物だからね。苦手という人もいるが、あの若干の酸味を含んだ独特の味がたまらない」
line = "「何を隠そう私はトマト料理が好物だからね。苦手という人もいるが、あの若干の酸味を含んだ独特の味がたまらない」"

[[dialogue]]
speaker = "ジュエリー"
# 「パスタのソースにしてもよし、パンに挟んでサンドイッチにしてもよし。もちろん生でがぶりといくのも良いね」
line = "「パスタのソースにしてもよし、パンに挟んでサンドイッチにしてもよし。もちろん生でがぶりといくのも良いね」"

[[dialogue]]
speaker = "ジュエリー"
# 「よし、決めた。イタリア出身のイレーナさんの前で僭越ではあるが、定番のトマトパスタにしよう」
line = "「よし、決めた。イタリア出身のイレーナさんの前で僭越ではあるが、定番のトマトパスタにしよう」"

[[dialogue]]
speaker = "ジュエリー"
# 「そうと決まればトマトだ。我が助手よ、トマトを用意してくれたまえ」
line = "「そうと決まればトマトだ。我が助手よ、トマトを用意してくれたまえ」"

[[dialogue]]
speaker = "unk"
# 冷蔵庫の野菜室からトマトを取り出すと、それをジュエリーに渡す。
line = "冷蔵庫の野菜室からトマトを取り出すと、それをジュエリーに渡す。"

[[dialogue]]
speaker = "ジュエリー"
# 「まずは切るところからだね。私の包丁さばきを見ていてくれ」
line = "「まずは切るところからだね。私の包丁さばきを見ていてくれ」"

[[dialogue]]
speaker = "unk"
# 日傘を差したままで大丈夫？
line = "日傘を差したままで大丈夫？"

[[dialogue]]
speaker = "イレーナ"
# 「そもそも、どうしてジュエリーさんは屋内なのに日傘を差しているのでしょう……？」
line = "「そもそも、どうしてジュエリーさんは屋内なのに日傘を差しているのでしょう……？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふふ、過去に苦い経験をしたことがあってね。それ以来、屋内であっても常に日傘を差すようにしているんだ」
line = "「ふふ、過去に苦い経験をしたことがあってね。それ以来、屋内であっても常に日傘を差すようにしているんだ」"

[[dialogue]]
speaker = "unk"
# ジュエリーは日傘を差したまま、包丁を握って刃をトマトに押し当てた。
line = "ジュエリーは日傘を差したまま、包丁を握って刃をトマトに押し当てた。"

[[dialogue]]
speaker = "unk"
# ザシュッ！！！！！
line = "ザシュッ！！！！！"

[[dialogue]]
speaker = "ジュエリー"
# 「あ、指を切ってしまった」
line = "「あ、指を切ってしまった」"

[[dialogue]]
speaker = "unk"
# ちょっ……！？
line = "ちょっ……！？"

[[dialogue]]
speaker = "イレーナ"
# 「見せてください、治療します！」
line = "「見せてください、治療します！」"

[[dialogue]]
speaker = "ジュエリー"
# 「ありがとう。イレーナさんが居てくれるなら、何度指を切っても大丈夫そうだ」
line = "「ありがとう。イレーナさんが居てくれるなら、何度指を切っても大丈夫そうだ」"

[[dialogue]]
speaker = "unk"
# 野菜を切るのは俺がやろうか？
line = "野菜を切るのは俺がやろうか？"

[[dialogue]]
speaker = "ジュエリー"
# 「しかしそれでは花嫁修業にならないのではないかな？」
line = "「しかしそれでは花嫁修業にならないのではないかな？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふむ、良いことを思いついたよ。助手、私を後ろから抱きしめてくれ」
line = "「ふむ、良いことを思いついたよ。助手、私を後ろから抱きしめてくれ」"

[[dialogue]]
speaker = "unk"
# え……？
line = "え……？"

[[dialogue]]
speaker = "ジュエリー"
# 「ふふ、何を勘違い……いや、期待したのかな？　違うよ、我が助手」
line = "「ふふ、何を勘違い……いや、期待したのかな？　違うよ、我が助手」"

[[dialogue]]
speaker = "ジュエリー"
# 「後ろから抱きしめるようにして、一緒に包丁を握るんだ。助手と一緒なら包丁を扱うコツも掴めるというものだろう」
line = "「後ろから抱きしめるようにして、一緒に包丁を握るんだ。助手と一緒なら包丁を扱うコツも掴めるというものだろう」"

[[dialogue]]
speaker = "ジュエリー"
# 「何を恥ずかしがっているんだい？　私たちは夫婦なのだから、この程度で照れる必要はないだろう」
line = "「何を恥ずかしがっているんだい？　私たちは夫婦なのだから、この程度で照れる必要はないだろう」"

[[dialogue]]
speaker = "unk"
# 夫として提案に乗り、ジュエリーの背中に身体を密着させる。
line = "夫として提案に乗り、ジュエリーの背中に身体を密着させる。"

[[dialogue]]
speaker = "unk"
# 左手を重ねるようにしてトマトを、右手で包み込むようにして包丁を握る。
line = "左手を重ねるようにしてトマトを、右手で包み込むようにして包丁を握る。"

[[dialogue]]
speaker = "unk"
# 日傘は……ジュエリーとの身体の間に挟み込んで、何とかした。
line = "日傘は……ジュエリーとの身体の間に挟み込んで、何とかした。"

[[dialogue]]
speaker = "イレーナ"
# （なんか無茶苦茶なことになってるけど……花嫁修業ってこんな感じでいいのかしら？）
line = "（なんか無茶苦茶なことになってるけど……花嫁修業ってこんな感じでいいのかしら？）"

[[dialogue]]
speaker = "イレーナ"
# （でも……）
line = "（でも……）"

[[dialogue]]
speaker = "ジュエリー"
# 「だんだん包丁の扱い方が掴めてきたよ。私と助手の愛のパスタの完成はもう間近ということだね」
line = "「だんだん包丁の扱い方が掴めてきたよ。私と助手の愛のパスタの完成はもう間近ということだね」"

[[dialogue]]
speaker = "unk"
# まだ野菜を切っただけだから
line = "まだ野菜を切っただけだから"

[[dialogue]]
speaker = "ジュエリー"
# 「おっと、そうだった。次はどうすればいいんだい？」
line = "「おっと、そうだった。次はどうすればいいんだい？」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふむふむ……生トマトをソースに使う場合は、オリーブオイルで炒めてから、ふたをして少し煮込むと。それなら煮込んでいる間にパスタを茹でれば無駄がないね」
line = "「ふむふむ……生トマトをソースに使う場合は、オリーブオイルで炒めてから、ふたをして少し煮込むと。それなら煮込んでいる間にパスタを茹でれば無駄がないね」"

[[dialogue]]
speaker = "ジュエリー"
# 「あっ、くすぐったいよ、助手。密着しているんだから、動いたら当たってしまうじゃないか」
line = "「あっ、くすぐったいよ、助手。密着しているんだから、動いたら当たってしまうじゃないか」"

[[dialogue]]
speaker = "ジュエリー"
# 「そういうのは食事の後で……な？」
line = "「そういうのは食事の後で……な？」"

[[dialogue]]
speaker = "イレーナ"
# （いやちょっと、料理作るだけにしてはイチャイチャしすぎじゃない？）
line = "（いやちょっと、料理作るだけにしてはイチャイチャしすぎじゃない？）"

[[dialogue]]
speaker = "ジュエリー"
# 「あ……ソースができたようだ。味見してみてくれ。あ～ん」
line = "「あ……ソースができたようだ。味見してみてくれ。あ～ん」"

[[dialogue]]
speaker = "ジュエリー"
# 「ふむふむ……もっと煮詰めた方が好み？　ふむ、なるほど。それはいいことを聞いた」
line = "「ふむふむ……もっと煮詰めた方が好み？　ふむ、なるほど。それはいいことを聞いた」"

[[dialogue]]
speaker = "ジュエリー"
# 「パスタも茹で上がるまでもう少しかな。楽しみに待っていてくれ」
line = "「パスタも茹で上がるまでもう少しかな。楽しみに待っていてくれ」"

[[dialogue]]
speaker = "イレーナ"
# （２人、すごく仲がいいじゃない……。失敗しても笑い合って、楽しそうで、夫婦ってこんな感じなの……？）
line = "（２人、すごく仲がいいじゃない……。失敗しても笑い合って、楽しそうで、夫婦ってこんな感じなの……？）"

[[dialogue]]
speaker = "イレーナ"
# （あたしには、無理……あんなふうにはできないわ……）
line = "（あたしには、無理……あんなふうにはできないわ……）"

[[dialogue]]
speaker = "イレーナ"
# （だってあたしが素直に振るまっても、全然可愛くないし……好きになってくれるはずないし……）
line = "（だってあたしが素直に振るまっても、全然可愛くないし……好きになってくれるはずないし……）"

[[dialogue]]
speaker = "イレーナ"
# （どうせあたしなんて……）
line = "（どうせあたしなんて……）"
