[[dialogue]]
speaker = "蘭美"
# 「いい！？　料理が下手な人に限って、隠し味だの何だの言って、自分の好きな味付けをしたがるけど、私から言わせれば――」
line = "「いい！？　料理が下手な人に限って、隠し味だの何だの言って、自分の好きな味付けをしたがるけど、私から言わせれば――」"

[[dialogue]]
speaker = "蘭美"
# 「レシピを馬鹿にしてんのか、って感じよ！」
line = "「レシピを馬鹿にしてんのか、って感じよ！」"

[[dialogue]]
speaker = "蘭美"
# 「レシピは料理の説明書！　その料理を美味しく作れる人が、作り方を分かりやすく示してくれたものよ！」
line = "「レシピは料理の説明書！　その料理を美味しく作れる人が、作り方を分かりやすく示してくれたものよ！」"

[[dialogue]]
speaker = "蘭美"
# 「せつな、貴方にも最速で伝わるように言ってあげるわ！　さっきあなたが、忍者の里の秘伝だっていった特製ドリンクがあったわよね？」
line = "「せつな、貴方にも最速で伝わるように言ってあげるわ！　さっきあなたが、忍者の里の秘伝だっていった特製ドリンクがあったわよね？」"

[[dialogue]]
speaker = "せつな"
# 「は、はいでござる」
line = "「は、はいでござる」"

[[dialogue]]
speaker = "蘭美"
# 「あなたはそれをチョコに入れようとしたけど、逆に聞くわ。なんでそのドリンクにチョコを入れないの？　甘くて飲みやすくなるじゃない」
line = "「あなたはそれをチョコに入れようとしたけど、逆に聞くわ。なんでそのドリンクにチョコを入れないの？　甘くて飲みやすくなるじゃない」"

[[dialogue]]
speaker = "せつな"
# 「え？　それは……古くより受け継がれてきた秘伝で……」
line = "「え？　それは……古くより受け継がれてきた秘伝で……」"

[[dialogue]]
speaker = "蘭美"
# 「それはつまり、特製ドリンクのレシピってことよね？」
line = "「それはつまり、特製ドリンクのレシピってことよね？」"

[[dialogue]]
speaker = "せつな"
# 「あ……！」
line = "「あ……！」"

[[dialogue]]
speaker = "蘭美"
# 「気づいたかしら？　せつな、あなたがチョコに特製ドリンクを入れるってことは、チョコを美味しく作る為の秘伝を崩そうとする行為なのよ！」
line = "「気づいたかしら？　せつな、あなたがチョコに特製ドリンクを入れるってことは、チョコを美味しく作る為の秘伝を崩そうとする行為なのよ！」"

[[dialogue]]
speaker = "蘭美"
# 「だから、せつな。今後、料理が上手くなりたいなら心に刻んでおきさない」
line = "「だから、せつな。今後、料理が上手くなりたいなら心に刻んでおきさない」"

[[dialogue]]
speaker = "蘭美"
# 「――レシピを守って、丁寧に料理を作りなさい。あなたが師匠の教えを守って、忍者になったのと同じように」
line = "「――レシピを守って、丁寧に料理を作りなさい。あなたが師匠の教えを守って、忍者になったのと同じように」"

[[dialogue]]
speaker = "せつな"
# 「……！　はい！　せつな、これからはちゃんとレシピ通りに料理を作るでござる！」
line = "「……！　はい！　せつな、これからはちゃんとレシピ通りに料理を作るでござる！」"

[[dialogue]]
speaker = "蘭美"
# 「それが分かったのなら、あとは私の教える通りに作れば、バッチリよ！」
line = "「それが分かったのなら、あとは私の教える通りに作れば、バッチリよ！」"

[[dialogue]]
speaker = "unk"
# そこからせつなは、蘭美の教える通り、丁寧に調理を進めていく。
line = "そこからせつなは、蘭美の教える通り、丁寧に調理を進めていく。"

[[dialogue]]
speaker = "蘭美"
# 「うん、いいわね。忍者だけあって、せつなは手先が器用ね。やればできるじゃない！」
line = "「うん、いいわね。忍者だけあって、せつなは手先が器用ね。やればできるじゃない！」"

[[dialogue]]
speaker = "せつな"
# 「えへへぇ♪　お褒め頂き光栄にござる！」
line = "「えへへぇ♪　お褒め頂き光栄にござる！」"

[[dialogue]]
speaker = "せつな"
# 「しかし、蘭美殿の料理の腕前はさすがでござるな！　速いのに丁寧で、実に美しい所作で、思わず感嘆のため息がもれてしまうでござる」
line = "「しかし、蘭美殿の料理の腕前はさすがでござるな！　速いのに丁寧で、実に美しい所作で、思わず感嘆のため息がもれてしまうでござる」"

[[dialogue]]
speaker = "蘭美"
# 「ふふんっ♪　カッコいいでしょ？　最速の美とはこういうことよ」
line = "「ふふんっ♪　カッコいいでしょ？　最速の美とはこういうことよ」"

[[dialogue]]
speaker = "せつな"
# 「蘭美殿。せつな、前から聞きたかったのでござるが……」
line = "「蘭美殿。せつな、前から聞きたかったのでござるが……」"

[[dialogue]]
speaker = "蘭美"
# 「うん？　なにかしら？」
line = "「うん？　なにかしら？」"

[[dialogue]]
speaker = "せつな"
# 「蘭美殿がメイドをカッコいいと思うようになったきっかけとかって、なにかあるのでござるか？」
line = "「蘭美殿がメイドをカッコいいと思うようになったきっかけとかって、なにかあるのでござるか？」"

[[dialogue]]
speaker = "蘭美"
# 「きっかけ？」
line = "「きっかけ？」"

[[dialogue]]
speaker = "せつな"
# 「その……蘭美殿は、魔界の地方を治める貴族の令嬢でござろう？」
line = "「その……蘭美殿は、魔界の地方を治める貴族の令嬢でござろう？」"

[[dialogue]]
speaker = "せつな"
# 「そんな方が世界一のメイドを目指そうと思うには、なにか強いきっかけがあったのではないかと思ったのでござる」
line = "「そんな方が世界一のメイドを目指そうと思うには、なにか強いきっかけがあったのではないかと思ったのでござる」"

[[dialogue]]
speaker = "蘭美"
# 「ええ、そうね。よくある話よ」
line = "「ええ、そうね。よくある話よ」"

[[dialogue]]
speaker = "蘭美"
# 「私が小さかった頃に、実家の屋敷へとある人間の女性がやってきたの」
line = "「私が小さかった頃に、実家の屋敷へとある人間の女性がやってきたの」"

[[dialogue]]
speaker = "蘭美"
# 「お母様が流星学園に通っていた頃の親友でね。老齢で引退することになった実家の前メイド長の後任として、迎え入れたのよ」
line = "「お母様が流星学園に通っていた頃の親友でね。老齢で引退することになった実家の前メイド長の後任として、迎え入れたのよ」"

[[dialogue]]
speaker = "蘭美"
# 「その人――新しいメイド長はもう、やること為すこと、とにかく美しくてカッコいい淑女だったわ。それでいて、星騎士としても強かったの」
line = "「その人――新しいメイド長はもう、やること為すこと、とにかく美しくてカッコいい淑女だったわ。それでいて、星騎士としても強かったの」"

[[dialogue]]
speaker = "蘭美"
# 「私はそんな彼女に、見惚れて、憧れてしまった。彼女の経歴を聞いて、納得したわ」
line = "「私はそんな彼女に、見惚れて、憧れてしまった。彼女の経歴を聞いて、納得したわ」"

[[dialogue]]
speaker = "蘭美"
# 「その人は昔、メイド・オブ・メイドで３回連続優勝を果たし、殿堂入りを果たした――」
line = "「その人は昔、メイド・オブ・メイドで３回連続優勝を果たし、殿堂入りを果たした――」"

[[dialogue]]
speaker = "蘭美"
# 「『マスターメイド』の称号を持つ、正真正銘、世界最高のメイドだったのよ」
line = "「『マスターメイド』の称号を持つ、正真正銘、世界最高のメイドだったのよ」"

[[dialogue]]
speaker = "蘭美"
# 「そのカッコよさに惹かれて、私は弟子入り志願をしたわ。両親は最初、驚いて反対したりもしたけれど――」
line = "「そのカッコよさに惹かれて、私は弟子入り志願をしたわ。両親は最初、驚いて反対したりもしたけれど――」"

[[dialogue]]
speaker = "蘭美"
# 「私の心はメイドへの憧れで燃え上がって、決して冷めることはなかった。それは、今でもね」
line = "「私の心はメイドへの憧れで燃え上がって、決して冷めることはなかった。それは、今でもね」"

[[dialogue]]
speaker = "蘭美"
# 「あとは、知っての通り。その人の指導で天才的な才能を開花させた私は、最速でメイドロードを駆け上がり、メイド・オブ・メイドで世界２位まで登り詰めて――」
line = "「あとは、知っての通り。その人の指導で天才的な才能を開花させた私は、最速でメイドロードを駆け上がり、メイド・オブ・メイドで世界２位まで登り詰めて――」"

[[dialogue]]
speaker = "蘭美"
# 「こうして、九浄家の最年少メイド長に抜擢されて、今に至るというわけ」
line = "「こうして、九浄家の最年少メイド長に抜擢されて、今に至るというわけ」"

[[dialogue]]
speaker = "せつな"
# 「蘭美殿にも、師匠がいたのでござるな！」
line = "「蘭美殿にも、師匠がいたのでござるな！」"

[[dialogue]]
speaker = "蘭美"
# 「ええ。私にとって、いつか乗り越えるべき、最強にして最高にカッコいいラスボスがね♪」
line = "「ええ。私にとって、いつか乗り越えるべき、最強にして最高にカッコいいラスボスがね♪」"

[[dialogue]]
speaker = "蘭美"
# 「まあ、その前に私は、今の世界１位に勝たなければいけないわけだけど――」
line = "「まあ、その前に私は、今の世界１位に勝たなければいけないわけだけど――」"

[[dialogue]]
speaker = "unk"
# それから蘭美の指導により、チョコが出来上がった。
line = "それから蘭美の指導により、チョコが出来上がった。"

[[dialogue]]
speaker = "せつな"
# 「冷蔵庫に入れて、１時間以上経ったでござる！」
line = "「冷蔵庫に入れて、１時間以上経ったでござる！」"

[[dialogue]]
speaker = "蘭美"
# 「じゃあ、仕上がりを確認してみるわよ」
line = "「じゃあ、仕上がりを確認してみるわよ」"

[[dialogue]]
speaker = "せつな"
# 「御意！」
line = "「御意！」"

[[dialogue]]
speaker = "unk"
# せつながチョコの入った型を、冷蔵庫から取ってくる。
line = "せつながチョコの入った型を、冷蔵庫から取ってくる。"

[[dialogue]]
speaker = "せつな"
# 「蘭美殿、綺麗に固まっているでござるよ！　このチョコを型から外せば完成でござるな！」
line = "「蘭美殿、綺麗に固まっているでござるよ！　このチョコを型から外せば完成でござるな！」"

[[dialogue]]
speaker = "蘭美"
# 「ん？　せつな、チョコレートがなんか光って――」
line = "「ん？　せつな、チョコレートがなんか光って――」"

[[dialogue]]
speaker = "せつな"
# 「え？　こ、これはまさか――！？」
line = "「え？　こ、これはまさか――！？」"

[[dialogue]]
speaker = "unk"
# 瞬間、厨房が白い光に包まれる。やがて、その光が収まると――
line = "瞬間、厨房が白い光に包まれる。やがて、その光が収まると――"

[[dialogue]]
speaker = "ゴーレム"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "蘭美"
# 「な……！」
line = "「な……！」"

[[dialogue]]
speaker = "せつな"
# 「で、デジャヴでござるぅぅぅーーーーーーーーーっ！！！」
line = "「で、デジャヴでござるぅぅぅーーーーーーーーーっ！！！」"

[[dialogue]]
speaker = "蘭美"
# 「なんでそうなるぴょんッ！！？」
line = "「なんでそうなるぴょんッ！！？」"

[[dialogue]]
speaker = "unk"
# 思わずツッコんでしまう蘭美なのだった。
line = "思わずツッコんでしまう蘭美なのだった。"
