[[dialogue]]
speaker = "水着フワッチ"
# 「イーーーーッ！」
line = "「イーーーーッ！」"

[[dialogue]]
speaker = "梨緒"
# 「いたぞ、モンスターだ！」
line = "「いたぞ、モンスターだ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「ふぅ。昨日あれだけ意気込んでたのに、雑魚狩りから始めるんだね」
line = "「ふぅ。昨日あれだけ意気込んでたのに、雑魚狩りから始めるんだね」"

[[dialogue]]
speaker = "梨緒"
# 「当然だ。念には念を入れて、もう少しレベルアップしてからボスモンスターに挑みたい」
line = "「当然だ。念には念を入れて、もう少しレベルアップしてからボスモンスターに挑みたい」"

[[dialogue]]
speaker = "ベアトリス"
# 「ふふ、梨緒ちゃんらしいね」
line = "「ふふ、梨緒ちゃんらしいね」"

[[dialogue]]
speaker = "アポロ"
# 「ま、肩慣らしにはちょーどいいか！」
line = "「ま、肩慣らしにはちょーどいいか！」"

[[dialogue]]
speaker = "水着フワッチ"
# 「イィーーーッ！！」
line = "「イィーーーッ！！」"

[[dialogue]]
speaker = "梨緒"
# 「さぁ、蹴散らすぞ！」
line = "「さぁ、蹴散らすぞ！」"

[[dialogue]]
speaker = "水着フワッチ"
# 「イィ～～ッ！　イイィィッ！！」
line = "「イィ～～ッ！　イイィィッ！！」"

[[dialogue]]
speaker = "梨緒"
# 「……今の攻撃が効いていない？」
line = "「……今の攻撃が効いていない？」"

[[dialogue]]
speaker = "ナターシャ"
# 「もしかしてこいつら、強くなってないっ？」
line = "「もしかしてこいつら、強くなってないっ？」"

[[dialogue]]
speaker = "ベアトリス"
# 「う、うんっ。昨日最後に戦った時は、もっと普通に倒せたもんっ」
line = "「う、うんっ。昨日最後に戦った時は、もっと普通に倒せたもんっ」"

[[dialogue]]
speaker = "アポロ"
# 「喋ってる場合じゃないぞっ！　本気でかからないとヤバいっ！」
line = "「喋ってる場合じゃないぞっ！　本気でかからないとヤバいっ！」"

[[dialogue]]
speaker = "梨緒"
# 「ああっ、全力で一気に片を付けようっ！！」
line = "「ああっ、全力で一気に片を付けようっ！！」"

[[dialogue]]
speaker = "水着フワッチ"
# 「イィィッッ～～…………！！？」
line = "「イィィッッ～～…………！！？」"

[[dialogue]]
speaker = "アポロ"
# 「ふー、危ねーところだったな……」
line = "「ふー、危ねーところだったな……」"

[[dialogue]]
speaker = "梨緒"
# 「まさか日ごとに敵が強くなっていく仕様なのか？」
line = "「まさか日ごとに敵が強くなっていく仕様なのか？」"

[[dialogue]]
speaker = "ナターシャ"
# 「だとしても上がり幅が異常でしょ……。調整ミスってるって」
line = "「だとしても上がり幅が異常でしょ……。調整ミスってるって」"

[[dialogue]]
speaker = "ベアトリス"
# 「ちまちまモンスターを倒してる場合じゃないかも……。ボスもこの調子で強くなっているとしたら……」
line = "「ちまちまモンスターを倒してる場合じゃないかも……。ボスもこの調子で強くなっているとしたら……」"

[[dialogue]]
speaker = "梨緒"
# 「明日になればとても手が付けられなくなりそうだな……。今日中に倒さねば、敗北は必至だ」
line = "「明日になればとても手が付けられなくなりそうだな……。今日中に倒さねば、敗北は必至だ」"

[[dialogue]]
speaker = "梨緒"
# 「レベル上げは、ボスモンスターを探しながらにしよう！　早急にボスを探し出した方がいいっ！」
line = "「レベル上げは、ボスモンスターを探しながらにしよう！　早急にボスを探し出した方がいいっ！」"

[[dialogue]]
speaker = "スクアルス"
# 「ギィィィーーーー！」
line = "「ギィィィーーーー！」"

[[dialogue]]
speaker = "梨緒"
# 「見つけたぞ、あそこだっ」
line = "「見つけたぞ、あそこだっ」"

[[dialogue]]
speaker = "ベアトリス"
# 「気配でわかるよ。やっぱり昨日よりずっと強くなってる」
line = "「気配でわかるよ。やっぱり昨日よりずっと強くなってる」"

[[dialogue]]
speaker = "ナターシャ"
# 「道中でそこそこレベルも上げたつもりだったのに……。これ、まだまだレベリング足りてなくない？」
line = "「道中でそこそこレベルも上げたつもりだったのに……。これ、まだまだレベリング足りてなくない？」"

[[dialogue]]
speaker = "アポロ"
# 「ここまで来たらレベルなんて見せかけだぜっ！　足りないレベルはチームワークと根性で補えばいいっ！」
line = "「ここまで来たらレベルなんて見せかけだぜっ！　足りないレベルはチームワークと根性で補えばいいっ！」"

[[dialogue]]
speaker = "梨緒"
# 「アポロの言う通りだ。私たちだって昨日とは違う」
line = "「アポロの言う通りだ。私たちだって昨日とは違う」"

[[dialogue]]
speaker = "ベアトリス"
# 「そうだね。水着フォームの力も使い慣れてきたし……！」
line = "「そうだね。水着フォームの力も使い慣れてきたし……！」"

[[dialogue]]
speaker = "ナターシャ"
# 「ま、修行の集大成って感じで挑んでみますか。ただ遊んでたわけじゃないってとこ、見せてあげるよ」
line = "「ま、修行の集大成って感じで挑んでみますか。ただ遊んでたわけじゃないってとこ、見せてあげるよ」"

[[dialogue]]
speaker = "ナターシャ"
# 「サンダーボルトプランジっ！！」
line = "「サンダーボルトプランジっ！！」"

[[dialogue]]
speaker = "スクアルス"
# 「ギィィィ～～～～！？」
line = "「ギィィィ～～～～！？」"

[[dialogue]]
speaker = "アポロ"
# 「おおっ、強烈なスパイクだなっ！」
line = "「おおっ、強烈なスパイクだなっ！」"

[[dialogue]]
speaker = "ナターシャ"
# 「ふふ、アポロのアタックを参考にさせてもらったんだ。勝負を決めたあの一撃、すごかったからね」
line = "「ふふ、アポロのアタックを参考にさせてもらったんだ。勝負を決めたあの一撃、すごかったからね」"

[[dialogue]]
speaker = "ベアトリス"
# 「私もみんなと海で遊んだこと、無駄にするわけにはいかないっ！」
line = "「私もみんなと海で遊んだこと、無駄にするわけにはいかないっ！」"

[[dialogue]]
speaker = "ベアトリス"
# 「サンシェードブリッツっ！！」
line = "「サンシェードブリッツっ！！」"

[[dialogue]]
speaker = "スクアルス"
# 「ギィアっ、ギギィィ……！？」
line = "「ギィアっ、ギギィィ……！？」"

[[dialogue]]
speaker = "アポロ"
# 「こいつはイケるぜっ！　このまま押し切っちまおうっ！」
line = "「こいつはイケるぜっ！　このまま押し切っちまおうっ！」"

[[dialogue]]
speaker = "スクアルス"
# 「ギィアアアアアーーッッ！！」
line = "「ギィアアアアアーーッッ！！」"

[[dialogue]]
speaker = "アポロ"
# 「って──全然効いてないっ！？」
line = "「って──全然効いてないっ！？」"

[[dialogue]]
speaker = "梨緒"
# 「いや、確実にダメージは与えられている。ここからは根比べだっ」
line = "「いや、確実にダメージは与えられている。ここからは根比べだっ」"

[[dialogue]]
speaker = "ナターシャ"
# 「また長期戦ってわけだね。骨が折れちゃいそう」
line = "「また長期戦ってわけだね。骨が折れちゃいそう」"

[[dialogue]]
speaker = "ベアトリス"
# 「でも勝てるよっ。私たちならっ！」
line = "「でも勝てるよっ。私たちならっ！」"

[[dialogue]]
speaker = "アポロ"
# 「ああっ。選管の底力っ、見せてやろうぜっ！！」
line = "「ああっ。選管の底力っ、見せてやろうぜっ！！」"

[[dialogue]]
speaker = "unk"
# 選管の４人とモンスターの激しい攻防が続き──
line = "選管の４人とモンスターの激しい攻防が続き──"

[[dialogue]]
speaker = "ベアトリス"
# 「はぁ、はぁ……これで決める……！」
line = "「はぁ、はぁ……これで決める……！」"

[[dialogue]]
speaker = "スクアルス"
# 「ギィアッ……！　ギッ、ギギギッ、ギィィ～～……！！」
line = "「ギィアッ……！　ギッ、ギギギッ、ギィィ～～……！！」"

[[dialogue]]
speaker = "梨緒"
# 「はぁはぁ、倒した……のか？」
line = "「はぁはぁ、倒した……のか？」"

[[dialogue]]
speaker = "ベアトリス"
# 「みたい、だね……」
line = "「みたい、だね……」"

[[dialogue]]
speaker = "アポロ"
# 「へへ、圧勝だったぜ……」
line = "「へへ、圧勝だったぜ……」"

[[dialogue]]
speaker = "ナターシャ"
# 「ギリギリもいいところだったでしょ……。もうヘトヘトだよ……」
line = "「ギリギリもいいところだったでしょ……。もうヘトヘトだよ……」"

[[dialogue]]
speaker = "梨緒"
# 「だが、勝った。クリアしたんだな、私たちは……！　あの新星星徒会よりも先に──！」
line = "「だが、勝った。クリアしたんだな、私たちは……！　あの新星星徒会よりも先に──！」"

[[dialogue]]
speaker = "ベアトリス"
# 「ふふ、やったね、梨緒ちゃん」
line = "「ふふ、やったね、梨緒ちゃん」"

[[dialogue]]
speaker = "アポロ"
# 「あとで魔王たちの悔しがる顔、みんなで見に行こーぜっ」
line = "「あとで魔王たちの悔しがる顔、みんなで見に行こーぜっ」"

[[dialogue]]
speaker = "ナターシャ"
# 「ジグにもいい報告ができるんじゃない？　それ見たことかって」
line = "「ジグにもいい報告ができるんじゃない？　それ見たことかって」"

[[dialogue]]
speaker = "梨緒"
# 「みんな、ぐす、ありがとう……！　みんなのおかげだ……！」
line = "「みんな、ぐす、ありがとう……！　みんなのおかげだ……！」"

[[dialogue]]
speaker = "ベアトリス"
# 「えへへ、も～泣き虫さんなんだから」
line = "「えへへ、も～泣き虫さんなんだから」"

[[dialogue]]
speaker = "アポロ"
# 「少し休んだらリップルを探しに行こうぜ。首を長くしてクリア報告を待ってるはずだ」
line = "「少し休んだらリップルを探しに行こうぜ。首を長くしてクリア報告を待ってるはずだ」"

[[dialogue]]
speaker = "ナターシャ"
# 「たっぷり文句を言ってあげなくちゃ。急激に難易度上げすぎだって」
line = "「たっぷり文句を言ってあげなくちゃ。急激に難易度上げすぎだって」"

[[dialogue]]
speaker = "梨緒"
# 「ふふ、そうだな。よし、それじゃリップルのところに──」
line = "「ふふ、そうだな。よし、それじゃリップルのところに──」"

[[dialogue]]
speaker = "デネブ・カイトス"
# 「グオオオオオオォォ～～！！！」
line = "「グオオオオオオォォ～～！！！」"

[[dialogue]]
speaker = "ベアトリス"
# 「え？」
line = "「え？」"

[[dialogue]]
speaker = "梨緒"
# 「よ──」
line = "「よ──」"

[[dialogue]]
speaker = "梨緒"
# 「避けろぉぉッッ！！！」
line = "「避けろぉぉッッ！！！」"
