[[dialogue]]
speaker = "？？？"
# 「その姿……星騎士だな」
line = "「その姿……星騎士だな」"

[[dialogue]]
speaker = "新星学園星騎士"
# 「え……？　はい、そうですけど……」
line = "「え……？　はい、そうですけど……」"

[[dialogue]]
speaker = "unk"
# モンスターの討伐を終えた星騎士の前に、黒い翼の天使が現れた。
line = "モンスターの討伐を終えた星騎士の前に、黒い翼の天使が現れた。"

[[dialogue]]
speaker = "unk"
# 彼女は薄い笑みを浮かべているものの、帯びる殺気は鋭く禍々しい。
line = "彼女は薄い笑みを浮かべているものの、帯びる殺気は鋭く禍々しい。"

[[dialogue]]
speaker = "？？？"
# 「貴様、プリマステラか？」
line = "「貴様、プリマステラか？」"

[[dialogue]]
speaker = "新星学園星騎士"
# 「な、なんですか急に……あなたは一体──」
line = "「な、なんですか急に……あなたは一体──」"

[[dialogue]]
speaker = "？？？"
# 「プリマステラかと聞いている」
line = "「プリマステラかと聞いている」"

[[dialogue]]
speaker = "新星学園星騎士"
# 「！　まさかコラプサー……！？　武器を捨ててください、抵抗するなら、プリマステラとして容赦しません！」
line = "「！　まさかコラプサー……！？　武器を捨ててください、抵抗するなら、プリマステラとして容赦しません！」"

[[dialogue]]
speaker = "？？？"
# 「やはりプリマステラか。ならば、狩らせてもらう！」
line = "「やはりプリマステラか。ならば、狩らせてもらう！」"

[[dialogue]]
speaker = "新星学園星騎士"
# 「きゃああああああああああッ！！」
line = "「きゃああああああああああッ！！」"

[[dialogue]]
speaker = "？？？"
# 「弱い、弱すぎる。流星市国のプリマステラといってもこの程度か？」
line = "「弱い、弱すぎる。流星市国のプリマステラといってもこの程度か？」"

[[dialogue]]
speaker = "新星学園星騎士"
# 「かはっ……はぁ、はぁ……」
line = "「かはっ……はぁ、はぁ……」"

[[dialogue]]
speaker = "？？？"
# 「まあいい、貴様のセレスティアは貰っていくぞ」
line = "「まあいい、貴様のセレスティアは貰っていくぞ」"

[[dialogue]]
speaker = "新星学園星騎士"
# 「！？　ま、待って……セレスティアがなかったら私……！」
line = "「！？　ま、待って……セレスティアがなかったら私……！」"

[[dialogue]]
speaker = "？？？"
# 「貴様のような弱者に戦う資格などない」
line = "「貴様のような弱者に戦う資格などない」"

[[dialogue]]
speaker = "新星学園星騎士"
# 「そんな……！　お願いだから返して！　私のセレスティアを返してぇ！！」
line = "「そんな……！　お願いだから返して！　私のセレスティアを返してぇ！！」"

[[dialogue]]
speaker = "アナ"
# 「──というように、新星・流星の星騎士が次々と襲撃される事件が起きています」
line = "「──というように、新星・流星の星騎士が次々と襲撃される事件が起きています」"

[[dialogue]]
speaker = "unk"
# 放っておけないな
line = "放っておけないな"

[[dialogue]]
speaker = "マトイ"
# 「うん、ただ襲われるだけじゃなくて、セレスティアまで奪われてるんだもん。早急に解決しなきゃ！」
line = "「うん、ただ襲われるだけじゃなくて、セレスティアまで奪われてるんだもん。早急に解決しなきゃ！」"

[[dialogue]]
speaker = "アナ"
# 「犯人については、被害者の証言からいくつか手がかりを得ています」
line = "「犯人については、被害者の証言からいくつか手がかりを得ています」"

[[dialogue]]
speaker = "マトイ"
# 「流石アナ！　それで犯人はどういう人なの？」
line = "「流石アナ！　それで犯人はどういう人なの？」"

[[dialogue]]
speaker = "アナ"
# 「特徴は、まず天使の女性であること、武器が日本刀であること」
line = "「特徴は、まず天使の女性であること、武器が日本刀であること」"

[[dialogue]]
speaker = "アナ"
# 「そして、襲撃の際に『貴様、プリマステラか？』と必ず問うことが分かっています」
line = "「そして、襲撃の際に『貴様、プリマステラか？』と必ず問うことが分かっています」"

[[dialogue]]
speaker = "マトイ"
# 「天使に日本刀……それと、プリマステラを探してる？」
line = "「天使に日本刀……それと、プリマステラを探してる？」"

[[dialogue]]
speaker = "アナ"
# 「どうやら、彼女は星騎士の中でもプリマステラのみを襲撃しているようです。プリマステラではない星騎士はみな被害に遭っていません」
line = "「どうやら、彼女は星騎士の中でもプリマステラのみを襲撃しているようです。プリマステラではない星騎士はみな被害に遭っていません」"

[[dialogue]]
speaker = "マトイ"
# 「うーん、プリマステラだけを狙うのには何か理由があるのかな？」
line = "「うーん、プリマステラだけを狙うのには何か理由があるのかな？」"

[[dialogue]]
speaker = "アナ"
# 「今のところはなんとも言えません。ですが、この事件は過去の件と類似性があります」
line = "「今のところはなんとも言えません。ですが、この事件は過去の件と類似性があります」"

[[dialogue]]
speaker = "unk"
# コラプサー……
line = "コラプサー……"

[[dialogue]]
speaker = "マトイ"
# 「コラプサー……！　あの星騎士襲撃事件の……」
line = "「コラプサー……！　あの星騎士襲撃事件の……」"

[[dialogue]]
speaker = "アナ"
# 「はい、その可能性はかなり高いと考えています」
line = "「はい、その可能性はかなり高いと考えています」"

[[dialogue]]
speaker = "キサナ"
# 『アタシらはコラプサー。星の光を喰らう者だ』
line = "『アタシらはコラプサー。星の光を喰らう者だ』"

[[dialogue]]
speaker = "unk"
# 過去二回に渡って現れた『コラプサー』と名乗る者たち。
line = "過去二回に渡って現れた『コラプサー』と名乗る者たち。"

[[dialogue]]
speaker = "unk"
# 彼女らの明確な目的は不明だが、新星・流星の星騎士を襲撃し、多くの混沌を招いた。
line = "彼女らの明確な目的は不明だが、新星・流星の星騎士を襲撃し、多くの混沌を招いた。"

[[dialogue]]
speaker = "unk"
# 圧倒的な戦闘力に、星力を打ち消す特殊能力。
line = "圧倒的な戦闘力に、星力を打ち消す特殊能力。"

[[dialogue]]
speaker = "unk"
# 今回も彼女ら『コラプサー』が関わっているとすれば、また困難な事件となるだろう。
line = "今回も彼女ら『コラプサー』が関わっているとすれば、また困難な事件となるだろう。"

[[dialogue]]
speaker = "マトイ"
# 「コラプサーが関わってるなら、なおさら放っておけないよ！　早く犯人を捕まえなきゃ！」
line = "「コラプサーが関わってるなら、なおさら放っておけないよ！　早く犯人を捕まえなきゃ！」"

[[dialogue]]
speaker = "アナ"
# 「ええ、ですから少しでも戦力が欲しいのが現状なのですが、コラプサーに立ち向かえる人員は限られていて──」
line = "「ええ、ですから少しでも戦力が欲しいのが現状なのですが、コラプサーに立ち向かえる人員は限られていて──」"

[[dialogue]]
speaker = "カティア"
# 「そこで私の出番というわけですね！！！」
line = "「そこで私の出番というわけですね！！！」"

[[dialogue]]
speaker = "マトイ"
# 「わあ！　ビックリした！」
line = "「わあ！　ビックリした！」"

[[dialogue]]
speaker = "アナ"
# 「カティアさん、どうしてここに？」
line = "「カティアさん、どうしてここに？」"

[[dialogue]]
speaker = "カティア"
# 「魔王様がピンチと聞いて駆けつけて来たんだワン！」
line = "「魔王様がピンチと聞いて駆けつけて来たんだワン！」"

[[dialogue]]
speaker = "アナ"
# 「つまり、盗み聞きをしていたと」
line = "「つまり、盗み聞きをしていたと」"

[[dialogue]]
speaker = "カティア"
# 「ギクッ！　べべ別にわざとしてたわけじゃないワン！　たまたま聞こえて来たんだガオ！」
line = "「ギクッ！　べべ別にわざとしてたわけじゃないワン！　たまたま聞こえて来たんだガオ！」"

[[dialogue]]
speaker = "マトイ"
# 「盗み聞きしてたことは否定しないんだ……」
line = "「盗み聞きしてたことは否定しないんだ……」"

[[dialogue]]
speaker = "カティア"
# 「それよりも魔王様。私も捜査のお供に加えてください……！」
line = "「それよりも魔王様。私も捜査のお供に加えてください……！」"

[[dialogue]]
speaker = "アナ"
# 「ですが、相手はコラプサー……危険な敵なんですよ？」
line = "「ですが、相手はコラプサー……危険な敵なんですよ？」"

[[dialogue]]
speaker = "マトイ"
# 「そうだよ。プリマステラならまだしも、一般の生徒が参加するだなんて……」
line = "「そうだよ。プリマステラならまだしも、一般の生徒が参加するだなんて……」"

[[dialogue]]
speaker = "カティア"
# 「いえ、犯人はプリマステラだけを狙っているとのこと……なのでプリマステラではない私は逆に安全なはずです！」
line = "「いえ、犯人はプリマステラだけを狙っているとのこと……なのでプリマステラではない私は逆に安全なはずです！」"

[[dialogue]]
speaker = "マトイ"
# 「確かにそういう考え方も出来るかもしれないけど……」
line = "「確かにそういう考え方も出来るかもしれないけど……」"

[[dialogue]]
speaker = "アナ"
# 「会長はどう思われます？」
line = "「会長はどう思われます？」"

[[dialogue]]
speaker = "unk"
# あまり賛同出来ないかな
line = "あまり賛同出来ないかな"

[[dialogue]]
speaker = "カティア"
# 「あ、危なくなったら逃げるワン！　絶対に無理はしませんから！」
line = "「あ、危なくなったら逃げるワン！　絶対に無理はしませんから！」"

[[dialogue]]
speaker = "unk"
# 本当に１人で逃げられる？
line = "本当に１人で逃げられる？"

[[dialogue]]
speaker = "カティア"
# 「大丈夫だワン！　走ることは大得意だガオ！」
line = "「大丈夫だワン！　走ることは大得意だガオ！」"

[[dialogue]]
speaker = "unk"
# ……分かった。絶対に無理しないでね
line = "……分かった。絶対に無理しないでね"

[[dialogue]]
speaker = "カティア"
# 「流石魔王様！　魔王様なら分かってくれると思ってました！」
line = "「流石魔王様！　魔王様なら分かってくれると思ってました！」"

[[dialogue]]
speaker = "マトイ"
# 「少なくとも会長が一緒なら安心はできるね」
line = "「少なくとも会長が一緒なら安心はできるね」"

[[dialogue]]
speaker = "アナ"
# 「それでは会長、カティアさんと一緒に調査をよろしくお願いします」
line = "「それでは会長、カティアさんと一緒に調査をよろしくお願いします」"

[[dialogue]]
speaker = "カティア"
# 「ふっふっふっ、カティア刑事の腕が鳴るワン！」
line = "「ふっふっふっ、カティア刑事の腕が鳴るワン！」"
