[[dialogue]]
speaker = "unk"
# エンジュとメテオラ──人のコラプサーと遭遇した後、コハルコさんにさっきのことを報告しつつ、得られたデータを確認していた。
line = "エンジュとメテオラ──人のコラプサーと遭遇した後、コハルコさんにさっきのことを報告しつつ、得られたデータを確認していた。"

[[dialogue]]
speaker = "コハルコ"
# 「あれだけの数のモンスターを一瞬で殲滅するなんて……エンジュとメテオラ、新たなコラプサーもこれまでの５人に匹敵する脅威みたいだね」
line = "「あれだけの数のモンスターを一瞬で殲滅するなんて……エンジュとメテオラ、新たなコラプサーもこれまでの５人に匹敵する脅威みたいだね」"

[[dialogue]]
speaker = "コハルコ"
# 「そしてメテオラは流星市国に来たばかりと言っていた……コラプサーが戦力を集めているのは、何かを起こそうとしている前兆かも」
line = "「そしてメテオラは流星市国に来たばかりと言っていた……コラプサーが戦力を集めているのは、何かを起こそうとしている前兆かも」"

[[dialogue]]
speaker = "コハルコ"
# 「私もいつも以上に警戒するけど……会長さんも注意してね」
line = "「私もいつも以上に警戒するけど……会長さんも注意してね」"

[[dialogue]]
speaker = "unk"
# そしてその数時間後──
line = "そしてその数時間後──"

[[dialogue]]
speaker = "コハルコ"
# 『緊急です！　都内各所に無数のアステラが出現しました！　出撃可能な星騎士は順次対処をお願いします！』
line = "『緊急です！　都内各所に無数のアステラが出現しました！　出撃可能な星騎士は順次対処をお願いします！』"

[[dialogue]]
speaker = "ミア"
# 「各所に無数って、ざっくりしすぎじゃないですか！？　私はどこに行けばいいんですか！？」
line = "「各所に無数って、ざっくりしすぎじゃないですか！？　私はどこに行けばいいんですか！？」"

[[dialogue]]
speaker = "コハルコ"
# 『情報を統合していますので、少々お待ちを──ミアさんは繁華街に発生したアステラを撃破してください』
line = "『情報を統合していますので、少々お待ちを──ミアさんは繁華街に発生したアステラを撃破してください』"

[[dialogue]]
speaker = "ミア"
# 「わかりました！　百合崎ミア、モンスター鎮圧に向かうわ！　あたしだってちょっとは強くなったんだから！」
line = "「わかりました！　百合崎ミア、モンスター鎮圧に向かうわ！　あたしだってちょっとは強くなったんだから！」"

[[dialogue]]
speaker = "unk"
# 不自然に同時多発した無数のアステラ。そして、大量のモンスター。
line = "不自然に同時多発した無数のアステラ。そして、大量のモンスター。"

[[dialogue]]
speaker = "unk"
# コハルコさんのオペレーションの元、新星・流星両校の星騎士たちは一斉に出撃した。
line = "コハルコさんのオペレーションの元、新星・流星両校の星騎士たちは一斉に出撃した。"

[[dialogue]]
speaker = "ミア"
# 「ふーっ……数は多かったけど、手応えのないモンスターばかりだったわね！　それとも、私が強くなったのかしら、ふふん♪」
line = "「ふーっ……数は多かったけど、手応えのないモンスターばかりだったわね！　それとも、私が強くなったのかしら、ふふん♪」"

[[dialogue]]
speaker = "風紀委員Ａ"
# 「確かにそこまで強いモンスターではなかったですね。でも、モンスターを倒したのに、どうしてアステラが消えないんでしょうか……？」
line = "「確かにそこまで強いモンスターではなかったですね。でも、モンスターを倒したのに、どうしてアステラが消えないんでしょうか……？」"

[[dialogue]]
speaker = "風紀委員Ｂ"
# 「どこかにまだモンスターが隠れてるのかも？　風紀委員各員、警戒を解かずに──」
line = "「どこかにまだモンスターが隠れてるのかも？　風紀委員各員、警戒を解かずに──」"

[[dialogue]]
speaker = "風紀委員Ｂ"
# 「ぐふっ！？」
line = "「ぐふっ！？」"

[[dialogue]]
speaker = "ミア"
# 「！？　大丈夫！？」
line = "「！？　大丈夫！？」"

[[dialogue]]
speaker = "キサナ"
# 「アタシは逃げも隠れもしねえよ。真っ向から正々堂々、潰し合おうじゃねえか」
line = "「アタシは逃げも隠れもしねえよ。真っ向から正々堂々、潰し合おうじゃねえか」"

[[dialogue]]
speaker = "ミア"
# 「キサナ……！？　コラプサーがどうしてここに……！」
line = "「キサナ……！？　コラプサーがどうしてここに……！」"

[[dialogue]]
speaker = "キサナ"
# 「ああ……あの時のチビか。因縁の対決ってヤツか？　あれからちったぁ強くなったのかよ？」
line = "「ああ……あの時のチビか。因縁の対決ってヤツか？　あれからちったぁ強くなったのかよ？」"

[[dialogue]]
speaker = "ミア"
# 「……おかげさまで。一皮剥けさせてもらったわ」
line = "「……おかげさまで。一皮剥けさせてもらったわ」"

[[dialogue]]
speaker = "キサナ"
# 「ハハァ！　声が震えちゃいるが、いい返事だ。泣き出さなかったのだけは褒めてやるよ」
line = "「ハハァ！　声が震えちゃいるが、いい返事だ。泣き出さなかったのだけは褒めてやるよ」"

[[dialogue]]
speaker = "ミア"
# 「コハルコ先輩、こちら、ミア。コラプサーのキサナと対峙……！　新星学園の風紀委員だけじゃちょっとつらいかも……救援は期待できませんか……！？」
line = "「コハルコ先輩、こちら、ミア。コラプサーのキサナと対峙……！　新星学園の風紀委員だけじゃちょっとつらいかも……救援は期待できませんか……！？」"

[[dialogue]]
speaker = "コハルコ"
# 『ごめんなさい……！　各所のアステラにコラプサーたちも同時に現れていて──！』
line = "『ごめんなさい……！　各所のアステラにコラプサーたちも同時に現れていて──！』"

[[dialogue]]
speaker = "コハルコ"
# 『蛍火さんのところにはヴァレリーが』
line = "『蛍火さんのところにはヴァレリーが』"

[[dialogue]]
speaker = "コハルコ"
# 『フランさんのところにイングリット』
line = "『フランさんのところにイングリット』"

[[dialogue]]
speaker = "コハルコ"
# 『シャルレーヌさんのところにジュリエッテ』
line = "『シャルレーヌさんのところにジュリエッテ』"

[[dialogue]]
speaker = "コハルコ"
# 『セナリィさんとネーゼマインさんは、リーナに対峙しています』
line = "『セナリィさんとネーゼマインさんは、リーナに対峙しています』"

[[dialogue]]
speaker = "ミア"
# 「コラプサーが勢揃いで……！？　つまりアステラは星騎士をおびき寄せるための罠だったってこと……！？」
line = "「コラプサーが勢揃いで……！？　つまりアステラは星騎士をおびき寄せるための罠だったってこと……！？」"

[[dialogue]]
speaker = "ミア"
# 「救援に期待できないなら、私たちでやるしかないわ……！　各員に通達！　距離を保ちつつキサナを迎撃！　絶対に正面から攻撃を受けちゃダメよ！」
line = "「救援に期待できないなら、私たちでやるしかないわ……！　各員に通達！　距離を保ちつつキサナを迎撃！　絶対に正面から攻撃を受けちゃダメよ！」"

[[dialogue]]
speaker = "風紀委員Ａ"
# 「はい！」
line = "「はい！」"

[[dialogue]]
speaker = "キサナ"
# 「へえ……肝が据わってんじゃねえか。いっぱしの顔になったみてえだな。さぁ！　楽しくやり合おうぜ！」
line = "「へえ……肝が据わってんじゃねえか。いっぱしの顔になったみてえだな。さぁ！　楽しくやり合おうぜ！」"

[[dialogue]]
speaker = "メテオラ"
# 「あはははは！　誰もいないなー！　けーかくどーり！」
line = "「あはははは！　誰もいないなー！　けーかくどーり！」"

[[dialogue]]
speaker = "エンジュ"
# 『陽動は成功したようだな。星騎士どもは泡食って慌てふためいている頃か』
line = "『陽動は成功したようだな。星騎士どもは泡食って慌てふためいている頃か』"

[[dialogue]]
speaker = "メテオラ"
# 「あはははは、星騎士たちはバカだなー！」
line = "「あはははは、星騎士たちはバカだなー！」"

[[dialogue]]
speaker = "エンジュ"
# 『頃合いだ。メテオラ。やりたい放題、景気よくぶっ放せ』
line = "『頃合いだ。メテオラ。やりたい放題、景気よくぶっ放せ』"

[[dialogue]]
speaker = "メテオラ"
# 「おー！　どっかんどっかんするぞー！　ミーサーイールーどっかーーーーん！」
line = "「おー！　どっかんどっかんするぞー！　ミーサーイールーどっかーーーーん！」"

[[dialogue]]
speaker = "メテオラ"
# 「あれれ？　誰かいるぞ！？　なにものだー！？」
line = "「あれれ？　誰かいるぞ！？　なにものだー！？」"

[[dialogue]]
speaker = "unk"
# 新星学園の星徒会長だ！
line = "新星学園の星徒会長だ！"

[[dialogue]]
speaker = "メテオラ"
# 「げぇ！　魔王！　なんでここにいるんだ！？　エンジュ、話が違うぞー！？」
line = "「げぇ！　魔王！　なんでここにいるんだ！？　エンジュ、話が違うぞー！？」"

[[dialogue]]
speaker = "エンジュ"
# 『アステラには釣られなかったってことか。だがどうして、ここに残った』
line = "『アステラには釣られなかったってことか。だがどうして、ここに残った』"

[[dialogue]]
speaker = "unk"
# コハルコさんが気をつけろって言ってくれたから
line = "コハルコさんが気をつけろって言ってくれたから"

[[dialogue]]
speaker = "unk"
# もしアステラが陽動であれば、本来星騎士に守られている場所を狙うためだと考えた。
line = "もしアステラが陽動であれば、本来星騎士に守られている場所を狙うためだと考えた。"

[[dialogue]]
speaker = "unk"
# 結果はこの通り。推測は的中したらしい。
line = "結果はこの通り。推測は的中したらしい。"

[[dialogue]]
speaker = "エンジュ"
# 『チッ……魔王は一筋縄では行かないか。まぁいい。あんまり簡単すぎても面白みに欠ける』
line = "『チッ……魔王は一筋縄では行かないか。まぁいい。あんまり簡単すぎても面白みに欠ける』"

[[dialogue]]
speaker = "エンジュ"
# 『計画に支障はない。やれ、メテオラ！』
line = "『計画に支障はない。やれ、メテオラ！』"

[[dialogue]]
speaker = "メテオラ"
# 「おーっ！　一番悪いやつ、ボッコボコにやっつけてやるぞー！　覚悟しろ、魔王！」
line = "「おーっ！　一番悪いやつ、ボッコボコにやっつけてやるぞー！　覚悟しろ、魔王！」"
