[[dialogue]]
speaker = "unk"
# 守護天使２人が本体に遭遇する約１０分前――
line = "守護天使２人が本体に遭遇する約１０分前――"

[[dialogue]]
speaker = "アニマ"
# 「これは……！　そうか、そういうことカ……！」
line = "「これは……！　そうか、そういうことカ……！」"

[[dialogue]]
speaker = "unk"
# 保健室でクロトの本体を検査していたアニマは、あることに気づく。
line = "保健室でクロトの本体を検査していたアニマは、あることに気づく。"

[[dialogue]]
speaker = "アニマ"
# 「だとすれば、急いで準備をしナイと――」
line = "「だとすれば、急いで準備をしナイと――」"

[[dialogue]]
speaker = "マグダレナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "アルモタヘル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "アニマ"
# 「はっ！？　しまっ……！」
line = "「はっ！？　しまっ……！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「――アルモタヘル！　無事ですか！？」
line = "「――アルモタヘル！　無事ですか！？」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「間一髪……かわせたのだ！　でも、これは一体、どういうことなのだ……！？」
line = "「間一髪……かわせたのだ！　でも、これは一体、どういうことなのだ……！？」"

[[dialogue]]
speaker = "マグダレナ"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "アルモタヘル"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「本体が攻撃してくるなんて！　まるで堕天している時みたいだぞ！？」
line = "「本体が攻撃してくるなんて！　まるで堕天している時みたいだぞ！？」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「わかりません……！　ただ、どうやら私たちを狙ってきてるみたいです。邪魔が入らないように、周囲に隠蔽の結界が張られています！」
line = "「わかりません……！　ただ、どうやら私たちを狙ってきてるみたいです。邪魔が入らないように、周囲に隠蔽の結界が張られています！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「そういうことなら……ちょうどいいのだ！　この体での新しい力、試してみるのだ、マグダレナ！」
line = "「そういうことなら……ちょうどいいのだ！　この体での新しい力、試してみるのだ、マグダレナ！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「そうですね。皆さまに心配をかけるわけにもいきません。手早く制圧するしかなさそうです！」
line = "「そうですね。皆さまに心配をかけるわけにもいきません。手早く制圧するしかなさそうです！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「――変身！」
line = "「――変身！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「変身なのだ！」
line = "「変身なのだ！」"

[[dialogue]]
speaker = "アルモタヘル（幼少）"
# 「じゃ～ん！　これが……我ら２人の新しい戦闘フォームなのだ！」
line = "「じゃ～ん！　これが……我ら２人の新しい戦闘フォームなのだ！」"

[[dialogue]]
speaker = "マグダレナ（幼少）"
# 「さあ、行きますよ――ママダレナの愛の力、見せちゃいます！」
line = "「さあ、行きますよ――ママダレナの愛の力、見せちゃいます！」"

[[dialogue]]
speaker = "unk"
# そうして、守護天使ＶＳ守護天使の戦闘が開始されるのだった――
line = "そうして、守護天使ＶＳ守護天使の戦闘が開始されるのだった――"
