[[dialogue]]
speaker = "unk"
# 第3話,メイド体験,B
line = "第3話,メイド体験,B"

[[dialogue]]
speaker = "unk"
# キリカ師匠から修行の一環と言われ、マリオンさんの作ったメイド服を着せられた俺は、何故か星見家メイド隊のメイドとして、体験入隊することになった。
line = "キリカ師匠から修行の一環と言われ、マリオンさんの作ったメイド服を着せられた俺は、何故か星見家メイド隊のメイドとして、体験入隊することになった。"

[[dialogue]]
speaker = "マリオン"
# 「あぁんっ<emoji=heart04>　会長様、なんてお可愛らしい<emoji=heart04>　やはり思った通り、メイクしたら、どこからどう見ても美少女にしか見えません！」
line = "「あぁんっ<emoji=heart04>　会長様、なんてお可愛らしい<emoji=heart04>　やはり思った通り、メイクしたら、どこからどう見ても美少女にしか見えません！」"

[[dialogue]]
speaker = "unk"
# いやこれ、執事服じゃダメだったんでしょうか！？
line = "いやこれ、執事服じゃダメだったんでしょうか！？"

[[dialogue]]
speaker = "マリオン"
# 「え？　だって、メイド服の方が可愛いですよね、キリカさん？」
line = "「え？　だって、メイド服の方が可愛いですよね、キリカさん？」"

[[dialogue]]
speaker = "キリカ"
# 「……メイド隊なので、メイドであるに越したことはないかと」
line = "「……メイド隊なので、メイドであるに越したことはないかと」"

[[dialogue]]
speaker = "unk"
# 師匠！？
line = "師匠！？"

[[dialogue]]
speaker = "マリオン"
# 「うふふっ<emoji=heart04>　真面目なキリカさんが頷く程、会長様のメイド服姿がよく似合っているということですよ♪」
line = "「うふふっ<emoji=heart04>　真面目なキリカさんが頷く程、会長様のメイド服姿がよく似合っているということですよ♪」"

[[dialogue]]
speaker = "キリカ"
# 「着替えも済んだところで、緋宮会長。改めて、基本的なところから説明していきます」
line = "「着替えも済んだところで、緋宮会長。改めて、基本的なところから説明していきます」"

[[dialogue]]
speaker = "キリカ"
# 「星見家メイド隊。それは――」
line = "「星見家メイド隊。それは――」"

[[dialogue]]
speaker = "キリカ"
# 「――続いて、『流星教皇』様のことについて改めて説明しておきましょうか」
line = "「――続いて、『流星教皇』様のことについて改めて説明しておきましょうか」"

[[dialogue]]
speaker = "キリカ"
# 「流星市国に住んでいる者なら誰もが知っていることかとは思いますが、この国を統治する機関が『流星教皇庁』です」
line = "「流星市国に住んでいる者なら誰もが知っていることかとは思いますが、この国を統治する機関が『流星教皇庁』です」"

[[dialogue]]
speaker = "キリカ"
# 「国教である『流星教』の総本山であり、下部組織として三界の各地に教会が存在しています」
line = "「国教である『流星教』の総本山であり、下部組織として三界の各地に教会が存在しています」"

[[dialogue]]
speaker = "キリカ"
# 「そのトップに立っているのが、流星教皇様です」
line = "「そのトップに立っているのが、流星教皇様です」"

[[dialogue]]
speaker = "キリカ"
# 「そして、それを代々襲名してきたのが私たちメイド隊が仕える星見家であり、現在の教皇様はフィオナお嬢様の父君にあらせられます」
line = "「そして、それを代々襲名してきたのが私たちメイド隊が仕える星見家であり、現在の教皇様はフィオナお嬢様の父君にあらせられます」"

[[dialogue]]
speaker = "マリオン"
# 「ちなみに教皇様は、セイファート様と共に新星学園を開設した創設者であり、流星学園の理事長も務めていらっしゃいます」
line = "「ちなみに教皇様は、セイファート様と共に新星学園を開設した創設者であり、流星学園の理事長も務めていらっしゃいます」"

[[dialogue]]
speaker = "unk"
# なるほど。だから、星見家メイド隊が――
line = "なるほど。だから、星見家メイド隊が――"

[[dialogue]]
speaker = "マリオン"
# 「ええ。星見家メイド隊が流星学園の運営管理を行っているのは、星見家のご当主である教皇様が学園の理事長だから、ということになりますね」
line = "「ええ。星見家メイド隊が流星学園の運営管理を行っているのは、星見家のご当主である教皇様が学園の理事長だから、ということになりますね」"

[[dialogue]]
speaker = "キリカ"
# 「その他に質問はありませんか？　――よろしいでしょう。ならば、次は緋宮会長がメイドとして、どのくらい仕事ができるのか見せてもらいます」
line = "「その他に質問はありませんか？　――よろしいでしょう。ならば、次は緋宮会長がメイドとして、どのくらい仕事ができるのか見せてもらいます」"

[[dialogue]]
speaker = "unk"
# それから俺は、これまで上月神闘流の修行の一環で磨いてきたメイドスキルで、１日仕事をこなしていった。
line = "それから俺は、これまで上月神闘流の修行の一環で磨いてきたメイドスキルで、１日仕事をこなしていった。"

[[dialogue]]
speaker = "マリオン"
# 「まあまあ、うふふっ♪　これは想像以上ではないですか、キリカさん？」
line = "「まあまあ、うふふっ♪　これは想像以上ではないですか、キリカさん？」"

[[dialogue]]
speaker = "キリカ"
# 「ええ。正直、驚いています。これまでの訓練でも物覚えが早いとは思っていましたが……緋宮会長、率直に申し上げます」
line = "「ええ。正直、驚いています。これまでの訓練でも物覚えが早いとは思っていましたが……緋宮会長、率直に申し上げます」"

[[dialogue]]
speaker = "キリカ"
# 「真面目な話、あなたにはメイド――いえ、執事としての才能があると思います。現時点十分に使用人として仕事を任せられる程に、手際が良い」
line = "「真面目な話、あなたにはメイド――いえ、執事としての才能があると思います。現時点十分に使用人として仕事を任せられる程に、手際が良い」"

[[dialogue]]
speaker = "キリカ"
# 「あなたさえよければ、私の方からフィオナお嬢様にお伝えして、本気で執事候補に迎えたいと私は考えていますが……いかがでしょうか？」
line = "「あなたさえよければ、私の方からフィオナお嬢様にお伝えして、本気で執事候補に迎えたいと私は考えていますが……いかがでしょうか？」"

[[dialogue]]
speaker = "unk"
# ありがたい申し出ですが――
line = "ありがたい申し出ですが――"

[[dialogue]]
speaker = "キリカ"
# 「――今は、星徒会長として皆をリクリエから救える星騎士を目指したい、ですか……」
line = "「――今は、星徒会長として皆をリクリエから救える星騎士を目指したい、ですか……」"

[[dialogue]]
speaker = "キリカ"
# 「そうですか……ダメですか……」
line = "「そうですか……ダメですか……」"

[[dialogue]]
speaker = "マリオン"
# 「残念ですが、その真っ直ぐに理想を追う姿が会長様の魅力でもありますから、致し方ないですね。でも、まだ諦めるには早いかもですよ？　キリカさん」
line = "「残念ですが、その真っ直ぐに理想を追う姿が会長様の魅力でもありますから、致し方ないですね。でも、まだ諦めるには早いかもですよ？　キリカさん」"

[[dialogue]]
speaker = "マリオン"
# 「執事として迎えるのは難しくても、将来的に会長様を上月家の婿に迎えて、生まれた子供を次の執事かメイド長として育てるという手もあります♪」
line = "「執事として迎えるのは難しくても、将来的に会長様を上月家の婿に迎えて、生まれた子供を次の執事かメイド長として育てるという手もあります♪」"

[[dialogue]]
speaker = "unk"
# いやいやいや、なに言ってるんですか！？
line = "いやいやいや、なに言ってるんですか！？"

[[dialogue]]
speaker = "キリカ"
# 「……それはつまり、私が緋宮会長と結婚するということですか？」
line = "「……それはつまり、私が緋宮会長と結婚するということですか？」"

[[dialogue]]
speaker = "マリオン"
# 「うふふ<emoji=heart04>　キリカさんも、いずれは上月家の娘として跡継ぎを作る必要があるでしょうし、会長様のことを現に高く評価しているわけですよね？」
line = "「うふふ<emoji=heart04>　キリカさんも、いずれは上月家の娘として跡継ぎを作る必要があるでしょうし、会長様のことを現に高く評価しているわけですよね？」"

[[dialogue]]
speaker = "マリオン"
# 「あ、でも私が会長様と子供を作って、育てるというパターンもありますね♪」
line = "「あ、でも私が会長様と子供を作って、育てるというパターンもありますね♪」"

[[dialogue]]
speaker = "キリカ"
# 「……ふむ」
line = "「……ふむ」"

[[dialogue]]
speaker = "キリカ"
# 「……どうやら１度、上月家の両親に相談する必要がありそうですね」
line = "「……どうやら１度、上月家の両親に相談する必要がありそうですね」"

[[dialogue]]
speaker = "unk"
# 師匠！？
line = "師匠！？"

[[dialogue]]
speaker = "キリカ"
# 「どうしました？　――子供を育てるのは色々時間がかかるから要検討、ですか？」
line = "「どうしました？　――子供を育てるのは色々時間がかかるから要検討、ですか？」"

[[dialogue]]
speaker = "キリカ"
# 「ですが、確かに私は、いずれ上月家の跡取りを生まなければなりませんし、それならば現状、弟子である緋宮会長を婿に迎えるのは合理的だと思ったのですが……」
line = "「ですが、確かに私は、いずれ上月家の跡取りを生まなければなりませんし、それならば現状、弟子である緋宮会長を婿に迎えるのは合理的だと思ったのですが……」"

[[dialogue]]
speaker = "キリカ"
# 「ああ、でも、会長の気持ちの問題もありますね。私はメイドですので、正妻であることに特にこだわりはありませんが……」
line = "「ああ、でも、会長の気持ちの問題もありますね。私はメイドですので、正妻であることに特にこだわりはありませんが……」"

[[dialogue]]
speaker = "キリカ"
# 「いずれにせよ、両親には一応、報告しておくとしましょう」
line = "「いずれにせよ、両親には一応、報告しておくとしましょう」"

[[dialogue]]
speaker = "unk"
# 師匠！？
line = "師匠！？"

[[dialogue]]
speaker = "マリオン"
# 「うふふっ、会長様<emoji=heart04>　私は３人仲良く一緒に、というのもウェルカムですよ♪」
line = "「うふふっ、会長様<emoji=heart04>　私は３人仲良く一緒に、というのもウェルカムですよ♪」"

[[dialogue]]
speaker = "unk"
# ちょっと想像して、俺は顔が熱くなってしまうのであった。
line = "ちょっと想像して、俺は顔が熱くなってしまうのであった。"
