[[dialogue]]
speaker = "モネ"
# 「う～、緊張します……」
line = "「う～、緊張します……」"

[[dialogue]]
speaker = "イクシリオン"
# 「何かあれば私がお助けしますよ」
line = "「何かあれば私がお助けしますよ」"

[[dialogue]]
speaker = "イクシリオン"
# 「心配されなくても大丈夫です。モネさんの想い、きっと届きます」
line = "「心配されなくても大丈夫です。モネさんの想い、きっと届きます」"

[[dialogue]]
speaker = "モネ"
# 「……はい！」
line = "「……はい！」"

[[dialogue]]
speaker = "モネ"
# 「皆さーん！　少しいいですかー？」
line = "「皆さーん！　少しいいですかー？」"

[[dialogue]]
speaker = "モネ"
# 「私は図書委員の紙屋敷モネです」
line = "「私は図書委員の紙屋敷モネです」"

[[dialogue]]
speaker = "モネ"
# 「私は本が大好きで、皆さんにもっと本を読んでほしい、もっと本に触れてほしいと思っています」
line = "「私は本が大好きで、皆さんにもっと本を読んでほしい、もっと本に触れてほしいと思っています」"

[[dialogue]]
speaker = "モネ"
# 「だから学園や図書館から許可を頂いて、ある活動をすることにしました」
line = "「だから学園や図書館から許可を頂いて、ある活動をすることにしました」"

[[dialogue]]
speaker = "モネ"
# 「ウィステリアさーん」
line = "「ウィステリアさーん」"

[[dialogue]]
speaker = "モネ"
# 「あれ、いない？　いつもならこの時間はまだ働いているのに……」
line = "「あれ、いない？　いつもならこの時間はまだ働いているのに……」"

[[dialogue]]
speaker = "ウィステリア"
# 「ごめんなさい、ちょっと野暮用で外してたの。大丈夫よ」
line = "「ごめんなさい、ちょっと野暮用で外してたの。大丈夫よ」"

[[dialogue]]
speaker = "ウィステリア"
# 「……って何やら真剣な顔ね。思いついたことがあるのかしら」
line = "「……って何やら真剣な顔ね。思いついたことがあるのかしら」"

[[dialogue]]
speaker = "モネ"
# 「どうすれば皆さんが図書館に来てくれるか、私はそればかり考えていました」
line = "「どうすれば皆さんが図書館に来てくれるか、私はそればかり考えていました」"

[[dialogue]]
speaker = "モネ"
# 「でもきっと、待つだけでは変わらない。だから時には図書館の外に出ることも必要なんだと思います」
line = "「でもきっと、待つだけでは変わらない。だから時には図書館の外に出ることも必要なんだと思います」"

[[dialogue]]
speaker = "モネ"
# 「名付けて──」
line = "「名付けて──」"

[[dialogue]]
speaker = "モネ"
# 「出張図書コンシェルジュです！」
line = "「出張図書コンシェルジュです！」"

[[dialogue]]
speaker = "モネ"
# 「読みたい本や知りたいこと、気になることがあったら教えてください。新星学園図書館の本を読み尽くした私が、あなたにぴったりの本をお選びします」
line = "「読みたい本や知りたいこと、気になることがあったら教えてください。新星学園図書館の本を読み尽くした私が、あなたにぴったりの本をお選びします」"

[[dialogue]]
speaker = "モネ"
# 「普段あまり図書館に来られない方も、たまには読書してみませんか？　お気軽にどうぞ～」
line = "「普段あまり図書館に来られない方も、たまには読書してみませんか？　お気軽にどうぞ～」"

[[dialogue]]
speaker = "イクシリオン"
# 「ちなみに私はお手伝いです～」
line = "「ちなみに私はお手伝いです～」"

[[dialogue]]
speaker = "unk"
# ……
line = "……"

[[dialogue]]
speaker = "unk"
# …………
line = "…………"

[[dialogue]]
speaker = "モネ"
# （うぅ、やっぱりあんまり人が来ない……でもここで心が折れたらダメ……誰かが少しくらいは興味を持ってくれるはず……）
line = "（うぅ、やっぱりあんまり人が来ない……でもここで心が折れたらダメ……誰かが少しくらいは興味を持ってくれるはず……）"

[[dialogue]]
speaker = "蛍火"
# 「……」
line = "「……」"

[[dialogue]]
speaker = "モネ"
# （蛍火さん……！　元星徒会役員だけあってとってもお強い人です……！）
line = "（蛍火さん……！　元星徒会役員だけあってとってもお強い人です……！）"

[[dialogue]]
speaker = "蛍火"
# 「こんにちは、モネさん。昨年は星徒会ではお世話になっておりました。よければ私にふさわしい本を見繕っていただけますか」
line = "「こんにちは、モネさん。昨年は星徒会ではお世話になっておりました。よければ私にふさわしい本を見繕っていただけますか」"

[[dialogue]]
speaker = "モネ"
# 「ひゃいっ、もちろんです」
line = "「ひゃいっ、もちろんです」"

[[dialogue]]
speaker = "蛍火"
# 「よろしくお願いします。ただ、私も図書館を訪れたことはあるのです」
line = "「よろしくお願いします。ただ、私も図書館を訪れたことはあるのです」"

[[dialogue]]
speaker = "蛍火"
# 「私が流星市国へとやってきたのは、リクリエに対処するだけでなく、人間界の料理を学ぶためです」
line = "「私が流星市国へとやってきたのは、リクリエに対処するだけでなく、人間界の料理を学ぶためです」"

[[dialogue]]
speaker = "蛍火"
# 「そのため入学直後に図書館で料理の本を調べましたが、技法に関してはすでに習得しているものばかり」
line = "「そのため入学直後に図書館で料理の本を調べましたが、技法に関してはすでに習得しているものばかり」"

[[dialogue]]
speaker = "蛍火"
# 「逆に料理を紹介した本は種類が多すぎて、どれを手に取っていいかわからないくらいでした」
line = "「逆に料理を紹介した本は種類が多すぎて、どれを手に取っていいかわからないくらいでした」"

[[dialogue]]
speaker = "モネ"
# 「ふむふむ、なるほど……そんな蛍火さんに読んでほしい本があります！」
line = "「ふむふむ、なるほど……そんな蛍火さんに読んでほしい本があります！」"

[[dialogue]]
speaker = "モネ"
# 「ウィステリアさん、図書館から持ってきてほしい本がいくつかありまして。書架の場所は──」
line = "「ウィステリアさん、図書館から持ってきてほしい本がいくつかありまして。書架の場所は──」"

[[dialogue]]
speaker = "ウィステリア"
# 「はい、持ってきたわよ。この本でいいのよね？」
line = "「はい、持ってきたわよ。この本でいいのよね？」"

[[dialogue]]
speaker = "モネ"
# 「ありがとうございます。蛍火さんにご紹介したい本は、この『魔界の秘境食』です！」
line = "「ありがとうございます。蛍火さんにご紹介したい本は、この『魔界の秘境食』です！」"

[[dialogue]]
speaker = "蛍火"
# 「？　ここに来たのは人間界の料理を学ぶためとお伝えしたはずですが」
line = "「？　ここに来たのは人間界の料理を学ぶためとお伝えしたはずですが」"

[[dialogue]]
speaker = "モネ"
# 「ええ、存じています。だけど蛍火さんであれば古今東西、三界すべての料理を学びたいはず。そして、人間界だからこそ知ることのできる魔界料理もあると思います」
line = "「ええ、存じています。だけど蛍火さんであれば古今東西、三界すべての料理を学びたいはず。そして、人間界だからこそ知ることのできる魔界料理もあると思います」"

[[dialogue]]
speaker = "モネ"
# 「魔界は広大で無秩序。そして混沌。未だ人智の及ばぬ秘境が無数にあり、一説には今も拡大を続けているとか」
line = "「魔界は広大で無秩序。そして混沌。未だ人智の及ばぬ秘境が無数にあり、一説には今も拡大を続けているとか」"

[[dialogue]]
speaker = "モネ"
# 「探検家が本業で、『魔族は魔界を知らない』と豪語する著者が記したこの本には、魔族すら容易に踏み入れない魔界の奥地の料理が記されています」
line = "「探検家が本業で、『魔族は魔界を知らない』と豪語する著者が記したこの本には、魔族すら容易に踏み入れない魔界の奥地の料理が記されています」"

[[dialogue]]
speaker = "モネ"
# 「例えばシャリオン地方の北西、狂暴な魔獣の巣がたくさんあるとされる場所ですが、そこには小さな村があって、そこでのみ食される料理があるそうです」
line = "「例えばシャリオン地方の北西、狂暴な魔獣の巣がたくさんあるとされる場所ですが、そこには小さな村があって、そこでのみ食される料理があるそうです」"

[[dialogue]]
speaker = "蛍火"
# 「魔鳥の皮から取った脂で、アヒージョのように内蔵を煮込む……初めて聞く料理です。この地方の魔鳥独特の調理法なのでしょうか」
line = "「魔鳥の皮から取った脂で、アヒージョのように内蔵を煮込む……初めて聞く料理です。この地方の魔鳥独特の調理法なのでしょうか」"

[[dialogue]]
speaker = "モネ"
# 「ちなみにこの本は１冊目で、２冊目もあるんです。３冊目の執筆にも取り掛かる予定だったそうですが、その前に著者が行方不明になったそうで……」
line = "「ちなみにこの本は１冊目で、２冊目もあるんです。３冊目の執筆にも取り掛かる予定だったそうですが、その前に著者が行方不明になったそうで……」"

[[dialogue]]
speaker = "蛍火"
# 「それは……魔界ですから、相応の危険があったということなのでしょう」
line = "「それは……魔界ですから、相応の危険があったということなのでしょう」"

[[dialogue]]
speaker = "モネ"
# 「そうですね。だからこそ、彼の著作は貴重と言えます」
line = "「そうですね。だからこそ、彼の著作は貴重と言えます」"

[[dialogue]]
speaker = "モネ"
# 「彼は料理人でも料理研究家でもないので、レシピについて詳細に書かれていないのは残念ではありますが。ですが蛍火さんなら推測も可能かと思います」
line = "「彼は料理人でも料理研究家でもないので、レシピについて詳細に書かれていないのは残念ではありますが。ですが蛍火さんなら推測も可能かと思います」"

[[dialogue]]
speaker = "蛍火"
# 「なるほど……確かに興味深いですね」
line = "「なるほど……確かに興味深いですね」"

[[dialogue]]
speaker = "ウィステリア"
# （蛍火さん、もしかして気を遣って声をかけてくれたのかしら？　でも彼女も楽しそうに本読んでるわね）
line = "（蛍火さん、もしかして気を遣って声をかけてくれたのかしら？　でも彼女も楽しそうに本読んでるわね）"

[[dialogue]]
speaker = "蛍火"
# 「ありがとうございます。予想とは異なりましたが、確かにとても魅力的な本でした。ぜひ読んでみたいと思います」
line = "「ありがとうございます。予想とは異なりましたが、確かにとても魅力的な本でした。ぜひ読んでみたいと思います」"

[[dialogue]]
speaker = "モネ"
# 「いえいえ、読みたいと思っていただけたなら何よりです。他にも料理や食材の本が──あれ？」
line = "「いえいえ、読みたいと思っていただけたなら何よりです。他にも料理や食材の本が──あれ？」"

[[dialogue]]
speaker = "イクシリオン"
# 「ほ～、魔界のお野菜の本もあるのですね。あら、このお茄子……大きくて張りがあって、形がとても……」
line = "「ほ～、魔界のお野菜の本もあるのですね。あら、このお茄子……大きくて張りがあって、形がとても……」"

[[dialogue]]
speaker = "イクシリオン"
# 「キュウリも太くて瑞々しくて……ゴクリ」
line = "「キュウリも太くて瑞々しくて……ゴクリ」"
