[[dialogue]]
speaker = "unk"
# 第１０話,ＶＳ星喰らいシャドウ・魔神ギエル戦闘後,B
line = "第１０話,ＶＳ星喰らいシャドウ・魔神ギエル戦闘後,B"

[[dialogue]]
speaker = "トリュファイナ"
# 「クラウディア、私の魔力をお渡しします──トドメを！！」
line = "「クラウディア、私の魔力をお渡しします──トドメを！！」"

[[dialogue]]
speaker = "クラウディア"
# 「感謝するぞ先代！　全身全霊の──インフィニット・ゴスペルッ！！」
line = "「感謝するぞ先代！　全身全霊の──インフィニット・ゴスペルッ！！」"

[[dialogue]]
speaker = "unk"
# 先代と今代、２人の光の魔女の力が束ねられ、解き放たれる──！
line = "先代と今代、２人の光の魔女の力が束ねられ、解き放たれる──！"

[[dialogue]]
speaker = "魔神ギエル"
# 「グ──ガァ、ァァァァアッ────！？」
line = "「グ──ガァ、ァァァァアッ────！？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「やったかしら！？」
line = "「やったかしら！？」"

[[dialogue]]
speaker = "美鶴"
# 「お嬢様、そういうのフラグって言うんで。敵の息の根が止まるまでは黙っときましょ？」
line = "「お嬢様、そういうのフラグって言うんで。敵の息の根が止まるまでは黙っときましょ？」"

[[dialogue]]
speaker = "魔神ギエル"
# 「なぜ……だ……なぜ……また……私は、敗れる……？」
line = "「なぜ……だ……なぜ……また……私は、敗れる……？」"

[[dialogue]]
speaker = "魔神ギエル"
# 「超越した者になれた、はず、なのに……お、ぉぉおぉおっ──！！」
line = "「超越した者になれた、はず、なのに……お、ぉぉおぉおっ──！！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「うん、やっぱり倒してるわ！！　ギエルの体、どんどん崩れていってるもの！」
line = "「うん、やっぱり倒してるわ！！　ギエルの体、どんどん崩れていってるもの！」"

[[dialogue]]
speaker = "美鶴"
# 「あー、よかった。こっからパワーアップで復活とかしないみたいですねー」
line = "「あー、よかった。こっからパワーアップで復活とかしないみたいですねー」"

[[dialogue]]
speaker = "ＸＥＬＯＳ"
# 「…………グ、グ、ググ……ガ、ァ…………」
line = "「…………グ、グ、ググ……ガ、ァ…………」"

[[dialogue]]
speaker = "トワ先生"
# 「『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』が……消えた！？」
line = "「『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』が……消えた！？」"

[[dialogue]]
speaker = "魔神ギエル"
# 「ふ……ふふ、ふふふ……残る最後の拠点へ、力を集中する……と……」
line = "「ふ……ふふ、ふふふ……残る最後の拠点へ、力を集中する……と……」"

[[dialogue]]
speaker = "リノ"
# 「……黒騎士の、居場所ね」
line = "「……黒騎士の、居場所ね」"

[[dialogue]]
speaker = "魔神ギエル"
# 「星騎士、たち……ここで勝ったところで、お前たちは、いずれ負ける<ruby=さだめ>運命</ruby>……」
line = "「星騎士、たち……ここで勝ったところで、お前たちは、いずれ負ける<ruby>運命<rt>さだめ</rt></ruby>……」"

[[dialogue]]
speaker = "魔神ギエル"
# 「真なる神は滅びない……お前たちは、このベガを解放することもできず……厄災の魔王をこの地に呼ぶことも、敵わない……！！」
line = "「真なる神は滅びない……お前たちは、このベガを解放することもできず……厄災の魔王をこの地に呼ぶことも、敵わない……！！」"

[[dialogue]]
speaker = "魔神ギエル"
# 「アハハ……アハハハハ……！！　先にあの世で待っていますよ！？　また会える時が……楽しみですねぇ……！！！」
line = "「アハハ……アハハハハ……！！　先にあの世で待っていますよ！？　また会える時が……楽しみですねぇ……！！！」"

[[dialogue]]
speaker = "魔神ギエル"
# 「グ、ァァ──ァァアァァア────！！！」
line = "「グ、ァァ──ァァアァァア────！！！」"

[[dialogue]]
speaker = "unk"
# その捨て台詞を最期に、魔神ギエルの影は消滅した──
line = "その捨て台詞を最期に、魔神ギエルの影は消滅した──"

[[dialogue]]
speaker = "ウェンディ"
# 「……目標の撃破を確認。これで４つ目ですね」
line = "「……目標の撃破を確認。これで４つ目ですね」"

[[dialogue]]
speaker = "リーリア"
# 「そうですね～。とりあえずみなさん、お疲れマジカルってことで！」
line = "「そうですね～。とりあえずみなさん、お疲れマジカルってことで！」"

[[dialogue]]
speaker = "クラウディア"
# 「うむ！　お疲れマジカルだ、リーリア！　先代も最後の助力、助かったぞ！」
line = "「うむ！　お疲れマジカルだ、リーリア！　先代も最後の助力、助かったぞ！」"

[[dialogue]]
speaker = "トリュファイナ"
# 「ふふ、お役に立てたようで何よりです。皆様、お疲れ様でした」
line = "「ふふ、お役に立てたようで何よりです。皆様、お疲れ様でした」"

[[dialogue]]
speaker = "クラウディア"
# 「むぅ……違うぞ先代。会話には、流れというものがあるのだ」
line = "「むぅ……違うぞ先代。会話には、流れというものがあるのだ」"

[[dialogue]]
speaker = "クラウディア"
# 「リーリアも余も『マジカル』をつけたのだ、先代も言わねば締まらんというものだぞ！」
line = "「リーリアも余も『マジカル』をつけたのだ、先代も言わねば締まらんというものだぞ！」"

[[dialogue]]
speaker = "ウェンディ"
# 「ちょっと、クラウディア様！？」
line = "「ちょっと、クラウディア様！？」"

[[dialogue]]
speaker = "トリュファイナ"
# 「ほぇ～……そうなのですね。勉強になりますっ」
line = "「ほぇ～……そうなのですね。勉強になりますっ」"

[[dialogue]]
speaker = "トリュファイナ"
# 「では改めて……皆様、お疲れマジカルです！」
line = "「では改めて……皆様、お疲れマジカルです！」"

[[dialogue]]
speaker = "ウェンディ"
# 「またおかしなことをトリュファイナ様に吹き込んで……セドナ長官にバレたらどうしよう……」
line = "「またおかしなことをトリュファイナ様に吹き込んで……セドナ長官にバレたらどうしよう……」"

[[dialogue]]
speaker = "リーリア"
# 「大変ですねー、ウェンディさんも」
line = "「大変ですねー、ウェンディさんも」"

[[dialogue]]
speaker = "ウェンディ"
# 「あなたが元凶ですからね！？　だいたい何なんですか、そのマジカルって！」
line = "「あなたが元凶ですからね！？　だいたい何なんですか、そのマジカルって！」"

[[dialogue]]
speaker = "リーリア"
# 「ん～……ノリですかね☆　ていうか、ウェンディさんは言ってなくないです？」
line = "「ん～……ノリですかね☆　ていうか、ウェンディさんは言ってなくないです？」"

[[dialogue]]
speaker = "ウェンディ"
# 「えっ」
line = "「えっ」"

[[dialogue]]
speaker = "トリュファイナ"
# 「私も聞きたいです。ウェンディ様、お疲れマジカルでした！」
line = "「私も聞きたいです。ウェンディ様、お疲れマジカルでした！」"

[[dialogue]]
speaker = "ウェンディ"
# 「おつかれマジカルですーーー！！！」
line = "「おつかれマジカルですーーー！！！」"

[[dialogue]]
speaker = "ウェンディ"
# （バカみたいな挨拶で恥ずかしすぎます！！　でも偉い人がやってるのに無視するなんて、私にはできません！！！）
line = "（バカみたいな挨拶で恥ずかしすぎます！！　でも偉い人がやってるのに無視するなんて、私にはできません！！！）"

[[dialogue]]
speaker = "クラウディア"
# 「そうだ先代よ。このクリスマスフォームは、ちぇちゅーりえが余のために特別に拵えてくれたものなのだ」
line = "「そうだ先代よ。このクリスマスフォームは、ちぇちゅーりえが余のために特別に拵えてくれたものなのだ」"

[[dialogue]]
speaker = "クラウディア"
# 「このホーリー・ベルは、振るえば何でも願いを叶えることができる！」
line = "「このホーリー・ベルは、振るえば何でも願いを叶えることができる！」"

[[dialogue]]
speaker = "トリュファイナ"
# 「そうなのですか？　それは素晴らしい能力ですね！」
line = "「そうなのですか？　それは素晴らしい能力ですね！」"

[[dialogue]]
speaker = "クラウディア"
# 「うむ！　試しに先代の望みを叶えてみようと思うのだが、何かないかのう？」
line = "「うむ！　試しに先代の望みを叶えてみようと思うのだが、何かないかのう？」"

[[dialogue]]
speaker = "トリュファイナ"
# 「では──戦いの後ですし、いささか喉が渇きました。皆様にお茶でもいかがでしょう？」
line = "「では──戦いの後ですし、いささか喉が渇きました。皆様にお茶でもいかがでしょう？」"

[[dialogue]]
speaker = "トリュファイナ"
# 「私、キイチゴのジャムが入った紅茶だと嬉しいのですが……ここまで細かくても大丈夫でしょうか？」
line = "「私、キイチゴのジャムが入った紅茶だと嬉しいのですが……ここまで細かくても大丈夫でしょうか？」"

[[dialogue]]
speaker = "クラウディア"
# 「承知したぞ！　では──メリークラウディアバースデ～♪」
line = "「承知したぞ！　では──メリークラウディアバースデ～♪」"

[[dialogue]]
speaker = "リーリア"
# 「……これは？」
line = "「……これは？」"

[[dialogue]]
speaker = "トリュファイナ"
# 「キイチゴの苗木と、茶葉の収穫方法が記された……書籍が１冊？」
line = "「キイチゴの苗木と、茶葉の収穫方法が記された……書籍が１冊？」"

[[dialogue]]
speaker = "ウェンディ"
# 「一から作るためのセットってことでしょうか？」
line = "「一から作るためのセットってことでしょうか？」"

[[dialogue]]
speaker = "クラウディア"
# 「むぅ……！　やっぱり願ったものと少し違ったものが出てくるな。世界が変わっても、これは変わらんのか」
line = "「むぅ……！　やっぱり願ったものと少し違ったものが出てくるな。世界が変わっても、これは変わらんのか」"

[[dialogue]]
speaker = "トリュファイナ"
# 「けれどこのようなものを生み出せるだなんて……ツェツィーリエ様は凄いのですね」
line = "「けれどこのようなものを生み出せるだなんて……ツェツィーリエ様は凄いのですね」"

[[dialogue]]
speaker = "ウェンディ"
# 「……あれ？　すみませんクラウディア様、その開発、ツェツィーリエが関わっているって……そのお金はどこから！？」
line = "「……あれ？　すみませんクラウディア様、その開発、ツェツィーリエが関わっているって……そのお金はどこから！？」"

[[dialogue]]
speaker = "クラウディア"
# 「そういえば記憶を受け継いだ時……ウェンディが青い顔をしておったビジョンも見えたのう」
line = "「そういえば記憶を受け継いだ時……ウェンディが青い顔をしておったビジョンも見えたのう」"

[[dialogue]]
speaker = "ウェンディ"
# 「あの女！　違う世界でも私を苦しめているんですね！？　冗談じゃありません！」
line = "「あの女！　違う世界でも私を苦しめているんですね！？　冗談じゃありません！」"

[[dialogue]]
speaker = "ヴィーナス"
# 「大勝利だったわね！　美鶴もリノさんも、お疲れ様♪」
line = "「大勝利だったわね！　美鶴もリノさんも、お疲れ様♪」"

[[dialogue]]
speaker = "リノ"
# 「ええ。ヴィーナスちゃんも大活躍だったわね～♪」
line = "「ええ。ヴィーナスちゃんも大活躍だったわね～♪」"

[[dialogue]]
speaker = "美鶴"
# 「どう考えても戦闘向きじゃないだろーって衣装が出てきましたけど、星力自体はめっちゃ強くなってたんで。お嬢様に怪我がなくてよかったです」
line = "「どう考えても戦闘向きじゃないだろーって衣装が出てきましたけど、星力自体はめっちゃ強くなってたんで。お嬢様に怪我がなくてよかったです」"

[[dialogue]]
speaker = "美鶴"
# 「リノさんもありがとうございました。何度もお嬢様のピンチを救ってくれましたよね。流石は『空間の魔女』」
line = "「リノさんもありがとうございました。何度もお嬢様のピンチを救ってくれましたよね。流石は『空間の魔女』」"

[[dialogue]]
speaker = "リノ"
# 「ヴィーナスちゃんやみんなをを守るためだもの！　お母さん、頑張っちゃったわ～♪」
line = "「ヴィーナスちゃんやみんなをを守るためだもの！　お母さん、頑張っちゃったわ～♪」"

[[dialogue]]
speaker = "ヴィーナス"
# 「ところで美鶴、その衣装はどうしたの？　今まで見たことのない衣装だったから、びっくりしたわ！」
line = "「ところで美鶴、その衣装はどうしたの？　今まで見たことのない衣装だったから、びっくりしたわ！」"

[[dialogue]]
speaker = "美鶴"
# 「星霊祭の応援団用にって作ったヤツみたいで。違う世界にいる自分が作った服を着るだなんて、ちょっと変な感じですけど」
line = "「星霊祭の応援団用にって作ったヤツみたいで。違う世界にいる自分が作った服を着るだなんて、ちょっと変な感じですけど」"

[[dialogue]]
speaker = "美鶴"
# 「でも我ながら良いデザインっていうか……気に入りました。今度お嬢様にも、同じやつ作ってあげましょうか」
line = "「でも我ながら良いデザインっていうか……気に入りました。今度お嬢様にも、同じやつ作ってあげましょうか」"

[[dialogue]]
speaker = "ヴィーナス"
# 「本当に！？　やったー！　完成したらセンちゃんにも見せてあげないとね！」
line = "「本当に！？　やったー！　完成したらセンちゃんにも見せてあげないとね！」"

[[dialogue]]
speaker = "美鶴"
# 「あー。あの子ならすっごく喜ぶでしょうね、色んな意味で……」
line = "「あー。あの子ならすっごく喜ぶでしょうね、色んな意味で……」"

[[dialogue]]
speaker = "美鶴"
# 「でも惜しいですね。フロンティアドライブ・オーバーロード──色んな世界の戦闘服が見れる機会なんて滅多にないのに、今だけなんて」
line = "「でも惜しいですね。フロンティアドライブ・オーバーロード──色んな世界の戦闘服が見れる機会なんて滅多にないのに、今だけなんて」"

[[dialogue]]
speaker = "リノ"
# 「美鶴ちゃんは服が好きなのかしら？」
line = "「美鶴ちゃんは服が好きなのかしら？」"

[[dialogue]]
speaker = "ヴィーナス"
# 「美鶴は九浄家のパタンナーなのよ、リノさん！」
line = "「美鶴は九浄家のパタンナーなのよ、リノさん！」"

[[dialogue]]
speaker = "美鶴"
# 「ぶっちゃけリノさんの水着のデザインも興味あるんですよね。近くで見てもいいです？」
line = "「ぶっちゃけリノさんの水着のデザインも興味あるんですよね。近くで見てもいいです？」"

[[dialogue]]
speaker = "リノ"
# 「ええ、もちろん！　ヴィーナスちゃんに可愛い衣装を作る参考にしてちょうだいね♪」
line = "「ええ、もちろん！　ヴィーナスちゃんに可愛い衣装を作る参考にしてちょうだいね♪」"

[[dialogue]]
speaker = "美鶴"
# 「デザインそのまま使ったら、閃のやつ鼻血出してぶっ倒れそー……ま、それはそれで面白いか」
line = "「デザインそのまま使ったら、閃のやつ鼻血出してぶっ倒れそー……ま、それはそれで面白いか」"

[[dialogue]]
speaker = "煌嶺"
# 「──凄かったね～、メイプルちゃんの戦いっぷり♪　流石は『次の魔王になる者』だね♪」
line = "「──凄かったね～、メイプルちゃんの戦いっぷり♪　流石は『次の魔王になる者』だね♪」"

[[dialogue]]
speaker = "メイプル"
# 「ひぃ！？」
line = "「ひぃ！？」"

[[dialogue]]
speaker = "煌嶺"
# 「そんなにビクビクしなくてもいいのに～♪　これでも褒めてるんだよー？」
line = "「そんなにビクビクしなくてもいいのに～♪　これでも褒めてるんだよー？」"

[[dialogue]]
speaker = "トワ先生"
# 「こらー！　やめなさい、煌嶺ちゃん！　メイプルちゃんが怖がってるでしょー！」
line = "「こらー！　やめなさい、煌嶺ちゃん！　メイプルちゃんが怖がってるでしょー！」"

[[dialogue]]
speaker = "メイプル"
# 「と、トワちゃんっ、トワちゃ～～んっ」
line = "「と、トワちゃんっ、トワちゃ～～んっ」"

[[dialogue]]
speaker = "トワ先生"
# 「そうやって嫌がらせばっかりしてると、みんなに嫌われちゃうんだからねっ。先生としていじめは見過ごせ──」
line = "「そうやって嫌がらせばっかりしてると、みんなに嫌われちゃうんだからねっ。先生としていじめは見過ごせ──」"

[[dialogue]]
speaker = "煌嶺"
# 「…………うるさいなあ♪」
line = "「…………うるさいなあ♪」"

[[dialogue]]
speaker = "煌嶺"
# 「妾の楽しみに水を差すな、教師」
line = "「妾の楽しみに水を差すな、教師」"

[[dialogue]]
speaker = "トワ先生"
# 「────はぇえぇ！？」
line = "「────はぇえぇ！？」"

[[dialogue]]
speaker = "煌嶺"
# 「道化もまともに演じられんとは──潰すぞ？」
line = "「道化もまともに演じられんとは──潰すぞ？」"

[[dialogue]]
speaker = "トワ先生"
# 「アーーウ！！？！？」
line = "「アーーウ！！？！？」"

[[dialogue]]
speaker = "メイプル"
# 「トワちゃん！？　トワちゃーーーーん！！」
line = "「トワちゃん！？　トワちゃーーーーん！！」"

[[dialogue]]
speaker = "トワ先生"
# 「アッ、アッ……アッ……」
line = "「アッ、アッ……アッ……」"

[[dialogue]]
speaker = "煌嶺"
# 「──なーんちゃって♪　うそうそ、冗談だよ～♪」
line = "「──なーんちゃって♪　うそうそ、冗談だよ～♪」"

[[dialogue]]
speaker = "メイプル"
# 「ほらトワちゃん！　煌嶺様も冗談だって──」
line = "「ほらトワちゃん！　煌嶺様も冗談だって──」"

[[dialogue]]
speaker = "煌嶺"
# 「今のところはねっ♪」
line = "「今のところはねっ♪」"

[[dialogue]]
speaker = "２人"
# 「「ひぃ！？」」
line = "「「ひぃ！？」」"

[[dialogue]]
speaker = "unk"
# とうとうアルタイル陣営は、『星喰らい』の拠点を４つ撃破した。
line = "とうとうアルタイル陣営は、『星喰らい』の拠点を４つ撃破した。"

[[dialogue]]
speaker = "リノ"
# （残すはあと１つ……『<ruby=ゼロス>ＸＥＬＯＳ</ruby>』は最後の拠点へ力を集中させると、ギエルが言っていたわね……）
line = "（残すはあと１つ……『<ruby>ＸＥＬＯＳ<rt>ゼロス</rt></ruby>』は最後の拠点へ力を集中させると、ギエルが言っていたわね……）"

[[dialogue]]
speaker = "リノ"
# （次の戦いは、過酷なものになりそうだわ。クロトに伝えておかなきゃ──）
line = "（次の戦いは、過酷なものになりそうだわ。クロトに伝えておかなきゃ──）"
