[[dialogue]]
speaker = "unk"
# ついに始まった、ヒルディオーネとマハムートの対決。
line = "ついに始まった、ヒルディオーネとマハムートの対決。"

[[dialogue]]
speaker = "unk"
# 一気に接近しての格闘戦で拳や蹴りを激しく打ち合った後、凄まじい技の応酬が繰り広げられていた――
line = "一気に接近しての格闘戦で拳や蹴りを激しく打ち合った後、凄まじい技の応酬が繰り広げられていた――"

[[dialogue]]
speaker = "マハムート"
# 「妃竜ライジングインパクト！」
line = "「妃竜ライジングインパクト！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ベイパークラッシュッ！！」
line = "「ベイパークラッシュッ！！」"

[[dialogue]]
speaker = "unk"
# 重力に逆らって下から跳ね上がるように襲い来る鉄球に、ヒルディオーネが渾身の踵落としを叩き込む。
line = "重力に逆らって下から跳ね上がるように襲い来る鉄球に、ヒルディオーネが渾身の踵落としを叩き込む。"

[[dialogue]]
speaker = "マハムート"
# 「引力操作！」
line = "「引力操作！」"

[[dialogue]]
speaker = "unk"
# マハムートが能力を発動し、ヒルディオーネにかかる引力を一気に引き上げ、地面に叩き付けようとするが――
line = "マハムートが能力を発動し、ヒルディオーネにかかる引力を一気に引き上げ、地面に叩き付けようとするが――"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ミラージュブレイカーッ！！」
line = "「ミラージュブレイカーッ！！」"

[[dialogue]]
speaker = "unk"
# 槍のドリルが高速回転し、引力操作の術式を粉砕する。
line = "槍のドリルが高速回転し、引力操作の術式を粉砕する。"

[[dialogue]]
speaker = "unk"
# ヒルディオーネの槍を用いて発動する『対象を物理的に破壊可能なものと定義し打ち砕く』固有の能力で、無効化したのだ。
line = "ヒルディオーネの槍を用いて発動する『対象を物理的に破壊可能なものと定義し打ち砕く』固有の能力で、無効化したのだ。"

[[dialogue]]
speaker = "マハムート"
# 「やはりそのドリルは、私の引力操作にとって天敵ね……」
line = "「やはりそのドリルは、私の引力操作にとって天敵ね……」"

[[dialogue]]
speaker = "マハムート"
# 「さっさと次の手札を切るとしましょう」
line = "「さっさと次の手札を切るとしましょう」"

[[dialogue]]
speaker = "マハムート"
# 「――<ruby=りゅうか>竜化</ruby>」
line = "「――<ruby>竜化<rt>りゅうか</rt></ruby>」"

[[dialogue]]
speaker = "マハムート"
# 「……この姿になるのは、久しぶりね」
line = "「……この姿になるのは、久しぶりね」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「出ましたわね、竜の姿への変身……！」
line = "「出ましたわね、竜の姿への変身……！」"

[[dialogue]]
speaker = "マハムート"
# 「さあ――畏怖をもって跪きなさい」
line = "「さあ――畏怖をもって跪きなさい」"

[[dialogue]]
speaker = "unk"
# 竜の一族の中でも才能を持つ者のみが行使できる能力――『竜化』。
line = "竜の一族の中でも才能を持つ者のみが行使できる能力――『竜化』。"

[[dialogue]]
speaker = "unk"
# それは体力を大きく消耗するのと引き換えに、星力を一時的に数倍にも跳ね上げる強力な変身能力である。
line = "それは体力を大きく消耗するのと引き換えに、星力を一時的に数倍にも跳ね上げる強力な変身能力である。"

[[dialogue]]
speaker = "マハムート"
# 「ドラゴニッククロー！」
line = "「ドラゴニッククロー！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「くうぅっ……！」
line = "「くうぅっ……！」"

[[dialogue]]
speaker = "unk"
# 大きな竜の体からは想像もつかないような速さで振るわれる爪撃を、なんとか槍で受け流すヒルディオーネ。
line = "大きな竜の体からは想像もつかないような速さで振るわれる爪撃を、なんとか槍で受け流すヒルディオーネ。"

[[dialogue]]
speaker = "マハムート"
# 「よく凌いだわね。でも――」
line = "「よく凌いだわね。でも――」"

[[dialogue]]
speaker = "ヒルディオーネ"
# （以前にも増して竜形態のパワーが凄まじくて、完全に攻撃を受け流せなかった……！　体勢が崩れて、マズいですわ！）
line = "（以前にも増して竜形態のパワーが凄まじくて、完全に攻撃を受け流せなかった……！　体勢が崩れて、マズいですわ！）"

[[dialogue]]
speaker = "unk"
# 前回の舞闘会における記憶が、ヒルディオーネの頭の中にデジャヴで蘇る。
line = "前回の舞闘会における記憶が、ヒルディオーネの頭の中にデジャヴで蘇る。"

[[dialogue]]
speaker = "unk"
# マハムートが竜の口を開き、そこに凄まじい密度の炎の星力を収束させて行く。
line = "マハムートが竜の口を開き、そこに凄まじい密度の炎の星力を収束させて行く。"

[[dialogue]]
speaker = "ヒルディオーネ"
# （竜の<ruby=ブレス>息吹</ruby>が――来る！）
line = "（竜の<ruby>息吹<rt>ブレス</rt></ruby>が――来る！）"

[[dialogue]]
speaker = "マハムート"
# 「ドラゴニックメガフレア！」
line = "「ドラゴニックメガフレア！」"

[[dialogue]]
speaker = "unk"
# 放たれた炎の息吹が着弾し、大爆発を引き起こす。その威力は凄まじく、アリーナ観客席との間に張られた仮想結界の境界を震撼させる程。
line = "放たれた炎の息吹が着弾し、大爆発を引き起こす。その威力は凄まじく、アリーナ観客席との間に張られた仮想結界の境界を震撼させる程。"

[[dialogue]]
speaker = "マハムート"
# 「……！」
line = "「……！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「ふうぅ……間一髪でしたわ」
line = "「ふうぅ……間一髪でしたわ」"

[[dialogue]]
speaker = "unk"
# しかし――ヒルディオーネはそれを回避することに成功していた。
line = "しかし――ヒルディオーネはそれを回避することに成功していた。"

[[dialogue]]
speaker = "マハムート"
# 「……どうやら、まだ終わりじゃないみたいね」
line = "「……どうやら、まだ終わりじゃないみたいね」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「前回と同じ轍を踏むわけには行きませんわ。これが私の、竜を打倒する為に編み出した新技――」
line = "「前回と同じ轍を踏むわけには行きませんわ。これが私の、竜を打倒する為に編み出した新技――」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「『スチームオーバーブースト』ですわ！」
line = "「『スチームオーバーブースト』ですわ！」"

[[dialogue]]
speaker = "マハムート"
# 「消えた？　いや――」
line = "「消えた？　いや――」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「はああぁーーーっ！！」
line = "「はああぁーーーっ！！」"

[[dialogue]]
speaker = "unk"
# ヒルディオーネは一瞬でマハムートの背後を取り、拳を叩き込む。
line = "ヒルディオーネは一瞬でマハムートの背後を取り、拳を叩き込む。"

[[dialogue]]
speaker = "マハムート"
# 「速い……！」
line = "「速い……！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# （この技は、最初にノヴァフォームに覚醒したトワ先生の星術『ライズオーバーブースト』を見て思いつき、先生に協力して頂いて完成させたもの）
line = "（この技は、最初にノヴァフォームに覚醒したトワ先生の星術『ライズオーバーブースト』を見て思いつき、先生に協力して頂いて完成させたもの）"

[[dialogue]]
speaker = "ヒルディオーネ"
# （私の身体能力を強化する戦闘服――スチームドレス内の水蒸気を極限まで圧縮し、一気に解放することで、ノヴァフォームに匹敵するパワーを引き出す！）
line = "（私の身体能力を強化する戦闘服――スチームドレス内の水蒸気を極限まで圧縮し、一気に解放することで、ノヴァフォームに匹敵するパワーを引き出す！）"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「スチームオーバースマッシュッ！！」
line = "「スチームオーバースマッシュッ！！」"

[[dialogue]]
speaker = "マハムート"
# 「――ドラゴニックテイル！」
line = "「――ドラゴニックテイル！」"

[[dialogue]]
speaker = "unk"
# 咄嗟に反応してみせたマハムートは竜の尻尾を振るい、ヒルディオーネの放った拳とぶつかり合う。が――
line = "咄嗟に反応してみせたマハムートは竜の尻尾を振るい、ヒルディオーネの放った拳とぶつかり合う。が――"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「蒸気出力、全開ですわぁーーーっ！！」
line = "「蒸気出力、全開ですわぁーーーっ！！」"

[[dialogue]]
speaker = "マハムート"
# 「くぅっ……！？」
line = "「くぅっ……！？」"

[[dialogue]]
speaker = "unk"
# 吹き飛ばされたのはなんと、マハムートの方だった。
line = "吹き飛ばされたのはなんと、マハムートの方だった。"

[[dialogue]]
speaker = "マハムート"
# 「なるほど……竜になった私の力を上回るなんて、大したパワーだわ」
line = "「なるほど……竜になった私の力を上回るなんて、大したパワーだわ」"

[[dialogue]]
speaker = "マハムート"
# 「前回だったら、もしかすると私が負けていたかもしれないわね」
line = "「前回だったら、もしかすると私が負けていたかもしれないわね」"

[[dialogue]]
speaker = "マハムート"
# 「でも――その技だけじゃ、<b>今の</b>私は倒せない」
line = "「でも――その技だけじゃ、<b>今の</b>私は倒せない」"

[[dialogue]]
speaker = "マハムート"
# 「チェンジ――ノヴァフォーム」
line = "「チェンジ――ノヴァフォーム」"

[[dialogue]]
speaker = "unk"
# 現れたのは、元の小さな体へと戻ったマハムート。しかし――
line = "現れたのは、元の小さな体へと戻ったマハムート。しかし――"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「来ましたわね、ノヴァフォーム……！」
line = "「来ましたわね、ノヴァフォーム……！」"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「――頭が高いわよ」
line = "「――頭が高いわよ」"

[[dialogue]]
speaker = "unk"
# 彼女から発せられる<ruby=プレッシャー>威圧感</ruby>は、先程の大きな竜形態よりも遥かに上。
line = "彼女から発せられる<ruby>威圧感<rt>プレッシャー</rt></ruby>は、先程の大きな竜形態よりも遥かに上。"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「くっ！？　ミラージュブレイカー！」
line = "「くっ！？　ミラージュブレイカー！」"

[[dialogue]]
speaker = "unk"
# マハムートの言葉と同時に発動した『引力操作』で、ヒルディオーネの体が引っ張られる。それをドリルで無効化しようとするが――
line = "マハムートの言葉と同時に発動した『引力操作』で、ヒルディオーネの体が引っ張られる。それをドリルで無効化しようとするが――"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「っ……解除できない！？」
line = "「っ……解除できない！？」"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「残念ね。打ち破るには純粋に、ドリルのパワー不足よ」
line = "「残念ね。打ち破るには純粋に、ドリルのパワー不足よ」"

[[dialogue]]
speaker = "unk"
# 通常フォームの時とは比べ物にならない引力の強さで、マハムートの方に引き寄せられるヒルディオーネ。
line = "通常フォームの時とは比べ物にならない引力の強さで、マハムートの方に引き寄せられるヒルディオーネ。"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「っ……だったら！　――ドリルオーバーブレイカーッ！！」
line = "「っ……だったら！　――ドリルオーバーブレイカーッ！！」"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「――メテオクロー！」
line = "「――メテオクロー！」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「くうぅっ！？」
line = "「くうぅっ！？」"

[[dialogue]]
speaker = "unk"
# 今度はヒルディオーネの方が力で競り負け、吹き飛ばされてしまう。
line = "今度はヒルディオーネの方が力で競り負け、吹き飛ばされてしまう。"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「かはっ……！」
line = "「かはっ……！」"

[[dialogue]]
speaker = "unk"
# 背中から地面に強く叩き付けられ、肺の中の空気が強制的に吐き出される。
line = "背中から地面に強く叩き付けられ、肺の中の空気が強制的に吐き出される。"

[[dialogue]]
speaker = "ヒルディオーネ"
# （スチームオーバーブーストの持続時間は約３分……その効果はまだ続いているはずなのに……！）
line = "（スチームオーバーブーストの持続時間は約３分……その効果はまだ続いているはずなのに……！）"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「――前にバトルフェスタで戦った私のシャドウとは、比べ物にならない程に強くなっている……そんな風に思ったりした？」
line = "「――前にバトルフェスタで戦った私のシャドウとは、比べ物にならない程に強くなっている……そんな風に思ったりした？」"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「だとしたら、畏怖が足りてないわよ、ヒルディオーネ」
line = "「だとしたら、畏怖が足りてないわよ、ヒルディオーネ」"

[[dialogue]]
speaker = "マハムート（覚醒）"
# 「言っていたでしょう？　同じノヴァフォームであっても――この私が、あの時と同じ強さのままでいるわけがないじゃない」
line = "「言っていたでしょう？　同じノヴァフォームであっても――この私が、あの時と同じ強さのままでいるわけがないじゃない」"

[[dialogue]]
speaker = "ヒルディオーネ"
# 「っ……！」
line = "「っ……！」"

[[dialogue]]
speaker = "unk"
# ヒルディオーネは仰向けに倒れたまま、圧倒的な星力を纏い飛翔する<ruby=マハムート>小さき竜</ruby>の姿を見上げるのだった――
line = "ヒルディオーネは仰向けに倒れたまま、圧倒的な星力を纏い飛翔する<ruby>小さき竜<rt>マハムート</rt></ruby>の姿を見上げるのだった――"
