[[dialogue]]
speaker = "unk"
# 新種のモンスターから逃げて、アステラ中心部を離れるように逃走し続けるトワとメイプル。
line = "新種のモンスターから逃げて、アステラ中心部を離れるように逃走し続けるトワとメイプル。"

[[dialogue]]
speaker = "unk"
# しかし――
line = "しかし――"

[[dialogue]]
speaker = "メイプル"
# 「くっ……ダメ！　逃げ切れない！　このモンスター、速すぎる！」
line = "「くっ……ダメ！　逃げ切れない！　このモンスター、速すぎる！」"

[[dialogue]]
speaker = "モンスター"
# 「グオォォォッ！」
line = "「グオォォォッ！」"

[[dialogue]]
speaker = "メイプル"
# 「きゃあぁっ！？」
line = "「きゃあぁっ！？」"

[[dialogue]]
speaker = "トワ先生"
# 「メイプルちゃん！」
line = "「メイプルちゃん！」"

[[dialogue]]
speaker = "メイプル"
# 「うっ……！　今の攻撃で足が……！」
line = "「うっ……！　今の攻撃で足が……！」"

[[dialogue]]
speaker = "unk"
# 片足にダメ―ジを受けて、メイプルはすぐに立ち上がることができない。
line = "片足にダメ―ジを受けて、メイプルはすぐに立ち上がることができない。"

[[dialogue]]
speaker = "トワ先生"
# （この傷は回復しなくちゃダメだ。でも、この速い相手に、回復の星術を使ってる暇はない……！）
line = "（この傷は回復しなくちゃダメだ。でも、この速い相手に、回復の星術を使ってる暇はない……！）"

[[dialogue]]
speaker = "メイプル"
# 「トワちゃん、あたしのことはいいから逃げて……！」
line = "「トワちゃん、あたしのことはいいから逃げて……！」"

[[dialogue]]
speaker = "トワ先生"
# 「……それはできない。私は先生だから」
line = "「……それはできない。私は先生だから」"

[[dialogue]]
speaker = "メイプル"
# 「でも、あたしはまだ学園に通ってない……！」
line = "「でも、あたしはまだ学園に通ってない……！」"

[[dialogue]]
speaker = "トワ先生"
# 「これから通うんでしょ。それに、生徒だから守るんじゃないよ」
line = "「これから通うんでしょ。それに、生徒だから守るんじゃないよ」"

[[dialogue]]
speaker = "トワ先生"
# 「私が先生として、そうなりたいから守るの」
line = "「私が先生として、そうなりたいから守るの」"

[[dialogue]]
speaker = "メイプル"
# 「トワちゃん……先生……」
line = "「トワちゃん……先生……」"

[[dialogue]]
speaker = "トワ先生"
# 「だから見てて。先生の戦うところ」
line = "「だから見てて。先生の戦うところ」"

[[dialogue]]
speaker = "unk"
# トワはメイプルの頭を優しく撫でて、立ち上がる。
line = "トワはメイプルの頭を優しく撫でて、立ち上がる。"

[[dialogue]]
speaker = "unk"
# そして、楽しむかのように空中から見下ろしているモンスターと、改めて向き直った。
line = "そして、楽しむかのように空中から見下ろしているモンスターと、改めて向き直った。"

[[dialogue]]
speaker = "トワ先生"
# （マリオン、使うよ。あの技を）
line = "（マリオン、使うよ。あの技を）"

[[dialogue]]
speaker = "unk"
# トワは１度、深呼吸をして……その技を口にする。
line = "トワは１度、深呼吸をして……その技を口にする。"

[[dialogue]]
speaker = "トワ先生"
# 「ライズ・オーバーブースト」
line = "「ライズ・オーバーブースト」"

[[dialogue]]
speaker = "メイプル"
# 「え……！？」
line = "「え……！？」"

[[dialogue]]
speaker = "unk"
# 次の瞬間、メイプルの目の前に立っていたトワの姿が消えていた。
line = "次の瞬間、メイプルの目の前に立っていたトワの姿が消えていた。"

[[dialogue]]
speaker = "メイプル"
# （いや違う！　一瞬でモンスターの背後に！？）
line = "（いや違う！　一瞬でモンスターの背後に！？）"

[[dialogue]]
speaker = "トワ先生"
# 「はあああぁぁぁーーーッ！」
line = "「はあああぁぁぁーーーッ！」"

[[dialogue]]
speaker = "モンスター"
# 「グオオォォォッ！？」
line = "「グオオォォォッ！？」"

[[dialogue]]
speaker = "unk"
# トワはモンスターの背中に拳を叩き込み、その体を地面に叩きつける。
line = "トワはモンスターの背中に拳を叩き込み、その体を地面に叩きつける。"

[[dialogue]]
speaker = "トワ先生"
# 「とりゃああぁぁぁーーーッ！」
line = "「とりゃああぁぁぁーーーッ！」"

[[dialogue]]
speaker = "unk"
# そのまま隙を与えず、地面に瞬間移動してモンスターを掴むと、宙に背負い投げる。
line = "そのまま隙を与えず、地面に瞬間移動してモンスターを掴むと、宙に背負い投げる。"

[[dialogue]]
speaker = "unk"
# そこから四方八方に瞬間移動し、ピンボールのように滅多打ちにし――
line = "そこから四方八方に瞬間移動し、ピンボールのように滅多打ちにし――"

[[dialogue]]
speaker = "トワ先生"
# 「星力反転……！」
line = "「星力反転……！」"

[[dialogue]]
speaker = "unk"
# トワの手の平に、暁色に輝く星力を収束させた球体が形成される。
line = "トワの手の平に、暁色に輝く星力を収束させた球体が形成される。"

[[dialogue]]
speaker = "unk"
# それをモンスターの腹部に押し付けるように、撃ち放った。
line = "それをモンスターの腹部に押し付けるように、撃ち放った。"

[[dialogue]]
speaker = "トワ先生"
# 「ライジングマーキュリー！」
line = "「ライジングマーキュリー！」"

[[dialogue]]
speaker = "モンスター"
# 「ウオオオォォォーーーーーーッ！！？」
line = "「ウオオオォォォーーーーーーッ！！？」"

[[dialogue]]
speaker = "unk"
# 凄まじい閃光と共に、モンスターが遠くまで吹き飛ばされ、アステラ内のオブジェクトに激突。
line = "凄まじい閃光と共に、モンスターが遠くまで吹き飛ばされ、アステラ内のオブジェクトに激突。"

[[dialogue]]
speaker = "unk"
# 衝撃で崩壊したオブジェクトの瓦礫に押しつぶされて、沈黙した。
line = "衝撃で崩壊したオブジェクトの瓦礫に押しつぶされて、沈黙した。"

[[dialogue]]
speaker = "メイプル"
# 「すごい……！　あのモンスターを倒しちゃうなんて……！」
line = "「すごい……！　あのモンスターを倒しちゃうなんて……！」"

[[dialogue]]
speaker = "トワ先生"
# 「はぁ……はぁ……！」
line = "「はぁ……はぁ……！」"

[[dialogue]]
speaker = "メイプル"
# 「先生、すごいよ！　まさかこんな力を隠してるなんて……！」
line = "「先生、すごいよ！　まさかこんな力を隠してるなんて……！」"

[[dialogue]]
speaker = "トワ先生"
# 「っ……！」
line = "「っ……！」"

[[dialogue]]
speaker = "メイプル"
# 「先生！？」
line = "「先生！？」"

[[dialogue]]
speaker = "unk"
# トワは苦しそうな表情を浮かべ、地面に崩れ落ちてしまう。
line = "トワは苦しそうな表情を浮かべ、地面に崩れ落ちてしまう。"

[[dialogue]]
speaker = "メイプル"
# 「どうしたの先生！？　大丈夫！？　……えっ！？」
line = "「どうしたの先生！？　大丈夫！？　……えっ！？」"

[[dialogue]]
speaker = "unk"
# 慌ててトワの体を支えるメイプルだったが、触れた手の平に違和感を感じて、見やると――
line = "慌ててトワの体を支えるメイプルだったが、触れた手の平に違和感を感じて、見やると――"

[[dialogue]]
speaker = "メイプル"
# 「血……！？　トワちゃん、体から血が出てる！？　どうして！？」
line = "「血……！？　トワちゃん、体から血が出てる！？　どうして！？」"

[[dialogue]]
speaker = "メイプル"
# 「すごい速さで動き回って、敵の攻撃は受けてなかったはず。なのに……！」
line = "「すごい速さで動き回って、敵の攻撃は受けてなかったはず。なのに……！」"

[[dialogue]]
speaker = "トワ先生"
# 「っ……これはそういう、リスクのある技だから……」
line = "「っ……これはそういう、リスクのある技だから……」"

[[dialogue]]
speaker = "メイプル"
# 「リスク……！？」
line = "「リスク……！？」"

[[dialogue]]
speaker = "トワ先生"
# 「ライズ・オーバーブーストは……私の自動回復の出力を極限まで引き上げる。そうすることで、体の限界を無視して星力を引き出す技なの」
line = "「ライズ・オーバーブーストは……私の自動回復の出力を極限まで引き上げる。そうすることで、体の限界を無視して星力を引き出す技なの」"

[[dialogue]]
speaker = "トワ先生"
# 「簡単に言うと、ドーピングみたいな感じ。だから……こうして反動がある……」
line = "「簡単に言うと、ドーピングみたいな感じ。だから……こうして反動がある……」"

[[dialogue]]
speaker = "トワ先生"
# 「ちょっとでも星力制御を誤ると、回復のし過ぎで体の細胞が壊れちゃうの……」
line = "「ちょっとでも星力制御を誤ると、回復のし過ぎで体の細胞が壊れちゃうの……」"

[[dialogue]]
speaker = "トワ先生"
# （学園を卒業してから１０年以上も星力制御を磨き続けて……それでやっと１分……）
line = "（学園を卒業してから１０年以上も星力制御を磨き続けて……それでやっと１分……）"

[[dialogue]]
speaker = "unk"
# それはかつて、トワが学生時代、最強の星徒会長であるマリオンに追いつき、隣に立って戦いたいが為に編み出した技だった。
line = "それはかつて、トワが学生時代、最強の星徒会長であるマリオンに追いつき、隣に立って戦いたいが為に編み出した技だった。"

[[dialogue]]
speaker = "unk"
# しかし――
line = "しかし――"

[[dialogue]]
speaker = "マリオン"
# 「――トワ、私の勝ちです。約束通り、星徒会長の権限を以て、その技の使用を禁じます」
line = "「――トワ、私の勝ちです。約束通り、星徒会長の権限を以て、その技の使用を禁じます」"

[[dialogue]]
speaker = "トワ先生"
# 「くっ……！　あとちょっと……だったのに……！　あと数秒……制御が上手く行っていれば……！」
line = "「くっ……！　あとちょっと……だったのに……！　あと数秒……制御が上手く行っていれば……！」"

[[dialogue]]
speaker = "マリオン"
# 「……ええ。強かった。わずか１分にも満たない間に、私の分身が全滅させられる程に……」
line = "「……ええ。強かった。わずか１分にも満たない間に、私の分身が全滅させられる程に……」"

[[dialogue]]
speaker = "マリオン"
# 「ですが……ダメです。使う度にそんな血まみれの自傷を繰り返す技は、星徒会長として……いえ、友人として看過できない」
line = "「ですが……ダメです。使う度にそんな血まみれの自傷を繰り返す技は、星徒会長として……いえ、友人として看過できない」"

[[dialogue]]
speaker = "トワ先生"
# 「でも……！　やっとマリオンと……みんなと一緒に戦えるようになる方法を見つけたのに……！」
line = "「でも……！　やっとマリオンと……みんなと一緒に戦えるようになる方法を見つけたのに……！」"

[[dialogue]]
speaker = "マリオン"
# 「……トワは自身だけでなく、他者にも長時間の持続性を持つ『自動回復』をかけることができる。それだけでも十分すぎる能力です」
line = "「……トワは自身だけでなく、他者にも長時間の持続性を持つ『自動回復』をかけることができる。それだけでも十分すぎる能力です」"

[[dialogue]]
speaker = "トワ先生"
# 「それでも、私は……！」
line = "「それでも、私は……！」"

[[dialogue]]
speaker = "マリオン"
# 「トワ！」
line = "「トワ！」"

[[dialogue]]
speaker = "unk"
# 今までにないほど真剣なマリオンの声にトワが頭を上げると、そこには――
line = "今までにないほど真剣なマリオンの声にトワが頭を上げると、そこには――"

[[dialogue]]
speaker = "マリオン"
# 「お願いだから、その技はもう使わないで……！」
line = "「お願いだから、その技はもう使わないで……！」"

[[dialogue]]
speaker = "メイプル"
# 「ごめん、なさい……先生……！」
line = "「ごめん、なさい……先生……！」"

[[dialogue]]
speaker = "トワ先生"
# 「メイプル、ちゃん……？」
line = "「メイプル、ちゃん……？」"

[[dialogue]]
speaker = "unk"
# トワが頭を上げるとそこには、涙をこぼすメイプルの泣き顔があった。
line = "トワが頭を上げるとそこには、涙をこぼすメイプルの泣き顔があった。"

[[dialogue]]
speaker = "メイプル"
# 「私が先生の言うことを聞いて、１人でモンスターと戦おうとなんかしていなければ、こんなことにならずに済んだのに……！」
line = "「私が先生の言うことを聞いて、１人でモンスターと戦おうとなんかしていなければ、こんなことにならずに済んだのに……！」"

[[dialogue]]
speaker = "トワ先生"
# 「今回のは……メイプルちゃんのせいじゃないよ。仮にメイプルちゃんがいなくても、先生は現場に駆け付けて、アステラの発生に巻き込まれてたと思うし……」
line = "「今回のは……メイプルちゃんのせいじゃないよ。仮にメイプルちゃんがいなくても、先生は現場に駆け付けて、アステラの発生に巻き込まれてたと思うし……」"

[[dialogue]]
speaker = "メイプル"
# 「でも、あたしがいなければ、先生は技を使わずに済んだかもしれない！」
line = "「でも、あたしがいなければ、先生は技を使わずに済んだかもしれない！」"

[[dialogue]]
speaker = "メイプル"
# 「……本当は、わかってたの。自分のワガママだって……！」
line = "「……本当は、わかってたの。自分のワガママだって……！」"

[[dialogue]]
speaker = "メイプル"
# 「あたしが世界を救う魔王になるって言った時、煌嶺には笑われて、パパとママには無理だと言われた」
line = "「あたしが世界を救う魔王になるって言った時、煌嶺には笑われて、パパとママには無理だと言われた」"

[[dialogue]]
speaker = "メイプル"
# 「悔しかった。あたしの憧れる魔王という存在まで馬鹿にされたみたいで……！　何もせずに諦めることが、どうしてもできなかった……！」
line = "「悔しかった。あたしの憧れる魔王という存在まで馬鹿にされたみたいで……！　何もせずに諦めることが、どうしてもできなかった……！」"

[[dialogue]]
speaker = "メイプル"
# 「血を引いているから魔王になれるんじゃない。世界を救う英雄が魔王と呼ばれるんだって、証明したかった……！」
line = "「血を引いているから魔王になれるんじゃない。世界を救う英雄が魔王と呼ばれるんだって、証明したかった……！」"

[[dialogue]]
speaker = "メイプル"
# 「トワ先生……ワガママで困らせて、ごめんなさい……！」
line = "「トワ先生……ワガママで困らせて、ごめんなさい……！」"

[[dialogue]]
speaker = "トワ先生"
# 「……わかるよ。私もずっと……今も、諦めきれないでいるから……」
line = "「……わかるよ。私もずっと……今も、諦めきれないでいるから……」"

[[dialogue]]
speaker = "メイプル"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "トワ先生"
# 「私の星騎士としての適性は、回復星術……でも、周りの子たちが強い星騎士ばかりで、自分も一緒に戦えるようになりたいって……下らない憧れを抱いちゃったの……」
line = "「私の星騎士としての適性は、回復星術……でも、周りの子たちが強い星騎士ばかりで、自分も一緒に戦えるようになりたいって……下らない憧れを抱いちゃったの……」"

[[dialogue]]
speaker = "トワ先生"
# 「それを諦めきれずに、考え出したのがさっきのライズ・オーバーブースト……自傷を免れない危険な星術だった……」
line = "「それを諦めきれずに、考え出したのがさっきのライズ・オーバーブースト……自傷を免れない危険な星術だった……」"

[[dialogue]]
speaker = "トワ先生"
# 「親友から使うなって言われてたのに、ワガママを通して使い続けて、使用禁止まで言い渡されたのに……今もまだ諦めきれないでいる……」
line = "「親友から使うなって言われてたのに、ワガママを通して使い続けて、使用禁止まで言い渡されたのに……今もまだ諦めきれないでいる……」"

[[dialogue]]
speaker = "トワ先生"
# 「『自動回復』の特異体質も同じ……卒業してから星力制御を鍛錬し続けて、本当は自分の意思でオフにできるようになったのに、色々理由を付けて結局できずにいる……」
line = "「『自動回復』の特異体質も同じ……卒業してから星力制御を鍛錬し続けて、本当は自分の意思でオフにできるようになったのに、色々理由を付けて結局できずにいる……」"

[[dialogue]]
speaker = "トワ先生"
# 「私はまだ、星騎士でいたいんだよ。しかも、できればまだ強くなりたいとまで思い続けてる……」
line = "「私はまだ、星騎士でいたいんだよ。しかも、できればまだ強くなりたいとまで思い続けてる……」"

[[dialogue]]
speaker = "トワ先生"
# 「つまりは……先生もまだ、大人になりきれていないんだ……」
line = "「つまりは……先生もまだ、大人になりきれていないんだ……」"

[[dialogue]]
speaker = "トワ先生"
# 「諦めきれないんだよ。みんなと一緒にリクリエと戦うことを……」
line = "「諦めきれないんだよ。みんなと一緒にリクリエと戦うことを……」"

[[dialogue]]
speaker = "トワ先生"
# 「だから……メイプルちゃんが諦めきれないなら、先生が応援する」
line = "「だから……メイプルちゃんが諦めきれないなら、先生が応援する」"

[[dialogue]]
speaker = "トワ先生"
# 「魔王になる夢を応援するよ」
line = "「魔王になる夢を応援するよ」"

[[dialogue]]
speaker = "トワ先生"
# 「だから、１人で戦おうとしないで。メイプルちゃんと一緒に戦おうとしてくれる仲間は……ちゃんと周りにいるから」
line = "「だから、１人で戦おうとしないで。メイプルちゃんと一緒に戦おうとしてくれる仲間は……ちゃんと周りにいるから」"

[[dialogue]]
speaker = "unk"
# トワ先生ーーッ！！　メイプルーーッ！！
line = "トワ先生ーーッ！！　メイプルーーッ！！"

[[dialogue]]
speaker = "メイプル"
# 「この声、お兄ちゃん……！？」
line = "「この声、お兄ちゃん……！？」"

[[dialogue]]
speaker = "トワ先生"
# 「ほら、助けに来てくれた……」
line = "「ほら、助けに来てくれた……」"

[[dialogue]]
speaker = "unk"
# よかった！　やっぱり２人共一緒にいた！
line = "よかった！　やっぱり２人共一緒にいた！"

[[dialogue]]
speaker = "メイプル"
# 「お兄ちゃん！」
line = "「お兄ちゃん！」"

[[dialogue]]
speaker = "トワ先生"
# 「これで後は……アステラから脱出するだけ……あれ……？」
line = "「これで後は……アステラから脱出するだけ……あれ……？」"

[[dialogue]]
speaker = "メイプル"
# 「先生？　どうしたの……？」
line = "「先生？　どうしたの……？」"

[[dialogue]]
speaker = "トワ先生"
# 「ボスモンスターは倒したはずなのに……」
line = "「ボスモンスターは倒したはずなのに……」"

[[dialogue]]
speaker = "トワ先生"
# 「アステラの崩壊が始まっていない……？」
line = "「アステラの崩壊が始まっていない……？」"

[[dialogue]]
speaker = "メイプル"
# 「え……？」
line = "「え……？」"

[[dialogue]]
speaker = "unk"
# その時、遠くのオブジェクトの瓦礫が崩れる音がして、その中から――
line = "その時、遠くのオブジェクトの瓦礫が崩れる音がして、その中から――"

[[dialogue]]
speaker = "モンスター"
# 「…………」
line = "「…………」"

[[dialogue]]
speaker = "メイプル"
# 「う……嘘でしょ……？　まだ生きてるなんて……！」
line = "「う……嘘でしょ……？　まだ生きてるなんて……！」"

[[dialogue]]
speaker = "モンスター"
# 「グオオオォォォーーーーーーッ！！！」
line = "「グオオオォォォーーーーーーッ！！！」"

[[dialogue]]
speaker = "unk"
# 新種モンスターは、怒るかのように再び咆哮を上げるのだった――
line = "新種モンスターは、怒るかのように再び咆哮を上げるのだった――"
