[[dialogue]]
speaker = "ウズメイア"
# 「セナリィさん、追い出されちゃったね」
line = "「セナリィさん、追い出されちゃったね」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「悪いことをしていたんだからしょうがないゆ！　名誉会長としても見過ごせないゆ！」
line = "「悪いことをしていたんだからしょうがないゆ！　名誉会長としても見過ごせないゆ！」"

[[dialogue]]
speaker = "ソフィア"
# 「名誉会長？」
line = "「名誉会長？」"

[[dialogue]]
speaker = "ヒトリ"
# 「ジャクリーヌちゃんはキャナンシーさんに見込まれて、ハロウィン実行委員会の名誉会長になったんです……」
line = "「ジャクリーヌちゃんはキャナンシーさんに見込まれて、ハロウィン実行委員会の名誉会長になったんです……」"

[[dialogue]]
speaker = "ウズメイア"
# 「あ～、じゃセナリィさん、名誉会長の前で全部自白しちゃったんだ～。そりゃドンマイだし～」
line = "「あ～、じゃセナリィさん、名誉会長の前で全部自白しちゃったんだ～。そりゃドンマイだし～」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「さあさあ、気を取り直して遊ぶゆ！　２人は気になる所はないのかゆ？」
line = "「さあさあ、気を取り直して遊ぶゆ！　２人は気になる所はないのかゆ？」"

[[dialogue]]
speaker = "ソフィア"
# 「私は大丈夫ですよ。それよりジャクリーヌさんに楽しんでもらわないと」
line = "「私は大丈夫ですよ。それよりジャクリーヌさんに楽しんでもらわないと」"

[[dialogue]]
speaker = "ウズメイア"
# 「そだね、ゆゆ姫ちゃんのやりたい事をやろう」
line = "「そだね、ゆゆ姫ちゃんのやりたい事をやろう」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆ～、わかったゆ！　それじゃあっちにいってみるゆ！」
line = "「ゆ～、わかったゆ！　それじゃあっちにいってみるゆ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「オッケー、レッツゴー♪」
line = "「オッケー、レッツゴー♪」"

[[dialogue]]
speaker = "unk"
# ──こうして、ジャクリーヌの気の向くままにハロウィンパーティーの会場を駆け回った。
line = "──こうして、ジャクリーヌの気の向くままにハロウィンパーティーの会場を駆け回った。"

[[dialogue]]
speaker = "unk"
# カフェテリアに出展されたブースを一通り巡り終える頃には、ジャクリーヌは両手で抱えきれないほどのお菓子を手に入れていた。
line = "カフェテリアに出展されたブースを一通り巡り終える頃には、ジャクリーヌは両手で抱えきれないほどのお菓子を手に入れていた。"

[[dialogue]]
speaker = "ソフィア"
# 「それにしてもさすがジャクリーヌさんですね」
line = "「それにしてもさすがジャクリーヌさんですね」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆ？　何がだゆ？」
line = "「ゆ？　何がだゆ？」"

[[dialogue]]
speaker = "ソフィア"
# 「普通に歩いているだけでみんなから声をかけられていましたし、まさにハロウィンの主役って感じでした」
line = "「普通に歩いているだけでみんなから声をかけられていましたし、まさにハロウィンの主役って感じでした」"

[[dialogue]]
speaker = "ウズメイア"
# 「そだね～。ゆゆ姫ちゃんに渡したくて、それ用のお菓子を用意してたって子もいたし、イタズラされて喜んでる子もいたし」
line = "「そだね～。ゆゆ姫ちゃんに渡したくて、それ用のお菓子を用意してたって子もいたし、イタズラされて喜んでる子もいたし」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ちょっと不思議な感じだゆ……でも、そのおかげで余はとっても嬉しい気持ちになれたゆ」
line = "「ちょっと不思議な感じだゆ……でも、そのおかげで余はとっても嬉しい気持ちになれたゆ」"

[[dialogue]]
speaker = "ソフィア"
# 「良かったです。私たちも頑張った甲斐がありました」
line = "「良かったです。私たちも頑張った甲斐がありました」"

[[dialogue]]
speaker = "ウズメイア"
# 「って一緒について回って遊んでただけだけどね」
line = "「って一緒について回って遊んでただけだけどね」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆ！　お菓子もいっぱい食べたし、楽しいこともいっぱいしたゆ！　そろそろ２人の戦闘服を元に戻すゆ！」
line = "「ゆ！　お菓子もいっぱい食べたし、楽しいこともいっぱいしたゆ！　そろそろ２人の戦闘服を元に戻すゆ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「あれ、もういいんだ？」
line = "「あれ、もういいんだ？」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「余は十分に楽しんだゆ！　さっさと元に戻してハロウィンの続きを楽しむゆ！」
line = "「余は十分に楽しんだゆ！　さっさと元に戻してハロウィンの続きを楽しむゆ！」"

[[dialogue]]
speaker = "ソフィア"
# 「そうですね。一旦問題を解決して、後はのびのび楽しむことにしましょう。ヒトリさん、お願いしてもいいですか？」
line = "「そうですね。一旦問題を解決して、後はのびのび楽しむことにしましょう。ヒトリさん、お願いしてもいいですか？」"

[[dialogue]]
speaker = "ヒトリ"
# 「は、はい、いつでも大丈夫です……っ」
line = "「は、はい、いつでも大丈夫です……っ」"

[[dialogue]]
speaker = "ウズメイア"
# 「よーし、それじゃハロウィンパワーをぱーっと解放しちゃって♪」
line = "「よーし、それじゃハロウィンパワーをぱーっと解放しちゃって♪」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「任せるゆ！　それじゃ行くゆ～！」
line = "「任せるゆ！　それじゃ行くゆ～！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆ？」
line = "「ゆ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「戻ってないみたいだし？」
line = "「戻ってないみたいだし？」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「おかしいゆ？　余はちゃんと戻れって念じたゆ？」
line = "「おかしいゆ？　余はちゃんと戻れって念じたゆ？」"

[[dialogue]]
speaker = "ヒトリ"
# 「もう一度やってみてください、お願いします……」
line = "「もう一度やってみてください、お願いします……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆ～～～～～っ！！」
line = "「ゆ～～～～～っ！！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆー！？　も、戻らないゆ～！」
line = "「ゆー！？　も、戻らないゆ～！」"

[[dialogue]]
speaker = "unk"
# 本当に困ってるみたいだね？
line = "本当に困ってるみたいだね？"

[[dialogue]]
speaker = "unk"
# 嘘じゃないみたいだ
line = "嘘じゃないみたいだ"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ヒトリと約束したゆ！　悪いイタズラはもうしないゆ！」
line = "「ヒトリと約束したゆ！　悪いイタズラはもうしないゆ！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「でも、２人が元に戻らないのはやっぱり余のせいなのかゆ？」
line = "「でも、２人が元に戻らないのはやっぱり余のせいなのかゆ？」"

[[dialogue]]
speaker = "ヒトリ"
# 「ハロウィンパワーがほとんど減っていません……つまりジャクリーヌちゃんの『願い』が叶えられていないということになります」
line = "「ハロウィンパワーがほとんど減っていません……つまりジャクリーヌちゃんの『願い』が叶えられていないということになります」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆゆゆっ！？　そんなことないゆ！　余はとても楽しんでるゆ！」
line = "「ゆゆゆっ！？　そんなことないゆ！　余はとても楽しんでるゆ！」"

[[dialogue]]
speaker = "ソフィア"
# 「どういうことなんでしょうか？」
line = "「どういうことなんでしょうか？」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「ゆー、ゆー！」
line = "「ゆー、ゆー！」"

[[dialogue]]
speaker = "ヒトリ"
# 「ゆーちゃんが言うには、ジャクリーヌちゃんはちゃんとハロウィンを楽しんでるみたいです」
line = "「ゆーちゃんが言うには、ジャクリーヌちゃんはちゃんとハロウィンを楽しんでるみたいです」"

[[dialogue]]
speaker = "ヒトリ"
# 「でも、ジャクリーヌちゃんは……みんなに楽しませてもらうよりも、みんなと一緒に楽しみたいと思ってるみたいで……」
line = "「でも、ジャクリーヌちゃんは……みんなに楽しませてもらうよりも、みんなと一緒に楽しみたいと思ってるみたいで……」"

[[dialogue]]
speaker = "ヒトリ"
# 「感動ですね、ゆーちゃん……ジャクリーヌちゃんがみんなと一緒にてぇてぇしたいなんて……」
line = "「感動ですね、ゆーちゃん……ジャクリーヌちゃんがみんなと一緒にてぇてぇしたいなんて……」"

[[dialogue]]
speaker = "ゆーちゃん"
# 「てーてー♪」
line = "「てーてー♪」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「わかったゆ！　それじゃみんなと一緒に楽しむにはどうしたらいいか教えるゆ！」
line = "「わかったゆ！　それじゃみんなと一緒に楽しむにはどうしたらいいか教えるゆ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「ん～、そんなの教えるような事じゃないんだけど」
line = "「ん～、そんなの教えるような事じゃないんだけど」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「そうなのかゆ？」
line = "「そうなのかゆ？」"

[[dialogue]]
speaker = "ウズメイア"
# 「難しく考えなくてもいいし！　そゆことなら、当初の予定通りでいいでしょ！」
line = "「難しく考えなくてもいいし！　そゆことなら、当初の予定通りでいいでしょ！」"

[[dialogue]]
speaker = "ウズメイア"
# 「つまり、あたしたちと一緒にハロウィンを楽しむってね♪」
line = "「つまり、あたしたちと一緒にハロウィンを楽しむってね♪」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆー……」
line = "「ゆー……」"

[[dialogue]]
speaker = "ソフィア"
# 「仕方ありませんね、ジャクリーヌさんは。それでは私たちで教えてあげましょう！」
line = "「仕方ありませんね、ジャクリーヌさんは。それでは私たちで教えてあげましょう！」"
