[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆっゆっゆ～♪　幽霊ゾンビ退治ゆ～♪」
line = "「ゆっゆっゆ～♪　幽霊ゾンビ退治ゆ～♪」"

[[dialogue]]
speaker = "ミルフィー"
# 「ジャクリーヌさん、楽しそうだね」
line = "「ジャクリーヌさん、楽しそうだね」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「映画の中に入ったみたいで嬉しいゆ～♪」
line = "「映画の中に入ったみたいで嬉しいゆ～♪」"

[[dialogue]]
speaker = "トリシャ"
# 「冥界の怪異が相手でも全く恐れる様子がないとは……さすがはジャクリーヌさんですね」
line = "「冥界の怪異が相手でも全く恐れる様子がないとは……さすがはジャクリーヌさんですね」"

[[dialogue]]
speaker = "unk"
# こうしてゾンビ型幽霊の討伐作戦は実行された。
line = "こうしてゾンビ型幽霊の討伐作戦は実行された。"

[[dialogue]]
speaker = "unk"
# マトイ、ソフィア、舞亜、ウズメには、混乱している現場に向かい、事態の収拾に当たってもらっている。
line = "マトイ、ソフィア、舞亜、ウズメには、混乱している現場に向かい、事態の収拾に当たってもらっている。"

[[dialogue]]
speaker = "unk"
# その間に残った俺たちが、片っ端からゾンビ型幽霊を調伏していく、という作戦だ。
line = "その間に残った俺たちが、片っ端からゾンビ型幽霊を調伏していく、という作戦だ。"

[[dialogue]]
speaker = "ミルフィー"
# 「ジャクリーヌさんやトリシャさんが見た映画は、私たちみたいな格好をした子が出てくるんだよね？」
line = "「ジャクリーヌさんやトリシャさんが見た映画は、私たちみたいな格好をした子が出てくるんだよね？」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆゆっ！？　ミルフィーはあれを見てないゆ？」
line = "「ゆゆっ！？　ミルフィーはあれを見てないゆ？」"

[[dialogue]]
speaker = "ミルフィー"
# 「うん……いきなりヘレナさんに呼び出されて、これを着て戦うように言われた感じだから……」
line = "「うん……いきなりヘレナさんに呼び出されて、これを着て戦うように言われた感じだから……」"

[[dialogue]]
speaker = "ミルフィー"
# 「人工戦闘服ってその元になっているテーマにアプローチすることで力を引き出せるようになるんだよね」
line = "「人工戦闘服ってその元になっているテーマにアプローチすることで力を引き出せるようになるんだよね」"

[[dialogue]]
speaker = "ミルフィー"
# 「元になった映画を知らない私が、この戦闘服の力をちゃんと引き出せるのかな？　うーん……心配だよ……」
line = "「元になった映画を知らない私が、この戦闘服の力をちゃんと引き出せるのかな？　うーん……心配だよ……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆゆゆっ♪　だったら今からみんなで映画を見ればいいゆ♪」
line = "「ゆゆゆっ♪　だったら今からみんなで映画を見ればいいゆ♪」"

[[dialogue]]
speaker = "unk"
# さすがにそんな時間の余裕はないから
line = "さすがにそんな時間の余裕はないから"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆ～……残念だゆ……」
line = "「ゆ～……残念だゆ……」"

[[dialogue]]
speaker = "トリシャ"
# 「だ、大丈夫かと思います……。むしろ、ミルフィーさんは……最初は何も知らないままの方がいいのかもしれません……」
line = "「だ、大丈夫かと思います……。むしろ、ミルフィーさんは……最初は何も知らないままの方がいいのかもしれません……」"

[[dialogue]]
speaker = "ミルフィー"
# 「えっ、どういうことですか？」
line = "「えっ、どういうことですか？」"

[[dialogue]]
speaker = "トリシャ"
# 「その映画では、ヒロインの女の子が何も知らないまま……お爺さんから宿命を引き継いで冥界道士になります……」
line = "「その映画では、ヒロインの女の子が何も知らないまま……お爺さんから宿命を引き継いで冥界道士になります……」"

[[dialogue]]
speaker = "ミルフィー"
# 「それって……今の私の状況に近い、ということですか？」
line = "「それって……今の私の状況に近い、ということですか？」"

[[dialogue]]
speaker = "トリシャ"
# 「フフ……その通りです……。そしてミルフィーさんを助けて、一人前の道士に成長させていくのがオトモの幽霊ゾンビのお役目……」
line = "「フフ……その通りです……。そしてミルフィーさんを助けて、一人前の道士に成長させていくのがオトモの幽霊ゾンビのお役目……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「そうだったゆ！　ヒトリがてぇてぇさに悶絶してたゆ！！」
line = "「そうだったゆ！　ヒトリがてぇてぇさに悶絶してたゆ！！」"

[[dialogue]]
speaker = "ミルフィー"
# 「えっと……てぇてぇ？」
line = "「えっと……てぇてぇ？」"

[[dialogue]]
speaker = "unk"
# 仲良しの２人を見て言うことだよ
line = "仲良しの２人を見て言うことだよ"

[[dialogue]]
speaker = "unk"
# 尊いってことかな
line = "尊いってことかな"

[[dialogue]]
speaker = "トリシャ"
# 「霊衣を纏いし２人……主とオトモが魂の交わりによって協力し、冥界より湧きし幽霊ゾンビを駆逐する……それも物語の見どころのひとつ……」
line = "「霊衣を纏いし２人……主とオトモが魂の交わりによって協力し、冥界より湧きし幽霊ゾンビを駆逐する……それも物語の見どころのひとつ……」"

[[dialogue]]
speaker = "トリシャ"
# 「オトモとしてミルフィーさんの魂に触れ、壮麗な音色を奏でることで、より高みへと昇華するのでしょう……」
line = "「オトモとしてミルフィーさんの魂に触れ、壮麗な音色を奏でることで、より高みへと昇華するのでしょう……」"

[[dialogue]]
speaker = "ミルフィー"
# 「うーん、トリシャさんの表現はわかりづらいけど、つまりその、てぇてぇ感じで頑張ろうってことですね？」
line = "「うーん、トリシャさんの表現はわかりづらいけど、つまりその、てぇてぇ感じで頑張ろうってことですね？」"

[[dialogue]]
speaker = "トリシャ"
# 「にへへ、そうです……オトモダチですから……てぇてぇも可能……」
line = "「にへへ、そうです……オトモダチですから……てぇてぇも可能……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「思う存分てぇてぇするゆ！　そして２人の戦いがいよいよ始まるんだゆ！」
line = "「思う存分てぇてぇするゆ！　そして２人の戦いがいよいよ始まるんだゆ！」"

[[dialogue]]
speaker = "トリシャ"
# 「お待ちください。その前に、ミルフィーさんには基本的な霊具の使い方を覚えて頂かなくては……」
line = "「お待ちください。その前に、ミルフィーさんには基本的な霊具の使い方を覚えて頂かなくては……」"

[[dialogue]]
speaker = "ミルフィー"
# 「あ、それは助かります。人工戦闘服の起動は出来てるけど、まだ力を引き出せている感じがしなくて……」
line = "「あ、それは助かります。人工戦闘服の起動は出来てるけど、まだ力を引き出せている感じがしなくて……」"

[[dialogue]]
speaker = "ミルフィー"
# 「アイテムもいろいろ貰ったんですけど、何に使うものなのか、どうやって使うものなのか全然分からないんです」
line = "「アイテムもいろいろ貰ったんですけど、何に使うものなのか、どうやって使うものなのか全然分からないんです」"

[[dialogue]]
speaker = "トリシャ"
# 「分かりました。ミルフィーさんが一人前の道士になれるよう、私が導きましょう……」
line = "「分かりました。ミルフィーさんが一人前の道士になれるよう、私が導きましょう……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「修行パート来たゆ！」
line = "「修行パート来たゆ！」"

[[dialogue]]
speaker = "トリシャ"
# 「まずはこちらの八卦鏡です。これは死色を帯びた霊力を感知し、その在所へ誘う力を有しています……」
line = "「まずはこちらの八卦鏡です。これは死色を帯びた霊力を感知し、その在所へ誘う力を有しています……」"

[[dialogue]]
speaker = "ミルフィー"
# 「それはヘレナさんからも聞きました。この鏡はゾンビ型幽霊を見つけるレーダーの役割があるって」
line = "「それはヘレナさんからも聞きました。この鏡はゾンビ型幽霊を見つけるレーダーの役割があるって」"

[[dialogue]]
speaker = "ミルフィー"
# 「見つけた後は、捕獲するか調伏するか、ですけど……どうすればいいんですか？」
line = "「見つけた後は、捕獲するか調伏するか、ですけど……どうすればいいんですか？」"

[[dialogue]]
speaker = "トリシャ"
# 「幽霊ゾンビとは木剣を用いて戦います」
line = "「幽霊ゾンビとは木剣を用いて戦います」"

[[dialogue]]
speaker = "トリシャ"
# 「ミルフィーさんの持つ霊具の数々は、星力を通すことで霊的な存在に極めて有効な武器となるのです」
line = "「ミルフィーさんの持つ霊具の数々は、星力を通すことで霊的な存在に極めて有効な武器となるのです」"

[[dialogue]]
speaker = "ミルフィー"
# 「星力を通すんですね。わかりました、やってみます……むむむっ……！」
line = "「星力を通すんですね。わかりました、やってみます……むむむっ……！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「す、すごい集中力なの……」
line = "「す、すごい集中力なの……」"

[[dialogue]]
speaker = "トリシャ"
# 「星力の高まりを感じます……星力が変換され、次第に異なる相を見せてゆく……これがミルフィーさんにのみ与えられた特別な力です……」
line = "「星力の高まりを感じます……星力が変換され、次第に異なる相を見せてゆく……これがミルフィーさんにのみ与えられた特別な力です……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「よくわかんないけどかっこいいゆ♪」
line = "「よくわかんないけどかっこいいゆ♪」"

[[dialogue]]
speaker = "ミルフィー"
# 「……視えた！　仙桃剣！」
line = "「……視えた！　仙桃剣！」"

[[dialogue]]
speaker = "ミルフィー"
# 「どんどん行くよ～！　一の斬！　二の払い！　三薙ぎ！」
line = "「どんどん行くよ～！　一の斬！　二の払い！　三薙ぎ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「貫け！　悪霊退散！」
line = "「貫け！　悪霊退散！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ふおおお～～～、ミルフィーかっこよかったの♪」
line = "「ふおおお～～～、ミルフィーかっこよかったの♪」"

[[dialogue]]
speaker = "トリシャ"
# 「尋常ならざる動きでした……まるで星の導きを授かりし流麗な連撃……お見事です……」
line = "「尋常ならざる動きでした……まるで星の導きを授かりし流麗な連撃……お見事です……」"

[[dialogue]]
speaker = "ミルフィー"
# 「そ、そうですか？　確かに自分でも、普段とは動きが違うなって感じましたけど」
line = "「そ、そうですか？　確かに自分でも、普段とは動きが違うなって感じましたけど」"

[[dialogue]]
speaker = "ミルフィー"
# 「これが特別な人工戦闘服の能力なんだね……ヘレナさん凄すぎだよ……」
line = "「これが特別な人工戦闘服の能力なんだね……ヘレナさん凄すぎだよ……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「トリシャも同じことができるゆ？」
line = "「トリシャも同じことができるゆ？」"

[[dialogue]]
speaker = "トリシャ"
# 「フフ……私はミルフィーさんと役割が異なりますので……」
line = "「フフ……私はミルフィーさんと役割が異なりますので……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「きっとトリシャもすっごいことが出来そうなの♪　映画でもオトモは大活躍だったの～♪」
line = "「きっとトリシャもすっごいことが出来そうなの♪　映画でもオトモは大活躍だったの～♪」"

[[dialogue]]
speaker = "トリシャ"
# 「さて、どうでしょう。オトモはあくまでオトモですから……」
line = "「さて、どうでしょう。オトモはあくまでオトモですから……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆっ、ゆっ、他には何が出来るゆ？」
line = "「ゆっ、ゆっ、他には何が出来るゆ？」"

[[dialogue]]
speaker = "ミルフィー"
# 「えっと……それじゃこの粉は何なのかな？」
line = "「えっと……それじゃこの粉は何なのかな？」"

[[dialogue]]
speaker = "トリシャ"
# 「論より証拠、使って見ましょう。ジャクリーヌさん、協力して頂けますか？」
line = "「論より証拠、使って見ましょう。ジャクリーヌさん、協力して頂けますか？」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「何をすればいいゆ？」
line = "「何をすればいいゆ？」"

[[dialogue]]
speaker = "トリシャ"
# 「私たちに見えないよう、姿を消して頂ければと……」
line = "「私たちに見えないよう、姿を消して頂ければと……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆゆっ、そのくらい余にかかれば簡単なの♪」
line = "「ゆゆっ、そのくらい余にかかれば簡単なの♪」"

[[dialogue]]
speaker = "ミルフィー"
# 「わっ、一瞬で消えた」
line = "「わっ、一瞬で消えた」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ひゅ～、どろどろどろ～……なの♪」
line = "「ひゅ～、どろどろどろ～……なの♪」"

[[dialogue]]
speaker = "トリシャ"
# 「ではジャクリーヌさんがいる辺りに向かって、先程の粉に星力をこめて撒いてみてください」
line = "「ではジャクリーヌさんがいる辺りに向かって、先程の粉に星力をこめて撒いてみてください」"

[[dialogue]]
speaker = "ミルフィー"
# 「ええと……んん……こうかなっ！」
line = "「ええと……んん……こうかなっ！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆっ！？　いきなりバフっとしたゆ！？」
line = "「ゆっ！？　いきなりバフっとしたゆ！？」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「けど痛くもかゆくもないの♪　余にはなんの効果もないゆ～♪」
line = "「けど痛くもかゆくもないの♪　余にはなんの効果もないゆ～♪」"

[[dialogue]]
speaker = "unk"
# 丸見えになったぞ
line = "丸見えになったぞ"

[[dialogue]]
speaker = "unk"
# いやいや、ばっちり効いてるし
line = "いやいや、ばっちり効いてるし"

[[dialogue]]
speaker = "トリシャ"
# 「特別な星力を浴びせることにより、幽世に揺蕩う不確定な存在を現世に固定化し、顕現させる……そういった力があります……」
line = "「特別な星力を浴びせることにより、幽世に揺蕩う不確定な存在を現世に固定化し、顕現させる……そういった力があります……」"

[[dialogue]]
speaker = "ミルフィー"
# 「もしゾンビ型幽霊が目視できなくても、この粉を使えば大丈夫そうだね」
line = "「もしゾンビ型幽霊が目視できなくても、この粉を使えば大丈夫そうだね」"

[[dialogue]]
speaker = "トリシャ"
# 「これで準備は整いました。では、八卦鏡を使って敵を探し、討伐に向かいましょう」
line = "「これで準備は整いました。では、八卦鏡を使って敵を探し、討伐に向かいましょう」"

[[dialogue]]
speaker = "ミルフィー"
# 「えっと、それじゃ八卦鏡を手のひらの上に乗せて……水平になるようにして……」
line = "「えっと、それじゃ八卦鏡を手のひらの上に乗せて……水平になるようにして……」"

[[dialogue]]
speaker = "ミルフィー"
# 「この反応……近い！　むむむ……見つけた、そこだーーーっ！！！」
line = "「この反応……近い！　むむむ……見つけた、そこだーーーっ！！！」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ゆ？」
line = "「ゆ？」"

[[dialogue]]
speaker = "ミルフィー"
# 「あれ？　ジャクリーヌさんの方を指しちゃってるけど……」
line = "「あれ？　ジャクリーヌさんの方を指しちゃってるけど……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「違うゆ！　余は幽霊ゾンビじゃないゆ～っ♪」
line = "「違うゆ！　余は幽霊ゾンビじゃないゆ～っ♪」"

[[dialogue]]
speaker = "トリシャ"
# 「フフ……条件付けを間違えていますね……これでは幽霊全体を探査することになってしまいます……」
line = "「フフ……条件付けを間違えていますね……これでは幽霊全体を探査することになってしまいます……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「ある意味大成功してるゆ……」
line = "「ある意味大成功してるゆ……」"

[[dialogue]]
speaker = "ミルフィー"
# 「な、なるほど。ゾンビ型幽霊のみに絞らなきゃダメなんですね」
line = "「な、なるほど。ゾンビ型幽霊のみに絞らなきゃダメなんですね」"

[[dialogue]]
speaker = "トリシャ"
# 「ミルフィーさんになら決して難しくはないはずです。何度か練習すれば使いこなせるようになると思います……」
line = "「ミルフィーさんになら決して難しくはないはずです。何度か練習すれば使いこなせるようになると思います……」"

[[dialogue]]
speaker = "ミルフィー"
# 「わかりました。頑張ってみます！」
line = "「わかりました。頑張ってみます！」"

[[dialogue]]
speaker = "unk"
# そこら中で暴れてるみたいだけどね
line = "そこら中で暴れてるみたいだけどね"

[[dialogue]]
speaker = "unk"
# まあ探すまでもなく
line = "まあ探すまでもなく"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「水を差すようなことを言わないゆ！」
line = "「水を差すようなことを言わないゆ！」"

[[dialogue]]
speaker = "unk"
# ご、ごめんなさい
line = "ご、ごめんなさい"

[[dialogue]]
speaker = "ミルフィー"
# 「あれ？　待って……ジャクリーヌさんの他にも近くに反応があるみたい！」
line = "「あれ？　待って……ジャクリーヌさんの他にも近くに反応があるみたい！」"

[[dialogue]]
speaker = "トリシャ"
# 「フフフ、星辰の輪が回り始めたようですね……あとは運命の導きに従うのみ……」
line = "「フフフ、星辰の輪が回り始めたようですね……あとは運命の導きに従うのみ……」"

[[dialogue]]
speaker = "ジャクリーヌ"
# 「今度こそ敵ゆ！　針の指す方に突撃ゆ！」
line = "「今度こそ敵ゆ！　針の指す方に突撃ゆ！」"

[[dialogue]]
speaker = "ミルフィー"
# 「はい！　行きましょう、みなさん！」
line = "「はい！　行きましょう、みなさん！」"
